### ISSUE TITLE
Trimming old branches

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/sql-docs#1227]
When editing from the web editor there is getting a little bit of a long list https://github.com/MicrosoftDocs/sql-docs/branches/all
Could you delete the merged branches and those that got moved to your internal repo.

PS: thanks for opening the issue tracker again 👍

**Comment by MightyPen** [comment]
@nschonni Nick, I will look into this.

**Comment by MightyPen** [comment]
@nschonni Nick, Majority of branches deleted. Thanks. Closing this Issue 1227 now.

**Comment by MightyPen** [comment]
Closing.
