### ISSUE TITLE
Outdated section Catalog Properties Dialog Box

### ISSUE THREAD

**Issue by abbgrade** [MicrosoftDocs/sql-docs#1230]
The section [Catalog Properties Dialog Box](https://docs.microsoft.com/en-us/sql/integration-services/catalog/ssis-catalog?view=sql-server-2016#catalog-properties-dialog-box) is outdated.

The view `catalog.catalog_property` does not exist for SQL Server 2016 anymore.
The view `catalog.catalog_properties` does not contain a row for `VALIDATION_TIMEOUT`
The dialog does not contain a setting 'Validation Timeout'.

**Comment by MightyPen** [comment]
Closing now.  However, this Issue 1230 will still be used later to communicate updated status of internal DevOps MsEng bug 1386649 back to the customer.
CC: @douglaslMS

**Comment by douglaslMS** [comment]
@abbgrade cc @MightyPen I have just opened a PR to fix these issues. Thank you for bringing the issues to our attention. The updated page will be published tomorrow Tue Nov 13.
