### ISSUE TITLE
String Split Azure Data Warehouse Not Correct

### ISSUE THREAD

**Issue by m1nkeh** [MicrosoftDocs/sql-docs#1231]
I don't think this doc actually applies to ADW... is this a doco error, or a defect on our ADW instance?

        sql-docs/docs/t-sql/functions/string-split-transact-sql.md

**Comment by craigg-msft** [comment]
Thank you @m1nkeh I will try and verify...

**Comment by craigg-msft** [comment]
@m1nkeh the topic "applies to " section at the top currently indicates Azure SQL Datawarehouse is not supported.

**Comment by m1nkeh** [comment]
yeah @craigg-msft it got updated with this commit 6815c99fa7ef4a050661ecf59b47a1a93255e3eb the other day 👍

**Comment by nunocenteno** [comment]
It seems that this problem is happening again. I see the function as being supported in ADW which is not true (at least my ADW says so).

**Comment by m1nkeh** [comment]
> It seems that this problem is happening again. I see the function as being supported in ADW which is not true (at least my ADW says so).
annoying, do people still use ADW that much though? :)
