### ISSUE TITLE
Update Master Data Services Excel Add-in link for SQL 2017

### ISSUE THREAD

**Issue by msaravindh** [MicrosoftDocs/sql-docs#1302]
The doc does not reflect the latest link to MDS Add in for Excel for SQL 2017. Please fix this

**Comment by MightyPen** [comment]
@LeoLiMSFT Hello Leo, Can you please consider this GitHub Issue 1302.  If you decide there is corrective action to take, and you are able to make the correction, that would be ideal.  In any case, can you please enter a comment into here with your initial thoughts?
Thank you.
(GeneMi ,  2018/11/26  11:40am  Monday)
CC: @msaravindh

**Comment by douglaslMS** [comment]
@msaravindh Please respond to clarify what the issue is. See my previous comment.

**Comment by msaravindh** [comment]
@douglaslMS The issues seems to be fixed now. I can see the link updated in the doc page(https://docs.microsoft.com/en-us/sql/master-data-services/microsoft-excel-add-in/master-data-services-add-in-for-microsoft-excel?view=sql-server-2017). No changes required. Thanks
