### ISSUE TITLE
no instructions for SLE 15

### ISSUE THREAD

**Issue by boblmartens** [MicrosoftDocs/sql-docs#1304]
SUSE has release SLE 15, but there are currently no instructions for installing the MSSQL ODBC driver on SLE 15. I am wondering if there is a timetable around getting that done.

**Comment by MightyPen** [comment]
@David-Engel Hi David,  Do you have information that might be helpful here, in GitHub Issue 1304 (repo= 'MicrosoftDocs/sql-docs').
.
CC: @boblmartens

**Comment by David-Engel** [comment]
The current release does officially support SLE 15. We've tested installing on SuSE 15 Enterprise Server and it looks like the SuSE 12 MS ODBC package that is out right now works, but it requires libopenssl 1.0.0, which by default is not installable on SuSE 15. To make it available the user has to execute `sudo SUSEConnect -p sle-module-legacy/15/x86_64` prior to installing the driver (assuming they didn't enable it already during the OS installation). The next release of the MS ODBC driver (scheduled for January) will officially support SLE 15 and include these instructions. The plan for the following release (we try to release twice a year) is to not depend on libopenssl 1.0.0.

**Comment by MightyPen** [comment]
@boblmartens Hi Bob, David's response is probably the best info we have for addressing your question.
We are going to Close this Issue 1304 now.  However, if you feel further communication is needed, you can still communicate to us by @ mentioning David or myself.
Thank you for submitting this Issue.  Good luck.
