### ISSUE TITLE
Failover when Kubernetes node restarts

### ISSUE THREAD

**Issue by anildwa** [MicrosoftDocs/sql-docs#1312]
The article talks about failover sceneraio when the POD is deleted. This scenario is seldom encountered. The article does not address the scenario when the Kubernetes node reboots. As the azure-disk is attached to the node, and if the node restarts, the POD cannot be restarted on another node as the persistent volume is not available.

**Comment by MightyPen** [comment]
@MikeRayMSFT Hi Mike, I am unsure which article this GitHub Issue 1312 is referring to, but perhaps it is one of those listed below.
Can you please process this Issue:
(GitHub Issues, Process info)
sqlcontentshiproom Notebook  >  sql-docs-pr  >  GitHub-ISSUES-Plan,-Rogue1
Thanks.  (GeneMi ,  2018/11/26  11:30am  Monday)
.
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-container-ha-overview?view=sql-server-2017
.
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-kubernetes-manage?view=sqlallproducts-allversions
.
https://docs.microsoft.com/en-us/sql/linux/sql-server-ag-kubernetes?view=sqlallproducts-allversions
.
CC: @anildwa

**Comment by craigg-msft** [comment]
@anildwa can you please provide the URL of the topic you have a question about.  It will help minimize investigation time as we have a limited number of people who can help.

**Comment by craigg-msft** [comment]
Closing.  Fyi @anildwa  @MikeRayMSFT
