### ISSUE TITLE
Please re-consider policy on "duplicate content"

### ISSUE THREAD

**Issue by jzabroski** [MicrosoftDocs/sql-docs#1314]
Hi @MightyPen @ShevaDas @yunyunyunyun @cillroy

I propose that Microsoft clean up its usage of doc includes and how inline inclusion of content can be used to improve document comprehension. Currently, files in  https://github.com/MicrosoftDocs/sql-docs/tree/live/docs/includes have a cryptic naming convention not explained to the open source community.

I propose three sweeping changes:
1. Rename cryptic file names into human readable file names that are instantly understood by everyone
2. Replace `applies-to-*.md` files with a single markdown extension that generates a badge
   1. The current approach makes it hard to peer review content without remembering the conventions.
3. Consider ways to avoid hyperlinking IMPORTANT usage notes such that IMPORTANT notes common to several features are not buried in the "fescue" of a hyperlink.
   1. Does Microsoft use any click-through analytics to see how often people actually click hyperlinks inside documentation?  While it might be offensive to career documentation experts like @MightyPen who are undoubtedly great at their job, ultimately I'm suggesting Microsoft should use some machine learning and/or at least A/B tests to predict the right way to structure the documentation.  If you want to open source the click-through data, I'd be interested in analyzing user behavior (from google/bing search through to entry and exit page).

For point 3, my previous pull request https://github.com/MicrosoftDocs/sql-docs/pull/1279 was closed. You mentioned there was an internal discussion about this, but I believe, in this day and age, the internal discussion should also happen with the community and the community should weigh in.

**Comment by craigg-msft** [comment]
@jzabroski thank you for the feedback.  It would be good to revisit how we manage includes but I do not think now is the time for a variety of reasons.  

When we implemented the includes, they were not fully supported in our publishing system so the vision for how to use them was very different then now.  Also, the applies to type includes where intended to be short lived as a work around for a lack of any other way to indicate support.  Well, many things have changed including the versioning feature in our publishing system has not happened and our landscape got more complex, with the introduction of more "flavors" of SQL such as Linux and managed instance. 

We would benefit from a reorganization of the includes folder with a few sub folders such as having all of the applies to includes in one folder, product names/versions in another.  We likely should also put together guidelines for the community before we encourage includes. 

Again, I appreciate your feedback.

**Comment by craigg-msft** [comment]
no the publishing system is not Open Source.
