### ISSUE TITLE
[de-DE] relational-databases/backup-restore/restore-database-options-page.md

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/sql-docs#1316]
On the German Page (de-de) of **Restore Database (Options Page)** there, more than one example where words are put together that doesn't belong together. In all these cases **bold** words are involved. I randomly clicked on other pages an found more examples. I guess this a global issue.

---
- Your wrote: **Wiederherstellen in**auf
- It should be: **Wiederherstellen in** auf
---
-  Your wrote: of **db_owner**, **dbcreator**oder **sysadmin**verfügbar.
- It should be: of **db_owner**, **dbcreator** oder **sysadmin** verfügbar.
---
-  Your wrote: auf **Nein**klicken 
- It should be: auf **Nein** klicken

**Comment by MightyPen** [comment]
The customer, DanielGoehler, is commenting about the article at the following link:
.
https://docs.microsoft.com/de-de/sql/relational-databases/backup-restore/restore-database-options-page?view=sql-server-2017

**Comment by MightyPen** [comment]
@DanielGoehler Hello Daniel, Thank you for bringing this concern to Microsoft's attention. Our Localization expert will return from vacation later this week.  I will make sure that she is notified about this Issue 1316.
.
(GeneMi ,  2018/11/26  11:08am  Monday)
.
CC: @nokura (for MOR team)

**Comment by craigg-msft** [comment]
@nokura and @DanielGoehler can we close this issue?

**Comment by DavidPrio** [comment]
Hi @nokura the ticket needs to be assigned to me so we can see it and move it corresponding repo.
@craigg-msft can you please unassign @nokura and assign it to me? thanks!

**Comment by MightyPen** [comment]
@DavidPrio , @nokura David has been assigned this GitHub Issue 1316, as requested.
And I advanced the yellow label from Triage-2 to WillFix-3.
.
Please enter another Comment box here when you have a status update, and
please do @ mention me MightyPen (GeneMi) in the comment.  Thanks!
.
CC: @DanielGoehler

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs.de-de #77](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/77) via [**ZenHub**](https://www.zenhub.com/)

**Comment by MightyPen** [comment]
Something is broken, because I cannot change the Label.  Closing this PR 1316, in favor of newer PR 77.

**Comment by MightyPen** [comment]
Closing.

**Comment by MightyPen** [comment]
Closing now (by using a different browser).
