### ISSUE TITLE
Incorrectly suggest you can select master' size

### ISSUE THREAD

**Issue by ams0** [MicrosoftDocs/sql-docs#1326]
This [article](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-on-aks.md#create-a-kubernetes-cluster) suggests that AKS will create a master node using the size specified; in fact, masters are run under the scene by Azure and not affected by the choice of agent node size.

**Comment by MightyPen** [comment]
@RothJa, Hi Jason, Can you please take a look at this GitHub Issue 1326.  Thanks.
.
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-on-aks.md#create-a-kubernetes-cluster
.
"Configure Azure Kubernetes Service for SQL Server 2019 (preview) deployments"
https://docs.microsoft.com/sql/big-data-cluster/deploy-on-aks.md#create-a-kubernetes-cluster
.
(GitHub Issues, Process info)
sqlcontentshiproom Notebook  >  sql-docs-pr  >  GitHub-ISSUES-Plan,-Rogue1
.
GeneMi ,  2018/11/26  10:50am  Monday
.
CC: @ams0

**Comment by rothja** [comment]
@ams0 I'm going to confirm this and then make the change to the article based on what I find. Thanks for the feedback!

**Comment by rothja** [comment]
@ams0 I've confirmed your understanding and will be correcting this shortly. Thanks for catching this mistake!
