### ISSUE TITLE
copy database wizard - file table error

### ISSUE THREAD

**Issue by gmareater** [MicrosoftDocs/sql-docs#1331]
i just want to mention, when using copy wizard, if you want to move database with file table it wont work because of same directory name for  "filestream directory name"
if you use attach and detach method, it works but could not reattach original database
so i think an option is needed in the wizard for defining new name
(i will go and report it in SSMS either, just a good idea to mention here)

**Comment by MightyPen** [comment]
@stevestein Hi Steve, My guess is that @gmareater has in mind the following articles. Can you take a look.  Thanks.
.
"Use the Copy Database Wizard"
https://docs.microsoft.com/sql/relational-databases/databases/use-the-copy-database-wizard?view=sql-server-2017
.

"Copy Databases to Other Servers"
https://docs.microsoft.com/sql/relational-databases/databases/copy-databases-to-other-servers?view=sql-server-2017
.

(Steve:  GitHub Issues, Process info)
sqlcontentshiproom Notebook  >  sql-docs-pr  >  GitHub-ISSUES-Plan,-Rogue1
.
(GeneMi ,  2018/11/26  10:10am  Monday)

**Comment by craigg-msft** [comment]
@gmareater can you please include the URL of the specific article you are referring to?  Even better, could you please click the "Edit" button on the topic and suggest an edit and we can review the PR. If you suggest an edit in the actual topic will ensure we are all working on the correct / same thing. @stevestein fyi.

**Comment by CarlRabeler** [comment]
@craigg-msft @stevestein @gmareater This sounds like a feature request and perhaps a request for a doc note saying that the copy wizard doesn't work when a file table in involved. I wonder if it works when the T-SQL equivalent is used.

**Comment by gmareater** [comment]
hi
I tried my best and created PR
this is the artice i mean
"
https://docs.microsoft.com/en-us/sql/relational-databases/databases/use-the-copy-database-wizard?view=sql-server-2017
"

thanx

**Comment by stevestein** [comment]
@gmareater - Thanks for creating the PR and adding this info to the article.  I made a minor edit to your addition [directly into your PR](https://github.com/MicrosoftDocs/sql-docs/pull/1380). The updated article should go live sometime today. 

Thanks!
