### ISSUE TITLE
sql/t-sql/queries/update-transact-sql (opendatasource)

### ISSUE THREAD

**Issue by pez-public** [MicrosoftDocs/sql-docs#1350]
[This](https://docs.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-2017#q-updating-data-in-a-remote-table-by-using-the-opendatasource-function) example is not relevant. The query uses the OPENQUERY function rather than then OPENDATASOURCE function. Additionally, the query is just a copy of the previous example.

Once the query is changed, the description should also be changed because currently it says the query would INSERT a row, however, this doc is for UPDATE.

**Comment by douglaslMS** [comment]
@pez-public Thanks for bringing this poor example to our attention. I have fixed the text and the example in the linked PR (which may not be viewable for you). The updated page will be published within the next day or so.
