### ISSUE TITLE
Re-open #1239  "Incorrect index_type_desc for spatial index"

### ISSUE THREAD

**Issue by jzabroski** [MicrosoftDocs/sql-docs#1351]
#1239 

As I explained in my comments after @stevestein closed the issue, my pull request is CORRECT.

I believe you are confusing `sys.indexes` with `sys.dm_db_index_physical_stats`

Here is my repro script for SQL Server 2016 Developer Edition - I've also ran similar tests a few weeks ago on a SQL Server 2017 RDS instance in AWS, but I'm not going to spend extra cycles beyond a local repro :
```sql
USE [master];
GO

CREATE DATABASE [Test];
GO

USE [Test];
GO

CREATE TABLE [dbo].[NonClusteredGeometryData] (
	[id] BIGINT IDENTITY(1,1) NOT NULL,
	geo GEOMETRY NOT null,
	CONSTRAINT [PK_NonClusteredGeometryData] PRIMARY KEY (
		ID
	)
);
GO

CREATE
SPATIAL
INDEX
IX_NonClusteredGeometryData_geo
ON
dbo.NonClusteredGeometryData
(geo)
USING GEOMETRY_AUTO_GRID
WITH (BOUNDING_BOX =
(XMIN = 0, YMIN = 0, XMAX = 10000000000, YMAX = 0.1));
GO

SELECT
	SERVERPROPERTY('Edition') AS [SERVERPROPERTY('Edition')],
	@@VERSION AS [SQL Server and OS Version Info],
	index_physical_stats.index_type_desc,
	i.object_id,
	i.name,
	i.index_id,
	i.type,
	i.type_desc
FROM sys.dm_db_index_physical_stats ( DB_ID(), DEFAULT, DEFAULT, DEFAULT,'DETAILED') AS index_physical_stats
	JOIN sys.indexes i	ON i.index_id = index_physical_stats.index_id AND i.object_id = index_physical_stats.object_id;
```
Here is the output of that script:

| SERVERPROPERTY('Edition') | SQL Server and OS Version Info | index_type_desc | sys.indexes object_id | sys.indexes name | sys.indexes index_id | sys.indexes type | sys.indexes type_desc |
| ------------------------------ | ----------------------------------- | ------------------ | ---------------------- | ---------------------- | ---------------------- | ------------------ | ----------------------- |
| Developer Edition (64-bit) | Microsoft SQL Server 2016 (SP1-CU1) (KB3208177) - 13.0.4411.0 (X64)   Jan  6 2017 14:24:37   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 6.3 <X64> (Build 17134: ) | CLUSTERED INDEX | 565577053 | PK_NonClusteredGeometryData | 1 | 1 | CLUSTERED |
| Developer Edition (64-bit) | Microsoft SQL Server 2016 (SP1-CU1) (KB3208177) - 13.0.4411.0 (X64)   Jan  6 2017 14:24:37   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 6.3 <X64> (Build 17134: ) | **EXTENDED INDEX** | 565577053 | IX_NonClusteredGeometryData_geo | 384000	| 4 | SPATIAL |
```

**Comment by jzabroski** [comment]
@stevestein  However, `PRIMARY XML INDEX` and `XML INDEX` are correct:

```sql
USE [master];
GO

CREATE DATABASE [Test3];
GO

USE [Test3];
GO

CREATE TABLE [dbo].[NonClusteredXml] (
	[id] BIGINT IDENTITY(1,1) NOT NULL,
	XmlDoc XML NOT NULL,
	CONSTRAINT [PK_NonClusteredXml] PRIMARY KEY (
		ID
	)
);
GO

CREATE PRIMARY XML INDEX PXML_NonClusteredXml
ON dbo.NonClusteredXml (XmlDoc);
GO

CREATE
XML
INDEX
IX_NonClusteredXml_XmlDoc
ON
dbo.[NonClusteredXml]
(XmlDoc) USING XML INDEX PXML_NonClusteredXml FOR PATH;
GO

SELECT
	SERVERPROPERTY('Edition') AS [SERVERPROPERTY('Edition')],
	@@VERSION AS [SQL Server and OS Version Info],
	index_physical_stats.index_type_desc,
	i.object_id,
	i.name,
	i.index_id,
	i.type,
	i.type_desc
FROM sys.dm_db_index_physical_stats ( DB_ID(), DEFAULT, DEFAULT, DEFAULT,'DETAILED') AS index_physical_stats
	JOIN sys.indexes i	ON i.index_id = index_physical_stats.index_id AND i.object_id = index_physical_stats.object_id;
```

**Comment by jzabroski** [comment]
Saw your comment, @stevestein . Thanks. CLosing

**Comment by MightyPen** [comment]
@stevestein Steve, I now understand, PR 1239 was the real item for this situation. This Issue 1351 seems redundant or overlapping.  PR is signed off, thus this overlapping Issue is Fixed. I shall so mark it. Thanks.
htt ps://githu b. com/MicrosoftDocs/sql-do cs/pull/1239
https://github.com/MicrosoftDocs/sql-docs/pull/1239
