### ISSUE TITLE
Samples Link Points to Dead Codeplex Site

### ISSUE THREAD

**Issue by smeddows** [MicrosoftDocs/sql-docs#1356]
The link for the SSRS samples (https://go.microsoft.com/fwlink/?LinkId=177889) Points to a Codeplex site that is no longer available.

**Comment by craigg-msft** [comment]
@maggiesMSFT  can you please address.

**Comment by maggiesMSFT** [comment]
Thanks, @smeddows! You're right, CodePlex is archived. Investigating.

**Comment by maggiesMSFT** [comment]
Hi, @smeddows -- I found the samples in the CodePlex archive and updated the link. Thanks for the heads up! If you're interested, here's the updated link: https://archive.codeplex.com/?p=msftrsprodsamples.

**Comment by MightyPen** [comment]
The FwLink 177889 now points to.....
https://archive.codeplex.com/?p=msftrsprodsamples 
.
Maggie says this Issue 1356 is Fixed (in the FwLink UI) and Completed.  Goodie, so now I will update the Outcome label, and will Close this Issue.

**Comment by smeddows** [comment]
It looks great.   Thanks
