### ISSUE TITLE
Include ACS Engine as an altertive way of deploying Kubernetes in Azure

### ISSUE THREAD

**Issue by jadarsie** [MicrosoftDocs/sql-docs#1372]
While Kubeadm works, the deployment process should be simpler using ACS Engine.

https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-guidance?view=sqlallproducts-allversions#kubernetes

**Comment by MightyPen** [comment]
@rothja Hi Jason, Can you please process this GitHub Issue 1372.  Thanks.
CC: @jadarsie

**Comment by rothja** [comment]
@jadarsie Currently we talk about three options for hosting Kubernetes. One of those is AKS for deploying in Azure. We decided that we probably didn't want to cover both ACS and AKS, so we went demonstrate AKS only. Is AKS interchageable for you instead of ACS? Thanks!

**Comment by jadarsie** [comment]
AKS and ACS are not interchangeable. One is managed K8S, the other is un-managed K8S.

Compared to Kubeadm, ACS Engine should provide a faster and friction-less deployment experience for somebody willing to run the solution on top of an un-managed cluster on Azure. I imagine that just mentioning the option and redirecting to an existing doc page would be enough.

As you wish guys, I was going through the docs and figured that you may liked the feedback. Feel free to close whenever you like.

**Comment by rothja** [comment]
@jadarsie The feedback is great! Thanks for explaining your case here. I'll do a little digging with the product team and see what we want to do.

**Comment by jadarsie** [comment]
FYI, I just realized that [ACS Engine](https://github.com/Azure/acs-engine) is [deprecated](https://github.com/Azure/acs-engine/commit/286893edb186d04e26341e7b1fb00f51cbcfc133) since yesterday.

I will be replaced by [AKS Engine](https://github.com/Azure/aks-engine). After a quick look, I have the impression that, from a K8S POV, both engines are supposed to achieve the same result.

**Comment by rothja** [comment]
@jadarsie Sorry for the delay. I spoke with the product team, and they confirmed that we are only testing and supporting AKS for an Azure deployment target. It is possible you could get it working on ACS, but we're not planning on adding that documentation. We feel it is better to steer customers to the future (AKS). Thanks again for the feedback!
