### ISSUE TITLE
Add prefix to environment variables used by `mssqlctl create cluster`

### ISSUE THREAD

**Issue by jadarsie** [MicrosoftDocs/sql-docs#1373]
https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-guidance?view=sqlallproducts-allversions#define-environment-variables

In order to avoid involuntary overrides of the variables values, I would add a prefix to their names.

E.x.: MYPREFIX_DOCKER_REPOSITORY instead of DOCKER_REPOSITORY

**Comment by craigg-msft** [comment]
@jadarsie   Our team has examined this GitHub Issue.  Your suggestion is a good one but we have limited team members to work on the content and we learn from how the community explains things and documents for other community members.  Please click the Edit button on the article's webpage, and to simply type in the fix, and click the buttons to create a GitHub pull request.  We will then examine your PR. Thank you for your time!

**Comment by MightyPen** [comment]
Thank you.  Closing this Issue 1373.
