### ISSUE TITLE
Installation instructions for Microsoft ODBC Driver for Ubuntu 14 do not work

### ISSUE THREAD

**Issue by jdavisp3** [MicrosoftDocs/sql-docs#1375]
The Ubuntu 14 instructions recommend installing `unixodbc-dev`:

```
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install msodbcsql17
# optional: for bcp and sqlcmd
sudo ACCEPT_EULA=Y apt-get install mssql-tools
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashrc
# optional: for unixODBC development headers
sudo apt-get install unixodbc-dev
```

However, the MS repo for Ubuntu 14 does not seem to provide that package and the one provided by the standard Ubuntu 14 repo conflicts with the dependencies of `msodbcsql17`:

```
The following packages have unmet dependencies:
 unixodbc-dev : Depends: unixodbc (= 2.2.14p2-5ubuntu5)
                Depends: odbcinst1debian2 (= 2.2.14p2-5ubuntu5) but 2.3.1-3 is to be installed
```

Should the MS repo provide this package? Or are the instructions wrong?

**Comment by jdavisp3** [comment]
Somewhat similar to https://github.com/Microsoft/msphpsql/issues/287 but for Ubuntu 14.

**Comment by jdavisp3** [comment]
Found some instructions for a work-around: https://gist.github.com/joecampo/6f777a659b8132b9d6fe1c3589df394c

This would be a lot easier if you provided the `-dev` package as well.

**Comment by MightyPen** [comment]
@jdavisp3 Hello Dave, For us to consider a GitHub Issue of this nature, we need you to provide us with the https address of the specific documentation article you feel is lacking or is in error.
When you add a comment with the link, please @ mention me so I will know.
Thanks a lot.

**Comment by karinazhou** [comment]
Hi @jdavisp3,

Thank you for pointing this out. For now, the MS repo doesn't have the unixodbc-dev package for Ubuntu 14.04 by default. A possible workaround is to manually get and install the package. Here's an example to do it:
```
wget http://mirrors.kernel.org/ubuntu/pool/main/libt/libtool/libltdl-dev_2.4.2-1.7ubuntu1_amd64.deb
dpkg -i libltdl-dev_2.4.2-1.7ubuntu1_amd64.deb
wget http://launchpadlibrarian.net/174316120/unixodbc-dev_2.3.1-3_amd64.deb 
dpkg -i unixodbc-dev_2.3.1-3_amd64.deb
```
NOTE: Please skip first two command lines if you already have `libltdl-dev`.

The installation doc needs to be updated for Ubuntu 14.04. We will take your suggestion about including unixodbc-dev in the repo into consideration in our future releases.

Thanks,
Karina

**Comment by karinazhou** [comment]
Hi @MightyPen ,

I have created a PR with the update: 
[https://github.com/MicrosoftDocs/sql-docs-pr/pull/8360](url)

Please take a look at it.

Thanks,
Karina

**Comment by MightyPen** [comment]
@jdavisp3 We have merged Karina's internal Microsoft PR 8360.  The change should be visible on our live Docs website by late this afternoon. (Thanks Karina!)
So, this Issue 1375 has achieved documentation improvement, thus it should be Closed now.
.
However, this Issue 1375 Comment boxes can be used for further communication if necessary, by using the @ mention syntax.
Thank you for submitting this Issue.  Good luck.
CC: @karinazhou

**Comment by jdavisp3** [comment]
Thanks everyone!

**Comment by hitokiri** [comment]
In the new versions, this problem is resolved by installing the following package

`sudo apt install libodbc1
`
after that you can run the following command 

`sudo apt-get install unixodbc-dev`
