### ISSUE TITLE
Azure SQL Data Warehouse Does Not Support Query Store

### ISSUE THREAD

**Issue by JohnMiner3** [MicrosoftDocs/sql-docs#1379]
The following link shows that Azure SQLDW supports Query Store.  This is not accurate.

https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-2017

**Comment by MikeRayMSFT** [comment]
@pmasl can you review?

**Comment by MikeRayMSFT** [comment]
@JohnMiner3 - thank you for this submission - we're reviewing it.

**Comment by julieMSFT** [comment]
@JohnMiner3 - Hi John, thank you for your input. I have reviewed this article. The applies to line contains Azure SQL Data Warehouse but it is greyed out meaning this topic does _not_ apply to Azure SQL Data Warehouse. Please let me know if you see something different. 

![image](https://user-images.githubusercontent.com/44736634/51006843-e7ce9b00-14f9-11e9-9cc6-7d9c0c9d821f.png)

**Comment by julieMSFT** [comment]
@JohnMiner3 - Hi John, I hope this addressed your issue. I will proceed with closing it at this time. Please feel free to contact us if we can be of further assistance.
#please-close
