### ISSUE TITLE
View and save the result Item Number 1 shows wrong information

### ISSUE THREAD

**Issue by jon49** [MicrosoftDocs/sql-docs#1389]
In the directions:

> # View and save the result Item
> 1. On the View menu, select Toggle Editor Group Layout to switch to vertical or horizontal split layout.

It shows going to the menu `View > Toggle Editor Group Layout`. This is confusing as that button doesn't exist. (Windows 10)

I did find the button which does perform the action under `View > Editor Layout > Flip Layout`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf7ad1cc-5659-1724-9ade-14859e2d469d
* Version Independent ID: 60d1da3a-3cbc-657c-e263-6fcefd918e23
* Content: [Use the Visual Studio Code mssql extension for SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-develop-use-vscode?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-develop-use-vscode.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-develop-use-vscode.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@rothja Hi Jason, can you please process this Issue 1389 (about article 'sql-server-linux-develop-use-vscode.md').
CC: @jon49

**Comment by rothja** [comment]
@jon49 Thanks for raising this issue. I'll try to reproduce. It is possible that the UI has changed since the article was written.

**Comment by rothja** [comment]
@jon49 I see what you're seeing. I'm going to update the instructions. Thank you!

**Comment by MightyPen** [comment]
PRs = 1389, 8461, for commit ab7a128.
