### ISSUE TITLE
Trying to download SQL Server on Linux

### ISSUE THREAD

**Issue by sbaileypn** [MicrosoftDocs/sql-docs#1396]
I get Unable to locate package mssql-server
Can you help me out?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Get started with SQL Server on Ubuntu](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-2017)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@jszazzing Hello. I'm sorry you're having trouble getting SQL Server. Can you paste in the commands you run and the error you get into this thread? I'll see if there is something wrong with the steps in this Ubuntu quickstart. Thank you.

**Comment by jszazzing** [comment]
root@ubuntu:/home/steven# sudo apt-get install -y mssql-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package mssql-server

**Comment by jszazzing** [comment]
root@ubuntu:/home/steven# sudo add-apt-repository "$(wget -qO-
https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list)"
root@ubuntu:/home/steven# sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Hit:3 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [107
kB]
Hit:5 https://packages.microsoft.com/ubuntu/16.04/mssql-server-2017 xenial
InRelease
Ign:6 https://download.webmin.com/download/repository sarge InRelease
Hit:7 https://packages.microsoft.com/ubuntu/16.04/mssql-server-preview
xenial InRelease
Hit:8 https://download.webmin.com/download/repository sarge Release
Fetched 214 kB in 0s (290 kB/s)
Target Packages (main/binary-amd64/Packages) is configured multiple times
in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/mssql-server.list:1
Target Packages (main/binary-all/Packages) is configured multiple times in
/etc/apt/sources.list:55 and /etc/apt/sources.list.d/mssql-server.list:1
Target Translations (main/i18n/Translation-en_US) is configured multiple
times in /etc/apt/sources.list:55 and
/etc/apt/sources.list.d/mssql-server.list:1
Target Translations (main/i18n/Translation-en) is configured multiple times
in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/mssql-server.list:1
Target DEP-11 (main/dep11/Components-i386.yml) is configured multiple times
in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/mssql-server.list:1
Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple
times in /etc/apt/sources.list:55 and
/etc/apt/sources.list.d/mssql-server.list:1
Reading package lists... Done
W: Target Packages (main/binary-amd64/Packages) is configured multiple
times in /etc/apt/sources.list:55 and
/etc/apt/sources.list.d/mssql-server.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times
in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/mssql-server.list:1
W: Target Translations (main/i18n/Translation-en_US) is configured multiple
times in /etc/apt/sources.list:55 and
/etc/apt/sources.list.d/mssql-server.list:1
W: Target Translations (main/i18n/Translation-en) is configured multiple
times in /etc/apt/sources.list:55 and
/etc/apt/sources.list.d/mssql-server.list:1
W: Target DEP-11 (main/dep11/Components-i386.yml) is configured multiple
times in /etc/apt/sources.list:55 and
/etc/apt/sources.list.d/mssql-server.list:1
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple
times in /etc/apt/sources.list:55 and
/etc/apt/sources.list.d/mssql-server.list:1
W: Target Packages (main/binary-amd64/Packages) is configured multiple
times in /etc/apt/sources.list:55 and
/etc/apt/sources.list.d/mssql-server.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times
in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/mssql-server.list:1
W: Target Translations (main/i18n/Translation-en_US) is configured multiple
times in /etc/apt/sources.list:55 and
/etc/apt/sources.list.d/mssql-server.list:1
W: Target Translations (main/i18n/Translation-en) is configured multiple
times in /etc/apt/sources.list:55 and
/etc/apt/sources.list.d/mssql-server.list:1
W: Target DEP-11 (main/dep11/Components-i386.yml) is configured multiple
times in /etc/apt/sources.list:55 and
/etc/apt/sources.list.d/mssql-server.list:1
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple
times in /etc/apt/sources.list:55 and
/etc/apt/sources.list.d/mssql-server.list:1
root@ubuntu:/home/steven# sudo apt-get install -y mssql-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package mssql-server

**Comment by rothja** [comment]
@jszazzing. Thank you. I've got a machine setup to test now. Are you on Ubuntu 18.04? 16.04? Something else? Thanks.

**Comment by rothja** [comment]
@jszazzing, on my Ubuntu machine, I don't get this error. I'm not sure what the difference could be. I see you're running the commands as root. You could try repeating all the commands run as a regular user. The sudo is suggested in places where you need the elevated permissions. Sorry!

**Comment by rothja** [comment]
@jszazzing One other thing to try is to run SQL Server in a Docker Container. There is almost no difference between running in a Docker container versus running locally, and the Docker container should always run consistently no matter what. Check out the Docker quickstart in the documentation as well as the Docker Configuration Guide that it points to. If you do use this for your SQL Server running on your local machine, you'll want to use one of the persistence options for your data. That way if your container is removed, you still have your data, and you can start a new container that is attached to that data directory.

**Comment by rothja** [comment]
@jszazzing , I'm sorry we couldn't get your deployment working. If you continue to have issues on your machine, our support team might be able to further investigate. Or you might be able to find help on the forums. However, I think it is also possible that you'll find the Docker containers with Developer Edition to be a good solution for your scenario. Are you OK if I close this Git Issue out at this time? Thank you!

**Comment by Tomas2046** [comment]
https://github.com/MicrosoftDocs/sql-docs/labels/Issue-Status-2-Author-will-triage
