### ISSUE TITLE
Incorrect Column Description - sys.dm_exec_sessions client_version

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/sql-docs#14]
Hello,

On [sys.dm_exec_sessions's documentation page](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-sessions-transact-sql), I believe the description for column client_version is incorrect.

According to that page, this column shows the "TDS protocol version of the interface that is used by the client to connect to the server. The value is NULL for internal sessions. Is nullable."

However, while this column holds a value that **correlates** with the TDS version, its **not** the actual TDS version. Rather, the TDS version is reported elsewhere in the management views, in sys.dm_exec_connection’s protocol_version column.

## Correlation
From my experimentation, client_version's values correlate to TDS version as follows:

TDS Version | TDS Version in Binary ([ref](https://msdn.microsoft.com/en-us/library/dd339982.aspx)) | client_version Value
----|-------------|---
7.0|0x00000070|2
7.1|0x00000071|3
7.1r1|0x01000071|4
7.2|0x02000972|5
7.3A|0x03000A73|6
7.3B|0x03000B73|7
7.4|0x04000074|7

There might be a mapping for client_version =1, but, if there is, I haven't been able to determine what it is. :-) There's the possibility that it's for TDS 4.2 (0x04020000), but I don't have any TDS 4.2 test code around to use to confirm.

If it would help, I can provide/post the source for a very simple C# console application that you can use to verify the above mappings.

## Interpretation
I'm not sure what exactly client_version represents. :-) However, it's clearly not the TDS version or even the major number portion of the TDS version.

If I had to make a wild guess, I'd wonder if client_version reflects the compatibility mode SQL Server's TDS parsing mode using for the connection.

## Suggestion
Would you consider updating client_version's description to describe what this field indicates? Possibly, a table showing the mappings between TDS version and client_version values could be included in the new description.

Thank you!

**Comment by craigg-msft** [comment]
@bgribaudo thank you for the feedback.  I am going to copy the text from both issues you created and put them in an internal tracking item for the author to review.  We only recently lit up the public side of our content and we had not intended to have the "issues" feature enabled as we are not staffed to manage issues and PRs for so many topics.  We hope to some day but not now.  Apologies for the confusion.  My suggestion is to also past a summed version of your question on the bottom of the topic, in the comments section, then after some reviews the feedback and updates the topic as needed, they can respond via the comments area.  https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-sessions-transact-sql.
--
