### ISSUE TITLE
Wrong CTP version for R/Python App feature

### ISSUE THREAD

**Issue by slunyakin** [MicrosoftDocs/sql-docs#1416]
Hi,

There is a mistake in CTP version in the row "Deploy Python and R apps. (CTP 2.1)". This feature from CTP 2.2. Please, fix it.

Regards,
Sergiy

**Comment by HeidiSteen** [comment]
Hi Sergiy, can you send a link to the page?  I did a string search and can't find it.  Thanks!

**Comment by MightyPen** [comment]
@slunyakin Hello Sergiy, Please provide a link to whichever article you are referring to in an Issue.

Mike Ray will triage this Issue 1416.  Mike thinks he knows which article this Issue is referring to.
Thanks.

@HeidiSteen , @MikeRayMSFT

**Comment by MikeRayMSFT** [comment]
https://github.com/MicrosoftDocs/sql-docs/edit/live/docs/sql-server/what-s-new-in-sql-server-ver15.md

**Comment by MikeRayMSFT** [comment]
Submitted a PR in private repository. Closing issue.

**Comment by slunyakin** [comment]
Yes. Page https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/what-s-new-in-sql-server-ver15.md 
Section Bigdata Cluster

And page  https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-ver15?view=sqlallproducts-allversions#bigdatacluster

Point "Deploy Python and R apps. (CTP 2.1)" still has CTP2.1

**Comment by MikeRayMSFT** [comment]
@slunyakin - thank you for this submission. This feature was introduced first in CTP 2.1 and improved for CTP 2.2. The What's New article - as published is correct.  We will not merge these changes in to the article.
