### ISSUE TITLE
Typo on 'Install sqlpackage' debian dependencies'

### ISSUE THREAD

**Issue by joalcava** [MicrosoftDocs/sql-docs#1425]
Hi, I was looking at the docs to [install sqlpackage on linux](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-2017) and realized a typo on the debian dependencies.
It says: `sudo apt-get install libuwind8` and I think it must be `sudo apt-get install libunwind8`
I din't submit a PR because I'm not 100% sure if it is really a typo.

**Comment by MightyPen** [comment]
Article is:
https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-2017

**Comment by MightyPen** [comment]
@stevestein Steve, can you please process this Issue 1425.  Thanks.
.
title: Download and install sqlpackage | Microsoft Docs
description: 'Download and Install sqlpackage for Windows, macOS, or Linux'
ms.custom: "tools|sos"
ms.date: "06/18/2018"
ms.prod: sql
ms.reviewer: "alayu; sstein"
ms.prod_service: sql-tools
ms.topic: conceptual
author: "pensivebrian"
ms.author: "broneill"
manager: craigg
---
# Download and install sqlpackage
.
@joalcava

**Comment by stevestein** [comment]
@joalcava - yes, that is a typo. Good catch!  There are no doc updates until after the holidays so the update won't appear until next week.

Thanks!

**Comment by stevestein** [comment]
Fixed in https://github.com/MicrosoftDocs/sql-docs-pr/pull/8603
