### ISSUE TITLE
Backup while encrypting for TDE

### ISSUE THREAD

**Issue by kdimitris33** [MicrosoftDocs/sql-docs#1442]
After discussing it internally, it appears that one can run a BACKUP process while doing the encryption (i.e. no need to stop the encryption to do so). This page gives the opposite impression in its "Restrictions" section - perhaps some rephrasing may be in order?

**Comment by MightyPen** [comment]
@kdimitris33 Hello kdimitris33, In order for us to consider this Issue 1442, we need to be provided with a link to whichever documentation article this Issue prompted the filing of this Issue.
.
Can you please add a new Comment here to give the needed link?
In the Comment @ mention me so I know you have updated this Issue.
Thank you.

**Comment by baleng** [comment]
@MightyPen 
https://docs.microsoft.com/it-it/sql/relational-databases/security/encryption/transparent-data-encryption?view=sql-server-2017#restrictions
The following operations are not allowed during initial database encryption, key change, or database decryption: Starting a database or database file backup.

**Comment by aliceku** [comment]
I will discuss with the feature team, I am not convinced that doing this is a good idea.

**Comment by baleng** [comment]
@aliceku - Tested  ON-PREMISE - Microsoft SQL Server 2016 (SP2)

despite the documentation quotes that is not possible, and in the sys.messages there is message_id 3023 "Backup, file manipulation operations (such as ALTER DATABASE ADD FILE) and encryption changes on a database must be serialized. Reissue the statement after the current backup or file manipulation operation is completed." 
it is possible to peform a backup on the same db while the encryption is in progress on the same db.
the encryption is performed in backgrond after the command is launched, you get immediatly "commands completed succesfully". i think it's not possible to start in the same moment a backup and an encryption (and you should get the error 3023) , but after the encryption starts, backups run succesfully. 

if the backup fails , while the encryption is in progress, reverting the previous state on the db (encryption on, or off) causes the error 33122 "This command requires a database encryption scan on database '%.*ls'. However, the database has changes from previous encryption scans that are pending log backup. Take a log backup and retry the command."
you need just to put in simple rec mode the db, or just do a log backup as the error states.
so a clarification could be proposed in the doc.
CC: @kdimitris33  - @MightyPen

**Comment by MightyPen** [comment]
@VanMSFT Hi Van, here in Issue 1442, AliceKu has provided info that you can probably use to correct the inaccuracy of the Docs article.  It sounds like the SQL product contains an error message that suffers the same inaccuracy - if so, it might be good to mention in the article that IF the error message is seen that it should be considered out-of-date?  Thanks.

**Comment by VanMSFT** [comment]
Hello @aliceku, can you please confirm @baleng comments above and see if we need to make changes to the docs regarding removing the line, "Starting a database or database file backup."

Thanks!

**Comment by aliceku** [comment]
@VanMSFT After confirmation, success of this operation might be due to factors like database size.  There are cases where it doesn't work, and our best practices have to cover all cases.  We still do not generally recommend this.  The documentation will not change.

**Comment by VanMSFT** [comment]
Thanks @aliceku! @kdimitris33 - We appreciate your contribution and interest in helping with our documentation. If there are any questions, please let us know. Per Alice's response, I will go ahead and close this issue.
