### ISSUE TITLE
last_logical_writes description is inconsistent with other columns

### ISSUE THREAD

**Issue by EitanBlumin** [MicrosoftDocs/sql-docs#1447]
In [sys.dm_exec_query_stats (Transact-SQL)](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-query-stats-transact-sql) line 55:

|**last_logical_writes**|**bigint**|Number of the number of buffer pool pages dirtied the last time the plan was executed. If a page is already dirty (modified) no writes are counted.<br /><br /> Will always be 0 querying a memory-optimized table.|  

Is inconsistent with the description of other similar columns. Is this intentional?
Do all logical reads and writes columns count number of pages?
Also, the description says "Number of the number of" which is obviously a mistake.

**Comment by MightyPen** [comment]
@EitanBlumin Hello Eitan, The description of 'last_logical_writes'  looks correct to me.  Your catch of the grammar or copy&paste error is certainly correct, and I will make this fix (internal PR 8560).  Thank you for bringing this error to our attention.
With this fix, I am now Closing this Issue 1447.
