### ISSUE TITLE
dm_os_performance_counters Permissions for SQL DB 

### ISSUE THREAD

**Issue by mikewo** [MicrosoftDocs/sql-docs#1452]
The article at https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-performance-counters-transact-sql?view=sql-server-2017 indicates that you need to have View Database state permissions for Azure SQL DB to use the DMV; however, when I create a new login, grant it rights to the database, then specifically grant it view database state to the database, when I attempt to use that SQL Login to view the dmv it returns an error. You can not grant view server state rights in SQL DB.

Msg 300, Level 14, State 1, Line 1
VIEW SERVER STATE permission was denied on object 'server', database 'master'.
Msg 297, Level 16, State 1, Line 1
The user does not have permission to perform this action.

Even though the error above says database 'master', I was running the DMV query in the context of the target database, not master.

I think the documentation is incorrect, or there is a bug.

**Comment by MightyPen** [comment]
(author: stevestein , ms.author: sstein)
@stevestein @CarlRabeler  Can one of you two please process this Issue 1452.  Steve owns the article, but Carl's expertise with Azure SQL DB might be handy for this Issue.
Thanks, GeneMi.
CC: @mikewo

**Comment by CarlRabeler** [comment]
Adding Van as he owns security these days

**Comment by CarlRabeler** [comment]
@VanMSFT

**Comment by VanMSFT** [comment]
Hi @mikewo and @baleng! Thanks for reporting this and providing details. We are doing additional investigation into our document permissions for DMVs and will follow-up with some edits.

**Comment by mikewo** [comment]
Thanks. If @baleng is correct that means that at this time it is not possible for an account other than the Server Admin account for Azure SQL DB to view this DMV. View Server State is not a permission you can grant to other users. This is annoying because it means you can't replicate the permissions of the Server Admin level account with a different account if you don't want to provide that high of a level of access to something like a monitoring system.

**Comment by CarlRabeler** [comment]
Adding Van

**Comment by VanMSFT** [comment]
Hi @mikewo, thanks again for bringing this issue up. We're working on investigating and updating the documentation, and will track this in our ticketing system: Feature [1427119](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1427119).  Since we're now tracking this internally, I'll proceed with closing out this Issue. However, please feel free to contact us if you have any additional information. Thanks again!
