### ISSUE TITLE
Incorrect schema namespace https://www.w3.org/2001/XMLSchema

### ISSUE THREAD

**Issue by marius-klimantavicius** [MicrosoftDocs/sql-docs#1457]
As part of 3f4996c8436b006d2c55fa164a3d79356575c976 all "http:" were replaced with "https:", this however breaks some examples that have xml namespaces (at least xsd namespace in sql-docs/docs/relational-databases/sqlxml-annotated-xsd-schemas-xpath-queries/sqlxml-4-0-net-framework-support-using-bulk-load.md):
Current:
`<xsd:schema xmlns:xsd="https://www.w3.org/2001/XMLSchema"`
Should be:
`<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"`

**Comment by MightyPen** [comment]
@marius-klimantavicius Thanks for reporting this, I will take a look at this sometime in January 2019.

**Comment by MightyPen** [comment]
fyi GeneMi-to-self: Info gathered in.....
C:\Users\genemi\OneDrive - Microsoft\Main-OD\Issue-1457-https\

**Comment by MightyPen** [comment]
https://github.com/MicrosoftDocs/sql-docs-pr/pull/8749
.
The PR 8749 completes the fix of this Issue 1457.
.
@marius-klimantavicius The fixes are now merged in, for the concern reported by you in this Issue 1457.  Thank you for reporting this documentation bug to us.
I am now Closing this Issue 1457.

**Comment by MightyPen** [comment]
Closing.
