### ISSUE TITLE
Use Active Directory authentication with SQL Server on Linux - Login failed. login from an untrusted domain

### ISSUE THREAD

**Issue by eliassal** [MicrosoftDocs/sql-docs#1463]
I followed all instructions  at 
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017 
I was able to add mydomain\mylogin to sql, in the step before last step, when I try to login through SSMS from my laptop, I get the following
TITLE: Connect to Server
Cannot connect to ubuntu17Sql.SALAM.NET.

ADDITIONAL INFORMATION:
Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication. (Microsoft SQL Server, Error: 18452)
For help, click: http://go.microsoft.com/fwlink?ProdName=Microsoft%20SQL%20Server&EvtSrc=MSSQLServer&EvtID=18452&LinkId=20476

The above  link lands me nowhere
Thanks for your help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Active Directory authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* GitHub Login: @meet-bhagdev
* Microsoft Alias: **meetb**

**Comment by rothja** [comment]
This seems to be a duplicate issue. Closing this one out.
