### ISSUE TITLE
login failed for user 'SA'

### ISSUE THREAD

**Issue by rajendrarama** [MicrosoftDocs/sql-docs#1465]
I have followed the documentation and everything went fine except for the step 'connect from outside the container'.  I am getting the error as below

PS C:\WINDOWS\system32&gt; sqlcmd -S XX.XXX.XX.XX,1433 -U SA -P "&lt;YourNewStrong!Passw0rd&gt;"
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Client unable to establish connection because an error was encountered during handshakes before login. Common causes include client attempting to connect to an unsupported version of SQL Server, server too busy to accept new connections or a resource limitation (memory or maximum allowed connections) on the server..
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: An existing connection was forcibly closed by the remote host.
.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Client unable to establish connection.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Client unable to establish connection due to prelogin failure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Get started with SQL Server containers on Docker (running SQL Server on Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rajendrarama** [comment]
sorry, it's my bad.  I have use the command 

docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=<YourStrong!Passw0rd>" `
   -p 1434:1434 --name sql1 `
   -d mcr.microsoft.com/mssql/server:2017-latest 

which should suppose to be 

docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=<YourStrong!Passw0rd>" `
   -p 1434:1433 --name sql1 `
   -d mcr.microsoft.com/mssql/server:2017-latest

**Comment by MightyPen** [comment]
@rajendrarama Thanks for diagnosing the problem in the test.  I gather there is no Documentation bug here after all.  So I will now Close this Issue 1465 as completed.
If further communication is needed about 1465, the @ mention mechanism must be used (@ sign, followed by my name MightyPen, with no intervening spaces).  If a good reason arises, I could reOpen this Issue.
Thank you.

**Comment by alaajarrah** [comment]
I got the following error when trying to connect to the sqlserver instance from external server:

 The login is from an untrusted domain and cannot be used with Integrated authentication.. Check if more detail is available for this error in the errorDetail field of the log.

Any advice please!
