### ISSUE TITLE
Extra file in sql-docs/managed-reference/sql2016/xml

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/sql-docs#1467]
#1147 was closed a month ago, but since it still hasn't been removed I'm opening this so it doens't get forgotten about

/cc @craigg-msft @sudeepku

**Comment by MightyPen** [comment]
Assigned this to myself. I will re-ping Sudeep Kumar about this in January 2019.

**Comment by MightyPen** [comment]
We have been unable to obtain confirmation from certain people, within our organization, that this file is no longer wanted for any present or future reason.  Thus we are leaving the harmless file alone.
But I am glad you brought this file to our attention, as we will continue to be more aware of it, and thus might find an opportunity in the near future to obtain confirmation about whether there is any reason to retain this file.
I am now Closing this Issue 1467.
Thank you.
