### ISSUE TITLE
Page outdated as CU13 is current release of SQL Server 2017

### ISSUE THREAD

**Issue by robinwilson16** [MicrosoftDocs/sql-docs#1495]
The page states that CU12 is the most recent CU for SQL Server 2017 but this is outdated as CU13 was released last month on 18th December: [https://sqlserverupdates.com/sql-server-2017-updates/](https://sqlserverupdates.com/sql-server-2017-updates/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2144de3e-5a91-5525-91f1-3d8a93aba54e
* Version Independent ID: 31e3fd7c-2d04-e976-8295-4edce2d1a093
* Content: [Release notes for SQL Server 2017 on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-release-notes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-release-notes.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@rothja Hi Jason,  Can you please process this Issue 1495, about CU13.  Thanks.
cc: @MikeRayMSFT  , @robinwilson16

**Comment by rothja** [comment]
@robinwilson16 You're absolutely right. Sorry for the delay in updating the release notes. I will do this today and close this issue after fixing. Thank you!

**Comment by robinwilson16** [comment]
Hello Jason
Thanks for updating.
Robin
