### ISSUE TITLE
Incorrect Column Description - sys.dm_exec_sessions client_interface_name

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/sql-docs#15]
On [sys.dm_exec_sessions’s documentation page](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-sessions-transact-sql), column client_interface_name is defined as "Protocol name that is used by the client to connect to the server. The value is NULL for internal sessions. Is nullable." 

I believe this definition is incorrect. Instead, this column holds the client interface library name. For example, when .Net Framework's System.Data.SqlClient is used, this column will show ".Net SqlClient Data Provider". From my testing, it appears that the value for this column is copied verbatim from TDS’s [Login7 packet’s](https://msdn.microsoft.com/en-us/library/dd304019.aspx) cchCltIntName field.

Would you consider updating this documentation page to reflect this? Maybe this column could be described something like “Name of interface library/driver being used by the client to communicate with the server. The value is NULL for internal sessions. Is nullable.”

**Comment by craigg-msft** [comment]
@bgribaudo thank you for the feedback.  I am going to copy the text from both issues you created and put them in an internal tracking item for the author to review.  We only recently lit up the public side of our content and we had not intended to have the "issues" feature enabled as we are not staffed to manage issues and PRs for so many topics.  We hope to some day but not now.  Apologies for the confusion.  My suggestion is to also past a summed version of your question on the bottom of the topic, in the comments section, then after some reviews the feedback and updates the topic as needed, they can respond via the comments area.  https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-sessions-transact-sql.
