### ISSUE TITLE
Typo in "Connect from outside the container"

### ISSUE THREAD

**Issue by danielthompson** [MicrosoftDocs/sql-docs#1510]
> "The  same **principals** apply when using other tools, but the process of connecting is unique to each tool." 

The word "principals" should be "principles".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Get started with SQL Server containers on Docker (running SQL Server on Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-ver15#pullandrun2019)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@danielthompson Thanks. I'm fixing this now and this issue will be closed when my PR is merged.
