### ISSUE TITLE
Help with XA Transaction article SQL

### ISSUE THREAD

**Issue by b0redj0rd** [MicrosoftDocs/sql-docs#1540]
Hello there, my query relates to the following article:- https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/understanding-xa-transactions.md

I have followed the instructions in this document, and have hit an issue which I was hoping someone would be able to help with.   The section which relates to the creation of new registry entries references a folder structure which doesn't exist on the system I am using.  The document says to create the following:- 

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL\<version>.<instance_name>\XATimeout 

From what I see, my install doesn't have the 'MSSQL' part of the structure.   I am using SQL 2016 on a Windows 2016 box and before I create the new structure I was wondering if someone wouldn't mind alleviating my concerns if they could.   

Thank you very much
Jordan

**Comment by MightyPen** [comment]
@arkadit    Hello Arkadi.    Can you please glance at this Issue 1540.    Then can you please enter a Comment into this Issue 1540 with your resolution or your assessment.
We would like to process this Issue 1540 very soon, and get is completed and closed.
.
You have the option of inquiring with @David-Engel for assistance in obtaining the correct answer.    David might know the answer, or David is often able to contact the right PM/Dev engineers for Microsoft's implementation of various programming languages.
Thank you.   GeneMi

**Comment by b0redj0rd** [comment]
Thanks very much @MightyPen - For clarity, the registry entry stated in the document is :- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL\<version>.<instance_name>\XATimeout  and it appears as the following on the server:- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL14.MSSQLSERVER so I appear to be missing the '\MSSQL\' portion - If someone can clarify if I should just go ahead and create the \XATimeout folder at this location that would be very helpful.    

Thanks very much for taking a look, I do appreciate it.

**Comment by arkadit** [comment]
@b0redj0rd, 
Hello, first if you are using SQL Server 2016 (ver 13) you should have and extend HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL13.MSSQLSERVER key 
If you are using SQL Server 2017 (ver 14) then key name should be HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL14.MSSQLSERVER

If you want to specify default and maximum XA transaction timeouts please a key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQLnn.MSSQLSERVER\XATimeout. nn here is either 13 or 14, depending on SQL Server version you have.  Then under this key create two DWORD values: XADefaultTimeout and XAMaxTimeout and specify the values you need.


Thanks

**Comment by David-Engel** [comment]
@b0redj0rd 
Also note, the doc apparently got an errant "\" added to the registry key sometime last year. It looks like it may have happened in one of someones scripted edits. I've edited the page and the change should be reflected sometime today. Thanks for noticing the discrepancy.

**Comment by b0redj0rd** [comment]
Thank you very much for the support guys, I do appreciate your time.

**Comment by MightyPen** [comment]
@craigg-msft , @rothja Craig and Jason, to my surprise, for this Issue 1540, the person who opened the Issue later Closed it.  We do not want this.  I am unsure if we can alter the permissions to prevent the public person who creates-opens the Issue from being able to Close it?

I noticed this closure, and was thereby able to fix the final label.
