### ISSUE TITLE
JDBC doc is hard to read

### ISSUE THREAD

**Issue by mvdobrinin** [MicrosoftDocs/sql-docs#1541]
This doc has a table that combines multiple columns into a single column - https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-2017, which makes it hard to read. Specifically, it has `Property`, `Type`, `Default` headings all in the first column in a vertical layout.

Is this allowed by the style guide?

**Comment by MightyPen** [comment]
@mvdobrinin Hello, this table was changed to this formatting (from 4 columns down to 2) after other customers told us the table was too wide to view easily.
.
However, if you feel that the 4 column formatting would be better, you may edit the article, by clicking its pencil icon (in its upper-right corner).  Then use the @ syntax in your Pull Request to notify me to look (and ideally also therein remind us of this Issue 1541 number).  If the width is no longer too wide, I will approve your PR and merge it into our 'master' branch.
.
It is possible that the per-column width tuning has been made smarter in our Build tools over the past year or two, and that the 4 column formatting might be better now than it was.
Thanks again.

I am now Closing this Issue 1541.  But the @ syntax for sending notifications to me will still work from in here.
