### ISSUE TITLE
Fix the Sample Python code on https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/install/sql-machine-learning-services-windows-install.md

### ISSUE THREAD

**Issue by ikdonev** [MicrosoftDocs/sql-docs#1547]
The sample Python code for testing External Scripts configuration is throwing an error: 
`Msg 39004, Level 16, State 20, Line 6
A 'Python' script error occurred during execution of 'sp_execute_external_script' with HRESULT 0x80004004.
Msg 39019, Level 16, State 2, Line 6
An external script error occurred: 

Error in execution.  Check the output for more information.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\SQL-MSSQLSERVER-ExtensibilityData-PY\MSSQLSERVER01\E500C15C-4FCD-4774-85D8-C49013A5623C\sqlindb.py", line 29
    OutputDataSet = InputDataSet;
    ^
IndentationError: unexpected indent

SqlSatelliteCall error: Error in execution.  Check the output for more information.`

There is a space in the line " OutputDataSet = InputDataSet" which is causing the error.

**Comment by MightyPen** [comment]
Fix is attempted by new PR 8796:
.
https://github.com/MicrosoftDocs/sql-docs-pr/pull/8796
`https://github.com/MicrosoftDocs/sql-docs-pr/pull/8796`
. . . . . . . . . .
Article:
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/install/sql-machine-learning-services-windows-install.md
.
https://docs.microsoft.com/en-us/sql/advanced-analytics/install/sql-machine-learning-services-windows-install?view=sql-server-2017 
.
@HeidiSteen Hi Heidi, I cannot vouch for whether my PR 8796 fixes the SQL Python code example in your article. You can decide whether testing the example is needed.  Thanks.  GeneMi
.
@ikdonev Hello Ivan, thank you for submitting this Issue 1547.  Hopefully our internal PR 8796 has fixed this Issue, and the fix should be available late Thursday January/17.
I am now Closing this Issue 1547, as fixed-completed.  But this Issue can still be used for communication between us, through use of the @ notification syntax.

**Comment by MightyPen** [comment]
@ikdonev Ivan, I forgot to mention, that we encourage people to use the pencil icon in the upper-right of our articles, to edit our articles directly.  This small change would have been a fine opportunity for you to try clicking the pencil icon.  Thanks again.
