### ISSUE TITLE
mssql-server : Depends: libjemalloc1 but it is not installable [on Ubuntu 18.10]

### ISSUE THREAD

**Issue by theSdev** [MicrosoftDocs/sql-docs#1562]
Got the above error when tried to run this command: `sudo apt-get install -y mssql-server`
Resolved by following steps from [an answer on AskUbuntu](https://askubuntu.com/a/1098630) partially copied below:

1. Download the latest version of libjemalloc (this one is for Ubuntu 18.04) from this mirror here - http://ftp.osuosl.org/pub/ubuntu/pool/universe/j/jemalloc/libjemalloc1_3.6.0-11_amd64.deb
2. Install it: `sudo dpkg -i libjemalloc1_3.6.0-11_amd64.deb`
3. Now run the apt command to install ms-sql server: `sudo apt-get install mssql-server`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Get started with SQL Server on Ubuntu - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-2017)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@theSdev, Hello. Did you mean to close this git issue? I can investigate this to see if we need to add this to the docs? Thanks!

**Comment by theSdev** [comment]
Yes I closed it because I had the issue on 18.10 but the docs are for 16.04 I suppose. Therefore I'm not sure if this is applicable to the docs but I guess it's worth investigating. Thanks.

**Comment by GaryLyon** [comment]
This solution posted here resolved the issue for me. https://dba.stackexchange.com/questions/212868/installing-sql-server-i-get-unmet-dependencies-libc1-and-libjemalloc1-but-it
