### ISSUE TITLE
Extended Protection for Authentication link goes to unexisting page

### ISSUE THREAD

**Issue by ClaudioESSilva** [MicrosoftDocs/sql-docs#1564]
Hi,

The link `Extended Protection for Authentication` on https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/configuration-manager/protocols-for-mssqlserver-properties-advanced-tab.md is redirecting to a not existing page https://support.microsoft.com/en-us/help/968389 and giving 404

Thanks

**Comment by MightyPen** [comment]
PR 8872, in our private version of repo 'sql-docs', fixes this Issue 1564.  The dead link is removed.  In its place are the two best available replacement links.

**Comment by MightyPen** [comment]
PR 8872 is merged.
So I am now closing this successful Issue 1564.
@ClaudioESSilva Claudio, thank for you bring this problem to our attention.
