### ISSUE TITLE
Polybase and Cosmos DB with MongoDB API

### ISSUE THREAD

**Issue by sqlmartini** [MicrosoftDocs/sql-docs#1591]
Following article:  https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-mongodb.md

When attempting to create external data source following format in example I receive the error message "External data sources are not supported with type GENERIC".

select @@version
--
Microsoft SQL Server 2019 (CTP2.2) - 15.0.1200.24 (X64)   Dec  5 2018 16:51:26   Copyright (C) 2018 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by sqlmartini** [comment]
Missed a pre-req.  Ensure that polybase is enabled.

exec sp_configure @configname = 'polybase enabled', @configvalue = 1;
RECONFIGURE WITH OVERRIDE;

**Comment by rothja** [comment]
@sqlmartini We need to call this out better in the docs. Thanks for bringing this up!
