### ISSUE TITLE
Perhaps missing source of ~/.bashrc

### ISSUE THREAD

**Issue by MattWohler** [MicrosoftDocs/sql-docs#1593]
Upon adding the services to your PATH. Perhaps running `source ~/.bashrc` would be nice as upon running this script, attempting to run `sqlcmd` will present you with a "command not found" message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96990aff-bdd7-3cdd-d801-d544178cfb4d
* Version Independent ID: 6b083b6d-56b7-5a1e-3279-ae9f870e7811
* Content: [Unattended install for SQL Server on Ubuntu - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sample-unattended-install-ubuntu?view=sql-server-2017)
* Content Source: [docs/linux/sample-unattended-install-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sample-unattended-install-ubuntu.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@rothja Jason, can you please process this Issue 1593.  Thanks.

**Comment by rothja** [comment]
@MattWohler Thanks for the suggestion. In the past, I've done this with the period instead of the "source" command. I looked up source and see that sometimes it does not work on Ubuntu. Do you agree that period would work as well across various distributions?

`. ~/.bashrc`

Thanks!

**Comment by MattWohler** [comment]
@rothja They are nearly synonymous and both can break for their own reasons. For purposes of this exercise, you can use whichever you'd like. If something goes wrong, the user has a bigger problem outside the scope of the bash script.

**Comment by rothja** [comment]
@MattWohler Thanks. I'm fixing this today.

**Comment by MightyPen** [comment]
@rothja Jason, a little reminder to update the Issue's label when closing the Issue.
This always means the final label will be one named like 'Issue-Outcome-*'.

And we never have more than just one label on the Issue at any one time.
Thx G    (Issue 1593)
