### ISSUE TITLE
C# CLR Functions on SQL 2017 Linux 

### ISSUE THREAD

**Issue by CalinBunea** [MicrosoftDocs/sql-docs#1594]
IN our company we decided that we might want to migrate from SQL Server 2014 hosted on Windows to SQL Server 2017 hosted on Linux. One question mark was related to some C# CLR functions that we have. I have installed a test SQL 2017 on Linux and I have deployed the C# CLR functions and they work.
The intriguing part is the fact that target framework of C# CLR project is .NET Framework 4.6.2. Can anyone explain me how comes that this works on Linux? I was expecting to have a target framework as .NET Standard or .NET Core...
Thanks in advance!

**Comment by MightyPen** [comment]
I will look into this.

**Comment by srutzky** [comment]
@CalinBunea Are you asking about the Target Framework in Project Properties in Visual Studio? If so, I don't think Visual Studio has any clue about distinguishing between Linux vs Windows in terms of Database Projects. Also, even if it could, the environment, as far as SQL Server is concerned, is Windows, not Linux. There is an abstraction layer, similar in concept to the CLR, called SQL PAL (SQL Platform Abstraction Layer). This layer allows for simulating enough of the Windows OS that is needed to run SQL Server. That is the jist of it, at least. Please see the following blog post by "_Scott Konersmann, Partner Engineering Manager, SQL Server, Slava Oks, Partner Group Engineering Manager, SQL Server, and Tobias Ternstrom, Principal Program Manager, SQL Server_" for details:

[SQL Server on Linux: How? Introduction](https://cloudblogs.microsoft.com/sqlserver/2016/12/16/sql-server-on-linux-how-introduction/)

**Comment by MightyPen** [comment]
@CalinBunea Hello, It appears that a good exchange of information has been provided, and @ notification activity has subsided.  This Issue 1594 looks to have been successful.
Therefore, it is time to Close this Issue 1594.
However, this Issue 1594 can still be used for further @ notification Comments, if necessary.
Thank you reaching out to us with your question.  Closing now.
CC: @srutzky
