### ISSUE TITLE
Unattended installation anbd updates?

### ISSUE THREAD

**Issue by lennybacon** [MicrosoftDocs/sql-docs#1597]
It would be nice to have information on unattended setup and update for Azure Data Studio!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017)
* Content Source: [docs/azure-data-studio/download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@stevestein Hi Steve, can you please process this Issue 1597, when you return to work?
Also, I sent email to Andrew Ng asking if he might have any info about unattended install.

CC: @lennybacon

**Comment by MightyPen** [comment]
@lennybacon Hi Daniel, Here is the response from our engineering team:
.
"_Our best advice is to have users install Azure Data Studio with the User Setup Installation. This allows installation on machines without needing admin permissions, as well as a better auto-update scenario._"
.
Thanks for inquiring.  I am closing this Issue 1597 now.
If further communications are needed, the @ notification syntax will continue to work in this closed Issue.
.
CC: @stevestein , @yualan

**Comment by lennybacon** [comment]
@MightyPen That is absolutely not helpful of your engineering team!

You might tell them about things like `SCCM`, `the cloud` and `containers` or even `automation` which are pretty helpful things when working as an engineer ;-)

Nonetheless, here is the command line that works for an unattended installation:

```powershell
& ".\azuredatastudio-windows-setup-1.3.9" /VERYSILENT /MERGETASKS=!runcode
```

**Comment by MightyPen** [comment]
@yualan Alan, Here in Issue 1597, the customer has replied with further thoughts and information that you and Steve might want to consider for the documentation article.  Please see his preceding Comment box.
Thanks.

CC: @stevestein

**Comment by MightyPen** [comment]
I am reOpening this Issue 1597.
Due to current resourcing situations, this Issue 1597 might have to wait longer than usual to be more fully addressed.

**Comment by MightyPen** [comment]
A new internal DevO work item = 1468858 is continuing to track this aging Issue 1597.
When the DevO is processed and Closed, this Issue 1597 will also be updated with the final information (including an @ notification to the original poster.

https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1468858

https://dev.azure.com/MsEng/TechnicalContent/_workitems/edit/1468858

CLOSING this Issue 1597 (at least for now).

@stevestein @yualan 
. .
