### ISSUE TITLE
Resource Governor for Azure SQL (managed instance only)

### ISSUE THREAD

**Issue by kristinaflorea** [MicrosoftDocs/sql-docs#1603]
In the Overview https://docs.microsoft.com/en-us/sql/relational-databases/resource-governor/resource-governor?view=sql-server-2017 - the Azure SQL (managed instance only) is mentioned as supported.

By Enable Resource Governor, managed Instance is not mentioned any more.

Is it supported in Azure SQL MI or not?
Can I enable it as described here https://docs.microsoft.com/en-us/sql/relational-databases/resource-governor/enable-resource-governor?view=sql-server-2017 or not?

Please advise and correct the info accordingly. 

And the Governor - typo "To enable Resource Governorn, using"

Thanks,

K

**Comment by CarlRabeler** [comment]
Per this topic: https://docs.microsoft.com/en-us/azure/sql-database/sql-database-features  resource governor is supported for SQL Database – managed instance only. For questions about enabling, for example, send mail to MDCS SQL Managed Instance PMs mdcssqlmipm@microsoft.com<mailto:mdcssqlmipm@microsoft.com>

If questions, ping me directly.
Carl

**Comment by MightyPen** [comment]
@julieMSFT Julie, I see what you mean about the odd behavior of GitHub in the Labels editing you performed - GitHub is behaving oddly.  I will fix these labels as necessary in the coming day or two.
Oh, and I merged PR 8956, so I am closing this Issue 1603 as Fixed.
Thanks.
.
@kristinaflorea Thank you for bringing this documentation situation to our attention.  The fix should appear on live Docs by late Monday Feb/04.
