### ISSUE TITLE
Settings File Locations

### ISSUE THREAD

**Issue by pmduda** [MicrosoftDocs/sql-docs#1605]
With change from SQL Ops to Azure DS settings file locations changed.  It is not sqlops buz azuredatastudio:

* Windows `%APPDATA%\azuredatastudio\User\settings.json`
* Mac `$HOME/Library/Application Support/azuredatastudio/User/settings.json`
* Linux `$HOME/.config/azuredatastudio/User/settings.json`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc7e7fb4-ba27-9596-2c15-a38cd106a906
* Version Independent ID: 6d72c0a1-54ac-4022-f80e-238fc9809277
* Content: [User and Workspace Settings - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/settings?view=sql-server-2017)
* Content Source: [docs/azure-data-studio/settings.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/settings.md)
* Product: **sql**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by MightyPen** [comment]
@yualan Hi Alan, This week, before Friday Feb/08,.....
Can you please assess Issue 1605, concerning your article 'azure-data-studio/settings.md'.
Alan, when you have an assessment or other info, please enter your assessment into a new Comment box in this Issue 1605.  And when you do, please @ notify SteveStein and MightyPen (MightyPen is myself, = GeneMi).
Thanks a lot.
CC: @pmduda

**Comment by MightyPen** [comment]
@pmduda The fix for this Issue should go Live on Docs on Monday Feb/04, by perhaps early afternoon Pacific time (Seattle WA time).
PR 8965 fixes this Issue (in our private repo 'sql-docs-pr', sister of this public repo).
Thank you for bringing this situation to our attention!
