### ISSUE TITLE
LEAD/LAG Default description

### ISSUE THREAD

**Issue by LarnuUK** [MicrosoftDocs/sql-docs#1608]
The description for the behaviour of the _default_ expression in [`LEAD`](https://docs.microsoft.com/en-gb/sql/t-sql/functions/lead-transact-sql?view=sql-server-2017)/[`LAG`](https://docs.microsoft.com/sql/t-sql/functions/lag-transact-sql?view=sql-server-2017) doesn't appear to be exactly correct: 

> The value to return when _scalar_expression_ at _offset_ is NULL.

This implies (at least to me) that if _scalar_expression_ evaluates to `NULL` then the value of _default_ will be returned. Take the below query as example:

```
WITH VTE AS(
    SELECT 1 AS ID,
           1 AS N
    UNION ALL
    SELECT 2,1
    UNION ALL
    SELECT 3,NULL
    UNION ALL
    SELECT 4,2)
SELECT ID,
       N,
       LEAD(N, 1, 0) OVER (ORDER BY ID) AS L
FROM VTE
ORDER BY ID ASC;
```
The current wording suggests that for the second row, `0` would be returned for the value of `L`, as _scalar_expression_ returns `NULL`. For second row, however, the value of `L` is `NULL`, not `0`. The value of _default_ (`0`) is only returned when `ID` has a value of `4`, which is when the value of _scalar_expression_ cannot be evaluated; as it is "out of range".

**Comment by MightyPen** [comment]
@MashaMSFT Hi Masha, this Issue 1608 might (?) involve the following article(s).....

https://docs.microsoft.com/sql/t-sql/functions/lead-transact-sql?view=sql-server-2017

https://docs.microsoft.com/sql/t-sql/functions/lag-transact-sql?view=sql-server-2017

CC: @LarnuUK  , @rothja

**Comment by LarnuUK** [comment]
I honestly thought I'd included the links @MightyPen . My bad, and thanks for confirming. I've added to the original post as well for clarity, but you are correct; those are the 2 documents I am referring to.

Many thanks.

**Comment by MashaMSFT** [comment]
Hi @LarnuUK , thanks for bringing this to our attention! Let me look into this a bit more. Thanks!

**Comment by MashaMSFT** [comment]
Hi @LarnuUK , thanks for your patience, we're still investigating this. Thanks!

**Comment by MikeRayMSFT** [comment]
Hi @LarnuUK  - thanks for submitting this. I believe the documentation is correct. Here's why:

The statement defines the default as:  

> The value to return when scalar_expression at offset is NULL.

So the value is returned when the *offset* is NULL - not where the scalar expression is NULL. The demonstration that you provided shows the scalar expression returning now. If you need a default for the scalar expression itself you can use `ISNULL(<scalar_expresssion>)`.

Does that make sense?

I haven't closed it out because I'm checking with some of my colleagues to make sure we agree... but I wanted your opinion as well.

Thanks.

**Comment by LarnuUK** [comment]
Thanks @MikeRayMSFT  for coming back on this.

I can see how that interpretation could be reached as well. That doesn't really seem, to me, to be what it's saying. You're specifically stating when *offset* is `NULL`, however, the statement says "when scalar_expression **at offset** is NULL" (emphasis mine). So, the value of scalar_expression at offset is checked, and if it is `NULL` the value *default* is returned.

English is an awfully ambiguous language at times, and this is probably a good example of that. In trith, to actually achieve what you're saying it means, you could therefore remove the words "scalar_expression at" and go with:
> The value to return when offset is NULL.
This would always end up with your interpretation, as there is no ambiguity.

**Comment by MikeRayMSFT** [comment]
@LarnuUK  - how would this be understood?

>  *default*  
 The value to return when *offset* is beyond the scope of the partition. If a default value is not specified, NULL is returned. *default* can be a column, subquery, or other expression, but it cannot be an analytic function. *default* must be type-compatible with *scalar_expression*.

**Comment by MikeRayMSFT** [comment]
This was approved and the updated verbiage will appear soon in the article. Thank you for raising this issue.

**Comment by LarnuUK** [comment]
Thanks @MikeRayMSFT. New wording reads far better to me as well. I think this is much clearer and portrays the function really well.

Thanks again for the input.
