### ISSUE TITLE
Docker / SQL on Linux / MSSQL_AGENT_ENABLED in CTP 2.1 & CTP 2.2

### ISSUE THREAD

**Issue by abair34** [MicrosoftDocs/sql-docs#1609]
I'm having trouble getting the MSSQL_AGENT_ENABLED environment variable to work in the 2019 CTPs.

Using mcr.microsoft.com/mssql/server:2019-CTP2.1-ubuntu
AND mcr.microsoft.com/mssql/server:2019-CTP2.2-ubuntu

when the MSSQL_AGENT_ENABLED environment variable is set to true the SQL Agent is not enabled and /var/opt/mssql/mssql.conf file is not created.

Also will there be an option for disabling customer telemetry through environment variables or only as a post task?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12eac8a-8797-b2d4-5195-e1d77b4b0001
* Version Independent ID: 163b4b50-6e25-b006-6ea6-c6e4cfd044d0
* Content: [Configure SQL Server settings with environment variables - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-configure-environment-variables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-environment-variables.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@abair34 Thanks for the question. Let me take a look at this and possibly get some input from some others here on this problem. So you're doing this on Docker containers? Did you try the same steps for 2017 containers to see if it works there? I'll try too. Thank you.

**Comment by abair34** [comment]
Yes, I had previously verified with the following SQL 2017 images that the environment variables were working.

microsoft/mssql-server-linux:2017-CU5
microsoft/mssql-server-linux:2017-CU12-ubuntu             

You can test in minikube with the following helm chart
https://github.com/helm/charts/tree/master/stable/mssql-linux

just modify mssql-linux\templates\deployment.yaml and add the following
            - name: MSSQL_AGENT_ENABLED
              value: "true"

underneath "- name: MSSQL_PID
              value: {{ .Values.edition | quote }}"

in the mssql-linux\values.yaml try the results when deploying using 2017 or one of the 2019 CTPs
SQL Agent is enabled if the following image is used:
  repository: mcr.microsoft.com/mssql/server
  tag: 2017-CU12-ubuntu

SQL Agent will not be enabled if either of the following images are used:
  repository: mcr.microsoft.com/mssql/server
  tag: 2019-CTP2.2-ubuntu
  repository: mcr.microsoft.com/mssql/server
  tag: 2019-CTP2.1-ubuntu

**Comment by abair34** [comment]
hi @rothja

I noticed that this issue seems to be specific to a helm deployment.  The helm deployments with 2017 images work but with 2019 it does not.  

Interestingly if I directly connect to minikube and start a container with 

docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=YourStrong!Passw0rd' -e 'MSSQL_AGENT_ENABLED=true' -p 1403:1433 -d mcr.microsoft.com/mssql/rhel/server:2019-CTP2.2
the agent starts successfully.

I verified the environment variables do exist on the running container.  by running env in a bash shell in the running container "docker exec -it <containerid> /bin/bash".  I've stopped the container and restarted it and the agent still isn't available.  

I'm not sure if something changed in the 2019 ctp images where the environment variables that tiller is setting are not being recognized at install time?

So for repro 

choco install kubernetes-helm
helm init
helm fetch stable/mssql-linux --untar
modify the template.yaml as described above to add the sql_agent_enabled env variable.

modify the values.yaml with the settings below

acceptEula:
  value: "y"
edition:
  value: Developer
sapassword: "MyStrongPassword1234"
repository: mcr.microsoft.com/mssql/server
tag: 2019-CTP2.2-ubuntu

I switch to the service nodeport for the type since i'm accessing it through SSMS on my local machine so the container will be exposed by minikube's ip on the service port

service:
  # If headless is set to TRUE then the service type is ignored
  headless: false
  type: NodePort


helm install mssql-linux --name mytest

(to find the port)
kubectl get services 

(to find minikube ip) run "minikube ip" in admin cmd prompt
connect through SSMS to the minikube ip on the port you found in kubectl get services

with 2019 agent is still disabled,

change the values.yaml to 2017 
repository: mcr.microsoft.com/mssql/server
tag: 2017-CU12-ubuntu

cleanup the old test
helm delete mytest --purge

start the new test container
helm install mssql-linux --name mytest2

and follow the same connection steps and you'll see the issue.

**Comment by abair34** [comment]
Hi @rothja 

I took helm out of the mix and went to a straight kubernetes deployment and the issue still occurs.

repro:
remove the .txt extensions so the files are all .yaml

kubectl create secret generic mssql --from-literal=SA_PASSWORD="MyStrongPassword1234"
kubectl apply -f pv.yaml
kubectl apply -f pvc.yaml
kubectl apply -f sqldeployment.yaml

connect and the agent will be disabled
switch to sqldeployment2017.yaml or edit sqldeployment.yaml and change the container to a 2017 image, kubectl apply and the service will still be stopped.

[pv.yaml.txt](https://github.com/MicrosoftDocs/sql-docs/files/2836598/pv.yaml.txt)
[pvc.yaml.txt](https://github.com/MicrosoftDocs/sql-docs/files/2836599/pvc.yaml.txt)
[sqldeployment.yaml.txt](https://github.com/MicrosoftDocs/sql-docs/files/2836600/sqldeployment.yaml.txt)
[sqldeployment2017.yaml.txt](https://github.com/MicrosoftDocs/sql-docs/files/2836601/sqldeployment2017.yaml.txt)

**Comment by rothja** [comment]
@abair34 Thanks for the additional details. I'm reaching out to other contacts in the product team to ask about this. So the details are useful. Just to be clear, when you say that the agent is not enabled, are you verifying this by running "env" to see the environment variables that are set? And you see the other variables for the container but not the agent one? Thanks!

**Comment by abair34** [comment]
@rothja 

I verify that the SQL agent a few ways, the error log does not show agent_xps enabled and connecting with SSMS to the instance shows the sql agent with the red disabled icon on it and it says (Agent XPs disabled).  

I did run "env" within the container just to be absolutely sure that kubernetes actually passed the environment variable in.  

Thanks for passing the info about the issue on.  I wasn't quite sure where to give feedback on the CTP directly.  I remember in the past going to "connect" to file bugs that I found.  Going forward if I encounter any other issues with the CTP is there an official place I can go to report it?

**Comment by MikeRayMSFT** [comment]
@abair34 - you can provide product feed back for CTPs and current SQL Server versions at [https://aka.ms/sqlfeedback](https://aka.ms/sqlfeedback).

**Comment by rothja** [comment]
@abair34 Thanks for the feedback. As Mike said, you can also provide this feedback on https://aka.ms/sqlfeedback. Reporting on the article itself is also OK when the instructions don't work, so there is some grey area. At this time, I don't have a solution, but I have created a work item to look into this more as we continue to release CTPs. We just released CTP 2.3 and I'll check the behavior there. I'm going to close the issue and look into it offline, but you can continue to add any additional information in the comments if you have more information. Thank you!
