### ISSUE TITLE
Command syntax for step one under 'Configure SQL Server service keytab'

### ISSUE THREAD

**Issue by ethanmoffat** [MicrosoftDocs/sql-docs#1613]
Under step one for ['Configure SQL Server service keytab'](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017#configurekeytab), the step says to enter:

```
kinit user@CONTOSO.COM

kvno MSSQLSvc/**<fully qualified domain name of host machine>**:**<tcp port>**
```

I had to enter (using my own domain/machine name)

```
kinit user@EWMOFFAT.LOCAL

kvno MSSQLSvc/sqllinux.EWMOFFAT.LOCAL:1433@EWMOFFAT.LOCAL
```

The command was appending `@EWMOFFAT` automatically, where my domain had `@EWMOFFAT.LOCAL`. The error I received was `kvno: KDC reply did not match expectations while getting credentials for MSSQLSvc/sqllinux.EWMOFFAT.LOCAL:1433@EWMOFFAT`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Active Directory authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017#configurekeytab)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* GitHub Login: @meet-bhagdev
* Microsoft Alias: **meetb**

**Comment by rothja** [comment]
@ethanmoffat Thanks for the feedback. What Linux distribution are you running these commands on? It looks like from the error it was appending EWMOFFAT rather than CONTOSO? Or were your commands all using EWMOFFAT.COM in actuality? @Dylan-MSFT I might need your help to investigate this as we get more information. Maybe, we should be explicit and add @CONTOSO.COM to the end of the command anyway. Thanks!

**Comment by Dylan-MSFT** [comment]
Ethan. contoso.com is a placeholder domain we use for our docs. Everywhere you see it, it should append you actual domain name. If no domain name is being appended, check /etc/krb5.conf. In the [libdefaults] section, check what default_realm is set to. It should be your domain in all uppercase (i.e. EWMOFFAT.LOCAL).

**Comment by ethanmoffat** [comment]
Sorry for the confusion, that was a copy/paste error. I updated the original post to use my actual domain/machine name.

**Comment by rothja** [comment]
@ethanmoffat Thanks.  So did you check the default_realm per Dylan's comments to make sure it is  EWMOFFAT.LOCAL and not just EWMOFFAT? Thanks!

**Comment by ethanmoffat** [comment]
I'll check when I have access to the system (it's on my home network) and report back.

**Comment by rothja** [comment]
@ethanmoffat Awesome. @Dylan-MSFT Do you see a need to either make the command more explicit or to provide a sentence on troubleshooting this problem? Or should we leave it for now and see if this becomes a repeated issue. Thanks!

**Comment by Dylan-MSFT** [comment]
I can update the docs when I get a minute. I will add instructions for updating default_realm in krb5.conf so that this doesn't happen in the future.

**Comment by rothja** [comment]
@Dylan-MSFT Thanks. @ethanmoffat I'm closing this issue now. Appreciate the feedback.
