### ISSUE TITLE
Date conversion issue

### ISSUE THREAD

**Issue by hien0024** [MicrosoftDocs/sql-docs#1615]
Hello.
I converted date-string, '0001/01/01', into DT_DBDATE using [Cast](https://docs.microsoft.com/en-us/sql/integration-services/expressions/cast-ssis-expression?view=sql-server-2017) at SSIS package.  
It should be converted into '0001-01-01' but it was converted into '2001-01-01'.

According to ['this mapping'](https://docs.microsoft.com/en-us/sql/integration-services/data-flow/integration-services-data-types?view=sql-server-2017#mapping-of-integration-services-data-types-to-database-data-types), DT_DBDATE can be converted into [date (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/data-types/date-transact-sql?view=sql-server-2017).  
So, '0001-01-01' is within effective range of DT_DBDATE.

I use SQL Server 2016 and Visual Studio 2015 including SSDT.
Strictly speaking, the version is different in my SSDT and these documents.  
But as far as I read [this old article](https://blogs.msdn.microsoft.com/mattm/2010/08/04/string-to-date-conversion/), I thought the effect have a small influence on this time.  

Thank you.

**Comment by MightyPen** [comment]
Jason, The links provided by hien0024 look like the following when fully spelled out:

- https://docs.microsoft.com/sql/integration-services/expressions/cast-ssis-expression?view=sql-server-2017
- https://docs.microsoft.com/sql/integration-services/data-flow/integration-services-data-types?view=sql-server-2017#mapping-of-integration-services-data-types-to-database-data-types
- https://docs.microsoft.com/sql/t-sql/data-types/date-transact-sql?view=sql-server-2017  (_MikeRay_)
- https://blogs.msdn.microsoft.com/mattm/2010/08/04/string-to-date-conversion/ 

_DouglasL_ is listed as the ms.author on these SSIS articles, but Doug is no longer their true owner.

**Comment by rothja** [comment]
@hien0024 Thank you for the question on the docs. I read through the blog post you pointed to. However, in that case, the problem only happened when they converted to a type that didn't support 0001, such as DT_DATETIME. The strange thing is that in this example, their DT_DBDATE conversion worked correctly in the screenshot output. So, I agree with you that it seems like it should work. I am going to try to get some input internally and get back to you. Have you tried experimenting with other values like 0002 and 0030 to see what they convert to for more data points?

**Comment by hien0024** [comment]
@rothja  Thank you. I tried converting the following. 0001→2001, 0002→2002, 0009→2009, 0020→2020, 0029→2029, 0030→1930, 0099→1999, 0100→0100, 1000→1000, 1001→1001. Judging from these, boundaries are 0100 and 0099, 0030 and 0029. Maybe this is not so important, 0000 was converted into 2000.

**Comment by rothja** [comment]
@hien0024 Thanks! I am still trying to find the right person to answer this or file it as a bug. Is there any work around that you have right now for the problem, or is this blocking you?

**Comment by hien0024** [comment]
@rothja Sorry, but I have not found a versatile workaround yet. I convert '0001/01/01' into NULL now. I tried to convert it into DT_DBDATE with Derived Column Transformation and Data Conversion Transformation. But neither of them work as expected.

**Comment by rothja** [comment]
@hien0024 I apologize for the long delay in responding. I've passed this onto the product team, but I don't have a solution for you yet. If you want to an additional channel to record this feedback that the product team looks at, you can report your feedback at https://aka.ms/sqlfeedback. I'm sorry I don't have a better answer at this time.
