### ISSUE TITLE
Minimizse the Results and Messages panes

### ISSUE THREAD

**Issue by jn-altius** [MicrosoftDocs/sql-docs#1624]
How can we hide the Results and Messages panes so that the code editing pane is maximized?

In SSMS this was Ctrl + R

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6d68e91-6a5b-7f3b-0e72-1b88691b0c72
* Version Independent ID: 6f4e07e3-eb0b-cd4c-cc82-399e4a2ad715
* Content: [Tutorial: Use the Transact-SQL editor to create database objects - Azure Data Studio](https://docs.microsoft.com/en-gb/sql/azure-data-studio/tutorial-sql-editor?view=sql-server-2017)
* Content Source: [docs/azure-data-studio/tutorial-sql-editor.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/tutorial-sql-editor.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by rothja** [comment]
@jn-altius Thanks for the question. Git issues in the repo are mainly for doc feedback on errors or enhancements to the articles. So this would probably be best answered in other forums like StackOverflow. However, I did look at Azure Data Studio, and there are several options to toggle full screen or to turn different panels on or off. Did you try these from the menu?

Also, if you go to File | Preferences | Keyboard shortcuts, you can probably assign a keyboard shortcut after you find the command from the menu that works for you.

![ads view options](https://www.dropbox.com/s/4d0rjet3a21do0r/ads_views.PNG)

**Comment by jn-altius** [comment]
Thanks.

Though I can't see any option in File -> Preferences that affects the behaviour of the Results pane.

Ah well, never mind.

**Comment by rothja** [comment]
@jn-altius Take a look at the keyboard shortcuts (under File | Preferences). I found a bunch of toggle commands that don't show up in the menu. It looks like SHIFT + WINDOWS + R might be what you need to hide the results pane. I hope this helps! I'm closing this issue now. Thanks.
