### ISSUE TITLE
No docs for SUPPRESSPRIVACYSTATEMENTNOTICE parameter when installing SQL Server 2017 from the command line

### ISSUE THREAD

**Issue by astrohart** [MicrosoftDocs/sql-docs#1627]
In the doc:  sql-docs/docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md

There is no documentation/explanation of what the SUPPRESSPRIVACYSTATEMENTNOTICE parameter does. Did a search on the Microsoft Docs website on this term, did not find any hits.  For completeness' sake, I respectfully suggest that docs be added for it.

**Comment by MightyPen** [comment]
@MashaMSFT Hi Masha, This Issue of your's, 1627, concerns the same .md article as in Issues 1628 and 1629.

CC: @astrohart

**Comment by MashaMSFT** [comment]
Hi @astrohart , thanks for contacting Microsoft and bringing this to our attention! Let me do a little research... Thanks!

**Comment by MashaMSFT** [comment]
Hi @astrohart , thanks for bringing this to our attention! I have added a note about the  /SUPPRESSPRIVACYSTATEMENTNOTICE parameter to our documentation. I will proceed with closing this Git Issue,  but please feel free to respond here if you have any further suggestions. Thanks again!
