### ISSUE TITLE
Docs do not indicate what the value set for /Q and /QS is

### ISSUE THREAD

**Issue by astrohart** [MicrosoftDocs/sql-docs#1629]
Related to #1628 

In the doc: sql-docs/docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md

It is ambiguous as to whether you simply specify /Q and/or /QS on the command-line of SQL Server 2017 Setup when installing from the Command Line, or if they have possible values of "True" and "False."

In my ConfigurationFile.ini written for me by the Setup Wizard, I see:

```
; Setup will not display any user interface. 

QUIET="False"
```
and
```
; Setup will display progress only, without any user interaction. 

QUIETSIMPLE="True"
```
Do the /Q and /QS parameters work the same way?  And which one has precedence if both are set?  It's not clear.  Respectfully suggest updating the docs to clarify.

**Comment by MightyPen** [comment]
@MashaMSFT Hi Masha, This Issue 1629 is very closely related to your other Issue 1628, which is also from @astrohart.

- _GitHub:_ &nbsp; [https://github.com/MicrosoftDocs/sql-docs-pr/blob/master/docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md](https://github.com/MicrosoftDocs/sql-docs-pr/blob/master/docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md)

- _Docs:_ &nbsp; [https://docs.microsoft.com/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-2017](https://docs.microsoft.com/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-2017)

**Comment by MashaMSFT** [comment]
Hi @astrohart , thanks for contacting Microsoft and bringing this to our attention! Let me do a little research... Thanks!

**Comment by MashaMSFT** [comment]
Hi @astrohart , thanks for bringing this to our attention! The documentation indicates what the different parameters are:

![image](https://user-images.githubusercontent.com/32783170/53198221-b3f29500-35d0-11e9-93d4-5f7139520eae.png)

For the values that require a "true" or "false", the documentation explicitly states so:
![image](https://user-images.githubusercontent.com/32783170/53198254-cbca1900-35d0-11e9-9b4d-75835c3228fa.png)

When the documentation doesn't explicitly state something is necessary, then just flag the is used, as is the case with /Q and /QS. Additionally, there are examples of how to use the /q flag elsewhere in the documentation. As such, no work is necessary in improving the documentation on how to use this flag.

However, I did add a note saying that /Q overrides the /QS parameter. 

Thanks again and please let us know if we can be of further assistance! I will now proceed with closing out this Git Issue.

**Comment by astrohart** [comment]
Masha,

As to your first point, I disagree.  I see that there is a lot left “implicit” for readers to piece together.  I assume the audience is typically busy professionals doing their jobs at work.   Therefore, they might not have time to do all that mental work to put 2 and 2 and 2 together to make six.

Regards,
 
Brian C. Hart, Ph.D.
CEO, xyLOGIX, LLC
