### ISSUE TITLE
Docs say to specify /MPYCACHEDIRECTORY for offline, command-line install of Microsoft Machine Learning Services; however, the installer says this flag is not supported.

### ISSUE THREAD

**Issue by astrohart** [MicrosoftDocs/sql-docs#1630]
In the docs:  sql-docs/docs/advanced-analytics/install/sql-ml-component-commandline-install.md

Under the [Command-line arguments section](https://docs.microsoft.com/en-us/sql/advanced-analytics/install/sql-ml-component-commandline-install?view=sql-server-2017#command-line-arguments) it says:
```
/MPYCACHEDIRECTORY: For offline setup, sets the folder containing the Python component CAB files.
```
However, I specified this flag, and I received the error:
```

C:\SQL2017Media\server>setup.exe /ConfigurationFile="C:\SQL2017Media\server\ConfigurationFile.ini"
Microsoft (R) SQL Server 2017 14.00.1000.169
Copyright (c) 2017 Microsoft.  All rights reserved.

SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Server 2017 data processing and privacy controls, please see the Privacy Statement.
The following error occurred:
**The setting 'MPYCACHEDIRECTORY' specified is not recognized.**

Error result: -2068578301
Result facility code: 1204
Result error code: 3

Please review the summary.txt log for further details

C:\SQL2017Media\server>
```
Something is wrong here....either the docs are incorrect, or the SQL 2017 Setup program needs to be re-written to take ```/MPYCACHEDIRECTORY``` as an argument, because the current version's behavior (not taking the ```/MPYCACHEDIRECTORY``` flag as a recognized argument) is inconsistent with the documentation.

**Comment by astrohart** [comment]
Update:

I am attaching the Summary.txt from that run and also a ZIP of the detail logs and data, for the purposes of facilitating analysis.

[Summary.txt](https://github.com/MicrosoftDocs/sql-docs/files/2848282/Summary.txt)

[20190209_161646.zip](https://github.com/MicrosoftDocs/sql-docs/files/2848295/20190209_161646.zip)

**Comment by MightyPen** [comment]
@HeidiSteen Hi Heidi, This Issue 1630 concerns an article that you own.
@astrohart has given a good explanation of his concern.

- _GitHub:_ &nbsp; [https://github.com/MicrosoftDocs/sql-docs-pr/blob/master/docs/advanced-analytics/install/sql-ml-component-commandline-install.md](https://github.com/MicrosoftDocs/sql-docs-pr/blob/master/docs/advanced-analytics/install/sql-ml-component-commandline-install.md)

- _Docs:_ &nbsp; [https://docs.microsoft.com/sql/advanced-analytics/install/sql-ml-component-commandline-install?view=sql-server-2017](https://docs.microsoft.com/sql/advanced-analytics/install/sql-ml-component-commandline-install?view=sql-server-2017)

**Comment by HeidiSteen** [comment]
@astrohart My apologies for the very long delay in responding to this issue.  You ran into a bug.  The MPYCACHEDIRECTORY directory is not operational.  For disconnected/offline setup, please put all .cab files in the %Temp% folder.

**Comment by HeidiSteen** [comment]
@astrohart  this issue is addressed in this PR: https://github.com/MicrosoftDocs/sql-docs-pr/pull/9427 
Content should be live this morning.  Thanks for reporting the issue.

**Comment by MightyPen** [comment]
@HeidiSteen @dphansen Heidi and David,
Please remember to finalize the LABEL on each Issue, when you Close the Issue.
This means Replacing the label named 'Issue-Status-*' with a label named 'Issue-Outcome-*'.

Today I finalized the label for you on this Closed Issue 1630.  (repo = 'sql-docs')

And thanks for putting in the related PR number, #9427.
To complete the _**bi-directionality**_ of the audit trail, I just now mentioned Issue 1630 in the PR.

Thanks a lot.  GeneMi.  2019/03/30.

**Comment by astrohart** [comment]
Respectfully suggest the docs be updated to say what you just told me.  Thanks.

Regards,
 
Brian
