### ISSUE TITLE
Geri getirme 

### ISSUE THREAD

**Issue by alkanalkn63** [MicrosoftDocs/sql-docs#1631]
Facebook instigram videolar trackview dosyalarim fotograflarim mesajlarim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92039d2f-79be-5b42-a880-d2992ce8a151
* Version Independent ID: ef7c0d04-a65f-28e0-3935-3dac80fb13c2
* Content: [What's New in SQL Server 2016 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-2016?view=sql-server-2017#info_tip-get-help)
* Content Source: [docs/sql-server/what-s-new-in-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/what-s-new-in-sql-server-2016.md)
* Product: **sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MashaMSFT** [comment]
Hi @alkanalkn63 , I may be wrong here but this does not seem to be a question. I will proceed with closing out this Git Issue, but please feel free to contact us if you need any assistance. Thanks!
