### ISSUE TITLE
Documentation Does not work

### ISSUE THREAD

**Issue by DerSandmann-Badcode** [MicrosoftDocs/sql-docs#1638]
The SQL Operations Studio debug extension tries to run 'sqlops', however the program has been renamed to 'azuredatastudio' - No link to any other updated documentation, sqlops is labelled as deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7daeef2-a818-fc7f-88b8-6a8b5fabb2c1
* Version Independent ID: 87a54b84-059e-189c-d989-1fd3e9e16e8e
* Content: [Tutorial: Create an extension - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/tutorial-create-extension?view=sql-server-2017)
* Content Source: [docs/azure-data-studio/tutorial-create-extension.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/tutorial-create-extension.md)
* Product: **sql**
* GitHub Login: @kevcunnane
* Microsoft Alias: **kcunnane**

**Comment by kevcunnane** [comment]
I'll look at updating this extension as a solution.

**Comment by kevcunnane** [comment]
OK - have fixes out, need to update the doc now that the tools are all published

**Comment by kevcunnane** [comment]
@DerSandmann-Badcode FYI to unblock you while I wait for private docs repo PR to merge/ get published:

New yeoman generator is
`npm install -g yo generator-azuredatastudio`

then run
`yo azuredatastudio`

This will then update the runtime executable target to `azuredatastudio`. I also updated the debug extension for VSCode to be `Azure Data Studio Debug`. Thanks again for raising this.
