### ISSUE TITLE
SET SINGLE_USER doc confuses most engineers I work with

### ISSUE THREAD

**Issue by jzabroski** [MicrosoftDocs/sql-docs#1640]
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/set-a-database-to-single-user-mode.md

@MightyPen Hope 2019 is treating you well :)

There are a couple of problems with this documentation:
1. Even Microsoft SQL Server MVPs have hard a hard time reading this documentation correctly. I worked with one vendor where it took them 9 months to fix a bug related to `AUTO_UPDATE_STATISTICS_ASYNC ON`.  I attribute most of this delay to the fact there is no good script that demonstrates best practices.
2. The best practices around killing all connections to a database are scattered all over the place, and no one place contains a general script that can do the job regardless of how your database is set-up.
3. The link https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options?view=sql-server-2017 has a verbose section on `AUTO_UPDATE_STATISTICS_ASYNC`, but doesn't say anything about how turning it on can negatively affect `ALTER DATABASE { database_name  | CURRENT }   SET SINGLE_USER WITH ROLLBACK IMMEDIATE`:
    > AUTO_UPDATE_STATISTICS_ASYNC { ON | OFF }
ON
    > Specifies that statistics updates for the AUTO_UPDATE_STATISTICS option are asynchronous. The query optimizer does not wait for statistics updates to complete before it compiles queries.
    > 
    > Setting this option to ON has no effect unless AUTO_UPDATE_STATISTICS is set to ON.
    > 
    > By default, the AUTO_UPDATE_STATISTICS_ASYNC option is set to OFF, and the query optimizer updates statistics synchronously.
    > 
    > OFF
    > Specifies that statistics updates for the AUTO_UPDATE_STATISTICS option are synchronous. The query optimizer waits for statistics updates to complete before it compiles queries.
    > 
    > Setting this option to OFF has no effect unless AUTO_UPDATE_STATISTICS is set to ON.
    > 
    > The status of this option can be determined by examining the is_auto_update_stats_async_on column in the sys.databases catalog view.
    > 
    > For more information that describes when to use synchronous or asynchronous statistics updates, see the section "Using the Database-Wide Statistics Options" in Statistics.
4. "Using the Database-Wide Statistics Options" is not even an actual section in https://docs.microsoft.com/en-us/sql/relational-databases/statistics/statistics?view=sql-server-2017 - I have _no idea_ what it should link to, but probably "Statistics Options" section here: https://docs.microsoft.com/en-us/sql/relational-databases/statistics/statistics?view=sql-server-2017#statistics-options
5. https://docs.microsoft.com/en-us/sql/relational-databases/databases/set-a-database-to-single-user-mode?view=sql-server-2017#Prerequisites has a bizarre pre-requisite that will only fail at run-time, and the pre-requisite is not even in a warning section.  It's a bit like that xkcd comic about Little Bobby Drop Tables.
   1. Even when you read the pre-requisites, it links you to a wall of text in the Arguments section of the ALTER DATABASE command which probably has the build instructions for the next Tesla model car somewhere on the page. :) For more information, see [ALTER DATABASE SET Options (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options?view=sql-server-2017). - I can see why the vendor I was working with gave up trying to figure out what I was talking about when I explained to them that asynchronous stat jobs were causing their scripts to fail.  It's actually gotten even more complicated now that the "Click a product" feature has come into place.
   2. Based on the pre-requisites, I would think I should scroll to the section on the ALTER DATABASE SET Options page about "AUTO_UPDATE_STATISTICS_ASYNC", but that doesn't seem to have any useful information or warnings/
   3. When you go to the Examples on the ALTER DATABASE SET Options page, it mentions NOTHING about "AUTO_UPDATE_STATISTICS_ASYNC" in the examples on how to set a database to READ_ONLY.
   4. Finally, if I scroll to the section under Arguments and look at SINGLE_USER, I see the following:
       > Before you set the database to SINGLE_USER, verify the AUTO_UPDATE_STATISTICS_ASYNC option is set to OFF. When set to ON, the background thread used to update statistics takes a connection against the database, and you will be unable to access the database in single-user mode. To view the status of this option, query the is_auto_update_stats_async_on column in the sys.databases catalog view. If the option is set to ON, perform the following tasks:
       >
       > 1. Set AUTO_UPDATE_STATISTICS_ASYNC to OFF.
       >
       > 2. Check for active asynchronous statistics jobs by querying the sys.dm_exec_background_job_queue dynamic management view.
       > 
       > If there are active jobs, either allow the jobs to complete or manually terminate them by using KILL STATS JOB.

     That's it.  No example code on how to properly check for active asynchronous statistics jobs, just a wall of text embedded deep in the docs.  Again, I can totally see why the vendor I was working with did not put in the extra effort to fix my bug - the documentation was just a tangled web here.

My suggestions for improvement would be:
1. Update https://docs.microsoft.com/en-us/sql/relational-databases/databases/set-a-database-to-single-user-mode?view=sql-server-2017 to move the pre-requisites into a Warning section instead of a tame pre-requisites section - color will help people to read more carefully.
2. Fix [!code-sql[DatabaseDDL#AlterDatabase8](../../relational-databases/databases/codesnippet/tsql/set-a-database-to-single_1.sql)] so that it works in all scenarios.
3. Fix bad section links in ALTER DATABASE SET Options page so that the two references to the Statistics page point to actual sections, rather than the whole page.
4. Fix the documentation for the argument SINGLE_USER in the ALTER DATABASE SET Options page so that there is a link back to [!code-sql[DatabaseDDL#AlterDatabase8](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/codesnippet/tsql/set-a-database-to-single_1.sql)] or even https://docs.microsoft.com/en-us/sql/relational-databases/databases/set-a-database-to-single-user-mode?view=sql-server-2017 so that developers can more easily find the appropriate way to kill all connections to a database.
5. Consider adding some search engine optimization to https://docs.microsoft.com/en-us/sql/relational-databases/databases/set-a-database-to-single-user-mode?view=sql-server-2017 so that the phrase "kill all connections to a database" are included, so that eventually this page becomes the top search result in Bing/Google/DuckDuckGo for how to kill all active connections to a database.
6. Fix SSMS as well so that the SMO library correctly scripts out this action as well (this may be too much to ask, at least of the documentation team).

**Comment by jzabroski** [comment]
One last comment.  The vendor I work with also, prior to eventually fixing the issue based on the convoluted documentation, suggested that the issue was fixable by doing the following:

```sql
SET DEADLOCK_PRIORITY 10;
ALTER DATABASE [YourDBName] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
```

This was claimed to be the "undocumented" solution by the Microsoft SQL Server MVP for about 6 months.

This advise appears to come adapted from the following blog/website: https://sqlstudies.com/2017/02/16/deadlock-on-alter-database/

**Comment by MightyPen** [comment]
@jzabroski Hi John, Thanks for this detail. This is an important documentation article, so we would like to make all necessary improvements to it as soon as we can.
To set expectations, it will be weeks, hopefully not months, before we can take a close look at this Issue 1640 and the docu article. We have far more work to do than we have resources to get to everything promptly  :-) 
.
CC: @stevestein

**Comment by jzabroski** [comment]
Thanks, @MightyPen 
@stevestein , below is my attempt at a script to kill stats job.  The idea being this script could be stacked above a SET SINGLE_USER command.  It's a bit messy, AND it doesn't appear like it will work on Data Parallel Warehouse databases (according to the _insane_ docs on the background job queue DMV - which I didn't even realize when I wrote up this initial suggestion to improve this area that the _name_ of the DMV depends on what product you run against).

I should know within a few nights of testing this if it actually works in the wild.  I debated waiting to see if it worked prior to posting this, but I also don't want to forget, either.  Consider this my contemporaneous notes :)

```sql
/*
From: https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-background-job-queue-transact-sql?view=sql-server-2017#remarks
Quote: This view returns information only for asynchronous update statistics jobs. For more information about asynchronous update statistics.
*/

SET XACT_ABORT ON;
SET NOCOUNT ON;

DECLARE @DatabaseName SYSNAME; -- Database on which the job is to execute.
DECLARE @job_id INT; -- 	Job identifier.

DECLARE StatsJobsCursor CURSOR FAST_FORWARD LOCAL
FOR
SELECT DB_NAME(database_id) AS DatabaseName, job_id
FROM sys.dm_exec_background_job_queue
WHERE DB_NAME(database_id) = DB_NAME();

OPEN StatsJobsCursor
FETCH NEXT FROM StatsJobsCursor INTO @DatabaseName, @job_id
WHILE @@FETCH_STATUS = 0
BEGIN
	
	DECLARE @SqlCmd1 VARCHAR(MAX) = 'ALTER DATABASE [' + @DatabaseName + '] SET AUTO_UPDATE_STATISTICS_ASYNC OFF';
	IF EXISTS (SELECT * FROM sys.databases d WHERE d.[name] = @DatabaseName AND d.is_auto_update_stats_async_on = CAST(1 AS BIT))
	BEGIN
		RAISERROR(@SqlCmd1, 16, 1) WITH NOWAIT;
		EXEC sp_executesql @stmt = @SqlCmd1;
	END

	DECLARE @SqlCmd2 VARCHAR(MAX) = 'KILL STATS JOB ' + CAST(@job_id AS VARCHAR);

	BEGIN TRY
		RAISERROR(@SqlCmd2, 16, 1) WITH NOWAIT;
		EXEC sys.sp_executesql @stmt = @SqlCmd2;
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(MAX) =
			'Error: ERROR_MESSAGE[' + ERROR_MESSAGE()
			+ '] ERROR_NUMBER[' + CAST(ERROR_NUMBER() AS NVARCHAR)
			+ '] ERROR_SEVERITY[' + CAST(ERROR_SEVERITY() AS NVARCHAR)
			+ '] ERROR_STATE[' + CAST(ERROR_STATE() AS VARCHAR) + ']'
		RAISERROR(@SqlCmd2, 16, 1) WITH NOWAIT;
	END CATCH

	FETCH NEXT FROM StatsJobsCursor INTO @DatabaseName, @job_id
END

/* Clean up our work */
CLOSE StatsJobsCursor;
DEALLOCATE StatsJobsCursor;
```

**Comment by MightyPen** [comment]
@stevestein Hi Steve, you were OOF when this public PR 1640 was entered, so here is a reminder now that you have returned.
This PR is Assigned to you for consideration and processing.   Thx G

**Comment by stevestein** [comment]
@jzabroski - This issue will be fixed in the documentation, although we cannot yet say when. We have created a new internal tracking number for this work item: 1504619. We are closing this Issue, and are letting the new item track this going forward. You will receive another notice after the internal item if completed. Thank you for submitting this Issue.

If you find any more info feel free to add to this closed issue as it will be reviewed/referenced when this item is eventually worked on.  

Thanks!

**Comment by jzabroski** [comment]
@stevestein Sounds great!  Thanks for the update, Steve!
