### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by tdhintz** [MicrosoftDocs/sql-docs#1645]
Query Notifications Related Dynamic Management Views (Transact-SQL) link doesn't go anywhere.

**Comment by MashaMSFT** [comment]
Hi @tdhintz , thanks for contacting Microsoft! I'm assuming you mean on this page? https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/system-dynamic-management-views?view=sql-server-2017

Thanks for bringing this to our attention! It actually looks like a few links here are broken. I'll get these fixed :)

**Comment by MashaMSFT** [comment]
Hi @tdhintz , thanks again for bringing this to our attention! I have updated the documentation and the links should be fixed now. I will proceed with closing out the Git Issue,  but please feel free to comment if you need anything further.
