### ISSUE TITLE
clarify licensing

### ISSUE THREAD

**Issue by thda** [MicrosoftDocs/sql-docs#1648]
I see two licenses, one for the code, the other for the documentation.

However, after reading ThirdPartyNotices, what is considered as code, and what is considered part of the documentation is not clear.
For example it is my understanding that syntax definitions (as EBNF here) considered as documentation and CC licensed. But it is ambiguous.
Is there an attribute in markdown to separate MIT and CC content ?

**Comment by MightyPen** [comment]
@thda Hello Thomas, I do not understand what this Issue 1648 is about.
Where do you see "two licenses"? Link?
What documentation article is this Issue 1648 referring to (on docs.microsoft.com)? Link?
Can you please provide more information, and more clarity, for this Issue 1648.
EBNF = (extended Backus-Naur form)
CC = ??
MIT = ??
Thanks.

**Comment by thda** [comment]
Hi, and thanks for taking the time to answer.

CC BY 4.0 is [this license](../blob/live/LICENSE)
MIT is [this license](../blob/live/LICENSE-CODE)

Which one does apply to what content ?
I think [this](../blob/live/ThirdPartyNotices) tries to address the issue.
It says:

> Microsoft and any contributors grant you a license to the Microsoft documentation and other content
in this repository under the [Creative Commons Attribution 4.0 International Public License](https://creativecommons.org/licenses/by/4.0/legalcode),
see the [LICENSE](LICENSE) file, and grant you a license to any code in the repository under the [MIT License](https://opensource.org/licenses/MIT), see the
[LICENSE-CODE](LICENSE-CODE) file.

 

However it looks vague to me.
I would like to know the license of the syntax definitions here in EBNF.

**Comment by MightyPen** [comment]
@craigg-msft Hi Craig,
The point of Thomas's question is, for repository 'MicrosoftDocs/sql-docs', - _Are the Transact-SQL BNF syntax diagrams under the CC license or under the MIT license?_
Or put another way, are our T-SQL syntax diagrams considered to be "code" or not?

Craig, do you know whom we should ask for an answer?

Thanks.    GeneMi

**Comment by MightyPen** [comment]
Email sent, seeking legal opinion from Microsoft internal legal team.

From: Gene M
Sent: Thursday, March 7, 2019 11:28 PM
To: Ned ; Jennifer ; Greg
Cc: CraigG
Subject: Which license applies to BNF syntax diagrams that define Transact-SQL statement syntaxes ?

**Comment by MightyPen** [comment]
@thda Answer is:  The BNF syntax diagrams for Transact-SQL statements are governed under the Creative Commons license.

- Creative Commons Attribution 4.0 International Public License [https://creativecommons.org/licenses/by/4.0/legalcode](https://creativecommons.org/licenses/by/4.0/legalcode)

(JH, of LCA, 2019/03/12 10:02am)

Closing this Issue 1648 now, as successfully fixed. (The @ notification mechanism remains available, if necessary.)
Thanks for inquiring.
