### ISSUE TITLE
mcr is not reliable, please provide docker registry as a backup source

### ISSUE THREAD

**Issue by flybyray** [MicrosoftDocs/sql-docs#1649]
There is no status page for the mcr and the pull will fail currently.
```
sudo docker pull mcr.microsoft.com/mssql/server:2017-latest
Error response from daemon: Get https://mcr.microsoft.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
using the latest tag it is possible to resolve at least the tag, but the pull fails too. 
```
docker pull mcr.microsoft.com/mssql/server
Using default tag: latest
Error response from daemon: Get https://mcr.microsoft.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Get started with SQL Server containers on Docker (running SQL Server on Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@rothja Hi Jason, a customer opened this Issue 1649, but then soon Closed it on his own.  OK.

&nbsp;

Just FYI, the Issue had been about a SQL Linux article:
- docs/linux/quickstart-install-connect-docker.md

**Comment by flybyray** [comment]
sorry was due to wrong docker engine on fedora 29 - package `moby-engine` is not working as expected.
