### ISSUE TITLE
Link to the Power Query - Overview and Learning page

### ISSUE THREAD

**Issue by HappymediaDz** [MicrosoftDocs/sql-docs#1653]

**Comment by HappymediaDz** [comment]
If a user have set its regional parameters to French, when he hit the link to the Power Query - Overview and Learning page he land to the Power Pivot - Overview and Learning French version page (https://support.office.com/fr-fr/article/power-pivot-présentation-générale-et-formation-ed614c81-4b00-4291-bd3a-55d80767f81d?ui=fr-FR&rs=fr-FR&ad=FR). Please include in the url the /en-us/ to insure that the correct page is loaded. (https://support.office.com/en-us/article/power-query-overview-and-learning-ed614c81-4b00-4291-bd3a-55d80767f81d)
Regards
Mehdi

**Comment by MightyPen** [comment]
@jmazzotta @meganbradley @ishasahni1 

Hello DevRel PMs,    Please would one of you bring this Issue 1653 to the attention of a PM who works on the new "Learning" thang, Triple Crown I guess?

If a Learning project PM has a response for the customer about this Issue 1653, it would be great for the PM to respond by using the @ notification mechanism, here in Issue 1653.
Ideally also @ MightPen (me = GeneMi), so I know when I can Close the completed Issue 1653.

Or @ notify me if you doubt this inquiry has anything to do with the new Learning.

Thanks a lot.
GeneMi

**Comment by ishasahni1** [comment]
@SunnyDeng as she is the Learn Loc PM.

**Comment by SunnyDeng** [comment]
When I looked at the issue, the issue was created based on sql-docs, the contributor reported one of SQL-DOCS pages jumps to power-pivot page (fr-fr) instead of power-query page (en-us), so he requested us to add “/en-us/” in the link of the fr-fr page. Despite whether the request is reasonable or not, I think this report has nothing related with MS Learn project. The SQL Server Loc PM should look into this. 
@nokura, can you please look at this?

**Comment by MightyPen** [comment]
@HappymediaDz The 'fr-fr/' webpage *is* found just fine now. The metadata indicates the fr-fr/ was published early on 2019/March/05.

Perhaps the fr-fr/ edition had not quite been created yet when this Issue 1653 was created.  It takes our system a couple weeks to catch up to changes in our English master source.

Thank you for filing this Issue.  I can understand the confusion the two week delay may cause.
I am now Closing this Issue 1653.

**Comment by MightyPen** [comment]
FWIWorth, the article that contains the link to the Support article is = 'power-query-source.md'.

```
[C:\Users\genemi\GitGm\temp2\sql-docs-pr\docs\]
>> findstr /s /l /i /n /c:"ed614c81-4b00-4291-bd3a-55d80767f81d" *.md

integration-services\data-flow\power-query-source.md :23:

This article describes how to configure the properties of the Power Query Source in the SQL Server Integration Services (SSIS) data flow. Power Query is a technology that allows you to connect to various data sources and transform data using Excel/Power BI Desktop. For more info, see [Power Query - Overview and Learning](https://support.office.com/article/power-query-overview-and-learning-ed614c81-4b00-4291-bd3a-55d80767f81d) article. The script generated by Power Query can be copied & pasted into the Power Query Source in the SSIS data flow to configure it.

[C:\Users\genemi\GitGm\temp2\sql-docs-pr\docs\]
>>
```
