### ISSUE TITLE
Broken link to WMI Perf Counter Types on 'sys.dm_os_performance_counters' page

### ISSUE THREAD

**Issue by aprotsenko** [MicrosoftDocs/sql-docs#1656]
In the description for cntr_type, there's a link to WMI Performance Counter Types article on MSDN. Link: https://msdn2.microsoft.com/library/aa394569.aspx. Browser says that it can't reach it. Seems like it's a typo -- when I remove '2', the links works well -- I get redirected to the right article on docs.

so. the right link is: https://msdn.microsoft.com/library/aa394569.aspx

**Comment by MightyPen** [comment]
@aprotsenko Hello, The following article, which was migrated from MSDN to the new Docs platform, is indeed the target-by-redirection of the 'aa394569' link you give in this GitHub Issue:

- [https://docs.microsoft.com/windows/desktop/WmiSdk/wmi-performance-counter-types](https://docs.microsoft.com/windows/desktop/WmiSdk/wmi-performance-counter-types)
   - "WMI Performance Counter Types"

But all links in the target article work fine.
It seems this Issue description lacks mention of Where the problem link to this article resides (the 'msdn2' version of the link)? Does the link reside in another article? We need an exact link to the article that contains the bad link. Can you please update this Issue with the exact link.
Thank you.

**Comment by aprotsenko** [comment]
I forgot to do the most important thing – give you the link to the mentioned article =) Here it is: https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-performance-counters-transact-sql?view=sql-server-2017

**Comment by MightyPen** [comment]
Thank you for doing the work to fix the concern expressed in this Issue 1656.
I will now finalize the label, from a 'Issue-Status-*', to an 'Issue-Outcome-*'.
