### ISSUE TITLE
Issue with link under - Comparing FILESTREAM and Remote BLOB Store (RBS)

### ISSUE THREAD

**Issue by mikerodionov** [MicrosoftDocs/sql-docs#1658]
sql-docs/docs/relational-databases/blob/compare-options-for-storing-blobs-sql-server.md

Link listed under "Comparing FILESTREAM and Remote BLOB Store (RBS)" does not work - it leads to non existing/disabled page on MSDN blogs, where we can see the following result:

Oops! That page can’t be found.
This page has been disabled.

**Comment by MightyPen** [comment]
I am inquiring with Pam L.

**Comment by MightyPen** [comment]
PR 9305 (in MicrosoftDocs private repo) replaces the broken link (FwLink 210317) with a plain link to:
https://docs.microsoft.com/sql/relational-databases/blob/remote-blob-store-rbs-sql-server .

**Comment by MightyPen** [comment]
The fix should be live by the afternoon of Tuesday 2019/March/05.
I will now Close this successful Issue 1658.

@mikerodionov  Thank you for bringing this problem to our attention.
