### ISSUE TITLE
Needs 9 bytes to save a datetime2 value (SQL Server 2014, 2016 and 2017)

### ISSUE THREAD

**Issue by DatStone** [MicrosoftDocs/sql-docs#1659]
Storage size|6 bytes for precisions less than 3; 7 bytes for precisions 3 and 4. All other precisions require 8 bytes.|  

see
DECLARE @context VARBINARY(128);
DECLARE @fileID INT = 1000;
DECLARE @actionLogId INT = -1000;
DECLARE @processingStart DATETIME2(7) = SYSDATETIME();

SET @context = CAST(@fileID AS BINARY(4)) --fileid on process
               + CAST(@actionLogId AS BINARY(4)) --IDENTITY inserted row actionID
               + CAST(@processingStart AS BINARY(8)); -- Processing starttime
gives error
Msg 8152, Level 16, State 17, Line 9
String or binary data would be truncated.

Following code gives no error
DECLARE @context VARBINARY(128);
DECLARE @fileID INT = 1000;
DECLARE @actionLogId INT = -1000;
DECLARE @processingStart DATETIME2(7) = SYSDATETIME();

SET @context = CAST(@fileID AS BINARY(4)) --fileid on process
               + CAST(@actionLogId AS BINARY(4)) --IDENTITY inserted row actionID
               + CAST(@processingStart AS BINARY(9)); -- Processing starttime

**Comment by VanMSFT** [comment]
Hi @DatStone, can you please clarify this request, and what article(s) you are referencing?

**Comment by DatStone** [comment]
https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql?view=sql-server-2017

about this paragraph

Storage size | 6 bytes for precisions less than 3; 7 bytes for precisions 3 and 4. All other precisions require 8 bytes.
-- | --
You need 9 bytes?

**Comment by VanMSFT** [comment]
Thanks @DatStone. @MikeRayMSFT - Please take a look.

**Comment by MikeRayMSFT** [comment]
@DatStone  - thank you for submitting this issue. According to @bluefooted - we will clarify the precision information as follows:

The first byte of a **datetime2** value stores the precision of the value, which means the actual storage required for a **datetime2** value is the storage size indicated in the table above plus 1 additional byte to store the precision.  This makes the maximum size of a **datetime2** value 9 bytes - 1 byte stores precision plus 8 bytes for data storage at maximum precision.

**Comment by bluefooted** [comment]
Thanks @DatStone, this was a good catch!
