### ISSUE TITLE
Broken link to download ODBC driver 17

### ISSUE THREAD

**Issue by alekseybochkov** [MicrosoftDocs/sql-docs#1668]
This link doesn't exist:
Download the Microsoft ODBC Driver 17 for SQL Server on Windows
https://www.microsoft.com/download/details.aspx?id=56567

**Comment by MightyPen** [comment]
@alekseybochkov Hi Alexey, thanks for reporting this.  From you we also need info about Where you encountered this failing link.

**Comment by alekseybochkov** [comment]
Oh.. that definitely gonna make things easier
https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-2017

It turned out that link is valid, but the issue was with the download web-site.
