### ISSUE TITLE
connect locally with sqlcmd.

### ISSUE THREAD

**Issue by ArisPavlides** [MicrosoftDocs/sql-docs#1670]
You might want to specify that, to connect locally with sqlcmd, the following must be executed:

/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'myPassword'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Get started with SQL Server containers on Docker (running SQL Server on Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-powershell)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@ArisPavlides  I think the article is already specifying this, at H2 "Change the SA password":

- [https://docs.microsoft.com/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash#sapassword](https://docs.microsoft.com/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash#sapassword)

- [https://docs.microsoft.com/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-powershell#sapassword](https://docs.microsoft.com/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-powershell#sapassword)

```powershell
docker exec -it sql1 /opt/mssql-tools/bin/sqlcmd `
   -S localhost -U SA -P "<YourStrong!Passw0rd>" `
   -Q "ALTER LOGIN SA WITH PASSWORD='<YourNewStrong!Passw0rd>'"
```

Or is something else being suggested?

**Comment by MightyPen** [comment]
@VanMSFT Hi Van, As this week's Triager, you can monitor this Issue 1670, and decide whether there is enough info to warrant assigning this to RothJa (versus closing this, etc).
I have asked the original poster for additional info.
Thanks.

**Comment by ArisPavlides** [comment]
You are right. I didnt see the command. I skipped the tutorial right to the "Connect to SQL Server" section. My bad.

**Comment by VanMSFT** [comment]
Thanks, @ArisPavlides! We will go ahead and close this issue.
