### ISSUE TITLE
Incorrect version for dynamic data masking initial support

### ISSUE THREAD

**Issue by ghotz** [MicrosoftDocs/sql-docs#1671]
Dynamic data masking was introduced in SQL Server 2016 (13.x), not in 2017 (14.x)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48cb4a50-bcd6-38bc-187b-27cc36576219
* Version Independent ID: 38c1d92e-25d6-6237-9a04-6ca13bbb1a09
* Content: [What's new in SQL Server 2019 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-ver15?view=sqlallproducts-allversions)
* Content Source: [docs/sql-server/what-s-new-in-sql-server-ver15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/what-s-new-in-sql-server-ver15.md)
* Product: **sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by VanMSFT** [comment]
Thanks @ghotz! @MikeRayMSFT - Please take a look at this.

**Comment by CarlRabeler** [comment]
@ghotz Thanks Gianluca

**Comment by MikeRayMSFT** [comment]
@ghotz - thank you. We are updating the content.
