### ISSUE TITLE
There is a typo in multiple places: it should read DACPAC instead of BACPAC

### ISSUE THREAD

**Issue by bpe78** [MicrosoftDocs/sql-docs#1673]
There is a typo in multiple places: it should read DACPAC instead of BACPAC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2970c02d-0e5e-fd3c-f83c-dfafcb7ae0c2
* Version Independent ID: 32832120-0a84-7ebf-c9b3-1478dd1cf03e
* Content: [Export and import a database on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-migrate-ssms?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-migrate-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-migrate-ssms.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by VanMSFT** [comment]
Hi @bpe78! Thank you for bringing up this issue. DACPAC and BACPAC are two different types of export files. BACPAC includes schema and data from the database, while DACPAC only contains the schema of the database. The examples in the article for BACPAC are correct.

I will go ahead and close this issue, but please feel free to ask additional questions.
