### ISSUE TITLE
AdventureWorks DB

### ISSUE THREAD

**Issue by ikemtz** [MicrosoftDocs/sql-docs#1676]
Hello,

I'm not sure if this is the correct repo to report this issue, if I need to post it somewhere else please feel free to advise.

I constantly refer to AdventureWorks as a "WWMD" (What would  Microsoft Do) of database design.  I'm also a big fan of Docker and being able to spin up and tear down resources at a moments notice.  

On the SQL Server Linux pages, the AdventureWorks pages don't provide a docker image.  I realize that it's quite possible that such as an image doesn't exist or exist yet, but I do feel that it should and subsequently reflected in the documentation.

https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-linux-ver15

Thanks,
Isaac Martinez

**Comment by CarlRabeler** [comment]
@rothja @MikeRayMSFT @MashaMSFT Making you aware of this user suggestion. I will close this issue as it is a big support-type issue.

**Comment by CarlRabeler** [comment]
@ikemtz I think this is a good idea for consideration. Thank you for your input. I am closing this now. If you wish to respond further, use the @ notification for further communication with each of us.
