### ISSUE TITLE
Broken link in Configure read-only routing for an Always On availability group

### ISSUE THREAD

**Issue by vbfox** [MicrosoftDocs/sql-docs#1678]
The article [Configure read-only routing for an Always On availability group](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-read-only-routing-for-an-availability-group-sql-server?view=sql-server-2017)
contains a link to [Calculating read_only_routing_url for Always On](https://blogs.msdn.microsoft.com/mattn/2012/04/25/calculating-read_only_routing_url-for-alwayson/) that is dead.

The article can still be found on the wayback machine at https://web.archive.org/web/20170512023255/https://blogs.msdn.microsoft.com/mattn/2012/04/25/calculating-read_only_routing_url-for-alwayson/ and the script inside is interesting (Someone posted an cleaned up version without the bad MSDN blog formatting here: https://gist.github.com/Echizendesu/1483916a232e9607650e627b00c13d7d/2827b23384b74301d412db34ca3fee66a8cc5f34 )

**Comment by CarlRabeler** [comment]
@vbfox fixing - thank you.

**Comment by CarlRabeler** [comment]
Fix will be live later today.
