### ISSUE TITLE
SSMS 

### ISSUE THREAD

**Issue by keeyu2** [MicrosoftDocs/sql-docs#1682]
Can I connect using SSMS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd398c1-ed8b-911b-f11a-3739d80b3f32
* Version Independent ID: dc3d55ff-3b55-a686-81f9-f4188054e381
* Content: [Restore a SQL Server database in Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-restore-backup-in-sql-server-container?view=sql-server-2017)
* Content Source: [docs/linux/tutorial-restore-backup-in-sql-server-container.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-restore-backup-in-sql-server-container.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by keeyu2** [comment]
I fixed it.  It was the mapping of ports.  Since I have a SQL server running on the host machine.  I wasn't able to use 1433:1433.  I changed the port to use 5022:1433 and connected using the dockerNAT address.

**Comment by rothja** [comment]
@keeyu2 That's great. Maybe we should add a note to this effect in the doc? I'm closing for now but will consider adding this note soon. Thanks for the feedback!
