### ISSUE TITLE
Copy a backup file into the container - little bug

### ISSUE THREAD

**Issue by SuddenlyPineapple** [MicrosoftDocs/sql-docs#1686]
Hi, I've a problem with that line and couldn't import files into container. I recommend to change that line:
"docker cp wwi.bak sql1:/var/opt/mssql/backup"
to
"docker cp wwi.bak sql1:/var/opt/mssql/backup/wwi.bak"
In first it's copied to container as a backup file, not to backup directory, so it should be copied as a wwi.bak file.
I has that problem in powerShell version of this tutorial, didn't checked bash version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd398c1-ed8b-911b-f11a-3739d80b3f32
* Version Independent ID: dc3d55ff-3b55-a686-81f9-f4188054e381
* Content: [Restore a SQL Server database in Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-restore-backup-in-sql-server-container?view=sql-server-2017)
* Content Source: [docs/linux/tutorial-restore-backup-in-sql-server-container.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-restore-backup-in-sql-server-container.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@SuddenlyPineapple I just tried these steps, and it worked differently for me. It created copied the backup file into the directory. However, if the backup directory was not already there, it would have created a file called backup. Is it possible that you did not create the backup directory in your test? Thanks!!

**Comment by SuddenlyPineapple** [comment]
Yes, it is possible. Thank you, for response.
