### ISSUE TITLE
SSAS .deploymentoptions needs explaination

### ISSUE THREAD

**Issue by abbgrade** [MicrosoftDocs/sql-docs#1687]
The document sql-docs/docs/analysis-services/multidimensional-models/deployment-script-files-specifying-processing-options.md would benefit from a explaination what the allowed values in the XML document are. For example the different options for ProcessingOption like 'Default', 'Full', 'DoNotProcess'.

**Comment by MightyPen** [comment]
@Minewiskan Hi Owen, can you please assess the suggestion made by 'abbgrade' here in Issue 1687.

I can help you with the mechanics of how to process an Issue like this, with updating its labels etc.  For now, please assess, and enter a new Comment into this Issue.  Please ping me whenever it is time for me to help you advance the processing of this Issue.

**Comment by mgblythe** [comment]
@Minewiskan has been OOF, but he should be back in tomorrow and will triage/address.
