### ISSUE TITLE
openSuSe Leap 42.1 Compatability

### ISSUE THREAD

**Issue by Jasonca2** [MicrosoftDocs/sql-docs#1688]
Is there a compatible repository for openSuSe Leap 42.1?  I have tried installing ODBC Driver 17 for Sql Server against all three repositories listed below and can't get it to work with a python program that runs a few queries concurrently. 

#SUSE Linux Enterprise Server 11 SP4
zypper ar https://packages.microsoft.com/config/sles/11/prod.repo

#SUSE Linux Enterprise Server 12
zypper ar https://packages.microsoft.com/config/sles/12/prod.repo

#SUSE Linux Enterprise Server 15
zypper ar https://packages.microsoft.com/config/sles/15/prod.repo
SUSEConnect -p sle-module-legacy/15/x86_64

**Comment by David-Engel** [comment]
@Jasonca2 Sorry, openSuSe Leap is not a supported Linux distribution and we therefore do not test the driver against it nor do we build a package specific to it.

**Comment by MightyPen** [comment]
@David-Engel  @rothja Perhaps our documentation could explicitly say there is no such support the 'openSuSe Leap'?  But as a principle that could imply a need to have lots of negative statements in lots of articles; wherein the complete positive list already gives the answer clearly albeit implicitly.  I dunno, case-by-case basis.

This Issue 1688 is assigned to RothJa.

**Comment by Jasonca2** [comment]
With certain distros (i.e., CentOS and Redhat) you can sometimes have package interchangeability between their repositories. I was hoping that maybe SuSe Enterprise would have the same effect with their open source distro. I see that is not the case when it comes to Microsoft's current release of the Sql Server driver for Linux. That is unfortunate. I hope Microsoft adopts more support for some of the other, albeit not as common, distros out in the wild.

**Comment by David-Engel** [comment]
@Jasonca2 I understand. I'm kind of surprised that it doesn't just work, given openSuSe's roots. But we can't test every distribution out there. We do try to support the most popular ones and evaluate if we need to add support for others as they become more popular. This is actually the first request I've heard for openSuSe, however.

**Comment by Jasonca2** [comment]
@David-Engel It's understandable from Microsoft's end. They only have so much in terms of resources to devote to driver support for Linux. I hope that in the future they allocate more towards that department/ project. And I'm more of a debian guy myself, as it seems to always have a lot of support. The company I currently work for favors openSuSe so it is what it is. I'm just trying to get a Django 2.0 project working and it need's Microsoft's drivers to work properly with what I am trying to do.

**Comment by rothja** [comment]
@Jasonca2 Sorry this isn't working for you. However, we really appreciate your feedback, as more feedback like this will help us to prioritize for the future. At this time, there is not much more we can do on this git issue, so I will close it out. I'm sorry we couldn't help.

**Comment by Jasonca2** [comment]
@rothja I understand. No worries. I hope Microsoft will take note and support openSuSe Leap officially down the road.
