### ISSUE TITLE
"Automatic Tunic" 

### ISSUE THREAD

**Issue by jzabroski** [MicrosoftDocs/sql-docs#1704]
https://docs.microsoft.com/en-us/sql/?view=sql-server-2017#pivot=sqlserver&panel=sqlserver

Please fix so it does not say "Automatic Tunic" but says "Automatic Tuning"

@MikeRayMSFT

**Comment by MightyPen** [comment]
@MashaMSFT Hi Masha, there is a spelling mistake to fix, on the SQL Hub page, I think. Per this Issue 1704.

CC: @MikeRayMSFT

**Comment by MashaMSFT** [comment]
Well.. that's embarrassing :) Thanks for catching that @jzabroski ! I've fixed this typo within PR 9298, and will proceed with closing out this Git Issue. However, please feel free to respond should you need anything further. Thanks again!

**Comment by jzabroski** [comment]
THANK YOU SO MUCH.

**Comment by MightyPen** [comment]
@MashaMSFT Hi Masha,  A friendly reminder - to click the Close button on a final Comment when you have completed an Issue.
Plus, update the label from 'Issue-Status-*' to 'Issue-Outcome-*'.

For this Issue 1704, @MikeRayMSFT  has closed and re-labeled this for you today.
Thanks.
