### ISSUE TITLE
Tags are displayed in source code only for Japanese sites

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#1717]
@TomiakiNiwa commented on [Mon Mar 04 2019](https://github.com/MicrosoftDocs/sql-docs.ja-jp/issues/229)

**Describe the bug**
In the Japanese page, the tag is displayed in the last sample source.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/ja-jp/sql/relational-databases/backup-restore/enable-sql-server-managed-backup-to-microsoft-azure?view=sql-server-2017'
2. Look at the last source.

**Expected behavior**
In English pages, it has not occurred.
There is a possibility that CSS error occurred during translation.

**Screenshots**
![image](https://user-images.githubusercontent.com/48230525/53776583-cc9c6c80-3f39-11e9-9767-daa65f991fa5.png)

**Desktop (please complete the following information):**
all

**Smartphone (please complete the following information):**
all

**Additional context**
none

---

@welcome[bot] commented on [Mon Mar 04 2019](https://github.com/MicrosoftDocs/sql-docs.ja-jp/issues/229#issuecomment-469510964)

Thank you for creating the issue! One of our team members will get back to you shortly with additional information.

**Comment by CeciAc** [comment]
Hi team,
I'm moving this here because I believe is a source issue.

I saw a similar issue some days ago and the problem was with the tags in the code were misplaced causing translatable content being shown as code.

Kind regards

**Comment by MikeRayMSFT** [comment]
@CeciAc - the English page also has incorrect formatting at exactly the same spot. It doesn't show the `<span..` command, but there is a block of code that is incorrectly formatted in markdown. 

![image](https://user-images.githubusercontent.com/15928587/53900182-cc12dd00-3ff0-11e9-87a9-f11c039bb090.png)

I will submit a fix for this today and after that, we should see if the problem reproduces in Japanese. Will that work?

Thank you for raising this issue to our attention.

**Comment by MikeRayMSFT** [comment]
@CeciAc  - I have submitted a fix to the english version. I *think* this will result in an update to the localized version that should resolve the issue which you so appropriately raised. Thank you.
