### ISSUE TITLE
Instant File Initialization incorrectly references backups

### ISSUE THREAD

**Issue by blueelm-alex** [MicrosoftDocs/sql-docs#1736]
The steps to grant the SE_MANAGE_VOLUME_NAME to the SQL Server service account is referring to a computer that is going to store backup files. This seems incorrect.

**Comment by MikeRayMSFT** [comment]
Hi @blueelm-alex - thank you for submitting this issue.

Are you referencing [Database File Initialization](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-instant-file-initialization?view=sql-server-2017)?

I think you're referencing step 1:

> 1. On the computer where the backup file will be created...

Is that right?

**Comment by blueelm-alex** [comment]
@MikeRayMSFT Yes, There's a few references to backups

> 1. On the computer where the backup file will be created...

> 4. Click Add User or Group and add any user accounts that are used for backups.

**Comment by MikeRayMSFT** [comment]
Thank you. We will fix.
