### ISSUE TITLE
create database on azure managed instance permission incorrrect

### ISSUE THREAD

**Issue by grcarter-microsoft** [MicrosoftDocs/sql-docs#1742]
Hi.  I believe there is an error on the managed instance create database documentation.   The last bullet says that the logins needs dbmanager.   https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-transact-sql?view=azuresqldb-mi-current#permissions-2.  There is no dbmanager role on managed instance.  I believe that should say dbcreator role.

Permissions
To create a database, a login must be one of the following:
The server-level principal login
The Azure AD administrator for the local Azure SQL Server
A login that is a member of the **dbmanager** database role

**Comment by MikeRayMSFT** [comment]
@grcarter-microsoft thank you for submitting this. Assigning to the author for review.

**Comment by CarlRabeler** [comment]
@grcarter-microsoft good catch - updating the create and the alter article permissions now @VanMSFT for visibility https://github.com/MicrosoftDocs/sql-docs-pr/pull/9355

**Comment by CarlRabeler** [comment]
Fixed - please close @Mike-Ubezzi-MSFT

**Comment by Mike-Ubezzi-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.

**Comment by Mike-Ubezzi-MSFT** [comment]
@CarlRabeler This is sql-docs repo and not azure-docs repo. The @MicrosoftDocs/azure-cxp-triage folks are working with azure-docs repo items and associated workflow.

**Comment by CarlRabeler** [comment]
@MikeRayMSFT please close @MightyPen @craigg-msft

**Comment by CarlRabeler** [comment]
@grcarter-microsoft Fixed on 3/8 - thanks.

**Comment by MightyPen** [comment]
@CarlRabeler Hi Carl, Just a Reminder.    On your Fixed and Close Issue 1742, you did add the label 'Issue-Outcome-42-Fixed', good.  We want exactly 1 label on an Issue at any one time, so you would have wanted to also Remove the label 'Issue-Status-20-Author-will-triage', at the same time when you added the -42-Fixed- label.  I am removing the second outdated label for you. thx G

**Comment by CarlRabeler** [comment]
Got it – thanks.
