### ISSUE TITLE
Wording of the /FTSVCACCOUNT parameter in installation documentation is confusing for newer versions of SQL Server

### ISSUE THREAD

**Issue by grcarter-microsoft** [MicrosoftDocs/sql-docs#1746]
In https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-2017#Install

SQL Server Full Text | /FTSVCACCOUNT      Optional | Specifies the account for Full-Text filter launcher   service.      This parameter is ignored in **Windows Server 2008**. ServiceSID is used to help   secure the communication between SQL Server and Full-text Filter Daemon. If   the values are not provided, the Full-text Filter Launcher Service is   disabled. You have to use SQL Server Control Manager to change the service   account and enable full-text functionality.      Default value: Local Service Account
-- | -- | --

This explicitly calls out Windows 2008, but doesn’t say anything about any other version of Windows post-2008.  This is confusing.   I just tested with SQL 2016 on Windows 2016 and it has the ignore behavior as well.   I think we should change it to read.

Specifies the account for Full-Text filter launcher service.

This parameter is ignored in Windows Server 2008 **or newer**. ServiceSID is used to help secure the communication between SQL Server and Full-text Filter Daemon. If the values are not provided, the Full-text Filter Launcher Service is disabled. You have to use SQL Server Control Manager to change the service account and enable full-text functionality.

Default value: Local Service Account

**Comment by MikeRayMSFT** [comment]
@grcarter-microsoft - thank you for this recommendation.

Would you like to submit this upgrade directly to the documentation? 

You can click **Edit** on the article.
![image](https://user-images.githubusercontent.com/15928587/54058920-2ad08600-41ac-11e9-9c05-0f59cfa20629.png)

If you submit the update, then your GitHub account is added to the list of contributors for the article. 

We will review your submission before final approval.

**Comment by grcarter-microsoft** [comment]
Sure thing.  I will be glad to.

Grant

**Comment by MikeRayMSFT** [comment]
I've created an internal PR to fix, based on a fix submitted by @grcarter-microsoft

**Comment by MikeRayMSFT** [comment]
https://github.com/MicrosoftDocs/sql-docs-pr/pull/9378

**Comment by MightyPen** [comment]
@MikeRayMSFT Hi Mike, Minor request, can you please finalize the label on this closed Issue 1746:
- Exactly 1 label at any given time, yet this Issue has 2 labels.
- Due to PR 9378, I get the impression the 1 final label you want might be -42-Fixed-?

Thanks. GeneMi. 2019/03/14

**Comment by MikeRayMSFT** [comment]
@grcarter-microsoft thanks for the submission. The fix is in the pipeline.
