### ISSUE TITLE
pcs resource cluster failure-timeout

### ISSUE THREAD

**Issue by mmarquesesri** [MicrosoftDocs/sql-docs#1748]
--To update the ag1 resource property failure-timeout to 60s run:
--pcs resource update ag1 meta failure-timeout=60s

I tried but failed.
pcs resource update ag1 meta failure-timeout=60s
Error: Unable to find resource: ag1

I had to use the resource name "ag_cluster"	
pcs resource update ag_cluster meta failure-timeout=60s

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce18a990-b715-0cc5-d812-93fe62e25b71
* Version Independent ID: 947c77e4-fc0b-2b14-1974-049f35022597
* Content: [Configure RHEL Cluster for SQL Server Availability Group - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-cluster-rhel?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-availability-group-cluster-rhel.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-availability-group-cluster-rhel.md)
* Product: **sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
@mmarquesesri - thank you for your submission. We are reviewing and will update.

**Comment by MikeRayMSFT** [comment]
Resolved in https://github.com/MicrosoftDocs/sql-docs/commit/458327bc5920813e621038f908d4597a7cf9326a

Thanks again @mmarquesesri for raising this issue.

Thank you @SQLSourabh for validating.
