### ISSUE TITLE
SQL Server Books Online reference does not seem to exist 

### ISSUE THREAD

**Issue by CamyDee** [MicrosoftDocs/sql-docs#1765]
Under "Bytes Per Row" There is a reference to:

"Row-Overflow Data Exceeding 8 KB" topic in SQL Server Books Online.

However, there is no link. Searching for this online in many different ways has not yielded a satisfactory result. Does this topic exist? I see many other people looking for updated documentation regarding this behavior in all versions of SQL Server, but no official documentation to definitively answer these questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 780e3e16-ac52-1343-fe0a-a706c71ddb92
* Version Independent ID: 6f09b278-faa0-6f0d-1013-c1ae62ca006c
* Content: [Maximum Capacity Specifications for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server?view=sql-server-2017)
* Content Source: [docs/sql-server/maximum-capacity-specifications-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/maximum-capacity-specifications-for-sql-server.md)
* Product: **sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@MikeRayMSFT (and @CamyDee), Mike, I found the old article that the text-only link was referring to. I have pasted in the content of the old article below, FWIWorth.
Caution, The five links to other articles, that are in the pasted article below, are all old MSDN archived links.  I awkwardly put next to each link the MSDN shortId (find these by finding the '[' character).

----  Very SLOW Link, archive:
http://157.56.148.23/en-us/library/ms186981(SQL.100).aspx 

C:\JunkM\
Issue-1765.PlainText-ms186981.Row-Overflow_Data_exceeding_8_KB.txt


```
# Row-Overflow Data Exceeding 8 KB

A table can contain a maximum of 8,060 bytes per row. In SQL Server 2008, this restriction is relaxed for tables that contain varchar, nvarchar, varbinary, sql_variant, or CLR user-defined type columns. The length of each one of these columns must still fall within the limit of 8,000 bytes; however, their combined widths can exceed the 8,060-byte limit. This applies to varchar, nvarchar, varbinary, sql_variant, or CLR user-defined type columns when they are created and modified, and also to when data is updated or inserted.

> [!NOTE]
> This restriction does not apply to varchar(max), nvarchar(max), varbinary(max), ntext, text, image, or xml columns. For more information about the storage of these columns, see [Using Large-Value Data Types](DONOTUSE_157.56.148.23/library/ms178158%28SQL.100%29), Using text and image Data[[ms189574]], and Using XML Data[[ms178051]].

## Row-Overflow Considerations

When you combine varchar, nvarchar, varbinary, sql_variant, or CLR user-defined type columns that exceed 8,060 bytes per row, consider the following:

- Surpassing the 8,060-byte row-size limit might affect performance because SQL Server still maintains a limit of 8 KB per page. When a combination of varchar, nvarchar, varbinary, sql_variant, or CLR user-defined type columns exceeds this limit, the SQL Server Database Engine moves the record column with the largest width to another page in the ROW_OVERFLOW_DATA allocation unit, while maintaining a 24-byte pointer on the original page. Moving large records to another page occurs dynamically as records are lengthened based on update operations. Update operations that shorten records may cause records to be moved back to the original page in the IN_ROW_DATA allocation unit. Also, querying and performing other select operations, such as sorts or joins on large records that contain row-overflow data slows processing time, because these records are processed synchronously instead of asynchronously.

- Therefore, when you design a table with multiple varchar, nvarchar, varbinary, sql_variant, or CLR user-defined type columns, consider the percentage of rows that are likely to flow over and the frequency with which this overflow data is likely to be queried. If there are likely to be frequent queries on many rows of row-overflow data, consider normalizing the table so that some columns are moved to another table. This can then be queried in an asynchronous JOIN operation.

- The length of individual columns must still fall within the limit of 8,000 bytes for varchar, nvarchar, varbinary, sql_variant, and CLR user-defined type columns. Only their combined lengths can exceed the 8,060-byte row limit of a table.

- The sum of other data type columns, including char and nchar data, must fall within the 8,060-byte row limit. Large object data is also exempt from the 8,060-byte row limit.

- The index key of a clustered index cannot contain varchar columns that have existing data in the ROW_OVERFLOW_DATA allocation unit. If a clustered index is created on a varchar column and the existing data is in the IN_ROW_DATA allocation unit, subsequent insert or update actions on the column that would push the data off-row will fail. For more information about allocation units, see Table and Index Organization[[ms189051]].

- You can include columns that contain row-overflow data as key or nonkey columns of a nonclustered index.

- The record-size limit for tables that use sparse columns is 8,018 bytes. When the converted data plus existing record data exceeds 8,018 bytes, MSSQLSERVER ERROR 576 is returned. When columns are converted between sparse and nonsparse types, Database Engine keeps a copy of the current record data. This temporarily doubles the storage that is required for the record.

- To obtain information about tables or indexes that might contain row-overflow data, use the sys.dm_db_index_physical_stats[[ms188917]] dynamic management function.

## See Also

Concepts
Assigning a Data Type to a Column
```

**Comment by MightyPen** [comment]
Also, a still active/fast link, that will likely be fully retired in 2019 without any forwarding redirector, is the following "social" MSDN, dated January 2014:

- "SQL Server 2008 - Row-Overflow Data Exceeding 8 KB"

    - https://social.msdn.microsoft.com/Forums/sqlserver/en-US/24dbb445-292b-4433-a804-f524d32375e1/sql-server-2008-rowoverflow-data-exceeding-8-kb?forum=transactsql

**Comment by MikeRayMSFT** [comment]
Working with @pmasl and @bluefooted  on solution.

**Comment by pmasl** [comment]
Fixed and merged changes

**Comment by MightyPen** [comment]
The mystery number of the PR is probably 9398.

**Comment by MightyPen** [comment]
@MikeRayMSFT Looks like Issue 1765 is Fixed, so I am sending this little @ notification to let you know.
You can probably close and finalize this Issue 1765 now.  Thanks.

**Comment by MikeRayMSFT** [comment]
Updated by @pmasl -thank you.

Thanks also to @CamyDee for raising this issue.

**Comment by MikeRayMSFT** [comment]
https://github.com/MicrosoftDocs/sql-docs/commit/b107bcde25df18e5b9c9d7d67d06fc39852d3afd
