### ISSUE TITLE
Now available in Azure SQL Data Warehouse

### ISSUE THREAD

**Issue by eeiriksson** [MicrosoftDocs/sql-docs#1774]
Documentation needs updating as QS is now in GA for Azure SQL Data Warehouse
https://azure.microsoft.com/en-gb/updates/query-store-for-azure-sql-data-warehouse-is-now-generally-available/

**Comment by julieMSFT** [comment]
@TwoUnder Matt, please review this and let me know how you would like to proceed.

**Comment by julieMSFT** [comment]
@TwoUnder Matt, please review this and let me know how you would like to proceed.

**Comment by ant-222** [comment]
Hmmm. I don't understand why I am receiving notifications about this issue.

**Comment by julieMSFT** [comment]
@ant-222 I am not sure either. I do not see you mentioned in this issue. You can mute the thread.

**Comment by MightyPen** [comment]
@stevestein  @TwoUnder Hi Steve and Matt,  The "Query Store" feature in SQL Server on-premises: Is it now also GA for SQL Data Warehouse (Azure)?

If Yes, Steve probably needs to adjust the AppliesTo (Includes) and the Versioning (metadata monikerRange:) for the Query Store articles in repo 'sql-docs-pr'.
My search in 'sql-docs-pr' shows that Steve owns almost all the Query Store articles.
Matt is a SQL DW PM, who can perhaps ensure Steve's full understanding of the mini-blog link to azure.m.com in the original post. If Matt can confirm, Steve would be unblocked.

CC: @julieMSFT (re-Assigning this from Julie to Steve, and keeping Matt assigned.)

Thanks. GeneMi.  2019/04/10  23:02pm.

**Comment by julieMSFT** [comment]
Hi @eeiriksson thanks for bringing this to our attention!  We are updating the main Query Store topic,  [https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/query-store-catalog-views-transact-sql?view=sql-server-2017](url) and the other relevant Query Store topics to show they are supported for SQL DW. This change should be visible later today or tomorrow.

I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!

**Comment by julieMSFT** [comment]
PR #9837
