### ISSUE TITLE
Must an ODBC driver use SQLGetPrivateProfileString?

### ISSUE THREAD

**Issue by ant-222** [MicrosoftDocs/sql-docs#1782]
The documentation for [SQLGetPrivateProfileString](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetprivateprofilestring-function?view=sql-server-2017) does not state explicitly whether in *ODBC* 2.0 and above this function is the only allowed method for a conforming driver to acquire its DSN parameters or the driver can still read the `odbc.ini` file directly. Can you please add an explicit statement to this effect?

I have sought help on *MSDN*, but to no avail:

1. [The ODBC standard](https://social.microsoft.com/Forums/en-US/298a33a8-a630-4be8-ad27-f698b9ca6706/the-odbc-standard?forum=whatforum) in section *Where is the forum for...*

2. [ODBC: must the driver use SQLGetPrivateProfileString?](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/8cb170e9-1986-4e7c-ab74-303f462b0b01/odbc-must-the-driver-use-sqlgetprivateprofilestring?forum=databasedesign) in section *Database Design*.

3. [The ODBC standard](https://social.msdn.microsoft.com/Forums/en-US/51ea243e-75d4-4fab-a8e7-9926ebe899b0/the-odbc-standard?forum=os_specifications) in section *Open Specifications*.

4. [ODBC: must the driver use SQLGetPrivateProfileString?](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/5f000fd1-ef7b-4f57-aa9e-74a59c58363a/odbc-must-the-driver-use-sqlgetprivateprofilestring?forum=sqldataaccess) in section *SQL Server Data Access*.

**Comment by MightyPen** [comment]
I have just now sent email to David E., to inquire whether he feels he can process this Issue 1782.

**Comment by ant-222** [comment]
Thank you, Gene. Perhaps connected with this issue is the remark about SQLGetPrivateProfileString that it:

>  is provided as a simple way to port drivers and driver setup DLLs from Microsoft® Windows® to Microsoft Windows NT®/Windows 2000.

which may mislead the reader into believing that he don't need it unless porting an ODBC driver to Windows 2000 from an earlier version, whereas in fact this function is certainly the primary (if not the only) means or reading DSN parameters.

**Comment by David-Engel** [comment]
That doc page is a copy of the specification. I don't think it would be appropriate for us to change it. The specification is exactly what it says. That's simply what @ant-222 has to work with in his argument with SAP and how they have implemented their HANA ODBC driver for Linux.

**Comment by MightyPen** [comment]
@ant-222 After considering this Issue 1782, we have decided not to make any changes at this time.  Our documentation is reflecting the specification, and we are in no position to change the spec.  The situation may not be as simple as we might like.

Thank for submitting this Issue. I am now Closing this Issue; although the @ communication mechanism still works in Closed Issues.

**Comment by ant-222** [comment]
@MightyPen Bad luck then, but thank for your attention. You said that page was a copy of the specification. Where is the specification itself? Do you have any suggestions of who can help me with the interpretation of the ODBC standard with regard to the supported/allowed methods of reading DSN parameters?
