### ISSUE TITLE
Wrong index definition for /relational-databases/in-memory-oltp/indexes-for-memory-optimized-tables.md

### ISSUE THREAD

**Issue by jgmreyes** [MicrosoftDocs/sql-docs#1789]
It should be (StartDateTime ASC, CustomerName) instead of (StartDateTime DESC, CustomerName) for the index definition of constraintUnique_SDT_CN.

According to the summary table the non clustered index is non-suited when its columns is used in the sort columns but the ordering is reversed.

In the current example the index definition uses DESC sorting while the SELECT statement sample used the index in the ORDER BY clause in an ASC sorting. See below for the SELECT sample used

SELECT StartDateTime, CustomerName  
FROM SupportEvent  
ORDER BY StartDateTime;

Anyway if you don't want to change the index definition, please just change the ordering of the SELECT statement sample to DESC.

BTW I tested your examples and it is using table scan instead of index scan when testing the SELECT statement.

**Comment by jgmreyes** [comment]
Another wrong example is this
    
SELECT CustomerName, Priority, Description 
FROM SupportEvent  
WHERE CustomerName != 'Ben'; 

I have tried testing it multiple times and the actual execution plan is using table scan. The summary table in the article shows that the engine will search at the index if the first column in the definition is used in the where clause. The index definition showed the CustomerName column is second in the index definition.

**Comment by craigg-msft** [comment]
Thank you @jgmreyes assigned to current author @MightyPen  for topic https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/indexes-for-memory-optimized-tables?view=sql-server-2017

**Comment by MightyPen** [comment]
@jgmreyes Hi, Tracking of this work item has been shifted to our main internal work item database.
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1506415

When the internal item is Fixed, I will report back here in Issue 1789 with another @ notification to you (likely in May 2019).

Thank you for bringing this concern to our attention.
This Issue 1789 is now being Closed.

**Comment by MightyPen** [comment]
Fixed, by PR 10488.
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10488

@jgmreyes Thank you very much for bringing these documentation errors to our attention. Your observations were astute.
Now Closing Issue 1789.
.

**Comment by MightyPen** [comment]
Closing again, this time permanently.
