### ISSUE TITLE
SQL Server 2019 OpenLDAP documentation

### ISSUE THREAD

**Issue by mcowart123** [MicrosoftDocs/sql-docs#1802]
I see this mentioned as a feature, but I have been able to find absolutely no documentation on getting it set up. I'm running the latest preview on Centos 7 and I can't find anywhere obvious to configure it.

Is this feature available yet?

**Comment by craigg-msft** [comment]
@mcowart123 can you point me to where you see it noted as a feaure?

**Comment by MightyPen** [comment]
(LDAP = _Lightweight Directory Access Protocol_)
FWIWorth, we document LDAP for SQL Server Linux, and for ADO.  But for Windows, in our SQL Server documentation I see nothing about LDAP or OpenLDAP.  On the WWWeb I see mentions of third parties that may have developed an OpenLDAP for Windows.
I see the following mention of LDAP in a Windows documentation article.

---

- https://docs.microsoft.com/windows/security/threat-protection/security-policy-settings/network-security-ldap-client-signing-requirements

---

`[.....sql-docs-pr\docs\]`
`>> findstr /s /l /i /m /c:"LDAP" *.md`

- ado\guide\appendixes\microsoft-ole-db-provider-for-microsoft-active-directory-service.md
- analytics-platform-system\pdw-firewall-configuration.md
- linux\sql-server-linux-active-directory-authentication.md
- sql-server\what-s-new-in-sql-server-ver15.md
   - Corresponding Https URL is.....   https://docs.microsoft.com/sql/sql-server/what-s-new-in-sql-ver15 

---

[.....  azure-docs-pr\articles\]
>> dir /b /s *ldap*.md

- active-directory\authentication\howto-mfaserver-dir-ldap.md
- active-directory-domain-services\active-directory-ds-admin-guide-configure-secure-ldap-enable-ldaps.md
- active-directory-domain-services\active-directory-ds-admin-guide-configure-secure-ldap-export-pfx.md
- active-directory-domain-services\active-directory-ds-admin-guide-configure-secure-ldap.md
- active-directory-domain-services\active-directory-ds-ldaps-bind-lockdown.md
- active-directory-domain-services\active-directory-ds-ldaps-configure-dns.md
- active-directory-domain-services\active-directory-ds-ldaps-troubleshoot.md
- active-directory-domain-services\active-directory-ds-troubleshoot-ldaps.md
   - (Meaning this https URL)  https://docs.microsoft.com/azure/active-directory-domain-services/active-directory-ds-troubleshoot-ldaps

---
.

**Comment by mcowart123** [comment]
https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-ver15?view=sql-server-ver15#sqllinux

The pertinent statement:
OpenLDAP support for third-party AD providers (CTP 2.0): SQL Server 2019 preview on Linux supports OpenLDAP, which allows third-party providers to join Active Directory.

**Comment by craigg-msft** [comment]
@mcowart123 investigating.

**Comment by craigg-msft** [comment]
@mcowart123 apologies for the delay.  @rothja is following up.  Our understanding at this time is that the steps are more about "how" in the distro and we would not want to replicate the steps and that existing community information like the following is the best source of information.  

Step by Step OpenLDAP Server Configuration on CentOS 7 / RHEL 7  https://www.itzgeek.com/how-tos/linux/centos-how-tos/step-step-openldap-server-configuration-centos-7-rhel-7.html

**Comment by rothja** [comment]
@mcowart123 I spoke with one of our Linux leads here, and he said that this feature was actually made available in a 2017 cumulative update as well as 2019 around the same time. So I'm sorry for the confusion that it looks like this is a 2019-only feature. Also, we recently completely redid the documentation surrounding AD support for Linux. I would suggest looking at those new docs and see if they answer your questions or not. I'm closing this git issue now with this information, but I would be happy to reopen this if the new articles do not provide the information you need. Sorry, again, for any confusion.

[Join SQL Server on a Linux host to an Active Directory domain](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-join-domain?view=sql-server-2017)
[Tutorial: Use Active Directory authentication with SQL Server on Linux](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017)
