### ISSUE TITLE
Schema twice in DROP ?

### ISSUE THREAD

**Issue by chatelao** [MicrosoftDocs/sql-docs#1805]
DROP TABLE [ IF EXISTS ] [ database_name . [ schema_name ] . | schema_name . ]  
table_name [ ,...n ]  
[ ; ]

**Comment by julieMSFT** [comment]
hi @chatelao, Thank you for you submission. This statement is correct. The information in the [ ] is optional information. the | within the brackets is an "or" statement. This can be written as DROP TABLE database.schema.tablename or DROP TABLE schema_name.tablename.

I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!
