### ISSUE TITLE
Password example for SQL in Linux Docker on Windows 

### ISSUE THREAD

**Issue by bradranks** [MicrosoftDocs/sql-docs#1807]
The password example uses a bang in the code to copy/paste, which fails in actual practice.

Example password: < YourStrong!Passw0rd>

Error
root@20d5078e331c:/# /opt/mssql-tools/bin/sqlcmd -U SA -P YourStrong!Passw0rd
bash: !Passw0rd: event not found

Same error for trying to update the password, so once created, you are stuck with removing the entire image and starting over.

I would consider changing the sample code to something usable for beginners. eg. Examples are supposed to work.

Also, there is no documentation showing a user that they need the NAT IP address to connect to the server. The interface shows an address of 0.0.0.0:1433, but the actual login can be something like:
172.10.0.1,1433 

In order to get the NAT address you have to run ipconfig /all and look for it in the list, extract it out and make sure to replace the colon in the example with a comma.

It is the small details that trip everyone up.

Hopefully this helps.

**Comment by rothja** [comment]
@bradranks I apologize for the long delay in responding to you on this. I agree that the examples should just work and that we should provide some additional information for the connection. I'm going to walk through the steps and see if I can make this better. Thanks!

**Comment by rothja** [comment]
@bradranks Thanks, again for the feedback. I realized that the example for connecting to sqlcmd was hidden when PowerShell was selected. I am fixing this. If you put the password in single quotes it works to connect, and the example will show this. Sorry. As for the NAT IP address recommendation, in the "Connect from outside the container" I say to using ipconfig to find the IP address and the example shows a comma. Are you saying that ipconfig alone is not enough and it must be "ipconfig /all" on Windows to find the machine IP address? When I just run ipconfig, I get a list of adapters and their IP address, so I could connect to the Wireless adapter IP or the LAN IP depending on what I'm connected with at the moment.

**Comment by rothja** [comment]
@bradranks I merged in the change to fix the sqlcmd example and verified it worked. This closed this git issue automatically, but I would be happy to make more changes related to the IP address as we discuss it. Thank you!

**Comment by bradranks** [comment]
awesome. I think that is probably pretty good!

Brad

*Brad Ranks *Solutions Architect

DIRECT: 480-577-2723 |


*Technically*, The Best!
