### ISSUE TITLE
Is Prod Repo down?

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#1808]
curl command appears not to be pulling files, and running yum install yields "File contains no section headers"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@PrometheusRising1 I assume you are doing this on Red Hat? I just tried out the install commands for tools and they worked for me. Can you try again and check your connection to the internet? If you still have problems, copy the commands you're running and the error messages from your terminal to this git issue for me to take a look. And verify the version of Linux you're running for me. Thanks, and sorry you've run into this issue!

**Comment by PrometheusRising1** [comment]
Hi @rothja - it looks like my repo was corrupted.  Removed and readded the repo and it fixed the problem.

**Comment by rothja** [comment]
@PrometheusRising1 Awesome. Thanks for letting me know!
