### ISSUE TITLE
Azure Data Studio CLI

### ISSUE THREAD

**Issue by jclark0909** [MicrosoftDocs/sql-docs#1812]
We are currently working on an ADS extension and our build out a release environment in Azure DevOps. Is there a way to automate the .vsix download? I know that ADS is built of the VSCode framework and VSCode has a CLI but I have not seen any CLI from ADS. Is there a CLI for ADS or when is it coming out soon? Please let me know if you have any additional questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12bf49db-fd24-7f4d-6792-6825f4e08faa
* Version Independent ID: 5f524d58-816a-812f-e43f-1916f1b4f199
* Content: [Add extensions - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions?view=sql-server-2017#feedback)
* Content Source: [docs/azure-data-studio/extensions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/extensions.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@jclark0909 - Hi Jared, Apologies for the slow reply. I'm trying to find out if there is any plan for this but haven't been able to get a solid answer yet. 
You might try posting the question at [UserVoice](https://feedback.azure.com/forums/908035-sql-server)

@yualan - Do you have any additional info or insight you can provide on this?

**Comment by stevestein** [comment]
@jclark0909 - This area is primarily for specific documentation issues, and I haven't been able to get an official statement on this so I suggest either posting as an [Azure Data Studio issue](https://github.com/microsoft/azuredatastudio/issues), or posting on the [UserVoice ](https://feedback.azure.com/forums/908035-sql-server) site.

-Thanks
