### ISSUE TITLE
Support for More Recent Versions of Ubuntu Than One Released Back in April 2016

### ISSUE THREAD

**Issue by robinwilson16** [MicrosoftDocs/sql-docs#1816]
Please could you consider supporting more current versions of Ubuntu as the documentation is all for 16.04 released back in 2016, 5 versions behind the current release which is 18.10. with 19.04 due out next month. The last long term release was 18.04 released a year ago.

There are workarounds for getting this installed but these are documented elsewhere and not on this page.

The same applies for the SSIS package which doesn't work either without looking elsewhere for how to get it working with current editions of Ubuntu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Get started with SQL Server on Ubuntu - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-2017#feedback)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by robinwilson16** [comment]
Workaround to get the latest mssql-server installed in current Ubuntu versions:
```
sudo wget http://ftp.osuosl.org/pub/ubuntu/pool/universe/j/jemalloc/libjemalloc1_3.6.0-11_amd64.deb
sudo dpkg -i libjemalloc1_3.6.0-11_amd64.deb
```

Workaround to the the latest mssql-server-is installed in current Ubuntu versions:
```
sudo apt download mssql-server-is
sudo dpkg --force-depends -i mssql-server-is_14.0.3015.40-1_amd64.deb

Now alter dependencies so apt doesn't complain:
sudo nano /var/lib/dpkg/status
Find:
mssql-server-is

In the depends line change the max openssl value from:
openssl (<< 1.1.0)
 
To:
openssl (<< 1.1.2)

Also change:
libcurl3
 
To:
libcurl4
```

**Comment by zippyjason** [comment]
I strongly agree.  Ubuntu 18.04 is already a year old, with no official support.  Please consider adding support.

**Comment by rothja** [comment]
@robinwilson16 @zippyjason Thanks for the feedback, and I sincerely apologize for the delayed response. Your request for us to support more recent versions is completely understandable, and I can tell you that we are working on testing/support for more recent versions. I apologize it is taking a long time to get these versions tested and supported. I'll try to respond on this git issue when I have more updates I can share, but for now, I am going to close it.

**Comment by robinwilson16** [comment]
Thanks, I think on Linux, packages tend to all be compatible in time for a new release and really the same is true on Windows normally. Updating the distribution actually removes SQL Server and then the task is left to the user to figure out how to get it running again once the upgrade has completed. You wouldn't expect the 1809 Windows Server update to remove SQL Server leaving it in an un-installable state, so I wouldn't have expected this on Linux either, given support for Linux is not beta.
It fully works in all newer distros, it just thinks it doesn't due to the dependencies file. Can't someone just test it to confirm it runs ok and then update the dependencies file so it installs without hassle? Currently running MSSQL and MSIS on 19.04 (6 versions newer).
