### ISSUE TITLE
AttributeError: 'TransformWrapper' object has no attribute '_parents'

### ISSUE THREAD

**Issue by vijayande** [MicrosoftDocs/sql-docs#1818]
Hi 
I followed the steps as mentioned above and trying to execute the code 
"
cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER={******};DATABASE={NYCTaxi_Sample};Trusted_Connection=True;')
cursor = cnxn.cursor()
cursor.execute("EXECUTE [dbo].[PyPlotMatplotlib]")
tables = cursor.fetchall()
for i in range(0, len(tables)):
    fig = pickle.loads(tables[i][0])
    fig.savefig(str(i)+'.png')
print("The plots are saved in directory: ",os.getcwd())
"
getting the error as
"AttributeError: 'TransformWrapper' object has no attribute '_parents'".
I have googled a lot to find a solution, but invain. As I am a beginner at using Python, kindly help me to fix this .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6fd8a06-35b9-9fc3-4912-d9af48ab95e5
* Version Independent ID: 537915f7-101b-5783-d2a9-546fd7a54ce6
* Content: [Lesson 1 Explore and visualize data using Python and T-SQL - SQL Server Machine Learning - SQL Server](https://docs.microsoft.com/en-us/sql/advanced-analytics/tutorials/sqldev-py3-explore-and-visualize-the-data?view=sql-server-2017#feedback)
* Content Source: [docs/advanced-analytics/tutorials/sqldev-py3-explore-and-visualize-the-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/tutorials/sqldev-py3-explore-and-visualize-the-data.md)
* Product: **sql**
* GitHub Login: @HeidiSteen
* Microsoft Alias: **heidist**

**Comment by MightyPen** [comment]
@HeidiSteen Hi Heidi, Can you please process this Issue 1818, about docs/advanced-analytics/.  Thanks.

**Comment by vijayande** [comment]
Hi @MightyPen or @HeidiSteen 

May I expect some quick response on this please. Now it's more than 7 days already, my learning has been on hold because of this issue.

**Comment by MightyPen** [comment]
@dphansen Hi David, If you are handling docs/advanced-analytics/ documentation now, can you please process this Issue 1818 for @vijayande .

Thanks.  GeneMi.

CC: @HeidiSteen

**Comment by HeidiSteen** [comment]
@vijayande  Hi Vijay sorry for the delayed response.  I cannot reproduce the error you are seeing.  I stepped through perquisites and loaded the tools and packages using the instructions in the docs.  My connection from Jupyter Notebooks is as follows, and it returns the plot.

%matplotlib notebook
import pyodbc
import pickle
import os
cnxn = pyodbc.connect('DRIVER=SQL Server;SERVER=localhost;DATABASE=NYCTAXI_SAMPLE;Trusted_Connection=True;')
cursor = cnxn.cursor()
cursor.execute("EXECUTE [dbo].[PyPlotMatplotlib]")
tables = cursor.fetchall()
for i in range(0, len(tables)):
    fig = pickle.loads(tables[i][0])
    fig.savefig(str(i)+'.png')
print("The plots are saved in directory: ",os.getcwd())

**Comment by HeidiSteen** [comment]
@vijayande   I think you should take a step back and revisit a few of these articles specifically:

1. Make sure Python is working on SQL Server >> https://docs.microsoft.com/en-us/sql/advanced-analytics/tutorials/quickstart-python-verify?view=sql-server-2017

2. Make sure the sample database exists and that you can return data from it >> https://docs.microsoft.com/en-us/sql/advanced-analytics/tutorials/demo-data-nyctaxi-in-sql?view=sql-server-2017

3,  Make sure you have a Python client that can connect to SQL Server: https://docs.microsoft.com/en-us/sql/advanced-analytics/python/setup-python-client-tools-sql?view=sql-server-2017 

I understand that there are a lot of steps, but there are a lot of moving parts when connecting clients to servers.  The connection string, permissions, and compatible tools are essential.

**Comment by vijayande** [comment]
Hi @HeidiSteen , thank you so much. Now I am able to display the plots.
