### ISSUE TITLE
Unlimited Virtualization, improved content clarity

### ISSUE THREAD

**Issue by clarkmac** [MicrosoftDocs/sql-docs#1820]
This being the summary page of SQL edition comparison it would good if it was made more clear that Unlimited Virtualization is only available on Enterprise.  It is referenced in the edition overview but not explicitly called out in the Scale limits section, which would help clarify as many users are looking at Standard Edition now and have been using "Host Licensing" in the past with EE. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 453dc1e2-0c9c-fe95-c6fc-90be886432ad
* Version Independent ID: cd472bc0-26b9-a4a6-4089-31b79be787cb
* Content: [Editions and supported features of SQL Server 2017 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2017?view=sql-server-2017#Other)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-2017.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-2017.md)
* Product: **sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@MikeRayMSFT Hi Mike, Can you please process this Issue 1820.  Thanks.

**Comment by MikeRayMSFT** [comment]
@clarkmac - thank you for the submission. We're evaluating an update for this issue.

**Comment by MikeRayMSFT** [comment]
@clarkmac because this is really a licensing issue and not an issue of technical scale, the information will not be added to the Scale limits section of the article. However you have highlighted an issue we will try to clarify with an update to the documentation. Thank you.
