### ISSUE TITLE
Why pickup_datetime becomes character in the returned dataframe? 

### ISSUE THREAD

**Issue by stevenluda** [MicrosoftDocs/sql-docs#1824]
I'm wondering why pickup_datetime in the returned dataframe is typed as character? This does not align with the instruction here https://docs.microsoft.com/en-us/sql/advanced-analytics/r/r-libraries-and-data-types?view=sql-server-2017. Also, when export dataframe from R to SQL server using rxDataStep, POSIXct became float in database. Why? Any solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bcfc68e-dbf1-736d-50fa-cf45bce80c83
* Version Independent ID: a3c2ed50-4657-f421-f9f2-63c8d132e784
* Content: [View and summarize SQL Server data using R functions - SQL Server Machine Learning - SQL Server](https://docs.microsoft.com/en-us/sql/advanced-analytics/tutorials/walkthrough-view-and-summarize-data-using-r?view=sql-server-2017#feedback)
* Content Source: [docs/advanced-analytics/tutorials/walkthrough-view-and-summarize-data-using-r.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/tutorials/walkthrough-view-and-summarize-data-using-r.md)
* Product: **sql**
* GitHub Login: @HeidiSteen
* Microsoft Alias: **heidist**

**Comment by dphansen** [comment]
@stevenluda My apologies for the delay in responding - I have been out of office. I am in the process of investigating and will get back to you.

**Comment by dphansen** [comment]
@stevenluda The [Data type mappings between R and SQL Server](https://docs.microsoft.com/en-us/sql/advanced-analytics/r/r-libraries-and-data-types?view=sql-server-2017) is only for when you are using [sp_execute_external_script](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-execute-external-script-transact-sql?view=sql-server-2017). 

For `rxGetVarInfo` and `rxDataStep`, please see the [RevoScaleR API documentation](https://docs.microsoft.com/en-us/machine-learning-server/r-reference/revoscaler/revoscaler
) for looking up information on `rx` APIs. Specifically, `colCasses` and `colInfo` parameters in [RxSqlServerData](https://docs.microsoft.com/en-us/machine-learning-server/r-reference/revoscaler/rxsqlserverdata) controls how the data types are mapped.
