### ISSUE TITLE
Many Wait Stats List "TBD" as Description

### ISSUE THREAD

**Issue by blakemartin** [MicrosoftDocs/sql-docs#1831]
Hi Folks!

The wait stats documentation here:
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-wait-stats-transact-sql

....lists "TBD" as a description for a bunch of valid wait stats.  For example, the GLOBAL_QUERY_* waits show up with Azure SQL Elastic Queries.  Would love to see their actual descriptions in there, at your leisure. 

Thank you!

**Comment by MightyPen** [comment]
@blakemartin Hi, you make a fair point.  For several reasons this work item will take months to Complete (not weeks).  Therefore I am shifting this work from this Issue 1831 to our internal DevOps item 1493218.

When 1493218 is Completed, our intention is to update this Issue 1831 again, with an @ notification of you.

https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1493218 

I am now Closing this Issue 1831.

CC: @MashaMSFT 
. .

**Comment by blakemartin** [comment]
Thanks @MightyPen!

**Comment by MashaMSFT** [comment]
Hi @blakemartin , thanks again for bringing this to our attention! There are many wait types that are used for internal purposes only, and so, we have updated the table to reflect that. However, we will be updating a number of wait types opportunistically over time. Thanks again and hope you have a wonderful rest of your day!

**Comment by blakemartin** [comment]
Thanks @MashaMSFT.  Are they also non-descriptive because they're used for a Preview feature?
