### ISSUE TITLE
"Spin up a Virtual Machine with SQL Server 2016 already installed" link does not work

### ISSUE THREAD

**Issue by emilyqiuyu** [MicrosoftDocs/sql-docs#1835]
"Spin up a Virtual Machine with SQL Server 2016 already installed" link brings me to 404 not found page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 468d4b7b-8880-a867-de2c-75e6099474f9
* Version Independent ID: e57139bf-0bd8-eb5c-4896-71488873c1f0
* Content: [Editions and supported features of SQL Server 2016 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2016?view=sql-server-2017#feedback)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-2016.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@MikeRayMSFT Hi Mike, Can you please process this Issue 1835, about a broken link.  Thanks.

@emilyqiuyu

**Comment by MikeRayMSFT** [comment]
Thanks @emilyqiuyu for submitting the issues. 
Fixed by @john-par on March 20. [See commit](https://github.com/MicrosoftDocs/sql-docs/commit/44dbe4f08c727371944c6e19b1d3b0ebc822da27#diff-5027f01da89688cde08148f2d24837b0).
Thanks @john-par
