### ISSUE TITLE
sys.dm_cdc_log_scan_sessions is not linked from System Dynamic Management Views

### ISSUE THREAD

**Issue by tcna** [MicrosoftDocs/sql-docs#1836]
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/change-data-capture-sys-dm-cdc-log-scan-sessions.md

sys.dm_cdc_log_scan_sessions is not linked from https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/system-dynamic-management-views.

I think a page like https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/common-language-runtime-related-dynamic-management-views-transact-sql is also needed for Change Data Capture.

**Comment by MightyPen** [comment]
@tcna Hello, we are no longer in favor of articles that have lists of links that the Table Of Contents (TOC) already supplies.    So we will not be making the update suggested in this Issue 1836.

But I certainly see why you suggested it, your suggestion is logical.

Thanks.  Closing now.

**Comment by MightyPen** [comment]
Oops, Closing now.
