### ISSUE TITLE
Elastic SQL Job sprocs don't have documentation

### ISSUE THREAD

**Issue by SqlSmash** [MicrosoftDocs/sql-docs#1842]
For example, when I use the drop down [here (https://docs.microsoft.com/sql/relational-databases/system-stored-procedures/sp-add-jobstep-transact-sql?view=sql-server-2017)](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-add-jobstep-transact-sql?view=sql-server-2017&viewFallbackFrom=azuresqldb-current) in order to switch from 2017 to single database / elastic pool I get the message "The requested page is not available for Azure SQL Database - current. You have been redirected to the newest product version this page is available for." I want to look up parameters such as @max_parallelism within jobs.sp_add_jobstep but they're nowhere to be found.

![image](https://user-images.githubusercontent.com/49165251/55347365-490f6600-547a-11e9-8771-548935b85d95.png)

![image](https://user-images.githubusercontent.com/49165251/55347372-50367400-547a-11e9-9e62-ec077b86aa62.png)

**Comment by MightyPen** [comment]
@stevestein Hi Steve,

From docs/docfx.json, I paste in the relevant line:
-  `"relational-databases/**/*.md": ">= sql-server-2016 || >= sql-server-linux-2017 || = sqlallproducts-allversions",`

Above, In the docfx.json Versioning line, we see that Azure SQL Database (azuresqldb-current) is unmentioned in the line.

Therefore, this **Issue 1842 might be claiming a Versioning problem.**  Perhaps the sproc that this article _(sp-add-jobstep-transact-sql.md)_ is about has DIfferent parameters depending on whether the sproc is used in SQL Server on-premises versus in Azure SQL Database: is that true?
If yes is true, then:

1. You probably need to research and discover what the parametric differences are; and then.....
2. We need to meet and refine the Versioning of at least this one article, and perhaps more too.

. .

**Comment by SqlSmash** [comment]
Yes, the parameters are different on-prem (msdb) vs. Azure SQL Db (a "Job" database targeted when creating an Elastic Database Job resource).

**Comment by stevestein** [comment]
@SqlSmash  - This issue will be fixed in the documentation, although most likely at the time Elastic Database Jobs goes GA. We have created a new internal tracking number for this work item: 1505325. We are closing this Issue, and are letting the new item track this going forward. You will receive another notice after the internal item if completed. Thank you for submitting this Issue.

Thanks!

**Comment by mytinam** [comment]
This person high tide in to my account and got everything all my
information credit card social security number I've had to put a stop on
everything he is getting my orders and all I cannot check my email I can
receive emails but I can't respond to him to get my tracking number when I
click on the link to find out where my this is what I get so what do I need
to do I need help bad

**Comment by MightyPen** [comment]
@stevestein This Closed Issue 1842 label, I am updating the label from 20-Triage to 41-Tracking-Internally.
Thanks.
