### ISSUE TITLE
Move the reverse DNS check to after joining the machine to the domain

### ISSUE THREAD

**Issue by Dylan-MSFT** [MicrosoftDocs/sql-docs#1845]
On some systems, the rDNS entries will be added by the domain join. Please move the rDNS check to after domain joining so fewer customers will have to do anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12171705-e172-ae55-c93a-7c9c707a6fc8
* Version Independent ID: 918d86e4-98bc-1465-243d-e0cc308f859a
* Content: [Join SQL Server on Linux to Active Directory - SQL Server](https://review.docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-join-domain?view=sql-server-2017&branch=pr-en-us-9662#feedback)
* Content Source: [docs/linux/sql-server-linux-active-directory-join-domain.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-join-domain.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **Dylan.Gray**

**Comment by MightyPen** [comment]
Jason Roth and Dylan Gray - agreed to Close all of these 8 today from Dylan.  Will be handled another way.

Thanks. GeneMi.
