### ISSUE TITLE
When adding SPNs to the keytab, you only add the full SPN

### ISSUE THREAD

**Issue by Dylan-MSFT** [MicrosoftDocs/sql-docs#1848]
When creating SPNs, the instructions create two: FQDN and NetBIOS. When we create the keytab, the instructions only add one. Please have those ktutil instructions add both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Use AD authentication for SQL Server on Linux - SQL Server](https://review.docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017&branch=pr-en-us-9662#feedback)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **Dylan.Gray**

**Comment by MightyPen** [comment]
closing
