### ISSUE TITLE
Extra wkt when adding UPNs to keytab

### ISSUE THREAD

**Issue by Dylan-MSFT** [MicrosoftDocs/sql-docs#1849]
When adding the UPN to mssql.keytab, the second wkt command "wkt /var/opt/mssql/secrets/mssql.keytabe" should be removed. It is unnecessary and misspelled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Use AD authentication for SQL Server on Linux - SQL Server](https://review.docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017&branch=pr-en-us-9662#feedback)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **Dylan.Gray**

**Comment by MightyPen** [comment]
closing
