### ISSUE TITLE
External table docs should include info about First_row option for file format 

### ISSUE THREAD

**Issue by madmaxlax** [MicrosoftDocs/sql-docs#1854]
Regarding documentation article:

- [https://docs.microsoft.com/sql/t-sql/statements/create-external-file-format-transact-sql?view=sql-server-2017](https://docs.microsoft.com/sql/t-sql/statements/create-external-file-format-transact-sql?view=sql-server-2017)

The documentation article should include information, at least for SQL data warehouse, about the `FIRST_ROW` option in the file format, to skip header rows. For instance, the following SQL DW post describes how this `FIRST_ROW` option avoids problems involving a header row:

- [https://azure.microsoft.com/en-us/updates/skip-header-rows-in-sql-dw-load/](https://azure.microsoft.com/en-us/updates/skip-header-rows-in-sql-dw-load/)

In the following T-SQL code block, we can see the `FIRST_ROW` option say that the first row of real data is row 2 (because row 1 is a column header row).

```
CREATE EXTERNAL FILE FORMAT TextFileFormatPipeShortDate 
WITH
(
    FORMAT_TYPE = DELIMITEDTEXT 
    , FORMAT_OPTIONS ( FIELD_TERMINATOR = '|' 
					 , STRING_DELIMITER = '' 
					 , DATE_FORMAT = 'dd-MM-yyyy' 
					 , USE_TYPE_DEFAULT = FALSE 
					 , FIRST_ROW = 2 --skip header row
					 ) 
);
```

( Edited by MightyPen. )

**Comment by MightyPen** [comment]
@madmaxlax  Hello Max, I am unsure, but my glance at the article ('create-external-file-format-transact-sql.md') sees the FIRST_ROW plainly documented. So I am unsure what the precise concern is in the original post here in Issue 1854.

Can you please add another Comment box to clarify the precise concern.
I will keep this Issue 1854 open for a couple days to give enough time for a reply.

Thank you.

**Comment by madmaxlax** [comment]
¯\_(ツ)_/¯
Weird i must've missed it or was mixed up with a different document link i landed on about external tables like https://docs.microsoft.com/en-us/azure/sql-data-warehouse/load-data-wideworldimportersdw

**Comment by julieMSFT** [comment]
@madmax Hi Max, I think it may be a good idea to add this to the tutorial documentation. I will work with the author to complete. Thank you for bringing this to our attention.

**Comment by julieMSFT** [comment]
@madmaxlax Hi Max, I think it may be a good idea to add this to the tutorial documentation. I have completed a new internal tracking number for this work [with](User Story 1496414: SQL DW | Update tutorial to showcase FIRST_ROW feature ). We are closing this issue and tracking this through the new item going forward. You will receive another notice after the internal item is complete.  Thank you for bringing this to our attention.
