### ISSUE TITLE
The distribution database cannot be placed in an availability group.

### ISSUE THREAD

**Issue by lzimmermann** [MicrosoftDocs/sql-docs#1861]
This article states "The distribution database cannot be placed in an availability group." but in https://docs.microsoft.com/en-us/sql/relational-databases/replication/configure-distribution-availability-group?view=sql-server-2017#supported-scenarios the configuration of the distribution Database in an AOAG is explained.

**Comment by MightyPen** [comment]
@MikeRayMSFT Hi Mike, Can you please process this Issue 1861.  Thanks.

**Comment by MashaMSFT** [comment]
Hi @lzimmermann , thanks for bringing this to our attention! Let me look into this a bit further. Thanks!

**Comment by MashaMSFT** [comment]
Hi @lzimmermann , thanks again for notifying us of this! The discrepancy comes from differences in versions. Placing the distribution database is supported only for SQL Server 2016 and higher. I've added a note clarifying this to the document, and it should be live tomorrow morning. Please let me know if you need anything further, or if I can proceed with closing out this Git Issue. Thanks!

**Comment by lzimmermann** [comment]
Hi masha, thanks very mich for the Update!



Freundliche Grüße
Lars Zimmermann

Outlook for Android herunterladen

________________________________

**Comment by MashaMSFT** [comment]
Hi @lzimmermann , thanks for your feedback! I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!
