### ISSUE TITLE
Is "commit" included

### ISSUE THREAD

**Issue by kenny-va** [MicrosoftDocs/sql-docs#1874]
Is a "commit" automatically included in the execution plan?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960815fc-a05d-b887-e5a8-e4aef6761000
* Version Independent ID: 4af0d0ae-c858-9b92-3058-a2e43f60bd8d
* Content: [GO (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-go?view=sql-server-2017)
* Content Source: [docs/t-sql/language-elements/sql-server-utilities-statements-go.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/sql-server-utilities-statements-go.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by MightyPen** [comment]
You can test this by starting with an explicit BEGIN TRANSACTION statement, then INSERT a row into a regular permanent table, followed by GO.
Then, on a second/different connection, try to SELECT the row.
The test result will show that you canNot SELECT the row, yet.
Next, on the original connection, you can issue a COMMIT TRANSACTION.
Finally, on the second connection, again try to SELECT the row, and this time see that yes you Can see the row.
---
If there is no explicit BEGIN TRANSACTION, the default configuration is that the T-SQL system auto-commits after every statement.

Thanks for the inquiry. Given this answer, I believe we can now Close this Issue as Answered.
Even after an Issue is Closed, the @ notification syntax still functions, if further communication is necessary.

**Comment by MightyPen** [comment]
@kenny-va Hi Kenny,
You can test this by starting with an explicit BEGIN TRANSACTION statement, then INSERT a row into a regular permanent table, followed by GO.
Then, on a second/different connection, try to SELECT the row.
The test result will show that you canNot SELECT the row, yet.
Next, on the original connection, you can issue a COMMIT TRANSACTION.
Finally, on the second connection, again try to SELECT the row, and this time see that yes you Can see the row.

---

If there is no explicit BEGIN TRANSACTION, the default configuration is that the T-SQL system auto-commits after every statement.

Thanks for the inquiry. Given this answer, I believe we can now Close this Issue as Answered.
Even after an Issue is Closed, the @ notification syntax still functions, if further communication is necessary.
