### ISSUE TITLE
code incomplete

### ISSUE THREAD

**Issue by sqlsrvgeek** [MicrosoftDocs/sql-docs#1875]
For the following code, parenthesis and single quotes are missing:
CREATE EXTERNAL DATA SOURCE external_data_source_name
WITH ( 
LOCATION = oracle://&lt;server address&gt;[:&lt;port&gt;],
-- PUSHDOWN = ON | OFF,
 CREDENTIAL = credential_name

Should be:

CREATE EXTERNAL DATA SOURCE external_data_source_name
WITH ( 
LOCATION = 'oracle://&lt;server address&gt;[:&lt;port&gt;]',
-- PUSHDOWN = ON | OFF,
 CREDENTIAL = credential_name);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4670a32c-843d-3464-dce8-2f4bb05612de
* Version Independent ID: 16c2982c-9788-7f33-61c0-9ba269361e37
* Content: [Configure PolyBase to access external data in Oracle - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-configure-oracle?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/relational-databases/polybase/polybase-configure-oracle.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-oracle.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @abiola
* Microsoft Alias: **aboke**

**Comment by rothja** [comment]
@sqlsrvgeek Thank you. Sorry for this bad mistake.  I'll get a fix in and close this issue out when it merges. It might be another half-day after that before the change shows up. Thanks, again!
