### ISSUE TITLE
location issue

### ISSUE THREAD

**Issue by sqlsrvgeek** [MicrosoftDocs/sql-docs#1876]
Location needs to be updated in 3 parts:
/*  LOCATION: Oracle table/view in '&lt;database_name&gt;.&lt;schema_name&gt;.&lt;object_name&gt;' format
*  DATA_SOURCE: the external data source, created above.
*/
CREATE EXTERNAL TABLE customers(
[O_ORDERKEY] DECIMAL(38) NOT NULL,
[O_CUSTKEY] DECIMAL(38) NOT NULL,
[O_ORDERSTATUS] CHAR COLLATE Latin1_General_BIN NOT NULL,
[O_TOTALPRICE] DECIMAL(15,2) NOT NULL,
[O_ORDERDATE] DATETIME2(0) NOT NULL,
[O_ORDERPRIORITY] CHAR(15) COLLATE Latin1_General_BIN NOT NULL,
[O_CLERK] CHAR(15) COLLATE Latin1_General_BIN NOT NULL,
[O_SHIPPRIORITY] DECIMAL(38) NOT NULL,
[O_COMMENT] VARCHAR(79) COLLATE Latin1_General_BIN NOT NULL
)
WITH (
LOCATION='SID.owner.customer',
DATA_SOURCE=  external_data_source_name
);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4670a32c-843d-3464-dce8-2f4bb05612de
* Version Independent ID: 16c2982c-9788-7f33-61c0-9ba269361e37
* Content: [Configure PolyBase to access external data in Oracle - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-configure-oracle?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/relational-databases/polybase/polybase-configure-oracle.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-oracle.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @abiola
* Microsoft Alias: **aboke**

**Comment by rothja** [comment]
@sqlsrvgeek Thanks! I'll confirm and then make the change. Appreciate it.

**Comment by rothja** [comment]
@sqlsrvgeek Thanks, again for this feedback. We're making some simplifications to this article soon where the syntax for create external table will not be shown here. We'll then improve the CREATE EXTERNAL TABLE docs and examples. So I'm closing this for now without changing this yet, but it will get addressed very soon. Thank you.
