### ISSUE TITLE
Example needs cleaned up.

### ISSUE THREAD

**Issue by Protiguous** [MicrosoftDocs/sql-docs#1877]
The example fails in a case-sensitive database with the "ID" and "id" columns.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84c44dc1-637b-22b0-35db-0668d741818d
* Version Independent ID: 5425118c-d998-df3e-89ee-29656a8aa07c
* Content: [SQL Graph Database Sample - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-sample?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/graphs/sql-graph-sample.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/graphs/sql-graph-sample.md)
* Product: **sql**
* GitHub Login: @shkale-msft
* Microsoft Alias: **shkale**

**Comment by Protiguous** [comment]
Also fails on the columns "friendOf" and "Person".

**Comment by julieMSFT** [comment]
@Protiguous Hello, I have update the code in the article. The PR number is 9775 at [https://github.com/MicrosoftDocs/sql-docs-pr/pull/9775](url) you for bringing this to our attention. I will proceed to close this issue.
