### ISSUE TITLE
This page doesn't provide the information that it says it does.

### ISSUE THREAD

**Issue by mrdenny** [MicrosoftDocs/sql-docs#1879]
The title of this page is "Change Server Authentication Mode" yet the example in T-SQL is how to enable the sa login for use. Which, while helpful isn't what the page say it is for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9b632d-7e6d-1434-cc6b-9aa77d37f41a
* Version Independent ID: 3689727c-e685-1503-fd9e-365aa15c33fa
* Content: [Change Server Authentication Mode - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/change-server-authentication-mode?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/configure-windows/change-server-authentication-mode.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/change-server-authentication-mode.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by julieMSFT** [comment]
@MikeRayMSFT Hi Mike, I belive adding the T-SQL to change the server authentication mode would resolve this issue.
CC:@mrdenny This Issue has been assigned to the article owner, who will triage this Issue. You will be notified again when the triage phase is completed.

**Comment by MikeRayMSFT** [comment]
Thank you @mrdenny for pointing this out. We'll clean it up.

**Comment by PaulBags** [comment]
Uh, nothing changed, and nothing in the article allows sql server to accept it's own authentication.

**Comment by julieMSFT** [comment]
@PaulBags Hello, thank you for you comment. Looking at the article it does show how to change the authentication mode, can you provide more information about what you are expecting to see?
