### ISSUE TITLE
 Integration Services extension in Visual Studio 2019 doesn't exist

### ISSUE THREAD

**Issue by mosharafMS** [MicrosoftDocs/sql-docs#1880]
In the install SQL Server Data Tools doc, it mentions that starting in VS 2019, the  Integration Services is implemented as extension but when searching for this extension it doesn't exist as indicated by the doc.

**Comment by julieMSFT** [comment]
@mosharafMS  Hi, can you please provide the article where you see this reference?

**Comment by djharvey999** [comment]
https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017

> Changes in SSDT for Visual Studio 2019
> With Visual Studio 2019, the required functionality to enable Analysis Services, **Integration Services**, and Reporting Services projects has moved into the respective Visual Studio extensions. The core SSDT functionality to create Database Projects has remained integral to Visual Studio (you need to select the Data storage and processing workload during install). There is no more standalone SSDT installation required.
> 
> If you already have a license to Visual Studio 2019:
> 
> For SQL Database Projects, install the Data storage and Processing workload for Visual Studio
> For Analysis Services, **Integration Services** or Reporting Services projects, install the appropriate extension(s) from the marketplace

Microsoft Integration Services can't be found in the VS Marketplace.

**Comment by julieMSFT** [comment]
@djharvey999 Thank you for the details and the article link. This has been assigned to the author to review.
@stevestein Hi Steve, please triage this issue.

**Comment by fan130** [comment]
We have released SSIS design tools for VS2019 (preview) at: https://marketplace.visualstudio.com/items?itemName=SSIS.SqlServerIntegrationServicesProjects

**Comment by stevestein** [comment]
@mosharafMS - Thanks for raising this issue. I'm going to close this issue. Let us know if you need any additional info. 
@fan130 - Thanks for the reply and link.
