### ISSUE TITLE
unixodbc unsatisfied dependency on Debian 9.8

### ISSUE THREAD

**Issue by nattomi** [MicrosoftDocs/sql-docs#1882]
Any workaround for Debian 9.8 yet? apt install unixodbc leads to "unsatisfied dependency: odbcinst1debian2 (&gt;= 2.3.7) but only 2.3.4-1 can be installed".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@nattomi Right now, we don't have explicit support or testing for Debian as a target for SQL Server on Linux, so it may be that there is no work around at the moment to get it working. I'm sorry for the answer, but I'll pass along your feedback requesting that we support Debian and remove any install blockers like this.

**Comment by MightyPen** [comment]
Closing.
