### ISSUE TITLE
No information for SQL Server 2017/2019 Express LocalDB

### ISSUE THREAD

**Issue by CodeTherapist** [MicrosoftDocs/sql-docs#1883]
The information for 2017 and 2019 version is missing and could be confusing for the reader.
Otherwise I would suggest to remove the "2016" from the page, when the installation steps and features are version independent and still accurate.
In any case I would voluntary contribute the fix(es) for this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b697e36f-a8d8-b0a1-6439-3138d1d52dea
* Version Independent ID: 472f6985-c656-772f-c793-91662de53083
* Content: [SQL Server 2016 Express LocalDB - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-2016-express-localdb?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/configure-windows/sql-server-2016-express-localdb.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/sql-server-2016-express-localdb.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by julieMSFT** [comment]
Hi @CodeTherapist, 
thanks for bringing this to our attention! You can actually add the change yourself! You can find more information here at [http://aka.ms/editsqldocs](url). Thanks for helping to improve our documentation :)

**Comment by CodeTherapist** [comment]
Hi @julieMSFT,
Not sure I follow, but the link is not showing any results, or did I miss something?

**Comment by MikeRayMSFT** [comment]
> Hi @julieMSFT,
> Not sure I follow, but the link is not showing any results, or did I miss something?

@CodeTherapist  - I updated the link in @julieMSFT 's comment. It should point to the correct place if you want to update the documentation yourself in the future.

For this issue, I'm updating it to remove the version (2016). I appreciate you pointing it out. Thanks!
