### ISSUE TITLE
Depreciated Feature

### ISSUE THREAD

**Issue by awilbert** [MicrosoftDocs/sql-docs#1884]
Per the release notes, Static Data Masking was removed in SSMS 18.0 RC1.
"Deprecated feature Details: Removed the Static Data Masking (preview) feature."

I hope it makes a comeback as it looked like it could have been a useful feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94aa1791-17e9-40de-eb28-4410e26fe24d
* Version Independent ID: 4a9c6546-4d09-fb60-817e-c643d2c71bef
* Content: [Static Data Masking - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/static-data-masking?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/static-data-masking.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/static-data-masking.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @egranet
* Microsoft Alias: **aliceku**

**Comment by julieMSFT** [comment]
@egranet Hi Estienne, please review and clarify what is meant by "Removed the Static Data Masking (preview) feature."? Thank you.

**Comment by tbolon** [comment]
@julieMSFT https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#deprecated-features great job :D

**Comment by julieMSFT** [comment]
@aliceku @vanmsft FYI..

**Comment by aliceku** [comment]
We do agree that this is a useful feature.  We have however decided that our current prototype does not meet our customer’s expectations. We will therefore not carry this capability forward. We will update you on our plans if we have a replacement candidate.

**Comment by julieMSFT** [comment]
HI @wilbert thanks for asking this question. It has been answered by @aliceku. I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!
