### ISSUE TITLE
SSDT 2019 suggests using community edition but licensing doesn't allow that for enterprises

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/sql-docs#1886]
On https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssdt/download-sql-server-data-tools-ssdt.md

> If you don’t already have a license to Visual Studio 2019:
>
>    Install Visual Studio 2019 Community
>    Install the Analysis Services, Integration Services or Reporting Services as appropriate

Community Edition can't be used for enterprise users, so is there an enterprise option anymore without purchasing Visual Studio subscriptions just for SSDT?

**Comment by julieMSFT** [comment]
@stevestein Hi Steve, please triage this issue.
CC: @nschonni This Issue has been assigned to the article owner, who will triage this Issue. You will be notified again when the triage phase is completed.

**Comment by timchenyx** [comment]
The EULA of VS 2019 community edition has a specific section that allows enterprise users to use it for the SSDT workload. See https://visualstudio.microsoft.com/license-terms/mlt031819/. 

_Any number of your users may use the software only for Microsoft SQL Server development when using the SQL Server Data Tools or the extensions “Microsoft Analysis Services Projects”, “Microsoft Reporting Services Projects”, or “SQL Server Integration Services Projects” to develop Microsoft SQL Server database projects or Analysis Services, Reporting Services, Power BI Report Server, or Integration Services projects._

**Comment by stevestein** [comment]
@timchenyx - Thanks for the clarification.
@nschonni - I'm going to close this one.
