### ISSUE TITLE
Catalog Views available in Azure Database and DW

### ISSUE THREAD

**Issue by cheenamalhotra** [MicrosoftDocs/sql-docs#1887]
These catalog views seem to be available in Azure DB and DW. Product team should confirm if that's expected behavior and documentation should be updated accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e44d6f5-818c-fdf0-8169-d23d0b6a0b68
* Version Independent ID: af6b6d8b-d984-faba-ff8e-ddf7fe954f36
* Content: [Object Catalog Views (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/object-catalog-views-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-catalog-views/object-catalog-views-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/object-catalog-views-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by julieMSFT** [comment]
@stevestein Hi Steve, please triage this article.
CC: @cheenamalhotra Hi Chenna, This Issue has been assigned to the article owner, who will triage this Issue. You will be notified again when the triage phase is completed.

**Comment by stevestein** [comment]
@cheenamalhotra - This issue will be fixed in the documentation. We have created a new internal tracking number for this work item: 1518995. We are closing this Issue, and are letting the new item track this going forward. You will receive another notice after the internal item is completed. Thank you for submitting this Issue.
