### ISSUE TITLE
Graphic does not display properly in Dark Theme

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#1889]
Not the largest issue in the world, but this may affect other pages as well.  If you switch the page to Dark Theme - which I now use by default since IPS panels on most screens have excessive glare/brightness -  the writing on the graphic shows up garbled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79a2eb85-039d-26b9-a89f-22cdbd9a05fb
* Version Independent ID: fcbc84da-0ef8-f57f-9a1c-08cdb7d17341
* Content: [SQL Server Multi-Subnet Clustering (SQL Server) - SQL Server Always On](https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/windows/sql-server-multi-subnet-clustering-sql-server?view=sql-server-2017)
* Content Source: [docs/sql-server/failover-clusters/windows/sql-server-multi-subnet-clustering-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/failover-clusters/windows/sql-server-multi-subnet-clustering-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @PrometheusRising1 , thanks for bringing this to our attention! Let me see what can be done about it... Thanks!

**Comment by MashaMSFT** [comment]
Hi @PrometheusRising1 , thanks again for bringing this to our attention!  I have updated the graphic so that it renders correctly in dark mode. This change should be live later today :) Please let me know if we could of further assistance. Thanks!

**Comment by julieMSFT** [comment]
HI @PrometheusRising1, I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!
