### ISSUE TITLE
incorrect info ?

### ISSUE THREAD

**Issue by leonbravo** [MicrosoftDocs/sql-docs#1890]
Error Reporting section states  "a dump file (SQLDUMP*nnnn*.txt) is created in the SQL Server LOG directory"   instead the  Dump directory is used. For locating this  SQL Server Configuration Manager, Advanced options. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2be5880-3a17-99a1-10b8-0c907f211667
* Version Independent ID: c0670e45-ead4-a8d3-0345-b7ee9052afce
* Content: [DBCC CHECKDB (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-checkdb-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/database-console-commands/dbcc-checkdb-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/database-console-commands/dbcc-checkdb-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **umajay**

**Comment by julieMSFT** [comment]
@pmasl Hi Pedro, You are the listed as the author of this article, so this issue has been assigned to you. Please triage this Issue.  Then update the label, and notify the customer.
CC: @leonbravo Hello, Thank you your submission. This issue has been assigned to the author to review.

**Comment by pmasl** [comment]
It is not incorrect. In case of AV, dumps (SQLDumpXXXX.log, SQLDumpXXXX.txt, and SQLDumpXXXX.mdmp) are stored in the LOG folder, where the errorlog and default trace files reside.

**Comment by MightyPen** [comment]
@leonbravo Hi Leon, Pedro has supplied an answer.
It might have been helpful to me if the original post, and the answer, had given an explicit example of their paths. But you two seem to know which exact paths, or final directory names you are talking about.

With Pedro's answer supplied, I am now closing this Issue 1890.
Thank you for inquiring.

CC: @pmasl
