### ISSUE TITLE
Algorithm availability statement incorrect

### ISSUE THREAD

**Issue by SQLKiwi** [MicrosoftDocs/sql-docs#1891]
The Remarks section of this page says "The MD2, MD4, MD5, SHA, and SHA1 algorithms are not available under compatibility level 130 and above.", which is not true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c0b314-20ee-183a-295f-eb1b59fd4005
* Version Independent ID: ed13d463-36d1-570b-e72d-e5adbdc450c5
* Content: [HASHBYTES (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/hashbytes-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/hashbytes-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/hashbytes-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @SQLKiwi , thanks for bringing this to our attention! Let me do a little research. Thanks!

**Comment by pmasl** [comment]
I'm correcting this to remove the DB compat claim.

**Comment by VanMSFT** [comment]
@pmasl - Thank you so much, Pedro!

@SQLKiwi - Paul, thank you for bringing this up to our attention. We really appreciate your help on this. Since Pedro will be updating the doc, we will go ahead and close this GitHub Issue now. If you have any questions, please feel free to let us know. Thanks again!

**Comment by gflores1023** [comment]
@pmasl Can you also correct this link which has the same erroneous statement?
[Deprecated in SQL Server 2017](https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-2017?view=sql-server-2017)

**Comment by pmasl** [comment]
@gflores1023 yes. Give it a few hours.
