### ISSUE TITLE
estimated compression ratio

### ISSUE THREAD

**Issue by vividt** [MicrosoftDocs/sql-docs#1892]
any estimated compression ratio?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55ef9922-308b-0b7e-c29a-0df7b858efac
* Version Independent ID: aebe1d11-c356-f77f-4716-a7691fe0a147
* Content: [Tune compression for availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/tune-compression-for-availability-group?view=sql-server-2017)
* Content Source: [docs/database-engine/availability-groups/windows/tune-compression-for-availability-group.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/tune-compression-for-availability-group.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @vividt , thanks for bringing this to our attention! Let me research a bit. Thanks!

**Comment by SQLSourabh** [comment]
Hi @vividt, we currently do not track metrics around the estimated or actual compression of the log blocks.

**Comment by MashaMSFT** [comment]
Hi @vividt , thanks for notifying of this gap! We will take this feedback to the product group to see if this is something implementable in the future. Since the question has been answered, I will proceed with closing out this Git Issue but please feel free to reply should you need anything further. Thanks!
