### ISSUE TITLE
mssql-conf setup and MSSQL_Collation change

### ISSUE THREAD

**Issue by mco100** [MicrosoftDocs/sql-docs#1893]
On Linux Redhat 7.5 and SQL Server 2017 (14.0.3076.1), 

I want to avoid below interactive command (that works fine BTW) to change SQL Server engine collation.
_sudo /opt/mssql/bin/mssql-conf set-collation_

But mssql-conf setup command with env. variable "MSSQL_COLLATION", does not work. 
By example, in below command, "MSSQL_COLLATION"argument is ignored (all other arguments are acknowledged).
_sudo ACCEPT_EULA='Y' MSSQL_PID='xxx' MSSQL_SA_PASSWORD='xxx' MSSQL_COLLATION='xxx' /opt/mssql/bin/mssql-conf setup_

Is it an issue, a mistake of mine or a missing SQL CU ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12eac8a-8797-b2d4-5195-e1d77b4b0001
* Version Independent ID: 163b4b50-6e25-b006-6ea6-c6e4cfd044d0
* Content: [Configure SQL Server settings with environment variables - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-configure-environment-variables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-environment-variables.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by julieMSFT** [comment]
@mco100 Thank you for bringing this to our attention. The author has been assigned to review this.
@rothja Please review this issue.

**Comment by rothja** [comment]
@mco100 Thank you. I'm looking into this and speaking with others internally about whether there are any known issues here.

**Comment by rothja** [comment]
@mco100 I apologize for the delay. I'm still investigating this and will have an update as soon as possible. Thank you!

**Comment by rothja** [comment]
@mco100 Thanks for your patience. Also, based on your help, we think we have identified a problem with using the environment variable to change the collation. We're still testing, so the documentation won't be updated immediately. Unfortunately, this means that the only way to change the collation is through mssql-conf set-collation. I apologize for this answer, as that is not what you were looking to do. After we figure out the problem, I'll update the documentation and maybe the behavior will get changed/fixed for a future cumulative update.

At this time I am going to close this issue, but please add any additional comments or questions on this issue thread. Thank you!
