### ISSUE TITLE
semicolons

### ISSUE THREAD

**Issue by ecklesweb** [MicrosoftDocs/sql-docs#1895]
There should not be a semicolon between the option clause and the rest of the select statement.  The option clause is a part of the select just like from or where.  Once we removed the semicolon before option, these examples started to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d712c8-87f2-7203-6dd9-5f23a60cdfc2
* Version Independent ID: 536de496-f292-b661-7da7-350d59ec331f
* Content: [Cardinality Estimation (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/cardinality-estimation-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/performance/cardinality-estimation-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/cardinality-estimation-sql-server.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by julieMSFT** [comment]
@ecklesweb Thank you for bringing this to our attention. I have submitted a PR, #9796, to correct this. [https://github.com/MicrosoftDocs/sql-docs-pr/pull/9796](url). It should be live tomorrow morning. Please let me know if you need anything further, or if I can proceed with closing out this Git Issue. Thanks!

**Comment by MightyPen** [comment]
Thanks for this fix Julie (PR 9796).  We can now Close this Issue 1895.
@julieMSFT @ecklesweb

**Comment by julieMSFT** [comment]
Hi Gene, I was waiting to see if the customer responded. I will close open issues after giving the customer some time to respond.


Thank you,

Julie

**Comment by ecklesweb** [comment]
Looks good to me.
