### ISSUE TITLE
ssbdiagnose tool is documented but the tool is missing

### ISSUE THREAD

**Issue by greglow** [MicrosoftDocs/sql-docs#1896]
The page documenting ssbdiagnose is fine. The problem is that the tool used to be installed when SQL Server was installed. It's also not in the feature pack. Anyone know where the tool can now be downloaded/installed from? If it's from another location, that needs to be documented.

**Comment by julieMSFT** [comment]
@greglow 
thanks for bringing this to our attention! The author has been notified to take a look. Thanks!

**Comment by craigg-msft** [comment]
@stevestein please review.

**Comment by stevestein** [comment]
@greglow - Thanks for raising this issue. I'll hoping to have some info in the next few days as to what the details are for getting ssbdiagnose. I'll reply again shortly as well as update the [ssbdiagnose article](https://docs.microsoft.com/en-us/sql/tools/ssbdiagnose/ssbdiagnose-utility-service-broker?view=sqlallproducts-allversions). 

Thanks again, and appreciate your patience.

**Comment by stevestein** [comment]
@greglow - The team is currently working on this but to help users who need the utility we added a note to the top of the [ssbdiagnose ](https://docs.microsoft.com/sql/tools/ssbdiagnose/ssbdiagnose-utility-service-broke) page saying to install _ssbdiagnose_ by installing SSMS 17.9.1.  

I'm going to go ahead and close this issue. We'll update the article/note when the download details change.

Thanks again for raising this one.
