### ISSUE TITLE
UPDATE() and COLUMNS_UPDATED() will be 1/TRUE for columns that are mentioned in UPDATE SET... ?

### ISSUE THREAD

**Issue by baodad** [MicrosoftDocs/sql-docs#1897]
I've been told that, even if a column value does not change as a result of the UPDATE or INSERT statement that led to the trigger, as long as the column was listed in the statement, it will cause UPDATE() and COLUMNS_UPDATED() to be set to TRUE or 1 for that column.

If this is true, then UPDATE() and COLUMNS_UPDATED() are not as helpful for determining if a value was actually changed by a SQL statement.  Perhaps this should be mentioned in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52d12681-a6f1-258a-d25a-b47741883a88
* Version Independent ID: 72ad45a0-a3d2-1b62-d7c5-2237909d4f4a
* Content: [COLUMNS_UPDATED (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/columns-updated-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/columns-updated-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/columns-updated-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @baodad , thanks for bringing this to our attention! Let me do a little research and get back to you. Thanks!

**Comment by MightyPen** [comment]
@baodad Hello baodad, I believe you can test this by tweaking an example found in the article you cited.

https://docs.microsoft.com/en-us/sql/t-sql/functions/columns-updated-transact-sql?view=sql-server-2017#examples

Thank you inquiring.
I am closing this Issue 1897 now. However, the @ notification system continues to work even after an issue is closed, if necessary.

CC: @MashaMSFT @julieMSFT

**Comment by baodad** [comment]
@MightyPen OK.  Seems like an important detail that is left out of the docs.  Just trying to suggest an improvement.

**Comment by MashaMSFT** [comment]
Hi @baodad, you can actually add the change yourself! You can find more information here at http://aka.ms/editsqldocs. Thanks for helping to improve our documentation :)

**Comment by MashaMSFT** [comment]
Hi @baodad , thanks again for bringing this to our attention! I've added a note to both the UPDATED() and COLUMNS_UPDATED() documentation stating that this behavior is by-design: 

If a trigger applies to a column, the COLUMNS_UPDATED returns as true or 1, even if the column value remains unchanged. This is by-design, and the trigger should implement business logic that determines if the insert/update/delete operation is permissible or not.

Hope that helps and please let me know if we could be of further assistance. Thanks!

**Comment by baodad** [comment]
@MashaMSFT I do not see the note you added in the document, but thanks for following up on this.
