### ISSUE TITLE
Link to "Allowing Partially Trusted Callers" article is incorrect 

### ISSUE THREAD

**Issue by turimbar1** [MicrosoftDocs/sql-docs#1898]
The link to the article "Allowing Partially Trusted Callers" takes you to a Chinese language page about analysis services instead of "Allowing Partially Trusted Callers" 

The page is https://docs.microsoft.com/zh-tw/sql/database-engine/query-options-pages-f1-help?view=sql-server-2014 
with the heading "查詢選項頁面 F1 說明" or  "Query option page F1 Description"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40d77088-b157-852e-8394-fc2419916a09
* Version Independent ID: 0b1dd4dd-242b-1a62-cf6b-dda7c8b8fa68
* Content: [CLR Integration Security - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/security/clr-integration-security?view=sql-server-2017)
* Content Source: [docs/relational-databases/clr-integration/security/clr-integration-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/clr-integration/security/clr-integration-security.md)
* Product: **sql**
* Technology: **clr**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by turimbar1** [comment]
I think this is the correct link https://docs.microsoft.com/en-us/sql/database-engine/dev-guide/allowing-partially-trusted-callers?view=sql-server-2014

**Comment by julieMSFT** [comment]
@turimbar1 thanks for bringing this to our attention! I believe you are correct on the link. I have updated the document. You should see it tomorrow. Please let me know if you need anything further, or if I can proceed with closing out this Git Issue. Thanks!

**Comment by julieMSFT** [comment]
#9796

**Comment by julieMSFT** [comment]
@turimbar1 
Please let me know if you need anything further. I will proceed with closing out this Git Issue. Thanks!
