### ISSUE TITLE
more examples in T-SQL needed with explanation

### ISSUE THREAD

**Issue by marchelloUA** [MicrosoftDocs/sql-docs#1901]
How do I prepare T-SQL to schedule running stored procedure every 3 hours (every day, starting from now, no expiration date)? 
Tried to follow example above, but it is rather not intuitive and each parameter is not explained in T-SQL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e755e952-4bd9-8547-d856-7b781c0e9594
* Version Independent ID: 5e4febe5-6b29-77bd-94c8-4bccd1e9afb3
* Content: [Schedule a Job - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/agent/schedule-a-job?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/agent/schedule-a-job.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/schedule-a-job.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by julieMSFT** [comment]
@marchelloUA Hi, thank you for your question. You can schedule a job to run every three hours. You first need to set up running the stored procedure as a job. See this article, [https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-run-sql-server-agent-job?view=sql-server-2017#create-a-job-with-ssms](url) . The step command will be "EXEC schema.nameofstoredprocedure". Ensure you select the database to run the stored procedure in. Once the job is set up you can schedule it as a recurring job running every three hours.
![image](https://user-images.githubusercontent.com/44736634/55895641-6971ab80-5b71-11e9-9415-cad20c32ff81.png) Let me know if you need more information.

**Comment by julieMSFT** [comment]
Hi @marchelloUA Please let me know if you need anything further.  I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!
