### ISSUE TITLE
Step produce error

### ISSUE THREAD

**Issue by wanqiaoyi** [MicrosoftDocs/sql-docs#1906]
The steps above state to be for "If an unrestored filegroup will never have to be restored, you can make the filegroup defunct by removing it from the database."   

After successfully performing a FILEGROUP restore of PRIMARY,  the steps above were used to try to remove an OFFLINE, unneeded secondary data file.   The error "Cannot add, remove, or modify a file in filegroup 'SECONDARY_FILE' because the filegroup is not online"   is produced.  

I have been unable to find any solution to remove this secondary file from the database.   I have migrated all user objects to the PRIMARY file.  some legacy internal (many, many years prior me) objects still remain on the file similar to "queue_messages_1577876788" that aren't tied to any real existing Queues     situation is exactly similar to https://social.msdn.microsoft.com/Forums/sqlserver/en-US/3bdbf445-f5b5-44ba-bc0b-e691be7f3b72/how-to-move-internal-tables-to-new-filegroup?forum=sqldatabaseengine and https://thesqldude.com/tag/queue_messages/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eff32bba-bc17-e118-7a4e-fcd0d5954ad0
* Version Independent ID: 91b2944d-b958-5063-7551-52ab55501264
* Content: [Remove Defunct Filegroups (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/remove-defunct-filegroups-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/backup-restore/remove-defunct-filegroups-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/remove-defunct-filegroups-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by julieMSFT** [comment]
HI @wanqiaoyi, thanks for contacting Microsoft! Unfortunately, your request is outside the scope of this communication channel, which is intended to focus on documentation assistance. The only thing I can suggest is possibly bringing your filegroup online, the following stackoverflow post may prove useful to you: [https://stackoverflow.com/questions/33245139/bringing-sql-server-filegroups-online](url)

If not, your best bet would be to contact support. You can do so for a [business](https://support.microsoft.com/en-us/help/4341255/support-for-business), or as a [consumer](https://support.microsoft.com/en-us/hub/4343728/support-for-business). 

I'm sorry, I wish I was able to assist more, and best of luck! I'll proceed with closing out this Doc Issue now but please feel free to reply if we could do more for you.

Thanks!

**Comment by MightyPen** [comment]
@MikeRayMSFT FYI.
