### ISSUE TITLE
MDS Roadmap or Profisee?

### ISSUE THREAD

**Issue by valcs007** [MicrosoftDocs/sql-docs#1908]
Hi,

For our enterprise level master data needs, we are seriously considering Microsoft MDS solution but we wanted to check if Microsoft has a strong road map for MDS before we get on board.

We are seeing articles floating around bout Microsoft push towards Profisee?

We really appreciate your thoughts.

Thanks,

**Comment by julieMSFT** [comment]
Hi @valcs007, Thank you for your question. I am doing some research and will get back to you.

**Comment by MightyPen** [comment]
@lrtoyou1223 Hi Leo, Can you please enter a Comment here into this Issue 1908, about Master Data Services, for @valcs007.

CC: @julieMSFT

**Comment by lrtoyou1223** [comment]
Hi @valcs007,
Thanks for reaching out. For the roadmap of MDS, we remove the Silverlight dependency in SQL vNext which means users can use other browsers than IE. But we don’t have any other features or Azure story planned after that right now. 
Profisee is still Microsoft's partner in MDM area.
Hope this answers your questions.
Thanks.

**Comment by valcs007** [comment]
Thanks everyone for getting me to the right person.

Leo, 

Thanks for sharing about vNext. Can you please let me know the timeline?

Reg future of MDS, is this in Microsoft’s long term roadmap?

We don’t want to choose a platform that will be dying in few years since we are starting something new. Is Profisee a replacement?

Thanks,

**Comment by MightyPen** [comment]
Hi @valcs007 , Leo has given all the info there is to give.
I am going to Close this Issue 1908 now as answered.
The @ notification mechanism continues to work, even after an Issue is closed, should further communication be necessary.
Thank you for inquiring.

**Comment by lrtoyou1223** [comment]
Hi @valcs007,
MDS will be released in SQL 2019, current is CTP 2.5. The probable GA date is by the end of this year.
We don't have any deprecation plan for MDS now and will continue supporting this product in future.
Thanks.

**Comment by valcs007** [comment]
Thanks Leo!
