### ISSUE TITLE
T-SQL way to enable a database for replication?

### ISSUE THREAD

**Issue by marchelloUA** [MicrosoftDocs/sql-docs#1913]
T-SQL way to enable a database for replication?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 456c5562-979c-cecd-e6b5-bf3e4ec6aaab
* Version Independent ID: 7b9bd83a-1d63-038a-3434-c5dd41188040
* Content: [Enable a Database for Replication (SQL Server Management Studio) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/enable-a-database-for-replication-sql-server-management-studio?view=sql-server-2017)
* Content Source: [docs/relational-databases/replication/enable-a-database-for-replication-sql-server-management-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/enable-a-database-for-replication-sql-server-management-studio.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @marchelloUA , thanks for contacting Microsoft! As long as distribution has been configured, you can enable a database for replication via:

```sql
use master
exec sp_replicationdboption @dbname = 'AdventureWorks2017',
@optname = 'publish',
@value = 'true'
go
```

To disable it, set the @value = 'false'. 

I hope that helps and please let me know if I can be of further assistance. Thanks!

**Comment by MashaMSFT** [comment]
Hi @marchelloUA , thanks for bringing this to our attention! I also updated the document to include the t-sql option as well. This change should be live later today. Hope that helps, and please let me know if there's  more I can do for you? Thanks!

**Comment by julieMSFT** [comment]
Hi @marchelloUA, I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!
