### ISSUE TITLE
feedback 

### ISSUE THREAD

**Issue by LuccaC** [MicrosoftDocs/sql-docs#1918]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96bf154-662d-369f-09e9-4a90d377a63f
* Version Independent ID: ae08216f-092c-b86e-ee0d-b0a8bb923465
* Content: [sys.database_mirroring_witnesses (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/database-mirroring-witness-catalog-views-sys-database-mirroring-witnesses?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-catalog-views/database-mirroring-witness-catalog-views-sys-database-mirroring-witnesses.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/database-mirroring-witness-catalog-views-sys-database-mirroring-witnesses.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @LuccaC , thanks for contacting Microsoft! Sorry, it looks like your feedback is blank - did you need help with something?

**Comment by julieMSFT** [comment]
Hi @zzLuccaC I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!

**Comment by julieMSFT** [comment]
Hi @LuccaC I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!
