### ISSUE TITLE
Issue in "Create the SQL Server login and permissions for Pacemaker"

### ISSUE THREAD

**Issue by SepehrCloud** [MicrosoftDocs/sql-docs#1920]
There is a syntax error in following page:

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-create-availability-group?view=sql-server-2017

Under section of "Create the SQL Server login and permissions for Pacemaker", the code snippet is showing:

CREATE LOGIN PMLogin WITH PASSWORD '<StrongPassword>';

The above syntax is wrong and there should be a '=' after PASSWORD:

CREATE LOGIN PMLogin WITH PASSWORD='<StrongPassword>';

Also in following steps it's instructing to use emacs editor. This is confusing, it would be a lot better to simply specify a file has to be created in /var/opt/mssql/secrets/passwd with the specified content.

**Comment by julieMSFT** [comment]
Hi @SepehrCloud, thank you for bringing this to our attention,. I have made the edit to the typo. I have asked to author to review your coment about using the emacs editor but you can actually add the change yourself! You can find more information here at [http://aka.ms/editsqldocs.](url) Thanks for helping to improve our documentation :)

**Comment by julieMSFT** [comment]
PR #9835

**Comment by SepehrCloud** [comment]
Thanks Julie, didn't know I can directly contribute. Will do it going forward :)
