### ISSUE TITLE
SQL Data Warehouse Does Not Support FORMAT Function

### ISSUE THREAD

**Issue by temalo** [MicrosoftDocs/sql-docs#1922]
The FORMAT Function (docs/t-sql/functions/format-transact-sql.md) is not currently supported by SQL Data Warehouse (neither Gen1 nor Gen2) so the "Applies To" section for this doc should be updated.
![FormatFunctionResultsDW](https://user-images.githubusercontent.com/10897895/56047881-407d2200-5cfb-11e9-8a93-065dd9a03105.GIF)

**Comment by julieMSFT** [comment]
Hi @temalo, thanks for bringing this to our attention! Let me look into this a bit further. Thanks!

**Comment by julieMSFT** [comment]
@Anumjs @TwoUnder  Hi, please review this issue. I have validated that fromat errors on Gen1.

**Comment by temalo** [comment]
Just to let you know, it also errors on Gen2, the output that I posted was from my Gen2 instance of SQLDW..

**Comment by julieMSFT** [comment]
Hi @temalo, thank you again for bringing this to our attention! I have verified that FORMAT is not supported in SQL DW. I have updated the documents to reflect this. I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!

**Comment by julieMSFT** [comment]
PR #9886
