### ISSUE TITLE
Transaction participation not documented

### ISSUE THREAD

**Issue by MartinLBuchanan** [MicrosoftDocs/sql-docs#1923]
Saw no description of whether CREATE LOGIN participates in transactions. If executed within a transaction and the transaction is rolled back, is the new login creation rolled back as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0f4b3be-5686-ac31-8c5d-676e08953d8f
* Version Independent ID: 43881484-714e-d528-7a38-72d24a2d40d1
* Content: [CREATE LOGIN (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-login-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-login-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-login-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by julieMSFT** [comment]
Hi @MartinLBuchanan, Thank you for your question. You can test this functinality for yourself by executing CREATE LOGIN in a transaction. Create Login will rollback if executed within a transaction and the transaction is rolled back.

Please let me know if you need anything further, or if I can proceed with closing out this Git Issue. Thanks!

**Comment by MartinLBuchanan** [comment]
Dear Julie:

Thanks for the quick response, which helps me with code I'm writing.

The issue should remain open until the documentation is fixed; just checked
the page and it still does not explain what you explained in your email.

(I was a senior technical writer for 15 years at Intel, so you may see more
documentation comments from me in the future.)

Sincerely,

Martin

**Comment by julieMSFT** [comment]
Hi @MartinLBuchanan, your input would be appreciated. You can actually add the change yourself! You can find more information here at [http://aka.ms/editsqldocs](url). Thanks for helping to improve our documentation :)

**Comment by julieMSFT** [comment]
Hi @MartinLBuchanan, thank you again for your input to our documentation. The vast majority of T-SQL commands are supported in transactions. The few that are not supported are documented in the individual T-SQL commands. We take the position that you should assume that it works within the scope of a transaction unless it is otherwise called out in the documentation. I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!
