### ISSUE TITLE
SSBDiagnose.exe not installing from DVD

### ISSUE THREAD

**Issue by gwalters69** [MicrosoftDocs/sql-docs#1926]
I cannot find SSBDiagnose.exe if I install SQL 2017 from a DVD mounted to a windows machine.  It exists on my Azure prebuilt SQL 2017 on Windows 2016 VM. Why is this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36bdcdc6-7a7e-ad82-66d4-61c78d06930a
* Version Independent ID: 5960e869-0a36-b277-4802-a86e4b02365f
* Content: [ssbdiagnose Utility (Service Broker) - SQL Server](https://docs.microsoft.com/en-us/sql/tools/ssbdiagnose/ssbdiagnose-utility-service-broker?view=sql-server-2017#feedback)
* Content Source: [docs/tools/ssbdiagnose/ssbdiagnose-utility-service-broker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/ssbdiagnose/ssbdiagnose-utility-service-broker.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@stevestein Hi Steve, can you please process this Issue 1926, about 'SSBDiagnose.exe'.  Thanks.
CC: @gwalters69

**Comment by MightyPen** [comment]
(DevO= https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1512150.)

**Comment by stevestein** [comment]
@gwalters69 - Thanks for raising this, the same issue is being tracked in [issue 1896](https://github.com/MicrosoftDocs/sql-docs/issues/1896) so I'm going to close this one.

We're working on getting the information to get the current version of ssbdiagnose and will update the article when the details are available. 

Thanks
