### ISSUE TITLE
typo in sidebar title

### ISSUE THREAD

**Issue by awilbert** [MicrosoftDocs/sql-docs#1929]
The title of this page in the left sidebar has the word "Objects" capitalized as "OBjects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa0615c-d590-69b6-debb-817cd2cef3ac
* Version Independent ID: ecdbbeba-38e1-45af-917f-ae156cd65c1f
* Content: [BLOBs and OLE Objects - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-ole-db-blobs/blobs-and-ole-objects?view=sql-server-ver15)
* Content Source: [docs/relational-databases/native-client-ole-db-blobs/blobs-and-ole-objects.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/native-client-ole-db-blobs/blobs-and-ole-objects.md)
* Product: **sql**
* Technology: **native-client**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
@awilbert Hi Adam, Thanks for bringing this problem to our attention.
Fixed it today (live late Monday). So now Closing this Issue 1929.
Correction, in 'docs/toc/toc.yml', now looks like the following, from private repo PR **9842**:

```
    - name: BLOBs & OLE Objects
      href: ../relational-databases/native-client-ole-db-blobs/blobs-and-ole-objects.md
      items:
```
