### ISSUE TITLE
Applies To section incorrect

### ISSUE THREAD

**Issue by krumpff** [MicrosoftDocs/sql-docs#1930]
This incorrectly states that Checkpoint does not apply to Azure SQL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c301c878-854d-e9e5-9efa-db78bc5b31d4
* Version Independent ID: bcf4f8cb-8351-7561-8170-22555109829e
* Content: [CHECKPOINT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/checkpoint-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/language-elements/checkpoint-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/checkpoint-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by MightyPen** [comment]
@julieMSFT Hi Julie, Can you please process this Issue 1930.

'AppliesTo' changes would likely also mean changes to metadata field 'monikerRange'.

Also, where Azure SQL Database should be added to AppliesTo (and thus probably also to monikerRange), the changes will often be needed for Azure SQL DB **MI**.  (Carl might have thoughts here.  Maybe we need to keep instances of each handier on a daily bases, for quickie tests?)

CC: @krumpff

**Comment by julieMSFT** [comment]
Hi @ krumpff, thanks for bringing this to our attention! I have made the change to the document and you should see it soon. I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!

**Comment by julieMSFT** [comment]
PR #9846
