### ISSUE TITLE
Alternative for -f option of SQLCMD in LINUX to support unicode characters insertion

### ISSUE THREAD

**Issue by pssoma76** [MicrosoftDocs/sql-docs#1932]
Hi,

My customer is looking for -f option to use in SQLCMD, to support insertion of Unicode characters. For example, customer is looking to insert Unicode values like N'¥' into a table. By using -f 65001 in windows environment, SQLCMD works fine to insert the row into a table with Unicode character. Whereas -f option is not available in LINUX environment, we are looking for an alternate solution for LINUX environment.

Thanks & Regards,
Somayajulu

**Comment by rothja** [comment]
@pssoma76 Thank you for the question. Please let me contact the product team and investigate what options we might have here. I wonder if the [mssql-cli command line tool](https://docs.microsoft.com/en-us/sql/tools/mssql-cli?view=sql-server-2017) offers any support for unicode characters. Also, is this a GUI Linux environment, because Azure Data Studio is cross platform as is the mssql extension in VS Code. Thanks!

**Comment by pssoma76** [comment]
> @pssoma76 Thank you for the question. Please let me contact the product team and investigate what options we might have here. I wonder if the mssql-cli command line tool offers any support for unicode characters. Also, is this a GUI Linux environment, because Azure Data Studio is cross platform as is the mssql extension in VS Code. Thanks!

@rothja Thank you Rothja for the quick response. Customer is having large set of .SQL files with insert statements. So, using SQLCMD utility, they want to execute these statements. And the insert statements have Unicode characters in it. Customer is trying to execute set of .SQL files using batch command.

**Comment by rothja** [comment]
@pssoma76 I apologize for the long delay. I have contacted our product team to let them know that the -f command is not available/working in Linux. I don't have a good solution now as the product does not support this at this time. I would encourage you to submit feedback on sqlcmd here: [UserVoice - Suggestion to improve SQL Server](https://feedback.azure.com/forums/908035-sql-server). If you were able to find an alternative solution to run the scripts, let me know. I apologize for both the delay and for not having a good solution for you. Let me know if you have any questions. Thank you!
