### ISSUE TITLE
Include BigInt

### ISSUE THREAD

**Issue by dtcgrabar** [MicrosoftDocs/sql-docs#1934]
Why is BigInt excluded from the list of valid bitwise operands? It appears to work...

DECLARE	@t BIGINT,
@f BIGINT

SELECT	@t = POWER(2.0, 40),
@f = POWER(2.0, 38) + POWER(2.0, 40)

SELECT	@t AS t,
@f AS f,
@t & @f AS [And],
@t | @f AS [Or],
@t ^ @f AS [Xor],
CAST(POWER(2.0, 38) AS BIGINT) AS [2^38]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b730b2bb-57ee-aba8-247f-0fa63114c88b
* Version Independent ID: 36fd9a35-e182-a272-a9f4-f2da1eec7d17
* Content: [Bitwise Operators (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/bitwise-operators-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/language-elements/bitwise-operators-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/bitwise-operators-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by rothja** [comment]
@dtcgrabar Thanks for this excellent question. After doing a little research, it looks like you are right and that BIGINT should be in the list of supported integer types that this works on. I will edit the article before closing this git issue. Thanks, again.

**Comment by rothja** [comment]
@dtcgrabar I'm fixing this today. Sorry for the delay!
