### ISSUE TITLE
Link failing

### ISSUE THREAD

**Issue by ghauan** [MicrosoftDocs/sql-docs#1936]
The link behind "Server Configuration - Collation" does not lead to a valid page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca70403-237f-0160-7d1f-5817e40b5d25
* Version Independent ID: 9993116a-bcec-e054-1cbe-82c3ad603ef6
* Content: [Set or Change the Server Collation - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-server-collation?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/collations/set-or-change-the-server-collation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/set-or-change-the-server-collation.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by rothja** [comment]
@ghauan Thank you. I am fixing this link. That page no longer exists except in the 2014 documentation, but the link should really go to the [top-level collation article](https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-2017). I'm making that change and will close this issue when it is merged in. Thanks!
