### ISSUE TITLE
Option 1 - You control output with FOR JSON PATH

### ISSUE THREAD

**Issue by avinashre** [MicrosoftDocs/sql-docs#1938]
"Item.Price"  instead  "Item.UnitPrice" to match the json mentioned in the image. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb5c17b-c567-303f-00b8-0c8a0ad15fb5
* Version Independent ID: a4ccc766-4a61-5b7a-e5dd-692e3cebb503
* Content: [Format Query Results as JSON with FOR JSON (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md)
* Product: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by MightyPen** [comment]
@avinashre Hello Avinash, Good catch. For this type of small very well defined and understood error, we encourage customers like yourself to please fix these.
Click the "Edit"-pencil icon at the top-right of the Docs article, and then in GitHub click its pencil icon.  Edit the correction, and then click to create a Pull Request (PR), mentioning "Issue 1938" in the PR description.
Once you know how to do this, you can complete this in less than 3 minutes.  Internally, I have a more laborious process.  And we are perpetually swamped with more work than we can ever get all done.

Then myself or a teammate will approve your Pull Request.

- _**Would you be willing to try implementing the fix that is described by you in this Issue 1938?  Please reply with an @ notification to me so I know either way.**_

We can then know how to finalized this Issue 1938.
Thanks a lot.

**Comment by MightyPen** [comment]
I fixed this, with private repo PR 9922.
https://github.com/MicrosoftDocs/sql-docs-pr/pull/9922 

Closing this now.
@avinashre Thank you for bring this error to our attention.  We hope to hear from you again.
