### ISSUE TITLE
Feels like this example would be clearer with a datetime argument instead of datetimeoffset

### ISSUE THREAD

**Issue by jg11jg** [MicrosoftDocs/sql-docs#1941]
DECLARE @dateTime datetimeoffset(7)= '2007-08-28 18:00:30';  
SELECT TODATETIMEOFFSET (@dateTime, '+13:00');  
-- RETURNS 2007-08-28 18:00:30.0000000 +13:00  

--bit confusing - why declare @dateTime as datetimeoffset?  It will get implicitly cast to DateTime2 before being passed to DateTime offset and just specifying it as DateTime2 from the start saves reader having to do any reasoning or wondering about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e482e62-38f6-06e4-f0ed-2c0c5fdef903
* Version Independent ID: 4bfc388b-2e23-fa9d-16dd-c9e52f7a15d4
* Content: [TODATETIMEOFFSET (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/todatetimeoffset-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/todatetimeoffset-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/todatetimeoffset-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @jg11jg , thanks for bringing this to our attention! Let me look into this and get back to you. Thanks!

**Comment by MashaMSFT** [comment]
Hi @jg11jg , thanks again for contacting Microsoft! I've updated the examples to eliminate the declaration all together. These changes should be live tomorrow. I hope that helps and please let me know if we could be of further assistance. Thanks!

**Comment by MightyPen** [comment]
@MashaMSFT Hi Masha, I am now Closing this Fixed Issue 1941.  Thanks.
