### ISSUE TITLE
Broken Links on the page

### ISSUE THREAD

**Issue by vCillusion** [MicrosoftDocs/sql-docs#1944]
Important section the link to Extended Protection for Authentication is broken. [https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/extended-protection-for-authentication-overview](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/extended-protection-for-authentication-overview)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fbb99b-b42b-0558-7270-e9a3c8b34828
* Version Independent ID: 30f9a223-3dc9-9e21-0f1a-5238f0b939d0
* Content: [Connect to the Database Engine Using Extended Protection - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/connect-to-the-database-engine-using-extended-protection?view=sql-server-2017)
* Content Source: [docs/database-engine/configure-windows/connect-to-the-database-engine-using-extended-protection.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/connect-to-the-database-engine-using-extended-protection.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rothja** [comment]
@vCillusion Thank you for this feedback. The author @MikeRayMSFT has been notified and will get back to you shortly. If you know the what the broken link should be, you can also edit the article directly with the Edit button. Let me know if you have any questions about that. Thank you!

**Comment by MikeRayMSFT** [comment]
@vCillusion - thanks for pointing this out. I will replace the broken link with https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/extended-protection-for-authentication-overview

Let us know if that's not what you intended. 
Thank you.
