### ISSUE TITLE
Missing documentation of column last_used_value

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/sql-docs#1945]
In SQL Server 2017, a new column last_used_value was added to the view

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cbc8307-23ed-9ef7-eed9-b5fc63f95a86
* Version Independent ID: d6a2dfa9-349b-39fc-50a3-a49280c82c6c
* Content: [sys.sequences (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-sequences-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-catalog-views/sys-sequences-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-sequences-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by rothja** [comment]
@KennieNP Thank you for the feedback. The author, @stevestein, has been notified. You can also make the change directly if you wish by clicking the edit button on the article. If you have any questions, let me know. Thank you!

**Comment by stevestein** [comment]
@KennieNP - Thanks for raising this issue. It'll be fixed soon in the documentation. 

We have created a new internal tracking number for this work item: _1528619_. We are closing this Issue, and letting the new item track this going forward. You will receive another notice after the internal item is completed. 

Thanks again for submitting this issue!
