### ISSUE TITLE
RDBMS security section

### ISSUE THREAD

**Issue by jimstjohn** [MicrosoftDocs/sql-docs#1949]
This page indicates that Transparent database encryption is not available for SQL Server 2017 standard.  I thought that TDE has been available in SQL Server Standard since SQL 2016 SP1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 453dc1e2-0c9c-fe95-c6fc-90be886432ad
* Version Independent ID: cd472bc0-26b9-a4a6-4089-31b79be787cb
* Content: [Editions and supported features of SQL Server 2017 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2017?view=sql-server-2017#feedback)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-2017.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-2017.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rothja** [comment]
@jimstjohn Thanks for the question. We'll want to fix the doc if the support statement is wrong. I've assigned this to @MikeRayMSFT, and he'll look into this further.

**Comment by MikeRayMSFT** [comment]
@jimstjohn - thank you for the question. We're verifying.

**Comment by pmasl** [comment]
See https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2017?view=sql-server-2017 

Only features that affect the programmability surface area were opened to Standard Edition in SQL Server 2016 SP1 and above. TDE is not a programmability feature.

What affects the programmability surface area? Think of it this way. Your application T-SQL code and application behavior should be consistent across editions. TDE has no bearing on application code portability.
