### ISSUE TITLE
New article not registered after adding it to the publication

### ISSUE THREAD

**Issue by raberana** [MicrosoftDocs/sql-docs#1952]
If sp_helpsubscription doesn't list down the newly added article, run sp_refreshsubscriptions '&lt;publication name&gt;' to update it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc92bf43-e386-8151-3fdd-179220b5e632
* Version Independent ID: 5d295335-ed3c-b316-4dee-503ee9a92372
* Content: [Add Articles to and Drop Articles from Existing Publications - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/publish/add-articles-to-and-drop-articles-from-existing-publications?view=sql-server-2017)
* Content Source: [docs/relational-databases/replication/publish/add-articles-to-and-drop-articles-from-existing-publications.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/publish/add-articles-to-and-drop-articles-from-existing-publications.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by rothja** [comment]
@raberana Thank you for contacting us with this issue. Can you give me a few more details about the problem. Is the article inaccurate or are you not getting the results you expect? Thank you!

**Comment by rothja** [comment]
@raberana Thanks, again, for contacting us. I'm not sure I have enough information to work on this git issue. Can you provide a few more details? Thank you!

**Comment by rothja** [comment]
@raberana I haven't heard back from you on this git issue, so I am going to temporarily close the issue. But if you want to reopen, please contact me at any time, and I'll work to understand the doc updates that might need to be made. Thank you!!
