### ISSUE TITLE
Incorrect "TOPIC APPLIES TO"

### ISSUE THREAD

**Issue by jonsparkes** [MicrosoftDocs/sql-docs#1953]
The page header states that this management view only applies to SQL Server 2019, however I can confirm this is available in Azure SQL database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b62b4fea-b265-13d8-8e2c-1a6f63bd158d
* Version Independent ID: c7509d53-0d38-37b9-8239-53d09e70bdd1
* Content: [sys.dm_exec_query_plan_stats (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-query-plan-stats-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-exec-query-plan-stats-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-query-plan-stats-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by rothja** [comment]
@jonsparkes Thank you for bringing this to our attention. I'm going to have one of our SQL Database content owners, @CarlRabeler, look into this.

**Comment by CarlRabeler** [comment]
@MikeRayMSFT please look into this comment for your article

**Comment by MikeRayMSFT** [comment]
@pmasl - can we verify this applies to both Azure SQL DB and Azure SQL DB Managed Instance?

**Comment by MikeRayMSFT** [comment]
Fixed
