### ISSUE TITLE
/var/opt/mssql/log directory cannot be removed

### ISSUE THREAD

**Issue by mco100** [MicrosoftDocs/sql-docs#1955]
Hi,

I ran the command "sudo /opt/mssql/bin/mssql-conf set filelocation.errorlogfile" and all errorlog, xe and trace files were successfully moved to another directory.

**But** directory /var/opt/mssql/log is recreated automatically every time SQL Server service is restarted with 2 logs in it:
- sqlagent.out
- sqlagentstartup.log

How to move above two logs to the same directory as errorlog ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c0b1027-3982-e114-0230-c6bd9bd81346
* Version Independent ID: 244740de-8817-1671-387d-970f8ee8dfcb
* Content: [Configure SQL Server settings on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-configure-mssql-conf.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-mssql-conf.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@mco100 I can see how that's not a comprehensive solution if it doesn't move all the SQL related logs. I have contacted the product team to see if this is intentional or if we need to consider a future change in behavior that takes the agent logs into account. Thank you!

**Comment by rothja** [comment]
@mco100 I've reported this issue to the product team. At this time, I do not have any work around for you for moving the sql server agent logs. I am sorry for the experience, and I hope we can address this in the future. I am going to close the git issue, but feel free to respond at any time with more information or questions. Thank you!
