### ISSUE TITLE
AlwaysEncrypted CMK stores using SHA1 or SHA256 for signing ?

### ISSUE THREAD

**Issue by Guillaume-Fourrat** [MicrosoftDocs/sql-docs#1957]
Current content 

> "All Microsoft CMK store providers encrypt CEKs by using RSA with Optimal Asymmetric Encryption Padding (RSA-OAEP) with the default parameters specified by RFC 8017 in Section A.2.1. Those default parameters are using a hash function of SHA-1 and a mask generation function of MGF1 with SHA-1."

RFC 8017 indeed has a _default_ of SHA-1, but it doesn't look like this is what we're using :

https://referencesource.microsoft.com/#System.Data/fx/src/data/System/Data/SqlClient/SqlColumnEncryptionCertificateStoreProvider.cs,62

`       /// <summary>
        /// Hashig algoirthm used for signing
        /// </summary>
        private const string _hashingAlgorithm = @"SHA256";`

https://referencesource.microsoft.com/#System.Data/fx/src/data/System/Data/SqlClient/SqlColumnEncryptionCertificateStoreProvider.cs,217
`           // Compute hash
            // SHA-2-256(version + keyPathLength + ciphertextLength + keyPath + ciphertext) 
            byte[] hash;
            using (SHA256Cng sha256 = new SHA256Cng())`

https://referencesource.microsoft.com/#System.Data/fx/src/data/System/Data/SqlClient/SqlColumnEncryptionCertificateStoreProvider.cs,579

`            //Set the hash algorithm to SHA256.
            rsaDeFormatter.SetHashAlgorithm(_hashingAlgorithm);`

=>Suggest checking if updating documentation to ".. are using a hash function of **SHA-2-256**" is valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f41e2f97-cfcf-3c42-307d-50a8595fd46a
* Version Independent ID: 81481319-c0de-367f-8822-e397d31f530b
* Content: [Always Encrypted Cryptography - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-cryptography?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/encryption/always-encrypted-cryptography.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/always-encrypted-cryptography.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @aliceku
* Microsoft Alias: **aliceku**

**Comment by aliceku** [comment]
@Guillaume-Fourrat thank you for your feedback.  I am adding @Jaszymas who is the AE feature PM for comment.

**Comment by MightyPen** [comment]
@VanMSFT @jaszymas 
Hi Van, Can you and Jakub Szymaszek please process this security Issue 1957, and eventually respond to @Guillaume-Fourrat .  Thanks a lot.

**Comment by VanMSFT** [comment]
Following up with @jaszymas

**Comment by VanMSFT** [comment]
Checking in with @jaszymas

**Comment by WilliamAntonRohm** [comment]
https://dev.azure.com/ceapex/Engineering/_workitems/edit/98938

Closing this issue #1957 as it is older than a month, and tracking it with the above work item.

@VanMSFT @jaszymas @Guillaume-Fourrat @aliceku

**Comment by jaszymas** [comment]
We have updated the docs (the last paragraph in this section: https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-cryptography?view=sqlallproducts-allversions#keys-key-stores-and-key-encryption-algorithms) to address this issue.
