### ISSUE TITLE
Logical funcitons link redirecting to same page

### ISSUE THREAD

**Issue by BenBitDesign** [MicrosoftDocs/sql-docs#1966]
"The logical functions" link in the table on this page is redirecting to this page ("What are the SQL database functions?").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fccc2683-09df-68d6-1bd0-84ba07e23782
* Version Independent ID: f96ce66e-089b-d5d2-62a3-047463f55057
* Content: [What are the Microsoft SQL database functions? - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/functions?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/functions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/functions.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by rothja** [comment]
@BenBitDesign Thanks for the feedback. I've assigned this to the author @MashaMSFT, and we will see if the link should be changed (and where). Thanks!

**Comment by MashaMSFT** [comment]
Hi @BenBitDesign , thanks for bringing this to our attention! I've fixed it temporarily by redirecting the link to the CHOOSE function but I have a work item to create a new article to improve this navigation.

**Comment by MashaMSFT** [comment]
Hi @BenBitDesign , thanks again for bringing this to our attention! This issue has now been addressed. Please let us know if we can be of further assistance :) otherwise, we'll proceed with closing out this Git Issue in a few business days. Thanks!

**Comment by BenBitDesign** [comment]
Thank you for the update!

Ben
