### ISSUE TITLE
Incorrect values for sysdac_history_internal.action_status column

### ISSUE THREAD

**Issue by lpatalas** [MicrosoftDocs/sql-docs#1967]
Docs specify following values:

0 = pending
1 = success
2 = fail

On LocalDB 13.1.4001.0 I actually get:

1 = pending
2 = success

![action_status](https://user-images.githubusercontent.com/1406063/56473548-03d4c780-646d-11e9-8aec-5c0deab1a010.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5502f8dc-33e1-6ae4-096b-5a3732d7f5d1
* Version Independent ID: a9d3c3ce-3561-67b3-b01e-a4b9b977191f
* Content: [sysdac_history_internal (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/data-tier-application-tables-sysdac-history-internal?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-tables/data-tier-application-tables-sysdac-history-internal.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/data-tier-application-tables-sysdac-history-internal.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@stevestein Hi Steve, Can you please process this Issue 1967.  Thanks.

CC: @lpatalas

**Comment by stevestein** [comment]
@lpatalas - Thank you for bringing up this issue! We will evaluate adding gMSA documentation, and will track this in our ticketing system: User Story 1530185. Since we're now tracking this internally, I'll proceed with closing out this Issue. However, please feel free to contact us if you have any additional information. Thanks again!
