### ISSUE TITLE
Can't download SQL Server Management studio successfully

### ISSUE THREAD

**Issue by nobieyi00** [MicrosoftDocs/sql-docs#1969]
Hi
When I download the software gets to 99% and an error occurs then I resume it and the error occurs again. I have tried several times across various laptops and internet browsers. Please look into it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by MashaMSFT** [comment]
Hi @nobieyi00 thank you for contacting Microsoft! I'm sorry to hear you're running into issues downloading SSMS. Would you mind clarifying which link you're selecting? Is it the current  17.9.1 new installation, the 17.9.1 upgrade, or something else? Thanks!

**Comment by nobieyi00** [comment]
Hi it is the 17.9.1

**Comment by MashaMSFT** [comment]
Hi @nobieyi00 , I tried to download both the [new ](https://go.microsoft.com/fwlink/?linkid=2043154 )installation, and the [upgrade](https://go.microsoft.com/fwlink/?linkid=2043430), and both links succeeded for me: 
![image](https://user-images.githubusercontent.com/32783170/56519431-e8160380-64f6-11e9-96b3-49b43dbeceb2.png)

Is it possible that there are some security settings on your end that are preventing downloads? 

Thanks!

**Comment by nobieyi00** [comment]
Hi I will try through a different network once I get home. However, I am currently still experiencing the same issue. It is actually running a loop. It gets to the end and restarts downloading. I have downloaded from other microsoft websites for example I downloaded visual studio few hours ago without any issue. Once I try through my home network I will update the ticket

**Comment by nobieyi00** [comment]
Hi I tried my local machine at home and it worked. Probably my work laptop has some network issue. I will close the issue. thanks
