### ISSUE TITLE
Is NaN value supported?

### ISSUE THREAD

**Issue by abelykh0** [MicrosoftDocs/sql-docs#1971]
The documentation page for float and real data types doesn't specify if NaN value is supported or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2de23d-86a7-de68-8755-1811be30348f
* Version Independent ID: 4b3b64d3-9857-89e9-1128-5fa35caa686b
* Content: [float and real (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/float-and-real-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/data-types/float-and-real-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/float-and-real-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
@pmasl - can you answer the question?

**Comment by pmasl** [comment]
NaN is not supported in T-SQL. If you want to test for whether a value is numeric or not, use the function IsNumeric.
