### ISSUE TITLE
An example showing how to configure Polybase using Azure Data Lake Gen2 is needed

### ISSUE THREAD

**Issue by mprince-capax** [MicrosoftDocs/sql-docs#1973]
The example above is for ADLS Gen1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140d7c84-acc3-f722-99af-867be1f8752a
* Version Independent ID: 6bb40855-9644-1b18-3c4f-cec734cdc169
* Content: [CREATE DATABASE SCOPED CREDENTIAL (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-scoped-credential-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-database-scoped-credential-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-database-scoped-credential-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
@rothja - Hey Jason, do you mind checking this out? Thanks!

**Comment by rothja** [comment]
@mprince-capax Thank you for this question. I apologize for the delay as I was out of the office last week. I will look into this further and get back to you. Thank you!

**Comment by rothja** [comment]
@mprince-capax I checked with the product team, and currently we do not support Azure Data Lake Gen2 with PolyBase. It is possible in SQL Server 2019 big data clusters to use HDFS tiering for this type of connection though. However, we probably need to put a statement in the article to this affect. I'm going to leave this open until I add this to the article. Thank you for the question and sorry that I can't help more.

**Comment by rothja** [comment]
@mprince-capax A writer on my team is making some updates to this article, and I asked him to put the support statement in about Gen2. Sorry, again, that I don't have a better answer at this time. Thanks!
