### ISSUE TITLE
Minimal logging requirements for CCI inserts

### ISSUE THREAD

**Issue by simonsabin** [MicrosoftDocs/sql-docs#1979]
There is nothing I can find that explicitly states that batch inserts > 102400 into a CCI is minimally logged irrespective of the recovery model of the database.

Can that be put in the docs somewhere 

This doesn’t call it out either way
https://docs.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-data-loading-guidance?view=sql-server-2017#plan-bulk-load-sizes-to-minimize-delta-rowgroups

and this implies that it requires simple of bulk logged recovery. I expect because CCI was added to the page
https://docs.microsoft.com/en-us/sql/relational-databases/import-export/prerequisites-for-minimal-logging-in-bulk-import?view=sql-server-2017 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2c8c53-6371-b844-3b7b-8e93b8601683
* Version Independent ID: a5a62a2f-e91c-d2bd-e489-a612ea049b1a
* Content: [Prerequisites for Minimal Logging in Bulk Import - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/prerequisites-for-minimal-logging-in-bulk-import?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/import-export/prerequisites-for-minimal-logging-in-bulk-import.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/prerequisites-for-minimal-logging-in-bulk-import.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by MashaMSFT** [comment]
Hi @simonsabin , thanks for contacting Microsoft! Let me do some research and get back to you. Thanks!

**Comment by MashaMSFT** [comment]
Hi @simonsabin , thanks again for reaching out! I found this paragraph in the second document you linked - is this what you're referring to?

If the table has a clustered index and is empty, both data and index pages are minimally logged. In contrast, if a table has a btree based clustered index and is non-empty, data pages and index pages are both fully logged regardless of the recovery model. **For tables with clustered columnstore index, the dataload into compressed rowgroup is always minimally logged independent of the table being empty or not when batchsize >= 102400.**

thanks!

**Comment by simonsabin** [comment]
Not really because the top of the page explicitly says

"For a database under the full recovery model, all row-insert operations that are performed by bulk import are fully logged in the transaction log. "

Historically all those requirements for minimal logging are in addition to the DB being in simple or bulk logged recovery.

Its just not explicit enough

**Comment by MashaMSFT** [comment]
Hi @simonsabin , thanks for your patience while I looked into this a bit further. You're right, there are some conditions for minimally logged operations to happen with inserts into CCI. The recovery model of the database overrides these conditions ultimately. So the database has to be SIMPLE | BULK_LOGGED to get minimally logged operations even with CCI. We're working on updating the documentation to make this a bit more clear. Just wanted to give you an update :) I'll reach out once more once the change are live. Thanks!

**Comment by simonsabin** [comment]
Hi masha

That’s not the case, not based on my testing anyway. You don’t need simple or bulk logged to get minimal logging for CCIs. That’s why it’s suggested for managed instance and sq database

Simon Sabin
Director Engineering Sabin.io
Founder SQLBits
Microsoft Regional Director & MVP

________________________________

**Comment by MashaMSFT** [comment]
Hi @simonsabin , thanks for your patience as I continue looking into this for you! It's interesting that your testing is counter to the internal feedback I received. Would you mind if I contact you directly via email to find out more information about your testing? 
Thanks!

**Comment by simonsabin** [comment]
Sure

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MightyPen** [comment]
@MashaMSFT We can leave this aging Issue 1979 open a while longer, because it is still actively being studied.  Hopefully you can receive the info that is needed to update the documentation and then close this aging issue.
Thanks.

**Comment by MightyPen** [comment]
https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1568010

@MashaMSFT Hi Masha, I have created work item 1568010 to track the unresolved status of this aging Issue 1979.

I am now closing this Issue.  See 1568010.

**Comment by MightyPen** [comment]
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1565276

..... is the AzBoards item 1565276 that is actually address this Issue 1979.  This belated link is crucial to our Audit Trail functionality.

**Comment by MashaMSFT** [comment]
Hi @simonsabin, thanks again for your suggestions, and for your patience as we updated the docs. We've removed some things, and added clarity around the difference between minimal logging, and reduced logging. 

Would you mind reviewing the following two articles to confirm if your concern has been addressed? 
https://docs.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-data-loading-guidance?view=sql-server-2017
https://docs.microsoft.com/en-us/sql/relational-databases/import-export/prerequisites-for-minimal-logging-in-bulk-import?view=sql-server-2017

Thanks again!
Masha from the SQL Docs team
