### ISSUE TITLE
Limitations on Filegroups on SQL Express

### ISSUE THREAD

**Issue by JasonLoKiSmith** [MicrosoftDocs/sql-docs#1980]
Can I kindly request that more information is added to this article with regards to the possible limitations there are when using SQL Express, specifically when it comes to the 10Gb limit. Do FILESTREAMS form part of the 10Gb data limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bd7807f-5dde-795d-56b9-3d4b9c4187cb
* Version Independent ID: 61ca2613-e6fe-b3c2-e4d4-fbf264bbc20d
* Content: [FILESTREAM (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/blob/filestream-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/blob/filestream-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/blob/filestream-sql-server.md)
* Product: **sql**
* Technology: **filestream**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by MashaMSFT** [comment]
Hi @JasonLoKiSmith , thanks for bringing this to our attention! Let me do some research and get back to you. Thanks!

**Comment by MashaMSFT** [comment]
Hi @JasonLoKiSmith , thanks again for contacting Microsoft! It looks like the 10gb limitation does NOT include filestream: https://docs.microsoft.com/en-us/sql/relational-databases/blob/filestream-compatibility-with-other-sql-server-features?view=sql-server-2017#SQLServerExpress

I hope that helps and please let me know if we could be of further assistance. Thanks!

**Comment by MashaMSFT** [comment]
Hi @JasonLoKiSmith , thanks again for reaching out! As it's been some time since we've heard from you, we'll assume the information provided was sufficient, and proceed with closing out this Git Issue. Please feel free to reply should you need anything further. Thanks!

**Comment by JasonLoKiSmith** [comment]
Hi guys,

Yes you can close this, thank you so much for your assistance!

Regards
Jason
