### ISSUE TITLE
Limitations - are there more?

### ISSUE THREAD

**Issue by GilesDMiddleton** [MicrosoftDocs/sql-docs#1982]
I know from bitter experience that you can't have more than 128 deep nested levels of XML elements. Can this be added to the limitations. Are there more limitations that could be added to the limitation section? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b80f2a-c27b-b55e-1c72-2a976cd18bff
* Version Independent ID: 81c2a3df-6055-d504-2580-a80cccf8bb50
* Content: [XML Data Type and Columns (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/xml/xml-data-type-and-columns-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/xml/xml-data-type-and-columns-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/xml/xml-data-type-and-columns-sql-server.md)
* Product: **sql**
* Technology: **xml**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MashaMSFT** [comment]
Hi @GilesDMiddleton , thanks for contacting Microsoft! I've assigned this issue to the author to research further. Thanks!

**Comment by MightyPen** [comment]
Fix is in PR #10263, in the sister private repo.
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10263

**Comment by MightyPen** [comment]
@GilesDMiddleton Hello Giles, The fix should be live before Monday 2019/May/20.  It is an added bullet to the Limitations list.

Thank you very much for bringing this to our attention.
(I am now Closing this Issue 1982. However, the @ notification mechanism continues to function even in Closed Issues.)
