### ISSUE TITLE
Array Example

### ISSUE THREAD

**Issue by shudson302** [MicrosoftDocs/sql-docs#1986]
After doing exhaustive searching, there is a lot of confusion about querying for values in an array.   This page seems to indicate in Example 2 that you can query an array of address info objects by using the jason path '$.info.address.town'

But every other example I have seen of querying for arrays requires you to have an indexer [0] in order to extract a value.  Could you make this example more clear by actually putting the value for @jsonInfo instead of just having it say &lt;array of address info&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28e8713d-8b6e-7e43-04cc-e2720891b56c
* Version Independent ID: d09b9ed6-4e55-7d18-b17f-88e17839074d
* Content: [JSON_VALUE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-value-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/json-value-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/json-value-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by MashaMSFT** [comment]
Hi @shudson302 , thanks for bringing this to our attention! Let me do a little research and get back to you. Thanks!

**Comment by jovanpop-msft** [comment]
@MashaMSFT the example is wrong. I corrected it here: https://github.com/MicrosoftDocs/sql-docs-pr/pull/10046. I think that we can close this issue once it is published.

**Comment by shudson302** [comment]
When I click on that link, it is a 404 error

**Comment by MashaMSFT** [comment]
Hi @shudson302 , the change has gone live:

DECLARE @jsonInfo NVARCHAR(MAX)
DECLARE @town NVARCHAR(32)

SET @jsonInfo=N'{"info":{"address":[{"town":"Paris"},{"town":"London"}]}';

SET @town=JSON_VALUE(@jsonInfo,'$.info.address[1].town'); -- Paris
SET @town=JSON_VALUE(@jsonInfo,'$.info.address[1].town'); -- London

I hope that helps and please let us know if we could be of further assistance. If we don't hear from you in the next few business days, we'll proceed with closing out this Git Issue. Thanks again for contacting Microsoft and improving our documentation!

**Comment by shudson302** [comment]
Ok, that example does make sense now.  Is there a way to query for all values of town?  

Something like this where it will return all items that match?

SET @jsonInfo=N'{"info":{"address":[{"town":"Paris"},{"town":"London"}]}';

SET @Towns =JSON_VALUE(@jsonInfo,'$.info.address.town'); -- Paris

**Comment by Houuse** [comment]
Hi @shudson302 to retrive an array you should use JSON_QUERY method as stated in the docs above

**Comment by MashaMSFT** [comment]
Hi @shudson302 , please let us know if your question remains unanswered? Otherwise, we'll proceed with closing out this Git Issue in a few business days. Thanks again for contacting Microsoft!
