### ISSUE TITLE
Blob Access using Key Vault

### ISSUE THREAD

**Issue by bbakermmc** [MicrosoftDocs/sql-docs#1987]
Is there away to access the blob storage using creds from the key vault?  If the storage account is configured to auto regen keys using the key vault, we would need to change these creds every time, but if SQL can already see the key vault would make more sense, or can we set it to use an application registered identity/user configured managed identity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b7a6124-86bc-bd57-88c6-7c4334c49cd5
* Version Independent ID: 1598c673-fb85-3cf7-4ff9-8fdc0e384c68
* Content: [Examples of Bulk Access to Data in Azure Blob Storage - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by MashaMSFT** [comment]
Hi @bbakermmc , thanks for contacting Microsoft! Let me do a little research and get back to you :) thanks!

**Comment by MashaMSFT** [comment]
Hi @bbakermmc , thanks again for contacting Microsoft! I apologize for the delay during my research. Unfortunately, Azure Key Vault is not supported today. Please feel free to provide feedback about this directly to the product group: https://aka.ms/sqlfeedback. 

Please let me know if there is anything further we can do to assist you? If not, we will proceed with closing out this Git Issue in a few business days. 

Thanks!
