### ISSUE TITLE
Complete Code Samples Needed.

### ISSUE THREAD

**Issue by dhmorrison** [MicrosoftDocs/sql-docs#1988]
Hi all,

I am providing the following constructive criticism.  I hope you take it in the spirit intended and that you guys get better at this stuff. 

The example is not sufficient for an implementer to fully understand how to specify the command.  You really really really really really, etc. need to get on the stick and provide complete code samples.  Or, in the alternative, give up and publish a link to a 3rd party sample that is complete.  Seriously.  It's a waste of my time to read your documentation.  This document is truly fundamentally useless for busy people.

For example, i need to implement using an IP address.  I ask you, is this sample helpful?  I invite you follow your own guidance and use the following to get the job done:

```
AS TCP (  
  LISTENER_PORT = listenerPort  
  [ [ , ] LISTENER_IP = ALL | ( 4-part-ip ) | ( "ip_address_v6" ) ]   
) 
```
what is "4-part-ip" signifying?  all v4 ips are 4 part ips.  How do we specify the value?  xxx-xxx-xxx-xxx?  xxx.xxx.xxx.xxx? 'xxx-xxx-xxx-xxx'?  'xxx.xxx.xxx.xxx'? So on and so forth. What does **"4-part-ip"** mean??  I'm not trying to solve the _Rubik's Cube,_ just assign an IP address....  This, "4-part-ip", is not an industry standard spec to my knowledge.  How do we implement **"4-part-ip"** properly in TSQL?  Finally does **the one anemic code sample provided** cover this?  Nope.

So it goes...come on man!

Dropping the mike.

Thanks,

David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 185eb0f2-645f-9cbb-38e9-7dded9c94428
* Version Independent ID: b3d729ee-dc03-0daa-dbd1-2ff564f4824c
* Content: [CREATE ENDPOINT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-endpoint-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-endpoint-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-endpoint-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by MashaMSFT** [comment]
Hi @dhmorrison , thank you for contacting Microsoft and your heartfelt feedback! I agree that this description is ambiguous, and I appreciate you bringing this to our attention. Let me see what I can do to resolve it :) Thanks!

**Comment by MashaMSFT** [comment]
Hi @dhmorrison , 
Thanks again for contacting Microsoft!  We've submitted a documentation change based on your suggestion, and it should be live at this point. Please let us know if there is anything more we can do for you? If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a wonderful rest of your day!
