### ISSUE TITLE
Supported Operating systems

### ISSUE THREAD

**Issue by dalekerr** [MicrosoftDocs/sql-docs#1989]
Regarding the required version of Windows 10 / Windows Server 2016, note that version 1607 is 10.0.14393 not 10.0.14939 as is stated on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by MashaMSFT** [comment]
Hi @dalekerr , thanks for contacting Microsoft and bringing this to our attention! @stevestein , would you mind looking into this further please? Thanks!

**Comment by stevestein** [comment]
@dalekerr - thanks for raising this issue!

The article has been updated: [Download SSMS](https://docs.microsoft.com/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#supported-operating-systems-ssms-180-ga)
