### ISSUE TITLE
Supported Operating systems #2

### ISSUE THREAD

**Issue by dalekerr** [MicrosoftDocs/sql-docs#1991]
The only supported client listed on this page is Windows 10 (64-bit). The 18.0 Release Notes however, state: "SSMS is not supported on Windows 8. Windows 10 and Windows Server 2016 require version 1607 (10.0.14393) or later. Due to the new dependency on NetFx 4.7.2, SSMS 18.0 does not install on Windows 8 and older versions of Windows 10 and Windows Server 2016. SSMS setup will block on those systems. Windows 8.1 is still supported."

Thus, can you please be consistent with your reporting of the support for Windows 8.1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by MashaMSFT** [comment]
Hi @dalekerr , thanks for bringing this to our attention as well! @stevestein , would you mind looking into this also? Thanks!

**Comment by AAvella** [comment]
SSMS 18 (all previews, RC1, and the GA) have all been running fine on Windows 7 Pro Build 7601.

**Comment by Munez-A** [comment]
looks great

**Comment by dnethi** [comment]
+@Matteo Taveggia<mailto:matteot@microsoft.com>

Steve

We need to update the supported OS to include Windows 8.1.
Would you mind updating it please?



Thanks,
Dinakar

**Comment by stevestein** [comment]
@dalekerr - Thanks for raising this issue. The download page should now align with the release notes regarding Windows 8.1

Thanks!

**Comment by mohamednazar** [comment]
SSMS 18.0 (GA) installed on Windows 2016, after installed it restarted the machine but SSMS is not opening . Please help!

**Comment by MashaMSFT** [comment]
Hi @mohamednazar , 

Thanks for contacting Microsoft!  From my understanding, the issue you're describing seems to be an issue with the product, is that correct? If so, unfortunately, this form of contact is intended explicitly for reporting issues with the documentation, and not for the product. To get further assistance with your issue, we'd recommend engaging the community, or opening a ticket with Microsoft Support. More information can be found here: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

Our apologies that the SQL Docs team was unable to assist you further with your issue, but we appreciate you reaching out. Please let us know if there's anything more we can do for you.

Thanks!
