### ISSUE TITLE
SSMS v18.0 Execution Plan (Incorrect %)

### ISSUE THREAD

**Issue by normanarmas** [MicrosoftDocs/sql-docs#1995]
![image](https://user-images.githubusercontent.com/17601197/56743220-2d7b4080-6744-11e9-9354-b1f5a7975b8a.png)

**Comment by MashaMSFT** [comment]
Hi @normanarmas , thank you for contacting Microsoft! Unfortunately, this seems to be an issue with the product, and this medium is intended for reporting issues with the documentation. As such, your request is outside the scope of this forum. If you're experiencing a bug, please submit it via UserVoice: https://feedback.azure.com/forums/908035-sql-server, engage the community, or contact Microsoft support for further assistance: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

Sorry about that, please let me know if I can be of any further assistance. Thanks!

**Comment by MashaMSFT** [comment]
Hi @normanarmas , just for clarification - which part is incorrect? Thanks!

**Comment by normanarmas** [comment]
The numbers in the percentage calculations are incorrect.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MashaMSFT** [comment]
Hi @normanarmas , sorry, which numbers? All of them? Or the 0%? Or the 233%? What gives you the indication that they're incorrect? Thanks!

**Comment by normanarmas** [comment]
The sum of the all numbers need to be 100

________________________________

**Comment by MashaMSFT** [comment]
Hi @normanarmas , would you mind clarifying further? I see 19+19+19+43 which sums up to 100. Which values are you referring to? Thanks!

**Comment by MashaMSFT** [comment]
Hi @normanarmas , just wanted to follow up on this request. It looks like the summation of all the operators is hitting 100%, and the 233% is by-design to indicate cost of multiple executions. I hope this addresses your question! If not, please let us know how we can clarify further. Otherwise, we will proceed with closing out this Git Issue in a few business days. Thanks again for contacting Microsoft!
