### ISSUE TITLE
Notebook for MSSQL Spark Connector documentation does not exist.

### ISSUE THREAD

**Issue by MasayukiOzawa** [MicrosoftDocs/sql-docs#1996]
https://docs.microsoft.com/en-us/sql/big-data-cluster/spark-mssql-connector?view=sqlallproducts-allversions#run-the-sample-notebook

Even if the URL of the contents of "Run the sample notebook" is accessed, it will be 404.
I can not access  https://raw.githubusercontent.com/Microsoft/sql-server-samples/master/samples/features/sql-big-data-cluster/spark/spark_to_sql/mssql_spark_connector.ipynb

**Comment by MashaMSFT** [comment]
Hi @MasayukiOzawa , thanks for contacting Microsoft and bringing this to our attention! @rothja , would you mind looking into this further?  Thanks!

**Comment by MasayukiOzawa** [comment]
@MashaMSFT @rothja Thank you for your reply.
As I checked today, I was able to access the content.
I will close this issue.

**Comment by MashaMSFT** [comment]
Hi @MasayukiOzawa , awesome! Glad to hear it's working, and thanks for letting us know :) Thanks again for contacting Microsoft!
