### ISSUE TITLE
No Examples On How To Use All Values

### ISSUE THREAD

**Issue by seanwhitepc** [MicrosoftDocs/sql-docs#1997]
This documentation is next to useless for this stored procedure.  I've been trying to find a way to actually use all the values this procedure returns without any luck.  All this documentation provides is how to get the metadata from the procedure, not how to actually get and use the entire range of values it generates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff2bf70-0924-5e33-6624-74e402157750
* Version Independent ID: 3cc8dc62-a7cf-3902-de4e-b9dc58e9a2a8
* Content: [sp_sequence_get_range (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-sequence-get-range-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-sequence-get-range-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-sequence-get-range-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MashaMSFT** [comment]
Hi @seanwhitepc , thanks for bringing this to our attention! @stevestein , would you mind looking into this further? Thanks!

**Comment by MikeRayMSFT** [comment]
Hi @seanwhitepc, there are a few places where you can see examples of how to use stored procedure output. See [Returning Data Using an Output Parameter](http://docs.microsoft.com/sql/relational-databases/stored-procedures/return-data-from-a-stored-procedure?view=sql-server-2017#returning-data-using-an-output-parameter).

For an example with this specific procedure, see [raresql.com](https://raresql.com/2013/01/20/sql-server-2012-sp_sequence_get_range-system-stored-procedure/).
