### ISSUE TITLE
Performance counter described that does not seem to exist

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#2006]
SQL Server:Availability Replica &gt; Bytes sent to transport\sec and SQL Server:Availability Replica &gt; Message Acknowledgement Time (ms)

When I follow the link to : [https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-availability-replica?view=sql-server-2017](This Page)

, the page does not describe this counter, nor is it available in the product.
How does one enable this counter in production?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0b9b5a-dd36-ab20-8d14-31cd137d76fd
* Version Independent ID: bdcc5d85-3cbd-7c91-82d1-c739f42eaeca
* Content: [Monitor performance for availability groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/monitor-performance-for-always-on-availability-groups?view=sql-server-2017&viewFallbackFrom=sql-server-2014#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/monitor-performance-for-always-on-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/monitor-performance-for-always-on-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MashaMSFT** [comment]
Hi @brettshearer , thanks for bringing this to our attention! Let me do a little research and get back to you. Thanks!

**Comment by MashaMSFT** [comment]
Hi @brettshearer , thanks again for contacting Microsoft! Just to clarify, you're clicking this link: SQL Server:Availability Replica > Message Acknowledgement Time and it's not taking you to a page that discusses this counter. Nor are you able to find any documentation that does, or even how to enable it. Is that correct? Thanks!

**Comment by brettshearer** [comment]
Yes – this is correct.
The page exists, but there is no content to describe “Message Acknowledgement Time”

**Comment by MashaMSFT** [comment]
Hi @brettshearer , you're right, this counter was not supposed to be added to the documentation and I've removed it :) Thanks for catching that! Please let us know if there is anything further we can assist you with? otherwise, we'll proceed with closing out this Git Issue in a few business days. Thanks!

**Comment by brettshearer** [comment]
No, all good. Shame the counter never existed...

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
