### ISSUE TITLE
Request_ID is always 0?

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#2007]
I am trying to collect data over time using this DMV, however Request_ID is not unique per session, as described in the help.
Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 785e6be1-0c51-7690-1eb6-c4c98c7c1133
* Version Independent ID: 79592f3b-ccff-06bd-eed8-08ab1bf74205
* Content: [sys.dm_exec_requests (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MashaMSFT** [comment]
Hi @brettshearer , thanks for bringing this to our attention! @stevestein , would you mind looking into this further? Thanks!

**Comment by stevestein** [comment]
@brettshearer - Thanks for the feedback!

The Request_Id is unique in the context of the session, so you need to filter on the request ids for a specific session:
![image](https://user-images.githubusercontent.com/9388190/57655118-b7236e80-758a-11e9-9a19-f996673169a8.png)
 
Hope that helps - I'm going to close this issue. For assistance in the future, you might try one of the links in the [Get Help section](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-technical-documentation?view=sqlallproducts-allversions#info_tip-get-help).

Thanks!

**Comment by brettshearer** [comment]
I think the documentation should be updated to indicate how to get a non zero value. I tested this with Multiple Active Result sets enabled on the connection and managed to get it to be non-zero.
