### ISSUE TITLE
SSMS 18.0 Help About contains incorrect information about operating system

### ISSUE THREAD

**Issue by tristanbarcelon** [MicrosoftDocs/sql-docs#2012]
I successfully uninstalled SSMS 17.9.1 and installed 18.0 via CLI successfully on Windows 10 1803 Enterprise. Upon clicking Help menu and select About item, it shows me 6.3.17134. 17134 is the correct build number but 6.3 is the major and minor for Windows 8.1/Server 2012 R2.

![image](https://user-images.githubusercontent.com/5810165/56782316-96020600-67b4-11e9-81a6-47b207cf9205.png)

**Comment by MashaMSFT** [comment]
Hi @tristanbarcelon , thanks for contacting Microsoft! Unfortunately, this medium is intended for assistance with the documentation, and the issue that you're seeing is outside the scope of that intent. As such, I would recommend using either User voice to submit this as a bug: https://feedback.azure.com/forums/908035-sql-server, contacting the community, or reaching out directly to Microsoft support for further assistance: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017. 

I hope that helps and please let me know if we could be of further assistance. Thanks!

**Comment by Matteo-T** [comment]
@MashaMSFT is correct: this is not really an issue with the documentation. It is more a long outstanding issue in SSMS, which went unnoticed until now. And, yes, the proper way to surface product issues (or even suggestions) is the https://aka.ms/sqlfeedback (short for the ones given above).

Having said all that, I'll look into it :-)

Thanks for reporting it, @tristanbarcelon.

**Comment by tristanbarcelon** [comment]
@Matteo-T , thank you for responding. I'll close this issue and post it to [sqlfeedback](https://aka.ms/sqlfeedback) instead.
