### ISSUE TITLE
DecryptByKey depends on database used for opening key

### ISSUE THREAD

**Issue by dzmitry-palcheuski** [MicrosoftDocs/sql-docs#2013]
You should explicitly set database before using DecryptByKey.
Next example demonstrates this problem when view returns required data and table returns NULL:

CREATE DATABASE __TestingDecryptByKey__
GO

CREATE TABLE __TestingDecryptByKey__.dbo.Test(val VARBINARY(8000) NOT NULL);
GO

USE __TestingDecryptByKey__;
GO

CREATE VIEW dbo.TestView AS SELECT CAST(DecryptByKey(val) AS VARCHAR(30)) AS DecryptedVal FROM __TestingDecryptByKey__.dbo.Test;
GO

USE __TestingDecryptByKey__;

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'ItIsreallyLong1AndSecured!Passsword#';

CREATE CERTIFICATE TestEncryptionCertificate WITH SUBJECT = 'TestEncryption';

CREATE SYMMETRIC KEY TestEncryptSymmmetricKey WITH ALGORITHM = AES_256, IDENTITY_VALUE = 'It is place for test',
KEY_SOURCE = 'It is source for test' ENCRYPTION BY CERTIFICATE TestEncryptionCertificate;

DECLARE @var VARBINARY(8000), @val VARCHAR(30);

SELECT @val = '000-123-4567';

OPEN SYMMETRIC KEY TestEncryptSymmmetricKey DECRYPTION BY CERTIFICATE TestEncryptionCertificate;

SELECT @var = EncryptByKey(Key_GUID('TestEncryptSymmmetricKey'), @val);

SELECT CAST(DecryptByKey(@var) AS VARCHAR(30)), @val;

INSERT INTO dbo.Test VALUES(@var);
GO
USE master;
GO

SELECT DecryptedVal FROM __TestingDecryptByKey__.dbo.TestView;

SELECT CAST(DecryptByKey(val) AS VARCHAR(30)) AS DecryptedVal FROM __TestingDecryptByKey__.dbo.Test;
GO

DROP SYMMETRIC KEY TestEncryptSymmmetricKey REMOVE PROVIDER KEY;

DROP CERTIFICATE TestEncryptionCertificate;

DROP DATABASE __TestingDecryptByKey__;
GO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0239ba-a143-aa94-4b9c-8c8f11432b02
* Version Independent ID: 08ca0425-e13d-67c8-8e3e-adfc8e2871a8
* Content: [DECRYPTBYKEY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/decryptbykey-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/decryptbykey-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/decryptbykey-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @dzmitry-palcheuski , thanks for bringing this to our attention! Let me do a little bit of research and get back to you. Thanks!

**Comment by MashaMSFT** [comment]
Hi @dzmitry-palcheuski , 

Thanks again for contacting Microsoft!  We've submitted a documentation change based on your suggestion, and it should be live at this point. Please let us know if there is anything more we can do for you? If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a wonderful rest of your day!
