### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by JRobinsIken** [MicrosoftDocs/sql-docs#2014]
Regarding this page:
https://docs.microsoft.com/en-us/sql/relational-databases/json/import-json-documents-into-sql-server?view=sql-server-2017#import-multiple-json-documents

The Code sample Under the 'import-multiple-json-documents' section shows that you are giving a variable @file to OPENROWSET, which does not work:

`SELECT @json = BulkColumn FROM OPENROWSET (BULK (@file), SINGLE_CLOB) AS j`

The [documentation for OPENROWSET](https://docs.microsoft.com/en-us/sql/t-sql/functions/openrowset-transact-sql?view=sql-server-2017#remarks) states in the remarks section:

'OPENROWSET does not accept variables for its arguments.'

There are lots of posts on various sites where people are resorting to dynamic sql in order to import multiple json documents.
I hope you implement this functionality in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96b577d2-6af6-c87e-336a-a6fb9b776697
* Version Independent ID: fcad9f44-92fa-dbed-81df-2a70368abe24
* Content: [Import JSON documents into SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/import-json-documents-into-sql-server?view=sql-server-2017#import-multiple-json-documents)
* Content Source: [docs/relational-databases/json/import-json-documents-into-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/import-json-documents-into-sql-server.md)
* Product: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by MashaMSFT** [comment]
Hi @JRobinsIken , thanks for bringing this to our attention! @jovanpop-msft , would you mind looking into this? Thanks!

**Comment by msebolt** [comment]
This issue 2014 is older than a month, closing now.

Bug created as work item at https://dev.azure.com/ceapex/Engineering/_workitems/edit/98704.  

CC: @jovanpop-msft @MashaMSFT

**Comment by oalexrivas** [comment]
What is the solution to this issue ?

CC: @jovanpop-msft @MashaMSFT @msebolt

**Comment by msebolt** [comment]
Apologies, I misinterpreted this as product-feedback opposed to doc-bug.

**Comment by stevestein** [comment]
@JRobinsIken - thanks for the feedback. You're correct, the code doesn't work. :( 
I removed that section from the article.

Thanks for pointing this out.

#please-close
