### ISSUE TITLE
Example 2 - Comments don't align with values

### ISSUE THREAD

**Issue by dphugo** [MicrosoftDocs/sql-docs#2015]
I can see an issue was already raised for Example 2, but I think this is new after that fix.
The last 2 lines in Example 2 are:
SET @town=JSON_VALUE(@jsonInfo,'$.info.address[1].town'); -- Paris
SET @town=JSON_VALUE(@jsonInfo,'$.info.address[1].town'); -- London

Both however returns "London" as the index is 1 for both lines. I assume the intent is that the last 2 lines should be:
SET @town=JSON_VALUE(@jsonInfo,'$.info.address[0].town'); -- Paris
SET @town=JSON_VALUE(@jsonInfo,'$.info.address[1].town'); -- London

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28e8713d-8b6e-7e43-04cc-e2720891b56c
* Version Independent ID: d09b9ed6-4e55-7d18-b17f-88e17839074d
* Content: [JSON_VALUE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-value-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/json-value-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/json-value-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by MashaMSFT** [comment]
Hi @dphugo, thanks for bringing this to our attention! @jovanpop-msft , would you mind looking into this? Thanks!

**Comment by MightyPen** [comment]
Fixed this Issue 2015 by creating public PR #2363 .

@dphugo Thank you for bringing this documentation error to our attention. We hope to hear from you again  :-) 

fyi @jovanpop-msft @MashaMSFT
