### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by pavlo94** [MicrosoftDocs/sql-docs#2016]
Hi, 

First link (to "Using the instructions at this link") in "Create a Domain Independent Availability Group" section is incorrect. 
Correct one is below: 

https://techcommunity.microsoft.com/t5/Failover-Clustering/Workgroup-and-Multi-domain-clusters-in-Windows-Server-2016/ba-p/372059

Best regards, 
Paweł

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df2d6260-37b5-78f2-e558-7129b58ca9c5
* Version Independent ID: 247cde67-5d7a-c844-f2e7-292277348c60
* Content: [Create a domain-independent availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/domain-independent-availability-groups?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/domain-independent-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/domain-independent-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @pavlo94 , thanks for bringing this to our attention! Let me look into this :) Thanks!

**Comment by MashaMSFT** [comment]
Thanks again for contacting Microsoft!  We've submitted a documentation change based on your suggestion, and it should be live at this point. Please let us know if there is anything more we can do for you? If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a wonderful rest of your day!
