### ISSUE TITLE
add with NFS mount

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#2017]
@aversag commented on [Fri Apr 26 2019](https://github.com/MicrosoftDocs/sql-docs.fr-fr/issues/104)

bonjour,
cela serait intéressant d'avoir également cette partie. merci

_Translation, from French to English, is:_  "Hello
it would be interesting to have that part as well. Thank you" (meaning the "NFS mount" part, I presume)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ae3bc9b9-65f5-13bb-53c5-ed929a94b638
* Version Independent ID: eccef86a-10ea-2bbb-ab1b-c530b3fb758c
* Content: [Configurer l’envoi de journaux pour SQL Server sur Linux - SQL Server](https://docs.microsoft.com/fr-fr/sql/linux/sql-server-linux-use-log-shipping?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-use-log-shipping.md](https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/linux/sql-server-linux-use-log-shipping.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @meet-bhagdev
* Microsoft Alias: **meetb**

**Comment by MashaMSFT** [comment]
Hi @CeciAc , thanks for bringing this to our attention! @meet-bhagdev , would you mind looking into this please? Thanks!

**Comment by MightyPen** [comment]
@meet-bhagdev Hi Meet, this article explicitly offers to add a section for NFS, if customers want/request such a section (see code block shortly below, which is a snip of the markdown source). Can you follow through on this offer and update the article via a PR?
In any case, we need to take action on this aging Issue 2017. If necessary please work with SQL Linux Writer @rothja (Jason Roth) to complete the work for this Issue.

```
## Setup a network share for Log Shipping using CIFS 

> [!NOTE] 
> This tutorial uses CIFS + Samba to setup the network share. If you want to use NFS, leave a comment and we will add it to the doc.
```

Thank you. (GeneMi)

CC: @aversag (`https://github.com/aversag`)

**Comment by rothja** [comment]
@CeciAc @aversag I apologize for the very long delay in replying. I have created a content work item to track this request. We appreciate you responding as the article requested. We will triage this and consider adding this to the article in the future. Thanks, again!
