### ISSUE TITLE
dasdsad

### ISSUE THREAD

**Issue by amitpatelupw** [MicrosoftDocs/sql-docs#2022]
dsadsads

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39949710-4382-6df8-9f49-91cc87e2f3e8
* Version Independent ID: a1ceff32-9f8e-5c16-0c6f-95ae1d1e634d
* Content: [SQL Server Documentation - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-technical-documentation?toc=..%2Ftoc%2Ftoc.json&view=sql-server-2017#feedback)
* Content Source: [docs/sql-server/sql-server-technical-documentation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/sql-server-technical-documentation.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @craigg-msft
* Microsoft Alias: **craigg**

**Comment by MikeRayMSFT** [comment]
@amitpatelupw - thanks for using the GitIssues feature of our documentation. We're happy to take a look at any specific issues you point out with our docs. For this issue, I'm going to go ahead and close.
