### ISSUE TITLE
"SSMS can only be upgraded by installing the package of the matching language"

### ISSUE THREAD

**Issue by Chris3y** [MicrosoftDocs/sql-docs#2026]
The release notes appear to indicate this restriction has been specifically removed and yet I'm unable to install SSMS as a result. 

New Windows 10 install. Just installed SQL Server Standard 2017 without any issues then followed the link from the installer to this  page and get the error:
"SSMS can only be upgraded by installing the package of the matching language..."

I'm on a UK operating system that *was* set to US English language. I downloaded the US English version - no difference, I corrected my regional settings to UK English language... still same error. Currently installing SSMS 17.9.1 and it's already half way through whereas 18.0 fails with the error right away.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by MikeRayMSFT** [comment]
@Chris3y - thank you for submitting this. We'll get back to you.

**Comment by Matteo-T** [comment]
This is not an issue with the documentation. It could be an issue with the product itself. I am investigating. I may need to reach out to @Chris3y and ask for a .zip of the %TEMP%\SSMSSetup, if I cannot repro it myself.

-Matteo

**Comment by nikunjratanpara** [comment]
I am facing same issue I am using Windows 10 Enterprise 10.0.17134 with English (United States) Language.

**Comment by Matteo-T** [comment]
That does not look like the same issue: your machine is 100% EN-US and you are (most likely?) installing SSMS EN-US (right)? If that's the case, could you confirm you don't have any other version (Preview, RC) of SSMS 18.0 installed on the machine? What's the output of 
  reg query "HKLM\SOFTWARE\WOW6432Node\Microsoft\Microsoft SQL Server Management Studio" /reg:32 /s

Thanks,
-Matteo

**Comment by bharathbkt** [comment]
Hi @Matteco-T, 
I am having a similar issue, 
Below is the output fo the reg command.

HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SQL Server Management Studio\18
    SSMSInstallRoot    REG_SZ    C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\

ref to to other threads..
https://social.msdn.microsoft.com/Forums/sharepoint/en-US/8b2ed013-66b7-44b9-b18e-6b42aa1b0930/ssms-18-fails-to-install

https://feedback.azure.com/forums/908035-sql-server/suggestions/37483594-ssms-18-0-ga-can-t-be-installed

Thanks for your time for looking into it.

**Comment by Matteo-T** [comment]
Well, if you are positive that:
1) You uninstalled any previous version of SSMS 18.0 (RC, Preview, etc)
2) You deleted the whole "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\" folder
you can just go ahead and delete the entire registry key and reinstall.

I'll post the same thing on UserVoice to unblock users.

**Comment by dkthedon** [comment]
After deleting the mentioned registry key, I was able to install the SSMS successfully. But after installation, SSMS is not starting and logging the following error:
Activation context generation failed for "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Ssms.exe". Dependent Assembly Automation,processorArchitecture="X86",type="win32",version="1.0.0.0" could not be found. Please use sxstrace.exe for detailed diagnosis.

**Comment by Matteo-T** [comment]
@dkthedon: that's something I've never seen before - ugh! Any chance you can zip up the context of %APPDATA%\Microsoft\AppEnv\15.0 and share it with me? Likewise, %Temp%\SSMSSetup. You can e/mail me at matteot@microsoft.com. Thanks.

**Comment by dkthedon** [comment]
@Matteo-T It seems that installation didn't happen correctly. I uninstalled the SSMS and then again installed it be deleting registry key. SSMS is working now after installation.

Thanks a lot for your support.

**Comment by Matteo-T** [comment]
Glad to hear SSMS is finally working! :)

**Comment by DylanCottell** [comment]
I'm having a similar issue with installing. Initially when trying to install it got to "Installing SQL Server Management Studio 18" when the installer locked up my computer - couldn't lock my computer, open task manager, open any windows, or even shut down. Had to manually power down.

Afterwards I tried uninstalling when I got the error message "SSMS can only be upgraded by installing the package of the matching language". I came across this ticket which is when I then tried deleting the "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18" folder and removing the registry keys. Once I had done that, I tried reinstalling which is when it partially installed - however SSMS 18 itself didn't install. When trying to use the wizard to uninstall it is stuck on "loading packages". Left it for 2 hours and has done nothing.

Any ideas on what I should do next?

**Comment by dkthedon** [comment]
@DylanCottell Please check the registry value at the following path
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SQL Server Management Studio\18\SSMSInstallRoot.

If it doesn't exist, please create it manually with type REG_SZ and value "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\".

After this, try to run the installer again to uninstall the application. It should work.

**Comment by DylanCottell** [comment]
> @DylanCottell Please check the registry value at the following path
> HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SQL Server Management Studio\18\SSMSInstallRoot.
> 
> If it doesn't exist, please create it manually with type REG_SZ and value "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18".
> 
> After this, try to run the installer again to uninstall the application. It should work.

Got it to install, although it required me to do another hard shut down. Thanks!

**Comment by dkthedon** [comment]
@DylanCottell, I am Glad to hear that.

**Comment by askhan123** [comment]
hey I have same issue. the download progress reaches to 99% then repeats itself and start from 1% again. I didnt find anything in the registry or in drive C relating to SSMS . Please help

**Comment by dkthedon** [comment]
@askhan123 This issue is not related to the download progress of setup files. You could try to download the offline installer and then install using it.

**Comment by askhan123** [comment]
@dkthedon Thanks. do you know where can I download offline installer from?

**Comment by dkthedon** [comment]
@askhan123 Online installer gives you the options to either installer the application or download the media. You can choose the download media option to download .iso file and then mount this iso file and run the setup.

**Comment by askhan123** [comment]
thanks @dkthedon

**Comment by asmialoski** [comment]
Hello,

I had the same issue. I was able to install SSMS after delete the key "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SQL Server Management Studio" and the folder "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18".

Regards,

**Comment by mlbuie** [comment]
> Hello,
> 
> I had the same issue. I was able to install SSMS after delete the key "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SQL Server Management Studio" and the folder "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18".
> 
> Regards,

This solution worked for me

**Comment by joseforendo** [comment]
> > Hello,
> > I had the same issue. I was able to install SSMS after delete the key "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SQL Server Management Studio" and the folder "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18".
> > Regards,
> 
> This solution worked for me

worked for me as well

**Comment by ib888877** [comment]
> Hello,
> 
> I had the same issue. I was able to install SSMS after delete the key "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SQL Server Management Studio" and the folder "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18".
> 
> Regards,

worked for me as well

**Comment by jiuminer** [comment]
Hola,

Tuve el mismo problema. Pude instalar SSMS después de eliminar la clave "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SQL Server Management Studio" y la carpeta "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18".

Saludos,

Me funcionó a mi también

**Comment by jiuminer** [comment]
Hola,

Tuve el mismo problema. Pude instalar SSMS después de eliminar la clave "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SQL Server Management Studio" y la carpeta "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18".

Saludos,

Me funcionó a mi también
