### ISSUE TITLE
Command typo for addent

### ISSUE THREAD

**Issue by smolens** [MicrosoftDocs/sql-docs#2027]
under "Add keytab entries for each SPN using the following commands:" "aes256-cts-hmac -sha1-96" should have no space after hmac

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Use AD authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **Dylan.Gray**

**Comment by MikeRayMSFT** [comment]
Thank you @smolens 

Reviewing solution

**Comment by MikeRayMSFT** [comment]
Fixed by @tejasaks MicrosoftDocs/sql-docs#2050

Thank you @smolens for raising the issue
