### ISSUE TITLE
Powershell 'cd' command confusion

### ISSUE THREAD

**Issue by stuart-hagsw** [MicrosoftDocs/sql-docs#2028]
Forgive me if I'm just being ignorant, but this line in the Powershell script example doesn't make any sense to me:
CD SQLSERVER:\SQL\localhost\DEFAULT  

I'm trying to get this working on Sql Express. Where would I need to CD to?

Thanks,
Stuart Neal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfdc07a0-b02e-f6c1-a4dc-45101e20c8d5
* Version Independent ID: b7fce2b0-3319-2a23-3927-21ef42ea7d7d
* Content: [Register a Database As a DAC - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/register-a-database-as-a-dac?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/data-tier-applications/register-a-database-as-a-dac.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/register-a-database-as-a-dac.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MikeRayMSFT** [comment]
@stuart-hagsw [Navigate SQL Server PowerShell Paths](http://docs.microsoft.com/sql/powershell/navigate-sql-server-powershell-paths) explains that an alias for `Set-Location` cmdlet is `cd`. 

The example in the command changes the current node to the SQL Server default instance.  

Probably: 
`CD SQLSERVER:\SQL\localhost\SQLEXPRESS`

Thanks for the comment!
