### ISSUE TITLE
Documentation for "lob *" columns output

### ISSUE THREAD

**Issue by magasvs** [MicrosoftDocs/sql-docs#2029]
The following output columns "lob logical reads", "lob physical reads", "lob read-ahead reads" will also have output for the columnstore indexes pages regardless of the data type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00651e98-1d8e-4c17-5f8f-ea50136128eb
* Version Independent ID: 158bf686-4304-aa99-c2d2-c7749f87e913
* Content: [SET STATISTICS IO (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-statistics-io-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/set-statistics-io-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-statistics-io-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by MikeRayMSFT** [comment]
@magasvs - thanks for the submission. I'm checking a few things out and will get back to you.

**Comment by MikeRayMSFT** [comment]
@bluefooted - would you mind looking into this issue. I can help update the docs.

**Comment by MikeRayMSFT** [comment]
Thank you @magasvs for raising this issue! It sheds light on this subject. We are updating the article.
