### ISSUE TITLE
Incorrect information regarding Change Tracking support

### ISSUE THREAD

**Issue by ShaunJStu** [MicrosoftDocs/sql-docs#2031]
This page states "Change tracking can be enabled on a database with In-Memory OLTP objects. However, changes in memory-optimized tables are not tracked." This is incorrect. Attempting to enable change tracking at the database level for a database with In-Memory objects results in the error "Change tracking is not supported for a database with memory optimized objects. Remove all memory optimized objects from the database and then configure change tracking."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f34d1d9-996d-a5b7-c525-a0c8b2275373
* Version Independent ID: 8d8a4eff-4a28-a749-97c8-b42c7e55c477
* Content: [Unsupported SQL Server Features for In-Memory OLTP - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/unsupported-sql-server-features-for-in-memory-oltp?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/in-memory-oltp/unsupported-sql-server-features-for-in-memory-oltp.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/unsupported-sql-server-features-for-in-memory-oltp.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MikeRayMSFT** [comment]
@ShaunJStu - thank you for this submission. We will investigate and get back to you.

**Comment by MightyPen** [comment]
Fixed this Issue 2031, with PR 10430.
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10430

@ShaunJStu Thank you very much for this very nice correction. And, we hope you are benefiting from the In-Memory features.

I am now closing this fixed Issue.  The fix should appear on live Docs within 24 hours.

**Comment by michael-baker** [comment]
Change tracking appears to work in SQL Server 2016 and 2019 when you have in-memory OLTP enabled. Because change tracking works perhaps the wording of the documentation is incorrect? Can I get clarification if the documentation is trying to convey one of these scenarios? 

- Change tracking on disk-based tables is not supported by Microsoft. This means I get no support if something goes wrong & I have in-memory OLTP enabled. But change tracking works.
- Change tracking no longer works at all.
- Change tracking works but does not work on in-memory OLTP tables.

**Comment by MikeRayMSFT** [comment]
@michael-baker - I'm reactivating this and thank you for raising this issue again.

**Comment by MikeRayMSFT** [comment]
> Change tracking appears to work in SQL Server 2016 and 2019 when you have in-memory OLTP enabled.
> 
> I receive no error when issuing
> 
> `alter database Foo set change_tracking = on (CHANGE_RETENTION = 7 DAYS, AUTO_CLEANUP = ON)`
> 
> I do see the warning mentioned in the original post when trying to use the UI from SSMS to configure change tracking but I imagine this is a bug in SSMS.
> 
> Because change tracking works perhaps the wording of the documentation is incorrect? Can I get clarification if the documentation is trying to convey one of these scenarios?
> 
> * Change tracking on disk-based tables is not supported by Microsoft. This means I get no support if something goes wrong & I have in-memory OLTP enabled. But change tracking works.
> * Change tracking no longer works at all.
> * Change tracking works but does not work on in-memory OLTP tables.

**Comment by MikeRayMSFT** [comment]
Our engineering team discussed this. I'm following up with them to answer.

**Comment by MikeRayMSFT** [comment]
Change tracking is not supported on a database that contains in-memory OLTP objects. This is what the documentation says currently and it seems to be correct from a support stand point. Our engineering team is investigating when and how this can be enabled and is planning to prevent users from configuring it in an unsupportable state. 

Contacted customer via email. 

Engineering is tracking the issue the customer described as an anomoly in the product and is planning an appropriate resolution.

**Comment by wicknicks** [comment]
@MikeRayMSFT I tried to enable CDC on a memory optimized table, but was unable to do so. the final error was: 

```
A memory-optimized table cannot be enabled for Change Data Capture (CDC). 
[SQL State=S0001, DB Errorcode=41385]
```

I'm using the docker image `mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-16.04` to run the test. As per this thread and this error message, are *both* change tracking and CDC unavailable for memory optimized tables? 

The table was created with: 

```
create table my_memtable (id int NOT NULL PRIMARY KEY NONCLUSTERED, name varchar(30)) WITH
(
    MEMORY_OPTIMIZED = ON,
    DURABILITY = SCHEMA_AND_DATA
);
```

and CDC was enabled with: 

```USE arjun
GO  
EXEC sys.sp_cdc_enable_table  
@source_schema  = N'dbo',  
@source_name    = N'my_memtable',  
@role_name      = NULL,  
@filegroup_name = NULL,  
@supports_net_changes = 0 
GO
```

thanks in advance!
