### ISSUE TITLE
Ubuntu deployment experience with this guideline.

### ISSUE THREAD

**Issue by luisgmsft** [MicrosoftDocs/sql-docs#2034]
I'm deploying in 3 equally deployed off-the-shelf Ubuntu 16.04.

On [Create the Pacemaker Cluster -Step 2](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-deploy-pacemaker-cluster?view=sql-server-2017#create-the-pacemaker-cluster): had to add --force as suggested by the error I've got 

In order to `sudo apt-get install mssql-server-ha` I had to add proper apt repo following these instructions (https://askubuntu.com/questions/850607/mssql-on-ubuntu-cant-get-it-install?answertab=votes#tab-top)

Also, got an error with  mssql-server-agent, but discarded as I don't need it right now.

Cheers :)

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88250aa7-86db-e08d-c01c-aeb2add82da2
* Version Independent ID: 5c2dd107-5983-654a-db22-3fbfcced8668
* Content: [Deploy a Pacemaker cluster for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-deploy-pacemaker-cluster?view=sql-server-2017#create-the-pacemaker-cluster)
* Content Source: [docs/linux/sql-server-linux-deploy-pacemaker-cluster.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-deploy-pacemaker-cluster.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
@luisgmsft - thank you for submitting this. I've asked @rothja to follow up.

**Comment by rothja** [comment]
@luisgmsft Hello. Sorry you were having a problem. I'd like to make sure the article is right and clear. Before you followed the steps in this article, had you previously installed SQL Server 2017 with the quickstart steps: https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-2017. I believe that the instructions of this article register the correct repositories for the HA pacakage to install. If you did do that, I'm not sure why it wouldn't have worked. I might need to compare the instructions there with the steps you followed on the forum post. Thanks for the additional information as I research this!

**Comment by luisgmsft** [comment]
@rothja you're right about me skipping the prereqs piece on SQL 2017. I manually run this at a latter stage on my testing setup with this script, which took care of it (https://docs.microsoft.com/en-us/sql/linux/sample-unattended-install-ubuntu?view=sql-server-2017).

Thanks for writing back. I'm working on automating the setup of a 3 node Linux SQL 2017 AG AO Cluster (for Full HA) based on this one and this [other](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-create-availability-group?view=sql-server-2017) guidelines. From infrastructure to working AO Cluster.
