### ISSUE TITLE
Valid range of values is not given for the date data type

### ISSUE THREAD

**Issue by fkconnors** [MicrosoftDocs/sql-docs#2036]
Someone told me that the date data type in SQL DW does not support date values prior to 1950.  I find that hard to believe, but I cannot get that confirmed or refuted because this page does not state what the valid range of values for the date data type are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4775d99-7054-3a3f-98bb-815b65b67358
* Version Independent ID: 6f9ab4ec-3b8a-e2d6-3546-8179f36a0999
* Content: [CREATE TABLE (Azure SQL Data Warehouse) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-azure-sql-data-warehouse?view=aps-pdw-2016-au7#feedback)
* Content Source: [docs/t-sql/statements/create-table-azure-sql-data-warehouse.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-azure-sql-data-warehouse.md)
* Service: **sql-data-warehouse**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by MikeRayMSFT** [comment]
@fkconnors - thank you for the question, I'll get back to you.

**Comment by MikeRayMSFT** [comment]
@julieMSFT would please investigate?

**Comment by julieMSFT** [comment]
@fconnors, thanks for bringing this to our attention! I am researching the answer. Thanks!

**Comment by julieMSFT** [comment]
@fkconnors, thank you for your question. The date ranges can be found [here](https://docs.microsoft.com/en-us/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql). I am updating the original document with this link. I am also updating the linked document to show it supports Azure SQL DW. The changes will be visible soon. I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!

**Comment by julieMSFT** [comment]
#10163

**Comment by fkconnors** [comment]
Thank you, Julie.  For some reason, the first time I followed that link, it
showed that it applied to Azure SQL DW, but every time I have followed that
link since then, it shows it only applies to SQL Server, even after closing
and re-opening my browser.  I also see no link to page from the create
table page for which I posed my question (
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-azure-sql-data-warehouse?view=aps-pdw-2016-au7#DataTypes)
and see no mention of the range of possible values for the date data type
there.  Would you please check this?
Thanks!
Kevin

**Comment by julieMSFT** [comment]
Hi Kevin, Sorry if my reply was confusing. The page you posted your question on now has a note and link to the article with all the data time values. It took a bit for the changes to get published but they are now visible. The date data type supports values _0001-01-01 through 9999-12-31_. You can find the range of values for the different date and time data types [here](https://docs.microsoft.com/en-us/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql?view=azure-sqldw-latest#DateandTimeDataTypes).  Please feel free to respond should you need anything further. Thanks!
