### ISSUE TITLE
Filtering widgets to dashboards for specific databases

### ISSUE THREAD

**Issue by jamesstead** [MicrosoftDocs/sql-docs#2037]
I'm curious about the "when" property I only want to show queries on databases with a specific name.  Any chance I can filter on that my attempts to add a filter for database have met with failure.  For example one pattern I tried was "when": "mssql:database=='HealthCheck'",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9720e473-61dc-6a0f-9481-ca6c617d3265
* Version Independent ID: 5e373d84-4b76-0019-fc0b-616e3672e4a4
* Content: [Tutorial: Build a custom insight widget - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/tutorial-build-custom-insight-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/azure-data-studio/tutorial-build-custom-insight-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/tutorial-build-custom-insight-sql-server.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MikeRayMSFT** [comment]
@jamesstead  - thank you for submitting. We'll take a look.

**Comment by mtcoope** [comment]
@jamesstead Took me a bit to figure this out but here are the variables you can use.
https://docs.microsoft.com/en-us/sql/azure-data-studio/extensibility?view=sql-server-2017#dashboard

So in your case this should work.
```
"when": "databaseName == 'HealthCheck'",
```

**Comment by stevestein** [comment]
@mtcoope - thanks for jumping in with a reply!
@jamesstead - Since this isn't an actual issue with the article I'm going to close this one. Thanks!

@markingmyname - FYI

**Comment by jamesstead** [comment]
Thanks so much this works great @mtcoope
