### ISSUE TITLE
Units???

### ISSUE THREAD

**Issue by eliotg** [MicrosoftDocs/sql-docs#2040]
What are the units of the tolerance parameter?  Meters? Percentage? Light years? Inverse femptobarns?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fcd429a-d923-e11c-aba1-6209159b1352
* Version Independent ID: 33829564-2321-7057-a054-b2b289f93d85
* Content: [Reduce (geography Data Type ) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geography/reduce-geography-data-type?view=sql-server-2017)
* Content Source: [docs/t-sql/spatial-geography/reduce-geography-data-type.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/spatial-geography/reduce-geography-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by MikeRayMSFT** [comment]
@eliotg thanks for the question - I'm going to get an answer - but it's probably not  Inverse femptobarns:)

**Comment by MikeRayMSFT** [comment]
Emailed spatial group

**Comment by MikeRayMSFT** [comment]
The unit is same as for the other unit aware operations such as STDistance – the one inherited from Srid.

Default Srid – 4326 -> meters
