### ISSUE TITLE
Dark Theme in SSMS 16.0

### ISSUE THREAD

**Issue by reader-man** [MicrosoftDocs/sql-docs#2041]
Hi,
 Thanks for the new powefull version of SSMS.
I would like to inform you, that the dark theme in SSMS 16.0 released version, is not available.
plus, this theme in SSMS 15.0 + 16 beta, was not applied to all windows and tools, e.g. Object Explorer + Results window.

Regards.

**Comment by MikeRayMSFT** [comment]
@reader-man thank for this issue. Will forward this issue to the appropriate development resource.

**Comment by mammadkoma** [comment]
Please add dark mode to ssms.

**Comment by WilliamAntonRohm** [comment]
@mammadkoma -- Mohammad, thank you for your suggestion.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)
