### ISSUE TITLE
STContains vs. STWithin vs. STIntersects?

### ISSUE THREAD

**Issue by eliotg** [MicrosoftDocs/sql-docs#2044]
It would be nice if the documentation explicitly addressed why there are multiple ostensibly similar functions.  Since STIntersects' existence presumably rules out partial vs. strict subset, I can't think of any other English-based meaning difference between STWithin and STContains.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be221aa-48df-e9ab-fc2d-65d4f7ec56ce
* Version Independent ID: b81cfb49-c58a-97bd-5e85-224e567a633e
* Content: [STContains  (geography Data Type) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geography/stcontains-geography-data-type?view=sql-server-2017)
* Content Source: [docs/t-sql/spatial-geography/stcontains-geography-data-type.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/spatial-geography/stcontains-geography-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by MikeRayMSFT** [comment]
Thank you @eliotg - again - I'll find the answer.

**Comment by MikeRayMSFT** [comment]
Still monitoring.

**Comment by MikeRayMSFT** [comment]
Here's the answer that I got back:)

>Functions starting with ST are OGC standardized function calls that can be found in other implementations of OGC spec as well in similar forms (e.g. `ST_Within`, `ST_Contains`, in PostgreSQL, Oracle, etc) 
>
>Also, I don’t see any language ambiguity when saying if A CONTAINS B, then B is WITHIN A, i.e.
>
> `a.STWithin(b) == b.STContains(a)`
