### ISSUE TITLE
SSDT for VS 2017: 15.9.1 Release Notes missing

### ISSUE THREAD

**Issue by pmalecka** [MicrosoftDocs/sql-docs#2045]
https://docs.microsoft.com/en-us/sql/ssdt/release-notes-ssdt?view=sql-server-2017

There's no Release Notes Published for the new version: 15.9.1

**Comment by stevestein** [comment]
@pmalecka - thanks for raising this issue!  Release notes for 15.9.1 have been added to the [current page](https://docs.microsoft.com/sql/ssdt/release-notes-ssdt?view=sql-server-2017#1591-ssdt-for-vs-2017) so I'm going to close this.

Thanks!
