### ISSUE TITLE
error on web page

### ISSUE THREAD

**Issue by mxmage** [MicrosoftDocs/sql-docs#2047]
the line reads: 
NOTE: When a login connects to SQL Server the identify is validated

should be:
NOTE: When a login connects to SQL Server the **identity** is validated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e102e98e-7c04-4898-f351-f78ae895772e
* Version Independent ID: 8a1d99f2-9209-3e34-843c-a17b5a60aa75
* Content: [Create a Login - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/create-a-login?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/authentication-access/create-a-login.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/create-a-login.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by MikeRayMSFT** [comment]
Thank you @mxmage for pointing this out. We're going to fix it. 

In the future you can contribute to our documentation by submitting the fix directly from the web page. Just click **Edit**. You'll need a GitHub account. Thanks again!

**Comment by MikeRayMSFT** [comment]
Fixed. Thanks again @mxmage
