### ISSUE TITLE
ignoring fk constraint 

### ISSUE THREAD

**Issue by jhirschdrg** [MicrosoftDocs/sql-docs#2048]
when have a FK on a column the bulk insert is ignoring it, looks to me like a bug in the bulk insert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5106a6-4e54-2177-3e03-b2845f9587c5
* Version Independent ID: c3bc5aaa-0119-9c4d-3d7b-0ee218885361
* Content: [BULK INSERT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/bulk-insert-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/bulk-insert-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/bulk-insert-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by MikeRayMSFT** [comment]
Thank you @jhirschdrg for the question. 
By default `BULK INSERT` ignores check constraints and FK constrainsts. 

See [Check constraints ](http://docs.microsoft.com/sql/t-sql/statements/bulk-insert-transact-sql?view=sql-server-2017#arguments).
