### ISSUE TITLE
Use double-quotes from the Windows command prompt

### ISSUE THREAD

**Issue by rlundy** [MicrosoftDocs/sql-docs#2058]
I think a lot of people are discovering this page when trying to run SQL Server in a Linux container on Windows.  But the above directions don't work, because the -e commands need to be in double quotes on Windows.  (https://github.com/Microsoft/mssql-docker/issues/199)  Could a note be added to the bash/PowerShell section indicating what the corresponding command would be in the Windows command prompt?  Or perhaps in addition to bash and PowerShell, Windows command prompt could be added as an article option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Get started with SQL Server containers on Docker (running SQL Server on Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@rlundy We could consider adding a CMD to the list at the top for clarity? Did you see the choices at the top when you first tried the article? This was an experiment to see if that slicer would be helpful. I would be interested in your feedback. Thank you! @MightyPen FYI.

**Comment by rlundy** [comment]
Hi, @rothja!  I saw the choices at the top, but I ignored them because neither one was relevant to me.  When I got to [Pull and run the container image, step 2](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-powershell#pullandrun2017), the bash syntax was still there by default so I used it, and the EULA stuff didn't work.  I ended up searching and finding this page and this comment...

https://github.com/Microsoft/mssql-docker/issues/199#issuecomment-346092077

...which explained what the issue was.

In this particular case, as it turns out, the PowerShell syntax would've worked in command prompt too, so perhaps I'll make that my default from now on.  But maybe there are still a fair number of us out there using the Windows command prompt and batch files to do these things?  How many pages like this are there?  How big a task would it be to add Windows command prompt commands alongside bash and PowerShell?

**Comment by rothja** [comment]
@rlundy Thanks for the extra info. I'm looking into what might be the best option here to avoid confusion.

**Comment by rothja** [comment]
@rlundy Thanks, again, for letting us know your confusion on this article. I have updated the article to have a CMD option as well to avoid that confusion in the future. I have also made some other changes for clarity. I'm closing this Git issue now, but let me know if you have any other questions. Thanks!
