### ISSUE TITLE
Management Studio Will Not Open

### ISSUE THREAD

**Issue by Ry-the-Stunner** [MicrosoftDocs/sql-docs#2061]
Ever since upgrading to Management Studio 18.0 GA, the product has difficulty opening.  I have no issues upon first installation and am able to use it fine.  However, if I restart my computer and then try to launch Management Studio from my taskbar shortcut, I get a brief (maybe 1 second) flash of Management Studio splash screen and then it closes and the product does not launch.  The first time this happened, I had to uninstall and reinstall and it worked, until I restarted my computer again.  I tried a Repair and that didn't work, so it seems I'll have to keep reinstalling the product every time I start my computer.  I had ZERO issues with this in the 18.0 Preview version, this ONLY started happening when I upgraded to GA.

**Comment by stevestein** [comment]
@Ry-the-Stunner - Thanks for the feedback! I've added a couple team members who might have some insight but this area is primarily for doc issues. To report product issues, the best way to reach out to the SSMS Team is at [UserVoice](https://aka.ms/sqlfeedback). 

Thanks!

**Comment by markingmyname** [comment]
Hi @Ry-the-Stunner, 

Do you have any previous versions of SSMS installed?  Starting in Mgmt Studio v18.0 it can be installed alongside previous versions.  Just curious. Thank you.

**Comment by Ry-the-Stunner** [comment]
Hi @markingmyname,

At the time, I did not have any previous versions of SSMS installed.  I had uninstalled v17.9 and installed v18.0 preview, and then when I upgraded to v18.0 GA, I started having the issue with SSMS not opening.

I had to revert back to v17.9 in order to be able to use it anymore.

**Comment by markingmyname** [comment]
@Ry-the-Stunner,

I can say I installed [18.0 (GA version)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#download-ssms-180-ga) just today in fact and have had no issues opening the application or running the application. 

I would suggest reaching out to UserVoice or opening a support ticket for this one.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
