### ISSUE TITLE
tde-architecture.gif doesn't render well when in dark theme on page

### ISSUE THREAD

**Issue by RachelAmbler** [MicrosoftDocs/sql-docs#2062]
My account settings here use the Dark theme. As a result, the `tde-architecture.gif` image that shows the *Encryption Hierarchy* fails to render well as the text inside is in black and thus is almost impossible to read when using the dark theme.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20953c9f-c769-7849-420a-dac77f917d4a
* Version Independent ID: dfd9ad27-844c-c3c8-58a3-5d4a0c92fbba
* Content: [Transparent Data Encryption (TDE) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/encryption/transparent-data-encryption.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/transparent-data-encryption.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @aliceku
* Microsoft Alias: **aliceku**

**Comment by stevestein** [comment]
@RachelAmbler - Thanks for the feedback! I've assigned this to the author @aliceku 

Thanks!

**Comment by aliceku** [comment]
@VanMSFT do you have any idea what can be done here? This graphic is at least 5 years old and I don't know who created it...

**Comment by VanMSFT** [comment]
@RachelAmbler - Thanks for letting us know, Rachel! We really appreciate it. I'll go ahead and fix this. If you have any questions, please feel free to let us know.

@aliceku - It's how the image is rendering when using gif. I'm switching the images to png. Thanks!

https://github.com/MicrosoftDocs/sql-docs-pr/pull/10164

**Comment by VanMSFT** [comment]
PR has been pushed through, and images are fixed. They will show on the live site tomorrow morning. Closing this Issue.
