### ISSUE TITLE
datetimeoffset is listed as an unsupported storage type for sql_variant

### ISSUE THREAD

**Issue by mburbea** [MicrosoftDocs/sql-docs#2063]
The documentation list that datetimeoffset is unsupported, however this
`select sql_variant_property(sysdatetimeoffset(),'BaseType')`
runs successfully and returns datetimeoffset.

Tried with sql server 2016 (but I believe it worked on earlier revisions).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f737f42-fee4-dd51-b8a8-460ca03eee44
* Version Independent ID: 859731e3-402e-5131-25fe-155095b4911f
* Content: [sql_variant (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/sql-variant-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/data-types/sql-variant-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/sql-variant-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by stevestein** [comment]
@mburbea - thanks for the feedback! I've assigned this to the author @MikeRayMSFT .
Thanks!

**Comment by MikeRayMSFT** [comment]
@mburbea - thanks again for the feedback. I'm reviewing with engineering to verify.

**Comment by MikeRayMSFT** [comment]
@mburbea, you are correct. Beginning with SQL Server 2012, sql_variant supports datetime offset. We're updating the content. Thank you @pmasl
