### ISSUE TITLE
The json data type value of 2 is incorrectly stated to be an int, it should be float.

### ISSUE THREAD

**Issue by mburbea** [MicrosoftDocs/sql-docs#2065]
The json data type table says that 2 is an `int`. However, it should really be a float as json only has a single IEEE754 double precision floating point type defined. 
`select type from openjson('[2.5,1]')`, both rows return 2.

---

`SELECT type from OpenJson('[2.5,1]');`

Two rows are returned. Both rows return type ID= '2', per the "Type" column in the documentation article.
Yet there is no way that the numeric value of "2.5" can be an integer, despite the claim of the table for row ID= '2': instead the type name should be "double precision floating point".

Thus to correct the documentation, replace "IntValue" with "DoublePrecisionFloatingPoint_Value", and add a second column whose value is '2.3456'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e25eda30-d6e4-600c-ed9d-4f0a53ee1058
* Version Independent ID: 9b53b7d7-b827-6f7f-c0c9-84645742d6a2
* Content: [OPENJSON (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/openjson-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/openjson-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/openjson-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by stevestein** [comment]
@mburbea - thanks for the feedback! I've assigned this to the author @jovanpop-msft 
Thanks!

**Comment by MightyPen** [comment]
@mburbea
I decided to fix this Issue 2065, and to fix the article (with PR 10742).
Thank you very much for bringing this documentation error to our attention, and for your helpful description of the problem. The fix should be visible on live Docs by EODay Monday June/24.

- PR=10742:  ` https://github.com/MicrosoftDocs/sql-docs-pr/pull/10742`

I am now Closing this Issue 2065, as fixed.

CC: @jovanpop-msft

**Comment by mburbea** [comment]
@MightyPen , thanks for the partial fix.
Unfortunately there is still this section in the article that claims that it is an int :(
![image](https://user-images.githubusercontent.com/213233/60049279-fa99ee00-969b-11e9-99e8-192876541bb9.png)
