### ISSUE TITLE
Is the [key] column only available in implicit schema mode?

### ISSUE THREAD

**Issue by mburbea** [MicrosoftDocs/sql-docs#2066]
The documentation makes it a point to mention that the type column is only returned when you call `openjson` in implicit mode (e.g. without a schema). However, it appears that the [key] column is also only available when you call `openjson` without a schema.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e25eda30-d6e4-600c-ed9d-4f0a53ee1058
* Version Independent ID: 9b53b7d7-b827-6f7f-c0c9-84645742d6a2
* Content: [OPENJSON (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/openjson-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/openjson-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/openjson-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by stevestein** [comment]
@mburbea - thanks for the feedback! I've assigned this to the author @jovanpop-msft 

Thanks!

**Comment by MightyPen** [comment]
@msebolt Hi Matthew, can you experiment for a few minutes to ascertain the degree to which this claim made by our customer is correct. And take actions to finish and close this Issue 2066. Thanks!
(FYI, Issue #2065 was a fix, by me, inside this same article.  GeneMi)

**Comment by msebolt** [comment]
@MightyPen @mburbea  I think this refers to accessing the key column while in explicit mode (using a schema) to which you can use a `JOIN` statement:

```
 DECLARE @json NVARCHAR(MAX) = N'[  
  {  
    "Order": {  
      "Number":"SO43659",  
      "Date":"2011-05-31T00:00:00"  
    },  
    "AccountNumber":"AW29825",  
    "Item": {  
      "Price":2024.9940,  
      "Quantity":1  
    }  
  },  
  {  
    "Order": {  
      "Number":"SO43661",  
      "Date":"2011-06-01T00:00:00"  
    },  
    "AccountNumber":"AW73565",  
    "Item": {  
      "Price":2024.9940,  
      "Quantity":3  
    }  
  }
]'  
   
SELECT *
FROM OPENJSON ( @json )  
WITH (   
              Number   varchar(200)   '$.Order.Number',  
              Date     datetime       '$.Order.Date',  
              Customer varchar(200)   '$.AccountNumber',  
              Quantity int            '$.Item.Quantity',  
              [Order]  nvarchar(MAX)  AS JSON  
 ) INNER JOIN OPENJSON ( @json ) ON value like '%' + Number + '%'
```

...and gain access to the key column.

**Comment by mburbea** [comment]
Yeah, but you're basically doing the work twice. So with a schema it is impossible to get access to the `[key]` column. If that's the case it should be documented explicitly, as it is for the `type` column. Or `type` should remove this bit of language, as it makes it appear that `[key]` could be available.

**Comment by msebolt** [comment]
@mburbea Sounds good, the document has been updated.

Please refer to the [forum](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/home) for product suggestions.

**Comment by msebolt** [comment]
#please-close
