### ISSUE TITLE
como documentar base de datos sql server de forma facil

### ISSUE THREAD

**Issue by cristian-ceniss** [MicrosoftDocs/sql-docs#2077]
ayuda quien sabe como documento una base de datos sql server de forma facil

(_The above Spanish translates into English as:_ "help who knows how to document a sql server database in an easy way")

**Comment by craigg-msft** [comment]
@nokura can you help us get started?

**Comment by MightyPen** [comment]
@cristian-ceniss Hello Cristian, this Issues website is for reporting errors in the SQL Server documentation, as it is under `https://docs.microsoft.com/sql/sql-server/`. You can start at that documentation article, and the search the left-side Table of Contents for documentation articles that pertain to your current area of interest about Microsoft SQL Server.

I am now Closing this Issue 2077.
Thank you.
