### ISSUE TITLE
sp_rename is not supported in Azure Data Warehouse

### ISSUE THREAD

**Issue by LuisGonzalezLT** [MicrosoftDocs/sql-docs#2079]
nuf said

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e01ce5d-922b-f4ed-d24a-af0123ef26b5
* Version Independent ID: 22de7f7e-fef0-410f-618b-d76915bff1c0
* Content: [Rename Statistics - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/statistics/rename-statistics?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/statistics/rename-statistics.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/statistics/rename-statistics.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by stevestein** [comment]
@LuisGonzalezLT - thanks for the feedback! I've assigned this to the author @julieMSFT 

Thanks!

**Comment by julieMSFT** [comment]
@LuisGonzalezLT, thanks for bringing this to our attention! I have updated the document. You should see the change today. I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!

**Comment by julieMSFT** [comment]
#10154
