### ISSUE TITLE
Setting a DEFAULT value for a DATE column in SMSS - How ???

### ISSUE THREAD

**Issue by bdcoder2** [MicrosoftDocs/sql-docs#2082]
Using SQL Server 2016 - In SQL Management Studio, when selecting Table -> Design and then trying to enter a value as the default for a DATE column:

Tried various literals, functions, etc to no avail -- How do you set a default value for a DATE column?    (NOT a DATETIME column)-- all of the below fail:

GETDATE()
CAST( GETDATE() AS DATE)
'2019-05-16'
CAST( '2019-05-16' AS DATE)
DATEFROMPARTS( 2019, 05, 16)

Please, please, please include at least one example on setting a DEFAULT value for a DATE column -- cannot be found anywhere in the documentation. 

As a matter of fact an example on how to set a default value for all data types should really be part of the docs.  But lets get one for DATE to start with.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82cb9c55-70cb-c14f-d6de-59f84af52098
* Version Independent ID: 619a332c-45ee-da6d-0eec-4721906d6880
* Content: [date (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/date-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/data-types/date-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/date-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by mburbea** [comment]
How's about::
drop table if exists #t
create table #t
(

    date date constraint df_name default datefromparts(2019,05,16)
)

**Comment by bdcoder2** [comment]
Sorry - original post should have mentioned these do NOT work in SQL Management Studio when selecting  Table -> Design -- Try entering the DATEFROMPARTS( 2019, 05, 16 ) as the default value for a column and SMSS will display an error (I am using SQL Server 2016).

**Comment by mburbea** [comment]
Seems to work for me?
![image](https://user-images.githubusercontent.com/213233/57390460-6545a780-718a-11e9-94ed-b4a1cd99fe4d.png)

**Comment by bdcoder2** [comment]
Not this format: DATEFROMPARTS( 2019, 5, 16 ) -- why and where is it described you need () around each value??

**Comment by mburbea** [comment]
I entered it as datefromparts(2019,9,1), ssms put parens around everything.

**Comment by bdcoder2** [comment]
Weird -- mine does not (put parens around the values) -- again, may a version difference?  The other difference (maybe) I was UPDATING a previously created table, not creating a new one.  Will have to experiment further.  Thanks for the updates though !! ;)

**Comment by bdcoder2** [comment]
OK - our system must have had a bug or something, because a quick re-boot and now I am able to set DATE defaults using the examples given -- my apologies for the rant -- however, I think examples for defaults within the docs would still be a good idea.

Thanks again to all who replied - very much appreciated.
