### ISSUE TITLE
Mistake in example code

### ISSUE THREAD

**Issue by gregorylyons** [MicrosoftDocs/sql-docs#2083]
> --Memory optimized
> LE Syntax

Assuming its a typo from the previous section which displays

> --Disk-Based CREATE TABLE Syntax

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be5dfc7-5496-f8ec-072f-81132fe92054
* Version Independent ID: 634e3c60-d717-92ba-dd93-e3773edf2816
* Content: [CREATE TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/create-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by GitHubber17** [comment]
@gregorylyons - This request has 0 commits. Would you update the request to contain suggested changes? Otherwise, the request will be closed. Thank you

**Comment by gregorylyons** [comment]
Opened this via the website feedback functionality, and then decided to just PR a fix myself, so this can be closed =)
