### ISSUE TITLE
Missing letters

### ISSUE THREAD

**Issue by YanumVlad** [MicrosoftDocs/sql-docs#2086]
Always On availability groups relies on the Windows Server Failover Cluste(WSFC) 

Cluster (WSFC)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6df874b-bf51-b8de-9b24-d9301469dfaf
* Version Independent ID: f013e112-bef0-a20b-add8-5ed39bb254ef
* Content: [Combine a failover cluster instance with availability groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/failover-clustering-and-always-on-availability-groups-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/failover-clustering-and-always-on-availability-groups-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/failover-clustering-and-always-on-availability-groups-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @YanumVlad , thanks for contacting Microsoft! It may be faster for you to edit the content yourself via a Pull Request (PR). To do so, please do the following:

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Name your file change and provide a description, if necessary
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page

Thanks!

**Comment by MashaMSFT** [comment]
Thanks again for contacting Microsoft!  We've submitted a documentation change based on your suggestion, and it should be live at this point. Please let us know if there is anything more we can do for you? If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a wonderful rest of your day!
