### ISSUE TITLE
Information on how to get portable version

### ISSUE THREAD

**Issue by eiva** [MicrosoftDocs/sql-docs#2088]
Portable version "copy and run" is really nice for tests and development.
Especially in companies where developers unable to use containers...
Right now it is not "trivial" how to get a portable version for one of support os

**Comment by stevestein** [comment]
@eiva - thanks for the feedback!  This area is primarily for doc issues so I'm going to close this one. 

The best way to reach out to the team with issues, feedback, or suggestions is at [UserVoice](https://aka.ms/sqlfeedback).

Thanks!
