### ISSUE TITLE
Not working on MsSQL

### ISSUE THREAD

**Issue by thebruuu** [MicrosoftDocs/sql-docs#2089]
Hi,
I applied the instructions to my MsSql 2017 instance (standard edition), language 1033, and the result of sys.dm_fts_parser is unchanged... I expected to have just one Exact Match ... I get 5 Exact Match and 2 Noise Word 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9acba3d2-7e2d-4f02-9e6a-fc5cad0abcb7
* Version Independent ID: 50cf7327-b676-ddd7-6525-09a09c828b93
* Content: [Customize the Behavior of Word Breakers with a Custom Dictionary - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/search/customize-the-behavior-of-word-breakers-with-a-custom-dictionary?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/search/customize-the-behavior-of-word-breakers-with-a-custom-dictionary.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/search/customize-the-behavior-of-word-breakers-with-a-custom-dictionary.md)
* Product: **sql**
* Technology: **search**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by stevestein** [comment]
@thebruuu - thanks for the feedback! I've assigned this to the author @pmasl 

Thanks!

**Comment by thebruuu** [comment]
Any news on that, Stevestein?

**Comment by pmasl** [comment]
@thebruuu you mean you followed the instruction on the Sharepoint documentation link?

**Comment by WilliamAntonRohm** [comment]
@thebruuu -- as this issue 2089 seems dormant, I am closing it now.  If you have further questions, feel free to @ mention to continue this conversation.

CC: @pmasl  @MikeRayMSFT (ms.reviewer)
