### ISSUE TITLE
Clarify that the table value constructor limit only applies to a direct insert statement

### ISSUE THREAD

**Issue by mburbea** [MicrosoftDocs/sql-docs#2090]
The TVC limit of 1000 rows only applies to a direct insert statement. Wrapping the statement in  a select removes said limit. The documentation makes it sound like the limit is everywhere. I've seen even experts cite this as a potential error vector.
```sql
declare @sql varchar(max) ='declare @t table(i int)
insert into @t
values '+stuff(replicate(',(1)',1001),1,1,'')
exec (@sql)
go
declare @sql varchar(max) ='declare @t table(i int)
insert into @t
select _
from(
values '+stuff(replicate(',(1)',1001),1,1,'')
+') a(_)'
exec (@sql)
```
Yields an error on the first statement followed by 1001 rows affected. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b0d920d-fb22-6165-c7b4-bbcd5792e971
* Version Independent ID: 7b7f03a6-22fe-203e-655d-7f464960badc
* Content: [Table Value Constructor (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/table-value-constructor-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/queries/table-value-constructor-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/table-value-constructor-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
@mburbea - Thanks Michael! Let me verify this and make the changes if needed.

**Comment by srutzky** [comment]
@VanMSFT Don't worry about this issue. I am in the process of updating that page. I just published the following with my test cases:

[Maximum Number of Rows for the Table Value Constructor](https://sqlquantumleap.com/2019/05/09/maximum-number-of-rows-for-the-table-value-constructor/)

@mburbea Thanks again for pointing this out.

**Comment by VanMSFT** [comment]
Thanks @srutzky!

**Comment by srutzky** [comment]
FYI: I have submitted PR #2115 with the changes requested here and a few other improvements.

**Comment by VanMSFT** [comment]
Hey @mburbea! Thanks again for this submission, and bringing this issue to our attention. Since Solomon has made edits to the documentation, and I have gone ahead and approved those changes, we'll close this issue. If you see any problems, please let us know. We appreciate your help and feedback on our documentation gaps. Thanks!
