### ISSUE TITLE
Typo for Example B

### ISSUE THREAD

**Issue by ByronBarton** [MicrosoftDocs/sql-docs#2091]
Should be:
SELECT SalesOrderID, OrderDate,   
    OrderDate AT TIME ZONE 'Pacific Standard Time' AS OrderDate_TimeZonePST,  
    OrderDate AT TIME ZONE 'Central European Standard Time' AS OrderDate_TimeZoneCET  
FROM Sales.SalesOrderHeader;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8b3b24-5a50-6b88-277a-e8ce528b49b2
* Version Independent ID: ed560876-5e84-cb31-1bd4-65b3b0e5da8b
* Content: [AT TIME ZONE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/at-time-zone-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/queries/at-time-zone-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/at-time-zone-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by stevestein** [comment]
@ByronBarton - thanks for the feedback! I've assigned this to the author @VanMSFT 

Thanks!

**Comment by VanMSFT** [comment]
Hi @ByronBarton! Thank you so much for catching this! We really appreciate your feedback, and helping us with the documentation. I have made the changes to fix the typo, and they will appear live soon. I'll go ahead and close this request now, but if you have any concerns, please let us know. Thanks again!

https://github.com/MicrosoftDocs/sql-docs-pr/pull/10605
