### ISSUE TITLE
Some set_options are invalid for 2017

### ISSUE THREAD

**Issue by chojrak11** [MicrosoftDocs/sql-docs#2092]
It seems you have renamed some options in SQL Server 2019, e.g. DISABLE_INTERLEAVED_EXECUTION_TVF has become INTERLEAVED_EXECUTION_TVF. I'm viewing this page for SQL Server 2017 and I already see the set options for 2019. Trying to follow this page to change database scoped configurations gives me syntax errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40d08d20-a910-1226-c65d-408992ad871d
* Version Independent ID: 321ee79c-fc7e-513e-fecd-a38ab8e264c0
* Content: [ALTER DATABASE SCOPED CONFIGURATION (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/alter-database-scoped-configuration-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-database-scoped-configuration-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by stevestein** [comment]
@chojrak11  - thanks for the feedback! I've assigned this to the author @CarlRabeler 

Thanks!

**Comment by WilliamAntonRohm** [comment]
@CarlRabeler -- please process this issue 2092.

**Comment by CarlRabeler** [comment]
This was addressed on 5/22/2019 
#please-close
