### ISSUE TITLE
Specify SSMS version required

### ISSUE THREAD

**Issue by sqlchicken** [MicrosoftDocs/sql-docs#2093]
Please specify what version of SSMS this feature is supported in. Also it would be helpful to add a piece talking about where this metadata is stored. I assume it's stored in master database when you run it against the instance, since you use sys. procedure to query the data but would be nice to have it explicitly documented. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34863695-cd07-1260-4fea-66738c5fa80a
* Version Independent ID: 4c01015d-9c1d-db8e-84f5-379ffc5d5133
* Content: [SQL Data Discovery & Classification - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/sql-data-discovery-and-classification?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/sql-data-discovery-and-classification.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/sql-data-discovery-and-classification.md)
* Service: **sql-database**
* GitHub Login: @giladm
* Microsoft Alias: **giladm**

**Comment by stevestein** [comment]
@sqlchicken  - thanks for the feedback! If you search through the SSMS release notes you can see when support was added.

I've assigned this to the author @giladmit for clarification.

Thanks!

**Comment by MightyPen** [comment]
@stevestein Hi Steve, Ideally you can help @giladmit get this aging SSMS-related Issue 2093 processed and closed.

@markingmyname (also works on SSMS)

**Comment by giladmit** [comment]
adding @ronitr @salexu as I am no longer part of this product group

**Comment by salexu** [comment]
+ @Michal Bar<mailto:Michal.Bar@microsoft.com>, our new PM

**Comment by VanMSFT** [comment]
Following up with Michal

**Comment by MightyPen** [comment]
@ronitr @VanMSFT Hello, This aging Issue 2093 is now assigned to each of you.
Maybe Ronit can suggest an answer or a documentation change, and maybe Van can implement the change (and finish the mechanical processing of this Issue).

If a PR is created to fix this Issue, please put a link to the Issue in the PR, and vice versa.
Thanks.
CC: @sqlchicken

**Comment by ronitr** [comment]
Hi,
Data classification is available in SSMS as of SSMS 17.5 - @VanMSFT  - perhaps you can add this to the doc?
As to the question on where metadata is stored - there is a whole section in the article on this talking about how it is stored in Extended Properties, so I'm not sure what is missing.
https://docs.microsoft.com/en-us/sql/relational-databases/security/sql-data-discovery-and-classification?view=sql-server-2017#subheading-3
BTW @Michal Bar <Michal.Bar@microsoft.com> should indeed own this content from now on.
Thx
--Ronit.

**Comment by VanMSFT** [comment]
Thanks @ronitr! I added the supported SSMS version to the doc, and changed the author to Michal.

https://github.com/MicrosoftDocs/sql-docs-pr/pull/10775

@sqlchicken - Please let us know if you have any concerns. If this issue has been answered, I will go ahead and close this thread. Thanks for the doc suggestion!

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- I am closing this Issue #2093 now as it has been addressed.
