### ISSUE TITLE
Database Diagram Missing In ssms V18.0

### ISSUE THREAD

**Issue by devrakeshkumar** [MicrosoftDocs/sql-docs#2094]
Any alternate solution to generate db diagram in ssms V18.0 as I see database diagram option is missing in this version .

**Comment by stevestein** [comment]
@devrakeshkumar - thanks for the feedback! 

Adding @Matteo-T and @dnethi who might have some suggestions, but this area is primarily for specific doc issues so I'm going to close this one. The best way to reach out to the team with issues, feedback, or suggestions is at [UserVoice](https://aka.ms/sqlfeedback).

Thanks!
