### ISSUE TITLE
Images with Dark Mode aren't readable

### ISSUE THREAD

**Issue by Phritzy** [MicrosoftDocs/sql-docs#2104]
Can't read the images when using dark mode. The images are using a transparent background instead of white.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e49268-9863-3be2-218c-c472fe6f3711
* Version Independent ID: b104aa79-5b21-cd77-f24e-71a9fd93cf36
* Content: [A Guide to Query Processing for Memory-Optimized Tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/a-guide-to-query-processing-for-memory-optimized-tables?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/in-memory-oltp/a-guide-to-query-processing-for-memory-optimized-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/a-guide-to-query-processing-for-memory-optimized-tables.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by VanMSFT** [comment]
@Phritzy - Thanks Mark! We appreciate you pointing this out. I'll go ahead and change the images.

@MightyPen - https://github.com/MicrosoftDocs/sql-docs-pr/pull/10164

**Comment by VanMSFT** [comment]
Changes are merge and will go live tomorrow. Go ahead and close when ready. Thanks!

**Comment by MightyPen** [comment]
@Phritzy Hi Mark,  The problem you are reporting on is a sudden problem that has arisen in numerous cases.  So we have a couple people who are figuring out what happened, and who should implement a broad fix.
Therefore, I am Closing this valid Issue 2104, as it has plenty of attention now.  :-) 
Thank you.
