### ISSUE TITLE
Lock conflicts table image is degraded

### ISSUE THREAD

**Issue by perennialmind** [MicrosoftDocs/sql-docs#2105]
The lock conflicts table image on this page appears to have been sized down from the image used on previous pages for SQL Server 2008, 2012, and 2014. The new, smaller image (512x408) is less legible than the previous image (646x524).

SQL Server 2017 locking page, "Lock Compatibility" section and image URLs
```
https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-2017#lock_compatibility
https://docs.microsoft.com/en-us/sql/relational-databases/media/lockconflicttable.png?view=sql-server-2017
```
SQL Server 2014 locking page, "Lock Compatibility" section and image URLs
```
https://docs.microsoft.com/en-us/sql/2014-toc/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-2014#lock-compatibility
https://docs.microsoft.com/en-us/sql/2014-toc/media/lockconflicttable.gif?view=sql-server-2014
```
SQL Server 2012 locking page, "Lock Compatibility" section and image URLs
```
https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-guides/jj856598(v=sql.110)#lock-compatibility
https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-guides/images/jj856598.lockconflicttable%28sql.110%29.gif
```
SQL Server 2008 R2 "Lock Compatibility" page and image URLs
```
https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms186396(v=sql.105)
https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/images/ms186396.lockconflicttable%28en-us%2csql.105%29.gif
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dae81d65-f7b9-7a97-7fe7-30775f815e5b
* Version Independent ID: d4d339e7-48d7-d159-eb59-13bdedc25b4c
* Content: [SQL Server Transaction Locking and Row Versioning Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-2017)
* Content Source: [docs/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by stevestein** [comment]
@perennialmind - Thanks for the feedback! 

If you want to take a try at fixing the image, check out our info on [how to contribute to the SQL docs](https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute)!

I've assigned this to the author, @rothja.

Thanks!

**Comment by stevestein** [comment]
@perennialmind, @rothja  - 
The problem you are reporting on is a sudden problem that has arisen in numerous cases. We have a couple people who are figuring out what happened, and who should implement a broad fix.
Therefore, I am Closing this valid Issue 2105, as it has plenty of attention now. :-)
Thank you.
