### ISSUE TITLE
That's great.. BUT......

### ISSUE THREAD

**Issue by jstockley** [MicrosoftDocs/sql-docs#2106]
It doesn't make importing flat files into Existing tables any easier. Only works for new tables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d89ecc7f-4705-dabe-9f70-2070d4aa19c9
* Version Independent ID: 9c991bd5-535c-03b5-d810-c1b2ca7e7cb4
* Content: [Import Flat File to SQL - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/import-flat-file-wizard?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/import-export/import-flat-file-wizard.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/import-flat-file-wizard.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by stevestein** [comment]
@jstockley - Thanks for the feedback! We'll add info to the top of the article clarifying it imports into new tables only. I created an internal item item to track: 1530084. I'm going to go ahead and close this issue.

Thanks!
