### ISSUE TITLE
Azure SQL and DTC?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/sql-docs#2107]
Please confirm that **Azure SQL** Database supports Microsoft Distributed Transaction Coordinator (MS **DTC**).
   
**In this article** it also say Azure SQL supports DTC: [Supporting Distributed Transactions](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-ole-db-transactions/supporting-distributed-transactions?view=sql-server-2017)

But here it say that Azure SQL does NOT support DTC: [Feature comparison: Azure SQL Database versus SQL Server](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-features)

And here it say: [ _"Since MSDTC is not available for Platform-as-a-Service application in Azure..."_ ](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-elastic-transactions-overview)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9134176c-f048-ad0d-ced6-99e8214350cb
* Version Independent ID: df2f6e46-bd91-3018-a6b7-de6e283df9ab
* Content: [Performing Distributed Transactions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/odbc/performing-transactions-distributed-transactions?view=sql-server-2017)
* Content Source: [docs/relational-databases/native-client/odbc/performing-transactions-distributed-transactions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/native-client/odbc/performing-transactions-distributed-transactions.md)
* Product: **sql**
* Technology: **native-client**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
@sarvesh-s Hi Sarvesh,  Please, can you tell us about how DTC is or is not supported on Azure SQL Database, DW, versus SQL Server on-premises?

CC: @MightyPen

**Comment by sarvesh-s** [comment]
Azure SQL DB supports distributed transactions without using msdtc. Only .net surface area is supported using TransactionScope() from C# code. Native c++ odbc drivers or linked servers using t-sql or Jdbc drivers are not supported on Azure SQL DB service.

**Comment by sarvesh-s** [comment]
On premises SQL supports msdtc as-is. 
DW does not support it.

**Comment by Bartolomeus-649** [comment]
![image](https://user-images.githubusercontent.com/7513795/57500009-0004ca00-72e2-11e9-9c75-3206af406ada.png)
https://docs.microsoft.com/en-us/sql/relational-databases/native-client-ole-db-transactions/supporting-distributed-transactions?view=sql-server-2017

![image](https://user-images.githubusercontent.com/7513795/57500098-4d813700-72e2-11e9-8d72-f5ee98de3aae.png)
https://docs.microsoft.com/en-us/sql/relational-databases/native-client/odbc/performing-transactions-distributed-transactions?view=sql-server-2017

@sarvesh-s The documentation does not agree with you

**Comment by MightyPen** [comment]
@Bartolomeus-649 This Issue 2107 is now fixed by Pull Request 10195 (in our private repo).
In general, before the PR 10195, the article spoke misleadingly about the relationship between MSDTC and Azure SQL Database.  The article implied that MSDTC applied to Azure SQL DB.
The article as revised by PR 10195 clarifies that distributed transactions can apply to Az SQL DB, just not by using MSDTC.
Thank you for submitting this issue.  Given PR 10195, it is time to close this issue, as fixed.
(The @ notification mechanism continues to work even after an issue is closed.)

@sarvesh-s Thank you very much for you informative and timely response.
