### ISSUE TITLE
sp_query_store_consistency_check doesn't exist in SQL 2016

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/sql-docs#2109]
"Verify Query Store is collecting query data continuously" section suggests running the `sp_query_store_consistency_check` procedure if the query store gets corrupted, but this sproc does not exist in SQL 2016, only SQL 2017 and later.

See also: https://dba.stackexchange.com/questions/237521/trying-to-repair-query-store-but-sp-query-store-consistency-check-does-not-exis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155bfbc5-9c63-32c6-9d06-a9b3cdb4c60e
* Version Independent ID: c854b2de-e509-e320-8151-67d690d486ed
* Content: [Best Practice with the Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/best-practice-with-the-query-store?view=sql-server-2016#Verify)
* Content Source: [docs/relational-databases/performance/best-practice-with-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/best-practice-with-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by stevestein** [comment]
- thanks for the feedback! I've assigned this to the author @julieMSFT 
Thanks!

**Comment by julieMSFT** [comment]
Hi @IanKemp, Thank you for bringing this to our attention. I will be updating the documents to state that sp_query_store_consistency_check only works with SQL version 2017 and later. For a 2016 version that is in an error state the only possible mitigation would be to run the following which will clear out the data:
ALTER DATABASE [YourDatabaseName] 
SET QUERY_STORE CLEAR ALL;

Please let me know if you need anything further, or if I can proceed with closing out this Git Issue. Thanks!

**Comment by julieMSFT** [comment]
#10229

**Comment by julieMSFT** [comment]
Hi @IanKemp, I have updated the documents to reflect that `sp_query_store_consistency_check` only works for SQL 2017 and later. The updates will go live later today. I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!

**Comment by maadityo** [comment]
hi, may i know what is the impact of "sp_query_store_consistency_check" ? does it will block the transaction or what is the impact? i have search but found nothing. 
thanks

**Comment by julieMSFT** [comment]
@TwoUnder Matt, can you comment on this customer question?

**Comment by pmasl** [comment]
@maadityo this is a recovery sp and can only execute against a database that has the Query Store feature disabled, so shouldn't affect user workload.
