### ISSUE TITLE
textimage_on "0 is the default value"

### ISSUE THREAD

**Issue by piratejon** [MicrosoftDocs/sql-docs#2112]
I am not clear on "0 is the default value" in this paragraph from the "textimage_on" note:

Varchar(max), nvarchar(max), varbinary(max), xml and large UDT values are stored directly in the data row, up to a limit of 8,000 bytes and as long as the value can fit the record. If the value does not fit in the record, a pointer is sorted in-row and the rest is stored out of row in the LOB storage space. 0 is the default value.

Does that refer to the column value when we insert a row without specifying a value for a large string column? It seems odd it would take on a 0 instead of NULL (if I am understanding correctly) for string types. Or does it mean something else here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be5dfc7-5496-f8ec-072f-81132fe92054
* Version Independent ID: 634e3c60-d717-92ba-dd93-e3773edf2816
* Content: [CREATE TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by stevestein** [comment]
@piratejon - thanks for the feedback! I've assigned this to the author @CarlRabeler 

Thanks!

**Comment by CarlRabeler** [comment]
@piratejon 0 is the default value, which indicates that all values are stored directly in the data row.

**Comment by CarlRabeler** [comment]
#please-close
