### ISSUE TITLE
sp_GetAppLock writes to the transaction log

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#2113]
There is no logical reason I can think of that requires sp_GetAppLock to write to the transaction log. This causes multiple issues (and is not mentioned in the documentation).

1/ excessive logs if you use this function to gate access to other resources
2/ extreme slowdown on servers with Always On when locking on the primary database.

The following script executes all locks in about 3 seconds on my i9 standalone database.

declare @i int = 0;
while @i &lt; 100000 BEGIN
	set nocount on;
	begin tran
		declare @locked int = 0;
		exec @locked = sp_getAppLock 'MyResource', 'Exclusive', 'Transaction'
		if @i % 1000 = 0 Begin
			print @i;
		end;
	rollback
	set @i +=1;
end 

Run multiple copies - all play well together, but you will see log file usage increase quickly (to about 6 megabytes/sec)

Then try running against a readonly database on an Always On Secondary. It still runs fast.
Then try running on a primary Always On database. It executes about 50 locks a second, instead of about 35,000.
Changing the database to async helps...

Please change the logic in sp_GetAppLock to be identical on primary and secondary server. I hope the secondary isn't logging at all, but I expect it to be logging in either TempDB or master...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfc5142-4589-ac67-69c2-65d7760719e4
* Version Independent ID: 02464294-1e91-30e6-8489-51ee2ee45a31
* Content: [sp_getapplock (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-getapplock-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-getapplock-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-getapplock-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@brettshearer - thanks for the feedback!  This area is primarily for doc issues so I'm closing this issue. The best way to reach out and report product issues and provide suggestions is at the [UserVoice ](https://feedback.azure.com/forums/908035-sql-server) site.

Thanks!
