### ISSUE TITLE
TEMPORAL_HISTORY_RETENTION option is not documented

### ISSUE THREAD

**Issue by chojrak11** [MicrosoftDocs/sql-docs#2118]
ALTER DATABASE ... SET TEMPORAL_HISTORY_RETENTION ON|OFF;
Is it intentional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d76ab6e-5a3d-94eb-26f9-b2805b35ea85
* Version Independent ID: 2ac43d27-c318-3e32-1e78-55229975eb4e
* Content: [ALTER DATABASE SET Options (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/alter-database-transact-sql-set-options.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-database-transact-sql-set-options.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@chojrak11 please clarify your question

**Comment by VanMSFT** [comment]
Hi @chojrak11! Thank you for bringing up this issue. I'm assigning this to @CarlRabeler to help investigate.

**Comment by CarlRabeler** [comment]
@chojrak11 temporal history retention is a feature of Azure SQL Database and not SQL Server (unless something changed recently). Do you have information that this capability is supported in SQL Server?

**Comment by chojrak11** [comment]
I got it running on SQL Server 2017 14.0.3076.1, don't know about older versions. This syntax worked for me. INFINITY option doesn't work

```
ALTER TABLE dbo.Product SET (
  SYSTEM_VERSIONING = ON (
    HISTORY_TABLE = dbo.ProductHistory,
    DATA_CONSISTENCY_CHECK = OFF,
    HISTORY_RETENTION_PERIOD = 10 DAYS)  -- also MONTHS, YEARS
);
```

**Comment by CarlRabeler** [comment]
@chojrak11 the option is INFINITE not INFINITY

Also, updating docs to state support for SQL Server 2017 and newer

**Comment by CarlRabeler** [comment]
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10266

**Comment by CarlRabeler** [comment]
#please-close

**Comment by chojrak11** [comment]
Thank you!

**Comment by CarlRabeler** [comment]
@chojrak11 thanks again for bringing this to our attention
