### ISSUE TITLE
2019-CTP2.1-ubuntu tagged images not working with Kubernetes deployment

### ISSUE THREAD

**Issue by NileshGule** [MicrosoftDocs/sql-docs#2119]
I tried following the steps in the document to [deploy ](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-kubernetes-deploy?view=sql-server-ver15) **SQL Server 2019 CTP 2.1** image on AKS cluster. The operator and the SQL Server CRDs get deployed correctly. But the services are unable to communicate with one another. The tags used in the [sql-server-example ](https://github.com/microsoft/sql-server-samples/tree/master/samples/features/high%20availability/Kubernetes)Github repo is not working. Investigating into the logs for MSSQL pod shows an error that **the evaluation period has expired**.

Do we need to pass any additional environment variable? The same steps work fine if I upgrade the tag to **2019-CTP2.2-ubuntu** instead of _2019-CTP2.1-ubuntu_

Refer to the attached screenshots.

![control panel overview](https://user-images.githubusercontent.com/1298374/57584414-a7b21000-750d-11e9-8934-bc4525d52bba.PNG)
![MSSQL initialize](https://user-images.githubusercontent.com/1298374/57584415-a84aa680-750d-11e9-9c5b-369e31ced897.PNG)
![MSSQL sqlserver](https://user-images.githubusercontent.com/1298374/57584416-a8e33d00-750d-11e9-84e7-0b35a8bd4ed9.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ebc3b9-aea4-0741-d4f3-88a599a0b357
* Version Independent ID: 72244521-eefe-8801-ca1e-1f25af221a97
* Content: [Deploy a SQL Server Always On availability group on a Kubernetes cluster - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-kubernetes-deploy?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/linux/sql-server-linux-kubernetes-deploy.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-kubernetes-deploy.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by VanMSFT** [comment]
Hi @NileshGule! Thanks for bringing this issue up. I'll assign this to @MikeRayMSFT to help verify the sample.

**Comment by NileshGule** [comment]
> Hi @NileshGule! Thanks for bringing this issue up. I'll assign this to @MikeRayMSFT to help verify the sample.

Thanks @VanMSFT. I have created a pull request by upgrading the tag to CTP2.2 from an existing tag. Waiting for the pull request to be approved and merged.

**Comment by MikeRayMSFT** [comment]
Hi @NileshGule - thank you for testing our content for preview software and providing this feedback. We will be updating soon. Including @SQLSourabh

**Comment by joseq-terawe** [comment]
Any word on fix? just tried to deploy and having same issues.

**Comment by NileshGule** [comment]
> Any word on fix? just tried to deploy and having same issues.

@joseq-terawe,  I am able to deploy the CTP2.2 version of the images. I was able to automate the steps which I blogged about https://www.handsonarchitect.com/2019/05/upgrade-sql-server-2017-to-2019-with-ha.html

Even the CTP 2.2. version of the images is coming toward an end for the evaluation period. Maybe its time to upgrade to CTP2.3 version.
