### ISSUE TITLE
Feature not available anymore

### ISSUE THREAD

**Issue by mturzynskigoyello** [MicrosoftDocs/sql-docs#2120]
That'd be nice to put some yellow background on the warning saying that the feature is not available anymore.. just lost half an hour to install management studio 18 just to find out it was rolled back

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94aa1791-17e9-40de-eb28-4410e26fe24d
* Version Independent ID: 4a9c6546-4d09-fb60-817e-c643d2c71bef
* Content: [Static Data Masking - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/static-data-masking?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/static-data-masking.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/static-data-masking.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @aliceku
* Microsoft Alias: **aliceku**

**Comment by aliceku** [comment]
Sorry about that, @mturzynskigoyello.  I added an "Important" box around the notice so it can be seen right away going forward.

**Comment by VanMSFT** [comment]
Hi @mturzynskigoyello! Thanks for bringing this issue up. We appreciate your input. If you have any questions on Alice's changes, please let us know. We will go ahead and close this issue as changes are reflected in the documentation.

**Comment by mturzynskigoyello** [comment]
Thanks! it indeed looks better :)
