### ISSUE TITLE
Very helpful

### ISSUE THREAD

**Issue by liaqatg** [MicrosoftDocs/sql-docs#2123]
I was trying to backup all databases on my local SQL Server 2008 R2 server and was struggling to get the PS script working. The issue seemed to be the required libraries were not loaded. After a couple of unsuccessful searches, I found this article, ran the above script and then my backup script and voila!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca91cbd9-efe5-1de5-7da6-6137b0437a3d
* Version Independent ID: 836f506c-0e26-8277-1a9f-451853e0d21b
* Content: [Load the SMO Assemblies in Windows PowerShell - SQL Server](https://docs.microsoft.com/en-us/sql/powershell/load-the-smo-assemblies-in-windows-powershell?view=sql-server-2017#feedback)
* Content Source: [docs/powershell/load-the-smo-assemblies-in-windows-powershell.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/load-the-smo-assemblies-in-windows-powershell.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@liaqatg - Thanks for the feedback! Glad the article assisted in accomplishing your task!

Thanks!
