### ISSUE TITLE
Compatiblity 100 to 110 differences

### ISSUE THREAD

**Issue by LarnuUK** [MicrosoftDocs/sql-docs#2124]
On [ALTER DATABASE (Transact-SQL) Compatibility Level](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-compatibility-level?view=sql-server-2017), the difference between compatibility 100 and 110 is listed under the heading [Differences Between Lower Compatibility Levels and Levels 110 and 120](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-compatibility-level?view=sql-server-2017#differences-between-lower-compatibility-levels-and-levels-110-and-120). Although these changes do apply to 120 as well, it makes finding the changes between 100 and 110; especially when the table below then lists the 2 columns as **Compatibility-level setting of 100 or lower** and **Compatibility-level setting of at least 110** (which is how the other tables are listed),

This appears to just need a simple heading change to *"Differences Between Lower Compatibility Levels and Levels 100 and 110"*.

**Comment by VanMSFT** [comment]
Hi @LarnuUK! Thank you for bringing this issue up. I'm assigning this issue to my colleague, Carl to see if clarification is needed.

cc: @CarlRabeler

**Comment by CarlRabeler** [comment]
@LarnuUK fixing now - thanks.

**Comment by CarlRabeler** [comment]
#please-close
