### ISSUE TITLE
Example query doesn't run on SQL DW in Azure Data Studio/SSMS 17.9.1 without putting brackets around [label]

### ISSUE THREAD

**Issue by mlongoria** [MicrosoftDocs/sql-docs#2130]
When I copy and paste the query listed under "A. Listing all classified columns and their corresponding classification" and execute it on an Azure SQL DW (Gen 2 or Gen 1), it throws an error: "Parse error at line: 3, column: 5: Incorrect syntax near 'Label'.". If I change Label to [Label] the query runs fine. Is label now a keyword? Do I need to update a driver or library somewhere? I consistently get this result in SSMS 17.9.1 as well as Azure Data studio 1.7.0. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7199df2d-4950-2533-791c-4fc134ce8eed
* Version Independent ID: 0b52e407-d9be-0ebd-2414-6a2478d999c3
* Content: [sys.sensitivity_classifications (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-sensitivity-classifications-transact-sql?view=azuresqldb-current#examples)
* Content Source: [docs/relational-databases/system-catalog-views/sys-sensitivity-classifications-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-sensitivity-classifications-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @vainolo
* Microsoft Alias: **arib**

**Comment by VanMSFT** [comment]
Hello @mlongoria! Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. I'm assigning my colleague, Julie to take a look.

**Comment by julieMSFT** [comment]
Hi @mlongoria, Thank you for your question. Label is a key word for Azure SQL DW and it is documented [here](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=azure-sqldw-latest). I will update the example in sys.sensitivity_classifications (Transact-SQL) - SQL Server to reflect this. Thank you again for bringing this to our attention.

**Comment by julieMSFT** [comment]
#10209

**Comment by julieMSFT** [comment]
[PR](https://github.com/MicrosoftDocs/sql-docs-pr/pull/10209)

**Comment by julieMSFT** [comment]
Hi @mlongoria, the changes have been made to the documentation. You will be able to see the changes in the next 24 hours. I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!
