### ISSUE TITLE
missing (

### ISSUE THREAD

**Issue by KrunchMuffin** [MicrosoftDocs/sql-docs#2131]
in the 5th code block on the page you have a line like this
skills nvarchar(max) '$.info.skills' as json) &lt;&lt;&lt;&lt;&lt; 
but that ending ) has no beginning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 991167bc-4e0e-1fc8-d0bb-f282b51b3321
* Version Independent ID: 0b5cf834-d452-dd57-d51d-268083011e33
* Content: [Work with JSON data in SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/json/json-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/json-data-sql-server.md)
* Product: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by VanMSFT** [comment]
Hello @KrunchMuffin! Thank you so much for your help on this! I have gone ahead and added the missing parenthesis to the mentioned code block. Changes should take place this afternoon. If you have any questions, please feel free to let us know. We will go ahead and close this. Thank you again for helping us correct the documentation!

https://github.com/MicrosoftDocs/sql-docs-pr/pull/10204
