### ISSUE TITLE
Wrong menu path for this page?

### ISSUE THREAD

**Issue by lukaseder** [MicrosoftDocs/sql-docs#2133]
Why is UPDATE in the Queries menu, whereas DELETE, INSERT, MERGE are in the Statements menu? Doesn't seem to make sense to me...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc5aa35c-e2c9-1cce-0026-6aae93b30504
* Version Independent ID: 85e9daaa-2af1-95c6-8795-75976c36ccba
* Content: [UPDATE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/queries/update-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/update-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @lukaseder! Thank you for contacting Microsoft and providing your feedback to our documentation! I'm assigning my colleague, Gene to take a look at the table of contents to see if we can clarify DML operations locations.

cc: @MashaMSFT

**Comment by MightyPen** [comment]
@lukaseder Hi Lukas, PR 10429 has been checked in to fix this TOC Issue 2133. Your Issue had a fair point and a legit argument, so we fixed it.  :-)
The change should appear on live Docs within 24 hours.
I am now closing this Issue.  Thank you.

**Comment by lukaseder** [comment]
Thanks very much, @MightyPen and @VanMSFT.

As an aside: I really like this docs/github integration! Very well done, Microsoft :)
