### ISSUE TITLE
No where specified that a semi colon is mandatory before throw keyword

### ISSUE THREAD

**Issue by vibs2006** [MicrosoftDocs/sql-docs#2134]
I wasted quite a lot of time in identifying the cause of why my throw statement was not working. As usual with the help of StackOverflow, I discovered that whenever throw statement is called then the statement before that keyword should be terminated by a SEMICOLON. Can the author tell me where is this mentioned in this documentation page anywhere!? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525698d4-0465-5fe0-f09d-dfad8b8413e6
* Version Independent ID: 2ece841a-2d51-542e-6c2b-9d36ffe54202
* Content: [THROW (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/throw-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/language-elements/throw-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/throw-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by VanMSFT** [comment]
Hello @vibs2006! Thank you for submitting this Issue. The answer you are looking for is in the Remarks section:

https://docs.microsoft.com/en-us/sql/t-sql/language-elements/throw-transact-sql

![image](https://user-images.githubusercontent.com/40007119/57711113-ff8e6b00-7622-11e9-9e83-bd6eac69dfa4.png)
