### ISSUE TITLE
User only install support for SSMS

### ISSUE THREAD

**Issue by vmvmpvm** [MicrosoftDocs/sql-docs#2135]
Can SSMS support user only install (i.e. without requiring Admin/Elevated Privileges)?

**Comment by VanMSFT** [comment]
Hello @vmvmpvm! Thank you for submitting this question! I'm assigning this to my colleague, Mark who will help answer your SSMS installation question.

https://docs.microsoft.com/sql/ssms/sql-server-management-studio-ssms

@markingmyname - Please update the SSMS documentation with permission requirements
cc: @stevestein

**Comment by markingmyname** [comment]
Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

**Comment by markingmyname** [comment]
Hi @vmvmpvm,

You cannot SSMS without requiring Admin/Elevated privileges.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
