### ISSUE TITLE
"To modify the properties of an index in Object Explorer" - Properties is not available in SSMS for Azure SQL Database

### ISSUE THREAD

**Issue by LuisGonzalezLT** [MicrosoftDocs/sql-docs#2137]
Right-Clicking on an index within an Azure SQL Database does not provide a Properties selection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 123d4429-8bbe-c1d0-260e-359e0c032bdd
* Version Independent ID: 22a9b1a0-264b-afe6-405b-7d1ce31b45a6
* Content: [Set Index Options - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/set-index-options?view=sql-server-2017)
* Content Source: [docs/relational-databases/indexes/set-index-options.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/set-index-options.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by VanMSFT** [comment]
Hello @LuisGonzalezLT - Thanks for bringing this issue up! You're right. I'm assigning this to my colleague, Mike for any changes.

**Comment by MikeRayMSFT** [comment]
@LuisGonzalezLT - we're looking into this. Thank you for raising it.

**Comment by MikeRayMSFT** [comment]
My colleague, @markingmyname will take a look at this.

**Comment by markingmyname** [comment]
Hi @LuisGonzalezLT,

Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

**Comment by markingmyname** [comment]
Hi @LuisGonzalezLT,

We are aware of this issue and are discussing how to solve it.

We have no current ETA for when this will be completed.

Thank you for adding more visibility to this.

Have a great weekend!

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
