### ISSUE TITLE
T-SQL reference moved within "Backup & restore" in TOC

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/sql-docs#2144]
At [Transact-SQL Reference (Database Engine)](https://docs.microsoft.com/en-us/sql/t-sql/language-reference?view=sql-server-2017), the table of contents and the breadcrumb bar show "Docs / SQL / Business continuity / Backup & restore / How-to / Configuration / Manage suspect_pages table" as the selected article.

At [CREATE TABLE (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-2017), the table of contents and the breadcrumb bar show "Docs / SQL / Business continuity / Backup & restore / Overview / Interoperability & Coexistence" as the selected article.

In both cases, the misleading TOC makes it difficult to navigate to other reference pages.

I note that &lt;https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/toc/toc.yml&gt; lacks `href` properties for "Manage suspect_pages table" and "Interoperability & Coexistence". Perhaps that confuses the docs build somehow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c90a9561-bef5-25e8-e672-ed0d4493a383
* Version Independent ID: 16c705c1-55be-d339-8326-51d57cb0fd69
* Content: [Transact-SQL Reference (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-reference?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/t-sql/language-reference.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-reference.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by KalleOlaviNiemitalo** [comment]
Seems to be working now.

**Comment by MashaMSFT** [comment]
Hi @KalleOlaviNiemitalo , thank you so much for bringing this to our attention! Yes, this was a bug that was inadvertently introduced into the TOC, and has since been fixed :) We apologize for the inconvenience, and appreciate you notifying us! 

Hope you have a wonderful rest of your day :)
