### ISSUE TITLE
The 'Download PDF 

### ISSUE THREAD

**Issue by Phil-Factor** [MicrosoftDocs/sql-docs#2147]
Clicking on the Download PDF tab downloads nothing, sadly, into Chrome's pdf viewer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7905a22-ac02-266e-ae4b-75e86d519cbe
* Version Independent ID: 3f56e8cf-abde-14fe-1b74-82e8a87df274
* Content: [sp_validname (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-validname-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-validname-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-validname-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by MashaMSFT** [comment]
Hi @Phil-Factor , thanks for contacting Microsoft! I'm sorry to hear the PDF download isn't working for you.  I checked the page you're referring to, and I was able to produce a PDF download in Chrome. Is it possible there may be some browser settings that's preventing it from working on your end?

![image](https://user-images.githubusercontent.com/32783170/57892123-ae34d600-77f2-11e9-8329-127ce5ea4805.png)

Thanks!
