### ISSUE TITLE
can we declare this 'upgrade replicated database' process also applied to patch SQL Server not only upgrade?

### ISSUE THREAD

**Issue by msftsandysun** [MicrosoftDocs/sql-docs#2154]
We encountered a few cases that if we don't follow this article steps when apply patch to SQL Server in replication, we may still encounter error like 'The process could not execute 'sp_replcmds', can we declare this  'upgrade replicated database' process not only apply to SQL Server upgrade but also apply to SQL Server patching? Thanks a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dbb2d0f-c435-74e6-384b-0b5137de9ff3
* Version Independent ID: a8489139-6d4c-223e-e39a-99b7510ef228
* Content: [Upgrade Replicated Databases - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/upgrade-replicated-databases?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/install-windows/upgrade-replicated-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/upgrade-replicated-databases.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @msftsandysun , thanks for contacting Microsoft! Sorry, are you just asking if this process should be used for when patching SQL Server, or are you asking to have this added to the documentation? If the former, yes. 

If the latter, it may be faster for you to edit the content yourself via a Pull Request (PR). To do so, please do the following:

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Name your file change and provide a description, if necessary
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page

I hope that helps and please let me know if I can be of further assistance.

Thanks!

**Comment by MashaMSFT** [comment]
Hi @msftsandysun, 

Thanks again for contacting Microsoft!  We've submitted a documentation change based on your suggestion, and it should be live at this point. Please let us know if there is anything more we can do for you? If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a wonderful rest of your day!

**Comment by msftsandysun** [comment]
Hi @MashaMSFT,

Thanks so much for your help on adjusting the documentation content. I have noticed the change. Please feel free to close the Git Issue.

Thanks again and Best Regards
