### ISSUE TITLE
Run_Status = 4 (In Progress) - records are never present in sysjobhistory with this run_status

### ISSUE THREAD

**Issue by Piquet65** [MicrosoftDocs/sql-docs#2155]
This issue may be more of a bug with the product than an issue with the page. Either way the doco and product (SQL 2014 thru to SQL 2017) do not agree. Jobs / steps that are currently "In Progress" DO NOT have a record present in msdb.dbo.sysjobhistory with run_status=4. This appears to be true for single step jobs, multi-step jobs for SQL Server 2017 back to (at least) SQL Server 2014.
Ideally the documentation would be correct and the "bug" corrected to ensure "In Progress" records are present in this table. If on the other hand the omission of in progress records in this table is "by design", then the documentation here should be updated to REMOVE the details regarding run_status 4 and replaced with a comment/note indicating that this table does not hold any records for jobs/steps currently in progress.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1188cb1-de0a-ce57-5baf-40ae903b41ef
* Version Independent ID: 86dc9874-a01d-e26f-d13b-3785ffd5c497
* Content: [dbo.sysjobhistory (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/dbo-sysjobhistory-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-tables/dbo-sysjobhistory-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/dbo-sysjobhistory-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by VanMSFT** [comment]
Thank you @Piquet65 for bringing up this issue. We appreciate your feedback. I'm assigning this issue to my colleague, Steve to help clarify.

**Comment by Jonathan811** [comment]
Yeah, that is a pain.......have to look at sysjobactivity to find current executing jobs.

Would be nice if sysjobhistory got updated when jobs start.....

**Comment by stevestein** [comment]
@Piquet65 - Thanks for raising this issue!

The documentation was incorrect and has been updated.

**Comment by stevestein** [comment]
#please-close
