### ISSUE TITLE
about run_duration 

### ISSUE THREAD

**Issue by jeffrey-yao** [MicrosoftDocs/sql-docs#2158]
the document should detail about what if run_duration is more than 24 hrs or 100 hrs? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1188cb1-de0a-ce57-5baf-40ae903b41ef
* Version Independent ID: 86dc9874-a01d-e26f-d13b-3785ffd5c497
* Content: [dbo.sysjobhistory (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/dbo-sysjobhistory-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-tables/dbo-sysjobhistory-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/dbo-sysjobhistory-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by VanMSFT** [comment]
Hello @jeffrey-yao! Thank you for providing your feedback on our documentation. I'm adding my colleague, Steve to help clarify.

**Comment by stevestein** [comment]
@jeffrey-yao - Thanks for the feedback! 

I'll have to investigate this. Are you seeing incorrect values for long-running jobs?

**Comment by jeffrey-yao** [comment]
Hi @stevestein , I tested it a job running more than 24 hrs, but less than 100 hrs, the value is still correct. But given the current format, i.e. HHMMSS, if a job is running longer than 100 hrs (i.e. 4+ days), what the value can be? truncated? I will do a test and update it here.

**Comment by fpugh** [comment]
Via - 

select run_duration
, STUFF(STUFF(STUFF(RIGHT(REPLICATE('0',8) + CAST(run_duration as VARCHAR(8)), 8), 3, 0, ':'), 6, 0, ':'), 9, 0 , ':') as RunDuration
from msdb.dbo.sysjobhistory
order by run_duration desc

We have:
run_duration
3674505	03:67:45:05
3674505	03:67:45:05
3632855	03:63:28:55
3632854	03:63:28:54
3630357	03:63:03:57

**Comment by fpugh** [comment]
Sorry for extra post - can't find an 'edit' option:
In post above - paying attention to the results at the bottom - it does not make sense that something would run more than 24 hours without overflowing into the next day - how do we have 3 days and 64 hour run times if this is really DD:HH:MM:SS format?

It would seem that just providing a single simple base unit - total seconds run time - for example would be more effective to consume and use.

**Comment by msebolt** [comment]
Taking a look at the issue.

**Comment by msebolt** [comment]
Sorry for the delay, the article's example shows how to display run duration as days, hours, minutes, seconds, all of which are supported.
