### ISSUE TITLE
SQL Server 2017, compatibility 1400 needs a different connection string

### ISSUE THREAD

**Issue by leehbi** [MicrosoftDocs/sql-docs#2162]
I had to amend the connection string and cube name to get this package working with 1400 compatible tabular cubes as follows:

cnnstr &lt;- "Data Source=localhost;Provider=MSOLAP;Initial Catalog={cube name}"
...
cube(qry) &lt;- "Model"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108c0c82-0821-9492-368c-9d865bc2d71b
* Version Independent ID: a5a3cde0-b2a9-dc3c-7ebc-f17e9085966f
* Content: [How to create MDX queries in R using olapR - SQL Server Machine Learning Services - SQL Server](https://docs.microsoft.com/en-us/sql/advanced-analytics/r/how-to-create-mdx-queries-using-olapr?view=sql-server-2017#feedback)
* Content Source: [docs/advanced-analytics/r/how-to-create-mdx-queries-using-olapr.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/r/how-to-create-mdx-queries-using-olapr.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@leehbi Thank you for your information. I am currently looking into the issue and will keep you updated.

**Comment by dphansen** [comment]
@leehbi We have added the Initial Catalog to the example code. It will be published tomorrow. Thanks you.

**Comment by leehbi** [comment]
There’s one other change - qry(cube) = ‘model’ for 1400 cubes - thanks for amending doc - I almost thought OlapR didn’t support tabular cubes.

**Comment by dphansen** [comment]
The example in the article uses an existing cube called "Analysis Services Tutorial". If you don't have that cube, you need to specify one you have. Thanks again for your contribution @leehbi - really appreciate it.
