### ISSUE TITLE
Code examples incorrect in RMO section

### ISSUE THREAD

**Issue by EnjoyinMoss** [MicrosoftDocs/sql-docs#2163]
The ServerConnection lines in the RMO code examples are incorrectly specifying subscriberName as the variable being passed when it should be publisherName.  This is reinforced by the preceding code comment:  //Create a connection to the Publisher.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4aacac09-b7ac-5338-6525-7c7455eead0d
* Version Independent ID: e4894ef4-a9b3-ac20-2fad-56927ed82304
* Content: [Create a Push Subscription - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/create-a-push-subscription?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/replication/create-a-push-subscription.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/create-a-push-subscription.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MikeRayMSFT** [comment]
@EnjoyinMoss - thank you for pointing this out. @MashaMSFT will take a look shortly if we have questions.

If you're interested, you can submit an update to the docs directly. Go to http://aka.ms/editsqldocs. You'll need a github account.

**Comment by MashaMSFT** [comment]
Hi @EnjoyinMoss , thanks for bringing this to our attention! Looks like you are correct, and it should be PublisherName. I have created an item to track this work (and fix) internally. Thanks for contacting Microsoft!

**Comment by msebolt** [comment]
Hi @MashaMSFT What is the item number created?

Since there is a work item created for this, the issue should be closed.  Gene, has made the request.

**Comment by MashaMSFT** [comment]
Hi @EnjoyinMoss , thanks again for bringing this to our attention! My apologies for the delay :) This issue has now been fixed! 

Thanks again and hope you have a wonderful rest of your day :)
Masha from the SQL Docs team
