### ISSUE TITLE
does not work with migrations

### ISSUE THREAD

**Issue by josersleal** [MicrosoftDocs/sql-docs#2164]
https://github.com/aspnet/EntityFrameworkCore/issues/11329

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea66ca27-e0b1-cd1e-a8ef-55911169c71a
* Version Independent ID: f2340ce9-9771-851e-60a7-237c6e55f085
* Content: [SQL Server Express LocalDB - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-2017)
* Content Source: [docs/database-engine/configure-windows/sql-server-express-localdb.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/sql-server-express-localdb.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
@josersleal - thanks for submitting this information. I'd like to better understand what scenario fails here. Can you be more specific about the migration scenario that fails? Thanks!

**Comment by MikeRayMSFT** [comment]
Closing because no response received.
