### ISSUE TITLE
Does Notification Services works with SQL Server 2016?

### ISSUE THREAD

**Issue by vijendrapatil** [MicrosoftDocs/sql-docs#2168]
Does Notification Services works with SQL Server 2016? We have configured Notification Service on SQL 2008, and we are looking for a way to migrate it to SQL 2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bec6db7d-c543-e82f-4608-a6547a07a85d
* Version Independent ID: 39aa630b-671e-1ee8-52da-1a81ccba91a1
* Content: [Notification Services (SQL Server Configuration Manager) - SQL Server](https://docs.microsoft.com/en-us/sql/tools/configuration-manager/notification-services-sql-server-configuration-manager?view=sql-server-2016)
* Content Source: [docs/tools/configuration-manager/notification-services-sql-server-configuration-manager.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/configuration-manager/notification-services-sql-server-configuration-manager.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MikeRayMSFT** [comment]
@vijendrapatil - thank you for the submission, I will check and get back to you soon.

**Comment by vijendrapatil** [comment]
Its bit urgent. Your speedy reply would be helpful.

**Comment by MikeRayMSFT** [comment]
@vijendrapatil [Notification Services](https://support.microsoft.com/en-us/lifecycle/search?alpha=Microsoft%20SQL%20Server%20Notification%20Services%202.0%20Standard%20Edition,Microsoft%20SQL%20Server%20Notification%20Services%202.0%20Standard%20Edition) was deprecated in SQL Server 2005 and removed after SQL Server 2008.

**Comment by MikeRayMSFT** [comment]
Cleaning up articles mentioning SSNS is internal work item [User Story 1537101: SQL | Remove articles about SQL Server Notification Services (NS)](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1537101)
