### ISSUE TITLE
SSMS 18 closes immediately after startup

### ISSUE THREAD

**Issue by eltionb** [MicrosoftDocs/sql-docs#2170]
Solution found here.

https://stackoverflow.com/questions/49279586/sql-server-management-studio-closes-immediately-after-startup

Please fix for next version

**Comment by MikeRayMSFT** [comment]
@eltionb - thank you for pointing this out. I'm reaching out to @yualan to see if he has additional helpful information.

**Comment by markingmyname** [comment]
@eltionb,

Thanks for your comment.

Your contribution is much appreciated. However, our team can only answer feedback related to the documentation. Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page or visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) page. If you have any feedback related to the documentation, please feel free to log in through this channel. We truly appreciate your contribution to our articles.

Please note: I installed SSMS 18.0 GA last week and have had no issues with opening the application.  I installed it side-by-side with version 17.6.  Then I removed version 17.6 and version 18.0 still was working as expected.

Hope this helps.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
