### ISSUE TITLE
Also returns Views

### ISSUE THREAD

**Issue by HeinziAT** [MicrosoftDocs/sql-docs#2171]
The description of the TABLE_TYPE column strongly hints that INFORMATION_SCHEMA.TABLES also returns views, but since this is SQL Server documentation and, in SQL Server lingo, an View is not a Table, the first line should read: "Returns one row for each table *and view* ..." instead of "Returns one row for each table ...".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e30b4e4b-db09-dca7-eb8d-41cf92e44f7c
* Version Independent ID: 8cc873ab-faef-83bb-44c9-dc3ade947f76
* Content: [TABLES (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-information-schema-views/tables-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-information-schema-views/tables-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-information-schema-views/tables-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by MikeRayMSFT** [comment]
@HeinziAT - thank you for this comment. We're updating the docs. The update should be live in the next ~24 hours
