### ISSUE TITLE
"以前のバージョン" three links are the same

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#2172]
@hyoshioka0128 commented on [Sat May 18 2019](https://github.com/MicrosoftDocs/sql-docs.ja-jp/issues/262)

https://docs.microsoft.com/ja-jp/sql/database-engine/discontinued-database-engine-functionality-in-sql-server-2016?view=sql-server-2017

以前のバージョン
    ・SQL Server 2014 で廃止されたデータベース エンジンの機能)
    ・SQL Server 2012 で廃止されたデータベース エンジンの機能)
    ・SQL Server 2008 で廃止されたデータベース エンジンの機能)
 → three links are the same:
    "https://docs.microsoft.com/ja-jp/sql/database-engine/discontinued-database-engine-functionality-in-sql-server-2016"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 309582b2-c853-175c-7356-3dd0aa953312
* Version Independent ID: adedc202-6434-4482-0c61-0da816ffeef6
* Content: [SQL Server 2016 で廃止されたデータベース エンジンの機能 - SQL Server](https://docs.microsoft.com/ja-jp/sql/database-engine/discontinued-database-engine-functionality-in-sql-server-2016?view=sql-server-2017#previous-versions)
* Content Source: [docs/database-engine/discontinued-database-engine-functionality-in-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs.ja-jp/blob/live/docs/database-engine/discontinued-database-engine-functionality-in-sql-server-2016.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by CeciAc** [comment]
Hi team, 
the error the contributor is reporting is also present in the source page.

These three links lead to the same target:
![imagen](https://user-images.githubusercontent.com/26746247/58025658-509ed300-7aeb-11e9-95f9-1981da24a992.png)

**Comment by MikeRayMSFT** [comment]
@hyoshioka0128 - thank you for pointing this out. We have submitted an update to the article you mentioned. 

It is in a private pull request (https://github.com/MicrosoftDocs/sql-docs-pr/pull/10302) but the update should be visible in a day or so. Thank you for identifying this problem.
