### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by pedroalfaroarias** [MicrosoftDocs/sql-docs#2173]
The download of the archive is failing, when it finishes, it star again and over again, being in a infinite downloading

When it reach the total of MB, it starts again, and over again, we have check it yet and is not a internet or device problem, it comes from microsoft website download module.

**Comment by MikeRayMSFT** [comment]
Hi @pedroalfaroarias Can you tell me a little bit more:

The download of what archive is failing? What Microsoft website is the download from?

Thank you,
Mike

**Comment by pedroalfaroarias** [comment]
Hi Mike,

The archive I´m talking about is the SQL Server Management Studio (SSMS) 18.0, on this link https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017.

Regards,

--
Pedro Andres Alfaro Arias
GLO - Global Logistics Organization
pedro.alfaro@hpe.com<mailto:pedro.alfaro@hpe.com>
+(506) 2699 5812
[hpesm_pri_grn_pos_rgb]
Heredia, Costa Rica

**Comment by MikeRayMSFT** [comment]
Hi Pedro - I have not been able to reproduce this issue. @markingmyname - Would you mind taking a look?

**Comment by MikeRayMSFT** [comment]
Hi Pedro - one additional suggestion, would you mind trying to download from a browser with Private (Edge) or Incognito (Chrome) session?

**Comment by pedroalfaroarias** [comment]
Neither, I tried in all browsers, in incognito, and I ask to be downloaded in other countries, and neither, I have the same problem.

**Comment by markingmyname** [comment]
Hi @pedroalfaroarias,

I apologize for being late to the party, but we are discussing this issue.

I will respond again once there is an update.

Thank you.

**Comment by markingmyname** [comment]
Hi again, @pedroalfaroarias,

Can I get one piece of info from you, just so I am clear, are you trying to download 18.0 or 18.1?

Because the article you referenced in this issue is to the current download page which now promotes 18.1.

Please let me know.

Thank you.

**Comment by MikeRayMSFT** [comment]
@pedroalfaroarias we haven't been able to reproduce this. I'm curious if some local policy or anti-virus configuration may be preventing download. Because this issue doesn't appear to be reproducible, will close.
