### ISSUE TITLE
KB 968389 No Longer Availalbe

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/sql-docs#2176]
This paragraph links to https://support.microsoft.com/kb/968389, which is no longer available.

"For more information about how to enable Extended Protection for the operating system, see Extended Protection for Authentication. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fbb99b-b42b-0558-7270-e9a3c8b34828
* Version Independent ID: 30f9a223-3dc9-9e21-0f1a-5238f0b939d0
* Content: [Connect to the Database Engine Using Extended Protection - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/connect-to-the-database-engine-using-extended-protection?view=sql-server-2017)
* Content Source: [docs/database-engine/configure-windows/connect-to-the-database-engine-using-extended-protection.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/connect-to-the-database-engine-using-extended-protection.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by MikeRayMSFT** [comment]
Thanks @fowl2  for submitting this. My colleague @VanMSFT will review.

**Comment by VanMSFT** [comment]
@fowl2 - Thank you, James for providing feedback on our documentation! I'm fixing the link and it should be live by tomorrow. We appreciate your help! If there are any concerns, please don't hesitate to let us know. I'll go ahead and close this for now.

https://github.com/MicrosoftDocs/sql-docs-pr/pull/10334
