### ISSUE TITLE
WITH FORMAT: "The existing contents of the volume become invalid, because any existing media header and backup sets are overwritten", the existing contents are not just invalid, its actually deleted

### ISSUE THREAD

**Issue by SDP190** [MicrosoftDocs/sql-docs#2180]
When you say that using "WITH FORMAT" causes "_The existing contents of the volume become invalid, because any existing media header and backup sets are overwritten_", it seams that the initial data is not being explicitly formatted and deleted but only overridden, thus say the original backup is larger then the current backup the file will not get shrunken.

However I tested it and found that doing a backup using "WITH FORMAT" option, will indeed shrink the file if the space needed is less then what was used for the original backup, thus indicating that "WITH FORMAT" does not just override the old backup-sets (content) with the current one, but will also perform a cleanup and wipe out any existing content causing the file to shrink.

So to say, that if you perform backup using option "WITH FORMAT" then: "The existing contents of the volume become invalid" that's not right, because the existing content is not there at all anymore, it is being deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdc1049f-2eaa-cf47-38c8-ae83dd0955aa
* Version Independent ID: 544fb558-5df0-ff90-70dc-2d6776964ffa
* Content: [BACKUP (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/backup-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/backup-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/backup-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by SDP190** [comment]
However, to comment on my own words, could passably be that this behavior that the file is shrunken is just an implementation detail when "WITH FORMAT" is used to backup on a disk file, since the content become invalid, as an effect those content are released, but for example when the operation is on a tape, that will not happen.

**Comment by MikeRayMSFT** [comment]
@SDP190 we're still verifying before we answer. Thanks for your patience.

**Comment by SDP190** [comment]
Any update?

**Comment by MikeRayMSFT** [comment]
@SDP190 - thanks for your patience. To clarify, you want to know if WITH FORMAT just removes the header and resets the file pages so that they can be over written (that's what the doc currently infers) or if it overwrites all of the information on the backup file disk pages (zeroes the file out). 

Is that right?

**Comment by SDP190** [comment]
Actually I can divide the question in 2:

1. If WITH FORMAT just removes the header and resets the file pages so that they can be overwritten or if it actually overwrites all of the information on the backup file disk pages (zeroes the file out)
2. In any case however, how does it explain the effect of the backup file being shrunken? (zeroing the file out would decrease the file size? )

**Comment by MikeRayMSFT** [comment]
`WITH FORMAT` causes the backup to overwrite the header and then truncate it without zeroing out rest of the file. The truncated space is released as free space to the volume.
Thanks for your patience.

**Comment by SDP190** [comment]
@MikeRayMSFT thanks, so I guess that  when its states in the docs 
> The existing contents of the volume become invalid
It refers to that  truncated part of the file which is not physically deleted but is not valid any more, and is released to the Volume, correct?
