### ISSUE TITLE
If MSA can register SPN automatically?

### ISSUE THREAD

**Issue by Maggie18z** [MicrosoftDocs/sql-docs#2181]
"An MSA has the ability to register Service Principal Name (SPN) with the Active Directory. " Does it need to grant read/write SPN permission manually or it should already with the permission?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b3831a3-6c86-243c-4b07-8960e4d06d7b
* Version Independent ID: dfd7599d-88eb-99f2-c227-0c9dc82bfd87
* Content: [Configure Windows Service Accounts and Permissions - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by VanMSFT** [comment]
Hi @Maggie18z! Thanks for bringing this to our attention! The statement has been modified to call out the permissions needed to register an SPN:

![image](https://user-images.githubusercontent.com/40007119/58653366-66ba4980-82ca-11e9-97a1-3db099bf6c95.png)

Feel free to let us know if you have any questions. I will go ahead and close this Issue for now.

https://github.com/MicrosoftDocs/sql-docs-pr/pull/10411

**Comment by Maggie18z** [comment]
Hi Van To!! This is Maggie. Yes I got to know document has been updated from Claire.
Thanks for reaching!!!

Best Regards,

Maggie Zhang （张梦琦）
Technical Advisor                Tel: +86 (510) 66657755
Data & BI Support               mengqi.zhang@microsoft.com<mailto:mengqi.zhang@microsoft.com>
Data & Enterprise Cloud     Mon - Fri 9:00 -18:00 (UTC+8)
[cid:image001.png@01D2EF6C.53CE4860]
