### ISSUE TITLE
sp_migrate_user_to_contained - add warning that it's irreversible 

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/sql-docs#2182]
It would be nice if there was a note on here mentioning that there is no way of reversing this command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3affeb6a-cf0f-1b7a-abfd-7661435f863b
* Version Independent ID: d4899b08-843d-2c5d-4bfa-d7a0ab130653
* Content: [sp_migrate_user_to_contained (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-migrate-user-to-contained-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-migrate-user-to-contained-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-migrate-user-to-contained-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by VanMSFT** [comment]
Hello @fowl2! I have added a note at the top of the page. It should go live soon. Thank you so much for your suggestions! Your feedback is appreciated! I'll go ahead and close this request now, but if you have any concerns, please feel free to let us know. Thanks again.

https://github.com/MicrosoftDocs/sql-docs-pr/pull/10606
