### ISSUE TITLE
No list?

### ISSUE THREAD

**Issue by JayPenney** [MicrosoftDocs/sql-docs#2185]
It would be nice to just have a basic list of ports needed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3bdfbfc-233e-77f1-7ce0-dd7f9df5899d
* Version Independent ID: 311358ab-78ca-6739-201d-13b05917e9da
* Content: [Configure the Windows Firewall to Allow SQL Server Access - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/configure-the-windows-firewall-to-allow-sql-server-access?view=sql-server-2017)
* Content Source: [docs/sql-server/install/configure-the-windows-firewall-to-allow-sql-server-access.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/configure-the-windows-firewall-to-allow-sql-server-access.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @JayPenney , 

Thanks for contacting Microsoft! I see a list here:
https://docs.microsoft.com/en-us/sql/sql-server/install/configure-the-windows-firewall-to-allow-sql-server-access?view=sql-server-2017#ports-used-by-

Are you looking for something different?

Thanks!

**Comment by JayPenney** [comment]
You are answering a question with the full details page. It would be nice to have an abbreviated summary of the ports – like everyone else does.

Jay Penney •  Network  Administrator
AYR FARMERS MUTUAL INSURANCE COMPANY
Toll Free: 1-800-265-8792 ext. 216
www.ayrmutual.com<http://www.ayrmutual.com/>

[Email Signature logo]

This e-mail message is confidential, for the exclusive use of the addressee, and its contents shall not constitute a commitment by Ayr Farmers Mutual Insurance Company, except as otherwise specifically provided in writing by Ayr Farmers Mutual Insurance Company. Any unauthorized disclosure, use or dissemination, either whole or partial, is prohibited. If you are not the intended recipient of the message, please notify the sender immediately.  Thank you.

**Comment by MashaMSFT** [comment]
Hi @JayPenney ,

something like this?
![image](https://user-images.githubusercontent.com/32783170/58902855-e70cf000-86b8-11e9-816b-ef5a1719a14f.png)

By the way, when you reply via email, your email address and signature is visible on Github. I've removed it from your previous comment, but wanted to let you know for future responses.

Thanks!

**Comment by JayPenney** [comment]
Yes 😊

Jay Penney •  Network  Administrator
AYR FARMERS MUTUAL INSURANCE COMPANY
Toll Free: 1-800-265-8792 ext. 216
www.ayrmutual.com<http://www.ayrmutual.com/>

[Email Signature logo]

This e-mail message is confidential, for the exclusive use of the addressee, and its contents shall not constitute a commitment by Ayr Farmers Mutual Insurance Company, except as otherwise specifically provided in writing by Ayr Farmers Mutual Insurance Company. Any unauthorized disclosure, use or dissemination, either whole or partial, is prohibited. If you are not the intended recipient of the message, please notify the sender immediately.  Thank you.

**Comment by MashaMSFT** [comment]
Hi @JayPenney , great! Thanks for your feedback, I've merged this change and it should be live by tomorrow morning. Please let us know if there is anything more we can do for you? If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a wonderful rest of your day!
