### ISSUE TITLE
Return Value is unclear

### ISSUE THREAD

**Issue by cabbruzzese** [MicrosoftDocs/sql-docs#2186]
The Returns Types paragraph is not clear on what is actually returned. Perhaps rewording it as "The return type for this method is dynamic. It will return the same data type as the argument supplied for the *date*."

Because this is unclear, I naturally assumed that the next section "Return Value" would have more information, but it appears to be providing sanity check information for some of the arguments. Is "Return Value" supposed to be describing possible error messages? Shouldn't there be an error section instead to better describe how to troubleshoot errors?

The expected format for code documentation is generally a small blurb on return describing the happy path, followed by an exceptions or errors section describing the errors that can be returned and what state causes them.

A good example of this format is the .NET entry for File.Open
https://docs.microsoft.com/en-us/dotnet/api/system.io.file.open?view=netframework-4.8

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a16b2e33-bcd1-2502-949f-de24d0f687b0
* Version Independent ID: 1dd3a1c6-957f-288a-c12d-02bedb92d6cc
* Content: [DATEADD (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/dateadd-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/dateadd-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/dateadd-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
@cabbruzzese - thanks for the recommendation. We've updated the return type information.
