### ISSUE TITLE
Please move DATABASE_PRINCIPAL_ID from "Metadata" to "Security" in left nav / TOC

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#2188]
Currently, the `DATABASE_PRINCIPAL_ID` built-in function is categorized in the "Transact-SQL (T-SQL) / Functions / Metadata" group. It does not belong there. It should be in the "Transact-SQL (T-SQL) / Functions / Security" group, just like all of the other `*USER*` and `*LOGIN*` functions.

I tried to update the following file that contains the left-nav / TOC:

https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/toc/toc.yml

But it wouldn't let me edit it (perhaps it is too big? just over 1 MB)

**Comment by MashaMSFT** [comment]
Hi @srutzky, thanks for bringing this to our attention! We'll get this fixed :)

**Comment by MashaMSFT** [comment]
Hi @srutzky , 

Thanks again for contacting Microsoft!  We've submitted a documentation change based on your suggestion, and it should be live tomorrow. Please let us know if there is anything more we can do for you? If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a wonderful rest of your day!

**Comment by srutzky** [comment]
Thanks @MashaMSFT . I'll check tomorrow and close this out. You are welcome. Thanks, and you, too 😺 .

**Comment by srutzky** [comment]
Looks good. And, as I just noticed that, as added support for this change, `DATABASE_PRINCIPAL_ID` was already listed in the "Security Functions" section main page:

https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/security-functions-transact-sql.md

live version:

[Security Functions (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/functions/security-functions-transact-sql)

Thanks for pushing this correction through :-). Take care, Solomon..
