### ISSUE TITLE
Add missing page for USER_SID built-in security function

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#2190]
There is a built-in function that shows up in SSMS Intellisense named `USER_SID`. This function operates very similarly to [SUSER_SID](https://docs.microsoft.com/en-us/sql/t-sql/functions/suser-sid-transact-sql), except that you pass in `database_principal_id` (`SMALLINT`) instead of `login_name` (`sysname`) like you do for `SUSER_SID`. I suppose it could be intentionally "undocumented", but I can't think of a reason why given its simple nature, and the existence of the companion `SUSER_SID` function. Assuming that there is no reason to leave this function undocumented, the new page should go under **Transact-SQL (T-SQL) / Functions / Security**.

**TEST**

```sql
SELECT [sid], USER_SID([principal_id]) AS [USER_SID], *
FROM sys.database_principals;
```

Thanks!

**Comment by VanMSFT** [comment]
Hey @srutzky, let me check on this and get back to you on adding that page. Thanks!

**Comment by VanMSFT** [comment]
@srutzky - Hey Solomon! Thanks for the suggestion. I'll add this to our work items, and hope to get it documented in the coming months. Since we're tracking this internally, I'll go ahead and close this request. If you have any concerns, please feel free to let me know. We appreciate your contributions to the documentation! Thanks!

User Story 1553900

**Comment by srutzky** [comment]
Hi @VanMSFT . With this issue being closed out, how will I be notified if/when this issue is resolved?

**Comment by VanMSFT** [comment]
@srutzky - Hey Solomon, I'll update this issue when the work is done. It's something we have planned, but there's no ETA I can provide. Thanks!

**Comment by srutzky** [comment]
@VanMSFT Ok. Thanks.
