### ISSUE TITLE
Is Sqlpackage available on the Microsoft package feed?

### ISSUE THREAD

**Issue by blueelvis** [MicrosoftDocs/sql-docs#2194]
Hi,

Is this package available on the Microsoft Package feed for Linux? If not, is it possible to make it available there? It would be much easier to just run `apt-get install sqlpackage` once the feed is configured. If yes, could you please add documentation about that as well?

Thanks,
Pranav

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3df6af-9ac8-bc57-93dc-29ff713c1d3b
* Version Independent ID: 7624e2cc-7aa9-40dd-4015-3371ea2ea0a2
* Content: [Download and install sqlpackage - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-2017)
* Content Source: [docs/tools/sqlpackage-download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage-download.md)
* Product: **sql**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by pensivebrian** [comment]
Hi, @blueelvis. There currently isn't an apt package for sqlpackage. I agree that an apt package would be the ideal way to install sqlpackage, and it's something we are strongly considering in future, but I don't have any specific timelines to get this done.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
