### ISSUE TITLE
REFERENCES does not apply to SYNONYM

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/sql-docs#2196]
The table under "Permissions Applicable to Specific Securables" claims that the REFERENCES permission applies to SYNONYM, among other classes. However, in SQL Server 2017, the following results in an error:

```SQL
CREATE TABLE dbo.demo1 (col int);

CREATE SYNONYM dbo.demo2 FOR dbo.demo1;

GRANT REFERENCES ON dbo.demo2 TO public;
```

> Msg 4606, Level 16, State 1, Line 5  
> Granted or revoked privilege REFERENCES is not compatible with object.

I think this behavior of SQL Server makes sense: the REFERENCES permission would be needed for SCHEMABINDING, but a SYNONYM does not ensure that the target object exists, so SCHEMABINDING would not work anyway:

```SQL
CREATE VIEW dbo.demo3 WITH SCHEMABINDING AS SELECT col FROM dbo.demo2;
```

> Msg 2788, Level 16, State 1, Procedure demo3, Line 1 [Batch Start Line 6]  
> Synonyms are invalid in a schemabound object or a constraint expression.

Please correct the documentation to state that the REFERENCES permission does not apply to the SYNONYM class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6141aa-bfd7-1ce4-aecd-820036f4a60e
* Version Independent ID: fd41bd15-b6f6-0a67-eee8-4bae68e9838e
* Content: [Permissions (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/permissions-database-engine?view=sql-server-2017)
* Content Source: [docs/relational-databases/security/permissions-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/permissions-database-engine.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hello @KalleOlaviNiemitalo! Thanks for contacting the Microsoft Documentation Team and helping with feedback! Let me dig into this issue and get back to you on updating the doc. Thanks!

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- please process this aging Issue 2196.

**Comment by WilliamAntonRohm** [comment]
@KalleOlaviNiemitalo -- thank you again for this information.  We have incorporated your feedback into the documentation and it should be live tomorrow.  I am closing this issue 2196 now.
