### ISSUE TITLE
Extended events do not capture CREATE and ALTER LOGIN statements

### ISSUE THREAD

**Issue by wasim-sayyad** [MicrosoftDocs/sql-docs#2197]
In SQL server 2012 and 2016, **CREATE LOGIN** and  **ALTER LOGIN** statements [are not trackable] by Extended events.

Is that bug or intentional? 

Any alternative to capture same in SQL server in-premises environments ?

Thank you,
wasim_sayyad@hotmail.com
 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df1b0130-7e8b-5b69-8042-cf9f08b66bd4
* Version Independent ID: 45454041-f3d6-fbdf-ca37-52ba2f7898a9
* Content: [XEvents overview - SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/extended-events/extended-events?view=sql-server-2017)
* Content Source: [docs/relational-databases/extended-events/extended-events.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/extended-events/extended-events.md)
* Product: **sql**
* Technology: **xevents**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
I wonder whether this tracking of CREATE LOGIN is within the capability of:
SSMS > Object Explorer > Databases > my database > Security > Audit
?

**Comment by MightyPen** [comment]
@wasim-sayyad This is not a bug. Perhaps it would be nice to have.
Thank you for inquiring. This Issue 2197 is now being closed.
