### ISSUE TITLE
ENCRYPTION BY CERTIFICATE 

### ISSUE THREAD

**Issue by tdracz** [MicrosoftDocs/sql-docs#2198]
What is the syntax for ENCRYPTION BY CERTIFICATE ? It doesn't seem to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 170326d4-4dd1-32cf-f96b-2d161cfc7cfb
* Version Independent ID: 1fa164f7-1987-70cb-4290-6a97b1717b19
* Content: [CREATE ASYMMETRIC KEY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-asymmetric-key-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/create-asymmetric-key-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-asymmetric-key-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hello @tdracz! Thank you for reaching out to Microsoft Documentation Team on your CREATE ASYMMETRIC KEY syntax question. Let me dig into this question and get back to you. Thank you!

**Comment by srutzky** [comment]
Hello @tdracz . There is no `ENCRYPTION BY CERTIFICATE` option for **A**symmetric keys. I believe you are confusing this with [CREATE SYMMETRIC KEY](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-symmetric-key-transact-sql). **Symmetric Keys** do have the `ENCRYPTION BY CERTIFICATE` option, whereas **A**symmetric Keys only have the `ENCRYPTION BY PASSWORD` option.

Take care, Solomon..

**Comment by tdracz** [comment]
Hello Solomon, 
I'm not confusing it - that's what the "[CREATE ASYMMETRIC KEY](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-asymmetric-key-transact-sql?view=sql-server-2017)" documentation says: "ENCRYPTION BY <key_name_in_provider> Specifies how the key is encrypted. Can be a **certificate**, password, or **asymmetric key**." It clearly mentions certificate and even another asymmetric key. If that's not an option, I gather the documentation should be corrected. Also the same documentation page does not mention what algorithm is used when encrypting with the password. Is that 3DES as in case of the SYMMETRIC KEY? The [documentation ](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-symmetric-key-transact-sql?view=sql-server-2017)for it is clear on that. 

Best regards,
Tadeusz Dracz

**Comment by srutzky** [comment]
@tdracz : Sorry, I had skimmed over that part earlier and missed that detail. Yes, that is a documentation error. It looks to be a copy-paste error taken from another page entirely. In fact, with regards to `ENCRYPTION BY <key_name_in_provider>`, the "\<key\_name\_in\_provider\>" part makes absolutely no sense there. Also, the **Syntax** section shows `PROVIDER_KEY_NAME = 'key_name_in_provider'`, while in **Arguments** it is `KEY_NAME ='key_name_in_provider'`, and then both `CREATION_DISPOSITION` options mention it as being `PROV_KEY_NAME`.

And, under **Remarks**, it says (emphasis added):

> By default, the private key is protected by the database master key. If no database master key has been created, a password is required to protect the private key. _If a database master key does exist, the password is optional_.

The 3rd sentence (the italicized one), directly contradicts the previous sentence ;-). The 2nd sentence is correct, so we just need to remove that last sentence.

So yeah, definitely some clean-up needed there ;-).

I will see about submitting an update for this...

Take care, Solomon..

P.S. the syntax description also has issues as it does not denote the dependencies between various options, but I don't have time to fix that part.

**Comment by srutzky** [comment]
Forgot to mention, here are the options as far as I can tell:

```sql
CREATE ASYMMETRIC KEY [AKey1]
WITH ALGORITHM = RSA_2048
ENCRYPTION BY PASSWORD = 'password' -- optional, default = database master key

GO

CREATE ASYMMETRIC KEY [AKey2]
FROM FILE = 'path\file.snk'
ENCRYPTION BY PASSWORD = 'password' -- optional, default = database master key

GO

CREATE ASYMMETRIC KEY [AKey3]
FROM EXECUTABLE FILE = 'path\file.dll'
-- no private key = can't use "ENCRYPTION BY PASSWORD"

GO

CREATE ASYMMETRIC KEY [AKey4]
FROM ASSEMBLY [assembly]
-- no private key = can't use "ENCRYPTION BY PASSWORD"

GO

CREATE ASYMMETRIC KEY [AKey5]
FROM PROVIDER [ekm_provider]
WITH 
--ALGORITHM = RSA_2048, -- optional? default?
--CREATION_DISPOSITION = CREATE_NEW, -- optional, default = CREATE_NEW
PROVIDER_KEY_NAME = 'key_name_in_provider'
```

**Comment by tdracz** [comment]
Thanks Solomon, that was helpful.

**Comment by srutzky** [comment]
@tdracz I submitted PR #2200 to clean this page up. It was a bit more extensive than I originally thought it would be 😿

**Comment by VanMSFT** [comment]
@tdracz @srutzky - We'll go ahead and close this Issue, since the changes by Solomon are submitted. You should see them live after the merging process. If there are any concerns, please don't hesitate to let me know. We appreciate your contribution!
