### ISSUE TITLE
add PERSISTED details to Transact-SQL section

### ISSUE THREAD

**Issue by SnowLeopard71** [MicrosoftDocs/sql-docs#2199]
The section showing how to add a computed column should include how to create a PERSISTED column by including the word.   example:
ALTER TABLE dbo.Products ADD RetailValue AS (QtyAvailable * UnitPrice * 1.5) PERSISTED; 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7155e90b-8b59-5029-6020-223ea44bac84
* Version Independent ID: 48027234-b139-14b5-b790-c65285664360
* Content: [Specify Computed Columns in a Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/specify-computed-columns-in-a-table?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/tables/specify-computed-columns-in-a-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/specify-computed-columns-in-a-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@SnowLeopard71 - Thanks for raising this issue. The article has been updated and should be live with the PERSISTED snippet within the next few days.

Thanks!
