### ISSUE TITLE
EXTERNAL TABLE Vs. POLYBASE IN AZURE SQL DATABASE

### ISSUE THREAD

**Issue by sandeepkmishra** [MicrosoftDocs/sql-docs#2203]
Dear Team,
This article is miss-leading while trying to understand/using the concept of Polybase vs. creating external table from ADLS to Azure SQL Database.  Because of this, we are getting an impression like Azure SQL Database does supports Polybase design and by which we can reads the data directly from external sources like ADLS/Data Lake Store however it is not true as it does not support the Polybase design. 

The reason, trying to connect with you, is after reading the article and while trying to implement external table as per above given command, it says, error in command near "HADOOP" which is completely out of context as it didn't say above on that, the command will not support. which is something different.

Kindly check this thread: 
https://stackoverflow.com/questions/54240747/create-external-data-source-azure-sql
Please advise.

Best Regards
Sandeep KM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ac2fe2-31da-7db6-2d5f-5091022f41d2
* Version Independent ID: bbf07c2c-7006-7b94-f12f-800fa7bc67e4
* Content: [CREATE EXTERNAL TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-table-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-external-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
Create External table is used for both elastic queries in Azure SQL Database and for polybase in Azure SQL Data Warehouse. I will revise the note at the top and the introductory sentence to make this a bit more clear. 
@sandeepkmishra

**Comment by sandeepkmishra** [comment]
Thank you so much @CarlRabeler. Much appreciate your quick response.

Your update will be really helpful/useful for lots of Architects/Leads/others, when someone proposing Polybase design to enterprise customers.  Just to make clear that external table is used in SQL Data warehouse is for Polybase design, while external table is used in Azure SQL Server is for Elastic search . Thank you once again and hope to see the changes.. Thank you and have a lovely weekend.

Best Regards,
Sandeep

**Comment by CarlRabeler** [comment]
fixed 
#please-close
