### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by esjayee** [MicrosoftDocs/sql-docs#2205]
Just the information I needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e5a0c52-7600-3010-6811-3466e13e3289
* Version Independent ID: 41988d95-503f-0097-6850-5e5656905b91
* Content: [ROWCOUNT_BIG (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/rowcount-big-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/rowcount-big-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/rowcount-big-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by CarlRabeler** [comment]
@esjayee thanks for the positive feedback.
