### ISSUE TITLE
Round function bug

### ISSUE THREAD

**Issue by hoalh** [MicrosoftDocs/sql-docs#2208]
DECLARE @x float = 5.595
SELECT ROUND(@x,2)
DECLARE @y money = 5.595
SELECT ROUND(@y,2)

Result: 
5.59
5.60

**Comment by MightyPen** [comment]
@hoalh Hi, thanks for creating this Issue 2208.  Our assessment is that the various imprecise numeric data types have these occasional edge conditions by their nature.  In your 'float' case, 5.596 does Round to 5.6.  We do not feel there is a bug here.  But we can certainly understand why there could be uncertainty about that.
I am Closing this Issue now. The @ notification mechanism works even in Issues that are Closed, in case further communication is necessary.
Thank you. Bye.
