### ISSUE TITLE
Code example return no data always

### ISSUE THREAD

**Issue by ricoisme** [MicrosoftDocs/sql-docs#2209]
I can not find value of "sys_sensitivity_label_name" or "sys_information_type_name" in name's column in sys.extended_properties.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34863695-cd07-1260-4fea-66738c5fa80a
* Version Independent ID: 4c01015d-9c1d-db8e-84f5-379ffc5d5133
* Content: [SQL Data Discovery & Classification - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/sql-data-discovery-and-classification?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/relational-databases/security/sql-data-discovery-and-classification.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/sql-data-discovery-and-classification.md)
* Service: **sql-database**
* GitHub Login: @giladm
* Microsoft Alias: **giladm**

**Comment by MightyPen** [comment]
@giladmit Hi Gilad, In this Issue 2209, a customer is reporting that a SQL code example in your article is not functioning.  Can you please look at the article, and make any necessary corrections.
Van To is a Writer who works in the general area of Security.  If necessary, you can perhaps ask Van for assistance.

- [https://docs.microsoft.com/sql/relational-databases/security/sql-data-discovery-and-classification](https://docs.microsoft.com/sql/relational-databases/security/sql-data-discovery-and-classification)

CC: @vanmsft , @ricoisme

**Comment by giladmit** [comment]
adding @salexu @ronitr as I am no longer part of this product group

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- I am closing this aging issue now.  I've created a followup task https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1564567.

@ricoisme -- you are welcome to follow up with us as needed, please just @ mention one of us.

**Comment by VanMSFT** [comment]
I added a simple data classification, and was able to get results:

![image](https://user-images.githubusercontent.com/40007119/61301594-0491a700-a799-11e9-8446-ce33e9cb30e5.png)

The query is working
