### ISSUE TITLE
Azure Sql db

### ISSUE THREAD

**Issue by HenrikStaunPoulsen** [MicrosoftDocs/sql-docs#2211]
the example does not work on Azure SQL DB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b79d736-c8b0-a460-501a-71c590092bc9
* Version Independent ID: f5c34ba9-0a5d-0af5-c4e5-c99d5572e6d5
* Content: [CREATE EVENT SESSION (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-event-session-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/create-event-session-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-event-session-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by MightyPen** [comment]
@HenrikStaunPoulsen The article has been changed to add relevant information that address the concern described here in Issue 2211 (PR 10427).  The change should be visible on live Docs by Thursday May/30.
Thank you.
I am now closing this Issue as fixed.
