### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by genifycom** [MicrosoftDocs/sql-docs#2215]
"To connect to a shared instance of LocalDB add .\ (dot + backslash) to the connection string" is correct.

However, "use a connection string such as (localdb).AppData" is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea66ca27-e0b1-cd1e-a8ef-55911169c71a
* Version Independent ID: f2340ce9-9771-851e-60a7-237c6e55f085
* Content: [SQL Server Express LocalDB - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/configure-windows/sql-server-express-localdb.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/sql-server-express-localdb.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@MikeRayMSFT Hi Mike, Issue 2215 is now assigned to you.  Thanks.

**Comment by MikeRayMSFT** [comment]
@genifycom thanks for the submission. Investigating

**Comment by srutzky** [comment]
The correct syntax _should_ be: `(localdb)\.\AppData`. And that _used_ to work. But I can no longer get it to work in either SQLCMD or SSMS. Using the newest SQLCMD / ODBC (version 17) with any version of LocaDB (including 2019 CTP 2.5), I get the following error:

> Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Named Pipes Provider: Could not open a connection to SQL Server [2]. .  
> Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.  
> Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..

Yet I can connect to that instance using the non-shared name and the named-pipes syntax. Apparently a bug has already been filed on this issue:

[SQL Server 2017 Express LocalDB Shared Instance Connections Fail](https://feedback.azure.com/forums/908035-sql-server/suggestions/36481279-sql-server-2017-express-localdb-shared-instance-co)

**Comment by MikeRayMSFT** [comment]
Thanks Solomon - I have asked a few people to look into this.

**Comment by genifycom** [comment]
Any update on this? Is there a workaround or a prior version we can use that does work in shared mode?

**Comment by MikeRayMSFT** [comment]
Did you run with 

`(localdb)\.\AppData`?

**Comment by MikeRayMSFT** [comment]
Updated syntax in article last week. Followed up with OP. No reply. Closing issue.
