### ISSUE TITLE
sql where and having

### ISSUE THREAD

**Issue by gopalkrishankunal** [MicrosoftDocs/sql-docs#2217]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36922666-9dd1-cdf1-a4b8-824da4fecfd0
* Version Independent ID: 8432ddb4-a502-8f34-3666-5d8f70e9d25d
* Content: [Use HAVING and WHERE Clauses in the Same Query - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/visual-db-tools/use-having-and-where-clauses-in-the-same-query-visual-database-tools?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/visual-db-tools/use-having-and-where-clauses-in-the-same-query-visual-database-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/visual-db-tools/use-having-and-where-clauses-in-the-same-query-visual-database-tools.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by MightyPen** [comment]
@gopalkrishankunal Hello, This Issue 2217 provides no explanation of why it was created. Therefore I must now Close this Issue.
Feel free to create another Issue, if you remember what the problem or concern was.
Thank you.
