### ISSUE TITLE
Temporary Keys

### ISSUE THREAD

**Issue by samrueby** [MicrosoftDocs/sql-docs#2218]
It's confusing what separates a temporary key from a not-temporary key. This documentation says "the names of temporary keys should begin with one number (#) sign", but the number sign isn't what makes it a temporary key. The example "Creating a temporary symmetric key" doesn't include any syntax that makes it clear that a temporary key is being created. Because of this, I'm unable to tell what actually makes a key temporary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e9162b3-83a4-f209-7046-c465a37c3ed8
* Version Independent ID: a168dd02-14ba-f666-3aae-028ef7aedd8c
* Content: [CREATE SYMMETRIC KEY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-symmetric-key-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-symmetric-key-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-symmetric-key-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by MightyPen** [comment]
@VanMSFT Hi Van, this Issue 2218 now assigned to you.  Thanks.

**Comment by VanMSFT** [comment]
Hey @samrueby - The # sign designates the key as a temporary key, and then is stored in the tempdb. Please let me know if that makes it clear. I will edit the doc to clarify the _key_name_. Thanks!

**Comment by VanMSFT** [comment]
Doc changes are taking place. Should be live shortly.

https://github.com/MicrosoftDocs/sql-docs-pr/pull/10611

@samrueby - Sam, if you have any concerns, please let us know. Thanks for your feedback. We appreciate you helping us improve our documentation! I'll go ahead and close this request for now.

**Comment by samrueby** [comment]
The change looks good. Thank you.
