### ISSUE TITLE
DOP downgrades

### ISSUE THREAD

**Issue by LonnyNiederstadt** [MicrosoftDocs/sql-docs#2220]
The page above says:
"After DOP is configured, it can only be lowered on grant memory pressure. Workload group reconfiguration is not visible while waiting in the grant memory queue."

Is it true that "it can only be lowered on grant memory pressure"?  DOP for a parallel query can certainly be lowered - all the way to DOP 1 - due to in-use and reserved worker pressure on 'max workers', as well.  If that is considered part of "DOP is configured" in this context, it is not clear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d79ae973-3a8a-0456-b618-fc23ab8dfe09
* Version Independent ID: 4cc8fa7c-af8f-7732-a188-75a70e7ba1c8
* Content: [CREATE WORKLOAD GROUP (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-workload-group-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-workload-group-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-workload-group-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by MightyPen** [comment]
@CarlRabeler Hi Carl, This Issue 2220 is now assigned to you.  Thanks.

**Comment by bluefooted** [comment]
Hi @LonnyNiederstadt - this is a poorly worded sentence, I think this has something to do with the fact that you can configure DOP on the workload group while queries are running, but if there are any active queries in the memory grant queue you cannot reconfigure the workload group until those queries are out of the queue. I'm not sure why this would be called out though. @CarlRabeler I would suggest we remove the bullet altogether.

**Comment by CarlRabeler** [comment]
#please-close
