### ISSUE TITLE
Advice is misleading

### ISSUE THREAD

**Issue by goobering** [MicrosoftDocs/sql-docs#2221]
In light of diagramming being pulled from SSMS 18, it's more than a little disingenuous to include 'Use database diagrams and table designers.' as a use case in the 'When Should I Use Azure Data Studio vs SQL Server Management Studio?' section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebb3c5fd-6f61-b90b-d3d0-5b4d0ae92145
* Version Independent ID: c68c3712-3fe9-04b3-a6e5-9d084764f54e
* Content: [FAQ - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/faq?view=sql-server-2017#when-should-i-use-azure-data-studio-vs-sql-server-management-studio)
* Content Source: [docs/azure-data-studio/faq.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/faq.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, I know you are looking into this DB Diagram issue, and that your efforts will take at least a few days.  When you have an answer that you can publicly share, please add a Comment into this Issue 2221.  Thanks.

**Comment by markingmyname** [comment]
Hi @goobering,

The feature was returned in SSMS  version 18.1.

Have you had a chance to download that version?

**Comment by goobering** [comment]
Hi Mark

I haven't looked at it yet, but if diagrams are back in then my original
comment and the thread are redundant! Please feel free to close the issue.

Many thanks

**Comment by markingmyname** [comment]
Thank you, @goobering.

Microsoft heard the comments of the SQL community and made the change to return the feature.

Thank you.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
