### ISSUE TITLE
Conditionally delete a json object from Json Array in SQL Server

### ISSUE THREAD

**Issue by prakash-manit** [MicrosoftDocs/sql-docs#2223]
Hi team,
I am using Json Array to store child table records as a column in parent table. Now I have a requirement to conditionally delete one of the record from json array. If it would have been a table, I could have used delete command with the condition but how can I delete a record form Json array stored as varchar(max) column in SQL Server. I have gone through below url and can see command to query and modify the data but what about delete?
https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-2017

**Comment by MightyPen** [comment]
@prakash-manit Hello, I believe you can perform a multi-step sequence.  The crucial step would be to use the **JSON_MODIFY** T-SQL function:

[JSON_MODIFY T-SQL function | https://docs.microsoft.com/sql/t-sql/functions/json-modify-transact-sql](https://docs.microsoft.com/sql/t-sql/functions/json-modify-transact-sql)

@jovanpop-msft Jovan can add further Comment if my claim in wrong or is too incomplete.

**Comment by MightyPen** [comment]
@prakash-manit I believe the answer I gave 11 days ago is the answer.
I am now Closing this Issue 2223 as Fixed.

Thank you for inquiring with us. We hope to hear from you again.
