### ISSUE TITLE
Unable to Create Identical Symmetric Keys on Two Servers using different versions of SQL Server.

### ISSUE THREAD

**Issue by samrueby** [MicrosoftDocs/sql-docs#2225]
The steps on this page do not work with one server running SQL Server 2016, and another running 2017. It can be resolved by enabling trace-flag 4631, as mentioned here: https://feedback.azure.com/forums/908035-sql-server/suggestions/33116269-identical-symmetric-keys-do-not-work-between-sql-s. and by installing a patch: https://support.microsoft.com/en-us/help/4053407/sql-server-2017-cannot-decrypt-data-encrypted-by-earlier-versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d903c17-112d-c463-0af8-e1b6799df66f
* Version Independent ID: 008ccdde-b62c-92a1-98fd-377ad97a769d
* Content: [Create Identical Symmetric Keys on Two Servers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/create-identical-symmetric-keys-on-two-servers?view=sql-server-2017)
* Content Source: [docs/relational-databases/security/encryption/create-identical-symmetric-keys-on-two-servers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/create-identical-symmetric-keys-on-two-servers.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @aliceku
* Microsoft Alias: **aliceku**

**Comment by MightyPen** [comment]
Working on a documentation fix presently. Here is the private repo link, which member of the public probably cannot see directly:
- [https://github.com/MicrosoftDocs/sql-docs-pr/pull/10456](https://github.com/MicrosoftDocs/sql-docs-pr/pull/10456)

**Comment by MightyPen** [comment]
@samrueby Hello Sam,
The fix should be live on Docs with a business day or two, under the numbered list of Steps.
Thank you very much for bringing this to our attention.
