### ISSUE TITLE
Poor English

### ISSUE THREAD

**Issue by rbonomo** [MicrosoftDocs/sql-docs#2228]
Someone get an editor over here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 537e197c-adac-94b7-1a8e-9f5ca34a29fc
* Version Independent ID: 99f9866c-b728-219a-c49d-8f7d52f59ea0
* Content: [Contained Database Users - Making Your Database Portable - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/contained-database-users-making-your-database-portable?view=sql-server-2017)
* Content Source: [docs/relational-databases/security/contained-database-users-making-your-database-portable.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/contained-database-users-making-your-database-portable.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @rbonomo! Thank you for bringing this issue up to the Microsoft Documentation team. I put in a task to review and edit this document. If you wish to edit this document yourself, please feel free.

To do so, please do the following:

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Name your file change and provide a description, if necessary
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page
9. Feel free to type @_____  in the comments so I can review the change as well, if I'm not the author of the page.

Thanks again! I'll close this for now, but feel free to let me know if you have any questions.

User Story 1548011
