### ISSUE TITLE
Poor English. Tree Item Typo "Overvivew"

### ISSUE THREAD

**Issue by rbonomo** [MicrosoftDocs/sql-docs#2229]
Needs editor review.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6334ee2-0f75-c3ee-aae7-4b4e6357aa84
* Version Independent ID: 2750b453-0f24-c180-dff2-9040fb531c8a
* Content: [Contained Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/contained-databases?view=sql-server-2017)
* Content Source: [docs/relational-databases/databases/contained-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/contained-databases.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@rbonomo - thanks for pointing this out. Fix is in process...

**Comment by stevestein** [comment]
@rbonomo - this is fixed. https://docs.microsoft.com/en-us/sql/relational-databases/databases/contained-databases?view=sql-server-2017

Thanks again!
