### ISSUE TITLE
Expand on statement

### ISSUE THREAD

**Issue by rbonomo** [MicrosoftDocs/sql-docs#2230]
"Because certain objects have a default containment setting of NONE, this view can return false positives." What is this about? What is "false positives?". Is your software incorrect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6334ee2-0f75-c3ee-aae7-4b4e6357aa84
* Version Independent ID: 2750b453-0f24-c180-dff2-9040fb531c8a
* Content: [Contained Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/contained-databases?view=sql-server-2017)
* Content Source: [docs/relational-databases/databases/contained-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/contained-databases.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@stevestein Hi Steve, this Issue 2230 is now assigned to you.
In dpmds, no name like 'contain' is found.  Perhaps you can clarify what the phrase "false positives" is intended to mean in this usage.

**Comment by stevestein** [comment]
@rbonomo - Thanks for raising this issue. I'm looking into the details and will reply when I

**Comment by stevestein** [comment]
@rbonomo - I couldn't track down a specific example, but as the note says: _certain objects have a default containment setting of NONE_  - so in this case, if the object is in a contained database, it can appear in the results of the uncontained entities view.

Hope that helps.
