### ISSUE TITLE
SSMS2018 - Installed, but will not run

### ISSUE THREAD

**Issue by fwd079** [MicrosoftDocs/sql-docs#2234]
Need to announce that this version does not run at all.
I just installed (as of 31-May-2019) - need to follow the fix in this link:
https://feedback.azure.com/forums/908035-sql-server/suggestions/37502512-ssms2018-installed-but-will-not-run

Copying here for others to see and use.
---
The issue (in .NET) has been investigated and understood.

The recommended workaround, in the interim, is:
1) Close all instances of SSMS
2) Edit ssms.exe.config 
3) Remove the line that has the following text (should be line 38):
NgenBind_OptimizeNonGac enabled=“1”

That’s the same change that will be in the next release of SSMS 18.x

Thanks,
-Matteo
---

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by SushiGuy** [comment]
SSMS when launched showed the splash screen then instantly crashed. Making the suggested config change as described did the trick. Here is the full path to config file.
`C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Ssms.exe.config`

**Comment by chrisheil** [comment]
This worked me for as well

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, On a forum, Matteo has posted the steps necessary for customers to Fix this SSMS bug locally on their own computers.  Those same steps have subsequently been pasted into the top of this Issue 2234.
You _might_ want to temporarily add a Cautionary alert into the SSMS Download documentation, to display the text of these same fix steps. I have no opinion on that, and the decision totally belongs to you and @rothja .
Thanks.

**Comment by boennhoff** [comment]
Why isn't Microsoft pulling back this beta release? Or replacing it immediately with a fixed version?

_"Here is the final episode of GoT.... Ahhh wait, the file is defect.... Just replace the first few bytes with NULs and your favourite Non-Microsoft video player should be able to continue at chapter 2........"_ :laughing: :rofl:

**Comment by kathleenkoson** [comment]
Gah, I'm sure this is something dumb, but please help...  I can get to the line and delete it, but I can't re-save the file to the same location ("you do not have permission to open this file.  See the owner of the file or the administrator to obtain permission").  What am I missing?  I am getting very tired of uninstalling and reinstalling the entire studio...  Thank you.

**Comment by SushiGuy** [comment]
First be sure to close SSMS app. Then, be sure to open your desired editing tool As Administrator which will allow you to Save the config file. Easiest way is to find your software shortcut or exe and Right-Click -> Run As Administrator

**Comment by kathleenkoson** [comment]
@SushiGuy – thank you!!  With that advice I got it fixed!  I’m back in, no more crashing.

**Comment by bineeshraghavan** [comment]
The recommended workaround worked me for as well, in the interim, is:

Close all instances of SSMS
Edit ssms.exe.config
Remove the line that has the following text (should be line 38):
NgenBind_OptimizeNonGac enabled=“1”

**Comment by csurrey** [comment]
Can confirm this worked for us - Thanks
As above you need to make sure all instances of SSMS are closed first and in our case we ported the configs from the preview after it kicked back into life

**Comment by dnethi** [comment]
hi folks, the updated SSMS 18.1 should have fixed this. Please update and let us know if the issue still exist.

**Comment by moosehunt2007** [comment]
I had the same problem as the people above with 18.1, it crashed after the splash screen.  I went back to 17.0 and it works just fine.  In my opinion, this is not fixed, this is 2 of us in my SQL Server class that have had this issue on our personal computers.

**Comment by markingmyname** [comment]
@MightPen,

A "known issues" section has been added to the release notes under the 18.0 section. :)

@moosehunt2007,

I see where you state - "I had the same problem as the people above" - referring to 18.1.  Have you tried the workarounds the people have tried as well?  It would be good to know if that works the same for 18.1 too.

**Comment by fwd079** [comment]
> @MightPen,
> 
> A "known issues" section has been added to the release notes under the 18.0 section. :)
> 
> @moosehunt2007,
> 
> I see where you state - "I had the same problem as the people above" - referring to 18.1. Have you tried the workarounds the people have tried as well? It would be good to know if that works the same for 18.1 too.

Okay tested,

Well @markingmyname - if you install fresh it gives the same splash screen crash, but if you have 18.0 installed and **upgrade** to 18.1, the fix is _kept_ and not overwritten. So perhaps add this to 18.1 Known Issues too. But yes, from 18.0 to 18.1 _upgrade_ works, not a clean install.

Regards.

**Comment by Matteo-T** [comment]
@fwd079: are you saying that installing 18.1 on a clean machine (i.e. with no 18.0 ever installed on it), you are still observing the flashing splash screens? If so, would you enter a UserVoice item (https://aka.ms/sqlfeedback) and share the SSMS 18.1 setup log files (%TEMP%\SSMSSetup)? Also, could you share your ssms.exe.config, the one installed by SSMS 18.1 (before any changes you may have done)?

**Comment by MichaelAzzar** [comment]
we need debugging tool to be added back please

**Comment by chaim1221** [comment]
Good lord I thought I was going crazy. I have uninstalled this program _so many times_ and reinstalled it thinking it was my computer. Seriously?

TEST

YOUR

SOFTWARE

**Comment by price5583** [comment]
I downloaded SSMS from the link on this page and found out they have now remarked out the NgenBind that was giving all the problems.  Here is how the NgenBind line reads in the Ssms.exe.config file now:

        

So, now all you have to do is download and run it, no config file editing is necessary.  Yeah!

**Comment by mrwensveen** [comment]
Adding this so it's easier to find this issue (hopefully). When you run smss.exe from the command line, you might get this message: `Program 'smss.exe' failed to run: The %1 application cannot be run in Win32 mode`. Above workaround should work, as well as installing SSMS.

Also, strangely, the executable seems to have been renamed from smss.exe to ssms.exe in this version?

**Comment by Matteo-T** [comment]
@mrwensveen:
> Adding this so it's easier to find this issue (hopefully). When you run smss.exe from the command line, you might get this message: Program 'smss.exe' failed to run: The %1 application cannot be run in Win32 mode. Above workaround should work, as well as installing SSMS.
> Also, strangely, the executable seems to have been renamed from smss.exe to ssms.exe in this version?

No, no... be very careful with that.
- SSMS.EXE is "SQL Server Management Studio"
- Smss.exe is "Session Manager Subsystem" - it's Windows stuff.

You will regret deeply if you mess with smss.exe :-)

**Comment by mrwensveen** [comment]
Ah, didn't know that. Thanks.

**Comment by IncubusSlayer** [comment]
I downloaded 18.1 today and cant connect to my local server anymore. Not sure if its tied to this same issue but some feedback would be greatly appreciated.

**Comment by Matteo-T** [comment]
> I downloaded 18.1 today and cant connect to my local server anymore. Not sure if its tied to this same issue but some feedback would be greatly appreciated.

I have no problem answering questions here, but... keep in mind this is the Git repo for the documentation, so the "doc" people may get mad at me :-)

To get help on SSMS: 
https://docs.microsoft.com/en-us/sql/ssms/sql-server-management-studio-ssms?view=sql-server-2017#info_tip-get-help

And, I can confidently say that the issue @IncubusSlayer is seeing in not related to the one discussed here. Can you try to use either sqlcmd.exe or Invoke-Sqlcmd (PowerShell cmdlet in the SQLServer module) to see if you can connected? If it does not work, then it's more like a configuration issue on the server side. If it does work, then log a UserVoice item (info at the same link I provided above).

**Comment by fwd079** [comment]
> @fwd079: are you saying that installing 18.1 on a clean machine (i.e. with no 18.0 ever installed on it), you are still observing the flashing splash screens? If so, would you enter a UserVoice item (https://aka.ms/sqlfeedback) and share the SSMS 18.1 setup log files (%TEMP%\SSMSSetup)? Also, could you share your ssms.exe.config, the one installed by SSMS 18.1 (before any changes you may have done)?

Tested today, fresh install is fixed and crashes no more. Cheers :)

Closing the issue now.

Regards.
