### ISSUE TITLE
WORTHLESS

### ISSUE THREAD

**Issue by rlhane** [MicrosoftDocs/sql-docs#2236]
What happened to a REAL T-SQL Reference?  What happened to actual content? Try searching for FULL OUTER JOIN on this site.  This page is useless and pointless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc6cd539-d024-9d35-5024-506041392e9a
* Version Independent ID: 0e63acf9-55aa-a81e-2150-b40dbde29f50
* Content: [Implementing an Outer Join - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/implementing-an-outer-join?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/in-memory-oltp/implementing-an-outer-join.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/implementing-an-outer-join.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
@rlhane Hello, An attempt to make our documentation about JOIN more find-able is contained in the new PR 10485 (in our private repo).  The PR should go live in Docs by Tuesday 2019/June/04. The most visible change will be the TOC title for the entry of the following article (about the FROM clause). Presently the TOC title is simply the four characters "FROM", but will change to something longer that includes the word "JOIN".

- https://docs.microsoft.com/sql/t-sql/queries/from-transact-sql

Related links:
- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/10485`
- `https://dev.azure.com/ceapex/Engineering/_workitems/edit/96535`

Thank you for bringing this concern to our attention. We hope to hear from you again.
I am now Closing this Fixed Issue 2236.  However, the @ notification system continues to work, in case further communication is needed.
 .
