### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by StockportJambo** [MicrosoftDocs/sql-docs#2239]
"This site can’t provide a secure connection.

azuredatastudiobuilds.blob.core.windows.net sent an invalid response." in Chrome. Similar message in Internet Explorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017#feedback)
* Content Source: [docs/azure-data-studio/download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by StockportJambo** [comment]
Antivirus is disabled.

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, Can you please process this Issue 2239.  Thanks.

**Comment by markingmyname** [comment]
Hi, @StockportJambo,

I am not sure how much you've looked into this, but can I ask if you have come across this action plan and see if it does work for you - https://answers.microsoft.com/en-us/ie/forum/all/errsslprotocolerror/c855d6b7-7330-43f0-bd48-a0063efb32a8?

Please let me know.

Thank you.

**Comment by StockportJambo** [comment]
The above didn't work, but it seems to be fixed anyway.

**Comment by aravindsd** [comment]
Downloading Data Studio file which is ~83MB takes ages. Not sure if file stored is from some blob storage and doesn't have transfer rate to download. You have github for product release why dont you guys use for all your product download. Fix it @Microsoft #Microsoft @azure-data-studio #azure-data-studio
