### ISSUE TITLE
IsDescendantOf

### ISSUE THREAD

**Issue by shoorik** [MicrosoftDocs/sql-docs#2241]
In the "Finding Ancestors by Using the CLR" section, in the "CommonAncestor" method, the code snippet calls "h1.IsDescendant(h2)". Was it meant to be "h1.IsDescendantOf(h2)"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eb7c78-a9f9-a4ba-e329-1612305ca5b7
* Version Independent ID: 32d85190-08f7-ae1f-db00-1837389d6863
* Content: [Hierarchical Data (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/hierarchical-data-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/hierarchical-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/hierarchical-data-sql-server.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@shoorik Hello Alex,
I have just now Merged your PR 2242, to fix this Issue 2241.
Thank you very much for your PR to actually fix this problem in our documentation! We love such PRs.
(When you create a PR, there is no need to also create a sister Issue.)

My PR 10512 makes other changes, like adding Language Specifiers onto the SQL and CSharp code blocks. My PR will sit idle (unMerged) until your PR is fully live on Docs.
