### ISSUE TITLE
Unable to initialize SQL Server 2019 Linux with Istio sidecar proxy on AKS

### ISSUE THREAD

**Issue by NileshGule** [MicrosoftDocs/sql-docs#2243]
I am able to deploy a SQL Server 2019 Linux container with HA on to an AKS cluster as shown [here](https://www.handsonarchitect.com/2019/05/upgrade-sql-server-2017-to-2019-with-ha.html).
`https://www.handsonarchitect.com/2019/05/upgrade-sql-server-2017-to-2019-with-ha.html`

I tried to use the SQL Server 2019 CTP 2.2 version with Kubernetes cluster which has Istio-1.1.3 version installed on it. The SQL Server 2019 initialization fails with the error attached as the screenshot
![Istio MSSQL 2019 error](https://user-images.githubusercontent.com/1298374/58763409-de1f0000-858c-11e9-9b00-3e30bd1b1f03.PNG)

The version of Kubernetes used for AKS is 1.13.5

Do I need to do anything special to make SQL Server 2019 Linux container image on AKS with Istio sidecar?

The MSSQL Pod initialization fails for all the 3 instances as shown below
![Istio MSSQL Pod Initialization error](https://user-images.githubusercontent.com/1298374/58763478-cbf19180-858d-11e9-8395-ff32fa6dddef.PNG)

**Comment by MightyPen** [comment]
@NileshGule Hello Niles, These GitHub Issues in this 'sql-docs' repository are only for Documentation errors, on Microsoft's `https://docs.microsoft.com/sql/` website.
This particular Issue 2243 refers to a different non-Microsoft web domain, and seems more about a Support request. We cannot process this type of Issue.

I will mention this Issue to someone who might know something helpful, and maybe we might notify you, through this Issue with the @ system. But realistically it is unlikely that further processing of this Issue will be occurring.
Closing now.  Thank you.
