### ISSUE TITLE
statement about permissions is ambiguous

### ISSUE THREAD

**Issue by kewalaka** [MicrosoftDocs/sql-docs#2244]
The page states "User must be a member of the sysadmin fixed server role or the db_ddladmin and db_owner fixed database roles.". 

This implies that if sysadmin is not granted, both db_ddladmin and db_owner are required.  Rebuilding an index can be achieved with either of these accounts, since db_owner includes the permissions granted to db_ddladmin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40c68674-b35e-416e-33d5-da18290e1640
* Version Independent ID: 7310124c-a4ff-a221-0ece-82bab37d6f62
* Content: [Reorganize and Rebuild Indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/reorganize-and-rebuild-indexes?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/indexes/reorganize-and-rebuild-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/reorganize-and-rebuild-indexes.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@MikeRayMSFT Hi Mike, This Issue 2244 concerns an article that is assigned to you.

@VanMSFT The Issue specifically concerns Security, so just FYI, maybe there is a chance that you would also be interested in this Issue 2244.

**Comment by MikeRayMSFT** [comment]
Thank you @kewelaka 
I'm staging an update

**Comment by MikeRayMSFT** [comment]
@kewalaka 

Would this clarify it for you?

Requires ALTER permission on the table or view. User must be a member of at least one of the following roles:
 * **db_ddladmin** database role <sup>1</sup> 
* **db_owner** database role
* **sysadmin** server role  

 <sup>1</sup>**db_ddladmin** database role is the [least privileged](https://docs.microsoft.com/windows-server/identity/ad-ds/plan/security-best-practices/implementing-least-privilege-administrative-models).

**Comment by kewalaka** [comment]
(y) looks good to me
Thanks Mike.

**Comment by MikeRayMSFT** [comment]
Thanks. The change is in flight. I'm having it reviewed. Will close the issues. Appreciate your submission & reply
