### ISSUE TITLE
SET FMTONLY (Transact-SQL)

### ISSUE THREAD

**Issue by sumankanthula** [MicrosoftDocs/sql-docs#2246]
Do not use this feature. This feature has been replaced by sp_describe_first_result_set (Transact-SQL), sp_describe_undeclared_parameters (Transact-SQL), sys.dm_exec_describe_first_result_set (Transact-SQL), and sys.dm_exec_describe_first_result_set_for_object (Transact-SQL).
---------------
The above statement gives a wrong impression. 
Ex : 
SET FMTONLY ON
EXEC "A PROCEDURE WHICH RETURNS multiple tables"
SET FMTONLY  OFF

executing the above statement will gives all the tables with columns those are part of SELECT CLAUSE, in other words it will provide all the tables schema without data. 

Now coming back to the issue, how can FMTONLY will be replaced by  sp_describe_first_result_set (Transact-SQL), sp_describe_undeclared_parameters (Transact-SQL), sys.dm_exec_describe_first_result_set (Transact-SQL), and sys.dm_exec_describe_first_result_set_for_object

While all of these objects provides only first result columns whereas the FMTONLY has more capabilities.

**Comment by MightyPen** [comment]
A fuller and runnable T-SQL code example, that demonstrates the points being raised in this Issue 2246 by @sumankanthula :


```sql
go
SET NoCount ON;

go
DROP PROCEDURE IF EXISTS prc_gm29;

DROP Table IF EXISTS #tabTemp41;
DROP Table IF EXISTS #tabTemp42;
go

CREATE TABLE #tabTemp41
(
	KeyInt41 int          not null,   -- Some values match KeyInt42, join-able.
	Name41   nvarchar(16) not null
);

CREATE TABLE #tabTemp42
(
	KeyInt42 int          not null,   -- Some values match KeyInt41, join-able.
	Name42   nvarchar(16) not null
);
go

INSERT into #tabTemp41 (KeyInt41, Name41) values (10, 't41-c');
INSERT into #tabTemp42 (KeyInt42, Name42) values (10, 't42-p');
go

CREATE PROCEDURE prc_gm29
AS
begin
SELECT * from #tabTemp41;
SELECT * from #tabTemp42;

SELECT t41.KeyInt41, t41.Name41, t42.Name42
	from
		           #tabTemp41 as t41
		INNER JOIN #tabTemp42 as t42 on t42.KeyInt42 = t41.KeyInt41
end;
go

SET FMTONLY ON;
EXECUTE prc_gm29;  -- "<A PROCEDURE WHICH RETURNS multiple tables>";
SET FMTONLY  OFF;
go
DROP PROCEDURE IF EXISTS prc_gm29;

DROP Table IF EXISTS #tabTemp41;
DROP Table IF EXISTS #tabTemp42;
go

/****  Actual Output:
[C:\JunkM\]
>> osql.exe -S myazuresqldb.database.windows.net -U somebody -P secret -d MyDatabase -i C:\JunkM\Issue-2246-a.SQL 

 KeyInt41    Name41        
 ----------- ----------------

 KeyInt42    Name42
 ----------- ----------------

 KeyInt41    Name41           Name42
 ----------- ---------------- ----------------


[C:\JunkM\]
>>
****/
```

**Comment by MightyPen** [comment]
@sumankanthula Hello, I understand now the points you are making. I see the strength in your points.
However, the SQL Server team sometimes must make small compromises with legacy features when it needs to improve and streamline the underlying architecture within the product. The SQL Server team is not planning on changing its plans for SET FMTONLY.

I am now Closing this Issue 2246. Thank you. We hope to hear from you again as you encounter documentation shortcomings.

**Comment by MightyPen** [comment]
Partially address by PR https://github.com/MicrosoftDocs/sql-docs-pr/pull/10510.
