### ISSUE TITLE
Feedback for new SQL Docs hubpage

### ISSUE THREAD

**Issue by MashaMSFT** [MicrosoftDocs/sql-docs#2249]
## https://aka.ms/sqldocs

For the month of June we're testing out a new hub page for the SQL Server technical documentation library. It's using a new design with updated links to commonly used or recommended content. Share your feedback by commenting on this issue.

New hub page can be seen here: https://aka.ms/sqldocs
Twitter reference: https://twitter.com/MashaMSFT/status/1115396660228526080

**Comment by ALZDBA** [comment]
SSMS 18.0 freezes frequently when doing things via the object explorer. ( Win 10 64-bit )
After waiting for to long, the only option is to kill the process using task manager. :-(

**Comment by MrM40** [comment]
Please keep a download link to version 17 on the page!
Version 18 still have so maaaaaany bugs! I can't believe you call this a release version, are you out of you mind?  Fare from ready to production environment!

**Comment by MrM40** [comment]
And for everybody else who need a working SSMS version, you can find them all here, incl. 17.9.1
https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#download-ssms-1791

**Comment by bartedgerton** [comment]
Please stop releasing broken software.   Please wait until you have at least fixed the MAJOR BUGS in your software.  If you are unable to fix the query window redraw problems, then why even bother making a release?  That problem renders the entire product useless.  https://feedback.azure.com/forums/908035-sql-server/suggestions/37474042-ssms-18-0-redraw-issues-when-switching-between-mul

**Comment by MichaelAntunes** [comment]
Worst ssms ever!!!!!!!!!!!!!!

I have already lost work hours because I simply cracked during the execution of a long-lasting command.

**Comment by MrM40** [comment]
Well, the SSMS developer team (and the rest of MS Co) have never understood KISS.
How much is the installation package...800MB? Should be 10MB 
And the setup program,  OMG!.
10 million files, 10 millions registry changes, 10 mill dependencies......no wonder the path of SSMS has always ALWAYS been full of pain and missiry. A system/program with so many dependencies will always be unstable and subject for failing.

**Comment by MashaMSFT** [comment]
Hello! A number of comments were left about SQL Server Management Studio (SSMS). These were all forwarded over to the SSMS team, and then deleted, as this forum is intended for feedback on the hub page :) Thank you all for your participation!

**Comment by isaacbouche** [comment]
helloo!! please help me to install it

**Comment by MashaMSFT** [comment]
Hi @isaacbouche , thanks for contacting Microsoft! You can find assistance with installing SQL Server here: https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server?view=sql-server-2017. Thanks!

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- please close this issue 2249 when the hub page preview is over.

**Comment by trstringer** [comment]
Test comment for @MashaMSFT.

**Comment by MashaMSFT** [comment]
Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We’ll contact you if we need further information, and you’ll receive an email message each time we “@mention” you in a comment. 
If you're suggesting a simple change to the documentation, it might be faster to submit the suggestion yourself by creating a GitHub pull request (PR). Here’s how:
1. On the page you have feedback about, select the **Edit** link at the top right.
1. On the next page, select the **Pencil** icon ( ) at the top right.
1. On the next page, in the **Edit file** text window, make your edits directly to the text you want to change.
    If you need help with formatting the new or changed text, see our Markdown Cheatsheet.
1. After you’ve made your edits, under **Commit changes**:
    a. In the first text box, enter a brief description of the change you’ve made.
    b. In the **Add an optional extended description** box, paste the link to your GitHub issue.
1. Select **Propose file change**.
1. On the **Comparing changes** page, select **Create pull request**.	
1. On the **Open a pull request** page, select **Create pull request**. 
    Allow a day or more for the article’s author to review and approve your change or offer an alternative solution.
    By opening a pull request, you’re helping the author add your approved change directly to the documentation. After the updated article is published, GitHub lists you as an article contributor.
If your issue is more complex than a simple change in the documentation, that’s okay.  We'll continue to research your suggestion and then get back to you with our response.
Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by MashaMSFT** [comment]
Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. Weâ€™ll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

If you're suggesting a simple change to the documentation, it might be faster to submit the suggestion yourself by creating a GitHub pull request (PR). Here's how:

1. On the page you have feedback about, select the **Edit** link at the top right.
1. On the next page, select the **Pencil** icon at the top right.
1. On the next page, in the **Edit file** text window, make your edits directly to the text you want to change.
    If you need help with formatting the new or changed text, see our [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).
1. After you've made your edits, under **Commit changes**:
    a. In the first text box, enter a brief description of the change you've made.
    b. In the **Add an optional extended description** box, paste the link to your GitHub issue.
1. Select **Propose file change**.
1. On the **Comparing changes** page, select **Create pull request**.
1. On the **Open a pull request** page, select **Create pull request**.

Allow a day or more for the article's author to review and approve your change or offer an alternative solution.

By opening a pull request, you're helping the author add your approved change directly to the documentation. After the updated article is published, GitHub lists you as an article contributor.

If your issue is more complex than a simple change in the documentation, that's okay.  We'll continue to research your suggestion and then get back to you with our response.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by thrainder** [comment]
Add more images for informative view
