### ISSUE TITLE
There is no example P.

### ISSUE THREAD

**Issue by AndreasHassing** [MicrosoftDocs/sql-docs#2250]
Hi,

At https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-2017#changing-the-size-of-a-column, you refer to an example P., but none such exists 😊.

_(On the webpage, Find "example P.", at the end of the section for H2 header "Changing the Size of a Column".)_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abcca5d2-d433-96cc-930e-4de020c5785d
* Version Independent ID: fde147ff-b157-502c-276a-d3a2bf9bb3c7
* Content: [ALTER TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-2017#changing-the-size-of-a-column)
* Content Source: [docs/t-sql/statements/alter-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by MightyPen** [comment]
@AndreasHassing I believe this Issue 2250 is now fixed.  Issue 2250 is now Closing.

Thank you for bringing this mistake to our attention. We hope to hear from you again.
