### ISSUE TITLE
Insert multiple rows

### ISSUE THREAD

**Issue by ChipDale66** [MicrosoftDocs/sql-docs#2251]
Example B to insert multiple rows does not work with Azure SQL Data Warehouse and Parallel Data Warehouse as the  table value constructor is not available in those systems. The wording needs to make this clear and suggest a workaround for inserting multiple rows for these two types of systems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ee2212c-0554-137e-323a-3e1fdf963791
* Version Independent ID: 8df2ab5c-395d-ffeb-8dbf-83da7ed14096
* Content: [INSERT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/insert-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/insert-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/insert-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@julieMSFT please review

**Comment by julieMSFT** [comment]
@ChipDale66 
thanks for bringing this to our attention! I am reviewing the entire article to identify the parts that apply to Azure SQL DW. I will notify you when the cahnges are made. Thanks!

**Comment by WilliamAntonRohm** [comment]
https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1571847

@julieMSFT Hi Julie, I have created work item 1571847 to track the unresolved status of this aging Issue 2251.
I am now closing this Issue.

**Comment by swanderz** [comment]
@WilliamAntonRohm  @julieMSFT what is the status of the table value constructor support in Azure Synapse (warehouse)? I cannot see the status of the above ADO work item. My understanding is that it still not supported, correct?

Just like #4864, my ask (as well as OP's, @ChipDale66), is two-fold:
1. add support for the table value constructor in Azure Synapse, and
2. per @ChipDale66, the docs should > suggest a workaround for inserting multiple rows

### example
```sql
INSERT INTO source.country_codes (country_code, country_name, continent) values
('NG', 'Nigeria', 'Africa'),('NP', 'Nepal', 'Asia')
```
`Failed to execute query. Error: Parse error at line: 2, column: 28: Incorrect syntax near ','.`

**Comment by julieMSFT** [comment]
@swanderz @ChipDale66 Hi, I have updated the INSERT (Transact-SQL) - SQL Server article to state that the table value constructor is not supported in Azure Synapse Analytics. I have added this as a [suggestion](https://feedback.azure.com/forums/307516-azure-synapse-analytics/suggestions/43031034-add-support-for-the-table-value-constructor) for Azure Synapse. Please vote for this suggestion if you would like to see it added to Azure Synapse. Thank you for contacting Microsoft and contributing to Microsoft Docs.

**Comment by swanderz** [comment]
thanks @julieMSFT!!! I [added](https://github.com/dbt-msft/dbt-synapse/commit/5926747aadd3b18d0a47c2fbcbf639932f1881a4) your [UserVoice suggestion](https://feedback.azure.com/forums/307516-azure-synapse-analytics/suggestions/43031034-add-support-for-the-table-value-constructor) to my running Synapse TSQL wishlist!

![you da real mvp](https://media1.tenor.com/images/b134840f2966488f9e65e62d6745f38b/tenor.gif?itemid=5953316)
