### ISSUE TITLE
Next steps configuration guides link missing

### ISSUE THREAD

**Issue by jsongy** [MicrosoftDocs/sql-docs#2252]
Next steps configuration guides is missing the link to ODBC Generic Types: https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-configure-odbc-generic?view=sql-server-ver15 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ebefef-f8c5-e429-269e-1ef7a96264fd
* Version Independent ID: a8009495-9bb9-87f4-85af-0ac0074749e7
* Content: [What is PolyBase? - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-guide?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/polybase/polybase-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-guide.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
Fixing Issue 2252 with private repo PR 10601:
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10601

**Comment by MightyPen** [comment]
@jsongy PR 10601 has fixed this Issue 2252. The fix should become visible on our Docs website in about 24 hours.

Thank you for bringing this concern to our attention. We hope to hear from you again.
I am now Closing this Fixed issue.
