### ISSUE TITLE
Transact-SQL Reference under SSMS in TOC

### ISSUE THREAD

**Issue by kevinoid** [MicrosoftDocs/sql-docs#2253]
Navigating directly to https://docs.microsoft.com/en-us/sql/t-sql/language-reference causes the TOC sidebar to show "Tools > SQL Server Management Studio (SSMS) > References > Transact-SQL Reference (Database Engine)" which has no child elements.  This is significantly less useful than "Reference > Transact-SQL (TSQL) > Transact-SQL (TSQL)" which refers to the same URL, but the TOC hierarchy includes "Data types", "Functions", "Queries",  "Statements" and the other TSQL reference material.

### Sub-optimal default TOC sidebar:
![Sub-optimal TOC Sidebar Screenshot](https://user-images.githubusercontent.com/336433/58889442-6f4ebd80-86d8-11e9-8496-6ddb9ffcb520.png)

### Better non-default TOC sidebar:
![Better TOC Sidebar Screenshot](https://user-images.githubusercontent.com/336433/58889460-7675cb80-86d8-11e9-92f8-208f005bd9ca.png)

Thanks for considering,
Kevin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c90a9561-bef5-25e8-e672-ed0d4493a383
* Version Independent ID: 16c705c1-55be-d339-8326-51d57cb0fd69
* Content: [Transact-SQL Reference (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-reference?view=sql-server-2017)
* Content Source: [docs/t-sql/language-reference.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-reference.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
Fixed, with new PR 10545.
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10545

@kevinoid Hello Kevin, Thank you very much for bringing this duplicate entry situation/problem in the TOC to our attention.  We rarely intend such duplicates, but this duplicate slipped in anyway by accident.
PR 10545 is eliminating the duplicate that neither you nor us want in the TOC.

The fix should be visible on live Docs website within approximately one business day.

I am now Closing this fixed Issue 2253.

**Comment by kevinoid** [comment]
Great.  Thanks @MightyPen!
