### ISSUE TITLE
SSMS v18 GA not starting

### ISSUE THREAD

**Issue by AshleySilver** [MicrosoftDocs/sql-docs#2255]
Installed OK on Win764 
.. but now get a failure starting with the following message:

The application has failed to start because its side-by side configuration is incorrect. Please 
see the application event log or use the command-line sxstrace.exe tool for more detail. 

There are no further hints to how to solve.

I do have SMSS v16 installed already, but it would appear that it is kosher to have both ...

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, This Issue 2255 suggests that SSMS can have a side-by-side configuration problem.  Can you please process this request.  However, if you find this Issue 2255 is Not a documentation shortcoming, you have broad discretion on how/whether to further process before closing this.
Thanks.
CC: @stevestein

**Comment by markingmyname** [comment]
@AshleySilver,

Can I ask if you have tried to download SSMS version 18.1 and getting the same result?

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.

Please visit [UserVoice](https://feedback.azure.com/forums/908035-sql-server) to offer more technical feedback.
