### ISSUE TITLE
Example C

### ISSUE THREAD

**Issue by snaddon** [MicrosoftDocs/sql-docs#2261]
For example C, was this really the result?
The column headers don't match the script?
Do the RankResult results make sense?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d0e965-5cdb-6c09-71bc-d3ad7acaad18
* Version Independent ID: 2925bec4-5818-8c98-fd51-7689d741fe1f
* Content: [RANK (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/rank-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/rank-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/rank-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@snaddon Thank you for the feedback.

Your change to headers has been processed, though the data used is for test purposes only.
