### ISSUE TITLE
Contradiction on Statements at (SQL Server 2017 (14.x) Functional)

### ISSUE THREAD

**Issue by nkumar230** [MicrosoftDocs/sql-docs#2263]
SQL Server 2017 (14.x) supports non-persisted computed columns in clustered columnstore indexes. Persisted columns are not supported in clustered columnstore indexes.

From the above, Could you confirm whether Non-Persisted Computed Columns are allowed/not allowed as part of Clustered Columnstore Index.

Thanks
Naveen Thummalapenta
MCSA|MCP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f005780-e6f8-10e5-a891-00a20254a64b
* Version Independent ID: 5d875140-6fb9-d85b-3e15-fa440bc49096
* Content: [Columnstore indexes - what's new - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-what-s-new?view=sql-server-2017#section)
* Content Source: [docs/relational-databases/indexes/columnstore-indexes-what-s-new.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/columnstore-indexes-what-s-new.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@MikeRayMSFT hi Mike, I CC'ed you on an email to Component owner Sasa T.
Hopefully there will be a clarifying answer that you can relay.

**Comment by MikeRayMSFT** [comment]
@nkumar230  - we have submitted an update to clarify. 

"Persisted computed columns are not supported in clustered columnstore indexes."
