### ISSUE TITLE
Automatic Seeding option

### ISSUE THREAD

**Issue by andyhush-athena** [MicrosoftDocs/sql-docs#2265]
You forgot to document the first option on the Select Initial Data Synchronization page: "Automatic Seeding"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d4a2bb4-93b7-3ef7-ccdb-b0312208f062
* Version Independent ID: 1288b338-f71d-19cd-5415-ddef24d65151
* Content: [Add a database to an availability group with the 'Availability Group Wizard' - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/availability-group-add-database-to-group-wizard?view=sql-server-2017)
* Content Source: [docs/database-engine/availability-groups/windows/availability-group-add-database-to-group-wizard.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/availability-group-add-database-to-group-wizard.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MightyPen** [comment]
@MashaMSFT Hi Masha, Can you please process this Issue 2265, about Availability Groups.

**Comment by MashaMSFT** [comment]
Hi @andyhush-athena , 

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by MashaMSFT** [comment]
Hi @andyhush-athena , thanks again for bringing this to our attention! I have added a section discussing automatic seeding. Please let me know if there is anything else we can do for you? If not, I will proceed with closing out this Git Issue in a few business days.

Thanks!

**Comment by andyhush-athena** [comment]
Looks great, thanks!
