### ISSUE TITLE
BUG? Beware! Using over 8 arguments may lead to duplicate checksums being calculated...

### ISSUE THREAD

**Issue by ggoodfrd** [MicrosoftDocs/sql-docs#2266]
SELECT CHECKSUM(1,0,0,0,0,0,0,0,0) -- 1
SELECT CHECKSUM(0,0,0,0,0,0,0,0,1) -- 1

SELECT CHECKSUM(1,0,0,0,0,0,0,0,0,0) -- 16
SELECT CHECKSUM(0,0,0,0,0,0,0,0,1,0) -- 16

SELECT CHECKSUM(1,0,0,0,0,0,0,0,0,0,0) -- 256
SELECT CHECKSUM(0,0,0,0,0,0,0,0,1,0,0) -- 256

SELECT CHECKSUM(1,0,0,0,0,0,0,0,0,0,0,0) -- 4096
SELECT CHECKSUM(0,0,0,0,0,0,0,0,1,0,0,0) -- 4096

SELECT CHECKSUM(1,0,0,0,0,0,0,0,0,0,0,0,0) -- 65536
SELECT CHECKSUM(0,0,0,0,0,0,0,0,1,0,0,0,0) -- 65536

SELECT CHECKSUM(1,0,0,0,0,0,0,0,0,0,0,0,0,0) -- 1048576
SELECT CHECKSUM(0,0,0,0,0,0,0,0,1,0,0,0,0,0) -- 1048576

SELECT CHECKSUM(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0) -- 16777216
SELECT CHECKSUM(0,0,0,0,0,0,0,0,1,0,0,0,0,0,0) -- 16777216

SELECT CHECKSUM(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0) -- 268435456
SELECT CHECKSUM(0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0) -- 268435456

SELECT CHECKSUM(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0) -- 1
SELECT CHECKSUM(0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0) -- 1

SELECT CHECKSUM(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0) -- 16
SELECT CHECKSUM(0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0) -- 16
SELECT CHECKSUM(1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0) -- 16

SELECT CHECKSUM(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0) -- 256
SELECT CHECKSUM(0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0) -- 256
SELECT CHECKSUM(1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0) -- 256

SELECT CHECKSUM(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123) -- 379
SELECT CHECKSUM(0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,123) -- 379
SELECT CHECKSUM(1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,123) -- 379

SELECT CHECKSUM(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'ETC...') -- 159919566
SELECT CHECKSUM(0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,'ETC...') -- 159919566
SELECT CHECKSUM(1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,'ETC...') -- 159919566

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 854e5542-ae5e-098e-7bbf-3005953f14d3
* Version Independent ID: 597e2c06-935d-1742-6dd4-906294d2a6f3
* Content: [CHECKSUM (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/checksum-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/checksum-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/checksum-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by ggoodfrd** [comment]
It looks like BINARY_CHECKSUM also exhibits the same behavior...

**Comment by MightyPen** [comment]
@MikeRayMSFT These might be "edge" conditions, with value sets carefully designed for a demo of a truth that may be of little or no practical consequence in the daily business world.  If so, it would perhaps not be helpful to add mention of such cases into the live Docs article, tho ultimately it is a matter of personal judgment.

Also, CheckSum is openly direct that it sometimes returns the same values even when given different input.  The rate of duplication is believed to be small and reasonable in practical use. The citation of specially designed edge cases that show a higher rate of duplicate values might not be helpful to the large majority of Docs readers.

Or, perhaps one cautionary sentence could be added to the effect that - More the eight parameters might be counter-productive toward the goal of generating unique returned values from CheckSum().

It is all for you to decide, as you own the article.

**Comment by MikeRayMSFT** [comment]
@ggoodfrd thank you. Reviewing.

**Comment by MikeRayMSFT** [comment]
@ggoodfrd - `CHECKSUM()` uses a relatively simple but fast algorithm for checksum calculation based on shifting and XORing for INT. It should be used to build hash indexes and for that purpose it is fast and good enough.

Another example, `CHECKSUM_AGG` is designed to detect changes in a group of values – a simple XOR on inputs is very fast and good enough algorithm for this.

On the other hand, `HASHBYTES` intrinsically supports common checksums such as MD2 | MD4 | MD5 | SHA | SHA1 | SHA2_256 | SHA2_512, but is much slower.

We're working to update the documentation to explicitly state that `CHECKSUM()` does not guarantee unique results.

Thank you.

**Comment by ggoodfrd** [comment]
Thanks for the clarification. I fully understand that the function would take an approach that is optimized for performance since it has to process the input of each parameter, which could be large strings, for example. It's good to mention the performance differences as you have here, as one might not have understood that impact without taking time to set up some examples with large datasets, etc. I appreciate that you're going to update the docs to show the limitations and which options might be better for determining uniqueness when checking a large number of inputs together. 

I believe over the years the term checksum has sort of become analogous to being like a "fingerprint" for whatever it's calculated on, which many would consider to be a unique identifier.

Thanks again for the detailed response and subsequent doc updates!
