### ISSUE TITLE
No examples of results with 1:n joins

### ISSUE THREAD

**Issue by bendodge-xwis** [MicrosoftDocs/sql-docs#2268]
It would be very helpful to see examples that include multiple results from the joined tables. For example, a class table joined to a students table. All the given examples appear to be 1:1 joins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb5c17b-c567-303f-00b8-0c8a0ad15fb5
* Version Independent ID: a4ccc766-4a61-5b7a-e5dd-692e3cebb503
* Content: [Format Query Results as JSON with FOR JSON (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-2017#option-2---select-statement-controls-output-with-for-json-auto)
* Content Source: [docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md)
* Product: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by MightyPen** [comment]
Fixed, by new PR 10544:
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10544

Hello @bendodge-xwis , Thank you for this feedback here in Issue 2268.
The new PR 10544 adds T-SQL example '2.b', which should become visible on live Docs with a business day or so.
I am now Closing this fixed Issue.

CC: @jovanpop-msft
