### ISSUE TITLE
Add information related to Exit codes of Sqlpackage

### ISSUE THREAD

**Issue by blueelvis** [MicrosoftDocs/sql-docs#2273]
Could you please add information related to Exit Codes of the `sqlpackage` to this document?

Thanks,
Pranav

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage.exe - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-2017#command-line-syntax)
* Content Source: [docs/tools/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage.md)
* Product: **sql**
* Technology: **ssdt**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by pensivebrian** [comment]
It follows the standard convention as most command line tools:
0 = success
non-zero = failure

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, Maybe you can update the article, with the info Brian gave about ==0 return code etc.  Then Close this Issue 2273.

@pensivebrian Brian, Thanks much for supply the needed info here so quickly.

**Comment by blueelvis** [comment]
Thanks!

**Comment by markingmyname** [comment]
Thank you, @pensivebrian.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
