### ISSUE TITLE
Cannot "Select the columns in the existing table..."

### ISSUE THREAD

**Issue by tomwimmenhove** [MicrosoftDocs/sql-docs#2276]
In SQL Server Management Studio v17.9.1 there is no option to "Select the columns in the existing table" as described in the instructions. Not in the object explorer nor in the design window.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4a6423-c509-5cc1-30f9-1fb55fe26833
* Version Independent ID: af8a0bd9-a993-8458-aebf-3ecc1462b228
* Content: [Duplicate Tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/duplicate-tables?view=sql-server-2017)
* Content Source: [docs/relational-databases/tables/duplicate-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/duplicate-tables.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, This SSMS Issue 2276 should probably be assigned to you, instead of to Steve (even though Steve is the 'ms.author'). But if I am mistaken, you can reAssign this Issue to Steve as you see fit.

CC: @stevestein

**Comment by markingmyname** [comment]
@tomwimmenhove,

Can I ask if you have tried that functionality in SSMS version 18.1?

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.

Please visit [UserVoice](https://feedback.azure.com/forums/908035-sql-server) to offer more technical feedback.
