### ISSUE TITLE
Error...

### ISSUE THREAD

**Issue by cbrsa** [MicrosoftDocs/sql-docs#2277]
Running on Ubuntu 19.04 connects and finds databases. Expanding node in Servers gets: Provider doesn't exist. id: PGSQL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7a41315-7a52-24f3-5b67-5e459d45afc4
* Version Independent ID: 401a2908-a73c-ccf9-ce58-a416f422d568
* Content: [PostgreSQL extension (preview) - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/postgres-extension?view=sql-server-2017#feedback)
* Content Source: [docs/azure-data-studio/postgres-extension.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/postgres-extension.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @rachel-msft
* Microsoft Alias: **raagyema**

**Comment by MightyPen** [comment]
@rachel-msft Hi Rachel, can you please process this customer Issue 2277.

@markingmyname Mark, As the Writer in this area of docs/azure-data-studio/, can you please assist Rachel if necessary, and please help ensure this Issue is process and eventually Closed.  Thanks, G.

**Comment by rachel-msft** [comment]
@cbrsa Thank you for reaching out and our apologies for the error. To resolve this, go to the Extensions menu (the square icon on the left toolbar). Reload the Postgres extension to get version 0.2.0. Once the reload is completed, the Output window will read "Installed". Then you will be able to connect to the server.

Let us know if you have any questions.

@MightyPen please close

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, I will leave it to you to decide if/when to Close this Issue 2277. For instance, I dunno whether first adding something like Rachel's feedback (in above Comment) to the article would be a good idea or not. In any case, you have the honor/duty of taking the next action toward processing and finishing this Issue 2277.
Thanks.

CC: @rachel-msft

**Comment by cbrsa** [comment]
@rachel-msft thanks for the quick update

**Comment by markingmyname** [comment]
As it being part of a preview, I will wait for GA to add to this article with this information.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
