### ISSUE TITLE
yum repro path not correct

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#2279]
@tire0011 commented on [Fri Jun 07 2019](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/84)

curl https://packages.microsoft.com/config/rhel/7/prod.repo &gt; /etc/yum.repos.d/msprod.repo
should be 
curl https://packages.microsoft.com/config/rhel/7/prod.repo &gt; /etc/yum/repos.d/msprod.repo

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Installieren von SQL Server-Befehlszeilentools unter Linux - SQL Server](https://docs.microsoft.com/de-de/sql/linux/sql-server-linux-setup-tools?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by CeciAc** [comment]
Hi team, 
The contributor is reporting a typo in the codebox
best

**Comment by rothja** [comment]
@CeciAc Thank you for the feedback. However, I think the `/yum.repos.d` is correct based on our testing and the RHEL documentation [here](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sec-configuring_yum_and_yum_repositories): "However, it is recommended to define individual repositories in new or existing .repo files in the /etc/yum.repos.d/ directory". Maybe I need more information on this one or a different version of linux is being used in this case? Let me know if there is something I'm missing. Thank you!

**Comment by MightyPen** [comment]
PR 10575 has manually reverted the unwanted fix that I rushed in.
So now the *.md article file is back to as it was.

@tire0011 @CeciAc @rothja 

I think this Issue 2279 can now be Closed. I leave it to RothJa to close, when he sees fit. (This Issue 2279 is now Assigned to RothJa.)

**Comment by rothja** [comment]
@CeciAc Yes, I think wee need to close this unless there is any further data for the repository differences from our tests or the article. Thank you!
