### ISSUE TITLE
SQL Query throws divide by zero errors

### ISSUE THREAD

**Issue by mjlafever** [MicrosoftDocs/sql-docs#2281]
The fragmentation line of the select statement doesn't handle zeros for total rows, which I run into almost every time I run this.  
100*(ISNULL(deleted_rows,0))/NULLIF(total_rows,0) AS 'Fragmentation'   is how I handle it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a24a194b-16d9-79e4-8483-95aaf2833c67
* Version Independent ID: 108fd3b5-631f-384f-25a0-6badb3a26428
* Content: [sys.dm_db_column_store_row_group_physical_stats (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-column-store-row-group-physical-stats-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-db-column-store-row-group-physical-stats-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-db-column-store-row-group-physical-stats-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
Fixing with PR 10582.
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10582

@mjlafever Hello, Thank you for this code improvement. It makes good sense. Your improvement should be visible on live Docs within 1-2 business days.
You always have the option of using either an Issue like this Issue 2281, or instead a Pull Request (PR). Today's code improvement would be an excellent fit for a PR, wherein you code edit our source documentation directly, cutting out our task of middleman. To start a PR, just click the 'Edit-pencil' icon at the top-right of the Docs webpage, and then click the similar icon on the GitHub webpage.  Not required of course, but a PR is a nicely direct option.
We hope to hear from you again!

I am now Closing this Issue 2281 as fixed.

CC: @stevestein Steve, I opted to fix this Issue, even though I am not the formal owner.  Just fyi.
