### ISSUE TITLE
Nearest neighbour query limited

### ISSUE THREAD

**Issue by rbrundritt** [MicrosoftDocs/sql-docs#2282]
The nearest neighbor documentation for SQL spatial queries is a really basic approach looking at distances. It might also be worth calling out the radial search approach as well where the user wants to find all locations within a specified distance. I've seen many people take the same approach as the nearest neighbor query and simply compare to the search radius. This does work, but is one of the slowest approaches. A significantly faster approach is to;

1. Buffer the point using the radius as the buffer distance. This creates a geo-circle polygon. 
2. Use the spatial intersections function with the buffer.
3. And of course, use a spatial index.

If they also want the distance, they can use the Filter function instead of the spatial intersection which is faster but returns false positives, then on the filtered data use the distance function and check against radius.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 731d3077-c535-c05d-d71c-f739dc1bb0f8
* Version Independent ID: 5981a97b-7d3c-ea32-2507-5a7ac2cc55a1
* Content: [Query Spatial Data for Nearest Neighbor - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/query-spatial-data-for-nearest-neighbor?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/spatial/query-spatial-data-for-nearest-neighbor.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/spatial/query-spatial-data-for-nearest-neighbor.md)
* Product: **sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by MightyPen** [comment]
@MladjoA Hello Mladen, can you please consider this customer Issue 2282, about Spatial functionality in SQL Server.

If you want assistance with the mechanics of the Issue/PR process, please ping either me (MightyPen = GeneMi at Msft), or to Jason Roth (RothJa = JRoth at Msft).
CC: @rothja

**Comment by mburbea** [comment]
From my testing in this with Sql 2016, or Sql 2012+ with traceflag 6533 on I found that buffering tended to be slower then using a simple distance search, when you moved past small distances. Here is census block centroids plotted (11million points in the US), and a search of 10 miles around a coffee shop in SF.

```
declare @p0 geography=geography::Point(37.7824618,-122.4099503,4326)
declare @s datetime2 = sysutcdatetime()
exec SP_executeSQL N'
declare @i int = (select count(*)
from dbo.census_block rb
where rb.latlong.STDistance(@p0) <= 1609.344e1)',N'@p0 geography',@p0
print concat('Distance from point:',datediff(ms,@s,sysutcdatetime()))
go
declare @p0 geography=geography::Point(37.7824618,-122.4099503,4326).STBuffer(1609.344e1)
declare @s datetime2 = sysutcdatetime()
exec SP_executeSQL N'
declare @i int = (select count(*)
from dbo.census_block rb
where rb.latlong.STIntersects(@p0) = 1)',N'@p0 geography',@p0
print concat('Intersect STBuffer:',datediff(ms,@s,sysutcdatetime()))
go
declare @p0 geography=geography::Point(37.7824618,-122.4099503,4326).BufferWithCurves(1609.344e1)
declare @s datetime2 = sysutcdatetime()
exec SP_executeSQL N'
declare @i int = (select count(*)
from dbo.census_block rb
where rb.latlong.STIntersects(@p0) = 1)',N'@p0 geography',@p0
print concat('Intersect Buffer With Curve:',datediff(ms,@s,sysutcdatetime()))
```
Printed::
```
Distance from point:83
Intersect STBuffer:124
Intersect Buffer With Curve:1346
```

**Comment by rbrundritt** [comment]
Is there a spatial index involved here? I don’t see any mention of it in the queries. That makes a big difference.

These numbers don’t align with the nearest neighbor section of the “Pro Spatial with SQL Server 2012” book. Nor what we have seen in the wild.

**Comment by mburbea** [comment]
Indeed, with a spatial index in play. 
`create spatial index s_census_block_latlong on census_block(latlong)`
Basically default settings. All 3 plans do use the index.


The key point is traceflag 6533, or using sql server 2016. This flag turns on native code for the STDistance calculation (Personally, I'd enable 6532,6533, and 6534 on non-2016 instances).
https://blogs.msdn.microsoft.com/bobsql/2016/06/03/sql-2016-it-just-runs-faster-native-spatial-implementations/
https://dba.stackexchange.com/questions/98044/how-to-optimize-stdistance-execution/199201#199201

For trivial distances (say around ~5miles or less), filter and then distance checking might be faster but larger distance, Distance just wins. 

My experience is that most articles on spatial in sql server are out of date on newer revisions. (See this awful example where part of the speed up comes from the fact that they have **wildly** truncated the query distance by dividing by an int rather than a float).
https://social.technet.microsoft.com/wiki/contents/articles/9694.tuning-spatial-point-data-queries-in-sql-server-2012.aspx

Query plans:
https://www.brentozar.com/pastetheplan/?id=Bku-jFU1H

**Comment by rbrundritt** [comment]
Interesting, I haven’t seen these flags before. I heavily used the spatial functionality in 2008 and 2012 so know the tricks for those platforms, but missed these newer optimizations.

Going on a tangent, it would be good to sync on the spatial functionality in SQL with the Azure Maps team as they have been getting a lot of requests for more spatial functionality in SQL. Happy to discuss offline.

**Comment by rbrundritt** [comment]
Any chance these flags can be used with the .NET library?

From: Ricky Brundritt
Sent: Tuesday, June 18, 2019 2:39 PM
To: MicrosoftDocs/sql-docs <reply@reply.github.com>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [MicrosoftDocs/sql-docs] Nearest neighbour query limited (#2282)

Interesting, I haven’t seen these flags before. I heavily used the spatial functionality in 2008 and 2012 so know the tricks for those platforms, but missed these newer optimizations.

Going on a tangent, it would be good to sync on the spatial functionality in SQL with the Azure Maps team as they have been getting a lot of requests for more spatial functionality in SQL. Happy to discuss offline.
