### ISSUE TITLE
Practical guide to restoring msql database on Linux machine

### ISSUE THREAD

**Issue by hareldvd** [MicrosoftDocs/sql-docs#2284]
Really great article. Used it on my Fedora desktop. Works smooth. 
Had to install MSQL Server also in article https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-2017 which is also great.
Nice to see that Microsoft finally behaves well.

Cheers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8714d60-ce51-aa48-7619-cc95a8843a7f
* Version Independent ID: 9580d01a-4d40-bcca-2c05-72aa069370d0
* Content: [Migrate a SQL Server database from Windows to Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-migrate-restore-database?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-migrate-restore-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-migrate-restore-database.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@hareldvd We are very glad to hear that the product, and its documentation article, are both being well-received and are helping customers. We make considerable efforts to keep these "tutorial" type articles up-to-date, and we care very much if they ever need any fix.
As you can see, we read ALL feedback Issues usually within 1 business day. I will pass along this feedback to the SQL team members who work in this particular area.

I am now closing this successful Issue 2284. However, the @ notification mechanism continues to function, in case further communication is needed.

CC: @MikeRayMSFT @rothja
