### ISSUE TITLE
On my Fedora 28 I had to install SQL Server 2019

### ISSUE THREAD

**Issue by hareldvd** [MicrosoftDocs/sql-docs#2285]
SQL Server 2017 had dependency issues:
Error: 
 Problem: conflicting requests
  - nothing provides openssl &lt; 1:1.1.0 needed by mssql-server-14.0.1000.169-2.x86_64

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b543b57-f397-779d-6fe4-1bc2ecd3bdca
* Version Independent ID: e274a0f3-ec74-e809-f4d3-515782b29a92
* Content: [Get started with SQL Server on Red Hat Enterprise Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-red-hat?view=sql-server-2017)
* Content Source: [docs/linux/quickstart-install-connect-red-hat.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-red-hat.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@rothja Hi Jason, can you please process this SQL-Linux Issue 2285. Perhaps the article needs to list an additional dependency that not all computers have?

**Comment by rothja** [comment]
@hareldvd Hello, and thanks for the feedback. As I understand it, this was an issue installing on Fedora? Unfortunately, we have only tested and supported Red Hat, Ubuntu, & SLES. Although Fedora is closely related to Red Hat, it is possible that it is ahead of the 7.* versions that we support of RHEL. I am assuming that as we support the most recent releases of RHEL, that Fedora installations will work smoothly as well. I will close this git issue, but you are welcome to respond and follow-up on this issue with any questions or comments. Thank you!!
