### ISSUE TITLE
Duplicate Entries :- "Configure and Manage Thesaurus Files for Full-Text Search"

### ISSUE THREAD

**Issue by DanielAdeniji** [MicrosoftDocs/sql-docs#2287]
[Enter feedback here]

Duplicate entries

Configure and Manage Thesaurus Files for Full-Text Search
Configure and Manage Thesaurus Files for Full-Text Search

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e853088-457a-39c0-1be2-5072571073d5
* Version Independent ID: df2a36de-4985-f0c6-5905-6c5523686889
* Content: [sp_fulltext_load_thesaurus_file (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-fulltext-load-thesaurus-file-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-fulltext-load-thesaurus-file-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-fulltext-load-thesaurus-file-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
PR 10591, in our private sister repo, is fixing this Issue 2287.
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10591

@DanielAdeniji Hi Daniel, Thank you for bringing this problem to our attention. The fix should be visible on our live Docs website before you go to bed tonight  :-) 
We hope to hear from you again.

Now I am Closing this fixed Issue 2287.

**Comment by DanielAdeniji** [comment]
Gene :-

Thanks Bro.

I visited
https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-fulltext-load-thesaurus-file-transact-sql?view=sql-server-2017
and
validated that the duplicated "Configure and Manage Thesaurus Files for
Full-Text Search" is indeed corrected.

Thanks so much for the attentiveness.

Daniel
