### ISSUE TITLE
How does one retrieve the newly generated GUID?

### ISSUE THREAD

**Issue by veljkoz** [MicrosoftDocs/sql-docs#2288]
For example, if the column was marked as Identity, we can do it via @@IDENTITY, but how do we get the newly inserted value if it's marked as NEWSEQUENTIALID ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a9b1a70-e8a4-9558-0e31-c665ccd761a7
* Version Independent ID: e1a957ad-dbbc-fa7a-93c7-8d3c20ec175a
* Content: [NEWSEQUENTIALID (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/newsequentialid-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/newsequentialid-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/newsequentialid-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@MikeRayMSFT Hi Mike, I see the customer's point, that there should be a GUID analogy to @@identity.
Ideally you can contact the relevant owner who could consider providing something like @@NewSequentialId, perhaps.

**Comment by veljkoz** [comment]
In the end I resolved it in a more general way:

```
DECLARE @NewSequentialId UNIQUEIDENTIFIER
DECLARE @InsertedIds TABLE(Id UNIQUEIDENTIFIER)
INSERT INTO MyTable(Field1, Field2)
OUTPUT Inserted.Id INTO @InsertedIds
VALUES ('abcd', 'efgi')
SET @NewSequentialId = (SELECT TOP 1 Id FROM @InsertedIds)
```
(I haven't checked the syntax here, I'm typing out of my head)

Although it's a bit more typing, it worked for my case. 

Thanks!

**Comment by srutzky** [comment]
FYI:

1. In most cases you should be using the [SCOPE_IDENTITY()](https://docs.microsoft.com/en-us/sql/t-sql/functions/scope-identity-transact-sql) built-in function instead of `@@IDENTITY`. And so, any request for similar functionality for `NEWID()` and `NEWSEQUENTIALID()` would need to mirror `SCOPE_IDENTITY()` (e.g. "SCOPE_ID()" perhaps?)

1. The `OUTPUT` clause is probably the preferred approach since it can also capture new values created from multi-row inserts, something that neither `@@IDENTITY` nor `SCOPE_IDENTITY()` can do.

Take care,
Solomon..

**Comment by MikeRayMSFT** [comment]
@pmasl  or @DBArgenis do you have any comment here?

**Comment by DBArgenis** [comment]
OUTPUT is the way to go here.

**Comment by mburbea** [comment]
Output isn't a perfect replacement for scope_identity.
Consider, if you insert your value with an output clause? How do you get the scope_identity then?
```sql
update dbo.some_table
set some_property=@val
output 'some_table',inserted.id,'some_property',deleted.val,inserted.val into dbo.audit_trail(table,key,column,old_val,new_val)
where id = @id
```
How do I get the audit_trail inserted id without scope_identity() here?
