### ISSUE TITLE
What to use instead If privacy is a concern

### ISSUE THREAD

**Issue by Sammers21** [MicrosoftDocs/sql-docs#2290]
There is a notice:

```
If privacy is a concern, do not use this function. It is possible to guess the value of the next generated GUID and, therefore, access data associated with that GUID.
```

But what can be used instead if privacy is a concern? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a9b1a70-e8a4-9558-0e31-c665ccd761a7
* Version Independent ID: e1a957ad-dbbc-fa7a-93c7-8d3c20ec175a
* Content: [NEWSEQUENTIALID (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/newsequentialid-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/newsequentialid-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/newsequentialid-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
The key column in your table can be specified as type UniqueIdentifier. Then assign
`SET @myNewId = NewId();`
Then use @myNewId in your INSERT statement.

The privacy issue is inherent in NewSequentialId through nobody's fault. By its very definition, it limits the generated guid value to a narrow range, thereby inherently making the value somewhat predictable.

The downside of having this kind of privacy actually matter, in a given case, is more page splits on INSERTs.

With this Issue 2290 now answered, I am now Closing this Issue.
Thank you for contacting us. We hope to hear from you again.

CC: @MikeRayMSFT just for awareness, no action.
