### ISSUE TITLE
Question - Section: Relationship between cluster timeout and lease timeout

### ISSUE THREAD

**Issue by bkscharf** [MicrosoftDocs/sql-docs#2294]
The first sentence reads:  "The primary function of the lease mechanism is to take the SQL Server resource..."

Is the word "offline" missing here, such as "The primary function of the lease mechanism is to take the SQL Server resource offline..." or am I reading too much into it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8705fa-b6ec-b933-a355-5de9eacc807f
* Version Independent ID: e6cd791d-b0f4-663d-5d07-b2850784cf37
* Content: [Mechanics of the availability group lease health check timeout - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/availability-group-lease-healthcheck-timeout?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/availability-group-lease-healthcheck-timeout.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/availability-group-lease-healthcheck-timeout.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MightyPen** [comment]
@MashaMSFT Hi Masha, here is the whole sentence.  Can you please process this Issue 2294.

"The primary function of the lease mechanism is to take the SQL Server resource in the case that the cluster service cannot communicate with the instance while performing a failover to another node."

**Comment by MashaMSFT** [comment]
Hi @bkscharf , 

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by MashaMSFT** [comment]
Hi @bkscharf , you're right, the word "offline" is missing. Did you want to add it  yourself? 

You can do so by following these steps:

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) format
5. Name your file change and copy the link to your Git Issue into the "extended description" box
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page
9. Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing so will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and list you as a contributor to the documentation.

Thanks!

**Comment by MashaMSFT** [comment]
Hi @bkscharf ,

Thanks again for contacting Microsoft!  We've submitted a documentation change based on your suggestion, and it should be live at this point. Please let us know if there is anything more we can do for you? If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a wonderful rest of your day!
