### ISSUE TITLE
Inconsistent file names and path

### ISSUE THREAD

**Issue by graystormtrooper** [MicrosoftDocs/sql-docs#2301]
In "Create the certificate on secondary servers", the file paths are inconsistent with the previous section. It seems to use *nix like paths (/var/opt...) instead of the Windows paths. This is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e357702e-ddfb-eb9c-d6a5-a5274d87b320
* Version Independent ID: a809b6ec-7bf2-4cce-b4af-c06fdd1b00bd
* Content: [Configure read-scale for an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-read-scale-availability-groups?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/configure-read-scale-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/configure-read-scale-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- please check into this discrepancy.  The examples appear to be first Windows and then Linux, but I'm not sure.

#2301

**Comment by MashaMSFT** [comment]
Hi @graystormtrooper , 

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by MashaMSFT** [comment]
Hi @graystormtrooper , 

Thanks again for contacting Microsoft!  We've submitted a documentation change based on your suggestion, and it should be live at this point. Please let us know if there is anything more we can do for you? If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a wonderful rest of your day!

**Comment by graystormtrooper** [comment]
Great. That's all, thanks.
