### ISSUE TITLE
Link for 17.9.1

### ISSUE THREAD

**Issue by MrM40** [MicrosoftDocs/sql-docs#2302]
As a courtesy and respect for everybodies time, a respect MS apparent don't have by publishing a version that is so full of bugs and not providing a link the previous versions, I hereby provide the download link for 17.9.1.
https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#download-ssms-1791

Last time I tried 18 it was so buggy that I couldn't even install it and get it running on a completely new server, so I had to uninstall and  go back to 17

18.1 might be better, but I don't wanna waste time trying. SSMS has always been a monstrosity, because it's have way to many dependencies and the installation program seem to be coded way to complex. If your system differ the slightest from the developers PC, there is a high change is will fail. Just look at the size, it says it all. 
It basically just a WinForm app which send Transact-SQL statements to the SQL server, it should be max 20MB! MS: KISS!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by StingyJack** [comment]
You Sir, are a gentleman and a scholar!

**Comment by Punk500** [comment]
18.0 has a launch issue.  18.1 crashes if you drag & drop anything.  Highly recommend 17.9.1!!! https://feedback.azure.com/forums/908035/suggestions/37887988

**Comment by piotrkwiatek** [comment]
Everyday I am dealing with another bug in 18.0. Thanks for the  link!

**Comment by therealjawss** [comment]
thank you! 18.1 also now keeps crashing on me.

**Comment by dylanetaft** [comment]
Seriously, do not install 18.0 or 18.1. 
18.1 crashes dragging\dropping tables into a query window.
I somehow just corrupted 18.1 too installing SSDT for VS 17.  Side-by-side configuration is incorrect.  Trying to uninstall 18.1 results in an installer hang - "Loading packages - please wait"
17.9 is fine.

**Comment by MightyPen** [comment]
@MrM40 The SSMS team is focused on fixing the bugs that are in SSMS 18.1.  Your points are noted and are well-taken. It is time to Close this Issue 2302.
Thank you for submitting this Issue. We hope to hear from you again.

CC: @WilliamAntonRohm

**Comment by MrM40** [comment]
The problem is not that 18.0  and 18.1 have bugs, all software has bugs, that's okay.
The problem is your attitude and decisions which seems to be highly influence by a political marketing agenda that has no place for a product like SSMS (and if it's not, that makes your decisions look even worse).
The real issues are:
1: That you release 18.0 and 18.1 as production ready. It is very obvious at beta stage!
2: That you don't provide a download link for 17.9 on your primary SSMS download page.
Judging by your reply it seems you didn't get that at all.
Before doing anything, fix the two above issues, and then start coding.
