### ISSUE TITLE
Temporal Table System Version Time

### ISSUE THREAD

**Issue by Siphonophora** [MicrosoftDocs/sql-docs#2306]
Hello, I was looking for documentation on how the System_Time values are set and could not find it. After some testing, it looks like system time is based on the current transaction start and not the moment that the insert/update/delete/commit happened. For some use-cases, This will be an important subtlety. 

If the documentation doesn't exist anywhere, I can write it up around the example below. 

It would also be good to point out that the SysStartTime is not the first time that a record could be selected under Snapshot Isolation. This could lead to some confusing behavior. For example, a user run a report while a long running transaction is ongoing, with Snapshot Isolation. If they rerun the report for system time as of... at some time after the transaction is complete, then the data will be seen to have changed. 

Let me know what you think. It seems like it should be [here](https://docs.microsoft.com/en-us/sql/relational-databases/tables/modifying-data-in-a-system-versioned-temporal-table?view=sql-server-2017) or probably on its own page under the 'manage' group. 

``` SQL 

CREATE TABLE [dbo].[ExampleTable]  
(   
     [ID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY  
   , [InsertDateTime] [datetime] NOT NULL
   , [TransactionType] [varchar](20) NOT NULL
   , [SysStartTime] [datetime2](7) GENERATED ALWAYS AS ROW START NOT NULL   
   , [SysEndTime] [datetime2](7) GENERATED ALWAYS AS ROW END NOT NULL   
   , PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])   
)    
WITH ( SYSTEM_VERSIONING = ON );   
GO   


INSERT INTO [dbo].[ExampleTable]  (InsertDateTime, TransactionType)
VALUES  (GETDATE(), 'Implicit');  

WAITFOR DELAY '00:00:02';  
INSERT INTO [dbo].[ExampleTable]  (InsertDateTime, TransactionType)
VALUES  (GETDATE(), 'Implicit');  

Begin Tran
    WAITFOR DELAY '00:00:02';  
    INSERT INTO [dbo].[ExampleTable]  (InsertDateTime, TransactionType)
    VALUES  (GETDATE(), 'Explicit');  
    
    Begin Tran
        WAITFOR DELAY '00:00:02';   
        INSERT INTO [dbo].[ExampleTable]  (InsertDateTime, TransactionType)
        VALUES  (GETDATE(), 'Explicit (Nested)');  
    Commit Tran
Commit Tran

Select * From dbo.ExampleTable

```

The last two records have StartTimes based on the time that the first transaction began. 
![image](https://user-images.githubusercontent.com/32316111/59386745-79566900-8d35-11e9-9ba7-29984b5123ec.png)

**Comment by msebolt** [comment]
@Siphonophora Thank you for the feedback and research on the issue!

For information on SYSTEM_TIME, see https://docs.microsoft.com/sql/relational-databases/tables/querying-data-in-a-system-versioned-temporal-table.  

For the timestamp issue, this seems to occur as the marked commit time of both transactions are the same since both transactions can be issued as one statement to the database.  If you feel this a product issue, use [SQL Server feedback](https://feedback.azure.com/forums/908035-sql-server) for change requests.
