### ISSUE TITLE
Script 1. writes to master database. And it is NOK

### ISSUE THREAD

**Issue by mllab-nl** [MicrosoftDocs/sql-docs#2309]
After: 
--- CREATE DATABASE [columnstore];  
it should be used before creating the table: 
USE [columnstore]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3548ae28-db22-cb89-179a-a5ecf39da2ff
* Version Independent ID: 8c8881db-734b-107a-e243-ccd8250633c4
* Content: [Columnstore indexes - defragmentation - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-defragmentation?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/indexes/columnstore-indexes-defragmentation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/columnstore-indexes-defragmentation.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@mllab-nl -- thank you for contacting us with your suggestion.

@MikeRayMSFT -- my understanding is to add their suggested statement into the article's first code sample, as shown below.  If you agree, I can submit a PR in the private repo with that change.

#### Existing
```
. . .
CREATE DATABASE [columnstore];  
GO
. . .  
```

#### Proposed
```
. . .
CREATE DATABASE [columnstore];  
GO  

USE columnstore;
GO
. . . 
```

**Comment by WilliamAntonRohm** [comment]
@mllab-nl Thank you for your feedback.  We have fixed this in the documentation and it should be live tomorrow.  I am closing this issue now.
