### ISSUE TITLE
Bad formatting on Results outputs

### ISSUE THREAD

**Issue by RachelAmbler** [MicrosoftDocs/sql-docs#2311]
The result outputs are missing the appropriate space\tabs. For example the output following the *The X and Y properties return an integer value, which is displayed in the result set.:* text looks like

```
IDxValyVal  
----------  
134  
215  
3199  
```

Perhaps it should be more like

```
ID   xVal     yVal  
------------------  
1     3        4  
2     1        5  
3     1        99  

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466ede58-a68f-b170-914b-12404b13c2b1
* Version Independent ID: c5fa5444-8723-c737-5fb7-0898c555eb30
* Content: [Manipulating UDT Data - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-types/working-with-user-defined-types-manipulating-udt-data?view=sql-server-2017)
* Content Source: [docs/relational-databases/clr-integration-database-objects-user-defined-types/working-with-user-defined-types-manipulating-udt-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/clr-integration-database-objects-user-defined-types/working-with-user-defined-types-manipulating-udt-data.md)
* Product: **sql**
* Technology: **clr**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@RachelAmbler thank you for your feedback.  We have updated the documentation and the change should be live tomorrow.
