### ISSUE TITLE
SqlPackage on Linux with Docker

### ISSUE THREAD

**Issue by TimCorey** [MicrosoftDocs/sql-docs#2313]
I'm currently trying to get the SqlPackage to run on Linux in docker (the MSSQLServer 2017 latest). Sorry, I'm not a Linux guy but I tried to follow the example fully and I could not get it to work (command not found). Since the Ubunu version is 16.x, I ran that command as well but the item was already installed and up to date.

Could you please tell me what I'm doing wrong?

Here is the docker command I'm running to get started before getting into bash:
docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Pwd12345!" -p 14433:1433 -d -v C:\Temp\Docker\:/tmp/ mcr.microsoft.com/mssql/server:2017-latest

**Comment by MightyPen** [comment]
@rothja Hi Jason, This Issue 2313 might be a documentation opportunity, or not. Whatever you judge is fine with me.
The following docs/linux/ articles might be related:

quickstart-install-connect-docker.md
sql-server-linux-configure-docker.md
sql-server-linux-configure-msdtc-docker.md

 . .

**Comment by rothja** [comment]
@TimCorey Thanks for the feedback. Are you saying that when you run the docker command, you get command not found? Have you installed Docker for Windows from the docker website? Sorry you're having problems. I want to make sure that the instructions are correct.

**Comment by TimCorey** [comment]
I've been playing around with this for a bit and I figured out the issue. It comes down to my lack of understanding of Linux. The issue ended up being a pathing problem. Let me explain my process:

1. I stood up a Linux SQL 2017 Developer Edition container in Docker (on Windows) with a volume that has the SqlPackage zip in it
2. I ran the docker exec -it <containerId> bash command
3. From the bash command, I tried to run the suggested commands. 
4. I did not need to install libunwind8 (already installed)
5. I tried to unzip the zip file (no unzip in the SQL Linux image)
6. I extracted the zip file on the host machine and put them in the mapped directory
7. I tried to run the commands to enable sqlpackage (it failed - this is where I got stuck)

It turns out since I mapped the volume to /sqlpackage, I needed to change your commands to match. I didn't realize you installed to the root folder instead of the root of the drive (not sure how to explain it - you installed to the equivalent of c:\root and I installed to c:\). The commands that I needed to run were the following:

- echo "export PATH=\"\$PATH:/sqlpackage\"" >> ~/.bashrc
- chmod a+x /sqlpackage/sqlpackage
- source ~/.bashrc

Note the subtle changes in the pathing in the export command and the chmod command.

I'm going to build a tool for extracting Azure SQL backups to local containers. I'll be documenting it for myself but if you would like me to add something here as well, I'd be happy to do so. Just let me know where you want it.

Thanks for being willing to look into it.
