### ISSUE TITLE
No table created from step 5-3?

### ISSUE THREAD

**Issue by YizeD** [MicrosoftDocs/sql-docs#2314]
How does step 5-3 (where data should be uploaded into a table in the SQL database) work? From documentation, it seems like line 4 creates a reference to the table iris_data in the irissql database and line 5 fills the table with data, but when was the table created in the first place? When running 5-3 on my own server, no table is created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2175e183-b508-c7e4-1caa-65b2adbb3b54
* Version Independent ID: e2ee7575-2be6-6ec7-4b2e-be278da1f2ff
* Content: [Set up a data science client for Python development - SQL Server Machine Learning - SQL Server](https://docs.microsoft.com/en-us/sql/advanced-analytics/python/setup-python-client-tools-sql?view=sql-server-2017#feedback)
* Content Source: [docs/advanced-analytics/python/setup-python-client-tools-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/python/setup-python-client-tools-sql.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@YizeD Thank you for opening a GitHub issue. I will investigate and get back to you.

**Comment by YizeD** [comment]
It turns out my connection string was not correct. It was interesting that it was giving a response like it had made changes in the SQL server before.

Now that the connection string is fixed, however, I get this new error for rx_data_step:
DataStep error: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user {'user'}

I'm pretty sure I set up the permissions correctly for the server, but I cannot access the database using rx_data_step.

**Comment by YizeD** [comment]
It seems like my problem was that I needed to grant each user permission to edit the irissql database, and not just permission in the server.
