### ISSUE TITLE
DataBase Diagrams “details” link doesn’t provide any value/details

### ISSUE THREAD

**Issue by ite-klass** [MicrosoftDocs/sql-docs#2315]
The 16.1 what's new says:

&gt; For details, see Database Diagrams.

But it just links to a useless, no-details feature request that basically says “please re-add it” and “it was added back in”. How is that details? It should instead link to some form of documentation that actually describes what Database Diagrams are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by ite-klass** [comment]
If a link to the feature request is desired, and pointing out that feedback is listened to, then it should still be reworded to something more descriptive. Like “This was requested *here*.” or “This was added again based on *community feedback*.¨

**Comment by msebolt** [comment]
@markingmyname Hi Mark, could you provide the status of this feature or otherwise process this issue #2315.

**Comment by tcovarrubias** [comment]
SSMS 18.1 crashes when you drag a database object (example, a table name) to a query window.

**Comment by ite-klass** [comment]
@tcovarrubias This ticket is about the release notes documentation, not the feature. Please refer to the product feedback system/tracker for SSMS. If no such ticket exists there yet, you can create a ticket for your issue; and otherwise follow existing ones.

It looks like the SSMS feedback is also in the SQL Server category. This is also linked in the documentation, or reachable from SSMS via Help -> Technical Support, and can be found at https://feedback.azure.com/forums/908035-sql-server/

**Comment by markingmyname** [comment]
Thank you, @ite-klass, for your feedback.

The article will be updated with updated changes by the end of the week.

thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
