### ISSUE TITLE
SQL Server 2019 release

### ISSUE THREAD

**Issue by 0ddo** [MicrosoftDocs/sql-docs#2316]
When will new server be released?

**Comment by msebolt** [comment]
@MikeRayMSFT Hi Mike, is there any information you want to share about this issue?

Mike, please close this issue when done.

**Comment by MikeRayMSFT** [comment]
@0ddo - Thank you for the question. The general availability (GA) date for SQL Server 2019 is not available yet. We will announce that through the [SQL Server official blog channel](https://cloudblogs.microsoft.com/sqlserver/).

**Comment by 0ddo** [comment]
We are waiting to move on from 2008 for 2019 to be released. Would be nice to have a date to look forward to.

**Comment by MikeRayMSFT** [comment]
Thank you very much for the feedback, @0ddo

I will share this with the team.
