### ISSUE TITLE
Viewing Column Collation

### ISSUE THREAD

**Issue by J0nKn1ght** [MicrosoftDocs/sql-docs#2317]
To show column collation and also include the table it belongs to, use:

SELECT t.name TableName, c.name ColumnName, collation_name 
FROM sys.columns c
inner join sys.tables t on c.object_id = t.object_id
WHERE c.name = N'&lt;Column Name&gt;';  

You can obviously add to the where clause to restrict the table as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af681c7-0879-d01e-ba8d-66577c9044dc
* Version Independent ID: 65b43c19-b9f9-0bf8-45da-5792f3466fae
* Content: [View Collation Information - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/collations/view-collation-information?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/collations/view-collation-information.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/view-collation-information.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@J0nKn1ght -- thank you for your suggestion.  We are looking into incorporating this new information into our documentation.

**Comment by WilliamAntonRohm** [comment]
Steve -- please consider adding Jon's ingenious suggestion to the examples in that article.

**Comment by stevestein** [comment]
@J0nKn1ght - thanks for raising the issue. I added your example to the article. 

Thanks!

**Comment by stevestein** [comment]
#please-close
