### ISSUE TITLE
dead link on Custom Messages for Logging

### ISSUE THREAD

**Issue by ryanmajidi** [MicrosoftDocs/sql-docs#2320]
**Submitted to [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1613) by @strattonn**

Link to article:
https://docs.microsoft.com/en-us/sql/integration-services/custom-messages-for-logging?view=sql-server-2014

Problem:
The Related Content link...
Blog entry, Logging custom events for Integration Services tasks, on dougbert.com.

Is dead, goes to a Game of Thrones online gaming site.

**Comment by MightyPen** [comment]
@msebolt PR #10667 is now Merged (into branch= 'master'). So I am now Closing this fixed Issue 2320.
Thanks. (GeneMi).
