### ISSUE TITLE
Document is outdated it seems

### ISSUE THREAD

**Issue by anuraj** [MicrosoftDocs/sql-docs#2322]
Looks like the document is not updated to the latest version of Azure Data studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9dc8a6a-682b-3016-5fd7-d1840505e075
* Version Independent ID: d9657550-a95f-f50c-7d56-0295de2904f6
* Content: [Tutorial: Enable the five slowest queries sample widget - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/tutorial-qds-sql-server?view=sql-server-2017)
* Content Source: [docs/azure-data-studio/tutorial-qds-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/tutorial-qds-sql-server.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, Here in Issue 2322, there is perhaps too little information provided in the initial description here. However you decide to deal with that problem is fine by me.  Thanks.

**Comment by markingmyname** [comment]
@anuraj,

Are you referring to the screenshots or the commands?

Please let us know.

Thank you.

**Comment by anuraj** [comment]
@markingmyname Both or the document is not in sync with the screenshots.

**Comment by markingmyname** [comment]
@VasuBhog for awareness

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please look into this aging issue 2322.

**Comment by markingmyname** [comment]
@anuraj,

I want to apologize for the late reply, but I was trying to collect the right info before i addressed this.

 As such, this article, as well as the Prereq Quickstart that is listed in this article, will be updated by the end of next week.

Thank you for your comments.  It helped us see we had a clear gap in some of our docs.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
