### ISSUE TITLE
Is there TDSDUMP equivalent in Microsoft SQL driver?

### ISSUE THREAD

**Issue by jankoprowski** [MicrosoftDocs/sql-docs#2324]
Hi,

  I'm Python developer. I'm using pymssql right now. However, because project is not maintained I'm considering to switch to pyodbc with Microsoft driver. Right now I'm using FreeTDS and TDSDUMP environment variable, described here: https://www.freetds.org/userguide/logging.htm to dump queries into the file. Is there equivalent in Microsoft driver?

**Comment by MightyPen** [comment]
@David-Engel Hi David, Can you Comment on this Issue 2324 about Python. Thanks.
@WilliamAntonRohm is ready to assist you.

**Comment by David-Engel** [comment]
@jankoprowski The Microsoft ODBC Driver for SQL Server takes advantage of unixODBC logging as described at the bottom of the link you provided. It does not use an environment variable like TDSDUMP to do additional logging.

If you have detailed questions about pyODBC and the MS ODBC driver, I recommend asking/filing an issue on the [pyODBC GitHub](https://github.com/mkleehammer/pyodbc/) site. The developers there know the code behind pyODBC and the MS ODBC driver in depth.

**Comment by jankoprowski** [comment]
Thank you very much. I will try logging with unixODBC.
