### ISSUE TITLE
Add recommended resource requests (and limits)

### ISSUE THREAD

**Issue by gldraphael** [MicrosoftDocs/sql-docs#2329]
Something like this:

```yaml
resources:
  requests:
    memory: "2G"
    cpu: "2000m"
  limits:
    memory: "4G"
    cpu: "4000m"
```

Would also be great if this link could be added somewhere: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup?view=sql-server-2017#system

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04922c04-a2da-186c-5946-1cc4d9a7447b
* Version Independent ID: 6e490885-cdd7-079a-0b3a-4688616b0954
* Content: [Deploy a SQL Server container in Kubernetes with Azure Kubernetes Services (AKS) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-2017)
* Content Source: [docs/linux/tutorial-sql-server-containers-kubernetes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-sql-server-containers-kubernetes.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please look into this aging issue 2329.

**Comment by MikeRayMSFT** [comment]
@gldraphael  - thank you for submitting this issue. I'm reaching out to my colleagues in engineering. My response was delayed due to a recent vacation. We'll get back to you soon.

**Comment by gldraphael** [comment]
@MikeRayMSFT No worries and no need for the explanation. Please take your time.

**Comment by MikeRayMSFT** [comment]
Taking internal documentation item for review.

**Comment by rwestMSFT** [comment]
It took three years, but we got there in the end. An article update in the next day or so will add in the resources, and link to system requirements.

Thanks for your patience, @gldraphael.
