### ISSUE TITLE
Typo in the escape sequences

### ISSUE THREAD

**Issue by Piotrek2** [MicrosoftDocs/sql-docs#2330]
[Enter feedback here]
Typo in the escape sequences:
It is:   Reverse solidus (\) | \|
It should be: Reverse solidus (\) | \\

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9298c088-3bff-2cab-7d11-a0aca451a5bf
* Version Independent ID: 6fdaf6bd-7af2-5a08-9e79-fe38cecab7a1
* Content: [STRING_ESCAPE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/string-escape-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/string-escape-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/string-escape-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@Piotrek2 Thank you for the feedback!

Change has been submitted for review.
