### ISSUE TITLE
sp_estimate_data_compression_savings can now be used for columnstore indexes

### ISSUE THREAD

**Issue by svaneyck** [MicrosoftDocs/sql-docs#2337]
[ @data_compression= ] 'data_compression'
Is the type of compression to be evaluated. data_compression can be one of the following values: NONE, ROW, PAGE, COLUMNSTORE, or COLUMNSTORE_ARCHIVE.

Refers to line in data compression article:
"The procedure sp_estimate_data_compression_savings (Transact-SQL) does not apply to columnstore indexes."

(the above argument explanation came from article https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-estimate-data-compression-savings-transact-sql?view=sql-server-2017)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffce279e-4bb0-60e0-a31e-22070fa4028e
* Version Independent ID: a2f863a7-7965-bc2c-7150-66eb81379bf9
* Content: [Data Compression - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-compression/data-compression?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/data-compression/data-compression.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-compression/data-compression.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@svaneyck Thank you for the feedback!  Your change has been made and merged.
