### ISSUE TITLE
The ORDER clause should only apply to SQL DW, not SQL Server or SQL DB

### ISSUE THREAD

**Issue by dimitri-furman** [MicrosoftDocs/sql-docs#2338]
In the Syntax session for SQL Server and Azure SQL Database, there is this:
[ORDER (column [,…n])]  --(Preview) 

But this preview is only in SQL DW now. This syntax is incorrect for other products.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 195f6bd5-e394-7695-3fed-2cb092db31b9
* Version Independent ID: 3bab1457-be3c-b344-feb3-f8b00a4f916d
* Content: [CREATE COLUMNSTORE INDEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-columnstore-index-transact-sql?view=azure-sqldw-latest)
* Content Source: [docs/t-sql/statements/create-columnstore-index-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-columnstore-index-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@dimitri-furman Please clarify - are you saying that ORDER (column .... is a syntax that is in preview and is only in preview for SQL DW and the syntax does not exist for any of the other flavors of SQL?

**Comment by dimitri-furman** [comment]
@CarlRabeler that is correct.

**Comment by WilliamAntonRohm** [comment]
@dimitri-furman, @CarlRabeler -- I am creating a PR for this and will ask Dimitri to review it.

**Comment by WilliamAntonRohm** [comment]
@dimitri-furman Thank you for your feedback.  We have fixed this issue in the documentation, and it should be live tomorrow, so I am closing this Issue 2338 now.
