### ISSUE TITLE
Write service time threshold for throttling checkpoint activity

### ISSUE THREAD

**Issue by LonnyNiederstadt** [MicrosoftDocs/sql-docs#2339]
Hello,

Does the 50 ms threshold for throttling checkpoint activity apply only to automatic checkpoints, or does it also apply to indirect checkpoints?
On the "Database Checkpoints" page, the structure implies the threshold only applies to automatic checkpoints.
In this sqlcat post, it seems to imply that the threshold may be considered for both automatic and indirect checkpoints.
Changes in SQL Server 2016 Checkpoint Behavior
https://blogs.msdn.microsoft.com/sqlcat/2016/08/03/changes-in-sql-server-2016-checkpoint-behavior/

Thanks!
Lonny Niederstadt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bca058-bde3-c76a-793a-dc344751d853
* Version Independent ID: 1f682f41-3a2d-66d6-47f1-bd5c2b4ca873
* Content: [Database Checkpoints (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/logs/database-checkpoints-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/logs/database-checkpoints-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/logs/database-checkpoints-sql-server.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @LonnyNiederstadt , 

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by MashaMSFT** [comment]
Hi @LonnyNiederstadt ,

Thanks again for contacting Microsoft! The 50ms throttling is only applicable to automatic checkpointing. Indirect checkpoints are not throttled. The sqlcat article is referring to automatic checkpointing when it's discussing the throttling, they just didn't state it explicitly. 

I hope that helps and please let me know if we could be of further assistance? If not, we will proceed with closing out this Git Issue in a few business days.

Thanks!
- Masha from SQL Docs team
