### ISSUE TITLE
How to make existing columns hidden

### ISSUE THREAD

**Issue by danobri** [MicrosoftDocs/sql-docs#2340]
In your final example - https://docs.microsoft.com/en-us/sql/relational-databases/tables/creating-a-system-versioned-temporal-table?view=sql-server-2017#migrate-existing-tables-to-built-in-support
Is there a way to make the period columns hidden?  If so, could you please include this in the documentation?  I would like to turn on versioning for an existing table and populate the "SysStartTime" column from an existing column, but would like the new period columns to be hidden.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349eae51-5e73-47db-ee0d-8cae824f5c45
* Version Independent ID: 98d04967-6eb4-4d4d-e4a4-8e77a0f1fba0
* Content: [Creating a System-Versioned Temporal Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/creating-a-system-versioned-temporal-table?view=sql-server-2017#migrate-existing-tables-to-built-in-support)
* Content Source: [docs/relational-databases/tables/creating-a-system-versioned-temporal-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/creating-a-system-versioned-temporal-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by danobri** [comment]
Thanks to the following post - https://bornsql.ca/blog/temporal-tables-hidden-columns/

I found the answer to my question.  I think it would be useful to add to your final example, as I would think hiding versioning columns added to existing table would be the most common case.

Here's a proposed update to your final example:

/*Drop trigger on future temporal table*/   
DROP TRIGGER ProjectCurrent_OnUpdateDelete;   
/*Make sure that future period columns are non-nullable*/   
ALTER TABLE ProjectTaskCurrent ALTER COLUMN [ValidFrom] datetime2 NOT NULL;   
ALTER TABLE ProjectTaskCurrent ALTER COLUMN [ValidTo] datetime2 NOT NULL;   
ALTER TABLE ProjectTaskHistory ALTER COLUMN [ValidFrom] datetime2 NOT NULL;   
ALTER TABLE ProjectTaskHistory ALTER COLUMN [ValidTo] datetime2 NOT NULL;   
ALTER TABLE ProjectTaskCurrent   
   ADD PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])   
ALTER TABLE ProjectTaskCurrent ALTER COLUMN [ValidFrom] ADD HIDDEN;   
ALTER TABLE ProjectTaskCurrent ALTER COLUMN [ValidTo] ADD HIDDEN;   
ALTER TABLE ProjectTaskHistory ALTER COLUMN [ValidFrom]  ADD HIDDEN;   
ALTER TABLE ProjectTaskHistory ALTER COLUMN [ValidTo] ADD HIDDEN; 
ALTER TABLE ProjectTaskCurrent   
   SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.ProjectTaskHistory, DATA_CONSISTENCY_CHECK = ON))   
;

**Comment by msebolt** [comment]
@danobri Thank you for the feedback!  

The documentation has been updated.
