### ISSUE TITLE
Turning Temporal OFF leaves the Period Columns in the base table

### ISSUE THREAD

**Issue by gwalkey** [MicrosoftDocs/sql-docs#2341]
[Enter feedback here]
SQL 2017 CU15 STD
We tested Temporal on a Production System, When we had a unrelated error crop up on the client APP, we turned Temporal OFF, and noticed that the two Start and End Period DateTime2 columns remained on the base table. The Client APP did not like it for some reason (EF6). 
Why not automatically drop those columns as part of these statements:

ALTER TABLE dbo.Department SET (SYSTEM_VERSIONING = OFF);   
ALTER TABLE dbo.Department   
DROP PERIOD FOR SYSTEM_TIME;  

Reference:
https://docs.microsoft.com/en-us/sql/relational-databases/tables/stopping-system-versioning-on-a-system-versioned-temporal-table?view=sql-server-2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3e6674-aa5d-6b80-ae29-514954988128
* Version Independent ID: 01e72b93-3f3c-408f-b0b7-06fbb0076640
* Content: [Stopping System-Versioning on a System-Versioned Temporal Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/stopping-system-versioning-on-a-system-versioned-temporal-table?view=sql-server-2017)
* Content Source: [docs/relational-databases/tables/stopping-system-versioning-on-a-system-versioned-temporal-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/stopping-system-versioning-on-a-system-versioned-temporal-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by MightyPen** [comment]
@bonova Hi Borko, Can you please add a Comment into this GitHub Issue 2341, to help address the customer's question?
We would like to finish this Issue and close it soon.

@CarlRabeler can assist you with the mechanics of updating a GitHub Issue, if you ask for his assistance.

This Issue 2341 must remain co-assigned to both Borko and Carl. First action we need is an explanatory Comment from Borko that reacts to the customer's original question. Then Carl can perform the necessary labelings and closing, if assistance is requested.

Thank you.

**Comment by CarlRabeler** [comment]
@gwalkey there are reasons to temporarily turn off and then turn back on temporal tables - if you turn them off and intend to remove them completely, it is your responsibility to remove those columns if you do not need them - as well as to design your application such that it does not care that these columns remain.

**Comment by gwalkey** [comment]
Agreed.
although Entity Framework was the one throwing a rod as it pertains to
"as well as to design your application such that it does not care that these columns remain."

Also, adding a Temporal On/off feature to SSMS or ADS in the right-click Table context menu would be nice too , used more often than Stretch 
:)

thanks again guys!
