### ISSUE TITLE
Incomplete process

### ISSUE THREAD

**Issue by dcallagh** [MicrosoftDocs/sql-docs#2343]
Hi, 

I have used this page to set up a domain independent AOAG group i Azure however the instructions are incomplete and I have not been 100% successful:
No Domain means no active directory DNS. I have used two independent DNS one on each sqlserver. Cluster role move is successful. However cluster manager gives errors on the second subnet. Is the cluster still supported?
Cluster resource 'IP Address 172.18.0.250' of type 'IP Address' in clustered role 'Cluster Group' failed.
Cluster resource 'AOAGgroup_172.18.0.251' of type 'IP Address' in clustered role 'AOAGgroup' failed.

Also had to  run this command in each sql manager:
GRANT ALTER ANY AVAILABILITY GROUP TO [NT AUTHORITY\SYSTEM];
GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
GRANT VIEW SERVER STATE TO [NT AUTHORITY\SYSTEM];

Having followed the AOAG setup join  with no sync option, the aoag creates successfully however the AOAG database is now stuck in 'synchronizing' in sql manager, no data available on secondary replicas, and failover does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df2d6260-37b5-78f2-e558-7129b58ca9c5
* Version Independent ID: 247cde67-5d7a-c844-f2e7-292277348c60
* Content: [Create a domain-independent availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/domain-independent-availability-groups?view=sql-server-2017)
* Content Source: [docs/database-engine/availability-groups/windows/domain-independent-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/domain-independent-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @dcallagh , Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by allanhirt** [comment]
> No Domain means no active directory DNS.

This is incorrect. A Workgroup Cluster (the variant of a WSFC that does not require AD DS) is meant to be used with DNS. DNS is often independent of AD in many organizations and not even MS-based. Therefore not requiring AD DS doesn't mean no DNS, and the Workgroup Cluster variant in Windows AFAIK is not tested with local DNS to each node so you most likely have an unsupported configuration.

Since a domain independent AG is based on a Workgroup Cluster, this is fairly simple "math".  When you set up the Workgroup CLuster correctly with DNS, domain independent AGs will work.

I have set up multi-subnet Workgroup Clusters. You need to ensure that the DNS suffix is the same on each WSFC node.

Also, it's not AOAG. Just AG. Thanks.

**Comment by allanhirt** [comment]
Also, please remember to configure DNS suffix to be the same on each node.
https://techcommunity.microsoft.com/t5/Failover-Clustering/Workgroup-and-Multi-domain-clusters-in-Windows-Server-2016/ba-p/372059

"Primary DNS Suffix Requirements

        Each cluster node needs to have a primary DNS suffix."

**Comment by dcallagh** [comment]
Ahh well, the WSFC appears to 'expect' to be able to update DNS. Scenario:  we use non AD integrated, primary-secondary  DNS, and practice a failover of the cluster role node. The cluster throws an error (as opposed to the warning about dual subnet IP resources) . It fails to update the secondary read only DNS end with the new cluster role owner.  While this can be done manually it still shows the cluster role owner expects a Multimaster (AD) DNS.Thanks, yes I noted the AOAG depends on synch replication and amended the design.The instructions need to be refreshed in any case as there are a couple of steps which have become necessary since they were written. Given this, addressing the static DNS (Perhaps as an expected error) is desirable.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Allan Hirt <notifications@github.com> Date: 25/6/19  3:35 am  (GMT+10:00) To: MicrosoftDocs/sql-docs <sql-docs@noreply.github.com> Cc: dcallagh <dcallagh@iname.com>, Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/sql-docs] Incomplete process (#2343) 
No Domain means no active directory DNS.

This is incorrect. A Workgroup Cluster (the variant of a WSFC that does not require AD DS) is meant to be used with DNS. DNS is often independent of AD in many organizations and not even MS-based. Therefore not requiring AD DS doesn't mean no DNS, and the Workgroup Cluster variant in Windows AFAIK is not tested with local DNS to each node so you most likely have an unsupported configuration.
Since a domain independent AG is based on a Workgroup Cluster, this is fairly simple "math".  When you set up the Workgroup CLuster correctly with DNS, domain independent AGs will work.
I have set up multi-subnet Workgroup Clusters. You need to ensure that the DNS suffix is the same on each WSFC node.
Also, it's not AOAG. Just AG. Thanks.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/sql-docs/issues/2343?email_source=notifications\u0026email_token=AADX422SSV7LOOMQYRY6ONTP4EAWFA5CNFSM4HZOO3CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYNVGPQ#issuecomment-505107262",
"url": "https://github.com/MicrosoftDocs/sql-docs/issues/2343?email_source=notifications\u0026email_token=AADX422SSV7LOOMQYRY6ONTP4EAWFA5CNFSM4HZOO3CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYNVGPQ#issuecomment-505107262",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by allanhirt** [comment]
So you have a WSFC problem, not an AG one.

Plenty of people deploy WSFCs where no automatic updates are allowed (AD integrated or not). This is why when you have multiple IP addresses, you put BOTH in DNS in this case, or have a process of dealing with it. It’s a choice, but it sounds like you’re not going to put both IP addresses in there, which means that until you manually update DNS with the new info, nothing will come online. Talk to your infrastructure folks and get that all sorted out.

So it’s a WSFC thing, not an AG thing. You also are going step further and have read only DNS, which is very uncommon.

**Comment by dcallagh** [comment]
Alreadydone as per existing instructionsSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Allan Hirt <notifications@github.com> Date: 25/6/19  3:50 am  (GMT+10:00) To: MicrosoftDocs/sql-docs <sql-docs@noreply.github.com> Cc: dcallagh <dcallagh@iname.com>, Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/sql-docs] Incomplete process (#2343) Also, please remember to configure DNS suffix to be the same on each node.
https://techcommunity.microsoft.com/t5/Failover-Clustering/Workgroup-and-Multi-domain-clusters-in-Windows-Server-2016/ba-p/372059
"Primary DNS Suffix Requirements
    Each cluster node needs to have a primary DNS suffix."


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/sql-docs/issues/2343?email_source=notifications\u0026email_token=AADX427XXEYC4OHKDHQO2TLP4ECODA5CNFSM4HZOO3CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYNWOMY#issuecomment-505112371",
"url": "https://github.com/MicrosoftDocs/sql-docs/issues/2343?email_source=notifications\u0026email_token=AADX427XXEYC4OHKDHQO2TLP4ECODA5CNFSM4HZOO3CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYNWOMY#issuecomment-505112371",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dcallagh** [comment]
Secondaries, in multi site non AD are the normSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Allan Hirt <notifications@github.com> Date: 25/6/19  7:31 am  (GMT+10:00) To: MicrosoftDocs/sql-docs <sql-docs@noreply.github.com> Cc: dcallagh <dcallagh@iname.com>, Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/sql-docs] Incomplete process (#2343) So you have a WSFC problem, not an AG one.







Plenty of people deploy WSFCs where no automatic updates are allowed (AD integrated or not). This is why when you have multiple IP addresses, you put BOTH in DNS in this case, or have a process of dealing with it. It’s a choice, but it sounds like you’re not going to put both IP addresses in there, which means that until you manually update DNS with the new info, nothing will come online. Talk to your infrastructure folks and get that all sorted out.







So it’s a WSFC thing, not an AG thing. You also are going step further and have read only DNS, which is very uncommon.

**Comment by dcallagh** [comment]
This and was a request to have this process updated WRT mirror steps. And to address that error, which will apply to the ag listener as well. Simply saying a manual dns update is required would address the issue.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Allan Hirt <notifications@github.com> Date: 25/6/19  7:31 am  (GMT+10:00) To: MicrosoftDocs/sql-docs <sql-docs@noreply.github.com> Cc: dcallagh <dcallagh@iname.com>, Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/sql-docs] Incomplete process (#2343) So you have a WSFC problem, not an AG one.







Plenty of people deploy WSFCs where no automatic updates are allowed (AD integrated or not). This is why when you have multiple IP addresses, you put BOTH in DNS in this case, or have a process of dealing with it. It’s a choice, but it sounds like you’re not going to put both IP addresses in there, which means that until you manually update DNS with the new info, nothing will come online. Talk to your infrastructure folks and get that all sorted out.







So it’s a WSFC thing, not an AG thing. You also are going step further and have read only DNS, which is very uncommon.

**Comment by MashaMSFT** [comment]
Hi @dcallagh, thanks again for reaching out! Sorry, would you mind clarifying what change you're suggesting?

There's a section here that states you need DNS:
A common DNS suffix is necessary for a Domain Independent Availability Group's Workgroup Cluster. To set and verify the DNS suffix on each Windows Server that will host a replica for the availability group, follow these instructions

Does that cover your question, or does something else need to be added?

Thanks!
Masha from SQL Docs team

**Comment by allanhirt** [comment]
He's talking more of adding something to the effect that if you have static DNS (whether it is write or read, which is updated from a writeable DNS server), you need to have a process to update it before you do a failover otherwise the network name isn't coming online. This isn't specific fo domain independent AGs, though. It's a general WSFC thing.

**Comment by MashaMSFT** [comment]
would something like the below work? 

If you have a static DNS that is being updated by a writeable DNS server, you will need to have a process in place to update the static DNS server before you perform a failover as otherwise the network name will not come online.

**Comment by allanhirt** [comment]
Not totally. Static DNS can be readable and/or writeable. His scenario is one writeable and one readable.

If you have a static DNS, you will need to have a process in place to update the DNS record associated with the listener or WSFC if you are using multiple subnets server before you perform a failover as otherwise the network name will not come online.

**Comment by MashaMSFT** [comment]
got it! Thanks Allan :)

**Comment by dcallagh** [comment]
Can the non domain joined primary DNS be made a role?Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Allan Hirt <notifications@github.com> Date: 26/6/19  5:49 am  (GMT+10:00) To: MicrosoftDocs/sql-docs <sql-docs@noreply.github.com> Cc: dcallagh <dcallagh@iname.com>, Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/sql-docs] Incomplete process (#2343) Not totally. Static DNS can be readable and/or writeable. His scenario is one writeable and one readable.
If you have a static DNS, you will need to have a process in place to update the DNS record associated with the listener or WSFC if you are using multiple subnets server before you perform a failover as otherwise the network name will not come online.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/sql-docs/issues/2343?email_source=notifications\u0026email_token=AADX425LN4I75PJSWCO2MELP4JZC5A5CNFSM4HZOO3CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYRMP6Q#issuecomment-505595898",
"url": "https://github.com/MicrosoftDocs/sql-docs/issues/2343?email_source=notifications\u0026email_token=AADX425LN4I75PJSWCO2MELP4JZC5A5CNFSM4HZOO3CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYRMP6Q#issuecomment-505595898",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MashaMSFT** [comment]
[edited comment to remove PII - MSFT]

**Comment by MashaMSFT** [comment]
Hi @dcallagh, sorry, would you mind clarifying by what you mean "made a role"? Thanks!

**Comment by allanhirt** [comment]
I'm confused by that comment as well.

**Comment by dcallagh** [comment]
Ahh - ok, we install DNS as a role in windows, it can either be AD integrated, or not.

In this case it is not as there is no AD, which also means no multimaster, with a primary (dynamic update=yes) and secondary(updates not allowed).

This means when you failover, you cannot update the secondary DNS.

 

So, can we make the Primary DNS service in this case a cluster role?

This effectively gives you failover DNS with updates allowed.

 

Cheers.

**Comment by allanhirt** [comment]
No, you cannot cluster DNS on Windows Server.

**Comment by dcallagh** [comment]
Thats a shame.
 

Sent: Tuesday, July 09, 2019 at 10:28 AM

**Comment by MashaMSFT** [comment]
Hi @dcallagh , thanks again for your suggestions for improving our documentation! Is there anything further we can assist you with from the documentation perspective? If not, we will proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
