### ISSUE TITLE
SQL DW ADLS missing from diagram

### ISSUE THREAD

**Issue by bricrsa** [MicrosoftDocs/sql-docs#2349]
The diagram regards polybase connectivty to storage explicitly says Blob only whereas this is no longer true. ADLS Gen 1 and Blob are both supported at present.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ebefef-f8c5-e429-269e-1ef7a96264fd
* Version Independent ID: a8009495-9bb9-87f4-85af-0ac0074749e7
* Content: [What is PolyBase? - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-guide?view=azure-sqldw-latest#feedback)
* Content Source: [docs/relational-databases/polybase/polybase-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-guide.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@rothja Hi Jason, can you please process this Issue 2349, about Polybase.

**Comment by rothja** [comment]
@bricrsa Thanks for the feedback. I'll look at adding this soon.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
