### ISSUE TITLE
SSMS: If drag and drop an object (the name) from Object Explorer into the query window the whole application freezes and crashes

### ISSUE THREAD

**Issue by mr2001** [MicrosoftDocs/sql-docs#2350]
If drag and drop an object (name) from Object Explorer into the query window the whole application freezes and crashes

**Comment by mr2001** [comment]
This is a bug in SSMS ver. 18.1

**Comment by WilliamAntonRohm** [comment]
@markingmyname (Issue 2350) Hi Mark, please look into this SSMS 18.1 issue.

**Comment by markingmyname** [comment]
Hi @mr2001,

We are aware of this regression and there will be a message in the release notes specifying this regression planned to be posted live this week.

The product fix is planned for the next release.

We apologize for any inconvenience this has caused.

**Comment by markingmyname** [comment]
@dnethi and @Matteo-T for awareness.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
