### ISSUE TITLE
DEA docs are out of date

### ISSUE THREAD

**Issue by noamo48** [MicrosoftDocs/sql-docs#2352]
The docs for SQL Server Database Experimentation Assistant are out of date and it's driving me nuts. In the "capture trace" docs, it specifies that you can choose trace file size. But in DEA 2.6, this option does not exist. As a result, I'm forced in to capturing 500mb trace files and for a 24 hour capture, I end up with hundreds of files which I have to replay one by one.

**Comment by msebolt** [comment]
Hi @noamo48 Thank you for the feedback!

@HJToland3 @MashaMSFT Can you assess this potential doc-bug?

**Comment by HJToland3** [comment]
@msebolt, I will reach out to the PM team and get corrected detail to publish.

**Comment by HJToland3** [comment]
@noamo48, we are working to update the documentation to reflect the latest version of DEA. In the interim, you can modify the size of the trace files collected using the following steps.

1. Navigate to the folder in which you installed DEA, and then open the \Scripts folder.
2. Based on the platform where you are capturing 
    a.	StartCaptureTrace.sql – For Capturing Server Traces
    b.	CaptureXEL.sql – For Capturing XEvents.
3. Opening the file will have a variable “<<MaxFileSize>>” defined at the top of the file
    a.	Remove that completely and specify the desired size there in MB directly there, e.g., if you want to capture 1GB files, then specify 1024

For more information on the max_file_size and how it works refer to the documentation at the following links:
- https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-trace-create-transact-sql?view=sql-server-2017
- https://www.sqlskills.com/blogs/jonathan/an-xevent-a-day-6-of-31-targets-week-asynchronous_file_target/

Hope this helps!

**Comment by HJToland3** [comment]
#please-close

**Comment by noamo48** [comment]
@HJToland3  thank you!!!
