### ISSUE TITLE
Azure SQL Database support

### ISSUE THREAD

**Issue by OscarCanek** [MicrosoftDocs/sql-docs#2353]
When it'll be supported by Azure SQL Database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0840e04-b52d-2c5f-197d-26bec998fcaa
* Version Independent ID: 40ca3965-4f80-cbb3-839c-3244a536675e
* Content: [Graph edge constraints - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/graph-edge-constraints?view=sql-server-2017)
* Content Source: [docs/relational-databases/tables/graph-edge-constraints.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/graph-edge-constraints.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @shkale-msft
* Microsoft Alias: **shkale**

**Comment by MightyPen** [comment]
@shkale-msft 
Hello Shreya,

In new GitHub Issue 2353, a customer is asking if/when graph edge constraints are supported on Azure SQL Database (single database - elastic pools) service.

Should this documentation article be updated, to say Yes for Az SQL DB?:

- https://docs.microsoft.com/en-us/sql/relational-databases/tables/graph-edge-constraints?view=sql-server-2017 

- https://github.com/MicrosoftDocs/sql-docs/issues/2353 

Currently the above article claims that graph edge constrains are NOT supported on Az SQL DB.    But I did a quickie simplistic run of the example T-SQL, and the example ran complete without errors.

Also, assuming the following article is closely related, it is worth noting that the following article does say Yes for Az SQL DB:

- https://docs.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-overview?view=sql-server-2017 

So, are graph edge constraints already supported on Az SQL DB? 

If yes, I (or another Writer) will update the documentation accordingly.    I will update the article to choose a different AppliesTo includes/ file, and I will update its OPS Versioning monikerization.

I gather that graph edge constraints are Not supported in either Az SQL DW or ASP-PDW.    But if I am wrong about that, please let me know.

Thank you.
(GeneMi)

CC: @msebolt

**Comment by MightyPen** [comment]
Fixed by PR 10743.  I am therefore now Closing this 
- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/10743`

Per confirmation email I (GeneMi) received by Shreya Verma:

---

From: Shreya Verma 
Sent: Friday, June 21, 2019 2:51 PM
To: Gene Milener
Subject: RE: [MicrosoftDocs/sql-docs] Azure SQL Database support (#2353)

Hi Gene,

Yes. The feature is now supported on Azure SQL DB. Please feel free to update the documentation.

Graph edge constraints are not supported in Azure SQL DW or PDW. 

Thanks,
shreya

---

CC: @shkale-msft
