### ISSUE TITLE
SSMS: Status Bar Layout and Colors not persisted

### ISSUE THREAD

**Issue by piersmyers** [MicrosoftDocs/sql-docs#2355]
The 'Group connections' and 'Single server connections' colors under Options->Text Editor->Editor Tab and Status Bar->Status Bar Layout and Colors do not persist after closing SSMS 18.1 and will revert to white when opened next time. They should default to Pink and Khaki as white text on a white background is hard to read. This was also an issue in SSMS 18.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by MightyPen** [comment]
@dnethi and @markingmyname 
Can you two please test with SSMS 18.1 to see whether you can reproduce this reported bug.
Then please add a Comment into this Issue 2355 to explain your conclusion about this Issue.

Thank you.

**Comment by markingmyname** [comment]
Hi @piersmyers,

 Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
Hi @piersmyers,

We did notice a regression with this feature and are working on correcting it.

We've added this information to the [release notes article](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#known-issues-181).

We apologize for any inconvenience and are working on correcting it.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by dnethi** [comment]
hi folks

thanks for reporting this issue. We have the fix and it will be in the next release, likely next month. 

thanks,
Dinakar
