### ISSUE TITLE
how to disable the distribution transactions on availability groups once it is enabled with alter statement?

### ISSUE THREAD

**Issue by yogigollapudi** [MicrosoftDocs/sql-docs#2361]
how to disable the distribution transactions on availability groups once it is enabled with alter statement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4525f922-c768-bb9c-fc93-4a3b790c03fb
* Version Independent ID: f50f9610-c6a6-0fad-5f53-975a64a53704
* Content: [Configure distributed transactions for an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-availability-group-for-distributed-transactions?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/configure-availability-group-for-distributed-transactions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/configure-availability-group-for-distributed-transactions.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MightyPen** [comment]
@MashaMSFT Hi Masha, I am unsure if the answer is an ALTER DROP or not. If that is the answer, maybe the article could receive a minor update to show such an ALTER DROP in a code example?
Anyway, can you please process this Issue 2361.

Thank you.

**Comment by MashaMSFT** [comment]
Hi @yogigollapudi , thanks for contacting Microsoft! You can disable DTC with the same command, just setting DTC = none like so: 

ALTER AVAILABILITY GROUP MyaAG
   SET (
      DTC_SUPPORT = NONE  
      );

I've submitted a PR that includes this change in the documentation, it should be live later today.

Thanks!

**Comment by MashaMSFT** [comment]
Hi @yogigollapudi , 

Thanks again for contacting Microsoft!  We've submitted a documentation change based on your suggestion, and it should be live at this point. Please let us know if there is anything more we can do for you? If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a wonderful rest of your day!
Masha from SQL Docs team
