### ISSUE TITLE
Azure SQLDB does not support this event in the xevents.

### ISSUE THREAD

**Issue by masashioms** [MicrosoftDocs/sql-docs#2367]
We can't capture this event and Plan Guide Unsuccessful Event on Azure SQLDB. As we can use plan guide feature on SQLDB, it should be able to be captured those events as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a74d539-30f2-315f-f99f-53aaf8a4d3d1
* Version Independent ID: 5e956f35-1f10-4607-9cd8-e25f1a36fd81
* Content: [Plan Guide Successful Event Class - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/event-classes/plan-guide-successful-event-class?view=sql-server-2017)
* Content Source: [docs/relational-databases/event-classes/plan-guide-successful-event-class.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/event-classes/plan-guide-successful-event-class.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@stevestein -- SQL Server Profiler appears to be deprecated, per https://docs.microsoft.com/en-us/sql/tools/sql-server-profiler/sql-server-profiler?view=sql-server-2017:

> SQL Trace and SQL Server Profiler are deprecated. The Microsoft.SqlServer.Management.Trace namespace that contains the Microsoft SQL Server Trace and Replay objects are also deprecated.

Please finish processing this issue 2367.

**Comment by stevestein** [comment]
@masashioms - thanks for raising this issue.  I'm investigating the details on this. Thanks!

**Comment by stevestein** [comment]
@masashioms - I just updated the article to show that these two events are not currently available in SQL DB. 

Thanks again for pointing this out.
