### ISSUE TITLE
SSMS Update don't show latest download

### ISSUE THREAD

**Issue by kristofzerbe** [MicrosoftDocs/sql-docs#2368]
The builtin SSMS update dialog is always nagging me with new versions of SSMS, like today: "Updates are available to SQL Server Management Studio. Installed: 15.0.18118.0 - Latest: 15.0.18131.0" and the UPDATE button is leading me to the download page. But there is NO download of the latest version, because it shows me always the German page (last update 25.04.2019), which is always way behind the English (last update 06/12/2019). 
But I'm working with an english SSMS! Solution for me is always: Fiddle with the Url like in the 90's...

Please: Redirect the users to the right page of the installed SSMS or keep all other language pages in sync with the english one!

**Comment by MightyPen** [comment]
@markingmyname  (Issue 2368)  Hi Mark, can you please look into this SSMS concern.  Thanks.

**Comment by markingmyname** [comment]
Hi, @kristofzerbe,

The localized pages are always a bit behind, sometimes several weeks -- so while the bits are out there, we simply need to wait until the other locales pick up the new article changes and updates the different language versions to match the English version.

However, I can say this is a concern we are looking into to see how we can better direct non-English locales to the English version.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
