### ISSUE TITLE
Document missing values for SQLServiceType enum

### ISSUE THREAD

**Issue by fsackur** [MicrosoftDocs/sql-docs#2369]
Reddit user CobbITGuy has found and identified further possible values for this enum:

8   &lt;AD Helper Service?? or Notification Services??&gt;
9   &lt;SQL Full-text Filter Daemon Launcher W10/SQL2017&gt; (Service to launch full-text filter daemon process which will perform document filtering and word breaking for SQL Server full-text search. Disabling this service will make full-text search features of SQL Server unavailable.)
10 &lt;SQL Server Polybase Engine&gt;
11 &lt;SQL Server Polybase Data Movement Service&gt;
12 &lt;SQL Server Launchpad WS2019/SQL2014&gt; (Service to launch Advanced Analytics Extensions Launchpad process that enables integration with Microsoft R Open using standard T-SQL statements. Disabling this service will make Advanced Analytics features of SQL Server unavailable.)

Source:
https://www.reddit.com/r/SQLServer/comments/atwjcp/wmi_sqlservicetype/

I have not personally verified these; I do not know if this completes the list of possible values.

Is anyone able to confirm these values and whether the list is now complete?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905fa290-bf83-20f2-21c2-ca3c79e54d04
* Version Independent ID: 6fc21f31-085f-cd79-7cd2-300e772b2865
* Content: [SqlServiceType Property (SqlServiceAdvancedProperty Class) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/wmi-provider-configuration-classes/sqlserviceadvancedproperty-class/sqlservicetype-property-sqlserviceadvancedproperty-class?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/wmi-provider-configuration-classes/sqlserviceadvancedproperty-class/sqlservicetype-property-sqlserviceadvancedproperty-class.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/wmi-provider-configuration-classes/sqlserviceadvancedproperty-class/sqlservicetype-property-sqlserviceadvancedproperty-class.md)
* Product: **sql**
* Technology: **wmi**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@CarlRabeler -- the customer has determined there may be additional, undocumented, enum values -- I don't know how to verify these new values -- please process this issue 2369.

**Comment by CarlRabeler** [comment]
@WilliamAntonRohm I do not know either - will investigate

**Comment by fsackur** [comment]
After logging this, I discovered a class in the same namespace called `RegServices`, which may hold the answer.

I ran this snippet on a SQL 2017 RTM installation:

```
Get-CimInstance -Namespace 'ROOT\Microsoft\SqlServer\ComputerManagement14' -ClassName 'RegServices' |
    Sort-Object Type |
    Format-Table

LName            Name                   ServiceType                               Type
-----            ----                   -----------                               ----
MSSQL$           MSSQLServer            SQL Server                                   1
SQLAgent$        SQLSERVERAGENT         SQL Agent                                    2
msftesql$        msftesql               Full Text                                    3
                 MsDtsServer            SSIS Server                                  4
MSOLAP$          MSSQLServerOLAPService Analysis Server                              5
ReportServer$    ReportServer           Report Server                                6
ReportServer$    ReportServer           ReportServer                                 6
                 SQLBrowser             SQL Browser                                  7
NS$              NsService              Notification Services                        8
MSSQLFDLauncher$ MSSQLFDLauncher        Full-text Filter Daemon Launcher             9
SQLPBENGINE$     SQLPBENGINE            SQL Server Polybase Engine                  10
SQLPBDMS$        SQLPBDMS               SQL Server Polybase Data Movement Service   11
MSSQLLaunchpad$  MSSQLLaunchpad         Launchpad Service                           12
```

I'm ready to bet that this is the full and complete answer, until vNext, anyway.

**Comment by fsackur** [comment]
@CarlRabeler thank you for the merge! Should this be live yet?

**Comment by CarlRabeler** [comment]
should be live within a couple of hours

**Comment by WilliamAntonRohm** [comment]
@fsackur Thank you for your feedback.  This issue has been fixed and so I am now closing this issue 2369.
