### ISSUE TITLE
SQL recovery model is not set to Full after server upgrade from W2008 R2 to W2012 R2

### ISSUE THREAD

**Issue by hsalama1** [MicrosoftDocs/sql-docs#2370]
After a server upgrade from  W2008 R2 to W2012 R2, recovery model is set to full however backup is not working successfully...each time it makes full backup instead of incremental

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3d152c1-49ed-9263-75c0-4cd738582f50
* Version Independent ID: d2ead26c-c016-a9f2-b6ad-bc4653f0bb7d
* Content: [Complete Database Restores (Full Recovery Model) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/complete-database-restores-full-recovery-model?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/backup-restore/complete-database-restores-full-recovery-model.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/complete-database-restores-full-recovery-model.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @hsalama1 , thanks for contacting Microsoft! This sounds like a support issue, and not an issue with the documentation, but I can try to provide some preliminary assistance. Can you please provide steps or scripts, for how you're taking the backup?

Thanks!

**Comment by MashaMSFT** [comment]
Hi @hsalama1 , hope you're doing well! I wanted to follow up with you and see if you had the chance to grab the steps or script for taking the backup?

Thanks!
Masha from SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @hsalama1 , hope your day is going well! I wanted to follow up with you once more and see if you had the chance to grab the scripts for taking the backup? Please note, if we don't hear back from you in a few business days, we'll be closing out this Git Issue.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @hsalama1 , hope you're enjoying your Monday! Since it's been some time since we've heard from you, we'll assume that you were able to get incremental backups working and will proceed with closing out this Git Issue. Please feel free to respond should you need anything further. Thanks!
