### ISSUE TITLE
Can I store txt files inside azure sql database?

### ISSUE THREAD

**Issue by Anmolgan81** [MicrosoftDocs/sql-docs#2371]
Can I store txt files inside azure sql database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf421288-ba40-3904-72d1-07de1c69e211
* Version Independent ID: f388925a-a573-65ab-e0db-fe61245df123
* Content: [char and varchar (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/data-types/char-and-varchar-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/char-and-varchar-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@Anmolgan81 -- you can store text in an Azure SQL Database as a varchar field, up to 2GB in length.  The top of the article indicates that it applies to Azure SQL Database, and other products as well.

The article you mention indicates that a varchar field can be defined with either 1) a number indicating the length up to 8,000 characters, or 2) a literal **max** for a length up to 2 GB.

I am closing this issue 2371 now.  Please feel free to @ mention me if you have any further questions.

**Comment by Anmolgan81** [comment]
Hi William, can I store .txt files in azure sql database??

Regards
Anmol Ganju

________________________________

**Comment by Anmolgan81** [comment]
I am talking about .txt files and not the text data type.

Regards
Anmol Ganju

________________________________
