### ISSUE TITLE
Specify Join Keys please

### ISSUE THREAD

**Issue by fpugh** [MicrosoftDocs/sql-docs#2374]
I PRESUME that you mean that sysjobactivity.job_history_id = sysjobhistory.instance_id

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42860196-2454-45d2-f2a8-760cf0a0f9cd
* Version Independent ID: 85b49171-3e96-6779-33df-7d0fd7c65919
* Content: [dbo.sysjobactivity (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/dbo-sysjobactivity-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-tables/dbo-sysjobactivity-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/dbo-sysjobactivity-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@fpugh - Thanks for opening this issue.  The query is joining sysjobs.job_id = sysjobactivity.job_id and runs as expected in my quick test. Are you seeing incorrect results?

**Comment by stevestein** [comment]
I am closing this issue now. You are welcome to @ mention me for any followup. 

Thanks!
