### ISSUE TITLE
fails on SSMS 18.1

### ISSUE THREAD

**Issue by ALZDBA** [MicrosoftDocs/sql-docs#2377]
This fails first time with SSMS 18.1 !  ( Getting the list of objects from 'dbname' produces error and scripting stops )
Clicking "previous" and "next" again produces the script ! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 222643c9-2ac1-11f6-4913-5e2e5216dfe6
* Version Independent ID: 7bb94693-57be-7775-0f40-ce7681a8b655
* Content: [Generate and Publish Scripts Wizard - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/scripting/generate-and-publish-scripts-wizard?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3Den-US%26k%3Dk(sql13.swb.generatescriptswizard.saveorpublishscripts.f1)%26rd%3Dtrue&view=sql-server-2017#feedback)
* Content Source: [docs/ssms/scripting/generate-and-publish-scripts-wizard.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/generate-and-publish-scripts-wizard.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, can you please process this Issue 2377, about SSMS 18.1.  Thanks.

**Comment by markingmyname** [comment]
HI @ALZDBA,

Can I ask if this has happened to you more than once?  For Example, does this happen every time you try and generate scripts from eth wizard?

I was unable to repro the issue in my 18.1 SSMS version.

Please let me know.

Thank you.

**Comment by davidgeary** [comment]
Running SSMS 15.0.18131.0 here (against SQL Express 2014) and getting the same issue here consistently when the `Save Scripts` page is reached.  No error details are given, other than the message at the top:

> Script Generation Failed.  Click on Help for Known Solutions

Clicking Help opens the MS Docs (https://docs.microsoft.com/en-us/sql/ssms/scripting/generate-and-publish-scripts-wizard?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3Den-US%26k%3Dk(sql13.swb.generatescriptswizard.saveorpublishscripts.f1)%26rd%3Dtrue&view=sql-server-2017), though the page contains no information about possible solutions.

FYI, clicking the `Save Report` button results in the scripts being created - go figure!

**Comment by tgburgin** [comment]
Getting the same issue on 18.1 against SQL Server 12.0.6205.1. Clicking back then next fixes it as per @ALZDBA

**Comment by markingmyname** [comment]
Hello, everyone.

I apologize for the delayed response.

Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

In the meantime, can you please visit [UserVoice](https://feedback.azure.com/forums/908035-sql-server) to submit your issue?

**Comment by markingmyname** [comment]
Hello all,

18.2 was released today that addressed a lot of the issues 18.0 and 18.1 are having.

Can you [download](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017) that version and let me know if you are still experiencing this?

**Comment by markingmyname** [comment]
Hello, all.

Has anyone tried this with 18.2 yet?

**Comment by paudio25** [comment]
I have tried with 18.2. Same error

**Comment by markingmyname** [comment]
Thank you, @paudio25.

I will discuss this with our engineering team.

**Comment by dnethi** [comment]
hi folks

I just created an Azure SQL DW resource, and SSMS 18.2 to connect to a sample DW and followed the instructions on the docs page to initiate the Generate Scripts wizard, set the Database engine edition/type settings as instructed, and had no issues with the wizard.

Please download/install SSMS 18.2, and try again. 

thanks,
Dinakar
Senior PM

**Comment by markingmyname** [comment]
@dnethi 

I could not repro the issue either. It works with me using 18.2 as well.

**Comment by markingmyname** [comment]
Hello, all,

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by DylDelport** [comment]
@markingmyname I'm still unable to generate a script. It immediately fails without any error message

**Comment by suvratrai** [comment]
This issue is still there. I have SSMS Version 18.4 installed on my machine, and whenever i try to create DB script from my SQL server, it fails for the first time and then when i go back and try it once again, it works just fine. I am trying to connect to a SQL Server 2012 Standard Edition, to get the scripts. Please look into this issue.

**Comment by dnethi** [comment]
what is the error message you get? Can you paste a screenshot?

**Comment by jitterbox** [comment]
I get his error repeatedly on SSMS 18.4 when accessing my Azure SQL Database and attempting to generate scripts (entire database, using Azure SQL engines, Schema only). Sometimes it crashes SSMS (which is all too common for many unrelated reasons recently). The error occurs on the first step ("Getting the list of objects from [database]"):

Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch. ---> System.Data.SqlClient.SqlException: **Invalid object name 'sys.sql_feature_restrictions'.** at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException) at Microsoft.SqlServer.Management.Common.ServerConnection.GetExecuteReader(SqlCommand command) --- End of inner exception stack trace --- at Microsoft.SqlServer.Management.SqlScriptPublish.GeneratePublishPage.worker_DoWork(Object sender, DoWorkEventArgs e) at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e) at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
--

**Comment by dnethi** [comment]
thanks for reporting this. Noted and will be fixed in the next release.

**Comment by hghumphrey** [comment]
Here is the error code:

Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch. ---> System.Data.SqlClient.SqlException: Invalid object name 'sys.sql_feature_restrictions'.   at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)   at Microsoft.SqlServer.Management.Common.ServerConnection.GetExecuteReader(SqlCommand command)   --- End of inner exception stack trace ---   at Microsoft.SqlServer.Management.SqlScriptPublish.GeneratePublishPage.worker_DoWork(Object sender, DoWorkEventArgs e)   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
--

**Comment by dnethi** [comment]
With 18.5 I am not able to repro. Can you verify if you are on the latest version of SSMS?

**Comment by hghumphrey** [comment]
We are running 18.4 but I have 18 preview 6 and it works just fine. So, something along the way broke it between preview 6 and 18.4.  I will not be able install 18.5 as I'm not an admin on my laptop for security reasons.  Even though I'm a SR DBA and have been a DBA for 20+ years.

**Comment by hghumphrey** [comment]
Ok, I was able to install 18.5 and you are correct, it is now fixed.

**Comment by sethnejame** [comment]
Had the same exact issue w/ error message as @hghumphrey (was working on SSMS 18.4) and upgrading to 18.6 now allows **Generate Scripts** to work.
