### ISSUE TITLE
Bit -> Date, DateTime2

### ISSUE THREAD

**Issue by viskri-msft** [MicrosoftDocs/sql-docs#2382]
SQL seems to allow bit to Date and DateTime2 conversions but the page says otherwise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84062379-c6f2-2af3-b1dd-560101d1fc0a
* Version Independent ID: 9c05fb90-d5ea-c494-e446-cd78a70a9785
* Content: [Data type conversion (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-type-conversion-database-engine?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/data-types/data-type-conversion-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/data-type-conversion-database-engine.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@viskri-msft -- thank you for your feedback. Technically, you are correct.  This is unlikely to arise, and we've decided to leave the article unchanged.
