### ISSUE TITLE
Documentation / Functionality Mismatch

### ISSUE THREAD

**Issue by MCTSQL** [MicrosoftDocs/sql-docs#2383]
The documentation states that "A single credential can be mapped to multiple SQL Server logins."
However, current SQL Server 2017 (14.0.3076.1) functionality contradicts that statement:
Test:
1. Map credential C to SQL login L -Result: success 
2. Map credential C to SQL login L2 -Result: Cannot add credential because it is already mapped to a login.

Error Details:
Add Credential failed for Login 'L2'.  (Microsoft.SqlServer.Smo)
For help, click: http://go.microsoft.com/fwlink?ProdName=Microsoft+SQL+Server&ProdVer=14.0.17289.0+((SSMS_Rel_17_4).181117-0805)&EvtSrc=Microsoft.SqlServer.Management.Smo.ExceptionTemplates.FailedOperationExceptionText&EvtID=Add+Credential+Login&LinkId=20476
Cannot add credential because it is already mapped to a login. (Microsoft SQL Server, Error: 33042)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11770cab-9a5d-bc53-160a-5b6eb63f4d41
* Version Independent ID: ed64663a-8da5-57e5-c969-60b615599ffb
* Content: [Credentials (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/credentials-database-engine?view=sql-server-2017)
* Content Source: [docs/relational-databases/security/authentication-access/credentials-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/credentials-database-engine.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10837

**Comment by WilliamAntonRohm** [comment]
@MCTSQL Thank you for your feedback.  We have incorporated it into the documentation and it should be live by tomorrow.

I am closing this Issue 2383 now.
