### ISSUE TITLE
Include reference to view or procedure that will show these properties

### ISSUE THREAD

**Issue by Cornan** [MicrosoftDocs/sql-docs#2384]
Please add references to any stored procedures or "system" views that will allow these properties to be retrieved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd48b72-0326-a279-7ff4-f0ddad982d88
* Version Independent ID: 9af67e3e-4851-82d6-636d-573308d86f56
* Content: [SQL Server Agent Properties (History Page) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/agent/sql-server-agent-properties-history-page?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/agent/sql-server-agent-properties-history-page.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/sql-server-agent-properties-history-page.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by MightyPen** [comment]
@Cornan Hello, You can probably discover this information by using the the extended event (XEvent) that is described in the following How-To article, namely 'sql_statement_completed'. Establish and activate the xevent, and then operate the SQL Agent.  Then go see what the xevent captured.

- `https://docs.microsoft.com/sql/relational-databases/extended-events/quick-start-extended-events-in-sql-server`
    - [https://docs.microsoft.com/sql/relational-databases/extended-events/quick-start-extended-events-in-sql-server](https://docs.microsoft.com/sql/relational-databases/extended-events/quick-start-extended-events-in-sql-server)

I am now closing this Issue 2384. We hope to hear from you again.

CC, FYI: @markingmyname 
 . .
