### ISSUE TITLE
KB832524 no longer available

### ISSUE THREAD

**Issue by ktaranov** [MicrosoftDocs/sql-docs#2385]
https://support.microsoft.com/en-us/help/832524

> Sorry, page not found
Try searching Microsoft Support to find a solution

This KB refer in https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql?view=sql-server-2017 for **trace flag 1201**

Please return it.

**Comment by MightyPen** [comment]
@ktaranov Hi Konstantin, We do not know why the KB832524 webpage was removed, but it was removed intentionally.  I will make one inquiry to try learning why it was removed, and I will send further @ notifications to you if I am successful.

I must now close this Issue 2385.

Thank you for submitting this Issue. We hope to hear from you again.

**Comment by MightyPen** [comment]
@WilliamAntonRohm Hi William, can you please fix/remove the broken link, and then paste the PR number/link in here.  Thanks.

**Comment by MightyPen** [comment]
Note: I sent email to Edison D. inquiring about the old KB 832524 webpage.
