### ISSUE TITLE
CommonAncestor correctness

### ISSUE THREAD

**Issue by FYfrog** [MicrosoftDocs/sql-docs#2386]
Is CommonAncestor method supposed to work correctly?
The classical algorithm looks something like this

<pre><code>CREATE FUNCTION CommonAncestor
(
  @h1 hierarchyid,
  @h2 hierarchyid
)
RETURNS hierarchyid
AS
BEGIN
  DECLARE @h1Level smallint = @h1.GetLevel();
  DECLARE @h2Level smallint = @h2.GetLevel();

  WHILE @h1Level &gt; @h2Level
  BEGIN
    SET @h1 = @h1.GetAncestor(1);
    SET @h1Level = @h1Level - 1;
  END;

  WHILE @h2Level &gt; @h1Level
  BEGIN
    SET @h2 = @h2.GetAncestor(1);
    SET @h2Level = @h2Level - 1;
  END;

  WHILE @h1 &lt;&gt; @h2
  BEGIN
    SET @h1 = @h1.GetAncestor(1);
    SET @h2 = @h2.GetAncestor(1);
  END;

  RETURN @h1;
END
</code></pre>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eb7c78-a9f9-a4ba-e329-1612305ca5b7
* Version Independent ID: 32d85190-08f7-ae1f-db00-1837389d6863
* Content: [Hierarchical Data (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/hierarchical-data-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/hierarchical-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/hierarchical-data-sql-server.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@rothja Hi Jason, can you please process this Issue #2386.  Thanks.

**Comment by rothja** [comment]
@FYfrog Thanks for contacting us, and so sorry for the long delay. For the function you provided here, are you saying that it should work but doesn't? I'm trying to understand if the content is wrong in some way on this page. Although, I do see that we provide a CLR example for common ancestor and not a T-SQL example.

**Comment by FYfrog** [comment]
I apologize for the ambiguity and for providing unnecessary T-SQL code. Let me be straightforward. Script with 'CommonAncestor' function (in CLR, from MSDN page) returns empty set, not '/1/1/'. And probably there is a typo in function definition: should be SqlHierarchyId instead of HierarchyId (return type of function, type of h2).

**Comment by rothja** [comment]
@FYfrog No need to apologize. Thank you for clarifying. So the code sample on the CLR example is wrong and might need fixing (or there is a bug in SQL Server). I'll take another look at this. Thank you.

**Comment by rothja** [comment]
@FYfrog Thanks for your patience. I have not had time to setup the sample to reproduce the problem, but I plan to do this soon to verify and hopefully fix the sample.

**Comment by rothja** [comment]
@FYfrog I have been unable to get the time to recreate and test/fix this CommonAncestor function at the moment. I have created an internal work item to track this (1600197) and we will try to investigate and correct this in the future. I really apologize for the long delay and for this response on the issue. I hope that you found a way to get around the documentation problem here in your solution. At this time, I am going to close the git issue, but the internal tracking item that we have will remain open until it is investigated, fixed, and closed. Please let me know if you have any questions. Thank you!
