### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by Talon9** [MicrosoftDocs/sql-docs#2387]
I believe that it is STIsValid instead of STIsValida

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 234035e0-bedc-773c-b12d-4a4304eeba03
* Version Independent ID: 0c647683-e848-6d95-cbe4-68ea9c67ad6d
* Content: [OGC Methods on Geography Instances - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geography/ogc-methods-on-geography-instances?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/spatial-geography/ogc-methods-on-geography-instances.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/spatial-geography/ogc-methods-on-geography-instances.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by MladjoA** [comment]
Thanks @Talon9 
FIx is on its way to prod docs

**Comment by MightyPen** [comment]
This seems to refer to PR:
https://github.com/Potapy4/sql-docs/pull/286 

I am now closing this fixed/successful Issue #2387.
Thank you for submitting this Issue. We hope to hear from you again.
