### ISSUE TITLE
SSMS 18.1 fails to install 

### ISSUE THREAD

**Issue by jensenjk** [MicrosoftDocs/sql-docs#2388]
SSMS Install Error Code: A certificate was explicitly revoked by its issuer (0x800B010C)

received when installing ssms 18 or 18.1

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, please process this Issue 2388.

**Comment by markingmyname** [comment]
Hi @jensenjk, 

Have you come across this [thread](https://github.com/Aftnet/RetriX/issues/38) or this [thread](https://social.msdn.microsoft.com/Forums/en-US/9fad8d58-09fc-4143-95ee-0538a9373818/ssms-install-error-code-a-certificate-was-explicitly-revoked-by-its-issuer-0x800b010c?forum=sqltools)?

**Comment by jensenjk** [comment]
Have tried both - can't still install.

**Comment by jensenjk** [comment]
After adding the certificate as described in the first thread , i didn't work but after a reboot problem was solved..

**Comment by jensenjk** [comment]
Sorry, mixed up ´two servers - still cant install on the one server.
Still get the certificata revoked error

**Comment by markingmyname** [comment]
Hello, everyone.

I apologize for the delayed response.

Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

In the meantime, can you please visit UserVoice to submit your issue?

**Comment by markingmyname** [comment]
Do you have a Kerberos setup?

**Comment by markingmyname** [comment]
Hi, @jensenjk,

Sorry for the delayed response.

This looks like a support request rather than documentation feedback – you can get support by going to https://support.powerbi.com. You might find a solution in the Power BI Community, found at https://community.powerbi.com.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
