### ISSUE TITLE
Automatic seeding DMVs are not documented

### ISSUE THREAD

**Issue by jadarnel27** [MicrosoftDocs/sql-docs#2391]
Hello!  I noticed that the following DMVs related to automatic seeding don't have dedicated documentation pages (that describe the different columns and their meanings / possible values) with the other AG-related DMVs:

```
SELECT * FROM sys.dm_hadr_automatic_seeding;
SELECT * FROM sys.dm_hadr_physical_seeding_stats;
```

It seems like they would would be linked from this page, but they are not: 

[Always On Availability Groups Dynamic Management Views - Functions](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/always-on-availability-groups-dynamic-management-views-functions?view=sql-server-2017)

Note that they are already partially documented here: 

[Use automatic seeding to initialize an Always On availability group - Monitor automatic seeding availability group](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/automatically-initialize-always-on-availability-group?view=sql-server-2017#monitor-automatic-seeding-availability-group)

> **sys.dm_hadr_automatic_seeding**
> 
> On the primary replica, query `sys.dm_hadr_automatic_seeding` to check the status of the automatic seeding process. The view returns one row for each seeding process.

and

> **sys.dm_hadr_physical_seeding_stats**
> 
> On the primary replica, query `sys.dm_hadr_physical_seeding_stats` DMV to see the physical statistics for each seeding process that is currently running.

If you're open to a pull request, I'd be happy to take a first pass at adding those new pages.  But I thought it would make sense to ask first.  I think they would be a useful addition to the docs

**Comment by MightyPen** [comment]
@MikeRayMSFT Hi Mike, I do not see that we have any reference articles dedicated to these two DMVs. Josh is offering to create the necessary PR for these two articles. I am inclined to say - "Yes thanks, please do!".
.
If you have concerns, please chime in today.  Else _Josh, yes please go ahead now and do create the PR_. In the PR, please @ notify both Mike and me.

CC: @jadarnel27

**Comment by MikeRayMSFT** [comment]
@jadarnel27 - thanks for offering to submit an initial pull request for these missing DMVs - we welcome your initiative! 
@SQLSourabh,  @MashaMSFT,  and I will watch for it.
Creating User Story [1577135](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1577135): HA | Document missing DMVs for Automatic Seeding 
on internal database so that we can track.

**Comment by MikeRayMSFT** [comment]
At this point, we're going to close this issue and schedule a doc fix at a future date. Tracking in https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1577135

@jadarnel27  if you submit a PR it will get reviewed quickly.
