### ISSUE TITLE
DATEDIFF does consider time zone

### ISSUE THREAD

**Issue by rdicroce** [MicrosoftDocs/sql-docs#2394]
The docs for DATEDIFF say:

> DATEDIFF does not use a time zone offset component of startdate or enddate to calculate the return value.

This is demonstrably untrue. I am in the eastern US, so currently my timezone is UTC-4. On SQL Server 2017, executing `SELECT datediff(hour, GETDATE(), SYSDATETIMEOFFSET())` yields 4.

The docs should be fixed to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340056a9-0593-4289-7b72-601ae718b05f
* Version Independent ID: 1db8e288-8068-be96-b2f2-c8a2fe5a857a
* Content: [DATEDIFF (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/datediff-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/datediff-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@WilliamAntonRohm Hi William, can you please process this Issue #2394.  Thanks.

Ideally this Issue will not need to be assigned to ms.author MikeRayMSFT.

**Comment by WilliamAntonRohm** [comment]
@rdicroce -- Rich, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

I am closing this issue 2394 now.  You are welcome to @ mention me for any followup.
