### ISSUE TITLE
Are you sure? - "As the source database is updated, the database snapshot is updated."

### ISSUE THREAD

**Issue by dakrdakr** [MicrosoftDocs/sql-docs#2397]
Is following sentence (from first paragraph on this page) really correct?: "As the source database is updated, the database snapshot is updated.". I expected: "As the source database is updated, the database snapshot is NOT updated.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2bcf755-2d2d-23bd-d4dc-0e0f2971f3df
* Version Independent ID: e74d5adf-7a03-6f64-29e5-dd0bc606f4c0
* Content: [Database Snapshots (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-snapshots-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/databases/database-snapshots-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/database-snapshots-sql-server.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@WilliamAntonRohm you know the drill !

**Comment by ChuckEzell** [comment]
@dakrdakr you are correct - as far as I've experienced the snapshots are "static" and are NOT updated... I think the copy must be wrong.

**Comment by WilliamAntonRohm** [comment]
@dakrdakr -- David, thank you for your feedback.  I updated the documentation and it should be live by tomorrow.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
