### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by xbcratos** [MicrosoftDocs/sql-docs#2398]
The link for CTP 3.1 is not working. The current link is: pip3 install -r  https://private-repo.microsoft.com/python/ctp-3.1/mssqlctl/requirements.txt --user and the correct link is pip3 install -r  https://private-repo.microsoft.com/python/ctp3.1/mssqlctl/requirements.txt --user

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb70b27-d5e7-1cce-4fc2-295e3fd7087d
* Version Independent ID: 307269c2-f65f-0cde-29e2-452acd278c4f
* Content: [Install mssqlctl - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-mssqlctl?view=sql-server-ver15#feedback)
* Content Source: [docs/big-data-cluster/deploy-install-mssqlctl.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-install-mssqlctl.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@xbcratos I apologize for this error, and thanks for posting the correct link. I'll get this fixed immediately.
