### ISSUE TITLE
Incorrect remarks

### ISSUE THREAD

**Issue by SimonHellings** [MicrosoftDocs/sql-docs#2400]
The remarks state:

sp_replrestart is used when the highest log sequence number (LSN) value at the Distributor **does match** the highest LSN value at the Publisher.

Should this read:
sp_replrestart is used when the highest log sequence number (LSN) value at the Distributor does **not** match the highest LSN value at the Publisher.

Kind regards

Simon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88463e52-d0bd-c56b-8ddc-4568fb49262a
* Version Independent ID: 2d4c0714-bad4-f3f8-fbcc-c5998c1d20b3
* Content: [sp_replrestart (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-replrestart-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-replrestart-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-replrestart-transact-sql.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@SimonHellings -- thank you Simon for your feedback.  I updated the documentation and it should be live by tomorrow.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
