### ISSUE TITLE
STContains Red Squiggly When Checking a Polygon contained within Another

### ISSUE THREAD

**Issue by rayjohnson529** [MicrosoftDocs/sql-docs#2402]
I noticed that when using STContains on SSMS with SQL Server 2019

Not sure if this is an SSMS/SQL/etc. issue.

The function operates perfectly normal, but it always has a red squiggly with "Could not find method 'STContains' for type 'Microsoft.SqlServer.Types.SqlGeography' in assembly 'MicrosoftSqlServer.Types'.
on hover.

**Here are Specs** 
SQL Server Management Studio						15.0.18131.0
Microsoft Analysis Services Client Tools						15.0.1347.0
Microsoft Data Access Components (MDAC)						10.0.18362.1
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.18362.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.18362

**Comment by WilliamAntonRohm** [comment]
@rayjohnson529 -- thank you for your feedback. 

@MladjoA -- please look into this issue 2402.

**Comment by MladjoA** [comment]
@WilliamAntonRohm Ack.
@rayjohnson529 - thanks for reporting this. I have a repro and a new bug filed. We will keep you posted on progress.

**Comment by mburbea** [comment]
Sadly there are many errors like this in SSMS :(
![image](https://user-images.githubusercontent.com/213233/60730203-959f8d00-9f12-11e9-9250-a6ee10fb2677.png)

**Comment by WilliamAntonRohm** [comment]
@MladjoA -- Mladen, please look into this aging issue 2402.

**Comment by WilliamAntonRohm** [comment]
@MladjoA  -- please add your new bug's path to this issue 2402.

**Comment by MightyPen** [comment]
@MladjoA Hi Mladen, we really need a link to your bug or fixed bug for this now aging GitHub Issue reported by the customer.  Or can you please share any update info you have, in here by entering a Comment.
Thank you.

**Comment by MightyPen** [comment]
MladjoA returns from vacation next week, around 2019/Aug/07-08.

Issues Triagers, let's allow this aging Issue #2402 to remain open beyond the usual cut-off duration.

**Comment by MladjoA** [comment]
Sorry for delayed response, I was on a vacation.
As I mentioned previously we have a [defect](http://sqlbuvsts01:8080/Main/SQL%20Server/_workitems/edit/13033315) open for this, but I don't have ETA for fix yet. 
Please let me know what else is needed.

Thanks,
Mladen

**Comment by WilliamAntonRohm** [comment]
@MladjoA -- thank you for the update.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
