### ISSUE TITLE
Links to keywords

### ISSUE THREAD

**Issue by reggaeguitar** [MicrosoftDocs/sql-docs#2405]
This page would be 10 times more useful if each keyword was a link to a documentation page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f79ec4df-5309-60fc-1c20-f32b219fb9b9
* Version Independent ID: 6ee85c34-9a2c-e007-dcda-fb6016b98119
* Content: [Reserved Keywords (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/language-elements/reserved-keywords-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/reserved-keywords-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@reggaeguitar -- thank you for your feedback.  In many cases, these keywords depend on context.  I will pass along your suggestion.

I am closing this issue now.  You are welcome to @ mention me for any followup.
