### ISSUE TITLE
Possible Incorrect Wording

### ISSUE THREAD

**Issue by azumbro** [MicrosoftDocs/sql-docs#2406]
Under the "Selecting Deterministic or Randomized Encryption" section, there is a sentence that says "However, but may also allow unauthorized users to guess information about encrypted values by examining patterns in the encrypted column, especially if there is a small set of possible encrypted values, such as True/False, or North/South/East/West region". I believe the second word in this sentence is incorrect (should maybe be "it").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21605a56-8aa8-9dbf-6743-999f204e6775
* Version Independent ID: 35bbb590-6aec-4c63-9dac-cff287745d06
* Content: [Always Encrypted (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine?view=sql-server-2017#selecting--deterministic-or-randomized-encryption)
* Content Source: [docs/relational-databases/security/encryption/always-encrypted-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/always-encrypted-database-engine.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @aliceku
* Microsoft Alias: **aliceku**

**Comment by WilliamAntonRohm** [comment]
@azumbro -- thank you for your suggestion.  I will fix it, and it should be live tomorrow.

One option for any future issues you may find is to update the published documentation by using a pull request.  Use the edit pencil in the upper right of any article, then click the pencil on the GitHub page.

**Comment by WilliamAntonRohm** [comment]
@azumbro -- I am closing this issue now.  You are welcome to @ mention me for any followup.
