### ISSUE TITLE
ACTIVESCRIPTING is removed in 2016, should reflect that

### ISSUE THREAD

**Issue by slepmog** [MicrosoftDocs/sql-docs#2407]
Documentation for `sp_add_job` (https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-add-jobstep-transact-sql?view=sql-server-2017) should be fixed to reflect the fact that the `ACTIVESCRIPTING` option was actually [removed](https://docs.microsoft.com/en-us/sql/database-engine/discontinued-database-engine-functionality-in-sql-server-2016?view=sql-server-2017#discontinued-features-in-) in SQL Server 2016.

Same for the how-to article: https://docs.microsoft.com/en-us/sql/ssms/agent/create-an-activex-script-job-step?view=sql-server-2017.

**Comment by WilliamAntonRohm** [comment]
@msebolt -- please look into this issue 2407.  Minor FYI, this article is owned by SteveStein.  However, this item might be resolvable in the triage stage.

**Comment by msebolt** [comment]
@slepmog Thank for the feedback!

The changes have been made and merged.
