### ISSUE TITLE
SSMS: How exactly can one do this?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/sql-docs#2408]
&gt; Use SSMS to query, design, and manage your databases and data warehouses, wherever they are - on your local computer, or in the cloud.

WHEN SSMS 18.1 CANNOT CONNECT TO SSIS SERVICES?????????????
THIS WAS BROKEN IN 18.0, AND STILL NOT FIXED IN 18.1???????????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by WilliamAntonRohm** [comment]
@StingyJack -- thank you for your feedback.  We are aware of this issue and are working on it.

CC: @markingmyname

**Comment by StingyJack** [comment]
@WilliamAntonRohm - are you also aware of how SSMS decides to hang for 10-20 seconds when I close a query tab?  And how it sometimes destroys the connections other query tabs have open, rendering the table unable to reconnect?

If you had a place to log issues other than Docs or devcomm, the drop in program reliability and quality would probably be clearer.   All you have though, is the MSDN forums and even those aren't getting the promised response times for MSDN Enterprise subscribers.

**Comment by RexfelisLOC** [comment]
No longer able to connect to any Azure SQL Database.  I receive the following error on all computers in my office:

"A connection was successfully established with the server; but then an error occurred during the pre-login handshake"

It's like a recent Windows 10 update which is causing this issue.

OS Version
10.0.18362 Build 18362

**Comment by markingmyname** [comment]
Thanks for the feedback! However, this area is primarily for doc issues. To report product issues, the best way to reach out to the SSMS Team is at [UserVoice](https://feedback.azure.com/forums/908035-sql-server).

**Comment by markingmyname** [comment]
Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

In the meantime, can you please visit [UserVoice](https://feedback.azure.com/forums/908035-sql-server) to submit your issue?

**Comment by StingyJack** [comment]
@markingmyname - I hope you making a funny?

**Comment by markingmyname** [comment]
hi @StingyJack,

I wasn't, but I was able to reproduce the issue.

That's why I am in discussion with our engineers to see what is going on.

I will keep you all posted.

To be clear, I am talking about not being able to connect to SSIS.

**Comment by StingyJack** [comment]
If it were still in use and usable, Uservoice would have been for new feature requests, not for reporting issues or bugs. 

Issues and bugs used to be the realm of Connect, until someone decided that a digital book burning was in order and they could somehow make the bugs that were reported in there vanish along with the reports of the bugs.  

I'm an MSDN enterprise subscription holder, but aint no 2 day response being had from the SQL forums for the few issues I reported there. 

I've tried going through developer community and various MSFT SQL project repos on github, and what I think is becoming fairly clear is that there is [nobody working on SSDT or SQL client tools](https://developercommunity.visualstudio.com/content/problem/168913/there-doesnt-seem-to-be-anyone-left-on-the-ssdt-te.html). Or there are, and they are just incapable of communication with the outside world (with two exceptions; Brian O, and Kevin C.)

SSMS was good until after v14 then it got buggy. Like constantly impeding productivity and trashing your work in progress buggy.  Please discuss with them both establishing a communication channel that is actually monitored and not a one way conversation, and also help figure out why whatever they are doing in SSMS is not being tested properly.

**Comment by dnethi** [comment]
hey @StingyJack  - 
I am the PM for SSMS.
As suggested, please use UserVoice for reporting both new features as well as bugs. Contrary to what you believe, we do have teams working on SSDT and other client tools. Chris's response in your other thread still holds true.

thanks,
Dinakar

**Comment by StingyJack** [comment]
@dnethi - Then perhaps you can speak to why SSMS 17+ has been so unstable, with new regressions after every release?  Have you forgone some part of the testing? I really cant afford to have a key tool that I need to use all the time be in this kind of bugged state.  There is a memory dump of SSMS.exe going non-responsive when I am in the middle of typing and switching tabs from an hour or so ago that you can get from [this dev comm feedback item](https://developercommunity.visualstudio.com/content/problem/653302/ssms-stops-responding-at-random-times.html)). Please use it to fix this program.

The suggestion to use UserVoice for bug reports is not responsible and a suboptimal experience for everyone involved. 
- I cant (file size) and **wont** use uservoice to send a memory dump, because you cant protect attachments that have sensitive data in them.  
- Uservoice is a feature request board. Its not what Connect was, and there has historically never been any dialogue between MSFT and the community on any item, on any uservoice channel.  Its not built for reporting defects. Its wrong to consider defects in delivered software in the same pool as "i want a Dark Theme."

UserVoice is suboptimal because you cannot get the information you need to resolve defects efficiently, and its not responsible for you to suggest because we cant safely get the information to you that you need in order to evaluate, understand, and possibly correct a defect.

Emailing a several hundred megabyte file, and especially to a shared mailbox, is not really any better.

The MSDN forums are supposed to guarantee some response (not resolution) within 2 days. That ain't happening. If I could get help there, I would go there, but I dont. Go see for yourself if you think I'm not being truthful. 

> Chris's response in your other thread still holds true.

Words are not able to be heard when the inaction is deafening. I made an observation based on the available evidence and did not state some whimsical, non-evidence backed belief. Chris could have chosen to ignore that issue and addressed one of my other ones that was open for longer and that wasnt just a complaint. but he didn't. Those issues still remain unaddressed, some are now more than [800+ days](https://developercommunity.visualstudio.com/content/problem/37834/report-data-window-hides-when-another-document-is.html) old.

**Comment by WilliamAntonRohm** [comment]
@StingyJack -- thank you for your feedback.  The next release of SSMS is in the works and should address your concerns.

cc: @markingmyname 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by StingyJack** [comment]
@WilliamAntonRohm - I was (perhaps foolishly) expecting some kind of meaningful response from @dnethi to any of the points made above, before or after he joined the thread. 

I'm not being a difficult lifelong customer, just a persistent one, but lately not as forgiving due to the drop in quality across the board and the inaction and various pushoffs I get when asking for help.

When the docs dont match the program state, how is anyone outside of the group who determine the intention for those programs and execute it going to know which of the two are incorrect?
