### ISSUE TITLE
404

### ISSUE THREAD

**Issue by hfleitas** [MicrosoftDocs/sql-docs#2410]
I am looking for these droids.

https://github.com/microsoft/sql-server-samples/blob/master/samples/features/sql-big-data-cluster/spark/sparklm/mssql-mleap-app

https://github.com/microsoft/sql-server-samples/blob/master/samples/features/sql-big-data-cluster/spark/sparklm/mleap_sql_test/mleap_sql_tests.py

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ffac34-e9e5-5fad-437a-ee01749d5b66
* Version Independent ID: 3eef39c8-7994-a908-37c3-d5457f143bf8
* Content: [Create and export Spark machine learning models with MLeap - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/spark-create-machine-learning-model?view=sqlallproducts-allversions&WT.mc_id=twitter#next-steps)
* Content Source: [docs/big-data-cluster/spark-create-machine-learning-model.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/spark-create-machine-learning-model.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @lgongmsft
* Microsoft Alias: **lgong**

**Comment by WilliamAntonRohm** [comment]
@hfleitas -- thank you for your inquiry.

@lgongmsft -- can you please help answer this Issue 2410.

CC: @rothja

**Comment by rothja** [comment]
@hfleitas Thank you for letting us know of these broken links, and I apologize for the long delay. I'll work on researching why these sample files are not at this location and get back to you.

**Comment by rothja** [comment]
@hfleitas Good news. We have the sample published now, but the links in the article are still wrong. I'm fixing those and this git issue will close when they merge. But you can find the sample here: [https://github.com/microsoft/sql-server-samples/tree/master/samples/features/sql-big-data-cluster/spark/sparkml](https://github.com/microsoft/sql-server-samples/tree/master/samples/features/sql-big-data-cluster/spark/sparkml). Sorry, again for the delay in getting this released and available. Thank you for letting us know!
