### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by reggaeguitar** [MicrosoftDocs/sql-docs#2416]
In this sentence "In the following example, the CustomerID column in the WHERE clause of the outer query is implicitly qualified by the table name in the outer query FROM clause (Sales.Store)" should "CustomerID" say "BusinessEntityID" instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b727c932-4a39-5272-80cd-1a5e2b5aca8b
* Version Independent ID: c31a79c4-06d5-749c-1a6d-69e53c929789
* Content: [Subqueries (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/subqueries?view=sql-server-2017)
* Content Source: [docs/relational-databases/performance/subqueries.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/subqueries.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by julieMSFT** [comment]
@reggaeguitar 
thanks for bringing this to our attention! You are correct. I have made the upset to the document and you should see it later today. I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!

**Comment by julieMSFT** [comment]
#10885

**Comment by julieMSFT** [comment]
#please-close

**Comment by WilliamAntonRohm** [comment]
@julieMSFT -- thank you for addressing and closing this Issue 2416.  I assigned you as author just for bookkeeping purposes; apologies for these superfluous GitHub notifications.

**Comment by julieMSFT** [comment]
Thanks William.
