### ISSUE TITLE
[Suggestion] Guarantees for Compatibility Level during upgrades

### ISSUE THREAD

**Issue by SQLAdrian** [MicrosoftDocs/sql-docs#2418]
I cannot find words around a guarantee on application behavior when upgrading from one server to another while retaining compatibility level.

Query plan protection only gives a guarantee on in-engine behavior, and not on the expected client behavior.

**Scenario:**
Assuming we have DB1 living on Server1(2008) on compat 100 and DMA comes back clear, we move DB1 to Server2(2017). 

**Questions**

What guarantee can I give my clients that applications connecting in to Server2 will behave the same way? No only from a performance perspective.

"Well that's great, but will my app break?"
This is the primary question I am getting from clients, and I cannot give any supporting statements that gives them enough confidence to jump into upgrades while remaining supported.

And what support do we have from Microsoft if the applications exhibit breaking behavior in the scenario above?

**Comment by MightyPen** [comment]
@SQLAdrian Thank you for your inquiry. The following ALTER DATABASE article does a reasonable job of explaining what customers can expect from the Compatibility Level settings.  If there is an advanced scenario that is not precisely described in the article, then testing of the scenario on the upgrade version might be advisable.

- https://docs.microsoft.com/sql/t-sql/statements/alter-database-transact-sql-compatibility-level

Thank you for submitting this Issue. We hope to hear from you again. 
I am now Closing this Issue. The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.
