### ISSUE TITLE
Example is at the wrong position in the text

### ISSUE THREAD

**Issue by kaesaecracker** [MicrosoftDocs/sql-docs#2420]
This is in the text:

```
Remarks
[...]
Do not use a semicolon as a statement terminator after GO.

Permissions
GO is a utility command that requires no permissions. It can be executed by any user.

[the following is a code example]
-- Yields an error because ; is not permitted after GO  
SELECT @@VERSION;  
GO;  
```

The example should be after the last sentence in Remarks. It has nothing to do with Permissions and should be moved up two paragraphs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960815fc-a05d-b887-e5a8-e4aef6761000
* Version Independent ID: 4af0d0ae-c858-9b92-3058-a2e43f60bd8d
* Content: [GO (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-go?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/language-elements/sql-server-utilities-statements-go.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/sql-server-utilities-statements-go.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@kaesaecracker Thank you for the feedback.

The change has been made and merged.
