### ISSUE TITLE
Spelling correction and a bit more details on loopback servers.

### ISSUE THREAD

**Issue by AngryRhetoric** [MicrosoftDocs/sql-docs#2421]
Well-written documentation!

However, the first note marked as "important" has a small typo.
Original message:
When an OLE DB provider is used, the account under which the SQL Server service runs must have read and execute permissions for the directory, and all subdirectories, in which the provider is installed. This includes Microsoft released provider, and any thirtd-party providers.

New message:
When an OLE DB provider is used, the account under which the SQL Server service runs must have read and execute permissions for the directory, and all subdirectories, in which the provider is installed. This includes the Microsoft-released provider and any third-party providers.

It would also be nice to have some more details on what exactly is a "loopback linked server", it's intended purpose and why it's meant for testing purposes only.  Where does it fall short?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7695b6a-e69f-7ee8-6493-d6276d5ea167
* Version Independent ID: 71d085f6-643b-4223-54d7-be831a9b0bf3
* Content: [Linked Servers (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/linked-servers/linked-servers-database-engine?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/linked-servers/linked-servers-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/linked-servers/linked-servers-database-engine.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@AngryRhetoric -- thank you Kevin for your compliment and for your attention to detail.  I have fixed the typos in that article and those corrections are now live.

@stevestein -- Steve, can you provide additional information or links for "loopback linked servers"?

**Comment by stevestein** [comment]
@AngryRhetoric - thanks for raising this issue. For linked servers that link to themselves, did you have a specific question? There's a note at the bottom of the article that explains what they are and why to use for testing only: 

_**Linked servers can be defined to point back (loop back) to the server on which they are defined.** Loopback servers are most useful when testing an application that uses distributed queries on a single server network. Loopback linked servers are intended for testing and **are not supported for many operations, such as distributed transactions**._

**Comment by WilliamAntonRohm** [comment]
@AngryRhetoric -- thank you for contacting us.  I believe Steve has answered your question.

I am closing this issue 2421 now.  You are welcome to @ mention me for any followup.

We hope to hear from you again.

**Comment by AngryRhetoric** [comment]
@WilliamAntonRohm and @stevestein 
Thank you both for the updated article and the mention of the comment.  I did read that, and it helps a bit...but I was hoping to know why it's not supported for many operations such as distributed transactions.  I believe our product is using it in production and it would be nice if the article detailed why this is a bad idea.

Take care,

-Kevin

**Comment by WilliamAntonRohm** [comment]
@stevestein -- please look into adding this information to that article.
