### ISSUE TITLE
Incorrect syntax near 'WAIT_STATS_CAPTURE_MODE'.

### ISSUE THREAD

**Issue by ronascentes** [MicrosoftDocs/sql-docs#2423]
This command could have a sintax error since it is not parsed:

ALTER DATABASE <database name>   
SET QUERY_STORE (  
    OPERATION_MODE = READ_WRITE,  
    CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30),  
    DATA_FLUSH_INTERVAL_SECONDS = 3000,  
    MAX_STORAGE_SIZE_MB = 500,  
    INTERVAL_LENGTH_MINUTES = 15,  
    SIZE_BASED_CLEANUP_MODE = AUTO,  
    QUERY_CAPTURE_MODE = AUTO,  
    MAX_PLANS_PER_QUERY = 1000,
    WAIT_STATS_CAPTURE_MODE = ON 
);

Msg 102, Level 15, State 1, Line 11
Incorrect syntax near 'WAIT_STATS_CAPTURE_MODE'.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b587ab-50b8-eada-aa86-ba0c838c57ee
* Version Independent ID: f1fd2d52-b66f-4fbc-c54a-c688c4fd0f21
* Content: [Monitoring Performance By Using the Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by MightyPen** [comment]
@ronascentes Hi Rodrigo, I am not convinced there is anything wrong with the documentation and this code example. In the doc, the database name is represented by a placeholder `<database name>`. But the copy of the example pasted in your original comment has neither the placeholder nor a database name.
When I test the code example with an actual database name, it works fine, in SQL Server **2017**.
If you are using SQL **2016** or earlier, that could explain why you saw a problem.
I also noticed when I tested the example by using SSMS, that the keyword in question, `WAIT_STATS_CAPTURE_MODE`, is not colorized the proper way that all the other keywords are. But that is just a minor shortcoming of the SSMS tool, and is separate from the SQL engine.

I am now Closing this Issue 2423. 
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed. 
Thank you for submitting this Issue. We hope to hear from you again.
