### ISSUE TITLE
Conversion table is misleading

### ISSUE THREAD

**Issue by KathiKellenberger** [MicrosoftDocs/sql-docs#2424]
There are too many implicit conversion symbols in this table. For example, varchar in the FROM lined up with int in the TO shows the implicit conversion symbol as expected. If you look at int in FROM and line it up with varchar in TO, it also shows the implicit conversion symbol which is not correct. I've always found the information in this page https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-type-precedence-transact-sql?view=sql-server-2017 to be correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84062379-c6f2-2af3-b1dd-560101d1fc0a
* Version Independent ID: 9c05fb90-d5ea-c494-e446-cd78a70a9785
* Content: [Data type conversion (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-type-conversion-database-engine?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/data-types/data-type-conversion-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/data-type-conversion-database-engine.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@KathiKellenberger @MikeRayMSFT Can you address this concern for a change to graphic?

**Comment by MikeRayMSFT** [comment]
Thank you @KathiKellenberger  for submitting this issue. I'm reaching out to @pmasl and others to verify.

**Comment by MikeRayMSFT** [comment]
When SQL Server does an implicit conversion, the data type with the lowest precedence is always converted to the data type with the higher precedence before any operators are applied. If there is a result, it is returned in the data type of the higher precedence.  

For example,
```sql
SELECT CONCAT(1, ' is an int converted to char')
```
Result:
1 is an int converted to char

Does that make sense? I’m working with my team to clarify the article.

Thank you for raising this issue. 

Including @bluefooted for additional insight.

**Comment by KathiKellenberger** [comment]
I agree with what you are saying about data types with lower precedence are always converted to higher. However, the FROM TO table on the Cast and Convert article and Data Type Conversion article make it look like it goes both directions. FROM int TO varchar has an orange circle when it should be a blue square.

________________________________

**Comment by KathiKellenberger** [comment]
Also, the CONCAT example is kind of misleading. This is a better example that shows that integers are NOT implicitly converted to char or varchar:

SELECT 1 + ' is an int converted to char'

Msg 245, Level 16, State 1, Line 3
Conversion failed when converting the varchar value ' is an int converted to char' to data type int.

________________________________

**Comment by bluefooted** [comment]
The rules of data type precedence do come into play with expressions and comparisons, but not with assignment. If you declare a variable of type varchar and assign an integer value to it, SQL Server will implicitly convert the int to varchar. Here's an example:

declare @string varchar(10);
SET @string = 1;
SELECT @string + ' is a string.'

The same would be true if you inserted an integer into a varchar column. You won't get an error, you'll get an implicit conversion. We would also implicitly convert a varchar to an int if the column or variable type is int. As long as the string can be converted to an integer, there won't be an error. So the matrix applies to all types of implicit conversions, not just comparisons and expressions. I can see how this would be confusing though, I'm open to how to change the language to make it clearer.

**Comment by KathiKellenberger** [comment]
OK, I do agree that the chart works for assignment, but not comparisons. The reason this came up was because I'm editing a book and the author stated that integers are always implicitly converted to varchars during comparisons based on the information in this table. This is what she says which I think is incorrect:


"Microsoft has pretty thorough documentation on datatype conversions, and it’s really easy to find. It is on their CAST and CONVERT Books-on-Line page: https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-2017

There is a big chart that will tell you which datatypes you can convert into what other datatypes. There are pretty dots that indicate where implicit conversion takes place. That’s all well and good, but what does it mean?

Let’s say we have an integer field and we need to compare it to a varchar field which has some integers in it but still stored as varchar. SQL Server will implicitly convert all of the integer fields into varchars for the comparison.  Let’s re-read that last sentence: SQL Server will implicitly convert ALL OF THE INTEGER FIELDS. The whole table. Because, we don’t know if records equal other records unless we can compare the values, so we have to do a table or index scan so we can first convert ALL THE VALUES in the integer field to varchar, so we can determine whether they are equivalent. This can prevent the use of an index."

Is there a way to clarify this table so that readers can understand where this applies?


Thanks,

Kathi






________________________________



________________________________

**Comment by bluefooted** [comment]
Ah yes, definitely see how that is confusing. What if we add a paragraph after the matrix that makes the distinction between assignments where the resulting data type is determined by the statement vs. comparisons and expressions where the resulting data type is determined by the rules of data type precedence and include that link?

**Comment by KathiKellenberger** [comment]
That sounds good!

Thanks,
Kathi

________________________________

**Comment by MikeRayMSFT** [comment]
Would this be sufficient?

The illustration shows how conversions are applied on assignment. An assignment happens when a variable is assigned a value or when a column is updated. For example,

```sql
declare @string varchar(10);
SET @string = 1;
SELECT @string + ' is a string.'
```

Conversions do not apply to comparisons or expressions. The following example adds integer `1` to the character `c`. 

```sql
SELECT 1 + ' c'
```
The expression returns an error.

`Msg 245, Level 16, State 1, Line 3 Conversion failed when converting the varchar value 'c' to data type int.`

SQL Server does not convert comparisons or expressions.

**Comment by KathiKellenberger** [comment]
Not sure. Conversions do apply to comparisons and expressions according to the precedence list found here: https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-type-precedence-transact-sql?view=sql-server-2017

This works, for example:

SELECT 1 + '2'


________________________________

**Comment by MikeRayMSFT** [comment]
Thanks @KathiKellenberger  - I've signed off on my update, without the explicit exclusion for conversions. I'll work with our engineering team to be more specific. For now I'm closing this issue.

**Comment by bluefooted** [comment]
@KathiKellenberger I'm working with Mike on this one offline, we'll submit a more detailed update in a separate PR and I can let you know when that publishes.

**Comment by KathiKellenberger** [comment]
Thanks, Pam!

________________________________
