### ISSUE TITLE
Error on Creating Session

### ISSUE THREAD

**Issue by Nubestic** [MicrosoftDocs/sql-docs#2425]
Following all instruction and created credentials 

CREATE EVENT SESSION [session2] ON DATABASE 
ADD EVENT sqlserver.sql_statement_completed(
    ACTION(sqlserver.client_app_name,sqlserver.client_connection_id,sqlserver.client_hostname,sqlserver.client_pid,sqlserver.database_id,sqlserver.database_name,sqlserver.session_id,sqlserver.sql_text,sqlserver.username))
ADD TARGET package0.event_file(SET filename=N'https://my47storage.file.core.windows.net/sqlextendedevent/filename.xel')
WITH (STARTUP_STATE=ON)
GO

Error:
Msg 40538, Level 16, State 3, Line 51
A valid URL beginning with 'https://' is required as value for any filepath specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b79d736-c8b0-a460-501a-71c590092bc9
* Version Independent ID: f5c34ba9-0a5d-0af5-c4e5-c99d5572e6d5
* Content: [CREATE EVENT SESSION (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-event-session-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/create-event-session-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-event-session-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@MsSQLGirl  Hi Julie -- GeneMi says you used to work on extended events.  If you are still working in this area, please advise on the following, or please let me know who is now working on it:

Using SQL Server 2017 on-premises, the customer's example code works when I code `ON SERVER`.  With an Azure SQL Database, I get the same error when I code `ON DATABASE` that they encountered.

Why is this command invalid when running on Azure SQL Database?

**Comment by CarlRabeler** [comment]
@MsSQLGirl see this article https://docs.microsoft.com/azure/sql-database/sql-database-xevent-code-event-file#transact-sql-code 
Updating the article you referenced to point to this example for SQL Database. Thanks for your question.
Carl

**Comment by CarlRabeler** [comment]
#please-close

**Comment by iLikeAzureSQL** [comment]
Please clarify if the issue is resolved and we can create external storage for Azure SQL DB extended events.

**Comment by CarlRabeler** [comment]
referenced article shows how to store extended events to blob storage
