### ISSUE TITLE
Powershell registration returns me a bunch of errors

### ISSUE THREAD

**Issue by anddrzejb** [MicrosoftDocs/sql-docs#2426]
( https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/register-a-database-as-a-dac?view=sql-server-2017#RegisterDACPowerShell )

Trying to execute the script given in the manual, my powershell fails on first line:
`CD SQLSERVER:\SQL\localhost\DEFAULT`
with a message
```
cd : Cannot find drive. A drive with the name 'SQLSERVER' does not exist.
At line:1 char:1
+ cd SQLSERVER:\SQL\localhost\DEFAULT
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SQLSERVER:String) [Set-Location], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
```

I managed to solve this once I run 
`invoke-sqlcmd`
and then
`CD SQLSERVER:\SQL\localhost\DEFAULT`

Still, when trying to execute 
` $registerunit = New-Object Microsoft.SqlServer.Management.Dac.DacExtractionUnit($srv, $dbname, $applicationname, $ver
sion)`

I get
```
New-Object : Cannot find type [Microsoft.SqlServer.Management.Dac.DacExtractionUnit]: verify that the assembly
containing this type is loaded.
At line:12 char:17
+ ... isterunit = New-Object Microsoft.SqlServer.Management.Dac.DacExtracti ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
```

When looking for a solution I reinstalled the following components of the feature pack:
SQLSysClrTypes.msi, SharedManagementObjects.msi, PowerShellTools.msi but this didn't work either.

I am using SQLExpress 2016.

**Comment by msebolt** [comment]
@anddrzejb Thank you for the feedback!  Can you point to the specific reference point?

**Comment by anddrzejb** [comment]
Don't really know how to do that. I mean this [link](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/register-a-database-as-a-dac?view=sql-server-2017#RegisterDACPowerShell) will take you to the exact section that I was trying to recreate, but failed.

**Comment by MightyPen** [comment]
@stevestein Hi Steve, you are the owner of record for the cited article, so can you please process this PowerShell Issue #2426.

**Comment by stevestein** [comment]
@anddrzejb - thanks for raising this issue. I ran into the same error.

@MSraye - Can you take a look at this one. I can register fine in SSMS, but it fails with the PowerShell script in this article. Thanks!

**Comment by MSraye** [comment]
@stevestein Hi Steve, seems you reach out to the wrong contact. DAC isn't under the scope of SSIS.

**Comment by stevestein** [comment]
@MSraye - Thanks Ran. 

I started an internal thread to locate someone who can assist on this.

**Comment by stevestein** [comment]
@anddrzejb - Dac registration is an older feature that is no longer working/supported and is in the process of being deprecated. I created an internal work item (1571961) to add info to the relevant articles.

**Comment by stevestein** [comment]
We're going to go ahead and close this issue. Feel free to provide additional comments.

Thanks again for raising this issue.
