### ISSUE TITLE
mssql-java:ctp3.1 not found

### ISSUE THREAD

**Issue by jtpower** [MicrosoftDocs/sql-docs#2427]
Error response from daemon: manifest for private-repo.microsoft.com/mssql-private-preview/mssql-java:ctp3.1 not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19e2a7b-c117-a829-8fa1-8169eebf07ea
* Version Independent ID: 09c0053c-7966-9be0-2aec-09155189c482
* Content: [Deploy offline - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-offline?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/big-data-cluster/deploy-offline.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-offline.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by jtpower** [comment]
#!/bin/bash
set -e

SQL_BDC_VERSION=ctp3.1

MICROSOFT_SQLBDC_PRIVATE_URL=private-repo.microsoft.com/mssql-private-preview
PRIVATE_URL=docker-private.com/private-sql-bdc-${SQL_BDC_VERSION}

images=(mssql-appdeploy-init:${SQL_BDC_VERSION}
mssql-monitor-fluentbit:${SQL_BDC_VERSION}
mssql-monitor-collectd:${SQL_BDC_VERSION}
mssql-server-data:${SQL_BDC_VERSION}
mssql-hadoop:${SQL_BDC_VERSION}
mssql-java:${SQL_BDC_VERSION}
mssql-mlservices-pythonserver:${SQL_BDC_VERSION}
mssql-mlservices-rserver:${SQL_BDC_VERSION}
mssql-monitor-elasticsearch:${SQL_BDC_VERSION}
mssql-monitor-influxdb:${SQL_BDC_VERSION}
mssql-security-knox:${SQL_BDC_VERSION}
mssql-mlserver-r-runtime:${SQL_BDC_VERSION}
mssql-mlserver-py-runtime:${SQL_BDC_VERSION}
mssql-controller:${SQL_BDC_VERSION}
mssql-mleap-serving-runtime:${SQL_BDC_VERSION}
mssql-server-controller:${SQL_BDC_VERSION}
mssql-monitor-grafana:${SQL_BDC_VERSION}
mssql-monitor-kibana:${SQL_BDC_VERSION}
mssql-service-proxy:${SQL_BDC_VERSION}
mssql-app-service-proxy:${SQL_BDC_VERSION}
mssql-ssis-app-runtime:${SQL_BDC_VERSION}
mssql-monitor-telegraf:${SQL_BDC_VERSION})

docker login private-repo.microsoft.com -u ??? -p ???

for imageName in ${images[@]} ; do
  docker pull $MICROSOFT_SQLBDC_PRIVATE_URL/$imageName
done

docker login docker-private.com -u ??? -p ???

for imageName in ${images[@]} ; do
  docker tag  $MICROSOFT_SQLBDC_PRIVATE_URL/$imageName $PRIVATE_URL/$imageName
  docker push $PRIVATE_URL/$imageName
done

docker images
docker rmi $(docker images | grep -v registry | grep -v REPOSITORY | awk '{print $1":"$2}')

**Comment by rothja** [comment]
@jtpower Thanks for letting us know about this error. @mihaelablendea, I've assigned this git issue to you to take a look at and see if you can help identify the solution. I'm including @MikeRayMSFT as well. Thank you!

**Comment by WilliamAntonRohm** [comment]
@mihaelablendea, @MikeRayMSFT -- please look into this aging issue 2427.

**Comment by MikeRayMSFT** [comment]
Article has been updated with more current instructions.

https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-offline?view=sqlallproducts-allversions
