### ISSUE TITLE
"left over" > "leftover"

### ISSUE THREAD

**Issue by jhays-nhaschools** [MicrosoftDocs/sql-docs#2429]
On the page described below, make the following typo correction:
"left over" > "leftover"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45eba8b0-0c31-d65b-f1ca-0ed260eb2f14
* Version Independent ID: fe2a79c1-6512-36f6-3118-cda7d18531de
* Content: [Using PIVOT and UNPIVOT - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/from-using-pivot-and-unpivot?view=sql-server-2017)
* Content Source: [docs/t-sql/queries/from-using-pivot-and-unpivot.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/from-using-pivot-and-unpivot.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by MightyPen** [comment]
Fixing this Issue 2429 with PR 10912.
`https://github.com/MicrosoftDocs/sql-docs-pr/pull/10912`

**Comment by MightyPen** [comment]
@jhays-nhaschools Thank you for bringing this mistake to our attention. This Issue 2429 is now fixed. The fix should be live on Docs by tomorrow afternoon (or maybe sooner).

A very effective option that many customers like is to - directly edit Microsoft's documentation article, to fix or update as you see fit.  We then review the proposed change, and hopefully we approve the update to go live.
To do this, you click the "Edit"-pencil icon near the upperRight on the Docs webpage, and then click the pencil on the GitHub webpage. This enables you to edit, and to then click to create a Pull Request that contains your update. We then see that PR. It is just a nice option.

I am now Closing this Issue 2429, as fixed. The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed. 
Thank you for submitting this Issue. We hope to hear from you again.

 . .
