### ISSUE TITLE
Query Function Request: REPLACE_COLUMN(col_list, col_name, replace_value)

### ISSUE THREAD

**Issue by eric-impact** [MicrosoftDocs/sql-docs#2432]
If you ever have a table with like 25 columns and you want to be able to insert those values into another table, but modify one of the column values on the way you have to type out the names of each column until you get to the column you want to change and then follow the remaining. This can be annoying from a dev maintenance perspective because you have to change this logic every time a column is added. I like the idea of a REPLACE_COLUMN function that takes in the list of returned columns, the name of the column you wish to replace the value of and the value to be used instead. So if I wanted to return all the values from table [dbo].[tooManyCols] except for [rand1] I want a different value it would be something like...

SELECT REPLACE_COLUMN(*,rand1,'different value')
FROM [dbo].[tooManyCols] AS t

OR

SELECT REPLACE_COLUMN(*,rand1,CASE WHEN rand1 BETWEEN 1 AND 5 THEN rand2 ELSE rand3 END)
FROM [dbo].[tooManyCols] AS t

... if I wanted to change the value of two of the columns I would just nest the function into the col_list...

SELECT REPLACE_COLUMN(REPLACE_COLUMN(*,rand1,'NewVal1'),rand2,'NewVal2') 
FROM [dbo].[tooManyCols] AS t

**Comment by mburbea** [comment]
This repository is for documentation, not for Sql server features. That said, while this in theory could be useful, production quality code should never really use *. SSMS has handy shortcuts like dragging the columns of a table, will produce the column list for you.

**Comment by msebolt** [comment]
@eric-impact Thank you for your feedback.

Please submit your request via the [SQL Server forum](https://feedback.azure.com/forums/908035-sql-server).
