### ISSUE TITLE
SysEndTime in the CurrentTable

### ISSUE THREAD

**Issue by AlexC84** [MicrosoftDocs/sql-docs#2433]
Why does the 'Current' table need a SysEndTime field if it always has the same value stored in it? Every record in the 'Current' table is live so there is no need for SysEndTime in the 'Current' table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f9c244b-870b-737f-6f6d-db9675179427
* Version Independent ID: 3dde09ff-88b5-f6f3-1120-3bf8a90a395e
* Content: [Temporal Tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/tables/temporal-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/temporal-tables.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@AlexC84 Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. 

Please feel free to submit your idea to the [Sql Server forums](https://feedback.azure.com/forums/908035-sql-server).
