### ISSUE TITLE
What is Informatica and why is it mentioned in this documentation?

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/sql-docs#2434]
It seems like this is documentation for SQL Server, not Informatica. Why is Informatica’s lack of support for seconds mentioned here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae4b3aeb-9874-c8a2-980d-9bdbbea8fdf3
* Version Independent ID: 41808935-91fb-6f3a-db0f-6d7193123e33
* Content: [datetimeoffset (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetimeoffset-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/data-types/datetimeoffset-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/datetimeoffset-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
@bikni thanks for pointing this out. I'm checking and will update.

**Comment by MikeRayMSFT** [comment]
@binki - thanks for noticing this. We're updating the article.

**Comment by binki** [comment]
@MikeRayMSFT Thanks for looking into this!

Just wondering, where is the changeset/PR for the article’s update? Shouldn’t my issue be kept open until then?

Thanks again!
