### ISSUE TITLE
Change tar.gz to tar

### ISSUE THREAD

**Issue by jtpower** [MicrosoftDocs/sql-docs#2437]
-- Not work
tar zxvf python-3.6.6-linux-x64-0.0.1.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

-- Work
tar xvf python-3.6.6-linux-x64-0.0.1.tar.gz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19e2a7b-c117-a829-8fa1-8169eebf07ea
* Version Independent ID: 09c0053c-7966-9be0-2aec-09155189c482
* Content: [Deploy offline - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-offline?view=sqlallproducts-allversions)
* Content Source: [docs/big-data-cluster/deploy-offline.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-offline.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@jtpower Thanks for the feedback. In this article, we don't specify how to extract the linux tar.gz file. Are you suggesting that we put the example on how to do this for Linux with the command you provided? Thank you!

**Comment by jtpower** [comment]
Use the file suffix have some confuse, normally, extract Type tar.gz files use parameter zxvf, Type tar use xvf to extract.
Suggest:
Modify the package file suffix from tar.gz to tar, or provide command that work fine. Our most customer been Windows-Based, At Linux platform maybe need we do more.

Personal experience:

  *   The Python package for offline deploy SQL BDC, have two core work items:

  1.  Download file “requirements.txt”
  2.  Install mssqlctl tool

  *   I have three experience：

  1.  The basic Python Package too large.
  2.  Our requirements.txt by https provide, Need to configure openssl for python; if just extract current package files and run:

pip download -r https://private-repo.microsoft.com/python/ctp{{-version|version }/mssqlctl/requirements.txt<https://private-repo.microsoft.com/python/ctp%7b%7d/mssqlctl/requirements.txt> will be SSL error.

  1.  All SQL BDC version online requirements.txt first row has: --find-links=https://private-repo.microsoft.com/python/ctp{-version|version}/mssqlctl/,

if do not remove this row to offline execute command: pip install --no-index --find-links <path-to-packages> -r <path-to-requirements.txt> will be error. You can test it.
Suggest:

  *   Just provide python URL: https://www.python.org/downloads/release/python-373/
  *   Remind user need to configure openssl for python or provide for offline deploy BDC’ requirements.txt file by http or other way.

**Comment by jtpower** [comment]
> @jtpower Thanks for the feedback. In this article, we don't specify how to extract the linux tar.gz file. Are you suggesting that we put the example on how to do this for Linux with the command you provided? Thank you!

* Use the file suffix have some confuse, normally, extract Type tar.gz files use parameter zxvf, Type tar use xvf to extract.

* Suggest:
Modify the package file suffix from tar.gz to tar, or provide command that work fine. Our most customer been Windows-Based, At Linux platform maybe need we do more.

**Comment by jtpower** [comment]
Personal experience:
* The Python package for offline deploy SQL BDC, have two core work items:
1.	Download file “requirements.txt”
2.	Install mssqlctl tool
* I have three experience：
1.	The basic Python Package too large.
2.	Our requirements.txt by https provide, Need to configure openssl for python; if just extract current package files and run:
pip download -r https://private-repo.microsoft.com/python/ctp{{-version|version }/mssqlctl/requirements.txt will be SSL error.
3.	All SQL BDC version online requirements.txt first row has: --find-links=https://private-repo.microsoft.com/python/ctp{-version|version}/mssqlctl/, 
if do not remove this row to offline execute command: pip install --no-index --find-links <path-to-packages> -r <path-to-requirements.txt> will be error. You can test it.

Suggest:
•	Just provide python URL: https://www.python.org/downloads/release/python-373/
•	Remind user need to configure openssl for python or provide for offline deploy BDC’ requirements.txt file by http or other way.

**Comment by rothja** [comment]
@jtpower Thank you for your detailed feedback and suggestions. We need to probably review and update this article using this feedback. I have created a work item internally to track this request, and we will get to this as soon as we can. Thank you, again!
