### ISSUE TITLE
should specify that contained users in master cannot create databases

### ISSUE THREAD

**Issue by arnoschuring** [MicrosoftDocs/sql-docs#2439]
The documentation on the dbmanager role states (correctly) that members of this role can create databases, and also states (correctly) that contained users in master can be added to this role. However, a contained user cannot create databases even if they are a member of the dbmanager role (they will get permission denied)!

I suspect that this is related to the explanation below that the user then becomes a member of the dbo role of the created database, which is only possible for logins, not contained users. It would be nice if the documentation mentioned this explicitly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d95c4e-dfbb-ec5a-7df9-8a8d33be5b83
* Version Independent ID: a35a9368-4e76-6d55-7e90-34e925b34dd7
* Content: [Database-Level Roles - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/authentication-access/database-level-roles.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/database-level-roles.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @arnoschuring! Thank you for bringing this feedback to us. I have verified, and made the changes to our documentation to reflect that contained database users added to the dbmanager role cannot create new databases. This should go live shortly. We appreciate your assistance with making our documentation better!

https://github.com/MicrosoftDocs/sql-docs-pr/pull/11004

#please-close
