### ISSUE TITLE
ENABLE_PARALLEL_PLAN_PREFERENCE

### ISSUE THREAD

**Issue by excelosaurus** [MicrosoftDocs/sql-docs#2442]
Add info about ENABLE_PARALLEL_PLAN_PREFERENCE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33da0c41-feb0-82a9-0ce9-9e2dbe58a1c4
* Version Independent ID: 4a97457a-c149-3c41-b78a-5b4e3869f078
* Content: [Query Hints (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-query?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/queries/hints-transact-sql-query.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/hints-transact-sql-query.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please look into this aging issue 2442.

**Comment by VanMSFT** [comment]
Hello @excelosaurus! Thank you for your feedback on our documentation. Unfortunately, we have to decline on adding information about ENABLE_PARALLEL_PLAN_PREFERENCE. That is an undocumented query hint that is meant for troubleshooting purposes and is to be used at the direction of Microsoft Support. We normally do not document certain query hints/trace flags intentionally as it may lead to performance issues or other unintended consequences.
