### ISSUE TITLE
Strange text inclusion - Planned Relocation step 5

### ISSUE THREAD

**Issue by andrewtobin** [MicrosoftDocs/sql-docs#2443]
The following text is included in the document, under step 5. It feels misplaced.

“We are listening: If you find something outdated or incorrect in this article, such as a step or a code example, please tell us. You can click the This page button in the Feedback section at the bottom of this page. We read every item of feedback about SQL, typically the next day. Thanks.“

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378754cc-abd5-2c11-4662-3da9af6094f9
* Version Independent ID: b6ae6f68-11b3-adb2-5ed2-c882bae020f3
* Content: [Move User Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/move-user-databases?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/databases/move-user-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/move-user-databases.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@andrewtobin Hello Andrew, By "misplaced" do you mean the cited text should moved to a different location in the article? Or do you mean the text should not be in the article at all? Or that the text is strangely worded and should be better written or rephrased or just shortened? Or is the text interlude annoying?

Our goal is to encourage a higher percentage of customers who read our documentation - to click the 'This Page' button/link (at the bottom of the article) when they detect something that is out-of-date or in error. Numbered Steps tend to be a well-defined section that is particularly important to keep accurate. The text you cited is an effort we decided to experiment with for a little while. If people do not like it, then at the end of the experiment we will conclude against continuing to include the text. So your feedback here counts. We are very open to suggestion as to how else we can increase the percentage who click 'This Page' when the article has an inaccuracy.
And we want those people who have so far decided against clicking to know that their comments will actually be studied, and promptly so.

Thank you for any further detail or suggestion you can provide. I am keeping this Issue #2443 open for a couple more days, in hopes of receiving further comment on this situation. Thanks again.

**Comment by MightyPen** [comment]
Closing this settled Issue 2443.
