### ISSUE TITLE
Select output as a JSON array (Single column list. Ex: List of IDs)

### ISSUE THREAD

**Issue by nabilahmed739** [MicrosoftDocs/sql-docs#2453]
I'm trying to find a way to get a simple JSON array as the output of the Select query.

**Example:** `Select ID from Employee where <SomeCondition> FOR JSON AUTO`
**Actual Output:** 

> [{"ID":1},{"ID":2},{"ID":3}]

**Expected Output:** 

> [1, 2, 3]

**Comment by MightyPen** [comment]
@nabilahmed739 Hello, we have at least two documentation articles on FOR JSON AUTO that you can look at:

- https://docs.microsoft.com/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server
- https://docs.microsoft.com/sql/relational-databases/json/format-json-output-automatically-with-auto-mode-sql-server

If the documentation is in error, this Issues website can assist. But no documentation error is being reported here in Issue #2453 .
At the bottom of the above bullet-listed articles, there is a **button/link labeled "This Product"** (different than "This Page"). The "This Product" link is appropriate for you to click if you want fixes or enhancements to Microsoft SQL Server (which is different than a fix to the documentation).

I am now closing this Issue #2453. The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.
Thank you for submitting this Issue. We hope to hear from you again.
