### ISSUE TITLE
Always post results!

### ISSUE THREAD

**Issue by JeffModen** [MicrosoftDocs/sql-docs#2455]
It would be nice if you'd take the extra bit of time to post the results of the demo query especially when people avoid such sample databases as AdventureWorks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4313ba5-7e1a-acd8-9e58-3e90d040b181
* Version Independent ID: 9b6dff50-023a-b158-983f-3c6daa6adc28
* Content: [sp_special_columns (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-special-columns-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-special-columns-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-special-columns-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@JeffModen Hi Jeff, I agree with you. We do not have a formal policy on this, and sometimes it is impractical to provide the output. But generally you are right.
I will mention this situation to the SQL Writing team.

I am now Closing this Issue 2455. 
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed. Thank you for submitting this Issue. We hope to hear from you again.

**Comment by JeffModen** [comment]
Thanks for the quick response and the feedback, Gene.
--Jeff Moden

    On Monday, July 8, 2019, 1:07:33 PM EDT, Gene Milener <notifications@github.com> wrote:  
 
 
@JeffModen Hi Jeff, I agree with you. We do not have a formal policy on this, and sometimes it is impractical to provide the output. But generally you are right.
I will mention this situation to the SQL Writing team.

I am now Closing this Issue 2455.
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed. Thank you for submitting this Issue. We hope to hear from you again.
