### ISSUE TITLE
Active Directory - Integrated Not Supported

### ISSUE THREAD

**Issue by databoxinsights** [MicrosoftDocs/sql-docs#2469]
This connection option does not appear to be supported in vscode. Could you provide an example or please add this feature? Thanks.

**Comment by WilliamAntonRohm** [comment]
@databoxinsights -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
