### ISSUE TITLE
Stored procedure accessing more than 64 databases

### ISSUE THREAD

**Issue by rsocol** [MicrosoftDocs/sql-docs#2470]
The page contains the following statement: "If a stored procedure accesses more than 64 databases, or more than 2 databases in interleaving, you will receive an error." This statement seems to be outdated or unclear, because I have tried to create a stored procedure that contains a SELECT query with UNION ALL accessing 100 databases and it works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 780e3e16-ac52-1343-fe0a-a706c71ddb92
* Version Independent ID: 6f09b278-faa0-6f0d-1013-c1ae62ca006c
* Content: [Maximum Capacity Specifications for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server?view=sql-server-2017)
* Content Source: [docs/sql-server/maximum-capacity-specifications-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/maximum-capacity-specifications-for-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@rsocol -- thank you for your feedback; we appreciate it.

@MikeRayMSFT -- please look into this Issue 2470.

**Comment by MikeRayMSFT** [comment]
@rsocol - thank you, I'm verifying this with engineering.

**Comment by MikeRayMSFT** [comment]
@rsocol - can you verify if your tests were nested stored procedures?

**Comment by rsocol** [comment]
The initial test was a single stored procedure containing something like this:

CREATE PROCEDURE p
AS
SELECT COUNT(*) FROM D1.sys.tables
UNION ALL SELECT COUNT(*) FROM D2.sys.tables
...
UNION ALL SELECT COUNT(*) FROM D100.sys.tables

I also tried today to access a regular table in each database (instead of accessing sys.tables) and to create another stored procedure:

CREATE PROCEDURE P2
AS
EXEC P

Both procedures executed without errors.

I understand the limit "Nested stored procedure levels" being 32. I tested that limit and it works as expected, i.e. I got the error "Maximum stored procedure, function, trigger, or view nesting level exceeded (limit 32)."

My problem was strictly related to the comment saying "If a stored procedure accesses more than 64 databases, or more than 2 databases in interleaving, you will receive an error." This comment seems unrelated to the nesting limit (it says "a stored procedure").

**Comment by MikeRayMSFT** [comment]
@rsocol thank you for the clarification. I agree that the comment seems unrelated. Working on an appropriate update.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please process this aging issue 2470.

**Comment by MikeRayMSFT** [comment]
-	The limitation of accessing more than 64 databases applies if such accesses take place on different levels of nesting in the chain of stored procedure calls. It does not apply to the number of database references made at the same nested level.
