### ISSUE TITLE
"The Docker image"

### ISSUE THREAD

**Issue by kierenj** [MicrosoftDocs/sql-docs#2471]
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-2017#docker - which docker image is "the" docker image? I came here from googling how to grab the tools...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-2017#docker)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@kierenj -- Kieren, thank you for asking this clarifying question. 

@rothja -- Jason, please process this Issue 2471.

**Comment by rothja** [comment]
@kierenj Thank you for asking this. This is just referring to running SQL Server docker containers. The image used for the container contains the tools. There is a quickstart on how to run SQL Server in a container here: https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash. 

@WilliamAntonRohm can you please change this paragraph:

```
The SQL Server command-line tools are included in the Docker image. If you attach to the image with an interactive command-prompt, you can run the tools locally.
```

To:

```
If you [run SQL Server in a docker container](quickstart-install-connect-docker.md), the SQL Server command-line tools are already included in the Docker image. If you attach to a running container with an interactive bash shell, you can run the tools locally.
```

Thank you, and let me know if this helps.

**Comment by kierenj** [comment]
Can I suggest that the problem is the words, "the docker image". I was googling how to run sql tools in docker, and came across a page which said "the docker image".

As a guess, maybe a good thing would be to say, the "the SQL Server Linux docker image, called `mcr.microsoft.com/mssql`" (or whatever it is)?

**Comment by rothja** [comment]
@kierenj Thanks for the additional clarification. I think you're right about the wording not being quite right around "the docker image". @WilliamAntonRohm, here is my new suggested edit. @kierenj let me know what you think;

```
If you [run SQL Server in a Docker container](quickstart-install-connect-docker.md), the SQL Server command-line tools are already included in the SQL Server Linux container image. If you attach to a running container with an interactive bash shell, you can run the tools locally.
```

**Comment by WilliamAntonRohm** [comment]
@rothja -- Jason, I've created the above [sql-docs-pr PR 11241](https://github.com/MicrosoftDocs/sql-docs-pr/pull/11241) with your suggested change.  If you're satisfied with the wording, please let me know & I'll auto-merge that paragraph.

**Comment by rothja** [comment]
@WilliamAntonRohm This looks great. Please sign off on the other PR to address this git issue. Thank you!

**Comment by WilliamAntonRohm** [comment]
@rothja -- thank you for confirming.

@kierenj -- I have made this update to the documentation and it should be live by tomorrow.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
