### ISSUE TITLE
Credit Card Function not included

### ISSUE THREAD

**Issue by Datachick** [MicrosoftDocs/sql-docs#2475]
The Function of "Credit Card" is missing from the Functions table under Defining a Dynamic Data Mask.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9408bf-18b5-339f-cd25-6a3024be3243
* Version Independent ID: eea4b8dc-5598-b7e6-e01a-902d5ca1f96d
* Content: [Dynamic Data Masking - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/dynamic-data-masking?view=sql-server-2017)
* Content Source: [docs/relational-databases/security/dynamic-data-masking.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/dynamic-data-masking.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by Datachick** [comment]
And I do realize that it really is just a drop down to get to a custom string.  But it's an option in the portal, so I should be discussed here.

**Comment by WilliamAntonRohm** [comment]
@Datachick Hi Karen, thank you for your feedback.

@VanMSFT Hi Van, please process this Issue 2475.

**Comment by VanMSFT** [comment]
@Datachick - Hi Karen! Are you talking about Azure SQL Server? If so, it's already listed here: https://docs.microsoft.com/en-us/azure/sql-database/sql-database-dynamic-data-masking-get-started

If you are talking about the page that is linked to this issue, masking a credit card number is done with "partial", and already discussed:

ADD MASKED WITH (FUNCTION = 'partial...

Please let me know if I have misunderstood.

Thanks!

**Comment by Datachick** [comment]
That is what I was talking about.  Apologies for not coming back to respond until now.
