### ISSUE TITLE
SchemaID is a valid property and isn't defined in the list of properties but is used in an example.

### ISSUE THREAD

**Issue by estimpson** [MicrosoftDocs/sql-docs#2478]
Furthermore, in previous versions of SQL owner_name(object_property(@id, 'OwnerID')) reliably returned the schema.  Now you would need to use schema_name(object_property(@id, 'SchemaID)).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce794da2-d198-5e15-22f4-39d65cbd933b
* Version Independent ID: c5c04b03-3250-498a-7d56-64660a79ea60
* Content: [OBJECTPROPERTY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/objectproperty-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/objectproperty-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/objectproperty-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@estimpson Hi Eric, thank you for your feedback.

@MikeRayMSFT Hi Mike, please process this Issue 2478.

**Comment by MikeRayMSFT** [comment]
Thanks for submitting this @estimpson - I'm going to add Schema ID right now. I'm going to need to clarify the ownerID functionality before I update that.

**Comment by estimpson** [comment]
Excellent.  Looks great
