### ISSUE TITLE
Enabling TDE for Availability Groups

### ISSUE THREAD

**Issue by Infinitism** [MicrosoftDocs/sql-docs#2481]
Hi, 

It'd be great if you could add a section on enabling TDE for Always On Availability Group with multiple nodes.

**Comment by WilliamAntonRohm** [comment]
@Infinitism -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by Infinitism** [comment]
@WilliamAntonRohm 

Hi, 

In the documentation on TDE (https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption?view=sql-server-2017), I think it would be helpful to cover how to enable TDE for AGs as well. 

Was this the context you wanted from me?
