### ISSUE TITLE
datetime2中文页面的存储大小有误

### ISSUE THREAD

**Issue by lichasu** [MicrosoftDocs/sql-docs#2483]
@airaou commented on [Wed Jul 10 2019](https://github.com/MicrosoftDocs/sql-docs.zh-cn/issues/114)

应为
精度小于 3 的 6 个字节。
精度为 3 和 4 的 7 个字节。
所有其他精度则需要 8 个字节。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: be8724bf-416a-437b-158c-a1f94019a36c
* Version Independent ID: 3b055d34-8d37-cca3-a916-caa43b69af6a
* Content: [datetime2 (Transact-SQL) - SQL Server](https://docs.microsoft.com/zh-cn/sql/t-sql/data-types/datetime2-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/data-types/datetime2-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/t-sql/data-types/datetime2-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by lichasu** [comment]
Hi team, please check this issue. Rough translation:

> 
> Should be
> 6 bytes with a precision less than 3.
> 7 bytes with a precision of 3 and 4.
> All other precisions require 8 bytes.

Thanks!

**Comment by WilliamAntonRohm** [comment]
@lichasu -- thank you for bringing this to our attention.  The distinction in this case appears to be between the current documentation with "3 or 4" and your suggestion of "3 and 4" -- in English, these are equivalent in this case.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
