### ISSUE TITLE
SSMS 18.1 locks when trying to restore a database with no backup

### ISSUE THREAD

**Issue by RobWoods-CPG** [MicrosoftDocs/sql-docs#2485]
When I try to restore a database from a file (click the device button) where there is no active backup for the database, the screen locks.

steps to reproduce.
1. Create new database
2. Right click on database and select restore
3. Try to restore from a file.

**Comment by markingmyname** [comment]
Thanks for the feedback! However, this area is primarily for doc issues. To report product issues, the best way to reach out to the SSMS Team is at [UserVoice](https://feedback.azure.com/forums/908035-sql-server).

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
