### ISSUE TITLE
Azure SQL Server as CMS

### ISSUE THREAD

**Issue by nprieto95** [MicrosoftDocs/sql-docs#2488]
This page says it applies to Azure SQL Database. However, when I try to configure an Azure SQL Server as a CMS from SSMS following the instructions of this page, I get this error: "Azure SQL Database cannot be used as a Central Management Server." This is confusing to me, am I doing something wrong or do these instructions not apply for Azure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7290dc83-139b-9cd0-f83c-3c247d7b11fe
* Version Independent ID: 7f0e8d3b-8bd1-7e75-2768-986fdc3f21b9
* Content: [Create a New Registered Server (SQL Server Management Studio) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/register-servers/create-a-new-registered-server-sql-server-management-studio?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/register-servers/create-a-new-registered-server-sql-server-management-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/register-servers/create-a-new-registered-server-sql-server-management-studio.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@markingmyname Hi Mark, can you please process this Issue 2488? Thanks.

**Comment by markingmyname** [comment]
@nprieto95,

Did you mean from this [article](https://docs.microsoft.com/en-us/sql/ssms/register-servers/create-a-central-management-server-and-server-group?view=sql-server-2017#SSMSProcedure)?

**Comment by markingmyname** [comment]
Also, I was able to make it work with an Azure SQL Database following the instructions.

Can you copy the link from the exact section of the article you are trying to follow, please?

thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by DBojsen** [comment]
Hi @markingmyname 
This is still an issue.  If you add an Azure SQL Database as a CMS, it works fine - until you start using it, then you get the error message "azure sql database cannot be used as a central management server".
I guess it has to do with Azure SQL DB not having MSDB database, where it seems this info is saved.

So please remove the checkmark for ASQLDB in the documentation article and potentially mention it cannot host the CMS.
