### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by GaborInancsi** [MicrosoftDocs/sql-docs#2489]
Option 1: Using UPN to configure the keytab
point 4:
"Delete all the entries by their slot number that are not the UPN. Do this one at a time by repeating the following command:

delent &lt;slot num&gt;"

is there really a "delent" command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Use AD authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **dygray**

**Comment by Dylan-MSFT** [comment]
Yes, there is a delent command. You have to be inside ktutil though. It would look like this:
>$ sudo ktutil
>ktutil: rkt /path/to/mssql.keytab
>ktutil: list
>ktutil: **delent \<slot number\>**
>ktutil: list

**Comment by WilliamAntonRohm** [comment]
@GaborInancsi -- thank you for your question.  

@Dylan-MSFT -- thanks for answering it.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
