### ISSUE TITLE
Document that either CR or LF ends a -- comment

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/sql-docs#2493]
The page says that "Comments inserted with -- are terminated by the newline character." Please document more specifically that the first U+000D (carriage return, \r) or U+000A (line feed, \n) terminates the comment, and that other characters such as U+0085 (next line) or U+2028 (line separator) do not terminate the comment. This information is useful for writing a T-SQL parser.

(It does not matter whether the parser recognizes a CR LF pair specifically in this context, because if it recognizes only the CR, then it will consume the LF as whitespace anyway.)

Testable with:

```SQL
SET NOCOUNT ON;

DECLARE @num AS int = 0;
DECLARE @sql AS nvarchar(4000);
DECLARE @result AS TABLE (val nvarchar(4000) NOT NULL);
DECLARE @isnewline AS TABLE (num int NOT NULL PRIMARY KEY);
DECLARE @problems AS TABLE (num int NOT NULL PRIMARY KEY, msg nvarchar(4000) NOT NULL);

WHILE @num < 65536
BEGIN
	DELETE @result;

	SET @sql = N'SELECT N''abc'' -- ' + NCHAR(@num) + N' + N''z''' + NCHAR(13) + NCHAR(10) + N' + N''def'';';

	BEGIN TRY
		INSERT @result (val)
		EXECUTE sp_executesql @stmt = @sql;
	END TRY
	BEGIN CATCH
		INSERT @problems (num, msg) VALUES (@num, ERROR_MESSAGE());
	END CATCH;

	IF (SELECT r.val FROM @result AS r) = N'abczdef'
	BEGIN
		INSERT @isnewline (num) VALUES (@num);
	END;

	SET @num = @num + 1;
END;

SELECT num, NCHAR(num) FROM @isnewline ORDER BY num;
SELECT num, NCHAR(num), msg FROM @problems ORDER BY num;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d4c3ccc-22a5-d3cc-fa22-53ddb41f8427
* Version Independent ID: 49e69c85-79ec-f46c-1005-b0592893a0a5
* Content: [-- (Comment) (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/comment-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/language-elements/comment-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/comment-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@KalleOlaviNiemitalo -- thank you for your feedback and your research.

@rothja -- Jason, please look into this Issue 2493.  If you can provide updated wording, I will make the change in the documentation.

**Comment by rothja** [comment]
@KalleOlaviNiemitalo Thank you for this feedback. I agree this is useful information to put into the article.

@WilliamAntonRohm Here is my suggested re-write in the article:

```
Use two hyphens (**--**) for single-line or nested comments. Comments inserted with **--** are terminated by a new line, which is specified with a carriage return character (U+000A), line feed character (U+000D), or a combination of the two. There is no maximum length for comments. The following table lists the keyboard shortcuts that you can use to comment or uncomment text.
```

**Comment by rothja** [comment]
#assign @WilliamAntonRohm

**Comment by rothja** [comment]
@WilliamAntonRohm I'm assigning this solely to you to avoid any confusion. Let me know if you have any questions about the fix. Thanks!

**Comment by WilliamAntonRohm** [comment]
I have made this update to the documentation, and it should be live by tomorrow.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by Edwardwsr** [comment]
Thanks for sharing good information
