### ISSUE TITLE
Document that backslash line continuation applies to LF or CR LF, but not to a sole CR

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/sql-docs#2494]
Please document that the line continuation feature of SQL Server deletes only these character sequences from the string literal:

* U+005C (backslash), U+000D (carriage return), U+000A (line feed)
* U+005C (backslash), U+000A (line feed)

In particular, it does not delete U+005C U+000D when the next character is not U+000A.  This information is useful for writing a T-SQL parser.

Testable with variations of:

```SQL
SET NOCOUNT ON;

DECLARE @num AS int = 0;
DECLARE @sql AS nvarchar(4000);
DECLARE @result AS TABLE (val nvarchar(4000) NOT NULL);
DECLARE @isnewline AS TABLE (num int NOT NULL PRIMARY KEY);
DECLARE @problems AS TABLE (num int NOT NULL PRIMARY KEY, msg nvarchar(4000) NOT NULL);

WHILE @num < 65536
BEGIN
	DELETE @result;

	SET @sql = N'SELECT N''abc\' + NCHAR(@num) + NCHAR(10) + N'def'';';

	BEGIN TRY
		INSERT @result (val)
		EXECUTE sp_executesql @stmt = @sql;
	END TRY
	BEGIN CATCH
		INSERT @problems (num, msg) VALUES (@num, ERROR_MESSAGE());
	END CATCH;

	IF (SELECT r.val FROM @result AS r) = N'abcdef' COLLATE Latin1_General_BIN2
	BEGIN
		INSERT @isnewline (num) VALUES (@num);
	END;

	SET @num = @num + 1;
END;

SELECT num, NCHAR(num) FROM @isnewline ORDER BY num;
SELECT num, NCHAR(num), msg FROM @problems ORDER BY num;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03d639c0-71aa-4c63-eb3b-4fba52a68904
* Version Independent ID: 3d4883e3-c5f1-d37d-7add-8c5ab55566da
* Content: [Backslash (Line Continuation) (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-backslash?view=sql-server-2017)
* Content Source: [docs/t-sql/language-elements/sql-server-utilities-statements-backslash.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/sql-server-utilities-statements-backslash.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@KalleOlaviNiemitalo -- thank you for your feedback and your research.

@rothja -- Jason, please look into this Issue 2494. If you can provide updated wording, I will make the change in the documentation.

Similar issue:  #2493

**Comment by rothja** [comment]
@KalleOlaviNiemitalo Again, thanks for making our docs more clear on this subject. I've verified your findings as well. 

@WilliamAntonRohm Could you please make the following rewording the remarks section:

```
## Remarks

This command returns the first and continued sections of the string as one string, without the backslash. The new line after the backslash must either be a line feed character (U+000A) or a combination of line feed (U+000A) and carriage return (U+000D) in that order. 
```
In addition, one of the samples has extra spaces after the backslash. @WilliamAntonRohm could you fix that too. It results in breaking the sample. Here is the fix:

```
### B. Splitting a binary string  

The following example uses a backslash and a carriage return to split a binary string into two lines.  

```  
SELECT 0xabc\
def AS [ColumnResult];  
```  
```

**Comment by rothja** [comment]
#assign @WilliamAntonRohm

**Comment by rothja** [comment]
@WilliamAntonRohm Just to avoid confusion, I'm reassigning this back to you to complete the change. Let me know if that works for you. Thank you! #reassign @WilliamAntonRohm

**Comment by PRMerger19** [comment]
WilliamAntonRohm is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by rothja** [comment]
@WilliamAntonRohm Just to avoid confusion, I'm reassigning this back to you to complete the change. Let me know if that works for you. Thank you! #reassign:@WilliamAntonRohm

**Comment by PRMerger19** [comment]
WilliamAntonRohm is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by rothja** [comment]
#reassign:@WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
I have made these updates to the documentation, and they should be live by tomorrow.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
