### ISSUE TITLE
Backslash escaping

### ISSUE THREAD

**Issue by mkxml** [MicrosoftDocs/sql-docs#2495]
The doc is stating that in order to escape the backslash you need ``\|`` when you actually need ``\\``

Please take a look.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56b615ec-8726-dcaf-9009-c0193aacc430
* Version Independent ID: 5d2a5218-d935-7b70-6fdb-10b80d163010
* Content: [How FOR JSON escapes special characters and control characters (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/how-for-json-escapes-special-characters-and-control-characters-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/json/how-for-json-escapes-special-characters-and-control-characters-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/how-for-json-escapes-special-characters-and-control-characters-sql-server.md)
* Product: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@mkxml -- Matheus, thank you for bringing this to our attention.  I am updating the documentation accordingly.

**Comment by WilliamAntonRohm** [comment]
@mkxml -- the change is in and should be live by tomorrow.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
