### ISSUE TITLE
How do we create the [sales].[dbo].[web_clickstreams_hdfs_parquet] table?

### ISSUE THREAD

**Issue by tnbarkhouse** [MicrosoftDocs/sql-docs#2498]
In Step 1. of the "Load data" section, the INSERT INTO...SELECT statement fails with the following error message:

    Msg 208, Level 16, State 1, Line 1
    Invalid object name 'sales.dbo.web_clickstreams_hdfs_parquet'.

I don't see where this external table gets created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf1b0e77-0f03-7b70-b2e3-26911e49dd47
* Version Independent ID: 511793e4-b3c5-3d07-a8e9-bc10b8347985
* Content: [Ingest data into a SQL Server data pool - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-sql?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/big-data-cluster/tutorial-data-pool-ingest-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/tutorial-data-pool-ingest-sql.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@tnbarkhouse -- thank you Trevor for your feedback.

@MikeRayMSFT -- Mike, please process this Issue 2498.

**Comment by MightyPen** [comment]
@WilliamAntonRohm 
Perhaps the earlier H2 section named "Create an external table in the data pool" is the answer?

- https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-sql?view=sqlallproducts-allversions#create-an-external-table-in-the-data-pool

**Comment by rl-msft** [comment]
the error happens after creating the external table, this is when we load into the external table with this script

SELECT wcs_user_sk, i_category_id, COUNT_BIG(*) as clicks
FROM sales.dbo.web_clickstreams_hdfs_parquet
    INNER JOIN sales.dbo.item it ON (wcs_item_sk = i_item_sk
        AND wcs_user_sk IS NOT NULL)
GROUP BY wcs_user_sk, i_category_id
HAVING COUNT_BIG(*) > 100;

Msg 208, Level 16, State 1, Line 1
Invalid object name 'sales.dbo.web_clickstreams_hdfs_parquet'.
Total execution time: 00:00:00.001

to follow the article having Sales database alone seems not not enough, seems we also need one step before loading the data into external table is to create  

"sales.dbo.web_clickstreams_hdfs_parquet" 

which seems can be created by this sample 

https://github.com/microsoft/sql-server-samples/tree/master/samples/features/sql-big-data-cluster/data-virtualization/storage-pool

we need to update the article to include how to create

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please look into this issue 2498.  If you prefer, I will create an Azure Boards work item to track this (and I will then close this issue).

**Comment by MikeRayMSFT** [comment]
@WilliamAntonRohm if you could create the Azure Boards work item and close, that will be great. I will loop in some PG resources on this thread.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- the work item is https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1579589

@tnbarkhouse -- Trevor, I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
