### ISSUE TITLE
What is the purpose of the double colon?

### ISSUE THREAD

**Issue by yg-rater8** [MicrosoftDocs/sql-docs#2499]
grant alter on schema :: whatever to whomever

I was able to get my work done by following the documentation example, but I completely don't understand the function of the :: other than empirically observing that the command works with it, but fails without it. 

Can someone please explain what this does?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c65a5cd0-c3a5-3a2f-86bd-37f751ff034c
* Version Independent ID: db167ad1-8603-a8f9-1a63-c04388515dfe
* Content: [GRANT Schema Permissions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-schema-permissions-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/grant-schema-permissions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/grant-schema-permissions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @yg-rater8! Thanks for your question. The double colon represents a scope qualifier. In this instance, users are able to GRANT permission to objects like SCHEMA, LOGIN, ect. The double colon tells SQL Server that SCHEMA is the class. Please see the following for more information: https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-transact-sql?view=sql-server-2017

I hope that helps! If there are no other concerns, I'll go ahead and close this issue.
