### ISSUE TITLE
Mistake (hh 00-14 ?)

### ISSUE THREAD

**Issue by kamisamanome** [MicrosoftDocs/sql-docs#2504]
In ISO 8601 part, "hh is two digits, ranging from 0 to 14," is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca577f7-34cc-52c9-a960-d81efdc9c46e
* Version Independent ID: eed233e6-4695-b583-2e95-12f77866ff6f
* Content: [time (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/time-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/data-types/time-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/time-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@kamisamanome Thank you for the feedback.

The change has been made.

#please-close
