### ISSUE TITLE
Incorrect last_run_duration definition

### ISSUE THREAD

**Issue by JonWiles-Smarsh** [MicrosoftDocs/sql-docs#2505]
Actually, last_run_duration is in hhmmss, not in seconds.  And if it exceeds 99 hours it is hhhmmss.  It is defined correctly here: https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/dbo-sysjobsteps-transact-sql?view=sql-server-2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21265d7-1a33-8c2e-9b2d-17ae28e2980c
* Version Independent ID: 65fa5f7d-b0ce-6c57-7311-030030e152cb
* Content: [sp_help_jobstep (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-help-jobstep-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-help-jobstep-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-help-jobstep-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@JonWiles-Smarsh Thank you for the feedback.

The change has been made.
