### ISSUE TITLE
SSMS 18.1 -- Doesn't work with Azure Servers

### ISSUE THREAD

**Issue by Scott123456** [MicrosoftDocs/sql-docs#2507]
When right-clicking a SQL Azure server I am already connected to there is no "Register" option. SSMS 18.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0674489e-3a2d-7898-5580-2a74b13f1a6a
* Version Independent ID: f380aa34-fe92-b756-9777-f39125616fb2
* Content: [Register a Connected Server (SQL Server Management Studio) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/register-servers/register-a-connected-server-sql-server-management-studio?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/register-servers/register-a-connected-server-sql-server-management-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/register-servers/register-a-connected-server-sql-server-management-studio.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@markingmyname Hi Mark, please process this Issue 2507.

**Comment by markingmyname** [comment]
@Scott123456,

I am able to work with my Azure Server with SSMS 18.1.

However, 18.2 was released this month.  Have you tried to [download](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017) it and see?

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
