### ISSUE TITLE
NOTRUNCATE is applicable only to data files. NONTRUNCATE doesn't affect the log file.

### ISSUE THREAD

**Issue by elbertlumenier** [MicrosoftDocs/sql-docs#2508]
There is a typo in the Arguments paragraph of the documentation: 
NOTRUNCATE is applicable only to data files. NONTRUNCATE doesn't affect the log file. =&gt; should be NOTRUNCATE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87349f50-5751-68c4-df29-90c1c7c151d9
* Version Independent ID: bb82dc63-23ec-eda3-0200-88c4748e050a
* Content: [DBCC SHRINKDATABASE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-shrinkdatabase-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/database-console-commands/dbcc-shrinkdatabase-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/database-console-commands/dbcc-shrinkdatabase-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **umajay**

**Comment by msebolt** [comment]
@elbertlumenier Thank you for the feedback.

The change has been made.
