### ISSUE TITLE
On using multiple versions of SQLCMD

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#2509]
1. I don't like that this page does not list which versions of SQL it pertains to, and instead had a link to the same command for prior to SQL2014.
2. I don't like that I can't tell which specific version of SQLCMD will be downloaded when I click on the download link.
3. I don't like the fact that I cannot easily tell by running the latest installation for SQLCMD that I am unable to determine where it was installed.
4. I don't like that there is no reference on this page on how to run a specific version of SQLCMD - especially referencing the one that was supposedly downloaded from this same page.

I like the fact that SQLCMD was updated to include new Azure features, but without telling me *how* to run this new version instead of any older SQLCMD versions already installed it is of little value.  The SQLCMD I currently have launching (v15.0.1300.359) matches the text on the page, but doesn't list the new Azure features when the [-?] command is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da1f57b-a8fd-cca7-4cf0-9d594d365062
* Version Independent ID: 60c46780-6a03-7958-c77a-e7c94e3b9e85
* Content: [sqlcmd Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-2017)
* Content Source: [docs/tools/sqlcmd-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlcmd-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@LindaLF  Our apologies for the delay.  This has been assigned to the author.

**Comment by markingmyname** [comment]
Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

In the meantime, can you please visit [UserVoice](https://feedback.azure.com/forums/908035-sql-server) to submit your issue?

**Comment by markingmyname** [comment]
Hi, @LindaLF,

I apologize for the delay, but I have heard back, and here are the results.

1. I ’don’t like that this page does not list which versions of SQL it pertains to, and instead had a link to the same command for before SQL2014.

[A] From what we can gather, you are requesting a documentation suggestion. The page links to the latest version of tools whereas ’you’re looking for wants a list of all versions in the same place. However, if I understand you correctly, Microsoft docs only focus on updating SQL articles that are 2016 and later now.  If you feel that the Utility page should encompass all past and present versions, please let me know, and I can discuss this with my team.

2. I ’don’t like that I ’can’t tell which specific version of SQLCMD will be downloaded when I click on the download link.

[A] The tools version might not map to SQL Engine version 1:1 but the link in the article mentions the tools version it is downloading. Tools version increments depend on the features added for that tool. It will work against multiple SQL versions; hence the 1:1 might not make sense.

3. I ’don’t like the fact that I cannot quickly tell by running the latest installation for SQLCMD that I am unable to determine where it was installed.

[A] We are discussing opening a bug for that for later releases. For now, I would suggest the trying “where SQLCMD” command from a cmd prompt.

4. I ’don’t like that there is no reference on this page on how to run a specific version of SQLCMD - especially referencing the one that was supposedly downloaded from this same page.

[A] The primary content for how to start of sqlcmd remains similar across versions (ref: https://docs.microsoft.com/en-us/sql/ssms/scripting/sqlcmd-start-the-utility?view=sql-server-2017). For options/features available for different versions, please check the section “Command Line Options” (ref: https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-2017#command-line-options).

I hope this helps.

Please let me know if there is anything else.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
