### ISSUE TITLE
Lacking closing parentheses

### ISSUE THREAD

**Issue by iamjakkie** [MicrosoftDocs/sql-docs#2511]
Hello, 

in code example 'CONTAINS(column_name, 'NEAR((A,AA),2, TRUE')  ' there is a lacking parentheses after 'TRUE'. 

Best wishes,
Jakub

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a763c6f-f4f6-2bbe-841a-46f8afd25e8b
* Version Independent ID: 7c12c524-fe1a-9327-30c3-c9cb55037892
* Content: [Search for Words Close to Another Word with NEAR - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/search/search-for-words-close-to-another-word-with-near?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/search/search-for-words-close-to-another-word-with-near.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/search/search-for-words-close-to-another-word-with-near.md)
* Product: **sql**
* Technology: **search**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by WilliamAntonRohm** [comment]
@iamjakkie -- Jakub, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by iamjakkie** [comment]
Hey @WilliamAntonRohm,
I suppose the change is live now, it should be CONTAINS(column_name, 'NEAR((A,AA),2, TRUE)') (so the parenthesis is before apostrophe).

If I am wrong and the change is not live yet then please ignore this comment.

Thanks,
Jakub

**Comment by WilliamAntonRohm** [comment]
@iamjakkie -- thank you again for your keen eye -- I have fixed that!
