### ISSUE TITLE
Issue with the logic of finding different between dates logic

### ISSUE THREAD

**Issue by pvmraghunandan** [MicrosoftDocs/sql-docs#2512]
For the logic in the Section finding-difference-between-startdate-and-enddate-as-date-parts-strings,

Let's consider below input

SET @date1 = '2019-11-29 00:00:00.000'
SET @date2 = '2020-01-31 00:00:00.000'

The output is showing as 2 Months 1 Day instead of 2 Months 2 Days. Also Output is 2 Months 1 Day for 

SET @date1 = '2019-11-29 00:00:00.000'
SET @date2 = '2020-01-30 00:00:00.000'

Scenario get's interesting for Leap year

SET @date1 = '2019-11-29 00:00:00.000'
SET @date2 = '2020-03-01 00:00:00.000'

The Expected Output is "3 Months 1 Days" but the output is "3 Months 2 Days"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340056a9-0593-4289-7b72-601ae718b05f
* Version Independent ID: 1db8e288-8068-be96-b2f2-c8a2fe5a857a
* Content: [DATEDIFF (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql?view=sql-server-2017#i-finding-difference-between-startdate-and-enddate-as-date-parts-strings)
* Content Source: [docs/t-sql/functions/datediff-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/datediff-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@pvmraghunandan Thank you for the feedback!

The sample you describe appears to be removing the year data, before calculating months, days, etc. and that is what is causing the discrepancy.  

I will add a note to the sample addressing the concern and mention the author for future update.

FYI @MikeRayMSFT

**Comment by msebolt** [comment]
#please-close

**Comment by pvmraghunandan** [comment]
@msebolt Thanks for the update. Is the logic going to be fixed?
