### ISSUE TITLE
Documentation for cascaded delete

### ISSUE THREAD

**Issue by dallen66** [MicrosoftDocs/sql-docs#2516]
I know its a new feature but are there an documentation on cascaded delete,
it was introduce in CTP 2.3.

Below is the release statement.
Extending this feature further, you can define cascaded delete actions on an edge constraint. You can define the actions that the database engine takes when a user deletes the node(s), that a given edge connects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0840e04-b52d-2c5f-197d-26bec998fcaa
* Version Independent ID: 40ca3965-4f80-cbb3-839c-3244a536675e
* Content: [Graph edge constraints - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/graph-edge-constraints?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/tables/graph-edge-constraints.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/graph-edge-constraints.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @shkale-msft
* Microsoft Alias: **shkale**

**Comment by WilliamAntonRohm** [comment]
@shkale-msft -- please look into this feedback.

cc: @stevestein @markingmyname

**Comment by stevestein** [comment]
@dallen66 - Thanks for the feedback!

@shkale-msft - Hi Shreya, is there any information we can provide here? Anything we need to add to the doc?

Thanks!

**Comment by WilliamAntonRohm** [comment]
@shkale-msft -- Shreya, please process this aging issue 2516.

**Comment by stevestein** [comment]
@dallen66 - Thanks again for the feedback. Documentation will be updated with additional information. If there's a specific question or clarification we could address prior to the docs getting updated feel free to provide additional comments.

Thanks.

**Comment by shkale-msft** [comment]
Documentation has been updated. Thanks!
