### ISSUE TITLE
-P option not working or no longer available

### ISSUE THREAD

**Issue by Corendiel** [MicrosoftDocs/sql-docs#2528]
[-P password]
Password when connecting with 'SQL Authentication' or 'Active Directory - Password'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 179d9df0-cfc8-d9f2-babc-e9b7d0732d87
* Version Independent ID: c458bccb-8bba-f94c-658c-5d35eab7cdc7
* Content: [Ssms Utility - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/ssms-utility?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/ssms-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/ssms-utility.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@Corendiel Thank you for the feedback.

What version of SSMS are you using?  

The removal of the -P option is listed as part of the features list for version 18 (see [SSMS 18 Release Notes](https://cloudblogs.microsoft.com/sqlserver/2019/04/24/sql-server-management-studio-ssms-18-0-released-for-general-availability/)).

**Comment by Corendiel** [comment]
Hi Matt,

I'm using the most recent version of SSMS. Thanks for pointing out the
Release Notes with the reason of that change. However, I still believe this
page need to be updated. The -P option is still referenced and mentioned in
relation to other options. Lot of the features are no longer working
properly with a guarantied failed authentication.

I don't know if you have a diferent version of that page depending on the
version of SSMS or if a deprecated tag should be added to the page.

**Comment by msebolt** [comment]
Hi Yann,

Sounds good, I'll assign to the author for an update on how/when the article will be changed to reflect this issue.

**Comment by msebolt** [comment]
@markingmyname Any guidance on how documentation is updated to reflect GA releases?

**Comment by markingmyname** [comment]
@Corendiel,

I am not quite sure what the ask is.  Are you saying that the "-P" no longer works with newer versions of SSMS, such as 18.x?  

Thank you.

**Comment by markingmyname** [comment]
@Corendiel,

-P is now gone (for security reasons). 

We will update the documentation ASAP.

The changes should be live by the end of this week.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by jballe** [comment]
@markingmyname, I agree that it is not ok security wise to specify passwords as clear text command line options.
However, I would really like to have a way to inject the password from my password manager. For Remote Desktop we can use cmdkey, are there any kind of similar options available? I don't see anything related to that in the docs
