### ISSUE TITLE
Codesnippet not shown

### ISSUE THREAD

**Issue by zrhpwr** [MicrosoftDocs/sql-docs#2529]
The codesnipped below the section "To modify an index" is not shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c5faa8-7453-9431-7aaf-d5df162f4635
* Version Independent ID: a5c6cef3-c5b8-9ad7-c10c-3f0e5d067d1b
* Content: [Modify an Index - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/modify-an-index?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/indexes/modify-an-index.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/modify-an-index.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@zrhpwr Thank you for the feedback.

The change has been made.
