### ISSUE TITLE
Error "External data sources are not supported with type GENERIC"

### ISSUE THREAD

**Issue by mco100** [MicrosoftDocs/sql-docs#2530]
Hi,
I get above error msg with this t-SQL statement :
CREATE EXTERNAL DATA SOURCE My1stDataSource WITH (LOCATION = 'sqlserver://xxx:1433',CREDENTIAL = SQLServerCredentials); 
Master key + Credentials created successfully....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23b43af9-7da3-819b-d4f6-0e39f24f5f75
* Version Independent ID: d9e6987c-2648-2f18-424c-2f482c9226e8
* Content: [Configure PolyBase to access external data in SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-configure-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/polybase/polybase-configure-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-sql-server.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @abiola
* Microsoft Alias: **aboke**

**Comment by mco100** [comment]
fixed issue by running below command
exec sp_configure @configname = 'polybase enabled', @configvalue = 1;
RECONFIGURE WITH OVERRIDE   ;

**Comment by msebolt** [comment]
@mco100 Thank you for the feedback.

Your fix is located in the [PolyBase installation](https://docs.microsoft.com/sql/relational-databases/polybase/polybase-installation?view=sql-server-ver15#enable) article, so to clarify I updated the **Prerequisites** section.
