### ISSUE TITLE
Incorrect "Applies To"

### ISSUE THREAD

**Issue by kfeit** [MicrosoftDocs/sql-docs#2531]
The content on this page actually applies to SQL Server, but it is tagged as Azure SQL Database.  
Please also add a section on rotating keys for SQL Server TDE encrypted databases using Azure Key Vault.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 561a78d9-5662-287c-2599-a36b2102b8d5
* Version Independent ID: 9820cfde-5caa-1a7f-cdb5-06df907b7395
* Content: [Use SQL Server Connector with SQL Encryption Features - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/use-sql-server-connector-with-sql-encryption-features?view=azuresqldb-current&viewFallbackFrom=sql-server-2017)
* Content Source: [docs/relational-databases/security/encryption/use-sql-server-connector-with-sql-encryption-features.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/use-sql-server-connector-with-sql-encryption-features.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @aliceku
* Microsoft Alias: **aliceku**

**Comment by aliceku** [comment]
@VanMSFT, can you help to fix the moniker, this is wrong and was added in error:  monikerRange: "= azuresqldb-current || = sqlallproducts-allversions"

**Comment by VanMSFT** [comment]
@aliceku - Hey Alice! I fixed the moniker and the **Applies to**. Monikers are not needed in this instance.

I'm assigning this issue back to you for any comments or closure. Thanks!

https://github.com/MicrosoftDocs/sql-docs-pr/pull/11100

**Comment by WilliamAntonRohm** [comment]
@kfeit -- Thank you for your feedback.  We have updated the documentation and it should be live by tomorrow.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
