### ISSUE TITLE
Bad link in Always Encrypted enclave docs

### ISSUE THREAD

**Issue by jzabroski** [MicrosoftDocs/sql-docs#2533]
https://docs.microsoft.com/en-us/windows/desktop/seccrypto/managing-certificates-with-certificate-stores/ 404 - does not exist

in https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/configure-always-encrypted-enclaves.md

**Comment by msebolt** [comment]
@jzabroski Thank you for the feedback.

The article has been updated.
