### ISSUE TITLE
Formatting symbols appear in the document.

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/sql-docs#2534]
For example, “\*@variable\*” and lots of “\*\*.\*\*WRITE”. I.e., the asterisk appears to show up in the document in places where it was meant to be transformed using the markdown parser but appears in the webpage as asterisks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc5aa35c-e2c9-1cce-0026-6aae93b30504
* Version Independent ID: 85e9daaa-2af1-95c6-8795-75976c36ccba
* Content: [UPDATE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/queries/update-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/update-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by binki** [comment]
Some examples as seen in my browser:

![image](https://user-images.githubusercontent.com/82626/61319840-1d6c7d80-a7d6-11e9-9cc7-1aac8fb52e21.png)
![image](https://user-images.githubusercontent.com/82626/61319845-23faf500-a7d6-11e9-962d-a2e16701b7e1.png)
![image](https://user-images.githubusercontent.com/82626/61319847-29f0d600-a7d6-11e9-9982-ecfd757c47f5.png)

**Comment by msebolt** [comment]
@binki  Thank you for the feedback.

The changes have been made to the documentation.

**Comment by binki** [comment]
It looks like the change that was supposed to fix this issue is https://github.com/MicrosoftDocs/sql-docs/commit/a5c1cbc5de1bace3d7e2bacc4741316c2e2b645c .

**Comment by binki** [comment]
Looks like https://github.com/MicrosoftDocs/sql-docs/commit/a5c1cbc5de1bace3d7e2bacc4741316c2e2b645c#diff-0585c664f631888e05e75fcf5db2b809 was also related.

**Comment by binki** [comment]
Looks like https://github.com/MicrosoftDocs/sql-docs/commit/0efdce4371aa69602502b10ea09f66e1e72a19aa is also related
