### ISSUE TITLE
Default Policy Location Error

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#2535]
The sentence "By default, these policies are not installed on the SQL Server Database Engine, but they can be imported from the default location of C:\Program Files\Microsoft SQL Server###\Tools\Policies\DatabaseEngine\1033 or C:\Program Files (x86)\Microsoft SQL Server###\Tools\Policies\DatabaseEngine\1033 on 64-bit installs." appears to list the wrong location for default policies.  I have SQL2012 through SQL2017 installed, and there is no folder [Microsoft SQL Server ###] under either [C:\Program Files] or [C:\Program Files (x86)}.  The folder structure is C:\Program Files%\Microsoft SQL Server\###\Tools, and I have yet to find the [Policies] folder mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 441e7c77-826e-ab4d-78b0-93262499a3ad
* Version Independent ID: d4056db3-35a2-9844-499a-c2ddaa7d542b
* Content: [Import a Policy-Based Management Policy - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/import-a-policy-based-management-policy?view=sql-server-2017)
* Content Source: [docs/relational-databases/policy-based-management/import-a-policy-based-management-policy.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/policy-based-management/import-a-policy-based-management-policy.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@LindaLF Thank you for the feedback.

I think the article meant to use:
`C:\Program Files (x86)\Microsoft SQL Server\###\Tools\Policies\DatabaseEngine\1033`

Are you able to locate the `Tools` folder?

I have SQL Server 2017 running with policies located here:
`C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Policies\DatabaseEngine\1033`

...though note the policies could be in any version's folder path as I also found a `150` folder with no Policies content.
