### ISSUE TITLE
Version Requirement

### ISSUE THREAD

**Issue by sam-s4s** [MicrosoftDocs/sql-docs#2539]
How are you supposed to know which versions of SQL Server things are supported in, if the pages don't tell you?

ie. I have a minimum requirement of 2008 R2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a29ea4d1-a927-9870-e19e-4e82a8078099
* Version Independent ID: ff446beb-d8ce-21b4-f6ab-cf5980b2df25
* Content: [~ (Bitwise NOT) (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/bitwise-not-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/language-elements/bitwise-not-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/bitwise-not-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@sam-s4s Please take a look a the [previous versions](https://docs.microsoft.com/en-us/sql/toc/previous-versions-sql-server?view=sql-server-2017) article for links to previous version documentation.

**Comment by sam-s4s** [comment]
Hmmm, I thought I remembered a past version of the docs listing the version that the feature was available in. Seems like something that should be present, for example...

TRIM (SQL Server 2017)

But the docs don't mention which versions things are in at all, which seems like a pretty big omission! Then we have to go hunting to old docco. And even the version selector (top-right) is broken, and when you select an older version, it always tell you "The requested page is not available for SQL Server 2014. You have been redirected to the newest product version this page is available for." even for features that existed then (RTRIM, for example).

It just leaves us in a situation where it's a real drag to try to figure out which version things are available in.

Hope I'm making sense :)

**Comment by binki** [comment]
I also find the version selector confusing. When I select Older Versions, it just gives the generic message. It doesn’t tell you, for example, the first version that the document is available for.

Also, some features are introduced in one version and then changed slightly in later versions. I want to be able to have a quick summary on each page telling me when I can use the feature and what gotchas there are in the earlier versions. Like the compat grids on MDN or caniuse.

Thanks!

P.S., For my, case I was looking at `THROW` which is relatively new (not in 2008 R2 but in 2012).

**Comment by rothja** [comment]
@sam-s4s @binki Thanks for the feedback. I am the manager of the SQL Server documentation team. I apologize that you're not finding the information you are looking for about versioning and applies-to. We could definitely do a better job of making this information more clear. In some articles, we have a note on certain parts of the reference saying "Applies to 2014 and higher" or something similar to that to show when certain features are introduced. On others this "Starting with 2014" appears in the applies to line at the top. In many cases, like the article on this git issue, we did not catalog when the feature appeared in the past, so the article does not explain the versioning story in detail. I know that is a problem, and I'll talk to the SQL Server documentation team about this challenge for the many reference articles that don't supply versioning info.

At this time, I don't have a way to fix this across the board, but I do appreciate your feedback and I commit to looking at this with my team. I'm going to close the git issue now, but please feel free to add any additional thoughts/ideas in the comment thread. Thank you!
