### ISSUE TITLE
Improve decimal precision with cast

### ISSUE THREAD

**Issue by wangyum** [MicrosoftDocs/sql-docs#2540]
For the following case:
```sql
CAST(decimal(p1, s1) * decimal(p2, s2) AS DECIMAL(p3, s3))
```

Could we optimize the `decimal(p1, s1) * decimal(p2, s2)`'s result type to `DECIMAL(p3, s3)` and remove `CAST`? This can improve performance and  precision.

Example:
```sql
select cast(cast(-34338492.215397047 as decimal(38, 18)) *  cast(-34338492.215397047 as decimal(38, 18)) as decimal(38, 18));
```
The result type of `cast(-34338492.215397047 as decimal(38, 18)) *  cast(-34338492.215397047 as decimal(38, 18))`  is `decimal(38, 6)`:
```sql
1> select SQL_VARIANT_PROPERTY(c1, 'BaseType'), SQL_VARIANT_PROPERTY(c1, 'Precision'), SQL_VARIANT_PROPERTY(c1, 'Scale') from (select cast(-34338492.215397047 as decimal(38, 18)) *  cast(-34338492.215397047 as decimal(38, 18)) as c1) t;
2> go

---------- ---------- ----------
decimal    38         6

(1 rows affected)
```
Then cast the result from `decimal(38, 6`) to `decimal(38, 18)`:
```sql
1> select cast(cast(-34338492.215397047 as decimal(38, 18)) *  cast(-34338492.215397047 as decimal(38, 18)) as decimal(38, 18));
2> go

----------------------------------------
     1179132047626883.596862000000000000

(1 rows affected)
```

Related ticket([SPARK-28348](https://issues.apache.org/jira/browse/SPARK-28348)) and benchmark:
```
[info] Java HotSpot(TM) 64-Bit Server VM 1.8.0_211-b12 on Linux 3.10.0-957.1.3.el7.x86_64
[info] Intel Core Processor (Broadwell)
[info] Benchmark SPARK-28348:                    Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
[info] ------------------------------------------------------------------------------------------------------------------------
[info] Without this optimize                       8870           9753         560          0.5        2217.5       1.0X
[info] With this optimize                          6212           7220         608          0.6        1553.0       1.4X
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90d3d3f1-b730-f53d-e009-71a01f794d2e
* Version Independent ID: 1bc1b5fb-4e66-2890-70ff-9b4392b77548
* Content: [Precision, scale, and length (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/precision-scale-and-length-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/data-types/precision-scale-and-length-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/precision-scale-and-length-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
@wangyum  - thank you for raising this issue. If you'd like, you can submit a pull request to update the article. To submit the pull request, please click edit on the article. We will review the update with our engineering group.
