### ISSUE TITLE
installation of kubeadm and kubelet are failing with : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed

### ISSUE THREAD

**Issue by rl-msft** [MicrosoftDocs/sql-docs#2541]
when following Step 4  and executing this command

KUBE_DPKG_VERSION=1.11.3-00
sudo apt-get update && /
sudo apt-get install -y ebtables ethtool && /
sudo apt-get install -y docker.io && /
sudo apt-get install -y apt-transport-https && /
sudo apt-get install -y kubelet=$KUBE_DPKG_VERSION kubeadm=$KUBE_DPKG_VERSION kubectl=$KUBE_DPKG_VERSION && /
curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash

this is failing with 

administrator@ubuntu1:~$ KUBE_DPKG_VERSION=1.11.3-00
administrator@ubuntu1:~$ sudo apt-get install -y kubelet=$KUBE_DPKG_VERSION kubeadm=$KUBE_DPKG_VERSION kubectl=$KUBE_DPKG_VERSION
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubeadm : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed
 kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed
E: Unable to correct problems, you have held broken packages.

seems dependency issue for that specific version 1.11.3-00

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8bb827-4819-7b2d-490a-071f6b7b57a2
* Version Independent ID: 65b90b91-5946-b2d1-b97a-537bc9b014ca
* Content: [Configure Kubernetes with kubeadm - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-with-kubeadm?view=sqlallproducts-allversions)
* Content Source: [docs/big-data-cluster/deploy-with-kubeadm.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-with-kubeadm.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rl-msft** [comment]
looking at https://github.com/microsoft/sql-server-samples/blob/master/samples/features/sql-big-data-cluster/deployment/kubeadm/ubuntu/setup-k8s-prereqs.sh see we are asking for higher version :

UBE_DPKG_VERSION=1.15.0-00
apt-get update
apt-get install -y ebtables ethtool
apt-get install -y docker.io
apt-get install -y apt-transport-https
apt-get install -y kubelet=$KUBE_DPKG_VERSION kubeadm=$KUBE_DPKG_VERSION kubectl=$KUBE_DPKG_VERSION
curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash

so we may just need to update the article and adjust the script in step 4
4. Configure docker and Kubernetes prerequisites on the machine.

**Comment by MikeRayMSFT** [comment]
@rl-msft thanks for the issue. We've submitted an update to the article.
