### ISSUE TITLE
Windows Server 2019

### ISSUE THREAD

**Issue by Loves2Code** [MicrosoftDocs/sql-docs#2542]
Windows Server 2019 is NOT listed as a "Supported Operating System."
I'm assuming it should be listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017#feedback)
* Content Source: [docs/azure-data-studio/download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@Loves2Code, 

Thanks for bringing this to our attention.

Expect the article to be updated early next week.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
