### ISSUE TITLE
The behavior of FOR XML AUTO is different when compatibility level is less then 90 

### ISSUE THREAD

**Issue by sqlenders** [MicrosoftDocs/sql-docs#2544]
The behavior of FOR XML AUTO is different when compatibility level is less then 90 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 252ab2db-6a09-17d5-b082-c369f06028ec
* Version Independent ID: 3e6521e3-565a-9a30-b17d-49254c22569d
* Content: [Use AUTO Mode with FOR XML - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/xml/use-auto-mode-with-for-xml?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/xml/use-auto-mode-with-for-xml.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/xml/use-auto-mode-with-for-xml.md)
* Product: **sql**
* Technology: **xml**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
@sqlenders Your statement is probably correct. Yet the particular article. "Use AUTO Mode with FOR XML", only claims to cover SQL Server versions 2016 and later (at least through SQL Server 2019). Compatibility Level 90 refers to SQL Server 2005 (I think), and the effect of Compat 90 on AUTO is covered in documentation between 2008-2014 (inclusive). At some point it becomes necessary to remove history from the latest articles.

I am now closing this Issue 2544. 
Thank you for submitting this Issue. We hope to hear from you again.

P.S. Info/link about Compatibility Levels:

- [https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-compatibility-level?view=sql-server-2016](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-compatibility-level?view=sql-server-2016)

 . .
