### ISSUE TITLE
The "Microsoft Knowledge Base article 329204" doesn't exist

### ISSUE THREAD

**Issue by freemanjr** [MicrosoftDocs/sql-docs#2545]
The link behind "Microsoft Knowledge Base article 329204" does not exist.

https://go.microsoft.com/fwlink/?linkid=117786

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a7dcdd-802d-d1c8-ddde-4a06d553bfc4
* Version Independent ID: 6cf27ff6-23be-179d-479a-fca388049ed4
* Content: [Set the Max Degree of Parallelism Option for Optimal Performance - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/set-the-max-degree-of-parallelism-option-for-optimal-performance?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/policy-based-management/set-the-max-degree-of-parallelism-option-for-optimal-performance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/policy-based-management/set-the-max-degree-of-parallelism-option-for-optimal-performance.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
@freemanjr - Hi Jonathan! Thank you for letting us know! We appreciate your contribution on helping us with the documentation. I have updated the link, and it should go live tomorrow. If there are any questions, please feel free to let us know. I'll go ahead and close this issue for now.

https://github.com/MicrosoftDocs/sql-docs-pr/pull/11101
