### ISSUE TITLE
RSS Feed?

### ISSUE THREAD

**Issue by cconrado** [MicrosoftDocs/sql-docs#2546]
Is there a rss feed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by msebolt** [comment]
@cconrado Thank you for the question.

You can use RSS feeds in Microsoft Docs search, just search for the article or general topic using the **Search** bar and select **RSS** in the top right corner.

See the feature's [Twitter post](https://twitter.com/docsmsft/status/914964358601625605?lang=en).

**Comment by msebolt** [comment]
@cconrado  I don't see an RSS feed readily available for the SSMS downloads.

@markingmyname Customers may be interested in an RSS feed for newly available downloads of SSMS.

**Comment by msebolt** [comment]
The alternative in the meantime is to watch for article updates with:

`https://docs.microsoft.com/api/search/rss?search=%22Download+SQL+Server+Management+Studio+%28SSMS%29%22&locale=en-us&%24filter=scopes%2Fany%28t%3A+t+eq+%27sql%27%29`

The search returns multiple results so you would need a way to only watch the first result.
