### ISSUE TITLE
What is a "blank"?

### ISSUE THREAD

**Issue by sam-s4s** [MicrosoftDocs/sql-docs#2548]
You state: "LEN excludes trailing blanks"... but what is a blank defined as? Just a CHAR(32)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ff0d040-6a32-aa7f-0b6e-91a392a1e4e0
* Version Independent ID: 5560f1d4-948f-e5de-738b-5950000505a1
* Content: [LEN (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/len-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/len-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/len-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@sam-s4s Thank you for the feedback.

Blanks are generally defined as spaces and tabs.

Since the **LEN** function registers tabs in the count I've updated the article to specify space.

**Comment by sam-s4s** [comment]
Perfect, thank you :)
