### ISSUE TITLE
Suggestion to add a version restriction tip to the working-with-kpis-in-reporting-services page

### ISSUE THREAD

**Issue by unlucky-cat** [MicrosoftDocs/sql-docs#2550]
It should be worth mentioning that KPI feature is accessible only in Enterprise (Developer) editions of the SSRS portal. 

I personally tried and failed to find out why I cant see the KPI option in the SSRS portal menu and it could save me some time if there was for example a tip that this feature is only available in the Enterprise edition

**Comment by msebolt** [comment]
@unlucky-cat Thank you for the feedback.

A note has been added to the article.
