### ISSUE TITLE
Requires refresh for SQL Server Box

### ISSUE THREAD

**Issue by Guillaume-Fourrat** [MicrosoftDocs/sql-docs#2551]
* Should specify SQL2019 / vNext as minimum version for Server (the metadata is included in header, which will make the page content unavailable if SQL 2017 or older is selected, but this information doesn't actually appear on the doc itself).
* Description of resultset not in line with 2019 CTP3 : some columns are missing from docs (eg checksum), some columns are documented and don't exist (eg torn_bits), many column names are slightly different (reserved_bytes_by_xdes_id).
* Default Column Order is incorrect (see output of "select * from sys.all_columns where object_id = object_id('sys.dm_db_page_info') order by column_id"  for ref ).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4985596b-165d-0200-4cac-9d726687fd9b
* Version Independent ID: 7f207f17-62c9-775d-902f-e692b5116dc3
* Content: [sys.dm_db_page_info (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-page-info-transact-sql?view=sqlallproducts-allversions)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-db-page-info-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-db-page-info-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @bluefooted
* Microsoft Alias: **pamela**

**Comment by WilliamAntonRohm** [comment]
@Guillaume-Fourrat -- thank you for your feedback.

@bluefooted -- please look at my new PR https://github.com/MicrosoftDocs/sql-docs-pr/pull/11384 and verify the updates.

**Comment by bluefooted** [comment]
Thanks @Guillaume-Fourrat and @WilliamAntonRohm ! [Latest PR](https://github.com/MicrosoftDocs/sql-docs-pr/pull/11417) just merged into master. The columns changed again in CTP 3.2 to reflect changes in ADR, I've updated this based on the latest version. I expect there may be more changes before RTM, will try to check in again when it gets closer.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
