### ISSUE TITLE
There is a problem with the docker startup command.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#2553]
Hi team, 
I'm copying this from here: https://github.com/MicrosoftDocs/sql-docs.zh-tw/issues/112
since the sure is making a suggestion on the code example

@f22520779 commented 13 hours ago 
(Translated)
Docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=&lt;YourStrong!Passw0rd&gt;' ...

Should be docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=YourStrong!Passw0rd" ...

Single quotes are wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Get started with SQL Server Linux containers on Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash#feedback)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by msebolt** [comment]
@CeciAc The changes have been made.
