### ISSUE TITLE
Incorrect formatting at end of Part II

### ISSUE THREAD

**Issue by kfeit** [MicrosoftDocs/sql-docs#2554]
The formatting of the text after "Important" at the end of Part II appears to be incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4997f245-c966-51a3-34c7-705c3cfbd4b0
* Version Independent ID: 129fbe40-3b02-f2c1-ef13-b42d86ffdb77
* Content: [SQL Server TDE Extensible Key Management Using Azure Key Vault - Setup Steps - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-2017)
* Content Source: [docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @aliceku
* Microsoft Alias: **aliceku**

**Comment by msebolt** [comment]
@kfeit  Thank you for the feedback.

The change has been made.
