### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by RachelAmbler** [MicrosoftDocs/sql-docs#2558]
Permission type XU (Unsafe Assembly) is missing for starters. Unsure if any other permission type is also not documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d84ff1d-3f92-6ac7-662c-c4f25a2fff8b
* Version Independent ID: fa9a8131-2155-644a-9474-94b749b2fd0e
* Content: [sys.server_permissions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-server-permissions-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-catalog-views/sys-server-permissions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-server-permissions-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by Mitch-Wheat** [comment]
Permission type IAL (IMPERSONAT ANY LOGIN) is also missing

**Comment by VanMSFT** [comment]
Table has been updated and should go live in a few hours. Thank you for your feedback! We really appreciate your help on updating our documentation.

https://github.com/MicrosoftDocs/sql-docs-pr/pull/12119

#please-close
