### ISSUE TITLE
Deferred Name Resolution

### ISSUE THREAD

**Issue by JediSQL** [MicrosoftDocs/sql-docs#2560]
This page should have content-about/link-to Deferred Name Resolution information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c31cc40b-000d-cfc3-4e59-7d829ea1b488
* Version Independent ID: e5c40e50-8ca3-f0bd-8f29-f3e8f566a0f3
* Content: [Stored Procedures (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/stored-procedures-database-engine?view=sql-server-2017)
* Content Source: [docs/relational-databases/stored-procedures/stored-procedures-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/stored-procedures/stored-procedures-database-engine.md)
* Product: **sql**
* Technology: **stored-procedures**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@JediSQL - Thanks for opening this issue! A link was added to the related info section that points to a short explanation of what deferred name resolution is. The link should appear within the next day or so.

I'm not sure which version of SQL you're using but there's an archived article here: https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms190686(v=sql.105)

**Comment by stevestein** [comment]
@JediSQL - We're going to go ahead and close this issue. Feel free to reach out if you have a specific question or ongoing issue related to this.

Thanks
