### ISSUE TITLE
Italics missing from one parameter in Syntax section

### ISSUE THREAD

**Issue by tom-boardman** [MicrosoftDocs/sql-docs#2562]
In the Syntax section, the word 'role' should be in italics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 416c8b0e-11c0-dea7-fcbf-8b893a1bf41c
* Version Independent ID: 613a1373-016f-ece2-0843-2acc80d48d4c
* Content: [sp_helpdbfixedrole (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-helpdbfixedrole-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-helpdbfixedrole-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-helpdbfixedrole-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@tom-boardman -- Tom, thank you for your feedback.  The italicization in that article is the same as its sibling articles, so I'm going to leave it as-is.
