### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by kevchant** [MicrosoftDocs/sql-docs#2563]
Just to check, are we still covered by Microsoft support if we use this method to change server collation here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca70403-237f-0160-7d1f-5817e40b5d25
* Version Independent ID: 9993116a-bcec-e054-1cbe-82c3ad603ef6
* Content: [Set or Change the Server Collation - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-server-collation?view=sql-server-2016#feedback)
* Content Source: [docs/relational-databases/collations/set-or-change-the-server-collation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/set-or-change-the-server-collation.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@kevchant Hello, I cannot be sure about what thing specifically your message refers to when asking whether the thing is "covered" by MS support. Assuming the question does not involve improperly exported data, or improperly stored safe copies of all CREATE statements for table and procs etc, I see no change in MS support.

The documented process involves exporting your data before then dropping your databases.  Of course any loss of data would not involve MS support.  It is easy enough for the customer to test the reload of data before the customer drops his databases.

A precaution would be to ensure you have the source code for all CREATE statements for tables, indexes, foreign keys, stored procs etc. In many companies those can be generated any time from the temporary test server that has all the original databases, just in case. 

Suppose that a customer exports all data, then drop all databases, and then follows the steps to change the server collation - but something goes wrong. At worst, their was very little left for the customer to lose. Server-level logins could be lost. But basically the worst is the customer would have to reinstall SQL Server.  The customer would still have all his CREATE statements for tables, indexes, stored procs etc.
If the whole process first succeeded on a Test server, it should work the same on a Production server.

Thank you.
