### ISSUE TITLE
ambiguous and misleading definition of varchar size

### ISSUE THREAD

**Issue by deanveggy** [MicrosoftDocs/sql-docs#2564]
it states "varchar [ ( n | max ) ] Variable-length string data. n defines the string length in bytes and can be a value from 1 through 8,000". that was not telling me if n should be the minimum, average or max size of my intended data. i had to google blogs to get the much better definition, that n should be the column's constraint max size.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf421288-ba40-3904-72d1-07de1c69e211
* Version Independent ID: f388925a-a573-65ab-e0db-fe61245df123
* Content: [char and varchar (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/data-types/char-and-varchar-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/char-and-varchar-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@deanveggy Thank you for the feedback!  Your change has been made and merged.
