### ISSUE TITLE
SQL Server Agent - Schedule - One Time Run 

### ISSUE THREAD

**Issue by erdinccolak** [MicrosoftDocs/sql-docs#2567]
Hi

set one time run working no problem
 but reconfig one time run schedule not working.

**Sample:**

Create Job  Set 19.07.2019 19:40  -One Time Run
**<<<>>> RUN NO PROBLEM <<<>>>**
job complete then

Edit "One time Run" Set new time--> 20.07.2019 19:40
**<<<>>> NOT RUN <<<>>>**

**Comment by WilliamAntonRohm** [comment]
@erdinccolak Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
