### ISSUE TITLE
spins errors

### ISSUE THREAD

**Issue by fred339** [MicrosoftDocs/sql-docs#2568]
one would expect given code to  be error free.

PS C:\WINDOWS\system32&gt; import-Module "sqlps"
WARNING: The names of some imported commands from the module 'sqlps' include unapproved verbs t
hat might make them less discoverable. To find the commands with unapproved verbs, run the Impo
rt-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb
.

PS SQLSERVER:\&gt; import-Module "sqlps" -verbose
VERBOSE: Importing cmdlet 'Add-SqlAvailabilityDatabase'.
VERBOSE: Importing cmdlet 'Add-SqlAvailabilityGroupListenerStaticIp'.
VERBOSE: Importing cmdlet 'Backup-SqlDatabase'.
VERBOSE: Importing cmdlet 'Convert-UrnToPath'.
WARNING: The names of some imported commands from the module 'sqlps' include unapproved verbs t
hat might make them less discoverable. To find the commands with unapproved verbs, run the Impo
rt-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb
.
VERBOSE: The 'Decode-SqlName' command in the sqlps' module was imported, but because its name d
oes not include an approved verb, it might be difficult to find. For a list of approved verbs, 
type Get-Verb.
VERBOSE: Importing cmdlet 'Decode-SqlName'.
VERBOSE: Importing cmdlet 'Disable-SqlAlwaysOn'.
VERBOSE: Importing cmdlet 'Enable-SqlAlwaysOn'.
VERBOSE: The 'Encode-SqlName' command in the sqlps' module was imported, but because its name d
oes not include an approved verb, it might be difficult to find. For a list of approved verbs, 
type Get-Verb.
VERBOSE: Importing cmdlet 'Encode-SqlName'.
VERBOSE: Importing cmdlet 'Get-SqlCredential'.
VERBOSE: Importing cmdlet 'Invoke-PolicyEvaluation'.
VERBOSE: Importing cmdlet 'Invoke-Sqlcmd'.
VERBOSE: Importing cmdlet 'Join-SqlAvailabilityGroup'.
VERBOSE: Importing cmdlet 'New-SqlAvailabilityGroup'.
VERBOSE: Importing cmdlet 'New-SqlAvailabilityGroupListener'.
VERBOSE: Importing cmdlet 'New-SqlAvailabilityReplica'.
VERBOSE: Importing cmdlet 'New-SqlCredential'.
VERBOSE: Importing cmdlet 'New-SqlHADREndpoint'.
VERBOSE: Importing cmdlet 'Remove-SqlAvailabilityDatabase'.
VERBOSE: Importing cmdlet 'Remove-SqlAvailabilityGroup'.
VERBOSE: Importing cmdlet 'Remove-SqlAvailabilityReplica'.
VERBOSE: Importing cmdlet 'Remove-SqlCredential'.
VERBOSE: Importing cmdlet 'Restore-SqlDatabase'.
VERBOSE: Importing cmdlet 'Resume-SqlAvailabilityDatabase'.
VERBOSE: Importing cmdlet 'Set-SqlAvailabilityGroup'.
VERBOSE: Importing cmdlet 'Set-SqlAvailabilityGroupListener'.
VERBOSE: Importing cmdlet 'Set-SqlAvailabilityReplica'.
VERBOSE: Importing cmdlet 'Set-SqlCredential'.
VERBOSE: Importing cmdlet 'Set-SqlHADREndpoint'.
VERBOSE: Importing cmdlet 'Suspend-SqlAvailabilityDatabase'.
VERBOSE: Importing cmdlet 'Switch-SqlAvailabilityGroup'.
VERBOSE: Importing cmdlet 'Test-SqlAvailabilityGroup'.
VERBOSE: Importing cmdlet 'Test-SqlAvailabilityReplica'.
VERBOSE: Importing cmdlet 'Test-SqlDatabaseReplicaState'.
VERBOSE: Importing function 'SQLSERVER:'.
VERBOSE: Importing variable 'm'.

PS SQLSERVER:\&gt; $smo = 'Microsoft.SqlServer.Management.Smo.'  
$wmi = new-object ($smo + 'Wmi.ManagedComputer').  

# List the object properties, including the instance names.  
$Wmi  

# Enable the TCP protocol on the default instance.  
$uri = "ManagedComputer[@Name='" + (get-item env:\computername).Value + "']/ServerInstance[@Name='MSSQLSERVER']/ServerProtocol[@Name='Tcp']"
$Tcp = $wmi.GetSmoObject($uri)  
$Tcp.IsEnabled = $true  
$Tcp.Alter()  
$Tcp  

# Enable the named pipes protocol for the default instance.  
$uri = "ManagedComputer[@Name='" + (get-item env:\computername).Value + "']/ServerInstance[@Name='MSSQLSERVER']/ServerProtocol[@Name='Tcp']"
$Np = $wmi.GetSmoObject($uri)  
$Np.IsEnabled = $true  
$Np.Alter()  
$Np

ConnectionSettings : Microsoft.SqlServer.Management.Smo.Wmi.WmiConnectionInfo
Services           : {MSSQL$SQLEXPRESS, MSSQL$SQLEXPRESS01, SQLAgent$SQLEXPRESS, 
                     SQLAgent$SQLEXPRESS01...}
ClientProtocols    : {np, sm, tcp}
ServerInstances    : {SQLEXPRESS01}
ServerAliases      : {}
Urn                : ManagedComputer[@Name='LB_SIEM']
Name               : LB_SIEM
Properties         : {}
UserData           : 
State              : Existing

Exception calling "GetSmoObject" with "1" argument(s): "Attempt to retrieve data for object 
failed for ManagedComputer 'LB_SIEM'."
At line:9 char:1
+ $Tcp = $wmi.GetSmoObject($uri)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FailedOperationException
 
The property 'IsEnabled' cannot be found on this object. Verify that the property exists and 
can be set.
At line:10 char:1
+ $Tcp.IsEnabled = $true
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
You cannot call a method on a null-valued expression.
At line:11 char:1
+ $Tcp.Alter()
+ ~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Exception calling "GetSmoObject" with "1" argument(s): "Attempt to retrieve data for object 
failed for ManagedComputer 'LB_SIEM'."
At line:16 char:1
+ $Np = $wmi.GetSmoObject($uri)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FailedOperationException
 
The property 'IsEnabled' cannot be found on this object. Verify that the property exists and 
can be set.
At line:17 char:1
+ $Np.IsEnabled = $true
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
You cannot call a method on a null-valued expression.
At line:18 char:1
+ $Np.Alter()
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 

PS SQLSERVER:\&gt; $smo = 'Microsoft.SqlServer.Management.Smo.'  
$wmi = new-object ($smo + 'Wmi.ManagedComputer').  

# List the object properties, including the instance names.  
$Wmi  

# Enable the TCP protocol on the default instance.  
$uri = "ManagedComputer[@Name='LB_SIEM']/ ServerInstance[@Name='MSSQLSERVER']/ServerProtocol[@Name='Tcp']"  
$Tcp = $wmi.GetSmoObject($uri)  
$Tcp.IsEnabled = $true  
$Tcp.Alter()  
$Tcp  

# Enable the named pipes protocol for the default instance.  
$uri = "ManagedComputer[@Name='LB_SIEM']/ ServerInstance[@Name='MSSQLSERVER']/ServerProtocol[@Name='Np']"  
$Np = $wmi.GetSmoObject($uri)  
$Np.IsEnabled = $true  
$Np.Alter()  
$Np

ConnectionSettings : Microsoft.SqlServer.Management.Smo.Wmi.WmiConnectionInfo
Services           : {MSSQL$SQLEXPRESS, MSSQL$SQLEXPRESS01, SQLAgent$SQLEXPRESS, 
                     SQLAgent$SQLEXPRESS01...}
ClientProtocols    : {np, sm, tcp}
ServerInstances    : {SQLEXPRESS01}
ServerAliases      : {}
Urn                : ManagedComputer[@Name='LB_SIEM']
Name               : LB_SIEM
Properties         : {}
UserData           : 
State              : Existing

Exception calling "GetSmoObject" with "1" argument(s): "Attempt to retrieve data for object 
failed for ManagedComputer 'LB_SIEM'."
At line:9 char:1
+ $Tcp = $wmi.GetSmoObject($uri)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FailedOperationException
 
The property 'IsEnabled' cannot be found on this object. Verify that the property exists and 
can be set.
At line:10 char:1
+ $Tcp.IsEnabled = $true
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
You cannot call a method on a null-valued expression.
At line:11 char:1
+ $Tcp.Alter()
+ ~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Exception calling "GetSmoObject" with "1" argument(s): "Attempt to retrieve data for object 
failed for ManagedComputer 'LB_SIEM'."
At line:16 char:1
+ $Np = $wmi.GetSmoObject($uri)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FailedOperationException
 
The property 'IsEnabled' cannot be found on this object. Verify that the property exists and 
can be set.
At line:17 char:1
+ $Np.IsEnabled = $true
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
You cannot call a method on a null-valued expression.
At line:18 char:1
+ $Np.Alter()
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 

PS SQLSERVER:\&gt; $wmi

ConnectionSettings : Microsoft.SqlServer.Management.Smo.Wmi.WmiConnectionInfo
Services           : {MSSQL$SQLEXPRESS, MSSQL$SQLEXPRESS01, SQLAgent$SQLEXPRESS, 
                     SQLAgent$SQLEXPRESS01...}
ClientProtocols    : {np, sm, tcp}
ServerInstances    : {SQLEXPRESS01}
ServerAliases      : {}
Urn                : ManagedComputer[@Name='LB_SIEM']
Name               : LB_SIEM
Properties         : {}
UserData           : 
State              : Existing

PS SQLSERVER:\&gt; # Get a reference to the ManagedComputer class.  
CD SQLSERVER:\SQL\LB_SIEM  
$Wmi = (get-item .).ManagedComputer  
# Get a reference to the default instance of the Database Engine.  
$DfltInstance = $Wmi.Services['MSSQLSERVER']  
# Display the state of the service.  
$DfltInstance  
# Stop the service.  
$DfltInstance.Stop();  
# Wait until the service has time to stop.  
# Refresh the cache.  
$DfltInstance.Refresh();   
# Display the state of the service.  
$DfltInstance  
# Start the service again.  
$DfltInstance.Start();  
# Wait until the service has time to start.  
# Refresh the cache and display the state of the service.  
$DfltInstance.Refresh(); $DfltInstance
You cannot call a method on a null-valued expression.
At line:9 char:1
+ $DfltInstance.Stop();
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At line:12 char:1
+ $DfltInstance.Refresh();
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At line:16 char:1
+ $DfltInstance.Start();
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At line:19 char:1
+ $DfltInstance.Refresh(); $DfltInstance
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 

PS SQLSERVER:\SQL\LB_SIEM&gt; $wmi

ConnectionSettings : Microsoft.SqlServer.Management.Smo.Wmi.WmiConnectionInfo
Services           : {MSSQL$SQLEXPRESS, SQLAgent$SQLEXPRESS, SQLBrowser}
ClientProtocols    : {np, sm, tcp}
ServerInstances    : {SQLEXPRESS}
ServerAliases      : {}
Urn                : ManagedComputer[@Name='LB_SIEM']
Name               : LB_SIEM
Properties         : {}
UserData           : 
State              : Existing

PS SQLSERVER:\SQL\LB_SIEM&gt; 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e350b6-b39b-0a14-6637-06fbec7b171a
* Version Independent ID: f92e2065-c2d4-3e93-c136-de4da69d7586
* Content: [Enable or Disable a Server Network Protocol - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-or-disable-a-server-network-protocol?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/configure-windows/enable-or-disable-a-server-network-protocol.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/enable-or-disable-a-server-network-protocol.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@MikeRayMSFT Hi, when you return from vacation, can you please process this GutHub Issue, about PowerShell, 

```
Using SQL Server PowerShell

To Enable a Server Network Protocol Using PowerShell

1. Using administrator permissions open a command prompt.
2. Start Windows PowerShell from the taskbar, or click Start, then All Programs, then Accessories, then Windows PowerShell, then Windows PowerShell.
3. Import the sqlps module by entering Import-Module "sqlps"
```

&nbsp;

@stevestein Steve, you might know whether Step_3 above is out-of-date?  The customer is reporting that the following PowerShell command suffered lots of errors when he ran it:

- `Import-Module "sqlps";`

I get the following error:

```
Import-Module : The specified module 'sqlps' was not loaded because no valid module file was found in any module directory.
At line:5 char:1
+ Import-Module "sqlps";
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (sqlps:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by MikeRayMSFT** [comment]
@fred339 - I tested the scripts and they work. 

For complete details on importing sqlps, see [Install SQL Server PowerShell module](https://docs.microsoft.com/en-us/sql/powershell/download-sql-server-ps-module).
