### ISSUE TITLE
Looking for checksums

### ISSUE THREAD

**Issue by InteXX** [MicrosoftDocs/sql-docs#2569]
Are you able to publish hashes for these downloads, so we can validate accuracy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by MightyPen** [comment]
@dnethi Hi Dinakar, My understand is the answer is - _"No, we do not have checksums that we provide to the public, for SSMS setup.exe files."_
But please enter another Comment here if I am mistaken about that, or if there is more to day.

@InteXX With the above answer, and the opportunity for dnethi to tell us in case my answer is wrong (and use @ notifications in your new comment), I am now Closing this Issue 2569 as answered.
We hope to hear from you again.

CC: @Matteo-T

**Comment by InteXX** [comment]
OK...  _would_ you add checksums? They're pretty easy to create as part of your pipeline, as I'm sure you know.

**Comment by dnethi** [comment]
hi InteXX
SSMS is windows only client tool, and we publish signed binaries. So I dont see any reason to also provide the hash.

**Comment by InteXX** [comment]
Very well.
