### ISSUE TITLE
SSIS 2019 and Microsoft connector for Oracle (v5.0)

### ISSUE THREAD

**Issue by mco100** [MicrosoftDocs/sql-docs#2570]
After installation of SQL Server 2019 with SSIS service and SSDT, during installation of Microsoft connector for Oracle v5.0, there is an error message "Microsoft SQL Server is not installed. The English version of the Connector will be installed". Is there any planned update of this connector for SQL Server 2019 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48cb4a50-bcd6-38bc-187b-27cc36576219
* Version Independent ID: 38c1d92e-25d6-6237-9a04-6ca13bbb1a09
* Content: [What's new in SQL Server 2019 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-ver15?view=sqlallproducts-allversions#other-services)
* Content Source: [docs/sql-server/what-s-new-in-sql-server-ver15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/what-s-new-in-sql-server-ver15.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@mco100 Hello, This GitHub Issues website can help only with shortcoming of our documentation. Product bugs, or product release schedules, must be handled elsewhere. Perhaps one of the following links could be useful for this?:

- [Setup and Upgrade -  MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsetupandupgrade&filter=alltypes&sort=lastpostdesc)
- [Support options for business users](https://support.microsoft.com/gp/support-options-for-business)
- [Contact Microsoft](https://support.microsoft.com/gp/contactus81?Audience=Commercial)
- [All the ways to get help](https://docs.microsoft.com/sql/sql-server/sql-server-get-help)

I am now Closing this Issue 2570.
We hope to hear from you again.

The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.
