### ISSUE TITLE
Unclear

### ISSUE THREAD

**Issue by WannaKatana** [MicrosoftDocs/sql-docs#2571]
where did the 14 come from??  "COLUMNS_UPDATED() & 14"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52d12681-a6f1-258a-d25a-b47741883a88
* Version Independent ID: 72ad45a0-a3d2-1b62-d7c5-2237909d4f4a
* Content: [COLUMNS_UPDATED (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/columns-updated-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/columns-updated-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/columns-updated-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@wannakatana Hello Joel, The following snippet from the article explains how each column number is convert into part of the overall bit mask that can identify columns in a bitwise operation.

```
/* Check whether columns 2, 3 or 4 have been updated. If any or all  
columns 2, 3 or 4 have been changed, create an audit record. The
bitmask is: power(2, (2-1)) + power(2, (3-1)) + power(2, (4-1)) = 14. To test   
whether all columns 2, 3, and 4 are updated, use = 14 instead of > 0  
(below). */
```

- bitmask is: `power(2, (2-1)) + power(2, (3-1)) + power(2, (4-1)) = 14`

- Translating the bitmask nodes into direct base_10, we get: `1 + 4 + 9 = 14`

I am adding the bitmask translation statement into the article (PR 11166).

---

I am now Closing this Issue 2571, as fixed. Thank you for bringing this to our attention.
We hope to hear from you again.

The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.
