### ISSUE TITLE
Refreshing all things

### ISSUE THREAD

**Issue by dmarlow** [MicrosoftDocs/sql-docs#2576]
I tried to use the wizard to enable always encrypted and it didn't work. So, I set things manually, but the "Edit top 200 rows" shows the values of the encrypted column as &lt;Binary data&gt; instead of the actual decrypted value. This works fine in another database, so I'm thinking something else needs to be refreshed using this SP, but I'm not sure what. Is that documented somewhere?

Edit: yes, I also have the `Column Encryption Setting=enabled` connection property set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 500ccf40-206f-9d90-5fb5-8f74b093046b
* Version Independent ID: e6a25384-956b-4d09-a13a-2ab432cf826d
* Content: [sp_refresh_parameter_encryption (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-refresh-parameter-encryption-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-refresh-parameter-encryption-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-refresh-parameter-encryption-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by dmarlow** [comment]
Looks like restarting SSMS was needed to make it work properly.

**Comment by MightyPen** [comment]
@dmarlow Hello Daniel, I'm glad the oldest trick in the book, reboot the application, worked. When the next version of SSMS becomes available (a version later than 18.1), a prompt upgrade would be a good idea.  Thanks.
