### ISSUE TITLE
Why is BEGIN THROW considered invalid syntax?

### ISSUE THREAD

**Issue by chipplyman** [MicrosoftDocs/sql-docs#2577]
"The statement before the THROW statement must be followed by the semicolon (;) statement terminator."

"BEGIN and END are control-of-flow language keywords." (https://docs.microsoft.com/en-us/sql/t-sql/language-elements/begin-end-transact-sql?view=sql-server-2017)

If BEGIN is a control-of-flow language keyword and not a statement, why does 
```
IF <expression>
BEGIN
   THROW <arguments>
END
```
result in error Msg 102 "Incorrect syntax near 'THROW'"?

It's highly bizarre to have to terminate BEGIN with a semicolon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525698d4-0465-5fe0-f09d-dfad8b8413e6
* Version Independent ID: 2ece841a-2d51-542e-6c2b-9d36ffe54202
* Content: [THROW (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/throw-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/language-elements/throw-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/throw-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@chipplyman Hello, The original Transact-SQL syntax did not even allow a terminator character (;), decades ago. I remember during the dev cycle for SQL 7.0 that my teammate wanted to add a particular keyword or phrase, but found that doing so would create an unforeseen ambiguity, if no terminator was used. By this time the SQL Server team had decided it was necessary to add a ';' terminator, and that it was unfortunate the original T-SQL spec had not required one.
I might have a sequence or other detail mis-remembered from so long ago. But the gist is that I am not shocked to occasionally see the type of idiosyncratic syntax instances in T-SQL. I worked in T-SQL before it had its handy THROW, so personally I'm just glad THROW is available, extra semi-colon or not  :-)
Nevertheless, we must agree with your conclusion, that the need for this extra ';' after BEGIN is odd.

I am now Closing this Issue 2577. We hope to hear from you again.  Thanks.

**Comment by KevinPence** [comment]
It helps me to think of it differently.  You're not putting a ';' after BEGIN, you're putting it before THROW.  That way, it reinforces the fact that it's the THROW that requires special syntax.  I do the same thing with CTEs:
BEGIN
;with cte(<cols>) as(...)

Also, I noticed that the semicolon is not required when THROW is the first statement in either a TRY or CATCH block. so BEGIN THROW is a problem, but BEGIN CATCH THROW and BEGIN TRY THROW are not.
