### ISSUE TITLE
More examples would be helpful

### ISSUE THREAD

**Issue by MariannaAtPlay** [MicrosoftDocs/sql-docs#2578]
Thank you for these examples.

I am wondering how I could match a substring of more than one character in a row matching the range in brackets.... Can I use a * or + ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 471411d8-4c8d-84f8-cb37-28593b50b046
* Version Independent ID: f68c0d0b-bc9b-6f83-89bc-49ee3f99b715
* Content: [\[ \] (Wildcard - Character(s) to Match) (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/wildcard-character-s-to-match-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/language-elements/wildcard-character-s-to-match-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/wildcard-character-s-to-match-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@MariannaAtPlay Hello Marianna, I doubt that the `[ ]` syntax supports embedded wildcard characters.

Maybe the following Regular Expression (SSMS) article might be of interest to you:
- https://docs.microsoft.com/sql/ssms/scripting/search-text-with-regular-expressions
    - `https://docs.microsoft.com/sql/ssms/scripting/search-text-with-regular-expressions`

I assume you already know about LIKE and PATINDEX (example C):
- `https://docs.microsoft.com/sql/t-sql/language-elements/like-transact-sql`
- `https://docs.microsoft.com/sql/t-sql/functions/patindex-transact-sql#examples`

Thanks for reaching out to us. Thank you for submitting this Issue. We hope to hear from you again.
I am now Closing this Issue 2578. 
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.
