### ISSUE TITLE
Honorable Mention?

### ISSUE THREAD

**Issue by HakuAnnaruto** [MicrosoftDocs/sql-docs#2581]
Before you set the database to SINGLE_USER, verify the AUTO_UPDATE_STATISTICS_ASYNC option is set to OFF. When set to ON, the background thread used to update statistics takes a connection against the database, and you will be unable to access the database in single-user mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcfe9dc7-6b24-f983-2ea4-a50df1fa335b
* Version Independent ID: 454a558b-3023-1d0e-c057-4f39a323e4aa
* Content: [sp_detach_db (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-detach-db-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-detach-db-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-detach-db-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@HakuAnnaruto - thanks for raising this issue. We're taking a look to see if this should be included in this article.  Thanks!

**Comment by stevestein** [comment]
@HakuAnnaruto - thanks for the suggestion! I added this info to the article and it should appear live within the next 24 hours.

#please-close

**Comment by HakuAnnaruto** [comment]
Many thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
