### ISSUE TITLE
An example of each might be nice

### ISSUE THREAD

**Issue by deanmresource** [MicrosoftDocs/sql-docs#2587]
possibly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea37453c-53c6-056d-46de-b53660afc859
* Version Independent ID: d2aa0683-f65f-7808-7667-8b8e2e90f78d
* Content: [Mathematical Functions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/mathematical-functions-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/mathematical-functions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/mathematical-functions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by deanmresource** [comment]
I think this request can be ignored as at the top of the page is a link to each of the functions.

**Comment by MikeRayMSFT** [comment]
Thanks @deanmresource
