### ISSUE TITLE
Cdc vs standard version

### ISSUE THREAD

**Issue by MisiekBest** [MicrosoftDocs/sql-docs#2588]
CDC is supported in SQL Server Standard since 2016 SP1 version. Does it mean that following issue still exists there? If not, please update the documemtation.

Qutoe from the docs:
If a database is attached or restored with the KEEP_CDC option to any edition other than Enterprise, the operation is blocked because change data capture requires SQL Server Enterprise. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5064f6a-f469-4b7c-101c-e62038f1efb6
* Version Independent ID: 4e830181-4699-703f-cf74-5c468628c082
* Content: [Track Data Changes (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/track-data-changes-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/track-changes/track-data-changes-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/track-data-changes-sql-server.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@rothja Hi Jason, Can you please process this Issue 2588. This issue seems like a Freshness concern.
Thanks, G.

**Comment by rothja** [comment]
@MisiekBest Thanks for pointing this out. I am going to investigate and update the doc if needed.

**Comment by rothja** [comment]
@MisiekBest Thanks for your patience. I believe you are correct. This document was probably updated for RTM, but CDC is supported in 2016 SP1 Standard as you mentioned. [https://blogs.msdn.microsoft.com/sqlreleaseservices/SQL-server-2016-service-pack-1-sp1-released/](https://blogs.msdn.microsoft.com/sqlreleaseservices/SQL-server-2016-service-pack-1-sp1-released/). I'm going to change this statement to avoid confusion. Thank you!
