### ISSUE TITLE
Embedded link directs to wrong page on DQS tutorial page, for SQL 2014

### ISSUE THREAD

**Issue by ryanmajidi** [MicrosoftDocs/sql-docs#2590]
**Submitted to [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1653) by @Xceptions **

A wrong link was inserted in a page for learning how to automate DQS cleansing with SSIS.
In this page [1], the link inserted at the bottom is supposed to take us to the next item on the list of learning which is this [2], but it instead, leads to here [3].
Please correct it

**Comment by MightyPen** [comment]
Helpfully, here are the hidden link Https URLs:

- [1] = `https://docs.microsoft.com/en-us/sql/tutorials/task-6-adding-excel-source-to-the-data-flow?view=sql-server-2014`

- [2] = `https://docs.microsoft.com/en-us/sql/tutorials/task-7-adding-dqs-cleansing-transform-to-the-data-flow?view=sql-server-2014`

- [3] = `https://docs.microsoft.com/en-us/sql/integration-services/data-flow/data-flow?view=sql-server-2014`

 . .

**Comment by MightyPen** [comment]
@msebolt Hi Matthew, For this Issue 2590, would you please fix the errant link, by creating a private repo PR.

**Comment by MightyPen** [comment]
@ryanmajidi Hello Ryan, This Issue #2590 is now fixed by our private repo PR #11245.

Thank you for bringing this documentation shortcoming to our attention. We hope to hear from you again.

I am now Closing this Issue, as fixed.
