### ISSUE TITLE
alexisjulian0509@hotmail.com

### ISSUE THREAD

**Issue by PERTOCK** [MicrosoftDocs/sql-docs#2591]
[alexisjulian0509@hotmail.com]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05f3c988-2e10-aa6c-521f-fb59d991091f
* Version Independent ID: e9545dc2-4a58-9558-4af1-f16d7d7102cb
* Content: [Database Mail - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/database-mail/database-mail?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/database-mail/database-mail.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/database-mail/database-mail.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
This is almost certainly junk spam. Closing.
