### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by AlainBorletHote** [MicrosoftDocs/sql-docs#2592]
The path of the Json variable is wrong in the sample of
Import JSON data into SQL Server tables

See the right path below.

SELECT SalesOrderJsonData.*  
FROM OPENJSON (@jsonVariable, N'$')  
           WITH (  
              Number   varchar(200) N'$.Order.Number',   
              Date     datetime     N'$.Order.Date',  
              Customer varchar(200) N'$.AccountNumber',   
              Quantity int          N'$.Item.Quantity'  
           )  
  AS SalesOrderJsonData; 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 991167bc-4e0e-1fc8-d0bb-f282b51b3321
* Version Independent ID: 0b5cf834-d452-dd57-d51d-268083011e33
* Content: [Work with JSON data in SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/json/json-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/json-data-sql-server.md)
* Product: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@AlainBorletHote -- thank you for your feedback.  We are looking into this now.

**Comment by WilliamAntonRohm** [comment]
@jovanpop-msft -- Jovan, please review my change in https://github.com/MicrosoftDocs/sql-docs-pr/pull/11389.

**Comment by WilliamAntonRohm** [comment]
@AlainBorletHote Thank you for your feedback.  We have updated the documentation and it should be live by tomorrow.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
