### ISSUE TITLE
Better explanation of when recompilation will occur

### ISSUE THREAD

**Issue by rdicroce** [MicrosoftDocs/sql-docs#2593]
The docs for sp_recompile currently say this:

> SQL Server automatically recompiles stored procedures, triggers, and user-defined functions when it is advantageous to do this.

This statement is vague and meaningless because the docs do not explain what conditions are "advantageous". The docs should be improved to precisely list what conditions will trigger recompilation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09d36edc-871a-1f9f-3fbe-7e3e005464c9
* Version Independent ID: b3e3cea8-ad65-1ec6-b666-1b0c9523ca55
* Content: [sp_recompile (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-recompile-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-recompile-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-recompile-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@rdicroce -- Rich, thank you for your feedback.

@stevestein -- Steve, please look into this issue 2593.

**Comment by stevestein** [comment]
@rdicroce - thanks for raising this issue. 
I created an internal work item (1576107) to address this. We can't say when the work item will be addressed but it is now in our queue.

Thanks!

**Comment by stevestein** [comment]
We're going to close this issue. Thanks!
