### ISSUE TITLE
Error in query example

### ISSUE THREAD

**Issue by CundyTech** [MicrosoftDocs/sql-docs#2594]
Query should be 

"SELECT * FROM sys.dm_operation_status   
   WHERE major_resource_id = 'myddb'   
   ORDER BY start_time DESC; "

Currently there is white space in the query which I've marked with an "*" below.

"SELECT * FROM sys.dm_*operation_status   
   WHERE major_resource_id = 'myddb'   
   ORDER BY start_time DESC; "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b04de445-400e-849b-cd9e-234f3bf1b088
* Version Independent ID: 23b5e022-eac1-7a0d-43d0-0964bd8e2a5e
* Content: [sys.dm_operation_status (Azure SQL Database) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-operation-status-azure-sql-database?view=azuresqldb-current)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-operation-status-azure-sql-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-operation-status-azure-sql-database.md)
* Service: **sql-database**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@CundyTech -- Dan, thank you for bringing this to our attention.  I will make this change shortly.

**Comment by WilliamAntonRohm** [comment]
The documentation has been updated and should be live by tomorrow.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
