### ISSUE TITLE
Reuse of @P1 variable is a bit confusing

### ISSUE THREAD

**Issue by lukaseder** [MicrosoftDocs/sql-docs#2597]
Studying the example code, there are two separate `@P1` variables with different meanings. This is a bit confusing. the first `@P1` variable could be called `@output` or `@handle` etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bedd3f7f-4501-da17-bb85-74792d52bd43
* Version Independent ID: 3eac053d-5dde-6ddf-26cb-d4677021dc69
* Content: [sp_prepexec (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-prepexec-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-prepexec-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-prepexec-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@lukaseder -- Lukas, thank you for your feedback.

@stevestein -- Steve, please review my updates in https://github.com/MicrosoftDocs/sql-docs-pr/pull/11388.

**Comment by stevestein** [comment]
@lukaseder - thanks again for raising this issue. The article has been update.
