### ISSUE TITLE
excess space

### ISSUE THREAD

**Issue by fedorovdima** [MicrosoftDocs/sql-docs#2598]
Hi,

There is an excess (unexpected) space between "sys.database_" and "audit_specifications" in "sys.database_ audit_specifications" link on this page. Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2a1a3a-cffa-ec4b-dedc-c1c23d547abb
* Version Independent ID: b0e62617-2dc3-8762-e359-a78af1fe3191
* Content: [SQL Server Audit (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-database-engine?view=sql-server-2017)
* Content Source: [docs/relational-databases/security/auditing/sql-server-audit-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/auditing/sql-server-audit-database-engine.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@fedorovdima -- Dmitry, thank you for your feedback. I have updated the documentation and it should be live by tomorrow.
