### ISSUE TITLE
Document inconsistency (-g startup option)

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#2601]
@ry0uta commented on [Fri Jul 26 2019](https://github.com/MicrosoftDocs/sql-docs.ja-jp/issues/435)
(Translated)
In the following pages, the statement about the -g startup option has been deleted in SQL Server 2016 and later versions.

Database Engine Service Startup Options
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/database-engine-service-startup-options?view=sql-server-2017

In the following pages, SQL Server 2017 still has the description of startup option -g, which causes inconsistencies.

sqlservr application
https://docs.microsoft.com/en-us/sql/tools/sqlservr-application?view=sql-server-2017

In addition, if the description deletion of -g is intentional, reference to -g for SQL Server 2017 still remains on the following page.
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/server-memory-server-configuration-options?view=sql-server-2017#setting-the-memory-options- manually
Then subtract the amount of memory that is equivalent to the potential SQL Server memory allocation, which is not controlled by max server memory. The equivalent amount of memory can be obtained by adding -g of startup parameter 3 to the maximum worker thread 2 calculated by the stack size 1 * (If -g is not set, 256 MB is added by default) ). What remains is the max_server_memory setting for single instance setup.

Clarification is required because it can not be determined whether the -g parameter is supported for SQL Server 2016 or later.
As an aside, if it is not supported, how will it handle memory settings of memory_to_reserve managed with -g in past versions? (Change of setting itself is deprecated in 2016 or later?)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 49ff7ba8-ef34-2020-0a3b-ee8e529d528e
* Version Independent ID: 8d086f94-2f89-db73-3ac9-60c1086e3262
* Content: [sqlservr.exe アプリケーション - SQL Server](https://docs.microsoft.com/ja-jp/sql/tools/sqlservr-application?view=sql-server-2017)
* Content Source: [docs/tools/sqlservr-application.md](https://github.com/MicrosoftDocs/sql-docs.ja-jp/blob/live/docs/tools/sqlservr-application.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

---

@srvbpigh commented on [Fri Jul 26 2019](https://github.com/MicrosoftDocs/sql-docs.ja-jp/issues/435#issuecomment-515387178)

Hello, @ry0uta
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I moved this here since the user is refering the original documentation
I hard translated it myself, if you need to reach the contributor in their native language, please let us know
best

**Comment by WilliamAntonRohm** [comment]
@msebolt -- please try running `sqlservr.exe /?` to see if the -g option still exists, and let me know the results.

**Comment by yang-jiayi** [comment]
use SQL2019 ctp3.2

C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Binn>sqlservr.exe /?
usage: sqlservr
        [-a<L2 buffer pool directory>,<size in GB>]                                     (adding an L2 buffer pool file)
        [-c] (not as a service)
        [-d file] (alternative master data file)
        [-l file] (alternative master log file)
        [-e file] (alternate errorlog file)
        [-f] (minimal configuration mode)
        [-m] (single user admin mode)
        [-g number] (stack MB to reserve)
        [-k <decimal number>] (checkpoint speed in MB/sec)
        [-n] (do not use event logging)
        [-s name] (alternate registry key name)
        [-T <number>] (trace flag turned on at startup)
        [-x] (no statistics tracking)
        [-y number] (stack dump on this error)
        [-B] (breakpoint on error (used with -y))
        [-K] (force regeneration of service master key (if exists))
        [-v] (list version information)

See documentation for details.
SQL Server shutdown has been initiated

The [-g number] (stack MB to reserve) option still exists. But is it supported?

**Comment by msebolt** [comment]
@CeciAc Please refer to issue https://github.com/MicrosoftDocs/sql-docs/issues/2596 for further feedback.
