### ISSUE TITLE
excess space

### ISSUE THREAD

**Issue by fedorovdima** [MicrosoftDocs/sql-docs#2602]
Hi,

There's an excess (unexpected) space in "AUDIT_ CHANGE_GROUP" under "Audit-Level Audit Action Groups".  Please fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e423dd72-6012-f9f0-9bd1-6ab946399770
* Version Independent ID: f55d3328-111e-13d2-d8c2-78ba2b644b91
* Content: [SQL Server Audit Action Groups and Actions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions?view=sql-server-2017#audit-level-audit-action-groups)
* Content Source: [docs/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@fedorovdima -- Dmitry, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
