### ISSUE TITLE
Syntax in the example A has some issues.

### ISSUE THREAD

**Issue by tpaulshippy** [MicrosoftDocs/sql-docs#2605]
FIELDTERMINATOR, STRINGDELIMITER, DATEFORMAT, and USETYPE_DEFAULT are all wrong.
As specified in another doc (https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-file-format-transact-sql?view=azure-sqldw-latest), these should be FIELD_TERMINATOR, STRING_DELIMETER, DATE_FORMAT, and USE_TYPE_DEFAULT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ac2fe2-31da-7db6-2d5f-5091022f41d2
* Version Independent ID: bbf07c2c-7006-7b94-f12f-800fa7bc67e4
* Content: [CREATE EXTERNAL TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-table-transact-sql?view=azure-sqldw-latest#feedback)
* Content Source: [docs/t-sql/statements/create-external-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@tpaulshippy Thank you for the feedback.

The issue appears to have been fixed.  Please comment below if there are any further questions.
