### ISSUE TITLE
Add compatibility table

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/sql-docs#2607]
I think this is a relatively new command. For example, it doesn’t exist in SQL Server 2008 R2. Please add a compatibility table like [MDN’s for browser features](https://developer.mozilla.org/en-US/docs/Web/CSS/grid#Browser_compatibility) so that we know when this feature was introduced and, thus, when we can start relying on it in our codebases.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525698d4-0465-5fe0-f09d-dfad8b8413e6
* Version Independent ID: 2ece841a-2d51-542e-6c2b-9d36ffe54202
* Content: [THROW (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/throw-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/language-elements/throw-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/throw-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@binki Thank you for the feedback.

Your request falls under general versioning documentation and has been requested under issue https://github.com/MicrosoftDocs/sql-docs/issues/2539.

Thank you again and please feel free to add any additional comments below.
