### ISSUE TITLE
Can't run SQL 2019 in ubuntu VM

### ISSUE THREAD

**Issue by sateeshmachineni** [MicrosoftDocs/sql-docs#2610]
I am using below distro

> 
>   Static hostname: Ubuntu-sateesh
>          Icon name: computer-vm
>            Chassis: vm
>         Machine ID: ede06e60f8d6483eb20f2d0041c4955f
>            Boot ID: 33d304d4ddaf4f008f90861f3684c116
>     Virtualization: oracle
>   Operating System: Ubuntu 18.04.2 LTS
>             Kernel: Linux 4.18.0-25-generic
>       Architecture: x86-64

and below image
```

REPOSITORY                       TAG                  IMAGE ID            CREATED             SIZE
mcr.microsoft.com/mssql/server   2019-CTP3.2-ubuntu   14eb731ca05b        5 days ago          1.48GB
```

while starting container, i am getting below error

This is an evaluation version.  There are [173] days left in the evaluation period.
This program has encountered a fatal error and cannot continue running at Mon Jul 29 03:25:29 2019
The following diagnostic information is available:

         Reason: 0x00000003
         Status: 0x00000001
        Message: (*__errno_location ()) == 28 || (*__errno_location ()) == 22 || (*__errno_location ()) == 38
          Stack:
                 IP               Function
                 ---------------- --------------------------------------
                 000055ebc91ec3aa std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
                 000055ebc91ebea9 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
                 000055ebc91313ee std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
                 000055ebc91cc923 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
                 000055ebc91c82f1 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
                 000055ebc91c8e6f std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
                 000055ebc912d79b std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
                 000055ebc911f645 <unknown>
                 00007f221645e830 __libc_start_main+0xf0
                 000055ebc911c029 <unknown>
        Process: 7 - sqlservr
         Thread: 7
    Instance Id: 15601460-77be-4c5a-93ae-bd2a9c09b28b
       Crash Id: d60d63c2-cc7e-4cc7-b6d1-df3539931748
    Build stamp: e7cecc1663d059f8a4c7f4e379339d34261f68cfceb977a62c34ac7bccbb72af
   Distribution: Ubuntu 16.04.6 LTS
     Processors: 1
   Total Memory: 4136456192 bytes
      Timestamp: Mon Jul 29 03:25:29 2019
     Last errno: 1
Last errno text: Operation not permitted

Ubuntu 16.04.6 LTS
Capturing core dump and information to /var/opt/mssql/log...
dmesg: read kernel buffer failed: Operation not permitted
No journal files were found.
No journal files were found.
Mon Jul 29 03:25:32 UTC 2019 Capturing program information
Mon Jul 29 03:25:33 UTC 2019 Attempting to capture a dump with paldumper
WARNING: Capture attempt failure detected
Attempting to capture a filtered dump with paldumper
WARNING: Attempt to capture dump failed.  Reference /var/opt/mssql/log/core.sqlservr.7.temp/log/paldumper-debug.log for details
Mon Jul 29 03:25:33 UTC 2019 Attempting to capture a dump with gdb
WARNING: Unable to capture crash dump with GDB. You may need to
allow ptrace debugging, enable the CAP_SYS_PTRACE capability, or
run as root.
Mon Jul 29 03:25:34 UTC 2019 Capturing program binaries
Mon Jul 29 03:25:35 UTC 2019 Compressing the dump files

Any ideas..There are  no log files in /var/opt/mssql

**Comment by msebolt** [comment]
@sateeshmachineni Thank you for the question.

For the best traction, please provide a specific document to reference.  

We generally do not provide support for non doc-related issues.

**Comment by msebolt** [comment]
Alternatively try the [SQL Server forum](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/home?category=sqlserver).

**Comment by MightyPen** [comment]
Hello @sateeshmachineni , is one of these two articles the one you obtained the link from?

[ sql-docs\docs\linux\ ]
 > dir /b /s \*ubuntu\*.md


- [https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu)
    - C:\Users\genemi\GitGm\sql-docs-pr\docs\linux\quickstart-install-connect-ubuntu.md

&nbsp;

- [https://docs.microsoft.com/en-us/sql/linux/sample-unattended-install-ubuntu](https://docs.microsoft.com/en-us/sql/linux/sample-unattended-install-ubuntu)
    - C:\Users\genemi\GitGm\sql-docs-pr\docs\linux\sample-unattended-install-ubuntu.md

CC: @msebolt 
 . .

**Comment by sateeshmachineni** [comment]
i am sorry , i thought clicking give feedback will directly link to the page i am.I installed from here.

https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-ver15&pivots=cs1-bash#pullandrun2019

you can close this, i will try in support forums

**Comment by msebolt** [comment]
@sateeshmachineni Thank you for the followup.  

Closing the issue now.
