### ISSUE TITLE
The first TSQL code on this page does not work

### ISSUE THREAD

**Issue by robert4os** [MicrosoftDocs/sql-docs#2614]
The returned data type is not defined in the code. It should read:

CREATE FUNCTION [dbo].[fnCalculateDistance] (@Lat1 float, @Long1 float, @Lat2 float, @Long2 float)
-- User-defined function calculates the direct distance between two geographical coordinates.
RETURNS decimal(28, 10)
AS...

Note the 'decimal(28, 10)'

Best regards,
Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9b5f36-b5fc-bfaf-5ed2-ff80b77b5635
* Version Independent ID: a2b2fd23-6440-b398-bdca-1c996fbb81b3
* Content: [Create data features using R and SQL Server functions - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/tutorials/walkthrough-create-data-features?view=sql-server-2017)
* Content Source: [docs/advanced-analytics/tutorials/walkthrough-create-data-features.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/tutorials/walkthrough-create-data-features.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
Thank you for your contribution @robert4os. I have fixed this and it will be published later today.
