### ISSUE TITLE
An example of the acceptance of Polygon

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#2616]
Hi team, 
I moving this from here:  https://github.com/MicrosoftDocs/sql-docs.zh-cn/issues/117 because the zh-CN is replicating the en-US documentation

@zhangzuozuo commented 9 hours ago (Translated)

In the introduction of the accepted examples on this page,
“The following criteria are needed for a ring to be acceptable.

The LineString instance must be accepted.
The LineString instance must have at least four points.
The starting and ending points of the LineString instance must be the same."

Whether the LineString instance should be a Polygon instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fafb07e7-3bab-c01a-409c-71c35c5880e9
* Version Independent ID: 05e7dc27-c520-039d-be50-c4fc91594313
* Content: [Polygon - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/polygon?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/spatial/polygon.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/spatial/polygon.md)
* Product: **sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by msebolt** [comment]
@MladjoA Is **LineString** the correct criteria or should it be **Polygon**?

Would you please process this issue #2616.

**Comment by msebolt** [comment]
@zhangzuozuo This issue #2616 is being processed.

**Comment by MladjoA** [comment]
@msebolt, Polygon consists of one or more rings, which are LineStrings.
Criteria listed refers to rings, so LineString is correct.
Please let me know if any additional action is needed from my side.

Thanks,
Mladen

**Comment by msebolt** [comment]
@MladjoA  Thank you for the clarification.  The documentation has been updated.
