### ISSUE TITLE
use of double quotes in JSON output from SQL server

### ISSUE THREAD

**Issue by jsnyderDH** [MicrosoftDocs/sql-docs#2617]
1. Is there a way to remove the double quotes from the field labels when out putting to JSON from SQL server?

2. Is there a way to change the double quotes to single quotes around the values when out putting to JSON from SQL Server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb5c17b-c567-303f-00b8-0c8a0ad15fb5
* Version Independent ID: a4ccc766-4a61-5b7a-e5dd-692e3cebb503
* Content: [Format Query Results as JSON with FOR JSON (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md)
* Product: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by MightyPen** [comment]
@jsnyderDH Hello John, This Issues webpage is only for Documentation shortcomings. We cannot provide Support here. However,.....

The following links to Docs articles may be relevant. I see no way to effect the changes to the output JSON that you described.


- [https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server](https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server)

- [https://docs.microsoft.com/en-us/sql/relational-databases/json/how-for-json-converts-sql-server-data-types-to-json-data-types-sql-server](https://docs.microsoft.com/en-us/sql/relational-databases/json/how-for-json-converts-sql-server-data-types-to-json-data-types-sql-server)

- [https://docs.microsoft.com/en-us/sql/relational-databases/json/how-for-json-escapes-special-characters-and-control-characters-sql-server](https://docs.microsoft.com/en-us/sql/relational-databases/json/how-for-json-escapes-special-characters-and-control-characters-sql-server)

- [https://docs.microsoft.com/en-us/sql/relational-databases/json/use-for-json-output-in-sql-server-and-in-client-apps-sql-server](https://docs.microsoft.com/en-us/sql/relational-databases/json/use-for-json-output-in-sql-server-and-in-client-apps-sql-server)

&nbsp;

I am now Closing this Issue #2617 .  But I may forward this concern onward to someone who might work in this area.
Thank you for submitting this Issue. We hope to hear from you again.

CC: @jovanpop-msft

**Comment by msebolt** [comment]
@jsnyderDH Also, as a workaround you may consider

```
DECLARE @j1 varchar(1024);
DECLARE @j2 varchar(1024);

SET @j1 = (SELECT '42' AS A FOR JSON PATH);
PRINT @j1;

SET @j2 = (SELECT REPLACE (@j1, '"', ''));

PRINT @j2;
```

with output

```
[{"A":"42"}]
[{A:42}]
```
