### ISSUE TITLE
Incorrectly labeled index example C, is it Clustered?

### ISSUE THREAD

**Issue by roy-tate** [MicrosoftDocs/sql-docs#2620]
Minor oversight in file /t-sql/statements/create-index-transact-sql.md  

Under H2 **Examples: All versions...**, in example **C**, the description identifies a non-clustered index, but the example is clearly clustered.  I didn't look at **AdventureWorks** before filing this, but I think it should be non-clustered as I suspect most vendors would have several products.

------

The text and the code example contradict each other, regarding `CLUSTERED`.
Should the text be changed to say _clustered_, or should the code example be changed to **remove** the keyword `CLUSTERED`?  (T-SQL has no keyword NONCLUSTERED.)
Maybe examining the existing indexes on the AdventureWorks sample database table `ProductVendor` will give a clue. For example, if the table already has Clustered index, then the code example is wrong to have `CLUSTERED` (because a table can have at most 1 clustered index).

_Here is a quotation from the article:_

The following example creates a **non-clustered** index on the VendorID column of the ProductVendor table in the Purchasing database.

```
CREATE CLUSTERED INDEX IX_ProductVendor_VendorID ON Purchasing..ProductVendor (VendorID);
```

**Comment by MightyPen** [comment]
@msebolt Hi Matthew, Can you please access the AdventureWorks database to process this Issue #2620.

**Comment by msebolt** [comment]
@roy-tate Thank you for the feedback.

It's an interesting question and I would guess it means a clustered index it focuses use on the ID column.
