### ISSUE TITLE
Small Typo in section "Set the default database mail profile for SQL Server on Linux"

### ISSUE THREAD

**Issue by bivanbi** [MicrosoftDocs/sql-docs#2621]
In section: Set the default database mail profile for SQL Server on Linux
sudo /opt/mssq/bin/mssql-conf set sqlagent.databasemailprofile <profile_name>
should be
sudo /opt/mssql/bin/mssql-conf set sqlagent.databasemailprofile <profile_name>

(notice the missing l in mssql-conf path)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c0b1027-3982-e114-0230-c6bd9bd81346
* Version Independent ID: 244740de-8817-1671-387d-970f8ee8dfcb
* Content: [Configure SQL Server settings on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-configure-mssql-conf.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-mssql-conf.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @bivanbi! Thank you so much for letting us know! We really appreciate it. I've fixed this typo and it should go live shortly.

https://github.com/MicrosoftDocs/sql-docs-pr/pull/11297
