### ISSUE TITLE
What about Stored Procedures

### ISSUE THREAD

**Issue by LukeChung** [MicrosoftDocs/sql-docs#2622]
What are the permission issues for reading the programmable items like stored procedures and functions where these keys are held?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21605a56-8aa8-9dbf-6743-999f204e6775
* Version Independent ID: 35bbb590-6aec-4c63-9dac-cff287745d06
* Content: [Always Encrypted (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/encryption/always-encrypted-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/always-encrypted-database-engine.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @aliceku
* Microsoft Alias: **aliceku**

**Comment by msebolt** [comment]
@LukeChung  Thank you for the question.

Permissions can vary with associated stored procedures, but are generally higher level permissions such as `VIEW SERVER STATE`, and should be included in reference documentation (such as [sys-dm-database-encryption-keys](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-database-encryption-keys-transact-sql?view=sql-server-2017)).

Specific [Always Encrypted permissions](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine?view=sql-server-2017#database-permissions) are there as more of a subset to be used for customization.
