### ISSUE TITLE
Batch, stored procedure PredictTipBatchMode expects 'input' not 'inquery'

### ISSUE THREAD

**Issue by robert4os** [MicrosoftDocs/sql-docs#2623]
q &lt;- paste("EXEC PredictTipBatchMode @inquery = ", input, sep="");

this should set @input NOT @inquery

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea5db3ce-8100-ffa7-6372-a46582cd2490
* Version Independent ID: 483e7891-b989-8bdb-4305-f57d2678c86e
* Content: [Deploy an R model for predictions on SQL Server - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/tutorials/walkthrough-deploy-and-use-the-model?view=sql-server-2017)
* Content Source: [docs/advanced-analytics/tutorials/walkthrough-deploy-and-use-the-model.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/tutorials/walkthrough-deploy-and-use-the-model.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by msebolt** [comment]
@robert4os Thank you for the feedback.

The document you reference has been updated.
