### ISSUE TITLE
The System Views link in the See Also section is incorrect

### ISSUE THREAD

**Issue by scmancuso** [MicrosoftDocs/sql-docs#2625]
The System Views link takes me to the Transact-SQL Reference page, not the System Views page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061902ef-4732-1639-2970-96bfc04a6ce0
* Version Independent ID: 7178ceb7-4a73-234d-fd3a-845754774ce7
* Content: [System Information Schema Views (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-information-schema-views/system-information-schema-views-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-information-schema-views/system-information-schema-views-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-information-schema-views/system-information-schema-views-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@scmancuso Thank you for the feedback.

The change has been made to the documentation.
