### ISSUE TITLE
Need Connectivity for JDBC URL

### ISSUE THREAD

**Issue by bishwo633** [MicrosoftDocs/sql-docs#2629]
Request for feature:
Connectivity of PostgreSQL via JDBC URL, e.g. jdbc:postgresql://&lt;hostname or IP address&gt;[:&lt;port&gt;]/&lt;database&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d38cb432-16c9-c7f7-d79b-18c9a640d271
* Version Independent ID: 9abf3190-1bc3-bc8a-016e-612dad3964ab
* Content: [Quickstart: Connect and query PostgreSQL - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/quickstart-postgres?view=sql-server-2017#feedback)
* Content Source: [docs/azure-data-studio/quickstart-postgres.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/quickstart-postgres.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @rachel-msft
* Microsoft Alias: **raagyema**

**Comment by rachel-msft** [comment]
Hi @bishwo633. Thanks for reaching out. We ask that you make feature requests on the product GitHub page: https://github.com/Microsoft/azuredatastudio-postgresql, including your reasons why you think this is a great feature add. Thanks

**Comment by rachel-msft** [comment]
#please-close
