### ISSUE TITLE
Need to adjust installation notes

### ISSUE THREAD

**Issue by fatherjack** [MicrosoftDocs/sql-docs#2630]
Module version has changed.

Where the content shows
**Install-Module sqlserver -RequiredVersion  21.1.18140-preview -AllowPrerelease**

It should be adjusted to show
**Install-Module sqlserver -RequiredVersion  21.1.18147 -AllowPrerelease**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdc5826c-d266-6f61-e1eb-b4f236d03dd9
* Version Independent ID: 4ab93d92-6a23-a0c0-2911-ce06e99dc5c5
* Content: [Download SQL Server PowerShell Module - SQL Server](https://docs.microsoft.com/en-us/sql/powershell/download-sql-server-ps-module?view=sql-server-2017)
* Content Source: [docs/powershell/download-sql-server-ps-module.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/download-sql-server-ps-module.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@fatherjack Thank you for the feedback.

I think the example is to highlight use of the `-AllowPrerelease` option, however the article has been updated to not reference in current release information.

Closing the issue now.
