### ISSUE TITLE
data types

### ISSUE THREAD

**Issue by HenrikStaunPoulsen** [MicrosoftDocs/sql-docs#2631]
Please note that SQL Database does not support all data types. So far I've found that Text, nText and XML are not supported data types for columns in external tables.

There is a work-a-round as listed in https://stackoverflow.com/questions/50898484/azure-sql-db-query-external-azure-sql-db-ppdwmanagedtonativeinteropexception
but it is very cumbersome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ac2fe2-31da-7db6-2d5f-5091022f41d2
* Version Independent ID: bbf07c2c-7006-7b94-f12f-800fa7bc67e4
* Content: [CREATE EXTERNAL TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-table-transact-sql?view=azuresqldb-current)
* Content Source: [docs/t-sql/statements/create-external-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@HenrikStaunPoulsen thanks - fixed

**Comment by CarlRabeler** [comment]
#please-close

**Comment by HenrikStaunPoulsen** [comment]
thank you very much
