### ISSUE TITLE
typo - Distribtued should be Distributed

### ISSUE THREAD

**Issue by TheOpsMgr** [MicrosoftDocs/sql-docs#2632]
https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/distributed-availability-groups?view=sql-server-2017#dmv-to-list-distribtued-ag-health 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0e8cda-edf4-81f6-0941-1ed53558e1e9
* Version Independent ID: 09e55110-b604-acd8-9903-bbd4f971170c
* Content: [What is a distributed availability groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/distributed-availability-groups?view=sql-server-2017#dmv-to-list-distribtued-ag-health)
* Content Source: [docs/database-engine/availability-groups/windows/distributed-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/distributed-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@TheOpsMgr Thank you for the feedback.

Your fix has been made.
