### ISSUE TITLE
Integrated Security

### ISSUE THREAD

**Issue by dlee1964** [MicrosoftDocs/sql-docs#2633]
I would like to see an example of how to call sp_setapprole with Integrated Security (ie, where the password is not known).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2ce8a13-8517-827a-4f00-a382b393f707
* Version Independent ID: 06f44d00-2978-ae10-a8fb-24a6a0c118c7
* Content: [sp_setapprole (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-setapprole-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-setapprole-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-setapprole-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please consider adding an Integrated Security example to this article.

**Comment by VanMSFT** [comment]
Hi @dlee1964 - Thank you for your feedback! Can you elaborate on what you are looking for? The sp_setapprole Stored Procedure requires a password, and does not work with Integrated Security (i.e. Windows Authentication).

**Comment by VanMSFT** [comment]
Hi @dlee1964 - I'll go ahead and close this issue for now, but please feel free to let us know if you have any concerns, or if you can clarify your question. Thanks!

**Comment by dlee1964** [comment]
> 
> 
> Hi @dlee1964 - Thank you for your feedback! Can you elaborate on what you are looking for? The sp_setapprole Stored Procedure requires a password, and does not work with Integrated Security (i.e. Windows Authentication).

To say that it "does not work with Integrated Security" contradicts the documentation, which states that it works with both types of authentication (which would include Windows Authentication / Integrated Security).  What I have since found out since posting feedback is that the password for the application role is a totally separate from the password for authentication.  This is not clear  in the documentation, however, and was the source of my confusion.

**Comment by VanMSFT** [comment]
@dlee1964 - Thanks for the feedback, Del! We'll take your criticism into consideration to enhance our documentation.

**Comment by VanMSFT** [comment]
https://github.com/MicrosoftDocs/sql-docs-pr/pull/11419
