### ISSUE TITLE
Mount command for tiered storage incorrect

### ISSUE THREAD

**Issue by dgshaver** [MicrosoftDocs/sql-docs#2635]
The mount command to mount a Gen2 storage account as tiered storage is (no longer?) correct.

This command:
azdata bdc **storage-pool** mount create --remote-uri abfs://<blob-container-name>@<storage-account-name>.dfs.core.windows.net/ --mount-path /mounts/<mount-name>

Should be:
azdata bdc **hdfs** mount create --remote-uri abfs://<blob-container-name>@<storage-account-name>.dfs.core.windows.net/ --mount-path /mounts/<mount-name>

Same applies to status command in the next section of the article.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd3bb6dd-5845-0242-2345-5344de8a0cda
* Version Independent ID: 919d830f-83cb-fe3f-33a2-163d6fe56640
* Content: [Mount ADLS Gen2 for HDFS tiering - How to mount ADLS Gen2](https://docs.microsoft.com/en-us/sql/big-data-cluster/hdfs-tiering-mount-adlsgen2?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/big-data-cluster/hdfs-tiering-mount-adlsgen2.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/hdfs-tiering-mount-adlsgen2.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @NelGson
* Microsoft Alias: **negust**

**Comment by msebolt** [comment]
@dgshaver  Thank you for the feedback.  

Your changes have been added to the documentation.

**Comment by dgshaver** [comment]
Thanks for fixing so quickly!

**Comment by msebolt** [comment]
@dgshaver  No problem.

Feel free to submit questions or concerns to the GitHub anytime.
