### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by bartedgerton** [MicrosoftDocs/sql-docs#2636]
There is a lot of missing information on installing this package.  I wish you would stop posting your stupid install files to 3rd party sites.  I'm not a programmer, I don't want to learn how to use NuGet, nor do I want to register there.  I just want to be able to use the software for my SQL SERVER needs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c7c4366-e500-8ead-332b-d258e456ae28
* Version Independent ID: fba66ee2-9c9a-e0f4-9049-2ceb7ca4a948
* Content: [Installing SMO - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/installing-smo?view=sql-server-2017)
* Content Source: [docs/relational-databases/server-management-objects-smo/installing-smo.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/server-management-objects-smo/installing-smo.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@bartedgerton -- Bart, thank you for your feedback.  To be sure it gets to the developers, please use the following link:

- [UserVoice - Suggestion to improve SQL Server?](https://feedback.azure.com/forums/908035-sql-server)

You might also find this topic useful:  https://stackoverflow.com/questions/14894864/how-to-download-a-nuget-package-without-nuget-exe-or-visual-studio-extension
