### ISSUE TITLE
Mistake? 

### ISSUE THREAD

**Issue by Kirja82** [MicrosoftDocs/sql-docs#2638]
Read-only access to one or more secondary replicas (readable secondary replicas)

Any availability replica can be configured to allow read-only access to its local databases when performing the secondary role, though some operations are not fully supported. Also, if you would like to prevent read-only workloads from running on the primary (i think, you mean on secondary) replica, you can configure the replicas to allow only read-write access when running under the primary role. For more information, see Active Secondaries: Readable Secondary Replicas (Always On Availability Groups).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c5b4585-159a-6472-140f-8e9439222ab7
* Version Independent ID: 03a14cb4-5589-1156-5a4e-938665968ebb
* Content: [Overview of Always On Availability Groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @Kirja82, thanks for contacting Microsoft! At first glance, "primary" looks correct, as we're talking about preventing read-only access on the primary replica by setting it to read-write. But let me double check :) 

Thanks!
Masha from the SQL Docs team

**Comment by MikeRayMSFT** [comment]
Hi @Kirja82. Thanks for submitting. I agree with @MashaMSFT. What this scenario is describing is a business requirement to offload the read-only workloads away from the primary replica for performance reasons. It would only allow connections for workloads that require read-write access. We'll look at if we can clarify this.

**Comment by MashaMSFT** [comment]
Hi @Kirja82 , thanks again for contacting Microsoft! Although the paragraph was written correctly, I see how it can be confusing. I've rewritten it to (hopefully) add greater clarity. This change should be live at this point. Is there anything more we can assist you with? If not, we will proceed with closing out this Git Issue in a few business days. 

Thanks again and hope you have a wonderful weekend!
Masha from the SQL Docs team
