### ISSUE TITLE
bad requirements

### ISSUE THREAD

**Issue by Mlsoun** [MicrosoftDocs/sql-docs#2640]
when installation error, follow this article https://social.msdn.microsoft.com/Forums/en-US/16c996d7-c3b1-42e4-9a66-6e27f6ec85e2/microsoft-command-line-utilities-15-for-sql-server-installation-failed?forum=sqlsetupandupgrade

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86bd520a-7468-fd55-c357-b0f645a917ef
* Version Independent ID: 3dc9dee5-afcb-8287-4441-e84ff717186a
* Content: [bcp Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-2017#feedback)
* Content Source: [docs/tools/bcp-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/bcp-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by Mlsoun** [comment]
Setup is missing an installation prerequisite: Microsoft ODBC Driver 17 for SQL Server".

**Comment by msebolt** [comment]
@Mlsoun Thank you for the feedback.

The ODBC Driver is already listed in the **Requirements** section, though I updated the article to make it easier to see.
