### ISSUE TITLE
Typo in "return value" documentation

### ISSUE THREAD

**Issue by RichardD2** [MicrosoftDocs/sql-docs#2641]
"The int difference between the startdate and enddate, expressed in the -&gt;coundary&lt;- set by datepart."

Should be "boundary", not "coundary".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340056a9-0593-4289-7b72-601ae718b05f
* Version Independent ID: 1db8e288-8068-be96-b2f2-c8a2fe5a857a
* Content: [DATEDIFF (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/datediff-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/datediff-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
THanks for noticing this - we're fixing it in https://github.com/MicrosoftDocs/sql-docs-pr/pull/11115
