### ISSUE TITLE
Typos on scale-out group page

### ISSUE THREAD

**Issue by lerchdude** [MicrosoftDocs/sql-docs#2645]
Title is wrong: "Improve PolyBase scale-out groups on Windows" -&gt; "Configure a scale-out group"
Misuse of the word "setup":  "This article describes how to setup" -&gt; "This article describes how to set up"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acaaf25c-0a4e-05af-dc8f-307ff92e3b17
* Version Independent ID: 14446de6-0c23-fae4-135c-4cc34aff96a3
* Content: [Improve PolyBase scale-out groups on Windows - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/configure-scale-out-groups-windows?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/polybase/configure-scale-out-groups-windows.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/configure-scale-out-groups-windows.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@lerchdude Thank you for the feedback.

The documentation has been updated.
