### ISSUE TITLE
sqlsrv support for PHP 7.3 unclear

### ISSUE THREAD

**Issue by ryanmajidi** [MicrosoftDocs/sql-docs#2646]
**Submitted to [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1767) by @camer-on **

I am seeing a discrepancy in documentation.

https://docs.microsoft.com/en-us/sql/connect/php/system-requirements-for-the-php-sql-driver?view=sql-server-2017 says that SQLSRV v5.6 supports PHP v7.3 and higher.
https://www.microsoft.com/en-us/download/details.aspx?id=57916 says that SQLSRV v5.6 supports PHP 7.0, 7.1 and 7.2.
I would be more comfortable downloading SQLSRV v5.6 if the two pages could agree on what versions of PHP it supports. Can someone get this corrected?

**Comment by msebolt** [comment]
@ryanmajidi Thank you for the feedback.

You should follow the [Systems Requirements](https://docs.microsoft.com/sql/connect/php/system-requirements-for-the-php-sql-driver) page for the latest information on PHP version to support.

All information on the download pages is out-of-date and will only be updated once with the newest version of **Microsoft Drivers** arrives.
