### ISSUE TITLE
SSMS 18.2:  Opening Saved Database Diagram crashes application

### ISSUE THREAD

**Issue by ArnieGA** [MicrosoftDocs/sql-docs#2652]
Hi:
For some reason, this only happens in a specific database; the others have not presented this problem.

Problem:  After saving a database diagram without any problems, trying to open the diagram (modify) crashes the entire application.  The application re-starts.

Things I've already tried:
1- Deleted the diagram
2- Refreshed the connection to the server (right-click on server node => refresh)
3- Confirmed the diagram no longer exists
4- Disconnected from Server
5- Closed application (SSMS)
6- Started application
7- Created a new diagram
8- Made necessary editions and saved the diagram
9- Closed the diagram
10- Re-opened (modify) the diagram (Diagram doesn't open and SSMS crashes)
11- Repeated steps 1 to 5
12- Performed an installation Repair
13- Repeated steps 6 to 10 with no success

Please let me know if there's any additional data needed.

**Comment by msebolt** [comment]
@ArnieGA  We're sorry to hear you're experiencing issues.

Generally this forum is documentation or product-related issues that reference a specific article (tutorials, how-tos, etc.) only.

Please post your issue in the [SQL Server forum](https://social.msdn.microsoft.com/Forums/sqlserver/home?category=sqlserver).  There's a much better chance there to get the traction it needs to be handled by the product team.

**Comment by pirnadi** [comment]
I am also experiencing the same problem, but I can overcome it.
Open your diagrams not by double-clicking them, but instead by right-clicking them to open the related context menu and then select Modify menu. Everything is running well.

**Comment by ryanmar** [comment]
I am also experiencing this problem.   The right-context menu does not work around the issue.   This is with SSMS version  xxx.   It reproduces when run under Administrator or restricted Windows permission, and connecting using Domain, Local System and SQL Server accounts.  (Yes, I went through the matrix).   I am willing to provide whatever debugging data or access anyone want to take a look at this.   I was a developer in the Windows group for 9 years and thus am very accomodating to whatever may be needed to understand the issue.  SQL Server Management Studio						15.0.18330.0
SQL Server Management Objects (SMO)						16.100.37971.0
Microsoft Analysis Services Client Tools						15.0.19040.0
Microsoft Data Access Components (MDAC)						10.0.19041.1
Microsoft MSXML						3.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.19041

**Comment by ryanmar** [comment]
Nevermind.  Known issue.
