### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by Rauzer** [MicrosoftDocs/sql-docs#2658]
There's a typo in the datatype of @pager_adress, page says its **NARCHAR(100)** while it should be **NVARCHAR(100)**

"[ @pager_address = ] 'pager_address' The pager address of the operator. This string is passed directly to the e-mail system. pager_address is narchar(100), with a default of NULL."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8530bea-ff51-0a36-c019-f1076bbc82c9
* Version Independent ID: 3465c4bc-2b02-fbc7-6cbd-be4928983ab1
* Content: [sp_add_operator (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-add-operator-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-add-operator-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-add-operator-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
#sign-off

**Comment by msebolt** [comment]
@Rauzer  Thank you for the feedback.

The documentation has been updated.
