### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ssaldi** [MicrosoftDocs/sql-docs#2659]
Might be useful to have some licensing info / reference here 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbe4ef3a-6282-5c51-5810-c6d63f3a0e1b
* Version Independent ID: 6d655e24-fc84-aad0-2422-2451cfb1ad34
* Content: [What is Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is?view=sql-server-2017)
* Content Source: [docs/azure-data-studio/what-is.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/what-is.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@ssaldi  Thank you for the feedback.

The documentation has been updated with a link to the [licensing info](https://docs.microsoft.com/sql/azure-data-studio/faq#what-can-i-do-with-azure-data-studio).
