### ISSUE TITLE
Indicate status of VSS on Linux

### ISSUE THREAD

**Issue by Guillaume-Fourrat** [MicrosoftDocs/sql-docs#2660]
Statement "You can take backups of databases from SQL Server 2017 on Linux with the same tools as other platforms" is not entirely correct as VSS is afaik not an option on Linux (and therefore there's no SQL Server VSS Writer service or equivalent on Linux), so VSS-based backup applications wouldn't be able to backup databases from a SQL Server running on Linux thru VSS.

That _might_ seem obvious since VSS is a Windows Framework =), but since SQL-VDI got its dedicated page, a single line on status of VSS for SQL on Linux would imho help avoid any ambiguity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa12baf4-fafe-817e-e3f2-1fe94a77a83e
* Version Independent ID: 6224becb-b6be-0bf4-5e7a-b75d7f6d07c4
* Content: [Backup and restore SQL Server databases on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-backup-and-restore-database?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-backup-and-restore-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-backup-and-restore-database.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@Guillaume-Fourrat Thank you for the feedback.

The documentation has been updated to better reflect the **different** options available vs. **all the same** options.

**Comment by MuthuramanD** [comment]
What are the changes Microsoft has made changes to SQL Server 2017 CU19 (February 2020) that is preventing the Plug-in for SQL Server (third-party )to protect SQL Server 2017 CU19?
