### ISSUE TITLE
VDI snapshot backups ?

### ISSUE THREAD

**Issue by Guillaume-Fourrat** [MicrosoftDocs/sql-docs#2661]
So would it be theoretically possible to create backup applications/agents on Linux that would rely on a native volume snapshot infrastructure (similar to VSS on Windows) and SQLVDI to allow *snapshot-based* backups for SQL Server on Linux ? 

("with Snapshot" option for VDI backup is part of TSQL, and is therefore parsed by the engine and the optional VDF_SnapshotPrepare flag is part of Features bits of VDConfig for which there is no indication of modification here)

Because there's no VSS framework on Linux, this scenario is more likely to be considered than on Windows (where going thru VSS and SQL Server writer offers a readily available and well-known higher level implementation).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4595da51-aab9-7454-4bd0-995aa2c3bab9
* Version Independent ID: f3c7a8ec-aa69-1d88-9020-1ff0e68ed5ca
* Content: [VDI Backup Specification - SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-backup-vdi-specification?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-backup-vdi-specification.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-backup-vdi-specification.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@Guillaume-Fourrat Thank you for the question.

Yes, though as stated, the [sample documentation](https://github.com/microsoft/sql-server-samples/tree/master/samples/features/sqlvdi-linux) is currently limited.  Perhaps try adding the issue to the [sql-server-samples repo](https://github.com/microsoft/sql-server-samples/issues).

Re-assigning to the author.

**Comment by MikeRayMSFT** [comment]
@Guillaume-Fourrat - thank you for the recommendation. This is not a capability we currently plan on supporting. #please-close

**Comment by MuthuramanD** [comment]
What are the changes Microsoft has made changes to SQL Server 2017 CU19 (February 2020) that is preventing the Plug-in for SQL Server (third-party )to protect SQL Server 2017 CU19?

**Comment by MikeRayMSFT** [comment]
Hi @MuthuramanD - would you mind submitting this on [Q&A](https://docs.microsoft.com/answers/products/sql-server) as this Git issue is closed.
