### ISSUE TITLE
Placeholders needing cleanup

### ISSUE THREAD

**Issue by nilopmsft** [MicrosoftDocs/sql-docs#2663]
Under the Recommended System Requirements there is a placeholder for more information regarding memory:

"For an optimal experience, please use the recommended system requirements. [Need update here to quantify memory]"

Needs to be updated or removed as it provides no benefit or looks like a draft of content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017#recommended-system-requirements)
* Content Source: [docs/azure-data-studio/download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@nilopmsft  Thank you for the feedback.

The documentation has been updated.
