### ISSUE TITLE
Typo for database master

### ISSUE THREAD

**Issue by jomccoy** [MicrosoftDocs/sql-docs#2664]
USE maser; **This should be master
GO
ALTER DATABASE tempdb
MODIFY FILE (NAME = tempdev, FILENAME = 'E:\SQLData\tempdb.mdf');
GO
ALTER DATABASE tempdb
MODIFY FILE (NAME = templog, FILENAME = 'E:\SQLData\templog.ldf');
GO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d5b65c4-3faa-3a6b-1a70-6e843a5c7069
* Version Independent ID: 4ad748c4-377c-9fe3-0554-f912a066cc4e
* Content: [ALTER DATABASE File and Filegroup Options (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-file-and-filegroup-options?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/alter-database-transact-sql-file-and-filegroup-options.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-database-transact-sql-file-and-filegroup-options.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@jomccoy  Thank you for the feedback.

The documentation has been updated.
