### ISSUE TITLE
CREATE EXTERNAL RESOURCE POOL (Transact-SQL)

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#2665]
@SQLBigEyesDad commented on [Sat Aug 03 2019](https://github.com/MicrosoftDocs/sql-docs.ko-kr/issues/110)

MAX_MEMORY_PERCENT =value
"... value is an integer with a default setting of 100...." 
--&gt; It seems default value is 20(not 100). It referenced SSMS or other Microsoft Document

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: a77e9e99-bc3a-92f8-d911-cae7072e8a16
* Version Independent ID: 3a77b0d7-ae97-1ebe-cbff-ade8ebd2e0c8
* Content: [CREATE EXTERNAL RESOURCE POOL(Transact-SQL) - SQL Server](https://docs.microsoft.com/ko-kr/sql/t-sql/statements/create-external-resource-pool-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-external-resource-pool-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ko-kr/blob/live/docs/t-sql/statements/create-external-resource-pool-transact-sql.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

---

@srvbpigh commented on [Sat Aug 03 2019](https://github.com/MicrosoftDocs/sql-docs.ko-kr/issues/110#issuecomment-517892272)

Hello, @SQLBigEyesDad
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here because the user is making a suggestion about the original documentation
best regards

**Comment by dphansen** [comment]
@msebolt I am clarifying this with the product team. Will keep you updated.

**Comment by dphansen** [comment]
I also saw a moniker issue and markdown issue with the article. This is being fixed in PR https://github.com/MicrosoftDocs/sql-docs-pr/pull/11432

**Comment by dphansen** [comment]
@SQLBigEyesDad Thank you for letting us know.

The default values are those from the default resource pool, which by default is 20%. 

I have changed the article and removed the default values for external pools. It will be published later today.
