### ISSUE TITLE
Manual SPN registration format

### ISSUE THREAD

**Issue by ghuser-sql** [MicrosoftDocs/sql-docs#2668]
The example for named instance is 
setspn -A MSSQLSvc/myhost.redmond.microsoft.com/instancename redmond\accountname  
should be 
setspn -A MSSQLSvc/myhost.redmond.microsoft.com:instancename redmond\accountname  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16136000-fc6d-9156-499a-c45bde264bc4
* Version Independent ID: ea9aacfc-8f27-563f-08c8-77ac4e941cff
* Content: [Register a Service Principal Name for Kerberos Connections - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@MikeRayMSFT Hi Mike, please formally Review PR 11427, which proposes to fix this Issue #2266 .
Thanks.  (GeneMi)

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/11427`

**Comment by MikeRayMSFT** [comment]
@ghuser-sql - thank you for the submission. I've signed off on PR 11427.

**Comment by demokert** [comment]
Is it possible to give an example for Group Managed accounts as well ? I'm using this on our SQL Servers. When I generate the setspn commands for them with this tool: [Microsoft® Kerberos Configuration Manager for SQL Server® ](https://www.microsoft.com/en-us/download/details.aspx?id=39046)

It says misplaced SPN afterwards.. so any advice or even an update for this tool would be highly appreciated.
