### ISSUE TITLE
Text cut off

### ISSUE THREAD

**Issue by JohnValenzuela** [MicrosoftDocs/sql-docs#2670]
'New in the Release' table, New Item SMO has details cut off.  All I see is "Assessment Extensions. See"  no link or other words after "See" 
Chrome Version 75.0.3770.142 (Official Build) (64-bit)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by msebolt** [comment]
@JohnValenzuela Thank you for the feedback.

The documentation has been updated.
