### ISSUE TITLE
Key & Certificate security in Sql server encryotion

### ISSUE THREAD

**Issue by jhakasjk** [MicrosoftDocs/sql-docs#2673]
As long as both keys & certificates are there in same database server, anyone who gets access to the server can always decrypt the data. Then where is the security? I might not understood it properly so posted this here to get proper idea to use encryption at database side and protect keys.

Ref: https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/encrypt-a-column-of-data?view=sql-server-2017

https://stackoverflow.com/questions/57381355/sql-server-encryption-via-symmetric-keys-aes-256

**Comment by MightyPen** [comment]
@jhakasjk Hello Kapil, Thank you for bringing this interesting question/challenge to our attention.

@VanMSFT Hi Van, Can you please consider whether our documentation article (`encrypt-a-column-of-data.md`) could or should directly anticipate the question that 'jhakasjk' is asking.  Thanks.

**Comment by jhakasjk** [comment]
> @jhakasjk Hello Kapil, Thank you for bringing this interesting question/challenge to our attention.
> 
> @VanMSFT Hi Van, Can you please consider whether our documentation article (`encrypt-a-column-of-data.md`) could or should directly anticipate the question that 'jhakasjk' is asking. Thanks.

Hi @MightyPen, 
Thanks for giving your attention to my concern. 
I'll be waiting for @VanMSFT to reply.

**Comment by VanMSFT** [comment]
@jhakasjk - Hi Kapil! The sample given in your referenced article is just a simple example. There are many ways to protect the certificate and keys used. Even if an intruder gets into the server, they need to know the certificate and key specifically used to encrypt those columns to decrypt them. This information is not stored in plain text.

If you are looking for more in-depth information regarding column encryption, I suggest you review our Always Encrypted articles: https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine?view=sql-server-2017#how-it-works

Thanks!

**Comment by jhakasjk** [comment]
@VanMSFT Thanks for reply. 
Actually my concern is even those keys are stored in encrypted manner but if someone comes to that server and open one stored procedure where I wrote to get some decrypted data, then they would know what function I am using. Then they can easily use same kind of queries to decrypted other data as well because anyhow keys/certificates are there.
From application layer, we're not passing the certificate or decryption key to decrypt the data.

**Comment by VanMSFT** [comment]
@jhakasjk - If an intruder can access the application and run queries on SQL Server, I would suggest that you secure the application. There are ways to encrypt Stored Procedures: https://docs.microsoft.com/en-us/sql/t-sql/statements/create-procedure-transact-sql?view=sql-server-2017

**Comment by jhakasjk** [comment]
@VanMSFT Again, problem remains same. As long as anyone can access database server, they can decrypt the data, stored procedure etc because keys/certificates are there only.

Is there a way in which we can store keys/certificates outside database server and pass to it at the time when we need to encrypt/decrypt the data?
Like store keys/certificate in Azure Vault and password database server at the time of encryption/decryption? 
Hoping that you're getting my concern.

**Comment by VanMSFT** [comment]
@jhakasjk - Have you looked at the article I pointed to about Always Encrypted?

**Comment by jhakasjk** [comment]
@VanMSFT Just read the complete article and this exactly what I was looking for. 
Thanks a lot. I am now reading implementation tutorial, I'll try to implement and post my findings. 
Thanks again for the help :)

**Comment by VanMSFT** [comment]
@jhakasjk - That's great, we're happy to help! Good luck!
