### ISSUE TITLE
What do the service level codes mean?

### ISSUE THREAD

**Issue by JoeMoyle** [MicrosoftDocs/sql-docs#2674]
Just what do the following codes mean and what is the difference between them?  A link would be helpful in this page if not an explanation.  S0, S1, S2, S3, S4, S6, S7, S9 or S12

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228c33b8-2005-40e1-584a-77c32b0433f8
* Version Independent ID: 96b3d88c-7343-48a5-37bb-854a94471be1
* Content: [sys.database_service_objectives (Azure SQL Database) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-service-objectives-azure-sql-database?view=azuresqldb-current#feedback)
* Content Source: [docs/relational-databases/system-catalog-views/sys-database-service-objectives-azure-sql-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-database-service-objectives-azure-sql-database.md)
* Service: **sql-database**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@JoeMoyle Hello Joe, Thank you for reaching out through our Feedback mechanism. We shall look into this Issue #2674 .

@stevestein Hi Steve, You might know of a good link to add to the article cited in this Issue. This issue is now assigned to you.

**Comment by stevestein** [comment]
@JoeMoyle - thanks for the feedback. I added some links to the article that should go live today.

The info you're looking for is here: https://docs.microsoft.com/en-us/azure/sql-database/sql-database-dtu-resource-limits-single-databases

Thanks.
