### ISSUE TITLE
Refresh Credentials No Longer Appearing

### ISSUE THREAD

**Issue by joelvega** [MicrosoftDocs/sql-docs#2675]
I have updated SSMS and I have noticed that the Refresh Credentials option is no longer appearing for Azure Analysis Services' connector menu. In the past I would be able to navigate to [Server Name] -> Database -> [Database Name] -> Connections -> right-click on connector name -> Refresh Credentials. This would display a prompt for my Microsoft Credentials. Now, the only way around this is to script the connector and add a password attribute to the JSON in plain text. I have colleagues that are still on an older version of SSMS and they still have this option. 

![image](https://user-images.githubusercontent.com/1467291/62573471-1cbe8880-b864-11e9-9acd-a430ab5927f2.png)

**Comment by MightyPen** [comment]
@joelvega Thank you for reaching out to us through our documentation Feedback mechanism.
However, this particular Feedback mechanism is limited to shortcomings in our documentation. Here we cannot process general Support type questions.

The following links might be of use to you in this case:

- [Support options for business users](https://support.microsoft.com/gp/support-options-for-business)
- [Contact Microsoft](https://support.microsoft.com/gp/contactus81?Audience=Commercial)
- [All the ways to get help](https://docs.microsoft.com/sql/sql-server/sql-server-get-help)

I am now Closing this Issue #2675 . 
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.
Thank you for submitting this Issue. We hope to hear from you again.

cc: @markingmyname Fyi.
