### ISSUE TITLE
Steps to set force encryption  = true/yes

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/sql-docs#2676]
how to set the flag to force encryption?
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-2017#to-configure-the-server-to-force-encrypted-connections

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 573f652e-46e9-d795-5e5b-5d65b6394a24
* Version Independent ID: 8cea560d-91b5-764f-87cc-92dcf4b58780
* Content: [Configure SQL Server on a Server Core Installation - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/configure-sql-server-on-a-server-core-installation?view=sql-server-2017#enable-tcpip-on-the-instance-of-)
* Content Source: [docs/database-engine/install-windows/configure-sql-server-on-a-server-core-installation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/configure-sql-server-on-a-server-core-installation.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by TiloGit** [comment]
see also #2672

**Comment by MashaMSFT** [comment]
Hi @TiloGit , thanks for contacting Microsoft! I'm sorry, I'm not sure I understand the intent of your question? The article you linked describes how to force encryption.. 

Would you mind clarifying what you're intended goal with encryption, and your question is?

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Ah, I see that Van answered you on the other Issue. Please let me know if anything further is needed? Otherwise, we'll close the Git Issue in a few business days.

Thanks!
Masha from the SQL Docs team

**Comment by MightyPen** [comment]
@TiloGit Hello,
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.  We will be promptly aware of any further @ notifications to us in this Issue webpage.

And because MashaMSFT considers this Issue #2676 to be answered and completed, it is my job to close completed Issues promptly, and so I now close this Issue.

Thank you for submitting this Issue. We hope to hear from you again.

cc: @MashaMSFT

**Comment by TiloGit** [comment]
Question is how to set the flag to force encryption server side on MS SQL running on Win Core without GUI. 
The other help article only list how to with GUI and Van claims that this is the only supported way. 

I miss information in this documentation **"Configure SQL Server on a Server Core Installation"** how to set the force encryption flag.
