### ISSUE TITLE
immediate_sync warning - context?

### ISSUE THREAD

**Issue by HakuAnnaruto** [MicrosoftDocs/sql-docs#2678]
Number 2. above, nicely warns: To avoid missing subscriber data, when using sp_addpublication with @allow_initialize_from_backup = N'true', always use @immediate_sync = N'true'.

However, Number 1. above, does NOT warn?  I think 1. should warn: @immediate_sync = N'true' as well b/c you can not assume that an existing publication is set: @immediate_sync = N'true'. If fact, by default our db's are set to false, b/c we want to ensure that our existing subscriptions are not NUKED by immediate sync, by simply adding, say, an article.

I tested sp_changepublication, @property=allow_initialize_from_backup, it has NO affect on immediate_sync; if (immediate_sync) is true it remains true, if it is false it remains false, regardless of setting: allow_initialize_from_backup.

So the context of the warning should be applicable to 1. and 2. ?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 964b4342-957a-8f52-d678-b664abbc85c1
* Version Independent ID: 806181ab-f040-f153-0ee4-92109897869f
* Content: [Initialize a Transactional Subscription from a Backup - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/initialize-a-transactional-subscription-from-a-backup?view=sql-server-2017)
* Content Source: [docs/relational-databases/replication/initialize-a-transactional-subscription-from-a-backup.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/initialize-a-transactional-subscription-from-a-backup.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @HakuAnnaruto , thank you for contacting Microsoft! Just to make sure I understand correctly,  you would like to add the following warning: 
![image](https://user-images.githubusercontent.com/32783170/62639679-e11fcf00-b8f4-11e9-86de-20c2db4a2a36.png)

To this point: 
![image](https://user-images.githubusercontent.com/32783170/62639697-ed0b9100-b8f4-11e9-823e-ef8081644f0e.png)

Am I understanding your intent correctly?

Thanks!
Masha from the SQL Docs team

**Comment by HakuAnnaruto** [comment]
In a word yes. It seems like it's relevant whether you have an existing publication or creating a new one.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MashaMSFT** [comment]
Hi @HakuAnnaruto , I just wanted to let you know I'm still looking into this :) Thanks for your patience!

- Masha from the SQL Docs team

**Comment by HakuAnnaruto** [comment]
Thank you. No worries!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MashaMSFT** [comment]
Hi @HakuAnnaruto , just wanted to give you an update and let you know I'm still researching this.

Thanks!
Masha from the SQL Docs team

**Comment by HakuAnnaruto** [comment]
Thanks for the update. Somebody sent me an email and said it was already done?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MashaMSFT** [comment]
@HakuAnnaruto , I am not sure what the context of that email is... It did not come from this Git Issue conversation, so I am not sure who emailed what. Sorry about that!

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @HakuAnnaruto , Thanks again for contacting Microsoft!  We've submitted a documentation change based on your suggestion, and it should be live at this point. Please let us know if there is anything more we can do for you? If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a wonderful rest of your day!
Masha from SQL Docs team
