### ISSUE TITLE
missing space between the strong tag and is checked

### ISSUE THREAD

**Issue by ccolella-mdc** [MicrosoftDocs/sql-docs#2679]
&lt;strong class="x-hidden-focus"&gt;Limit size of job history log&lt;/strong&gt;is checked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94adf3fd-769a-aa52-9dd4-c742a5f48237
* Version Independent ID: 2d14d44e-11ea-26b6-94e7-1684e6a365d6
* Content: [Resize the Job History Log - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/agent/resize-the-job-history-log?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/agent/resize-the-job-history-log.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/resize-the-job-history-log.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@ccolella-mdc,

It is not clear what you're asking.

Is there an issue with the article that you noticed?

thank you.

**Comment by ccolella-mdc** [comment]
There is a missing space on the page.

It is between the words “history log” and “is checked”.

One needs to be added after that strong tag and before the words “is checked”

**Comment by ccolella-mdc** [comment]
It looks like this on the page:

“history logis checked”

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
