### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Dean-McMillan** [MicrosoftDocs/sql-docs#2680]
Hi - please note that the column "startup_desc" doe not exist in the view.  Looks like the column is actually "startup_type_desc".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9286bfad-4cf6-7a06-a8d1-d8297a50ea40
* Version Independent ID: 76e9081a-b97e-3d8d-1d09-43663896c87d
* Content: [sys.dm_server_services (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-server-services-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-server-services-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-server-services-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@Dean-McMillan  Thank you for the feedback.

The documentation has been updated.
