### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by markg4030** [MicrosoftDocs/sql-docs#2682]
Should the last line of code in Step 3 be RESTORE DATABASE adb WITH RECOVERY; instead of RESTORE LOG adb WITH RECOVERY; ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae96822b-ab51-010e-6560-5803b9711b27
* Version Independent ID: 913eebb5-3a57-e1b3-79d1-34e6b0a9d50b
* Content: [Example: Online Restore of a Read-Write File (Full Recovery Model) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/example-online-restore-of-a-read-write-file-full-recovery-model?view=sql-server-2016#feedback)
* Content Source: [docs/relational-databases/backup-restore/example-online-restore-of-a-read-write-file-full-recovery-model.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/example-online-restore-of-a-read-write-file-full-recovery-model.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
Verifying.

**Comment by MikeRayMSFT** [comment]
Updating in a pull request as cited. Thank you @markg4030.
