### ISSUE TITLE
Do not show this starting page again...

### ISSUE THREAD

**Issue by AnthonyAtApex** [MicrosoftDocs/sql-docs#2687]
How do we turn this feature back on after checking the box and clicking next? Is this a setting in SSMS or maybe in the Windows Registry?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d89ecc7f-4705-dabe-9f70-2070d4aa19c9
* Version Independent ID: 9c991bd5-535c-03b5-d810-c1b2ca7e7cb4
* Content: [Import Flat File to SQL - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/import-flat-file-wizard?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/import-export/import-flat-file-wizard.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/import-flat-file-wizard.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by msebolt** [comment]
@AnthonyAtApex  Thank you for the feedback.

After running through the process with the box checked, I was able to rerun the process again and from the initial screen, select either **Previous** or **Introduction** in the left-hand pane.  This will bring you back to the startup screen where you again have the choice to show the page.

**Comment by AnthonyAtApex** [comment]
@msebolt I'm getting an full application crash and restart when attempting to use the "Import Flat File" with a specific Database, and when I had the splash screen available I received an error dialog popup. But since I canceled it, the popup never showed and SSMS just restarted. 

What I was able to do, based on your suggestion was attach to a different DB Server and Database and run the Import Flat File wizard, hit previous and uncheck the box.

![image](https://user-images.githubusercontent.com/45775482/62724317-b4e17c80-b9e0-11e9-8c22-d90d8d1a5cb3.png)

With the Import Flat File splash screen off, this error causes a full application restart. Should I file that as a bug?

Still curious, any idea where is the bit stored?

**Comment by msebolt** [comment]
@AnthonyAtApex Thank you for the followup.

That's an interesting scenario and I would post the issue to the [SQL Server forum](https://social.msdn.microsoft.com/Forums/sqlserver/home?category=sqlserver) to get the product team involved.  

You can also try asking about the registry bit there since it's outside our scope.  Access here is limited to GitHub repo only.

**Comment by pituach** [comment]
Good day,
The forum is not the right place to report a bug. You should submit a bug report via UserVoice at https://aka.ms/sqlfeedback
