### ISSUE TITLE
Using BCP and keeping NULL in last column

### ISSUE THREAD

**Issue by yehoshuadimarsky** [MicrosoftDocs/sql-docs#2689]
Hi, per this document I should be able to successfully upload NULLs into the SQL database using BCP. However, the example given (https://docs.microsoft.com/en-us/sql/relational-databases/import-export/keep-nulls-or-use-default-values-during-bulk-import-sql-server?view=sql-server-2017#sample-data-file) has the NULL value in some middle column. When I try this with a NULL value in the LAST column, it gives me an error :

SQLState = 22001, NativeError = 0
Error = [Microsoft][ODBC Driver 17 for SQL Server]String data, right truncation
SQLState = S1000, NativeError = 0
Error = [Microsoft][ODBC Driver 17 for SQL Server]Text column data incomplete

How can I insert NULLs that are in the last column?

To reproduce:
the text data file, 4 rows long:
series/observations,NCBCMDPMVCE,1945-10-01,43.0619630553
series/observations,NCBCMDPMVCE,1946-01-01,
series/observations,NCBCMDPMVCE,1952-01-01,52.6649432695
series/observations,NCBCMDPMVCE,1952-04-01,51.2479335424

The non-xml format file:
9.0
4
1    SQLCHAR    0    0    ","    1    web_endpoint    SQL_Latin1_General_CP1_CI_AS    
2    SQLCHAR    0    0    ","    2    series_id    SQL_Latin1_General_CP1_CI_AS    
3    SQLCHAR    0    0    ","    3    date    SQL_Latin1_General_CP1_CI_AS    
4    SQLCHAR    0    0    "\r\n"    4    value    SQL_Latin1_General_CP1_CI_AS    

BCP command:
bcp dbo.series_observations in &lt;DATA FILE PATH&gt; -S &lt;SERVER&gt; -d &lt;DATABASE&gt; -U &lt;USERNAME&gt; -P &lt;PASSWORD&gt; -f &lt;FORMAT FILE PATH&gt; -k

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eae9b7a4-fb32-cae7-e36a-cc683e997d03
* Version Independent ID: f0e8a957-a0cc-2bde-c0ec-9ccce494e85d
* Content: [Keep Nulls or Use Default Values During Bulk Import (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/keep-nulls-or-use-default-values-during-bulk-import-sql-server?view=sql-server-2017)
* Content Source: [docs/relational-databases/import-export/keep-nulls-or-use-default-values-during-bulk-import-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/keep-nulls-or-use-default-values-during-bulk-import-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @yehoshuadimarsky,

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

Thanks again for your submission!
Masha from SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @yehoshuadimarsky , thanks again for contacting Microsoft! Unfortunately, the scope of your question is a support request in nature, and as such, it's outside the documentation-related intent of this forum. However, having said that, using something like a ; as a row-terminator might help. The BULK INSERT command has an option to specify a row terminator, you would just need to add this to the sample command:

BULK INSERT dbo.myNulls
   FROM 'D:\BCP\myNulls.bcp'
   WITH (
      DATAFILETYPE = 'char',  
      FIELDTERMINATOR = ','
      ROWTERMINATOR = ';'  );


Please give that a shot and if that doesn't work, you may need to engage the community for further assistance. This article may assist with that: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017

I hope that helps and please let us know if we can be of further assistance from the documentation perspective. If not, we will proceed with closing out this Git Issue in a few business days. 

Thank you!
Masha from the SQL Docs team

**Comment by jacodegrootoodle** [comment]
BCP has a bug concerning empty (NULL) values in the last column that effects both the export and the import.

https://stackoverflow.com/questions/48446315/bcp-error-if-last-column-is-empty?rq=1

As a work around, you could add a dummy string at the end of your CSV file, e.g. "dummy" and then drop that column after the bcp import has completed.

**Comment by MashaMSFT** [comment]
Hi @jacodegrootoodle , thanks for contacting Microsoft and bringing this to our attention! Since this forum is intended for doc bugs, would you mind submitting a bug report directly to the product group so that it hits their radar, if it's not already? You can do so at [https://aka.ms/sqlfeedback](https://aka.ms/sqlfeedback).

Thanks!
Masha from the SQL Docs team

**Comment by jacodegrootoodle** [comment]
Masha,

I recommend you explicitly describe this bug in your documentation as a known issue. This bug has been around for many years and is unlikely going to be fixed as it would break backwards compatibility.
