### ISSUE TITLE
Repeat steps 1-4 on the subscriber for the distribution agent and the merge agent, changing the machine name to that of the subscriber.

### ISSUE THREAD

**Issue by alphabet5** [MicrosoftDocs/sql-docs#2690]
This cannot be completed on 'NODE2' as neither the distribution database exists or the AdventureWorks2012 database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab6b4b80-09aa-bd62-8f45-0c52235b2dd0
* Version Independent ID: 39e51ab8-0469-f8bb-d32a-96847b198229
* Content: [Tutorial: Prepare SQL Server for replication (publisher, distributor, subscriber) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/tutorial-preparing-the-server-for-replication?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/replication/tutorial-preparing-the-server-for-replication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/tutorial-preparing-the-server-for-replication.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @alphabet5 , thanks for contacting Microsoft! Ah, you're right, good catch! I'll need some time to fix this.

Thanks for your submission :)
Masha from the SQL Docs team
