### ISSUE TITLE
Get sqlpackage (preview) for Docker

### ISSUE THREAD

**Issue by GeorgeTsiokos** [MicrosoftDocs/sql-docs#2691]
Missing 'Get sqlpackage (preview) for Docker'

microsoft/mssql-docker#135 was created for this, but, it looks like it was closed after sqlpackage was made available as a file download. The issue is we need a docker image, not a file download.

If you look [at this customer-built Docker image](https://hub.docker.com/r/samuelmarks/mssql-server-fts-sqlpackage-linux), it has 1.6K pulls. We need a Microsoft Docker image for sqlpackage, and for it to be documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3df6af-9ac8-bc57-93dc-29ff713c1d3b
* Version Independent ID: 7624e2cc-7aa9-40dd-4015-3371ea2ea0a2
* Content: [Download and install sqlpackage - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-2017#feedback)
* Content Source: [docs/tools/sqlpackage-download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage-download.md)
* Product: **sql**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by WilliamAntonRohm** [comment]
@GeorgeTsiokos -- George, thank you for your feedback.

@pensivebrian -- Brian, please look into this issue 2691.

**Comment by pensivebrian** [comment]
Thanks for the feedback @GeorgeTsiokos. Creating docker images is on our roadmap, but we don't have a timeline for when this work will get done.

**Comment by Kannas24** [comment]
Instructions mentioned on the link are not even working for me on MAC. 
Error: sqlpackage: command not found.

**Comment by CarlRabeler** [comment]
@Kannas24 - links for the mac are working for me today. 
@GeorgeTsiokos creating docker image for tools is on roadmap
Closing this issue.

**Comment by markhobson** [comment]
If it helps, I have a Docker image for sqlpackage here: https://github.com/markhobson/docker-sqlpackage
