### ISSUE TITLE
Names of views

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#2692]
**[HARD TRANSLATION]**
@FrauDrDerWoche commented on [Thu Aug 08 2019](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/88)

This does not define which names are allowed for a view. Is there no character limit or are certain characters rejected?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3aca8415-3cf0-347d-e36e-25ac4232adcf
* Version Independent ID: 05ce00aa-acfe-6936-4f56-a66691ce2dcc
* Content: [Erstellen von Sichten - SQL Server](https://docs.microsoft.com/de-de/sql/relational-databases/views/create-views?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/views/create-views.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/relational-databases/views/create-views.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

---

@srvbpigh commented on [Thu Aug 08 2019](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/88#issuecomment-519513248)

Hallo, @FrauDrDerWoche

Vielen Dank für Ihr Feedback. 

Ihre Kommentare werden aktuell von uns geprüft. Wir melden uns bald bei Ihnen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team,
I'm moving this here because the user is requesting aditional information on the article

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please look into this issue 2692.

cc: @CeciAc

**Comment by stevestein** [comment]
@FrauDrDerWoche - Dieser Artikel sollte hilfreich sein: https://docs.microsoft.com/de-de/sql/relational-databases/databases/database-identifiers

Hoffe, dass dies Sinn macht, es ist von Bing Übersetzer!

@CeciAc - This article should be helpful: https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers

**Comment by stevestein** [comment]
#please-close
