### ISSUE TITLE
Data Transfer Options: formula for calculating virtual memory usage by a backup is incorrect

### ISSUE THREAD

**Issue by julesroussel3** [MicrosoftDocs/sql-docs#2694]
It should be "The total space used by the buffers is determined by: buffercount*maxtransfersize."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdc1049f-2eaa-cf47-38c8-ae83dd0955aa
* Version Independent ID: 544fb558-5df0-ff90-70dc-2d6776964ffa
* Content: [BACKUP (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/backup-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/backup-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/backup-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@julesroussel3 - thank you for your feedback.  I am looking into this update.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

**Comment by julesroussel3** [comment]
Thanks!
