### ISSUE TITLE
Documentation is not clear if feature is only available to a specific SQL Server version

### ISSUE THREAD

**Issue by bonskijr** [MicrosoftDocs/sql-docs#2697]
The current documentation makes it hard to know if a feature, in this case, PARSE function, is available in SQL Server 2014.  The current way to know is via a drop down at the left side above the TOC, which is easily missed. In this case, even though the feature is already available since 2012, it is made to look like this one is available only in 2017.

https://docs.microsoft.com/en-us/sql/t-sql/functions/parse-transact-sql?view=sql-server-2017&viewFallbackFrom=sql-server-2014

![image](https://user-images.githubusercontent.com/60311/62767062-6dcdb700-bac6-11e9-8f76-ebbfcfff4177.png)

> Note: Tested that the message will only appear for earlier versions of Sql Server 2014 and below

Compare the current with the previous, only front page though from wayback, but one can clearly see which version this is applicable to (see **APPLIES TO** )

![image](https://user-images.githubusercontent.com/60311/62767572-94d8b880-bac7-11e9-93a1-b7430a4997a9.png)

At the very least the message should at least link to the old one, the recommended version which links to the latest is unnecessary since it is currently linked to that one.

Also, I was only able to find the 2012 version but not the 2014 reference as well any 2014 T-SQL reference.

https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/hh213316%28v%3dsql.110%29

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a364b29c-2775-b79d-b519-2776b2a2b324
* Version Independent ID: 38c42f7b-615b-fa25-fe2f-c868fd9a85e6
* Content: [PARSE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/parse-transact-sql?view=sql-server-2017&viewFallbackFrom=sql-server-2014)
* Content Source: [docs/t-sql/functions/parse-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/parse-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@bonskijr -- thank you for your detailed feedback.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
@MightyPen - can you look at this - I'm not 100% sure what our options are with our versioning infrastructure?

**Comment by MightyPen** [comment]
@bonskijr Hello, There was a big change between the documentation for SQL Server 2014 and 2016.  Among many other changes, we implemented Versioning within single article files, starting in SQL 2016.
Overall the changes bring many benefits, and the ratio of benefits -to- drawbacks is nicely increasing as time moves ever forward. But for now the big changes that started for SQL 2016 documentation do include drawbacks.

As a result, it is common for a SQL 2016 article to _**not** have exactly the same \*.md file name_ as any 2014 \*.md file name has.  This is what sometimes prevents the Versioning drop-down list from switching from a 2016 article to a 2014 article.
However, it is also common for a 2016 article to have an exact path+name match in SQL 2014.  Both the Match and No-match cases are common.

---

I am now closing this Issue #2697.
Thank you for submitting this Issue. We hope to hear from you again.

cc: @MikeRayMSFT

**Comment by MightyPen** [comment]
closing.

**Comment by MightyPen** [comment]
@bonskijr Hi, A bit of follow-up on your Issue #2697. We recommend that SQL Server 2014 customers use the SQL Server 2016 documentation for Transact-SQL statement information.  Thanks.

- `https://docs.microsoft.com/sql/t-sql/language-reference?view=sql-server-2016`

cc: @MikeRayMSFT
