### ISSUE TITLE
Please document DEFAULT_DOMAIN() function

### ISSUE THREAD

**Issue by sqlserverexpert** [MicrosoftDocs/sql-docs#2700]
Please document the builtin system function DEFAULT_DOMAIN().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4b44feb-196b-8504-52cb-266a5b5cd6e2
* Version Independent ID: 850c1556-8ec7-e2eb-0b97-1d0e5f6df75f
* Content: [System Functions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/system-functions-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/system-functions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/system-functions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@sqlserverexpert -- Michael, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue 2700.

**Comment by MikeRayMSFT** [comment]
Reviewing with PM team

**Comment by sqlserverexpert** [comment]
Thank you.

While this information might be available from system views, system views require extra permission reducing the ability to run scripts under least privileges.  Also, this function offers greater simplicity.  Case in point:

Dm_server_registry

Negates need for xp reg read, but still complex query to parse out domain.

Default domain function has been around decades, discoverable in many ways. Typically by studying system procedures and/or features.

-Mike
Certified Master, SQL Server

On Sep 23, 2019, at 6:17 PM, Mike Ray <notifications@github.com<mailto:notifications@github.com>> wrote:


Reviewing with PM team

**Comment by MikeRayMSFT** [comment]
@sqlserverexpert - thanks for the comment, and please accept my personal apology for the late reply. During summer vacation I fell a bit behind on the issues I was tracking.

We reviewed the request and have decided not to document it at this time, but I recommend submitting the reasons you cite above at our product feedback site [https://feedback.azure.com/forums/908035-sql-server](https://feedback.azure.com/forums/908035-sql-server). 

Git issues is primarily for documentation feedback so a submission at that site will get a more comprehensive review from the product group.

Thanks you again.

**Comment by petervandivier** [comment]
Cross-posted to feedback forum as https://feedback.azure.com/forums/908035-sql-server/suggestions/42235297-default-domain

**Comment by ojintoad** [comment]
Updated link that I suspect is correct:

https://feedback.azure.com/d365community/idea/fcf18dd3-5f25-ec11-b6e6-000d3a4f0da0

Similar:

https://feedback.azure.com/d365community/idea/f24a2f72-4025-ec11-b6e6-000d3a4f0da0
