### ISSUE TITLE
Broken link to XE Tables page

### ISSUE THREAD

**Issue by aalamrangi** [MicrosoftDocs/sql-docs#2703]
[Enter feedback here]

Link broken at -
In This Section > SQL Server Extended Events Tables (Transact-SQL)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 311319ea-7b5d-3c12-aec2-72e400ae6d76
* Version Independent ID: 6a57fb1b-adcf-aa6f-b0bb-d42a71d96246
* Content: [System Tables (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/system-tables-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-tables/system-tables-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/system-tables-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@msebolt Hi Matthew, can you please fix the PR's 11473 warning, and then finalize this Issue #2703.

If necessary, you might be advised to create an explicit `<a name=` element in the .md file that is the target of the link?

`# <a name="anchor-system-tables"></a> System tables`

 . .

**Comment by msebolt** [comment]
@MightyPen The validation issue has been resolved and the PR merged.

@aalamrangi Thank you for the feedback.

Closing the issue now.
