### ISSUE TITLE
What is stats_flag?

### ISSUE THREAD

**Issue by awbloss** [MicrosoftDocs/sql-docs#2704]
Hi,

You talk about stats_flag but do not say what it is.

Thank you,

Andrew Bloss

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca588751-0df8-9d42-2698-26d953599eff
* Version Independent ID: 5429e364-55ac-894d-f218-58f937f19f31
* Content: [sp_autostats (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-autostats-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-autostats-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-autostats-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@awbloss -- Andrew, thank you for your feedback.

@stevestein -- Steve, please look into this issue 2704.

**Comment by stevestein** [comment]
@awbloss - thanks for raising this issue!

stats_flag is the value of the \@flagc parameter. The article has been updated to clarify this and should be live within 24 hours.

Thanks!

#please-close
