### ISSUE TITLE
Starting point for zero-length delete

### ISSUE THREAD

**Issue by mcb2k3** [MicrosoftDocs/sql-docs#2705]
"If _length_ is zero, insertion occurs before the first character in the string."

Maybe we're using different words, or I'm just confused, but I would say that insertion occurs at the _start_ position if _length_ is zero, and/or that no characters are deleted. "Before the first character in the string" seems to me to imply that _start_ will be ignored if _length_ is zero.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b3f468-5782-d8f1-089f-59527367cdd6
* Version Independent ID: 60885f1b-5125-f2c4-c3d3-1ccd65e0859b
* Content: [STUFF (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/stuff-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/stuff-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/stuff-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@mcb2k3 -- Megan, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue 2705.

**Comment by untilted-document** [comment]
I agree with the point raised by mcb2k3 - this advice about length being zero is confusing and wrong. If length is zero, no deletion of source string characters occurs. Insertion occurs at the index indicated by start. It's almost as though the person writing the doc thought "start position" meant "the beginning of the string" not "the index specified in the start argument"

**Comment by MikeRayMSFT** [comment]
@mcb2k3 - thanks for raising this issue. We're updating the article. 

> If *length* is zero, insertion occurs at *start* location and no characters are deleted.
