### ISSUE TITLE
Screenshot in the "Use the installation wizard" section is outdated.

### ISSUE THREAD

**Issue by tcdoan** [MicrosoftDocs/sql-docs#2706]
In the current CTP 3.2 we can choose to install either PolyBase or PolyBase Java separately but the current screenshot in this page is still from CTP 1.4 and does not have that option.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0f602a-88ea-16cc-a28f-d306de15d22b
* Version Independent ID: 81ed5850-ffbb-b1f8-4bd6-fede5eb5769b
* Content: [Install PolyBase on Windows - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-installation?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/polybase/polybase-installation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-installation.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@tcdoan Hello, We have assigned your Issue #2706 for investigation.  Thank you for bringing this concern to our attention.

**Comment by msebolt** [comment]
Since we're still in 2019 Preview, I've added this as a temporary note.

The screenshot should be updated after 2019 is released.
