### ISSUE TITLE
ALTER DATABASE ... WITH NO_WAIT

### ISSUE THREAD

**Issue by JodyLMeyer** [MicrosoftDocs/sql-docs#2707]
I am learning more about ALTER DATABASE [AdventureWorks2017] SET RECOVERY options. When I open the database properties dialog box, go to options page, change the Recovery model from Simple to Full, click the Script action to new query window, SQL Server 2017 SSMS v18.2, creates a script: 
   ALTER DATABASE [AdventureWorks2017] SET RECOVERY WITH NO_WAIT

I didn't see "WITH NO_WAIT" in the ALTER DATABASE documentation.  It would be nice if it was there.

Best regards,
Jody 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d76ab6e-5a3d-94eb-26f9-b2805b35ea85
* Version Independent ID: 2ac43d27-c318-3e32-1e78-55229975eb4e
* Content: [ALTER DATABASE SET Options (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/alter-database-transact-sql-set-options.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-database-transact-sql-set-options.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
In this file: https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options, search for "no_wait"

**Comment by CarlRabeler** [comment]
#please-close

**Comment by JodyLMeyer** [comment]
Augh! Sorry I missed that! Thank you for your quick response.
