### ISSUE TITLE
Example 2 has output instead of code

### ISSUE THREAD

**Issue by dariosuardiaza1** [MicrosoftDocs/sql-docs#2709]
The example 2 in this doc instead of showing the SQL for the example it has the code output as the reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96b577d2-6af6-c87e-336a-a6fb9b776697
* Version Independent ID: fcad9f44-92fa-dbed-81df-2a70368abe24
* Content: [Import JSON documents into SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/import-json-documents-into-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/json/import-json-documents-into-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/import-json-documents-into-sql-server.md)
* Product: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@dariosuardiaza1 -- thank you for your feedback.

@MightyPen -- please look into this issue 2709.

cc: @jovanpop-msft

**Comment by MightyPen** [comment]
Fixed this Issue #2709, by PR 11500.
- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/11500`

The output was mislabeled as another example.  I removed the H3 label.

@dariosuardiaza1 Thank you for bringing this mistake to our attention.  The fix will appear on live Docs within 24 hours.
Thank you for submitting this Issue. We hope to hear from you again.

cc: @WilliamAntonRohm
