### ISSUE TITLE
This description is incorrect, the verification test does not support: the aggregate column storage index now supports LOB columns (nvarchar(max), varchar(max), varbinary(max))

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#2717]
**TRANSLATED**

@sqlora2019 commented on [Wed Jul 03 2019](https://github.com/MicrosoftDocs/sql-docs.zh-cn/issues/112)
This description is incorrect and the validation test does not support: The aggregate column storage index now supports LOB columns (nvarchar(max), varchar(max), varbinary(max)).
Please check the function.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9547ecaa-d979-ee91-5657-9c302a829d38
* Version Independent ID: baf83ba3-4555-e3ba-123c-adab825200ba
* Content: [数据库引擎中的新增功能 - SQL Server 2017 - SQL Server](https://docs.microsoft.com/zh-cn/sql/database-engine/whats-new-in-sql-server-2017?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/whats-new-in-sql-server-2017.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/database-engine/whats-new-in-sql-server-2017.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

---

@CeciAc commented on [Wed Jul 03 2019](https://github.com/MicrosoftDocs/sql-docs.zh-cn/issues/112#issuecomment-508226107)

你好，@sqlora2019
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
This issue was Machine Translated

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- thank you for raising this feedback.

@rothja -- please process this issue 2717.

**Comment by rothja** [comment]
@CeciAc Thanks for passing this to us. I think the feedback is that the stated new feature about LOB columns does not actually work? I can try to check on this. Thanks!

**Comment by rothja** [comment]
@CeciAc Hello. I have not been able to test and validate this yet. I have opened a work item to track this work internally (1610832) and I will try to update this git issue when it is verified/resolved. Thank you for your patience.
