### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by RonaldHensbergen** [MicrosoftDocs/sql-docs#2720]
In the event_session_addres section there is a typo, the related view should be sys.dm_xe_sessions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54319505-a8a2-94ec-20da-6cdf4477d699
* Version Independent ID: 181df7fd-5faf-cf92-6892-fd904ddec7ee
* Content: [sys.dm_server_audit_status (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-server-audit-status-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-server-audit-status-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-server-audit-status-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@RonaldHensbergen -- thank you for your feedback.  I am incorporating it into the documentation.

**Comment by WilliamAntonRohm** [comment]
I have updated the documentation and it should be live by tomorrow.

**Comment by MightyPen** [comment]
@WilliamAntonRohm What is the PR number?

**Comment by WilliamAntonRohm** [comment]
@MightyPen -- https://github.com/MicrosoftDocs/sql-docs-pr/pull/11553; I'm not sure why its own cross-reference didn't show up in this issue 2720's timeline
