### ISSUE TITLE
Setting memory using mssql-conf not working on CentOS

### ISSUE THREAD

**Issue by Susanthab** [MicrosoftDocs/sql-docs#2724]
sudo /opt/mssql/bin/mssql-conf set memory.memorylimitmb 3328
systemctl restart mssql-server.service

And then check the max server memory in SQL Server properties but it is not changed to the new value.

**Comment by WilliamAntonRohm** [comment]
@Susanthab Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by MightyPen** [comment]
@Susanthab We need to close this Issue #2724 because we have not received the further information that we need.
However, you can still @ notify @WilliamAntonRohm and @msebolt if you can later provide the additional info, and they can reOpen this Issue at that time.

Thank you for submitting this Issue. We hope to hear from you again, on this or any new Issue.

**Comment by Susanthab** [comment]
@WilliamAntonRohm @msebolt I'm referring to the topic "Memory limit" in this link. https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-2017
That does not work as explained in the doc.

**Comment by WilliamAntonRohm** [comment]
@Susanthab -- Susantha, thank you for that information.

@VanMSFT -- Van, please look into this issue 2724.

cc: @MightyPen

**Comment by VanMSFT** [comment]
Hi @Susanthab! Thanks for providing more information on your issue to us. The article specifically states the following:

**mssql-conf is a configuration script that installs with SQL Server 2017 for Red Hat Enterprise Linux, SUSE Linux Enterprise Server, and Ubuntu.**

CentOS is not on that list and we do not guarantee that mssql-conf will work on that flavor of Linux. Please let us know if you have any concerns.

**Comment by Susanthab** [comment]
@VanMSFT I understand that. But generally CentOS behaves the same way as the RHEL. However, I get your point. It will be really useful if the SQL Server can support CentOS as well because its widely used in non-prod environments. Thanks.

**Comment by VanMSFT** [comment]
Thanks for your feedback, @Susanthab! I have provided your feedback to our Product Team. As you noted, CentOS has not been tested for supportability at the moment. As this forum is for documentation issues only, I will go ahead and close this issue. We appreciate you taking your time to contact Microsoft.
