### ISSUE TITLE
Note: Crashes SQL Management Studio when viewing SQL Agent logs

### ISSUE THREAD

**Issue by Alocyte** [MicrosoftDocs/sql-docs#2730]
I repeatedly crashed SQL Management Studio, losing all opened files, viewing SQL Agent error logs.
SQL Server Management Studio				15.0.18131.0
Microsoft Analysis Services Client Tools		15.0.1347.0
Microsoft Data Access Components (MDAC)	10.0.17134.1
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer				9.11.17134.0
Microsoft .NET Framework				4.0.30319.42000
Operating System						10.0.17134

Server: Standard 13.0.4001.0 (SQL 2016 SP1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc7174d6-85a9-acb3-f749-a940ccef7826
* Version Independent ID: 4a8c9832-76c4-c1e3-bf0a-321fa307600a
* Content: [View SQL Server Agent Error Log (SQL Server Management Studio) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/agent/view-sql-server-agent-error-log-sql-server-management-studio?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/agent/view-sql-server-agent-error-log-sql-server-management-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/view-sql-server-agent-error-log-sql-server-management-studio.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@Alocyte,

This seems more like a support issue than a documentation issue.

However, I can recommend that you try and uninstall the current version you have and download version 18.2, and see if that remedies the issue.  If not, please visit one of the following pages depending on your product or service.

[On Prem users](https://support.microsoft.com/en-us/supportforbusiness/productselection)
[SQL on Azure](https://ms.portal.azure.com/#home)
[Services Hub (Unified/premier customers)](https://serviceshub.microsoft.com/support/create/097a91e3-084a-46a8-b385-d5b07ffedcfe)

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by Alocyte** [comment]
HI

18.2 tested: open SQL Agent error log – crashes.

Is there an application crash log I supply for debug?

Regards
Victor Brink
Database Administrator | VIADATA (pty) ltd
tel: +27 21 674 3682 | cell: +27 83 718 3701 |email: victor@viadata.co.za<mailto:victor@viadata.co.za> |
www.viadata.co.za<http://www.viadata.co.za/>
