### ISSUE TITLE
SQL 2019 Big Data Cluster - HDFS Tiering ADLS Gen2 Incorrect

### ISSUE THREAD

**Issue by temalo** [MicrosoftDocs/sql-docs#2734]
In this document: _*docs/big-data-cluster/hdfs-tiering-mount-adlsgen2.md*_ , the instructions refer to blob storage, not ADLS Gen2 (with hierarchical storage). 

Specifically, the first bullet says to create a storage account with ADLS Gen2 (Hierarchical namespace) and then the second bullet says to add a blob. You cannot add blobs to an ADLS Gen2 account, you have to add a filesystem.

**Comment by NelGson** [comment]
That is right. Fixed. @msebolt @temalo

**Comment by rothja** [comment]
Closing as this has been fixed. Thank you!
