### ISSUE TITLE
SSMS ver 18.2 - Strange behavior when trying to copy from search and replace box

### ISSUE THREAD

**Issue by mr2001** [MicrosoftDocs/sql-docs#2738]
Steps to reproduce:

1. In SSMS ver. 18.2 create some query, for example select TOP 1000 rows from a table
2. Double click on a table field and press CTRL + H (attempting a copy/replace)
3. Highlight the top field in the Find and Replace box using the mouse (in this case, [Vendor_ID])
3. Press CTRL + C to copy it.

You now get this error:

![SSMS_error](https://user-images.githubusercontent.com/23727949/63121439-73b61300-bf72-11e9-9243-a12b63bb2628.png)

I saw it happening also in SSMS ver. 18. 1 but not in SSMS ver, 17

**Comment by MightyPen** [comment]
@mr2001 Hello, This Issues website is only for Documentation shortcomings. For product bugs, one of the following links might be helpful:

- [UserVoice - Suggestion to improve SQL Server?](https://feedback.azure.com/forums/908035-sql-server)
- [Support options for business users](https://support.microsoft.com/gp/support-options-for-business)
- [Contact Microsoft](https://support.microsoft.com/gp/contactus81?Audience=Commercial)
- [All the ways to get help](https://docs.microsoft.com/sql/sql-server/sql-server-get-help)

Thank you for contacting us. We hope to hear from you again.

I am now closing this Issue #2738 . 
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.

**Comment by MightyPen** [comment]
@markingmyname Hi Mark,  Just a minor note that a customer has reported a bug in an SSMS dialog. You might want to let the engineering team know about this report.  Thx, G
