### ISSUE TITLE
NYCTaxi_Sample.bak database can't be restored in SQL 2016 due to unsupported type columnstore index

### ISSUE THREAD

**Issue by dsun-edwards** [MicrosoftDocs/sql-docs#2739]
Hi, I tried to load NYCTaxi_Sample.bak into SQL 2016 but failed and it reports error, which suggests unsupported type columnstore index. Could you please help? Thanks very much. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37a1ef4c-d85a-4b53-b0c4-381159a48d17
* Version Independent ID: 3d16ce13-9835-16f1-8f99-5a0fd4ddaa0e
* Content: [Download NYC Taxi demo data and scripts for embedded R and Python - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/tutorials/demo-data-nyctaxi-in-sql?view=sql-server-2016#feedback)
* Content Source: [docs/advanced-analytics/tutorials/demo-data-nyctaxi-in-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/tutorials/demo-data-nyctaxi-in-sql.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dsun-edwards** [comment]
![image](https://user-images.githubusercontent.com/54071846/63122538-e89f4200-bf9e-11e9-869a-ee6e7029abab.png)
Could you please send me one with columnstore index disabled if possible? Thanks.

**Comment by MightyPen** [comment]
@dphansen  Hi David, Can you please look at this Issue #2739 .

(@dsun-edwards Hello, we will look at this Issue.  Thanks.)

**Comment by dphansen** [comment]
@dun-edwards My apologies for the delay. Columnstore indexes are supported in SQL Server 2016 SP1 and later. Please apply the latest service pack to your SQL Server and it should work. For more information, see the [RDBMS Scalability and Performance section in Editions and supported features of SQL Server 2016](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2016?view=sql-server-2017#RDBMSSP).
