### ISSUE TITLE
Documentation is unclear on how to get SSDT installed on build servers

### ISSUE THREAD

**Issue by W0GER** [MicrosoftDocs/sql-docs#2740]
The documentation does not provide information on how to get a build server setup with SSDT (or whatever MSFT is calling it with Visual Studio 2019) without having to install the full version of Visual Studio on the build server.

**Comment by msebolt** [comment]
@W0GER Thank you for the question.

Are you looking for [Analysis Services, Integration Services, and Reporting Services support](https://docs.microsoft.com/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017#install-analysis-services-integration-services-and-reporting-services-tools)?

If so, the description states a minimal version of Visual Studio is automatically installed if not present.

**Comment by W0GER** [comment]
Sorry, didn’t get a notification of the reply above. 

I looked over the article posted above but don’t really see a process for how to get this installed on a build server. There are vague statements 

Are we are back to having to install Visual Studio 2019 on the build server instead of just the tools?

**Comment by msebolt** [comment]
I see, the documentation does seem rather vague as to what the "best experience" means.  

Re-assigning to the author.

**Comment by markingmyname** [comment]
Hi, @W0GER.

Apologize for the delayed response.

With VS 2019, the old SSDT tools such as SSRS, SSAS, and SSIS are now installed through what they call VSIX now.  Microsoft devided to go this route to eliminate the confusion between using the separate SSDT install and VSIX which caused install and uninstall issues with VS 2017 and earlier. 

So to answer your direct question about do you need to install Visual Studio 2019, you will need to.

We apologize for any inconvenience this may cause.

Please let us know if you have any other questions.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
