### ISSUE TITLE
Visibility On Command Being Executed

### ISSUE THREAD

**Issue by abowen** [MicrosoftDocs/sql-docs#2743]
Importing a BACPAC into SQL Server using SSMS works every time.

However replicating the behaviour with the same BACPAC using either SqlPackage.exe or PS dbatools results in errors during importing users.

Can the documentation be updated with the command & options that's being run?

The ideal scenario would be SSMS has a diagnostics option that shows me this but I don't feel this page is appropriate for that feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946e0151-dfab-11da-7089-2f55926d1121
* Version Independent ID: 1e4a4cea-6111-35d8-b9c9-0f9516aee405
* Content: [Import a BACPAC File to Create a New User Database - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/import-a-bacpac-file-to-create-a-new-user-database?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/data-tier-applications/import-a-bacpac-file-to-create-a-new-user-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/import-a-bacpac-file-to-create-a-new-user-database.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@abowen Hi Andrew,  Thanks for submitting this Issue #2743.  It is now being Assigned for investigation.

@stevestein Hi Steve, Can you please process this Issue #2743 .

Thanks. G

**Comment by stevestein** [comment]
@abowen - thanks for raising this issue. I'm investigating your query and will reply when I have some info.

Thanks!
