### ISSUE TITLE
Equivalent to REPLACE?

### ISSUE THREAD

**Issue by SimonSellickSRA** [MicrosoftDocs/sql-docs#2744]
"Behavior of TRIM function with specified characters is identical to behavior of REPLACE function where characters from start or end are replaced with empty strings." - I don't think REPLACE can be restricted to the beginning and end of strings, it just replaces throughout.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfc6a4cd-b57c-8df6-221d-85aead960a91
* Version Independent ID: d0acb956-b718-d5d4-f422-52110f7a1242
* Content: [TRIM (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/trim-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/trim-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/trim-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@SimonSellickSRA Thank you for submitting this Issue #2744 . I see your point.  I think we can improve the writing in the 'Remarks' section.

---

@msebolt Hi Matthew,  Can you please create a fix PR, and in it do the following things to process and complete this Issue #2744 :

[1]
In the Remarks section, replace the existing text with the following text:

"By default, the TRIM function removes the space character from both the beginning and the ending ends of the string. This behavior is equivalent to `LTRIM(RTRIM(@string))`."

[2]
ReTest this Example B, to see whether its results really are as claimed (`# test`) in the article.  I am skeptical of the example.
`SELECT TRIM( '.,! ' FROM  '#     test    .') AS Result;`

[3]
I wonder whether TRIM also trims away the tab character (not just the space character)?  You could test that if you like.


Thanks. G
 . . . . .

**Comment by SimonSellickSRA** [comment]
Thanks Gene.

**Comment by msebolt** [comment]
The documentation has been updated, the results of example B were correct, but weren't being rendered properly to show the spaces in the output.

Also, beware when using tabs as it produces spaces in the `TRIM` output.  For example, using 4 tabs,
```
SELECT TRIM( '. ' FROM	'				#     test.') AS Result;
```

...produces an output with 4 spaces.

```
    #     test
```

**Comment by MightyPen** [comment]
I see no evidence that TRIM changes Tab characters in any way.

```
DECLARE
	@varychar11  varchar(32),
	@varychar12  varchar(32),
	@varychar23  varchar(32),
	@varychar24  varchar(32);

SET @varychar11 = char(09) + char(09) + 'A B';
SET @varychar12 = 't' + char(09) + char(09) + 'A B';
SET @varychar23 = TRIM(@varychar11);
SET @varychar24 = '1' + @varychar23;

PRINT @varychar11 + '   [ 11.  Original string, starts with tabs.]';
PRINT @varychar12 + '   [ 12.  Prepend a ''t'', just for visual clarity.]';
PRINT @varychar23 + '   [ 23.  TRIM of 11.]';
PRINT @varychar24 + '   [ 24.  Prepend a ''t'', just for visual clarity.]';

/*** Actual output:
		A B   [ 11.  Original string, starts with tabs.]
t		A B   [ 12.  Prepend a 't', just for visual clarity.]
		A B   [ 23.  TRIM of 11.]
1		A B   [ 24.  Prepend a 't', just for visual clarity.]
***/
```

cc: @msebolt

**Comment by msebolt** [comment]
Good call, use `char(09)` instead.  

Just the way SSMS handles text display.
