### ISSUE TITLE
List of referencing_class values is not exhaustive

### ISSUE THREAD

**Issue by brikken** [MicrosoftDocs/sql-docs#2745]
There are other possible values of referencing_class that is shown here. It's misleading that only some are mentioned without making it clear it's only an excerpt of the full list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ada44a9-e5a1-65b3-3bb2-9ebac215e5ab
* Version Independent ID: 470c3c15-d19d-e29f-c5f9-0824881deaac
* Content: [sys.sql_expression_dependencies (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-sql-expression-dependencies-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-catalog-views/sys-sql-expression-dependencies-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-sql-expression-dependencies-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@brikken - thanks for raising this issue. We've created an internal work item (1595947) to investigate and potentially update the article. 

We're going to close to this item and track with our internal work item. Feel free to continue to add any additional info or comments here.

Thanks again for pointing this out.
