### ISSUE TITLE
This needs to be updated to match the new settings style

### ISSUE THREAD

**Issue by RyanTaite** [MicrosoftDocs/sql-docs#2747]
There is no longer a right and left side of the settings.json file, you are only shown the one for your custom settings when making changes to something not doable through the settings window.

When you search for `dashboard` you get links to `Edit in settings.json` where you have to add the `dashboard.database.widgets` section of json yourself before you can add the new widgets described here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aea4ccb9-1337-4701-4d1b-ebbf251d508c
* Version Independent ID: c31b65be-3267-0130-26bf-1d9cafd13686
* Content: [Tutorial: Enable the table space usage sample insight widget - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/tutorial-table-space-sql-server?view=sql-server-2017)
* Content Source: [docs/azure-data-studio/tutorial-table-space-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/tutorial-table-space-sql-server.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by MightyPen** [comment]
@RyanTaite Hello Ryan, Thank you for bringing this inaccuracy to our attention.

@markingmyname Hi Mark, can you please process this Issue #2747. 
The Issue seems to concern the description of the UI in Step_4 being outdated, in its use of 'left' and 'right'?

> Step_4: To customize the dashboard.database.widgets settings you need to edit the dashboard.database.widgets entry in the USER SETTINGS section (the column in the **right** side). If there is no dashboard.database.widgets in the USER SETTINGS section, hover over the dashboard.database.widgets text in the DEFAULT SETTINGS column and click the pencil icon that appears to the **left** of the text and click Copy to Settings. If the pop-up says Replace in Settings, don't click it! Go to the USER SETTINGS column to the **right** and locate the dashboard.database.widgets section and advance to the next step.

Even if accurate, perhaps the above bulky paragraph should be divided into smaller Step_4 top node, with a subbullet or two for the rest of the text.

Thanks. G

**Comment by markingmyname** [comment]
@RyanTaite,

Thank you for bringing this to our attention.  I'll investigate and edit as needed.

Thank you.

**Comment by markingmyname** [comment]
@RyanTaite 

We have created a docs item internally to update all the ADS tutorial articles.

We realized their screenshots are a bit out of date, so we will work on updating all of them.

No planned ETA about when this will be completed, but we do have it on our radar.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by markingmyname** [comment]
This particular article should be updated by the end of the week.

thank you again for bringing this to our attention.

**Comment by RyanTaite** [comment]
Sorry this is a such a late reply, but wanted to say that I see the changes now and I appreciate it! Thank you!
