### ISSUE TITLE
SSMS 18.2 installed, but huge display problems

### ISSUE THREAD

**Issue by cdebel2005** [MicrosoftDocs/sql-docs#2749]
I've the latest display driver for my board, and when i open the app, i'm getting this.   When i move the mouse over stuff, it appear.   I don't think it's related to my display driver because it's the only application doing this.
https://ibb.co/z64H2mx

**Comment by msebolt** [comment]
@cdebel2005  We're sorry you're experiencing issues with the product.

However, the issues posted here are generally for documentation-related concerns only. For product support (or to file bugs), please use the [SQL Server forums](https://feedback.azure.com/forums/908035-sql-server).  

This issue has been moved to https://feedback.azure.com/forums/908035-sql-server/suggestions/38393446-ssms-18-2-display-problems.

**Comment by msebolt** [comment]
As posted from the forums,

```
Under TOOLS \ OPTIONS, uncheck "Use hardware graphics acceleration if available".

I don't know if my computer has hardware gfx acceleration, but it's just an On-Board GPU, so pretty basic. So maybe the "if available" is just not detecting the gfx acceleration capability properly.
```

Closing the issue now.
