### ISSUE TITLE
`WAITFOR` example is invalid

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#2753]
The example code for the `WAITFOR` restriction shows the following test:

`IF SYSTEM_USER='sa'`

This is an invalid scenario for two reasons:

1. The `sa` Login is not necessarily the only account with "sysadmin" permissions. Rather than checking the specific Login, an attacker would be more likely to check if the current Login is a member of the `sysadmin` fixed server role.
2. If the current security context truly did have "sysadmin" permissions, then Feature Restrictions would not restrict anything, hence `WAITFOR DELAY '00:00:05'` would still cause a 5-second delay.

Ideally, this entire feature would be removed along with this documentation and the page for `sys.sql_feature_restrictions` . The multiple reasons that this feature should be removed are detailed here: https://sqlquantumleap.com/2019/08/05/feature-restrictions-in-sql-server-2019-are-worse-than-useless-a-false-sense-of-security-and-wasted-opportunity/ . One of those reasons is that disabling `WAITFOR` doesn't prevent an attacker from causing a delay. A simple `WHILE` loop will accomplish that. And, there might even be other methods to do that. However, in the unfortunate event that this feature is not removed, please update the `WAITFOR` example to test for some other condition. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4c82b0b-c909-5049-4a32-d33dcb5c603b
* Version Independent ID: 4dc6b6db-e3aa-de6f-953e-3beb895cfdbd
* Content: [Feature Restrictions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/feature-restrictions?view=sqlallproducts-allversions#waitfor-feature-restriction)
* Content Source: [docs/relational-databases/security/feature-restrictions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/feature-restrictions.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @vainolo
* Microsoft Alias: **arib**

**Comment by rothja** [comment]
@srutzky Thank you for this feedback. I just checked and it appears that this article has been removed since you opened this feedback request. @barmichal @VanMSFT Could either of you confirm that this was in response to this feedback and whether there is any other context to this change? @srutzky, because the article no longer is live, I am going to close this issue, but please feel free to add to this thread and to look for any additional information fro @barmichal  and @VanMSFT. Thank you!

**Comment by srutzky** [comment]
@rothja (and @barmichal and @VanMSFT ): sounds good. I am curious to know, as you had inquired, if the removal was due to this particular issue (or my related blog post). I did just find that all documentation for "Feature Restrictions", including all mentions of it, were removed on Aug 28th via the following commit by @MikeRayMSFT :

https://github.com/MicrosoftDocs/sql-docs/commit/54c082a69e7adcd64a5e9c9a5936caa8668594b9

that just says: "Remove items".

**Comment by srutzky** [comment]
@rothja (and @barmichal and @VanMSFT and @MikeRayMSFT ): As far as I can tell, now that SQL Server 2019 has been officially released / RTM, the "restricted features" feature has been disabled, though not fully removed. You can still select from the system catalog view to get an empty result set (instead of a missing object error):

```sql
SELECT * FROM sys.sql_feature_restrictions;
```

However, the `sys.sp_add_feature_restriction` system stored procedure is not suggested via Intellisense, and attempting to execute it:

```sql
EXEC sp_add_feature_restriction N'WaitFor', N'USER', N'_TestAppAccount';
```

returns the following error:

> Msg 16305 Level 16 State 0 Line XXXXX  
> The database does not support feature restrictions.

**Comment by MikeRayMSFT** [comment]
@DavidTrigano

**Comment by DavidTrigano** [comment]
Hi @srutzky 

You're right, we disabled Feature Restriction when we released SQL Server 2019. You can still view the sql_feature_restrictions view, but it will always be empty.
