### ISSUE TITLE
Latitude

### ISSUE THREAD

**Issue by Mahdy1989** [MicrosoftDocs/sql-docs#2756]
"The following illustration shows a schematic view of the three-step decomposition process. In the pyramids, the dotted lines represent the boundaries of the four facets of each pyramid. Steps 1 and 2 illustrate the geodetic ellipsoid, using a green horizontal line to represent the '''equatorial longitude line''' and a series of green ***vertical lines to represent several latitude lines***. Step 1 shows the pyramids being projected over the two hemispheres. Step 2 shows the pyramids being flattened. Step 3 illustrates the flattened pyramids, after they have been combined to form a plane, showing a number of projected longitude lines. Notice that these projected lines are straightened and vary in length, depending on where they fall on the pyramids." 

The above paragraph is a little confusing, particularly because of the usage of the words latitude and longitude. 

Where it says '''equatorial longitude line''' I believe it should be '''equatorial latitude line'''. Why? Although this may be a very subtle difference, however, since you are referring to latitude-0 (the equator) I believe that word should be a latitude. Conceptually, we measure longitude in the -x/+x direction which is what I think you meant to communicate.

Also where there is ***vertical lines to represent several latitude lines***, these are longitude lines; although latitude is measured in the ( 0 to +90 ) and ( 0 to -90 ) which is in the -y/+y direction.

Notice where at the end in Step 3 you have explained, "Step 3 illustrates the flattened pyramids, after they have been combined to form a plane, showing a number of projected longitude lines." You have correctly referred to "a number of projected longitude lines".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cc755df-a7f8-a80f-8d59-cb36dd8e7125
* Version Independent ID: 75e6108e-c939-3a4f-2690-6c3429d4c7c2
* Content: [Spatial Indexes Overview - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-indexes-overview?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/spatial/spatial-indexes-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/spatial/spatial-indexes-overview.md)
* Product: **sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@Mahdy1989 -- Mahdy, thank you for your feedback.  I am looking into adding your suggestion to the documentation.

**Comment by WilliamAntonRohm** [comment]
@MladjoA -- Mladen, please review the above-mentioned [PR 11647](https://github.com/MicrosoftDocs/sql-docs-pr/pull/11647)

**Comment by WilliamAntonRohm** [comment]
@MladjoA -- please process this aging issue 2756.

**Comment by WilliamAntonRohm** [comment]
@MladjoA -- please review.
