### ISSUE TITLE
Aggregate Pushdown Requirements

### ISSUE THREAD

**Issue by SQLKiwi** [MicrosoftDocs/sql-docs#2757]
Please update this page to reflect the fact that previously unsupported types like real, float, datetimeoffset (any scale), and numeric with precision &gt; 18 are now supported in SQL Server 2017 (from which CU I don't know), for the COUNT aggregates, where the data fits in 64 bits at runtime.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3191c3a2-d412-96fc-c92c-9cf4ed4989fe
* Version Independent ID: e034baf2-b219-ed89-d9be-661c0b28c346
* Content: [Columnstore indexes - Query performance - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-query-performance?view=sql-server-2017)
* Content Source: [docs/relational-databases/indexes/columnstore-indexes-query-performance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/columnstore-indexes-query-performance.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@SQLKiwi -- Paul, thank you for your feedback.

@MikeRayMSFT -- Mike, please process this issue 2757,

**Comment by MikeRayMSFT** [comment]
@SQLKiwi - thanks for the submission. Reviewing with @pmasl

**Comment by MikeRayMSFT** [comment]
@SQLKiwi - I'm making one more deep dive to get an answer to this very good question. Thank you.

**Comment by MikeRayMSFT** [comment]
@SQLKiwi - thanks again for the good submission. We're working to confirm the correct CU and update the docs. Internal reference number. 1648807
