### ISSUE TITLE
Confusing options 

### ISSUE THREAD

**Issue by iampeterdaniels** [MicrosoftDocs/sql-docs#2758]
The page says "by creating a local server group, or a Central Management Server and one or more server groups, and one or more registered servers within the groups, and then querying the complete group.", which leads me to believe that I can do this just "by creating a local server group", but then it says "NOTE! Before you execute the following procedures, create a Central Management Server and server group." which tells me I have to use a central management server. I'm confused. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2311922d-7336-b2bf-1c05-4ce443a63640
* Version Independent ID: e2550458-4e2c-6b7a-287d-3627d4e8d08d
* Content: [Execute Statements Against Multiple Servers Simultaneously - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/register-servers/execute-statements-against-multiple-servers-simultaneously?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/register-servers/execute-statements-against-multiple-servers-simultaneously.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/register-servers/execute-statements-against-multiple-servers-simultaneously.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@iampeterdaniels -- Peter, thank you for your feedback.

@markingmyname -- Mark, please process this issue 2758.

**Comment by markingmyname** [comment]
Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

In the meantime, please visit [UserVoice](https://feedback.azure.com/forums/908035-sql-server) to see if this issue was already submitted to the product group.

**Comment by markingmyname** [comment]
@iampeterdaniels 

The wording is correct. You can query multi-server via local server group OR CMS.  Don't need both.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
