### ISSUE TITLE
This output doesn't match what I am seeing

### ISSUE THREAD

**Issue by Morshedk** [MicrosoftDocs/sql-docs#2760]
I am using SQL version

Microsoft SQL Server 2017 (RTM-CU16) (KB4508218) - 14.0.3223.3 (X64) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db9c6462-2a54-cfd9-91c4-e806e29aa450
* Version Independent ID: 95ea6cad-4a0d-6fd3-0536-522a50d8db11
* Content: [managed_backup.fn_backup_instance_config (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/managed-backup-fn-backup-instance-config-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-functions/managed-backup-fn-backup-instance-config-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-functions/managed-backup-fn-backup-instance-config-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@Morshedk -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
@Morshedk -- thank you for the additional clarification.

@MikeRayMSFT -- please look into this issue 2760.

**Comment by MikeRayMSFT** [comment]
Hi @Morshedk - The column names clearly changed between versions. I've created an item to track (Internal User Story 1605487).
Thank you for the submission.
