### ISSUE TITLE
subscribe_r   in  Arguments heading

### ISSUE THREAD

**Issue by EnjoyinMoss** [MicrosoftDocs/sql-docs#2762]
Under the Arguments heading, the 3rd argument [ @subscriber = ] is immediately followed by a mistake in the word subscriber ('subscribe_r').  There shouldn't be an underscore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a75de3d-208f-1c27-7f87-beb50624b097
* Version Independent ID: f68ccfe5-2234-e243-aee5-cee49e1a1843
* Content: [sp_dropsubscription (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-dropsubscription-transact-sql?view=sql-server-2017&viewFallbackFrom=sql-server-2014)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-dropsubscription-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-dropsubscription-transact-sql.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@EnjoyinMoss -- Simon, thank you for your feedback.  I am looking into updating the documentation.

**Comment by WilliamAntonRohm** [comment]
@EnjoyinMoss -- Simon, I have updated the documentation and it should be live by tomorrow.
