### ISSUE TITLE
Typo: to query external data in "Hadoop".

### ISSUE THREAD

**Issue by gitegite** [MicrosoftDocs/sql-docs#2764]
I think it should be changed to "Azure Blob Storage" according to the title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ab99ca-282b-6ace-6354-09a0d3ad97ad
* Version Independent ID: 7448fdc3-2a74-1811-38c5-aafcef2630e7
* Content: [Configure PolyBase to access external data in Azure Blob Storage - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-configure-azure-blob-storage?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/polybase/polybase-configure-azure-blob-storage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-azure-blob-storage.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@gitegite -- thank you for your feedback. I am looking into updating the documentation.

**Comment by gitegite** [comment]
@WilliamAntonRohm I also created a PR for this issue as well. https://github.com/MicrosoftDocs/sql-docs/pull/2765. But please feel free to update it separately 👍.

**Comment by WilliamAntonRohm** [comment]
@gitegite -- thank you for creating that PR.

@MikeRayMSFT -- Mike, please review  https://github.com/MicrosoftDocs/sql-docs/pull/2765.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- please process this aging issue 2764.

**Comment by rothja** [comment]
@gitegite @WilliamAntonRohm @MikeRayMSFT Thanks for the correction. I reviewed the PR, merged it, and will now close this git issue. Thank you!
