### ISSUE TITLE
Error Code 3110

### ISSUE THREAD

**Issue by waynenus** [MicrosoftDocs/sql-docs#2770]
If you forget remove the hyphens from the Client ID in Part 4 - 4 https://docs.microsoft.com/zh-cn/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-2016#part-iv-configure-includessnoversionincludesssnoversion-mdmd
You will get the error code 3110 in Part 4 - 5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 248641a9-2364-dcbf-b071-6df585b05bba
* Version Independent ID: bd00d184-ff67-3b36-2d8f-22d05538a92f
* Content: [SQL Server Connector Maintenance & Troubleshooting - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/sql-server-connector-maintenance-troubleshooting?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/encryption/sql-server-connector-maintenance-troubleshooting.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/sql-server-connector-maintenance-troubleshooting.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @aliceku
* Microsoft Alias: **aliceku**

**Comment by WilliamAntonRohm** [comment]
@waynenus -- thank you for your feedback.

That section (part 4-4) has an Important note saying "You must remove the hyphens from the Client ID."

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
