### ISSUE TITLE
No Info On Changing Usage Collection

### ISSUE THREAD

**Issue by BoCoKeith** [MicrosoftDocs/sql-docs#2780]
During install of SSMS, there is a link to this page that is supposed to have information on changing usage collection by SSMS.  To obvious way to get to it from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a6234d9-12fa-7843-5abf-79cefc84b167
* Version Independent ID: fff09871-4ea5-aa72-6365-1539b2ed03bc
* Content: [SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@BoCoKeith  Thank you for the feedback.

The documentation has been updated.

Please see the [SQL Server privacy statement](https://docs.microsoft.com/sql/sql-server/sql-server-privacy) for information on general diagnostic data collection or [Configure usage and diagnostic data collection ](https://docs.microsoft.com/sql/sql-server/usage-and-diagnostic-data-configuration-for-sql-server) on how to adjust your settings.
