### ISSUE TITLE
Page Title in the Nav tree and breadcrumbs path

### ISSUE THREAD

**Issue by ZStoner** [MicrosoftDocs/sql-docs#2782]
The title of this page seen in the left-hand Nav tree, or the breadcrumbs path, says...
"Format nested output with PATH ode"  ....   instead of   "...PATH Mode"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 678c7ae3-295a-912b-9a1a-9bc9414178fd
* Version Independent ID: 99132c6a-7986-6403-b191-15b4ada93a76
* Content: [Format Nested JSON Output with PATH Mode (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/format-nested-json-output-with-path-mode-sql-server?view=sql-server-2017)
* Content Source: [docs/relational-databases/json/format-nested-json-output-with-path-mode-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/format-nested-json-output-with-path-mode-sql-server.md)
* Product: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by msebolt** [comment]
@ZStoner Thank you for the feedback.  

The documentation has been updated.
