### ISSUE TITLE
Lack of space between Events and column

### ISSUE THREAD

**Issue by Wesley-Snipes** [MicrosoftDocs/sql-docs#2784]
[Enter feedback here]

Lack of space between Events and column.

To filter events in a trace
In the Trace Properties or Trace Template Properties dialog box, click the Events Selection tab.

The Events Selection tab contains a grid control. The grid control is a table that contains each of the traceable event classes. The table contains one row for each event class. The event classes may differ slightly, depending on the type and version of server to which you are connected. The event classes are identified in the Eventscolumn of the grid and are grouped by event category. The remaining columns list the data columns that can be returned for each event class.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a23c538-d888-ce21-461f-dbb6ef9c1ebb
* Version Independent ID: 227b84ce-d7ca-c580-e992-53ecbd6788f1
* Content: [Filter Events in a Trace (SQL Server Profiler) - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sql-server-profiler/filter-events-in-a-trace-sql-server-profiler?view=sql-server-2017#feedback)
* Content Source: [docs/tools/sql-server-profiler/filter-events-in-a-trace-sql-server-profiler.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sql-server-profiler/filter-events-in-a-trace-sql-server-profiler.md)
* Product: **sql**
* Technology: **profiler**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@Wesley-Snipes Thank you for the feedback.

The documentation has been updated.
