### ISSUE TITLE
Add a link to events.xsd

### ISSUE THREAD

**Issue by tomuxmon** [MicrosoftDocs/sql-docs#2785]
Would be great if there was a link to [events.xsd](http://schemas.microsoft.com/sqlserver/2006/11/eventdata/events.xsd) and information on EVENT_INSTANCE_% mapping to each event plus TSQL statement that can cause it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a14d613f-8491-824f-38a8-552f6086a12b
* Version Independent ID: 1e8bd781-30f0-60b2-5b6e-44cc0e1b1630
* Content: [DDL Events - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/triggers/ddl-events?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/triggers/ddl-events.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/triggers/ddl-events.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@tomuxmon Hello. Thank you for the feedback, and apologies for the long delay. This is good feedback, but at this time we don't have the resources to researching and updating the event mapping as you suggest. However, it is good that you opened this up to track the request. Can you tell me a little bit more about how you use that information in your scenario? Thank you!

**Comment by davepend** [comment]
@tomuxmon, what you are looking for is here: 

https://docs.microsoft.com/en-us/sql/relational-databases/triggers/ddl-event-groups?view=sql-server-2017

**Comment by rothja** [comment]
@davepend Thank you for the additional link! @tomuxmon, does this help?

**Comment by rothja** [comment]
@tomuxmon I'm going to close this issue per the previous thread. But please feel free to add more feedback or suggestions on how we can improve this experience. Thank you!
