### ISSUE TITLE
Not ALL comments are retained in query_store_query_text

### ISSUE THREAD

**Issue by bradzelenak** [MicrosoftDocs/sql-docs#2789]
This article says that comments are included in the query text, but this other article says only comments within the query are retained, not those preceding the query. https://docs.microsoft.com/en-us/sql/relational-databases/performance/how-query-store-collects-data?view=sql-server-2017

It seems the other article is a more correct representation, as we discovered when unsuccessfully trying to find query tags from EF Core (which end up as comments preceding the query text) in query_store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 029a199e-d59c-38a3-b3b5-c46dc7f5b853
* Version Independent ID: c5c07e93-7738-ee5a-4b40-2af3481b0b5e
* Content: [sys.query_store_query_text (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-query-store-query-text-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-catalog-views/sys-query-store-query-text-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-query-store-query-text-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@bradzelenak Thank you for the feedback.

The documentation has been updated.

**Comment by simeyla** [comment]
Such a shame! 
@bradzelenak did you ever find a way to see query tags in the query store.
