### ISSUE TITLE
Wrong reference to sys.sysdatabases

### ISSUE THREAD

**Issue by ByronBarton** [MicrosoftDocs/sql-docs#2790]
This page should reference sys.databases rather than the obsolete sys.sysdatabases.  Ditto for the "See Also" link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebaaa371-7e23-921a-44f4-37c79d1ef26c
* Version Independent ID: b61040c5-abc7-a030-10cb-856ad4f11d21
* Content: [sp_replicationdboption (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-replicationdboption-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-replicationdboption-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-replicationdboption-transact-sql.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@ByronBarton  Thank you for the feedback.

I hesitate to make this change, as even though `sys.sysdatabases` is in the process of being phased out, I don't see the equivalent **category** column mentioned in the article in the `sys.databases` table.

Re-assigning to the author.
