### ISSUE TITLE
Can't SELECT TOP rows when joining by STIntersects

### ISSUE THREAD

**Issue by gguille077** [MicrosoftDocs/sql-docs#2791]
A query like this
SELECT TOP 100 polyTable.[PolygonID], pointTable.[PointID]
FROM PointTable
INNER JOIN polyTable ON polyTable.Geom.STIntersects(pointTable.Geom) = 1

returns a message
Msg 6522, Level 16, State 1, Line 33
A .NET Framework error occurred during execution of user-defined routine or aggregate "No extended information available.": .

There are overlapping polygons, meaning the join may end with more than one record on the polygon side; and by removing the TOP clause it works. Any idea on how to solve it or workaround it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77910f94-8a85-ba1d-8945-21a596f99f3b
* Version Independent ID: a2bc84f5-8603-f01e-a032-59afdbafb178
* Content: [STIntersects (geometry Data Type) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geometry/stintersects-geometry-data-type?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/spatial-geometry/stintersects-geometry-data-type.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/spatial-geometry/stintersects-geometry-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@gguille077 -- thank you for your feedback.

@MladjoA -- please look into this issue 2791.

**Comment by MladjoA** [comment]
@gguille077 , thanks for reporting this issue.
I tried to repro it, but had no luck.
Would it be possible to share some obfuscated/depersonalized data set with us where repro is possible?

Thanks

**Comment by gguille077** [comment]
The attached code doesn't fail, yet it's a text extraction of the Geom columns (one polygon and the points to intersect) which fail. In the original server, both Geom columns are Geometry type in their tables.

[SELECT TOP 100 Geom reproducible example.txt](https://github.com/MicrosoftDocs/sql-docs/files/3717841/SELECT.TOP.100.Geom.reproducible.example.txt)

**Comment by MladjoA** [comment]
Thanks @gguille077 , may I also ask you for the following information:
- Version of SQL Server you are using
- Execution plans with and without TOP 100 clause.

**Comment by MladjoA** [comment]
@gguille077 , kind reminder for sharing the SQL Server version and execution plans. Thanks.

**Comment by MladjoA** [comment]
@gguille077 , alternatively, can you try TOP 100 version with MAXDOP 1 hint? That would help us confirm whether this is known issue already fixed in Azure SQL DB.

**Comment by gguille077** [comment]
Sorry for the delay in the response, here goes everything you asked for.
. Version of the SQL server 14.0.3223.3.
. The execution plans with and without the TOP clause: [plans.zip](https://github.com/MicrosoftDocs/sql-docs/files/3856018/plans.zip).
. Effectively, with the MAXDOP 1 hint looks like not throwing the error.

**Comment by cawrites** [comment]
@gguille077  Based on your response and the feedback you received this is no longer an issue. It appears by implementing the suggestion you have stated it is "not throwing the error." At this time we will be moving forward in closing this issue. Please feel free to contact us again in the future regarding any content related issue. Thank You.

**Comment by cawrites** [comment]
#sign-off

**Comment by cawrites** [comment]
#please-close
