### ISSUE TITLE
Are there any benefits specific to SQL on Azure VM, ie that differ from using a data drive on Azure storage?

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/sql-docs#2793]
Regarding the section "Why use": Are there any benefits specific to having database files stored as Azure blobs compared to stored on a data drive in Azure storage for SQL on Azure VM? Most/all of the benefits listed under "Why use" apply the same more or less to using a data drive in Azure storage. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb6076ae-3679-3a8e-6530-5f0db78b3f06
* Version Independent ID: 335044f8-f561-6f8d-b878-f3fde1664e19
* Content: [SQL Server data files in Microsoft Azure - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/sql-server-data-files-in-microsoft-azure?view=sql-server-2016)
* Content Source: [docs/relational-databases/databases/sql-server-data-files-in-microsoft-azure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/sql-server-data-files-in-microsoft-azure.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by softwarecraft** [comment]
I [posed the same question](https://dba.stackexchange.com/questions/246127/azure-blob-storage-container-vs-vm-managed-disk-for-sql-on-azure-vm-database-fil) on Stack.

**Comment by WilliamAntonRohm** [comment]
@softwarecraft -- John, thank you for your feedback and for posting your question.

@MikeRayMSFT -- Mike, please look into this issue 2793.

**Comment by MikeRayMSFT** [comment]
@minetokusaltug  - any thoughts on this one?

**Comment by MikeRayMSFT** [comment]
@rajeshsetlem

**Comment by MikeRayMSFT** [comment]
I have an open PR (12907) to resolve. Waiting for PM review.
