### ISSUE TITLE
Missing reserved word URL

### ISSUE THREAD

**Issue by EnjoyinMoss** [MicrosoftDocs/sql-docs#2794]
I cannot find an entry for "URL" on this page however the various Azure migration tools are flagging it as a migration blocker.  Should it be listed here?

Note it is listed as part of the BACKUP command as found in the t-sql example here:
https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-2017#Examples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f79ec4df-5309-60fc-1c20-f32b219fb9b9
* Version Independent ID: 6ee85c34-9a2c-e007-dcda-fb6016b98119
* Content: [Reserved Keywords (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/language-elements/reserved-keywords-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/reserved-keywords-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@EnjoyinMoss -- Simon, thank you again for your feedback.

@rothja -- Jason, please look into this issue 2794.

**Comment by rothja** [comment]
@EnjoyinMoss Hello, and apologies for the delay. The definition of a reserved keyword on this page is one that cannot be used in Transact-SQL statements except with a delimiter. So the following fails:

```sql
select 'test' as ADD
```

But you can use URL in this example:

```sql
select 'test' as URL
```

So it would appear from testing that URL is not a reserved keyword in the same way. I'm not sure why it is getting flagged. But you could put delimiters around it possibly just to be clear:

```sql
select 'test' as [URL]
```

Let me know if this makes sense or if you have any other feedback. At this time I am going to close the issue.
