### ISSUE TITLE
Valid from what version of SQL Server?

### ISSUE THREAD

**Issue by MartinLBuchanan** [MicrosoftDocs/sql-docs#2796]
Your doc pages typically indicate the version of SQL Server that introduced a feature. For example, SQL Server 2008, SQL Server 2012, etc. Please add that information to this page and to any similar pages that lack it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2de0e28-b19a-b269-4af4-c6c1a375edb8
* Version Independent ID: 4cf18494-0c02-2dbd-334e-2880e2f02f7f
* Content: [TRY_CAST (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/try-cast-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/try-cast-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/try-cast-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
Thanks @MartinLBuchanan - due to a recent redesign the specific versions were removed. We're working on finding the right way to call this out across the documentation set. (Internal issue: 1605663)
