### ISSUE TITLE
Initialize the Kubernetes master on this machine - KUBE_VERSION error message / suggestions

### ISSUE THREAD

**Issue by Peter-Msft** [MicrosoftDocs/sql-docs#2799]
In this section:
KUBE_VERSION=1.11.3
sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --kubernetes-version=$KUBE_VERSION

The kubeadm init will run if the version is 1.11.3. In my case, I got this error: 
this version of kubeadm only supports deploying clusters with the control plane version &gt;= 1.13.0. Current version: v1.11.3 

I had to use KUBE_VERSION=1.15.0 for it to work.

I think it would be good to mentioned in the documentation that the user may need to adjust the parameter based on their version, or even better, if possible have the script automatically grab the latest version number.

(the same issue may apply to KUBE_DPKG_VERSION=1.15.0-00 - declared in earlier 4. Prepare the machine section on this same page)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8bb827-4819-7b2d-490a-071f6b7b57a2
* Version Independent ID: 65b90b91-5946-b2d1-b97a-537bc9b014ca
* Content: [Configure Kubernetes with kubeadm - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-with-kubeadm?view=sqlallproducts-allversions#configure-the-kubernetes-master)
* Content Source: [docs/big-data-cluster/deploy-with-kubeadm.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-with-kubeadm.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
@Peter-Msft - thank you. Investigating

**Comment by MikeRayMSFT** [comment]
Resolving in pull request
