### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by Peter-Msft** [MicrosoftDocs/sql-docs#2800]
Section 5. Configure the cluster and the Kubernetes dashboard.

The Kubernetes dashboard link in the following command is broken:

kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

error: unable to read URL "https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml", server reported 404 Not Found, status code=404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8bb827-4819-7b2d-490a-071f6b7b57a2
* Version Independent ID: 65b90b91-5946-b2d1-b97a-537bc9b014ca
* Content: [Configure Kubernetes with kubeadm - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-with-kubeadm?view=sqlallproducts-allversions#configure-the-kubernetes-master)
* Content Source: [docs/big-data-cluster/deploy-with-kubeadm.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-with-kubeadm.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
Thank you for pointing this out @Peter-Msft  - the correct link is: https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
