### ISSUE TITLE
Where is SQL Native Client 11.0 service?

### ISSUE THREAD

**Issue by ma17961363** [MicrosoftDocs/sql-docs#2805]
When the Force protocol encryption is changed to "yes" and click on OK button the prompt says it will have any effect unless restarting the service! Which service?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 085b5d0f-f4f9-342f-7c7d-aa38c63248a7
* Version Independent ID: 9a713381-18b3-85d4-aa23-ec447af811f3
* Content: [SQL Server Native Client Configuration Properties (Flags Tab) - SQL Server](https://docs.microsoft.com/en-us/sql/tools/configuration-manager/sql-server-native-client-configuration-properties-flags-tab?view=sql-server-2017)
* Content Source: [docs/tools/configuration-manager/sql-server-native-client-configuration-properties-flags-tab.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/configuration-manager/sql-server-native-client-configuration-properties-flags-tab.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@ma17961363,

Sorry for the delayed response.

I am not 100% sure what you are referencing.  In the article, it does not reference a "service."

Is this message coming from a popup on your machine?

**Comment by markingmyname** [comment]
@ma17961363 

You can open the SQL Server Configuration Manager and see the SQL Native Client 11.0 Configuration option.  Is this what you are trying to get to?

Please let us know.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
