### ISSUE TITLE
One more step needed

### ISSUE THREAD

**Issue by erickson55345** [MicrosoftDocs/sql-docs#2817]
I had a login whose default database was renamed.  When I looked at the login properties, on the User Mappings tab, all the permissions carried over to the new name seamlessly.  However, on the General Tab, the Default Database was now blank.  The new name didn't carry over.  I had to manually reset the Default Database to the new name.  You can argue that this update should be part of the ALTER process, but in the meantime, know that you have to make this change manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8670bba-cc1d-49ec-aca2-e1433c1be45a
* Version Independent ID: cc4a360b-5663-a619-d992-c7866221df43
* Content: [Rename a Database - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/rename-a-database?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/databases/rename-a-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/rename-a-database.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please look into updating the documentation.

**Comment by stevestein** [comment]
@erickson55345 - thanks for opening this issue. I added info to the rename db article per your suggestion. The update should appear in the live article later today.

Thanks!
