### ISSUE TITLE
"When converting float or real values to decimal or numeric, the decimal value will never have more than 17 decimals. Any float value < 5E-18 will always convert as 0" is wrong

### ISSUE THREAD

**Issue by victren** [MicrosoftDocs/sql-docs#2827]
code:

declare @f float(53) = 0.123456789123456719;
select @f as 'f';
declare @d as decimal(38,37) = @f;
select @d as 'd';
go

result:

f
----------------------
0.123456789123457

(1 row affected)

d
---------------------------------------
0.1234567891234567144076450517786724959

(1 row affected)

**Comment by victren** [comment]
declare @f float(53) = 0.123456789123456744;
select @f as 'f';
declare @d as decimal(38,37) = @f;
select @d as 'd';
go

f
----------------------
0.123456789123457

(1 row affected)

d
---------------------------------------
0.1234567891234567421632206674075860064

(1 row affected)

**Comment by srutzky** [comment]
@victren , @msebolt , @MikeRayMSFT : it appears that this behavior changed in SQL Server 2016. Until that version, the behavior matches the documentation (and to be clear, based on "Converting float and real data" section on the "float \& real" page, this only ever affected float literals expressed in scientific notation):

```sql
-- Decimal notation works just fine:
SELECT CONVERT(DECIMAL(38, 37), 0.0000000000000000000000000000000002862);
-- 0.0000000000000000000000000000000002862


-- Scientific notation no el worko:
DECLARE @Dec AS DECIMAL(38,37) = 4E-18;
SELECT @Dec AS 'Dec';
-- 0.0000000000000000000000000000000000000

SELECT CONVERT(DECIMAL(38, 37), 5E-18);    -- 0.0000000000000000100000000000000000000
SELECT CONVERT(DECIMAL(38, 37), 4.99E-18); -- 0.0000000000000000000000000000000000000
SELECT CONVERT(DECIMAL(38, 37), 4E-18);    -- 0.0000000000000000000000000000000000000
SELECT CONVERT(DECIMAL(38, 37), 5E-19);    -- 0.0000000000000000000000000000000000000
```
The results in the T-SQL comments above were based on testing in SQL Server 2012 and 2014 (and presumably prior versions behaved similarly).

But, starting with SQL Server 2016 (and also tested on 2017 and 2019), this was no longer a restriction:

```sql
-- Scientific notation now works:
DECLARE @Dec AS DECIMAL(38,37) = 4E-18;
SELECT @Dec AS 'Dec';
-- 0.0000000000000000040000000000000002862

SELECT CONVERT(DECIMAL(38, 37), 5E-18);    -- 0.0000000000000000050000000000000003577
SELECT CONVERT(DECIMAL(38, 37), 4.99E-18); -- 0.0000000000000000049899999999999996406
SELECT CONVERT(DECIMAL(38, 37), 4E-18);    -- 0.0000000000000000040000000000000002862
SELECT CONVERT(DECIMAL(38, 37), 5E-19);    -- 0.0000000000000000005000000000000000358
```

I'll see if I can update these two pages.

**Comment by srutzky** [comment]
Actually, my first test for "Decimal notation" is flawed as that is converting a Decimal literal to `DECIMAL`. I re-did the test using a `FLOAT` datatype (just like @victren 's original test) and found the true nuance:

```sql
DECLARE @Float FLOAT = 5E-18;
DECLARE @Decimal AS DECIMAL(38,37) = @Float;
SELECT @Float AS 'Float', @Decimal AS 'Decimal';
-- 5E-18     0.0000000000000000100000000000000000000 (2014 and prior)
--           0.0000000000000000050000000000000003577 (2016 and newer)

SET @Float = 4.99E-18;
SET @Decimal = @Float;
SELECT @Float AS 'Float', @Decimal AS 'Decimal';
-- 4.99E-18     0.0000000000000000000000000000000000000 (2014 and prior)
--              0.0000000000000000049899999999999996406 (2016 and newer)

SET @Float = 0.000000000000000005000000000000000;
SET @Decimal = @Float;
SELECT @Float AS 'Float', @Decimal AS 'Decimal';
-- 5E-18     0.0000000000000000000000000000000000000 (2014 and prior)
--           0.0000000000000000050000000000000003577 (2016 and newer)

SET @Float = 0.000000000000000005000000000000001;
SET @Decimal = @Float;
SELECT @Float AS 'Float', @Decimal AS 'Decimal';
-- 5E-18     0.0000000000000000100000000000000000000 (2014 and prior)
--           0.0000000000000000050000000000000011281 (2016 and newer)
```

The final two cases both show `5E-18` as the float value, but clearly the underlying value is not identical as one of them converts to 0 and the other converts to a non-zero value.

**Comment by srutzky** [comment]
Updated both pages via PR #2951 .

Take care,
Solomon...
https://SqlQuantumLeap.com/

**Comment by victren** [comment]
thanks, this change will have effect on code migration from old version to SQL2016, cheers

**Comment by srutzky** [comment]
@victren You're welcome 😺 .
