### ISSUE TITLE
Limitation across databases.

### ISSUE THREAD

**Issue by martynlesbirel** [MicrosoftDocs/sql-docs#2828]
If you have two Databases, say A and B. Both have the same table value type with the same name in each and one (Database A) is using the table value directly in a stored procedure. All will appear to be well. However if you try to access the table type and it's related stored procedure via a synonym from another database, Database B you'll get errors saying it can't be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3cf0abc-6058-9d8f-53cc-577e790c314d
* Version Independent ID: 85390619-52e7-2146-04c5-eb36fe07e1d0
* Content: [Use Table-Valued Parameters (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/use-table-valued-parameters-database-engine?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/tables/use-table-valued-parameters-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/use-table-valued-parameters-database-engine.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@msebolt Hi Matthew, maybe a note about this limitation could be added into the following SYNONYM article? I am unsure:

- `https://docs.microsoft.com/sql/t-sql/statements/create-synonym-transact-sql`

**Comment by msebolt** [comment]
@MightyPen  Sounds good, a note has been added to the documentation.
