### ISSUE TITLE
Missing version number in sentence

### ISSUE THREAD

**Issue by CarrieAnne** [MicrosoftDocs/sql-docs#2838]
I think you're missing the version number in the following sentence:
GEOMETRY_AUTO_GRID tessellation is the default tessellation scheme for the geometry data type for SQL Server and later.
(Possibly should be SQL Server 2012?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cc755df-a7f8-a80f-8d59-cb36dd8e7125
* Version Independent ID: 75e6108e-c939-3a4f-2690-6c3429d4c7c2
* Content: [Spatial Indexes Overview - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-indexes-overview?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/spatial/spatial-indexes-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/spatial/spatial-indexes-overview.md)
* Product: **sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@CarrieAnne -- thank you for your feedback.  I am looking into it.

**Comment by WilliamAntonRohm** [comment]
@MladjoA -- Mladen, please let me know the appropriate versions of SQL Server for these two sentences:

#### Geometry Grid Tessellation Scheme  
 GEOMETRY_AUTO_GRID tessellation is the default tessellation scheme for the geometry data type for SQL Server **XXXX** and later.  GEOMETRY_GRID tessellation is the only tessellation scheme available for geometry data types in SQL Server **XXXX**.

**Comment by MladjoA** [comment]
@WilliamAntonRohm -- William, it should be 2012 and 2008 respectively. Thanks!

**Comment by WilliamAntonRohm** [comment]
@CarrieAnne -- I have updated the documentation and it should be live by tomorrow.

@MladjoA -- you're welcome.
