### ISSUE TITLE
Syntax colouring on example

### ISSUE THREAD

**Issue by jpomfret** [MicrosoftDocs/sql-docs#2839]
On example `D. Using a database-scoped DDL trigger` starting on the `RAISERROR` line the syntax is not the appropriate colours. 

![image](https://user-images.githubusercontent.com/981370/63938756-8c72fe00-ca33-11e9-9fb9-980490a13614.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8add50-414a-a033-6fc0-84de1c7735f2
* Version Independent ID: 8f2f3149-7035-b3d4-6f09-a6eadd015e24
* Content: [CREATE TRIGGER (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-trigger-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-trigger-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-trigger-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by jpomfret** [comment]
The issue seems to be with using the word `drop` within the text string. Not sure if there is a way to escape that within a code block?
Could also change the text to use remove which isn't a keyword.

**Comment by WilliamAntonRohm** [comment]
@jpomfret -- Jess, thank you for your feedback.  I am looking into it.

**Comment by WilliamAntonRohm** [comment]
@jpomfret -- Jess, I have updated the documentation and it should be live by tomorrow.
