### ISSUE TITLE
Reference to fs.default.name property

### ISSUE THREAD

**Issue by mezankhaja** [MicrosoftDocs/sql-docs#2840]
The fs.default.name property has been deprecated. The new property is fs.defaultFS.

See: http://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/DeprecatedProperties.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e450abc6-2dbd-8f6c-423c-52aca37a2b06
* Version Independent ID: 4aff678a-6db1-a438-9aca-bb4b4d49bc27
* Content: [CREATE EXTERNAL DATA SOURCE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-external-data-source-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-data-source-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@mezankhaja -- thank you for your feedback.  I am looking into it.

**Comment by WilliamAntonRohm** [comment]
@mezankhaja --  I have updated the documentation and it should be live by tomorrow.
