### ISSUE TITLE
What Types/SKUs of storage are supported and recommended?

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/sql-docs#2841]
Please indicate if all types and SKUs of Azure Page Blob Storage are support and/or recommended. I don't see any mention of this in this page. The tutorial shows an example using Standard_RAGRS but what about Premium vs Standard and GRS, RA-GRS, GZRS or RA-GZRS?

Also for pricing and referring to https://azure.microsoft.com/en-ca/pricing/details/storage/page-blobs/, is it "Page Blobs used as Unmanaged Disks" or "Page Blobs (Non-disks)".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb6076ae-3679-3a8e-6530-5f0db78b3f06
* Version Independent ID: 335044f8-f561-6f8d-b878-f3fde1664e19
* Content: [SQL Server data files in Microsoft Azure - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/sql-server-data-files-in-microsoft-azure?view=sql-server-2016)
* Content Source: [docs/relational-databases/databases/sql-server-data-files-in-microsoft-azure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/sql-server-data-files-in-microsoft-azure.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@softwarecraft -- John, thank you for your feedback.  We are looking into it.

**Comment by MikeRayMSFT** [comment]
@softwarecraft - I'm still following up on this. Will get back to you soon.

**Comment by MikeRayMSFT** [comment]
@minetokusaltug - any comments on this?

**Comment by MikeRayMSFT** [comment]
Thank you for the submission. We're working internally on a doc update. Reference (1648809).
