### ISSUE TITLE
is_nullable reports incorrect value

### ISSUE THREAD

**Issue by JerrodV** [MicrosoftDocs/sql-docs#2844]
I have a stored procedure that takes a required @tID int parameter. In Sql Server 2014 when I query this parameter it gives me a 1 in the is_nullable column despite it not taking a null value. 
ALTER PROCEDURE [dbo].[Terminals_Set]
	@tID int,
	@tName varchar(25) = NULL, ...

(Select * from sys.parameters where name='@tID')
(the final value is the is_nullable field and is not correct which is breaking my code generator)
210099789	@tID	1	56	56	4	10	0	0	0	0	0	NULL	0	0	1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ced26fd5-2da0-74fd-800f-c7a193338276
* Version Independent ID: aeb21de9-67d3-87b3-f3c0-1b2e529bf169
* Content: [sys.parameters (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-parameters-transact-sql?view=sql-server-2017&viewFallbackFrom=sql-server-2014)
* Content Source: [docs/relational-databases/system-catalog-views/sys-parameters-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-parameters-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@JerrodV -- thank you for your feedback,  We are looking into it.

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please raise this issue at [Contact Microsoft](https://support.microsoft.com/gp/contactus81?Audience=Commercial).

If I find a more specific SQL Server product bug reporting link, I will add it here.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by WilliamAntonRohm** [comment]
@JerrodV -- [please try this link](https://aka.ms/sqlfeedback).

**Comment by MightyPen** [comment]
@jerrodV Hi Jerrod, William and I have done more research, and the following link can be used by any customers to report bugs (or important feature requests) directly to the SQL Server product team.

- [SQL Feedback, at aka.ms](https://aka.ms/sqlfeedback)
    - `https://aka.ms/sqlfeedback` , takes you to so-called "User Voice"
    - (Currently resolves to `https://feedback.azure.com/forums/908035-sql-server`.)

&nbsp;

- [UserVoice - Suggestion to improve SQL Server?](https://feedback.azure.com/forums/908035-sql-server)
    - `https://feedback.azure.com/forums/908035-sql-server`


cc: @WilliamAntonRohm @msebolt 
 . .
