### ISSUE TITLE
BIG Note (About support on Azure and AWS managed instances)

### ISSUE THREAD

**Issue by zerg2k** [MicrosoftDocs/sql-docs#2845]
All sqlclr functions and aggregates are crippled by the new .Net security model for SQL2017+ if you want to use them in managed instances.

 I hope this helps people save time and effort with less surprises.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a861430-2277-5e5e-db65-16aebb041283
* Version Independent ID: 2928021b-c23c-0e75-8aa9-0b45ea02efb6
* Content: [Requirements for CLR User-Defined Aggregates - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-functions/clr-user-defined-aggregates-requirements?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/clr-integration-database-objects-user-defined-functions/clr-user-defined-aggregates-requirements.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/clr-integration-database-objects-user-defined-functions/clr-user-defined-aggregates-requirements.md)
* Product: **sql**
* Technology: **clr**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@zerg2k -- thank you for your feedback.  We are looking into it.

**Comment by WilliamAntonRohm** [comment]
@rothja -- Jason, please consider adding this information to the documentation.

**Comment by rothja** [comment]
@zerg2k I apologize that you've run into this problem with aggregates and the CLR. Can you provide a little more information? This only apples to Managed Instance? Can you give me an example for reference? Thank you for sharing this if it helps others, but I'd like to research and put a note in the article if possible to make this even more clear (or find another solution that we could document to get around the issues you're seeing).

**Comment by zerg2k** [comment]
How about this post:
[CLR on SQL2017](https://joeydantoni.com/2017/04/19/sqlclr-in-sql-server-2017/)

Or how about a "series"

[“SQLCLR vs. SQL Server 2017” Series](https://sqlquantumleap.com/2017/08/07/sqlclr-vs-sql-server-2017-part-1-clr-strict-security/)

Or how about [Amazon response and silent Azure drop out of the feature](https://stackoverflow.com/questions/57162012/sqlclr-support-on-aws-sql-server-2017-rds)

This is so massive that it is my believe that it should have a more prominent place in the documentation.

**Comment by rothja** [comment]
@zerg2k Thank you for the additional information. I need to look more at what we should be saying in the docs to help make this more clear. I also need to work with the product team to review. I appreciate you pointing this out. Because of this, I have created an internal work item (1658982) to track the work and follow up in January. I am going to close out this git issue, but I will try to respond on it when we create some content to address your concerns. Thanks, again, and I'm sorry about the lack of content to address the issues you found with CLR in SQL.
