### ISSUE TITLE
Errors occur when the user does not have VIEW SERVER STATE permission.

### ISSUE THREAD

**Issue by mdell-seradex** [MicrosoftDocs/sql-docs#2846]
In this case the following errors are raised even though the function succeeds.

> Msg 300, Level 14, State 1, Procedure "trigger name here", Line ## [Batch Start Line 0]
> VIEW SERVER STATE permission was denied on object 'server', database 'master'.
> Msg 297, Level 16, State 1, Procedure "trigger name here", Line ## [Batch Start Line 0]
> The user does not have permission to perform this action.

This prevents using this function inside triggers.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ef80f24-0d7d-217d-f014-d9c24dc57bc0
* Version Independent ID: dd246fd2-e967-ef77-1dc4-0d05d0caebb3
* Content: [sys.dm_exec_input_buffer (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-ca/SQL/relational-databases/system-dynamic-management-views/sys-dm-exec-input-buffer-transact-sql?view=sql-server-linux-2017#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-exec-input-buffer-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-input-buffer-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by srutzky** [comment]
FYI, regarding getting instance-level permissions, please see:

[Safely and Easily Use High-Level Permissions Without Granting Them to Anyone: Server-level](https://sqlquantumleap.com/2018/02/15/safely-and-easily-use-high-level-permissions-without-granting-them-to-anyone-server-level/)

Take care,
Solomon...
https://SqlQuantumLeap.com/

**Comment by mdell-seradex** [comment]
I don't really understand how that is a solution.  That is more a workaround to what appears to be an undocumented bug.
The documentation says it works for the less privileged users as long as they only access their information, but the error being thrown basically means that this is untrue in any useful automated way.
It does NOT say that users can really only do this within management studio because virtually everywhere else will receive and report the error.
It does NOT say that users can do this by not actually doing it but instead going through additional steps that if not done correctly would give access to information not specific to that user and could compromise security.

The documentations actually says "On SQL Server, if the user has VIEW SERVER STATE permission, the user will see all executing sessions on the instance of SQL Server; otherwise, the user will see only the current session."  This gives no indication that the error I mentioned WILL be returned upon completion of the trigger, stored procedure, or function when the user does NOT have the VIEW SERVER STATE permission.

**Comment by stevestein** [comment]
@mdell-seradex - thanks for raising this issue. We're currently investigating...

**Comment by mdell-seradex** [comment]
Thank you very much.

**Comment by srutzky** [comment]
@mdell-seradex Ah, sorry. I misunderstood the context. Yes, you are correct. I can reproduce the issue using the following T-SQL:

```sql
USE [tempdb];
CREATE LOGIN [InpBufTest] WITH PASSWORD = 'Show Me The Buffer!';
CREATE USER [InpBufTest] FOR LOGIN [InpBufTest];

EXECUTE AS LOGIN = N'InpBufTest';
SELECT USER, SYSTEM_USER;

DBCC INPUTBUFFER(@@SPID); -- works
SELECT * FROM sys.dm_exec_input_buffer(@@SPID, CURRENT_REQUEST_ID()); -- error:
/*
Msg 300, Level 14, State 1, Line XXXXX
VIEW SERVER STATE permission was denied on object 'server', database 'master'.
Msg 297, Level 16, State 1, Line XXXXX
The user does not have permission to perform this action.
*/
REVERT;

DROP USER [InpBufTest];
DROP LOGIN [InpBufTest];
```

Given that `DBCC INPUTBUFFER` does work, that implies that `sys.dm_exec_input_buffer()` should also work for a User to see their own data (which is what you are saying), so it appears that the documentation is correct, but there is a bug in `sys.dm_exec_input_buffer()`. I see that you did post this to the FeedBack site:

[sys.dm_exec_input_buffer(@@SPID, NULL) returns "VIEW SERVER STATE permission was denied on object 'server', database 'master'."](https://feedback.azure.com/forums/908035-sql-server/suggestions/38485429-sys-dm-exec-input-buffer-spid-null-returns-vi)

I just voted for that issue. I also added a comment with the same repro code as shown above, and linked back to this issue.

Take care,
Solomon...
https://SqlQuantumLeap.com/

**Comment by mdell-seradex** [comment]
Interesting, I thought that DBCC INPUTBUFFER previously could not be run by those that did not have high level privileges, such as sysadmin or VIEW SERVER STATE.  Perhaps this has changed or the documentation has, or our understanding of them...
DBCC INPUTBUFFER also has a size limitation.  Hopefully sys.dm_exec_input_buffer() does not have that same limitation.

**Comment by srutzky** [comment]
> DBCC INPUTBUFFER also has a size limitation. Hopefully sys.dm_exec_input_buffer() does not have that same limitation.

I haven't tested prior versions to see if permissions behavior is the same or different, but I did test max length and yes, `DBCC INPUTBUFFER` is limited to `NVARCHAR(4000)` while `sys.dm_exec_input_buffer` is `NVARCHAR(MAX)`. I was able to get a batch fully returned from `sys.dm_exec_input_buffer` that was > 6000 character / 12k bytes.

**Comment by rothja** [comment]
@mdell-seradex Thanks for bringing this to our attention and to @srutzky for the input/conversation. @stevestein is out of the office for several weeks, so I'm going to ask @CarlRabeler if he can take a look at this and see what doc changes might be necessary. I apologize for the delay. Thank you! #reassign:CarlRabeler

**Comment by CarlRabeler** [comment]
@mdell-seradex @srutzky So, you are basically saying this, correct?

Running this DMV outside of SQL Server Management Studio against SQL Server without VIEW SERVER STATE permissions (such as in a trigger, stored procedure, or function) throws a permission error on the master database.

**Comment by mdell-seradex** [comment]
Technically speaking I think it throws a warning, but every data access technique I have used still treats it as an error, and it can happen on any database.
From what I recall, the message that you get within SQL Server Management Studio when run without VIEW SERVER STATE permissions is what is treated as an error by all data access technologies I have used.  e.g. ADODB, ADO.NET

**Comment by mdell-seradex** [comment]
Note that I personally feel that this is a bug in SQL Server, but until it is addressed, if it ever is, then this behaviour should be documented.

**Comment by CarlRabeler** [comment]
updated docs

#please-close

**Comment by mdell-seradex** [comment]
I am unsu

**Comment by mdell-seradex** [comment]
Thank you for the documentation update.I am not sure if you meant to include the warning twice.

**Comment by mdell-seradex** [comment]
Thank you for the documentation update.
I am not sure if you meant to include the warning twice.
Also, regarding the wording, I wonder if some readers would mistake this as an issue that only occurs when retrieving a SQL statement that was executed against the master database, and would think that it does not occur in other databases.

Thank you again.

**Comment by CarlRabeler** [comment]
Any suggestions for improving this warning would be appreciated. Please feel free to click Edit in the upper right hand corner and submit your edit suggestions. Thanks.
