### ISSUE TITLE
Limitations and Restrictions

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/sql-docs#2847]
Is the Limitations and Restrictions applicable to SQL Managed Instance as well?
I assume it's true since I learned that there's no difference between Azure SQL Database and SQL Managed Instance except supporting UTF-8 for collation, but I cannot find specific information for Managed Instance in here and the following page.   Thanks.

Azure SQL Database managed instance T-SQL differences | Microsoft Docs
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-transact-sql-information#collation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 683853cb-ea06-2b91-7606-6a313408e335
* Version Independent ID: 3f630abf-7950-5698-990e-331290ebb521
* Content: [Set or Change the Database Collation - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-database-collation?view=sql-server-2017#Restrictions)
* Content Source: [docs/relational-databases/collations/set-or-change-the-database-collation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/set-or-change-the-database-collation.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@kazshi - thanks for opening this issue. This entire article is related to SQL Database managed instance. Can you clarify your question or what you're running into?

Thanks!

**Comment by stevestein** [comment]
@kazshi - to clarify, while you can set the collation at the time of creation, for a SQL database, or SQL Database managed instance, you cannot change the collation after creation. The same restriction applies.

**Comment by kazshi** [comment]
@stevestein
1) I was not sure if the the entire article is related to SQL Database managed instance since Azure SQL Managed Instance is not listed in the APPLIES TO: (top of the page).
2) The Note says "Collation cannot be changed after database has been created on Azure SQL Database." (I assume it's about database, not server or instance) however actually Azure SQL Database collation can be changed (but SQL Managed Instance database collation cannot be changed) as far as I verified.

**Comment by stevestein** [comment]
@kazshi - thanks for the clarification. Apologies for any confusion: The page you opened the issue on: https://docs.microsoft.com/sql/relational-databases/collations/set-or-change-the-database-collation applies for both SQL Database and Managed instance. When the applies to says SQL Database, it usually means both SQL Database AND managed instance. There is a separate applies to you might see on other articles that say 'managed instance only'.

The page you linked in your original description: https://docs.microsoft.com/azure/sql-database/sql-database-managed-instance-transact-sql-information#collation applies to managed instance only. 

Hope that helps.

**Comment by stevestein** [comment]
#please-close

**Comment by kazshi** [comment]
@stevestein Thank you for clarifying "When the applies to says SQL Database, it usually means both SQL Database AND managed instance."
