### ISSUE TITLE
Azure SQL Database managed instance server collation can be changed.

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/sql-docs#2848]
"Azure SQL Database managed instance server collation is SQL_Latin1_General_CP1_CI_AS and cannot be changed." in the Note, but the server collation can be changed when creating Managed Instance. Please update accordingly.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c14ada4b-32fa-f33f-5828-7d82db830056
* Version Independent ID: b360bfe9-714d-200e-5127-389a6d95b113
* Content: [COLLATE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/collations?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/collations.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/collations.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
Fixed https://github.com/MicrosoftDocs/sql-docs-pr/pull/11788

**Comment by kazshi** [comment]
@CarlRabeler Thank you for the update. I checked the PR #11788. Closing.
