### ISSUE TITLE
Database-level collations

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/sql-docs#2849]
I understand that the description in the section is applicable to Azure SQL Database (and Managed Instance), but is it true that "When you change the collation of a user database,..."?
It's inconsistent with the following restriction - "Collation cannot be changed after database has been created on Azure SQL Database." (from the following page)

Set or Change the Database Collation - SQL Server | Microsoft Docs
https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-database-collation?view=sql-server-2017#Restrictions

Related to #2847

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bda69849-66d9-0b69-1041-c526a406c04f
* Version Independent ID: 7a8927c6-95b4-47bf-d866-3c5585cf9383
* Content: [Collation and Unicode Support - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-2017#Collation_Defn)
* Content Source: [docs/relational-databases/collations/collation-and-unicode-support.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/collation-and-unicode-support.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@kazshi - thanks for opening this issue. We've added a note to the article where changing collations is mentioned.

Thanks!
