### ISSUE TITLE
Example showing parallel processing happens with RxInSqlServer context

### ISSUE THREAD

**Issue by stevenluda** [MicrosoftDocs/sql-docs#2850]
Among tons of docs, it is claimed that the HPA functions in RevoScaleR package can process large data in parallel in a computer context suh as RxInSqlServer. But no doc provides an example showing such parallelism. As a deep dive doc, could you provide a reproducible convincing example? For example, showing rxPredict scores partitions of data on multiple cores, or rxDForest building trees on multiple cores. 

I'm raising this request because in another post here https://nielsberglund.com/2018/05/20/sp_execute_external_script-and-sql-compute-context---i/, I was trying to reproduce the experiments. Specifically, with code snippet 8 and numTasks = 4 for RxInSqlServer, I didn't see similar result of parallelism reported in Figure 7, where mpiexec.exe spins up multiple Rterm to do the training. 

I'm using SQL server 2016, and has updated to the most recent update KB4052908. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26bfdeb-ae89-69cc-5e52-37ddbe2444ba
* Version Independent ID: 31170f3a-2ba3-b9fa-9533-8c2ee40840bd
* Content: [Define and use RevoScaleR compute contexts - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/tutorials/deepdive-define-and-use-compute-contexts?view=sql-server-2017#feedback)
* Content Source: [docs/advanced-analytics/tutorials/deepdive-define-and-use-compute-contexts.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/tutorials/deepdive-define-and-use-compute-contexts.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@stevenluda Thank you for your doc idea. We are looking into if/how we can document this for SQL Server Machine Learning Services. In the meantime, please have a look at the [reference documentation for RevoScaleR](https://docs.microsoft.com/en-us/machine-learning-server/r-reference/revoscaler/revoscaler) for Machine Learning Server, which is also used for SQL Server.
