### ISSUE TITLE
bdc.json file

### ISSUE THREAD

**Issue by chrisadkin** [MicrosoftDocs/sql-docs#2851]
Running the command:

azdata bdc config init --source aks-dev-test --target custom

results in two json files: cluster.json and control.json, there is no bdc.json file to be found, can you please correct this page accordingly. I'm using rc1 btw.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f789883-5a24-a045-21d5-4b95951cb798
* Version Independent ID: fadbef40-b033-7e4f-533a-abd7a8e303db
* Content: [Deployment guidance - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-guidance?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/big-data-cluster/deployment-guidance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deployment-guidance.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by lmil10** [comment]
I had the same issue.  I didn't have the latest azdata build.  Once I uninstalled and reinstalled azdata, I got the bdc.json file.

**Comment by MikeRayMSFT** [comment]
@chrisadkin  - I'm trying to repro. Is this still an issue (assuming you're on the latest azdata). Thanks for submitting.

**Comment by MikeRayMSFT** [comment]
I've verified with the product group that bdc.json and config.json are the correct file names. If you have other file names, there is an older version of azdata.

**Comment by lmil10** [comment]
I can confirm this also. Had the same issue, but after upgrading azdata, I received the expected files
