### ISSUE TITLE
sizing for the storage pool

### ISSUE THREAD

**Issue by chrisadkin** [MicrosoftDocs/sql-docs#2852]
By default HDFS makes data highly available via Resilient Distributed Datasets, I believe there was talk about the data being replicated three times. If this is still the case, can this please be mentioned in the documentation with some context around how this influences storage requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e099502f-f7d3-5368-41fe-6c50d593c8fd
* Version Independent ID: 7f77cae8-15a9-a586-31b2-80d985ca019a
* Content: [Data persistence on Kubernetes - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/concept-data-persistence?view=sqlallproducts-allversions)
* Content Source: [docs/big-data-cluster/concept-data-persistence.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/concept-data-persistence.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @mihaelablendea
* Microsoft Alias: **mihaelab**

**Comment by rothja** [comment]
@chrisadkin Thank you for the question, and apologies for the delayed response. @mihaelablendea Could you take a look at this question and see if the article needs updating? Thank you!

**Comment by mihaelablendea** [comment]
Added a note regarding impact of replication factor: https://github.com/MicrosoftDocs/sql-docs-pr/pull/14239
