### ISSUE TITLE
AD authentication in Docker

### ISSUE THREAD

**Issue by danvalero** [MicrosoftDocs/sql-docs#2855]
Is it possible to use AD authentication for SQL Server running in Dockers containers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5785871a-0daf-16d7-6678-4285bbd28b6e
* Version Independent ID: c5587dc0-b731-67e1-0d2a-3225a10dd310
* Content: [Active Directory authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-auth-overview?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-active-directory-auth-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-auth-overview.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **dygray**

**Comment by vin-yu** [comment]
It is possible to set up SQL Server containers with AD set up and we'll update these docs in the future with instructions on how you could set this up but this configuration is not supported for production use cases yet.

**Comment by rothja** [comment]
@danvalero Thank you for your question. Per @vin-yu 's response, we'll be providing more guidance soon, but we don't have the steps documented just yet. For now, we will close the git issue, but I will try to remember to post back here when we have documentation available on this. Thank you!
