### ISSUE TITLE
Related Content Link

### ISSUE THREAD

**Issue by JediSQL** [MicrosoftDocs/sql-docs#2856]
I think it would be helpful were the "Related Content" section to have a link to:
xml (Transact-SQL)
https://docs.microsoft.com/en-us/sql/t-sql/xml/xml-transact-sql

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed5014a4-6cfd-670a-b5ee-c75669fa5b5b
* Version Independent ID: eae2dd35-ff1b-6edf-aa0e-df7942d147e4
* Content: [XML Data (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/xml/xml-data-sql-server?view=sql-server-2017)
* Content Source: [docs/relational-databases/xml/xml-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/xml/xml-data-sql-server.md)
* Product: **sql**
* Technology: **xml**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by msebolt** [comment]
@JediSQL  Thank you for the feedback.

The documentation has been updated.
