### ISSUE TITLE
Typo in this sentence

### ISSUE THREAD

**Issue by rgward** [MicrosoftDocs/sql-docs#2857]
Similarly for changing the settings of a signle service within a specific resource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6f46cd1-caaa-99ac-1098-f15552369f22
* Version Independent ID: 34ec4839-afba-f57e-1a6d-bc453e70b9ce
* Content: [Configure deployments - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-custom-configuration?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/big-data-cluster/deployment-custom-configuration.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deployment-custom-configuration.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@rgward -- Bob, thank you for your feedback.  I am looking into it.

**Comment by WilliamAntonRohm** [comment]
Thank you for your keen eye.  I have updated the documentation and it should be live by tomorrow.
