### ISSUE TITLE
Attempt at formatting bleeds through into rendered document

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/sql-docs#2859]
There are a number of places where there has been an attempt to use markdown formatting to display identifiers and variable names in a particular way. However, the rendered document shows things like

&gt; \_@variable\\_name\_

instead of

&gt; _@variable\_name_

. I see this mostly in the documentation for `OPTIMIZE FOR` on this page, but the entire page probably could use a formatting audit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33da0c41-feb0-82a9-0ce9-9e2dbe58a1c4
* Version Independent ID: 4a97457a-c149-3c41-b78a-5b4e3869f078
* Content: [Query Hints (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-query?view=sql-server-2017)
* Content Source: [docs/t-sql/queries/hints-transact-sql-query.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/hints-transact-sql-query.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by binki** [comment]
Since https://github.com/MicrosoftDocs/sql-docs/blob/00350f6ffb73c2c0d99beeded61c5b9baa63d171/docs/t-sql/queries/hints-transact-sql-query.md seems to render things correctly, perhaps the markdown renderer used by the publishing process to docs.microsoft.com itself is broken.

**Comment by VanMSFT** [comment]
@binki - Thanks Nathan!

@MightyPen - Hey Gene, do you know why this might be broken on the live page?

**Comment by MightyPen** [comment]
@VanMSFT Van, I too am surprised to see that ` _@variable\_name_ ` does not render to look like simply italicized.

- _@variable\_name_  &nbsp; ` _@variable\_name_ `

- *@variable_name* &nbsp; `*@variable_name*`

I will assign this Issue 2859 to myself.
Thanks. G
 . .

**Comment by MightyPen** [comment]
Testing with new PR #11850.

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/11850`

**Comment by MightyPen** [comment]
Fixed, for this article, by PR 11850.
The gist is that now the AT-SIGN `@` must also be escaped (with a backslash) in some cases.
Or `@` can be HTML encoded as `&#x40;`.

I will mention this Issue #2859 to Tami_F, so that she can convey to her people.
Thanks. G.

---

@binki Hi Nathan, I am now Closing this Issue #2859. 
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.
Thank you for submitting this Issue. We hope to hear from you again.

cc: @VanMSFT
