### ISSUE TITLE
View with stored data

### ISSUE THREAD

**Issue by ma17961363** [MicrosoftDocs/sql-docs#2865]
I think it was better to have a view that stores its query result to access quickly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7bfcbf2-4dbb-6a41-4390-40d6bc076606
* Version Independent ID: 2992dd77-8134-c2ea-8957-3a696583a2c4
* Content: [Views - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/views/views?view=sql-server-2017)
* Content Source: [docs/relational-databases/views/views.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/views/views.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@ma17961363 -- thank you for your feedback.  Can you please give us more information about your task or issue?

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
