### ISSUE TITLE
Deprecated option use in examples

### ISSUE THREAD

**Issue by cunnpole** [MicrosoftDocs/sql-docs#2866]
The article references deprecated SHA1 and also could do with a sentence that describes  why you would want an authenticating hash. Various articles state that "a random salt value is always applied to the encryption" so this should also be clearly stated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd3dba3-ebd8-342e-fce9-af4c5ce39324
* Version Independent ID: f9725f20-7bdd-2e6c-f5db-957c00771d27
* Content: [Encrypt a Column of Data - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/encrypt-a-column-of-data?view=sql-server-2017)
* Content Source: [docs/relational-databases/security/encryption/encrypt-a-column-of-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/encrypt-a-column-of-data.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @aliceku
* Microsoft Alias: **aliceku**

**Comment by WilliamAntonRohm** [comment]
@cunnpole -- Stewart, thank you for your feedback.

@aliceku -- Alice, please look into this issue 2866.

**Comment by PrometheusRising1** [comment]
In addition to cunnpole's comment, there should be a list or easy link to the types of symmetric key algorithms available.  It is not clear which ones are available for use outside of the sample/example code.

**Comment by rothja** [comment]
@jaszymas, I believe you're the new owner of this content. Can you take a look? Thank you! #reassign:jaszymas

**Comment by VanMSFT** [comment]
Hi @cunnpole! Thanks for submitting this issue. I apologize for the delay. I'm checking with the Product Group on this, and will get back to you on this thread.

**Comment by PrometheusRising1** [comment]
Hi, any progress on this topic?  I have verified personally (obviously, not an exhaustive test) that SHA2 works in replacement of SHA1 for SQL 2016.

**Comment by VanMSFT** [comment]
Hey @jaszymas - Can you help with this? Thanks!

**Comment by MikeRayMSFT** [comment]
Thanks for the call out, sorry it took so long to reply. An update to a supported algorithm is in flight.
