### ISSUE TITLE
The length of the encrypted field used in example is wrong. 

### ISSUE THREAD

**Issue by bak3r** [MicrosoftDocs/sql-docs#2876]
CardNumber_Encrypted should be 160 bits not 128 bits if you are using SHA1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd3dba3-ebd8-342e-fce9-af4c5ce39324
* Version Independent ID: f9725f20-7bdd-2e6c-f5db-957c00771d27
* Content: [Encrypt a Column of Data - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/encrypt-a-column-of-data?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/encryption/encrypt-a-column-of-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/encrypt-a-column-of-data.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @aliceku
* Microsoft Alias: **aliceku**

**Comment by WilliamAntonRohm** [comment]
@bak3r -- thank you for your feedback.  I am looking into it.

**Comment by WilliamAntonRohm** [comment]
Thank you for your keen eye.  I have updated the documentation and it should be live by tomorrow.
