### ISSUE TITLE
Missing RC1 new custom features details

### ISSUE THREAD

**Issue by iuriivaschuk** [MicrosoftDocs/sql-docs#2883]
"security": {
        "ouDistinguishedName": "",
        "dnsIpAddresses": [],
        "domainControllerFullyQualifiedDns": [],
        "realm": "",
        "domainDnsName": "",
        "bdcAdminPrincipals": [],
        "bdcUserPrincipals": []
DOMAIN_SERVICE_ACCOUNT_PASSWORD
DOMAIN_SERVICE_ACCOUNT_USERNAME
dnsName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6f46cd1-caaa-99ac-1098-f15552369f22
* Version Independent ID: 34ec4839-afba-f57e-1a6d-bc453e70b9ce
* Content: [Configure deployments - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-custom-configuration?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/big-data-cluster/deployment-custom-configuration.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deployment-custom-configuration.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@iuriivaschuk -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue 2883.

**Comment by MikeRayMSFT** [comment]
@iuriivaschuk - thank you. Reviewing.

**Comment by NelGson** [comment]
@iuriivaschuk Tye security feature in big data clusters is not yet public and is only in private preview at the moment. We will make it documented on the Docs once it is public.

**Comment by NelGson** [comment]
@iuriivaschuk  Let me know if you want to participate in the private preview or have questions. Here is a pointer to some private docs: https://aka.ms/bdc-eap-security-docs

The script to deploy in AD mode is also available here: https://github.com/microsoft/sql-server-samples/tree/master/samples/features/sql-big-data-cluster/deployment/kubeadm/ubuntu-single-node-vm-ad

**Comment by iuriivaschuk** [comment]
Thank.

You are the only one who could help me with bdc.

What is necessary from me to take part in a private preview?

Perhaps you can help me with this issue.
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/c395e067-1c7c-4d5a-a275-85cfaa455dd0/bdc-2019-rc1-gateway-does-not-work?forum=sqlgetstarted


ср, 25 сент. 2019 г. в 19:40, Mike Ray <notifications@github.com>:
