### ISSUE TITLE
General query - unsupported functions

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/sql-docs#2885]
Where is a complete synchronized list of all functions that do not have 'Azure SQL Database' ticked?
or is there a data source I could generated one from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 051788f8-a729-7a59-8b2f-5e2ba2cf62c2
* Version Independent ID: 30b9fe82-bc80-cf19-6ee3-7ce45a826975
* Content: [sp_addlinkedserver (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-addlinkedserver-transact-sql?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(sp_addlinkedserver_TSQL);k(sql13.swb.tsqlresults.f1);k(sql13.swb.tsqlquery.f1);k(MiscellaneousFilesProject);k(DevLang-TSQL)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-addlinkedserver-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-addlinkedserver-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by OzBob** [comment]
I made a list:
https://medium.com/@obobwa/azure-sql-snapshot-of-supported-system-procedures-84747c324e2a


Any suggestions on where to find a list of all the tSQL keywords like URL that the .bacpac wizard complains about if they are not surrounded by []? e.g. bacpac fails if a View has a column called URL but passes if it is [URL]

**Comment by msebolt** [comment]
@OzBob  Thank you for the question.

Currently the SQL Server and Azure SQL database reference is categorized by functionality as opposed to database type, so you would need to browse each functionality manually.

Assigning to author for comment.

**Comment by CarlRabeler** [comment]
I am not aware of any such list. We will add this request to our backlog of work items. Thanks for your inquiry.
Carl

**Comment by CarlRabeler** [comment]
#please-close

**Comment by OzBob** [comment]
@CarlRabeler 
here is the list of currently supported functions
generated from the GitHub repository on the 1st of the September:
https://medium.com/@obobwa/azure-sql-snapshot-of-supported-system-procedures-84747c324e2a

**Comment by CarlRabeler** [comment]
@OzBob - your list is relying on a metadata tag that is not guaranteed to be up-to-date and reliable. This metadata tag was added at one time for internal reporting purposes by the content team - but is not currently being used. As the 1000's of articles are updated by 100's of different PMs and Devs, there is no requirement that this tag be updated. A more reliable indicator is the moniker tag on the file or the folder containing the file, as well as the applies to tag at the top of the file - but not all files have applies to tags on them - such as the backup statement or the create database statement articles. Finally, you may find statements that work that are not supported - and will not be supported until fully tested by the product team. When we find a statement that is not tagged as supported, but appears to work - we coordinate with the product team to clarify support in the article about the statement.
I hope this helps.
Carl
