### ISSUE TITLE
Deployment of Apps

### ISSUE THREAD

**Issue by Sandmaann** [MicrosoftDocs/sql-docs#2887]
There is no help regarding the deployment of applications using SMO libraries. Apparently there are major complications with the deployment of such apps while delivering the dlls without installing SMO libs on the client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7a39ec0-ba64-4084-aaed-e632d4238859
* Version Independent ID: 1bce7350-5fd6-1778-0363-49d1ee2bc1a9
* Content: [Create a Visual C# SMO Project in Visual Studio .NET - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/how-to-create-a-visual-csharp-smo-project-in-visual-studio-net?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/server-management-objects-smo/how-to-create-a-visual-csharp-smo-project-in-visual-studio-net.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/server-management-objects-smo/how-to-create-a-visual-csharp-smo-project-in-visual-studio-net.md)
* Product: **sql**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@Sandmann  We're sorry you're experiencing issues.

This sounds like a product issue, do either of these pending SMO issues describe the problem?

- https://feedback.azure.com/forums/908035-sql-server/suggestions/32898796-smo-nuget-packages-do-not-work-reliably-due-to-a-g

- https://stackoverflow.com/questions/52768629/deploying-c-sharp-sql-server-smo-application

Assigning author.

**Comment by markingmyname** [comment]
@Sandmaann,


Do @msebolt's suggestions address your question?

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
