### ISSUE TITLE
Statement to disable for a single database throws an argument exception

### ISSUE THREAD

**Issue by degrover-cn** [MicrosoftDocs/sql-docs#2888]
EXEC msdb.managed_backup.sp_backup_config_basic  
                @database_name = 'MyDB'   
                ,@enable_backup = 0;  

SQL Server Managed Backup to Microsoft Azure cannot configure the database  'MyDB' because a container URL was either not provided or invalid. It is also possible that your SAS credential is invalid. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f448d2c-730b-9728-b43f-4ea080fc7861
* Version Independent ID: 45828819-be38-5acc-ec47-7d696dffc74b
* Content: [Disable SQL Server Managed Backup to Microsoft Azure - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/disable-sql-server-managed-backup-to-microsoft-azure?view=sql-server-2017)
* Content Source: [docs/relational-databases/backup-restore/disable-sql-server-managed-backup-to-microsoft-azure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/disable-sql-server-managed-backup-to-microsoft-azure.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@degrover-cn  Thank you for the question.

Was this backup previously enabled using a storage container?

If so, please try using the `@container_url` parameter listed [here](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/managed-backup-sp-backup-config-basic-transact-sql?view=sql-server-2017) to set the container.

**Comment by degrover-cn** [comment]
That's helpful, thank you. I do recommend updating the document I submitted this ticket from.

**Comment by msebolt** [comment]
You're welcome.  A note has been added.
