### ISSUE TITLE
In-place upgrade wording

### ISSUE THREAD

**Issue by mrlife** [MicrosoftDocs/sql-docs#2891]
This sentence is worded in a confusing way: 

> Upgrade instances of SQL Server 2019 RC from instances of SQL Server 2012 through SQL Server 2017 and SQL Server CTP 3.0.

Should it be? 

> Upgrade to SQL Server 2019 RC from instances of SQL Server 2012 through SQL Server 2017 and SQL Server CTP 3.0.

Also, should the docs mention to prospective previewers whether the RC is upgradeable to the final version once it's released? If it does, I apologize for missing it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d27f9e6d-face-26a5-c6a6-28c7b3df73f1
* Version Independent ID: 62aa0061-3e52-6afd-cbe6-ee928375fc92
* Content: [SQL Server 2019 Release Notes - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-ver15-release-notes?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/sql-server/sql-server-ver15-release-notes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/sql-server-ver15-release-notes.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@mrlife  Thank you for the feedback.

The documentation has been updated.
