### ISSUE TITLE
Error: The package management feature is not enabled for the current user or not supported on SQL Server version

### ISSUE THREAD

**Issue by stevenluda** [MicrosoftDocs/sql-docs#2896]
Using the code sample:

library(sqlmlutils)
connection &lt;- connectionInfo(
  server= "yourserver",
  database = "yourdatabase",
  uid = "yoursqluser",
  pwd = "yoursqlpassword")

sql_install.packages(connectionString = connection, pkgs = "glue", verbose = TRUE, scope = "PUBLIC")

Any thought? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce36aa85-fd24-74a6-1e01-20c892f92a9f
* Version Independent ID: 08b9fb79-7117-98fc-5d2c-7a42a6c49a04
* Content: [Install new R packages with sqlmlutils - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/package-management/install-additional-r-packages-on-sql-server?view=sql-server-2017)
* Content Source: [docs/advanced-analytics/package-management/install-additional-r-packages-on-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/package-management/install-additional-r-packages-on-sql-server.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by msebolt** [comment]
@stevenluda We're sorry you're experiencing issues.

Some things to check:

- make sure the R option is selected from the installation wizard

![Capture](https://user-images.githubusercontent.com/6675884/64310758-4992b800-cf56-11e9-9d2c-079cba5d9d2c.PNG)

  ...or check installation via [command line](https://docs.microsoft.com/sql/advanced-analytics/install/sql-ml-component-commandline-install?view=sql-server-2017).

- try running through [upgrading R](https://docs.microsoft.com/sql/advanced-analytics/install/upgrade-r-and-python?view=sql-server-2017) and/or [setup R](https://docs.microsoft.com/sql/advanced-analytics/r/set-up-a-data-science-client?view=sql-server-2017) to see if your basic packages are installed correctly

If neither works, please comment below.

**Comment by stevenluda** [comment]
I can confirm that R services is installed on the SQL server instance. I found one resource here https://renenyffenegger.ch/notes/Windows/dirs/Program-Files/Microsoft-SQL-Server/version/R_SERVER/library/RevoScaleR/rxLibs/x64/RegisterRExt_exe saying RegisterRext.exe /installpkgmgmt has to be ran first. When I ran it, I got the following error:

Source directory to pick the RExtension binaries determined to be "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\R_SERVICES\library\RevoScaleR\rxLibs\x64\".
Installation flavor was not supplied
Connecting to SQL server...
Sql server binn directory is "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Binn".
Stopping service MSSQLLaunchpad...
Copied RLauncher.dll from C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\R_SERVICES\library\RevoScaleR\rxLibs\x64\ to C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Binn.
Installing SQL R services package management for instance ''
Installing version 1.0 artifacts
Creating package management account MSSQLSERVERPKG...
Saving package management user account configuration...
Working directory from data root "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL" is "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\ExtensibilityData".
Working Directory Name is "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\ExtensibilityData".
GetSymbolicLinkPath: Adding ProgramData to symbolic link path
Deleting existing symlink:'C:\ProgramData\MSSQLSERVER\Temp-R'.
ExtensibilityData Symlink:'C:\ProgramData\MSSQLSERVER\Temp-R' and long path:'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\ExtensibilityData'.
Working directory from data root "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL" is "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\ExtensibilityData".
Working Directory Name is "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\ExtensibilityData".
GetSymbolicLinkPath: Adding ProgramData to symbolic link path
Failed to install version 1.0 artifacts
Error: Couldnt create the symbolic link for ExtensibilityData
Failed to install SQL R services package management for instance ''
Cleaning up for instance  after failed installation
Removing SQL R services package management for instance ''
Removing version 1.0 artifacts
Working directory from data root "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL" is "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\ExtensibilityData".
Configuring security for folder C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\ExtensibilityData...
Removing package management account MSSQLSERVERPKG...
Deleting package management user account configuration...
Working directory from data root "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL" is "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\ExtensibilityData".
Working Directory Name is "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\ExtensibilityData".
GetSymbolicLinkPath: Adding ProgramData to symbolic link path
Failed to remove version 1.0 artifacts
Error: Couldnt create the symbolic link for ExtensibilityData
Failed to Remove SQL R services package management for instance ''
Failed to cleanup after failed install.
Error: Couldnt create the symbolic link for ExtensibilityData
Starting service MSSQLLaunchpad...
Error: Couldnt create the symbolic link for ExtensibilityData
Failed to complete the operation successfully

**Comment by stevenluda** [comment]
RegisterRext.exe /installpkgmgmt went through successfully. It turned out /instance has to be specified. Also, enable pkg mgmt at database level. Tried sql_install.packages(connectionString = connection, pkgs = "glue", verbose = TRUE, scope = "public") again, still giving same error:
Error: The package management feature is not enabled for the current user or not supported on SQL Server version 13.0.4541.0

But interestingly, rxInstallPackages can do the work without problem:
pkgs <- c("glue")
rxInstallPackages(pkgs = pkgs, verbose = TRUE, scope = "public", computeContext = sqlcc)

Any thought?

**Comment by msebolt** [comment]
Thank you for your efforts, this is good information for the product team.  

I'll assign this over to the author now.

**Comment by garyericson** [comment]
@stevenluda - Thanks for filing this issue with all the detail. It turns out that the sqlmlutils package doesn't work with 2016, it only works with SQL 2017 or later. We'll work on correcting the versioning of the article and then document an alternative for 2016. At this point it looks like the alternative for 2016 is to either run install.packages from within the SQL instance folder (e.g., `C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\R_SERVICES\bin\x64\`) or use RevoScaleR (rxInstallPackages, like you've shown above).

@dphansen

**Comment by garyericson** [comment]
#please-close

**Comment by stefan-oppliger** [comment]
It's not quite right that sqlmlutils works with SQL Server 2017.
The functions sql_install.packages at some point (in the function sqlCheckPackageManagementVersion) checks the installed SQL Server Version:
` if (((version[["serverType"]] == "azure" && version[["major"]] >= 
    12) || (version[["serverType"]] == "box" && version[["major"]] >= 
    15))) {
    versionClass <- "ExtLib"
  }`.

The major version 15 is SQL Server 2019 which is not yet released. The newest available version of SQL Server 2017 is 14.0.3238.1. So it's not possible to use sqlmlutils package with SQL Server 2017. 

Is this a bug or on purpose?

**Comment by garyericson** [comment]
@stefan-oppliger - I'm checking with the product team. I'll post back here what I find out what they say, hopefully soon.

**Comment by harshbangad** [comment]
Hi, I am getting the same error. I have SQL Server 2017 installed on the machine
"Error: The package management feature is not enabled for the current user or not supported on SQL Server version 14.0.3223.3"

**Comment by dphansen** [comment]
@harshbangad and @stefan-oppliger: `sqlmlutils` is not supported in SQL Server 2017. For how to install R packages, see [Install packages with R tools](https://docs.microsoft.com/en-us/sql/advanced-analytics/package-management/install-r-packages-standard-tools?view=sql-server-2017) and [Use T-SQL (CREATE EXTERNAL LIBRARY) to install R packages on SQL Server](https://docs.microsoft.com/en-us/sql/advanced-analytics/package-management/install-r-packages-with-tsql?view=sql-server-2017).
