### ISSUE TITLE
Missing parameter in text

### ISSUE THREAD

**Issue by ChristosMonogios** [MicrosoftDocs/sql-docs#2903]
On the first Parameter/Description table:

mcr.microsoft.com/mssql/server:2017-latest - The SQL Server 2017 Linux container image.

the -d is missing in front of the image name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Get started with SQL Server Linux containers on Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-powershell#feedback)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by msebolt** [comment]
@ChristosMonogios Thank you for the feedback.

The documentation has been updated.
