### ISSUE TITLE
Excellently written. Thank you.

### ISSUE THREAD

**Issue by awbloss** [MicrosoftDocs/sql-docs#2904]
Very helpful and very well written. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d550c681-67e1-78a3-119e-a46b30821d99
* Version Independent ID: 64d394ce-e80f-72c9-0590-4dd8a8801d0c
* Content: [Atomic Blocks - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/atomic-blocks-in-native-procedures?view=sql-server-2017)
* Content Source: [docs/relational-databases/in-memory-oltp/atomic-blocks-in-native-procedures.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/atomic-blocks-in-native-procedures.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@awbloss  Thank you for the feedback.  It's nice to know we can help.

Including @CarlRabeler
