### ISSUE TITLE
Documentation incorrectly indicates SQL DW supports Try_Cast

### ISSUE THREAD

**Issue by MatthewERossi** [MicrosoftDocs/sql-docs#2907]
At the time of this issue 9/5/2019 Try_Cast is not supported by SQL DW but the site indicates that it is at the top.

**Comment by WilliamAntonRohm** [comment]
@MatthewERossi  Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
