### ISSUE TITLE
Failover Cluster possible owners

### ISSUE THREAD

**Issue by jschmidt0723** [MicrosoftDocs/sql-docs#2908]
Do not use the Failover Cluster Manager to manipulate availability groups:

For example:

Do not change any availability group properties, such as the possible owners.

-- 

Can there be any note or reason why we cannot change possible owners for a failover cluster in a SQL AG? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5dab67c-0b02-71a8-bba0-416be62e5d52
* Version Independent ID: c0f9db5f-668e-aac1-f789-cd7e34bdf316
* Content: [Prerequisites, Restrictions, and Recommendations for availability groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @jschmidt0723 , thanks for contacting Microsoft! Let me investigate this a bit and get back to you :) 

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @jschmidt0723 , thank you for patience as I researched this. 

The state of a SQL Failover Cluster Instance (FCI) is shared between SQL and the Windows Failover Cluster (WSFC), with SQL keeping some more detailed state information on the instances than the cluster cares about.  The management model is that SQL must drive the transactions, and is responsible for keeping the cluster’s view of the state in sync with SQL’s view of state.  If the state of the cluster is changed outside of SQL (using the cluster manager to fail over, for example), it is possible for the state to get out of sync between WSFC and SQL, which can cause unpredictable behavior.

This will be added to the documentation as well :)

Thanks for your help in improving our documentation! Please let us know if we can be of further assistance? If not, we will proceed with closing out the Git Issue in a few business days.

Thanks!
Masha from the SQL Docs team

**Comment by jschmidt0723** [comment]
This is awesome! Thank you so much!!!


Jake

**Comment by MashaMSFT** [comment]
glad we could help :) We'll close out the Git Issue now. Thanks for making docs better!
