### ISSUE TITLE
Microsoft Sync Framework

### ISSUE THREAD

**Issue by dlieser** [MicrosoftDocs/sql-docs#2911]
Sync Framework is mentioned on this page, but is sunsetting, with no apparent direct replacement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c051760-30c7-a96c-f4f2-db49a468b432
* Version Independent ID: f5426e86-2456-8231-5fea-d856bae84e83
* Content: [SQL Server Replication - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/sql-server-replication?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/replication/sql-server-replication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/sql-server-replication.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @dlieser , thanks for bringing this to our attention! Let me do a bit of research and get back to you :) Thanks!

Masha from the SQL Docs team
