### ISSUE TITLE
apt-get update failing

### ISSUE THREAD

**Issue by werebear73** [MicrosoftDocs/sql-docs#2912]
I'm getting the following error when trying to update before the install.

E: Some index files failed to download. They have been ignored, or old ones used instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41654ae8-cbd1-c5dd-f15a-69466a765fda
* Version Independent ID: 94311dce-80f0-b8ce-7296-b595ff50d640
* Content: [Install SQL Server Integration Services on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-ssis?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-setup-ssis.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-ssis.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @lrtoyou1223
* Microsoft Alias: **lle**

**Comment by msebolt** [comment]
@werebear73 Thank you for the feedback.

It's likely certain repositories will be down at any given time during the update.  Do the installation steps fail or are enough repos still available?

**Comment by msebolt** [comment]
Closing this now, please comment below if there are any further issues.
