### ISSUE TITLE
Proxy server

### ISSUE THREAD

**Issue by chainhead** [MicrosoftDocs/sql-docs#2913]
Is there a proxy server solution that has Azure SQL DB as the back-end? Consider ProxySQL - it is a MySQL proxy - https://proxysql.com/#features . Which features of ProxySQL are similarly supported natively with Azure SQL DB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d91022-0ff5-2a0e-4711-217fd9568018
* Version Independent ID: cd30c087-06e7-f947-cf6a-262001d574a3
* Content: [Intelligent query processing in Microsoft SQL databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/intelligent-query-processing?view=sql-server-2017)
* Content Source: [docs/relational-databases/performance/intelligent-query-processing.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/intelligent-query-processing.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @joesackmsft
* Microsoft Alias: **josack**

**Comment by joesackmsft** [comment]
@chainhead In most cases, we cannot add links to third-party products from our SQL documentation. I’m closing this now, but let me know if you have any questions.

**Comment by joesackmsft** [comment]
#please-close
