### ISSUE TITLE
Typo in this sentence (same same)

### ISSUE THREAD

**Issue by macarv-ms** [MicrosoftDocs/sql-docs#2915]
For example, if you would like to set same same settings for Spark across

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6f46cd1-caaa-99ac-1098-f15552369f22
* Version Independent ID: 34ec4839-afba-f57e-1a6d-bc453e70b9ce
* Content: [Configure deployments - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-custom-configuration?view=sqlallproducts-allversions)
* Content Source: [docs/big-data-cluster/deployment-custom-configuration.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deployment-custom-configuration.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@macarv-ms  Thank you for the feedback.

The documentation has been updated.
