### ISSUE TITLE
The following deploy sequence can be improved (--patch-file patch.json to --patch-file ha-patch.json).

### ISSUE THREAD

**Issue by macarv-ms** [MicrosoftDocs/sql-docs#2916]
Despite not wrong, I believe the following example can be improved in order to avoid misleading interpretations.

1. Create a ha-patch.json file
...

2. Clone your targeted profile
azdata config init --source aks-dev-test --target custom-aks

3 .Apply the patch file to your custom profile
azdata bdc config patch -c custom-aks/bdc.json --patch-file patch.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a52d6b-4d65-8e74-78f0-51387397ae21
* Version Independent ID: 576d9270-ad4c-bedf-cce9-a3b260183f0d
* Content: [Deploy SQL Server Big Data Cluster with high availability - Deploy SQL Server Big Data Cluster with high availability](https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-high-availability?view=sqlallproducts-allversions)
* Content Source: [docs/big-data-cluster/deployment-high-availability.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deployment-high-availability.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @mihaelablendea
* Microsoft Alias: **mihaelab**

**Comment by msebolt** [comment]
@macarv-ms  Thank you for the feedback.

Did you have issues during the deploy?  What misleading interpretation are you referring to?

**Comment by macarv-ms** [comment]
Honestly I haven't tried to deploy this way.. my fault and sorry if this is some misleading from my end. Anyway, should't we have the following script for step 3:

azdata bdc config patch -c custom-aks/bdc.json --patch-file ha-patch.json 

instead of

azdata bdc config patch -c custom-aks/bdc.json --patch-file patch.json

Once in step 1 we have created ha-patch.json and not patch.json?

Thanks!

**Comment by msebolt** [comment]
No worries, I should have caught that.  We'll get the documentation updated.

**Comment by msebolt** [comment]
Documentation has been updated, please comment below if there are further issues.
