### ISSUE TITLE
No detail on what version of SQL Server this was supported from

### ISSUE THREAD

**Issue by rob-smartspace** [MicrosoftDocs/sql-docs#2918]
I would like to see what version first supported this function (or any function for that matter) and be able to see the differences either in the doc or by being able to navigate to different versions of this doc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5e0826e-9a72-d26c-e82a-2ebc0dc41e62
* Version Independent ID: aab05073-f967-e218-b40f-f11bfb73ca00
* Content: [Sequence Numbers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/sequence-numbers/sequence-numbers?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/sequence-numbers/sequence-numbers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/sequence-numbers/sequence-numbers.md)
* Product: **sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@rob-smartspace Thank you for the feedback.

With the version selector this should be possible.

![Capture](https://user-images.githubusercontent.com/6675884/64444224-7f37be00-d088-11e9-9f36-e96e351d4b3c.PNG)

Are there omissions from these versions in the stated article, or are you looking for something older than 2014?

Older archived documentation can be found in [previous versions](https://docs.microsoft.com/en-us/previous-versions/sql/).

**Comment by binki** [comment]
@msebolt But https://stackoverflow.com/a/8465306 says sequences are supported by SQL Server 2012. Using the version selector, I can only see 2014. And if I select “older”, I get a redirect to 2019. Please show me how I can see a simple table showing which versions of SQL Server support the feature versus not.

**Comment by msebolt** [comment]
@binki  Apologies for any confusion, it sounds like this issue is similar to https://github.com/MicrosoftDocs/sql-docs/issues/3823.  

Unfortunately, if this is in regards to how the version selector works (such as lacking functionality for earliest supported version, version tables, etc.) it needs to be handled by the **Microsoft Docs** team [here](https://github.com/MicrosoftDocs/feedback/issues).
