### ISSUE TITLE
This does not work in my case

### ISSUE THREAD

**Issue by DumboJetEngine** [MicrosoftDocs/sql-docs#2926]
I have written this script to enable protocols:

```
Import-Module "sqlps" -DisableNamechecking
###############################################################
#                                                             #
# Function to Enable or Disable a SQL Server Network Protocol #
#                                                             #
###############################################################
function ChangeSQLProtocolStatus
{
	Param (
		$protocol,
		$instanceName,
		$enable
	)
	try
	{
		Add-Type -AssemblyName "Microsoft.SqlServer.Smo"
		Add-Type -AssemblyName "Microsoft.SqlServer.SqlWmiManagement"
	}
	catch { throw "Exception occurred when we refer smo and SqlWmiManagement assembly, and its $($_.Exception)" }
	
	try
	{
		Write-Host "Initializing WMI object"		
		$wmi = new-object Microsoft.SqlServer.Management.Smo.WMI.ManagedComputer
		
		Write-Host "Generation URI"		
		$uri = "ManagedComputer[@Name='$env:COMPUTERNAME']/ServerInstance[@Name='MSSQL`$$instanceName']/ServerProtocol[@Name='$protocol']";
		$uri
		
		Write-Host "Creating protocol settings"
		$prtocolSettings = $wmi.getsmoobject($uri)
		
		Write-Host "Created Protocol smo  object"
		$prtocolSettings.IsEnabled = $enable
		$prtocolSettings.Alter()
		
		# Restart SQL Server
		try { Get-Service -Name "MSSQL`$$instanceName" -ErrorAction 'Stop' | Restart-Service -Force -ErrorAction 'Stop' }
		catch { throw "Starting Sql server service failed in server $($_.Exception)" }
	}
	
	catch
	{
		$_
	}
}
# Calling it like that:
ChangeSQLProtocolStatus 'Tcp' 'EXPRESS_2017' True;
```
I always get an error saying:
```
Exception calling "GetSmoObject" with "1" argument(s): "Attempt to retrieve data for object failed for ManagedComputer 'WINS-2019'."
````

I have tried running it with the 32 bit version of powershell and still nothing.
Using the exact code that the docs propose fails as well:

```
$smo = 'Microsoft.SqlServer.Management.Smo.'
$wmi = new-object ($smo + 'Wmi.ManagedComputer').

# List the object properties, including the instance names.  
$Wmi  

# Enable the TCP protocol on the default instance.  
$uri = "ManagedComputer[@Name='WINS-2019']/ ServerInstance[@Name='MSSQL$EXPRESS_2017']/ServerProtocol[@Name='Tcp']"   
$Tcp = $wmi.GetSmoObject($uri)
$Tcp.IsEnabled = $true
$Tcp.Alter()
$Tcp
```

I have a named instance and I run the script on the computer where the instance is running.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e350b6-b39b-0a14-6637-06fbec7b171a
* Version Independent ID: f92e2065-c2d4-3e93-c136-de4da69d7586
* Content: [Enable or Disable a Server Network Protocol - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-or-disable-a-server-network-protocol?view=sql-server-2017)
* Content Source: [docs/database-engine/configure-windows/enable-or-disable-a-server-network-protocol.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/enable-or-disable-a-server-network-protocol.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by DumboJetEngine** [comment]
Found it!
I had to remove the `MSSQL$` part from the instance name.
The docs where misleading on this...

```
Import-Module "sqlps" -DisableNamechecking
###############################################################
#                                                             #
# Function to Enable or Disable a SQL Server Network Protocol #
#                                                             #
###############################################################
function ChangeSQLProtocolStatus
{
	Param (
		$protocol,
		$instanceName,
		$enable
	)
	try
	{
		Add-Type -AssemblyName "Microsoft.SqlServer.Smo"
		Add-Type -AssemblyName "Microsoft.SqlServer.SqlWmiManagement"
	}
	catch { throw "Exception occurred when we refer smo and SqlWmiManagement assembly, and its $($_.Exception)" }
	
	try
	{
		Write-Host "Initializing WMI object"		
		$wmi = new-object Microsoft.SqlServer.Management.Smo.WMI.ManagedComputer
		
		Write-Host "Generation URI"		
		$uri = "ManagedComputer[@Name='$env:COMPUTERNAME']/ServerInstance[@Name='$instanceName']/ServerProtocol[@Name='$protocol']";
		$uri
		
		Write-Host "Creating protocol settings"
		$prtocolSettings = $wmi.getsmoobject($uri)
		
		Write-Host "Created Protocol smo  object"
		$prtocolSettings.IsEnabled = $enable
		$prtocolSettings.Alter()
		
		# Restart SQL Server
		try { Get-Service -Name "MSSQL`$$instanceName" -ErrorAction 'Stop' | Restart-Service -Force -ErrorAction 'Stop' }
		catch { throw "Starting Sql server service failed in server $($_.Exception)" }
	}
	
	catch
	{
		$_
	}
}
ChangeSQLProtocolStatus 'Tcp' 'EXPRESS_2017' True;
```

**Comment by WilliamAntonRohm** [comment]
@DumboJetEngine -- thank you for your thorough feedback.  

@MikeRayMSFT -- please look into this issue 2926.

**Comment by MikeRayMSFT** [comment]
@DumboJetEngine  - is there a specific update to the [Enable or Disable a Server Network Protocol](http://docs.microsoft.com/sql/database-engine/configure-windows/enable-or-disable-a-server-network-protocol?view=sql-server-2017) article that would clarify this for you?

Adding @MightyPen and @VanMSFT  for extra insight

**Comment by MikeRayMSFT** [comment]
Closing for the time being.

**Comment by MightyPen** [comment]
This Issue #2926 is more of a request for Support service, than it is a note about Documentation.
These GitHub Issues cannot provide Support services.

**Comment by DumboJetEngine** [comment]
@MikeRayMSFT I think this part:
```
To stop and start a named instance replace 'MSSQLSERVER' with 'MSSQL$<instance_name>'.
```
..causes confusion, because the WMI code below uses the name 'MSSQLSERVER' as well. And if you use the 'MSSQL$<instance_name>' in the WMI code, it will fail (based on my experience at least).

Notice the difference between:
```
ServerInstance[@Name='$instanceName']
```
...and :
```
-Name "MSSQL`$$instanceName"
```
...in my PowerShell script above. This is what made it work. Using `MSSQL$<instanceName>` in both places causes failure in the WMI code.

**Comment by VanMSFT** [comment]
The only line in the documentation that notates replacing 'MSSQLSERVER' with 'MSSQL$<instance_name>' is for the following code block:

`$DfltInstance = $Wmi.Services['MSSQLSERVER']`

Are you saying that this fails? MSSQL$<instance_name> does not equate to the Instance Name of a SQL Server Instance. MSSQL$ is not a part of the Instance Name and that's why your PS script fails. We specifically state the following:

![image](https://user-images.githubusercontent.com/40007119/65708376-4a91a380-e043-11e9-95cc-13394c8a04ea.png)

We don't think this is a documentation issue, but rather a confusion on what is an Instance Name. We appreciate the feedback, but these forums are not for troubleshooting/support services.

**Comment by DumboJetEngine** [comment]
OK. :)
