### ISSUE TITLE
Installing SSIS in docker microsoft/mssql-server-linux failed

### ISSUE THREAD

**Issue by ph3ll3r** [MicrosoftDocs/sql-docs#2927]
What do I need to add to the docker OS Ubuntu to successfully add to install SSIS?  Are there suggested links ?

sudo /opt/ssis/bin/ssis-conf setup
The license terms for this product can be downloaded from:
https://go.microsoft.com/fwlink/?LinkId=855862

The privacy statement can be viewed at:
https://go.microsoft.com/fwlink/?LinkId=853010

### Attempting to start the telemetry service failed.
**
root@csci331-server:/# exit

**Comment by msebolt** [comment]
@ph3ll3r Thank you for the feedback.  We're sorry you're experiencing issues.

SSIS in Docker is not yet supported, however some users have found a way to get it working.

Please refer to issue https://github.com/Microsoft/mssql-docker/issues/213.
