### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/sql-docs#2930]
It should contain information here about installation from command line with possible arguments list etc...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by WilliamAntonRohm** [comment]
@djpirra -- Luis, thank you for your suggestions.

@dnethi -- Dinakar, please look into this issue 2930.

**Comment by dnethi** [comment]
I don’t think we have an official doc page for cmdline installation of SSMS.
@Matteo Taveggia<mailto:matteot@microsoft.com> – do you have any instructions and all the cmdline options that go with the setup?



Thanks,
Dinakar

**Comment by seamonkey420** [comment]
+1 to this. first thing in this doc should be how to install via commandline ie deploy to users silently.

**Comment by keanankruse** [comment]
As Seamonkey said we need info on the silent install, im trying to use SCCM and the code im using is:
SSMS-Setup-ENU.exe /install /quiet /norestart

But this fails with 1603... does anyone know  if there is anything different for this version of SQL 18.3.1 in regards to command line?

**Comment by dnethi** [comment]
Not sure how it works from SCCM, but as long as you can run the script with elevated permissions it should succeed. I was able to run "SSMS-Setup-ENU.exe /install /quiet /norestart" via elevated command prompt and successfully installed SSMS 18.4. 
you can also run SSMS-Setup-ENU.exe /help to see available options.

**Comment by Matteo-T** [comment]
@keanankruse: error 1603, unfortunately, is a super generic one. You would have to look ath the setup logs (%TEMP%\SSMSSetup) and see what went wrong. If you can't make sense of what you see, can  you share the content of that folder with us (OneDrive, etc...)?

**Comment by dnethi** [comment]
We have updated the SSMS download page to include the command line install instructions.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
