### ISSUE TITLE
Tutorial Lesson 2-3 step 2 failed to work

### ISSUE THREAD

**Issue by user186** [MicrosoftDocs/sql-docs#2933]
I'm new to SSIS and just started to learn by following the tutorial.

I have MSSQL 2017 server, SSMT, Visual Studio 2017 (SSDT) installed.

Everything was fine until I reached step 2 in https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/integration-services/lesson-2-3-modifying-the-flat-file-connection-manager.md

There is no "PackagePath" nor "Expressions" properties within the Properties window. (Only "File Name" and "Full Path" properties are available). I Googled for hours and still have no clue what's going on, and being stuck here means no way to proceed any further.

Is it my problem or the documentation? Is the tutorial written for a specific version of VS and doesn't work for VS2017?

**Comment by user186** [comment]
Here's the screen capture for reference, it' seems very difficult from what the documentation describes.

![ssis-problem](https://user-images.githubusercontent.com/55093944/64540502-eab4b080-d352-11e9-98c7-ad28f1c6de57.png)

**Comment by WilliamAntonRohm** [comment]
@user186 -- thank you for your feedback.

@janinezhang -- Janine, please investigate this issue 2933.

**Comment by MightyPen** [comment]
@WilliamAntonRohm Hi William, Janine Zhang is *not* a member of the distlist Rogue1, so she cannot be the only Assignee of this Issue #2933.
And in Janine's case, she can almost never work on GitHub Issues.

SSIS documentation has no one clear Writer assigned presently, so I am co-Assigning @rothja  (manager of the SQL Server documentation team).

**Comment by rothja** [comment]
@chugugrace Hello. Could you please help me take a look at this issue? 

@user186 Thank you for your patience, and we apologize for the long delay!

**Comment by chugugrace** [comment]
@user186 sorry for the long delay. 
The properties window shows up when you right click connection managers in the middle frame of the canvas, check red box in below screen shot. 
![image](https://user-images.githubusercontent.com/53034637/66363880-5c1b6980-e9ba-11e9-8ed1-9a7bb2ac1379.png)

**Comment by rothja** [comment]
@chugugrace Thank you for the additional information! @user186 Thank you for your patience. I am going to close this issue now, but if you have any additional questions or if you do not feel this resolves the issue, please let us know in this thread. Thanks!! #please-close
