### ISSUE TITLE
unclear requirements.

### ISSUE THREAD

**Issue by EricF14** [MicrosoftDocs/sql-docs#2934]
There are multiple cases of the word "should" being used in places where the word "must" seems more appropriate. The word "should" implies a best practice but not a requirement. If these are best practices then an explanation should be given as to the alternative and reason for the preference. If these are absolute requirements in order for success then the use of the word "must" is required to ensure proper understanding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4165179c-e336-919e-a590-3b892143f247
* Version Independent ID: 017d0a81-549f-8ac2-dd5d-40c9dc461cdf
* Content: [CREATE VIEW (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-view-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/create-view-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-view-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@EricF14 -- thank you for your feedback.  I have updated the documentation accordingly and it is pending review.

**Comment by WilliamAntonRohm** [comment]
@EricF14 -- Thank you for your feedback.  The documentation should be live by tomorrow.

**Comment by WilliamAntonRohm** [comment]
@CarlRabeler -- Carl, thank you for your review.
