### ISSUE TITLE
Code isn't T-SQL

### ISSUE THREAD

**Issue by mrdenny** [MicrosoftDocs/sql-docs#2936]
That code example is C# not T-SQL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42662ed-e2f2-18f7-037e-c06c62ef4fcc
* Version Independent ID: 3020bedc-7401-7111-50ad-b35474701781
* Content: [sp_changedistributor_password (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-changedistributor-password-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-changedistributor-password-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-changedistributor-password-transact-sql.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@mrdenny -- thank you for your feedback, and can you please provide me with some additional details.  The only example I found on that page is SQL:

```
-- Change the password on the Distributor. 
-- To avoid storing the password in the script file, the value is passed 
-- into SQLCMD as a scripting variable. For information about how to use 
-- scripting variables on the command line and in SQL Server Management
-- Studio, see the "Executing Replication Scripts" section in the topic
-- "Programming Replication Using System Stored Procedures".
USE master
EXEC sp_changedistributor_password $(Password)
GO
```

**Comment by mrdenny** [comment]
$(Password) isn’t a T-SQL variable.  It should look something like this.


USE master

DECLARE @password nvarchar(50) = “YourLongP@$$w0rdHere”

EXEC sp_changedistributor_password @password

GO


Thank You,
Denny Cherry
Owner & Principal Consultant
Denny Cherry & Associates Consulting, an Inc. 5000 company
denny@dcac.com<mailto:denny@dcac.com>
(o) +1 (323) 686-1478<tel:3236861478> | (d) +1 (213) 973-3669<tel:2139733669>
Online Calendar Bookings<https://outlook.office365.com/owa/calendar/DennyCherry@dcac.com/bookings/>
[cid:image001.png@01D5672A.7CAA2370]<http://www.dcac.co/>
[cid:image002.jpg@01D5672A.7CAA2370]
[cid:image003.png@01D5672A.7CAA2370]
[cid:image004.jpg@01D5672A.7CAA2370]

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please review the changes in the above PR.

**Comment by WilliamAntonRohm** [comment]
@mrdenny -- thank you again for your feedback.  I have updated the documentation and it should be live by tomorrow.

@stevestein -- thanks for your review.
