### ISSUE TITLE
Update your version of SQL Server

### ISSUE THREAD

**Issue by KrystinaWoelkers** [MicrosoftDocs/sql-docs#2937]
Hello! I was wondering if security updates are also included in the latest CU. I know that the previous CU fixes are included in the most recent, but I wasn't 100% sure about security updates!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39949710-4382-6df8-9f49-91cc87e2f3e8
* Version Independent ID: a1ceff32-9f8e-5c16-0c6f-95ae1d1e634d
* Content: [SQL Server Documentation - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-technical-documentation?view=sql-server-2017)
* Content Source: [docs/sql-server/sql-server-technical-documentation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/sql-server-technical-documentation.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @craigg-msft
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@KrystinaWoelkers Thank you for the question.

The SQL Server CU update will bring your version to the latest stable release and includes fixes and security updates.  

The list of fixes is included [with the CU release info](https://support.microsoft.com/en-us/help/4508218/cumulative-update-16-for-sql-server-2017) and security information is included with the issue itself.  For example, [this security issue](https://support.microsoft.com/en-us/help/4505222/security-update-for-sql-server-2016-sp2-cu7) was resolved in CU 7.
