### ISSUE TITLE
Issue with SSRS Mobile reports custom Map Instructions

### ISSUE THREAD

**Issue by bluey47** [MicrosoftDocs/sql-docs#2938]
Hi,

https://docs.microsoft.com/en-us/sql/reporting-services/mobile-reports/add-a-custom-map-to-a-reporting-services-mobile-report?view=sql-server-2017

The above page contains incorrect information and I have spent several days trying to get my custom map to work.

It turns out it doesnt use the "NAME" field from the DBF File to match with the key data. It uses the first column in the DBF file regardless of what it contains. So the solution I used was to export only the Name column with the ESRI Shapefile using QGIS.

Please update the documentation so others arn't mislead.

**Comment by maggiesMSFT** [comment]
Thanks for letting us know, @bluey47 ! I'll update the docs to reflect that.

**Comment by maggiesMSFT** [comment]
Hi, @bluey47 -- updating the article today. Thanks!
#please-close

**Comment by bluey47** [comment]
Thanks @maggiesMSFT, much better now. ;-)
