### ISSUE TITLE
misspelling of directorya

### ISSUE THREAD

**Issue by valerymoskalenko** [MicrosoftDocs/sql-docs#2941]
Looks like a misspelling. Instead of "and select the target directorya." should be "and select the target directory."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3df6af-9ac8-bc57-93dc-29ff713c1d3b
* Version Independent ID: 7624e2cc-7aa9-40dd-4015-3371ea2ea0a2
* Content: [Download and install sqlpackage - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-2017)
* Content Source: [docs/tools/sqlpackage-download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage-download.md)
* Product: **sql**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by msebolt** [comment]
@valerymoskalenko Thank you for the feedback.

The documentation has been updated.
