### ISSUE TITLE
The wizard has changed since the article was written

### ISSUE THREAD

**Issue by d3katja** [MicrosoftDocs/sql-docs#2942]
In Visual Studio 2017, 15.9.11, there is no item called Tasks in the context menu. "Extract Data-tier Application..." is placed directly in the menu. The wizard is not looking the same as described in the article. It would be helpful to have a note reading "this article applies to version x, but you can follow it anyway" so you don't wonder if you are in the right place or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06bbcc85-68e9-ee44-04ad-26acb92a195a
* Version Independent ID: 71678aad-04f0-8951-5242-c89fc79d077e
* Content: [Extract a DAC From a Database - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/extract-a-dac-from-a-database?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/data-tier-applications/extract-a-dac-from-a-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/extract-a-dac-from-a-database.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@d3katja - thanks for the feedback.  An internal work item (1637516) has been open to update the article. Thanks for pointing this one out.

#please-close
