### ISSUE TITLE
Link "Redistribution License for Microsoft JDBC Driver 4.0 for SQL Server" is broken

### ISSUE THREAD

**Issue by t104** [MicrosoftDocs/sql-docs#2943]
Link "Redistribution License for Microsoft JDBC Driver 4.0 for SQL Server" is broken.
The link is in this doc (https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/redistributing-the-microsoft-jdbc-driver.md).
It is linked to "https://msdn.microsoft.com/sqlserver/jj589698", but redirected to "https://docs.microsoft.com/en-us/sql/sql-server/sql-server-technical-documentation?view=sql-server-2017".

Microsoft JDBC Driver 4.0 for SQL Server is now totally unavailable?

**Comment by msebolt** [comment]
@t104  Thank you for the feedback.

Assigning this to the author for confirmation.

**Comment by MightyPen** [comment]
@David-Engel Hi David, Can you find a link that should replace the lost link (jj589698) discovered by the customer.

- _Article containing the bad link to the license:_ &nbsp;  `https://docs.microsoft.com/sql/connect/jdbc/redistributing-the-microsoft-jdbc-driver`

- _Another loosely related article, to JDBC licenses:_ &nbsp; `https://docs.microsoft.com/sql/connect/jdbc/frequently-asked-questions-faq-for-jdbc-driver`

@t104 Hi Toshiki, We have begun to process your Issue #2943.  Thanks.
 . .

**Comment by rothja** [comment]
@David-Engel Thanks for the suggestion. Is this something that you can fix in the doc, or do you want @MightyPen or my team to help make the change? Let us know if you can assist with the actual doc change. @t104 Thanks for pointing this out and helping us to remove outdated content!

**Comment by MightyPen** [comment]
New PR 12678 is intended to fix this Issue #2943 .
The PR awaits Review.

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/12678`

cc: @david-Engel @rothja

**Comment by cawrites** [comment]
@t104 I wanted to follow-up to advise you of the following updates: JDBC drivers https://docs.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver15#41 and previous releases https://docs.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver15#previous-releases
These two pages would be your best resources for locating jdbc drivers that are available to download.

**Comment by cawrites** [comment]
@t104 thank you for contacting Microsoft. Please don't hesitate to contact us again if you have any content-related issues.

**Comment by cawrites** [comment]
#please-close
