### ISSUE TITLE
$sqlpsreg

### ISSUE THREAD

**Issue by mco100** [MicrosoftDocs/sql-docs#2944]
incorrect value for registry key on Windows system hosting SQL Server 2019 instance ?
I had to change key name to
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.SqlServer.Management.PowerShell.sqlps150

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca91cbd9-efe5-1de5-7da6-6137b0437a3d
* Version Independent ID: 836f506c-0e26-8277-1a9f-451853e0d21b
* Content: [Load the SMO Assemblies in Windows PowerShell - SQL Server](https://docs.microsoft.com/en-us/sql/powershell/load-the-smo-assemblies-in-windows-powershell?view=sql-server-2017)
* Content Source: [docs/powershell/load-the-smo-assemblies-in-windows-powershell.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/load-the-smo-assemblies-in-windows-powershell.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@mco100, 

Apologizes for the delayed response.

We are looking into this.

**Comment by markingmyname** [comment]
@mco100,

We do not recommend doing it that way.

The actual version after “.sqlps” is dependent on the version of SQL Server installed on the machine (150 is good for SQL2019, 140 is good for SQL2017, etc…)

Hope this helps.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
