### ISSUE TITLE
dbo.agent_datetime(run_date, run_time)

### ISSUE THREAD

**Issue by tomgilmour** [MicrosoftDocs/sql-docs#2955]
As a suggestion: https://www.mssqltips.com/sqlservertip/2850/querying-sql-server-agent-job-history-data/ mentions using the agent_datetime() scalar function to convert the run_date and run_time into a single datetime format, which may be more useful in some situations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1188cb1-de0a-ce57-5baf-40ae903b41ef
* Version Independent ID: 86dc9874-a01d-e26f-d13b-3785ffd5c497
* Content: [dbo.sysjobhistory (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/dbo-sysjobhistory-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-tables/dbo-sysjobhistory-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/dbo-sysjobhistory-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@tomgilmour -- Tom, thank you for your feedback.  I am looking into it.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please look into this issue 2955.

**Comment by stevestein** [comment]
@tomgilmour - thanks for the feedback. We appreciate the suggestion. An internal work item (1642021) has been opened to track potential updates to this article. 

Thanks!

#please-close
