### ISSUE TITLE
Syntax for Step 3 under 'Manual failover without data loss' is not correct

### ISSUE THREAD

**Issue by adamdes** [MicrosoftDocs/sql-docs#2956]
The syntax for Step 3 under 'Manual failover without data loss' is not correct. 

It should be: 
```
ALTER AVAILABILITY GROUP [ag1] 
SET( REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT = 1 );
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e357702e-ddfb-eb9c-d6a5-a5274d87b320
* Version Independent ID: a809b6ec-7bf2-4cce-b4af-c06fdd1b00bd
* Content: [Configure read-scale for an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-read-scale-availability-groups?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/configure-read-scale-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/configure-read-scale-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@adamdes -- thank you for your feedback.  I am looking into it.

**Comment by WilliamAntonRohm** [comment]
@adamdes, I have updated the documentation and it should be live by tomorrow.  Thank you for your keen eye.
