### ISSUE TITLE
"Microsoft Edge constraints" navigation entry under SQL Server 2017/Database design/Tables

### ISSUE THREAD

**Issue by blin4444** [MicrosoftDocs/sql-docs#2957]
Perhaps the title should be "Graph edge constraints" instead of "Microsoft Edge constraints"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0840e04-b52d-2c5f-197d-26bec998fcaa
* Version Independent ID: 40ca3965-4f80-cbb3-839c-3244a536675e
* Content: [Graph edge constraints - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/graph-edge-constraints?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/tables/graph-edge-constraints.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/graph-edge-constraints.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @shkale-msft
* Microsoft Alias: **shkale**

**Comment by msebolt** [comment]
@blin4444  Thank you for the feedback.

The documentation has been updated.
