### ISSUE TITLE
Where can I find out what the number returned means?

### ISSUE THREAD

**Issue by JoelMacKenzie** [MicrosoftDocs/sql-docs#2964]
I have error 547.  What did I do wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6493c898-6f12-f44f-26df-28864300c101
* Version Independent ID: 9c3a6e72-7f63-7e73-722c-433e43715770
* Content: [ERROR_NUMBER (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/error-number-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/error-number-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/error-number-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
Closing this now, please comment below if there are further issues.
