### ISSUE TITLE
Incorrect application name

### ISSUE THREAD

**Issue by iuriivaschuk** [MicrosoftDocs/sql-docs#2972]
Incorrect application name addpy.
Must be add-app

azdata app describe --name addpy --version v1
"app": "https://10.1.1.3:30080/app/addpy/v1",
"swagger": "https://10.1.1.3:30080/app/addpy/v1/swagger.json"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8546addb-1209-b474-62c8-3efe0967739f
* Version Independent ID: cc4639e5-93d2-0203-ff74-26e6f2fb82b6
* Content: [Consume applications on SQL Server big data clusters - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/big-data-cluster-consume-apps?view=sqlallproducts-allversions)
* Content Source: [docs/big-data-cluster/big-data-cluster-consume-apps.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/big-data-cluster-consume-apps.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @jeroenterheerdt
* Microsoft Alias: **jterh**

**Comment by msebolt** [comment]
@iuriivaschuk Thank you for the feedback.

The documentation has been updated.
