### ISSUE TITLE
Need another example of how to read an array of JSON objects 

### ISSUE THREAD

**Issue by kae36** [MicrosoftDocs/sql-docs#2973]
All the JSON object examples in the documentation of JSON_VALUE and JSON_QUERY seem to only show examples of how to handle a single root JSON object, but there are no examples of how to handle an array of JSON Objects at the root level.   For example, consider these arrays of JSON objects.

First Example, Where the Array is an array of a JSON object (type, name, value).
`
DECLARE @json NVARCHAR(MAX)
SET @json=N'[{"type": "textfield", "name": "date", "value": "12/15/2005 14:51:35"},{"type": "textfield", "name": "fullname", "value": "John Doe"}]'
`

Second Example, Another type of Array of JSON objects is simple JSON object (key, value)
`
SET @json=N'[{"key": "Alabama"}, {"key": "Alaska"}, {"key": "Arizona"}, {"key": "Arkansas"}, {"key": "California"}, {"key": "Colorado"}, {"key": "Connecticut"}, {"key": "Delaware"}, {"key": "Florida"}]'
`

I'm not sure if this is because the JSON Object functions do not support the array of JSON objects type of root JSON object?  If that's the case, then this is not a documentation issue.
(not sure why this was inserted as bold and larger text)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67023ef0-dd62-a8b2-12ee-3a06673f6152
* Version Independent ID: 7cd50e87-de1a-2204-3c9f-470e9bbda3ac
* Content: [JSON_QUERY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-query-transact-sql?view=sql-server-2016)
* Content Source: [docs/t-sql/functions/json-query-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/json-query-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by jovanpop-msft** [comment]
JSON_VALUE can reference a value in the JSON array but you would need to explicitly hardcode the index for every path, like: `SELECT JSON_VALUE(@json, '$[2].key')`

In this case it is better to use OPENJSON because it is designed to process array and return table as result.

**Comment by WilliamAntonRohm** [comment]
@kae36 -- Alan, I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
