### ISSUE TITLE
Files still in use.

### ISSUE THREAD

**Issue by Ditronian** [MicrosoftDocs/sql-docs#2974]
After closing the solution, Visual Studio keeps using it for a prolonged period of time, making it un-deletable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd2c8cc5-dfd5-bcf8-cb75-e0d44ffe13bf
* Version Independent ID: d2af2fb6-203c-87d7-e8eb-151a9c46af29
* Content: [Delete a Solution - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/solution/delete-a-solution?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/solution/delete-a-solution.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/solution/delete-a-solution.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@Ditronian -- thank you for your feedback.  Please see [UserVoice - Suggestion to improve SQL Server?](https://feedback.azure.com/forums/908035-sql-server).

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
