### ISSUE TITLE
"sysmail_add_principalprofile_sp" introduction uses the term "role" incorrectly

### ISSUE THREAD

**Issue by RobAshton-IM** [MicrosoftDocs/sql-docs#2975]
The introduction paragraph to the "sysmail_add_principalprofile_sp" stored procedure uses the term "role". This can lead the reader to imply that it is possible to associate either Application Roles or Database Roles in the msdb database to a Database Mail profile.

This is incorrect; the "sysmail_add_principalprofile_sp" stored procedure internally calls the "sysmail_verify_principal_sp" stored procedure. That stored procedure limits the types of database principals that it will consider to only:
- SQL Users (sys.database_principals.type = 'S')
- Windows Users (sys.database_principals.type = 'U')
- Windows Groups (sys.database_principals.type = 'G')

The introduction paragraph should be reworked to make a more direct connection to the type of database principal that it supports. For example:
"Grants permission for a msdb database principal that maps to a SQL Server authentication user, a Windows User, or a Windows Group to use a Database Mail profile."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ed886c2-1f0a-13d1-7957-24f29ca51e91
* Version Independent ID: 8fe46f71-dca4-cf00-589b-e7e41e8aca25
* Content: [sysmail_add_principalprofile_sp (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sysmail-add-principalprofile-sp-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sysmail-add-principalprofile-sp-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sysmail-add-principalprofile-sp-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@RobAshton-IM -- thank you for your feedback.  I've updated that article and it is in review.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
