### ISSUE TITLE
Need more complete info

### ISSUE THREAD

**Issue by MarkB-Dansko** [MicrosoftDocs/sql-docs#2976]
The example powershell script under "Starting and stopping a service in PowerShell"
Does not show how to connect the ManagedComputer instance to a different (remote) SQLServer machine. Can this be enhanced to show that (rather significant) detail?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c80d6fd-2aa6-ddb6-1184-4c170adb827f
* Version Independent ID: 5424cd3f-c447-653a-81a5-957a1e22d330
* Content: [Managing Services and Network Settings by Using WMI Provider - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/tasks/managing-services-and-network-settings-by-using-wmi-provider?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/server-management-objects-smo/tasks/managing-services-and-network-settings-by-using-wmi-provider.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/server-management-objects-smo/tasks/managing-services-and-network-settings-by-using-wmi-provider.md)
* Product: **sql**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@MarkB-Dansko -- thank you for your suggestion.

@markingmyname -- please look into adding this information.

**Comment by MarkB-Dansko** [comment]
@Mark Ghanayem / @markingmyname :

I suggest that the following answers the question I posited:
"#Get a managed computer instance  
$mc = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer  "
- will retrieve the ManagedComputer instance for the local computer
"#Get a managed computer instance  
$mc = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer  "YourRemoteComputerNameHere" "
- will retrieve a ManagedComputer instance for the named remote computer (assuming it is available on the network)

On a different, but related point, the first line in this example uses a now-deprecated method call to load the library:
"#Load the assembly containing the objects used in this example  
[reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.SqlWmiManagement")  "

Current Microsoft preferences are to use:
"[System.Reflection.Assembly]::Load("Microsoft.SqlServer.sqlwmiManagement, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91")" instead (note that the version numbers are required and are specific to the installed SQL Server library versions in use, but the PublicKeyToken is the same across versions)

**Comment by markingmyname** [comment]
@MarkB-Dansko,

Thank you for your comment.

Are you suggesting we add this info to the article?

**Comment by markingmyname** [comment]
Closing due to no response.
