### ISSUE TITLE
SQLSRV_CONNECT NO REGRESA TODOS LOS REGISTROS DEL QUERY

### ISSUE THREAD

**Issue by jaimeres** [MicrosoftDocs/sql-docs#2982]
Hola tengo un problema con sqlsrv_connect en PHP

Me conecto desde php Ubuntu por medio de SQLSRV_CONNECT a SQL, hasta ahora todo bien, el detalle es que al consultar bastante información y solo esta regresando 13846, el mismo query lo ejecuto en Server 2014 Management Studio y regresa casi 30000 registros.

`$resOC=$objCon->ejecutar($query);
$con=0;
while($c= sqlsrv_fetch_array($resOC))
{
$con++;
  array_push($result, array(
    'con'					=>$con,
    'UsuCreacion'=>			$c['UsuCreacion']
  ));
}
echo json_encode($result);`

`function conectar()
{
  if (!($this->c= sqlsrv_connect($this->s, $this->d)))
  {
	return array(
	 'isError'	=> true,
	 'msg'      =>'Error al cargar las ordenes de compra'./*$this->formatoE(*/var_dump(sqlsrv_errors())/*)*/
	);
  }
  else
  {
	return (array(
	 'isError'	=> false,
	 'msg'      => 'Conexión exitosa'
	));
  }
}
 
// consultar la base de datos
function ejecutar($query)
{
   return $stmt = sqlsrv_query($this->c, $query);
   $this->cerrarConexion() ;
}

// cierra una conexion con sqlserver
function cerrarConexion()
{
	sqlsrv_close($this->c);
}`
![image](https://user-images.githubusercontent.com/19354871/64917969-d9a5de00-d75c-11e9-8142-8964d8fd9129.png)

**Comment by msebolt** [comment]
@jaimeres Gracias por la pregunta. Lamentamos que tengas problemas.

Pruebe una muestra más simple según [este artículo](https://docs.microsoft.com/sql/connect/php/sqlsrv-fetch-array?view=sql-server-2017#example) y vea si los resultados coinciden.

**Comment by msebolt** [comment]
@jaimeras Closing issue, please comment below if you have any questions.
