### ISSUE TITLE
TABLE_SCHEMA reliability warning - is this still valid?

### ISSUE THREAD

**Issue by griffinator76** [MicrosoftDocs/sql-docs#2984]
As raised years ago on Connect (https://web.archive.org/web/20121126175858/http://connect.microsoft.com/SQLServer/feedback/details/686118/doc-information-schema-tables-gives-improper-warning-about-schema) the INFORMATION_SCHEMA definition uses the same underlying schema_id as sys.objects so there doesn't appear to be any possible way it could show a different schema to the one in the sys catalog views.
The response to the Connect article added the note about INFORMATION_SCHEMA not being updated for new features, but didn't really address the point that this vague warning about unreliability is quite unhelpful. 
Many SQL tools and drivers rely on the INFORMATION_SCHEMA views to return metadata and they are part of the SQL standard and important for inter-operability so it's quite unhelpful if this is true (the views are inaccurate) but the information supplied in the document doesn't offer any elaboration on what circumstances schema might not be accurate which leaves the user unable to make an informed decision whether to use them or not.
Can it be clarified whether or not these views really are still unreliable, and if so under what circumstances?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e30b4e4b-db09-dca7-eb8d-41cf92e44f7c
* Version Independent ID: 8cc873ab-faef-83bb-44c9-dc3ade947f76
* Content: [TABLES (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-information-schema-views/tables-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-information-schema-views/tables-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-information-schema-views/tables-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@griffinator76 -- thank you for your feedback.

@CarlRabeler -- please look into this issue 2984.

**Comment by CarlRabeler** [comment]
it is true there are some cases where the information schema views are incomplete and that can lead to semantically broken applications if you are unaware.

**Comment by CarlRabeler** [comment]
#please-close

**Comment by griffinator76** [comment]
What specifically are "the cases" though? Without further information this is not helpful and renders the information schemas basically useless.
