### ISSUE TITLE
Incorrect master service url

### ISSUE THREAD

**Issue by iuriivaschuk** [MicrosoftDocs/sql-docs#2986]
mssql_spark_connector.ipynb contain incorrect master service url

servername = "jdbc:sqlserver://master-0.master-svc"
master-0 - not service name

servername = "jdbc:sqlserver://master-svc"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e7588-f740-33b4-303b-e927f3400414
* Version Independent ID: 186607e3-fd55-5d9b-2cfc-26120fc438ad
* Content: [Connect Spark to SQL Server - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/spark-mssql-connector?view=sqlallproducts-allversions)
* Content Source: [docs/big-data-cluster/spark-mssql-connector.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/spark-mssql-connector.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@iuriivaschuk Thank you for the feedback.  

This is a product issue as opposed to documentation.

Can you move the issue to the [sql-server-samples](https://github.com/microsoft/sql-server-samples/issues) issues?
