### ISSUE TITLE
Error after following instructions

### ISSUE THREAD

**Issue by rkhjjs** [MicrosoftDocs/sql-docs#2988]
I followed the instructions and examples on this page and on running the script I got this error:

`All files must be specified for database snapshot creation. Missing the file "ggc".`

The article needs a note saying the `NAME` parameter must be the same as the logical name of the data file, otherwise error 5127 is shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75a530e-446a-a521-c186-488cbed9b463
* Version Independent ID: 417b56a6-e21c-c7d1-8fe9-04caf78fd3a4
* Content: [Create a Database Snapshot (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/create-a-database-snapshot-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/databases/create-a-database-snapshot-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/create-a-database-snapshot-transact-sql.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@rkhjjs  Thank you for the feedback.

The documentation has been updated.
