### ISSUE TITLE
Section 4.a threshold option is set to 0

### ISSUE THREAD

**Issue by g-kannan** [MicrosoftDocs/sql-docs#2989]
Should the vaule for "@threshold_alert_enabled" to be 1 in 4.a "On the new primary server"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea474667-7ade-302f-1906-695a8f86b122
* Version Independent ID: 17205b9e-5555-1ff8-cca6-2689b9c54aaa
* Content: [Change Roles Between Primary and Secondary Log Shipping Servers (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/log-shipping/change-roles-between-primary-and-secondary-log-shipping-servers-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/log-shipping/change-roles-between-primary-and-secondary-log-shipping-servers-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/log-shipping/change-roles-between-primary-and-secondary-log-shipping-servers-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@g-kannan -- Kannan, thank you for your feedback.

@MashaMSFT -- please look into this issue 2989.

**Comment by MikeRayMSFT** [comment]
@pmasl or @bluefooted  - this submission looks correct, so we're going to proceed and accept the submission. Including you for visibility.

@g-kannan  thank you for your feedback.

**Comment by bluefooted** [comment]
Shouldn't this be 1 for both statements? One statement turns on the backup threshold alert and the other statement turns on the restore threshold alert. If the premise is that monitoring was enabled before and we want to keep it enabled, both of these should be 1.

**Comment by bluefooted** [comment]
Adding @kfarlee to see if he has any insight, my log shipping knowledge is pretty rusty.

**Comment by MikeRayMSFT** [comment]
We have updated the article in https://github.com/MicrosoftDocs/sql-docs-pr/commit/09fe2f89fbe61cbb763ea29572f533814690ea7e

**Comment by MashaMSFT** [comment]
Hi @g-kannan, thanks again for bringing this to our attention and for making our docs better :) We've updated the documentation to set the enable the alert for both the primary and secondary servers, and this change should be live tomorrow.

Please let us know if anything further is needed? If not, we will proceed with closing out this Git Issue in a few business days if we don't hear back from you.

Thanks again and hope you have a wonderful rest of your day!
Masha from the SQL Docs team

**Comment by g-kannan** [comment]
Thanks everyone for the updates and great work..  Happy to work with MS & its products..
