### ISSUE TITLE
Doesn't work in Azure SQL Data Warehouse

### ISSUE THREAD

**Issue by ameert** [MicrosoftDocs/sql-docs#2990]
Document says it applies to SQL Data Warehouse, but I get 
Msg 104162, Level 16, State 1
'FORMAT' is not a recognized built-in function name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f019407-5787-6f54-1027-084e817b6b8e
* Version Independent ID: a92541d0-b63a-9603-2a1f-18e210be89e4
* Content: [FORMAT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/format-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/format-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/format-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@ameert -- Alan, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue 2990.

**Comment by MikeRayMSFT** [comment]
@ameert - thanks for the feedback. We're checking.

**Comment by MikeRayMSFT** [comment]
@ameert - FORMAT() appears to work on SQL Data Warehouse.

![format](https://user-images.githubusercontent.com/15928587/65560373-3f2f6280-def3-11e9-9d78-42911d6e5149.png)

**Comment by MikeRayMSFT** [comment]
@ameert - can you verify if the function now works for you? If it does not, can you tell me what region your Azure SQL DB is in?

**Comment by ameert** [comment]
Hi,

This worked for me today without issue.

Thanks,
Alan

**Comment by MikeRayMSFT** [comment]
Thanks @ameert - I have confirmed that the feature roll-out is very recent. Glad it worked for your.
