### ISSUE TITLE
Database audit

### ISSUE THREAD

**Issue by MichaelFirsov** [MicrosoftDocs/sql-docs#2992]
"Audit - The name of an existing database audit." - the words "database audit" may be misleading here because all audits can be created only on server level - there's no such term as "Database audit". In the beginning of the article you write "To create a server audit ..." and later refer to that audit object as "database audit".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cf3c337-46df-17f4-7daf-f03e0759c196
* Version Independent ID: daa49989-f4ba-3bb9-3491-5e7e2d1a4523
* Content: [Create a Server Audit and Database Audit Specification - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/create-a-server-audit-and-database-audit-specification?view=sql-server-2017)
* Content Source: [docs/relational-databases/security/auditing/create-a-server-audit-and-database-audit-specification.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/auditing/create-a-server-audit-and-database-audit-specification.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hello @MichaelFirsov! Thanks for the feedback. We appreciate the input. I changed the wording to specify "existing server audit object" instead of "database audit". These changes should reflect later today. Again, we appreciate your help on our documentation.

https://github.com/MicrosoftDocs/sql-docs-pr/pull/12066

#please-close

**Comment by MichaelFirsov** [comment]
Thank you all!
