### ISSUE TITLE
Syntax errors in example script to create AG with dtc_support

### ISSUE THREAD

**Issue by Ventilios** [MicrosoftDocs/sql-docs#2994]
The script to create an Availability Group with DTC Support contains syntax errors. 
1. Server1 and Server2 need to be enclosed by single quotes. 
2. Missing comma between the specified replica's.
CREATE AVAILABILITY GROUP MyAG
   WITH (
      DTC_SUPPORT = PER_DB  
      )
   FOR DATABASE DB1, DB2
   REPLICA ON
      'Server1' WITH (
         ENDPOINT_URL = 'TCP://SERVER1.corp.com:5022',  
         AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,  
         FAILOVER_MODE = AUTOMATIC  
         ),
      'Server2' WITH (
         ENDPOINT_URL = 'TCP://SERVER2.corp.com:5022',  
         AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,  
         FAILOVER_MODE = AUTOMATIC  
         )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4525f922-c768-bb9c-fc93-4a3b790c03fb
* Version Independent ID: f50f9610-c6a6-0fad-5f53-975a64a53704
* Content: [Configure distributed transactions for an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-availability-group-for-distributed-transactions?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/configure-availability-group-for-distributed-transactions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/configure-availability-group-for-distributed-transactions.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@Ventilios -- Ymer, thank you for your feedback.  I am updating the documentation.

**Comment by WilliamAntonRohm** [comment]
@Ventilios -- Ymer, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
