### ISSUE TITLE
Error Code 3106

### ISSUE THREAD

**Issue by majormfa32** [MicrosoftDocs/sql-docs#3001]
This error code is missing from the list above. It's been called out in numerous social.msdn.microsoft.com blogs and readers of docs.microsoft.com could benefit from adding a description of the error code. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 248641a9-2364-dcbf-b071-6df585b05bba
* Version Independent ID: bd00d184-ff67-3b36-2d8f-22d05538a92f
* Content: [SQL Server Connector Maintenance & Troubleshooting - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/sql-server-connector-maintenance-troubleshooting?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/encryption/sql-server-connector-maintenance-troubleshooting.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/sql-server-connector-maintenance-troubleshooting.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @aliceku
* Microsoft Alias: **aliceku**

**Comment by VanMSFT** [comment]
Thanks for the suggestion, @ermajor32! We will investigate this feedback.

**Comment by rothja** [comment]
@jaszymas, I believe you're the new owner of this content. Can you take a look? Thank you! #reassign:jaszymas

**Comment by VanMSFT** [comment]
Hello @ermajor32! Sorry for the delay. I will investigate the error codes with the Product Group and follow-up in this thread.

**Comment by VanMSFT** [comment]
This has been added with the update to the SQL Server Connector articles.
