### ISSUE TITLE
Escaping in Azure SQL DW

### ISSUE THREAD

**Issue by Willem-J-an** [MicrosoftDocs/sql-docs#3008]
Soo.. how do I escape stuff in Azure SQL DW?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5353a04-2e20-ae05-2004-6fd8a19c440a
* Version Independent ID: 382b0acd-1e14-c7fd-bf92-c3e09ccdf4fa
* Content: [LIKE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/language-elements/like-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/like-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by msebolt** [comment]
@Willem-J-an Thank you for the question.

Please try using the [SQL Server escape character](https://stackoverflow.com/questions/5139770/escape-character-in-sql-server).  

It seems odd there's no official documentation on this, assigning to the author for further feedback.

**Comment by Willem-J-an** [comment]
The linked page I assume would work to escape single quotes, but not wildcards such as _ or %, might have to verify that assumption.

**Comment by julieMSFT** [comment]
@XiaoyuMSFT Hi Xiaoyu, is there an escape character for Azure Synapse Analytics (SQL DW)?

**Comment by shikharbsar** [comment]
What's the similar syntax for escape character in SQL SERVER in Azure Synapse Analytics (SQL DW)?

**Comment by julieMSFT** [comment]
@Willem-J-an @shikharbsar Thank you for your question.  Azure Synapse Analytics (SQL DW) does not currently support escaping, including for wildcard characters. We will be updating the article to reflect this. You can request this feature enhancement at https://feedback.azure.com/forums/307516-azure-synapse-analytics.

**Comment by julieMSFT** [comment]
@Willem-J-an @shikharbsar The document has been updated to show that ESCAPE and STRING_ESCAPE are not supported in Azure SQL Data Warehouse or Parallel Data Warehouse. I will go ahead and close this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close

**Comment by julieMSFT** [comment]
#please-close
