### ISSUE TITLE
upgrade without Failover Cluster

### ISSUE THREAD

**Issue by fredobas** [MicrosoftDocs/sql-docs#3009]
In the section of this page, "Steps for side-by-side migration of the Distributor to Windows Server 2012 R2", about the case "current OS is Windows 2008", you say that need to perform a side-by side upgrade of the OS to Windows Server 2012 R2 or greater.
You explain on of the reason is "Windows Server 2008/20008 R2 does not in-place upgrades for Failover Clusters.
My question: what about the case Windows Server 2008 WITHOUT Failover Clusters? Can we upgrade in-place from Windows Server 2008 (no Failover Cluster)with SQL 2008, to Windows 2016, SQL 2016, upgrading first the OS, then the SQL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dbb2d0f-c435-74e6-384b-0b5137de9ff3
* Version Independent ID: a8489139-6d4c-223e-e39a-99b7510ef228
* Content: [Upgrade or patch replicated databases - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/upgrade-replicated-databases?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/install-windows/upgrade-replicated-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/upgrade-replicated-databases.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @fredobas , thanks for contacting Microsoft! Let me investigate this for you. Please note that, depending on the complexity, this process might take a few weeks.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @fredobas, thank you for your patience as we continue investigating your issue! [Upgrading Windows 2008 and 2008 R2 directly to Windows 2016 is not supported](https://docs.microsoft.com/en-us/windows-server/get-started/modernize-windows-server-2008) whether or not the failover cluster installation feature is installed. I've updated the documentation to reflect this, removing the mention of the FCI component entirely. This change should be live later today. 

Thanks for bringing this to our attention and helping improve our docs :) Please let us know if there is anything further we can assist with? If not, we will proceed with closing out this Git Issue in a few business days.

Thanks and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
