### ISSUE TITLE
Change Tracking with Clustered Columnstore Indexing

### ISSUE THREAD

**Issue by abair34** [MicrosoftDocs/sql-docs#3010]
Above you note:

"SQL Server 2014 (12.x) specific limitations
These limitations apply only to SQL Server 2014 (12.x). In this release, we introduced updateable clustered columnstore indexes. Nonclustered columnstore indexes were still read-only.

Change tracking. You cannot use change tracking with nonclustered columnstore indexes (NCCI) because they are read-only. It does work for clustered columnstore indexes (CCI)."

I'm not sure that Change Tracking can be enabled on CCI's as the text states.

When enabling change tracking on a table with CCI you receive the error below..

Msg 35353, Level 16, State 1, Line 3
Change Tracking cannot be enabled on a table with a clustered columnstore index.  Consider dropping clustered columnstore index '%s' on table '%s'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 195f6bd5-e394-7695-3fed-2cb092db31b9
* Version Independent ID: 3bab1457-be3c-b344-feb3-f8b00a4f916d
* Content: [CREATE COLUMNSTORE INDEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-columnstore-index-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/create-columnstore-index-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-columnstore-index-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@abair34  Thank you for the feedback, assigning the author now.

**Comment by CarlRabeler** [comment]
fixing now - thanks for submitting this issue.
#please-close
