### ISSUE TITLE
Multiple Queue Reader - Activation Procedure Spawning

### ISSUE THREAD

**Issue by JediSQL** [MicrosoftDocs/sql-docs#3011]
While I imagine it is probably true, it would be good if this topic had some explicit details about, or references to, how activated store procedure calls are spawned when MAX_QUEUE_READERS is greater than 1. Does each one get its own SPID? If my internal activation stored procedure creates a #Temp table, will each parallel executing copy of the proc get its own #Temp table without cross-talk?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f996c3a4-8cd7-2046-9819-acd3fb7ffb5f
* Version Independent ID: 6714dee4-7077-56d2-1227-83d1ab0d6638
* Content: [CREATE QUEUE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-queue-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/create-queue-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-queue-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by JediSQL** [comment]
I found the "Internal Activation Context" topic at
https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms171585%28v%3dsql.105%29
In the "Session Settings" section, it says "Service Broker executes internally activated service programs on a background session distinct from the connection that created the message." It is not explicit whether parallel activated procs are on separate background sessions. A strict interpretation of that text is "programs" (plural) on "a" (singlular) background session... It does not say "distinct from each other."

**Comment by msebolt** [comment]
@JediSQL Thank you for the feedback.  

This has been assigned to the author.

**Comment by CarlRabeler** [comment]
This question is answered here: https://stackoverflow.com/questions/44116727/does-service-broker-use-the-same-session-for-stored-procedure-exec-risk-of-tem/44126719#44126719

**Comment by CarlRabeler** [comment]
#please-close
