### ISSUE TITLE
Viewing Transaction Logs in Azure Portal

### ISSUE THREAD

**Issue by aayush3667** [MicrosoftDocs/sql-docs#3012]
Hi,

I was viewing the transaction logs in SQL server. 
My question is Can we see the transaction logs in Azure Portal or using Azure PowerShell?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea2ebe6c-220c-c582-6259-6b3867cc6d99
* Version Independent ID: 8cd2d494-c723-f4b7-4dc4-4809196d6579
* Content: [The Transaction Log (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/logs/the-transaction-log-sql-server?view=sql-server-2017)
* Content Source: [docs/relational-databases/logs/the-transaction-log-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/logs/the-transaction-log-sql-server.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @aayush3667 , thanks for contacting Microsoft! Let me check for you. Please note that, depending on complexity, this may take some time.

Thanks!
Masha from the SQL Docs team

**Comment by aayush3667** [comment]
Hi,

still waiting for the solution.

Thanks

**Comment by MashaMSFT** [comment]
Hi @aayush3667 , thank  you for patience :) I am still investigating, but I do apologize for the delay.

Thanks!
Masha from the SQL Docs team

**Comment by anosov1960** [comment]
Hi @aayush3667,
Azure SQL database  blocks the ability to parse the tx log. This is because we truncate it regularly so even if allowed it would be of limited duration.  
Thank you

**Comment by MashaMSFT** [comment]
Hi @aayush3667, just wanted to check in with you and see if you are able to provide a need to read the log? Please note, if we don't hear back from you soon, we will assume your question has been answered and close out this Git Issue.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @aayush3667 , since it's been some time since we've heard from you, we'll assume that your issue has been resolved and close out this Git Issue. However, please feel free to respond via comment should you need anything further.

Thanks and hope you have a wonderful rest of your day!
Masha from SQL Docs team
