### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by NuNn-DaDdY** [MicrosoftDocs/sql-docs#3015]
Rolling Upgrade - Missing space (SQL Serverinstance) in 2nd sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916e128d-19fd-1f7d-8285-6313c4419710
* Version Independent ID: 8402af42-fdd1-2f3b-7c6a-8759e90e115f
* Content: [Choose a database engine upgrade method - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/choose-a-database-engine-upgrade-method?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/install-windows/choose-a-database-engine-upgrade-method.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/choose-a-database-engine-upgrade-method.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @NuNn-DaDdY , thanks for contacting Microsoft and finding this typo! Did you want to make this change yourself? This will add you as a contributor to the article, and it's a very simple process. 

To do so, please do the following:

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Name your file change and provide a description, if necessary
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page

Please let me know if you wanted do it yourself, or I would be happy to do so.

Thanks!
Masha from the SQL Docs team

**Comment by NuNn-DaDdY** [comment]
Good Afternoon Masha,

Sure - I'd be happy to create a pull request.  This has been completed and
a pull request has been created.  Thank you very much for the instructions
as well. Have a great day!

Best Regards,
Corey Nunnery

**Comment by MashaMSFT** [comment]
Hi @NuNn-DaDdY , awesome, thank you so much! I've signed off on the PR and you should see the change live in the next two business days :) Thanks again for making our documentation better! I will proceed with closing out this Git Issue but please feel free to reply should you need anything further.

Thanks!
Masha from the SQL Docs team
