### ISSUE TITLE
Connect to Azure Data Lake using Polybase

### ISSUE THREAD

**Issue by SuperSing** [MicrosoftDocs/sql-docs#3023]
Is it possible to connect to Azure Data Lake Gen2 ( or Gen1)  using Polybase in SQL Server ? Thanks !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ab99ca-282b-6ace-6354-09a0d3ad97ad
* Version Independent ID: 7448fdc3-2a74-1811-38c5-aafcef2630e7
* Content: [Configure PolyBase to access external data in Azure Blob Storage - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-configure-azure-blob-storage?view=sql-server-2017)
* Content Source: [docs/relational-databases/polybase/polybase-configure-azure-blob-storage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-azure-blob-storage.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@SuperSing Thank you for the question, assigning this to the author now.

**Comment by MikeRayMSFT** [comment]
@uc-msft - do you have any comment on this?

**Comment by MikeRayMSFT** [comment]
Hi @SuperSing - apologies for the delay. Currently here is the answer:

- Connection to ADLS Gen 1 is not supported.
- Connection to ADLS Gen 2 may be supported if the ADLS does not use a hierarchical namespace. To connect, create an external data source that connects to Azure Blob Storage with a `wasb` location prefix. See CREATE EXTERNAL DATA SOURCE (Transact-SQL).  
- Additional connection scenarios are supported with [Multi-protocol access for Azure Data Lake Storage](https://aka.ms/mpaadls), which is currently available in public preview.

**Comment by sgiovinetti** [comment]
Could you please give more details on Additional connection scenarios are supported with Multi-protocol access for Azure Data Lake Storage, which is currently available in public preview?

This is not in preview anymore but no documentation around for connecting SQL 2019 to ADLS Gen2 using polybase. Thanks.

You said "Connection to ADLS Gen 2 may be supported if the ADLS does not use a hierarchical namespace." but if i'm not wrong the hierarchical namespace is what makes a normal blob storage account an adls gen 2 storage account. If you don't enable it you end up with a standard blob storage account so what's the point ?
