### ISSUE TITLE
Does not address Azure SQL

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/sql-docs#3026]
This article should either contain or link to information about using this command with Azure SQL Databases. Is it even possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4d7aeba-7fae-3de0-74b3-2c5705ed664c
* Version Independent ID: ce019d19-6617-737f-ccd7-65d77047a7fc
* Content: [Specify Instances in the SQL Server PowerShell Provider - SQL Server](https://docs.microsoft.com/en-us/sql/powershell/specify-instances-in-the-sql-server-powershell-provider?view=sql-server-2017)
* Content Source: [docs/powershell/specify-instances-in-the-sql-server-powershell-provider.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/specify-instances-in-the-sql-server-powershell-provider.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@MisinformedDNA -- Dan, thank you for your question.

@markingmyname -- Mark, please look into this issue 3026.

**Comment by markingmyname** [comment]
@MisinformedDNA MisinformedDNA

Are you looking for a specific scenario or just that Azure SQL is mentioned?  Because if so, then there is information about Azure SQL.  It is at the top of the article where it states what this article applies to.

**Comment by MisinformedDNA** [comment]
Awesome, it applies. So now how would you connect? Do I enter the full server URL for the computer name? Do I need to specify TCP and post? What about the Database Engine? What would I put there?
There are no examples of how/what needs to change with an Azure SQL DB.

**Comment by markingmyname** [comment]
@MisinformedDNA,

I am still working with the engineering group to get these details.

Thank you.

**Comment by markingmyname** [comment]
@MisinformedDNA,

We apologize for not replying sooner.

Your ask has been passed on to our product team and they agree we should add some examples for Azure SQL.

I can't provide an ETA, but we will be working on this.

**Comment by markingmyname** [comment]
@MisinformedDNA 

If you are looking for Azure SQL samples here is a place to [start](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-powershell-samples?tabs=single-database).

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
