### ISSUE TITLE
DACPAC for SQL Server 2014?

### ISSUE THREAD

**Issue by paramda** [MicrosoftDocs/sql-docs#3028]
URL says 2017 but the Note says this:
 Important
This article is valid for SQL Server 2012, but not for SQL Server 2014 or later. For DAC articles about SQL 2012 and earlier, see the following links:
https://docs.microsoft.com/previous-versions/sql/sql-server-2008-r2/ee240739(v=sql.105)
https://docs.microsoft.com/previous-versions/sql/sql-server-2012/hh753459(v=sql.110)

Where is the page for 2014 and later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f0297c-1e1f-fe6e-4b0f-9fd5d2cebfd8
* Version Independent ID: 55771482-ffea-379b-8f32-11ddd69bb301
* Content: [DAC Support For SQL Server Objects and Versions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/dac-support-for-sql-server-objects-and-versions?view=sql-server-2017)
* Content Source: [docs/relational-databases/data-tier-applications/dac-support-for-sql-server-objects-and-versions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/dac-support-for-sql-server-objects-and-versions.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@paramda -- thank you for your question.

@stevestein -- please look into this issue 3028.

**Comment by vinothrao** [comment]
I do not understand. I have Azure SQL database. I am trying to generate bacpac through code and saving it in a Azure Storage. But getting the error "database source is not a supported version of sql server". I really do not understand why. If it is local then  i could update. But this is Azure sql. Please help.

**Comment by stevestein** [comment]
@paramda - thanks for the feedback.  The article is not up-to-date for SQL versions later than 2012. An internal work item (1642012) has been opened to track the work related to updating this section of documentation. If you have specific questions try one of the links located here: https://docs.microsoft.com/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-ver15#info_tip-get-help 

Thanks

#please-close
