### ISSUE TITLE
Added @CONTOSO.COM in several commands seems to be unnecessary

### ISSUE THREAD

**Issue by vic-t** [MicrosoftDocs/sql-docs#3029]
It seems to me that a few commands have @CONTOSO.COM added to them without good reason. For example, the command 

kvno MSSQLSvc/**&lt;fully qualified domain name of host machine&gt;**:**&lt;tcp port&gt;**@CONTOSO.COM

Does not work for me. But if I leave out @CONTOSO.COM (which anyway is already part of the fully qualified domain name), it works. 

I guess the same goes for other commands on this page but I haven't checked all of them just yet. 

And as another side note, according to the official Microsoft documentation, the flag -A is obsolete for setspn.exe, -S should be used instead. Apparently, for backward compatibility, -A still works but is translated to -S. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Use AD authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **dygray**

**Comment by WilliamAntonRohm** [comment]
@vic-t -- Vic, thank you for your feedback.

@Dylan-MSFT -- Dylan, please look into this issue 3029.

**Comment by Dylan-MSFT** [comment]
In my testing on several systems, the final @CONTOSO.COM does not make a difference. If it is omitted, the kvno implementation appends it anyways, so it does not make a difference

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
