### ISSUE TITLE
Default Encryption Algorithm

### ISSUE THREAD

**Issue by NuNn-DaDdY** [MicrosoftDocs/sql-docs#3030]
Note - If using two different versions of SQL Server, you may want to explicitly state the encryption algorithm in case the servers use different algorithms as their default.  Otherwise, you'll end up with the following error message that doesn't state the culprit being the different algorithms:  

The server network address “TCP://foo.bar:5022” cannot be reached or does not exist. Check the network address name and that the ports for the local and remote endpoints are operational. (Microsoft SQL Server, Error:1418)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b15a4cb-5e12-427d-146e-fd717a094d37
* Version Independent ID: e1996c22-0fa7-3ecf-d04a-fe6cbc8609db
* Content: [Create a Database Mirroring Endpoint for Windows Authentication (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/database-mirroring/create-a-database-mirroring-endpoint-for-windows-authentication-transact-sql?view=sql-server-2017)
* Content Source: [docs/database-engine/database-mirroring/create-a-database-mirroring-endpoint-for-windows-authentication-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/database-mirroring/create-a-database-mirroring-endpoint-for-windows-authentication-transact-sql.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by VanMSFT** [comment]
@NuNn-DaDdY - Thanks, Corey! We'll look into adding additional clarification in the documentation.

**Comment by VanMSFT** [comment]
Sorry for the delay. I have updated the documentation.
