### ISSUE TITLE
Version availability

### ISSUE THREAD

**Issue by ivanzinhoa** [MicrosoftDocs/sql-docs#3032]
Please, we need to know which version of SQL Server this function is available at, these date functions are not simple, I first research whether in stackoverflow.com or whatever other site and then I run a query where I just get frustrated because the solution found is not compatible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1c1cb1-feb7-d2d1-9b9f-6b3f8caff8d6
* Version Independent ID: c6caa07c-fb64-31e9-ed4f-36e367dfbaeb
* Content: [DATEPART (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/datepart-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/datepart-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/datepart-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@ivanzinhoa -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue 3032.

**Comment by MikeRayMSFT** [comment]
@ivanzinhoa - can you point me to an example of a script that doesn't work on your version, and tell me what version you're running it on?

**Comment by ivanzinhoa** [comment]
it was just an example, let's suppose I'm running SQL Server 2008 R2, I found a site|blog|whatever that advises that I can use DATEFROMPARTS, I write happily the code just to find this function is not available, now I want to see what SQL Server version this function is available at in order to determine a workaround.

**Comment by MikeRayMSFT** [comment]
@ivanzinhoa - I've created a work item (internal tracking number 1605663) to allow us to further analyze this problem. Thank you for raising the issue.
