### ISSUE TITLE
Documentation incorrect for Point

### ISSUE THREAD

**Issue by boneill81** [MicrosoftDocs/sql-docs#3034]
I noticed a fairly serious documentation issue with the Point documentation. Following the documentation's instructions would result in any points generated being far out of their intended positions.

The documentation is incorrect for Point it lists the following:

> Point ( Lat, Long, SRID )  
> 
> **Lat**
> Is a float expression representing the x-coordinate of the Point being generated.
> 
> **Long**
> Is a float expression representing the y-coordinate of the Point being generated. For more information on valid latitude and longitude values, see Point.

This should read:

Point ( **Long, Lat**, SRID )  

**Long**
Is a float expression representing the **x-coordinate** of the Point being generated. For more information on valid latitude and longitude values, see Point.

**Lat**
Is a float expression representing the **y-coordinate** of the Point being generated.

**Comment by msebolt** [comment]
@boneill81 Thank you for the feedback.

The example seems to check out.  Is this because the x and y coordinates are reversed?  

If so, there is a note later in the article that states:

```Arguments for the Point (geography Data Type) method have coordinates reversed compared to WKT.```

**Comment by msebolt** [comment]
Closing the issue now.
