### ISSUE TITLE
Approximation?

### ISSUE THREAD

**Issue by vu-dang** [MicrosoftDocs/sql-docs#3039]
There is a note on STDistance method stating that the result is an approximation.  Is the result from this function also an approximation?  and does the accuracy also fall within 0.25% of the shortest line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5b517d-c3a0-08d0-197f-dd2d6b7036db
* Version Independent ID: 964962a7-356e-b8bc-7f99-38b0a79737b4
* Content: [ShortestLineTo (geography Data Type) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geography/shortestlineto-geography-data-type?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/spatial-geography/shortestlineto-geography-data-type.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/spatial-geography/shortestlineto-geography-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by msebolt** [comment]
@vu-dang  Thank you for the question, assigning this to the author.

**Comment by MladjoA** [comment]
@vu-dang , yes, both methods share the same implementation.

**Comment by MladjoA** [comment]
@msebolt , I answered the question

**Comment by msebolt** [comment]
@vu-dang @MladjoA Closing the issue now.

**Comment by vu-dang** [comment]
Can a note be added to the online documentation so they match?
