### ISSUE TITLE
Can't find Sql Management Studio 2017 download

### ISSUE THREAD

**Issue by igor63132** [MicrosoftDocs/sql-docs#3040]
As usual MS won't allow to find anything besides the latest and greatest version 18. The problem with it is that it doesn't support Reporting project created in VS 2019 using reporting tools based on previous versions. So I have on my desktop VS solution working but on my laptop with newest software it won't load reporting project. How do I upgrade it?

**Comment by MightyPen** [comment]
@igor63132 Hello, your Issue #3040 has been recognized, and processing has begun.

@markingmyname Hi Mark, Can you please process this Issue #3040. Does our documentation provide links to install somewhat older versions of SSMS?

**Comment by markingmyname** [comment]
@igor63132 Have you looked at the Release Notes to download older versions?

https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#download-ssms-1791

**Comment by igor63132** [comment]
I just realized I have to click on a link for the particular language to get it.Not really obvious it's a link to download.For the latest version it shows as :
SSMS 18.3

Download: Download SSMS 18.3
 It's obvious, right? I expected similar for everythnig else as it used to be on product download pages before.Well, at the end my issue wasn't really with version of SSRS but rather  the way how someone gets Reporting Serviced for VS 2019 now. It's not included  in Data Services package as before but rather hidden in the extensions (in pretty "obvious" place for that matter - roaming extensions).I had a dream I still have msdn subscriptions page with all products clearly labeled and properly grouped, my old complaints how I couldn't find something there sometimes seems petty right now...
Thank you, Mark!
    On Friday, September 27, 2019, 08:47:14 AM CDT, Mark Ghanayem <notifications@github.com> wrote:  
 
 
@igor63132 Have you looked at the Release Notes to download older versions?

https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#download-ssms-1791

**Comment by markingmyname** [comment]
@igor63132,

Glad I could help.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
