### ISSUE TITLE
Maximum columns per view

### ISSUE THREAD

**Issue by keandersen** [MicrosoftDocs/sql-docs#3045]
Using Microsoft SQL Server 2016 (SP2-GDR) (KB4505220) - 13.0.5101.9 (X64)   Jun 15 2019 23:15:58   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 &lt;X64&gt; (Build 14393: ) 
I received Msg 4505, Level 16, State 1, Procedure ...snipped...
CREATE VIEW failed because column '...snipped...' in view '...snipped...' exceeds the maximum of 1024 columns.

I don't see this limit documented on this page.
I would like to create views up to the limit of a SELECT statement (4096 columns).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 780e3e16-ac52-1343-fe0a-a706c71ddb92
* Version Independent ID: 6f09b278-faa0-6f0d-1013-c1ae62ca006c
* Content: [Maximum Capacity Specifications for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server?view=sql-server-2016#feedback)
* Content Source: [docs/sql-server/maximum-capacity-specifications-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/maximum-capacity-specifications-for-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@keandersen -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue 3045.

**Comment by MikeRayMSFT** [comment]
https://github.com/MicrosoftDocs/sql-docs/issues/3045

**Comment by MikeRayMSFT** [comment]
The update to the documentation is en-route. 
To request an update to the feature (i.e. to ask to raise the maximum columns in a view), use https://aka.ms/sqlfeedback.

Thank you @keandersen for submitting this comment.
