### ISSUE TITLE
Missing information regarding private key permissions

### ISSUE THREAD

**Issue by thecosmictrickster** [MicrosoftDocs/sql-docs#3048]
I had one extra step to do that I did not see any any official documentation or in several pundit articles: if you're running SQL Server using a [non-privileged] domain account, you will need to grant read access to the certificate private key. If you don't do this, the SQL Server service will not start. I found this information at https://nickstips.wordpress.com/2010/09/08/sql-ssl-and-sql-server-2008-service-doesnt-start-error-code-2146885628/  
I was configuring SQL Server 2016 and found this resolved the issue I was having.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa20275-e415-5531-3ef4-7472d859753b
* Version Independent ID: cc1346a6-9336-91ba-bcff-9fff79847c35
* Content: [Enable Encrypted Connections to the Database Engine - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @thecosmictrickster - Thank you for the feedback. I will add clarity to the documentation, and note that the service account needs read permissions on the certificate. We appreciate your help on our documentation.

https://github.com/MicrosoftDocs/sql-docs-pr/pull/12173

#please-close
