### ISSUE TITLE
Why must an explicit value for the identity column be specified?

### ISSUE THREAD

**Issue by Elaskanator** [MicrosoftDocs/sql-docs#3059]
If I have a verbatim copy of a table and wish to do a simple INSERT ... SELECT * statement, why must I explicitly specify the identity column? I get the following error otherwise:
"An explicit value for the identity column in table '...' can only be specified when a column list is used and IDENTITY_INSERT is ON."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a803389f-08b7-7078-a104-707c612722b3
* Version Independent ID: 02f17dab-452a-7300-0bee-76b2a03e9517
* Content: [SET IDENTITY_INSERT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-identity-insert-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/set-identity-insert-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-identity-insert-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@Elaskanator Thank you for the question.

You shouldn't have to explicitly specify the identity unless `IDENTITY_INSERT` is turned ON and by default, it should be turned OFF.

If ON, it's somewhat cumbersome to specify column names as mentioned in [this post](https://stackoverflow.com/questions/2005437/an-explicit-value-for-the-identity-column-in-table-can-only-be-specified-when-a), but the work-around is to use SQL to generate the columns for you.

```
SELECT column_name + ',' 
FROM   information_schema.columns 
WHERE  table_name = 'YourTable'
```

Please comment below if this is not what you had in mind.
