### ISSUE TITLE
Include files for SQL Server version name & number are inconsistent

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#3061]
Going through the various include files for "**SQL Server versionName (versionNumber.x)**" you can see that there is no consistency to the file naming convention. For each file I show the content below the URL for the file, and then below that I note, based on the content of the file, whether the filename is referencing the version _Name_ (e.g. "2017") or the version _Number_ (e.g. "14.x").

At the very least the **sssqlv15-md.md** files needs the version number added to the content, and the **sssql15-md.md** files either needs to be removed or perhaps its content changed to be "2019 (15.x)", though in either case not before all existing references to that file are migrated over to the **sssql16-md.md** file (or perhaps create a **sssqlv13-md.md** file?).

&nbsp;

* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/sssql11-md.md
    > SQL Server 2012 (11.x)

    Version number
* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/sssql11sp1-md.md
    > SQL Server 2012 SP1 (11.0.3x)

    Version number
* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/sssql14-md.md
    > SQL Server 2014 (12.x)

    Version Name
* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/sssql15-md.md
    > SQL Server 2016 (13.x)

    Neither number nor Name
* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/sssql16-md.md
    > SQL Server 2016 (13.x)

    Version Name
* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/sssql17-md.md
    > SQL Server 2017 (14.x)

    Version Name
---
The following two files, unlike the previous set, have a "**v**" in their names:

* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/sssqlv14-md.md
    > SQL Server 2017 (14.x)

    Version number
* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/sssqlv15-md.md
    > SQL Server 2019

    Version number (but missing the number 😉 )
---
The following two files are consistent with their naming and content, but their names do not match either of the previous two conventions:

* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/ssversion2000-md.md
    > SQL Server 2000 (8.x)

    Version Name
* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/ssversion2005-md.md
    > SQL Server 2005 (9.x)

    Version Name
---
Should the following files contain the version number (i.e. `(14.x)` for their current value of "2017")?

* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/sscurrent-md.md
    > SQL Server 2017
* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/sscurrent.md
    > &lt;Token xmlns:xlink="http://www.w3.org/1999/xlink">SQL Server 2017
* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/sscurrentui-md.md
    > **Microsoft SQL Server 2017**

**Comment by msebolt** [comment]
@srutzky Thank you for the feedback.

The new versioning syntax used in Microsoft Docs (see below) allows multiple versions to be included in the same document.

![Capture](https://user-images.githubusercontent.com/6675884/65782620-e9310980-e102-11e9-81b6-88599ff10b46.PNG)

...so at some point the .md files referenced above should be condensed into a single sssql or ssversion document.  The image names could then be changed.

The Markdown syntax is as follows:

```
::: moniker range="azure-devops"
[!INCLUDE [temp](../_shared/dashboard-prerequisites-vsts.md)]  
::: moniker-end

::: moniker range=">= tfs-2017 <= tfs-2018"
[!INCLUDE [temp](../_shared/dashboard-prerequisites-tfs-2017-18.md)] 
::: moniker-end
```

...and we're definitely open to contributions.  :)

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
