### ISSUE TITLE
Some seed values gives predictable/same result of RAND

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/sql-docs#3062]
Setting the Seed with max smallint returns the same non-random result.

select RAND(32767)

consistently returns:
0.324119942249554

but, Select RAND() on it's own run several times works as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f43f1f35-c57f-379a-7117-5ba1ec7ddb7a
* Version Independent ID: a16ea319-1189-61a0-3082-dc094ca506ce
* Content: [RAND (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/rand-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/rand-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/rand-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@OzBob  Thank you for the feedback.

This is the expected behavior and is stated in the article as such.

Is this a suggestion to change the function?

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
