### ISSUE TITLE
FK Not Backwards

### ISSUE THREAD

**Issue by JediSQL** [MicrosoftDocs/sql-docs#3065]
SQL Server has a requirement for creating foreign key constraints that is not documented in this topic.
For a mulitple column foreign key, the "( ref_column [ ,...n ] )" reference column specification must list the columns in the order they were listed to create the referenced primary key on the primary key table.

The script below gets an error in the "backwards key" batch. However, the sp_help output shows that the foreign key from the "forwards key" batch gets added (SQL 2017 CU13).

--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--

use tempdb
;
GO
create table dbo.tPrimary (
  aaa int, bbb int, ccc int
, primary key clustered (aaa, bbb)
);
create table dbo.tForeign (
  bbb int, aaa int, ddd int, eee int
, primary key clustered (aaa, bbb, ddd)
);
GO
raiserror(N'Before backwards key', 10 , 1) with nowait
;
alter table dbo.tForeign add
  foreign key (bbb, aaa) references dbo.tPrimary (bbb, aaa)
;
raiserror(N'After backwards key', 10 , 1) with nowait
;
GO
raiserror(N'Before forwards key', 10 , 1) with nowait
;
alter table dbo.tForeign add
  foreign key (aaa, bbb) references dbo.tPrimary (aaa, bbb)
;
raiserror(N'After forwards key', 10 , 1) with nowait
;
GO
exec sp_help N'dbo.tForeign'
;
GO
drop table dbo.tForeign
;
drop table dbo.tPrimary
;
GO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5cd392a-eda6-eaf1-1a15-617d405d6add
* Version Independent ID: b29cc815-8e35-c1ac-cc50-5f7c8ac58778
* Content: [Create Foreign Key Relationships - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/create-foreign-key-relationships?view=sql-server-2017)
* Content Source: [docs/relational-databases/tables/create-foreign-key-relationships.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/create-foreign-key-relationships.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@JediSQL -- Dan, thank you for your feedback.

@CarlRabeler -- Carl, please look into updating the documentation.

Related issue https://github.com/MicrosoftDocs/sql-docs/issues/3066

**Comment by VanMSFT** [comment]
Hello @JediSQL! Thanks for submitting this issue. We appreciate the input. What would you recommend we add to the documentation? You can also help edit this doc yourself: <https://docs.microsoft.com/en-us/sql/sql-server/sql-server-docs-contribute>

Thanks!
