### ISSUE TITLE
Update link to enable-in-memory-oltp.sql script

### ISSUE THREAD

**Issue by genuinefafa** [MicrosoftDocs/sql-docs#3070]
In [here](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/survey-of-initial-areas-in-in-memory-oltp?view=sql-server-2017#2-elevate-to-snapshot) 
> The following sample T-SQL script enables a database for In-Memory OLTP and configures all recommended settings. It works with both SQL Server and Azure SQL Database:

link is oudated, updated is [this](https://github.com/microsoft/sql-server-samples/raw/master/samples/features/in-memory-database/in-memory-oltp/t-sql-scripts/enable-in-memory-oltp.sql)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c7055d-861f-fe71-bde6-63decf873bfe
* Version Independent ID: 4dc3b379-862b-54d3-f04f-c29e95353527
* Content: [Quick Start 1: In-Memory OLTP Technologies for Faster Transact-SQL Performance - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/survey-of-initial-areas-in-in-memory-oltp?view=sql-server-2017)
* Content Source: [docs/relational-databases/in-memory-oltp/survey-of-initial-areas-in-in-memory-oltp.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/survey-of-initial-areas-in-in-memory-oltp.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
@genuinefafa Hello Facundo, I am grateful for your report to us about this bad link, and for finding the correct link. Very cool.
Fixing with PR 12209. The fix should be live on Docs sometime on Monday Sept/30.

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/12209`

I am now Closing this Issue #3070 as fixed.
Thank you for submitting this Issue. We hope to hear from you again.
