### ISSUE TITLE
When not to use it?

### ISSUE THREAD

**Issue by alebrozzoamz** [MicrosoftDocs/sql-docs#3072]
I think there would be much value if a section of this page explained what a filtered index is NOT good for. Particularly, I was interested in whether to add WHERE IsDeleted = 0 (record not soft deleted) in my particular index, for a table where most of the values will be 0 (not soft deleted). My guess is it would not be useful but wanted to go to the source.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e578e8fc-b9da-8c8d-5a4a-64084f1204de
* Version Independent ID: 4adb8a19-ff61-5724-9f01-fb673efb7991
* Content: [Create Filtered Indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/create-filtered-indexes?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/indexes/create-filtered-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/create-filtered-indexes.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@alebrozzoamz Thank you for the feedback.

Assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
@alebrozzoamz - thank you for the suggestion. I've filed internal doc work item (1609076) and will review with PM.
