### ISSUE TITLE
Mystery column in SQL edition comparison 

### ISSUE THREAD

**Issue by modest** [MicrosoftDocs/sql-docs#3073]
"RDBMS manageability" and "Programmability" tables contain an unlabeled column with some values filled in. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93d8379a-9079-2ff1-b9c9-594116fe8367
* Version Independent ID: 1fda1b0c-fea1-ae35-c3a2-34c214bf1570
* Content: [Editions and supported features of SQL Server 2017 ~ Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-editions-and-components-2017?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-editions-and-components-2017.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-editions-and-components-2017.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@modest  Thank you for the feedback.

The documentation has been updated.
