### ISSUE TITLE
Past versions?

### ISSUE THREAD

**Issue by m-brooks** [MicrosoftDocs/sql-docs#3074]
Given that the ability to restore databases depends upon matching the correct version of SSMS to the backup file, it is important that we can still download and install past versions of SSMS. I don't see any link on this page to allow us to do that though.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-gb/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by MichaelBrooks-Version1** [comment]
OK, forget that - the link is there I just failed to spot it. Apologies.

**Comment by msebolt** [comment]
No worries, thank you for the update.
