### ISSUE TITLE
Nested Groups

### ISSUE THREAD

**Issue by blakemcneill** [MicrosoftDocs/sql-docs#3075]
Please add info on how to create nested groups. E.g. GroupA/SubGroupA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26c39cc5-33c8-c13d-0dd0-a3a8841d78de
* Version Independent ID: da1d4d25-546f-4748-6c6b-1ac9d0565783
* Content: [Server groups - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/server-groups?view=sql-server-2017#feedback)
* Content Source: [docs/azure-data-studio/server-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/server-groups.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@blakemcneill Thank you for the feedback.

Assigning this to the author for review.

**Comment by markingmyname** [comment]
@blakemcneill, 

Thanks for your comment.

Your contribution is much appreciated. 

However, our team can only answer feedback related to the documentation. Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page or visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) page. If you have any feedback related to the documentation, please feel free to log in through this channel. We truly appreciate your contribution to our articles.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
