### ISSUE TITLE
Not enough info: types of locks, Shared, Update, IntentShared, IntentExclusive, or Exclusive

### ISSUE THREAD

**Issue by samrueby** [MicrosoftDocs/sql-docs#3078]
There is not enough information on the types of locks that can be acquired or where to learn more about them and their pros and cons. Please link to the exact meaning of Shared, Update, IntentShared, IntentExclusive, or Exclusive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfc5142-4589-ac67-69c2-65d7760719e4
* Version Independent ID: 02464294-1e91-30e6-8489-51ee2ee45a31
* Content: [sp_getapplock (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-getapplock-transact-sql?redirectedfrom=MSDN&view=sql-server-2017)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-getapplock-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-getapplock-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@samrueby Thank you for the feedback, assigning this to the author.

In the meantime, please refer to the [Lock Compatibility matrix](https://docs.microsoft.com/previous-versions/sql/sql-server-2008-r2/ms186396(v=sql.105)?redirectedfrom=MSDN).

**Comment by stevestein** [comment]
@samrueby - thanks for the feedback. I updated the article to include a link to: https://docs.microsoft.com/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide#lock_modes

Thanks!

#please-close
