### ISSUE TITLE
CROSS APPLY OPENJSON examples are hard to understand and to reproduce if the content of the JSON strings is unknown

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/sql-docs#3081]
@aisbergde commented on [Sun Sep 29 2019](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/102)

On this site are some examples for the usage of CROSS APPLY.
But these examples are very hard to understand and can't be reproduced if the content of the JSON is unknown.
Please consider to add the content of the used JSON strings to enable a user to understand examples.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e25eda30-d6e4-600c-ed9d-4f0a53ee1058
* Version Independent ID: 9b53b7d7-b827-6f7f-c0c9-84645742d6a2
* Content: [OPENJSON (Transact-SQL) - SQL Server](https://docs.microsoft.com/de-de/sql/t-sql/functions/openjson-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/openjson-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/t-sql/functions/openjson-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

---

@srvbpigh commented on [Sun Sep 29 2019](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/102#issuecomment-536331100)

Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hi, please check the issue above.

Thanks!

**Comment by aisbergde** [comment]
You find good and understandable examples of the usage of CROSS APPLY OPENJSON outside the Microsoft documentation. It would be fine to get this easy to understand examples inside the Microsoft documentation.

**Comment by Phil-Factor** [comment]
--keeping the cross apply example simple
DECLARE @json NVARCHAR(MAX) = N'[  
  {  
    "OrderNumber":"SO43659",  
    "OrderDate":"2011-05-31T00:00:00",  
    "AccountNumber":"AW29825",  
    "ItemPrice":2024.9940,  
    "ItemQuantity":1  
   },  
  {  
    "OrderNumber":"SO43661",  
    "OrderDate":"2011-06-01T00:00:00", 
    "AccountNumber":"AW73565",  
    "ItemPrice":2024.9940,  
    "ItemQuantity":3  
  }
]'  
   
SELECT root.[key] AS [Order],TheValues.[key], TheValues.[value]
FROM OPENJSON ( @json )  AS root
CROSS APPLY OPENJSON ( root.value)  AS TheValues

**Comment by CarlRabeler** [comment]
Adding simple example now
