### ISSUE TITLE
Programmability table has unlabelled columns

### ISSUE THREAD

**Issue by lichasu** [MicrosoftDocs/sql-docs#3082]
@swsch commented on [Mon Sep 30 2019](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/103)

The table in the section Programmability has 1+4 = 5 headings but 6 columns in a few rows towards the bottom with contradicting values in the final columns of two of them.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 93d8379a-9079-2ff1-b9c9-594116fe8367
* Version Independent ID: 1fda1b0c-fea1-ae35-c3a2-34c214bf1570
* Content: [Editionen und unterstützte Funktionen von SQL Server 2017 – Linux - SQL Server](https://docs.microsoft.com/de-de/sql/linux/sql-server-linux-editions-and-components-2017?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-editions-and-components-2017.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/linux/sql-server-linux-editions-and-components-2017.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

---

@srvbpigh commented on [Mon Sep 30 2019](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/103#issuecomment-536687786)

Hello, @swsch
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hi team,

Please check this issue.

Thanks!

**Comment by lichasu** [comment]
Hi team,

Please check this issue.

Thanks!

**Comment by swsch** [comment]
seems to be the same as #3073 ?

**Comment by msebolt** [comment]
@swsch You're correct, please refer there for further updates.
