### ISSUE TITLE
Make "Event Notifications" a distinct group from "Service Broker"

### ISSUE THREAD

**Issue by TheConstructor** [MicrosoftDocs/sql-docs#3085]
Currently `docs/relational-databases/service-broker/index.md` redirects to `/sql/relational-databases/service-broker/event-notifications` and all the pages inside the folder add to this topic. While it does utilize service broker, it may not be the primary use-case.

I would like to propose creating a new `event-notifications` folder & group, and have a page for "Service Broker" that directs people there and probably also towards `docs/database-engine/configure-windows/sql-server-service-broker.md` (where I wonder what it has to do with windows). There used to be a tutorial how to set up a service and send and receive messages through it, but other than the examples on the statement-pages I can not find further tutorials/overviews of service broker inside the repository.

**Comment by WilliamAntonRohm** [comment]
@TheConstructor -- Matthias, thank you for your feedback.

@MashaMSFT -- Masha, please look into adding this information.

**Comment by MashaMSFT** [comment]
Hi @TheConstructor , thank  you very much for providing your feedback to our docs :) This is a good suggestion, I've created an internal work item ([1608985](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1608985)) to track it further.

I will proceed with closing out this Git Issue in the meantime, but please feel free to reach out should you need anything further.

Thanks!
Masha from the SQL Docs team
