### ISSUE TITLE
Is there a permanent link to the latest stable version of SSMS?

### ISSUE THREAD

**Issue by mdsyslab** [MicrosoftDocs/sql-docs#3086]
The SQL 2017 docs at https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?redirectedfrom=MSDN&view=sql-server-2017 point to https://go.microsoft.com/fwlink/?linkid=2104251 for the download of the latest SSMS. 

Will this link change when a newer version is SSMS is released, or is that a permanent link that will always point to the latest release?

I am asking as I would like to write some automation download and install the latest release.

**Comment by WilliamAntonRohm** [comment]
@mdsyslab -- thank you for your question.

@dnethi -- Dinakar, is this fwlink to the latest version?

cc:  @MightyPen

**Comment by dnethi** [comment]
Currently, the ID at the end is generated each time and hence, will be different.

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, Can you please take over this Issue #3086 , because it needs your SSMS expertise.
@dnethi Has provided some info in a Comment.

**Comment by dnethi** [comment]
@mdsyslab ; @WilliamAntonRohm  - you can use https://aka.ms/ssmsfullsetup to download the latest version of SSMS. Do know that we typically wait for a couple of days after a release to update this link just in case we find any high priority issues immediately post release.

**Comment by mdsyslab** [comment]
@dnethi Awesome, thank you!

Sorry, I'm not sure what the etiquette on GitHub is regarding closing issues, whether I'm ok to do it, or if I should leave it for you guys, so I'll leave it for you guys :)

**Comment by markingmyname** [comment]
@mdsyslab,

If you feel your issue is addressed, then you can close the issue yourself. :)

However, I will go ahead and do it for this one.  

Thank you for your comment.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
