### ISSUE TITLE
Supported Scenarios Server OS is incomplete

### ISSUE THREAD

**Issue by Karl-WE** [MicrosoftDocs/sql-docs#3087]
https://docs.microsoft.com/de-de/sql/database-engine/install-windows/install-sql-server-on-server-core?view=sql-server-2017#supported-scenarios OR
https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-on-server-core?view=sql-server-2017#supported-scenarios

does not match with supported Windows Core Installation matrix as listed on:
https://docs.microsoft.com/de-de/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server?view=sql-server-2017

I recommend a backlink to prevent future incompleteness or cluttering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa839a1-df21-b566-b798-bf17159c4c74
* Version Independent ID: 97d386f4-c657-eaba-a62c-404ced145cb2
* Content: [Install SQL Server 2016 on Server Core - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-on-server-core?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/install-windows/install-sql-server-on-server-core.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/install-sql-server-on-server-core.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @Karl-WE , thanks for contacting Microsoft, and bringing this to our attention! You're right it looks like there are some version mismatches here. We'll get this fixed in a bit :) 

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @Karl-we, thanks again for your feedback! My apologies, this change is taking longer than anticipated, so I've created an internal work item to track this work ([1614866](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1614866)). I will close out this Git Issue for the time being, but it will be updated once the change is made to the docs.

Thanks again for helping improve our documentation :)
Masha from the SQL Docs team

**Comment by reinaldokibel** [comment]
any updates?

**Comment by MashaMSFT** [comment]
Hi @reinaldokibel , thanks for reaching out! Yes, this issue was resolved back in October of 2019.

Thanks!
Masha from the SQL Docs team
