### ISSUE TITLE
blocking_session_id is 0, never null, contrary to documentation?

### ISSUE THREAD

**Issue by davisnw** [MicrosoftDocs/sql-docs#3090]
The documentation for sys.dm_exec_requests says:

"blocking_session_id	smallint	ID of the session that is blocking the request. If this column is NULL, the request is not blocked, or the session information of the blocking session is not available (or cannot be identified)."

However my experience shows that `blocking_session_id` is never `null`, instead it appears to be `0` for non-blocked requests. (testing under Microsoft SQL Server 2016 (SP2-CU6))

That is `select session_id, blocking_session_id, * from sys.dm_exec_request` never shows `session_id = 0` , but always shows `blocking_session_id = 0` for non-blocked requests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 785e6be1-0c51-7690-1eb6-c4c98c7c1133
* Version Independent ID: 79592f3b-ccff-06bd-eed8-08ab1bf74205
* Content: [sys.dm_exec_requests (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @pmasl
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@davisnw -- thank you for your feedback.

@pmasl -- please look into updating the documentation.

cc; @MightyPen

**Comment by MightyPen** [comment]
This attached MS Word .docx file is an email I sent to Pedro Lopes, asking him to enter a Comment to the PR12275:

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/12275`

[Email.Issue-3090.PR-12275.GeneMi.Pedro agree with fix for Issue 3090 blocking_session_id 0.msg.docx](https://github.com/MicrosoftDocs/sql-docs/files/3679697/Email.Issue-3090.PR-12275.GeneMi.Pedro.agree.with.fix.for.Issue.3090.blocking_session_id.0.msg.docx)

**Comment by pmasl** [comment]
Close this as it's been corrected.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
