### ISSUE TITLE
Example B

### ISSUE THREAD

**Issue by aneame** [MicrosoftDocs/sql-docs#3093]
Example B does not work for me.
I get the error "Invalid column name 'blocked'"
However this succeeds: "select blocking_session_id from sys.dm_exec_requests where blocking_session_id &lt;&gt; 0" 
I am using SQL Server 2016 SP2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57bb7336-951e-cab7-522e-abb98e7f7a54
* Version Independent ID: 339664c0-7de2-720a-d28d-49e38288a240
* Content: [Use the sqlcmd Utility - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/scripting/sqlcmd-use-the-utility?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/scripting/sqlcmd-use-the-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/sqlcmd-use-the-utility.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@aneame Thank you for the feedback.

The documentation has been updated.
