### ISSUE TITLE
This content has been retired - How to: Automate Package Execution 

### ISSUE THREAD

**Issue by brubakerjeff** [MicrosoftDocs/sql-docs#3094]
Hi,

I'm reading this document https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/integration-services/packages/sql-server-agent-jobs-for-packages.md with the objective of learning how to configure SSIS packages to run with SQL Server Agent on an on premise installation.

The reference I feel most relevant is the following:
Video, How to: Automate Package Execution by Using the SQL Server Agent (SQL Server Video), in the MSDN Library

However when I follow the link the message blow is displayed.
" This content has been retired and may not be updated in the future. The product, service, or technology mentioned in this content is no longer supported."

My understanding is the information is still relevant for on-premise installations and I can disregard the message? If this is the case I'm wondering if the document be improved for the next person?

thanks,
Jeff

**Comment by msebolt** [comment]
@brubakerjeff Thank you for the feedback.

This is a good question if the video is still relevant for current installations, assigning the author.

**Comment by rothja** [comment]
@brubakerjeff Yes, thank you for this question. @chugugrace Grace, can you take a look at the article and the video and see if the information is still relevant? If so, we could update the video we're linking to and/or we could provide a note in the article that the information is still relevant despite the retired content message. Please let me know if you can help out. Thank you!

**Comment by chugugrace** [comment]
@rothja from the description, the content is still relevant.

**Comment by rothja** [comment]
@chugugrace Thank you for confirming! Do you think you could add a note in this article under the video link that explains that the video is still relevant even though it is in an archived content location? Let me know if you think this would be a good improvement.

**Comment by rothja** [comment]
@brubakerjeff Thanks for the question. @chugugrace has confirmed the content is still relevant, and we will consider making this more clear in the future. Thanks, again, for your question.
