### ISSUE TITLE
Does not appear to handle Z and M values

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/sql-docs#3095]
Input:

`select geometry::STLineFromText('LINESTRING ZM (1 2 0 0,3 4 0 0)', 0)`

Result:

```sql
Msg 6522, Level 16, State 1, Line 8
A .NET Framework error occurred during execution of user-defined routine or aggregate "geometry": 
System.FormatException: 24142: Expected "(" at position 11. The input has "Z".
System.FormatException: 
   at Microsoft.SqlServer.Types.WellKnownTextReader.RecognizeToken(Char token)
   at Microsoft.SqlServer.Types.WellKnownTextReader.ParseLineStringText()
   at Microsoft.SqlServer.Types.WellKnownTextReader.ParseTaggedText(OpenGisType type)
   at Microsoft.SqlServer.Types.WellKnownTextReader.Read(OpenGisType type, Int32 srid)
   at Microsoft.SqlServer.Types.SqlGeometry.GeometryFromText(OpenGisType type, SqlChars text, Int32 srid)
```

Occurs on both SQL Azure and SQL 2016 LocalDB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb8630f-fe2c-f388-f2a7-1aca2a1a6a65
* Version Independent ID: 1d4dda34-e068-0735-d405-70a7ac88ee34
* Content: [STLineFromText (geometry Data Type) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geometry/stlinefromtext-geometry-data-type?view=sql-server-2017)
* Content Source: [docs/t-sql/spatial-geometry/stlinefromtext-geometry-data-type.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/spatial-geometry/stlinefromtext-geometry-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by msebolt** [comment]
@IanKemp  Thank you for the question.

Does this work if you remove the `ZM`?

```select geometry::STLineFromText('LINESTRING (1 2 0 0,3 4 0 0)', 0)```

**Comment by airbreather** [comment]
SQL Server seems to read WKT with Z/M/ZM data differently than the OGC WKT standard.  See NetTopologySuite/NetTopologySuite#324 for when I first discovered this.

If the WKT is coming from NetTopologySuite, then you can use`WKTWriter.ForMicrosoftSqlServer()` (as of NTS 2.0.0) to get an instance of `WKTWriter` that writes out WKT in the format that SQL Server expects.

**Comment by IanKemp** [comment]
> @IanKemp SQL Server seems to read WKT with Z/M/ZM data differently than the OGC WKT standard. See [NetTopologySuite/NetTopologySuite#324](https://github.com/NetTopologySuite/NetTopologySuite/issues/324) for when I first discovered this.
> 
> If the WKT is coming from NetTopologySuite, then you can use`WKTWriter.ForMicrosoftSqlServer()` (as of NTS 2.0.0) to get an instance of `WKTWriter` that writes out WKT in the format that SQL Server expects.

Sadly I am stuck on Core 2.2 / NTS 1.15 as our company has some pressing deadlines coming up and they don't want to risk anything by migrating to 3.0 / NTS 2.0 until after said deadlines have been met.

Since MSSQL doesn't fully implement OGC 06-103r4, a note should be added to the docs of the `geometry::ST*FromText` methods to state that certain WKT geometries aren't supported.

**Comment by msebolt** [comment]
Assigning this to the author for review.

**Comment by MladjoA** [comment]
@IanKemp , thanks for bringing up this issue. 
geometry::STLineFromText article is being updated with the remarks and examples for three-dimension and measured geometry WKT format as we speak. The rest of the related articles will be updated in the following days.

**Comment by vishnu4** [comment]
> If the WKT is coming from NetTopologySuite, then you can use`WKTWriter.ForMicrosoftSqlServer()` (as of NTS 2.0.0) to get an instance of `WKTWriter` that writes out WKT in the format that SQL Server expects.

What about if you're not using WKTWriter directly, but just using <Geometry>.AsText() ?  can we have an overload, or is there another method i can/should be using here?

**Comment by MladjoA** [comment]
@vishnu4 , are you referring to an alternative NetTopologySuite functionality, or your question is related to SQL Server Spatial. If latter, can you please elaborate your scenario?

**Comment by vishnu4** [comment]
it's the issue i'm having here : https://gis.stackexchange.com/questions/346195/cant-convert-a-wkt-with-a-z-value-into-a-sql-geometry-value
i get the same error as mentioned above, but i'm not using a WKTWriter directly.

**Comment by vishnu4** [comment]
So it looks like i was able to get around my issue by replacing any occurance i had of 
<Geometry>.AsText()
to 
<Geometry>.ToWKT()

where 'ToWKT' is just an extension method i made below.  keeping my sql/not sql options open with the second parameter too.:
```
public static string ToWKT(this NetTopologySuite.Geometries.Geometry geom, bool forSQL = true)
        {
            if (geom != null && geom.IsValid)
            {
                WKTWriter w;
                if (forSQL)
                {
                    w = WKTWriter.ForMicrosoftSqlServer();
                }
                else
                {
                    w = new WKTWriter();
                }
                return w.Write(geom);
            }
            return string.Empty;
        }
```

**Comment by cawrites** [comment]
@IanKemp thank you for contacting Microsoft. It appears your original question has been answered. Please don't hesitate to contact Microsoft again with your content-related questions.

**Comment by cawrites** [comment]
#please-close
