### ISSUE TITLE
select statement should be in parenthesis 

### ISSUE THREAD

**Issue by devale** [MicrosoftDocs/sql-docs#3097]
the select statements in the examples dont have parentheses. 

documentation says: " If the Boolean expression contains a SELECT statement, **the SELECT statement must be enclosed in parentheses.**"

example says:
IF DATENAME(weekday, GETDATE()) IN (N'Saturday', N'Sunday')
       **SELECT 'Weekend';**
ELSE 
       **SELECT 'Weekday';**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5c4b818-4333-c6f1-3a13-bdcd32afccbb
* Version Independent ID: eb3f02b0-214d-eff7-cc6e-f2bee0607ae5
* Content: [IF...ELSE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/if-else-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/language-elements/if-else-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/if-else-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@devale  Thank you for the feedback.

The term Boolean expression refers only to `SELECT` statements used in the logic.

However, since the examples are misleading, I've updated the documentation accordingly.
