### ISSUE TITLE
This page should not list any download link for this program. 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/sql-docs#3098]
It has been so broken since 17.x that every little thing (dragging from object explorer to the editor, changing the active db, simply typing, etc) causes it to go Not Responding for long periods of time, sometimes never coming back and losing the work in progress. 

It does this like 2-5 times a day during light use. How has this hot mess been allowed to pass any kind of QA testing? Versions before 17.x didnt have this problem. I'd use them more often but the start menu wont remember that I choose them more often and always serves me a 17 or 18.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#info_tip-get-help-for-sql-tools)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by msebolt** [comment]
@StingyJack  Thank you for the feedback, we're sorry your experiencing issues.

This issue in particular (referenced [here](https://feedback.azure.com/forums/908035-sql-server/suggestions/37887988-ssms-crash-when-dragging-table-from-object-explore)) has been addressed and will be released in the next update.

Please refer to the [SQL Server forums](https://feedback.azure.com/forums/908035-sql-server) for product-related issues.

**Comment by StingyJack** [comment]
@msebolt - yeah, yeah, I know its a product issue. (but think of how many of your users you can help by altering the doc in the way that I mentioned =P )

**Comment by StingyJack** [comment]
@msebolt - i think part of the problem with this is that there is a Check for Updates menu option that lies like a rug
