### ISSUE TITLE
64-Bit Machines

### ISSUE THREAD

**Issue by brentcarlson** [MicrosoftDocs/sql-docs#3100]
When following these steps on a 64-bit machine, you must run mmc.exe /32 in order for the SQL Configuration Manager extension to show up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f80bfb4b-10e3-5341-5010-f9020acb91a6
* Version Independent ID: 8caf8830-7425-512f-b32a-6f6bca44310c
* Content: [Connect to Another Computer (SQL Server Configuration Manager) - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/scm-services-connect-to-another-computer?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/configure-windows/scm-services-connect-to-another-computer.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/scm-services-connect-to-another-computer.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@brentcarlson Thank you for the feedback.

This has been assigned to the author for review.

**Comment by MikeRayMSFT** [comment]
Thank you for the feedback. Confirming with engineering.

**Comment by CarlRabeler** [comment]
PR pending
