### ISSUE TITLE
SSMS 18.x ? No thanks

### ISSUE THREAD

**Issue by gaelj** [MicrosoftDocs/sql-docs#3101]
DB diagrams were removed without valid reason or notice from 18.0.
They put it back in 18.1 after user backlash.
But in 18.1 editing a schema will randomly break it, especially when other people are still using 17.x. You end up re-creating your whole schema from scratch, only to find it broken again 2 days later.
My schemas are too precious to take that risk again.
I'm sticking with 17.9.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by msebolt** [comment]
@gaelj  Thank you for the feedback, we're sorry you're experiencing issues.

Unfortunately, this is a topic that can only be addressed by the product team.

Please move the issue to the [SQL Server forums](https://feedback.azure.com/forums/908035-sql-server).

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are any questions.
