### ISSUE TITLE
procedure in the document

### ISSUE THREAD

**Issue by emad-almousa** [MicrosoftDocs/sql-docs#3102]
I think there is a mistake in this guide, here we are tackling stored procedure where the code is "dynamic SQL". the procedure in this guide is not using dynamic SQL !?

Regards,
Emad Al-Mousa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca807e0-3f89-1a14-86af-d2d1b463ab1d
* Version Independent ID: 9e9ba593-b9e6-6cb4-e68a-b08558fe3504
* Content: [Tutorial: Signing Stored Procedures with a Certificate - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-signing-stored-procedures-with-a-certificate?redirectedfrom=MSDN&view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/tutorial-signing-stored-procedures-with-a-certificate.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tutorial-signing-stored-procedures-with-a-certificate.md)
* Product: **sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@emad-almousa Thank you for the feedback.

Apologies in that I see no reference to **dynamic sql** used in the article.

Is this referenced as dynamic from another article?

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are any questions.
