### ISSUE TITLE
Debug on Azure SQL Database?

### ISSUE THREAD

**Issue by jeroenhabets** [MicrosoftDocs/sql-docs#3103]
If I switch to Azure SQL Database the "How to: Debug Stored Procedures" still explains how to debug. Not a single warning about this not supported on Azure.

docs/ssdt/how-to-debug-stored-procedures.md

**Comment by markingmyname** [comment]
@jeroenhabets

Thank you for your feedback! We will investigate and get back to you with the relevant info.

However, please add your experience in [UserVoice](https://feedback.azure.com/forums/908035-sql-server) to find if you see more people experience the same situation.

**Comment by markingmyname** [comment]
This is for On-prem only.

However, our team can only answer feedback related to the documentation. Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page or visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) page. If you have any feedback related to the documentation, please feel free to log in through this channel. We truly appreciate your contribution to our articles.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
