### ISSUE TITLE
Is there any way to add a column AFTER or BEFORE an existing column? ...

### ISSUE THREAD

**Issue by bdcoder2** [MicrosoftDocs/sql-docs#3104]
Hello,

Is there any way to ADD a column to a table and specify its position?  Something like:

`ALTER TABLE my_table ADD new_column VARCHAR(10) NULL AFTER existing_column_name;`

Would be nice, rather than having to create a new table with the columns, copy data from existing table, and then drop the old table and rename the new table.

If not, the docs should be updated to at least indicate that new columns will be added to the END of the row (I am assuming).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abcca5d2-d433-96cc-930e-4de020c5785d
* Version Independent ID: fde147ff-b157-502c-276a-d3a2bf9bb3c7
* Content: [ALTER TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-2016#Example_Top)
* Content Source: [docs/t-sql/statements/alter-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@bdcoder2 Thanks for your question. The new column is added at the end of this existing set of columns. I am updating the docs to make this clear. 
Carl
