### ISSUE TITLE
Examples: Azure SQL Data Warehouse and Parallel Data Warehouse -> seems like it's in the wrong place

### ISSUE THREAD

**Issue by isaac-dasan** [MicrosoftDocs/sql-docs#3105]
The heading -&gt; Examples: Azure SQL Data Warehouse and Parallel Data Warehouse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ef56d2d-d84f-9c9d-7c59-d53f9bb3e32e
* Version Independent ID: 7291bb23-ac58-4e43-8a46-27e0a86926db
* Content: [PERCENTILE_CONT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/percentile-cont-transact-sql?redirectedfrom=MSDN&view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/percentile-cont-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/percentile-cont-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@isaac-dasan -- Isaac, thank you for your feedback.  I'll update this article.
