### ISSUE TITLE
Broken link to Linux download

### ISSUE THREAD

**Issue by dllmr** [MicrosoftDocs/sql-docs#3108]
The link to the .tar.gz download for Azure Data Studio 1.12.0 currently gives the .deb file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017#feedback)
* Content Source: [docs/azure-data-studio/download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@dllmr -- Mike, thank you for your feedback.  I'm looking into this link.

**Comment by LarnuUK** [comment]
The `.deb` link also takes you to then 1.11 `.deb` file. Looks like a "simple" case of wrong links updated. Also note that the `.tar.gz` has also been incorrect updated (again) to now take you to the 1.12.1 `.deb` file.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
