### ISSUE TITLE
OLE DB or ODBC connection string allow curly braces

### ISSUE THREAD

**Issue by mloskot** [MicrosoftDocs/sql-docs#3110]
Currently, on this page https://docs.microsoft.com/en-us/sql/relational-databases/security/strong-passwords, there is this note:

![image](https://user-images.githubusercontent.com/80741/66129891-12fd9b00-e5f1-11e9-94ab-d5c5ef6e17f9.png)

I have successfully connected to`Microsoft SQL Server 2017 (14.0.2027.2)` using the password `AbC23=$dEfG'+}`, where the last `}` character is part of the password as displayed, and drivers as presented in the following connection strings:

- `Provider=SQLOLEDB;Password=AbC23=$dEfG'+};...` and whole connection string passed to `Open` of `ADODB::Connection`
- `Driver={ODBC Driver 17 for SQL Server};PWD=AbC23=$dEfG'+};...` and whole connection string passed to ODBC API call `SQLDriverConnect`.

Of course, the password also works fine with the SQL Server Management Studio.

----

Either the page linked above is outdated or incorrect.

**Comment by WilliamAntonRohm** [comment]
@mloskot -- Mateusz, thank you for your feedback.

@VanMSFT -- Van, please look into this issue 3110.

**Comment by VanMSFT** [comment]
Hello @mloskot! I apologize for the delay. I am looking into this issue and will update the article appropriately.

**Comment by VanMSFT** [comment]
Hi @mloskot! Thanks again for bringing up this issue. I've confirmed that the limitation was removed for brackets {}. I'm updating the document now.

**Comment by mloskot** [comment]
@VanMSFT Thanks!

**Comment by jftrianda** [comment]
Hi @VanMSFT
the connection concern still exists with the opening curly brace { in the password in ODBC connection string 
`PWD=AbC23=$dEfG'+{;DRIVER={SQL Server Native Client 11.0};  `

**Comment by camron-wellsky** [comment]
try wrapping your PWD parameter with {}

so like: 
`PWD={AbC23=$dEfG'+{};`

**Comment by mloskot** [comment]
@camron-wellsky unrelated, sorry
