### ISSUE TITLE
Slow download

### ISSUE THREAD

**Issue by DmitryVakhrushev** [MicrosoftDocs/sql-docs#3111]
Could you provide an alternative download link? I am trying for several days and it shows me 5 hours as an approximate download time. To compare, I just downloaded another piece of software (200Mb) and it took about 3 minutes. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by WilliamAntonRohm** [comment]
@DmitryVakhrushev -- Dmitry, I am unable to replicate your issue, as my estimated download time is 9 minutes.  There are many factors at work and from here I cannot determine where the slowdown is occurring.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
