### ISSUE TITLE
Example doesn't work for schema_option > than an int

### ISSUE THREAD

**Issue by breenb** [MicrosoftDocs/sql-docs#3113]
The schema_option cannot be cast to an int correctly if the number is &gt; that what an int can hold. Casting it to a bigint produces the correct number, but passing a number that large to the value in the SP doesn't convert it correctly to a varbinary(8) for the article being updated. The SP appears to take varbinary(8) values fine, so not sure why the example doesn't just do it that way. I am working with schema_option = '0x00000004080352DD'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0bc5357-fd5e-6029-dd19-ef73101d2cfa
* Version Independent ID: d78f8e70-7f11-cd19-6ba1-fdbfec5a9e6a
* Content: [sp_changearticle (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-changearticle-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-changearticle-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-changearticle-transact-sql.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@breenb -- thank you for your feedback.

@stevestein -- please look into this issue 3113.

**Comment by stevestein** [comment]
@breenb - thanks for the feedback.  An internal work item (1620390) has been created to consider updating the example per your suggestion.

Thanks!


#please-close
