### ISSUE TITLE
EncryptByPassphrase

### ISSUE THREAD

**Issue by jbolduc81** [MicrosoftDocs/sql-docs#3115]
The fact that Sql Server 2017 now uses SHA2 algorithm instead of SHA1 in the process of encrypting data by passphrase should in my opinion be listed in the breaking changes as it has broken our application which exchanges encrypted data between different sql server versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13216eb2-c154-aa4c-7a35-09a8295121aa
* Version Independent ID: 8c0412c8-7f6d-87d4-454e-ddbbcc11367b
* Content: [Breaking Changes to Database Engine Features in SQL Server 2017 - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/breaking-changes-to-database-engine-features-in-sql-server-2017?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/breaking-changes-to-database-engine-features-in-sql-server-2017.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/breaking-changes-to-database-engine-features-in-sql-server-2017.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@jbolduc81 -- thank you for your feedback.

@MikeRayMSFT -- please look into updating this article.

**Comment by MikeRayMSFT** [comment]
@jbolduc81 - thanks for this submission. I'm working with my engineering team to bring the right answer to you.

**Comment by jaszymas** [comment]
@jbolduc81 - we have confirmed this is a breaking change and we will work on updating the documentation to make that clear. Thanks for your input.
