### ISSUE TITLE
Cannot download SSMS 18.3

### ISSUE THREAD

**Issue by JeffSkyrunner** [MicrosoftDocs/sql-docs#3122]
The link https://go.microsoft.com/fwlink/?linkid=2104251 from page https://docs.microsoft.com/it-it/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017 doesn't allow to open the correct page, so I cannot download the update

**Comment by imba-tjd** [comment]
This has been fixed in https://github.com/MicrosoftDocs/sql-docs/commit/816648720165343d7f830b0a8c428bbb743945b2. The localized page will be synced in a few days. You can use those links in the en-us page before that.

**Comment by msebolt** [comment]
@JeffSkyrunner Thank you for the feedback.

Closing the issue now, please comment below if there issues with the fix.
