### ISSUE TITLE
CREATE DATABASE ON <url>

### ISSUE THREAD

**Issue by banzaisi** [MicrosoftDocs/sql-docs#3128]
The following page describes the concept of storing database files in Azure using blob storage: https://docs.microsoft.com/en-gb/sql/relational-databases/databases/sql-server-data-files-in-microsoft-azure

However, the syntax of CREATE DATABASE does not apparently allow for specifying a URL.
Can this page be updated with the valid syntax and an example, and also a reference to the concept page mentioned above?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e8abfde-2523-5c70-bb95-b10101a726ff
* Version Independent ID: 3b8152d2-b49e-df4b-0f05-3ec52aa5bb71
* Content: [CREATE DATABASE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-gb/sql/t-sql/statements/create-database-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/create-database-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-database-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@banzaisi  Thank you for the feedback.

Assigning this to the author for review.

**Comment by rothja** [comment]
@banzaisi Thank you for your question. @CarlRabeler is currently out of the office. @MashaMSFT can you please take a look at this suggestion. 

@banzaisi Can I ask a few questions? So you're saying that the article shows using CREATE DATABASE with a URL to blob storage, but when you do this it does not work? Do you have an error you could share? So you're asking us to verify that the article works and/or change the article to show the correct syntax for creating a database in Azure blob storage. Is this correct? Thank you!

**Comment by MashaMSFT** [comment]
Hi @banzaisi , thank you for contacting Microsoft! Sorry, would you mind clarifying your question? The [doc ](https://docs.microsoft.com/en-gb/sql/relational-databases/databases/sql-server-data-files-in-microsoft-azure?view=sql-server-2017) you mention has this code sample:

```sql
CREATE CREDENTIAL [https://testdb.blob.core.windows.net/data]  
WITH IDENTITY='SHARED ACCESS SIGNATURE',  
SECRET = '<your SAS key>'  
  
CREATE DATABASE testdb   
ON  
( NAME = testdb_dat,  
    FILENAME = 'https://testdb.blob.core.windows.net/data/TestData.mdf' )  
 LOG ON  
( NAME = testdb_log,  
    FILENAME =  'https://testdb.blob.core.windows.net/data/TestLog.ldf')
```

Is that different than what you were looking for?

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
@banzaisi , oh, I just reread your question :) Are you asking to have the above example added to the [CREATE DATABASE](https://docs.microsoft.com/en-gb/sql/t-sql/statements/create-database-transact-sql?view=sql-server-2017) article? 

Thanks!
Masha from the SQL Docs team

**Comment by banzaisi** [comment]
@MashaMSFT , yes, exactly. Does the main syntax for CREATE DATABASE also need clarifying to say that Azure blob URLs are also allowed, per below?
Are all the other options like SIZE, MAXSIZE and FILEGROWTH also supported for Azure blobs?

<filespec> ::=
{
(
    NAME = logical_file_name ,
    FILENAME = { 'os_file_name' | 'filestream_path' | 'azure_blob_url' }
    [ , SIZE = size [ KB | MB | GB | TB ] ]
    [ , MAXSIZE = { max_size [ KB | MB | GB | TB ] | UNLIMITED } ]
    [ , FILEGROWTH = growth_increment [ KB | MB | GB | TB | % ] ]
)
}

**Comment by MashaMSFT** [comment]
Hi @banzaisi , thanks for the confirmation! Let me verify that the other options are supported, and then I'll update the doc :) Thanks again for helping improve our documentation!

Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @banzaisi , thanks again for providing feedback to our documentation! I have created an internal work item to track this work ([1622218](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1622218)). I will close out this Git Issue for the time being, but please feel free to respond should you need anything further in the meantime.

Thanks!
Masha from the SQL Docs team
