### ISSUE TITLE
Blob lease

### ISSUE THREAD

**Issue by banzaisi** [MicrosoftDocs/sql-docs#3129]
The section on troubleshooting says for Lease blob errors, you can explicitly "break" the lease on a blob to free it up for another client (another SQL Server instance) to attach to the blob.
However, the correct terminology is to "release" the blob lease.
"Breaking" a lease does NOT release it for use by another client:
https://docs.microsoft.com/en-us/rest/api/storageservices/lease-blob

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb6076ae-3679-3a8e-6530-5f0db78b3f06
* Version Independent ID: 335044f8-f561-6f8d-b878-f3fde1664e19
* Content: [SQL Server data files in Microsoft Azure - SQL Server](https://docs.microsoft.com/en-gb/sql/relational-databases/databases/sql-server-data-files-in-microsoft-azure?view=sql-server-2016)
* Content Source: [docs/relational-databases/databases/sql-server-data-files-in-microsoft-azure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/sql-server-data-files-in-microsoft-azure.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@banzaisi Thank you for the feedback.

Assigning this to the author for review.
