### ISSUE TITLE
Alias on table prevents SYSTEM_TIME from working - is this intentional?

### ISSUE THREAD

**Issue by Dean-McMillan** [MicrosoftDocs/sql-docs#3137]
Example:

	select 
		e.Column1
		,e.Column2
	from 
		dbo.tbl_Example e
	for SYSTEM_TIME between '2001-01-01' and '2020-01-01'

-&gt; causes the error "Incorrect syntax near 'for'."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 751e374d-cd64-1de5-c1d2-5c426c9534c9
* Version Independent ID: 2c62a70f-cd2e-bf40-5974-dde1b5a10efe
* Content: [Querying Data in a System-Versioned Temporal Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/querying-data-in-a-system-versioned-temporal-table?view=sql-server-2017)
* Content Source: [docs/relational-databases/tables/querying-data-in-a-system-versioned-temporal-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/querying-data-in-a-system-versioned-temporal-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@Dean-McMillan Thank you for the feedback.

The example is incorrect, refer to [this post](https://stackoverflow.com/questions/44337046/why-does-the-for-clause-not-work-with-an-alias-in-sql-server-2016-with-temporal) and either remove or restructure the alias.

Assigning this to the author for review.

**Comment by Dean-McMillan** [comment]
Many thanks.

**Comment by Dean-McMillan** [comment]
Closing issue as there are alias examples present.
