### ISSUE TITLE
Text wrong or code missing

### ISSUE THREAD

**Issue by K232** [MicrosoftDocs/sql-docs#3143]
I'm not sure whether the text is wrong or the example code is missing. Step 3 in [To recompile a stored procedure by using the WITH RECOMPILE option](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/recompile-a-stored-procedure?view=sql-server-2017#to-recompile-a-stored-procedure-by-using-the-with-recompile-option-1) says that the first example creates a stored procedure but there is no such code.
![Recompile a Stored Procedure](https://user-images.githubusercontent.com/685016/66297870-d089d600-e8f0-11e9-941a-d1c7338424c3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19bbbbc-0e34-a78c-3f14-dfbc0fbf536c
* Version Independent ID: 8f236ed6-fc5a-8a6e-9b16-6a925bba0b70
* Content: [Recompile a Stored Procedure - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/recompile-a-stored-procedure?view=sql-server-2017)
* Content Source: [docs/relational-databases/stored-procedures/recompile-a-stored-procedure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/stored-procedures/recompile-a-stored-procedure.md)
* Product: **sql**
* Technology: **stored-procedures**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@K232  Thank you for the feedback, assigning this to the author for review.

@stevestein Please note this issue occurs twice in the article in both the **To recompile a stored procedure by using the WITH RECOMPILE option** and **To recompile a stored procedure by using sp_recompile** sections.

**Comment by stevestein** [comment]
@K232 - thanks for pointing this out. I updated the steps in the article to use the stored procedure created in the first code block.  Thanks!

#please-close
