### ISSUE TITLE
Text wrong or code missing

### ISSUE THREAD

**Issue by K232** [MicrosoftDocs/sql-docs#3144]
I've just seen that [To recompile a stored procedure by using sp_recompile](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/recompile-a-stored-procedure?view=sql-server-2017#to-recompile-a-stored-procedure-by-using-sp_recompile) has the same wrong text / missing code problem as already reported in #3143 for another chapter: Step 3 contains info about a stored procedure but the mentioned code is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19bbbbc-0e34-a78c-3f14-dfbc0fbf536c
* Version Independent ID: 8f236ed6-fc5a-8a6e-9b16-6a925bba0b70
* Content: [Recompile a Stored Procedure - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/recompile-a-stored-procedure?view=sql-server-2017)
* Content Source: [docs/relational-databases/stored-procedures/recompile-a-stored-procedure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/stored-procedures/recompile-a-stored-procedure.md)
* Product: **sql**
* Technology: **stored-procedures**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@K232  Thank you for the feedback.

Since this issue is now included in https://github.com/MicrosoftDocs/sql-docs/issues/3143 I'm closing this as a duplicate.
