### ISSUE TITLE
Dac supported objects list

### ISSUE THREAD

**Issue by mco100** [MicrosoftDocs/sql-docs#3147]
Hi,
Include Sequences in the list of objects supported by DAC 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f0297c-1e1f-fe6e-4b0f-9fd5d2cebfd8
* Version Independent ID: 55771482-ffea-379b-8f32-11ddd69bb301
* Content: [DAC Support For SQL Server Objects and Versions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/dac-support-for-sql-server-objects-and-versions?view=sql-server-2017)
* Content Source: [docs/relational-databases/data-tier-applications/dac-support-for-sql-server-objects-and-versions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/dac-support-for-sql-server-objects-and-versions.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@mco100  Thank you for the feedback, assigning the author for review.

**Comment by stevestein** [comment]
@mco100 - thanks for the feedback. The DAC content is undergoing a larger review and assessment. An internal work item (1620374) has been created with your request. 

Thanks!

#please-close
