### ISSUE TITLE
HYPERVISOR

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#3151]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/sql-docs.ru-ru/issues/61
The comments refer to the original documentation

@MichaelFirsov commented 8 hours ago — with docs.microsoft.com
Hello!
"HYPERVISOR = SQL Server is running inside a hypervisor, which implies a hardware-assisted virtualization. When the Hyper_V role is installed, the hypervisor hosts the OS, so an instance running on the host OS is running in the hypervisor." - my SQL Server 2019 that's running inside a virtual machine on a Hyper-V host displays "HYPERVISOR" while the description above states the "HYPERVISOR" should be displayed only for SQL Server instances installed on the Hyper-V hosts themselves (not inside virtual machines!)...- is that correct?
By the way, it's not clear which value must be displayed here for the virtual_machine_type/virtual_machine_type_desc field in case SQL Server is running inside the general Hyper-V based virtual machines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1073200-d5d6-a64e-d8d8-a4809873822b
* Version Independent ID: aab7789b-e333-2d9a-bfb9-52106184c156
* Content: [sys.dm_os_sys_info (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@MichaelFirsov  Thank you for the questions, we're sorry you're experiencing issues.

Unfortunately issues here are used for changes to the documentation, for product questions please consider moving the issue to either:

- [SQL Server forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqldocumentation%2Csqldatabaseengine)
- [SQL Server on StackOverflow](https://stackoverflow.com/questions/tagged/sql-server)

After the issue has been resolved we can always update the documents accordingly.

**Comment by MichaelFirsov** [comment]
"Unfortunately issues here are used for changes to the documentation, for product questions please consider moving the issue to either:" - please excuse me but I didn't understand it: my question does pertain to "changes to the documentation" - I didn't say SQL Server works incorrectly, it's definitely just a documentation issue!

**Comment by msebolt** [comment]
I see the misunderstanding, assigning to the author now.

**Comment by stevestein** [comment]
@MichaelFirsov - thanks for the feedback. The description was definitely a bit unclear so I updated it with the following text: 

Describes the virtual_machine_type column. Not nullable.

NONE = SQL Server is not running inside a virtual machine.

HYPERVISOR = SQL Server is running inside a virtual machine hosted by an OS running hypervisor (a host OS that employs hardware-assisted virtualization).

OTHER = SQL Server is running inside a virtual machine hosted by an OS that does not employ hardware assistant such as Microsoft Virtual PC.

Hopefully this is more helpful.

**Comment by stevestein** [comment]
#please-close

**Comment by MichaelFirsov** [comment]
Thank you very much for the clarification, stevestein - that's much better!
