### ISSUE TITLE
The download icon looks strange under the dark theme

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/sql-docs#3152]
@Hawkeyes0 commented on Tue Oct 08 2019

看起来好像抠图失败的样子，而且图标的颜色与暗色的背景太相似了，以至于我专门切换到亮色主题才知道那是个下载图标😂

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [下载 SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/zh-cn/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

---

@srvbpigh commented on Tue Oct 08 2019

Hello, @Hawkeyes0
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hi team, please check this issue. The download icon is not displaying properly in the dark theme.

Thanks!

**Comment by markingmyname** [comment]
I do not understand the issue.

It looks fine to me...

![image](https://user-images.githubusercontent.com/22989000/76353412-b0ff3b00-62de-11ea-9f69-008a3009073f.png)

**Comment by markingmyname** [comment]
The issue was handled months ago.

I will resume in closing this issue.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
