### ISSUE TITLE
Missing a small step

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#3153]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/sql-docs.zh-tw/issues/113
The user is making a suggestion to add a step to the documentation
*The comment below was machine translation*

@lovepm860524 commented 19 days ago — with docs.microsoft.com

"Judge the Database Engine to execute the name of the individual" block,
4. ...right-click [Local Server Group], point to [Work], and then click [Register Local Server]. All Database Engine executions installed on your computer are displayed. ...
The middle of the line should be added to the "Expanding the local server group".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c35290b-b676-c52d-4204-ada11a3bb2af
* Version Independent ID: 87264101-997a-d17a-c96a-7a2cf15689e1
* Content: [Lesson 1: Connecting to the Database Engine - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/lesson-1-connecting-to-the-database-engine?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/lesson-1-connecting-to-the-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/lesson-1-connecting-to-the-database-engine.md)
* Product: **sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @lovepm860524, thank you so much for your feedback! I modified the text a bit to highlight expanding the security group as suggested. Thank  you so much for making our docs better! This change will be live later today. 

Is there anything else we can assist you with? If not, we will proceed with closing out this Git Issue in a few business days.

Thanks!
Masha from the SQL Docs team
