### ISSUE TITLE
Cannot check/remove index fragmentation using SSMS for Azure SQL Database

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/sql-docs#3158]
Looks like checking/removing index fragmentation using SSMS is not available for Azure SQL Database since Properties/Reorganize context menu command is not available, but I cannot find any information about the restriction. Would you please add information if we don't have it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40c68674-b35e-416e-33d5-da18290e1640
* Version Independent ID: 7310124c-a4ff-a221-0ece-82bab37d6f62
* Content: [Reorganize and Rebuild Indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/reorganize-and-rebuild-indexes?view=sql-server-2017)
* Content Source: [docs/relational-databases/indexes/reorganize-and-rebuild-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/reorganize-and-rebuild-indexes.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @pmasl
* Microsoft Alias: **mikeray**

**Comment by rothja** [comment]
@kazshi Thank you for your question and sorry for any delay. @MikeRayMSFT can you take a look at this and maybe work with @stevestein to see if this is a limitation for Azure SQL Database? Thank you!

**Comment by CarlRabeler** [comment]
PR pending to address this - not supported with SSMS in Azure SQL Database - TSQL script works fine
