### ISSUE TITLE
If the query can be parallelized, rows are distributed according to the MAXDOP setting

### ISSUE THREAD

**Issue by gintarasg** [MicrosoftDocs/sql-docs#3159]
Could you please clarify which MAXDOP you're referring to? Is it the server level, database level, or (input) query level MAXDOP?
This article implies that the MAXDOP of the input query is used: https://nielsberglund.com/2018/03/21/microsoft-sql-server-r-services---sp_execute_external_script---iii/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa45eb4-2d8b-71ba-c7a6-e830199dca20
* Version Independent ID: 938a7bb2-b7c3-d5f2-ec1a-a6a8ff8a7f5a
* Content: [sp_execute_external_script (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-execute-external-script-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-execute-external-script-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-execute-external-script-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@gintarasg -- thank you for your feedback.

@stevestein -- please look into this issue 3159.

**Comment by garyericson** [comment]
I'm looking into it.

**Comment by garyericson** [comment]
The answer from the engineering team is that it is all the settings: server level, resource group, or query hint. You can find a detailed discussion here: 
https://techcommunity.microsoft.com/t5/SQL-Server-Support/Server-8217-s-8220-Max-Degree-of-Parallelism-8221-setting/ba-p/318569

#please-close
