### ISSUE TITLE
Analyze an Actual Execution Plan - Missing option in context menu

### ISSUE THREAD

**Issue by JohnKNess** [MicrosoftDocs/sql-docs#3165]
Even though I have filtered on SQL Server 2016 and accessed the page "Analyze an Actual Execution Plan" via https://docs.microsoft.com/en-us/sql/relational-databases/performance/analyze-an-actual-execution-plan?view=sql-server-2016 this option is not available to me on a SQL Server 2016 Service Pack 2 instance running SSMS 16.5. Is this feature only available in SQL Server 2017 and/or SSMS 17.x?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e7b8b29-f3e3-0f7e-04b1-ae53738085d5
* Version Independent ID: 780e2aec-7997-a92f-2f30-ff88e7f75972
* Content: [Analyze an Actual Execution Plan - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/analyze-an-actual-execution-plan?view=sql-server-2016#feedback)
* Content Source: [docs/relational-databases/performance/analyze-an-actual-execution-plan.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/analyze-an-actual-execution-plan.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by pmasl** [comment]
You need at least SSMS v17.4. SSMS release cycle has been decouple from SQL Server for a few years. You should always plan to use the latest version, which can connect to previous engine versions as well.

**Comment by WilliamAntonRohm** [comment]
@pmasl -- Pedro, thank you for that information.

@JohnKNess -- John, I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by JohnKNess** [comment]
@WilliamAntonRohm Thank your for the follow up. It just isn't apparent from the page itself, that version SSMS 17.4 is required in order to use this feature. I am aware that SSMS has been decoupled from SQL Server development and after looking through the release notes of older SSMS versions I couldn't find a reference to "Analyze an Actual Execution Plan", that's why I raised an issue. Any chance one could add a generic "Please ensure you are using the current release of SSMS in order to use this feature" to the page (and possible others)?

**Comment by WilliamAntonRohm** [comment]
@JohnKNess -- you're welcome, John.

@pmasl -- please look into adding this note.

cc @MightyPen

**Comment by MightyPen** [comment]
To the introduction at top of the article, new PR 12421 is adding text to recommend that customers install the latest SSMS, and it gives the necessary link. This text is added immediately after the existing text that says SSMS version 17.4 or later is needed.

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/12421`

Thank you.
 . .

**Comment by MightyPen** [comment]
Closing this Issue #3165.
