### ISSUE TITLE
"Custom" option for capture mode is missing 

### ISSUE THREAD

**Issue by mco100** [MicrosoftDocs/sql-docs#3167]
SQL Server version : Microsoft SQL Server 2019 (CTP3.2) - 15.0.1800.32 (X64)   Jul 17 2019 21:29:33   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Linux (CentOS Linux 7 (Core)) &lt;X64&gt;
Issue : "Custom" option for capture mode is missing in SSMS drop down list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b587ab-50b8-eada-aa86-ba0c838c57ee
* Version Independent ID: f1fd2d52-b66f-4fbc-c54a-c688c4fd0f21
* Content: [Monitoring Performance By Using the Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-2017#Enabling)
* Content Source: [docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by msebolt** [comment]
@mco100  Thank you for the feedback, assigning this to the author for review.

If this involves a local configuration issues you will need to create a support ticket in the [SQL Server forum](https://feedback.azure.com/forums/908035-sql-server).

**Comment by julieMSFT** [comment]
@mco100 Thank you for your feedback. What version on SSMS are you using? Support for the new option in the Query Store UI should be visible in SSMS 18.4.

The "Custom" option is supported through the [ALTER DATABASE syntax](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options?view=sql-server-ver15#syntax). Also see
[SQL Server 2019 CTP3.0 Query Store Changes](https://milossql.wordpress.com/2019/05/29/sql-server-2019-ctp3-0-query-store-changes/)

Please let me know if you have further questions.

**Comment by julieMSFT** [comment]
@mco100  Thank you for your feedback. I will proceed with closing this issue. If you have further questions the @ notification will continue to work even after an item is closed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
