### ISSUE TITLE
Setup Blocked 

### ISSUE THREAD

**Issue by datcodeboy** [MicrosoftDocs/sql-docs#3168]
i download the SSMS 18.3.1 release from the officail link i got from google but i keep getting this error
```This version of windows 10 or windiows server 2016 is not supported. Please upgrade to version 1607 or greater.```
need direction on what to do

**Comment by WilliamAntonRohm** [comment]
@datcodeboy -- it seems you need to update your operating system to a newer version.  You may also find an answer here:
- [Setup and Upgrade - MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsetupandupgrade&filter=alltypes&sort=lastpostdesc)
- [Reddit - general discussion about SQL Server](https://www.reddit.com/r/SQLServer/)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
