### ISSUE TITLE
Please update this document to reflect the new support in .Net Core 3.0

### ISSUE THREAD

**Issue by SgtSpamCan** [MicrosoftDocs/sql-docs#3171]
.Net Core 3.0 release now supports Always Encrypted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb15ed8-749c-6cba-49d4-31f173644f73
* Version Independent ID: 4c3f1eb6-9db7-b056-d170-cdad560281df
* Content: [Always Encrypted (client development) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-client-development?redirectedfrom=MSDN&view=sql-server-2017)
* Content Source: [docs/relational-databases/security/encryption/always-encrypted-client-development.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/always-encrypted-client-development.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@SgtSpamCan Thank you for the feedback, assigning this to the author for review.

**Comment by VanMSFT** [comment]
@jaszymas - Hey Jakub, can you please confirm and help with this Issue? Thanks!

**Comment by VanMSFT** [comment]
Hi @SgtSpamCan! Thanks for bringing up this feedback. We are updating the document internally, and will be removing the note that AE is not supported in .Net Core. This will be reflected in the coming weeks as part of a larger update. If you have any questions, please feel free to let us know. Thanks again!

https://github.com/MicrosoftDocs/sql-docs-pr/pull/12274
