### ISSUE TITLE
return data type not clear

### ISSUE THREAD

**Issue by mariomuja** [MicrosoftDocs/sql-docs#3210]
"Returns character data"

this is not very specific - can you please update the documentation for the STUFF function to be more clear about which result data type (varchar/nvarchar/text, length?) is returned by this function in all possible execution paths?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b3f468-5782-d8f1-089f-59527367cdd6
* Version Independent ID: 60885f1b-5125-f2c4-c3d3-1ccd65e0859b
* Content: [STUFF (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/stuff-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/stuff-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/stuff-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@mariomuja Thank you for the feedback, assigning this to the author for comment.

**Comment by MikeRayMSFT** [comment]
@mariomuja Thanks for the note.

We're planning a documentation update to clarify this. 

Internally, we reference (1648827).
