### ISSUE TITLE
An inline scalar function has a body

### ISSUE THREAD

**Issue by camillagaardsted** [MicrosoftDocs/sql-docs#3218]
Hi microsoft,

I read this sentence: "For an inline scalar function, there is no function body; the scalar value is the result of a single statement." 

As far as I can see in the documentation for a scalar inline function and also during my test samples, I have concluded that it can have a body and you can use if statements and also have more than one return statement in the body. So an inline scalar function can use more complex statements like IF than compared to an inline table valued function, which only consists of one statement. The view sys.sql_modules tells me my sample functions are inlineable in the column is_inlineable.

Regards 

Camilla Gaardsted

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea8a53d-e5c1-bd0e-34ca-c68cedb738c8
* Version Independent ID: 59238b70-ff8d-8feb-9d0a-be85d20960db
* Content: [User-Defined Functions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/user-defined-functions?view=azuresqldb-current)
* Content Source: [docs/relational-databases/user-defined-functions/user-defined-functions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/user-defined-functions/user-defined-functions.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@camillagaardsted Thank you for the feedback.

Multiple return statements would still be considered returning a single value, perhaps this is being confused with a **multistatement scaler function** as described in the next sentence?

Apologies for any confusion.

**Comment by camillagaardsted** [comment]
Hi Matthew,

It's probably easier to understand what I mean if I provide an example. The
scalar function below is inlineable and it contains a body and not just one
statement, so the sentence I don't like in the article is this " For an
inline scalar function, there is no function body; the scalar value is the
result of a single statement.":

CREATE FUNCTION [dbo].FuncWithIF
(
    @param1 int,
    @param2 int
)
RETURNS INT
AS
BEGIN
DECLARE @val INT
IF @param1 > @param2
SET @val= @param1 + @param2
ELSE
SET @val= @param1 - @param2
RETURN @val
END

Regards

Camilla




Den tor. 10. okt. 2019 kl. 18.57 skrev Matthew Sebolt <
notifications@github.com>:

**Comment by msebolt** [comment]
@camillagaardsted  Thank you for the example.

I think I understand this now, the terms `function body` and `BEGIN...END` is incorrect in differentiating between inline and multi-statement.

The article has been updated.

Also as reference, [this post](https://stackoverflow.com/questions/2554333/multi-statement-table-valued-function-vs-inline-table-valued-function) provided a helpful comparison.
