### ISSUE TITLE
Missing Arguments

### ISSUE THREAD

**Issue by mco100** [MicrosoftDocs/sql-docs#3219]
Hi,
please add below arguments :
-k MaxTotalIndexes
-K MaxIndexesPerTable
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f86c62-487c-303e-bee9-d9de8da391e7
* Version Independent ID: 7efab1d1-e562-37f8-8be4-ba13edfcbb81
* Content: [dta Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/dta/dta-utility?view=sql-server-2017#examples)
* Content Source: [docs/tools/dta/dta-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/dta/dta-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mco100** [comment]
SSMS 18.2 offers many other arguments for dta
Could you update documentation accordingly ?

**Comment by msebolt** [comment]
@mco100 Thank you for the feedback, assigning the author for review.

**Comment by mco100** [comment]
could you tell what are values for -cl argument ?

**Comment by markingmyname** [comment]
@mco100,

I am discussing with our partner teams to make sure there are no other arguments missign we need to add as well.  I am also double checking if this article needs to be refreshed.

Thank you for your patience.

**Comment by markingmyname** [comment]
Added the -k/-K arguments to the dta article.

I will still be working on making sure this article is up to date with no missing arguments going forward.

Thank you.

**Comment by markingmyname** [comment]
It should be updated by tomorrow.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
