### ISSUE TITLE
instruction or link: how to clone an existing Git-Repo which is not yet cloned to a local directory, using Azure Data Studio

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/sql-docs#3221]
@aisbergde commented on [Thu Oct 10 2019](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/105)

I miss information how to clone an existing Git-Repository (for example on dev.azure.com, on github, ...) using only Azure Data Studio. Or if this is not possible with Azure Data Studio: A link or some instructions how to start.
Normally I use Visual Studio to clone and manage Git-Repos, but there are environments where VS can't be installed, but Azure Data Studio works fine.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a4e4bf78-49f5-ecce-a9bd-d89efab80063
* Version Independent ID: 805d36d2-8163-48be-1a02-55008b4b09f7
* Content: [Quellcodeverwaltung - Azure Data Studio](https://docs.microsoft.com/de-de/sql/azure-data-studio/source-control?view=sql-server-2017)
* Content Source: [docs/azure-data-studio/source-control.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/azure-data-studio/source-control.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

---

@srvbpigh commented on [Thu Oct 10 2019](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/105#issuecomment-540496944)

Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hi team, please check this issue.

Thanks!

**Comment by msebolt** [comment]
@srvbpigh  Thank you for the question, assigning this to the author for review.

**Comment by markingmyname** [comment]
Hi, @Ceciac,

Can we get this to the right localization team?

**Comment by CeciAc** [comment]
@markingmyname this is not a localization issue
@SunnyDeng

**Comment by craigg-msft** [comment]
@markingmyname probably adding a link to VS code functionality is the best answer, say https://code.visualstudio.com/docs/editor/github but given the user account that filed this item is no longer valid #please-close
