### ISSUE TITLE
.NET Core (preview)

### ISSUE THREAD

**Issue by droessmj** [MicrosoftDocs/sql-docs#3222]
We have a working deployment using the Windows sqlpackage.exe which authenticates using the AccessToken parameter. When using the .NET Core version of the tool, we see an error indicating which shows user as '' (empty). Is AccessToken expected to work with the .NET Core versions, or is that still in flight? If so, is this potentially just a quirk of CLI parameter parsing for the .NET Core version(s)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3df6af-9ac8-bc57-93dc-29ff713c1d3b
* Version Independent ID: 7624e2cc-7aa9-40dd-4015-3371ea2ea0a2
* Content: [Download and install sqlpackage - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-2017)
* Content Source: [docs/tools/sqlpackage-download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage-download.md)
* Product: **sql**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by droessmj** [comment]
For context, we'd love to be OS agnostic with our tools, but this specific item will require an asterisk for "do this thing only from Windows hosts". Thanks!

**Comment by pensivebrian** [comment]
@droessmj - Thanks for reporting this. Initially when porting sqlpackage to .NET Core, SqlClient didn't support the SqlConnection.AccessToken property, hence the current behavior. However, SqlClient now supports this property, and has for some time now, so this should be fixed.

Can you download and give the below versions of sqlpackage a try with the /AccessToken parameter? These are preview versions of sqlpackge with a fix for this issue.

Linux:
https://sqlpackage.blob.core.windows.net/preview/sqlpackage-linux-x64-en-US-15.0.4570.1.zip

Windows:
https://sqlpackage.blob.core.windows.net/preview/sqlpackage-win7-x64-en-US-15.0.4570.1.zip

**Comment by droessmj** [comment]
@pensivebrian - First few tests are looking real good using the version linked above. I've asked a colleague to independently recreate, but for now this seems to have resolved this issue with no change in the parameters being fed into the executable.

**Comment by WilliamAntonRohm** [comment]
@droessmj -- Michael, I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by pensivebrian** [comment]
@droessmj - Thanks for the confirmation! This fix will officially ship in the sqlpackage 18.4 release which should be available in a month or so.
