### ISSUE TITLE
SQL Server Version feature was implemented in

### ISSUE THREAD

**Issue by RichardMooreClear** [MicrosoftDocs/sql-docs#3223]
Can't see what SQL Server Version feature was implemented in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f019407-5787-6f54-1027-084e817b6b8e
* Version Independent ID: a92541d0-b63a-9603-2a1f-18e210be89e4
* Content: [FORMAT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/format-transact-sql?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Format_TSQL)%3Bk(sql13.swb.tsqlresults.f1)%3Bk(sql13.swb.tsqlquery.f1)%3Bk(MiscellaneousFilesProject)%3Bk(DevLang-TSQL)%26rd%3Dtrue&view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/format-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/format-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@RichardMooreClear -- thank you for your feedback.  FORMAT was first implemented in SQL Server 2016, and was not in SQL Server 2014.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by RichardMooreClear** [comment]
Hi SQL Docs

Are you sure it only started in SQL Server 2016.

Every where else I searched said SQL Server 2012

Kind regards

Richard Moore
[cid:image001.png@01D587E7.AB63FEB0]
This e-mail message, including any attachment(s), is intended solely for the addressee or addressees and is strictly confidential or otherwise legally protected.
If you are not the intended recipient of this communication please return this e-mail message and the attachment(s) to the sender and delete and destroy all copies

**Comment by RichardMooreClear** [comment]
Hi SQL Docs

Sorry I accidently deleted your reply to below.

But I just found

https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/hh213505%28v%3dsql.110%29

So is Format in SQL Server 2012 or not?

We are in the process of converting our existing DB to MS SQL and need to know what min version of SQL Server to advise our customers.

Kind regards

Richard Moore
[cid:image001.png@01D5880D.A45C9160]
This e-mail message, including any attachment(s), is intended solely for the addressee or addressees and is strictly confidential or otherwise legally protected.
If you are not the intended recipient of this communication please return this e-mail message and the attachment(s) to the sender and delete and destroy all copies

From: Richard Moore
Sent: Monday, 21 October 2019 08:15
To: MicrosoftDocs/sql-docs <reply@reply.github.com>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/sql-docs] SQL Server Version feature was implemented in (#3223)

Hi SQL Docs

Are you sure it only started in SQL Server 2016.

Every where else I searched said SQL Server 2012

Kind regards

Richard Moore
[cid:image001.png@01D5880D.A45C9160]
This e-mail message, including any attachment(s), is intended solely for the addressee or addressees and is strictly confidential or otherwise legally protected.
If you are not the intended recipient of this communication please return this e-mail message and the attachment(s) to the sender and delete and destroy all copies
