### ISSUE TITLE
Question regarding Publish action

### ISSUE THREAD

**Issue by baatch** [MicrosoftDocs/sql-docs#3230]
Question regarding Publish action in Sqlpackage.exe documentation, https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-2017

is it possible to not deploy database if it does not exist in the target server?

**Comment by WilliamAntonRohm** [comment]
@baatch -- thank you for your question.  To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by baatch** [comment]
> @baatch -- thank you for your question. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

Hi @WilliamAntonRohm 
I have updated the original post with more context and reference to the site.

**Comment by WilliamAntonRohm** [comment]
@baatch -- thank you for your clarification.

@pensivebrian -- please look into this issue 3230.

**Comment by pensivebrian** [comment]
@baatch - Currently there is no option like this for sqlpackage. sqlpackage will always create a database if one doesn't exist.
