### ISSUE TITLE
"Remarks" section referenced but not in document

### ISSUE THREAD

**Issue by altmank** [MicrosoftDocs/sql-docs#3241]
Several parts of the document mention:

"see "Remarks," later in this topic."

But then the document has no section labeled "Remarks" to go look at.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c94a997f-1840-46b8-3cdb-99ba8bf79784
* Version Independent ID: bca2acd4-c166-d3ad-3000-1c371d6fee26
* Content: [ALTER FULLTEXT INDEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-fulltext-index-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/alter-fulltext-index-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-fulltext-index-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@altmank -- thank you for your feedback.  The referenced section may be https://docs.microsoft.com/sql/t-sql/statements/alter-fulltext-index-transact-sql?view=sql-server-2017#interactions-of-change-tracking-and-no-population-parameter.  I will look into updating the documentation.

**Comment by WilliamAntonRohm** [comment]
@MightyPen -- test mention

**Comment by WilliamAntonRohm** [comment]
@CarlRabeler -- please review the changes in the above-mentioned PR #12453.
