### ISSUE TITLE
'Install SQL' article needs SQL 2019 added

### ISSUE THREAD

**Issue by MightyPen** [MicrosoftDocs/sql-docs#3243]
'Install SQL' article needs SQL 2019 added.  At least it will in a couple weeks from now.
And I a link to SQL Linux 2019 install might be nice too.

It is way too easy to forget about ongoing maintaining articles like this, too hard to remember. Thus, maybe this type of article is simply an obsolete/bad idea?

Thanks. (GeneMi = MightyPen).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f6a7b8-a953-79d3-e19a-297a1f5a6a29
* Version Independent ID: 8f23814e-a9e2-2f95-f7fd-d5d0bdb5c80d
* Content: [SQL Server Installation - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/installation-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/install-windows/installation-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/installation-for-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@MightyPen  Thank you for the feedback, assigning this to the author for review.

**Comment by MashaMSFT** [comment]
Hi @Mightypen, thanks for your feedback! We are tracking this work internally ([1333810](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1333810)) and as such will close out this Git Issue for the time being.

Please let us know if anything further is needed in the meantime :) 

Thanks!
Masha from the SQL Docs team
