### ISSUE TITLE
Use with image, ntext, or text data types.

### ISSUE THREAD

**Issue by MNF** [MicrosoftDocs/sql-docs#3244]
The page states "CHARINDEX cannot be used with image, ntext, or text data types." 
It is not exactly true. The function searches for the first part of the string (~7000 characters) and return correct results, if expression found.

To have expected results for the full string, it is enough to cast to NVARCHAR(MAX) as described in  https://stackoverflow.com/questions/31436479/sql-server-charindex-not-returning-index-for-long-search-strings/31436480#31436480 

SELECT CHARINDEX('keyword', CAST(Table.Field as NVARCHAR(MAX))) FROM Table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55cade6d-c03a-bce0-7ff0-2a734368827f
* Version Independent ID: 66231dfd-fd0e-e552-9215-345aeefc614c
* Content: [CHARINDEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/charindex-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/charindex-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/charindex-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srutzky** [comment]
For clarification, `TEXT` and `NTEXT` _are_ invalid, but only for "expressionToFind". For "expressionToSearch" it does work as mentioned by @MNF . Please note that the documentation is correct regarding:

> _expressionToFind_ has an 8000 character limit.

The following examples prove the statements made above:

```sql
SET NOCOUNT ON;
DECLARE @CharIndexText TABLE ([ID] INT, Col1 TEXT, Col2 NTEXT);

INSERT INTO @CharIndexText ([ID], [Col1], [Col2])
VALUES (1,
        REPLICATE(CONVERT(VARCHAR(MAX), 'A'), 8000) + 'B',
        REPLICATE(CONVERT(NVARCHAR(MAX), N'A'), 4000) + N'B');

INSERT INTO @CharIndexText ([ID], [Col1], [Col2])
VALUES (2,
        REPLICATE(CONVERT(VARCHAR(MAX), 'A'), 7999) + 'B',
        REPLICATE(CONVERT(NVARCHAR(MAX), N'A'), 3999) + N'B');

--SELECT * FROM @CharIndexText;


-- Yes, TEXT / NTEXT can be used for "expressionToSearch", but there is silent truncation:
SELECT [ID], CHARINDEX('B', t.[Col1]) AS [TEXT]
FROM   @CharIndexText t;

SELECT [ID], CHARINDEX(N'B', t.[Col2]) AS [NTEXT]
FROM   @CharIndexText t;

-- Yes, converting to MAX type allow for > 8000 bytes, and
-- start_location can then be > 8000 (> 4000 for NVARCHAR(MAX)):
SELECT [ID], CHARINDEX('B', CONVERT(VARCHAR(MAX), t.[Col1]), 8001) AS [MAX]
FROM   @CharIndexText t;


-- Yes, "expressionToFind" is limited to 8000 bytes:
SELECT [ID], CHARINDEX(REPLICATE(CONVERT(VARCHAR(MAX), 'B'), 8001),
                       CONVERT(VARCHAR(MAX), t.[Col1]), 8001) AS [Oops]
FROM   @CharIndexText t;
/*
Msg 8152, Level 16, State 10, Line XXXXX
String or binary data would be truncated.
*/
```

And (the following needs to be in a separate batch as it produces a compile-time error):

```sql
GO

-- No, TEXT / NTEXT cannot be used as for "expressionToFind":
SELECT CHARINDEX(CONVERT(TEXT, 'B'), 'AB');
/*
Msg 8116, Level 16, State 1, Line XXXXX
Argument data type text is invalid for argument 1 of charindex function.
*/
```

**Comment by msebolt** [comment]
@MNF  Thank you for the feedback, assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
@MNF  thank you for the submission. After a review with engineering, the documentation matches the functionality of the product.

**Comment by MNF** [comment]
The statement "CHARINDEX cannot be used with image, ntext, or text data types." doesn’t match. See srutzky comment:
“For clarification, TEXT and NTEXT are invalid, but only for "expressionToFind".
