### ISSUE TITLE
How to execute Sys.Dm_hadr_availability_replica_states?

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/sql-docs#3259]
What you need on this page is telling people how to execute sys.dm_hadr_availability_replica_states. I believe it is "SELECT * FROM sys.dm_hadr_availability_replica_states ".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e73ea0-e2d9-3f36-fc42-06072e79f421
* Version Independent ID: 7cbf3916-f036-12d8-115c-972e4e0c6026
* Content: [sys.dm_hadr_availability_replica_states (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-hadr-availability-replica-states-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-hadr-availability-replica-states-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-hadr-availability-replica-states-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@chanmmn Thank you for the feedback, assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
Thanks for the submission, @chanmmn 

I'm verifying a few things.

**Comment by MikeRayMSFT** [comment]
@chanmmn - I'm working with our PMs to update the content. This website offers some examples of how to use this DMV.

[7 ways to Query Always On Availability Groups using SQL](https://sqlundercover.com/2017/09/19/7-ways-to-query-always-on-availability-groups-using-sql/)
