### ISSUE TITLE
Anything that SSMS or Azure Data Studio do we can so with T-SQL 

### ISSUE THREAD

**Issue by pituach** [MicrosoftDocs/sql-docs#3273]
The claiming that "This task cannot be performed using Transact-SQL statements" make no sense, since these are client application which do the task using T-SQL, in the same way we can do it. It might be a bit complex, but we can always develop our own application which will do the same that these app do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76507156-d85c-e9f0-a214-3a9f1eb0f1fc
* Version Independent ID: 045c9c15-fbf9-abf9-c48a-904733e7ab42
* Content: [Change Column Order in a Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/change-column-order-in-a-table?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/change-column-order-in-a-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/change-column-order-in-a-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@pituach  Thank you for the feedback.

Your statement is true for any task that needs to restructure the database, however column order is considered a cosmetic trait, see [this post](https://stackoverflow.com/questions/1605144/how-to-change-column-order-in-a-table-using-sql-query-in-sql-server-2005).

If this is a feature you'd like included, please start a thread in the [SQL Server forums](https://feedback.azure.com/forums/908035-sql-server).

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by pituach** [comment]
Good day @msebolt 

Claiming that "columns order is cosmetic " is a huge mistake IMO, which marc_s did in the link you provided. In fact, I responded to his message in that specific thread long time ago and I explained this mistake in short. Search the comments for the respond from "Ronen Ariely", which is me by the way ("pituach" is just a nick name saying "developer" in Hebrew. I chose many years ago it in-contrast with all these who named themselves with nicknames like "The King", "The genius", "God" and so on... I decided to say that I am a simple developer [as I mentioned in the interview here](https://blogs.technet.microsoft.com/wikininjas/2013/11/11/interview-with-ronen-ariely-many-times-technet-guru-competition-winner/)). I quote this thread and several other experts (without mention the names) when I lecture about "SQL Server internals - Table structure".

The order of columns can directly impact the table's and the database's size, and it can even be related to errors which will raise in one order and not in another order! The question "is the order of columns important" is VERY common in the forums, and I showed multiple times a full demo code to present this including at stackoverflow and in the MSDN forums. The impact of order can start when we start to change the table structure.

In fact, [Just several day ago I spoke in the Israeli Data Platforms PASS group and I opened the meeting with this question](https://www.meetup.com/Data-Platform-Meetup-Israel/events/262090664), and full demo. This specific lecture was in Hebrew. In the summarize post of the lecture I added links to other posts which I wrote about physical table structure, including different demos. One of these is the full demo on this topic. The summarize post is in Hebrew, but the code and images are international and most of the other posts I have are in English. In addition, I spoke in other events on the same topic in English, and you can search for recording of one of these lectures to watch the demo.
[Meeting summary: Physical Table Structure under the hood, and implementation on real case scenarios (Hebrew)](http://ariely.info/Blog/tabid/83/EntryId/242/Physical-Table-Structure-under-the-hood-and-implementation-on-real-case-scenarios-Hebrew.aspx)
[This link is a pure code (almost) without any explanation, which demonstrate this specific topic](http://ariely.info/Blog/tabid/83/EntryId/243/Code-Order-of-columns-in-table-might-impact-the-size-of-the-table-database-and-even-related-to-errors.aspx).

**Back to the documentation:** 

As I see it, the documentation addresses regular users, and naturally it does not include any undocumented entities and internals information, which make sense as the name clearly speak about "undocumented". With that being said the documentation cannot say something that is wrong! It does not have to provide the full information, but it is wrong to say that it cannot be done with T-SQL. It does not mean that you need to provide the example to do it this way. 

This statement is wrong: "This task cannot be performed using Transact-SQL statements."
As I see it, instead, the document should say something like "This task is not supported using Transact-SQL statements." which make it accurate. Microsoft do not support this task using direct T-SQL, but there are people who can do it.

**Comment by pituach** [comment]
@WilliamAntonRohm please read my message above. At this time the documentation simply wrong.
Have a great day

**Comment by msebolt** [comment]
@pituach  Thank you for that informative post.  

I understand now and have updated the documentation per your suggestion.

We look forward to hearing from you again.

**Comment by pituach** [comment]
Awesome Matthew ( @msebolt ) 
Now it's look good👍
I glad I could help a bit😀
