### ISSUE TITLE
Can't access MSSQL usign a mac

### ISSUE THREAD

**Issue by fschroder** [MicrosoftDocs/sql-docs#3303]
I followed the instructions. Things look good, I can see the ticket when doing klist, but then it fails to login with error: Connection failed due to Kerberos error.
Help configuring Kerberos is available at https://aka.ms/sqlopskerberos
If you have previously connected you may need to re-run kinit.

see https://github.com/Microsoft/azuredatastudio/issues/447

Version: 1.12.1
Commit: cccb9327c707fe71de24d5ce655acb29cc8946d1
Date: 2019-10-07T19:26:59.245Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29dd905c-43f7-9045-4eee-c087e27f48e0
* Version Independent ID: 0e52d919-2745-c8c5-eb12-77b564f5e3d1
* Content: [Use Active Directory Authentication (Kerberos) - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/enable-kerberos.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/enable-kerberos.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @meet-bhagdev
* Microsoft Alias: **meetb**

**Comment by msebolt** [comment]
@fschroder  Thank you for the feedback, we're sorry you're experiencing issues.

Unfortunately issues here are for documentation concerns and/or general product questions only.

For support requests, please see [SQL Server Help and Feedback](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-ver15).

**Comment by WilliamAntonRohm** [comment]
cc @MightyPen -- notification test
