### ISSUE TITLE
Wrong EmployeeID values

### ISSUE THREAD

**Issue by DuncanP62** [MicrosoftDocs/sql-docs#3306]
The complex pivot query makes use of EmployeeID values [250], [251], [256], [257], [260]. However the commentary that follows talks about employees 164, 198, 223, 231, and 233.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45eba8b0-0c31-d65b-f1ca-0ed260eb2f14
* Version Independent ID: fe2a79c1-6512-36f6-3118-cda7d18531de
* Content: [Using PIVOT and UNPIVOT - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/from-using-pivot-and-unpivot?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/queries/from-using-pivot-and-unpivot.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/from-using-pivot-and-unpivot.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
@DuncanP62 - Thanks for pointing this out! We appreciate your help on our documentation. This is being fixed, and the revision should go live later today.

https://github.com/MicrosoftDocs/sql-docs-pr/pull/12439

#please-close
