### ISSUE TITLE
"Future Keywords" list seems out of date, many are keywords now

### ISSUE THREAD

**Issue by MightyPen** [MicrosoftDocs/sql-docs#3307]
In `https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-ver15#future-keywords`, the section says `CAST` might become a Reserved Keyword in Transact-SQL in SQL Server sometime in the future. Yet I believe `CAST` is already a keyword, as the article about "CAST and CONVERT" already strongly implies.  And there are other similar "future" keywords the same list that again seem keywords in SQL 2017+.

- `https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver15`

P.S.   Might be good to have an Aquent person turn all these actual T-SQL keywords into clickable LINKS to the Ref article that discusses each.

Thanks. GeneMi ( = MightyPen ).  2019/10/14.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f79ec4df-5309-60fc-1c20-f32b219fb9b9
* Version Independent ID: 6ee85c34-9a2c-e007-dcda-fb6016b98119
* Content: [Reserved Keywords (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-ver15#future-keywords)
* Content Source: [docs/t-sql/language-elements/reserved-keywords-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/reserved-keywords-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@MightyPen  Thank you for the feedback, assigning this to the author for review of `CAST`.

Including links would provide a nice feature, keywords like `ADD`  have no equivalent page and make such a list inconsistent.

**Comment by rothja** [comment]
@MightyPen Sorry for the long delay. I've seen customers bring up keyword questions in the past too, but I think this is a confusing area. I believe that CAST is not a keyword in transact-SQL the way that other keywords on the list are. See this example:
![image](https://user-images.githubusercontent.com/1580454/69178169-0ec10a80-0ad7-11ea-8e30-3f9b7e4485f5.png)

You can make CAST the name of the column without escaping it. That is not the case with "official" keywords. Why you can do this is not clear to me. Maybe we need to make the article more clear about what makes a keyword a keyword?

**Comment by MightyPen** [comment]
I guess 'CAST' is more like an arbitrary function name that can be called from the T-SQL language.  Thanks.
