### ISSUE TITLE
Not updated article with SQL 2017

### ISSUE THREAD

**Issue by MohamedHusseinT** [MicrosoftDocs/sql-docs#3309]
Hi, 
In applying step 2 (create index ui_ukDoc), it gives error on 2017 version due to the changes in schema.
I passed over the next steps, i found also that they are not matching the created one in the DB.

https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bacec67f-be0b-cae2-0299-18a387894a3b
* Version Independent ID: c6d947e9-c30a-234f-0c31-e0881d384c2a
* Content: [Get Started with Full-Text Search - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/search/get-started-with-full-text-search?view=sql-server-ver15)
* Content Source: [docs/relational-databases/search/get-started-with-full-text-search.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/search/get-started-with-full-text-search.md)
* Product: **sql**
* Technology: **search**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by msebolt** [comment]
@MohamedHusseinT Thank you for the feedback, assigning this to the author for review.

**Comment by cawrites** [comment]
@MohamedHusseinT I am looking into this issue. 
1. CREATE UNIQUE INDEX ui_ukDoc ON Production.Document(DocumentID);   **The DocumentID column does not exist.**

The second statement is impacted as well
2. CREATE FULLTEXT INDEX ON Production.Document  
(  
    Document                         --Full-text index column name   
        TYPE COLUMN FileExtension    --Name of column that contains file type information  
        Language 2057                 --2057 is the LCID for British English  
)  
KEY INDEX ui_ukDoc ON AdvWksDocFTCat --Unique index  
WITH CHANGE_TRACKING AUTO            --Population type;  
GO 

I will be updating with a solution.

**Comment by cawrites** [comment]
TABLE [Production].[Document](
	[DocumentNode] [hierarchyid] NOT NULL,
	[DocumentLevel]  AS ([DocumentNode].[GetLevel]()),
	[Title] [nvarchar](50) NOT NULL,
	[Owner] [int] NOT NULL,
	[FolderFlag] [bit] NOT NULL,
	[FileName] [nvarchar](400) NOT NULL,
	[FileExtension] [nvarchar](8) NOT NULL,
	[Revision] [nchar](5) NOT NULL,
	[ChangeNumber] [int] NOT NULL,
	[Status] [tinyint] NOT NULL,
	[DocumentSummary] [nvarchar](max) NULL,
	[Document] [varbinary](max) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Document_DocumentNode] PRIMARY KEY CLUSTERED 

Table does not contain DocumentID

**Comment by cawrites** [comment]
@MohamedHusseinT thank you for contacting Microsoft. We appreciate your review of our documentation. Our team is aware this is a priority and we have noted your request. 
As we update the content we will take this information into consideration.

**Comment by cawrites** [comment]
#please-close
