### ISSUE TITLE
/etc/ssl/private missing

### ISSUE THREAD

**Issue by eutychus83** [MicrosoftDocs/sql-docs#3310]
mv: cannot move ‘mssql.key’ to ‘/etc/ssl/private/’: Not a directory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8029b968-0ef5-a3a0-050f-a0b0189e5984
* Version Independent ID: 2ffb6a1e-5672-7742-d685-1d418c24f29c
* Content: [Encrypting Connections to SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-encrypted-connections?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-encrypted-connections.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-encrypted-connections.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by msebolt** [comment]
@eutychus83 Thank you for the feedback.

Depending on how OpenSSL is configured, the certs folder can be in different locations, see [this post](https://serverfault.com/questions/62496/ssl-certificate-location-on-unix-linux) for some examples.

You can use `openssl version -d` to see the path setting.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by eutychus83** [comment]
Thank you for your help!

On Oct 15, 2019, at 2:22 PM, William Anton Rohm <notifications@github.com<mailto:notifications@github.com>> wrote:


I am closing this issue now. You are welcome to @ mention me for any followup.
We hope to hear from you again.
