### ISSUE TITLE
newValue data type not clear

### ISSUE THREAD

**Issue by tphillipvidea** [MicrosoftDocs/sql-docs#3311]
The documentation does not make it clear newValue must be a [n]varchar or text value.  Other data types generate an error: Argument date type … is not value for argument 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c673e1d-891c-8c83-4566-b8bc27ce139d
* Version Independent ID: 3cd2f484-3a26-5c7b-cacc-16990b0c2be0
* Content: [JSON_MODIFY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-modify-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/json-modify-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/json-modify-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by msebolt** [comment]
@tphillipvidea Thank you for the feedback, assigning this to the author for review.

**Comment by cawrites** [comment]
@tphillipvidea please confirm if this content you are referring to:

newValue
The new value for the property specified by path.

In lax mode, JSON_MODIFY deletes the specified key if the new value is NULL.

JSON_MODIFY escapes all special characters in the new value if the type of the value is NVARCHAR or VARCHAR. A text value is not escaped if it is properly formatted JSON produced by FOR JSON, JSON_QUERY, or JSON_MODIFY.

**Comment by tphillipvidea** [comment]
This was in response to a forum post to correct the documentation, which I cannot find.

newValue must be able to implicitly convert to a (n)varchar.  Otherwise, it errors.

DECLARE @info NVARCHAR(100)='{"name":"John","skills":["C#","SQL"]}'

DECLARE @newdata date = '2019-01-01';


PRINT @info

-- Update name

SET @info=JSON_MODIFY(@info,'$.name',@newdata)

PRINT @info

Msg 8116, Level 16, State 1, Line 10
Argument data type date is invalid for argument 3 of json_modify function.

If date data type is not valid for newValue.  What data types are valid?  This should be clearly documented.

**Comment by cawrites** [comment]
@tphillipvidea thank you for contacting Microsoft. We value your feedback regarding our documentation and have applied your recommendation.

**Comment by cawrites** [comment]
#please-close
