### ISSUE TITLE
Wrong SQL Server version referenced.

### ISSUE THREAD

**Issue by ataraxia89** [MicrosoftDocs/sql-docs#3314]
"SQL Server downloads" leads to SQL Server 2017, not 2016 as referenced in this document. Also, due to Microsoft's infuriatingly simplified installer interface in 2017, there is no option to install LocalDB as a feature, again as referenced in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea66ca27-e0b1-cd1e-a8ef-55911169c71a
* Version Independent ID: f2340ce9-9771-851e-60a7-237c6e55f085
* Content: [SQL Server Express LocalDB - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/configure-windows/sql-server-express-localdb.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/sql-server-express-localdb.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@ataraxia89 -- thank you for your feedback.  I am looking into updating that article.  Please visit the [SQL Feedback page](https://aka.ms/sqlfeedback) to register your concerns with the installer.

**Comment by WilliamAntonRohm** [comment]
@ataraxia89 -- that link goes to the current SQL Server version.  Please see the [SQL Server 2016](https://www.microsoft.com/en-us/sql-server/sql-server-2016) page.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
