### ISSUE TITLE
Need a separate page or a section covering how to upgrade from SQL Server 2017 to SQL Server 2019. 

### ISSUE THREAD

**Issue by jaynar-cts1** [MicrosoftDocs/sql-docs#3320]
I would like to have a separate page or a section in https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-change-repo?view=sql-server-ver15&pivots=ld2-rhel#repositories covering how to upgrade from SQL Server 2017 to SQL Server 2019. It should cover FCI/AG/K8s scenarios.

For example Exxon has 3 node replica and if they ask how to upgrade we don’t have links to point to. We need to sequence like which node to upgrade and how to failover etc.. 
How to upgrade existing SQL Server 2017 to SQL Server 2019.

We can also have KB article and link it to Microsoft Docs.

**Comment by WilliamAntonRohm** [comment]
@jaynar-cts1 -- thank you for your feedback.

@VanMSFT -- please look into this issue 3320.

**Comment by VanMSFT** [comment]
Hi @jaynar-cts1! Thanks for the feedback. The upgrade sequence for Linux is the same as it would be on Windows: https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/windows/upgrade-a-sql-server-failover-cluster-instance?view=sql-server-ver15#perform-a-rolling-upgrade-or-update

Please utilize the following article for upgrading SQL Server on Linux: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup?view=sql-server-ver15#upgrade

We will investigate the additions to the Linux docs in the future, and your feedback is very helpful. Thanks again!
