### ISSUE TITLE
"Maximum File Size" Documentation Incorrect?

### ISSUE THREAD

**Issue by seanwhitepc** [MicrosoftDocs/sql-docs#3323]
I am able to set the maximum file size of an audit to 128 MBs without an error.  Is 1024 MB really the minimum value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233cfefa-453a-5c85-a3f7-e1a6e9a31815
* Version Independent ID: 417f38b4-6e46-d326-197d-2afd1a4b7136
* Content: [Create a Server Audit and Server Audit Specification - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/create-a-server-audit-and-server-audit-specification?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/security/auditing/create-a-server-audit-and-server-audit-specification.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/auditing/create-a-server-audit-and-server-audit-specification.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@seanwhitepc Thank you for the question, assigning this the author for review.

**Comment by VanMSFT** [comment]
Hi @seanwhitepc - Thanks for pointing this out. I confirmed that you can create a Server Audit with a maximum size lower than 1024MB.  I will change the doc. Thank you so much for your help on improving our documentation!

https://github.com/MicrosoftDocs/sql-docs-pr/pull/12492
