### ISSUE TITLE
TempTableChanged reason is missing

### ISSUE THREAD

**Issue by tussosedan** [MicrosoftDocs/sql-docs#3326]
TempTableChanged reason is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24764159-9678-dad1-dfbd-f0563e2146f9
* Version Independent ID: 87a7ac36-8697-6ddd-e9a4-fd8b019e3ecd
* Content: [sys.dm_db_tuning_recommendations (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-tuning-recommendations-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-db-tuning-recommendations-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-db-tuning-recommendations-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by msebolt** [comment]
@tussosedan Thank you for the feedback, assigning this to the author for review.

**Comment by julieMSFT** [comment]
#assign:julieMSFT

**Comment by julieMSFT** [comment]
@tussosedan Thank you for contacting Microsoft. I apologize for the delayed response to your submission. I am working to identify any missing reasons and have them added to the documentation.

**Comment by julieMSFT** [comment]
@tussosedan Hello. I apologize again for the delayed response to your submission. I am working to identify any missing reasons and have them added to the documentation.

**Comment by julieMSFT** [comment]
@tussosedan I am sorry for the delay in resolving this issue. We have updated the doc with the reasons you cited as missing. Thank you for your contribution to Microsoft Docs. I will go ahead with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
