### ISSUE TITLE
Manual Failover without dataloss notes

### ISSUE THREAD

**Issue by BIGabor** [MicrosoftDocs/sql-docs#3329]
To 5th step: Promote the target secondary replica to primary.
My note: in SQL2016 documentation: "Fail over from the primary availability group to the secondary availability group. Run the following command on the SQL Server that hosts the primary replica for the secondary availability group."
Till 5th step, all commands run in original PRIMARY, and 5th step should be executed on "original" SECONDARY.

In SQL2016 documentation there is a note after the 5th(last) step:
After completing the steps above, the distributed availability group fails over without any data loss. If the availability groups are across a geographical distance that causes latency, change the availability mode back to ASYNCHRONOUS_COMMIT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e33fa363-855a-a15d-f692-1b841363cc9f
* Version Independent ID: 9827e246-51df-6b3d-f21d-69c36b349860
* Content: [Perform a planned manual failover of an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/perform-a-planned-manual-failover-of-an-availability-group-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/perform-a-planned-manual-failover-of-an-availability-group-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/perform-a-planned-manual-failover-of-an-availability-group-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@BIGabor  Thank you for the feedback, assigning this to the author for review.

**Comment by MashaMSFT** [comment]
Hi @BIGabor , thanks for your feedback! Just to clarify, you're saying the following command should be executed on the secondary replica?

![image](https://user-images.githubusercontent.com/32783170/66962474-ee101b80-f025-11e9-813f-86175f2cc9c7.png)

My apologies, I'm not seeing this anywhere: After completing the steps above, the distributed availability group fails over without any data loss. If the availability groups are across a geographical distance that causes latency, change the availability mode back to ASYNCHRONOUS_COMMIT.

Nor am I understanding what your suggestion is regards to this note - are you saying it's missing and it should be added?

Thanks!
Masha from the SQL Docs team

**Comment by BIGabor** [comment]
Hi MashaMSFT,

sorry, that's from the Distributed AOGs failover. I mixed the two articles.
https://docs.microsoft.com/en-gb/sql/database-engine/availability-groups/windows/configure-distributed-availability-groups?view=sql-server-ver15#failover

In first step, mode altered to sync, but maybe it was async. It's up to the admin if he changes this back to async again after failover for some reason.

Regards,
Gabor

**Comment by MashaMSFT** [comment]
Hi @BIGabor, thanks for reaching out once more! My apologies, I am still not clear on what the proposed change should be for either documentation. 

Would you mind submitting an editorial pull request?
1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Name your file change and provide a description, if necessary
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page

There's a detailed gif here: https://aka.ms/editsqldcocs 

I hope that helps and please let me know how I can help further :)

Thanks!
Masha from the SQL Docs team

**Comment by BIGabor** [comment]
Hi Masha

No changes are required.
Just mixed on DOCs page Distributed AOGs with normal AOGs. My fault, sorry!

Regards,
Gabor
