### ISSUE TITLE
SQLPackage.exe is generating the script for Indexes which are ending with GUID(auto generated) even they are exists at target for 64 bit version

### ISSUE THREAD

**Issue by ghanchiasif** [MicrosoftDocs/sql-docs#3330]
I noticed glitch while generating the script through SqlPackage.exe from my machine and through release pipeline. 

In my machine, I had 32 bit version of sql package. The script for indexes are not generated because it’s exists in both source and destination. 

I got the error when I tried to deploy the same code through release pipeline where it picks the machine from hosted agent where it has 64 bit version of sql package.

To replicate, I installed sql package for 64 bit machine from below link and generated publish script and noticed that indexes are generated with create script only for those indexes which are ending with guid. 
https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-ver15

It seems those are created through auto tuning in Sql Azure and imported in project to keep it sync.

There might be some parameter which is not retuning the index information from target while comparing with source and generating create index script. 

I know one option to remove the index from my project but it will impact in future if there’s any change which required drop and re-create of the table through dacpac deployment. And I will miss this indexes.

Please help to fix this issue.

E.g.

PRINT N'Creating [dbo].[Person].[nci_wi_Person_1675E67CDFA297BB87E419681B39844A]...';

GO
CREATE NONCLUSTERED INDEX [nci_wi_Person_1675E67CDFA297BB87E419681B39844A]
    ON [dbo].[Person]([CreateBy] ASC, [CreateDate] ASC);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage.exe - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage.md)
* Product: **sql**
* Technology: **ssdt**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by pensivebrian** [comment]
@ghanchiasif - per the [release notes for sqlpackage 18.3.1](https://docs.microsoft.com/en-us/sql/tools/release-notes-sqlpackage?view=sql-server-ver15#fixes), sqlpackage now ignores automatic indexes, so you should remove them from your project. sqlpackage could be smarter in how it manages automatic indexes, but it's not currently being prioritized, and won't be fixed anytime soon.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
