### ISSUE TITLE
Should add "go" command after section 8. 

### ISSUE THREAD

**Issue by sundayhd** [MicrosoftDocs/sql-docs#3332]
Without the "go" command the query will not executed 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41367fc-38cf-0c73-3ea8-93bff726f421
* Version Independent ID: 07b2d0b3-2013-a133-9d1e-ee2d249740d5
* Content: [Connect to SQL Server When System Administrators Are Locked Out - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@sundayhd  Thank you for the feedback, assigning this to the author for review.

**Comment by MightyPen** [comment]
@sundayhd Hi sundayhd, can you be a bit more specific: exactly where is the GO needed?

GO is not needed at the end of the Transact-SQL script.
Is GO needed _**between**_ the following two statements?:

```
CREATE LOGIN [CONTOSO\PatK] FROM WINDOWS;  
ALTER SERVER ROLE sysadmin ADD MEMBER [CONTOSO\PatK];
```
 . .

**Comment by MikeRayMSFT** [comment]
The command succeeds without modifying the T-SQL.

If you're interested in submitting an update to the docs, see [How to contribute to SQL Server Documentation](https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute?view=sql-server-ver15)
