### ISSUE TITLE
<computed_column_definition>

### ISSUE THREAD

**Issue by JediSQL** [MicrosoftDocs/sql-docs#3333]
This page uses &lt;computed_column_definition&gt;, but it does not have a definition or link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abcca5d2-d433-96cc-930e-4de020c5785d
* Version Independent ID: fde147ff-b157-502c-276a-d3a2bf9bb3c7
* Content: [ALTER TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/alter-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@JediSQL  Thank you for the feedback, please see [computed_column_definition](https://docs.microsoft.com/sql/t-sql/statements/alter-table-computed-column-definition-transact-sql?view=sql-server-ver15).

...and use the TOC when navigating terms:

![Capture](https://user-images.githubusercontent.com/6675884/66966175-2b2ddb00-f031-11e9-8390-1b3a3129f13b.PNG)

Unfortunately, linking each term in-between articles would break the flow of content.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by JediSQL** [comment]
@WilliamAntonRohm
I guess I'm not used to topics being split across multiple pages. Now I know.

There is the standard paragraph that starts with "For more information about the syntax conventions..." For multi-page topics, maybe there could be a second sentence that identifies it as a multi-page topic and the need to use the TOC.
