### ISSUE TITLE
Only available on Azure SQL Database Managed Instance

### ISSUE THREAD

**Issue by Hal-H2Apps** [MicrosoftDocs/sql-docs#3334]
It could be confusing to not specify that this feature is not available on normal Azure SQL Database. You need to have a Managed Instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca33880-49c6-5ed6-ed13-2ae6171c9b37
* Version Independent ID: 3aed241c-299d-a1c6-3bdf-f44c439c13b8
* Content: [Capture Logon Trigger Event Data - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/triggers/capture-logon-trigger-event-data?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/triggers/capture-logon-trigger-event-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/triggers/capture-logon-trigger-event-data.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@Hal-H2Apps -- Hal, thank you for your feedback.

@rothja -- Jason, please look into this issue 3334.

**Comment by rothja** [comment]
@Hal-H2Apps Thank you for this feedback. I am going to get you to one of our SQL Database experts on my team. @stevestein Could you verify this and change the article that it only applies to Managed Instance if you confirm? Thanks. #reassign:stevestein

**Comment by stevestein** [comment]
@Hal-H2Apps - thanks for pointing this out. The article has been updated so the applies to info says managed instance only.

Thanks!

#please-close
