### ISSUE TITLE
Switching back to SNAPSHOT isolation level is possible

### ISSUE THREAD

**Issue by branko-d** [MicrosoftDocs/sql-docs#3337]
**EDIT 2:** However if the transaction is started under SNAPSHOT isolation, then it can switch to another isolation and then back to SNAPSHOT. This does **not** produce an error:

```
BEGIN TRAN
SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
SELECT * FROM FOO;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT * FROM FOO;
SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
SELECT * FROM FOO;
COMMIT;
```
Perhaps that should be better documented?

---

**EDIT:** Sorry, I neglected to notice this behavior is within the same transaction. Indeed when I do this...

```
BEGIN TRAN
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT * FROM FOO;
SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
SELECT * FROM FOO;
COMMIT;
```
...I get an error on the second SELECT:
```
Msg 3951, Level 16, State 1, Line 16
Transaction failed in database 'DB1' because the statement was run under snapshot isolation but the transaction did not start in snapshot isolation. You cannot change the isolation level of the transaction to snapshot after the transaction has started unless the transaction was originally started under snapshot isolation level.
```

Perhaps the documentation should be clarified that the error will not happen on SET TRANSACTION ISOLATION LEVEL SNAPSHOT, but on the first query after it, but is otherwise correct.

---

The following paragraph is incorrect:

> With one exception, you can switch from one isolation level to another at any time during a transaction. The exception occurs when changing from any isolation level to SNAPSHOT isolation. Doing this causes the transaction to fail and roll back.

Under my SQL Server 2017 Developer, I'm able to switch to SNAPSHOT isolation without any problems that I can see. For example, the following script will **not** cause an error:

```
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT * FROM FOO;
SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
SELECT * FROM FOO;
```

The first SELECT correctly waits on locks and the second SELECT correctly ignores locks and returns old row versions.

_Note: READ COMMITTED SNAPSHOT is OFF in my database._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86cc4c94-6124-2630-7f9a-163baa08c68a
* Version Independent ID: 062e657e-1ed4-0fd2-1fcb-87a281a1ad8f
* Content: [SET TRANSACTION ISOLATION LEVEL (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-transaction-isolation-level-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/set-transaction-isolation-level-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-transaction-isolation-level-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@branko-d -- thank you for your feedback.

@CarlRabeler -- please look into this issue 3337.

**Comment by rothja** [comment]
@branko-d I apologize but Carl is out of the office. @VanMSFT Can you please take a look at this feedback/question. Thank you! #reassign:vanmsft

**Comment by VanMSFT** [comment]
Hi @branko-d - Thanks for the feedback, and going into details about your issue. However, your 2nd edit shows precisely this behavior that is stated in our doc:

> With one exception, you can switch from one isolation level to another at any time during a transaction. The exception occurs when changing from any isolation level to SNAPSHOT isolation. Doing this causes the transaction to fail and roll back. **However, you can change a transaction started in SNAPSHOT isolation to any other isolation level.**
