### ISSUE TITLE
Possible incorrect applies to

### ISSUE THREAD

**Issue by FireStormHR** [MicrosoftDocs/sql-docs#3339]
This page mentions it doesnt aply to Azure SQL Database, but I tried the functions (ABS, ACOS etc.) and all mentioned functions are recognised and are even excuted on my Azure SQL database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea37453c-53c6-056d-46de-b53660afc859
* Version Independent ID: d2aa0683-f65f-7808-7667-8b8e2e90f78d
* Content: [Mathematical Functions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/mathematical-functions-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/mathematical-functions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/mathematical-functions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@FireStormHR -- thank you for providing these observations.

@MikeRayMSFT -- please look into this issue 3339.

**Comment by FireStormHR** [comment]
Looking further into this, it looks like FLOOR, SQUARE and the overview page are the incorrectly not-marked applies to's. The other specific pages of the mathematical functions are already marked as applies to for AzureSQL.

**Comment by MikeRayMSFT** [comment]
@FireStormHR - thanks. We're working on an update.

**Comment by CarlRabeler** [comment]
PR pending
