### ISSUE TITLE
SQL Data Warehouse

### ISSUE THREAD

**Issue by arashaga** [MicrosoftDocs/sql-docs#3342]
This applies to SQL Data Warehouse as well but on top it's indicated it's only available in SQL Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9825d0-343d-9a72-342c-3bd8bf7564e0
* Version Independent ID: 3b9185e6-d2aa-cfaf-6a0f-4da3d751080c
* Content: [Use OPENJSON with the Default Schema (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/use-openjson-with-the-default-schema-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/json/use-openjson-with-the-default-schema-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/use-openjson-with-the-default-schema-sql-server.md)
* Product: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@arashaga -- thank you for your feedback.

@jovanpop-msft -- please look into this issue 3342.

**Comment by jovanpop-msft** [comment]
@WilliamAntonRohm could you please assign this to some author for DW? Someone marked top-level page as supported in DW; however, other pages  are not marked. Not sure is this error or intentional, but this should be checked with DW doc/pm team.

**Comment by WilliamAntonRohm** [comment]
@jovanpop-msft -- thank you, I will.

**Comment by WilliamAntonRohm** [comment]
@julieMSFT -- please look into this issue 3342.

**Comment by julieMSFT** [comment]
@XiaoyuMSFT Xiaoyu, can you verify this should be marked as supported in SQL DW?

**Comment by julieMSFT** [comment]
@XiaoyuMSFT Xiaoyu, can you verify this should be marked as supported in SQL DW?

**Comment by julieMSFT** [comment]
@arashaga Thank you for submitting this issue. I am updating the page to show as supported in Azure Synapse. You will see the update on the docs site tomorrow. I will go ahead and close this issue but if you have further question you can still respond to this issue. Thank you.

**Comment by julieMSFT** [comment]
#please-close  #https://github.com/MicrosoftDocs/sql-docs-pr/pull/14641
