### ISSUE TITLE
Typo in EXEC sp_repldone example?

### ISSUE THREAD

**Issue by ColinPM** [MicrosoftDocs/sql-docs#3344]
EXEC sp_repldone @xactid = NULL, @xact_segno = NULL, @numtrans = 0,     @time = 0, @reset = 1 

should be

EXEC sp_repldone @xactid = NULL, @xact_seqno = NULL, @numtrans = 0,     @time = 0, @reset = 1 

ie the g in segno should be a q for seqno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c94213-3067-9778-159b-99b2e622df53
* Version Independent ID: 47a3d0a3-40dd-8c2a-39ac-340aff5ada0f
* Content: [sp_repldone (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-repldone-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-repldone-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-repldone-transact-sql.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@ColinPM  Thank you for the feedback.

The documentation has been updated per recommended change and is pending review.
