### ISSUE TITLE
Local user has to be created with another method for Windows Home users

### ISSUE THREAD

**Issue by marcoandre1** [MicrosoftDocs/sql-docs#3346]
Hi,  
creating a [new windows account](https://docs.microsoft.com/en-us/sql/t-sql/lesson-2-configuring-permissions-on-database-objects?view=sql-server-ver15#create-a-new-windows-account) as stated in the tutorial doesn't work for Windows Home. See [StackOverflow](https://stackoverflow.com/questions/41093714/why-local-users-and-groups-is-missing-in-computer-management-on-windows-10-home).  
You can probably add a note telling people that Local Users and Groups is missing in Computer Management on Windows 10 Home. The tutorial can be completed by creating a local user but not the way it is explained in the tutorial.  
Thanks!  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d451daf-8bc4-b2ec-8539-90d62803da4a
* Version Independent ID: 19eae858-fd92-b6dc-076b-6691e3eb9997
* Content: [T-SQL Tutorial: Configure permissions on database objects - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/lesson-2-configuring-permissions-on-database-objects?view=sql-server-ver15)
* Content Source: [docs/t-sql/lesson-2-configuring-permissions-on-database-objects.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/lesson-2-configuring-permissions-on-database-objects.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@marcoandre1 Thank you for the feedback, assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
Thanks @marcoandre1 - Investigating.

**Comment by MikeRayMSFT** [comment]
We're going to publish a fix for this:


>On Windows 10 Home does not include **Local Users and Groups**. To create a new user, complete the following steps:
> 1. Click **Start**, click **Run**. 
> 2. In the command prompt, type `NET USER Mary * /ADD`, and then press `CTRL`+`SHIFT`+`ENTER`.
> 3. When prompted, type a strong password

Thank you for submitting!
