### ISSUE TITLE
prerequisites of C++ build tools 14.0

### ISSUE THREAD

**Issue by siliang-jiao** [MicrosoftDocs/sql-docs#3347]
Trying to follow the guide [install azdata with pip](sql-docs/docs/big-data-cluster/deploy-install-azdata.md) to install azdata into windows server 2019 datacenter.  But got the "C++ build tool 14.0 is required" error when installing `Cython` (which is required for running `pip3 install -r https://aka.ms/azdata`)

Resolved it using
`choco install microsoft-visual-cpp-build-tools`

Could you please add a sentence of explanation of the above prerequisites requirement to documentation?

**Comment by msebolt** [comment]
Referencing https://docs.microsoft.com/sql/big-data-cluster/deploy-install-azdata.

@siliang-jiao Thank you for the feedback and posted work-around.

Assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
The latest recommendation is to install `azdata` with a package manager:

- [Windows installer](https://docs.microsoft.com/sql/big-data-cluster/deploy-install-azdata-installer?view=sql-server-ver15) 
- [Ubuntu](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-azdata-linux-package?view=sql-server-ver15)
