### ISSUE TITLE
python 3.8 not able to run `pip3 install https://aka.ms/azdata`

### ISSUE THREAD

**Issue by siliang-jiao** [MicrosoftDocs/sql-docs#3349]
Trying to follow the guide [install azdata with pip](sql-docs/docs/big-data-cluster/deploy-install-azdata.md) to install azdata into windows server 2019 datacenter. But got an error when installing `pywinpty` ( which is required to run `pip3 install https://aka.ms/azdata`).

seems like `pywinpty` is not ready for python 3.8 yet.

Could you please add a sentence of explanation above python3.8 to documentation?

**Comment by msebolt** [comment]
Related to issue https://github.com/MicrosoftDocs/sql-docs/issues/3347.

@siliang-jiao Thank you for the feedback, assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
The latest recommendation is to install `azdata` with a package manager:

- [Windows installer](https://docs.microsoft.com/sql/big-data-cluster/deploy-install-azdata-installer?view=sql-server-ver15) 
- [Ubuntu](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-azdata-linux-package?view=sql-server-ver15)
