### ISSUE TITLE
Versions are mixed and I don't think it's intended

### ISSUE THREAD

**Issue by chojrak11** [MicrosoftDocs/sql-docs#3356]
While I understand this is WIP for SQL Server 2019, I'd like to point out things I've noticed:
* I'm filtering the content by 2019 (upper left corner)
* The first sentence says: "This topic describes how to create, rebuild, or drop indexes online in SQL Server **2017** by using SQL Server Management Studio or Transact-SQL"
* The information in the box says "Online index operations are not available in every SQL Server edition. For more information, see Features Supported by the Editions of SQL Server **2016**."
* There's no info about the new features mentioned in "What's New" document - e.g. "Resumable online rowstore index build"
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cd99ac5-4414-3c3e-2fea-0f3c35821f30
* Version Independent ID: d29c1bd8-533a-99a5-fc52-02170c93f31d
* Content: [Perform Index Operations Online - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/perform-index-operations-online?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/indexes/perform-index-operations-online.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/perform-index-operations-online.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@chojrak11 -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue 3356.

**Comment by MikeRayMSFT** [comment]
@chojrak11 
- Thanks for the thorough review.
- I'm updating the version information and adding a link to the correct features and editions content. 
- I'll follow up with my engineering counterparts about more content for this article.

**Comment by MikeRayMSFT** [comment]
Added a link to [Resumable index considerations](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/guidelines-for-online-index-operations?view=sql-server-ver15#resumable-index-considerations).
