### ISSUE TITLE
Is there a way to opt-out?

### ISSUE THREAD

**Issue by TheConstructor** [MicrosoftDocs/sql-docs#3359]
Hi,

I am currently trying to find a way to override this behavior, as we have a case where we want to include a backslash followed by a line-break. Is this just undocumented (e.g. `\\` would not get replaced) or do I need to file a feature-request/bug against SQL Server elsewhere?

Best Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03d639c0-71aa-4c63-eb3b-4fba52a68904
* Version Independent ID: 3d4883e3-c5f1-d37d-7add-8c5ab55566da
* Content: [Backslash (Line Continuation) (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-backslash?view=sql-server-2016#feedback)
* Content Source: [docs/t-sql/language-elements/sql-server-utilities-statements-backslash.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/sql-server-utilities-statements-backslash.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by LarnuUK** [comment]
This only happens when using a literal string with the value. For example the below will return `testing`:
```sql
PRINT N'test\
ing';
```
If, however, you us `NCHAR` to insert the characters, the behaviour isn't replicated:
```sql
PRINT N'test\' + NCHAR(13) + NCHAR(10) + N'ing';
```
This returns:
```text
test\
ing
```

Seems like you're best bet would be to simply not use a literal value; so you problem need to simply parametrise your query.

**Comment by TheConstructor** [comment]
Wouldn't
```sql
PRINT N'test\' + '
ing';
```
be enough? Do `PRINT` and `EXEC` allow concatenation? Ideal would be a solution that works as literal.

**Comment by LarnuUK** [comment]
> 
> 
> Wouldn't
> 
> ```sql
> PRINT N'test\' + '
> ing';
> ```
> 
> be enough? Do `PRINT` and `EXEC` allow concatenation? Ideal would be a solution that works as literal.

That would work as well, yes. personal habit that I use `NCHAR(13)` and `NCHAR(10)`, as I tend to work on both Linux and Windows environments; so it keeps strings consistent between the 2. (Linux only uses Line break, where as Windows Carriage return the Line Break).

**Comment by WilliamAntonRohm** [comment]
@TheConstructor -- Matthias, thank you for your feedback.

@LarnuUK -- Thom, thank you for answering!

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by TheConstructor** [comment]
> `PRINT` does, `EXEC` does not. You can't pass an expression for any of the parameters for a Stored procedure, so parametrisation would seem the right choice there anyway.

I am using this from an automated context to generate scripts; this would mean, that I have to keep track of in-use variable names :-\

**Comment by TheConstructor** [comment]
@WilliamAntonRohm @LarnuUK I think I found a literal solution:

```sql
PRINT N'a\\

b';
```

Only the inner `\<CR><LF>` is replaced, so that the outer `\` and `<CR><LF>` touch afterwards.
