### ISSUE TITLE
Trace Flag 3427 as applies to 2017 is incorrect

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#3362]
Please review the description. It says 2017 is affected, but then says it is not affected.
Which is it and in what versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0e35dc1-14be-0678-aeae-88de1c7601ac
* Version Independent ID: b3700e3e-acbf-9248-c333-ac9013827d84
* Content: [Trace Flags (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by WilliamAntonRohm** [comment]
@brettshearer -- Brett, thank you for your close reading.

@pmasl, @MightyPen -- please look into this issue 3362.

**Comment by pmasl** [comment]
I'm correcting the information. Thanks!

**Comment by rothja** [comment]
It looks like this change was made back in October according to the article history. I am closing this issue. Thank you!
