### ISSUE TITLE
Incorrect inheritance

### ISSUE THREAD

**Issue by PawJershauge** [MicrosoftDocs/sql-docs#3363]
Acording to this article, sql_logins should inherit server_principals, but it doesn't.
sql_logins fails to inherit the following two columns from server_principals:

- `owning_principal_id`
- `is_fixed_role`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7432bff9-69c5-181a-8f9e-5501d7c03807
* Version Independent ID: bf59bcd2-80b2-53dd-060e-2575ac5c39d1
* Content: [sys.sql_logins (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-sql-logins-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-catalog-views/sys-sql-logins-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-sql-logins-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@PawJershauge -- Paw, thank you for your feedback.

@VanMSFT -- Van, please look into this issue 3363.

**Comment by VanMSFT** [comment]
Hello @PawJershauge! Thanks for submitting this issue. Sorry for the delay. I have changed the article to clarify that those 2 columns are not inherited.
