### ISSUE TITLE
SQL Server Monitoring Tools

### ISSUE THREAD

**Issue by CLLAX** [MicrosoftDocs/sql-docs#3364]
[Enter feedback here]
The real time alerts and email notification of [SQL Server Performance Monitoring Software](https://cllax.com/top-17-best-sql-server-performance-monitoring-tools-and-software.html) helps admin to manage space accordingly and avoid mishaps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7be88fdd-a8f6-d7b2-ef4b-484829401082
* Version Independent ID: 98077a8c-50ab-a992-afd8-cb27bbd51bee
* Content: [Performance Monitoring and Tuning Tools - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/performance-monitoring-and-tuning-tools?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/performance-monitoring-and-tuning-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/performance-monitoring-and-tuning-tools.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by msebolt** [comment]
@CLLAX  Thank you for providing a list of external tools for measuring SQL Server performance.

Please see [System Monitor](https://docs.microsoft.com/sql/relational-databases/performance-monitor/monitor-resource-usage-system-monitor?view=sql-server-ver15) and [Query Store](https://docs.microsoft.com/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-ver15) for some Microsoft alternatives and if there are any questions or concerns about SQL Server please comment below.
