### ISSUE TITLE
DST changes of Sao Paulo time zone are not determined by SQL Server 2017 on Linux

### ISSUE THREAD

**Issue by rafaelhumberto** [MicrosoftDocs/sql-docs#3367]
In this year America/Sao Paulo time zone doesn't have DST, but SQL Server 2017 Latest Linux  version have changed UTC to -02:00. (the normal value is -03:00).

You can observe DST active running this query: 
select * from sys.time_zone_info where name = 'E. South America Standard Time'

name                          |current_utc_offset|is_currently_dst|
------------------------------|------------------|----------------|
E. South America Standard Time|-02:00            |               1|

SQL Server version:

Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64) ¶ Sep 13 2019 15:49:57 ¶ Copyright (C) 2017 Microsoft Corporation¶ Developer Edition (64-bit) on Linux (Ubuntu 16.04.6 LTS)|

**Comment by msebolt** [comment]
@rafaelhumberto Thank you for the feedback and diagnosis.

Since this is product-related, please move this to the [SQL Server User Voice](https://feedback.azure.com/forums/908035-sql-server) and link back to this issue.

There the product team will respond and fix accordingly.

**Comment by rafaelhumberto** [comment]
Tks !
