### ISSUE TITLE
Teradata, not Terradata

### ISSUE THREAD

**Issue by oscarzamora** [MicrosoftDocs/sql-docs#3368]
Nitpicking here. Teradata instead "Terradata".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb42e0e-b056-6e2c-b8dd-8d9541f86fb8
* Version Independent ID: 9212ec4a-4862-7df7-0698-b3f01e46f631
* Content: [What are compute pools? - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/concept-compute-pool?view=sql-server-ver15#feedback)
* Content Source: [docs/big-data-cluster/concept-compute-pool.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/concept-compute-pool.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@oscarzamora Thank you for the feedback, we're glad to have all the help we can get.

The documentation has been updated.
