### ISSUE TITLE
Entity Reference Documentation Failure

### ISSUE THREAD

**Issue by JonnyWaffles** [MicrosoftDocs/sql-docs#3371]
Hi friends,

The two code examples given [here](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/xquery/primary-expressions-xquery.md) are the same, and thus the second one does not work either, thus it becomes unclear what the article is trying to express.

**Comment by WilliamAntonRohm** [comment]
@JonnyWaffles -- Jonny, thank you for your feedback.

@rothja -- Jason, please look into this issue 3371.

**Comment by rothja** [comment]
@JonnyWaffles Thank you for the question. You're referring to this repeated code sample:

```
DECLARE @var XML  
SET @var = ''  
SELECT @var.query(' <SalaryRange>Salary > 50000 and < 100000</SalaryRange>')  
GO  
```

That is strange and must be an oversight. I'll see if I can figure out what it should have said. Are you able to figure out what you need for your current task? Thanks!

**Comment by JonnyWaffles** [comment]
@rothja Hi Jason. Thanks for the response. Unfortunately, I don't have a current task to relate the item to. I was just trying to understand XQuery broadly, so I was reading all the documentation and this particular topic made no sense so I figured I'd ask you guys. Cheers.

**Comment by rothja** [comment]
@JonnyWaffles Thanks for sending this over. I'm fixing the sample today to show the `&lt;` and `&gt;` correctly in the sample in place of the greater and less than signs.

**Comment by rothja** [comment]
@JonnyWaffles Hi, in addition to the problem you noticed, I saw that the table above was not correctly displaying the escaped symbols. I fixed that too. Thank you for making the docs better!!
