### ISSUE TITLE
Diagramming tools?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/sql-docs#3377]
What program did you use to create the flowchart diagrams at the top of the screen? (https://docs.microsoft.com/en-us/sql/t-sql/functions/openjson-transact-sql?view=sql-server-ver15#openjson)
I've seen Microsoft use these in other docs and I find them very useful.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e25eda30-d6e4-600c-ed9d-4f0a53ee1058
* Version Independent ID: 9b53b7d7-b827-6f7f-c0c9-84645742d6a2
* Content: [OPENJSON (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/openjson-transact-sql?view=sql-server-ver15#openjson)
* Content Source: [docs/t-sql/functions/openjson-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/openjson-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@SeaDude -- thank you for your question and positive feedback.

@jovanpop-msft -- Jovan, please let us know whether this an external or internal tool, and thank you for your time.

**Comment by SeaDude** [comment]
I know its an *almost* non-related question, but these diagrams are quite unique and useful. 
Thank you !

**Comment by SeaDude** [comment]
The Jovan you're mentioning doesn't happen to be [_this_ Jovan](https://channel9.msdn.com/Shows/Data-Exposed/Using-JSON-in-SQL-Server-2016-and-Azure-SQL-Database), does he?

**Comment by CarlRabeler** [comment]
same Jovan

**Comment by cawrites** [comment]
@JocaPC can you provide an answer to the question regarding tool was used to design these diagrams?

**Comment by cawrites** [comment]
@SeaDude thank you for contacting Microsoft. I understand this is still an outstanding question but as this is not a content issue I would suggest contacting him through his Twitter handle @JovanPop_MSFT, it is likely you will get the response you need.

**Comment by cawrites** [comment]
#please-close

**Comment by JocaPC** [comment]
This tool is used: http://www.bottlecaps.de/rr/ui

**Comment by SeaDude** [comment]
@JocaPC , thank you very much.
