### ISSUE TITLE
Incorrect spelling of MSSQL_PID

### ISSUE THREAD

**Issue by DutchMarcel** [MicrosoftDocs/sql-docs#3378]
In sections 'Use with initial setup' and 'Use with Docker' the MSSQL_PID variable is incorrectly spelled as MSSSQL_PID. In the code samples the spelling is correct.

Regards,
Marcel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12eac8a-8797-b2d4-5195-e1d77b4b0001
* Version Independent ID: 163b4b50-6e25-b006-6ea6-c6e4cfd044d0
* Content: [Configure SQL Server settings with environment variables - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-configure-environment-variables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-environment-variables.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Thanks @DutchMarcel for reporting this issue. The document is currently being updated by @Potapy4. Thanks for all your help on our documentation!
