### ISSUE TITLE
sp_update_job @notify_level_email valid values wrong 

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#3380]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/sql-docs.de-de/issues/109

@abbgrade commented 12 hours ago
The description for parameter @notify_level_email is wrong.
Value 0 for 'Never' is not supported. The error message is:

    The specified '@notify_level_email' is invalid (valid values are: 1, 2, 3).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c3735b-36b2-f19e-c4ce-41e6ce3e277f
* Version Independent ID: 0af58b01-c988-dbeb-f9d6-c2214f348aa9
* Content: [sp_update_job (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-update-job-transact-sql?view=sql-server-2016#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-update-job-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-update-job-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, thank you for bringing this to our attention.

@stevestein -- Steve, please look into this issue 3380.

**Comment by stevestein** [comment]
@CeciAc - thanks for raising this issue. An internal work item (1642023) has been opened to track the work related to updating this article. 

Thanks!

#please-close
