### ISSUE TITLE
Default value for Script indexes option

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/sql-docs#3381]
For the Script indexes option, Default is "True " in the description but looks like the default is "False" - could you please check it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b12f56f-4709-cab6-33a2-52acb1581ff8
* Version Independent ID: c6790f69-453e-ffce-6f79-5aa3a656e80b
* Content: [Options (SQL Server Object Explorer - Scripting Page) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/object/options-sql-server-object-explorer-scripting-page?view=sql-server-ver15#object-scripting-options)
* Content Source: [docs/ssms/object/options-sql-server-object-explorer-scripting-page.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/object/options-sql-server-object-explorer-scripting-page.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@kazshi Thank you for the feedback.

I am using the latest version of SSMS and the default is `True`.

![Capture2](https://user-images.githubusercontent.com/6675884/67508084-2aa2cf00-f645-11e9-9f2c-83e517598975.PNG)

Comment below if there are any questions.

**Comment by kazshi** [comment]
@msebolt Thanks for your comment/confirmation. For entire database and all database objects, you're right - the default is True. But it's False if we select specific objects (a table for example) - sorry for my insufficient explanation - I'm not sure if it's by design, please close if it's by design.

**Comment by msebolt** [comment]
@kazshi  Thank you for the clarification.

I've added a note to the documentation to better reflect this discrepancy and changes are pending review.
