### ISSUE TITLE
Up-to-date?

### ISSUE THREAD

**Issue by saandersen** [MicrosoftDocs/sql-docs#3386]
This page hasn't been updated for a while, and there are a few CU's that have been released that are not listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1353d4d-3899-d6cf-e44f-8536c7828335
* Version Independent ID: de0210cf-386a-f8c8-1157-40cea207ed4b
* Content: [Latest updates for Microsoft SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/latest-updates-for-microsoft-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/install-windows/latest-updates-for-microsoft-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/latest-updates-for-microsoft-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @tmichael-ms
* Microsoft Alias: **tmichael**

**Comment by msebolt** [comment]
@saandersen  Thank you for the feedback, assigning this to the author for review.

**Comment by CarlRabeler** [comment]
@saandersen closing this git issue as this topic has been updated multiple times since you opened this issue. Thanks for bringing this to our attention. 
Carl
