### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by naveedm143** [MicrosoftDocs/sql-docs#3387]
The text under heading "Permissions" states that "VIEW SERVER STATE cannot be granted in SQL Database so sys.dm_exec_requests is always limited to the current connection." This is ambiguous. I believe it means AZURE SQL Database. Can the text be change to to "VIEW SERVER STATE cannot be granted in AZURE SQL Database so sys.dm_exec_requests is always limited to the current connection.". This will help the reader.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 785e6be1-0c51-7690-1eb6-c4c98c7c1133
* Version Independent ID: 79592f3b-ccff-06bd-eed8-08ab1bf74205
* Content: [sys.dm_exec_requests (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by pmasl** [comment]
SQL Database and Azure SQL Database are synonyms. That much is used in many pages. Will add this to backlog. @MikeRayMSFT it would be useful to look for all pages using the [!INCLUDE[ssSDS](../../includes/sssds-md.md)] token and replace with [!INCLUDE[ssSDSfull](../../includes/sssdsfull-md.md)], or change the token content itself from _SQL Database_ to _Azure SQL Database_

**Comment by pmasl** [comment]
@msebolt please assign @MikeRayMSFT or @MashaMSFT for follow-up.

**Comment by CarlRabeler** [comment]
addressed in this topic - we generally say Azure SQL Database for the first instance of the string in an article and then SQL Database thereafter, as that is the actual product name. Changing the token globally will have some number of undesirable consequences.
