### ISSUE TITLE
Very confusing phrasing

### ISSUE THREAD

**Issue by dministrator** [MicrosoftDocs/sql-docs#3388]
> AFTER is the default when FOR is the only keyword specified.

What exactly does this mean? Can this be worded better? There is no description provided for the **FOR** keyword. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8add50-414a-a033-6fc0-84de1c7735f2
* Version Independent ID: 8f2f3149-7035-b3d4-6f09-a6eadd015e24
* Content: [CREATE TRIGGER (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-trigger-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-trigger-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-trigger-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@dministrator -- thank you for your feedback.  I am looking into the documentation.

**Comment by WilliamAntonRohm** [comment]
@CarlRabeler -- please look into this issue 3388, as it is beyond my expertise.

**Comment by rothja** [comment]
@dministrator Thank you again for this feedback. @CarlRabeler is out of the office, so I am going to ask @VanMSFT if he could take a look at this and see if there is a better way we could explain this. @VanMSFT can you help? #reassign:VanMSFT

**Comment by VanMSFT** [comment]
Hi @dministrator! Thanks for bringing up this feedback. There's no difference between the Arguments FOR and AFTER in a Trigger. AFTER just has a better connotation since it follows the context that the `DML trigger fires only when all operations specified in the triggering SQL statement have launched successfully`. I'll re-word the documentation for better clarity. Thanks again!

**Comment by dministrator** [comment]
@VanMSFT @rothja @CarlRabeler @WilliamAntonRohm - Thank you all for considering my feedback.
