### ISSUE TITLE
Please add a spec on what units the returned distance is in.

### ISSUE THREAD

**Issue by dalton478** [MicrosoftDocs/sql-docs#3389]
Nominal required text

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35760e7-cf19-be8e-2bed-8cac09519942
* Version Independent ID: 86fdd88f-6d3f-f775-32be-100f1c855f9a
* Content: [STDistance (geography Data Type) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geography/stdistance-geography-data-type?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/spatial-geography/stdistance-geography-data-type.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/spatial-geography/stdistance-geography-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@dalton478 -- thank you for your concise feedback.

@MladjoA -- please look into this issue 3389.

**Comment by gbjbaanb** [comment]
FYI, to find any unit used in a SRID do this:

`SELECT * FROM sys.spatial_reference_systems WHERE spatial_reference_id = 4326`

which returns metres in SQL Server. 

However! The answer is supposed to return degrees as this is what SRID 4326 uses. 
However! But STDistance() returns metres. 
However! This only applies for geography types, if you calc distance on geometry columns, then you get degrees.
However! ha, got you that time :)

so its wrong, but right at the same time (or right, but wrong). I can only assume STDistance in SQLServer has helpfully transformed the results to a useful answer for geography, which is nice. 

Maybe its time to add a extra parameter to STDistance to return native units (ie degrees for 4326), but also to use a faster haversine algorithm for those who just want quick results (postgis can return a quick distance calc on using a sphere if you pass in false to it, for example)

**Comment by cawrites** [comment]
@dalton478 in regards to: https://docs.microsoft.com/en-us/sql/t-sql/spatial-geography/stdistance-geography-data-type?view=sql-server-ver15  

Please review the usage as stated here:
https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-reference-identifiers-srids?view=sql-server-ver15

SRID can be defined as:
Linear unit of measure
Units of measure  (degrees, meters, and so on)
Maximum and minimum coordinates (also referred to as the bounds)
Planar or spheroid data
Projection information for transforming the data to other SRSs

The table sys.spatial_reference_systems in SQL Server contains all the spatial reference systems (SRIDs) supported by SQL Server.

**Comment by cawrites** [comment]
@dalton478 thank you for contacting Microsoft we apologize for the delay in our response. Please do not hesitate to contact us again if you have any further questions.

**Comment by cawrites** [comment]
#please-close
