### ISSUE TITLE
The commands given in the "Persist your data" section do not work when using Linux containers on Windows

### ISSUE THREAD

**Issue by trbenning** [MicrosoftDocs/sql-docs#3390]
The command given, `docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=&lt;YourStrong!Passw0rd&gt;" -p 1433:1433 -v <host directory>:/var/opt/mssql -d mcr.microsoft.com/mssql/server:2019-CTP3.2-ubuntu` will fail due to a file access violation. It is better to explicitly mount the data & log directories instead:

`docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=&lt;YourStrong!Passw0rd&gt;" -p 1433:1433 -v <host directory>/data:/var/opt/mssql/data -v <host directory>/log:/var/opt/mssql/log -d mcr.microsoft.com/mssql/server:2019-CTP3.2-ubuntu`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dc2ec36-4915-f7ab-3104-282acc9321e6
* Version Independent ID: fc98af17-f3c5-adff-69ca-593f985e7882
* Content: [Configuration options for SQL Server on Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-ver15#persist)
* Content Source: [docs/linux/sql-server-linux-configure-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by WilliamAntonRohm** [comment]
@trbenning -- Todd, thank you for your feedback.  I am looking into it now.

**Comment by WilliamAntonRohm** [comment]
@vin-yu -- Vin, please review the above-mentioned PR 12703.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please review [PR 12703](https://github.com/MicrosoftDocs/sql-docs-pr/pull/12703).

**Comment by danvalero** [comment]
It works when I sue the 2017 image, but it does not work with 2019 image

**Comment by VanMSFT** [comment]
Following up with @vin-yu

**Comment by WilliamAntonRohm** [comment]
@VanMSFT, @vin-yu -- Van, Vin, please look into this issue and [PR 12703](https://github.com/MicrosoftDocs/sql-docs-pr/pull/12703).

**Comment by danvalero** [comment]
any update in this matter?

**Comment by CraigHead** [comment]
I can confirm at least on 2019 Sql Server. Only mount the data and log directories. The documentation should be updated to reflect this.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT, @vin-yu -- Van, Vin, please look into this issue and [PR 12703](https://github.com/MicrosoftDocs/sql-docs-pr/pull/12703).

**Comment by CraigHead** [comment]
I opened PR 3913 to address this.
#3913

**Comment by WilliamAntonRohm** [comment]
@CraigHead -- Craig, thank you for your contribution.

@VanMSFT, @vin-yu -- Van, Vin, please look into this issue and PRs 12703 & #3913.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT, @vin-yu -- Van, Vin, please look into this [PR 12703](https://github.com/MicrosoftDocs/sql-docs-pr/pull/12703) and PR #3913.

**Comment by VanMSFT** [comment]
Thanks @trbenning for bringing up this issue!

Thanks @CraigHead for making the appropriate changes!
