### ISSUE TITLE
What is a "Windows file" in this doc?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/sql-docs#3391]
Do you mean *local* file? or do you mean a file created on a Windows OS? or something else? [There isn't such as things as a "Windows file"](https://www.google.com/search?source=hp&ei=4XayXZCQHZPV9APBhIm4Cw&q=What+is+a+%22Windows+file%22%3F&oq=What+is+a+%22Windows+file%22%3F&gs_l=psy-ab.3..0l4j0i22i30l6.1270.1270..3386...0.0..0.94.94.1......0....2j1..gws-wiz.1YuxdCSiwec&ved=0ahUKEwjQhOizxrblAhWTKn0KHUFCArcQ4dUDCAc&uact=5). 
Please clarify this term.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbec06eb-2341-9186-a24f-adc129642169
* Version Independent ID: d32aa975-1187-ede1-e775-a590c0dba458
* Content: [OPENROWSET (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/openrowset-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/openrowset-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/openrowset-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@SeaDude -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue 3391.  The particular sentence in this article is "Azure SQL Database does not support reading from Windows files.".

**Comment by sqlsauce** [comment]
With Azure SQL Database, there is no local Windows file system, so it cannot connect to local drives, and it cannot connect to UNC paths; it only supports Azure Blob Storage for BULK INSERT. I recommend changing the text from _Azure SQL Database does not support reading from Windows files_ to _Azure SQL Database does not support Windows file paths or UNC paths_.

Also, I suggest adding the same note block below the `FORMAT = 'CSV'` example under [Input file format options](https://docs.microsoft.com/en-us/sql/t-sql/statements/bulk-insert-transact-sql?view=sql-server-ver15#input-file-format-options).

**Comment by CarlRabeler** [comment]
@MikeRayMSFT I am addressing this issue

**Comment by CarlRabeler** [comment]
PR pending
