### ISSUE TITLE
re: memory consumption

### ISSUE THREAD

**Issue by duncfair** [MicrosoftDocs/sql-docs#3395]
is there a memory advantage to using the CmdExec method? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db6f2a8a-7b0a-b5b6-7095-b7569d2c23bb
* Version Independent ID: 26d6594a-6d7d-7091-0f4b-382bb4a38ebe
* Content: [Run Windows PowerShell Steps in SQL Server Agent - SQL Server](https://docs.microsoft.com/en-us/sql/powershell/run-windows-powershell-steps-in-sql-server-agent?view=sql-server-ver15#feedback)
* Content Source: [docs/powershell/run-windows-powershell-steps-in-sql-server-agent.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/run-windows-powershell-steps-in-sql-server-agent.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@duncfair -- thank you for your question.

@markingmyname -- please look into this issue 3395, possibly regarding [this caution](https://docs.microsoft.com/en-us/sql/powershell/run-windows-powershell-steps-in-sql-server-agent?view=sql-server-ver15#LimitationsRestrictions).

**Comment by markingmyname** [comment]
@duncfair,

I apologize for the delayed response, but the answer is "yes."

When I did my own test with CMDExec I was around 724 KB vs PowerShell at about 31000kb.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
