### ISSUE TITLE
Install Pre-reqs Needs Attention

### ISSUE THREAD

**Issue by cdotzenrod** [MicrosoftDocs/sql-docs#3398]
I'm running into a lot of issues trying to get the pre-req tools installed.  Most of my issues have been trying to figure out what exactly needs to be installed to get azdata to install.  I went down some rabbit holes trying to put the right C++ build tools on my test machine but still couldn't get azdata to install due to Cython issues and CLI issues.  I think the documentation needs some more requirements or guidance on the Cython requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99908ff8-cfba-af0d-1415-c366a9f380c5
* Version Independent ID: 30494d83-bf1e-6085-04b3-8b02ff19e301
* Content: [Install azdata using pip - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-azdata?view=sql-server-ver15#feedback)
* Content Source: [docs/big-data-cluster/deploy-install-azdata.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-install-azdata.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by cdotzenrod** [comment]
Perhaps a better way to say this:  I have a clean Windows 10 VM from Azure.  What software packages will this workstation need in order to successfully install Azure Data Studiom- Insiders and the required big data tools for building a BDC on AKS.

**Comment by msebolt** [comment]
@cdotzenrod Thank you for the feedback, assigning this to the author for review.

**Comment by craigdallen** [comment]
@cdotzenrod Same thing on both Cython and C++ v14.

I did PS> pip install Cython

That got past the Cython error.

Next, C++ error. 

I did PS> choco install visualstudio2017enterprise

This is version 14 of C++. Still errored. Next installed 2019, same error.

I let Buck Woody know of the install error.

Environment: Azure D2 VM (Win10 virgin install)

**Comment by MikeRayMSFT** [comment]
The latest recommendation is to install `azdata` with a package manager:

- [Windows installer](https://docs.microsoft.com/sql/big-data-cluster/deploy-install-azdata-installer?view=sql-server-ver15) 
- [Ubuntu](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-azdata-linux-package?view=sql-server-ver15)
