### ISSUE TITLE
SqlPackage throws exception: System.ArgumentNullException: Value cannot be null. Parameter name: reportedElement

### ISSUE THREAD

**Issue by nickQuant** [MicrosoftDocs/sql-docs#3400]
I'm hitting an issue comparing two DACPAC files using the latest version of SqlPackage (15.0.4518.2).

The output is:
Microsoft.Data.Tools.Diagnostics.Tracer Information: 1 : 2019-10-28T15:09:28 : Generating operation 4 for [ContactCentre].[SP_RESOURCE__DIM]
Microsoft.Data.Tools.Diagnostics.Tracer Information: 1 : 2019-10-28T15:09:28 : Generating operation 1 for [eds_Satalia]
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2019-10-28T15:09:28 : SqlStudioException.TraceException(Exception)
 Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: reportedElement
*** Value cannot be null.
Parameter name: reportedElement
Time elapsed 00:00:17.03
Microsoft.Data.Tools.Diagnostics.Tracer Information: 0 : 2019-10-28T15:09:28 : SqlPackage completed

The command line run is: sqlpackage /TargetFile:"currentUAT.dacpac" /Action:DeployReport /SourceFile:"AZDDCDBA0001_CEK1.dacpac"  /op:output.xml /targetdatabasename:xxx /d:True

DACPAC files attached

[DB Extract.zip](https://github.com/MicrosoftDocs/sql-docs/files/3777177/DB.Extract.zip)

**Comment by msebolt** [comment]
@nickQuant  Thank you for the feedback.

Unfortunately this sounds like more of an issue for the product team then documentation.

Please start a thread in the [SQL Server forum](https://social.msdn.microsoft.com/Forums/home?forum=sqldocumentation,sqldatabaseengine) and link back to reference this issue.

**Comment by nickQuant** [comment]
Thank you - done at https://social.msdn.microsoft.com/Forums/en-US/ddcf82c3-e895-4d50-9504-1c259e16565b/sqlpackage-throws-exception-systemargumentnullexception-value-cannot-be-null-parameter-name?forum=ssdt for anyone that encounters the same issues and wants to follow the bread-crumbs :)

**Comment by nickQuant** [comment]
Issue has been up for over a week.  Disappointing the team can't be bother responding :/
