### ISSUE TITLE
Number of error logs seems to be wrong

### ISSUE THREAD

**Issue by ildjarnisdead** [MicrosoftDocs/sql-docs#3403]
&gt; The default is 6, one current and the 5 previous backup logs that SQL Server retains before recycling them.

Fresh install of SQL 2017: ERRORLOG and ERRORLOG.[1-6]. So six previous backup logs, not 5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1504e2ae-7082-a7e6-d5cc-a067174e17f7
* Version Independent ID: f67cacf7-54f3-0f7e-55f3-3618d7464dba
* Content: [Configure SQL Server Error Logs - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/scm-services-configure-sql-server-error-logs?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/configure-windows/scm-services-configure-sql-server-error-logs.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/scm-services-configure-sql-server-error-logs.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@ildjarnisdead  Thank you for the feedback, assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
I'm submitting the fix. Thank you for raising this issue.
