### ISSUE TITLE
How to parameterise sqlcmd on Ubuntu16 or MacOs

### ISSUE THREAD

**Issue by abij** [MicrosoftDocs/sql-docs#3404]
The option `-v` does NOT exist in Linux/Mac version of the command utility.
We are using the DevOps Linux (Ubuntu16) Build Agents, this tool is pre-installed, but its hard to figure out how to call a SQL-script with parameters. Can you include an example how to pass parameters for the non-windows version?

The correct way is:
`var1="MyValue1" var2="Value2" sqlcmd -S "SERVER.database.windows.net" -d "dbname" -U "user" -P "password" -i scriptfile.sql -b`

The -b is to fail on error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da1f57b-a8fd-cca7-4cf0-9d594d365062
* Version Independent ID: 60c46780-6a03-7958-c77a-e7c94e3b9e85
* Content: [sqlcmd Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15)
* Content Source: [docs/tools/sqlcmd-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlcmd-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@abij  Thank you for the feedback, assigning this to the author for review.  

This could also be mentioned in the [SQL Server for Linux setup](https://docs.microsoft.com/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15).

@VanMSFT

**Comment by markingmyname** [comment]
@abij,

We apologize for the delayed response.

Did this article not help you at all? - https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15.

Please confirm.

Thank you.

**Comment by markingmyname** [comment]
Due to no response, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
