### ISSUE TITLE
Register SPN without port number for SSRS breaks remote WinRM

### ISSUE THREAD

**Issue by Teutenberg** [MicrosoftDocs/sql-docs#3408]
```
Document should be updated to include port number and a note added about the error mentioned below. 

https://docs.microsoft.com/en-us/sql/reporting-services/report-server/register-a-service-principal-name-spn-for-a-report-server?view=sql-server-ver15

ERROR:
[localhost] Connecting to remote server localhost failed with the following error message : WinRM cannot process the
request. The following error with errorcode 0x80090322 occurred while using Negotiate authentication: An unknown
security error occurred.
Possible causes are:
  -The user name or password specified are invalid.
  -Kerberos is used when no authentication method and no user name are specified.
  -Kerberos accepts domain user names, but not local user names.
  -The Service Principal Name (SPN) for the remote computer name and port does not exist.
  -The client and remote computers are in different domains and there is no trust between the two domains.
After checking for the above issues, try the following:
  -Check the Event Viewer for events related to authentication.
  -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or
use HTTPS transport.
Note that computers in the TrustedHosts list might not be authenticated.
   -For more information about WinRM configuration, run the following command: winrm help config. For more
information, see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (localhost:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : -2144108387,PSSessionStateBroken


SOLUTION:
# Returns the HTTP SPN. When executed it showed that the HTTP SPN without port number was assigned to an SSRS service account. This breaks PowerShell remote access. 
setspn -Q HTTP/<SERVERNAME>*

# To fix this, you need to change the HTTP SPN assigned to SSRS to include a port number. 
setspn -S  HTTP/<SERVERNAME>:<PORT NUMBER> <DOMAIN>\<SERVICEACCOUNT>
setspn -S  HTTP/<SERVERNAME>.<FQDN>:<PORT NUMBER> <DOMAIN>\<SERVICEACCOUNT>

# Delete the generic HTTP SPN's (that don't have a port number) to get remote PowerShell working
setspn -D  HTTP/<SERVERNAME> <DOMAIN>\<SERVICEACCOUNT>
setspn -D  HTTP/<SERVERNAME> <DOMAIN>\<SERVICEACCOUNT>


```

**Comment by msebolt** [comment]
@Teutenberg  Thank you for the feedback, assigning this to the author for review.

**Comment by Teutenberg** [comment]
Here is an updated workaround for connecting to WinRm when SSRS SPN has been set. 

To workaround this, you need to add an HTTP SPN with the WinRM port number, and update your PowerShell code: 

SETSPN:
setspn -S  HTTP/<SERVERNAME>:5985 <SERVERNAME>
setspn -S  HTTP/<SERVERNAME>.BNZNAG.NZ.THENATIONAL.com:5985 <SERVERNAME>

POWERSHELL:
$sessionOptions = New-PSSessionOption -IncludePortInSPN
$session= New-PSSession -Computername $env:COMPUTERNAME -Credential $SqlAdminCredential -SessionOption $sessionOptions

Invoke-Command -Session $session

**Comment by WilliamAntonRohm** [comment]
@maggiesMSFT -- please let me know if there is a preferred author to make this change.

**Comment by WilliamAntonRohm** [comment]
cc @MightyPen for suggested assignee

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, I kinda remember that you are the SSRS writer (it is no longer Maggie).
But if I am wrong about who, then can you and @rothja figure out who the SSRS writer is these days, so that writer can have this Issue #3408 assigned to them.

- `https://docs.microsoft.com/en-us/sql/reporting-services/report-server/register-a-service-principal-name-spn-for-a-report-server?view=sql-server-ver15`

Thanks. G

cc: @WilliamAntonRohm

**Comment by maggiesMSFT** [comment]
Hi, @MightyPen -- nope, other way around. Used to be @markingmyname , now it's me. So you have to assign it to me. Thx
cc @rothja

**Comment by maggiesMSFT** [comment]
Hi, @Teutenberg -- thanks for your detailed request. After conferring with the product team, I've updated the article. Per their advice, I haven't included the PowerShell. The update will be live tomorrow.
Thanks again!
#please-close
