### ISSUE TITLE
Clear-HgsClientHostKey command not working

### ISSUE THREAD

**Issue by arafubeatbox** [MicrosoftDocs/sql-docs#3410]
I am running Windows 10 Enterprise version 10.0.18362,
PowerShell version 5.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f498ebf8-8cda-7e68-c70c-9ecd0e7bd7df
* Version Independent ID: b710fea4-0d4e-5fdd-03e8-ce2679fa18c2
* Content: [Tutorial: Getting Started with Always Encrypted with secure enclaves using SSMS - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@arafubeatbox -- Futai, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around the general task.

**Comment by arafubeatbox** [comment]
Thank you William, for your response. Excuse me for asking such an ambiguous question.

I was setting up my SQL server computer, following the instructions of 
https://docs.microsoft.com/en-us/sql/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves?view=sql-server-ver15

In step 2. part 8, I was not able to attest to the HGS computer, so I ran the "Clear-HgsClientHostKey" command, as told.
It didn't work on neither the HGS computer or the SQL server computer, telling me "is not recognized as the name of a cmdlet, function, script file, or operable program."

**Comment by WilliamAntonRohm** [comment]
Hi @arafubeatbox --

I’m a PM for Always Encrypted in SQL Server. I’m contacting you regarding the issue and your comment you submitted at https://github.com/MicrosoftDocs/sql-docs/issues/3410.

First of all, thank for trying AE with enclaves. Sorry about the issues you have hit. Hopefully, we can unblock you soon.

First of all, we confirmed the correct cmdlet name is Remove-HgsClientHostKey, not Clear-HgsClientHostKey. We will fix it in the doc.

Please, try to run it and retry the steps again. If that does not help, please open System Information (msinfo32.exe) on the machine running SQL Server and check the value of Virtualization-based security - it should say "Running" if you successfully completed Step 2.4. If it is not running, please share the values of other VBS fields from System information.

Thanks,

Jakub (@jaszymas)

**Comment by arafubeatbox** [comment]
Hello @jaszymas --
I am sorry for my late response.
I was able to configure secure enclaves for my SQL Server properly.
Thank you for your sincere support.
