### ISSUE TITLE
Conversion behavior should be documented in more detail

### ISSUE THREAD

**Issue by HeinziAT** [MicrosoftDocs/sql-docs#3411]
For example, the fact that an empty string converted to an int becomes 0 and an empty string converted to a date becomes 1900-01-01, should be documented here in the section "Converting Character Data". If this documentation already exists but is located somewhere else, please add a link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf421288-ba40-3904-72d1-07de1c69e211
* Version Independent ID: f388925a-a573-65ab-e0db-fe61245df123
* Content: [char and varchar (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/data-types/char-and-varchar-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/char-and-varchar-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@HeinziAT -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue 3411.

**Comment by MikeRayMSFT** [comment]
@HeinziAT - thank you for the feedback.

The information about date is included as an example in [CAST and CONVERT (Transact-SQL)](https://docs.microsoft.com/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver15#date-and-time-styles).

I'm reviewing your request to add an explanation of the implicit conversion of empty string (' ') to int return 0.

**Comment by CarlRabeler** [comment]
PR pending that addresses this git issue
