### ISSUE TITLE
If you have an older preview version of SSMS 18.x installed, 

### ISSUE THREAD

**Issue by thedavegray** [MicrosoftDocs/sql-docs#3412]
What does this even mean?  I have v18.2 installed, no ,mention of "preview" or "GA".  Can you not just be specific as using the word older is not ideal. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-gb/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by dnethi** [comment]
Hi Dave

Our telemetry shows some users are still on 18.x Preview version. The note is meant for those users.

thanks,
Dinakar

**Comment by WilliamAntonRohm** [comment]
@thedavegray -- Dave, thank you for your feedback.

@dnethi -- Dinakar, thanks for answering.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by thedavegray** [comment]
Hi
  
Does it say “preview “ in the help/about box?   
  

  
  

  
  
>
