### ISSUE TITLE
"Allow Enclave Computations" option is STILL missing

### ISSUE THREAD

**Issue by MNashDev** [MicrosoftDocs/sql-docs#3414]
We're Hitting a similar issue to https://github.com/MicrosoftDocs/sql-docs/issues/2376

We have followed this Tutorial to enable Secure Enclaves:
https://docs.microsoft.com/en-us/sql/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves?view=sql-server-ver15

We are running on Microsoft SQL Server 2019 (RC1) - 15.0.1900.25 (X64) Developer Edition and are still unable to follow Step 5 due to enclave errors.

We are also seeing 'Internal enclave error: Cannot initialize the VBS enclave. Load method: 敇䕴据慬敶' in the Event Logs.

We've been told thet CTP 3.1 should have been included in 15.0.1900.25 but we're still hitting this issue.

**Comment by WilliamAntonRohm** [comment]
@MNashDev -- Mark, thank you for your feedback.  I have re-opened your original issue https://github.com/MicrosoftDocs/sql-docs/issues/2376.

@jaszymas, @MightyPen -- fyi.

**Comment by MightyPen** [comment]
@VanMSFT Hi Van, Jakob Zymaszek (JasZymas) is the owner of this article, and ideally Jakob will respond to this GitHub Issue, by entering a new Comment that provides an answer to the customer.

You Van are the 'ms.reviewer', and are a documentation writer, so I am co-assigning this Issue #3414 to you, in case work with Jakob is needed.

As Jakob is the 'author', I am also assigning this Issue to Jakob .
Thanks. (GeneMi)

cc: @WilliamAntonRohm

**Comment by MightyPen** [comment]
@jaszymas Hi Jakob, Here in Issue #3414 the customer is saying that Step 5 is not working.  Can you assess whether the documentation is wrong or outdated?  Or might there be a problem in the product?:

---

## Step 5: Provision enclave-enabled keys

In this step, you will create a column master key and a column encryption key that allow enclave computations.

---

- [https://docs.microsoft.com/en-us/sql/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves?view=sql-server-ver15#step-5-provision-enclave-enabled-keys](https://docs.microsoft.com/en-us/sql/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves?view=sql-server-ver15#step-5-provision-enclave-enabled-keys)

VanTo might be able to assist you.

cc: @VanMSFT

**Comment by jaszymas** [comment]
The issue with Chinese characters is scheduled to be fixed in one of the next CU (cumulative update) for SQL Server 2019. Meanwhile, could you please provide a full error message for the SQL error log, including state information.

**Comment by jaszymas** [comment]
The higher-level point here is that if the Allow Enclave Computations options is missing in SSMS, it means the enclave is not properly initialized in SQL Server. 

Could you please confirm you have successfully completed Step 2 of the tutorial: please run Get-HgsClientConfiguration  - the result should show that AttestationStatus = Passed. If it shows the different status, please share the the following fields from the result: AttestationOperationMode, AttestationStatus, AttestationSubstatus.

In addition, please open System Information (msinfo32.exe) on the machine running SQL Server and check the value of Virtualization-based security - it should say "Running" if you successfully completed Step 2.4. Ifit is not running, please the values of other VBS fields from System information.

Thanks.

**Comment by MightyPen** [comment]
@MNashDev Hello Mark, Would you please send us an email today, from your email account, to:

- `VanTo@microsoft.com` , &nbsp; _and_
- `GeneMi@microsoft.com`

We want to understand the details with precision, and to communicate an answer to you with precision.
Thank you!

cc: @jaszymas

**Comment by MNashDev** [comment]
Email sent with the details. 

Summary though is that the Get-HgsClientConfiguration is providing a false, and so it seems our setup may not be set properly.

We are running on Azure, and so it seems we may have missed step 2.4

but we are still looking into this

**Comment by VanMSFT** [comment]
Since this has been taken offline, I'll go ahead and close this GitHub Issue. @MNashDev  - Please feel free to let us know if you have any issues with this. Thanks for your time.
