### ISSUE TITLE
sql not work properly in ubuntu 19.04

### ISSUE THREAD

**Issue by goliverma** [MicrosoftDocs/sql-docs#3417]
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection.
-------------------------------------------------------------------------------------------
how can sol this error

**Comment by WilliamAntonRohm** [comment]
@goliverma -- thank you for your feedback.  To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by goliverma** [comment]
Thank u sir but this problem is not solve
