### ISSUE TITLE
Data Flush Interval (Minutes) (No, wait! Seconds!)

### ISSUE THREAD

**Issue by samrueby** [MicrosoftDocs/sql-docs#3418]
This line is confusing: "Data Flush Interval (Minutes): Defines the frequency in seconds to persist collected runtime statistics to disk". It's states it's in minutes, and then immediately says seconds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155bfbc5-9c63-32c6-9d06-a9b3cdb4c60e
* Version Independent ID: c854b2de-e509-e320-8151-67d690d486ed
* Content: [Best practices with Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/best-practice-with-the-query-store?view=sql-server-ver15#Configure)
* Content Source: [docs/relational-databases/performance/best-practice-with-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/best-practice-with-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @pmasl
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@samrueby -- Sam, thank you for your feedback.  I am looking into this untimely issue.
