### ISSUE TITLE
No diagram in document

### ISSUE THREAD

**Issue by lxnguyen059** [MicrosoftDocs/sql-docs#3421]
The 2nd paragraph of the document says "The following diagram demonstrates the relationship between applications ..."
There is no diagram shown in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca2544b-ea59-50ea-d831-cd4cc1778326
* Version Independent ID: 710c2742-9297-bb9d-d7ec-3a3bd269e8c4
* Content: [Generate and analyze the CLUSTER.LOG for an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/cluster-log-always-on-availability-groups?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/cluster-log-always-on-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/cluster-log-always-on-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@lxnguyen059  Thank you for the feedback.

The documentation has been updated and is pending review.
