### ISSUE TITLE
Little enhancement for the sample query

### ISSUE THREAD

**Issue by RalfSeidel** [MicrosoftDocs/sql-docs#3425]
The query should also take into account that the job execution is requested but execution has not yet startet:

SELECT sj.Name, 
	CASE
		WHEN sja.start_execution_date IS NULL AND sja.run_requested_date is NOT NULL  THEN 'Starting'
		WHEN sja.start_execution_date IS NULL THEN 'Not running'
		WHEN sja.start_execution_date IS NOT NULL AND sja.stop_execution_date IS NULL THEN 'Running'
		WHEN sja.start_execution_date IS NOT NULL AND sja.stop_execution_date IS NOT NULL THEN 'Not running'
	END AS 'RunStatus'
FROM msdb.dbo.sysjobs sj
JOIN msdb.dbo.sysjobactivity sja
ON sj.job_id = sja.job_id
WHERE session_id = (
	SELECT MAX(session_id) FROM msdb.dbo.sysjobactivity); 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42860196-2454-45d2-f2a8-760cf0a0f9cd
* Version Independent ID: 85b49171-3e96-6779-33df-7d0fd7c65919
* Content: [dbo.sysjobactivity (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/dbo-sysjobactivity-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-tables/dbo-sysjobactivity-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/dbo-sysjobactivity-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@RalfSeidel  Thank you for your contribution.

Assigning this to the author for review.

**Comment by msebolt** [comment]
Please also consider using the GitHub to [submit a PR to Micrsoft Docs](https://docs.microsoft.com/contribute/) for further contribution credit.

**Comment by stevestein** [comment]
@RalfSeidel - thanks for the feedback.  The example is to get users started and not intended to cover every scenario.

I haven't tested your query, but if sja.run_requested_date is in the future, would this condition be considered to be starting or would it be waiting to start?  _WHEN sja.start_execution_date IS NULL AND sja.run_requested_date is NOT NULL THEN 'Starting'_  

Thanks for the suggestion!

#please-close
