### ISSUE TITLE
Availability on Azure SQL Database

### ISSUE THREAD

**Issue by jimp100** [MicrosoftDocs/sql-docs#3426]
This function is available on Azure SQL Database despite the grey cross indicating otherwise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3495ddd3-8fb9-b52c-e0dd-fd888b2e2c6b
* Version Independent ID: 7b30dd2f-5299-47b4-3ddd-31a4e9bda788
* Content: [PWDCOMPARE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/pwdcompare-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/pwdcompare-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/pwdcompare-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@jimp100  Thank you for the feedback, assigning this to the author for review.

**Comment by VanMSFT** [comment]
Thanks @jimp100! I confirmed that this function now works in Azure SQL Database. I'll edit the article. We appreciate your help on our documentation.
