### ISSUE TITLE
Different expired/revert reasons have different implications on the future which are not documented

### ISSUE THREAD

**Issue by tussosedan** [MicrosoftDocs/sql-docs#3427]
For example, from our testing, with the "PlanUnforcedByUser" reason the recommendations can still be applied again. However, with the "UserForcedDifferentPlan" reason the recommendations will not be applied anymore.
Please document the full behavior for all the reasons, so we users don't have to guess and be surprised by the results...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24764159-9678-dad1-dfbd-f0563e2146f9
* Version Independent ID: 87a7ac36-8697-6ddd-e9a4-fd8b019e3ecd
* Content: [sys.dm_db_tuning_recommendations (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-tuning-recommendations-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-db-tuning-recommendations-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-db-tuning-recommendations-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by msebolt** [comment]
@tussosedan Thank you for the feedback, we apologize for the confusion.

Assigning this to the author for review.

**Comment by julieMSFT** [comment]
#assign:julieMSFT

**Comment by julieMSFT** [comment]
@tussosedan Hi Alex, I am looking into this with the other issues you submitted for this article.

**Comment by julieMSFT** [comment]
@tussosedan Hi Alex, on further review the reasons were updated to includes information on how the reason affected further applications of the recommendations. I will go ahead and close this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. Thank you for your contribution to Microsoft Docs and we hope to hear from you again.

**Comment by julieMSFT** [comment]
#https://github.com/MicrosoftDocs/sql-docs-pr/pull/14517/files

**Comment by julieMSFT** [comment]
#please-close
