### ISSUE TITLE
TDE in standard edition

### ISSUE THREAD

**Issue by Jagoop** [MicrosoftDocs/sql-docs#3428]
I am aware that this is prerelease information, but I have to ask: Is it on purpose that TDE (transparent data encryption) is listes as a feature that is available on Standard Edition? If so, this would be a rather significant change from previous versions :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48cb4a50-bcd6-38bc-187b-27cc36576219
* Version Independent ID: 38c1d92e-25d6-6237-9a04-6ca13bbb1a09
* Content: [What's new in SQL Server 2019 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-ver15?view=sql-server-ver15)
* Content Source: [docs/sql-server/what-s-new-in-sql-server-ver15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/what-s-new-in-sql-server-ver15.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@Jagoop Thank you for the question.

There hasn't been any official mention of this feature supported as of now, assigning this to the author for review.

**Comment by LarnuUK** [comment]
This has been confirmed @Jagoop in the details release yesterday: https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-version-15?view=sql-server-ver15#RDBMSS

**Comment by PAC77** [comment]
Has there been any official confirmation from Microsoft about this?  TDE in Standard is a BIG DEAL and should be a headlining feature change if true.

**Comment by MikeRayMSFT** [comment]
Thanks for the comment, @Jagoop - TDE is available in SQL Server 2019 Standard Edition.

In addition to the updates in the docs, we announced it in a [blog post](https://techcommunity.microsoft.com/t5/SQL-Server/SQL-Server-2019-Standard-Edition/ba-p/986121)
