### ISSUE TITLE
TDE in standard edition

### ISSUE THREAD

**Issue by Jagoop** [MicrosoftDocs/sql-docs#3429]
I am aware that this is prerelease information, but I have to ask: Is it on purpose that TDE (transparent data encryption) is listes as a feature that is available on Standard Edition? If so, this would be a rather significant change from previous versions :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d663fffb-d444-59c0-714f-433cf91980c4
* Version Independent ID: ee6da2f6-9ab0-792c-8a5d-d3c725779669
* Content: [Editions and supported features of SQL Server 2019 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-version-15?view=sql-server-ver15)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-version-15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-version-15.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
Closing issue, please refer to https://github.com/MicrosoftDocs/sql-docs/issues/3428.
