### ISSUE TITLE
CPU time values documentation is missing units

### ISSUE THREAD

**Issue by tussosedan** [MicrosoftDocs/sql-docs#3430]
I believe it's microseconds, but it should be specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24764159-9678-dad1-dfbd-f0563e2146f9
* Version Independent ID: 87a7ac36-8697-6ddd-e9a4-fd8b019e3ecd
* Content: [sys.dm_db_tuning_recommendations (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-tuning-recommendations-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-db-tuning-recommendations-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-db-tuning-recommendations-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by msebolt** [comment]
@tussosedan Thank you for the feedback, assigning this to the author for review.

**Comment by julieMSFT** [comment]
#assign-julieMSFT

**Comment by julieMSFT** [comment]
@tussosedan Hi Alex, I am looking into this with the other issues you submitted for this article.

**Comment by julieMSFT** [comment]
#https://github.com/MicrosoftDocs/sql-docs-pr/pull/14517/files

**Comment by julieMSFT** [comment]
@tussosedan Hi Alex, on further review the CPU time values were added to the document. I will go ahead and close this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. Thank you for your contribution to Microsoft Docs and we hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
