### ISSUE TITLE
Download links at the beginning

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#3431]
Hi team, 
I moved this from here: 
The contributor is making a suggestion on the disposition of the downlaod links.

**The comment below was machine translated**

@Apocatastasis commented 3 hours ago — with docs.microsoft.com
Put the download links first, not everyone has time to read their release notes and realize they are in the middle.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by dnethi** [comment]
We recently updated the download link from a normal font size to the big, bold, blue header. I think that should suffice. 

thanks,
Dinakar

**Comment by danielearwicker** [comment]
Now it's the same size/font as all the other plain headings, and so looks like a heading as you scroll past trying to find the download button.

**Comment by NishSG** [comment]
Where is the download link. Its been 30 minutes I cant find.. I have a job to do I cant waste time in solving such riddles. worst product page

**Comment by dnethi** [comment]
![image](https://user-images.githubusercontent.com/43253513/68214358-485c2680-ffab-11e9-8d76-1ad0366daaeb.png)

**Comment by gkarldoka** [comment]
Still looks like a headline and different than most other links on this page :(

**Comment by ruibca** [comment]
Arrogance doesn't help. Conventions do. At least in a page that's meant to be practical, not the result of a moment of inspiration of a genius. If it looks like a duck, swims like a duck... It doesn't matter how big or what colour it is: https://www.youtube.com/watch?v=vJG698U2Mvo. Basically it is not obvious at all where the download link is and it should be (main purpose of the page?).  It looks like a title and that's what I and apparently quite a few more people assumed. So it would be great if it could be fixed. Thank you.
