### ISSUE TITLE
Variables cannot be used in views

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/sql-docs#3433]
It would be useful to mention in the documentation that variables cannot be used in views.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1857c225-3fdd-7316-44e9-77b27a9f1e18
* Version Independent ID: f922610c-2b7e-8b65-0883-e01fa2dd0982
* Content: [Variables (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/variables-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/language-elements/variables-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/variables-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@HairyDrumroll Thank you for the feedback, assigning this to the author for review.

**Comment by rothja** [comment]
@HairyDrumroll Thanks for the suggestion. Can you give me a simple example of what you might try to do with variables in a view that would not work? That might help me to document the limitation you're referring to more clearly. Thank you!

**Comment by HairyDrumroll** [comment]
Something along the lines of:
```
CREATE VIEW view_MyView AS
DECLARE @myvar char(1);
SET @myvar = 'A';
SELECT fields FROM table WHERE field1=@myvar
```
won't work.

Basically, I want some mechanism to just type in the value for a variable at the top of the query, then reuse that several times through the query later, and save that as a view so I can come back to it.

I now know I can get this functionality with User Defined Functions instead of views (`CREATE FUNCTION myfunc (@var) RETURNS TABLE AS etc...`), or a hack with Common Table Expressions (putting `WITH myvars AS (SELECT myvar='A')` at the top then joining it in to the query and saving that as a view), but I think the fact that variables can't be used _in views_ should be highlighted in the documentation.

**Comment by rothja** [comment]
@HairyDrumroll Thanks for providing the example, and I see what you mean. Let me look at the best way of adding this limitation. Once I make the change I'll close out this git issue. Thank you!
