### ISSUE TITLE
SqlPackage 2014 arguments mistakes

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#3443]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/sql-docs.ru-ru/issues/63

@VerdonTrigance commented 9 hours ago — with docs.microsoft.com
c:\Program Files (x86)\Microsoft SQL Server\120\DAC\bin&gt;SqlPackage.exe /a:Publish /TargetServerName:dev /TargetDatabaseName:CDB /SourceFile:".\DB.dacpac" /DeployReportPath:".\report.xml" /DiagnosticsFile:".\di.txt"
leads to
*** Unrecognized command line argument 'DeployReportPath'.
*** Unrecognized command line argument 'DiagnosticsFile'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage.exe - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-ver15&viewFallbackFrom=sql-server-2014#feedback)
* Content Source: [docs/tools/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage.md)
* Product: **sql**
* Technology: **ssdt**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by msebolt** [comment]
Assigning this to the author for review.

**Comment by pensivebrian** [comment]
We do not have a 2014 version of the page for sqlpackage, only the latest 2019 version, where these arguments are supported. There should be a message when changing the SQL version on the page that you are redirected to the latest version.

**Comment by VerdonTrigance** [comment]
FYI
I was reading page with selected version 2014. That’s why I created this ticket.

**Comment by markingmyname** [comment]
Thank you, @VerdonTrigance, for bringing this to our attention.  We are currently discussing how to present the different versions of SQL in a more streamlined manner. To avoid exact instances such as the confusion of what version you are currently viewing to see a feature.

@pensivebrian, Thank you for your reply.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by umeshgauda** [comment]
is this solved?
