### ISSUE TITLE
Suggestion: Indicate when T-SQL language features and functions are part of the ISO standard

### ISSUE THREAD

**Issue by Jehoel** [MicrosoftDocs/sql-docs#3454]
The "Applies to" section is useful - but it only indicates if a language feature or built-in function is supported by current SQL Server functionality. I'm _not_ proposing that Microsoft start listing whether or not certain functionality is also present in MySQL, PostgreSQL or Oracle - but when a feature is supported by SQL Server because it's part of the ISO SQL spec then I think that should be made clear. As well as maybe mentioning an ISO-compliant alternative where [SQL Server is non-conformant](https://modern-sql.com/feature/is-distinct-from) (e.g. "Use `( ( a = b ) OR ( a IS NULL AND b IS NULL ) )` instead of `a IS NOT DISTINCT FROM b`"). [1]

Microsoft does have ISO standard conformance declaration documents, but they're PDFs: https://docs.microsoft.com/en-us/openspecs/sql_standards/ms-sqlstandlp/89fb00b1-4b9e-4296-92ce-a2b3f7ca01d2 - but those pages haven't been updated since SQL Server 2012.

[1]: Of course I'd prefer it if SQL Server supported MariaDB/MySQL's far more terse `<=>` operator! (and `<!=>` for `IS DISTINCT FROM`?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f748e679-fde4-3cc7-4200-7b45adb74a21
* Version Independent ID: 6946f36e-4731-1ed9-365a-0085103a630e
* Content: [CONCAT_WS (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/concat-ws-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/concat-ws-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/concat-ws-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@Jehoel -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue 3454.

**Comment by MikeRayMSFT** [comment]
@Jehoel 
Thanks for the feedback.

I'll make sure our team evaluates how to incorporate ISO documentation in our T-SQL reference docs. 

WRT features for SQL Server, please submit those via [feedback](https://aka.ms/sqlfeedback).
