### ISSUE TITLE
Incorrect discription of code sample

### ISSUE THREAD

**Issue by chris904apps** [MicrosoftDocs/sql-docs#3455]
Description of sample code states "A correlated subquery can also be used in the HAVING clause of an outer query. This example finds the product models for which the maximum list price is more than twice the average for the model."

However, this code does not return results  that have MAX ListPrice that are 'twice' the amount of their AVG list price; just results that are equal to or greater then the AVG. In order to be twice as much you would need to multiple AVG by 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b8c2959-4a3c-bf2e-4504-c84cb30660b7
* Version Independent ID: c1e9b6b5-d398-ebd1-b447-ede189bd6c15
* Content: [SELECT Examples (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-examples-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/queries/select-examples-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/select-examples-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@chris904apps -- Christopher, thank you for your feedback.  I am looking into updating the documentation.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- please review the change in the above-mentioned PR 12788.
