### ISSUE TITLE
Sql Server Version info was removed

### ISSUE THREAD

**Issue by Rafujin** [MicrosoftDocs/sql-docs#3456]
Why was the version info removed?
Nowhere else on the docs page can i find in which sql server version the feature was introduced.
This was really helpful information that is now missing. (or maybe i just looked over it?)

Commit that removed this info: https://github.com/MicrosoftDocs/sql-docs/commit/479e2dc54b699e0ed29dccdb3d347a7d0861258a

Thanks,
Rafujin

**Comment by WilliamAntonRohm** [comment]
@Rafujin -- thank you for your feedback.

@MightyPen -- please assist with this issue 3456.

**Comment by MightyPen** [comment]
The removal of version info was necessary to end the contradictions and incorrect claims that sooner or later creep into our documentation webpages for SQL Server.
At the top-left sector of Docs webpages like.....

- `https://docs.microsoft.com/en-us/sql/sql-server/sql-docs-navigation-guide?view=sql-server-ver15`
  - _(Article happens to include a discussion of the Versioning drop-down.)_

.....there is a Versioning drop-down box, slightly above the TOC search textbox. A person can set the versioning drop-down to whatever Product + Version they care about, and then know that the content on the Docs page is accurate for that version.

The person could never know whether the old "2008 R2" version claim was true for all content on the webpage.
Some enhancements to the Versioning drop-down list went live on Docs just a few weeks ago. There are further improvements being considered for the Versioning drop-down list, but no specifics on any near-term horizon.

---

I am now Closing this Issue #3456 as Answered/Fixed.
Thank you for submitting this Issue. We hope to hear from you again.

 . .

**Comment by Rafujin** [comment]
Thank you for the explanation.

The issue i have with the versioning drop down is that for most older versions i get the following message:
"The requested page is not available for SQL Server previous versions. You have been redirected to the newest product version this page is available for."

I get this message for example when i try to select older versions for the ISNULL command: https://docs.microsoft.com/en-us/sql/t-sql/functions/isnull-transact-sql?view=sql-server-ver15

The reason why this info was helpfull was so i could check if could use the command in a script that needed to be compatible with sql server 2008. I have a sql server 2019 installed locally while some of our clients still use a 2008, so intellisense doesnt tell me if im using a command that's not compatible.

Thanks again for the response and i look forward to the further improvements.

Greetings,
Rafujin
