### ISSUE TITLE
Downloaded SSMS 18.4 but once downloaded the setup file says 18.3.1

### ISSUE THREAD

**Issue by micsel** [MicrosoftDocs/sql-docs#3458]
I have downloaded and after all installation, I noticed the version is still 18.3.1 but the download link is for 18.4. Please kindly let us know.

![SSMS 18 4](https://user-images.githubusercontent.com/9040560/68129125-f1a20e80-ff10-11e9-9260-179d2ebc2587.png)

**Comment by WilliamAntonRohm** [comment]
@micsel -- thank you for your feedback.  To make sure we have all the information needed to address your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
@micsel -- Michael, we are looking into this SSMS issue.

**Comment by WilliamAntonRohm** [comment]
@micsel -- Michael, thank you for your feedback.

@markingmyname -- Mark, please look into this issue 3458.

**Comment by markingmyname** [comment]
@micsel,

We apologize for the inconvenience.

The link was updated after this was submitted.

I tried it myself, and it does show 18.4 now.

Thank you for your patience.

**Comment by micsel** [comment]
Ok excellent. Thank you so much guys.
