### ISSUE TITLE
The top link is still pointing to 18.3.1

### ISSUE THREAD

**Issue by Jagoop** [MicrosoftDocs/sql-docs#3459]
The top download link is still pointing to 18.3.1, the lower link (with the different language versions) appear to be okay though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by WilliamAntonRohm** [comment]
@Jagoop -- Jakob, thank you for your feedback.

@markingmyname -- Mark, please look into this issue 3459.

**Comment by markingmyname** [comment]
@Jagoop 

We apologize for the inconvenience.

The link was updated about a couple of hours after this was submitted.

I tried it myself, and it does show 18.4 now.

Thank you for your patience.
