### ISSUE TITLE
Alexander Sinitsyn

### ISSUE THREAD

**Issue by Al-ex-and-er** [MicrosoftDocs/sql-docs#3460]
Return type should be NVARCHAR(128), I guess. 

At least it is what I see when do 
select SYSTEM_USER as n into #tmp
and check the type of 'n'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b25f866-3dc7-7a19-163e-1ca4c1cf3118
* Version Independent ID: e946a621-3bad-6f0b-711f-d43882fcfce9
* Content: [SYSTEM_USER (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/system-user-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/system-user-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/system-user-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@Al-ex-and-er Thank you for the feedback.

You are correct, however using a modified version of your query:

```
select SYSTEM_USER as n into #tmp

SELECT   SQL_VARIANT_PROPERTY(n,'BaseType') AS 'Base Type',  
         SQL_VARIANT_PROPERTY(n,'MaxLength') AS 'MaxLength' 
FROM      #tmp
```

...it appears to be NVARCHAR(256), similar to [USER_NAME](https://docs.microsoft.com/sql/t-sql/functions/user-name-transact-sql?view=sql-server-ver15).

The documentation has been updated and is pending review.

**Comment by Al-ex-and-er** [comment]
Hi Matthew,

I would check that SQL_VARIANT_PROPERTY(MaxLength) returns length in
characters. I think it is in bytes, so 256 bytes for NVARCHAR corresponds
to 128 characters.  I'll double-check tomorrow, and USER_NAME too.

Thank you,
Alexander

**Comment by Al-ex-and-er** [comment]
OK, I checked all relevant functions and they all return NVARCHAR(128)

```
SELECT 
  [SUSER_NAME] = SUSER_NAME(),
  [SUSER_SNAME] = SUSER_SNAME(),
  [SYSTEM_USER] = SYSTEM_USER,
  [USER] = USER,
  [USER_NAME] = USER_NAME()
INTO #tmp

SELECT v.*
FROM #tmp t
 cross apply
 ( values
  ('SUSER_NAME',  SQL_VARIANT_PROPERTY([SUSER_NAME] , 'BaseType'), SQL_VARIANT_PROPERTY([SUSER_NAME] , 'MaxLength') ),
  ('SUSER_SNAME', SQL_VARIANT_PROPERTY([SUSER_SNAME], 'BaseType'), SQL_VARIANT_PROPERTY([SUSER_SNAME], 'MaxLength') ),
  ('SYSTEM_USER', SQL_VARIANT_PROPERTY([SYSTEM_USER], 'BaseType'), SQL_VARIANT_PROPERTY([SYSTEM_USER], 'MaxLength') ),
  ('USER',        SQL_VARIANT_PROPERTY([USER]       , 'BaseType'), SQL_VARIANT_PROPERTY([USER]       , 'MaxLength') ),
  ('USER_NAME',   SQL_VARIANT_PROPERTY([USER_NAME]  , 'BaseType'), SQL_VARIANT_PROPERTY([USER_NAME]  , 'MaxLength') )
 ) v(func, BaseType, MaxLength)

```
func|BaseType|MaxLength
-----|----------|------------
SUSER_NAME|nvarchar|256
SUSER_SNAME|nvarchar|256
SYSTEM_USER|nvarchar|256
USER|nvarchar|256
USER_NAME|nvarchar|256

SUSER_NAME and SUSER_SNAME have correct type specified in docs. SYSTEM_USER, USER and USER_NAME are not correct.

**Comment by msebolt** [comment]
You're correct and thank you for noting the additional items.

The documentation has been updated with changes pending review.
