### ISSUE TITLE
18.4 download link points to 18.3.1

### ISSUE THREAD

**Issue by vf021** [MicrosoftDocs/sql-docs#3461]
I clicked the elink and got 18.3.1 downloaded

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@vf021 -- Vadim, thank you for your feedback.

@markingmyname -- Mark, please look into this issue 3461.

**Comment by markingmyname** [comment]
@vf021,

We apologize for the inconvenience.

The link was updated after this was submitted.

I tried it myself, and it does show 18.4 now.

Thank you for your patience.
