### ISSUE TITLE
Table designer, no intellisense on dataType

### ISSUE THREAD

**Issue by nwoodin** [MicrosoftDocs/sql-docs#3462]
When creating a new table using the graphical designer, I used to be able to be able to type letters and it would select the datatype that matches the closest (effectively dropping me down to the listItem).  Additionally, after I name a column and I press the tab key to get to the dataType column, an audio alert is triggered as if the tab key created some error.

This behavior started happening in 18.3.1, I have rolled back to 18.2 to get the desired behavior.

**Comment by WilliamAntonRohm** [comment]
@nwoodin -- Nick, thank you for your feedback.

@markingmyname -- Mark, please look into this issue 3462.

**Comment by markingmyname** [comment]
@nwoodin,

Thanks for your comment.

Your contribution is much appreciated. 

However, our team can only answer feedback related to the documentation. Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page or visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) page. If you have any feedback related to the documentation, please feel free to log in through this channel. We truly appreciate your contribution to our articles.

Hope this helps.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
