### ISSUE TITLE
azdata msi download hyperlink

### ISSUE THREAD

**Issue by hfleitas** [MicrosoftDocs/sql-docs#3463]
broken: [Download the azdata Windows Installer] (httpss://aka.ms/azdata-msi)
fix: [Download the azdata Windows Installer](https://aka.ms/azdata-msi)

thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48f1663f-55cf-ce99-8cfc-9249aa0c6d79
* Version Independent ID: 32838cba-366f-5a89-50fd-f56a8978c094
* Content: [Install azdata with Windows Installer - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-azdata-installer?view=sql-server-ver15#feedback)
* Content Source: [docs/big-data-cluster/deploy-install-azdata-installer.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-install-azdata-installer.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@hfleitas -- Hiram, thank you for your feedback.  I am looking into the documentation.

**Comment by swells** [comment]
[This has now been fixed](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-azdata-installer?view=sql-server-ver15#install-azdata-with-the-microsoft-windows-installer) with the latest doc update.

**Comment by MikeRayMSFT** [comment]
@hfeiltas - thank you for raising this issue. 

M
