### ISSUE TITLE
ROUND() behaves differently for different numeric types

### ISSUE THREAD

**Issue by baizini** [MicrosoftDocs/sql-docs#3471]
On Azure SQL Database or SQL Server, the following expressions give different results:

SELECT ROUND (CONVERT(money,1.525),2);

SELECT ROUND (CONVERT(float,1.525),2);

The first expression gives 1.53, whereas the second gives 1.52

The documentation is not clear about how a terminal 5 is rounded, up or down.  It seems that for money it is rounded up whereas for float it is rounded down.

This behaviour needs to be flagged and clarified in the documentation.

**Comment by msebolt** [comment]
@baizini Thank you for the feedback and noting this discrepancy.

Assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
@baizini - thank you for the submission. Reviewing with engineering.

**Comment by setemsft** [comment]
The [float] type in SQL Server is an 8-byte IEEE 754 double, which is inherently imprecise. The value of 1.525 is really 1.5249999999... - which makes the rounding of it to 2 decimal point produce 1.52. 

The [money] type, on the other hand, is a 64-bit integer in SQL Server, having 1.525 represented as 152500. This is a precise value, which is rounded to 1.53.
