### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by Dinhhai94** [MicrosoftDocs/sql-docs#3476]
Phải chăng.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f789883-5a24-a045-21d5-4b95951cb798
* Version Independent ID: fadbef40-b033-7e4f-533a-abd7a8e303db
* Content: [Deployment guidance - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-guidance?view=sql-server-ver15#endpoints)
* Content Source: [docs/big-data-cluster/deployment-guidance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deployment-guidance.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@Dinhhai94   Thank you for the feedback.

If you have any questions or need changes to the documentation please comment below.
