### ISSUE TITLE
DBH_SQL

### ISSUE THREAD

**Issue by Dinhhai94** [MicrosoftDocs/sql-docs#3477]
Các lệnh cuối toàn cầu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e08034dd-d4b3-2a75-a323-b021faecca2c
* Version Independent ID: 1e9a2b10-caf9-1caa-60c7-2c746f71382f
* Content: [azdata reference - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/reference-azdata.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/reference-azdata.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@Dinhhai94   Thank you for the feedback.

If you have any questions or need changes to the documentation please comment below.
