### ISSUE TITLE
Missing Documentation on what each permission gives access

### ISSUE THREAD

**Issue by KevinConanMSFT** [MicrosoftDocs/sql-docs#3478]
We are missing easy to find documentation on what access the user will gain for each server permission granted on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83e5f29-dca4-dde6-4abc-ba38715477d0
* Version Independent ID: 0e0a550e-f7e7-49a0-adca-417e5f5720e2
* Content: [GRANT Server Permissions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-server-permissions-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/grant-server-permissions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/grant-server-permissions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@KevinConanMSFT -- thank you for your feedback.

@VanMSFT -- please look into this issue 3478,

**Comment by VanMSFT** [comment]
@KevinConanMSFT - Thanks for the feedback, Kevin! We have no plans to update this doc at this time. We appreciate your feedback, and if you feel contributing further, we'd love help updating our documentation: https://review.docs.microsoft.com/en-us/help/contribute/sql-docs-pr-get-started?branch=master

**Comment by KevinConanMSFT** [comment]
My customer is going to ask, why are we not publishing documentation on what each permission gives access to?  This is critical information for compliance.

Thank you,

Kevin Conan
PFE – Data & AI

[Description: MSFT_logo]
