### ISSUE TITLE
When XACT_ABORT is ON the DBMS may cause errors on the query to system tables.

### ISSUE THREAD

**Issue by sancoder** [MicrosoftDocs/sql-docs#3483]
Noticed a bug on MSSQL 14.0.1000.169
After altering database with 
    ALTER DATABASE s2 COLLATE Latin1_General_CI_AS
The following query ends with 'severe error'

select
  a.name obj,
  b.name col,
  c.name typ,
  case when b.prec is not null then b.prec else 0 end siz,
  b.isnullable nul
from
  sysobjects a
  inner join syscolumns b
  on a.id = b.id and a.xtype = 'U'
  inner join systypes c
  on c.name in ('nchar', 'nvarchar', 'char', 'varchar')
    and b.collationid is not null
    and b.xtype = c.xusertype
where a.name NOT IN (
  select a.name obj
  from sysobjects a
  inner join syscolumns b on a.id = b.id and a.xtype = 'U'
  inner join systypes c on c.name in ('ntext', 'text') and b.collationid is not null and b.xtype = c.xusertype
)
order by obj, col

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9fdd49-3145-7ae3-bf90-47f002895264
* Version Independent ID: 075116a4-7a22-3816-9782-079952bc0fe7
* Content: [SET XACT_ABORT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-xact-abort-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/set-xact-abort-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-xact-abort-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@sancoder -- thank you for finding this anomaly.  Please report it at [SQL Server Feedback](https://aka.ms/sqlfeedback).

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
