### ISSUE TITLE
Version Requirements

### ISSUE THREAD

**Issue by SauerKraut51** [MicrosoftDocs/sql-docs#3484]
It would be helpful what the minimum version of Windows a given version of SSMS needs. Could be my mind is going as fast as my eyesight but I'm not seeing it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@SauerKraut51 -- thank you for your feedback.

@markingmyname -- please look into this issue 3484.

**Comment by markingmyname** [comment]
I apologize for the delayed response.

Hope this helps.

https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15#supported-operating-systems-ssms-184.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by happyphunn** [comment]
I think what's missing here is the there's no system requirements listed for any previous version on ssms, only the current release. For example, I'd like to know the highest version of SSMS that's allowed to be installed on Windows 7. Windows 7 is not listed for the current release although I've got an older version installed on a windows 7 box that's prompting me to 'upgrade' and the version it's showing is the current release. Hence the confusion.
