### ISSUE TITLE
Connection String for Another Computer

### ISSUE THREAD

**Issue by jvorata96** [MicrosoftDocs/sql-docs#3488]
Hi. I currently connect to my Microsoft SQL Server on the local computer that runs the server with a connection string as follows:
(SQLCHAR*)(DSN=JoelDB;UID=myID2;PWD=myPW2;WSID=JE-ACCOUNTS;DATABASE=myDB;)

I'm trying to connect to the server from ANOTHER computer and I already did the instructions above. I can telnet to the IP and port of the server using the other computer. However, I can't access it using that connection string. Can you give any insight on how I can do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24e49fc4-1101-0d6f-e16a-52242616287b
* Version Independent ID: df5e0042-2137-3309-a957-de5f556f5c84
* Content: [Lesson 2: Connecting from Another Computer - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/lesson-2-connecting-from-another-computer?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/lesson-2-connecting-from-another-computer.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/lesson-2-connecting-from-another-computer.md)
* Product: **sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@jvorata96  Thank you for the feedback.

What are the setup details you are trying to connect with?

The tutorial referenced is using a SSMS client with the `tcp:<computer_name>,49172` connection format.

**Comment by MashaMSFT** [comment]
Hi @jvorata96 ,Thanks for contacting Microsoft!  From my understanding, the issue you're describing seems to be an issue with the product, is that correct? If so, unfortunately, this form of contact is intended explicitly for reporting issues with the documentation, and not for the product. To get further assistance with your issue, we'd recommend engaging the community, or opening a ticket with Microsoft Support. More information can be found here: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

The connection string you're using is a DSN, which means you're using an ODBC connection. There are a multitude of reasons why your connection might be failing, and they would need to be explored within the scope of a support engagement so those reasons can be investigated. 

Our apologies that the SQL Docs team was unable to assist you further with your issue, but we appreciate you reaching out. Please let us know if there's anything more we can do for you.

Thanks again and hope you have a wonderful rest of your day!
Masha from SQL Docs team
