### ISSUE TITLE
Update Extract and Export to note that /p:TableData can be specified multiple times

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/sql-docs#3506]
A simple "This option may be specified multiple times" as a suffix to each paragraph would suffice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage.exe - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-2017#import-parameters-and-properties)
* Content Source: [docs/tools/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage.md)
* Product: **sql**
* Technology: **ssdt**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by msebolt** [comment]
@IanKemp  Thank you for the feedback, assigning this to the author for review.

**Comment by markingmyname** [comment]
@msebolt,

@pensivebrian is out due to paternity leave.

Please assign all further Issues to @hannahqin in the meantime, please.

**Comment by markingmyname** [comment]
@IanKemp 

So I understand clearly, are you suggesting we add "This option may be specified multiple times"  to the end of each paragraph the reference is made it can work with another specific feature witihn the description?

Good eye, @[Github user]! We’ve forwarded it to the writer, who should respond soon. Thanks!

Also, did you know: You can edit the doc! Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click the Propose file change. 
And voila! It's sent directly to the writer.

Then all the writer has to do is sign off and it goes into the publishing queue.

Thanks again!

**Comment by CarlRabeler** [comment]
@IanKemp good call. Change made - thanks.
Carl
