### ISSUE TITLE
Page placement in contents structure is wrong

### ISSUE THREAD

**Issue by rikgarner** [MicrosoftDocs/sql-docs#3507]
This page and its 4 siblings all deal with memory-optimized *temporal tables*, so it looks like they should be below the Temporal Tables topic; their location in the contents structure (Database Design -&gt; Tables -&gt; Memory-optimized Tables ) suggests this page should be about Memory Optimized Tables more generally - but all the pages about MemOp tables are several nodes away at Manage Monitor and Tune -&gt; Tune -&gt; In Memory OLTP; seems like there should be *at least* an overview of MemOp tables in the Tables topic and these more specific pages moved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03cf2bdc-2759-b827-afd5-24adf5542e40
* Version Independent ID: 40aaf36a-b501-6f50-ff87-84a355ae8b71
* Content: [System-Versioned Temporal Tables with Memory-Optimized Tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/system-versioned-temporal-tables-with-memory-optimized-tables?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/tables/system-versioned-temporal-tables-with-memory-optimized-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/system-versioned-temporal-tables-with-memory-optimized-tables.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@rikgarner I am busy at SQL PASS this week. I will review and address this issue as soon as I can. Thanks for bringing this to my attention.
Carl

**Comment by CarlRabeler** [comment]
agreed - PR pending now

**Comment by CarlRabeler** [comment]
https://github.com/MicrosoftDocs/sql-docs-pr/pull/12909

#please-close
