### ISSUE TITLE
Permissions on files in customized MSSQL 2019 containers

### ISSUE THREAD

**Issue by astellingwerf** [MicrosoftDocs/sql-docs#3508]
I personally feel that the page is unclear on permissions since the MSSQL 2019 rollout. The container since then runs as a non-root user. I've struggled for quite some time, because I was getting an error message while recovering databases from file:

```
2019-11-07 17:02:01.79 spid51      [5]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2019-11-07 17:02:01.79 spid51      Starting up database 'Northwind'.
2019-11-07 17:02:01.86 spid51      Parallel redo is started for database 'Northwind' with worker pool size [1].
2019-11-07 17:02:01.88 spid51      Parallel redo is shutdown for database 'Northwind' with worker pool size [1].
2019-11-07 17:02:01.88 spid51      Error: 3415, Severity: 16, State: 2.
2019-11-07 17:02:01.88 spid51      Database 'Northwind' cannot be upgraded because it is read-only, has read-only files or the user does not have permissions to modify some of the files. Make the database or files writeable, and rerun recovery.
Msg 3415, Level 16, State 2, Server b5a756451795, Line 1
Database 'Northwind' cannot be upgraded because it is read-only, has read-only files or the user does not have permissions to modify some of the files. Make the database or files writeable, and rerun recovery.
```

It turns out that the fix is to figure out the uid of the `mssql` user (`10001`). Once you know that, you can change your command in the Dockerfile:

```
FROM mcr.microsoft.com/mssql/server:2017-latest-ubuntu
#This used to be sufficient in MSSQL 2017
COPY db-files/ /tmp/
...
```

```
FROM mcr.microsoft.com/mssql/server:2019-latest
#Since 2019 you need to specify the owner
COPY --chown=10001 db-files/ /tmp/
...
```

It'd be good if such requirements could be mentioned/explained a bit more explicit. Also, can I be sure that the user id is and remains 10001?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dc2ec36-4915-f7ab-3104-282acc9321e6
* Version Independent ID: fc98af17-f3c5-adff-69ca-593f985e7882
* Content: [Configuration options for SQL Server on Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-2017#storagepermissions)
* Content Source: [docs/linux/sql-server-linux-configure-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by msebolt** [comment]
@astellingwerf  Thank you for the feedback, assigning this to the author for review.

**Comment by CarlRabeler** [comment]
@VanMSFT for awareness

**Comment by VanMSFT** [comment]
Following up with Vin

**Comment by VanMSFT** [comment]
Following up

**Comment by VanMSFT** [comment]
Hi @astellingwerf! I apologize for the delay. I refactored this article into several articles, and we now have a security section that explains SQL Server 2019 container images will have the non-root user start up by default. Hopefully this will help. We really appreciate your patience. I will go ahead and close this out since this article will be refreshed next week, but please feel free to let us know if you have any concerns.
