### ISSUE TITLE
Environment variables for AD authentication

### ISSUE THREAD

**Issue by chrisadkin** [MicrosoftDocs/sql-docs#3509]
Is the following incorrect ?

export DOMAIN_SERVICE_ACCOUNT_USERNAME=&lt;AD principal account name&gt;
export DOMAIN_SERVICE_ACCOUNT_USERNAME=&lt;AD principal password&gt;

should the second environment variable read DOMAIN_SERVICE_ACCOUNT_PASSWORD ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6733c468-62a5-41d9-2c5a-5ca57ee5fdf3
* Version Independent ID: dd529f6a-f02d-0dc4-dd4f-52321e90bed0
* Content: [Deploy SQL Server Big Data Cluster in Active Directory mode - Deploy SQL Server Big Data Cluster in Active Directory mode](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-active-directory?view=sql-server-ver15#feedback)
* Content Source: [docs/big-data-cluster/deploy-active-directory.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-active-directory.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @NelGson
* Microsoft Alias: **negust**

**Comment by msebolt** [comment]
@chrisadkin Thank you for the feedback.

The documentation has been updated and is pending review.
