### ISSUE TITLE
Schema definition incorrect and causes sample streaming application to fail

### ISSUE THREAD

**Issue by dgshaver** [MicrosoftDocs/sql-docs#3510]
The schema definition specified in the first notebook code cell is incorrect.  The Spark types need to be changed from IntegerType to LongType.  Otherwise, the streaming application failed.

Here's the corrected schema definition (replaces lines 12 and 13
StructField("wcs_click_date_sk",LongType,true), StructField("wcs_click_time_sk",LongType,true), StructField("wcs_sales_sk",LongType,true), StructField("wcs_item_sk",LongType,true), 
StructField("wcs_web_page_sk",LongType,true), StructField("wcs_user_sk",LongType,true)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c639fd7-43ee-f24d-ce5e-530077367aab
* Version Independent ID: 28059c60-abe8-e4f8-08c5-221c926f007e
* Content: [Ingest data with Spark jobs - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-spark?view=sqlallproducts-allversions)
* Content Source: [docs/big-data-cluster/tutorial-data-pool-ingest-spark.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/tutorial-data-pool-ingest-spark.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@dgshaver  Thank you for the feedback, assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
Opening pull request to resolve.
