### ISSUE TITLE
Polybase Now Supports Pass Through Authentication to ADLS

### ISSUE THREAD

**Issue by amattas** [MicrosoftDocs/sql-docs#3511]
Polybase now supports pass through authentication to ADLS, however, that is not documented on this page which only refers to using storage keys. The required identity configuration for passthrough authentication is only found on the Service Endpoint page: https://docs.microsoft.com/en-us/azure/sql-database/sql-database-vnet-service-endpoint-rule-overview?toc=/azure/sql-data-warehouse/toc.json#impact-of-using-vnet-service-endpoints-with-azure-storage

**Comment by msebolt** [comment]
@amattas Thank you for the feedback, assigning this to the author for review.

Referencing [Polybase](https://docs.microsoft.com/sql/relational-databases/polybase/polybase-guide).

**Comment by MikeRayMSFT** [comment]
Created DevOps (1646374) item to track. Closing this issue.
