### ISSUE TITLE
2 other properties are not restored when attaching or restoring databases

### ISSUE THREAD

**Issue by parlevjo2** [MicrosoftDocs/sql-docs#3512]
Please add to those 2 properties
"is_trustworthy_on": By default, restored or attached databases have Trustworthy not marked. The exception to this is database mirroring where the broker is enabled after failover.
"is_honor_broker_priority_on": By default, restored or attached databases have Honor Broker Priority off. 

The exception to this is database mirroring where the broker is enabled after failover.
I am not sure if "The exception to this is database mirroring where the broker is enabled after failover." is true.
Those 2 like "is_broker_enabled": By default, restored or attached databases have the broker disabled. The exception to this is database mirroring where the broker is enabled after failover.

See for example: https://blogs.technet.microsoft.com/configurationmgr/2013/04/02/how-to-move-the-configmgr-2012-site-database-to-a-new-sql-server/

3 properties are not restored when detaching/attaching an "sccm configuration management" databases

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d95ec6f-3b85-8d5b-2111-8c10f11dcc1a
* Version Independent ID: 15bd8fa1-dd1b-80ff-c244-4b3dfa3b7049
* Content: [sys.databases (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-databases-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-catalog-views/sys-databases-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-databases-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@parlevjo2  Thank you for the feedback, assigning this to the author for review.

**Comment by rothja** [comment]
@parlevjo2 Thanks for the question, and I apologize for the delay. @stevestein is out of the office this month. @CarlRabeler could you please take a look at this and see if we need to add these properties to the docs? Thank you! #reassign:CarlRabeler

**Comment by CarlRabeler** [comment]
see https://github.com/MicrosoftDocs/sql-docs-pr/pull/12910

**Comment by parlevjo2** [comment]
@CarlRabeler That link does not work. Gives 404 error

**Comment by CarlRabeler** [comment]
sorry - internal link - updated doc should be live in a few hours

**Comment by CarlRabeler** [comment]
#please-close

**Comment by parlevjo2** [comment]
Thanks for the update. But now 3 properties have exact the same text: "By default, restored or attached databases have the broker disabled. The exception to this is database mirroring where the broker is enabled after failover." 
That is not right.

For those 2 properties the text should be something like this:
"is_trustworthy_on": By default, restored or attached databases have Trustworthy not enabled. _Maybe more text._
"is_honor_broker_priority_on": By default, restored or attached databases have Honor Broker Priority not enabled. _Maybe more text._

**Comment by CarlRabeler** [comment]
addressing now - thanks
