### ISSUE TITLE
JSON_VALUE no es un nombre de función integrada reconocido.

### ISSUE THREAD

**Issue by jaimeres** [MicrosoftDocs/sql-docs#3513]
Aparece este error al ejecutar la función, mi versión es SQL Server 2014
JSON_VALUE no es un nombre de función integrada reconocido.

**Comment by msebolt** [comment]
```
This error appears when executing the function, my version is SQL Server 2014
JSON_VALUE is not a recognized integrated function name.
```

@jaimeres  Thank you for the feedback.

Unfortunately `JSON_VALUE` is only supported in versions 2016 and above.

Please see [SQL Server downloads](https://www.microsoft.com/sql-server/sql-server-downloads) for access to more recent versions.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are still issues.
