### ISSUE TITLE
Supported Windows 10 Installations?

### ISSUE THREAD

**Issue by drchilds** [MicrosoftDocs/sql-docs#3514]
Is Windows 10 Pro/EE deliberately unsupported for even Express and Developer Editions, or is this an oversight?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09beb1a-92a9-4335-511c-395ba64c875b
* Version Independent ID: 8f43fca3-43d7-a2e4-1469-bf17f14d9ac8
* Content: [Hardware and software requirements for installing SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15?view=sql-server-ver15)
* Content Source: [docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@drchilds Thank you for the feedback.

`Windows 10 TH1 1507 or greater` is stated as a [hardware requirement](https://docs.microsoft.com/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15?view=sql-server-ver15#hwswr) so this is likely an oversight.

Assigning this to the author for review.

**Comment by MashaMSFT** [comment]
Hi @drchilds, thanks for contacting Microsoft! I have submitted a change to update the documentation that should be live later this week. I will close out this Git Issue in the meantime but please feel free to comment should you need anything further from us :)

Thanks again and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
