### ISSUE TITLE
There is a space in column name "object_ id"

### ISSUE THREAD

**Issue by halfkilo** [MicrosoftDocs/sql-docs#3520]
It should be "object_id" instead of "object_ id"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df79411-afd1-930a-5248-525ddcd37229
* Version Independent ID: a10e89b4-cb68-2d1e-ee64-c44db4035c22
* Content: [SQL Server Audit Records - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-records?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/security/auditing/sql-server-audit-records.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/auditing/sql-server-audit-records.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@halfkilo -- thank you for your feedback.  I am updating the documentation.
