### ISSUE TITLE
Can not see FAILED_LOGIN_GROUP action group

### ISSUE THREAD

**Issue by halfkilo** [MicrosoftDocs/sql-docs#3522]
This action group is still available as Server-Level Audit Action Group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e423dd72-6012-f9f0-9bd1-6ab946399770
* Version Independent ID: f55d3328-111e-13d2-d8c2-78ba2b644b91
* Content: [SQL Server Audit Action Groups and Actions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@halfkilo -- please provide more context for your issue, as I am not sure what you are asking.  Thank you.

**Comment by halfkilo** [comment]
Here is the example using action group "FAILED_LOGIN_GROUP" from [CREATE SERVER AUDIT SPECIFICATION](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-server-audit-specification-transact-sql)
CREATE SERVER AUDIT SPECIFICATION HIPAA_Audit_Specification  
FOR SERVER AUDIT HIPAA_Audit  
    ADD (FAILED_LOGIN_GROUP);  
GO  

But the action group "FAILED_LOGIN_GROUP" is not listed on reference page [SQL Server Audit Action Groups and Actions](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions)

**Comment by WilliamAntonRohm** [comment]
@halfkilo -- thank you for clarifying.

@VanMSFT -- please look into this issue 3522.

**Comment by VanMSFT** [comment]
Hi @halfkilo! Sorry for the delay. I investigated why FAILED_LOGIN_GROUP was removed, and have added it back into the doc. Thanks for bringing this issue to us! The document should update in the next few hours.
