### ISSUE TITLE
Dowload Link for SqlLocalDB 2019

### ISSUE THREAD

**Issue by virzak** [MicrosoftDocs/sql-docs#3524]
Using LocalDB in a Wix Toolset Installer, so need a direct download link to SqlLocalDB.exe.

Previously was getting from [here](https://stackoverflow.com/questions/42951632/sql-server-express-localdb-msi-offline-installer)

Thanks

**Comment by msebolt** [comment]
@virzak  Thank you for the feedback.

The document has been updated per your suggestion and is pending review.

**Comment by virzak** [comment]
Thanks @msebolt 

Could you point to the PR in the meantime? Need that link :)

**Comment by msebolt** [comment]
You're welcome.

The PR is at  https://github.com/MicrosoftDocs/sql-docs-pr/pull/12861.

**Comment by virzak** [comment]
Sorry, is that a private repo? I'm getting a 404

**Comment by msebolt** [comment]
Yes, sorry for the confusion.  

If you'd like you can submit a PR via the public repo and I can merge it directly, else we need to use the private repo where it's reviewed internally and you'll need to view the changes after publish.

**Comment by virzak** [comment]
Is this live yet somewhere? Still not sure what the direct link is and I don't have access to that private repo.

**Comment by msebolt** [comment]
The link is live and now points to the SQL Express page for access to all editions.

![Capture](https://user-images.githubusercontent.com/6675884/69394831-f9dca680-0c91-11ea-8dd1-92aea7a8b2bb.PNG)
