### ISSUE TITLE
sp_estimate_data_compression_savings Not Supported on Azure

### ISSUE THREAD

**Issue by don4of4** [MicrosoftDocs/sql-docs#3529]
Since `sp_estimate_data_compression_savings` is not supported, is there an alternative that should be used?

Msg 534, Level 16, State 1, Procedure sp_estimate_data_compression_savings, Line 20 [Batch Start Line 115]
'sp_estimate_data_compression_savings' failed because it is not supported in the edition of this SQL Server instance 'MSSQLSERVER'. See books online for more details on feature support in different SQL Server editions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b4d1b7c-15c8-6671-9b5e-78ff189b354a
* Version Independent ID: 5c12ec62-94f5-7a43-04e5-026b09ac2538
* Content: [Enable Compression on a Table or Index - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-compression/enable-compression-on-a-table-or-index?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/data-compression/enable-compression-on-a-table-or-index.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-compression/enable-compression-on-a-table-or-index.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@don4of4 Thank you for the question.

Unfortunately Azure functionality is only provided as a subset to SQL Server's and is in part based on user need and priority.  

To get this in front of the product team for review and prioritization, please start a thread [here](https://feedback.azure.com/forums/908035-sql-server) and link back to this issue.

For all other support needs, please refer to the **Obtain support from Microsoft** section on the [SQL Server support](https://support.microsoft.com/help/4047326/support-policy-for-microsoft-sql-server) page.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any issues.
