### ISSUE TITLE
sudo yum install -y mssql-tools unixODBC-devel

### ISSUE THREAD

**Issue by marvinhosea** [MicrosoftDocs/sql-docs#3530]
When trying to install mssql-tools i get this error 
`No match for argument: mssql-tools
Error: Unable to find a match`

both on ubuntu 18 and fedora 30

**Comment by msebolt** [comment]
Thank you for the feedback.

This issue has been addressed in https://github.com/MicrosoftDocs/sql-docs/issues/3528, please refer there for further review and comment.
