### ISSUE TITLE
How to create a Database Scoped Credential to a Github repo or file?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/sql-docs#3531]
Hello,

What is the syntax for creating a DSC to a Github repo or file? Is this possible?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140d7c84-acc3-f722-99af-867be1f8752a
* Version Independent ID: 6bb40855-9644-1b18-3c4f-cec734cdc169
* Content: [CREATE DATABASE SCOPED CREDENTIAL (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-scoped-credential-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-database-scoped-credential-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-database-scoped-credential-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@SeaDude Thank you for the question.

Unfortunately, SQL Server does not currently offer built-in support for source control with Git.

Please see features available with either [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is?view=sql-server-ver15) or other external tools such as **Apex** and **RedGate**, see [this post](https://stackoverflow.com/questions/3793388/how-to-use-git-as-source-control-provider-for-sql-server-management-studio).

Or as an alternative, you could just run the Git commands from script, see [here](https://stackoverflow.com/questions/52454275/execute-the-bash-script-in-sql-server).

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any issues.
