### ISSUE TITLE
How to create an External Data Source to Github Repo/File?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/sql-docs#3532]
I'd like to connect an Azure SQL database to a `.geojson` file in a Github repo. Is it possible to add Github as an External Data Source? 
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e450abc6-2dbd-8f6c-423c-52aca37a2b06
* Version Independent ID: 4aff678a-6db1-a438-9aca-bb4b4d49bc27
* Content: [CREATE EXTERNAL DATA SOURCE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql?view=sql-server-ver15#f-create-an-external-data-source-for-bulk-operations-retrieving-data-from-azure-blob-storage)
* Content Source: [docs/t-sql/statements/create-external-data-source-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-data-source-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@SeaDude Thank you for the question.

This question has a similar response to issue https://github.com/MicrosoftDocs/sql-docs/issues/3531.

Please refer there for questions/comments.
