### ISSUE TITLE
SQL Server on Linux price?

### ISSUE THREAD

**Issue by q409640976** [MicrosoftDocs/sql-docs#3533]
SQL Server on Linux is free?
or the price?

**Comment by msebolt** [comment]
@q409640976 Thank you for the question.

SQL Server is priced the same on Linux as it is for Windows, please refer to [Licensing and pricing](https://docs.microsoft.com/sql/linux/sql-server-linux-setup?view=sql-server-ver15#licensing-and-pricing).

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any issues.
