### ISSUE TITLE
Table is broken

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/sql-docs#3536]
![cdc-change-tables-transact-sql](https://user-images.githubusercontent.com/40815708/68559780-9c6e7b80-0481-11ea-8a79-caef70c53589.png)

https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/cdc-change-tables-transact-sql?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3e1f12-48de-b6ae-9d20-53254795f1ce
* Version Independent ID: 604f01f5-1844-8e68-ddc0-6ef1adefcd1e
* Content: [cdc.change_tables (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/cdc-change-tables-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-tables/cdc-change-tables-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/cdc-change-tables-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@hyoshioka0128 Thank you for the feedback.

The documentation has been updated and is pending review.
