### ISSUE TITLE
Space saved

### ISSUE THREAD

**Issue by DaveBoltman** [MicrosoftDocs/sql-docs#3538]
> Consider using sparse columns when the space saved is at least 20 percent to 40 percent

In fact the NULL percentages here correspond to a space saving of specifically **_28%_**. Not sure why the words "20 percent to 40 percent" are used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46ab5559-d930-39c4-b27c-898d2883efe2
* Version Independent ID: ac1acd3d-c154-2934-5daf-fbacab4df7ba
* Content: [Use Sparse Columns - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/use-sparse-columns?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/use-sparse-columns.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/use-sparse-columns.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@DaveBoltman  Thank you for the feedback.

I can't seem to find the reference to 28%, values in the [space savings table](https://docs.microsoft.com/sql/relational-databases/tables/use-sparse-columns?view=sql-server-ver15#estimated-space-savings-by-data-type) seem to correspond to 40%?

The term "at least 20% to 40%" is meant as a rough guide on when to use this feature, each percentage is based on specific user-case scenarios and some might opt to not enable this for anything less than 40%.  

Please comment below any concerns with this approach.

**Comment by msebolt** [comment]
Closing the issue now, please add any concerns below.
