### ISSUE TITLE
Confusing Example

### ISSUE THREAD

**Issue by deanis74** [MicrosoftDocs/sql-docs#3540]
The first example is extremely confusing. The variable name is identical to the setting name, plus the leading '@'. 

@@@
DECLARE @CONCAT_NULL_YIELDS_NULL VARCHAR(3) = 'OFF';  
IF ( (4096 & @@OPTIONS) = 4096 ) SET @CONCAT_NULL_YIELDS_NULL = 'ON';  
SELECT @CONCAT_NULL_YIELDS_NULL AS CONCAT_NULL_YIELDS_NULL;
@@@

Suggest using @SAVE_SETTING for a variable name, instead of @CONCAT_NULL_YIELDS_NULL, to make it obvious what the code is doing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e46a55a-b416-67c1-3452-6bcd520f9177
* Version Independent ID: 19cf9124-8bce-7c8e-d798-a2c73e808b34
* Content: [SET CONCAT_NULL_YIELDS_NULL (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-concat-null-yields-null-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/set-concat-null-yields-null-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-concat-null-yields-null-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@deanis74  Thank you for the feedback.

The documentation has been updated and is pending review.

**Comment by deanis74** [comment]
That reads much better.
