### ISSUE TITLE
connection between nodes

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#3543]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/sql-docs.es-es/issues/73

The comment below was machine translated

@Aligtrrz commented 7 hours ago — with docs.microsoft.com
First of all, a cordial greeting, I was following the tutorial and everything was going well until point 5 of the creation of subscribers, when trying to add a SQL Server subscriber, the agent does not allow it. (It should be noted that the subscriber is a remote server) I would like to know where I can get the documentation to achieve the connection of the two nodes, as shown in this tutorial.
Another dimension is that through the server's IP, I manage to connect the instance to the publisher but I can't connect as a subscriber.
Thanks much for your attention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0086945e-a60b-31ed-9445-160fed6ea1f1
* Version Independent ID: 2dcdbf33-d5af-b766-dd5c-f477c8b441b7
* Content: [Tutorial: Configure replication between two fully connected servers (transactional) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/tutorial-replicating-data-between-continuously-connected-servers?view=sql-server-ver15)
* Content Source: [docs/relational-databases/replication/tutorial-replicating-data-between-continuously-connected-servers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/tutorial-replicating-data-between-continuously-connected-servers.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@Aligtrrz Thank you for the feedback, assigning this to the author for review of the steps.

Please note that for user scenarios outside scope of the docs will require support from those listed under **Obtain support from Microsoft** in the [SQL Server support policy](https://support.microsoft.com/help/4047326/support-policy-for-microsoft-sql-server).

**Comment by MashaMSFT** [comment]
Hi @aligtrrz, thanks for contacting Microsoft! Would you mind providing details about the issue you're seeing? What do you mean "the agent does not allow it"?  What error message are you seeing?

Thanks!
Masha from the SQL Docs team

**Comment by Aligtrrz** [comment]
Hi, I already solve the problem, the issue presented was an error to connect two remote servers when I tried to publish a database into a suscriptor sql server because the suscriptor server name was not found, I tried to connect them through "IP number/instance name" but doesn't work. so I created an alias in the sql configuration manager and that way finally works.

**Comment by MashaMSFT** [comment]
Hi @Aligtrrz , thanks for the follow up and confirming you were able to resolve your issue! I am thrilled to hear it :) I will proceed with closing out this Git Issue, but please feel free to reach out should you need anything further from us.

Thanks and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
