### ISSUE TITLE
Additional Query Store setting value made available

### ISSUE THREAD

**Issue by erinstellato** [MicrosoftDocs/sql-docs#3544]
Based on a review of the additional options in the Query Store page for Database Properties, it looks like Wait Statistics Capture Mode was also added in the 18.4 release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@erinstellato -- thank you for your feedback.

@markingmyname -- please look into this issue 3544.

**Comment by markingmyname** [comment]
@erinstellato,

Thank you for pointing this out.

This information will be added by  the end of the week.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
