### ISSUE TITLE
about volume path

### ISSUE THREAD

**Issue by q409640976** [MicrosoftDocs/sql-docs#3547]
why i set volume path with: "-v sqlvolume:/var/opt/mssql"
but the Actual volume path is "/var/lib/docker/volumes/sqlvolume/_data/data"

**Comment by WilliamAntonRohm** [comment]
@q409640976 -- thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
