### ISSUE TITLE
SSMS 18.4 Takes solid 5 min to open Steps on a SQL Agent job

### ISSUE THREAD

**Issue by JonathanH89** [MicrosoftDocs/sql-docs#3549]
Recently installed  SSMS 18.4 and SQL Server 2019. When going into steps - Edit step on a agent job it takes around 5 minutes for it to open. Works fine in example 17.5

**Comment by WilliamAntonRohm** [comment]
@JonathanH89 -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by JonathanH89** [comment]
The problem is when we're trying to edit a sql agent job step. When we either double-click on the step or chose Edit SSMS just freeze for a solid 5 minutes before opening the edit window. We've tried this with both SSMS 18.4 and 18.2 and experienced the same issue. We have tried connecting with 18.4 & 18.2 on SQL Server 2008-2019 and the same problem exist every time. We have tried using SSMS 17.5 or 17.9 and the edit window opens instantly.

**Comment by WilliamAntonRohm** [comment]
@JonathanH89 -- thank you for clarifying.

@markingmyname -- please look into this issue 3549.

**Comment by Klabbo** [comment]
I have exactly the same issue and it's really annoying. 
Its on Windows Server 2019 and SQL Server 2019 Enterprise edition when I run SSMS 18.4 locally.

**Comment by markingmyname** [comment]
@JonathanH89 

Thanks for your comment.

Your contribution is much appreciated. 

However, our team can only answer feedback related to the documentation. Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page or visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) page. If you have any feedback related to the documentation, please feel free to log in through this channel. We truly appreciate your contribution to our articles.

Hope this helps.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
