### ISSUE TITLE
"Adding versioning to non-temporal tables" uses DATETIME2 with precision 0

### ISSUE THREAD

**Issue by taspeotis** [MicrosoftDocs/sql-docs#3553]
Everything else uses `DATETIME2` (default precision: 7) but the *Adding versioning to non-temporal tables* section specifies `DATETIME2(0)`. Why the difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349eae51-5e73-47db-ee0d-8cae824f5c45
* Version Independent ID: 98d04967-6eb4-4d4d-e4a4-8e77a0f1fba0
* Content: [Creating a System-Versioned Temporal Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/creating-a-system-versioned-temporal-table?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/tables/creating-a-system-versioned-temporal-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/creating-a-system-versioned-temporal-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@taspeotis -- Todd, thank you for your feedback.

@CarlRabeler -- Carl, please look into this issue 3553.

**Comment by CarlRabeler** [comment]
@taspeotis The precision specified in this ALTER STATEMENT (https://docs.microsoft.com/en-us/sql/relational-databases/tables/creating-a-system-versioned-temporal-table?view=sql-server-ver15#adding-versioning-to-non-temporal-tables) is merely intended to show that you can specify your level of precision - for example, if you do not need fractional seconds. But also note in the Important remarks section where we say that the end time must be specified as the maximum value for a given datetime2 precision {in the underlying table]. Notice that the example in this article uses a precision of 2 in one spot and 0 in another and 7 in another - https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-table-usage-scenarios. Use the precision appropriate for your environment.

**Comment by taspeotis** [comment]
Thanks for the quick response.

I feel the documentation would benefit from a discussion about precision. Reading it doesn't impart to me how to choose a precision that would be "appropriate for [my] environment" and if I naïvely applied the examples in the documentation to my own environment today then all my new tables would have `DATETIME2(7)` columns and all my existing tables would have `DATETIME2(0)` columns. Who knows, maybe if I read the other document first I'd also have `DATETIME2(2)` in the mix?

I appreciate all your efforts on the documentation, and if you don't think it's worth pursuing I'm happy for this issue to be closed.

**Comment by CarlRabeler** [comment]
I will take a work item to improve this content. But basically, the precision for temporal should match the precision in your underlying table (will improve content to say this - thanks for bringing this to my attention). Regarding the precision you choose for your underlying table, that it really your choice based on the time precision you need and the amount of storage required for different levels of precision - see https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql.

**Comment by CarlRabeler** [comment]
PR pending
