### ISSUE TITLE
Multiple typos - should be on-premises rather than on-premise

### ISSUE THREAD

**Issue by dan-motion** [MicrosoftDocs/sql-docs#3556]
This article contains two typos - the term "on-premise" is incorrect - it should be "on-premises".  Premises means site, whereas premise means an assumption from which a logical conclusion can be drawn.  You can't drop the "s" off the end of premises in the same way you can't drop the "s" off of species, series or news!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946e0151-dfab-11da-7089-2f55926d1121
* Version Independent ID: 1e4a4cea-6111-35d8-b9c9-0f9516aee405
* Content: [Import a BACPAC File to Create a New User Database - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/import-a-bacpac-file-to-create-a-new-user-database?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/data-tier-applications/import-a-bacpac-file-to-create-a-new-user-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/import-a-bacpac-file-to-create-a-new-user-database.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@dan-motion -- thank you for your feedback.  I am looking into that article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
