### ISSUE TITLE
Small mistake/confusion on Example A

### ISSUE THREAD

**Issue by v-maudel** [MicrosoftDocs/sql-docs#3558]
@ZeDocteur commented on [Tue Nov 12 2019](https://github.com/MicrosoftDocs/sql-docs.fr-fr/issues/118)

Hi,

I believe there's a small confusion on the Example A. of this page. This is the current code example:

`DECLARE @range_first_value sql_variant ,   
        @range_first_value_output sql_variant ;  
  
EXEC sp_sequence_get_range  
@sequence_name = N'Test.RangeSeq'  
, @range_size = 4  
, @range_first_value = @range_first_value_output OUTPUT ;  
  
SELECT @range_first_value_output AS FirstNumber ;`

This should be:

`DECLARE @range_first_value_output sql_variant ;  
  
EXEC sp_sequence_get_range  
@sequence_name = N'Test.RangeSeq'  
, @range_size = 4  
, @range_first_value = @range_first_value_output OUTPUT ;  
  
SELECT @range_first_value_output AS FirstNumber ;`

The first parameter to be declared is actually the name of the parameter of the stored procedure and hence does not need to be declared. I think it's a bit confusing although the example script is still valid.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 4ff2bf70-0924-5e33-6624-74e402157750
* Version Independent ID: 3cc8dc62-a7cf-3902-de4e-b9dc58e9a2a8
* Content: [sp_sequence_get_range (Transact-SQL) - SQL Server](https://docs.microsoft.com/fr-fr/sql/relational-databases/system-stored-procedures/sp-sequence-get-range-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-sequence-get-range-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/relational-databases/system-stored-procedures/sp-sequence-get-range-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

---

@srvbpigh commented on [Tue Nov 12 2019](https://github.com/MicrosoftDocs/sql-docs.fr-fr/issues/118#issuecomment-553004333)

Hello, @ZeDocteur
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@stevestein, @srvbpigh, @v-maudel -- The above-mentioned [PR 12880](https://github.com/MicrosoftDocs/sql-docs-pr/pull/12880) has this proposed change -- please let me know if it is correct.

**Comment by rothja** [comment]
@WilliamAntonRohm Thanks, Steve is OOF for the month. @CarlRabeler could you please take a look? #assign:CarlRabeler #unassign:stevestein

**Comment by CarlRabeler** [comment]
addressed in this PR: https://github.com/MicrosoftDocs/sql-docs-pr/pull/12880
