### ISSUE TITLE
Error in ESTIMATEONLY

### ISSUE THREAD

**Issue by ssg-randy-knight** [MicrosoftDocs/sql-docs#3560]
The document has "ESTIMATE ONLY" (with  a space) and the command requires ESTIMATEONLY (no space). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81ceda7-f086-be93-7213-affd26e8aa23
* Version Independent ID: 36dd40d5-21c3-eb68-a51b-7e9977d61d73
* Content: [DBCC CHECKALLOC (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-checkalloc-transact-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-2014#feedback)
* Content Source: [docs/t-sql/database-console-commands/dbcc-checkalloc-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/database-console-commands/dbcc-checkalloc-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **umajay**

**Comment by pmasl** [comment]
Addressed with PR #12882

**Comment by WilliamAntonRohm** [comment]
@ssg-randy-knight -- thank you for your feedback.  We have updated the documentation and it should be live by tomorrow.

@pmasl -- thank you for creating [PR 12882](https://github.com/MicrosoftDocs/sql-docs-pr/pull/12882).  I have signed off on it and it is now merged.
