### ISSUE TITLE
In Exapme (E) Using correlated subqueries, misleading content

### ISSUE THREAD

**Issue by SDP190** [MicrosoftDocs/sql-docs#3561]
In the page at example E you wrote:

-START-

![Capture2](https://user-images.githubusercontent.com/16751213/68727546-b481f000-0592-11ea-95ba-cb508837db86.PNG)

-END-

Now you are not clear enough here, because it seems to indicate that the first code example is not a correlated subquery, as you say after that  '_**The following** example uses IN in a correlated, or repeating, subquery_', however in fact the first code example with the `EXISTS` in the `WHERE` clause IS definitely a correlated subquery, since it depends on the Outer queries current row `ProductModelId`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b8c2959-4a3c-bf2e-4504-c84cb30660b7
* Version Independent ID: c1e9b6b5-d398-ebd1-b447-ede189bd6c15
* Content: [SELECT Examples (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-examples-transact-sql?view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/t-sql/queries/select-examples-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/select-examples-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@SDP190  Thank you for the feedback and insight.

The documentation has been reworded and is pending review.

**Comment by SDP190** [comment]
Hi @msebolt, I hope you will see my comment although it was closed.

Firstable thanks for you taking time to work on that issue, I saw the changes you committed [here](https://github.com/MicrosoftDocs/sql-docs/commit/38433551f45bbffd61c5eee20553a819629490bd).
However to my understanding, the first code example may still need some clarification, as shown in the image at the first code segment there are 2 examples of a query, the first using `EXISTS`  vs the second using `IN`. We should be more explicit by explaining what's the difference between them is, and that the first one is a _correlated_ subquery while the second one is not. @msebolt am I right? can you see what bothers me?

![Capture5](https://user-images.githubusercontent.com/16751213/69010737-87d22d80-0930-11ea-9b93-88a83f939b35.PNG)
