### ISSUE TITLE
example code using the ALL keyword is redundant

### ISSUE THREAD

**Issue by SDP190** [MicrosoftDocs/sql-docs#3562]
In the example code for example **(E)** which can be found [here](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/codesnippet/tsql/select-examples-transact_11.sql), the usage of **ALL** keyword ([line 6](https://github.com/MicrosoftDocs/sql-docs/blob/e37636c275002200cf7b1e7f731cec5709473913/docs/t-sql/queries/codesnippet/tsql/select-examples-transact_11.sql#L6)) is redundant, since the subquery returns only a scaler value with the `AVG` function, so you can skip **'ALL'** keyword which is only used when comparing against a recordset.

---

![tempsnip](https://user-images.githubusercontent.com/16751213/68726657-2ad12300-0590-11ea-9f60-406c2d6b56cf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b8c2959-4a3c-bf2e-4504-c84cb30660b7
* Version Independent ID: c1e9b6b5-d398-ebd1-b447-ede189bd6c15
* Content: [SELECT Examples (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-examples-transact-sql?view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/t-sql/queries/select-examples-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/select-examples-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@SDP190 Thank you again for the feedback.

The documentation has been updated and is pending review.

**Comment by SDP190** [comment]
> The documentation has been updated and is pending review.

Where was the change committed? can I find it on github?

**Comment by msebolt** [comment]
@SDP190 Sorry for the missing details, the link to the PR listed above is a private repo.

You'll need to wait until the changes are published to review, unless you want to submit the PR ahead of time through the public repo and it can be merged directly.

**Comment by SDP190** [comment]
Can you please guide me on how to (quote): _"submit the PR ahead of time through the public repo and it can be merged directly"_

**Comment by msebolt** [comment]
@SDP190 You're welcome.

Sure, please refer to the [Contributor's guide](https://docs.microsoft.com/contribute/) for guidance.
