### ISSUE TITLE
Applies to Azure SQL Database?

### ISSUE THREAD

**Issue by baizini** [MicrosoftDocs/sql-docs#3570]
The APPLIES TO: heading indicates that this feature does not apply to Azure SQL Database, whereas the first sentence of text implies that it does.
Which is correct?  Please edit the page to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4e3344e-e4a8-4356-7036-729c77f6fbd1
* Version Independent ID: a57b3944-c108-081a-6308-a2fedec15de6
* Content: [Scalar UDF Inlining in Microsoft SQL databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/scalar-udf-inlining?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/relational-databases/user-defined-functions/scalar-udf-inlining.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/user-defined-functions/scalar-udf-inlining.md)
* Product: **sql**
* GitHub Login: @s-r-k
* Microsoft Alias: **karam**

**Comment by msebolt** [comment]
@baizini Thank you for the feedback, assigning this to the author for review.

**Comment by hillmarcus** [comment]
Has there been any update on this? I'm trying to determine if this is a feature I can make use of in our Azure environment.

Thanks

**Comment by rothja** [comment]
@hillmarcus I apologize for the delay. @s-r-k Do you know the answer to this question? Also adding @stevestein to help look into it. #assign:stevestein

**Comment by CarlRabeler** [comment]
@hillmarcus edited page to reflect that it does not currently apply to Azure SQL Database

**Comment by hillmarcus** [comment]
Thanks for the update @rothja and @CarlRabeler.

I'd just like to be clear, since I don't see any change on the web page and no one has referenced a commit or pull request. The bold text below is what was confusing me. Is it going to be changed in a future PR?

Quote from the beginning of [this article](https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/scalar-udf-inlining) (emphasis mine):

> This article introduces Scalar UDF Inlining, a feature under the Intelligent Query Processing suite of features. This feature improves the performance of queries that invoke scalar UDFs in SQL Server (starting with SQL Server 2019 (15.x)) and **Azure SQL Database**.

**Comment by CarlRabeler** [comment]
PR has merged – will be live later today
