### ISSUE TITLE
Not array

### ISSUE THREAD

**Issue by iuriivaschuk** [MicrosoftDocs/sql-docs#3573]
azdata bdc config replace -c custom-prod-kubeadm/control.json -j "$.security.clusterUsers=[\"bdcusers1\,bdcusers2\"]"
may be
azdata bdc config replace -c custom/control.json -j "$.security.clusterUsers=[\"bdcusers1\",\"bdcusers2\"]"
?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6733c468-62a5-41d9-2c5a-5ca57ee5fdf3
* Version Independent ID: dd529f6a-f02d-0dc4-dd4f-52321e90bed0
* Content: [Deploy SQL Server Big Data Cluster in Active Directory mode - Deploy SQL Server Big Data Cluster in Active Directory mode](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-active-directory?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/deploy-active-directory.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-active-directory.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @NelGson
* Microsoft Alias: **negust**

**Comment by NelGson** [comment]
Hi, not sure what your question is. It all depends on what you called your custom profile. The command in the Doc assumes you did this:
azdata bdc config init --source kubeadm-prod  --target **custom-prod-kubeadm**

If you named your profile "custom", then you can use that name.

**Comment by iuriivaschuk** [comment]
string, one user with name bdcusers1,bdcusers2
"$.security.clusterUsers=["bdcusers1,bdcusers2"]"
array of strings, two users with names bdcusers1 and bdcusers2
"$.security.clusterUsers=["bdcusers1","bdcusers2"]"

**Comment by NelGson** [comment]
Oh ok. Yes you are corrrect. It should be ["bdcusers1","bdcusers2"]". We will update the Doc

**Comment by NelGson** [comment]
However, at this point, we recommend only having one group.

**Comment by NelGson** [comment]
So please use only one group like this: 
azdata bdc config replace -c custom-prod-kubeadm/control.json -j "$.security.clusterUsers=[\"bdcusersgroup\"]"

Doc will be updated to reflect this. You can add other groups as members of a group

**Comment by iuriivaschuk** [comment]
So, do not use multiple values for ALL security settings?
I have couple DNS & AD Servers

**Comment by NelGson** [comment]
No, just one group in ClusterAdmins and ClusterUsers for now. You can have multiple AD/DNS servers.
