### ISSUE TITLE
query window not update content when i click from one to other

### ISSUE THREAD

**Issue by dishmaev** [MicrosoftDocs/sql-docs#3574]
SQL Server Management Studio						15.0.18206.0
Microsoft Analysis Services Client Tools						15.0.1567.0
Microsoft Data Access Components (MDAC)						10.0.18362.1
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.18362.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.18362

**Comment by msebolt** [comment]
@dishmaev Thank you for the feedback.

Unfortunately we can only address documentation issues in this forum.

Please move this issue to the [SQL Server feedback](https://feedback.azure.com/forums/908035-sql-server) and the product team can respond.
