### ISSUE TITLE
Note

### ISSUE THREAD

**Issue by bertrand24** [MicrosoftDocs/sql-docs#3575]
in the Note, after the uninstallation of SSMS
you mean : reboot is required

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b419de6-b39e-a68f-7c68-d996e77e72ab
* Version Independent ID: 5304fec4-1727-47d2-73c5-152ca67c50d5
* Content: [SQL Server 2019 Release Notes - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-version-15-release-notes?view=sql-server-ver15#feedback)
* Content Source: [docs/sql-server/sql-server-version-15-release-notes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/sql-server-version-15-release-notes.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@bertrand24  Thank you for the feedback.

Since this could also mean that uninstall is an overall requirement to process, I'll just remove the note altogether.

Any reboots will be implied by following direction from the installer.
