### ISSUE TITLE
Examples are misleading

### ISSUE THREAD

**Issue by nsiicm0** [MicrosoftDocs/sql-docs#3576]
The example B on the reported page (https://docs.microsoft.com/en-us/sql/t-sql/language-elements/while-transact-sql?view=sql-server-2016#b-using-while-in-a-cursor) is misleading.

Issues:
1. There are two consecutive FETCH NEXT statements which actually skips the first record inside the loop, while directing the first record to the client directly.

```SQL
...
OPEN Employee_Cursor;  
FETCH NEXT FROM Employee_Cursor;  
FETCH NEXT FROM Employee_Cursor INTO @EmployeeID, @Title;  
...
```

2. Inside the loop the next fetch does not update the variables, hence the print statement does not change. Instead all successive fetches are directly sent to the client.

```SQL
...
    FETCH NEXT FROM Employee_Cursor;  
END;
```

I propose the following:
1. Remove the first `FETCH NEXT FROM Employee_Cursor;` as described in issue 1, as it is misleading and cause for error.
2. Replace the second `FETCH NEXT FROM Employee_Cursor;` inside the loop as described in issue 2 with `FETCH NEXT FROM Employee_Cursor INTO @EmployeeID, @Title; `

Since this example is about while loops, it does not need to send stuff to the client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 281e1863-17b2-816d-5ff8-c78567f42715
* Version Independent ID: 97d6be62-7c8e-45ca-79df-85f48b60b9b0
* Content: [WHILE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/while-transact-sql?view=sql-server-2016#feedback)
* Content Source: [docs/t-sql/language-elements/while-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/while-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@nsiicm0 Thank you for the feedback and assessment.

The documentation has been updated and should now function as intended.
