### ISSUE TITLE
Invalid download link

### ISSUE THREAD

**Issue by Truckerek** [MicrosoftDocs/sql-docs#3581]
Download link on the page is incorrect. The correct download link is https://aka.ms/ssmsfullsetup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by davervw** [comment]
Agreed, invalid download link.  Typo -- extra "s".  It's not sssms, but ssms....

**Comment by nkarthik123** [comment]
Thank You :)

**Comment by jeffussing** [comment]
I had the same problem, but I think it's fixed now.

**Comment by msebolt** [comment]
@Truckerek Thank you for the feedback, this was fixed per latest commit https://github.com/MicrosoftDocs/sql-docs/commit/8f51a4dc00998d853381ce0dffa39b61e855f00e#diff-c05e370262563982dae2899f4fc40f3e. 

Please comment below if there are any further issues.
