### ISSUE TITLE
How to fix SSMS 18

### ISSUE THREAD

**Issue by dimmthewitted** [MicrosoftDocs/sql-docs#3583]
Are you seeing The query has been canceled because the estimated cost of this query?

Go into Tools &gt; Options&gt; Query Execution &gt; SQL Server &gt; Advanced
Change set query governor cost limit to 0 (unlimited)

MS in their infinite wisdom decided we need local SSMS governors so tight it kills 2 second queries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef632046-6b35-8bb6-d3f7-9eb8a752d84e
* Version Independent ID: 4e08e515-9ee3-7414-9683-639f740fef83
* Content: [SET QUERY_GOVERNOR_COST_LIMIT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-query-governor-cost-limit-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/set-query-governor-cost-limit-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-query-governor-cost-limit-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by dimmthewitted** [comment]
Note you will need to close and re-open SSMS.

That'll teach you to update a Microsoft product.

**Comment by msebolt** [comment]
@dimmthewitted Thank you for the feedback.

The latest version of SSMS has the default setting set to `0`:

![Capture](https://user-images.githubusercontent.com/6675884/68827374-94b40000-0656-11ea-9947-d815a3df1dc3.PNG)

Could this setting have been set to `2` by another process?

**Comment by msebolt** [comment]
Closing this now, please comment below if there are further issues.
