### ISSUE TITLE
Ctrl-C / Ctrl-V

### ISSUE THREAD

**Issue by iuriivaschuk** [MicrosoftDocs/sql-docs#3587]
Change from
Create User objects
Create User objects
To
Create User objects
Delete User objects

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6733c468-62a5-41d9-2c5a-5ca57ee5fdf3
* Version Independent ID: dd529f6a-f02d-0dc4-dd4f-52321e90bed0
* Content: [Deploy SQL Server Big Data Cluster in Active Directory mode - Deploy SQL Server Big Data Cluster in Active Directory mode](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-active-directory?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/deploy-active-directory.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-active-directory.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @NelGson
* Microsoft Alias: **negust**

**Comment by WilliamAntonRohm** [comment]
@iuriivaschuk -- thank you for your feedback.  I am looking into the documentation.
