### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by BjornSigurd** [MicrosoftDocs/sql-docs#3595]
Please make the download links stand out much clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by WilliamAntonRohm** [comment]
@BjornSigurd -- thank you for your feedback.  We will look into this in the documentation.  You can submit issues related to your overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
