### ISSUE TITLE
Temp table vs mem opt table - performance

### ISSUE THREAD

**Issue by maciejpiwowarczyk** [MicrosoftDocs/sql-docs#3596]
I tried to benchmark temporary table with mem opt table - in my case temp table was much faster. https://stackoverflow.com/questions/58858515/sql-server-memory-optimized-table-poor-performance-compared-to-temporary-table/58859928

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18fbf809-639b-6188-c54f-3cb0a009addf
* Version Independent ID: 4e1b4ccd-1980-3ffd-0de2-5c1db30618b4
* Content: [Faster temp table and table variable by using memory optimization - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/faster-temp-table-and-table-variable-by-using-memory-optimization?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/in-memory-oltp/faster-temp-table-and-table-variable-by-using-memory-optimization.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/faster-temp-table-and-table-variable-by-using-memory-optimization.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @jodebrui
* Microsoft Alias: **jodebrui**

**Comment by WilliamAntonRohm** [comment]
@maciejpiwowarczyk -- thank you for your research and feedback.

@jodebrui -- please look into updating the article as needed.

fyi @MightyPen

**Comment by WilliamAntonRohm** [comment]
@jodebrui -- Jos, please look into this issue.

cc @rothja as a writer

**Comment by rothja** [comment]
@maciejpiwowarczyk Sorry for the long delay on a response on this one. For issues with product functionality and performance, it is probably better to discuss this on [Microsoft Docs](https://docs.microsoft.com/en-us/answers/products/sql-server) with the community & Microsoft and/or give [product feedback for SQL Server](https://feedback.azure.com/forums/908035-sql-server). I will close out this issue now, but please feel free to add more comments to the thread if you have additional questions or comments.

**Comment by rothja** [comment]
#reassign:rothja
