### ISSUE TITLE
All azdata reference articles say they're for "sql" commands

### ISSUE THREAD

**Issue by DiegoBoy-MSFT** [MicrosoftDocs/sql-docs#3599]
Due to copy&paste, all reference articles for azdata, just below the "this topic applies to" section, state the article is for azdata's sql commands. Some examples:

https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata?view=sql-server-ver15
https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata-notebook?view=sql-server-ver15
https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata-bdc?view=sql-server-ver15

* Microsoft Alias: **dirodri**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 664800ce-d1cd-0ef1-f1b1-ac29e3a0e70d
* Version Independent ID: 88acde31-c5df-8b82-b447-8a982bca13b9
* Content: [azdata bdc reference - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata-bdc?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/reference-azdata-bdc.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/reference-azdata-bdc.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@DiegoBoy-MSFT -- thank you for noticing this and letting us know.

@MikeRayMSFT -- here is the existing sentence.  Please reword it as needed and I will update the articles.

> The following article provides reference for the sql commands in the azdata tool. For more information about other azdata commands, see azdata reference

**Comment by MikeRayMSFT** [comment]
@DiegoBoy-MSFT  - thanks for submitting this - fixing now. PR 13086 cited above.
