### ISSUE TITLE
Changing to read-only

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/sql-docs#3601]
The section below is confusing a customer working with Azure SQL DB. In our understanding, SIZE_BASED_CLEANUP_MODE is set to AUTO by default and usually prevents this from happening. Is it common for the Query Store to hit max size while SIZE_BASED_CLEANUP_MODE is in effect? If that did happen, would it switch back to read-write after cleanup?
If this is just talking about a scenario where you aren't cleaning it up, maybe that could be made clearer.

Max Size (MB): Specifies the limit for the data space that Query Store takes inside your database. This is the most important setting that directly affects the operation mode of Query Store.
While Query Store collects queries, execution plans, and statistics, its size in the database grows until this limit is reached. When that happens, Query Store automatically changes the operation mode to read-only and stops collecting new data, which means that your performance analysis is no longer accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155bfbc5-9c63-32c6-9d06-a9b3cdb4c60e
* Version Independent ID: c854b2de-e509-e320-8151-67d690d486ed
* Content: [Best practices with Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/best-practice-with-the-query-store?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/best-practice-with-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/best-practice-with-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @pmasl
* Microsoft Alias: **jrasnick**

**Comment by msebolt** [comment]
@dcbrown16 Thank you for the feedback, assigning this to the author for review.

For specific questions about how to use SQL Server, please refer to [SQL Server help and feedback](https://docs.microsoft.com/sql/sql-server/sql-server-get-help).

**Comment by CarlRabeler** [comment]
@dcbrown16 could you please submit your suggested improvement to the article by clicking the Edit button in the upper right of the article and submitting a PR? Thank you.
Carl

**Comment by dcbrown16** [comment]
Thanks @CarlRabeler, I would normally do that if I was sure of the content but I'm not sure what the correct change would be. The support case we had for this issue is long since closed but the interaction between Max Size and the default SIZE_BASED_CLEANUP_MODE settings seems to have been the issue.

**Comment by CarlRabeler** [comment]
we probably will not document it then - this is the only time I have heard it come up

**Comment by pmasl** [comment]
I've added a clarification to the https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options page with PR #14188

**Comment by CarlRabeler** [comment]
Thanks @pmasl
