### ISSUE TITLE
Examples missing!

### ISSUE THREAD

**Issue by Gagan059** [MicrosoftDocs/sql-docs#3602]
Please specify TSQL examples for adding FK with NOT FOR REPLICATION option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1440b021-9ccb-3146-921e-a294fd7ee29e
* Version Independent ID: e93f583e-fea7-4c3d-5669-b8a3654349dd
* Content: [Disable Foreign Key Constraints for Replication - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/disable-foreign-key-constraints-for-replication?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/tables/disable-foreign-key-constraints-for-replication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/disable-foreign-key-constraints-for-replication.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@Gagan059 Thank you for the feedback, assigning this to the author for review.

**Comment by msebolt** [comment]
Including @CarlRabeler

**Comment by rothja** [comment]
@Gagan059 Thank you for the suggestion. I will take a look and see if we can add this. Were you able to figure out how to use this in your scenario? If you have an example to share, I can use that as the basis of an article update. *Or* if you would like to edit the article, you will get credit as a collaborator at the top of the article page. Let me know. Thank you!

**Comment by Gagan059** [comment]
Hi Jason,
Thanks for reaching out. Sure, I was able to find it, and I can add it
there. Let me know if there are any rules to follow for it.

Gagan Lamba

**Comment by rothja** [comment]
@Gagan059 Thank you for being willing to edit the article. There is an edit button on each article that allows you to make and propose changes:

![image](https://user-images.githubusercontent.com/1580454/69168772-4a52d900-0ac5-11ea-9ac9-209404917f6e.png)

The only suggestion I have would be to place your example in a code block with tick marks like this screenshot: 

![image](https://user-images.githubusercontent.com/1580454/69170994-1083d180-0ac9-11ea-82e1-d123f21faf5a.png)

If you give it a try and submit your change, I'll review it and be able to give feedback if it needs any adjustments. Thank you!!

**Comment by Gagan059** [comment]
Thanks, I've added the example now.

Gagan Lamba

**Comment by rothja** [comment]
Thank you! I am going to close this issue now. I really appreciate your help with this.
