### ISSUE TITLE
processAllAvailable() is only meant for testing according to spark docs

### ISSUE THREAD

**Issue by dgshaver** [MicrosoftDocs/sql-docs#3603]
Looks like we shouldn't include processAllAvailable() in this sample as it's only intended for testing?
https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.streaming.StreamingQuery
abstract def
processAllAvailable(): Unit
Permalink
Blocks until all available data in the source has been processed and committed to the sink. This method is intended for testing. Note that in the case of continually arriving data, this method may block forever. Additionally, this method is only guaranteed to block until data that has been synchronously appended data to a org.apache.spark.sql.execution.streaming.Source prior to invocation. (i.e. getOffset must immediately reflect the addition).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c639fd7-43ee-f24d-ce5e-530077367aab
* Version Independent ID: 28059c60-abe8-e4f8-08c5-221c926f007e
* Content: [Ingest data with Spark jobs - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-spark?view=sqlallproducts-allversions#prereqs)
* Content Source: [docs/big-data-cluster/tutorial-data-pool-ingest-spark.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/tutorial-data-pool-ingest-spark.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@dgshaver  Thank you for the feedback, assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
Reviewing with engineering

**Comment by MikeRayMSFT** [comment]
https://github.com/MicrosoftDocs/sql-docs-pr/pull/12976
