### ISSUE TITLE
azdata bdc spark batch create command example is incorrect

### ISSUE THREAD

**Issue by dgshaver** [MicrosoftDocs/sql-docs#3604]
This example command is incorrect:
azdata spark batch create --code "2+2"

Two problems with this example:
1. The bdc subcommand is missing:
azdata bdc spark batch create --code 2+2
2. The --code parameter isn't valid for batches:
C:\Users\sql2019css&gt;azdata bdc spark batch create --code "2+2"
usage: azdata bdc spark batch create [-h] [--verbose] [--debug]
                                     [--output {json,jsonc,table,tsv}]
                                     [--query JMESPATH] --file FILE_TO_EXECUTE
                                     [--class-name CLASS_NAME]
                                     [--arguments ARGUMENTS]
                                     [--jar-files JARS] [--py-files PY_FILES]
                                     [--files FILES]
                                     [--driver-memory DRIVER_MEMORY]
                                     [--driver-cores DRIVER_CORES]
                                     [--executor-memory EXECUTOR_MEMORY]
                                     [--executor-cores EXECUTOR_CORES]
                                     [--executor-count EXECUTOR_COUNT]
                                     [--archives ARCHIVES] [--queue QUEUE]
                                     [--name NAME] [--config CONFIGURATION]
azdata bdc spark batch create: error: the following arguments are required: --file/-f

--file is a required parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6600107a-20b8-6ee3-1616-4c6ca1c06159
* Version Independent ID: 46981b99-72b9-16d4-bfe3-cc383708f26d
* Content: [azdata bdc spark batch reference - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata-bdc-spark-batch?view=sql-server-ver15#examples)
* Content Source: [docs/big-data-cluster/reference-azdata-bdc-spark-batch.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/reference-azdata-bdc-spark-batch.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@dgshaver Thank you for the feedback, assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
Checking with engineering.

**Comment by MikeRayMSFT** [comment]
User Story 1648821: SQL | azdata issues
