### ISSUE TITLE
File referenced by --file needs to reside in HDFS

### ISSUE THREAD

**Issue by dgshaver** [MicrosoftDocs/sql-docs#3606]
Hi, the documentation for the --file argument for **azdata bdc spark batch create** needs to be updated to reflect the requirement the file reside in HDFS.  If one references a file from the local drive of the workstation where the command is executed, the command fails with a 400, Bad Request.
This command works:
C:\Users\sql2019css&gt;azdata bdc spark batch create -f hdfs://nmnode-0/scripts/pi.py

These commands that reference the pi.py file on the local disk of the workstation where the command was submitted return a 400 (Bad Request):
C:\Users\sql2019css&gt;azdata bdc spark batch create -f file:///c:/users/sql2019css/pi.py 
C:\Users\sql2019css&gt;azdata bdc spark batch create -f pi.py

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6600107a-20b8-6ee3-1616-4c6ca1c06159
* Version Independent ID: 46981b99-72b9-16d4-bfe3-cc383708f26d
* Content: [azdata bdc spark batch reference - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata-bdc-spark-batch?view=sql-server-ver15#azdata-bdc-spark-batch-create)
* Content Source: [docs/big-data-cluster/reference-azdata-bdc-spark-batch.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/reference-azdata-bdc-spark-batch.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@dgshaver -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue 3606.

**Comment by MikeRayMSFT** [comment]
Thanks! @dgshaver -- investigating.

**Comment by MikeRayMSFT** [comment]
https://github.com/MicrosoftDocs/sql-docs/issues/3606

**Comment by ev2900** [comment]
Was this issue resolved? 

I am looking at the documentation for [azdata bdc spark batch create](https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata-bdc-spark-batch?view=sql-server-ver15#azdata-bdc-spark-batch-create). It does not include any information that that file must be located on the HDFS of the BDC cluster and not on the local host.

**Comment by dgshaver** [comment]
It doesn’t appear so. I think Mike discussed it with the developer that owns the feature, but I don’t recall what the outcome was.

Thanks,
Dan Shaver
Microsoft Big Data and Analytics Support
980 776 7817
Work schedule: M – F, 08:00 to 17:00 US Eastern Standard Time Zone

**Comment by ev2900** [comment]
Ok should I reopen the issue then or do you feel that it isn't appropriate to include this information in the documentation?
