### ISSUE TITLE
Documentation for --jar-files argument is incorrect

### ISSUE THREAD

**Issue by dgshaver** [MicrosoftDocs/sql-docs#3607]
If I correctly understand the documentation for the --jar-files argument, it doesn't seem to be correct.  The documentation states the format of --jar-files is:
List of jar file paths. To pass in a list JSON encode the values. Example: '["entry1", "entry2"]'.

If I submit the following command, it fails with a 400:
C:\Users\sql2019css&gt;azdata bdc spark batch create --file hdfs://nmnode-0/scripts/pi.py --debug --jar-files '["hdfs://nmnode-0/jars/azure-eventhubs-2.3.2.jar","hdfs://nmnode-0/jars/azure-eventhubs-spark_2.11-2.3.13.jar","hdfs://nmnode-0/jars/proton-j-0.31.0.jar","hdfs://nmnode-0/jars/qpid-proton-j-extensions-1.2.0.jar","hdfs://nmnode-0/jars/scala-java8-compat_2.11-0.9.0.jar","hdfs://nmnode-0/jars/slf4j-api-1.7.25.jar"]'
I see the following in the DEBUG output that leads me to believe the correct format is a comma separated, list of double-quoted strings:
send: b'{"file": "hdfs://nmnode-0/scripts/pi.py", "jars": ["\'[hdfs://nmnode-0/jars/azure-eventhubs-2.3.2.jar,hdfs://nmnode-0/jars/azure-eventhubs-spark_2.11-2.3.13.jar,hdfs://nmnode-0/jars/proton-j-0.31.0.jar,hdfs://nmnode-0/jars/qpid-proton-j-extensions-1.2.0.jar,hdfs://nmnode-0/jars/scala-java8-compat_2.11-0.9.0.jar,hdfs://nmnode-0/jars/slf4j-api-1.7.25.jar]\'"]}'
reply: 'HTTP/1.1 400 Bad Request\r\n'

This command works as long as there are no spaces between the entries in the list:
C:\Users\sql2019css&gt;azdata bdc spark batch create --file hdfs://nmnode-0/scripts/pyeventhub.py --debug --jar-files "hdfs://nmnode-0/jars/azure-eventhubs-2.3.2.jar","hdfs://nmnode-0/jars/azure-eventhubs-spark_2.11-2.3.13.jar","hdfs://nmnode-0/jars/proton-j-0.31.0.jar","hdfs://nmnode-0/jars/qpid-proton-j-extensions-1.2.0.jar","hdfs://nmnode-0/jars/scala-java8-compat_2.11-0.9.0.jar","hdfs://nmnode-0/jars/slf4j-api-1.7.25.jar"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6600107a-20b8-6ee3-1616-4c6ca1c06159
* Version Independent ID: 46981b99-72b9-16d4-bfe3-cc383708f26d
* Content: [azdata bdc spark batch reference - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata-bdc-spark-batch?view=sql-server-ver15#azdata-bdc-spark-batch-create)
* Content Source: [docs/big-data-cluster/reference-azdata-bdc-spark-batch.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/reference-azdata-bdc-spark-batch.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@dgshaver -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue 3607.

**Comment by MikeRayMSFT** [comment]
User Story 1648821: SQL | azdata issues
