### ISSUE TITLE
Step 2 for Install sqlmlutils online is incomplete

### ISSUE THREAD

**Issue by rovermx** [MicrosoftDocs/sql-docs#3608]
Step 2 needs to specify that command prompt must be opened as Administrator, otherwise operation halts because of permissions lacking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce36aa85-fd24-74a6-1e01-20c892f92a9f
* Version Independent ID: 08b9fb79-7117-98fc-5d2c-7a42a6c49a04
* Content: [Install new R packages - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/package-management/install-additional-r-packages-on-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/advanced-analytics/package-management/install-additional-r-packages-on-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/package-management/install-additional-r-packages-on-sql-server.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by WilliamAntonRohm** [comment]
@rovermx -- Renaud, thank you for your feedback.

@garyericson -- Gary, please look into this issue 3608.

**Comment by garyericson** [comment]
@rovermx - Which Step 2 are you referring to?

**Comment by garyericson** [comment]
#please-close, pending further clarifications from @rovermx
