### ISSUE TITLE
bash -e causes unattended install failure on slow start

### ISSUE THREAD

**Issue by ajs5710** [MicrosoftDocs/sql-docs#3609]
This section of the script appears to be polling the freshly started sql server instance to see if it is up and appears to expect a non-zero exit status if the sql server instance is not yet started at the time of polling.

```
# Connect to server and get the version:
counter=1
errstatus=1
while [ $counter -le 5 ] && [ $errstatus = 1 ]
do
  echo Waiting for SQL Server to start...
  sleep 3s
  /opt/mssql-tools/bin/sqlcmd \
    -S localhost \
    -U SA \
    -P $MSSQL_SA_PASSWORD \
    -Q "SELECT @@VERSION" 2>/dev/null
  errstatus=$?
  ((counter++))
done
```

Meanwhile in the shebang `#!/bin/bash -e` the -e seems to cause the script to exit if any command (including the polling attempts) returns a non-zero exit status?  
I was running this script more-or-less verbatim as a vagrant provisioner and the step was failing after the first `Waiting for SQL Server to start...` (but was succeeding on a different machine) removing the `-e` seemed to allow the script to finish and so-far has been working for me but might prevent the script from failing if a real failure occurs.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96990aff-bdd7-3cdd-d801-d544178cfb4d
* Version Independent ID: 6b083b6d-56b7-5a1e-3279-ae9f870e7811
* Content: [Unattended install for SQL Server on Ubuntu - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sample-unattended-install-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/sample-unattended-install-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sample-unattended-install-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@ajs5710 -- thank you for your research and feedback.

@VanMSFT -- please look into this issue 3609.

**Comment by rothja** [comment]
@ajs5710 Thanks for this information. This does seem to be a conflicting requirement in the script. We will look into it. Just to let you know, @VanMSFT is out of the office for the rest of this month, but he will take a look when he returns. Thanks in advance for your patience, and really appreciate the details in your research.

**Comment by VanMSFT** [comment]
@ajs5710 - Thanks for reporting this failure in the script. We will look into this further.

**Comment by VanMSFT** [comment]
Hi @ajs5710 - Thanks again! I apologize for the delay. I have added a note to clarify that the script might fail with the `-e` switch since we are exiting with a non-zero status for a slow SQL Server start. We appreciate your help on our documentation!
