### ISSUE TITLE
Guessing when a feature was implemented

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#3616]
Hi - this whole new process of having to select a version and guess whether a feature is installed is very time wasting.

IsNumeric IS available in SQL 2014 (at least in SP3-CU4).
However when I try and check when the feature was added by using this page, I get :
The requested page is not available for SQL Server 2014. You have been redirected to the newest product version this page is available for.

Instead of taking me to the oldest page, it takes me to the newest.

Is there any easy way to navigate help to see when a feature was introduced (and can you fix this page so it is correct also).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d033792-b9dc-3d69-1020-8e0c295b9d3c
* Version Independent ID: b3bac4f3-fb1f-c992-7cba-2dda8459bf14
* Content: [ISNUMERIC (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/isnumeric-transact-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-2014)
* Content Source: [docs/t-sql/functions/isnumeric-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/isnumeric-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@brettshearer -- Brett, thank you for your feedback.  You are welcome to file a bug about your documentation experience:  [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback). 

@MikeRayMSFT -- Mike, please look into this issue 3616.

**Comment by MikeRayMSFT** [comment]
@brettshearer 

- Thanks for this feedback. You're presenting two important issues.

1. What's the correct content for SQL Server 2014 `ISNUMERIC()` function.
2. Make the version specific information explicit, discover-able and correct. 

I'm creating an item to track (1684796). We'll track this (and other issues related to version). As @WilliamAntonRohm mentioned, you can submit your experience to aka.ms/sitefeedback.
