### ISSUE TITLE
documentation not consistent with behavior

### ISSUE THREAD

**Issue by af4jm** [MicrosoftDocs/sql-docs#3619]
After getting the November update, I created a new notebook, connected it to SQL, & added a code block, as per the top of this page... when I clicked Run, I expected it to run the query & show results, as described in this page... instead I got a rotating arrow indicator labelled "PowerShell" in the status bar & nothing in the notebook... after a minute I killed it, opened a new Query, pasted in the same query and hit Run... had my results in a second or 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4558fc-19ae-bc48-0f83-2c83aee01252
* Version Independent ID: 5e391c2c-49ed-9a44-7980-ba8db5a26b2d
* Content: [Run notebooks in Azure Data Studio - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/notebooks-guidance?view=sql-server-ver15#feedback)
* Content Source: [docs/big-data-cluster/notebooks-guidance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/notebooks-guidance.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@af4jm -- John, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue 3619.

**Comment by MikeRayMSFT** [comment]
@af4jm - thank you for your feedback. I'm sharing this with the tools team.

**Comment by hannahqin** [comment]
@af4jm Hi John, thanks for your feedback. I was unable to reproduce the issue you described. If it occurs again, could you please refile this issue on the Azure Data Studio repository with more detail? Screenshots and gifs help us a lot in resolving bugs quickly. 

**Azure Data Studio repo:** https://github.com/microsoft/azuredatastudio
