### ISSUE TITLE
We would love the option to disable outlining

### ISSUE THREAD

**Issue by dimmthewitted** [MicrosoftDocs/sql-docs#3620]
Imagine We have a number parameters at the top that we need to one off comment out, but the collapse is always in the way.

There is not enough space between the code outlining and the text so we are CONSTANTLY accidentally collapsing when trying to click in first line of the query.

I find myself disabling code outlining on EVERY single new query window.

Please make a global disable of Code outlining.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d3ba88-bb53-d484-ee90-d3d531befe5d
* Version Independent ID: 5382dd32-b21d-2e3a-2c6b-ed2cb7c18863
* Content: [Code Outlining - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/scripting/code-outlining?view=sql-server-ver15)
* Content Source: [docs/ssms/scripting/code-outlining.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/code-outlining.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@dimmthewitted -- thank you for your feedback; please add it here:

- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
