### ISSUE TITLE
Does NOT work with Power BI as stated

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#3623]
This page contains a statement "Other tools or services like SSIS, SSRS, or Power BI will work with graph tables, just the way they work with relational tables.".  I disagree from a Power BI standpoint.
Power BI will NOT import Graph Tables the same as relational tables.  This post [https://www.sqlshack.com/plot-sql-server-2017-graph-database-using-powerbi/] highlights a potential mitigating method, but the base concept that it works *the same* is not true as an error is given by Power BI when the graph table is requested to be imported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a893981-46bb-c010-6d63-39eee88dcf91
* Version Independent ID: 8bacd3f7-6793-3316-6a31-3e599d209821
* Content: [Graph processing - SQL Server and Azure SQL Database](https://docs.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-overview?view=sql-server-ver15&source=docs)
* Content Source: [docs/relational-databases/graphs/sql-graph-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/graphs/sql-graph-overview.md)
* Product: **sql**
* GitHub Login: @shkale-msft
* Microsoft Alias: **shkale**

**Comment by WilliamAntonRohm** [comment]
@LindaLF -- thank you for your research and feedback.

@shkale-msft -- please look into this issue 3623.

**Comment by sachinbabuputhur** [comment]
You can't import the tables themselves, but you can import the view which describes the relationships.

**Comment by rothja** [comment]
@LindaLF I'm closing this PR per the previous comment, but if you have any concerns or comments on this, please let me know.
