### ISSUE TITLE
Clarify impact to TVFs and CTEs

### ISSUE THREAD

**Issue by dialedin2014** [MicrosoftDocs/sql-docs#3624]
With the inline TFV example, this article hints Deferred Compilation of Table Variables impacts more than just table variables.  What about CTEs, multi-statement TVFs, and user-defined table types?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6815fe42-952d-35a8-5be1-6f804348ced0
* Version Independent ID: 06ff291c-9c92-11b5-88ec-467b6801eee6
* Content: [table (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/table-transact-sql?view=sql-server-ver15#table-variable-deferred-compilation)
* Content Source: [docs/t-sql/data-types/table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
Thanks for the good questions. I'm verifying a few things and working to get your questions answered.

**Comment by joesackmsft** [comment]
Hello,
Table variable deferred compilation is specific to table variables.  It doesn't apply to CTEs, MSTVFs and user defined types.  You mention we hint at this - can you let me know where and I'll adjust the language?  Thanks

**Comment by dialedin2014** [comment]
Example B on https://docs.microsoft.com/en-us/sql/t-sql/data-types/table-transact-sql?view=sql-server-ver15#table-variable-deferred-compilation refers to an inline table-valued function.  The example is below a discussion of deferred compilation.

**Comment by joesackmsft** [comment]
Got it.  The examples apply to the overall "table" topic and TVDC is just a subtopic.  For clarity, I'll work on moving the majority of TVDC content to the Intelligent QP page.

**Comment by MikeRayMSFT** [comment]
@dialedin2014, thanks for raising this issue. 

Thank you @joesackmsft  for responding.

**Comment by joesackmsft** [comment]
FYI on this - I've moved the TVDC content to https://docs.microsoft.com/en-us/sql/relational-databases/performance/intelligent-query-processing?view=sql-server-2017#table-variable-deferred-compilation and added a pointer from the original table topic.  @dialedin2014 thanks for the feedback!

**Comment by dialedin2014** [comment]
Looks good thanks
