### ISSUE TITLE
Instructions for role-based security are missing

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/sql-docs#3625]
Where can we find the instructions about how to implement role-based security for the web portal? they don't seem to exist.

**Comment by msebolt** [comment]
@DeanGross Thank you for the feedback.

Are you referring to RBAC security in particular?

Please see the [RBAC overview](https://docs.microsoft.com/azure/role-based-access-control/overview) and/or [Database engine permissions](https://docs.microsoft.com/sql/relational-databases/security/authentication-access/getting-started-with-database-engine-permissions) adding any details you think would be helpful and we can assign an author.

**Comment by DeanGross** [comment]
Sorry for not being more clear, on https://docs.microsoft.com/en-us/sql/reporting-services/web-portal-ssrs-native-mode?view=sql-server-2016#what-is-the-web-portal there is a statement that we can "Configure role-based security that determines access to items and operations.". Where can I find the instructions for doing this in the SSRS web portal?

**Comment by msebolt** [comment]
Thank you for the update, assigning this to the author for review.

**Comment by maggiesMSFT** [comment]
Hi, @DeanGross -- see the article https://docs.microsoft.com/en-us/sql/reporting-services/security/role-definitions-predefined-roles?view=sql-server-ver15 for info on role-based security in SSRS. 
I can add a link to that article from the web portal article, https://docs.microsoft.com/en-us/sql/reporting-services/web-portal-ssrs-native-mode?view=sql-server-2016#what-is-the-web-portal.

**Comment by maggiesMSFT** [comment]
Hi, @DeanGross -- added the link. Thanks again!
#please-close
