### ISSUE TITLE
Value returned of Status property

### ISSUE THREAD

**Issue by bgehem** [MicrosoftDocs/sql-docs#3628]
The "Value returned" column of the Status property says: "... The database can accept connections when the database collation returns a non-null value. ..." This is not true when Status is SUSPECT. I have tested on SQL Server 2017 CU17.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ca907e-99b6-3663-82bf-abe45f1ae76e
* Version Independent ID: 1acba411-593f-6cd2-7c76-8e35dbd8ac13
* Content: [DATABASEPROPERTYEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/databasepropertyex-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/databasepropertyex-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/databasepropertyex-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@bgehem Thank you for the feedback.

Please note your cited reference describes the `ONLINE` status only.

However though, it's also noted under section [syntax](https://docs.microsoft.com/en-us/sql/t-sql/functions/databasepropertyex-transact-sql?view=sql-server-2017#syntax), as:

```
If the database has not yet started, calls to DATABASEPROPERTYEX will return NULL if DATABASEPROPERTYEX retrieves those values by direct database access, instead of retrieval from metadata.
```

Please confirm that:
- you're making a direct call to `DATABASEPROPERTYEX`, not metadata
- the call is returning a non-null value
- no connections can be made to the database

If so, I can assign this to the author for further review.

**Comment by bgehem** [comment]
Tested with sa server role.

- The result is not NULL so I assume it's a direct call.
- The result is not NULL.
- No connections can be made to the database.

```sql
select HAS_DBACCESS('test') as HAS_DBACCESS,
       DATABASEPROPERTYEX('test', 'Collation') as Collation, 
       DATABASEPROPERTYEX('test', 'Status') as Status,
       DATABASEPROPERTYEX('test', 'IsAutoClose') as IsAutoClose
```	   
HAS_DBACCESS | Collation | Status | IsAutoClose
------------ | --------- | ------ | -----------
0 | SQL_Latin1_General_CP1_CI_AS | SUSPECT | 0

**Comment by msebolt** [comment]
Thank you for the update, assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
@bghehem - I've staged an update and am having it reviewed internally. The note applies to when a database status is ONLINE. The note does not apply to  when the database status is SUSPECT.  I think the document shows it. 

But to clarify, the proposed update to the note would read:

> **Note**: The function may return a status of ONLINE while the database opens and has not yet recovered. To identify if an ONLINE database can accept can accept connections, query the Collation property of **DATABASEPROPERTYEX**. The ONLINE database can accept connections when the database collation returns a non-null value. For Always On databases, query the database_state or database_state_desc columns of sys.dm_hadr_database_replica_states.

Do you believe that provides sufficient clarity?

**Comment by bgehem** [comment]
That makes it perfectly clear.

One small thing: can accept is duplicated.
> database can accept can accept connections
