### ISSUE TITLE
Download Docs Instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/sql-docs#3629]
The documenation at https://www.microsoft.com/en-us/download/details.aspx?id=55949 for this web part does not show that SP 2019 is supported. I'm assuming that is just a documentation issue, but it is causing some confusion. Can you please get the docs at the download site updated?

**Comment by rothja** [comment]
@DeanGross I apologize sincerely for the delay. The issue was incorrectly assigned originally, and we didn't catch it. Considering this has to do with Reporting Services, I think we need to get @maggiesMSFT to take a look. Thank you! #reassign:maggiesMSFT

**Comment by maggiesMSFT** [comment]
Hi, @DeanGross -- Thanks for your question and sorry for the delay!
Currently the Download page, https://www.microsoft.com/en-us/download/details.aspx?id=55949, doesn't list any versions.
It links to this page, https://docs.microsoft.com/en-us/sql/reporting-services/report-server-sharepoint/deploy-report-viewer-web-part, which states that it
APPLIES TO: SQL Server 2016 Reporting Services and later, Power BI Report Server, SharePoint 2013 & later
and doesn't apply to SharePoint Online
Is that clear enough?
Thanks!

**Comment by rothja** [comment]
@maggiesMSFT Thanks for the details on this. @DeanGross we are going to close out the issue, but please let us know if you have any other questions on this thread. Thank you!
