### ISSUE TITLE
SQL Server 2017 on Windows Server 2019 Datacenter/Standard/Essentials

### ISSUE THREAD

**Issue by nwkteng** [MicrosoftDocs/sql-docs#3630]
This page show SQL Server 2017 & prior but the table for SQL Server and Windows Server 2019 only mentions SQL Server 2019. How about SQL Server 2017 and compatibility with all the different editions of Windows Server 2019. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b411a1-f282-d77e-a497-83d08a963549
* Version Independent ID: f896a7f4-f08a-4b67-6d98-c14a0e1a969e
* Content: [Hardware and Software Requirements for Installing SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @nwkteng, thank you for contacting Microsoft! Please use the [version filter](https://docs.microsoft.com/en-us/sql/sql-server/sql-docs-navigation-guide?view=sql-server-ver15#version-filter) to choose SQL Server 2017 to display information about SQL Server 2017. 

![image](https://user-images.githubusercontent.com/32783170/69171836-8b40f280-0ab1-11ea-837e-a2633aa9386e.png)

However, you're right in that the version filter and name of the document in the TOC is causing confusion - there's actually a fix for this issue currently going through QA and should be live either this week or next. As such, I will proceed with closing out this Git issue but please feel free to comment should you need anything further. 

Thanks for reaching out to Microsoft to make our documentation better! Hope you have a wonderful rest of your day. 
Masha from the SQL Docs team
#please-close
