### ISSUE TITLE
Version information is lost

### ISSUE THREAD

**Issue by mverbaas** [MicrosoftDocs/sql-docs#3631]
It used to be more clearer in what version a specified function (or any other object) it was supported. The top of the page would explain for this specific function it is supported since 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f748e679-fde4-3cc7-4200-7b45adb74a21
* Version Independent ID: 6946f36e-4731-1ed9-365a-0085103a630e
* Content: [CONCAT_WS (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/concat-ws-transact-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-2014#feedback)
* Content Source: [docs/t-sql/functions/concat-ws-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/concat-ws-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by axellentx2** [comment]
I agree, it used to be very easy to determine the SQL Server versions that supported a specific T-SQL object/language construct. Now it seems you have to select each version of SQL Server in the top left menu to see if an error pops up to determine that a T-SQL object/language construct has not been documented for a specific version. But then the question is whether that also means that it's not supported by that specific SQL Server version... Please, please make this explicit once again!

**Comment by msebolt** [comment]
@mverbaas Thank you for the feedback.

Please refer to active issue https://github.com/MicrosoftDocs/sql-docs/issues/3616.
