### ISSUE TITLE
SSRS SharePoint Web Part Documentation Incorrect

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/sql-docs#3632]
The documentation outlined at https://docs.microsoft.com/en-us/sql/reporting-services/report-server-sharepoint/report-viewer-web-part-sharepoint-site?view=sql-server-ver15 appears to be incorrect.

First, the web part supports SharePoint 2013 and later per https://www.microsoft.com/en-us/download/details.aspx?id=55949 (which also needs to mention SharePoint 2019 and Windows Server 2019). In addition, this entire topic appears to be under the incorrect section, "Report Server SharePoint mode" and should be moved to the Native mode section.

**Comment by msebolt** [comment]
@tseward  Thank you for the feedback, assigning this to the author for review.

**Comment by maggiesMSFT** [comment]
Hi, @tseward -- good points! Moved the web part articles out of the SharePoint section of the TOC. Checking on version support.
Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @tseward -- updating the version support. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @tseward -- the update should be live tomorrow. Thanks again!
#please-close
