### ISSUE TITLE
Please Update Tools and Link for SQL 2019 RTM

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#3633]
Hi Guys, looks like the installer is still using CTP 2.3 - at least that's what it says when you get to the UAC prompt asking if you would like to allow this app to make changes to your device.  Would you mind updating for RTM now that 2019 is GA as of Nov 4?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da1f57b-a8fd-cca7-4cf0-9d594d365062
* Version Independent ID: 60c46780-6a03-7958-c77a-e7c94e3b9e85
* Content: [sqlcmd Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/sqlcmd-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlcmd-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@PrometheusRising1 Thank you for the feedback, assigning this to the author for review.

**Comment by markingmyname** [comment]
@PrometheusRising1,

I apologize for the delay.

Can I ask what are specifically you are clicking to get this result?

Is this the MsSqlCmdLnUtils.msi (https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15)?

Please let me know.

Thank you.

**Comment by markingmyname** [comment]
@PrometheusRising1,

Thanks for your comment.

I apologize for the delay.

Your contribution is much appreciated. 

A couple of questions: 

- Can I ask what are specifically you are clicking to get this result?
- Is this the MsSqlCmdLnUtils.msi (https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15)?

However, our team can only answer feedback related to the documentation. Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page or visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) page. If you have any feedback related to the documentation, please feel free to log in through this channel. We truly appreciate your contribution to our articles.

I hope this helps.

Thank you.

P. S.  I reached out to our engineering team to see if they can elaborate on your issue.  If I hear back, I will let you know.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by PrometheusRising1** [comment]
No, this is going through the normal GUI installer - double click on it and UAC pops up.  The UAC prompt indicates the RTM is CTP 2.3.  Just double click on the installer and look at the prompt when it asks you to elevate.

**Comment by Matteo-T** [comment]
I'm probably guilty of missing this (old) thread. The good news is that (finally!) we uploaded the ""RTM" branded MSIs to the download center and we are in the process of uploading the new DOCS pages with the updated fwlinks.

- [x86] https://go.microsoft.com/fwlink/?linkid=2142257
- [x64] https://go.microsoft.com/fwlink/?linkid=2142258

Note that your browser should be smart enough to download the MSI that matches your OS language, 
If you want a different language, just append something like &clcid=<LCID_IN_Hexadecimal>to the URLs above (e.g. for the x64 Italian MSI, you would use https://go.microsoft.com/fwlink/?linkid=2142258&clcid=0x410.
