### ISSUE TITLE
Associating a File Extension is case-sensitive

### ISSUE THREAD

**Issue by njtpremier** [MicrosoftDocs/sql-docs#3634]
The extension value when associating a file extension to a code editor, appears to be case-sensitive. If I have a file extension entered of "PRC", SSMS doesn't match this extension with "prc". However, the issue herein is that the SSMS doesn't allow both upper and lower to be entered in the options.

Using SQL Server Management Studio 14.0.17289.0 on Windows 10 Enterprise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a73ac8f6-4a93-40e5-3abd-08ca8fd206a2
* Version Independent ID: 2a557b9e-8f7e-16e7-492b-a7d285fad5a6
* Content: [Associate File Extensions to a Code Editor - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/scripting/associate-file-extensions-to-a-code-editor?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/ssms/scripting/associate-file-extensions-to-a-code-editor.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/associate-file-extensions-to-a-code-editor.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@njtpremier  Thank you for the feedback, we apologize for the issues.

To get this to the right people, please move this to either:

- [SQL Server User Voice](https://feedback.azure.com/forums/908035-sql-server)
- [SQL Server technical forums](https://social.msdn.microsoft.com/Forums/sqlserver/home)

The product team can then respond and provide both recommendations and updates on the issue.

Again we apologize for the inconvenience.
