### ISSUE TITLE
Windows 10 ODBC Data Sources

### ISSUE THREAD

**Issue by matt-k11** [MicrosoftDocs/sql-docs#3635]
Microsoft OLE DB Driver for SQL Server (MSOLEDBSQL) does not show up as a driver when creating Data Sources in the Windows 10 ODBC Data Sources app.  The Native Client does show up as a valid driver.  Additionally, the ODBC SQL Driver 17 is prone to 17832 connection errors when setting up an ODBC data source.  The Native Client does not generate the 17832 errors as often.  Please continue to provide a working, reliable driver for Windows 10 ODBC connections.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dce92f1-67d7-4a45-a4e7-bc4000c5b357
* Version Independent ID: eb2d7bfd-04b4-e008-a5f1-c1e197f811a0
* Content: [SQL Server Native Client - SQL Server](https://docs.microsoft.com/en-us/SQL/relational-databases/native-client/SQL-server-native-client?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/native-client/sql-server-native-client.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/native-client/sql-server-native-client.md)
* Product: **sql**
* Technology: **native-client**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by msebolt** [comment]
@matt-k11 Thank you for the feedback, we're sorry you're experiencing issues.

To get the issue to the right people, please move this to [SQL Server forums](https://social.msdn.microsoft.com/Forums/sqlserver/home) where the product team can have a chance to respond.

Again we apologize for any inconvenience.
