### ISSUE TITLE
Offline Installation Instructions is Unclear or Incomplete 

### ISSUE THREAD

**Issue by TeamSwarm** [MicrosoftDocs/sql-docs#3638]
Over the past four days, I've tried to install additional packages to the R Server, with no avail.

Our team has tried to install from a folder where copies of packages were located, attempting to use the CMD function, and installing through R itself. 

Help would be appreciated. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e48762-b66c-949c-4cc4-cf5f55463912
* Version Independent ID: 62671bd8-8edb-4276-e855-45284f9f6b32
* Content: [Get R package information - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/package-management/r-package-information?view=sql-server-2017)
* Content Source: [docs/advanced-analytics/package-management/r-package-information.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/package-management/r-package-information.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by garyericson** [comment]
@TeamSwarm - I assume you're following the instructions in the article, [Install new R packages - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/package-management/install-additional-r-packages-on-sql-server), specifically the section "[Add the package offline](https://docs.microsoft.com/en-us/sql/advanced-analytics/package-management/install-additional-r-packages-on-sql-server#add-the-package-offline)". What errors are you getting?

**Comment by TeamSwarm** [comment]
Hi Gary,

Thank you for reaching out.

In the perquisite, the installation of R and/or R Studio does not automatically point to the base R program that R Server uses. Specifically, I’ve noticed that in order to install R Server, a version of R gets installed. In our case 3.3.3 was installed. However, to execute many of the steps to install additional packages offline, R by itself needed to be installed as well. Therefore, after R is installed, it creates another instance of R, which is separate from the instance of R that the R Server uses. The result is that executing many of the instructions on the page do not actually affect R Server, just the separate instance of R.

Hope that makes sense, if not, I can clarify or restate the challenge further.

Thanks,

Sebastian Montagne

**Comment by garyericson** [comment]
@TeamSwarm - Thanks for the details, I think I understand better now. 

If you're using sqlmlutils (recommended for SQL 2019), then those functions basically reach over from the client computer and installing the package into the SQL instance. So the version of R on the client computer doesn't matter. 

If you're using 2017 or earlier, then the idea is to either use RevoScaleR which should handle the version issues, or run R from within the folder in the instance so you're using the correct version of R. If you're using RStudio, you can tell it to use that installation of R. I've just updated the articles for 2016/2017 and I hope it's clearer now (will probably be published on Monday). Let me know if it's still not clear or if you see an issue.

**Comment by garyericson** [comment]
#please-close, pending additional comments from @TeamSwarm
