### ISSUE TITLE
Reword "The base tables referenced in the view at the time the table is created."

### ISSUE THREAD

**Issue by samrueby** [MicrosoftDocs/sql-docs#3639]
I think the wording of the bulletpoint "The base tables referenced in the view at the time the table is created." is confusing. In fact, I'm having trouble understanding what it intends to say.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a452207-5ac2-1a41-c5b1-3baf085a79b4
* Version Independent ID: a590e66c-ed9f-4d80-1511-1864128d2e8e
* Content: [Create Indexed Views - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/views/create-indexed-views?view=sql-server-ver15)
* Content Source: [docs/relational-databases/views/create-indexed-views.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/views/create-indexed-views.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@samrueby Thank you for the feedback.

It likely means to say, `The base tables referenced in the view at the time the view is created`.

Assigning this to the author for review.

**Comment by rothja** [comment]
@samrueby Thanks for the question, and I agree that the statement is confusing. I agree with Matthew on the change, and I am making this in the article. When the change gets merged in for publishing, this PR will close. Thanks for your patience!
