### ISSUE TITLE
install on Mac running Catalina

### ISSUE THREAD

**Issue by dbrtly** [MicrosoftDocs/sql-docs#3647]
Having trouble installing on Mac running Catalina. Apparently there is a feature on by default to disallow software by unidentified developers. I keep getting a permission denied error. I suspect the installation problems are new feature may be related. Does the install script need to be tweaked?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3df6af-9ac8-bc57-93dc-29ff713c1d3b
* Version Independent ID: 7624e2cc-7aa9-40dd-4015-3371ea2ea0a2
* Content: [Download and install sqlpackage - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-ver15)
* Content Source: [docs/tools/sqlpackage-download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage-download.md)
* Product: **sql**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by dbrtly** [comment]
rereading. High Sierra was 2 years ago... My laptop came out after that. Will sqlpackage get an update?

**Comment by msebolt** [comment]
@dbrtly  Thank you for the question.

This could be related to your Mac permission settings.

Please refer to [Unidentified developer apps](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) for instructions on how to get this installed.

If not, please post further details to the issue below.

**Comment by msebolt** [comment]
Closing now, comment if there are issues.
