### ISSUE TITLE
missing UNIQUE keyword within INDEX part of CREATE TABLE definition

### ISSUE THREAD

**Issue by PiDiBi** [MicrosoftDocs/sql-docs#3648]
Hey,

there is missing possibility of creating UNIQUE INDEX like
```
CREATE TABLE [dbo].[Test](
        [Id] int IDENTITY(1,1) NOT NULL,
        [Name] nvarchar(255) NOT NULL,
     CONSTRAINT [PK_GlobalTest] PRIMARY KEY CLUSTERED ([Id] ASC),
     INDEX IX_GlobalNames_Name UNIQUE NONCLUSTERED ([Name]),
    )

```
this construction works and is supported by INDEX as defined in INDEX documentation
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver15

```
CREATE [ UNIQUE ] [ CLUSTERED | NONCLUSTERED ] INDEX index_name
    ON &lt;object&gt; ( column [ ASC | DESC ] [ ,...n ] )
    [ INCLUDE ( column_name [ ,...n ] ) ]
    [ WHERE &lt;filter_predicate&gt; ]
    [ WITH ( &lt;relational_index_option&gt; [ ,...n ] ) ]
    [ ON { partition_scheme_name ( column_name )
         | filegroup_name
         | default
         }
    ]
    [ FILESTREAM_ON { filestream_filegroup_name | partition_scheme_name | "NULL" } ]
  
[ ; ]

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be5dfc7-5496-f8ec-072f-81132fe92054
* Version Independent ID: 634e3c60-d717-92ba-dd93-e3773edf2816
* Content: [CREATE TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@PiDiBi please edit the file directly using the Edit link in this upper right-hand corner. 
Thank you.
Carl

**Comment by PiDiBi** [comment]
problem is that Microsoft.SqlServer.TransactSql.ScriptDom.dll doesn't support this construction either ..
but works when executed
so I need to find someone and follow up this problem to get it supported in Script DOM too

**Comment by CarlRabeler** [comment]
so this is a product bug / enhancement request - not a documentation issue, is this correct?

**Comment by PiDiBi** [comment]
I don't now, thsi construction works, but is not docmuented and when not documented, si it means ScriptDom is not using it. No idea what is correct way to document it (not only here but in way it's used ny other teams too)

**Comment by CarlRabeler** [comment]
OK - I am not clear what you are asking of the content team. Are you asking for an additional example be added to the CREATE TABLE topic?

**Comment by CarlRabeler** [comment]
PR Pending to add this to the syntax block
