### ISSUE TITLE
Guide on installing over SqlPS is wrong

### ISSUE THREAD

**Issue by Pxtl** [MicrosoftDocs/sql-docs#3650]
I do not have an existing install of SqlServer present.  "Get-Module SqlServer -ListAvailable" returns no results.  However, when I attempt to install SqlServer ps module, I still get the "This module 'SqlServer' may override the existing commands." because of SqlPs.

Trying to clobber them just seems to break both.

If I have to remove-module SqlPS for this to actually work, you need to explain that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdc5826c-d266-6f61-e1eb-b4f236d03dd9
* Version Independent ID: 4ab93d92-6a23-a0c0-2911-ce06e99dc5c5
* Content: [Download SQL Server PowerShell Module - SQL Server](https://docs.microsoft.com/en-us/sql/powershell/download-sql-server-ps-module?view=sql-server-ver15)
* Content Source: [docs/powershell/download-sql-server-ps-module.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/download-sql-server-ps-module.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@Pxtl -- Martin, thank you for your feedback.

@markingmyname -- Mark, please look into this issue 3650.

**Comment by Matteo-T** [comment]
The message you are seeing you are seeing is expected: it's basically PowerShell telling you that there is another module (SQLPS) that has cmdlets with the same name as the ones in the module you are installing (SQLServer).

What is not expected is that things gets broken: they two modules don't really share any binaries, so there should be no issues. However, you should be a little careful when using the cmdlets. I would recommend making sure that you always "Import-Module SQLServer" explicitly before you use it: this way PowerShell won't try to guess on your behalf. Another thing you could do, just for your user/session, is to hide the path to SQLPS from the module probing path by tweaking the environment variable "PSMODULE" before you start PowerShell: this would essentially make SQLPS invisible to your PowerShell session.

Let me know if that helps.

-Matteo

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
