### ISSUE TITLE
A job step must specify a proxy unless the creator of the job step is a member of the sysadmin fixed security role

### ISSUE THREAD

**Issue by gintarasg** [MicrosoftDocs/sql-docs#3655]
I was able to add a TSQL job step by executing msdb.dbo.sp_add_jobstep without specifying a proxy and i'm not sysadmin. Maybe, it's applicable only to SSIS, SSAS, etc. steps? I tested it on Microsoft SQL Server 2016 (SP2-CU1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 571ba504-da27-884c-e533-e4671b00ad66
* Version Independent ID: 87f89fc3-ba62-66ff-5651-3a8091ee6a3e
* Content: [sp_add_jobstep (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-add-jobstep-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-add-jobstep-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-add-jobstep-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by jameslee84** [comment]
This is not a issue at all. It can be fixed in a minute.. For more details, please contact me via email (james.lee84@mail.com)

**Comment by msebolt** [comment]
@gintarasg Thank you for the feedback.  

I think the wording of this is causing confusion...

Please refer to the statement on `proxy_name`:
```
If no proxy_id is specified, no proxy_name is specified, and no user_name is specified, the job step runs as the service account for SQL Server Agent.
```

You can still create the job step by default, however to run the SQL Server Agent requires sysadmin membership, see [Select account for SQL Server Agent Service](https://docs.microsoft.com/sql/ssms/agent/select-an-account-for-the-sql-server-agent-service?view=sql-server-ver15#sql-server-role-membership).

We'll add the rewording of this to our list of changes for the docs.
