### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by heidiweber** [MicrosoftDocs/sql-docs#3657]
A great explanation for import - thank you for that.
But export is somewhat rough and not helpful at all. 
At least please provide a link to somewhere that can help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b355db5-8821-7121-5aca-e9b6552187ee
* Version Independent ID: eb5be849-2bad-411b-fa0a-79add4bfcf81
* Content: [Bulk import & export of XML documents - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/examples-of-bulk-import-and-export-of-xml-documents-sql-server?view=sql-server-ver15#bulk_export_xml_data)
* Content Source: [docs/relational-databases/import-export/examples-of-bulk-import-and-export-of-xml-documents-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/examples-of-bulk-import-and-export-of-xml-documents-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@heidiweber  Thank you for the feedback, adding a link to the documentation.

For the time being, please refer to the [bcp](https://docs.microsoft.com/sql/tools/bcp-utility?view=sql-server-ver15#bulk-exporting-or-importing-sqlxml-documents) page for examples.
