### ISSUE TITLE
Incorrect stored procedure name

### ISSUE THREAD

**Issue by taddison** [MicrosoftDocs/sql-docs#3659]
In SQL2019 RTM (RTM-GDR) (KB4517790) - 15.0.2070.41) the referenced stored procedure `sys.sp_persistent_version_store_cleanup` does not exist.

The stored procedure `sys.sp_persistent_version_cleanup` _does_ exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d6d147-a7a7-cd75-13fb-4f4f72a16a15
* Version Independent ID: bb4f71b0-3103-06af-0560-e28860c752bc
* Content: [Accelerated database recovery - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/accelerated-database-recovery-management?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/accelerated-database-recovery-management.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/accelerated-database-recovery-management.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @taddison , thanks for contacting Microsoft and bringing this to our attention! Let me do some research to confirm and get back to you.

Thanks!
Masha from the SQL Docs team
