### ISSUE TITLE
Super hard to set or remove the bookmark for the current line CTRL+K, CTRL+K

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#3661]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/sql-docs.zh-tw/issues/117
the contributor is asking for a way to change the default keyboard shortcuts

The following comment was machine-translated.

@blueqoo commented 13 hours ago — with docs.microsoft.com
When using the left hand, ctrl and K are far away, the previous shortcuts are not very useful?
Why should I change it??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b1a74a-487c-8b7a-894c-454d5986ed1b
* Version Independent ID: 001c4d17-589b-ccd5-9887-52bead593258
* Content: [SQL Server Management Studio Keyboard Shortcuts - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/sql-server-management-studio-keyboard-shortcuts?view=sql-server-ver15#bookmark-keyboard-shortcuts)
* Content Source: [docs/ssms/sql-server-management-studio-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/sql-server-management-studio-keyboard-shortcuts.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@blueqoo  Thank you for the questions.

Does your keyboard not support a left-hand Ctrl key?  

Bookmark shortcuts are intentionally grouped for left-handed navigation, though this can be customized using the instructions at the top of the article.

**Comment by blueqoo** [comment]
left ctrl & k = distance is too far
When I use left hand can't touch the two word
left ctrl <----------------my left hand ------------------------------>K
left ctrl <----------------distance is too far------------------------->K

請問有辦法，設定為像之前一樣的SQL Server2000的快速鍵配置嗎?

Can I set Keyboard scheme -> SQL Server 2000???
bookmark shortcuts is ctrl+F2 is ok，vary good， why chage the setting????? 

Microsoft SQL Server Management Studio New version only visual studio 2010 compatible...

**Comment by msebolt** [comment]
@blueqoo  Apologies, what I meant was does your keyboard support a right-hand Ctrl key?

Recommended approach is Right Ctrl + K.

For SQL Server 2000 documentation, please see [this download](https://www.microsoft.com/download/details.aspx?id=51958).

**Comment by msebolt** [comment]
Closing the issue, please comment below if there are questions.
