### ISSUE TITLE
How can i download 18.2 or 18.3 English version SSMS??

### ISSUE THREAD

**Issue by leung85** [MicrosoftDocs/sql-docs#3663]
Where can i download  previous 18.2 or 18.3 English version SSMS??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@leung85 -- please see this article:  https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver15#download-ssms-182

**Comment by leung85** [comment]
@WilliamAntonRohm 
i click the link it only download Chinese version. I need other language

**Comment by WilliamAntonRohm** [comment]
@leung85 -- here's the English version link.  I believe if you replace "en-us" in this URL with a different culture, you should see that language's version to download.

- https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver15#download-ssms-182

Apologies for the delay in responding.
