### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by sumptersmartt** [MicrosoftDocs/sql-docs#3667]
The link https://support.microsoft.com/help/319723/how-to-use-kerberos-authentication-in-sql-server in the below line is broken.

More information on setting up Sql Server to authenticate using Kerberos can be found here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29dd905c-43f7-9045-4eee-c087e27f48e0
* Version Independent ID: 0e52d919-2745-c8c5-eb12-77b564f5e3d1
* Content: [Use Active Directory Authentication (Kerberos) - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-2017#feedback)
* Content Source: [docs/azure-data-studio/enable-kerberos.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/enable-kerberos.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @meet-bhagdev
* Microsoft Alias: **meetb**

**Comment by WilliamAntonRohm** [comment]
@sumptersmartt -- Sumpter, thank you for your feedback.  I am looking into this documentation.
