### ISSUE TITLE
"Explicitly adding, dropping, or altering indexes is not supported."

### ISSUE THREAD

**Issue by williamadba** [MicrosoftDocs/sql-docs#3673]
Not sure what the intent of this is, this sentence needs context, it's misleading and when broadly applied. You can create indexes on subscribers and publishers. This article has contradictory information: https://docs.microsoft.com/en-us/sql/relational-databases/replication/administration/frequently-asked-questions-for-replication-administrators?redirectedfrom=MSDN&view=sql-server-ver15: "Indexes can be added at the Publisher or Subscribers with no special considerations for replication"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7d71c9-38b9-beea-30b7-a4340158eb72
* Version Independent ID: 4704c064-38ad-4d47-6570-a74b9698f8e7
* Content: [Make Schema Changes on Publication Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/publish/make-schema-changes-on-publication-databases?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/replication/publish/make-schema-changes-on-publication-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/publish/make-schema-changes-on-publication-databases.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@williamadba Thank you for the feedback and apologies for the confusion.

The statement has been re-worded to better reflect index limitations.
