### ISSUE TITLE
Screenshots missing from the page

### ISSUE THREAD

**Issue by kirancobe** [MicrosoftDocs/sql-docs#3674]
Please include screenshot for each of the relevant and key steps of configuration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab9cce7b-b467-d3ab-3727-1b11cc1a563c
* Version Independent ID: 0cad315a-e2cf-2ee7-d62d-5cbdaefdf001
* Content: [Enable and configure FILESTREAM - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/blob/enable-and-configure-filestream?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/blob/enable-and-configure-filestream.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/blob/enable-and-configure-filestream.md)
* Product: **sql**
* Technology: **filestream**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@kirancobe Thank you for the feedback, assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
@kirancobe 

Thanks for this helpful recommendation.

We'll consider your recommendation. 

If you're looking for screenshots now, you can see some on other websites.

[Voice of the DBA](https://voiceofthedba.com/2012/03/07/enabling-filestream-in-sql-server-2012/)

[YouTube video from SolarWinds](https://www.youtube.com/watch?v=xhS1C6G2Fn8)

Thanks,
Mike
