### ISSUE TITLE
Incomplete doc

### ISSUE THREAD

**Issue by Dwayne75** [MicrosoftDocs/sql-docs#3676]
On 2019 brand new install I had to also do
sp_configure 'Agent XPs', 1
reconfigure with override

to get agent to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeba625e-8a51-f1ce-1b74-85fa2009a3e5
* Version Independent ID: f3d5c671-a891-e015-3c19-14a3bfbc15f4
* Content: [Install SQL Server Agent on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-sql-agent?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-setup-sql-agent.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-sql-agent.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@Dwayne75 Thank you for the feedback.

I have tried using a fresh install with Ubuntu and SQL Server 2019, see [here](https://docs.microsoft.com/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-linux-ver15) and can not reproduce this issue.

Please add further details on your setup below.

**Comment by msebolt** [comment]
Closing the issue, please comment below if there any questions.
