### ISSUE TITLE
Sample not working in my setup

### ISSUE THREAD

**Issue by Roadrunner67** [MicrosoftDocs/sql-docs#3678]
When mounting a volume claim in /var/opt/mssql, the original databases (master, model, msdbdata, and tempdb) are missing from the container, resulting in this output:

SQL Server 2019 will run as non-root by default.
This container is running as user root.
Your master database file is owned by root.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
2019-11-25 12:05:27.82 Server      Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64)
        Sep 13 2019 15:49:57
        Copyright (C) 2017 Microsoft Corporation
        Developer Edition (64-bit) on Linux (Ubuntu 16.04.6 LTS)
2019-11-25 12:05:27.83 Server      UTC adjustment: 0:00
2019-11-25 12:05:27.83 Server      (c) Microsoft Corporation.
2019-11-25 12:05:27.83 Server      All rights reserved.
2019-11-25 12:05:27.83 Server      Server process ID is 28.
2019-11-25 12:05:27.83 Server      Logging SQL Server messages in file '/var/opt/mssql/log/errorlog'.
2019-11-25 12:05:27.84 Server      Registry startup parameters:
         -d /var/opt/mssql/data/master.mdf
         -l /var/opt/mssql/data/mastlog.ldf
         -e /var/opt/mssql/log/errorlog
2019-11-25 12:05:27.84 Server      Error: 17113, Severity: 16, State: 1.
2019-11-25 12:05:27.84 Server      Error 87(The parameter is incorrect.) occurred while opening file '/var/opt/mssql/data/master.mdf' to obtain configuration information at startup. An invalid startup option might have caused the error. Verify your startup options, and correct or remove them if necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04922c04-a2da-186c-5946-1cc4d9a7447b
* Version Independent ID: 6e490885-cdd7-079a-0b3a-4688616b0954
* Content: [Deploy a SQL Server container in Kubernetes with Azure Kubernetes Services (AKS) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/tutorial-sql-server-containers-kubernetes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-sql-server-containers-kubernetes.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@Roadrunner67 Thank you for the feedback.

If you're running on a Mac, volume mounting is still unsupported, see https://github.com/microsoft/mssql-docker/issues/12.  

Please comment below any additional details as needed.

**Comment by Roadrunner67** [comment]
I am not running on Mac, I am running on Minikube under Windows.
I've come to believe that mssql is incompatible with ZFS, which in effect renders mssql unusable for Kubernetes Persistent Volumes.

**Comment by msebolt** [comment]
Thank you for the update.

Please refer to https://github.com/microsoft/mssql-docker/issues/13 for workarounds and/or current status and if this doesn't describe the issue comment below.

**Comment by Roadrunner67** [comment]
IMHO, the best lesson to learn from that thread and other similar threads was precisely put by @Mic92:

> But hey there is still postgresql/mariadb which will perform faster anyway on *bsd/linux.

**Comment by msebolt** [comment]
I'll assign this to the author for review of the steps.

**Comment by Roadrunner67** [comment]
I know this article is written for Azure AKS, but I would assume that others like myself would try this on MiniKube first.
In the meantime, I have tested it on a local microk8s running on Linux, and that works.
The article should as a minimum warn that mssql will not run on MiniKube PVs

**Comment by MikeRayMSFT** [comment]
@Roadrunner67 - thanks - I'm verifying with partners.

**Comment by MikeRayMSFT** [comment]
@Roadrunner67 - The point of the article is to demonstrate the scenario on Azure Kubernentes Service, as specified by the title. I've forwarded your concerns to program management.  Thank you for the submission.
