### ISSUE TITLE
PIP command is not functional

### ISSUE THREAD

**Issue by JamieL22** [MicrosoftDocs/sql-docs#3683]
'pip' is not recognized as an internal or external command,
operable program or batch file.

pip install --upgrade --upgrade-strategy only-if-needed c:\temp\sqlmlutils-0.7.2.zip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb790fba-2d19-b1a7-3935-6ec5f9207fcc
* Version Independent ID: f350cf6b-0fa8-6d76-8433-f3f752e62ecf
* Content: [Install Python packages with pip - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/package-management/install-additional-python-packages-on-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/advanced-analytics/package-management/install-additional-python-packages-on-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/package-management/install-additional-python-packages-on-sql-server.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by msebolt** [comment]
@JamieL22 Thank you for the feedback, please refer to [pip installation](https://pip.pypa.io/en/stable/installing/) for instructions on how to install.

The documentation has been updated with a link and is pending review.
