### ISSUE TITLE
Precision and scale seem to work on datetime2 datatype but no mention in documentation

### ISSUE THREAD

**Issue by salmanarshad2000** [MicrosoftDocs/sql-docs#3685]
Precision and scale seem to work on datetime2 datatype but there is no mention in documentation... simply "All other types = 0"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa0e861-d609-4b40-7d29-6a520760dd0a
* Version Independent ID: 8b0558ab-e2dc-188e-34d9-062970b1c50b
* Content: [SQL_VARIANT_PROPERTY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/sql-variant-property-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/sql-variant-property-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/sql-variant-property-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
@salmanarshad2000 - Thanks for the submission. We're processing an update.
