### ISSUE TITLE
Should differentiate from traditional session_id

### ISSUE THREAD

**Issue by AaronBertrand** [MicrosoftDocs/sql-docs#3687]
It's clear through investigation that session_id here (and in sysjobactivity) is distinct from session_id in sys.dm_exec_sessions et. al. 
While the naming collision is unfortunate, it's unlikely it will be corrected, so I think the docs should call it out explicitly so that people don't spin their wheels trying to establish some relationship that isn't valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b2f31b-22ea-1b5c-1ae5-5dd84ee1bd58
* Version Independent ID: 59c177b1-9d84-7c32-cee0-b6df419a534e
* Content: [dbo.syssessions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/dbo-syssessions-transact-sql?view=sql-server-2017&source=docs#feedback)
* Content Source: [docs/relational-databases/system-tables/dbo-syssessions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/dbo-syssessions-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by srutzky** [comment]
Just to add some verification for what Aaron found, executing the following:

```sql
EXEC msdb.sys.sp_help N'dbo.syssessions';
```

indicates that the `syssessions.session_id` is an `IDENTITY` column (hence, cannot be `@@SPID`).

Agreed: "session\_id" is definitely a poor choice for a name. &#x1F63F;

**Comment by WilliamAntonRohm** [comment]
@AaronBertrand, @srutzky -- Aaron, Solomon, thank you for your feedback.

@stevestein -- Steve, please look into this issue 3687.

**Comment by rothja** [comment]
@AaronBertrand Thanks for the feedback. @stevestein is not in the office. I apologize for the delay. @CarlRabeler could you please take a look at this? Thank you! #reassign:carlrabeler

**Comment by CarlRabeler** [comment]
PR pending
