### ISSUE TITLE
missing error numbers for availability groups

### ISSUE THREAD

**Issue by williamadba** [MicrosoftDocs/sql-docs#3688]
Need to add error numbers for example found in this doc and other locations:
https://download.microsoft.com/download/0/F/B/0FBFAA46-2BFD-478F-8E56-7BF3C672DF9D/Troubleshooting%20SQL%20Server%20AlwaysOn.pdf

Specifically would like to see some more detail on error numbers 41414 and 41418 which indicate a secondary availability group replica has become disconnected. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5973cd79-d024-6670-8b9f-d02d9824e8ec
* Version Independent ID: 9c7e4cd4-9bd7-16ad-83c0-9c114e5eec46
* Content: [Database engine events and errors - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-events-and-errors?view=sql-server-ver15#errors-31000-to-41400)
* Content Source: [docs/relational-databases/errors-events/database-engine-events-and-errors.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/errors-events/database-engine-events-and-errors.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@williamadba -- William, thank you for your feedback.

@MashaMSFT -- Masha, please look into this issue 3688.

**Comment by MashaMSFT** [comment]
Hi @williamadba , thank you for contacting Microsoft and for providing your feedback! You're right, it would be helpful to document these error messages. I have created an internal work item to track this work ([1652363](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1652363)). I will close out this Git Issue for the time being but please feel free to comment should you need anything further in the meantime.

Thanks again!
Masha from the SQL Docs team
