### ISSUE TITLE
Column CPU returning rounded values?

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#3689]
Data Column CPU appears to be returning values rounded to 1000.
Could you confirm this is intended behaviour please.
We are specifically looking where ERROR == 1
There is no mention of the typical 'returns microseconds, accurate to milliseconds' as in other BOL locations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 207f4d6b-9d6e-1d6b-cd64-f30c107d2dd5
* Version Independent ID: 9a737c53-1a35-422d-a790-64cfc68ab307
* Content: [SQL:BatchCompleted Event Class - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/event-classes/sql-batchcompleted-event-class?view=sql-server-ver15)
* Content Source: [docs/relational-databases/event-classes/sql-batchcompleted-event-class.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/event-classes/sql-batchcompleted-event-class.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@brettshearer -- Brett, thank you for your feedback.

@stevestein -- Steve, please look into this issue 3689.

**Comment by rothja** [comment]
@brettshearer Thanks for the feedback, but Steve is currently out of the office. I apologize for the delay. @CarlRabeler could you please take a look at this issue? Thank you! #reassign:carlrabeler

**Comment by CarlRabeler** [comment]
investigating

**Comment by CarlRabeler** [comment]
@brettshearer I can confirm that CPU time is in milliseconds. If you think additional language would add clarity, please suggest such language.
Thank you, Carl
