### ISSUE TITLE
Bug in Using Column Tracking code snippet

### ISSUE THREAD

**Issue by Szmiglo** [MicrosoftDocs/sql-docs#3690]
There is no comma in code snippet for "Using Column Tracking" section. There should be comma after "CT_ThumbNailPhoto_Changed" parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b26df5c-92a8-91e4-3fd1-e90d28157778
* Version Independent ID: ee0fa626-9318-7cf6-e27d-66d512fc2ee3
* Content: [Work with Change Tracking - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/work-with-change-tracking-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/track-changes/work-with-change-tracking-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/work-with-change-tracking-sql-server.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by Szmiglo** [comment]
created PR with fix :) #3691

**Comment by WilliamAntonRohm** [comment]
@Szmiglo -- Szmiglo, thank you for finding this and providing a fix.

@Jak-MS -- Jak, please review Szmiglo's PR #3691 

cc @MightyPen as the writer

**Comment by MightyPen** [comment]
I Reviewed and Approved PR #3691 .
I sent email to TechDocPRs saying the PR can now be merged.
I believe this Issue #3690 can now be Closed, as Fixed. (fix will appear live on Docs in a couple days).

Thank you for submitting this Issue. We hope to hear from you again.
