### ISSUE TITLE
Typo in the First Example

### ISSUE THREAD

**Issue by edvaldocastro** [MicrosoftDocs/sql-docs#3692]
Below sentence is not in accordance with the image

Current:
A synchronous secondary replica on COMPUTER03

Should be:
An Asynchronous secondary replica on COMPUTER03

Also, the Script to create the Availability Group
'COMPUTER03' WITH   
         (  
         ENDPOINT_URL = 'TCP://COMPUTER03.<domain>.<tld>:5022',  
         AVAILABILITY_MODE = **SYNCHRONOUS_COMMIT,**  

Either the Image or aforementioned Text is wrong 

![image](https://user-images.githubusercontent.com/9415915/69621808-affc1380-1037-11ea-9453-7da1e1ac1e23.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 948a3def-7af7-e4dc-e14e-c49613ffc2bb
* Version Independent ID: 7d0b6654-eb60-1640-10e1-1f00b6245cf4
* Content: [SQL Server secondary to primary replica read/write connection redirection-Always On Availability Groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/secondary-replica-connection-redirection-always-on-availability-groups?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/secondary-replica-connection-redirection-always-on-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/secondary-replica-connection-redirection-always-on-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@edvaldocastro -- Edvaldo, thank you for your observations.

@MikeRayMSFT -- Mike, please look into this issue 3692.

**Comment by MikeRayMSFT** [comment]
@edvaldocastro - thank you for reviewing this and commenting on it. We'll take a look.

**Comment by MashaMSFT** [comment]
Thanks again for contacting Microsoft!  We've submitted a documentation change based on your suggestion, and it should be live at this point. I will proceed with closing out this Git Issue, but please feel free to commend should you need anything further. 

Thanks again and hope you have a wonderful rest of your day! 
Masha from the SQL Docs team
