### ISSUE TITLE
Disabling instant file initialization will increase allocation times for data files.

### ISSUE THREAD

**Issue by M-Damaschke** [MicrosoftDocs/sql-docs#3694]
Well that is not a correct information if I compare that statement with the following link to "File initialization takes a long time for SQL Server database-related operations." LINK: https://support.microsoft.com/en-us/help/2574695/file-initialization-takes-a-long-time-for-sql-server-database-related
PLEASE COULD YOU CLARIFY THAT. Thanks in advance! Best regards ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ff457d-65be-2e16-7460-8dc5c77286a7
* Version Independent ID: 69640716-d7da-dafa-3028-0534181f4645
* Content: [Database Instant File Initialization - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-instant-file-initialization?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/databases/database-instant-file-initialization.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/database-instant-file-initialization.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@M-Damaschke -- thank you for your feedback.

@stevestein -- please look into this issue 3694.

**Comment by rothja** [comment]
@M-Damaschke Thanks for the feedback. I apologize for the delay, but Steve is currently out of the office. @CarlRabeler could you please take a look at this issue? Thank you!

**Comment by mcbits** [comment]
I think the docs are correct. Disabling instant file initialization means the data will be overwritten with zeroes, which will increase the allocation time.

Maybe it's confusing because "disable instant" (i.e. disable no-zeroes) is kind of a double negative.

**Comment by stevestein** [comment]
@M-Damaschke - Thanks for the feedback!

The statement in the doc is correct. Can you clarify which statement in [the support document](https://support.microsoft.com/en-us/help/2574695/file-initialization-takes-a-long-time-for-sql-server-database-related) that appears to conflict with the doc?

Thanks

**Comment by stevestein** [comment]
#please-close
