### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by fatherjack** [MicrosoftDocs/sql-docs#3695]
Limitations paragraph
first bullet point.
"Basic availabililty groups" should be "Basic Availability Groups"
last bullet point
"can not" should be "cannot"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32bb0e7a-a91c-6ccd-bf16-5118801d5612
* Version Independent ID: 84eb1614-0e30-e116-9dd2-34a3db7c6b5d
* Content: [Basic availability groups for a single database - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups?view=sql-server-ver15&source=docs)
* Content Source: [docs/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@fatherjack -- thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

**Comment by MashaMSFT** [comment]
Hi @fatherjack, thank you for your feedback! Just so you know, you have the ability to modify the documentation yourself :) This will add you as a public contributor to our documentation!

In case you're interested, here are the steps:
1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Name your file change and provide a description, if necessary
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page

You can find more information about that here: https://aka.ms/editsqldocs

However, we're happy to make the changes on your behalf as well! Just passing this along as an FYI.

Thanks!
Masha from the SQL Docs team
