### ISSUE TITLE
Constant Folding in Q.O.: CLR UDFs 𝑐𝑎𝑛, while NTEXT and XML output types 𝑤𝑜𝑛’𝑡

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#3696]
<sup>(Q.O. = Query Optimizer)</sup>

There are two mistakes in the [Constant Folding](https://docs.microsoft.com/en-us/sql/relational-databases/query-processing-architecture-guide#ConstantFolding) section:

1. There is a "note" that states:

    > If the output type of the folding process is a large object type (text, image, nvarchar(max), varchar(max), or varbinary(max)), then SQL Server does not fold the expression.

    That list of datatypes is missing both `NTEXT` and `XML`.

2. Under "**Nonfoldable Expressions**", it lists:

    > * User-defined functions (both Transact-SQL and CLR)

    That _was_ true until SQL Server 2012. Starting in that version (and still true as of SQL Server 2017), the following two items are foldable _if_ they do not do any data access:

    * Deterministic scalar-valued CLR user-defined functions
    * Deterministic methods of CLR user-defined types

    Please see [Behavior Changes in SQL Server 2012: Constant Folding for CLR User-Defined Functions and Methods](https://docs.microsoft.com/en-us/sql/database-engine/behavior-changes-to-database-engine-features-in-sql-server-2014#constant-folding-for-clr-user-defined-functions-and-methods)

Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45a7c96a-9d41-83e8-0ae8-b73fff390f48
* Version Independent ID: 1a880308-6a3b-6944-6428-1331801b327a
* Content: [Query Processing Architecture Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/query-processing-architecture-guide?view=sql-server-ver15#ConstantFolding)
* Content Source: [docs/relational-databases/query-processing-architecture-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/query-processing-architecture-guide.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@srutzky Thank you for the feedback, assigning this to the author for review.

**Comment by srutzky** [comment]
Please see PR #3698 for details and demo code 😺

**Comment by rothja** [comment]
@srutzky Thanks for sharing this feedback, and also for going above and beyond by creating the PR for the change. I am reviewing this with our product team before merging and closing both. Thank you for your patience!

**Comment by rothja** [comment]
@srutzky Thanks, again, for submitting the PR with the suggested changes. I've reached out to Pedro yesterday to ask him to review your suggestions, as we need his input. Thanks for your patience.

**Comment by rothja** [comment]
I see in the associated PR that the changes are in the docs now. Closing this issue.
