### ISSUE TITLE
Wrong title?

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#3699]
To recompile a stored procedure by using the WITH RECOMPILE option

This appears twice - I think for the second occurrence you mean 'to recompile when executing a stored procedure...'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19bbbbc-0e34-a78c-3f14-dfbc0fbf536c
* Version Independent ID: 8f236ed6-fc5a-8a6e-9b16-6a925bba0b70
* Content: [Recompile a Stored Procedure - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/recompile-a-stored-procedure?view=sql-server-ver15)
* Content Source: [docs/relational-databases/stored-procedures/recompile-a-stored-procedure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/stored-procedures/recompile-a-stored-procedure.md)
* Product: **sql**
* Technology: **stored-procedures**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@brettshearer Thank you for the feedback.

The documentation has been updated and is pending review.
