### ISSUE TITLE
Redundant "Use AdventureWorks2012"

### ISSUE THREAD

**Issue by maziarrezaei** [MicrosoftDocs/sql-docs#3700]
On examples D,E,F,G, the table is defined as part of the example. "Use AdventureWorks2012" is redundant, and in-fact, misleading since reader thinks having the AdventureWorks2012 database is sufficient to run the example were actually he/she need to add the lines in example D to create the table variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e25ceb80-19cf-5c95-cb88-9affc2c6abc3
* Version Independent ID: 3c6696e6-ec06-0fe5-5e27-07aa961c2457
* Content: [WITH common_table_expression (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/queries/with-common-table-expression-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/with-common-table-expression-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@maziarrezaei Thank you for the feedback and apologies for the confusion.

The documentation has been updated and is pending review.
