### ISSUE TITLE
Tooltip tip

### ISSUE THREAD

**Issue by pavelsagittarius** [MicrosoftDocs/sql-docs#3702]
Hello, 
it would be nice to display a tooltip message over links containing bacic definition from target page (like on Wikipedia) so I can remember what it is without having to open the link. For example this page contains links to another six pages, so the tooltip could contain this: 
* RANK - "Returns the rank of each row within the partition of a result set. The rank of a row is one plus the number of ranks that come before the row in question.
ROW_NUMBER and RANK are similar. ROW_NUMBER numbers all rows sequentially (for example 1, 2, 3, 4, 5). RANK provides the same numeric value for ties (for example 1, 2, 2, 4, 5)."
* NTILE - "Distributes the rows in an ordered partition into a specified number of groups. The groups are numbered, starting at one. For each row, NTILE returns the number of the group to which the row belongs."
* DENSE_RANK - "This function returns the rank of each row within a result set partition, with no gaps in the ranking values. The rank of a specific row is one plus the number of distinct rank values that come before that specific row."
* ROW_NUMBER - "Numbers the output of a result set. More specifically, returns the sequential number of a row within a partition of a result set, starting at 1 for the first row in each partition.
ROW_NUMBER and RANK are similar. ROW_NUMBER numbers all rows sequentially (for example 1, 2, 3, 4, 5). RANK provides the same numeric value for ties (for example 1, 2, 2, 4, 5)."
* Built-in Functions (Transact-SQL) - "Learn about the categories of built-in functions you can use with SQL databases. You can use the built-in functions or create your own user-defined functions."
* OVER Clause (Transact-SQL) - "Determines the partitioning and ordering of a rowset before the associated window function is applied. That is, the OVER clause defines a window or user-specified set of rows within a query result set. A window function then computes a value for each row in the window. You can use the OVER clause with functions to compute aggregated values such as moving averages, cumulative aggregates, running totals, or a top N per group results."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cf3d6dc-3bd5-b62b-0398-489f6db9c9f9
* Version Independent ID: 79e4d7d4-9f45-99d8-50ed-08e72483c533
* Content: [Ranking Functions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/ranking-functions-transact-sql?view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/t-sql/functions/ranking-functions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/ranking-functions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@pavelsagittarius Thank you for the feedback.

Tool tips are not yet included in the Markdown rendering syntax we use to write these articles.

Please move this issue to the [MicrosoftDocs repo](https://github.com/MicrosoftDocs/feedback/issues) for a response from the Docs team.

**Comment by pavelsagittarius** [comment]
It looks like I can´t move issues. Can you do it for me, please?

**Comment by msebolt** [comment]
@MikeRayMSFT Can you find someone with access to transfer this issue?

**Comment by MikeRayMSFT** [comment]
I also cannot. Checking on my options.

**Comment by MikeRayMSFT** [comment]
I manually created it.

**Comment by pavelsagittarius** [comment]
Thanks
