### ISSUE TITLE
SQL Agent

### ISSUE THREAD

**Issue by Klabbo** [MicrosoftDocs/sql-docs#3704]
In version 18.4 when you connect to a server and SQL Agent.  When you should edit an excisting job and try to Edit in steps it hangs for a really long time(minutes).

**Comment by msebolt** [comment]
@Klabbo  Thank you for the feedback.

Please see if any of [these issues](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/home?category=sqlserver&forum=sqlintegrationservices%2Csqldatamining%2Csqlreportingservices%2Csqlanalysisservices%2Csqltools%2Ctransactsql%2Csqlnetfx%2Csqldataaccess%2Csqlsmoanddmo%2Csqlxml%2Csqlreplication%2Csqlservicebroker%2Csqlsecurity%2Csqldatabaseengine%2Csqldocumentation%2Csqlsetupandupgrade%2Csqldisasterrecovery%2Csqlnotificationservices%2Csqlce%2Csqlgetstarted%2Csqldatabasemirroring%2Csqlexpress%2Csqldriverforphp%2Csqldatawarehousing%2Csqlsearch%2Csqlspatial%2Csqlserversamples%2Cdatabasedesign%2Csqlservermigration%2Csqlmds%2Csqlkjappmsmgmt%2Csqlkjpowerpivotforexcel%2Csqlkjpowerpointforsharepoint%2Csqlkjmanageability%2Csqldru%2Csqldataqualityservices%2Cssdt%2Csqlinmemory&filter=&sort=relevancedesc&brandIgnore=true&searchTerm=agent+hangs) addresses the problem and then vote and/or comment to increase the visibility to the product team.

**Comment by msebolt** [comment]
Closing the issue, please comment below if there any questions.
