### ISSUE TITLE
Cannot find Microsoft KB Article number 914847 referenced on this page.

### ISSUE THREAD

**Issue by discaddict** [MicrosoftDocs/sql-docs#3705]
After the caution box on permission chaining there is a reference to a KB article...
For more information, see the Microsoft KB Article number 914847.

Searching the web I can find other references to the article but not the article itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c65a5cd0-c3a5-3a2f-86bd-37f751ff034c
* Version Independent ID: db167ad1-8603-a8f9-1a63-c04388515dfe
* Content: [GRANT Schema Permissions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-schema-permissions-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/grant-schema-permissions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/grant-schema-permissions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@discaddict Thank you for the feedback.

An update to the documentation is pending.
