### ISSUE TITLE
> I'm an Outlook Web App end user (thus I have no control over my site's Exchange Server configuration). Version information may be obtainable, but I don't want to call our support staff over this minor issue if it isn't really necessary. "?" -> "Privacy notice" -> "Product Feedback" led me here.

### ISSUE THREAD

**Issue by corebase22** [MicrosoftDocs/sql-docs#3708]
> I'm an Outlook Web App end user (thus I have no control over my site's Exchange Server configuration). Version information may be obtainable, but I don't want to call our support staff over this minor issue if it isn't really necessary. "?" -> "Privacy notice" -> "Product Feedback" led me here.
> When I browse the settings in the General section (from "My account" to "Text messaging") without making any changes, I'm allowed to leave every tab except "Region and time zone settings" where I'm asked to either Save or Discard a change I didn't knowingly make (or Cancel the action). It appears the "Rename default folders so their names match the specified language" checkbox is checked automatically as I enter the tab, because when I manually uncheck it, the Save and Discard icons turn light gray and the exit alert goes away. When I reenter the tab, the checkbox is checked again, rinse and repeat.
> I'm using Firefox under Linux and I have my OWA interface language set to English (in spite of being in Sweden). Checking with a colleague who uses the Swedish interface, he was able to reproduce the behaviour using Firefox, Edge and (I think) Google Chrome under Microsoft Windows. Another colleague was unable to reproduce it, but we didn't do any substantial comparison of environment factors.
> Is it a bug or a misunderstood feature? Seems unintuitive to me to be asked to confirm a change I'm not aware of, especially one that is likely to have a permanent effect, though my default folders seem to be in English already (Drafts, Inbox etc).

translate.

_Originally posted by @corebase22 in https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/373#issuecomment-559357384_

**Comment by corebase22** [comment]
- [ ] https://support.google.com/chrome/thread/3595504?msgid=3595504

**Comment by msebolt** [comment]
@corebase22 Thank you for the feedback.

Since this doesn't involve SQL Server please either request the issue be re-opened in the **Office Docs** or use [Outlook support](https://support.office.com/outlook).

**Comment by dstrome** [comment]
@msebolt - I'm one of the OfficeDocs admins...you can close this issue. The text was copied from an old issue in one of our repos.
