### ISSUE TITLE
Manual failover without data loss not working in SQL2019

### ISSUE THREAD

**Issue by danvalero** [MicrosoftDocs/sql-docs#3709]
Hi
I am following the instructions for Manual failover without data loss and it fails in SQL 2019, however, it works correctly in SQL 2017.
I created a Read Scale Only Availablity Group with two instances on linux, and it fails.  I created a Read Scale Only Availablity Group with one instances on linux and another in Windows and fails with the same error.

I get the error when I execute: ALTER AVAILABILITY GROUP [ag1]  SET (ROLE = SECONDARY);
and it does make sense to me as it mention the AG resouce that does not exsits as there is no cluster in place.

The message is: 
Msg 41104, Level 16, State 5, Line 1
Failover of the availability group to the local replica failed because the availability group resource did not come online due to a previous error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64a1097e-f103-c12f-8c89-963258159dfd
* Version Independent ID: 7bd741b1-5027-f38c-17bb-8199dacbf763
* Content: [Configure a SQL Server Availability Group for read-scale on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-configure-rs?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-availability-group-configure-rs.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-availability-group-configure-rs.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@danvalero Thank you for the feedback, we're sorry for any issues you're experiencing.

This issue has been supposedly fixed and documented [here](https://support.microsoft.com/en-ph/help/4492604/fix-manual-failover-between-forwarder-and-secondary-replica-fails-with).

If you can confirm you've adhered to the solution's requirements and the issue still remains, please start a ticket [here](https://social.msdn.microsoft.com/Forums/sqlserver/home?category=sqlserver) with the product team and link back to this issue.

**Comment by danvalero** [comment]
Thanks,
The issue is not the one describe in the link you provided.
I opened a ticket as instrcuted: https://social.msdn.microsoft.com/Forums/en-US/752845be-5cab-47ff-b193-2d7974404644/availablity-group-for-read-scale-manual-failover-without-data-loss-not-working-in-sql2019?forum=sqldisasterrecovery

**Comment by msebolt** [comment]
Closing the issue since the product team has started dialogue, please comment below if there any questions.

**Comment by goranschwarz** [comment]
@danvalero , @msebolt 
Has this been resolved, or did you find any solution or workaround for it!
I have the same issue... and desperately need a solution!

I'm on: Microsoft SQL Server 2019 (RTM-CU3) (KB4538853) - 15.0.4023.6 (X64) Mar 4 2020 00:59:26 Copyright (C) 2019 Microsoft Corporation Standard Edition (64-bit) on Linux (CentOS Linux 7 (Core)) <X64>

**Comment by sbeygi** [comment]
I'm also experiencing the same issue;

It probably doesn't matter but I'm using mcr.microsoft.com/mssql/server:2019:latest with docker and have configured an AG with 3 replicas
