### ISSUE TITLE
optimize_for_sequential_key is not available for sql server before 2019 but present in documentation

### ISSUE THREAD

**Issue by alexcom** [MicrosoftDocs/sql-docs#3710]
Column sys.indexes.optimize_for_sequential_key is present in documentation at least for servers 2016 and 2017. But it is absent in 2017 database and article below  states this column appeared in version 2019.
https://techcommunity.microsoft.com/t5/SQL-Server/Behind-the-Scenes-on-OPTIMIZE-FOR-SEQUENTIAL-KEY/ba-p/806888

Please fix misleading documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78d65932-6ae2-4a7d-6f5b-063a744c476b
* Version Independent ID: 3a20a4f3-b7f8-a6b1-a4d8-bdcc95ce45b4
* Content: [sys.indexes (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-indexes-transact-sql?view=sql-server-2016#feedback)
* Content Source: [docs/relational-databases/system-catalog-views/sys-indexes-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-indexes-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@alexcom  Thank you for the feedback.

The documentation has been updated and is pending review.
