### ISSUE TITLE
SQL Compare Extension v1.0.0

### ISSUE THREAD

**Issue by kethahel99** [MicrosoftDocs/sql-docs#3711]
Cannot download the extension, even manually the source link give error:

&lt;Error&gt;
&lt;Code&gt;BlobNotFound&lt;/Code&gt;
&lt;Message&gt;
The specified blob does not exist. RequestId:cb3a2350-001e-0065-809c-a65c5f000000 Time:2019-11-29T10:02:18.9986710Z
&lt;/Message&gt;
&lt;/Error&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710e924f-bb4e-5e71-90db-04c6eb1b8c22
* Version Independent ID: 1a1ef45b-a9ff-dc61-fa22-19708f9c96cb
* Content: [Schema Compare extension - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/schema-compare-extension?view=sql-server-ver15#feedback)
* Content Source: [docs/azure-data-studio/schema-compare-extension.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/schema-compare-extension.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by msebolt** [comment]
@kethahel99 Thank you for the feedback, assigning this to the author for review.

You can also refer to the [azuredatastudio](https://github.com/microsoft/azuredatastudio/issues) repo.

**Comment by hannahqin** [comment]
Hi @kethahel99, are you still having issues installing the Schema Compare extension? And are you experiencing installation problems in-app or on this GitHub page? https://github.com/microsoft/azuredatastudio/wiki/List-of-Extensions

**Comment by yualan** [comment]
Hi @msebolt, let's close this issue and reopen once there is additional follow up from user.

**Comment by kethahel99** [comment]
Solved, thank you. Downloaded newer release
