### ISSUE TITLE
problem with system_user on Azure SQL Database

### ISSUE THREAD

**Issue by HenrikStaunPoulsen** [MicrosoftDocs/sql-docs#3712]
when using system_user on an Azure SQL Database, and executing at stored procedure that contain "execute as", I get this message:
Msg 40529, Level 16, State 1, Procedure myTrigger, Line 88 [Batch Start Line 0]
Built-in function 'SUSER_SNAME' in impersonation context is not supported in this version of SQL Server.

I have been hunting all over for any suser_sname() in my database, but the real cause was System_name.
Please improve the error_message, and add a warning to the documentation that system_user does not work with "Execute as"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b25f866-3dc7-7a19-163e-1ca4c1cf3118
* Version Independent ID: e946a621-3bad-6f0b-711f-d43882fcfce9
* Content: [SYSTEM_USER (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/system-user-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/system-user-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/system-user-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@HenrikStaunPoulsen Thank you for the feedback, assigning this to the author for review.

**Comment by VanMSFT** [comment]
@HenrikStaunPoulsen - Hi! Thank you for submitting this issue. I apologize for the delay. I added a remark that you cannot EXECUTE AS a SYSTEM_USER. We appreciate your help in improving our documentation. The doc updates should go live today.

**Comment by HenrikStaunPoulsen** [comment]
well, this is still not fixed properly.
If I run this procedure:

```
go
create procedure dbo.testhsp
**with execute as owner**
as BEGIN
   select user_name(), suser_sname(), suser_name(), system_user
end
go

exec dbo.testhsp

```
Then I get the error:
Msg 40529, Level 16, State 1, Procedure dbo.testhsp, Line 4 [Batch Start Line 14]
Built-in function 'SUSER_SNAME' in impersonation context is not supported in this version of SQL Server.
I have also tested this on Microsoft SQL Server 2019 (RTM-CU1), where it works fine.

I think you need to update the docs for suser_sname() to state that it is not supported on Azure SQL Database.

**Comment by HenrikStaunPoulsen** [comment]
also, please see https://docs.microsoft.com/en-us/sql/t-sql/functions/original-login-transact-sql?view=sql-server-ver15 for the correct explanation.

**Comment by VanMSFT** [comment]
Thanks, @HenrikStaunPoulsen! I'm updating the rest of the documents with a note to say that the Execute AS statement is not supported on Azure SQL DB.
