### ISSUE TITLE
How to delete

### ISSUE THREAD

**Issue by albertomute** [MicrosoftDocs/sql-docs#3714]
How to delete recovery pending databases

**Comment by msebolt** [comment]
@albertomute Thank you for the question.

Please refer to [this post](https://dba.stackexchange.com/questions/11175/how-do-you-stop-take-offline-and-delete-a-sql-server-database-in-recovery) and comment below if there are issues.

**Comment by msebolt** [comment]
Closing the issue, please comment below if there any questions.
