### ISSUE TITLE
Column CPU unit could be microsecond?

### ISSUE THREAD

**Issue by matriarchvip** [MicrosoftDocs/sql-docs#3721]
Column CPU in all other extended events are microsecond except this one. In real data it actually seems like microsecond.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 207f4d6b-9d6e-1d6b-cd64-f30c107d2dd5
* Version Independent ID: 9a737c53-1a35-422d-a790-64cfc68ab307
* Content: [SQL:BatchCompleted Event Class - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/event-classes/sql-batchcompleted-event-class?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/event-classes/sql-batchcompleted-event-class.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/event-classes/sql-batchcompleted-event-class.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@matriarchvip Thank you for the feedback, assigning this to the author for review.

@stevestein

**Comment by rothja** [comment]
@matriarchvip Sorry for the long delay in replying, and thanks for the question. In doing some research from the community experience with this column (see [https://stackoverflow.com/questions/976628/sql-profiler-cpu-duration-units](https://stackoverflow.com/questions/976628/sql-profiler-cpu-duration-units)), it seems that there might be a difference between what you see in SQL Server Profiler (milliseconds) and what you see in exported data (microseconds). There also might be a UI setting to adjust this.

I think the answer is spelled out in a different article: [SQL Trace](https://docs.microsoft.com/en-us/sql/relational-databases/sql-trace/sql-trace). It says:

|Data column|Column number|Description|  
|-----------------|-------------------|-----------------|  
|**Duration**|13|The duration (in microseconds) of the event.<br /><br /> The server reports the duration of an event in microseconds (one millionth, or 10<sup>-6</sup>, of a second) and the amount of CPU time used by the event in milliseconds (one thousandth, or 10<sup>-3</sup>, of a second). The [!INCLUDE[ssSqlProfiler](../../includes/sssqlprofiler-md.md)] graphical user interface displays the **Duration** column in milliseconds by default, but when a trace is saved to either a file or a database table, the **Duration** column value is written in microseconds.|  

At this time, I am going to close this issue, but please let me know if this does not address your concern. Thanks!
