### ISSUE TITLE
Ubuntu 19.10 Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection. 

### ISSUE THREAD

**Issue by hdisma** [MicrosoftDocs/sql-docs#3722]
Im getting this error when i'm trying to connecto to mssql server on ubuntu 19.10 :
`Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection.`

**Comment by msebolt** [comment]
@hdisma  Thank you for the question.

This could be related to a recent SSL patch, please see if [this post](https://stackoverflow.com/questions/57265913/error-tcp-provider-error-code-0x2746-during-the-sql-setup-in-linux-through-te) resolves your issue.

**Comment by hdisma** [comment]
Hi @msebolt 

- After trying this solution, everything works like a charm. Thank you so much, you saved my day! :smile:

**Comment by msebolt** [comment]
Great, it's good to know this is working again.  Thank you for contacting Microsoft.
