### ISSUE TITLE
Code mistake

### ISSUE THREAD

**Issue by Gid8** [MicrosoftDocs/sql-docs#3723]
There is a format problem in the first code block of the Examples section, the first apostrophe isn't getting picked up as the start of a string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5132e6b6-4c94-d72c-4b3d-31a047402731
* Version Independent ID: 448308aa-3277-40b7-db76-ac3e9a380bd5
* Content: [@@ERROR (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/error-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/error-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/error-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@Gid8  Thank you for the feedback.

The documentation has been updated and is pending review.
