### ISSUE TITLE
Certificate Requirements for TLS in a SQL Failover Cluster

### ISSUE THREAD

**Issue by arcus4** [MicrosoftDocs/sql-docs#3724]
when the import of a server certificate for TLS in a SQL Failover Cluster as described here, we found that it would be helpful to know that a certificate' s subject should include the SQL Server instance name (in a Failover Cluster). You will have to provide any Failover Cluster object (FQDN) name in the certificate' s SubjectAlternateNames (SAN), this includes the FQDN of DTC and Cluster Nodes as well as any SQL Server instance name.
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa20275-e415-5531-3ef4-7472d859753b
* Version Independent ID: cc1346a6-9336-91ba-bcff-9fff79847c35
* Content: [Enable Encrypted Connections to the Database Engine - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@arcus4  Thank you for the feedback, assigning this to the author for review.

**Comment by VanMSFT** [comment]
@arcus4 - Hi Jan! Thanks for these suggestions! We really appreciate your assistance with our documentation. There's no need to add the SQL Server Instance Name to the certificate Alternate Name. The Cluster Virtual Name as the CN should be enough. An additional requirement for cluster node instances is that the thumbprint of the certificate needs to match on each server. We are working on an article on how to configure an SSL/TLS certificate for SQL Server. For now, we will close this Issue. Thanks again for your feedback!

**Comment by rjk** [comment]
@VanMSFT - is that article written now? I'm struggling to find docs on exactly what the CN & Alternate Name actually needs to be for SQL Failover Clusters.

**Comment by VanMSFT** [comment]
Hi @rjk, CN for a cluster setup is mentioned several times in the article referenced.

https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine#about

![image](https://user-images.githubusercontent.com/40007119/161775027-33094e25-a64a-4fab-af83-1fa6282c7af7.png)


![image](https://user-images.githubusercontent.com/40007119/161775101-ada584e2-7c69-4588-ba44-8b485c0fdc0e.png)
