### ISSUE TITLE
Problem with SQL Server 2019 RTM

### ISSUE THREAD

**Issue by ghotz** [MicrosoftDocs/sql-docs#3727]
Not sure whether is a bug, but as of SQL Server 2019 RTM defining an external data source to Azure SQL Database like this:

```
CREATE EXTERNAL DATA SOURCE AzureSQLDB
WITH (
	LOCATION = N'sqlserver://polybase.database.windows.net'
,	CREDENTIAL = AzureCredential
);
```
result in the following error being risen when later trying to define an External Table:
```
Msg 105082, Level 16, State 1, Line 72
105082;Generic ODBC error: [Microsoft][ODBC Driver 17 for SQL Server]Database is invalid or cannot be accessed .
```

The workaround is to specify the database name in `CONNECTION_OPTIONS` like this:
```
CREATE EXTERNAL DATA SOURCE AzureSQLDB
WITH (
	LOCATION = 'sqlserver://polybase.database.windows.net'
,	CREDENTIAL = AzureCredential
,	CONNECTION_OPTIONS = 'Database=pbdemo'
);
```
although this shouldn't be required since it has already to be specified in `LOCATION` when using `CREATE EXTERNAL TABLE`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23b43af9-7da3-819b-d4f6-0e39f24f5f75
* Version Independent ID: d9e6987c-2648-2f18-424c-2f482c9226e8
* Content: [Configure PolyBase to access external data in SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-configure-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/polybase/polybase-configure-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-sql-server.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@ghotz  Thank you for the feedback, assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
@ghotz - I'm reaching out to partners to assess. Thank you for the submission.

**Comment by lerchdude** [comment]
@ghotz - Can you confirm the exact version of SQL you are running? (i.e. The output of `SELECT @@VERSION;`)

This bug was fixed in RTM (GDR), but not RTM.

**Comment by ghotz** [comment]
> @ghotz - Can you confirm the exact version of SQL you are running? (i.e. The output of `SELECT @@VERSION;`)

I'm running RTM: `Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)`

> This bug was fixed in RTM (GDR), but not RTM.

Good to know :-) the KB article for the GDR currently shows only one fix regarding SQL Browser in FCI environments (KB4527165) so I didn't installed it.
