### ISSUE TITLE
TRIM() function was added in SQL Server 2017

### ISSUE THREAD

**Issue by jboarman** [MicrosoftDocs/sql-docs#3728]
It should be noted what version this was added to T-SQL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfc6a4cd-b57c-8df6-221d-85aead960a91
* Version Independent ID: d0acb956-b718-d5d4-f422-52110f7a1242
* Content: [TRIM (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/trim-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/trim-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@jboarman Thank you for the feedback.

Currently this information is built into each doc rendered using the version selector:

![Capture](https://user-images.githubusercontent.com/6675884/70003787-1510a700-1519-11ea-810f-f43115a62e49.PNG)

To improve this method as your idea suggests, please move this issue to Microsoft Docs [feedback issues](https://github.com/MicrosoftDocs/feedback/issues).

**Comment by msebolt** [comment]
Closing the issue, please comment below if there any questions.
