### ISSUE TITLE
Don't forget to start SQL Agent again after step 12

### ISSUE THREAD

**Issue by t0mmg** [MicrosoftDocs/sql-docs#3729]
It may be worth adding a Note section to remind users who stopped the SQL agent earlier in the process to start it again. Otherwise Agent jobs such as backups/maintenance won't run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41367fc-38cf-0c73-3ea8-93bff726f421
* Version Independent ID: 07b2d0b3-2013-a133-9d1e-ee2d249740d5
* Content: [Connect to SQL Server When System Administrators Are Locked Out - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@t0mmg  Thank you for the feedback.

The documentation has been updated and is pending review.
