### ISSUE TITLE
Please correct the name of the DMV

### ISSUE THREAD

**Issue by gmafodda** [MicrosoftDocs/sql-docs#3730]
In the Tip for "Prerequisites and restrictions", the text refers to the DMV "sys.dm_hadr_database_cluster_states" when in fact the correct DMV name is "sys.dm_hadr_database_replica_cluster_states".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e33fa363-855a-a15d-f692-1b841363cc9f
* Version Independent ID: 9827e246-51df-6b3d-f21d-69c36b349860
* Content: [Perform a planned manual failover of an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/perform-a-planned-manual-failover-of-an-availability-group-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/perform-a-planned-manual-failover-of-an-availability-group-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/perform-a-planned-manual-failover-of-an-availability-group-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@gmafodda Thank you for the feedback.

The documentation has been updated and is pending review.
