### ISSUE TITLE
link to compatibility compatrix is missing

### ISSUE THREAD

**Issue by mco100** [MicrosoftDocs/sql-docs#3733]
could you create a link to SSDT compatibility matrix with attunity connectors (https://docs.microsoft.com/en-us/sql/integration-services/attunity-connectors?view=sql-server-ver15) in page
https://docs.microsoft.com/en-us/sql/integration-services/install-windows/install-integration-services?view=sql-server-ver15
instead of the link to attunity connectors latest version download page that does not mention compatibility issue with SSDT ?
Thanks

**Comment by msebolt** [comment]
@mco100 Thank you for the feedback, assigning this to the author for review.

**Comment by chugugrace** [comment]
link is updated.

**Comment by rothja** [comment]
Thanks @chugugrace! I'll close this issue now. And thanks for the feedback @mco100!
