### ISSUE TITLE
Diagrams Rendered Incorrectly using Dark Theme

### ISSUE THREAD

**Issue by artimob** [MicrosoftDocs/sql-docs#3734]
While "Dark Theme" is enabled the "Database Engine Upgrade Non-HA In-Place Upgrade" flow diagram and few others below render incorrectly as it doesn't have a white background like other diagrams.

**Good Example**
![2019-12-03-Image-19-26-46](https://user-images.githubusercontent.com/52269201/70033135-ef5fcc80-1602-11ea-83c9-41ef1b781f25.png)

**Bad Example**
![2019-12-03-Image-19-16-36](https://user-images.githubusercontent.com/52269201/70032971-ad368b00-1602-11ea-9274-5be2b4f6d5bb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916e128d-19fd-1f7d-8285-6313c4419710
* Version Independent ID: 8402af42-fdd1-2f3b-7c6a-8759e90e115f
* Content: [Choose a database engine upgrade method - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/choose-a-database-engine-upgrade-method?view=sql-server-ver15)
* Content Source: [docs/database-engine/install-windows/choose-a-database-engine-upgrade-method.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/choose-a-database-engine-upgrade-method.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @artimob , thanks for contacting Microsoft and bringing this to our attention! Let me see what I can do to fix this :) 

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @artimob , thanks again for bringing this to our attention! I have submitted a change to update the image and it should be live later today. 

I am going to close out this Git Issue but please feel free to comment should you need anything further.

Thanks for improving our documentation and hope you have a wonderful rest of your day@
Masha from the SQL Docs team
