### ISSUE TITLE
@loginame

### ISSUE THREAD

**Issue by amccool** [MicrosoftDocs/sql-docs#3736]
shouldnt this be @loginname?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5d2d017-80cc-de80-4460-2ebfbdc142f4
* Version Independent ID: 03a0def0-18a3-bc66-b5a7-9b1153c922ce
* Content: [sp_addlogin (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-addlogin-transact-sql?view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-addlogin-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-addlogin-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @amccool - Can you please elaborate on the issue? Thanks!

**Comment by msebolt** [comment]
@VanMSFT I think this refers to both `@loginame` in the **Syntax** and **Arguments** section.

**Comment by VanMSFT** [comment]
@amccool @msebolt - I see. The parameters are correct and does not need to be changed:

![image](https://user-images.githubusercontent.com/40007119/70091641-6bd9b780-15d1-11ea-850d-db1fb34cd900.png)

Thanks!
