### ISSUE TITLE
Scope of "Replicate"

### ISSUE THREAD

**Issue by potato-enthusiast** [MicrosoftDocs/sql-docs#3737]
Replicated tables exist in ASA, not sure why the page says "REPLICATE only applies to Parallel Data Warehouse."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adf0e9a7-a1d8-aa28-5806-9bc25dd280ba
* Version Independent ID: 85f18545-84c2-f810-a70e-74ea8b4a0d3d
* Content: [sys.pdw_table_distribution_properties (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-pdw-table-distribution-properties-transact-sql?redirectedfrom=MSDN&view=aps-pdw-2016-au7#feedback)
* Content Source: [docs/relational-databases/system-catalog-views/sys-pdw-table-distribution-properties-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-pdw-table-distribution-properties-transact-sql.md)
* Product: **sql**
* Technology: **data-warehouse**
* GitHub Login: @ronortloff
* Microsoft Alias: **rortloff**

**Comment by ronortloff** [comment]
thanks for the feedback.  this is fixed in pr13085.

**Comment by ronortloff** [comment]
#please-close
