### ISSUE TITLE
Error in Basic Syntax, section C. Using a cursor to determine the row to delete

### ISSUE THREAD

**Issue by gingagit** [MicrosoftDocs/sql-docs#3739]
There is an issue with this section.  The description states that the cursor's name is my_cursor but is named complex_cursor in the code segment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21fe0c8-0242-d9e0-b7bb-cee5265d39c9
* Version Independent ID: e70df047-67c6-7933-ccdd-11731a77eb20
* Content: [DELETE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/delete-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/delete-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/delete-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@gingagit -- thank you for your feedback.  I am looking into this article.
