### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by MrSuaveh** [MicrosoftDocs/sql-docs#3743]
I believe this “The characters 0x will be added to the left of the converted result for style 1.”  Is actually describing style 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f56efc1-e90f-68dd-cb02-2f2ba21373fd
* Version Independent ID: aa110136-4520-ed90-97fe-1fdedd1863ad
* Content: [CAST and CONVERT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/cast-and-convert-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/cast-and-convert-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@MrSuaveh Thank you for the feedback.

Can you provide an example to support this claim?

The following below shows an example of style1 vs. style 2 without the `0x`:

```
DECLARE @tmp binary(4);  
SET @tmp = 0011
SELECT @tmp
SELECT CONVERT(char(8), @tmp, 0) 
SELECT CONVERT(char(8), @tmp, 1) 
SELECT CONVERT(char(10), @tmp, 1) 
SELECT CONVERT(char(8), @tmp, 2) 
```

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
