### ISSUE TITLE
Typo mistake

### ISSUE THREAD

**Issue by n-shyamprasad** [MicrosoftDocs/sql-docs#3745]
Typo mistake in 2nd paragraph **B**ACPAC instead of **D**ACPAC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cea5408a-67bf-2d2f-d0f3-5eb32b0251e0
* Version Independent ID: f8049868-f012-9c03-df33-7fce87448c40
* Content: [Data-tier Applications - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/data-tier-applications?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/data-tier-applications/data-tier-applications.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/data-tier-applications.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@n-shyamprasad Thank you for the feedback.

Are you referring to `A BACPAC is a related artifact...`?

If so, the term `BACPAC` is also valid and is discussed [here](https://docs.microsoft.com/sql/relational-databases/data-tier-applications/data-tier-applications?view=sql-server-ver15#bacpac) later is the article.

**Comment by shyamprasad-n** [comment]
> @n-shyamprasad Thank you for the feedback.
> 
> Are you referring to `A BACPAC is a related artifact...`?
> 
> If so, the term `BACPAC` is also valid and is discussed [here](https://docs.microsoft.com/sql/relational-databases/data-tier-applications/data-tier-applications?view=sql-server-ver15#bacpac) later is the article.

Ookay..I got it now... mistake was mine. Thank you.
