### ISSUE TITLE
Is .NET Core SDK available for programmatic access to SSIS object model?

### ISSUE THREAD

**Issue by immitev** [MicrosoftDocs/sql-docs#3747]
Is there a corresponding .NET Core version of `Microsoft.SqlServer.ManagedDTS.dll` that enables using the API for loading or creating packages (see https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dts.runtime )?

In https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-ssis-known-issues?view=sql-server-ver15 I couldn't find this mentioned.

**Comment by WilliamAntonRohm** [comment]
@immitev -- Ivan, thank you for your feedback.

@markingmyname -- Mark, please look into this issue 3747.

**Comment by markingmyname** [comment]
@immitev,

I apologize for the delayed response. 

Thanks for your comment.

Your contribution is much appreciated. 

However, our team can only answer feedback related to the documentation. Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page or visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) page. If you have any feedback related to the documentation, please feel free to log in through this channel. We truly appreciate your contribution to our articles.

Hope this helps.

Thank you.

P. S. I did reach out to our SSIS engineering team.  If there is a reply, I will let you know.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by markingmyname** [comment]
I heard back and we never built a .net core version of the SDK. 

The Linux version of SSIS is using SQLPAL technology which is unrelated to .net core.

Hope this helps.

Thank you.
