### ISSUE TITLE
Minimum version

### ISSUE THREAD

**Issue by kalatchev** [MicrosoftDocs/sql-docs#3751]
Not long ago, there was information for the minimum version for every feathure. Now it's removed! How I can know in which version SEQUENCE object appear?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fe1f7ad-1e14-ed5e-992c-1037500f20f1
* Version Independent ID: f4a6dbbf-0273-536c-f3f2-2e56b1c7bc28
* Content: [ALTER SEQUENCE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-sequence-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/alter-sequence-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-sequence-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@kalatchev for the general page about sequence in SQL Server 2014, for instance - you can go here https://docs.microsoft.com/en-us/sql/relational-databases/xml/xml-data-sql-server?view=sql-server-2014 - for the actual syntax - such as the CREATE SEQUENCE or ALTER SYNTAX statement, these topics are version agnostic. Within each such topic, there should be (and most times there is, but not always) "Applies to" tags to identify when a new argument, for example, was added. See, for example ALTER INDEX https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-index-transact-sql 

all this said, if you have a specific question about ALTER SEQUENCE not working as expect, please advise and we will try to get you assistance. 

Finally, for this particular topic, I searched the GitHub history and do not see any versioning information being removed.

Cheers, Carl

**Comment by kalatchev** [comment]
Thank you, @CarlRabeler . Despite your explanation, I was not able to find information in which version sequences are introduced. The main topic ( https://docs.microsoft.com/en-us/sql/relational-databases/sequence-numbers/sequence-numbers ) has not such info.

IMHO version information is very important for every developer and it should be available on almost every page. Also, I think the documentation should not follow support lifetime, but to be like time machine, as there are installations of old servers and they should be maintained somehow. In fact, our company still supports SQL Server 2012, which is missing in documentation. 

<img src="https://user-images.githubusercontent.com/10154711/70279106-5c6b9180-17be-11ea-97c8-8c1c52432913.png" width="70%">

**No 2012?!?** My suspucion is that sequences appeared there.

Today people use both software and hardware much longer than before (which is the reason PC market is much lower than before). And ISV's have to adapt and support very old versions and systems. My proposal is to establish kind of **Archived Docs** site, where to put a copy of documentation and downloads for such needs. It could be a read-only dump of current site, just for reference. Yes, I know is database driven, but it's not impossible.

**Comment by CarlRabeler** [comment]
For 2012 docs, go to https://www.microsoft.com/en-us/download/details.aspx?id=347

**Comment by CarlRabeler** [comment]
For 2014, go to https://www.microsoft.com/en-us/download/details.aspx?id=42557

**Comment by kalatchev** [comment]
Well, that makes sense :smile: Little bit inconveniently, but solves the problem. Thanks.

**Comment by CarlRabeler** [comment]
I know, it is something that we are aware of and working on.
