### ISSUE TITLE
BACKUP DATABASE is terminating abnormally

### ISSUE THREAD

**Issue by SmartNoel** [MicrosoftDocs/sql-docs#3757]
Did it and I'm receiving the mentioned error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c3875ad-d73a-8f5b-e8ba-8418014fbada
* Version Independent ID: 13471101-d549-e73b-fef2-fed92518bfcf
* Content: [Run Transact-SQL Script Files Using sqlcmd - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/scripting/sqlcmd-run-transact-sql-script-files?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/scripting/sqlcmd-run-transact-sql-script-files.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/sqlcmd-run-transact-sql-script-files.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@SmartNoel -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task.
