### ISSUE TITLE
1918

### ISSUE THREAD

**Issue by LuisGonzalezLT** [MicrosoftDocs/sql-docs#3758]
It appears the underlying timezone rules that AT TIME ZONE uses selects 04/07/1918 2AM as the spring switch date/time instead of the correct 03/31/1918 2AM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8b3b24-5a50-6b88-277a-e8ce528b49b2
* Version Independent ID: ed560876-5e84-cb31-1bd4-65b3b0e5da8b
* Content: [AT TIME ZONE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/at-time-zone-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/queries/at-time-zone-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/at-time-zone-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by LuisGonzalezLT** [comment]
Also uses 04/06/1919 instead of 03/30/1919

**Comment by WilliamAntonRohm** [comment]
@LuisGonzalezLT -- thank you for finding these.  Please enter your feedback at:

- [SQL Server Feedback](https://aka.ms/sqlfeedback)

**Comment by srutzky** [comment]
@LuisGonzalezLT Please see the comment I left on the related issue:

https://github.com/MicrosoftDocs/sql-docs/issues/3763#issuecomment-586828742

**Comment by LuisGonzalezLT** [comment]
That kind of stinks for anyone working with dates < 1987 needing to do reliable time zone conversions where being an hour off could hurt. Fortunately it doesn’t affect my current dataset as we don’t deal with years that old but if it was a problem with current date conversions we could be in hot water since we have specific regulations we have to follow that are hour sensitive. It was just something I stumbled on so thought I would bring it up.

Thanks for the insight 😊

**Comment by srutzky** [comment]
@LuisGonzalezLT Hi. Something happened with your reply and it contains your email address. I suggested deleting the comment on issue 3758 and adding it to issue 3763 via the UI instead of a reply email. Take care, solomon...
