### ISSUE TITLE
sqlsrv support for PHP 7.4 unclear

### ISSUE THREAD

**Issue by SteveKennedy** [MicrosoftDocs/sql-docs#3760]
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/download-drivers-php-sql-server.md

This page has drivers for PHP version 5.3 up to 7.3.  But it does not have support for PHP 7.4 which is the latest release of PHP on https://www.php.net/.

**Comment by WilliamAntonRohm** [comment]
@SteveKennedy -- Steve, thank you for your feedback.

@MightyPen -- Gene, please look into this issue 3760.

**Comment by MightyPen** [comment]
@David-Engel  Hi David,  In this Issue #3760, can you ascertain whether this PHP download webpage is up to date?
`SteveKennedy` says the webpage currently support "7.3", and that he believes "7.4" should be added to the article.  Yet "5.6" is the highest version that my eyes see on the webpage?

- `https://docs.microsoft.com/en-us/sql/connect/php/download-drivers-php-sql-server?view=sql-server-ver15`

Thanks, G.

**Comment by David-Engel** [comment]
@SteveKennedy PHP 7.4 (which just release GA Nov 28) support is currently only available in the preview releases of the Microsoft Drivers 5.7.x for PHP for SQL Server. A GA version of the 5.7.x drivers has not yet been released. Look for a GA release around the end of January, at which time the documentation will be updated accordingly.

Regards,
David

cc: @MightyPen

**Comment by MightyPen** [comment]
@SteveKennedy Hi Steve, David-Engel's informative Comment makes it time for me to Close this Issue #3760 as Answered.

Thank you for reaching out to us with this concern.
And, thank you for submitting this Issue. We hope to hear from you again.

(The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.)

**Comment by SteveKennedy** [comment]
Thank you. Based on this thread alone, I learned that there's a preview release of Microsoft Drivers 5.7.x for PHP for SQL Server. That solved my issue.

Leaves me wondering why links to the preview release couldn't be added to the page?

**Comment by David-Engel** [comment]
@SteveKennedy The docs for drivers generally represent GA released versions. Previews are announced via the [SQLServerDrivers blog](https://techcommunity.microsoft.com/t5/SQL-Server/bg-p/SQLServer/label-name/SQLServerDrivers) and on the repo for open source drivers for developers to try out and provide feedback before changes are introduced into a GA release:

PHP Repo: https://github.com/microsoft/msphpsql/releases
