### ISSUE TITLE
Unnecessary Confusion

### ISSUE THREAD

**Issue by mwdarab** [MicrosoftDocs/sql-docs#3766]
Can #5 under section "Create an external table in the data pool" be removed? BDCs are GA now. Anyone running CTP 3.1 should upgrade. (It could potentially create unnecessary confusion for someone starting out with BDCs).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c639fd7-43ee-f24d-ce5e-530077367aab
* Version Independent ID: 28059c60-abe8-e4f8-08c5-221c926f007e
* Content: [Ingest data with Spark jobs - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-spark?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/tutorial-data-pool-ingest-spark.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/tutorial-data-pool-ingest-spark.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @rajmera3
* Microsoft Alias: **raajmera**

**Comment by rajmera3** [comment]
Thanks for the catch @mwdarab. Updating now.

**Comment by mwdarab** [comment]
#5 still exists.

**Comment by MikeRayMSFT** [comment]
Resolved in https://github.com/MicrosoftDocs/sql-docs-pr/commit/4a571aa6ba02a952f0f7ace80625f845f1be3ed8#diff-5040f3daef38a9b726267e8c7c68f676
