### ISSUE TITLE
Login Failed for user ERROR

### ISSUE THREAD

**Issue by mwdarab** [MicrosoftDocs/sql-docs#3767]
I am currently going through https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-spark?view=sql-server-ver15#start-a-spark-streaming-job

and successfully get past #3 a., then when I run 3(b), I get the following "login failed for user root"...what am I missing?

[I am on my Surface Book 2 on ADS logged into my single node Ubuntu 18.04 kubeadm BDC server]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c639fd7-43ee-f24d-ce5e-530077367aab
* Version Independent ID: 28059c60-abe8-e4f8-08c5-221c926f007e
* Content: [Ingest data with Spark jobs - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-spark?view=sql-server-ver15#start-a-spark-streaming-job)
* Content Source: [docs/big-data-cluster/tutorial-data-pool-ingest-spark.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/tutorial-data-pool-ingest-spark.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @rajmera3
* Microsoft Alias: **raajmera**

**Comment by rajmera3** [comment]
@mwdarab Looking into this.

I believe if you follow these steps, it will fix it: https://github.com/microsoft/sql-server-samples/blob/master/samples/features/sql-big-data-cluster/spark/data-virtualization/mssql_spark_connector_user_creation.ipynb

This twitter streaming sample is up-to-date and working. The instructions are also applicable to the tutorial you are doing: https://github.com/microsoft/sql-server-samples/blob/master/samples/features/sql-big-data-cluster/spark/data-loading/spark-twitter-streaming-sample.ipynb

**Comment by mwdarab** [comment]
But where are those steps on *this* page? Why isn't there a section that either has this information on this page (to lessen confusion) *or* a blurb section that says, "go do this then come back and continue"? This is very confusing to the beginner.

My goal is to "Load data with Spark" according to what is on *this* page. From beginning to end.

**Comment by rajmera3** [comment]
We are in the process of updating the docs. The links are supplied as reference until then.

**Comment by rajmera3** [comment]
Addressed in PR #13245
