### ISSUE TITLE
SQL handling of spaces

### ISSUE THREAD

**Issue by DaveBoltman** [MicrosoftDocs/sql-docs#3771]
> STRING_SPLIT will return empty string if there is nothing between separator. Condition RTRIM(value) &lt;&gt; '' will remove empty tokens.

Due to the way SQL (and thus SQL Server) handles trailing spaces, just the condition `WHERE value <> ''` is enough (`RTRIM `is not needed).
This is true even if there are spaces in the delimited string, e.g: `DECLARE @tags NVARCHAR(400) = 'clothing,road,      ,touring,bike'`  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77b3e27b-a3ee-da83-1d41-1fafd96228cb
* Version Independent ID: cc43ad4b-92ac-477f-a92d-1487c82ebe70
* Content: [STRING_SPLIT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/string-split-transact-sql?view=sql-server-2016)
* Content Source: [docs/t-sql/functions/string-split-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/string-split-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@DaveBoltman -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue 3771.

**Comment by MikeRayMSFT** [comment]
@DaveBoltman - Thank you for the submission. We'll accept this request into our queue. If you'd like to update the content directly, please click **Edit** at the top of the article and submit a public pull request. For more information, [see Quick edits](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) in our contributor guide.
Mike
