### ISSUE TITLE
Setup seems to require ODBC Driver 13 and ODBC 17

### ISSUE THREAD

**Issue by yacineahbar** [MicrosoftDocs/sql-docs#3772]
The installer does not recognize ODBC Driver 17. Is the doc wrong about this requirement ?

https://social.msdn.microsoft.com/Forums/en-US/16c996d7-c3b1-42e4-9a66-6e27f6ec85e2/microsoft-command-line-utilities-15-for-sql-server-installation-failed

**Comment by WilliamAntonRohm** [comment]
@yacineahbar -- Yacine, thank you for your well-researched question.

@MightyPen -- Gene, please look into this potential documentation issue 3772.

**Comment by rothja** [comment]
@yacineahbar Thank you for reaching out to us with this problem. This sounds like it could be a product and/or doc bug, but I'll have to research it. I apologize for the long delay in a response. Thanks for he link to the detailed steps and the work around.

**Comment by rothja** [comment]
@yacineahbar In looking at the [forum post](https://social.msdn.microsoft.com/Forums/en-US/16c996d7-c3b1-42e4-9a66-6e27f6ec85e2/microsoft-command-line-utilities-15-for-sql-server-installation-failed) it looks like there is a validated work around for this problem. I am reporting this as a problem to the tools team, but it looks like that solution will unblock you. Please let me know if it does not. Thank you!

**Comment by rothja** [comment]
Note, the same problem shows up in our feedback forums [here](https://feedback.azure.com/forums/908035-sql-server/suggestions/36132202-microsoft-command-line-utilities-15-for-sql-server). I have reached out to report and request that we address this problem. The good news is that the work around seems to work for the users reporting it there.
