### ISSUE TITLE
Blocking?

### ISSUE THREAD

**Issue by propellor** [MicrosoftDocs/sql-docs#3776]
Does adding a column to a table block other transactions against it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f1c141-dea3-1a2c-ba2f-86163be24aa6
* Version Independent ID: 5d4a7221-2821-feb8-c74d-509c0c6e3889
* Content: [Add Columns to a Table (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/add-columns-to-a-table-database-engine?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/add-columns-to-a-table-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/add-columns-to-a-table-database-engine.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@propellor - Thanks for the feedback!

Hi Sam, can you be more specific?

I think the answer really depends on a few different things such as the details of the new column (is it nullable, is it a computed column, etc.),  the details of the transaction running against the table (is it adding values that the new column uses in any way), isolation level, etc.

At some point the table needs to update the schema and add the new column to existing rows so there will be locking at some point which will cause any transaction to have to wait. 

Are you running into a real-world issue and having transactions fail, or ?

Thanks!

**Comment by CarlRabeler** [comment]
@propellor Given that we have not heard back from you for over 2 months, I am going to close this issue for now. Please feel free to reopen it at any time with the specific information requested and we will try to answer your specific questions.
Thanks,
Carl
