### ISSUE TITLE
Typeo and better example for "Create a classification function for machine learning"

### ISSUE THREAD

**Issue by sstansfield** [MicrosoftDocs/sql-docs#3777]
Step 2 of "Create a classification function for machine learning"
A better example would include the 'Mashup' engine as this is used by machine learning services:

 IF program_name() in ('Microsoft R Host', 'RStudio', 'Mashup') RETURN 'ds_wg';

Step 3 of "Create a classification function for machine learning"

You cannot alter "WITH" reconfigure;

 ALTER RESOURCE GOVERNOR WITH reconfigure;

This step should read:

 ALTER RESOURCE GOVERNOR RECONFIGURE;

Thank you,
Steve Stansfield

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a7c9941-5ec6-eb46-e916-b541f4be5608
* Version Independent ID: f090a31f-ab70-1392-610f-749b79c5ef87
* Content: [Create a resource pool - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/administration/create-external-resource-pool?view=sql-server-ver15#feedback)
* Content Source: [docs/advanced-analytics/administration/create-external-resource-pool.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/administration/create-external-resource-pool.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by WilliamAntonRohm** [comment]
@sstansfield -- Steve, thank you for your detailed feedback.

@dphansen -- David, please look into this issue 3777.

cc @MightyPen as a writer

**Comment by dphansen** [comment]
Assigning this to @garyericson

**Comment by garyericson** [comment]
@sstansfield - Thanks for catching this. I'll go ahead and make the changes, but just so you know, you can submit changes like these yourself by editing the article directly. If you're interested, here are the instructions: https://docs.microsoft.com/en-us/contribute/

@dphansen 

#please-close
