### ISSUE TITLE
SEQUENCES view missing in "System Information Schema Views (Transact-SQL)"

### ISSUE THREAD

**Issue by knutwannheden** [MicrosoftDocs/sql-docs#3783]
* ID: 7178ceb7-4a73-234d-fd3a-845754774ce7
URL: https://docs.microsoft.com/en-us/sql/relational-databases/system-information-schema-views/system-information-schema-views-transact-sql?view=sql-server-ver15

On this page there is no documentation about the `INFORMATION_SCHEMA.SEQUENCES` view.

**Comment by WilliamAntonRohm** [comment]
@knutwannheden -- Knut, thank you for your feedback.

@CarlRabeler -- Carl, please look into this issue 3783.

**Comment by CarlRabeler** [comment]
PR pending

**Comment by CarlRabeler** [comment]
still awaiting PM review of staged article

**Comment by CarlRabeler** [comment]
PR merger pending
