### ISSUE TITLE
MaxSizeInBytes values shown are for DTU model only.

### ISSUE THREAD

**Issue by m60freeman** [MicrosoftDocs/sql-docs#3786]
MaxSizeInBytes values shown are for DTU model. Please update for vCore. Also, all of the vCore databases that I've tried return null.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ca907e-99b6-3663-82bf-abe45f1ae76e
* Version Independent ID: 1acba411-593f-6cd2-7c76-8e35dbd8ac13
* Content: [DATABASEPROPERTYEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/databasepropertyex-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/databasepropertyex-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/databasepropertyex-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@m60freeman -- Mark, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue 3786.

**Comment by MikeRayMSFT** [comment]
@m60freeman -- Sorry about the delayed response. We've done a little internal testing. 

Are all of the vCore databases still returning null?

**Comment by m60freeman** [comment]
@MikeRayMSFT Two issues: 1) Documentation; the page lists 7 values that can be returned. Presumably, those only apply for databases in the DTU model, and even for those, there are many more valid values depending on which Edition applies. For example, in Standard Edition, the values could be any of the following (in GB):

2
5
10
20
30
40
50
100
150
200
250
500

vCore databases are not restricted to a set list of possible values and can be any multiple of 1 GB.

2) Function; it doesn't seem to be a vCore issue. If I am connectected to master and execute:

SELECT DATABASEPROPERTYEX('MyDatabase', 'MaxSizeInBytes');  

it returns NULL. If I change the connection to MyDatabase and run it, I get a value. If it only works in the current user database, why do I have to specify the database name? Conversely, if I have to specify the database name, why doesn't it work when executed in master?

**Comment by rothja** [comment]
@juliemsft Could you please look more into this issue? Thank you! #reassign:juliemsft

**Comment by julieMSFT** [comment]
@m60freeman Hello, I have taken over this issue and am researching an answer. Thank you.

**Comment by julieMSFT** [comment]
@m60freeman  Hi Mark, I am updating the document to show the values. 

Azure SQL Database and Azure Synapse Analytics (SQL DW) – Value is based on SLO unless additional storage has been purchased.

vCore – Value is in 1GB increments up to max size.

The vCore machines should return a value. If you are still having an issue with values being returned for vCore we'd recommend engaging the community, or opening a ticket with Microsoft Support. More information can be found here: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

I will proceed with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
