### ISSUE TITLE
Need to alias columns in multi-table query

### ISSUE THREAD

**Issue by pnwguy** [MicrosoftDocs/sql-docs#3787]
It would help if you aliased the columns in the multi-table query, so we know which columns are from which tables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 678c7ae3-295a-912b-9a1a-9bc9414178fd
* Version Independent ID: 99132c6a-7986-6403-b191-15b4ada93a76
* Content: [Format Nested JSON Output with PATH Mode - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/format-nested-json-output-with-path-mode-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/json/format-nested-json-output-with-path-mode-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/format-nested-json-output-with-path-mode-sql-server.md)
* Product: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by msebolt** [comment]
@pnwguy  Thank you for the feedback.

The documentation has been updated and is pending review.
