### ISSUE TITLE
Additional info needed

### ISSUE THREAD

**Issue by mwdarab** [MicrosoftDocs/sql-docs#3788]
Under "Query the data", #1. says, "Before querying the ingested data, look at the Spark Execution Status..."

Can there be a sentence on *how* to do that? Where to find the "Spark Execution Status..."? It would make it a lot easier for people trying this out for the first time. It is a bit confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c639fd7-43ee-f24d-ce5e-530077367aab
* Version Independent ID: 28059c60-abe8-e4f8-08c5-221c926f007e
* Content: [Ingest data with Spark jobs - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-spark?view=sql-server-ver15#start-a-spark-streaming-job)
* Content Source: [docs/big-data-cluster/tutorial-data-pool-ingest-spark.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/tutorial-data-pool-ingest-spark.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @rajmera3
* Microsoft Alias: **raajmera**

**Comment by msebolt** [comment]
@mwdarab Thank you for the feedback, assigning this to the author for review.

**Comment by rajmera3** [comment]
Addressed in PR #13245
