### ISSUE TITLE
Link goes to a 404

### ISSUE THREAD

**Issue by TrustMeImADBA** [MicrosoftDocs/sql-docs#3789]
The link for How to use Kerberos authentication in SQL Server  goes to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16136000-fc6d-9156-499a-c45bde264bc4
* Version Independent ID: ea9aacfc-8f27-563f-08c8-77ac4e941cff
* Content: [Register a Service Principal Name for Kerberos Connections - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@TrustMeImADBA Thank you for the feedback.

The documentation has been updated and is pending review.

@MikeRayMSFT
