### ISSUE TITLE
is this page still valid - azure sql database v11

### ISSUE THREAD

**Issue by amthomas46** [MicrosoftDocs/sql-docs#3793]
I am wondering if this page should be archived? Isn't everything v12? Also, do customers know what v11/v12 means?  

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8d9ca6-1795-8023-871e-9f5521440a7d
* Version Independent ID: c8619519-e5a8-f6ff-89dd-3805476b0f19
* Content: [dbo.server_quotas (Azure SQL Database) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/dbo-server-quotas-azure-sql-database?view=azuresqldb-current)
* Content Source: [docs/relational-databases/system-catalog-views/dbo-server-quotas-azure-sql-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/dbo-server-quotas-azure-sql-database.md)
* Service: **sql-database**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@amthomas46 Thank you for the feedback, 

You are correct in that v11/v2 was deprecated since 2016,  see [here](https://techcommunity.microsoft.com/t5/Azure-Database-Support-Blog/No-Azure-SQL-V2-or-as-called-sometimes-V11-anymore/ba-p/368815).

Assigning this to the author for review.

**Comment by stevestein** [comment]
@amthomas46 - Thanks for the feedback! 
Hi Anna, thanks for pointing this out. I removed the old article.

Thanks!

**Comment by stevestein** [comment]
#please-close
