### ISSUE TITLE
step 4 and 5 are the same text just copied again (On the Select a Partition Function page, )

### ISSUE THREAD

**Issue by momchilok** [MicrosoftDocs/sql-docs#3797]
[Enter feedback here]
step 4 and 5 are the same text just copied again (On the Select a Partition Function page, )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4466c524-282b-adc0-d539-3eb85d956597
* Version Independent ID: 08052bb4-d7bb-02ab-6d37-e3fcce20846c
* Content: [Create Partitioned Tables and Indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/partitions/create-partitioned-tables-and-indexes?view=sql-server-ver15)
* Content Source: [docs/relational-databases/partitions/create-partitioned-tables-and-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/partitions/create-partitioned-tables-and-indexes.md)
* Product: **sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by msebolt** [comment]
@momchilok Thank you for the feedback.

Steps 4 and 5 are similar, though each appear to represent an additional step needed to create the partition table.

Please provide further description to the issue if you'd like an update.

**Comment by msebolt** [comment]
Closing the issue now.
