### ISSUE TITLE
T-SQL syntax - Create Login: inconsistent information on where to put commas

### ISSUE THREAD

**Issue by richlionm2** [MicrosoftDocs/sql-docs#3798]
[Enter feedback here]

Hello, 

I have got not clue how this works, but I'll try this.
I needed the correct syntax on the T-SQL command "create login":
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-login-transact-sql?view=sql-server-ver15

There are not enough real life example. I struggled to use this statement, googled for 30 minutes, then I tried to check the commas, so my statement works. 
```
CREATE LOGIN [MyUser] 
WITH PASSWORD = 'MyPassword',      /* so here I had a missing comma */
DEFAULT_DATABASE = MyDatabase,   /* this can also work with [] */ 
CHECK_POLICY = OFF, 
CHECK_EXPIRATION = OFF ;
```

Your document doesn't actually help with commas. 

Kind Regards, 
Richard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0f4b3be-5686-ac31-8c5d-676e08953d8f
* Version Independent ID: 43881484-714e-d528-7a38-72d24a2d40d1
* Content: [CREATE LOGIN (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-login-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-login-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-login-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@richlionm2 -- thank you for your feedback.  I am looking into this documentation.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- please look into this issue 3798.

**Comment by CarlRabeler** [comment]
@richlionm2 I am added your example into the list of examples now. The syntax convention can definitely be a bit difficult to parse.

**Comment by VanMSFT** [comment]
Thanks, @CarlRabeler!
