### ISSUE TITLE
Error highlighting

### ISSUE THREAD

**Issue by JulioNobre** [MicrosoftDocs/sql-docs#3801]
Since interferences from this measure would be nothing but benign, I think **Exception** event (from **Errors and Warnings** group) should be always present in public **SQL Server Profiler** templates like this.
The main benefit from this measure would be pointing less experient users to the right diretion, while promoting a possible significant reduction on troubleshooting tracing anomalies.

Thanks for your attention.
Kinds regards,

Júlio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 029c2b34-bc6a-ff4c-2dd5-dc8934ee4f06
* Version Independent ID: 227a26d7-a8eb-a544-4974-c4375d31727f
* Content: [Replay Requirements - SQL Server Profiler](https://docs.microsoft.com/en-us/sql/tools/sql-server-profiler/replay-requirements?view=sql-server-2017)
* Content Source: [docs/tools/sql-server-profiler/replay-requirements.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sql-server-profiler/replay-requirements.md)
* Product: **sql**
* Technology: **profiler**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@JulioNobre -- Júlio, thank you for your feedback.  Please add your ideas here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
