### ISSUE TITLE
Remove outdated information

### ISSUE THREAD

**Issue by mwdarab** [MicrosoftDocs/sql-docs#3802]
Please remove #6 under Create an external table in the data pool. We are in GA and no longer need to reference CTP version. It only adds to confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf1b0e77-0f03-7b70-b2e3-26911e49dd47
* Version Independent ID: 511793e4-b3c5-3d07-a8e9-bc10b8347985
* Content: [Ingest data into a SQL Server data pool - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-sql?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/tutorial-data-pool-ingest-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/tutorial-data-pool-ingest-sql.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@mwdarab -- Mohammad, thank you for your suggestion.  I am looking into this documentation.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- please review the above-mentioned PR 13298.
