### ISSUE TITLE
Broken debian packages repository

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#3803]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/sql-docs.pt-br/issues/34

@rodrigomaraujo commented 1 hour ago
Since Dez, 13 2019 update the package repository is bronken.

https://packages.microsoft.com/debian/10/prod/dists/buster/Release and https://packages.microsoft.com/debian/10/prod/dists/buster/InRelease has different size and hashes from https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-amd64/Packages.bz2

Release (right values):
MD5Sum:
232d6c5b746913f648a6445998206f6f 18556 main/binary-amd64/Packages.bz2

InRelease (wrong values):
MD5Sum:
4153a12e4a5629bfb14ed98f4c8ac234 156065 main/binary-amd64/Packages.bz2

Now we can't install ODBC Driver in Debian Linux systems.

APT error:

E: Failed to fetch https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-amd64/Packages.bz2 File has unexpected size (18556 != 156065). Mirror sync in progress? [IP: 40.76.35.62 443]
Hashes of expected file:
- Filesize:156065 [weak]
- SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
- SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
- SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
- MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
Release file created at: Thu, 12 Dec 2019 19:59:19 +0000

**Comment by rodrigomaraujo** [comment]
Great, I tested now and seens that resolved :)

# apt-get update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [162 kB]
Get:5 https://packages.microsoft.com/debian/10/prod buster InRelease [29.8 kB]
Get:6 https://packages.microsoft.com/debian/10/prod buster/main arm64 Packages [556 B]
Get:7 https://packages.microsoft.com/debian/10/prod buster/main amd64 Packages [18.8 kB]
Get:8 https://packages.microsoft.com/debian/10/prod buster/main armhf Packages [556 B]
Get:9 https://packages.microsoft.com/debian/10/prod buster/main all Packages [556 B]
Fetched 277 kB in 2s (117 kB/s)
Reading package lists... Done

Thank's

**Comment by WilliamAntonRohm** [comment]
@CeciAc, @rodrigomaraujo  -- Cecilia, Rodrigo, I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
