### ISSUE TITLE
Error Reporting Parameter

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#3807]
In the Installation Parameters section, please clarify /ERRORREPORTING description - it seems to be saying what works/does not work for SQL 2016 - can you please clarify for 2017+ and clarify the entry overall (i.e. does it still actually work?)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff01c71-f3bf-2c3a-5e90-b11952aee4f8
* Version Independent ID: 99ebd80b-9465-6929-c84f-187525ee3284
* Content: [SQL Server installation - Command Prompt parameters - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-ver15#Install)
* Content Source: [docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @PrometheusRising1 , thanks for contacting Microsoft! Let me look into this for you.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @PrometheusRising1 , thanks for bringing this to our attention as well. The new privacy terms are applicable to SQL Server 2016 and newer. I've updated the document as such, and it should be live tomorrow.

I will close out this Git Issue but please feel free to comment should you need anything further.

Thanks again!
Masha from the SQL Docs team
