### ISSUE TITLE
Password Required, but How to use NT Service?

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#3808]
Hi, it says that things like /AGTSVCPASSWORD or /SQLSVCPASSWORD are required, but what do you do if you want a quiet install that uses NT Service\SQLSERVERAGENT or NT Service\MSSQLSERVER?  In the GUI, this is easy, but what about from command line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff01c71-f3bf-2c3a-5e90-b11952aee4f8
* Version Independent ID: 99ebd80b-9465-6929-c84f-187525ee3284
* Content: [SQL Server installation - Command Prompt parameters - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-ver15#Install)
* Content Source: [docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @PrometheusRising1 , thanks again for reaching out! Let me look into this as well for you :)

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @PrometheusRising1 , thanks for bringing this to our attention! This parameter can be omitted when used in conjunction with a managed service account, virtual account, or built-in account. There is a note in the doc that specifies that but I've added it explicitly as a note to every password parameter.

This change should be live tomorrow.  I will close out this Git Issue at this time but please feel free to comment should you need anything further.

Thanks and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
