### ISSUE TITLE
Documentation Mistake !!

### ISSUE THREAD

**Issue by emad-almousa** [MicrosoftDocs/sql-docs#3810]
db_accessadmin is the database permission that will enable the database account to add new members to the partially contained database Not db_securityadmin !

i think the paragraph wording is not clear.

Regards,
Emad Al-Mousa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9d16565-6317-df2b-41d7-701eb83fb90b
* Version Independent ID: 8fcc2424-a8b4-f188-dceb-e3aebd2b49ff
* Content: [Security Best Practices with Contained Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/security-best-practices-with-contained-databases?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/databases/security-best-practices-with-contained-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/security-best-practices-with-contained-databases.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@emad-almousa -- Emad, thank you for your feedback.

@VanMSFT -- Van, please look into this issue 3810.

**Comment by VanMSFT** [comment]
@emad-almousa - Hi Emad Al-Mousa! Thank you! You're right, and I've fixed the text to reflect db_accessadmin instead of db_securityadmin. It should be live soon. Thanks again for your help on our documentation!

https://github.com/MicrosoftDocs/sql-docs-pr/pull/13274
