### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Mitch-Wheat** [MicrosoftDocs/sql-docs#3811]
Column 'transaction_isolation_level' values description should read:

1 = ReadUncommitted
....
3 = RepeatableRead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c4e75e-7e4b-3143-8f2f-1d866f309c90
* Version Independent ID: d7b963c0-691a-f4af-35e6-bb84fca98ff2
* Content: [sys.dm_exec_sessions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-sessions-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-exec-sessions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-sessions-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please review the above-mentioned PR 13305.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please confirm the above-mentioned PR 13305.
