### ISSUE TITLE
The code failed because of a fatal error: 	Invalid status code '401' 

### ISSUE THREAD

**Issue by kenakamu** [MicrosoftDocs/sql-docs#3812]
I setup BDC by using default azdata template with 1 cluster, and I didn't change any password so far.
I imported sample data and at step 3 of this page, i cannot connect to gateway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c639fd7-43ee-f24d-ce5e-530077367aab
* Version Independent ID: 28059c60-abe8-e4f8-08c5-221c926f007e
* Content: [Ingest data with Spark jobs - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-spark?view=sql-server-ver15#start-a-spark-streaming-job)
* Content Source: [docs/big-data-cluster/tutorial-data-pool-ingest-spark.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/tutorial-data-pool-ingest-spark.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @rajmera3
* Microsoft Alias: **raajmera**

**Comment by WilliamAntonRohm** [comment]
@kenakamu -- Kenichiro, thank you for your feedback.

@rajmera3 -- Rahul, please look into this issue 3812.

cc @MightyPen as a writer

**Comment by MightyPen** [comment]
@MikeRayMSFT Mike, This is a big-data-cluster Issue #3812 , on which you are the `ms.reviewer`.  So I am switching the assigned Writer from me to you.

Of course, we are nevertheless looking for the PM to enter a Comment into this Issue.
Thanks.  G.

cc: @WilliamAntonRohm @rajmera3

**Comment by kenakamu** [comment]
It seems like if I use "$" as part of password, it fails. From the doc, I don't consider this is not prohibited letter though.

**Comment by rajmera3** [comment]
@kenakamu Is it working now?

We are working on updating the docs (a PR is out to include the instructions below), but is your error at the data ingestion portion?

This link instructs you how to grant permissions for a user and the mssql-spark connector to actually read data and store in an external table. 
[MSSQL-Spark Connector User Creation](https://github.com/microsoft/sql-server-samples/blob/master/samples/features/sql-big-data-cluster/spark/data-virtualization/mssql_spark_connector_user_creation.ipynb)

**Comment by kenakamu** [comment]
No, my issue is different. I can not even comment to execute any spark when I have $ in my password

Ken
________________________________

**Comment by cdotzenrod** [comment]
I have the same issue.  This is my error:  Invalid status code '401' from https://52.188.45.190:30443/gateway/default/livy/v1/sessions with error payload

If I go to the code on the MSSQL-Spark Connector User Creation page, it won't let me run the first command.  I get this error when I run:  Create DATABASE connector_test_db
Invalid status code '401' from https://52.188.45.190:30443/gateway/default/livy/v1/sessions with error payload: .

Not sure what I'm supposed to do to fix this.

**Comment by rajmera3** [comment]
@shivsood Do you have any guidance here? Looks like @kenakamu is having issues because he has a $ in the password, while @cdotzenrod is having issues executing the SQL code

**Comment by cdotzenrod** [comment]
Any updates on this issue.  I was hoping to demo the Spark capability to my accounts but at this time am blocked.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT, @rajmera3, @shivsood -- please look into this potential documentation issue.

**Comment by cdotzenrod** [comment]
I followed the workshop doc word for word and got jammed when I tried the spark material. Everything prior worked like a charm.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by rajmera3** [comment]
@cdotzenrod Can you further explain your process and what you have done so far? I'm not sure why the Spark session is being invoked if you're still in the process of executing SQL

**Comment by cdotzenrod** [comment]
Just to help clarify,  I've working through Buck Woody's SQL Big Data Cluster workshop.  I was able to go through the hands on materials for the SQL tasks without an issue until I got to the part of workshop where I needed to run Spark and use Azure Data Studio notebooks connected to my cluster.  Here are details on what I did and where I got stuck.

Workshop site:  https://github.com/microsoft/sqlworkshops/blob/master/sqlserver2019bigdataclusters/SQL2019BDC/00%20-%20Prerequisites.md

Workshop chapter that I was trying to finish:  https://github.com/microsoft/sqlworkshops/blob/master/sqlserver2019bigdataclusters/SQL2019BDC/04%20-%20Operationalization.md

The latter portion of chapter 4 goes into running spark jobs on the BDC.  This tutorial link has issues when I try to run the spark code:  https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-spark?view=sqlallproducts-allversions
![image](https://user-images.githubusercontent.com/36054013/73077631-26759000-3e86-11ea-927b-b77ac1478835.png)

Does my update help?  Do you need any other details?

**Comment by rajmera3** [comment]
@cdotzenrod Are you able to run any spark code in general? For example, can you open a new notebook, choose PySpark or Scala and run a hello world job?

Also, on the machine with the kube_config, can you run kubectl get all -n {name of bdc}?
Is there a spark pod listed there?

**Comment by ruifcg** [comment]
Any updates on this issue?
I'm facing the same problem @cdotzenrod reported in the exact same step.
My knox psw also has a $.
Tried PySpark and Scale code and returns the same error.

**Comment by rajmera3** [comment]
@cdotzenrod @kenakamu I deployed a BDC with a "$" in the password (using a mac) on AKS. I have no issues running SQL nor Spark commands. 

Are you deploying using a Windows machine? Perhaps the $ needs to be escaped somehow?

If you can provide any more information that would be great

**Comment by cdotzenrod** [comment]
> @cdotzenrod Are you able to run any spark code in general? For example, can you open a new notebook, choose PySpark or Scala and run a hello world job?
> 
> Also, on the machine with the kube_config, can you run `kubectl get all -n {name of bdc}`?
> Is there a spark pod listed there?

I'm now able to run spark code on my cluster.  I ended up tearing down the 3 instance environment and building a new 1 instance environment with similar cores and memory to the 3 instance environment I used to have.  This simpler config seems to be having less challenges.  I would like to go back and make a multi instance env and see if I run into the same issues again at some point.

**Comment by kenakamu** [comment]
I have changed my password and recreated the environment. It still had issue for the first time but when I re-run the notebook by opening new one again, it did goes through.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT, @rajmera3, @shivsood -- please look into this issue.
