### ISSUE TITLE
SQL server manager doesn't allow changes unless the database is dropped and recreated

### ISSUE THREAD

**Issue by lypolyzo** [MicrosoftDocs/sql-docs#3815]
I tried using the designer but the command required to drop and recreate the table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76507156-d85c-e9f0-a214-3a9f1eb0f1fc
* Version Independent ID: 045c9c15-fbf9-abf9-c48a-904733e7ab42
* Content: [Change Column Order in a Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/change-column-order-in-a-table?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/change-column-order-in-a-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/change-column-order-in-a-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@lypolyzo -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task.

**Comment by lypolyzo** [comment]
Hello,
Thank you for reaching out to me!
I was trying to upload a video but the maximum size was 4MB so it didn’t got sent.

I did the following steps:
Select the table
Right click Design
Then in the Design tab I dragged up the column I wanted to change its order
I pressed CTRL+S to save the changes
I got an exception: Saving changes is not permitted. The changes you have made require the following tables to be dropped and re-created. You have either made changes to a table that can't be recreated or enabled the option Prevent saving changes that require the table to be re-created.

Thank you,
Lydia

**Comment by WilliamAntonRohm** [comment]
@lypolyzo -- Lydia, thank you for clarifying.

@stevestein -- Steve, please look into this issue 3815.

**Comment by stevestein** [comment]
@lypolyzo - thanks for the feedback!

Hi Lydia, 

Try unchecking **Prevent saving changes that require table re-creation** in **Tools>Options>Designers**:

![image](https://user-images.githubusercontent.com/9388190/71738619-f9e0d200-2e0b-11ea-876f-12c8b652009b.png)


Thanks,
Steve

**Comment by CarlRabeler** [comment]
@lypolyzo it has been over 2 months - so, I am going to assume that Steve's answer on January 4 solved your issue. Closing. If I am incorrect, please re-open.
Cheers, Carl

**Comment by vimanmg** [comment]
@stevestein @carlrabeler I came here with the same issue and this solution worked like a charm so take it as a yes! Thanks!!

**Comment by CarlRabeler** [comment]
excellent!
