### ISSUE TITLE
Installing package with sqlmlutils on SQL 2019 RTM causes DBCC CHECKDB to fail

### ISSUE THREAD

**Issue by filippz** [MicrosoftDocs/sql-docs#3818]
I noticed that if I use sqlmlutils  to install package and run DBCC CHECKDB I get an error:
```
Msg 8992, Level 16, State 1, Line 1
Check Catalog Msg 3851, State 1: An invalid row (class=128,depid=<LibrarzžyID>,depsubid=0) was found in the system table sys.syssingleobjrefs (class=128).
```
Removing the installed package gets things back into normal - so it might be caused by DBCC CHECKDB not fully "understanding" what's going on.

At the same time installed module can be found by SQL Python runtime for limited period of time (possibly an period of inactivity) after which the script that requires installed module fails with:

```
An external script error occurred: 

Error in execution.  Check the output for more information.
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "C:\ProgramData\MSSQLSERVER\Temp-PY\Appcontainer1\<GUID>\sqlindb_0.py", line nn, in transform
    from xxx import YYY
ModuleNotFoundError: No module named 'xxx'

SqlSatelliteCall error: Error in execution.  Check the output for more information.
```
Package is still visible in sys.external_libraries and exists in _C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\ExternalLibraries_

Installing the package via pip install directly seems to be working just fine (no entries that confuse DBCC CHECKDB) and SQL Pyhton runtime finds the modules every time

**Comment by msebolt** [comment]
@filippz  Thank you for the feedback.

This issue seems better geared towards the product team, please start a thread [here](https://social.msdn.microsoft.com/Forums/sqlserver/home?category=sqlserver) and link back to this issue.

**Comment by msebolt** [comment]
Closing issue now.
