### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Mitch-Wheat** [MicrosoftDocs/sql-docs#3820]
"which users can anticipate until performing an operation." should probably read "which users can't anticipate until performing an operation."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf421288-ba40-3904-72d1-07de1c69e211
* Version Independent ID: f388925a-a573-65ab-e0db-fe61245df123
* Content: [char and varchar (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/data-types/char-and-varchar-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/char-and-varchar-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@Mitch-Wheat Thank you for the feedback.

The documentation has been updated and is pending review.
