### ISSUE TITLE
i can not install sqlserver on mint 19.2

### ISSUE THREAD

**Issue by mrezalamei** [MicrosoftDocs/sql-docs#3822]
After executing this command 
sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list)"

It gives output

Malformed input, repository not added
--------------------------------------------------------------------------------------------
sorry my english is bad

**Comment by msebolt** [comment]
@mrezalamei Thank you for the feedback.

The command works on Ubuntu and is known to only occur with Mint, see https://github.com/typora/typora-issues/issues/2065.

Please refer to issue https://github.com/linuxmint/mintsources/issues/179 for updates.

**Comment by msebolt** [comment]
Closing issue now.

**Comment by mrezalamei** [comment]
> @mrezalamei Thank you for the feedback.
> 
> The command works on Ubuntu and is known to only occur with Mint, see [typora/typora-issues#2065](https://github.com/typora/typora-issues/issues/2065).
> 
> Please refer to issue [linuxmint/mintsources#179](https://github.com/linuxmint/mintsources/issues/179) for updates.

My problem is not solved

**Comment by mrezalamei** [comment]
By executing this command

`echo -e "$(wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list)" | sudo tee -a /etc/apt/sources.list`


My problem was solved
