### ISSUE TITLE
Typo of tull should be full.

### ISSUE THREAD

**Issue by MrZev** [MicrosoftDocs/sql-docs#3824]
"Disable or re-enable tull-text indexing for a table"  Says tull and not full.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5332b85c-c67f-2dfe-3fec-d4bc978822de
* Version Independent ID: 6239c2b0-c81e-f22c-bdff-1393cd372aab
* Content: [Create and Manage Full-Text Indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/search/create-and-manage-full-text-indexes?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/search/create-and-manage-full-text-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/search/create-and-manage-full-text-indexes.md)
* Product: **sql**
* Technology: **search**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by pmasl** [comment]
Fixing it. Thanks!
