### ISSUE TITLE
Fault in "Insert data into a table" step.

### ISSUE THREAD

**Issue by richardck** [MicrosoftDocs/sql-docs#3825]
I think something is wrong in this tutorial.  At the "Insert data into a table" step I entered:
-- Standard syntax  
INSERT dbo.Products (ProductID, ProductName, Price, ProductDescription)  
    VALUES (1, 'Clamp', 12.48, 'Workbench clamp')  
GO

and the result was:

Msg 2627, Level 14, State 1, Line 2
Violation of PRIMARY KEY constraint 'PK__Products__B40CC6EDC940AC97'. Cannot insert duplicate key in object 'dbo.Products'. The duplicate key value is (1).
The statement has been terminated.

So maybe something needs updating in the tutorial.
I think I had done everything else exactly as described.  All SQL commands were copied from this page using the "Copy" links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2627e7e1-2d0f-ed0c-30b8-2287c2612703
* Version Independent ID: 1f848e41-537b-029e-3289-f02158b53749
* Content: [T-SQL Tutorial: Create & query database objects - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/lesson-1-creating-database-objects?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/lesson-1-creating-database-objects.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/lesson-1-creating-database-objects.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@richardck Thank you for the feedback, assigning this to the author for review.

**Comment by jayfiled** [comment]
I think you may have already added a row with Primary Key value = 1.

I've just completed this page as per the instructions and didn't get an error.

Run 
SELECT * FROM Products

To see if there is already a row with PK = 1, or try entering another value that definitely hasn't been used before, or start again with a new DB?

**Comment by MikeRayMSFT** [comment]
Hi @richardck

I've gone through the steps to validate and they all work. 

As @jayfiled mentioned, the steps will fail if a row with the same primary key is inserted. 

We're considering adding a step at the end to reset everything if a reader needs to reset. 
## Delete test database

> [!CAUTION]
> This section is optional. Do not complete this section if you plan on proceeding to [lesson 2](lesson-2-configuring-permissions-on-database-objects.md).

If the steps before this section failed, you can drop the database, and then start over at [Create a database](#create-a-database).

The following command removes the test database. The change cannot be un-done. Use the following command only to reset the test scenario. 

To drop the database, run the following command.
```sql
USE [master]
GO

ALTER DATABASE [TestData] 
 SET SINGLE_USER 
 WITH ROLLBACK IMMEDIATE
GO

DROP DATABASE [TestData]
GO

CREATE DATABASE [TestData] 
GO
```
