### ISSUE TITLE
Location String & Example

### ISSUE THREAD

**Issue by n00611858** [MicrosoftDocs/sql-docs#3828]
The location should be in a string.  An example using the ODBC driver image earlier in the article would be helpful.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad6b54f-7b8d-0d9b-0ece-815b8874f751
* Version Independent ID: dee28cea-a153-0d80-b3f1-982aa4d16a87
* Content: [Access external data: ODBC generic types - PolyBase - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-configure-odbc-generic?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/polybase/polybase-configure-odbc-generic.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-odbc-generic.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@n00611858 Thank you for the feedback, assigning this to the author for review.
