### ISSUE TITLE
Rubbish examples

### ISSUE THREAD

**Issue by TDK1964** [MicrosoftDocs/sql-docs#3829]
Examples don't work, no myRv or myTS defined

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21550d41-12b6-37f6-0cd0-9212e0529d9d
* Version Independent ID: 2949dbcd-13bd-8777-0e85-6845726aa6e7
* Content: [rowversion (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/data-types/rowversion-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/rowversion-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@TDK1964 -- Tim, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue 3829.

**Comment by MikeRayMSFT** [comment]
Checking with engineering partners

**Comment by CarlRabeler** [comment]
looks like this issue was fixed. Closing. If I am incorrect, please re-open.
