### ISSUE TITLE
DEFERRABILITY is not documented

### ISSUE THREAD

**Issue by tsahi** [MicrosoftDocs/sql-docs#3830]
Azure Managed Database and SQL Server 2016 also return a DEFERRABILITY column, which isn't in the list in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1992bf85-dea1-2c1e-8769-24db3bcc8821
* Version Independent ID: dc662cb7-edd0-d470-1f6e-d61739778603
* Content: [sp_fkeys (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-fkeys-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-fkeys-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-fkeys-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@tsahi -- thank you for your feedback.

@stevestein -- please look into this potential documentation issue 3830.

**Comment by stevestein** [comment]
@tsahi - thanks for pointing this out. We created an internal work item (1710377) to track this and will go ahead and close this issue. 

Thanks!

**Comment by stevestein** [comment]
#please-close
