### ISSUE TITLE
Code for section "List python packages" is version dependant

### ISSUE THREAD

**Issue by MattiasWoldu** [MicrosoftDocs/sql-docs#3831]
EXECUTE sp_execute_external_script @language = N'Python'
    , @script = N'
import pip
for i in pip.get_installed_distributions():
    print(i)
'
GO

Does'nt work on Pyton 3.7. Need to use...

EXECUTE sp_execute_external_script @language = N'Python'
    , @script = N'
import pkg_resources
dists = [str(d) for d in pkg_resources.working_set]
print(dists)
'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37033ba2-66fb-1cf5-86e0-03b31c7ba7ac
* Version Independent ID: 2dc585ee-ac57-ac0d-cf03-12d623a18ff7
* Content: [Quickstart: Create Python scripts - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/tutorials/quickstart-python-create-script?view=sql-server-ver15#feedback)
* Content Source: [docs/advanced-analytics/tutorials/quickstart-python-create-script.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/tutorials/quickstart-python-create-script.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by garyericson** [comment]
#assign:garyericson

**Comment by garyericson** [comment]
@MattiasWoldu - Thanks for catching this and for providing sample code! I thought I'd make it look a little nicer (see below), but if you have any other suggestions, let me know. 

By the way, you can submit changes like these yourself by editing the article directly. Edits get sent to the author for review and sign-off. If you're interested, here are the instructions: https://docs.microsoft.com/en-us/contribute/

```python
EXECUTE sp_execute_external_script @language = N'Python'
, @script = N'
import pkg_resources
import pandas
dists = [str(d) for d in pkg_resources.working_set]
OutputDataSet = pandas.DataFrame(dists)
'
with result sets(([Package] nvarchar(max)))
```

**Comment by garyericson** [comment]
I've made the change, should be merged and published tomorrow.

#please-close

**Comment by mfsalomons** [comment]
When importing panda you must us it as such:
import panda as <name>
see: https://stackoverflow.com/questions/35697404/why-its-a-convention-to-import-pandas-as-pd

**Comment by stefanschulingkamp** [comment]
-- This example works fine.
EXECUTE sp_execute_external_script @language = N'Python', @script = 
N'import pkg_resources
import pandas as pd
dists = [str(d) for d in pkg_resources.working_set]
OutputDataSet = pd.DataFrame(dists)
'
WITH RESULT SETS(([Package] NVARCHAR(max)))
GO
