### ISSUE TITLE
Query Store CPU usage

### ISSUE THREAD

**Issue by kenjmartinii** [MicrosoftDocs/sql-docs#3833]
What exactly does the 'Query Store CPU usage' counter represent? CPU usage as a percentage? Time? The current documentation is extremely vague and not clear as to how the counter should be interpreted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c4d08b5-91cf-a86f-e4da-fb2adaaf836f
* Version Independent ID: 31bc3c36-742d-5f61-f4e7-5fc05567116f
* Content: [SQL Server, Query Store Object - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-query-store-object?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/performance-monitor/sql-server-query-store-object.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance-monitor/sql-server-query-store-object.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by msebolt** [comment]
@kenjmartinii Thank you for the feedback, assigning this to the author for review.

**Comment by rothja** [comment]
@kenjmartinii I apologize, but this issue was incorrectly assigned to you. @CarlRabeler could you please take  look at this issue? #reassign:CarlRabeler

**Comment by PRMerger16** [comment]
GitHub user kenjmartinii has been removed from the MicrosoftDocs organization, so they were automatically removed as an assignee.

**Comment by CarlRabeler** [comment]
@kenjmartinii  Indicates Query Store's usage of the CPU as a percentile of the use of the CPU by other processes

I am updating the docs with this clarification - update will be live later today. Thanks for the question. 
Carl
