### ISSUE TITLE
Misrepresentation of functionality

### ISSUE THREAD

**Issue by Mendolis** [MicrosoftDocs/sql-docs#3834]
Selecting different versions of SQL Server returns the same page - same information.  Example, this function returns different results between 2014 and 2019.  Yet, selecting 2014 returns the exact same information.  Gives me no confidence that the information on this site is valid or useful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 925d255f-0749-ef8b-bb60-c07680836f04
* Version Independent ID: 4d697adf-3d72-936e-a01f-9ca8e64a318d
* Content: [sys.dm_io_virtual_file_stats (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-io-virtual-file-stats-transact-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-2014#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-io-virtual-file-stats-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-io-virtual-file-stats-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@Mendolis  Thank you for the feedback.

This is a fault in the design of the `moniker` system used by Microsoft Docs.

You can see the specifics on versioning by looking for it in the article's meta-data, see [here](https://raw.githubusercontent.com/MicrosoftDocs/sql-docs/live/docs/relational-databases/system-dynamic-management-views/sys-dm-io-virtual-file-stats-transact-sql.md).

To make this information more accessible, please move this issue [here](https://github.com/MicrosoftDocs/feedback/issues) for feedback from the Docs team.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
