### ISSUE TITLE
Prereq Confusion

### ISSUE THREAD

**Issue by mwdarab** [MicrosoftDocs/sql-docs#3836]
Under prereq it says minimum RAM per VM should be 64GB, but at this github page, https://github.com/microsoft/sql-server-samples/tree/cu1-bdc/samples/features/sql-big-data-cluster/deployment/kubeadm/ubuntu , it says 32GB RAM. Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8bb827-4819-7b2d-490a-071f6b7b57a2
* Version Independent ID: 65b90b91-5946-b2d1-b97a-537bc9b014ca
* Content: [Configure Kubernetes with kubeadm - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-with-kubeadm?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/deploy-with-kubeadm.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-with-kubeadm.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@mwdarab Thank you for the feedback, assigning this to the author for review.

**Comment by MikeRayMSFT** [comment]
@mwdarab - thanks for the feedback. I reviewed this and updated the sql-server-samples article.

**Comment by marasinghe82** [comment]
Once deploy 
azdata bdc create --config-profile custom --accept-eula yes

Pod Name: mgmtproxy-7jk75 event log displays following. Please let me know how to resolve this issue

Readiness probe failed: cat: /var/run/container.ready: No such file or directory
