### ISSUE TITLE
FROM clause on Azure Synaptics (SQL DW) can be optional

### ISSUE THREAD

**Issue by jelther** [MicrosoftDocs/sql-docs#3838]
The part that mention the SQL Statement for Azure Synaptics (SQL DW), it shows the FROM clause as not optional for the DELETE statement.

However, omiting the FROM and aliasing the table in a WHERE is possible. For example, supose there are 2 tables,  **tableA** and **tableB** with column **col1**.

One can delete rows that exist in each other table using:

> DELETE tableA WHERE EXISTS (
>  SELECT TOP 1 1 FROM tableB tb WHERE tb.col1 = tableA.col1
> )

Me and my team ran into this problem due to the fact that an inner join is not allowed in a DELETE statement but this statement works for us.

**Comment by msebolt** [comment]
@jelther Thank you for the feedback, assigning this to the author for review.

**Comment by msebolt** [comment]
Article in question is https://docs.microsoft.com/sql/t-sql/statements/delete-transact-sql.

**Comment by CarlRabeler** [comment]
PR pending
