### ISSUE TITLE
SAS auth in COPY command 

### ISSUE THREAD

**Issue by abhijeethp** [MicrosoftDocs/sql-docs#3840]
hello, 
Is the copy command's auth with SAS currently functional as part of the preview? 
We are currently failing to use the COPY command on files stored in Azure Blob Storage and auth using SAS as we keep getting a 403 forbidden. but we are successful in downloading the file manually when we use the entire blob URI along with SAS token.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e651729e-3c87-4b5f-22c6-4db750f0eed9
* Version Independent ID: 60781c40-06b8-3b7f-e55b-d02011d7f89e
* Content: [COPY INTO (Transact-SQL) (preview) - (SQL Data Warehouse) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/copy-into-transact-sql?view=azure-sqldw-latest)
* Content Source: [docs/t-sql/statements/copy-into-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/copy-into-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @kevinvngo
* Microsoft Alias: **kevin**

**Comment by msebolt** [comment]
@rkinabhi Thank you for the question, assigning the author for review.

Please note specific product questions might be more suited for the product team.  Please see either:

- [SQL Server forums](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/home?category=sqlserver)
- [SQL Server feedback](https://feedback.azure.com/forums/908035-sql-server)

**Comment by kevinvngo** [comment]
Hi, is the SAS token at the container or blob level? Can you please send the details on the issue to the following distribution list and we will take a look: sqldwcopypreview@service.microsoft.com

**Comment by kevinvngo** [comment]
#please-close
