### ISSUE TITLE
Incorrect BNF notation

### ISSUE THREAD

**Issue by MikeHowell-TransferenceUnLimited** [MicrosoftDocs/sql-docs#3841]
The BNF you have used has "no root".  As it stands, you would never type in a SELECT statement at all.  I would argue it written "upside-down".

** &lt;SELECT statement...  Your choice of "SELECT Statement" name is meaningless since what has WITH XML... got to do with the definition of the SELECT statement itself? **

&lt;SELECT statement&gt; ::=    
    [ WITH { [ XMLNAMESPACES ,] [ &lt;common_table_expression&gt; [,...n] ] } ]  
    &lt;query_expression&gt;   
    [ ORDER BY { order_by_expression | column_position [ ASC | DESC ] }   
  [ ,...n ] ]   
    [ &lt;FOR Clause&gt;]   
    [ OPTION ( &lt;query_hint&gt; [ ,...n ] ) ]   
&lt;query_expression&gt; ::=   
    { &lt;query_specification&gt; | ( &lt;query_expression&gt; ) }   
    [  { UNION [ ALL ] | EXCEPT | INTERSECT }  
        &lt;query_specification&gt; | ( &lt;query_expression&gt; ) [...n ] ]   

** &lt;Query_specification&gt;  is never referred to implying you never type SELECT ... **

&lt;query_specification&gt; ::=   
SELECT [ ALL | DISTINCT ]   
    [TOP ( expression ) [PERCENT] [ WITH TIES ] ]   

** You don't define select_list **
    &lt; select_list &gt;   
    [ INTO new_table ]   
    [ FROM { &lt;table_source&gt; } [ ,...n ] ]   
    [ WHERE &lt;search_condition&gt; ]   
    [ &lt;GROUP BY&gt; ]   
    [ HAVING &lt; search_condition &gt; ]   

I have not checked for any other errors as the errors I have listed are so severe that I do not trust your BNF notation any futher.

The old help screens *had* the correct BNF.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da7ee936-5d16-3ab9-97dc-35fceb3ebe29
* Version Independent ID: 9daaeef8-0dc3-e241-5b65-fbe2b217e191
* Content: [SELECT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/queries/select-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/select-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@MikeHowell-TransferenceUnLimited Thank you for the feedback, assigning this to the author for review.

**Comment by VanMSFT** [comment]
Hi @MikeHowell-TransferenceUnLimited! Thanks for the feedback. We really appreciate it. We will leave the syntax as is for now. 

```
<SELECT statement> ::=    
    [ WITH { [ XMLNAMESPACES ,] [ <common_table_expression> [,...n] ] } ]  
    <query_expression> 
```

The WITH statement is surrounded in brackets, and therefore, optional. We list details on this syntax in the Remarks section. `<query_expression>` is not optional, and therefore needs to be specified.

```
<query_expression> ::=   
    { <query_specification> | ( <query_expression> ) }   
    [  { UNION [ ALL ] | EXCEPT | INTERSECT }  
        <query_specification> | ( <query_expression> ) [...n ] ] 
```

`<query_specification>` is specified in `<query_expression>`, which is surrounded in braces and a requirement.

`<select list>` is defined in the [SELECT Clause](https://docs.microsoft.com/sql/t-sql/queries/select-clause-transact-sql) in the Remarks section.

Thanks again for the feedback. We will not be changing this syntax.
