### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by hmortada** [MicrosoftDocs/sql-docs#3842]
Permissions
The sp_addlinkedserver statement requires the ALTER ANY LINKED SERVER permission. (The SQL Server Management Studio New Linked Server dialog box is implemented in a way that requires membership in the sysadmin fixed server role.)
On both Servers? in other words, what is the minimal permission required on for the remote login on the remote server, is it only the permissions required to execute the statement or sysadmin is required on the remote login as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 051788f8-a729-7a59-8b2f-5e2ba2cf62c2
* Version Independent ID: 30b9fe82-bc80-cf19-6ee3-7ce45a826975
* Content: [sp_addlinkedserver (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-addlinkedserver-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-addlinkedserver-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-addlinkedserver-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@hmortada Thank you for the feedback, assigning this to the author for review.

**Comment by CarlRabeler** [comment]
please assign to @VanMSFT

**Comment by VanMSFT** [comment]
Hi @hmortada! Thanks for submitting this question. Sorry for the delay!

The only permissions you should need on the remote server to create the linked server is the CONNECT permissions. The permission should be the same as if you were trying to connect directly to that remote server. I'll confirm this and get back to you.

**Comment by CarlRabeler** [comment]
@VanMSFT do you have any update on this issue?

**Comment by VanMSFT** [comment]
Thanks, @CarlRabeler.

@hmortada - We'll go ahead and close this issue since there are no other concerns.
