### ISSUE TITLE
Compatibility Distributor SQL Server 2018 -> SQL Server 2019

### ISSUE THREAD

**Issue by Jamal27** [MicrosoftDocs/sql-docs#3846]
Is correct this?

Pub - SQL Server 2008 R2
Dist - SQL Server 2019
Sub - SQL Server 2008 R2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e7c4bee-dbaa-2470-b96e-0822989eb194
* Version Independent ID: 88ca602f-598e-6da4-8f9a-224880a2b8e9
* Content: [Replication Backward Compatibility - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/replication-backward-compatibility?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/replication/replication-backward-compatibility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/replication-backward-compatibility.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @Jamal27 , thanks for contacting Microsoft! For transactional  or merge replication?

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Actually.. it should work for either but let me confirm :)

Thanks!
Masha from the SQL Docs team

**Comment by Jamal27** [comment]
Welcome, for transactional replication, if you look right don't make sense,
cause another version haven't the support.

Thanks

**Comment by MashaMSFT** [comment]
Hi @Jamal27 , thanks for your patience as we researched this. Yes, the following topology will work for both transactional and merge replication:

Pub - SQL Server 2008 R2
Dist - SQL Server 2019
Sub - SQL Server 2008 R2

However, please note that SQL Server 2008 R2 is out of extended support so no security fixes will be available for your publisher and subscriber, unless you've purchased an extended security update subscription. You can find more information here: https://docs.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-end-of-life-overview?view=sql-server-ver15

I hope that helps and please let me know if you have any further questions? Otherwise, I will proceed with closing out this Git Issue in a few business days. 

Thanks!
Masha from the SQL Docs team

**Comment by Jamal27** [comment]
Hi.

Thanks for answering my questions, but i have any doubts yet.

In documentation say that publisher can be 2008 version and support
distributor in 2019 version, but SQL server 2012/2014 doesn't have support
for distributor in 2019 version, is it correct?

Regards.

**Comment by MashaMSFT** [comment]
Hi @Jamal27 ,

Thanks for reaching out again!  If your distributor is SQL Server 2019, then it is compatible with a SQL Server 2019 publisher, and a subscriber that is within two versions of the publisher (so SQL 2016 is the lowest) for transactional replication, and any version of SQL Server (So SQL 2008 at the lowest) for merge replication.

The rules are defined in the documentation: 
![image](https://user-images.githubusercontent.com/32783170/71701603-6661bf80-2d7f-11ea-8723-d3aefa82e954.png)

I hope that helps and please let me know if you have any further questions.

Thanks!
Masha from the SQL Docs team

**Comment by Jamal27** [comment]
Thanks very much.

Sorry for my lack of understanding, see this image below, why SQL 2008 can
replicate to SQL 2019 and SQL 2012 not?

[image: image.png]

**Comment by MashaMSFT** [comment]
Hi @jamal27, my apologies, the image didn't come through, but I  believe it's showing that SQL 2019 is an acceptable subscriber for SQL 2008, is that correct? 
![image](https://user-images.githubusercontent.com/32783170/71846022-6c58e880-307e-11ea-931b-c77c6e0a5905.png)

Thank  you so much for bringing this to our attention! This is actually an error with the documentation, and will be fixed later today. For transactional replication, the subscriber must be within two versions of the publisher. 

My apologies for any confusion, and thanks for helping us fix this :)
Masha from the SQL Docs team

**Comment by Jamal27** [comment]
No problem, thank you very much for answering my questions.

Regards.
Reginaldo Silva.

**Comment by MashaMSFT** [comment]
Hi @jamal27, thanks again for improving our documentation! This change is now live :) I will close out this Git Issue but please feel free to reach out should you need anything further from us.

Thanks again and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
