### ISSUE TITLE
Persistent not needed for indexing

### ISSUE THREAD

**Issue by winBoscoe** [MicrosoftDocs/sql-docs#3847]
https://www.brentozar.com/archive/2019/12/the-two-ways-to-fix-non-sargable-queries/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f034f3c2-58c6-6a37-e5d3-3feb40c32681
* Version Independent ID: 3efcf41e-30f3-6595-276b-abc3fbb8e69d
* Content: [computed_column_definition (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-computed-column-definition-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/alter-table-computed-column-definition-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-table-computed-column-definition-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@winBoscoe -- thank you for your feedback and the tip.

@CarlRabeler -- please look into this potential documentation issue 3847.

**Comment by CarlRabeler** [comment]
@winBoscoe Please clarify the change that you would like to see in this topic related to indexing or not indexing of persisted columns - or, better yet, click Edit in the upper right-hand corner and propose a change for someone on our team to review.
Thanks - Carl
