### ISSUE TITLE
Ubuntu Version in script

### ISSUE THREAD

**Issue by mwdarab** [MicrosoftDocs/sql-docs#3850]
Under https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-script-single-node-kubeadm?view=sql-server-ver15#instructions-to-deploy-sql-server-big-data-cluster the setup-bdc.sh script has a line in it that says: 

export DOCKER_TAG="2019-GDR1-ubuntu-16.04"

Will this work fine even if you are deploying to Ubuntu 18.03? Or should there be another setup-bdc.sh script that is used for 18.03 version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b52c141e-1793-43bb-5a16-5d82c1eff988
* Version Independent ID: 93cbcb06-0108-3f1d-990d-b8ef8ad31756
* Content: [Deploy single node kubeadm cluster - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-script-single-node-kubeadm?view=sql-server-ver15#instructions-to-deploy-sql-server-big-data-cluster)
* Content Source: [docs/big-data-cluster/deployment-script-single-node-kubeadm.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deployment-script-single-node-kubeadm.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @mihaelablendea
* Microsoft Alias: **mihaelab**

**Comment by WilliamAntonRohm** [comment]
@mwdarab -- Mohammad, thank you for your question.

@mihaelablendea -- Mihaela, please look into this issue 3850.

cc @MightyPen as a writer

**Comment by MightyPen** [comment]
@MikeRayMSFT Hi Mike, I do not see the phrase - &nbsp; `export DOCKER_TAG` &nbsp; - in the article, although the original poster makes the phrase a focus of this Issue #3850?
Mihaela is the formal owner of the article in question.

cc: @MihaelaBlendea

**Comment by 3ICE** [comment]
A line of the article links to a file:
https://raw.githubusercontent.com/microsoft/sql-server-samples/master/samples/features/sql-big-data-cluster/deployment/kubeadm/ubuntu-single-node-vm/setup-bdc.sh

In it is the version number in question. On line 49.

**Comment by MightyPen** [comment]
FWIWorth, that line (49) has been updated in the past, to represent this or that particular version.
Maybe an inline `#` comment could be added to clarify that this value can be changed (or cannot be changed?).

**Comment by WilliamAntonRohm** [comment]
@mihaelablendea, @MikeRayMSFT -- please look into this issue.

**Comment by mihaelablendea** [comment]
Ubuntu 18.x is not yet one of the supported host OSes: https://docs.microsoft.com/en-us/sql/big-data-cluster/release-notes-big-data-cluster?view=sql-server-ver15#supported-platforms
