### ISSUE TITLE
Prerequisites lists SQL Server 2019

### ISSUE THREAD

**Issue by klennan** [MicrosoftDocs/sql-docs#3851]
The .NET Framework 4.6.1 section says "For all editions of SQL Server 2019..." on this SQL Server 2017 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa839a1-df21-b566-b798-bf17159c4c74
* Version Independent ID: 97d386f4-c657-eaba-a62c-404ced145cb2
* Content: [Install SQL Server 2016 on Server Core - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-on-server-core?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/install-windows/install-sql-server-on-server-core.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/install-sql-server-on-server-core.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @klennan, thanks for bringing this to our attention! Let me look into this.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @klennan, thanks again for reaching out! I've submitted a change to update the documentation and it should be live either later today, or possibly early next week. I'm going to close out this Git Issue, but please feel free to comment should you need anything further. 

Thanks for improving our documentation and hope you have a wonderful weekend!
Masha from the SQL Docs team

**Comment by reinaldokibel** [comment]
any updates?  I still see only references to WIN 2012 R2 and none to Win 2016 nor 2019.    and for SQL Server there are no references to SQL Server 2019 still.

**Comment by MashaMSFT** [comment]
Hi @reinaldokibel , thanks for contacting Microsoft! Actually, the issue pointed out by @klennan  is that on a page for SQL Server 2017, the product was referencing SQL Server 2019 erroneously, which has been resolved. 

However, having said that, I do see that Windows 2019 is missing from this article so will process that change. 

Thanks for bringing it to our attention!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @reinaldokibel , this change has been processed and is now live.

Thanks for improving our documentation! Hope you have a wonderful rest of your day :) 
Masha from the SQL Docs team
