### ISSUE TITLE
Blocked Process Report - Duration Units

### ISSUE THREAD

**Issue by BeginTry** [MicrosoftDocs/sql-docs#3852]
[BLOCKED_PROCESS_REPORT ~ SQL 2017.txt](https://github.com/MicrosoftDocs/sql-docs/files/3989846/BLOCKED_PROCESS_REPORT.SQL.2017.txt)

The documentation indicates the Duration of a Blocked Process Report is in milliseconds. I believe it should be microseconds.
Run the attached .txt TSQL script. It does the following:

- Sets the system configuration "_blocked process threshold (s)_" to 5 seconds.
- Creates a logging table.
- Creates a SQL Agent Job (for receiving an alert)
- Creates a (WMI) SQL Alert

Make sure _Token Replacement_ is enabled in SQL Server Agent properties (see _Alert System_ page). Enabling the setting may require a restart of the SQL Server Agent service.

In SSMS, open two query windows. In the first window, run the following:
```
CREATE TABLE tempdb.dbo.Employee (
	EmployeeID INT IDENTITY
		CONSTRAINT PK_Employee PRIMARY KEY,
	FirstName VARCHAR(128),
	LastName VARCHAR(128)
);
TRUNCATE TABLE tempdb.dbo.Employee;

BEGIN TRAN

INSERT INTO tempdb.dbo.Employee (FirstName, LastName)
VALUES
	('Larry', 'Bird'),
	('Jaylen', 'Brown'),
	('Marcus', 'Smart');

--Wait for 10 seconds
WAITFOR DELAY '00:00:10';	

COMMIT
```
Then immediately run the following code in the second SSMS tab/window:
```
SELECT *
FROM tempdb.dbo.Employee; 
```
This should generate a blocking event. The SQL Agent alert will respond by executing the SQL Agent job, which in turn writes data for the blocked process report event to a table. The blocking should be at most ten seconds. When I query the table, the duration is 7,014,000 (see attached TextData1.xml.log file).

[TextData1.xml.log](https://github.com/MicrosoftDocs/sql-docs/files/3989928/TextData1.xml.log)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e28c9e-b675-91cd-4b2b-d1bc662aff7a
* Version Independent ID: b621377d-7837-3282-241b-7360b1fa473f
* Content: [Blocked Process Report Event Class - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/event-classes/blocked-process-report-event-class?view=sql-server-ver15)
* Content Source: [docs/relational-databases/event-classes/blocked-process-report-event-class.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/event-classes/blocked-process-report-event-class.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@BeginTry -- Dave, thank you for your feedback and your detailed test case  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please review the above-mentioned PR 13376.
