### ISSUE TITLE
sys.schemas missing

### ISSUE THREAD

**Issue by LarnuUK** [MicrosoftDocs/sql-docs#3853]
Is it intentional that `sys.schemas` is omitted from this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e44d6f5-818c-fdf0-8169-d23d0b6a0b68
* Version Independent ID: af6b6d8b-d984-faba-ff8e-ddf7fe954f36
* Content: [Object Catalog Views (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/object-catalog-views-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-catalog-views/object-catalog-views-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/object-catalog-views-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@LarnuUK -- Thom, thank you for your question.

@stevestein -- Steve, please look into this issue 3853.

**Comment by stevestein** [comment]
@LarnuUK - thanks for the feedback!

Hi Thom,
The sys.schemas page is presented at a higher node level in the TOC and not in the Object node:

![image](https://user-images.githubusercontent.com/9388190/71739195-a2436600-2e0d-11ea-92c0-9004c9464340.png)

Thanks,
Steve
