### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by mwdarab** [MicrosoftDocs/sql-docs#3855]
Please update under the Prerequisites section:

Latest version of Azure Data Studio Insiders build - Do we still need this or does regular ADS allow this too (since SQL 19 is in GA)?
SQL Server 2019 (15.x) extension installed in Azure Data Studio - This extension has been deprecated. Please include the updated one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 057a02b3-bff9-5d98-8de5-4842e1ecdea7
* Version Independent ID: 974e4fe2-cb21-a8c4-a908-c28998a044fd
* Content: [Manage SQL Server big data cluster with controller dashboard - Manage SQL Server big data cluster with controller dashboard](https://docs.microsoft.com/en-us/sql/big-data-cluster/manage-with-controller-dashboard?view=sql-server-ver15#prerequisites)
* Content Source: [docs/big-data-cluster/manage-with-controller-dashboard.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/manage-with-controller-dashboard.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @yualan
* Microsoft Alias: **alanyu**

**Comment by WilliamAntonRohm** [comment]
@mwdarab -- Mohammad, thank you for your close reading.

@yualan -- Alan, please look into this issue 3855.

cc @MightyPen as a writer

**Comment by MightyPen** [comment]
@yualan , @MikeRayMSFT Guys, I set MikeRayMSFT as the associated writer Assignee, for this Issue #3855. Every Issue that a PM is responsible for also needs a writer as a co-Assignee, just to watch - prompt - assist if necessary.

 _Reason why Mike was chosen:_ &nbsp; &nbsp; Mike owns a lot of the other docs/big-data-cluster/ .md articles.

However, Alan is still the primary Assignee, and is the `ms.author` for this article.
Thanks.

cc: @WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
@yualan -- Alan, please look into this issue.

**Comment by MikeRayMSFT** [comment]
I'm following up on this again.

**Comment by WilliamAntonRohm** [comment]
@yualan -- thank you for answering.

@mwdarab -- I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by yualan** [comment]
Hi, why was this issue reopened again? @WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
@yualan -- Alan, the current text under Prerequisites appears to be still out of date:
> The following prerequisites are required to launch the notebook:
> Latest version of Azure Data Studio Insiders build
> SQL Server 2019 (15.x) extension installed in Azure Data Studio

Please close this issue if my understanding is incorrect.
