### ISSUE TITLE
Listing trace flags to understand inner workings of filtered indexes

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#3861]
There are many internal trace flags that are useful to understand the limitations of filtered indexes.
eg: 8606,8607,8612,8615,3604,2372,8675,8619

Perhaps these could become documented and available so that customers can understanding what is going on 'under the hood'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e578e8fc-b9da-8c8d-5a4a-64084f1204de
* Version Independent ID: 4adb8a19-ff61-5724-9f01-fb673efb7991
* Content: [Create Filtered Indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/create-filtered-indexes?view=sql-server-ver15)
* Content Source: [docs/relational-databases/indexes/create-filtered-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/create-filtered-indexes.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@brettshearer -- Brett, thank you for your suggestion.

@MikeRayMSFT -- Mike, please look into this issue 3861.

**Comment by MikeRayMSFT** [comment]
@brettshearer,

Thank you for the submission. At this time we are not documenting the currently undocumented trace flags.

**Comment by pmasl** [comment]
@brettshearer to give you some additional context, while the product behavior is documented, implementation details are not. Trace flags are documented on a need to know basis, either as bug fix enablers, or as non standard perf/scale enablers that we recommend customers to use in specific scenarios (and retire once said behavior is made default into the product). Many trace flags you mention and many others are there for debugging purposes, and were never tested at scale in production systems for customer use, and are therefore unsupported, and therefore undocumented.
