### ISSUE TITLE
OLTP is not supported for database diagram.

### ISSUE THREAD

**Issue by xaamt** [MicrosoftDocs/sql-docs#3862]
Unfortunatly, there is no reference to mention that In-Memory OLTP is not supported for database diagram.
So, consider that, please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f34d1d9-996d-a5b7-c525-a0c8b2275373
* Version Independent ID: 8d8a4eff-4a28-a749-97c8-b42c7e55c477
* Content: [Features not supported - in-memory OLTP - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/unsupported-sql-server-features-for-in-memory-oltp?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/in-memory-oltp/unsupported-sql-server-features-for-in-memory-oltp.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/unsupported-sql-server-features-for-in-memory-oltp.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by WilliamAntonRohm** [comment]
@xaamt -- thank you for your feedback.  

@MightyPen -- please look into this potential documentation issue 3862.

**Comment by MightyPen** [comment]
I am looking at this.

**Comment by MightyPen** [comment]
@xaamt Hi, You have a fair point here.  However, the whole **SSMS** Database Diagram feature has been in flux for the past several months.  So I am unable to make a robust addition to the documentation article at this time.

I am Closing this Issue #3862 , for now.
Thank you.

cc: @markingmyname - who might know more about the Diagram feature's latest status.
