### ISSUE TITLE
correct comma position

### ISSUE THREAD

**Issue by trynio** [MicrosoftDocs/sql-docs#3864]
Is this the correct syntax?
FORMAT ( value, format [, culture ] ) 
Isn't it like that?
FORMAT ( value, format, [ culture ] )
I'm not sure that's why I'm asking.
Best regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: L2VuLXVzL3NxbC90LXNxbC9mdW5jdGlvbnMvZm9ybWF0LXRyYW5zYWN0LXNxbA==
* Version Independent ID: L2VuLXVzL3NxbC90LXNxbC9mdW5jdGlvbnMvZm9ybWF0LXRyYW5zYWN0LXNxbA==
* Content: [FORMAT (Transact-SQL) - SQL Server | Microsoft Docs](https://docs.microsoft.com/en-us/sql/t-sql/functions/format-transact-sql?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1&l=EN-US&k=k(FORMAT_TSQL)%3Bk(sql13.swb.tsqlresults.f1)%3Bk(sql13.swb.tsqlquery.f1)%3Bk(MiscellaneousFilesProject)%3Bk(DevLang-TSQL)&rd=true&irgwc=1&OCID=AID2000142_aff_7811_1246483&tduid=(ir__qxctr9t3ggkfrlspkk0sohz30n2xlxenfhhsl0sf00)(7811)(1246483)((e8312d9424d97e85b2cd2687de535746)(278693)(2353959)(v030400009109143e51396fdd42b4bd55c30594b55a22)())(e8312d9424d97e85b2cd2687de535746)&irclickid=_qxctr9t3ggkfrlspkk0sohz30n2xlxenfhhsl0sf00&view=sql-server-ver15#syntax)
* Content Source: [docs/t-sql/functions/format-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/format-transact-sql.md)

**Comment by LarnuUK** [comment]
`FORMAT ( value, format [, culture ] )` is correct. Parts inside the brackets (`[]`) are optional. If `FORMAT ( value, format, [ culture ] )` *were* the correct syntax, then when you omit a value for `culture` you would have to have a trailing comma (`,`):

```sql
SELECT FORMAT(GETDATE(),'dd/MM/yyyy',);
```
If you try that, you'll get an error.

**Comment by WilliamAntonRohm** [comment]
@trynio -- thank you for your question.

@LarnuUK -- thank you for your answer  :^)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
