### ISSUE TITLE
Example A says "public" in the description, yet script uses "dbo"

### ISSUE THREAD

**Issue by tussosedan** [MicrosoftDocs/sql-docs#3865]
Please either align them or explain the difference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0bede25-95a9-222d-eabe-7ff229096f53
* Version Independent ID: 7b33301e-1863-b3b2-4391-cb30a6908d2c
* Content: [CREATE DATABASE AUDIT SPECIFICATION - SQL Server (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-audit-specification-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-database-audit-specification-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-database-audit-specification-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@tussosedan -- Alex, thank you for your feedback.

@VanMSFT -- Van, please look into this issue 3865.

**Comment by VanMSFT** [comment]
Hi @tussosedan! Thanks for the feedback. The changes will be updated shortly.
