### ISSUE TITLE
Setting @log_backup_freq = '0' doesn't work on 2017 CU16

### ISSUE THREAD

**Issue by Morshedk** [MicrosoftDocs/sql-docs#3868]
Setting @log_backup_freq = '0' doesn't work on 2017 CU16, I get 
Msg 45207, Level 17, State 4, Procedure managed_backup.sp_add_task_command, Line 102 [Batch Start Line 13]
The value specified for parameter @log_backup_freq is not valid. A valid scheduling parameter is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a4c9ab1-5694-1d4e-4517-4376836f6336
* Version Independent ID: 050dd382-015b-7d74-044a-abd6e74a1a9a
* Content: [managed_backup.sp_backup_config_schedule (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/managed-backup-sp-backup-config-schedule-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-stored-procedures/managed-backup-sp-backup-config-schedule-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/managed-backup-sp-backup-config-schedule-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@Morshedk -- thank you for your feedback.  You are welcome to add this to [SQL Server Feedback](https://aka.ms/sqlfeedback).

@MikeRayMSFT -- please look into this issue 3868.

**Comment by MikeRayMSFT** [comment]
I've verified that the correct way to prevent log backups is to set the value to one of the following:
 '0:00', '0:0', '00:0', '00:00'

When any of these zero values are passed, Managed Backup will not take log backups. If the database is in FULL or BULK_LOGGED recovery model the user will need to handle log backups themselves or they will eventually run into log full issues or out of disk space issues.

I'm working on an update to the documentaiton.
