### ISSUE TITLE
Code labeled VB

### ISSUE THREAD

**Issue by CODevOp** [MicrosoftDocs/sql-docs#3869]
[Enter feedback here]
There are 2 code windows on this page, the first page is labeled VB instead of Transact-SQL. The second window is not labeled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20768d1f-2859-d266-e79c-d04ee97d615e
* Version Independent ID: 34a20aa9-9b34-aace-ea59-bc867e7af5f9
* Content: [managed_backup.sp_backup_config_advanced (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/managed-backup-sp-backup-config-advanced-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/managed-backup-sp-backup-config-advanced-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/managed-backup-sp-backup-config-advanced-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@CODevOp -- Bret, thank you for bringing this to our attention.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review the above-mentioned PR 13404.
