### ISSUE TITLE
Formatting DateTime

### ISSUE THREAD

**Issue by michaelAngeloEgypt** [MicrosoftDocs/sql-docs#3874]
Hi, I was expecting to see a mention for the Format function here
https://docs.microsoft.com/en-us/sql/t-sql/functions/format-transact-sql?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972a4352-4957-49fc-0c39-3e254d130fe7
* Version Independent ID: cc865d87-1527-9f72-3cbc-7b036f4503df
* Content: [Date and Time Data Types and Functions - SQL Server (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql?view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/t-sql/functions/date-and-time-data-types-and-functions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/date-and-time-data-types-and-functions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@michaelAngeloEgypt -- Michael, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue 3874.

**Comment by CarlRabeler** [comment]
@michaelAngeloEgypt thanks - adding FORMAT now
