### ISSUE TITLE
URL of the sample notebook is broken (404)

### ISSUE THREAD

**Issue by ckarras** [MicrosoftDocs/sql-docs#3876]
When I try to run the curl command for the sample notebook, I get an error "404: Not found", for the following URL: https://raw.githubusercontent.com/microsoft/sql-server-samples/master/samples/features/sql-big-data-cluster/spark/data-virtualization/mssql_spark_connector.ipynb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e7588-f740-33b4-303b-e927f3400414
* Version Independent ID: 186607e3-fd55-5d9b-2cfc-26120fc438ad
* Content: [Connect Spark to SQL Server - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/spark-mssql-connector?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/spark-mssql-connector.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/spark-mssql-connector.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@ckarras -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue 3876.

**Comment by MikeRayMSFT** [comment]
@ckarras - thanks - checking.
