### ISSUE TITLE
Table is broken

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/sql-docs#3879]
![oracle-publishing-overview](https://user-images.githubusercontent.com/40815708/71575229-90bd3e00-2b2f-11ea-9e55-178886f0aaec.png)

https://docs.microsoft.com/en-us/sql/relational-databases/replication/non-sql/oracle-publishing-overview?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38d5eb8d-5232-0fb5-bf7e-a07772f52059
* Version Independent ID: a998bab8-a58d-02c0-94a3-76235e5fa2cb
* Content: [Oracle Publishing Overview - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/non-sql/oracle-publishing-overview?view=sql-server-ver15)
* Content Source: [docs/relational-databases/replication/non-sql/oracle-publishing-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/non-sql/oracle-publishing-overview.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @hyoshioka0128 , thanks so much for bringing this to our attention! I've merged a change that will fix it, and it should be live either later today, or possibly tomorrow.w

Thanks for improving our documentation! I will close out this Git Issue but please feel free to comment should you need anything further.

Thanks and hope you have a great rest of your day!
Masha from the SQL Docs team
