### ISSUE TITLE
What constitutes a line and what does not?

### ISSUE THREAD

**Issue by wwmbes** [MicrosoftDocs/sql-docs#3880]
It seems that the ErrorLine number produced by the ERRORLINE() function has an unspecified way of counting lines which is not the number of lines starting from the beginning of the file. sometimes it seems as if comments are included in the line count, while at other times it does not. It would be helpful if this information was clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25598555-85ee-3a62-914c-79bb8a6f7511
* Version Independent ID: 351bf3d8-60ed-8969-eeb2-34844fbbdaca
* Content: [ERROR_LINE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/error-line-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/error-line-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/error-line-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by LarnuUK** [comment]
Could you give some examples? I can't think of times when the line number has *not* been the line number. The line number is relevant to the scope. So, for example, say you run the below:
```sql
/*Use a relevent sandbox database
  that you have on your instance.*/
USE Sandbox;
GO

--Created by Thom Andrews 
CREATE PROC dbo.YourProc @I int AS  
BEGIN

    --A comment
    SELECT 10 / @i; 

END;
GO

EXEC dbo.YourProc 2;
GO
EXEC dbo.YourProc 0;
GO

DROP PROC dbo.YourProc;
```

If you run that, you'll get the error below:
> Msg 8134, Level 16, State 1, Procedure dbo.YourProc, Line 7
> Divide by zero error encountered.

Line 7 is correct, not 18, because the error occurred on line 7 withing the SP. If I add line numbers at the end of each line in the SP this becomes apparent:
```sql
                                        --1
--Created by Thom Andrews               --2
CREATE PROC dbo.YourProc @I int AS      --3
BEGIN                                   --4
                                        --5
    --A comment                         --6
    SELECT 10 / @i;                     --7
                                        --8
END;                                    --9
```

Perhaps this is the behaviour you're misunderstanding?

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please look into this issue 3880.  There is some confusion here with the line counting in these examples.  That is, [Example A](https://docs.microsoft.com/en-us/sql/t-sql/functions/error-line-transact-sql?view=sql-server-ver15#a-using-error_line-in-a-catch-block) indicates the error is on line 4, where it would seem to be line 3 (counting comment lines) or line 2 (not counting comment lines).

**Comment by MikeRayMSFT** [comment]
@wwmbes - the article explains that 
> This function returns the line number of occurrence of an error that caused the CATCH block of a TRY...CATCH construct to execute.

I see the inconsistencies noted by @WilliamAntonRohm and will connect with engineering to check.
