### ISSUE TITLE
Example A bitmask to base_10 comment

### ISSUE THREAD

**Issue by jackapie** [MicrosoftDocs/sql-docs#3881]
The comment in Example A states:
The bitmask is: power(2, (2-1)) + power(2, (3-1)) + power(2, (4-1)) = 14.
This bitmask translates into base_10 as: 1 + 4 + 9 = 14.

The translation looks wrong to me, it should be 2 + 4 + 8 = 14, since: power(2, 2-1) is 2^1, 
power(2, 3-1) is 2^2 two squared
and power(2, 4-1) is 2^3 two cubed

Incidentally, this does returns the same value as 1 + 4 + 9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52d12681-a6f1-258a-d25a-b47741883a88
* Version Independent ID: 72ad45a0-a3d2-1b62-d7c5-2237909d4f4a
* Content: [COLUMNS_UPDATED (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/columns-updated-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/columns-updated-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/columns-updated-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@jackapie -- Jacqueline, thank you for your feedback.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@jackapie -- Jacqueline, I have updated the documentation and it should be live by tomorrow.
