### ISSUE TITLE
BSOD When attempting to install

### ISSUE THREAD

**Issue by briannipper** [MicrosoftDocs/sql-docs#3882]
Huge fan of SSMS.

Specs:
ASUS Laptop (Model K501UW)
CPU x64
16 GB RAM
500 GB SSD for primary hard drive (OS and Apps)
Secondary Drive is also SSD that I instal existing DB data directories and logs to
Windows 10 1906 (OS Build 18362.535)

Currently running SSMS v18.2
Copy Info from Installed version:
SQL Server Management Studio						15.0.18142.0
Microsoft Analysis Services Client Tools						15.0.1389.0
Microsoft Data Access Components (MDAC)						10.0.18362.1
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.18362.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.18362

I've tried to install using the EXE (SSMS-Setup-ENU.exe) for version 18.4.

It prompts to run as admin and after a moment (maybe a few seconds) the computer blue screens.

I haven't been able to find any info in a temp directory (looked for %TEMP%\SSMSSetup\ but doesn't exists).

I believe the BSOD shows ddkmd.sys as the issue.

As I'm pretty sure I can consistently repeat this issue I'm happy to try and gather more info if that would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by dnethi** [comment]
+@Matteo Taveggia<mailto:matteot@microsoft.com> and @David Shiflet<mailto:davidshi@microsoft.com> while Matteo is oof..

David – would a full memory dump as described here - https://docs.microsoft.com/en-us/sql/ssms/troubleshoot/get-full-memory-dump?view=sql-server-ver15 be useful or do you have any other recommendations?



Thanks,
Dinakar

**Comment by dnethi** [comment]
Kernel crashes in Windows would be beyond my help. It's most likely a hardware or device driver bug.


From: Dinakar Nethi <Dinakar.Nethi@microsoft.com>
Sent: Monday, December 30, 2019 1:06 PM
To: MicrosoftDocs/sql-docs <reply@reply.github.com>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com>; Matteo Taveggia <matteot@microsoft.com>; David Shiflet <davidshi@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/sql-docs] BSOD When attempting to install (#3882)

+@Matteo Taveggia<mailto:matteot@microsoft.com> and @David Shiflet<mailto:davidshi@microsoft.com> while Matteo is oof..

David – would a full memory dump as described here - https://docs.microsoft.com/en-us/sql/ssms/troubleshoot/get-full-memory-dump?view=sql-server-ver15<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fsql%2Fssms%2Ftroubleshoot%2Fget-full-memory-dump%3Fview%3Dsql-server-ver15&data=02%7C01%7Cdavidshi%40microsoft.com%7C953ff766fc424a58543208d78d52dfd4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637133259400540598&sdata=t2XLAy8FN%2BVY4fJmS1%2BPe6w0AMRIlr4lQJdSoIz1Lh8%3D&reserved=0> be useful or do you have any other recommendations?



Thanks,
Dinakar

**Comment by dnethi** [comment]
Can we suggest a silent installation?


  1.  Open elevated cmd prompt
  2.  Type:
     *   start “” /w SSMS-Setup-ENU.exe /install /quiet


From: David Shiflet <davidshi@microsoft.com>
Sent: lunedì 30 dicembre 2019 11:15
To: Dinakar Nethi <Dinakar.Nethi@microsoft.com>; MicrosoftDocs/sql-docs <reply@reply.github.com>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com>; Matteo Taveggia <matteot@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/sql-docs] BSOD When attempting to install (#3882)

Kernel crashes in Windows would be beyond my help. It's most likely a hardware or device driver bug.


From: Dinakar Nethi <Dinakar.Nethi@microsoft.com<mailto:Dinakar.Nethi@microsoft.com>>
Sent: Monday, December 30, 2019 1:06 PM
To: MicrosoftDocs/sql-docs <reply@reply.github.com<mailto:reply@reply.github.com>>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com<mailto:sql-docs@noreply.github.com>>; Matteo Taveggia <matteot@microsoft.com<mailto:matteot@microsoft.com>>; David Shiflet <davidshi@microsoft.com<mailto:davidshi@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [MicrosoftDocs/sql-docs] BSOD When attempting to install (#3882)

+@Matteo Taveggia<mailto:matteot@microsoft.com> and @David Shiflet<mailto:davidshi@microsoft.com> while Matteo is oof..

David – would a full memory dump as described here - https://docs.microsoft.com/en-us/sql/ssms/troubleshoot/get-full-memory-dump?view=sql-server-ver15<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fsql%2Fssms%2Ftroubleshoot%2Fget-full-memory-dump%3Fview%3Dsql-server-ver15&data=02%7C01%7Cmatteot%40microsoft.com%7C6e076f6e719a49bc492a08d78d5c8de4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637133300964948846&sdata=mq%2BlXSDWxZHSJscZf7Fd2L57W9Bbfq5z%2BrY12z9C2tQ%3D&reserved=0> be useful or do you have any other recommendations?



Thanks,
Dinakar

**Comment by briannipper** [comment]
Thank you for the suggestion @dnethi I tried as you suggested to install via elevated CMD; however, the same result occurs. BSOD as soon as I run the command.

I'm guessing it's a driver issue of some kind. Perhaps an attempt to install in safe mode might work, but I'm not sure what effect installing in safe mode would occur.

Anyone on this thread know if installing in Safe Mode would even be an option worth considering?

**Comment by Matteo-T** [comment]
Since it's a BSOD, the recommended way to proceed (from the Windows folks) is:
- Share (OneDrive, etc...) c:\windows\system32\memory.dmp
Also:
- File a feedback hub bug (Start -> feedback hub) and share the link to the feedback

Thanks,
-Matteo

**Comment by Dean-NC** [comment]
@briannipper Installing a program in Safe Mode will not normally work, because in addition to drivers not loading, Windows also scales back some things needed for installs. However it can be done, and the trick has worked as far back as Win 7. See here for details: https://www.infopackets.com/news/10513/how-fix-install-software-safe-mode-windows-10
At least it would rule out a driver conflict. The only driver that I feel could potentially be the cause would be the graphics/video. See here for how to boot Windows using the Microsoft "basic" graphics driver: https://www.infopackets.com/news/10508/how-fix-boot-windows-10-using-basic-display-adapter-driver. 
Does it happen when installing another program, for example, Notepad++ ?

**Comment by Dean-NC** [comment]
Using the trick to install in Safe Mode is hit or miss, and doesn't work for some programs. I would 1st try booting without an Intel/NVidia/AMD display driver. If the link I posted about that doesn't work, I would:
1. Stop, and disable Windows Update service.
2. Uninstall Intel/NVidia/AMD display drivers.
3. Reboot, and in Device Manager make sure ALL video cards/display adapters are listed as "Basic adapter".
4. Try SSMS install.
5. Re-install any/all display drivers, or let Windows Update put them back.
6. Re-enable Windows Update service.

**Comment by Dean-NC** [comment]
@briannipper If you have a program called "Duet Display" installed, there have been cases where BSOD's happened related to ddkmd.sys, and you can remove that program.

**Comment by briannipper** [comment]
> @briannipper If you have a program called "Duet Display" installed, there have been cases where BSOD's happened related to ddkmd.sys, and you can remove that program.

Thank you for this suggestion... I did have Duet Display installed. So I uninstalled; however, it still BSOD after attempting to install SSMS... so I'll try some of the other suggestions.

**Comment by briannipper** [comment]
> Using the trick to install in Safe Mode is hit or miss, and doesn't work for some programs. I would 1st try booting without an Intel/NVidia/AMD display driver. If the link I posted about that doesn't work, I would:
> 
> 1. Stop, and disable Windows Update service.
> 2. Uninstall Intel/NVidia/AMD display drivers.
> 3. Reboot, and in Device Manager make sure ALL video cards/display adapters are listed as "Basic adapter".
> 4. Try SSMS install.
> 5. Re-install any/all display drivers, or let Windows Update put them back.
> 6. Re-enable Windows Update service.

### THIS WORKED!!!!
Thank you so much for this suggestion. I did as the steps outlined and was able to intsall SSMS 18.4 without any issue.

I hope others are able to find this beneficial.
