### ISSUE TITLE
'Microsoft purchasing website' link broken

### ISSUE THREAD

**Issue by Tim-GOM** [MicrosoftDocs/sql-docs#3884]
'Microsoft purchasing website' link is currently: https://www.microsoft.com/server-cloud/products/sql-server/overview.aspx
This page states:
We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available.

Tested on browsers: Edge, Brave, Chrome, & IE 11

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae75dfb-2017-17a3-835b-9409fdb06427
* Version Independent ID: 8f22b559-823e-d719-7c5d-f76f89345c01
* Content: [SQL Server installation guide - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/install-windows/install-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/install-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @Tim-GOM , thanks for bringing this to our attention! Let me look into this :)

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @Tim-GOM , thanks again for letting us know of the broken link. I have merged a change that fixes the link and it will be live later today. I will proceed with closing out this Git Issue in the meantime, but please feel free to comment should you need anything further from us. 

I hope that helps and thanks again for improving our documentation!  Hope you have a wonderful rest of your day :)
Masha from the SQL Docs team
