### ISSUE TITLE
minor update in the documentation is required

### ISSUE THREAD

**Issue by emad-almousa** [MicrosoftDocs/sql-docs#3894]
in the restore database section, the statement should be as follows:

After you rebuild the resource database, all service packs, cumulative updates and hot fixes are lost, and therefore must be reapplied.
from SQL Server 2017 and beyond, Microsoft only releases cumulative updates and hot fixes for MSSQL ! No Service Packs anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39e93d44-8942-2548-190e-616285b554c6
* Version Independent ID: 4a1e67f5-097c-f4c9-544f-fd75ce0c974c
* Content: [Rebuild System Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/rebuild-system-databases?view=sql-server-ver15&source=docs)
* Content Source: [docs/relational-databases/databases/rebuild-system-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/rebuild-system-databases.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@emad-almousa -- Emad, thank you for your feedback.  I am updating this document.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please review the above-mentioned PR 13411.
