### ISSUE TITLE
DRIVER option for Generic ODBC connection

### ISSUE THREAD

**Issue by Avyncentia** [MicrosoftDocs/sql-docs#3895]
I'm trying to create an external table for a generic ODBC connection for use with Polybase (specifically KB_SQL). This page says to specify the "driver" when creating an external data source using ODBC, but I don't understand syntax for specifying the driver. It doesn't seem to be a valid option in the CREATE EXTERNAL DATA SOURCE command. Here's what I tried: ALTER EXTERNAL DATA SOURCE [kbsql] SET LOCATION = N'odbc://myserver:xxxx', CREDENTIAL = [my_credential], DRIVER='KB_SQL ODBC 64-bit driver'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e450abc6-2dbd-8f6c-423c-52aca37a2b06
* Version Independent ID: 4aff678a-6db1-a438-9aca-bb4b4d49bc27
* Content: [CREATE EXTERNAL DATA SOURCE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-external-data-source-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-data-source-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
researching...

**Comment by KalleOlaviNiemitalo** [comment]
I would try `CONNECTION_OPTIONS = 'Driver={KB_SQL ODBC 64-bit driver}'` with the braces. However, `CONNECTION_OPTIONS` is documented only for `CREATE EXTERNAL DATA SOURCE` and not for `ALTER EXTERNAL DATA SOURCE`. I don't know whether that is an omission in the documentation or a limitation of the software.

**Comment by CarlRabeler** [comment]
@Avyncentia please try the suggestion from @KalleOlaviNiemitalo and let me know what you discover. Thank you.
Carl

**Comment by CarlRabeler** [comment]
@Avyncentia Its been a while we heard from you.
We will proceed to close this issue now.
Please post this issue on StackOverflow (https://stackoverflow.com/questions/tagged/azure-sql-database?tab=Newest) or MSDN (https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=ssdsgetstarted) for better visibility
