### ISSUE TITLE
Which version of Visual Studio can run Azure Feature Pack?

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/sql-docs#3897]
SSIS is running on Visual Studio. It is good to let people know which Visual Studio versions are supported by Azure Feature Pack. Can we have that information in this article?
This is a suggestion rather.

**Comment by WilliamAntonRohm** [comment]
@chanmmn -- thank you for your feedback.  Please provide a link to the article in question and we will look into it.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
