### ISSUE TITLE
Sql Server Management Studio doesn't have Shrink as an option on Tasks menu

### ISSUE THREAD

**Issue by gregveres** [MicrosoftDocs/sql-docs#3898]
When I connect to my Azure DB and follow the instructions above under SMSS, I don't find a Shrink under the Tasks menu. I am using SSMS v 18.4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67f0fd32-024f-734e-82c1-32b890ac591d
* Version Independent ID: bca0a8c1-05fe-91d5-37b5-0a4729c1237f
* Content: [Shrink a Database - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/shrink-a-database?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/shrink-a-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/shrink-a-database.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@gregveres -- thank you for your feedback.

@stevestein -- please look into this issue 3898.

**Comment by gregveres** [comment]
The one thing I learned recently for azure data studio is that azure sql server doesn’t have all the same support as sql server. I wonder if that is why smss doesn’t have this option for my databases, they are azure sql servers.

**Comment by CarlRabeler** [comment]
to shrink an Azure SQL Database, use T-SQL. Not supported using SSMS
Article being updated now

**Comment by vandre** [comment]
@CarlRabeler DBCC SHRINKDATABASE doesn't work either. Tested with SSMS 19.3 an an Azure SQL Database:

![image](https://github.com/MicrosoftDocs/sql-docs/assets/7480750/e312ccda-1215-4b35-83ad-584e8d05e8dc)

![image](https://github.com/MicrosoftDocs/sql-docs/assets/7480750/e9c297e0-c36b-4016-aa92-4bfa4e1d9fa8)

**Comment by WilliamAntonRohm** [comment]
@vandre -- Victor, thank you for your follow-up.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
@vandre Are you by chance using Azure SQL Database Hyperscale tier? While SHRINK is supported in Azure SQL Database, it is [not yet supported in Azure SQL Database Hyperscale](https://learn.microsoft.com/en-us/azure/azure-sql/database/service-tier-hyperscale-frequently-asked-questions-faq?view=azuresql#is-database-shrink-supported-).

**Comment by vandre** [comment]
> @vandre Are you by chance using Azure SQL Database Hyperscale tier? While SHRINK is supported in Azure SQL Database, it is [not yet supported in Azure SQL Database Hyperscale](https://learn.microsoft.com/en-us/azure/azure-sql/database/service-tier-hyperscale-frequently-asked-questions-faq?view=azuresql#is-database-shrink-supported-).
> 
> 
> 
> 

Thank you @WilliamDAssafMSFT Yes that's it! We are planning on archiving a Hyperscale database to blog storage and we were trying to shrink it first.
