### ISSUE TITLE
sys.crypt_properties how to get to a column

### ISSUE THREAD

**Issue by TomGroszko** [MicrosoftDocs/sql-docs#3903]
When class type is 1 (object or column) and it is a column it seems like there needs to be a minor_id  to identify the column in the major_id. On the other hand there does not seem to be a way to add a signature to a column with ADD SIGNATURE so how can it ever be a column?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3c172d7-3713-9829-1a50-e5506cddb927
* Version Independent ID: 5b16eae0-07e7-c8bb-8081-2d7752393c2b
* Content: [sys.crypt_properties (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-crypt-properties-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-catalog-views/sys-crypt-properties-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-crypt-properties-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @TomGroszko! We appreciate your question. Unfortunately, this forum is only for documentation issues, and not for product feature or related product questions. Please utilize the feedback for the product at the bottom of the page to submit your concerns.

![image](https://user-images.githubusercontent.com/40007119/71908814-8b5d8600-3123-11ea-8a7b-baa54b9e96a4.png)

Thanks!
