### ISSUE TITLE
Readable seconday

### ISSUE THREAD

**Issue by mmmiller60** [MicrosoftDocs/sql-docs#3904]
Clarify if it is required for the secondaries be configured as "readable secondaries"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22e74780-976d-c65a-b0e3-7d9e4a8a25b7
* Version Independent ID: 8eaff680-6aaf-5996-38b8-508bc79e4fdf
* Content: [Configure backups on secondary replicas of an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-backup-on-availability-replicas-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/configure-backup-on-availability-replicas-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/configure-backup-on-availability-replicas-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @mmmiller60 , thanks for contacting Microsoft! My apologies, I'm not sure I understand your question. Are you asking if the secondary has to be readable to configure backups? 

Thanks!
Masha from the SQL Docs team

**Comment by mmmiller60** [comment]
Exactly.  There is a separate configuration to enable the secondary DB to be readable, is that configuration also needed to use the secondary for backups?

Sam

**Comment by MashaMSFT** [comment]
Hi @mmmiller60 , my apologies for the delay while I research this for you. Just to make sure I'm understanding your question correctly, you want to set the secondary as unreadable like so: 

![image](https://user-images.githubusercontent.com/32783170/72949910-937e0e00-3d3e-11ea-8d2f-d2bf0047b87a.png)

And then you want to set the backup preference to be on the secondary replica, like so: 
![image](https://user-images.githubusercontent.com/32783170/72949932-a42e8400-3d3e-11ea-83b6-f96741d3c19a.png)

And you'd like to know if this will work, is that correct? Or if it's required that the secondary replica is set to readable in the above option for the backup to succeed on the secondary replica? 

Thanks!
Masha from the SQL Docs team

**Comment by mmmiller60** [comment]
My question is the 2nd question...

if it's required that the secondary replica is set to readable in the above option for the backup to succeed on the secondary replica?

I believe the answer is NO but this information should be clarified in the documentation because logically you would think the secondary would need to be readable if it is to be used for backups.


Thanks
Sam


-------- Original message --------

**Comment by MashaMSFT** [comment]
Hi @mmmiller60, thank you for your patience! We were able to confirm that a secondary replica does not need to be readable for a backup to succeed on it.

I've added a note to the article that should be live tomorrow. I'll proceed with closing out this Git issue but please feel free to comment should you need anything else. 

I hope that helps and please let us know if we can be of further assistance!
Masha from the SQL Docs team

**Comment by mmmiller60** [comment]
Thanks for the help!



Thanks
Sam



-------- Original message --------
