### ISSUE TITLE
The summary paragraph should say "Extended Events" instead of "XEvents" 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/sql-docs#3905]
Use codenames, shortened names, pet names, cutesy names, etc after the thing has been declared with a proper name. It just confuses people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ddbdcc5-661b-427d-7080-902c4611f739
* Version Independent ID: 3cf010c2-45ef-b58a-4091-c79c3e67cfef
* Content: [SQL Server Profiler extension - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/sql-server-profiler-extension?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/sql-server-profiler-extension.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/sql-server-profiler-extension.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
@StingyJack -- thank you for your feedback.
