### ISSUE TITLE
Change 'he' pronoun to gender neutral

### ISSUE THREAD

**Issue by tgilmour** [MicrosoftDocs/sql-docs#3909]
In "If a user is a Windows domain user who has a login and password for Windows, he must still provide another (SQL Server) login"
Consider revising this to use a gender neutral pronoun.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a9d17e2-3f3e-745c-058e-50ae13558b96
* Version Independent ID: c6d6b73a-96c0-10f3-0dd7-a9cb4cd6618b
* Content: [Choose an Authentication Mode - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/choose-an-authentication-mode?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/choose-an-authentication-mode.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/choose-an-authentication-mode.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Thanks for the feedback @tgilmour! I've made the change to the doc and it should go live today.
