### ISSUE TITLE
varchar (max) is not supported in CCI

### ISSUE THREAD

**Issue by vijaysuram** [MicrosoftDocs/sql-docs#3914]
This page says varchar(max) is only used in sql data warehouse but when I use max it throws me an error saying that CCI doesn;t support such data type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4775d99-7054-3a3f-98bb-815b65b67358
* Version Independent ID: 6f9ab4ec-3b8a-e2d6-3546-8179f36a0999
* Content: [CREATE TABLE (Azure SQL Data Warehouse) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-azure-sql-data-warehouse?view=aps-pdw-2016-au7)
* Content Source: [docs/t-sql/statements/create-table-azure-sql-data-warehouse.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-azure-sql-data-warehouse.md)
* Service: **sql-data-warehouse**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@vijaysuram -- thank you for your feedback.

@julieMSFT -- please look into this issue 3914.

**Comment by julieMSFT** [comment]
@XiaoyuMSFT Please advise on this issue.

**Comment by julieMSFT** [comment]
@vijaysuram Hello, thank you for your question. For guidance on choosing the type of table to use, follow the link in the article to [Indexing tables in Azure SQL Data Warehouse](https://docs.microsoft.com/azure/sql-data-warehouse/sql-data-warehouse-tables-index.). This link explains the different considerations when choosing a table type. I am now closing this issue. The @ mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
