### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tgilmour** [MicrosoftDocs/sql-docs#3915]
I think "transaction logon disk" be "transaction log on disk"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91f89b-5196-0ea5-28fc-79cf59ab327e
* Version Independent ID: 0f4f2d0d-0913-8b47-15ab-7300dc2aa1a3
* Content: [Overview and Usage Scenarios - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/overview-and-usage-scenarios?view=sql-server-2016)
* Content Source: [docs/relational-databases/in-memory-oltp/overview-and-usage-scenarios.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/overview-and-usage-scenarios.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @jodebrui
* Microsoft Alias: **jodebrui**

**Comment by WilliamAntonRohm** [comment]
@tgilmour -- thank you for your feedback.  I am looking into this document.
