### ISSUE TITLE
Not clear enough

### ISSUE THREAD

**Issue by JohnTrombone** [MicrosoftDocs/sql-docs#3916]
I still don't know, after reading this page, what "read-scale" means. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d2fdfcd-bb40-75ae-21ba-f9019f816d5a
* Version Independent ID: cfecc4e2-f246-809e-6445-d96eb753e101
* Content: [Use read-scale with availability groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/read-scale-availability-groups?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/read-scale-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/read-scale-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @JohnTrombone , thanks for contacting Microsoft and bringing this to our attention! Let me see what we can do about adding more clarity to this doc.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @JohnTrombone , I've added a sentence to add clarity to the definition:

![image](https://user-images.githubusercontent.com/32783170/71915274-3ffda480-3130-11ea-94e7-34c5452460b2.png)

This change will be live later today. I will close out this Git Issue in the meantime, but please feel free to comment should you need anything further.

Thanks for helping improve our documentation! Hope you have a wonderful rest of your day :)
Masha from the SQL Docs team

**Comment by JohnTrombone** [comment]
Not much better. How about: “In the context of an availability group, “read scale” refers to one or more replicas whose purpose is to offload data for read-only access, as opposed to failover purposes.”

**Comment by MashaMSFT** [comment]
Hi @JohnTrombone, yeah that's great! Did you want to make the change yourself so you can be listed as a contributor to the article? 

Here are the steps, if you're interested:

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Name your file change and provide a description, if necessary
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page

If not, I can make the change myself as well :) 

Thanks!
Masha from the SQL Docs team
