### ISSUE TITLE
BIT storage optimization question

### ISSUE THREAD

**Issue by ctasantos** [MicrosoftDocs/sql-docs#3923]
Hello,

I was reading the following page regarding BIT datatype: https://docs.microsoft.com/en-us/sql/t-sql/data-types/bit-transact-sql?view=sql-server-ver15

I believe the statement below (from the Remarks section) only applies to BIT columns that are NOT NULL.

> The SQL Server Database Engine optimizes storage of bit columns. If there are 8 or fewer bit columns in a table, the columns are stored as 1 byte. If there are from 9 up to 16 bit columns, the columns are stored as 2 bytes, and so on.

Could you please clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 019de197-9478-71e7-9618-7236a13027e6
* Version Independent ID: d9e87003-b94b-106d-af24-05916e4f9737
* Content: [bit (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/bit-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/data-types/bit-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/bit-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@ctasantos -- Carlos, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue 3923.

**Comment by MikeRayMSFT** [comment]
Thanks @ctasantos  - I'm confirming with partners.

**Comment by MikeRayMSFT** [comment]
SQL Server takes the one byte of storage if up to 8 bit columns are defined for row. If all eight columns are nulll, it doesn't take any storage - other than what's taken for the null bitmap.  If one of the eight columns is not null, the entire byte is taken up if if the other seven are null.
