### ISSUE TITLE
max workers for 64 processors

### ISSUE THREAD

**Issue by LonnyNiederstadt** [MicrosoftDocs/sql-docs#3926]
The following appears in the first table above.
64 processors 	
32 bit: 736
64 bit: 1472

These formulas appear in the following table.
&gt; 4 processors and &lt; 64 processors 	
32 bit: 256 + ((logical CPU's - 4) * 8)
64 bit: 512 + ((logical CPU's - 4) * 16)

&gt; 64 processors
32 bit: 256 + ((logical CPU's - 4) * 32)
64 bit: 512 + ((logical CPU's - 4) * 32)

In order to account for the table of formulas to account for 64 processor systems and agree with the preceding table, the first formula should apply to &gt; 4 processors and &lt;= 64 processors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90f494da-8888-13e8-0fcc-187242579039
* Version Independent ID: 01bd6647-777e-8c62-f865-6831469b4924
* Content: [Configure the max worker threads Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-max-worker-threads-server-configuration-option?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/configure-windows/configure-the-max-worker-threads-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-max-worker-threads-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@LonnyNiederstadt -- Lonny, thank you for your keen eye.  I am looking into this document.
