### ISSUE TITLE
xp_sprintf not available on Azure SQL

### ISSUE THREAD

**Issue by DannyMeister** [MicrosoftDocs/sql-docs#3930]
This article claims that the docs for xp_sprintf applies to Azure SQL Database.  However, none of our Azure SQL Server's contain this system extended stored procedure in the master database, leading to errors when our application runs in Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fdda028-1f5e-2f89-3d6e-f3dbb8015dd8
* Version Independent ID: 50b7d66e-9627-0e08-098b-0659713f1e93
* Content: [xp_sprintf (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/xp-sprintf-transact-sql?view=azuresqldb-current#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/xp-sprintf-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/xp-sprintf-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
Thanks Danny,
This is an error in the docs. Extended procedures should not be marked as supported.
Carl

**Comment by CarlRabeler** [comment]
doc updated - live later today
