### ISSUE TITLE
Will DateTime be declared as deprecated on newer versions of SQL Server?

### ISSUE THREAD

**Issue by Peled-Zohar** [MicrosoftDocs/sql-docs#3933]
I'm basing my question on the note at the top of the page that starts with "Use the time, date, datetime2 and datetimeoffset data types for new work."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1774f2f4-950d-03af-fc87-f75099f31835
* Version Independent ID: 76893d14-e1ed-0d4a-6092-15d25628ce14
* Content: [datetime (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/data-types/datetime-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/datetime-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@Peled-Zohar -- Zohar, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue 3933.

**Comment by MightyPen** [comment]
@Peled-Zohar Hello,
The 'DateTime' data type has not been declared as Deprecated. There is nothing more to say about the continuing status of DateTime, nor about any other data type.

Thank you for inquiring. We hope to hear from you again.
I am now closing this Issue #3933 .

c: @MikeRayMSFT

**Comment by bkwdesign** [comment]
datetimeoffset definitely works better for greenfield projects, especially if you're creating new OData style Web API's and exposing those via OpenAPI (aka swagger) - much of which can be scaffolded into existence from an Entity Framework-based data-access-layer

**Comment by Peled-Zohar** [comment]
Oh I know it's not deprecated now, I was merely wondering if there are any plans to deprecate it in the near future. Thanks for responding!

**Comment by MightyPen** [comment]
@Peled-Zohar @bkwdesign 
With each new release of SQL Server, Microsoft never creates any _Backward Incompatibility_ in SQL Server unless there is a strongly compelling reason.
When a B.I. seems truly necessary and unavoidable, even then we add an sp_configure setting that can refuse the changes that create the B.I.

Thanks.
