### ISSUE TITLE
Azure SQL MI

### ISSUE THREAD

**Issue by dudu-markovitz** [MicrosoftDocs/sql-docs#3937]
There is not reference to Azure SQL MI limitations.
It turns out a Linked Server to Azure SQL MI supports only SQL authentication on the Azure SQL MI side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac4dbeb2-b244-27af-7cfe-4f441ca26d2e
* Version Independent ID: ee282927-e7df-a8d9-da5c-755d0bc41b0f
* Content: [Create Linked Servers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/linked-servers/create-linked-servers-sql-server-database-engine?view=sql-server-ver15#SSMSProcedure)
* Content Source: [docs/relational-databases/linked-servers/create-linked-servers-sql-server-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/linked-servers/create-linked-servers-sql-server-database-engine.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@dudu-markovitz -- דודו, thank you for your feedback and for that information.

@stevestein -- Steve, please look into this issue 3937.

**Comment by CarlRabeler** [comment]
@dudu-markovitz Please clarify the change you wish to have made to this article. It is unclear to me.
Thank you, Carl

**Comment by dudu-markovitz** [comment]
Hi Carl

A customer was struggling for a long time, attempting to create a linked server from SQL Server on-prem to Azure SQL MI, by mapping Windows/SQL Server users (on-prem) to AAD users (MI).
The customer has fail to do so and the error messages he got were unclear.

After we (CSU) were involved and reached out to PG, it was clarified that this scenario is not supported -
only a SQL Server user can be used as "Remote User" on Azure SQL MI.
It would be helpful to clarify in the documentation which scenarios are supported and which not.

Thanks

**Comment by CarlRabeler** [comment]
Can you please help me with respect to what scenarios are supported and which are not? FYI – you should be able to just click Edit in the upper-right hand corner and modify the article – which will come back to me for review. Linked servers are definitely supported, but beyond that I do not have information. If you do not have that information, I will reach out to the product team for assistance.
Thank you,
Carl

**Comment by CarlRabeler** [comment]
PR submitted to address this specific scenario: https://github.com/MicrosoftDocs/sql-docs-pr/pull/13583
