### ISSUE TITLE
"columnstore table does not allow a primary key constraint" is false?

### ISSUE THREAD

**Issue by samrueby** [MicrosoftDocs/sql-docs#3938]
This documentation states "By design, a columnstore table does not allow a primary key constraint."

This doesn't appear to be true. See this example:

CREATE TABLE t_account (  
    AccountKey int NOT NULL PRIMARY KEY NONCLUSTERED,  
    AccountDescription nvarchar (50),  
    AccountType nvarchar(50),  
    UnitSold int
);  
  
CREATE CLUSTERED COLUMNSTORE INDEX t_account_cci ON t_account ;

This executed fine in SQL 2017. I think what the documentation intends to say is that the table cannot have a clustered primary key, since the table is a clustered columnstore  index.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e021430-b8b5-1a96-1e71-c95d72580c0f
* Version Independent ID: 9f8a8520-31ef-eb8f-3ff5-c92db7d69514
* Content: [Columnstore indexes - Data Warehouse - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-data-warehouse?view=sql-server-ver15)
* Content Source: [docs/relational-databases/indexes/columnstore-indexes-data-warehouse.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/columnstore-indexes-data-warehouse.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@samrueby -- Sam, thank you for your feedback and your researches.

@MikeRayMSFT -- please look into this issue 3938.

**Comment by MikeRayMSFT** [comment]
@samrueby - thanks for the submission. Verifying.

**Comment by pmasl** [comment]
Fixed by adding "clustered". Does not allow a clustered PK.
