### ISSUE TITLE
Are "extended properties" supported for in-memory OLTP objects?

### ISSUE THREAD

**Issue by JohannWeskandt** [MicrosoftDocs/sql-docs#3939]
It looks like extended properties are not supported for in-memory OLTP objects.
e.g. SQL Management Studio shows the section "extended properties" in the property dialogue for a column in an OLTP table. But once I try to add an extended property (calling "sp_addextendedproperty" under the hood) SQL error 12320 "Operations that require a change to the schema version, for example renaming, are not supported with memory optimized tables." is raised.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f34d1d9-996d-a5b7-c525-a0c8b2275373
* Version Independent ID: 8d8a4eff-4a28-a749-97c8-b42c7e55c477
* Content: [Features not supported - in-memory OLTP - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/unsupported-sql-server-features-for-in-memory-oltp?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/in-memory-oltp/unsupported-sql-server-features-for-in-memory-oltp.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/unsupported-sql-server-features-for-in-memory-oltp.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by WilliamAntonRohm** [comment]
@JohannWeskandt -- Johann, thank you for your question and your researches.

@MightyPen -- Gene, please look into this issue #3939.

**Comment by MightyPen** [comment]
@JohannWeskandt Hi, in this Issue #3939 , we would need to know which Version of SQL Server you are working with.

Our SQL Server 2014 documentation does mention the error 12320 that you mentioned.
But our SQL 2016 (and onward) documentation does not mention error 12320.

> - "|Operation|schema change|Memory-optimized tables and natively compiled stored procedures do not support shema changes, for example, `sp_rename`.<br /><br /> Attempting to make schema changes, such as renaming a table, will generate **error 12320**, Operations that require a change to the schema version, for example renaming, are not supported with memory-optimized tables.<br /><br /> To change the schema, drop and recreate the table or procedure using an updated definition.|  
"

I know that many enhancements were made in SQL 2016 for in-memory tables, and this could well have been one of those enhancements.  And it looks like the mention of 12320 was deliberately removed for SQL 2016.

I suspect that for in-memory table, these extended properties are supported for SQL 2016, but not for SQL 2014.  At present I have no info to the contrary.
So I am now Closing this Issue.

But feel free to reOpen this Issue if you were using SQL Server 2016 or later, and were using a version of SSMS that you downloaded within the past half year:

- https://docs.microsoft.com/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2016

Thank you.

cc: @rothja

**Comment by JohannWeskandt** [comment]
Hello MightyPen,

I provided a simple repro scenario that raises error 12320 in SQL Server 2017 (V14.0.3281.6) and SQL Server 2019 (V15.0.4013.40) connecting from SSMS V15.0.18206.0 on my system.
Are you able to add extended properties to column of an OLTP table in SQL 2017 or 2019?

Thanks, Johann
