### ISSUE TITLE
Missing Error: 978, Severity: 14, State: 1.

### ISSUE THREAD

**Issue by Ken-DBA** [MicrosoftDocs/sql-docs#3941]
My ErrorLog file contains the following:
&gt; Error: 978, Severity: 14, State: 1.
This error is missing from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5973cd79-d024-6670-8b9f-d02d9824e8ec
* Version Independent ID: 9c7e4cd4-9bd7-16ad-83c0-9c114e5eec46
* Content: [Database engine events and errors - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-events-and-errors?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/errors-events/database-engine-events-and-errors.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/errors-events/database-engine-events-and-errors.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@Ken-DBA -- thank you for bringing this lacuna to our attention.

@MashaMSFT -- please look into this issue 3941.

**Comment by MashaMSFT** [comment]
Hi @Ken-DBA , thank you for bringing this to our attention! While this list is not meant to be exhaustive, such a disclaimer was missing from the documentation. We added the disclaimer, along with a query you can use to get the full list from the system engine. 

As a courtesy, however, we did add the error message that you pointed out was missing, along with a few others. 

I hope that helps, and please leave us a comment should you need anything further. 

Thanks and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
