### ISSUE TITLE
Feature name

### ISSUE THREAD

**Issue by kalendelaney** [MicrosoftDocs/sql-docs#3944]
In the list of features, I believe there is no feature call Data Tuning Advisor.  "Tuning Data" doesn't even mean anything.  DTA is either Database Tuning Advisor or Database Engine Tuning Advisor. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbe4ef3a-6282-5c51-5810-c6d63f3a0e1b
* Version Independent ID: 6d655e24-fc84-aad0-2422-2451cfb1ad34
* Content: [What is Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is?view=sql-server-ver15#feedback)
* Content Source: [docs/azure-data-studio/what-is.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/what-is.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@kalendelaney,

Thank you for bringing this to our attention.

I will look into this and let you know.

**Comment by markingmyname** [comment]
@kalendelaney 

It should be a Database Engine Tuning Advisor.

Thank you for bringing this to our attention.

The update should be live by tomorrow.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
