### ISSUE TITLE
Incorrect syntax: I. Using OUTPUT INTO with identity and computed columns 

### ISSUE THREAD

**Issue by OskarWielanowski** [MicrosoftDocs/sql-docs#3946]
I found an error in query - declaration of table variable  @MyTableVar doesn't match to INTO @MyTableVar 
part.  I suppose it declaration should be like this:
 DECLARE @MyTableVar table(  
  EmployeeID   int IDENTITY (1,5) NOT NULL,  
  LastName     nvarchar(20) NOT NULL,  
  FirstName    nvarchar(20) NOT NULL,  
  CurrentSales money NOT NULL,  
  ProjectedSales AS CurrentSales * 1.10 
  );
or insert should be like this :
INSERT INTO dbo.EmployeeSales (LastName, FirstName, CurrentSales)  
  OUTPUT INSERTED.EmployeeID,
		 INSERTED.LastName,   
         INSERTED.FirstName,   
         INSERTED.CurrentSales,
		 INSERTED.ProjectedSales
  INTO @MyTableVar  

[I. Using OUTPUT INTO with identity and computed columns](https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15&source=docs#i-using-output-into-with-identity-and-computed-columns). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec163f51-1b95-aa3c-1946-92d995bc8c74
* Version Independent ID: 740c5b7b-2f6d-1269-7511-85cb5ddb63a2
* Content: [OUTPUT Clause (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/t-sql/queries/output-clause-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/output-clause-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@OskarWielanowski -- Oskar, thank you for your feedback and your suggested correction.

@VanMSFT -- Van, please look into this issue 3946.

**Comment by VanMSFT** [comment]
@OskarWielanowski - Thanks for informing us of this error, Oskar! We really appreciate it. I have fixed the sample, and it will go live later today. Thanks again!
