### ISSUE TITLE
Error line

### ISSUE THREAD

**Issue by grchristin** [MicrosoftDocs/sql-docs#3949]
How is the errorline number determined? The sample result lists 6 and I cannot figure out where it gets that number.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76fe2072-7b1f-c650-b519-f76808d5c070
* Version Independent ID: a3363342-9f9d-a2d9-7553-0d3a07712336
* Content: [ERROR_PROCEDURE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/error-procedure-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/error-procedure-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/error-procedure-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@grchristin -- thank you for your feedback.  There is a previous issue with this same topic: #3880.  I am closing this current issue (3949) and will add another note to #3880.  You are welcome to @ mention me for any followup.
