### ISSUE TITLE
Is DBCC CHECKIDENT needed after using this?

### ISSUE THREAD

**Issue by SurturZ** [MicrosoftDocs/sql-docs#3952]
Do you need to perform a DBCC CHECKIDENT to set the seed after using this command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a803389f-08b7-7078-a104-707c612722b3
* Version Independent ID: 02f17dab-452a-7300-0bee-76b2a03e9517
* Content: [SET IDENTITY_INSERT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-identity-insert-transact-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-2014#feedback)
* Content Source: [docs/t-sql/statements/set-identity-insert-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-identity-insert-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
If the value inserted is larger than the current identity value for the table, SQL Server automatically uses the new inserted value as the current identity value. Otherwise, the seed value does not change.

**Comment by SurturZ** [comment]
Thanks, that clears things up!
