### ISSUE TITLE
Typo in the "Title" meta tag

### ISSUE THREAD

**Issue by tgilmour** [MicrosoftDocs/sql-docs#3954]
The meta tag og:title is currently "Creat Server Audit & Server Audit Specification - SQL Server", and this appears in the browser tab name.
But think it should be "Create Server Audit & Server Audit Specification - SQL Server"
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233cfefa-453a-5c85-a3f7-e1a6e9a31815
* Version Independent ID: 417f38b4-6e46-d326-197d-2afd1a4b7136
* Content: [Creat Server Audit & Server Audit Specification - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/create-a-server-audit-and-server-audit-specification?view=sql-server-2016)
* Content Source: [docs/relational-databases/security/auditing/create-a-server-audit-and-server-audit-specification.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/auditing/create-a-server-audit-and-server-audit-specification.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
@tgilmour - Thanks for catching this! We really appreciate it. I have edited the file, and it should go live later today.
