### ISSUE TITLE
SET ANSI_WARNINGS ON    implicitly sets ARITHABORT to ON ...  Checking what this means ?

### ISSUE THREAD

**Issue by allanford17** [MicrosoftDocs/sql-docs#3956]
Dear Microsoft,  

I don't understand what this sentence means : 

"Setting ANSI_WARNINGS to ON implicitly sets ARITHABORT to ON when the database compatibility level is set to 90 or higher. If the database compatibility level is set to 80 or earlier, the ARITHABORT option must be explicitly set to ON."

Does this mean (?) the following:

So even if the ARITHABORT setting value is OFF and displaying as OFF and the ANSI_WARNINGS setting is ON then the ARITHABORT setting value is actually ON (even though display and queried values show OFF) for database compatibility level 90 or higher ..

or should I expect to be able to see ARITHABORT set to ON after SET ANSI_WARNINGS ON?

I will test as per script above ..

cheers, Allan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ca316f1-685a-2ad1-2440-433f11908358
* Version Independent ID: e1c788c2-818b-d984-e357-d4389fb4b770
* Content: [SET ARITHABORT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-arithabort-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/set-arithabort-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-arithabort-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@allanford17 good question. I would have to test. I will put this in my work queue. If you get a chance to test before I do, please let me know the results of your testing.
Thanks, Carl

**Comment by allanford17** [comment]
@CarlRabeler ... I find that if I use command SET ANSI_WARNINGS ON before running above Example script in this article then the examples under the SET ARITHABORT OFF;  command act as if SET ARITHABORT ON was still in effect.
I find that if I use command SET ANSI_WARNINGS OFF before running above Example script then the SET ARITHABORT ON statement has an effect on results.

*** SET ANSI_WARNINGS ON

(1 row affected)

(1 row affected)
*** SET ARITHABORT ON
*** Testing divide by zero during SELECT
Msg 8134, Level 16, State 1, Line 29
Divide by zero error encountered.
*** Testing divide by zero during INSERT
Msg 8134, Level 16, State 1, Line 35
Divide by zero error encountered.
The statement has been terminated.
*** Testing tinyint overflow
Msg 8115, Level 16, State 2, Line 42
Arithmetic overflow error converting expression to data type tinyint.
The statement has been terminated.
*** Resulting data - should be no data

(0 rows affected)
*** SET ARITHABORT OFF
*** Testing divide by zero during SELECT
Msg 8134, Level 16, State 1, Line 66
Divide by zero error encountered.
*** Testing divide by zero during INSERT
Msg 8134, Level 16, State 1, Line 73
Divide by zero error encountered.
The statement has been terminated.
*** Testing tinyint overflow
Msg 8115, Level 16, State 2, Line 79
Arithmetic overflow error converting expression to data type tinyint.
The statement has been terminated.
*** Resulting data - should be 0 rows

(0 rows affected)

*** #################################################################################

*** SET ANSI_WARNINGS OFF

(1 row affected)

(1 row affected)
*** SET ARITHABORT ON
*** Testing divide by zero during SELECT
Msg 8134, Level 16, State 1, Line 29
Divide by zero error encountered.
*** Testing divide by zero during INSERT
Msg 8134, Level 16, State 1, Line 35
Divide by zero error encountered.
*** Testing tinyint overflow
Msg 8115, Level 16, State 2, Line 42
Arithmetic overflow error converting expression to data type tinyint.
*** Resulting data - should be no data

(0 rows affected)
*** SET ARITHABORT OFF
*** Testing divide by zero during SELECT
Division by zero occurred.

(2 rows affected)
*** Testing divide by zero during INSERT
Division by zero occurred.

(2 rows affected)
*** Testing tinyint overflow
Arithmetic overflow occurred.

(2 rows affected)
*** Resulting data - should be 0 rows

(4 rows affected)

**Comment by CarlRabeler** [comment]
@allanford17 based on your testing, what changes to the documentation would you propose?
Thank you, 
Carl

**Comment by allanford17** [comment]
Hi CarlRabeler,  

Thankyou for your followup ..   I googled the dictionary meaning for the word "implicitly" ... 

I would propose that this sentence :

Setting ANSI_WARNINGS to ON implicitly sets ARITHABORT to ON when the database compatibility level is set to 90 or higher. 

Be replaced with this text: 

When ANSI_WARNINGS has a value of ON and the database compatibility level is set to 90 or higher then ARITHABORT is implicitly ON regardless of it's value setting.

What do you think ?

thanks, 
Allan

**Comment by CarlRabeler** [comment]
That sounds good. Please submit that change and I will get it approved (click Edit and submit a publish pull request).
Thank you,
Carl

**Comment by allanford17** [comment]
Thanks Carl,
Yes - I have tried to do this GitHub change ..
thanks, Allan

**Comment by CarlRabeler** [comment]
resolved with PR
