### ISSUE TITLE
Example A is missing a single quote after the password

### ISSUE THREAD

**Issue by mrdenny** [MicrosoftDocs/sql-docs#3957]
Hense all the red text

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e450abc6-2dbd-8f6c-423c-52aca37a2b06
* Version Independent ID: 4aff678a-6db1-a438-9aca-bb4b4d49bc27
* Content: [CREATE EXTERNAL DATA SOURCE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-external-data-source-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-data-source-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@mrdenny - there is a little button called edit in the upper right so you can submit this change directly. That said, I will add this to my queue if you do not get to it before I do. 
Thanks, Carl

**Comment by WilliamAntonRohm** [comment]
@mrdenny -- thank you for bringing this to our attention.  I have updated the documentation and it should be live by tomorrow.

@CarlRabeler -- thank you for your offer; this one is off your plate.
