### ISSUE TITLE
BCP Examples and Syntax needs to be shown

### ISSUE THREAD

**Issue by mrdenny** [MicrosoftDocs/sql-docs#3958]
There needs to be an update with the information for BDC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ac2fe2-31da-7db6-2d5f-5091022f41d2
* Version Independent ID: bbf07c2c-7006-7b94-f12f-800fa7bc67e4
* Content: [CREATE EXTERNAL TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-table-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-external-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@mrdenny - can you provide some more assistance here? is this about a big data clusters?
@MikeRayMSFT Mike - if this is Big Data Clusters, adding you here to assist

**Comment by mrdenny** [comment]
Yeah, this is about BDC.  If I knew all the various syntaxes I'd update it. :)

**Comment by CarlRabeler** [comment]
Denny,
Are you saying that BCP is working differently with BDC? 

This is what I have from the product team to date:

There is no difference in terms of using BCP against SQL Server Master instance. The bootstrap script uses bcp to extract data from files. If you are trying to ingest data from say the master pod then steps are bit different in terms of copying the files into the pod.

**Comment by mrdenny** [comment]
I might have clicked the wrong place. It should be on the CREATE EXTERNAL TABLE page, not the BCP page.

Thank You,
Denny Cherry
Owner & Principal Consultant
Denny Cherry & Associates Consulting, an Inc. 5000 company
denny@dcac.com<mailto:denny@dcac.com>
(o) +1 (323) 686-1478<tel:3236861478> | (d) +1 (213) 973-3669<tel:2139733669>
Online Calendar Bookings<https://calendly.com/mrdenny>
[cid:image001.png@01D496D7.0B514EC0]<http://www.dcac.co/>
[cid:image005.jpg@01D4A793.11CB8A50]
[cid:image003.png@01D496D7.0B514EC0]
[cid:image004.jpg@01D496D7.0B514EC0]
