### ISSUE TITLE
Where to put my article on showing reporting services usage stats with Grafana?

### ISSUE THREAD

**Issue by suxstellino** [MicrosoftDocs/sql-docs#3961]
I'm trying to figure out where to put (propose) my article on showing reporting services usage stats with Grafana. I'm working on this path right now in order to make the PR:
![image](https://user-images.githubusercontent.com/2568107/72425707-99954d00-3788-11ea-9445-74084043d47f.png)
Should I create a folder under the `reporting-services` one or it is better to use one that already exists? Regardless, what would be your suggested folder name?

Thanks

**Comment by WilliamAntonRohm** [comment]
@suxstellino -- Alessandro, thank you for your proposed article.  Please provide some more context regarding the article's place in the docs.microsoft.com collection, so I can find an author or expert to help answer your questions.

**Comment by suxstellino** [comment]
The article will describe how to display in a dashboard (instead of just using SSMS) the usage stats of reports based on queries over the ReportServer database. The dashboard is useful when you would like to understand whether or not keep any report. Many of them could be overlapped, duplicated or even used only one time. The dashboard is made with Grafana via SQL Server connector.

I was wondering where to put this content. In a specific folder? Under which one? Should I create certain folders by myself?
Thanks

**Comment by suxstellino** [comment]
Hi there, do you need more info? May the article itself can help you?

**Comment by WilliamAntonRohm** [comment]
@suxstellino -- Alessandro, it would be very helpful to see your proposed article.  I am looking for an expert reviewer here.

**Comment by suxstellino** [comment]
Ok, I have a blog post (short version) or, in some weeks, a version of the definitive article out there :-) 
Is the blog post ok for you? If so, here it is: https://alessandroalpi.blog/2020/01/15/show-reporting-services-usage-statistics-with-grafana/
many thanks, William!

**Comment by WilliamAntonRohm** [comment]
@suxstellino -- Alessandro, thank you for your kind offer.  I've asked our local experts, and it doesn't seem to fit into our documentation set at this time.  I'm closing this issue now, and we hope to hear from you again.

cc @markingmyname for awareness per Gene

**Comment by suxstellino** [comment]
Ok, thanks anyway. Just to understand, is there any information which shouldn't go into the docs? How can I improve it to make it better for the topics the doc should be provide? The blog post is not a detailed article (which will be different). Tips?
