### ISSUE TITLE
Text from previsous tab is visible when changing tabs

### ISSUE THREAD

**Issue by andowero** [MicrosoftDocs/sql-docs#3962]
When I change tabs, text doesn't change until I use scrollbar or resize window. This is especially frustrating when creating new tab (Ctrl+N), since it doesn't have scrollbar to move. Version 17.1 does this ocassionally. Version 18.4 does this always. I'm running Windows 10 build 17763.

**Comment by WilliamAntonRohm** [comment]
@andowero -- thank you for your feedback.  You may want to log it here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

This repo is only for documentation issues, not product issues, and so I am closing this now.  You are welcome to @ mention me for any followup.
