### ISSUE TITLE
Create a New msdb Database

### ISSUE THREAD

**Issue by dfuente** [MicrosoftDocs/sql-docs#3963]
It is necessary to 8. Re-apply any service packs or hotfix installed on the instance after creating a new MSDB?
Isn't that only necessary when re-creating the resource database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39e93d44-8942-2548-190e-616285b554c6
* Version Independent ID: 4a1e67f5-097c-f4c9-544f-fd75ce0c974c
* Content: [Rebuild System Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/rebuild-system-databases?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/databases/rebuild-system-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/rebuild-system-databases.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@dfuente -- David, that is a good question.

@stevestein -- Steve, please look into this issue 3963.

**Comment by CarlRabeler** [comment]
Service packs may have updated system databases as well as user databases

**Comment by dfuente** [comment]
Thanks for the info. However, if for instance, my SQL Server version is SQL Server 2014 SP3-CU3 and I rebuild the system databases (master, msdb and model). Do I have to re-apply SP3 and CU3 afterwards? Isn't the rebuild process recreating them as "SQL 2014 SP3-CU3"? Cheers

**Comment by CarlRabeler** [comment]
How did you do the rebuild? Unless you are doing the rebuild and pointing to installation media that has all of the, in your case, SP3-CU3 bits included, you need to re-apply. Typically, one would use the RTM / GA media which would not have the SP3-CU3 bits included.

**Comment by dfuente** [comment]
Thanks for this. I'm using setup.exe from this path C:\Program Files\Microsoft SQL Server\120\Setup Bootstrap\SQLServer2014\ to rebuild system databases (msdb, master, model). So afterwards I run select @@version and shows Microsoft SQL Server 2014 (SP3-CU3) (KB4491539) - 12.0.6259.0 (X64). Or it is potentially showing the wrong version? Thanks.

**Comment by CarlRabeler** [comment]
this looks like you have a version of 2014 with SP3-CU3 already integrated.
