### ISSUE TITLE
Wrong headline?

### ISSUE THREAD

**Issue by OLEWebAffairs** [MicrosoftDocs/sql-docs#3965]
Must the word "nonclustered" in the headline [here](https://docs.microsoft.com/en-us/sql/relational-databases/tables/create-primary-keys?view=sql-server-ver15#to-create-a-primary-key-with-nonclustered-index-in-a-new-table) not be "clustered "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e15a126f-ac3f-59aa-0b73-823e0f2b50ef
* Version Independent ID: a73386d0-4ff3-dc7a-ae2a-596d03c01e69
* Content: [Create Primary Keys - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/create-primary-keys?view=sql-server-ver15#to-create-a-primary-key-with-nonclustered-index-in-a-new-table)
* Content Source: [docs/relational-databases/tables/create-primary-keys.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/create-primary-keys.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@OLEWebAffairs -- thank you for catching that.  I am updating the document.
