### ISSUE TITLE
Harlan A Nelson

### ISSUE THREAD

**Issue by harlananelson** [MicrosoftDocs/sql-docs#3967]
If you put a high pass filter on the audio for the "Introduction to Azure Data Studio Notebooks" video, it will remove the all the low frequency hum currently in the audio.  You can set the filter to about 120 Hz.  Either that or use a sound treated room when recording the video.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4558fc-19ae-bc48-0f83-2c83aee01252
* Version Independent ID: 5e391c2c-49ed-9a44-7980-ba8db5a26b2d
* Content: [Run notebooks: Azure Data Studio - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/notebooks-guidance?view=sql-server-ver15#feedback)
* Content Source: [docs/big-data-cluster/notebooks-guidance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/notebooks-guidance.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@harlananelson Thank you for the feedback and for providing a solution.

Please note this is considered low priority if the sample still functions accordingly, but I will assign the author to make note of the enhancement.

**Comment by MikeRayMSFT** [comment]
@harlananelson - thank you for the comment. I'm notifying the engineers who can help with this.

**Comment by MikeRayMSFT** [comment]
Thanks for raising the issue, @harlananelson. I've notified the engineers to look at this. I don't hear the problem your describing, but we'll look into the audio quality per your recommendation.

Mike
