### ISSUE TITLE
Docs for Entity Framework Core

### ISSUE THREAD

**Issue by ferronsw** [MicrosoftDocs/sql-docs#3968]
If I'm correct Always Encrypted should be supported in EF Core 3.*
I can't find any docs for how to configure this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf954767-86be-8831-d974-7a3ed7e738f2
* Version Independent ID: 1872e0ad-c841-7cea-0405-0975e9fba946
* Content: [Always Encrypted with .NET Framework Data Provider - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/develop-using-always-encrypted-with-net-framework-data-provider?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/develop-using-always-encrypted-with-net-framework-data-provider.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/develop-using-always-encrypted-with-net-framework-data-provider.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by msebolt** [comment]
@ferronsw Thank you for the feedback, assigning this to the author for further review.

**Comment by RA-Work-A** [comment]
@ferronsw, any update on this?

**Comment by ferronsw** [comment]
@RA-Work-A It only works for .Net Core 3.0 and higher, because of the new Microsoft.Data.SqlClient.

**Comment by RA-Work-A** [comment]
@ferronsw & @msebolt , what's odd about this, is that I can get the reads to work just fine in 2.1. However, it's the inserts that just outright fail to work.

**Comment by VanMSFT** [comment]
Hi @ferronsw! Thanks for submitting this question. I think you already have your answer, but you can find more information on this thread: <https://stackoverflow.com/questions/41027953/sql-server-always-encrypted-with-net-core-not-compatible>

I'll check with the Product Group to see if there are any detailed docs on configuring AE with .NET Core.

**Comment by VanMSFT** [comment]
Hi @ferronsw! I apologize for the delay. The way to use AE with .NET Core is using the new Microsoft.Data.SqlClient provider: https://docs.microsoft.com/sql/connect/ado-net/sql/sqlclient-support-always-encrypted?view=sql-server-ver15

There are currently no plans to document EF with AE.
