### ISSUE TITLE
The step 3 is failing with "Exclusive access could not be obtained because the database is in use"

### ISSUE THREAD

**Issue by nickstocker** [MicrosoftDocs/sql-docs#3969]
The action was carried out through SSMS selecting "Transaction Log" and also selecting "backup the tail of the log" under Media Options which should leave the database in "restoring mode".
After the failure I attempted to put the database into single user mode first and also take it offline but both commands didn't work either.
I have repeated the action against a test database and that worked with no problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b44f028-44c3-531b-3595-8f3fbba19cc6
* Version Independent ID: 10c4091c-d2c3-66ae-f5fd-08b44427b20e
* Content: [Fail over to a log shipping secondary - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/log-shipping/fail-over-to-a-log-shipping-secondary-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/log-shipping/fail-over-to-a-log-shipping-secondary-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/log-shipping/fail-over-to-a-log-shipping-secondary-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@nickstocker -- thank you for your feedback and research.

@MashaMSFT -- please look into this issue 3969.

**Comment by MashaMSFT** [comment]
Hi @nickstocker , thanks for bringing this to our attention! This sounds like a support issue, and not an issue with the documentation, but just to clarify, would you please mind walking me through what steps you've already taken, and what step you're taking when the error occurs?

Have you already applied the transaction log backups in sequence to the secondary database? When you're backing up the transaction log, are you selecting the "WITH NO RECOVERY" option, and is that where you're seeing the error? 

Thanks!
Masha from the SQL Docs team

**Comment by nickstocker** [comment]
Hi @MashaMSFT the reason I suggested documentation is because it doesn't mention taking out of multi user mode.  The steps I took were simply (except for backups etc):  
1. Created the share with the same name on the secondary server
2. Configured permissions on the local log-shipping backup folder 
3. Checked log shipping status. The latest was only on the primary server. This wasn't sync'd because we were not too worried about the data being bang up to date.
4. Then attempted to backup the tail of the T-LOG (leaving the database in restoring state) but that failed as it didn't have exclusive access. 
5. Then tried single user (WITHOUT rollback immediate) i.e. "ALTER DATABASE [DB]
SET SINGLE_USER" - that just hung as did trying to take the database offline.

**Comment by MashaMSFT** [comment]
Hi @nickstocker , thanks for the additional context! Let me look into this for you :)

Thanks!
Masha from the SQL Docs team

**Comment by nickstocker** [comment]
Thanks very much @MashaMSFT

**Comment by nickstocker** [comment]
Hi, @MashaMSFT  have you had chance to look at this yet?
Many Thanks.
Nick

**Comment by kfarlee** [comment]
In step 3, you are preparing the database which had been the primary, to be in the secondary role.  In the secondary role, the database is not accessible to users.  The tail-log backup is used to harvest all of the updates fro the old primary so that it can be applied to the new secondary with no data loss.
The tail-log backup WITH NORECOVERY is used to both take the database offline in preparation for becoming secondary, and to capture the last bit of transactions from the old primary's transaction log.  It is expected that at the conclusion of the tail-log backup with NORECOVERY, the database will not be accessible to users.  Thus it makes sense to kick the users out before running the command.  For completeness, this should be added to the tail-log backup topic.

**Comment by nickstocker** [comment]
Thanks yes that is something I plan to do next time by putting the database into single user mode first. Hopefully that is all that was missing from my plan and from the original online recommended steps.

**Comment by nickstocker** [comment]
Hi @MashaMSFT am I correct in suggesting that the only thing I need to do different is:
USE master;
GO
ALTER DATABASE <db name>
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO 

before I backup the log with
BACKUP LOG <db name>
TO <destination>  
WITH NORECOVERY;  
GO

??
TIA.

**Comment by MashaMSFT** [comment]
@kfarlee , can you please confirm?

Thank you!
Masha from the SQL Docs team

**Comment by kfarlee** [comment]
That's correct, but you need to not forget to take the database back out of single user mode.  As soon as the backup log with NORECOVERY is done, the database will be in a restoring state, and not accessible to users. If the primary fails and you need to bring the secondary online, you WILL want users to connect, and it would be good to make that exercise as short and simple as possible.

**Comment by MashaMSFT** [comment]
Hi @nickstocker , I've published a change to the documentation suggesting that setting the database to single user mode may be necessary. 

Thank you for helping improve our documentation! I'm going to close out this Git Issue at this time, but please feel free to comment should you need anything further.

Thanks again and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
