### ISSUE TITLE
Support for SQL DWH

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/sql-docs#3979]
Per the much more recent document below, SQL DWH supports unique constraints when NOT ENFORCED is used.
https://docs.microsoft.com/en-us/azure/sql-data-warehouse/sql-data-warehouse-table-constraints

Should the doc I am reporting this on be updated to indicate SQL DWH support? I'm not sure if you have an icon to indicate partial support in the "APPLIES TO:" bar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79da4db5-9188-132b-b6eb-4010171a34fd
* Version Independent ID: 2ff26525-5bfd-00c8-942a-809b866a4bdb
* Content: [Create Unique Constraints - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/create-unique-constraints?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/create-unique-constraints.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/create-unique-constraints.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@dcbrown16 -- Dillon, thank you for your feedback.

@stevestein -- Steve, please look into this issue #3979.

**Comment by CarlRabeler** [comment]
Please assign to @julieMSFT

**Comment by CarlRabeler** [comment]
@dcbrown16 I updated the unique constraints doc with a note pointing to the Azure Synapse (SQL DW) article. Thanks for bringing this to our attention.
