### ISSUE TITLE
Missing information on page "Granting permissions on a native mode report server"

### ISSUE THREAD

**Issue by Duncan-Howe** [MicrosoftDocs/sql-docs#3981]
In the file 
[docs/reporting-services/security/granting-permissions-on-a-native-mode-report-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/reporting-services/security/granting-permissions-on-a-native-mode-report-server.md) under the heading "Who sets permissions", second paragraph, there is some information missing about the roles that a local administrator is assigned to

**Comment by WilliamAntonRohm** [comment]
@Duncan-Howe -- thank you for letting us know about this missing information.

@maggiesMSFT -- please look into this issue #3981. 

cc @MightyPen as a writer

**Comment by maggiesMSFT** [comment]
Hi, @Duncan-Howe -- good catch. The info in the rest of the article is complete. That sentence fragment just needed to go away. It's gone now. Thanks!
#please-close
