### ISSUE TITLE
Missing state 

### ISSUE THREAD

**Issue by Typhoon87** [MicrosoftDocs/sql-docs#3982]
Running SQl 2016 13.0.5492.2 I am hitting this error with state 58, state 58 does not appear to exist in this document. Please update it to include additional currently undocumented states.

Error :18456, Severity 14, State 58

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24a18d7d-9f42-c2b4-5338-dcf093d807de
* Version Independent ID: 34d11940-55c0-95ed-46ff-6dd3fe9ab905
* Content: [MSSQLSERVER_18456 - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/mssqlserver-18456-database-engine-error?view=sql-server-ver15)
* Content Source: [docs/relational-databases/errors-events/mssqlserver-18456-database-engine-error.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/errors-events/mssqlserver-18456-database-engine-error.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@Typhoon87 -- thank you for your feedback.

@MashaMSFT -- please look into this issue #3982.

**Comment by MashaMSFT** [comment]
Hi @Typhoon87 , thanks for bringing this to our attention! I've added this error state to the doc. 

Hope that helps and please leave us a comment should you need anything further from us.

Thanks and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
