### ISSUE TITLE
Is `sp_changedbowner` deprecated or not?

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#3989]
Hi there. Is this Security Stored Procedure deprecated or not? There is a deprecation notice at the top of this page, yet it is not noted as being deprecated on the main [Security Stored Procedures](https://docs.microsoft.com/en-us/SQL/relational-databases/system-stored-procedures/security-stored-procedures-transact-sql) page. I checked most of the other links on that page and they were mostly consistent between being marked as "Deprecated" there and having the full deprecation notice on the stored procedure-specific page. As far as I can tell, this is the only proc that has the full deprecation notice (the "Important" note in lt. blue) yet is not noted as being "Deprecated" on that main page.

Also, this proc is _not_ listed as deprecated in what I assume is the official, master list of such things: [Features deprecated in a future version of SQL Server (SQL Server 2017)](https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-2017#features-deprecated-in-a-future-version-of-sql-server).

Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936dce5a-cf4f-f32f-fab6-8b48cb31fa22
* Version Independent ID: ef329dc7-3b6c-d06f-9c71-a1b5ebbe2028
* Content: [sp_changedbowner (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/SQL/relational-databases/system-stored-procedures/sp-changedbowner-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-changedbowner-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-changedbowner-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@srutzky -- Solomon, thank you for your feedback.

@VanMSFT -- Van, please look into this issue #3989 and its related issues #3990 & #3991.

**Comment by VanMSFT** [comment]
@srutzky - Hi Solomon, thanks for the inquiry! sp_changedbowner is still available in SQL Server 2019. It's not fully deprecated and removed as of yet, but the idea of that note is to steer customers away from using that Stored Proc. We will update the list when it is removed. Thanks! Please let us know if you have any questions.

**Comment by srutzky** [comment]
Hello @VanMSFT  Can you please re-open this as per my comments below? Thanks.

> `sp_changedbowner` is still available in SQL Server 2019. It's not fully deprecated and removed as of yet

Deprecated and removed are two entirely separate things. By definition, "deprecated" means that it is still available, just not removed yet (there is a separate list for "discontinued" / "removed" functionality). In fact, all of the system stored procs on that main [Security Stored Procedures](https://docs.microsoft.com/en-us/SQL/relational-databases/system-stored-procedures/security-stored-procedures-transact-sql) page that are listed as "(Deprecated)" are still available in SQL Server 2019.

> ... but the idea of that note is to steer customers away from using that Stored Proc.

Steering customers away from using functionality means that it is indeed deprecated. In fact, at the top of the ["Deprecated Database Engine Features in SQL Server 2017"](https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-2017) page it states:

>> When a feature is marked deprecated, it means:  
>>  
>> * The feature is in maintenance mode only. No new changes will be done, including those related to inter-operability with new features.  
>> * We strive not to remove a deprecated feature from future releases to make upgrades easier. However, under rare situations, we may choose to permanently remove the feature from SQL Server if it limits future innovations.
>>* For new development work, we do not recommend using deprecated features.

And that description matches the notice in light blue at the top of the `sp_changedbowner` page.

> We will update the list when it is removed.

Something needs to be updated prior to that as the current state is inconsistent. Either:
1. Remove the deprecation notice from the top of the `sp_changedbowner` page,

   OR

1. Note that it is deprecated in the following two places (both of which are linked in the main issue above):
    1. the "Security Stored Procedures" page
    1. the "Features deprecated in a future version of SQL Server (SQL Server 2017)" page

Only in doing one of those two things will the documentation be consistent.

Thanks.

**Comment by VanMSFT** [comment]
@srutzky - Hi Solomon, that SP is deprecated. I went ahead and made the changes to the referenced pages. They should update shortly. Thanks again for your help!
