### ISSUE TITLE
Is `sp_change_users_login` deprecated?

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#3990]
Hi there. Is this Security Stored Procedure deprecated or not? There is a partial deprecation notice at the top of this page (most of the top paragraph, but not the full, "Important" note in light blue that is on most/all other deprecated pages), yet it is _not_ noted as being deprecated on the main [Security Stored Procedures](https://docs.microsoft.com/en-us/SQL/relational-databases/system-stored-procedures/security-stored-procedures-transact-sql) page. I checked most of the other links on that page and they were mostly consistent between being marked as "Deprecated" there and having the full deprecation notice on the stored procedure-specific page.

Also, this proc _is_ listed as deprecated in what I assume is the official, master list of such things: [Features deprecated in a future version of SQL Server (SQL Server 2017)](https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-2017#features-deprecated-in-a-future-version-of-sql-server).

Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62e3205d-c195-4d70-f908-958f7a354ddf
* Version Independent ID: 9023af42-e911-f4b8-394f-6bc05f615340
* Content: [sp_change_users_login (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/SQL/relational-databases/system-stored-procedures/sp-change-users-login-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-change-users-login-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-change-users-login-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@srutzky -- Solomon, thank you for your feedback.

@VanMSFT -- Van, please look into this issue #3990 and its related issues #3989 & #3991.

**Comment by VanMSFT** [comment]
Hi @srutzky! Thanks, I'm checking on this with the Product Group to see if I can clarify the SPs.

**Comment by VanMSFT** [comment]
Hello @srutzky! Actually, I checked the code and it is deprecated. I'm adding the text in a note for the sp_change_users_login doc, and added Deprecated next to the Security SP list. Thanks again for submitting this issue!
