### ISSUE TITLE
Should `sp_changedbowner` be replaced with `ALTER AUTHORIZATION`?

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#3991]
In the [Remarks](https://docs.microsoft.com/en-us/SQL/t-sql/statements/create-database-transact-sql#remarks) section above, it states:

> Each database has an owner that can perform special activities in the database. The owner is the user that creates the database. The database owner can be changed by using **`sp_changedbowner`**.

While the jury is still out on [whether or not `sp_changedbowner` is deprecated (&#35;3989)](https://github.com/MicrosoftDocs/sql-docs/issues/3989), at the very least it was superseded by [ALTER AUTHORIZATION](https://docs.microsoft.com/en-us/SQL/t-sql/statements/alter-authorization-transact-sql) when SQL Server 2008 was released (12 years ago). `sp_changedbowner` is still required for SQL Server 2005, but that has been out of support for at least 4 years.

Is there any reason to not replace `sp_changedbowner` with `ALTER AUTHORIZATION` and add `ALTER AUTHORIZATION` to the "**See Also**" section? There could still be a note informing readers that `sp_changedbowner` should instead be used for versions prior to SQL Server 2008.

Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e8abfde-2523-5c70-bb95-b10101a726ff
* Version Independent ID: 3b8152d2-b49e-df4b-0f05-3ec52aa5bb71
* Content: [CREATE DATABASE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/SQL/t-sql/statements/create-database-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-database-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-database-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@srutzky -- Solomon, thank you for your feedback.

@VanMSFT -- Van, please look into this issue #3991 and its related issues #3989 & #3990.

**Comment by VanMSFT** [comment]
Thanks @srutzky! I changed the doc to use ALTER AUTHORIZATION instead of sp_changedbowner. We appreciate you bringing this to our attention!
