### ISSUE TITLE
Permissions incorrect (?)

### ISSUE THREAD

**Issue by jimp100** [MicrosoftDocs/sql-docs#3992]
The article states a user needs "db_ddladmin and db_owner fixed database roles" in order to create indexes.  I don't believe this to be correct, a user can create indexes with just db_ddladmin database role.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13793c61-629f-f379-fcb7-e9178e4f5dce
* Version Independent ID: ced6efc1-1e34-f452-f995-b597e812c2f2
* Content: [CREATE INDEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver15#permissions)
* Content Source: [docs/t-sql/statements/create-index-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-index-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@jimp100 Thank you for the feedback, assigning this to the author for review.

**Comment by pmasl** [comment]
It's an OR permission, I'll correct the article asap.

**Comment by CarlRabeler** [comment]
fixing now: https://github.com/MicrosoftDocs/sql-docs-pr/pull/14157

@jimp100 sorry it took us this long - slipped through the cracks.
