### ISSUE TITLE
missing space

### ISSUE THREAD

**Issue by monrealis** [MicrosoftDocs/sql-docs#3995]
"sqlcmd-v X=Y" is missing a space. There's no command sqlcmd-v.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f5f9d0-f5c3-a8c8-7800-823a95c1ea07
* Version Independent ID: 9b623a77-8813-88f4-e78f-e6a63dd87709
* Content: [Use sqlcmd with Scripting Variables - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/scripting/sqlcmd-use-with-scripting-variables?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/scripting/sqlcmd-use-with-scripting-variables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/sqlcmd-use-with-scripting-variables.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@monrealis Thank you for the feedback.

The documentation has been updated and is pending review.

Please consider [becoming a contributor](https://docs.microsoft.com/contribute)!
