### ISSUE TITLE
CREATE EXTERNAL TABLE examples does not include an ODBC example

### ISSUE THREAD

**Issue by wsuhoey** [MicrosoftDocs/sql-docs#3996]
There needs to be an example that shows how to create an external table that uses an ODBC external data source, now that PolyBase in SQL Server 2019 allows ODBC.

**Comment by msebolt** [comment]
@wsuhoey Thank you for the feedback.

Please refer to [Configure PolyBase to access external data](https://docs.microsoft.com/sql/relational-databases/polybase/polybase-configure-odbc-generic) and comment below on any information you find missing.

**Comment by msebolt** [comment]
Closing this now, please comment below if you'd like the issue re-visited.
