### ISSUE TITLE
Error Code 2058

### ISSUE THREAD

**Issue by HunedMSFT** [MicrosoftDocs/sql-docs#3997]
Error code 2058 and workaround/fix is missing from this list.

https://melodiouscode.net/sql-azure-key-vault/
https://www.visualstudiogeeks.com/devops/SqlServerKeyVaultConnectorProviderError2058RegistryConsultEKMProvider
https://sysadmin-monkey.net/2018/03/errors-with-february-2018-sql-connector-for-azure-key-vault/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 248641a9-2364-dcbf-b071-6df585b05bba
* Version Independent ID: bd00d184-ff67-3b36-2d8f-22d05538a92f
* Content: [SQL Server Connector maintenance & troubleshooting - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/sql-server-connector-maintenance-troubleshooting?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/sql-server-connector-maintenance-troubleshooting.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/sql-server-connector-maintenance-troubleshooting.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by msebolt** [comment]
@HunedMSFT Thank you for the feedback.

Assigning this to the author for further review.

**Comment by VanMSFT** [comment]
Hello @HunedMSFT! Thanks for submitting this issue. I apologize for the delay. We are currently looking at updating the error code list.

**Comment by NikoNeugebauer** [comment]
Would love to see this situation solved, since all new users are facing it.
In any case, editing registry keys does not look like a really good way to encourage further usage of Azure Key Vault or EKM and finding error code on other pages than official documentation rises the question of the trust.

**Comment by VanMSFT** [comment]
We're working on getting the list updated, and the doc should be changed soon. We appreciate your patience, and thank you so much for bringing it to our attention!

**Comment by VanMSFT** [comment]
It looks like error code 2058 is still missing from the list after our update.

@Rupp29 - Can you please help look into this?

#assign:Rupp29
#unassign:jaszymas

**Comment by Rupp29** [comment]
I’ll look into getting these error codes from an engineer, but as far as I can tell, this was not in the list of errors I got from the developer… since I literally copied them from source code, I’m not sure how to track this down.
@vidit gupta

**Comment by rothja** [comment]
@Rupp29 Do you have any other leads on how we can track this down to add to the documentation? Thanks for your help!

**Comment by Rupp29** [comment]
I do not...
Other than asking the engineer (Rajat or Vidit) to track it down.
I had access to the source control at one time (which is where I got the additional 150 error codes)...
But this error code (2058) was not in the list...
So Rajat or Vidit may be able to assist, but I have exhausted my efforts to find this.


::Adrian
425.753.4998

**Comment by VanMSFT** [comment]
I'll see if I can track down the source code

**Comment by VanMSFT** [comment]
Added error with the help of Rajat.

Thanks for bringing this up, @HunedMSFT!
