### ISSUE TITLE
Run Time, Run Duration

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/sql-docs#3998]
This page says:  
&gt;&gt; run_time	int	Time the job or step started.
&gt;&gt; run_duration	int	Elapsed time in the execution of the job or step in HHMMSS format.
The format note here should also be describing the run_time field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1188cb1-de0a-ce57-5baf-40ae903b41ef
* Version Independent ID: 86dc9874-a01d-e26f-d13b-3785ffd5c497
* Content: [dbo.sysjobhistory (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/dbo-sysjobhistory-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-tables/dbo-sysjobhistory-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/dbo-sysjobhistory-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@cbailiss Thank you for the feedback.

The documentation has been updated and is pending review.

Please consider [becoming a contributor](https://docs.microsoft.com/contribute).
