### ISSUE TITLE
Second SQL example for HAVING does not match the description

### ISSUE THREAD

**Issue by sbitaxi** [MicrosoftDocs/sql-docs#3999]
https://docs.microsoft.com/en-us/sql/t-sql/queries/select-having-transact-sql?view=sql-server-ver15#examples--and-

The description for the example states "...when the OrderDateKey is in the year 2004 or later." However, the query is on the Sales Amount "HAVING SUM(SalesAmount) &gt; 80000". Without knowing what the OrderDateKey field holds, I'm not able to recommend a specific correction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 373ffad1-a3a6-6b61-3ff1-41ba75ae46a5
* Version Independent ID: c97b36a4-d176-ce8b-f3ae-7f7e235b2d96
* Content: [HAVING (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-having-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/queries/select-having-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/select-having-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @sbitaxi - Thanks for your feedback on this page! I have fixed the example text, and it should go live later today. We really appreciate your assistance on our documentation.

**Comment by sbitaxi** [comment]
Wow, that was fast. Thank you for the update. Happy to help.

Steven
