### ISSUE TITLE
mssql-server service doesn't start after certificate installation

### ISSUE THREAD

**Issue by goeasyflow** [MicrosoftDocs/sql-docs#4004]
The procedure explaining how to install is missing the fact that the /etc/ssl/private directory by default has root read-only permissions, so following the procedure as is ends up with the mssql-server service not starting.

Permission on that folder must be changed to read and execute.

**Comment by msebolt** [comment]
@goeasyflow  Thank you for the feedback.

Can you provide a reference to the article in question?

We can then assign this to an author for further review.

**Comment by msebolt** [comment]
Closing this now, please comment below if you'd like the issue re-visited.
