### ISSUE TITLE
Does 18.4.1 support ordered clustered columnstore indexes in Synapse

### ISSUE THREAD

**Issue by mwc360** [MicrosoftDocs/sql-docs#4012]
Does 18.4.1 support ordered clustered columnstore indexes in Synapse? The installed DevOps agent version (18.3.1) doesn't support them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 121d051e-9962-0554-b11d-ba22c1802ff7
* Version Independent ID: 3fc25a21-a2b1-8d06-2ba2-373112e004ef
* Content: [DacFx and SqlPackage release notes - SQL Server](https://docs.microsoft.com/en-us/sql/tools/release-notes-sqlpackage?view=sql-server-ver15)
* Content Source: [docs/tools/release-notes-sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/release-notes-sqlpackage.md)
* Product: **sql**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by msebolt** [comment]
@mwc360 Thank you for the question.

Unfortunately our support options are limited to documentation examples only.

For feature specific questions please start a thread [here](https://feedback.azure.com/forums/908035-sql-server) for feedback from the product team.

@pensivebrian

**Comment by pensivebrian** [comment]
Adding @kevinvngo who might know the status of this feature.

**Comment by rothja** [comment]
@kevinvngo Could you help out with this question? #assign:kevinvngo.

**Comment by PRMerger12** [comment]
kevinvngo. is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by dzsquared** [comment]
Hi @mwc360 - support for ordered CCIs was introduced in sqlpackage 18.5 (https://docs.microsoft.com/en-us/sql/tools/release-notes-sqlpackage?view=sql-server-ver15#features-1)
The virtual environments for devops agents should currently be 18.5.1 and include this feature.

thanks!

#assign:dzsquared

**Comment by dzsquared** [comment]
#please-close
