### ISSUE TITLE
Column name error

### ISSUE THREAD

**Issue by sclover** [MicrosoftDocs/sql-docs#4014]
pool_id should be external_pool_id

Looks like it _has_ been renamed :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8a97fb-6654-1717-a3c5-b884b3b7b168
* Version Independent ID: dfd5ced6-5321-b1d8-39af-2d5944e488a0
* Content: [sys.resource_governor_external_resource_pools (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-resource-governor-external-resource-pools-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-catalog-views/sys-resource-governor-external-resource-pools-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-resource-governor-external-resource-pools-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@sclover -- stephen, thank you for bringing this to our attention.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please review the above-mentioned PR.
