### ISSUE TITLE
Correction to the comment in Example I.

### ISSUE THREAD

**Issue by bderwart** [MicrosoftDocs/sql-docs#4015]
If you following the steps in Example I and are using the Progress DataDirect Oracle WP ODBC driver to create an external table to an Oracle table, then the LOCATION string cannot contain the database_name. This driver does not support catalogs, so creating an external table with this naming convention will result in an error when you try to SELECT from the external table.

Instead of using a three part name of the format  '&lt;database_name&gt;.&lt;schema_name&gt;.&lt;object_name&gt;', you should instead use a string that only contains the table name. Example I already shows a sample CREATE EXTERNAL TABLE statement showing this format.

If you need for the schema_name to be part of the reference to the Oracle table in the external table definition, then use a string where the database_name value has been left blank, but keep the dot before the schema name. Here's an example:

CREATE EXTERNAL TABLE customers(
   [O_ORDERKEY] DECIMAL(38) NOT NULL,
   [O_CUSTKEY] DECIMAL(38) NOT NULL,
   [O_ORDERSTATUS] CHAR COLLATE Latin1_General_BIN NOT NULL,
   [O_TOTALPRICE] DECIMAL(15,2) NOT NULL,
   [O_ORDERDATE] DATETIME2(0) NOT NULL,
   [O_ORDERPRIORITY] CHAR(15) COLLATE Latin1_General_BIN NOT NULL,
   [O_CLERK] CHAR(15) COLLATE Latin1_General_BIN NOT NULL,
   [O_SHIPPRIORITY] DECIMAL(38) NOT NULL,
   [O_COMMENT] VARCHAR(79) COLLATE Latin1_General_BIN NOT NULL
   )
   WITH (
    LOCATION='.mySchema.customer',
    DATA_SOURCE= external_data_source_name
   );

The CREATE EXTERNAL TABLE statement will fail to execute if you use a LOCATION string of the format '&lt;schema_name&gt;.&lt;object_name&gt;'. Adding the dot to this string before the schema_name argument provides a workaround to this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ac2fe2-31da-7db6-2d5f-5091022f41d2
* Version Independent ID: bbf07c2c-7006-7b94-f12f-800fa7bc67e4
* Content: [CREATE EXTERNAL TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-table-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-external-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@bderwart -- thank you for your detailed feedback.

@CarlRabeler -- Carl, please look into this issue #4015.

**Comment by CarlRabeler** [comment]
Thank you. PR to fix this example is pending.
