### ISSUE TITLE
Misleading statement

### ISSUE THREAD

**Issue by potato-enthusiast** [MicrosoftDocs/sql-docs#4016]
The definition for owning_principal_id: 
"ID of the principal that owns this principal. All principals except Database Roles must be owned by dbo."
On my ASDW instance, the value for "owning_principal_id" for all of my SQL_USER principals is NULL. 
Is NULL equivalent to dbo? I expect the SQL_USER's owning_principal_id be that of dbo, which is 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07bfd80a-5650-4c57-e6a3-f40e813f08b0
* Version Independent ID: 9e6e2d00-9df8-2fa2-7336-aa2d3f17bd1c
* Content: [sys.database_principals (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-principals-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-catalog-views/sys-database-principals-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-database-principals-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @potato-enthusiast! Thanks for bringing this issue up. I'll check on this.

**Comment by VanMSFT** [comment]
Hi @potato-enthusiast - We've confirmed that fixed database roles are owned by dbo, and not SQL_USER principals. I'm changing the doc, and it should be updated soon. Thanks again for bringing this to our attention!
