### ISSUE TITLE
FORMATFILE_DATASOURCE needs to be FORMATFILE_DATA_SOURCE

### ISSUE THREAD

**Issue by nruffilo** [MicrosoftDocs/sql-docs#4017]
The docs reference:    [ [ , ] FORMATFILE_DATASOURCE = 'data_source_name' ] but sqlserver only allows FORMATFILE_DATA_SOURCE  It just needs the _ in it.

Have a great day

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5106a6-4e54-2177-3e03-b2845f9587c5
* Version Independent ID: c3bc5aaa-0119-9c4d-3d7b-0ee218885361
* Content: [BULK INSERT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/bulk-insert-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/bulk-insert-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/bulk-insert-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@nruffilo -- thank you for letting us know.  I am looking into the document.
