### ISSUE TITLE
Document for the *pattern* format is missing

### ISSUE THREAD

**Issue by festerman** [MicrosoftDocs/sql-docs#4019]
.. and an example showing how to use this would be nice. https://stackoverflow.com/questions/3891331/find-non-ascii-characters-in-varchar-columns-using-sql-server has an example (but not as the selected answer ...) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ee250de-0d7b-7f3c-66a7-e47e9b96304c
* Version Independent ID: 49c960f5-80ab-cd68-f8e8-da3cd3a59b63
* Content: [PATINDEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/patindex-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/patindex-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/patindex-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@festerman -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue #4019.

**Comment by MikeRayMSFT** [comment]
@festerman -- thank you for your feedback. Evaluating options.

**Comment by bluefooted** [comment]
@festerman Thanks this is a great suggestion! We need to make a few different changes for this, I think it makes sense to add a link to the wildcard documentation here in addition to the example https://docs.microsoft.com/en-us/sql/t-sql/language-elements/wildcard-character-s-to-match-transact-sql?view=sql-server-ver15 I will take care of this in a separate pull request.

**Comment by bluefooted** [comment]
@festerman The documentation for PATINDEX has been updated, along with the documentation for [] and [^]. I've added new examples (not the same as the StackOverflow issue, but similar). Let me know if this clarifies the scenario.

**Comment by festerman** [comment]
@bluefooted neat! thx!
