### ISSUE TITLE
The Query for example 2 syntax is incorrect

### ISSUE THREAD

**Issue by dfhampshire** [MicrosoftDocs/sql-docs#4020]
The 4th line reads
SET @jsonInfo=N'{"info":{"address":[{"town":"Paris"},{"town":"London"}]}';

it should read:
SET @jsonInfo=N'{"info":{"address":[{"town":"Paris"},{"town":"London"}]}}';

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28e8713d-8b6e-7e43-04cc-e2720891b56c
* Version Independent ID: d09b9ed6-4e55-7d18-b17f-88e17839074d
* Content: [JSON_VALUE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-value-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/json-value-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/json-value-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@dfhampshire -- thank you for your detailed feedback.  I am looking into the document.

**Comment by WilliamAntonRohm** [comment]
@dfhampshire -- Thank you for your feedback.  I have updated the documentation.
