### ISSUE TITLE
Tested classification parameter precedence does not match that of document, specifically for labels

### ISSUE THREAD

**Issue by potato-enthusiast** [MicrosoftDocs/sql-docs#4022]
The statement "The higher precedence matching classifier is used first to assign a workload group and importance. The precedence goes as follows: [user, role, label, session, time]" does not agree with a test that I ran.

If I make a classifier:
CREATE WORKLOAD CLASSIFIER wc_staticrc30_nolabel WITH ( 
	WORKLOAD_GROUP = 'staticrc30'
	,MEMBERNAME     = 'mic_default'  
)

And then I run:
select COUNT_BIG(*)
from clearing.transactionAttributes
OPTION (LABEL = 'wc_staticrc10')

It runs with classifier wc_staticrc30_nolabel, as expected

If I create a second classifier:
CREATE WORKLOAD CLASSIFIER wc_staticrc10_label WITH ( 
	WORKLOAD_GROUP = 'staticrc10'
	,MEMBERNAME     = 'mic_default'  
	,WLM_LABEL      = 'wc_staticrc10' 
)

And then I run:
select COUNT_BIG(*)
from clearing.transactionAttributes
OPTION (LABEL = 'wc_staticrc10')

It runs with classifier wc_staticrc10_label

I've already shown that the query matches wc_staticrc30_nolabel. Thus, the query matched against both wc_staticrc30_nolabel and wc_staticrc10_label. According to the hierarchy, wc_staticrc30 should have been the classifier because it matched at a higher point in the hierarchy.

The unwritten rule appears to be:
If a query that specifies a label matches a classifier with also specifies that label, then that classifier takes precedence over other matching classifiers that do not specify a label at all.

However the same pattern does apply to start_time/end_time. As the the example in this article demonstrates that even though classifierB matches the query, classifier A matches it higher in the hierarchy and is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30bae37b-efd5-a4bb-6e5a-474f5688283a
* Version Independent ID: 1fc3e0d9-98d3-67ea-372b-a7aeb4b8ba05
* Content: [CREATE WORKLOAD Classifier (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-workload-classifier-transact-sql?view=azure-sqldw-latest)
* Content Source: [docs/t-sql/statements/create-workload-classifier-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-workload-classifier-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @ronortloff
* Microsoft Alias: **rortloff**

**Comment by msebolt** [comment]
@potato-enthusiast Thank you for the feedback.

Assigning this to the author for further review.

**Comment by ronortloff** [comment]
Hello @potato-enthusiast, 
Thanks for the question.  A doc update is coming that should help clarify.  There is a parameter weighting that takes effect when evaluating classifiers.  wc_staticrc10_label has a higher weight than wc_staticrc30_nolabel.  If you have any questions after the doc update, please let me know.

**Comment by ronortloff** [comment]
#please-close
