### ISSUE TITLE
Trace Flags 3604 & 3605 to redirect output

### ISSUE THREAD

**Issue by LonnyNiederstadt** [MicrosoftDocs/sql-docs#4023]
Some trace flags in the list require trace flags 3604 or 3605 to redirect output.
For example, trace flag 8721 will produce output for auto-stats updates (both sync and async) but without accompanying trace flag 3605 to direct output to SQL Server error log, trace flag 8721 isn't very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0e35dc1-14be-0678-aeae-88de1c7601ac
* Version Independent ID: b3700e3e-acbf-9248-c333-ac9013827d84
* Content: [Trace Flags (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by pmasl** [comment]
Thanks Lonny, I'll put it in the backlog to scrub which TFs need 3604 or 3605 and add that info. Those in turn are also not documented.

**Comment by rothja** [comment]
@pmasl Pedro, did you have a chance to check on this yet and add the information to the doc? Thanks!

**Comment by pmasl** [comment]
Haven't had a chance yet. This is Pri2.

**Comment by pmasl** [comment]
#please-close
