### ISSUE TITLE
Upgrade Failed

### ISSUE THREAD

**Issue by mwdarab** [MicrosoftDocs/sql-docs#4027]
I tried this but still got the error: "Control plane upgrade failed. Failed to upgrade controller."

I am running a Big Data Cluster on a single node kubeadm cluster (on-prem). I even increased the thresholds but still failed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8fc75e5-8fba-36bb-9339-c2887150cae1
* Version Independent ID: 8b46f98f-1a38-a5e7-025f-49ae7570d389
* Content: [Upgrade to a new release - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-upgrade?view=sql-server-ver15#upgrade-from-supported-release)
* Content Source: [docs/big-data-cluster/deployment-upgrade.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deployment-upgrade.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@mwdarab  Thank you for contacting Microsoft.

Please refer to issue https://github.com/MicrosoftDocs/sql-docs/issues/4026 for further details.
