### ISSUE TITLE
Add Usage Examples for Operations

### ISSUE THREAD

**Issue by brunomartinspro** [MicrosoftDocs/sql-docs#4028]
Adding examples of how this tool can be used to perform operations is a major improvement to this document.
Example: generate differences between two databases, produce .dacpac files and generate a delta script - also including a user and password to authenticate to a SQL Server or Azure 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage.exe - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage?redirectedfrom=MSDN&view=sql-server-ver15&source=docs)
* Content Source: [docs/tools/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage.md)
* Product: **sql**
* Technology: **ssdt**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by brunomartinspro** [comment]
Found examples on https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/sql-server-actions.md

**Comment by msebolt** [comment]
@brunomartinspro Thank you for the feedback and for providing the necessary changes.

Assigning this to an author for further review.

**Comment by rothja** [comment]
I asked Brian to review the changes in the PR. @brunomartinspro Thanks for your patience!
