### ISSUE TITLE
Passwords should always be at least ten characters long, rather than eight characters long.

### ISSUE THREAD

**Issue by LifeRyuto** [MicrosoftDocs/sql-docs#4031]
Hi,
When creating a login, passwords should be at least 10 characters long apparently.
When I specified 8 characters long password, "too short" error always occurred.
This is regarding SQL Database managed instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0f4b3be-5686-ac31-8c5d-676e08953d8f
* Version Independent ID: 43881484-714e-d528-7a38-72d24a2d40d1
* Content: [CREATE LOGIN (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-login-transact-sql?view=azuresqldb-mi-current)
* Content Source: [docs/t-sql/statements/create-login-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-login-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@LifeRyuto Thank you for the feedback.

Can you please specify the details of your query and SQL version?

On my machine the following query generates a "too short" error,

```
CREATE LOGIN test WITH PASSWORD = 'pa4sw!r';
GO
```

...but this query works without error,

```
CREATE LOGIN test WITH PASSWORD = 'pa4sw!rd';
GO
```
...using SQL Server 14.0.2027.2.

**Comment by LifeRyuto** [comment]
@msebolt Thank you for your reply.

Sorry, I talked about SQL Database managed instance.

The following query generated a "too short" error.

```
CREATE LOGIN test WITH PASSWORD = 'pa4sw!rd';
GO
```

```
Msg 15116, Level 16, State 1, Line 1
Password validation failed. The password does not meet the operating system policy requirements because it is too short.

Completion time: 2020-01-29T09:09:11.2982764+09:00
```

**Comment by msebolt** [comment]
@LifeRyuto Sounds good, we'll get an update to this documentation out shortly.

**Comment by VanMSFT** [comment]
Thanks @LifeRyuto! I've fixed the doc, and it should go live shortly. Thanks again for helping us on this!
