### ISSUE TITLE
Please provide definitions

### ISSUE THREAD

**Issue by barryblessing** [MicrosoftDocs/sql-docs#4033]
This page provides adequate code examples of the uses of these join hints, but provides neither clarity to their hint definition or links to pages that establish their exact definition.  Either would be welcome to better understand their respective definition, function and use case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0643ce4d-5fa1-fe37-a28f-72f4a3adee85
* Version Independent ID: eaf6dc7d-368d-3fbc-50d9-b9b72cb253d3
* Content: [Join Hints (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-join?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/queries/hints-transact-sql-join.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/hints-transact-sql-join.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@barryblessing Thank you for the feedback.

Assigning this to the author for further review.

**Comment by VanMSFT** [comment]
Thanks for the feedback, @barryblessing! I've added a link to our Joins page that explains the different joins. The doc should be updated later today.
