### ISSUE TITLE
Connect from outside via jdbc tcpip

### ISSUE THREAD

**Issue by KDNeufeld** [MicrosoftDocs/sql-docs#4034]
The "Connect from outside the container" is missing documentation on how to enable TCP/IP connections from a jdbc connection url.
The sqlcmd example has the host as "&lt;ip_address&gt;,1433"
But a jdbc connection url uses a colon, not a comma, to separate host and port so this doesn't work.
How do I enable TCP/IP connections to the container using docker?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-bash#feedback)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by msebolt** [comment]
@KDNeufeld Thank you for the question, we apologize for any issues you're experiencing.

Assigning this to the author for review.

**Comment by caio-davi** [comment]
Aren't they enabled by default? 
If you started the container with `-p 1433:1433` it should be listening the 1433 port.

**Comment by datauduong** [comment]
question about the linked server connection, I can't see any provider on SQL 2019 Linux on Docker Container. Is this a limitation or Is there something I can do. Thanks.

**Comment by VanMSFT** [comment]
Hello @KDNeufeld! The port mapping is listed in the referenced doc: https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-bash#pullandrun2019

If you are connecting outside of the container, you would use the specification necessary for any driver/provider being used. Here is the documentation on using Microsoft's JDBC Driver: https://docs.microsoft.com/en-us/sql/connect/jdbc/using-the-jdbc-driver?view=sql-server-ver15#making-a-simple-connection-to-a-database

@datauduong - You should be able to install drivers manually if they are not present: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15

@vin-yu - Please provide any additional comments.

**Comment by rothja** [comment]
@KDNeufeld @datauduong Thanks for your feedback and questions. Based on Van's response, I'm going to close this issue, but feel free to add any additional comments on this issue thread. Thank you!
