### ISSUE TITLE
Missing Errors: 4878, 4879, Severity: 16

### ISSUE THREAD

**Issue by torjo2k** [MicrosoftDocs/sql-docs#4036]
There's not a single reference to 4879 in all of the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5973cd79-d024-6670-8b9f-d02d9824e8ec
* Version Independent ID: 9c7e4cd4-9bd7-16ad-83c0-9c114e5eec46
* Content: [Database engine events and errors - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-events-and-errors?view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/relational-databases/errors-events/database-engine-events-and-errors.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/errors-events/database-engine-events-and-errors.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @torjo2k  , thank you for bringing this to our attention! While this list is not meant to be exhaustive, such a disclaimer was missing from the documentation. We added the disclaimer, along with a query you can use to get the full list from the system engine. 

As a courtesy, however, we did add the error message that you pointed out was missing, along with a few others. 

I hope that helps, and please leave us a comment should you need anything further. 

Thanks and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
