### ISSUE TITLE
Create an Official Microsoft.SqlPackage NuGet Package

### ISSUE THREAD

**Issue by brunomartinspro** [MicrosoftDocs/sql-docs#4037]
This is a very useful tool when used correctly, to avoid unofficial versions of this tool to be publicly available i propose creating an official package for .Net Core and  .Net Framework.

Example of unofficial packages: https://www.nuget.org/packages/SqlPackage.CommandLine/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage.exe - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/tools/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage.md)
* Product: **sql**
* Technology: **ssdt**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by msebolt** [comment]
@brunomartinspro Thank you for the feedback.

Assigning this to an author for further review.

We could make the download link more present, though any changes involving packages should be submitted to the product team [here](https://feedback.azure.com/forums/908035-sql-server).

**Comment by yualan** [comment]
Hi @brunomartinspro, my name is Alan Yu, a PM on the SQL Tools team. I have discussed this with Brian O'Neill, the tech lead for sqlpackage.

On the current roadmap, we don't plan to create an official NuGet Package onthe NuGet marketplace. We encourage unofficial maintainers to direct customers to the official docs package, which includes the bits for all platforms.

...that said, we are looking into investment into: https://docs.microsoft.com//dotnet/core/tools/global-tools 

This includes a line: "A .NET Core Global Tool is a special NuGet package that contains a console application. "

@msebolt I would consider this issue closed as we are looking into future global-tools support.

**Comment by isaacabraham** [comment]
@yualan what's the recommended approach if we want to use SqlPackage as part of an application e.g. build script and don't want developers to have to install an MSI on their machine first? Ideally it should be possible to bundle SQL Package within our repo - surely other people are trying to do this, too?
