### ISSUE TITLE
The January release information is missing

### ISSUE THREAD

**Issue by dbamaster** [MicrosoftDocs/sql-docs#4038]
I was checking the last version and month for the last release, I cannot find the January 2020 information.

![image](https://user-images.githubusercontent.com/38668645/73292502-63f85700-41bf-11ea-834b-219a8660db4a.png)

I also compared to my local installation (macOS), the version match the last one on the Microsoft docs page - no updates are available
![image](https://user-images.githubusercontent.com/38668645/73292575-838f7f80-41bf-11ea-8f4a-4f5b9563bafb.png)

![image](https://user-images.githubusercontent.com/38668645/73292867-116b6a80-41c0-11ea-9140-099076629e6a.png)

Thanks!

**Comment by msebolt** [comment]
@dbamaster Thank you for the feedback.

Assigning this to the author of [Release Notes for Azure Data Studio](https://docs.microsoft.com/sql/azure-data-studio/release-notes-azure-data-studio) for further review.

**Comment by markingmyname** [comment]
@dbamaster 

We did not have a Jan 2020 release for Azure Data Studio.

However, we are currently working on the next release. No ETA as of yet.

**Comment by yualan** [comment]
My suggestion is to close this issue since we did not have a January release, but will have one soon for Feb :)

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit Azure Data Studio repo(https://github.com/microsoft/azuredatastudio)

**Comment by dbamaster** [comment]
> @dbamaster
> 
> We did not have a Jan 2020 release for Azure Data Studio.
> 
> However, we are currently working on the next release. No ETA as of yet.

That makes sense, thanks for the explanation.

**Comment by dbamaster** [comment]
> My suggestion is to close this issue since we did not have a January release, but will have one soon for Feb :)

Awesome! Sorry for the false alarm 👍
