### ISSUE TITLE
XML Core support for Azure SQL DB

### ISSUE THREAD

**Issue by ananth3010** [MicrosoftDocs/sql-docs#4041]
Link here specifies that Azure SQL database supports XML: https://docs.microsoft.com/en-us/azure/sql-database/sql-database-multi-model-features#xml-features

Where as this link states Azure SQL DB is not supported: https://docs.microsoft.com/en-us/sql/relational-databases/xml/xml-data-sql-server?view=sql-server-ver15

Could you please update the support matrix in the "Applies To" section with the right info?

**Comment by msebolt** [comment]
@ananth3010 Thank you for the feedback.

Assigning this to the author of [XML data](https://docs.microsoft.com/sql/relational-databases/xml/xml-data-sql-server) to reconcile.

@jovanpop-msft

**Comment by MightyPen** [comment]
@ananth3010 Hello, This article's AppliesTo, and it Versioning configuration, have been fixed to now include Azure SQL Database.

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/13725`

Thanks for bringing this problem to our attention.
Thank you for submitting this Issue. We hope to hear from you again.
