### ISSUE TITLE
No sudo

### ISSUE THREAD

**Issue by MisterY** [MicrosoftDocs/sql-docs#4042]
There is no sudo in the latest images. How is this supposed to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c90871c9-0cc1-9630-e129-fb0a90201977
* Version Independent ID: 53421935-b14c-82ef-70e6-2d382fa8e7f8
* Content: [Troubleshoot SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-troubleshooting-guide?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-troubleshooting-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-troubleshooting-guide.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@MisterY Thank you for the feedback. 

Please provide information on what image you're using and we will try to resolve this issue.

Note that tests on the latest Ubuntu 18.04 image does not experience this problem.

**Comment by MisterY** [comment]
@msebolt, thanks for the feedback. I was using "latest" and later "2017-latest" but didn't manage with either. I guess that "latest" uses "2019-latest".

**Comment by MisterY** [comment]
Oh, that's interesting. According to the table at https://hub.docker.com/_/microsoft-mssql-server, both of the images I mentioned are using 16.04 and I've read elsewhere that su is disabled and sudo needs to be installed separately, which is not possible, unfortunately.
Which tags can I use to get 18.04?
Thanks

**Comment by MisterY** [comment]
This is what I get when using `2019-latest`:

![image](https://user-images.githubusercontent.com/462445/73431873-ae094600-4341-11ea-8922-9cddf4d9e6b5.png)

**Comment by msebolt** [comment]
@MisterY Apologies, I wasn't aware you were using Docker and was referring to the Azure Ubuntu image.

Please refer to [this post](https://stackoverflow.com/questions/25845538/how-to-use-sudo-inside-a-docker-container/49529946) for possible options and I'll assign this the author for further review.

**Comment by VanMSFT** [comment]
Hi @MisterY! Are you using Docker? If so, you will likely need to use the publish flag to open ports: https://docs.docker.com/config/containers/container-networking/
