### ISSUE TITLE
No sudo available

### ISSUE THREAD

**Issue by MisterY** [MicrosoftDocs/sql-docs#4043]
In the latest default images, there is no sudo available. How are we supposed to open the ports?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d88f222-c450-29e0-922c-b83228df4985
* Version Independent ID: 416d38e5-c07f-dd58-f59c-5045f68054b8
* Content: [How to configure MSDTC on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-msdtc?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-configure-msdtc.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-msdtc.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@MisterY Thank you for the feedback.

This issue is currently active in https://github.com/MicrosoftDocs/sql-docs/issues/4042.

Please refer there for additional questions and/or concerns.
