### ISSUE TITLE
SQL Log Shipping Windows -> Linux

### ISSUE THREAD

**Issue by viniciuskoberwc** [MicrosoftDocs/sql-docs#4046]
Hi, it's possible to configure log shipping in a scenario where the primary server is running SQL Server 2017 on an Windows Server 2016, and the secondary server is running an Linux distro?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae3bc9b9-65f5-13bb-53c5-ed929a94b638
* Version Independent ID: eccef86a-10ea-2bbb-ab1b-c530b3fb758c
* Content: [Configure log shipping for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/Linux/sql-server-linux-use-log-shipping?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-use-log-shipping.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-use-log-shipping.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hello @viniciuskoberwc! Thanks for submitting this issue. I'm currently looking into this.

**Comment by VanMSFT** [comment]
Hi @viniciuskoberwc! Thanks for your patience. I confirmed with our Product Group that there's currently no issues with log shipping from Windows to Linux with SQL Server. If our documentation is not clear on the steps, here are 3rd party examples:

https://www.sqlservercentral.com/articles/logshipping-to-sql-server-on-linux

I hope that helps!
