### ISSUE TITLE
Data migration Assistant missing

### ISSUE THREAD

**Issue by ErikEJ** [MicrosoftDocs/sql-docs#4047]
Why is Data migration assistant not included??

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 8af0672c-3e79-244d-4d09-5e7fb857345d
* Version Independent ID: f4b35a5c-1e55-d7e6-63be-b40dbc421039
* Content: [SQL tools overview - SQL Server](https://docs.microsoft.com/da-dk/sql/tools/overview-sql-tools?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/overview-sql-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/overview-sql-tools.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@ErikEJ  Thank  you for the feedback.

Assigning this to the author for further review.

In the meantime, please refer to the [Data Migration Assistant overview](https://docs.microsoft.com/sql/dma/dma-overview).

**Comment by markingmyname** [comment]
@ErikEJ 

Thank you for bringing this to our attention. The overview article will be updated with the data migration tool by the end of the week.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
