### ISSUE TITLE
glibc 2.18

### ISSUE THREAD

**Issue by gbjbaanb** [MicrosoftDocs/sql-docs#4048]
The page says "You must have a RHEL 7.3, 7.4, 7.5, 7.6, or 8 machine" (well, I have CentOS so no real difference) but the SQL Server installation requires glibc 2.18, and CentOS comes with 2.17 with no option to update it (as RHEL doesn't change glibc within major versions).

The SQL Server versions retrieved from the link was  mssql-server-15.0.4003.23-3.x86_64

The error reported is:

/opt/mssql/bin/sqlservr: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /opt/mssql/bin/../lib/libc++abi.so.1)
Initial setup of Microsoft SQL Server failed. Please consult the ERRORLOG

**Comment by gbjbaanb** [comment]
My fault - I grabbed the original repo using the curl link in the article to get the mssql repo, which was for rhel 8. Changing the 8 to 7 and re-installing works.

**Comment by WilliamAntonRohm** [comment]
@gbjbaanb -- Andy, thank you for your feedback, resolution, and avatar.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
