### ISSUE TITLE
Incorrect page link

### ISSUE THREAD

**Issue by BrentOzar** [MicrosoftDocs/sql-docs#4049]
In the "SQL Server 2016 Database Engine" section on this page, the "See Database Engine" redirects back to this page itself: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/what-s-new-in-sql-server-2016-database-engine?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92039d2f-79be-5b42-a880-d2992ce8a151
* Version Independent ID: ef7c0d04-a65f-28e0-3935-3dac80fb13c2
* Content: [What's New in SQL Server 2016 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-2016?view=sql-server-ver15#sql-server-2016-analysis-services-ssas)
* Content Source: [docs/sql-server/what-s-new-in-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/what-s-new-in-sql-server-2016.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@BrentOzar -- Brent, thank you for your keen eye.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@BrentOzar -- Brent, thank you for bringing this to our attention.

@MikeRayMSFT -- Mike, I can't find a new target for this link.  Please advise.

See [Database Engine](../database-engine/configure-windows/what-s-new-in-sql-server-2016-database-engine.md).

**Comment by semcha** [comment]
@WilliamAntonRohm link doesn't work.

**Comment by semcha** [comment]
@MikeRayMSFT https://github.com/MicrosoftDocs/sql-docs/commit/e9d80a0befa48d06805bae8015779d3f6bd87711

**Comment by MikeRayMSFT** [comment]
We did a bit of re-organizing and this link is no longer necessary. 

Removing the redundant link.

Thanks @BrentOzar
