### ISSUE TITLE
There's no documentation about the <termination> flag

### ISSUE THREAD

**Issue by mrdenny** [MicrosoftDocs/sql-docs#4050]
The &lt;termination&gt; flag needs some documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e24f87c-7a50-8dbe-a818-c603c979c5e4
* Version Independent ID: 07401c95-1053-03ff-abc6-b6b18c5f3fef
* Content: [ALTER DATABASE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/alter-database-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-database-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@mrdenny  Thank you for the feedback.

Assigning this to the author for further review.

**Comment by CarlRabeler** [comment]
@mrdenny all of the SET options are documented in this article: https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options
