### ISSUE TITLE
STRING_SPLIT does not document that it doesn't handle CHAR(0)

### ISSUE THREAD

**Issue by slepmog** [MicrosoftDocs/sql-docs#4051]
`STRING_SPLIT` does not handle `CHAR(0)` as a delimiter.

E.g. `select count(*) from string_split ('1' + char(0) + '2' + char(0) + '3', char(0))` incorrectly returns 1, whereas `select count(*) from string_split ('1' + char(1) + '2' + char(1) + '3', char(1));` correctly returns 3.

It would appear this is due to `CHAR(0)` being invalid, which is documented in the [`CHARINDEX` function](https://docs.microsoft.com/en-us/sql/t-sql/functions/charindex-transact-sql?view=sql-server-ver15#remarks):

> 0x0000 (char(0)) is an undefined character in Windows collations and cannot be included in CHARINDEX.

There is no such remark in `STRING_SPLIT` documentation, so it makes it look like `CHAR(0)` is going to work there.

Please verify that not handling `CHAR(0)` is indeed the correct behaviour for `STRING_SPLIT`, and if so, please add the remark about `CHAR(0)` there as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77b3e27b-a3ee-da83-1d41-1fafd96228cb
* Version Independent ID: cc43ad4b-92ac-477f-a92d-1487c82ebe70
* Content: [STRING_SPLIT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/string-split-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/string-split-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/string-split-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@slepmog  Thank you for the feedback.

Assigning this to the author for further review.

**Comment by srutzky** [comment]
I would expect that most string functions do not handle U+0000 / `NCHAR(0)`. However, there is a very simple method to get any string function to recognize any code point: use a binary collation (one ending in `_BIN2`, not `_BIN`). For example:

```sql
SELECT COUNT(*) FROM STRING_SPLIT ('1' + CHAR(0) + '2' + CHAR(0) + '3',
                                   CHAR(0) COLLATE Latin1_General_100_BIN2);
-- 3


SELECT REPLACE('1' + CHAR(0) + '2' + CHAR(0) + '3',
               CHAR(0) COLLATE Latin1_General_100_CI_AS,
               '~');
-- 1

SELECT REPLACE('1' + CHAR(0) + '2' + CHAR(0) + '3',
               CHAR(0) COLLATE Latin1_General_100_BIN2,
               '~');
-- 1~2~3
```

However, even though using a binary collation allows `STRING_SPLIT` to work with U+0000, I would recommend against using that code point as it is the string terminator in many languages, and does not always work as expected:

```sql
SELECT '1' + CHAR(0) + '2' + CHAR(0) + '3' COLLATE Latin1_General_100_BIN2;
-- 1

PRINT '1' + CHAR(0) + '2' + CHAR(0) + '3' COLLATE Latin1_General_100_BIN2;
-- Shows "123" in "Messages", but if you copy/paste into query editor, only "1" gets pasted

SELECT '1' + CHAR(0) + '2' + CHAR(0) + '3' COLLATE SQL_Latin1_General_CP1_CI_AS;
-- 1

PRINT '1' + CHAR(0) + '2' + CHAR(0) + '3' COLLATE SQL_Latin1_General_CP1_CI_AS;
-- Shows "123" in "Messages", but if you copy/paste into query editor, only "1" gets pasted.
-- The U+0000 is still there, it just doesn't take up any space
```

I would recommend using U+001F (i.e. `NCHAR(0x1F)` or `NCHAR(31)`) for this purpose.

For more info on working with Collations, please visit: [Collations Info](https://Collations.Info/)

Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

**Comment by MikeRayMSFT** [comment]
Thank you for the submission. We're updating our documentation. 

CC: @pmasl
