### ISSUE TITLE
Removing permissions

### ISSUE THREAD

**Issue by stoycqs** [MicrosoftDocs/sql-docs#4052]
Please put the following in a red square:

If the target entity is not a database and the entity is being transferred to a new owner, all permissions on the target will be dropped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5946ab8c-cab3-ba01-90f7-86210517d518
* Version Independent ID: d346ffc0-29ff-8ffa-d9b5-ad0ea78af848
* Content: [ALTER AUTHORIZATION (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-authorization-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/alter-authorization-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-authorization-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
@stoycqs Thank you for the feedback.

Assigning this to the author for further review.

**Comment by VanMSFT** [comment]
Hi @stoycqs! Thanks for the style suggestion of our docs. We do appreciate the input. However, we will leave the style of the document as is right now, and look to re-vamp the doc at a later date. Thanks again!
