### ISSUE TITLE
Information about python version

### ISSUE THREAD

**Issue by nishant-udgaonkar** [MicrosoftDocs/sql-docs#4053]
I would be helpful if the version of Python assumed is mentioned, since `str` is bytes in Python 2 but unicode in Python 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ea22367-9924-edb3-c65a-66a1cb4181fa
* Version Independent ID: cef2a17a-d363-3042-e585-4c9184637eb4
* Content: [Convert Python and SQL data types - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/python/python-libraries-and-data-types?view=sql-server-ver15#feedback)
* Content Source: [docs/advanced-analytics/python/python-libraries-and-data-types.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/python/python-libraries-and-data-types.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by msebolt** [comment]
@nishant-udgaonkar Thank you for the feedback.

Assigning this to the author for further review.

**Comment by dphansen** [comment]
@nishant-udgaonkar Thank you for the feedback. I will look into it and get back to you.

**Comment by dphansen** [comment]
@nishant-udgaonkar We will add this information to the documentation. Will let you know once it has been added.

**Comment by dphansen** [comment]
@nishant-udgaonkar I have updated the [What is SQL Server Machine Learning Services (Python and R)?](https://docs.microsoft.com/en-us/sql/advanced-analytics/what-is-sql-server-machine-learning?view=sql-server-ver15#versions) article to include the Python and R version information in our private repo. The update will be published next week. 

Thank you again for your valuable feedback and have a great weekend!
