### ISSUE TITLE
Syntax clarification

### ISSUE THREAD

**Issue by LeonSweden** [MicrosoftDocs/sql-docs#4054]
It would be good if syntax was more clearer like:
expression1 &= expression2

and simple example like:
DECLARE @HasBeenDelivered int = 8;
DECLARE @DeliveryStatus int = 1;

-- check if delivered
SELECT @DeliveryStatus &= @HasBeenDelivered

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5601c74-4ee4-bc90-c633-e970862bca76
* Version Independent ID: ee27f2c8-ff35-cc03-ce88-0f87a4409ce7
* Content: [&= (Bitwise AND Assignment) (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/bitwise-and-equals-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/language-elements/bitwise-and-equals-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/bitwise-and-equals-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@LeonSweden Thank you for the feedback and apologies for the delay.

Adding an example to this means adding examples to each bitwise operation and will take some time depending on the priority.

Assigning this to the author for further review and consideration.

**Comment by rothja** [comment]
@LeonSweden Thank you for the suggestion. I will look at your idea and the article more closely and get back to you.

**Comment by rothja** [comment]
@LeonSweden Sorry for the long delay on getting back to you on this one. I like your idea of adding more examples, but I think for now that the pointer in the article back to the [& (Bitwise AND) (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/bitwise-and-transact-sql?view=sql-server-ver15) page provides examples of bitwise& that will help make the &= clear enough. Based on documentation priorities and feedback, we'll consider additional examples for the future. Thanks, again, for your feedback. Let me know if you have any other comments or questions about this.
