### ISSUE TITLE
Version 18.4 crashes when open a diagram

### ISSUE THREAD

**Issue by wgutierrezr** [MicrosoftDocs/sql-docs#4055]
I created a diagram with my version 18.4. I turned off my computer and when trying to open the diagram it crashes.

**Comment by msebolt** [comment]
@wgutierrezr Thank you for the feedback.

Please refer to [this post](https://feedback.azure.com/forums/908035-sql-server/suggestions/38712874-fix-ssms-open-diagram-crash) or start a new thread in the [SQL Server feedback](https://feedback.azure.com/forums/908035-sql-server) for product team involvement.

**Comment by msebolt** [comment]
Closing issue now.
