### ISSUE TITLE
Please specify that select statements are not allowed in Azure DW UDF

### ISSUE THREAD

**Issue by sgiovinetti** [MicrosoftDocs/sql-docs#4056]
There no mention in the doc that select statements are not allowed in Azure DW UDF.
If they are you have an issue because I'm not able to create an UDF that contains SELECT statements even doing DECLARE @var [vartype] = SELECT()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae4c2020-39b8-ac93-1780-211b289125a0
* Version Independent ID: 1fa51178-1b68-106e-ae23-74ee4665144e
* Content: [CREATE FUNCTION (SQL Data Warehouse) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-function-sql-data-warehouse?view=aps-pdw-2016-au7)
* Content Source: [docs/t-sql/statements/create-function-sql-data-warehouse.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-function-sql-data-warehouse.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@sgiovinetti Thank you for the feedback.

Assigning this to the author for further review.

**Comment by CarlRabeler** [comment]
@msebolt please assign to @julieMSFT

**Comment by cawrites** [comment]
@sgiovinetti you are correct this is currently not a supported feature of Azure DW. It is a feature of SQL Server 2019 as noted in  https://docs.microsoft.com/sql/relational-databases/user-defined-functions/scalar-udf-inlining?view=sql-server-ver15 Keep in mind this is not applicable for Azure DW. Depending on what task you are trying to perform there may be a workaround (i.e views) but documentation is correct in not stating that this is a function of Azure DW. Please don't hesitate to contact us again regarding any questions you may have about the documentation.

**Comment by cawrites** [comment]
#please-close
