### ISSUE TITLE
What about available drives?

### ISSUE THREAD

**Issue by jelutz77** [MicrosoftDocs/sql-docs#4058]
This page does not even mention which drives may or not be available for cluster instances. I'm trying to figure out why my drive is not available to choose for backup!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3c56a92-e7d8-5763-d187-9e611ad2f35c
* Version Independent ID: 5982d698-75cc-e7f8-9112-1c0ec1e568de
* Content: [Specify disk or tape backup destination - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/specify-a-disk-or-tape-as-a-backup-destination-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/backup-restore/specify-a-disk-or-tape-as-a-backup-destination-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/specify-a-disk-or-tape-as-a-backup-destination-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@jelutz77 Thank you for the feedback.

Assigning this to the author for further review.

A similar issue was raised earlier in https://github.com/MicrosoftDocs/azure-docs/issues/46970.

**Comment by MashaMSFT** [comment]
Hi @jelutz77 , thanks for contacting Microsoft! Would you mind clarifying what you're doing when you can't see the drive? Are you just taking a backup using the GUI, or are you using T-SQL, or are you specifying a default back up drive?

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @jelutz77 , it's been some time since we've heard from you and I wanted to follow up to see if you still need assistance?

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @jelutz77 , since we haven't heard from you, we're going to assume that your issue has been resolved, and close out this Git Issue.

However, please feel free to comment should you need anything further :)

Thanks!
Masha from the SQL Docs team
