### ISSUE TITLE
Available drives?

### ISSUE THREAD

**Issue by jelutz77** [MicrosoftDocs/sql-docs#4059]
Why can't I save to the drive that has space?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cf4d073-76da-d1ec-20e6-f52188c8e846
* Version Independent ID: 545d5a71-3ebe-42b6-bab5-d76a35711a77
* Content: [Define logical backup device - disk - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/define-a-logical-backup-device-for-a-disk-file-sql-server?view=sql-server-ver15#Restrictions)
* Content Source: [docs/relational-databases/backup-restore/define-a-logical-backup-device-for-a-disk-file-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/define-a-logical-backup-device-for-a-disk-file-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@jelutz77 Thank you for the feedback.

This issue is being addressed in https://github.com/MicrosoftDocs/sql-docs/issues/4058.

Please refer there for further details on the resolution status.
