### ISSUE TITLE
Does not apply to Azure Synapse Analytics (SQL DW) 

### ISSUE THREAD

**Issue by ESTOCKY** [MicrosoftDocs/sql-docs#4060]
Does not apply to Azure Synapse Analytics (SQL DW) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfe9cad3-2e7d-a426-43ff-1347937dc291
* Version Independent ID: 6b04557f-6331-609e-5e80-6b3663495bd7
* Content: [View the Dependencies of a Stored Procedure - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/view-the-dependencies-of-a-stored-procedure?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/stored-procedures/view-the-dependencies-of-a-stored-procedure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/stored-procedures/view-the-dependencies-of-a-stored-procedure.md)
* Product: **sql**
* Technology: **stored-procedures**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@ESTOCKY Thank you for the feedback.

Assigning this to the author for review.

**Comment by stevestein** [comment]
@ESTOCKY - thanks for raising this issue.

The article has been updated and the applies to no longer applies to DW. 

#please-close
