### ISSUE TITLE
How to store audit information in Extended Log file (.XEL) in Azure VM SQL Server on hourly basis.

### ISSUE THREAD

**Issue by heresabya** [MicrosoftDocs/sql-docs#4063]
Here SQL Server instance installed in Azure VM . (So its not a Managed Instance / Azure SQL Database ---Its most like a on premise )

I have enabled the Auditing using Extended Event .Now auditing is stored in a .XEL file .

My requirement is like -

I want to move auditing information in some azure blob location /event hub (as a json) . Every one hour one job will be invoked and take last hours data and push it to blob / event hub (i have the conversion login from xel to json). So in a day there should be total 24 files containing 24 hours audit information and the job will run 24 times in a day to transfer the data to the storage location.

As per this document auditing will keep on growing untill max size reached .Then there will be a new file created once there is max size reached. 

My question is it possiblle to move to a new XEL file every one hour after .
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e18242cc-01df-27ba-a2cc-0f73e20c27d0
* Version Independent ID: af3f329d-8374-9093-ac64-75ad95aa2b57
* Content: [Quickstart: Extended events in SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/extended-events/quick-start-extended-events-in-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/extended-events/quick-start-extended-events-in-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/extended-events/quick-start-extended-events-in-sql-server.md)
* Product: **sql**
* Technology: **xevents**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
Hello @heresabya , I do not have the time to put together and test a working example, but one strategy you might try is to - use PowerShell to manipulate the XEvent system, as part of your hourly batch run to grab all the XEL data.  Something like the following numbered steps each hourly run:

1. Copy the XEL contents to a blob, as you currently do.
2. PowerShell to stop the event. (Then maybe delete the XEL file?)
3. PowerShell to start the event.

---

Here are some webpage related to PowerShell with XEvents:

- `https://docs.microsoft.comsql/relational-databases/extended-events/use-the-powershell-provider-for-extended-events?view=sql-server-ver15`

- `https://docs.microsoft.comazure/sql-database/sql-database-xevent-code-event-file#phase-1-powershell-code-for-azure-storage-container`

- `https://www.youtube.com/watch?v=pWZZYOdTnWM`

- `https://www.powershellgallery.com/packages/SqlServer.XEvent/1.5`

---

I am now Closing this Issue #4063.

The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.

Thank you for submitting this Issue. We hope to hear from you again.

.

**Comment by heresabya** [comment]
Thanks for this ..@MightyPen
