### ISSUE TITLE
Configure firewall for SQL Server using PowerShell

### ISSUE THREAD

**Issue by Liturgist** [MicrosoftDocs/sql-docs#4064]
[Enter feedback here]
SQL Server installation refers to this page describing use of the `netsh` command.

Is this page available describing the use of PowerShell for setting SQL Server firewall requirements? If so, where?

The `netsh` command reports:
```
In future versions of Windows, Microsoft might remove the Netsh functionality
for TCP/IP.
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3bdfbfc-233e-77f1-7ce0-dd7f9df5899d
* Version Independent ID: 311358ab-78ca-6739-201d-13b05917e9da
* Content: [Configure Windows Firewall - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/configure-the-windows-firewall-to-allow-sql-server-access?view=sql-server-ver15)
* Content Source: [docs/sql-server/install/configure-the-windows-firewall-to-allow-sql-server-access.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/configure-the-windows-firewall-to-allow-sql-server-access.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @Liturgist , thanks for contacting Microsoft! Just to make sure I understand correctly -  you're looking for PowerShell scripts to open the firewall ports, is that correct? 

Thanks!
Masha from the SQL Docs team

**Comment by Liturgist** [comment]
Masha,

Yes. The SQL Server 2019 install process points to the document describing
the use of netsh.

It would be good if it pointed to a document about using PowerShell
commands; either instead or in addition to netsh.

I found information about using Azure PowerShell commands, but not for
locally installed SQL Server.

**Comment by MashaMSFT** [comment]
Hi @Liturgist , thanks for confirming! Is this what you're looking for?

https://docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=win10-ps

Thanks!
Masha from the SQL Docs team

**Comment by Liturgist** [comment]
Masha,

Thank you for sending a link to New-NetFirewallRule.

The SQL Server install should point to a page about configuring ports
with New-NetFirewallRule. It should be specific to the ports used by
SQL Server.

**Comment by MashaMSFT** [comment]
Hi @Liturgist , okay perfect, thanks for confirming that's what you were looking for :) I've created an internal work item ([1672151](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1672151)) to update this article and track this work. I'll close the Git Issue in the meantime but you'll be notified once the changes have been made. 

Thank you so much for helping improve the documentation!
Masha from the SQL Docs team
