### ISSUE TITLE
Table is unnecessarily indented

### ISSUE THREAD

**Issue by estensen** [MicrosoftDocs/sql-docs#4066]
The SQL in the first table in [Obtaining Initial Data](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/work-with-change-tracking-sql-server?view=sql-server-ver15#obtaining-initial-data) could be un-indented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b26df5c-92a8-91e4-3fd1-e90d28157778
* Version Independent ID: ee0fa626-9318-7cf6-e27d-66d512fc2ee3
* Content: [Work with Change Tracking - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/work-with-change-tracking-sql-server?view=sql-server-ver15#obtaining-initial-data)
* Content Source: [docs/relational-databases/track-changes/work-with-change-tracking-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/work-with-change-tracking-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@estensen  Thank you for the feedback and please consider [becoming a contributor](https://docs.microsoft.com/en-us/contribute/).

The documentation has been updated and is pending review.
