### ISSUE TITLE
how and which tool can i need for output a scatterplot 

### ISSUE THREAD

**Issue by dqaudithillstone** [MicrosoftDocs/sql-docs#4068]
[ If your code generates visual output like a scatterplot or histogram, you need a tool or end-user application that can render the image

which  tool  it means ,how to do ? 
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6825b235-0949-0488-d8b2-3af7f071d462
* Version Independent ID: faf4b2bd-ce94-b9d0-98d7-12c84e09e998
* Content: [Quickstart: Train a model in Python - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/tutorials/quickstart-python-train-score-model?view=sql-server-2017)
* Content Source: [docs/advanced-analytics/tutorials/quickstart-python-train-score-model.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/tutorials/quickstart-python-train-score-model.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by dphansen** [comment]
@dqaudithillstone Thank you for your feedback. We are looking into it and will get back to you.

**Comment by garyericson** [comment]
@dqaudithillstone - This comment in the article is just clarifying that a SQL stored procedure is not able to display visual output. So if you have Python code that includes statements to generate visual output, those statements will not be usable if you embed that code in a stored procedure. If you need the visual output, you will need to find a way to generate it outside of the stored procedure, through separate Python code or maybe a standalone application. There are many ways to do this depending on the data and how you want to view it. You could try a Google search for data visualization tools if you need some suggestions.

**Comment by garyericson** [comment]
#please-close

**Comment by garyericson** [comment]
Added some clarification to the article.  PR [13676](https://github.com/MicrosoftDocs/sql-docs-pr/pull/13676)

**Comment by garyericson** [comment]
#assign:garyericson

**Comment by garyericson** [comment]
#assign:garyericson

**Comment by garyericson** [comment]
#assign:garyericson
