### ISSUE TITLE
Incomplete examples

### ISSUE THREAD

**Issue by estensen** [MicrosoftDocs/sql-docs#4071]
Running the example to get initial data I get the error `Must declare the scalar variable "@synchronization_version".`

Not being very familiar with SQL it took me some time to figure out that I have to declare the var first: `declare @synchronization_version bigint;`

You also have to declare `@last_synchronization_version` before the third example when you join tables.

I think examples should be self-contained and require little before-hand knowledge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b26df5c-92a8-91e4-3fd1-e90d28157778
* Version Independent ID: ee0fa626-9318-7cf6-e27d-66d512fc2ee3
* Content: [Work with Change Tracking - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/work-with-change-tracking-sql-server?view=sql-server-ver15#obtaining-initial-data)
* Content Source: [docs/relational-databases/track-changes/work-with-change-tracking-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/work-with-change-tracking-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@estensen -- Håvard, thank you for your feedback and solutions.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@rothja -- Jason, please review the above-mentioned PR 13784.

**Comment by rothja** [comment]
@WilliamAntonRohm Looks great. Thank you!
