### ISSUE TITLE
Better code for: Delete ad-hoc queries

### ISSUE THREAD

**Issue by LeAnneJergensen** [MicrosoftDocs/sql-docs#4072]
The code in "Delete ad-hoc queries" is not really the best way to remove ad-hoc queries.  This is because what is in that code would actually delete queries that are procedures/triggers/functions if they only ran once during a 24 hour time period.  We have bunches of these because we have a nightly process as well as a month end process.  The following is the better way as it only targets those records that are NOT procedures/triggers/functions (object_id=0).  It also targets those queries that are system queries.  Last, it does it for all databases on an instance.  So you only have to have it run once on an instance and it takes care of all databases on it if they have query store turned on.

SET NOCOUNT ON
-- This purges adhoc and internal queries from the query store every 3 minutes so that the 
-- query store does not run out of space and remove queries we really need to track
DECLARE @command varchar(1000) 

SELECT @command = 'IF ''?'' NOT IN(''master'', ''model'', ''msdb'', ''tempdb'') BEGIN USE ? 
EXEC(''
DECLARE @id int
DECLARE adhoc_queries_cursor CURSOR
FOR
SELECT q.query_id
FROM sys.query_store_query_text AS qt
JOIN sys.query_store_query AS q
    ON q.query_text_id = qt.query_text_id
JOIN sys.query_store_plan AS p
    ON p.query_id = q.query_id
JOIN sys.query_store_runtime_stats AS rs
    ON rs.plan_id = p.plan_id
WHERE q.is_internal_query = 1 '   -- is it an internal query then we dont care to keep track of it
+ '   OR q.object_id = 0'  -- if it does not have a valid object_id then it is an adhoc query and we dont care about keeping track of it
+ ' GROUP BY q.query_id
HAVING MAX(rs.last_execution_time) &lt; DATEADD (minute, -5, GETUTCDATE()) '  -- if it has been more than 5 minutes since the adhoc query ran
+ ' ORDER BY q.query_id ;
OPEN adhoc_queries_cursor ;
FETCH NEXT FROM adhoc_queries_cursor INTO @id;
WHILE @@fetch_status = 0
    BEGIN
        EXEC sp_query_store_remove_query @id
        FETCH NEXT FROM adhoc_queries_cursor INTO @id
    END
CLOSE adhoc_queries_cursor ;
DEALLOCATE adhoc_queries_cursor;
'') END' ;

EXEC sp_MSforeachdb @command  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b587ab-50b8-eada-aa86-ba0c838c57ee
* Version Independent ID: f1fd2d52-b66f-4fbc-c54a-c688c4fd0f21
* Content: [Monitoring Performance By Using the Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@LeAnneJergensen -- LeAnne, thank you for your detailed feedback.

@julieMSFT -- Julie, please look into this issue #4072.

**Comment by CarlRabeler** [comment]
@LeAnneJergensen thanks for the most excellent query and explanation - updated doc. Please keep providing better, more real-world examples.
Cheers,
Carl
