### ISSUE TITLE
Very helpful!

### ISSUE THREAD

**Issue by pedro-bonilla** [MicrosoftDocs/sql-docs#4073]
Very helpful for some maintenance jobs!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a829c6f-c86c-403b-67ae-3bbfffa59f45
* Version Independent ID: 1a67ec64-9d25-93e6-b021-56103b4399c2
* Content: [sys.fn_hadr_is_primary_replica (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/sys-fn-hadr-is-primary-replica-transact-sql?view=sql-server-2016)
* Content Source: [docs/relational-databases/system-functions/sys-fn-hadr-is-primary-replica-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-functions/sys-fn-hadr-is-primary-replica-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@pedro-bonilla -- thank you Pedro for your positive feedback; it is much appreciated.

cc @MikeRayMSFT @MightyPen
