### ISSUE TITLE
How do I update a cell to the value 4-char string NULL or 6-char string 'NULL'?

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/sql-docs#4075]
The documentation for the Results editor does describe how to update a cell to `NULL`: by simply entering `NULL` literally. However, it doesn’t specify how to set a stringish column to the literal value `'NULL'` (i.e., the four character string with characters capital N, capital U, capital L, and capital L, respsectively) or `'''NULL'''` (i.e., the six character string with characters single quote, capital N, capital U, capital L, capital L, and single quote, respectively).

So I am left with the question: how do I do I set the value to this string value with the Results pane editor? The documentation should be clear on this.

I can figure out how to set the cell value to the four-character string literal `'NULL'`. To do so, simply [write `'NULL'` literally](https://stackoverflow.com/a/23776487).

I cannot figure out how to set the value to the 6 character string literal `'''NULL'''`. I [asked on SO](https://stackoverflow.com/q/60047517) and have yet to receive a satisfactory answer. Perhaps it’s impossible. If so, the documentation should be updated to clarify that.

It also would be great if the documentation could explain how to interpret “NULL” in the results pane. Does it mean the 4-character string, the absence of a value, or something else? Or how about “'NULL'”?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143cac09-f6f2-5c37-1209-165bf05b7747
* Version Independent ID: 11b8de0b-5ddd-9e3f-a083-f1eca0cd31a9
* Content: [Edit Rows in the Results Pane - Visual Database Tools](https://docs.microsoft.com/en-us/sql/ssms/visual-db-tools/edit-rows-in-the-results-pane-visual-database-tools?view=sql-server-ver15#to-edit-data-in-the-results-pane)
* Content Source: [docs/ssms/visual-db-tools/edit-rows-in-the-results-pane-visual-database-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/visual-db-tools/edit-rows-in-the-results-pane-visual-database-tools.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@binki -- Nathan, thank you for your detailed feedback.

@markingmyname -- Mark, please look into this issue #4075.

**Comment by markingmyname** [comment]
@binki 

Please excuse the delayed response.

Thank you for your feedback! We will investigate and get back to you with the relevant info.

However, please add your experience in [UserVoice](https://feedback.azure.com/forums/908035-sql-server) to find if you see more people experience the same situation.

**Comment by markingmyname** [comment]
@binki 

What version of SSMS are you using because it works in version 18.4 (newest)?

Please let me know if this works with that version for you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by binki** [comment]
@markingmyname
> @binki
> 
> What version of SSMS are you using because it works in version 18.4 (newest)?

18.4. I find it impossible to enter the 6-character literal `'NULL'` through the Results pane. I don’t see how it’s “working”.

> You need to enter 'NULL' (i.e. NULL enclosed in single quotes)
> 
> It is not possible to enter the string literal 'NULL'.

@markingmyname Where is this behavior documented? Shouldn’t it be documented?
