### ISSUE TITLE
DecryptByPassphrase Does not work when database is restored to another server

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#4079]
Please update documentation to address this common scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc9c48d3-9c69-6897-c547-d0e7b4a76126
* Version Independent ID: cb28d268-9d47-c049-229f-23591dc69c1b
* Content: [DECRYPTBYPASSPHRASE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/decryptbypassphrase-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/decryptbypassphrase-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/decryptbypassphrase-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by rrg92** [comment]
Which the SQL version (complete build number) used to test?

**Comment by PrometheusRising1** [comment]
15.0.4003.23

**Comment by rrg92** [comment]
Testing on same Version!

I build two Virtual Machines on Azures, each one with SQL Server 2019 15.0.4003.23 runing on Windows Server 2019 1809 17763.973

On first VM, I generated a test encrypted data:
![image](https://user-images.githubusercontent.com/16887793/74052264-5cebf880-49b8-11ea-870b-c63c1268c786.png)


Then, on second VM, I restored the encrypted database and decrypt the data:
![image](https://user-images.githubusercontent.com/16887793/74052498-c409ad00-49b8-11ea-863d-2280e0011ee0.png)

The data was decrypted succesfully. The behavior documented is correct.

**Comment by rrg92** [comment]
@PrometheusRising1 did you see the tests above? can you provide additional details about to we check if doc is correct?

**Comment by rrg92** [comment]
I guess that issue can be closed. According with test above, the product is working like documentation describes.

**Comment by VanMSFT** [comment]
Thanks @rrg92! We really appreciate the help!
