### ISSUE TITLE
This article has an UNPIVOT example but the Table of Contents doesn't have it listed

### ISSUE THREAD

**Issue by GourdJ** [MicrosoftDocs/sql-docs#4080]
This article has an UNPIVOT example but the Table of Contents doesn't have it listed - only PIVOT examples are listed in the TOC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45eba8b0-0c31-d65b-f1ca-0ed260eb2f14
* Version Independent ID: fe2a79c1-6512-36f6-3118-cda7d18531de
* Content: [Using PIVOT and UNPIVOT - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/from-using-pivot-and-unpivot?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/queries/from-using-pivot-and-unpivot.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/from-using-pivot-and-unpivot.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@GourdJ -- thank you for your feedback.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@GourdJ -- Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
