### ISSUE TITLE
Some page headers are shown as UIElement List

### ISSUE THREAD

**Issue by egoryainova-spr** [MicrosoftDocs/sql-docs#4084]
I noticed that some article headers on this page are displaying incorrectly and showing UIElement List word instead. In addition to that, the entire page name is "Manage Partition Wizard F1 Help" which seems like a blend of name "Manage Partition Wizard" with additional metadata information. Hope this can be fixed in the future versions. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49c82a7-f857-b2fc-4074-bd8b72af0c2b
* Version Independent ID: 788de8e1-4816-6994-5a82-9aa22ba6219c
* Content: [Manage Partition Wizard F1 Help - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/partitions/manage-partition-wizard-f1-help?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/partitions/manage-partition-wizard-f1-help.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/partitions/manage-partition-wizard-f1-help.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@egoryainova-spr -- thank you for your feedback.

@julieMSFT -- please look into this issue #4084.

**Comment by julieMSFT** [comment]
@egoryainova-spr Hello, Thank you for bringing this to our attention. I have submitted the fix to the doc. You should see the changes tomorrow. I will go ahead and close this issue. If you need anything further you can still respond to this issue.
