### ISSUE TITLE
Is there a column that indicates Query 1, Query 2, Query 3 for an object

### ISSUE THREAD

**Issue by LeAnneJergensen** [MicrosoftDocs/sql-docs#4085]
The big difference I  found between the execution plan stored in Cached Queries vs Query Store is that for an object (procedure/trigger/function) that contains more than one query, the Cached Queries plan only has one execution plan for ALL queries with the queries in order specifying Query 1, Query 2, Query 3 etc.  Whereas, Query Store has a separate execution plan for each query in the object.  What I can't find is a column in any of the Query Store tables/views that tell me if the query the plan is for is Query 1, Query 2, Query 3 etc.  Am I just missing what column I should be pulling to get that information for the Query Store execution plan?  If it's not there, I would recommend to MS that it be added if at all possible as it would help greatly when your investigating an object execution plans that have lots of queries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b587ab-50b8-eada-aa86-ba0c838c57ee
* Version Independent ID: f1fd2d52-b66f-4fbc-c54a-c688c4fd0f21
* Content: [Monitoring Performance By Using the Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@LeAnneJergensen -- LeAnne, thank you for your questions.

@julieMSFT -- Julie, please look into this issue #4085.

**Comment by CarlRabeler** [comment]
@LeAnneJergensen I am investigating

**Comment by CarlRabeler** [comment]
Is the ask on how to correlate execution plans with queries and determine their execution order within a stored procedure, trigger, etc. ?

You can do this by joining with sys.query_store_query_text on query_text_id, where you will be able to see the actual query text.
In the stored procedure definition, you know in which order the queries are executed, so you can join the query texts with queries and then plans to deduce the order in which execution plans were executed.

**Comment by LeAnneJergensen** [comment]
Yes that is the ask, to know that the select query is the 1st query, the update is the 2nd query, the if exists(select) is the 3rd query, etc, without having to look at the proc code and one by one figure out which queries are executed how many times.  Or even more important, that the query in a particular if clause is not in query store, so now I know that it is not ever executed.  Here is the code we are using now for a procedure to see all of the queries that execute and the number of times it executes.  From it though, and we just used this to help us debug a proc we are changing, it does not indicate which query comes in what order in the procedure.  

DECLARE @ObjectName VARCHAR(128) = '<objectname>' -- DO NOT INCLUDE SCHEMA NAME

 
SELECT    
       p.query_id
      ,s.name as schemaname
      ,ob.name AS ObjectName
      -- Query store uses GMT for its datetimes.  So subtract 7 hours from it so it is in AZT time
      ,DATEADD(HOUR,-7,MAX(COALESCE(rs.last_execution_time,p.last_execution_time))) AS LastExecutionCapturedDateTime
      ,ISNULL(sum(rs.count_executions), 0) as Counts -- if no record in the query store then set count to 0
      ,qt.query_sql_text 
  FROM sys.objects AS ob 
  JOIN sys.schemas AS S
    ON ob.schema_id = s.schema_id
  LEFT JOIN sys.query_store_query AS Qry
    ON ob.object_id = Qry.object_id
  LEFT JOIN sys.query_store_query_text AS qt  
    ON qry.query_text_id = qt.query_text_id  
  LEFT JOIN sys.query_store_plan AS p   
    ON p.query_id = qry.query_id  
  LEFT JOIN sys.query_store_runtime_stats AS rs   
    ON rs.plan_id = p.plan_id  
  where p.last_execution_time IS NOT null
    AND ob.name = @ObjectName
GROUP BY s.name, ob.name,p.query_id,qt.query_sql_text
ORDER BY p.query_id, DATEADD(HOUR,-7,MAX(COALESCE(rs.last_execution_time,p.last_execution_time)))

So based on your second comment, it sounds like we did the only thing possible, to basically, manually figure out which query is which by comparing the results of the above query to the code in the procedure.    Is that correct, or is there something else you are alluding to that is possible?

**Comment by CarlRabeler** [comment]
Yes, @LeAnneJergensen, you have done the only thing possible - namely to manually review the stored procedure to know the order of execution - and then manually define the join the query text with queries

**Comment by LeAnneJergensen** [comment]
Thanks for checking.  Good to know I had it right.

**Comment by CarlRabeler** [comment]
you are most welcome
