### ISSUE TITLE
How to change from Windows only to SQL Server and Windows authentication mode

### ISSUE THREAD

**Issue by bdcoder2** [MicrosoftDocs/sql-docs#4087]
The article shows how to change the authentication mode to Windows only - but what T-SQL command and magic value is used to change the authentication mode to "SQL Server and Windows authentication mode".

All combinations should be documented.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9b632d-7e6d-1434-cc6b-9aa77d37f41a
* Version Independent ID: 3689727c-e685-1503-fd9e-365aa15c33fa
* Content: [Change Server Authentication Mode - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/change-server-authentication-mode?view=sql-server-ver15#TsqlProcedure)
* Content Source: [docs/database-engine/configure-windows/change-server-authentication-mode.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/change-server-authentication-mode.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@bdcoder2 -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue #4087.

**Comment by bdcoder2** [comment]
Suggested rewrite:

- LoginMode: 1  (Windows authentication only)
- LoginMode: 2  (SQL Server and Windows Authentication)

**To set mode to “Windows Authentication only”:**

```
USE [master]
GO
EXEC xp_instance_regwrite N'HKEY_LOCAL_MACHINE', 
     N'Software\Microsoft\MSSQLServer\MSSQLServer', N'LoginMode', REG_DWORD, 1
GO
```

**To set mode to “SQL Server and Windows Authentication mode” (mixed mode):**

```
USE [master]
GO
EXEC xp_instance_regwrite N'HKEY_LOCAL_MACHINE', 
     N'Software\Microsoft\MSSQLServer\MSSQLServer', N'LoginMode', REG_DWORD, 2
GO

```
**NOTE: Restart the SQL Server after the above commands are executed.**

Other suggestion:

- Include a list of the various registry paths for the various flavors of SQL (ie: SQLExpress)
- Mention the above can be accomplished using RegEdit as well (in case access to SMSS is not available)

**Comment by rrg92** [comment]
I guess that original doc dont speicfy T-SQL because it uses undocumented xp_regwrite* procedures.

Maybe, Product Team want not encourage users to use this procedure due to side effects that it can cause on environment.

I dont know why Microsoft not use the "sys.configurations" to store it. This would can a better place and all interfaces to change it already documented.

**Comment by MikeRayMSFT** [comment]
@bdcoder2  thanks for the submission, and writing up a way to accomplish the task. I'm reviewing your suggestion with engineering.

Your call out helps me identify that this doc could be improved to clarify what you can  & can't do with T-SQL. 

After I review, we'll update.

Thanks!
Mike

**Comment by MikeRayMSFT** [comment]
@bdcoder2 thanks for the submission. 

We've reviewed the article and are updating it to clarify what the different steps do. We are not explicitly describing how to use T-SQL XPs to change the authentication mode beyond what it currently describes. The manual steps described manually modify the registry. This task is very high-risk and not advised. 

If you would like to submit a feature request to enable a programmatic way to change this setting, consider submitting feedback at https://aka.ms/sqlfeedback.
