### ISSUE TITLE
C. Producing a moving average and cumulative total

### ISSUE THREAD

**Issue by joselameira** [MicrosoftDocs/sql-docs#4089]
Applies to: SQL Server 2012 (11.x) and later.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81477bb5-e2f4-dd0b-b025-19a30041622e
* Version Independent ID: 482fcc64-0e86-3cac-7c5a-1a312d4ba088
* Content: [OVER Clause (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-over-clause-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/queries/select-over-clause-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/select-over-clause-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@joselameira -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task or concern.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
