### ISSUE TITLE
DacFramework.msi for Windows 2019

### ISSUE THREAD

**Issue by Bliyaal** [MicrosoftDocs/sql-docs#4091]
I'm trying to install SqlPackage on self hosted Azure DevOps agent and since Azure creates all new databases with compatibility level at 150 I also need the tools for it. The link here seems to use a Windows Server 2012 version. When installing it on my agent it doesn't create a C:\Program Files (x86)\Microsoft SQL Server\150 directory.

Is the link out of date or am I doing something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3df6af-9ac8-bc57-93dc-29ff713c1d3b
* Version Independent ID: 7624e2cc-7aa9-40dd-4015-3371ea2ea0a2
* Content: [Download and install sqlpackage - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/sqlpackage-download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage-download.md)
* Product: **sql**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by WilliamAntonRohm** [comment]
@Bliyaal -- Michel, thank you for your feedback.  I found [this link](https://www.microsoft.com/en-us/download/details.aspx?id=42293) to a 2014 version of DacFramework.msi.  That version creates a `C:\Program Files\Microsoft SQL Server\150` folder but that folder does not in turn have a `\DAC` subfolder.

@pensivebrian -- Brian, please look into these instructions.

**Comment by pensivebrian** [comment]
We stopped shipping the x86 version of sqlpackage. The install should place x64 version of sqlpackage in the `C:\Program Files\Microsoft SQL Server\150\DAC\bin` folder.

**Comment by Bliyaal** [comment]
@pensivebrian -- You're right! It was there all allong. Stupid me. Thanks!
