### ISSUE TITLE
Error in Arguments section

### ISSUE THREAD

**Issue by wyattroberts** [MicrosoftDocs/sql-docs#4093]
In the Arguments section, you have "other_geometry Is another geometry instance in addition to the instance on which *STSymDistance() *is being invoked." That should be STSymDifference().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00236ad3-0321-19b3-c975-ca4ab3326e29
* Version Independent ID: 37e3bcd4-7ed7-88ec-42d2-acc87a4ec562
* Content: [STSymDifference (geometry Data Type) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geometry/stsymdifference-geometry-data-type?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/spatial-geometry/stsymdifference-geometry-data-type.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/spatial-geometry/stsymdifference-geometry-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by MladjoA** [comment]
Thanks for reporting @wyattroberts. PR with the fix is on its way.

**Comment by cawrites** [comment]
@wyattroberts I reviewed the content and the sentence is as you stated without correction:

## Arguments  
 *other_geometry*  
 Is another **geometry** instance in addition to the instance on which `STSymDifference()` is being invoked.       STSymDifference() is what is shown

**Comment by cawrites** [comment]
@wyattroberts thank you for contacting Microsoft if you have any other content-related questions please don't hesitate to contact Microsoft again.

**Comment by cawrites** [comment]
#please-close
