### ISSUE TITLE
General Feedback: Version in first paragraph does not change when version drop down is changed

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#4094]
I have noticed this on multiple pages now: when the version is selected in the drop down over the navigation pane, the first paragraph still states information concerning SQL Server 2019:
"This topic describes how to configure SQL Server Agent to use Database Mail to send notification and alerts in SQL Server 2019 (15.x) by using SQL Server Management Studio."

This is not affected unless one goes all the way back to SQL Server 2014 or earlier as the version in the drop down.  This can confuse people new to the SQL Server or seeing this for the first time, as it might lead them to think the article is only relevant for 2019, and to not trust the documentation for 2017 and 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e146ff3-268e-5025-e645-b477d33ac8eb
* Version Independent ID: 5b5d6ac5-e0ed-d7d9-c33e-d55a3fcb57ec
* Content: [Configure SQL Server Agent Mail to Use Database Mail - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/database-mail/configure-sql-server-agent-mail-to-use-database-mail?view=sql-server-2016#feedback)
* Content Source: [docs/relational-databases/database-mail/configure-sql-server-agent-mail-to-use-database-mail.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/database-mail/configure-sql-server-agent-mail-to-use-database-mail.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@PrometheusRising1 -- thank you for your feedback. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback). 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

@MightyPen fyi
