### ISSUE TITLE
tier parameter is case sensitive for 'Standard' tier

### ISSUE THREAD

**Issue by LaurenceWelch** [MicrosoftDocs/sql-docs#4100]
Not a huge deal, but should 'standard' always be listed as 'Standard' in this doc?(and perhaps 'basic' and 'premium' as well) I started using the EFCore function HasServiceTier('Standard') to ensure my db doesn't default to VCores. At first I tried using 'standard' and it defaulted to VCores. Once I used 'Standard', it worked like a charm. This doc lists it as 'standard' in some places and 'Standard' in others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e24f87c-7a50-8dbe-a818-c603c979c5e4
* Version Independent ID: 07401c95-1053-03ff-abc6-b6b18c5f3fef
* Content: [ALTER DATABASE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql?view=azuresqldb-current#feedback)
* Content Source: [docs/t-sql/statements/alter-database-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-database-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@LaurenceWelch -- Laurence, thank you for your feedback.

@CarlRabeler -- Carl, please look into this issue 4100.

**Comment by CarlRabeler** [comment]
@LaurenceWelch thanks - PR pending to fix this today.
