### ISSUE TITLE
Is the default server-level collation specific to the locale settings on that machine?

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/sql-docs#4103]
> The server collation is specified during SQL Server installation. Default server-level collation is SQL_Latin1_General_CP1_CI_AS.

However, as per https://www.sqlservercentral.com/forums/topic/default-server-collation-for-sql-does-it-depend-on-the-os-version-standard-vs-enterprise it appears the actual default collation on install depends on the locale on the machine that MSSQL is being installed. **I know the above pertains to SQL 2008 and is probably out of date**, but I just wanted to confirm that the behaviour documented is the actual behaviour. If it is, can a note please be added to update the text to something like:

> The server collation is specified during SQL Server installation. Default server-level collation is SQL_Latin1_General_CP1_CI_AS, **regardless of the server's locale setting**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca70403-237f-0160-7d1f-5817e40b5d25
* Version Independent ID: 9993116a-bcec-e054-1cbe-82c3ad603ef6
* Content: [Set or Change the Server Collation - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-server-collation?view=sql-server-ver15)
* Content Source: [docs/relational-databases/collations/set-or-change-the-server-collation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/set-or-change-the-server-collation.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@IanKemp -- Ian, thank you for your feedback. 

@stevestein -- Steve, please look into this issue #4103.

**Comment by srutzky** [comment]
Hello @IanKemp  (and @stevestein ): I just submitted PR #4747 to address this issue (as well as Issue #2524 ). Essentially, yes, the default (which can be overridden) is (or, at least, absolutely should be) based on the OS locale. I clarified that the `SQL_Latin1_General_CP1_CI_AS` collation is the default (albeit a [horrible default that needs to be changed](https://feedback.azure.com/forums/908035-sql-server/suggestions/32889958-make-latin1-general-100-ci-as-the-default-collat)!) when the OS locale is set to US English (en-US). I also included a link to the list of OS locales-to-collation mappings: https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support#Server-level-collations .

Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

**Comment by stevestein** [comment]
@IanKemp - thanks for raising this issue.
@srutzky - thanks for responding and updating the related docs!

**Comment by stevestein** [comment]
PR #4747 should get merged and go live later today or tomorrow.
#please-close
