### ISSUE TITLE
wrong value in example - max degree of parallelism option

### ISSUE THREAD

**Issue by SO-MECA** [MicrosoftDocs/sql-docs#4105]
The example show the wrong value.
The text says:
"... This example shows how to use sp_configure to configure the max degree of parallelism option to 8."

The example code shows:
"...  
EXEC sp_configure 'max degree of parallelism', 16;  
..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e3528c6-06d5-aaef-58ac-a4426ca2a433
* Version Independent ID: 6264cc46-28bb-c4d6-067d-67c9c417f4b1
* Content: [Configure the max degree of parallelism Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-max-degree-of-parallelism-server-configuration-option?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/configure-windows/configure-the-max-degree-of-parallelism-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-max-degree-of-parallelism-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@SO-MECA -- MECA, thank you for catching this.  I am looking into the document.

**Comment by WilliamAntonRohm** [comment]
@SO-MECA -- Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
