### ISSUE TITLE
Reference Data Services in DQS

### ISSUE THREAD

**Issue by bthakks** [MicrosoftDocs/sql-docs#4110]
The document still referring to creating the account on the site that cannot be reachable. Also there is no example around how it can be integrated with Azure marketplace 

https://docs.microsoft.com/en-us/sql/data-quality-services/reference-data-services-in-dqs?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@bthakks -- thank you for your feedback.  Sorry for the delay in responding.  

@swinarko -- please look into this issue.

cc @rothja as a writer

**Comment by swinarko** [comment]
Sorry for our out-of-date doc, Azure Marketplace and RDS feature in DQS have been deprecated a while back, we'll add references to alternative products from our partners that support this feature soon.  #please-close
