### ISSUE TITLE
Unable to install msodbcsql17 on Ubuntu 14

### ISSUE THREAD

**Issue by jdavisp3** [MicrosoftDocs/sql-docs#4111]
Installing this package on Ubuntu 14 gives:

```
 msodbcsql17 : Depends: libc6 (>= 2.21) but 2.19-0ubuntu6.15 is to be installed
               Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.4 is to be installed
```

I don't believe that version of `libc6` is available.

**Comment by WilliamAntonRohm** [comment]
@jdavisp3 -- Dave, thank you for your feedback.  Do you have a particular docs.microsoft.com article in mind?

**Comment by jdavisp3** [comment]
Whoops, sorry, it is this one:

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@jdavisp3 -- Dave, thank you for clarifying.

@MightyPen -- Gene, please look into this issue #4111.

**Comment by rothja** [comment]
@jdavisp3 Apologies for the long-delayed response. In looking at the article you reference, I think the best person to investigate is @David-Engel. We should have routed this to him much sooner, and I sincerely apologize. Were you able to find a solution/work-around? Is this currently blocking you still?

@David-Engel can you please take a look at this reported problem? #reassign:David-Engel

**Comment by David-Engel** [comment]
@jdavisp3 This is more more of a support issue. Installation generally works fine for Ubuntu 14.04. I've only seen this error in the context of other errors. Can you post the rest of the context around your `apt-get` command? My first guess would be you have held broken packages or dependency conflicts on your local machine which need to be resolved.

**Comment by jdavisp3** [comment]
Well I fixed it by pinning the version to one just before the release that broke my install.

**Comment by jdavisp3** [comment]
Has there been another release since then that maybe fixed it?

**Comment by jdavisp3** [comment]
I can test later when I'm back at keyboard.

**Comment by David-Engel** [comment]
@jdavisp3 Update: We noticed an issue, too, and the 17.5.x packages will not install on 14.04. Pinning at 17.4.2 should work. We are going to pull the 17.5.x packages.

Thanks,
David

**Comment by jdavisp3** [comment]
@David-Engel gotcha, well glad to know it wasn't just me 😄 Thanks!

**Comment by David-Engel** [comment]
The 17.5 packages have been removed and this issue should be resolved.

Note: Ubuntu 14.04 Standard Support ended last year and there will be no new Microsoft ODBC Driver for SQL Server releases for that Ubuntu version. So 17.4.2 is the latest version it will ever have.

**Comment by David-Engel** [comment]
#please-close

**Comment by jdavisp3** [comment]
> The 17.5 packages have been removed and this issue should be resolved.
> 
> Note: Ubuntu 14.04 Standard Support ended last year and there will be no new Microsoft ODBC Driver for SQL Server releases for that Ubuntu version. So 17.4.2 is the latest version it will ever have.

Understood, thanks @David-Engel .
