### ISSUE TITLE
An Extra Paragraph to Elaborate on What Can/Can't be Done with SAS Tokens?

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#4112]
Not to bloat the article, but maybe give a couple of examples of what the SAS token can/can't do and some scenarios for use?  When people are reading up on Azure capabilities, they say you need a SAS token added to a database scoped credential to access the other Azure resources.  At the same time, you are stating here that there are limitations (i.e. with Polybase, which is supposed to act as a unifying layer for external resources).  These two things seem to contradict each other and probably merit more explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140d7c84-acc3-f722-99af-867be1f8752a
* Version Independent ID: 6bb40855-9644-1b18-3c4f-cec734cdc169
* Content: [CREATE DATABASE SCOPED CREDENTIAL (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-scoped-credential-transact-sql?redirectedfrom=MSDN&view=sql-server-2017)
* Content Source: [docs/t-sql/statements/create-database-scoped-credential-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-database-scoped-credential-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@PrometheusRising1 -- thank you for your feedback.

@VanMSFT -- please look into this issue #4112.

**Comment by VanMSFT** [comment]
Hello @PrometheusRising1! Thanks for the suggestions on our documentation! Unfortunately, we are not able to provide all the examples available. We do link to the [SAS article](https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview) for further reference, and provide some examples of using SAS and limitation on other pages (i.e. https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql). If there are any limitations, we will try to include them in the relevant pages. If you feel that a known issue is missing, please feel free to make future suggestions. We'd love your input.
