### ISSUE TITLE
Invalid object name 'sys.dm_xe_session_targets'.

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/sql-docs#4113]
This object does not exist for Azure SQL database.  Please advise on how to read the data from a trace without having to double click through SSMS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 923bd786-410a-0e1c-6519-4971035a9dbd
* Version Independent ID: 4142e15a-1b9e-f4ae-86eb-46871fb8aa72
* Content: [Targets for Extended Events in SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/extended-events/targets-for-extended-events-in-sql-server?view=azuresqldb-current#h2_target_ring_buffer)
* Content Source: [docs/relational-databases/extended-events/targets-for-extended-events-in-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/extended-events/targets-for-extended-events-in-sql-server.md)
* Product: **sql**
* Technology: **xevents**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by StingyJack** [comment]
This document should have the contents of https://docs.microsoft.com/en-us/azure/sql-database/sql-database-xevent-code-ring-buffer incorporated, as its more correct than this one.

**Comment by WilliamAntonRohm** [comment]
@StingyJack -- Andrew, thank you for your feedback.

@MightyPen -- Gene, please look into this issue #4113.

**Comment by rothja** [comment]
@StingyJack Andrew, I apologize for the delayed response. Thanks for your suggestion on what content should appear in the target page. I am reaching out to the product team to confirm the changes and updates that are needed. I'll keep this open while I explore. Thank you!

**Comment by rothja** [comment]
You're right that we should be more clear on what is supported in Azure SQL on this page, and I'm trying to get the exact changes needed. 

I found that the XEvent server-level views (e.g. sys.dm_xe_session_targets) are not visible on Azure SQL DB. They were replaced with database-level equivalent views (e.g. sys_dm_xe_session_targets became sys.dm_xe_database_session_targets). For Azure, we need to refer to the database-level views:

We have docs on the new Azure database-level views here:

- [https://docs.microsoft.com/en-us/azure/azure-sql/database/xevent-db-diff-from-svr#new-catalog-views](https://docs.microsoft.com/en-us/azure/azure-sql/database/xevent-db-diff-from-svr#new-catalog-views)
- [https://docs.microsoft.com/en-us/azure/azure-sql/database/xevent-db-diff-from-svr#new-dynamic-management-views-dmvs](https://docs.microsoft.com/en-us/azure/azure-sql/database/xevent-db-diff-from-svr#new-dynamic-management-views-dmvs)
- [https://docs.microsoft.com/en-us/azure/azure-sql/database/xevent-db-diff-from-svr#dmvs-common-to-both](https://docs.microsoft.com/en-us/azure/azure-sql/database/xevent-db-diff-from-svr#dmvs-common-to-both)

Let me know if you have any questions or if this helps. I'm going to close the issue, but I can still see any comments you make on the thread. Thank you!
