### ISSUE TITLE
upgrade SQL Eval with AlwaysOn AG to SQL Ent

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/sql-docs#4114]
article says "Upgrading from Evaluation (a free edition) to any of the paid editions is supported for stand-alone installations, but is not supported for clustered installations."

I guess "clustered installations" means SQL AlwaysOn FCI instances.

What about upgrade of a pair of SQL Eval instances configured with AlwaysOn AG ?
In this scenario, we have *standalone* SQL instances running on  Windows Server Failover **cluster** (WSFC) nodes.
I assume this scenario is not considered "clustered installation" and thus upgrade from SQL 2019 Eval to SQL 2019 Enterprise will be supported.
Am I correct?
Could you please add an explicit statement to the article clarifying this aspect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636765e0-c401-c659-aafd-8d85aaea5c78
* Version Independent ID: fce6d332-ea8c-cf44-51bb-4cebc2b3d305
* Content: [Supported Version and Edition Upgrades - SQL Server 2019 - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/supported-version-and-edition-upgrades-version-15?view=sql-server-ver15#-edition-upgrade)
* Content Source: [docs/database-engine/install-windows/supported-version-and-edition-upgrades-version-15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/supported-version-and-edition-upgrades-version-15.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @shivtorov , thank you so much for your feedback! A SQL Server instance in an AG, but not clustered, sounds like it should be fine to me, but let me confirm.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @shivtorov , thank you for your patience while I confirmed! Yes, it is possible to upgrade the edition from evaluation for a standalone instance that is installed to a Windows Failover Cluster and is used as a replica for an availability group. This instance is _not_ a failover cluster instance, and thus, this limitation does not apply. 

I hope that helps and please let us know if there is anything more we can assist you with?

Thanks!
Masha from the SQL Docs team

**Comment by shivtorov** [comment]
Hi @MashaMSFT 
Thank you for the confirmation. I did the upgrade a couple of days ago and it all went well.
It would be nice if you could update the article with the clarifications you provided here.

Thanks!
Misha from Generation-e Pty Ltd team

**Comment by MashaMSFT** [comment]
Hi @shivtorov , thanks for your feedback! I have made a change to the doc that should be live next week. 

I'll close out this Git Issue, but please feel free to reply should you need anything further.

Thanks again for helping improve our documentation and hope you have a great weekend!
Masha from the SQL Docs team
