### ISSUE TITLE
keytab secrets for sql server on docker container in linux

### ISSUE THREAD

**Issue by jovton** [MicrosoftDocs/sql-docs#4115]
hi. how would I manage SQL Server keytab secrets for an instance running in a docker container in Linux (Ubuntu 18.04)? SQL server is not currently installed as stand-alone (deb / apt). the documentation assumes that, and says nothing about docker containers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Use AD authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **dygray**

**Comment by jovton** [comment]
I found the documentation for docker data volumes for SQL Server: [Configure SQL Server container images on Docker](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-ver15#mount-a-host-directory-as-data-volume)

It may be helpful to link to this in the documentation for people who may want to know where to put their keytabs for sql running in docker containers. Thanks 😄

**Comment by WilliamAntonRohm** [comment]
@jovton -- thank you for your question and research.

@Dylan-MSFT -- please look into this issue #4115.

cc @MightyPen as a writer
