### ISSUE TITLE
ktpass and keytab file example

### ISSUE THREAD

**Issue by jovton** [MicrosoftDocs/sql-docs#4116]
hi. please tell people not to include the stars ( ** ) in the ktpass commands as per your example. thanks. this really tripped me up.  :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Use AD authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **dygray**

**Comment by WilliamAntonRohm** [comment]
@jovton -- thank you for your feedback.  I am looking into this document.
