### ISSUE TITLE
Please add note about truncation

### ISSUE THREAD

**Issue by tphillipvidea** [MicrosoftDocs/sql-docs#4121]
Please add to note in example C:  As a default Results to Text are truncated to 256 characters.  To change this setting select Tools -&gt; Options -&gt; Query Results -&gt; SQL Server -&gt; Results to Text and change "Maximum number of characters displayed in each column".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8471b5d7-c6c9-c158-c57e-341683a0fc36
* Version Independent ID: 50e18725-91d2-21b7-864e-8b6432ad342b
* Content: [STRING_AGG (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/string-agg-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/string-agg-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/string-agg-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@tphillipvidea -- Tom, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please look into this issue #4121.

**Comment by MikeRayMSFT** [comment]
@tphillipvidea - thank you for the submission. Will respond shortly.

**Comment by pmasl** [comment]
Addressed with PR 13823
