### ISSUE TITLE
Incorrect result set definition

### ISSUE THREAD

**Issue by TomLitt** [MicrosoftDocs/sql-docs#4126]
Hi,
I had some code putting the result set of sp_who into a temporary table, which started throwing a "string or binary data would be truncated" error on upgrade to SQL Server 2019.

The column definition now has the cmd column as nvarchar(26).

According the output of this statement, the other columns are correct:
SELECT * FROM sys.dm_exec_describe_first_result_set_for_object(object_id('sp_who'),DEFAULT)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f8b6bbc-cede-54e2-860d-3804f01893fe
* Version Independent ID: bca196ed-73de-99d6-6c8d-62239510e36d
* Content: [sp_who (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-who-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-who-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-who-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@TomLitt -- thank you for your feedback.

@VanMSFT -- please look into this issue #4126.

**Comment by VanMSFT** [comment]
Hi @TomLitt! Thanks for submitting this issue! The document has now been updated.
