### ISSUE TITLE
Sort Order on Non-Key columns in Index

### ISSUE THREAD

**Issue by vijaykvs** [MicrosoftDocs/sql-docs#4127]
Under "Index Sort Order Design Guidelines" section it was mentioned that SORT order for indexes can be created only on key columns. However, in the Adventure Works example provided, sort order was mentioned on "RejectedQty" which is not a key column in the table. Please check this and let me know if I am missing something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20a94499-0b07-2deb-46d6-102e6f1dedac
* Version Independent ID: 324ed645-ed52-6104-9ffd-2907ff315565
* Content: [SQL Server Index Architecture and Design Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-index-design-guide?view=sql-server-ver15#General_Design)
* Content Source: [docs/relational-databases/sql-server-index-design-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/sql-server-index-design-guide.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@vijaykvs -- thank you for your feedback.

@rothja -- please look into this issue #4127.

**Comment by rothja** [comment]
@vijaykvs Thank you for the question and so sorry for the delay. I am going to investigate this further to see if the documentation is wrong or outdated.

**Comment by CarlRabeler** [comment]
@vijaykvs I think what this example is trying to say is that the key column is one of the columns in the index, not in the underlying table. The example in the article (also below here) is placing the RejectedQty column as one of the 3 columns in the index and sorting it in the index in descending order

CREATE NONCLUSTERED INDEX IX_PurchaseOrderDetail_RejectedQty  
ON Purchasing.PurchaseOrderDetail  
    (RejectedQty DESC, ProductID ASC, DueDate, OrderQty);

**Comment by vijaykvs** [comment]
@CarlRabeler That makes sense. Probably the term "key" column is making in ambiguous in the context of index columns. Got my answer, please check the possibility of rewording that phrase.

**Comment by CarlRabeler** [comment]
will do
