### ISSUE TITLE
RANK & DENSE_RANK??

### ISSUE THREAD

**Issue by yertle983** [MicrosoftDocs/sql-docs#4128]
"Deterministic functions always return the same result any time they are called with a specific set of input values and given the same state of the database. Nondeterministic functions may return different results each time they are called with a specific set of input values even if the database state that they access remains the same. For example, the function AVG always returns the same result given the qualifications stated above, but the GETDATE function, which returns the current datetime value, always returns a different result."

Under that definition, shouldn't RANK & DENSE_RANK be classified as deterministic?

I understand that how ROW_NUMBER & NTILE are implemented they don't meet the definition of deterministic. Rows that are tied with regards to how these windowed functions are sorted will return non-deterministic results because the ties are broken in a non-deterministic manner AND the result of how that tie is broken will/may alter the returned value.

However, RANK & DENSE_RANK differ from ROW_NUMBER & NTILE in that all ties share the same returned value. So even if somewhere deep in the server code these functions are triggering the same tie break scenario that is being handled in a non-deterministic way, the result of how that tie is broken has no impact on the values the functions return for each of those rows and the results will be the same every time the query is run so long as the underlying data hasn't changed.

The only scenario that I could come up with in which RANK & DENSE_RANK would return non-deterministic values is when the values they are sorted off of are non-deterministic. However, none of the functions classified as deterministic would hold up to that strict of a definition. For example, SUM(NEWID()) is non-deterministic but SUM is still classified as a deterministic function as it should be. 

Am I missing something? Is there some other scenario where RANK & DENSE_RANK are non-deterministic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40d5f476-1dad-ca8f-094a-cd537d89355f
* Version Independent ID: 466ecb08-0f84-738a-3651-d9b655325f05
* Content: [Deterministic and Nondeterministic Functions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/deterministic-and-nondeterministic-functions?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/user-defined-functions/deterministic-and-nondeterministic-functions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/user-defined-functions/deterministic-and-nondeterministic-functions.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@yertle983 -- thank you for your well-reasoned feedback.

@rothja -- please look into this issue #4128.

**Comment by rothja** [comment]
@yertle983 Thank you for this feedback and question. I don't have an immediate answer for you, but I will investigate and see if I can get some details (and also see if the doc needs to be clarified). Thank you!

**Comment by rothja** [comment]
@yertle983 After doing some research internally, I do not have a conclusive answer for you on this question. Is the lack of these details blocking your use of functions? Or is this part of your own research to understand SQL Server more technically? The subject matter expert I spoke to on this article believes that the categorization of deterministic and non-deterministic is correct here even if we don't go into the underlying details. I apologize for the delayed response.

**Comment by rothja** [comment]
I'm going to close the issue, but feel free to add any comments or suggestions. I apologize if the docs are unclear in this case. Thank you!
