### ISSUE TITLE
Do document needs update for Availability Group Databases?

### ISSUE THREAD

**Issue by GITAhmad123** [MicrosoftDocs/sql-docs#4130]
Do document needs update for Availability Group Databases?
Kindly share the process or at least warnings only!

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81b4b8ea-3a1e-8e54-210d-1366b5d30556
* Version Independent ID: 9cc8729d-6289-7043-156e-d1051a7d02c0
* Content: [Database Detach and Attach (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-detach-and-attach-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/database-detach-and-attach-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/database-detach-and-attach-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@GITAhmad123 -- thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task.

**Comment by GITAhmad123** [comment]
> @GITAhmad123 -- thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task.

Thank you, William
Actually in case of SQL Server AG, the attach and detach constraints with respect to AG should also be added in this article?
I am hopeful that any warning; which may come up while we attach/detach databases of AG should be added in this article.
Thanks

**Comment by WilliamAntonRohm** [comment]
@GITAhmad123 -- thank you for clarifying.

@stevestein -- please look into this issue #4130.

**Comment by stevestein** [comment]
@GITAhmad123 - thanks for the feedback. Info was added to the detach article stating that you can't detach a database that is in an availability group.

Thanks!

#please-close
