### ISSUE TITLE
Missing Object Type 'SO'

### ISSUE THREAD

**Issue by Cobi911** [MicrosoftDocs/sql-docs#4131]
which is a Sequence Object (SEQUENCE_OBJECT in sys.objects).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 119f0d2e-697f-c218-40ef-c1a0c05cdf9e
* Version Independent ID: 69e49c79-1f35-3e66-ef57-ebcb19d90b02
* Content: [sys.all_objects (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-all-objects-transact-sql?view=sql-server-ver15&source=docs)
* Content Source: [docs/relational-databases/system-catalog-views/sys-all-objects-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-all-objects-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@Cobi911 -- thank you for catching this.

@stevestein -- please look into this issue #4131.

**Comment by rothja** [comment]
Apologies for the delayed response. @CarlRabeler Could you please look into this issue? Thank you! #reassign:CarlRabeler

**Comment by CarlRabeler** [comment]
PR pending to fix this - will be live within 24 hours
