### ISSUE TITLE
Update documentation for RHEL 8 

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#4134]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/sql-docs.es-es/issues/74

@sirio3mil commented 9 hours ago — with docs.microsoft.com
This are more accurate commands for RHEL 8 using dnf instead of yum

dnf -y install dnf-plugins-core
dnf config-manager --add-repo https://packages.microsoft.com/config/rhel/8/mssql-server-2019.repo
dnf config-manager --add-repo https://packages.microsoft.com/config/rhel/8/prod.repo
ACCEPT_EULA=Y dnf -y install mssql-server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b543b57-f397-779d-6fe4-1bc2ecd3bdca
* Version Independent ID: e274a0f3-ec74-e809-f4d3-515782b29a92
* Content: [RHEL: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-red-hat?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/quickstart-install-connect-red-hat.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-red-hat.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by MikeRayMSFT** [comment]
@sirio3mil 
Thank you for the submission. We're reviewing.

@CeciAc  thank you for moving it int our queue

**Comment by Susanthab** [comment]
Python2 reached EOL on 31st Jan, 2020. So still SQL Server needs Python2? When it will be switched to Python3?

**Comment by VanMSFT** [comment]
Thanks! Currently looking into this

**Comment by VanMSFT** [comment]
Since we've tested with yum, and not dnf, we will not be updating our documentation. The customer can choose to use dnf, but there are no plans for us to test this.

FYI - @CeciAc Thanks!

@Susanthab - We're looking for guidance on Python3 in the future, but currently, SQL Server on RHEL 8 only supports Python2.
