### ISSUE TITLE
Incorrect page link

### ISSUE THREAD

**Issue by semcha** [MicrosoftDocs/sql-docs#4135]
In the "SQL Server 2017 Database Engine" section on this page, the "see What's New in Integration Services in SQL Server 2017" redirects back to this page itself: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/what-s-new-in-sql-server-2017-database-engine?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2add531-b902-ad44-c471-0eec3b3549d4
* Version Independent ID: 0d856a5a-3b3c-5f72-cfbf-f38f2399eb5b
* Content: [What's new in SQL Server 2017 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-2017?view=sql-server-ver15#feedback)
* Content Source: [docs/sql-server/what-s-new-in-sql-server-2017.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/what-s-new-in-sql-server-2017.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by semcha** [comment]
This commit: https://github.com/MicrosoftDocs/sql-docs/commit/e9d80a0befa48d06805bae8015779d3f6bd87711

**Comment by WilliamAntonRohm** [comment]
@semcha -- Alexey, thank you for your feedback.

@MikeRayMSFT -- Mike, this link and "What's new in SQL Server 2017 Database Engine" (https://github.com/MicrosoftDocs/sql-docs/issues/4049) both redirect to their own page.  Please let me know the correct destination links and I will update the document.
