### ISSUE TITLE
The TargetFile option is not applied to the Script Parameters and Properties section

### ISSUE THREAD

**Issue by ashamrai** [MicrosoftDocs/sql-docs#4136]
I`ve tested this in pipeline with the following cmd:

`"C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/Extensions/Microsoft/SQLDB/DAC/130/sqlpackage.exe" /action:script  /outputpath:$(build.artifactstagingdirectory)\db-rollback.sql /SourceConnectionString:"Server=tcp:myazuresqlserver,1433;Initial Catalog=mydb;Persist Security Info=False;User ID=useradmin;Password=$(passwordVariable);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" /tf:"$(build.artifactstagingdirectory)\AdventureWorksDW\AdventureWorksDW\bin\Release\AdventureWorksDW.dacpac" /tdn:mydb`

I`ve got the answer:

> *** The Script Action does not support a source database and a target file.

So, the TargetFile option should be removed from the Script Parameters and Properties section  or should be added an explanation how we can use TargetFile here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage.exe - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/tools/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage.md)
* Product: **sql**
* Technology: **ssdt**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by pensivebrian** [comment]
I think you want use the `/SourceFile` parameter instead of the `/TargetFile` parameter. The `/TargetFile` parameter is for generating the target file, which isn't the case for the `/Action:Script` action. Can you try something like:

`sqlpackage /action:script /sf:"D:\Crap\AW.dacpac" /outputpath:deploy.sql /TargetConnectionString:"server=server2017;database=AW;integrated security=true"
`
The sqlpackage docs aren't the greatest. We could definitely add some samples.

**Comment by ashamrai** [comment]
> I think you want use the `/SourceFile` parameter instead of the `/TargetFile` parameter. The `/TargetFile` parameter is for generating the target file, which isn't the case for the `/Action:Script` action. Can you try something like:
> 
> `sqlpackage /action:script /sf:"D:\Crap\AW.dacpac" /outputpath:deploy.sql /TargetConnectionString:"server=server2017;database=AW;integrated security=true" `
> The sqlpackage docs aren't the greatest. We could definitely add some samples.

Yes, your suggestion works as a direct deployment. However, my goal here to get a rollback script.

**Comment by ashamrai** [comment]
I see that behavior is by design, but documentation is not aligned with it. Therefore, I spent my time to detect possible cases. I think, if documentation will contain something like "TargetFile is not supported by Script action" other developers will save their time in the future.

**Comment by guercheLE** [comment]
I am also trying to generate a rollback script to no success. So far, I was able to get the rollback script by resorting to an SCMP file.

This does not work:
SqlPackage ^
	/Action:Script ^
	/OutputPath:MyDb.sql ^
	/SourceServerName:MyServer ^
	/SourceDatabaseName:MyDb ^
	/SourceTimeout:60 ^
	/SourceEncryptConnection:False ^
	/SourceTrustServerCertificate:True ^
	/TargetFile:MyDb.dacpac ^
	/TargetDatabaseName:MyDb ^
	/UniversalAuthentication:False

This works:
SqlPackage ^
	/Action:Script ^
	/OutputPath:MyServer.rollback.sql ^
	/SourceFile:MyServer-Rollback.scmp

SCMP definition:
<?xml version="1.0" encoding="utf-8"?>
<SchemaComparison>
  <Version>10</Version>
  <SourceModelProvider>
    <ConnectionBasedModelProvider>
      <ConnectionString>Data Source=MyServer;Initial Catalog=MyDb;Integrated Security=True;Persist Security Info=False;Pooling=False;MultipleActiveResultSets=False;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True</ConnectionString>
    </ConnectionBasedModelProvider>
  </SourceModelProvider>
  <TargetModelProvider>
    <FileBasedModelProvider>
      <Name></Name>
      <DatabaseFileName>MyDb.dacpac</DatabaseFileName>
    </FileBasedModelProvider>
  </TargetModelProvider>
</SchemaComparison>

Interestingly, generating the deployment script takes about 12 seconds and the rollback script (using SCMP file) takes about 50 seconds.

**Comment by CarlRabeler** [comment]
@WilliamAntonRohm @pensivebrian is out due to paternity leave.

Please assign all further Issues to @hannahqin in the meantime, please.

@markingmyname for awareness

**Comment by ashamrai** [comment]
> I am also trying to generate a rollback script to no success. So far, I was able to get the rollback script by resorting to an SCMP file.
> 
> This does not work:
> SqlPackage ^
> /Action:Script ^
> /OutputPath:MyDb.sql ^
> /SourceServerName:MyServer ^
> /SourceDatabaseName:MyDb ^
> /SourceTimeout:60 ^
> /SourceEncryptConnection:False ^
> /SourceTrustServerCertificate:True ^
> /TargetFile:MyDb.dacpac ^
> /TargetDatabaseName:MyDb ^
> /UniversalAuthentication:False
> 
> This works:
> SqlPackage ^
> /Action:Script ^
> /OutputPath:MyServer.rollback.sql ^
> /SourceFile:MyServer-Rollback.scmp
> 
> MyServer-Rollback.scmp definition:
> <?xml version="1.0" encoding="utf-8"?>
> <SchemaComparison>
> <Version>10</Version>
> <SourceModelProvider>
> <ConnectionBasedModelProvider>
> <ConnectionString>Data Source=MyServer;Initial Catalog=MyDb;Integrated Security=True;Persist Security Info=False;Pooling=False;MultipleActiveResultSets=False;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True</ConnectionString>
> </ConnectionBasedModelProvider>
> </SourceModelProvider>
> <TargetModelProvider>
> <FileBasedModelProvider>
> <Name></Name>
> <DatabaseFileName>MyDb.dacpac</DatabaseFileName>
> </FileBasedModelProvider>
> </TargetModelProvider>
> </SchemaComparison>
> 
> Interestingly, generating the deployment script takes about 12 seconds and the rollback script (using SCMP file) takes about 50 seconds.

Yes, that`s interesting workaround.  I`ll check it. Anyway, documentation should be aligned to the real tool behavior .

**Comment by pensivebrian** [comment]
To generate a rollback script, I would recommend saving previously deployed .dacpac generating a script against the upgraded schema for the rollback. However, you have to be careful with a refactoring operation, like renaming a table. For operations like this, you may have undo the operation manually or create a new .dacpac which refactors back to the old name.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
