### ISSUE TITLE
should not be a deployment

### ISSUE THREAD

**Issue by csb1582** [MicrosoftDocs/sql-docs#4140]
I have found on k8s 1.15.x that deployments can sometimes run on top of each other, even when strategy is set to Recreate. Specifically, if a pod is running from a deployment, and is then manually deleted, the new pod will spin up before the old terminates.

This could be dangerous for SQL server if new pod starts on same node; both containers may try to read/write from same data and could potentially lead to corruption.

Instead of using Deployment, StatefulSet should be used for SQL server. This will ensure orderly spin-up/shut down of pods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04922c04-a2da-186c-5946-1cc4d9a7447b
* Version Independent ID: 6e490885-cdd7-079a-0b3a-4688616b0954
* Content: [Deploy a SQL Server container with Azure Kubernetes Services (AKS) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/tutorial-sql-server-containers-kubernetes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-sql-server-containers-kubernetes.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@csb1582 -- thank you for your feedback.  You are welcome to raise this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
