### ISSUE TITLE
Implicit conversion matrix says it should download as a PDF, but downloads as a PNG.

### ISSUE THREAD

**Issue by kreely** [MicrosoftDocs/sql-docs#4142]
Small issue. Just letting you know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f56efc1-e90f-68dd-cb02-2f2ba21373fd
* Version Independent ID: aa110136-4520-ed90-97fe-1fdedd1863ad
* Content: [CAST and CONVERT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/cast-and-convert-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/cast-and-convert-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@kreely -- Dave, thank you for your keen eye.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@kreely -- Dave, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
