### ISSUE TITLE
This doesn't belongs to Transaction log management.

### ISSUE THREAD

**Issue by BIGabor** [MicrosoftDocs/sql-docs#4143]
How is this related to Transaction logs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613b4ce1-07b4-4dfd-9dc9-26767af1a619
* Version Independent ID: 9944943b-72ef-278a-8afe-0595c49e42e6
* Content: [Log File Viewer - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/logs/log-file-viewer?view=sql-server-ver15)
* Content Source: [docs/relational-databases/logs/log-file-viewer.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/logs/log-file-viewer.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@BIGabor -- Bilicz, thank you for your question.  I as well do not see Transaction logs in the list of logs that can be viewed.

@MashaMSFT -- Masha, please clarify.

**Comment by MashaMSFT** [comment]
Hi @BIGabor, thanks for contacting Microsoft! You're right, this collection of articles does not belong in the transaction log manager section. Thanks for bringing this to our attention! I have created an internal tracking item to resolve this ([1678606](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1678606)). I will close this Git Issue out in the meantime but will update it once the change has been processed. 

However, please feel free to reach out via comment should you need anything further in the meantime.

Thank you so much for improving our documentation!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @BIGabor , just wanted to let you know I've processed a change that moves this content elsewhere :) It shoudl be live tomorrow. 

Thanks again for improve our docs! 
Masha from the SQL Docs team
