### ISSUE TITLE
Layout cannot display

### ISSUE THREAD

**Issue by Ray0305** [MicrosoftDocs/sql-docs#4144]
Try to reinstall but still fail.
Different problems occur every time.

![image](https://user-images.githubusercontent.com/14798066/74537106-65be6a80-4f74-11ea-8995-79657ee77bf4.png)
![image](https://user-images.githubusercontent.com/14798066/74537348-df565880-4f74-11ea-975f-d2c4afe8c804.png)
![image](https://user-images.githubusercontent.com/14798066/74537363-e4b3a300-4f74-11ea-86cc-3407082ed3b2.png)

**Comment by WilliamAntonRohm** [comment]
@Ray0305 -- Ray, thank you for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by Ray0305** [comment]
It happen when I try to use SQL Query.

https://streamable.com/xmrbz

**Comment by WilliamAntonRohm** [comment]
@Ray0305 -- Ray, thank you for clarifying.  Do you have a specific docs.microsoft.com article in mind?
