### ISSUE TITLE
Parameters are not permitted in Azure SQL Server

### ISSUE THREAD

**Issue by LarnuUK** [MicrosoftDocs/sql-docs#4145]
This document makes no mention that the parameters (*login* and poorly name *Param2*) are not permitted when using Azure SQL Server.

If you attempt to use the function on Azure with a parameter you get an error:
```sql
SELECT SUSER_SID('sa'); --Obviously sa won't appear on an Azure Server
```
> Msg 40507, Level 16, State 1, Line 1
> 'SUSER_SID' cannot be invoked with parameters in this version of SQL Server.

The documentation should reflect this, so that readers know they would need a different method to obtain the `sid` of a different login (for example by use of `sys.database_principals`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28934caf-abb8-47e6-5c49-a27c5005bac1
* Version Independent ID: dad62802-701f-7528-0c80-fb10f94ad9fb
* Content: [SUSER_SID (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/suser-sid-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/suser-sid-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/suser-sid-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@LarnuUK -- Thom, thank you for your feedback.

@VanMSFT -- Van, please look into this issue #4145.

**Comment by VanMSFT** [comment]
Hello @LarnuUK! Thank you for the suggestion! I implemented a clarification under a new Azure SQL DB remark for the document. This should go live shortly. We appreciate your assistance with making our documents better!
