### ISSUE TITLE
Misplaced hyphen?

### ISSUE THREAD

**Issue by mrlife** [MicrosoftDocs/sql-docs#4146]
Here is the sentence from the docs, with the area in question bolded.

> An availability replica provides redundancy only at the **database level-for** the set of databases in one availability group.

Here is the proposed update to the bolded section.

> database-level for

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c5b4585-159a-6472-140f-8e9439222ab7
* Version Independent ID: 03a14cb4-5589-1156-5a4e-938665968ebb
* Content: [What is an Always On availability group? - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@mrlife -- thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

**Comment by MashaMSFT** [comment]
Hi @mrlife,  thank you so much for improving our documentation! I just wanted to let you know that you have the ability to make these changes yourself, if you were interested in doing so :) Not only will this help improve our documentation, but you'll be listed as a contributor to the article!

If this is something you'd like to do, here are the steps: 
1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Name your file change and provide a description, if necessary
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page

You can find more information here: https://aka.ms/editsqldocs

I hope that helps! And I hope you have a wonderful rest of your day :)
Masha from the SQL Docs team
