### ISSUE TITLE
Primary and Secondary Replica SQL Server Error Logs

### ISSUE THREAD

**Issue by GITAhmad123** [MicrosoftDocs/sql-docs#4152]
Hi All,
If at primary replica the business continues; then the SQL Server error log on secondary server is also synchronized with primary? Both Servers have different physical machines! In both case why and why not?
Does it should be part of this page as well ?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 154afa3b-d022-db3d-b118-ef4126a23ca0
* Version Independent ID: 72b2496e-683d-c4f2-bc01-441d81f8383f
* Content: [SQL Server error log (availability groups) - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/sql-server-error-log-always-on-availability-groups?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/sql-server-error-log-always-on-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/sql-server-error-log-always-on-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@GITAhmad123 So sorry for the delay. So you're asking if the error log gets synchronized it will show the same physical machine in both logs? Or if it doesn't why not? Is that the correct question? Thank you!

**Comment by rothja** [comment]
@GITAhmad123 Thanks for reaching out. I'm not sure I have enough information to go on here, but apologies if I just misunderstood the initial description. I'm going to close this issue, but please feel free to add more details and I will reopen it to continue investigating. Thank you!
