### ISSUE TITLE
LocalDB is an option when installing SQL Server 2016 Express.

### ISSUE THREAD

**Issue by ticianaciminari** [MicrosoftDocs/sql-docs#4155]
@doggy8088 commented yesterday — with docs.microsoft.com
LocalDB on this page is an option when installing SQL Server 2016 Express. It should be modified to LocalDB is an option when installing SQL Server 2017 Express.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea66ca27-e0b1-cd1e-a8ef-55911169c71a
* Version Independent ID: f2340ce9-9771-851e-60a7-237c6e55f085
* Content: [SQL Server Express LocalDB - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/sql-server-express-localdb.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/sql-server-express-localdb.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by ticianaciminari** [comment]
Hi Team,

Could you please check the suggestion from user?

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@doggy8088, @ticianaciminari -- Will, Ticiana -- thank you for your feedback.  I am looking into this issue.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, "SQL Server 2016 Express" comes from includes/ssexpcurrent-md.md -- should ssexpcurrent be "...2017..." now?

**Comment by MikeRayMSFT** [comment]
> @MikeRayMSFT -- Mike, "SQL Server 2016 Express" comes from includes/ssexpcurrent-md.md -- should ssexpcurrent be "...2017..." now?

IMO we should remove the version, number. includes/ssexpcurrent-md.md should just be SQL Server.

**Comment by MikeRayMSFT** [comment]
@doggy8088, @ticianaciminari -

Thanks for this submission, because the information applies equally to SQL Server 2016, 2017, and 2019, we're going to remove the version specific information.

I appreciate your attention to detail.
