### ISSUE TITLE
The iPython notebook file is not found

### ISSUE THREAD

**Issue by ticianaciminari** [MicrosoftDocs/sql-docs#4156]
@VioletVivirand commented 21 hours ago — with docs.microsoft.com
The iPython notebook file at https://raw.githubusercontent.com/microsoft/sql-server-samples/master/samples/features/sql-big-data-cluster/spark/data-virtualization/mssql_spark_connector.ipynb is not found, please update the hyperlink of the file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e7588-f740-33b4-303b-e927f3400414
* Version Independent ID: 186607e3-fd55-5d9b-2cfc-26120fc438ad
* Content: [Connect Spark to SQL Server - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/spark-mssql-connector?view=sql-server-ver15#feedback)
* Content Source: [docs/big-data-cluster/spark-mssql-connector.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/spark-mssql-connector.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by ticianaciminari** [comment]
Hi Team,

Could you please check issue from user?

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@VioletVivirand, @ticianaciminari -- Chung-Ping, Ticiana, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue #4156.

**Comment by MikeRayMSFT** [comment]
The article was updated on January 24 with a new link.

The link may not have been updated on all localized versions. What locale is being used?

Here's the updated content:

## Run the sample notebook

To demonstrate the use of the MSSQL Spark Connector with this data, you can download a sample notebook, open it in Azure Data Studio, and run each code block. For more information about working with notebooks, see [How to use notebooks in SQL Server](notebooks-guidance.md).

1. From a PowerShell or bash command line, run the following command to download the **mssql_spark_connector_non_ad_pyspark.ipynb** sample notebook:

   ```PowerShell
   curl -o mssql_spark_connector.ipynb "https://raw.githubusercontent.com/microsoft/sql-server-samples/master/samples/features/sql-big-data-cluster/spark/data-virtualization/mssql_spark_connector_non_ad_pyspark.ipynb"
   ```

**Comment by MikeRayMSFT** [comment]
@RyanKing77 - can we follow up on this as a possible localization error?

**Comment by MikeRayMSFT** [comment]
@ticianaciminari and @VioletVivirand, I've confirmed that this is in fact being corrected in the localized paths. It should be done in a week or so. In the mean time the correct path is in my previous comment.
