### ISSUE TITLE
Infinity litteral

### ISSUE THREAD

**Issue by theGerk** [MicrosoftDocs/sql-docs#4157]
I'm trying to run some testing where I need a float argument to a stored procedure with values of positive and negative infinity. I can't figure out how to do this.

**Comment by WilliamAntonRohm** [comment]
@theGerk -- Benji, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
