### ISSUE TITLE
Azure SQL Database is ticked but...

### ISSUE THREAD

**Issue by martinsmith123456** [MicrosoftDocs/sql-docs#4162]
The xEventProfiler node does not show in SSMS when connected to Azure SQL Database (using most up-to-date version of SSMS - v.18.4)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c84f914-e1fc-5cfe-e56e-74aefaf9a5ba
* Version Independent ID: d56b9604-2dc1-9f97-ae79-0a9039eeec45
* Content: [Use the SSMS XEvent Profiler - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/extended-events/use-the-ssms-xe-profiler?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/extended-events/use-the-ssms-xe-profiler.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/extended-events/use-the-ssms-xe-profiler.md)
* Product: **sql**
* Technology: **xevents**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
@martinsmith123456 -- thank you for your feedback.

@markingmyname -- please look into this issue #4162.

fyi @yualan

**Comment by markingmyname** [comment]
@martinsmith123456,

Apologizes for the delayed response.

Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

In the meantime, please visit [UserVoice](https://feedback.azure.com/forums/908035-sql-server) to see if this issue was already submitted to the product group.

**Comment by CarlRabeler** [comment]
@martinsmith123456 removed tick- not supported.
Thanks for bringing this to our attention
