### ISSUE TITLE
Does not convert to local time

### ISSUE THREAD

**Issue by DaveBoltman** [MicrosoftDocs/sql-docs#4163]
The query under the heading [Query Temporal Tables using local time zone](https://docs.microsoft.com/en-us/sql/t-sql/queries/at-time-zone-transact-sql?view=sql-server-ver15#c-query-temporal-tables-using-local-time-zone) always returns the time in Pacific Standard Time instead of Local Time, as advertised. Since an estimated [1% of people live in the Pacific Standard Time zone](https://blog.cyberclip.com/world-population-by-time-zone), this will be wrong 99% of the time.
It's easy enough to hard-code your local time zone in the SQL code, but then it won't always return local time as the code claims to do, but only that hard-coded time zone, as the MS employee here has done!
Please either fix the code or the heading. A suggested heading could be "Query Temporal Tables using _Pacific Standard Time_", but fixing the code would be much more useful, thank you.

**Comment by WilliamAntonRohm** [comment]
@DaveBoltman -- thank you for your feedback.

@VanMSFT -- please look into this issue #4163.

**Comment by VanMSFT** [comment]
Hi @DaveBoltman! Thank you so much for the feedback. I have changed the heading in the doc, and it should go live later today. We very much appreciate your suggestion.
