### ISSUE TITLE
 'e' character in 5. is too much

### ISSUE THREAD

**Issue by emadfalsafi1** [MicrosoftDocs/sql-docs#4164]
End of number 5. is only an 'e' character. 
I think it shouldn't be here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61fcc05d-fb57-f09e-21f2-f248fba6f23f
* Version Independent ID: 51fd5fd6-d538-4fc2-cce0-c766bc5a4c06
* Content: [Configure availability group in SSMS - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/use-the-availability-group-wizard-sql-server-management-studio?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/use-the-availability-group-wizard-sql-server-management-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/use-the-availability-group-wizard-sql-server-management-studio.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @emadfalsafi1 , thank you for contacting Microsoft! You're right, that e is not meant to be there :) 

Would you be interested in submitting the change yourself? Not only does this help improve our documentation, but you'll be listed as a contributor to the article!

If you'd like to do so, here are the steps: 
1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Name your file change and provide a description, if necessary
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page

However, I am happy to process this change on my end as well. 

Thank you for improving our documentation!
Masha from the SQL Docs team

**Comment by emadfalsafi1** [comment]
Hi Masha

Yes I did'nt know that I can do it.
I will be very Happy to try this.

Your Dokumentation is our very Important, we work based on Microsoft.

Thanks
Best regards
Emad


________________________________

**Comment by MashaMSFT** [comment]
Hi @emadfalsafi1 , just wanted to check in - did you get a chance to submit a public PR? If not, I am happy to do so for you! Please let me know what you prefer :)

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @emadfalsafi1 , thank you so much for updating our documentation! It really helps us :) 

I'll go ahead and close out this Git Issue. I hope you have a wonderful rest of your day, and thanks again!!
Masha from the SQL Docs team
