### ISSUE TITLE
uncomment the phrase "CREATE DATABASE SCOPED CREDENTIAL MyCredentials "

### ISSUE THREAD

**Issue by dineshaj10** [MicrosoftDocs/sql-docs#4165]
-- Create a db master key if one does not already exist, using your own password.
CREATE MASTER KEY ENCRYPTION BY PASSWORD='&lt;EnterStrongPasswordHere&gt;';

-- Create a database scoped credential.CREATE DATABASE SCOPED CREDENTIAL MyCredentials
WITH IDENTITY = 'SHARED ACCESS SIGNATURE',
SECRET = 'QLYMgmSXMklt%2FI1U6DcVrQixnlU5Sgbtk1qDRakUBGs%3D';

syntax error in the "Create database scoped credential"  line, The pharse is commented , it has to be in next line uncommented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140d7c84-acc3-f722-99af-867be1f8752a
* Version Independent ID: 6bb40855-9644-1b18-3c4f-cec734cdc169
* Content: [CREATE DATABASE SCOPED CREDENTIAL (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-scoped-credential-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-database-scoped-credential-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-database-scoped-credential-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@dineshaj10 -- thank you for your feedback and correction.

@Potapy4 -- thank you for creating that PR.

@VanMSFT -- please review the above-mentioned PR 4175.

**Comment by VanMSFT** [comment]
Thanks @dineshaj10 and @Potapy4! I've approved the changes.
