### ISSUE TITLE
Missing column information

### ISSUE THREAD

**Issue by sidesw1pe** [MicrosoftDocs/sql-docs#4170]
I can see the following columns, which are not described in this article, when I select from sys.external_data_sources:
1. connection_options
2. pushdown

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd8614c9-679c-a0d9-719e-9cb63e5d81bb
* Version Independent ID: 3193d7a4-387b-b9bb-60b1-f5c066fd1358
* Content: [sys.external_data_sources (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-external-data-sources-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-catalog-views/sys-external-data-sources-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-external-data-sources-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@sidesw1pe -- thank you for your feedback.

@stevestein -- please look into this issue #4170.

**Comment by rothja** [comment]
Apologies for the delayed response. @CarlRabeler Could you please look into this issue? Thank you! #reassign:CarlRabeler

**Comment by CarlRabeler** [comment]
@pmasl Pedro, could you please look at this issue re: missing columns? Thanks, Carl

**Comment by pmasl** [comment]
#reassign:uc-msft

**Comment by pmasl** [comment]
#assign:CarlRabeler

**Comment by pmasl** [comment]
#assign:uc-msft who owns this area. Confirmed the new SQL 2019 columns were missed.

**Comment by PRMerger10** [comment]
uc-msft is already assigned.

**Comment by CarlRabeler** [comment]
#resassign:uc-msft

**Comment by rothja** [comment]
@uc-msft Could you add descriptions for these columns here and I can help get it into the docs. #assign:rothja

**Comment by pmasl** [comment]
Also @mihaelablendea in case she has context

**Comment by rothja** [comment]
@mihaelablendea @uc-msft Please take a look at this older git issue. @sidesw1pe has pointed out that the table [sys.external_data_sources](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-external-data-sources-transact-sql?view=sql-server-ver15) does not have documentation for two columns:

1. connection_options
2. pushdown

I verified these columns exist on SQL Server 2019:

![image](https://user-images.githubusercontent.com/1580454/95112130-8d825e80-070e-11eb-910e-a461a08f593c.png)

If you can provide some descriptions, I can help add them to the article.

Mihaela, I'm adding you to the issue along with UC and me. #assign:mihaelablendea

**Comment by rothja** [comment]
@mihaelablendea @uc-msft Let me know if you have a chance to take a look at this. Thank you!

**Comment by MikeRayMSFT** [comment]
Tracking in User Story 1799704: PolyBase | Git Issue - Describe new columns in sys.external_data_sources
