### ISSUE TITLE
KeyProtection wont be enabled 

### ISSUE THREAD

**Issue by ahmedifhaam** [MicrosoftDocs/sql-docs#4171]
Following the same procedures mentioned here keyprotection was not enabled until i setup encryption and signing certificates on the HGS server. Following this article i was able to start the hgs server perfectly https://argonsys.com/microsoft-cloud/library/step-by-step-configuring-the-host-guardian-service-in-windows-server-2016/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f498ebf8-8cda-7e68-c70c-9ecd0e7bd7df
* Version Independent ID: b710fea4-0d4e-5fdd-03e8-ce2679fa18c2
* Content: [Tutorial: Always Encrypted with secure enclaves using SSMS - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@ahmedifhaam -- Ahmed, thank you for your feedback and a solution.

@jaszymas -- please look into this issue #4171.

cc @MightyPen as a writer

**Comment by VanMSFT** [comment]
Following up with Jakub

**Comment by ahmedifhaam** [comment]
@WilliamAntonRohm (Y)

**Comment by rpsqrd** [comment]
Hey @ahmedifhaam,

Thanks for sharing this feedback! Are you trying to set up HGS for shielded VMs or SQL Server Always Encrypted?

The steps in this doc are only intended for use with SQL Server, which does not require the key protection service. The steps for setting up HGS for shielded VMs are available at https://aka.ms/shieldedvms

Ryan

**Comment by VanMSFT** [comment]
@ahmedifhaam - We'll close this for now, but please follow-up if you have any concerns. Thanks!
