### ISSUE TITLE
Ambiguous Step 

### ISSUE THREAD

**Issue by ahmedifhaam** [MicrosoftDocs/sql-docs#4172]
Point number 4 on step 2 is ambiguous since for the first time users. All the other points explicitly mention which server to execute what except this point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f498ebf8-8cda-7e68-c70c-9ecd0e7bd7df
* Version Independent ID: b710fea4-0d4e-5fdd-03e8-ce2679fa18c2
* Content: [Tutorial: Always Encrypted with secure enclaves using SSMS - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@ahmedifhaam -- Ahmed, thank you for your feedback.

@jaszymas -- please look into this issue #4172.

cc @MightyPen as a writer

**Comment by VanMSFT** [comment]
Following up with Jakub

**Comment by VanMSFT** [comment]
Hi @ahmedifhaam - Ryan has updated the doc, and I hope that clears up this question for you. Please follow-up if there are any concerns. We appreciate your input.
