### ISSUE TITLE
USE HINT('DISALLOW_BATCH_MODE')

### ISSUE THREAD

**Issue by SQLBigEyesDad** [MicrosoftDocs/sql-docs#4173]
It's supported from SQL Server 2019 not SQL Server 2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33da0c41-feb0-82a9-0ce9-9e2dbe58a1c4
* Version Independent ID: 4a97457a-c149-3c41-b78a-5b4e3869f078
* Content: [Query Hints (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-query?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/queries/hints-transact-sql-query.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/hints-transact-sql-query.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@SQLBigEyesDad -- Jungsun, thank you for your feedback.  I am looking into this document.

**Comment by pmasl** [comment]
Hello,
This is likely a copy past issue. Will correct

**Comment by pmasl** [comment]
@WilliamAntonRohm please close this
