### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by mansakerlund** [MicrosoftDocs/sql-docs#4174]
Suggest that the "Only one BDC per domain is allowed at this time" text is changed "Only one BDC per domain (Active Directory) is allowed at this time"  or similar to clarify the meaning of the word domain as we have had several discussion within the organisation where this wording have been misinterpreted and misunderstood. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6733c468-62a5-41d9-2c5a-5ca57ee5fdf3
* Version Independent ID: dd529f6a-f02d-0dc4-dd4f-52321e90bed0
* Content: [Deploy in Active Directory mode - SQL Server Big Data Cluster](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-active-directory?view=sql-server-ver15#feedback)
* Content Source: [docs/big-data-cluster/deploy-active-directory.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-active-directory.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @NelGson
* Microsoft Alias: **negust**

**Comment by WilliamAntonRohm** [comment]
@mansakerlund -- thank you for your feedback.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@NelGson -- please review the above-mentioned PR 13890.

cc @MightyPen as a writer

**Comment by NelGson** [comment]
Looks good to me @WilliamAntonRohm

**Comment by MightyPen** [comment]
Fixed, with PR #13967 .

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/13967`

@mansakerlund Thank you for submitting this Issue. We hope to hear from you again. I am now Closing this Issue #4174 .

@WilliamAntonRohm MikeRayMSFT is the Writer, not me.  Check 'ms.reviewer' in these cases, for a Writer, when ms.author is a non-Writer.

@MikeRayMSFT Feel free to improve the phrasing of the altered sentence, if you see fit.  Thanks, G.
