### ISSUE TITLE
update bundeled runtime in linux package

### ISSUE THREAD

**Issue by bitcloud** [MicrosoftDocs/sql-docs#4177]
Could you please update the bundeled runtime version in the sqlpackage linux zip file? It currently uses a outdated libssl version e.g. only found in debian oldoldstable anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3df6af-9ac8-bc57-93dc-29ff713c1d3b
* Version Independent ID: 7624e2cc-7aa9-40dd-4015-3371ea2ea0a2
* Content: [Download and install sqlpackage - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-ver15)
* Content Source: [docs/tools/sqlpackage-download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage-download.md)
* Product: **sql**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by WilliamAntonRohm** [comment]
@bitcloud -- Jan, thank you for your feedback and a solution.

@pensivebrian -- please look into this issue #4177.

cc @MightyPen as a writer

**Comment by pensivebrian** [comment]
Thanks for reporting @bitcloud. We'll get the runtime updated in one of the next upcoming releases. Is the tool not working for you as is due to this issue?

**Comment by bitcloud** [comment]
I'm currently building a docker container for backup tasks. The issue is, that I need to downgrade openssl and ca-certificates to a version from 2014. But there is also the azure-cli part of the container which needs an update version of the ca-certificate because the current Root CA Microsoft is using (Baltimore Root CA) was not part of the 2014 bundle. So i needed to add that manually.

Long story short: it is working for now but is a little bit hacky ;-)

Also if the runtime version is from around 2014-2015, I would guess that there were certainly some important fixes in the mean time beside that one ;-)

**Comment by pensivebrian** [comment]
Thanks for the explanation. sqlpackage was built with a fairly recent (within 6 months) version of the dotnet 2.2 sdk. The dotnet sdk is the one doing the hard work of packaging all dependencies. I plan on upgrading to the dotnet 3.1 sdk soon for future sqlpackage releases, so hopefully that will resolve this issue. I'll make sure note this update in the release notes.

**Comment by bitcloud** [comment]
Then I have to excuse myself. I just dug a little deeper into the code and found this:

https://github.com/dotnet/corefx/commit/901ff58aee521984e8791f9f7d51fabfd31f910e#diff-beb297cd7d8c3c9c24b7cb07ff5bd6f8

So the support for 1.1 was introduced in Sep 4, 2018.
The issue is that support for 1.0.* got removed in the current debian stable which was released July 6th, 2019.

https://packages.debian.org/search?keywords=libssl1

Sorry @pensivebrian for dramatizing ;-)

Still it would be great for having a version working with the current stable release. So Thanks for looking into that!

**Comment by pensivebrian** [comment]
No worries. Glad to hear you got to the bottom of this. And thanks for using sqlpackage!

**Comment by CarlRabeler** [comment]
issue appears to be addressed and @pensivebrian is on top of next steps. Closing for now.
