### ISSUE TITLE
Missing information SSIS Master / SSIS Worker

### ISSUE THREAD

**Issue by andgarz** [MicrosoftDocs/sql-docs#4180]
There is not reference in documentation about SSIS Master / SSIS Worker services. Also there are no reference about privileges required for this services concerning certificate access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b3831a3-6c86-243c-4b07-8960e4d06d7b
* Version Independent ID: dfd7599d-88eb-99f2-c227-0c9dc82bfd87
* Content: [Configure Windows Service Accounts and Permissions - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@andgarz -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue #4180.

**Comment by MikeRayMSFT** [comment]
@andgarz - thank you for the feeback. I'm reviewing with the engineering team.
