### ISSUE TITLE
Bug when synchronizing a SSAS Database

### ISSUE THREAD

**Issue by andgarz** [MicrosoftDocs/sql-docs#4181]
In SSMS 18.4 there is an error when synchronizing SSAS Databases:

![image](https://user-images.githubusercontent.com/61247035/74862345-fb158200-5319-11ea-97e4-13f92c82a492.png)

When I click previously in attach button and after I try again Sync Databases, the wizard works fine.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@andgarz -- thank you for uncovering this behavior.  Please file a bug at [SQL Server Feedback](https://aka.ms/sqlfeedback).
