### ISSUE TITLE
SQL Agent Extension actually still in preview?

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/sql-docs#4183]
This page still marks the agent as being in preview.... I don't believe that's the case anymore (but I can't quote an authoritative source)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbdd7165-e41d-4643-67b8-04a1fa83a21d
* Version Independent ID: 82da58fe-125e-1870-1935-34f5a8b536f4
* Content: [SQL Server Agent extension - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/sql-server-agent-extension?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/sql-server-agent-extension.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/sql-server-agent-extension.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
@CHDAFNI-MSFT -- Chase, thank you for your feedback.

@yualan -- Alan, please look into this issue #4183.

cc @MightyPen as a writer

**Comment by MightyPen** [comment]
@CHDAFNI-MSFT Hello, this feature _**is**_ still in preview.    Don't feel bad, I would have guess it was no longer in preview too!

Closing this Issue #4183 now.

cc: @yualan @WilliamAntonRohm
