### ISSUE TITLE
great

### ISSUE THREAD

**Issue by AJ37z** [MicrosoftDocs/sql-docs#4184]
amazing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d04ee6-6c35-a50f-2b95-1ab707143fa6
* Version Independent ID: 5d4ae5ce-40e8-b180-6e49-685e2e1a8878
* Content: [sp_executesql (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-executesql-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-executesql-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-executesql-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@AJ37z -- thank you for your positive feedback!  I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
