### ISSUE TITLE
wrong repository for RedHat7

### ISSUE THREAD

**Issue by laurentiupetre1** [MicrosoftDocs/sql-docs#4187]
Hi,
In step 1 the repository is for RedHat 8 even if in the begining of the article is specified that the article aims version 7 also.
Using this will generate the following error during setup, after entering the password:

/opt/mssql/bin/sqlservr: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /opt/mssql/bin/../lib/libc++abi.so.1)

Just like in this article:
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-change-repo?view=sql-server-ver15&pivots=ld2-rhel
please add this comment:
"If you are using RHEL 7, change the path below to /rhel/7 instead of /rhel/8."
It will help many people.
Thanks,
Laurentiu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b543b57-f397-779d-6fe4-1bc2ecd3bdca
* Version Independent ID: e274a0f3-ec74-e809-f4d3-515782b29a92
* Content: [RHEL: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-red-hat?view=sql-server-linux-ver15#feedback)
* Content Source: [docs/linux/quickstart-install-connect-red-hat.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-red-hat.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @laurentiupetre1! Thanks for the suggestion. I added the note to the doc. It will go live later today. Thanks for your feedback.

**Comment by Yuanmu93** [comment]
very helpful for me, thank you @laurentiupetre1
