### ISSUE TITLE
ARM CPU or 32bit Version

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/sql-docs#4189]
There is no compatible version for the Surface X. I would prefer Arm64 but settle for 32bit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15#feedback)
* Content Source: [docs/azure-data-studio/download-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download-azure-data-studio.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@stephenc01 -- thank you for your feedback.  Please file an issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

**Comment by stephenc01** [comment]
If you end up here. Please vote for arm support

https://feedback.azure.com/forums/908035-sql-server/suggestions/39175228-sql-server-management-studio-for-windows-on-arm-a
