### ISSUE TITLE
No INLINE scalar UDFs for SQL 2016

### ISSUE THREAD

**Issue by DaveBoltman** [MicrosoftDocs/sql-docs#4192]
This page (https://docs.microsoft.com/en-us/sql/t-sql/statements/create-function-transact-sql?view=sql-server-2016) speaks about inline scalar UDFs which are actually only available from SQL 2019. Possibly the page was just copied and pasted from the 2019 version, but is not correct for SQL 2016:

![image](https://user-images.githubusercontent.com/8627894/75011387-2fa74c00-5488-11ea-98d9-5fb785a86c45.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71bc28bf-993a-79e3-1a83-b39052bab882
* Version Independent ID: 73350c77-8839-dcd3-af67-9342a49dbf22
* Content: [CREATE FUNCTION (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-function-transact-sql?view=sql-server-2016#feedback)
* Content Source: [docs/t-sql/statements/create-function-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-function-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@DaveBoltman -- thank you for your feedback.

@CarlRabeler -- please look into this issue #4192.

**Comment by CarlRabeler** [comment]
@DaveBoltman thanks - i have added this to my honeydew list

**Comment by CarlRabeler** [comment]
@DaveBoltman thanks - fixing now
