### ISSUE TITLE
Incorrect statement about database snapshot

### ISSUE THREAD

**Issue by rysalah** [MicrosoftDocs/sql-docs#4194]
https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/unsupported-sql-server-features-for-in-memory-oltp?view=sql-server-ver15#scenarios-not-supported

> "Database snapshots as not supported for databases that have a MEMORY_OPTIMIZED_DATA filegroup."

Since SQL Server 2019, database snapshots are supported for databases that have a MEMORY_OPTIMIZED_DATA filegroup.

**Comment by WilliamAntonRohm** [comment]
@rysalah -- thank you for your feedback.

@MightyPen -- please look into this issue #4194.

**Comment by MightyPen** [comment]
Today, I fixed this Issue #4194, with internal repo PR #13886.
- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/13886`
  - https://github.com/MicrosoftDocs/sql-docs-pr/pull/13886

@rysalah Thank you for submitting this Issue. We hope to hear from you again.

I am now Closing this Issue #4194, as fixed and completed.  The fix should be visible / live on Docs before Tuesday 2020/Feb/25.

(GeneMi = MightyPen)

cc: @WilliamAntonRohm @rothja
