### ISSUE TITLE
Deployment's yaml contains wrong environment variable name for the SA's password

### ISSUE THREAD

**Issue by mstavrev** [MicrosoftDocs/sql-docs#4195]
The deployment has wrong name for the SA's password environment variable.
It is using:
 - name: MSSQL_SA_PASSWORD

however, the 2017 image expects the variable to be named SA_PASSWORD. Without this change the server terminates with the error:

ERROR: Unable to set system administrator password: Password validation failed. The password does not meet SQL Server password policy requirements because it is too short. The password must be at least 8 characters..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04922c04-a2da-186c-5946-1cc4d9a7447b
* Version Independent ID: 6e490885-cdd7-079a-0b3a-4688616b0954
* Content: [Deploy a SQL Server container with Azure Kubernetes Services (AKS) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/tutorial-sql-server-containers-kubernetes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-sql-server-containers-kubernetes.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@mstavrev -- thank you for your feedback.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review the above-mentioned PR 13894.
