### ISSUE TITLE
XACT_ABORT does not always roll back the transaction on error. The page does not explain why

### ISSUE THREAD

**Issue by kamilk** [MicrosoftDocs/sql-docs#4196]
I believe the documentation is missing some detail on what conditions need to be met for the transaction to be rolled back when a runtime error is raised and this option is ON. I have just posted this question on StackOverflow: https://stackoverflow.com/questions/60338489

Clarification of the documentation would be appreciated. 
- Is this true the severity level must be 16 or greater? (Like suggested here: https://stackoverflow.com/a/11957224/1371188)
- What happens.if the option is set in a stored procedures executing in a transaction created by an external process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9fdd49-3145-7ae3-bf90-47f002895264
* Version Independent ID: 075116a4-7a22-3816-9782-079952bc0fe7
* Content: [SET XACT_ABORT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-xact-abort-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/set-xact-abort-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-xact-abort-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
Please review this post: https://dba.stackexchange.com/questions/233079/best-practices-for-committing-a-transaction-in-sql-server-where-try-catch-is-use/233129#233129

**Comment by CarlRabeler** [comment]
@kamilk please re-open if the link in this issue did not resolve your question. Closing for now.
