### ISSUE TITLE
bulkadmin permissions are not allowed on Linux

### ISSUE THREAD

**Issue by ndiaz-addepar** [MicrosoftDocs/sql-docs#4198]
This is a very undocumented issue.
It is impossible to run BULK INSERT from anything but the sysadmin (or sa) account.
running : " ALTER SERVER ROLE [bulkadmin] ADD MEMBER [regularlogin];" 
results in: 
"Msg 16202, Level 15, State 1, Line 1
Keyword or statement option 'bulkadmin' is not supported on the 'Linux' platform.
"
Alternatively running:
"GRANT ADMINISTER BULK OPERATIONS TO [regularlogin];" 
Produces: 
"
Msg 16202, Level 15, State 3, Line 1
Keyword or statement option 'ADMINISTER BULK OPERATIONS' is not supported on the 'Linux' platform.
"

This is both undocumented and not acceptable to use the inprocess loader.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5106a6-4e54-2177-3e03-b2845f9587c5
* Version Independent ID: c3bc5aaa-0119-9c4d-3d7b-0ee218885361
* Content: [BULK INSERT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/bulk-insert-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/bulk-insert-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/bulk-insert-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@ndiaz-addepar -- Noel, thank you for your feedback.

@CarlRabeler -- Carl, please look into this issue #4198.

**Comment by CarlRabeler** [comment]
@ndiaz-addepar - Please assign to @VanMSFT

**Comment by ndiaz-addepar** [comment]
@CarlRabeler I don't think I have permissions to assign PRs in a MS repo :)

**Comment by VanMSFT** [comment]
@tejasaks - Hey Tejas, do you mind confirming if altering bulkadmin is unsupported on Linux?

**Comment by tejasaks** [comment]
Bulkadmin role is unsupported on Linux for the moment. Users require sysadmin privileges to perform bulk insert. If it is not documented today, we should document it.

@Mike<mailto:mikehab@microsoft.com>,
Additional proof for the bulk insert impersonation improvement.

~Tejas Shah | Principal Program Manager | Data Platform – SQL Server

**Comment by VanMSFT** [comment]
Thanks, @tejasaks! I'm adding this information under the Permissions section. Should go live later today.

Thanks @ndiaz-addepar for bringing this up! We appreciate your help on our documentation!

**Comment by johnwc** [comment]
@tejasaks We just ran into this issue today as well, and have heavy concerns being forced to give a login sysadmin privileges to bulk insert data files. Is there any ETA on the SQL Server team side of getting this enabled for linux version?

**Comment by tejasaks** [comment]
Adding @amvin87. 

Thanks for the feedback @johnwc . We are acutely aware of this challenge and have this work in our backlog. Please keep providing feedback and we promise to look into it as and when we can reprioritize the requirements such as this one.

**Comment by johnwc** [comment]
Does sql server have a issue tracker that we can create this issue in, rather than in the docs repo?

**Comment by tejasaks** [comment]
You can use https://aka.ms/sqlfeedback to provide the feedback and upvote existing feedback. For example, you can upvote on following item and provide additional context. 

https://feedback.azure.com/d365community/idea/116fe702-4825-ec11-b6e6-000d3a4f0da0

**Comment by johnwc** [comment]
@tejasaks now 4 years old, any expectations on this? This kills us on our security audits.
