### ISSUE TITLE
NULL! NULL! NULL!

### ISSUE THREAD

**Issue by jxfreeman** [MicrosoftDocs/sql-docs#4199]
The article fails to address NULLs in columns for Unique constraints.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3709c36d-5f11-41b8-0926-e4549bd2b78e
* Version Independent ID: cff4179f-03c9-bba8-b87b-a4e13fb3e919
* Content: [Unique Constraints and Check Constraints - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/unique-constraints-and-check-constraints?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/tables/unique-constraints-and-check-constraints.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/unique-constraints-and-check-constraints.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@jxfreeman -- Jason, thank you for your feedback.

@stevestein -- Steve, please look into this issue #4199.

**Comment by stevestein** [comment]
@jxfreeman - thanks for the feedback!

This is at the top of the article: 
_Unlike PRIMARY KEY constraints, UNIQUE constraints allow for the value NULL. However, as with any value participating in a UNIQUE constraint, only one null value is allowed per column._

What information would you like to see here?


-Thanks

**Comment by jxfreeman** [comment]
The scenario I was working on was an external id that is not present in all cases.  The requirement was that any existing ids must be unique.  But not all rows in the tracking table would have external ids, hence there would be more than one null in the column.  The solution is trivial and simply to use a filtered index.  But the documentation doesn’t suggest this.  From a strict perspective I suppose it’s beyond the scope of a discussion around unique indexes to make those kinds of suggestions, but from a development perspective it seems related especially given that the only real difference between the definition of a unique index and a unique filtered index is the presence of a predicate.  Any mention of this relationship would have saved me some time.

Thanks

- Jason
206.940.0110
jason.b.freeman@gmail.com

**Comment by stevestein** [comment]
@jxfreeman - thanks for the feedback. Yeah, it's hard to address the many scenarios and potential caveats associated with each feature.  

Thanks for the clarification. We're going to go ahead and close this one.

#please-close
