### ISSUE TITLE
Is this a mistake in documentation?

### ISSUE THREAD

**Issue by Peled-Zohar** [MicrosoftDocs/sql-docs#4202]
In this part:
```
< table_index > ::=
{  
    {  
      INDEX index_name [ CLUSTERED | NONCLUSTERED ] [ UNIQUE ]
      .....
```
I think the order is reversed and should be 

      INDEX index_name [ UNIQUE ] [ CLUSTERED | NONCLUSTERED ] 

At least on my SSMS version 14.0.17230.0 the way it's currently documented was marked as wrong (with the red squiggly line)
and my server (2016 (SP1-CU15-GDR) (KB4505221) - 13.0.4604.0 (X64)) accepted the second version (with `unique` before `clustered`)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be5dfc7-5496-f8ec-072f-81132fe92054
* Version Independent ID: 634e3c60-d717-92ba-dd93-e3773edf2816
* Content: [CREATE TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
Yes – it is wrong here. Fixing now. I is correct in the CREATE INDEX article.
Thanks for pointing this out.
Carl

**Comment by Peled-Zohar** [comment]
Glad I could help :-)
