### ISSUE TITLE
Figure doesn't display all objects

### ISSUE THREAD

**Issue by dhanajipatil** [MicrosoftDocs/sql-docs#4203]
Figure doesn't show all the objects, e.g. CircularString, CompoundCurve etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2797e2b3-62ca-d4f9-c36f-31d77358deda
* Version Independent ID: 0e1e4a3a-2bcb-97e1-94ac-98be1bfbda97
* Content: [Spatial Data Types Overview - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-data-types-overview?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/spatial/spatial-data-types-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/spatial/spatial-data-types-overview.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@dhanajipatil -- thank you for your feedback.

@MladjoA -- please look into this issue #4203.

cc @MightyPen as a writer

**Comment by WilliamAntonRohm** [comment]
@MladjoA -- please look into this issue.

cc @rothja as a writer

**Comment by MladjoA** [comment]
@dhanajipatil , thanks for the feedback. 
Figure is now fixed.

**Comment by MladjoA** [comment]
#please-close
