### ISSUE TITLE
SQL Server

### ISSUE THREAD

**Issue by SQLDTAIT** [MicrosoftDocs/sql-docs#4205]
Hi - the functionality is available in SQL Server now with the 2019 release, page says just Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7199df2d-4950-2533-791c-4fc134ce8eed
* Version Independent ID: 0b52e407-d9be-0ebd-2414-6a2478d999c3
* Content: [sys.sensitivity_classifications (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-sensitivity-classifications-transact-sql?view=azuresqldb-current#feedback)
* Content Source: [docs/relational-databases/system-catalog-views/sys-sensitivity-classifications-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-sensitivity-classifications-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @barmichal
* Microsoft Alias: **mibar**

**Comment by WilliamAntonRohm** [comment]
@SQLDTAIT -- David, thank you for your feedback.  I am looking into this document.

**Comment by MightyPen** [comment]
@WilliamAntonRohm Hi William,  please create the necessary PR, and use the following revised markdown lines to replace the current lines, to correct the AppliesTo / Versioning situation in the indicated article.

```
monikerRange: ">= sql-server-2019 || = azuresqldb-current || = azure-sqldw-latest || = sqlallproducts-allversions"
---
# sys.sensitivity_classifications (Transact-SQL)

[!INCLUDE[appliesto-ss-asdb-asdw-xxx-md](../../includes/appliesto-ss-asdb-asdw-xxx-md.md)]
```

Thanks.  (GeneMi)

cc: @barmichal (just fyi)
