### ISSUE TITLE
Possible Trigger improvement

### ISSUE THREAD

**Issue by BrilliantTechie** [MicrosoftDocs/sql-docs#4206]
I wonder why the example inner joined the inserted table with Purchasing.PurchaseOrderHeader table and then join the vendor table.

I believe we can get the same result using only the inserted table inner joining the vendor table directly without joining with Purchasing.PurchaseOrderHeader table?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de204ead-2a80-46ec-6adc-3d8b13977602
* Version Independent ID: eb4f715f-eba6-5d39-b2ba-5baae1b58c71
* Content: [Use the inserted and deleted Tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/triggers/use-the-inserted-and-deleted-tables?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/relational-databases/triggers/use-the-inserted-and-deleted-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/triggers/use-the-inserted-and-deleted-tables.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@BrilliantTechie Thank you for the feedback and suggestion. I'm going to find some time to take a closer look and get back to you. If you have the time to write out the statement as you think it should be that might help. Otherwise, I'll investigate with your description.

**Comment by rothja** [comment]
@BrilliantTechie Thanks for your patience. I took some time to look carefully at the sample, and I do think you're correct. It seems to be an extra step to join to the PurchaseOrderHeader table when the vendor ID is already in the inserted table. At the same time, I don't see any reason why joining hurts (except for the inefficiency). I don't have the time right now to thoroughly test our assumption here, so I am going to leave the working code as is, but this is something we could test and change in the future. Sorry for the confusion, and thanks for the feedback!
