### ISSUE TITLE
Viewing sqlaudit files

### ISSUE THREAD

**Issue by fatherjack** [MicrosoftDocs/sql-docs#4209]
The suggestion that Log Viewer from SSMS can be used to read .sqlaudit files it incorrect, it doesnt do a very good job at all.
1 - you have to locate the log file / browse to it rather than have an option to open it from the audits that are on the active instance in SSMS
2 - once opened the content is broken and includes file read errors and ascii characters.

I'd suggest removing this suggestion from this page or fixing Log Viewer so that it can read and filter sqlaudit files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2a1a3a-cffa-ec4b-dedc-c1c23d547abb
* Version Independent ID: b0e62617-2dc3-8762-e359-a78af1fe3191
* Content: [SQL Server Audit (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-database-engine?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/security/auditing/sql-server-audit-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/auditing/sql-server-audit-database-engine.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@fatherjack -- thank you for your documentation feedback.  For Log Viewer changes, you are welcome to add a suggestion here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

@VanMSFT -- please look into this issue #4209.

**Comment by VanMSFT** [comment]
Hi @fatherjack! Thanks for the suggestion. It sounds to me like you are experiencing a product issue, and not a documentation issue. Log Viewer is appropriate to view SQL Server audits, and if you are experiencing an issue with the product, please feel free to submit a Product Feedback. Thanks for your time and input on our docs!
