### ISSUE TITLE
This page lists ALTER ANY EVENT SESSION but the docs page for that says it doesnt support Azure SQL

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/sql-docs#4210]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e18242cc-01df-27ba-a2cc-0f73e20c27d0
* Version Independent ID: af3f329d-8374-9093-ac64-75ad95aa2b57
* Content: [Quickstart: Extended events in SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/extended-events/quick-start-extended-events-in-sql-server?view=sql-server-ver15#appendix1)
* Content Source: [docs/relational-databases/extended-events/quick-start-extended-events-in-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/extended-events/quick-start-extended-events-in-sql-server.md)
* Product: **sql**
* Technology: **xevents**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by WilliamAntonRohm** [comment]
@StingyJack -- thank you for your feedback.

@MightyPen -- please look into this issue #4210.

**Comment by CarlRabeler** [comment]
@StingyJack this quickstart as written does not work for Azure SQL Database. For Azure SQL Database, see https://docs.microsoft.com/en-us/azure/sql-database/sql-database-xevent-db-diff-from-svr - there are two code samples there that are written for Azure SQL Database

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by StingyJack** [comment]
@WilliamAntonRohm @CarlRabeler this page states that it's for AzureSQL at the top and is littered with disclaimers for azure sql. So it's reasonable for me to expect that it's going to be consistent and correct in that regard. The expected docs work would be to either remove the azure sql stuff or fix the gaps. If it's not a priority right now, that's fine and I kind of understand, but closing the issue without resolving it is not appropriate for a few reasons.

**Comment by CarlRabeler** [comment]
I was not intending to close it. I wanted to give you a quick note telling you about the two articles that are written specifically for Azure SQL while I work on finding the time to address the article that you are asking about.
Carl

**Comment by WilliamAntonRohm** [comment]
@CarlRabeler, @StingyJack -- my mistake -- I misunderstood Carl's response as final.

**Comment by CarlRabeler** [comment]
PR pending

**Comment by CarlRabeler** [comment]
merged and live
