### ISSUE TITLE
ROUND(123.456,0) resulting incorrect results

### ISSUE THREAD

**Issue by devudu** [MicrosoftDocs/sql-docs#4212]
If we round off 123.456 to the whole number by applying math rules, the result should be 124. However, ROUND(123.456,0) is resulting in 123. Isn't this buggy?

**Comment by WilliamAntonRohm** [comment]
@devudu -- thank you for your feedback.  To make sure we have all the information needed to triage your issue, please let us know which docs.microsoft.com article you’re referencing.  

It looks like 123.456 is less than 123.5, and so the rounding is correct.
