### ISSUE TITLE
Double entry in SQL Agent file permissions

### ISSUE THREAD

**Issue by mverbaas** [MicrosoftDocs/sql-docs#4213]
There seems to be a duplicate entry in the SQL Agent file system permissions. The first and SQL line are equal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b3831a3-6c86-243c-4b07-8960e4d06d7b
* Version Independent ID: dfd7599d-88eb-99f2-c227-0c9dc82bfd87
* Content: [Configure Windows Service Accounts and Permissions - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by mverbaas** [comment]
Line 321 and 322 for extra clearity.

**Comment by WilliamAntonRohm** [comment]
@mverbaas -- Mark, thank you for your feedback. 

@MikeRayMSFT -- Mike, please look into this issue #4213.

**Comment by CarlRabeler** [comment]
fixed - thanks @mverbaas
