### ISSUE TITLE
Missing datatypes from 'BaseType', 'Precision', and 'Scale' options of SQL_VARIANT_PROPERTY

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#4215]
Under **BaseType**

1. `BIT`

Under **Precision**

1. `DATE`
2. `DATETIME2(s)`
3. `DATETIMEOFFSET`
4. `DATETIMEOFFSET(s)`
5. `DECIMAL / NUMERIC`
6. `TIME`
7. `TIME(s)`

Under **Scale**

1. `DATETIME2(s)`
2. `DATETIMEOFFSET`
3. `DATETIMEOFFSET(s)`
4. `DECIMAL / NUMERIC`
5. `TIME`
6. `TIME(s)`

&nbsp;
_Please note:_ all of the datatypes noted above that do not have an `(s)` at the end are ones that have an optional scale, and the default when no scale is provided should be noted on this page.

&nbsp;
Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa0e861-d609-4b40-7d29-6a520760dd0a
* Version Independent ID: 8b0558ab-e2dc-188e-34d9-062970b1c50b
* Content: [SQL_VARIANT_PROPERTY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/sql-variant-property-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/sql-variant-property-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/sql-variant-property-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@srutzky -- Solomon, thank you for your detailed feedback.

@MikeRayMSFT -- Mike, please look into this issue #4215.

**Comment by srutzky** [comment]
@MikeRayMSFT Please see PR #4218 .

Full test script can be found on PasteBin (relevant queries copied to the PR):
https://pastebin.com/3RAFxLbH

**Comment by cawrites** [comment]
@srutzky thank you for contacting Microsoft. It appears that there was an update issued that addresses this request.  Please don't hesitate to contact us again regarding any documentation related concerns.

**Comment by cawrites** [comment]
#please-close
