### ISSUE TITLE
Example E Typo

### ISSUE THREAD

**Issue by melknothink** [MicrosoftDocs/sql-docs#4216]
TYPE = HADOOP, should be TYPE = BLOB_STORAGE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e450abc6-2dbd-8f6c-423c-52aca37a2b06
* Version Independent ID: 4aff678a-6db1-a438-9aca-bb4b4d49bc27
* Content: [CREATE EXTERNAL DATA SOURCE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-external-data-source-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-data-source-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@melknothink Thank you for pointing out this error - fixing now.
Carl
