### ISSUE TITLE
READONLY: Definition and explanation is misslading

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/sql-docs#4219]
READONLY  for a parameter in the function prototype can only be used for table value parameters.

The documentation as it is now, both in the syntax of how to define the prototype of the function and in the explanation of READONLY, gives no info that READONLY can only be used with table value parameters. On the contrary, the text in the explanation of READONLY  indicate that it can be used for other types than table value types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71bc28bf-993a-79e3-1a83-b39052bab882
* Version Independent ID: 73350c77-8839-dcd3-af67-9342a49dbf22
* Content: [CREATE FUNCTION (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-function-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-function-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-function-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by srutzky** [comment]
> the text in the explanation of READONLY indicate that it can be used for other types than table value types.

Not only is that misleading and incorrect, but the current wording for `READONLY` also implies that it's optional for TVPs, and that's also provably false.

I'm submitting a PR for this.

**Comment by srutzky** [comment]
@Bartolomeus-649 and @CarlRabeler Please see PR #4224
