### ISSUE TITLE
Remove confusing text about control flow after CATCH-statement

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/sql-docs#4221]
In the fourth paragraph under the Remarks header, remove the last sentence since its content is confusing and it is better explained in the leading sentence of the following paragraph.

> ... ~~If the END CATCH statement is the last statement in a stored procedure or trigger, control is passed back to the statement that called the stored procedure or fired the trigger.~~
> 
> When the code in the CATCH block finishes, control passes to the statement immediately after the END CATCH statement. ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5733f776-615e-9e0e-7df2-8adacf4c3b09
* Version Independent ID: 2f6cc6e5-8479-87d1-de8d-9ac97551925d
* Content: [TRY...CATCH (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/try-catch-transact-sql?view=sql-server-2016)
* Content Source: [docs/t-sql/language-elements/try-catch-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/try-catch-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@Bartolomeus-649 -- thank you for your feedback.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@Bartolomeus-649 -- after investigation, I think the existing sentence should stay, as it clarifies a particular case.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by Bartolomeus-649** [comment]
@WilliamAntonRohm It might clarify one particular case, but at the same time it directly raises the issue abut  what happens when this is not the case. It's normally best when explaining something to  give the generic, broad picture of how something work first, and then, if there are special circumstances which require further explanation, you do them afterwards. 
So, if you want to keep it, then it should be moved to after the generic statement. As it is now, it appears like there is something special, "an exception to normal", that happens when the last statement in a CATCH is also the last statement in the procedure.

**Comment by WilliamAntonRohm** [comment]
@Bartolomeus-649 -- you make a good point.  I've updated the document and it should be live by tomorrow.
