### ISSUE TITLE
Please add information on what privileges are needed to query these tables.

### ISSUE THREAD

**Issue by Prof-hu** [MicrosoftDocs/sql-docs#4222]
Please add information on what privileges are needed to query these tables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 311319ea-7b5d-3c12-aec2-72e400ae6d76
* Version Independent ID: 6a57fb1b-adcf-aa6f-b0bb-d42a71d96246
* Content: [System Tables (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/system-tables-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-tables/system-tables-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/system-tables-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@Prof-hu -- thank you for your feedback.

@stevestein -- please look into this issue #4222.

**Comment by rothja** [comment]
Apologies for the delayed response. @CarlRabeler Could you please look into this issue? Thank you! #reassign:CarlRabeler

**Comment by CarlRabeler** [comment]
@Prof-hu Hi - is there a specific table that you are requesting information regarding query permissions? Generally, you should not query system tables directly, but rather through system stored procedures, statements, functions, etc. This said, to query system tables, you generally need to be a member of the sysadmin role or specifically be given read permissions to a particular table - directly or via a database role.
