### ISSUE TITLE
Azure SQL Server compatible?

### ISSUE THREAD

**Issue by LowerKees** [MicrosoftDocs/sql-docs#4223]
When looking at the Azure SQL Server auditing settings, at least some of the audit action groups from the above article and the Azure SQL Server seem to overlap. The same goes for Azure SQL Database audit action groups. Still, this article indicates that it's only applicable to SQL Server. Is there a specific Azure SQL Server/SQL Database article that I'm missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e423dd72-6012-f9f0-9bd1-6ab946399770
* Version Independent ID: f55d3328-111e-13d2-d8c2-78ba2b644b91
* Content: [SQL Server Audit Action Groups and Actions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions?view=sql-server-ver15#database-level-audit-action-groups)
* Content Source: [docs/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@LowerKees -- thank you for your question.

@VanMSFT -- please look into this issue #4223.

**Comment by VanMSFT** [comment]
Hi @LowerKees - Thanks for your inquiry. Here's our document on auditing for Azure SQL Database: <https://docs.microsoft.com/azure/sql-database/sql-database-auditing>

There are some overlaps for Azure SQL Database in the document for [SQL Server Audit Action Groups and Actions](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions?view=sql-server-ver15#database-level-audit-action-groups), but not all will apply. The available Audit Action Groups should be listed under our reference documentation: <https://docs.microsoft.com/en-us/powershell/module/az.sql/set-azsqldatabaseaudit?view=azps-3.5.0#parameters>

@DavidTrigano - David, please provide any input. Thanks!

**Comment by DavidTrigano** [comment]
Hi @LowerKees,

The available Audit Action Groups available for Azure SQL server are listed under our reference documentation: https://docs.microsoft.com/en-us/powershell/module/az.sql/set-azsqlserveraudit?view=azps-3.5.0#parameters

Best,
D.
