### ISSUE TITLE
Complete re-write needed.

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/sql-docs#4227]
There are so many problems with this I can't list them all, but here are a few of them.
You really need to check with the developers to make sure you get this stuff correct.
* Is binary really supported, or is any binary data just converted to varchar/nvarchar?
* What about Unicode support with binary data?
* The initial description is very clear and good, don't make it more complicated in other places.
    As an example, _"If the length to delete is longer than the first string, it is deleted to the first character in the first string."_ has a huge potential to be tiny bit clearer.
* I have found no combination of arguments which return a binary datatype.
* It say:  _"The length parameter counts each surrogate in character_expression as a single character."_, what about the _start_ argument?

## Argument: character_expression
1. Confusing, first it **is** character data, then later it can be either character or binary data.
2. "Character data" is unclear and unspecified.
3. No mention of character sets or Unicode/UTF8.

> _**character_expression**_
> <ins>DataType; char, varchar, nchar, nvarchar, binary or varbinary</ins>
> <ins>Argument type: Constant, variable, or column</ins>
> ~~Is an expression of character data. character_expression can be a constant, variable, or column of either character or binary data.~~
> <ins>The datatype of _character_expression_ affect the datatype of the return value. See return types below.</ins>

## Argument: start
1. Unclear if _start_ is zero-based or not.
2. Unclear what this "null string" is that can be returned.
3. Ambiguous datatype of start, both integer and bigint is mentioned, also it supposedly _can be_ a "bigint" without any mention of what it is when it's not a bigint.
4. Confusing and unclear constraints for _start_: "first _character_expression_" - are there more than one _character_expression_?, " If start is longer than the first _character_expression_" - a bigint is 8 bytes long so only very short strings?

> **_start_**
> <ins>DataType: [bigint](https://docs.microsoft.com/en-us/sql/t-sql/data-types/int-bigint-smallint-and-tinyint-transact-sql?view=sql-server-ver15)</ins>
> <ins>Argument type: Constant, variable, or column</ins>
> ~~Is an integer value that s~~Specifies the ~~location~~ <ins>1-based index into _character_expression_ where</ins> to start ~~deletion and~~ insertion<ins> and possible delition (argument _length_ > 0)</ins>. ~~If start is negative or zero, a null string is returned. If start is longer than the first character_expression, a null string is returned.~~ 
> Valid values for _start_ is: 1 <= _start_ <= [LEN](https://docs.microsoft.com/en-us/sql/t-sql/functions/len-transact-sql?view=sql-server-ver15)(_character_expression_). 
Invalid values for start returns [_NULL_](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/null-and-unknown-transact-sql?view=sql-server-ver15).      ~~start can be of type bigint.~~

## Section: Return Types
> ### Return Types
> ~~Returns character data if character_expression is one of the supported character data types. Returns binary data if character_expression is one of the supported binary data types.~~
<ins>The return type depend on the input arguments.
As long as none of the arguments are nchar or nvarchar, then the return datatype is varchar.
If any of the arguments are either nchar or nvarchar, then the return datatype is nvarchar.
If _character_expression_ is a zero length string or zero length binary data or or NULL, then NULL is returned
If _start_ is outside the intervall; 1 <= _start_ <= [LEN](https://docs.microsoft.com/en-us/sql/t-sql/functions/len-transact-sql?view=sql-server-ver15)(_character_expression_), then NULL is returned.</ins>
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b3f468-5782-d8f1-089f-59527367cdd6
* Version Independent ID: 60885f1b-5125-f2c4-c3d3-1ccd65e0859b
* Content: [STUFF (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/stuff-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/stuff-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/stuff-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@Bartolomeus-649 -- thank you for your detailed feedback.

@MikeRayMSFT -- please look into this issue #4227.

**Comment by pmasl** [comment]
@Bartolomeus-649 please clarify what you mean by "What about Unicode support with binary data". If using a bin2 UTF8 collation? Or are you referring to something else?

**Comment by Bartolomeus-649** [comment]
Since you can mix data types for the first and last arguments, then it is possible to insert an nvarchar into binary data, or the other way around.

**Comment by pmasl** [comment]
This is still bound to legal data type conversions which are thoroughly documented. If you have specific issues using the STUFF function, then providing a repro would help.

**Comment by Bartolomeus-649** [comment]
So, STUFF don't really support binary data types then?

**Comment by srutzky** [comment]
@Bartolomeus-649 (and @pmasl , etc):

> So, STUFF doesn't really support binary data types then?

Well, yes and no. Binary data is converted into character data. If both first _and_ fourth parameters are binary and/or `VARCHAR`, then the result is `VARCHAR`. If either of those parameters is `NVARCHAR`, then both input parameters are interpreted as being `NVARCHAR` and the result is `NVARCHAR`. If I remember correctly, only `SUBSTRING` will return a true binary type for purely binary inputs.

So, in the context provided above, binary data can be passed in, and will be use in either 1-byte or 2-byte segments, depending on `VARCHAR` vs `NVARCHAR` interpretation. Output can easily be converted back to binary. The reason why I said "yes and no" at the beginning is because if you pass in both parameters as binary and convert the return value back into a binary type, then it's pretty much the same as working in binary (outside of the need to convert the return value back into binary), right? Please see the examples below:

```sql
SELECT CONVERT(VARBINARY(100), STUFF(0X12340056, 2, 1, 0XAB));
-- 0x12AB0056  (replaced 2nd byte -- 0x34 -- with 1 byte)

SELECT CONVERT(VARBINARY(100), STUFF(0X12340056, 2, 1, 0XABCD));
-- 0x12ABCD0056  (replaced 2nd byte -- 0x34 -- with 2 bytes)

SELECT CONVERT(VARBINARY(100), STUFF(0X12340056, 2, 2, 0XAB));
-- 0x12AB56  (replaced 2nd and 3rd bytes -- 0x3400 -- with 1 byte)

SELECT CONVERT(VARBINARY(100), STUFF(0X1234005678, 2, 1, N'A'));
-- 0x123441007800  (replaced 2nd UTF-16 code point -- 0x0056 -- with 1 UTF-16 code point)

SELECT CONVERT(VARBINARY(100), STUFF(0X12340056789A, 2, 1, N'A'));
-- 0x12344100789A  (replaced 2nd UTF-16 code point -- 0x0056 -- with 1 UTF-16 code point)
```

Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

**Comment by Bartolomeus-649** [comment]
But just because you can convert between datatypes and use that converted value as an argument does not really make the function support that datatype. If that were the case then we could just get rid of datatypes all together since basically any datatype could, in one way or another, be converted to any other datatype.
And the documentation for STUFF clearly say that the returned datatype is BINARY if called with a BINARY datatype, which is obviously wrong.

**Comment by rothja** [comment]
@Bartolomeus-649 I'm sorry for the confusion in the documentation. Your feedback is noted for possible future improvements. If you want to suggest an immediate specific change today, you can edit the article with the Edit button that appears on docs pages. Your suggested edits will get reviewed and published if accepted. Thank you! #reassign:rothja
