### ISSUE TITLE
'Create Login' command is incorrect

### ISSUE THREAD

**Issue by RTTrickster** [MicrosoftDocs/sql-docs#4233]
The command;

_CREATE LOGIN [mygroup] FROM EXTERNAL PROVIDER
GO_

Does not work - it produces error; 
_Msg 102, Level 15, State 48, Line 1
Incorrect syntax near 'PROVIDER'._

The correct syntax appears to be; 

_CREATE **USER** [mygroup] FROM EXTERNAL PROVIDER_

As indicated here: https://docs.microsoft.com/en-us/azure/sql-database/sql-database-manage-logins

**Comment by WilliamAntonRohm** [comment]
@RTTrickster -- thank you for your feedback.  Please provide more context around your general task.

**Comment by RTTrickster** [comment]
I had an Azure SQL instance that was originally only setup with a SQL administrator password. I needed to get an AD group a Role within the Database. 

1. I added an Active Directory Administrator in Azure
2. I connected to the Azure SQL instance with SSMS
3. I started a new query against the target database with the 'create login' command, which failed with the error in OP. 
4. I found alternate articles suggesting the correct syntax was actually 'create user' and not 'create login'. I tested the command with 'create user' and it succeeded. 
5. I completed testing with a member of the AD group, who now had the necessary permissions.

**Comment by WilliamAntonRohm** [comment]
@RTTrickster -- thank you for your detailed clarification.

@VanMSFT -- please look into this issue #4233.

**Comment by VanMSFT** [comment]
Hi @RTTrickster! Thanks for the inquiry.  The T-SQL `CREATE LOGIN [mygroup] FROM EXTERNAL PROVIDER` is a valid command in *managed instance*. If you are having issues and want to troubleshoot the problem, please contact Microsoft Support. Thanks!

**Comment by msedej** [comment]
VanMSFT did you resolve your issue ?
