### ISSUE TITLE
Behavior of ERROR_PROCEDURE() changed between SQL Server 2016 and SQL Server 2019

### ISSUE THREAD

**Issue by TheConstructor** [MicrosoftDocs/sql-docs#4234]
Hi,

I just realized that the behavior of `ERROR_PROCEDURE()` is different between SQL Server 2016 and SQL Server 2019. I am not sure if it changed in 2017 or 2019, this probably needs clarification. In the end I would like the documentation to state the change in behavior.

Statements to show the behavior change:
```tsql
BEGIN TRAN;
GO
EXEC ( N'CREATE SCHEMA deleteMe' );
GO
CREATE OR ALTER PROCEDURE usp_ExampleProc1
AS
SELECT 1 / 0;
GO
CREATE OR ALTER PROCEDURE deleteMe.[usp ExampleProc2]
AS
SELECT 1 / 0;
GO

BEGIN TRY
    EXECUTE usp_ExampleProc1;
END TRY
BEGIN CATCH
    SELECT ErrorProcedure = ERROR_PROCEDURE();
/*
SQL Server 2016 & 2019: usp_ExampleProc1
*/
END CATCH;

BEGIN TRY
    DECLARE @QualifiedProcedureName nvarchar(256) = CONCAT(QUOTENAME(SCHEMA_NAME()), '.usp_ExampleProc1');
    EXECUTE @QualifiedProcedureName;
END TRY
BEGIN CATCH
    SELECT ErrorProcedure = ERROR_PROCEDURE();
/*
SQL Server 2016: usp_ExampleProc1
SQL Server 2019: dbo.usp_ExampleProc1
*/
END CATCH;

BEGIN TRY
    EXECUTE deleteMe.[usp ExampleProc2];
END TRY
BEGIN CATCH
    SELECT ErrorProcedure = ERROR_PROCEDURE();
/*
SQL Server 2016: usp_ExampleProc2
SQL Server 2019: deleteMe.usp ExampleProc2
*/
END CATCH;
GO
ROLLBACK;
```

So it seems that in SQL Server 2019 `ERROR_PROCEDURE()` returns the name as used during the call minus quotation. Especially with stuff like tSQLt requiring the use of a space in the procedure name, I would like to call this an interesting approach. So while I totally like to have the schema, I would also love quotes, at least when needed. And as stated above, I need to know, when the definition changes.

Best

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76fe2072-7b1f-c650-b519-f76808d5c070
* Version Independent ID: a3363342-9f9d-a2d9-7553-0d3a07712336
* Content: [ERROR_PROCEDURE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/error-procedure-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/error-procedure-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/error-procedure-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@TheConstructor -- Matthias, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue #4234.

**Comment by MikeRayMSFT** [comment]
@TheConstructor -- Matthias - I'm looking into this and I appreciate the submission and the sample script. Will get back to you.

**Comment by rothja** [comment]
@juliemsft Could you please look more into this issue? Thank you! #reassign:juliemsft

**Comment by julieMSFT** [comment]
@TheConstructor Hello and thank you for contacting Microsoft. I ran your code in SQL Server 2017 and have annotated the results. The change did take place in SQL Server 2017. I will update the document to show that the from 2017 the schema and the name of the stored procedure are returned.

BEGIN TRAN;
GO
EXEC ( N'CREATE SCHEMA deleteMe' );
GO
CREATE OR ALTER PROCEDURE usp_ExampleProc1
AS
SELECT 1 / 0;
GO
CREATE OR ALTER PROCEDURE deleteMe.[usp ExampleProc2]
AS
SELECT 1 / 0;
GO

BEGIN TRY
    EXECUTE usp_ExampleProc1;
END TRY
BEGIN CATCH
    SELECT ErrorProcedure = ERROR_PROCEDURE();
/*
SQL Server 2016 & 2019: usp_ExampleProc1
SQL Server 2017: usp_ExampleProc1
*/
END CATCH;

BEGIN TRY
    DECLARE @QualifiedProcedureName nvarchar(256) = CONCAT(QUOTENAME(SCHEMA_NAME()), '.usp_ExampleProc1');
    EXECUTE @QualifiedProcedureName;
END TRY
BEGIN CATCH
    SELECT ErrorProcedure = ERROR_PROCEDURE();
/*
SQL Server 2016: usp_ExampleProc1
SQL Server 2019: dbo.usp_ExampleProc1
SQL Server 2017: dbo.usp_ExampleProc1
*/
END CATCH;

BEGIN TRY
    EXECUTE deleteMe.[usp ExampleProc2];
END TRY
BEGIN CATCH
    SELECT ErrorProcedure = ERROR_PROCEDURE();
/*
SQL Server 2016: usp_ExampleProc2
SQL Server 2019: deleteMe.usp ExampleProc2
SQL Server 2017: deleteMe.usp ExampleProc2
*/
END CATCH;
GO
ROLLBACK;

I understand that you would like to see the quotes returned when there is a space in the stored procedure name. Unfortunately, this form of contact is intended explicitly for reporting issues with the documentation, and not for the product. To get further assistance with your issue, we'd recommend engaging the community, or opening a ticket with Microsoft Support. More information can be found here: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

If you're looking to provide suggestions or ideas for improvement for the product,  you can do so at https://aka.ms/sqlfeedback.

**Comment by julieMSFT** [comment]
#please-close

**Comment by rsocol** [comment]
I believe this behaviour change should have been mentioned in the page https://docs.microsoft.com/en-us/sql/database-engine/breaking-changes-to-database-engine-features-in-sql-server-2017?view=sql-server-ver15.

Prior to upgrading I have read this page, but I have found out only after upgrading about this change (which breaks some of my queries, even if I did not change the compatibility level yet).

**Comment by rothja** [comment]
@rsocol Thanks for the suggestion. I'm also including @MikeRayMSFT on this for considering an update to that page with this info.
