### ISSUE TITLE
Buffer cache hit ratio

### ISSUE THREAD

**Issue by Jhunter1** [MicrosoftDocs/sql-docs#4236]
"Buffer cache hit ratio - Indicates the percentage of pages found in the buffer cache without having to read from disk...". This value is often over 100 so I am wondering how can it be a percentage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20bbd3bb-9820-ed3e-20e5-46708940a9dc
* Version Independent ID: 8f62a995-ec15-e038-63d6-fe464bbb6fa5
* Content: [SQL Server, Buffer Manager Object - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-buffer-manager-object?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/performance-monitor/sql-server-buffer-manager-object.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance-monitor/sql-server-buffer-manager-object.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by rrg92** [comment]
This can be due rounds by performance counter math.

**Comment by WilliamAntonRohm** [comment]
@Jhunter1, @rrg92 -- thank you for your feedback.

@julieMSFT -- please look into this issue #4236.

cc @MightyPen as a writer

**Comment by MightyPen** [comment]
@Jhunter1 Hello, @rrg92 gave a well-explained answer.
There are no specific numbers in the original description. Unless you are seeing values so high that they cannot be explained by rrg92's answer, we should consider this Issue #4236 answered, and to now be close-able.

I am now Closing this Issue.  Thank you very much @rrg92 !

If this Issue needs to be reOpened, the @ notification approach still sends messages.

Thank you for submitting this Issue. We hope to hear from you again if any other issues arise.

cc: @WilliamAntonRohm  @julieMSFT (who is a Writer)

**Comment by Jhunter1** [comment]
I'm not quite getting this. rrg92 has said the field [Buffer cache hit ratio] is not actually the percentage value and you need to perform a calculation (100*[Buffer cache hit ratio]/[Buffer cache hit ratio base]). 

That is fair enough, but Microsoft's documentation does not reflect this information. Instead they are saying the percentage is already there ready for you in the field [Buffer cache hit ratio]. "Buffer cache hit ratio... Indicates the percentage.."

**Comment by Jhunter1** [comment]
I'm not the only one finding this confusing.. https://dba.stackexchange.com/questions/88784/what-does-a-buffer-cache-hit-ratio-of-9990-mean

**Comment by rrg92** [comment]
I agree with @Jhunter1  about more clarification. I submitted a PR to keep doc about SQL Server Objects a little more clear, because this fact can occurs to another counters, not only Buffer cache hit ratio.
