### ISSUE TITLE
Ranking Functions - applies to is wrong

### ISSUE THREAD

**Issue by ChipDale66** [MicrosoftDocs/sql-docs#4238]
The APPLIES TO on this Ranking Functions page says it only applies to SQL Server, yet the 4 functions listed have their own pages which all say they apply to all 4 environments - SQL Server - Azure SQL Database - Azure Synapse Analytics (SQL DW) -  Parallel Data Warehouse. Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cf3d6dc-3bd5-b62b-0398-489f6db9c9f9
* Version Independent ID: 79e4d7d4-9f45-99d8-50ed-08e72483c533
* Content: [Ranking Functions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/ranking-functions-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/ranking-functions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/ranking-functions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@ChipDale66 -- thank you for your feedback.

@MikeRayMSFT -- please let me know if this article's APPLIES TO should instead show all four products, and assign this issue back to & I will update the document.

**Comment by CarlRabeler** [comment]
@ChipDale66 thanks - fixing
