### ISSUE TITLE
Differences Among SQL Database, Managed Instance, SQL Server

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#4239]
This page does not seem to differentiate between what is available in Azure SQL Database, Managed Instance, and SQL Server, even when the nav dropdown is set to one of these options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f33f7c8-745d-bdd0-fe14-2c1dac6875de
* Version Independent ID: 6db1bff2-e212-3337-7599-ea2b94019e04
* Content: [System Stored Procedures (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/system-stored-procedures-transact-sql?view=azuresqldb-mi-current#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/system-stored-procedures-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/system-stored-procedures-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@PrometheusRising1 -- thank you for your feedback.

@VanMSFT -- please look into this issue #4239.

**Comment by VanMSFT** [comment]
Hi @PrometheusRising1! Thanks for your feedback. Currently, managed instance falls under the umbrella of Azure SQL Database. All of the System Stored Procedure listed on that page should pertain to Azure SQL Database and SQL Server. Thanks!
