### ISSUE TITLE
UOM

### ISSUE THREAD

**Issue by dhamacher** [MicrosoftDocs/sql-docs#4243]
What is the unit of measure for the distance argument?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4238e773-b14a-ab3e-59fc-7b2ab038c0f6
* Version Independent ID: ef528a38-8f23-d76d-6b1b-d977bae597c9
* Content: [STBuffer (geometry Data Type) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geometry/stbuffer-geometry-data-type?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/spatial-geometry/stbuffer-geometry-data-type.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/spatial-geometry/stbuffer-geometry-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@dhamacher -- Daniel, please see [this article](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-data-types-overview?view=sql-server-ver15#measurements-in-spatial-data-types).

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
