### ISSUE TITLE
guidline of dealing with builtin\administrators login

### ISSUE THREAD

**Issue by wetnurseyang** [MicrosoftDocs/sql-docs#4244]
builtin\administrators login come back as a default login in SQL on Linux. Since removing "builtin\administrators" login is one of the most common security hardening activity in older versions of SQL on windows. Better to document how DBA should handle this login and whether it is officially supported to drop this login

**Comment by WilliamAntonRohm** [comment]
@wetnurseyang -- thank you for your feedback.  To make sure we have all the information needed to process your issue, please let us know which topic you’re referencing, or provide more context around your general task.
