### ISSUE TITLE
Syntax for Azure SQL Database is misleading

### ISSUE THREAD

**Issue by jude-dsouza** [MicrosoftDocs/sql-docs#4245]
-- Syntax for Azure SQL Database, Azure SQL Data Warehouse, Parallel Data Warehouse  
  LOG ( float_expression ) 

I have verified that the  Syntax for Azure SQL Database is the same as the syntax for SQL Server. That is, Azure SQL Database accepts the syntax   
LOG ( float_expression [, base ] )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5403c207-d38b-308e-92e7-0ef88c777d67
* Version Independent ID: aedd2c2c-4ce5-6eb6-8d0a-a783c5a98e3a
* Content: [LOG (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/log-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/log-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/log-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@jude-dsouza -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue #4245.
