### ISSUE TITLE
Error in sample query.

### ISSUE THREAD

**Issue by zikato** [MicrosoftDocs/sql-docs#4246]
The second sample query has extra paranthesis in SUBSTRING.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fec72919-9f99-9718-91d4-c1ca59d95106
* Version Independent ID: 89df21bb-925f-e3be-b00e-a1f2bfcf76cc
* Content: [Monitor performance of natively compiled stored procedures - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/monitoring-performance-of-natively-compiled-stored-procedures?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/in-memory-oltp/monitoring-performance-of-natively-compiled-stored-procedures.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/monitoring-performance-of-natively-compiled-stored-procedures.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@zikato fixed - thanks
