### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by jovton** [MicrosoftDocs/sql-docs#4250]
Hi. In the doc you state ... "If disablesssd is set to true along with forcesecureldap being set to true, then it will use LDAPS protocol over openldap library calls made by SQL Server." ...

I have a few questions on that, because I'd like to try it. In such a scenario, does that mean any of openldap packages have to installed beforehand, such as libnss-ldap, libpam-ldap, ldap-utils? If it makes LDAP calls via libraries, then which one, and does it have to be a specific version? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Use AD authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-ver15#additionalconfig)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **dygray**

**Comment by Dylan-MSFT** [comment]
Hey! The LDAP packages needed by SQL Server are dependencies of the package you download, so they get installed automatically by your packages manager (apt, yum, etc). There are no extra install steps.

**Comment by WilliamAntonRohm** [comment]
@jovton -- thank you for your questions.

@Dylan-MSFT -- thank you for your answers.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
