### ISSUE TITLE
The documentation is incomplete

### ISSUE THREAD

**Issue by mdhruv1** [MicrosoftDocs/sql-docs#4251]
I am looking at the documentation 
I would expect a sample of what the csv file should look like
The syntax and details of the format fit file.

That way I can walk through the whole example. 

I don’t see the details. This would be awesome that shows clearly
For csv File a format file so we can replicate the steps 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b7a6124-86bc-bd57-88c6-7c4334c49cd5
* Version Independent ID: 1598c673-fb85-3cf7-4ff9-8fdc0e384c68
* Content: [Bulk access to data in Azure Blob storage - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@mdhruv1 -- thank you for your feedback.

@MashaMSFT -- please look into this issue #4151.

**Comment by MashaMSFT** [comment]
Hi @mdhruv1, thanks for contacting Microsoft and providing your feedback! Let me see what our options are for you. Stay tuned :)

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @mdhruv1 , thanks for bringing this to our attention! I have created an internal work item to track this work  ([1698110](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1698110)). 

I will close out this Git Issue in the meantime but please feel free to comment should you need anything further.

Thanks for improving our documentation!
Masha from the SQL Docs team

**Comment by rwestMSFT** [comment]
#reassign:@rwestMSFT

**Comment by rwestMSFT** [comment]
This article is being refreshed and will publish in the next few days. There is already a link in the article that points to [sample code](https://github.com/Azure-Samples/azure-sql-db-import-data/tree/main/csv), where you can examine an example CSV file.
