### ISSUE TITLE
missing columns details

### ISSUE THREAD

**Issue by erikdarlingdata** [MicrosoftDocs/sql-docs#4254]
I believe these showed up in SQL Server 2016, but don't recall exactly:
 * reserved_worker_count,
 * used_worker_count,
 * max_used_worker_count,
 * reserved_node_bitmap

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059c6a91-de0e-fcbf-824a-f324119158f8
* Version Independent ID: 55c8ca7c-eb90-6831-c52a-c11c476f7d36
* Content: [sys.dm_exec_query_memory_grants (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-query-memory-grants-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-exec-query-memory-grants-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-query-memory-grants-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@erikdarlingdata -- Erik, thank you for your feedback.

@stevestein -- Steve, please look into this issue #4254.

**Comment by rothja** [comment]
Apologies for the delayed response. @CarlRabeler Could you please look into this issue? Thank you! #reassign:CarlRabeler

**Comment by CarlRabeler** [comment]
@pmasl Pedro, could you please look at this issue re: missing columns? Thanks, Carl

**Comment by CarlRabeler** [comment]
@pmasl Pedro, could you please look at this issue re: missing columns? Thanks, Carl

**Comment by pmasl** [comment]
Added missing info #please-close
