### ISSUE TITLE
Use New INSERT INTO ... VALUES syntax

### ISSUE THREAD

**Issue by JpsKaGitHub** [MicrosoftDocs/sql-docs#4255]
Why do Microsoft developers continue to use the OLD INSERT INTO .... VALUE SYNTAX, instead of using the NEW INSERT INTO ... VALUES Syntax introduced in SQL Server 2008 (or even earlier)?
INSERT INTO Person VALUES (1,'John');
INSERT INTO Person VALUES (2,'Mary');
....
could have been coded as:
INSERT INTO Person 
VALUES ( (1, 'John')
                (2, 'Mary'),
                (....          ) );
                

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84c44dc1-637b-22b0-35db-0668d741818d
* Version Independent ID: 5425118c-d998-df3e-89ee-29656a8aa07c
* Content: [SQL Graph Database Sample - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-sample?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/graphs/sql-graph-sample.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/graphs/sql-graph-sample.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @shkale-msft
* Microsoft Alias: **shkale**

**Comment by WilliamAntonRohm** [comment]
@JpsKaGitHub -- thank you for your feedback.  Please add your suggestion here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
