### ISSUE TITLE
typo in document.

### ISSUE THREAD

**Issue by ntorvik** [MicrosoftDocs/sql-docs#4256]
The first instance of "database_name" has a typo as indicated below, the "d-" should be "-d":

Current: You can also explicitly specify the database name with d-.
Change to: You can also explicitly specify the database name with -d.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86bd520a-7468-fd55-c357-b0f645a917ef
* Version Independent ID: 3dc9dee5-afcb-8287-4441-e84ff717186a
* Content: [bcp Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/bcp-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/bcp-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@ntorvik -- thank you for your keen eye.  I am looking into this document.
