### ISSUE TITLE
Provide Docs for Azure SQL Server Always Encrypted with Entity Framework Core on .Net Core 3+

### ISSUE THREAD

**Issue by Tim-Bijnens** [MicrosoftDocs/sql-docs#4259]
I find it hard to implement the above. Always Encrypted keys are stored in Azure KeyVault (not in secrets in my case)
Documentation on how to accomplish this in an official way would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb15ed8-749c-6cba-49d4-31f173644f73
* Version Independent ID: 4c3f1eb6-9db7-b056-d170-cdad560281df
* Content: [Develop applications using Always Encrypted - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-client-development?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/always-encrypted-client-development.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/always-encrypted-client-development.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@Tim-Bijnens -- thank you for your feedback.

@jaszymas -- please look into this issue #4259.

cc @MightyPen as a writer

**Comment by VanMSFT** [comment]
Hi @Tim-Bijnens! Thanks for submitting this issue. Sorry for the delay. Are you still having issues? I saw your comments in <https://stackoverflow.com/questions/41027953/sql-server-always-encrypted-with-net-core-not-compatible>, and wanted to follow-up.

**Comment by Tim-Bijnens** [comment]
Hi @VanMSFT 
As you can see I managed to implement it, but I lost some time doing it, it would have been nice to have had an official doc with all the steps explained (including azure keyvault permissions on local and published development)
Since there a multiple stackoverflow questions about it, I thaught I d share my basic "get up and running" solution with the community. I have no idea if the way I implemented it  is the way developers  are supposed to do it, so an "official" way of implementation could still be usefull

**Comment by VanMSFT** [comment]
Thanks @Tim-Bijnens! I'll follow-up with the Product Group and discuss these docs. We appreciate your input.

**Comment by VanMSFT** [comment]
Hi @Tim-Bijnens! Sorry for the delay! I spoke with the Product Team, and although there will not be additional documentation written at this time on Always Encrypted with Azure Key Vault, we do discuss this topic extensively here: https://docs.microsoft.com/sql/connect/ado-net/sql/sqlclient-support-always-encrypted?view=sql-server-ver15

It's not a step by step tutorial, but I'm hoping this helps. If you have any concerns, please feel free to let us know. Thanks again for bringing this issue up!
