### ISSUE TITLE
Side-by-side support for SQL Server 2019

### ISSUE THREAD

**Issue by ghotz** [MicrosoftDocs/sql-docs#4260]
I think the side-by-side support for SQL Server 2019 list is missing SQL Server 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c5b2d5d-0a6b-46e2-cb87-be75e37c538f
* Version Independent ID: 66e80689-5e06-fd53-bfdd-75058533df10
* Content: [Work with multiple versions and instances - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/work-with-multiple-versions-and-instances-of-sql-server?view=sql-server-2016)
* Content Source: [docs/sql-server/install/work-with-multiple-versions-and-instances-of-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/work-with-multiple-versions-and-instances-of-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@ghotz -- Gianluca, thank you for your feedback.

@MashaMSFT -- Masha, please look into this issue #4260.

**Comment by MashaMSFT** [comment]
Hi @ghotz, thanks for contacting Microsoft and providing your feedback! Let me do a little research.

Thanks!
Masha from the SQL Docs team

**Comment by CarlRabeler** [comment]
@ghotz hey Gianluca - help us out by clicking edit in the upper right and submitting a fix. How are you ? How bad are things in your part of Italy? Strange times - Carl

**Comment by MashaMSFT** [comment]
@ghotz , @CarlRabeler  this is actually an issue with the include, and there is incorrect information here. I already have a PR open to fix this :) 

Thanks!
Masha from the SQL Docs team

**Comment by ghotz** [comment]
> . How are you ? How bad are things in your part of Italy? Strange times - Carl
Luckily we are fine, thanks for asking, things in my area are not critical. Hope you're fine too. Strange times indeed...

**Comment by MashaMSFT** [comment]
Hi @ghotz, just wanted to let you know that I'm working with the team to get clarity on this, and update the documentation :)

Due to the complexity, it may take a bit so please bear with us!

Thanks :)
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @ghotz, thanks again for bringing this to our attention! I have processed a change to update the table in that section to be a bit more clear.

I hope that helps and please let us know if we can be of further assistance? I am going to close out this Git Issue, but please feel free to comment should you need anything further.

Thanks again and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
