### ISSUE TITLE
Basic Availability Group for non prod

### ISSUE THREAD

**Issue by matt-k11** [MicrosoftDocs/sql-docs#4261]
For licensing purposes, is there a way to create a Basic Availability Group using Developer Edition for non prod instances/envrionments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32bb0e7a-a91c-6ccd-bf16-5118801d5612
* Version Independent ID: 84eb1614-0e30-e116-9dd2-34a3db7c6b5d
* Content: [Basic availability groups for a single database - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@matt-k11 -- thank you for your question.  Please refer to [Microsoft SQL Server License Terms and Information](https://www.microsoft.com/download/details.aspx?id=39299).

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by matt-k11** [comment]
Thank you for the feedback.  Let's take the licensing piece out for clarity.  Is there a way to create a Basic Availability Group using Developer Edition?

**Comment by MashaMSFT** [comment]
Hi @matt-k11, thanks for contacting Microsoft! I don't believe you can, but let me double check to confirm.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @matt-k11 , thanks for your patience as we researched this! I tested it just to be sure, and no, you cannot create a basic availability with a developer license. Attempting to do so results in an error saying it is not supported by the developer edition. 

If this behavior is causing you a business issue and/or you feel that it should behave differently, please feel free to file a feedback item at https://aka.ms/sqlfeedback and our engineering team will be happy to triage the issue.rus-face-masks.html

I am going to close out this Git Issue for now but please feel free to comment should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team

**Comment by ntachandley** [comment]
So .. wht does rus-face-masks.html have to do with anything? Seems weird.

**Comment by MashaMSFT** [comment]
@ntachandley , thanks for bringing that to my attention! Honestly... I am not sure either :) I've deleted it, but am also confused by it..

Thanks!
Masha from the SQL Docs team
