### ISSUE TITLE
Documents are not displayed in local languages.

### ISSUE THREAD

**Issue by koatsush** [MicrosoftDocs/sql-docs#4262]
[フィードバックをこちらに入力してください]
All SQL Server related documents are written in English. Documents are not displayed in local languages such as Japanese, are there any plans to fix this?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 06ed8fd8-016f-7779-ed08-462f505c5f3e
* Version Independent ID: af26e293-4d4c-3810-b350-6dfab61a6161
* Content: [blocked process threshold Server Configuration Option - SQL Server](https://docs.microsoft.com/ja-jp/sql/database-engine/configure-windows/blocked-process-threshold-server-configuration-option?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/blocked-process-threshold-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/blocked-process-threshold-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@koatsush -- Thanks for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).   

You are also welcome to add your suggestion here:
- [UserVoice - Suggestion to improve SQL Server?](https://feedback.azure.com/forums/908035-sql-server)
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
