### ISSUE TITLE
Update automatic tuning options document

### ISSUE THREAD

**Issue by srizwanhms** [MicrosoftDocs/sql-docs#4263]
Please update this document to reflect new desired_states, reason, and actual_state as they are different in Azure SQL DB and Azure SQL MI

https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-automatic-tuning-options-transact-sql?view=sql-server-ver15

Thanks!

**Comment by WilliamAntonRohm** [comment]
@srizwanhms -- thank you for your feedback.

@jovanpop-msft -- please look into this issue #4263.

cc @MightyPen as a writer

**Comment by MightyPen** [comment]
@stevestein Steve, It falls to you to prod @jovanpop-msft in providing the info needed to address this Issue #4263 .
Thanks.

**Comment by WilliamAntonRohm** [comment]
@stevestein, @jovanpop-msft -- Steve, Jovan, please look into this issue.

**Comment by stevestein** [comment]
@srizwanhms - thanks for the feedback.

We recently created an internal work item (1781712) for refreshing all system views, stored procedures, that includes this one.

Thanks

#please-close
