### ISSUE TITLE
日本語が表示されない

### ISSUE THREAD

**Issue by LifeRyuto** [MicrosoftDocs/sql-docs#4264]
英語が表示されてしまいます

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f7ac2fe2-31da-7db6-2d5f-5091022f41d2
* Version Independent ID: bbf07c2c-7006-7b94-f12f-800fa7bc67e4
* Content: [CREATE EXTERNAL TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/ja-jp/sql/t-sql/statements/create-external-table-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-external-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@ticianaciminari -- Ticiana, please assist in translating this issue #4264.  It may be a similar request to #4262.  

The machine translation of his initial comment is "English will be displayed".

cc @MightyPen 作家として ("as a writer")
