### ISSUE TITLE
Note on this page to update

### ISSUE THREAD

**Issue by cbigenwald-edt** [MicrosoftDocs/sql-docs#4265]
The note about the Session Monitor should read "and current date" not "and current data".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6210c109-cc8c-3516-65f0-ba165d891f8c
* Version Independent ID: 2affb6d6-6b5c-02a2-50f7-d4b609599168
* Content: [Basic navigation in DTA - SQL Server](https://docs.microsoft.com/en-us/sql/tools/dta/lesson-1-basic-navigation-in-database-engine-tuning-advisor?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/dta/lesson-1-basic-navigation-in-database-engine-tuning-advisor.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/dta/lesson-1-basic-navigation-in-database-engine-tuning-advisor.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@cbigenwald-edt -- thank you for letting us know.  I am looking into this document.
