### ISSUE TITLE
msdb.dbo.sp_add_jobschedule: Anomaly when server under load

### ISSUE THREAD

**Issue by Alocyte** [MicrosoftDocs/sql-docs#4266]
Please note: sometimes executing sp_add_jobschedule with a time not in the future, the schedule will be Enabled=0 despite being created with Enabled=1.
The job will be enabled, but will never fire, as the schedule is not active.

Sometimes this bites you because you add (for example) 10 seconds to GETDATE() for determining @active_start_time but the SQLAgent processes the command too late, and the job is created after the margin you added covers... and your job looks good to go but never goes. 

This can occur when you hardware / VM is sluggish due to operations on the VM level, or operating system... 
The SQL Agent / SQL Server logs do not indicate the time the job is created, nor the values in the parameters used to create the job... and no error is recorded despite what you get not matching what you specify. 

I have tested this by creating a new Job. Then adding a schedule to it.

> USE [msdb]
GO

/****** Object:  Job [Test]    Script Date: 2020-03-04 08:34:48 ******/
BEGIN TRANSACTION
DECLARE @ReturnCode INT
SELECT @ReturnCode = 0
/****** Object:  JobCategory [[Uncategorized (Local)]]    Script Date: 2020-03-04 08:34:49 ******/
IF NOT EXISTS (SELECT name FROM msdb.dbo.syscategories WHERE name=N'[Uncategorized (Local)]' AND category_class=1)
BEGIN
EXEC @ReturnCode = msdb.dbo.sp_add_category @class=N'JOB', @type=N'LOCAL', @name=N'[Uncategorized (Local)]'
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback

END

DECLARE @jobId BINARY(16)
EXEC @ReturnCode =  msdb.dbo.sp_add_job @job_name=N'Test', 
		@enabled=1, 
		@notify_level_eventlog=0, 
		@notify_level_email=0, 
		@notify_level_netsend=0, 
		@notify_level_page=0, 
		@delete_level=0, 
		@description=N'Test', 
		@category_name=N'[Uncategorized (Local)]', 
		@owner_login_name=N'setup', @job_id = @jobId OUTPUT
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
/****** Object:  Step [Test]    Script Date: 2020-03-04 08:34:50 ******/
EXEC @ReturnCode = msdb.dbo.sp_add_jobstep @job_id=@jobId, @step_name=N'Test', 
		@step_id=1, 
		@cmdexec_success_code=0, 
		@on_success_action=1, 
		@on_success_step_id=0, 
		@on_fail_action=2, 
		@on_fail_step_id=0, 
		@retry_attempts=0, 
		@retry_interval=0, 
		@os_run_priority=0, @subsystem=N'TSQL', 
		@command=N'exec sp_helpdb', 
		@database_name=N'master', 
		@flags=0
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
EXEC @ReturnCode = msdb.dbo.sp_update_job @job_id = @jobId, @start_step_id = 1
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
EXEC @ReturnCode = msdb.dbo.sp_add_jobserver @job_id = @jobId, @server_name = N'(local)'
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
COMMIT TRANSACTION
GOTO EndSave
QuitWithRollback:
    IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION
EndSave:
GO

Then forced a "delayed time" for a schedule:
DECLARE 
@RunTime DateTime = GETDATE(),
@YYYYMMDD INT,
@HHMMSS INT,
@JobName VARCHAR(200) = 'Test',
@RC BIT

			SET @RunTime = dateadd(ss, -10, GETDATE())

			SELECT 
			@YYYYMMDD = CONVERT(VARCHAR(8), @RUNTIME, 112), 
			@HHMMSS =	CONVERT(VARCHAR(2),RIGHT( '0' + CONVERT(VARCHAR(2), DATEPART(HOUR  ,@RUNTIME)),2))	+	
						CONVERT(VARCHAR(2),RIGHT( '0' + CONVERT(VARCHAR(2), DATEPART(MINUTE,@RUNTIME)),2))	+	
						CONVERT(VARCHAR(2),RIGHT( '0' + CONVERT(VARCHAR(2), DATEPART(SECOND,@RUNTIME)),2))

EXEC @RC = msdb.dbo.sp_add_jobschedule
				@job_name = @JobName,
				@enabled = 1, /* Enabled = 1, Disabled = 0 */
				@name = @JobName,
				@freq_type = 1, /* ONCE ONLY */
				@active_start_date = @YYYYMMDD,
				@active_start_time = @HHMMSS

EXEC MSDB.dbo.sp_help_jobschedule NULL, @JobName, @JobName, NULL

--EXEC MSDB.dbo.sp_delete_jobschedule NULL, 'Test','Test'

So you can see, despite @Enabled=1 being called, @Enabled=0 results, and no record is recorded in a log advising the inconsistency.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ddb0cb-63f9-16ad-6f58-4f93cdee5e80
* Version Independent ID: 842e6e4d-adcb-279a-55c9-c0ce125e9a9d
* Content: [sp_attach_schedule (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-attach-schedule-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-attach-schedule-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-attach-schedule-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@Alocyte -- thank you for your detailed feedback.  It looks like you've encountered an issue with the product itself, rather than the documentation.  Please add your information here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)


cc @stevestein for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by Alocyte** [comment]
Hi everyone

This is not included in the documentation.
The product will not be changing and no mention is made of this particular quirk.
Documentation explains how a product behaves.
Please include this information to avoid people being ignorant of the nature of the product.


Regards
Victor Brink
Database Administrator | VIADATA (pty) ltd
tel: +27 21 674 3682 | cell: +27 83 718 3701 |email: victor@viadata.co.za<mailto:victor@viadata.co.za> |
www.viadata.co.za<http://www.viadata.co.za/>

**Comment by Alocyte** [comment]
@stevestein Wondering where I log a complaint that when responding to the email received, my email address is published, and a link exposed which interacts with my profile settings (unsubscribe to notifications).
