### ISSUE TITLE
Should apply to Azure Synapse Analytics (SQL DW) as well

### ISSUE THREAD

**Issue by meken** [MicrosoftDocs/sql-docs#4269]
According to https://azure.microsoft.com/en-us/blog/announcing-the-general-availability-of-query-store-for-azure-sql-data-warehouse/ the Query Store is available for Azure Synapse Analytics as well, however, when I follow the link from that article, I land on this page with the warning that 'The requested page is not available for Azure Synapse Analytics. You have been redirected to the newest product version this page is available for.' and APPLIES TO doesn't list Azure Synapse Analytics (SQL DW) as a valid option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b587ab-50b8-eada-aa86-ba0c838c57ee
* Version Independent ID: f1fd2d52-b66f-4fbc-c54a-c688c4fd0f21
* Content: [Monitoring Performance By Using the Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-ver15&viewFallbackFrom=azure-sqldw-latest#feedback)
* Content Source: [docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@meken -- Murat, thank you for your feedback.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@julieMSFT -- please review the above-mentioned PR 14085.

**Comment by CarlRabeler** [comment]
@meken Thanks for reporting this - fixed
