### ISSUE TITLE
Typo: BYTE(1)

### ISSUE THREAD

**Issue by jerm014** [MicrosoftDocs/sql-docs#4270]
should be BIT(1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e8a50f-dd56-7b9e-58a8-7842710f9d1e
* Version Independent ID: d1d3e45f-f441-95ce-34a3-38faeebc0da6
* Content: [RESTORE HEADERONLY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/restore-statements-headeronly-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/restore-statements-headeronly-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/restore-statements-headeronly-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@jerm014 -- thank you for this feedback.

@MikeRayMSFT -- please confirm the above-mentioned PR 14018.
