### ISSUE TITLE
SSL Certificates

### ISSUE THREAD

**Issue by efilbert** [MicrosoftDocs/sql-docs#4272]
I ran into an issue with the instructions for the SSL certificates when using the procedure above.  Users and applications using the SERVER\Instance fail on connection.  To get past this, I registered the following SAN Names
Server,ServerFQDN,AG_Listener1,AG_ListenerFQDN,etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c76c2d8c-17da-8982-8a91-dd9968efa26e
* Version Independent ID: 2ecd127b-9f05-1f89-bcea-a93e8ded60eb
* Content: [Connect to an availability group listener - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@efilbert -- thank you for your feedback and suggested solution.

@MashaMSFT -- please look into this issue #4272.

**Comment by MashaMSFT** [comment]
Hi @efilbert , thanks for contacting Microsoft!

SAN = ServerFQDN should be all you need to ensure proper connectivity directly to the server name (though the listener values are important to connect to the listener). If that is insufficient, you may need to open a support ticket with Microsoft to determine if there are any other underlying causes preventing your connectivity. 

I hope that helps and please let us know if we can be of further assistance.

Thanks!
Masha from the SQL Docs team

**Comment by efilbert** [comment]
Masha -

With just the server name I cannot connect to AG_Listener or
AG_ListenerFQDN.  In an AG you sometimes need to connect to individual SQL
servers underlying the AG.  Only with the method I sent you was I able to
connect to every available SQL server.

**Comment by MashaMSFT** [comment]
Hi @efilbert, yes, to connect to the server name, you must have the servernamefqdn in the SAN, and to connect to the listener, you must have the listenerFQDN to connect to the listener. 

My apologies if that was not clear in my first comment :) 

You should not need to put the servername and listener name (without the fqdn) into the SAN, as DNS should be routing you to the correct destination based on the FQDN. If you're having to put the servername and listenername (without the fqdn) into the SAN to fix connectivity, you may have an underlying issue with your DNS. 

I hope that helps and please let us know if you have any additional questions.

Thanks!
Masha from the SQL Docs team

**Comment by efilbert** [comment]
I do not have an issue with my DNS and if I do not have the non-fqdn in SSMS an encrypted connection will fail and the error indicates ssl cert mismatch. Dns will follow the domain suffix search list for resolution but that does not change what is in the application’s connection window - hence the error   Browsers are exactly the same.

**Comment by MashaMSFT** [comment]
Hi @efilbert,

Are you saying that when you connect to your server name in SSMS,  you have to put the FQDN when you're using the SSL certificate? Otherwise, when you put just the server name, you're getting an SSL cert mismatch error? 

Thanks!
Masha from the SQL Docs team

**Comment by efilbert** [comment]
if I put SERVER\Instance into SSMS (which it does by default when opening
members of an AG) but the cert has both SERVERFQDN and InstanceFQDN, I get
the SSL Cert mismatch error.

**Comment by MashaMSFT** [comment]
Hi @efilbert , thanks for the additional clarity! The behavior that you're describing sounds atypical. When you have an SSL certificate, you should be able to connect to the instance with just SERVER\Instance, without having to provide the FQDN. Additionally, there should be no FQDN for the instance. 

For example, let's say you have the following:
Servername: Win2019
Instance: SQL2019
AG: AG2019
Listener: Listener2019
Domain: contoso.com

When you create your certificate, you should have the following:

CN: Win2019.contoso.com
SAN: Win2019.contoso.com, Listener2019.contoso.com

When you connect, you should be able to connect to the following values without specifying the fqdn:
Win2019\SQL2019
Listener2019

There is a small subset of customers that require the netbios in the SAN (as you have indicated), but it is rarely necessary. If you want to add the netbios, then your SAN will look like:

SAN: Win2019, Win2019.contoso.com, Listener2019, Listener2019.contoso.com

I'm hesitant to add the netbios to the documentation for the SAN as it's not typically a requirement and should only benefit a small subset of customers.

I hope that helps and please let me know if you have any further questions?

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @efilbert , I just wanted to check in with you - did this help address your question? Do you need anything further from us?

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
HI @efilbert , thanks again for bringing this to our attention! I have processed a change to the documentation that is live now that provides the same example as above. 

I hope that helps and please let us know if we can be of further assistance? I am going to close out this Git Issue, but please feel free to comment should you need anything further.

Thanks again and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
