### ISSUE TITLE
reject option example

### ISSUE THREAD

**Issue by LifeRyuto** [MicrosoftDocs/sql-docs#4273]
Hi
&gt;this time 25 rows succeed and 75 rows fail.
I think this results to 25%, but the document says 50%.
How do we calculate this? We should add percentages every time the calculation executed?

PolyBase attempts to retrieve the first 100 rows; 25 fail and 75 succeed.
Percent of failed rows is calculated as 25%, which is less than the reject value of 30%. As a result, PolyBase will continue retrieving data from the external data source.
PolyBase attempts to load the next 100 rows; this time 25 rows succeed and 75 rows fail.
Percent of failed rows is recalculated as 50%. The percentage of failed rows has exceeded the 30% reject value.
The PolyBase query fails with 50% rejected rows after attempting to return the first 200 rows. Notice that matching rows have been returned before the PolyBase query detects the reject threshold has been exceeded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ac2fe2-31da-7db6-2d5f-5091022f41d2
* Version Independent ID: bbf07c2c-7006-7b94-f12f-800fa7bc67e4
* Content: [CREATE EXTERNAL TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-table-transact-sql?view=azure-sqldw-latest)
* Content Source: [docs/t-sql/statements/create-external-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@LifeRyuto -- Ryuto, thank you for your questions.

@CarlRabeler -- Carl, please look into this issue #4273.

**Comment by CarlRabeler** [comment]
@LifeRyuto The article is saying that the first 100 had a 25% failure rate. The second 100 had a 75% failure rate. Combined, this is 50% failure rate for the first 200 rows. This is the 50% that the article is talking about

**Comment by LifeRyuto** [comment]
@CarlRabeler Thank you for your answer. I misunderstood that the percentage is a success rate. It's ok to close this issue.

**Comment by CarlRabeler** [comment]
@LifeRyuto easy to do - glad I could be of assistance
