### ISSUE TITLE
Inverted queries

### ISSUE THREAD

**Issue by eduardomb08** [MicrosoftDocs/sql-docs#4274]
The queries for topics "To view the objects that depend on a table" and "To view the objects on which a table depends" seem to be inverted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1d9a706-27a6-b00f-6e5b-3f7f548a2f4a
* Version Independent ID: d99fd464-baea-24b8-30d7-2cbdb36981a8
* Content: [View the Dependencies of a Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/view-the-dependencies-of-a-table?view=sql-server-ver15#TsqlProcedure)
* Content Source: [docs/relational-databases/tables/view-the-dependencies-of-a-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/view-the-dependencies-of-a-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@eduardomb08 -- Eduardo, thank you for your feedback.

@stevestein -- Steve, please look into this issue #4274.

**Comment by stevestein** [comment]
@eduardomb08 - thanks for the feedback. Looks like this was updated in https://github.com/MicrosoftDocs/sql-docs-pr/pull/14608

Thanks

#please-close
