### ISSUE TITLE
Does any special persmissions required to call this function?

### ISSUE THREAD

**Issue by GITAhmad123** [MicrosoftDocs/sql-docs#4275]
[Enter feedback here]
Does any special persmissions required to call this function?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4afba28-0b2a-638a-df33-7fc462631a0d
* Version Independent ID: 521f25ca-39d4-3c07-3e97-9ba6942fdb49
* Content: [DATABASE_PRINCIPAL_ID (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/database-principal-id-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/database-principal-id-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/database-principal-id-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @GITAhmad123! Thanks for your inquiry. As long as the user has access to the database, they should be able to run this function. There are no other permissions needed. Thanks!
