### ISSUE TITLE
Typo I believe for Input Parameter Options

### ISSUE THREAD

**Issue by lawrensmith** [MicrosoftDocs/sql-docs#4276]
Where the document describes the /Properties option for Input parameters, the explanation text suggests to use the list of Publish property names instead of input.

Example: sqlpackage.exe /Action:Publish /?.
should be
Example: sqlpackage.exe /Action:Import /?.

I believe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage.exe - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage.md)
* Product: **sql**
* Technology: **ssdt**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by WilliamAntonRohm** [comment]
@lawrensmith -- thank you for your question.

@pensivebrian -- please look into this issue #4276.

cc @rothja as a writer

**Comment by CarlRabeler** [comment]
@lawrensmith good catch - fixed and several related ones as well. Thanks.
Carl
