### ISSUE TITLE
Pitfall using OPENROWSET as Remote Execution to Insert and return Inserted ID

### ISSUE THREAD

**Issue by Alocyte** [MicrosoftDocs/sql-docs#4278]
The power of SQL Server / SQLNCLI connections with a connection string and Dynamic SQL capability allows for great creativity - BUT beware! Not all is as it seems.  Refer https://www.sqlservercentral.com/forums/topic/call-a-insert-procedure-with-openrowset
If you are using OpenRowset to return a PrimaryKey from a row you inserted remotely - you get the values but if you are not careful - the data is not persisted!
The information in the link is still valid, and is from 2013.
Try execute the following a single command at a time[, else the Query Analyser fails to parse the SQL and the statement causes an error.]

SELECT * FROM OPENROWSET(
'SQLNCLI11', 
'Server=LocalHost;trusted_connection=Yes;Integrated Security=SSPI',
'Insert into Tempdb.dbo.TempT (RunDate) 
	OUTPUT INSERTED.* 
	SELECT CONVERT(DATETIME, GETDATE()) EventDate')

SELECT * FROM  TempDB.dbo.TempT 

DROP TABLE tempdb.dbo.TempT

There is a way to perpetuate the data:

CREATE TABLE TempDB.dbo.TempT (ID INT IDENTITY(1,1) PRIMARY KEY, RUNDATE DATETIME)

SELECT * FROM OPENROWSET(
'SQLNCLI11', 
'Server=LocalHost;trusted_connection=Yes;Integrated Security=SSPI',
'Insert into Tempdb.dbo.TempT (RunDate) 
	OUTPUT INSERTED.* 
	SELECT CONVERT(DATETIME, GETDATE()) EventDate; commit')

SELECT * FROM  TempDB.dbo.TempT 

DROP TABLE tempdb.dbo.TempT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8339bb92-236a-4ae2-39ed-1207bead3cba
* Version Independent ID: 71aab847-7d4e-083f-127d-dc3833451ca5
* Content: [Use BULK INSERT or OPENROWSET(BULK...) to import data to SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/import-bulk-data-by-using-bulk-insert-or-openrowset-bulk-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/import-export/import-bulk-data-by-using-bulk-insert-or-openrowset-bulk-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/import-bulk-data-by-using-bulk-insert-or-openrowset-bulk-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@Alocyte -- thank you for your detailed feedback.

@markingmyname -- please look into this issue #4278.

**Comment by CarlRabeler** [comment]
@Alocyte it is not clear to me that this is a documentation issue or a product bug. We will need to investigate further - and this may take some time

**Comment by Alocyte** [comment]
@CarlRabeler No rush, mate. 
The article on SQLServerCentral I quote, was created January 15, 2013 at 5:12 am

**Comment by CarlRabeler** [comment]
also with no response as to why 'commit" was needed

**Comment by Alocyte** [comment]
@CarlRabeler Indeed - this is the critical aspect. Most peculiar. A commit, for an atomic implicit transaction? Spooky stuff.

**Comment by markingmyname** [comment]
@Alocyte,

This seems to be a bug. 

Thanks for the feedback! However, this area is primarily for doc issues. To report product issues, the best way to reach out to the SSMS Team is at [UserVoice](https://feedback.azure.com/forums/908035-sql-server).

They can give you better guidance.

If you do file a UV comment, please feel free to add it back to this conversation.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
