### ISSUE TITLE
percent_complete field is very-very-very misleading

### ISSUE THREAD

**Issue by beckandwhite** [MicrosoftDocs/sql-docs#4280]
My humble recommendation is to call it like something else until it is not real percentage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b04de445-400e-849b-cd9e-234f3bf1b088
* Version Independent ID: 23b5e022-eac1-7a0d-43d0-0964bd8e2a5e
* Content: [sys.dm_operation_status (Azure SQL Database) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-operation-status-azure-sql-database?view=azure-sqldw-latest#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-operation-status-azure-sql-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-operation-status-azure-sql-database.md)
* Service: **sql-database**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@beckandwhite -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task.
