### ISSUE TITLE
Filter by editions - consistent and concise presentation

### ISSUE THREAD

**Issue by ite-klass** [MicrosoftDocs/sql-docs#4281]
When evaluating editions after an initial overview it will be between only a subset of two or three editions.

The varying column width size, many editions, and varying first column width make this unnecessarily hard for how much data there is here; how many tables and how much to compare.

It would be very helpful to be able to hide those editions you are not interested in (e.g. the two express editions) for a more consistent and more concise presentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d663fffb-d444-59c0-714f-433cf91980c4
* Version Independent ID: ee6da2f6-9ab0-792c-8a5d-d3c725779669
* Content: [Editions and supported features of SQL Server 2019 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-version-15?view=sql-server-ver15)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-version-15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-version-15.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@ite-klass -- Jan, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue #4281.

**Comment by CarlRabeler** [comment]
@ite-klass I know that there is a lot of information here. However, I am not sure how to eliminate it. I would love to know your ideas how to accomplish what you suggest.

**Comment by ite-klass** [comment]
My suggestions are:

1. Make sure column widths remain the same across tables (styling)
2. Implement a filter functionality that allows displaying only a subset of editions across tables

I understand that this may not be supported currently in this documentation engine. Still this page especially could make a lot of use of them.

The limited page width and varying/auto column width allows for these to occur. Changing these could improve the situation as workarounds.

**Comment by CarlRabeler** [comment]
@ite-klass within the limits of markdown, please see new version that will be live tomorrow

**Comment by ite-klass** [comment]
@CarlRabeler So what changed? What should I be looking for? The file source was not modified. And I can not see any very obvious changes (without the before as a reference).

**Comment by CarlRabeler** [comment]
@ite-klass it will go live in the 9:00 AM publishing schedule and be visible within about an hour

**Comment by CarlRabeler** [comment]
columns aligned and streamlined to better fit smaller screen sizes. Multi-select in a filter is not feasible and filtering to a single edition would not allow comparisons - which I think would be a regression.

**Comment by ite-klass** [comment]
The point of a filter would be to compare a subset of editions not to only display a single one.

**Comment by ite-klass** [comment]
I see it is not completely aligned still but I have no comparison to how it was before. It doesn’t seem too bad [right] now. I feel like it probably improved.

Feel free to handle this ticket how you see fit.

**Comment by ite-klass** [comment]
> will be live tomorrow

> 9:00 AM publishing schedule

I’m not in your time zone btw. so relative short term time references are ambiguous and at times misleading.
