### ISSUE TITLE
script installs Helm 2.0 but does not install Tiller

### ISSUE THREAD

**Issue by chrisadkin** [MicrosoftDocs/sql-docs#4282]
If you run the script successfully, then run helm versio, you will get back the fact it is version 2.0, but tiller is not installed. For all versions of Helm prior to version 3.0, the server side component, i.e. tiller must be deployed to the target cluster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b52c141e-1793-43bb-5a16-5d82c1eff988
* Version Independent ID: 93cbcb06-0108-3f1d-990d-b8ef8ad31756
* Content: [Deploy single node kubeadm cluster - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-script-single-node-kubeadm?view=sql-server-ver15#feedback)
* Content Source: [docs/big-data-cluster/deployment-script-single-node-kubeadm.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deployment-script-single-node-kubeadm.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @mihaelablendea
* Microsoft Alias: **mihaelab**

**Comment by WilliamAntonRohm** [comment]
@chrisadkin -- Chris, thank you for your feedback.

@mihaelablendea -- Mihaela, please look into this issue #4282.

cc @rothja as a writer

**Comment by MikeRayMSFT** [comment]
@chrisadkin we're reviewing this comment. Thank you for the feedback.

**Comment by mihaelablendea** [comment]
I updated the script and removed helm, it is not required for BDC.
