### ISSUE TITLE
ESU notifications?

### ISSUE THREAD

**Issue by chjone** [MicrosoftDocs/sql-docs#4284]
Is there a way for customers to receive notices when patches are available within the SQL Server registry portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3e29e8-6559-58d3-27a5-3c443bd76c94
* Version Independent ID: 37b33566-6d93-ca52-7f54-4101ddb3a332
* Content: [What are Extended Security Updates? - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-extended-security-updates?view=sql-server-ver15#feedback)
* Content Source: [docs/sql-server/end-of-support/sql-server-extended-security-updates.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/end-of-support/sql-server-extended-security-updates.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @chjone , thanks for contacting Microsoft! Let me do a bit of research for you :)

Thanks!
Masha from the SQL Docs team

**Comment by pmasl** [comment]
@WilliamAntonRohm please reach out to your TAM for further information on how we will be advertising ESU releases.

**Comment by chjone** [comment]
My TAMs are the ones asking me...

_______________________________________________
Typing with thumbs, please excuse brevity & typos.

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by pmasl** [comment]
Please have them reach out to me directly.

**Comment by MashaMSFT** [comment]
Hi @chjone , I am going to close out this Git Issue for now as having been answered, but please feel free to comment should you have any additional questions or need further assistance.

Thanks and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
