### ISSUE TITLE
Non-root user

### ISSUE THREAD

**Issue by michaelrp** [MicrosoftDocs/sql-docs#4285]
Are there any additional steps necessary to run the newer default container that uses the non-root user `mssql`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04922c04-a2da-186c-5946-1cc4d9a7447b
* Version Independent ID: 6e490885-cdd7-079a-0b3a-4688616b0954
* Content: [Deploy a SQL Server container with Azure Kubernetes Services (AKS) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/tutorial-sql-server-containers-kubernetes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-sql-server-containers-kubernetes.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
@michaelrp  - I'm checking with engineering.

**Comment by michaelrp** [comment]
@MikeRayMSFT - Thanks!

In the mean time, this seems to work in our Dockerfile:

```
FROM mcr.microsoft.com/mssql/server:2019-CU2-ubuntu-16.04

USER root

RUN chown -R 10001:0 /var/opt/mssql

USER mssql

CMD [ "/opt/mssql/bin/sqlservr" ]
```

**Comment by MikeRayMSFT** [comment]
[Run container as a different non-root user on the host](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-ver15#nonrootuser) appears to have the information.

**Comment by danvalero** [comment]
I can not make it work with the SQL 2019 image. It seems to be some issues as it is runing as non-root. The document @MikeRayMSFT mention works if you can execute commands directly in dockers but I can not find the way to do it in AKS
