### ISSUE TITLE
Azure SQL Database Compatibility

### ISSUE THREAD

**Issue by ZacharyVorwaller** [MicrosoftDocs/sql-docs#4287]
I believe this works in Azure SQL (V12+) according to https://docs.microsoft.com/en-us/sql/t-sql/functions/context-info-transact-sql?view=sql-server-ver15 and https://social.msdn.microsoft.com/Forums/azure/en-US/ae7dbd50-4aa6-493a-8f46-022d3e780dcc/alternatives-to-contextinfo-on-sql-azure?forum=ssdsgetstarted.  Can this be confirmed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bca0beb-4b86-7128-17d6-0654d75a8569
* Version Independent ID: d7258791-e167-0213-9705-c17215c5a27d
* Content: [SET CONTEXT_INFO (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-context-info-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/set-context-info-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-context-info-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@ZacharyVorwaller I do not understand. Are you asking if context-info is supported in Azure SQL Database? If so, the answer is yes - as indicated in the article. If you are asked something more, please provide additional clarity regarding your question. Thank you, Carl

**Comment by ZacharyVorwaller** [comment]
Carl,

Sorry if this is not the right place for this feedback but if you look at
the top of this page it has an X next to Azure SQL Database when it should
be a green check box.
https://docs.microsoft.com/en-us/sql/t-sql/statements/set-context-info-transact-sql?view=sql-server-ver15


Let me know if I am not clear, and it really isn't that big of a deal it's
just confusing and I spent a few hours looking up alternatives because I
didn't think it was going to work but then tested it and it seems to work
fine and then found it was supported.

Hope this helps,
Zachary
ᐧ

**Comment by CarlRabeler** [comment]
sorry - my bad. I clicked the link for Context_Info that was referred to in this git issue - which was marked correctly - and did not look at Set_Context_Info. Fixing now - thank you
