### ISSUE TITLE
Does an executed command wait for triggers to complete

### ISSUE THREAD

**Issue by haymansfield** [MicrosoftDocs/sql-docs#4295]
It would be useful if the document confirmed whether when a command is executed by an external application (e.g. an EF Core call) the response is only sent once trigger execution has completed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8add50-414a-a033-6fc0-84de1c7735f2
* Version Independent ID: 8f2f3149-7035-b3d4-6f09-a6eadd015e24
* Content: [CREATE TRIGGER (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-trigger-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-trigger-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-trigger-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@haymansfield -- thank you for your question.

@CarlRabeler -- please look into this issue #4295.

**Comment by CarlRabeler** [comment]
@haymansfield Can you please provide me an example scenario? What type of trigger are you asking about?

**Comment by srutzky** [comment]
@haymansfield (and @CarlRabeler ): Triggers in SQL Server execute synchronously in the operation that triggered them. Triggers are part of the transaction, whether explicit or auto-commit, that is the operation being performed. This should include DDL and LOGON triggers as well as DML triggers. This is how/why you are able to cancel an operation (even a log in) by calling `ROLLBACK` in the trigger.


Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

**Comment by haymansfield** [comment]
@srutzky Thanks very much for the answer.

**Comment by srutzky** [comment]
> @srutzky Thanks very much for the answer.

You're quite welcome. Were you able to test any scenarios, or did you just dangerously take my word for it? 😉  🙀 Just curious 😺
