### ISSUE TITLE
Incorrect Information : MDF only

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#4296]
It appears that the information that this DMV presents is not described accurately.  The page states "Returns space usage information for each file in the database."  That is false.  
I have a database with both a data and log file, and the return from this DMV only displays information regarding the MDF (Data) file.  
There is no log file (LDF) information provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f01bb1-33f0-7814-949e-988fc6fc475a
* Version Independent ID: f3033bc8-06da-2def-88fa-91a71eee73c4
* Content: [sys.dm_db_file_space_usage (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-file-space-usage-transact-sql?view=sql-server-ver15&source=docs)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-db-file-space-usage-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-db-file-space-usage-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by rothja** [comment]
Apologies for the delayed response. @CarlRabeler Could you please look into this issue? Thank you! #reassign:CarlRabeler

**Comment by CarlRabeler** [comment]
@LindaLF Thanks for your clarification. PR pending now. 
Carl
