### ISSUE TITLE
Example C not using variables

### ISSUE THREAD

**Issue by David0Son** [MicrosoftDocs/sql-docs#4297]
For Example C: 
1> :Setvar FirstName Gustavo
1> :Setvar LastName Achong
1> EXEC dbo.ContactEmailAddress $(Gustavo),$(Achong)
2> GO
This does not work

It should be
1> EXEC dbo.ContactEmailAddress $(FirstName),$(LastName)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57bb7336-951e-cab7-522e-abb98e7f7a54
* Version Independent ID: 339664c0-7de2-720a-d28d-49e38288a240
* Content: [Use the sqlcmd Utility - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/scripting/sqlcmd-use-the-utility?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/scripting/sqlcmd-use-the-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/sqlcmd-use-the-utility.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@David0Son -- thank you for your observation.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
