### ISSUE TITLE
Minor error when Description for column freq_relative_interval

### ISSUE THREAD

**Issue by NimbSTech** [MicrosoftDocs/sql-docs#4300]
The Description for column freq_relative_interval begins by saying:-
"When freq_interval occurs in each month, if freq_interval is 32".
This should read:-
"When freq_interval occurs in each month, if freq_type is 32".
ie: replace "freq_interval" with "freq_type" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c651dcc6-fcaf-9e56-7de0-1f735c249970
* Version Independent ID: 57a3657a-4e3e-1324-670c-da97fdd01fa8
* Content: [dbo.sysschedules (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/dbo-sysschedules-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-tables/dbo-sysschedules-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/dbo-sysschedules-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@NimbSTech -- thank you for catching this.  I'm looking into the document.
