### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by mwdarab** [MicrosoftDocs/sql-docs#4301]
For #3, please add a space after &gt; and -- in "&lt;namespaceName&gt;--"

It should be, "&lt;namespaceName&gt; --"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b11c2fe-4e4a-3379-1ba6-928fbc290e43
* Version Independent ID: 4ad1482b-ba6f-61ee-f7e2-6f5f8b9183d0
* Content: [Configure SQL Server master instance - Configure SQL Server master instance of Big Data Cluster](https://docs.microsoft.com/en-us/sql/big-data-cluster/configure-sql-server-master-instance?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/configure-sql-server-master-instance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/configure-sql-server-master-instance.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@mwdarab -- Mohammad, thank you for this catch.  I'm looking into this document.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
