### ISSUE TITLE
No?

### ISSUE THREAD

**Issue by jeffshumphreys** [MicrosoftDocs/sql-docs#4303]
Interesting.  Most product comparison sheets have "Yes" and "No".  But not here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbe4ef3a-6282-5c51-5810-c6d63f3a0e1b
* Version Independent ID: 6d655e24-fc84-aad0-2422-2451cfb1ad34
* Content: [What is Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/what-is.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/what-is.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@jeffshumphreys -- Jeff, thank you for your observation.  We are conserving ink  :^)

I am closing this issue now.  You are welcome to @ mention me for any followup, and we hope to hear from you again.
