### ISSUE TITLE
Transact-SQL debugger - This feature works with SSMS version 17.9.1 and earlier.

### ISSUE THREAD

**Issue by davepile** [MicrosoftDocs/sql-docs#4304]
It would be good to know how I am meant to debug SQL code ith the latest version of SSMS which apparently no longer includes the debugger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b6bda12-8647-257a-0cff-3e1753f24ef1
* Version Independent ID: 88cf6bd4-b860-e79e-50eb-6d7b6c5d0f45
* Content: [Transact-SQL debugger - T-SQL debugger](https://docs.microsoft.com/en-us/sql/ssms/scripting/transact-sql-debugger?view=sql-server-ver15#see-also)
* Content Source: [docs/ssms/scripting/transact-sql-debugger.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/transact-sql-debugger.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@davepile -- thank you for your feedback.

@markingmyname -- please look into this issue #4304.

**Comment by markingmyname** [comment]
Hi, @davepile 

We apologize for the delay in response.

There's SQL Profiler Trace now.

We apologize for any inconvenience and delays this might cause you.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
