### ISSUE TITLE
Documentation not clear on `Transferring ownership of a table`

### ISSUE THREAD

**Issue by saumyasuhagiya** [MicrosoftDocs/sql-docs#4305]
The following example modifies the schema HumanResources by transferring the table Address from schema Person into the schema.

It should be as below.

The following example modifies the schema HumanResources by transferring the table Address from schema Person into the `HumanResources` schema.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f606ee47-e635-c71e-2874-56d9e8938390
* Version Independent ID: 85d3a27d-3001-c27b-e0c8-47cc10fede97
* Content: [ALTER SCHEMA (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-schema-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/alter-schema-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-schema-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@saumyasuhagiya Thank you - fixing now. 

FYI - you can also click Edit in the upper right hand corner of an article and submit this kind of change directly - which will come to me for review.
