### ISSUE TITLE
Please link to Geometry equivalent

### ISSUE THREAD

**Issue by crpage** [MicrosoftDocs/sql-docs#4306]
On the Geometry page there is a helpful link
ShortestLineTo (geography Data Type)

Please add these so we can go from Geography (which is where F1 (Help) takes us) to the method on the Geometry data type

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5b517d-c3a0-08d0-197f-dd2d6b7036db
* Version Independent ID: 964962a7-356e-b8bc-7f99-38b0a79737b4
* Content: [ShortestLineTo (geography Data Type) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geography/shortestlineto-geography-data-type?view=sql-server-ver15)
* Content Source: [docs/t-sql/spatial-geography/shortestlineto-geography-data-type.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/spatial-geography/shortestlineto-geography-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@crpage -- thank you for your suggestion.  I am looking into this article.
