### ISSUE TITLE
2 Headers "Syntax"

### ISSUE THREAD

**Issue by luis-flores** [MicrosoftDocs/sql-docs#4307]
In this page there are two headers labeled "Syntax". This also appears duplicated in the "In this article" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8add50-414a-a033-6fc0-84de1c7735f2
* Version Independent ID: 8f2f3149-7035-b3d4-6f09-a6eadd015e24
* Content: [CREATE TRIGGER (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-trigger-transact-sql?view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/t-sql/statements/create-trigger-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-trigger-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@luis-flores -- Luis, thank you for catching that.  I am looking into the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
