### ISSUE TITLE
Phrasing in INSTEAD OF

### ISSUE THREAD

**Issue by luis-flores** [MicrosoftDocs/sql-docs#4308]
In the explanation for "INSTEAD OF" the following appears: "You can't define INSTEAD OF triggers on updatable views that use WITH CHECK OPTION. SQL Server Doing so results in an error when an INSTEAD OF trigger is added to an updatable view WITH CHECK OPTION specified."

It looks to me that "SQL Server" should not be there, and it should be written as: "... on updatable views that use WITH CHECK OPTION. Doing so ..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8add50-414a-a033-6fc0-84de1c7735f2
* Version Independent ID: 8f2f3149-7035-b3d4-6f09-a6eadd015e24
* Content: [CREATE TRIGGER (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-trigger-transact-sql?view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/t-sql/statements/create-trigger-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-trigger-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@luis-flores -- Luis, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
