### ISSUE TITLE
The article link for Trace Flag 1148 returns a 404 error

### ISSUE THREAD

**Issue by rlDawsonShaper** [MicrosoftDocs/sql-docs#4309]
The link for trace flag 1448:

https://support.microsoft.com/kb/937041

Returned a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0e35dc1-14be-0678-aeae-88de1c7601ac
* Version Independent ID: b3700e3e-acbf-9248-c333-ac9013827d84
* Content: [Trace Flags (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by rlDawsonShaper** [comment]
Correction, that is tf 1448.

**Comment by pmasl** [comment]
Thank you, I've requested for the link to be reactivated.

**Comment by pmasl** [comment]
#please-close

**Comment by JanosBerke** [comment]
It still returns http 404. Please re-open! Thanks!
