### ISSUE TITLE
Tutorial Links to incorrect file

### ISSUE THREAD

**Issue by gdiddy44** [MicrosoftDocs/sql-docs#4310]
On page 
https://docs.microsoft.com/en-us/sql/tutorials/enterprise-information-management-using-ssis-mds-and-dqs-together-%5Btutorial%5D?view=sql-server-2014

the link 'Download the Suppliers.xls file from Microsoft Download Center.' links to a PDF which is not part of the tutorial.  That file is the basis for most of the tutorial.

**Comment by WilliamAntonRohm** [comment]
@gdiddy44 -- Gee, thank you for your feedback.

@lrtoyou1223 -- Leo, please look into this issue #4310.

cc @rothja as a writer

**Comment by rothja** [comment]
@gdiddy44 Apologies for the long delay. At this time, I can not find that tutorial online, so I am assuming that it must have been retired or taken down? @lrtoyou1223 Leo, please correct me if that is not the case. As the article is not reachable, I will be closing this git issue, but please reach out to me if there is more to research or correct in this case. Thank you! #reassign:rothja

**Comment by DavidEPatrick** [comment]
The tutorial is still up and the file is still missing. 

https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/jj819782(v=sql.110)
