### ISSUE TITLE
OLE DB is supported again

### ISSUE THREAD

**Issue by David-Engel** [MicrosoftDocs/sql-docs#4311]
On this page: https://docs.microsoft.com/en-us/sql/integration-services/import-export-data/connect-to-a-sql-server-data-source-sql-server-import-and-export-wizard?view=sql-server-ver15#connect-to-sql-server-with-the-microsoft-ole-db-provider-for-sql-server-or-sql-server-native-client

There is a note about OLE DB not being supported after SQL Server 2012. Well it was undeprecated and a new Microsoft OLE DB Driver for SQL Server was released in March of 2018.
https://docs.microsoft.com/en-us/sql/connect/connect-history?view=sql-server-ver15#ole-db

The note should be removed or updated to reflect that. Ideally, the section would be updated to include the same OLE DB information as is there for ODBC. But removing/updating the note is a good first step since SQL Server 2019 does ship with and supports the new OLE DB driver.

**Comment by WilliamAntonRohm** [comment]
@David-Engel -- thank you for your feedback.

@chugugrace -- please look into this issue #4311.

cc @rothja as a writer

**Comment by rothja** [comment]
@chugugrace Could you please take a look at David's suggestions here? Can you make the change in the documentation so we can close out this issue. Thank you!

**Comment by MikeRayMSFT** [comment]
I emailed @chugugrace
