### ISSUE TITLE
MSRC Portal Doesn't List SQL 2008 Anymore

### ISSUE THREAD

**Issue by scruffty** [MicrosoftDocs/sql-docs#4313]
Hi, the text above says:
ESUs are made available if needed, once a security vulnerability is discovered and is rated as Critical by the Microsoft Security Response Center (MSRC). Therefore, there is no regular release cadence for SQL Server ESUs.
if you look on the MSRC https://portal.msrc.microsoft.com/en-us/security-guidance under SQL the latest version it reports on is now Microsoft SQL Server 2012...there is no report for SQL 2008
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3e29e8-6559-58d3-27a5-3c443bd76c94
* Version Independent ID: 37b33566-6d93-ca52-7f54-4101ddb3a332
* Content: [What are Extended Security Updates? - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-extended-security-updates?view=sql-server-ver15#feedback)
* Content Source: [docs/sql-server/end-of-support/sql-server-extended-security-updates.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/end-of-support/sql-server-extended-security-updates.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@scruffty -- thank you for your feedback.

@MashaMSFT -- please look into this issue #4313.

**Comment by MashaMSFT** [comment]
Hi @scruffty , thanks for bringing this to our attention! Let me look into it :) 

Thanks!
Masha from the SQL Docs team

**Comment by scruffty** [comment]
Hi @MashaMSFT - they have now re-appeared so I'm guessing this is down to you? If so, thank you!!!
