### ISSUE TITLE
Link does not work sometimes

### ISSUE THREAD

**Issue by kaysauter** [MicrosoftDocs/sql-docs#4314]
I'm not sure why, but the link for "Supported SQL Server Versions in Replication Topology" in the note box (https://blogs.msdn.microsoft.com/repltalk/2016/08/12/suppported-sql-server-versions-in-replication-topology/) does only work sometimes. Sometimes, you'll get to a site saying "This site is no longer available." and other times, you get redirected to https://repltalk.com/2016/08/12/suppported-sql-server-versions-in-replication-topology/
This is easily reproducible by using "private modus" in browser.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab6b4b80-09aa-bd62-8f45-0c52235b2dd0
* Version Independent ID: 39e51ab8-0469-f8bb-d32a-96847b198229
* Content: [Tutorial: Prepare for replication - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/tutorial-preparing-the-server-for-replication?view=sql-server-ver15)
* Content Source: [docs/relational-databases/replication/tutorial-preparing-the-server-for-replication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/tutorial-preparing-the-server-for-replication.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by kaysauter** [comment]
If I see it correctly, this link should actually refer to this site: https://docs.microsoft.com/en-us/sql/relational-databases/replication/replication-backward-compatibility?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@kaysauter -- Kay, thank you for your feedback.

@MashaMSFT -- Masha, please look into this issue #4314.

**Comment by MashaMSFT** [comment]
Hi @kaysauter , thanks so much for bringing this to our attention! You're right, it should be the backwards compatibility link. I have processed a change to get this fixed and it should be live tomorrow. 

I will close out this Git Issue but please feel free to comment should you need anything further.

Thanks for improving our documentation and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
