### ISSUE TITLE
Information for SQL Server 2019 is missing

### ISSUE THREAD

**Issue by kaysauter** [MicrosoftDocs/sql-docs#4315]
The note box states that "Replication is not supported on SQL Server instances that are more than two versions apart" and refers to a website which does only mention 2016 as newest server. Is this still true for 2017 and 2019 - this is unfortunately not very clear. However, this site https://github.com/Microsoft/mssql-docker/issues/368 suggests that it could be possible to replicate from 2014 -> 2019 albeit there is SQL Server on linux (docker) in discussion.

**Comment by kaysauter** [comment]
If I see it correctly, the link about the topology should actually refer to this site: https://docs.microsoft.com/en-us/sql/relational-databases/replication/replication-backward-compatibility?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@kaysauter -- Kay, thank you for your feedback.

@MashaMSFT -- Masha, please look into this issue #4315.

**Comment by MashaMSFT** [comment]
Hi @kaysauter , thanks for contacting Microsoft! The compatibility matrix you've posted is correct - publishing to a SQL 2019 subscriber from a SQL 2014 publisher is unsupported. I believe Vin has retracted his statement in the comment you provided :) 

I hope that helps and please let us know if there's anything further we can assist you with? I'll close out this Git Issue for the time being but please feel free to comment should you have additional questions.

Thanks!
Masha from the SQL Docs team
