### ISSUE TITLE
LastGoodCheckDbTime "Applies to" may be misleading for 2017

### ISSUE THREAD

**Issue by tkwj** [MicrosoftDocs/sql-docs#4318]
The "Applies to" section for LastGoodCheckDbTime can be misleading or incorrect because it currently says "Starting with SQL Server 2016 (13.x) SP2". This gives the impression that it works on all versions of SQL Server 2017, including the RTM version.

This is not the case.  In my testing, this property does not return a result from 2017 RTM through 2017 CU8. 
SQL Server 2017 with CU9 does return a result as expected.

The text should read something like "Starting with SQL Server 2016 (13.x) SP2, SQL Server 2017 (14.x) CU9, and Azure SQL Database." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ca907e-99b6-3663-82bf-abe45f1ae76e
* Version Independent ID: 1acba411-593f-6cd2-7c76-8e35dbd8ac13
* Content: [DATABASEPROPERTYEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/databasepropertyex-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/databasepropertyex-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/databasepropertyex-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@tkwj -- Tom, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue #4318.

**Comment by MikeRayMSFT** [comment]
@tkwj - thanks for the feedback. Checking
