### ISSUE TITLE
ForceEncryption = True with no certificate specified

### ISSUE THREAD

**Issue by WHinDenver** [MicrosoftDocs/sql-docs#4319]
Two clarifications please:
1) By what method is the connection encrypted when the ForceEncryption is true but no certificate is configured, is it the self-signed certificate?  
2) The document uses the phrase "encrypted connection" but does not differentiate between the initial login connection and the ongoing state of the connection.  This is further confused by requiring the client to request encryption even when the server is set to force encrypted connection.  

I believe a chart may be the best way to explain when encryption is enabled, and by self-signed vs SSL, and by client request or by server forced.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa20275-e415-5531-3ef4-7472d859753b
* Version Independent ID: cc1346a6-9336-91ba-bcff-9fff79847c35
* Content: [Enable Encrypted Connections to the Database Engine - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@WHinDenver -- thank you for your question and feedback.

@VanMSFT -- please look into this issue #4319.

**Comment by VanMSFT** [comment]
Hello @WHinDenver! Thanks for submitting these questions. We're working to update or add more comprehensive connectivity articles to our docs. In the meantime, I will answer your questions here.

1. When no certificate is installed, and **Force Encryption** is set to `Yes`, the self-signed certificate will be used.
2. SQL Server will always encrypt the login phase of the connection. You can verify this in a network trace. The encryption option here is for the ongoing connection of the data transaction.

I hope that answers your question, but let me know if any clarification is needed. Thanks!
