### ISSUE TITLE
Creating Column Master Keys in Azure Key Vault - Using PowerShell

### ISSUE THREAD

**Issue by KrystinaWoelkers** [MicrosoftDocs/sql-docs#4320]
Hello! When I run this command all in one..

# Create a column master key in Azure Key Vault.
Connect-AzAccount
$SubscriptionId = "&lt;Azure subscription ID&gt;"
$resourceGroup = "&lt;resource group name&gt;"
$azureLocation = "&lt;key vault location&gt;"
$akvName = "&lt;key vault name&gt;"
$akvKeyName = "&lt;column master key name&gt;"
$azureCtx = Set-AzContext -SubscriptionId $SubscriptionId # Sets the context for the below cmdlets to the specified subscription.
New-AzResourceGroup -Name $resourceGroup -Location $azureLocation # Creates a new resource group - skip, if you desire group already exists.
New-AzKeyVault -VaultName $akvName -ResourceGroupName $resourceGroup -Location $azureLocation -SKU premium # Creates a new key vault - skip if your vault already exists.
Set-AzKeyVaultAccessPolicy -VaultName $akvName -ResourceGroupName $resourceGroup -PermissionsToKeys get, create, delete, list, update, import, backup, restore, wrapKey, unwrapKey, sign, verify -UserPrincipalName $azureCtx.Account
$akvKey = Add-AzureKeyVaultKey -VaultName $akvName -Name $akvKeyName -Destination HSM

the "Add-AzureKeyVaultKey" gives an error - if we switch to "Add-AZKeyVaultKey" it will work.

However we ran into another issue...
If the key vault is already existing, with all the proper permissions in place - I would assume we could just run 
"Add-AzureKeyVaultKey -VaultName &lt;name&gt; -Name &lt;name&gt; -Destination HSM"
but this fails. Not sure why...it seems to not like it if the vault already exists. We get a forbidden error. 

Any chance there is a tutorial walk through for setting up Always Encrypted with role separation in Azure Key vault using PowerShell? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc717e21-1e3c-35b0-26ee-901c41deb303
* Version Independent ID: 33167cb3-1a89-f9df-c561-f1e474b249c7
* Content: [Create & store column master keys for Always Encrypted - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/create-and-store-column-master-keys-always-encrypted?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/create-and-store-column-master-keys-always-encrypted.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/create-and-store-column-master-keys-always-encrypted.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@KrystinaWoelkers -- thank you for your feedback.

@jaszymas -- please look into this issue #4320.

**Comment by VanMSFT** [comment]
I'll follow-up with Jakub. Thanks!

**Comment by rothja** [comment]
Fixing assignees for reporting: #reassign:jaszymas

**Comment by rothja** [comment]
#assign:VanMSFT

**Comment by VanMSFT** [comment]
Hi @KrystinaWoelkers! Thank you for bringing this issue to our attention! I have fixed the typo with Add-AzKeyVaultKey.

Regarding the tutorial, we'll add that to our backlog, but you should be able to look at the [Windows Certificate Store with Role Separation (Example)](https://docs.microsoft.com/sql/relational-databases/security/encryption/configure-always-encrypted-keys-using-powershell?view=sql-server-ver15#windows-certificate-store-with-role-separation-example) and the [Azure Key Vault without Role Separation (Example)](https://docs.microsoft.com/sql/relational-databases/security/encryption/configure-always-encrypted-keys-using-powershell?view=sql-server-ver15#azure-key-vault-without-role-separation-example) to get what you need.

Thanks again!
