### ISSUE TITLE
Link to BLOG incorrect

### ISSUE THREAD

**Issue by ABloesch** [MicrosoftDocs/sql-docs#4321]
The article contains an incorrect forward link to the RBS BLOG https://go.microsoft.com/fwlink/?LinkId=210315

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da9da73-e904-c21c-ff0d-aa3057203510
* Version Independent ID: 6d9e3116-96ac-16e5-e398-4a274df81578
* Content: [Remote Blob Store (RBS) (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/blob/remote-blob-store-rbs-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/blob/remote-blob-store-rbs-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/blob/remote-blob-store-rbs-sql-server.md)
* Product: **sql**
* Technology: **filestream**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@ABloesch -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue #4321.

**Comment by MikeRayMSFT** [comment]
@ABloesch  -- thanks for letting us know. Checking this.

**Comment by MikeRayMSFT** [comment]
On closer inspection, the link on the docs page, returns me to the download page.

![image](https://user-images.githubusercontent.com/15928587/76798776-72a9c600-678d-11ea-9dde-7431b8ac03de.png)

**Comment by ABloesch** [comment]
Its this link that I am talking about:
The RBS blog<https://go.microsoft.com/fwlink/?LinkId=210315> provides additional information to help you understand, deploy, and maintain RBS.

Anthony—安大神
[cid:image001.png@01D5FC70.C7543920]
I am primary Incident Manager this week. Due to the COVID-19 outbreak, some of SOX will be working from home or remotely. Those in the office are under social distancing and health-check restrictions. Some team members are under travel restrictions and are unable to return to Suzhou and do not have laptops and SAW devices with them.

**Comment by ABloesch** [comment]
Its **this** link that I am talking about:
The **RBS blog** provides additional information to help you understand, deploy, and maintain RBS.

**Comment by KalleOlaviNiemitalo** [comment]
I get this chain of redirections: <https://go.microsoft.com/fwlink/?LinkId=210315> 302 Moved Temporarily <http://blogs.msdn.com/b/sqlrbs/> 301 Moved Permanently <https://docs.microsoft.com/archive/blogs/> 301 Moved Permanently <https://docs.microsoft.com/en-us/archive/blogs/>

The correct URL is <https://docs.microsoft.com/archive/blogs/sqlrbs/>. I think <http://blogs.msdn.com/b/sqlrbs/> should redirect there. This applies to many other blogs too. It was already reported in <https://github.com/MicrosoftDocs/feedback/issues/2384> but I get the impression that Microsoft does not want to set up a wildcard redirection. Until then, it would be good to edit the link in the SQL documentation.
