### ISSUE TITLE
Asterisks in Remarks section cause unintentional emphasis.

### ISSUE THREAD

**Issue by marked23** [MicrosoftDocs/sql-docs#4322]
There are a few instances where there are double-asterisks in the Remarks paragraph.  Two of them seem like typos, as they are invalid as SQL code, and unhelpful as markup for bold-text.

On a separate note, it might be helpful to indicate that this is an output formatting feature: 
"Returns (right-justified | decimal-aligned) character data converted from numeric data."
or
"Renders a numeric value into a right-justified string of a specified length and decimal precision.  Useful for aligning numeric values across multiple rows."   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 247290ac-9dcd-4647-05f0-d35d93aa1d21
* Version Independent ID: dc6acad9-85a3-366d-6f58-f432a5ca2376
* Content: [STR (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/str-transact-sql?view=sql-server-ver15#remarks)
* Content Source: [docs/t-sql/functions/str-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/str-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@marked23 -- thank you for your feedback.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- please review the above-mentioned PR 14092.
