### ISSUE TITLE
Changing the word subfolder to file

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#4326]
@ThomasKwakman commented on [Wed Mar 11 2020](https://github.com/MicrosoftDocs/sql-docs.fr-fr/issues/122)

Hi, I guess that there is a small mistake. In the **Arguments** section, in the paragraph before the diagram:
mydata3.txt because it's a **subfolder** of a hidden folder.
=> mydata3.txt because it's a **file** of a hidden folder.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f7ac2fe2-31da-7db6-2d5f-5091022f41d2
* Version Independent ID: bbf07c2c-7006-7b94-f12f-800fa7bc67e4
* Content: [CREATE EXTERNAL TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/fr-fr/sql/t-sql/statements/create-external-table-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-external-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/t-sql/statements/create-external-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

---

@srvbpigh commented on [Wed Mar 11 2020](https://github.com/MicrosoftDocs/sql-docs.fr-fr/issues/122#issuecomment-597515392)

Hello, @ThomasKwakman
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@CarlRabeler commented on [Wed Mar 11 2020](https://github.com/MicrosoftDocs/sql-docs.fr-fr/issues/122#issuecomment-597641971)

@ThomasKwakman @CeciAc @srvbpigh Thomas is correct. Please make the change.
Thank you Thomas

**Comment by WilliamAntonRohm** [comment]
@ThomasKwakman @CeciAc @srvbpigh -- I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
