### ISSUE TITLE
database should be repaired but won't repair (times out)

### ISSUE THREAD

**Issue by marc-gmail-towersap** [MicrosoftDocs/sql-docs#4328]
I am having issues with MDS configuration manager.  Am switching my database from local users/groups to AD users/groups by cloning the VM, and configuring the clone to use AD.  This worked fine, but in the meantime, the old machine had additional database changes.  So I figured I'd back up the cloned VM, restore the latest prod backup to the cloned VM, make some minor changes to database to switch groups from local to AD, and then I could theoretically shut down the original VM and tell everyone to use the new clone URL. 

So, we wanted to test it all out before actually doing it.

SO I did.  Seemed to work, only I used a backup of a few-day-old backup, 

Now, I needed to rollback the changes, using the restore of the cloned backup bak file.

So I did, it restored fine, no issues.

I did forget to change the app pool user's permissions (remember, the original was using a local user, the AD clone is using an AD user).  So when I tested it out, it got permissions problems.  No biggie, I granted it permissions.  

The website now works.  However, as a double-check, I looked at MDS Configuration manager.  I selected my database, and it says 'this database should be repaired'.  I click on it Repair database.... and it chunks and chunks and chunks along and.... times out.  tried again, times out again. and again. rebooted the VM, and still times out.  Made sure IIS was down, turned off a windows service as well that also accesses the db.  Still, it times out.

I ran dbcc opentran(), then exec sp_who2 &lt;spid&gt; and I see it's doing some delete (as the app pool user) (and it's suspended).  Not sure why it would be doing a delete at all.  but it times out...

any help/clues? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c767b8a9-9b93-2af4-5bd4-568ad5e5c080
* Version Independent ID: 8ee958ea-2b12-3684-283a-8be6168f2e41
* Content: [Upgrade Master Data Services - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/upgrade-master-data-services?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/install-windows/upgrade-master-data-services.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/upgrade-master-data-services.md)
* Product: **sql**
* Technology: **master-data-services**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @marc-gmail-towersap , thank you for contacting Microsoft! I really wish I could help but unfortunately this forum is intended for issues specifically with the documentation, and not issues encountered while using the product :(

To get further assistance with your issue, we'd recommend engaging the community, or opening a ticket with Microsoft Support. More information can be found here: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

Our apologies that the SQL Docs team was unable to assist you further with your issue, but we appreciate you reaching out. Please let us know if there's anything more we can do for you.

Thanks again and hope you have a wonderful rest of your day!
Masha from SQL Docs team

**Comment by marc-gmail-towersap** [comment]
never mind, the problem was it was replaying the stuff out of the transaction logs.  for some reason, our logs are freakin huge.

**Comment by MashaMSFT** [comment]
Hi @marc-gmail-towersap , awesome, thanks for the clarification! It's good to have this documented for others that may run into a similar issue :) 

Thanks again!
Masha from the SQL Docs team
