### ISSUE TITLE
Sys.databases - Missing info about col [physical_database_name]

### ISSUE THREAD

**Issue by Trovalo** [MicrosoftDocs/sql-docs#4333]
In the docs about sys.databases, the column **[physical_database_name]** is not listed in the docs. 
The column meaning is clear but it would be handy to see in which version it has been introduced. 

For what I've found so far it exists only in SQL Server 2019 and in Azure SQL DB

**Comment by WilliamAntonRohm** [comment]
@Trovalo -- Giovanni, thank you for your feedback.  Are you referring to [this article](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-databases-transact-sql?view=sql-server-ver15)?

@stevestein -- Steve, please look into this issue #4333.

**Comment by Trovalo** [comment]
Yes, that's the page (sry for not adding the link myself)

**Comment by stevestein** [comment]
@Trovalo - thanks for the feedback. 

You are correct, the physical_database_name column is new for SQL 2019.

#please-close
