### ISSUE TITLE
Small error on page FYI

### ISSUE THREAD

**Issue by holly-searchengineunity** [MicrosoftDocs/sql-docs#4334]
"There is nothing a graph database can achieve, "
I think you might want this to instead say : "There is nothing a graph database can't achieve, "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a893981-46bb-c010-6d63-39eee88dcf91
* Version Independent ID: 8bacd3f7-6793-3316-6a31-3e599d209821
* Content: [Graph processing - SQL Server and Azure SQL Database](https://docs.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-overview?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/graphs/sql-graph-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/graphs/sql-graph-overview.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @shkale-msft
* Microsoft Alias: **shkale**

**Comment by WilliamAntonRohm** [comment]
@holly-searchengineunity -- thank you for catching that.  I am looking into that article.

**Comment by WilliamAntonRohm** [comment]
@holly-searchengineunity -- that phrase was correct in the sentence, however, it was in a negative-logic construction.  I have updated that paragraph.

@shkale-msft -- please review the above-mentioned PR 14122.

cc @rothja as a writer

**Comment by holly-searchengineunity** [comment]
Yes it was correct in the context of the sentence. However on first glance
I didn’t make it past the comma shocked at what it said before. As a
developer I am looking for good information very quickly if not for the
fact this was a Microsoft page that would have been my read depth and I
would have moved on dismissing it as either bad information or influenced
by marketing. Recently I was at your ignite conference in Toronto and I was
happy to see that all of the Azure workshops I attended were not marketing
for used but dev focused and so I thought I should bring this to your
attention.

Best,
Holly

**Comment by WilliamAntonRohm** [comment]
@holly-searchengineunity -- Holly, thank you for your considered feedback.  I'll pass it along!
