### ISSUE TITLE
LocalDB is only listed if Edition != Developer

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/sql-docs#4336]
Please update the doc to state that the edition must be `Express` (or Enterprise) in order for LocalDB to be listed in the features list.

P.S.
Why??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea66ca27-e0b1-cd1e-a8ef-55911169c71a
* Version Independent ID: f2340ce9-9771-851e-60a7-237c6e55f085
* Content: [SQL Server Express LocalDB - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15#install-localdb)
* Content Source: [docs/database-engine/configure-windows/sql-server-express-localdb.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/sql-server-express-localdb.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @abatishchev , thanks for bringing this to our attention! Let me do some research :) 

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @abatishchev , thanks for your patience as we I looked into this for you! I was able to confirm the following behavior:

•	Other than directly downloaded, LocalDB is only directly exposed as an installable edition/shared feature in Express with Advanced Services
•	It is not exposed as an installable shared feature in any other edition
•	However, during the Enterprise media Setup operation there is a drop down where one can choose to enter either a Product Key (pre-filled in for paid edition media, such as Enterprise), or select and install a Free edition (using the Enterprise media).
o	A free edition can be Evaluation, Express, or Developer.
•	If Express is selected, during installation the user can request to install LocalDB as a shared feature

Therefore, it technically is possible to install LocalDB from the Enterprise (pre-PID) media.  However, you cannot directly install LocalDB as a shared feature while installing Enterprise.  Nor is sqllocaldb.msi installed on the machine while installing all available features during an Enterprise installation.

So the documents are correct in stating that only Express with Advanced services media supports the installation of LocalDB. 

I hope that helps and please let me know if you have any further questions?

Thanks!
Masha from the SQL Docs team

**Comment by abatishchev** [comment]
Hi Masha,
Thanks for coming back on this!

I was facing this issue (no option to install LocalDB) when have chosen Edition=Developer on the first page of the installation wizard.

**Comment by MashaMSFT** [comment]
Hi @abatishchev , awesome, does this mean you were able to find it in the Express with Advanced edition? Is there anything more we can assist you with?

Thanks!
Masha from the SQL Docs team

**Comment by abatishchev** [comment]
Can you please update the doc to clearly state that selecting neither Developer (what I don't understand; LovalDB *is* for developers) nor Enterprise (if I understood your correctly) would list LocalDB in the list? Does it mean that only selecting Standard would?

**Comment by MashaMSFT** [comment]
Hi @abatishchev , my apologies, I'm not sure I understand what the ask is. 

The second sentence of this article states explicitly:  It is available on SQL Server Express with Advanced Services.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @abatishchev , it's been some time since we've heard from you - does this mean your question was addressed? Is there anything more we could assist you with?

Thanks!
Masha from the SQL Docs team
