### ISSUE TITLE
Rich computations (preview)

### ISSUE THREAD

**Issue by mpMelnikov** [MicrosoftDocs/sql-docs#4337]
Are rich computations still in preview status? I can't find any info about it elsewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a7130ba-36cc-7733-8c95-7905fa186b4f
* Version Independent ID: 6adca6aa-fba3-b678-ae3c-44cbbe37af18
* Content: [Always Encrypted with secure enclaves - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-enclaves?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/always-encrypted-enclaves.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/always-encrypted-enclaves.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@mpMelnikov -- Mikhail, thank you for your question.

@jaszymas -- please look into this issue #4337.

cc @rothja as a writer

**Comment by rothja** [comment]
Adding @VanMSFT. #assign:VanMSFT #unassign:rothja

**Comment by PRMerger10** [comment]
jaszymas is already assigned.

**Comment by VanMSFT** [comment]
Hi @mpMelnikov! Thanks for bringing this issue to our attention. Rich computation is no longer in preview status. We have fixed the doc. We really appreciate your assistance!
