### ISSUE TITLE
Which Ubuntu version is supported?

### ISSUE THREAD

**Issue by Ayrton007** [MicrosoftDocs/sql-docs#4338]
Here you write "You must have a Ubuntu 18.04" but the link leads to Ubuntu 16.04 LTS (Xenial Xerus). On the other page (https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup?view=sql-server-ver15) you write that supported version of Ubuntu is 16.04. So which one is roght? Please, answer and correct also the information on your pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-linux-ver15#feedback)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @Ayrton007! Thanks for pointing this out. Ubuntu 18.04 is supported starting with SQL Server 2019 CU3. This was released yesterday. I will fix the link, and update the docs. Thanks again!
