### ISSUE TITLE
Rich computations (preview)

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#4340]
@mpMelnikov commented on [Fri Mar 13 2020](https://github.com/MicrosoftDocs/sql-docs.ru-ru/issues/69)

Are rich computations still in preview status? I can't find any info about it elsewhere.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 1a7130ba-36cc-7733-8c95-7905fa186b4f
* Version Independent ID: 6adca6aa-fba3-b678-ae3c-44cbbe37af18
* Content: [Always Encrypted с безопасными анклавами. - SQL Server](https://docs.microsoft.com/ru-ru/sql/relational-databases/security/encryption/always-encrypted-enclaves?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/always-encrypted-enclaves.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/relational-databases/security/encryption/always-encrypted-enclaves.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

---

@srvbpigh commented on [Fri Mar 13 2020](https://github.com/MicrosoftDocs/sql-docs.ru-ru/issues/69#issuecomment-598624539)

Hello, @mpMelnikov
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by mpMelnikov** [comment]
Probably, this issue can be also closed as I've created the same issue for the English version 3 hours ago: https://github.com/MicrosoftDocs/sql-docs/issues/4337

**Comment by WilliamAntonRohm** [comment]
@mpMelnikov -- thank you Mikhail.
