### ISSUE TITLE
SRID 4326

### ISSUE THREAD

**Issue by gbjbaanb** [MicrosoftDocs/sql-docs#4342]
when using SRID 4326 (which is very commonly used for most purposes), what is the format for geometry_tagged_text? Is it ('lat,lng', 4326) or it is ('lng,lat', 4326).

I understand that it should be lng,lat according to WKT geometry, but as this would be unintuitive for anyone creating one without explicitly knowing the format (which is not easily found) then the calculatiosn will be wrong. Even if the points are all created consistently wrong, distances will be consistently wrong. 

You can check by calculating the distances using Haversine algorithm for example, which should be a couple of km out at worst.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e237a10d-a9ba-a5ff-c18f-203604f889ea
* Version Independent ID: cfe26ff5-5b8c-399c-f461-990a4a8d6481
* Content: [STGeomFromText (geometry Data Type) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geometry/stgeomfromtext-geometry-data-type?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/t-sql/spatial-geometry/stgeomfromtext-geometry-data-type.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/spatial-geometry/stgeomfromtext-geometry-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@gbjbaanb -- Andy, thank you for your thorough feedback.

@MladjoA -- Mladen, please look into this issue #4342.

cc @rothja as a writer

**Comment by KoenDelaere** [comment]
Think of LINESTRING(X1 Y1, X2, Y2, ...). It makes sense that X=long and Y=lat looking at the "front" of the world globe.

**Comment by MladjoA** [comment]
#please-close
