### ISSUE TITLE
Small issues on ALTER DATABASE statement

### ISSUE THREAD

**Issue by jgmreyes** [MicrosoftDocs/sql-docs#4345]
You left this unchecked.

ALTER DATABASE database_name
{
    <add_or_modify_files>
  | <add_or_modify_filegroups>
}
[;

Notice the open bracket before the semi colon.

**Comment by WilliamAntonRohm** [comment]
@jgmreyes -- thank you for catching that.  I am looking into the article.

**Comment by WilliamAntonRohm** [comment]
@jgmreyes -- I neglected to ask:  which docs.microsoft.com article are you referring to?

**Comment by jgmreyes** [comment]
Hi @WilliamAntonRohm , it's here

sql/t-sql/statements/alter-database-transact-sql-file-and-filegroup-options

Very first syntax displayed.

**Comment by WilliamAntonRohm** [comment]
@jgmreyes -- thank you.
