### ISSUE TITLE
Typo on setting env variable

### ISSUE THREAD

**Issue by MikeSpark** [MicrosoftDocs/sql-docs#4347]
bootstrap-sample-db.cmd has error 
DEFINED set set KNOX_PASSWORD=%AZDATA_PASSWORD%
should be just 
DEFINED set KNOX_PASSWORD=%AZDATA_PASSWORD%
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16adfeea-f75b-bd99-b9ae-44fe77e9c8d1
* Version Independent ID: 2c6e8c0d-4764-e6a1-e20c-8014a06264dd
* Content: [Load sample data - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-load-sample-data?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/big-data-cluster/tutorial-load-sample-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/tutorial-load-sample-data.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@MikeSpark -- thank you for catching that.  I am looking into the document.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- please review the above-mentioned [PR 754](https://github.com/microsoft/sql-server-samples/pull/754).
