### ISSUE TITLE
Using Table Aliases with "FOR SYSTEM_TIME"

### ISSUE THREAD

**Issue by JediSQL** [MicrosoftDocs/sql-docs#4348]
One of the example queries should be written to use a table alias, because it is not obvious where the "FOR SYSTEM_TIME &lt;SYSTEM TIME&gt; clause goes relative to the table name and the assigned alias.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 751e374d-cd64-1de5-c1d2-5c426c9534c9
* Version Independent ID: 2c62a70f-cd2e-bf40-5974-dde1b5a10efe
* Content: [Querying Data in a System-Versioned Temporal Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/querying-data-in-a-system-versioned-temporal-table?view=sql-server-ver15&source=docs)
* Content Source: [docs/relational-databases/tables/querying-data-in-a-system-versioned-temporal-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/querying-data-in-a-system-versioned-temporal-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by JediSQL** [comment]
OK, I finally found the one example. It is so densely formatted that it makes it hard to find when it is not the actual subject of the example. I guess you could technically say that you have it covered, but it would be more helpful if there were explicit instructional text.

**Comment by WilliamAntonRohm** [comment]
@JediSQL -- Dan, thank you for your feedback.  Please clarify which example you mean.

@CarlRabeler -- Carl, please look into this issue #4348.

**Comment by CarlRabeler** [comment]
@JediSQL please provide an example of how you would like it rewritten for more clarity and I will see that it is changed.

**Comment by JediSQL** [comment]
@CarlRabeler: At the end of the opening section there is "FOR SYSTEM_TIME can be specified independently for each table in a query. It can be used inside common table expressions, table-valued functions and stored procedures." I made an edit, and the pull request was assigned to you.

**Comment by CarlRabeler** [comment]
committed 28 days ago
