### ISSUE TITLE
BNF for "FOR SYSTEM_TIME <system_time>" Is Incorrect

### ISSUE THREAD

**Issue by JediSQL** [MicrosoftDocs/sql-docs#4349]
The BNF for "FOR SYSTEM_TIME &lt;system_time&gt;" is incorrect. The vertical bars say that "FOR SYSTEM_TIME &lt;system_time&gt;" is mutually exclusive with "table_or_view_name ...".

In fact, it should be

[ FROM { &lt;table_source&gt; } [ ,...n ] ]   
&lt;table_source&gt; ::=   
{  
    table_or_view_name [FOR SYSTEM_TIME &lt;system_time&gt;] [ [ AS ] table_alias ]   
        [ &lt;tablesample_clause&gt; ]   
        [ WITH ( &lt; table_hint &gt; [ [ , ]...n ] ) ]   
    | rowset_function [ [ AS ] table_alias ]   
    .....
    
because the "FOR SYSTEM_TIME &lt;system_time&gt;" clause must appear between the temporal table name an the alias assigned to the temporal table.
There should also be an example for a temporal table that shows the proper placement of the "FOR SYSTEM_TIME &lt;system_time&gt;" clause when using a table_alias.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3553153e-f6bf-2bc7-288c-ee03a3ba0781
* Version Independent ID: b4e3cfdf-aad7-e8a6-ffd7-acba7571de5c
* Content: [FROM: JOIN, APPLY, PIVOT (T-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/from-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/queries/from-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/from-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@JediSQL -- Dan, thank you for catching that.  I am looking into the document.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please review the above-mentioned PR 14210.
