### ISSUE TITLE
LocalDB download link is outdated

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/sql-docs#4350]
![image](https://user-images.githubusercontent.com/14079228/76810012-0ba70400-67c3-11ea-9d45-337990d683a7.png)

The link points to https://www.microsoft.com/sql-server/sql-server-editions-express

which gets redirect to https://www.microsoft.com/en-us/sql-server/sql-server-2019

I don't think that is the desired outcome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea66ca27-e0b1-cd1e-a8ef-55911169c71a
* Version Independent ID: f2340ce9-9771-851e-60a7-237c6e55f085
* Content: [SQL Server Express LocalDB - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/sql-server-express-localdb.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/sql-server-express-localdb.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@spottedmahn -- Michael, thank you for your feedback.

@MashaMSFT -- Masha, please look into this issue #4350.

**Comment by MashaMSFT** [comment]
Hi @spottedmahn , thanks for bringing this to our attention! I've processed a change to update this link and it should be live tomorrow.

I'm going to close out this Git Issue in the meantime, but please feel free to comment should you need anything further.

Thanks again for contacting Microsoft and hope you have a wonderful rest of your day!
Masha from the SQL Docs team

**Comment by spottedmahn** [comment]
🙏& 😎

---

Wish there was a link to the commit or PR... I assume you guys have some internal thing and that's why it's missing.

Nice to have everything linked full circle.

**Comment by MashaMSFT** [comment]
@spottedmahn , interesting, for my own education, is this not visible for you, earlier in the thread? 

![image](https://user-images.githubusercontent.com/32783170/77598141-49401700-6ebe-11ea-9190-811e420cee62.png)

Thanks!
Masha from the SQL Docs team

**Comment by spottedmahn** [comment]
Nope 😢, here's what I see:

![image](https://user-images.githubusercontent.com/14079228/77598328-e491b600-6ed7-11ea-80ba-84fd8de0e744.png)

---

guess that 🔒 means that? 🤔🤷‍♂️

![image](https://user-images.githubusercontent.com/14079228/77598352-f2dfd200-6ed7-11ea-8293-f53b23edf214.png)

---

I'm pretty sure it works the way I'm hoping for w/ the ASP.NET team...

**Comment by MashaMSFT** [comment]
@spottedmahn , that's so interesting! I am not sure how common knowledge it is that those aren't visible to everyone... our editing is through a private repo so this is actually good to know :) I believe once the change is actually live, anyone can see it in the history, but it looks like the actual PR doesn't display. 

Thanks a lot for bringing this to my attention! I've actually been relying on that as a signal that work is being done on the issue... so now I know not to do that! 

Thanks again!!
Masha from the SQL Docs team

**Comment by spottedmahn** [comment]
>Thanks a lot for bringing this to my attention!

👍
