### ISSUE TITLE
Installation Guide Link is broken

### ISSUE THREAD

**Issue by shyamsundarb-arch** [MicrosoftDocs/sql-docs#4352]
The link for installation Guide returns a 404. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da54684-9898-f8f7-55b6-713de7463bcb
* Version Independent ID: a3bb533f-c3d8-eb21-82ac-6d5e74ab99f7
* Content: [mssql-cli - SQL Server](https://docs.microsoft.com/en-us/sql/tools/mssql-cli?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/mssql-cli.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/mssql-cli.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@shyamsundarb-arch -- thank you for your feedback.

@markingmyname -- please look into this issue #4352.

**Comment by markingmyname** [comment]
@shyamsundarb-arch,

Thank you very much for bringing this to our attention.

Looking into this now.

**Comment by markingmyname** [comment]
I believe I found the issue.

Changes should be live sometime early next week.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit Azure Data Studio repo(https://github.com/microsoft/azuredatastudio)

**Comment by ellbosch** [comment]
Links are still broken, so I proposed a PR which fixes this: https://github.com/MicrosoftDocs/sql-docs/pull/4393

We made some doc changes to the mssql-cli GitHub page a few weeks back, which broke these links. Sorry about this!
