### ISSUE TITLE
Definition of "Column Definition" Not Aligned.

### ISSUE THREAD

**Issue by luomoyuyi** [MicrosoftDocs/sql-docs#4354]
The grammar of "Column Definition" in page 
https://docs.microsoft.com/zh-cn/sql/t-sql/statements/alter-table-transact-sql?redirectedfrom=MSDN&view=azure-sqldw-latest
and page 
https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-column-definition-transact-sql?redirectedfrom=MSDN&view=azure-sqldw-latest 
are not aligned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67bc2a9f-6bac-407f-27ba-ebbef0e9f884
* Version Independent ID: e070433f-bc91-80ef-878d-85e0071be6a2
* Content: [column_definition (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-column-definition-transact-sql?redirectedfrom=MSDN&view=azure-sqldw-latest)
* Content Source: [docs/t-sql/statements/alter-table-column-definition-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-table-column-definition-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@luomoyuyi -- Yanzhe, thank you for your feedback.

@CarlRabeler -- Carl, please look into this issue #4354.

**Comment by CarlRabeler** [comment]
@luomoyuyi researching with the product group

**Comment by CarlRabeler** [comment]
#reassign: @julieMSFT
Julie - could you please look at this. If this is not in your area, please either reassign back to me and reassign to the appropriate individual

**Comment by julieMSFT** [comment]
#assign:mstehrani

**Comment by mstehrani** [comment]
@CarlRabeler It looks like the column_definition for 'Azure Synapse Analytics' defines its own particular usage within the syntax block itself (and the other syntax blocks do not define it but instead point to the other documentation). I will update the [ALTER TABLE column_definition](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-column-definition-transact-sql?view=azure-sqldw-latest) to reflect that it is not meant for 'Azure Synapse Analytics'.

**Comment by CarlRabeler** [comment]
OK – sounds good.

**Comment by mstehrani** [comment]
@luomoyuyi Thank you for your feedback. The syntax blocks that use column_definition but don't define them have definitions at [ALTER TABLE column_definition page](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-column-definition-transact-sql?view=sqlallproducts-allversions) (whereas the Synapse syntax block defines it within the grammar itself). I'm updating the other Doc to reflect that it is not meant to cover Synapse syntax.

**Comment by mstehrani** [comment]
#please-close
