### ISSUE TITLE
broken rendering

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#4360]
@yujiorama commented on [Tue Mar 17 2020](https://github.com/MicrosoftDocs/sql-docs.ja-jp/issues/946)

From `In [!INCLUDEssCurrent], `, markdown rendering was broken.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4f33f7c8-745d-bdd0-fe14-2c1dac6875de
* Version Independent ID: 6db1bff2-e212-3337-7599-ea2b94019e04
* Content: [システムストアドプロシージャ (Transact-sql) - SQL Server](https://docs.microsoft.com/ja-jp/sql/relational-databases/system-stored-procedures/system-stored-procedures-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/system-stored-procedures-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ja-jp/blob/live/docs/relational-databases/system-stored-procedures/system-stored-procedures-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

---

@srvbpigh commented on [Tue Mar 17 2020](https://github.com/MicrosoftDocs/sql-docs.ja-jp/issues/946#issuecomment-599935912)

Hello, @yujiorama
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
the error is reported in a localized page but it's MT and out of our scope
There must be issues with the formatting in the en-us page that breaks the format when processed

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, thank you for sending along this feedback.

The [English-language version](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/system-stored-procedures-transact-sql?view=sql-server-ver15) is rendering correctly, as are neighboring Japanese pages.

@VanMSFT -- Van, please look into this issue #4360.

**Comment by VanMSFT** [comment]
Checking with the Loc team.

**Comment by MightyPen** [comment]
@RyanKing77 Hi Ryan, this image shows the problem.  The !INCLUDE line is literally visible in the '**ja-jp/**' edition of the article.
But in the English '**en-us/**' edition, the !INCLUDE line is not visible. Instead the contents of the !include are visible (as they should be): "**SQL Server 2019 (15.x)**".

&nbsp;

![Issue-4360 sql-docs ja-jp INCLUDE-literally-visible 20200318](https://user-images.githubusercontent.com/9660758/77016764-e1c21e80-6935-11ea-82ac-ba83010cba89.PNG)

&nbsp;

cc: @VanMSFT

**Comment by RyanKing77** [comment]
There is a known issue with how the MT Engine handles markdown syntax in some cases. We are actively working with the MSR MT team to fix this issue in the machine translation engine.  Additionally, we are working with the localization engineering team to automate fixes to some of these display problems. Both solutions require time, so we have to ask for your patience.

**Comment by WilliamAntonRohm** [comment]
@RyanKing77, thank you for your answer.  

I am closing this issue now.  You are welcome to @ mention me for any followup.
