### ISSUE TITLE
Remarks section on ANSI defaults hard to understand

### ISSUE THREAD

**Issue by ecki** [MicrosoftDocs/sql-docs#4362]
"opposite" and the text after it in the remarks if for me not understandable. What does it want to tell me? Does setting it off in the client equals to not setting it and will it unset the ansi options?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01be73e3-40a2-6d69-5fad-7fb0372d335f
* Version Independent ID: 5430c286-5d00-d233-6e83-d1bc6602b312
* Content: [SET ANSI_DEFAULTS (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-ansi-defaults-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/set-ansi-defaults-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-ansi-defaults-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@pmasl can you advise on this customer question ?

**Comment by ecki** [comment]
This text

> ANSI_DEFAULTS is a server-side setting that the client does not modify. The client manages its own settings. By default, these settings are the opposite of the server setting. Users should not modify the server setting. To change client the behavior, users should use the SQL_COPT_SS_PRESERVE_CURSORS. For more information, see SQLSetConnectAttr.

I understand it to read:

> ANSI_DEFAULTS is a server-side setting which can enable the behavior for all client connections.  The client typically requests the setting on connection or session initialisation —  Users should not modify the server setting. (To change client the behavior, users should use the client specific methods like SQL_COPT_SS_PRESERVE_CURSORS. For more information, see SQLSetConnectAttr.)

Or something like that? (It really seems to be critical to spell out why almost everything defaults to ANSI mode and yet all config options default to the opposite)

**Comment by pmasl** [comment]
Will clarify asap. Please bear with us and allow for some reasonable turnaround time.

**Comment by ecki** [comment]
Tanks the new wording is easier to understand.

**Comment by CarlRabeler** [comment]
Thanks for the confirmation.
