### ISSUE TITLE
FORMATMESSAGE with a msg_string note re 2016 is incorrect

### ISSUE THREAD

**Issue by gbritton1** [MicrosoftDocs/sql-docs#4367]
THe page has this note:

msg_string
Applies to: SQL Server ( SQL Server 2016 (13.x) through current version).

However all the tests on the page work fine in SQL Server 2012 SP4.  Please change the note to reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a768b81-c094-3a48-a8d5-0697ce6b78d7
* Version Independent ID: 65ae8973-f433-a826-d779-4ac4feb54f1c
* Content: [FORMATMESSAGE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/formatmessage-transact-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-previousversions)
* Content Source: [docs/t-sql/functions/formatmessage-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/formatmessage-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@gbritton1 -- Gerald, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue #4367.

**Comment by MikeRayMSFT** [comment]
Verifying. Thanks, @gbritton1 Gerald, for the submission.

**Comment by rothja** [comment]
@juliemsft Could you please look more into this issue? Thank you! #reassign:juliemsft

**Comment by julieMSFT** [comment]
@gbritton Thank you for contacting Microsoft. I am sorry for the delay in addressing your concerns. I am verifying your comment with the product group.

**Comment by julieMSFT** [comment]
@gbritton1 Hello, I have researched when FORMATMESSAGE was introduced. While it may have been present in earlier versions, it was not publicly documented and not formally supported. FORMATMESSAGE was announced and is supported SQL Server 2016 (13.x) through the current version. The SQL 2012 content has been archived and is not being updated. I will proceed with closing this issue.

The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
