### ISSUE TITLE
Issue creating a localDB at Runtime

### ISSUE THREAD

**Issue by msavazzi** [MicrosoftDocs/sql-docs#4371]
Team,
I'm stuck on creating a localDB at runtime.

Here is the code:
`            cnStrSQLServer = "Server=(LocalDB)\MSSQLLocalDB; Integrated Security=true "
' this is needed as without a connection I cannot drop/create the db
' if I put the new db name "TestDB" in the connection string ("Server=(LocalDB)\TestDB; Integrated Security=true ") I get a network error
            Using connection = New SqlConnection(cnStrSQLServer)
                connection.Open()
                Dim cmd As SqlCommand = connection.CreateCommand()
                Try
                    cmd.CommandText = String.Format("DROP DATABASE TestDB") 'no error here
                    cmd.ExecuteNonQuery()
                Catch ex As Exception
                    Debug.Print(ex.Message)
                End Try
                cmd.CommandText = "CREATE DATABASE TestDB On (Name ='TestDB', FILENAME ='c:\test\TestDB.mdf')" 'NO Error here!
                cmd.ExecuteNonQuery()
                connection.Close()
            End Using
            cnStrSQLServer = "Server=(LocalDB)\TestDB; Integrated Security=true;AttachDbFileName='c:\test\TestDB.mdf'"
            cnSQL = New SqlConnection(cnStrSQLServer)
            cnSQL.Open()
`
The last open gives an error on open. Network error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea66ca27-e0b1-cd1e-a8ef-55911169c71a
* Version Independent ID: f2340ce9-9771-851e-60a7-237c6e55f085
* Content: [SQL Server Express LocalDB - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/sql-server-express-localdb.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/sql-server-express-localdb.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @msavazzi , thank you for contacting Microsoft! From my understanding, the issue you're describing seems to be an issue with the product, is that correct? If so, unfortunately, this form of contact is intended explicitly for reporting issues with the documentation, and not for the product. To get further assistance with your issue, we'd recommend engaging the community, or opening a ticket with Microsoft Support. More information can be found here: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

Our apologies that the SQL Docs team was unable to assist you further with your issue, but we appreciate you reaching out. Please let us know if there's anything more we can do for you. We will close out this Git Issue in the meantime but please feel free to comment should  you need anything from the documentation perspective. 

Thanks again and hope you have a wonderful rest of your day!
Masha from SQL Docs team

**Comment by msavazzi** [comment]
Sorry but I opened it as it is an issue with the documentation as it does not provide clear and working instructions on how to connect, create a new LocalDB from code.
The information the page provides are not complete… and relevant but just partial.


Da: Masha at MSFT <notifications@github.com>
Inviato: mercoledì 18 marzo 2020 23:30
A: MicrosoftDocs/sql-docs <sql-docs@noreply.github.com>
Cc: Massimo Savazzi <massimo@savazzi.eu>; Mention <mention@noreply.github.com>
Oggetto: Re: [MicrosoftDocs/sql-docs] Issue creating a localDB at Runtime (#4371)


Hi @msavazzi<https://github.com/msavazzi> , thank you for contacting Microsoft! From my understanding, the issue you're describing seems to be an issue with the product, is that correct? If so, unfortunately, this form of contact is intended explicitly for reporting issues with the documentation, and not for the product. To get further assistance with your issue, we'd recommend engaging the community, or opening a ticket with Microsoft Support. More information can be found here: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

Our apologies that the SQL Docs team was unable to assist you further with your issue, but we appreciate you reaching out. Please let us know if there's anything more we can do for you. We will close out this Git Issue in the meantime but please feel free to comment should you need anything from the documentation perspective.

Thanks again and hope you have a wonderful rest of your day!
Masha from SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @msavazzi , thank you for the clarification! Are you saying that this doesn't work to create LocalDB for you?

`"C:\Program Files\Microsoft SQL Server\130\Tools\Binn\SqlLocalDB.exe" create LocalDBApp1`

Additionally, you're not able to connect with a connection string similar to: 

`np:\\.\pipe\LOCALDB#F365A78E\tsql\query`

Am I understanding correctly?

Thanks!
Masha from the SQL Docs team

**Comment by msavazzi** [comment]
The commands from command line like the ones you posted work.  The issue is how to create the localDB programmatically... from C# or VB.net code. This is what is missing

**Comment by MashaMSFT** [comment]
@msavazzi , ahh okay, I understand now, thank you for the clarification :) 

In that case, I have created an internal work item to track this work ([1699520](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1699520)) and will keep the Git Issue closed in the meantime. 

Thank you so much for providing your feedback and improving our documentation! Please feel free to comment should you need anything further.

Thanks again and hope you have a great weekend!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @msavazzi , does this information help?

For more information about including LocalDB in an application, see [Visual Studio Local Data Overview](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2012/ms233817(v=vs.110)), [Create a database and add tables in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-sql-database-by-using-a-designer?view=vs-2019).

Thanks!
Masha from the SQL Docs team

**Comment by msavazzi** [comment]
Mahsa,
Thank you very much, those pages help me in the next steps… once the LocalDB is created.
What I was trying to achieve was to create the LocalDB database at runtime.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MashaMSFT** [comment]
Hi @msavazzi , LocalDB is installed when SQL Server Express with Advanced Series is installed. It's not created during run time. This [blog ](https://www.pixelstech.net/article/1333167223-Introducing-LocalDB-an-improved-SQL-Express) explains it: 
LocalDB is installed once on a machine (per major SQL Server version). Multiple applications can start multiple LocalDB processes, but they are all started from the same sqlservr.exe executable file from the same disk location.

Is starting the process what you mean when you say "create at runtime"? 

Thanks!
Masha from the SQL Docs team

**Comment by msavazzi** [comment]
Masha,
sorry for not making it clear.
I install SQL Server Express with all the options.
During the install the basic LocalDB files are installed.
Now I want to create another DB “Test.mdf” in a specific folder and to use it from my app.
In the page is explained how to create the Test.mdf from the SQL Server CLI or the SSMS… but this is NOT what I want.
I want to create the Test.mdf with VB.NET / C# code, from the application… as response (for example) to a New command.


M


Da: Masha at MSFT <notifications@github.com>
Inviato: lunedì 23 marzo 2020 23:09
A: MicrosoftDocs/sql-docs <sql-docs@noreply.github.com>
Cc: Massimo Savazzi <massimo@savazzi.eu>; Mention <mention@noreply.github.com>
Oggetto: Re: [MicrosoftDocs/sql-docs] Issue creating a localDB at Runtime (#4371)


Hi @msavazzi<https://github.com/msavazzi> , LocalDB is installed when SQL Server Express with Advanced Series is installed. It's not created during run time. This blog <https://www.pixelstech.net/article/1333167223-Introducing-LocalDB-an-improved-SQL-Express> explains it:
LocalDB is installed once on a machine (per major SQL Server version). Multiple applications can start multiple LocalDB processes, but they are all started from the same sqlservr.exe executable file from the same disk location.

Is starting the process what you mean when you say "create at runtime"?

Thanks!
Masha from the SQL Docs team
