### ISSUE TITLE
Issues with validate-ad-config

### ISSUE THREAD

**Issue by AlexSamad** [MicrosoftDocs/sql-docs#4374]
Hi

I was doing a install on centos 8 and working through this. came across this issue.

1 is the case sensitivity of kerberos vs dns on linux
2 is the SPN not all that are tested for are configure above .. so I am not sure which is correct the validate script or the doco above

So 2 references
https://docs.microsoft.com/en-au/sql/linux/quickstart-install-connect-red-hat?view=sql-server-linux-ver15 &lt;&lt; Install guide
https://docs.microsoft.com/en-au/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-linux-ver15 &lt;&lt; AD connectivity

So done some digging into the script and validate-ad-config

I will try and document here - maybe MS will patch !

Its python - thats cool, but it assume some things. like case so RDNS is failing, hostname lookups is always lowercase in centos8 and it checks out the kerberos which is upper case

So trick here .. i added a line to my /etc/hosts file with the FQDN hostname  with the domain in capitals - not sure what that will do to the rest of the system - but ..

"lib/mssql-conf/mssqlconfhelper.py"

matchObject = re.match(".*%s" % (matchRealm), self.rdns)
can change to 
matchObject = re.match(".*%s" % (matchRealm), self.rdns, flags=re.IGNORECASE)

Think i will go with the change to the script over the hosts file change 

Now the SPN check - says not all there 
Its testing for SPN's that are not created ! The doco says to create spn's but only with ports

        validSPNs = []
        validSPNs.append("MSSQLSvc/%s.%s:%s" % (hostname, realm, self.port))
        #validSPNs.append("MSSQLSvc/%s.%s" % (hostname, realm))
        validSPNs.append("MSSQLSvc/%s:%s" % (hostname, self.port))
        #validSPNs.append("MSSQLSvc/%s" % (hostname))

Thats okay  - is this s problem ??? Who knows .. I could also add in the SPN with out ports , but I will wait and see

so now validate-ad-config works.

This was linked into the forums 
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/c8fb8fbb-7ca9-4cf3-bbbf-a7f77cb54f9b/issues-with-validateadconfig-on-centos-8?forum=sqlgetstarted

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Use AD authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-au/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-ver15&viewFallbackFrom=sql-server-linux-ver1#feedback)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **dygray**

**Comment by Dylan-MSFT** [comment]
Thanks for your comments! We are actually working on completely revamping this script, so stay tuned for some exciting changes :) We really appreciate all your debugging and will make sure these issues aren't a problem in our next release.
