### ISSUE TITLE
[SQL Server 2019] Settings missing for Server Configuration Options doc

### ISSUE THREAD

**Issue by wsmelton** [MicrosoftDocs/sql-docs#4376]
The following items are not documented on the [Sever Configuration Options](https://docs.microsoft.com/en-us/sql/relational-databases/accelerated-database-recovery-concepts?view=sql-server-ver15) doc for 2019. I've noted below which ones are missing

- ADR cleaner retry timeout (min) (default 0)
- ADR Preallocation Factor (default 0)
- allow filesystem enumeration (default 1)
- allow polybase export (default 0)
- column encryption enclave type (default 0)
- polybase network encryption (default value on my RTM is 1)
- tempdb metadata memory-optimized (default value 0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32e9c4f8-ec32-ff5f-93a4-8f07b664db5f
* Version Independent ID: 2111d777-a999-dc99-a3e5-cc7e7877c9b8
* Content: [Server Configuration Options (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/server-configuration-options-sql-server?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/configure-windows/server-configuration-options-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/server-configuration-options-sql-server.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by wsmelton** [comment]
I also don't find any doc specific to the ADR settings so not sure if that content just does not exists either or not.

**Comment by WilliamAntonRohm** [comment]
@wsmelton -- Shawn, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue #4376.

**Comment by JohannWeskandt** [comment]
I am also missing any official documentation about these new options in SQL 2019:
- version high part of SQL Server
- version low part of SQL Server
Many thanks in advance, Johann Weskandt

**Comment by MikeRayMSFT** [comment]
Investigating.

**Comment by MikeRayMSFT** [comment]
* ADR cleaner retry timeout: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/adr-cleaner-retry-timeout-configuration-option?view=sql-server-ver15
* ADR preallocation factor: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/adr-preallocation-factor-server-configuration-option?view=sql-server-ver15
* Column encryption enclave: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-column-encryption-enclave-type?view=sql-server-ver15
* Temp DB Metadata configuration is at: https://docs.microsoft.com/en-us/sql/relational-databases/databases/tempdb-database?view=sql-server-ver15#memory-optimized-tempdb-metadata

Looks like we still need:
* allow filesystem enumeration (default 1)
* allow polybase export
* Polybase Network configuration. Checking on how this relates to: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/polybase-connectivity-configuration-transact-sql?view=sql-server-ver15
