### ISSUE TITLE
Latest Release (1.16.0) not showing

### ISSUE THREAD

**Issue by sschocke** [MicrosoftDocs/sql-docs#4377]
Version 1.16.0 has been released and has already downloaded and installed on my machine, but the Release Notes are not available here as yet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f818cae2-8091-38c6-217c-328f5aa12b99
* Version Independent ID: 0a6efa72-49c2-12c4-4095-8fc094747b14
* Content: [Release notes - Azure Data Studio](https://docs.microsoft.com/en-za/sql/azure-data-studio/release-notes-azure-data-studio?view=sql-server-ver15#feedback)
* Content Source: [docs/azure-data-studio/release-notes-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/release-notes-azure-data-studio.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@sschocke -- Sebastian, thank you for your feedback.

@markingmyname -- Mark, please look into this issue #4377.

**Comment by markingmyname** [comment]
@sschocke 

It is showing up now.

March 2020
March 18, 2020   /   version: 1.16.0

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit Azure Data Studio repo(https://github.com/microsoft/azuredatastudio)
