### ISSUE TITLE
Where is the corresponding page for databases?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/sql-docs#4378]
that has the advice like "make the owner a regular low privilege sql user and not a domain account, etc?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30e180e-7e59-3a45-017d-9b94aa4b228d
* Version Independent ID: dbc9d750-c5ed-85b2-4031-71b1d4b04190
* Content: [Security Considerations - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/security-considerations-for-a-sql-server-installation?view=sql-server-ver15)
* Content Source: [docs/sql-server/install/security-considerations-for-a-sql-server-installation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/security-considerations-for-a-sql-server-installation.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @stingyjack, the following article is a great starting point to secure both your SQL Server, and your database: https://docs.microsoft.com/en-us/sql/relational-databases/security/security-center-for-sql-server-database-engine-and-azure-sql-database?view=sql-server-ver15 

Please let me know if this answers your question?

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @stingyjack, it's been some time since we've heard from you. Does this mean that your question has been addressed? I'm going to assume so and close out this Git Issue but please feel free to comment should you need anything further from us.

Thanks for contacting Microsoft! 
Masha from the SQL Docs team

**Comment by StingyJack** [comment]
There wasn't a mention of "owner" on that page, but I know I've seen the advice somewhere on docs (maybe it was technet) before. Don't worry about it. Thanks for looking.

**Comment by MashaMSFT** [comment]
Hi @StingyJack, I perused around as well and am not finding what you're referring to, my apologies for that. However, if you do find it, please be sure to let us know so that we can update our documentation as well :)

Thanks again for helping improve our documentation!
Masha from the SQL Docs team
