### ISSUE TITLE
serverproperty does not return NULL but fails horrible

### ISSUE THREAD

**Issue by ecki** [MicrosoftDocs/sql-docs#4379]
It should be mentioned that this fails on Azure SQL Database (not managed) with 

    Msg 40517, Level 16, State 1, Server server1, Line 1
    Keyword or statement option '@@servicename' is not supported in this version of SQL Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4609068-0fdc-8635-9fb8-becc215fec99
* Version Independent ID: 7636b86a-446a-621d-0795-85668c7b37be
* Content: [@@SERVICENAME (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/servicename-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/servicename-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/servicename-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hello @ecki! The **Applies to** at the top of the page already implies that it doesn't apply:

![image](https://user-images.githubusercontent.com/40007119/77113585-59508600-69e8-11ea-9dd2-a508ec84d56d.png)

**Comment by ecki** [comment]
Yes and no, if you are use to have serverproperties which simply reply null it can be quite surprising if you get an error instead, especially if the same "product" in different deployment variants behaves so different, so a caveat message would be a courtesy to the developers.
