### ISSUE TITLE
sqlserver.query_thread_profile barely returns [total_time_us] value greater than 0,

### ISSUE THREAD

**Issue by Park-minkyu** [MicrosoftDocs/sql-docs#4380]
that events are really cool stuff for dbas.
but this event only returns greater-than-zero value of [total_time_us]  on SOME condition which I haven't figure out yet,.

can you specify the condition?

I try to use this data column as [sqlserver.query_thread_profile] for events so my event session won't flood by plan nodes event datas

"okay, I want to collect all that plan nodes that exceed total_time_us greater than 10000 microseconds)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1510fff2-024d-f3ed-59fa-6d14cad8fa0a
* Version Independent ID: 0cfcf072-0691-5690-c3cf-2e468d168978
* Content: [Query Profling Infrastruture - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/query-profiling-infrastructure?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/query-profiling-infrastructure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/query-profiling-infrastructure.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by pmasl** [comment]
Not sure which condition you are referring to. Take a look at this blog post to see how the XE can be leveraged. https://blogs.msdn.microsoft.com/sql_server_team/added-per-operator-level-performance-stats-for-query-processing/

**Comment by pmasl** [comment]
There was no follow-up. #please-close
