### ISSUE TITLE
Numbers Problem

### ISSUE THREAD

**Issue by boraberka** [MicrosoftDocs/sql-docs#4381]
metin içinde KDV.MUK.B.07.4.DEF.0.34.18.4619 bu ifade var ancak hiçbir şekilde sonuç bulmuyor. Fakat metin içindeki ifadeyi KDV.MUK.B.07.4.DEF.0.34.18. 4619 bu şekilde son parçada bir boşluk gelecek şekilde yaptığımda sonuç alıyorum. Sorun ile ilgili yardım istiyorum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f9bb23-a597-f5c9-b06d-3edf96a985ec
* Version Independent ID: 105b11c2-9dbc-2127-59fc-337a707a0d8d
* Content: [Query with Full-Text Search - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/search/query-with-full-text-search?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/search/query-with-full-text-search.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/search/query-with-full-text-search.md)
* Product: **sql**
* Technology: **search**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by WilliamAntonRohm** [comment]
@boraberka -- please clarify your issue.  The machine-translation of your comment is:

> VAT in text. Muk. B.07.4.DEF.0.34.18.4619 has this expression but does not find any results. But vat the expression in the text. Muk. B.07.4.DEF.0.34.18. 4619 I get results when I do this in a way that there is a gap in the last piece. I'm asking for help with the problem.
