### ISSUE TITLE
Example appears to contain a syntax error

### ISSUE THREAD

**Issue by pcleckler** [MicrosoftDocs/sql-docs#4382]
USE AdventureWorks2012;  
GO  
EXEC sp_procoption @ProcName = '&lt;procedure name&gt;'   
    , @OptionName = ] 'startup'  /* &lt;-- Syntax error? */ 
    , @OptionValue = 'on';

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a260067f-c0fc-2a45-82c2-795ae1bb8dc6
* Version Independent ID: e06f1f7e-1c5f-a494-7038-241053d5298a
* Content: [Execute a Stored Procedure - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/execute-a-stored-procedure?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/stored-procedures/execute-a-stored-procedure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/stored-procedures/execute-a-stored-procedure.md)
* Product: **sql**
* Technology: **stored-procedures**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@pcleckler -- Philip, thank you for your feedback.  I am looking into this document.
