### ISSUE TITLE
The description for the DeviceType column is missing the value 9

### ISSUE THREAD

**Issue by akarzazi** [MicrosoftDocs/sql-docs#4383]
When I do a backup header from an azure blob storage.

`RESTORE HEADERONLY FROM URL = 'https://....blob.core.windows.net/...' WITH CREDENTIAL = '...'`

I get for the **DeviceType** Column the value 9. (I guess it is for azure storage)

Which is not documented in 
https://docs.microsoft.com/en-us/sql/t-sql/statements/restore-statements-headeronly-transact-sql?view=sql-server-ver15

Here are the listed values
Disk:
2 = Logical
102 = Physical

Tape:
5 = Logical
105 = Physical

Virtual Device:
7 = Logical
107 = Physical

Can you please provide the comprehensive enum list ?

Aside, are these values related to the device_type property from backupmediafamily.

**Comment by WilliamAntonRohm** [comment]
@akarzazi -- Adel, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue #4383.

**Comment by MikeRayMSFT** [comment]
@akarzazi - I'm preparing a doc update. Thanks.
