### ISSUE TITLE
Request documentation: Enable SQL Agent

### ISSUE THREAD

**Issue by mwdarab** [MicrosoftDocs/sql-docs#4385]
Can you create a whole new page and call it, "Enable SQL Agent"? I feel like that is a big thing to know but it's buried in this page that's titled, "SQL Server master instance" or perhaps change the title of this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b11c2fe-4e4a-3379-1ba6-928fbc290e43
* Version Independent ID: 4ad1482b-ba6f-61ee-f7e2-6f5f8b9183d0
* Content: [Configure SQL Server master instance - Configure SQL Server master instance of Big Data Cluster](https://docs.microsoft.com/en-us/sql/big-data-cluster/configure-sql-server-master-instance?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/configure-sql-server-master-instance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/configure-sql-server-master-instance.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@mwdarab -- Mohammad, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue #4385.

**Comment by MikeRayMSFT** [comment]
@mwdarab - thank you for the submission. I'm checking the best way to provide this information.

**Comment by MikeRayMSFT** [comment]
An example to enable SQL Agent is provided in the [SQL Server master instance configuration](https://docs.microsoft.com/sql/big-data-cluster/configure-sql-server-master-instance?view=sql-server-ver15) article. 

I'm working with the team for additional content. Thank you for the submission.
