### ISSUE TITLE
Questions in headers

### ISSUE THREAD

**Issue by SimpleSamples** [MicrosoftDocs/sql-docs#4387]
I have spent a few years editing articles written by people in India. I have noticed that when they make a header as a question, the header is a necessary part of the material. That is relevant here because in the section "When Is a Format File Required?" I have no idea what the purpose of the first list is. The second list is preceded with the explanation "Format files are required if". If the header "When Is a Format File Required?" is the explanation of the first list then there is redundancy. I think the reader should not be required to read the header to understand the material and use of a question in a header usually requires the reader to do that. In this case even the header does not provide adequate explanation of all the material.

There are many millions of very intelligent people in India. It is not my intent to be critical of them. I hope I am helping.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17fa4de7-73aa-5c2a-828b-ad55f9af037b
* Version Independent ID: d57836ea-29c3-6704-a15e-fe623f4f8335
* Content: [Format files to import & export data - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/format-files-for-importing-or-exporting-data-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/import-export/format-files-for-importing-or-exporting-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/format-files-for-importing-or-exporting-data-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @SimpleSamples , thanks for your feedback! Actually, using a question as a heading is a common practice to optimize for a search engine. Having said that though, I can see that having the two lists here may be causing confusion. As such, I have created an internal work item ([1689110](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1698110)) to review and refresh this article for clarity. 

I will close out this Git Issue for the time being but please feel free to comment should you have any additional feedback. 

Thanks again for helping improve our documentation!
Masha from the SQL Docs team

**Comment by rwestMSFT** [comment]
#reassign:@rwestMSFT

**Comment by rwestMSFT** [comment]
Given the tone and couching of this issue in racism, we will not be following up, and we will not entertain any further discussion on this topic.

Your cooperation is appreciated.
