### ISSUE TITLE
rxExecBy not work with numTasks higher than 1 in sql server 2019

### ISSUE THREAD

**Issue by xofware** [MicrosoftDocs/sql-docs#4388]
This function works well with SQL Server versions 2016 and 2017, but with 2019 it only works with a parallelism level of 1. Tests have been carried out with the same code example that appears on this web page:

https://docs.microsoft.com/en-us/sql/advanced-analytics/r/creating-multiple-models-using-rxexecby?view=sql-server-ver15

When numTasks equals 1, the script ends correctly, however when it is 2 or higher, the procedure hangs and no feedback appears. The issue could be related to the new 2019 version isolation scheme and MPI Application Launcher. I appreciate the help in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa208f0b-48c7-ab50-7b97-37963411d4c6
* Version Independent ID: 41c19b94-da08-dc88-d6b8-256c886435a0
* Content: [Create multiple models with rxExecBy - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/r/creating-multiple-models-using-rxexecby?view=sql-server-ver15#feedback)
* Content Source: [docs/advanced-analytics/r/creating-multiple-models-using-rxexecby.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/r/creating-multiple-models-using-rxexecby.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@xofware Thank you for opening a GitHub issue. I will investigate this and get back to you.

**Comment by dphansen** [comment]
@xofware This is a known issue with parallelism in R scripts in the current version of SQL Server 2019. It will be fixed in a future Cumulative Update (CU). 

We will update the [Known issues documentation](https://docs.microsoft.com/sql/advanced-analytics/known-issues-for-sql-server-machine-learning-services?view=sql-server-ver15) to reflect this.

**Comment by xofware** [comment]
Hello @dphansen, I just tried Cumulative Update 4 and issue persists.  It could be posible to have a fix for the next update?

**Comment by dphansen** [comment]
@xofware I do not have a timeline for the fix at this time.

**Comment by dphansen** [comment]
@xofware I've spoken with the product team. There are two solutions until the fix will be released:

1. Open a [support case](https://support.microsoft.com/en-us/help/4341255/support-for-business) describing the issue and mention this GitHub issue. The product team might be able to help you with a fix.

1. As a workaround, you can insert the below workaround code in your `sp_execute_external_script` query before their parallel execution.

```R
parallel <- getNamespace("parallel")
unlockBinding("makePSOCKcluster", parallel)

internalMakePSOCKcluster <- parallel::makePSOCKcluster
wrapperMakePSOCKcluster = function(...) {
 args <- list(...)
 if (!("outfile" %in% names(args)) || is.null(args[["outfile"]]))
 {
   args[["outfile"]] <- tempfile()
 }
 do.call(internalMakePSOCKcluster, args)
}

parallel$makePSOCKcluster <- wrapperMakePSOCKcluster
lockBinding("makePSOCKcluster", parallel)
```

A full external script example is this:

```sql
exec sp_execute_external_script  
@language = N'R',
@script = N'

# Workaround code
parallel <- getNamespace("parallel")
unlockBinding("makePSOCKcluster", parallel)

internalMakePSOCKcluster <- parallel::makePSOCKcluster
wrapperMakePSOCKcluster = function(...) {
 args <- list(...)
 if (!("outfile" %in% names(args)) || is.null(args[["outfile"]]))
 {
   args[["outfile"]] <- tempfile()
 }

 do.call(internalMakePSOCKcluster, args)
}

parallel$makePSOCKcluster <- wrapperMakePSOCKcluster
lockBinding("makePSOCKcluster", parallel)

# Your code
func <- function()
{
"hello world"
} 
rxSetComputeContext(RxLocalParallel())
z <- rxExec(func, timesToRun=4)
print(z)
'
```

**Comment by xofware** [comment]
@dphansen we appreciate your prompt reply. We have carried out tests with SQL Server 2019 in various scenarios using the workaround code which works flawlessly. 
It is suggested to update the Known issues documentation (https://docs.microsoft.com/sql/advanced-analytics/known-issues-for-sql-server-machine-learning-services?view=sql-server-ver15) with the proposed code.
Thanks for your valuable help.
