### ISSUE TITLE
Unable to launch runtime for Python/R script IN Ubuntu

### ISSUE THREAD

**Issue by jlehew** [MicrosoftDocs/sql-docs#4390]
On Ubuntu receiving an error similar to the windows "Unable to launch runtime for Python/R script"

In SSMS when running the verification script receive
Msg 39012, Level 16, State 14, Line 16
Unable to communicate with the runtime for 'Python' script for request id: 63098BB8-38A9-4958-B6FE-B643ED26533F. Please check the requirements of 'Python' runtime.

In sudo systemctl status mssql-launchpadd
receive "Error launching satellite: Launcher for script type Python(2) not loaded"

The install didn't work, when running "sudo apt-get install mssql-mlservices-mlm-py"

This said "The following packages have unmet dependencies:"  then listed microsoft-openmpi

I could not install microsoft-openmpi, said Package microsoft-openmpi is not available after running sudo apt-get install microsoft-openmpi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87848ac2-7a1b-5d5a-f43b-bc6714647969
* Version Independent ID: c1d80113-7951-c4c4-12ec-6a04232a4d21
* Content: [Common issues with Launchpad - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/common-issues-external-script-execution?view=sql-server-ver15#feedback)
* Content Source: [docs/advanced-analytics/common-issues-external-script-execution.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/common-issues-external-script-execution.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@jlehew Thanks John for opening up this GitHub issue. I will investigate the issue and get back to you.

**Comment by dphansen** [comment]
@jlehew I have a couple of questions:

1. Which version of Ubuntu are you running? 
1. Which *Microsoft SQL Server Ubuntu repository for SQL Server 2019* are you using (see step 2 under [Install SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-linux-ver15&source=docs#install) for an example of the which repo is registered during the installation).

**Comment by dphansen** [comment]
@jlehew Please see my note above about some questions to be able to proceed with the trouble shooting. Thanks.

**Comment by jlehew** [comment]
Running Ubuntu 18.04 LTS - Bionic latest version on AWS by Cononical Group Limited
t3a.small AWS instance Type on EC2

This is what's listed in my /etc/apt/sources.list file
https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019 bionic main

I installed the developer version of Sql 2019

**Comment by jlehew** [comment]
I think the bottom half this thread shows two more developers that have the same issue [https://github.com/Microsoft/mssql-docker/issues/403](url)

Here are my notes from the install.  These are notes, not a tested script.  It might not be 100% accurate.  Sql Server is running fine, just the ML Services isn't working
# After a fresh install of AWS Ubuntu 18.04 LTS Bionic on a t3a.small EC2 instance start with the apt-get update command
sudo apt-get update
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/18.04/mssql-server-2019.list)"

sudo apt-get update
sudo apt-get install -y mssql-server
sudo /opt/mssql/bin/mssql-conf setup
systemctl status mssql-server --no-pager

# Install as root
sudo su

# Optionally, if your system does not have the https apt transport option
apt-get install apt-transport-https

# Set the location of the package repo the "prod" directory containing the distribution.
# This example specifies 16.04. Replace with 14.04 if you want that version
wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

# Register the repo  (HAD TO ADD .1 ON THE END…. dpkg -i packages-microsoft-prod.deb.1
dpkg -i packages-microsoft-prod.deb

# Update packages on your system (required), including MRO installation
sudo apt-get update


# Install tools on Ubuntu 18.04 
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add –
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
sudo apt-get update
sudo apt-get install mssql-tools unixodbc-dev

# Install SQL Server Agent
#	Add hostname in the /etc/hosts file
sudo nano /etc/hosts
#	Add 1.2.3.4 ec2-1-2-3-4.us-east-2.compute.amazonaws.com

# Enable SQL Server agent
sudo /opt/mssql/bin/mssql-conf set sqlagent.enabled true
sudo systemctl restart mssql-server

# Install mssql-server-extensibility for Machine Learning Services
sudo apt-get install mssql-server-extensibility    
sudo apt-get install mssql-mlservices-python 
# Post-install config (required)
sudo /opt/mssql/bin/mssql-conf setup 
# Type 2, yes, then SA password
# Should see this message
#	Setup has completed successfully. Microsoft SQL Server Machine Learning Services is now starting. 
sudo /opt/mssql/bin/mssql-conf set EULA accepteulaml Y
sudo /opt/mssql/bin/mssql-conf set extensibility outboundnetworkaccess 1

# Execute this file by typing source .bash_profile at a bash command prompt.
sudo echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile 
sudo echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashrc
sudo systemctl restart mssql-launchpadd
sudo systemctl restart mssql-server.service  

# IN SSMS – Turn on external scripts
#	EXEC sp_configure 'external scripts enabled', 1 
# 	RECONFIGURE WITH OVERRIDE

**Comment by dphansen** [comment]
@jlehew Thanks John for the details information. There was an issue with missing packages in the 18.04 repo. This has now been fixed. Would you be able to try install SQL Server 2019 and Machine Learning Services again, and see if you still have the same issue?

**Comment by jlehew** [comment]
I created a new EC2 instance and was able to installed it successfully following the instructions.  Thanks for your assistance.
