### ISSUE TITLE
Pleonastic Transposition?

### ISSUE THREAD

**Issue by KevinPence** [MicrosoftDocs/sql-docs#4395]
Given 'unique PK' is tautological, should the 6th bullet point under Restrictions read:
"A sparse column cannot be part of a UNIQUE clustered index or a u̶n̶i̶q̶u̶e̶ primary key index."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46ab5559-d930-39c4-b27c-898d2883efe2
* Version Independent ID: ac1acd3d-c154-2934-5daf-fbacab4df7ba
* Content: [Use Sparse Columns - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/use-sparse-columns?view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/relational-databases/tables/use-sparse-columns.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/use-sparse-columns.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@KevinPence -- thank you for your feedback.

@stevestein -- please look into this issue #4395.

**Comment by stevestein** [comment]
@KevinPence - thanks for the feedback. Considering it's not technically wrong and has been this way for several versions we're going to leave it as is.

Thanks!

#please-close

**Comment by KevinPence** [comment]
@stevestein, From your response I'm not sure if you caught my entire question.  I should have been much more clear and direct instead of having fun with words.

I think your reply is to my observation that "unique" is redundantly applied to "primary key."  That is not the issue, per se.  It's just there to explain why I'm raising my real question.

I want clarity on whether sparse columns are not allowed in any clustered index or just unique ones.  Is the "unique" redundancy just a redundancy, or does the word belong with "clustered index" instead of "primary key"?

Thanks for considering.
