### ISSUE TITLE
This same error has been seen by a user trying to connect to Azure SQL Database

### ISSUE THREAD

**Issue by langstonj** [MicrosoftDocs/sql-docs#4397]
The document list applies to SQL Server.  One of my users encountered it with Azure SQL Database.  Just wanted you to know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad59c2f-79d6-5062-8fe5-0fff32b316c8
* Version Independent ID: 7941ba5c-1aa2-4abd-44cb-fb913bc6ead8
* Content: [MSSQLSERVER_11001 - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/mssqlserver-11001-database-engine-error?view=sql-server-ver15)
* Content Source: [docs/relational-databases/errors-events/mssqlserver-11001-database-engine-error.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/errors-events/mssqlserver-11001-database-engine-error.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @langstonj , thanks for bringing this to our attention! I've created an internal work item ([1700543](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1700543)) to go through and update the applies to for this, and other errors :) 

I'm going to close out this Git Issue for the time being but please feel free to comment should you need anything further from us. 

Thanks for helping improve our documentation and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
