### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#4398]
"SQL Sewrver 2017"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d903c17-112d-c463-0af8-e1b6799df66f
* Version Independent ID: 008ccdde-b62c-92a1-98fd-377ad97a769d
* Content: [Create Identical Symmetric Keys on Two Servers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/create-identical-symmetric-keys-on-two-servers?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/security/encryption/create-identical-symmetric-keys-on-two-servers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/create-identical-symmetric-keys-on-two-servers.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@PrometheusRising1 -- thank you for catching that.  I am updating the document.
