### ISSUE TITLE
Shared Secret Generation

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#4399]
You need examples (or a link to another docs article) of how to generate shared secrets correctly in Windows Server (and possibly Linux), both On-Prem and in the cloud.  Database Admins do not have the requisite experience to assume that they can create a C# program or call a method to do this unless you were to give a T-SQL function or PowerShell cmdlet example. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d903c17-112d-c463-0af8-e1b6799df66f
* Version Independent ID: 008ccdde-b62c-92a1-98fd-377ad97a769d
* Content: [Create Identical Symmetric Keys on Two Servers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/create-identical-symmetric-keys-on-two-servers?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/security/encryption/create-identical-symmetric-keys-on-two-servers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/create-identical-symmetric-keys-on-two-servers.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@PrometheusRising1 -- thank you for your feedback.

@jaszymas -- please look into this issue.

**Comment by PrometheusRising1** [comment]
Hi, any additional info on this one?  I am building a restore script out right now and need the information on KEY_SOURCE and IDENTITY_VALUE  to ensure that i am creating something according to general best practices.  Is it best to generate these from a .NET library and stored them out-of-band?  Use a random string of letters and numbers (e.g. can I use special characters?  It doesn't say), or a phrase that my team would remember, or should I avoid dictionary words and phrases altogether?

**Comment by VanMSFT** [comment]
Hello @PrometheusRising1! Sorry for the delay! I hope you were able to find what you were looking for, but if not, the CREATE SYMMETRIC KEY syntax is documented here: https://docs.microsoft.com/en-us/sql/t-sql/statements/create-symmetric-key-transact-sql

You should be able to find what you need for KEY_SOURCE and IDENTITY_VALUE. I hope that helps! I'll go ahead and close this issue, but please feel free to @ me if you have any questions on this.
