### ISSUE TITLE
Size Limit with Block Blobs may be 4.5 TB instead of 200 GB

### ISSUE THREAD

**Issue by ashishsinghbhu** [MicrosoftDocs/sql-docs#4400]
The article indicates "SQL Server limits the maximum backup size supported using a page blob to 1 TB. The maximum backup size supported using block blobs is limited to approximately 200 GB (50,000 blocks * 4MB MAXTRANSFERSIZE)." 

The 200 GB size limit is perhaps coming from the old storage block blob size limit, but it has now been raised to 4.5 TB. Ref : https://docs.microsoft.com/en-us/azure/storage/blobs/scalability-targets#scale-targets-for-blob-storage 

Kindly confirm if above hypothesis is true and if we should mention 4.5 TB instead of 200 GB in the SQL article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07f4557b-415f-e3d6-7ee4-11b0ca970318
* Version Independent ID: f2ef03ed-1295-1b21-8323-42921f0fb7d3
* Content: [Backup & restore with Azure Blob Storage - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-and-restore-with-microsoft-azure-blob-storage-service?view=sql-server-ver15)
* Content Source: [docs/relational-databases/backup-restore/sql-server-backup-and-restore-with-microsoft-azure-blob-storage-service.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/sql-server-backup-and-restore-with-microsoft-azure-blob-storage-service.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@ashishsinghbhu -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
@ashishsinghbhu - thank you for the submission. I don't see the text you're citing in the linked article. I do see it here:

[SQL Server Backup to URL](https://docs.microsoft.com/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-ver15#limitations)

The current documentation is correct. The MAXTRANSFERSIZE limit still applies to SQL Server so it does not use the increased block size.
