### ISSUE TITLE
Description of DeploymentReport output file

### ISSUE THREAD

**Issue by dansydner** [MicrosoftDocs/sql-docs#4403]
I've looked everywhere and have not found a description of the contents of the DeploymentReport output file. It woulr be useful to at least have a brief description of the file format or a link pointing to something of the kind.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage.exe - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by WilliamAntonRohm** [comment]
@dansydner -- Dan, thank you for your feedback.

@pensivebrian -- Brian, please look into this issue.

**Comment by rothja** [comment]
@pensivebrian Could you help @dansydner with his question on the contents of the DeploymentReport output file. He is looking for the file format or any other info related that you could point to. If such a thing exists, we could update the docs as well. 

@dansydner Dan, sorry for the long delay on getting back to you. Were you able to find out anything online or in the community, or is this still blocking you in any way? Thank you!

**Comment by dzsquared** [comment]
#assign:dzsquared

**Comment by dansydner** [comment]
We were able to work around this. Still curious to know if there is any further information on the file contents.

**Comment by rothja** [comment]
@dansydner Sorry for the lack of traction on this. I will try to look into this more. @pensivebrian, Brian, let me know if you know whether/where this might be documented.  #assign:rothja

**Comment by PRMerger12** [comment]
rothja is already assigned.

**Comment by rothja** [comment]
@dansydner Dan, I haven't been able to get additional clarification on this output file for the documentation. I apologize for the lack of clarity here. Hopefully in the future we can track this down and get it added. If you or additional customers run into this again, anyone is welcome to add support for this request in the comment thread of this issue. Also, there are several people included on this issue that might have additional comments as they look into this in the future. Thank you!
