### ISSUE TITLE
possible syntax convention typo

### ISSUE THREAD

**Issue by JohnOsborneOPM** [MicrosoftDocs/sql-docs#4409]
Should 'database_name.schema_name.table_name.' actually be 'database_name.schema_name.table_name' with the period dropped at the end?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be5dfc7-5496-f8ec-072f-81132fe92054
* Version Independent ID: 634e3c60-d717-92ba-dd93-e3773edf2816
* Content: [CREATE TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
good catch - fixing now - PR pending - will be live later today.

**Comment by CarlRabeler** [comment]
Good catch – yes. Updating now.
