### ISSUE TITLE
Continuity issue

### ISSUE THREAD

**Issue by walteriousnut** [MicrosoftDocs/sql-docs#4419]
The last section of this page 'View the Query Plan' is not correctly continuing from the previous section. 

In the previous section, the last step was to copy the query text for the slow running query to the clipboard. Then the next section 'View the Query Plan' is suddenly running the widget's query (which lists slow running queries) and viewing the explain plan for that query. 

I don't think this is what you intended.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9dc8a6a-682b-3016-5fd7-d1840505e075
* Version Independent ID: d9657550-a95f-f50c-7d56-0295de2904f6
* Content: [Enable the five slowest queries sample widget - Azure Data Studio](https://docs.microsoft.com/en-au/sql/azure-data-studio/tutorial-qds-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/azure-data-studio/tutorial-qds-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/tutorial-qds-sql-server.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@walteriousnut -- thank you for your feedback.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
@walteriousnut,

First, I apologize for the delay.

Second, good catch.

I will update the article.

**Comment by markingmyname** [comment]
PR - https://github.com/MicrosoftDocs/sql-docs-pr/pull/15218

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit Azure Data Studio repo(https://github.com/microsoft/azuredatastudio)
