### ISSUE TITLE
Example for sql restore stopatlogmark is wrong

### ISSUE THREAD

**Issue by SQLBackupMike** [MicrosoftDocs/sql-docs#4420]
The sample code below is wrong.  It is trying to stop at the description of the logmark. It needs to pass the logmark name instead.    IE. 'ListPriceUpdate'   On the last line.

USE AdventureWorks2012
GO
BEGIN TRANSACTION ListPriceUpdate
    WITH MARK 'UPDATE Product list prices';
GO

UPDATE Production.Product
    SET ListPrice = ListPrice * 1.10
    WHERE ProductNumber LIKE 'BK-%';
GO

COMMIT TRANSACTION ListPriceUpdate;
GO

-- Time passes. Regular database
-- and log backups are taken.
-- An error occurs in the database.
USE master;
GO

RESTORE DATABASE AdventureWorks2012
FROM AdventureWorksBackups
WITH FILE = 3, NORECOVERY;
GO

RESTORE LOG AdventureWorks2012
  FROM AdventureWorksBackups
    WITH FILE = 4,
    RECOVERY,
    STOPATMARK = 'UPDATE Product list prices';

**Comment by WilliamAntonRohm** [comment]
@SQLBackupMike -- thank you for your feedback.  Are you referring to a specific docs.microsoft.com article?

**Comment by SQLBackupMike** [comment]
https://docs.microsoft.com/en-us/sql/t-sql/statements/restore-statements-transact-sql?view=sql-server-ver15#restoring_transaction_log_to_mark

in this link the logmark restore example is wrong.

**Comment by SQLBackupMike** [comment]
https://docs.microsoft.com/en-us/sql/t-sql/statements/restore-statements-transact-sql?view=sql-server-ver15#restoring_transaction_log_to_mark

in this link the logmark restore example is wrong

**Comment by WilliamAntonRohm** [comment]
@SQLBackupMike -- thank you for clarifying, and I believe you are correct here, per [this article](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/recovery-of-related-databases-that-contain-marked-transaction?view=sql-server-ver15#transact-sql-syntax-for-inserting-named-marks-into-a-transaction-log).

@MikeRayMSFT -- please review [private PR 14360](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14360).
