### ISSUE TITLE
advice on HDFS replication factor

### ISSUE THREAD

**Issue by chrisadkin** [MicrosoftDocs/sql-docs#4427]
This page states the following:

When computing the storage pool sizing requirements, you must consider the replication factor that HDFS is configured with. Replication factor is configurable at deployment time in the cluster deployment configuration file. The default value for the dev-test profiles (i.e. aks-dev-test or kubeadm-dev-test) is 2, and for the profiles that we recomend for production deployments (i.e. kubeadm-prod) the default value is 3. As a best practice, we recomd you configure your production deployment of big data cluster with a replication factor for HDFS of at least 3. The value of the replication factor will impact the number of instances in the storage pool: at a minimum, you must deploy at least as many storage pool instances as the value of the replication factor. In addition, you must size the storage accordingly, and acount for data being replicated in HDFS as many times as the value of the replication factor. You can find more about data replication in HDFS here.

This information harks back to the era when people purchased using spinning disk based storage platforms, which used protection mechanisms basded on spindles failing. Modern flash based storage, which most people are now buying, use protection mechanisms based on protecting data at the block level, such as erasure coding and modern RAID levels, in this case the replication factor can be set safely to 1. The advice for setting the replication factor to a value greater than 1 only applies to:

- Spinning disk based storage systems that do not use any type of RAID level and / or erasure coding
- Hyper-converged platforms, i.e. they scale-out in units that combine both storage and compute resources
- And kind of software defined storage platform that does not use RAID level and / or erasure coding

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e099502f-f7d3-5368-41fe-6c50d593c8fd
* Version Independent ID: 7f77cae8-15a9-a586-31b2-80d985ca019a
* Content: [Data persistence on Kubernetes - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/concept-data-persistence?view=sql-server-ver15#feedback)
* Content Source: [docs/big-data-cluster/concept-data-persistence.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/concept-data-persistence.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @mihaelablendea
* Microsoft Alias: **mihaelab**

**Comment by WilliamAntonRohm** [comment]
@chrisadkin -- Chris, thank you for writing.  Please add your feedback here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @mihaelablendea for awareness
