### ISSUE TITLE
Wrong Title

### ISSUE THREAD

**Issue by JediSQL** [MicrosoftDocs/sql-docs#4430]
In the left side navigation, this page is listed under "Service Broker." While event notifications do involve service broker, the four pages under Database design/Service broker are really about event notifications, and they do not cover the basics of service broker. The left side navigation should be changed to be:

Database design
  ...
  +- Event notification
    +- Event notification
    +- Implement
    +- Configure Dialog Security
    +- Get Information
  ...
  +- Service broker
    +- Service broker
  ...

This should be done by first renaming the existing "Service Broker" navigation items to "Event notification." Then add a new set of items for "Service Broker" that go with pages that cover the basics of service broker.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9871df5-01b4-72e4-33bf-d77856ba8656
* Version Independent ID: 2bd78481-34eb-bddb-89f2-c7a0850963b2
* Content: [Event Notifications - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/service-broker/event-notifications?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/service-broker/event-notifications.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/service-broker/event-notifications.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @jediSQL, thanks for bringing this to our attention! Let me do some research :)

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @JediSQL , thanks for bringing this to our attention! I have processed a change to fix this that should be live now. 

I hope that helps and please let us know if we can be of further assistance? I am going to close out this Git Issue, but please feel free to comment should you need anything further.

Thanks again and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team

**Comment by JediSQL** [comment]
Looks good. Thank you.
