### ISSUE TITLE
No mention of error 927 occurring when using this function

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#4431]
Using this on a server that has a database in a restoring state fails with error 927.
This means I can no longer query for statistics from the server

This works:
select * from sys.dm_exec_query_stats
cross apply sys.dm_Exec_sql_Text(sql_handle)

This does not:
select * from sys.dm_exec_query_stats
cross apply sys.dm_Exec_sql_Text(sql_handle)
cross apply sys.dm_exec_plan_attributes(sql_handle) x

Unfortunately forums are getting ignored, but there seems to be a lot of activity on docs, so cross posting here
https://feedback.azure.com/forums/908035-sql-server/suggestions/36684238-strange-problems-related-to-query-cache-plan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a77d63-0ef7-54c8-4f02-59f736298c70
* Version Independent ID: 1688ab2b-7894-bbb5-d19d-8d26b6e820aa
* Content: [sys.dm_exec_plan_attributes (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-plan-attributes-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-exec-plan-attributes-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-plan-attributes-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@brettshearer -- Brett, thank you for your feedback.

@stevestein -- Steve, please look into this issue.

**Comment by rothja** [comment]
Apologies for the delayed response. @CarlRabeler Could you please look into this issue? Thank you! #reassign:CarlRabeler

**Comment by CarlRabeler** [comment]
@brettshearer researching ...

**Comment by CarlRabeler** [comment]
@brettshearer Per product team, please open a support case given that it worked in a previous version. 
Thanks, 
Carl
