### ISSUE TITLE
Specifying NULL string (NULL AS)

### ISSUE THREAD

**Issue by manikant-prasad** [MicrosoftDocs/sql-docs#4432]
There should be a way to specify the NULL string, which is not always BLANK and can have values like "NA", "NaN" etc, based on the source data. Almost all the COPY INTO commands have that option through "NULL AS" parameter. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e651729e-3c87-4b5f-22c6-4db750f0eed9
* Version Independent ID: 60781c40-06b8-3b7f-e55b-d02011d7f89e
* Content: [COPY INTO (Transact-SQL) (preview) - (SQL Data Warehouse) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/copy-into-transact-sql?view=azure-sqldw-latest#feedback)
* Content Source: [docs/t-sql/statements/copy-into-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/copy-into-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @kevinvngo
* Microsoft Alias: **kevin**

**Comment by WilliamAntonRohm** [comment]
@manikant-prasad -- Manikant, thank you for your suggestion.  Please add it here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
