### ISSUE TITLE
PARSENAME allows input longer than sysname

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/sql-docs#4433]
The documentation of the `PARSENAME` function states that the *object_name* parameter is **sysname**. According to [nchar and nvarchar (Transact-SQL)](https://docs.microsoft.com/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql), **sysname** is equivalent to **nvarchar(128) NOT NULL**. However, `PARSENAME` appears to support longer strings in the *object_name* parameter, so that *object_name* can consist of four 128-character names and each of those can be quoted. The actual type of the parameter is apparently not **sysname**; it may be **nvarchar(1035)** or even **nvarchar(4000)**.

```SQL
DECLARE @whole AS nvarchar(MAX);

SET @whole = QUOTENAME(REPLICATE(N']', 128))
	+ N'.' + QUOTENAME(REPLICATE(N']', 128))
	+ N'.' + QUOTENAME(REPLICATE(N']', 128))
	+ N'.' + QUOTENAME(REPLICATE(N']', 128));

SELECT
	LEN(name) AS length,
	PARSENAME(name, 1) AS object_name,
	PARSENAME(name, 2) AS schema_name,
	PARSENAME(name, 3) AS database_name,
	PARSENAME(name, 4) AS server_name
FROM (
	SELECT @whole UNION ALL
	SELECT CAST(@whole AS sysname)
) AS t (name);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e238279-e2e3-6b0c-dfc0-1fc6e7449df4
* Version Independent ID: 26fa833a-91d2-88d7-7840-4e71b41b2826
* Content: [PARSENAME (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/parsename-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/parsename-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/parsename-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@KalleOlaviNiemitalo -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue.

**Comment by rothja** [comment]
@KalleOlaviNiemitalo I'm sorry for the delay in response. @juliemsft Could you please look more into this issue? Thank you! #reassign:juliemsft

**Comment by julieMSFT** [comment]
@KalleOlaviNiemitalo Hello and thank you for contacting Microsoft. I am sorry for the delay in our response. Your observation is correct. If the object_name is a fully qualified name  it can have four parts: the server name, the database name, the owner name, and the object name. Each of these parts is type sysname. So if all four are present, the object_name is not type sysname.  I will update the document to reflect that each part is of type sysname.

**Comment by julieMSFT** [comment]
@KalleOlaviNiemitalo Hello, I have updated the article to reflect that the input parameter "object_name' can hold up to 512 bytes, 128 for each part of the 4 part name, server, database,schema,object. You should see the update soon. 
I will proceed with closing out this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#https://github.com/MicrosoftDocs/sql-docs-pr/pull/15228

**Comment by julieMSFT** [comment]
#please-close

**Comment by KalleOlaviNiemitalo** [comment]
> I have updated the article to reflect that the input parameter "object_name' can hold up to 512 bytes, 128 for each part of the 4 part name, server, database,schema,object.

@julieMSFT, I am not sure what you wrote in the article, because the change is not yet live and I am not authorized to access [MicrosoftDocs/sql-docs-pr#15228](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15228); but "512 bytes" is not enough because each of the four parts can have 128 UTF-16 code units rather than only 128 bytes. Even **nvarchar(512)** would not be enough because the separating dots, actual delimiters, and delimiters quoted by doubling them can add up to **1035** characters.

**Comment by julieMSFT** [comment]
#please-open

**Comment by julieMSFT** [comment]
@KalleOlaviNiemitalo Thank you for the additional information. I am checking with the engineering team as to the exact specs.

**Comment by julieMSFT** [comment]
@KalleOlaviNiemitalo Hello, the parameter will accept all four parts of the name with dots and or delimiters. The important thing functionality for this function is that each part of the name is less than 256 bytes. I have update the doc and you should see it later today. Again, thank you for your contribution to Microsoft Docs.
