### ISSUE TITLE
Example H is missing arguments

### ISSUE THREAD

**Issue by jn-altius** [MicrosoftDocs/sql-docs#4434]
I followed example H and got as far as CREATE EXTERNAL DATA SOURCE
When I run the code as shown above I get the error message "External data sources are not supported with type GENERIC."  A bit of bing-ing revealed that I needed to include the argument TYPE = RDBMS
When I include that and try again I get a new error message "Missing required external DDL option 'DATABASE_NAME'."
So I added that and got as far as CREATE EXTERNAL TABLE
When I follow example H and include a LOCATION I get the error message "LOCATION cannot be used with Error: 0, Severity: -1, State: 0. (Params:). The error is printed in terse mode because there was error during formatting. Tracing, ETW, notifications etc are skipped.
 data source."
Which is clearly munged, but I don't know what it should have said :-?

If I take the LOCATION out then I can create my EXTERNAL table but cannot query it because I get an error saying it cannot find the remote table.  This is because I have a dedicated schema for External tables (because there is an identically named table in my local db).

Can the example H be amended or expanded to show how to query a differently named table?  The present example does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ac2fe2-31da-7db6-2d5f-5091022f41d2
* Version Independent ID: bbf07c2c-7006-7b94-f12f-800fa7bc67e4
* Content: [CREATE EXTERNAL TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-table-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-external-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@jn-altius Please provide more detail. What version of SQL Server? Can you post the exact scripts you are using?

**Comment by jn-altius** [comment]
Hi @CarlRabeler

@@Version returns: Microsoft SQL Azure (RTM) - 12.0.2000.8   Feb 14 2020 18:30:14   Copyright (C) 2019 Microsoft Corporation 
--
The scripts are copied from Example H.
--
The CREATE MASTER KEY and CREATE DATABASE SCOPED CREDENTIAL work fine.  It is the CREATE EXTERNAL DATA SOURCE command that I am having trouble with.
--
CREATE EXTERNAL DATA SOURCE RemoteDatabase4
	WITH 
	( 
		TYPE = RDBMS, 
		LOCATION = 'nameremoved.database.windows.net',
		CREDENTIAL = ReLaCred 
	); 
GO
--
The above command returns the error message: "Missing required external DDL option 'DATABASE_NAME'."
--
CREATE EXTERNAL DATA SOURCE RemoteDatabase4
	WITH 
	( 
		LOCATION = 'nameremoved.database.windows.net',
		CREDENTIAL = ReLaCred 
	); 
GO
--
The above command returns the error message: "External data sources are not supported with type GENERIC."  According to Example H that 2nd command should work.

**Comment by jn-altius** [comment]
(I have no idea why that ended up all in bold face??  Sorry)

**Comment by CarlRabeler** [comment]
@jn-altius You are trying to run example H against an Azure SQL Database. Example H is intended for a SQL Server database rather than Azure SQL Database. In Azure SQL Database, external tables are intended for sharded databases and elastic query features. 

External table is a polybase feature that is supported by Azure Synapse Analytics (formerly Azure Data Warehouse) and SQL Server. 
https://stackoverflow.com/questions/41767573/create-a-table-in-azure-sql-database-from-blob-storage
https://stackoverflow.com/questions/33611170/unable-to-create-external-table-to-azure-sql-server-on-azure-sql-data-warehouse
https://stackoverflow.com/questions/41769329/cannot-create-external-table-on-azure-sql-databse
https://docs.microsoft.com/en-us/azure/synapse-analytics/sql/develop-tables-external-tables
