### ISSUE TITLE
Important Section

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#4435]
Hi,
This section...
" Important

If xp_cmdshell is executed within a batch and returns an error, the batch will fail. This is a change of behavior. In earlier versions of MicrosoftSQL Server the batch would continue to execute."

... Should include the version number when this was changed, or else the user has to change the version number on the left nav until they figure out which versions don't behave this way. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cae5e224-054d-8787-6b4d-5259a9057f9f
* Version Independent ID: 7c782643-2e58-de1b-b430-8f3ea38ec4c1
* Content: [xp_cmdshell (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/xp-cmdshell-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-stored-procedures/xp-cmdshell-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/xp-cmdshell-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@PrometheusRising1 thanks for bringing this to our attention. This note only applied to very old versions - now well out of support. So, I have removed the note.
You will see the updated version of this article later today.
