### ISSUE TITLE
Mention that ORDER BY variables are not supported 

### ISSUE THREAD

**Issue by vertonghenb** [MicrosoftDocs/sql-docs#4437]
Nice article, unfortunately the fact that you cannot use a variable in the ORDER BY clause is not entirely clear. Maybe add it to the remarks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d04ee6-6c35-a50f-2b95-1ab707143fa6
* Version Independent ID: 5d4ae5ce-40e8-b180-6e49-685e2e1a8878
* Content: [sp_executesql (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-executesql-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-executesql-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-executesql-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@vertonghenb -- Benjamin, thank you for your feedback.  Please clarify where you would like this information added, as there are no references to "ORDER BY" in that article.
