### ISSUE TITLE
Documenting 'Added in ' versions

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#4438]
Hi - it is almost impossible to tell when functions are added, and in what version.
By redirecting back to the most recent version (rather than the first version) when using the drop edit for version it makes it even harder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a829c6f-c86c-403b-67ae-3bbfffa59f45
* Version Independent ID: 1a67ec64-9d25-93e6-b021-56103b4399c2
* Content: [sys.fn_hadr_is_primary_replica (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/sys-fn-hadr-is-primary-replica-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-functions/sys-fn-hadr-is-primary-replica-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-functions/sys-fn-hadr-is-primary-replica-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@brettshearer -- Brett, thank you for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
