### ISSUE TITLE
wrong command mentioned

### ISSUE THREAD

**Issue by nitin0411** [MicrosoftDocs/sql-docs#4439]
tuned-amd profile mssql   ----- is wrong..it could be a typo error. actual command is

tuned-adm profile mssql

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc91cc25-7d13-a975-76ee-6d97bdcf9416
* Version Independent ID: ae8d2f7e-0c69-1269-a438-d6d36594dd27
* Content: [Performance best practices for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-performance-best-practices?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-performance-best-practices.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-performance-best-practices.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @tejasaks
* Microsoft Alias: **tejasaks**

**Comment by tejasaks** [comment]
Adding @Van To (SQL)<mailto:vanto@microsoft.com> to help correct the typo.

~Tejas Shah | Principal Program Manager | Data Platform – SQL Server

**Comment by WilliamAntonRohm** [comment]
@nitin0411 -- thank you for catching that.  I am looking into the document.

**Comment by WilliamAntonRohm** [comment]
@nitin0411 -- Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

@tejasaks, @VanMSFT -- this issue (#4439) is fixed with [private PR 14361](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14361).

**Comment by nitin0411** [comment]
Thanks Team for your prompt response..

Regards,
Nitin Khandelwal
________________________________

**Comment by WilliamAntonRohm** [comment]
You're welcome!
