### ISSUE TITLE
According to test, control permission on the database is not sufficient to run the stored procedure, need 'sysadmin' to run it.

### ISSUE THREAD

**Issue by tisun2** [MicrosoftDocs/sql-docs#4441]
According to test, control permission on the database is not sufficient to run the stored procedure, need 'sysadmin' to run it. Could you please double check what is the minimum permission to run this stored procedure? Thanks a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d965f05c-cc0b-e1d4-4b88-676c223077d5
* Version Independent ID: 5b50b875-f577-4c65-0b15-395f72a9d6cc
* Content: [sp_control_dbmasterkey_password (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-control-dbmasterkey-password-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-control-dbmasterkey-password-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-control-dbmasterkey-password-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@tisun2 -- thank you for your feedback.

@VanMSFT -- please review [private PR 14342](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14342).
