### ISSUE TITLE
Missing libicu for Debian

### ISSUE THREAD

**Issue by alesbobek** [MicrosoftDocs/sql-docs#4448]
There is missing instalation libicu on Debian.
If running sqlpackage, is complaining like: "Couldn't find a valid ICU package installed on the system."
I was solved for Debian Stretch by installing libicu57.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3df6af-9ac8-bc57-93dc-29ff713c1d3b
* Version Independent ID: 7624e2cc-7aa9-40dd-4015-3371ea2ea0a2
* Content: [Download and install sqlpackage - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/sqlpackage-download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage-download.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by alesbobek** [comment]
Note: I'm using package sqlpackage-linux-x64-en-US-15.0.4630.1.zip

**Comment by WilliamAntonRohm** [comment]
@alesbobek -- Aleš, thank you for your detailed feedback.

@pensivebrian -- Brian, please look into this issue.

**Comment by rothja** [comment]
@alesbobek Thanks for letting us know about this missing dependency on Debian. At this time, SQL Server is only tested/supported on the Ubuntu version of Debian. If the problem appears on Ubuntu, we would definitely want to document it. But we are unable to add caveats like this for all related distributions where SQL Server might run but isn't tested. Appreciate you sharing your work around for anyone else that might see this issue! Thank you, and apologies for the delayed response. #reassign:rothja
