### ISSUE TITLE
When did the naming convention of LocalDB for automatic instance changed?

### ISSUE THREAD

**Issue by ToMakeSense** [MicrosoftDocs/sql-docs#4449]
I found it was impossible to connection LocalDB with the connection string like: **Server=(localdb)\v13.0;Integrated Security=true**,  in this documentation the default name for the automatic instance is **MSSQLLocalDB**.  and the connection string is: **Server=(localdb)\MSSQLLocalDB;Integrated Security=true**

However, I used to use previous version LocalDB, which was not the case:
> The name for the automatic instance is a single v character followed by the LocalDB release version number in the format xx.x. For example, v11.0 represents SQL Server 2012.

This is the documentation: https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/hh510202(v=sql.110)?redirectedfrom=MSDN#automatic-and-named-instances 

Could you add documentation to specify this change? it's frustrated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea66ca27-e0b1-cd1e-a8ef-55911169c71a
* Version Independent ID: f2340ce9-9771-851e-60a7-237c6e55f085
* Content: [SQL Server Express LocalDB - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-2017#automatic-and-named-instances)
* Content Source: [docs/database-engine/configure-windows/sql-server-express-localdb.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/sql-server-express-localdb.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@ToMakeSense -- Kevin, thank you for your question.

@MashaMSFT -- Masha, please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @ToMakeSense , thank you for contacting Microsoft! My apologies, I'm not sure I understand.

Are you saying that when you try to connect using 
```
Server=(localdb)\MSSQLLocalDB;Integrated Security=true
```
it doesn't work?

Thanks!
Masha from the SQL Docs team

**Comment by ToMakeSense** [comment]
@MashaMSFT No, I didn't mean that. the new connection string below does work.
```
Server=(localdb)\MSSQLLocalDB;Integrated Security=true
```

 I was saying I tried to use the below connection string,  it didn't work.
```
Server=(localdb)\v13.0;Integrated Security=true
```
*Note that: I used this a few years ago in SQL Server LocalDB 2012, it's v11.0. I got SQL Server LocalDB 2016 installed, so it's v13.0 in the connection string.*


This technology is mentioned in this documentation: [sql-server-2012#automatic-and-named-instances](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/hh510202(v=sql.110)?redirectedfrom=MSDN#automatic-and-named-instances). 
![image](https://user-images.githubusercontent.com/6244148/78320289-b1b48580-759b-11ea-94ae-c6b1be23549b.png)

However, the naming convention change does not mentioned in the new documentation: [Automatic and named instances](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-2017#automatic-and-named-instances) . it's frustrated.
![image](https://user-images.githubusercontent.com/6244148/78320369-da3c7f80-759b-11ea-874e-ad0e984b3018.png)

**Comment by ToMakeSense** [comment]
@MashaMSFT see this blog who had the same confusion: https://www.michael-whelan.net/sql-server-localdb-2014-connection-string/

**Comment by MashaMSFT** [comment]
@ToMakeSense , just to make sure I understand correctly, although the documentation does have the correct connection string, you would like us to add an additional note pointing out the fact that the naming convention is different than previous versions?

Thanks!
Masha from the SQL Docs team

**Comment by ToMakeSense** [comment]
@MashaMSFT  Correct.

**Comment by MashaMSFT** [comment]
Hi @ToMakeSense , thanks for the clarification! Sure, we would be happy to add this note to help prevent any confusion. I will process this change and let you know once the article has been updated.

Thank you!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @ToMakeSense , thanks for bringing this to our attention! I have added a note to this doc highlighting the fact that the naming convention is different than previous versions :) 

I hope that helps and please let us know if we can be of further assistance? I am going to close out this Git Issue, but please feel free to comment should you need anything further.

Thanks again and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
