### ISSUE TITLE
sqlcmd doesn't print messages or results until "end-of-batch"

### ISSUE THREAD

**Issue by goranschwarz** [MicrosoftDocs/sql-docs#4450]
I'm using `sqlcmd` in a Linux environment, within maintenance scripts etc.   
When I have a SQL Statement that loops (waits for various status or similar) I want the output to be displayed at the client/sqlcmd so that waiting users can see what's happening (feedback to user/caller).

Here is an example sql file:
```
set nocount on
go
select getdate() as now 
go
declare @cnt int = 10
declare @time char(8)
while(@cnt>0)
begin
        SET @time= convert (varchar(30), getdate(), 8)
        RAISERROR ('RAISERROR with NOWAIT at: %s', 0, 1, @time) WITH NOWAIT -- <<<< I Expect THIS message to be displayed at the client side (which isn't happening)

        --select @time as ts ---- <<<< even if I add a "select" statement... the resultset isn't displayed until "end-of-batch"

        WAITFOR DELAY '00:00:01'
        set @cnt = @cnt - 1
end
go
```

Which I execute using `sqlcmd -Usa -Sprod-2a-mssql -Ppasswd -i /tmp/xxx.sql | gawk '{ print strftime("[%H:%M:%S]"), $0 }'`   
Piping output to gawk is just to "timestamp" the ouput, so it's easier to see that the output comes "as a chunk" **after** last *go*, The output is below
```
[12:03:52] now
[12:03:52] -----------------------
[12:03:52] 2020-04-01 12:03:52.993
[12:04:03] RAISERROR with NOWAIT at: 12:03:52
[12:04:03] RAISERROR with NOWAIT at: 12:03:54
[12:04:03] RAISERROR with NOWAIT at: 12:03:54
[12:04:03] RAISERROR with NOWAIT at: 12:03:55
[12:04:03] RAISERROR with NOWAIT at: 12:03:57
[12:04:03] RAISERROR with NOWAIT at: 12:03:58
[12:04:03] RAISERROR with NOWAIT at: 12:03:59
[12:04:03] RAISERROR with NOWAIT at: 12:04:00
[12:04:03] RAISERROR with NOWAIT at: 12:04:01
[12:04:03] RAISERROR with NOWAIT at: 12:04:02
```
Above you see that **all** output from the 'RAISERROR' is printed at the **same** timestamp `12:04:03`, after the SQL Batch is completed!

If you execute the same SQL Statement from SSMS, it will print out every 'RAISERROR' in a timely fashion (every second, as expected)

TDS is a **streaming** protocol, so `sqlcmd` should be able to do this (just as SSMS does)   
As Microsoft is entering the Linux world, the command line tools needs to **work** in a command line fashion :)

**Comment by WilliamAntonRohm** [comment]
@goranschwarz -- Goran, thank you for your detailed feedback.  Please add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
