### ISSUE TITLE
What does 'APPLIES TO' exactly mean?

### ISSUE THREAD

**Issue by GeorgePlotnikov** [MicrosoftDocs/sql-docs#4453]
Does `APPLIES TO: SQL Server` mean this functionality only appliable to an on-premises solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1d1286b-6090-4ede-9336-47b6028c5ab0
* Version Independent ID: 46479642-0189-f8fa-fdab-3220e1a2626f
* Content: [Automatic page repair for availability groups & database mirroring - SQL Server Always On](https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/automatic-page-repair-availability-groups-database-mirroring?view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/sql-server/failover-clusters/automatic-page-repair-availability-groups-database-mirroring.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/failover-clusters/automatic-page-repair-availability-groups-database-mirroring.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@GeorgePlotnikov -- George, thank you for your question.  Please refer to [Azure SQL Database Features](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-features).
