### ISSUE TITLE
A mistatement regarding identifiers

### ISSUE THREAD

**Issue by NovoaProgramming** [MicrosoftDocs/sql-docs#4454]
It is stated that "When SET QUOTED_IDENTIFIER is OFF, identifiers cannot be quoted and must follow all Transact-SQL rules for identifiers." but this is incorrect. Even with QUOTED_IDENTIFIER set to OFF you can use square brackets to break the standard Transact-SQL rules for identifiers.  I believe that as a point of clarification it's important to mention this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d2c9eb-91eb-3516-c95c-ad60a5f12e89
* Version Independent ID: e33be0cd-009f-9e4a-38f6-b1e6d92c14dc
* Content: [SET QUOTED_IDENTIFIER (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-quoted-identifier-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/set-quoted-identifier-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-quoted-identifier-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by NovoaProgramming** [comment]
A simple  example here:
SET QUOTED_IDENTIFIER OFF;
GO

CREATE TABLE [My Employees]
(MyColumn INT PRIMARY KEY)

SELECT * FROM [My Employees]

**Comment by CarlRabeler** [comment]
@pmasl please review

**Comment by pmasl** [comment]
I'll add a note specific to square brackets.

Thank you

**Comment by WilliamAntonRohm** [comment]
@NovoaProgramming -- thank you for your feedback.

@CarlRabeler, @pmasl -- thank you for replying.
