### ISSUE TITLE
Slight correction about determinism of built-in string functions.

### ISSUE THREAD

**Issue by rajucomp** [MicrosoftDocs/sql-docs#4456]
On the [page ](https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/deterministic-and-nondeterministic-functions?view=sql-server-ver15) about Deterministic and Nondeterministic Functions, it says "All of the string built-in functions are deterministic." whereas on this [page](https://docs.microsoft.com/en-us/sql/t-sql/functions/string-functions-transact-sql?view=sql-server-ver15) about String Functions, it says "All built-in string functions except FORMAT are deterministic. ". Maybe we could update the page about Deterministic and Nondeterministic Functions stating the same that is written on the page about String Functions.

**Comment by WilliamAntonRohm** [comment]
@rajucomp -- Raju, thank you for your close reading.  I am looking into these documents.

**Comment by WilliamAntonRohm** [comment]
@rothja -- Jason, please verify this in [private PR 14418](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14418).

**Comment by rajucomp** [comment]
Thanks. I can see the correct information on both the pages. Thanks a ton! Stay safe.
