### ISSUE TITLE
The document contains incorrect information.

### ISSUE THREAD

**Issue by TimonYang** [MicrosoftDocs/sql-docs#4459]
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15
This document says that Sqlserver localDB will be downloaded along with the .NET desktop development workload, but in vs2019, this is not the case. It is part of the ASP.NET and web development workload. Is this an error caused by a version change? Should the documentation be updated?

**Comment by WilliamAntonRohm** [comment]
@TimonYang -- thank you for your feedback.

@MashaMSFT -- please look into this issue.

**Comment by Matteo-T** [comment]
Yeah - the workload that installs SQL LocalDB is the "Data Store and Processing". Users can also go to the "Individual Components" tab during setup and add "SQL Server Express LocalDB" in case the selected workload does not have it.

**Comment by MashaMSFT** [comment]
Hi @TimonYang , thanks for bringing this to our attention! I have processed a change that updates this information in the doc. 

I hope that helps and please let us know if we can be of further assistance? I am going to close out this Git Issue, but please feel free to comment should you need anything further.

Thanks again and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
