### ISSUE TITLE
Proofread!

### ISSUE THREAD

**Issue by JohnBoncek** [MicrosoftDocs/sql-docs#4463]
Clearly, much of this page was never read after being written.  I'm not going to point out exactly where, because then only those instances would get corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8cf272b-3e28-160e-7e32-cf824766f87a
* Version Independent ID: cb16a55b-c7c3-8e5a-7b1e-9fb8d16cedc2
* Content: [CHAR (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/char-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/char-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/char-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@JohnBoncek -- thank you for your feedback.

cc @MikeRayMSFT for awareness
