### ISSUE TITLE
ALTER ROLE ... MEMBER is not supported on SQL Data Warehouse (Synapse)

### ISSUE THREAD

**Issue by shai-g** [MicrosoftDocs/sql-docs#4464]
ALTER ROLE ... MEMBER is not supported on SQL Data Warehouse (Synapse).
This is stated in https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-role-transact-sql?view=azure-sqldw-latest and is validated empirically.
This page needs to be corrected to reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d95c4e-dfbb-ec5a-7df9-8a8d33be5b83
* Version Independent ID: a35a9368-4e76-6d55-7e90-34e925b34dd7
* Content: [Database-Level Roles - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles?view=azure-sqldw-latest#feedback)
* Content Source: [docs/relational-databases/security/authentication-access/database-level-roles.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/database-level-roles.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@shai-g -- thank you for your feedback.

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
Hello @shai-g! Thank you for bringing this issue to our attention. I have updated the doc, and it should go live later today.

**Comment by lsnliu** [comment]
The original issue seem to still be an issue in 2022?  And the doc says it is supported? 

![image](https://user-images.githubusercontent.com/2326746/186022390-8de6f2c1-77a4-4632-9751-90def903b80c.png)

**Comment by WilliamAntonRohm** [comment]
@lsnliu -- thank you for your follow-up.

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
@lsnliu @WilliamAntonRohm - Thanks for catching this. I'm updating the Alter Role doc. The changes should go live later this week.
