### ISSUE TITLE
Azure SQL Database Support

### ISSUE THREAD

**Issue by NDSoul** [MicrosoftDocs/sql-docs#4467]
Hello, 

Azure SQL Database should not be selected as a supported product on this page as it does not have access to the SQL Agent.

Please revise. 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db6f2a8a-7b0a-b5b6-7095-b7569d2c23bb
* Version Independent ID: 26d6594a-6d7d-7091-0f4b-382bb4a38ebe
* Content: [Run Windows PowerShell Steps in SQL Server Agent - SQL Server](https://docs.microsoft.com/en-us/sql/powershell/run-windows-powershell-steps-in-sql-server-agent?view=sql-server-ver15)
* Content Source: [docs/powershell/run-windows-powershell-steps-in-sql-server-agent.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/run-windows-powershell-steps-in-sql-server-agent.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@NDSoul -- Tyler, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please verify this in [private PR 14419](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14419).
