### ISSUE TITLE
DEFAULT_DATABASE option is not supported in Azure

### ISSUE THREAD

**Issue by NaomiN** [MicrosoftDocs/sql-docs#4468]
It would be nice to clarify which options are available in Azure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0f4b3be-5686-ac31-8c5d-676e08953d8f
* Version Independent ID: 43881484-714e-d528-7a38-72d24a2d40d1
* Content: [CREATE LOGIN (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-login-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-login-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-login-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@NaomiN -- Naomi, thank you for your feedback.  Please add it here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
