### ISSUE TITLE
(KB 4548597) Invalid Link

### ISSUE THREAD

**Issue by frugecn** [MicrosoftDocs/sql-docs#4469]
The link for (KB 4548597) which is the article for CU4 of SQL 2019 throws a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1353d4d-3899-d6cf-e44f-8536c7828335
* Version Independent ID: de0210cf-386a-f8c8-1157-40cea207ed4b
* Content: [Latest updates for Microsoft SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/latest-updates-for-microsoft-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/install-windows/latest-updates-for-microsoft-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/latest-updates-for-microsoft-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @tmichael-ms
* Microsoft Alias: **tmichael**

**Comment by tmichael-ms** [comment]
Thanks for reporting this issue.  Actions are being taken to fix the broken URL link for SQL Server 2019 CU4.
