### ISSUE TITLE
Inaccurate statement

### ISSUE THREAD

**Issue by JamieChicago** [MicrosoftDocs/sql-docs#4470]
Locking Behavior

By default, a DELETE statement always acquires an exclusive (X) lock on the table it modifies, and holds that lock until the transaction completes.

This is only accurate if the number of rows being deleted requires an exclusive lock at the table level otherwise an intent exclusive lock would be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21fe0c8-0242-d9e0-b7bb-cee5265d39c9
* Version Independent ID: e70df047-67c6-7933-ccdd-11731a77eb20
* Content: [DELETE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/delete-transact-sql?view=azuresqldb-current#feedback)
* Content Source: [docs/t-sql/statements/delete-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/delete-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by cawrites** [comment]
@JamieChicago  Thank you for contacting Microsoft.

The SQL Server Database Engine often has to acquire locks at multiple levels of granularity to fully protect a resource. This group of locks at multiple levels of granularity is called a lock hierarchy. For example, to fully protect a read of an index, an instance of the SQL Server Database Engine may have to acquire share locks on rows and intent share locks on the pages and table.

Please review regarding intent locking:
https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@JamieChicago -- thank you for your feedback.

@cawrites -- thank you for your reply.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
