### ISSUE TITLE
OPENXML seems to work fine on Azure SQL Database

### ISSUE THREAD

**Issue by dudu-markovitz** [MicrosoftDocs/sql-docs#4474]
The "APPLIES TO" suggests that it works only for SQL Server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 051910dd-f368-8472-3068-d73a572d8650
* Version Independent ID: 316236f5-5c00-9584-7775-baf844c34a25
* Content: [OPENXML (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/xml/openxml-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/xml/openxml-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/xml/openxml-sql-server.md)
* Product: **sql**
* Technology: **xml**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
Fixed this Issue #4474 , with PR #14393 and #14395 .

---

@dudu-markovitz 
Hello, this Issue 4474 has now been fixed.  The fix should appear live on our Docs documentation website by the late afternoon of 2020/April/06 Monday.

Thank you for submitting this Issue. We hope to hear from you again.

---

MightyPen (G)

cc: @WilliamAntonRohm
