### ISSUE TITLE
innacurate information on section [Locking Behavior]

### ISSUE THREAD

**Issue by sammesel** [MicrosoftDocs/sql-docs#4475]
the document states that a ROW delete will always cause an EXCLUSIVE LOCK in the TABLE. this is incorrect. The delete of a single row will cause an IX lock in the table. if the DELETE operation affects more rows than what is specified for LOCK ESCALATION THRESHOLD (or under memory pressure to a lower number of rows), then the ENGINE may escalate the locks from individual ROWS into the TABLE. 
This can be easily demonstrated using SSMS with 2 sessions
-- session 1 
-- observe the session id, as it will be used on 2nd session
USE &lt;database&gt;
BEGIN TRANSACTION
  DELETE &lt;tablename&gt;
  WHERE &lt;condition to affect 1 single row&gt;
-- do not end the transaction for now

-- session 2
SELECT * FROM sys.dm_tran_locks WHERE request_session_id = &lt;session id from 1st session&gt;
-- you will notice IX on Table, another IX on the page storing the row being deleted, an X lock on the row being deleted

-- now go back to session 1 and issue:
ROLLBACK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21fe0c8-0242-d9e0-b7bb-cee5265d39c9
* Version Independent ID: e70df047-67c6-7933-ccdd-11731a77eb20
* Content: [DELETE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/delete-transact-sql?view=azuresqldb-current#feedback)
* Content Source: [docs/t-sql/statements/delete-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/delete-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@pmasl please review

**Comment by pmasl** [comment]
The lock type is IX of course. I think the term "exclusive" was used in the broader term that it prevents modifications, for users to understand the concept. Still, IX is the correct lock type, not X, and so I'm changing it.

**Comment by CarlRabeler** [comment]
Updated. Closing now. If you have further questions, please reopen or create new issue. Thanks.
