### ISSUE TITLE
The data type of the result may different than the input for decimal/numeric types

### ISSUE THREAD

**Issue by eric-miller-cdfw** [MicrosoftDocs/sql-docs#4477]
Calling FLOOR() on a NUMERIC(p, s) type yields a NUMERIC(p, 0). Those are not the same data type and can yield unexpected results due to implicit cast/convert behavior when part of a larger expression.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2948d996-d70e-593b-e6f6-9f902fd09bd3
* Version Independent ID: 63c2eeb2-7f6b-dcf1-9e77-73f95194943f
* Content: [FLOOR (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/floor-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/floor-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/floor-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rothja** [comment]
@eric-miller-cdfw I'm sorry for the delayed response on this issue. @juliemsft Could you please look more into this issue? Thank you! #reassign:juliemsft

**Comment by julieMSFT** [comment]
@eric-miller-cdfw Hello and thankyou for contacting Microsoft. I am reviewing your comments

**Comment by julieMSFT** [comment]
@eric-miller-cdfw Hi, I am trying to recreate your issue. Can you share an example of where this causes a problem?

**Comment by eric-miller-cdfw** [comment]
I'll try to dig up an example. It involved SUM(), multiplication and subtraction and sub queries. Unfortunately, I can't access the computer I was using at the time. So, I don't have some of the views/queries I was working on.

**Comment by julieMSFT** [comment]
@eric-miller-cdfw Hi Eric, I am going to close this issue for now. I would like to see your example so we can dig into this more. Once you find it, you can reply to this issue and we can continue to work on this as the @notification mechanism continues to work even after an item is closed. Thank you for contacting Microsoft and I hope to hear from you soon.

**Comment by julieMSFT** [comment]
#please-close
