### ISSUE TITLE
This page should not contain any reference to SHORTEST_PATH. Its not supported by SQL Server 2017

### ISSUE THREAD

**Issue by dmitribodiu** [MicrosoftDocs/sql-docs#4478]
Navigate to https://docs.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-shortest-path?view=sql-server-ver15
Take a look at: THIS TOPIC APPLIES TO:YesSQL Server 2019 and later. There 2 options: mistake is on this page, or on that page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9522c78a-6cdd-c5b0-4b5b-f7c6d0e5a241
* Version Independent ID: 27551083-bb07-638b-a491-7f5e4f94c22c
* Content: [MATCH (SQL Graph) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/match-sql-graph?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/queries/match-sql-graph.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/match-sql-graph.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @shkale-msft
* Microsoft Alias: **shkale**

**Comment by WilliamAntonRohm** [comment]
@dmitribodiu -- thank you for your feedback.  Apologies for the delay in responding.

@shkale-msft -- Shreya, please look into this issue.

**Comment by rothja** [comment]
@dmitribodiu Thank you for submitting this feedback, and apologies for the delay. 

@shkale-msft Shreya, could you help to clarify the version of SQL Server that these articles should apply to:

1. [SHORTEST_PATH (Transact-SQL)](https://docs.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-shortest-path?view=sql-server-ver15) states that it applies to SQL Server 2019 as well as Azure SQL.
2. [MATCH (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/queries/match-sql-graph?view=sql-server-2017) states that it applies to SQL Server 2017 and later and not Azure SQL.

Please let us know what this should say, and I can help make the change if needed, or you can submit a pull request to fix. Thank you!

**Comment by rothja** [comment]
@shkale-msft Let me know if you can take a look at this issue. Thank you!

**Comment by MikeRayMSFT** [comment]
Emailed @shkale-msft

**Comment by MikeRayMSFT** [comment]
Messaged PM again.

**Comment by MikeRayMSFT** [comment]
@dmitribodiu - first allow me to apologize for the delayed response. 

The support for the features are:

* `SHORTEST_PATH` applies to sql server 2019 and above and Azure sql
* `MATCH` applies to sql server 2017 and up and Azure SQL DB
* both `SHORTEST PATH` and `MATCH` work on managed instance too

I'll stage an appropriate doc update. 
Mike
