### ISSUE TITLE
Bad link in article

### ISSUE THREAD

**Issue by DieselAnalytics** [MicrosoftDocs/sql-docs#4485]
The https://github.com/Microsoft/sqlmlutils/tree/master/Python/dist  link in this article is broken. In addition to this, the information at https://github.com/microsoft/sqlmlutils is different than the information in this article. Which is correct? If this article is correct can you please update the link? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb790fba-2d19-b1a7-3935-6ec5f9207fcc
* Version Independent ID: f350cf6b-0fa8-6d76-8433-f3f752e62ecf
* Content: [Install Python packages with sqlmlutils - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/package-management/install-additional-python-packages-on-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/machine-learning/package-management/install-additional-python-packages-on-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/package-management/install-additional-python-packages-on-sql-server.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by WilliamAntonRohm** [comment]
@DieselAnalytics -- Ryan, thank you for your feedback.

@garyericson -- Gary, please look into this issue.

**Comment by garyericson** [comment]
@DieselAnalytics - Thanks for reporting this! Somehow the dist folder on GitHub was removed accidentally. It's been added back so the link works now.

#please-close

**Comment by ryanwadebg** [comment]
@garyericson and @WilliamAntonRohm,

Thanks for the prompt response! I will test this weekend.
