### ISSUE TITLE
Facing issue while creating external table

### ISSUE THREAD

**Issue by sidtandon2014** [MicrosoftDocs/sql-docs#4487]
Hi,

If I use below command, there is an error

> Invalid configuration value detected for fs.azure.account.key'

CREATE DATABASE SCOPED CREDENTIAL ADL_User
WITH
    IDENTITY = '<client_id>@\<OAuth_2.0_Token_EndPoint>',
    SECRET = '<key>'
;

but if I use Storage account name (for identity) and primary key (as secret) its working. 
There is a backward slash after "client_id@". Is that required?

**Comment by WilliamAntonRohm** [comment]
@sidtandon2014 -- thank you for your question.  Please provide a link to the docs.microsoft.com article you're reading, or provide more context around your task.
