### ISSUE TITLE
apt-get / pip consistency when unistalling azdata

### ISSUE THREAD

**Issue by chrisadkin** [MicrosoftDocs/sql-docs#4488]
In the corresponding section for installing azdata via apt-get, the following command is used for uninstalling azdata:

pip freeze | grep azdata-* | xargs pip uninstall -y

For the puproses of consistency, should the same command also be used on this page ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58e35029-c023-aeba-0bee-5b0444342507
* Version Independent ID: 0c41c7ec-5513-b0b1-f5eb-6cf239a5be7e
* Content: [Install azdata using pip - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-azdata-pip?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/deploy-install-azdata-pip.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-install-azdata-pip.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@chrisadkin -- Chris, thank you for your close reading.  Please add your suggestion here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
