### ISSUE TITLE
Add SQL Server version this method applies to

### ISSUE THREAD

**Issue by praneetnadkar** [MicrosoftDocs/sql-docs#4492]
For SQL Server functions usage, it would be great if it is given that what is the minimum version of SQL Server that is required for this function to compile. Like in which version of SQL Server was this function introduced.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277a5d00-6fcf-a830-0451-f0667dd806e8
* Version Independent ID: ac998a63-0675-de0c-c528-4b355c1d9d5f
* Content: [EOMONTH (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/eomonth-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/eomonth-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/eomonth-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@k7shanmugam -- K7, thank you for your feedback.  Please add your suggestion here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
