### ISSUE TITLE
SSPROPT_INIT_CURRENTLANGUAGE should be SSPROP_INIT_CURRENTLANGUAGE

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/sql-docs#4494]
This page mentions the initialization property `SSPROPT_INIT_CURRENTLANGUAGE` three times. However, &lt;sqloledb.h&gt; in Windows SDK 10.0.18362.0 does not define that name and instead defines `SSPROP_INIT_CURRENTLANGUAGE`:

```C
//----------------------------------------------------------------------------
// PropIds for DBPROPSET_SQLSERVERDBINIT 
#define SSPROP_INIT_CURRENTLANGUAGE		4
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7197d3b-5829-e8f5-7245-e51869cc0836
* Version Independent ID: 40f0e4c5-95eb-24e0-6f0f-2776c8f89bb0
* Content: [Native Client, connection keywords SQL - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client.md)
* Product: **sql**
* Technology: **native-client**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by WilliamAntonRohm** [comment]
@KalleOlaviNiemitalo -- thank you for catching this.  I am looking into the document.
