### ISSUE TITLE
misspelling on this page

### ISSUE THREAD

**Issue by scorellis** [MicrosoftDocs/sql-docs#4496]
"aatabase" should be "database"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81b4b8ea-3a1e-8e54-210d-1366b5d30556
* Version Independent ID: 9cc8729d-6289-7043-156e-d1051a7d02c0
* Content: [Database Detach and Attach (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-detach-and-attach-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/databases/database-detach-and-attach-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/database-detach-and-attach-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@scorellis - thanks for the feedback.  Fix should go live soon.

Thanks!

**Comment by scorellis** [comment]
Any time! Thanks for fixing it so quickly!
