### ISSUE TITLE
makecert

### ISSUE THREAD

**Issue by kaysauter** [MicrosoftDocs/sql-docs#4498]
Makecert is deprecated, so I think it would make sense to state it here in brackets and also name its successor, the cmdlet New-SelfSignedCertificate (https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0153ed-c27e-ee8e-ec46-9b23e7333a49
* Version Independent ID: ed29baef-027e-b3c6-9272-c865b29b9fc8
* Content: [SQL Server Certificates and Asymmetric Keys - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/sql-server-certificates-and-asymmetric-keys?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/sql-server-certificates-and-asymmetric-keys.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/sql-server-certificates-and-asymmetric-keys.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@kaysauter -- Kay, thank you for your research and feedback.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please review [private PR 14505](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14505).
