### ISSUE TITLE
Feedback regarding missing documentation on Server Level  permissions

### ISSUE THREAD

**Issue by NovoaProgramming** [MicrosoftDocs/sql-docs#4499]
I cannot find any documentation on what these Server permissions actually do in any level of detail. I'm also confused about what the "implied by" column is indicating.

Any clarity that can be provided in the documentation here would be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83e5f29-dca4-dde6-4abc-ba38715477d0
* Version Independent ID: 0e0a550e-f7e7-49a0-adca-417e5f5720e2
* Content: [GRANT Server Permissions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-server-permissions-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/grant-server-permissions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/grant-server-permissions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by NovoaProgramming** [comment]
I should add that what I'm suggesting is that that all of these permissions have details added like connect any database, impersonate any login, and select all user securables all have under remarks. Most of these have no further details available.

**Comment by WilliamAntonRohm** [comment]
@NovoaProgramming -- thank you for your feedback.  Each "Implied by" permission is a superset of that row's permission, that is, having CONTROL SERVER permission includes the ADMINISTER BULK OPERATIONS permission.

@VanMSFT -- please look into this issue.

**Comment by RobAshton-IM** [comment]
@WilliamAntonRohm, @VanMSFT --
I agree with @NovoaProgramming here. MS Docs does a good job of describing the relationships in the permissions hierarchy of SQL Server, but it doesn't appear to have a comprehensive list of what actions or capabilities in SQL Server are governed by a specific server-level permission. This page currently only describes the three server permissions that were added in SQL Server 2014 (CONNECT ANY DATABASE, IMPERSONATE ANY LOGIN, and SELECT ALL USER SECURABLES), but doesn't touch on any of the other permissions at this scope.

For example:
- ALTER ANY LOGIN allows a user to create, drop, or modify logins, and is implicitly granted to the "securityadmin" fixed server role.
- ALTER SETTINGS allows a user to execute the sp_configure system stored procedure and use the RECONFIGURE keyword to make server setting changes.

Currently, readers seeking to understand this level of information have to rely on third party sources which may or may not be accurate at the time of writing, and they may not be kept up-to-date when changes to the SQL Server permissions hierarchy are made over versions of the product.

**Comment by VanMSFT** [comment]
@NovoaProgramming @RobAshton-IM - Thanks for submitting this issue! You're right that we could use more clarity in our documentation for granting permissions. Our Permissions naming convention and details can be found in the following doc: https://docs.microsoft.com/sql/relational-databases/security/permissions-database-engine?view=sql-server-ver15#_conventions

We also have a chart that explains the relationship between permissions here: https://docs.microsoft.com/sql/relational-databases/security/permissions-database-engine?view=sql-server-ver15#chart-of-sql-server-permissions

Does that help with your question?

**Comment by RobAshton-IM** [comment]
@VanMSFT, not really, no.

The naming conventions help when trying to understand permissions on object scopes lower than the entire server level (DATABASE, SCHEMA, OBJECT, etc.), but here we're talking specifically about the server-level permissions broken down in the first "Remarks" section on this page. While some of those permissions can be mapped to a lower level in the permissions hierarchy, several can't. The ones that can't usually relate to capabilities in SQL Server that are not obvious from the name of the permission.

For example, what exactly does the "AUTHENTICATE SERVER" permission let a server principal do? What effects can occur if it explicitly denied to a server principal? I can't infer enough of the permission's purpose from the name of the permission nor from its position in the permissions hierarchy to understand the ramifications of allowing (or disallowing) it, and that's what I would hope to be able to find here.

**Comment by NovoaProgramming** [comment]
I would say that the chart @VanMSFT shared certainly is helpful as a high level reference, and provides more information than the GRANT Server Permissions page itself, but it lacks the type of extra information that I think a documentation page on permissions at each level could ideally provide. 

Continuing with @RobAshton-IM 's example of AUTHENTICATE SERVER , the only additional information the chart provides is that it "allows server-level delegation" and perhaps I'm in over my head and should understand what that means, but without any further information or the exact consequence of explicitly granting or denying that permission I'm not much better of having viewed either the documentation page or the chart.

**Comment by VanMSFT** [comment]
Thank you everyone for the discussion. This is something I will review with the Product Team, and see if we can provide clearer documentation. We appreciate the input.

**Comment by VanMSFT** [comment]
Hi All,

Thanks for the discussion on this. We realize that the current documentation on permissions needs work, and I've discussed this internally. As you've already noted, the permissions are intricate and there are some layers not explained in documentation. We will need to re-think this, and it will involve a lot of work. This is not something that can be completed in a short amount of time. As such, I will go ahead and close this discussion, but will track this with an internal work item. We appreciate everyone's feedback!

Regarding the AUTHENTICATE SERVER permissions, this has to do with server level delegations, and the ability to pass on credentials. This permission should not affect or be granted to individual principals. 

Thanks,
Van

@AndreasWolter - FYI

**Comment by AndreasWolter** [comment]
acknowledging and agreeing with Van
