### ISSUE TITLE
Please always include data type - other scalar functions do

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#4501]
Is 1 a bool or an int or something else?
I got caught because I didn't have always on and it got to functional review to find it was a bool.
This is the same for fn_hadr_backup_is_preferred_replica

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a829c6f-c86c-403b-67ae-3bbfffa59f45
* Version Independent ID: 1a67ec64-9d25-93e6-b021-56103b4399c2
* Content: [sys.fn_hadr_is_primary_replica (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/sys-fn-hadr-is-primary-replica-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-functions/sys-fn-hadr-is-primary-replica-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-functions/sys-fn-hadr-is-primary-replica-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@brettshearer -- Brett, thank you for your feedback.  I have updated those documents.

@MikeRayMSFT -- Mike, please review [private PR 14507](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14507).
