### ISSUE TITLE
event_file wrong destination target generates access violation dump

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#4504]
@Park-minkyu commented on [Tue Apr 07 2020](https://github.com/MicrosoftDocs/sql-docs.ko-kr/issues/117)

if you specify extended event event_file target as shown below,
if you starting event session that will generates error 596 and access violation dump.

I also posted same issue on azure feedback still have no response for 2 years..
If this issue has fixed, can you address me of fixed version?

https://feedback.azure.com/forums/908035-sql-server/suggestions/32895931-extended-events-creates-dump-when-destination-file
--
add target package0.event_file (
	set 
		filename	= N'N'DRIVE_EXISTS:\FOLDER_DOES_NO_EXISTS\query_check.xel'
) 

ALTER event SESSION [your_event_session] on server 
state = START
GO

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 923bd786-410a-0e1c-6519-4971035a9dbd
* Version Independent ID: 4142e15a-1b9e-f4ae-86eb-46871fb8aa72
* Content: [SQL Server에서 확장 이벤트에 대한 대상 - SQL Server](https://docs.microsoft.com/ko-kr/sql/relational-databases/extended-events/targets-for-extended-events-in-sql-server?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/extended-events/targets-for-extended-events-in-sql-server.md](https://github.com/MicrosoftDocs/sql-docs.ko-kr/blob/live/docs/relational-databases/extended-events/targets-for-extended-events-in-sql-server.md)
* Product: **sql**
* Technology: **xevents**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

---

@srvbpigh commented on [Tue Apr 07 2020](https://github.com/MicrosoftDocs/sql-docs.ko-kr/issues/117#issuecomment-610190485)

Hello, @Park-minkyu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@MightyPen commented on [Tue Apr 07 2020](https://github.com/MicrosoftDocs/sql-docs.ko-kr/issues/117#issuecomment-610194526)

I suspect this feedback Issue 117 is more a claim of a product BUG, not a claim of a Documentation bug.

---

@Park-minkyu commented on [Tue Apr 07 2020](https://github.com/MicrosoftDocs/sql-docs.ko-kr/issues/117#issuecomment-610196287)

@MightyPen  Yes, exactly. 
But I think that every persons who read this article may have a same question I had. 
"Why I can't find any information about this issue on earth?"

So if you think this feedback is an inappropriate for this article I will close and delete this issue.

---

@Park-minkyu commented on [Tue Apr 07 2020](https://github.com/MicrosoftDocs/sql-docs.ko-kr/issues/117#issuecomment-610198268)

or we could add information message that if you specify folder name that does not exists could generates error on sql server version below xx.xx.x;

**Comment by MightyPen** [comment]
@rothja @MashaMSFT @MikeRayMSFT Maybe a person on the SQL Content team can give @CeciAc a link to a tool for forum that is better suited to product Bugs to be filed?
Thanks.

**Comment by rothja** [comment]
@CeciAc I think the feedback forum item that was already filed is the right person to put this product feedback. We typically don't document bugs in the content, so I don't think there is any action here at this time. Thank you!
