### ISSUE TITLE
modify view

### ISSUE THREAD

**Issue by BarisKocaman55** [MicrosoftDocs/sql-docs#4505]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: babbabb2-6b2b-b436-f312-5e912688e447
* Version Independent ID: 33c2333f-9f28-68c3-acb9-17e5df03a0e0
* Content: [Modify Views - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/views/modify-views?view=sql-server-ver15)
* Content Source: [docs/relational-databases/views/modify-views.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/views/modify-views.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@BarisKocaman55 -- thank you for your feedback.  Please provide more context around your issue and task.
