### ISSUE TITLE
Include new parameters

### ISSUE THREAD

**Issue by tiagobalabuch** [MicrosoftDocs/sql-docs#4510]
Section "azdata bdc upgrade" should be updated to reflect changes made in CU2 that introduced new parameters option --controller-timeout and --component-timeout as describe here: https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-upgrade?view=sql-server-ver15#increase-the-timeout-for-the-upgrade

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 664800ce-d1cd-0ef1-f1b1-ac29e3a0e70d
* Version Independent ID: 88acde31-c5df-8b82-b447-8a982bca13b9
* Content: [azdata bdc reference - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata-bdc?view=sql-server-ver15#azdata-bdc-upgrade)
* Content Source: [docs/big-data-cluster/reference-azdata-bdc.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/reference-azdata-bdc.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@tiagobalabuch -- Tiago, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by MikeRayMSFT** [comment]
These were added.
