### ISSUE TITLE
locking section seems too simple

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/sql-docs#4513]
In my experience, `UPDATE` often does range locking instead of exclusive table locking. This allows multiple concurrent transactions to modify different rows. The locking section on this page seems to oversimplify things. Could it be expanded to explain when one would get different sorts of locks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc5aa35c-e2c9-1cce-0026-6aae93b30504
* Version Independent ID: 85e9daaa-2af1-95c6-8795-75976c36ccba
* Content: [UPDATE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/queries/update-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/update-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@binki -- Nathan, thank you for your feedback.  The article states:
> An UPDATE statement always acquires an exclusive (X) lock on the table it modifies, and holds that lock until the transaction completes. With an exclusive lock, no other transactions can modify data. 

> You can specify table hints to override this default behavior for the duration of the UPDATE statement by specifying another locking method, however, we recommend that hints be used only as a last resort by experienced developers and database administrators. 

> For more information, see [Table Hints (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table?view=sql-server-ver15).

I hope this answers your question.

**Comment by binki** [comment]
@WilliamAntonRohm I am saying that I am pretty certain that the part of the documentation which you copied and pasted is incorrect or too vague. That’s the exact language which caused me to open this issue.

I think that might be true for an `UPDATE` without a `WHERE` clause. But an `UPDATE` with criteria can do things like taking out non-table-level locks such as index range locks, allowing other transactions to modify the table prior to the current transaction completing.

**Comment by WilliamAntonRohm** [comment]
@binki -- Nathan, thank you for clarifying.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Looking into the issue.

**Comment by VanMSFT** [comment]
Hi @binki! Thanks for the feedback and suggestion. I have updated the Locking behavior section based on feedback from our Product Team. The text will be updated later today.

**Comment by binki** [comment]
Thanks. That looks much better!
