### ISSUE TITLE
Compatability with SQL Server 2019

### ISSUE THREAD

**Issue by ChrisSommers** [MicrosoftDocs/sql-docs#4514]
The download page https://www.microsoft.com/en-us/download/details.aspx?id=45344 does not mention SQL Server 2019. Is it compatible/supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4997f245-c966-51a3-34c7-705c3cfbd4b0
* Version Independent ID: 129fbe40-3b02-f2c1-ef13-b42d86ffdb77
* Content: [Setup TDE Extensible Key Management with Azure Key Vault - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-ver15#next-step)
* Content Source: [docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by ChrisSommers** [comment]
It also only mentions Server 2012/R2. We'd like to use this on Server 2019 with SQL 2019

**Comment by WilliamAntonRohm** [comment]
@ChrisSommers -- thank you for your question.

@jaszymas -- please look into this potential documentation issue.

**Comment by ChrisSommers** [comment]
This SQL 2019 article mentions it so I presume it is compatible: https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/enable-tde-on-sql-server-using-ekm?view=sql-server-ver15

**Comment by astretch** [comment]
@ChrisSommers - I have SQL 2019 running fine with TDE / EKM using the Azure Key Vault and SQL Connector, but I'll leave it to Microsoft to give you an official answer. Please note that you need to install the Visual C++ Redistributable Packages for Visual Studio 2013 as opposed to the 2015 version specified for 2016.

**Comment by VanMSFT** [comment]
Hi! Sorry for the delay. SQL Server Connector is supported for SQL Server 2019. I believe the download page has been updated. Thanks for your inquiry!
