### ISSUE TITLE
Ambiguity on OLE DB Driver 18 for SQL Server download page

### ISSUE THREAD

**Issue by williamadba** [MicrosoftDocs/sql-docs#4515]
Not sure where to file this issue to, trying here.
The "Microsoft® OLE DB Driver 18 for SQL Server®" download page allows you to download two identically named files with no disambiguation. Obviously, one is for 32bit and one is for 64bit, but the page provides no way to tell which one. 
Problem is on download site here: https://www.microsoft.com/en-us/download/details.aspx?id=56730
Can we get some identifying information associated here when choosing which of the files to download? Confusing to have no way to tell which one is 64bit.

**Comment by WilliamAntonRohm** [comment]
@williamadba -- William, thank you for your feedback.  The larger file is the 64-bit version.

You're welcome to add your suggestion here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
