### ISSUE TITLE
Synapse - Service Objective

### ISSUE THREAD

**Issue by stevej-arbela** [MicrosoftDocs/sql-docs#4518]
Msg 104385, Level 16, State 1, Line 1
Catalog view 'database_service_objectives' is not supported in this version.
Completion time: 2020-04-08T22:45:42.6399267-04:00

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228c33b8-2005-40e1-584a-77c32b0433f8
* Version Independent ID: 96b3d88c-7343-48a5-37bb-854a94471be1
* Content: [sys.database_service_objectives - Azure SQL Database](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-service-objectives-azure-sql-database?view=azure-sqldw-latest#feedback)
* Content Source: [docs/relational-databases/system-catalog-views/sys-database-service-objectives-azure-sql-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-database-service-objectives-azure-sql-database.md)
* Service: **sql-database**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@stevej-arbela -- thank you for your feedback.  Which version are you using?

**Comment by msebolt** [comment]
Closing this now, please comment below if there are further issues.
