### ISSUE TITLE
Images are not legible when using the dark theme

### ISSUE THREAD

**Issue by davidsk** [MicrosoftDocs/sql-docs#4519]
The labels in the images within the https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/complete-database-restores-simple-recovery-model?view=sql-server-ver15#Overview section are not clear when using the dark theme.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2053f61-70d6-8b93-06bd-6ba26c3402da
* Version Independent ID: 83587c09-f6e2-47a5-d2a3-ea08d414dcd0
* Content: [Restore database - simple recovery model - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/complete-database-restores-simple-recovery-model?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/backup-restore/complete-database-restores-simple-recovery-model.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/complete-database-restores-simple-recovery-model.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @davidsk, thanks for bringing this to our attention! Let me see what we can do about it :) 

Thanks!
Masha from the SQL Docs team

**Comment by rothja** [comment]
@davidsk I'm going to be updating those images today. Your issue will close when the changes have been merged in. Thanks, again, for letting us know! #assign:rothja
