### ISSUE TITLE
The KB links arent working 

### ISSUE THREAD

**Issue by anishkunisetty** [MicrosoftDocs/sql-docs#4521]
https://go.microsoft.com/fwlink/?LinkId=237321 is not working 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 149fddbd-9772-a8c5-733d-706c3d437baf
* Version Independent ID: 691e1dbf-5ff5-d881-eb14-f84ad2a45fd5
* Content: [Install SQL Server with SMB fileshare storage - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-with-smb-fileshare-as-a-storage-option?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/install-windows/install-sql-server-with-smb-fileshare-as-a-storage-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/install-sql-server-with-smb-fileshare-as-a-storage-option.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @anishkunisetty , thanks so much for bringing this to our attention! Let me look into this :)

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @anishkunisetty , thanks again for contacting Microsoft and helping improve our documentation! My sincerest apologies for the delay, the last few months have been extra hectic :) I have created an internal work item ([1744245](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1744245)) to track this work and hope to have this fixed for you this month.

I'm going to close out this Git Issue for the time being but please feel free to comment should you need anything further.

Thanks again and hope you have a wonderful rest of your day!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @anishkunisetty , I just wanted to let  you know that I have processed a change and the link should be fixed later this week.

Thanks again for improving our docs!
Masha from the SQL Docs team
