### ISSUE TITLE
Windows Server 2008 only?

### ISSUE THREAD

**Issue by rmcgarry** [MicrosoftDocs/sql-docs#4522]
https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/install/before-installing-failover-clustering?view=sql-server-ver15#OS_Support

This is a current document for SQL Server 2019, yet there are only references to Windows Server 2008 and Windows Server 2008R2.

Please update references to the operating systems supported in a FCI, and include any notes specific to more recent versions of Windows Server, including 2016 and 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30225758-8196-5216-31fc-8380133d577e
* Version Independent ID: 4718f672-8fd8-9956-45dc-4329bfcc0b7b
* Content: [Before Installing Failover Clustering - SQL Server Always On](https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/install/before-installing-failover-clustering?view=sql-server-ver15#OS_Support)
* Content Source: [docs/sql-server/failover-clusters/install/before-installing-failover-clustering.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/failover-clusters/install/before-installing-failover-clustering.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@rmcgarry -- thank you for your feedback.

@MashaMSFT -- please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @rmcgarry , thanks for contacting Microsoft! You're right, this should not be SQL Server 2019. I am processing a change that will update this page.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @rmcgarry , thanks for bringing this to our attention! Upon further review, there are a few inaccuracies in this article. I have created an internal work item ([1709977](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1709977)) to review this article thoroughly. 

I will close out this Git Issue in the meantime but please feel free to comment should you need anything in the meantime.

Thanks!
Masha from the SQL Docs team

**Comment by rmcgarry** [comment]
Thank you!  It was difficult to determine what sections still applied, and
which did not, and having to figure out what still applied through trial
and error.

I appreciate your quick and thoughtful responses, and look forward to
seeing what I got wrong.  :)


Thanks again,
Ryan McGarry

**Comment by MashaMSFT** [comment]
@rmcgarry , so sorry about the negative experience! It may be just a bit before we can publish the rewrite for this, but I'll let you know once the changes are live :) And thanks again for providing your feedback and helping improve our documentation!

If there are specific questions that you have, I can try to address them before publishing the rewrite. For example, the hardware and software articles list current OS compatibilities: 

[SQL 2016 & 2017](https://docs.microsoft.com/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15?view=sql-server-ver15#TOP_Principal)
[SQL 2019](https://docs.microsoft.com/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15?view=sql-server-ver15#TOP_Principal)

Thanks!
Masha from the SQL Docs team
