### ISSUE TITLE
Managed engine SQL database with replication

### ISSUE THREAD

**Issue by SQLDBA346** [MicrosoftDocs/sql-docs#4527]
Restored failed. I've been trying to restore sql database from prod to non-prod environments. Both source and destination are managed instance. In prod, I've configured Transactional replication from Managed instance database as publisher and azure SQL database as a subscriber. The issue is I cannot able to restore QA database with prod backup. It has been failing. I had to remove replication, take a backup and restore to QA.  

Error: 
Msg 208, Level 16, State 1, Line 48
Invalid object name 'dbo.sysextendedarticlesview'.
Cannot drop the table 'dbo.MSpeer_lsns' because it is being used for replication.
Database '29db7953-014e-XXXXX-a41d-XXXXXXXXXXXX' was restored, however an error was encountered while replication was being restored/removed. The database has been left offline. See the topic MSSQL_ENG003165 in SQL Server Books Online.
RESTORE DATABASE is terminating abnormally.
Msg 3013, Level 16, State 1, Line 48
RESTORE DATABASE is terminating abnormally.

I dont see the database offline at the destination.  Any inputs will be appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf165912-1223-f858-f9a5-9ff835e35da7
* Version Independent ID: e376568f-5539-fee6-a91d-7eb8422f286b
* Content: [MSSQL_ENG003165 - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/mssql-eng003165?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/replication/mssql-eng003165.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/mssql-eng003165.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by SQLDBA346** [comment]
Correction: Managed Instance

**Comment by MashaMSFT** [comment]
Hi @SQLDBA346 , thank you for contacting Microsoft! I'm so sorry to hear you're running into issues! I really wish I could help but unfortunately this forum is intended for feedback on the documentation, and not with the product. 

To get further assistance with your issue, we'd recommend engaging the community, or opening a ticket with Microsoft Support. More information can be found here: [https://docs.microsoft.com/sql/sql-server/sql-server-get-help](https://docs.microsoft.com/sql/sql-server/sql-server-get-help).

If you're looking to provide suggestions or ideas for improvement for the product,  you can do so at [https://aka.ms/sqlfeedback](https://aka.ms/sqlfeedback).

Our apologies that the SQL Docs team was unable to assist you further with your issue, but we appreciate you reaching out. Please let us know if there's anything more we can do for you.

Thanks again and hope you have a wonderful rest of your day!
Masha from SQL Docs team
