### ISSUE TITLE
distributor in AG

### ISSUE THREAD

**Issue by kurt6794** [MicrosoftDocs/sql-docs#4528]
Found unexpected behavior when 
1) Create 2 named distribution instances
-DIST1\distribution
-DIST2\distribution
2) Create the distribution database on DIST1\distribution
3) Create an AG for distribution database with replicas on DIST1\distribution, DIST2\distribution. And configure a listener for this AG

When run "sp_adddistributiondb 'distribution'" on DIST2\distribution to add distributor in AG - I get next error:
"Msg 3906, Level 16, State 2, Line 1
Failed to update database "distribution" because the database is read-only."

NOTE: that error does not happen when run not on named instance like DIST2
Reproduce on SQL2016 and SQL2017
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e9c3cd5-47b1-8118-b2c1-cd7b9bc64869
* Version Independent ID: e6e4741f-4646-bc21-cb41-a5dbc95b1622
* Content: [Configure distribution database in availability group - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/configure-distribution-availability-group?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/replication/configure-distribution-availability-group.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/configure-distribution-availability-group.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@kurt6794 -- thank you for your feedback and researches.  Please add your issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
