### ISSUE TITLE
Copy Database Wizard - Display Issues with Overlapping Elements

### ISSUE THREAD

**Issue by singicus** [MicrosoftDocs/sql-docs#4530]
Thank you for the latest update to SSMS!  There may still be issues that were reported as fixed in 18.5  The elements here overlap.  I have run Import Export Settings > Set to Default so that the default settings are being used in the application. Since you reported the particular dialog as having issues addressed, I thought you'd want to see this.
![image](https://user-images.githubusercontent.com/2279558/79027670-1ef78600-7b5b-11ea-8ae6-eda22237acc8.png)

Here is the same dialog in version 17 on my machine, which may have some custom settings applied:
![image](https://user-images.githubusercontent.com/2279558/79027852-d55b6b00-7b5b-11ea-9f5e-8aa1af154873.png)
If there is anything you'd like to have confirmed or anything I should try to address this, I am willing to help or to try suggestions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@singicus -- thank you for your feedback.  Please add it here:

- [SQL Server Feedback](https://aka.ms/sqlfeedback)

**Comment by silentk62** [comment]
I'm wondering why this was closed because the problem still exists in SSMS 19.0.2.
Can you point me to the fix?
