### ISSUE TITLE
Is the Maximum database size of 524 petabytes correct?

### ISSUE THREAD

**Issue by klzbrt** [MicrosoftDocs/sql-docs#4532]
This page below states that the maximum database size is 524 terabytes.

https://docs.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server?view=sql-server-2016

Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 468d4b7b-8880-a867-de2c-75e6099474f9
* Version Independent ID: e57139bf-0bd8-eb5c-4896-71488873c1f0
* Content: [Editions and supported features - SQL Server 2016](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2016?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-2016.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@klzbrt -- thank you for your question.  I believe the page referenced in your comment is incorrect and should say "Database size 524,272 gigabytes".  I am looking into this issue.

**Comment by klzbrt** [comment]
@WilliamAntonRohm OK, so the correct max. capacity is 524 terabytes not petabytes?

**Comment by WilliamAntonRohm** [comment]
@klzbrt -- yes, I believe that is the case.

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- please review [private PR 14559](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14559).

**Comment by MashaMSFT** [comment]
Hi @klzbrt, thanks for contacting Microsoft! The correct maximum database size is 524 petabytes, or 524,272 terabytes. 

My apologies, but I am not seeing where in the documentation you see 524 terabytes? 

This is what I see: 
https://docs.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server?view=sql-server-2016 
Database size                     524,272 terabytes        

https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2016?redirectedfrom=MSDN&view=sql-server-ver15#feedback 
Maximum relational database size            524 PB
     
Would you mind providing a screenshot of where you see the incorrect value?

Thanks!
Masha from the SQL Docs team

**Comment by klzbrt** [comment]
@MashaMSFT Wow. Masha. So, first off, I didn't know (or believe) SQL Server had such a large capacity.

And secondly, I must apologize. After revisiting these pages, I can't say where I saw "524 terabytes". My only guess is that one page expresses the size in petabytes while the other expresses it in terabytes.

So after all of this, I guess my only request is that someone change the notation on one page to match that of the other page. Mixing the two is confusing; hence this false doc-bug.

**Comment by MashaMSFT** [comment]
Hi @klzbrt, thanks for this feedback! Let me see what I can do for you :)

**Comment by klzbrt** [comment]
Thank you Masha. Much appreciated.

**Comment by MashaMSFT** [comment]
Hi @anishkunisetty , thanks again for contacting Microsoft and helping improve our documentation! My sincerest apologies for the delay, the last few months have been extra hectic :) I have created an internal work item ([1744245](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1744245)) to track this work and hope to have this fixed for you this month.

I'm going to close out this Git Issue for the time being but please feel free to comment should you need anything further.

Thanks again and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
