### ISSUE TITLE
ODBC Driver support for AG in Windows

### ISSUE THREAD

**Issue by Ashwinkumar-R** [MicrosoftDocs/sql-docs#4536]
From Docs, I see that ODBC 13/17 driver does not support AG in Windows, as per the details mentioned.

https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/always-on-client-connectivity-sql-server?view=sql-server-ver15

On the other side in the release notes for 13.1 it is mentioned as the feature is supported.

https://docs.microsoft.com/en-us/sql/connect/odbc/windows/microsoft-odbc-driver-for-sql-server-on-windows?view=sql-server-ver15

Could you please clarify on this point whether AG will be supported by ODBC 13/17 in Windows.

Also please update this page with drivers supported.
https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/always-on-client-connectivity-sql-server?view=sql-server-ver15

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93dc3f31-08df-0ca2-2793-e8abe4de193a
* Version Independent ID: cebd12d7-aedc-f24f-79d3-c2361aa535ec
* Content: [Driver and client connectivity support for availability groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/always-on-client-connectivity-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/always-on-client-connectivity-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/always-on-client-connectivity-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @Ashwinkumar-R , thanks for bringing this to our attention! Let me check :) 

Thanks!
Masha from the SQL Docs team

**Comment by Ashwinkumar-R** [comment]
@MashaMSFT Can you confirm whether this is a documentation bug and ODBC supports AG ? We have some requirement where we need to point to MS docs as reference.

Thanks,
Ashwin

**Comment by Ash46** [comment]
This page also not mention anything about AG support
https://docs.microsoft.com/en-us/sql/connect/odbc/windows/features-of-the-microsoft-odbc-driver-for-sql-server-on-windows?view=sql-server-ver15

Appreciate if you could provide an update.

Ashwin

**Comment by Ashwinkumar-R** [comment]
This page also not mention anything about AG support
https://docs.microsoft.com/en-us/sql/connect/odbc/windows/features-of-the-microsoft-odbc-driver-for-sql-server-on-windows?view=sql-server-ver15

Appreciate if you could provide an update.

Ashwin

**Comment by kfarlee** [comment]
I'm a bit confused. When I look at the page in your first link: https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/always-on-client-connectivity-sql-server?view=sql-server-ver15

It very clearly indicates that Always On Availability Groups are supported by ODBC drivers versioned 13.1 and above (13.1+ in the table)

The following table summarizes driver support for Always On availability groups:

Driver | Multi-Subnet Failover | Application Intent | Read-Only Routing | Multi-Subnet Failover: Faster Single Subnet Endpoint Failover | Multi-Subnet Failover: Named Instance Resolution For SQL Clustered Instances
-- | -- | -- | -- | -- | --
SQL Native Client 11.0 ODBC | Yes | Yes | Yes | Yes | Yes
SQL Native Client 11.0 OLEDB | No | Yes | Yes | No | No
ADO.NET with .NET Framework 4.0 with connectivity patch* | Yes | Yes | Yes | Yes | Yes
ADO.NET with .NET Framework 3.5 SP1 with connectivity patch** | Yes | Yes | Yes | Yes | Yes
**Microsoft ODBC Driver 13.1+ for SQL Server** | Yes | Yes | Yes | Yes | Yes
Microsoft JDBC Driver 4.0+ for SQL Server | Yes | Yes | Yes | Yes | Yes
Microsoft OLE DB Driver for SQL Server | Yes | Yes | Yes | Yes | Yes

**Comment by MashaMSFT** [comment]
Hi @ashwinkumar-r, thanks again for reaching out! It looks like kfarlee has addressed your question so I'm going to close out this Git Issue, but please feel free to comment should you have any further questions.

I hope that helps and please let us know if you need anything further.

Thanks and hope you have a great rest of your day!
Masha from the SQL Docs team
