### ISSUE TITLE
Use it with SQL 2019

### ISSUE THREAD

**Issue by yang-jiayi** [MicrosoftDocs/sql-docs#4538]
Can use it with SQL Server 2019, so please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dee4c182-7c0a-22e0-b89d-1434dde2c0a2
* Version Independent ID: a2a4d5fa-54a9-8863-add8-db5c6219142c
* Content: [DROP SENSITIVITY CLASSIFICATION (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-sensitivity-classification-transact-sql?view=azuresqldb-current&viewFallbackFrom=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/drop-sensitivity-classification-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/drop-sensitivity-classification-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @giladmit
* Microsoft Alias: **giladm**

**Comment by rothja** [comment]
@yang-jiayi Thank you for the question and apologies for the delayed response. @giladmit Hello. As the article owner, you have been assigned this question on whether SQL Server 2019 is supported. Can you please take a look? Thank you!

**Comment by rothja** [comment]
@VanMSFT Van, can you please help verify whether [Data Discovery & Classification](https://docs.microsoft.com/en-us/azure/azure-sql/database/data-discovery-and-classification-overview) is an Azure SQL only feature, or does it also apply to SQL Server 2019? See the applies-to here:

[ADD SENSITIVITY CLASSIFICATION (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/statements/add-sensitivity-classification-transact-sql?view=sql-server-ver15)
[sys.sensitivity_classifications (Transact-SQL)](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-sensitivity-classifications-transact-sql?view=sql-server-ver15)

where it says applies to "all supported versions" of SQL Server (that's not right, is it? should be 2019 according to intro paragraph), and then this topic:

[DROP SENSITIVITY CLASSIFICATION (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-sensitivity-classification-transact-sql?view=azuresqldb-current)

where it only says it applies to Azure SQL. If it really is a 2019 introduced feature, we should change the articles in sql-docs to have the 2019 & Azure SQL Applies To header. I can ask William to make a PR with this change if you can verify for me. Thanks! #assign:vanmsft #assign:rothja

**Comment by VanMSFT** [comment]
Hey @DavidTrigano - Can you help clarify this GitHub Issue?

**Comment by DavidTrigano** [comment]
@yang-jiayi is right. We can use this T-SQL command with SQL 2019.
@VanMSFT can you please fix this?

**Comment by VanMSFT** [comment]
@DavidTrigano - Thanks David.
@rothja - All supported versions should be correct:

![image](https://user-images.githubusercontent.com/40007119/95249650-db11d080-07cd-11eb-991a-6c56c94ba5b7.png)

**Comment by VanMSFT** [comment]
Thanks for the help, @yang-jiayi! I've fixed the doc.

**Comment by rothja** [comment]
@VanMSFT Van, thank you for making the change. When you get a chance, can you update the applies-to on these articles as well:

[ADD SENSITIVITY CLASSIFICATION (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/statements/add-sensitivity-classification-transact-sql?view=sql-server-ver15)
[sys.sensitivity_classifications (Transact-SQL)](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-sensitivity-classifications-transact-sql?view=sql-server-ver15)

**Comment by rothja** [comment]
#assign:DavidTrigano David, assigning you for tracking the collaboration on the git issue. No action required as it is closed now. Thank you!

**Comment by VanMSFT** [comment]
Hey @DavidTrigano - Can you verify this statement?

![image](https://user-images.githubusercontent.com/40007119/95260366-6f376400-07dd-11eb-9a96-35963ca64b8b.png)

Hey @rothja - Can you clarify what needs to be changed? The applies-to should indicate that it is supported with all supported versions of SQL Server, which it already has. Maybe I'm missing something.

**Comment by DavidTrigano** [comment]
@VanMSFT Data Discovery & Classification is supported for SQL Server 2012 and later. The statement should be:

For SQL Server, this was introduced in SQL Server 2012

**Comment by VanMSFT** [comment]
Thanks, @DavidTrigano!
