### ISSUE TITLE
Semicolon or no semicolon?

### ISSUE THREAD

**Issue by jake-reece** [MicrosoftDocs/sql-docs#4539]
The SYNTAX section shows no semicolon after END, but the EXAMPLES section does show a semicolon used after END. Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e71367c7-99bd-7d1a-a162-a6a447b0cd63
* Version Independent ID: 000247d6-3e0a-7aa8-4c65-b1960f5fca3c
* Content: [BEGIN...END (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/begin-end-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/language-elements/begin-end-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/begin-end-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@jake-reece Thank you for the feedback.

The documentation has been updated and is pending review.
