### ISSUE TITLE
Images in the docs don't work in dark mode

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#4542]
@SetTrend commented on [Sun Apr 12 2020](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/120)

Many pictures in the SQL Server docs have been created with a transparent background.

Due to the transparent background, black letters in the image render illegible in dark mode:

![Screenshot](https://user-images.githubusercontent.com/9283914/79081357-f4edc180-7d1c-11ea-9cf0-969a8a11df34.png)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9a878f81-f084-d4a2-8098-2b63558b7369
* Version Independent ID: 9e64bd2c-670e-284b-f34e-a409650cec88
* Content: [Handbuch zur Architektur und Verwaltung von Transaktionsprotokollen - SQL Server](https://docs.microsoft.com/de-de/sql/relational-databases/sql-server-transaction-log-architecture-and-management-guide?view=sql-server-ver15#physical_arch)
* Content Source: [docs/relational-databases/sql-server-transaction-log-architecture-and-management-guide.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/relational-databases/sql-server-transaction-log-architecture-and-management-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

---

@srvbpigh commented on [Sun Apr 12 2020](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/120#issuecomment-612686746)

Hello, @SetTrend
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by rothja** [comment]
@CeciAc we are aware of this problem but have not found a way to systematically fix them all. We've been fixing the ones that people report. I'll look at this one. Thanks!

**Comment by rothja** [comment]
I'm fixing the screenshots in this article today to make them have a permanent white background. Thanks!
