### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by tjcheah** [MicrosoftDocs/sql-docs#4545]
I'm using SQL Express 2019 and SSMS 18.4 and trying to delete sql express instances but find that when following this, there is no installation pop up for me to carry out. Instead it unintalls straight leaving the sql instances behind

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5559d56d-e787-2c02-970d-a2825911d81e
* Version Independent ID: 99f7b922-9fca-dc06-f934-d4a87c098764
* Content: [Uninstall existing instance - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/uninstall-an-existing-instance-of-sql-server-setup?view=sql-server-ver15&tabs=Windows10#feedback)
* Content Source: [docs/sql-server/install/uninstall-an-existing-instance-of-sql-server-setup.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/uninstall-an-existing-instance-of-sql-server-setup.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @tjcheah , thanks for contacting Microsoft! Unfortunately, it sounds like you're running into a support issue, and this forum is intended for issues with the documentation. 

Although in this case I can offer some preliminary assistance, you may still need to reach out to the community for assistance, or possibly open a support ticket with Microsoft.

Would you mind taking a screenshot of your Programs and Features, and highlighting which program you're choosing to uninstall when attempting to uninstall SQL Server Express?

Thanks!
Masha from the SQL Docs team

**Comment by tjcheah** [comment]
Hi,

thanks for coming back to me. I have attached the screenshot with all of my
SQL programs and features listed. The highlighted line was what i was
uninstalling as per the instructions found on the forum. However when I did
it, the uninstall pop up never came up so hence I could not choose parts to
uninstall and was only given the option to uninstall everything.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
16/04/20,
09:13:42

**Comment by MashaMSFT** [comment]
Hi @tjcheah , you'll need to paste the pictures into the comment on GitHub :( pictures don't come through over email.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @tjcheah , I tested it out, and I was able to uninstall SQL Server 2019 Express from the **Add or remove programs** settings page. When I chose to uninstall **Microsoft SQL Server 2019 (64-bit)**, my installation window came up, and I was able to select the features that I wanted to remove. 

![image](https://user-images.githubusercontent.com/32783170/79489142-b7648f00-7fcf-11ea-8b16-81d9d1e90525.png)

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @tjcheah, it's been some time since we we've heard from you, so we're going to assume that your issue is resolved and close out this Git Issue.

However, please feel free to comment should you need anything further!

Thanks again for contacting Microsoft and I hope you have a great rest of your day!
Masha from the SQL Docs team
