### ISSUE TITLE
Need examples of how to do equality joins to a deterministic encrypted column

### ISSUE THREAD

**Issue by wsuhoey** [MicrosoftDocs/sql-docs#4550]
There's a gap in documentation about how to properly do an equality join to a deterministic encrypted column. The docs that discuss `Selecting Deterministic or Randomized Encryption` state that equality joins are supported with deterministic columns. Yet all of the examples in the docs I've found only show how to use WHERE clauses, none show how to do JOIN clauses. Please add examples of how to do equality joins to a deterministic encrypted column so that we don't get the common "The data types char and char(10) encrypted with (...) are incompatible in the equal to operator" errors, for example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc2598a6-e400-784c-450e-c47f22bd7e9b
* Version Independent ID: 07422cff-f8b1-8a0f-b011-36e8f4629080
* Content: [Query columns using Always Encrypted with SQL Server Management Studio - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-query-columns-ssms?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/always-encrypted-query-columns-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/always-encrypted-query-columns-ssms.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@wsuhoey -- John, thank you for your feedback.

@jaszymas -- please look into this issue.

**Comment by wsuhoey** [comment]
@jaszymas 

Based on the question I posted on [DBA Stack Exchange](https://dba.stackexchange.com/questions/264926/always-encrypted-how-do-i-do-an-equality-join-with-a-non-encrypted-column-to-a) and the answer and comments discussed, it seems some of the confusion could be avoided if the docs explicitly stated that it is not possible to join a non-encrypted column to a deterministic encrypted column. The docs' description of:

> Using deterministic encryption allows point lookups, equality joins, grouping and indexing on encrypted columns.

I interpreted (as well as many other people have) to mean that I could use a non-encrypted column on one side of the JOIN clause and a deterministic encrypted column on the other side of a JOIN clause, but it seems that's not the case. If it is indeed not the case, please update the docs stating that. Otherwise, if it is in fact possible, that's the example syntax that would be needed which caused me to create this feedback initially.

**Comment by sql-deadwood** [comment]
I was also tripped up by the exact line of documentation that wsuhoey is referencing:

> Using deterministic encryption allows point lookups, equality joins, grouping and indexing on encrypted columns.

**Comment by VanMSFT** [comment]
Hey @jaszymas - This is an old one. When you get a chance, can you please take a look? Thanks!

**Comment by jaszymas** [comment]
Hi Van,

That's been on my todo list. It requires some fairly heavy refactoring to the docs, but I plan to get to it in the next few weeks.

Thanks,

Jakub

**Comment by MikeRayMSFT** [comment]
The specific issue listed in https://github.com/MicrosoftDocs/sql-docs/issues/4550#issuecomment-614267630 is resolved.

Additional reviews and updates are in flight. 

Propose close.

**Comment by VanMSFT** [comment]
Closing this. We'll take adding more examples into considerations when we update the doc.
