### ISSUE TITLE
json path for cu4 (and cu3) should be $.security.activeDirectory 

### ISSUE THREAD

**Issue by chrisadkin** [MicrosoftDocs/sql-docs#4551]
Can you please add a section to the documentation for configuring the active directory config for CU4 (and I'm guessing CU3 is also affected), for example with CU4, instead of:

azdata bdc config replace -c custom-prod-kubeadm/control.json -j "$.security.ouDistinguishedName=OU\=bdc\,DC\=contoso\,DC\=local"

you should have:

azdata bdc config replace -c custom-prod-kubeadm/control.json -j "$.security.activeDirectory.ouDistinguishedName=OU\=bdc\,DC\=contoso\,DC\=local"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6733c468-62a5-41d9-2c5a-5ca57ee5fdf3
* Version Independent ID: dd529f6a-f02d-0dc4-dd4f-52321e90bed0
* Content: [Deploy in Active Directory mode - SQL Server Big Data Cluster](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-active-directory?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/deploy-active-directory.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-active-directory.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @mihaelablendea
* Microsoft Alias: **mihaelab**

**Comment by WilliamAntonRohm** [comment]
@chrisadkin -- Chris, thank you for your feedback and research.

@mihaelablendea -- Mihaela, please look into this issue.

**Comment by mihaelablendea** [comment]
Documentation includes samples for both CU2 (and up) and pre-CU2 releases. Please re-open if you still see any issue

**Comment by mihaelablendea** [comment]
#please-close
