### ISSUE TITLE
Severity level

### ISSUE THREAD

**Issue by KevinPence** [MicrosoftDocs/sql-docs#4557]
I was slightly confused by the phrasing "The exception severity is always set to 16" in the Differences Between... section.  The CATCH block example provided in the article contradicts that statement, as did my own tests.

I think it should be clarified that when THROW is used to initiate the exception, the severity is always 16, but when it is used to re-throw an existing exception it passes along the severity level it caught.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525698d4-0465-5fe0-f09d-dfad8b8413e6
* Version Independent ID: 2ece841a-2d51-542e-6c2b-9d36ffe54202
* Content: [THROW (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/throw-transact-sql?view=sql-server-2016)
* Content Source: [docs/t-sql/language-elements/throw-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/throw-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@KevinPence -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@rothja -- Jason, please review [private PR 14560](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14560).

**Comment by rothja** [comment]
@KevinPence  Thanks for the feedback, and thank you, @WilliamAntonRohm , for the change to the article. I also tested and verified the described behavior.
