### ISSUE TITLE
Please clarify THROW recommendation

### ISSUE THREAD

**Issue by KevinPence** [MicrosoftDocs/sql-docs#4558]
"New applications should use THROW instead."

To me, this phrasing doesn't exactly mean that RAISERROR is deprecated.  Is it actually deprecated?  If not, I can guess why THROW is recommended- because RAISERROR is less tidy and consistent- but I'd appreciate a more concrete explanation.

I am familiar with and like some of the subtleties of RAISERROR, like being able to set the severity level to alter its behavior.  As such, I will probably not transition to THROW and relearn new subtleties unless there is a clear reason.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472beb1c-1682-d2db-c2b1-3083c174b0cc
* Version Independent ID: 099a81a1-42cb-bd91-9147-bc761d4be177
* Content: [RAISERROR (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/raiserror-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/language-elements/raiserror-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/raiserror-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@KevinPence -- thank you for your feedback.  You may find additional information here:
- https://social.msdn.microsoft.com/Forums/sqlserver/en-US/81ef8f38-7ddc-486b-983c-18dbf7be412d/please-clarify-which-raiserror-variation-is-on-the-deprecation-list?forum=transactsql
- https://dba.stackexchange.com/questions/229579/deprecated-raiserror-detection

cc @rothja for awareness

**Comment by KevinPence** [comment]
Thanks for the quick reply.  The links appear to address one specific RAISERROR syntax that was deprecated long before my time.  My codebase does not include any of the old syntax.

My question is, for the currently supported and documented RAISERROR syntax*, what is the meaning of the advice, "New applications should use THROW instead"?

*for example,
> RAISERROR(@ErrorMsg,@Severity,@State,@Params);
