### ISSUE TITLE
Please clarify transfer of control

### ISSUE THREAD

**Issue by KevinPence** [MicrosoftDocs/sql-docs#4559]
"When RAISERROR is run with a severity of 11 or higher in a TRY block, it transfers control to the associated CATCH block. The error is returned to the caller if..."

This seems misleading to me.  One might conclude that when the conditions are met to return the error to the caller, control is also transferred to the caller automatically.  This is not the case- a RETURN statement is required following the RAISERROR to immediately cease execution and transfer control to the caller.

I think that this behavioral difference may not be obvious to newer devs tinkering with it, and that it's a critical enough behavioral difference that it should be stated explicitly.

Thanks for considering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472beb1c-1682-d2db-c2b1-3083c174b0cc
* Version Independent ID: 099a81a1-42cb-bd91-9147-bc761d4be177
* Content: [RAISERROR (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/raiserror-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/language-elements/raiserror-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/raiserror-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@KevinPence -- thank you for clarifying this issue.  I am looking into this article as well.

**Comment by WilliamAntonRohm** [comment]
@rothja -- please review [private PR 14606](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14606) which will close this issue.

**Comment by rothja** [comment]
@WilliamAntonRohm Thanks for submitting a fix. I have an alternate suggestion that involves two changes:

I think in the sentence above, it should say, `The error message is returned to the caller if` (I added "message") because this is accurate whether control is passed back to the caller or not. Then I think we need a sentence added to this paragraph:

```
RAISERROR can be used as an alternative to PRINT to return messages to calling applications. RAISERROR supports character substitution similar to the functionality of the printf function in the C standard library, while the Transact-SQL PRINT statement does not. The PRINT statement is not affected by TRY blocks, while a RAISERROR run with a severity of 11 to 19 in a TRY block transfers control to the associated CATCH block. Specify a severity of 10 or lower to use RAISERROR to return a message from a TRY block without invoking the CATCH block.
```

I would add this sentence to the end of the previous paragraph:

```
Errors that are severity 10 or lower do not immediately pass control back to the caller unless you use an explicit RETURN statement following RAISERROR.
```

@KevinPence I would welcome a review of this change to make sure that this is the problem you were raising. Thanks!

**Comment by KevinPence** [comment]
Hi Rothja,
Thanks for requesting my input!  I'll take you up on your invitation.

**Suggestion 1**
I recall puzzling over the phrase "the error is returned."  I concluded that in this context 'error' means the set of properties that comprise an _error thing_ (message, number, severity, state, line, and proc).*  Could the word "message" imply that only the error_message() property is returned?  To me, "error" was dense, but "error message" is potentially misleading.

*I'm unsure of what kind of thing 'error' actually is- is it an object, result set, or concatenated string?

**Suggestion 2**
The addition is accurate for RAISERROR with severity <11 inside a TRY.  However, RAISERROR 11-19 (and 20+?) outside a TRY will not immediately pass control back to the caller either.  Non-TRY RAISERROR is what I primarily want to see clarified.

I think it might be simpler to describe the default behavior for RAISERROR first, then introduce the way TRY...CATCH handles errors created by RAISERROR.  In my mind, RAISERROR does not do extra stuff, TRY does.

Here's a rough idea of what I have in mind:
> RAISERROR creates an _error thing_ to be returned to the caller.  It does not end execution or pass control.  You must explicitly state RETURN following RAISERROR to immediately pass control back to the caller. 
then later,
> TRY ignores RAISERROR <11, allowing the _error thing_ to be passed back to the caller.  TRY immediately passes control to CATCH for RAISERROR 11-19.

**New Questions on RAISERROR 20+**
In TRY
Given that "the error is returned to the caller if RAISERROR is run...with a severity of 20 or higher", does TRY
- ignore 20+ (exactly as with <11)? or
- immediately pass execution to the caller (bypassing CATCH)? or
- do some other thing that 20+ wouldn't do outside of TRY...CATCH?

Outside TRY
The Caution in the article's Severity Argument states that 20+ terminates the client connection "after receiving the message."  If that means after _the client_ receives the message, can execution continue indefinitely until then?  And is the client responsible for terminating the connection?  That meaning seems unlikely to me, but the passive voice makes it unclear.

Thanks for considering.

**Comment by WilliamAntonRohm** [comment]
@KevinPence -- thank you for your further clarifications and questions.

I understand what you are each saying, but I don't have the depth of knowledge necessary to contribute to the technical side of this discussion.  

@rothja -- please review Kevin's comment & I will update the doc accordingly.

**Comment by rothja** [comment]
@KevinPence Thanks for the detailed thoughts here! All of these questions are good ones, but in the near future, I won't have the time to fully investigate/test the behavior in each case to make substantial changes to the article and how it talks about the error-raising process. I am sorry that it is confusing or misleading as-is, though. Let me look think through your comments and see if I can make my suggestions more clear. @WilliamAntonRohm I can take ownership of this. I think it would be easier if you closed your open PR and I'll make the final changes. Thank you! #reassign: rothja

**Comment by KevinPence** [comment]
Thanks @rothja and @WilliamAntonRohm for the feedback.  After I posted yesterday I realized the connection between my concerns discussed here and my other question about this article.

My other question was why THROW is recommended over RAISERROR.  The answer is because RAISERROR does not honor XACT_ABORT ON.  This information was a breakthrough for me.

We've been aware of this behavior in my shop, and the policy has been to always SET XACT_ABORT OFF and manually handle RETURNs as needed.  In recent years, we developed a DAC framework that encapsulates pretty much our entire application in a TRY...CATCH, in what we call "MasterProc."  I've been focused on RAISERROR behavior recently because of an old project I've been working on.

So my need for finer nuance is partly of our own making, and I agree with you that this is not high priority info for most devs or dbas.  I really do appreciate your help and patience in discussing my questions and suggestions!

**Comment by rothja** [comment]
@KevinPence Thank you for the additional info! I'm glad you found the key to understanding the space better. Likely, we could do some additional work to make this more clear, but for now, if you feel you have the answers you need, I will close this issue and consider this (and other) feedback we might get for future changes. Let me know if you have any other questions or concerns on this issue. Thank you!
