### ISSUE TITLE
Incorrect documentation on truncating values to datetime

### ISSUE THREAD

**Issue by siufay325** [MicrosoftDocs/sql-docs#4560]
The document mentioned that "When the fractional precision of the datetime2(n) value is greater than three digits, the value will be truncated.". This is not correct:

DECLARE @datetime2 datetime2(4) = '1968-10-23 12:45:37.9989';  
DECLARE @datetime datetime = @datetime2;  
  
SELECT @datetime AS '@datetime', @datetime2 AS '@datetime2'; 

--Result  
--@datetime               @datetime2  
------------------------- ------------------------  
--1968-10-23 12:45:38.000 1968-10-23 12:45:37.9989  

It seems like the values are first rounded to .999 (instead of truncate), then converted to datetime to become .000.
If the value is truncated as mentioned in the documentation, it should become .997 instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1774f2f4-950d-03af-fc87-f75099f31835
* Version Independent ID: 76893d14-e1ed-0d4a-6092-15d25628ce14
* Content: [datetime (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/data-types/datetime-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/datetime-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@siufay325 -- SiuFay, thank you for your feedback.  Please add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
