### ISSUE TITLE
Missing @RowCount

### ISSUE THREAD

**Issue by shnja** [MicrosoftDocs/sql-docs#4563]
I. Using UPDATE in a stored procedure - mentions `@RowCount` output parameter, but it is not included in the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e804135e-b9e9-3d0c-4bc8-9f522a6d8178
* Version Independent ID: 117bdc3d-c3d0-4363-e625-a41ef559d488
* Content: [CREATE PROCEDURE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-procedure-transact-sql?view=sql-server-ver15#i-using-update-in-a-stored-procedure)
* Content Source: [docs/t-sql/statements/create-procedure-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-procedure-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@shnja please feel free to submit an edit for this. If not, I will get to this at some point in the reasonable future.
Thanks, Carl

**Comment by CarlRabeler** [comment]
@shnja fixed. PR just merged. Will be live on the public site in a few hours.
