### ISSUE TITLE
Provides a link to the 2019 edition which then brings you back here!!

### ISSUE THREAD

**Issue by sureseam** [MicrosoftDocs/sql-docs#4566]
In the segment "Pull and Run Container Image" there is a link for the 2019 edition which brings the browser back to this self same page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash#feedback)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by sureseam** [comment]
Workaround: setting the edition at the top of the left hand frame gets the browser to the 2019 edition.

**Comment by WilliamAntonRohm** [comment]
@sureseam -- Alastair, thank you for your feedback and workaround. I will pass it on.
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
