### ISSUE TITLE
sys.dm_resource_governor_workload_groups - Missing column in docs

### ISSUE THREAD

**Issue by Trovalo** [MicrosoftDocs/sql-docs#4568]
[Enter feedback here]

The column [total_cpu_usage_preemptive_ms] is not present in the documentation.
For what I've seen so far it has been introduced in SQL Server 2016.
[Here ](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-resource-governor-workload-groups-transact-sql?view=sql-server-ver15)is the link to the page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc78ee79-8b2d-f734-3d6c-bf429fdbe78e
* Version Independent ID: 583be827-6175-06d7-fb58-d452fc2c9ada
* Content: [sys.dm_resource_governor_workload_groups (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-resource-governor-workload-groups-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-resource-governor-workload-groups-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-resource-governor-workload-groups-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@Trovalo -- Giovanni, thank you for your feedback.

@stevestein -- Steve, please look into this issue.

**Comment by rothja** [comment]
Apologies for the delayed response. @CarlRabeler Could you please look into this issue? Thank you! #reassign:CarlRabeler

**Comment by CarlRabeler** [comment]
@pmasl Pedro, can you please review this issue? Thanks, Carl

**Comment by CarlRabeler** [comment]
@pmasl Pedro, can you please review this issue? Thanks, Carl

**Comment by CarlRabeler** [comment]
#reassign: @pmasl 
Pedro - could you please look at this. If this is not in your area, please either reassign back to me and reassign to the appropriate individual

**Comment by rothja** [comment]
@Trovalo Apologies for the extremely long delay in responding, but it looks like that field is in the documentation now. Let me know if you do not see it on the page you referenced. Thank you!

**Comment by rothja** [comment]
#reassign:rothja

**Comment by Trovalo** [comment]
Can confirm that now it's there, thanks
