### ISSUE TITLE
Example has wrong paramaters

### ISSUE THREAD

**Issue by tiagobalabuch** [MicrosoftDocs/sql-docs#4569]
"azdata bdc spark batch create" section has a wrong parameter/example --code. 
It should be --file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6600107a-20b8-6ee3-1616-4c6ca1c06159
* Version Independent ID: 46981b99-72b9-16d4-bfe3-cc383708f26d
* Content: [azdata bdc spark batch reference - SQL Server](https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata-bdc-spark-batch?view=sql-server-ver15#azdata-bdc-spark-batch-create)
* Content Source: [docs/big-data-cluster/reference-azdata-bdc-spark-batch.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/reference-azdata-bdc-spark-batch.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@tiagobalabuch -- Tiago, thank you for catching that.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review [private PR 14609](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14609).
