### ISSUE TITLE
storage protocol support for underlying platform

### ISSUE THREAD

**Issue by chrisadkin** [MicrosoftDocs/sql-docs#4572]
Can you please explicitly confirm on this page that this is NFS 4.2, SMB 3.0+ and block (iSCSI or FC).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e099502f-f7d3-5368-41fe-6c50d593c8fd
* Version Independent ID: 7f77cae8-15a9-a586-31b2-80d985ca019a
* Content: [Data persistence on Kubernetes - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/concept-data-persistence?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/concept-data-persistence.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/concept-data-persistence.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @mihaelablendea
* Microsoft Alias: **mihaelab**

**Comment by WilliamAntonRohm** [comment]
@chrisadkin -- Chris, all I can offer you is those info links.  This repo is solely for documentation issues, not product questions.  I do see your point and will cc the author.  Please leave further feedback here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @mihaelablendea for awareness
