### ISSUE TITLE
HDFS replication factor

### ISSUE THREAD

**Issue by chrisadkin** [MicrosoftDocs/sql-docs#4573]
Would it be possible to state that for storage platforms with in-built data resiliency (RAID and / or erasure coding) that this can be set to 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e099502f-f7d3-5368-41fe-6c50d593c8fd
* Version Independent ID: 7f77cae8-15a9-a586-31b2-80d985ca019a
* Content: [Data persistence on Kubernetes - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/concept-data-persistence?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/concept-data-persistence.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/concept-data-persistence.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @mihaelablendea
* Microsoft Alias: **mihaelab**

**Comment by WilliamAntonRohm** [comment]
@chrisadkin -- Chris, thank you for your question.

@mihaelablendea --Mihaela, please look into this issue.

**Comment by MikeRayMSFT** [comment]
Thanks @mihaelablendea for discussing with the submitter.
