### ISSUE TITLE
please provide direct download links

### ISSUE THREAD

**Issue by trondhindenes** [MicrosoftDocs/sql-docs#4576]
a link named ".deb" should link to an actual deb file so that I can wget that link directly. Microsoft makes it unnecessarily difficult to download software by always linking to "intermediate" urls. Now I have to start the download on my workstation to get the actual url, which I will then copy from Chrome's download window and then paste it into the terminal where I wish to download the package. I don't understand why you make it so difficult.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15#feedback)
* Content Source: [docs/azure-data-studio/download-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download-azure-data-studio.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
@trondhindenes -- Trond, thank you for your feedback.  Please add your issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
