### ISSUE TITLE
Need to also start the cluster group after changing RegisterAllProvidersIP and HostRecordTTL

### ISSUE THREAD

**Issue by snolan-uturn** [MicrosoftDocs/sql-docs#4577]
The script for updating  needs to also include a Start-ClusterGroup command because the cluster group (the listener role) is stopped when you stop the cluster resource and it does not start again when you start the cluster resource. So the script should be:
```
Import-Module FailoverClusters  
Get-ClusterResource yourListenerName | Set-ClusterParameter RegisterAllProvidersIP 0   
Get-ClusterResource yourListenerName | Set-ClusterParameter HostRecordTTL 300  
Stop-ClusterResource yourListenerName  
Start-ClusterResource yourListenerName
Start-Clustergroup yourListenerGroupName
```

If the cluster group is offline the state of the availability group listener in SQL Server will be "Resolving".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b679be86-06b0-b425-cd4f-d7b3ea104693
* Version Independent ID: aec2cf5b-5bf9-647e-6b0f-9fab6fca3a79
* Content: [Configure availability group listener - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@snolan-uturn -- thank you for your suggestion.  I have updated the article.

@MashaMSFT -- please review [private PR 14610](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14610).
