### ISSUE TITLE
LAST_VALUE was available in versions prior to 2019

### ISSUE THREAD

**Issue by LarnuUK** [MicrosoftDocs/sql-docs#4581]
The opening line in this document below:
&gt; Returns the last value in an ordered set of values in SQL Server 2019 (15.x).

This *implies* that it's only available in SQL Server 2019, however, it was first available in 2012. There are no documentation pages for 2017-, so this line is very misleading, and could make those useing 2017- think they do not have access to `LAST_VALUE`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ffda42-ab8a-74df-0b14-92cc12cf39df
* Version Independent ID: 1fd3836e-52fa-014c-67de-b73e0fd810ed
* Content: [LAST_VALUE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/last-value-transact-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-2014#feedback)
* Content Source: [docs/t-sql/functions/last-value-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/last-value-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@LarnuUK -- Thom, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review [private PR 14611](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14611).
