### ISSUE TITLE
Easier way

### ISSUE THREAD

**Issue by SimpleSamples** [MicrosoftDocs/sql-docs#4583]
There is an easier way. Just change the extension to zip. Or copy the file and give that file the zip extension. That is easier and cleaner than unpacking all files. For me when I open a file in the zip file from the Files Explorer (Windows Explorer) the files are (put in a temporary file) then opened by VS Code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5562c8a2-12fb-50e2-b69d-2d4d3d5c272d
* Version Independent ID: f6e38e92-bb69-496d-c44a-8b6f07f10a1f
* Content: [Validate a DAC Package - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/validate-a-dac-package?view=sql-server-ver15)
* Content Source: [docs/relational-databases/data-tier-applications/validate-a-dac-package.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/validate-a-dac-package.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@SimpleSamples -- Sam, thank you for your feedback and suggested solution. Please add your information here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
