### ISSUE TITLE
format 'dpkg-reconfigure ca-certificates'

### ISSUE THREAD

**Issue by apgrc** [MicrosoftDocs/sql-docs#4584]
The Ubuntu command to install certificate is not highlighted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8029b968-0ef5-a3a0-050f-a0b0189e5984
* Version Independent ID: 2ffb6a1e-5672-7742-d685-1d418c24f29c
* Content: [Encrypting Connections to SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-encrypted-connections?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-encrypted-connections.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-encrypted-connections.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by WilliamAntonRohm** [comment]
@vin-yu -- Vin, please review [private PR 14733](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14733).
