### ISSUE TITLE
SS 2019? 

### ISSUE THREAD

**Issue by TiaTheTechWriter** [MicrosoftDocs/sql-docs#4586]
The contents of the topic, especially the first table with the 0,1 values, seem to leave the status of enabled strict security by default in 2019 unclear. Please update the topic to indicate the default status in SQL Server 2019. Is enabled the default status for 2017 and newer? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96693d4a-9460-9e08-8f14-836b6257e449
* Version Independent ID: 47f19aec-1f62-97c4-fca4-609496fc2139
* Content: [CLR strict security - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/clr-strict-security?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/clr-strict-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/clr-strict-security.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@TiaTheTechWriter -- thank you for your question.  I am looking into this article.

**Comment by pmasl** [comment]
@TiaTheTechWriter it is enabled starting with SQL 2017.

**Comment by pmasl** [comment]
@TiaTheTechWriter it is enabled starting with SQL 2017.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review [private PR 14658](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14658).
