### ISSUE TITLE
Queries that recently regressed in performance (comparing recent vs. history execution)

### ISSUE THREAD

**Issue by TorstenStrauss** [MicrosoftDocs/sql-docs#4588]
Hi Microsoft Team,
I think the duration in ms should be calculated as in the code below.
Also the last duration in the regressed query report in Query Store is wrong.

--- "Recent" workload - last 1 hour
DECLARE @recent_start_time datetimeoffset;
DECLARE @recent_end_time datetimeoffset;
SET @recent_start_time = DATEADD(hour, -1, SYSUTCDATETIME());
SET @recent_end_time = SYSUTCDATETIME();

--- "History" workload
DECLARE @history_start_time datetimeoffset;
DECLARE @history_end_time datetimeoffset;
SET @history_start_time = DATEADD(hour, -24, SYSUTCDATETIME());
SET @history_end_time = SYSUTCDATETIME();

WITH
	hist AS
	(
		SELECT
			p.query_id query_id
		  , ROUND(
					 ROUND(
							  CONVERT(
										 float
									   , SUM(rs.avg_duration
											 * rs.count_executions
											)
									 ) * 0.001, 2
						  ), 2
				 ) AS total_duration
		  , SUM(rs.count_executions) count_executions
		  , COUNT(DISTINCT p.plan_id) num_plans
		FROM
			sys.query_store_runtime_stats AS rs
		JOIN
			sys.query_store_plan AS p
		ON
			p.plan_id = rs.plan_id
		WHERE
			(
				rs.first_execution_time &gt;= @history_start_time
				AND rs.last_execution_time &lt; @history_end_time
			)
			OR
				(
					rs.first_execution_time &lt;= @history_start_time
					AND rs.last_execution_time &gt; @history_start_time
				)
			OR
				(
					rs.first_execution_time &lt;= @history_end_time
					AND rs.last_execution_time &gt; @history_end_time
				)
		GROUP BY
			p.query_id
	)
,
	recent AS
	(
		SELECT
			p.query_id query_id
		  , ROUND(
					 ROUND(
							  CONVERT(
										 float
									   , SUM(rs.avg_duration
											 * rs.count_executions
											)
									 ) * 0.001, 2
						  ), 2
				 ) AS total_duration
		  , SUM(rs.count_executions) count_executions
		  , COUNT(DISTINCT p.plan_id) num_plans
		FROM
			sys.query_store_runtime_stats AS rs
		JOIN
			sys.query_store_plan AS p
		ON
			p.plan_id = rs.plan_id
		WHERE
			(
				rs.first_execution_time &gt;= @recent_start_time
				AND rs.last_execution_time &lt; @recent_end_time
			)
			OR
				(
					rs.first_execution_time &lt;= @recent_start_time
					AND rs.last_execution_time &gt; @recent_start_time
				)
			OR
				(
					rs.first_execution_time &lt;= @recent_end_time
					AND rs.last_execution_time &gt; @recent_end_time
				)
		GROUP BY
			p.query_id
	)
SELECT
	results.query_id query_id
  , results.query_text query_text
  , results.additional_duration_workload additional_duration_workload
  , results.total_duration_recent total_duration_recent
  , results.total_duration_hist total_duration_hist
  , ISNULL(results.count_executions_recent, 0) count_executions_recent
  , ISNULL(results.count_executions_hist, 0) count_executions_hist
FROM
	(
		SELECT
			hist.query_id query_id
		  , qt.query_sql_text query_text
		  , ROUND(
					 CONVERT(
								float
							  , recent.total_duration / recent.count_executions
								- hist.total_duration / hist.count_executions
							) * (recent.count_executions), 2
				 ) AS additional_duration_workload
		  , ROUND(recent.total_duration, 2) total_duration_recent
		  , ROUND(hist.total_duration, 2) total_duration_hist
		  , recent.count_executions count_executions_recent
		  , hist.count_executions count_executions_hist
		FROM
			hist
		JOIN
			recent
		ON
			hist.query_id = recent.query_id
		JOIN
			sys.query_store_query AS q
		ON
			q.query_id = hist.query_id
		JOIN
			sys.query_store_query_text AS qt
		ON
			q.query_text_id = qt.query_text_id
	) AS results
WHERE
	additional_duration_workload &gt; 0
ORDER BY
	additional_duration_workload DESC
OPTION (MERGE JOIN);
GO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b587ab-50b8-eada-aa86-ba0c838c57ee
* Version Independent ID: f1fd2d52-b66f-4fbc-c54a-c688c4fd0f21
* Content: [Monitoring Performance By Using the Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@TorstenStrauss -- thank you for your detailed feedback.  Please clarify "the last duration in the regressed query report in Query Store is wrong".

@julieMSFT -- please look into this issue.

**Comment by julieMSFT** [comment]
@TorstenStrauss I am looking into this. Can you please clarify "the last duration in the regressed query report in Query Store is wrong".

**Comment by TorstenStrauss** [comment]
Hi Julie,

 

Thanks for looking into this!

 

I guess you need to divide the time by 1000.

If the execution_count is one and the total_duration is 59,31, the last_duration mst be 59,31 and 59310

 



 

Same for the CPU

 



 

It seems that there is a general issue with the last_xyz measure. I did not checked for logical reads, writs, CLR etc but maybe worth to do.

This issue seems to be even the same for all Query Store results not only in regression but in top 25 resource concumers, etc



 

Viele Grüße

Torsten Strauß
Senior Microsoft SQL Server Database Engineer
MVP | MCSE | MCT



Schadowstr. 50
44799 Bochum, Germany

VAT: DE305929870
Tel.: +49.179.451.25.03
 <https://inside-sqlserver.com/> https://inside-sqlserver.com

**Comment by TorstenStrauss** [comment]
Hi Julie,

do you need additional information?

Mit freundlichen Grüßen

Torsten Strauß

**Comment by julieMSFT** [comment]
@TorstenStrauss Thank you again for bringing this to our attention. You were correct and should see the update you suggested in the article today. A bug has also been filed to update the report. I will go ahead an close this issue now. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#https://github.com/MicrosoftDocs/sql-docs-pr/pull/14831

**Comment by julieMSFT** [comment]
#please-close
