### ISSUE TITLE
bcp version less than 15 after update

### ISSUE THREAD

**Issue by rjrjack** [MicrosoftDocs/sql-docs#4589]
on Win10 machine I used the page link to 'download Download Microsoft Command Line Utilities 15 for SQL Server (x64)'
Ran the .msi file
From the page: To check the BCP version execute bcp /v command and confirm that 15.0.1300.359 or higher is in use.
cmd line 'bcp /v' shows Version: 14.0.2027.2   ???
BCP does work...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86bd520a-7468-fd55-c357-b0f645a917ef
* Version Independent ID: 3dc9dee5-afcb-8287-4441-e84ff717186a
* Content: [bcp Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/bcp-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/bcp-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@rjrjack -- thank you for your feedback.  I will pass it along!
