### ISSUE TITLE
Explore cmdlets in SqlServer module

### ISSUE THREAD

**Issue by homebrew9** [MicrosoftDocs/sql-docs#4590]
I receive an error message when I use this command pipeline in pwsh on Debian 10 (Buster):
"Get-Command -Module SqlServer -CommandType Cmdlet | SORT -Property Noun | SELECT Name"
/usr/bin/sort: invalid option -- 'p'
Try '/usr/bin/sort --help' for more information.

Looks like somehow it's trying to use the sort command of the Bash shell.
Shouldn't the cmdlet be "Sort-Object" instead of "SORT".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3d99108-bc02-97aa-bfa3-434f36d5ef6d
* Version Independent ID: ea0eda7e-0593-be02-130a-3c81dae1a5be
* Content: [Manage SQL Server on Linux with PowerShell Core - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-manage-powershell-core?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-manage-powershell-core.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-manage-powershell-core.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @SQLvariant
* Microsoft Alias: **aanelson**

**Comment by homebrew9** [comment]
Actually, the error message pasted above was for this command:
"get-command -Module SqlServer -CommandType Cmdlet | sort -property name | select name"

If I retain the case then I see a different error:
PS> Get-Command -Module SqlServer -CommandType Cmdlet | SORT -Property Noun | SELECT Name
SORT: The term 'SORT' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS>

**Comment by WilliamAntonRohm** [comment]
@homebrew9 -- thank you for your feedback.  I am looking into this article.

**Comment by homebrew9** [comment]
I think I figured out the cause of this issue. Looks like the "sort" alias is missing in Powershell for Linux. The command "Get-Alias sort" on Windows Powershell says that "sort" is an alias for "Sort-Object"; but errors out on Linux. There's some discussion on this topic earlier: https://github.com/PowerShell/PowerShell/issues/827
Once I create an alias: "Set-Alias sort Sort-Object", the last command in this article works fine.

**Comment by WilliamAntonRohm** [comment]
@SQLvariant -- Aaron, please review [private PR 14737](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14737).
