### ISSUE TITLE
sessions actively logging in

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#4591]
It may be worth noting that sessions that have not completed logging in will be shown with a login_time of '1900-01-01'.
If you have a logon trigger that blocks all logons they still briefly appear here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c4e75e-7e4b-3143-8f2f-1d866f309c90
* Version Independent ID: d7b963c0-691a-f4af-35e6-bb84fca98ff2
* Content: [sys.dm_exec_sessions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-sessions-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-exec-sessions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-sessions-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by rothja** [comment]
Apologies for the delayed response. @CarlRabeler Could you please look into this issue? Thank you! #reassign:CarlRabeler

**Comment by CarlRabeler** [comment]
@brettshearer PR pending to address this issue
