### ISSUE TITLE
Links to the different product options all point to the On-Premises version

### ISSUE THREAD

**Issue by cairneym** [MicrosoftDocs/sql-docs#4593]
The links to the product selection at https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-transact-sql?view=sql-server-ver15&source=docs#click-a-product are all directing to the "sql-server-ver15" option.

The difference in syntax for Azure SQL Database / Managed Instance / Synapse / APS are not being shown after clicking on the corresponding links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e8abfde-2523-5c70-bb95-b10101a726ff
* Version Independent ID: 3b8152d2-b49e-df4b-0f05-3ec52aa5bb71
* Content: [CREATE DATABASE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-transact-sql?view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/t-sql/statements/create-database-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-database-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@cairneym -- thank you for your feedback.  Please try this link instead:
- https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-transact-sql?view=sql-server-2017

and let me know if that works for you.

**Comment by CarlRabeler** [comment]
@cairneym Thanks and sorry. This was a regression bug in the docs platform last Monday that was fixed last Tuesday. Please verify on your end that it is now fixed

**Comment by cairneym** [comment]
Thanks Carl – all looks healthy now.

**Comment by CarlRabeler** [comment]
Thanks.
