### ISSUE TITLE
Applicable to SQL DB?

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/sql-docs#4594]
All of the sub-pages for Execution Plans apply to SQL Server and Azure SQL DB. Shouldn't this page have both of them marked as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0255e0c3-6f50-a3c5-4ef0-7d93d597e9c9
* Version Independent ID: fd034f77-24f7-3455-5355-ddeb1ad38b21
* Content: [Execution Plans - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/execution-plans?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/execution-plans.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/execution-plans.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by pmasl** [comment]
@dcbrown16 indeed. Will be corrected in the next few hours. Thanks!

**Comment by WilliamAntonRohm** [comment]
@pmasl -- Pedro, thank you for updating this article.
