### ISSUE TITLE
The SQL provided in section C is formatted incorrectly, and the syntax coloring is not right.

### ISSUE THREAD

**Issue by Protiguous** [MicrosoftDocs/sql-docs#4598]
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/throw-transact-sql?view=sql-server-ver15#c-using-formatmessage-with-throw

**Comment by WilliamAntonRohm** [comment]
@Protiguous -- thank you for catching that.  I am looking into the article.

**Comment by WilliamAntonRohm** [comment]
This issue is superseded by #4921
