### ISSUE TITLE
Advanced Scripting Options Page lost the explanation for "Check for object existence"

### ISSUE THREAD

**Issue by chucklu** [MicrosoftDocs/sql-docs#4603]
The screenshot contains “Check for object existence” while the documentation did not contain it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 222643c9-2ac1-11f6-4913-5e2e5216dfe6
* Version Independent ID: 7bb94693-57be-7775-0f40-ce7681a8b655
* Content: [Generate and Publish Scripts Wizard - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/scripting/generate-and-publish-scripts-wizard?view=sql-server-ver15)
* Content Source: [docs/ssms/scripting/generate-and-publish-scripts-wizard.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/generate-and-publish-scripts-wizard.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@chucklu -- Chuck, thank you for your feedback.

@markingmyname -- Mark, please look into this issue, located [here](https://docs.microsoft.com/en-us/sql/ssms/scripting/generate-and-publish-scripts-wizard?view=sql-server-ver15#AdvScriptOpt).

**Comment by markingmyname** [comment]
Thanks, @chucklu, for bringing this to our attention.

The article will be updated later this week.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
