### ISSUE TITLE
wrong data type for latch_class

### ISSUE THREAD

**Issue by jmanske** [MicrosoftDocs/sql-docs#4606]
The data type for latch_class is nvarchar(60), not nvarchar(120). 120 is the length (because it is 2 bytes per character)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0c89bc5-3d69-c14b-5d0e-dad924dfee15
* Version Independent ID: ffc4c63d-2958-813c-c7b3-89b13c470af7
* Content: [sys.dm_os_latch_stats (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-latch-stats-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-os-latch-stats-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-os-latch-stats-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@jmanske -- thank you for catching this.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- please review [private PR 14754](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14754).

**Comment by jmanske** [comment]
Why was this closed? Is the data type actually nvarchar(120)? sp_help has the length as 120 which means it is actually nvarchar(60). Is sp_help broken?

**Comment by WilliamAntonRohm** [comment]
@jmanske -- I have updated the document, and that auto-closed this issue.  Your correction will be live tomorrow.
