### ISSUE TITLE
LockMode and LockOwner data types are wrong

### ISSUE THREAD

**Issue by jmanske** [MicrosoftDocs/sql-docs#4607]
Both are varchar(32), not nvarchar(32) (as of SQL Server 2019 CU4)

create procedure sys.sp_getapplock --- 1999/04/14 00:00
 @Resource nvarchar (255) = NULL,           -- Resource to lock
 @LockMode varchar (32),                    -- Lock mode
 @LockOwner varchar (32) = 'Transaction',   -- Lock Owner - [D = Transaction]
 @LockTimeout int = NULL,                   -- Lock timeout [D = Session setting]
 @DbPrincipal sysname = N'public'	    -- DB principal to use for name space and permissions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfc5142-4589-ac67-69c2-65d7760719e4
* Version Independent ID: 02464294-1e91-30e6-8489-51ee2ee45a31
* Content: [sp_getapplock (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-getapplock-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-getapplock-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-getapplock-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@jmanske -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- please review [private PR 14755](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14755).
