### ISSUE TITLE
Error in examples

### ISSUE THREAD

**Issue by tejasvih** [MicrosoftDocs/sql-docs#4608]
In Examples, 

@StartingRowNumber and @FetchRows are wrongly used.
For example, in: B. Specifying variables for OFFSET and FETCH values

-- Specifying variables for OFFSET and FETCH values    
DECLARE @StartingRowNumber tinyint = 1  
      , @FetchRows tinyint = 8;  
SELECT DepartmentID, Name, GroupName  
FROM HumanResources.Department  
ORDER BY DepartmentID ASC   
    OFFSET @StartingRowNumber ROWS   
    FETCH NEXT @FetchRows ROWS ONLY;  

This skips first row because of @StartingRowNumber is 1. whereas OFFSET needs number of records to skip. In this case, it skips 1 record.

Example could be written as:

-- Specifying variables for OFFSET and FETCH values    
DECLARE @RowToSkip tinyint = 0
      , @FetchRows tinyint = 8;  
SELECT DepartmentID, Name, GroupName  
FROM HumanResources.Department  
ORDER BY DepartmentID ASC   
    OFFSET @RowToSkip ROWS   
    FETCH NEXT @FetchRows ROWS ONLY; 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e30064c-9e16-640d-19ce-4b62c4cee65b
* Version Independent ID: 7f1a98a5-81c8-6b04-c216-ffdf81d31cce
* Content: [ORDER BY Clause (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/queries/select-order-by-clause-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/select-order-by-clause-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@tejasvih -- Tejasvi, thank you for your suggestion.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please review [private PR 14756](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14756).
