### ISSUE TITLE
Invalid column_name in the resultset of sp_server_diagnostics. 

### ISSUE THREAD

**Issue by ojngo** [MicrosoftDocs/sql-docs#4611]
There is no "creation_time" column in the resultset of sp_server_diagnostics, only "create_time".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f12452-bb91-08c1-04ff-0f6f5036c742
* Version Independent ID: 628bdd4d-fc17-8732-a6e6-945eb35b00c5
* Content: [sp_server_diagnostics (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-server-diagnostics-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-server-diagnostics-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-server-diagnostics-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@ojngo -- thank you for your feedback.  I am looking into this issue.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- please review [private PR 14804](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14804).
