### ISSUE TITLE
Incorrect description for %:Requests counters

### ISSUE THREAD

**Issue by ochoto** [MicrosoftDocs/sql-docs#4612]
It seems that counters Elapsed Time:Requests and CPU Time:Requests are mistakenly described as time instead of request count.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7407ac02-763a-1ce1-f5ad-023c5c2f9f0d
* Version Independent ID: 43143896-5251-a4e6-be26-9aa9a44b7923
* Content: [SQL Server, Batch Resp Statistics Object - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-batch-resp-statistics-object?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/performance-monitor/sql-server-batch-resp-statistics-object.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance-monitor/sql-server-batch-resp-statistics-object.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@ochoto -- Xabi, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@ochoto -- Xabi, it seems the descriptions are accurate as-is.

@julieMSFT -- Julie, please help clarify the difference here in plural vs singular:
> CPU Time:Requests
> The time the CPU spent on the request.

> Elapsed Time:Requests
> The elapsed time of the request.

**Comment by julieMSFT** [comment]
@ochoto Thank you for your input. I am looking into this.

**Comment by WilliamDAssafMSFT** [comment]
#inprogress

**Comment by WilliamDAssafMSFT** [comment]
@ochoto Thanks for the input here. A doc update is in flight. Sorry about the delay.

**Comment by WilliamDAssafMSFT** [comment]
#please-close
