### ISSUE TITLE
Document SQL standard compliance

### ISSUE THREAD

**Issue by vanillajonathan** [MicrosoftDocs/sql-docs#4616]
Does Microsoft SQL Server fully support SQL:1999, SQL:2003, SQL:2006, SQL:2008, SQL:2011 and SQL:2016?

What standards are fully supported?
What standards are partially supported?
What standards are are not supported?
What functionality differs from that one of the standard?
What is functionally equivalent?

PostgreSQL have a [SQL conformance](https://www.postgresql.org/docs/current/features.html) page documents [supported features](https://www.postgresql.org/docs/current/features-sql-standard.html), [unsupported features](https://www.postgresql.org/docs/current/unsupported-features-sql-standard.html), and [limits in conformance](https://www.postgresql.org/docs/current/xml-limits-conformance.html).
Firebird have a [SQL conformance](https://www.firebirdsql.org/en/sql-conformance/) page.
MySQL have a page on [MySQL Differences from Standard SQL](https://dev.mysql.com/doc/refman/8.0/en/differences-from-ansi.html)
Oracle have a [Oracle and Standard SQL](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Oracle-and-Standard-SQL.html) chapter in their documentation.

Wikipedia have a incomplete article on [SQL compliance](https://en.wikipedia.org/wiki/SQL_compliance) with a comparison table.

**Comment by WilliamAntonRohm** [comment]
@vanillajonathan -- Jonathan, please add your suggestion & questions here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

**Comment by vanillajonathan** [comment]
This could be auto-generated if SQL feature F501-01 was supported which exposes a SQL_FEATURES view on the INFORMATION_SCHEMA.

```sql
SELECT * FROM information_schema.sql_features
```
