### ISSUE TITLE
Sample executing issue.

### ISSUE THREAD

**Issue by EinsteinSu** [MicrosoftDocs/sql-docs#4619]
[Enter feedback here]
I got this error when running the sample

Exception has occurred: AttributeError
'AxesSubplot' object has no attribute '_stale_viewlim_x'
  File "C:\Users\QAMAdmin\showplot.py", line 11, in <module>
    fig.savefig(str(i)+'.png')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6fd8a06-35b9-9fc3-4912-d9af48ab95e5
* Version Independent ID: 537915f7-101b-5783-d2a9-546fd7a54ce6
* Content: [Python + T-SQL: Explore data - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/tutorials/sqldev-py3-explore-and-visualize-the-data?view=sql-server-ver15#feedback)
* Content Source: [docs/machine-learning/tutorials/sqldev-py3-explore-and-visualize-the-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/tutorials/sqldev-py3-explore-and-visualize-the-data.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@EinsteinSu Thank you for opening the GitHub issue. To be able to troubleshoot the issue, I would like to kindly ask you which version of SQL Server you are running (including the build number)? Thank you.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
