### ISSUE TITLE
Synapse "Understanding Query Plans" link points to APS AU5 client documentation download

### ISSUE THREAD

**Issue by amvieira** [MicrosoftDocs/sql-docs#4621]
Hi,
At the begining of the article, there is a statement "Understanding Query Plans in the Parallel Data Warehouse product documentation" that refers the url https://www.microsoft.com/download/details.aspx?id=51610
This URL is pointing to the download of the client documents for the AU5 Client documentation.
Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1f7a9b-c3a6-1728-6c2a-3073ec4c9185
* Version Independent ID: 33b78b9b-c3aa-1c01-e944-caff029aee0e
* Content: [EXPLAIN (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/explain-transact-sql?view=azure-sqldw-latest&source=docs)
* Content Source: [docs/t-sql/queries/explain-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/explain-transact-sql.md)
* Product: **sql**
* Technology: **data-warehouse**
* GitHub Login: @XiaoyuMSFT
* Microsoft Alias: **xiaoyul**

**Comment by WilliamAntonRohm** [comment]
@amvieira -- Artur, thank you for bringing this to our attention.  This article does not apply to Parallel Data Warehouse.

@XiaoyuMSFT -- please look into this issue.

**Comment by XiaoyuMSFT** [comment]
Removed the invalid link.

**Comment by XiaoyuMSFT** [comment]
#please-close
