### ISSUE TITLE
rbac apiVersion update

### ISSUE THREAD

**Issue by mwdarab** [MicrosoftDocs/sql-docs#4627]
I believe the apiVersion needs to be updated in the rbac example above to: /v1    (not v1beta1)

as seen in the Kubernetes docs example here: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#restrictions-on-role-binding-creation-or-update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8bb827-4819-7b2d-490a-071f6b7b57a2
* Version Independent ID: 65b90b91-5946-b2d1-b97a-537bc9b014ca
* Content: [Configure Kubernetes with kubeadm - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-with-kubeadm?view=sql-server-ver15#configure-the-kubernetes-master)
* Content Source: [docs/big-data-cluster/deploy-with-kubeadm.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-with-kubeadm.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@mwdarab -- Mohammad, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review [private PR 14810](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14810).
