### ISSUE TITLE
Syntax presentation is inconsistent with Transact-SQL Syntax Conventions

### ISSUE THREAD

**Issue by rcaldwell-hiusa** [MicrosoftDocs/sql-docs#4628]
This page deviates from the standards set forth at https://docs.microsoft.com/en-us/sql/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql?view=sql-server-ver15

Which is confusing as hell... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13793c61-629f-f379-fcb7-e9178e4f5dce
* Version Independent ID: ced6efc1-1e34-f452-f995-b597e812c2f2
* Content: [CREATE INDEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-index-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-index-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@rcaldwell-hiusa -- thank you for your feedback.  Please provide an example and I will be able to look into this further.
