### ISSUE TITLE
References to max rowgroup size of 1,024,576 rows is incorrect

### ISSUE THREAD

**Issue by mortgagemetrix** [MicrosoftDocs/sql-docs#4632]
This page references a maximum rowgroup size of 1,024,576 rows. This is incorrect. The maximum rowgroup size for a clustered columnstore is 1,048,576 rows. It appears that this typo occurred because the minimum compressed rowgroup size is 102,400.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40c68674-b35e-416e-33d5-da18290e1640
* Version Independent ID: 7310124c-a4ff-a221-0ece-82bab37d6f62
* Content: [Detecting and resolving fragmented indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/reorganize-and-rebuild-indexes?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/indexes/reorganize-and-rebuild-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/reorganize-and-rebuild-indexes.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @pmasl
* Microsoft Alias: **mikeray**

**Comment by pmasl** [comment]
Thanks for catching this.

**Comment by WilliamAntonRohm** [comment]
@mortgagemetrix -- Tom, thank you for your feedback.  I am looking into this topic.

**Comment by pmasl** [comment]
> @mortgagemetrix -- Tom, thank you for your feedback. I am looking into this topic.

It's fixed already
