### ISSUE TITLE
References to max clustered columstore rowgroup size of 1,024,576 rows is incorrect. 

### ISSUE THREAD

**Issue by mortgagemetrix** [MicrosoftDocs/sql-docs#4633]
This page references a maximum rowgroup size of 1,024,576 rows. This is incorrect. The maximum rowgroup size for a clustered columnstore is 1,048,576 rows. It appears that this typo occurred because the minimum compressed rowgroup size is 102,400.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773ed159-a586-0660-729b-c9b4cb249e48
* Version Independent ID: 8a27afa6-4e12-2a63-b272-123108808479
* Content: [ALTER INDEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-index-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/alter-index-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-index-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **carlrab**

**Comment by pmasl** [comment]
Thanks for catching this.

**Comment by WilliamAntonRohm** [comment]
@mortgagemetrix -- Tom, thank you again for your feedback.  I am looking into this topic as well.

**Comment by WilliamAntonRohm** [comment]
@pmasl -- Pedro, please review [private PR 14811](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14811).

**Comment by pmasl** [comment]
This had already been fixed.
