### ISSUE TITLE
Supported Client Drivers list missing

### ISSUE THREAD

**Issue by mispencer** [MicrosoftDocs/sql-docs#4634]
Where is this? The link on this page is a loop, linking to itself, which isn't useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a7130ba-36cc-7733-8c95-7905fa186b4f
* Version Independent ID: 6adca6aa-fba3-b678-ae3c-44cbbe37af18
* Content: [Always Encrypted with secure enclaves - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-enclaves?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/security/encryption/always-encrypted-enclaves.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/always-encrypted-enclaves.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@mispencer, thank you for your feedback.  I am looking into this topic.

**Comment by WilliamAntonRohm** [comment]
@jaszymas -- please let me know if there is a more suitable replacement link than this one:
- [Using Always Encrypted with Secure Enclaves with the PHP Drivers for SQL Server](https://docs.microsoft.com/en-us/sql/connect/php/always-encrypted-secure-enclaves)

**Comment by eNeRGy164** [comment]
This is still not fixed.

Found a list for .NET related drivers:
https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-enclaves-client-development

**Comment by jaszymas** [comment]
Resolved with https://github.com/MicrosoftDocs/sql-docs-pr/pull/17684

**Comment by jaszymas** [comment]
#please-close
