### ISSUE TITLE
Query Optimizer Fixes option is not explained in depth and the link to trace flag seems to link to outdated file 

### ISSUE THREAD

**Issue by NaomiN** [MicrosoftDocs/sql-docs#4636]
There is not enough info about Query Optimizer Fixes option. The link to trace flag discusses version 2016 as the most recent.

I'm creating a new Azure DB and want to make sure to specify correct option which is OFF by default

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ff5f89-39e8-2526-9f4c-fd03c8674fdc
* Version Independent ID: d27b5731-f02e-c33c-5a6e-86a0a7ea0522
* Content: [Database Properties (Options Page) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-properties-options-page?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/database-properties-options-page.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/database-properties-options-page.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@NaomiN - thanks for raising this issue.  Doc update should go live today. I updated the description/link:

Enables or disables query optimization hotfixes on the primary regardless of the compatibility level of the database. This is equivalent to [Trace Flag 4199](https://docs.microsoft.com/sql/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql). For details, see [QUERY_OPTIMIZER_HOTFIXES](https://docs.microsoft.com/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql#qo_hotfixes).


Thanks!

**Comment by stevestein** [comment]
#please-close
