### ISSUE TITLE
sys.server_principals view?

### ISSUE THREAD

**Issue by jeffqu17** [MicrosoftDocs/sql-docs#4637]
The [doc located here](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-server-principals-transact-sql?view=sql-server-ver15) suggests that the sys.server_principals view exists as part of Sql Datawarehouse now called Azure Synapse Analytics however, it does not exist in the multiple installations we have examined. Was the view removed and part of earlier releases of the product? 

This question is related to compliance reviews.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39c5adf9-f58f-34f7-d410-a2340912a734
* Version Independent ID: 244eccee-f8d3-f99f-9d65-c59bd392f218
* Content: [sys.server_principals (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-server-principals-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-catalog-views/sys-server-principals-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-server-principals-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @jeffqu17! Thanks for bringing up this issue. The page you're referencing shows that Azure Synapse is not included as having that view:

![image](https://user-images.githubusercontent.com/40007119/80475155-5016db00-88fd-11ea-82ed-7a04b850222d.png)

Are you seeing that this appears somewhere?

**Comment by VanMSFT** [comment]
I'll go ahead and close this for now, but please let us know if you have any concerns, and we can address them.
