### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by Mitch-Wheat** [MicrosoftDocs/sql-docs#4640]
This page is out of date. SQL Server 2017 RTM contains these additional columns:
cluster_type
cluster_type_desc
required_synchronized_secondaries_to_commit
sequence_number,

SQL Server 2019 adds another column: is_contained

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07c84e50-00f3-ea41-f75c-940489feed76
* Version Independent ID: c6055306-ce3c-d48b-ddad-ff31fe3e0689
* Content: [sys.availability_groups (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-availability-groups-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-catalog-views/sys-availability-groups-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-availability-groups-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rothja** [comment]
@Mitch-Wheat Thank you for letting us know. We are looking into this, and apologies for the delayed response!

**Comment by MikeRayMSFT** [comment]
@Mitch-Wheat - thanks for the submission. I'm preparing a doc update. Sorry about the wait.
