### ISSUE TITLE
Doesn't actually give the example that is so important.

### ISSUE THREAD

**Issue by cdichter** [MicrosoftDocs/sql-docs#4642]
This article fails to answer a fundamental question that is at the heart of why this function is needed. How do you enter single quote as an argument?

If you already know how to properly escape a single quote in T-SQL, this function is of limited value. And if you don't know, this funciton with this documentation is of no value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c758dbd-4b19-ce16-1f41-f607a1353c43
* Version Independent ID: 997552d7-2715-57d4-bccc-0411f6663a12
* Content: [QUOTENAME (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/quotename-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/functions/quotename-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/quotename-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@cdichter Thank you for the feedback.

An example has been added to the documentation and is pending review.
