### ISSUE TITLE
salzburg

### ISSUE THREAD

**Issue by christian7877** [MicrosoftDocs/sql-docs#4645]
SELECT  DB_NAME(sd.source_database_id) AS [SourceDatabase], 
		sd.name AS [Snapshot],
		mf.name AS [Filename], 
		size_on_disk_bytes/1024 AS [size_on_disk (KB)],
		mf2.size/128 AS [MaximumSize (MB)]
FROM sys.master_files mf
JOIN sys.databases sd
	ON mf.database_id = sd.database_id
JOIN sys.master_files mf2
	ON sd.source_database_id = mf2.database_id
	AND mf.file_id = mf2.file_id
CROSS APPLY sys.dm_io_virtual_file_stats(sd.database_id, mf.file_id)
WHERE mf.is_sparse = 1
AND mf2.is_sparse = 0
ORDER BY 1;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb223d8-50d2-3a19-f305-bcba59ec6faa
* Version Independent ID: 18fccb29-bf5a-c370-f431-b712d66cf842
* Content: [View size of sparse file of a Database Snapshot (T-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/view-the-size-of-the-sparse-file-of-a-database-snapshot-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/view-the-size-of-the-sparse-file-of-a-database-snapshot-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/view-the-size-of-the-sparse-file-of-a-database-snapshot-transact-sql.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@christian7877   Thank you for the feedback.

If there are issues with the documentation or in the query referenced above, please provide them as additional details below.

**Comment by msebolt** [comment]
Closing this now, please comment below if there are further issues.
