### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by BalazsM** [MicrosoftDocs/sql-docs#4647]
The second example (&lt;path&gt;\LoginsAudit_{GUID}) in the file_pattern section only works when I put an asterisk on the end of it: SELECT * FROM sys.fn_get_audit_file ('&lt;path&gt;\LoginsAudit_{GUID}*', default, default);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3794494c-9b85-3c07-11fb-32c0573cbacb
* Version Independent ID: 5ae86b59-0ac0-06f1-88bc-0c55fa8c43a0
* Content: [sys.fn_get_audit_file (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/sys-fn-get-audit-file-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-functions/sys-fn-get-audit-file-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-functions/sys-fn-get-audit-file-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@BalazsM Thank you for the feedback.

The documentation has been updated and is pending review.
