### ISSUE TITLE
seeding_mode Columns

### ISSUE THREAD

**Issue by PhilipKelley** [MicrosoftDocs/sql-docs#4649]
A query against this catalog view returns additional columns
  seeding_mode
  seeding_mode_desc
What are they? Please add documentation!

Version used: Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2b25f04-95d4-9375-3c8b-4bbfe9957d6f
* Version Independent ID: 198a432b-fc11-0d67-896d-ac2ea523f390
* Content: [sys.availability_replicas (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-availability-replicas-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-catalog-views/sys-availability-replicas-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-availability-replicas-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rothja** [comment]
@PhilipKelley Thank you for letting us know, and apologies for the delayed response. We are confirming and will try to get back to you soon. Thanks for your patience!

**Comment by MikeRayMSFT** [comment]
@PhilipKelley - I have an update that I'm preparing. Thanks for the submission.
