### ISSUE TITLE
SSMS 18.4, 18.5 no Database Upgrade or Tuning Assistant

### ISSUE THREAD

**Issue by jschrap** [MicrosoftDocs/sql-docs#4650]
In SSMS, when selecting Tasks, there is no option to select Database Upgrade, in combination with Azure SQL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acff5ec8-7513-131b-b45f-bdaff9b7dfc1
* Version Independent ID: 68c2239d-c014-a3bd-d8c3-832b50e2bb59
* Content: [Upgrade databases using Query Tuning Assistant - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/upgrade-dbcompat-using-qta?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/performance/upgrade-dbcompat-using-qta.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/upgrade-dbcompat-using-qta.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by pmasl** [comment]
At this point in time, the task isn't available for Azure SQL. Will be correcting the header that references Azure SQL DB.

**Comment by pmasl** [comment]
#please-close
