### ISSUE TITLE
alpine linux install fails

### ISSUE THREAD

**Issue by droopy4096** [MicrosoftDocs/sql-docs#4651]
```shell
# curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.5.2.2-1_amd64.apk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1213  100  1213    0     0   1691      0 --:--:-- --:--:-- --:--:--  1689
/ # apk add mssql-tools_17.5.2.2-1_amd64.apk 
ERROR: mssql-tools_17.5.2.2-1_amd64.apk: IO ERROR
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#alpine-linux)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by droopy4096** [comment]
```shell
$ file mssql-tools_17.5.2.2-1_amd64.apk 
mssql-tools_17.5.2.2-1_amd64.apk: HTML document, ASCII text
$ grep header mssql-tools_17.5.2.2-1_amd64.apk 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
<div id="header"><h1>404 Not Found</h1></div>
```

**Comment by David-Engel** [comment]
@droopy4096 Thanks for the submission. We actually noticed this error earlier today and the doc change is scheduled to be pushed out within a couple hours. The correct URL is:
https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.5.2.1-1_amd64.apk
and if you need the signature file:
https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.5.2.1-1_amd64.sig

Regards,
David

**Comment by David-Engel** [comment]
#please-close
