### ISSUE TITLE
You need to share how to make insertion caret visible.

### ISSUE THREAD

**Issue by MCcoder52** [MicrosoftDocs/sql-docs#4652]
You need to share how to make insertion caret visible in the query edit window. Seriously.  Who starts typing without knowing where the text is going to go?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b1a74a-487c-8b7a-894c-454d5986ed1b
* Version Independent ID: 001c4d17-589b-ccd5-9887-52bead593258
* Content: [SQL Server Management Studio Keyboard Shortcuts - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/sql-server-management-studio-keyboard-shortcuts?view=sql-server-ver15)
* Content Source: [docs/ssms/sql-server-management-studio-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/sql-server-management-studio-keyboard-shortcuts.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@MCcoder52 Thank you for the feedback.

Please refer to the [cursor commands](https://docs.microsoft.com/en-us/sql/ssms/sql-server-management-studio-keyboard-shortcuts?view=sql-server-ver15#cursor-movement-keyboard-shortcuts) combined with the editor's purple mark for current location:

![Capture](https://user-images.githubusercontent.com/6675884/81627159-69fef600-93b2-11ea-8c7d-25db6fc1e04d.PNG)

To comment on missing features, please start a thread with the product team using [SQL Server feedback](https://feedback.azure.com/forums/908035-sql-server) or [SQL Server forums](https://social.msdn.microsoft.com/Forums/sqlserver/home?category=sqlserver).

**Comment by MCcoder52** [comment]
Thank you.The error was mine. I am working with two different sized displays connected to a single laptop. Working on a complex query, I had to move the application back and forth between displays. At some point it shrank, the insertion caret was too small to render and I was so focused on the query, I did not notice I was working through a 4x4 inch keyhole. I posted the remark (Thanks again for your kind reply), returned to my work and noticed what was going on.Can’t remember last time that happened. Sent from Mail for Windows 10 From: Matthew SeboltSent: Monday, May 11, 2020 9:09 PMTo: MicrosoftDocs/sql-docsCc: MCcoder52; MentionSubject: Re: [MicrosoftDocs/sql-docs] You need to share how to make insertion caret visible. (#4652) @MCcoder52 Thank you for the feedback.Please refer to the cursor commands combined with the editor's purple mark for current location:To comment on missing features, please start a thread with the product team using SQL Server feedback or SQL Server forums.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by msebolt** [comment]
@MCcoder52 Sure, sounds good.  Thank you for posting the full explanation and contributing to the docs.

Closing this issue now.
