### ISSUE TITLE
Think you've got your Lat/Lngs mixed up here.

### ISSUE THREAD

**Issue by spatialbits** [MicrosoftDocs/sql-docs#4653]
"Lat
Is a float expression representing the x-coordinate of the Point being generated.

Long
Is a float expression representing the y-coordinate of the Point being generated. For more information on valid latitude and longitude values, see Point."

Seems to me it should be the reverse: Long representing the X and Lat represents the Y.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd5d5523-6420-23c6-88a0-fe4557ec1a28
* Version Independent ID: 5352029c-f717-cb65-185f-b5326acca049
* Content: [Point (geography Data Type) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geography/point-geography-data-type?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Point_TSQL)%3Bk(sql13.swb.tsqlresults.f1)%3Bk(sql13.swb.tsqlquery.f1)%3Bk(MiscellaneousFilesProject)%3Bk(DevLang-TSQL)%26rd%3Dtrue&view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/spatial-geography/point-geography-data-type.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/spatial-geography/point-geography-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@spatialbits -- Adam, thank you for your feedback.  There is a Note under [Return Types](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geography/point-geography-data-type?view=sql-server-ver15#return-types):
> Arguments for the Point (geography Data Type) method have coordinates reversed compared to WKT.

I'll move this Note up under Arguments for better clarity.

**Comment by spatialbits** [comment]
Hi @WilliamAntonRohm. I think the bit about the parameter order is OK. But, specifically the text "Lat ... Is a float expression representing the **x-coordinate** . It should be:
"Lat ... Is a float expression representing the **y-coordinate** "; same for Long.

**Comment by WilliamAntonRohm** [comment]
@spatialbits -- Adam, I concur.  I'm updating the article.

**Comment by WilliamAntonRohm** [comment]
@MladjoA -- Mladen, please review [private PR 14816](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14816).
