### ISSUE TITLE
unclear that IDENTITY must be 'SHARED ACCESS SIGNATURE' for blob storage

### ISSUE THREAD

**Issue by ChrisMenegay** [MicrosoftDocs/sql-docs#4660]
I spent hours on this. For Azure Blob storage I could only get it to work if I set IDENTITY to 'SHARED ACCESS SIGNATURE'.  another doc page indicated IDENTITY wasn't even used. I could use either an Access Key or SAS for the secret.
 
CREATE DATABASE SCOPED CREDENTIAL AzureStorageCredential
WITH
  IDENTITY = 'SHARED ACCESS SIGNATURE' ,
  SECRET = 'this can be and access key or a shared access sig'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e450abc6-2dbd-8f6c-423c-52aca37a2b06
* Version Independent ID: 4aff678a-6db1-a438-9aca-bb4b4d49bc27
* Content: [CREATE EXTERNAL DATA SOURCE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql?toc=/azure/synapse-analytics/sql-data-warehouse/toc.json&bc=/azure/synapse-analytics/sql-data-warehouse/breadcrumb/toc.json&view=azure-sqldw-latest)
* Content Source: [docs/t-sql/statements/create-external-data-source-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-data-source-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@ChrisMenegay Sorry for your confusion. I too am confused about your precise question. Do you have a question about CREATE DATABASE SCOPED CREDENTIAL or about CREATE EXTERNAL DATA SOURCE?  What other pages are you looking at that are confusing you? If you set up your container in Azure Blob storage to accept anonymous connections, WITH IDENTITY is not needed. It is needed is you place security on your container in Azure Blob storage.

**Comment by ChrisMenegay** [comment]
CREATE DATABASE SCOPED CREDENTIAL - what you mentioned is what needs to be added.  Above it says "You can specify any string in database scoped credential identity as it isn't used during authentication to Azure storage."  It needs to be stated that if you security you need to provide the IDENTITY and that the IDENTITY MUST BE "SHARED ACCESS SIGNATURE".  I was using just "SAS" or "AccessKey" for IDENTITY for dozens of attempts before just trying "SHARED ACCESS SIGNATURE" since that was in a lot of the examples I found online.

**Comment by CarlRabeler** [comment]
PR pending - adds reference to this article and states that IDENTITY is optional if anonymous is enabled for Azure Blob storage
