### ISSUE TITLE
Can you elaborate on hardware and software requirements to install and run SSMS?

### ISSUE THREAD

**Issue by masaki1234** [MicrosoftDocs/sql-docs#4661]
Hello,

This page has a list of supported operating systems to install SSMS. But I am not sure of the other software and hardware requirements to install and run SSMS. What is the minimum required memory? How much disk space does it require for installation?

The following Microsoft web page provides the hardware, software, and disk space requirements for SQL Server, but it does not mention SSMS so I cannot assume that the SSMS requirements are identical to the SQL Server requirements.
https://docs.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server

Thanks,
Masaki

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by markingmyname** [comment]
@masaki1234 

We are working on adding this info to the article.

Thanks for the feedback.  To answer your question, for now, it is similar to the [specs of VS2017](https://docs.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15?view=sql-server-ver15).  The caveat is it does not require the same amount of disk space.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
