### ISSUE TITLE
Setting scope

### ISSUE THREAD

**Issue by Ponchothewise** [MicrosoftDocs/sql-docs#4666]
The page should make clear the scope at which this setting takes effect - session, procedure/batch, table setting etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a803389f-08b7-7078-a104-707c612722b3
* Version Independent ID: 02f17dab-452a-7300-0bee-76b2a03e9517
* Content: [SET IDENTITY_INSERT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-identity-insert-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/set-identity-insert-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-identity-insert-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@Ponchothewise I do not understand your question. Can you please elaborate?

**Comment by CarlRabeler** [comment]
@Ponchothewise closing due to the lack of response to my request for clarity / elaboration. Please re-open with more detail if still an open issue. 
Thanks,
Carl
