### ISSUE TITLE
Sample Database

### ISSUE THREAD

**Issue by steebn** [MicrosoftDocs/sql-docs#4668]
Would be helpful to have a link to the required pubs sample database in the Examples: https://docs.microsoft.com/en-us/sql/t-sql/queries/readtext-transact-sql?view=sql-server-2016#examples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a1fb25f-6d0a-24ca-a667-741c74574e0f
* Version Independent ID: e931b5ea-2cfb-0720-c057-d384c436862c
* Content: [READTEXT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/readtext-transact-sql?view=sql-server-2016#examples)
* Content Source: [docs/t-sql/queries/readtext-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/readtext-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @steebn! Thanks for the suggestion. I added a link to our sql-server-samples github repository that has the northwind-pubs database. The document should be live later today.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- thank you for adding that link.  I am closing this issue now.
