### ISSUE TITLE
Visual C++ Redistributable Package required for SQL Server 2019

### ISSUE THREAD

**Issue by astretch** [MicrosoftDocs/sql-docs#4670]
After quite a bit of trial and error I managed to get SQL Server 2019 TDE/EKM using Azure Key Vault working. Although the documentation version for this page was set to SQL Server 2019, there is no documentation pertaining to which version of the Visual C++ Redistributable is required to enable the SQL Server Connector for SQL Server 2019. The page currently notes that SQL Server versions 2014 and older require Visual C++ Redistributable Packages for Visual Studio 2013, while SQL Server 2016 requires Visual C++ Redistributable for Visual Studio 2015. 
The Visual C++ Redistributable installed with SQL Server 2019 is the Visual C++ Redistributable Package for Visual Studio 2017, which does not currently work with the SQL Server Connector. One would assume that since the documentation shows SQL Server 2016 "supposedly" requires the Visual Studio 2015 version, that SQL Server 2019 would use the same; however SQL Server 2019 currently requires the Visual C++ Redistributable for Visual Studio 2013 in order to enable the SQL Connector.

To Do:
Please verify that your documentation for SQL Server 2016 is correct.
Please add documentation for SQL Server 2017.
Please add documentation for SQL Server 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4997f245-c966-51a3-34c7-705c3cfbd4b0
* Version Independent ID: 129fbe40-3b02-f2c1-ef13-b42d86ffdb77
* Content: [Setup TDE Extensible Key Management with Azure Key Vault - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@astretch -- thank you for your thorough feedback.

@jaszymas -- please look into this issue.

**Comment by VanMSFT** [comment]
Hello @astretch - I apologize for the delay. We have updated the section regarding the SQL Server Connector, but it looks like the Visual C++ Redistributable portion has not been updated.

@Rupp29 @shohamMSFT - Hey Adrian/Shoham, do you mind checking on this issue and see if we can get an update? It looks like even the download site has outdate prereqs.

https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-ver15&tabs=portal#prerequisites

**Comment by Rupp29** [comment]
I had to reach out to the engineer to track down the correct answer for the C++ versions.
I just heard from the engineer this morning, he said he was looking into it.
Once that is confirmed, I can update the docs with the appropriate information.


::Adrian

**Comment by VanMSFT** [comment]
@Rupp29 - Thanks Adrian!

#reassign:Rupp29

**Comment by VanMSFT** [comment]
@Rupp29 - Hey Adrian, checking back on this. Did we get an answer?

**Comment by Rupp29** [comment]
Nothing yet.
I’m not sure how to move ahead on this.
I don’t have to the means to test this myself.

Adrian Rupp
Sr. Program Manager
Azure SQL DB - Security
VoIP: 425.705.4895
Mobile: 425.753.4998
Email: ***@***.***
________________________________

**Comment by MikeRayMSFT** [comment]
@Rupp29 fixed this in https://github.com/MicrosoftDocs/sql-docs/commit/7d2922dfe23c77d6ef52e8a7bef7bc302cf94f03
