### ISSUE TITLE
this doesn't work

### ISSUE THREAD

**Issue by gwellbrock** [MicrosoftDocs/sql-docs#4671]
pcs resource create ag_cluster ocf:mssql:ag ag_name=my_ag1 meta failure-timeout=30s master notify=true

your documentation has --master which causes issues

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7de1f2c-d879-9ce4-09fd-251fc3dacc05
* Version Independent ID: 4de58f31-0b21-f4da-2a43-1eb4e8151f00
* Content: [Configure Ubuntu cluster for availability group - SQL Server on Linux](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-cluster-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-availability-group-cluster-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-availability-group-cluster-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@gwellbrock -- Greg, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review [private PR 14876](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14876).
