### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by ryanwadebg** [MicrosoftDocs/sql-docs#4672]
[Enter feedback here]
To whom it may concern,

I get the following error:
```
Msg 39004, Level 16, State 19, Line 2
A 'R' script error occurred during execution of 'sp_execute_external_script' with HRESULT 0x80004004.
Msg 39019, Level 16, State 2, Line 2
An external script error occurred: 

[Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user 'NT Service\MSSQLLaunchpad'.


Error in doTryCatch(return(expr), name, parentenv, handler) : 
  [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user 'NT Service\MSSQLLaunchpad'.

Calls: source ... eval -> eval -> rxWriteObject -> rxWriteObject.RxOdbcData
```

When I run the following code to train the partition based model in the example:
```
--Example 2: Train on 20 percent of the dataset to expedite processing.
EXEC train_rxLogIt_per_partition N'
  SELECT tipped, payment_type, passenger_count, trip_time_in_secs, trip_distance, d.direct_distance
  FROM dbo.nyctaxi_sample TABLESAMPLE (20 PERCENT) REPEATABLE (98074)
  CROSS APPLY [CalculateDistance](pickup_latitude, pickup_longitude,  dropoff_latitude, dropoff_longitude) as d
';
GO
```
To trouble shoot, I refactored the code and ran it in R Studio inside a ***Data Science Virtual Machine*** using Windows 2019. I created a data frame that had the same name as the input data frame in the stored procedure and I changed the serve name to “DSVM2019” in the connection string instead of using the results of the ***@@SERVERNAME***. The connection string would not work when I used ***@@SERVERNAME***. Here is the code that I ran in R Studio:

```
library(RODBC)

sql <- "SELECT tipped, payment_type, passenger_count, trip_time_in_secs, trip_distance, d.direct_distance
FROM dbo.nyctaxi_sample TABLESAMPLE (20 PERCENT) REPEATABLE (98074)
CROSS APPLY [CalculateDistance](pickup_latitude, pickup_longitude,  dropoff_latitude, dropoff_longitude) as d"

conn <- odbcDriverConnect('driver={SQL Server};server=DSVM2019;database=NYCTaxi_Sample;trusted_connection=true')
InputDataSet <- sqlQuery(conn, sql)


# Make sure InputDataSet is not empty. In parallel mode, if one thread gets zero data, an error occurs
if (nrow(InputDataSet) > 0) {
  # Define the connection string
  connStr <- 'driver={SQL Server};server=DSVM2019;database=NYCTaxi_Sample;trusted_connection=true';
  
  # build classification model to predict a tip outcome
  duration <- system.time(logitObj <- rxLogit(tipped ~ passenger_count + trip_distance + trip_time_in_secs + direct_distance, data = InputDataSet))[3];
  
  # First, serialize a model to and put it into a database table
  modelbin <- as.raw(serialize(logitObj, NULL));
  
  # Create the data source. To reduce data size, add rowsPerRead=500000 to cut the dataset by half.
  ds <- RxOdbcData(table="ml_models", connectionString=connStr);
  
  # Store the model in the database
  model_name <- paste0("nyctaxi.", InputDataSet[1,]$payment_type);
  
  rxWriteObject(ds, model_name, modelbin, version = "v1", keyName = "model_name", valueName = "model_object", versionName = "model_version", overwrite = TRUE, serialize = FALSE);
} 
```
I was able to successfully run the script and a model was added to the database in a table named ***ml_models***. The table consisted of three field:  ***model_name***, ***model_version***, and ***mode_object***. Why was I able to add a model to the table in SQL Server via the ***rxWriteObject()*** function from a script in ***R Studio*** but not in the ***R Stored procedure*** used to create the partition based models in the example?

Your response is highly anticipated. Thanks in advance!

Best Regards,

Ryan Wade
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960c18da-504e-028f-fb10-6fd78ee3cf78
* Version Independent ID: 96b77abb-0309-5c32-2ed7-131de05c3f8e
* Content: [Create partition-based models in R - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/tutorials/r-tutorial-create-models-per-partition?view=sql-server-ver15#feedback)
* Content Source: [docs/machine-learning/tutorials/r-tutorial-create-models-per-partition.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/tutorials/r-tutorial-create-models-per-partition.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by WilliamAntonRohm** [comment]
@ryanwadebg -- thank you for your well-researched feedback.

@dphansen -- please look into this issue.

**Comment by dphansen** [comment]
@ryanwadebg Thank you for your feedback. I will investigate and get back to you.

**Comment by dphansen** [comment]
@ryanwadebg The tutorial uses a [loopback connection](https://docs.microsoft.com/en-us/sql/machine-learning/concepts/security?view=sql-server-ver15#implied-authentication). Therefore you need to add login for the SQLRUserGroup for implied authentication to work. For how to do that, see [Create a login for SQLRUserGroup](https://docs.microsoft.com/en-us/sql/machine-learning/security/create-a-login-for-sqlrusergroup?view=sql-server-ver15).

I will update the article to clarify this.

**Comment by ryanwadebg** [comment]
Thanks @dphansen! I would have never figured that out. I will try the fix tonight.
