### ISSUE TITLE
Unary Operators - Positive works at Azure Synapse Analytics (SQL DW) environment.

### ISSUE THREAD

**Issue by emshimon** [MicrosoftDocs/sql-docs#4673]
I checked that "Unary Operators - Positive" works at my Synapse environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf58bb04-bc5a-e10b-5532-541fa6f26a78
* Version Independent ID: b3674a1c-ddcc-1276-19a3-2ac5487fd9f7
* Content: [+ (Unary Plus) (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/unary-operators-positive?view=sql-server-ver15&viewFallbackFrom=azure-sqldw-latest)
* Content Source: [docs/t-sql/language-elements/unary-operators-positive.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/unary-operators-positive.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@emshimon, thank you for your feedback. I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@rothja -- please review [private PR 14878](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14878).

**Comment by rothja** [comment]
I added some comments to the PR. Thanks!
