### ISSUE TITLE
Find and replace - copy paste to the field fails.

### ISSUE THREAD

**Issue by Alocyte** [MicrosoftDocs/sql-docs#4675]
In the SSMS version 18.1 its possible to get into a state where you cannot copy and paste into the search field.
Cntrl-C results in a dialogue box popping up with a error message:
"Unsaved documents cannot be cut or copied to the clipboard from the Miscellaneous Files project. You must save the unsaved document(s) before cutting or copying them."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d570cd4-8dc2-f840-2693-8af14ed7da13
* Version Independent ID: 6e3d0508-081e-e4dc-3510-753320c5a660
* Content: [Find and Replace - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/scripting/find-and-replace?view=sql-server-ver15)
* Content Source: [docs/ssms/scripting/find-and-replace.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/find-and-replace.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@Alocyte -- thank you for your feedback.  Please add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @markingmyname for awareness
