### ISSUE TITLE
Missing restrictions

### ISSUE THREAD

**Issue by erikdarlingdata** [MicrosoftDocs/sql-docs#4676]
There seem to be some features missing from the restrictions section, like Temporal tables, Change Data Capture, Edge constraints, and columnstore indexes (maybe 2012 only?). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8777523f-c297-e6e8-bd86-b32d86a7e0e6
* Version Independent ID: e5cd6782-f71d-e5ac-9f87-d50dd8ccd0e7
* Content: [TRUNCATE TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/truncate-table-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/truncate-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/truncate-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@pmasl Could you please look into this issue? Thanks, Carl

**Comment by pmasl** [comment]
Yep, I'll add what's missing after verifying

**Comment by CarlRabeler** [comment]
addressed by Pedro - closing now
