### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by wjlmoraes** [MicrosoftDocs/sql-docs#4678]
Is there a release from MSODBCSQL to Ubuntu 20.04?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@wjlmoraes Not yet. Ubuntu 20.04 was just released. Look for official support for 20.04 in the next regular MSODBCSQL release cycle at the end of July. In the meantime, you can try the instructions for 19.10 (in dev/test, obviously). We've found there haven't been any breaking changes in Ubuntu releases for quite a while.

Regards,
David

**Comment by David-Engel** [comment]
#please-close
