### ISSUE TITLE
Full documentation please

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#4679]
METADATA.SECURITY_CACHE
I am having serious problems with locking in this area. Rather than me having to raise a ticket to go through the whole level1-99 diagnostics process, could you organise the people that wrote the software (And know WHAT is being locked here) to give some more information please.

METADATA: database_id = 1 SECURITY_CACHE($hash = 0x0:0x17),

If I knew what 0x17 referred to, I could continue investigating.

Thanks in advance awesome documentation team!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 456c4d6c-80da-fa98-b678-e0182f4bed6f
* Version Independent ID: 4de79b77-e30a-c0b7-35fa-10ff6f4bff05
* Content: [sys.dm_tran_locks (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-tran-locks-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-tran-locks-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-tran-locks-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@brettshearer -- Brett, thank you for your feedback.  The document states:

> METADATA.SECURITY_CACHE 
> Identified for informational purposes only. Not supported. Future compatibility is not guaranteed.


@stevestein -- Steve, can you add anything here?
