### ISSUE TITLE
noexec sql

### ISSUE THREAD

**Issue by SodioG** [MicrosoftDocs/sql-docs#4681]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 528e032a-fda8-5f25-b771-2483bbc668c8
* Version Independent ID: f90965e3-3f88-1718-cf2c-8ddae89ed80f
* Content: [SET NOEXEC (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-noexec-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/set-noexec-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-noexec-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
no feedback provided - closing this empty issue
