### ISSUE TITLE
Not available on Azure SQL?

### ISSUE THREAD

**Issue by rasghub** [MicrosoftDocs/sql-docs#4683]
Most of the other pages indicate that CONTAINS & FREETEXT can be used on Azure SQL, however, this page indicates that FREETEXT isn't available on Azure SQL. Please confirm if this is the case/correct if inaccurate.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03b79f47-7668-2a8a-a932-3ef3d1b48de9
* Version Independent ID: 83aacb08-c21b-45cb-56e7-133a87e2a487
* Content: [FREETEXT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-ca/sql/t-sql/queries/freetext-transact-sql?view=azuresqldb-current#feedback)
* Content Source: [docs/t-sql/queries/freetext-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/freetext-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @rasghub! Thanks for bringing up this issue. FREETEXT can be used with Azure SQL Database. I'll go ahead and update the doc. Thanks!

**Comment by rasghub** [comment]
Thanks for confirming.

On May 1, 2020, at 3:02 PM, Van To <notifications@github.com> wrote:

﻿

Hi @rasghub<https://github.com/rasghub>! Thanks for bringing up this issue. FREETEXT can be used with Azure SQL Database. I'll go ahead and update the doc. Thanks!
