### ISSUE TITLE
auth_scheme	is null

### ISSUE THREAD

**Issue by shanerisk** [MicrosoftDocs/sql-docs#4685]
In Azure Synapse, the auth_scheme column has null values in it.  Documentation clearly states this is not the case, please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc7ff6e-41f8-1510-898d-21f24e77efd7
* Version Independent ID: 62ebe8d7-ff47-d479-c78f-15b5d67848da
* Content: [sys.dm_pdw_exec_connections (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-pdw-exec-connections-transact-sql?view=aps-pdw-2016-au7#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-pdw-exec-connections-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-pdw-exec-connections-transact-sql.md)
* Product: **sql**
* Technology: **data-warehouse**
* GitHub Login: @ronortloff
* Microsoft Alias: **rortloff**

**Comment by ronortloff** [comment]
@nanditavalsan will take ownership of this.

**Comment by rothja** [comment]
@nanditavalsan Could you please take a look at this Azure Synapse issue? @julieMSFT @ronortloff Julie/Ron, let me know if you have any insight into this question about the documentation versus the behavior of auth_scheme for [sys.dm_pdw_exec_connections (Transact-SQL)](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-pdw-exec-connections-transact-sql) in Azure Synapse.
