### ISSUE TITLE
Nice Job

### ISSUE THREAD

**Issue by DMiradakis** [MicrosoftDocs/sql-docs#4686]
Super helpful page! Just wanted to say thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 182fddd0-1d28-22c5-3e0b-371d24f805e8
* Version Independent ID: 81766aa4-84a9-884f-16ee-dfc1d1451829
* Content: [sp_settriggerorder (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-settriggerorder-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-settriggerorder-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-settriggerorder-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@DMiradakis -- Daniel, you're very welcome!

cc @stevestein as the author
