### ISSUE TITLE
Does not work after columns have been created

### ISSUE THREAD

**Issue by chiques** [MicrosoftDocs/sql-docs#4688]
Dragging it as described does not allow it to be saved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76507156-d85c-e9f0-a214-3a9f1eb0f1fc
* Version Independent ID: 045c9c15-fbf9-abf9-c48a-904733e7ab42
* Content: [Change Column Order in a Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/change-column-order-in-a-table?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/tables/change-column-order-in-a-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/change-column-order-in-a-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@chiques -- thank you for your product-related feedback.  Please add it here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
