### ISSUE TITLE
MS Docs reference to the VIRTUAL master database

### ISSUE THREAD

**Issue by JpsKaGitHub** [MicrosoftDocs/sql-docs#4689]
Specifically in the section below: (what is meant by virtual master database? No *.MDF and *.LDF files as in the case of physical databases?

Special Roles for SQL Database and SQL Data Warehouse
These database roles exist only in the virtual master database. Their permissions are restricted to actions performed in master. Only database users in master can be added to these roles. Logins cannot be added to these roles, but users can be created based on logins and then those users can be added to the roles. Contained database users in master can also be added to these roles. However, contained database users added to the dbmanager role in master cannot be used to create new databases.

TABLE 2
Role name	Description
dbmanager	Can create and delete databases. A member of the dbmanager role that creates a database, becomes the owner of that database which allows that user to connect to that database as the dbo user. The dbo user has all database permissions in the database. Members of the dbmanager role do not necessarily have permission to access databases that they do not own.
loginmanager	Can create and delete logins in the virtual master database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d95c4e-dfbb-ec5a-7df9-8a8d33be5b83
* Version Independent ID: a35a9368-4e76-6d55-7e90-34e925b34dd7
* Content: [Database-Level Roles - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/authentication-access/database-level-roles.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/database-level-roles.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @JpsKaGitHub - It's referring to the master database in the logical Azure SQL Database server. Does that answer your question?
