### ISSUE TITLE
Add or remove role Active Directory members?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/sql-docs#4691]
How do we ADD MEMBER for Active Directory users? 
Example: 
- New AD User created with:

```
CREATE USER [bob@bob.com] FROM EXTERNAL PROVIDER
WITH SCHEMA = dbo
```
Now trying to add this user to `testRole` using:
```
ALTER ROLE testRole ADD MEMBER 'bob@bob.com`
```
Does not work. Please add an AD example. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08b8d0a0-540c-51b9-0862-61cdb1f93c14
* Version Independent ID: 15f49975-f408-122c-4ece-b8b5deb60076
* Content: [ALTER ROLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-role-transact-sql?view=sql-server-ver15#examples)
* Content Source: [docs/t-sql/statements/alter-role-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-role-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by SeaDude** [comment]
Found the answer. Needed to use: `ALTER ROLE testRole ADD MEMBER [bob@bob.com]`
Please consider updating the docs here with this example. Found answer on [StackOverflow](https://stackoverflow.com/questions/51642423/azure-sql-database-user-not-inheriting-role-permissions).

**Comment by VanMSFT** [comment]
Hi @SeaDude! Thanks for submitting this issue. Can you please clarify the error that you were experiencing, and the fix?

**Comment by SeaDude** [comment]
Hi @VanMSFT . I'm not in position to reply the error right now, but the fix was to go from 
- `ADD MEMBER 'bob@bob.com'` to 
- `ADD MEMBER [bob@bob.com]`

**Comment by dirkslab** [comment]
thanks @SeaDude !
