### ISSUE TITLE
Trouble installing sqlmlutils_0.7.1

### ISSUE THREAD

**Issue by ryanwadebg** [MicrosoftDocs/sql-docs#4692]
As stated in a previous issue the RODBC package has been removed from CRAN. I installed an archive version using the following code:

```
library(devtools)
install_url("https://cran.r-project.org/src/contrib/Archive/RODBCext/RODBCext_0.3.2.tar.gz")
```

That appeared to work but I then ran into problems when I ran the second piece of code in the command prompt:

```
R CMD INSTALL %UserProfile%\Documents\sqlmlutils_0.7.1.zip
```
The code appeared to run successfully but when I tried to load the package I got the following error:
```
Error: package or namespace load failed for ‘sqlmlutils’:
 package ‘sqlmlutils’ was installed before R 4.0.0: please re-install it
```
I don't know exactly what this error mean. I was originally running R 3.6.2 in the Windows 2019 Data Science Virtual Machine but updated to 4.0.0 because I was having issues communicating with CRAN. Do I need to use a &lt;4.0.0 version of CRAN? There is a sqlmlutils folder in my C:\Program Files\R\R-4.0.0\library directory so it appears it was installed successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce36aa85-fd24-74a6-1e01-20c892f92a9f
* Version Independent ID: 08b9fb79-7117-98fc-5d2c-7a42a6c49a04
* Content: [Install new R packages - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/package-management/install-additional-r-packages-on-sql-server?view=sql-server-ver15)
* Content Source: [docs/machine-learning/package-management/install-additional-r-packages-on-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/package-management/install-additional-r-packages-on-sql-server.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by ryanwadebg** [comment]
FYI, I was able to install sqlmlutils using R 3.6.3 using the above method but not R 3.6.2 or R 4.0.0.

**Comment by WilliamAntonRohm** [comment]
@ryanwadebg -- thank you for your feedback.

@garyericson -- please look into this issue -- related to #4690.

**Comment by garyericson** [comment]
@ryanwadebg - I'm not sure what's happening. Can you try again but this time install RODBCext using the updated instructions mentioned in GitHub Issue [4690](https://github.com/MicrosoftDocs/sql-docs/issues/4690#issuecomment-627017806)?

**Comment by dphansen** [comment]
@ryanwadebg I will close this GitHub issue as we haven't heard from you since it was opened. If you have tried @garyericson's suggestion above and still have an issue, please open a new GitHub issue. Thank you.
