### ISSUE TITLE
Left Hand Rule is mentioned but is not defined.

### ISSUE THREAD

**Issue by bdcoder2** [MicrosoftDocs/sql-docs#4693]
The page states: "The interior of the polygon in an ellipsoidal system is defined by the left-hand rule." -- but offers no reference link for the Left Hand Rule.

I would recommend something simple, such as the following:

The area where a search occurs is selected as if looking over ones left shoulder, while walking around the area, for example:

- When constructing a polygon in CLOCKWISE order and looking to your left, everything outside of the polygon will be selected; in effect you are creating a "hole" within the selected area.

- When constructing the polygon in COUNTER-CLOCKWISE order and looking to your left, everything INSIDE the polygon will be selected; representing the search area.

In summary, if constructing a closed polygon (search area) for use with SQL, do so in a COUNTER-CLOCKWISE  fashion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2797e2b3-62ca-d4f9-c36f-31d77358deda
* Version Independent ID: 0e1e4a3a-2bcb-97e1-94ac-98be1bfbda97
* Content: [Spatial Data Types Overview - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-data-types-overview?view=sql-server-ver15#differences)
* Content Source: [docs/relational-databases/spatial/spatial-data-types-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/spatial/spatial-data-types-overview.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@bdcoder2 -- thank you for your feedback and suggestions.

@MladjoA -- please look into this issue.

**Comment by MladjoA** [comment]
Thanks for the suggestion @bdcoder2. The pull request is on its way.

**Comment by MladjoA** [comment]
#please-close
