### ISSUE TITLE
Code examples for a point within a bounds ...

### ISSUE THREAD

**Issue by bdcoder2** [MicrosoftDocs/sql-docs#4694]
I know this might be a repeat of the previously closed question regarding difference between STContains and STWithin - but I have yet to find an answer.

Please see my StackOverflow post at:
https://stackoverflow.com/questions/61553745/ms-sql-geography-testing-if-a-point-is-within-a-bounds-what-does-stwithin-do

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be221aa-48df-e9ab-fc2d-65d4f7ec56ce
* Version Independent ID: b81cfb49-c58a-97bd-5e85-224e567a633e
* Content: [STContains  (geography Data Type) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geography/stcontains-geography-data-type?view=sql-server-ver15)
* Content Source: [docs/t-sql/spatial-geography/stcontains-geography-data-type.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/spatial-geography/stcontains-geography-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by MladjoA** [comment]
@bdcoder2 , STContains and STWithin are analogous spatial relation checks in terms of a.STContains(b) returning always the same result as b.STWithin(a). In fact, only one of them is actually implemented in SQL Spatial - calling the latter one is internally being "swapped" to a call of a former one.

**Comment by bdcoder2** [comment]
@MladjoA - so it is true: a.STContains(b) == b.STWithin(a)    This should be mentioned in the docs (if not already) -- Thanks!!
