### ISSUE TITLE
Recursion in WITH statements is not supported on Azure Synapse

### ISSUE THREAD

**Issue by bhuesemann** [MicrosoftDocs/sql-docs#4695]
Example: 
```
WITH rowgen AS (
  SELECT 0 as Number
  UNION ALL
  SELECT Number+1
  FROM rowgen
  WHERE Number <99 
)
select * from rowgen;
``` 
Leads to SQL Error [100084] [S0001]: Recursive common table expressions are not supported in this version.

The documentation states that this should be possible:
"A common table expression can include references to itself. This is referred to as a recursive common table expression."
[Doc](https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver15)

**Comment by WilliamAntonRohm** [comment]
@bhuesemann -- thank you for your feedback. 

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
Hi @julieMSFT - Do you mind taking a look at this? Thanks!

#reassign:julieMSFT

**Comment by julieMSFT** [comment]
@bhuesemann Hello and thank you for contacting Microsoft. I am sorry for the delay. I am am looking into your issue.

**Comment by bhuesemann** [comment]
@julieMSFT Thanks for addressing the issue. Happy to help if needed. The documentation issue is one (minor) thing, but it would also be great to know if this is meant to be added. Although my example is of course synthetic, it is a common use case to query relational graphs or hierachies using Sql with this pattern.

**Comment by julieMSFT** [comment]
@bhuesemann Hi, recursive CTEs are not supported and this is mentioned in the doc, https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=azure-sqldw-latest#features-and-limitations-of-common-table-expressions-in--and-. If you would like to request an enhancement to the product you can do so at https://feedback.azure.com/forums/307516-azure-synapse-analytics.  I will proceed with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close

**Comment by bhuesemann** [comment]
Alright, thanks for the clarification. I've not seen this limitation description and section later on the page. I will add a feature request or vote if I find an existing one. Thanks!

**Comment by highqualitytorquewrench** [comment]
> Alright, thanks for the clarification. I've not seen this limitation description and section later on the page. I will add a feature request or vote if I find an existing one. Thanks!

Did this issue ever get resolved?  I'm having the same issue now in 2022...`The query references an object that is not supported in distributed processing mode.`

**Comment by VanMSFT** [comment]
@WilliamDAssafMSFT for awareness

**Comment by tksunw** [comment]
I'm having the same issue.  Investigating Azure SQL Vulnerability Scan results in the Portal goes to a Microsoft Defender pane that lists scan findings.  In my case, Rule 'VA2130' is a finding for us, and Microsoft provides this query as the query to check the finding:
```
WITH UsersAndRoles (principal_name, sid, type) AS 
(
    SELECT DISTINCT prin.name, prin.sid, prin.type 
    FROM sys.database_principals prin 
        INNER JOIN ( SELECT *
                     FROM sys.database_permissions
                     WHERE type = 'CO' 
                        AND state IN ('G', 'W')
        ) perm 
            ON perm.grantee_principal_id = prin.principal_id 
        WHERE prin.type IN ('S', 'X', 'R', 'E', 'G')
    UNION ALL
    SELECT 
        user_name(rls.member_principal_id), prin.sid, prin.type
    FROM 
        UsersAndRoles cte
        INNER JOIN sys.database_role_members rls
            ON user_name(rls.role_principal_id) = cte.principal_name
        INNER JOIN sys.database_principals prin
            ON rls.member_principal_id = prin.principal_id
        WHERE cte.type = 'R'
),
Users (database_user, sid) AS
(
    SELECT principal_name, sid
    FROM UsersAndRoles
    WHERE type IN ('S', 'X', 'E', 'G')
        AND principal_name != 'dbo'
)
SELECT DISTINCT database_user AS [User], sid AS [SID]
    FROM Users
    WHERE sid != 0x01
```
The Azure portal is able to return results from a DataWarehouse, so it seems the portal doesn't actually use the provided query, and instead uses a different query that's not provided.  We can always click through the portal to check/set/update our baseline, but it would be nice if this query was supported by the DataWarehouse, or if Microsoft provided a working query for DW products.  Other Rules have working queries that differ between the Az SQL and Az SQL DW editions.

To replicate the issue, in the Azure Portal, go to any Dedicated SQL Pool (formerly SQL DW), and in the left menu, under Security, select Microsoft Defender for Cloud.  On that page, at the bottom will be "View additional findings in Vulnerability Assessment".  Click the link.  You'll see the Query in the Query Box in "Query and results".

<img width="831" alt="dw-busted-query-VA2130" src="https://user-images.githubusercontent.com/497321/207461794-6e14235e-9da7-452b-aba0-13e6c59bdd5c.png">
