### ISSUE TITLE
Missing Error: Msg 35392, Level 16, State 1

### ISSUE THREAD

**Issue by tgilmour** [MicrosoftDocs/sql-docs#4696]
The error message is:
"The statement failed because column '' on table '' is a computed column. Nonclustered index with computed column as key or included column cannot be created on a table that has a clustered columnstore index."

Version: Microsoft SQL Server 2019 (RTM-CU4) (KB4548597) - 15.0.4033.1 (X64) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5973cd79-d024-6670-8b9f-d02d9824e8ec
* Version Independent ID: 9c7e4cd4-9bd7-16ad-83c0-9c114e5eec46
* Content: [Database engine events and errors - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-events-and-errors?view=sql-server-ver15#errors-31000-to-41400)
* Content Source: [docs/relational-databases/errors-events/database-engine-events-and-errors.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/errors-events/database-engine-events-and-errors.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@tgilmour -- thank you for your product feedback.  Please add it here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

**Comment by MashaMSFT** [comment]
Hi @tgilmour , thanks for your feedback and for bringing this to our attention! Actually, this list of errors is not meant to be exhaustive, there's a number of errors that are not listed here. 

You can use this query to find all of the errors:

```sql
SELECT message_id AS Error, severity AS Severity,  
[Event Logged] = CASE is_event_logged WHEN 0 THEN 'No' ELSE 'Yes' END,
text AS [Description]
FROM sys.messages
WHERE language_id = <desired language, such as 1033 for US English>
ORDER BY message_id
```

Thanks!
Masha from the SQL Docs team
