### ISSUE TITLE
Remarks appear incorrect.

### ISSUE THREAD

**Issue by rjrjack** [MicrosoftDocs/sql-docs#4698]
Inthe Remarks section:
  1) It states 'If the key is open in the current session the statement will fail' however I have no problem opening a symmetric key and then immediately dropping the key, as below:
open symmetric key CreditCards_key11 decryption by certificate SalesCertificate 
drop symmetric key CreditCards_key11

2) It mentions 'If the asymmetric key is mapped to....' but page is about symmetric keys not asymmetric keys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79a06920-2ae9-2774-ed77-2bc5e7d805e0
* Version Independent ID: a234c1d1-392d-c1e2-c1fc-5bf830350e58
* Content: [DROP SYMMETRIC KEY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-symmetric-key-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/drop-symmetric-key-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/drop-symmetric-key-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @rjrjack - Thanks for submitting this issue. Let me check on this and get back to you.

**Comment by VanMSFT** [comment]
Verified that an open Symmetric Key can be dropped. Checking with the Product Team.

**Comment by VanMSFT** [comment]
Internal discussion going on

**Comment by VanMSFT** [comment]
Since we verified that the key can be dropped while open, I made the change to remove the remark from the documentation.

Thanks, and sorry for the delay, @rjrjack! We appreciate your feedback and testing!
