### ISSUE TITLE
Partition switch image is distorted

### ISSUE THREAD

**Issue by devudu** [MicrosoftDocs/sql-docs#4700]
Text in the image is not redable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae143071-a443-cd21-1da4-0f7897e31575
* Version Independent ID: 2b0e6251-0690-6d8f-b7ed-f2fdb6e74d72
* Content: [Application pattern - partitioning memory-optimized tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/application-pattern-for-partitioning-memory-optimized-tables?view=sql-server-ver15)
* Content Source: [docs/relational-databases/in-memory-oltp/application-pattern-for-partitioning-memory-optimized-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/application-pattern-for-partitioning-memory-optimized-tables.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
@devudu Hello, to fix this Issue #4700, I have created and merged PR #14820, in the private sister repo. The changes to the article's text are many. The crummy image that you cited is no longer needed in the article: it was redundant to a bullet list of steps. The PR clarifies the steps, and converts them into the numeric bullet list they should have been in.

So, thank you for bringing this bad image to our attention.
I am now Closing this Issue, as fixed.

We hope to hear from you again.

CC: @rothja
