### ISSUE TITLE
Update 'Unique constraints' page to say 'Unique and Check constraints' on the navigation pane.

### ISSUE THREAD

**Issue by zakiirjuman** [MicrosoftDocs/sql-docs#4701]
I was trying to find more information on Check Constriants and found it on this page. While it's title is correct, "Unique Constraints and Check Constraints" it is not properly displayed in the navigation bar which only says "Unique Constraints".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3709c36d-5f11-41b8-0926-e4549bd2b78e
* Version Independent ID: cff4179f-03c9-bba8-b87b-a4e13fb3e919
* Content: [Unique Constraints and Check Constraints - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/unique-constraints-and-check-constraints?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/tables/unique-constraints-and-check-constraints.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/unique-constraints-and-check-constraints.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@zakiirjuman -- Zakiir, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please review [private PR 14879](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14879).
