### ISSUE TITLE
Missing -d in docs for unzipping package in macos docs

### ISSUE THREAD

**Issue by jameseg** [MicrosoftDocs/sql-docs#4705]
I wasn't able to unzip the file downloaded to the ~/<dir> unless I put a -d in front of the directory

**Comment by WilliamAntonRohm** [comment]
@jameseg -- thank you for your feedback.  Please clarify which docs.microsoft.com article you are reading.

**Comment by jameseg** [comment]
@WilliamAntonRohm sorry about that, the sqlpackage.exe docs for Mac OS

**Comment by WilliamAntonRohm** [comment]
@jameseg -- please provide a specific article -- there are a lot of those  :^)

**Comment by jameseg** [comment]
[https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-ver15#get-sqlpackage-net-core-for-macos](url)

Mac

**Comment by WilliamAntonRohm** [comment]
@jameseg -- thank you for specifying!  I have updated the documentation and it should be live by tomorrow.
