### ISSUE TITLE
Beginning with SP1 of SQL Server 2016

### ISSUE THREAD

**Issue by rcfoyn** [MicrosoftDocs/sql-docs#4710]
It should be specified that columnstore index begins with SP1 of SQL Server 2016 (13.0.4001). Currently, this page says 2016 (13.x) only, which is not entirely accurate. See https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2016, which reads "Applies to SQL Server 2016 (13.x) SP1".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 571bf244-1472-286b-d1a8-7db2e54f40a2
* Version Independent ID: bccbd120-47f3-78b7-0cd6-7d4198ea3604
* Content: [Columnstore indexes: Overview - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-overview?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/indexes/columnstore-indexes-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/columnstore-indexes-overview.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@rcfoyn -- thank you for your feedback.  I am looking into this article.
