### ISSUE TITLE
No indication of column types that it can apply to

### ISSUE THREAD

**Issue by JamesHorsley** [MicrosoftDocs/sql-docs#4712]
IDENTITY can only apply to certain types - these should be listed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33014f93-e2e9-f0e7-804b-e50493a32627
* Version Independent ID: 38498f73-63c2-4557-bf4b-c20923b45656
* Content: [IDENTITY (Property) (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-table-transact-sql-identity-property.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-transact-sql-identity-property.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @JamesHorsley - Can you please elaborate?

**Comment by VanMSFT** [comment]
Hi @JamesHorsley - Thanks for your inquiry. Since we have not received further response on this issue, we will close it for now.
