### ISSUE TITLE
Add defualt value SSIS

### ISSUE THREAD

**Issue by HASSEN-MEDDEB-ATOS** [MicrosoftDocs/sql-docs#4713]
Hello,

I want to set default value to column where it's null using SSIS

![image](https://user-images.githubusercontent.com/58071802/81103486-629e9f00-8f11-11ea-91bb-b389cb040ac3.png)

i have added script 

`````````
 public override void Input0_ProcessInputRow(Input0Buffer Row)
    {
        /*
         * Add your code here
         */
                
        decimal PMR_Value = 1000.0000000000m;

        if (Row.idPMR_IsNull)
        {
            Row.idPMR = Math.Truncate(PMR_Value);
        }
        else
        {
            Row.DirectRowToSortie0();

        }
    }
``````````

I get this error : 142/5000
idPMR 'is not valid - The value' 'is not valid according to its data type' Integer '- The string' 'is not a valid Integer value

I have tried
Convert.TOInt32 , toInt64 , to Int12 still same error
Cordially

**Comment by WilliamAntonRohm** [comment]
@HASSEN-MEDDEB-ATOS -- thank you for your feedback.  Please provide additional information on which docs.microsoft.com article you are reading, and on your overall task.
