### ISSUE TITLE
Describe what maintenance mode means for this particular feature

### ISSUE THREAD

**Issue by Prof-hu** [MicrosoftDocs/sql-docs#4715]
Please add information on why and since when this feature is in maintenance mode and what is the successor of this feature to be used instead of this one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49bf8822-4851-2e5a-69dc-52ae05c7e00b
* Version Independent ID: 99be3989-8c8d-603d-3340-285edae63f18
* Content: [default trace enabled Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/default-trace-enabled-server-configuration-option?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/default-trace-enabled-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/default-trace-enabled-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@Prof-hu -- thank you for your feedback.  It appears to have been in maintenance mode for several years. The successor is [Extended events](https://docs.microsoft.com/en-us/sql/relational-databases/extended-events/extended-events).


I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
