### ISSUE TITLE
Cannot select additional files

### ISSUE THREAD

**Issue by russrayner** [MicrosoftDocs/sql-docs#4718]
The dialog in SSMS used to show, after selecting the MDF file, all other associated database files, even if those files cannot be found.  Re-mapping of actual file location was then possible.

This is no longer possible, so the UI cannot be used in instances where the data files have been moved or renamed, which is really frustrating.  

I'm not sure why this functionality was removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f754e5a-c07f-943b-5184-6a8eb8a24c26
* Version Independent ID: cedc9b77-16de-ae53-9cec-d10b3dfb1ff1
* Content: [Attach a Database - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/attach-a-database?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/databases/attach-a-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/attach-a-database.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@russrayner -- thank you for your feedback.  Please add it here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
