### ISSUE TITLE
Lesson1-7: Add and configure the OLE DB destination

### ISSUE THREAD

**Issue by bestmbaman** [MicrosoftDocs/sql-docs#4720]
Hello,
The following command suggests to create a new table as **NewFactCurrencyRate**, but I get an error that this table already exists in database **AdventureWorksDW2012**.

- https://docs.microsoft.com/sql/integration-services/lesson-1-7-adding-and-configuring-the-ole-db-destination?view=sql-server-ver15

Solution: Either we should first drop the table first and add it later, or select a new name instead!
Please fix it to avoid further frustrations!

**Comment by WilliamAntonRohm** [comment]
@bestmbaman -- thank you for your feedback.

@chugugrace -- please look into this issue.

**Comment by MightyPen** [comment]
I am Closing this Issue #4720 now, as Fixed by private repo PR 17096.
The fix should be live on Docs before the end of September 2020.

@bestmbaman Thank you for bring this problem to our attention.
