### ISSUE TITLE
"When to Use a Heap" section has sentence that's never finished.

### ISSUE THREAD

**Issue by chlafreniere** [MicrosoftDocs/sql-docs#4722]
In the "When to Use a Heap" section, I see the following: "Heaps are also used for" and the sentence is never ended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba8c976f-591a-4bf6-c8cd-9e2ec0cbe022
* Version Independent ID: 576ef9af-578b-e5b5-b230-727af80dec04
* Content: [Heaps (Tables without Clustered Indexes) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/heaps-tables-without-clustered-indexes?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/indexes/heaps-tables-without-clustered-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/heaps-tables-without-clustered-indexes.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by toddkitta** [comment]
![suspense](https://media2.giphy.com/media/y0SJVYxf90J1u/source.gif)

**Comment by WilliamAntonRohm** [comment]
@chlafreniere -- Chris, thank you for your feedback.

@toddkitta -- thank you as well.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by pmasl** [comment]
Apologies for this typo. I have corrected with the missing information and will be onliune in a few hours.
