### ISSUE TITLE
“Inserting data using a CDATA section” has incorrect formatting

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/sql-docs#4723]
The documentation tries to say that `<` is inserted as `&lt;` but it instead says that `<` is inserted as `<`.

The documentation’s example of the output XML also is invalid. It says the result is:

```xml
<Root>
<ProductDescription ProductID="1" ProductName="Road Bike">
<Features> <notxml> as text </notxml> or cdata </Features>
</ProductDescription>
</Root>
```

when the actual result is

```xml
<Root>
  <ProductDescription ProductID="1" ProductName="Road Bike">
    <Features> &lt;notxml&gt; as text &lt;/notxml&gt; or cdata </Features>
  </ProductDescription>
</Root>
```

Note that to get this result, the query I had to use was the following because I couldn’t figure out how to get the XPath to let me construct `<![CDATA[…]]>`. I am using SQL Server 11. Is support for direct construction of CDATA in expressions a relatively new feature?

```sql
DECLARE @myDoc XML = '<Root>
    <ProductDescription ProductID="1" ProductName="Road Bike">
        <Features/>
    </ProductDescription>
</Root>';
SELECT @myDoc;
DECLARE @x XML = N'<![CDATA[ <notxml> as text </notxml> or cdata ]]>';
SET @myDoc.modify('
insert sql:variable(''@x'')
into  (/Root/ProductDescription/Features)[1]
');
SELECT @myDoc;
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 297ecdb3-da6e-836b-a463-3904511053d1
* Version Independent ID: d44faa63-e260-33b3-8313-763d36aa4b29
* Content: [insert (XML DML) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/xml/insert-xml-dml?view=sql-server-2017#f-inserting-data-using-a-cdata-section)
* Content Source: [docs/t-sql/xml/insert-xml-dml.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/xml/insert-xml-dml.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by WilliamAntonRohm** [comment]
@binki -- Nathan, thank you for your detailed feedback.  I am looking into this article.

**Comment by MightyPen** [comment]
I reviewed private repo PR 14968 .
G

**Comment by binki** [comment]
When will the changes be reflected in this repository? It still looks incorrect to me.

**Comment by MightyPen** [comment]
@binki We need to give the system a couple business days.  As of now, the PR was merged less than two business days ago.  Thanks.
