### ISSUE TITLE
Unable to access the download page

### ISSUE THREAD

**Issue by hkonomi1** [MicrosoftDocs/sql-docs#4724]
There is a certificate error with the download page for SSMS. Currently Chrome and Edge are not allowing me to reach it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by WilliamAntonRohm** [comment]
@hkonomi1 -- thank you for your feedback.  It appears to be working now.  Please try again.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by hkonomi1** [comment]
It is not working, still the same error

**Comment by markingmyname** [comment]
Hi, @hkonomi1,

I'm not getting an issue either.

I know this is easier said than done, but any chance you can try on a different machine or clear the cache from your browsers?

**Comment by hkonomi1** [comment]
This is the error I get with multiple browsers when clicking the download
link:
[image: image.png]

**Comment by hkonomi1** [comment]
I am in Canada

**Comment by markingmyname** [comment]
can you try downloading one of the different languages and see if that works for you? - https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#available-languages

please let us know.

thank you.

**Comment by UnimplementedTrap** [comment]
Doesn't work for me either.
I have a fresh install of Server 2019 and am installing SQL Server 2017.
The Install SQL Server Management Tools link from the installer takes you to
https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?redirectedfrom=MSDN&view=sql-server-ver15
The Download SQL Server Management Studio (SSMS) link takes you to https://aka.ms/ssmsfullsetup
which fails on IE 11, the default browser for Server 2019

**Comment by UnimplementedTrap** [comment]
The download (https://aka.ms/ssmsfullsetup) worked for me in chrome.

**Comment by markingmyname** [comment]
@hkonomi1,

Are you still experiencing this issue?

@UnimplementedTrap,

Can I ask what error you are getting, please? 

This is important if you can't download it.

**Comment by UnimplementedTrap** [comment]
I have a different error than before.
From the SQL Server 2017 installer I clicked "Install SQL Server Management Tools"
IE-11 Opens up and gets the following error.

![image](https://user-images.githubusercontent.com/49542265/83469986-a8825080-a446-11ea-9ce3-4724e45c3c7a.png)

Chrome opens the page just fine.

As a test I added go.microsoft.com to the trusted sites under Internet Options -> Security, then I set the Security levels to low for the trusted sites and I got the same error.

**Comment by markingmyname** [comment]
@UnimplementedTrap 

Can you verify on the server under IE Enhanced security is set to OFF?

![image](https://user-images.githubusercontent.com/22989000/83470973-129bf500-a449-11ea-9300-11aac484df24.png)

**Comment by markingmyname** [comment]
if that is not set you cannot download on a Windows Server via IE.

**Comment by UnimplementedTrap** [comment]
It is Off.
When I first commented https://github.com/MicrosoftDocs/sql-docs/issues/4724#issuecomment-635514876
Using IE-11, I could load the "Download SQL Server Management Studio (SSMS)" page, I just couldn't connect to https://aka.ms/ssmsfullsetup

Now I can't even load the "Download SQL Server Management Studio (SSMS)".

I have downloaded/installed everything I need, so I don't need any help.  I am happy to answer any questions if it helps you.

**Comment by markingmyname** [comment]
@UnimplementedTrap,

Thank you for clarifying and bringing this to our attention.

We will continue to investigate this situation with SSMS being downloaded via IE 11 on WS 2019.

**Comment by markingmyname** [comment]
@hkonomi1,

Since I cannot repro the issue, please open a support ticket for further assistance.

Please visit one of the following pages depending on your product or service.

[On Prem users](https://support.microsoft.com/en-us/supportforbusiness/productselection)
[SQL on Azure](https://ms.portal.azure.com/#home)
[Services Hub (Unified/premier customers)](https://serviceshub.microsoft.com/support/create/097a91e3-084a-46a8-b385-d5b07ffedcfe)
---------------------------------

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
