### ISSUE TITLE
Table variable SQl Server docs typo grammatical error

### ISSUE THREAD

**Issue by vboina** [MicrosoftDocs/sql-docs#4725]
Wrong :
This variable is the function, stored procedure, or batch that it's declared in.

Correct : This variable can be used in the function, stored procedure, or batch that it's declared in.
Link : https://docs.microsoft.com/en-us/sql/t-sql/data-types/table-transact-sql

**Comment by WilliamAntonRohm** [comment]
@vboina -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review [private PR 14969](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14969).
