### ISSUE TITLE
The list of values for desired_state is incomplete

### ISSUE THREAD

**Issue by rsocol** [MicrosoftDocs/sql-docs#4726]
The list of values for the desired_state and desired_state_desc column is incomplete. Besides 0=OFF and 1=ON, we can also find 2=DEFAULT in these columns.

The documentation page https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options?view=sql-server-ver15 should also be updated, because we can use "ALTER DATABASE AdventureWorks2017 SET AUTOMATIC_TUNING (FORCE_LAST_GOOD_PLAN=DEFAULT)".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc1cf143-365e-7075-ef98-04452fbbd53a
* Version Independent ID: e05b9812-f457-5e6a-2527-5911f935eeb7
* Content: [sys.database_automatic_tuning_options (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-automatic-tuning-options-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-catalog-views/sys-database-automatic-tuning-options-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-database-automatic-tuning-options-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by rsocol** [comment]
The values for the reason_desc column also seem to be incomplete, because I see 2=AUTO_CONFIGURED in a Managed Instance database and in another SQL Server 2019 database.

**Comment by WilliamAntonRohm** [comment]
@rsocol -- Rasvan, thank you for clarifying further.

@jovanpop-msft -- Jovan, please look into this issue.

**Comment by rothja** [comment]
@jovanpop-msft Jovan, can you please advise what we shoul change in the sys.database_automatic_tuning_options article? Note that @rsocol added additional suggestions in the comments. @rsocol Sorry for the long delay. If you know the values that you think should be added and where, you can click the "Edit" link on the article to make the change submissions directly for our approval. Thank you!

**Comment by rwestMSFT** [comment]
#reassign:@rwestMSFT

**Comment by rwestMSFT** [comment]
@rsocol Thank you for your patience. I will update the documentation in the near future. Note that `DEFAULT` does not apply to on-premises SQL Server, but Azure SQL only. We will not be documenting `AUTO_CONFIGURED`.

**Comment by rsocol** [comment]
@rwestMSFT It looks like `DEFAULT` also applies to on-premises SQL Server, see attached screenshot.

![image](https://user-images.githubusercontent.com/29515341/182434068-e6f78a59-92c6-4019-bb27-004ee579795a.png)

**Comment by rwestMSFT** [comment]
@rsocol Thanks, the information I received may have been out of date. Your continued feedback is appreciated.

**Comment by rwestMSFT** [comment]
Following up to say there's no news yet.

**Comment by rwestMSFT** [comment]
@rsocol We will be putting together an internal PR to update the article. Thank you for your patience.

For your reference, this is how DEFAULT is implemented on each product.

|Version|DEFAULT|
|---|---|
|SQL Server|`OFF`|
|Azure SQL Managed Instance|`ON`|
|Azure SQL Database|`ON`, but can be affected by `INHERITED_FROM_SERVER`|
