### ISSUE TITLE
This does not appy to Azure Synapse

### ISSUE THREAD

**Issue by Robert-Kostecki** [MicrosoftDocs/sql-docs#4727]
You cannot use neither sp_rename nor SQL Server Management Studio to rename views in Azure Synapse Analytics. Neither method is supported. 

Tested using SSMS 18.5 & Synapse @@version: Microsoft Azure SQL Data Warehouse - 10.0.11038.0 Apr 21 2020 19:42:42 Copyright (c) Microsoft Corporation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f659019d-11c8-df01-08ce-cf4815e15fc9
* Version Independent ID: 2152590c-dd29-d1f4-490e-62d05718b1a2
* Content: [Rename Views - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/views/rename-views?view=sql-server-ver15)
* Content Source: [docs/relational-databases/views/rename-views.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/views/rename-views.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@Robert-Kostecki -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please review [private PR 14970](https://github.com/MicrosoftDocs/sql-docs-pr/pull/14970).
