### ISSUE TITLE
New SERVERPROPERTY value : MachineOS

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#4730]
I would like to suggest that this command have a new command to return information on the Operating System.  It will already return the name of the host [ComputerNamePhysicalNetBIOS], the name of the logical server (in the case of a cluster node) [MachineName], it should also return information about the Operating System that hosts the SQL instance (e.g. Edition and version number).  
It would be helpful if Microsoft maintained a list of those Windows Operating systems versions that this could be matched to - including those that may no longer be supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddfe68a0-2711-8521-2b95-562c6d2c6f58
* Version Independent ID: 2636e412-39db-93a6-d07a-0f6fc3fa33d6
* Content: [SERVERPROPERTY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/serverproperty-transact-sql?view=sql-server-ver15&source=docs)
* Content Source: [docs/t-sql/functions/serverproperty-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/serverproperty-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @LindaLF! Thanks for the suggestion on the product. We appreciate it. Please submit your feedback using the product feedback button:

![image](https://user-images.githubusercontent.com/40007119/81335760-f92ba700-905c-11ea-80f7-960171f55e8f.png)
