### ISSUE TITLE
IS_MEMBER *does* work for Azure AD groups.

### ISSUE THREAD

**Issue by toddkitta** [MicrosoftDocs/sql-docs#4732]
The [docs](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/is-member-transact-sql.md) state that IS_MEMBER does not work for AAD groups. However, I have been able to get this to work.

You have to add any group you want to check for membership as a contained user and then IS_MEMBER works as expected. Am I missing something?

**Comment by WilliamAntonRohm** [comment]
@toddkitta -- thank you for your feedback.  You appear to be on the right track.

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
Hi @GithubMirek - Is this something you can help check? Thanks!

https://docs.microsoft.com/en-us/sql/t-sql/functions/is-member-transact-sql?view=sql-server-ver15

#reassign:GithubMirek

**Comment by GithubMirek** [comment]
The AAD/SQL product group is in the process of completing and testing this functionality. It should be publicly available toward the end of Q1 2021 (CY).

**Comment by PRMerger9** [comment]
to is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by VanMSFT** [comment]
Thanks @GithubMirek!

@toddkitta - Thanks for bringing this issue up. We will track this internally and make the necessary doc changes as needed. I will close this issue for now, but please feel free to let us know if you have any concerns.
