### ISSUE TITLE
EXECUTE AS *does* work in Synapse Analytics/DW

### ISSUE THREAD

**Issue by toddkitta** [MicrosoftDocs/sql-docs#4733]
[Docs state](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/row-level-security.md) EXECUTE AS does not work in Synapse/DW. However, I have found that it does. Before I submitted a PR, I wanted to understand if there are perhaps any caveats I am missing. Thoughts?

The offending sentence is: "Azure SQL Data Warehouse doesn't support EXECUTE AS USER, so log in as the appropriate user to test the above behavior."

**Comment by WilliamAntonRohm** [comment]
@toddkitta -- thank you for your interesting question.  

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
Hi @julieMSFT - Can you please take a look at this? Thanks!

#reassign:julieMSFT

**Comment by julieMSFT** [comment]
@toddkitta Hello and thank you for contacting Microsoft. I am sorry for the delay in response. I am looking into your issue.

**Comment by julieMSFT** [comment]
@toddkitta Hello and thank you for contacting Microsoft. You are correct and the document has been updated. Thank you for helping to improve the documentation. I will proceed with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#https://github.com/MicrosoftDocs/sql-docs/pull/4859

**Comment by julieMSFT** [comment]
#please-close
