### ISSUE TITLE
2012 had this feature - docs missing

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#4735]
Hello, me again..

I just rejected a shelf because of compatibility issues.
Is there a way to get a list of all sql functions and when they were added. Trying to reverse engineer this out of the documentation is very time consuming and error prone. (select in drop edit, wait and see if banner saying not applicable, 'here look at SQL 2019 docs' is a waste of effort).

https://www.mssqltips.com/sqlservertip/2640/sql-server-2012-functions--firstvalue-and-lastvalue/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f79de5-2cb7-ad78-ae1e-0dc617b027c6
* Version Independent ID: e633d0e5-9bd0-5e07-2698-ca1f4475abcf
* Content: [FIRST_VALUE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/first-value-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/first-value-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/first-value-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@brettshearer -- Brett, thank you for your question.  I am looking into it.

**Comment by WilliamAntonRohm** [comment]
@brettshearer -- Brett, please see [this related comment](https://github.com/MicrosoftDocs/sql-docs/issues/3751#issuecomment-562364104) and subsequent discussion.

You are welcome to add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
