### ISSUE TITLE
Creating and Update Statistics in PowerShell

### ISSUE THREAD

**Issue by Firmbyte** [MicrosoftDocs/sql-docs#4736]
There is nothing in this section about creating and /or updating statistics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e019554-eed7-4704-75b9-7ae97c4f3e77
* Version Independent ID: 35705f6e-1aac-7122-d82d-6ba4faf06b59
* Content: [Creating and Updating Statistics - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/tasks/creating-and-updating-statistics?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/server-management-objects-smo/tasks/creating-and-updating-statistics.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/server-management-objects-smo/tasks/creating-and-updating-statistics.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@Firmbyte -- thank you for your feedback, and you are correct.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
@Firmbyte 

Sorry for the delay.

we are investigating this.

Thank you.

**Comment by markingmyname** [comment]
@Firmbyte 

After looking at the PS script, it seems it is used to create a Full-Text Index.

We are working on a new example to better fit this article.

Thank you for bringing this to our attention.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by Firmbyte** [comment]
Thank you!!!

Regards,
*Iain Barnetson*
