### ISSUE TITLE
SQL mistake

### ISSUE THREAD

**Issue by Pope-Liu** [MicrosoftDocs/sql-docs#4746]
在本页面的Example部分所给的SQL语句中，CREATE TABLE Orders( CustomerID varchar(20), OrderDate datetime;)语句应修改为CREATE TABLE Orders( CustomerID varchar(20), OrderDate datetime)；

---
In English, the problem is `;)` at the end should instead be `);`.

In the SQL statement given in the Example section of this page, the `CREATE TABLE Orders (CustomerID varchar (20), OrderDate datetime;)` 

Statement should be modified to `CREATE TABLE Orders (CustomerID varchar (20), OrderDate datetime);` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 051910dd-f368-8472-3068-d73a572d8650
* Version Independent ID: 316236f5-5c00-9584-7775-baf844c34a25
* Content: [OPENXML (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/xml/openxml-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/xml/openxml-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/xml/openxml-sql-server.md)
* Product: **sql**
* Technology: **xml**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by WilliamAntonRohm** [comment]
@Pope-Liu -- 刘行,  thank you for your feedback.  I am looking into this article.

**Comment by MightyPen** [comment]
Fixed this Issue #4746, by private repo PR #14948 .

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/14948`

@Pope-Liu , Thank you for bringing this Transact-SQL mistake to our attention.  We have now fixed it, and this fix should be live on Docs within 24-48 hours.

I am now Closing this fixed Issue
We hope to hear from you again.

cc: @WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
@MightyPen -- Gene, thank you for wrapping up this one.
