### ISSUE TITLE
Does not seem to be working in 

### ISSUE THREAD

**Issue by Robert-Kostecki** [MicrosoftDocs/sql-docs#4751]
SELECT @@version:  Microsoft Azure SQL Data Warehouse - 10.0.11038.0 Apr 21 2020 19:42:42 Copyright (c) Microsoft Corporation

DBCC SHOWRESULTCACHESPACEUSED; 

Returns: 
Msg 104311, Level 16, State 1, Line 44
Incorrect DBCC statement. Check the documentation for the correct DBCC syntax and options.

Completion time: 2020-05-11T15:35:45.4713251+01:00

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66637528-2d6c-4798-db89-3abd393f75a4
* Version Independent ID: 21f933e5-a3d4-46a8-9f3e-b2f9e14e6647
* Content: [DBCC SHOWRESULTCACHESPACEUSED (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-showresultcachespaceused-transact-sql?toc=/azure/synapse-analytics/sql-data-warehouse/toc.json&bc=/azure/synapse-analytics/sql-data-warehouse/breadcrumb/toc.json&view=azure-sqldw-latest)
* Content Source: [docs/t-sql/database-console-commands/dbcc-showresultcachespaceused-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/database-console-commands/dbcc-showresultcachespaceused-transact-sql.md)
* Product: **sql**
* Technology: **data-warehouse**
* GitHub Login: @XiaoyuMSFT
* Microsoft Alias: **xiaoyul**

**Comment by Robert-Kostecki** [comment]
Digging a bit more I have found that the RESULT_SET_CACHING was not enabled (via ALTER DATABASE [DB] SET RESULT_SET_CACHING ON;). 

Once enabled the DBCC command started working. The error message should read "RESULT_SET_CACHING is OFF" rather than incorrect DBCC statement. It may be worth amending as the message is misleading.

**Comment by WilliamAntonRohm** [comment]
@Robert-Kostecki -- Robert, thank you for your feedback and researches.

@XiaoyuMSFT -- Xiaoyu, please look into this issue.

**Comment by julieMSFT** [comment]
@Robert-Kostecki Hi Robert, I am sorry for the delay in response. I am checking to see if we can update the error statement.

**Comment by julieMSFT** [comment]
#assign:julieMSFT

**Comment by Robert-Kostecki** [comment]
No probs Julie!

**Comment by julieMSFT** [comment]
@Robert-Kostecki Hi Robert, I am still trying to get a date for this update. I am going to go ahead and close this issue and update you once the update happens. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
[DevOps work item](https://mseng.visualstudio.com/TechnicalContent/_boards/board/t/SQL/Stories/?showParents=true&workitem=1816452)

**Comment by julieMSFT** [comment]
#please-close

**Comment by Robert-Kostecki** [comment]
Perfect - thank you.
