### ISSUE TITLE
Primary replica SYNCHRONOUS_COMMIT

### ISSUE THREAD

**Issue by ritchxu** [MicrosoftDocs/sql-docs#4756]
In the "Manual failover without data loss" section, it is stated that "Make the target secondary replica SYNCHRONOUS_COMMIT". In reality, the primary replica needs to be set in this mode. Echoed in another documentation https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/failover-and-failover-modes-always-on-availability-groups?view=sql-server-ver15#TermsAndDefinitions

Quoted below:
"A planned manual failover is supported only if both the primary replica and secondary replica are configured for synchronous-commit mode and the secondary replica is currently synchronized (in the SYNCHRONIZED state)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e33fa363-855a-a15d-f692-1b841363cc9f
* Version Independent ID: 9827e246-51df-6b3d-f21d-69c36b349860
* Content: [Perform a planned manual failover of an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/perform-a-planned-manual-failover-of-an-availability-group-sql-server?view=sql-server-ver15#manual-failover-without-data-loss)
* Content Source: [docs/database-engine/availability-groups/windows/perform-a-planned-manual-failover-of-an-availability-group-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/perform-a-planned-manual-failover-of-an-availability-group-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@ritchxu -- Ray, thank you for your feedback and research.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- Masha, please review [private PR 15000](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15000).
