### ISSUE TITLE
Unsupported on Azure SQL

### ISSUE THREAD

**Issue by TaylorN15** [MicrosoftDocs/sql-docs#4758]
The SP sp_estimate_data_compression_savings doesn't work on Azure SQL, but this article implies that it should.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b4d1b7c-15c8-6671-9b5e-78ff189b354a
* Version Independent ID: 5c12ec62-94f5-7a43-04e5-026b09ac2538
* Content: [Enable Compression on a Table or Index - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-compression/enable-compression-on-a-table-or-index?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/data-compression/enable-compression-on-a-table-or-index.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-compression/enable-compression-on-a-table-or-index.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@TaylorN15 -- Taylor, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- please review [private PR 15002](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15002).

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- thank you for the documentation update.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
