### ISSUE TITLE
About Using Table Variables: "Consider using a standard table or temporary table to hold the results of multi-statement table-valued functions (mstvf)."

### ISSUE THREAD

**Issue by Alocyte** [MicrosoftDocs/sql-docs#4762]
Massive differences occur in performance using temporary tables:

Example below derived in database in Compatibility Level 130. 
Using TABLE INT self joining takes (eg) 8 seconds.
Using TABLE INT (Primary Key) self joining takes (eg) 0 seconds.

PRINT '0&gt;' + CONVERT(VARCHAR(30), GETDATE(),20)
DECLARE @SampleSize INT = 10000
DECLARE @Sample TABLE( intValue INT)
INSERT INTO @Sample (intValue)

SELECT TOP (10000) ROW_NUMBER() OVER (ORDER BY a.object_id, b.object_id /*, c.object_id */) i
FROM sys.objects a, sys.objects b--, sys.objects c
PRINT '1&gt;' + CONVERT(VARCHAR(30), GETDATE(),20)

DECLARE @a TABLE (intValue INT )	INSERT INTO @a SELECT DISTINCT intValue FROM @Sample 
DECLARE @b TABLE (intValue INT )	INSERT INTO @b SELECT DISTINCT intValue FROM @Sample 

PRINT '2&gt;' + CONVERT(VARCHAR(30), GETDATE(),20)
SELECT 
       COUNT(a.intValue ) aCount
       ,COUNT(b.intValue ) bCount
FROM @a a
LEFT JOIN @b b
ON b.intValue = a.intValue

PRINT '3&gt;' + CONVERT(VARCHAR(30), GETDATE(),20)

/*
0&gt;2020-05-12 13:07:10

(10000 rows affected)
1&gt;2020-05-12 13:07:10

(10000 rows affected)

(10000 rows affected)
2&gt;2020-05-12 13:07:10

(1 row affected)
3&gt;2020-05-12 13:07:19

Completion time: 2020-05-12T13:07:20.5558659+02:00
*/
GO

PRINT '0&gt;' + CONVERT(VARCHAR(30), GETDATE(),20)
DECLARE @SampleSize INT = 10000
DECLARE @Sample TABLE( intValue INT)
INSERT INTO @Sample (intValue)

SELECT TOP (10000) ROW_NUMBER() OVER (ORDER BY a.object_id, b.object_id /*, c.object_id */) i
FROM sys.objects a, sys.objects b--, sys.objects c
PRINT '1&gt;' + CONVERT(VARCHAR(30), GETDATE(),20)

DECLARE @a TABLE (intValue INT PRIMARY KEY)	INSERT INTO @a SELECT DISTINCT intValue FROM @Sample 
DECLARE @b TABLE (intValue INT PRIMARY KEY)	INSERT INTO @b SELECT DISTINCT intValue FROM @Sample 

PRINT '2&gt;' + CONVERT(VARCHAR(30), GETDATE(),20)
SELECT 
       COUNT(a.intValue ) aCount
       ,COUNT(b.intValue ) bCount
FROM @a a
LEFT JOIN @b b
ON b.intValue = a.intValue
PRINT '3&gt;' + CONVERT(VARCHAR(30), GETDATE(),20)
/*
0&gt;2020-05-12 13:08:35

(10000 rows affected)
1&gt;2020-05-12 13:08:35

(10000 rows affected)

(10000 rows affected)
2&gt;2020-05-12 13:08:35

(1 row affected)
3&gt;2020-05-12 13:08:35

*/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e5062c-ab80-eace-5cbb-8868c17014c3
* Version Independent ID: 7bcb85b7-ee68-ae1c-5385-91f6db828c06
* Content: [Statistics - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/statistics/statistics?view=sql-server-ver15&source=docs)
* Content Source: [docs/relational-databases/statistics/statistics.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/statistics/statistics.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@Alocyte -- thank you for your feedback.

@julieMSFT -- please look into this potential documentation issue.

**Comment by julieMSFT** [comment]
@Alocyte Hello and thank you for contacting Microsoft. I see the differences in execution times in your example.  
You said "Massive differences occur in performance using temporary tables' yet you use a table variable in your example not a [temporary table](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver15#temporary-tables). Can you provide me more information on what you think the article is not stating correctly?

**Comment by Alocyte** [comment]
Hi JulieMSFT
I seem to have lost the context of the statement I made - this response comes on 26 June to WilliamAntonRohm's request on 13 May. This page,  https://github.com/MicrosoftDocs/sql-docs/issues/4762, is contextless.

I don't believe I understood your question correctly- it seems to state I misunderstood the nature of the temporary table within a multi-statement function? And from the link, you are meaning I should be utilising a #table?

CREATE FUNCTION dbo.fn_Test(@Int1 INT, @Int2 INT)
RETURNS @TABLE TABLE ( Int1 INT, Int2, Result INT)
AS
BEGIN
	IF OBJECT_ID('TempDB.dbo.#fn_Test_TemporaryTable') IS NOT NULL
		DROP TABLE #fn_Test_TemporaryTable
	CREATE TABLE #fn_Test_TemporaryTable
	( Int1 INT, Int2 INT, Result AS Int1 * Int2)
	INSERT INTO #fn_Test_TemporaryTable (Int1, Int2)
	VALUES (Int1, Int2)

	RETURN (SELECT * FROM #fn_Test_TemporaryTable)
END
GO
 
Msg 2772, Level 16, State 1, Procedure fn_Test, Line 9 [Batch Start Line 0]
Cannot access temporary tables from within a function.

**Comment by julieMSFT** [comment]
@Alocyte Hi, thank you for your response. I am confused by this submission. The title and the comments do not seem to match. the comment is  "Massive differences occur in performance using temporary tables" yet the example does not use a temporary table and the difference in performance seems to be from a table with a primary key vs a heap table. Can you restate your original concern to help me understand what you think should be different in this document?

**Comment by Alocyte** [comment]
HI @julieMSFT 

Please provide a link to the original article my submission targeted.

Thanks

**Comment by julieMSFT** [comment]
@Alocyte Hi, this is the article this issue was attached to, https://docs.microsoft.com/en-us/sql/relational-databases/statistics/statistics?view=sql-server-ver15&source=docs.

**Comment by Alocyte** [comment]
Well, I too am confused. Statistics... huh. 

My statement elaborated how creating a clustered index on a table variable, 
made a disproportionately massive difference to the query's execution speed. 
[ 1 sec vs 9 sec for 10000 rows self joining on an integer field]
That has nothing to do with statistics. 

Ok then.
