### ISSUE TITLE
Title is potentially misleading

### ISSUE THREAD

**Issue by WouterJeuris** [MicrosoftDocs/sql-docs#4763]
This page concerns an *SQL Server driver for Ruby*, yet the title turns this the other way around. In the current phrasing "A Ruby Driver to connect to SQL Server" is implied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2426d21c-01c8-1d0e-9bf6-a5262dc19155
* Version Independent ID: 0bca8d2e-201e-a3a2-95ef-2fab28b38872
* Content: [Ruby Driver - SQL Server](https://docs.microsoft.com/en-us/sql/connect/ruby/ruby-driver-for-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/connect/ruby/ruby-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/ruby/ruby-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@WouterJeuris Thanks for submitting feedback.

> This page concerns an _SQL Server driver for Ruby_, yet the title turns this the other way around. In the current phrasing "A Ruby Driver to connect to SQL Server" is implied.

I'm not sure I understand how the title is misleading. The main heading is "Ruby Driver for SQL Server". The page title is "Ruby Driver - SQL Server". You seem to be implying that the title might be implying that it is about a driver for SQL Server to connect to Ruby. But you would never connect to a programming language from a database. There's nothing to connect to until you create it using the programming language.

The phrasing is consistent with what we use for other the drivers in this documentation. "for SQL Server" comes last as in "for [connecting to] SQL Server".

**Comment by David-Engel** [comment]
Closing this issue. If you feel that there is still something that needs to be resolved, feel free to reopen and add more information.

#please-close
