### ISSUE TITLE
OFFSET / FETCH missing from SELECT syntax

### ISSUE THREAD

**Issue by HugoKornelis** [MicrosoftDocs/sql-docs#4764]
On the page that desscribes the SELECT syntax (https://docs.microsoft.com/en-us/sql/t-sql/queries/select-transact-sql?view=sql-server-ver15), the syntax for OFFSET ... FETCH is missing.

Since (I think?) SQL Server 2012, SQL Server supports the ANSI standard "OFFSET nn ROWS FETCH mm ROWS ONLY" syntax, as an alternative to the non-standard TOP clause; but only when an ORDER BY is present.
The OFFSET ... FETCH option is completely missing from this page, though.

(It is documented here, though: https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/ms188385(v=sql.110)?redirectedfrom=MSDN)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da7ee936-5d16-3ab9-97dc-35fceb3ebe29
* Version Independent ID: 9daaeef8-0dc3-e241-5b65-fbe2b217e191
* Content: [SELECT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/queries/select-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/select-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@HugoKornelis -- thank you for your feedback.

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
Hello @HugoKornelis - Can you please clarify? We do list the ORDER BY clauses in the [ORDER BY](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-ver15) page, which is linked from the SELECT article.

![image](https://user-images.githubusercontent.com/40007119/83615020-db0d7580-a53a-11ea-8eb7-7b976030b8e3.png)

**Comment by HugoKornelis** [comment]
Apologies for the late reply.

The documentation on https://docs.microsoft.com/en-us/sql/t-sql/queries/select-transact-sql?view=sql-server-ver15 starts with two versions of the main syntax, One for SQL Server / SQL Azure Database; and below that a second one for Azure Synapse Analytics and Parallel Data Warehouse.

In the second overview (for Azure Synapse Analytics and Parallel Data Warehouse), all clauses _including ORDER BY_ are merely mentioned briefly, as a clear indication that the reader should use the links to more detailed information.

In the first overview (for SQL Server and Azure SQL Database), _most_ clauses, are listed that way ... but ORDER BY is not! In this section, ORDER BY is described as "[ ORDER BY { order_by_expression | column_position [ ASC | DESC ] }     [ ,...n ] ]", which suggests that the link to the more detailed information about ORDER BY only applies to Azure Synapse Analytics and Parallel Data Warehouse.

**Comment by VanMSFT** [comment]
Hi @HugoKornelis - ORDER BY is listed in the Syntax for SQL Server and Azure SQL Database as well:

![image](https://user-images.githubusercontent.com/40007119/96722264-09f97c00-1362-11eb-8cd9-0d90f37ded91.png)

**Comment by HugoKornelis** [comment]
Yes, I know that ORDER BY is in there as well. I said so myself.
What is missing is the FETCH / OFFSET option. That's what I reported.

**Comment by VanMSFT** [comment]
Thanks for clarifying, @HugoKornelis! I understand that this can cause confusion for some, but as you inferred, we're hoping that users will open the [ORDER BY](https://docs.microsoft.com/sql/t-sql/queries/select-order-by-clause-transact-sql) article to get more information about the syntax available. This is the way that we currently structure our articles. We do appreciate the feedback, and will look to make improvements in the future with the feedback that we receive from this wonderful community.

**Comment by HugoKornelis** [comment]
If you hope that users open the ORDER BY article, then perhaps you should put a reference to the ORDER BY article in that place (similar to how you do it for Azure Synapse Analytics and Parallel Data Warehouse). Simple copy/paste. Would have taken you less time than the responses you sent to me.
