### ISSUE TITLE
ls -l

### ISSUE THREAD

**Issue by brettrowberry** [MicrosoftDocs/sql-docs#4765]
ls -l does not work in PowerShell, and ls will probably give what we want anyway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd398c1-ed8b-911b-f11a-3739d80b3f32
* Version Independent ID: dc3d55ff-3b55-a686-81f9-f4188054e381
* Content: [Restore a SQL Server database in Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-restore-backup-in-sql-server-container?view=sql-server-linux-2017#feedback)
* Content Source: [docs/linux/tutorial-restore-backup-in-sql-server-container.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-restore-backup-in-sql-server-container.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Thanks @brettrowberry!

Hey @vin-yu - Can you confirm this?

**Comment by VanMSFT** [comment]
Hello @brettrowberry! Thanks for your patience! I have fixed the typo in the doc, and it should be updated later today. We appreciate you bringing this to our attention!
