### ISSUE TITLE
Confusion about default driver being used

### ISSUE THREAD

**Issue by MrBrianGale** [MicrosoftDocs/sql-docs#4767]
I am just curious why SQL Server by default uses the SQL Server Native Client OLE DB provider (SQLNCLI) provider by default when making a linked server without specifying the provider.  Multiple times in the document it indicates this provider is deprecated and should not be used.  In more recent versions of SQL Server, is it using the Microsoft OLE DB Driver for SQL Server (MSOLEDBSQL) provider by default or does it still use the depreciated SQLNCLI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 051788f8-a729-7a59-8b2f-5e2ba2cf62c2
* Version Independent ID: 30b9fe82-bc80-cf19-6ee3-7ce45a826975
* Content: [sp_addlinkedserver (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-addlinkedserver-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-addlinkedserver-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-addlinkedserver-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@pmasl Pedro, do you know who can answer this question?

**Comment by MrBrianGale** [comment]
I mean, I expect the documentation to be correct and the SQLNCLI driver is being used by default, even in SQL Server 2019, , I just think that some clarification on as to WHY this is the default.
My best guess is that it is due to compatibility reasons, but it would be helpful to include that in the documentation.

**Comment by CarlRabeler** [comment]
SQLNCLI is installed with every version of SQL Server, and SQLNCLI10 is installed with 2008/2008R2. SQLNCLI11 is installed with 2012, 2016, 2017, and 2019. So the customer is partially right, SQLNCLI is the default because not every version of SQL installation includes a specific driver besides SQLNCLI.
You can specify the driver that you want to use in the parameter. MSOLEDBSQL is not installed with SQL Server, and has a standalone download, so it wouldn’t be a default, and we wouldn’t include this as a default in our docs that span multiple versions even it was standard for 2019.

**Comment by MrBrianGale** [comment]
So is it more that SQLNCLI10 is discontinued, not that SQLNCLI is discontinued?

**Comment by CarlRabeler** [comment]
See https://docs.microsoft.com/en-us/archive/blogs/sqlnativeclient/announcing-the-new-release-of-ole-db-driver-for-sql-server

I will be updating this article (and others to reflect this). Thank you for bringing this up.
Carl

**Comment by CarlRabeler** [comment]
In SQL2019, the alias SQLNCLI maps to MSOLEDBSQL, so existing server connection strings using this should switch to MSOLEDBSQL transparently. (In older versions, SQLNCLI maps to SQLNCLI11; in 2019, you can still use SQLNCLI11 if you want to use the old provider).

**Comment by CarlRabeler** [comment]
@MrBrianGale See update in these articles: https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-servers-transact-sql?view=sql-server-ver15 and https://docs.microsoft.com/en-us/sql/relational-databases/linked-servers/linked-servers-database-engine?view=sql-server-ver15

In SQL2019, the alias SQLNCLI maps to MSOLEDBSQL, so existing server connection strings using this switch to MSOLEDBSQL transparently. Is this not what you observe?
(In older versions, SQLNCLI will map to SQLNCLI11; in 2019, you can still use SQLNCLI11 if you want to use the old provider).


Thanks for bringing this to our attention
