### ISSUE TITLE
STStartPoint document sql statement error

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#4769]
The comments below were machine-translated

@zLulus commented on [Tue May 12 2020](https://github.com/MicrosoftDocs/sql-docs.zh-cn/issues/143)

[STStartPoint (geometry Data Type）](https://docs.microsoft.com/zh-cn/sql/t-sql/spatial-geometry/ststartpoint-geometry-data-type?view=sql-server-ver15)    
```sql
DECLARE @g geometry;  
SET @g = geometry::STGeomFromText('LINESTRING(0 0, 2 2, 1 0)', 0;  
SELECT @g.STStartPoint().ToString();  
```
Should be changed to
```sql
SET @g = geometry::STGeomFromText('LINESTRING(0 0, 2 2, 1 0)', 0);  
```

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e46d0079-02e5-e0ba-8d64-93030fa6ddf7
* Version Independent ID: 4a0eff3a-0396-795b-a413-48d8805bf12e
* Content: [STStartPoint（geometry 数据类型） - SQL Server](https://docs.microsoft.com/zh-cn/sql/t-sql/spatial-geometry/ststartpoint-geometry-data-type?view=sql-server-ver15)
* Content Source: [docs/t-sql/spatial-geometry/ststartpoint-geometry-data-type.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/t-sql/spatial-geometry/ststartpoint-geometry-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

---

@srvbpigh commented on [Tue May 12 2020](https://github.com/MicrosoftDocs/sql-docs.zh-cn/issues/143#issuecomment-627163838)

Hello, @zLulus
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@imba-tjd -- 谭九鼎, thank you for your contribution.

@MladjoA -- Mladen, please review the above-mentioned PR 4761.
