### ISSUE TITLE
GIF images not readable when using dark theme

### ISSUE THREAD

**Issue by Shuwi75** [MicrosoftDocs/sql-docs#4771]
The GIF images are not readable when using dark themed (chromium) browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916e128d-19fd-1f7d-8285-6313c4419710
* Version Independent ID: 8402af42-fdd1-2f3b-7c6a-8759e90e115f
* Content: [Choose a database engine upgrade method - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/choose-a-database-engine-upgrade-method?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/install-windows/choose-a-database-engine-upgrade-method.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/choose-a-database-engine-upgrade-method.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@Shuwi75 -- thank you for your feedback.  Please raise it here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

**Comment by MashaMSFT** [comment]
Hi @Shuwi75 , thanks for bringing this to our attention! Actually, I can update these images myself. 
I'll update the Issue once the change is processed, but please bear with us as it may not happen immediately. 

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @Shuwi75 , this change has been processed and is now live.

Thanks for improving our documentation! Hope you have a wonderful rest of your day :) 
Masha from the SQL Docs team
