### ISSUE TITLE
Wrong arguments listed ?

### ISSUE THREAD

**Issue by Ikaer** [MicrosoftDocs/sql-docs#4772]
On my SQL Server 2016 and 2012 R1 + a test on Azure SQL DB 12, this stored procedure have different parameter names sys.sp_db_selective_xml_index ( @dbname sysname = null, @selective_xml_index varchar(6) = null ).

Also it would be great to include in this page that N'off' or N'false' will not work if this feature have already been enabled (Error message: "The data type of substitution parameter 2 does not match the expected type of the format specification."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fda8730d-d1a2-4b42-348e-16768640dc8b
* Version Independent ID: c2d1f135-9f10-2304-e3df-9e7e5a294be7
* Content: [sp_db_selective_xml_index (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-db-selective-xml-index-transact-sql?view=sql-server-2016#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-db-selective-xml-index-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-db-selective-xml-index-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@pmasl Pedro, could you please look at this?

**Comment by CarlRabeler** [comment]
@pmasl Pedro, could you please look at this?

**Comment by CarlRabeler** [comment]
#reassign: @pmasl 
Pedro - could you please look at this. If this is not in your area, please either reassign back to me and reassign to the appropriate individual

**Comment by rothja** [comment]
@Ikaer Apologies for the long delay on this. @WilliamDAssafMSFT William, this should be fairly straightforward to verify with the examples provided in the doc. Would you be able to take a look at testing and potentially fixing the arguments on this page if necessary. I'm going to assign it to you for testing, and we'll only loop in @pmasl on the eventual PR for awareness (or if it is more complex than it looks). Thank you! #reassign:WilliamDAssafMSFT

**Comment by WilliamDAssafMSFT** [comment]
@lkaer Thanks for contacting Microsoft with feedback about our product documentation. In this article there appear to be a couple things we'll be working on. A doc update is in flight, and we are working with the product team to investigate the disable message.

We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. 

Thanks again for submitting your feedback. Your suggestions help improve our documentation and we appreciate the effort.
