### ISSUE TITLE
Ubuntu 20.04 repo is already provided, please update docs.

### ISSUE THREAD

**Issue by flipbit03** [MicrosoftDocs/sql-docs#4774]
I figured it out by just exchanging the apt url from 19.10 to 20.04 and it downloaded a repository definition, so I guess it's ready.

Thank you!

**Comment by WilliamAntonRohm** [comment]
@flipbit03 -- Cadu, thank you for your feedback.  Do you have a particular docs.microsoft.com article in mind?

**Comment by flipbit03** [comment]
Yes, it was the article about configuring the MSSQL Linux ODBC Driver. But I inspected further and, while the 20.04 repository is there, the mssqlodbc17 driver is still not present, so I guess _the guys at MS_ are still working on it.

Sorry!

**Comment by WilliamAntonRohm** [comment]
@flipbit03 -- Cadu, thank you for clarifying.

cc @David-Engel for awareness
