### ISSUE TITLE
No mssql-tools package for ubuntu 20.04

### ISSUE THREAD

**Issue by camille-rodriguez** [MicrosoftDocs/sql-docs#4775]
I seem unable to locate the package mssql-tools for ubuntu 20.04. I changed the curl to point towards https://packages.microsoft.com/config/ubuntu/20.04/prod.list , which exists, but I get an error " Unable to locate package mssql-tools" when I try to install it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by camille-rodriguez** [comment]
Also, if I try to install from 18.04 or earlier, there are broken dependencies.

**Comment by VanMSFT** [comment]
Hi @camille-rodriguez! Ubuntu 20.04 is not a supported for SQL Server at the moment.

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019?view=sql-server-ver15
