### ISSUE TITLE
RETURN SCOPE_IDENTITY() vs. SELECT SCOPE_IDENTITY()

### ISSUE THREAD

**Issue by denmitchell** [MicrosoftDocs/sql-docs#4776]
Regarding the [SQL Server Unit Test Walkthrough](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssdt/walkthrough-creating-and-running-a-sql-server-unit-test.md) ...

I am having difficulty returning the newly inserted identity value for CustomerID when the uspNewCustomer stored procedure ends with ```SELECT SCOPE_IDENTITY()```.  I don't have any difficulty if I modify this line to be ```RETURN SCOPE_IDENTITY()``` instead.  Is there any reason why this might be happening.  Is ```SELECT``` preferred over ```RETURN```?

I am targeting a (localdb)\ProjectsV13 instance, version 13.0.4001.

**Comment by WilliamAntonRohm** [comment]
@denmitchell -- Dennis, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review [private PR 15003](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15003).
