### ISSUE TITLE
ActiveX subsystem discontinued ?

### ISSUE THREAD

**Issue by mco100** [MicrosoftDocs/sql-docs#4779]
isn't there a contradiction between this page and the fact that this subsystem is discontinued since SQL Server 2016 ? see https://docs.microsoft.com/en-us/sql/database-engine/discontinued-database-engine-functionality-in-sql-server?view=sql-server-ver15#discontinued-features-in--1 this subsystem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5008405-0ab9-5fbd-11df-5ffac1c631b0
* Version Independent ID: 1759bd47-7e19-582b-9c71-a4ba4485f5bb
* Content: [Create an ActiveX Script Job Step - SQL Server Agent](https://docs.microsoft.com/en-us/sql/ssms/agent/create-an-activex-script-job-step?view=sql-server-ver15)
* Content Source: [docs/ssms/agent/create-an-activex-script-job-step.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/create-an-activex-script-job-step.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@mco100 -- thank you for your question.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
@mco100 

Apologizes for the delay.

We are investigating this.

**Comment by markingmyname** [comment]
The issue has been reassigned to get a further investigation.
