### ISSUE TITLE
No maximum value for MAX_STORAGE_SIZE_MB is documented

### ISSUE THREAD

**Issue by m60freeman** [MicrosoftDocs/sql-docs#4781]
Any attempt to set the value of MAX_STORAGE_SIZE_MB higher than 10240 results in the following error message: "Cannot set Query Store max_storage_size_mb to nnnnn. The maximum allowed limit is 10240 MB." This limit does not appear to be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155bfbc5-9c63-32c6-9d06-a9b3cdb4c60e
* Version Independent ID: c854b2de-e509-e320-8151-67d690d486ed
* Content: [Best practices with Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/best-practice-with-the-query-store?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/best-practice-with-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/best-practice-with-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @pmasl
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@m60freeman -- Mark, thank you for your feedback.

@pmasl -- Pedro, please look into this issue.

related to #4782

**Comment by pmasl** [comment]
The Query Store has no such limit on SQL 2016 through 2019. Where are you trying to execute ALTER DATABASE ... SET QUERY STORE command?

**Comment by nqg04789** [comment]
Isn't it about Azure SQL Database?
I got the same error in Azure SQL Database.

**Comment by pmasl** [comment]
It's an Azure SQL only limitation. I'll add that to the docs asap. #please-close

**Comment by pmasl** [comment]
For reverence, updated here: https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options?view=azuresqldb-current
