### ISSUE TITLE
No maximum value for MAX_STORAGE_SIZE_MB is documented

### ISSUE THREAD

**Issue by m60freeman** [MicrosoftDocs/sql-docs#4782]
Any attempt to set the value of MAX_STORAGE_SIZE_MB higher than 10240 results in the following error message: "Cannot set Query Store max_storage_size_mb to nnnnn. The maximum allowed limit is 10240 MB." This limit does not appear to be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b587ab-50b8-eada-aa86-ba0c838c57ee
* Version Independent ID: f1fd2d52-b66f-4fbc-c54a-c688c4fd0f21
* Content: [Monitoring Performance By Using the Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by julieMSFT** [comment]
@m60freeman Hi Mark, thank you for contacting Microsoft. This is an Azure SQL only limitation. It will be added to the docs asap. We hope to hear from you again.

#please-close
