### ISSUE TITLE
Incorrect date

### ISSUE THREAD

**Issue by ccparkhill** [MicrosoftDocs/sql-docs#4784]
The date listed for SQL Server 2017 CU 20 is actually for CU19.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1353d4d-3899-d6cf-e44f-8536c7828335
* Version Independent ID: de0210cf-386a-f8c8-1157-40cea207ed4b
* Content: [Latest updates for Microsoft SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/latest-updates-for-microsoft-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/install-windows/latest-updates-for-microsoft-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/latest-updates-for-microsoft-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @tmichael-ms
* Microsoft Alias: **tmichael**

**Comment by WilliamAntonRohm** [comment]
@ccparkhill -- thank you for your feedback.

@tmichael-ms -- please look into this issue.  You are welcome to send me the date & I will update the article.

**Comment by ccparkhill** [comment]
> @ccparkhill -- thank you for your feedback.
> 
> @tmichael-ms -- please look into this issue. You are welcome to send me the date & I will update the article.

Date is 7th April 2020:
https://www.microsoft.com/en-us/download/details.aspx?id=56128

**Comment by tmichael-ms** [comment]
I fixed it.  SQL 17 CU20 release date updated to 4/7/2020…
https://github.com/MicrosoftDocs/sql-docs-pr/pull/15434

**Comment by tmichael-ms** [comment]
@ccparkhill -- Thank you for reporting this issue so we could take action to fix it.
