### ISSUE TITLE
wrong sentence

### ISSUE THREAD

**Issue by edurakhanyan** [MicrosoftDocs/sql-docs#4787]
i think this sentence is not grammatically correct:

The query optimizer makes a cost-based decision to push computation to Hadoop when doing so will improve query performance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ebefef-f8c5-e429-269e-1ef7a96264fd
* Version Independent ID: a8009495-9bb9-87f4-85af-0ac0074749e7
* Content: [What is PolyBase? - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-guide?view=sql-server-ver15)
* Content Source: [docs/relational-databases/polybase/polybase-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-guide.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@edurakhanyan -- thank you for your feedback.  I am looking into clarifying that sentence.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- please review [private PR 15004](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15004).
