### ISSUE TITLE
Need more details about DELIMITEDTEXT file content expectations when STRING_DELIMITER is specified.

### ISSUE THREAD

**Issue by agr** [MicrosoftDocs/sql-docs#4788]
I have a delimited text file, that uses single space as a field separator and puts quotes around string values _only_ when there is a space in that value. Is it possible to describe such format with CREATE EXTERNAL FILE FORMAT?
Does specifying STRING_DELIMITER make it expect that _every_ string value in the file would be surrounded by that delimiter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72fb8035-306f-ffc1-4159-141ae7b68c77
* Version Independent ID: a202acea-442c-140f-6f39-3f851238a740
* Content: [CREATE EXTERNAL FILE FORMAT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-file-format-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-external-file-format-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-file-format-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
yes, that is my understanding

**Comment by agr** [comment]
Was that "yes" for the first or the second question? :)

**Comment by CarlRabeler** [comment]
Sorry - second question - every string value with delimiter
