### ISSUE TITLE
What kind of conditions are allowed?

### ISSUE THREAD

**Issue by NaomiN** [MicrosoftDocs/sql-docs#4790]
I tried to create a filtered index using NOT LIKE 'Value%' expression and then also NOT IN ('Value1', 'Value2') and both resulted in error Msg 102, Level 15, State 1, Line 163
Incorrect syntax near 'NOT'.
I can try one more time using where column !='Value2' and Column =!'Value2' I'm using Azure DB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e578e8fc-b9da-8c8d-5a4a-64084f1204de
* Version Independent ID: 4adb8a19-ff61-5724-9f01-fb673efb7991
* Content: [Create Filtered Indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/create-filtered-indexes?view=sql-server-ver15)
* Content Source: [docs/relational-databases/indexes/create-filtered-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/create-filtered-indexes.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by NaomiN** [comment]
Just a comment - the last variation (with two conditions) did work.

**Comment by WilliamAntonRohm** [comment]
@NaomiN -- Naomi, thank you for your question and successful research.  The article mentions:
> Filtered indexes are defined on one table and only support simple comparison operators. If you need a filter expression that references multiple tables or has complex logic, you should create a view.


@MikeRayMSFT -- Mike, please look into this issue.

**Comment by NaomiN** [comment]
I think we may want to add some clarifications of what is considered "simple".

**Comment by MikeRayMSFT** [comment]
Hi @NaomiN -thanks for the submission. We're updating the docs. 

@bluefooted helped me clarify what's happening here:

Basically a “simple comparison operator” is one of the mathematical [comparison operators](https://docs.microsoft.com/sql/t-sql/language-elements/comparison-operators-transact-sql).

Under the covers, the database engine translates a LIKE or NOT LIKE into two clauses with an AND operation between them. In other works, string LIKE ‘cat%’ would be translated to string >= ‘cat’ AND string <= ‘caU’ or something like that (would have to look up the exact character order to know for sure, also it would depend on collation). 

The doc update is in flight, but you've already waited a long time so I wanted to get you an answer! Thanks for the good question!
Mike
