### ISSUE TITLE
The SQL examples are not colored.

### ISSUE THREAD

**Issue by Protiguous** [MicrosoftDocs/sql-docs#4791]
The SQL examples are not colored, (like they are on 
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/set-operators-union-transact-sql).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afce4563-251c-b618-9ed3-e8a8240a65f5
* Version Independent ID: 1bf83dd1-97c7-853e-1ef8-cce95b4bdf7d
* Content: [EXCEPT and INTERSECT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/set-operators-except-and-intersect-transact-sql?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(except_TSQL);k(sql13.swb.tsqlresults.f1);k(sql13.swb.tsqlquery.f1);k(DevLang-TSQL)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=sql-server-ver15)
* Content Source: [docs/t-sql/language-elements/set-operators-except-and-intersect-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/set-operators-except-and-intersect-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@Protiguous -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
