### ISSUE TITLE
Unable to complete the example

### ISSUE THREAD

**Issue by camille-rodriguez** [MicrosoftDocs/sql-docs#4794]
At the "Load Data" step, when I run this section 
```
INSERT INTO web_clickstream_clicks_data_pool
SELECT wcs_user_sk, i_category_id, COUNT_BIG(*) as clicks
  FROM sales.dbo.web_clickstreams_hdfs
INNER JOIN sales.dbo.item it ON (wcs_item_sk = i_item_sk
                        AND wcs_user_sk IS NOT NULL)
GROUP BY wcs_user_sk, i_category_id
HAVING COUNT_BIG(*) &gt; 100;
```
I end up with this error:
```
Started executing query at Line 1
Msg 208, Level 16, State 1, Line 1
Invalid object name 'sales.dbo.web_clickstreams_hdfs'.
Total execution time: 00:00:00.039
```
Is this example missing some data to be loaded?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf1b0e77-0f03-7b70-b2e3-26911e49dd47
* Version Independent ID: 511793e4-b3c5-3d07-a8e9-bc10b8347985
* Content: [Ingest data into a SQL Server data pool - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-sql?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/tutorial-data-pool-ingest-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/tutorial-data-pool-ingest-sql.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@camille-rodriguez -- Camille, thank you for your feedback.  I believe the table name should be `sales.dbo.web_clickstreams_hdfs_parquet`, as in [this GitHub example](https://github.com/microsoft/sql-server-samples/blob/master/samples/features/sql-big-data-cluster/data-pool/data-ingestion-sql.sql).  

Please let me know if this solves your issue, and then I will updated this article.

cc @MikeRayMSFT for awareness
