### ISSUE TITLE
Edition Availability needs to be fixed

### ISSUE THREAD

**Issue by nirmalkohli** [MicrosoftDocs/sql-docs#4795]
Polybase can now use Standard Edition for the head node (starting with SQL Server 2019). This page needs to be updated in the "Editions Availability" section, where it says this feature is only available in Enterprise Edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f4110e3-60aa-33ec-a988-dac8ff120969
* Version Independent ID: 5f09f973-22d6-a487-a749-515a0607cd00
* Content: [PolyBase scale-out groups - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-scale-out-groups?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/polybase/polybase-scale-out-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-scale-out-groups.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@nirmalkohli -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- please review [private PR 15023](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15023).
