### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ChrisWoods1977** [MicrosoftDocs/sql-docs#4796]
May I recommend specifically calling out in the permissions section something like, "Membership of the database role db_owner is not enough. The user must also be the actual owner." I had this problem and have come across several forum posts that show others were confused by this, as well. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117e4295-fbcd-6d05-97a3-ee23d13bed33
* Version Independent ID: 2d74fe2e-3d32-a650-d073-c891fc2382a1
* Content: [sp_updatestats (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-updatestats-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-updatestats-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-updatestats-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@pmasl Pedro - could you please look at this?

**Comment by CarlRabeler** [comment]
@VanMSFT  could you also look into this?

**Comment by VanMSFT** [comment]
@CarlRabeler - I think it's worth calling out if there's confusion. To me, it's clear that you need owner permission, not just db_owner role, or else we would purposely state db_owner role instead of ownership itself.

![image](https://user-images.githubusercontent.com/40007119/82085986-ab3d2180-96a2-11ea-8dde-5ac61722cf03.png)

@AndreasWolter - Please let us know your thoughts. Thanks!

**Comment by AndreasWolter** [comment]
Thanks for calling that out.
I suggest to rephrase like so:
To run sp_updatestats as user needs to be the owner of the database (the dbo, not just member of the role db_owner) or to be member of the sysadmin fixed server role.

**Comment by ChrisWoods1977** [comment]
I like that proposed change. It clears up any possible confusion. Thanks!

**Comment by CarlRabeler** [comment]
@ChrisWoods1977 updating this article today - fix will be live within 6 hours or so
