### ISSUE TITLE
APPLIES TO: Azure Synapse Analytics (SQL DW) does not seem to be the case

### ISSUE THREAD

**Issue by Robert-Kostecki** [MicrosoftDocs/sql-docs#4804]
@@version: Microsoft Azure SQL Data Warehouse - 10.0.11038.0 Apr 30 2020 04:41:26 Copyright (c) Microsoft Corporation
Msg 40515, Level 15, State 1, Line 45
Reference to database and/or server name in 'xxx.INFORMATION_SCHEMA.SEQUENCES' is not supported in this version of SQL Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e59b7c2-8cdd-d109-3ab6-720fb3318b62
* Version Independent ID: 31304233-f9a3-63cc-acd8-a8e2985b89be
* Content: [SEQUENCES (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-information-schema-views/sequences-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-information-schema-views/sequences-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-information-schema-views/sequences-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@julieMSFT could you please look into this?

**Comment by julieMSFT** [comment]
#assign:julieMSFT

**Comment by julieMSFT** [comment]
@Robert-Kostecki Hello, Thank you for contacting Microsoft. I am looking into this.

**Comment by julieMSFT** [comment]
@Robert-Kostecki Hi Robert, thank you for contacting Microsoft. You are correct, sequences do not apply to Azure Synapse Analytics (SQL DW). I have updated the document to reflect this and you should see it shortly. I will go ahead and close this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
