### ISSUE TITLE
Secondary replica behavior when suspended

### ISSUE THREAD

**Issue by felipespas-brz** [MicrosoftDocs/sql-docs#4806]
Regarding the statement "Existing connections on the readable secondary remain usable. New connections to the suspended database on the readable secondary are not allowed until data movement is resumed."
We have a SQL 2019 environment where we suspended the secondary replica in the secondary itself and we were still able to open new connections with the app directly pointed to the secondary (without read-only routing) while running a regular workload (DML/DDL) on primary. 
Based on this scenario, the statement above should specify this behavior only applies when connecting to secondaries via listener and with read-only routing enabled. The statement should specify this:
"Existing connections on the readable secondary remain usable. New connections to the suspended database on the readable secondary are not allowed until data movement is resumed. This behavior only applies when connections are opened using listener and read-only routing."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9328660b-a039-4055-d5ce-39ab21865319
* Version Independent ID: 2bcce881-5638-a3c7-aaf2-1d386be491ee
* Content: [Suspend an availability database - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/suspend-an-availability-database-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/suspend-an-availability-database-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/suspend-an-availability-database-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@felipespas-brz -- Felipe, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- Masha, please review [private PR 15059](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15059).
