### ISSUE TITLE
Typo "[Code of Conduct][conduct-md]" ?

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/sql-docs#4810]
https://docs.microsoft.com/en-us/sql/azure-data-studio/powershell-extension?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abda6b59-7b6a-af05-5551-06375473fdc3
* Version Independent ID: 0bba3dc2-9bce-5df1-fa8a-be933632e733
* Content: [PowerShell extension - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/powershell-extension?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/powershell-extension.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/powershell-extension.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @SQLvariant
* Microsoft Alias: **aanelson**

**Comment by WilliamAntonRohm** [comment]
@hyoshioka0128 -- Hiroshi, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
I have updated the documentation and it should be live by tomorrow.
