### ISSUE TITLE
In the example script, DacStore is deprecated since MS SQL Server 2012

### ISSUE THREAD

**Issue by Iamanorange** [MicrosoftDocs/sql-docs#4811]
Error message:
```
PS SQLSERVER:\SQL\localhost\DEFAULT&gt; $dacstore = New-Object Microsoft.SqlServer.Management.Dac.DacStore($serverconnection)
New-Object : Cannot find type [Microsoft.SqlServer.Management.Dac.DacStore]: verify that the assembly containing this type is loaded.
At line:1 char:13
+ $dacstore = New-Object Microsoft.SqlServer.Management.Dac.DacStore($s ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
```
Link to DacStore doc: https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ee242746(v%3Dsql.105)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 153035d3-8b8a-5d7c-f400-ba32fc3bd53c
* Version Independent ID: adbe44f8-d6b0-33dd-cfb1-cf7d3b259c8a
* Content: [Upgrade a Data-tier Application - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/upgrade-a-data-tier-application?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/data-tier-applications/upgrade-a-data-tier-application.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/upgrade-a-data-tier-application.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@Iamanorange -- thank you for your feedback.

@stevestein -- please look into this issue.

**Comment by stevestein** [comment]
@Iamanorange - thanks for raising this issue. At this time the entire Data-tier application section is due for an update. We're tracking this in an internal work item (1571961).

Thanks!
#please-close
