### ISSUE TITLE
what is the address of connecting to SQL docker from host

### ISSUE THREAD

**Issue by AAATechGuy** [MicrosoftDocs/sql-docs#4812]
this is a common confusion. 
In this walkthrough, to connect via SSMS, you need this address `localhost\sqlexpress,1433`, which is not clear in this tutorial. spent some time to figure it out. 
Discussion here https://github.com/microsoft/msphpsql/issues/302

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-cmd#feedback)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by AAATechGuy** [comment]
it's not just IP Address, rather, ipaddress\instancename,port
PS, i do have sql installed on my host.

**Comment by WilliamAntonRohm** [comment]
@AAATechGuy -- Abin, thank you for your feedback and research.

@vin-yu - Vin, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @AAATechGuy, thanks for submitting this issue. To connect to your local instance of SQL Server, there is no need to input `ipaddress\instancename,port`. For a default instance of SQL Server that uses the default port, using `ipaddress` or `servername` is enough. We default to connecting on port 1433. If connecting locally, `localhost` will also work.

When denoting the `\` in the connection, this triggers SQL Browser to find the port that SQL Server is listening on for the connection. If you want to specify the port, or if SQL Server is using a non-default port, you can omit the instance name from the server connection. Like so, `ipaddress,port`.

We'll go ahead and close this issue, but please let us know if you have concerns.
