### ISSUE TITLE
Modify_Date column description is not full or correct

### ISSUE THREAD

**Issue by sqlvar** [MicrosoftDocs/sql-docs#4817]
Hello.
Here is the description for MODIFY_DATE in the documentation for the system table 'sys.objects':
<<Date the object was last modified by using an ALTER statement. If the object is a table or a view, modify_date also changes when a clustered index on the table or view is created or altered.>>

I have noticed that the value of MODIFY_DATE also changes when rebuilding a NON-CLUSTERED index like 
ALTER INDEX nci_col1 ON dbo.test REBUILD;
As you see above, the doc does not mention non-clustered indexes.

Is this a bug in SQL Server or missing/incomplete info in the doc?

Please let me know if you need more info.

Thanks,
Varsham Papikian
vpapikian@hotmail.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aedf5009-471e-5efb-1b40-cc1193292036
* Version Independent ID: 604d5a23-cb15-e037-7df8-9798d62332f9
* Content: [sys.objects (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-objects-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15&source=docs)
* Content Source: [docs/relational-databases/system-catalog-views/sys-objects-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-objects-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@pmasl Pedro, can you please look at this issue? Thanks, Carl

**Comment by pmasl** [comment]
It's by design. I'll add the missing info. Thanks #please-close
