### ISSUE TITLE
smss intelligent suggestion is too bad

### ISSUE THREAD

**Issue by khoiphanngoc89** [MicrosoftDocs/sql-docs#4821]
smss intelligent suggestion is too bad. There are not suggestion when I typing sql query 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by WilliamAntonRohm** [comment]
@khoiphanngoc89 -- thank you for your feedback.  Please see this article:
- [Configure IntelliSense (SQL Server Management Studio)](https://docs.microsoft.com/sql/ssms/scripting/configure-intellisense-sql-server-management-studio)

You are welcome to add your concern here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
