### ISSUE TITLE
back slashes in front of most lines in the example XML file 

### ISSUE THREAD

**Issue by whudwl** [MicrosoftDocs/sql-docs#4822]
Seems the example XML files are ill formatted, for example one of them looks like this: 
![image](https://user-images.githubusercontent.com/2842789/82539079-22d1eb80-9b90-11ea-886a-d4de0cfbf558.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b3384ba-bb57-c651-d1e7-ebcb608c3170
* Version Independent ID: 7e8b85c3-70b6-8f55-8090-78021387d324
* Content: [Map table columns to data-file fields with a format file - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/use-a-format-file-to-map-table-columns-to-data-file-fields-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/import-export/use-a-format-file-to-map-table-columns-to-data-file-fields-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/use-a-format-file-to-map-table-columns-to-data-file-fields-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@whudwl -- David, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
