### ISSUE TITLE
syntax error  in source db name using copy to another server

### ISSUE THREAD

**Issue by Rutikhal** [MicrosoftDocs/sql-docs#4829]
Hi. I would like to copy db from one server to another and I am following this article using T-SQL
CREATE DATABASE db_copy AS COPY OF db.etl-jobs; and  Azure Data Studio and  SQL SMS complains with
"Incorrect syntax near '-'."
How I could copy db with when in name '-'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e8abfde-2523-5c70-bb95-b10101a726ff
* Version Independent ID: 3b8152d2-b49e-df4b-0f05-3ec52aa5bb71
* Content: [CREATE DATABASE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-transact-sql?view=azuresqldb-current#copy-a-database)
* Content Source: [docs/t-sql/statements/create-database-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-database-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@Rutikhal -- thank you for your question.  Please try enclosing the hyphenated name in [square brackets]:
`CREATE DATABASE db_copy AS COPY OF db.[etl-jobs];`

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by Rutikhal** [comment]
Thanks. Yes, now it works.

**Comment by WilliamAntonRohm** [comment]
@Rutikhal -- you're welcome, and glad we could help.
