### ISSUE TITLE
Environment variable name for password incorrect

### ISSUE THREAD

**Issue by ogsadmin** [MicrosoftDocs/sql-docs#4836]
The environment variable for passing the SA password in the docker run command should read MSSQL_SA_PASSWORD instead of SA_PASSWORD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6a10dd4-ef5f-f9a4-f4cb-36346ef183be
* Version Independent ID: 567e43d3-67dd-a771-fcd4-566c84b44dde
* Content: [Install on Docker - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-machine-learning-docker?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-setup-machine-learning-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-machine-learning-docker.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@ogsadmin -- he, thank you for spotting this.  I am looking into the article.

**Comment by WilliamAntonRohm** [comment]
@cawrites -- please review [private PR 15204](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15204).
