### ISSUE TITLE
Prerequisites show Docker for Windows as supported configuration - which is not correct 

### ISSUE THREAD

**Issue by ogsadmin** [MicrosoftDocs/sql-docs#4837]
Please remove Docker for Windows from the list of prerequisites - according to the discussion at https://github.com/MicrosoftDocs/sql-docs/issues/4742, SQL Server Machine Learning Services do only run on Docker for Ubuntu 16.04 (nothing else is a supported configuration).

Likely the same is true for Docker for Mac?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6a10dd4-ef5f-f9a4-f4cb-36346ef183be
* Version Independent ID: 567e43d3-67dd-a771-fcd4-566c84b44dde
* Content: [Install on Docker - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-machine-learning-docker?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-setup-machine-learning-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-machine-learning-docker.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by cawrites** [comment]
@ogsadmin I understand you are referring to the other issue that has been closed. It was identified that the specific server-based configuration you identified has not been that was tested. The documentation provides general guidance. You also reported error messages that were specifically related to your install, or an incomplete uninstall. To engage the product team to look at the specific configuration you are attempting to use, you need to ask someone within your organization to open a support ticket. The product team has the ability to track reported issues, once a support ticket has been created. Please contact support : https://www.microsoft.com/en-us/industry/services/support

**Comment by ogsadmin** [comment]
@cawrites, it was you who explained to me that Docker for Windows is not a supported configuration - if that is true, then please update the documentation accordingly. 

I have already found a solution for my initial issue and I now have a working setup - so I don't see the need to open a support case (and waste weeks going back and forth until somebody actually takes action - we've been through this a few times before). 

I was only trying to help, ...

Best regards!

**Comment by cawrites** [comment]
@ogsadmin I am glad you were able to work with a fellow contributor and find the solution you need. The team has access to all comments so no going back and forth is needed. Offering  support is an option we provide to all of the community but it is certainly not a requirement. 

My only ask at this point is to continue to work with your PR to keep the conversation single threaded for discovery purposes. Microsoft appreciates your support and we will work with the product team to apply whatever documentation updates are needed. 

We closed this thread so you can focus on updating just one. If you can support that effort it would be greatly appreciated.
