### ISSUE TITLE
SIN input type not specified.

### ISSUE THREAD

**Issue by GeneralTyres** [MicrosoftDocs/sql-docs#4839]
[Enter feedback here]
The document does not specify if the input should be in radians or degrees. From working with it now it seems that the input should be in radians.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6b8f2a0-f927-0082-13b7-5a045f424efb
* Version Independent ID: 5816dbd5-00c3-fd4e-e73c-2156b471dc22
* Content: [SIN (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/sin-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/sin-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/sin-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@GeneralTyres -- MarkusAfricanus, thank you for your feedback.  I believe you are correct and am looking into this article.

**Comment by GeneralTyres** [comment]
Awesome William, thanks for the feedback. Should I close the issue or can I leave that to you?

**Comment by WilliamAntonRohm** [comment]
@GeneralTyres -- you're welcome!  & poof it's done.
