### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by hecongy** [MicrosoftDocs/sql-docs#4843]
Did you miss a 'd' in the Note section?
This is the query plan that is store**d**  in the plan cache.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0255e0c3-6f50-a3c5-4ef0-7d93d597e9c9
* Version Independent ID: fd034f77-24f7-3455-5355-ddeb1ad38b21
* Content: [Execution Plans - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/execution-plans?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/execution-plans.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/execution-plans.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by hecongy** [comment]
PR here: https://github.com/MicrosoftDocs/sql-docs/pull/4844

**Comment by WilliamAntonRohm** [comment]
@hecongy -- cyhe, thank you for fixing this typo.  Your PR has been merged and the updated document will be live tomorrow.
