### ISSUE TITLE
SQL coloring is not correct; "(1 row(s) affected)" is not needed; Result sets are inconsistent.

### ISSUE THREAD

**Issue by Protiguous** [MicrosoftDocs/sql-docs#4849]
SQL coloring is not correct.
"(1 row(s) affected)" is not needed.
Result sets are inconsistently displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cdca663-134c-4929-bbcd-ffc44dea258c
* Version Independent ID: ce78de6c-e68d-7ddd-b364-675240142028
* Content: [RTRIM (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/rtrim-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/rtrim-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/rtrim-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@Protiguous -- thank you for your feedback.  I am looking into this article.
