### ISSUE TITLE
Bad rendering of Event Session States diagram in dark mode

### ISSUE THREAD

**Issue by nikolapeja6** [MicrosoftDocs/sql-docs#4854]
When the docs are in dark mode, this picture doesn't render that well and the writing is mostly illegible.

![image](https://user-images.githubusercontent.com/18459277/82908062-bc6e1400-9f67-11ea-99f8-1dcd4187619f.png)

For reference, the picture from the .md file looks like this.

![image](https://user-images.githubusercontent.com/18459277/82921656-ea0f8900-9f78-11ea-978a-a8fd94a20322.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64ee049a-7a49-fac0-5f03-d2424154a92c
* Version Independent ID: 507d468b-6a06-ba43-c730-b30c6b2d43be
* Content: [SQL Server Extended Events Sessions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/extended-events/sql-server-extended-events-sessions?view=sql-server-ver15)
* Content Source: [docs/relational-databases/extended-events/sql-server-extended-events-sessions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/extended-events/sql-server-extended-events-sessions.md)
* Product: **sql**
* Technology: **xevents**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
I am trying to fix this now, with PR 15122, in the private repo.

cc: @nikolapeja6

**Comment by MightyPen** [comment]
The fix works. The fix should be live on Docs on or before Thursday 2020/May/28.

@nikolapeja6 , thank you for bringing this error to our attention. We hope to hear from you again someday.

I am now Closing this Issue, as fixed.

G
