### ISSUE TITLE
Why we should not use SET FMTONLY?

### ISSUE THREAD

**Issue by pcelba** [MicrosoftDocs/sql-docs#4857]
SET FMTONLY ON is useful when we need to retrieve just the output data structure from SQL Server query. It can be processed in many languages w/o any adjustments.

Neither sp_describe_first_result_set nor the sys.dm_exec_describe_first_result_set provides the result set in required format.

Thanks
Pavel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09f6ac31-b642-7227-5a8c-c05994668481
* Version Independent ID: 3e24b694-754e-c12c-dfc0-655d06fa6bae
* Content: [SET FMTONLY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-fmtonly-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/set-fmtonly-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-fmtonly-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@pmasl Can you assist in directing this question to right person in the PG? Thanks.
Carl

**Comment by pmasl** [comment]
@CarlRabeler that would be me. 

@pcelba SET FMTONLY is deprecated as seen in https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-2017. By replacing FMTONLY with sp_describe_first_result_set, sp_describe_undeclared_parameters, sys.dm_exec_describe_first_result_set, or sys.dm_exec_describe_first_result_set_for_object, you'll have better quality results when comparing metadata:

These rules are used by the newer replacement:
- If column names differ, name is unknown (NULL).
- If nullability differs, assume is nullable.
- If data types differ, throw exception.

You can massage the format to meet your needs using T-SQL, or retrieve the results using SqlDataReader methods and massage it afterwards.

**Comment by pmasl** [comment]
#please-close

**Comment by pcelba** [comment]
OK, fortunately, "deprecated" does not mean "removed"...

Of course, the documentation could show how to code SET FMTONLY using the proposed replacements. I don't see any simple code which could be used instead of
`SET FMTONLY ON;`
`EXECUTE prc_gm29;   -- Returns multiple tables.`
`SET FMTONLY OFF;`

Thanks
Pavel

**Comment by pmasl** [comment]
@pcelba, yes it's not removed. But deprecated means "don't use this in new work, and plan to move away from it asap".
