### ISSUE TITLE
What is the Synapse equivalent of "FOR XML PATH"?

### ISSUE THREAD

**Issue by swanderz** [MicrosoftDocs/sql-docs#4861]
[This thread](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/e5a8f6eb-bb26-4784-bc67-a8f0408b6ce1/alternative-to-for-xml?forum=AzureSQLDataWarehouse) says that `FOR XML PATH()` is unsupported. However, I am not interested in loading XML data, rather using the `FOR XML PATH()` to create a list of executable sql statements.

On this page, you should link to the the [`STRING AGG` page](https://docs.microsoft.com/en-us/sql/t-sql/functions/string-agg-transact-sql?view=sql-server-ver15) and mention [this SO answer](https://stackoverflow.com/a/42778050/3842610)!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93bfe89b-671a-31fc-5d54-eda784b8dee2
* Version Independent ID: 64485144-9dbe-23e0-1db8-165ae3441a9c
* Content: [FOR XML (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/xml/for-xml-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/xml/for-xml-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/xml/for-xml-sql-server.md)
* Product: **sql**
* Technology: **xml**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@swanderz -- Anders, thank you for your thorough feedback.

@rothja -- Jason, please look into this issue.

**Comment by swanderz** [comment]
this is one small ask as part of #55713

**Comment by rothja** [comment]
@swanderz Thanks for the question. I'm going to ask @julieMSFT to take a look, as she works on the content for Azure Synapse Analytics. #reassign:julieMSFT. Thank you!

**Comment by PRMerger12** [comment]
julieMSFT. is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by julieMSFT** [comment]
@swanderz Hi Anders. Thank you for contacting Microsoft. I am looking into your comments.

**Comment by swanderz** [comment]
@julieMSFT I linked the wrong issue above. Here (https://github.com/MicrosoftDocs/azure-docs/issues/55713), I hint that `STRINGAGG()` is the answer.

**Comment by swanderz** [comment]
my high level SQL doc feedback is that while I appreciate that you've consolidated the T-SQL function ref across products to avoid duplication, I don't think this works for the persona that is trying to translate between TSQL implementations. I also opened this issue on the same topic. https://github.com/MicrosoftDocs/azure-docs/issues/55713 @WilliamAntonRohm 

I think using the analogy of offering an analogy of a language translation dictionary. Imagine I'm a Spanish speaker who is trying to learn how to say _biblioteca_ in English. So I google "biblioteca English" and am brought to a page that has this at the top.

> _biblioteca_ 
Spanish: ✔️ Italian: ✔️ English: ❌ 

At this point, I have nowhere to go next. And the presence of the English word is going to bring me to that entry even though `biblioteca` isn't a word in English.

This is the experience of someone trying to figure out how to develop in Synapse that is coming from SQL server. 

[FOR XML PATH (SQL SERVER)](https://docs.microsoft.com/en-us/sql/relational-databases/xml/for-xml-sql-server?view=sql-server-ver15)
<img width="899" alt="image" src="https://user-images.githubusercontent.com/8158673/85906978-dac46b00-b7c4-11ea-8ee2-3a66d9dd58ef.png">

**Comment by julieMSFT** [comment]
@swanderz  Thank you for providing more clarifying information. I do understand the issue. I have crated a work item to track this suggestion. I will close this issue but will let you know when we decide how to address  the concern you raise here. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#https://mseng.visualstudio.com/TechnicalContent/_boards/board/t/SQL/Stories/?workitem=1745082
