### ISSUE TITLE
sys.server_event_sessions mentioned on page not supported in Azure.

### ISSUE THREAD

**Issue by Kalamazoo-DBA** [MicrosoftDocs/sql-docs#4866]
"SELECT * FROM sys.server_event_sessions" is mentioned on the page yet is not supported in Azure.  Is there an alternate select for Azure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b79d736-c8b0-a460-501a-71c590092bc9
* Version Independent ID: f5c34ba9-0a5d-0af5-c4e5-c99d5572e6d5
* Content: [CREATE EVENT SESSION (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-event-session-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-event-session-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-event-session-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by Kalamazoo-DBA** [comment]
Found: 

https://docs.microsoft.com/en-us/sql/relational-databases/extended-events/manage-event-sessions-in-the-object-explorer?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@Kalamazoo-DBA -- thank you for your question & your answer.
