### ISSUE TITLE
sqlpackage Linux does not run on debian 10

### ISSUE THREAD

**Issue by yene** [MicrosoftDocs/sql-docs#4867]
Running sqlpackage on debian 10 gives me the error "No usable version of the libssl was found".
Some one said this is because its an old dot net core version that requires OpenSSL 1.0. Is it possible to fix this dependency?

Thank you for your time.

Linux .NET Core  | April 28, 2020 | 18.5 | 15.0.4769.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3df6af-9ac8-bc57-93dc-29ff713c1d3b
* Version Independent ID: 7624e2cc-7aa9-40dd-4015-3371ea2ea0a2
* Content: [Download and install sqlpackage - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-ver15)
* Content Source: [docs/tools/sqlpackage-download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage-download.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by WilliamAntonRohm** [comment]
@yene -- Yannick, thank you for your question.  Please add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by yene** [comment]
@WilliamAntonRohm thank you for the quick response, could you please forward this issue to the maintainers of sqlpackage.

Thank you

**Comment by WilliamAntonRohm** [comment]
@yene -- Yannick, please open this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

**Comment by sarvasana** [comment]
@yene and don't forget to post a link to your new issue, just in case somebody is running into the same error.

**Comment by funktionalsystems** [comment]
@yene @ sarvasana  I can't find the link at this second, but this issue was fixed in a point release within the past 2 months or so.

**Comment by sarvasana** [comment]
@yene thanks for the reply and sorry about my somewhat frustrated reply on this issue. I thought I ran into yet another dead end and thought...hell...lets comment on it and see if someone responds. Luckily you did and you are right!

The version sqlpackage-linux-x64-en-US-15.0.4897.1 on [docs.microsoft.com](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-ver15#get-sqlpackage-net-core-for-linux) works just fine.

I am on Manjaro and the package in the Arch User Repository is outdated and I will mark it as such right away.
