### ISSUE TITLE
What is the example C:\returnvalue.sql supposed to illustrate?

### ISSUE THREAD

**Issue by Mannigfaltigkeit** [MicrosoftDocs/sql-docs#4870]
Hi
I don't get the point of this example. All it does is return the value 100.
Thanks
Marcel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57bb7336-951e-cab7-522e-abb98e7f7a54
* Version Independent ID: 339664c0-7de2-720a-d28d-49e38288a240
* Content: [Use the sqlcmd Utility - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/scripting/sqlcmd-use-the-utility?redirectedfrom=MSDN&view=sql-server-ver15#running-transact-sql-script-files-using-sqlcmd)
* Content Source: [docs/ssms/scripting/sqlcmd-use-the-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/sqlcmd-use-the-utility.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@Mannigfaltigkeit -- thank you for your feedback.  Yes, `returnvalue.sql` only demonstrates how to set an exit code; the remainder of that example file was mistakenly copied from the subsequent example `windowsscript.bat`.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review [private PR 15205](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15205).
