### ISSUE TITLE
SQLGetInfo: Broken formatting of list of SQL_DBMS_VER and others

### ISSUE THREAD

**Issue by mloskot** [MicrosoftDocs/sql-docs#4871]
Formatting of the list of allowed arguments is broken, it is displayed as a single string:

![image](https://user-images.githubusercontent.com/80741/83174543-d439c980-a11a-11ea-8e77-3fce31e8d12c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dbecbff-a7d6-ec1f-86e6-75c29f1d1850
* Version Independent ID: ad74b783-407c-b0ce-1d01-9384b232c162
* Content: [SQLGetInfo Function - SQL Server](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetinfo-function?view=sql-server-ver15)
* Content Source: [docs/odbc/reference/syntax/sqlgetinfo-function.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/syntax/sqlgetinfo-function.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@mloskot -- Mateusz, thank you for your feedback.  I am looking into this article.

**Comment by David-Engel** [comment]
@mloskot @WilliamAntonRohm 

I fixed a lot of bad formatting on the page, including the DBMS Product Information section. It should look much better now.

**Comment by WilliamAntonRohm** [comment]
@David-Engel -- David, thank you for addressing this issue.

**Comment by mloskot** [comment]
@David-Engel Thank you!
