### ISSUE TITLE
SSO for Azure SQL Server database and Synapse DW

### ISSUE THREAD

**Issue by raunakjhawar** [MicrosoftDocs/sql-docs#4872]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14028139-b25b-f04c-0661-fbe81e6efe94
* Version Independent ID: 9cfc5b2a-39b0-4822-6ff3-a2cba7b97e21
* Content: [Service Principal Name (SPN) Support in Client Connections - SQL Server](https://docs.microsoft.com/en-us/sql/connect/oledb/features/service-principal-name-spn-support-in-client-connections?view=sql-server-ver15)
* Content Source: [docs/connect/oledb/features/service-principal-name-spn-support-in-client-connections.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/oledb/features/service-principal-name-spn-support-in-client-connections.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

As Azure SQL database and Synapse DW are managed PaaS offerings, how is this page relevant to show that SSO can be established using Kerberos. If not, please update tags on this page to show that this works with only SQL Server i.e. IaaS.

**Comment by WilliamAntonRohm** [comment]
@raunakjhawar -- Raunak, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@pmasl -- Pedro, please look into this issue.  If the answer is negative, I will create a PR to update the applicability.

**Comment by David-Engel** [comment]
@WilliamAntonRohm Confirmed. The page is only relevant to SQL Server.

Regards,
David

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
