### ISSUE TITLE
Documentation Error  for Azure Synapse SQL DW Update statement 

### ISSUE THREAD

**Issue by antoniosch** [MicrosoftDocs/sql-docs#4873]
Hello All
In the Update statement page (https://docs.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-ver15) at section AH. ANSI joins for update statement,  the sample has two errors that are not supported by Azure Synapse SQL DW. 

These are
INSERT INTO dbo.Table1 VALUES(1, 10.0), (1, 20.0);  
Returns 
Msg 103010, Level 16, State 1, Line 1
Parse error at line: 1, column: 39: Incorrect syntax near ','.
Correct statements are 
INSERT INTO dbo.Table1 VALUES(1, 10.0);  
INSERT INTO dbo.Table1 VALUES(1, 20.0);  

And the Update 
UPDATE dbo.Table2   
SET dbo.Table2.ColB = dbo.Table2.ColB + dbo.Table1.ColB  
FROM dbo.Table2   
    INNER JOIN dbo.Table1   
    ON (dbo.Table2.ColA = dbo.Table1.ColA);  
GO  
Returns 
Msg 104058, Level 16, State 1, Line 1
FROM clause in UPDATE and DELETE statements cannot contain subquery sources or joins.
Correct statement is
UPDATE dbo.Table2   
SET dbo.Table2.ColB = dbo.Table2.ColB + dbo.Table1.ColB  
FROM dbo.Table1  
WHERE dbo.Table2.ColA = dbo.Table1.ColA;  
GO  

Also the syntax of UPDATE Statement for Azure Synapse is wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc5aa35c-e2c9-1cce-0026-6aae93b30504
* Version Independent ID: 85e9daaa-2af1-95c6-8795-75976c36ccba
* Content: [UPDATE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/queries/update-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/update-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@antoniosch -- Antonios, thank you for your feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
@julieMSFT - Hey Julie, can you please take a look at this? Thanks!

**Comment by julieMSFT** [comment]
@antoniosch Hi Antonios, thank you for contacting Microsoft and bringing this to our attention. I have correct the syntax in the document. The join syntax you highlighted does work in the latest version of Azure Synapse (formerly SQL DW). Please run @@version to ensure you have a version greater than Microsoft Azure SQL Data Warehouse - 10.0.11115.0 May 16 2020 02:43:26 Copyright (c) Microsoft Corporation. To get the latest version, you can pause and resume, scale, or the latest version will be applied to your SQL pool during your next maintenance window. 

This new update syntax is not supported in Azure Synapse (workspaces preview).

I will go ahead and close this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
