### ISSUE TITLE
Issue step 5repro

### ISSUE THREAD

**Issue by Xellos000** [MicrosoftDocs/sql-docs#4876]
https://docs.microsoft.com/en-us/sql/relational-databases/replication/configure-distribution-availability-group?view=sql-server-ver15

Current eeor :

-- STEP 5 - Enable **SQLNode1** also as a Distributor
 :CONNECT SQLNODE2 EXEC sp_adddistributiondb @database = 'DistributionDB', @security_mode = 1; GO

Current fixed:

-- STEP 5 - Enable **SQLNode2** also as a Distributor 
:CONNECT SQLNODE2 EXEC sp_adddistributiondb @database = 'DistributionDB', @security_mode = 1; GO

**Comment by WilliamAntonRohm** [comment]
@Xellos000 -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
