### ISSUE TITLE
Create session example incorrect

### ISSUE THREAD

**Issue by ev2900** [MicrosoftDocs/sql-docs#4877]
The example for the [creating a spark session](https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata-bdc-spark-session?view=sql-server-ver15#examples) is incorrect. 

It should be `azdata bdc spark session create --session-kind pyspark` 

instead of `azdata spark session create --session-kind pyspark` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12185f75-ff28-ab8b-b161-900ea33c2e37
* Version Independent ID: e2bdf97e-18ce-bcb5-0329-3a8c7e621a2e
* Content: [azdata bdc spark session reference - SQL Server](https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata-bdc-spark-session?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/reference-azdata-bdc-spark-session.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/reference-azdata-bdc-spark-session.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@ev2900 -- Christopher, thank you for your feedback. I am looking into this article.

**Comment by ev2900** [comment]
@WilliamAntonRohm if this helps, please see this image. 

The first command I execute is the example currently listed in the documentation. As you can see if produces an error. 

The second command I execute is the edit suggested. It works correctly and creates a spark session.

![azdata bdc create session](https://user-images.githubusercontent.com/5414004/83361507-9675b480-a357-11ea-8bc5-b5e6d504f6bf.PNG)

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review [private PR 15208](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15208).
