### ISSUE TITLE
How to configure

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/sql-docs#4879]
This page says "When SQL Server is configured to use the Windows application log..."
Is this an optional setting? If so, how do you configure it? I'm not finding any other info in nearby docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af7f84da-929e-fc76-cdec-4a08578612e2
* Version Independent ID: 12985b4a-3673-a0be-2257-b73b5d699a06
* Content: [View the Windows application log (Windows) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/view-the-windows-application-log-windows-10?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/view-the-windows-application-log-windows-10.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/view-the-windows-application-log-windows-10.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by julieMSFT** [comment]
@dcbrown16 Hello and thank you for contacting Microsoft. SQL Serve by default sends events to the Windows application log. If you would like to log SQL Server Agent jobs to the Windows application log see https://docs.microsoft.com/en-us/sql/ssms/agent/write-the-job-status-to-the-windows-application-log?view=sql-server-ver15. Please let me know if you have further questions.

**Comment by julieMSFT** [comment]
@dcbrown16 Hello, I will proceed with closing this issue. If further communication is needed, the @notification mechanism continues to work even after an item is closed. Thank you for your contribution to Microsoft docs! We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
