### ISSUE TITLE
Grammatical issue

### ISSUE THREAD

**Issue by jons-aura** [MicrosoftDocs/sql-docs#4885]
This sentence seems to be missing a portion around "to for the"
" You can update data in the current table from the history table to for the "oops" scenario. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6bd9289-f5fc-c084-fac8-92024f35f9c5
* Version Independent ID: 47bc2199-497a-3421-b0f9-ca9afa67e0a3
* Content: [Modifying Data in a System-Versioned Temporal Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/modifying-data-in-a-system-versioned-temporal-table?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/modifying-data-in-a-system-versioned-temporal-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/modifying-data-in-a-system-versioned-temporal-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@jons-aura -- thank you for your feedback. I am looking into this article.

**Comment by CarlRabeler** [comment]
@jons-aura @WilliamAntonRohm I concur - please fix grammatical error

**Comment by WilliamAntonRohm** [comment]
@CarlRabeler -- Carl, please review [private PR 15237](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15237).
