### ISSUE TITLE
Add position of the substring into the result table of the STRING_SPLIT function

### ISSUE THREAD

**Issue by mmichtch** [MicrosoftDocs/sql-docs#4888]
I would be extremely useful if result of the function will include position of the substring as in this exmple:

`SELECT value FROM STRING_SPLIT('Lorem ipsum dolor sit amet.', ' ');`

position | value
------ | ------
0 | Lorem
1 | ipsum
2 | dolor
3 | sit
4 | amet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77b3e27b-a3ee-da83-1d41-1fafd96228cb
* Version Independent ID: cc43ad4b-92ac-477f-a92d-1487c82ebe70
* Content: [STRING_SPLIT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/string-split-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/string-split-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/string-split-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by julieMSFT** [comment]
assign:julieMSFT

**Comment by mmichtch** [comment]
this is the business case:
I need to parse a string '$GNGGA,195020.011,4915.9412,N,12244.3999,W,0,0,,-4.8,M,-16.7,M,,*40' and get substring 7. to do this I am using this:

```
declare
	@Gga nvarchar(300) = '$GNGGA,195020.011,4915.9412,N,12244.3999,W,0,0,,-4.8,M,-16.7,M,,*40',
	@GpsFixQuality nchar(1)

select @GpsFixQuality = SUBSTRING(Gga,(SELECT SUM(LEN(value)) FROM (SELECT top 6 value FROM STRING_SPLIT(Gga,',')) GgaSplit)+7, 1)
```
when I should be able to do this:

```
SELECT @GpsFixQuality = value FROM STRING_SPLIT(Gga,',') 
WHERE position = 6 /* for 0 based index*/
```

**Comment by julieMSFT** [comment]
@mmichtch Hello, thank you for contacting Microsoft. I understand that you would like an improvement to the split_string function. Unfortunately, this form of contact is intended explicitly for reporting issues with the documentation, and not for the product.

You can try this:
SELECT ROW_NUMBER() OVER (ORDER BY value ASC)  AS No, value FROM STRING_SPLIT('Lorem ipsum dolor sit amet.', ' ');

If you're looking to provide suggestions or ideas for improvement for the product,  you can do so at https://aka.ms/sqlfeedback.

I will proceed with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close

**Comment by mmichtch** [comment]
this will not work, because I need to retrieve substring by positional number and not by sorted order.
