### ISSUE TITLE
odbcsql.cpp example has a build error and is incomplete

### ISSUE THREAD

**Issue by kalakshm** [MicrosoftDocs/sql-docs#4889]
1. Under wmain, this code does not compile because you cannot assign the value in the way that it is done under the else condition.
`if (argc > 1) 
    { 
        pwszConnStr = *++argv; 
    }  
    else 
    { 
        pwszConnStr = L""; 
    } `

2. The sample code under odbcsql.cpp is a missing closing brace right at the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac828919-7780-c626-d071-724e0cbc5d56
* Version Independent ID: 47d85824-56f3-9fa1-4348-30c864bc756b
* Content: [C++ ODBC app accessing a SQL database - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/cpp-code-example-app-connect-access-sql-db?view=sql-server-ver15#a-readmetxt)
* Content Source: [docs/connect/odbc/cpp-code-example-app-connect-access-sql-db.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/cpp-code-example-app-connect-access-sql-db.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@kalakshm Thanks for the feedback.

@v-makouz Can you take a look at this?

Thanks,
David

**Comment by David-Engel** [comment]
@v-zhangw Can you take a look at this?

Thanks,
David

**Comment by v-zhangw** [comment]
Currently being addressed.

**Comment by David-Engel** [comment]
The code sample has been fixed and brought up-to-date.

#please-close
