### ISSUE TITLE
geography barely mentioned

### ISSUE THREAD

**Issue by DickBaker** [MicrosoftDocs/sql-docs#4890]
the Geography gets a scant mention before Geometry and all 4 examples A-D are of Geometry.

Should mention the useful Well-Known Text (WKT) and float functions, e.g.
declare	@pt1 geography = geography::STGeomFromText('POINT(50.4750671 -1.5165396)', 4326),
		@pt2 geography = geography::Point(1.293561, 51.868143, 4326)
select	@pt1.STDistance(@pt2) as A, @pt2.STDistance(@pt1) as B

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 359226f6-b858-ffab-59ac-474e43381fd3
* Version Independent ID: 0b8aaaa0-a09a-c72d-eb08-963d631aaec9
* Content: [Point - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/point?view=sql-server-ver15)
* Content Source: [docs/relational-databases/spatial/point.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/spatial/point.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by DickBaker** [comment]
add another (sorry I missed first entry)
declare @pt3 geography = geography::STPointFromText('POINT(50.4750671 -1.5165396)', 4326)

**Comment by WilliamAntonRohm** [comment]
@DickBaker -- Dick, thank you for your feedback.

@MladjoA -- Mladen, please look into this issue.

**Comment by rothja** [comment]
@MladjoA Mladen, could you look at this suggestion? Should we add more of these geography examples now or track this for a future improvement. @DickBaker thank you for the suggestion and apologies for the delay.

**Comment by rwestMSFT** [comment]
@DickBaker We're revisiting older open issues, and I wanted to ask if you'd be interested in opening a pull request that includes the geography examples you mentioned. Even if it isn't perfect, it'll get this enhancement ahead in the queue.

**Comment by DickBaker** [comment]
@rwestMSFT thanks Randolph I'll pass as think ano likely more proficient than me on GIS etc

**Comment by rwestMSFT** [comment]
Closing this issue and adding it to our backlog.
