### ISSUE TITLE
Need an error message limitation (512 bytes) for bcp utility

### ISSUE THREAD

**Issue by mufukuha** [MicrosoftDocs/sql-docs#4893]
The [bcp utility](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver15) has a limitation that the error message shows only 512-byte characters. We need a description about that limitation in the [Remarks](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver15#remarks) section, such as "Only the first 512 bytes of the error message are displayed. "

For example, if the error 5304 occurs, if you have a long database name or table name, the end of the error message may be cut off.
```
>bcp db0123456789012345678901234567890123456789012345678901234567890123456789.dbo.table0123456789012345678901234567890123456789012345678901234567890123456789 IN D:\BCP\table.bcp -U *** -P *** -c -t, -S ***

Starting copy...
SQLState = 37000, NativeError = 5304
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Bulk copy failed. User does not have ALTER TABLE permission on table 'db0123456789012345678901234567890123456789012345678901234567890123456789.dbo.table0123456789012345678901234567890123456789012345678901234567890123456789'. ALTER TABLE permission is required on the target table of a bulk copy operation if the table has triggers or check constraints, but 'FIRE_TRIGGERS' or 'CHECK_CONSTRAINTS' bulk hints are not specified as options to the bulk copy comm

0 rows copied.
Network packet size (bytes): 4096
Clock Time (ms.) Total     : 1
```
The error message is supposed to be:
> Bulk copy failed. User does not have ALTER TABLE permission on table '%.*ls'. ALTER TABLE permission is required on the target table of a bulk copy operation if the table has triggers or check constraints, but 'FIRE_TRIGGERS' or 'CHECK_CONSTRAINTS' bulk hints are not specified as options to the bulk copy **command.**

This example is not very common, but this issue is likely to happen in Linux, which uses UTF-8 with 2byte characters or 3byte characters.

**Comment by WilliamAntonRohm** [comment]
@mufukuha -- Munenori, thank you for your feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@mufukuha 
Added a new considerations and limitations section in the BCP utility article.

Expect updates to show live by the end of the week.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
