### ISSUE TITLE
Syntax error on azdata bdc hdfs ls example

### ISSUE THREAD

**Issue by ev2900** [MicrosoftDocs/sql-docs#4894]
The example for the [listing the content of a directory](https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata-bdc-hdfs?view=sql-server-ver15#examples-1) on HDFS is incorrect.
 
It should be `azdata bdc hdfs ls --path "tmp/"`

instead of `azdata bdc hdfs ls --path '/tmp'`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 139a38a8-f227-24a0-136f-4a3567783a3b
* Version Independent ID: b3dadd7c-6b82-3d72-0e94-d5c335a0f286
* Content: [azdata bdc hdfs reference - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/reference-azdata-bdc-hdfs?view=sql-server-ver15#azdata-bdc-hdfs-ls)
* Content Source: [docs/big-data-cluster/reference-azdata-bdc-hdfs.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/reference-azdata-bdc-hdfs.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by ev2900** [comment]
If it helps please see the image below.

The first command I execute is the example currently listed in the documentation. As you can see if produces an error.

The second command I execute is the edit suggested. It works correctly and list the content of the tmp directory.

![Syntax error on azdata bdc hdfs ls](https://user-images.githubusercontent.com/5414004/83363019-fd996600-a363-11ea-8554-6187ca40713c.PNG)

**Comment by WilliamAntonRohm** [comment]
@ev2900 -- Christopher, thank you for you feedback.  I am looking into this article.

**Comment by MikeRayMSFT** [comment]
Hi @ev2900 thanks for pointing this out. 

The samples are written to run in various terminals. In this case a bash shell uses single quotes while command prompt uses double quotes. I see a couple other problems though. I'm going to keep this item open for  a bit while we look into it.

Appreciate you mentioning it.

Mike

**Comment by MikeRayMSFT** [comment]
Hi @ev2900 - just FYI, I'm still trying to fix this at the root.

**Comment by ev2900** [comment]
Ok @MikeRayMSFT

**Comment by MikeRayMSFT** [comment]
We did a bulk update of the reference content when we shipped SQL Server 2019 CU6. I was waiting for that to publish before addressing. I see the example hasn't changed. I *think* there's a dependency on the console. The example works as written in bash but the change is needed for Command Prompt. Verifying. 

mike

**Comment by MikeRayMSFT** [comment]
I've confirmed that the example runs in bash as written. I can't update the docs at this level because they're built from source code. Any manual update will eventually be overwritten. I'm working with the engineers on a way to note this in the docs. Thanks for submitting the issue.
