### ISSUE TITLE
What provider to use for accessing Excel files via automated processes? 

### ISSUE THREAD

**Issue by benjaminselby** [MicrosoftDocs/sql-docs#4897]
You state: 

"The ACE provider (formerly the Jet provider) that connects to Excel data sources is intended for interactive client-side use. If you use the ACE provider on SQL Server, especially in automated processes or processes running in parallel, you may see unexpected results." 

So, what provider SHOULD we use for automated processes then? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6257880-5f84-8ab4-29e0-cf9e1e130b76
* Version Independent ID: 47351d7f-29eb-298e-9a75-7bf8c3e648ca
* Content: [Import data from Excel to SQL - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/import-data-from-excel-to-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/import-export/import-data-from-excel-to-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/import-data-from-excel-to-sql.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by VanMSFT** [comment]
Server side automation is not supported for Excel. Please see the following for some considerations: https://support.microsoft.com/en-us/help/257757/considerations-for-server-side-automation-of-office

You can still use the ACE Provider, but you might run into various issues stated above.
