### ISSUE TITLE
Where is the Test scripts folder? 

### ISSUE THREAD

**Issue by cosmoKenney** [MicrosoftDocs/sql-docs#4901]
Can't find the test scripts folder mentioned in the documentation. And there is no Test.sql file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c697524f-08a8-b961-a673-d93a92e7a13a
* Version Independent ID: b16d93e1-709f-e7b5-2928-9e12d2756cf8
* Content: [Debugging CLR Database Objects - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/debugging-clr-database-objects?view=sql-server-ver15)
* Content Source: [docs/relational-databases/clr-integration/debugging-clr-database-objects.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/clr-integration/debugging-clr-database-objects.md)
* Product: **sql**
* Technology: **clr**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by cosmoKenney** [comment]
@WilliamAntonRohm I'm sorry, but the documentation says there are folders and files in a CLR stored procedure project that don't get created by Visual Sudio 2019's new item template. So this issue is not a coding issue for Stack Exchange/Overflow. I believe the documentation is wrong.

**Comment by WilliamAntonRohm** [comment]
@cosmoKenney -- Ken, thank you for clarifying.

@rothja -- Jason, please look into this issue.

**Comment by rothja** [comment]
@cosmoKenney I agree the documentation needs work here. Sorry for the confusion. I think it was written for previous versions of Visual Studio and no longer behaves the same in current versions. I will try to see what the new process should be. Thanks for your patience.

**Comment by rothja** [comment]
@cosmoKenney I'm still trying to find the correct steps for updating the doc. Were you able to find a way to accomplish this with community threads/blogs online? Are you still stuck trying to debug your object? Thanks!

**Comment by cosmoKenney** [comment]
@rothja 
uh, i've gotten past this issue. But I don't recall exactly how. I think I changed a setting in the project that explicitly set the test sql script. Which enabled me to do normal F5 debugging.

**Comment by rothja** [comment]
@cosmoKenney Yes, sorry for the long delay and for having to find the answer yourself. I would still like to find a better update for the doc to avoid the confusion. I'll be looking into this more, but I'm glad you're not blocked. Thank you!

**Comment by rothja** [comment]
@cosmoKenney Thanks for your patience. Here are the updated steps that I'm adding to the article today. I hope this helps. Thanks!

## Debugging steps

Use the following steps to debug a CLR database object in Microsoft Visual Studio:

1. Open Microsoft Visual Studio, and create a new SQL Server project. You can use the SQL LocalDB instance that comes with Visual Studio.

2. Create a new SQL CLR type (C#):

   - In **Solution Explorer**, right-click the project, and select **Add**, **New Item...**. 
   - From the **Add New Item** window, select **SQL CLR C# Stored Procedure**, **SQL CLR C# User-Defined Function**, **SQL CLR C# User-Defined Type**, **SQL CLR C# Trigger**, **SQL CLR C# Aggregate**, or **Class**.
   - Specify a name for the source file of the new type, and then select **Add**.

3. Add code for the new type to the text editor. For sample code for an example stored procedure, see the following Example section in this article.

4. Add a script that tests the type: 

   - In **Solution Explorer**, right-click on the project node and select **Add**, **Script...**. 
   - In the **Add New Item** window, select **Script (Not in build)**, and specify a name, such as `Test.sql`. Select the **Add** button.
   - In **Solution Explorer**, double-click the `Test.sql` node to open the default test script source file.
   - Add the test script (one that invokes the code to be debugged) to the text editor. See the example in the next section for a sample script.

5. Place one or more breakpoints in the source code. Right-click on a line of code in the text editor on the function or routine that you want to debug. Select **Breakpoint**, **Insert Breakpoint**. The breakpoint is added, highlighting the line of code in red.

6. In the **Debug** menu, select **Start Debugging** to compile, deploy, and test the project. The test script in `Test.sql` is run, and the managed database object is invoked.

7. When the yellow arrow (designating the instruction pointer) appears at the breakpoint, code execution pauses. You can then debug your managed database object:

   - Use **Step Over** from the **Debug** menu to advance the instruction pointer to the next line of code.
   - Use the **Locals** window to observe the state of the objects currently highlighted by the instruction pointer.
   - Add variables to the **Watch** window. You can observe the state of watched variables throughout the debugging session, even when the variable is not at the line of code currently highlighted by the instruction pointer. 
   - Select **Continue** from the **Debug** menu to advance the instruction pointer to the next breakpoint or to complete execution of the routine if there are no more breakpoints.
