### ISSUE TITLE
Non-consistent blue SQL keywords. Extra fluff in results shown.

### ISSUE THREAD

**Issue by Protiguous** [MicrosoftDocs/sql-docs#4906]
Under the section "Fractional seconds" in the SQL example, both "millisecond" and "nanosecond" should be blue to be consistent.

Under the section "Examples":
 In the 1st example SQL, there is an unneeded "*/".

 In the 4th example SQL, the "SELECT TOP(1) DATEPART (year,'12/20/1974') FROM dbo.DimCustomer;" can be rewritten as "SELECT DATEPART(year,'12/20/1974');" as there are no columns used in the FROM clause. This would also make the comment "-- Uses AdventureWorks" unneeded.

Also, examples 3 & 5 do not need the "--------" above the result.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1c1cb1-feb7-d2d1-9b9f-6b3f8caff8d6
* Version Independent ID: c6caa07c-fb64-31e9-ed4f-36e367dfbaeb
* Content: [DATEPART (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/datepart-transact-sql?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(datepart_TSQL);k(sql13.swb.tsqlresults.f1);k(sql13.swb.tsqlquery.f1);k(DevLang-TSQL)%26rd%3Dtrue&view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/datepart-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/datepart-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@Protiguous -- thank you for your keen eye.  I am looking into this article.

**Comment by Protiguous** [comment]
You are welcome! I like to think that I'm helping.
Now.. How can I get paid to edit these pages myself? Haha! (hmm..)

If notifying your editors of these when I come across them is *not *annoying,
shall I keep sending in notifications?

**Comment by WilliamAntonRohm** [comment]
@Protiguous -- you are welcome to send in anything you find!

**Comment by julieMSFT** [comment]
@Protiguous When you're suggesting a simple change to the documentation,  it may be faster for you to submit the edit yourself via a Pull Request (PR). You can do so by following these steps:
1. Navigate to the page of interest 
2. Select the "Edit" button at the top right of the page 
3. Select the "Pencil" icon on the right 
4. Modify the text within the text box in [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) format 
5. Name your file change and copy the link to your Git Issue into the "extended description" box 
6. Select "Propose file change" 
7. Select "Create pull request" on the 'Comparing changes' page 
8. Select "Create pull request" on the 'Open a pull request' page 
9. Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing so will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and list you as a contributor to the documentation.

Thanks again for your submission!

**Comment by WilliamAntonRohm** [comment]
@Protiguous -- I've tidied up the examples per your suggestions, except:
- For the blue inconsistency, you have uncovered a possible bug in the SQL code formatter.
- I think the 4th and 5th examples are designed to show more context.

Thank you for your feedback!
