### ISSUE TITLE
The SQL examples A and B are not color-coded.

### ISSUE THREAD

**Issue by Protiguous** [MicrosoftDocs/sql-docs#4907]
The SQL examples A and B are not color-coded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277a5d00-6fcf-a830-0451-f0667dd806e8
* Version Independent ID: ac998a63-0675-de0c-c528-4b355c1d9d5f
* Content: [EOMONTH (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/eomonth-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/eomonth-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/eomonth-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by julieMSFT** [comment]
#assign:julieMSFT

**Comment by julieMSFT** [comment]
@Protiguous Hello and thank you for contacting Microsoft. I have updated the document and you should see it later today. I will proceed with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#https://github.com/MicrosoftDocs/sql-docs-pr/pull/15254

**Comment by julieMSFT** [comment]
#plese-close
