### ISSUE TITLE
Illustration missing

### ISSUE THREAD

**Issue by bkline** [MicrosoftDocs/sql-docs#4909]
The page ends "The next illustration ..." but that illustration is not provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8606c200-380e-6d26-379d-3d948f4a03b2
* Version Independent ID: db53b0b2-7ee0-6f5b-fb76-48521d9c66e1
* Content: [Dynamic SQL - SQL Server](https://docs.microsoft.com/en-us/sql/odbc/reference/dynamic-sql?view=sql-server-ver15)
* Content Source: [docs/odbc/reference/dynamic-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/dynamic-sql.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@bkline -- Bob, thank you for bringing this to our attention.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
I searched as far back as I could but it appears there was never any illustration. So I removed the last sentence. The change should be visible in tomorrow morning's doc publish.

Thanks,
David

#please-close
