### ISSUE TITLE
Typos in Example D

### ISSUE THREAD

**Issue by cranstol** [MicrosoftDocs/sql-docs#4912]
LEAD(Sale sAmountQuota,1,0)

Column SalesAmountQuote should not have a space in it.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da87abf6-d598-f63d-3337-c7423770235b
* Version Independent ID: c88e4e6e-982c-dc13-d9b8-b513deee6732
* Content: [LEAD (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/lead-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/lead-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/lead-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@cranstol -- James, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
