### ISSUE TITLE
First sentence of Remarks block doesn't make sense

### ISSUE THREAD

**Issue by bkline** [MicrosoftDocs/sql-docs#4913]
> Unicode functions that always return or take strings or length arguments are passed as count-of-characters.

This sentence needs to be rewritten so that it's clear what is being passed as count-of-characters. As it is written, it's saying that the functions are passed as count-of-characters, which is nonsense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8021345e-7a84-e71d-2182-5cf67b924721
* Version Independent ID: bb8f3a6f-55ed-21fe-6ea4-77c52c51b51e
* Content: [Unicode Function Arguments - SQL Server](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/unicode-function-arguments?view=sql-server-ver15)
* Content Source: [docs/odbc/reference/develop-app/unicode-function-arguments.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/develop-app/unicode-function-arguments.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@bkline -- Bob, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@David-Engel -- David, please review [private PR 15313](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15313).

**Comment by David-Engel** [comment]
@WilliamAntonRohm Done. Looks good to me.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

**Comment by bkline** [comment]
Super, thanks!
