### ISSUE TITLE
Confusing requirement for output buffer

### ISSUE THREAD

**Issue by bkline** [MicrosoftDocs/sql-docs#4914]
> BufferLength
[Input] Length of *CursorName, in characters. If the value in *CursorName is a Unicode string (when calling SQLGetCursorNameW), the BufferLength argument must be an even number.

Since, as is made clear elsewhere in the Microsoft ODBC documentation, the driver is required to append the null terminator character at the end of the returned string value, and since the values returned by `SQLGetInfo()` for maximum lengths (including for cursor names) are usually (if not always) even numbers, and since the caller is required to provide space in the buffer for the null terminator character, wouldn't it be more sensible for the buffer length (again, in _characters_) to be an _odd_ number? It's almost as if the person writing the description quoted above forgot for a moment that the length isn't in bytes but in characters, and that the number of bytes, for an array of `SQLWCHAR` will _always_ be even by definition. If there really were a need for the number of *character* positions in the buffer to be even, for some reason which the writer of the documentation is unwilling to divulge, why wouldn't this requirement apply to both `SQLWCHAR*` values _and_ `SQLCHAR*` values? It seems likely that the only effect of this misleading sentence (aside from wasting a tiny bit of unnecessary space) would be to lead the programmer reading this documentation to wonder, "hmm, I wonder if they mean `char` (meaning byte) when they say _character_ here?" If there really is a reason why the size of the buffer _in characters_ needs to be even for one type of string but not for the other, it would help significantly to avoid that sort of confusion if the documentation were to state explicitly what that reason is. Even if that means writing something like "requiring the buffer size _in characters_ to be even for `SQLWCHAR` strings but not for `SQLCHAR` strings was a misguided requirement, but that requirement can't be changed now because of the risk that a driver implementation exists which relies on that constraint."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f8568d8-d69d-6982-1f46-5ef8831c3dfe
* Version Independent ID: 7b4787e0-b18c-d30f-1b3d-452038a14327
* Content: [SQLGetCursorName Function - SQL Server](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetcursorname-function?view=sql-server-ver15)
* Content Source: [docs/odbc/reference/syntax/sqlgetcursorname-function.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/syntax/sqlgetcursorname-function.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@bkline -- Bob, thank you for your feedback.

@David-Engel -- David, please look into this issue.

**Comment by v-chojas** [comment]
The second sentence should be removed, since this is referring to a function argument which is always a string, and the count is in characters.

See here for more information: https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/unicode-function-arguments?view=sql-server-ver15

**Comment by David-Engel** [comment]
The page has been updated to simply say:

BufferLength
[Input] Length of *CursorName, in characters.

#please-close
