### ISSUE TITLE
Figure on the page looks distorted

### ISSUE THREAD

**Issue by mpolena** [MicrosoftDocs/sql-docs#4915]
Figure on the page, although it renders well here, looks distorted on both chrome and safari: 
https://docs.microsoft.com/en-us/sql/relational-databases/import-export/use-a-format-file-to-skip-a-table-column-sql-server?view=sql-server-ver15

The text is unreadable.
[
![image](https://user-images.githubusercontent.com/3845622/83798866-81a46400-a66a-11ea-8542-d7217724e40e.png)
](url)

**Comment by WilliamAntonRohm** [comment]
@mpolena -- thank you for your feedback.  On my Windows 10 machine, the image appears fine in both Edge & Chrome.  Safari is no longer supported for Windows.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by mpolena** [comment]
@WilliamAntonRohm thanks for the prompt response.  I failed to mention that I was viewing the page on a Mac.
