### ISSUE TITLE
Where are we supposed to file bug reports related to DacFX?

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/sql-docs#4919]
UserVoice is a black hole of "if it's not upvoted it's ignored".

https://github.com/microsoft/DACExtensions/issues has not received Microsoft employee feedback in over 3 years.

Where should these issues be directed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 121d051e-9962-0554-b11d-ba22c1802ff7
* Version Independent ID: 3fc25a21-a2b1-8d06-2ba2-373112e004ef
* Content: [DacFx and SqlPackage release notes - SQL Server](https://docs.microsoft.com/en-us/sql/tools/release-notes-sqlpackage?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/release-notes-sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/release-notes-sqlpackage.md)
* Product: **sql**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by WilliamAntonRohm** [comment]
@IanKemp -- Ian, thank you for your question.  Please consider adding your issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

cc @pensivebrian for awareness

**Comment by pensivebrian** [comment]
@IanKemp - You can also use https://developercommunity.visualstudio.com and file the issue against SSDT. The DacFx team monitors this queue for issues that are DacFx specific.
