### ISSUE TITLE
The docs for dbcc tracestatus (-1) seem inaccurate

### ISSUE THREAD

**Issue by shueybubbles** [MicrosoftDocs/sql-docs#4920]
```TSQL
dbcc traceon (1800)
dbcc tracestatus (-1)
```
According to the doc, the tracestatus call should only return flags where Global = 1.
But it returns this:
```
TraceFlag Status Global Session
--------- ------ ------ -------
124       1      1      0
1800      1      0      1
4631      1      1      0
11100     1      1      0
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c899fb63-ed2a-e421-e0b1-54185aeafe8d
* Version Independent ID: 4292074a-42c5-cd9c-147d-d12d050e3994
* Content: [DBCC TRACESTATUS (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-tracestatus-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/database-console-commands/dbcc-tracestatus-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/database-console-commands/dbcc-tracestatus-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **umajay**

**Comment by WilliamAntonRohm** [comment]
@shueybubbles -- David, thank you for your feedback.

@pmasl -- Pedro, please look into this issue.

**Comment by rothja** [comment]
@pmasl Could you take a look at this and see if we need to update the docs. Thank you!

**Comment by MikeRayMSFT** [comment]
@shueybubbles  -  David, thanks for the submission. A minor doc update is in flight.
