### ISSUE TITLE
The SQL in Section C needs fixed.

### ISSUE THREAD

**Issue by Protiguous** [MicrosoftDocs/sql-docs#4921]
The SQL in Section C, "Using FORMATMESSAGE with THROW" is not formatted correctly and not colored correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525698d4-0465-5fe0-f09d-dfad8b8413e6
* Version Independent ID: 2ece841a-2d51-542e-6c2b-9d36ffe54202
* Content: [THROW (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/throw-transact-sql?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(throw_TSQL)%3Bk(sql13.swb.tsqlresults.f1)%3Bk(sql13.swb.tsqlquery.f1)%3Bk(DevLang-TSQL)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=sql-server-ver15#c-using-formatmessage-with-throw)
* Content Source: [docs/t-sql/language-elements/throw-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/throw-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@Protiguous -- thank you for catching that.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@Protiguous -- I fixed the indentation, and I believe the SQL itself is correct.  The coloring is still off and I am following up on that internally.
