### ISSUE TITLE
Example needed here

### ISSUE THREAD

**Issue by openStove** [MicrosoftDocs/sql-docs#4922]
In the documentation for flattening, you are showing the source data, and describe what will be the output, but I'm missing an example form how the external tables are needed to be configured for that... Not only describe it, but providing a concrete example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abe9b545-6797-9f77-7b8a-76b1b344e0fd
* Version Independent ID: 56e98c50-3f4f-df1e-ee9b-8a07cd860204
* Content: [Access external data: MongoDB - PolyBase - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-configure-mongodb?view=sql-server-ver15)
* Content Source: [docs/relational-databases/polybase/polybase-configure-mongodb.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-mongodb.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
Thank you for the suggestion, @openStove 
@uc-msft - can you help here?

**Comment by MikeRayMSFT** [comment]
@rajmera3 - would you have input for this?

**Comment by MikeRayMSFT** [comment]
@openStove - still working to get you a solid example. Thanks.
