### ISSUE TITLE
SQL in Sections A, B, and C are not colored.

### ISSUE THREAD

**Issue by Protiguous** [MicrosoftDocs/sql-docs#4923]
The SQL in Sections A, B, and C are not colored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a768b81-c094-3a48-a8d5-0697ce6b78d7
* Version Independent ID: 65ae8973-f433-a826-d779-4ac4feb54f1c
* Content: [FORMATMESSAGE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/formatmessage-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/formatmessage-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/formatmessage-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@Protiguous -- so noted!  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@Protiguous -- thank you.  They are now, and will be live shortly.
