### ISSUE TITLE
Please update the documentation to reflect that this feature currently is extremely error prone, upon opening existing diagrams

### ISSUE THREAD

**Issue by noontz** [MicrosoftDocs/sql-docs#4924]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8bc803d-3aee-0e1f-ab64-31c5af48e9f9
* Version Independent ID: 472fcb4b-39c3-72a3-d2af-4eba68b72f04
* Content: [Create a New Database Diagram - Visual Database Tools](https://docs.microsoft.com/en-us/sql/ssms/visual-db-tools/create-a-new-database-diagram-visual-database-tools?view=sql-server-ver15)
* Content Source: [docs/ssms/visual-db-tools/create-a-new-database-diagram-visual-database-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/visual-db-tools/create-a-new-database-diagram-visual-database-tools.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@noontz -- Steffen, thank you for your feedback.  Please add it here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
