### ISSUE TITLE
Specify port syntax

### ISSUE THREAD

**Issue by SheepRock** [MicrosoftDocs/sql-docs#4925]
The page should present how to specify a port other than the default to connect. 

It could, for example, in the "_Server name_" row of the table says something like "_Enter the name of the target Linux SQL Server machine or its IP address and port, in the format **IP,port**._"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44db5687-5102-dea4-b7b3-f088cdf57457
* Version Independent ID: b8d4cdad-8b18-2eea-415d-97f6048535af
* Content: [Use SSMS to Manage SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-manage-ssms?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-manage-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-manage-ssms.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@SheepRock -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- please review [private PR 15457](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15457).
