### ISSUE TITLE
FIELD ID property and COLUMN SOURCE property have to be number?

### ISSUE THREAD

**Issue by bestickley** [MicrosoftDocs/sql-docs#4926]
All of the examples have the FIELD ID property being a number that increase for each FIELD tag. Example:
```
<FIELD ID="1" .../>
<FIELD ID="2" .../>
```

Is it ok if I use a string/text that better describes the column?

```
<FIELD ID="FirstName" .../>
<FIELD ID="LastName" .../>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3d260a6-975c-b738-9907-7480f1a9f79e
* Version Independent ID: 28939f55-94c8-e305-95ff-1f023eb33a23
* Content: [Use a Format File to Skip a Table Column (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/use-a-format-file-to-skip-a-table-column-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/import-export/use-a-format-file-to-skip-a-table-column-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/use-a-format-file-to-skip-a-table-column-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@bestickley -- Ben, thank you for your question.  According to my research, string values are allowed for ID.  Please let me know if you find otherwise.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

cc @MashaMSFT for awareness
