### ISSUE TITLE
 result_cache_hit is returned as a decimal

### ISSUE THREAD

**Issue by markprycemaher** [MicrosoftDocs/sql-docs#4930]
The value of result_cache_hit in the DMV is Decimal, but the value in the table is Hex.
It would be useful to have the decimal value in the table as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073a14b1-1a4b-6da7-4c45-16bbdd0e7bf9
* Version Independent ID: d593d8af-ecd4-c2f7-b1ab-ce0e256bf82d
* Content: [sys.dm_pdw_exec_requests (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-pdw-exec-requests-transact-sql?view=aps-pdw-2016-au7)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-pdw-exec-requests-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-pdw-exec-requests-transact-sql.md)
* Product: **sql**
* Technology: **data-warehouse**
* GitHub Login: @XiaoyuMSFT
* Microsoft Alias: **xiaoyul**

**Comment by WilliamAntonRohm** [comment]
@markprycemaher -- Mark, thank you for your feedback.  I am looking into this article.
