### ISSUE TITLE
TVP columns don't always need to be bound

### ISSUE THREAD

**Issue by bkline** [MicrosoftDocs/sql-docs#4931]
The sentence which begins the fourth paragraph of this page ...

> After binding the table-valued parameter, the application must then bind each table-valued parameter column.

...  is not true in every case. As I learned from a Microsoft contractor (see the discussions in [this GitHub ticket](https://github.com/mkleehammer/pyodbc/issues/772)) it is also possible to tell the driver to use the default value, which in the case of a TVP is an empty sequence. It would have saved a considerable amount of time and work to have had that information in the ODBC documentation.

This new information also seem to contradict the previous paragraph, which says

> Table-valued parameters as a whole cannot be set to a default value by using SQL_DEFAULT_PARAM in StrLen_or_IndPtr....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 566a596c-5b9f-9775-f561-a8f19e5e6109
* Version Independent ID: 06c58e2a-7d06-64d5-c1bc-818e7ab8848a
* Content: [Data Transfer of Table-Valued Parameters - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-table-valued-parameters/binding-and-data-transfer-of-table-valued-parameters-and-column-values?view=sql-server-ver15)
* Content Source: [docs/relational-databases/native-client-odbc-table-valued-parameters/binding-and-data-transfer-of-table-valued-parameters-and-column-values.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/native-client-odbc-table-valued-parameters/binding-and-data-transfer-of-table-valued-parameters-and-column-values.md)
* Product: **sql**
* Technology: **native-client**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@bkline -- Bob, thank you for your feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@bkline 

Sorry for the delayed response.

Here is info that I hope will help you with your concern.

-If there are no rows, there are also no columns to bind.
-TVPs do not have a default value that can be set, because SQL_DEFAULT_PARAM indicates no rows.

Please let me know if you have any more questions.

Thank you.

**Comment by markingmyname** [comment]
@bkline 

The article will be updated by the end of the week with a Note describing this info.

Thank you for bringing this to our attention.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by bkline** [comment]
Thanks, @markingmyname .
