### ISSUE TITLE
SELECT INTO doesn't create a "copy" of a table

### ISSUE THREAD

**Issue by TiborKaraszi** [MicrosoftDocs/sql-docs#4934]
ExampleF 
The terminology "copy of a table" is dangerous. Less experienced users might not understand that SELECT INTO won't carry over things such as constraints, indexes etc. Please change to something like "Copying the data from one table to another and create the new table on a specified filegroup".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7a0081-bcda-fa97-710e-e80f6163370c
* Version Independent ID: be2ce0d8-2b71-f7dd-bc3c-0fe89963488f
* Content: [INTO Clause (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-into-clause-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/queries/select-into-clause-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/select-into-clause-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@TiborKaraszi -- Tibor, thank you for your feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @TiborKaraszi! Sorry for the delay. We really appreciate your feedback, and I have incorporated it into the document. Thank you so much!
