### ISSUE TITLE
Columns added to sys.dm_os_memory_objects DMV in SQL Server 2016 release are not labelled as such

### ISSUE THREAD

**Issue by RobAshton-IM** [MicrosoftDocs/sql-docs#4939]
The columns **partition_type**, **contention_factor**, **waiting_tasks_count**, and **exclusive_access_count** in the _sys.dm_os_memory_objects_ DMV were added in the SQL Server 2016 release (see the Bob SQL post [SQL 2016 - It Just Runs Faster: Dynamic Memory Object (CMemThread) Partitioning](https://docs.microsoft.com/en-us/archive/blogs/bobsql/sql-2016-it-just-runs-faster-dynamic-memory-object-cmemthread-partitioning) for details).

The columns' descriptions don't indicate that, so end users may be confused when they try to find them on versions of SQL Server older than 2016. An "Applies to: SQL Server 2016 (13.x) and later." label should be applied to those columns' descriptions to reflect this correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1115cb11-99d6-a4b9-80d5-9b50b090351e
* Version Independent ID: 4590c1d7-b55d-4d3e-473a-ba92a2a14b15
* Content: [sys.dm_os_memory_objects (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-memory-objects-transact-sql?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(dm_os_memory_objects_TSQL);k(sql13.swb.tsqlresults.f1);k(sql13.swb.tsqlquery.f1);k(MiscellaneousFilesProject);k(DevLang-TSQL)%26rd%3Dtrue&view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-os-memory-objects-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-os-memory-objects-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
