### ISSUE TITLE
Typo in this page (I assume)

### ISSUE THREAD

**Issue by NaomiN** [MicrosoftDocs/sql-docs#4948]
Click a product!
In the following row, click whichever product name you are interested in. The **click** displays different content here on this webpage, appropriate for whichever product you click.

-----------------------------------------
I believe it is supposed to be 'The link displays'... instead

**Comment by WilliamAntonRohm** [comment]
*@NaomiN -- Naomi, thank you for your feedback.  Please provide the URL of the article you're reading.  I will pass along your comment regarding the new-window behavior.

**Comment by NaomiN** [comment]
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@NaomiN -- Naomi, thank you for that information.  It looks like there are 14 sibling pages with the same typo; I am looking into them.

**Comment by NaomiN** [comment]
Same typo here as well https://docs.microsoft.com/en-us/sql/t-sql/statements/backup-transact-sql?view=sql-server-ver15

**Comment by NaomiN** [comment]
Also, that link doesn't display products it applies to at the top (I assume it applies to SQL Server and Azure Managed Instance)

**Comment by WilliamAntonRohm** [comment]
@NaomiN -- Naomi, thank you for clarifying.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review [private PR 15762](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15762).

**Comment by NaomiN** [comment]
I think I saw that exact same typo in other document I was reading recently too, but decided to not raise the issue again. Most likely that same typo is repeated in lots of the documents. Don't know if I should be fixing it manually next time I came across it or leave it.

**Comment by WilliamAntonRohm** [comment]
@NaomiN -- yes, there are 14 articles under t-sql/statements with the same typo.  I updated them all in Mike's PR, which is filed in the private (staging) docs repo, so you can leave them.  You're welcome to fix anything else you find.

@MikeRayMSFT -- Mike, please note Naomi's comment:

> Also, that link doesn't display products it applies to at the top (I assume it applies to SQL Server and Azure Managed Instance)
