### ISSUE TITLE
Page describes how to apply a DENY privilege. There is no mention of how to undo/remove that.

### ISSUE THREAD

**Issue by DatabaseAsAService** [MicrosoftDocs/sql-docs#4950]
Page describes how to apply a DENY privilege. There is no mention of how to undo/remove that. Is it REVOKE DENY? Would be nice to have a mention on the page.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61813295-01ed-e551-f767-238eb89c99b0
* Version Independent ID: 3ed4d853-898b-39f3-8a16-d96941651d46
* Content: [DENY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/deny-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/deny-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/deny-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@DatabaseAsAService -- thank you for your feedback.  Please see this section:
- [REVOKE](https://docs.microsoft.com/en-us/sql/t-sql/statements/revoke-transact-sql#remarks)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
