### ISSUE TITLE
Keyword "FOR" or "AFTER" are same?

### ISSUE THREAD

**Issue by kind03** [MicrosoftDocs/sql-docs#4953]
I'm confused by this paragraph:

> FOR | AFTER
FOR or AFTER specifies that the DML trigger fires only when all operations specified in the triggering SQL statement have launched successfully. All referential cascade actions and constraint checks must also succeed before this trigger fires.
You can't define AFTER triggers on views.

So what is the difference between "For" and "After"? Looks like they are the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8add50-414a-a033-6fc0-84de1c7735f2
* Version Independent ID: 8f2f3149-7035-b3d4-6f09-a6eadd015e24
* Content: [CREATE TRIGGER (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-trigger-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-trigger-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-trigger-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@kind03 -- thank you for your question.  Please see an answer here:
- https://stackoverflow.com/questions/5340638/difference-between-for-and-after-triggers

@CarlRabeler -- please look into this issue.

**Comment by CarlRabeler** [comment]
@kind03 they are the same

**Comment by WilliamAntonRohm** [comment]
@CarlRabeler -- thank you for clarifying.
