### ISSUE TITLE
Update SQL server ODBC documentation for Ubuntu 20.04

### ISSUE THREAD

**Issue by aaronfranke** [MicrosoftDocs/sql-docs#4956]
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15

https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md

The documentation only includes Ubuntu 16.04, 18.04, and 19.10. The same instructions do not work on Ubuntu 20.04, so the instructions need to be updated.

Similarly, https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15 and https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md need to be updated, since they only contain instructions for Ubuntu 18.04.

Here's what happens when I try following the instructions for 19.10 (and 18.04 for the quickstart):

```
$ sudo apt install unixodbc-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unixodbc-dev : Depends: unixodbc (= 2.3.7)
                Depends: odbcinst1debian2 (= 2.3.7) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

$ sudo apt install libodbc1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libodbc1 : PreDepends: multiarch-support but it is not installable
E: Unable to correct problems, you have held broken packages.

$ sudo apt install multiarch-support
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package multiarch-support is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'multiarch-support' has no installation candidate
```

**Comment by WilliamAntonRohm** [comment]
@aaronfranke -- Aaron, thank you for your feedback.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
@aaronfranke Ubuntu 20.04 is not yet supported by the ODBC driver. The instructions will be updated when support is added (coming within a couple months).

#please-close
