### ISSUE TITLE
Too much information

### ISSUE THREAD

**Issue by eugenevdm** [MicrosoftDocs/sql-docs#4960]
[Enter feedback here]

Reading this document is like reading the dictionary. Way too much information!

A typical user wants to see a summary of commonly used commands, and then a reference. This is a reference. It should have a TL;DR section at the top.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da1f57b-a8fd-cca7-4cf0-9d594d365062
* Version Independent ID: 60c46780-6a03-7958-c77a-e7c94e3b9e85
* Content: [sqlcmd Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15)
* Content Source: [docs/tools/sqlcmd-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlcmd-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@eugenevdm -- Eugene, thank you for your feedback.  You are welcome to add it here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

Please see also this article:
- [sqlcmd - Use the utility](https://docs.microsoft.com/sql/ssms/scripting/sqlcmd-use-the-utility)
