### ISSUE TITLE
How exactly do I know my version of SSMS? Does the minor version update automatically?

### ISSUE THREAD

**Issue by NaomiN** [MicrosoftDocs/sql-docs#4962]
From the page about Download of SSMS I was redirected here when I wanted to add a comment / question (the original page closed?)

My question is - how exactly do I see my version of SSMS? The latest is supposed to be 18.5.1 When I check Help/About I see 18.5. If I go to Tools/Check for Updates it says I'm on the latest already and also my build number matches the built shown in that link. However, it says that version was released on June 9 and I believe I installed my version a bit earlier (either in April or in May). Was the update done somehow automatically? How can I confirm it?

**Comment by WilliamAntonRohm** [comment]
@NaomiN -- Naomi, thank you for your questions.  Is this the page you're referring to?
- https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms

@dzsquared -- Drew, please look into this issue.  Naomi's explanation of Tools/Check for Updates matches my experience on my local machine.

**Comment by NaomiN** [comment]
Yes, that was the page. I got re-directed as the first time (in my prev. issue). Using Google Chrome. My Help says 18.5 so I don't know if I'm using the latest or one minor version behind.

**Comment by dzsquared** [comment]
@NaomiN it looks like that dialog is incorrectly returning the most up to date version. You are 1 fix-version behind at the moment.  Early next week the in-application update check will return correctly, but in the meantime if you want to update you can grab the latest installed from https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms

SSMS will not install the update automatically and it is the same installer being downloaded from the docs page.  The build number you see installed for 18.5 should be 15.0.18330.0 while the build number for 18.5.1 is 15.0.18333.0, the difference is in the 2nd to last digit.

Sorry for the confusion!

**Comment by NaomiN** [comment]
I think I may wait a bit :) Perhaps next week a new update will come out again :) I actually went through this check since I found this thread
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/317686a0-58f0-417d-8c55-2eee80e6c767/importing-azure-database-to-local-on-prem-db-error-in-importing-db?forum=sqltools

**Comment by WilliamAntonRohm** [comment]
@dzsquared -- thank you for your detailed reply.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by NaomiN** [comment]
Hi William, I was trying to figure out how to ask a question  - did I somehow became an author of the documents or now everyone can edit? E.g. I went to this document https://docs.microsoft.com/en-us/sql/ssma/oracle/what-s-new-in-ssma-for-oracle-oracletosql?view=sql-server-ver15&source=docs and I wanted to actually ask a question related to this MSDN thread https://social.msdn.microsoft.com/Forums/sqlserver/en-US/91fd22ef-6213-4a90-8610-e0bda85799dc/how-can-i-configure-ssma-to-generate-a-filtered-unique-index-that-ignores-null?forum=sqlservermigration but there was no option under the document to add any notes but rather an option to edit. Does it mean I can edit the documents or it was just for that particular one?

**Comment by WilliamAntonRohm** [comment]
@NaomiN -- Hi!  Everyone can edit a document and create a PR for their update.  Each PR is reviewed by our team and typically merged into the live site.  Here's how:
- Navigate to the page of interest
- Select the "Edit" button at the top right of the page
- Select the "Pencil" icon on the right
- Modify the text within the text box in markdown format
- Name your file change and copy the link to your Git Issue into the "extended description" box
- Select "Propose file change"
- Select "Create pull request" on the 'Comparing changes' page
- Select "Create pull request" on the 'Open a pull request' page
- Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing this will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and list you as a contributor to the documentation.

**Comment by WilliamAntonRohm** [comment]
@NaomiN -- as to why there is no Feedback button on that release note page, I'm not sure.  I'll ask on my end.

What is your question?

**Comment by NaomiN** [comment]
To be honest, I already forgot. I was doing a research of someone's question in MSDN and I believe someone from the team (with Russian sound name) answered that person's question that the option is ON by default (the question was about filtered indexes in SSMA from Oracle to SQL Server)
