### ISSUE TITLE
Check the accuracy of the list of permissions associated with each type

### ISSUE THREAD

**Issue by shueybubbles** [MicrosoftDocs/sql-docs#4963]
It looks like "DELETE" isn't applicable to user defined data types.

```
GRANT DELETE ON TYPE :: [dbo].[dataType] TO [testRole]

Msg 102, Level 15, State 1, Line 0
Incorrect syntax near 'DELETE...'.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6141aa-bfd7-1ce4-aecd-820036f4a60e
* Version Independent ID: fd41bd15-b6f6-0a67-eee8-4bae68e9838e
* Content: [Permissions (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/permissions-database-engine?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/permissions-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/permissions-database-engine.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@shueybubbles -- David, thank you for your feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by shueybubbles** [comment]
I think I was misled because there are 2 tables on the page. The bottom table has the right set associated with TYPE, but the top table says "all types except database scoped credential and SERVER" for "DELETE".  Does this page really need 2 separate tables?

**Comment by WilliamAntonRohm** [comment]
@shueybubbles -- David, thank you for the followup.  I am updating the first table's DELETE description.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please review [private PR 15459](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15459).
