### ISSUE TITLE
Please correct spelling of 'Identify'

### ISSUE THREAD

**Issue by jgmreyes** [MicrosoftDocs/sql-docs#4965]
You had it spelled wrong. Quoting the whole paragraph for easy search.

"A credential can be created for an EKM provider and mapped to a login (both Windows and SQL Server accounts) to access an EKM module on per-login basis. The Identify field of the credential contains the username; the secret field contains a password to connect to an EKM module."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1f2c05-a6cd-c645-3328-f3a2dfaaf6a6
* Version Independent ID: c71aae83-1916-738d-a2dd-0c3917f86551
* Content: [Extensible Key Management (EKM) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/extensible-key-management-ekm?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/extensible-key-management-ekm.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/extensible-key-management-ekm.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@jgmreyes -- thank you for catching that.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
