### ISSUE TITLE
Wrong env variable

### ISSUE THREAD

**Issue by olyoberdorf** [MicrosoftDocs/sql-docs#4966]
The docs say to use MSSQL_SA_PASSWORD but this is incorrect.  The real variable is SA_PASSWORD.  This is compounded by the container not providing any message about the password being unset.  Instead, you are unable to login as you would expect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dc2ec36-4915-f7ab-3104-282acc9321e6
* Version Independent ID: fc98af17-f3c5-adff-69ca-593f985e7882
* Content: [Configuration options for SQL Server on Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-configure-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by WilliamAntonRohm** [comment]
@olyoberdorf -- Oliver, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@vin-yu -- Vin, please review [private PR 15497](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15497).

**Comment by VanMSFT** [comment]
Hi @olyoberdorf! Thanks for letting us know! We really appreciate it. I have refreshed this article, and the changes should take place next week.

@WilliamAntonRohm - Sorry about the delay. I just saw this issue. Please go ahead and close your PR as my refresh will take care of this.
