### ISSUE TITLE
TRANSLATE is not avail to SQL EXPRESS 2017

### ISSUE THREAD

**Issue by bachphi** [MicrosoftDocs/sql-docs#4967]
I am using SQL EXPRESS 2017 w/ latest update revision, and yet TRANSLATE is not avail.  The TRANSLATE document page said otherwise.
Do you know why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e60cc3d-fd45-2a73-aa40-536051e9f54d
* Version Independent ID: ddf2d9c5-6855-66e7-06c6-b4036dea1276
* Content: [TRANSLATE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/translate-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/translate-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/translate-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@bachphi -- thank you for your question.  I am investigating.

**Comment by WilliamAntonRohm** [comment]
@bachphi -- my apologies for the delay in responding. 

@julieMSFT -- please look into this issue.

**Comment by julieMSFT** [comment]
@bachphi Hello and thank you for contacting Microsoft. Can you provide the code you are trying to run and the error you are getting?

**Comment by julieMSFT** [comment]
@bachphi Hello, I will proceed to close this issue. If you have further information the @notification mechanism continues to work even after an item is closed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
