### ISSUE TITLE
DBCC SHRINKDATABASE missing a few words in the explanations

### ISSUE THREAD

**Issue by BrentOzar** [MicrosoftDocs/sql-docs#4969]
The Best Practices section reads:

> A shrink operation is most effective after an operation. This operation creates unused space, such as a truncate table or a drop table operation.

I think there are words missing in this part: "most effective after an ____ operation."

I think what it meant to say was, "A shrink operation is most effective after an operation that creates unused space, such as a truncate table or a drop table operation."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87349f50-5751-68c4-df29-90c1c7c151d9
* Version Independent ID: bb82dc63-23ec-eda3-0200-88c4748e050a
* Content: [DBCC SHRINKDATABASE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-shrinkdatabase-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/database-console-commands/dbcc-shrinkdatabase-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/database-console-commands/dbcc-shrinkdatabase-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **umajay**

**Comment by WilliamAntonRohm** [comment]
@BrentOzar -- Brent, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@pmasl -- Pedro, please review [private PR 15498](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15498).

**Comment by pmasl** [comment]
@BrentOzar thanks for finding the typo.

**Comment by BrentOzar** [comment]
You bet! Have a good week.
