### ISSUE TITLE
Incomplete list of columns

### ISSUE THREAD

**Issue by erinstellato** [MicrosoftDocs/sql-docs#4972]
The sys.stats documentations lists columns in the system view up to is_incremental, but in the latest 2019 CU (CU5 currently), there is also has_persisted_sample, stats_generation_method, and stats_generation_method_desc.

It would be nice to understand those last two :)

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c714137-6eda-b825-2207-6b0765e3f97a
* Version Independent ID: 99852c0c-e4bb-22d8-6376-cd65a6e95e8b
* Content: [sys.stats (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-stats-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-catalog-views/sys-stats-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-stats-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
#reassign: @pmasl 
Pedro - could you please look at this. If this is not in your area, please either reassign back to me and reassign to the appropriate individual

**Comment by Hermholtz** [comment]
They're still not updated.

**Comment by erikdarlingdata** [comment]
Yeah, what's up with these? Inquiring minds want to know.

**Comment by pmasl** [comment]
Will be updated in the next few hours. 

#please-close
