### ISSUE TITLE
sys.system_internals_allocation_units

### ISSUE THREAD

**Issue by HenrikStaunPoulsen** [MicrosoftDocs/sql-docs#4974]
sys.system_internals_allocation_units is not available on SQL Azure Database. 
Documentation should reflect this, IMHO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2881d6-51e3-3eee-a6df-911463517b54
* Version Independent ID: 9295888e-8884-7d3f-7bd4-2bdeccae6962
* Content: [Pages and Extents Architecture Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/pages-and-extents-architecture-guide?view=sql-server-ver15)
* Content Source: [docs/relational-databases/pages-and-extents-architecture-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/pages-and-extents-architecture-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@HenrikStaunPoulsen -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@rothja -- please review [private PR 15499](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15499).
