### ISSUE TITLE
Update to RHEL 8

### ISSUE THREAD

**Issue by iantrudell** [MicrosoftDocs/sql-docs#4975]
Looking for a guide on how to install SSIS on RHEL 8 instead of RHEL 7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41654ae8-cbd1-c5dd-f15a-69466a765fda
* Version Independent ID: 94311dce-80f0-b8ce-7296-b595ff50d640
* Content: [Install SQL Server Integration Services on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-ssis?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-setup-ssis.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-ssis.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @lrtoyou1223
* Microsoft Alias: **lle**

**Comment by iantrudell** [comment]
The rhel/8 repo does not contain mssql-server-is
```
No match for argument: mssql-server-is
Error: Unable to find a match: mssql-server-is
```

**Comment by WilliamAntonRohm** [comment]
@iantrudell -- Ian, thank you for your follow-up. 

@lrtoyou1223 -- Leo, please look into this issue.

**Comment by lrtoyou1223** [comment]
Currently SSIS Linux doesn't support RHEL8. The target ETA could be by the end of this year or early next year.
