### ISSUE TITLE
bpool_commited column has wrong name

### ISSUE THREAD

**Issue by bowermea** [MicrosoftDocs/sql-docs#4976]
On a SQL Server instance of 2008 R2 (10.5 SP3), the bpool_commited column is not found on the dm_os_sys_info view because the actual column name was bpool_committed (with two 't's).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1073200-d5d6-a64e-d8d8-a4809873822b
* Version Independent ID: aab7789b-e333-2d9a-bfb9-52106184c156
* Content: [sys.dm_os_sys_info (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@bowermea -- thank you for catching that.  I am looking into this article.
