### ISSUE TITLE
268435456 = Log file will grow to a maximum size of 2 TB. Seems Wrong

### ISSUE THREAD

**Issue by terryclancy** [MicrosoftDocs/sql-docs#4977]
268435456 = Log file will grow to a maximum size of 2 TB. Seems Wrong
268435456 = 268,435,456 so even if units are KB that would be  268,435,456,000 bytes which is not close to 
1,000,000,000,000  = 1TB ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae823efc-d65f-9f4a-9a62-faad1d047a76
* Version Independent ID: 16cbcb94-577b-6998-0c65-c4107c509826
* Content: [sys.database_files (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-files-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-catalog-views/sys-database-files-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-database-files-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@terryclancy -- Terry, thank you for your feedback.  The units for max_size are 8-KB pages, per that row's notes:
> max_size 
> Maximum file size, in 8-KB pages  

So 268,435,456 * 8 * 1,024 = 2,199,023,255,552 total bytes.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by terryclancy** [comment]
OK thanks – ( although weird unit to use 😊 )
