### ISSUE TITLE
en-us/sql/linux/sql-server-linux-security-get-started broken formatting

### ISSUE THREAD

**Issue by marksweiss** [MicrosoftDocs/sql-docs#4983]
The code blocks starting with `CREATE SECURITY POLICY SalesFilter` and below are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef0b65e5-3c2a-d6cf-f2d3-4ba2a9dc5451
* Version Independent ID: 85fa54ab-0067-6bfd-7aa4-95ca26763f3a
* Content: [Get started with SQL Server security on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-security-get-started?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-security-get-started.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-security-get-started.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@marksweiss -- Mark, thank you for your feedback.  I am looking into this article.

**Comment by marksweiss** [comment]
Awesome. Thanks for the amazingly fast response!
