### ISSUE TITLE
Typo in Configure Backup Compression Documentation

### ISSUE THREAD

**Issue by sonoftunk** [MicrosoftDocs/sql-docs#4984]
The line reads `use either WITH NO_COMPRESSION or WITH COMPRESSION in you BACKUP statement.` The word `your` should be used instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fac3bce-e592-f213-beb4-d414fa842f8c
* Version Independent ID: 43164541-9225-97f7-49e1-e888f02bcf9b
* Content: [Configure Backup Compression (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/configure-backup-compression-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/backup-restore/configure-backup-compression-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/configure-backup-compression-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@sonoftunk -- thank you for your feedback. I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
I have updated the documentation and it should be live by tomorrow.
