### ISSUE TITLE
LAST_NODE usage

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#4986]
@Elloudo commented on [Sun Jun 14 2020](https://github.com/MicrosoftDocs/sql-docs.fr-fr/issues/124)

Hello!

I am not sure to understand the usage of LAST_NODE and I was not able to help myself with the documentation and did not found any example. 

Can you please provide more explanation and example for LAST_NODE usage in:
- simple_match_pattern
- arbitrary_length_match_last_node_predicate
- arbitrary_length_pattern

Thanks a lot

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9522c78a-6cdd-c5b0-4b5b-f7c6d0e5a241
* Version Independent ID: 27551083-bb07-638b-a491-7f5e4f94c22c
* Content: [MATCH (SQL Graph) - SQL Server](https://docs.microsoft.com/fr-fr/sql/t-sql/queries/match-sql-graph?view=sql-server-2017)
* Content Source: [docs/t-sql/queries/match-sql-graph.md](https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/t-sql/queries/match-sql-graph.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @shkale-msft
* Microsoft Alias: **shkale**

---

@srvbpigh commented on [Sun Jun 14 2020](https://github.com/MicrosoftDocs/sql-docs.fr-fr/issues/124#issuecomment-643809140)

Hello, @Elloudo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, thank you for raising this.  Please convey the following to @Elloudo:

- Please see as well [Arbitrary Length Pattern](https://docs.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-shortest-path#arbitrary-length-pattern).

@shkale-msft -- Shreya, please look into this issue.

**Comment by rothja** [comment]
@shkale-msft Shreya, could you please take a look at this git issue? Thank you!

**Comment by arvindshmicrosoft** [comment]
@rothja - kindly add me to the assignees list. I'll coordinate with Shreya and get a good example for this into the docs.

**Comment by rothja** [comment]
@arvindshmicrosoft Thank you so much for helping to address this! #assign:arvindshmicrosoft

**Comment by arvindshmicrosoft** [comment]
This has been addressed with recent updates to the docs. There are changes to https://docs.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-shortest-path?view=azuresqldb-current#examples which should reflect in a few days. With this, I believe we can close this issue.

**Comment by rothja** [comment]
@arvindshmicrosoft Thank you for following up on this! I will close the issue. We can reopen if there is any further concern or feedback. Thank you!
