### ISSUE TITLE
Missing Figures 

### ISSUE THREAD

**Issue by JeromeAtchison** [MicrosoftDocs/sql-docs#4988]
In the [Circular Arc Segments section](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-data-types-overview?view=sql-server-ver15#circular), there are references to figures "A", "B", "C", and "D", that are not on the page:
**Circular Arc Segments**
...
Figures A and B show typical circular arc segments. ... 
Figures C and D show how a line ...

Please insert missing "figures" (images?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2797e2b3-62ca-d4f9-c36f-31d77358deda
* Version Independent ID: 0e1e4a3a-2bcb-97e1-94ac-98be1bfbda97
* Content: [Spatial Data Types Overview - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-data-types-overview?view=sql-server-ver15)
* Content Source: [docs/relational-databases/spatial/spatial-data-types-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/spatial/spatial-data-types-overview.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@JeromeAtchison -- Jerome, thank you for your feedback.

@MladjoA -- Mladen, please look into this issue.

**Comment by MladjoA** [comment]
The figure is back now, and reference in the text is updated.
Thanks @JeromeAtchison for bringing this to our attention!

**Comment by MladjoA** [comment]
#please-close
