### ISSUE TITLE
MacOS installation - missing a last step

### ISSUE THREAD

**Issue by MikeB2019x** [MicrosoftDocs/sql-docs#4989]
Hi!  The macOS installation docs are great but missing a last important step.  When you run either of the two scripts indicated for ver 13 or 17, the drivers are installed in a directory called '\usr\local\etc'.  However 'odbcinst' the installer expects the files to be in '\etc'.  So when 'pyodbc' is used for a database connection, it throws a 'File not found' error.  

The remedy is really simple.  macOS has an 'alias' folder called '\etc'.  So after running either of the two scripts on the page, the user should run the following two commands:
```
sudo ln -s /usr/local/etc/odbcinst.ini /etc/odbcinst.ini
sudo ln -s /usr/local/etc/odbc.ini /etc/odbc.ini
```
What that does is when 'odbcinst' looks for say '/etc/odbcinst.ini' it gets instead re-directed to '/usr/local/etc/odbcinst.ini' and it finds the file it needs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c0de6fb-19ae-ff6f-8e73-ce66fa94bd64
* Version Independent ID: 34edd099-f4fe-4ac3-cdd4-abc87b35270b
* Content: [Install the Microsoft ODBC driver for SQL Server (macOS) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@MikeB2019x -- thank you for your detailed feedback.

@David-Engel -- please look into this issue.

**Comment by David-Engel** [comment]
The driver appears to install fine in mine and others' environments without that "last step". It seems like there might be something specific about your environment, which is causing the link to be needed. The installation steps are correct as-is.

#please-close
