### ISSUE TITLE
Suggested feedback: include note about spatial indexes on indexed views

### ISSUE THREAD

**Issue by CMoltedo** [MicrosoftDocs/sql-docs#4991]
[Enter feedback here]
Please include a note about not being able to create spatial indexes on indexed views, similar to what's stated here: https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/bb964740(v=sql.105)?redirectedfrom=MSDN

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1982b813-5bcb-0733-370e-332dfcd883d4
* Version Independent ID: bda354b5-6672-3f46-275d-be882727ea1d
* Content: [CREATE SPATIAL INDEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-spatial-index-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-spatial-index-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-spatial-index-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@CMoltedo -- Chase, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@CarlRabeler -- Carl, please review [private PR 15628](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15628).
