### ISSUE TITLE
Clarify compatibility with SLES 15

### ISSUE THREAD

**Issue by jaldinger** [MicrosoftDocs/sql-docs#4994]
SQL Server 2019 seems to be available por SLES 15, too, from this repo link: https://packages.microsoft.com/config/sles/15/prod.repo

However, that is not mentioned in the page, so if I assume correctly, that should be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600e45dc-85ad-e487-9375-949af2530a83
* Version Independent ID: a0e1527b-fd9a-b7a0-0bef-d14339cf4e1f
* Content: [SUSE: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-suse?view=sql-server-2017)
* Content Source: [docs/linux/quickstart-install-connect-suse.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-suse.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@jaldinger -- Joerg, thank you for your feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @jaldinger! Thanks for the feedback. As you correctly stated, the repo files are there. However, we currently don't have full support for SLES 15, and so it isn't listed in our documentation. There's no ETA for support at the moment that I can provide, but our documentation will be updated as soon as it is officially supported. We appreciate you bringing up this issue.
