### ISSUE TITLE
Make more useful

### ISSUE THREAD

**Issue by michaelruss777** [MicrosoftDocs/sql-docs#4997]
It would be very useful to add examples for each option of how it changes the scripting output. For example, for the "Include descriptive headers", True adds a comment like: /****** Object:  Table [dbo].[Customers]    Script Date: 7/16/2019 8:10:59 AM ******/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b12f56f-4709-cab6-33a2-52acb1581ff8
* Version Independent ID: c6790f69-453e-ffce-6f79-5aa3a656e80b
* Content: [Options (SQL Server Object Explorer - Scripting Page) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/object/options-sql-server-object-explorer-scripting-page?view=sql-server-ver15)
* Content Source: [docs/ssms/object/options-sql-server-object-explorer-scripting-page.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/object/options-sql-server-object-explorer-scripting-page.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@michaelruss777 -- Michael, thank you for your suggestion.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@michaelruss777 

Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by markingmyname** [comment]
Hi, @michaelruss777,

If there are examples you have interest in, can you please mention them in this Issue?

I can review them and add them if they fit the scope of the article.

Thank you.

**Comment by markingmyname** [comment]
@michaelruss777 

Since I have n ot heard back i will close this issue.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
