### ISSUE TITLE
'View as Chart' hyperlink missing

### ISSUE THREAD

**Issue by robertplata** [MicrosoftDocs/sql-docs#4998]
Hello< I am following the 'Tutorial: Build a custom insight widget' on this page:
https://docs.microsoft.com/en-us/sql/azure-data-studio/tutorial-build-custom-insight-sql-server?view=sql-server-ver15

I can't seem to find the link referred to in Step 6 of the 'Run your own query and view the result in a chart view' section.  

I am following along with Azure Data Studio:
Version: 1.19.0 (user setup)
Commit: 4095037f2578c23033867e611e82c13de114ca5a
Date: 2020-06-11T22:06:05.429Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Is it right in front of my face and I am not seeing it?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9720e473-61dc-6a0f-9481-ca6c617d3265
* Version Independent ID: 5e373d84-4b76-0019-fc0b-616e3672e4a4
* Content: [Tutorial: Build a custom insight widget - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/tutorial-build-custom-insight-sql-server?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/tutorial-build-custom-insight-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/tutorial-build-custom-insight-sql-server.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@robertplata -- thank you for your feedback & question.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@robertplata -- after I run that query, a Results window appears below the query with three tabs (Results, Messages, Chart), and there are icons on the right side of its window including one that's a miniature vertical bar chart.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
