### ISSUE TITLE
independed DATEPART(WEEKDAY, ...)

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#5005]
@samot1 commented on [Wed Jun 17 2020](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/126)

If you need the WEEKDAY independend on the value set currently for DATEFIRST, you can use
`SELECT (DATEPART(WEEKDAY, GETDATE()) - 1 + @@DATEFIRST) % 7  AS weekday`

It will always return 1 for Monday, 2 for Tuesday ... 7 for Sunday, regardless to what DATEFIRST is set.

Maybe it could be added to the examples

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4d1c1cb1-feb7-d2d1-9b9f-6b3f8caff8d6
* Version Independent ID: c6caa07c-fb64-31e9-ed4f-36e367dfbaeb
* Content: [DATEPART (Transact-SQL) - SQL Server](https://docs.microsoft.com/de-de/sql/t-sql/functions/datepart-transact-sql?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(DATEPART_TSQL);k(sql13.swb.tsqlresults.f1);k(sql13.swb.tsqlquery.f1);k(DevLang-TSQL)%26rd%3Dtrue&view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/datepart-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/t-sql/functions/datepart-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

---

@srvbpigh commented on [Wed Jun 17 2020](https://github.com/MicrosoftDocs/sql-docs.de-de/issues/126#issuecomment-645454184)

Hello, @samot1
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, thank you for raising this issue here.  Please convey the following to @samot1:
- @samot1, thank you for clever contribution.

@julieMSFT -- Julie, please look into this issue.

**Comment by julieMSFT** [comment]
@CeciAc Hi Cecilia, Thank you for this example. I am looking into adding it to the article.

**Comment by julieMSFT** [comment]
@CeciAc Hi Cecilia, Thank you again for contacting Microsoft and for this example. When I run this example I find that Sunday always returns as 0 not 7. I think this could be useful in the right situation but I am not sure it has enough general value to add to the document. I will proceed with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close

**Comment by samot1** [comment]
With a slightly modification you can fix the Sunday behavior:

(DATEPART(WEEKDAY, @date) - 1 + @@DATEFIRST -1) % 7 + 1 AS weekday_1_to_7)


 

(additional -1 after @@DATEFIRST and + 1 after the %7.

 


Gesendet: Donnerstag, 02. Juli 2020 um 21:44 Uhr
Von: "julieMSFT" <notifications@github.com>
An: "MicrosoftDocs/sql-docs" <sql-docs@noreply.github.com>
Cc: "Thomas Franz" <samot-dwarf@gmx.net>, "Mention" <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/sql-docs] independed DATEPART(WEEKDAY, ...) (#5005)


 

@CeciAc Hi Cecilia, Thank you again for contacting Microsoft and for this example. When I run this example I find that Sunday always returns as 0 not 7. I think this could be useful in the right situation but I am not sure it has enough general value to add to the document. I will proceed with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
@samot1 Hi Thomas, thank you for contacting Microsoft and for the code update. I would need a good general scenario for adding this example to the article.
