### ISSUE TITLE
The Keyword "Application Intent" is incorrect

### ISSUE THREAD

**Issue by genifycom** [MicrosoftDocs/sql-docs#5008]
The Keyword "Application Intent" is incorrect. The correct Keyword is "ApplicationIntent" with NO space.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7197d3b-5829-e8f5-7245-e51869cc0836
* Version Independent ID: 40f0e4c5-95eb-24e0-6f0f-2776c8f89bb0
* Content: [Using Connection String Keywords - SQL Server Native Client](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client?view=sql-server-ver15)
* Content Source: [docs/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client.md)
* Product: **sql**
* Technology: **native-client**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@genifycom -- thank you for catching this.  I am looking into the article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review [private PR 15631](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15631).
