### ISSUE TITLE
Don't require Homebrew to install msodbcsql17

### ISSUE THREAD

**Issue by breiter** [MicrosoftDocs/sql-docs#5009]
Microsoft shouldn't be distributing Mac software only through Homebrew. Homebrew is not the  "official" package manager for macOS and it is not without problems -- for one thing it takes over `/usr/local/bin` and requires changing the permissions on `/usr/local/bin`.

If Microsoft can't provide a source tarball for msodbsql17 that can be arbitrarily compiled for unix and linux systems, then it should provide a .pkg file for macOS and support the 3 main package managers: Homebrew, MacPorts, and pkgsrc.

MacPorts has a package for  msodbcsql17 but it is a pain for the project to maintain. Currently when you install msodbsql17, MacPorts prints out a warning that manual intervention is required:

```
  msodbcsql17 has the following notes:
    To make this work with SSL you need to create a symbolic link as follows: 
     sudo mkdir -p /usr/local/opt/openssl/ 
     sudo ln -s /opt/local/lib /usr/local/opt/openssl/lib 
    
     This is because this port installs binaries meant to be used with Homebrew.
```

Microsoft has the resources to take over maintenance of the MacPorts package so that installation is reliable and doesn't require a symlink hack to find openssl.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c0de6fb-19ae-ff6f-8e73-ce66fa94bd64
* Version Independent ID: 34edd099-f4fe-4ac3-cdd4-abc87b35270b
* Content: [Install the Microsoft ODBC driver for SQL Server (macOS) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@breiter -- Brian, thank you for your feedback.  It appears you have product suggestions rather than documentation issues.  Please raise your points here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @David-Engel for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
