### ISSUE TITLE
Release of threads

### ISSUE THREAD

**Issue by gani746** [MicrosoftDocs/sql-docs#5010]
I want to highlight a correction  or clarification in this section:
https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability?view=sql-server-ver15#ThreadUsage

In my lab tests when I tested how long it takes for the threads to be released back to the thread pool, it turned out that the parallel redo threads are not released at all. It's only the serial redo threads that are released after perhaps 60 seconds. You may consider some internal testing for the same. 

Also reference to : https://techcommunity.microsoft.com/t5/sql-server/sql-server-2019-intelligent-performance-worker-migration/ba-p/939610

After a database successfully starts its parallel redo worker tasks during database startup phase, these parallel redo worker tasks will stay alive until the database is shut down. The main redo task also keeps running as long as there are transaction logs to process and does not stay idle for more than 60 seconds.

It is possible for one or more parallel redo worker tasks of a database to be assigned to the same scheduler as its main redo task. If more than one long-running redo task competes for CPU cycles on the same scheduler, scheduler contention may occur. When this happens, the overall transaction log redo throughput of the impacted database can drop 20-30%.

When several availability group databases have heavy redo workloads during the same period, this scheduler contention pattern is more common because of the increased chance for one or more database main redo tasks to be allocated to the same scheduler with parallel redo worker tasks.

Worker migration avoids this performance degradation and maintains more consistent redo throughput for a database. For multiple database concurrent redo workloads, the overall redo throughput has about 10-15% improvement compared to the situation when there is scheduler contention between some main redo tasks and parallel redo worker tasks.

So, in conclusion:

With SQL 2016/2017, the main redo thread is released back to the pool after perhaps 60 seconds. (You may want to test this if this is 15 seconds or 60 seconds).  But if the thread needs to be spawned again it could be allocated to the same scheduler. 

With SQL 2019, there is an enhancement. The main redo thread could be allocated a different scheduler than the parallel redo threads. That way, the thread is smartly migrated to avoid scheduler contention. 

Please feel free to ping me suganiga@microsoft.com or hetarra@microsoft.com to have m
<img width="541" alt="Parallelredo_and_mainredo_thread_behaviour" src="https://user-images.githubusercontent.com/40675162/85220250-9cdfd500-b3c7-11ea-98bd-534ae20df4f1.png">
ore clarity on this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5dab67c-0b02-71a8-bba0-416be62e5d52
* Version Independent ID: c0f9db5f-668e-aac1-f789-cd7e34bdf316
* Content: [Availability group: Prerequisites, restrictions, & recommendations - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability?view=sql-server-ver15#ThreadUsage)
* Content Source: [docs/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@gani746 -- thank you for your thorough feedback.

@MashaMSFT -- please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @gani746 , thanks for providing this feedback! I have passed it along to the appropriate parties and we are investigating further. We will close out this Git Issue in the meantime but please feel free to comment should you need anything further.

Thanks!
Masha from the SQL Docs team
