### ISSUE TITLE
Predict function is not working on Azure Managed Instance 

### ISSUE THREAD

**Issue by rawatsudhir1** [MicrosoftDocs/sql-docs#5011]
As per the article https://docs.microsoft.com/en-us/sql/t-sql/queries/predict-transact-sql?view=sql-server-ver15 Predict is supported in Azure SQL Managed Instance. However If i am trying to execute the Predict statement (https://docs.microsoft.com/en-us/azure/azure-sql-edge/deploy-onnx) against Azure SQL MI, it gives below error. 

Msg 102, Level 15, State 40, Line 27
Incorrect syntax near '='.
 Msg 319, Level 15, State 1, Line 27
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.

![image](https://user-images.githubusercontent.com/32550309/85228199-275f1d80-b436-11ea-9e30-e2862e7915fe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddee1efc-31ea-5433-b363-b3374ff6f2bd
* Version Independent ID: 1206e81c-1cf6-bab2-666b-a0243eee4410
* Content: [PREDICT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/predict-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/queries/predict-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/predict-transact-sql.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by rawatsudhir1** [comment]
May be my subscription needs to be whitelisted to use PREDICT fucntion?

**Comment by garyericson** [comment]
@rawatsudhir1 - You're correct about needing to be whitelisted. Machine Learning Services in Azure SQL Managed Instance is currently in preview. The sign up process is described here: https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/machine-learning-services-overview#signup. The sign-up process is being modified at the moment, so the specific steps described in the article are a little off right now. But you basically need to create a support ticket where you request to be added to the preview, providing your subscription, logical server name, and region.

**Comment by garyericson** [comment]
#please-close
