### ISSUE TITLE
Type of Columnstore index you can create

### ISSUE THREAD

**Issue by kevchant** [MicrosoftDocs/sql-docs#5012]
Hi, from the testing I've done it looks like the version of Columnstore index you can create depends entirely on the SQL Server version regardless of the compatibility level of your database if you are using the on-premises version of SQL Server. 

For example, I'm been testing and I am able to create clustered Columnstore indexes on databases that have SQL Server 2012 compat level.

If this is true, can it be highlighted here for others?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 571bf244-1472-286b-d1a8-7db2e54f40a2
* Version Independent ID: bccbd120-47f3-78b7-0cd6-7d4198ea3604
* Content: [Columnstore indexes: Overview - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-overview?view=sql-server-ver15)
* Content Source: [docs/relational-databases/indexes/columnstore-indexes-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/columnstore-indexes-overview.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@kevchant -- thank you for your feedback and question.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
@kevchant - compatibility level allows the database Transact-SQL and query processing behaviors to align with older versions of SQL Server. The instance of SQL Server still has all of the features available with its current version.  This doesn't seem to be a distinction specifically related to Columnstore Indexes. 

If you'd like to submit a specific documentation update, go to the article, click **Edit** and submit a pull request. See [Contribute to SQL Server documentation](https://docs.microsoft.com/en-us/sql/sql-server/sql-docs-navigation-guide?view=sql-server-ver15#contribute-to-sql-documentation)

Thanks!
Mike
