### ISSUE TITLE
Long running query

### ISSUE THREAD

**Issue by kevchant** [MicrosoftDocs/sql-docs#5013]
Can this page give a Tip about the fact that if a long running query is taking place the online index operation will not complete until the query has finished. Because I had to look into the cause of a long running index maintenance job a while back and this was the cause of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64a32f57-da82-cdb9-56f6-f08b35e972b8
* Version Independent ID: b8ae2486-4d95-73fd-c7c8-da043ffb7526
* Content: [How Online Index Operations Work - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/how-online-index-operations-work?view=sql-server-ver15)
* Content Source: [docs/relational-databases/indexes/how-online-index-operations-work.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/how-online-index-operations-work.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@kevchant -- thank you for your suggestion.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
@kevchant for the suggestion. [Guidelines for online index operations - Performance considerations](https://docs.microsoft.com/sql/relational-databases/indexes/guidelines-for-online-index-operations) specifically says 

> Although online index operations permit concurrent user update activity, the index operations will take longer if the update activity is very heavy. Typically, online index operations will be slower than equivalent offline index operations regardless of the concurrent update activity level.

It sounds like you're looking for a little more specific information on [How Online Index Operations Work - SQL Server](https://docs.microsoft.com/sql/relational-databases/indexes/how-online-index-operations-work). What would you recommend we add on that page?

**Comment by MikeRayMSFT** [comment]
Accidentally closed. Reopened for customer to respond.

**Comment by MikeRayMSFT** [comment]
@pmasl or @bluefooted do we have anything specific to add to the documentation?

**Comment by bluefooted** [comment]
I'm not sure where to put this in the article, but I think @kevchant is talking about the very end of the operation when the index rebuild is trying to get a SCH-M lock. Any outstanding queries against the table will block this SCH-M lock, so it can take a long time before the rebuild operation can acquire the lock. While it's in the queue waiting for the lock, it may block other transactions as well. There's an option called WAIT_AT_LOW_PRIORITY (sometimes referred to as managed lock priority) which can be used on the index rebuild command to influence how long the rebuild will wait, and what will happen when the wait time is exceeded. The details of how this works are here: https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-index-option-transact-sql?view=sql-server-ver15#arguments

In this article, there's a reference right after the table that talks about the types of locks that are acquired on the source object during the index rebuild operation:
_* The index operation waits for any uncommitted update transactions to complete before acquiring the S lock or SCH-M lock on the table._

This might be a good place to add a note.

**Comment by kevchant** [comment]
Really sorry for the delay, been busy with wife's birthday present.

Anyway, @bluefooted is right that is exactly what I am talking about. 

I think the suggestion about adding the note there is perfect because I've had to go through this issue at a couple of places now.

**Comment by MikeRayMSFT** [comment]
Thanks both. We're submitting an update.
