### ISSUE TITLE
No reference to Azure SQL

### ISSUE THREAD

**Issue by soumya-parida** [MicrosoftDocs/sql-docs#5018]
The page is misleading, it "applies" to Azure SQL but does not provide any reference to importing or exporting data from Azure SQL. There are no reference to how to connect to Azure SQL from the SQL Server Import an d export Wizard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dba49af1-3e8f-3dd2-c979-b58df139e183
* Version Independent ID: 6d4b133e-09ba-a2de-9cee-f4f4ad156bc3
* Content: [Import & export data from SQL Server & Azure SQL Database - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/overview-import-export?view=sql-server-ver15)
* Content Source: [docs/relational-databases/import-export/overview-import-export.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/overview-import-export.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@soumya-parida -- Soumya, thank you for your feedback.

@MashaMSFT -- Masha, please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @soumya-parida , thanks for your feedback! My apologies for the delay. All of these methods should work with Azure SQL Database. Would you mind clarifying what you mean  by connect to Azure SQL using the import and export wizard? When you connect to your Azure SQL Database in SSMS, there is no additional step to connect to your database using the wizard. Or are you connected to another instance of SQL Server and then trying to import to Azure SQL Database? 

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @soumya-parida , it's been some time since we've heard from  you so we're going to close out this Git Issue. However, if you need anything further, please feel free to comment.

Thanks and hope you have a great rest of your day!
Masha from the SQL Docs team
