### ISSUE TITLE
Does overlaps duplicated?

### ISSUE THREAD

**Issue by lousaibiao** [MicrosoftDocs/sql-docs#5020]
I found two STOverlaps in https://docs.microsoft.com/en-us/sql/relational-databases/spatial/create-construct-and-query-geometry-instances?view=sql-server-ver15#rel

![pic](https://images.cnblogs.com/cnblogs_com/sheldon-lou/1623385/o_2006220915341.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765ed641-4c8e-4239-cd41-c330e1bcf000
* Version Independent ID: 8f7f2d13-6098-41e0-7575-d50686ace082
* Content: [Create, Construct, and Query geometry Instances - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/create-construct-and-query-geometry-instances?view=sql-server-ver15#querying)
* Content Source: [docs/relational-databases/spatial/create-construct-and-query-geometry-instances.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/spatial/create-construct-and-query-geometry-instances.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@lousaibiao -- thank you for your question and your close reading.  Each of those duplicates clarifies a slightly different aspect of geometry, although logically they mean the same.  

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

cc @MladjoA for awareness
