### ISSUE TITLE
Dangerous recommendation: run SQL Server as AD Domain Admin so it can register itself its SPN

### ISSUE THREAD

**Issue by cnotin** [MicrosoftDocs/sql-docs#5023]
We can read the following in the documentation:

> To register the SPN, the Database Engine must be running under a built-in account, such as Local System (not recommended), or NETWORK SERVICE, or an account that has permission to register an SPN, such as a **domain administrator account**

Even if it's suggested as last resort, running SQL Server as Active Directory "domain administrator" is highly discouraged for security reasons.
I suggest removing this recommendation, or at least adding a strong warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16136000-fc6d-9156-499a-c45bde264bc4
* Version Independent ID: ea9aacfc-8f27-563f-08c8-77ac4e941cff
* Content: [Register a Service Principal Name for Kerberos Connections - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections?view=sql-server-ver15#Permissions)
* Content Source: [docs/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@cnotin -- Clément, thank you for your suggestion.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
Thank you, @cnotin, for this comment.

As such, we have updated the permission paragraph to state that using a domain admin account is not recommende din a production environment. 

The changes should show by end of week.

thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
