### ISSUE TITLE
Missing Version Number

### ISSUE THREAD

**Issue by PhilipKelley** [MicrosoftDocs/sql-docs#5025]
As of Jun 22, 2020, 11:50am CST, the "Note" in this entry reads as follows:

> In versions of SQL Server and later, sub-securables cannot use brackets in the form '[sub name]'. Use 'sub name' instead.

This is unclear. Presumably, a SQL edition (2012, 2016, etc.) should be listed here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dbdc572-f77b-c2d6-03c9-158cdbd4a3c1
* Version Independent ID: 99a53116-e283-282a-a900-6dbaa38cce43
* Content: [HAS_PERMS_BY_NAME (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/has-perms-by-name-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/has-perms-by-name-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/has-perms-by-name-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@PhilipKelley -- Philip, thank you for your feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @PhilipKelley! Thanks for the feedback. I apologize for the delay. We are fixing this doc, and will be removing the reference to a SQL Server version. Currently, our documentation should reference what versions of SQL Server it applies to at the top, and are aimed only at supported versions of SQL Server for this doc.

Thanks again for your feedback on our documentation!
