### ISSUE TITLE
Small spelling error in download-sql-server-management-studio-ssms.md

### ISSUE THREAD

**Issue by Jbekker** [MicrosoftDocs/sql-docs#5031]
Spelling mistake line ~119:
These components aren't **uninstall** because they can be shared with other products. If uninstalled, you may run the risk of disabling other products.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-gb/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
Fixed in #5028

**Comment by WilliamAntonRohm** [comment]
@dzsquared -- Drew, thank you for fixing this typo.
