### ISSUE TITLE
How to tell what version of sqlpackage.exe we have is?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/sql-docs#5032]
The only thing I can find is a copyright for 2016, and I think the MSI on this page is later than that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3df6af-9ac8-bc57-93dc-29ff713c1d3b
* Version Independent ID: 7624e2cc-7aa9-40dd-4015-3371ea2ea0a2
* Content: [Download and install sqlpackage - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-ver15)
* Content Source: [docs/tools/sqlpackage-download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage-download.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by pensivebrian** [comment]
Right now, the only way is to right click on the sqlpackage.exe file, select properties, and on the details tab, check the file version.

I'll add a /version parameter next release. I'll update the copyright and print the version in the header as well :)

Thanks for reporting.

**Comment by WilliamAntonRohm** [comment]
@StingyJack -- thank you for your question.

@pensivebrian -- thank you for answering!

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
