### ISSUE TITLE
Install of ODBC driver for Debian 10 is currently (Jun 24 2020) not possibly. "unexpected size" issue

### ISSUE THREAD

**Issue by kvrban** [MicrosoftDocs/sql-docs#5036]
Install of ODBC driver for Debian 10 is currently (Jun 24 2020) not possibly because of:

`Failed to fetch https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-amd64/Packages.bz2  File has unexpected size (43969 != 43653)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@kvrban -- thank you for your feedback.  This issue has been resolved; please try again.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
