### ISSUE TITLE
Latest package update is causing docker build failure

### ISSUE THREAD

**Issue by harshavemuluru-gep** [MicrosoftDocs/sql-docs#5037]
After the update released on 24-Jun-2020 15:09. Docker builds command is failing after the URL is added to source list.

I have explained the problem here.
https://stackoverflow.com/questions/62559934/where-can-i-get-older-version-of-this-package-as-new-version-is-failing-my-docke

![image](https://user-images.githubusercontent.com/44601878/85596901-c0c14600-b667-11ea-8e8b-173ae54771ac.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@harshavemuluru-gep -- Vemuluru, thank you for your feedback. This issue has been resolved; please try again.

I am closing this issue now. You are welcome to @ mention me for any followup.
We hope to hear from you again.
