### ISSUE TITLE
Creating login with contained database user

### ISSUE THREAD

**Issue by mmannion** [MicrosoftDocs/sql-docs#5042]
Under _Typical Scenario_ > _If the person connecting will be connecting to only one database_, the first step is to "Create a login...". The goal, however, appears to be to create a contained database user. Per prior information in this same page, and in the related doc on contained databases, I believe that a login is not required.

If my understanding is correct, it would help to either:

1. Remove the step for creating a login, or;

1. Elaborate as to why a login is recommended here, even when creating a contained database user

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5712ad60-1a28-d778-aeb7-251b4cea45bf
* Version Independent ID: 58fa9e44-f8a3-1eb0-d0dc-21e915d1868c
* Content: [Getting Started with Database Engine Permissions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/getting-started-with-database-engine-permissions?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/authentication-access/getting-started-with-database-engine-permissions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/getting-started-with-database-engine-permissions.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @mmannion - Thanks for bringing up this issue.

@AndreasWolter - What are your thoughts on this? https://docs.microsoft.com/sql/relational-databases/security/authentication-access/getting-started-with-database-engine-permissions?view=sql-server-ver15#if-the-person-connecting-will-be-connecting-to-only-one-database

@mmannion is right that there is no need to create a login for the Windows group if the intent is to create a contained database user, and the users are only connecting to a single database. My thoughts are to remove the step to create the login. Let me know if I'm missing something. Thanks!

**Comment by AndreasWolter** [comment]
thanks for catching that. As its written that does not make sense.
Either one creates a user based on a Login, OR a contained user.
But contained users are only available if the database is set to Containment = Partial. That has a few more implications than just allowing contained users. So it is a conscious decision to take.
Many enterprises want to keep control of who can access which databases on the server level.

**Comment by VanMSFT** [comment]
Document has been updated and the steps to create the login has been removed.

@mmannion - Thank you very much for your feedback on this doc. We really appreciate your help! I apologize for the delay.
