### ISSUE TITLE
Memory contention between sqlservr.exe and fdhost.exe. Is this still relevant ?

### ISSUE THREAD

**Issue by pierrejeandev** [MicrosoftDocs/sql-docs#5044]
Per the doc, since SQL Server 2008, the Full-Text Engine is part of the sqlservr.exe process. 
Are the remarks on memory contention between sqlservr.exe and fdhost.exe still relevant ?
May be you should clarify this point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1557aca-6d60-4fc0-0d33-81b595435d98
* Version Independent ID: 82924924-2519-7016-fb6d-3ed5734fd6eb
* Content: [Improve the Performance of Full-Text Indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/search/improve-the-performance-of-full-text-indexes?view=sql-server-ver15&source=docs)
* Content Source: [docs/relational-databases/search/improve-the-performance-of-full-text-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/search/improve-the-performance-of-full-text-indexes.md)
* Product: **sql**
* Technology: **search**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by rothja** [comment]
@pmasl Pedro, the [full text index article](https://docs.microsoft.com/en-us/sql/relational-databases/search/improve-the-performance-of-full-text-indexes?view=sql-server-ver15&source=docs) talks a lot about FDHOST, and @pierrejeandev is wondering whether this is still valid (whether all of the process memory would be covered in sqlservr.exe). In reading the docs, it is not clear to me whether FDHOST is still used in recent versions of SQL Server. For example, [https://docs.microsoft.com/en-us/sql/tools/configuration-manager/sql-full-text-filter-daemon-launcher-sql-server-configuration-manager?view=sql-server-ver15](https://docs.microsoft.com/en-us/sql/tools/configuration-manager/sql-full-text-filter-daemon-launcher-sql-server-configuration-manager?view=sql-server-ver15).

**Comment by pmasl** [comment]
It is current yes. The FDHost is used for full-text search filtering and word breaking. You can see more about how this process is used with the SQL Server process in this page: https://docs.microsoft.com/en-us/sql/relational-databases/search/full-text-search?view=sql-server-ver15#architecture
