### ISSUE TITLE
Possible incorrect logic description for to_lsn parameter?

### ISSUE THREAD

**Issue by nbarnwell** [MicrosoftDocs/sql-docs#5046]
The document contains the text:

> Only rows in the cdc.[capture_instance]_CT change table with a value in __$start_lsn **less than or equal to from_lsn or equal to to_lsn** are included in the result set.

That sounds wrong, and I'm concerned it should be:

> Only rows in the cdc.[capture_instance]_CT change table with a value in __$start_lsn **less than or equal to to_lsn** are included in the result set.

Which would then indicate that values between from_lsn and to_lsn, inclusive, are returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec947a0e-704f-ae89-9141-1e11d23c9d14
* Version Independent ID: 9a5607af-a10e-cf21-e212-65da9f7a4b25
* Content: [cdc.fn_cdc_get_all_changes_&lt;capture_instance&gt;  (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/cdc-fn-cdc-get-all-changes-capture-instance-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-functions/cdc-fn-cdc-get-all-changes-capture-instance-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-functions/cdc-fn-cdc-get-all-changes-capture-instance-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@nbarnwell -- Neil, thank you for your question.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@rothja -- Jason, please review [private PR 15764](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15764).

**Comment by rothja** [comment]
@WilliamAntonRohm Thank you, I'll take a look!

**Comment by rothja** [comment]
@nbarnwell Neil, sorry for the delay on this. I am talking to some people internally to confirm. Did you confirm this behavior in any tests you ran? Also, I assume this wasn't blocking you in any design or implementation work? Thank you! Adding @Sait-MSFT to the issue. #assign:@Sait-MSFT

**Comment by nbarnwell** [comment]
No I haven't been able to, really. Because these values represent pointers to the transaction log, it's hard to make a deterministic test that proves one way or the other. It's not really blocking me at the moment, I just came for the rules on how it worked and found the writing didn't really make logical sense. So either it could be written more clearly (or an example provided), or it's literally incorrect.

**Comment by rothja** [comment]
@nbarnwell Thanks, Neil, for the additional details. Appreciate you pointing out the confusion (and possible error) here. If I can get a conclusive answer internally, we'll change this. Thank you.

**Comment by rothja** [comment]
@nbarnwell Thanks again for your patience. I believe that you are right when you think of what it is trying to show logically. I am going to approve this, although I have not gotten final product team confirmation. @Sait-MSFT I believe this is right and we are proceeding with the fix, but if you review later and determine there was a nuance we didn't understand, please let me know and we'll correct it. Thank you!

**Comment by Sait-MSFT** [comment]
@nbarnwell is right that this statement is incorrect. It should be changed as following.

Only rows in the cdc.[capture_instance]_CT change table with a value in __$start_lsn greater than or equal to from_lsn and less than or equal to to_lsn are included in the result set.
