### ISSUE TITLE
Table "not supported" by SQL DW

### ISSUE THREAD

**Issue by potato-enthusiast** [MicrosoftDocs/sql-docs#5047]
This table is available on my SQL DW instance. Should this page be updated to indicate that it applies to SQL DW?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2a9f49-f432-6702-7987-854f00ceae93
* Version Independent ID: 1b80bc28-fe12-077a-4cd1-94eec13af354
* Content: [sys.pdw_table_mappings (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-pdw-table-mappings-transact-sql?view=aps-pdw-2016-au7)
* Content Source: [docs/relational-databases/system-catalog-views/sys-pdw-table-mappings-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-pdw-table-mappings-transact-sql.md)
* Product: **sql**
* Technology: **data-warehouse**
* GitHub Login: @ronortloff
* Microsoft Alias: **rortloff**

**Comment by WilliamAntonRohm** [comment]
@potato-enthusiast -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@ronortloff -- Ron, please review [private PR 15765](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15765).

**Comment by WilliamAntonRohm** [comment]
@potato-enthusiast -- we have updated the documentation and it should be live by tomorrow.
