### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by potato-enthusiast** [MicrosoftDocs/sql-docs#5049]
In the description for <inherited columns>:

> For a list of columns that this view inherits, see sys.objects.

The link to sys.objects incorrectly links to sys.dm_pdw_request_steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c77bc02b-3f13-a20a-c166-7afff401ed43
* Version Independent ID: 172adabd-d817-09db-c3d3-972f436e28e7
* Content: [sys.pdw_nodes_tables (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-pdw-nodes-tables-transact-sql?view=aps-pdw-2016-au7)
* Content Source: [docs/relational-databases/system-catalog-views/sys-pdw-nodes-tables-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-pdw-nodes-tables-transact-sql.md)
* Product: **sql**
* Technology: **data-warehouse**
* GitHub Login: @ronortloff
* Microsoft Alias: **rortloff**

**Comment by WilliamAntonRohm** [comment]
@potato-enthusiast -- thank you for finding that.  I am looking into the article.
