### ISSUE TITLE
sys.dm_os_sys_info listed as not supported for Azure SQL Database

### ISSUE THREAD

**Issue by amthomas46** [MicrosoftDocs/sql-docs#5058]
sys.dm_os_sys_info listed as not supported for Azure SQL Database, however, I am able to run it in the context of my database 
![image](https://user-images.githubusercontent.com/28786161/86039273-134b8b00-b9f7-11ea-9bcb-009257e664cb.png) as well as in the context of master
![image](https://user-images.githubusercontent.com/28786161/86039343-23636a80-b9f7-11ea-8cd3-e88d7384c998.png)

Is it possible but not supported? Or is it not supposed to be possible? Or did something change?

Thanks,
Anna

cc @rgward 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1073200-d5d6-a64e-d8d8-a4809873822b
* Version Independent ID: aab7789b-e333-2d9a-bfb9-52106184c156
* Content: [sys.dm_os_sys_info (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql?view=sql-server-ver15&viewFallbackFrom=azuresqldb-current)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@amthomas46 -- Anna, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@CarlRabeler -- Carl, please review [private PR 15768](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15768).
