### ISSUE TITLE
Need Azure differences on ALL documentation

### ISSUE THREAD

**Issue by amommy** [MicrosoftDocs/sql-docs#5059]
There needs to be more info on all SQL doc pages for managed instances or make all new documentation for azure sql (database and managed) because the docs that are available lack vital information especially 'no longer applies'. 
Updating security checks on managed instance and need to justify why audits set to maximum maxsize and max_rollover_files no where does it say why or that it just doesn't apply.
Would really be great if azure documentation was overhauled all together.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f12db5-fb2d-728c-8456-b3bc37961a17
* Version Independent ID: 026880d7-f057-0ef1-dfea-4e6d6be62132
* Content: [CREATE SERVER AUDIT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-server-audit-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-server-audit-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-server-audit-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@amommy -- thank you for your feedback.  We are in a continual process of updating the SQL Server Documentation to be more accurate with Azure SQL Database and Azure SQL Managed Instance. We're sorry the docs do not cover all scenarios yet in detail.

If you find something on a specific page, you are welcome to open a GitHub issue on that page to request that we make it more accurate, or you can edit the page to be clearer about anything, including Azure SQL support. 

You're welcome to add this feedback here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  Please @ mention me for any followup. We hope to hear from you again.
