### ISSUE TITLE
Wrong version for Linux in download link

### ISSUE THREAD

**Issue by krishnamsft20** [MicrosoftDocs/sql-docs#5061]
[When we click tar.gz, it downloads 8.2.0.0 not 8.2.2.0]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cded3d0-9d0a-ce94-1c91-21de62e3ddaf
* Version Independent ID: c14c4066-056b-faea-0a28-5eba2c544a43
* Content: [Download Microsoft JDBC Driver for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@krishnamsft20 -- thank you for your feedback.

@David-Engel -- please look into this issue.

**Comment by David-Engel** [comment]
Fixed. Thanks!

#please-close
