### ISSUE TITLE
Inconsistent type casing (CAPS or smallcase)

### ISSUE THREAD

**Issue by ite-klass** [MicrosoftDocs/sql-docs#5064]
What is the intended convention for type name casing? The examples are mostly CAPS, but also sometimes smallcase.

I’ve seen it lowercase in other places (DECLARE) but here types seem to be CAPS for the most part, but not exclusively.

Create script in MSSQLSMS seems to create them in smallcase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be5dfc7-5496-f8ec-072f-81132fe92054
* Version Independent ID: 634e3c60-d717-92ba-dd93-e3773edf2816
* Content: [CREATE TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@ite-klass -- Jan, thank you for your feedback.  I am investigating.

**Comment by CarlRabeler** [comment]
There is no official policy - but a lot of community standards - for example, see https://www.sqlservercentral.com/articles/sql-server-name-convention-and-t-sql-programming-style. This said, with so many contributors to T-SQL code over so many years, there is no standard convention that has been followed.

**Comment by WilliamAntonRohm** [comment]
@CarlRabeler -- thank you for responding.

**Comment by ite-klass** [comment]
And I take this as also no intention to introduce one or make the documentation consistent.
