### ISSUE TITLE
Missing details of permissions and class for database-scoped credentials

### ISSUE THREAD

**Issue by RobAshton-IM** [MicrosoftDocs/sql-docs#5075]
The documentation page for the sys.database_permissions view doesn't include any details for the "database scoped credential" object type introduced in SQL Server 2016/2017, [sys.database_scoped_credentials](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-scoped-credentials-transact-sql?view=sql-server-ver15)

Could these details be added please? I can see from [this page](https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-database-scoped-credential-transact-sql?view=sql-server-ver15) what possible permissions can be granted/denied over those objects (i.e. ALTER, CONTROL, REFERENCES, TAKE OWNERSHIP, VIEW DEFINITION), but I need to know what Class value is used to represent those permissions in the sys.database_permissions view for a report I'm writing, and I don't see a record of that anywhere online.

Kind regards,
Rob Ashton

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78080f83-be60-8136-9a97-dee7cae49df4
* Version Independent ID: 07cbb880-46a7-3da7-21ad-00b9de39eccb
* Content: [sys.database_permissions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-permissions-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-catalog-views/sys-database-permissions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-database-permissions-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@RobAshton-IM -- Rob, thank you for your feedback and question.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hey @AndreasWolter - Can you please help with this?

**Comment by AndreasWolter** [comment]
Hi @Steven<mailto:Steven.Gott@microsoft.com>

I think for Database Scoped Credential there is no dedicated permission
The Doc mentions “ALTER on the Credential”, but how could you have that?

For Create it is:

Requires CONTROL permission on the database.
I think the same applies to ALTER/DROP

And hence there is no special entry in permissions.
Is that right?

Thanks
Andreas
-----------------------------------------------
Andreas Wolter | Senior Program Manager
MCM, MCSM | Data Platform Security
Twitter<https://twitter.com/AndreasWolter> | Linkedin<https://www.linkedin.com/in/andreaswolter/>

**Comment by RobAshton-IM** [comment]
Hi Andreas, while DSC permission inheritance worked the way you describe in SQL Server 2016 when they were first introduced, the latest version of the [SQL Server permissions poster](https://aka.ms/sql-permissions-poster) shows that ALTER, CONTROL, REFERENCES, TAKE OWNERSHIP, and VIEW DEFINITION permissions were added to database scoped credentials in SQL Server 2017 onwards and Azure SQL Database at the same time.

Unless DSC's have a fundamentally different way of associating permissions, grantee, grantor, objects and state (DENY/GRANT/GRANT WITH GRANT) together, I assume they are represented in sys.database_permissions with a specific Class value, however I currently don't have access to an example to confirm that myself.

Kind regards,
Rob Ashton

**Comment by RobAshton-IM** [comment]
Also, while we're at it... :)

Could the same question be asked of Full Text Search Property Lists, or does that want raising as a separate issue?

Kind regards,
Rob Ashton

**Comment by VanMSFT** [comment]
Hi @RobAshton-IM - Sorry for the delay. This fell off my radar and I apologize. Let me follow-up internally.

#reassign:AndreasWolter

**Comment by VanMSFT** [comment]
Checking back with Andreas

**Comment by VanMSFT** [comment]
Revisiting with Andreas

**Comment by rwestMSFT** [comment]
We're still following up on this.

**Comment by rwestMSFT** [comment]
Hi @RobAshton-IM, the class is listed on the `sys.database_permissions` article (`32`), so I'm closing this issue.
