### ISSUE TITLE
Sentence can be interpreted in two different ways...

### ISSUE THREAD

**Issue by rjrjack** [MicrosoftDocs/sql-docs#5077]
When I read the below sentence in Design Recommendatilons
        "Redesign nonclustered indexes with a large index key size so that only columns used for searching and lookups are key columns"
I read it to mean redesign the index so that it has a large index key size.

I think the sentence should say
       " Redesign nonclustered indexes that have a large index key size so that only columns used for searching and lookups are key columns"

This is not a major point, but changing the sentence might save novices a bit of confusion.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 513e0ea1-70af-5a56-9b42-8d2e173d4176
* Version Independent ID: 0b04a8fa-17f1-1bee-a1f6-2064a11e05ee
* Content: [Create Indexes with Included Columns - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/create-indexes-with-included-columns?view=sql-server-ver15)
* Content Source: [docs/relational-databases/indexes/create-indexes-with-included-columns.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/create-indexes-with-included-columns.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@rjrjack -- thank you for your feedback.  I am looking into this wording.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review [private PR 15769](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15769).
