### ISSUE TITLE
Confusing Text

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#5078]
"This article is valid for SQL Server 2012, but not for SQL Server 2014 or later. For DAC articles about SQL 2012 and earlier, see the following links:"

The above is confusing, as there is no provided link for SQL Server 2014 or later.  Please provide a link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f0297c-1e1f-fe6e-4b0f-9fd5d2cebfd8
* Version Independent ID: 55771482-ffea-379b-8f32-11ddd69bb301
* Content: [DAC Support For SQL Server Objects and Versions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/dac-support-for-sql-server-objects-and-versions?view=sql-server-ver15)
* Content Source: [docs/relational-databases/data-tier-applications/dac-support-for-sql-server-objects-and-versions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/dac-support-for-sql-server-objects-and-versions.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@PrometheusRising1 -- thank you for your feedback.  Please see [Previous versions of SQL Server documentation](https://docs.microsoft.com/en-us/sql/sql-server/previous-versions-sql-server?view=sql-server-ver15).

@stevestein -- please look into this issue.  If you provide me with the link, I'll create a PR to update this article.

**Comment by stevestein** [comment]
@PrometheusRising1 - thanks for raising this issue. The article is for a previous version, and there's no updated documentation at this time.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
