### ISSUE TITLE
CURRENT_TIMESTAMP and DATE() functions have same description

### ISSUE THREAD

**Issue by phil-shin** [MicrosoftDocs/sql-docs#5082]
CURRENT_TIMESTAMP and GETDATE() functions have same description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972a4352-4957-49fc-0c39-3e254d130fe7
* Version Independent ID: cc865d87-1527-9f72-3cbc-7b036f4503df
* Content: [Date and Time Data Types and Functions - SQL Server (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/date-and-time-data-types-and-functions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/date-and-time-data-types-and-functions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@phil-shin -- Phil, thank you for your feedback.  My understanding is that CURRENT_TIMESTAMP and GETDATE return the same datetime for a given instant, and so those descriptions are equally correct.

cc @markingmyname for awareness
