### ISSUE TITLE
FORMAT letter options are not listed and F for Floating Point is not in example

### ISSUE THREAD

**Issue by data-architect-tampa** [MicrosoftDocs/sql-docs#5090]
There is no list of all possible options for the 2nd argument. 

Pn  - Percentage
Fn - Floating point
etc.

No example with F is included.
select format(1.222222222,'F2')   produces '1.22'

I was looking for this and had to guess myself what the answer was.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f019407-5787-6f54-1027-084e817b6b8e
* Version Independent ID: a92541d0-b63a-9603-2a1f-18e210be89e4
* Content: [FORMAT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/format-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/format-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/format-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@data-architect-tampa -- thank you for your feedback.  Please see this article:
- [Standard numeric format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings)

**Comment by data-architect-tampa** [comment]
I thought the Format function was the landing page.   I don't see a
reference to the standard formatting strings from the landing page.

Use case: search for "sql server format function".   See if you can get the
link you gave me.  I have had this trouble before.
