### ISSUE TITLE
Vague description of return type and length in CONCAT.

### ISSUE THREAD

**Issue by chrisspre** [MicrosoftDocs/sql-docs#5091]
The phrase "A string value whose length and type depend on the input." under return type is quite vague.

When writing recursive CTE it is useful to know what the type and length of the results to avoid the error "Types don't match between the anchor and the recursive part in column..." . This can be avoided by extensive casting which seems redundant and can be error prone. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f748e679-fde4-3cc7-4200-7b45adb74a21
* Version Independent ID: 6946f36e-4731-1ed9-365a-0085103a630e
* Content: [CONCAT_WS (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/concat-ws-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/concat-ws-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/concat-ws-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@chrisspre -- Christof, thank you for your feedback.  Please see the CONCAT article referenced in this article's Remarks:
- https://docs.microsoft.com/en-us/sql/t-sql/functions/concat-transact-sql?view=sql-server-ver15#remarks
