### ISSUE TITLE
In the Portal english version of the document, the step to create the key in the Key Vault is missing. French Powershell version indicates it.

### ISSUE THREAD

**Issue by LudoBoggioTotal** [MicrosoftDocs/sql-docs#5094]
Creation of the Key in the newly created Key Vault is missing in the English Portal version. The French Powershell version indicates it (but it didn't say the "list" rights has to be given)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4997f245-c966-51a3-34c7-705c3cfbd4b0
* Version Independent ID: 129fbe40-3b02-f2c1-ef13-b42d86ffdb77
* Content: [Set up Transparent Data Encryption (TDE) Extensible Key Management with Azure Key Vault - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-ver15&tabs=portal#step-4-configure-)
* Content Source: [docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@LudoBoggioTotal -- Ludovic, thank you for your helpful feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
@Rupp29 - Hey Adrian, can you please take a look at this issue?

**Comment by Rupp29** [comment]
I’m not sure I follow what the problem is?
I’m not sure how to view the French version and even if I could, would it be obvious what I’m looking for?

Screen shots got a long way in explaining the issue.
Happy to check it out but need a nudge in the correct direction.


::Adrian
425.753.4998

**Comment by VanMSFT** [comment]
@Rupp29 - I think in [step 2](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-ver15&tabs=portal#step-2-create-a-key-vault), @LudoBoggioTotal mentions that we create a key vault, but not a key. @LudoBoggioTotal - Is that correct?

**Comment by VanMSFT** [comment]
We'll follow-up internally on the French version update. Thanks!

**Comment by Rupp29** [comment]
A little further down it does create a key:
Create a new key
Alternatively, you can create a new encryption key directly in your Azure key vault and make it either software-protected or HSM-protected. In this example, let's create a software-protected key by using the Add-AzureKeyVaultKey cmdlet:
PowerShellCopy
Add-AzureKeyVaultKey -VaultName 'ContosoEKMKeyVault' `
  -Name 'ContosoRSAKey0' -Destination 'Software'


[cid:image001.png@01D6547F.672228C0]

::Adrian
425.753.4998

**Comment by LudoBoggioTotal** [comment]
Hello,
Sorry for mentionning the French version, I can understand that you're not familiar with the language. I've been looking in the page I mentionned (https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-ver15&tabs=portal), so with PORTAL instructions, and I couldn't find the mention you're providing to create a key.
Step 2 creates a key vault and the policy; Step 3 installs the SQL connector; Step 4 helps configuring the SQL server, but key is never created.

**Comment by Rupp29** [comment]
Thanks for the feedback @LudoBoggioTotal - This document has gone through a few iterations and the key generation step must have been (accidentally) missed, dropped or deleted and is not part of the  documentation (portal section). I will add that as an update to the doc.  If you need specific assistance with that, I can add the step for you until the docs are updated (with screenshots) - unfortunately that might take a couple weeks.

**Comment by LudoBoggioTotal** [comment]
No problem, I totally understand.
Actually, I don't need help as I found the missing information on the French translation, and checked it on the PowerShell version of the page for confirmation (and it's pretty easy steps :) ).

**Comment by VanMSFT** [comment]
Closing this. The documentation should be updated with a create a key portion.

![image](https://user-images.githubusercontent.com/40007119/101545487-2c6c4680-395c-11eb-95a1-1ccb0a4d71e5.png)

Thanks again, @LudoBoggioTotal!
