### ISSUE TITLE
Misspell

### ISSUE THREAD

**Issue by ltlombardi** [MicrosoftDocs/sql-docs#5120]
"Missing a updated row or seeing an updated row multiple times"
should be "Missing aN updated row or seeing an updated row multiple times"
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dae81d65-f7b9-7a97-7fe7-30775f815e5b
* Version Independent ID: d4d339e7-48d7-d159-eb59-13bdedc25b4c
* Content: [Transaction Locking and Row Versioning Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-ver15)
* Content Source: [docs/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@ltlombardi -- thank you for catching that.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
