### ISSUE TITLE
SSMS Startup Arguments

### ISSUE THREAD

**Issue by AdamFinster** [MicrosoftDocs/sql-docs#5123]
Missing details for the -P parameter (The password associated with the login)

This parameter is displayed in the command-line display for "ssms -?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 179d9df0-cfc8-d9f2-babc-e9b7d0732d87
* Version Independent ID: c458bccb-8bba-f94c-658c-5d35eab7cdc7
* Content: [SSMS Utility - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/ssms-utility?view=sql-server-ver15)
* Content Source: [docs/ssms/ssms-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/ssms-utility.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@AdamFinster -- thank you for your feedback.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
@AdamFinster 

Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by markingmyname** [comment]
@AdamFinster

Article updated.

Expect changes to go live by Monday.

thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by AdamFinster** [comment]
@markingmyname - Thanks for the update. It is now visible in the Aruguements section, but the -P parameter is also missing from the Syntax section.

Also noted in the Remarks section (2nd paragraph) "_The -log switch must appear at the end of the command line, after all, other switches._"  should read "_The -log switch must appear at the end of the command line, after all other switches._" (removed 2nd comma)
