### ISSUE TITLE
Documentation outdated : AquireTokenAsync is obsolete

### ISSUE THREAD

**Issue by Tim-Bijnens** [MicrosoftDocs/sql-docs#5126]
This documentation seems to be outdated since authorizationcontext.AquireTokenAsync is obsolete and produces a warning in VS, please provide a solution that is free of this "obsolete" warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01456910-0583-1787-b8a8-2aef66378eec
* Version Independent ID: b55ac9e0-bdd7-8e3d-19d2-540b47ca2e58
* Content: [Example demonstrating use of Azure Key Vault provider with Always Encrypted - SQL Server](https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-key-vault-example?view=sql-server-ver15)
* Content Source: [docs/connect/ado-net/sql/azure-key-vault-example.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/ado-net/sql/azure-key-vault-example.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @karinazhou
* Microsoft Alias: **v-jizho2**

**Comment by WilliamAntonRohm** [comment]
@Tim-Bijnens -- Tim, thank you for your feedback.

@karinazhou -- Karina, please look into this issue.

**Comment by karinazhou** [comment]
Hi @Tim-Bijnens and @WilliamAntonRohm , 

I built the code example from [Example demonstrating use of Azure Key Vault provider with Always Encrypted - SQL Server](https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-key-vault-example?view=sql-server-ver15) locally and didn't see obsolete warnings from Visual Studio 2019. 

From [this page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext.acquiretokenasync?view=azure-dotnet#Microsoft_IdentityModel_Clients_ActiveDirectory_AuthenticationContext_AcquireTokenAsync_System_String_Microsoft_IdentityModel_Clients_ActiveDirectory_ClientCredential_), the `AuthenticationContext.AcquireTokenAsync` is still in use. The library we are using is `Microsoft.IdentityModel.Clients.ActiveDirectory`.

**Comment by Tim-Bijnens** [comment]
Hi,

That is strange, when I copy the Authentication callback code and put it in
my solution, I get the obsolete warning as shown in the attachment.
I AM using Microsoft.IdentityModel.Clients.ActiveDirectory (I let VS add
the using automatically)

Regards,
Tim Bijnens
*Development/Support - Samplified Europe*
Clementine | A Samplified Product
+32 (0)477 53 72 55 <+32477537255>
tim@askclementine.com
Tim BijnensThat is strange,
www.askclementine.com
Tim Bijnens <https://www.linkedin.com/in/timbijnens>


Disclaimer: The content of this message is confidential. If you have
received it by mistake, please inform us by an email reply and then delete
the message. It is forbidden to copy, forward, or in any way reveal the
contents of this message to anyone. The integrity and security of this
email cannot be guaranteed over the Internet. Therefore, the sender will
not be held liable for any damage caused by the message.


Op di 7 jul. 2020 om 00:48 schreef Karina Zhou <notifications@github.com>:

**Comment by karinazhou** [comment]
@Tim-Bijnens  The sample code already has the `using Microsoft.IdentityModel.Clients.ActiveDirectory;` at the beginning so I don't think you need to add it in the code manually. If you are testing the sample code in a new application, you can go to Nuget Manager to install the Microsoft.IdentityModel.Clients.ActiveDirectory nuget package from nuget.org. The latest version 5.2.8 works fine on both .net framework and .net core.

If you are writing your own application, do you also use other libraries such as `Microsoft.Identity.Client`? I find that `IPublicClientApplication.AcquireTokenAsync` is obsolete according to [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.ipublicclientapplication.acquiretokenasync?view=azure-dotnet) . 

If you are still facing the warning, can you share your repo application so I can test it on my side?

**Comment by cheenamalhotra** [comment]
@WilliamAntonRohm 

I believe this can be closed as there's no action item on any documentation updates.

**Comment by WilliamAntonRohm** [comment]
@cheenamalhotra -- Cheena, thank you for following up on this issue.
