### ISSUE TITLE
Link to a list of char codes

### ISSUE THREAD

**Issue by scottsealanddesign** [MicrosoftDocs/sql-docs#5130]
[It would be nice to have a link to the list of char codes.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8cf272b-3e28-160e-7e32-cf824766f87a
* Version Independent ID: cb16a55b-c7c3-8e5a-7b1e-9fb8d16cedc2
* Content: [CHAR (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/char-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/char-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/char-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@scottsealanddesign -- thank you for your suggestion.  Please see here for the complete list:
- https://en.wikipedia.org/wiki/ASCII

cc @markingmyname for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
