### ISSUE TITLE
Schema Lock

### ISSUE THREAD

**Issue by aschlick** [MicrosoftDocs/sql-docs#5132]
Recently found out that the alter schema command can put a schema level lock on. I think it would be useful to include that in this documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f606ee47-e635-c71e-2874-56d9e8938390
* Version Independent ID: 85d3a27d-3001-c27b-e0c8-47cc10fede97
* Content: [ALTER SCHEMA (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-schema-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/alter-schema-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-schema-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
Thank you @aschlick 
update will appear later today
