### ISSUE TITLE
ADLS Gen2 url pattern is bad and doesnt work anymore

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/sql-docs#5146]
the LOCATION pattern specified in this section of document for ADLSGen2 is bad and doesnt work anymore
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql?view=azure-sqldw-latest#b-create-external-data-source-to-reference-azure-data-lake-store-gen-1-or-2-using-a-service-principal

for the right way of representing a abfss path with ADLS Gen2, please check this
https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction-abfs-uri#uri-syntax

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e450abc6-2dbd-8f6c-423c-52aca37a2b06
* Version Independent ID: 4aff678a-6db1-a438-9aca-bb4b4d49bc27
* Content: [CREATE EXTERNAL DATA SOURCE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql?view=azure-sqldw-latest#b-create-external-data-source-to-reference-azure-data-lake-store-gen-1-or-2-using-a-service-principal)
* Content Source: [docs/t-sql/statements/create-external-data-source-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-data-source-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@mganeshphani -- Ganesh, thank you for your feedback, and for correlating the newer URI syntax.

@CarlRabeler -- Carl, please look into this issue.

**Comment by mganeshphani** [comment]
Quick question..Is the docs correction solely dependent on customers reporting?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by CarlRabeler** [comment]
Following up with internal resources...

**Comment by CarlRabeler** [comment]
updating article now

**Comment by CarlRabeler** [comment]
changes are live now
