### ISSUE TITLE
Client Components (bcp.exe and sqlcmd.exe) installer folder for 2017

### ISSUE THREAD

**Issue by sjzcao** [MicrosoftDocs/sql-docs#5147]
[Enter feedback here]
By document, for SQL Server 2017 Express, Client Components (bcp.exe and sqlcmd.exe) should be installed at <Install Directory>\Client SDK\ODBC\140\Tools\Binn. But actually, it is installed at <Install Directory>\Client SDK\ODBC\130\Tools\Binn. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ca4320-49c8-31a4-84c6-0185ba176216
* Version Independent ID: 04a1843f-813d-fe8e-611b-af6ada02ef01
* Content: [File Locations - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server?view=sql-server-ver15)
* Content Source: [docs/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@sjzcao -- thank you for your feedback.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
@sjzcao

Thank you for your feedback! 

The article describes the install path like so - <Install Directory>\Client SDK\ODBC\nnn\Tools\Binn.

https://docs.microsoft.com/en-us/sql/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server?view=sql-server-ver15#specifying-file-paths

It depends on what version of SQL Server is installed to determine what "numbered" folder it is located.

thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
