### ISSUE TITLE
Update text - Azure SQL Data Warehouse (Synapse) does now support auto creation of statistics

### ISSUE THREAD

**Issue by maxwiks** [MicrosoftDocs/sql-docs#5150]
In [this](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-as-select-azure-sql-data-warehouse?view=aps-pdw-2016-au7#limitations-and-restrictions) docs section it states that:

> Azure SQL Data Warehouse does not yet support auto create or auto update statistics. In order to get the best performance from your queries, it's important to create statistics on all columns of all tables after you run CTAS and after any substantial changes occur in the data.

However since the last couple of years Azure DW does support automatic creation of statistics. That section should be edited to support the "new" features available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d789618-4d39-1977-a4f3-520308f4f675
* Version Independent ID: a4e034e8-fc72-dd9b-c575-1ef81528c5cd
* Content: [CREATE TABLE AS SELECT (Azure SQL Data Warehouse) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-as-select-azure-sql-data-warehouse?view=aps-pdw-2016-au7)
* Content Source: [docs/t-sql/statements/create-table-as-select-azure-sql-data-warehouse.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-as-select-azure-sql-data-warehouse.md)
* Service: **sql-data-warehouse**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by julieMSFT** [comment]
#assign:julieMSFT

**Comment by julieMSFT** [comment]
#https://github.com/MicrosoftDocs/sql-docs-pr/pull/15936

**Comment by julieMSFT** [comment]
@maxwiks Hello, I have updated the article and you will see the changes later today. Thank you for your contribution to Microsoft Docs! I will proceed with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
