### ISSUE TITLE
References a Utility Explorer

### ISSUE THREAD

**Issue by drk-mtr** [MicrosoftDocs/sql-docs#5152]
But there is no Utility Explorer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d05f7a87-13d6-802e-0d8d-1af3290cc488
* Version Independent ID: a1042da6-6c8b-54ca-064a-7f673db0c404
* Content: [Remove an Instance of SQL Server from the SQL Server Utility - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/manage/remove-an-instance-of-sql-server-from-the-sql-server-utility?view=sql-server-ver15)
* Content Source: [docs/relational-databases/manage/remove-an-instance-of-sql-server-from-the-sql-server-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/manage/remove-an-instance-of-sql-server-from-the-sql-server-utility.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@drk-mtr -- thank you for your feedback.  I do not see it either:
- [Viewing Utility Explorer](https://docs.microsoft.com/en-us/sql/relational-databases/manage/use-utility-explorer-to-manage-the-sql-server-utility?view=sql-server-2017#viewing-utility-explorer)

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
@markingmyname -- could you look into this issue?

**Comment by drk-mtr** [comment]
Now that I understand this better, I think I was probably in the wrong part of the documentation. I suspect the Utility Explorer only appears if you've configured a UCP (utility control point) or something like that i.e. https://docs.microsoft.com/en-us/sql/relational-databases/manage/sql-server-utility-features-and-tasks?view=sql-server-ver15

This is what I was actually after, so of course please feel to close this issue if you feel the existing documentation re. Utility Explorer is ok as it stands: https://docs.microsoft.com/en-us/sql/sql-server/install/uninstall-an-existing-instance-of-sql-server-setup?view=sql-server-ver15&tabs=Windows10

**Comment by rothja** [comment]
@drk-mtr Thank you for the clarification. I am going to close the issue for now, but there are probably ways the documentation could be more clear that we could consider for future improvements. Thanks for reaching out! #reassign:rothja.

**Comment by PRMerger20** [comment]
rothja. is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by rothja** [comment]
#reassign:rothja
