### ISSUE TITLE
References to setting the SA password in the container is not consistent

### ISSUE THREAD

**Issue by wsmelton** [MicrosoftDocs/sql-docs#5153]
Multiple places setting the SA password for the SQL Server container are referenced as `SA_PASSWORD` while others are referenced as `MSSQL_SA_PASSWORD`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dc2ec36-4915-f7ab-3104-282acc9321e6
* Version Independent ID: fc98af17-f3c5-adff-69ca-593f985e7882
* Content: [Configuration options for SQL Server on Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-configure-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by WilliamAntonRohm** [comment]
@wsmelton -- Shawn, thank you for your feedback.

@vin-yu -- Vin, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @wsmelton! Thanks for your feedback. I am refreshing this article and will make the appropriate changes. They should be live next week.
