### ISSUE TITLE
BATCH_COMPLETED_GROUP minimal SQL Server version

### ISSUE THREAD

**Issue by vasek-cz** [MicrosoftDocs/sql-docs#5154]
BATCH_COMPLETED_GROUP is supposed to work for SQL Server 2016 and newer, however for SQL Server 2017 I am getting following:

```
Msg 40517, Level 16, State 1, Line 6
Keyword or statement option 'BATCH_COMPLETED_GROUP' is not supported in this version of SQL Server.
```

The documentation link: https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions?view=sql-server-2016

Same query works fine in SQL Server 2019. Can you please confirm the minimal SQL Server version for BATCH_COMPLETED_GROUP (and maybe other classes)?

**Comment by WilliamAntonRohm** [comment]
@vasek-cz -- Vasek, thank you for your question.

@DavidTrigano -- David, please look into this issue.

**Comment by DavidTrigano** [comment]
Hi @vasek-cz,

BATCH_COMPLETED_GROUP works with SQL Server 2019 only (same for BATCH_STARTED_GROUP)

@WilliamAntonRohm you can go ahead and close this request.
