### ISSUE TITLE
LOCATION argument/parameter not enclosed in quotes

### ISSUE THREAD

**Issue by BeginTry** [MicrosoftDocs/sql-docs#5155]
### CREATE EXTERNAL DATA SOURCE
The value for the **LOCATION** argument/parameter should be enclosed in single quotes, right?
I don't see it in either the syntax/definition or the example provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad6b54f-7b8d-0d9b-0ece-815b8874f751
* Version Independent ID: dee28cea-a153-0d80-b3f1-982aa4d16a87
* Content: [Access external data: ODBC generic types - PolyBase - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-configure-odbc-generic?view=sql-server-ver15)
* Content Source: [docs/relational-databases/polybase/polybase-configure-odbc-generic.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-odbc-generic.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@BeginTry -- Dave, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@BeginTry -- Dave, per [CREATE EXTERNAL DATA SOURCE](https://docs.microsoft.com/sql/t-sql/statements/create-external-data-source-transact-sql?view=sql-server-ver15#syntax) you are correct.  I have updated the documentation and it should be live by tomorrow.
