### ISSUE TITLE
CREATE EXTERNAL TABLE

### ISSUE THREAD

**Issue by BeginTry** [MicrosoftDocs/sql-docs#5156]
Was there supposed to be an ODBC-specific example for **CREATE EXTERNAL TABLE**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad6b54f-7b8d-0d9b-0ece-815b8874f751
* Version Independent ID: dee28cea-a153-0d80-b3f1-982aa4d16a87
* Content: [Access external data: ODBC generic types - PolyBase - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-configure-odbc-generic?view=sql-server-ver15)
* Content Source: [docs/relational-databases/polybase/polybase-configure-odbc-generic.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-odbc-generic.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@BeginTry -- Dave, thank you for your question.  I am looking into this issue.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, apologies for my delay here.  Please look into this issue.

**Comment by rothja** [comment]
@BeginTry Hello. Mike is out of the office. I'm going to try to get someone else to look at this question in his absence. Thank you!

**Comment by jrowlandjones** [comment]
@BeginTry Hello There and thank you for this feedback. This article is designed to show you how to create all the dependent objects but not create the external table itself. Once you have the dependent objects correctly set you can create external tables just by referencing these standard objects. The CREATE EXTERNAL TABLE article is referenced at the bottom of the article. I will revisit the article to see if the language can be improved to avoid any confusion here. Thanks again for the feedback.

**Comment by BeginTry** [comment]
Thanks for the follow up. 
For what it's worth, I was able to create an external table to an odbc-type external data source. There was some trial and error with the **CREATE EXTERNAL TABLE** statement...mostly with the **LOCATION** argument/parameter. I suppose it may vary a bit from one ODBC provider to another.

Cheers!

**Comment by WilliamAntonRohm** [comment]
@jrowlandjones -- thank you for your explanation.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
