### ISSUE TITLE
Missing docs for 'new' columns

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#5157]
The following columns are not documented.
I am running

Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64) 
	Feb 15 2020 01:47:30 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: )

Total_CPU_Delayed_MS
total_CPU_Active_MS
Total_CPU_Violation_delay_MS
Total_Cpu_violation_Sec,
total_Cpu_Usage_PreEmptive_MS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d21c5d2c-0853-2d30-27e8-bc7d3c328d1a
* Version Independent ID: 3817d2cd-157c-15d6-9b2e-9d91c077a68a
* Content: [sys.dm_resource_governor_resource_pools (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-resource-governor-resource-pools-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-resource-governor-resource-pools-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-resource-governor-resource-pools-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@brettshearer -- Brett, thank you for your feedback.

@CarlRabeler -- Carl, please look into this issue.

**Comment by CarlRabeler** [comment]
#reassign @pmasl Pedro, please review and assign appropriately

**Comment by pmasl** [comment]
Fixed. 
#please-close
