### ISSUE TITLE
Work with remote data sources

### ISSUE THREAD

**Issue by FoxyChmoxy** [MicrosoftDocs/sql-docs#5159]
# Issue Description
There is a document on how to connect to [linked servers](https://docs.microsoft.com/en-us/sql/relational-databases/linked-servers/linked-servers-database-engine?view=sql-server-ver15), but there is no information on how to interact with the remote server. Can I add a new doc with information about how `EXEC AT` can be used and what is a difference between `OPENQUERY` and `OPENROWSET` ?

**Comment by WilliamAntonRohm** [comment]
@FoxyChmoxy -- Almas, thank you for your question.

@stevestein -- Steve, please look into this issue.

**Comment by FoxyChmoxy** [comment]
Hi @stevestein 
I have successfully created a pull request #5289 , please let me know if something needs to be fixed.
I also have signed the Contribution License Agreement.

**Comment by stevestein** [comment]
@FoxyChmoxy - thanks for opening this issue, and submitting a PR. I'm going to close this issue and continue the conversation in the PR.

Thanks.
