### ISSUE TITLE
poor download experience

### ISSUE THREAD

**Issue by sharepointman** [MicrosoftDocs/sql-docs#5160]
[Enter feedback here]
I have a fast internet connection  but trying to download this is PITTA. Tried 4 times and it hangs part way thru each time. There is an  MS download tool that is much better than the one linked to please use that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@sharepointman -- thank you for your feedback.

Please clarify:  "There is an MS download tool that is much better than the one linked to please use that" -- which download tool are you referring to?

Meanwhile, you are welcome to add your concern here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

**Comment by sharepointman** [comment]
There is a download tool that does not lose downloaded content. Cannot remember what but you are given the option to download as this is or you can select a more resilient version. My issue was that the download paused part way thru and did not recover so I had to try several times and it is a big download so was eating up my bandwidth.

**Comment by WilliamAntonRohm** [comment]
@sharepointman -- were you able to find a suitable download tool?  My apologies for the delay in responding.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by shapeh** [comment]
@WilliamAntonRohm - what about implementing the same download experience as in Visual Studio?

**Comment by WilliamAntonRohm** [comment]
@shapeh -- Shapeh, thank you for your question, and my apologies for the delay in responding.  Please add your suggestion regarding the comparative download experiences here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
