### ISSUE TITLE
CHECKED OPTION

### ISSUE THREAD

**Issue by merarischroeder** [MicrosoftDocs/sql-docs#5161]
What does the following "NOTE" mean?

"Any updates performed directly to a view's underlying tables are not verified against the view, even if CHECK OPTION is specified."

This is in a note following a statement that states

"Forces all data modification statements executed against the view to follow the criteria set within select_statement. When a row is modified through a view, the WITH CHECK OPTION makes sure the data remains visible through the view after the modification is committed."

The "NOTE" seems to contradict the definition of CHECK OPTION. Apparently the "NOTE" is trying to say something important, but in its current form it's too vague.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4165179c-e336-919e-a590-3b892143f247
* Version Independent ID: 017d0a81-549f-8ac2-dd5d-40c9dc461cdf
* Content: [CREATE VIEW (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-view-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-view-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-view-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@merarischroeder -- thank you for your feedback.

@CarlRabeler -- please look into this issue.

**Comment by CarlRabeler** [comment]
@merarischroeder the WITH CHECK OPTION only applies to actions taken through the view. If someone with sufficient permissions makes changes directly to the underlying table and not through the view are not constrained in any way by the WITH CHECK OPTION.

**Comment by merarischroeder** [comment]
@CarlRabeler Thanks for the clarification, that makes more sense now.

I came to this article trying to find possible caveats about "WITH CHECK OPTION". So I was extra confused when I saw that note. 

Perhaps the following rewrite of the sentence might help others in the future:

"You need to use the VIEW for the defined criteria to be enforced; if you bypass the view and directly reference from the underlying Tables (or dependent Views) the criteria will not be enforced"

Thanks.

**Comment by CarlRabeler** [comment]
making an update to the sentence today.
