### ISSUE TITLE
Review SQL Server 2019 Release Notes

### ISSUE THREAD

**Issue by rotchfordf** [MicrosoftDocs/sql-docs#5163]
Great!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b419de6-b39e-a68f-7c68-d996e77e72ab
* Version Independent ID: 5304fec4-1727-47d2-73c5-152ca67c50d5
* Content: [SQL Server 2019 Release Notes - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-version-15-release-notes?view=sql-server-ver15)
* Content Source: [docs/sql-server/sql-server-version-15-release-notes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/sql-server-version-15-release-notes.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@rotchfordf -- Frank, thank you.
