### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by Mitch-Wheat** [MicrosoftDocs/sql-docs#5166]
Run this:

    declare @bg3 binary(4000) = 0x87362854873873648
    declare @bg4 binary(4000) = 0x87362854873873648

    select @bg3 ^ @bg4

Error message is:

Msg 402, Level 16, State 1, Line 12
The data types binary and binary are incompatible in the '^' operator.

                         ^               ^

binary is stated twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49a71499-f9ee-6347-78ff-19f202db6fa9
* Version Independent ID: 3319220a-7038-c011-d881-78886327cc26
* Content: [^ (Bitwise Exclusive OR) (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/bitwise-exclusive-or-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/language-elements/bitwise-exclusive-or-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/bitwise-exclusive-or-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@Mitch-Wheat -- Mitch, thank you for your feedback.  I believe that message is correct, as the interpreter is very literal.  For example, with binary & varchar arguments the error message is:

```
The data types binary and varchar are incompatible in the '^' operator.
```

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
