### ISSUE TITLE
Missing space for "Enginefrom"

### ISSUE THREAD

**Issue by NathanG** [MicrosoftDocs/sql-docs#5169]
Hello,

I hope you are doing well.

There is a line in your doc "Connect to the instance of the Database Enginefrom the Object Explorer pane."
I believe it should be "Connect to the instance of the Database Engine from the Object Explorer pane."

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63ddb5d-2b77-bdeb-e764-ad84d18fe76c
* Version Independent ID: 01786943-f591-d8f9-f1db-3867a787198c
* Content: [Monitor Data-tier Applications - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/monitor-data-tier-applications?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/data-tier-applications/monitor-data-tier-applications.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/monitor-data-tier-applications.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@NathanG -- thank you bringing this to our attention.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
