### ISSUE TITLE
LInk for documentation goes to deprecated pages

### ISSUE THREAD

**Issue by RachelAmbler** [MicrosoftDocs/sql-docs#5170]
The following section:

> See the previously published documentation for Service Broker concepts and for development and management tasks. This documentation is not reproduced in the SQL Server 2019 (15.x) documentation due to the small number of changes in Service Broker in SQL Server 2019 (15.x).

Links to the Microsoft docs site here: https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/bb522893(v=sql.105)?redirectedfrom=MSDN

Each page there on in is labelled: 

> This content has been retired and may not be updated in the future. The product, service, or technology mentioned in this content is no longer supported.

Understanding that the documentation has changed little (hence the back link), should it be labeled though stating that it's no longer supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f089d928-4091-1873-0d28-c1307187aff3
* Version Independent ID: af2356c1-5d4d-6d14-e9d4-9cfdddc37abd
* Content: [SQL Server Service Broker - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-service-broker?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/sql-server-service-broker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/sql-server-service-broker.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@RachelAmbler -- Rachel, thank you for your feedback.  I agree the destination pages' "no longer supported" seems to contradict the starting page's description; in this case the intention is clear.  I will bring this up to our docs team.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
