### ISSUE TITLE
Step Two is incorrect for ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by BrendanNurmi** [MicrosoftDocs/sql-docs#5172]
The page current does not work for ubuntu 20.04 LTS.

Step 2 - Register the Microsoft SQL Server Ubuntu repository for SQL Server 2019:
Can we add a note to advise the user of the correct URL for the correct version of Ubuntu they are running? 

e.g.
Ubuntu 18.04
` 
sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/18.04/mssql-server-2019.list)"
`
Ubuntu 20.04
` 
sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list)"
`
and so on

Or just possible refer them to https://packages.microsoft.com/config/ubuntu/ to see what versions are avalible :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@BrendanNurmi -- Brendan, thank you for your feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @BrendanNurmi! Thanks for the feedback. Ubuntu 20.04 is not supported with SQL Server 2019 at the moment. https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019?view=sql-server-ver15

I will add a note to reference the release notes for supported versions. Thanks!
