### ISSUE TITLE
Picture are not clear

### ISSUE THREAD

**Issue by amalsharief** [MicrosoftDocs/sql-docs#5176]
The  illustrations show a transaction log before and after truncation are not clear, can not be read.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a878f81-f084-d4a2-8098-2b63558b7369
* Version Independent ID: 9e64bd2c-670e-284b-f34e-a409650cec88
* Content: [Transaction Log Architecture and Management Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-log-architecture-and-management-guide?view=sql-server-ver15)
* Content Source: [docs/relational-databases/sql-server-transaction-log-architecture-and-management-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/sql-server-transaction-log-architecture-and-management-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@amalsharief -- thank you for your feedback.  The illustrations are clearly legible on my screen.  What is your viewing configuration?

**Comment by ite-klass** [comment]
I checked as well and this is a Theme issue. On the dark and high contrast themes they are not readable.

![image](https://user-images.githubusercontent.com/8045680/87684666-cf8cab80-c782-11ea-82a9-94ba94ad1be1.png)

![image](https://user-images.githubusercontent.com/8045680/87684677-d3203280-c782-11ea-98a7-2052de9807e1.png)

**Comment by rothja** [comment]
@WilliamAntonRohm You can set the dark theme at the bottom of the page:

![image](https://user-images.githubusercontent.com/1580454/87690302-48760e00-c757-11ea-8830-1c8e90bf1c24.png)

Transparent images are normally bad in the dark theme and must be changed to have an all-white background.

**Comment by ite-klass** [comment]
At least the text should be white rather than transparent. Then it would work fine.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
