### ISSUE TITLE
Azure Data Studio fails PowerShell Extension Installation from GitHub

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#5177]
The reference on this page [(https://docs.microsoft.com/en-us/sql/azure-data-studio/powershell-extension?view=sql-server-ver15)]  lists to go to GitHub if unable to access the Azure Data Studio [ADS} extensions.  That target indicates the PowerShell extension, but it requires Visual Studio Code [VSCode].  Why should I have to install VSCode when I am looking to add an extension to ADS?  There was no indication that VSCode was a prerequisite for ADS.  The page states "Provides rich PowerShell language support for _Azure Data Studio_", not it provides PS support for **VSCode**.

I am trying to install ADS on a server that has no internet connection.  If ADS requires a _**separate**_ VSCode installation to gain offline access to ADS extensions, that should be clearly stated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12bf49db-fd24-7f4d-6792-6825f4e08faa
* Version Independent ID: 5f524d58-816a-812f-e43f-1916f1b4f199
* Content: [Add extensions - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/extensions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/extensions.md)
* Product: **azure-data-studio**
* Technology: ****
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@LindaLF -- thank you for your feedback.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
Hi, @MicrosoftDocs/sql-tools-reference-content-admin 
apologize for the delayed response, but I am not finding the snippet you posted.

You do not need VS Code to install an Azure Data Studio extension either directly from Azure Data Studio library or via a VSIX install.

So can I ask to please clarify?

thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit Azure Data Studio repo(https://github.com/microsoft/azuredatastudio)
