### ISSUE TITLE
Errors in documention refer to figures and elements not present.

### ISSUE THREAD

**Issue by careygister** [MicrosoftDocs/sql-docs#5179]
[Enter feedback here]

The documentation refers to instantiable types **CircularString**, **CompoundCurve** and **PloygonCurve**. Yet, there are only seven (7) instantiable types enumerated in the diagram.

The documentation refers to a Figure A, B, C and D under the **Circular Arc Segments** heading. There are no such figures on the page!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2797e2b3-62ca-d4f9-c36f-31d77358deda
* Version Independent ID: 0e1e4a3a-2bcb-97e1-94ac-98be1bfbda97
* Content: [Spatial Data Types Overview - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-data-types-overview?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/spatial/spatial-data-types-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/spatial/spatial-data-types-overview.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@careygister -- Carey, thank you for your feedback.

@MladjoA -- Mladen, please look into this issue.

**Comment by MladjoA** [comment]
@careygister , thanks for your feedback!
Diagram is now updated, and figure reference fixed.

**Comment by MladjoA** [comment]
#please-close
