### ISSUE TITLE
duplicate code snip and note

### ISSUE THREAD

**Issue by denneyliptak** [MicrosoftDocs/sql-docs#5181]
[Enter feedback here]
Hi there. Was reading this page trying to learn more about the namespaced-admin role that is created. Noticed in the lower section on metrics that there is a duplicate code block and 'note' section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34c5ac4a-6a72-af9e-b1e9-ded4fcc3f061
* Version Independent ID: c4baa78e-2ae1-2ce8-d948-e5a3142ef738
* Content: [Kubernetes RBAC - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/kubernetes-rbac?view=sql-server-ver15#cluster-role-required-for-pods-and-nodes-metrics-collection)
* Content Source: [docs/big-data-cluster/kubernetes-rbac.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/kubernetes-rbac.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @mihaelablendea
* Microsoft Alias: **mihaelab**

**Comment by WilliamAntonRohm** [comment]
@denneyliptak -- thank you for bringing this to our attention.  I am looking into this article.
