### ISSUE TITLE
Permission to use the BULK load statement is required

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/sql-docs#5185]
Users may need their admin to enable the 'bulkadmin' role.

`ALTER SERVER ROLE [bulkadmin] ADD MEMBER [user]`

For completeness, this should be mentioned in the documentation.

HD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96b577d2-6af6-c87e-336a-a6fb9b776697
* Version Independent ID: fcad9f44-92fa-dbed-81df-2a70368abe24
* Content: [Import JSON documents - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/import-json-documents-into-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/json/import-json-documents-into-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/import-json-documents-into-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@HairyDrumroll -- thank you for your feedback.

@jovanpop-msft -- please look into this issue.

**Comment by HarryDriscollTWE** [comment]
I think you also need read/write access to the file. Read-only doesn't seem to be sufficient.

**Comment by rwestMSFT** [comment]
@HarryDriscollTWE Thanks for your feedback. We have an article refresh in review. When that is merged, this issue will automatically close, and you will see the published article in the next business day.
