### ISSUE TITLE
Incorrect syntax

### ISSUE THREAD

**Issue by Zjokke** [MicrosoftDocs/sql-docs#5192]
After a lot of investigation, I found out that the data source references in the mentioned syntax are incorrect:

- FORMATFILE_DATASOURCE should be FORMATFILE_DATA_SOURCE
- ERRORFILE_DATASOURCE should be ERRORFILE_DATA_SOURCE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbec06eb-2341-9186-a24f-adc129642169
* Version Independent ID: d32aa975-1187-ede1-e775-a590c0dba458
* Content: [OPENROWSET (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/openrowset-transact-sql?view=sql-server-ver15&source=docs)
* Content Source: [docs/t-sql/functions/openrowset-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/openrowset-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@Zjokke -- Jo, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@julieMSFT -- Julie, please review [private PR 16053](https://github.com/MicrosoftDocs/sql-docs-pr/pull/16053).
