### ISSUE TITLE
Basic PIVOT Example doesn't work

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/sql-docs#5194]
```sql
-- Pivot table with one row and five columns  
SELECT 'AverageCost' AS Cost_Sorted_By_Production_Days,   
[0], [1], [2], [3], [4]  
FROM  
(SELECT DaysToManufacture, StandardCost   
    FROM Production.Product) AS SourceTable  
PIVOT  
(  
AVG(StandardCost)  
FOR DaysToManufacture IN ([0], [1], [2], [3], [4])  
) AS PivotTable;  
```

Except, there is no column named `AverageCost`. Presumably `AVG(StandardCost)` is supposed to be `AVG(StandardCost) as AverageCost` as per the previous SQL snippet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45eba8b0-0c31-d65b-f1ca-0ed260eb2f14
* Version Independent ID: fe2a79c1-6512-36f6-3118-cda7d18531de
* Content: [Using PIVOT and UNPIVOT - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/from-using-pivot-and-unpivot?view=sql-server-ver15)
* Content Source: [docs/t-sql/queries/from-using-pivot-and-unpivot.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/from-using-pivot-and-unpivot.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@IanKemp -- Ian, thank you for catching this.  I am looking into the article.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @IanKemp - I'm sorry for the delay. This fell through the cracks. I just attempted the query on my machine, and it does work, and provides the results shown on the doc. Please feel free to let me know if I'm missing something. I will close this now, but you can @ me for any issues.

![image](https://user-images.githubusercontent.com/40007119/101546043-0abf8f00-395d-11eb-934b-fd4c5278f719.png)
