### ISSUE TITLE
SUSE Linux Enterprise Server 15

### ISSUE THREAD

**Issue by fuentestechsoft** [MicrosoftDocs/sql-docs#5195]
There is support for SQL Server 2019 in SUSE Linux Enterprise Server 15?
If not, when is expected to be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600e45dc-85ad-e487-9375-949af2530a83
* Version Independent ID: a0e1527b-fd9a-b7a0-0bef-d14339cf4e1f
* Content: [SUSE: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-suse?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-suse.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-suse.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
SLES v15 is not supported for SQL Server 2019: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019?view=sql-server-ver15

Unfortunately, we cannot discuss future dates on supported platforms. We apologize for the inconvenience.
