### ISSUE TITLE
typo in "QUERY_CAPTURE_MODE to AUTO and sets other recommended options in SQL Server 2017 (14.x) " example

### ISSUE THREAD

**Issue by campbellwarren** [MicrosoftDocs/sql-docs#5200]
There is a typo here.  The last comma after   WAIT_STATS_CAPTURE_MODE = ON, should not be there.

The following example sets QUERY_CAPTURE_MODE to AUTO and sets other recommended options in SQL Server 2017 (14.x) to include wait statistics:

SQL

Copy
ALTER DATABASE [QueryStoreDB]
SET QUERY_STORE = ON
    (
      OPERATION_MODE = READ_WRITE,
      CLEANUP_POLICY = ( STALE_QUERY_THRESHOLD_DAYS = 90 ),
      DATA_FLUSH_INTERVAL_SECONDS = 900,
      QUERY_CAPTURE_MODE = AUTO,
      MAX_STORAGE_SIZE_MB = 1000,
      INTERVAL_LENGTH_MINUTES = 60,
      SIZE_BASED_CLEANUP_MODE = AUTO,
      MAX_PLANS_PER_QUERY = 200,
      WAIT_STATS_CAPTURE_MODE = ON,
    );

**Comment by WilliamAntonRohm** [comment]
@campbellwarren -- thank you for catching this. I am looking into the article.

**Comment by campbellwarren** [comment]
Happy to help.  The robust documentation for Query Store is appreciated!

**Comment by WilliamAntonRohm** [comment]
@campbellwarren -- I overlooked one minor item:  which docs.microsoft.com article are you reading?

**Comment by campbellwarren** [comment]
https://docs.microsoft.com/en-us/sql/relational-databases/performance/best-practice-with-the-query-store?view=sql-server-ver15&viewFallbackFrom=sql-server-ver14

Best practices for query store

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
