### ISSUE TITLE
LPIM and edition support

### ISSUE THREAD

**Issue by vasek-cz** [MicrosoftDocs/sql-docs#5201]
This article doesn't mention any requirements for engine editions. However, other Microsoft [resource](https://support.microsoft.com/en-us/help/918483/how-to-reduce-paging-of-buffer-pool-memory-in-sql-server) state it's supported only for Standard and Enterprise editions:

> Note Since SQL Server 2008 SP1 Cumulative Update 2 both SQL Server Standard and Enterprise editions can use the Lock pages in memory user right. 

Can you please clarify the minimal edition needed to support LPIM in this article?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46872074-d754-a4bc-fd01-3cc0c90e566e
* Version Independent ID: c40f0947-7b53-1197-10f6-722ee283684e
* Content: [Enable the Lock Pages in Memory Option (Windows) - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-the-lock-pages-in-memory-option-windows?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/enable-the-lock-pages-in-memory-option-windows.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/enable-the-lock-pages-in-memory-option-windows.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@vasek-cz -- Vasek, thank you for your feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
Hi, @vasek-cz,

 Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
It's the Standard edition.

hope this helps.

thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
