### ISSUE TITLE
Python2 is deprecated

### ISSUE THREAD

**Issue by Susanthab** [MicrosoftDocs/sql-docs#5203]
SQL Server on Linux has a prerequisite of python2. Since Python2 is deprecated, we are unable to move ahead with Linux because company does not allow us to install deprecated software. When MS is planning to change it to python3?

**Comment by WilliamAntonRohm** [comment]
@Susanthab -- Susantha, thank you for your question.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @Susanthab! Thanks for submitting this question. I've been checking with our Product Team, and it is in their road-map, but we don't have any timelines to share. I apologize for the inconvenience! Please feel free to submit a product feedback, but I have an internal work item to track this. When it is supported, we will document the changes. Thanks again!
