### ISSUE TITLE
Unique Identity in Synapse

### ISSUE THREAD

**Issue by Robert-Kostecki** [MicrosoftDocs/sql-docs#5204]
According to this documentation:
“The **identity** property on a column **does not guarantee** the following:
•	**Uniqueness of the value** - **Uniqueness must be enforced by using a PRIMARY KEY or UNIQUE constraint or UNIQUE index**.”

As this “Applies to: Azure Synapse Analytics (SQL DW)” can we please clarify how a primary or unique key can be enforced in Synapse? Otherwise how can we enforce Identity uniqueness in Synapse? 

This is linked to, to https://github.com/MicrosoftDocs/azure-docs/issues/59238

Linked articles:
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15
and
https://docs.microsoft.com/en-us/azure/synapse-analytics/sql-data-warehouse/sql-data-warehouse-tables-identity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33014f93-e2e9-f0e7-804b-e50493a32627
* Version Independent ID: 38498f73-63c2-4557-bf4b-c20923b45656
* Content: [IDENTITY (Property) (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-table-transact-sql-identity-property.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-transact-sql-identity-property.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hey @julieMSFT - Related to https://github.com/MicrosoftDocs/sql-docs/issues/4935

**Comment by julieMSFT** [comment]
@Robert-Kostecki Hi Robert, I have  updated [IDENTITY (Property) (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15) to include a note that PRIMARY KEY or UNIQUE constraint or UNIQUE index do not apply to Azure Synapse and directed you to Using IDENTITY to create surrogate keys - Azure Synapse Analytics(https://docs.microsoft.com/en-us/azure/synapse-analytics/sql-data-warehouse/sql-data-warehouse-tables-identity).  I have updated this article to state that is SET IDENTITY INSERT is off and you do not reseed the identity value that in most cases the value will be unique and can be used for a surrogate key. You should see the update in the doc in the next day or so. Thank you for bringing this to our attention and helping to improve Microsoft Docs! I will proceed with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#https://github.com/MicrosoftDocs/sql-docs-pr/pull/16097
#https://github.com/MicrosoftDocs/azure-docs-pr/pull/123033

**Comment by julieMSFT** [comment]
#please-close

**Comment by Robert-Kostecki** [comment]
Hi Julie 

"I have updated this article to state that is SET IDENTITY INSERT is off and you do not reseed the identity value that **in most cases** the value will be unique and can be used for a surrogate key."

Could you please elaborate on "in most cases" bit? What would be case(s) where the IDENTITY generated value is not unique (given the parameters you stated above i.e. identity on and no reseeds)? 

I don't want to be a pain but these features need to be rock-solid to make sure the multimillion project investments won't start failing weeks or months after production deployment due to the keys collisions. Therefore is anything we need to know before using the feature can we please have this documented?
