### ISSUE TITLE
Needs better examples

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/sql-docs#5210]
Pivoting is a powerful feature but the examples on this topic fail to demonstrate this power. Missing examples of its most powerful features:

* pivoting on values that you don't actually want to aggregate
* pivoting on a variable number of rows, i.e. when the pivoted column set isn't known beforehand

An example of both of the above can be seen at https://data.stackexchange.com/stackoverflow/query/1263693/moderator-election-badges - I needed to pivot on a variable number of rows containing `bit` values, which necessitated actually typing the values as `tinyint` so I could perform a non-aggregation of `min` on them, and using dynamic SQL to handle the columns.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45eba8b0-0c31-d65b-f1ca-0ed260eb2f14
* Version Independent ID: fe2a79c1-6512-36f6-3118-cda7d18531de
* Content: [Using PIVOT and UNPIVOT - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/from-using-pivot-and-unpivot?view=sql-server-ver15)
* Content Source: [docs/t-sql/queries/from-using-pivot-and-unpivot.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/from-using-pivot-and-unpivot.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@IanKemp -- Ian, thank you for your feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
@IanKemp - Hi Ian, thanks for the suggestion! We really appreciate your recommendations, and I have created an internal work item to track and possibly work on this issue. Unfortunately, we cannot provide a timeline on when this work will be done. I will go ahead and close this issue. Thanks again!

Work Item # 1780016
