### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mrlife** [MicrosoftDocs/sql-docs#5213]
Is there a new link for this?

Text: How to use Kerberos authentication in SQL Server
Link: https://support.microsoft.com/kb/319723

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33dd6653-34cf-9637-4b21-da7354446746
* Version Independent ID: 9a9661c4-782c-8560-4f6e-99391f7b7c4d
* Content: [Using Kerberos integrated authentication to connect to SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@mrlife -- thank you for your question.  Please let me know if this link is helpful:
- [Using Kerberos integrated authentication to connect to SQL Server](https://docs.microsoft.com/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver15)

@David-Engel -- please look into this issue.

**Comment by David-Engel** [comment]
@mrlife I think this might be a good replacement for the previous link: [Register a Service Principal Name for Kerberos Connections](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections?view=sql-server-ver15)

**Comment by mrlife** [comment]
Thank you both. This is the specific information I was looking for - using `setspn` - so @David-Engel's link sounds good.

https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections?view=sql-server-ver15#Manual

**Comment by David-Engel** [comment]
Great! I updated the article. Changes should be reflected some time today.

#please-close
