### ISSUE TITLE
Link to command line utilities v15?

### ISSUE THREAD

**Issue by Avyncentia** [MicrosoftDocs/sql-docs#5215]
Shouldn't there be a link to the install page for command line utilities v15 in the "command-line tools" section? Right now it only discusses v11 and v13, which seems confusing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4123780b-93ac-e188-87a8-ffd4d5d37aa3
* Version Independent ID: fec60355-b6d1-1c41-bcd5-d202e0d09d90
* Content: [System Requirements, Installation, and Driver Files - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/windows/system-requirements-installation-and-driver-files?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/windows/system-requirements-installation-and-driver-files.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/windows/system-requirements-installation-and-driver-files.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@Avyncentia Thanks for the heads up. We also noticed this recently and it will be updated within the next couple of weeks as part of another set of changes in progress.

The update will link to https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15.

Thanks,
David

#please-close
