### ISSUE TITLE
Azure Data Studio prerequisite port(s) [?]

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#5217]
There is no mention on this page regarding that port 1433 needs to be open when accessing a SQL environment.  In fact, I can't find anything in the documentation for Azure Data Studio that defines what port needs to be opened with **_ANY_** of the kernels that are being used in an Azure Data Studio Notebook.

Please add this information.

Regards,
Linda A. Lorentz Fletcher
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df0319c-ec31-e09f-6f44-d71ed20544c3
* Version Independent ID: c52fabfa-5a3d-ea25-cbbf-8a988a8bc867
* Content: [Quickstart: Connect and query SQL Server - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/quickstart-sql-server?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/quickstart-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/quickstart-sql-server.md)
* Product: **azure-data-studio**
* Technology: ****
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
@LindaLF -- Linda, thank you for your detailed feedback.

@yualan -- Alan, please look into this issue.

**Comment by markingmyname** [comment]
Hi, @LindaLF 

First, I want to apologize for the delayed response.

However, we do acknowledge that the connection and query docs might be lagging in certain areas.

As such, there is an effort to revamp the connect and query docs, not just from azure-data-studio, but for ssms too.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit Azure Data Studio repo(https://github.com/microsoft/azuredatastudio)
