### ISSUE TITLE
I think the paragraph explaining the example is incorrect??

### ISSUE THREAD

**Issue by cosmoKenney** [MicrosoftDocs/sql-docs#5218]
[Enter feedback here]

In this paragraph: https://docs.microsoft.com/en-us/sql/relational-databases/import-export/use-native-format-to-import-or-export-data-sql-server?view=sql-server-ver15#sample-non-xml-format-file

In the text it say the "c" qualifier is used, but it is using the "-n" option in the actual example. Did I miss something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 328e38b9-9bc3-b8d0-6c35-523adc294fa3
* Version Independent ID: f8a555b0-d2ae-c8bc-842e-0b160afb4490
* Content: [Use native format to import & export data - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/use-native-format-to-import-or-export-data-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/import-export/use-native-format-to-import-or-export-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/use-native-format-to-import-or-export-data-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@cosmoKenney -- Ken, thank you for your feedback.

@MashaMSFT -- Masha, please look into this conundrum.

**Comment by MashaMSFT** [comment]
Hi @cosmoKenney , this change has been processed and is now live.

Thanks for improving our documentation! Hope you have a wonderful rest of your day :) 
Masha from the SQL Docs team
