### ISSUE TITLE
Step 10: Create a database encryption key by using the ASYMMETRIC KEY (EKMSampleASYKey).

### ISSUE THREAD

**Issue by jthompson-ghd** [MicrosoftDocs/sql-docs#5221]
[Enter feedback here]

Missing 3rd line in SQL command

--Create an ENCRYPTION KEY using the ASYMMETRIC KEY (EKMSampleASYKey)
CREATE DATABASE ENCRYPTION KEY  
WITH ALGORITHM = AES_256  
ENCRYPTION BY SERVER ASYMMETRIC KEY EKMSampleASYKey; 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4997f245-c966-51a3-34c7-705c3cfbd4b0
* Version Independent ID: 129fbe40-3b02-f2c1-ef13-b42d86ffdb77
* Content: [Set up Transparent Data Encryption (TDE) Extensible Key Management with Azure Key Vault - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-ver15&tabs=portal#step-1-set-up-an-azure-ad-service-principal)
* Content Source: [docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@jthompson-ghd -- Joe, thank you for finding this.  I am looking into the article.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please review [private PR 16196](https://github.com/MicrosoftDocs/sql-docs-pr/pull/16196).

**Comment by VanMSFT** [comment]
@Rupp29 - Hey Adrian, can you please help review this, and also https://github.com/MicrosoftDocs/sql-docs-pr/pull/16196 for the additions? Thanks!
