### ISSUE TITLE
A small correction to the c# demo code in the section called Use FOR JSON output in a C# client app

### ISSUE THREAD

**Issue by Peled-Zohar** [MicrosoftDocs/sql-docs#5224]
`SqlConnection` , `SqlCommand` and SqlDataReader all implement the `IDisposable` interface - so a better code example would be this:
```csharp
var queryWithForJson = "SELECT ... FOR JSON";
var jsonResult = new StringBuilder();
using(var conn = new SqlConnection("<connection string>"))
{
    using(var cmd = new SqlCommand(queryWithForJson, conn))
    {
        conn.Open();
        using(var reader = cmd.ExecuteReader())
        {
            if (!reader.HasRows)
            {
                jsonResult.Append("[]");
            }
            else
            {
                while (reader.Read())
                {
                    jsonResult.Append(reader.GetValue(0).ToString());
                }
            }
        }
    }
}
```

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6780fe4-5238-8607-8343-b8affadff8e2
* Version Independent ID: aa89f52b-328d-38b9-7b23-7f7de8ac8b25
* Content: [Use FOR JSON output in SQL Server and in client apps - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/use-for-json-output-in-sql-server-and-in-client-apps-sql-server?view=sql-server-ver15#use-for-json-output-in-a-c-client-app)
* Content Source: [docs/relational-databases/json/use-for-json-output-in-sql-server-and-in-client-apps-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/use-for-json-output-in-sql-server-and-in-client-apps-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@Peled-Zohar -- Zohar, thank you for your suggestion.

@jovanpop-msft -- Jovan, please look into this issue.

**Comment by rothja** [comment]
@jovanpop-msft Jovan, could you compare the code example in the [article](https://docs.microsoft.com/en-us/sql/relational-databases/json/use-for-json-output-in-sql-server-and-in-client-apps-sql-server?view=sql-server-ver15#use-for-json-output-in-a-c-client-app) here:

```csharp
var queryWithForJson = "SELECT ... FOR JSON";
var conn = new SqlConnection("<connection string>");
var cmd = new SqlCommand(queryWithForJson, conn);
conn.Open();
var jsonResult = new StringBuilder();
var reader = cmd.ExecuteReader();
if (!reader.HasRows)
{
    jsonResult.Append("[]");
}
else
{
    while (reader.Read())
    {
        jsonResult.Append(reader.GetValue(0).ToString());
    }
}
```

with this improvement that @Peled-Zohar is suggesting in this git issue:

```csharp
var queryWithForJson = "SELECT ... FOR JSON";
var jsonResult = new StringBuilder();
using(var conn = new SqlConnection("<connection string>"))
{
    using(var cmd = new SqlCommand(queryWithForJson, conn))
    {
        conn.Open();
        using(var reader = cmd.ExecuteReader())
        {
            if (!reader.HasRows)
            {
                jsonResult.Append("[]");
            }
            else
            {
                while (reader.Read())
                {
                    jsonResult.Append(reader.GetValue(0).ToString());
                }
            }
        }
    }
}
```

@jovanpop-msft Do you agree with this improvement to the code sample, or do you have comments about this suggestion? Thank you!

**Comment by jovanpop-msft** [comment]
@rothja yes this change is fine. I already create PR for this: https://github.com/MicrosoftDocs/sql-docs-pr/pull/18234

**Comment by rothja** [comment]
@jovanpop-msft Thank you! And thanks @Peled-Zohar for the suggestion. I will close out this issue now.
