### ISSUE TITLE
Page seems to be outdated

### ISSUE THREAD

**Issue by dedvds** [MicrosoftDocs/sql-docs#5226]
This page seems to be a little bit outdated. For example, Joins, aggregates, and sorts are currently working for ADLS g2/blob to Azure Synapse Analytics, but this page says it doesnt. Could it be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 066808bd-cf93-7fa7-d84c-fb2da46558ab
* Version Independent ID: 415a5039-44e1-0654-10e2-ca4916732df3
* Content: [PolyBase features and limitations - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-versioned-feature-summary?view=sql-server-ver15)
* Content Source: [docs/relational-databases/polybase/polybase-versioned-feature-summary.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-versioned-feature-summary.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@dedvds -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
@dedvds -- David, thanks for your patience. I'm reviewing an update per your recommendation.

**Comment by dedvds** [comment]
@MikeRayMSFT , @WilliamAntonRohm, many thanks for taking the time to update this page. We'll see the page updated in the future.
