### ISSUE TITLE
Edge Hub external data source cannot be created using syntax in the doc

### ISSUE THREAD

**Issue by helloyesthisisdave** [MicrosoftDocs/sql-docs#5230]
Running the following as per the docs against an SQL Edge database:

```
create external data source EdgeHubSource
with
(
  location = 'edgehub://'
);
```
returns the error:

>Msg 46530, Level 16, State 11, Line 1
>External data sources are not supported with type GENERIC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e450abc6-2dbd-8f6c-423c-52aca37a2b06
* Version Independent ID: 4aff678a-6db1-a438-9aca-bb4b4d49bc27
* Content: [CREATE EXTERNAL DATA SOURCE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-external-data-source-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-data-source-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
#reassign: @stevestein please review

**Comment by helloyesthisisdave** [comment]
Nevermind, thought I had set trace flag 11515 but apparently hadn't
