### ISSUE TITLE
Customer cannot create login or user using graphic user interface (dialog box) for Azure SQL Database

### ISSUE THREAD

**Issue by hyparki** [MicrosoftDocs/sql-docs#5232]
Customer cannot create login or user using graphic user interface (dialog box) for Azure SQL Database.
But there is no guidance for the behavior.
If we don't have a plan to enhance the SSMS feature to create login using GUI for Azure SQL DB, we need to guide about it from this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e102e98e-7c04-4898-f351-f78ae895772e
* Version Independent ID: 8a1d99f2-9209-3e34-843c-a17b5a60aa75
* Content: [Create a Login - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/create-a-login?view=azuresqldb-current)
* Content Source: [docs/relational-databases/security/authentication-access/create-a-login.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/create-a-login.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @hyparki! Thanks for submitting this issue. You will find the more in-depth article for creating a login here: https://docs.microsoft.com/sql/t-sql/statements/create-login-transact-sql?view=azuresqldb-current. This will give you the specific command for Azure SQL Database. This page is already linked in the article mentioned.

**Comment by hyparki** [comment]
Hi @VanMSFT
Yes, we already have guidance for creating a login as you said.
However, there is no guide that the GUI is not supported when creating a login to Azure SQL DB.
In other words, there is no guid that only T-SQL can be used for it.

Regarding what I said, you can check this Azure blog article. 
But It is too old. It is talking about only SSMS 2008 R2.
https://azure.microsoft.com/en-us/blog/adding-users-to-your-sql-azure-database/

**Comment by VanMSFT** [comment]
Hi @hyparki - Unfortunately, we do not document functionality that doesn't exist. There are unlimited scenarios that don't exist, and we cannot document those. We will do our best to document supported scenarios, but cannot give guidance on any future functionality. We hope for your understanding. Thanks.

**Comment by hyparki** [comment]
@VanMSFT 
Thank you for your answer. I understood what you said. :)
