### ISSUE TITLE
Pricing is not clear on official website 

### ISSUE THREAD

**Issue by jingli0118** [MicrosoftDocs/sql-docs#5234]
I tried to follow the pricing part on official website for sql big data cluster.

But it is not really clear for me. https://www.microsoft.com/en-us/sql-server/sql-server-2019-pricing

Is it charging based on the number of master instance and node? (is it charging based on total number of nodes in the VMSS or only the nodes have sql server engine?)

And how many pod will be spined up when the sql big data part is added?

Can anyone help me for this question? Thank you very much!

![image](https://user-images.githubusercontent.com/52419120/88286659-60b6d180-ccf1-11ea-856b-c479ba081c61.png)

**Comment by WilliamAntonRohm** [comment]
@jingli0118 -- thank you for your requests for clarifications.  The pricing values themselves are determined by a different group.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
@jingli0118 - thanks for submitting this issue. We're working to clarify the information.
Will update shortly. 
Mike

**Comment by MikeRayMSFT** [comment]
@jingli0118 - web page where you raised the issue provides a summary. The link [Read the SQL Server 2019 licensing guide ](https://download.microsoft.com/download/e/2/9/e29a9331-965d-4faa-bd2e-7c1db7cd8348/SQL_Server_2019_Licensing_guide.pdf) provides the current licensing guide with all details. 

We also posted [a video](https://channel9.msdn.com/Shows/Data-Exposed/SQL-Server-Licensing-Big-Data-Clusters--Data-Exposed) that explains licensing. 

Thanks so much,
Mike
