### ISSUE TITLE
MS Support Case 117020315270200

### ISSUE THREAD

**Issue by martinbherbener** [MicrosoftDocs/sql-docs#5236]
Hi,

It would be helpful to include the information I obtained through  MS Support Case 117020315270200

There are two issues uncovered. First SQL 2016 SSM has a product issue that prevents to use GUI to configure replication to non-sql server subscribers. Secondly SQL 2016 doesn’t have proper meta data mapped to oracle 12 C.
Resolution
1.	Use TSQL Script to configure Oracle subscription 
2.	For 12c, extra steps are needed. Below are the steps

Note that these steps assume that you create a table on Oracle yourself without applying snapshot.

1. connect to SQL Server using dedicated admin connection (DAC)
use msdb
go
exec sys.sp_MSrepl_ORAdatatypes 'Oracle', '12'
go
exec sys.sp_MSrepl_MSSQL_ORA_datatypemappings @source_dbms = N'MSSQLSERVER', @destination_dbms = N'ORACLE', @destination_version = '12'

2. on oracle server
a. drop table MSREPL7;
b. create your own table (make sure exact name and schema)

3. create a simple transaction replication publication
4. change publication properties ("subscription options") "Allow no-SQL Server subscribors" to be true
4. use the following script to create subscription and agent job. You need to change oracle instance name, password and publication name

use [dbpub]

exec sp_addsubscription @publication = N'pub_t2', @subscriber = N'ORCLJACKLI', @destination_db = N'(default destination)', @subscription_type = N'Push', @sync_type = N'replication support only', @article = N'all', @update_mode = N'read only', @subscriber_type = 3
exec sp_addpushsubscription_agent @publication = N'pub_t2', @subscriber = N'ORCLJACKLI', @subscriber_db = N'(default destination)', @job_login = null, @job_password = null, @subscriber_security_mode = 0, @subscriber_login = N'SCOTT', @subscriber_password = null, @subscriber_provider = N'OraOLEDB.Oracle', @subscriber_datasrc = N'orcljackli', @subscriber_provider_string = N'orcljackli', @frequency_type = 64, @frequency_interval = 1, @frequency_relative_interval = 1, @frequency_recurrence_factor = 0, @frequency_subday = 4, @frequency_subday_interval = 5, @active_start_time_of_day = 0, @active_end_time_of_day = 235959, @active_start_date = 0, @active_end_date = 0, @dts_package_location = N'Distributor'

5. add some rows in the published table
6. verify in oracle after a few minutes of wait

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0918cd8a-85fe-5106-6b7e-27fbe6c4ee00
* Version Independent ID: c7d665a0-f57f-518c-40ba-e70b5f81933c
* Content: [Non-SQL Server Subscribers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/non-sql/non-sql-server-subscribers?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/relational-databases/replication/non-sql/non-sql-server-subscribers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/non-sql/non-sql-server-subscribers.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@martinbherbener -- thank for your thorough feedback.  

@MashaMSFT -- please look into this issue.

**Comment by briancarrig** [comment]
Hi martinbherbener, 

There does not appear to be a case matching the number mentioned. Nor can I find an associated case with your name or email. The number is also logically inconsistent with how we generate case numbers.

It could be a typo you accidentally copied into this PR #5236 and the duplicate #5235. The closest case I can find with similar steps, is over five years old.

We strongly recommend using CDC, SSIS and/or ADF to meet your needs as heterogeneous subscribers are deprecated.

_Heterogeneous replication to non-SQL Server subscribers is deprecated. Oracle Publishing is deprecated. To move data, create solutions using change data capture and SSIS._

https://docs.microsoft.com/en-us/sql/relational-databases/replication/non-sql/oracle-subscribers?view=sql-server-2016

**Comment by martinbherbener** [comment]
Hello briancarrig,

I've attached a copy of the email thread with the PSS Senior Escalation Engineer in case it helps you track down further info.

If y'all decide this is not worth adding to the article, I understand.

thanks

Martin
[RE_ [REG_117020315270200] New Time Proposed_  _Invalid Operation_ when adding Oracle subscriber  Initial Response.pdf](https://github.com/MicrosoftDocs/sql-docs/files/5208905/RE_.REG_117020315270200.New.Time.Proposed_._Invalid.Operation_.when.adding.Oracle.subscriber.Initial.Response.pdf)

**Comment by briancarrig** [comment]
@MashaMSFT if there are no objections I am going to close this. With the feature being deprecated there is little we can do to fix (e.g. even a wrapper system procedure with the correct steps). I am aware that this was not the ask but I do not feel comfortable putting these steps in official documentation (especially for a deprecated feature). 

We also would backport a fix to SQL 2019 not SQL 2016 which may be of little use to the poster if they cannot upgrade for some reason. I recommend upgrading to SQL 2019 to avail of a number of CDC fixes and there is also the option of connecting to Oracle using Polybase(v2).

**Comment by briancarrig** [comment]
We appear to have commented at the same time. I will review and leave the case open. 

@martinbherbener I am sure you understand that undocumented trace flags, fixes, commands etc. provided by CSS are tailored for your situation and not always suitable to be publicly documented or apply to a broad range of scenarios.

Have you considered alternates such as CDC and SSIS or ADF?

**Comment by briancarrig** [comment]
Also I will talk to Jack Li ... 

Feel free to email me first.last at microsoft.com if you prefer not to have whole conversations as Github issues :-)

**Comment by martinbherbener** [comment]
Hi,

I understand that actual fixes are not likely to happen and that documented specifics of the workaround may not be wise.  I guess my main remaining suggestion is to update the documentation to make it clear that not only is the functionality deprecated, it doesn't actually work as described, at least for Oracle 12c.

I understand that for future work we will need to use a different feature/technology.

thanks!

Martin

**Comment by briancarrig** [comment]
`I guess my main remaining suggestion is to update the documentation to make it clear that not only is the functionality deprecated, it doesn't actually work as described, at least for Oracle 12c.`

We do call out 12c specifically, but perhaps not clearly enough or in the appropriate manner.

![image](https://user-images.githubusercontent.com/11153968/96308342-0f4c7480-0fb8-11eb-960e-9e108fcfb546.png)

https://docs.microsoft.com/en-us/sql/relational-databases/replication/non-sql/heterogeneous-database-replication?view=sql-server-ver15

**Comment by briancarrig** [comment]
Again, I will mention a strong recommendation to upgrade to SQL 2019. Development edition is free and would give you an opportunity to experiment with newer features that might meet your use case.

**Comment by martinbherbener** [comment]
Understood re recommendation, I have no intention of trying to make this work at this point.

I think "Up to Oracle 12c" could easily be interpreted as "up to and including Oracle 12c", especially since in the preceding row you are (I think) including 10g in what is supported.

Thanks!

Martin

**Comment by MashaMSFT** [comment]
Hi @martinbherbener , thanks so much for reaching out and providing your feedback! I have processed a change to update the supportability and it will be live either later this week, or possibly next. 

I'll close out this Git Issue but please feel free to comment should you need anything further.

Thanks again and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
