### ISSUE TITLE
Estimates are way under actual size and not helpful

### ISSUE THREAD

**Issue by markaugust** [MicrosoftDocs/sql-docs#5239]
Using this page, my estimates were way off from what the actual size of the index is.  I believe the issue is in Step 2.4.  It states:

> If there are variable-length columns in the index key, including any necessary clustering key columns as described previously in Step 2.2, determine how much space is used to store the columns within the index row ... If there are no variable-length columns, set Variable_Leaf_Size to 0.

This makes it sound like the formula should only be used when there are Variable Length Columns in the Index Key. However, when I took that approach, my estimates were way off because my indexes didn't have any variable length columns in the Index Key, and therefore I was setting the Variable_Leaf_Size to 0.

I'm assuming this is incorrect, as when I started using the formula in this step, my estimates were closer to what they should have been, even though I have no variable key columns in my index key.  Plus it doesn't make sense that the calculation for the Variable_Leaf_Size should be dependent on if there is a variable column in the index key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acd0f89f-5bd7-5332-fbb5-2c362d9da599
* Version Independent ID: 78e1a2f9-2aa1-06a8-ff64-21cfe75b2540
* Content: [Estimate the Size of a Nonclustered Index - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/estimate-the-size-of-a-nonclustered-index?view=sql-server-2017)
* Content Source: [docs/relational-databases/databases/estimate-the-size-of-a-nonclustered-index.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/estimate-the-size-of-a-nonclustered-index.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@markaugust -- thank you for your feedback.

@stevestein -- please look into this issue.

**Comment by stevestein** [comment]
@markaugust - thanks for raising this issue. 

To clarify, instead of setting to zero you're setting Variable_Leaf_Size to 2 before continuing to the next step, because in your situation setting to zero resulted in an inaccurate result?

**Comment by markaugust** [comment]
@stevestein 

I'm not necessarily setting Variable_Leaf_Size to 2.  I'm setting it to _Variable_Leaf_Size = 2 + (Num_Variable_Leaf_Cols x 2) + Max_Var_Leaf_Size_.  Originally, I was setting it to 0 because the wording made it sound like I should since I didn't have any variable length columns in my index key, just one variable length column in my included columns.

> If there are variable-length columns in the index key [use the formula]

and then
> If there are no variable-length columns, set Variable_Leaf_Size to 0

which makes it sound like if I have no variable length columns in the Index Key, then I should set the Variable_Leaf_Size to 0, no matter how many variable length columns I have in my included columns.  However, because I had a variable length column in my included columns, this didn't seem to be getting figured into the calculation, and the estimates were way under the actual size of the index.

So once I started setting _Variable_Leaf_Size = 2 + (Num_Variable_Leaf_Cols x 2) + Max_Var_Leaf_Size_ even though I didn't have any variable length columns in my index key, the estimates were closer to what the actual size of the index was.

**Comment by stevestein** [comment]
@markaugust - thanks for the details. 

It's not 100% clear here:
If there are variable-length columns in the index key, **_including any necessary clustering key columns as described previously_** in Step 2.2, determine how much space is used to store the columns within the index row:


So I added this to clarify step 2.4:

_If there are no variable-length columns (key columns or included), set ***Variable_Leaf_Size*** to 0._

**Comment by markaugust** [comment]
@stevestein - Thank you.

Should the first paragraph in step 2.4 also say "If there are variable-length columns in the index key **or included columns**..."

**Comment by stevestein** [comment]
@markaugust - Thanks for the feedback.  I updated the first sentence for 2.4.

**Comment by stevestein** [comment]
#please-close
