### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Librichard** [MicrosoftDocs/sql-docs#5245]
Hi there.

When you click on `Set Operators` link it just opens the same page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cb39e42-9f1b-33e1-6409-3734766d2d63
* Version Independent ID: cabf1bdc-3eaf-dca0-9a6b-9c924549e4c9
* Content: [Operators (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/operators-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/t-sql/language-elements/operators-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/operators-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@Librichard -- Richard, thank you for catching that.  I am looking into this article.
