### ISSUE TITLE
DBCC command 'SHOWRESULTCACHESPACEUSED' is not supported in this version of SQL Server.

### ISSUE THREAD

**Issue by blakemartin** [MicrosoftDocs/sql-docs#5246]
Am seeing this response when trying to run this command in Synapse:

DBCC command 'SHOWRESULTCACHESPACEUSED' is not supported in this version of SQL Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66637528-2d6c-4798-db89-3abd393f75a4
* Version Independent ID: 21f933e5-a3d4-46a8-9f3e-b2f9e14e6647
* Content: [DBCC SHOWRESULTCACHESPACEUSED (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-showresultcachespaceused-transact-sql?toc=%2Fazure%2Fsynapse-analytics%2Fsql-data-warehouse%2Ftoc.json&bc=%2Fazure%2Fsynapse-analytics%2Fsql-data-warehouse%2Fbreadcrumb%2Ftoc.json&view=azure-sqldw-latest)
* Content Source: [docs/t-sql/database-console-commands/dbcc-showresultcachespaceused-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/database-console-commands/dbcc-showresultcachespaceused-transact-sql.md)
* Product: **sql**
* Technology: **data-warehouse**
* GitHub Login: @XiaoyuMSFT
* Microsoft Alias: **xiaoyul**

**Comment by WilliamAntonRohm** [comment]
@blakemartin -- thank you for your feedback.

@XiaoyuMSFT -- Xiaoyu, please look into this issue.

**Comment by XiaoyuMSFT** [comment]
@blakemartin - Please make sure you run this command in the Synapse database, not in the master database, otherwise you will get this error.

**Comment by XiaoyuMSFT** [comment]
#please-close
