### ISSUE TITLE
Missing double quotes 

### ISSUE THREAD

**Issue by LBanfalvi** [MicrosoftDocs/sql-docs#5253]
On SLES, the correct command for php configuration is (missing double quotes):
echo "extension=pdo_sqlsrv.so" >> `php --ini | grep "Scan for additional .ini files" | sed -e "s|.*:\s*||"`/pdo_sqlsrv.ini
echo "extension=sqlsrv.so" >> `php --ini | grep "Scan for additional .ini files" | sed -e "s|.*:\s*||"`/sqlsrv.ini

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f591be-6564-c959-7a92-6489bdd4f60b
* Version Independent ID: eec72536-eda0-1bc8-a41a-36ed4b9a8883
* Content: [Linux and macOS Installation for the Drivers for PHP - SQL Server](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017#installing-the-drivers-on-suse-12-and-15)
* Content Source: [docs/connect/php/installation-tutorial-linux-mac.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/installation-tutorial-linux-mac.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @ulvii
* Microsoft Alias: **v-ulibra**

**Comment by WilliamAntonRohm** [comment]
@LBanfalvi -- László, thank you for catching this.  I am looking into the article.

**Comment by WilliamAntonRohm** [comment]
@ulvii -- please review [private PR 16311](https://github.com/MicrosoftDocs/sql-docs-pr/pull/16311).

**Comment by ulvii** [comment]
I don't work with PHP anymore, @yitam  can help.

**Comment by yitam** [comment]
Double quotes are not necessary when using echo statements, even in SLES

**Comment by David-Engel** [comment]
Closing this issue given the above response.

#please-close
