### ISSUE TITLE
There's an error in the BCPFORMAT tag

### ISSUE THREAD

**Issue by dondumortier** [MicrosoftDocs/sql-docs#5255]
[Enter feedback here]

the value for xmlns shoud be with HTTP, not HTTPS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe073190-9591-00f0-0d07-8f1fcf16bbc0
* Version Independent ID: 769fb224-8abc-29b4-355d-bab3417be8c1
* Content: [Use a format file to bulk import data - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/use-a-format-file-to-bulk-import-data-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/import-export/use-a-format-file-to-bulk-import-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/use-a-format-file-to-bulk-import-data-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @dondumortier , this change has been processed and is now live.

Thanks for improving our documentation! Hope you have a wonderful rest of your day :) 
Masha from the SQL Docs team
