### ISSUE TITLE
SQL Server for Ubuntu 20.04

### ISSUE THREAD

**Issue by UltimateYZ** [MicrosoftDocs/sql-docs#5256]
Hello SQL devs,
Are there any support plans for Ubuntu 20.04? I'm wondering about that for a quite time...

**Comment by WilliamAntonRohm** [comment]
@UltimateYZ -- thank you for your question.  Please see this related comment:
- https://github.com/MicrosoftDocs/sql-docs/issues/4678#issuecomment-622044539
