### ISSUE TITLE
Duplicate link

### ISSUE THREAD

**Issue by kalendelaney** [MicrosoftDocs/sql-docs#5259]
[Enter feedback here]
The last two links on this page (in the "for more info" section, point to the same place

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d91022-0ff5-2a0e-4711-217fd9568018
* Version Independent ID: cd30c087-06e7-f947-cf6a-262001d574a3
* Content: [Intelligent query processing - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/intelligent-query-processing?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/intelligent-query-processing.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/intelligent-query-processing.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @joesackmsft
* Microsoft Alias: **josack**

**Comment by joesackmsft** [comment]
Thanks Kalen - good catch. Looks like two issues opened for this, but I'll comment on both.  I removed the redundant link as all scripts in the AQP topic are in the IQP topic now.  PR submitted and will be reflected by this afternoon.
#please-close

**Comment by kalendelaney** [comment]
Thanks for getting back to me!

I was doing final edits on a new Learn course containing info on AQP and IQP and wanting to see what the correct capitalization was. It was looking like Adaptive Query Processing is not even used as a term anymore. Is that correct?



Kalen Delaney, Global Technical Learning -  Data & AI, World Wide Learning
kadelane@microsoft.com<mailto:kadelane@microsoft.com> | twitter: @sqlqueen

**Comment by joesackmsft** [comment]
"Adaptive Query Processing" is really a subset of the overall Intelligent
Query Processing feature family.  We had to expand the terminology, because
not everything is adaptive by definition.  We still plan on adding more
adaptive mechanisms, so you'll still see AQP as a sub-tree in the overall
IQP tree.

**Comment by kalendelaney** [comment]
Yes, I know it’s a subset … but is the term ever really used or should we just talk about Intelligent Query Processing instead?

Kalen Delaney, Global Technical Learning -  Data & AI, World Wide Learning
kadelane@microsoft.com<mailto:kadelane@microsoft.com> | twitter: @sqlqueen

**Comment by joesackmsft** [comment]
Feel free to use Intelligent Query Processing (IQP) moving forward.  AQP is
valid terminology still, but you achieve the same high-level aim by talking
about IQP.
