### ISSUE TITLE
Duplicate LInk

### ISSUE THREAD

**Issue by kalendelaney** [MicrosoftDocs/sql-docs#5260]
[Enter feedback here]
The last two links on this page (in the "see also" section, point to the same place

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d91022-0ff5-2a0e-4711-217fd9568018
* Version Independent ID: cd30c087-06e7-f947-cf6a-262001d574a3
* Content: [Intelligent query processing - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/intelligent-query-processing?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/intelligent-query-processing.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/intelligent-query-processing.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @joesackmsft
* Microsoft Alias: **josack**

**Comment by joesackmsft** [comment]
Good catch!  Thanks Kalen.  Will fix this today.

**Comment by joesackmsft** [comment]
PR now submitted.  Should be updated later this day.
#please-close
