### ISSUE TITLE
sqlserver_start_time needs clarification

### ISSUE THREAD

**Issue by rtaylor72** [MicrosoftDocs/sql-docs#5263]
sqlserver_start_time needs clarification:
Is it UTC time
OR
Is it local time

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1073200-d5d6-a64e-d8d8-a4809873822b
* Version Independent ID: aab7789b-e333-2d9a-bfb9-52106184c156
* Content: [sys.dm_os_sys_info (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@rtaylor72 -- Robert, thank you for your question.  It is your system's local time.


cc @CarlRabeler for awareness

**Comment by rtaylor72** [comment]
Can the docs be updated to reflect that?

Thanks!

Robert Taylor

________________________________

**Comment by WilliamAntonRohm** [comment]
@rtaylor72 -- Robert, thank you for your suggestion.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@CarlRabeler -- Carl, please review [private PR 16353](https://github.com/MicrosoftDocs/sql-docs-pr/pull/16353).
