### ISSUE TITLE
additional remark required

### ISSUE THREAD

**Issue by pmehrwald** [MicrosoftDocs/sql-docs#5264]
Hi,

in my opinion, there should be some information, that the CTE is executed everytime it is used later in the query.

E.g.
```
with cte(id) as 
(
    select NEWID() as id
)
select * from cte
union all
select * from cte
```
Is returning 2 different guids, not the same. I would expect, that it is actually returning the same guid twice (and that the CTE result set is kept in memory for the current query). 
This has a huge impact on the performance when the CTE query is more expensive. And there is an easy workaround e.g. using temporary tables or table variables. 

Thank you,
Philipp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e25ceb80-19cf-5c95-cb88-9affc2c6abc3
* Version Independent ID: 3c6696e6-ec06-0fe5-5e27-07aa961c2457
* Content: [WITH common_table_expression (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/queries/with-common-table-expression-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/with-common-table-expression-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@pmehrwald -- thank you for your feedback.

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
Hi @pmehrwald! Sorry for the delay. I am looking into this.

**Comment by VanMSFT** [comment]
Following up with the Product Group.

**Comment by VanMSFT** [comment]
Hi @pmehrwald! Here's the explanation from our Product Group:


> It’s not that “CTE is executed twice”, it’s that doing a UNION ALL from two queries on the same table, or a self-join query will result in the same object being accessed twice. So it’s not a characteristic of CTEs and saying that induces misconceptions. 
> In most cases, both have to be represented in a plan, and both show reads (saying most cases because I imagine that with proper referential integrity this may not be the case, but referential integrity only exists in schema objects like tables or views).
> 
> For example
> 
> -- Define the CTE expression name and column list.  
> WITH Sales_CTE (SalesPersonID)  
> AS  
> -- Define the CTE query.  
> (  
>     SELECT DISTINCT SalesPersonID  
>     FROM Sales.SalesOrderHeader  
> )
> -- Define the outer query referencing the CTE name.  
> SELECT *  
> FROM Sales_CTE AS t1
> INNER JOIN Sales_CTE AS t2 ON t1.SalesPersonID = t2.SalesPersonID 
> GO
> 
> Has the same plan and IO as:
> 
> -- Define the CTE expression name and column list.  
> WITH Sales_CTE (SalesPersonID)  
> AS  
> -- Define the CTE query.  
> (  
>     SELECT DISTINCT SalesPersonID  
>     FROM Sales.SalesOrderHeader  
> ),
> Sales2_CTE (SalesPersonID)  
> AS  
> -- Define the CTE query.  
> (  
>     SELECT * FROM Sales_CTE  
> )
> -- Define the outer query referencing the CTE name.  
> SELECT *  
> FROM Sales_CTE AS t1
> INNER JOIN Sales2_CTE AS t2 ON t1.SalesPersonID = t2.SalesPersonID 
> GO
> 
> And has the same plan and IO as:
> 
> SELECT DISTINCT t1.SalesPersonID, t2.SalesPersonID  
> FROM Sales.SalesOrderHeader AS t1
> INNER JOIN Sales.SalesOrderHeader AS t2 ON t1.SalesPersonID = t2.SalesPersonID 
> GO
> 
> Or
> -- Define the CTE expression name and column list.  
> WITH Sales_CTE (SalesPersonID)  
> AS  
> -- Define the CTE query.  
> (  
>     SELECT DISTINCT SalesPersonID  
>     FROM Sales.SalesOrderHeader  
>     WHERE SalesPersonID IS NOT NULL  
> ),
> Sales2_CTE (SalesPersonID)  
> AS  
> -- Define the CTE query.  
> (  
>     SELECT * FROM Sales_CTE  
> )
> -- Define the outer query referencing the CTE name.  
> SELECT *  FROM Sales_CTE 
> UNION ALL
> SELECT *  FROM Sales2_CTE 
> GO
> 
> Has the same plan and IO as:
> 
> SELECT DISTINCT SalesPersonID  
> FROM Sales.SalesOrderHeader  
> WHERE SalesPersonID IS NOT NULL  
> UNION ALL
> SELECT DISTINCT SalesPersonID  
> FROM Sales.SalesOrderHeader  
> WHERE SalesPersonID IS NOT NULL
> GO
> 
> What the user is trying to achieve is best done using a local variable. That’s NOT a use case for a CTE. Think of a CTE as a inlined non-persisted TVF.

Please let us know if there are any further concerns. Thanks again for submitting this issue, and for your patience.
