### ISSUE TITLE
Approve as baseline bug

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/sql-docs#5265]
Selecting any security check finding and clicking 'Approve as Baseline' throws the error below. Here is version info:
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) 

TITLE: Microsoft SQL Server Management Studio
------------------------------

VA2032 - Failed to set baseline. (Microsoft.SqlServer.Management.ThreatDetection)

------------------------------
ADDITIONAL INFORMATION:

One or more errors occurred. (mscorlib)

------------------------------

Could not load file or assembly 'Microsoft.Azure.Storage.Common, Version=11.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. (DataSec.VA.Core.Baseline)

------------------------------
BUTTONS:

OK
------------------------------

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2d785ce-ee98-7cbf-a016-b88f6947dd8e
* Version Independent ID: 2ecb2905-5c58-f768-3487-5af00d983102
* Content: [SQL Vulnerability Assessment - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/sql-vulnerability-assessment?view=sql-server-2017)
* Content Source: [docs/relational-databases/security/sql-vulnerability-assessment.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/sql-vulnerability-assessment.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
@SharePointBlackBelt -- Vincent, thank you for your feedback.  This repo is solely for documentation issues, and it looks like you've found a product bug.  Please report this here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @yualan for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
