### ISSUE TITLE
Incorrect number on document

### ISSUE THREAD

**Issue by TrickyS2010** [MicrosoftDocs/sql-docs#5266]
The line that reads :-

n* is zero to three digits, ranging from 0 to 999, that represent the fractional seconds.

Should read :-

n* is zero to three digits, ranging from 0 to 997, that represent the fractional seconds.

As the details say below that the last digit has to be 0,3 or 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1774f2f4-950d-03af-fc87-f75099f31835
* Version Independent ID: 76893d14-e1ed-0d4a-6092-15d25628ce14
* Content: [datetime (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/data-types/datetime-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/datetime-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@TrickyS2010 -- thank you for your feedback.  I believe the document is correct as-is.  The fractional second representation is 0-999 before rounding, while the rounded accuracy is .000, .003, or .007.

@MikeRayMSFT -- please confirm my understanding.
