### ISSUE TITLE
Should specify the number of arguments needs to be 254 or less

### ISSUE THREAD

**Issue by AaronBertrand** [MicrosoftDocs/sql-docs#5267]
The original CONCAT document (https://docs.microsoft.com/en-us/sql/t-sql/functions/concat-transact-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-previousversions) specifies 254 as the upper bound on the number of string arguments, but the CONCAT_WS document is missing this (important) detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f748e679-fde4-3cc7-4200-7b45adb74a21
* Version Independent ID: 6946f36e-4731-1ed9-365a-0085103a630e
* Content: [CONCAT_WS (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/concat-ws-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/concat-ws-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/concat-ws-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@AaronBertrand -- thank you for noticing this.  I am looking into the article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review [private PR 16344](https://github.com/MicrosoftDocs/sql-docs-pr/pull/16344).
