### ISSUE TITLE
Incorrect number of rows for maximum number of rows in a row group

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/sql-docs#5275]
In the table, for the trim_reason_desc field, the description states:

> 1 - NO_TRIM: The row group was not trimmed. The row group was compressed with the maximum of 1,048,476 rows. The number of rows could be less if a subset of rows was deleted after delta rowgroup was closed

This is incorrect.  The number should be 1,048,**5**76 rows, not 1,048,**4**76.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a24a194b-16d9-79e4-8483-95aaf2833c67
* Version Independent ID: 108fd3b5-631f-384f-25a0-6badb3a26428
* Content: [sys.dm_db_column_store_row_group_physical_stats (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-column-store-row-group-physical-stats-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-db-column-store-row-group-physical-stats-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-db-column-store-row-group-physical-stats-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@pmasl Pedro, could you please look at this issue?

**Comment by cawrites** [comment]
#reassign:cawrites

**Comment by cawrites** [comment]
@cbailiss thank you for contacting Microsoft regarding this issue. We have resolved this issue and it will be reflected in the next content update. Please don't hesitate to contact us again if you have any more questions.

**Comment by cawrites** [comment]
#please-close
