### ISSUE TITLE
BNF for search_condition_without_match looks wrong

### ISSUE THREAD

**Issue by siggemannen** [MicrosoftDocs/sql-docs#5280]
Hi,

On this page: https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/search-condition-transact-sql.md

I'm wondering about this part:
```
<search_condition_without_match> ::= 
    { [ NOT ] <predicate> | ( <search_condition_without_match> ) }   
    [ { AND | OR } [ NOT ] { <predicate> | ( <search_condition_without_match> ) } ]   
[ ,...n ] 
```

In which case is the `[ ,...n ]` comma applicable when searching on conditions?

**Comment by msebolt** [comment]
@siggemannen Thank you for the feedback.

The BNF in question describes the repeatable nature of a search criteria without use of `MATCH`, for example:

```
SELECT * FROM table WHERE
column1 = value1 AND NOT (column2 = value2 OR column3 = value3)
```

`MATCH` is generally preferred, however does not support `OR` and `NOT`, see [MATCH](https://docs.microsoft.com/sql/t-sql/queries/match-sql-graph?view=sql-server-ver15#remarks).

**Comment by siggemannen** [comment]
I see. But shouldn't it be `[...n]` then and not `[,...n]` ?

I'm not too good at the BNF syntax, building a little parser and wonder if the "," ever occurs between the selections or it should be just space between

**Comment by msebolt** [comment]
Good point, some sections such as [SELECT](https://docs.microsoft.com/sql/t-sql/queries/select-transact-sql?view=sql-server-ver15) appear to use `[,...n]`, while others such as [CASE](https://docs.microsoft.com/sql/t-sql/language-elements/case-transact-sql?view=sql-server-ver15) use `[...n]`.

Assigning this to the author for further review.

**Comment by VanMSFT** [comment]
Hi @siggemannen! You are right. I am updating the doc. Thanks for submitting this issue and helping with our documentation.
