### ISSUE TITLE
The note about failing to start seems out-of-date

### ISSUE THREAD

**Issue by runekock** [MicrosoftDocs/sql-docs#5282]
The page about startup options does not mention -g.  I assume that this option does no longer exist in recent versions of SQL Server.

From reading elsewhere, it seems to reserve the specified number of megabytes for misc. purposes, including CLR. (default 256).

Maybe it only makes sense on a 32-bit version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f0bea49-5769-bc96-7f5d-377a96ceda78
* Version Independent ID: d71ae472-8ba4-4060-b83d-600436a66ed7
* Content: [Enabling CLR Integration - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/clr-integration-enabling?view=sql-server-ver15)
* Content Source: [docs/relational-databases/clr-integration/clr-integration-enabling.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/clr-integration/clr-integration-enabling.md)
* Product: **sql**
* Technology: **clr**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@runekock  Thank you for the feedback.

The `-g` option appears to be from versions 2012 and 2014 and can be referenced in the [previous documentation](https://support.microsoft.com/help/2663912/memory-configuration-and-sizing-considerations-in-sql-server-2012-and).

This parameter is out-dated and should be removed from the documentation.

For memory setting specifics, please refer to [server memory configuration options](https://docs.microsoft.com/sql/database-engine/configure-windows/server-memory-server-configuration-options).

**Comment by rothja** [comment]
@runekock Thanks for the question. I will get that option removed after I investigate/confirm. Sorry for the confusion! I hope the link that Matthew sent helps.

**Comment by rothja** [comment]
I'm going to close out this issue as I don't think we have changes to make. But please let me know if I misunderstand. Thanks for the feedback!
