### ISSUE TITLE
Quick question on license?

### ISSUE THREAD

**Issue by killmasta93** [MicrosoftDocs/sql-docs#5290]
Hi,
I was wondering if someone could shed some light, Currently were going to install MSSQL linux, the idea is that were going to buy the standard license but we need to try a few tests before, so not sure what option i should choose. As option 1 is evaluation, but after we buy the license how would i insert it again? OR go with option 5 but it says that using this option i should already bought the license but how would it know if i dont put any key?  and then there is option 8 which lets me put in the key. So im confused on licensing part

Thank you

**Comment by msebolt** [comment]
@killmasta93 Thank you for the question.

Unfortunately the support options in this forum are limited to specific documentation examples only.

Is there a page you can provide where the information on this is unclear?

For additional support options, please see [here](https://support.microsoft.com/help/4047326/support-policy-for-microsoft-sql-server).

**Comment by killmasta93** [comment]
thanks for the reply, the options that i was talking about is when its going to run the command 

```
sudo /opt/mssql/bin/mssql-conf setup
Choose an edition of SQL Server:
  1) Evaluation (free, no production use rights, 180-day limit)
  2) Developer (free, no production use rights)
  3) Express (free)
  4) Web (PAID)
  5) Standard (PAID)
  6) Enterprise (PAID)
  7) Enterprise Core (PAID)
  8) I bought a license through a retail sales channel and have a product key to enter.

Details about editions can be found at
https://go.microsoft.com/fwlink/?LinkId=852748

Use of PAID editions of this software requires separate licensing through a
Microsoft Volume Licensing program.
By choosing a PAID edition, you are verifying that you have the appropriate
number of licenses in place to install and run this software.

Enter your edition(1-8):
```

and thats the part im confused whats the difference from option 5 or 8 
the question is that if i buy the standard license though Microsoft Volume Licensing program. would i need to enter the License code? 

Thank you

**Comment by WilliamAntonRohm** [comment]
@killmasta93 -- please see the [SQL Server 2019 licensing guide ](https://download.microsoft.com/download/e/2/9/e29a9331-965d-4faa-bd2e-7c1db7cd8348/SQL_Server_2019_Licensing_guide.pdf). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
