### ISSUE TITLE
Hi There,

### ISSUE THREAD

**Issue by azadehgnia** [MicrosoftDocs/sql-docs#5291]
Hi there,

In the documentation for SQL Server 2016 and 2017 there are more editions of Windows listed, such as Windows 10 IoT Eterprise, but for SQL Server 2019 it is not the case, could it be an error or is it supporting less operating systems?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09beb1a-92a9-4335-511c-395ba64c875b
* Version Independent ID: 8f43fca3-43d7-a2e4-1469-bf17f14d9ac8
* Content: [SQL Server 2019: Hardware & software requirements - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15?view=sql-server-ver15)
* Content Source: [docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@azadehgnia  Thank you for the question.

Assigning this to the author for additional review.

**Comment by MikeRayMSFT** [comment]
@azadehgnia - thank you for the question.

I'm confirming the support with my engineering partners. Will reply soon.
