### ISSUE TITLE
When picking a version, the "Older" option does not direct to older documentation, it sends you to the newest

### ISSUE THREAD

**Issue by bmercernccer** [MicrosoftDocs/sql-docs#5292]
When reviewing documentation , attempt to select the Older option from the list of SQL Server versions
Result:

The requested page is not available for SQL Server previous versions. You have been redirected to the newest product version this page is available for.

When someone is looking for documentation for an OLDER version of SQL Server, sending them to the documentation for the absolutely newest version is the least appropriate, least helpful, and most frustrating thing you could do. 

Given that older documentation is actually still available, I see no reason why this option could not send you to it. I can only assume this is a decision made by someone in marketing, as only marketing could show such disregard for the value of historlcal content.

**Comment by msebolt** [comment]
@bmercernccer Thank you for the feedback.

Please provide the reference link to an example of this behaviour and we will look into this further.

**Comment by bmercernccer** [comment]
Here are a couple of examples, the behavior is pretty consistent across different pages. 
https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server
https://docs.microsoft.com/en-us/sql/reporting-services/install-windows/install-reporting-services
Attached are a couple of screen shots showing the behavior. 
![Annotation 2020-08-06 153139](https://user-images.githubusercontent.com/21127097/89574467-2d4c6a80-d7fa-11ea-8d7f-83fa9dc1c205.png)
![Annotation 2020-08-06 153150](https://user-images.githubusercontent.com/21127097/89574478-350c0f00-d7fa-11ea-87bc-a56e0ab0e4af.png)

Here's the URL after attempting to click the Older version option from the menu. .
https://docs.microsoft.com/en-us/sql/reporting-services/install-windows/install-reporting-services?view=sql-server-ver15&viewFallbackFrom=sql-server-previousversions

**Comment by WilliamAntonRohm** [comment]
@bmercernccer -- please submit issues related to overall site experience, or suggestions for improved site functionality or design, to [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback). 

cc @rothja for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by bmercernccer** [comment]
Sigh… why did I expect anything better than this?
When will I learn.

**Comment by rothja** [comment]
@bmercernccer Hello. I'm the manager for the SQL documentation. Sorry for your disappointment with the response here. Actually, what you say here is completely valid and something that we control in our SQL documentation for versioning. We've recently been trying to improve the versioning experience, and our decision is that the experience of selecting "older versions" is broken as you've pointed out. Sorry about the confusion. We are going to remove this, and direct people to previous versions in two ways:

1. We are putting a not on how to find previous versions in many T-SQL reference articles.

1. We hope readers will spot the Previous versions article in the table of contents at the top. 

In both cases, we link to this article: [Previous versions of SQL Server documentation](https://docs.microsoft.com/en-us/sql/sql-server/previous-versions-sql-server?view=sql-server-ver15).

I hope this helps. I know the much better experience would be if all articles linked directly to their older counterparts, but we are not able to wire that up right now. We hope the older/offline versions of the docs will help when needed. Please let me know if you have any questions. #assign:rothja

**Comment by PRMerger16** [comment]
rothja is already assigned.
