### ISSUE TITLE
"Capture trace" section seems to be missing?

### ISSUE THREAD

**Issue by Robert-Kostecki** [MicrosoftDocs/sql-docs#5293]
What is the most efficient and vendor recommended way of collecting data for the distributed replay? 

This linked section in the article [https://docs.microsoft.com/en-us/sql/tools/distributed-replay/distributed-replay-requirements?view=sql-server-ver15](url) implies using "The TSQL_Replay template in **SQL Server Profiler**". However the tool (SQL Server Profiler) has been announced to be deprecated with SQL Server 2014 if memory serves well?

Can you please clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05c57eca-4aa0-5628-675a-fbeeea1355a8
* Version Independent ID: ec6be4b3-73c5-d5cd-cd9c-33980a2312a7
* Content: [Prepare the input trace data - SQL Server Distributed Replay](https://docs.microsoft.com/en-us/sql/tools/distributed-replay/prepare-the-input-trace-data?view=sql-server-ver15)
* Content Source: [docs/tools/distributed-replay/prepare-the-input-trace-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/distributed-replay/prepare-the-input-trace-data.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by msebolt** [comment]
@Robert-Kostecki Thank you for the feedback.

Assigning this to the author for additional review.

**Comment by markingmyname** [comment]
@msebolt 

SQL Server Profiler is not deprecated.

Hope this helps.

Thank you.
