### ISSUE TITLE
Comment mentions wrong algorithm

### ISSUE THREAD

**Issue by pete1854** [MicrosoftDocs/sql-docs#5294]
The first comment in the code windows says: "_Stored procedure that trains and generates a Python model using the rental_data and a decision tree algorithm"_

Since the sample is showing a stored procedure implementing a Linear Regression algorithm i think the comment needs to be updated to mention the correct algorithm.

Kind regards,
Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a32e6416-4a53-2d8b-ad22-f097b5b51e70
* Version Independent ID: cf34396e-0f4d-e284-8d40-1ae784f4b81a
* Content: [Python tutorial: Deploy model - SQL machine learning](https://docs.microsoft.com/en-us/sql/machine-learning/tutorials/python-ski-rental-linear-regression-deploy-model?view=sql-server-ver15)
* Content Source: [docs/machine-learning/tutorials/python-ski-rental-linear-regression-deploy-model.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/tutorials/python-ski-rental-linear-regression-deploy-model.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@pete1854 Thank you for reporting the issue. I have changed the algorithm to the correct one and the change will get published later today.
