### ISSUE TITLE
Update Query Store documentation to reflect what applies to Azure Synapse

### ISSUE THREAD

**Issue by SQLAdventurer** [MicrosoftDocs/sql-docs#5295]
Nearly all of the examples (SSMS functions features) for Query Store documentation do not apply to Azure Synapse.  Documentation should be updated to CLEARLY reflect those features that are not available to Azure Synapse. I cannot recommend this documentation to my customers as 90% does not apply to Azure Synapse and that which does not apply is not marked in any way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b587ab-50b8-eada-aa86-ba0c838c57ee
* Version Independent ID: f1fd2d52-b66f-4fbc-c54a-c688c4fd0f21
* Content: [Monitoring Performance By Using the Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=azure-sqldw-latest)
* Content Source: [docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@SQLAdventurer -- Tammy, thank you for your feedback.  I edited your title for brevity; please let me know if I captured your issue accurately, or revise it as needed.

@julieMSFT -- Julie, please look into this issue.

**Comment by julieMSFT** [comment]
@SQLAdventurer Hi Tammy, I am looking into this, thanks for bringing this to our attention.

**Comment by julieMSFT** [comment]
@WilliamAntonRohm Hi William, I think we should update the title to "Update Query Store documentation to reflect what applies to Azure Synapse. This issue is not about SSMS.

**Comment by julieMSFT** [comment]
@SQLAdventurer Hi Tammy, the docs for query store are undergoing a rewrite. I am going to create a work item to track this request. I will notify you once the article is updated. I will proceed with closing this issue and track it in the work item. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.
