### ISSUE TITLE
instructions for using -m are incorrect

### ISSUE THREAD

**Issue by TokenRing** [MicrosoftDocs/sql-docs#5307]
Using -m"SQLCMD" does not work. You have to use -mSQLCMD without the quotes. These incorrect instructions on that page had me running in circles for hours. This post solved my problem https://serverfault.com/a/338294

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41367fc-38cf-0c73-3ea8-93bff726f421
* Version Independent ID: 07b2d0b3-2013-a133-9d1e-ee2d249740d5
* Content: [Connect to SQL Server when system administrators are locked out - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@TokenRing -- thank you for your feedback.  I am looking into this issue.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review [private PR 16615](https://github.com/MicrosoftDocs/sql-docs-pr/pull/16615).
