### ISSUE TITLE
Update link for: Django and SQL Database on Azure

### ISSUE THREAD

**Issue by hecj1** [MicrosoftDocs/sql-docs#5310]
The original link https://github.com/Microsoft/PTVS/wiki/Django-and-SQL-Database-on-Azure directs the user to a retired repo page, the link should be updated to direct the user to https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python?tabs=bash (Quickstart: Create a Python app in Azure App Service on Linux)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7625e88c-5f6b-c5c8-7708-0123aa115c2f
* Version Independent ID: e6548c63-31ef-31d1-f4b4-46234dc7e1a7
* Content: [Python Driver for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/connect/python/python-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/python/python-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/python/python-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@hecj1 -- James, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
