### ISSUE TITLE
PolyBase head node information is out of date

### ISSUE THREAD

**Issue by awilbert** [MicrosoftDocs/sql-docs#5315]
In the Process Overview section, bullet 2, it says "A head node can only be designated on an instance running SQL Server Enterprise." That appears to have changed in SQL Server 2019, and head nodes can now be created on Enterprise or Standard according to the chart here: https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-version-15?view=sql-server-ver15#Programmability
Specifically note 4, which reads "4) Prior to SQL Server 2019 PolyBase head node requires Enterprise Edition."

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acaaf25c-0a4e-05af-dc8f-307ff92e3b17
* Version Independent ID: 14446de6-0c23-fae4-135c-4cc34aff96a3
* Content: [Configure PolyBase scale-out groups on Windows - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/configure-scale-out-groups-windows?view=sql-server-ver15)
* Content Source: [docs/relational-databases/polybase/configure-scale-out-groups-windows.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/configure-scale-out-groups-windows.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@awilbert -- Adam, thank you for your feedback.  I am looking into this article.
