### ISSUE TITLE
Incorrect slash on SetSPN example

### ISSUE THREAD

**Issue by gmafodda** [MicrosoftDocs/sql-docs#5318]
Hi, you have used the incorrect slash for the domain account in the example of setspn.  The current text is:

setspn -A MSSQLSvc/AG1listener.Adventure-Works.com:1433 corp/svclogin2

It should be:

setspn -A MSSQLSvc/AG1listener.Adventure-Works.com:1433 corp\svclogin2

Regards.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c76c2d8c-17da-8982-8a91-dd9968efa26e
* Version Independent ID: 2ecd127b-9f05-1f89-bcea-a93e8ded60eb
* Content: [Connect to an availability group listener - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@gmafodda -- Glenn, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- please review [private PR 16686](https://github.com/MicrosoftDocs/sql-docs-pr/pull/16686).

**Comment by MashaMSFT** [comment]
Hi @WilliamAntonRohm  your change looks good, I have approved it, and it should be live later this week. I have closed out this Git Issue in the meantime. 

@gmafodda , thank you for your feedback and improving our docs! Just as an FYI, you can also update the docs yourself, if you were so inclined. Not only does this help improve the quality of our documentation, but it marks you as a contributor to the article! 

If you wanted to do so, follow these steps: 

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Name your file change and provide a description, if necessary
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page

Thanks again and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
