### ISSUE TITLE
i'm getting error while running you sample 'Figure' object has no attribute '_remove_ax' using matplotlib==3.3.0

### ISSUE THREAD

**Issue by mkobilansky** [MicrosoftDocs/sql-docs#5321]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0300ff9d-ace6-93b9-64b7-c570a5015d5e
* Version Independent ID: ad14f936-2cc5-b4b2-2727-63d1ee82f6f9
* Content: [Python tutorial: Explore and visualize data - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/tutorials/python-taxi-classification-explore-data?view=sql-server-ver15)
* Content Source: [docs/machine-learning/tutorials/python-taxi-classification-explore-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/tutorials/python-taxi-classification-explore-data.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by garyericson** [comment]
@mkobilansky - Thanks for taking time to send this feedback. Can you provide more context: Which sample code from the text were you running when this occurred? Thanks.

**Comment by mkobilansky** [comment]
The error coming from the
https://docs.microsoft.com/en-us/sql/machine-learning/tutorials/python-taxi-classification-introduction?view=sql-server-ver15
NYC
taxi example binary plot object generation, following line :  fig =
pickle.loads(tables[i][0])
Quite possible bug is in matplitlib 3.2.0 version

**Comment by garyericson** [comment]
@mkobilansky - Thanks. I'm working on reproducing this. 

Are you running this on SQL Server or something else like SQL Managed Instance or SQL Big Data Clusters?

**Comment by mkobilansky** [comment]
SQL server. SQL part is working OK.  The error coming from the python code
running in either AzureData Studio, jupyter notebook or vscode

**Comment by garyericson** [comment]
Sorry, I thought I responded to this already.

I've been trying to reproduce this. I have seen this specific error once, and a couple other similar errors, when I had different versions of Python or Python packages between SQL and the client computer. After I reinstalled locally (as necessary) to get the local versions to match the SQL versions, it runs for me without an error.

If matching versions doesn't work for you, the next step would for you to raise the question in [SQL Server on Q&A](https://docs.microsoft.com/answers/products/sql-server), or contact Microsoft Support to open a ticket for this issue. The process is described in [SQL Server help and feedback](https://docs.microsoft.com/sql/advanced-analytics/package-management/r-package-information).

I've been using this code to check the local Python and package versions:
```
# List the versions of Python packages used in this tutorial
import matplotlib
import pandas
import pickle
import pyodbc
import sys
import pkg_resources

print("Python = " + str(sys.version_info))

pkg_name = "matplotlib";  print(pkg_name + " = " + pkg_resources.get_distribution(pkg_name).version)
pkg_name = "pandas";      print(pkg_name + " = " + pkg_resources.get_distribution(pkg_name).version)
pkg_name = "pickleshare"; print(pkg_name + " = " + pkg_resources.get_distribution(pkg_name).version)
pkg_name = "pyodbc";      print(pkg_name + " = " + pkg_resources.get_distribution(pkg_name).version)
```

And this to check the same thing in SQL:
```
-- List the versions of Python packages used in this tutorial
EXECUTE sp_execute_external_script 
  @language = N'Python', 
  @script = N'
import matplotlib
import pandas
import pickle
import pyodbc
import sys
import pkg_resources

print("Python = " + str(sys.version_info))

pkg_name = "matplotlib";  print(pkg_name + " = " + pkg_resources.get_distribution(pkg_name).version)
pkg_name = "pandas";      print(pkg_name + " = " + pkg_resources.get_distribution(pkg_name).version)
pkg_name = "pickleshare"; print(pkg_name + " = " + pkg_resources.get_distribution(pkg_name).version)
pkg_name = "pyodbc";      print(pkg_name + " = " + pkg_resources.get_distribution(pkg_name).version)
'
```

**Comment by garyericson** [comment]
#please-close - I've done all I can. The next step is to use the Q&A Forum or Microsoft Support.
