### ISSUE TITLE
File limit?

### ISSUE THREAD

**Issue by dwang94118** [MicrosoftDocs/sql-docs#5322]
[It worked for small files (500 rows), but when I tried importing the complete file (48K+ rows), i get the error below -

Error inserting data into table. (Microsoft.SqlServer.Prose.Import)
The given value of type String from the data source cannot be converted to type nvarchar of the specified target column. (System.Data)
String or binary data would be truncated. (System.Data)

What is the maximum CSV file size for import?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d89ecc7f-4705-dabe-9f70-2070d4aa19c9
* Version Independent ID: 9c991bd5-535c-03b5-d810-c1b2ca7e7cb4
* Content: [Import Flat File to SQL - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/import-flat-file-wizard?view=sql-server-ver15)
* Content Source: [docs/relational-databases/import-export/import-flat-file-wizard.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/import-flat-file-wizard.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by dzsquared** [comment]
@dwang94118 there isn't an explicit file size limit for the flat file import wizard.  The error message you received suggests data in rows beyond the first 500 doesn't fit in the data types detected by PROSE in training on the first subset of data.

Have you run with error reporting enabled?  This will give you more in-depth information about the issue you're encountering.
![image](https://user-images.githubusercontent.com/12227241/90061841-92d9a480-dc9b-11ea-9288-84987e99ce1b.png)

**Comment by dwang94118** [comment]
I enabled the error reporting, but the message is the same.  My test file with 1K rows was imported without issue, but 1500 rows gives me the error.

TITLE: Microsoft SQL Server Management Studio
------------------------------
Error inserting data into table occured while inserting rows 0 - 100000. (Microsoft.SqlServer.Import.Wizard)
------------------------------
ADDITIONAL INFORMATION:
Error inserting data into table occured while inserting rows 0 - 100000. (Microsoft.SqlServer.Prose.Import)
------------------------------
The given value of type String from the data source cannot be converted to type nvarchar of the specified target column. (System.Data)
------------------------------
String or binary data would be truncated. (System.Data)
------------------------------
BUTTONS:
OK
------------------------------

**Comment by dzsquared** [comment]
@dwang94118 You will want to run the import with a smaller error reporting range to more closely identify with row contains data that does not fit the data types defined in the "Modify Columns" tab.  Once the row(s) are identified, you will need to adjust the data types.  Based on the error message, the nvarchar column(s) are not wide enough for the text.

**Comment by dzsquared** [comment]
@dwang94118 I hope you were able to identify the row(s) that were not fitting the trained data model.  Let me know if anything came up!

**Comment by dzsquared** [comment]
#please-close
