### ISSUE TITLE
Please move the summary to the bottom...

### ISSUE THREAD

**Issue by v-chojas** [MicrosoftDocs/sql-docs#5325]
There's a very good chance someone visiting this page already knows what the function is for, and just wants to check something - and so it is annoying to scroll past several paragraphs of fluff just to get to the syntax and parameter descriptions which are the crucial information in this *reference* material.

"provides the following connection attributes" is also inaccurate, since the phrase "connection attribute" has a very well-defined meaning in ODBC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 578fb505-6f97-3ec4-f0a3-f2ee169a9f87
* Version Independent ID: ee0f6ed6-214d-546b-aac1-b7f8b9b4bc5e
* Content: [SQLDriverConnect Function - SQL Server](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqldriverconnect-function?view=sql-server-ver15#feedback)
* Content Source: [docs/odbc/reference/syntax/sqldriverconnect-function.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/syntax/sqldriverconnect-function.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@v-chojas -- thank you for your feedback.

@David-Engel -- please look into this issue.

**Comment by David-Engel** [comment]
I've adjusted the summary, moving much of the content to the page that was already linked to at the bottom of the summary. This change should be reflected after tomorrow morning's publish.

#please-close
