### ISSUE TITLE
Check all tables with change tracking enabled   code issue

### ISSUE THREAD

**Issue by np0316** [MicrosoftDocs/sql-docs#5329]
[Enter feedback here]

-- Check all tables with change tracking enabled  
IF EXISTS (  
  SELECT COUNT(*) FROM sys.change_tracking_tables  
  WHERE min_valid_version > @last_synchronization_version )  
BEGIN  
  -- Handle invalid version & do not enumerate changes  
  -- Client must be reinitialized  
END
---

Shouldn't be as below? 

-- Check all tables with change tracking enabled  
IF EXISTS (  
  SELECT 1 FROM sys.change_tracking_tables  
  WHERE min_valid_version > @last_synchronization_version )  
BEGIN  
  -- Handle invalid version & do not enumerate changes  
  -- Client must be reinitialized  
END

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b26df5c-92a8-91e4-3fd1-e90d28157778
* Version Independent ID: ee0fa626-9318-7cf6-e27d-66d512fc2ee3
* Content: [Work with Change Tracking - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/work-with-change-tracking-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/track-changes/work-with-change-tracking-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/work-with-change-tracking-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@np0316 -- thank you for your feedback.  Your solution is correct, and I am updating this article.
