### ISSUE TITLE
[FEATURE REQUEST] SQL Server Management Studio Remains filters on connection configuration

### ISSUE THREAD

**Issue by buster95** [MicrosoftDocs/sql-docs#5332]
I would like to remains configuration about filters in management studio
filters on database,
filters on tables,
filters on views,
filters on procedures

![Anotación 2020-08-13 150401](https://user-images.githubusercontent.com/15637669/90187163-90984880-dd76-11ea-8d49-2b53f6a55feb.png)

**Comment by WilliamAntonRohm** [comment]
@buster95 -- Walter, thank you for your feedback.  Please add your feature request here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by buster95** [comment]
@WilliamAntonRohm I published the idea here https://feedback.azure.com/forums/908035-sql-server/suggestions/41149912-ssms-keep-filters-when-opening-or-closing
