### ISSUE TITLE
Management of metadata not related to sensitivity

### ISSUE THREAD

**Issue by JeffDeMarseille** [MicrosoftDocs/sql-docs#5337]
Dear,
This new implementation of the sensitivity feature is nice, even it should be more separated from the production databases and not nested inside.
What's a damage that MS has not included one extra free field or the possibility to manage our custom metadata structure, as a replacement of the Extended properties!
Regards,

Jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34863695-cd07-1260-4fea-66738c5fa80a
* Version Independent ID: 4c01015d-9c1d-db8e-84f5-379ffc5d5133
* Content: [SQL Data Discovery & Classification - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/sql-data-discovery-and-classification?view=sql-server-ver15&tabs=t-sql)
* Content Source: [docs/relational-databases/security/sql-data-discovery-and-classification.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/sql-data-discovery-and-classification.md)
* Service: **sql-database**
* GitHub Login: @DavidTrigano
* Microsoft Alias: **datrigan**

**Comment by DavidTrigano** [comment]
Hi @JeffDeMarseille, 

Thanks for your comments.
Metadata does not allow extra free field, this is why we can't support the scenario you are describing. Having said that, you can still use Extended properties to save additional data in case you need it.

Best,
D.

**Comment by WilliamAntonRohm** [comment]
@JeffDeMarseille -- thank you for your feedback.

@DavidTrigano -- thank you for your answer.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
