### ISSUE TITLE
Change MSDB forums to Q/A

### ISSUE THREAD

**Issue by TiborKaraszi** [MicrosoftDocs/sql-docs#5340]
The pages refers to the old MS MSDN forums, whcih are now read-only and nowadays we have Microsoft Q&A instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1b8751e-c59a-edd0-9c6d-1fde427d1945
* Version Independent ID: 9e48f7cb-7a85-ee36-81c2-590bb01ddb79
* Content: [SQL Server help and feedback - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-ver15)
* Content Source: [docs/sql-server/sql-server-get-help.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/sql-server-get-help.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@TiborKaraszi -- Tibor, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue.
