### ISSUE TITLE
EULA for SQL server on docker references "pre-release software"

### ISSUE THREAD

**Issue by kevin-david** [MicrosoftDocs/sql-docs#5346]
Is the link to the EULA describing the `-e "ACCEPT_EULA=Y"` option correct? It references a EULA that talks about "pre-release software" - my impression based on https://support.microsoft.com/en-us/help/4047326/support-policy-for-microsoft-sql-server is that container-based SQL is very much supported... 

Thanks for clarifying!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by WilliamAntonRohm** [comment]
@kevin-david -- Kevin, thank you for your question.

@vin-yu -- Vin, please look into this issue.

**Comment by VanMSFT** [comment]
Hey @vin-yu - Is there an updated EULA for 2019 GA?

**Comment by VanMSFT** [comment]
#reassign:amvin87

**Comment by VanMSFT** [comment]
@amvin87 - Hey Amit, can you please help track down the SQL Server 2019 EULA that is referenced in this article?

**Comment by amvin87** [comment]
@VanMSFT  There is an updated EULA for SQL 2019 GA, for now can you remove this hyperlink which points to the preview EULA for now, I will uploaded the latest EULA for SQL 2019 GA and then we can link it here again. 

@kevin-david  You are right, SQL Server containers on linux is a very well supported product and this is a documentation issue of being stale and not updated. Thank you for the feedback we will work on this and update the documentation.

**Comment by VanMSFT** [comment]
@amvin87 - Thanks Amit! I'm removing the link.

@kevin-david - Sorry for the delay, Kevin. We appreciate you reporting this issue!
