### ISSUE TITLE
[SQL Server 2019] Missing documents for Server Configuration Options

### ISSUE THREAD

**Issue by mufukuha** [MicrosoftDocs/sql-docs#5347]
There was an old issue [[SQL Server 2019] Settings missing for Server Configuration Options doc](https://github.com/MicrosoftDocs/sql-docs/issues/4376), but we still have missing docs for these options.

- allow filesystem enumeration 
- version high part of SQL Server
- version low part of SQL Server

**allow filesystem enumeration**
Since this option is useful for users, an official doc would be helpful.
[What’s New in sp_Configure Options](https://www.brentozar.com/archive/2018/09/whats-new-in-sql-server-2019-system-tables/)
> “allow filesystem enumeration” – defaults to 1, can be 0 or 1. If you’re trying to host a secure SQL Server and you don’t want people looking at the file system, like say you’re running Azure SQL DB, you might want to disable folks from browsing the file system. This would be useful for other hosting providers, too.

**version high part of SQL Server**
**version low part of SQL Server**
These options don't look like ones for admins. If they are for internal use, we want documentation explaining we should not change them because of internal use.
[Interesting Undocumented Tidbits in SQL Server 2019 CU2](https://www.brentozar.com/archive/2020/02/interesting-undocumented-tidbits-in-sql-server-2019-cu2/) 

> - 2 new entries in sys.configurations:
>   - 1593 – version high part of SQL Server – version high part of SQL Server that model database copied for
>   - 1594 – version low part of SQL Server – version low part of SQL Server that model database copied for

**Comment by WilliamAntonRohm** [comment]
@mufukuha --  Munenori, thank you for your suggestions.

@markingmyname -- Mark, please look into this issue.

cc @MikeRayMSFT for awareness

**Comment by mufukuha** [comment]
"allow filesystem enumeration" just exists for configuration but does not take effect as below.

https://www.sqlservercentral.com/blogs/sys-xp_delete_files-and-allow-filesystem-enumeration-two-new-undocumented-items-in-sql-server-2019

**Comment by markingmyname** [comment]
@mufukuha,

First, we apologize for the delayed response.

Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
@mufukuha, 

Sorry again for the late reply.

We are currently in talks of reassessing allow filesystem enumeration, version high part of SQL Server, and version low part of SQL Server.

Once we do, we should have new content out there.

Thank you for your contribution.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
