### ISSUE TITLE
COLUMN STORE INDEXES - Do not work with ROWLOCK hints

### ISSUE THREAD

**Issue by ermagana** [MicrosoftDocs/sql-docs#5354]
Our organization recently attempted to make a performance optimization by leveraging a column store index. In the process of regression testing, we found that update and delete statements using the ROWLOCK hint were failing due to the Column Store Index. This was a surprise to us, as we have not been able to find any Microsoft documentation that would have led us to believe this is a constraint. 

We'd request the constraint be added, so that future users of this great feature are aware before using the index. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 571bf244-1472-286b-d1a8-7db2e54f40a2
* Version Independent ID: bccbd120-47f3-78b7-0cd6-7d4198ea3604
* Content: [Columnstore indexes: Overview - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-overview?view=sql-server-ver15)
* Content Source: [docs/relational-databases/indexes/columnstore-indexes-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/columnstore-indexes-overview.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
Thank you @ermagana - I'm reviewing this with product partners & engineers.

**Comment by pmasl** [comment]
@ermagana you mean you hit error 651? That's by design. I'll add a note to docs.

@MikeRayMSFT see PR #16847

**Comment by ermagana** [comment]
Yes, thank you. Can you share a link to the updated docs?

**Comment by pmasl** [comment]
> Yes, thank you. Can you share a link to the updated docs?

https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table
