### ISSUE TITLE
tables

### ISSUE THREAD

**Issue by GonjaMichael** [MicrosoftDocs/sql-docs#5361]
[They should show the tables being joined and their respective columns
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f3f4741-a003-e127-ce4d-2bc2ded98886
* Version Independent ID: 576a3826-5b7a-15ab-6405-7cd445b6b7c0
* Content: [Joins (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/joins?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/joins.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/joins.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@GonjaMichael -- thank you for your feedback.  Please see my suggestions in your previous issue #5360.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
