### ISSUE TITLE
Path to BXLServer for Python may not be correct

### ISSUE THREAD

**Issue by tgilmour** [MicrosoftDocs/sql-docs#5363]
Hello,

In the "Collecting events from external processes" > "BXLServer" section, the Python path does not seem to match the default path on a SQL Server 2019 installation.
On a default installation the BXLServer.exe file is in path
C:\Program Files\Microsoft SQL Server\MSSQL_version_number.MSSQLSERVER\PYTHON_SERVICES\Lib\site-packages\revoscalepy\rxLibs
Could this be checked and if necessary updated please?

Thanks,
Tom Gilmour

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0d98a92-e29a-4f41-8d02-ea31ccaf0673
* Version Independent ID: c73e95a0-eb07-7651-5c60-518f95f40b8d
* Content: [Monitor scripts with extended events - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/administration/extended-events?view=sql-server-ver15&source=docs)
* Content Source: [docs/machine-learning/administration/extended-events.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/administration/extended-events.md)
* Product: **sql**
* Technology: **machine-learning-services**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@tgilmour Thank you for opening a GitHub issue. We will have a look at the issue and get back to you.

**Comment by cawrites** [comment]
@tgilmour thank you for taking the time to contact us regarding this documentation. We certainly appreciate it when we can get information that improves the user experience. Your observation is correct regarding the path, we will update this document and advise you when this change has posted.

**Comment by cawrites** [comment]
@tgilmour we have updated this document to reflect the correct path. https://docs.microsoft.com/en-us/sql/machine-learning/administration/extended-events. We appreciate the time you took to advise us and we encourage you to reach out again if you have questions about any new issues. Thank you.

**Comment by cawrites** [comment]
#please-close
