### ISSUE TITLE
Database Snapshot with In-Memory tables is supported in SQL 2019

### ISSUE THREAD

**Issue by felipespas-brz** [MicrosoftDocs/sql-docs#5365]
In the beginning of the article, it says "The source database must not contain a MEMORY_OPTIMIZED_DATA filegroup. For more information, see Unsupported SQL Server Features for In-Memory OLTP." but in SQL Server 2019 it is supported as we can see in this link: https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/unsupported-sql-server-features-for-in-memory-oltp?view=sql-server-ver15#recently-added-supports. 

Additionally, it is important to add in the documentation the information that the database snapshot does not work with the same copy-on-write approach for in-memory tables as it does with disk-based tables. At least in our tests it copied all in-memory data to the snapshot as soon as we created the snapshot. It is possible to check this behavior in the column name in the DMV sys.dm_os_memory_clerks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75a530e-446a-a521-c186-488cbed9b463
* Version Independent ID: 417b56a6-e21c-c7d1-8fe9-04caf78fd3a4
* Content: [Create a Database Snapshot (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/create-a-database-snapshot-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/create-a-database-snapshot-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/create-a-database-snapshot-transact-sql.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@felipespas-brz -- Felipe, thank you for thorough feedback.

@stevestein -- Steve, please look into this issue.

**Comment by stevestein** [comment]
@felipespas-brz - thanks for the feedback. 

We removed _The source database must not contain a MEMORY_OPTIMIZED_DATA filegroup._ when SQL Server 2019 is selected.

We also created an internal work item (1780952) to consider adding the additional info you requested.

Thanks!

#please-close
