### ISSUE TITLE
Error during the registration of a CLR assembly in SQL Server 2017 which references other assembly

### ISSUE THREAD

**Issue by imranshams** [MicrosoftDocs/sql-docs#5368]
Hi, can anybody helps me to solve my problem:
https://stackoverflow.com/questions/63575895/error-during-the-registration-of-a-clr-assembly-in-sql-server-2017-which-referen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a21d0936-6216-2251-6bdc-b1d7746c7039
* Version Independent ID: cd19b31a-b56d-6958-a404-a5a04db7b4bc
* Content: [Deploying CLR Database Objects - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/deploying-clr-database-objects?view=sql-server-2017)
* Content Source: [docs/relational-databases/clr-integration/deploying-clr-database-objects.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/clr-integration/deploying-clr-database-objects.md)
* Product: **sql**
* Technology: **clr**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@imranshams -- Imran, thank you for your question, and for your answer in that thread.

cc @rothja for awareness
