### ISSUE TITLE
MIN_ACTIVE_ROWVERSION syntax wrong?

### ISSUE THREAD

**Issue by siggemannen** [MicrosoftDocs/sql-docs#5370]
Hi!
On this page: https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/min-active-rowversion-transact-sql.md
the syntax for MIN_ACTIVE_ROWVERSION is specified as:
`MIN_ACTIVE_ROWVERSION`

but shouldn't it be `MIN_ACTIVE_ROWVERSION()`?

I haven't been able to call this function without the brackets, and the bracket syntax is mentioned lower down.

Is it perhaps possible in some versions but not others?

**Comment by WilliamAntonRohm** [comment]
@siggemannen -- thank you for catching this.  I am updating this article.
