### ISSUE TITLE
Missing (minor) instruction in 'Using SQL Server Management Studio'

### ISSUE THREAD

**Issue by mcalexster** [MicrosoftDocs/sql-docs#5371]
[Enter feedback here]
On page:  https://docs.microsoft.com/en-us/sql/relational-databases/tables/create-unique-constraints?view=sql-server-ver15.

No instruction is given to close the Indexes/Keys dialog.  I suggest changing Point 4 from:

In the grid under General, click Type and choose Unique Key from the drop-down list box to the right of the property.

to;

In the grid under General, click Type and choose Unique Key from the drop-down list box to the right of the property and then click Close. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79da4db5-9188-132b-b6eb-4010171a34fd
* Version Independent ID: 2ff26525-5bfd-00c8-942a-809b866a4bdb
* Content: [Create Unique Constraints - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/create-unique-constraints?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/create-unique-constraints.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/create-unique-constraints.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@mcalexster -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
