### ISSUE TITLE
sqlpackage Installation - macOS Catalina

### ISSUE THREAD

**Issue by tonyawad88** [MicrosoftDocs/sql-docs#5378]
I ran into an issue when trying to install sqlpackage on macOS Catalina (10.15.6). It's mainly due to the permissions issue added by Apple to Catalina.

To bypass it for now we should add a note to the macOS installation to use something like: 
`sudo spctl --master-disable`

Execute `sqlpackage` then re-enable it:
`sudo spctl --master-enable`

Or at least add a note that on macOS Catalina there's a permission issue that users will run into.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3df6af-9ac8-bc57-93dc-29ff713c1d3b
* Version Independent ID: 7624e2cc-7aa9-40dd-4015-3371ea2ea0a2
* Content: [Download and install sqlpackage - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-ver15)
* Content Source: [docs/tools/sqlpackage-download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage-download.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by WilliamAntonRohm** [comment]
@tonyawad88 -- Tony, thank you for your feedback and proposed solution.

@pensivebrian -- Brian, please look into this issue.

**Comment by joyOf** [comment]
Hello! Not sure if it's the best place to ask but frankly I am lost ...

I experience troubles during the installation of sqlpackage on macos Catalina.
Following the instructions from docs

$ mkdir sqlpackage
$ unzip ~/Downloads/sqlpackage-osx-<version string>.zip -d ~/sqlpackage 
$ echo 'export PATH="$PATH:~/sqlpackage"' >> ~/.bash_profile
$ source ~/.bash_profile
$ sqlpackage

`sqlpackage` command was returning Permission Denied and after I ran the suggested command `sudo spctl --master-disable` it returns `sqlpackage: command not found`.

I have checked the .bash_profile and it does indeed contain the path to the tool, so this part is ok.

Another weird thing is that the application to open sqlpackage by default is TextEdit which is clearly wrong. When trying to open it via Terminal nothing happens at all. 

I do not understand what is the format of the file and if I can't execute it neither from the terminal not from the Finder, I am not sure what to do next. 

Thanks!

**Comment by dzsquared** [comment]
@WilliamAntonRohm I will submit a PR to take care of this issue.  thank you!

**Comment by dzsquared** [comment]
@WilliamAntonRohm this is now covered

**Comment by WilliamAntonRohm** [comment]
@dzsquared -- thank you!
