### ISSUE TITLE
Missing bracket in SQL example

### ISSUE THREAD

**Issue by rjk** [MicrosoftDocs/sql-docs#5380]
You're missing closing brackets (and perhaps more?) in this example code: 

```
UPDATE SalesOrder  
SET Details =  
     (SELECT TOP 1 UnitPrice, OrderQty  
       FROM Sales.SalesOrderDetail D  
       WHERE D.SalesOrderId = SalesOrder.SalesOrderId  
      FOR JSON AUTO 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6780fe4-5238-8607-8343-b8affadff8e2
* Version Independent ID: aa89f52b-328d-38b9-7b23-7f7de8ac8b25
* Content: [Use FOR JSON output in SQL Server and in client apps - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/use-for-json-output-in-sql-server-and-in-client-apps-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/json/use-for-json-output-in-sql-server-and-in-client-apps-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/use-for-json-output-in-sql-server-and-in-client-apps-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@rjk -- Rory, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@jovanpop-msft -- Jovan, please review [private PR 16852](https://github.com/MicrosoftDocs/sql-docs-pr/pull/16852).
