### ISSUE TITLE
Subquery converted to a join

### ISSUE THREAD

**Issue by victren** [MicrosoftDocs/sql-docs#5387]
[Enter feedback here]
USE AdventureWorks2016;
GO
SELECT Name
FROM Production.Product
WHERE ProductSubcategoryID NOT IN
    (SELECT ProductSubcategoryID
     FROM Production.ProductSubcategory
     WHERE Name = 'Mountain Bikes' 
        OR Name = 'Road Bikes'
        OR Name = 'Touring Bikes');
GO

can be converted like:

select l.Name 
from Production.Product as l join Production.ProductSubcategory as r 
on l.ProductSubcategoryID = r.ProductSubcategoryID 
where not(r.Name = 'Mountain Bikes' 
        OR r.Name = 'Road Bikes'
        OR r.Name = 'Touring Bikes')

the result is same!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b727c932-4a39-5272-80cd-1a5e2b5aca8b
* Version Independent ID: c31a79c4-06d5-749c-1a6d-69e53c929789
* Content: [Subqueries (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/subqueries?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/subqueries.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/subqueries.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by victren** [comment]
the not in subquery finds the ProductSubcategoryID of the product and then search it in the (Name = 'Mountain Bikes' OR Name = 'Road Bikes' OR Name = 'Touring Bikes') ProductSubcategoryID group, 

the join query find the ProductSubcategoryID of the product, and then verify if this ProductSubcategoryID satisfy the conditions of not (Name = 'Mountain Bikes' OR Name = 'Road Bikes' OR Name = 'Touring Bikes'), if it's true, then it can't belong to the group of (Name = 'Mountain Bikes' OR Name = 'Road Bikes' OR Name = 'Touring Bikes') ProductSubcategoryID group, 

so the meaning is equal

**Comment by victren** [comment]
it has a fixed relationship between product and productsubcategory, that means every product should belong to one and only one subcategory

**Comment by WilliamAntonRohm** [comment]
@victren -- Victor, thank you for your thorough feedback.  Please consider adding this suggestion here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @julieMSFT for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
