### ISSUE TITLE
Verification step incorrect

### ISSUE THREAD

**Issue by MHacker9404** [MicrosoftDocs/sql-docs#5388]
[Enter feedback here]

According to this document: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/external-scripts-enabled-server-configuration-option?view=sql-server-ver15
...
the verification step is wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10a1a190-9335-9d2d-c664-9b91c9be8cf0
* Version Independent ID: c9e23f38-b817-bf96-453a-3c7171501dd3
* Content: [Install on Windows - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/install/sql-machine-learning-services-windows-install?view=sql-server-ver15#restart-the-service)
* Content Source: [docs/machine-learning/install/sql-machine-learning-services-windows-install.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/install/sql-machine-learning-services-windows-install.md)
* Product: **sql**
* Technology: **machine-learning-services**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by cawrites** [comment]
@MHacker9404 can you expand more specifically what you are referring to?

**Comment by MHacker9404** [comment]
Sure:
The verification step says to run the SQL code 
`EXECUTE sp_configure  'external scripts enabled'`
and this will set the run_value to 1.

This is incorrect according to the referenced document.  The SQL code should be:
`sp_configure 'external scripts enabled', 1;
RECONFIGURE WITH OVERRIDE;`

**Comment by cawrites** [comment]
![image](https://user-images.githubusercontent.com/54048339/91775292-8f04b800-eb9f-11ea-8dbe-1e0a84635077.png)

**Comment by cawrites** [comment]
@MHacker9404  the results shown in the image verify the setting is correct. Is this comment based on inconsistent documentation or an error you encountered?

**Comment by cawrites** [comment]
@MHacker9404 I am just following up with you regarding the question you presented. We were able to validate the results and provide the results.

**Comment by cawrites** [comment]
![image](https://user-images.githubusercontent.com/54048339/92683647-490acb00-f2e8-11ea-863d-d69e33a25d5b.png)

**Comment by cawrites** [comment]
@MHacker9404 we have provided results for both commands. There doesn't appear to be an error in obtaining the correct results.
Since we have not heard back from you we will be closing this issue. Please don't hesitate to contact Microsoft again if you have a question regarding our content.

**Comment by cawrites** [comment]
#please-close
