### ISSUE TITLE
Standard_L8s does not support 32 disks, only 16 

### ISSUE THREAD

**Issue by jpineda123** [MicrosoftDocs/sql-docs#5391]
In the importance ection of this page, you say that Standard_L8s supports 32 disks, but if you go to https://docs.microsoft.com/en-us/azure/virtual-machines/lsv2-series?toc=/azure/virtual-machines/linux/toc.json&bc=/azure/virtual-machines/linux/breadcrumb/toc.json , you can check that L8s only supports 16 disks.

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc88b7b8-d8ae-8b11-b988-4ad4bf702863
* Version Independent ID: 355e9bf2-4da3-70e1-d0a1-8a038ebdbc8e
* Content: [Deploy with a python script - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/quickstart-big-data-cluster-deploy?view=sqlallproducts-allversions)
* Content Source: [docs/big-data-cluster/quickstart-big-data-cluster-deploy.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/quickstart-big-data-cluster-deploy.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
Submitting fix. Thanks for the note.
