### ISSUE TITLE
ODBC Test Program

### ISSUE THREAD

**Issue by sfc-gh-space** [MicrosoftDocs/sql-docs#5392]
[Enter feedback here]

This page implies you can download an ODBC Test program. It even names them. However, the programs aren't clickable and it isn't clear how to download them. Page should be more explicit about where to get the ODBC Test program. Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5343285-846d-c7c8-d035-84b48dd2e4af
* Version Independent ID: 70a44fef-7a92-8bce-8c46-20b5567f6308
* Content: [ODBC Test - SQL Server](https://docs.microsoft.com/en-us/sql/odbc/odbc-test?view=sql-server-ver15)
* Content Source: [docs/odbc/odbc-test.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/odbc-test.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@sfc-gh-space Thanks for the feedback. ODBC Test is part of the Microsoft Data Access Components (MDAC) 2.8 Software Development Kit, which can be downloaded from here: https://www.microsoft.com/download/details.aspx?id=21995

I'll work on updating the documentation.

Thanks,
David

**Comment by David-Engel** [comment]
#assign:David-Engel

**Comment by David-Engel** [comment]
@sfc-gh-space The documentation has been updated.

Thanks,
David

#please-close
