### ISSUE TITLE
Code sample is referring to the older ODBC Driver

### ISSUE THREAD

**Issue by cawrites** [MicrosoftDocs/sql-docs#5393]
Driver={ODBC Driver 13 for SQL Server};Server=ServerNameHere;Encrypt=YES;TrustServerCertificate=YES  

Other examples use ODBC Driver 17, but the example shown above refers to Driver 13.  Driver version should be consistent throughout the entire article. 

# [DSN name]
[MSSQLTest]  
Driver = ODBC Driver 17 for SQL Server  
# Server = [protocol:]server[,port]  
Server = tcp:localhost,1433
#
# Note:  
# Port is not a valid keyword in the odbc.ini file  
# for the Microsoft ODBC driver on Linux or macOS
#  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cfdda44-e9f6-d18a-6fbb-311b12847f4e
* Version Independent ID: 4755f473-a601-79d8-1de9-15e7bc18c51e
* Content: [Connecting using ODBC - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@cawrites Thanks for the feedback. I'll update the reference.

Regards,
David

**Comment by David-Engel** [comment]
#assign:David-Engel

**Comment by David-Engel** [comment]
@cawrites The documentation has been updated.

Thanks,
David

#please-close
