### ISSUE TITLE
Missing info in "Column Statistics and Joins" section

### ISSUE THREAD

**Issue by sidesw1pe** [MicrosoftDocs/sql-docs#5394]
Within this section there is a comparison between two query plans; the same query before and after deleting rows from the Customer table. The article states "The following is the plan for the query:", but does not show the plan. Instead there is a SQL code snippet. The article goes on to show the "after" plan and briefly discusses the differences. 

It seems to me that the "before" plan should be added to the article, replacing the SQL code snippet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e49268-9863-3be2-218c-c472fe6f3711
* Version Independent ID: b104aa79-5b21-cd77-f24e-71a9fd93cf36
* Content: [Query processing for memory-optimized tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/a-guide-to-query-processing-for-memory-optimized-tables?view=sql-server-ver15#natively-compiled-stored-procedures)
* Content Source: [docs/relational-databases/in-memory-oltp/a-guide-to-query-processing-for-memory-optimized-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/a-guide-to-query-processing-for-memory-optimized-tables.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
@rothja I cannot process this Issue #5394 .  Reassigning to RothJa, for the SQL Content team to consider.  Thanks.

**Comment by rothja** [comment]
@sidesw1pe Thank you for this observation/suggestion. I'll take a look at the article and see if we can make it more clear. Thank you!

**Comment by rothja** [comment]
@sidesw1pe After looking closer, I think the wording is very confusing. It is saying that for the query shown, the following is the plan generated after the deletion. I will reword this in a pull request to make this more clear. It took me a while looking at it to see that is what they meant, so thanks for pointing it out. This git issue will close after I make the fix.
