### ISSUE TITLE
Title should be fixed

### ISSUE THREAD

**Issue by lcanastreiro** [MicrosoftDocs/sql-docs#5395]
The title of this documentation page doesn't seem correct. it should be reviewed and fixed.

Thanks,
Luís.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19da7a75-ffd3-adb4-1abf-084c3dff1aeb
* Version Independent ID: 6e99fd96-00f9-abfa-ba3b-cbb424ed6cc4
* Content: [Manage job logins for databases in an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/logins-and-jobs-for-availability-group-databases?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/logins-and-jobs-for-availability-group-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/logins-and-jobs-for-availability-group-databases.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@lcanastreiro -- Luís, thank you for your feedback.  Please clarify what may be misinterpreted in the title, or the source of confusion in the article.

**Comment by lcanastreiro** [comment]
@WilliamAntonRohm the HTML title of this page is - "**Manage job logins for databases** in an availability group" but the Title on the page is "**Manage logins for jobs using databases** in an Always On availability group". But what it is covered in this page is what a SQL Admin should have in consideration to synchronize SQL Server Agent Jobs and SQL Server Logins between AG replicas. Having this in consideration I consider that the TITLE of the page (and also the HTML one) should be rephrased or changed to something more intuitive easy to understand,

**Comment by WilliamAntonRohm** [comment]
@lcanastreiro -- thank you for clarifying.

@MashaMSFT -- please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @lcanastreiro thanks for your feedback! I am seeing a number of inconsistencies with this article, along with the title :) I have created an internal backlog item ([1771657](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1771657)) to address this in a future iteration. 

I'll close out this Git Issue for now but please feel free to comment should you need anything further.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
#please-close
