### ISSUE TITLE
Automatic Failover - Database Level

### ISSUE THREAD

**Issue by githubnagaraj** [MicrosoftDocs/sql-docs#5396]
The note at the starting of the page is confusing:

_"Issues at the database level, such as a database becoming suspect due to the loss of a data file, deletion of a database, or corruption of a transaction log, do not cause an availability group to failover
"
If I enable database level health detection, when the database is not online, it trigger AG Failover , as stated here. https://docs.microsoft.com/en-us/archive/blogs/sql_server_team/sql-server-availability-groups-enhanced-database-level-failover

Is not the note directly contradicting, database level health detection options? Appreciate better clarity in the document. Thanks 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2153369a-3013-8849-d2fb-8a96cb53123b
* Version Independent ID: e6189cd8-97cf-f769-9331-43f91490e3e6
* Content: [Failover modes for availability groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/failover-and-failover-modes-always-on-availability-groups?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/failover-and-failover-modes-always-on-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/failover-and-failover-modes-always-on-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@githubnagaraj -- thank you for your feedback.

@MashaMSFT -- please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @githubnagaraj , thanks so much for bringing this to our attention! You're correct, this should be updated to include information about the database level health check. We have processed a change to reflect this and it will be live later this week.

I'm going to close out this Git Issue but please feel free to comment should you need anything further. 

Thanks again for reaching out and improving our docs!  I hope you have a wonderful rest of your day :)
Masha from the SQL Docs team
