### ISSUE TITLE
question: Are JUPYTER notebooks published in Azure Data Studio to be managed here?

### ISSUE THREAD

**Issue by mi-hol** [MicrosoftDocs/sql-docs#5405]
I wanted to correct a typo in the jupyter notebook installed by default to 'C:\Program Files\Azure Data Studio\resources\app\extensions\Microsoft.sqlservernotebook\books\sqlserver2019\content\readme.md' but couldn't find it here.
A clarification would be appreciated.

**Comment by WilliamAntonRohm** [comment]
@mi-hol -- thank you for your feedback.  Are you following a particular docs.microsoft.com article?

**Comment by mi-hol** [comment]
not sure to understand the context/background of the question.
"here' in above refers to https://github.com/MicrosoftDocs/sql-docs

**Comment by dzsquared** [comment]
Hi @mi-hol  - you should drop this question over at https://github.com/microsoft/azuredatastudio since the application you're working in is Azure Data Studio.

**Comment by mi-hol** [comment]
given the official title 'Operations and Support Jupyter Book - SQL Server 2019 Big Data Clusters' and a reference in Azure Data Studio to a Microsoft doc package in https://github.com/microsoft/azuredatastudio/blob/main/resources/xlf/en/Microsoft.sqlservernotebook.xlf maybe the JUPYTER type doc has not (yet) been migrated to this repository and still lives on some Microsoft internal server?

**Comment by WilliamAntonRohm** [comment]
@mi-hol -- please clarify the details of the typo you've found.  I may be able to update the source file for you.

**Comment by mi-hol** [comment]
typo is:
NTB600 - NTB699: Montioring
in: 
'C:\Program Files\Azure Data Studio\resources\app\extensions\Microsoft.sqlservernotebook\books\sqlserver2019\content\readme.md'

**Comment by mi-hol** [comment]
next error is in a related jupyter notebook https://github.com/microsoft/azuredatastudio/issues/12138

**Comment by mi-hol** [comment]
@WilliamAntonRohm is anything more required?

**Comment by WilliamAntonRohm** [comment]
@mi-hol -- my apologies for the delay.

@kburtram -- please look into the following:
- C:\Program Files\Azure Data Studio\resources\app\extensions\Microsoft.sqlservernotebook\books\sqlserver2019\content\readme.md
- https://github.com/microsoft/azuredatastudio/blob/main/resources/xlf/en/Microsoft.sqlservernotebook.xlf
- https://github.com/microsoft/azuredatastudio/issues/12138

cc @chlafreniere, @alanrenmsft, @dzsquared for awareness

**Comment by alanrenmsft** [comment]
@yualan I suppose you mean Alan Yu here. @WilliamAntonRohm

**Comment by mi-hol** [comment]
moved to https://github.com/microsoft/tigertoolbox/issues/226
