### ISSUE TITLE
Ready to Update!?

### ISSUE THREAD

**Issue by neillindberg** [MicrosoftDocs/sql-docs#5416]
For sometime now I am prompted with an update available message when I fire up MSSQL Server Management Studio. I would like to simply update and be done.
But, the prompt links to a download page. I'm hesitant to be slapping new code trees into a working software. Is that how this thing runs though? Is it just a process of replacing your install? 
That feels unsafe, so why not present just a simple update? I mean I could go on as to why, but mostly for peace-of-mind?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by rothja** [comment]
@neillindberg It looks like Drew answered your question from the documentation? If that is not the case, please reach out and clarify, and we'll do our best to respond. For now, I am going to close the issue. Thank you for reaching out!
