### ISSUE TITLE
Missing detail on performance optimization and troubleshooting

### ISSUE THREAD

**Issue by james----** [MicrosoftDocs/sql-docs#5418]
Can't find any documentation on what to do when this does not perform well and how to make it performant in the first place.

This article makes no mention of even using it which implies that it should not be used in production workloads, it would be good to call that out at a very minimum...
https://docs.microsoft.com/en-us/azure/azure-sql/virtual-machines/windows/performance-guidelines-best-practices

At the absolute minimum SQL Server Event 833 should be documented in the troubleshooting section 

Specifically this error from event 833... 
SQL Server has encountered 1 occurrence(s) of I/O requests taking longer than 15 seconds to complete on file [https://xxxx.blob.core.windows.net/yyyy/zzzz.mdf] in database id 10.  The OS file handle is 0x00000250B129D311.  The offset of the latest long I/O is: 0x00000f2ef6a000.  The duration of the long I/O is: 15759 ms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb6076ae-3679-3a8e-6530-5f0db78b3f06
* Version Independent ID: 335044f8-f561-6f8d-b878-f3fde1664e19
* Content: [SQL Server data files in Microsoft Azure - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/sql-server-data-files-in-microsoft-azure?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/sql-server-data-files-in-microsoft-azure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/sql-server-data-files-in-microsoft-azure.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
@MashaMSFT  - would you be available to investigate?

Thanks,
Mike

**Comment by MashaMSFT** [comment]
Hi @james---- , thanks for bringing this to our attention! We have processed a change to add this to the documentation that should be live later this week.

I'm going to close out this Git Issue for the time being but please feel free to comment should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
