### ISSUE TITLE
Master Data Services: Incorrect code generation for a business-rule processing stored procedure (for non-english versions of MDS)

### ISSUE THREAD

**Issue by BISMN** [MicrosoftDocs/sql-docs#5428]
This problem occurs in non-english of MDS versions only, I think. Russian version, in my case (14.0.1000.169)

When a business-rule condition contains a reference to a built-in attribute (Code or Name) of a parent hierarchy (such as Parent.FooHierarchy1.Code), MDS code generator creates incorrect query text.
Query in a SP references a localized attribute name and raise "SYSERR207 | Invalid column name" exception when you try to validate.

Here is a part of SP ([mdm].[udp_SYSTEM_4_9_CHILDATTRIBUTES_ProcessRules]) code:
`

         -- Rule 12 Condition Evaluation: IF Parent.FooHierarchy1.Код равно Blank
         ---------------------------------------------------------------------------------------

          SET @SQL = N'      
         UPDATE #BRConditionEvaluation SET
           IsConditionTrue = CASE WHEN ( ( md.[Parent.FooHierarchy1.Код] IS NULL OR md.[Parent.FooHierarchy1.Код] = N''~NULL~'' ) ) THEN 1 ELSE 0 END
         FROM #BRConditionEvaluation AS ce
         INNER JOIN #BRMemberData AS md ON (ce.MemberID = md.MemberID) AND ce.BusinessRuleID = 12;`

As you can see, there is a `Parent.FooHierarchy1.Код` reference instead of `Parent.FooHierarchy1.Code`

**Comment by WilliamAntonRohm** [comment]
@BISMN -- thank you for your feedback.  This repo is solely for documentation issues, and this appears to be in the product.  Please add your feedback here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
