### ISSUE TITLE
Correction Required

### ISSUE THREAD

**Issue by rohith-um** [MicrosoftDocs/sql-docs#5430]
Legacy CE: For a SQL Server database set at compatibility level 120 and above, the CE version 70 can be can be activated by using the at the database level by using the ALTER DATABASE SCOPED CONFIGURATION.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d712c8-87f2-7203-6dd9-5f23a60cdfc2
* Version Independent ID: 536de496-f292-b661-7da7-350d59ec331f
* Content: [Cardinality Estimation (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/cardinality-estimation-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/cardinality-estimation-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/cardinality-estimation-sql-server.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@rohith-um -- thank you for your feedback.  It seems like there's a missing word between "activated by using the" and "at the database level"?

@julieMSFT -- please look into this issue.

**Comment by julieMSFT** [comment]
@rohith-um Hello and thank you for contacting Microsoft. The sentence in question should read "Legacy CE: For a SQL Server database set at compatibility level 120 and above, the CE version 70 can be can be activated at the database level by using the ALTER DATABASE SCOPED CONFIGURATION. I have updated the article and it should be visible sometime next week. I will proceed with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#https://github.com/MicrosoftDocs/sql-docs-pr/pull/17081

**Comment by julieMSFT** [comment]
#please-close
