### ISSUE TITLE
Out of Date Content for Azure Synapse

### ISSUE THREAD

**Issue by shanerisk** [MicrosoftDocs/sql-docs#5431]
The article needs to be updated, it still references SQL DW and specifies that Accelerated Database Recovery is still in preview.  ADR has been GA for over a year on Azure Synapse.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 357ceaef-c63a-ddfc-f183-3f653f95dd28
* Version Independent ID: 9a7ca535-7370-d124-88b0-c3a8b1aa05b7
* Content: [Accelerated database recovery - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/accelerated-database-recovery-concepts?view=sql-server-ver15)
* Content Source: [docs/relational-databases/accelerated-database-recovery-concepts.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/accelerated-database-recovery-concepts.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@shanerisk -- thank you for your feedback.

@MashaMSFT -- please look into this article.

**Comment by julieMSFT** [comment]
#assign:julieMSFT

**Comment by MashaMSFT** [comment]
Hi @shanerisk , thanks so much for bringing this to our attention! We have processed a change that should be live later this week. 

I'm going to close out this Git Issue but please feel free to comment should you need anything further. 

Thanks again for improving our docs and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
