### ISSUE TITLE
Trace Flag 5004 can pause the TDE Scan in versions below SQL 2019

### ISSUE THREAD

**Issue by WHinDenver** [MicrosoftDocs/sql-docs#5432]
The document could reference trace flag 5004 for pausing the TDE Scan for versions below SQL 2019.

See 5004 in https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql

--Will
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20953c9f-c769-7849-420a-dac77f917d4a
* Version Independent ID: dfd9ad27-844c-c3c8-58a3-5d4a0c92fbba
* Content: [Transparent Data Encryption (TDE) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/transparent-data-encryption.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/transparent-data-encryption.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@WHinDenver -- Will, thank you for your suggestion.

@jaszymas -- Jakub, please look into this issue.

**Comment by shohamMSFT** [comment]
As advised in the TDE documentation, our recommended way to pause and resume an encryption scan is by using the Alter Database Set Encryption Suspend/Resume command. Trace flags are more suitable for debug/diagnose scenarios and 5004 should be used carefully as it has a 'global only' scope.

**Comment by shohamMSFT** [comment]
#please-close

**Comment by WHinDenver** [comment]
@shohamMSFT @PRMerger19 
Is the alter Database Set Encryption Suspend/Resume supported in older versions of SQL now?  My comment was that this is an option that should be in the documentation to support older versions of  SQL, before 2019.

--Will
