### ISSUE TITLE
User Created for Spark Ingestion Requires View Database State Permission

### ISSUE THREAD

**Issue by nielsberglund** [MicrosoftDocs/sql-docs#5434]
Hi guys!

When running the code "as is" in the article you fail on writing to the datapool with the error: `DataPools are not configured or non reachable`.

The failure point is in the `DataPoolUtils.getDataPoolNodeList` method in the SQL Server Spark connector. In that method we execute a query under the created user: `select address from sys.dm_db_data_pool_nodes`. That query requires the user to have `VIEW DATABASE STATE` permission. Since we have not granted those permissions the query will fail and no node addresses are being returned, and the method will throw the exception mentioned above.

So in step 3 "Create permissions for MSSQL-Spark Connector." following statement should be added:

`GRANT VIEW DATABASE STATE ON DATABASE::Sales TO sample_user;`

Thanks!

Niels

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c639fd7-43ee-f24d-ce5e-530077367aab
* Version Independent ID: 28059c60-abe8-e4f8-08c5-221c926f007e
* Content: [Ingest data with Spark jobs - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-spark?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/tutorial-data-pool-ingest-spark.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/tutorial-data-pool-ingest-spark.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @rajmera3
* Microsoft Alias: **raajmera**

**Comment by WilliamAntonRohm** [comment]
@nielsberglund -- Niels, thank you for your feedback and suggested solution.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@rajmera3 -- Rahul, please review [private PR 16980](https://github.com/MicrosoftDocs/sql-docs-pr/pull/16980).

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
