### ISSUE TITLE
Keyboard shortcut for browser help about a keyword

### ISSUE THREAD

**Issue by camillagaardsted** [MicrosoftDocs/sql-docs#5436]
I really miss a keyboard shortcut like F1 in SSMS, where you can lookup the online help article for a keyword e.g. I press F1 when my cursor is standing on SELECT and then the online article on https://docs.microsoft.com/ about select is opened in my browser. For PowerShell ctrl-F1 also does this for Visual Studio Code, so I suggest to add the same logic for Azure Data Studio.

Regards 

Camilla

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe030aa-7a71-2d02-c26f-103cfe4687a8
* Version Independent ID: 4781bc1f-47db-5eb3-066d-0177014fd7c7
* Content: [Create and customize keyboard shortcuts - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/keyboard-shortcuts?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/keyboard-shortcuts.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@camillagaardsted -- thank you for your feedback.  For product suggestions, please use this link:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
