### ISSUE TITLE
sqlsrv downloads for older PHP versions?

### ISSUE THREAD

**Issue by FireSBurnsmuP** [MicrosoftDocs/sql-docs#5441]
I don't see any way to get at dlls targeting older versions of PHP - while they may not be officially supported anymore, there are those of us unfortunate enough to need to use them still.

Seems to me that it would be better to provide a reference to other PHP versions here than force users to use shady peer-to-peer download sites to get at the older versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0042b2-85e3-2e09-8f7e-16f7f1b70be7
* Version Independent ID: 7c56b699-4f86-11e3-b3c9-51af04511c8d
* Content: [System Requirements for the Microsoft Drivers for PHP - SQL Server](https://docs.microsoft.com/en-us/sql/connect/php/system-requirements-for-the-php-sql-driver?view=sql-server-ver15)
* Content Source: [docs/connect/php/system-requirements-for-the-php-sql-driver.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/system-requirements-for-the-php-sql-driver.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@FireSBurnsmuP Thanks for submitting feedback. Previous release downloads are available on the [Release notes](https://docs.microsoft.com/sql/connect/php/release-notes-php-sql-driver#previous-releases) page for the Drivers for PHP. Downloads are available for releases that support back to PHP 5.4.

Regards,
David

**Comment by WilliamAntonRohm** [comment]
@David-Engel -- David, thank you for your answer.

@FireSBurnsmuP -- I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
