### ISSUE TITLE
Not a table Duplicate

### ISSUE THREAD

**Issue by Juncus** [MicrosoftDocs/sql-docs#5444]
This a structure duplication NOT a table duplication

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4a6423-c509-5cc1-30f9-1fb55fe26833
* Version Independent ID: af8a0bd9-a993-8458-aebf-3ecc1462b228
* Content: [Duplicate Tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/duplicate-tables?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/duplicate-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/duplicate-tables.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@Juncus -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please review [private PR 17030](https://github.com/MicrosoftDocs/sql-docs-pr/pull/17030).

**Comment by MikeRayMSFT** [comment]
@Juncus - The note in the article says that the operation only duplicates the structure. Updated the article to revert to the previous syntax.
