### ISSUE TITLE
All Supported Versions mistake in Accelerated Database Recovery

### ISSUE THREAD

**Issue by EitanBlumin** [MicrosoftDocs/sql-docs#5447]
The ADR feature is new since **SQL Server 2019**, and yet the documentation says "SQL Server (**all** supported versions)".

This is a misleading mistake because it would imply that ADR is also available in SQL Server 2012, for example.

Please fix.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d6d147-a7a7-cd75-13fb-4f4f72a16a15
* Version Independent ID: bb4f71b0-3103-06af-0560-e28860c752bc
* Content: [Manage accelerated database recovery - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/accelerated-database-recovery-management?view=sql-server-ver15)
* Content Source: [docs/relational-databases/accelerated-database-recovery-management.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/accelerated-database-recovery-management.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @EitanBlumin , thanks for bringing this to our attention! I have processed a change to update this typo and it should be live later this week.

I'm going to close out this Git Issue but please feel free to comment should you need anything further. 

Thanks again for improving our documentation and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team

**Comment by EitanBlumin** [comment]
Thank you, Masha.

On the same topic, would it be possible to clarify please whether ADR is supported on SQL managed instances?

We tried to activate it yesterday and got an error saying the syntax is not supported or something like that.

**Comment by MashaMSFT** [comment]
Hi @EitanBlumin , thanks for reaching out once more! ADR is enabled by default on SQL Managed Instance and cannot be disabled - thus the commands will fail :) 

Thanks!
Masha from the SQL Docs team

**Comment by EitanBlumin** [comment]
I see, thanks!

(is that mentioned anywhere in the documentation? if not, it probably should)

**Comment by MashaMSFT** [comment]
Hi @EitanBlumin , thanks for the suggestion! I added it to the following doc: https://docs.microsoft.com/en-us/azure/azure-sql/accelerated-database-recovery

The change should be live later this week :) 

Thanks again for helping improve our documentation! 
Masha from the SQL Docs team
