### ISSUE TITLE
RLS Example with Synapse

### ISSUE THREAD

**Issue by arashaga** [MicrosoftDocs/sql-docs#5451]
The Synapse example apparently pointing to a blob storage but it shows the data is entered in the SQL table. We need clarity here is the external table pointing to SQL server or another Synapse Table that way? or the part that the data need to be inserted into blob as a delimited file is missing in the doc?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c96c3ee-5443-004f-d189-3701f8bef6c9
* Version Independent ID: efcc952b-eadb-4579-54c7-00da3bc107ae
* Content: [Row-Level Security - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/row-level-security?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/row-level-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/row-level-security.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
@julieMSFT - Hey Julie, can you please take a look? Thanks!
#reassign:julieMSFT

**Comment by julieMSFT** [comment]
@arashaga  Hello and thank you for contacting Microsoft. In the example we create a SQL table and then use that table to populate an external table using a CREATE EXTERNAL TABLE AS SELECT. The external table is pointing to the table you created with this statement. We do this to create an external table that is then used to show how row level security works. Does this help with your question?

**Comment by julieMSFT** [comment]
@arashaga Hello, I updated the document to clarify the information in the article. I will go ahead and close this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
