### ISSUE TITLE
SQL Server 2008 can be removed

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/sql-docs#5460]
The first table on this page "the last **four** versions" has 5 entries. By now, SQL Server 2008 can be removed if you ask me, it is not generally supported anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b3831a3-6c86-243c-4b07-8960e4d06d7b
* Version Independent ID: dfd7599d-88eb-99f2-c227-0c9dc82bfd87
* Content: [Configure Windows Service Accounts and Permissions - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@andrePKI -- thank you for your suggestion.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review [private PR 17080](https://github.com/MicrosoftDocs/sql-docs-pr/pull/17080).
