### ISSUE TITLE
Incomplete specification

### ISSUE THREAD

**Issue by WillBrownsberger** [MicrosoftDocs/sql-docs#5470]
The page states that  _Note: You can configure the location of the log file in the php.ini file._

Hello?  What is the appropriate setting.  There is a setting for the location of the general php error log:  `error_log = `d:/logs/php_errors.log` but that is not where sqlsrv messages are going.
`
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e72ebf96-f590-a265-9bd2-80aa88224a53
* Version Independent ID: 9023d7f2-7ee7-fa54-933f-4c86adfa74f3
* Content: [Logging activity - SQL Server](https://docs.microsoft.com/en-us/sql/connect/php/logging-activity?view=sql-server-ver15)
* Content Source: [docs/connect/php/logging-activity.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/logging-activity.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@WillBrownsberger -- Will, thank you for your question.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
@WillBrownsberger Logging in this context is done via the PHP logging infrastructure. It looks like that could be better explained at the beginning of the page and perhaps we should include a link to the PHP documentation for other PHP log settings. I'll look into that.

In the meantime, I believe you will want to consult the PHP documentation: https://www.php.net/manual/en/errorfunc.configuration.php#ini.error-log

For further technical questions, I recommend filing issues in the msphpsql GitHub repo: https://github.com/microsoft/msphpsql/issues
They will be better able to answer your questions there.

Thanks,
David

**Comment by David-Engel** [comment]
I've adjusted the documentation to reflect that the page is only describing the driver-specific settings related to logging to the PHP system log and added a link to the PHP documentation on how to further configure the PHP log.

#please-close
