### ISSUE TITLE
parse error in example

### ISSUE THREAD

**Issue by qt3m45su0najc7** [MicrosoftDocs/sql-docs#5472]
in the example, 
bcp TestDatabase.dbo.myRemap format nul -c -f D:\BCP\myRemap.fmt -t, -T

an error is generated when I use this format (replacing testdatabase.db.myremap with my database name and tablename).
No error when the comman is removed after the -t parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b3384ba-bb57-c651-d1e7-ebcb608c3170
* Version Independent ID: 7e8b85c3-70b6-8f55-8090-78021387d324
* Content: [Map table columns to data-file fields with a format file - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/use-a-format-file-to-map-table-columns-to-data-file-fields-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/import-export/use-a-format-file-to-map-table-columns-to-data-file-fields-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/use-a-format-file-to-map-table-columns-to-data-file-fields-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@qt3m45su0najc7 -- thank you for bringing this to our attention.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- Masha, [this page](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver15#g-copying-data-from-a-query-to-a-data-file) indicates that the -t switch by itself is for comma-separated files, and the [example mentioned above](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/use-a-format-file-to-map-table-columns-to-data-file-fields-sql-server?view=sql-server-ver15#creating-a-non-xml-format-file) follows a paragraph stating "`t,` is used to specify a comma as a field terminator".  Please help clarify.

**Comment by MashaMSFT** [comment]
Hi @qt3m45su0najc7 , thanks for reaching out! The example is correct so it's likely the error is coming from something else. Unfortunately, we are unable to provide support through this medium. Please either reach out to the community, or engage Microsoft directly. The following can help: https://docs.microsoft.com/sql/sql-server/sql-server-get-help

I hope that helps and please let us know if we can be of further assistance. I'll close out this Git Issue for the time being but please comment should you nee anything.

Thanks again and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
