### ISSUE TITLE
Managed Instance does not support log shipping but is included in Applies To section

### ISSUE THREAD

**Issue by fvarga01** [MicrosoftDocs/sql-docs#5473]
Managed Instance does not support log shipping. Including Managed Instances in the applies to section causes confusion about the supported state. Please see features article which clarifies this further: •	https://docs.microsoft.com/en-us/azure/azure-sql/database/features-comparison.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53787e1c-f7fd-82a7-8c74-f33b7026d8ef
* Version Independent ID: d06f9fb9-cd1e-fa75-7dc7-8677042877dc
* Content: [About Log Shipping (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/log-shipping/about-log-shipping-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/log-shipping/about-log-shipping-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/log-shipping/about-log-shipping-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@fvarga01 -- Fany, thank you for your feedback.

@MashaMSFT -- Masha, please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @fvarga01 , thanks so much for bringing this to our attention! So, you can configure a SQL Managed Instance as a log shipping target when used with [Azure Database Migration Service](https://docs.microsoft.com/azure/dms/) but that is not the same implementation as discussed in this article. As such, I have processed a change to update the applies to and it should be live next week.

Thanks again for improving our docs! I will close out this Git Issue for the time being but please feel free to comment to should you need anything further.

Hope you have a wonderful rest of your day!
Masha from the SQL Docs team
