### ISSUE TITLE
Expired Digital Signature Certificate

### ISSUE THREAD

**Issue by rherling79** [MicrosoftDocs/sql-docs#5479]
The digitial  signature certificate has expired for both new downloads and needs to be updated.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da1f57b-a8fd-cca7-4cf0-9d594d365062
* Version Independent ID: 60c46780-6a03-7958-c77a-e7c94e3b9e85
* Content: [sqlcmd Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15)
* Content Source: [docs/tools/sqlcmd-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlcmd-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@rherling79 -- thank you for bringing this to our attention.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
@rherling79 

Can I request what message you are receiving when using a digital signature certificate?

**Comment by rherling79** [comment]
Mark,

It wasn't a message.  I was just making a note that the certificate
associated with the file's digital signature is expired as seen in the
image below.  Due to regulatory constraints I have to record this
information and cert validity to verify file integrity prior to
installation.  So as of right now I cannot upgrade to this latest version
until the cert valid dates are updated.

[image: image.png]

Thank you,
Richard Herling

**Comment by markingmyname** [comment]
@rherling79 

I am working with @Matteo-T and the team to help understand what is happening here.

Thank you for bringing this to our attention.

We are actively discussing this.

Thank you.

**Comment by Matteo-T** [comment]
So, here's the deal (straight from the "signing team", so quite an authoritative answer:

1. What matters is the countersignature timestamp (‎Tuesday, ‎September ‎24, ‎2019 11:35:00 PM).
2. The certificate validity was  5/2/2019 thru 5/2/2020.
3. Since the countersignature **is** within the range of validity of the certificate, there is nothing to worry about: the binary is legitimate and to be trusted.

@rherling79 - I believe you need to adjust your logic to validate that something is valid or not - that's all.

Thanks,
-Matteo

**Comment by rherling79** [comment]
Thanks for the clarification.  Can you verify, is it the signature
timestamp or the countersignature timestamp that has to fall in the cert
range?  They look to be the same time from what I see, but I just wanted to
clarify since it looks like the countersignature has its own certificate
which is current.

Examples below.

The cert for the signature here.
[image: image.png]

Vs the cert for the countersignature here.
[image: image.png]

Thanks,
Richard Herling

**Comment by Matteo-T** [comment]
I cannot see the pictures, but I definitely confimr: it's the countersignature (so I was told).

**Comment by rherling79** [comment]
The method you stated makes sense.  I guess I was thrown off expecting the dates to be current for the digital signatures since the file is a new release.  I appreciate all the information.  I will adjust our logic accordingly.
