### ISSUE TITLE
Docker Image missing 2019-CU7-ubuntu-16.04 missing from mssql/bdc Repo

### ISSUE THREAD

**Issue by ms4446** [MicrosoftDocs/sql-docs#5480]
[Enter feedback here]

I been trying to deploy to SQL2019 - BDC via ADS to AKS without success. Upon further troubleshooting I noticed I was getting a  "ImagePullBackOff" error when I executed a 

`kubectl get pods --all-namespaces` 

`...`
`...`
`mssql-cluster   control-hqwdg                                0/3     ImagePullBackOff   0          25m`
`mssql-cluster   controldb-0                                  0/2     ImagePullBackOff   0          25m `

Next

`kubectl get pods -n mssql-cluster`

`NAME            READY   STATUS             RESTARTS   AGE`
`control-hqwdg   0/3     ImagePullBackOff   0          20m`
`controldb-0     0/2     ImagePullBackOff   0          20m `

Then 

`kubectl describe pod control-hqwdg`
`**Error from server (NotFound): pods "control-hqwdg" not found**`

In ADS when trying to deploy a BDC, I noticed under the Docker Settings ADS was referencing 
**2019-CU7-ubuntu-16.04** 

When I checked the Repo - http://ne2b.com/repo/mssql/bdc/mssql-server. This image seems to be missing.

When I changed the Docker Settings to point to 2019-CU6-ubuntu-16.04 I was able to build the BDC with success.

 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6f46cd1-caaa-99ac-1098-f15552369f22
* Version Independent ID: 34ec4839-afba-f57e-1a6d-bc453e70b9ce
* Content: [Configure deployments - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-custom-configuration?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/deployment-custom-configuration.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deployment-custom-configuration.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
@ms4446 - thank you for your feedback. The product issue has been fixed.
