### ISSUE TITLE
wrong url for drivers

### ISSUE THREAD

**Issue by JanosBerke** [MicrosoftDocs/sql-docs#5483]
Microsoft JDBC Driver 4.0+ for SQL Server link points to the Microsoft OLE DB Driver for SQL Server url and vice versa. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93dc3f31-08df-0ca2-2793-e8abe4de193a
* Version Independent ID: cebd12d7-aedc-f24f-79d3-c2361aa535ec
* Content: [Driver and client connectivity support for availability groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/always-on-client-connectivity-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/always-on-client-connectivity-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/always-on-client-connectivity-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@JanosBerke -- thank you for bringing this to our attention.  I am looking into the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
