### ISSUE TITLE
Needs more info on restarting services (Active or Passive node first?)

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#5485]
This needs info on whether Active or Passive node should be set and service restarted first.  You should also link to a document for Always On Availability Groups and which side to restart first.

E.g. do you change the account/password on the active node and then on the passive nodes?  For AG, on the Primary and then on the secondaries?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4442255-a76d-cfd7-c7a4-960c2a8feb42
* Version Independent ID: df030418-8e7d-931c-63fa-2276ef281148
* Content: [Failover Cluster Instance administration & maintenance - SQL Server Always On](https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/windows/failover-cluster-instance-administration-and-maintenance?view=sql-server-ver15)
* Content Source: [docs/sql-server/failover-clusters/windows/failover-cluster-instance-administration-and-maintenance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/failover-clusters/windows/failover-cluster-instance-administration-and-maintenance.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@PrometheusRising1 -- thank you for your suggestions.

@MashaMSFT -- please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @PrometheusRising1 , thanks for reaching out! This article is focusing on failover cluster instances, and is not applicable to  availability groups. 

For an Always On availability group, add connect permissions for the database mirroring endpoint on both instances participating in the availability group for the new service account, then change the service account for the secondary instance, fail the availability group over to it, and then change the service account for the new secondary instance. You can then failback if you want to, and also remove connect permissions from the old service account if you so choose. 

For a failover cluster instance, both nodes must be online, but you can only make this change on the Active node, which is the node hosting the SQL Server service. When the instance fails over, it will failover to the passive node with the new account information.

I have created an internal work item ([1766504](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1766504)) to add this to the documentation.

Thanks again for bringing this to our attention! I'm going to close out this Git Issue for the time being but please feel free to comment should you need anything further. 

Hope you have a wonderful rest of your day! 
Masha from the SQL Docs team
