### ISSUE TITLE
Provide documentation for using Azure Keyvault with SQLPackage.exe

### ISSUE THREAD

**Issue by merca** [MicrosoftDocs/sql-docs#5495]
The Publish action in SQLPackage.exe takes parameters for Azure key-vault `/AzureKeyVaultAuthMethod:` together with `clientid` and `secret`, but for love of me I cannot find any documentation for usage for those parameters. Does it mean I can inject key-vault secrets in scripts? Does it mean I can fetch admin password from the key-vault? Or is it only for _Always encrypted_ ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage.exe - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by markingmyname** [comment]
#re-assign @dzsquared

**Comment by dzsquared** [comment]
@merca You are correct, the Azure Key Vault parameters are in relation to support for encrypted columns/tables.  It does not support accessing the key vault to access passwords.
I'm getting the docs updated to include this information, but in case you'd like a peak at the namespace behind the parameters - here's the .NET API information for Dac.KeyVault: https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.keyvault?view=sql-dacfx-150

**Comment by merca** [comment]
> @merca You are correct, the Azure Key Vault parameters are in relation to support for encrypted columns/tables. It does not support accessing the key vault to access passwords.
> I'm getting the docs updated to include this information, but in case you'd like a peak at the namespace behind the parameters - here's the .NET API information for Dac.KeyVault: https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.keyvault?view=sql-dacfx-150

@dzsquared, thank you for information and the API docomentation. This answers my question (although hoped for different one 😉)

**Comment by dzsquared** [comment]
Glad to be helpful, even if not quite the functionality we were hoping for!

#please-close
