### ISSUE TITLE
Reference URL's for OPEN and BACKUP Service Master Key point to Database Master Key

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#5500]
The instructions state to copy and validate after backing up the Service Master Key (smk).  However the URL's provided only mention the Database Master Key (dmk).  Shouldn't they reference the smk instead of the dmk in the links provided?  

Or do the URL's being pointed to need to be updated to reflect that these commands (OPEN MASTER KEY and BACKUP MASTER KEY) refer to ***BOTH*** the smk's and dmk's?

[https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/back-up-the-service-master-key?view=sql-server-ver15](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/back-up-the-service-master-key?view=sql-server-ver15) 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0528f177-7fc8-2d7b-ba55-803bc0edc741
* Version Independent ID: 4d1c3d66-6715-ce15-0a08-12f7f06ae640
* Content: [Back Up the Service Master Key - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/back-up-the-service-master-key?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/back-up-the-service-master-key.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/back-up-the-service-master-key.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@LindaLF -- thank you for your feedback.

@jaszymas -- please look into this issue.

**Comment by VanMSFT** [comment]
Hey @LindaLF - Sorry for the delay! You're right, the next steps should list [Restore the Service Master Key](https://docs.microsoft.com/sql/relational-databases/security/encryption/restore-the-service-master-key) instead. I'll update the documentation. Thanks!

**Comment by VanMSFT** [comment]
#reassign:VanMSFT

FYI - @Rupp29
