### ISSUE TITLE
what about current versions of Ubuntu?

### ISSUE THREAD

**Issue by danstoner** [MicrosoftDocs/sql-docs#5501]
Ubuntu LTS is now 20.04.

It is not clear if that version is unsupported or this doc is just out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
@danstoner - Hi Dan, Ubuntu 20.04 is not a supported platform at the moment. We only list supported features in our docs, so if it's missing, we don't support it. You can find the supported platforms for SQL Server here: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019?view=sql-server-ver15
