### ISSUE TITLE
Testing a Backup of a Service Master Key

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#5510]
Why is there no test available to validate the backup of a SQL Service Master Key [smk]?  I should not have to try to restore the smk to simply be able to validate a backup.  **Is there no alternative?**

This is the only page that is close to the 'validation' mention on the page that explains what a smk is.

https://docs.microsoft.com/en-us/sql/t-sql/statements/restore-service-master-key-transact-sql?view=sql-server-ver15 

Regards,
Linda A. Lorentz Fletcher

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01677f63-3702-abfc-d5a1-8c4054d0d046
* Version Independent ID: baf30705-14cd-02b8-bcb4-3e6ab1787467
* Content: [Restore the Service Master Key - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/restore-the-service-master-key?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/restore-the-service-master-key.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/restore-the-service-master-key.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@LindaLF -- Linda, thank you for your feedback.

@jaszymas -- please look into this issue.

cc @VanMSFT for awareness

**Comment by VanMSFT** [comment]
Hi @LindaLF - If you backup the master key to a file, you should be able to see that the file exist. https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/back-up-the-service-master-key

**Comment by WilliamAntonRohm** [comment]
@vanmsft -- Van, thank you for your answer.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
