### ISSUE TITLE
Do this per database?

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#5517]
Is there a way to limit connections per database rather than per instance?  If so, can you put a reference link in the article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b79d489-e394-90af-ccc3-607ff2a691cb
* Version Independent ID: eb65450f-fe5e-1bbc-72ab-3d7cdd557a2e
* Content: [Configure the user connections Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-user-connections-server-configuration-option?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-the-user-connections-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-user-connections-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@PrometheusRising1 -- thank you again for your feedback.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
@PrometheusRising1 

Thank you for your feedback! We will investigate and get back to you with the relevant info.

However, please add your experience in [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) to find if you see more people experience the same situation.

**Comment by markingmyname** [comment]
@PrometheusRising1 

Is this what you're looking for - https://www.mssqltips.com/sqlservertip/5766/managing-maximum-number-of-concurrent-connections-in-sql-server/?

Please let us know.

Thank you.

**Comment by PrometheusRising1** [comment]
No sir, that would be the max concurrent connections per instance - I was wondering if we could add info here on how to limit per database.

**Comment by markingmyname** [comment]
@PrometheusRising1 

I apologize again for the late delay, but unfortunately, there is not a way to do this that we support.

But please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site, and mention that addition if you would like.  The Product Group does review that site often to get ideas to update and improve.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
