### ISSUE TITLE
Instructional step does not match image

### ISSUE THREAD

**Issue by victorjz** [MicrosoftDocs/sql-docs#5519]
Under section 
_Script Stored Procedures_
on this line
_Right-click the stored procedure dbo.uspGetBillOfMaterials > Script Stored Procedure As > DROP and CREATE To > New Query Editor Window:_
Note that it says _DROP and CREATE To_

In the following image, it can be seen that the option _DROP To_ is pictured as selected

It seems it should be checked what is correct and then the text and image made to match.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9e9e24-0d85-b45b-21c1-65281538bfd4
* Version Independent ID: f26c593a-d399-b37e-244f-64c28a8285c1
* Content: [SSMS Script objects - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/tutorials/scripting-ssms?view=sql-server-ver15#script-extended-events)
* Content Source: [docs/ssms/tutorials/scripting-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/tutorials/scripting-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@victorjz -- Victor, thank you for your feedback.

@markingmyname -- Mark, please look into this issue.  You are welcome to send me the correct text or image, and I will update this article in a PR.

**Comment by markingmyname** [comment]
@victorjz 

Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

**Comment by markingmyname** [comment]
@victorjz 

The article has been updated.  Updates should be live by end of next week.

Thank you again for your comment

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
