### ISSUE TITLE
[typo]single quote are not closed

### ISSUE THREAD

**Issue by GCer-Hidenori** [MicrosoftDocs/sql-docs#5525]
- sql
```
IF NOT EXISTS  
(SELECT * FROM sys.credentials   
WHERE credential_identity = 'mycredential')  
CREATE CREDENTIAL <credential name> WITH IDENTITY = 'mystorageaccount'  
,SECRET = '<storage access key> ;  
```

single quote is required at the end of " '<storage access key> ;  ".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54961bd6-2a57-66b8-95ef-4b390263db82
* Version Independent ID: 213d141c-af2c-1ac5-8964-adee28f6fc87
* Content: [Backup to URL best practices & troubleshooting - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url-best-practices-and-troubleshooting?view=sql-server-ver15)
* Content Source: [docs/relational-databases/backup-restore/sql-server-backup-to-url-best-practices-and-troubleshooting.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/sql-server-backup-to-url-best-practices-and-troubleshooting.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@GCer-Hidenori -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
