### ISSUE TITLE
Conflict between docs on upper limit of synchronous-commit replicas

### ISSUE THREAD

**Issue by David-Rushton** [MicrosoftDocs/sql-docs#5528]
From this doc:

> Availability replicas: Each availability group supports one primary replica and up to eight secondary replicas. All of the replicas can run under asynchronous-commit mode, or up to **three of them can run under synchronous-commit mode** (one primary replica with two synchronous secondary replicas).  

(added emphasis)

According to the [What's new in SQL Server 2019](https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-ver15?view=sql-server-ver15#availability-groups) doc the synchronous-commit mode limit is now five and not three.

> SQL Server 2019 (15.x) increases the maximum number of synchronous replicas to 5, up from 3 in SQL Server 2017 (14.x). You can configure this group of five replicas to have automatic failover within the group. There is one primary replica, plus four synchronous secondary replicas.

Not tested but I believe the correct limit for SQL Server 2019 is 5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5dab67c-0b02-71a8-bba0-416be62e5d52
* Version Independent ID: c0f9db5f-668e-aac1-f789-cd7e34bdf316
* Content: [Availability group: Prerequisites, restrictions, & recommendations - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@David-Rushton -- David, thank you for your feedback.

@MashaMSFT -- Masha, please look into this issue.

**Comment by David-Rushton** [comment]
There is also a conflict in this doc:
https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/always-on-availability-groups-sql-server?view=sql-server-ver15

> Synchronous-commit mode. This availability mode emphasizes high availability and data protection over performance, at the cost of increased transaction latency. A given availability group can support up to **three** synchronous-commit availability replicas, including the current primary replica.

From the next paragraph:
SQL Server 2019 (15.x) increases the maximum number of synchronous replicas to **5**, up from 3 in SQL Server 2017 (14.x). You can configure this group of five replicas to have automatic failover within the group. There is one primary replica, plus four synchronous secondary replicas.

**Comment by cawrites** [comment]
@David-Rushton I appreciate your patience in reporting these updates for our Docs. We rely on community users like yourself to assist us with updates such as this. You will be happy to know I am bringing both this issue, current, and the updates will be shown in the next documentation refresh. Thank you again for contacting us.

**Comment by cawrites** [comment]
https://github.com/MicrosoftDocs/sql-docs-pr/pull/18542
