### ISSUE TITLE
Instructions for _installing_ extensions missing

### ISSUE THREAD

**Issue by ruffin--** [MicrosoftDocs/sql-docs#5529]
Page says...

> Extension installation in SSMS 18.x can be achieved by deploying the VSIX through Visual Studio or an independent managed package installer. The Visual Studio deployment is outlined below.

Note that this doesn't cover how to install SSMS extensions you've developed on other workstations. There are resources that cover this process:

* https://www.emoreau.com/Entries/Articles/2019/10/Creating-an-extension-using-VS2017-for-SSMS-18.aspx
* https://github.com/ErikEJ/SqlCeToolbox#installing-the-ssms-18-extension
* https://github.com/Timovski/CSVPaste/wiki/Installation-guide

... but they do not appear to be working currently. 

For instance:

* https://github.com/Timovski/CSVPaste/issues/1

I am having the same issue described above with SSMS extensions that I've written in Visual Studio (and run successfully locally) and have tried to deploy on other workstations with SSMS v18 installed. That is, I believe that github repo is representative of SSMS extensions in general.

----

Ideally, this page would include instructions for each of those options...

1. VS for local dev
2. Literally **installing** that extension on other workstations
3. [At least point to info on] Using "independent managed package installers". 

Currently this page only does 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63208429-3a47-debb-8dc5-78638bda7cd3
* Version Independent ID: 72ec2ffd-61c3-6329-c8f0-0927f3d13cdf
* Content: [Install Extensions in SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/install-extensions-in-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/install-extensions-in-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/install-extensions-in-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@ruffin-- Ruffin, thank you for your considered feedback.

@dzsquared -- Drew, please look into this issue.

**Comment by markingmyname** [comment]
We understand that you're looking for a specific permutation of the extension installation options.  

However, at this time we are researching other avenues and this will be a topic to investigate later in the future.

Once we start addressing this topic we will make an announcement.

thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by ruffin--** [comment]
> However, at this time we are researching other avenues and this will be a topic to investigate later in the future.

@markingmyname I don't understand what that means.

**Comment by markingmyname** [comment]
Hi, @ruffin--,

I apologize for not being clear.

I mean that we understand the request, but the means to plan for creating this content is far down the line.
