### ISSUE TITLE
SQL Service Master Key : Documentation not clear

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#5531]
The documentation at [https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/back-up-the-service-master-key?view=sql-server-ver15#:~:text=To%20back%20up%20the%20Service%20Master%20key%201,copy%20of%20the%20backed-up%20key.%20More%20items...%20] is not clear with regard to the SQL Server Service Master Key maintenance.

It states...
=====
Limitations and Restrictions
- The master key must be open and, therefore, decrypted before it is backed up. If it is encrypted with the service master key, the master key does not have to be explicitly opened; however, if the master key is encrypted only with a password, it must be explicitly opened.
- We recommend that you back up the master key as soon as it is created, and store the backup in a secure, off-site location.
=====
It is not clear if these directions are for the Service **Master Key** [smk] or a Database **Master Key** [dmk].  It would appear that these refer to a dmk instead - which does not make sense on a page that is specific to a smk.  This is in addition to an earlier submission of mine that the links at the bottom of the same page (referring to OPEN MASTER KEY and BACKUP MASTER KEY) also refer to a dmk rather than smk maintenance.

Where also is any reference as to how one tests that the backup of an smk is valid?  I have also submitted this issue in other documentation "fix" requests.  

It would appear that this entire page is a confusing mix of references to smk (desired) and dmk (not desired and not fully referenced as "master key" could refer to BOTH or either) maintenance processes.

Regards,
Linda A. Lorentz Fletcher

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0528f177-7fc8-2d7b-ba55-803bc0edc741
* Version Independent ID: 4d1c3d66-6715-ce15-0a08-12f7f06ae640
* Content: [Back Up the Service Master Key - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/back-up-the-service-master-key?view=sql-server-ver15#:~:text=To%20back%20up%20the%20Service%20Master%20key%201,copy%20of%20the%20backed-up%20key.%20More%20items...%20)
* Content Source: [docs/relational-databases/security/encryption/back-up-the-service-master-key.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/back-up-the-service-master-key.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@LindaLF -- Linda, thank you for your thorough feedback, and for your previous similar issues:
- https://github.com/MicrosoftDocs/sql-docs/issues/5500
- https://github.com/MicrosoftDocs/sql-docs/issues/5510

@jaszymas -- please look into this new issue.

**Comment by VanMSFT** [comment]
@LindaLF - Hey Linda, thanks again for submitting these issues. I agree, it's confusing and the the first limitation reference seems to be for DMK.

@Rupp29 - Hey Adrian, can you help confirm this? It seems that we'll want to remove the **Limitations and Restrictions** section as it appears to be talking about the DMK, and not the SMK. Please help confirm.

**Comment by VanMSFT** [comment]
Clarifying in https://github.com/MicrosoftDocs/sql-docs-pr/pull/19007

**Comment by VanMSFT** [comment]
Hi @LindaLF - Thanks again for bring up this issue. I've clarified that the limitation portion of the article is referencing the DMK, and am removing that portion from the doc.
