### ISSUE TITLE
Needs additional steps to get sqlcmd working on Ubuntu

### ISSUE THREAD

**Issue by kaushalp** [MicrosoftDocs/sql-docs#5532]
I had to run an additional command to get sqlcmd working on ubuntu 

> ln -sfn /opt/mssql-tools/bin/sqlcmd /usr/bin/sqlcmd

Without these link, it errored out with sqlcmd not found. 

I found the instructions here: https://sqlserveronlinuxbackup.com/sqlcmd-command-not-found-ubuntu/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15#ubuntu)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@kaushalp -- Kaushal, thank you for your clear solution.  I am updating this article.

**Comment by VanMSFT** [comment]
@kaushalp @WilliamAntonRohm - This is already covered in Step 4: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15#ubuntu

The reason the sqlcmd is not found is because you're not in the correct folder to execute it. What you're doing with the `ln` command is creating a symbolic link, instead of adding the path to the ~/.bash_profile file as the document states.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, thank you for clarifying.  

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by kaushalp** [comment]
@VanMSFT I had tried the step 4, and that hadn't worked. I will give this a try on another box and if it re-surfaces, I will update the thread.

**Comment by VanMSFT** [comment]
@kaushalp - You'll need to make sure that path that you are putting in actually contains sqlcmd. This is not a documentation issue.
