### ISSUE TITLE
Why does error_state() return an int when the only allowable values are tinyint?

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/sql-docs#5536]
`throw` and `raiserror` accept a `state` parameter that is constrained to be a `tinyint`, yet `error_state()` is defined and documented to return the wider `int`. Why?

**Comment by WilliamAntonRohm** [comment]
@IanKemp -- Ian, thank you again for your perceptive questions.  Are you following a particular docs.microsoft.com article?
