### ISSUE TITLE
Documentation lacking about how to use curl with AD deployment of BDC

### ISSUE THREAD

**Issue by saurabh500** [MicrosoftDocs/sql-docs#5544]
[Enter feedback here]

There is no documentation hint about how to use curl with webHdfs when Big data clusters are deployed with AD.
The username/password authentication would not work in that case. 

The documentation should be improved for AD deployments and curl usage. 

For AD usage the customer needs to 
1. Get a kerberos token using kinit `kinit <username>`
2. Use negotiate auth in curl using 
`curl -i -L -k -negotiate -u : -X GET 'https://<gateway-svc-external IP external address>:30443/gateway/default/webhdfs/v1/product_review_data/?op=liststatus'`

AD deployment is important especially for the HDFS interactions and we should highlight it better in the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84020496-00b9-06f6-4342-48ba4fa6323e
* Version Independent ID: 75531c7f-4d0d-b8cc-741d-75baf456382f
* Content: [Use curl to load data into HDFS - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/data-ingestion-curl?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/data-ingestion-curl.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/data-ingestion-curl.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@saurabh500 -- Saurabh, thank you for your feedback and for your documentation contribution.

@MikeRayMSFT -- Mike, please look into this issue.
