### ISSUE TITLE
Duplicate Ubuntu 16.04 entries on ODBC page

### ISSUE THREAD

**Issue by curiositycasualty** [MicrosoftDocs/sql-docs#5546]
Entries for "Ubuntu 16.04" are duplicated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@curiositycasualty Thanks for submitting feedback. There are 3 different sections for Ubuntu 16.04. One for ODBC Driver 17, one for ODBC Driver 13.1, and on for ODBC Driver 13. There are small differences to install the different driver versions. Is that what you are referring to? Those sections look similar but are not duplicates of each other.

Thanks,
David

**Comment by curiositycasualty** [comment]
My mistake!
