### ISSUE TITLE
SQL Server Partitioning

### ISSUE THREAD

**Issue by MarianoKovo** [MicrosoftDocs/sql-docs#5548]
Hi team, I was reading the section **Query Processing Enhancements on Partitioned Tables and Indexes** and it declares in a note the following: 
"Partitioned tables and indexes are supported only in the SQL Server Enterprise, Developer, and Evaluation editions."

In the other hand, in the Documentation of **Partitioned Tables and Indexes** 
Ref: [https://docs.microsoft.com/en-us/sql/relational-databases/partitions/partitioned-tables-and-indexes?view=sql-server-ver15](url)
It specifies that from SQLServer 2016 SP1 and later versions, Partitioned Tables and Indexes are supported in Standard Edition as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45a7c96a-9d41-83e8-0ae8-b73fff390f48
* Version Independent ID: 1a880308-6a3b-6944-6428-1331801b327a
* Content: [Query Processing Architecture Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/query-processing-architecture-guide?view=sql-server-ver15)
* Content Source: [docs/relational-databases/query-processing-architecture-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/query-processing-architecture-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by pmasl** [comment]
Thanks for calling this out. It is supported on Std Ed, I'll update the guide.

**Comment by pmasl** [comment]
#please-close
