### ISSUE TITLE
Fix Example for Adding SPNs

### ISSUE THREAD

**Issue by seanpmassey** [MicrosoftDocs/sql-docs#5554]
The doc states that adding the SPN for the Linux server has to be formatted exactly as the example code.  This includes characters like ** to denote when you're denoting a variable that the user will need to fill in to match their environment. 

This can cause some confusion, especially for inexperienced users who are not familiar with creating SPNs, and they may copy the code exactly as it is displayed, fill in their variables, and test it. 

Please include the following in this tutorial to help clear this up:
1. A note that certain characters are for formatting and should not be included
2. Sample commands that would show how this should look with hostnames and ports filled in

The ** characters could also be a Markdown formatting error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Use AD authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **dygray**

**Comment by WilliamAntonRohm** [comment]
@seanpmassey -- Sean, thank you for catching these.  It's a Markdown issue, and I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
