### ISSUE TITLE
kill xxx with commit ,kill xxx with rollback is supported with SQL Server 2019?

### ISSUE THREAD

**Issue by GCer-Hidenori** [MicrosoftDocs/sql-docs#5562]
[This page](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/kill-transact-sql?view=sql-server-ver15)  did not describe kill xxx with commit and kill xxx with rollback.
But [This page](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-availability-group-for-distributed-transactions?view=sql-server-ver15) use kill xxx with commit ,kill xxx with rollback.
These kill xxx with commit ,kill xxx with rollback is supported with SQL Server 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4525f922-c768-bb9c-fc93-4a3b790c03fb
* Version Independent ID: f50f9610-c6a6-0fad-5f53-975a64a53704
* Content: [Configure distributed transactions for an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-availability-group-for-distributed-transactions?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/configure-availability-group-for-distributed-transactions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/configure-availability-group-for-distributed-transactions.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@GCer-Hidenori -- thank you for your question.

@MashaMSFT -- please look into this issue.

cc @rothja for awareness

**Comment by MashaMSFT** [comment]
Hi @GCer-Hidenori , thanks so much for reaching out! The kill with commit and kill with roll back is only applicable to distributed transactions. We've updated the Kill documentation to provide some extra cross reference. These changes will be live next week.

Thanks for contacting Microsoft and helping improve our documentation! I'm going to close out this Git Issue but please feel free to comment should you need anything further.

Thanks again and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
