### ISSUE TITLE
[typo]single quote is not closed

### ISSUE THREAD

**Issue by GCer-Hidenori** [MicrosoftDocs/sql-docs#5564]
- sql
```
SELECT g.name AS AG, replica_server_name, secondary_role_allow_connections_desc  
FROM sys.availability_replicas AS r  
JOIN sys.availability_groups AS g  
    ON r.group_id = g.group_id  
WHERE g.name = N'MY_AG_NAME;  
```

single quote is required between 'MY_AG_NAME' and ';'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 027b02c5-715e-2948-67e0-12834121be1a
* Version Independent ID: ac8135ce-21cf-470e-809c-7bf3e83fa8af
* Content: [Replication, change tracking, change data capture & availability groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/replicate-track-change-data-capture-always-on-availability?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/replicate-track-change-data-capture-always-on-availability.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/replicate-track-change-data-capture-always-on-availability.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@GCer-Hidenori -- thank you for catching this. I am updating the article.
