### ISSUE TITLE
Add info regarding availability of x64 version of SSMS

### ISSUE THREAD

**Issue by luisdev** [MicrosoftDocs/sql-docs#5568]
This page should include some information regarding the availability of the x64 version of SSMS. Is a x64 version available? If so, where do you get it? If not, why not... etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
Notification has been added to the page that this is a 32-bit application and no other versions are available.
https://docs.microsoft.com/sql/ssms/download-sql-server-management-studio-ssms#ssms-system-requirements

#please-close
