### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jrmclennan** [MicrosoftDocs/sql-docs#5571]
"It is importand to understand however"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d91022-0ff5-2a0e-4711-217fd9568018
* Version Independent ID: cd30c087-06e7-f947-cf6a-262001d574a3
* Content: [Intelligent query processing - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/intelligent-query-processing?view=sql-server-ver15#batch-mode-on-rowstore)
* Content Source: [docs/relational-databases/performance/intelligent-query-processing.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/intelligent-query-processing.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @joesackmsft
* Microsoft Alias: **josack**

**Comment by WilliamAntonRohm** [comment]
@jrmclennan -- thank you for catching this.  I am updating the article.
