### ISSUE TITLE
Page needs update

### ISSUE THREAD

**Issue by truxonjm** [MicrosoftDocs/sql-docs#5576]
On a fresh installation of SQL Server 2019 Developer Edition with Python ML tools installed, installing tensorflow as described in the [Cannot install tensorflow...](https://docs.microsoft.com/en-us/sql/machine-learning/troubleshooting/known-issues-for-sql-server-machine-learning-services?view=sql-server-ver15#9-cannot-install-tensorflow-package-using-sqlmlutils) section, I found that attempting to use tensorflow [will still fail](https://github.com/tensorflow/tensorflow/issues/42394) until the C++ redistributable has been installed, as described [here](https://stackoverflow.com/questions/60319768/cant-import-tensorflow-in-python-windows-10-64-bit/61656869#61656869).   Including that detail in your Known Issues document would be extremely helpful to those that follow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 301e7988-db36-681c-3dfa-d3b351ffea70
* Version Independent ID: e07fb786-5d4d-dae4-9d59-cc53aa79525f
* Content: [Known issues for Python and R - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/troubleshooting/known-issues-for-sql-server-machine-learning-services?view=sql-server-ver15#7-unable-to-install-python-packages-using-pip-after-installing-sql-server-2019-on-windows)
* Content Source: [docs/machine-learning/troubleshooting/known-issues-for-sql-server-machine-learning-services.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/troubleshooting/known-issues-for-sql-server-machine-learning-services.md)
* Product: **sql**
* Technology: **machine-learning-services**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@truxonjm Thank you for your suggestion. I have assigned the GitHub issue to the author and we will get back to you shortly.

**Comment by cawrites** [comment]
@truxonjm thank you for contacting Microsoft regarding this matter. We will review these findings and be in touch.

**Comment by cawrites** [comment]
#please-close
