### ISSUE TITLE
nice Information

### ISSUE THREAD

**Issue by anil150875** [MicrosoftDocs/sql-docs#5577]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24e49fc4-1101-0d6f-e16a-52242616287b
* Version Independent ID: df5e0042-2137-3309-a957-de5f556f5c84
* Content: [Lesson 2: Connecting from Another Computer - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/lesson-2-connecting-from-another-computer?view=sql-server-ver15)
* Content Source: [docs/relational-databases/lesson-2-connecting-from-another-computer.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/lesson-2-connecting-from-another-computer.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @anil150875 , my apologies, but it seems that your feedback did not come through. How can Microsoft help?

Thanks!
Masha from the SQL Docs team
