### ISSUE TITLE
Maximum Snapshot Database sparse file size

### ISSUE THREAD

**Issue by LonnyNiederstadt** [MicrosoftDocs/sql-docs#5580]
[Enter feedback here]
On the "View the Size of the Sparse File of a Database Snapshot (Transact-SQL)" page, under the "Find Out the Maximum Size of a Sparse File" heading it says:
"The maximum size to which a sparse can grow is the size of the corresponding source database file at the time of the snapshot creation."

It is more accurate to say the maximum is the corresponding source database file size unless otherwise limited by filesystem metadata constraints.

For example, in an NTFS filesystem with 4k or 64k allocation unit size which was created without the /L or useLargeFRS option, the sparse file is limited to ~1.5 million extents or roughly 91.5 gb if every 64k allocation in the sparse file is a separate extent.  With the /L or useLargeFRS option, the maximum number of extents becomes ~6 million for a maximum sparse file size-on-disk of ~366 gb under the same circumstances.

The maximum extents per file is discussed at the NTFS overview link - though not in the context of sparse files - in the "Formatting requirements for large files" section.
https://docs.microsoft.com/en-us/windows-server/storage/file-server/ntfs-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb223d8-50d2-3a19-f305-bcba59ec6faa
* Version Independent ID: 18fccb29-bf5a-c370-f431-b712d66cf842
* Content: [View size of sparse file of a Database Snapshot (T-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/view-the-size-of-the-sparse-file-of-a-database-snapshot-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/view-the-size-of-the-sparse-file-of-a-database-snapshot-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/view-the-size-of-the-sparse-file-of-a-database-snapshot-transact-sql.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@LonnyNiederstadt -- thank you for your well-researched feedback.

@stevestein -- please look into this issue.

**Comment by stevestein** [comment]
@LonnyNiederstadt - thanks for raising this issue.  Because of the limited amount of traffic to this article, and the complexity this will add to the explanation, we've decided to keep the wording as is. If this article was more than simply viewing the file size we might consider adding more information. 

Thanks

#please-close
