### ISSUE TITLE
DATEDIFF_BIG does consider time zone

### ISSUE THREAD

**Issue by mitchterlisner** [MicrosoftDocs/sql-docs#5592]
The docs for DATEDIFF_BIG say:

> `DATEDIFF_BIG` does not use a time zone offset component of _startdate_ or _enddate_ to calculate the return value.

(This is the case for the docs for both [2017](https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-big-transact-sql?view=sql-server-2017) and [ver15 (2019)](https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-big-transact-sql?view=sql-server-ver15).)

This appears to be wrong.  I'm running 2017, and this demonstrates that DATEDIFF_BIG does support the offset (the same as DATEDIFF) by displaying the correct difference:
```
DECLARE @dt1 DATETIMEOFFSET(7) = '2020-10-19 07:00:00 -06:00', @dt2 DATETIMEOFFSET(7) = '2020-10-19 07:00:00 -05:00';
SELECT [@dt1] = @dt1, [@dt2] = @dt2, DATEDIFF = DATEDIFF(MINUTE, @dt1, @dt2), DATEDIFF_BIG = DATEDIFF_BIG(MINUTE, @dt1, @dt2);
```

I found this same issue previously reported (and fixed) for the DATEDIFF docs (https://github.com/MicrosoftDocs/sql-docs/issues/2394), so I suspect this just needs a corresponding documentation update for DATEDIFF_BIG.

Please update the docs to reflect this.

**Comment by WilliamAntonRohm** [comment]
@mitchterlisner -- Mitch, thank you for your feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@mitchterlisner,

Thank you for your contribution.

Good catch.

The article should be updated by end of the week.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
