### ISSUE TITLE
Why didn't Microsoft ever build a single script that detect the Linux distro and its version to install and test?

### ISSUE THREAD

**Issue by enniosousa** [MicrosoftDocs/sql-docs#5601]
Why didn't Microsoft ever build a single script that detect the Linux distro and its version to install and test?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
Hi @enniosousa 

Thank you for contacting us. A single script like that in the documentation would be far more complicated than the few steps documented for each Linux distribution. Distribution detection and prompting for optional steps would add to the script complexity. As it is, the few commands are easy enough for a typical Linux user to choose from and run correctly based on their optional needs.

Most of the actual installation process is simplified in the packages, which get installed by the documented installation steps. The steps start with a couple one-time commands to configure the Microsoft package repository. The actual package install commands are standard/simple package commands (yum/apt-get/zypper) for each Linux distribution. Then there are optional commands you can run for helper packages and to configure your PATH for easier tool use. While a one-size-fits-all script might sound even simpler, it's already been simplified quite a bit and the existing steps are easily customizable.

Regards,
David

**Comment by WilliamAntonRohm** [comment]
@David-Engel -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
