### ISSUE TITLE
on redhat, how do i run a cmd line microsoft cmd line query?

### ISSUE THREAD

**Issue by cellurl3** [MicrosoftDocs/sql-docs#5603]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077d3062-2151-69f2-e27d-e3a988d948e1
* Version Independent ID: f014c606-a4a7-011c-2911-fc10e4cd2369
* Content: [Unattended install for SQL Server on RHEL - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sample-unattended-install-redhat?view=sql-server-ver15)
* Content Source: [docs/linux/sample-unattended-install-redhat.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sample-unattended-install-redhat.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by cellurl3** [comment]
from redhat, i want to get data from a microsoft sql server.

After I install cmd line tools, where is example I run/how?       "Select * from table" and send it to a flatfile perhaps??

**Comment by VanMSFT** [comment]
Hi @cellurl3 - Please check out our [sqlcmd](https://docs.microsoft.com/sql/ssms/scripting/sqlcmd-use-the-utility) documentation for more information.
