### ISSUE TITLE
auto Installing ADS with SSMS will just cause us to remove ADS

### ISSUE THREAD

**Issue by gwalkey** [MicrosoftDocs/sql-docs#5606]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
The best place for providing feedback on the products is UserVoice, these pages are for contributing to changes to the documentation. 
User Voice: https://feedback.azure.com/forums/908035-sql-server

thanks!

#please-close
