### ISSUE TITLE
Inaccurate and Incomplete Article

### ISSUE THREAD

**Issue by WittiTech** [MicrosoftDocs/sql-docs#5609]
The articles does not address constrains or limitations for SQL Azure; and if you try to follow the documentation; you will never create a partitioned table in SQL Azure. Additionally, the article title mentioned Indexes which are not addressed in the article when it absolutely should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4466c524-282b-adc0-d539-3eb85d956597
* Version Independent ID: 08052bb4-d7bb-02ab-6d37-e3fcce20846c
* Content: [Create Partitioned Tables and Indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/partitions/create-partitioned-tables-and-indexes?view=sql-server-ver15)
* Content Source: [docs/relational-databases/partitions/create-partitioned-tables-and-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/partitions/create-partitioned-tables-and-indexes.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamDAssafMSFT** [comment]
#reassign WilliamDassafMSFT

**Comment by WilliamDAssafMSFT** [comment]
Hi @WittiTech, thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. 

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
#in-progress

**Comment by WilliamDAssafMSFT** [comment]
Hi @WittiTech, thanks for the comment. We have a doc update in flight to add more caveats about filegroups in Azure SQL DB. We have an updated sample script reflecting that only the PRIMARY filegroup is supported in Azure SQL DB. Otherwise table partitioning and partition switching are fully supported in Azure SQL DB.

#please-close
