### ISSUE TITLE
CREATE MASTER KEY on which db?

### ISSUE THREAD

**Issue by random-filip** [MicrosoftDocs/sql-docs#5612]
In Azure Synapse Analytics, are you not supposed to the create the master key in the database you intend to use it in? I have read some threads where a server admin user was unauthorized to do this on master. Also, in the below exercise, I believe the master key is created in another db (DemoDW) than master.

https://docs.microsoft.com/en-us/learn/modules/import-data-into-asdw-with-polybase/7-import-data-from-blob-to-dw

Some threads:
https://stackoverflow.com/questions/59511699/how-to-create-a-master-key-on-the-master-databasewhat-are-the-roles-required-to

https://dba.stackexchange.com/questions/256411/how-to-create-a-master-key-on-the-master-databasewhat-are-the-roles-required-to

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72202472-1d43-9377-d783-588347884491
* Version Independent ID: 99f5b0e8-b482-0ce4-ba88-73aa5dd28dc9
* Content: [Create a Database Master Key - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/create-a-database-master-key?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/create-a-database-master-key.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/create-a-database-master-key.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@random-filip -- thank you for your question and research.  Please consider this resource as well:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)

@jaszymas -- please look into this issue.

**Comment by random-filip** [comment]
Found a thread in the linked Q&A, that I believe anwsers the question, and should be added to the Azure tutorials/instructions:

https://social.msdn.microsoft.com/Forums/en-US/1c283baa-6f2c-4f5d-838b-14213b6a46d6/cannot-create-master-keycertificate-in-master-db-for-tde?forum=ssdsgetstarted

See specific reply in image below:

![image](https://user-images.githubusercontent.com/54273774/96997009-37e0eb00-1531-11eb-8373-18662de72e59.png)

**Comment by VanMSFT** [comment]
Hi @random-filip! Sorry for the delay.

@julieMSFT @WilliamDAssafMSFT - Is this something you guys can take a look at and see if doc adjustments are needed?
