### ISSUE TITLE
Dynamic Data Masking only available from SQL Server 2016 and later

### ISSUE THREAD

**Issue by sqlgt0** [MicrosoftDocs/sql-docs#5621]
This page state Dynamic Data Masking is supported on SQL Server (all supported versions), but it seem this feature is only available from SQL Server 2016 and higher.
If this is the case, then the "SQL Server (all supported versions)" should be removed from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9408bf-18b5-339f-cd25-6a3024be3243
* Version Independent ID: eea4b8dc-5598-b7e6-e01a-902d5ca1f96d
* Content: [Dynamic Data Masking - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/dynamic-data-masking?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/dynamic-data-masking.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/dynamic-data-masking.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Thanks @sqlgt0! I'm fixing this and the doc should be updated later today.

**Comment by SanthoshPK** [comment]
Hi All, 

I have a issue with dynamic data masking while accessing via Views which use UNION .

Select name from **TableA** > name column masked with abcxyz using partial function
Select name from **TableB** > name column masked with abcxyz using partial function

Create a View called **ViewAB**. It has select query inside which looks similar as below.

**Select name from TableA
Union 
Select name from TableB**

the output shows me the data as xxxxx - which is a default mask and not the mask which we applied using partial function 
 as abczyz.

Any help / advise would be appreciated .

thank you.
Santhosh
