### ISSUE TITLE
Proper file name possible ? 

### ISSUE THREAD

**Issue by nojetlag** [MicrosoftDocs/sql-docs#5624]
Would it be possible to have the version information in the file name as well ? Other Microsoft products do it like that, with SSMS we always get a generic file name that has to be later manually renamed to know what version is what executable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@nojetlag -- thank you for your suggestion.  Please add it here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @dzsquared for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
