### ISSUE TITLE
Linux installation does not include silent options

### ISSUE THREAD

**Issue by Justin-DynamicD** [MicrosoftDocs/sql-docs#5628]
[Enter feedback here]

while this does show how how to install tools in linux, the apt-installer requires a user to type "yes" and will not install automatically.  Please include methods toautomatically install so the tools can be installed in a container.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @Justin-DynamicD - Please see https://docs.microsoft.com/en-us/sql/linux/sample-unattended-install-ubuntu?view=sql-server-ver15 for an example of unattended install of mssql-tools.
