### ISSUE TITLE
[Question] T-SQL date data type format for SQL Server mm/dd/yy or yy/dd/mm or something else?

### ISSUE THREAD

**Issue by donhuvy** [MicrosoftDocs/sql-docs#5630]
Please help me answer the question at here https://stackoverflow.com/questions/64522397/t-sql-date-data-type-format-for-sql-server-mm-dd-yy-or-yy-dd-mm-or-something-els

Seemly it is a mistake in reference document.

**Comment by donhuvy** [comment]
We need table border at here for easy-to-read, very confusing at these information.

**Comment by WilliamAntonRohm** [comment]
@donhuvy -- thank you for your question.  It appears to have been answered in StackOverflow already.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
