### ISSUE TITLE
JSON string with \ are not JSON 

### ISSUE THREAD

**Issue by RdV28** [MicrosoftDocs/sql-docs#5647]
When a JSON string contains a \ in the data part it can't be interpreted by de SQL JSON implementation.

declare @json nvarchar(max);
set @json = '{  "WindowStoragePath": "\20220"}' 
print @json
select isjson(@json) isjson

will return 0

**Comment by WilliamAntonRohm** [comment]
@RdV28 -- thank you for your feedback.  Please consider adding it here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

Are you following a particular docs.microsoft.com article?
