### ISSUE TITLE
JSON string can't be using ' as separator even though it is valid JSON 

### ISSUE THREAD

**Issue by RdV28** [MicrosoftDocs/sql-docs#5648]
When a JSON string contains ' instead of " as separator SQL JSON implementation does not accept this as valid JSON while PowerShell does.

declare @json nvarchar(max);
set @json = '{  ''WindowStoragePath'': ''20220''}' 
print @json
select isjson(@json) isjson
go

prints message : {  'WindowStoragePath': '20220'}
prints results:  0

**Comment by WilliamAntonRohm** [comment]
@RdV28 -- thank you for your feedback.  Please see my comments in #5647.
