### ISSUE TITLE
Ubuntu 20.04 Can't Install msodbcsql17

### ISSUE THREAD

**Issue by ecc256** [MicrosoftDocs/sql-docs#5650]
Follow up for [closed issue](https://github.com/MicrosoftDocs/sql-docs/issues/5277#) 

It doesn’t work 100% on Ubuntu 20.04
**# sudo apt-get update**
_Hit:1 http://us-east-1.ec2.ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:2 http://us-east-1.ec2.ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:3 http://us-east-1.ec2.ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Get:4 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease [10.5 kB]
Get:5 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 Packages [32.9 kB]
Get:6 https://packages.microsoft.com/ubuntu/20.04/prod focal/main arm64 Packages [5210 B]
Get:7 https://packages.microsoft.com/ubuntu/20.04/prod focal/main armhf Packages [5205 B]
Hit:8 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease  
Fetched 53.8 kB in 0s (142 kB/s)               
Reading package lists... Done_

**# sudo ACCEPT_EULA=Y apt-get install msodbcsql17**
_Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package msodbcsql17_

How could it possibly work if [Contents](https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/Contents-arm64.gz) doesn't even mention **msodbcsql17**?

**Comment by WilliamAntonRohm** [comment]
@ecc256 -- thank you for your follow-up.

@David-Engel -- please look into this potential documentation issue.

**Comment by ecc256** [comment]
@WilliamAntonRohm 
I do understand perfectly, it’s simply not available for all Ubuntu CPU architectures.

The real question is:
Is it just a matter of compiling it or a lot more than that and thus won’t be available anytime soon?

I assume, it’s not an open source code and there is no way to DIY, correct?

**Comment by David-Engel** [comment]
@ecc256 I definitely see the driver in [Contents](https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/Contents-amd64.gz) for amd64. It isn't in the arm64 Contents because it is only supported on x64 platforms:

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/system-requirements?view=sql-server-ver15#operating-system-support
> Versions 17, 13.1, and 13 of the Linux and macOS drivers are supported on the **x64** architecture of the following operating systems:

No, there is no way to DIY this. The ODBC driver is not open-source. It's never as simple as just compiling. There is significant test infrastructure that is required to support and maintain a platform, as well.

I was going to suggest submitting feedback, but it looks like someone has already requested arm64 support on Ubuntu. You can go vote for it, though:
https://feedback.azure.com/forums/908035-sql-server/suggestions/40572529-ubuntu-20-04

Regards,
David

Closing, since this isn't a doc issue.
#please-close

**Comment by ecc256** [comment]
@David-Engel,
Casted my votes just now!
Do you happen to know how to subscribe for alpha/beta testing when they'll be available?
Thanks for clarification!

**Comment by David-Engel** [comment]
@ecc256 If there is a beta test cycle, it would be announced on this blog: https://techcommunity.microsoft.com/t5/sql-server/bg-p/SQLServer/label-name/SQLServerDrivers
It would probably need to gain many more votes to happen any time soon. However, given the Apple ARM64 announcements and other ARM64 growth, it's not out of the realm of possibilities.

**Comment by ecc256** [comment]
@David-Engel,
Got it.
Look like no way to subscribe to get notified, need to keep monitoring...
Once again thanks for clarification!

**Comment by funcelotwork** [comment]
```sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/21.04/prod.list)"```

```sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/prod.list)"```

@David-Engel

**Comment by David-Engel** [comment]
@funcelotwork 

Both of those URLs work for me. Maybe you were experiencing an intermittent issue?

**Comment by funcelotwork** [comment]
> @funcelotwork
> 
> Both of those URLs work for me. Maybe you were experiencing an intermittent issue?

I think it is an issue for 21.04 Microsoft key not being added to trusted providers.

**Comment by funcelotwork** [comment]
I have to install 20.04 instead of my favorite 21.04 due to impossibility work with msodbsql17's luck of driver installation insturctions on official Microsoft site

**Comment by David-Engel** [comment]
@funcelotwork Oh, right. In the context of installing the driver... Ubuntu 21.04 is not yet supported by the Microsoft ODBC Driver for SQL Server. Ubuntu 21.04 wasn't even out the last time the driver was released (January this year). It will be supported in the next release, though. The driver is on a 6-month release cycle, so look for it on July 30th (releases happen during business hours Pacific time).

**Comment by funcelotwork** [comment]
For the 20.04, The Trampoline works! as expected, approved.

**Comment by ps-mattstuart** [comment]
Perhaps I'm missing something, the msodbcsql17 driver is still not listed in the available packages for the 18.04, 20.04, or 21.04 distributions for arm64. They're present for the amd64 packages but not as this thread would indicate available for arm. The packages don't even physically exist https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/msodbcsql17/ 

The feedback link posted is now 404 so I can't update that. There's an M1 build that's based on arm64, would it not be possible to release these into the linux channels?

**Comment by ecc256** [comment]
> There's an M1 build that's based on arm64, would it not be possible to release these into the linux channels?

+1

**Comment by David-Engel** [comment]
@ps-mattstuart 

> Perhaps I'm missing something, the msodbcsql17 driver is still not listed in the available packages for the 18.04, 20.04, or 21.04 distributions for arm64. They're present for the amd64 packages but not as this thread would indicate available for arm. The packages don't even physically exist https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/msodbcsql17/

I think the thread pivoted to 21.04 support on amd64. Linux arm support has not been added to the ODBC driver.

> The feedback link posted is now 404 so I can't update that.

The feedback website completely changed. It looks like this might be the new link to the same request: https://feedback.azure.com/d365community/idea/38d01043-5825-ec11-b6e6-000d3a4f0da0

> There's an M1 build that's based on arm64, would it not be possible to release these into the linux channels?

No. macOS and Linux use different packaging. for starters.

Regards,
David

**Comment by ps-mattstuart** [comment]
Thank you for the clarity on the thread switch, definitely where my confusion came from. 

I will continue to watch for the arm based Linux releases. The final piece we’re waiting on before switching our dev machines and our production instances to full arm hosts.

**Comment by ecc256** [comment]
David,

>I think the thread pivoted to 21.04 support on amd64. Linux arm support has not been added to the ODBC driver.

Could you tell, was it due to lack of resources or lack of demand (estimated)?
With such a progress it might be easier/faster to switch backend DB, actually... :(

**Comment by David-Engel** [comment]
> Could you tell, was it due to lack of resources or lack of demand (estimated)?

@ecc256 It's always a balance of resources versus demand. Demand has been increasing, though. In my opinion, the priority of ARM support in general has gone significantly up in the past year or so.

**Comment by ecc256** [comment]
@David-Engel 
Fair enough! :)
