### ISSUE TITLE
Missing white space after INDEX

### ISSUE THREAD

**Issue by NeuroXiq** [MicrosoftDocs/sql-docs#5653]
"By default, the cells-per-object limit is 16 cells per object, which provides a satisfactory trade-off between space and precision for most spatial indexes. However, the CREATE SPATIAL INDEXTransact-SQL"
Last is "INDEXTransact-SQL" but should be "INDEX Transact-SQL" :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cc755df-a7f8-a80f-8d59-cb36dd8e7125
* Version Independent ID: 75e6108e-c939-3a4f-2690-6c3429d4c7c2
* Content: [Spatial Indexes Overview - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-indexes-overview?view=sql-server-ver15)
* Content Source: [docs/relational-databases/spatial/spatial-indexes-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/spatial/spatial-indexes-overview.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@NeuroXiq -- Marek, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@NeuroXiq -- this article appears to have been updated since your feedback, as that typo is no longer there.  
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
