### ISSUE TITLE
[typo]full-width single quote is used as enclosure character

### ISSUE THREAD

**Issue by GCer-Hidenori** [MicrosoftDocs/sql-docs#5654]
```
EXEC sp_rename 'dbo.MyTableNew', 'dbo.MyTable’;
```
last single quote is full-width character.
It must be half-width single quote character.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87a2748-d8be-3035-46c9-6d9d0defafb1
* Version Independent ID: 9fbac27b-784a-c17f-c3eb-9925c93c7744
* Content: [Set or Change the Column Collation - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-column-collation?view=sql-server-ver15)
* Content Source: [docs/relational-databases/collations/set-or-change-the-column-collation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/set-or-change-the-column-collation.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@GCer-Hidenori -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
