### ISSUE TITLE
[typo]mistakenly wrote fron as from

### ISSUE THREAD

**Issue by GCer-Hidenori** [MicrosoftDocs/sql-docs#5655]
You mistakenly wrote fron as from.
```
SELECT * FRON t_hk  
   WHERE c2 > 5;  
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b709105d-2585-1426-2453-c7078ba9af24
* Version Independent ID: d2a502c2-29b1-1c39-51a2-6c3c5a5c8978
* Content: [Memory requirements - memory-optimized tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/estimate-memory-requirements-for-memory-optimized-tables?view=sql-server-ver15)
* Content Source: [docs/relational-databases/in-memory-oltp/estimate-memory-requirements-for-memory-optimized-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/estimate-memory-requirements-for-memory-optimized-tables.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@GCer-Hidenori -- nice catch!  I am updating the article.
