### ISSUE TITLE
[typo]single quote is not closed

### ISSUE THREAD

**Issue by GCer-Hidenori** [MicrosoftDocs/sql-docs#5656]
https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-fkeys-transact-sql?view=sql-server-ver15

```
EXEC sp_fkeys @pktable_name = N'DimDate;  
```
single quote is not closed.

**Comment by WilliamAntonRohm** [comment]
@GCer-Hidenori -- thank you again for your keen eye.  I will update the article.
