### ISSUE TITLE
add architecture notice - currently x64 only

### ISSUE THREAD

**Issue by williamvm** [MicrosoftDocs/sql-docs#5657]
the .deb download has no architecture mentioned in the file name. That might be an indication it is x64 only. Tried to install on Arm64 and failed. 

Better make it explicit in the filename and as a note on the docs page.

Thank you, love the tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/download-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download-azure-data-studio.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
@williamvm -- William, thank you for your feedback and kind words.

@yualan -- Alan, please look into this issue.

**Comment by markingmyname** [comment]
@williamvm 

Apologies for the delayed response.

Unfortunately, we do not support ARM currently, but we are in discussion on making it so.

**Comment by markingmyname** [comment]
The article will be updated by the end of next week.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
