### ISSUE TITLE
[typo]There's an extra single quote written in.

### ISSUE THREAD

**Issue by GCer-Hidenori** [MicrosoftDocs/sql-docs#5662]
https://docs.microsoft.com/en-us/sql/t-sql/statements/delete-transact-sql?view=sql-server-ver15

```sql
DELETE FROM OPENDATASOURCE('SQLNCLI',  
    'Data Source= <server_name>; Integrated Security=SSPI')  
    .AdventureWorks2012.HumanResources.Department   
WHERE DepartmentID = 17;'  
```  
No need for a single quote at the end.

**Comment by WilliamAntonRohm** [comment]
@GCer-Hidenori -- thank you for your close reading.  I am correcting the article.
