### ISSUE TITLE
[typo]The parentheses in the insert statement are not closed.

### ISSUE THREAD

**Issue by GCer-Hidenori** [MicrosoftDocs/sql-docs#5669]
The parentheses in the insert statement are not closed.

```sql
CREATE PROCEDURE [dbo].[spUpdateInventory]
@productId int,
@locationId int,
@quantityIncrement int

WITH NATIVE_COMPILATION, SCHEMABINDING
AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL=SNAPSHOT, LANGUAGE=N'English')
    UPDATE dbo.ProductInventory
        SET Quantity = Quantity + @quantityIncrement
            WHERE ProductId = @productId AND LocationId = @locationId

/*If zero rows were updated than this is insert of the new product for a given location*/
    IF @@rowcount = 0
        BEGIN
            IF @quantityIncrement < 0
                SET @quantityIncrement = 0
            INSERT INTO [dbo].[ProductInventory]
                (
                    [ProductId]
                    ,[LocationID]
                    ,[Quantity]
                )
                VALUES
                   (
                        @productId
                       ,@locationId
                       ,@quantityIncrement
        END
END;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16923b34-9fbb-86a2-071d-c4fa47e639ff
* Version Independent ID: 83127f7a-a6cd-0b63-a723-ee72f7511a6a
* Content: [Temporal Table Usage Scenarios - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-table-usage-scenarios?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/temporal-table-usage-scenarios.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/temporal-table-usage-scenarios.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@GCer-Hidenori -- thank you for helping improve this documentation.  I am addressing the article.
