### ISSUE TITLE
executed_count is missing

### ISSUE THREAD

**Issue by yorickbouma** [MicrosoftDocs/sql-docs#5671]
The column executed_count is missing from the catalog.executions view.

https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/integration-services/system-views/catalog-executions-ssisdb-database.md

**Comment by WilliamAntonRohm** [comment]
@yorickbouma -- thank you for your feedback.

@chugugrace -- please look into this issue.

**Comment by alittlesliceoftom** [comment]
Found this issue whilst exp same bug. Could you please share a definition?

**Comment by VanMSFT** [comment]
I've added the definition to some missing columns. Please feel free to let us know if there are any questions.

#reassign:VanMSFT
