### ISSUE TITLE
Miss align link to jar version

### ISSUE THREAD

**Issue by anniexudan** [MicrosoftDocs/sql-docs#5672]
[Enter feedback here]
This documentation redirects to a github page and it says the minimum recommended version in 1.6.6:

 
But the one in the maven repository for mssql jar (v8.4.1-jre8) says that the version is 1.6.5:

 
Please do advice for the exact version to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8816308-e8ba-e813-6607-473bd3e9aeeb
* Version Independent ID: 7724b453-99b2-4567-e0d1-6ccb9d83e83d
* Content: [Connecting using Azure Active Directory authentication - SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15)
* Content Source: [docs/connect/jdbc/connecting-using-azure-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/connecting-using-azure-active-directory-authentication.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@anniexudan Thanks for submitting feedback.

Version 8.4.1 of the Microsoft JDBC Driver for SQL Server was released on August 27, 2020. The current version of the Azure Active Directory Library for Java at that time was 1.6.5. Version 1.6.6 released on Sept 17, 2020. The "correct" version to use would be 1.6.5, which was tested with the JDBC driver during development. However, 1.6.6 is probably fine to use, too, (revision number increments are supposed to be backwards compatible) as long as you do not experience any issues with it.

Regards,
David

#please-close
