### ISSUE TITLE
How to use STRING_AGG with Azure Synapse -- a documentation wild good chase

### ISSUE THREAD

**Issue by swanderz** [MicrosoftDocs/sql-docs#5676]
from #5675, I learned that `STRING_SPLIT` is supported by Azure Synapse. Here is the steps that I went through to try and use it. @julieMSFT can you maybe point me in the right direction?

## 1. Visit 'STRING_SPLIT' page
I read the note one the [`STRING_SPLIT` page](https://docs.microsoft.com/en-us/sql/t-sql/functions/string-split-transact-sql?view=azure-sqldw-latest) that says,
> STRING_SPLIT requires the compatibility level to be at least 130. When the level is less than 130, SQL Server is unable to find the STRING_SPLIT function.
> To change the compatibility level of a database, refer to [View or Change the Compatibility Level of a Database](https://docs.microsoft.com/en-us/sql/relational-databases/databases/view-or-change-the-compatibility-level-of-a-database?view=azure-sqldw-latest).
## 2. Visit 'Change Compatibility Level of a Database' page
I click on the Change Compatibility Level of a Database link and see this error at the top.
>  The requested page is not available for Azure Synapse Analytics. You have been redirected to the newest product version this page is available for.
## 3. Google for correct page
Ouch! I decide leave the docs page and Google: "Azure Synapse compatibility level"
## 4. Visit 'Release Notes' page
The first result is the [Release Notes page](https://docs.microsoft.com/en-us/azure/synapse-analytics/sql-data-warehouse/release-notes-10-0-10106-0), I `CTRL+F` for compatibility which brings me to an update from July 2020 that says
> ## Compatibility Level support (GA)
> With this release, users can now set a database's compatibility  level to get the Transact-SQL language and query processing behaviors of  a specific version of the Synapse SQL engine. For more information, see  [sys.database_scoped_configurations](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-scoped-configurations-transact-sql?toc=/azure/synapse-analytics/sql-data-warehouse/toc.json&bc=/azure/synapse-analytics/sql-data-warehouse/breadcrumb/toc.json&view=azure-sqldw-latest) and [Alter Database Scoped Configuration](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql?toc=/azure/synapse-analytics/sql-data-warehouse/toc.json&bc=/azure/synapse-analytics/sql-data-warehouse/breadcrumb/toc.json&view=azure-sqldw-latest).
## 5. Visit 'Alter Database Scoped Configuration' & ``sys.database_scoped_configurations`` pages
From those pages I learn that my SQL pool's `DW_COMPATIBILITY_LEVEL` is set to 0 (by running `SELECT * FROM sys.database_scoped_configurations`).
## 6. Try to change setting
I thought I was in the clear when I ran this statement
```
ALTER DATABASE SCOPED CONFIGURATION SET DW_COMPATIBILITY_LEVEL = 130;
```
instead I get the response:
```
Compatibility Level '130' is not supported.: Supported compat levels are: [AUTO, 10, 20, 30].
```
I tried setting compatibility to `30`, but it still doesn't let me use the `STRING_SPLIT` function.

**Comment by swanderz** [comment]
#5376 seems related

**Comment by julieMSFT** [comment]
#reassign:julieMSFT

**Comment by swanderz** [comment]
`STRING_SPLIT` is supported but I was using it wrong. 🤦 . Thanks @MicrosoftDocs/sql-docs for helping me rubber duck debug team!

**Comment by julieMSFT** [comment]
Hi Anders, I was just going to ask how you were using it. Glad you found the answer. We have updated the doc to say you do not need to change to compatibility level for Azure Synapse. Are you good with me closing this issue?

**Comment by swanderz** [comment]
amazing. this is the developer experience/support I dream of. thanks!
