### ISSUE TITLE
Error in OS  options

### ISSUE THREAD

**Issue by jdanton** [MicrosoftDocs/sql-docs#5682]
The typical scenario is to use cross-cluster migration of Always On availability groups for OS upgrade to **Windows 8** or Windows Server 2012. For more information, see Cross-Cluster Migration of Always On Availability Groups for OS Upgrade.

AFAIK, Windows 8 does not support clustering and should be removed. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc9b3581-d795-49c4-6538-451c80cee05b
* Version Independent ID: d572af76-7e1f-78f0-c6c4-1421a421bdaf
* Content: [Take an Availability Group Offline (SQL Server) - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/take-an-availability-group-offline-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/take-an-availability-group-offline-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/take-an-availability-group-offline-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@jdanton -- thank you for your feedback.

@MashaMSFT -- please look into this issue.

**Comment by cawrites** [comment]
@jdanton thank you for contacting Microsoft. I have reviewed your feedback and made an adjustment to the content, It will appear in the next content refresh.

**Comment by cawrites** [comment]
#please-close
