### ISSUE TITLE
MSDTC with SQL Server 2019 Linux and Windows host

### ISSUE THREAD

**Issue by cklepeis** [MicrosoftDocs/sql-docs#5690]
It's unclear / confusing how to properly setup MSDTC when using SQL Server 2019 Linux Container and a Windows host.

I want to use SQL Server 2019 Linux container for my development environment. When I run an integration test project via Visual Studio I received MSDTC communication errors.

In this article it states: 

> For SQL Server outside of a container or for non-root containers, a different ephemeral port, such as 13500, must be used in the container and traffic to port 135 must then be routed to that port. You would also need to configure port routing rules within the container from the container port 135 to the ephemeral port.

At the bottom of the article it states that SQL Server 2019 does not run as root... so this is required for me. I'm using docker-compose and based on this article adjusted the port to: `135:13500` - port 135 for the host and port 13500 for the container. I believe this would handle the port routing for me? By "ephemeral" port does this mean the host or container port? Would be better if that was clarified. Still getting MSDTC communication errors. I posted my issue and docker-compose snippet here https://stackoverflow.com/questions/64745789/msdtc-configuration-issues-with-sql-server-in-docker-linux-and-windows-host hoping for help.

The following paragraph:

> Also, if you decide to map the container's port 135 to a different port on the host, such as 13500, then you have to configure port routing on the host. This enables the docker container to participate in distributed transactions with the host and with other external servers.

... the last sentence is confusing... it makes it sound like its required to use a container port other than 135 for the host port for DTC between the host and the external server.

Unclear how to properly do any (necessary?) port routing. I'm stuck on just getting it working. The link in the article to Configure port routing (https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-msdtc?view=sql-server-ver15#configure-port-routing) does not help people using SQL Server 2019 container since we do not have sudo nor iptables in that container. If port routing is necessary in windows, would be nice to see an example for that as well (netsh?)

I can't find a sample / details anywhere on how to setup MSDTC when using SQL Server 2019 Linux container and a windows host.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c998e1ee-e33d-1e74-291b-565239adf112
* Version Independent ID: 0318ca75-d26e-243b-b322-6412b9521916
* Content: [Distributed transactions (MSDTC) with SQL Server on Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-msdtc-docker?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-configure-msdtc-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-msdtc-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@cklepeis -- Chris, thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
@amvin87 - Hey Amit, can you please take a look at this and see if you can clarify? Thanks!

#reassign:amvin87

**Comment by VanMSFT** [comment]
@amvin87 - Hey Amit, when you have a chance, can you also check on this? Thanks!

**Comment by tejasaks** [comment]
First of all, I agree that the documentation on enabling MSDTC for containers needs a pretty substantial update. I have tried to answer this question at following post as best as i can. Please let me know if this works for you. Please note that i have shown configuration on using SQL containers on Linux hosts as using Linux containers on Windows hosts is essentially experimental. I have not validated some of the routing steps on Windows host for Linux containers and i am not sure they would work. 

https://github.com/microsoft/mssql-docker/issues/492#issuecomment-683637807

**Comment by VanMSFT** [comment]
Closing this as this has been answered. We are planning to rework the MSDTC portion of our docs for containers, and will track internally.

**Comment by silverl** [comment]
I would like to see this issue re-opened. The OP asked about a Windows host with a Linux container. The answer from @VanMSFT covers Linux host and Linux container, dismissing the use of a Windows host as "experimental". The OPs question has not been answered, but dismissed.

**Comment by WilliamAntonRohm** [comment]
@silverl -- Larry, thank you for your considered feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @silverl - Thanks for the feedback. We are not dismissing yours or the OP's concerns, but rather there is currently no documentation we have right now that walks you through MSDTC using a Linux container on a Windows host. This is something we will plan to work into our documentation in the future, and it's being tracked internally. Thus, we have closed this issue that is specific to documentation

If you have a specific product issue during testing the configuration, you may find or submit your issue here:

[SQL Server Feedback](https://feedback.azure.com/forums/908035-sql-server)

**Comment by tejasaks** [comment]
While we don't have the container deployed on VM documentation yet, following documentation should help you set up MSDTC on containers deployed on K8s, which is what probably is most important production use case. Once MSDTC is enabled on containers deployed on K8s, it should ideally work with your Windows client as well. 

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-msdtc-docker?view=sql-server-ver16

**Comment by VanMSFT** [comment]
Adding @rwestMSFT to comment as they've been working on MSDTC updates.

**Comment by rwestMSFT** [comment]
#please-close

**Comment by silverl** [comment]
Either my Google-fu has failed me or it is just not possible.

Windows always binds the RPC service to port 135 on all available interfaces. While you can configure a separate range of high ports for dynamic port allocation for conversations with participating external services, you cannot change that basic port 135 binding. Windows uses port 135 for so many things, it would likely break most of Windows to mess with it.

I have found no reference that indicates that Windows supports any kind of host-specific port remapping strategy that would enable us to teach the Windows host to call an external service on a different port than 135 for the RPC discovery process.

So if we cannot change Windows' binding of port 135, and if we cannot teach Windows to talk to an external service on an alternative RPC port for the purposes of SQL Server/MSDTC support, then I think we're well and truly stuck here.

If y'all know anyone in the core Windows OS team who could corroborate this conclusion, that'd be nifty.

**Comment by tejasaks** [comment]
I assume that the intent is to deploy a SQL on Linux container directly (via docker desktop for Windows) on a Windows host, which is not a production supported scenario. If you intend to deploy a Linux VM on a Windows machine and host the SQL container in that linux VM, it's completely different VM than the host machine and the limitation of port 135 binding does not apply.

**Comment by tejasaks** [comment]
@amvin87 as FYI on this thread.

**Comment by silverl** [comment]
@tejasaks You are correct. And this is for our developer workstations, so it's definitely a development environment, not a production environment.  I understand you're saying that SQL on Linux container on a Windows host is not supported.

**Comment by tejasaks** [comment]
Considering the lack of support for SQL containers on Windows, it's not a well-tested configuration. As far as I can tell, we have a conflicting requirement where RPC service on Windows host and SQLPAL, both need to listen on port 135 to route RPC requests to its own endpoint mapper for name resolution which is impossible to achieve. So, I don't see how we can make this work.
