### ISSUE TITLE
Break in text

### ISSUE THREAD

**Issue by therealjbschueler** [MicrosoftDocs/sql-docs#5693]
[Enter feedback here]
In the following text fragment, there should not be a space after ATTR_.
an Attribute of SQL_ATTR_ TRACEFILE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da688271-2074-259b-3249-4b915da2712c
* Version Independent ID: f748db20-7142-ca0b-f873-6b5932e20917
* Content: [SQLSetConnectAttr Function - SQL Server](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetconnectattr-function?view=sql-server-ver15)
* Content Source: [docs/odbc/reference/syntax/sqlsetconnectattr-function.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/syntax/sqlsetconnectattr-function.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@therealjbschueler -- thank you for catching this typo.  I am updating the article.
