### ISSUE TITLE
Does SQL Server 2019 license comes free with windows server 2019 essentials or do i have to buy a seperate License for it?

### ISSUE THREAD

**Issue by Harshitjain188** [MicrosoftDocs/sql-docs#5695]
I want to know if Windows Server 2019 Essentials comes with SQL server 2019 (License) or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09beb1a-92a9-4335-511c-395ba64c875b
* Version Independent ID: 8f43fca3-43d7-a2e4-1469-bf17f14d9ac8
* Content: [SQL Server 2019: Hardware & software requirements - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15?view=sql-server-ver15)
* Content Source: [docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@Harshitjain188 -- thank you for your question.  

@MikeRayMSFT -- please look into this issue, as I haven't found a definitive answer.

**Comment by pmasl** [comment]
Windows Server Essentials (formerly Small Business Server) doesn’t include any SQL Server license. Licensing topics aren’t covered in the product technical documentation. To find out more about SQL Server licensing, please see https://www.microsoft.com/en-us/sql-server/sql-server-2019-pricing.

**Comment by MikeRayMSFT** [comment]
Thank you, @pmasl
