### ISSUE TITLE
SSIS -- Package mssql-server-is not found on Centos 8

### ISSUE THREAD

**Issue by jayped007** [MicrosoftDocs/sql-docs#5696]
[Enter feedback here]
A failure is currently occurring when attempting to install SSIS on a Centos 8 machine where MS SQL Server 2019 was successfully installed (using the mssql-server and mssql-tools and the unixODBC-devel packages).  The failure message is "no match for argument: mssql-server-is" error.  Details are provided below.

This occurred on November 9, 2020.

NOTE: because this is Centos 8, "dnf" was used instead of "yum".
NOTE: the mssql-server package was installed using dnf without any problem

The documentation I am following is:
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-ssis?view=sql-server-ver15

Here was the command that attempted to install SSIS and its failure message:

sudo dnf install -y mssql-server-is
Last metadata expiration check: 0:08:40 ago on Sun 08 Nov 2020 08:42:56 AM EST.
No match for argument: mssql-server-is

The following shows that mssql-server is a known package and was installed

$ sudo dnf install -y mssql-server
Last metadata expiration check: 0:08:49 ago on Sun 08 Nov 2020 08:42:56 AM EST.
Package mssql-server-15.0.4073.23-4.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

The following were the commands used to establish the mssql-server package, etc:

sudo curl https://packages.microsoft.com/config/rhel/8/mssql-server-2019.repo -o /etc/yum.repos.d/mssql-server-2019.repo

sudo  curl https://packages.microsoft.com/config/rhel/8/prod.repo -o /etc/yum.repos.d/msprod.repo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41654ae8-cbd1-c5dd-f15a-69466a765fda
* Version Independent ID: 94311dce-80f0-b8ce-7296-b595ff50d640
* Content: [Install SQL Server Integration Services on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-ssis?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-setup-ssis.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-ssis.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @lrtoyou1223
* Microsoft Alias: **lle**

**Comment by VanMSFT** [comment]
Hi @jayped007 - The SSIS package is not available with RHEL 8. Please see the following release notes: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes?view=sql-server-ver15#package-details
