### ISSUE TITLE
nested CTEs vs. multipe CTEs defined within a nonrecursive CTE

### ISSUE THREAD

**Issue by swanderz** [MicrosoftDocs/sql-docs#5698]
In Azure Synapse, how does one define a CTE that references another CTE without using `WITH` twice?
Related question: what exactly constitutes a `CTE query definition`? Is it different than a single `CTE`?
cc: @alittlesliceoftom @nandanhegde15 @julieMSFT 

In the [Features and Limitations of Common Table Expressions in Azure Synapse Analytics](https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver15#guidelines-for-creating-and-using-common-table-expressions?WT.mc_id=DP-MVP-5003930) section of  [docs/t-sql/queries/with-common-table-expression-transact-sql.md](https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver15#features-and-limitations-of-common-table-expressions-in--and-?WT.mc_id=DP-MVP-5003930) there are two bullet points that confuse me:

> - Multiple CTE query definitions can be defined in a CTE.
> - Specifying more than one WITH clause in a CTE is not allowed. For example, if a CTE query definition contains a subquery, that subquery cannot contain a nested WITH clause that defines another CTE.

The [Guidelines for Creating and Using Common Table Expressions](https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver15#guidelines-for-creating-and-using-common-table-expressions) section has the same information:
> - Multiple CTE query definitions can be defined in a nonrecursive CTE ...
> - Specifying more than one WITH clause in a CTE is not allowed ...

**Comment by swanderz** [comment]
did some playing around, and I think have an example of something worth being added to a the page linked above. Happy to make the PR if you agree. Basically it wasn't immediately clear from reading the docs whether it was possible to have CTEs reference one another inside a single `WITH` statement. Now I've figured it out...

this works
```sql
WITH att_a AS (
    SELECT name, id
    FROM [ajs_stg].[attributes]
    WHERE name = 'Campaign'
),
att_b AS (
    SELECT name, id
    FROM att_a
    WHERE id = 122529495
)
SELECT * FROM att_b;
```
but this doesn't work
```sql
WITH att_b AS (
    WITH att_a AS (
        SELECT name, id
        FROM [ajs_stg].[attributes]
        WHERE name = 'Campaign'
    )
    SELECT name, id
    FROM att_a
    WHERE id = 122529495
)
SELECT * FROM att_b;
```

**Comment by WilliamAntonRohm** [comment]
@swanderz -- Anders, thank you for your feedback and research.

@VanMSFT -- Van, please review the above suggestion and if possible give Anders the go-ahead for a new PR.

**Comment by VanMSFT** [comment]
Hi @swanderz! Thanks for the feedback and testing. Please go ahead and submit the PR, and we will validate it. We appreciate your help with our documentation! I'll close this GitHub Issue for now, since you found the answer. We look forward to the PR! Thanks again!
