### ISSUE TITLE
ACCELERATED_DATABASE_RECOVERY database option does not mention it requires exclusive access to the DB

### ISSUE THREAD

**Issue by danrcarollo** [MicrosoftDocs/sql-docs#5699]
While to to run this:

ALTER DATABASE [DB] SET ACCELERATED_DATABASE_RECOVERY = ON

I noticed it hung.  It appears the only way I could run was to have exclusive access to the database.
However, neither the feature page nor it's parent page (ALTER DATABASE) mention this requirement:

https://docs.microsoft.com/en-us/sql/relational-databases/accelerated-database-recovery-management?view=sql-server-ver15
https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d6d147-a7a7-cd75-13fb-4f4f72a16a15
* Version Independent ID: bb4f71b0-3103-06af-0560-e28860c752bc
* Content: [Manage accelerated database recovery - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/accelerated-database-recovery-management?view=sql-server-ver15)
* Content Source: [docs/relational-databases/accelerated-database-recovery-management.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/accelerated-database-recovery-management.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@danrcarollo -- Dan, thank you for your feedback and solution.

@MashaMSFT -- Masha, please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @danrcarollo , thanks so much for bringing this to our attention! I have processed a change to add a note to the alter database article, and it should be live later this week, or possibly next.

I'm going to close out this Git Issue for the time being but please feel free to comment should you need anything further.

Thanks again for improving our docs! I hope you have a wonderful rest of your day :) 
Masha from the SQL Docs team
