### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jrmclennan** [MicrosoftDocs/sql-docs#5700]
Second sentence, there is a typo. "Use **is** to create conditions that contain condition expressions."

I think you meant **it**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45242659-a731-0b7f-7cce-73856b350391
* Version Independent ID: 9a138c9c-3379-03cc-51ec-dff50c6efa38
* Content: [Administer servers using Policy-Based Management - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/administer-servers-by-using-policy-based-management?view=sql-server-ver15)
* Content Source: [docs/relational-databases/policy-based-management/administer-servers-by-using-policy-based-management.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/policy-based-management/administer-servers-by-using-policy-based-management.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@jrmclennan -- thank you for catching this.  I am updating the article.
