### ISSUE TITLE
Misleading bullet points

### ISSUE THREAD

**Issue by lukedd** [MicrosoftDocs/sql-docs#5701]
Hi,

The three bullet points at the top of this article are intended to be alternatives: only one of them will be true for a given data source.

I think this is not very clear from the wording.  The natural reading is that all three bullet points will be true.  The text would be a lot clearer if it was made explicit that these were alternatives, eg:

> Depending on the data source, committing or rolling back a transaction will have one of the following effects on cursors and access plans:
> * All cursors are closed, and access plans for prepared statements on that connection are deleted; OR
> * All cursors are closed, and access plans for prepared statements on that connection remain intact; OR
> * All cursors remain open, and access plans for prepared statements on that connection remain intact.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f479634-bff2-0f37-ed42-578478f05b10
* Version Independent ID: 4469052f-5f65-a799-418a-ddeea342bd99
* Content: [Effect of Transactions on Cursors and Prepared Statements - SQL Server](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/effect-of-transactions-on-cursors-and-prepared-statements?view=sql-server-ver15)
* Content Source: [docs/odbc/reference/develop-app/effect-of-transactions-on-cursors-and-prepared-statements.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/develop-app/effect-of-transactions-on-cursors-and-prepared-statements.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@lukedd -- Luke, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
