### ISSUE TITLE
Clicking links in 'Edge constraint' menu group does not work (redundant links)

### ISSUE THREAD

**Issue by NeuroXiq** [MicrosoftDocs/sql-docs#5703]
On the left side menu, there is a menu item "Edge constraint". 
Full path to this item: Database design -> Tables -> Edge constraints

Edge constraints has 5 items:
* Edge Constraint 
* Create
* Edit 
* Modify
* View

When I click on Create/Edit/Modify/View they redirect me to the first one: "Edge Constraint" page. That means that clicking on 
Craete/Edit/Modify/View has not affect, the do not change page. I think that this links are reduntant because there are no content and all informations are in "Edge Constraint" :)

Regards
Marek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0840e04-b52d-2c5f-197d-26bec998fcaa
* Version Independent ID: 40ca3965-4f80-cbb3-839c-3244a536675e
* Content: [Graph edge constraints - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/graph-edge-constraints?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/graph-edge-constraints.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/graph-edge-constraints.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @shkale-msft
* Microsoft Alias: **shkale**

**Comment by WilliamAntonRohm** [comment]
@NeuroXiq -- Marek, thank you for bringing those to our attention.  I am looking into these menu item links.
