### ISSUE TITLE
SQL Backup to URL does not work towards a container with immutable storage 

### ISSUE THREAD

**Issue by AdelaManea** [MicrosoftDocs/sql-docs#5704]
Hello, 

I am a support engineer that had a customer attempt to use SQL backup to URL to a storage container with a legal hold on it. Based on what the cx has shown me on his Portal, it seems like when the SQL backs up to a container, it first creates a blob of size 0kb to which it then attempts to add blocks. Because the container is immutable, it does not allow the subsequent writes to that blob and therefore the backup fails. I could not find anything about this in the Storage documentation or the SQL one, but I did see customers bring this concern on other platforms such as Reddit and Stackoverflow. I believe we would all benefit from this info being publicly available on the MS docs (this support request ran for quite a long time because we did not know this). I will make the same request to the following page : 

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-immutable-storage#faq

Thank you very much for your hard work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc04e819-4cfd-5b23-404b-8d4ed41afd21
* Version Independent ID: d254a232-e05d-0d52-0e25-7e83866f12e6
* Content: [SQL Server Backup to URL - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-ver15#blockbloborpageblob)
* Content Source: [docs/relational-databases/backup-restore/sql-server-backup-to-url.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/sql-server-backup-to-url.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@AdelaManea -- thank you for your well-researched feedback.

@MashaMSFT -- please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @AdelaManea , thanks for bringing this to our attention! We actually processed a change at the beginning of October to add that immutable storage is [not supported](https://docs.microsoft.com/sql/relational-databases/backup-restore/sql-server-backup-to-url#limitations): 

![image](https://user-images.githubusercontent.com/32783170/99738196-c6884f80-2a7e-11eb-8e62-4cfa55caedb0.png)

This may not have been readily apparent due to the timing but does this address your concern?

Thanks!
Masha from the SQL Docs team

**Comment by AdelaManea** [comment]
Hello,

Yes, it does. I highly appreciate your quick work on this and I am sure so will our customers.

Thank you very much!

Adela Manea
Support Engineer
POD Azure
Customer Services and Support
Work Phone: +40 (31) 1331073
adela.manea@microsoft.com<mailto:adela.manea@microsoft.com>
Normal Working hours: 9:00 AM - 6:00 PM EET Monday to Friday
[Azu re]
Tech Lead | Carlos Nogueira (carlos.nogueira@microsoft.com<mailto:carlos.nogueira@microsoft.com>) +49 (89) 31764358
Team Manager | Gabriel Ion (gabriel.ion@microsoft.com<mailto:gabriel.ion@microsoft.com>) +40 (31) 1330219
[Microsoft]
If you have any feedback about my work, please let either me or my manager Gabriel Ion know at gabriel.ion@microsoft.com<mailto:gabriel.ion@microsoft.com>
If you have any support request issues and I am unavailable, please do contact azurebu@microsoft.com <mailto:azurebu@microsoft.com> with your case ID and details.
