### ISSUE TITLE
sys.dm_io_virtual_file_stats does not have a database_name column (docs says it does)

### ISSUE THREAD

**Issue by BrentOzar** [MicrosoftDocs/sql-docs#5705]
On this page:
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-io-virtual-file-stats-transact-sql?view=sql-server-ver15

The documentation says database_name is a column in this function. It's not, at least not in SQL Server. Needs to have the "Does not apply to:: SQL Server 2008 through SQL Server 2019." labeling on it that the other unavailable columns have. Thanks!

**Comment by WilliamAntonRohm** [comment]
@BrentOzar -- Brent, thank you for your feedback.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review [private PR 17873](https://github.com/MicrosoftDocs/sql-docs-pr/pull/17873).
