### ISSUE TITLE
Incorrect usage of term "kilo" - it should be "kibi"

### ISSUE THREAD

**Issue by grahamfurner** [MicrosoftDocs/sql-docs#5706]
The document states that a page is "8-KB" and "8 kilobytes" in size whereas a page in SQL is actually 8 Kibibytes (KiB) (or 8096 bytes).

Similarly, the use of the term "megabyte" is incorrect and should be changed to MiB or mibibyte.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2881d6-51e3-3eee-a6df-911463517b54
* Version Independent ID: 9295888e-8884-7d3f-7bd4-2bdeccae6962
* Content: [Pages and Extents Architecture Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/pages-and-extents-architecture-guide?view=sql-server-ver15)
* Content Source: [docs/relational-databases/pages-and-extents-architecture-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/pages-and-extents-architecture-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@grahamfurner -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@grahamfurner -- you are correct.  Upon investigation, this set of Microsoft documentation is not yet using the term kibibyte, so I am leaving the article as-is.

You're welcome to add this suggestion here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
