### ISSUE TITLE
Wrong version info in Applies to section

### ISSUE THREAD

**Issue by andreymakarov** [MicrosoftDocs/sql-docs#5708]
It says "SQL Server (all supported versions)" but actually it should be "SQL Server 2016 and later"

**Comment by WilliamAntonRohm** [comment]
@andreymakarov -- thank you for your feedback.  Which article are you referring to?

**Comment by andreymakarov** [comment]
All articles about JSON support in sql server. To name a few:
https://docs.microsoft.com/en-us/sql/relational-databases/json/json-path-expressions-sql-server?view=sql-server-ver15
https://docs.microsoft.com/en-us/sql/relational-databases/json/format-json-output-automatically-with-auto-mode-sql-server?view=sql-server-ver15
https://docs.microsoft.com/en-us/sql/relational-databases/json/remove-square-brackets-from-json-without-array-wrapper-option?view=sql-server-ver15
and so on except the only first one 
https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-ver15 - this one is correct.

**Comment by WilliamAntonRohm** [comment]
@andreymakarov -- thank you for clarifying.  I am looking into this set of articles.
