### ISSUE TITLE
SQL Server *or* Azure Data Studio

### ISSUE THREAD

**Issue by offthewoll** [MicrosoftDocs/sql-docs#5717]
The prerequisites section provides the impression that **both** SQL Server and Azure Data Studio are required since they're listed as separate bullet points even though only one of them is necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75ef50ee-113c-d60b-d325-e0b2c8b3ff8c
* Version Independent ID: 22a0fe29-9168-fe54-c022-c03f6db7ac5c
* Content: [Insert Python dataframe into SQL table - SQL machine learning](https://docs.microsoft.com/en-us/sql/machine-learning/data-exploration/python-dataframe-sql-server?view=sql-server-ver15)
* Content Source: [docs/machine-learning/data-exploration/python-dataframe-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/data-exploration/python-dataframe-sql-server.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@offthewoll -- Avi, thank you for your clarification.  I am updating the article.

**Comment by cawrites** [comment]
@WilliamAntonRohm @offthewoll  the mention of SQL Server as a data source is correct. Azure Data Studio is a tool that is used to run the Python Code sample. These two prerequisites are not the same.  You can run Python without it, for this example it is required as it is referred to in the documentation. @offthewoll what is your understanding when you read it?

**Comment by garyericson** [comment]
The article is correct as-is. The article says that "SQL Server" is required, but I believe Avi is reading this as "SQL Server Management Studio". SSMS is an alternative to Azure Data Studio, so both of those would not be required. But SQL Server itself is required, which is what the article states.

#please-close
