### ISSUE TITLE
Python37/Scripts

### ISSUE THREAD

**Issue by mouradbka** [MicrosoftDocs/sql-docs#5718]
I had issues to find the folder python37/Scripts where I can run pip install.  

I found it using "dir Scripts /s /p" in the command line. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95454cf7-3691-e4eb-d8c6-b7986fcd490b
* Version Independent ID: 84a42231-fc84-e831-a9a8-18cb86f3cfb9
* Content: [Step 1: Configure pyodbc Python environment - SQL Server](https://docs.microsoft.com/en-us/sql/connect/python/pyodbc/step-1-configure-development-environment-for-pyodbc-python-development?view=sql-server-ver15)
* Content Source: [docs/connect/python/pyodbc/step-1-configure-development-environment-for-pyodbc-python-development.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/python/pyodbc/step-1-configure-development-environment-for-pyodbc-python-development.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@mouradbka -- thank you for your helpful feedback.

@David-Engel -- please look into this issue.

**Comment by David-Engel** [comment]
Two possible default Python paths are already noted in step 2 when verifying your Python installation. You should already know your path from step 2 so there is no need for additional documentation on how to find it in the next step.

Regards,
David

#please-close
