### ISSUE TITLE
Typo:  "Trueand False" -> " True and False."

### ISSUE THREAD

**Issue by NeuroXiq** [MicrosoftDocs/sql-docs#5719]
Primary Key section contains following sentence:
 Indicates whether the column is a primary key. Possible values are Trueand False.
at the end: "Trueand False" but should be "True and False" 
:)

Regards
Marek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d42fb53-5f58-ed2e-f91b-cecf4c9fecee
* Version Independent ID: c602a50c-56cb-2252-151d-09a0a9a6bb8a
* Content: [Column Properties (General Page) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/column-properties-general-page?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/column-properties-general-page.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/column-properties-general-page.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@NeuroXiq -- Marek, thank you again for your keen eye.  I am updating this article.
