### ISSUE TITLE
sql server

### ISSUE THREAD

**Issue by naouel232** [MicrosoftDocs/sql-docs#5722]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7044c28-1682-15db-6add-77d185262f3c
* Version Independent ID: e42f8fe5-da01-d793-a799-d7102bea5eec
* Content: [Create a Full Database Backup - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/create-a-full-database-backup-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/backup-restore/create-a-full-database-backup-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/create-a-full-database-backup-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@naouel232 -- thank you for your feedback.  Please clarify your task or question.
