### ISSUE TITLE
Augment SLES install section

### ISSUE THREAD

**Issue by bwgartner** [MicrosoftDocs/sql-docs#5727]
Please

* change section title to more general "Install tools on SLES"
* then in step 1
  - add sub-steps/choices:
    -  using existing "addrepo" designation citing major release 12
    -  clone "addrepo" and s/12/15/ citing (other) supported major release 15
  - "keys" command straddles both variants
* steps 2-3 can be used in either scenario

This works fine and was even demo'd this during recent PASS Summit (virtual event)

**Comment by WilliamAntonRohm** [comment]
@bwgartner -- Bryan, thank you for your detailed feedback.  Are you following a particular docs.microsoft.com article?

**Comment by bwgartner** [comment]
> @bwgartner -- Bryan, thank you for your detailed feedback. Are you following a particular docs.microsoft.com article?

Was just referring to this particular document ( https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15#SLES) as part of the demo (documenting the flow here -https://github.com/bwgartner/PASS-Summit/tree/main/2020/Demo-Ensuring_availability_of_SQL_Server_in_Azure) and showed how using repo 15 instead of 12 (for the SLES15-SP1 deployment) worked fine to get sqlcmd installed/running.

**Comment by WilliamAntonRohm** [comment]
@bwgartner -- Bryan, thank you for clarifying.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
@bwgartner - Hi Bryan! Thanks for the feedback. We really appreciate it. Regarding adding SLES 15 to the article, we will do this once SQL Server on Linux supports SLES 15. Although some features may work, we don't add those features in our documents until it is supported.

https://docs.microsoft.com/sql/linux/sql-server-linux-release-notes-2019?view=sql-server-ver15#supported-platforms

@tejasaks - FYI
