### ISSUE TITLE
Lesson 5-2: Enable and configure package configurations

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/sql-docs#5729]
---
**Issue moved from MicrosoftDocs/feedback#3264**
- Please respond to @Joseph-McFadden.

---

_From @Joseph-McFadden on Thursday, November 12, 2020 6:09:59 PM_

**Describe the bug**
https://docs.microsoft.com/en-us/sql/integration-services/lesson-5-2-enabling-and-configuring-package-configurations?view=sql-server-ver15

Visual Studio 2019.  In "Enable package configurations" step 2 to "Convert to Package Deployment Model" dialog fails.  Reason is  the presence of "project connection manager" created in Lesson 1-3.

To proceed with "Convert to Package Deployment Model" the connection manager had to be delete.  After conversion had to manually re-add connections to each OLE DB connection manager.

Is this a bug or work around?  I leave it to you to decide.

**To Reproduce**

**Expected behavior**

**Screenshots**
Project (menu) --> Convert to Package Deployment Model
![image](https://user-images.githubusercontent.com/16122259/98977640-104cc500-24d6-11eb-8e42-9adec28e6310.png)

![image](https://user-images.githubusercontent.com/16122259/98976997-49386a00-24d5-11eb-945e-62fd4304e0ae.png)

Error message preventing conversion to Package Deployment Model
![image](https://user-images.githubusercontent.com/16122259/98977032-581f1c80-24d5-11eb-8644-451a96afd39f.png)

Connection Managers present in Project SSIS Tutorial created in 
![image](https://user-images.githubusercontent.com/16122259/98977327-bc41e080-24d5-11eb-9201-d75c7b0f2dd1.png)

![image](https://user-images.githubusercontent.com/16122259/98978172-cadcc780-24d6-11eb-9f7f-cf105c0a44f7.png)

The lookup transformations and OLE DB destination are subsequently broke.
![image](https://user-images.githubusercontent.com/16122259/98978323-08d9eb80-24d7-11eb-9fe2-39cb87e0a52d.png)

The OLE DB Connection Manager for the three objects had to reset.
![image](https://user-images.githubusercontent.com/16122259/98978479-463e7900-24d7-11eb-8e76-840e652667bb.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3264**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Thursday, November 12, 2020 6:10:00 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by WilliamAntonRohm** [comment]
@Joseph-McFadden -- Joseph, thank you for your detailed feedback.

@chugugrace -- Grace, please look into this issue.

**Comment by chugugrace** [comment]
@Joseph-McFadden can you check the which step you added or configured the project scope connection manager? Package scope connection managers should work with "convert to package deployment model". As in package deployment model, there is no concept of "project scope".

**Comment by VanMSFT** [comment]
Closing this as there hasn't been any responses for a while.
