### ISSUE TITLE
Redundant text 

### ISSUE THREAD

**Issue by smitpatel** [MicrosoftDocs/sql-docs#5739]
"Assembly (CLR) aggregate functions" repeated multiple times in the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c893780-4b8c-b3e5-8826-5dd1353f686e
* Version Independent ID: cb8916fd-a44a-9969-76d6-cf0214efdc86
* Content: [Synonyms (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/synonyms/synonyms-database-engine?view=sql-server-ver15)
* Content Source: [docs/relational-databases/synonyms/synonyms-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/synonyms/synonyms-database-engine.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@smitpatel -- Smit, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
