### ISSUE TITLE
Creating Database credential is only possible if you specify the storage account Key.  

### ISSUE THREAD

**Issue by andrehass** [MicrosoftDocs/sql-docs#5741]
When creating Database credentials in Synapse Analytics, it is only possible if you specify the Storage Account key. It does not work when specifying the SAS key. 

The option WITH IDENTITY = 'SHARED ACCESS SIGNATURE'  Confuses customers as it make they think they need to use a SAS key instead.  They need to provide a storage key and NOT The 'SHARED ACCESS SIGNATURE'   SAS Key. 

SHARED ACCESS SIGNATURE

This example 
CREATE DATABASE SCOPED CREDENTIAL CSAready
WITH IDENTITY = 'anything', 
SECRET = 'S1IIoEtF94OP3MY*************************i*************FyB5Dpy7K9w0XQ==' 

WITH IDENTITY parameter can be really anything. In the documentation SHARED ACCESS SIGNATURE is confusing.

**Comment by WilliamAntonRohm** [comment]
@andrehass -- thank you for your considered feedback.  Are you following a particular docs.microsoft.com article?

**Comment by WilliamAntonRohm** [comment]
#reassign:WilliamAntonRohm
