### ISSUE TITLE
Link to documentation describing how to set permissions on SQL data folder

### ISSUE THREAD

**Issue by alansingfield** [MicrosoftDocs/sql-docs#5756]
You have a note stating "After moving files, the SQL Server service account must have permission to access the files in new file folder location."

Can you add a link to this document which explains what needs to be done:
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-file-system-permissions-for-database-
engine-access?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9423e4-0573-7564-3f58-2a8df9a11d9f
* Version Independent ID: 5b88aa32-b6f7-e8eb-806f-fd331ed43133
* Content: [Move System Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/move-system-databases?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/move-system-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/move-system-databases.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@alansingfield -- Alan, thank you for your feedback.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
