### ISSUE TITLE
A lower version of this product has been detected

### ISSUE THREAD

**Issue by JamieL22** [MicrosoftDocs/sql-docs#5759]
SQL Server Management Studio is supporting the msodbc17 driver from SSMS version 18.7.1.  Despite this most recent version, the msodbc17 setup for SQL Server is stating the product from SSMS 18.7.1 is a lower version of the msodbc library.  Without reinstalling SSMS, is there a way to tell whether the upgrade is going to break the SSMS 18.7.1?
Can the error message be updated to say something more appropriate.
"Your version of msodbc17 is lower than the one your are installing.  Updating your version will not break your current installation."  
I doubt it can be said that way so - maybe a warning - "hey, it usually works.  take your chances".
I find it discomforting to see this message on the latest and greatest version of SSMS 18.7.1.   Perhaps SSMS could be updated?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36a1d7f-a410-b597-0eb7-98212934fb0e
* Version Independent ID: e706f2bd-e051-fcff-7c3d-2ef3d9f80e87
* Content: [Download ODBC Driver for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/download-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/download-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@JamieL22 -- Jamie, thank you for your feedback.  This repo is solely for documentation issues, and that error message is from the SSMS product itself.  Please add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
