### ISSUE TITLE
2019 replication of logins, jobs, meta

### ISSUE THREAD

**Issue by distributorofpain** [MicrosoftDocs/sql-docs#5761]
2019 now copies logins/jobs/meta information in an AG ( i tested this ) by default now, but only for new AGs.  Doesnt work for existing AGs that are upgraded, so it would be nice to see information on how to enable an existing AG as well.  Both are missing from this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19da7a75-ffd3-adb4-1abf-084c3dff1aeb
* Version Independent ID: 6e99fd96-00f9-abfa-ba3b-cbb424ed6cc4
* Content: [Manage job logins for databases in an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/logins-and-jobs-for-availability-group-databases?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/logins-and-jobs-for-availability-group-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/logins-and-jobs-for-availability-group-databases.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@distributorofpain -- Brent, thank you for your feedback.

@MashaMSFT -- Masha, please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @distributorofpain , thanks so much for your feedback! I agree, there are a few opportunities for us to improve this article. I've created an internal work item to review and refresh it [1771657](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1771657) and added it to our backlog to be addressed per priority. 

I'm going to close out this Git Issue for the time being but please feel free to comment should you need anything further in the meantime. 

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
