### ISSUE TITLE
Doc errors in the "Grant access to the custom Python installation folder" section

### ISSUE THREAD

**Issue by nielsberglund** [MicrosoftDocs/sql-docs#5765]
The instructions for granting access to the SQL Launchpad user is incorrect. When granting access to the default instance you need to omit the instance name, i.e. $MSSQLSERVER.  If you run the code as is:

`icacls "%PYTHONHOME%" /grant "NT Service\MSSQLLAUNCHPAD$MSSQLSERVER":(OI)(CI)RX /T`

you get an error like so: 

`The trust relationship between this workstation and the primary domain failed. Successfully processed 0 files; Failed processing 1 files`.

However if you execute without $MSSQLSERVER: 

`icacls "%PYTHONHOME%" /grant "NT Service\MSSQLLAUNCHPAD":(OI)(CI)RX /T`

it works fine.

You do need to include the instance name for any non-default instances though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f107052-ed91-e275-b171-788afe18194e
* Version Independent ID: 840bc864-f103-b15d-8340-3e12170ac569
* Content: [Install Python custom runtime - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/install/custom-runtime-python?view=sql-server-ver15)
* Content Source: [docs/machine-learning/install/custom-runtime-python.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/install/custom-runtime-python.md)
* Product: **sql**
* Technology: **machine-learning-services**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@nielsberglund Thank you for pointing out this issue. We will look into it and get back to you as soon as possible.

**Comment by dphansen** [comment]
@nielsberglund We have confirmed the doc bug. We will update the documentation as soon as possible (along with some other updates). Should be updated within a week or so. Thank you again for letting us know!
