### ISSUE TITLE
Example of  that shows how to remotely create assembly and publish with user with create assembly rights, sign

### ISSUE THREAD

**Issue by troglobytor** [MicrosoftDocs/sql-docs#5768]
Using VS2019 and generated pfx, user x on C1 always gives me
 
 SQL72014: .Net SqlClient Data Provider: Msg 10343, Level 14, State 1, Line 1 CREATE or ALTER ASSEMBLY for assembly 'clr0' with the SAFE or EXTERNAL_ACCESS option failed because the 'clr strict security' option of sp_configure is set to 1. Microsoft recommends that you sign the assembly with a certificate or asymmetric key that has a corresponding login with UNSAFE ASSEMBLY permission. Alternatively, you can trust the assembly using sp_add_trusted_assembly.
(47,0): SQL72045: Script execution error.

yet user x on C0 installed sqlx19, created databases, and when sa  was enabled, same errors for sa. It would be great to have example of what would work from start to finish rather than explanations of what is required without detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96693d4a-9460-9e08-8f14-836b6257e449
* Version Independent ID: 47f19aec-1f62-97c4-fca4-609496fc2139
* Content: [CLR strict security - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/clr-strict-security?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/clr-strict-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/clr-strict-security.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@troglobytor,

Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

In the meantime, please visit [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) to see if this issue was already submitted to the product group.

**Comment by shueybubbles** [comment]
@troglobytor  can you share some more information about how you generated your certificate and signed the binary and created the login on the server associated with that certificate? Do you have a minimal .csproj and sql script to reproduce the issue? Is the cert authority a trusted root on the sql server (I'm not sure if that's required).  Those might help on the user feedback site as opposed to trying to resolve what's going on in this docs forum.

**Comment by troglobytor** [comment]
@shueybubbles I can't remember if this was my attempt at windows sql19clr or linux sql19 from windows, but I know it was not from my cpp sqlclr on windows. My notes will take me a day or so to be sure of what I did to do the clrs on both windows and linux. I was successful at both. I will update as soon as I have cleaned up the steps.

**Comment by troglobytor** [comment]
What I had to do for cpp on windows

::------------------------------------------------------------------------------------------
:: cwd is u1msdoc
::
::https://www.sqlshack.com/impact-clr-strict-security-configuration-setting-sql-server-2017/
::makecert -r -pe -n CN=CLRString Split Test Root Authority -a sha256 -sky signature -cy authority -sv CLRStringS plit.pvk -len 2048 -m ::144 CLRStringSplit.cer
::
makecert -r -pe -n CN=CLRCPPTRA1 -a sha256 -sky signature -cy authority -sv CLRCPP1.pvk -len 2048 -m 144 CLRCPP1.cer
::
::password msdoc
::
::PVK2PFX -pvk CLRStringSplit.pvk -spc CLRStringSplit.cer -pfx CLRStringSplit.pfx -pi P@ssw0rd1 -po P@ssw0rd1
::
PVK2PFX -pvk CLRCPP1.pvk -spc CLRCPP1.cer -pfx CLRCPP1.pfx -pi msdoc -po AllieBear
::---------------------------------------------------------------------------------------------
--SQLQ----------------------------------------------------------------------------------------------
USE master;
GO
-- BAD VERY BAD NOT FOUND AND NO RIGHTS: CREATE CERTIFICATE CLRCPPCert FROM FILE = 'D:\c\vs2019\sqlclrcpp\cert\u1\CLRCPP.cer';
--linux must create directory that sql server can read  and access on windows, too
--CREATE CERTIFICATE CLRCPPCert FROM FILE = '\\TROGFSRVR\s1$\sql19\CERT\U1\CLRCPP.cer';
--CREATE CERTIFICATE CLRCPPCert FROM FILE = '\\TROGFSRVR\s1$\sql19\CERT\U1MSDOC\CLRCPP.cer';  
-- SUBSITUTE <YOUR PATH>
CREATE CERTIFICATE CLRCPPCert1 FROM FILE = '<YOUR PATH>';
GO
-- CREATE LOGIN OR ALTER PERMISSIONS
CREATE LOGIN CLRCPPCert1Login FROM CERTIFICATE CLRCPPCert1;
GRANT UNSAFE ASSEMBLY TO CLRCPPCert1Login;
GO
--
//
// project post link build event
// SignTool sign /f ..\cert\\CLRCPP.pfx /p XXXXXX $(OutDir)$(TargetFileName)
   SignTool sign /f ..\cert\\CLRCPP1.pfx /p AllieBear $(OutDir)$(TargetFileName)
// copy $(OutDir)$(TargetFileName) \\trogfsrvr\s1$\sql19\a\u1
// copy $(OutDir)$(TargetFileName) \\trogfsrvr\s1$\sql19\a\u1msdoc
   copy $(OutDir)$(TargetFileName) <YOUR PATH>
//
--
USE CLR
--CREATE ASSEMBLY SQLCLRCPP0 FROM '\\trogfsrvr\s1$\sql19\a\u1\sqlclrcpp0.dll' WITH PERMISSION_SET = UNSAFE;
CREATE ASSEMBLY SQLCLRCPP1 FROM '\\trogfsrvr\s1$\sql19\a\u1msdoc\sqlclrcpp1.dll' WITH PERMISSION_SET = UNSAFE;
--
CREATE PROCEDURE [dbo].[clr_getversion1]
WITH EXECUTE AS CALLER
AS
EXTERNAL NAME [sqlclrcpp1].[sqlclrcpp1.StoredProcedures].[clr_getversion1]
GO

**Comment by troglobytor** [comment]
I cannot get my text as text to appear properly, that is plain simple text.

**Comment by troglobytor** [comment]
--SQLQ----------------------------------------------------------------------------------------------
USE master;
GO
-- BAD VERY BAD NOT FOUND AND NO RIGHTS: CREATE CERTIFICATE CLRCPPCert FROM FILE = 'D:\c\vs2019\sqlclrcpp\cert\u1\CLRCPP.cer';
--linux must create directory that sql server can read  and access on windows, too
--CREATE CERTIFICATE CLRCPPCert FROM FILE = '\\TROGFSRVR\s1$\sql19\CERT\U1\CLRCPP.cer';
--CREATE CERTIFICATE CLRCPPCert FROM FILE = '\\TROGFSRVR\s1$\sql19\CERT\U1MSDOC\CLRCPP.cer';  
-- SUBSITUTE YOUR PATH
CREATE CERTIFICATE CLRCPPCert1 FROM FILE = 'YOUR PATH';
GO
-- CREATE LOGIN OR ALTER PERMISSIONS
CREATE LOGIN CLRCPPCert1Login FROM CERTIFICATE CLRCPPCert1;
GRANT UNSAFE ASSEMBLY TO CLRCPPCert1Login;
GO

**Comment by troglobytor** [comment]
--
//
// project post link build event
// SignTool sign /f ..\cert\\CLRCPP.pfx /p XXXXXX $(OutDir)$(TargetFileName)
  SignTool sign /f ..\cert\\CLRCPP1.pfx /p AllieBear $(OutDir)$(TargetFileName)
// copy $(OutDir)$(TargetFileName) \\trogfsrvr\s1$\sql19\a\u1
// copy $(OutDir)$(TargetFileName) \\trogfsrvr\s1$\sql19\a\u1msdoc
   copy $(OutDir)$(TargetFileName) 'YOUR PATH'
//
SE CLR
--CREATE ASSEMBLY SQLCLRCPP0 FROM '\\trogfsrvr\s1$\sql19\a\u1\sqlclrcpp0.dll' WITH PERMISSION_SET = UNSAFE;
CREATE ASSEMBLY SQLCLRCPP1 FROM '\\trogfsrvr\s1$\sql19\a\u1msdoc\sqlclrcpp1.dll' WITH PERMISSION_SET = UNSAFE;
CREATE PROCEDURE [dbo].[clr_getversion1]

**Comment by troglobytor** [comment]
--
CREATE PROCEDURE [dbo].[clr_getversion1]
WITH EXECUTE AS CALLER
AS
EXTERNAL NAME [sqlclrcpp1].[sqlclrcpp1.StoredProcedures].[clr_getversion1]
GO

**Comment by troglobytor** [comment]
Sorry about my post sequence, but crazy bold would take over if I pasted too much.

**Comment by markingmyname** [comment]
@shueybubbles

Does @troglobytor additional info help?

**Comment by shueybubbles** [comment]
I think you'd have better luck getting input from someone on https://dba.stackexchange.com/ or aka.ms/sqlfeedback to comment on what the right way to achieve your goal is.  I agree the docs need work if they aren't providing adequate support, but I don't think this forum is meant for this kind of deep dive into your specific environment's problems. The folks who contribute to the docs may not be the right folks to know _why_ the documented approach isn't working for you.

**Comment by markingmyname** [comment]
Thanks, @shueybubbles.  correct, this forum is for doc bugs specifically.

@troglobytor 

As such, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by troglobytor** [comment]
@markingmyname

Did anybody get that a newbie would not know how to do all those things? Did anyone read all the things I had to do? Would it not be a bug if one was taught how to get a plane in the air but keep landing a secret?
