### ISSUE TITLE
Certificate Import feature not available in 2017 and below.

### ISSUE THREAD

**Issue by Muxxx** [MicrosoftDocs/sql-docs#5769]
On this page, it references an 'Import' function within the Certificates tab of SQL Server Network Configuration. This import function does not exist in SQL Server 2017 and below. This page should be updated to not include these steps for any version of SQL Server below 2019, as it is misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be811156-078f-e4d9-406a-7e63e06603b5
* Version Independent ID: e7ab123c-1f76-14ac-2d55-296e7845a50c
* Content: [Certificate Management (SQL Server Configuration Manager) - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/manage-certificates?view=sql-server-2017#provision-failover-cluster-cert)
* Content Source: [docs/database-engine/configure-windows/manage-certificates.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/manage-certificates.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@Muxxx -- Stefano, thank you for your feedback.

@markingmyname -- Mark, please look into this issue.

cc @VanMSFT for related issue #5770

**Comment by markingmyname** [comment]
@Muxxx,

Thank you for your contribution.

The article will be updated by the end of the week.

Please review it then and let me know if this works.

thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
