### ISSUE TITLE
Contradicting use statements for Configuration Manager for SQL Server 2019 

### ISSUE THREAD

**Issue by Muxxx** [MicrosoftDocs/sql-docs#5770]
"With SQL Server 2019 (15.x), certificate management is integrated into the SQL Server Configuration Manager. SQL Server Configuration Manager for SQL Server 2019 (15.x) can be used with earlier versions of SQL Server. Refer to Certificate Management (SQL Server Configuration Manager) to add a certificate in a Failover Cluster configuration or in an Availability Group configuration.

If using SQL Server 2012 (11.x) through SQL Server 2017 (14.x), and SQL Server Configuration Manager for SQL Server 2019 (15.x) is not available, follow the steps in section To provision (install) a certificate on a single server for every server."

These two paragraphs contradict one another. In the first paragraph we CAN use Configuration Manager for SQL Server 2019 for earlier versions of SQL Server. In the second paragraph goes on to state that this is actually not possible for previous versions of SQL Server. Please be clear on what is and isn't possible with Configuration Manager for SQL Server 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa20275-e415-5531-3ef4-7472d859753b
* Version Independent ID: cc1346a6-9336-91ba-bcff-9fff79847c35
* Content: [Enable encrypted connections - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-2017)
* Content Source: [docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @Muxxx - The article references that SQL Server Configuration Manager that is installed with SQL Server 2019 can be used with SQL Server 2017 and lower versions. Certificate management is only available with SQL Server Configuration Manager for SQL Server 2019. SQL Server Configuration Manager is not used exclusively for certificate management, and I don't believe that those paragraphs contradict each other.

Please let us know if you have any further concerns. Thanks!
