### ISSUE TITLE
Ubuntu 20.10 apt-key is deprecated

### ISSUE THREAD

**Issue by tgmoo** [MicrosoftDocs/sql-docs#5775]
[The instructions cannot be followed on  Ubuntu 20.10 (GNU/Linux 5.8.0-1006-raspi aarch64) as the apt-get commands do not work.  Some earlier reports online suggested that the deprecation was just a warning and that the command worked.  It is not working on this version of Ubuntu.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @tgmoo! Thanks for the feedback. Currently, Ubuntu 20 is not supported for SQL Server on Linux. https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019?view=sql-server-ver15#supported-platforms

Once we are able to provide support, we will ensure that the commands are updated. We appreciate your feedback.
