### ISSUE TITLE
Article "Prepare data for bulk export or import" incorrectly states CSV is not supported by BULK INSERT

### ISSUE THREAD

**Issue by ChaseGeeseman** [MicrosoftDocs/sql-docs#5779]
The article with the title "Prepare data for bulk export or import" located at URL

https://docs.microsoft.com/en-us/sql/relational-databases/import-export/prepare-data-for-bulk-export-or-import-sql-server?view=sql-server-ver15

states 

"Comma-separated value (CSV) files are not supported by SQL Server bulk-import operations. "

However the article covering Bulk insert located at

https://docs.microsoft.com/en-us/sql/t-sql/statements/bulk-insert-transact-sql?view=sql-server-ver15

states

"Input file format options
FORMAT = 'CSV' Applies to: SQL Server 2017 (14.x) CTP 1.1. Specifies a comma separated values file compliant to the RFC 4180 standard."

**Comment by WilliamAntonRohm** [comment]
@ChaseGeeseman -- thank you for bringing this inconsistency to our attention.

@MashaMSFT -- please look into this issue.

cc @markingmyname for awareness

**Comment by MashaMSFT** [comment]
Hi @ChaseGeeseman , thanks so much for reaching out! The supportability for CSV import changed with SQL Server 2017. I have processed a change to update this and it will be live either later this week, or possibly next. 

I'll close out this Git Issue for the time being but please feel free to comment should you need anything further.

Thanks and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
