### ISSUE TITLE
Not up to date or not valid for Azure SQL Server Instances

### ISSUE THREAD

**Issue by jdthorpe** [MicrosoftDocs/sql-docs#5780]
I installed the latest version of SSMS (18.7.1) but it doesn't have a task called "Data Discovery and Classification" in any of my databases (all hosted Azure SQL instances).  Somehow several fields in my database were automatically classified as credit card numbers (they aren't), and the instructions in this article don't seem to be valid for the current version of SSMS or Azure SQL Instances.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34863695-cd07-1260-4fea-66738c5fa80a
* Version Independent ID: 4c01015d-9c1d-db8e-84f5-379ffc5d5133
* Content: [SQL Data Discovery & Classification - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/sql-data-discovery-and-classification?view=sql-server-ver15&tabs=t-sql)
* Content Source: [docs/relational-databases/security/sql-data-discovery-and-classification.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/sql-data-discovery-and-classification.md)
* Service: **sql-database**
* GitHub Login: @DavidTrigano
* Microsoft Alias: **datrigan**

**Comment by DavidTrigano** [comment]
Hello @jdthorpe,

This article describes SQL Data Discovery and Classification. For Azure SQL Data Discovery and Classification, please refer to https://docs.microsoft.com/en-us/azure/azure-sql/database/data-discovery-and-classification-overview

**Comment by WilliamAntonRohm** [comment]
@DavidTrigano -- David, thank you for clarifying.  

I am closing this issue now.  Jason, you are welcome to @ mention me for any followup.
We hope to hear from you again.
