### ISSUE TITLE
Mentioning of Express version is too short and unclear

### ISSUE THREAD

**Issue by Laniusexcubitor** [MicrosoftDocs/sql-docs#5784]
It would be nice if the article would elaborate on SQL Server Express not supporting the publication in the tutorial and what options there are for Express and what are the disadvantages. The wording suggests that it is possible to create another type of publication for express subscribers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16df2747-32ea-b464-e92c-535f6d2a788c
* Version Independent ID: f50b285e-9a62-8823-c207-3b31ce6d4e7e
* Content: [Tutorial: Configure Merge Replication - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/tutorial-replicating-data-with-mobile-clients?view=sql-server-ver15)
* Content Source: [docs/relational-databases/replication/tutorial-replicating-data-with-mobile-clients.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/tutorial-replicating-data-with-mobile-clients.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @Laniusexcubitor , thanks for contacting Microsoft! You can find information about what replication technology is supported by edition here: [Editions and supported features for SQL Server 2019](https://docs.microsoft.com/sql/sql-server/editions-and-components-of-sql-server-version-15#Replication).

You'll notice that SQL Server Express supports being a subscriber to a merge replication. However, the objects that are created in this tutorial specifically do not support SQL Server express. 

I hope that helps! I will close out this Git Issue for the time being but please feel free to commend should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
