### ISSUE TITLE
 see "Managing Concurrent Data Access" in SQL Server Books Online.

### ISSUE THREAD

**Issue by BobAlston** [MicrosoftDocs/sql-docs#5786]
I cannot find this document.  Can someone tell me its url?
[Enter feedback here]

I cannot find this document.  Can someone tell me its url?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 983e0aa0-106e-8df8-f0d0-f12d586d8015
* Version Independent ID: 53a5e701-deac-b6f6-be21-3d0c29fd5afd
* Content: [Understanding concurrency control - SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/understanding-concurrency-control?view=sql-server-ver15)
* Content Source: [docs/connect/jdbc/understanding-concurrency-control.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/understanding-concurrency-control.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@BobAlston Thanks for submitting feedback!

I believe you are looking for this page:
https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-ver15#managing-concurrent-data-access

I've noted that the page you are submitted feedback for doesn't have a link directly there and I'll update it to include the link.

Thanks,
David

**Comment by David-Engel** [comment]
The page has been updated and the change should be reflected sometime in the next few hours.

#please-close
