### ISSUE TITLE
Polybase not Currently Supported on SQL Managed instance 

### ISSUE THREAD

**Issue by KatieOS** [MicrosoftDocs/sql-docs#5787]
Currently Polybase can only be installed on SQL Server Windows 
The docs indicate that this is supported on MI 
![image](https://user-images.githubusercontent.com/8825167/101617591-b70a7f80-3a08-11eb-97ac-f5f443cedfde.png)

Looking at the doc on github https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-installation.md

The problem is this the link  https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/includes/applies-to-version/sql-windows-only-asdbmi.md

This should link to  a doc with only SQL Sever windows 
example [!INCLUDE Applies to] [!INCLUDE SQL Server] - Windows only

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0f602a-88ea-16cc-a28f-d306de15d22b
* Version Independent ID: 81ed5850-ffbb-b1f8-4bd6-fede5eb5769b
* Content: [Install PolyBase on Windows - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-installation?view=sql-server-ver15)
* Content Source: [docs/relational-databases/polybase/polybase-installation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-installation.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@KatieOS -- thank you for your feedback!  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review [private PR 18083](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18083) containing this change.

**Comment by WilliamAntonRohm** [comment]
@KatieOS -- we have updated the documentation and it should be live by tomorrow.  We hope to hear from you again.
