### ISSUE TITLE
compat level 1500 is missing

### ISSUE THREAD

**Issue by KoenVerbeeck** [MicrosoftDocs/sql-docs#5788]
compat level 1500 is missing from the table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58f47a93-3c1f-dcc3-4e65-0db0f10e09b8
* Version Independent ID: babc41d2-5b9d-1af6-3cae-0e0d59f579d1
* Content: [Upgrade Analysis Services - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/upgrade-analysis-services?view=sql-server-ver15)
* Content Source: [docs/database-engine/install-windows/upgrade-analysis-services.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/upgrade-analysis-services.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by Minewiskan** [comment]
@KoenVerbeeck - Thanks for pointing this out. Update will appear in en-us locale later today, 12/9/2020 PST.
#please-close
