### ISSUE TITLE
RC4 encryption is disabled by default on redhat 8.2

### ISSUE THREAD

**Issue by guidin360** [MicrosoftDocs/sql-docs#5792]
I've followed the steps to be able to login using AD and kerberos on redhat 8.2.

Initially it failed with:

Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication. [CLIENT: 10.1.0.4]

/var/opt/mssql/log/errorlog:
2020-12-09 22:01:04.00 Logon       SSPI handshake failed with error code 0x80090304, state 14 while establishing a connecti
on with integrated security; the connection has been closed. Reason: AcceptSecurityContext failed. The operating system err
or code indicates the cause of failure. The Local Security Authority cannot be contacted   [CLIENT: 10.1.0.4]
2020-12-09 22:01:04.01 Logon       Error: 18452, Severity: 14, State: 1.
2020-12-09 22:01:04.01 Logon       Login failed. The login is from an untrusted domain and cannot be used with Integrated a
uthentication. [CLIENT: 10.1.0.4]

Enabling debug traces i found:

12/10/2020 08:55:53.693422448 Error [security.kerberos] <0000022936/0x000001b0> Request ticket server MSSQLSvc/<serverfqdn>:1433@DOMAIN.COM kvno <#> enctype rc4-hmac found in keytab but cannot decrypt ticket

It seems that redhat 8x has rc4 disabled by default as per https://access.redhat.com/articles/3642912
After enabling it using the "legacy" crypto policy it worked.
Is there any implication on this, or is it possible to use one of the default supported crypto systems in redhat?

I think the documentation should be updated since it says that mssql supports 8.2 but I spent a week trying to figure out why AD authentication was not working.

Thanks!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Use AD authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-ver15#createuser)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **dygray**

**Comment by guidin360** [comment]
Update,

I tried creating the keytab file using only aes-256 with:

ktpass /princ MSSQLSvc/<fully qualified domain name of host machine>:<tcp port>@CONTOSO.COM /ptype KRB5_NT_PRINCIPAL /crypto aes256-sha1 /mapuser <DomainName>\<UserName> /out mssql.keytab -setpass -setupn /kvno <#> /pass <StrongPassword>


ktpass /princ MSSQLSvc/<netbios name of the host machine>:<tcp port>@CONTOSO.COM /ptype KRB5_NT_PRINCIPAL /crypto aes256-sha1 /mapuser <DomainName>\<UserName> /in mssql.keytab /out mssql.keytab -setpass -setupn /kvno <#> /pass <StrongPassword>


ktpass /princ <UserName>@CONTOSO.COM /ptype KRB5_NT_PRINCIPAL /crypto aes256-sha1 /mapuser <DomainName>\<UserName> /in mssql.keytab /out mssql.keytab -setpass -setupn /kvno <#> /pass <StrongPassword>


But for some reason, rc4-hmac is still being tried:

12/10/2020 13:57:28.779870028 Error [security.kerberos] <0000002205/0x00000240> Request ticket server MSSQLSvc/<fqdn>:1433@CONTOSO.COM kvno 2 found in keytab but not with enctype rc4-hmac

**Comment by Dylan-MSFT** [comment]
[These](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/security/configuration-to-support-kerberos-aes-encryption) instructions are for how to enable AES on a sharepoint AD account, but the resolution steps should also work for you. Essentially, AES is not enabled on the account which owns the SPNs, so it falls back to RC4. However, RC4 is not enabled on RHEL 8.2. If we enabled AES on the account, your login failures should go away.

**Comment by guidin360** [comment]
Thanks @Dylan-MSFT , it worked.
Maybe it would be a good idea to mention it on the SQL documentation too.

Best regards.
Guido

**Comment by Dylan-MSFT** [comment]
Glad it worked! We are already working on doc updates :)

**Comment by Dylan-MSFT** [comment]
@VanMSFT

**Comment by VanMSFT** [comment]
This has been addressed in the latest document update by Tejas. https://github.com/MicrosoftDocs/sql-docs/commit/0d246de21a9fc25a8a23428a6f4857ac7a4cea12#diff-889f18cacc4eb6cd136b1b2910e5aeffd3138379cbab4920e9f05b4b20ed163f
