### ISSUE TITLE
Checksum mismatch errors in the https://packages.microsoft.com/sles/12/prod

### ISSUE THREAD

**Issue by szabotoma** [MicrosoftDocs/sql-docs#5793]
Dear All,

I created a repo on our SUSE SMT server. 
Repo ext URL:   https://packages.microsoft.com/sles/12/prod

When I tried to mirror the repository I got Checksum mismatch errors with 3 files.

Repositories with errors  :
  * MicrosoftODBC (https://packages.microsoft.com/sles/12/prod):
    - E '/srv/www/htdocs/repo/full/RPMMD/MicrosoftODBC/adutil-preview-0.7.022-1.x86_64.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/full/RPMMD/MicrosoftODBC/omi-1.6.4-0.ssl_100.ulinux.x64.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/full/RPMMD/MicrosoftODBC/scx-1.6.4-7.universal.x64.rpm': Checksum mismatch'

Please fix the Checksum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@szabotoma Thanks for submitting feedback!

I've forwarded the info to the Linux repo admins so that they can resolve the mismatch.

Since this is not a documentation-related issue, though, I'm am going to close the issue.

Regards,
David

#please-close

**Comment by David-Engel** [comment]
FYI, the teams that own the listed packages have all republished them and the mismatch should be resolved now.
