### ISSUE TITLE
Need IPV4 example

### ISSUE THREAD

**Issue by kbuck-fortifieddata** [MicrosoftDocs/sql-docs#5794]
Great article, would be good to have the T-SQL example use IPV4 addresses that are easier to understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b679be86-06b0-b425-cd4f-d7b3ea104693
* Version Independent ID: aec2cf5b-5bf9-647e-6b0f-9fab6fca3a79
* Content: [Configure availability group listener - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@kbuck-fortifieddata -- thank you for your kind words and your suggestion.

@cawrites -- please look into this issue.

**Comment by cawrites** [comment]
@kbuck-fortifieddata thank you for contacting Microsoft regarding your suggestion. I have reviewed the sections referencing IPV4. The syntax using for each of the statements:  command adds a static IPv4 address to the availability group listener, the IPv4 address passed to the -StaticIp parameter as its virtual IP address, Add-SqlAGListenerstaticIp command adds a static IPv4 address are needed for each of the functions described as suggested. 

Can you advise if these are the sections you are referring to? Or a specific section.

**Comment by kbuck-fortifieddata** [comment]
No, the section you are referring to is PowerShell.
I was referring to the section “Using Transact-SQL” and the example that is part of that section.

[cid:image001.gif@01D6CF9E.6849AE90]

Keith Buck
Senior Consultant
Fortified Data
KBUCK@FORTIFIEDDATA.COM<mailto:KBUCK@FORTIFIEDDATA.COM>

After Hours and Emergency Production Support
1.844.282.DATA(3282)

**Comment by cawrites** [comment]
@kbuck-fortifieddata  I am reviewing the IPV4 Line by line with the existing description:

Description:
The following example adds an availability group listener to an existing availability group named MyAg2. 

Syntax
**ALTER AVAILABILITY GROUP MyAg2**  

Description A unique DNS name, MyAg2ListenerIvP6, is specified for this listener. 

Syntax
 **ADD LISTENER 'MyAg2ListenerIvP6'**

Description
For each of the two availability replicas, the WITH IP clause specifies a static IP address, 2001:4898:f0:f00f::cf3c and 2001:4898:e0:f213::4ce2,

Syntax
**( WITH IP ( ('2001:db88:f0:f00f::cf3c'),('2001:4898:e0:f213::4ce2') ) , PORT = 60173 );**

Description
This example also specifies uses the optional PORT argument to specify port 60173 as the listener port.

Syntax
**PORT = 60173 );** 

**It is noted in the description that it is using the IPv6 format**

I understand your need for clarification. It appears that the syntax is showing examples of both IPv4 and IPv6. However, in each example, it identifies which address version it is using. By showing both it gives the user examples for both. Individuals could determine on their own to use IPV4 throughout the set up.

**Comment by cawrites** [comment]
@kbuck-fortifieddata we appreciate your suggestions regarding our content and we certainly consider them as we continue to update our content. Thank you for contacting Microsoft.

**Comment by cawrites** [comment]
#please-close
