### ISSUE TITLE
Missing some types for sys.external_data_sources

### ISSUE THREAD

**Issue by RobClenshaw** [MicrosoftDocs/sql-docs#5800]
In the docs for the system view [sys.external_data_sources](https://github.com/MicrosoftDocs/sql-docs/blob/master/docs/relational-databases/system-catalog-views/sys-external-data-sources-transact-sql.md), _type_ and _type_desc_ only list the following types - 

0 - HADOOP
1 - RDBMS
2 - SHARD_MAP_MANAGER
3 - RemoteDataArchiveTypeExtDataSource

I've already discovered that there are the following undocumented values 

5 - BLOB_STORAGE
6 - NONE

I couldn't work out what type 4 was but that is also missing, whether it is simply reserved for future use or not. Could this be updated with all the supported types?

Thanks

**Comment by WilliamAntonRohm** [comment]
@RobClenshaw -- Rob, thank you for your well-researched feedback.

@stevestein -- Steve, please look into this issue.

**Comment by stevestein** [comment]
@RobClenshaw - I created an internal work item (1829248) to investigate and update with any additional values. 

Thanks for pointing this out.

**Comment by rothja** [comment]
Closing per internal tracking of this feedback. @WilliamDAssafMSFT William, please take a look at this issue and the associated work item to see if this influences the work you're doing in related areas of the documentation external data sources. Thank you! #please-close

**Comment by WilliamDAssafMSFT** [comment]
#reassign:williamdassafmsft

**Comment by WilliamDAssafMSFT** [comment]
@RobClenshaw Thanks again for submitting this issue. Your suggestions help improve our documentation. A document update is in flight to complete the possible values for this field and should be published later today.

**Comment by RobClenshaw** [comment]
Thanks for the update :)
