### ISSUE TITLE
Missing "-N" in example

### ISSUE THREAD

**Issue by Dodev-S** [MicrosoftDocs/sql-docs#5803]
The "-N" option is missing in the example for section "Using bcp and Unicode Native Format to Import Data with a Non-XML Format File"  (https://docs.microsoft.com/en-us/sql/relational-databases/import-export/use-unicode-native-format-to-import-or-export-data-sql-server?view=sql-server-ver15#using-bcp-and-unicode-native-format-to-import-data-with-a-non-xml-format-file)

**Comment by WilliamAntonRohm** [comment]
@Dodev-S -- thank you for catching that.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- Masha, please review [private PR 18116](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18116).

**Comment by WilliamAntonRohm** [comment]
@Dodev-S -- thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
