### ISSUE TITLE
Order of steps is incorrect

### ISSUE THREAD

**Issue by kevinowen** [MicrosoftDocs/sql-docs#5807]
The order of the steps listed in the "Planned Relocation Procedure" section is incorrect. Step 3 (running the `ALTER DATABASE database_name MODIFY FILE` command to change the path to the file on disk) should actually be the first step, followed by steps 1 (set database offline), 2 (actually move files), 4 (set database online), and 5 (verify new paths in `sys.master_files`).

Trying to do the steps in the order they are currently listed results in an error, because you can't run `ALTER DATABASE database_name MODIFY FILE` against a database that is already offline. You can, however, run it against an online database, and SQL Server won't try to actually use the new path until the next time the database comes online (either after explicitly taking it offline, or restarting the instance).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378754cc-abd5-2c11-4662-3da9af6094f9
* Version Independent ID: b6ae6f68-11b3-adb2-5ed2-c882bae020f3
* Content: [Move User Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/move-user-databases?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/move-user-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/move-user-databases.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@kevinowen -- Kevin, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please review [private PR 18136](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18136).

**Comment by stevestein** [comment]
@kevinowen - thanks for the feedback.
@WilliamAntonRohm - thanks for updating the article.
