### ISSUE TITLE
Result Grid Color Customization 

### ISSUE THREAD

**Issue by eternityhq** [MicrosoftDocs/sql-docs#5808]
Add the ability to change background / foreground colors separate from the editor in the results grid.
something like resultsGrid.backgroundColor:

**Comment by WilliamAntonRohm** [comment]
@eternityhq -- thank you for your feedback.  Are you following a particular docs.microsoft.com article?  Meanwhile, you're welcome to add your suggestion here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
