### ISSUE TITLE
Error in code sample for Schedule and automate backups of SQL Server databases in SQL Server Express

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/sql-docs#5817]
---
**Issue moved from MicrosoftDocs/feedback#3334**
- Please respond to @cairneym.

---

_From @cairneym on Wednesday, December 16, 2020 7:15:03 AM_

There is a code error in Example 1 on the docs page "[Schedule and automate backups of SQL Server databases in SQL Server Express](https://docs.microsoft.com/en-us/troubleshoot/sql/admin/schedule-automate-backup-database)"

The code provided is : 
    `// Sqlbackup.bat`    
    `sqlcmd -S .\EXPRESS -E -Q "EXEC sp_BackupDatabases @backupLocation='D:\SQLBackups\', @backupType='F'"`   

However the documentation steps around this and the subsequent examples are for an instance named "SQLEXPRESS" and not "EXPRESS".

I resolved a question in [StackOverflow](https://stackoverflow.com/questions/65316885/error-when-trying-to-schedule-auto-backup-in-sql-server-express/65317737) where the user had followed the text exactly and had received errors.

The code sample should be 
    `// Sqlbackup.bat`    
    `sqlcmd -S .\SQLEXPRESS -E -Q "EXEC sp_BackupDatabases @backupLocation='D:\SQLBackups\', @backupType='F'"`

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3334**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Wednesday, December 16, 2020 7:15:04 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by WilliamAntonRohm** [comment]
@cairneym -- Martin, thank you for bringing this to our attention.  I am updating the article.

cc @ramakoni1 for awareness

**Comment by WilliamAntonRohm** [comment]
@cairneym -- Martin, we've updated the article and it should be live tomorrow.  Thank you again.
