### ISSUE TITLE
GRANT CONNECT on the endpoint should be associated with the Login instead of being associated with the user.

### ISSUE THREAD

**Issue by lcanastreiro** [MicrosoftDocs/sql-docs#5822]
Hi all,

step 13. needs to be reviewed, the GRANT CONNECT on the endpoint should be associated with the Login instead of being associated with the user.
https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-endpoint-permissions-transact-sql?view=sql-server-ver15

Thanks,
Luís.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df2d6260-37b5-78f2-e558-7129b58ca9c5
* Version Independent ID: 247cde67-5d7a-c844-f2e7-292277348c60
* Content: [Create a domain-independent availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/domain-independent-availability-groups?view=sql-server-ver15#create-a-domain-independent-availability-group-1)
* Content Source: [docs/database-engine/availability-groups/windows/domain-independent-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/domain-independent-availability-groups.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@lcanastreiro -- thank you for your feedback.

@cawrites -- please look into this issue.

**Comment by cawrites** [comment]
@lcanastreiro thank you for contacting Microsoft. The steps are actually numbered. Can you confirm what you are referring to when you state step number 13?

**Comment by lcanastreiro** [comment]
The step is this one:

13.  Assign rights to each user created on that instance in Step 9 to be able to connect to the endpoint.

GRANT CONNECT ON ENDPOINT::DIAG_EP TO [InstanceX_User];
GO

It should be

GRANT CONNECT ON ENDPOINT::DIAG_EP TO [InstanceX_Login]
GO

Best Regards,
Luís.

**Comment by cawrites** [comment]
@lcanastreiro thank you for contacting Microsoft. This is the syntax from the content you article you referenced.  
https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-endpoint-permissions-transact-sql?view=sql-server-ver15
GRANT permission  [ ,...n ] ON ENDPOINT :: endpoint_name  
        TO < server_principal >  [ ,...n ]  
    [ WITH GRANT OPTION ]  
    [ AS SQL_Server_login ]   
  
<server_principal> ::=   
        SQL_Server_login  
    | SQL_Server_login_from_Windows_login   
    | SQL_Server_login_from_certificate   
    | SQL_Server_login_from_AsymKey

It is using SQL_Server_login.

**Comment by lcanastreiro** [comment]
Everything is correct in your comment but the exception continue to be the code present on step 13. precisely by the reasons that you explained. The grant should be given to a LOGIN (InstanceX_Login) instead to a database user (InstanceX_User). The other steps the code is correct.

**Comment by cawrites** [comment]
@lcanastreiro I understand your point of reference for the context of the syntax. My question to you is, have you executed all the steps in the stated sequence? If so, what error did you receive? I will review it as well. I look forward to your reply.

**Comment by cawrites** [comment]
@lcanastreiro we haven't heard from you regarding this issue. The question was are you executing all the steps in sequence as described and if so, are you getting an error?

**Comment by lcanastreiro** [comment]
Yes, I've executed all the steps, following all the instructions available on the page. the error happens on the step mentioned since the beginning because if you follow the sample code then you are going to use a database user instead if a SQL Instance login, which is the part that's incorrect.

**Comment by cawrites** [comment]
@lcanastreiro I appreciate your patience as I reviewed this document. I walked through all the steps as well, unedited. I was able to generate the following error.
![User-Er](https://user-images.githubusercontent.com/54048339/106982439-fa3b5300-6718-11eb-89c0-c7c2c59705fd.PNG)

**Comment by cawrites** [comment]
@lcanastreiro when I modified the syntax (using a LOGIN instead of a USER) I was able to complete the step.
![Login-OK](https://user-images.githubusercontent.com/54048339/106982550-2a82f180-6719-11eb-86f3-820c5b035fc8.PNG)

**Comment by cawrites** [comment]
@lcanastreiro the 2nd image displays the error I wanted to obtain from you to confirm we were discussing the same issue. Again I appreciate your patience as we were seeking clarity. Now that we have confirmed that this is an error, we can create an update to this content.

**Comment by cawrites** [comment]
@lcanastreiro your change should be reflected in the next refresh. Thank you for contributing to Microsoft.
