### ISSUE TITLE
Why doesn't this page show the command that needs to be run to have alter trace permissions?

### ISSUE THREAD

**Issue by LukeChung** [MicrosoftDocs/sql-docs#5825]
Why doesn't this page show the command that needs to be run to have alter trace permissions?

Where do I now go to find what this page recommends I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6c7a699-d1d6-fe96-276f-a7078f482208
* Version Independent ID: 9323e604-d17f-2a39-2ccc-d1c811204428
* Content: [Permissions Required - SQL Server Profiler](https://docs.microsoft.com/en-us/sql/tools/sql-server-profiler/permissions-required-to-run-sql-server-profiler?view=sql-server-ver15#:~:text=By%20default%2C%20running%20SQL%20Server%20Profiler%20requires%20the,users%20must%20be%20granted%20the%20ALTER%20TRACE%20permission.)
* Content Source: [docs/tools/sql-server-profiler/permissions-required-to-run-sql-server-profiler.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sql-server-profiler/permissions-required-to-run-sql-server-profiler.md)
* Product: **sql**
* Technology: **profiler**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by LukeChung** [comment]
Or is this a setting I need to change in SSMS as a database property?

**Comment by msebolt** [comment]
@LukeChung  Thank you for the question.

Please refer to the [GRANT server permissions](https://docs.microsoft.com/sql/t-sql/statements/grant-server-permissions-transact-sql) documentation that includes the `ALTER TRACE` permission as one of the options.

If there are further issues, please comment below.

**Comment by LukeChung** [comment]
Actually, the solution has nothing to do with the SQL commands.

The solution is that this can’t be done if the database is on Azure and the Azure Data Studio needs to be used instead.

Luke

**Comment by WilliamAntonRohm** [comment]
@LukeChung -- Luke, thank you for your follow-up.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@LukeChung,

Thanks for the feedback! However, this area is primarily for doc issues. To report product issues, the best way to reach out to the SSMS Team is at [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server).

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
