### ISSUE TITLE
Useless.

### ISSUE THREAD

**Issue by Balasariusx** [MicrosoftDocs/sql-docs#5826]
SHOW THE FUCKING SQL STATEMENT FFS.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fb26d1f-f4f6-15cf-344c-412eca5c0814
* Version Independent ID: 60751c53-d023-b48c-403e-34621d405618
* Content: [View a Database Snapshot (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/view-a-database-snapshot-sql-server?view=sql-server-ver15#TsqlProcedure)
* Content Source: [docs/relational-databases/databases/view-a-database-snapshot-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/view-a-database-snapshot-sql-server.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by CrazyPyro** [comment]
Who hurt you? It's ok, you can tell us...

**Comment by msebolt** [comment]
@Balasariusx We apologize for the issues you have.

Please note the page includes a link to [sys.databases examples](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-databases-transact-sql?view=sql-server-ver15#examples).
