### ISSUE TITLE
DROP FUNCTION See also link is incorrect on CREATE FUNCTION docs page

### ISSUE THREAD

**Issue by dave-q** [MicrosoftDocs/sql-docs#5830]
The DROP FUNCTION link in the 'See Also' section is wrong it takes you to https://docs.microsoft.com/en-us/sql/tools/sql-server-profiler/start-sql-server-profiler?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83a97c04-e1b4-7a16-dc4e-09fbb0a88b29
* Version Independent ID: 5f051d06-a63b-03e8-c8a9-6862c6977ebc
* Content: [Create User-defined Functions (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/create-user-defined-functions-database-engine?view=sql-server-ver15)
* Content Source: [docs/relational-databases/user-defined-functions/create-user-defined-functions-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/user-defined-functions/create-user-defined-functions-database-engine.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@dave-q -- thank you for notifying us about these typos.  I am looking into the article.
