### ISSUE TITLE
Security: SQL Server can be reached from the whole Internet

### ISSUE THREAD

**Issue by ipg-informatik** [MicrosoftDocs/sql-docs#5837]
The Tutorial works, but with this Tutorial the SQL Server is reachable from the whole Internet. After a few hours there are many login attempts in the SQL Server Logs. It would be important, when the Tutorial also consider the security. For example with a kubernetes network policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04922c04-a2da-186c-5946-1cc4d9a7447b
* Version Independent ID: 6e490885-cdd7-079a-0b3a-4688616b0954
* Content: [Deploy a SQL Server container with Azure Kubernetes Services (AKS) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-ver15)
* Content Source: [docs/linux/tutorial-sql-server-containers-kubernetes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-sql-server-containers-kubernetes.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@ipg-informatik -- thank you for your considered feedback and suggestions.

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
Hi @ipg-informatik! Thank you for the feedback. I will consider this in upcoming revisions of the document. As with any version of SQL Server that is connected to the internet, it is always good to consider network policies and changing the default port that SQL Server listens on. An example of this can be seen here: https://dbafromthecold.com/2018/04/04/changing-the-port-for-sql-server-in-azure-container-services/

I will go ahead and close this issue, but please feel free to let us know if you have any concerns.
