### ISSUE TITLE
You have 'and' twice in first paragraph

### ISSUE THREAD

**Issue by matthewcrow** [MicrosoftDocs/sql-docs#5843]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ebefef-f8c5-e429-269e-1ef7a96264fd
* Version Independent ID: a8009495-9bb9-87f4-85af-0ac0074749e7
* Content: [What is PolyBase? - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-guide?view=sql-server-ver15)
* Content Source: [docs/relational-databases/polybase/polybase-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-guide.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@matthewcrow -- Matthew, thank you for bringing this to our attention.  I am looking into the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
