### ISSUE TITLE
in-memory based tables do not have a Buffer Pool

### ISSUE THREAD

**Issue by TorstenStrauss** [MicrosoftDocs/sql-docs#5844]
Hi Microsoft Team,

Quote

"Consider the following scenario:

Worker 1 is a long-running task, for example a read query using read-ahead over in-memory based tables. Worker 1 finds its required data pages are already in Buffer Pool, so it doesn't have to yield to wait for I/O operations, and can consume its full quantum before yielding.
Worker 2 is doing shorter sub-millisecond tasks and therefore is required to yield before its full quantum is exhausted."

To my understanding this is not correct.
There is no read ahead, Buffer Pool concept, pages and no I/O operations for in-memory based tables.
I guess you should replace in-memory based tables with on-disk tables.

Thanks for fixing!

Torsten Strauß
MVP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c4ffb5-9862-ea37-e28d-547f97de08f9
* Version Independent ID: 0c6a63c8-7a9f-06ee-2ffc-d6fd4455c016
* Content: [Thread and Task Architecture Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/thread-and-task-architecture-guide?view=sql-server-ver15&viewFallbackFrom=sql-server-ver1)
* Content Source: [docs/relational-databases/thread-and-task-architecture-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/thread-and-task-architecture-guide.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @pmasl
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@TorstenStrauss -- Torsten, thank you for your feedback.

@pmasl -- Pedro, please look into this issue.

**Comment by MikeRayMSFT** [comment]
Fixed in https://github.com/MicrosoftDocs/sql-docs-pr/pull/18905

Thank you @pmasl

**Comment by MikeRayMSFT** [comment]
@TorstenStrauss  - thanks again for submitting this. The update to correct the documentation will publish in the next day or so.
