### ISSUE TITLE
Some headers under Related Tasks are repeated

### ISSUE THREAD

**Issue by engfob** [MicrosoftDocs/sql-docs#5856]
Under Related Tasks, all the following headers & their links are repeated:
To delete old rows from backup and restore history tables
To delete all rows for a specific database from backup and restore history tables
To view media header information
To view backup header information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 759088b5-5531-93c4-bb7b-40407a61a07e
* Version Independent ID: 3cd738de-043b-b777-9956-57f0f2c444a2
* Content: [Backup history & header - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/backup-history-and-header-information-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/backup-restore/backup-history-and-header-information-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/backup-history-and-header-information-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@engfob -- thank you for bringing these to our attention.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
