### ISSUE TITLE
Remove Parameter From Sp

### ISSUE THREAD

**Issue by mohammadyasinparsi** [MicrosoftDocs/sql-docs#5857]
in your in your peer to peer replication guide, there is a parameter with name @source_table that has change to @source_object. please update your guide thanks alot 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a9c0280-dda6-a439-a161-317f4157bcce
* Version Independent ID: 54857751-d553-ce1f-cf42-52ff40fda5b4
* Content: [Administer a Peer-to-Peer topology (Replication SP) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/administration/administer-a-peer-to-peer-topology-replication-transact-sql-programming?view=sql-server-2017)
* Content Source: [docs/relational-databases/replication/administration/administer-a-peer-to-peer-topology-replication-transact-sql-programming.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/administration/administer-a-peer-to-peer-topology-replication-transact-sql-programming.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@mohammadyasinparsi -- thank you for bringing this to our attention.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- Masha, please review [private PR 18214](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18214).

**Comment by mohammadyasinparsi** [comment]
Hi it's return not found page(404)

Best regards MYP

________________________________

**Comment by WilliamAntonRohm** [comment]
@mohammadyasinparsi -- Mohammad, the pull request I created is in a different, private repo that we use for staging documentation before it goes live.  Masha is investigating this issue now.

**Comment by WilliamAntonRohm** [comment]
@mohammadyasinparsi -- Mohammad, here is the response:

- `@source_table` is deprecated but still supported for backward compatibility. However, if `@source_object` is used (that is, not NULL) the user is expected to manually create the view to be used for the snapshot of the article source object. The previous script works and uses a deprecated (but still supported) parameter.
- We are updating the documentation to clarify this.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
