### ISSUE TITLE
HumanResources schema not part of sample data for Azure SQL db

### ISSUE THREAD

**Issue by mohowzeh** [MicrosoftDocs/sql-docs#5860]
Hi, 

First of all thank you for this great tutorial. 

I followed this tutorial by first creating an Azure SQL db and populating it with sample data during its creation. However, the schema HumanResources was not part of the sample data, so the creation of the stored procedure failed. 

May I suggest that the tutorial is modified so that also an Azure SQL db with sample data could be used as a source?

For example, the stored procedure could be modified to use the SalesLT.Customer table if the following modifications are applied:

` CREATE PROCEDURE SalesLT.uspGetCustomerTest` 

and 

` SELECT FirstName, LastName, CompanyName  
FROM SalesLT.Customer as c
WHERE c.FirstName = @FirstName AND c.LastName = @LastName AND CompanyName IS NOT NULL; `

The above is just a friendly suggestion  :-) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92c7b9f-a4b5-115e-f929-f291b6f7b3c0
* Version Independent ID: 894d9c40-c03f-36c1-3f4b-2d60ab63e039
* Content: [Create a Stored Procedure - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/create-a-stored-procedure?view=sql-server-ver15)
* Content Source: [docs/relational-databases/stored-procedures/create-a-stored-procedure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/stored-procedures/create-a-stored-procedure.md)
* Product: **sql**
* Technology: **stored-procedures**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@mohowzeh -- Nick, thank you for your positive feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, there are too many ramifications here for me to confidently update the SQL code.  Please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Hi @mohowzeh Thanks for the feedback on this documentation. You're right, this is an issue because the Azure SQL DB "sample" uses the AdventureWorks**LT**201n sample database, not the AdventureWorks201n sample database that the documentation was written for.

I will put in a future work item to rewrite these sample exercises we'll keep in mind both sets of sample databases.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.
