### ISSUE TITLE
Documentation for dm_db_missing_index_group_stats_query

### ISSUE THREAD

**Issue by erikdarlingdata** [MicrosoftDocs/sql-docs#5862]
This DMV is available in SQL Server 2019, but has no supporting documentation. Can someone please add it?

Thanks,
Erik

**Comment by WilliamAntonRohm** [comment]
@erikdarlingdata -- Erik, thank you for your feedback.  Please provide a link to the article where this new information should go.

**Comment by erikdarlingdata** [comment]
@WilliamAntonRohm shouldn't it get a new page along with other DMVs that describe missing index requests?

**Comment by WilliamAntonRohm** [comment]
@erikdarlingdata -- Erik, thank you for clarifying.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@ericadarlingdata

Is this the [documentation](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-missing-index-group-stats-transact-sql) you are requesting?

Please let me know.

Thank you.

**Comment by erikdarlingdata** [comment]
@markingmyname no, I'm looking for `dm_db_missing_index_group_stats_query`. which is a DMV introduced in SQL Server 2019.

```
SELECT 
    @@VERSION AS version,
    migsq.*
FROM sys.dm_db_missing_index_group_stats_query AS migsq;
```

![image](https://user-images.githubusercontent.com/2136037/104516876-1557ee80-55c3-11eb-946c-7134223778e7.png)

**Comment by erikdarlingdata** [comment]
@markingmyname just checking in -- are you clear on which DMV I'm looking for? It's been a few weeks since anyone responded or updated. Thanks.

**Comment by erikdarlingdata** [comment]
@markingmyname following up -- did you need any more information from me? Thanks!

**Comment by erikdarlingdata** [comment]
@WilliamAntonRohm I am starting to feel very lonely here.

**Comment by WilliamDAssafMSFT** [comment]
@Erikdarlingdata Thanks for contacting Microsoft with feedback about our product documentation. We're working with product team on this now. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.  Standby.

**Comment by erikdarlingdata** [comment]
@williamadba gotcha! Thanks for the update. After a month, I was getting a little nervous...

**Comment by WilliamDAssafMSFT** [comment]
@erikdarlingdata Thanks for bringing this to attention Erik, a doc update is in flight.

**Comment by erikdarlingdata** [comment]
@williamadba thanks, that's awesome! will i get a notification when the doc is live?

**Comment by WilliamDAssafMSFT** [comment]
haha, so I'm @WilliamDAssafMSFT, @williamadba is a personal account. We work on different projects, but we both have the same nice beard.

This doc should go live some time in the next 24 hours: https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-missing-index-group-stats-query-transact-sql

Thanks again for this contribution @erikdarlingdata.

**Comment by erikdarlingdata** [comment]
@WilliamDAssafMSFT oops, sorry about that! I was distracted by the beard, as you can imagine. Thanks for the link -- I'll keep an F5 on it.
