### ISSUE TITLE
Incorrectly filed page

### ISSUE THREAD

**Issue by sardarw** [MicrosoftDocs/sql-docs#5866]
This page is incorrectly located in the navigation hierarchy.

![image](https://user-images.githubusercontent.com/77050470/103754572-6df81c00-5004-11eb-9bff-21151f02ec99.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac6f1da6-aeea-1f1e-1a97-3260c8d4db1b
* Version Independent ID: 0ac78ce5-331d-a4c8-08e7-43e37c52189e
* Content: [Change Data Capture and Other SQL Server Features - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/change-data-capture-and-other-sql-server-features?view=sql-server-ver15)
* Content Source: [docs/relational-databases/track-changes/change-data-capture-and-other-sql-server-features.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/change-data-capture-and-other-sql-server-features.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@sardarw -- thank you for your feedback.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
Thank you again for your feedback.  I have updated the documentation and it should be live by tomorrow.
