### ISSUE TITLE
Permission issue with linux host

### ISSUE THREAD

**Issue by GetoXs** [MicrosoftDocs/sql-docs#5867]
Hi,
There is no information about linux host requirements. If you run sql-server docker on linux host with volume binding you need to setup proper permission for bounded volume. I wrote some information in here: https://github.com/microsoft/mssql-docker/issues/615#issuecomment-755343546
It would be helpful to have such an information in official doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f77423-91bb-21e4-5e1b-a956a7161ca2
* Version Independent ID: b2d30183-00b8-302d-ab1e-4f9882a2eed0
* Content: [Configure and customize SQL Server Docker containers - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-configure?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-docker-container-configure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-docker-container-configure.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by WilliamAntonRohm** [comment]
@GetoXs -- Mateusz, thank you for your feedback and contribution.

@vin-yu -- Vin, please look into this issue.

**Comment by MikeRayMSFT** [comment]
@GetoXs - I've asked @amvin87 to look at this with me. We'll see if we can get an appropriate response/update.

**Comment by VanMSFT** [comment]
Hi @GetoXs - Thanks for the feedback! This issue stems from SQL Server 2019 containers automatically starting up as non-root, while SQL Server 2017 containers starts as root by default. You will find more information about configuring security here:

https://docs.microsoft.com/sql/linux/sql-server-linux-docker-container-security

I will add a note for clarification in the mentioned doc. Thanks again!
