### ISSUE TITLE
Missing URL link (Create Invoices and Forms with Lists)

### ISSUE THREAD

**Issue by EitanBlumin** [MicrosoftDocs/sql-docs#5870]
Missing URL in this sentence, line 87:

```
For more information, see [Create Invoices and Forms with Lists].
```

https://github.com/MicrosoftDocs/sql-docs/blame/live/docs/reporting-services/report-design/tables-matrices-and-lists-report-builder-and-ssrs.md#L87

**Comment by WilliamAntonRohm** [comment]
@EitanBlumin -- Eitan, thank you for bringing this to our attention.  I am updating the article -- this is the destination:
- https://docs.microsoft.com/sql/reporting-services/report-design/create-invoices-and-forms-with-lists-report-builder-and-ssrs
