### ISSUE TITLE
Why is there a question mark at the end of this paragraph?

### ISSUE THREAD

**Issue by brentmcc** [MicrosoftDocs/sql-docs#5876]
[Enter feedback here]

I've copied and pasted the relevant section here... See the question mark at the end. There shouldn't be question marks in Microsoft documentation as it should be stating facts and not asking questions.

Starting with SQL Server 2016 (13.x) and under the database compatibility level 130, SQL Server uses a decreasing, dynamic statistics update threshold that adjusts according to the number of rows in the table. This is calculated as the square root of the product of 1000 and the current table cardinality. For example if your table contains 2 million rows, then the calculation is sqrt(1000 * 2000000) = 44721.359. With this change, statistics on large tables will be updated more frequently. However, if a database has a compatibility level below 130, then the SQL Server 2014 (12.x) threshold applies. ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e5062c-ab80-eace-5cbb-8868c17014c3
* Version Independent ID: 7bcb85b7-ee68-ae1c-5385-91f6db828c06
* Content: [Statistics - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/statistics/statistics?view=sql-server-ver15)
* Content Source: [docs/relational-databases/statistics/statistics.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/statistics/statistics.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
#Assign:WilliamDAssafMSFT

**Comment by WilliamDAssafMSFT** [comment]
#in-progress

**Comment by WilliamDAssafMSFT** [comment]
Thanks @brentmcc for contacting Microsoft with feedback about our product documentation.  Thanks again for submitting your feedback. Your suggestions help improve our documentation. A document update is in flight.

**Comment by WilliamDAssafMSFT** [comment]
#please-close
