### ISSUE TITLE
Confused about how this service interacts with relational engine

### ISSUE THREAD

**Issue by iampeterdaniels** [MicrosoftDocs/sql-docs#5877]
In the "Pre-install Checklist" section, one line says "**A database engine instance is required**. You can't install just Python or R features, although you can add them incrementally to an existing instance."  Another line further down says, "**Don't install Shared Features > Machine Learning Server (Standalone) on the same computer running a database instance**. A stand-alone server will compete for the same resources, diminishes the performance of both installations."  It would be helpful to clarify if the database instance required should be on the same or a different server and what version of SQL relational engine is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10a1a190-9335-9d2d-c664-9b91c9be8cf0
* Version Independent ID: c9e23f38-b817-bf96-453a-3c7171501dd3
* Content: [Install on Windows - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/install/sql-machine-learning-services-windows-install?view=sql-server-ver15)
* Content Source: [docs/machine-learning/install/sql-machine-learning-services-windows-install.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/install/sql-machine-learning-services-windows-install.md)
* Product: **sql**
* Technology: **machine-learning-services**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@iampeterdaniels Thank you for bringing this to our attention. The **"Don't install Shared Features > Machine Learning Server (Standalone) on the same computer running a database instance."** refers to [Machine Learning Server (Standalone)](https://docs.microsoft.com/en-us/sql/machine-learning/r/r-server-standalone?view=sql-server-ver15), which is different than SQL Server. The database instance and the Machine Learning Services functionality needs to be installed on the same server. Machine Learning Services is supported in SQL Server 2017 and 2019, as indicated by the "Applies to" in the article.

 I can see why this can be confusing and will update the article to clarify this.
