### ISSUE TITLE
SQL Server performance counters: instant snapshot vs cumulative

### ISSUE THREAD

**Issue by n9** [MicrosoftDocs/sql-docs#5878]
I am a bit confused by [the current state of documentation of sys.dm_os_performance_counters](https://github.com/MicrosoftDocs/sql-docs/blob/61fabe82779b4c792d05f47ecfcb32f3d16e2e76/docs/relational-databases/system-dynamic-management-views/sys-dm-os-performance-counters-transact-sql.md).

https://github.com/MicrosoftDocs/sql-docs/commit/1335c4762359d10115d57f9575317f3d9d827855 states that `cntr_type` = `272696320` (PERF_COUNTER_COUNTER) is an **instant snapshot counter** and that `cntr_type` = `272696576` (PERF_COUNTER_BULK_COUNT) is **cumulative counter**.

But [WMI SDK docs](https://docs.microsoft.com/en-us/windows/win32/wmisdk/counter-algorithm-counter-types) says:

> PERF_COUNTER_BULK_COUNT (272696576): Average number of operations completed during each second of the  sample interval. This counter type is the same as the PERF_COUNTER_COUNTER type, but it uses larger fields to accommodate  larger values.

Similarly [.NET docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.performancedata.countertype?view=dotnet-plat-ext-5.0#System_Diagnostics_PerformanceData_CounterType_RawBase32):

> RateOfCountPerSecond64 272696576: This counter type shows the average number of operations  completed during each second of the sample interval. Counters of this  type measure time in ticks of the system clock. This counter type is the  same as the RateOfCountPerSecond32 (272696320) type, but it uses larger fields to accommodate larger values.

And @DavidBridge['s blog post](https://davidbridge.wordpress.com/2011/08/03/sql-server-performance-2008/) states:

> PERF_COUNTER_COUNTER 272696320: Average number of operations completed during each second of the sample interval. NOTE: For “per-second counters”, this value is cumulative. The rate value must be calculated by sampling the value at discrete time intervals. The difference between any two successive sample values is equal to the rate for the time interval used. For example, batch requests/sec is a per-second counter, it would show cumulative values.

Is the documentation correct? (If yes, could there be a bit deeper explanation or link to some explanation?)

**Comment by n9** [comment]
Similar confusion causes PERF_LARGE_RAW_BASE. [The current state of documentation of sys.dm_os_performance_counters](https://github.com/MicrosoftDocs/sql-docs/blob/61fabe82779b4c792d05f47ecfcb32f3d16e2e76/docs/relational-databases/system-dynamic-management-views/sys-dm-os-performance-counters-transact-sql.md) says that PERF_LARGE_RAW_BASE (1073939712) is cumulative counter. But [Interpreting the counter values from sys.dm_os_performance_counters (by mssql-support)](https://techcommunity.microsoft.com/t5/sql-server-support/interpreting-the-counter-values-from-sys-dm-os-performance/ba-p/317824) says:

> PERF_LARGE_RAW_BASE (1073939712): This counter value is raw data that is used as the denominator of a counter that presents a **instantaneous** arithmetic fraction. See PERF_LARGE_RAW_FRACTION for more information.

With example formula: `PERF_LARGE_RAW_FRACTION / PERF_LARGE_RAW_BASE`

But PERF_LARGE_RAW_BASE (1073939712) is also used there as the denominator for PERF_AVERAGE_BULK (1073874176).

Nevertheless, [Base Counter Types of WMI SDK docs](https://github.com/MicrosoftDocs/win32/blob/ede245a19159456eabafa4cc5fdbcf1e13e28397/desktop-src/WmiSdk/base-counter-types.md) says that PERF_AVERAGE_BASE (1073939458) is base for PERF_AVERAGE_BULK (1073874176). (Yes, it might be just one-way relation. Just implication, but not equivalence.)

Does SQL Server *"misuse"* the PERF_LARGE_RAW_BASE also for PERF_AVERAGE_BULK?

**Comment by WilliamAntonRohm** [comment]
@n9 -- thank you for your well-researched feedback.

@markingmyname -- please look into this issue.

**Comment by pmasl** [comment]
@n9 I’m addressing your feedback below. The existing wasn’t wrong as much as it was incomplete or over-simplified. Thanks for prompting this change. I'm changing to:

Performance counters where the `cntr_type` column value is 65792 display a snapshot of the last observed value only, not an average. 

Performance counters where the `cntr_type` column value is 272696320 or 272696576 display the average number of operations completed during each second of the sample interval. Counters of this type measure time in ticks of the system clock. For example, to get a snapshot-like reading of the last second only for the `Buffer Manager:Lazy writes/sec` and `Buffer Manager:Checkpoint pages/sec` counters, you must compare the delta between two collection points that are one second apart.    

Performance counters where the `cntr_type` column value is 537003264 display the ratio of a subset to its set as a percentage. For example, the `Buffer Manager:Buffer cache hit ratio` counter compares the total number of cache hits and the total number of cache lookups. As such, to get a snapshot-like reading of the last second only, you must compare the delta between the current value and the base value (denominator) between two collection points that are one second apart. The corresponding base value is the performance counter `Buffer Manager:Buffer cache hit ratio base` where the `cntr_type` column value is 1073939712.

Performance counters where the `cntr_type` column value is 1073874176 display how many items are processed on average, as a ratio of the items processed to the number of operations. For example, the `Locks:Average Wait Time (ms)` counters compares the lock waits per second with the lock requests per second, to display the average amount of wait time (in milliseconds) for each lock request that resulted in a wait. As such, to get a snapshot-like reading of the last second only, you must compare the delta between the current value and the base value (denominator) between two collection points that are one second apart. The corresponding base value is the performance counter `Locks:Average Wait Time Base` where the `cntr_type` column value is 1073939712.

**Comment by MikeRayMSFT** [comment]
Thanks @pmasl for fixing in https://github.com/MicrosoftDocs/sql-docs-pr/pull/18918
