### ISSUE TITLE
Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by shadinamrouti** [MicrosoftDocs/sql-docs#5879]
Please update this page for version Ubuntu 20.04 LTS

Note that there might be full support for 20.04
see this link:  https://packages.microsoft.com/config/ubuntu/20.04/prod.list

Also, I suggest to remove 16.04 because its end of life is Apr, 2021:

See: 
Version Name  | Released | End of life
Ubuntu 16.04 LTS | Apr 2016 | Apr 2021
Ubuntu 18.04 LTS | Apr 2018 | Apr 2023
Ubuntu 20.04 LTS | Apr 2020 | Apr 2025
Source: ubuntu.com

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-linux-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@shadinamrouti -- Shadi, thank you for your feedback.

@VanMSFT -- Van,  please look into this issue.

**Comment by VanMSFT** [comment]
Hi @shadinamrouti - Thanks for the feedback. Ubuntu 20.04 is currently not supported. This is on our radar, and when it is officially supported from our Product Team, we will make the proper revisions to our documents. We appreciate your attention to our docs!
