### ISSUE TITLE
ODBC: documentation inconsistency on retrieving attribute values

### ISSUE THREAD

**Issue by mversic** [MicrosoftDocs/sql-docs#5885]
[`SQLGetConnectAttr` documentation](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetconnectattr-function?view=sql-server-ver15) says:
> ValuePtr
> [Output] A pointer to memory in which to return the current value of the attribute specified by Attribute. For integer-type attributes, some drivers may only write the lower 32-bit or 16-bit of a buffer and leave the higher-order bit unchanged. Therefore, applications should use a buffer of SQLULEN and initialize the value to 0 before calling this function.
> 
> **If ValuePtr is NULL, StringLengthPtr will still return the total number of bytes** (excluding the null-termination character for character data) available to return in the buffer pointed to by ValuePtr.
> 
> StringLengthPtr
> [Output] A pointer to a buffer in which to return the total number of bytes (excluding the null-termination character) available to return in *ValuePtr. **If \*ValuePtr is a null pointer, no length is returned**. If the attribute value is a character string and the number of bytes available to return is greater than BufferLength minus the length of the null-termination character, the data in *ValuePtr is truncated to BufferLength minus the length of the null-termination character and is null-terminated by the driver.

I've highlighted the problematic section. One of these two sentences is incorrect and should be removed. What makes sense to me is that length should still be returned when `ValuePtr` is `NULL`. That way a user could get the required size for their pointer in the first request, allocate the correct size of the char array and then get the data in the second request. Otherwise, what is the point of allowing the `NULL` as a `*ValuePtr` value?
However, I've tested this on the `unixODBC` and no length is returned when `*ValuePtr` is `NULL`(at least for that implementation). I've also found some [IBM documentation](https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0000600.html) which also states that no length is returned when `*ValuePtr` is `NULL`.

The same goes for `SQLGetEnvAttr` and `SQLGetStmtAttr`

I'd be happy to open a PR if I knew what is correct.

**Comment by WilliamAntonRohm** [comment]
@mversic -- Marin, thank you for your well-researched feedback.  Once you have the answers, the process for creating a PR is:
- Navigate to the page of interest
- Select the "Edit" button at the top right of the page
- Select the "Pencil" icon on the right
- Modify the text within the text box in markdown format
- Name your file change and copy the link to your Git Issue into the "extended description" box
- Select "Propose file change"
- Select "Create pull request" on the 'Comparing changes' page
- Select "Create pull request" on the 'Open a pull request' page
- Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing this will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and list you as a contributor to the documentation.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
@v-makouz Can you take a look at this and determine which is the actual/correct behavior?

**Comment by v-makouz** [comment]
Looking at the code it appears that if valuePtr is NULL it won't return a length for the following types:
SQL_COPT_SS_PERF_QUERY
SQL_COPT_SS_BROWSE_CONNECT
SQL_COPT_SS_BROWSE_CACHE_DATA
SQL_COPT_SS_WARN_ON_CP_ERROR

For all other types it should return length regardless (if the length pointer is supplied).
