### ISSUE TITLE
Review the list of supported database Engines where it's possible to host reporting services database

### ISSUE THREAD

**Issue by lcanastreiro** [MicrosoftDocs/sql-docs#5887]
Hi all,

Please review the following documentation https://docs.microsoft.com/en-us/sql/reporting-services/install-windows/ssrs-report-server-create-a-report-server-database?view=sql-server-ver15&source=docs#database-server-version-requirements to highlight that SQL on Linux isn't a supported environment to host SQL Server Reporting Services Database.

Thanks Luís.

**Comment by WilliamAntonRohm** [comment]
@lcanastreiro -- Luís, thank you for your feedback.

@maggiesMSFT -- Maggie, please look into this issue.

**Comment by maggiesMSFT** [comment]
Thanks, @lcanastreiro ! I've updated the article per your suggestion.
#please-close
