### ISSUE TITLE
Incorrect information about retrieving metadata

### ISSUE THREAD

**Issue by kalendelaney** [MicrosoftDocs/sql-docs#5892]
SELECT * FROM sys.tables  
WHERE object_id = 1973582069

The above statement is said to return information about all the columns in the specified table. This is absolutely not true. First of all, there is no information about there the id comes from. You could have used a function to get that so that a known table name could be used:

SELECT * FROM sys.tables  
WHERE object_id = object_id('mytable')

But beyond that, is that this statement returns no information about columns. It returns general property information about the table but nothing about the columns in the table. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed157539-52dc-0dab-22ca-964143d7095d
* Version Independent ID: f8c8107c-8662-95e2-650b-1a1692a44db4
* Content: [View the Table Definition - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/view-the-table-definition?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/view-the-table-definition.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/view-the-table-definition.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@kalendelaney -- Kalen, thank you for your feedback.

@stevestein -- Steve, please look into this issue.
