### ISSUE TITLE
Microsoft JDBC now supports Uniqueidentifier types correctly, and failing to use them causes implicit conversion issues

### ISSUE THREAD

**Issue by vsabella** [MicrosoftDocs/sql-docs#5901]
The page recommends that the JDBC data type for SQL UNIQUEIDENTIFIER is "String" when in fact the JDBC driver now actually supports java's UUID data type.

Passing in a string results in an implicit conversion, and if that implicit conversion is on a where/join column then it can cause SQL to pick the wrong query plan. The document should be updated to reflect the extended data type support in the latest Microsoft JDBC drivers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed6f88c8-ab07-a261-b30e-0ba7e2302fde
* Version Independent ID: 2005b24f-8884-cd20-d501-68d6ea507935
* Content: [Using basic JDBC data types - SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-basic-data-types?view=sql-server-ver15)
* Content Source: [docs/connect/jdbc/using-basic-data-types.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/using-basic-data-types.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@vsabella -- Vito, thank you for your well-researched feedback.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
@vsabella Yes, the user can do SQLServerResultSet.getObject(x, UUID.class) to obtain a UUID object. However, the driver still returns the data as String when calling SQLServerResultSet.getUniqueIdentifier(), as well as accepting a String when calling SQLServerPrepareStatement.setUniqueIdentifier(x, String). Therefore, I think that the document should stay as it is (that the driver maps uniqueidentifier to String). If you are running into issues with implicit conversions between String and UUID, I recommend filing an issue to the GitHub repo: https://github.com/Microsoft/mssql-jdbc

Regards,
David

**Comment by David-Engel** [comment]
#please-close
