### ISSUE TITLE
No link to download the complete solution

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/sql-docs#5922]
There os no link I can find to download the complete Visual Studio solution. Is there a link to the repository?

---
#### Document Details

https://docs.microsoft.com/en-us/sql/connect/odbc/cpp-code-example-app-connect-access-sql-db?view=sql-server-ver15

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac828919-7780-c626-d071-724e0cbc5d56
* Version Independent ID: 47d85824-56f3-9fa1-4348-30c864bc756b
* Content: [C++ ODBC app accessing a SQL database - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/cpp-code-example-app-connect-access-sql-db?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/cpp-code-example-app-connect-access-sql-db.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/cpp-code-example-app-connect-access-sql-db.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@chanmmn Thanks for submitting feedback.

All files for the complete solution are available to copy and paste directly from the documentation page you referenced:
[ReadMe.txt](https://docs.microsoft.com/en-us/sql/connect/odbc/cpp-code-example-app-connect-access-sql-db?view=sql-server-ver15#a-readmetxt)
[odbcsql.cpp](https://docs.microsoft.com/en-us/sql/connect/odbc/cpp-code-example-app-connect-access-sql-db?view=sql-server-ver15#b-odbcsqlcpp-code)
[odbcsql.sln](https://docs.microsoft.com/en-us/sql/connect/odbc/cpp-code-example-app-connect-access-sql-db?view=sql-server-ver15#c-odbcsqlsln-code)
[odbcsql.vcxproj](https://docs.microsoft.com/en-us/sql/connect/odbc/cpp-code-example-app-connect-access-sql-db?view=sql-server-ver15#d-odbcsqlvcxproj-code)

Regards,
David

**Comment by chanmmn** [comment]
Thanks David,

Yes, put the 4 files in the same folder, open using Visual Studio, build it then can run.

**Comment by David-Engel** [comment]
#please-close
