### ISSUE TITLE
Create symlinks to 'SQLCMD' and 'BCP' under /usr/bin/ (which work for me )

### ISSUE THREAD

**Issue by rupeshrvk** [MicrosoftDocs/sql-docs#5923]
Create symlinks to 'SQLCMD' and 'BCP' under /usr/bin/ 

ln -sfn /opt/mssql-tools/bin/sqlcmd-13.0.1.0 /usr/bin/sqlcmd 
ln -sfn /opt/mssql-tools/bin/bcp-13.0.1.0 /usr/bin/bcp

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @rupeshrvk! Thanks for the feedback. Creating a symlink is definitely another way to have sqlcmd/bcp accessible from bash without having to navigate to mssql-tools/bin folder. We will evaluate adding this option in future documentation revisions. Thanks again!
