### ISSUE TITLE
Example computed column index requires explicit convert/cast

### ISSUE THREAD

**Issue by LarnuUK** [MicrosoftDocs/sql-docs#5926]
The [example](https://docs.microsoft.com/en-us/sql/relational-databases/json/index-json-data?view=sql-server-ver15#example-index) will need an explicit `CONVERT`/`CAST` on the returned value from `JSON_VALUE`. This is because the function returns an `nvarchar(4000)`, which is far too wide for an index. I didn't want to submit a PR as I don't  have a copy of (what I assume is) the Adventure Works 2019 database this example uses and end up with an example that causes truncation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 647be77d-8f01-6d16-7c7f-9a539199abc1
* Version Independent ID: 0ea0cc4f-b66e-e1ad-5a08-01a8b50aab41
* Content: [Index JSON data - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/index-json-data?view=sql-server-ver15)
* Content Source: [docs/relational-databases/json/index-json-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/index-json-data.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@LarnuUK -- Thom, thank you for your detailed feedback.  

@jovanpop-msft -- Jovan, please look into this issue.

**Comment by BrentOzar** [comment]
@LarnuUK technically, this works:

```
DROP TABLE IF EXISTS dbo.Tester;
CREATE TABLE dbo.Tester(col1 NVARCHAR(4000));
CREATE INDEX col1 ON dbo.Tester(col1);
```

It does return a warning, but this is only a warning - the index works fine until your JSON includes too wide of values:

`Warning! The maximum key length for a nonclustered index is 1700 bytes. 
The index 'col1' has maximum length of 8000 bytes. 
For some combination of large values, the insert/update operation will fail.`

**Comment by MikeRayMSFT** [comment]
@LarnuUK - thanks for submitting this. I'm following up with my team for a doc update.

Thanks @BrentOzar for the reply.

**Comment by MikeRayMSFT** [comment]
Update https://github.com/MicrosoftDocs/sql-docs-pr/pull/18927 is intended to resolve this issue. Thanks.
