### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by sardarw** [MicrosoftDocs/sql-docs#5927]
Where it says "Change Data Tracking", should it say "Change Tracking"?

Regards

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7967cb92-4205-31da-e7a3-6ee76091c9fb
* Version Independent ID: d947240d-76dd-036f-b1b2-814e85ba3e9f
* Content: [Temporal Table Considerations and Limitations - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-table-considerations-and-limitations?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/temporal-table-considerations-and-limitations.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/temporal-table-considerations-and-limitations.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@sardarw -- thank you for your question.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review this change in [private PR 18343](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18343).

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
