### ISSUE TITLE
typo UDATE should be UPDATE

### ISSUE THREAD

**Issue by sqlzim** [MicrosoftDocs/sql-docs#5935]
> You cannot update multiple properties at once using Transact-SQL. For example, the following UPDATE statement fails with an error because you cannot use the same column name twice in one UDATE statement.

typo: UDATE should be UPDATE
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466ede58-a68f-b170-914b-12404b13c2b1
* Version Independent ID: c5fa5444-8723-c737-5fb7-0898c555eb30
* Content: [Manipulating UDT Data - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-types/working-with-user-defined-types-manipulating-udt-data?view=sql-server-ver15)
* Content Source: [docs/relational-databases/clr-integration-database-objects-user-defined-types/working-with-user-defined-types-manipulating-udt-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/clr-integration-database-objects-user-defined-types/working-with-user-defined-types-manipulating-udt-data.md)
* Product: **sql**
* Technology: **clr**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@sqlzim -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
