### ISSUE TITLE
Login Failed for user 'sa'

### ISSUE THREAD

**Issue by UelisonSantos** [MicrosoftDocs/sql-docs#5939]
You should use MSSQL_SA_PASSWORD instead of sa_password

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by WilliamAntonRohm** [comment]
@UelisonSantos -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@vin-yu -- Vin, please review this change in [private PR 18345](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18345).

**Comment by thanhmanci** [comment]
@WilliamAntonRohm link is dead bro

**Comment by WilliamAntonRohm** [comment]
@thanhmanci -- Thanh, thank you for your followup.  That PR is in a private repo that we use for staging content before it goes live.

**Comment by WilliamAntonRohm** [comment]
@UelisonSantos -- the response from our expert is that `SA_PASSWORD` is correct.  

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

cc @vin-yu @dzsquared for awareness

**Comment by fkucuk** [comment]
strangely MSSQL_SA_PASSWORD worked for me.
