### ISSUE TITLE
What exactly does "SQL Server 2019 does not deprecate any features" mean?

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#5940]
The "Deprecated database engine features in SQL Server 2019 (15.x)" page currently states:

> SQL Server 2019 does not deprecate any features.

What does this mean _specifically_? It's quite ambiguous. Does it mean:

1. Starting in SQL Server 2019, _no features are deprecated anymore_! (i.e. features that had been deprecated in previous versions are now *un*deprecated)

   **or:**

2. "There are no _new_ deprecated or discontinued Database Engine features announced for SQL Server 2019 (15.x)." (similar to what is currently stated on the the "[Deprecated Database Engine Features in SQL Server 2017](https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-2017)" page:
    > **Note**
    > This list is identical to the SQL Server 2016 (13.x) list. There are no new deprecated or discontinued Database Engine features announced for SQL Server 2017 (14.x).

    )

Whichever meaning it happens to be, can this page please be updated to state, very specifically, what is meant? Thanks!

Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fd36271-def0-10d0-4fd4-bb8740149433
* Version Independent ID: 100621f6-da29-759e-4ac9-704c3b48fd97
* Content: [Deprecated database engine features in SQL Server 2019 - SQL Server 2019](https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-version-15?view=sql-server-ver15)
* Content Source: [docs/database-engine/deprecated-database-engine-features-in-sql-server-version-15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/deprecated-database-engine-features-in-sql-server-version-15.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@srutzky -- Solomon, thank you for your questions.  Hank Scorpio rules, or would!

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by MikeRayMSFT** [comment]
@srutzky Solomon, 

Thanks for noticing this. We need to update it. What it means is - we SQL Server 2019 doesn't deprecate add any additional features to the list of features that was already deprecated. I'm working with our engineering team to clarify what that means for customers. I also am working to get an explicit statement about any features that may have been announced as deprecated and then removed. 

I'm going to keep this open while I chase down more comprehensive answers.
