### ISSUE TITLE
Incorrect Link to Windows Server Edition for Failover Cluster

### ISSUE THREAD

**Issue by gjmscc** [MicrosoftDocs/sql-docs#5941]
Under: Describes Windows Failover Clustering Concepts and provides links to tasks related to Windows Failover Clustering

It links to Windows Server 2008 !? Surely this should be Windows Server 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8d0e40d-3a6e-79cb-4594-4fa453fcc2d8
* Version Independent ID: 0395eaf4-56cc-0bb1-34ae-701d31dc092f
* Content: [Always On failover cluster instances - SQL Server Always On](https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/windows/always-on-failover-cluster-instances-sql-server?view=sql-server-ver15)
* Content Source: [docs/sql-server/failover-clusters/windows/always-on-failover-cluster-instances-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/failover-clusters/windows/always-on-failover-cluster-instances-sql-server.md)
* Product: **sql**
* Technology: **failover-cluster-instance**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@gjmscc -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@cawrites -- please review [private PR 18353](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18353).

**Comment by cawrites** [comment]
@gjmscc thank you for contacting Microsoft. Your update will be reflected in the next refresh.

**Comment by cawrites** [comment]
#please-close
