### ISSUE TITLE
Add-AzureKeyVaultKey should be Add-AzKeyVaultKey

### ISSUE THREAD

**Issue by ydhondt** [MicrosoftDocs/sql-docs#5948]
The PowerShell sample on Azure Key Vault without Role Separation (Example) mentions

`
$akvKey = Add-AzureKeyVaultKey -VaultName $akvName -Name $akvKeyName -Destination "Software"
`

while it has to be 

`
$akvKey = Add-AzKeyVaultKey -VaultName $akvName -Name $akvKeyName -Destination "Software"
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1572cf3-2c25-0de0-691c-10d6bf3388bc
* Version Independent ID: 759b556c-4077-48b5-dc17-d5886d123a6b
* Content: [Provision Always Encrypted keys using PowerShell - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/configure-always-encrypted-keys-using-powershell?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/configure-always-encrypted-keys-using-powershell.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/configure-always-encrypted-keys-using-powershell.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@ydhondt -- thank you for bringing this to our attention.  I am looking into this article.

**Comment by ikshitiz** [comment]
@WilliamAntonRohm Created PR with changes #6078

**Comment by WilliamAntonRohm** [comment]
@ikshitiz -- Kshitij, thank you for your contribution.

@jaszymas -- please review either PR above.

**Comment by VanMSFT** [comment]
Addressed in https://github.com/MicrosoftDocs/sql-docs/pull/6078
