### ISSUE TITLE
KeyURL should be using Key.Kid rather than ID

### ISSUE THREAD

**Issue by ydhondt** [MicrosoftDocs/sql-docs#5949]
In the PowerShell sample on "Azure Key Vault without Role Separation (Example)" it states

`
$cmkSettings = New-SqlAzureKeyVaultColumnMasterKeySettings -KeyURL $akvKey.ID
`

This will work for most connections and drivers, but not for all. For example, the ODBC driver has an issue with it. A better setting should be

`
$cmkSettings = New-SqlAzureKeyVaultColumnMasterKeySettings -KeyURL $akvKey.Key.Kid
`

The difference between the two is that `$avkKey.ID` will include the port number (:443) in the url while `akvKey.Key.Kid` does not. Next to being the more correct and logical representation, it will also avoid potential issues with drivers like the ODBC one.

Actually, it might be best to extend the documentation with a note on this. The exact same problem exists for Azure Disk Encryption and is well documented over there. See the last paragraph of the [Set up a key encryption key (optional)](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption-key-vault-aad#bkmk_KEK) . The accompanying sample on that page does it correctly:

`
$keyEncryptionKeyUrl = (Get-AzKeyVaultKey -VaultName $KeyVaultName -Name $keyEncryptionKeyName).Key.kid;
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1572cf3-2c25-0de0-691c-10d6bf3388bc
* Version Independent ID: 759b556c-4077-48b5-dc17-d5886d123a6b
* Content: [Provision Always Encrypted keys using PowerShell - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/configure-always-encrypted-keys-using-powershell?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/configure-always-encrypted-keys-using-powershell.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/configure-always-encrypted-keys-using-powershell.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@ydhondt -- thank you for your considered feedback.

@jaszymas -- please look into this issue.

**Comment by jaszymas** [comment]
This has been addressed in https://github.com/MicrosoftDocs/sql-docs-pr/pull/18481#issuecomment-773511729.

**Comment by jaszymas** [comment]
#please-close
