### ISSUE TITLE
Minor Grammar Issue - Have vs. How

### ISSUE THREAD

**Issue by evans911** [MicrosoftDocs/sql-docs#5953]
[Enter feedback here]
The following procedures show you **have** to create a database protected by TDE using SQL Server Management Studio and by using Transact-SQL. 

Should be: The following procedures show you **how** to create a database protected by TDE using SQL Server Management Studio and by using Transact-SQL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94439bc6-f72b-9b0e-68fd-997f702b45c1
* Version Independent ID: 21ffb1bd-3715-11f8-540c-7e6c93e58ba3
* Content: [Move a TDE-protected database to another SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/move-a-tde-protected-database-to-another-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/move-a-tde-protected-database-to-another-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/move-a-tde-protected-database-to-another-sql-server.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@evans911 -- thank you for catching this.  I am updating the article.
