### ISSUE TITLE
Can readable scale AG replicas for the same AG locate on the same node?

### ISSUE THREAD

**Issue by AnyiYang** [MicrosoftDocs/sql-docs#5969]
In the doc for AG, it only mentions that the replicas for the same AG cannot be located on the same WSFC cluster node:
"For a given availability group, the availability replicas must be hosted by separate instances of SQL Server residing on different nodes of a WSFC cluster."

According to our test, the readable scale AG also has such limitation. But in the official document, it is not mentioned and readable scale AG does not need WSFC. Could you please help to verify that and add certain statement in the document for readable scale AG?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d2fdfcd-bb40-75ae-21ba-f9019f816d5a
* Version Independent ID: cfecc4e2-f246-809e-6445-d96eb753e101
* Content: [Use read-scale with availability groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/read-scale-availability-groups?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/read-scale-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/read-scale-availability-groups.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@AnyiYang -- thank you for your feedback.

@cawrites -- please look into this issue.

**Comment by AnyiYang** [comment]
Hi team,

Is there any update on this?

**Comment by cawrites** [comment]
@AnyiYang thank you for contacting Microsoft regarding this issue. We are researching your question and will reply with an update.

**Comment by cawrites** [comment]
@AnyiYang we will make the following revision to address this concern:
"For a given availability group, the availability replicas must be hosted by separate instances of SQL Server residing on different nodes of a WSFC cluster, with the exception of read-scale availability groups, which have no cluster requirement." This should appear in the next documentation refresh.

**Comment by AnyiYang** [comment]
@cawrites Do you mean that for readable-scale availability group, there is no need to put different replicas on different nodes? Have you done any test on that? In my environment, we cannot configure different replicas for the same readable-scale availability group on the same node. Could you confirm that?

**Comment by cawrites** [comment]
@AnyiYang I conducted some research on your comment, viewing it as a quote from the content. However, I am unable to find this exact syntax to update. Was your comment an extension of your question, or were you quoting? The associated content does not have the syntax you mentioned.

**Comment by cawrites** [comment]
@AnyiYang the information I have obtained is that replicas in any AG, read-scale, or regular AG should always be on different nodes.

**Comment by cawrites** [comment]
@AnyiYang we appreciate your patience as we researched your question. We have provided the latest update. Thank you for contacting Microsoft.

**Comment by cawrites** [comment]
#please-close
