### ISSUE TITLE
Incorrect T-SQL meaning of '--' (copy/paste)

### ISSUE THREAD

**Issue by MarcToons** [MicrosoftDocs/sql-docs#5970]
Under the **Validate All Input** section, in the `[Input character, Meaning in Transact-SQL]` table, the meaning for `--` is incorrect: it should be something like *single comment line marker* (instead of ~~*Character data string delimiter*~~).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75b0c5a5-dadb-192a-c466-23275c8409d3
* Version Independent ID: 179ebcda-6d12-2e9c-3df3-902fc038388c
* Content: [SQL Injection - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/sql-injection?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/sql-injection.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/sql-injection.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@Toons33 -- MarcT, thank you for your feedback.  I am looking into this article.
