### ISSUE TITLE
What is a "Unicode C data type"?

### ISSUE THREAD

**Issue by autoantwort** [MicrosoftDocs/sql-docs#5971]
I can not find a definition what a `Unicode C data type` should be? It is used in the Summary section (or simple search for `Unicode C data type`, there is only one match).
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c250aaf-b36a-f589-f64a-abdfb64497f7
* Version Independent ID: d446db5e-d5c8-d06e-ef50-525999e87e56
* Content: [SQLBindParameter Function - SQL Server](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlbindparameter-function?view=sql-server-ver15)
* Content Source: [docs/odbc/reference/syntax/sqlbindparameter-function.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/syntax/sqlbindparameter-function.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@autoantwort -- thank you for your question.  Please see:
- [Unicode Data](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/unicode-data)
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by autoantwort** [comment]
Ahh. I searched this kind of information, but I didn't find them. I searched for the C data types and hoped there where something abound Unicode. But there is`t (Or I did not find the information). I suggest: simply make the `Unicode C data type` string a link to the site you mentioned. Then nobody has to search it.
