### ISSUE TITLE
Error in example one

### ISSUE THREAD

**Issue by pdarkness** [MicrosoftDocs/sql-docs#5977]
Hi,

In example one this string 'ReturnDatesAsStrings '=> true just returned an error (PHP 5.6)
It worked after changing it to 'ReturnDatesAsStrings' => true

Also you might want to be more consistant in your use of either " or '.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b071468-f2a7-ff6a-a129-184e41af8408
* Version Independent ID: 3dd277ec-014b-9ece-67d6-b889d025b7b1
* Content: [Retrieve Date and Time Types as Strings Using the SQLSRV Driver - SQL Server](https://docs.microsoft.com/en-us/sql/connect/php/how-to-retrieve-date-and-time-type-as-strings-using-the-sqlsrv-driver?view=sql-server-ver15)
* Content Source: [docs/connect/php/how-to-retrieve-date-and-time-type-as-strings-using-the-sqlsrv-driver.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/how-to-retrieve-date-and-time-type-as-strings-using-the-sqlsrv-driver.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@pdarkness -- Knútur, thank you for bringing this to our attention.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

cc @David-Engel for the quotation marks
