### ISSUE TITLE
Command to Get All Cluster Values incorrect

### ISSUE THREAD

**Issue by simonwhybrow-cbre** [MicrosoftDocs/sql-docs#6016]
Command to get all cluster values is incorrect.
Article states it as:

*  Get-Cluster | fl \

This should be:

*  Get-Cluster | fl *

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8705fa-b6ec-b933-a355-5de9eacc807f
* Version Independent ID: e6cd791d-b0f4-663d-5d07-b2850784cf37
* Content: [Availability group lease health check timeout - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/availability-group-lease-healthcheck-timeout?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/availability-group-lease-healthcheck-timeout.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/availability-group-lease-healthcheck-timeout.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@simonwhybrow-cbre -- thank you for bringing this to our attention. I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@cawrites -- please review [private PR 18446](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18446).

**Comment by simonwhybrow-cbre** [comment]
Hi, I got notification that this has been closed, but I can see that the article hasn't been updated yet?

**Comment by cawrites** [comment]
@simonwhybrow-cbre the update will occur with the next content refresh. I cannot give an approximate time. But I have reviewed this issue an update will be applied. The refresh will be completed this week. Thank you.

**Comment by simonwhybrow-cbre** [comment]
@cawrites thank you for the update, much appreciated.
