### ISSUE TITLE
What are the install instructions for 20.04? 

### ISSUE THREAD

**Issue by JerryGeis** [MicrosoftDocs/sql-docs#6023]
I tried this:
	wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
	add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/18.04/mssql-server-2019.list)"
	apt-get update
	apt-get install mssql-cli

did not work.  This page only shows for upto 16. I need install for 20.04

Jerry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@JerryGeis -- Jerry, thank you for the feedback. Ubuntu 20.04 is currently not supported. This is on our radar, and when it is officially supported from our Product Team, we will make the proper revisions to our documents. We appreciate your attention to our docs!
