### ISSUE TITLE
CREATE AVAILABILITY GROUP SYNTAX improvement - "Normal" vs Basic vs Distributed

### ISSUE THREAD

**Issue by RobAshton-IM** [MicrosoftDocs/sql-docs#6029]
The syntax displayed for the [CREATE AVAILABILITY GROUP](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-availability-group-transact-sql?view=sql-server-ver15#syntax) command could be improved around the usage of BASIC and DISTRIBUTED keywords.

Currently, the syntax definition gives the impression that the BASIC and DISTRIBUTED keywords could both be used in the same command. However, careful reading of the page describing [Basic Availability Groups](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups?view=sql-server-ver15#limitations) shows that a Basic Availability Group cannot be part of a Distributed Availability Group.

I think it makes more sense to change the syntax description for the command to show that the BASIC and DISTRIBUTED keywords are both optional and mutually exclusive by changing them from:
`
<with_option_spec>::=   
...
  | BASIC  
  | DISTRIBUTED
...
`

to:
`
<with_option_spec>::=   
...
  | [ BASIC  | DISTRIBUTED ]
...
`

**Comment by RobAshton-IM** [comment]
Apologies for not linking this directly to the page involved; I couldn't see an option to provide direct feedback from the page itself.

**Comment by WilliamAntonRohm** [comment]
@RobAshton-IM -- thank you for your well-researched feedback.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review [private PR 18451](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18451).
