### ISSUE TITLE
Lock:Released Event Class - possible incorrect description for Mode column

### ISSUE THREAD

**Issue by OleksiiKovalov** [MicrosoftDocs/sql-docs#6031]
Looks like "Mode" column contains incorrect/incomplete description "Resulting mode after the lock was released." in part of "0=NULL - Compatible with all other lock modes (LCK_M_NL)"
According to SQL Profiler Mode "0" does not release any locks and any other Modes (at least mode 5=Exclusive Lock (LCK_M_X)) releases appropriate lock type.
1st marked line places X lock, 2nd line "releases" with mode 0 and 3rd line actually released X lock

![Screenshot_4](https://user-images.githubusercontent.com/26844170/106490336-62dac380-64be-11eb-8d56-28493c526720.png)

**Comment by WilliamAntonRohm** [comment]
@OleksiiKovalov -- Oleksii, thank you for your well-researched feedback.

@stevestein -- Steve, please look into this issue.

**Comment by stevestein** [comment]
@OleksiiKovalov - thanks for the feedback.

re: https://docs.microsoft.com/sql/relational-databases/event-classes/lock-released-event-class?view=sql-server-ver15

Could you provide the exact change that you're suggesting we consider making? 


Thanks

**Comment by OleksiiKovalov** [comment]
hi @stevestein , sorry for the delay.
I'll do some research and will suggest changes

**Comment by rothja** [comment]
@OleksiiKovalov Thanks, again, for the feedback on the docs. If you do get a chance to suggest what you would change here, you can add your suggestions to this thread. For now, I will close the issue, but I will gladly reopen if you provide a few more details on what you would change. Alternatively, you could click the edit button on the article to suggest the direct changes you would make. This would make you a collaborator on the top of the article as well. It is completely up to you. Thank you! #reassign:rothja #please-close

**Comment by XSpringSun** [comment]
@OleksiiKovalov  Hello, excuse me, have you found the answer to this question? The document description is correct? the "model" description use "after",I think it should be "on".
