### ISSUE TITLE
dbo.sp_HexToChar is not needed anymore

### ISSUE THREAD

**Issue by JediSQL** [MicrosoftDocs/sql-docs#6034]
Hi,

The PROCEDURE dbo.sp_HexToChar sample code is not needed anymore, because the CONVERT statement now supports conversion of binary values to "readable hexadecimal string[s]."

See:
https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql#h-using-convert-with-binary-and-character-data

HTH,
Dan Jameson

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbb8bff9-6a43-9267-629c-c32d1aeb0a46
* Version Independent ID: 0695f967-7fb8-e300-dc13-520a23332236
* Content: [OLE Automation Return Codes and Error Information - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/ole-automation-return-codes-and-error-information?view=sql-server-ver15)
* Content Source: [docs/relational-databases/stored-procedures/ole-automation-return-codes-and-error-information.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/stored-procedures/ole-automation-return-codes-and-error-information.md)
* Product: **sql**
* Technology: **stored-procedures**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by JediSQL** [comment]
Hi,
I just also noticed this in the first paragraph. The first paragraph should end with a number having a negative sign:
... HRESULT has the form -214nnnnnnn.

**Comment by WilliamAntonRohm** [comment]
@JediSQL -- Dan, thank you for your feedback.

@stevestein -- Steve, please look into this issue.

**Comment by rothja** [comment]
@MikeRayMSFT Mike, could you please take a look at this issue and see what changes we might need to make? @JediSQL I apologize for the delay on this issue. Thank you! #reassign:mikeraymsft

**Comment by JediSQL** [comment]
That's OK. I've got old items in my backlog, too 😃.

**Comment by MikeRayMSFT** [comment]
An update is going to be published later today. Thank you, Mike

**Comment by JediSQL** [comment]
Looks good!
