### ISSUE TITLE
Ticks Not Right

### ISSUE THREAD

**Issue by CubeSpark** [MicrosoftDocs/sql-docs#6037]
The ticks are in the wrong place in this document. See the descriptions for Example B and Example C. There are tick marks, like this.....:    _The following example creates a geomet**ry``Poin**t instance representing the point (3, 4) w_  .....   There ought NOT  be NO tick marks, correct?   It reads as if the tick marks are some kind of weird "markdown" anomaly.  It might tick someone off. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 359226f6-b858-ffab-59ac-474e43381fd3
* Version Independent ID: 0b8aaaa0-a09a-c72d-eb08-963d631aaec9
* Content: [Point - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/point?view=sql-server-ver15)
* Content Source: [docs/relational-databases/spatial/point.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/spatial/point.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by MladjoA** [comment]
@CubeSpark , thanks Robert, the pull request is on its way.

**Comment by MladjoA** [comment]
#please-close

**Comment by CubeSpark** [comment]
Awesome !   Maybe you can help with the next one?  Bulk Load Format File xsi:type for GEOMETRY Not Available
#6047
