### ISSUE TITLE
Wrong Date for hot fix.  s/b 2021?

### ISSUE THREAD

**Issue by gregsoc** [MicrosoftDocs/sql-docs#6039]
Wrong Date for hot fix.  s/b 2021?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f818cae2-8091-38c6-217c-328f5aa12b99
* Version Independent ID: 0a6efa72-49c2-12c4-4095-8fc094747b14
* Content: [Azure Data Studio release notes - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/release-notes-azure-data-studio?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/release-notes-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/release-notes-azure-data-studio.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
@gregsoc -- Curtis, thank you for catching that.  I have updated the article and it should be live by tomorrow.
