### ISSUE TITLE
Might be helpful to include reference to SQLPackage executable

### ISSUE THREAD

**Issue by BredonHill** [MicrosoftDocs/sql-docs#6045]
[To create DACPAC in a pipeline](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-pipelines?view=sql-server-ver15)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06bbcc85-68e9-ee44-04ad-26acb92a195a
* Version Independent ID: 71678aad-04f0-8951-5242-c89fc79d077e
* Content: [Extract a DAC From a Database - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/extract-a-dac-from-a-database?view=sql-server-ver15)
* Content Source: [docs/relational-databases/data-tier-applications/extract-a-dac-from-a-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/extract-a-dac-from-a-database.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@BredonHill -- thank you for your feedback.  I am updating the article.
