### ISSUE TITLE
Repo is pointing to prod.list; adutil is still in preview

### ISSUE THREAD

**Issue by bishrest-msft** [MicrosoftDocs/sql-docs#6050]
[Enter feedback here]
For all distros (RHEL, Ubuntu, and SLES), the repo is pointing to prod.list it should be mssql-server-preview.list. 

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84e4ebac-6e2e-f188-e382-4e8d9940f8fb
* Version Independent ID: c256593c-499f-1cf9-9f6b-eba3516de73a
* Content: [Configure Active Directory authentication with SQL Server on Linux using adutil - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-ad-auth-adutil-tutorial?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-ad-auth-adutil-tutorial.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-ad-auth-adutil-tutorial.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@bishrest-msft -- thank you for bringing this to our attention.

@amvin87 -- please look into this issue.

**Comment by amvin87** [comment]
@bishrest-msft, please help me with details so I understand the feedback better.  As far as i see, the document rightly shows the adutil_preview package location to prod.repo.
For Rhel: https://packages.microsoft.com/config/rhel/8/prod.repo
For Ubuntu: https://packages.microsoft.com/config/ubuntu/18.04/prod.list
For SLES: https://packages.microsoft.com/config/sles/12/prod.repo

**Comment by VanMSFT** [comment]
Closing this as it seems we have provided the answer.

#please-close
