### ISSUE TITLE
Installation Error : MSSQL Tool won't install

### ISSUE THREAD

**Issue by yezz123** [MicrosoftDocs/sql-docs#6057]
When i try to install the MSSQL-tool :
```
sudo apt-get install mssql-tools unixodbc-dev
```
He give me this i try it on both `Ubuntu20.04.2LTS` & `CentOS-8.3.2011` :
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mssql-tools is already the newest version (17.7.1.1-1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mssql-tools : Depends: msodbcsql17 (>= 17.3.0.0) but it is not going to be installed
 unixodbc-dev : Depends: unixodbc (= 2.3.7)
                Depends: odbcinst1debian2 (= 2.3.7) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by dzsquared** [comment]
Starting with the issue you ran into with Ubuntu 20.04, confirming that you ran these 4 commands: (note that the package URL is changed for 20.04)

```
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
sudo apt-get update 
sudo apt-get install mssql-tools unixodbc-dev
```

If issues persist you can manually install the 2 listed dependencies from your error message

> The following packages have unmet dependencies:
 mssql-tools : Depends: msodbcsql17 (>= 17.3.0.0) but it is not going to be installed
 unixodbc-dev : Depends: unixodbc (= 2.3.7)
                Depends: odbcinst1debian2 (= 2.3.7) but it is not going to be installed

with the following:
```
sudo apt-get install msodbcsql17 odbcinst1debian2  unixodbc
```

**Comment by dzsquared** [comment]
#assign:dzsquared

**Comment by yezz123** [comment]
I do this and when i do this command :
```
sudo apt-get install msodbcsql17 odbcinst1debian2  unixodbc
```
he show me this : 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
msodbcsql17 is already the newest version (17.7.1.1-1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unixodbc : Depends: libodbc1 (>= 2.3.7) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by dzsquared** [comment]
Are you able to install libodbc1 with:
`sudo apt-get install libodbc1`

It may have some conflicting packages, which would require installing with:
`sudo apt install libodbc1`

**Comment by yezz123** [comment]
I guess now its work : 
`sudo apt-get install libodbc1`
and its successful : 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libfprint-2-tod1 libllvm10 libltdl7:i386 libreadline8:i386 libsss-nss-idmap0
  odbcinst:i386 odbcinst1debian2:i386 pigz slirp4netns
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  msodbcsql17 unixodbc-bin
The following packages will be REMOVED:
  libodbc1:i386 msodbcsql17 mssql-tools unixodbc:i386
The following NEW packages will be installed:
  libodbc1
0 upgraded, 1 newly installed, 4 to remove and 41 not upgraded.
Need to get 511 kB of archives.
After this operation, 179 kB disk space will be freed.
Do you want to continue? [Y/n] Y
Get:1 https://packages.microsoft.com/ubuntu/20.10/prod groovy/main amd64 libodbc1 amd64 2.3.7 [511 kB]
Fetched 511 kB in 3s (147 kB/s)   
(Reading database ... 329349 files and directories currently installed.)
Removing mssql-tools (17.7.1.1-1) ...
Removing msodbcsql17 (17.7.1.1-1) ...
Removing unixodbc:i386 (2.3.6-0.1build1) ...
Removing libodbc1:i386 (2.3.6-0.1build1) ...
Selecting previously unselected package libodbc1:amd64.
(Reading database ... 329296 files and directories currently installed.)
Preparing to unpack .../libodbc1_2.3.7_amd64.deb ...
Unpacking libodbc1:amd64 (2.3.7) ...
Setting up libodbc1:amd64 (2.3.7) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...

```

**Comment by yezz123** [comment]
> Starting with the issue you ran into with Ubuntu 20.04, confirming that you ran these 4 commands: (note that the package URL is changed for 20.04)
> 
> ```
> curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
> curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
> sudo apt-get update 
> sudo apt-get install mssql-tools unixodbc-dev
> ```
> 
> If issues persist you can manually install the 2 listed dependencies from your error message
> 
> > The following packages have unmet dependencies:
> > mssql-tools : Depends: msodbcsql17 (>= 17.3.0.0) but it is not going to be installed
> > unixodbc-dev : Depends: unixodbc (= 2.3.7)
> > Depends: odbcinst1debian2 (= 2.3.7) but it is not going to be installed
> 
> with the following:
> 
> ```
> sudo apt-get install msodbcsql17 odbcinst1debian2  unixodbc
> ```

But when i try to do those commands and download it the same result i get : 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
msodbcsql17 is already the newest version (17.7.1.1-1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unixodbc : Depends: libodbc1 (>= 2.3.7) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by cawrites** [comment]
@yezz123 based on your comments it appears the resolution provided worked on Feb 9th. It appears previous comments were reposted. We will mark this as solved. Thank you for contacting Microsoft.

**Comment by Tuckertcs** [comment]
I've recently ran into this same issue, though the proposed solution doesn't work for me for some reason. The command `sudo apt-get install libodbc1` (both the apt and apt-get version) yielded this result:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libodbc1 : PreDepends: multiarch-support but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by dzsquared** [comment]
@Tuckertcs - it can be difficult for us to troubleshoot individual environment issues through the docs issues, so it's usually recommended to check with a community like StackOverflow.  Among others, this thread may be helpful: https://stackoverflow.com/questions/62387396/unable-install-sqlserver-tool-in-ubuntu-20

**Comment by scottstensland** [comment]
this is still very broken

https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15&tabs=debian18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline

will break your ubuntu package system   

root@oslo /etc/apt # sudo apt-get -f install -y 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libodbc1
Suggested packages:
  msodbcsql17 unixodbc-bin
The following NEW packages will be installed:
  libodbc1
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
2 not fully installed or removed.
Need to get 486 kB of archives.
After this operation, 623 kB of additional disk space will be used.
Get:1 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 libodbc1 amd64 2.3.11-1 [486 kB]
Fetched 486 kB in 0s (1,047 kB/s)
(Reading database ... 754986 files and directories currently installed.)
Preparing to unpack .../libodbc1_2.3.11-1_amd64.deb ...
Unpacking libodbc1:amd64 (2.3.11-1) ...
dpkg: error processing archive /var/cache/apt/archives/libodbc1_2.3.11-1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libodbc.so.2.0.0', which is also in package libodbc2:amd64 2.3.9-5
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libodbc1_2.3.11-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)



this bug in microsoft odbc packages has been nagging for ever

please fix

**Comment by WilliamAntonRohm** [comment]
@scottstensland -- Scott, thank you for your follow-up.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)
