### ISSUE TITLE
Change tracking is supported by <AZURE> SQL Database

### ISSUE THREAD

**Issue by sethsanuMSFT** [MicrosoftDocs/sql-docs#6060]
[Enter feedback here]
"Change tracking is supported by SQL Database"
should be
Change tracking is supported by Azure SQL Database

to reduce confusion. Particularly since the related Change Data Capture is in private preview for Azure SQL and this documentation will change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5064f6a-f469-4b7c-101c-e62038f1efb6
* Version Independent ID: 4e830181-4699-703f-cf74-5c468628c082
* Content: [Track Data Changes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/track-data-changes-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/track-changes/track-data-changes-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/track-data-changes-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@sethsanuMSFT -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@rothja -- Jason, please review [private PR 18590](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18590) containing this change.
