### ISSUE TITLE
Typo: "If we temp table example previously described"

### ISSUE THREAD

**Issue by MarkFreemanBDO** [MicrosoftDocs/sql-docs#6069]
Typo:            "If we temp table example previously described".
It seem that "**In the** temp table example previously described" is what was intended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 334c00d1-26f7-8a39-b3d7-50e44d4780cb
* Version Independent ID: 640bbf7e-faa1-e8b1-d8b2-34e832ab6ca6
* Content: [Contained Database Collations - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/contained-database-collations?view=sql-server-ver15#contained-databases)
* Content Source: [docs/relational-databases/databases/contained-database-collations.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/contained-database-collations.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@MarkFreemanBDO -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
