### ISSUE TITLE
Wishing the note about PowerShell version.

### ISSUE THREAD

**Issue by NewGyu** [MicrosoftDocs/sql-docs#6071]
I wanted to run the PowerShell script described on this page to configure `Always Encrypted` with KeyVault. But the SQL Provider (which is bundled with PS7.0.2) did not support `authentication` keyword.

```
# Connect to your database (Azure SQL database).
Import-Module "SqlServer"
$serverName = "<Azure SQL server name>.database.windows.net"
$databaseName = "<database name>"
# Change the authentication method in the connection string, if needed.
$connStr = "Server = " + $serverName + "; Database = " + $databaseName + "; Authentication = Active Directory Integrated"
$database = Get-SqlDatabase -ConnectionString $connStr

Get-SqlDatabase: Keyword not supported: 'authentication'. <--- this error raised.
```

I found some issue about this message. They seem to say that this error depends on PS version.

* https://github.com/MicrosoftDocs/azure-docs/issues/47257

In order to use `authentication` keyword on PS7 which is based on .Net Core, it was necessary to install `Microsoft.Data.Sql`. I spent a lot of time to investigate this.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1572cf3-2c25-0de0-691c-10d6bf3388bc
* Version Independent ID: 759b556c-4077-48b5-dc17-d5886d123a6b
* Content: [Provision Always Encrypted keys using PowerShell - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/configure-always-encrypted-keys-using-powershell?view=sql-server-ver15#azure-key-vault-without-role-separation-example)
* Content Source: [docs/relational-databases/security/encryption/configure-always-encrypted-keys-using-powershell.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/configure-always-encrypted-keys-using-powershell.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@NewGyu -- thank you for your thorough feedback.

@jaszymas -- please look into this issue.

**Comment by VanMSFT** [comment]
Hi @NewGyu! Thank you for the feedback, and sorry for your troubles. Yes, if you are using PowerShell with .NET Core, you will need to use Microsoft.Data.SqlClient. Unfortunately, this issue doesn't just apply to Always Encrypted, and the article referenced is not a good place to address this. We will look at other means of clarifying these issues, and your input is very much appreciated. I will close this issue for now, but please feel free to @ me if you have any concerns. Thanks again!
