### ISSUE TITLE
Wrong section name or wrong content

### ISSUE THREAD

**Issue by rajapadmanaban** [MicrosoftDocs/sql-docs#6072]
Hi,

In this page, under the section name "Using SQL Server Management Studio" and  under the topic "To configure SQL Server Agent" the steps ask the user go to control panel and configure. None of the steps are related to using SQL Server management studio. Either changing the section name or the content would make the page look correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4169a35-ff35-53ad-f184-85ea95075817
* Version Independent ID: 32157654-f726-53d8-59aa-5199e44b1625
* Content: [Configure SQL Server Agent - SQL Server Agent](https://docs.microsoft.com/en-us/sql/ssms/agent/configure-sql-server-agent?view=sql-server-ver15)
* Content Source: [docs/ssms/agent/configure-sql-server-agent.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/configure-sql-server-agent.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@rajapadmanaban -- thank you for your feedback.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
@rajapadmanaban

Thank you for your comment.

I see what you are discussing here.

I will review the section and make the appropriate changes if needed.

thank you.

**Comment by markingmyname** [comment]
Change should be live by end of the week.

thank you.
