### ISSUE TITLE
Details for M1 architecture

### ISSUE THREAD

**Issue by lamon82** [MicrosoftDocs/sql-docs#6082]
Hallo,

The page is well documented. However, I’m missing the description for the M1 architecture as I haven’t been able to install the ODBC driver.
Would it be possible to extend it?

Kind regards,
Raphael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c0de6fb-19ae-ff6f-8e73-ce66fa94bd64
* Version Independent ID: 34edd099-f4fe-4ac3-cdd4-abc87b35270b
* Content: [Install the Microsoft ODBC driver for SQL Server (macOS) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
Thanks for submitting feedback.

Support for the M1 architecture has not yet been added to the Microsoft ODBC Driver for SQL Server. The instructions will be extended when that happens. It looks like we need to note that on the system requirements page now, so I'll address that separately.

Regards,
David

#please-close
