### ISSUE TITLE
Sql script is incorrect in tutorial

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/sql-docs#6083]
---
**Issue moved from MicrosoftDocs/feedback#3418**
- Please respond to @IvanKondral.

---

_From @IvanKondral on Monday, January 25, 2021 10:43:08 AM_

**Describe the bug**
https://docs.microsoft.com/en-us/sql/integration-services/lesson-1-6-adding-and-configuring-the-lookup-transformations?view=sql-server-ver15
There is a wrong sql query that uses Sales.Currency which has not been described before.
Also in downloaded lesson 1 result this query is different

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3418**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Monday, January 25, 2021 10:43:09 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by WilliamAntonRohm** [comment]
@gewarren -- Genevieve, please pass this along to Ivan:

- @IvanKondral -- Ivan, thank you for your feedback.  We are looking into updating this article.

@chugugrace -- Grace, please look into this issue.

**Comment by ktoliver** [comment]
After email discussion with @chugugrace, the issue is resolved in merged PR https://github.com/MicrosoftDocs/sql-docs/pull/6152. The fix should be live later today. I've responded to and closed the other pull requests that propose updates to resolve the issue.

**Comment by WilliamAntonRohm** [comment]
#please-close
