### ISSUE TITLE
collation change using the sqlservr command should be documented

### ISSUE THREAD

**Issue by AdmiralSnyder** [MicrosoftDocs/sql-docs#6087]
after asking a coworker, this solved my problem:
sqlservr -m -T4022 -T3659 -s"<<ServerName>>" -q"Latin1_General_CI_AS"

(see here for background: https://www.mssqltips.com/sqlservertip/3519/changing-sql-server-collation-after-installation/ )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca70403-237f-0160-7d1f-5817e40b5d25
* Version Independent ID: 9993116a-bcec-e054-1cbe-82c3ad603ef6
* Content: [Set or Change the Server Collation - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-server-collation?view=sql-server-ver15)
* Content Source: [docs/relational-databases/collations/set-or-change-the-server-collation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/set-or-change-the-server-collation.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@AdmiralSnyder -- Alexander, thank you for your feedback and details.

@stevestein -- Steve, please look into this issue.

**Comment by stevestein** [comment]
@AdmiralSnyder - thanks for the feedback. I created an internal work item (1829320) to investigate adding this example to the article.

Thanks

**Comment by rothja** [comment]
@AdmiralSnyder Thanks, again, for the suggestion! Now that we are tracking this documentation improvement internally, I am going to close the issue. Appreciate your engagement with our docs! #reassign:rothja #please-close
