### ISSUE TITLE
sp_execute_external_script does not exist

### ISSUE THREAD

**Issue by jvanderweele** [MicrosoftDocs/sql-docs#6093]
The page outlines to run: 

sp_execute_external_script

However, the error:
Msg 2812, Level 16, State 62, Line 1
Could not find stored procedure 'sp_execute_external_script'.

Indicates this sp does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 920d11c0-3834-248b-ff4f-65bc04313ff3
* Version Independent ID: 6214d3bb-7794-cce7-7345-b50699a0d46c
* Content: [Azure Data Studio notebooks (Python, R) - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/install/sql-machine-learning-azure-data-studio?view=sql-server-ver15)
* Content Source: [docs/machine-learning/install/sql-machine-learning-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/install/sql-machine-learning-azure-data-studio.md)
* Product: **sql**
* Technology: **machine-learning-services**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@jvanderweele Which SQL platform are you using? Have you installed/enabled Machine Learning Services? [sp_execute_external_script](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-execute-external-script-transact-sql?view=sql-server-ver15) works only with [SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/sql-server-machine-learning-services?view=sql-server-ver15) or [Azure SQL Managed Instance Machine Learning Services](https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/machine-learning-services-overview).

**Comment by jvanderweele** [comment]
@dphansen Thank you. I was working through the page and I think that was something I either missed or wasn't obvious. I've now been able to execute that external script with the SQL kernel.

I'm just beginning to delve into these methods, I'm easily able to use Python and SQL in the Azure Data Studio, I've been trying to get R going. Lots of learning happening here as a first-time attempting these connections/installs.

Thanks for your guidance.

**Comment by dphansen** [comment]
@jvanderweele Happy to help. We have a good number of [Python](https://docs.microsoft.com/en-us/sql/machine-learning/tutorials/python-tutorials?view=sql-server-ver15) and [R tutorials/quickstarts](https://docs.microsoft.com/en-us/sql/machine-learning/tutorials/r-tutorials?view=sql-server-ver15) that I'd recommend you take a look at.
