### ISSUE TITLE
Intellisense for <CredentialName> is broken

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#6099]
Intellisense (running SSMS 18.8, so shouldn't happen) is seeing credentialName as incorrect, even though the statement runs.

For example:
CREATE DATABASE SCOPED CREDENTIAL **job_credential** WITH IDENTITY 'job_credential', 
  SECRET = 'insertpasswordsamplehere';
GO

job_credential will get the red squiggly line, even though the statement will run properly.  After that, IDENTITY will also get a squiggly line, but this is probably because it is not recognizing the syntax earlier on in the statement.

**Comment by WilliamAntonRohm** [comment]
@PrometheusRising1 -- thank you for your feedback.  Please consider adding this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

Are you following a particular docs.microsoft.com article?

**Comment by PrometheusRising1** [comment]
This was for the following page that does not have a comment section:
https://docs.microsoft.com/en-us/azure/azure-sql/database/elastic-jobs-tsql-create-manage

**Comment by WilliamAntonRohm** [comment]
@PrometheusRising1 -- thank you for your followup.  I would send you our standard help links but you've seen them already.  Your input is appreciated!

@jaredmoo -- please look into this potential documentation issue.

**Comment by cawrites** [comment]
@PrometheusRising1 thank you for contacting Microsoft. I apologize for the delay you've experienced in getting a response to this issue. I understand the frustration of getting errors in T-SQL statements. We will be following up shortly on this issue with insights.

**Comment by cawrites** [comment]
@PrometheusRising1 can you take a look at this: https://stackoverflow.com/questions/50454237/azure-sql-creating-database-scoped-credential    "IntelliSense always reports the scoped credential as invalid syntax but the command works if issued immediately after creating the master key or opening the master key."

**Comment by cawrites** [comment]
Thank you for contacting Microsoft.
