### ISSUE TITLE
Invalid SQL statement in 'Delete ad-hoc queries'

### ISSUE THREAD

**Issue by miksh7** [MicrosoftDocs/sql-docs#6104]
SQL statement in 'Delete ad-hoc queries' missed string concatenation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b587ab-50b8-eada-aa86-ba0c838c57ee
* Version Independent ID: f1fd2d52-b66f-4fbc-c54a-c688c4fd0f21
* Content: [Monitoring Performance By Using the Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@miksh7 -- thank you for bringing that to our attention.

@WilliamDAssafMSFT -- William, please look into this issue.  You are welcome to send me the corrected code & I will make a PR for the update.

**Comment by WilliamDAssafMSFT** [comment]
@miksh7  Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. 

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @miksh7, we have a doc update in flight. Thanks again, your feedback here has helped improve our documentation.
