### ISSUE TITLE
Add a note to clarify that the order of the included column list does not matter

### ISSUE THREAD

**Issue by fvarga01** [MicrosoftDocs/sql-docs#6116]
Please add a note to clarify that the order of the include column list does not matter. This may be intuitive to folks who understand the concept of leaf pages and how include columns are stored. But, not as much with people who didn't have as much exposure to on-prem SQL Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 513e0ea1-70af-5a56-9b42-8d2e173d4176
* Version Independent ID: 0b04a8fa-17f1-1bee-a1f6-2064a11e05ee
* Content: [Create Indexes with Included Columns - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/create-indexes-with-included-columns?view=sql-server-ver15)
* Content Source: [docs/relational-databases/indexes/create-indexes-with-included-columns.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/create-indexes-with-included-columns.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@fvarga01 -- Fany, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by MikeRayMSFT** [comment]
Thank you @fvarga01 - I've staged an update. Reviewing. 

You're also welcome to submit pull requests through the public repository, at your convenience
