### ISSUE TITLE
After upgrading to 17.7.1.1 on Windows and Ubuntu, connection string to SQL database fails with error "Logon Timeout Expired" if we are using managed identity for the connection

### ISSUE THREAD

**Issue by openingbullet** [MicrosoftDocs/sql-docs#6118]
Hi, My name is Prashant Bahroos and I am a Support Escalation Engineer with Microsoft Azure Rapid Response Team.

I recently worked on an issue where the connection string to SQL database fails with error "Logon Timeout Expired"
According to the customer, this was working 2 weeks ago and started failing around 1st week of Feb 2021.
We collected data from customer environment, and compared it with my lab (working) environment.
We identified that the new driver (17.7.1.1) is **_hitting the wrong endpoint when requesting for a token for the managed identity_**.

Here are the details to reproduce the issue.
Install Python ODBC and set the following variables (you must have an Azure SQL server and a SQL database in your tenant, along with a managed identity configured as AD admin on the SQL server in order to reproduce this issue)

server='tcp:<**SQLServerName**>.database.windows.net'
username='< Object ID of the managed identity >'
database = '<SQL Database Name>' # enter database name

Connection String
cnxn = pyodbc.connect('Driver=ODBC Driver 17 for SQL Server;UID='+username+';Server='+server+';Database='+database+';Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=30;Authentication=ActiveDirectoryMSI;')

Working trace from my lab

177 13:39:57.4562500 10.0.4.7 169.254.169.254 HTTP HTTP:Request, GET **/metadata/identity/oauth2/token**, Query:api-version=2018-02-01&resource=https%3A%2F%2Fdatabase.windows.net%2F&object_id=<Object ID of the the Managed Identity> 181 13:39:57.8937520 10.0.4.7 168.63.129.16 HTTP HTTP:Request, GET /machine/plugins/, Query:comp=netanalyticsnodeagent&type=command

------------------------------------------------
Non-working from your environment

9271 12:01:21.9918940 10.238.194.10 169.254.169.254 HTTP HTTP:Request, GET **_/metadata/oauth2/token_**, Query:api-version=2018-02-01&resource=https%3A%2F%2Fdatabase.windows.net%2F&object_id=<Object ID of the the Managed Identity>
9272 12:01:21.9976330 169.254.169.254 10.238.194.10 HTTP HTTP:Response, HTTP/1.1, **_Status: Not found, URL: /metadata/oauth2/token_**
9317 12:01:22.4984960 10.238.194.10 169.254.169.254 HTTP HTTP:Request, GET **_/metadata/oauth2/token_**, Query:api-version=2018-02-01&resource=https%3A%2F%2Fdatabase.windows.net%2F&object_id=<Object ID of the the Managed Identity>
9318 12:01:22.5034640 169.254.169.254 10.238.194.10 HTTP HTTP:Response, HTTP/1.1, **_Status: Not found, URL: /metadata/oauth2/token_**

Please put a warning on the public documentation informing the customers about this issue.
We are working internally to get this issue fixed with the driver.

Thanks,

Prashant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36a1d7f-a410-b597-0eb7-98212934fb0e
* Version Independent ID: e706f2bd-e051-fcff-7c3d-2ef3d9f80e87
* Content: [Download ODBC Driver for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/download-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/download-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@openingbullet -- Prashant, thank you for your detailed explanation.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
@openingbullet We are aware of the issue and are working on a driver hotfix. I will add a note to the download page until the fix is released.

**Comment by openingbullet** [comment]
> @openingbullet We are aware of the issue and are working on a driver hotfix. I will add a note to the download page until the fix is released.

Thank you David. That would be really helpful for customers who are planning to upgrade, or if they are seeing the same issue after the upgrade to 17.7.1.1

**Comment by David-Engel** [comment]
The note has been added to the download page. Closing this issue.

#please-close
