### ISSUE TITLE
Documentation on DacDeployOptions.AllowIncompatiblePlatform is incorrect

### ISSUE THREAD

**Issue by abelbraaksma** [MicrosoftDocs/sql-docs#6127]
I couldn't find the md file for this in the source of the repo, so apologies if I'm in the wrong location. The public docs link is: https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.dacdeployoptions.allowincompatibleplatform?view=sql-dacfx-150

The text gives this, which is false:

> True to block deployment to incompatible platforms; otherwise, false. Default is false.

This should be something like (emphasis mine):

> True to **allow** deployment to incompatible platforms; otherwise, false. Default is false.

**Comment by WilliamAntonRohm** [comment]
@abelbraaksma -- Abel, thank you for your feedback.  I am looking into this article.

**Comment by abelbraaksma** [comment]
While you're at it, it may be useful to mention that it allows the deployment of a dacpac set for Azure to deploy to localdb, even if the local version is older. Quite a common scenario,considering the questions on several forums.

**Comment by WilliamAntonRohm** [comment]
@abelbraaksma -- Abel, thank you for your followup.

@shueybubbles -- David, please look into this issue.

**Comment by abelbraaksma** [comment]
@shueybubbles, see prev. comment, can you take a look at this? It is only one line that needs changing, but it is a rather critical line (see OP). Tx!

**Comment by dzsquared** [comment]
#reassign:dzsquared

**Comment by dzsquared** [comment]
#please-close
fixed in API docs

**Comment by abelbraaksma** [comment]
Thanks for this. Verified ✅.
