### ISSUE TITLE
Microsoft Docs - how to collapse or hide the left panel

### ISSUE THREAD

**Issue by JrMan68** [MicrosoftDocs/sql-docs#6128]
[Enter feedback here]
I'm using a small screen and would like the left panel (the contents tree) to collapse or hide. Is there a way to do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3db84b5-ab92-5b47-daf1-4141eb90c778
* Version Independent ID: df014d2f-71f8-bd2c-41f9-47b4ebdeff6e
* Content: [Connect and query a SQL Server instance using SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/quickstarts/ssms-connect-query-sql-server?view=sql-server-2016)
* Content Source: [docs/ssms/quickstarts/ssms-connect-query-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/quickstarts/ssms-connect-query-sql-server.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@JrMan68 -- Carlos, thank you for your question.  One approach is to narrow the window until the left panel disappears, and a small Table of Contents button will show at the top of the narrowed window.

You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).

**Comment by windperson** [comment]
There's a browser extension that adds a toggle button on top of each document when you browse:
https://www.drewsk.tech/docs-fullview/

**Comment by spottedmahn** [comment]
reference: https://github.com/MicrosoftDocs/feedback/issues/2237
