### ISSUE TITLE
Typo in adutil documentation

### ISSUE THREAD

**Issue by storm49152** [MicrosoftDocs/sql-docs#6130]
On this page [https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-ad-auth-adutil-tutorial?view=sql-server-ver15](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-ad-auth-adutil-tutorial?view=sql-server-ver15), the documentation says this is how to create an AD user using `adutil`:

```
adutil user create --name sqluser -distname CN=sqluser,CN=Users,DC=CONTOSO,DC=COM --password 'P@ssw0rd'
```

This will fail, because the parameter should be "--distname". Further below, this typo is repeated in:

```
You can specify the name of the account using the distinguished name (-distname) as shown above
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84e4ebac-6e2e-f188-e382-4e8d9940f8fb
* Version Independent ID: c256593c-499f-1cf9-9f6b-eba3516de73a
* Content: [Configure Active Directory authentication with SQL Server on Linux using adutil - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-ad-auth-adutil-tutorial?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-ad-auth-adutil-tutorial.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-ad-auth-adutil-tutorial.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by amvin87** [comment]
@storm49152 Thank you for pointing this out, let me fix the typo. I really appreciate your time on this .

**Comment by cawrites** [comment]
@storm49152 thank you for contacting Microsoft regarding this issue. We have updated this content and the correction will appear in the next content refresh.

**Comment by storm49152** [comment]
@cawrites Thanks for that. I can see that the Bash commandline is now correct, however, the second instance I mentioned is not corrected and still contains the single-hyphen `-distname`:

You can specify the name of the account using the distinguished name (`-distname`) as shown above, [...etc...]
