### ISSUE TITLE
pyodbc Error code 0x2746 (10054) (SQLDriverConnect) after upgrading to 17.7.1.1 on Ubuntu 18.04 

### ISSUE THREAD

**Issue by teemour** [MicrosoftDocs/sql-docs#6135]
Hello, my python application inside a docker container tried to establish connection with a MS SQL database using pyodbc, but failed with [08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746 (10054) (SQLDriverConnect). It worked just fine several weeks ago with version msodbcsql17=17.6.1.1-1 (i'm using these instructions: https://docs.microsoft.com/ru-ru/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15&viewFallbackFrom=sql-server-ver17#ubuntu ). This is my Dockerfile: 
```
FROM ubuntu:18.04

RUN apt-get update && apt-get upgrade -y && apt-get install -y apt-transport-https && apt-get install -y apt-utils && apt-get install -y gnupg2 && apt-get clean

RUN apt-get install -y curl python3.6-dev python3.6-distutils python3-pip

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN apt-get update\
 && apt-get upgrade -y\
 && ACCEPT_EULA=Y apt-get install msodbcsql17 -y\
 && ACCEPT_EULA=Y apt-get install mssql-tools -y\
 && apt-get install unixodbc-dev -y

RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> /home/.bash_profile
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> /home/.bashrc
RUN /bin/bash -c "source /home/.bashrc"

RUN pip3 install --no-cache-dir -r requirements.txt
```
My connection string is "Driver={ODBC Driver 17 for SQL Server};Server={server};Database={db};uid=uid;pwd=pwd"

I tried to tinker configs, for example ```RUN chmod +rwx /etc/ssl/openssl.cnf
RUN sed -i 's/TLSv1.2/TLSv1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/SECLEVEL=2/SECLEVEL=1/g' /etc/ssl/openssl.cnf```
however i managed to make it work only after locking versions ```RUN apt-get update\
 && apt-get upgrade -y\
 && ACCEPT_EULA=Y apt-get install msodbcsql17=17.6.1.1-1 -y\
 && ACCEPT_EULA=Y apt-get install mssql-tools=17.6.1.1-1 -y\
 && apt-get install unixodbc-dev=2.3.7 -y```

So, everything failed after these libraries updates, just letting everybody know.

**Comment by WilliamAntonRohm** [comment]
@teemour -- Timur, thank you for your detailed feedback.  Please add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @David-Engel for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
