### ISSUE TITLE
Missing Information about Limits throught Standard Edition and Buffer pool extension

### ISSUE THREAD

**Issue by fischerRo** [MicrosoftDocs/sql-docs#6136]
Hallo ,
I see on this links that there is a limit  for an ratio of 4x BufferPool Memory to the Buffer pool extension on SQL Server Standard Edition:
https://social.technet.microsoft.com/wiki/contents/articles/51454.sql-server-buffer-pool.aspx
https://logicalread.com/buffer-pool-extensions-sql-server-2014-pd01/#.Wu8UyYiFOUk
---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 453dc1e2-0c9c-fe95-c6fc-90be886432ad
* Version Independent ID: cd472bc0-26b9-a4a6-4089-31b79be787cb
* Content: [Editions and supported features - SQL Server 2017](https://docs.microsoft.com/en-us/SQL/SQL-server/editions-and-components-of-SQL-server-2017?view=sql-server-ver15)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-2017.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-2017.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@fischerRo -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
@fischerRo I'm staging an update to resolve this. Thank you.

**Comment by fischerRo** [comment]
@MikeRayMSFT is there a link to see the change? Thank you.
