### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by CarlosAugustoDeSouzaJunior** [MicrosoftDocs/sql-docs#6138]
[Enter feedback here]

Because of that, the **online** approach is likely to consume more resources on the server side than the **online** approach.

..it should be...

Because of that, the **online** approach is likely to consume more resources on the server side than the **offline** approach.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21b15790-8233-1099-2d0c-c0abd4f5926d
* Version Independent ID: 9a72e924-c89a-c236-33f2-2d72136e4f94
* Content: [Configure column encryption using Always Encrypted with PowerShell - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/configure-column-encryption-using-powershell?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/configure-column-encryption-using-powershell.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/configure-column-encryption-using-powershell.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@CarlosAugustoDeSouzaJunior -- Carlos, thank you for catching this.  I am updating the article.
