### ISSUE TITLE
Version of RHEL listed are no longer supported by Red Hat

### ISSUE THREAD

**Issue by limershein** [MicrosoftDocs/sql-docs#6139]
The versions of RHEL (7.3 and 7.4) on this page are no longer supported by Red Hat.  7.3  support ended November 30, 2018 while 7.4 ended August 31, 2019.  As long as the Azure Data Studio complies with the RHEL 7 Application Compatibility Guide, an application built on a version of RHEL 7 should continue to run on ANY version of RHEL 7 and Red Hat commits to resolving any issues with that compatibility.   See: https://access.redhat.com/articles/rhel-abi-compatibility for details.  

Note that while this application appears to run without issues on RHEL 8.3, you generally want to support each major version with a seperate version.  For details of the RHEL 8 Application Compatibility Guide see: https://access.redhat.com/articles/rhel8-abi-compatibility

Thanks,

Louis Imershein
Principal Product Manager
Red Hat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/download-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download-azure-data-studio.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
@limershein -- Louis, thank you for your considered feedback.

@yualan -- Alan, please look into this issue.

**Comment by markingmyname** [comment]
@limershein 

Thank you for this feedback.

Due to your suggestion, we updated the downlaod page with updated RHEL versions and a note that discuss compatibility.

Change will go live early next week.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit Azure Data Studio repo(https://github.com/microsoft/azuredatastudio)
