### ISSUE TITLE
Download link points to the wrong locations

### ISSUE THREAD

**Issue by paddotk** [MicrosoftDocs/sql-docs#6142]
Hi,
I'm trying to download ADO.NET, but the link for this points to the download page for the .NET framework. Now I can't download ADO. Please fix this!

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 38b08d64-d099-9d45-766b-37957f63d5a6
* Version Independent ID: 3c9c63c5-9c7e-29a7-0c65-b865bc6733d5
* Content: [Connection libraries for Microsoft SQL Database - SQL Server](https://docs.microsoft.com/nl-nl/sql/connect/sql-connection-libraries?view=sql-server-ver15#anchor-20-drivers-relational-access)
* Content Source: [docs/connect/sql-connection-libraries.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/sql-connection-libraries.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@paddotk -- thank you for your feedback.

@David-Engel -- please look into this issue.

**Comment by David-Engel** [comment]
@paddotk ADO.NET is part of .NET, .NET Core, and .NET Framework. The link takes you to the single download page for all of those. What exactly are you looking for?

**Comment by paddotk** [comment]
@David-Engel Oh I see... That wasn't clear from that page nor the documentation where I got there from. This page lists a few download links under the column 'Download the SQL driver' so it looks as though these are separate downloads (drivers). In this case, I'd suggest to make the page clearer.

Thanks for clearing this up :)

**Comment by David-Engel** [comment]
@paddotk I can see that it's not perfectly clear. I'll look into updating the page.

Thanks,
David

#please-close
