### ISSUE TITLE
Remove adding /opt/mssql-tools/bin to PATH in .bash_profile for Ubuntu (maybe other distros too)

### ISSUE THREAD

**Issue by jgilles** [MicrosoftDocs/sql-docs#6143]
The current documentation has the following commands for installing on Ubuntu

```
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
```

This causes problems on Ubuntu because by default, a user does not have ~/.bash_profile, but does have ~/.profile and ~/.bashrc.  Also, by default, ~/.profile loads ~/.bashrc.

Therefore it is only necessary to add to PATH in ~/.bashrc.

Adding to ~/.bash_profile actually *causes* problems because when it exists, bash stops loading ~/.profile and loads ~/.bash_profile instead.  This causes ~/.bashrc to no longer be loaded automatically and also skips running the other commands in the users' ~/.profile, such as adding $HOME/bin to PATH if it exists.

Please remove the command that creates/modifies ~/.bash_profile -- adding to ~/.bashrc alone is sufficient.

This could very well apply to other distros too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu17)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@jgilles -- Jesse, thank you for your considered feedback.  I am looking into this article.

**Comment by Evilantireversed** [comment]
> The current documentation has the following commands for installing on Ubuntu
> 
> ```
> echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
> echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
> ```
> 
> This causes problems on Ubuntu because by default, a user does not have ~/.bash_profile, but does have ~/.profile and ~/.bashrc. Also, by default, ~/.profile loads ~/.bashrc.
> 
> Therefore it is only necessary to add to PATH in ~/.bashrc.
> 
> Adding to ~/.bash_profile actually _causes_ problems because when it exists, bash stops loading ~/.profile and loads ~/.bash_profile instead. This causes ~/.bashrc to no longer be loaded automatically and also skips running the other commands in the users' ~/.profile, such as adding $HOME/bin to PATH if it exists.
> 
> Please remove the command that creates/modifies ~/.bash_profile -- adding to ~/.bashrc alone is sufficient.
> 
> This could very well apply to other distros too.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
> * Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
> * Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu17)
> * Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
> * Product: **sql**
> * Technology: **connectivity**
> * GitHub Login: @David-Engel
> * Microsoft Alias: **v-daenge**

Operations assistant
