### ISSUE TITLE
Needs Version Low Part, Version High Part descriptions added

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#6146]
These appear to have been added in 2019 - can you please run sp_configure on a latest-version instance and check what these are and document here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32e9c4f8-ec32-ff5f-93a4-8f07b664db5f
* Version Independent ID: 2111d777-a999-dc99-a3e5-cc7e7877c9b8
* Content: [Server Configuration Options (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/server-configuration-options-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/server-configuration-options-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/server-configuration-options-sql-server.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by TimShererWithAquent** [comment]
@PrometheusRising1 Thanks for your feedback. We'll look into this article.

**Comment by markingmyname** [comment]
Hi, @PrometheusRising1

apologizes for the delayed response, but I verified that the list on this article and running "sp_configure" on SQL Server 2019 match

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/maghan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/maghan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



name | minimum | maximum | config_value | run_value
-- | -- | -- | -- | --
allow polybase export | 0 | 1 | 0 | 0
allow updates | 0 | 1 | 0 | 0
backup checksum default | 0 | 1 | 0 | 0
backup compression default | 0 | 1 | 0 | 0
clr enabled | 0 | 1 | 0 | 0
column encryption enclave type | 0 | 2 | 0 | 0
contained database authentication | 0 | 1 | 0 | 0
cross db ownership chaining | 0 | 1 | 0 | 0
default language | 0 | 9999 | 0 | 0
external scripts enabled | 0 | 1 | 0 | 0
filestream access level | 0 | 2 | 0 | 0
hadoop connectivity | 0 | 7 | 0 | 0
max text repl size (B) | -1 | 2147483647 | 65536 | 65536
nested triggers | 0 | 1 | 1 | 1
polybase enabled | 0 | 1 | 0 | 0
polybase network encryption | 0 | 1 | 1 | 1
remote access | 0 | 1 | 1 | 1
remote admin connections | 0 | 1 | 0 | 0
remote data archive | 0 | 1 | 0 | 0
remote login timeout (s) | 0 | 2147483647 | 10 | 10
remote proc trans | 0 | 1 | 0 | 0
remote query timeout (s) | 0 | 2147483647 | 600 | 600
server trigger recursion | 0 | 1 | 1 | 1
show advanced options | 0 | 1 | 0 | 0
user options | 0 | 32767 | 0 | 0
  |   |   |   |  



</body>

</html>

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
