### ISSUE TITLE
SQL Query is cWrong output using "for json path,root('CustomerMaxId')"

### ISSUE THREAD

**Issue by ph3ll3r** [MicrosoftDocs/sql-docs#6147]
SQL Query is correct.  Using "for json path,root('CustomerMaxId')" on the query produces an incorrect result.
	 **select OuterQuery.CustomerId

			, OuterQuery.OrderId
			, OuterQuery.OrderDate
			, OuterQuery.EmployeeId
	from Sales.[Order] as OuterQuery
	where OuterQuery.OrderId =
	(
		select max(InnerQuery.OrderId)
		from Sales.[Order] as InnerQuery
		where InnerQuery.CustomerId = OuterQuery.CustomerId
	)
	order by OuterQuery.CustomerId
	--for json path,root('CustomerMaxId');**
--
-- SQL
CustomerId	OrderId	OrderDate	EmployeeId
1	11011	2016-04-09	3
2	10926	2016-03-04	4
3	10856	2016-01-28	3
4	11016	2016-04-10	9
5	10924	2016-03-04	3
6	11058	2016-04-29	9
7	10826	2016-01-12	6
8	10970	2016-03-24	9
9	11076	2016-05-06	4
10	11048	2016-04-24	7
11	11023	2016-04-14	1
12	11054	2016-04-28	8
13	10259	2014-07-18	4
14	11041	2016-04-22	3
15	11042	2016-04-22	2
16	10848	2016-01-23	7
17	11067	2016-05-04	1
18	10890	2016-02-16	7
19	11056	2016-04-28	8
20	11072	2016-05-05	4
21	10725	2015-10-31	4
23	10789	2015-12-22	1
24	11050	2016-04-27	8
25	11012	2016-04-09	1
26	10971	2016-03-24	2
27	11060	2016-04-30	2
28	10963	2016-03-19	9
29	10928	2016-03-05	1
30	11037	2016-04-21	7
31	11049	2016-04-24	3
32	11061	2016-04-30	4
33	10785	2015-12-18	1
34	11052	2016-04-27	3
35	11055	2016-04-28	7
36	10660	2015-09-08	8
37	11063	2016-04-30	3
38	10933	2016-03-06	6
39	11028	2016-04-16	2
40	10973	2016-03-24	6
41	11051	2016-04-27	7
42	10810	2016-01-01	2
43	10545	2015-05-22	8
44	11070	2016-05-05	2
45	10884	2016-02-12	4
46	11071	2016-05-05	1
47	11039	2016-04-21	1
48	11018	2016-04-13	4
49	10950	2016-03-16	1
50	11004	2016-04-07	3
51	10724	2015-10-30	8
52	10945	2016-03-12	4
53	11057	2016-04-29	3
54	10986	2016-03-30	8
55	11034	2016-04-20	8
56	11020	2016-04-14	2
58	11073	2016-05-05	2
59	11053	2016-04-27	2
60	11007	2016-04-08	8
61	10989	2016-03-31	2
62	11068	2016-05-04	8
63	11021	2016-04-14	3
64	11019	2016-04-13	6
65	11077	2016-05-06	1
66	11062	2016-04-30	4
67	11059	2016-04-29	2
68	11075	2016-05-06	8
69	11013	2016-04-09	2
70	11015	2016-04-10	2
71	11064	2016-05-01	1
72	10869	2016-02-04	5
73	11074	2016-05-06	7
74	11043	2016-04-22	5
75	10974	2016-03-25	3
76	11038	2016-04-21	1
77	10992	2016-04-01	1
78	11003	2016-04-06	3
79	10967	2016-03-23	2
80	11069	2016-05-04	1
81	10839	2016-01-19	3
82	10822	2016-01-08	6
83	10994	2016-04-02	2
84	10850	2016-01-23	1
85	10739	2015-11-12	3
86	11046	2016-04-23	8
87	11025	2016-04-15	6
88	10935	2016-03-09	4
89	11066	2016-05-01	7
90	11005	2016-04-07	2
91	11044	2016-04-23	4
--
--
	select OuterQuery.CustomerId
			, OuterQuery.OrderId
			, OuterQuery.OrderDate
			, OuterQuery.EmployeeId
	from Sales.[Order] as OuterQuery
	where OuterQuery.OrderId =
	(
		select max(InnerQuery.OrderId)
		from Sales.[Order] as InnerQuery
		where InnerQuery.CustomerId = OuterQuery.CustomerId
	)
	order by OuterQuery.CustomerId
	for json path,root('CustomerMaxId');
--
--JSON  Truncate data 
{
    "CustomerMaxId": [{
            "CustomerId": 1,
            "OrderId": 11011,
            "OrderDate": "2016-04-09",
            "EmployeeId": 3
        }, {
            "CustomerId": 2,
            "OrderId": 10926,
            "OrderDate": "2016-03-04",
            "EmployeeId": 4
        }, {
            "CustomerId": 3,
            "OrderId": 10856,
            "OrderDate": "2016-01-28",
            "EmployeeId": 3
        }, {
            "CustomerId": 4,
            "OrderId": 11016,
            "OrderDate": "2016-04-10",
            "EmployeeId": 9
        }, {
            "CustomerId": 5,
            "OrderId": 10924,
            "OrderDate": "2016-03-04",
            "EmployeeId": 3
        }, {
            "CustomerId": 6,
            "OrderId": 11058,
            "OrderDate": "2016-04-29",
            "EmployeeId": 9
        }, {
            "CustomerId": 7,
            "OrderId": 10826,
            "OrderDate": "2016-01-12",
            "EmployeeId": 6
        }, {
            "CustomerId": 8,
            "OrderId": 10970,
            "OrderDate": "2016-03-24",
            "EmployeeId": 9
        }, {
            "CustomerId": 9,
            "OrderId": 11076,
            "OrderDate": "2016-05-06",
            "EmployeeId": 4
        }, {
            "CustomerId": 10,
            "OrderId": 11048,
            "OrderDate": "2016-04-24",
            "EmployeeId": 7
        }, {
            "CustomerId": 11,
            "OrderId": 11023,
            "OrderDate": "2016-04-14",
            "EmployeeId": 1
        }, {
            "CustomerId": 12,
            "OrderId": 11054,
            "OrderDate": "2016-04-28",
            "EmployeeId": 8
        }, {
            "CustomerId": 13,
            "OrderId": 10259,
            "OrderDate": "2014-07-18",
            "EmployeeId": 4
        }, {
            "CustomerId": 14,
            "OrderId": 11041,
            "OrderDate": "2016-04-22",
            "EmployeeId": 3
        }, {
            "CustomerId": 15,
            "OrderId": 11042,
            "OrderDate": "2016-04-22",
            "EmployeeId": 2
        }, {
            "CustomerId": 16,
            "OrderId": 10848,
            "OrderDate": "2016-01-23",
            "EmployeeId": 7
        }, {
            "CustomerId": 17,
            "OrderId": 11067,
            "OrderDate": "2016-05-04",
            "EmployeeId": 1
        }, {
            "CustomerId": 18,
            "OrderId": 10890,
            "OrderDate": "2016-02-16",
            "EmployeeId": 7
        }, {
            "CustomerId": 19,
            "OrderId": 11056,
            "OrderDate": "2016-04-28",
            "EmployeeId": 8
        }, {
            "CustomerId": 20,
            "OrderId": 11072,
            "OrderDate": "2016-05-05",
            "EmployeeId": 4
        }, {
            "CustomerId": 21,
            "OrderId": 10725,
            "OrderDate": "2015-10-31",
            "EmployeeId": 4
        }, {
            "CustomerId": 23,
            "OrderId": 10789,
            "OrderDate": "2015-12-22",
            "EmployeeId": 1
        }, {
            "CustomerId": 24,
            "OrderId": 11050,
            "OrderDate": "2016-04-27",
            "EmployeeId": 8
        }, {
            "CustomerId": 25,
            "OrderId": 11012,
            "OrderDate": "2016-04-09",
            "EmployeeId": 1
        }, {
            "CustomerId": 26,
            "OrderId": 10971,
            "OrderDate": "2016-03-24",
            "EmployeeId": 2
        }, {
            "CustomerId": 27,
            "OrderId": 11060,
            "OrderDate": "2016-04-30",
            "EmployeeId": 2
        }, {
            "CustomerId": 28,
            "OrderId": 10963,
            "OrderDate": "2016-03-19",
            "EmployeeId": 9
        }, {
            "CustomerId": 29,
            "OrderId"

**Comment by TimShererWithAquent** [comment]
@ph3ll3r Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing, or provide more context around the general task.

**Comment by ph3ll3r** [comment]
This is a kluge to get it to work found it  on stackoverflow:  I am assuming that there is a better way to produce JSON output other than storing it in XML?
 
![image](https://user-images.githubusercontent.com/3041978/109893744-369b9980-7c5a-11eb-8cec-e5e322496c51.png)


		declare @JsonOutput XML;
		set @JsonOutput = (
							select OuterQuery.CustomerId
								 , OuterQuery.OrderId
								 , OuterQuery.OrderDate
								 , OuterQuery.EmployeeId
							from Sales.[Order] as OuterQuery
							where OuterQuery.OrderId =
							(
								select max(InnerQuery.OrderId)
								from Sales.[Order] as InnerQuery
								where InnerQuery.CustomerId = OuterQuery.CustomerId
							)
							order by OuterQuery.CustomerId
							for json path, root('CustomerMaxId')
		)
		select @JsonOutput as JsonOutput

**Comment by WilliamAntonRohm** [comment]
@ph3ll3r -- thank you for your reply.  Are you following a particular docs.microsoft.com article?  Meanwhile, please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
