### ISSUE TITLE
Local hostname entries required for PowerBI scale-out deployment?

### ISSUE THREAD

**Issue by noakesey** [MicrosoftDocs/sql-docs#6149]
We struggled to get a scale-out deployment of "Power BI server (October 2020 / January 2021)" working without adding an entry to the hosts file on each server to redirect "virtual host name" to local ip, e.g.

127.0.0.1 loadbalanced.pbi.server

This article doesn't mention it, so if not required, it might be good to highlight which part of the article provides the alternative to this approach:
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/reporting-services/report-server/configure-a-report-server-on-a-network-load-balancing-cluster.md

I found the solution to my problem here - see message 3 (05-29-2018 02:25 PM):
https://community.powerbi.com/t5/Report-Server/Scale-out-deployment-on-March-2018-PBIRS/m-p/396981

Without this local host entry, we were unable to import .pbix files into report manager.

(we configured Hostname and UrlRoot as documented.)

**Comment by WilliamAntonRohm** [comment]
@noakesey -- Paul, thank you for your well-researched feedback.

@maggiesMSFT -- Maggie, please look into this issue.

**Comment by maggiesMSFT** [comment]
Hi, @noakesey -- sorry for the delay! Can you report if this is still an issue? If so, I'll check with the product team. 
Thanks!
