### ISSUE TITLE
Incorrect Ubuntu install commands

### ISSUE THREAD

**Issue by southpaw5271** [MicrosoftDocs/sql-docs#6151]
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu17

For this section, in the code block where you are using apt to install packages, if you change `apt-get install` to `apt-get install -y`, the commands can be run sequentially without user interaction. See the below code block:
`
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17
optional: for bcp and sqlcmd
sudo ACCEPT_EULA=Y apt-get install mssql-tools
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashrc
optional: for unixODBC development headers
sudo apt-get install -y unixodbc-dev
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@southpaw5271 -- Kyle, thank you for your feedback and proposed solution.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
I updated the page to include -y in the install commands. It should be visible after tomorrow morning's doc publish.

Thanks,
David

#please-close
