### ISSUE TITLE
SQL Server: REPLACE argument description is incorrect

### ISSUE THREAD

**Issue by LowlyDBA** [MicrosoftDocs/sql-docs#6153]
On SQL Server's [REPLACE ](https://docs.microsoft.com/en-us/sql/t-sql/functions/replace-transact-sql?view=sql-server-ver15) function page,  it states (emphasis mine):

> *string_pattern*
Is the substring to be found. string_pattern can be of a character or binary data type. **string_pattern cannot be an empty string ('')**, and must not exceed the maximum number of bytes that fits on a page.

However on Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 using an empty string pattern `''` works fine and simply returns the *string_expression* unchanged. The wording should be changed to make it clear than at empty string can be used, although the output will be the same as the input.

**Comment by WilliamAntonRohm** [comment]
@LowlyDBA -- John, thank you for your considered feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@julieMSFT -- Julie, please review this update in [private PR 18848](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18848).
