### ISSUE TITLE
Typo in the select statement in 6-generate Generate activity and backup log using file-snapshot backup

### ISSUE THREAD

**Issue by msdpalam** [MicrosoftDocs/sql-docs#6155]
We have a typo in the doc, under
"6-generate Generate activity and backup log using file-snapshot backup"
_SELECT COUNT (*) from AdventureWorks2014.Production.Location;_  

I think we want to have:
SELECT COUNT (*) from AdventureWorks2016.Production.Location;  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e8e46c-01f3-a76a-761f-5206e6d878e9
* Version Independent ID: 3945290e-ef38-b04c-9ee6-d3889b4b94e4
* Content: [Tutorial: Use Azure Blob storage service with SQL Server 2016 - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@msdpalam -- Meer, thank you for your feedback.  I am looking into this article.

**Comment by cawrites** [comment]
@msdpalam thank you for contacting Microsoft regarding this issue. We have updated the content and it will appear in the next refresh.
