### ISSUE TITLE
Restore Master database - using corrupted Master database.

### ISSUE THREAD

**Issue by Alocyte** [MicrosoftDocs/sql-docs#6157]
Recently I experienced a need to restore the master database, as explained.

The error log showed this when SQL Service tried to start:
The log scan number (2627:336:1) passed to log scan in database 'master' is not valid. 
This error may indicate data corruption or that the log file (.ldf) does not match the data file (.mdf). 
If this error occurred during replication, re-create the publication. 
Otherwise, restore from backup if the problem results in a failure during startup.

However, the master database needed restoring due to this corruption, 
and the SQL Service would not start - even in Single User mode.

The solution required replacing the master.mdf / master.ldf using [C:\Program Files\Microsoft SQL Server\130\LocalDB\Binn\Templates] master datatbase files.
Running the SQL Server in CMD prompt, with startup-parameters for the MSDB, TempDB and Model DB, failed - the Master database referenced an obscure folder: 
E:\sql10_main_t.obj.x86fre\sql\mkmastr\databases\objfre\i386
To overcome this dependency I mapped a local folder I shared, as E: and created the folder tree.
I copied the MSDB and Model databases there also.
Only once I had done that, did the SQL Service start, and run scripts on the master database. 
That enabled me to execute the RESTORE MASTER FROM DISK = '' WITH RECOVERY command.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117162ac-5412-f945-e534-d7d6fe9ae861
* Version Independent ID: e0aba6b9-5ec5-3ddd-c37c-a3f3cc2fdc9f
* Content: [Restore the master Database (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/restore-the-master-database-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/relational-databases/backup-restore/restore-the-master-database-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/restore-the-master-database-transact-sql.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@Alocyte -- thank you for your detailed feedback.

@cawrites -- please look into this issue.

**Comment by cawrites** [comment]
@Alocyte I reviewed your feedback. What is the specific question as it relates to the content in the article?

**Comment by cawrites** [comment]
It sounds like your primary issue is starting SQL Server in single-user mode. This can be challenging because other services connect to SQL Server as well.  I recommend starting with https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/start-sql-server-in-single-user-mode?view=sql-server-ver15 to ensure you are in Single User Mode.

**Comment by Alocyte** [comment]
> @Alocyte I reviewed your feedback. What is the specific question as it relates to the content in the article?
Hi @cawrites
 
Including the steps to rebuild a master from the Template database would likely be appropriate in the article describing the restore, given that a corrupt master could render the SQL Service inoperable.

The article assumes that the SQL Service is in a runnable state, able to restore the master database.

My experience was there was a need to recover from a corrupted master database prior to having a SQL Service with which to implement the restore of the corrupted master database.

There is no description on the process required to do this critical step.
Given the arbitrary folder dependency ( the parameters for system database (msdb, model, master) location being ignored) I thought it appropriate to explain an easy workaround (my description of my process) using a local share mapped as a drive (although if the server has an E: merely creating the folder tree would suffice of course).

**Comment by Alocyte** [comment]
> @Alocyte thank you for the clarification of your request and the simpler solution. I agree when this happens situations are not ideal. Do you think this sentence: To start SQL Server, we need a master database, which is corrupted." Actually means "To start SQL Server, we need a master database, which isn't corrupted." Have you tried this solution in your environment? The simpler one?

@cawrites Definately we need a master database, which isn't corrupted. :)
I have not tried the simpler solution, I had resolved it previously ( production server so not doing it again! )
The trouble with Master corruption is that it IS so infrequent, critical, and while the office is breathing down your neck is not the time to be Googling.

**Comment by cawrites** [comment]
@Alocyte I am glad to hear that you successfully got your production database running again. In regards to your comment from the blog there is documentation for it here https://docs.microsoft.com/en-us/sql/relational-databases/databases/rebuild-system-databases?view=sql-server-ver15#Resource

**Comment by Alocyte** [comment]
@cawrites Well, indeed. 21 days after initiating the request, you have Googled the solution. However, my point is that this should be included in the Master database recovery solution. What are your scenarios which dictate that Master needs restoring? Would the service be running in these scenarios?

Imagine your car's engine breaks. How do you drive it to the mechanic?

The SQL Service broke when Master was corrupted. I had to uncorrupt the Master database to get the SQL Service started, to use it to restore my backup.
The article is incomplete, it assumes the SQL Service (car's engine) is fully functional, and able to process SQL commands (drive).
It is not, is my point.
A temporary Master database (from the template directory) was needed (a tow, in the car metaphor) to start the restore (mechanic).

**Comment by cawrites** [comment]
@Alocyte I understand your concern. Upon review, it appears that our conversation was initiated after your initial request. I needed to clarify your original ask. Once I clarified your request. I reviewed the link you sent and spoke with other individuals in this space. Keep in mind that this is documentation and not support. If you had/have an urgent need that is production-related I highly recommend you create a support ticket. Documentation is not the place to handle such requests. You will be able to prioritize your responses based on the level of support you have for your organization. Fortunately, I did not have to "google" the response, because the documented process you found externally was actually on the same page you reported the issue.

**Comment by Alocyte** [comment]
no, i don't believe you do understand my concern, @cawrites. 
However, I have stated it sufficiently to accept you can't.
Be well.

**Comment by cawrites** [comment]
@Alocyte I understand that you are stating your scenario does not fit the scenario defined in the content. In the documentation,n it is not possible to cover every scenario, that is why the additional documentation is listed on the same page to provide the reader with more than one option. It appears that you are expanding your question/request to consider adding the content link (which is the same as your external link) in a more prominent place within the content to provide another option.

**Comment by cawrites** [comment]
I see that you have closed the requ

**Comment by Alocyte** [comment]
I cannot think of any scenario requiring restoring of Master that would use a SQL service that is corrupted by the Master needing to be restored, hence my recommendation to describe how to replace a corrupted Master so as to have a SQL instance CAPABLE of restoring a Master database.

**Comment by cawrites** [comment]
@Alocyte   Let's proceed this way. We will leave this closed. But I will provide an update to this that you can review. I agree that having that plainly noted in the article would be helpful. You originally referenced a general page for restoring master. Give me an opportunity to explore the best placement.

**Comment by Alocyte** [comment]
@;---- Be well.

**Comment by cawrites** [comment]
@Alocyte I just wanted to advise you that this content https://docs.microsoft.com/en-us/sql/relational-databases/databases/rebuild-system-databases?view=sql-server-ver15&viewFallbackFrom=sql-server-ver15%5C is appearing on the web page. I recall it being a concern and I advised you I would let you know; pulling in additional content is part of the content desigin

**Comment by Alocyte** [comment]
Cawrites :) I trust you are well. 
Referring the original article, [Restore Master Database](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/restore-the-master-database-transact-sql?view=sql-server-ver15), the link to rebuilding the system databases is on the web page, at the bottom, in the Recommeded Links section. Past the See Also section... 
By this time the user attempting to restore a corrupt master database will have abandoned this page, as the service is incapable of restoring the database. 

I won't be participating in this conversation further.
