### ISSUE TITLE
M1 mac sql server driver not working

### ISSUE THREAD

**Issue by marauderdave** [MicrosoftDocs/sql-docs#6164]
Hello MSFT,

After installing the driver I tried running a python query with it, but then I realized the driver file didn't actually install...

Terminal Output:

Mac-mini ~ % cat /usr/local/lib/libmsodbcsql.17.dylib
cat: /usr/local/lib/libmsodbcsql.17.dylib: No such file or directory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c0de6fb-19ae-ff6f-8e73-ce66fa94bd64
* Version Independent ID: 34edd099-f4fe-4ac3-cdd4-abc87b35270b
* Content: [Install the Microsoft ODBC driver for SQL Server (macOS) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by DanielCollins96** [comment]
damn
