### ISSUE TITLE
Missing prerequisite to install sqlsrv driver on Ubuntu 20.20

### ISSUE THREAD

**Issue by dregad** [MicrosoftDocs/sql-docs#6170]
Following the indications in the documentation, the driver installation failed

```
$ pecl install sqlsrv
[snip]
running: make
/bin/bash /tmp/pear/temp/pear-build-rootyjQo2J/sqlsrv-5.9.0/libtool --mode=compile g++ -I. -I/tmp/pear/temp/sqlsrv -I/tmp/pear/temp/pear-build-rootyjQo2J/sqlsrv-5.9.0/include -I/tmp/pear/temp/pear-build-rootyjQo2J/sqlsrv-5.9.0/main -I/tmp/pear/temp/sqlsrv -I/usr/include/php/20200930 -I/usr/include/php/20200930/main -I/usr/include/php/20200930/TSRM -I/usr/include/php/20200930/Zend -I/usr/include/php/20200930/ext -I/usr/include/php/20200930/ext/date/lib -I/tmp/pear/temp/sqlsrv/shared/  -DHAVE_CONFIG_H  -std=c++11 -D_FORTIFY_SOURCE=2 -O2 -fstack-protector   -std=c++11 -c /tmp/pear/temp/sqlsrv/conn.cpp -o conn.lo
libtool: compile:  g++ -I. -I/tmp/pear/temp/sqlsrv -I/tmp/pear/temp/pear-build-rootyjQo2J/sqlsrv-5.9.0/include -I/tmp/pear/temp/pear-build-rootyjQo2J/sqlsrv-5.9.0/main -I/tmp/pear/temp/sqlsrv -I/usr/include/php/20200930 -I/usr/include/php/20200930/main -I/usr/include/php/20200930/TSRM -I/usr/include/php/20200930/Zend -I/usr/include/php/20200930/ext -I/usr/include/php/20200930/ext/date/lib -I/tmp/pear/temp/sqlsrv/shared/ -DHAVE_CONFIG_H -std=c++11 -D_FORTIFY_SOURCE=2 -O2 -fstack-protector -std=c++11 -c /tmp/pear/temp/sqlsrv/conn.cpp  -fPIC -DPIC -o .libs/conn.o
In file included from /tmp/pear/temp/sqlsrv/shared/typedefs_for_linux.h:23,
                 from /tmp/pear/temp/sqlsrv/shared/xplat_winnls.h:24,
                 from /tmp/pear/temp/sqlsrv/shared/FormattedPrint.h:24,
                 from /tmp/pear/temp/sqlsrv/shared/core_sqlsrv.h:41,
                 from /tmp/pear/temp/sqlsrv/php_sqlsrv_int.h:25,
                 from /tmp/pear/temp/sqlsrv/conn.cpp:24:
/tmp/pear/temp/sqlsrv/shared/xplat.h:30:10: fatal error: sql.h: No such file or directory
   30 | #include <sql.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:209: conn.lo] Error 1
ERROR: `make' failed
```

Installing the `unixodbc-dev` package fixed the problem, you might want to mention that in the documentation.
```
sudo apt install unixodbc-dev
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f591be-6564-c959-7a92-6489bdd4f60b
* Version Independent ID: eec72536-eda0-1bc8-a41a-36ed4b9a8883
* Content: [Linux and macOS Installation for the Drivers for PHP - SQL Server](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15#installing-the-drivers-on-ubuntu-1604-1804-and-2004)
* Content Source: [docs/connect/php/installation-tutorial-linux-mac.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/installation-tutorial-linux-mac.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@dregad -- Damien, thank you for your feedback and proposed solution.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
I added a note to include the optional unixodbc-dev package in the prerequisites step of the installation instructions.

Regards,
David

#please-close

**Comment by TechFanDan** [comment]
I was following this page which was missing the reference to install the missing package:
https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@TechFanDan -- Dan, thank you for your followup.  Do you mean that page needs another update?

cc @David-Engel for awareness

**Comment by TechFanDan** [comment]
@WilliamAntonRohm @David-Engel Disregard my last comment. I didn't find the explicit mention to install unixodbc-dev in the various code snippets. However, after having double checked, I did see it in the paragraph of Step 2. Sorry.

**Comment by WilliamAntonRohm** [comment]
@TechFanDan -- Dan, no problem -- glad you found an answer!
