### ISSUE TITLE
Phasing at hierarchyid page

### ISSUE THREAD

**Issue by mrsegen** [MicrosoftDocs/sql-docs#6173]
Regarding the second point under this section: https://docs.microsoft.com/en-us/sql/relational-databases/hierarchical-data-sql-server

The sentence
`A breadth-first stores the rows each level of the hierarchy together.`
... seems like it should be:
`A breadth-first index stores the rows at each level of the hierarchy together.`

**Comment by WilliamAntonRohm** [comment]
@mrsegen -- Leif, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
