### ISSUE TITLE
INSERTED/DELETED tables in the Trigger explanation

### ISSUE THREAD

**Issue by SNiedinger** [MicrosoftDocs/sql-docs#6175]
The text to describe the INSERTED and DELETED tables used in the trigger is extremely ambiguous and vague. Please simplify the language used. It is difficult to understand what has been written. A simple INSERTED are the deltas and DELETED the original values description would be more useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de204ead-2a80-46ec-6adc-3d8b13977602
* Version Independent ID: eb4f715f-eba6-5d39-b2ba-5baae1b58c71
* Content: [Use the inserted and deleted Tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/triggers/use-the-inserted-and-deleted-tables?view=sql-server-ver15)
* Content Source: [docs/relational-databases/triggers/use-the-inserted-and-deleted-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/triggers/use-the-inserted-and-deleted-tables.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@SNiedinger -- thank you for your feedback.

@rothja -- please look into this issue.

**Comment by rothja** [comment]
@SNiedinger Thanks for the suggestion to improve this article. I will take a look at the description and your suggestion and see if we can improve it.

**Comment by rothja** [comment]
@SNiedinger Apologies for the delay. I did some research on this today, and I see what you mean. We don't really provide a clear explanation of the inserted/deleted tables when it comes to updates (that there will be rows in both tables for the original and changed values). And we use "affected" in a way that is not clear. How is it affected, the reader asks? I want to spend a little more time figuring out the best way to change the article to make it more clear. But thank you, again, for the suggestion. I'll run by my final edits with you when they are complete to see if you think it is an improvement.

**Comment by rothja** [comment]
@SNiedinger Hello! I know it has been a while, but I have rewritten the description to try to make this more clear. I hope this helps! Here is a screenshot of the changes that will publish soon:

![image](https://user-images.githubusercontent.com/1580454/145868832-574444cc-2bff-40a3-87ad-ed7d29c8b826.png)

**Comment by rothja** [comment]
BTW, the number is off there and that will get fixed when I publish. Thanks!
