### ISSUE TITLE
history_retention_period mistake in sp_change_log_shipping_secondary_primary

### ISSUE THREAD

**Issue by EitanBlumin** [MicrosoftDocs/sql-docs#6182]
The following documentation seems to have a mistake:

https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-change-log-shipping-secondary-primary-transact-sql.md

The following part supposedly describes the `@file_retention_period` parameter, but in the description, it refers *history_retention_period* instead:

`[ @file_retention_period = ] 'file_retention_period'`
 Is the length of time in minutes in which the history will be retained. *history_retention_period* is **int**, with a default of NULL. A value of 14420 will be used if none is specified.  

Does the `@file_retention_period` parameter affect the history retention period as well?

It looks to me like a copy-paste error copied from either of the procedures `sp_change_log_shipping_primary_database` or `sp_change_log_shipping_secondary_database`.

Can you please update the documentation to properly clarify this? 

Thanks

**Comment by WilliamAntonRohm** [comment]
@EitanBlumin -- Eitan, thank you for catching this.

@MashaMSFT -- Masha, please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @EitanBlumin , thanks so much for bringing this to our attention! We've processed a change in PR [6291](https://github.com/MicrosoftDocs/sql-docs/pull/6291) to update this typo. This change should be live later this week. 

I'll close out this Git Issue for the time being but please feel free to comment should you need anything further.

Thanks for improving our docs and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
#reassign:kfarlee
