### ISSUE TITLE
Typo in "Complete Example" section

### ISSUE THREAD

**Issue by emad-almousa** [MicrosoftDocs/sql-docs#6184]
in "Complete Example" section "4" you are referencing the wrong database name USE AdventureWorks2012; it should
be replaced with **USE AdventureWorks2017**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca807e0-3f89-1a14-86af-d2d1b463ab1d
* Version Independent ID: 9e9ba593-b9e6-6cb4-e68a-b08558fe3504
* Content: [Tutorial: Signing Stored Procedures with a Certificate - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-signing-stored-procedures-with-a-certificate?view=sql-server-ver15#CompleteExample)
* Content Source: [docs/relational-databases/tutorial-signing-stored-procedures-with-a-certificate.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tutorial-signing-stored-procedures-with-a-certificate.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@emad-almousa -- Emad, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- Masha, please review this update in [private PR 18857](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18857).
