### ISSUE TITLE
EXECUTE AS (Transact-SQL) - document clarification

### ISSUE THREAD

**Issue by emad-almousa** [MicrosoftDocs/sql-docs#6185]
Hi,

This option is not available in a contained database or SQL Database or Azure Synapse Analytics.

can be changed to clearer statement:

**This option is not available in a SQL Server On-Premise contained database or Azure SQL Database or Azure Synapse Analytics.**

Reference Docs:

https://docs.microsoft.com/en-us/sql/t-sql/statements/execute-as-transact-sql?view=sql-server-ver15

Thanks,
Emad

**Comment by WilliamAntonRohm** [comment]
@emad-almousa -- Emad, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@WilliamDAssafMSFT -- William, please review this change in [private PR 18868](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18868).

**Comment by WilliamDAssafMSFT** [comment]
Thanks @emad-almousa for contacting Microsoft with feedback about our product documentation. 
EXECUTE AS _is_ supported in these platforms for both USER and LOGIN. Many of the contained or partially contained databases on these platforms do not have logins from the master database mapped to user databases however, so EXECUTE AS LOGIN may not work.

While this isn't Microsoft Support, can you provide detailed scripts and results on the issue you're having on these platforms?

**Comment by emad-almousa** [comment]
hi, you can close the ticket I just wanted to state a "minor" modification of the statement instead of SQL database----> Azure SQL Database. Thanks.

**Comment by WilliamAntonRohm** [comment]
@emad-almousa -- Emad, thank you for clarifying.

@WilliamDAssafMSFT -- William, thank you for your explanation.  I updated the [PR](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18868) to have just the one change.
