### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by theguru0** [MicrosoftDocs/sql-docs#6188]
Property NodeWieght = 1

Should be

Property NodeWeight = 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6481fbc7-f080-36fb-6dca-b5688f97c905
* Version Independent ID: 4a57a5e6-3e1d-5214-eba9-b5e57a28f4d2
* Content: [Force a WSFC Cluster to Start Without a Quorum - SQL Server Always On](https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/windows/force-a-wsfc-cluster-to-start-without-a-quorum?view=sql-server-ver15)
* Content Source: [docs/sql-server/failover-clusters/windows/force-a-wsfc-cluster-to-start-without-a-quorum.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/failover-clusters/windows/force-a-wsfc-cluster-to-start-without-a-quorum.md)
* Product: **sql**
* Technology: **failover-cluster-instance**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@theguru0 -- thank you for catching that.  I am updating the article.
