### ISSUE TITLE
Using temporal history retention policy approach

### ISSUE THREAD

**Issue by sqlworldwide** [MicrosoftDocs/sql-docs#6189]
[In this section](https://docs.microsoft.com/en-us/sql/relational-databases/tables/manage-retention-of-historical-data-in-system-versioned-temporal-tables?view=sql-server-ver15#using-temporal-history-retention-policy-approach):

Note section:
Using the Temporal History Retention Policy approach applies to SQL Database and SQL Server 2017 starting from CTP 1.3.

Will be cleared if modified to:
Using the Temporal History Retention Policy approach applies to **Azure** SQL Database and SQL Server 2017 starting from CTP 1.3.

I am assuming this feature is not available for 'Azure SQL Managed Instance'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99bdd334-2a3f-c8bb-fe67-a34f04dbae2b
* Version Independent ID: a485f3bf-2be0-8161-4cd8-7a63ac0ac828
* Content: [Manage historical data in System-Versioned Temporal Tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/manage-retention-of-historical-data-in-system-versioned-temporal-tables?view=sql-server-ver15#using-temporal-history-retention-policy-approach)
* Content Source: [docs/relational-databases/tables/manage-retention-of-historical-data-in-system-versioned-temporal-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/manage-retention-of-historical-data-in-system-versioned-temporal-tables.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@sqlworldwide -- thank you for your suggestion.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review this change in [private PR 18898](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18898).
