### ISSUE TITLE
Resource links / info missing on renaming a non-standalone instance

### ISSUE THREAD

**Issue by paulkathro** [MicrosoftDocs/sql-docs#6195]
Page refers to, but is missing links to resources on renaming a failover clustered (or AG) instance.
After digging, I found [this page](https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/install/rename-a-sql-server-failover-cluster-instance?view=sql-server-ver15) which has what I want and even links back to this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cc85187-40a7-2c00-a27b-23951994c215
* Version Independent ID: 87e62b4e-b1c8-eaac-acdf-744f5d5757e6
* Content: [Rename computer hosting instance - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/rename-a-computer-that-hosts-a-stand-alone-instance-of-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/install-windows/rename-a-computer-that-hosts-a-stand-alone-instance-of-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/rename-a-computer-that-hosts-a-stand-alone-instance-of-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@paulkathro -- Paul, thank you for your feedback and that link.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@cawrites -- please review this addition in [private PR 18938](https://github.com/MicrosoftDocs/sql-docs-pr/pull/18938).
