### ISSUE TITLE
OPTIMIZE_FOR_SEQUENTIAL_KEY showing in SQL Server 2017 documentation

### ISSUE THREAD

**Issue by paulkathro** [MicrosoftDocs/sql-docs#6200]
AFAIK, `OPTIMIZE_FOR_SEQUENTIAL_KEY`, optional parameter of `create index`, is a new feature in SQL Server 2019 and therefore shouldn't be displayed when looking at 2017 documentation.
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-2017#syntax-for-sql-server-and-azure-sql-database

**Comment by WilliamAntonRohm** [comment]
@paulkathro -- Paul, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@paulkathro -- Paul, I read through this article and there are several similar optional parameters that do not exist in SQL Server 2017, such as `RESUMABLE`.  Each parameter description states the applicable versions.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
