### ISSUE TITLE
SQL FOR JSON Option 1 Example is incorrect

### ISSUE THREAD

**Issue by JamesNJep** [MicrosoftDocs/sql-docs#6201]
There is in issue with the example shown in Option 1 of the JSON FOR documentation here https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-ver15 

The example shows SQL code to set the JSON key as UnitPrice, but the example data shows the key becomes Price.
The same type of error happens for the next column the code sets the value to Qty, but the data shows Quantity. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb5c17b-c567-303f-00b8-0c8a0ad15fb5
* Version Independent ID: a4ccc766-4a61-5b7a-e5dd-692e3cebb503
* Content: [Format Query Results as JSON with FOR JSON - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@JamesNJep -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@jovanpop-msft -- Jovan, this issue is in the image, and there is one reference to `UnitPrice` in the text (line 36).

**Comment by rwestMSFT** [comment]
I am submitting an internal PR that will update these images. Thanks for the feedback, @JamesNJep.

#assign:@rwestMSFT
