### ISSUE TITLE
Mask at the point of listing

### ISSUE THREAD

**Issue by harlananelson** [MicrosoftDocs/sql-docs#6215]
It would be nice to be able to mask data fields at the point of list (not in storage).  This way I could list the TOP 10 rows for a report, but not have the identifier (PID info)  in the report.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9408bf-18b5-339f-cd25-6a3024be3243
* Version Independent ID: eea4b8dc-5598-b7e6-e01a-902d5ca1f96d
* Content: [Dynamic Data Masking - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/dynamic-data-masking?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/dynamic-data-masking.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/dynamic-data-masking.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@harlananelson -- Harlan, thank you for your suggestion.  Please add it here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @VanMSFT for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
