### ISSUE TITLE
CATALOG_COLLATION not mentioned for database identifier collation rules

### ISSUE THREAD

**Issue by hilari0n** [MicrosoftDocs/sql-docs#6235]
The document on database identifiers for Azure SQL seems to be the same as for MS SQL, so it fails to mention the `CATALOG_COLLATION` impact on database identifiers. I.e. the whole part on identifier collation is (emphasis mine):

> The collation of an identifier depends on the level at which it is defined. Identifiers of instance-level objects, such as logins and database names, are assigned the default collation of the instance. **Identifiers of objects in a database, such as tables, views, and column names, are assigned the default collation of the database**. For example, two tables with names that differ only in case can be created in a database that has case-sensitive collation, but cannot be created in a database that has case-insensitive collation.

This would suggest, that the collation of the database identifiers relies on the database collation, which is not true for Azure SQL. There it relies on `CATALOG_COLLATION`, which is quite often different from the database collation (as the first has to be explicitly specified on database creation to be anything different than `SQL_Latin1_General_CP1_CI_AS`, and as it is rarely known to anyone, it usually remains as `SQL_Latin1_General_CP1_CI_AS`, while the database collation is a known concept and is quite often set to a different value on creation or later).
The fact that `CATALOG_COLLATION` is not prominently documented and omitted in such crucial places as this one, makes it a real PITA for many.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dc89ee-79b3-9175-fcbd-0115d0b8d00d
* Version Independent ID: 402a20bb-727f-5681-f288-471aa9cb6b50
* Content: [Database Identifiers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers?view=azuresqldb-current)
* Content Source: [docs/relational-databases/databases/database-identifiers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/database-identifiers.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@hilari0n -- thank you for your thorough feedback.

@stevestein -- please look into this issue and #6236.

**Comment by rothja** [comment]
@MashaMSFT Masha, could you work with the team and the product team on this issue. Thank you! #reassign:mashasmsft

**Comment by PRMerger18** [comment]
mashasmsft is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by WilliamDAssafMSFT** [comment]
@hilari0n Thanks for taking the time to create this GitHub issue with our documentation. I agree we should be more specific as to the behavior of database identifiers in Azure SQL Database because the relationship with the `master` database is different from SQL Server. This feedback is valuable to us and will be incorporated into the documentation in a future update. Thanks again.

**Comment by hilari0n** [comment]
This is now closed as completed. Where can I see the changes?

**Comment by WilliamDAssafMSFT** [comment]
Hi @hilari0n, the doc changes are tracked internally and separately from this public GitHub issue.

**Comment by hilari0n** [comment]
> Hi @hilari0n, the doc changes are tracked internally and separately from this public GitHub issue.

Uhm... What's preventing you from only closing this issue, only after the doc changes are made? That way those two tracking systems would be in sync and people filing issues here would actually be able to track something, instead of being kept in the dark on when (if at all) the issue is addressed.

**Comment by rwestMSFT** [comment]
@hilari0n Pursuing this conversation is unhelpful. As we have stated several times, the feedback will be incorporated into the documentation in a future update.

Thanks again for your contribution.
