### ISSUE TITLE
CATALOG_COLLATION not mentioned in document on database collation

### ISSUE THREAD

**Issue by hilari0n** [MicrosoftDocs/sql-docs#6236]
The document on database collation for Azure SQL seems to be the same as for MS SQL, so it fails to mention the `CATALOG_COLLATION` existence and relation to the database collation. As one can't change the `CATALOG_COLLATION` after database creation, so its conscious choice may be critical, it should be documented in articles like this one.

The fact that `CATALOG_COLLATION` is not prominently documented in general and omitted in such crucial places as this one, makes it a real PITA for many to understand why different behaviors between Azure SQL and MS SQL occur.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 683853cb-ea06-2b91-7606-6a313408e335
* Version Independent ID: 3f630abf-7950-5698-990e-331290ebb521
* Content: [Set or Change the Database Collation - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-database-collation?view=azuresqldb-current)
* Content Source: [docs/relational-databases/collations/set-or-change-the-database-collation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/set-or-change-the-database-collation.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@hilari0n -- thank you for your followup.

@stevestein -- please look into this issue and #6235.

**Comment by rothja** [comment]
@MashaMSFT Masha, this is a related git issue to #6235. I think the research required and/or changes required would be similar. #reassign:mashamsft

**Comment by rwestMSFT** [comment]
Related to https://github.com/MicrosoftDocs/sql-docs/issues/6235.

**Comment by WilliamDAssafMSFT** [comment]
@hilari0n Thanks for taking the time to create this GitHub issue with our documentation. I agree we should be more specific as to the behavior of database identifiers in Azure SQL Database because the relationship with the `master` database is different from SQL Server. This feedback is valuable to us and will be incorporated into the documentation in a future update. Thanks again.

**Comment by hilari0n** [comment]
This is now closed as completed. Where can I see the changes?

**Comment by rwestMSFT** [comment]
> This feedback is valuable to us and will be incorporated into the documentation in a future update.

**Comment by WilliamDAssafMSFT** [comment]
@hilari0n Thanks again for this feedback. Following up to let you know an update to a variety of articles regarding Azure SQL Database collation options has recently been published. For example, you'll see additional detail and examples here: https://learn.microsoft.com/en-us/sql/t-sql/statements/create-database-transact-sql?view=azuresqldb-current&preserve-view=true&tabs=sqlpool#collation_name
