### ISSUE TITLE
TDE Decrypt with CDC enabled

### ISSUE THREAD

**Issue by WHinDenver** [MicrosoftDocs/sql-docs#6239]
[Enter feedback here]
We discovered an issue attempting to remove TDE from a database that had Change Data Capture enabled.  We were not able to restore the database without the key due to some encryption in the log file.  Turning off CDC before decrypting the database allowed us to restore the database elsewhere successfully.  Sorry I don't have more technical details, but it might be worth noting in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20953c9f-c769-7849-420a-dac77f917d4a
* Version Independent ID: dfd9ad27-844c-c3c8-58a3-5d4a0c92fbba
* Content: [Transparent Data Encryption (TDE) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/transparent-data-encryption.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/transparent-data-encryption.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@WHinDenver -- thank you for your well-researched feedback.

@jaszymas -- please look into this issue.

**Comment by shohamMSFT** [comment]
#reassign:shohamMSFT

**Comment by VanMSFT** [comment]
Hey @shohamMSFT - Following up on this. Should we add a message regarding CDC for TDE?

**Comment by shohamMSFT** [comment]
@WHinDenver Sorry for the delayed response on this. This is an interesting scenario that you have mentioned and we will need to investigate this further. 
Was this a one-off occurrence or are you consistently facing this wherein you have to first turn off CDC, then decrypt the database and are then able to restore it? 
Can you provide some more details such as which version of SQL Server used? Also repro steps would greatly help so we can try to reproduce this on our end. Thanks!

**Comment by VanMSFT** [comment]
Closing this as we are awaiting more information.

**Comment by WHinDenver** [comment]
Come on, you don’t need any more information to recreate this issue than I already provided.  Sometimes it feels like if the request is not exactly to your liking you toss a question back so you can put it on hold and close it later.  My expectations is that you attempt a basic recreation of the issue on your end.  

Sent from my iPhone

On Apr 12, 2022, at 7:09 PM, Van To ***@***.***> wrote:

﻿
Closed #6239.

**Comment by VanMSFT** [comment]
> @WHinDenver Sorry for the delayed response on this. This is an interesting scenario that you have mentioned and we will need to investigate this further. Was this a one-off occurrence or are you consistently facing this wherein you have to first turn off CDC, then decrypt the database and are then able to restore it? Can you provide some more details such as which version of SQL Server used? Also repro steps would greatly help so we can try to reproduce this on our end. Thanks!

@WHinDenver - Can you help clarify Shoham's question to your issue?
