### ISSUE TITLE
Non-Microsoft website download link

### ISSUE THREAD

**Issue by chazjn** [MicrosoftDocs/sql-docs#6242]
The weblink provided to the 'Windows Installer 4.5' page goes to 'https://windows-installer.soft32.com/' - 

This looks like one of those dodgy software download websites. Surely this is not the official download source for this item??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da1f57b-a8fd-cca7-4cf0-9d594d365062
* Version Independent ID: 60c46780-6a03-7958-c77a-e7c94e3b9e85
* Content: [sqlcmd Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15)
* Content Source: [docs/tools/sqlcmd-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlcmd-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@chazjn -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review this update in [private PR 19001](https://github.com/MicrosoftDocs/sql-docs-pr/pull/19001).

**Comment by cawrites** [comment]
@cha-zhang thank you for contacting Microsoft, your update will appear in the next refresh.
