### ISSUE TITLE
Allocation bytes clarification for block size larger than 32

### ISSUE THREAD

**Issue by skrana** [MicrosoftDocs/sql-docs#6256]
When the block size is greater than 32, should the disk space allocated be **nKiB**?
Reference text: 
If nBytes is greater than 32, disk space is allocated **in blocks of nBytes bytes**. If you specify a block size value greater than 32, you can save substantial disk space.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4712e904-08c5-4d80-42f5-5cbd555a2105
* Version Independent ID: efe989fa-fc7e-3140-4ecf-4b036390eba2
* Content: [SET BLOCKSIZE Command - SQL Server](https://docs.microsoft.com/en-us/sql/odbc/microsoft/set-blocksize-command?view=sql-server-ver15)
* Content Source: [docs/odbc/microsoft/set-blocksize-command.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/microsoft/set-blocksize-command.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@skrana -- thank you for your question. 

- If nBytes is 0, disk space is allocated in single bytes (blocks of 1 byte). If nBytes is an integer between 1 and 32, disk space is allocated in blocks of nBytes bytes multiplied by 512. If nBytes is greater than 32, disk space is allocated in blocks of nBytes bytes *multiplied by 1024*.

@David-Engel -- please look into this issue -- are the added italics or the existing prose correct?

**Comment by David-Engel** [comment]
@skrana @WilliamAntonRohm 

No. The existing documentation is accurate.

From what I've read, `SET BLOCKSIZE to n` uses three different schemes: n x 512 byte blocks for 1–32, blocks of explicit n bytes for 33–32,768, and one byte blocks when n = 0.

**Comment by WilliamAntonRohm** [comment]
@David-Engel -- David, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by skrana** [comment]
Thanks for the clarification!
