### ISSUE TITLE
Error in grammer

### ISSUE THREAD

**Issue by TECKenWells** [MicrosoftDocs/sql-docs#6258]
The grammer of this is incorrect: "This topic describes how to grant the SQL Server Database Engine, file system access to the location..." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6273b4b6-5e71-e8fb-be7a-055e47f224a4
* Version Independent ID: 6107681b-f538-12ea-bf7d-c7fb179edd2a
* Content: [Configure File System Permissions for Database Engine Access - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-file-system-permissions-for-database-engine-access?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-file-system-permissions-for-database-engine-access.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-file-system-permissions-for-database-engine-access.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@TECKenWells -- thank you for catching this.  I am updating the article.
