### ISSUE TITLE
OPENJSON (Transact-SQL) claims Azure still defaults to Compat 120

### ISSUE THREAD

**Issue by LarnuUK** [MicrosoftDocs/sql-docs#6278]
Fromm [OPENJSON (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/functions/openjson-transact-sql?view=sql-server-ver15):

> Compatibility level 120 may be the default even in a new Azure SQL Database.

According to this [article](https://azure.microsoft.com/en-gb/blog/default-compatibility-level-140-for-azure-sql-databases/), from way back in August 2017, this is no longer true:
> As of today [28 August, 2017], the default compatibility level for new databases created in Azure SQL Database is 130. Very soon, we’ll be changing the Azure SQL Database default compatibility level for newly created databases to 140.

I can't see any other documents that make this [*exact* claim](https://www.google.com/search?q=%22Compatibility+level+120+may+be+the+default+even+in+a+new+Azure+SQL+Database.%22+site:docs.microsoft.com) (that doesn't mean there aren't any), however, [T-SQL differences between SQL Server & Azure SQL Managed Instance](https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/transact-sql-tsql-differences-sql-server) certainly agrees that 140 is the default and the SQL Azure Database(s) I have agrees with that.

**Comment by WilliamAntonRohm** [comment]
@LarnuUK -- Thom, thank you for your well-researched feedback.

@jovanpop-msft -- Jovan, please look into this issue.

**Comment by VanMSFT** [comment]
Thanks for bringing this issue to our attention, @LarnuUK! The current compatibility level is 150. I'll remove that text from the doc.

**Comment by VanMSFT** [comment]
#reassign:VanMSFT
