### ISSUE TITLE
[Typo] bigint != float64 in PYTHON to SQL mapping table 

### ISSUE THREAD

**Issue by sergiialtana** [MicrosoftDocs/sql-docs#6279]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ea22367-9924-edb3-c65a-66a1cb4181fa
* Version Independent ID: cef2a17a-d363-3042-e585-4c9184637eb4
* Content: [Convert Python and SQL data types - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/python/python-libraries-and-data-types?view=sql-server-ver15)
* Content Source: [docs/machine-learning/python/python-libraries-and-data-types.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/python/python-libraries-and-data-types.md)
* Product: **sql**
* Technology: **machine-learning-services**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@sergiialtana Thank you for opening a GitHub issue. Would you be able to provide a bit more detail of your issue? Thank you.

**Comment by dphansen** [comment]
@sergiialtana I am closing this GitHub issue, as we have not received a response from you. If you still have an issue, please open a new GitHub issue. Thank you.
