### ISSUE TITLE
Example output incorrect - array wrapper not shown

### ISSUE THREAD

**Issue by SomeTroglodyte** [MicrosoftDocs/sql-docs#6282]
The actual output from the query as shown will include an extra "[]", the shown output corresponds to the query with an additional WITHOUT_ARRAY_WRAPPER option.

(~~Also, a pointer as to why the json query functions will not unescape \u sequences and how to work around that would be nice.~~) my bad - all JSON functions and OPENJSON *do* unescape \u sequences appropriately

Tested on version 13.0.5850.14...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56b615ec-8726-dcaf-9009-c0193aacc430
* Version Independent ID: 5d2a5218-d935-7b70-6fdb-10b80d163010
* Content: [How FOR JSON escapes special characters and control characters - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/how-for-json-escapes-special-characters-and-control-characters-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/json/how-for-json-escapes-special-characters-and-control-characters-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/how-for-json-escapes-special-characters-and-control-characters-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@SomeTroglodyte -- thank you for your well-researched feedback.

@jovanpop-msft -- please look into this issue.

**Comment by rwestMSFT** [comment]
@SomeTroglodyte Thank you for your feedback. We have addressed this issue, and a refreshed article will be published in the next day or so.
