### ISSUE TITLE
"Feedback" links missing from most sections under Docs / SQL / Reference / ...

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#6296]
For some reason, the "Feedback" link (at the top of the page, between "Bookmark" and "Edit") _and_ the entire "Feedback" section (at the bottom of the page) are missing from most, but not all, pages within the **Docs / SQL / Reference / ...** area.

For example (neither of the following lists is exhaustive):

**Has link and section:**
* [Install the SQL Server PowerShell module](https://docs.microsoft.com/en-us/sql/powershell/download-sql-server-ps-module)

**Missing link and section:**
* [Errors and Events Reference](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/errors-and-events-reference-database-engine)
* [System Catalog Views](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/catalog-views-transact-sql)
* [System Dynamic Management Views](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/system-dynamic-management-views)
* [Transact-SQL Reference](https://docs.microsoft.com/en-us/sql/t-sql/language-reference)

**Comment by WilliamAntonRohm** [comment]
@srutzky -- Solomon, thank you again for your considered feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @srutzky for the feedback. Many reference articles do have the feedback option enabled. Some of these articles are procedurally generated based off source code, or in the past attracted a high amount of feedback that was low-quality. You can still submit a pull request by clicking the Edit button in the top-right hand corner to submit your suggestions for article improvements. By opening a pull request, you're helping the author add your approved change directly to the documentation. After the updated article is published, GitHub lists you as an article contributor. Once the PR is open, the content team can fine tune your suggestions, so don’t worry about getting everything formatted or capitalized just right. For a complete walkthrough of the the PR process in the browser, check out https://docs.microsoft.com/contribute/. 

Thanks again for your attention to these articles, this feedback helps improve our documentation.

**Comment by srutzky** [comment]
Hi @WilliamDAssafMSFT (and @WilliamAntonRohm ): Thanks for the reply, but um, is this a joke? Where are you seeing these "many" articles with Feedback links? Nearly all of the pages I checked in the **Docs  / SQL  / Reference** area no longer have Feedback links or sections. What does being procedurally generated have to do with anything? Is that something new, because all of these pages, as far as I had seen, had Feedback links and sections until recently. And thank you, I think, for the info about submitting PRs, but I don't see how that's relevant to this issue given that:
1. they clearly don't get the same level of engagement from the MS Docs team as issues do
2. they don't have the auto-populated info that points to the actual page on the web, the path to the source file, etc.
3. they don't work in situations such as #6297 where I know what's missing, but either I don't know what wording to use (in this case for the column descriptions), or it would be inappropriate for me to do that type and/or amount of work without being paid (as a contractor).

So, if I understand your response correctly, you are saying that Microsoft is intentionally making it harder for it's customers to volunteer time and effort to do Microsoft's QA work because some end-users were abusing this feature and either requesting changes that were possibly incorrect, and/or asking questions here instead of in an appropriate forum? Couldn't someone just add language to the "Feedback" section and/or auto-populated info that states appropriate usage and gives a link to the newer https://docs.microsoft.com/en-us/answers/products/ ?

**Comment by WilliamDAssafMSFT** [comment]
Thanks @srutzky, I hear you and the frustration. I do apologize, I obviously had a typo: I was acknowledging that many reference articles do NOT have the feedback option enabled for Github issues.

I'm sorry it's not been your experience but be assured the same teams and internal collaborations are involved with both Issues and PRs. 

If in the case you know what is missing but don't have all the details to fill in or time to research them, starting a PR for the article (and even leaving some things blank) is still the best way to get it fixed and to get recognition for contributing. Content teams will always review, edit to fine tune, and validate PRs before they are merged.
