### ISSUE TITLE
Newer columns missing from sys.parameters, sys.system_parameters, and sys.all_parameters System Catalog Views

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#6297]
The doc pages for [sys.parameters](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-parameters-transact-sql), [sys.system_parameters](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-system-parameters-transact-sql), and [sys.all_parameters](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-all-parameters-transact-sql) are all missing the following columns (all added in SQL Server 2016; perhaps for Always Encrypted?):

1. `encryption_type`
1. ` encryption_type_desc`
1. ` encryption_algorithm_name`
1. `column_encryption_key_id`
1. `column_encryption_key_database_name`

Additionally, the pages for `sys.system_parameters` and `sys.all_parameters` are both missing the following columns (which should be listed before the five columns noted above):

1. `is_readonly` (added in SQL Server 2008; for Table-Valued Parameters)
1. `is_nullable` (added in SQL Server 2014; for Native Compiled procs)

You can see the full set of columns returned by executing the following query:

```sql
SELECT -- PLEASE NOTE: the following CASE will NOT work for all queries or catalog views;
       -- It is just meant for this query for sys.parameters columns
       CASE typ.[name]
         WHEN N'nvarchar' THEN CONCAT(N'nvarchar(', (typ.[max_length] / 2), N')')
         ELSE typ.[name]
       END AS [DataType],
       col.*
FROM   sys.all_columns col
INNER JOIN sys.types typ
        ON col.[user_type_id] = typ.[user_type_id]
WHERE  col.[object_id] = OBJECT_ID(N'sys.parameters')
ORDER BY col.[column_id];
```
Even though the above query only returns columns for one of the three views, you can see that all three have the exact same columns by executing the following query:

```sql
SELECT * FROM sys.parameters
UNION
SELECT * FROM sys.system_parameters
UNION
SELECT * FROM sys.all_parameters
```

If there were any differences in the result set (datatypes, number of columns, etc), then the `UNION` would return an error.

P.S. This issue doesn't include the automatically pre-filled data due to there not being a "Feedback" link or button to click on to create an issue for a particular doc page (hence: #6296 ).

**Comment by WilliamAntonRohm** [comment]
@srutzky -- Solomon, thank you for your well-researched feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @srutzky for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your suggestions. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. 
	
Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
Hi @srutzky while this work is in progress with a backlog item, I wanted to mention:

The query you provided if re-used could benefit from this change:

Find:
WHEN N'nvarchar' THEN CONCAT(N'nvarchar(', (typ.[max_length] / 2), N')')
Replace with:
WHEN N'nvarchar' THEN CONCAT(N'nvarchar(', (**col**.[max_length] / 2), N')')

Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
Hi @srutzky these article updates are in flight. I've submitted a documentation change based on your suggestion, and it should be live in the next day. Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by srutzky** [comment]
@WilliamDAssafMSFT Good catch on that query change (i.e. `typ` -&gt; `col` table alias). I have updated it in the initial comment to prevent anyone from copying the flawed version if  they hadn't also read your comment. Thanks for pointing that out.
