### ISSUE TITLE
Syntax page for sys.database_scoped_credentials incorrectly implies presence of principal_id column in 2016

### ISSUE THREAD

**Issue by RobAshton-IM** [MicrosoftDocs/sql-docs#6307]
The [syntax page for the sys.database_scoped_credentials view](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-database-scoped-credentials-transact-sql.md) implies that the principal_id column is present in all supported versions of SQL Server, i.e. from SQL Server 2016 onwards, when it was actually introduced in SQL Server 2017.

The syntax page should be updated to reflect this fact so that users will understand that this view underwent a structure revision between 2016 and 2017.

**Comment by WilliamAntonRohm** [comment]
@RobAshton-IM -- thank you for your feedback.  I am looking into this page.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please review [private PR 19174](https://github.com/MicrosoftDocs/sql-docs-pr/pull/19174).

**Comment by VanMSFT** [comment]
Approved William's changes.
