### ISSUE TITLE
SQL on Linux and Authentication [SQL & Active Directory]

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#6308]
I would like to clarify something.  This page indicates **_ONLY_** SQL-based authentication.  It even states "_For SQL Server on Linux, use SQL Server Authentication._"  It was my understanding that **BOTH** SQL and Active Directory authentication could be used when accessing SQL on a Linux host.  There are a number of URL's that are supposed to show how to get this set up.
I am wondering if the other pages are wrong, or THIS page is wrong - and AD Authentication ***can*** be used.  

***_If_*** AD authentication can be used, there should at least be a note on this page to indicate that potential, to be consistent with pages such as:
1] https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-ad-auth-adutil-tutorial?view=sql-server-ver15
2] https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44db5687-5102-dea4-b7b3-f088cdf57457
* Version Independent ID: b8d4cdad-8b18-2eea-415d-97f6048535af
* Content: [Use SSMS to Manage SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-manage-ssms?view=sql-server-ver15&source=docs)
* Content Source: [docs/linux/sql-server-linux-manage-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-manage-ssms.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @LindaLF! Thanks for pointing this out. You are correct, that Windows Authentication is available if AD Authentication is set up. I'll revised this doc. Thanks!

**Comment by LindaLF** [comment]
Yeah, too bad we haven’t gotten it working here yet, in spite of the URL’s I mentioned.  Sigh...

Linda
