### ISSUE TITLE
Page out of date for most recent SSMS version

### ISSUE THREAD

**Issue by robbbbbb** [MicrosoftDocs/sql-docs#6312]
This entire page appears to be completely out of date as SSMS 18 no longer has the "Tasks > Back Up..." context menu option. 

It appears the application now only supports export of SQL Server databases to a 'Date-tier Application' in the the '.bacpac' file format as covered [here](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/export-a-data-tier-application?view=sql-server-ver15)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b39a6f87-ff17-e358-4a7c-ea7c2a037cde
* Version Independent ID: a8691d00-99a1-ec0d-346b-fee8f78202dd
* Content: [Quickstart: Backup & restore to Azure Blob storage service - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-sql-server-backup-and-restore-to-azure-blob-storage-service?view=sql-server-ver15&tabs=SSMS#create-a-test-database)
* Content Source: [docs/relational-databases/tutorial-sql-server-backup-and-restore-to-azure-blob-storage-service.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tutorial-sql-server-backup-and-restore-to-azure-blob-storage-service.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@robbbbbb -- Rob, thank you for your feedback.

@cawrites -- please look into this issue.

**Comment by cawrites** [comment]
@robbbbbb thank you for contacting Microsoft and providing your first feedback on this content. I will be looking at your feedback and likely asking more questions to get some clarity around your request.

**Comment by cawrites** [comment]
@robbbbbb we appreciate you reaching out, but we were unable to find an issue based on your specific ask.  Context-based references are always helpful in finding an issue or asking a question. We encourage you to continue to reach out when you have a document-related concern. Thank you and welcome to the community.
