### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by TorquinDSL** [MicrosoftDocs/sql-docs#6316]
How come this page does not seem to address security for constraints, adding/dropping?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d95c4e-dfbb-ec5a-7df9-8a8d33be5b83
* Version Independent ID: a35a9368-4e76-6d55-7e90-34e925b34dd7
* Content: [Database-Level Roles - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/authentication-access/database-level-roles.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/database-level-roles.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @TorquinDSL - Can you please clarify which constraints you are talking about, and why you think they should be in the Database-Level Roles article?
