### ISSUE TITLE
Support for RHEL 7.9

### ISSUE THREAD

**Issue by krishnamsft20** [MicrosoftDocs/sql-docs#6320]
Is there a reason we exclude RHEL 7.9 from Supported Platforms for SQL Server 2019 on Linux?

the documents only specify Red Hat Enterprise Linux 7.3 - 7.8, or 8.0 - 8.3 Server

Some customers are wondering if RHEL 7.9 is supported. 
Please update docs if it is supported

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e57953d0-a43f-3e01-a792-bcf4fe241579
* Version Independent ID: 1c4a4f72-bc1d-1a03-fbe6-df21c0149d03
* Content: [Release notes for SQL Server 2019 on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-release-notes-2019.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-release-notes-2019.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hey @tejasaks - Can you please help confirm if RHEL 7.9 has been tested to be supported? Thanks!

**Comment by tejasaks** [comment]
Amit to check this out.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by VanMSFT** [comment]
@amvin87 - Hey Amit, can you please help confirm if RHEL 7.9 is supported? Thanks!

**Comment by amvin87** [comment]
Rhel 7.9 is supported! @VanMSFT Can we please modify the document to include RHEL 7.9 as supported distribution please. Thank you for the feedback!

**Comment by VanMSFT** [comment]
Thanks, @amvin87! Will get this updated

**Comment by VanMSFT** [comment]
Thanks @krishnamsft20 for reporting this. The doc has been updated, and will appear live soon.

**Comment by krishnamsft20** [comment]
Thank you!

Krishna Bhurtel
SUPPORT ENGINEER
Office: +1 (469) 7750067
***@***.******@***.***>
9 AM - 6 PM CST
Manager: Mohammad Batayneh
***@***.******@***.***>
[Microsoft]
The content of this email including its attachments (the "Content") is confidential and provided for information purposes only. It does not under any circumstance constitute a legally binding offer or acceptance of Microsoft Ireland Operations Limited or any other Microsoft Group affiliate. This Content shall not be construed as (i) any commitment from Microsoft Ireland Operations Limited or any other Microsoft Group affiliate and/or (ii) supplementing or amending the terms of any existing agreement with Microsoft Ireland Operations Limited or any other Microsoft Group affiliate. In any case, any commitment from Microsoft Ireland Operations Limited or any other Microsoft Group affiliate must be prior stated in an agreement drafted by Microsoft and signed by the duly authorized representatives of the Microsoft affiliate concerned and your company. Furthermore you are reminded that the Content is solely based on the information provided to us at the time of this email and that it will be subject to possible change.
