### ISSUE TITLE
RegisterAllProvidersIP=0 and SQL AG using DNN

### ISSUE THREAD

**Issue by PhilB-MSFT** [MicrosoftDocs/sql-docs#6321]
Please can this document be reviewed with respect to the suggested use of RegisterAllProvidersIP=0. SQL Server 2019 CU8 released the DNN functionality for AG (https://docs.microsoft.com/en-us/azure/azure-sql/virtual-machines/windows/availability-group-distributed-network-name-dnn-listener-configure). 

I don't believe that cluster will honour the RegisterAllProvidersIP=0 when using a Distributed Network Name (i.e. it will always register all IP Addresses associated with the nodes that are possible owners) and therefore it is not an option when using DNN.

I'm not sure if this doc could be re-written to clarify the VNN/DNN options, or if it just needs a note/warning in an appropriate place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b679be86-06b0-b425-cd4f-d7b3ea104693
* Version Independent ID: aec2cf5b-5bf9-647e-6b0f-9fab6fca3a79
* Content: [Configure availability group listener - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@PhilB-MSFT -- Phil, thank you for your suggestions.

@cawrites -- Cheryl, please look into this issue.

**Comment by cawrites** [comment]
@PhilB-MSFT I have asked a PM to review this request.

**Comment by cawrites** [comment]
@PhilB-MSFT I was given this information to provide clarity.
 https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sync-staging-server

I understand this has taken an extended period of time. If this isn't what you needed I may have an alternativr solution. Please advise.

**Comment by cawrites** [comment]
@PhilB-MSFT I understand from our conversation you've been speaking with the PM. I am closing this issue since you have followed up offline.
