### ISSUE TITLE
Query Store is only available on SQL Server 2016 and higher

### ISSUE THREAD

**Issue by sqlgt0** [MicrosoftDocs/sql-docs#6324]
Query Store is a feature introduced on SQL Server 2016, so obviously the DMV and the feature itself would not be exposed to SQL Server (all supported versions)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b587ab-50b8-eada-aa86-ba0c838c57ee
* Version Independent ID: f1fd2d52-b66f-4fbc-c54a-c688c4fd0f21
* Content: [Monitoring Performance By Using the Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@sqlgt0 -- thank you for your feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Hi @sqlgt0 thanks for contacting Microsoft with feedback about our product documentation. This is of course correct and we'll fix the metadata. A doc update is in flight. 
	
Thanks again for this feedback, your suggestions help improve our documentation.
