### ISSUE TITLE
Visual Query Editor (SQL Pane) not supported for Azure SQL !

### ISSUE THREAD

**Issue by sdt-msft** [MicrosoftDocs/sql-docs#6325]
[Enter feedback here]

This page does not reflect the changes in support of the Visual Query Editor: visual editing of queries is not available for Azure SQL family of products. Please update or amend!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a34fe0e1-0377-d194-9f8c-e2aba78583f9
* Version Independent ID: 953e4378-9982-1622-f288-36da98774f57
* Content: [SQL Pane - Visual Database Tools](https://docs.microsoft.com/en-us/sql/ssms/visual-db-tools/sql-pane-visual-database-tools?view=sql-server-ver15)
* Content Source: [docs/ssms/visual-db-tools/sql-pane-visual-database-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/visual-db-tools/sql-pane-visual-database-tools.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@sdt-msft -- thank you for your feedback.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
@sdt-msft

Apologies for the delayed response, but can you be more specific?

thank you.

**Comment by sdt-msft** [comment]
Hi,
in this https://docs.microsoft.com/en-us/sql/ssms/visual-db-tools/sql-pane-visual-database-tools?view=sql-server-ver15
this https://docs.microsoft.com/en-us/sql/ssms/visual-db-tools/open-the-query-and-view-designer-visual-database-tools?view=sql-server-ver15

and other pages of the documentation of SQL Server Mgmt Studio, a visual query editor is described, but it actually does not work with Azure SQL databases (Azure SQL or Managed Instance): this is very misleading.

It seems this Visual query editor functionality for Azure SQL was dropped in 2017.

Please correct this.

Thanks
Stefano


--

STEFANO DE TONI

Cloud Solution Architect – Advanced Analytics and Artificial Intelligence

Microsoft Italy

Email: ***@***.******@***.***>

Cell: +39 335 755 87 78


________________________________

**Comment by markingmyname** [comment]
Hi, @sdt-msft.

First, apologizes for the extremely delayed response.

Unfortunately, the designer was never meant to work with Azure.

So if that seems misleading, then we will investigate and update the content.

We appreciate you bringing this to our attention.

Have a great weekend.

thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
