### ISSUE TITLE
Python code is with syntax problems on the WriteStream call

### ISSUE THREAD

**Issue by lcanastreiro** [MicrosoftDocs/sql-docs#6326]
https://docs.microsoft.com/en-us/sql/big-data-cluster/spark-streaming-guide?view=sql-server-ver15#sample-spark-streaming-application - this section of the code has syntax problems on the WriteStream call.

Thanks,
Luís.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7badf2b4-72c4-6cf5-6a2b-fffd51b51460
* Version Independent ID: 22f11199-dc54-6526-9e04-b651c4b50ded
* Content: [SQL Server Big Data Clusters Spark Streaming guide - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/spark-streaming-guide?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/spark-streaming-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/spark-streaming-guide.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @dacoelho
* Microsoft Alias: **dacoelho**

**Comment by WilliamAntonRohm** [comment]
@lcanastreiro -- Luís, thank you for your feedback.  Please clarify the type of failure.

@DaniBunny -- Daniel, please look into this issue.

**Comment by lcanastreiro** [comment]
this block here.
sensor_stats_df.writeStream
            .format("kafka")
            .option("topic", topic_to)
            .option("kafka.bootstrap.servers", bootstrap_servers)
            .option("kafka.sasl.mechanism", "PLAIN")
            .option("kafka.security.protocol", "SASL_SSL")
            .option("kafka.sasl.jaas.config", sasl)
            .save()

needs to be replaced by:

sensor_stats_df.writeStream \
            .format("kafka") \
            .option("topic", topic_to) \
            .option("kafka.bootstrap.servers", bootstrap_servers) \
            .option("kafka.sasl.mechanism", "PLAIN") \
            .option("kafka.security.protocol", "SASL_SSL") \
            .option("kafka.sasl.jaas.config", sasl) \
            .save() \

**Comment by WilliamAntonRohm** [comment]
@lcanastreiro -- Luís, thank you for clarifying.

**Comment by WilliamAntonRohm** [comment]
@DaniBunny -- Daniel, please review [private PR 19176](https://github.com/MicrosoftDocs/sql-docs-pr/pull/19176).

@lcanastreiro -- Luís, for future reference, you can enclose the whole snippet in triple backticks \`\`\` and it will render literally:
```
a \
line \
continued
```

**Comment by WilliamDAssafMSFT** [comment]
#assign:williamdassafMSFT

**Comment by WilliamDAssafMSFT** [comment]
Thanks @lcanastreiro very much for the input. Your feedback makes Microsoft Docs better. I've reviewed with the engineer and will be implementing a fix along these lines.
