### ISSUE TITLE
Replace cmds with PowerShell

### ISSUE THREAD

**Issue by MarcoEnxuto** [MicrosoftDocs/sql-docs#6328]
[Enter feedback here]

The section below:

**sc config SQLBROWSER start= auto**

After it is enabled, run the following command from the command prompt to start the service:

**net start SQLBROWSER**

should be:

Set-service sqlbrowser -StartupType Auto
Start-service sqlbrowser
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa839a1-df21-b566-b798-bf17159c4c74
* Version Independent ID: 97d386f4-c657-eaba-a62c-404ced145cb2
* Content: [Install SQL Server on Server Core - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-on-server-core?view=sql-server-ver15)
* Content Source: [docs/database-engine/install-windows/install-sql-server-on-server-core.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/install-sql-server-on-server-core.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@MarcoEnxuto -- Marco, thank you for your feedback.  I am looking into this article.

**Comment by MarcoEnxuto** [comment]
I see its still not updated, is there any issue using PowerShell to invoke those cmdlets?

**Comment by WilliamAntonRohm** [comment]
@cawrites -- Cheryl, please review this change in [private PR 19185](https://github.com/MicrosoftDocs/sql-docs-pr/pull/19185).

**Comment by cawrites** [comment]
@MarcoEnxuto thank you for contacting Microsoft. Your change was reviewed and should appear in the next content refresh.
