### ISSUE TITLE
Explanation on how to execute the Spark SQL piece of code

### ISSUE THREAD

**Issue by lcanastreiro** [MicrosoftDocs/sql-docs#6330]
Would be important to include a link to this other page (invoke Spark Jobs using cmdline) or to explain directly on this page how the Spark SQL code could be executed to create the "tables" requested on the python code to store the data:

section that starts with "Create the following tables by using Spark SQL."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7badf2b4-72c4-6cf5-6a2b-fffd51b51460
* Version Independent ID: 22f11199-dc54-6526-9e04-b651c4b50ded
* Content: [SQL Server Big Data Clusters Spark Streaming guide - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/spark-streaming-guide?view=sql-server-ver15#sample-spark-streaming-application)
* Content Source: [docs/big-data-cluster/spark-streaming-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/spark-streaming-guide.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @dacoelho
* Microsoft Alias: **dacoelho**

**Comment by WilliamAntonRohm** [comment]
@lcanastreiro -- Luís, thank you for your feedback.

@DaniBunny -- Daniel, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
#assign:williamdassafMSFT

**Comment by WilliamDAssafMSFT** [comment]
Thanks @lcanastreiro very much for the input. Your feedback makes Microsoft Docs better. I've reviewed with the engineer and will be implementing a fix along these lines.
