### ISSUE TITLE
Include note about Apple M1 for SQL Server docker image

### ISSUE THREAD

**Issue by badsyntax** [MicrosoftDocs/sql-docs#6333]
Hi there. The SQL Server 2019 docker image will not work on a Mac with Apple M1 chip using Rosetta emulation. See this issue for more details: https://github.com/microsoft/mssql-docker/issues/668

It would be helpful if that was mentioned on this page. Even better would be to provide arm64 versions of the docker image. Thanks!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-gb/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-bash)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by WilliamAntonRohm** [comment]
@badsyntax -- Richard, thank you for your research and feedback.  This repo is solely for documentation issues; please add your suggestion for arm64 images here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

@vin-yu -- Vin, please look into this issue.

**Comment by vin-yu** [comment]
@amvin87

**Comment by amvin87** [comment]
SQL Server 2019 container images are currently not supported for arm64, you can use azure-sql-edge container images for arm64 has documented here: https://azure.microsoft.com/en-in/products/azure-sql/edge/#:~:text=Bring%20the%20security%20and%20performance,machine%20learning%20and%20graph%20features.

**Comment by badsyntax** [comment]
This is not document on [this page](https://docs.microsoft.com/en-gb/sql/linux/quickstart-install-connect-docker?), hence the reason I created this issue (unless I'm missing something).

The following is stated as part of the Prerequisites:

- Docker Engine 1.8+ on any supported Linux distribution or Docker for Mac/Windows.

To me, this implies it should work on any Mac. All i'm saying is, the docs for this page can be improved to explicity mention that the image cannot be built using a Mac with an M1 chip.

**Comment by amvin87** [comment]
Sure, we can update the page to add the link to this page which mentions the hardware requirements including the supported processor types. : https://docs.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15?view=sql-server-ver15#pmosr

**Comment by badsyntax** [comment]
that would be helpful imo!
