### ISSUE TITLE
wrong column mentioned in the command 

### ISSUE THREAD

**Issue by sharma88bhaskar** [MicrosoftDocs/sql-docs#6339]
[Enter feedback here]

I see an extra column CreditCardID mentioned in the command bit is not refreneced any where .

 UPDATE CreditCard  
SET CardNumber_Encrypted = EncryptByKey(Key_GUID('CreditCards_Key11')  
    , CardNumber, 1, HASHBYTES('SHA2_256', CONVERT( varbinary  
    , **CreditCardID**)));
    
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd3dba3-ebd8-342e-fce9-af4c5ce39324
* Version Independent ID: f9725f20-7bdd-2e6c-f5db-957c00771d27
* Content: [Encrypt a Column of Data - SQL Server & Azure Synapse Analytics & Azure SQL Database & SQL Managed Instance](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/encrypt-a-column-of-data?view=azure-sqldw-latest)
* Content Source: [docs/relational-databases/security/encryption/encrypt-a-column-of-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/encrypt-a-column-of-data.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@sharma88bhaskar -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@sharma88bhaskar -- the `CreditCardID` column is in the `Sales.CreditCard` table.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
