### ISSUE TITLE
Dead link in ODBC "Using Integrated Authentication" docs

### ISSUE THREAD

**Issue by TheToddLuci0** [MicrosoftDocs/sql-docs#6342]
The link titled `Kerberos Configuration and Use` in the section [Deploying a Linux or macOS ODBC Driver Application Designed to Run as a Service](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication?view=sql-server-ver15#deploying-a-linux-or-macos-odbc-driver-application-designed-to-run-as-a-service) points to a dead link, now redirects to the O'Reilly home page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb3d740e-2304-39ef-ad0f-e26a52217f03
* Version Independent ID: 6c76ab3f-129f-ad54-08c4-27c813603dff
* Content: [Using Integrated Authentication - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/using-integrated-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/using-integrated-authentication.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@TheToddLuci0 -- thank you for your feedback.  I am looking into this article.
