### ISSUE TITLE
there is a typo

### ISSUE THREAD

**Issue by btlblt** [MicrosoftDocs/sql-docs#6343]
$serverName = "(local)";  

should be like this

$serverName = ("local");  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c0f0be-361d-4a9f-9585-beca93d2ab12
* Version Independent ID: e41acef1-da93-6e63-8be7-2182ea2d0b8f
* Content: [sqlsrv_connect - SQL Server](https://docs.microsoft.com/en-us/sql/connect/php/sqlsrv-connect?view=sql-server-ver15)
* Content Source: [docs/connect/php/sqlsrv-connect.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/sqlsrv-connect.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@btlblt -- thank you for catching this.  I am updating the article.

**Comment by David-Engel** [comment]
@btlblt It's not a typo.

`.`, `(local)`, `localhost`, and `YourMachineName` are all basically equivalent, referring to your own machine.

**Comment by WilliamAntonRohm** [comment]
@David-Engel -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
