### ISSUE TITLE
'Applies to' section is misleading

### ISSUE THREAD

**Issue by mkumar1212** [MicrosoftDocs/sql-docs#6349]
[This functionality is not true for Azure Synapse Analytics. No such option pops up in SSMS for a Synapse SQL Pool aka ADW]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76507156-d85c-e9f0-a214-3a9f1eb0f1fc
* Version Independent ID: 045c9c15-fbf9-abf9-c48a-904733e7ab42
* Content: [Change Column Order in a Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/change-column-order-in-a-table?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/change-column-order-in-a-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/change-column-order-in-a-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@mkumar1212 -- Mohit, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@stevestein -- Steve, please review [private PR 19321](https://github.com/MicrosoftDocs/sql-docs-pr/pull/19321).
