### ISSUE TITLE
Wrong version of libicu for Ubuntu 20.04

### ISSUE THREAD

**Issue by markhobson** [MicrosoftDocs/sql-docs#6351]
The installation instructions for Ubuntu state:

```
$ sudo apt-get install libicu60      # for 20.x
```

Whereas it should say:

```
$ sudo apt-get install libicu66      # for 20.x
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3df6af-9ac8-bc57-93dc-29ff713c1d3b
* Version Independent ID: 7624e2cc-7aa9-40dd-4015-3371ea2ea0a2
* Content: [Download and install sqlpackage - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15#supported-operating-systems)
* Content Source: [docs/tools/sqlpackage/sqlpackage-download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage/sqlpackage-download.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@markhobson -- Mark, thank you for catching this.  I am updating the article.
