### ISSUE TITLE
sys.views query should use "WHERE(CHARINDEX(vw.viewname, st.text, 1) > 0)"

### ISSUE THREAD

**Issue by ALZDBA** [MicrosoftDocs/sql-docs#6361]
the cross apply of the SYS,VIEWS query used vw._schemaname_ in its where clause.
That should be vw.viewname ! 

**WHERE(CHARINDEX(vw.viewname, st.text, 1) > 0)**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d55b6cb9-bcfb-6d53-d502-357dda974539
* Version Independent ID: 707c2dff-b5e2-1235-36fd-c6c2751fbf98
* Content: [DMVs - usage statistics and performance of views - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/use-dmvs-determine-usage-performance-views?WT.mc_id=DP-MVP-4029181&view=sql-server-ver15&source=docs)
* Content Source: [docs/relational-databases/performance/use-dmvs-determine-usage-performance-views.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/use-dmvs-determine-usage-performance-views.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
@ALZDBA I agree! This should be updated. Would you like to submit an edit via a pull request to correct the article yourself, and get contributor's credit for your Github account on the top of this page? Easy process documented here, all inside the Github UI: https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute#githubui
Let me know.
