### ISSUE TITLE
No example for Azure SQL Database

### ISSUE THREAD

**Issue by Frankd4** [MicrosoftDocs/sql-docs#6366]
[Enter feedback here]

Please provide steps for setting up SSL using JDBC for Azure SQL Database
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 595adadb-970f-2cc4-ff63-637ef2366416
* Version Independent ID: 196e559a-966b-70b4-34c9-9b944837cf49
* Content: [Configuring the client for encryption - SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/configuring-the-client-for-ssl-encryption?view=sql-server-ver15)
* Content Source: [docs/connect/jdbc/configuring-the-client-for-ssl-encryption.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/configuring-the-client-for-ssl-encryption.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@Frankd4 Steps for "setting up SSL" is a pretty broad request. Since you are talking about connecting to Azure SQL Database, I'll start with: There is nothing on the server-side that needs to be configured. All Azure SQL endpoints are already configured with SSL (TLS) certificates.

On the client-side, this is already well documented and is the same whether you are connecting to SQL Server or Azure SQL Database. Just remember, "SSL" is the very old encryption technology that is no longer considered secure. Most documentation calls it TLS now. However, "SSL" is still commonly used in conversation to describe encrypted communications between a client and server.

https://docs.microsoft.com/en-us/sql/connect/jdbc/using-ssl-encryption

If you already understand the basics, you simply need to include `encrypt=true;` in your connection string.

Regards,
David

**Comment by Frankd4** [comment]
Thank you, David. Sorry, I was referring to the TLS 1.2 setting on the Azure SQL server --> Firewalls and virtual networks

![image](https://user-images.githubusercontent.com/24920658/116949446-2d13c980-acbd-11eb-9fea-41938b822159.png)

So, all I need to do from the Client is use "encrypt=true;" ?, 
no need to import the certificate in the keystore using keytool ?

jdbc:sqlserver://servername.database.windows.net:1433;database=AdventureWorks;user=user@servername;password={your_password_here};**encrypt=true;**trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

**Comment by David-Engel** [comment]
> So, all I need to do from the Client is use "encrypt=true;" ?,
> no need to import the certificate in the keystore using keytool ?

`encrypt=true;` is optional, but highly recommended to avoid allowing the client to connect unencrypted to a malicious endpoint (spoofing the server). Yes, that is generally all that is needed on the client side. The caveat is older OSes/Java platforms or certain container configurations may need additional configuration to enable TLS 1.2. Anything modern should already have it enabled. The driver will use it automatically if the underlying platform is configured correctly.

You only need to import the server certificate if your environment is not already configured to trust common, public certificates (Azure-provided certificates are all public). This is usually already configured for you in a typical, modern OS or Java installation, but certain environments may need that additional step. You may need help from your IT department.
Ref: https://docs.microsoft.com/en-us/sql/connect/jdbc/configuring-the-client-for-ssl-encryption?view=sql-server-ver15#configuring-the-client-trust-store

Regards,
David

**Comment by Frankd4** [comment]
Thanks David. I'm following that link. But that link is not for Azure SQL database it's for SQL server. And therefore I requested you to please update & create one specific to Azure SQL Database Server

**Comment by David-Engel** [comment]
> Thanks David. I'm following that link. But that link is not for Azure SQL database it's for SQL server. And therefore I requested you to please update & create one specific to Azure SQL Database Server

The documentation applies to Azure SQL database, too. The client-side behavior of the driver is the same for whatever database it is connecting to. Unless a difference is specifically called out in the documentation, connecting to and executing against an Azure SQL Database is generally supported and behaves the same as SQL Server.

From the [Overview ](https://docs.microsoft.com/en-us/sql/connect/jdbc/overview-of-the-jdbc-driver?view=sql-server-ver15) page:

> The Microsoft JDBC Driver for SQL Server is a Type 4 Java Database Connectivity (JDBC) 4.2 compliant driver that provides robust data access to **SQL Server and Azure SQL databases.**

**Comment by Frankd4** [comment]
Ok, David. Please close the case. Thank you very much.

**Comment by David-Engel** [comment]
#please-close
