### ISSUE TITLE
/HideConsole option

### ISSUE THREAD

**Issue by mdexch** [MicrosoftDocs/sql-docs#6367]
I've used HideConsole option with setup and same work when install SQL Server 2017 CU. This is helpful in silent install as it hides the dos window about privacy notice. /quite option doesn't do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c50493f-74fc-becf-0ef1-618c99409545
* Version Independent ID: ccfd0c75-bd62-9993-fe27-1a6615432ce1
* Content: [Installing Updates from the Command Prompt - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/installing-updates-from-the-command-prompt?view=sql-server-2017)
* Content Source: [docs/database-engine/install-windows/installing-updates-from-the-command-prompt.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/installing-updates-from-the-command-prompt.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@mdexch -- thank you for your feedback.

@cawrites -- please look into this issue.

**Comment by cawrites** [comment]
@mdexch welcome to the contributor community. We appreciate you providing insights on this parameter. Your update will appear in the next refresh.
