### ISSUE TITLE
sys.resource_governor_workload_groups should include new request_max_memory_grant_percent_numeric column

### ISSUE THREAD

**Issue by rgward** [MicrosoftDocs/sql-docs#6368]
Starting in SQL Server 2019, you can set a REQUEST_MAX_MEMORY_GRANT_PERCENT to a float value and even < 1. This new column was added to track floating point values. We should add this to the doc page

**Comment by WilliamAntonRohm** [comment]
@rgward -- Bob, thank you for your feedback.  Are you referring to [this article](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-resource-governor-workload-groups-transact-sql?view=sql-server-ver15)?

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Resolved in https://github.com/MicrosoftDocs/sql-docs-pr/pull/19248
