### ISSUE TITLE
Document REQUEST_MAX_MEMORY_GRANT_PERCENT can be set to < 1

### ISSUE THREAD

**Issue by rgward** [MicrosoftDocs/sql-docs#6369]
Starting in SQL Server 2019 you can set the REQUEST_MAX_MEMORY_GRANT_PERCENT value to < 1. The docs say you can use floating point values but still says the value has to be > 1 which is not true. This can be very helpful for systems with large memory footprint and was a long customer request. We should also add an example of setting this value to a float < 1.

**Comment by WilliamAntonRohm** [comment]
Related to #6368.

**Comment by WilliamDAssafMSFT** [comment]
I believe the docs @rgward is referring to are: 
https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-workload-group-transact-sql and 
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-workload-group-transact-sql

@rgward can you confirm that before SQL 2019, the allowed range was 1-100 but starting with SQL 2019, the allowed range is 0-100?

**Comment by rgward** [comment]
Let's double-check with @Pedro ***@***.***> but yes I believe it is now 0-100 and allows floats.

The DMV has the new column in it but not the system table.

Thank you,

Bob Ward
Microsoft Azure Data
Cell: 817-455-0196

Empowering Others to Make a Difference

Get free training from from https://aka.ms/sqlworkshops<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fsqlworkshops&data=04%7C01%7Cbobward%40microsoft.com%7C2eab5d5b0bc741c758b308d8c8bfb76c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637480073024809999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=opkc3j1zbV%2B4ycBtfgg5HiCB4Np%2F0gykA%2FDdmc9HIbo%3D&reserved=0>
Want to learn Azure SQL? Get the book Azure SQL Revealed at https://aka.ms/azuresqlbook<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazuresqlbook&data=04%7C01%7Cbobward%40microsoft.com%7C2eab5d5b0bc741c758b308d8c8bfb76c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637480073024809999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PupUgoExg17eo8k8HArPqldptoAr8VEGA%2BSxz055yEM%3D&reserved=0>
Get the book SQL Server 2019 Revealed from https://aka.ms/sql2019book<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fsql2019book&data=04%7C01%7Cbobward%40microsoft.com%7C2eab5d5b0bc741c758b308d8c8bfb76c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637480073024819954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rr2uE3FwusAiwP%2Fx5PjigCkyEIeYGRNVdf0zg5LhF4w%3D&reserved=0>
Get the book Pro SQL Server on Linux from https://aka.ms/sqllinuxbook<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fsqllinuxbook&data=04%7C01%7Cbobward%40microsoft.com%7C2eab5d5b0bc741c758b308d8c8bfb76c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637480073024819954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tSR8qv3U0yhmvEFWOyDfjASJB3K%2FIdLekdaSdjjQ30s%3D&reserved=0>

**Comment by rgward** [comment]
Correct on both counts. On both pages, where it says "The allowed range for value is from 1 through 100." should be "The allowed range for value is from 0 through 100.".

Thanks

Pedro Lopes
***@***.***D7404A.757A0ED0]<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Ftwitter.com%2FSQLPedro&data=04%7C01%7CPedro.Lopes%40microsoft.com%7Cc574bc20263c4b864fa008d8d8429f46%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637497127944780062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b9j%2FkGMMfSYCLDdowqmJLAjom91qbbBTAx8djjBCrQY%3D&reserved=0>    ***@***.***D7404A.757A0ED0] <https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Flinkedin.com%2Fin%2Fpedroazevedolopes&data=04%7C01%7CPedro.Lopes%40microsoft.com%7Cc574bc20263c4b864fa008d8d8429f46%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637497127944790057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=z9y9DFY8%2FQQoHWH9AHKDdmXUa7zBVmpZEPSeRNywGx8%3D&reserved=0>

Need a way to keep indexes and statistics healthy? Check out AdaptiveIndexDefrag<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Faka.ms%2FAdaptiveIndexDefrag&data=04%7C01%7CPedro.Lopes%40microsoft.com%7Cc574bc20263c4b864fa008d8d8429f46%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637497127944800049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XkoD0Eoz%2FdIITMTyYcbJSwU03kq%2B8Pc6GouZRjkjho8%3D&reserved=0>!
Check your SQL Server for known best practices and performance issues with BPCheck<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Faka.ms%2FBPCheck&data=04%7C01%7CPedro.Lopes%40microsoft.com%7Cc574bc20263c4b864fa008d8d8429f46%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637497127944800049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2RbBhieenSc87Rvg6oV%2BSmZ1hLJuiX7FK7juYSBvnk4%3D&reserved=0>.
Learn T-SQL Querying book: aka.ms/LearnTSQLQuerying<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FLearnTSQLQuerying&data=04%7C01%7CPedro.Lopes%40microsoft.com%7Cc574bc20263c4b864fa008d8d8429f46%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637497127944810046%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gOYimf6o90bkdEpbQ9oMXar81gdVeTEp6LNIEEZnu3M%3D&reserved=0>
Follow the SQL Team on Twitter: @mssqltiger<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fmssqltiger&data=04%7C01%7CPedro.Lopes%40microsoft.com%7Cc574bc20263c4b864fa008d8d8429f46%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637497127944810046%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ArZ1xi95QNvxB8Wu5CvDbgF0%2FVv%2FzEbbDneHdcafPGw%3D&reserved=0> | Blog: aka.ms/sqlserverteam<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Faka.ms%2Fsqlserverteam&data=04%7C01%7CPedro.Lopes%40microsoft.com%7Cc574bc20263c4b864fa008d8d8429f46%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637497127944820040%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C5Hxo7EUc5%2FL7VwHORSGNWHprhyO%2BvouOWkaGLSeGKA%3D&reserved=0>

From: Bob Ward ***@***.***>
Sent: Monday, May 3, 2021 4:31 PM
To: MicrosoftDocs/sql-docs ***@***.***>; MicrosoftDocs/sql-docs ***@***.***>; Pedro Lopes ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/sql-docs] Document REQUEST_MAX_MEMORY_GRANT_PERCENT can be set to < 1 (#6369)

Let's double-check with @Pedro ***@***.***> but yes I believe it is now 0-100 and allows floats.

The DMV has the new column in it but not the system table.

Thank you,

Bob Ward
Microsoft Azure Data
Cell: 817-455-0196

Empowering Others to Make a Difference

Get free training from from https://aka.ms/sqlworkshops<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fsqlworkshops&data=04%7C01%7CPedro.Lopes%40microsoft.com%7C00896ac954dc470eea2c08d90e8b7157%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637556814325892105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GPY6fK1ZT%2Bwyt7RvhDzQCUmlZO%2FrIFZqYf7Rv2zmglQ%3D&reserved=0>
Want to learn Azure SQL? Get the book Azure SQL Revealed at https://aka.ms/azuresqlbook<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazuresqlbook&data=04%7C01%7CPedro.Lopes%40microsoft.com%7C00896ac954dc470eea2c08d90e8b7157%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637556814325902061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sPF6eK%2FrGJpZj5Pdih7cLUtIELdR2%2FRvo%2FehqwQo6NQ%3D&reserved=0>
Get the book SQL Server 2019 Revealed from https://aka.ms/sql2019book<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fsql2019book&data=04%7C01%7CPedro.Lopes%40microsoft.com%7C00896ac954dc470eea2c08d90e8b7157%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637556814325902061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=74Ug%2Bj154h%2B8hmkAtuPgP4PE6YQI%2FWEhaZYQO854tjU%3D&reserved=0>
Get the book Pro SQL Server on Linux from https://aka.ms/sqllinuxbook<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fsqllinuxbook&data=04%7C01%7CPedro.Lopes%40microsoft.com%7C00896ac954dc470eea2c08d90e8b7157%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637556814325912017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QfyDXDnkeaMRrW%2FbWmBPxBQP7%2FpyNbtMp%2B174Adavzo%3D&reserved=0>

**Comment by WilliamDAssafMSFT** [comment]
Resolved in https://github.com/MicrosoftDocs/sql-docs-pr/pull/19248
