### ISSUE TITLE
ISNULL (Transact-SQL) is not working on DATE

### ISSUE THREAD

**Issue by jhirschdrg** [MicrosoftDocs/sql-docs#6370]
ISNULL function is causing an "Operand type clash: int is incompatible with date" when using with a DATE datatype

```
DECLARE @Date DATE = '5/4/21'
PRINT ISNULL(@Date,0)
```

but when using ISNULL with the DATETIME datatype it's working 

```
DECLARE @DateTime DATETIME =  '5/4/21'
PRINT ISNULL(@DateTime, 0)
```

its either a SQL Server issue, or if it's intentional it should be in the doc the limitation

**Comment by WilliamAntonRohm** [comment]
@jhirschdrg -- thank you for your feedback.  Are you following a particular docs.microsoft.com article?  Meanwhile, you're welcome to add this here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

**Comment by jhirschdrg** [comment]
I look here 
https://docs.microsoft.com/en-us/sql/t-sql/functions/isnull-transact-sql?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@jhirschdrg -- thank you for clarifying.  This issue appears to be caused by incompatible implicit type conversions, that is, the specified replacement value in `ISNULL(@Date, 0)` is integer zero rather than a DATE itself.  DATETIME seems to allow a zero value.

@cawrites -- please look into this issue.

**Comment by cawrites** [comment]
@jhirschdrg I am trying to find the specific article you based your comment on. Is the example you gave, from a specific article ? the link you mentioned only speaks of ISNULL but not DATETIME

**Comment by cawrites** [comment]
@jhirschdrg thank you I understand the concern and frustration. Regarding the T-SQL content, it's not possible to list every combination that may/may not produce an error.  There may be other syntax combined with ISNULL that will not produce favorable results. The intent of the T-SQL content to define usage. DATE and DATETIME are common and used frequently. There is a number of articles in the content for DATE and DATETIME https://docs.microsoft.com/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql?view=sql-server-ver15

**Comment by cawrites** [comment]
@jhirschdrg thank you for providing this suggestion. We appreciate your input and will take this advisory for review.
