### ISSUE TITLE
Request to add SSMS licensing information

### ISSUE THREAD

**Issue by davidrshelton** [MicrosoftDocs/sql-docs#6373]
As a Microsoft licensing practitioner, I get asked all manner of Microsoft licensing questions on a daily basis.  Though it is generally understood that SSMS (SQL Server Management Studio) is a free tool, it's far too difficult to find this information from Microsoft themselves.  At a minimum, I would hope that the SQL Server Licensing Guides would weigh in on it, but to no avail.  Therefore, since this page is devoted specifically to SSMS, this would be an ideal place to put this information so we could reduce the number of times I and I'm sure scores of others are asked about the free nature of this product.

Thank you for your consideration of this suggestion.

Sincerely,

David Shelton
Manager, License & Asset Management
Applied Medical

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
Thank you for the feedback @davidrshelton - I am working on a PR to add links on this page to the license terms and privacy policy that are acknowledged during SSMS install.
#assign:dzsquared

**Comment by davidrshelton** [comment]
Drew,

Thanks for responding personally and acknowledging the need for the enhancement.  This might be the first time I’ve ever heard back from Microsoft regarding a documentation update.

I had forgotten about click-thru as a potential place where one might find this documentation, but as you might expect, there are lots of people who don’t ever touch the software who would want to know about the licensing implications.

Thanks,
David

P.S. Be sure to give Riccardo Muti my regards, if he happens to still be the PM for SSMS.

**Comment by PRMerger14** [comment]
Only Microsoft employees can manage issues via commenting in this repo.

**Comment by dzsquared** [comment]
@davidrshelton - glad I could level up your experience with the docs.

Riccardo is no longer the PM for SSMS, that would be me. 😄 

Links to the SSMS license terms and privacy statement are now on the download page, I hope that is an easier link to locate.
https://docs.microsoft.com/sql/ssms/download-sql-server-management-studio-ssms

#please-close
