### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by aauronn** [MicrosoftDocs/sql-docs#6376]
Customer Case Studies links are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91f89b-5196-0ea5-28fc-79cf59ab327e
* Version Independent ID: 0f4f2d0d-0913-8b47-15ab-7300dc2aa1a3
* Content: [Overview and Usage Scenarios - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/overview-and-usage-scenarios?view=sql-server-ver15)
* Content Source: [docs/relational-databases/in-memory-oltp/overview-and-usage-scenarios.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/overview-and-usage-scenarios.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @Kevin-Farlee
* Microsoft Alias: **kfarlee**

**Comment by WilliamAntonRohm** [comment]
@aauronn -- Luis, thank you for catching this.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@Kevin-Farlee -- Kevin, two _Customer case studies_ sections are for older versions of SQL Server: [here](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/overview-and-usage-scenarios?view=sql-server-ver15#customer-case-studies-1) and [here](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/overview-and-usage-scenarios?view=sql-server-ver15#customer-case-studies-2).  Here are the [current in-memory OLTP customer case studies](https://customers.microsoft.com/en-us/search?sq=in%20memory%20oltp&ff=&p=0&so=story_publish_date%20desc).
