### ISSUE TITLE
SQL Server 2016 Standard Edition.  

### ISSUE THREAD

**Issue by PaulCoetser** [MicrosoftDocs/sql-docs#6378]
[Enter feedback here]
This does not work on SQL Server 2016 Standard Edition.   Your documentation stated this will work on all versions of SQL Server.  

CREATE PARTITION FUNCTION [PF_DocumentHistoryPartition] (BIGINT)
AS RANGE RIGHT FOR VALUES 
(
  2147483648 
);
GO

Msg 7736, Level 16, State 1, Line 24
Partition function can only be created in Enterprise edition of SQL Server. Only Enterprise edition of SQL Server supports partitioning.

Please advice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4466c524-282b-adc0-d539-3eb85d956597
* Version Independent ID: 08052bb4-d7bb-02ab-6d37-e3fcce20846c
* Content: [Create Partitioned Tables and Indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/partitions/create-partitioned-tables-and-indexes?view=sql-server-2016)
* Content Source: [docs/relational-databases/partitions/create-partitioned-tables-and-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/partitions/create-partitioned-tables-and-indexes.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@PaulCoetser -- thank you for your feedback.  I am updating the applicability in this article.

**Comment by cawrites** [comment]
@PaulCoetser this content link states that starting with 2016 sp1 it does have partitioning https://docs.microsoft.com/en-us/archive/blogs/sqlreleaseservices/sql-server-2016-service-pack-1-sp1-released

**Comment by cawrites** [comment]
@WilliamAntonRohm please hold for updates.

**Comment by cawrites** [comment]
Thank you for contacting Microsoft regarding this question. The reference information you have been provided will confirm that this option is available once the appropriate service pack is applied.
