### ISSUE TITLE
anny.star15@hotmail.com

### ISSUE THREAD

**Issue by vic-simons** [MicrosoftDocs/sql-docs#6388]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0db48ae-6190-c9a4-41dd-17bb38ab25e6
* Version Independent ID: 44b68238-6935-4909-a42b-793d523e7554
* Content: [Visual FoxPro ODBC Driver - Open Database Connectivity (ODBC)](https://docs.microsoft.com/en-us/sql/odbc/microsoft/visual-foxpro-odbc-driver?view=sql-server-ver15)
* Content Source: [docs/odbc/microsoft/visual-foxpro-odbc-driver.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/microsoft/visual-foxpro-odbc-driver.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
