### ISSUE TITLE
Page is not accurate for "All Supported Versions of SQL Server', as it states.

### ISSUE THREAD

**Issue by kstuber** [MicrosoftDocs/sql-docs#6399]
This page says it applies to All Supported Versions of SQL Server, but, as an example, the 1700 byte max for non-clustered index keys was only added in SQL 2016. Having version-specific versions of this page would be quite useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 780e3e16-ac52-1343-fe0a-a706c71ddb92
* Version Independent ID: 6f09b278-faa0-6f0d-1013-c1ae62ca006c
* Content: [Maximum capacity specifications for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server?view=sql-server-2017)
* Content Source: [docs/sql-server/maximum-capacity-specifications-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/maximum-capacity-specifications-for-sql-server.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@kstuber -- Ken, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by MikeRayMSFT** [comment]
@kstuber -- thanks for the request.  We're reviewing based on your suggestion.

**Comment by MikeRayMSFT** [comment]
@kstuber -  Ken, thanks for the feedback. 

Based on your feedback we're adding some information to the column mentioned, and a link back to the 2014 capacity article archive.

https://docs.microsoft.com/en-us/previous-versions/sql/2014/sql-server/maximum-capacity-specifications-for-sql-server

The updated article will be available later today.

**Comment by kstuber** [comment]
Fantastic, thank you!!
