### ISSUE TITLE
Out-of-Date

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#6401]
This page still references CodePlex - please update and be sure that all references for these tutorials lead to the most up-to-date materials.

The aging of this article does not inspire confidence, especially in new learners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9261422-8fd0-f534-8503-b3f144853958
* Version Independent ID: 0c05cc4f-8260-a264-e724-2f3801f82862
* Content: [Tutorials for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/tutorials-for-sql-server-2016?view=sql-server-ver15)
* Content Source: [docs/sql-server/tutorials-for-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/tutorials-for-sql-server-2016.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@PrometheusRising1 -- thank you for your feedback.

@rothja -- please look into this issue.

**Comment by rothja** [comment]
@PrometheusRising1 You're absolutely right. We just became aware of this issue in several other places in our documentation set. Apologies for this, and we will get it corrected as soon as possible. Thank you for for bringing it to our attention. @MikeRayMSFT FYI.

**Comment by rothja** [comment]
We are going to go through all of the SQL Documentation and remove / replace references to codeplex. This should be updated in the near future. Thank you!
