### ISSUE TITLE
STRING_AGG syntax is wrong

### ISSUE THREAD

**Issue by MosheWeingarten** [MicrosoftDocs/sql-docs#6403]
https://docs.microsoft.com/en-us/sql/t-sql/functions/string-agg-transact-sql?view=sql-server-ver15

The WITHIN Group syntax documentation is missing a Group By Clause

**Comment by WilliamAntonRohm** [comment]
@MosheWeingarten -- thank you for your feedback.

@julieMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
Analytic functions support evaluation over group of rows. But this syntax users OVER clause and the keyword is PARTITION BY.

GROUP BY is used only in SELECT statement. 

reviewed with @uc-msft 

Thanks
