### ISSUE TITLE
documentation improvement

### ISSUE THREAD

**Issue by KeeveySongMS** [MicrosoftDocs/sql-docs#6404]
currently only access key and managed identity works in dedicated SQL pool and only shared access signature and managed identity works in serverless SQL pool.
I do understand we have indicated this by saying:
![image](https://user-images.githubusercontent.com/75061821/118225054-ea20d580-b4b6-11eb-9aee-98fe368ebd8e.png)
![image](https://user-images.githubusercontent.com/75061821/118225089-f9078800-b4b6-11eb-9584-d5115b27c324.png)

But I think this is not clear for user to get the point. Hope we can improve this in this doc: https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-scoped-credential-transact-sql?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@KeeveySongMS -- thank you for your suggestions.

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
Thanks, @KeeveySongMS - This is documented in our Azure Synapse docs, but I will add a link to it from the scoped credential page. https://docs.microsoft.com/en-us/azure/synapse-analytics/sql/develop-tables-external-tables?tabs=hadoop

@WilliamDAssafMSFT @julieMSFT - FYI

**Comment by VanMSFT** [comment]
The authentication seems to have been updated for Azure Synapse. @julieMSFT @WilliamDAssafMSFT - Do you mind checking the supported authentication types for the different external tables, so that we can add some clarity to the Database Scoped Credential doc? Thanks!

**Comment by julieMSFT** [comment]
@VanMSFT , yes it did just get updated in the  https://docs.microsoft.com/en-us/azure/synapse-analytics/sql/develop-tables-external-tables?tabs=hadoop article due to preview support for native parquet tables in dedicated SQL pool.

**Comment by VanMSFT** [comment]
I'm updating the database scoped credential doc for more clarity on storage authentication for Azure Synapse.
