### ISSUE TITLE
TRY_CAST  returns 0 if empty string is converted to int

### ISSUE THREAD

**Issue by DiPal2** [MicrosoftDocs/sql-docs#6408]
From https://docs.microsoft.com/en-us/sql/t-sql/functions/try-cast-transact-sql :
TRY_CAST returns a value cast to the specified data type if the cast succeeds; otherwise, returns null.

But TRY_CAST('' AS INT) returns 0.

Is it expected?

**Comment by WilliamAntonRohm** [comment]
@DiPal2 -- thank you for your question.  I believe that is the expected value, as an empty string is zero characters and represents a literal nothing.

@julieMSFT -- please verify.

**Comment by siggemannen** [comment]
try_cast(x as y) should return same as cast(x as y) on success, and cast('' as int) returns 0 so it's probably to be expected

**Comment by julieMSFT** [comment]
@DiPal2 Thank you for contacting Microsoft. Yes this behavior is expected. The the try_cast did not fail. The '' is implicitly converted to an integer. An Empty string is a value of zero length which is implicitly converted to 0.

**Comment by julieMSFT** [comment]
#please-close
