### ISSUE TITLE
Executing one of the SQL statements gives me the following error

### ISSUE THREAD

**Issue by CXMelga** [MicrosoftDocs/sql-docs#6409]
Hello

I ran through all the the items in the post successfully (apart from the fact I had to create a registry key manually) so all the commands worked OK apart from the last one 

--Enable TDE by setting ENCRYPTION ON
ALTER DATABASE TestTDE
SET ENCRYPTION ON; 

When I execute this I get the following error

Msg 33106, Level 16, State 1, Line 2
Cannot change database encryption state because no database encryption key is set.
Msg 5069, Level 16, State 1, Line 2
ALTER DATABASE statement failed.

Please explain the issue and fix

Thank you
Charlie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4997f245-c966-51a3-34c7-705c3cfbd4b0
* Version Independent ID: 129fbe40-3b02-f2c1-ef13-b42d86ffdb77
* Content: [Set up Transparent Data Encryption (TDE) Extensible Key Management with Azure Key Vault - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-ver15&tabs=portal)
* Content Source: [docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @Rupp29
* Microsoft Alias: **arupp**

**Comment by Rupp29** [comment]
Hello Charlie;
Without knowing exactly the results of the previous steps, my first thought is that if your SQL Server service does not have read/write permissions to the registry and something did not get setup correctly. You did not say what registry settings you created manually as there are a few that you would need to make in lieu of having the configuration process do it.  If you can revert the configuration/setup, back out all the objects (logins, asymmetric keys, credentials, etc... and then unregister the crypto provider DLL (SQL Server Connector) and RESTART SQL Server. Then try again this time making sure the SQL Server Service has read/write permissions to the registry, you may have better luck.

**Comment by MikeRayMSFT** [comment]
Closing this issue. 

@CXMelga - I went through the steps and could not reproduce. If you do reproduce the issue, please provide the specifics about the registry key you changed and additional details as requested by @rupp29. You can either open a new issue, or [request support](https://docs.microsoft.com/sql/sql-server/sql-server-get-help). 

#please-close
