### ISSUE TITLE
TRANSACTION WITH MARK

### ISSUE THREAD

**Issue by MichaelFirsov** [MicrosoftDocs/sql-docs#6411]
Hello!
MS SQL Server 2019 (and all other versions except 2017) does not insert a row into logmarkhistory table when a marked transaction (BEGIN TRANSACTION WITH MARK) is carried out.

EXAMPLE:
     USE AdventureWorks2019;  
     GO 
        
     BEGIN TRANSACTION CandidateDelete  
         WITH MARK N'Deleting a Job Candidate';  
         
     DELETE FROM AdventureWorks2019.HumanResources.JobCandidate  
          WHERE JobCandidateID = 13;  
         
     COMMIT TRANSACTION CandidateDelete;  
     GO  
        
     SELECT * FROM [msdb].[dbo].[logmarkhistory];
     GO

- the last command (SELECT * FROM [msdb].[dbo].[logmarkhistory]) will always return the empty set.
Regards,
Michael Firsov
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20afbbca-5fed-b938-abf8-fca9f61c1850
* Version Independent ID: 78528cda-05db-73c9-ed74-4f11002b9a4c
* Content: [Restore databases to marked transaction - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/use-marked-transactions-to-recover-related-databases-consistently?view=sql-server-ver15)
* Content Source: [docs/relational-databases/backup-restore/use-marked-transactions-to-recover-related-databases-consistently.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/use-marked-transactions-to-recover-related-databases-consistently.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@MichaelFirsov -- Michael, thank you for your well-researched feedback.

@cawrites -- Cheryl, please look into this issue.

**Comment by MichaelFirsov** [comment]
Oh, awfully sorry... it does work, but apparently the problem stems from the documentation: [this ](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/use-marked-transactions-to-recover-related-databases-consistently?view=sql-server-ver15) page says nothing about any prerequisites to marked transactions, namely, the presence of any backup BEFORE issuing BEGIN TRANSACTIOn WITH MARK statement (the example on that page starts from 
"USE AdventureWorks  
GO  
BEGIN TRANSACTION ListPriceUpdate   ....  " and only after that the backup is taken. 

In my case the test database was in the Full recovery mode, but no backups were taken yet.

Futhermore, that same page says 

- A typical scenario for using marked transactions includes the following steps:

    Create a full or differential database backup of each of the related databases.

    Mark a transaction block in all the databases.

    Back up the transaction log for all the databases.

- if the "_Mark a transaction block in all the databases._" means a user can issue a marked transaction - after ONLY a full or  differential database backup was taken - then it did not work in my environment either: only after the LOG database backup was taken I was able to insert a row into the _logmarkhistory_ table.

Please excuse me once again!

Regards,
Michael Firsov

**Comment by WilliamAntonRohm** [comment]
@MichaelFirsov -- thank you for clarifying, and no problem!

**Comment by cawrites** [comment]
@MichaelFirsov Thank you for this additional information I appreciate you taking the additional time to add these insights.

**Comment by cawrites** [comment]
@MichaelFirsov I reviewed the document you mentioned and it clearly states to make a backup of the transaction log.  The reported page 

Typical Scenario for Using Marked Transactions
A typical scenario for using marked transactions includes the following steps:

Create a full or differential database backup of each of the related databases.

Mark a transaction block in all the databases.

**Back up the transaction log for all the databases.**

Restore database backups WITH NORECOVERY.

Restore logs WITH STOPATMARK.

**Comment by WilliamAntonRohm** [comment]
@cawrites -- Cheryl, thank you for that information.

**Comment by cawrites** [comment]
@please close
