### ISSUE TITLE
Wrong data folder mount point

### ISSUE THREAD

**Issue by rblackman** [MicrosoftDocs/sql-docs#6412]
> 3. To run the container image with Docker, you can use the following command:
> sudo docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=<YourStrong!Passw0rd>' \
   --name 'sql1' -p 1401:1433 \
   -v sql1data:/var/opt/mssql \
   -d mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04```

Using these instructions the container will fail to start. Mout point should be set to `/var/opt/mssql/data` not `/var/opt/mssql`. See: https://github.com/microsoft/mssql-docker/issues/603

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd398c1-ed8b-911b-f11a-3739d80b3f32
* Version Independent ID: dc3d55ff-3b55-a686-81f9-f4188054e381
* Content: [Restore a SQL Server database in Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-restore-backup-in-sql-server-container?view=sql-server-ver15)
* Content Source: [docs/linux/tutorial-restore-backup-in-sql-server-container.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-restore-backup-in-sql-server-container.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Thanks, @rblackman! We appreciate the feedback! If you are using Docker containers on Windows, this is noted: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-configure?view=sql-server-ver15&pivots=cs1-bash#mount-a-host-directory-as-data-volume

For clarity, I'll add a similar note to the referenced doc. Thanks!

@amvin87 - FYI
