### ISSUE TITLE
LoadWarehouse script - Step 3 :: Cannot insert the value NULL into column 'TargetCompatKey'

### ISSUE THREAD

**Issue by francesco1119** [MicrosoftDocs/sql-docs#6416]
I've used this script for a few times in the last 2 months but this is the first time I run into this issue. 

This morning I have used the DMA tool to assess 10 servers that contained 185 databases. The DMA tool returned quite a lot of data and for the first time I faced an error that I hadn't faced before: 

`Cannot insert the value NULL into column 'TargetCompatKey', table 'DMAWarehouse.dbo.FactAssessment'; column does not allow nulls. INSERT fails.`

So I edited the dbo.FactAssessment and allowed the column TargrtCompatKey to accept the NULL value and this sparked a lot of change in the tables: 

![image](https://user-images.githubusercontent.com/3397477/118676615-d7cad280-b7fb-11eb-8515-2f3ad49adeaa.png)

...but after this change everything was fine and the  Step 3 of the LoadWarehouse script was accepted. 

But now my TargetCompatKey has NULLs inot it: 

![image](https://user-images.githubusercontent.com/3397477/118677648-abfc1c80-b7fc-11eb-80de-2fd8f0d0497d.png)

And I'm not sure if this is good or bad but I have searched for the word "TargetCompatKey" in the LoadWarehouse script and that word is not mentioned anywhere apart from Step3.

This brings us to 2 possible scenarios: 
- Those NULLS where wrongly imported by the Azure Az PowerShell module [dmaProcessor](https://docs.microsoft.com/en-us/sql/dma/dma-consolidatereports?view=sql-server-ver15#consuming-the-assessment-json-file), in this case is BAD
- Those NULLS where wrongly generated by the DMA tool when saving the output JSON file, in this case is double BAD

**Comment by WilliamAntonRohm** [comment]
@francesco1119 -- Francesco, thank you again for your research and feedback.

@pochiraju -- Raj, please look into this issue.

- Related to #6415

**Comment by francesco1119** [comment]
I f***ing fixed it!

1. Go to this [link ](Assess an enterprise and consolidate assessment reports with DMA)and download the The LoadWarehouse script.
2. Right click on the dbo.FactAssessment table > Design, and add these 2 columns: 

<img width="297" alt="Column" src="https://user-images.githubusercontent.com/3397477/120511762-fbc90f00-c3ca-11eb-9725-db875d48d3b4.png">

3. into the script LoadWarehouse replace the "-- Step 3" part with this code:

```
-- Step 3 - Run select statement first to ensure no NULL keys (except dbowner which is expected to be null at this point).  
-- IMPORTANT - Once happy uncomment out the INSERT statement and run again
-- INSERT INTO DMAWarehouse..FactAssessment(DateKey, StatusKey, SourceCompatKey, TargetCompatKey, Categorykey, SeverityKey, ChangeCategorykey, RulesKey, AssessmentTargetKey, ObjectTypeKey, DBOwnerKey, InstanceName, DatabaseName, SizeMB, ImpactedObjectName, ImpactDetail, AssessmentName, AssessmentNumber, ServerVersion, ServerEdition)
INSERT INTO DMAWarehouse..FactAssessment (
	DateKey
	,StatusKey
	,SourceCompatKey
	,TargetCompatKey
	,Categorykey
	,SeverityKey
	,ChangeCategorykey
	,RulesKey
	,AssessmentTargetKey
	,ObjectTypeKey
	,DBOwnerKey
	,InstanceName
	,DatabaseName
	,SizeMB
	,ImpactedObjectName
	,ImpactDetail
	,AssessmentName
	,AssessmentNumber
	,ServerVersion
	,ServerEdition
	)
SELECT dd.DateKey AS "DateKey"
	,ds.StatusKey AS "StatusKey"
	,sc.SourceCompatKey AS "SourceCompatKey"
	,CASE 
		WHEN tc.TargetCompatKey IS NULL
			THEN '1'
		ELSE tc.TargetCompatKey
		END AS "TargetCompatKey"
	,dc.CategoryKey AS "CategoryKey"
	,dsev.SeverityKey AS "SeverityKey"
	,dcc.ChangeCategoryKey AS "ChangeCategoryKey"
	,dr.RulesKey AS "RulesKey"
	,AssessmentTargetKey AS "AssessmentTargetKey"
	,ot.ObjectTypeKey AS "ObjectTypeKey"
	,dbo.DBOwnerKey AS "DBOwnerKey"
	,dma_rd.InstanceName AS "InstanceName"
	,[Name] AS "DatabaseName"
	,SizeMB AS "SizeMB"
	,COALESCE(ImpactedObjectName, 'NA') AS "ImpactedObjectName"
	,COALESCE(ImpactDetail, 'NA') AS "ImpactDetail"
	,AssessmentName
	,AssessmentNumber
	,CASE 
		WHEN tc.TargetCompatibilityLevel IS NULL
			THEN 'N/A'
		ELSE tc.TargetCompatibilityLevel
		END AS "ServerVersion"
	,CASE 
		WHEN TargetSQLServerEdition IS NULL
			THEN 'N/A'
		ELSE TargetSQLServerEdition
		END AS "ServerEdition"
FROM DMAReporting..reportdata dma_rd
LEFT JOIN DMAWarehouse..dimDate dd ON CONVERT(CHAR(8), dma_rd.ImportDate, 112) = dd.[Date]
LEFT JOIN DMAWarehouse..dimStatus ds ON dma_rd.[Status] = ds.[Status]
LEFT JOIN DMAWarehouse..dimSourceCompatibility sc ON dma_rd.SourceCompatibilityLevel = sc.SourceCompatibilityLevel
LEFT JOIN DMAWarehouse..dimTargetCompatibility tc ON dma_rd.TargetCompatibilityLevel = tc.TargetCompatibilityLevel
LEFT JOIN DMAWarehouse..dimCategory dc ON dma_rd.Category = dc.Category
LEFT JOIN DMAWarehouse..dimSeverity dsev ON dma_rd.Severity = dsev.Severity
LEFT JOIN DMAWarehouse..dimRules dr ON dma_rd.RuleId = dr.RuleID
	AND dma_rd.title = dr.Title -- there is a ruleid being used for 2 different titles
LEFT JOIN DMAWarehouse..dimAssessmentTarget ast ON dma_rd.AssessmentTarget = ast.AssessmentTarget
LEFT JOIN DMAWarehouse..dimChangeCategory dcc ON dma_rd.ChangeCategory = dcc.ChangeCategory
LEFT JOIN DMAWarehouse..dimObjectType ot ON CASE 
		WHEN dma_rd.ImpactedObjectType IS NULL
			OR dma_rd.ImpactedObjectType = ''
			THEN 'NA'
		ELSE ImpactedObjectType
		END = ot.ObjectType
LEFT JOIN DMAWarehouse..dimDBOwner dbo ON dma_rd.InstanceName = dbo.InstanceName
	AND dma_rd.Name = dbo.DatabaseName
WHERE IsLoaded = 0
```

4. Now download the The DMA Reports Power BI template, and follow the instructions. If you now do right click on the database > Drillthrough > Remediation Plan you will see the complete assessment for the Power BI report
 
![image](https://user-images.githubusercontent.com/3397477/120512198-6a0dd180-c3cb-11eb-98c2-92107d813c8f.png)
