### ISSUE TITLE
CEIP Unsupported Wording

### ISSUE THREAD

**Issue by rob837428394** [MicrosoftDocs/sql-docs#6420]
The Remarks section states "Removing or disabling the SQL CEIP service is not supported", this may be true but it is misleading. People could interpret this as turning off collection/sending via "Error and Usage Report Settings" would invalid support (which it does not). 

Please update the wording so this is clear. Thank you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91f186d6-2a54-0489-0c30-a31a61e92ca0
* Version Independent ID: ffdfc7e9-27ee-d37c-9082-975be02b78c9
* Content: [Local audit usage and diagnostic data collection - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/usage-and-diagnostic-data-in-local-audit?view=sql-server-ver15)
* Content Source: [docs/sql-server/usage-and-diagnostic-data-in-local-audit.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/usage-and-diagnostic-data-in-local-audit.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@rob837428394 -- thank you for your feedback.

@MashaMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
Hi @rob837428394 - thanks for the submission - I see that the text says the following items can't be removed or disabled:

- CEIP service
- CEIP resources

The following statement says that you can turn off local audit.

What would you recommend we add to clarify what you can and can not do here? 

Looking for some suggestions while we discuss this. 

Thanks,
Mike

**Comment by VanMSFT** [comment]
Making the updates to clarify this based on the feedback here. Thanks @rob837428394 

#reassign:VanMSFT
