### ISSUE TITLE
Import does not work without creating the database first

### ISSUE THREAD

**Issue by lukos** [MicrosoftDocs/sql-docs#6423]
The lead text says that this will import into a new or empty database but certainly on Linux SQL Server 2019, this is not true. To make it worse, the error is misleading since it mentions that the server cannot be found even though it also mentions "Could not open database..."

Depending on whether this applies to all versions of SQL Server or maybe it works on Azure databases, the text should be clear that in some/all scenarios, the database must be created before you can import a bacpac.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f7954fa-99b7-be69-922b-4cadbcedcf2f
* Version Independent ID: a87d86dd-0354-ba30-eb0d-fbf3f4e0f8e5
* Content: [SqlPackage Import - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-import?view=sql-server-ver15)
* Content Source: [docs/tools/sqlpackage/sqlpackage-import.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage/sqlpackage-import.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@lukos -- Luke, thank you for your feedback.

@dzsquared -- Drew, please look into this issue.

**Comment by MikeRayMSFT** [comment]
@lukos -- Luke, I'm reviewing this with some internal folks and plan to reply shortly.

**Comment by dzsquared** [comment]
@lukos - the scenario in which the database must be created before the import is when the user credentials do not have permissions to create a database.  I will add this information to the docs.

**Comment by dzsquared** [comment]
@lukos - please let me know if you have any additional questions

#please-close

**Comment by lukos** [comment]
Sounds great. Thanks.
