### ISSUE TITLE
Storage unit labels - GB or GiB?

### ISSUE THREAD

**Issue by julienshepherd** [MicrosoftDocs/sql-docs#6424]
I see Windows displays storage values with the label GB when they are actually GiB. I don't know whether SQL Server displays GiB values labeled as GB. Are the labels in this doc page correct or should they be GiB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 453dc1e2-0c9c-fe95-c6fc-90be886432ad
* Version Independent ID: cd472bc0-26b9-a4a6-4089-31b79be787cb
* Content: [Editions and supported features - SQL Server 2017](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2017?view=sql-server-ver15)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-2017.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-2017.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@julienshepherd -- thank you for your question.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
The labels in that article should be GiB. #please-close
