### ISSUE TITLE
Applicability to SQLMI

### ISSUE THREAD

**Issue by akiohose** [MicrosoftDocs/sql-docs#6427]
This page doesn't seem to apply to SQL MI although it is listed in the "Applies to" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b357e7d-b0a5-8e5f-96eb-735ec9562c7d
* Version Independent ID: 0f2d3b33-ba65-01c9-1db7-b51c2611cf75
* Content: [Client Protocols - Named Pipes Properties (Protocol Tab) - SQL Server](https://docs.microsoft.com/en-us/sql/tools/configuration-manager/client-protocols-named-pipes-properties-protocol-tab?view=sql-server-ver15)
* Content Source: [docs/tools/configuration-manager/client-protocols-named-pipes-properties-protocol-tab.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/configuration-manager/client-protocols-named-pipes-properties-protocol-tab.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@akiohose -- thank you for bringing this to our attention.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review this update in [private PR 19407](https://github.com/MicrosoftDocs/sql-docs-pr/pull/19407).

**Comment by markingmyname** [comment]
Hi, @akiohose.

First, apologizes for the extremely delayed response.

Thank you for making us aware of this.

Updates should be live sometime next week.

thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
