### ISSUE TITLE
Incorrect syntax in example

### ISSUE THREAD

**Issue by amitmsft** [MicrosoftDocs/sql-docs#6433]
[Enter feedback here]
The word DISK is missing in the syntax. Or it could be changed to reflect backup device.

RESTORE DATABASE <database> PAGE='1:57, 1:202, 1:916, 1:1016'  
   FROM DISK = <file_backup_of_file_B>   
   WITH NORECOVERY;  
RESTORE LOG <database> FROM DISK = <log_backup>  
   WITH NORECOVERY;  
RESTORE LOG <database> FROM DISK = <log_backup>   
   WITH NORECOVERY;   
BACKUP LOG <database> TO DISK = <new_log_backup>;   
RESTORE LOG <database> FROM DISK = <new_log_backup> WITH RECOVERY;  
GO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a37f3d-af75-665b-7dac-b0089dd582b0
* Version Independent ID: 243e183a-1c3d-eda5-7681-6c2ede475997
* Content: [Restore Pages (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/restore-pages-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/backup-restore/restore-pages-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/restore-pages-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by cawrites** [comment]
@amitmsft thank you for reaching out. I hope you are doing well. I will take a look at your request and the update will appear in the next content refresh.

**Comment by cawrites** [comment]
https://github.com/MicrosoftDocs/sql-docs-pr/pull/19393
