### ISSUE TITLE
The topic for @@REMSERVER

### ISSUE THREAD

**Issue by sommarskog** [MicrosoftDocs/sql-docs#6434]
I had reason to view this topic to day due to a forum question. My understanding is that this function relates to functionality which has been discontinued ("remote servers"), and therefore this function always returns NULL. The topic could be updated to reflect this. The deprecation note would be retained, and the text could say "This function only exists for backward compatibility, but it always returns NULL."

**Comment by WilliamAntonRohm** [comment]
@sommarskog -- thank you for your feedback.  I believe this is the topic you're referencing:
- [@@REMSERVER (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/functions/remserver-transact-sql?view=sql-server-ver15)

@julieMSFT -- please look into this issue.

**Comment by julieMSFT** [comment]
@sommarskog Hi and thank your for contacting Microsoft. You are correct, the @@REMSERVER function only returns NULL. I have updated the article. You should see the update today or tomorrow. I will go ahead with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
