### ISSUE TITLE
[LOC]Fixed inappropriate japanese "SQL Server&2016; のインストール"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/sql-docs#6441]
ja-jp:"https://docs.microsoft.com/ja-jp/sql/database-engine/install-windows/install-sql-server?view=sql-server-ver15"
![install-sql-server_j](https://user-images.githubusercontent.com/40815708/119796001-f45dbd80-bf13-11eb-95ff-b40482ab6c2f.png)

en-us:"https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server?view=sql-server-ver15"
![install-sql-server_e](https://user-images.githubusercontent.com/40815708/119796026-f9bb0800-bf13-11eb-8996-d8daf1f06a70.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae75dfb-2017-17a3-835b-9409fdb06427
* Version Independent ID: 8f22b559-823e-d719-7c5d-f76f89345c01
* Content: [SQL Server installation guide - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/install-windows/install-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/install-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@hyoshioka0128 -- Hiroshi, thank you for bringing this to our attention.

@cawrites -- Cheryl, please look into this issue, and forward it to a localization person if needed.

**Comment by cawrites** [comment]
@WilliamAntonRohm I believe this will need to be forwarded. Do you have a contact alias?

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, please let us know who can help with this page.

**Comment by VanMSFT** [comment]
Forwarded to the localization team for feedback. Closing this issue as we will review internally.
