### ISSUE TITLE
apt-key is deprecated

### ISSUE THREAD

**Issue by JEvason90** [MicrosoftDocs/sql-docs#6446]
I'm following along with the guide and when I come to run the first wget command 

wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

The command completes with an error simply stating apt-key is deprecated.

I'm running Ubuntu 20.04 on a Raspberry Pi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
@amvin87 - Hey Amit, can you please help with this? It looks like we need to re-work the quickstart for `apt-key add`. Thanks!

#reassign:amvin87

**Comment by amvin87** [comment]
You cannot install SQL Server on ARM like (Raspberry Pi), if you want to install SQL Server on Raspberry pi, please run SQL edge which is supported on ARM. https://azure.microsoft.com/en-in/products/azure-sql/edge/#features

**Comment by VanMSFT** [comment]
As `apt-key add` still works for our supported platforms, I am closing this issue for now.
