### ISSUE TITLE
MD5 checksum next to SSMS download link

### ISSUE THREAD

**Issue by ekholve** [MicrosoftDocs/sql-docs#6452]
Hi there,

I would like to propose MD5 checksum to be added next to SQL Server Management Studio download link so that it can be easily verified before installation.

It is either very well hidden or not existing at all.

Thank you.

Vesa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@ekholve -- thank you for your feedback.  Please add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @dzsquared for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
