### ISSUE TITLE
Grammar for cursor declaration misses for read only

### ISSUE THREAD

**Issue by siggemannen** [MicrosoftDocs/sql-docs#6455]
The page (https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/declare-cursor-transact-sql.md) lists two ways of declaring a cursor, iso and tsql.

The below is a valid tsql syntax, but not according to documentation:

`
DECLARE CR_X CURSOR LOCAL
FOR SELECT 1
FOR READ ONLY
`

Note that this is mutually-exclusive to READ_ONLY option, ie. this is not a valid declaration:

`DECLARE CR_X CURSOR LOCAL READ_ONLY
FOR SELECT 1
FOR READ ONLY
`

**Comment by WilliamAntonRohm** [comment]
@siggemannen -- thank you for your feedback.

@cawrites -- please look into this issue.

**Comment by cawrites** [comment]
@siggemannen I am unclear on your question. Are you stating that there is inconsistent documentation? What is the other content you are referring to?

**Comment by cawrites** [comment]
@siggemannen I am unclear on your question. Are you stating that there is inconsistent documentation? What is the other content you are referring to?

**Comment by siggemannen** [comment]
Hi, sorry for being a bit vague. What i mean is that documentation doesn't match the syntax accepted by SQL Server, and should probably be corrected to match it.

I have a SQL-statement that goes like: "DECLARE CR_X CURSOR LOCAL FOR SELECT 1 FOR READ ONLY"
If i run it, it works.

But, the above declaration doesn't match the two possible cursor declarations on the cursor documentation page.

The ISO-syntax looks like:
"ISO Syntax  
DECLARE cursor_name [ INSENSITIVE ] [ SCROLL ] CURSOR   
     FOR select_statement   
     [ FOR { READ ONLY | UPDATE [ OF column_name [ ,...n ] ] } ]  
[;]  "

But since my statement contains "LOCAL", this doesn't match the ISO-syntax.

So, now i'm trying to match the TSQL Extended syntax:

DECLARE cursor_name CURSOR [ LOCAL | GLOBAL ]   
     [ FORWARD_ONLY | SCROLL ]   
     [ STATIC | KEYSET | DYNAMIC | FAST_FORWARD ]   
     [ READ_ONLY | SCROLL_LOCKS | OPTIMISTIC ]   
     [ TYPE_WARNING ]   
     FOR select_statement   
     [ FOR UPDATE [ OF column_name [ ,...n ] ] ]  
[;]  

But this syntax doesn't accept the "FOR READ ONLY" part of my declaration.

So, none of the options accepts the statement, so i assume one of them is incomplete.

**Comment by siggemannen** [comment]
Yeah, either "LOCAL" should be added to the iso cursor documentation as a available keyword, or FOR READ ONLY should be added to tsql extended syntax as allowed keywords. But since i don't know exact internals of cursors you guys probably do a better job of providing updated syntax.

The reason for my questions is that i'm doing sql parsing, and sometimes hit grammars that are accepted by the server but don't match the sql server documentation

**Comment by cawrites** [comment]
@siggemannen upon further review it appears that all the syntax options are shown here:ISO Syntax  
DECLARE cursor_name [ INSENSITIVE ] [ SCROLL ] CURSOR   
     FOR select_statement   
     [ FOR { READ ONLY | UPDATE [ OF column_name [ ,...n ] ] } ]  
[;]  
Transact-SQL Extended Syntax  
DECLARE cursor_name CURSOR [ LOCAL | GLOBAL ]   
     [ FORWARD_ONLY | SCROLL ]   
     [ STATIC | KEYSET | DYNAMIC | FAST_FORWARD ]   
     [ READ_ONLY | SCROLL_LOCKS | OPTIMISTIC ]   
     [ TYPE_WARNING ]   
     FOR select_statement   
     [ FOR UPDATE [ OF column_name [ ,...n ] ] ]  
[;]  
Although the examples don't show all the variations it is defined in the syntax as an option.

**Comment by cawrites** [comment]
Thank you for contacting Microsoft.
