### ISSUE TITLE
Typo in script

### ISSUE THREAD

**Issue by maw-mjohnson** [MicrosoftDocs/sql-docs#6461]
There appears to be an odd typo when reading this document. You can search the page for this phrase "highly availability" as  "high availability" is most likely what the author intended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8a49313-385a-3f77-5468-f6b5c631adcb
* Version Independent ID: 913fde38-b0c6-6abc-1a7f-69ae976a9c30
* Content: [Extensible Key Management using Azure Key Vault - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/extensible-key-management-using-azure-key-vault-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/extensible-key-management-using-azure-key-vault-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/extensible-key-management-using-azure-key-vault-sql-server.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@maw-mjohnson -- thank you for bringing this to our attention.  I am updating the article.

**Comment by maw-mjohnson** [comment]
I’m happy that I could help!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by WilliamAntonRohm** [comment]
I have updated the documentation and it should be live by tomorrow.
