### ISSUE TITLE
Strange wording on bullet point

### ISSUE THREAD

**Issue by KathiKellenberger** [MicrosoftDocs/sql-docs#6462]
On this bullet point in the reasons for an internal checkpoint: 
An instance of SQL Server is stopped by stopping the SQL Server (MSSQLSERVER) service . Either action causes a checkpoint in each database in the instance of SQL Server.

When you say "Either" it sounds like the previous sentence should mention two separate actions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bca058-bde3-c76a-793a-dc344751d853
* Version Independent ID: 1f682f41-3a2d-66d6-47f1-bd5c2b4ca873
* Content: [Database Checkpoints (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/logs/database-checkpoints-sql-server?view=sql-server-ver15#EventsCausingChkpt)
* Content Source: [docs/relational-databases/logs/database-checkpoints-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/logs/database-checkpoints-sql-server.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@KathiKellenberger -- thank you for your feedback.  I am looking into this article.
