### ISSUE TITLE
Please mention sql 2019 uses batch mode in rows as well in "batch mode execution" section

### ISSUE THREAD

**Issue by benoityip** [MicrosoftDocs/sql-docs#6465]
[Enter feedback here]
Please mention sql 2019 uses batch mode in rows as well in "batch mode execution" section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45a7c96a-9d41-83e8-0ae8-b73fff390f48
* Version Independent ID: 1a880308-6a3b-6944-6428-1331801b327a
* Content: [Query Processing Architecture Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/query-processing-architecture-guide?view=sql-server-ver15)
* Content Source: [docs/relational-databases/query-processing-architecture-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/query-processing-architecture-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by WilliamAntonRohm** [comment]
@benoityip -- thank you for your feedback.

@pmasl -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
Checking with PM/Eng

**Comment by pmasl** [comment]
Merged PR with required change. Thanks

**Comment by pmasl** [comment]
#please-close
