### ISSUE TITLE
[LOC] Reporting Services Properties - Report Server System Properties

### ISSUE THREAD

**Issue by Hyamyam** [MicrosoftDocs/sql-docs#6469]
URL: https://docs.microsoft.com/en-us/sql/reporting-services/report-server-web-service/net-framework/reporting-services-properties-report-server-system-properties?view=sql-server-ver15

[Request]
In the Japanese version, the numbers are written incorrectly (the commas are large and look like individual numbers).

// JP ver
![image](https://user-images.githubusercontent.com/73410575/121100431-cb52fc00-c834-11eb-90d3-988aefd59f50.png)

// English ver
![image](https://user-images.githubusercontent.com/73410575/121100377-aced0080-c834-11eb-9df1-02ca6333b5b0.png)

**Comment by WilliamAntonRohm** [comment]
@Hyamyam -- Hy, thank you for catching this.

@CeciAc -- Cecilia, please direct this issue to the localization team.

**Comment by VanMSFT** [comment]
Closing this. Needs to go through the localization team.
