### ISSUE TITLE
Define what is a trigger table before moving to inserted and deleted tables

### ISSUE THREAD

**Issue by OfirD1** [MicrosoftDocs/sql-docs#6476]
The page should also explain what is a "trigger table", as this terminology is used without context.

Such a definition is given in the [`CREATE TRIGGER`](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-trigger-transact-sql?view=sql-server-ver15) page:

> The table or view on which the DML trigger runs. This table or view is sometimes referred to as the trigger table or trigger view. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de204ead-2a80-46ec-6adc-3d8b13977602
* Version Independent ID: eb4f715f-eba6-5d39-b2ba-5baae1b58c71
* Content: [Use the inserted and deleted Tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/triggers/use-the-inserted-and-deleted-tables?view=sql-server-ver15)
* Content Source: [docs/relational-databases/triggers/use-the-inserted-and-deleted-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/triggers/use-the-inserted-and-deleted-tables.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@OfirD1 -- thank you for your suggestion.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
