### ISSUE TITLE
Documentation for PowerQuery in SSIS should provide a link to the download page

### ISSUE THREAD

**Issue by realolap** [MicrosoftDocs/sql-docs#6480]
There is as far as I can see no link from the [documentation ](https://docs.microsoft.com/en-us/sql/integration-services/data-flow/power-query-source?view=sql-server-ver15)page to the [download ](https://www.microsoft.com/en-us/download/details.aspx?id=100619)page, making it more difficult for the users to find.

**Comment by WilliamAntonRohm** [comment]
@realolap -- Ola, thank you for your feedback.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@realolap -- Ola, please see the Note below the first paragraph -- the download link is in the middle sentence.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
