### ISSUE TITLE
SqlPackage code samples and publish file naming rules

### ISSUE THREAD

**Issue by jasonhorner** [MicrosoftDocs/sql-docs#6483]
Would be great to add a code sample for both publish and export and also any rules around naming files for publish

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae753662-56c4-17c1-e6f5-f96682d273d7
* Version Independent ID: 88b53ab1-bc42-61ff-d852-f6188eb66c74
* Content: [SqlPackage for Azure Synapse Analytics - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-for-azure-synapse-analytics?view=sql-server-ver15)
* Content Source: [docs/tools/sqlpackage/sqlpackage-for-azure-synapse-analytics.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage/sqlpackage-for-azure-synapse-analytics.md)
* Product: **sql**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
thanks for raising this @jasonhorner - will add to the article

**Comment by dzsquared** [comment]
#assign:dzsquared

**Comment by rwestMSFT** [comment]
@dzsquared Is there any further action required here or can we close this issue?

**Comment by dzsquared** [comment]
no, do not close.  this issue raises a gap in the documentation around the naming rules for files used in publish via parquet that has not yet been completed

**Comment by rwestMSFT** [comment]
@jasonhorner We are closing this issue because we are tracking it internally.

You can also engage with the engineering team directly at https://github.com/microsoft/dacfx.

AB#203362
