### ISSUE TITLE
Article Schema changes (adding/dropping column) never requires quiescing.

### ISSUE THREAD

**Issue by babarlhr** [MicrosoftDocs/sql-docs#6489]
[Enter feedback here]

There are two different conflicting statement or statements require more in-depth explanation. below are the statements.

1) Article Schema changes (adding/dropping column) never requires quiescing.

2) Topology schema changes (adding or dropping an article) requires quiescing. For more information, see Administer a Peer-to-Peer Topology (Replication Transact-SQL Programming).

  Also, need an explanation regarding conflict resolution if some conflict arises. how can we resolve conflict through SQL Server Management Studio (SSMS) or any other means?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9aa196d-743a-3c5a-536b-74c2774dda48
* Version Independent ID: a6a3b31c-88ed-4734-817e-349d3df94f7f
* Content: [Peer-to-Peer Transactional Replication - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/transactional/peer-to-peer-transactional-replication?view=sql-server-ver15)
* Content Source: [docs/relational-databases/replication/transactional/peer-to-peer-transactional-replication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/transactional/peer-to-peer-transactional-replication.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by babarlhr** [comment]
Ok, I got it. there are two different things 
1) Article Schema changes
2) Topology schema changes

Please highlight these for newbies to easily understand and also with examples and require a more in-depth explanation.

**Comment by MashaMSFT** [comment]
Hi @babarlhr , thanks for contacting Microsoft and providing your feedback!  We explain an article schema change as adding or dropping a column in the article, whereas a topology change is changing the replication topology such as adding a new article to be replicated. Changes to a table will be replicated over and as such quiescing is not required, whereas changing the replication topology (topology schema) such as adding an article to be replicated, or dropping an article from the replication topology may require quiescing depending on the action.

Do you have suggestions for how we can make it more clear?

Thanks!
Masha from the SQL Docs team

**Comment by babarlhr** [comment]
Thank you for your reply. In my opinion, it can be more clearer if there is a table  showing, 
Table as
 1) requires quiescing,  2) Not requires quiescing.

 it will be easy to go through quickly and easily.

**Comment by MashaMSFT** [comment]
Hi @babarlhr , thanks again for contacting Microsoft and my apologies for the delay as we work through a large backlog of Issues. While your suggestion has merit, it is out of scope for a Git Issue engagement so we're going to start tracking it internally ([61462](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61462)) and address it as resourcing allows. I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
