### ISSUE TITLE
Wrong mount fstab

### ISSUE THREAD

**Issue by kariem2k** [MicrosoftDocs/sql-docs#6490]
UUID="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" /data1 xfs,rw,attr2,noatime 0 0

shouldn't it be?

UUID="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" /data1 xfs rw,attr2,noatime 0 0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc91cc25-7d13-a975-76ee-6d97bdcf9416
* Version Independent ID: ae8d2f7e-0c69-1269-a438-d6d36594dd27
* Content: [Performance best practices for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-performance-best-practices?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-performance-best-practices.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-performance-best-practices.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @tejasaks
* Microsoft Alias: **tejasaks**

**Comment by tejasaks** [comment]
@amvin87 , Can you please confirm and make the necessary change?

**Comment by tejasaks** [comment]
Fixed it. 
@WilliamAntonRohm , Can you please close it out?

**Comment by WilliamAntonRohm** [comment]
@tejasaks -- thank you, Tejas.

#please-close
