### ISSUE TITLE
Information on using SSIS and CDC as an alternate solution

### ISSUE THREAD

**Issue by karthikyella** [MicrosoftDocs/sql-docs#6492]
[Enter feedback here]

The page recommends using SSIS and CDC as an alternate solution. Is there any documentation on how to leverage SSIS and CDC to replicate changes to oracle? If there is, then it would be good to have the reference here.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0918cd8a-85fe-5106-6b7e-27fbe6c4ee00
* Version Independent ID: c7d665a0-f57f-518c-40ba-e70b5f81933c
* Content: [Non-SQL Server Subscribers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/non-sql/non-sql-server-subscribers?view=sql-server-ver15)
* Content Source: [docs/relational-databases/replication/non-sql/non-sql-server-subscribers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/non-sql/non-sql-server-subscribers.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@karthikyella -- Karthik, thank you for your feedback.  This topic may be useful to you:
- [How Change Data Capture Works in Integration Services](https://docs.microsoft.com/en-us/sql/integration-services/change-data-capture/change-data-capture-ssis?view=sql-server-ver15#how-change-data-capture-works-in-integration-services)

@MashaMSFT -- Masha, please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @karthikyella , thanks for contacting Microsoft and my apologies for the delay as we work through a large backlog of Issues. While your suggestion has merit, it is out of scope for a Git Issue engagement so we're going to start tracking it internally ([61464](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61464)) and address it as resourcing allows. I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
