### ISSUE TITLE
404 Debian10 !!!!!

### ISSUE THREAD

**Issue by svatos-jirka** [MicrosoftDocs/sql-docs#6495]
404 is response to https://packages.microsoft.com/debian/10/prod/pool/main/m/msodbcsql17/

please fix it!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36a1d7f-a410-b597-0eb7-98212934fb0e
* Version Independent ID: e706f2bd-e051-fcff-7c3d-2ef3d9f80e87
* Content: [Download ODBC Driver for SQL Server - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/download-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/download-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
This is an issue with the Microsoft Package Repository hosting Linux packages. It is not a documentation issue. The owners of the service are aware of and working on the issue. It should be resolved ASAP. In fact, the Debian 10 links started working for me in the last 10 minutes. They should start working for everyone else as replication to mirrors completes.

Regards,
David

#please-close
