### ISSUE TITLE
Debian mirror /prod/pool/ broken?

### ISSUE THREAD

**Issue by mhauserbkw** [MicrosoftDocs/sql-docs#6496]
I tried to install the driver in a Debian based docker image according to the instructions on this page.
Yesterday it worked. Today it doesn't work anymore. I didn't change anything.
Error message:

Failed to fetch https://packages.microsoft.com/debian/10/prod/pool/main/m/msodbcsql17/msodbcsql17_17.7.2.1-1_amd64.deb  404  Not Found [IP: 40.114.136.21 443]

Regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by dsuarez993** [comment]
Same issue here! :(

**Comment by pmooij** [comment]
I just reported an similar issue #6497

**Comment by ykursav** [comment]
I reported as well :) They all debian and ubuntu drivers are gone from server :) You are coming work trying to build docker image and not building anymore so much fun. 🤣

**Comment by pellejacobs** [comment]
It seems like most packages are back online.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
