### ISSUE TITLE
Install MSODBC with Ubuntu results in 404  Not Found

### ISSUE THREAD

**Issue by pmooij** [MicrosoftDocs/sql-docs#6497]
The installation of MSODBC as described on:
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#ubuntu17

is not working anymore, the path retrieved from the prod.list results in an `404  Not Found` error.
please fix this

**Input**
```bash
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

#Ubuntu 18.04
curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 --fix-missing
```

**Output**
```bash
Get:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [4,003 B]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:5 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [207 kB]
Hit:6 https://repos.azul.com/zulu/deb stable InRelease
Hit:7 http://security.ubuntu.com/ubuntu bionic-security InRelease
Fetched 286 kB in 1s (393 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  libcap2-bin libpam-cap
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  msodbcsql17
0 upgraded, 1 newly installed, 0 to remove and 52 not upgraded.
Need to get 745 kB of archives.
After this operation, 0 B of additional disk space will be used.
Err:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 msodbcsql17 amd64 17.7.2.1-1
  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/m/msodbcsql17/msodbcsql17_17.7.2.1-1_amd64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Internal Error, ordering was unable to handle the media swap
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#ubuntu17)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by dsuarez993** [comment]
same here :(

**Comment by daguito81** [comment]
+1

**Comment by saschaa442** [comment]
+1

**Comment by pmooij** [comment]
seems to be up and running again so closing this issue.
