### ISSUE TITLE
Drivers not found/removed

### ISSUE THREAD

**Issue by ykursav** [MicrosoftDocs/sql-docs#6498]
Hi,

There is some serious issue with where drivers located. It looks like all deleted and gone. Currently there is no possibility to install linux odbc mssql drivers. Please check and update the links.

Tested version: Ubuntu 20.04
https://packages.microsoft.com/ubuntu/20.04/

Below page also not working as they are using same urls: (Alpine works, Ubuntu and Debian not working at all any versions.)
https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
This was an infrastructure issue (not docs) that has been resolved. Please see: https://status.dev.azure.com/_event/246136621

Thanks,
David

#please-close
