### ISSUE TITLE
https://packages.microsoft.com 404 when installing msodbc

### ISSUE THREAD

**Issue by testfile2** [MicrosoftDocs/sql-docs#6499]
Linking https://github.com/MicrosoftDocs/windowsserverdocs/issues/5051

It seems as though someone broke the msodbc install for ubuntu yesterday. When installing the same way the docs say I get:

![image](https://user-images.githubusercontent.com/17514244/122364927-84fb4c80-cf5a-11eb-9047-3ec497ad437a.png)

Now as windowsserverdocs/issues/5051 states:

![image](https://user-images.githubusercontent.com/17514244/122365327-dc99b800-cf5a-11eb-83e6-8c25fb02d44f.png)

This is not a docs issue but rather a package management issue but it seems no one knows where to report package repo issues, other than here? I was directed here from https://docs.microsoft.com/en-us/answers/questions/440191/where-do-i-report-issues-for-httpspackagesmicrosof.html 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu17)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
This was an infrastructure issue (not docs) that has been resolved. Please see: https://status.dev.azure.com/_event/246136621

Note: It had quite a wide impact, internally and externally.

Regards,
David

#please-close
