### ISSUE TITLE
MSSQL Linux Packages not installing from Repository 404 Not Found

### ISSUE THREAD

**Issue by ChrisKayAyling** [MicrosoftDocs/sql-docs#6503]
Err:1 https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019 focal/main amd64 mssql-server amd64 15.0.4138.2-1
  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019/pool/main/m/mssql-server/mssql-server_15.0.4138.2-1_amd64.deb  404  Not Found [IP: 104.214.230.139 443]

Unable to install MSSQL Server as it appears the files are not present in the repo after following instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f0bcec3-7063-e556-e089-f6df587e2f03
* Version Independent ID: 801bc1d0-3453-9fba-2d82-d913ca90fdc8
* Content: [Installation guidance for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-setup.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by ChrisKayAyling** [comment]
Repo appears to be up but very slow.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
