### ISSUE TITLE
Microsoft ODBC driver on Debian 10 missing

### ISSUE THREAD

**Issue by diefenbachh** [MicrosoftDocs/sql-docs#6504]
Err:1 https://packages.microsoft.com/debian/10/prod buster/main amd64 libodbc1 amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:2 https://packages.microsoft.com/debian/10/prod buster/main amd64 odbcinst amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:3 https://packages.microsoft.com/debian/10/prod buster/main amd64 odbcinst1debian2 amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:4 https://packages.microsoft.com/debian/10/prod buster/main amd64 unixodbc amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:5 https://packages.microsoft.com/debian/10/prod buster/main amd64 msodbcsql17 amd64 17.7.2.1-1
  404  Not Found [IP: 104.214.230.139 443]
Err:6 https://packages.microsoft.com/debian/10/prod buster/main amd64 unixodbc-dev amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]

E: Failed to fetch https://packages.microsoft.com/debian/10/prod/pool/main/u/unixodbc/libodbc1_2.3.7_amd64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/debian/10/prod/pool/main/u/unixodbc/odbcinst_2.3.7_amd64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/debian/10/prod/pool/main/u/unixodbc/odbcinst1debian2_2.3.7_amd64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/debian/10/prod/pool/main/u/unixodbc/unixodbc_2.3.7_amd64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/debian/10/prod/pool/main/m/msodbcsql17/msodbcsql17_17.7.2.1-1_amd64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/debian/10/prod/pool/main/u/unixodbc/unixodbc-dev_2.3.7_amd64.deb  404  Not Found [IP: 104.214.230.139 443]

**Comment by dzsquared** [comment]
There is a temporary issue with some mirrors for packages.microsoft.com that should be resolved soon.  More information may be available sooner here: https://github.com/dotnet/core/issues/6381#issuecomment-863576167

#assign:dzsquared

**Comment by dzsquared** [comment]
#please-close
