### ISSUE TITLE
Debian Direct Download Links Dead

### ISSUE THREAD

**Issue by ffaen** [MicrosoftDocs/sql-docs#6505]
The debian direct download links on this page return a 404

![image](https://user-images.githubusercontent.com/3136033/122381471-e1616a80-cf60-11eb-9dde-772f6155554b.png)

![image](https://user-images.githubusercontent.com/3136033/122381490-e7574b80-cf60-11eb-9fc4-d11df9d9b2b9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36a1d7f-a410-b597-0eb7-98212934fb0e
* Version Independent ID: e706f2bd-e051-fcff-7c3d-2ef3d9f80e87
* Content: [Download ODBC Driver for SQL Server - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/download-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/download-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by remco-pc** [comment]
same here for ubuntu

**Comment by David-Engel** [comment]
This was an infrastructure issue (not docs) that has been resolved. Please see: https://status.dev.azure.com/_event/246136621

Regards,
David

#please-close
