### ISSUE TITLE
Window download link to downloading Linux version

### ISSUE THREAD

**Issue by PMLIO** [MicrosoftDocs/sql-docs#6518]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/en-gb/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/download-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download-azure-data-studio.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
cc @dzsquared for awareness

**Comment by dzsquared** [comment]
Thanks for the heads up! The correction will be in any minute now, but in the meantime all the download links are also available here: https://github.com/microsoft/azuredatastudio

In particular, the Windows system installer for June 2021 (1.30.0) is: https://go.microsoft.com/fwlink/?linkid=2165737

**Comment by dzsquared** [comment]
The tremendous @markingmyname knocked this out and it's all fixed now. :)

#assign:dzsquared
#please-close
