### ISSUE TITLE
Move TempDB

### ISSUE THREAD

**Issue by UTrackIT** [MicrosoftDocs/sql-docs#6522]
Information given is accurate and clear. Thank you.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9423e4-0573-7564-3f58-2a8df9a11d9f
* Version Independent ID: 5b88aa32-b6f7-e8eb-806f-fd331ed43133
* Content: [Move System Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/move-system-databases?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/move-system-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/move-system-databases.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@UTrackIT -- that is our aspiration :^)  You're very welcome!

cc @WilliamDAssafMSFT @rothja
