### ISSUE TITLE
default value for Remote Query Timeout is not 600 seconds

### ISSUE THREAD

**Issue by sunilgure** [MicrosoftDocs/sql-docs#6523]
Hi,
The value for "remote query timeout" is 0 by default and not 600 seconds. Can we correct this please.

Thanks,
Sunil Gure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e25fe07f-aad6-ad1d-8645-5a15b55c4a0a
* Version Independent ID: 3cf2c9b2-8a73-cea6-4da2-3677d5076725
* Content: [Configure the remote query timeout Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-remote-query-timeout-server-configuration-option?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-the-remote-query-timeout-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-remote-query-timeout-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@sunilgure -- Sunil, thank you for bringing this to our attention.  I am updating the article.

**Comment by sunilgure** [comment]
Thanks Willian.

**Comment by markingmyname** [comment]
change made

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
