### ISSUE TITLE
Out of date!

### ISSUE THREAD

**Issue by keithbarrow** [MicrosoftDocs/sql-docs#6525]
[Enter feedback here]

You really need to make it clear that SQL Configuration Manager is now a snap in for MMC and the easiest way is to now access it from Computer Management. Pity really, it was less to remember to type "SQL C.." to get prompted for the correct thing instead of hiding it inside something tangentially related. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b465c6c5-a14a-1190-ed27-3bf4b3b51fa5
* Version Independent ID: 5c375e20-d566-90fe-f19a-f3fc5fbc864a
* Content: [Create or Delete a Server Alias for Use by a Client - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/create-or-delete-a-server-alias-for-use-by-a-client?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/create-or-delete-a-server-alias-for-use-by-a-client.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/create-or-delete-a-server-alias-for-use-by-a-client.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@keithbarrow -- Keith, thank you for your feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@keithbarrow 

First, apologies for the extremely delayed response.

i believe the information you are looking for is [here](https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-configuration-manager).
