### ISSUE TITLE
Name of environment variable: SA_PASSWORD or MSSQL_SA_PASSWORD

### ISSUE THREAD

**Issue by draptik** [MicrosoftDocs/sql-docs#6527]
What is the name of the environment variable for setting the password in the docker container?

According to this page: `MSSQL_SA_PASSWORD`
According the all other docs: `SA_PASSWORD`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dc2ec36-4915-f7ab-3104-282acc9321e6
* Version Independent ID: fc98af17-f3c5-adff-69ca-593f985e7882
* Content: [Deploy and connect to SQL Server Docker containers - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-docker-container-deployment.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-docker-container-deployment.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@draptik -- Patrick, thank you for your question.  I am looking into this issue.

**Comment by WilliamAntonRohm** [comment]
@amvin87 -- please review this change in [private PR 19653](https://github.com/MicrosoftDocs/sql-docs-pr/pull/19653).

**Comment by amvin87** [comment]
My apologies for missing this. 

SA_PASSWORD is the old style way of passing the password, internally SA_PASSWORD simply get assigned to MSSQL_SA_PASSWORD. But to stay consistent we need to change the doc to ensure everywhere we use MSSQL_SA_PASSSWORD as the environment variable. 

@WilliamAntonRohm could you please help update the document and change the SA_PASSWORD environment variable to MSSQL_SA_PASSWORD.

**Comment by WilliamAntonRohm** [comment]
@amvin87 -- the current article file has 18 instances of this variable, all correctly named as MSSQL_SA_PASSWORD.  No edits to that article are needed.
