### ISSUE TITLE
Installing the ODBC driver for RHEL8 is not working

### ISSUE THREAD

**Issue by tephe** [MicrosoftDocs/sql-docs#6529]
Installing the ODBC driver for rhel 8 doesn't work as stated in the documentation. The issue is described in this stackoverflow post: https://stackoverflow.com/questions/63262668/rhel-8-container-mssql-odbc-driver-e2fsprogs

If you follow the steps there you get:
```
ACCEPT_EULA=Y yum install -y msodbcsql17
Problem: cannot install the best candidate for the job
 - nothing provides e2fsprogs needed by msodbcsql17-17.7.2.1-1.x86_64
```
`e2fsprogs` was removed in rhel8. The stackoverflow post says to install it without dependencies but that seems dangerous. What do you suggest in this case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@tephe -- Vasile, thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
@tephe You can install it without the e2fsprogs dependency. It should work fine. The package dependency will be removed in the next GA release of the Microsoft ODBC Driver 17 for SQL Server, targeting the last day of this month.

Regards,
David

**Comment by tephe** [comment]
Thank you for the answer! It's good to hear this will be fixed. Looking forward to the release. In the meantime we'll download the driver without `e2fsprogs`.
