### ISSUE TITLE
Not clear that External Tables are not supported on Azure SQL DB

### ISSUE THREAD

**Issue by BennyHarding** [MicrosoftDocs/sql-docs#6535]
Could this article explicitly state that although External Data Sources are supported on Azure SQL Database, External Tables are not?

Also, there is a section is visible for Azure SQL Database that states:
"The Database Engine doesn't verify the existence of the external data source when the object is created. To validate, create an external table using the external data source."
Can this be hidden for Azure SQL DB?

**Comment by WilliamAntonRohm** [comment]
@BennyHarding -- Ben, thank you for your feedback.  Are you referring to this article?
- [CREATE EXTERNAL DATA SOURCE (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql)

**Comment by BennyHarding** [comment]
Yep, that's the article.
Sorry for the delay, missed the first email reminder..

**Comment by WilliamAntonRohm** [comment]
@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Hi @BennyHarding, thanks for the feedback and for taking the time to create a GitHub Issue. Your feedback helps improve Microsoft Docs for everyone.

1. [CREATE EXTERNAL TABLE](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-table-transact-sql?view=azuresqldb-current&preserve-view=true&tabs=dedicated) is supported for Azure SQL DB, though not for all the same data sources. 
2. Re: the sentence "The Database Engine doesn't verify the existence of the external data source when the object is created. To validate, create an external table using the external data source." What part of that sentence doesn't make sense to you?

**Comment by BennyHarding** [comment]
Hi William. Looking over my original feedback item, I'm not actually sure why I quoted that section..
Let me start again.

A customer contacted our team saying they were unable to create an external table against a blob data source in Azure SQL DB. We advised them that this was not supported - they replied that they felt Docs was not clear on this.
Reviewing the below articles, I tend to agree.
1) https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-table-transact-sql?view=azuresqldb-current&preserve-view=true&tabs=dedicated
2) https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql?view=azuresqldb-current&tabs=dedicated#type---blob_storage--rdbms--shard_map_manager

Would it be possible to add a note at the beginning of the 'create external table' article for Azure SQL DB, something to the affect of 'Azure SQL DB supports creating external tables to RDMS and SHARD_MAP_MANAGER. It does not support external tables to BLOB data sources'?

**Comment by WilliamDAssafMSFT** [comment]
@BennyHarding Ah, that makes more sense. Let me confirm with the product team, this will be a good doc update. Standby.

**Comment by WilliamDAssafMSFT** [comment]
Will update this in referenced https://github.com/MicrosoftDocs/sql-docs-pr/pull/19756 after collaboration with product team. Thanks @BennyHarding for bringing this to attention.

**Comment by WilliamDAssafMSFT** [comment]
Thanks again @BennyHarding. This has been addressed in a doc update to create-external-table-transact-sql that is in flight.
