### ISSUE TITLE
Links to Codeplex on this page become invalid after July 1st 2021

### ISSUE THREAD

**Issue by bakintunde** [MicrosoftDocs/sql-docs#6536]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da9da73-e904-c21c-ff0d-aa3057203510
* Version Independent ID: 6d9e3116-96ac-16e5-e398-4a274df81578
* Content: [Remote Blob Store (RBS) (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/blob/remote-blob-store-rbs-sql-server?view=sql-server-ver15&viewFallbackFrom=azuresqldb-current)
* Content Source: [docs/relational-databases/blob/remote-blob-store-rbs-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/blob/remote-blob-store-rbs-sql-server.md)
* Product: **sql**
* Technology: **filestream**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@bakintunde -- Olubisi, thank you for your feedback!

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by MikeRayMSFT** [comment]
Broken links removed. At this time alternative code sample is not available.
