### ISSUE TITLE
Broken url link

### ISSUE THREAD

**Issue by Atrony** [MicrosoftDocs/sql-docs#6537]
Url link https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate shows 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa20275-e415-5531-3ef4-7472d859753b
* Version Independent ID: cc1346a6-9336-91ba-bcff-9fff79847c35
* Content: [Enable encrypted connections - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@Atrony -- Anton, thank you for bringing this to our attention.  I am updating the article.
