### ISSUE TITLE
Scalar UDF Inlining Restrictions

### ISSUE THREAD

**Issue by bwertman-rc** [MicrosoftDocs/sql-docs#6545]
The last three restrictions on scalar UDF inlining (added in [this commit](https://github.com/MicrosoftDocs/sql-docs/commit/9024004616f9234c51e922ba4c5fb42ba65a09e4)) read as inverted compared to the rest of the list - I think it should possibly say:

> The UDF does not reference encrypted columns .
> The UDF does not contain references to 'WITH XMLNAMESPACES' .
> The UDF-calling query does not contain references to Common Table Expressions (CTEs).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4e3344e-e4a8-4356-7036-729c77f6fbd1
* Version Independent ID: a57b3944-c108-081a-6308-a2fedec15de6
* Content: [Scalar UDF Inlining in Microsoft SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/scalar-udf-inlining?view=sql-server-ver15)
* Content Source: [docs/relational-databases/user-defined-functions/scalar-udf-inlining.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/user-defined-functions/scalar-udf-inlining.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @s-r-k
* Microsoft Alias: **karam**

**Comment by WilliamAntonRohm** [comment]
@bwertman-rc -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@s-r-k -- Karthik, please review this update in [private PR 19765](https://github.com/MicrosoftDocs/sql-docs-pr/pull/19765).
