### ISSUE TITLE
Default RHEL open file limit 

### ISSUE THREAD

**Issue by DamnItWindows** [MicrosoftDocs/sql-docs#6562]
[Enter feedback here]
The default open file limit for users on RHEL, is 1024. Which for a production server handling many connections, that number can be dangerously low. To prevent possibly running into that limit this best practices should include a recommendation of raising the limit.

Editing /etc/security/limits.d/99-mssql-server.conf with 
mssql hard nofile [number]
mssql soft nofile [number]

A restart of the mssql-service is required for the change to go into effect. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc91cc25-7d13-a975-76ee-6d97bdcf9416
* Version Independent ID: ae8d2f7e-0c69-1269-a438-d6d36594dd27
* Content: [Performance best practices for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-performance-best-practices?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-performance-best-practices.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-performance-best-practices.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @tejasaks
* Microsoft Alias: **tejasaks**

**Comment by WilliamAntonRohm** [comment]
@DamnItWindows -- thank you for your suggestion.

@tejasaks -- please look into this issue.

**Comment by tejasaks** [comment]
@tfevriermsft to help review the recommendation. As far as I recall, open file limit is important for some other factors but not relevant to the open connections. We haven't seen issue with this, at least for the customers which already use the best practices defined for SQL Server on Linux servers (https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-performance-best-practices?view=sql-server-ver15). @tfevriermsft may be able to provide additional insight into this. 

@amvin87 to help with the doc.

**Comment by DamnItWindows** [comment]
lsof -u mssql 

You'll see connections in there. Thanks!

**Comment by VanMSFT** [comment]
@amvin87 - Hey Amit, can you please help follow-up on this recommendation?

**Comment by amvin87** [comment]
ack. let me take a look at this and confirm,

**Comment by VanMSFT** [comment]
adding recommendations from the Product Team
