### ISSUE TITLE
Adding new steps at T-SQL scripts

### ISSUE THREAD

**Issue by d4shm1r** [MicrosoftDocs/sql-docs#6564]
At [insert and query](https://docs.microsoft.com/en-us/sql/tools/visual-studio-code/sql-server-develop-use-vscode?view=sql-server-ver15#insert-and-query) part it could be easier to add before the given code with those two steps recommended.

1. In the SQL file,  type _sql_ to display a list of editable code snippets.
2. Select **sqlInsertRows**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85ee3f3-9c1b-f58f-57e7-47b3ac56014d
* Version Independent ID: 563123f2-41a3-ef47-ce0a-75ca0373da08
* Content: [Use the Visual Studio Code mssql extension - SQL Server](https://docs.microsoft.com/en-us/sql/tools/visual-studio-code/sql-server-develop-use-vscode?view=sql-server-ver15)
* Content Source: [docs/tools/visual-studio-code/sql-server-develop-use-vscode.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/visual-studio-code/sql-server-develop-use-vscode.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@d4shm1r -- Dashmir, thank you for your suggestion.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@d4shm1r 

Thank you for your suggestion.

Also, did you know: For minor edits, you can edit the doc! Click the little Edit pencil icon in the article, click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer.
Then all the writer has to do is sign off, and it goes into the publishing queue.

However, at this time, we regretfully will not add this suggestion.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
