### ISSUE TITLE
Can't download english version

### ISSUE THREAD

**Issue by Alvaromp** [MicrosoftDocs/sql-docs#6565]
I'm trying to download the US English version of SQL Server Management Studio, but it aways downloads the PTB version, even if I click on US English Version link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@Alvaromp -- thank you for your feedback.  Please try this URL that includes the language specifier "en-us" and let me know if it works for you:
- https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15

**Comment by markingmyname** [comment]
Hi, Alvaromp.

Apologizes for the long delay in responding.

We have tried to reproduce your issue and are unable to do so.

We will do our best to investigate this further if possible.

Also, may I ask if you have tried different browsers when downloading the versions?

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
