### ISSUE TITLE
No download extension available when proxy is enabled

### ISSUE THREAD

**Issue by datalexs** [MicrosoftDocs/sql-docs#6566]
Hello,

Downloading extension doesn't work when the browser is behind a proxy (zscaler is configured on my laptop).
  
I receive the error "unable to open "extensions SQL Server Profiler":  XHR has failed
![image](https://user-images.githubusercontent.com/57521065/124377582-e0447300-dcac-11eb-8981-1c3af6921240.png)

When I try manually, I have the following error:
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:d531df1b-801e-0074-17a9-706b44000000 Time:2021-07-04T07:49:25.8552026Z</Message>
</Error>

Issue is with Chrome 91.0.4472.124  or Edge Version 91.0.864.59
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12bf49db-fd24-7f4d-6792-6825f4e08faa
* Version Independent ID: 5f524d58-816a-812f-e43f-1916f1b4f199
* Content: [Add extensions - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/add-extensions?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/extensions/add-extensions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/extensions/add-extensions.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by dzsquared** [comment]
@datalexs are you downloading the extension VSIX from a docs page, the GitHub repository list of extensions, or from within Azure Data Studio?  If it isn’t directly from the docs page you will need to open an issue on the Azure Data Studio repository (https://github.com/microsoft/azuredatastudio)

**Comment by dzsquared** [comment]
Based on the screenshot, this is an issue that should be opened in the Azure Data Studio repo (https://github.com/microsoft/azuredatastudio)
#please-close
