### ISSUE TITLE
ethtool misspelling

### ISSUE THREAD

**Issue by robertnsu** [MicrosoftDocs/sql-docs#6567]
The bash script in _Network settings recommendations_ section under part 3:

```bash
echtool -C eth0 adaptive-rx on
echtool -C eth0 adaptive-tx on
```

should be:

```bash
ethtool -C eth0 adaptive-rx on
ethtool -C eth0 adaptive-tx on
```

Created PR https://github.com/MicrosoftDocs/sql-docs/pull/6568

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc91cc25-7d13-a975-76ee-6d97bdcf9416
* Version Independent ID: ae8d2f7e-0c69-1269-a438-d6d36594dd27
* Content: [Performance best practices for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-performance-best-practices?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-performance-best-practices.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-performance-best-practices.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @tejasaks
* Microsoft Alias: **tejasaks**

**Comment by robertnsu** [comment]
https://github.com/MicrosoftDocs/sql-docs/pull/6568

**Comment by tejasaks** [comment]
@amvin87 , Can you take a look at this and fix it?

**Comment by amvin87** [comment]
thank you @robertnsu. Have fixed the typos and the document should get updated in about 24 hours. Appreciate your feedback and time on this.

**Comment by VanMSFT** [comment]
fixed in https://github.com/MicrosoftDocs/sql-docs-pr/pull/19704. Closing this.
