### ISSUE TITLE
Python Tutorial: Deploy a linear regression model with SQL machine learning

### ISSUE THREAD

**Issue by bcrivercity54** [MicrosoftDocs/sql-docs#6571]
[Enter feedback here]
This tutorial specifies to create a Python notebook in Azure Data Studio. Not everyone has access to Azure, and since ML services are additions to local SQL Server it would be nice to have it noted that the option to use SSMS is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6126902-bcdc-3d8e-5977-ed58b8bf00f1
* Version Independent ID: 9dc69621-c9ce-840a-1dac-5da135f50515
* Content: [Python tutorial: Prepare data - SQL machine learning](https://docs.microsoft.com/en-us/sql/machine-learning/tutorials/python-ski-rental-linear-regression-prepare-data?view=sql-server-ver15)
* Content Source: [docs/machine-learning/tutorials/python-ski-rental-linear-regression-prepare-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/tutorials/python-ski-rental-linear-regression-prepare-data.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@bcrivercity54 Azure Data Studio also works with on-prem (local) SQL Server. You can also use SSMS for the T-SQL part of the tutorial, if you prefer, but for the Python part you need a notebook such as the one built-in to Azure Data Studio or a local Jupyter notebook.

**Comment by bcrivercity54** [comment]
Thank you!
       Brian T. Collins ***@***.***
 

    On Tuesday, July 6, 2021, 10:58:38 AM CDT, dphansen ***@***.***> wrote:  
 
 


Closed #6571.
