### ISSUE TITLE
AAD MFA break brought forward?

### ISSUE THREAD

**Issue by nickbeagley** [MicrosoftDocs/sql-docs#6572]
There is currently a Note in the documentation on this page about Azure Active Directory authentication with MFA breaking on < v18.6 from December 2021. Can you confirm that behaviour change has not been brought forward to July 2021 as I'm seeing issues with MFA on 18.4 as of this week?  I'm seeing it widespread across 18.4 installations but it's not not present on machines running 18.7.

The error we receive after entering pw in the "Sign in to your account" window and authorising the MFA request when connecting to Azure Analysis Services with Azure AD with MFA authentication:

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'cf710c6e-dfcc-4fa8-a093-d47294e44c66'.

The error does not occur when connecting to Azure SQL Databases.

Thanks

edit: re-included client id guid in error message

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by shueybubbles** [comment]
@nickbeagley the guid won't be  specific to you, it's the client id SSMS is using to authenticate with AAD.

**Comment by dzsquared** [comment]
#assign:dzsquared

**Comment by dzsquared** [comment]
#assign:dzsquared

**Comment by dzsquared** [comment]
@nickbeagley - the note is relative to the Azure SQL connections with AAD+MFA, I'm checking with the Azure Analysis Services group for any more information on their AAD+MFA connectivity.
Unfortunately, with SSMS 18.4 being out of support for over a year now, a fix in that version is unlikely.

**Comment by nickbeagley** [comment]
> Unfortunately, with SSMS 18.4 being out of support for over a year now, a fix in that version is unlikely.

Not after a fix, that's already clear -> upgrade to 18.9.1, just after confirmation of the cause of the problem that started this week. In trying to diagnose the issue we saw the Note on this documentation which seemed very related despite it not being Dec 2021 yet.

**Comment by dzsquared** [comment]
I've gotten confirmation that the current minimum requirement for the SSMS connectivity to Azure Analysis Services with AAD+MFA is 18.5.1.  Will adjust the note to make this clear, should go out within the day.

thanks!

**Comment by dzsquared** [comment]
#please-close
