### ISSUE TITLE
Applies to doesn't mention Azure SQL database and Azure SQL Managed Instance

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/sql-docs#6573]
Hi team,
 
The 'Applies to' of this article doesn't mention Azure SQL database and Azure SQL Managed Instance although setting OPTIMIZE_FOR_AD_HOC_WORKLOADS is available and can be enabled or disabled on them. 
See also the 'Applies to' of https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql?view=sql-server-ver15 where they're included. If applicable, Azure SQL database and Azure SQL Managed Instance are mentioned separately in other docs.  
 
Please review if the 'Applies to' is eligible for improvement.
  
Thank you and kind regards,
Inge van der Zouw-Beumer
#MSFTadvocate 
 
![Applies to](https://user-images.githubusercontent.com/40343254/124580744-baf06a00-de50-11eb-984a-592752cf234e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c10ea3a3-427f-c8ce-f3c0-c85b8d72c821
* Version Independent ID: 191aa689-fd15-6a0a-cb07-7e33a3c5a6a5
* Content: [optimize for ad hoc workloads Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/optimize-for-ad-hoc-workloads-server-configuration-option?view=sql-server-ver15&viewFallbackFrom=azuresqldb-current&source=docs#feedback)
* Content Source: [docs/database-engine/configure-windows/optimize-for-ad-hoc-workloads-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/optimize-for-ad-hoc-workloads-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by ingebeumer** [comment]
PS. The 'Applies to' of https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql?view=sql-server-ver15 doesn't include Azure SQL Managed Instance although MI is mentioned later in the document. See screenshot in original post. If applicable, Azure SQL Managed Instance is mentioned separately in other docs.

Please also review if the 'Applies to' of https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql?view=sql-server-ver15 is also eligible for improvement. This document doesn't seem to have a feedback button.
Thx.

**Comment by WilliamAntonRohm** [comment]
@ingebeumer -- Inge, thank you for your well-researched feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@ingebeumer 

Thank you for your suggestion.

the article will be updated later this week.

thank you for your contribution.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by ingebeumer** [comment]
Thank you @markingmyname 
Can you please check the article in my comment as well? It's missing Azure SQL Managed Instance in the Applies to section.
https://github.com/MicrosoftDocs/sql-docs/issues/6573#issuecomment-874628310
