### ISSUE TITLE
404 error when trying to download mssql.

### ISSUE THREAD

**Issue by Ben-Garcia-Data** [MicrosoftDocs/sql-docs#6576]
Hey there,

I'm following the instructions from: https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15

I'm using a 2GB Raspberry Pi 4B, running Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1028-raspi aarch64). I am accessing the server via ssh connection over the internet, using a Windows CMD line.

I run: `wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -`
This outputs `OK`

I then run: `sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list)"`

This outputs:
`E: Malformed line 1 in source list /etc/apt/sources.list.d/mssql-server.list (type)
E: The list of sources could not be read.`

From what I can understand, https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list is giving a 404 error.

When I run `nano /etc/apt/sources.list.d/mssql-server.list`

I see:

```
GNU nano 4.8                          /etc/apt/sources.list.d/mssql-server.list                                    <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by dzsquared** [comment]
The issue likely stems from the ARM processor on the Raspberry Pi 4, there isn't an ARM image available for SQL Server on Linux at this moment.

However - there is an Azure SQL Edge container that runs on ARM and will likely support your IOT scenario. - https://docs.microsoft.com/en-us/azure/azure-sql-edge/disconnected-deployment

**Comment by Ben-Garcia-Data** [comment]
Hmmm. Had a go with that alternative, which requires Docker. Run into this whilst trying to install Docker which might be related:

`sudo apt-get install docker-ce docker-ce-cli containerd.io`
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'moby-containerd' instead of 'containerd.io'
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  moby-engine moby-cli moby-engine:armhf moby-cli:armhf moby-engine:amd64 moby-cli:amd64 docker-ce-cli:amd64


E: Package 'docker-ce' has no installation candidate
E: Unable to locate package docker-ce-cli ```

Do I need to install moby-engine instead? This is my first time setting up a Ubuntu server, so it's very possible I've done something wrong.

A similar issue I've found, [https://github.com/MicrosoftDocs/azure-docs/issues/14254](url) I think I'll try and follow their solution of using Azure SQL Edge.

**Comment by dzsquared** [comment]
I don't have an RPI handy at the moment, but have a few troubleshooting ideas:

- You may need to add the repository for docker-ce before running apt-get: https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository
- alternatively, you can try their install script: https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script
- lastly, moby-engine and moby-cli are the underlying projects to docker and are preferred in some examples (https://dbafromthecold.com/2020/04/22/running-azure-sql-edge-on-a-raspberry-pi/)

**Comment by Ben-Garcia-Data** [comment]
I had a few issues trying to get Docker to work, as well as a few dependancies.

The simple solution I used in the end was to use mysql-server, following instructions from here: [Guide](https://linuxize.com/post/how-to-install-mysql-on-ubuntu-18-04/). It just worked. (Even tho I'm using ubuntu 20.04)
