### ISSUE TITLE
how do i revert back to previous state

### ISSUE THREAD

**Issue by minoseah629** [MicrosoftDocs/sql-docs#6577]
I saw this page: https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/tutorial-table-space-sql-server.md

I tried the widget out, but when I removed the setting from json from dashboard.database.widget.  I can no longer see the tables in my database and have a search

**Comment by WilliamAntonRohm** [comment]
@minoseah629 -- thank you for your feedback.  Just to be sure, please double-check the curly braces and commas in the last-edited widget file.  Let me know if this helps.

**Comment by minoseah629** [comment]
I figured it out.
