### ISSUE TITLE
No Data Types page?

### ISSUE THREAD

**Issue by m60freeman** [MicrosoftDocs/sql-docs#6579]
I am unable to find a modern equivalent to this very old deprecated page titled "Data Types": https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms187752(v=sql.105). The "Recommended Version" link at the top simply goes to the top page for SQL, and from there I see no obvious link to a more modern version of the Data Types page.

Where should I refer people to learn about the data types available for parameters, variables, and columns in SQL Server 2019 / Azure SQL Database and their storage requirements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 625776df-6886-3b5a-faa6-a9b07d4b729e
* Version Independent ID: 92c99567-c62f-b1e3-d2eb-dc0b99d372c1
* Content: [Tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/tables?view=sql-server-ver15&source=docs)
* Content Source: [docs/relational-databases/tables/tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/tables.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
@m60freeman Take a look at https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql
