### ISSUE TITLE
srv_getbindtoken typo

### ISSUE THREAD

**Issue by maharmstone** [MicrosoftDocs/sql-docs#6584]
Typo on this page - `svr_getbindtoken` should read `srv_getbindtoken`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c039715b-3167-027e-9510-8f71648a2f4c
* Version Independent ID: 28fa6e33-8256-1573-ea7d-04df7050eadd
* Content: [srv_getbindtoken (Extended Stored Procedure API) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/extended-stored-procedures-reference/srv-getbindtoken-extended-stored-procedure-api?view=sql-server-ver15)
* Content Source: [docs/relational-databases/extended-stored-procedures-reference/srv-getbindtoken-extended-stored-procedure-api.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/extended-stored-procedures-reference/srv-getbindtoken-extended-stored-procedure-api.md)
* Product: **sql**
* Technology: **stored-procedures**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@maharmstone -- thank you for bringing this to our attention.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
