### ISSUE TITLE
SQL Server Agent not an available option

### ISSUE THREAD

**Issue by JamesEarle** [MicrosoftDocs/sql-docs#6588]
It seems the last time this document was updated is 2017 and I suspect a lot has changed since then. There is no way to create a job for a SQL Server Agent using SSMS as there is no "SQL Server Agent" option in the Object Explorer when a new connection is created. This should be updated or removed if it's no longer valid. Is there an alternate way to do this through SSMS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16918c21-a4c9-3c41-10c1-84bb352f9f53
* Version Independent ID: 8b808763-695e-f8a3-b34f-9f1d196803ec
* Content: [Create a Job - SQL Server Agent](https://docs.microsoft.com/en-us/sql/ssms/agent/create-a-job?view=sql-server-ver15#SSMSProcedure)
* Content Source: [docs/ssms/agent/create-a-job.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/create-a-job.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by dzsquared** [comment]
@jamesearle - confirming that you have connected to SSMS with a supported instance (SQL Server, Azure Managed Instance)

**Comment by JamesEarle** [comment]
I see that a managed instance is a requirement I think, which I am not using so my mistake.
