### ISSUE TITLE
Clarification about what's the ImagePullPolicy used by the upgrade process when an offline deployment was used

### ISSUE THREAD

**Issue by lcanastreiro** [MicrosoftDocs/sql-docs#6590]
Hello all,

On the initial deployment of SQL BDC, in config.json it's possible to define the imagePullPolicy and implement an "offline" deployment strategy. In terms of the upgrade of the SQL BDC it's important to clarify which imagePullPolicy it's going to be used because it's possible to redefine the tag and repository values, using azdata bdc upgrade but we don't have a way to influence the imagePullPolicy used by the azdata bdc upgrade command.

Thanks,
Luís.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8fc75e5-8fba-36bb-9339-c2887150cae1
* Version Independent ID: 8b46f98f-1a38-a5e7-025f-49ae7570d389
* Content: [Upgrade to a new release - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-upgrade?view=sql-server-ver15&source=docs)
* Content Source: [docs/big-data-cluster/deployment-upgrade.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deployment-upgrade.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@lcanastreiro -- Luís, thank you again for your considered feedback.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
#reassign:williamdassafMSFT

**Comment by WilliamDAssafMSFT** [comment]
#assign:DaniBunny 
Thanks @lcanastreiro for contacting Microsoft with feedback about our product documentation. This pair of requests has been passed to the product team and we are in progress getting answers here. We'll contact you if we need further information or have questions, and you'll receive an email message each time we "@mention" you in a comment. 
	
Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @lcanastreiro for contacting Microsoft with feedback about our product documentation. We have a doc update in flight to address the desired imagePullPolicy setting and upgrade implications. Thanks again for the taking the time to make create these 2 issues, your suggestions help improve our documentation.
