### ISSUE TITLE
A note about the ImagePullPolicy Setting and which values could be specified would be important to add

### ISSUE THREAD

**Issue by lcanastreiro** [MicrosoftDocs/sql-docs#6591]
Hello all,

There isn't any information about the setting imagePullPolicy and which values can be used. With special attention when an offline deployment of SQL BDC is being done. In this specific case, could make sense to use the value IfNotPresent - https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images to avoid the need to download the SQL BDC images and with this accelerate all the process.

Thanks,
Luís.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19e2a7b-c117-a829-8fa1-8169eebf07ea
* Version Independent ID: 09c0053c-7966-9be0-2aec-09155189c482
* Content: [Deploy offline - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-offline?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/deploy-offline.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-offline.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @mihaelablendea
* Microsoft Alias: **mihaelab**

**Comment by WilliamAntonRohm** [comment]
@lcanastreiro -- Luís, thank you for your clear feedback.

@mihaelablendea -- Mihaela, please look into this issue.

Related to issue #6590.

**Comment by WilliamDAssafMSFT** [comment]
#reassign:williamdassafMSFT

**Comment by WilliamDAssafMSFT** [comment]
#assign:DaniBunny 
Thanks @lcanastreiro for contacting Microsoft with feedback about our product documentation. This pair of requests has been passed to the product team and we are in progress getting answers here. We'll contact you if we need further information or have questions, and you'll receive an email message each time we "@mention" you in a comment. 
	
Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @lcanastreiro for contacting Microsoft with feedback about our product documentation. We have a doc update in flight to address the desired imagePullPolicy setting and upgrade implications. Thanks again for the taking the time to make create these 2 issues, your suggestions help improve our documentation.
