### ISSUE TITLE
ALTER db collate for azure sql db

### ISSUE THREAD

**Issue by minsikmsft** [MicrosoftDocs/sql-docs#6593]
Hi,

I noticed that the document says the alter db collate is not supported in azure sql db, however, I am able to perform the statement. So, I was wondering if this is out-dated information. could you please let me know if the statement is still correct? I actually work at Microsoft, so feel free to reach out to me alias @minsikcho

Thank youy.

this is what I see from the doc.

**Important

ALTER DATABASE COLLATE statement on Azure SQL Database is not supported.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 683853cb-ea06-2b91-7606-6a313408e335
* Version Independent ID: 3f630abf-7950-5698-990e-331290ebb521
* Content: [Set or Change the Database Collation - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-database-collation?view=sql-server-ver15)
* Content Source: [docs/relational-databases/collations/set-or-change-the-database-collation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/set-or-change-the-database-collation.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@minsikmsft -- thank you for your question.

@WilliamDAssafMSFT -- please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
@minsikmsft Thanks for the feedback and taking the time to create the issue.
Can you be more specific as to the Azure SQL product you're using and a script that manages to change the collation of an Azure SQL DB? That is you can actually see the collation change in `sys.databases`?

**Comment by minsikmsft** [comment]
I am referring to Azure SQL DB. I have attached a picture which should show the scripts and the result of updated collation. Please let me know if you need anything.

**Comment by WilliamDAssafMSFT** [comment]
Discussed with @minsikmsft. Changing the collation requires exclusive access to the database, which isn't provided by Azure SQL DB. You should get something like this on a database where telemetry and other background services maintain connections:

Msg 42008, Level 16, State 5, Line 3
ODBC error: State: 42000: Error: 5030 Message:'[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The database b5722cce-3533-4bb6-8fa2-d911231635fc could not be exclusively locked to perform the operation.'.
Msg 5069, Level 16, State 3, Line 3
ALTER DATABASE statement failed.

Closing this as it is not a docs issue.
