### ISSUE TITLE
Broken Link - Please update or remove

### ISSUE THREAD

**Issue by ScottStauffer** [MicrosoftDocs/sql-docs#6597]
[Enter feedback here]
"Learn how to test updates: Testing and Developing Supportability Roadmaps for ISV Applications (PDF)"
BAD URL: https://msdnshared.blob.core.windows.net/media/TNBlogsFS/prod.evol.blogs.technet.com/CommunityServer.Blogs.Components.WeblogFiles/00/00/00/85/48/Files/0827.Testing%20And%20Developing%20Supportability%20Roadmaps%20for%20ISV%20Applications.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1353d4d-3899-d6cf-e44f-8536c7828335
* Version Independent ID: de0210cf-386a-f8c8-1157-40cea207ed4b
* Content: [Latest updates for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/latest-updates-for-microsoft-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/install-windows/latest-updates-for-microsoft-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/latest-updates-for-microsoft-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @SrinivasSQLMS
* Microsoft Alias: **skandi**

**Comment by WilliamAntonRohm** [comment]
@ScottStauffer -- Scott, thank you for bringing this to our attention.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@SrinivasSQLMS -- please review this excision in [private PR 19788](https://github.com/MicrosoftDocs/sql-docs-pr/pull/19788).

**Comment by SrinivasSQLMS** [comment]
@Mike Ray ***@***.***>, could you pls review this PR

**Comment by SrinivasSQLMS** [comment]
Hi @Mike Ray ***@***.***>, bring this to the top of your inbox

From: Srinivas Kandibanda ***@***.***>
Sent: Tuesday, July 20, 2021 7:04 PM
To: MicrosoftDocs/sql-docs ***@***.***>; MicrosoftDocs/sql-docs ***@***.***>; Mike Ray (SQL) ***@***.***>
Cc: Mention ***@***.***>; Azure Data SQL Release Team ***@***.***>
Subject: RE: [MicrosoftDocs/sql-docs] Broken Link - Please update or remove (#6597)

@Mike Ray ***@***.***>, could you pls review this PR

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
