### ISSUE TITLE
Link under Next Steps points to wrong document 

### ISSUE THREAD

**Issue by pabeilke** [MicrosoftDocs/sql-docs#6605]
The link at the bottom of the page under "Next Steps" captioned "Install new Python packages with sqlmlutils" points to the "install additional R packages on SQL Server" page. (https://docs.microsoft.com/en-us/sql/machine-learning/package-management/install-additional-r-packages-on-sql-server?view=sql-server-ver15) It should point to "Install Python packages with sqlmlutils" (https://docs.microsoft.com/en-us/sql/machine-learning/package-management/install-additional-python-packages-on-sql-server?view=sql-server-ver15)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6294b36-44e3-eea4-4e03-8260ae01fe08
* Version Independent ID: c88e5502-c0b1-56aa-a32e-f1e17192cd17
* Content: [Get Python package information - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/package-management/python-package-information?view=sql-server-ver15)
* Content Source: [docs/machine-learning/package-management/python-package-information.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/package-management/python-package-information.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by WilliamAntonRohm** [comment]
@pabeilke -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
