### ISSUE TITLE
Some confusion out there on where this are at with this feature - depricated, replace, dead on the vine? 

### ISSUE THREAD

**Issue by ScottStauffer** [MicrosoftDocs/sql-docs#6606]
not supported in SSMS 18.x?
supported in SSMS 17.x?
announced for future deprecation?
where IS this feature at?  Maybe this isn't the only page that needs updating?

[https://stackoverflow.com/questions/61892063/cannot-find-dreplay-exe-for-sql-server-2019](https://stackoverflow.com/questions/61892063/cannot-find-dreplay-exe-for-sql-server-2019)

"It's fully capable for both workload capture and replay. The docs are in the download. And OStress is so fast that a single client can typically drive enough load to saturate your server. It's widely used by SQL Server support. See eg github.com/microsoft/SqlNexus/wiki/RML-Utility – David Browne - Microsoft May 19 '20 at 14:08 "

"Mark Teagarden commented  ·  August 26, 2019 13:17  ·  Flag as inappropriate
Since Microsoft deprecated the "Management Tools - Basic" feature selection item when they forked SSMS off from the main product, but didn't update any of their DR installation documentation, and chose to silently deprecate the DReplay.exe tool - but only that tool, not Distributed Replay itself - in SSMS 18, it seems like the least they could do to support an official SQL Server feature. Ostress / ORCA are even less well documented / supported than DR so it's not clear what we're supposed to be relying on, or what the roadmap is. If I recall, DReplay.exe isn't even available on the lonely little "download other SQL Server command line tools" with relics like sql90."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c36ca7-8419-b719-492a-3e829b9bd08e
* Version Independent ID: 8dc1ef5d-99e9-76ed-b468-e65cfef7421c
* Content: [SQL Server Distributed Replay - SQL Server Distributed Replay](https://docs.microsoft.com/en-us/sql/tools/distributed-replay/sql-server-distributed-replay?view=sql-server-ver15)
* Content Source: [docs/tools/distributed-replay/sql-server-distributed-replay.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/distributed-replay/sql-server-distributed-replay.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@ScottStauffer -- Scott, thank you for your thoughtful questions.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)

@markingmyname -- Mark, please look into this potential documentation issue.

**Comment by markingmyname** [comment]
@dzsquared for awareness

**Comment by dzsquared** [comment]
Hi @ScottStauffer - we have work in motion to make DReplay admin CLI available more readily, as you have noted it is tough to install at this time. Appreciate your interest in the tool!
#please-close

**Comment by ScottStauffer** [comment]
Just for clarity on my part, it is not my desire for fixes or changes in the product packaging, architecture implementation or install, but rather a clear message which doesn’t mislead people into thinking that it’s just them and the product is working fine for everyone else.
I think people are seeing gaps because the product isn’t doing well in this certain area and instead of the product team not addressing the elephant in the room, the conversation or documentation is omitted.
Please just say, “that isn’t working right now… sorry, we are working on making it better, for now, please do this:”  or reach out to the MVP distribution list and ask an MVP interested in doing blog post or YouTube video on how they’ve currently been able to get it working and then amplify their contribution…

this provides MANY solutions:

  1.  Customers have a solution
  2.  Your team isn’t pressured into creating documentation of edge cases which have limited time horizon
  3.  MVP is able to document something that likely they have had to do for a client and get kudos to share.

**Comment by ScottStauffer** [comment]
Just for clarity on my part, it is not my desire for fixes or changes in the product packaging, architecture implementation or install, but rather a clear message which doesn’t mislead people into thinking that it’s just them and the product is working fine for everyone else.
I think people are seeing gaps because the product isn’t doing well in this certain area and instead of the product team not addressing the elephant in the room, the conversation or documentation is omitted.
Please just say, “that isn’t working right now… sorry, we are working on making it better, for now, please do this:”  or reach out to the MVP distribution list and ask an MVP interested in doing blog post or YouTube video on how they’ve currently been able to get it working and then amplify their contribution…

this provides MANY solutions:

  1.  Customers have a solution
  2.  Your team isn’t pressured into creating documentation of edge cases which have limited time horizon
  3.  MVP is able to document something that likely they have had to do for a client and get kudos to share.

**Comment by ScottStauffer** [comment]
Just for clarity on my part, it is not my desire for fixes or changes in the product packaging, architecture implementation or install, but rather a clear message which doesn’t mislead people into thinking that it’s just them and the product is working fine for everyone else.
I think people are seeing gaps because the product isn’t doing well in this certain area and instead of the product team not addressing the elephant in the room, the conversation or documentation is omitted.
Please just say, “that isn’t working right now… sorry, we are working on making it better, for now, please do this:”  or reach out to the MVP distribution list and ask an MVP interested in doing blog post or YouTube video on how they’ve currently been able to get it working and then amplify their contribution…

this provides MANY solutions:

  1.  Customers have a solution
  2.  Your team isn’t pressured into creating documentation of edge cases which have limited time horizon
  3.  MVP is able to document something that likely they have had to do for a client and get kudos to share.
