### ISSUE TITLE
Link to Microsoft SQL Server License Terms and Information doesn't provide SQL Server License Terms

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/sql-docs#6616]
It sends you to a MS Downloads site which when you click on the link shows this popup which doesn't have a file that indicates it is SQL Server License Terms:

![image](https://user-images.githubusercontent.com/16762974/126371743-bcbc3586-d0a6-44e0-bc60-c83dad62213a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d663fffb-d444-59c0-714f-433cf91980c4
* Version Independent ID: ee6da2f6-9ab0-792c-8a5d-d3c725779669
* Content: [Editions and supported features of SQL Server 2019 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-version-15?view=sql-server-ver15)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-version-15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-version-15.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@MarkIannucci -- Mark, thank you for catching this.

@MikeRayMSFT -- Mike, please look into this issue.
