### ISSUE TITLE
Incorrect External Table Permissions documented

### ISSUE THREAD

**Issue by A30005881** [MicrosoftDocs/sql-docs#6617]
The DROP EXTERNAL TABLE permissions documented [here](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/drop-external-table-transact-sql.md) are incorrect.

The document states that the ONLY role you need to have is ALTER on the schema for Azure Synapse (Unsure about other SQL instances, but suspect it would be the same). You actually need the following roles at a minimum to be able to drop an external table:

**System Roles**
- ALTER ANY EXTERNAL DATA SOURCE
- ALTER ANY EXTERNAL FILE FORMAT

(Tried using one or other, but both are required)

**Schema Roles**
- ALTER

Alternatively, you can use ALTER ANY SCHEMA as a system role

**Comment by WilliamAntonRohm** [comment]
@A30005881 -- Doug, thank you for your thorough feedback.  I am updating this article.

**Comment by jovanpop-msft** [comment]
@A30005881 could you let us know did oyu tried this on dedicated (Polybase) or serverless? I tried the script below on serverless and I need all three permissions to drop the table.  You say that you need alter schema OR alter format AND alter data source.

```
CREATE EXTERNAL DATA SOURCE nyctlc
WITH ( LOCATION = 'https://azureopendatastorage.blob.core.windows.net/nyctlc/')
GO
CREATE EXTERNAL FILE FORMAT ParquetFormat WITH (  FORMAT_TYPE = PARQUET );
GO
CREATE EXTERNAL TABLE Taxi ( vendor_id VARCHAR(100) COLLATE Latin1_General_100_BIN2_UTF8 )
WITH (   LOCATION = 'yellow/puYear=*/puMonth=*/*.parquet', DATA_SOURCE = nyctlc, FILE_FORMAT = ParquetFormat );
 
 
CREATE LOGIN test WITH PASSWORD = 'VerySecurePassword1234!@#$'
CREATE USER test FOR LOGIN test
 
EXEC ('DROP EXTERNAL TABLE Taxi') AS USER = 'test'
--Msg 15247, Level 16, State 1, Line 25
--User does not have permission to perform this action.
 
GRANT ALTER ANY SCHEMA TO test
EXEC ('DROP EXTERNAL TABLE Taxi') AS LOGIN = 'test'
--Msg 15247, Level 16, State 1, Line 31
--User does not have permission to perform this action.
 
GRANT ALTER ANY EXTERNAL DATA SOURCE TO test
EXEC ('DROP EXTERNAL TABLE Taxi') AS LOGIN = 'test'
--Msg 15247, Level 16, State 2, Line 36
--User does not have permission to perform this action.
 
GRANT ALTER ANY EXTERNAL FILE FORMAT TO test
EXEC ('DROP EXTERNAL TABLE Taxi') AS LOGIN = 'test'
--Commands completed successfully.
 
DROP USER test 
DROP LOGIN test
```

**Comment by A30005881** [comment]
@jovanpop-msft I think I may have confused you with what I was saying. I am not saying that ALTER ANY SCHEMA is enough, by it's self. I am saying that, at minimum, you need to have:

- ALTER ANY EXTERNAL DATA SOURCE
- ALTER ANY EXTERNAL FILE FORMAT
- ALTER ON SCHEMA // ALTER ANY SCHEMA

i.e.:
```
CREATE EXTERNAL DATA SOURCE nyctlc
 WITH ( LOCATION = 'https://azureopendatastorage.blob.core.windows.net/nyctlc/')
GO
CREATE EXTERNAL FILE FORMAT ParquetFormat WITH (  FORMAT_TYPE = PARQUET );
GO
CREATE EXTERNAL TABLE Taxi ( vendor_id VARCHAR(100) COLLATE Latin1_General_100_BIN2_UTF8 )
WITH (   LOCATION = 'yellow/puYear=*/puMonth=*/*.parquet', DATA_SOURCE = nyctlc, FILE_FORMAT = ParquetFormat );
 
 
CREATE LOGIN test WITH PASSWORD = 'VerySecurePassword1234!@#$'
CREATE USER test FOR LOGIN test
 
EXEC ('DROP EXTERNAL TABLE Taxi') AS USER = 'test'
--Msg 15247, Level 16, State 1, Line 25
--User does not have permission to perform this action.
 
GRANT ALTER ANY EXTERNAL DATA SOURCE TO test
EXEC ('DROP EXTERNAL TABLE Taxi') AS LOGIN = 'test'
--Msg 15247, Level 16, State 2, Line 36
--User does not have permission to perform this action.
 
GRANT ALTER ANY EXTERNAL FILE FORMAT TO test
EXEC ('DROP EXTERNAL TABLE Taxi') AS LOGIN = 'test'
--Msg 3701, Level 14, State 20, Line 1
--Cannot drop the EXTERNAL TABLE 'Taxi', because it does not exist or you do not have permission.

GRANT ALTER ANY SCHEMA TO test
EXEC ('DROP EXTERNAL TABLE Taxi') AS LOGIN = 'test'
--Commands completed successfully.

REVOKE ALTER ANY SCHEMA TO test
-- Recreate the table as was just dropped
CREATE EXTERNAL TABLE Taxi ( vendor_id VARCHAR(100) COLLATE Latin1_General_100_BIN2_UTF8 )
WITH (   LOCATION = 'yellow/puYear=*/puMonth=*/*.parquet', DATA_SOURCE = nyctlc, FILE_FORMAT = ParquetFormat );
 
GRANT ALTER ON SCHEMA::dbo TO test
EXEC ('DROP EXTERNAL TABLE Taxi') AS LOGIN = 'test'
--Commands completed successfully.

DROP USER test 
DROP LOGIN test 
```

As you can see, either `GRANT ALTER ON SCHEMA::_<schema_name>_` or `GRANT ALTER ANY SCHEMA` works (as its the system version, rather than a specific schema). Again, was looking to provide the minimum level of access, so for me ALTER ON SCHEMA makes more sense.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @A30005881 for taking the time to raise this to our attention, and for the detail repro scripts. Your feedback helps improve our docs for everyone. A doc update is in flight here to reflect the additional permissions needed here.
