### ISSUE TITLE
This page has a link to obsolete data.

### ISSUE THREAD

**Issue by kbittnerNIA** [MicrosoftDocs/sql-docs#6619]
The first part of basic troubleshooting has a link to an obsolete 20008 R2 document/page: "For details on validation, see Failover Cluster Step-by-Step Guide: Validating Hardware for a Failover Cluster.".

There is enough description on the current page to feel semi confident of running the tool on an operating, production cluster, but ... it would be better to have more info that is current!  I have AOG for SQL set up only in production, and want to run the validation, but ... was looking for more info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fedc707-0696-d509-8c60-743672e54fc0
* Version Independent ID: d0b0f16d-f330-1a1d-b396-6f4068a00e8b
* Content: [Failover Cluster Troubleshooting - SQL Server Always On](https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/windows/failover-cluster-troubleshooting?view=sql-server-2016)
* Content Source: [docs/sql-server/failover-clusters/windows/failover-cluster-troubleshooting.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/failover-clusters/windows/failover-cluster-troubleshooting.md)
* Product: **sql**
* Technology: **failover-cluster-instance**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by cawrites** [comment]
@kbittnerNIA thank you for contacting Microsoft we will look into your concern and reach out to you after our review.

**Comment by kfarlee** [comment]
Thanks for bringing this to our attention.  I've requested a current link for this topic from the Windows Cluster team. 
I'll replace the link in the doc as soon as I get it.

**Comment by kbittnerNIA** [comment]
Good, thanks!

**Comment by kfarlee** [comment]
The fix has been made, and is live now.  thanks for letting us know.

**Comment by MikeRayMSFT** [comment]
Fixed in https://github.com/MicrosoftDocs/sql-docs-pr/pull/19810
