### ISSUE TITLE
typo: caturing ?

### ISSUE THREAD

**Issue by deathv129** [MicrosoftDocs/sql-docs#6623]
In the section:
# Important remarks
History Table will stop **caturing** the updates for the duration of SYSTEM_VERSIONING = OFF.

Is this a typo of capturing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3e6674-aa5d-6b80-ae29-514954988128
* Version Independent ID: 01e72b93-3f3c-408f-b0b7-06fbb0076640
* Content: [Stopping System-Versioning on a System-Versioned Temporal Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/stopping-system-versioning-on-a-system-versioned-temporal-table?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/stopping-system-versioning-on-a-system-versioned-temporal-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/stopping-system-versioning-on-a-system-versioned-temporal-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@deathv129 -- Vincent, you're right, and this is a typo.  I'm fixing it shortly.

**Comment by deathv129** [comment]
@WilliamAntonRohm Thanks.

**Comment by markingmyname** [comment]
Good eye, @deathv129,! We’ve forwarded it to the writer, who should respond soon. Thanks!

Did you know: For minor things like typos, you can edit the doc! Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer.

Then all the writer has to do is sign off and it goes into the publishing queue.

Thanks again!

**Comment by markingmyname** [comment]
The article will be updated later this week.

thank you.

**Comment by deathv129** [comment]
@markingmyname Sorry I didn't notice that I could edit the doc directly, thanks for telling me. I will keep this in mind. =)
