### ISSUE TITLE
Azure SQL Managed Instance not in Applies to section

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/sql-docs#6632]
Hi team,
 
Please review as the article also applies to Azure SQL Managed Instance, but MI is not included in the Applies to section. Usually Applies to mention MI separately (see small insert in screenshot). 
There're quite some mentions of Azure SQL database only (see some examples underlined in screenshot) where it's also applicable to MI. Please review if some in the article is eligible for improvement to fully include Azure SQL Managed Instance.
 
Thank you and kind regards, Inge
#MSFTadvocate 
![Compatibility Certification](https://user-images.githubusercontent.com/40343254/126786543-65936ca7-9d65-4250-8130-3429bdad1425.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6f8d774-120c-2fb2-29ff-5782736200fa
* Version Independent ID: 16b4afed-becc-1d76-d8a5-3f80a2ff2c78
* Content: [Compatibility Certification - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/compatibility-certification?view=sql-server-ver15)
* Content Source: [docs/database-engine/install-windows/compatibility-certification.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/compatibility-certification.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by WilliamAntonRohm** [comment]
@ingebeumer -- Inge, thank you again for your feedback.

@pmasl -- Pedro, please look into this issue.

**Comment by rothja** [comment]
@MashaMSFT Could you please take a look at this issue in Pedro's absence? Thanks! #reassign:mashamsft

**Comment by MashaMSFT** [comment]
Hi @ingebeumer , thanks for contacting Microsoft! The documentation has been updated :) I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks again for reaching out and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
