### ISSUE TITLE
ODBC attributes, not sure about the platform

### ISSUE THREAD

**Issue by tolhc** [MicrosoftDocs/sql-docs#6633]
Hello, in the following page specifies that the attributes 
SQL_COPT_SS_CONNECT_RETRY_COUNT
SQL_COPT_SS_CONNECT_RETRY_INTERVAL
are available only for Windows

However in linux-mac odbc release notes it is implied that they are included.
See here (in July 2018)
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/release-notes-odbc-sql-server-linux-mac?view=sql-server-ver15#172-july-2018

Which one is true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5c7072-9621-6515-3084-8f2399cb1ee8
* Version Independent ID: a4940460-af5a-0d88-7218-d510e2a8909b
* Content: [ODBC DSN and connection string keywords - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/dsn-connection-string-attribute?view=sql-server-ver15#transparentnetworkipresolution---sql_copt_ss_tnir)
* Content Source: [docs/connect/odbc/dsn-connection-string-attribute.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/dsn-connection-string-attribute.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@tolhc

Thanks for submitting feedback. You are correct that these pages are not in sync. The connection resiliency feature, including those attributes, was extended to Linux, per the 17.2 release notes. However it looks like doc updates were missed. Those attributes are definitely available on Linux and macOS in version 17.2+ of the MS ODBC driver. I'll update the docs.

Thanks,
David

**Comment by David-Engel** [comment]
The docs have been updated. You can see the changes on these pages:
https://docs.microsoft.com/en-us/sql/connect/odbc/dsn-connection-string-attribute?view=sql-server-ver15#supported-dsnconnection-string-keywords-and-connection-attributes
and
https://docs.microsoft.com/en-us/sql/connect/odbc/connection-resiliency?view=sql-server-ver15

Thanks,
David

#please-close
