### ISSUE TITLE
Why promote a scan when a seek would be far better?

### ISSUE THREAD

**Issue by LarnuUK** [MicrosoftDocs/sql-docs#6634]
In the example it seems odd that the `ON` clause contains the following expressions:
```
      AND DATEPART(mm,OrderDate)= 3
      AND DATEPART(yy,OrderDate) = 2002
```
Though true in the comment at the start of the query, that the query will use the indexed view, it *scans* the index. If proper date boundaries are used and not `DATEPART`, then a **seek** can be used; far more performant.

I don't really understand why this document is teaching a bad habit here. When referencing columns in the `WHERE` or `ON` applying functions on them should be avoided to maintain SARGability. The above cause would be far better as the following, which maintains SARGability and promotes good query writing:
```
      AND o.OrderDate >= '20020301'
      AND o.OrderDate < '20020401'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a452207-5ac2-1a41-c5b1-3baf085a79b4
* Version Independent ID: a590e66c-ed9f-4d80-1511-1864128d2e8e
* Content: [Create Indexed Views - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/views/create-indexed-views?view=sql-server-ver15)
* Content Source: [docs/relational-databases/views/create-indexed-views.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/views/create-indexed-views.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @LarnuUK for contacting Microsoft with feedback about our product documentation.

This is a good edit! Perhaps these ranges:

```
      AND o.OrderDate >= '20110101'
      AND o.OrderDate < '20120101'
````

So that data is returned in the latest versions of the AdventureWorks sample databases.

Would you like to open a PR to make the change yourself, and be recognized as a contributor? Let me know.

**Comment by LarnuUK** [comment]
That's done for you, @WilliamDAssafMSFT . I did a small amount other "tidying" as well while I was there.
