### ISSUE TITLE
Documentation inconsistent with observed behavior

### ISSUE THREAD

**Issue by craig-wagner** [MicrosoftDocs/sql-docs#6636]
I have a database at the S1 pricing tier and was able to enabled CDC at the database and table level. From what I can tell the changes are being tracked. However, the documentation states:

> Availability of CDC in Azure SQL Databases (Preview) CDC can only be enabled on databases tiers above Standard 3 (S3+). Basic, S0, S1, S2 Azure SQL Databases are not supported for CDC.

I'm trying to determine if the observed behavior is a bug or the documentation is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 015ca28b-f0f3-c5b0-b2b6-b0a546fd4e17
* Version Independent ID: 1d340e3e-6e9e-1463-e9be-16e7d5a8062a
* Content: [What is change data capture (CDC)? - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/about-change-data-capture-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/track-changes/about-change-data-capture-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/about-change-data-capture-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@craig-wagner -- Craig, thank you for your feedback.

@rothja -- Jason, please look into this issue.

**Comment by rothja** [comment]
@craig-wagner Thank you for the question. @MaraSteiu Can you shed some light on what @craig-wagner is seeing here? Is there a documentation change we need to make? Thank you! #assign:MaraSteiu

**Comment by MaraSteiu** [comment]
Hi Jason!

There is no documentation change to make here, what we mentioned before still applies. However, due to a code regression (that we are fixing now), some customers were able to deploy CDC on S1 DBs. After our fix, that won't be possible anymore and we are reaching out now to impacted customers.

Thus, no changes are needed for documentation.

Thanks,
Mara

**Comment by PRMerger9** [comment]
MaraSteiu

-
You is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by rothja** [comment]
@craig-wagner Per Mara's comment above, I think this answers the behavior you are seeing. Let me know if that is not the case. Thank you!
