### ISSUE TITLE
Minor security concern with the password change command

### ISSUE THREAD

**Issue by dovecode** [MicrosoftDocs/sql-docs#6645]
The section on changing the SA password fails to point out that the user's history file will now contain both passwords. I personally prefer to do this like this:

    docker exec -it mssqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U SA \
        -P "$(read -sp "Enter current SA password: "; echo "${REPLY}")" \
        -Q "ALTER LOGIN SA WITH PASSWORD=\"$(read -sp "Enter new SA password: "; echo "${REPLY}")\""

This way, the passwords will be prompted for when the command is run instead of being on a command line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&preserve-view=true&pivots=cs1-bash)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@dovecode -- Nicolai, thank you for your feedback and code.

@amvin87 -- please look into this issue.

**Comment by amvin87** [comment]
@dovecode - Thank you Nicolai, agreed what you suggested is a safe method to update the password, without printing the password on the CLI. 

@WilliamAntonRohm - Can you please add this to the doc as a alternate method to update the password.

**Comment by WilliamAntonRohm** [comment]
@amvin87 -- yes, and thank you for validating this approach.

**Comment by WilliamAntonRohm** [comment]
@amvin87 -- please review [private PR 19950](https://github.com/MicrosoftDocs/sql-docs-pr/pull/19950).
