### ISSUE TITLE
Shared DB instances are not supported anymore

### ISSUE THREAD

**Issue by mcurko** [MicrosoftDocs/sql-docs#6646]
As I just found out after upgrading LocalDB from v13 to v15, shared DB instances don't seem to work anymore.

https://feedback.azure.com/forums/908035-sql-server/suggestions/36481279-sql-server-2017-express-localdb-shared-instance-co

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea66ca27-e0b1-cd1e-a8ef-55911169c71a
* Version Independent ID: f2340ce9-9771-851e-60a7-237c6e55f085
* Content: [SQL Server Express LocalDB - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/sql-server-express-localdb.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/sql-server-express-localdb.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@mcurko,

Thanks for bringing this to our attention.

Our engineering team is investigating this issue.  We are still not at a phase where we can document this yet.

However, we will update the article accordingly if we determine this to be a limitation or restriction.

For further assistance, please contact support.

Please visit one of the following pages depending on your product or service.

[On Prem users](https://support.microsoft.com/en-us/supportforbusiness/productselection)
[SQL on Azure](https://ms.portal.azure.com/#home)
[Services Hub (Unified/premier customers)](https://serviceshub.microsoft.com/support/create/097a91e3-084a-46a8-b385-d5b07ffedcfe)

We apologize for the inconvenience.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
