### ISSUE TITLE
Triggers are not allowed system-versioned table, not just the history table.

### ISSUE THREAD

**Issue by ZanderFick** [MicrosoftDocs/sql-docs#6648]
The docs indicate:

>"The history table cannot have a primary key, foreign keys, unique indexes, table constraints or triggers. It cannot be configured for change data capture, change tracking, transactional or merge replication"

Implying that the history table may not have triggers, but nothing is said about the base versioned table having triggers or not.

On a provisioned Azure SQL server instance, this appears to be invalid for the base system-versioned table as well:

Test:
```SQL
CREATE TABLE dbo.DepartmentHistory
(
    DeptID INT NOT NULL
  , SysStartTime DATETIME2 NOT NULL
  , SysEndTime DATETIME2 NOT NULL
);
GO

CREATE TABLE dbo.Department
(
    DeptID INT NOT NULL PRIMARY KEY CLUSTERED
  , SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL
  , SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL
  , PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.DepartmentHistory));
GO


CREATE TRIGGER dbo.test_trigger_create on dbo.Department
INSTEAD OF INSERT
AS
BEGIN
	SELECT 1
END
GO
```

The `CREATE TRIGGER COMMAND` raises:
>```Cannot` create a trigger on a system-versioned temporal table 'azure-sql-test-db.dbo.Department'.```

Therefore implying that triggers are not allowed on the base temporal table either.
Should the docs perhaps clarify this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349eae51-5e73-47db-ee0d-8cae824f5c45
* Version Independent ID: 98d04967-6eb4-4d4d-e4a4-8e77a0f1fba0
* Content: [Creating a System-Versioned Temporal Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/creating-a-system-versioned-temporal-table?view=sql-server-ver15#alter-non-temporal-table-to-be-a-system-versioned-temporal-table)
* Content Source: [docs/relational-databases/tables/creating-a-system-versioned-temporal-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/creating-a-system-versioned-temporal-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@ZanderFick -- Zander, thank you for your detailed feedback.

@rothja -- Jason, please look into this issue.

**Comment by rothja** [comment]
@ZanderFick Thanks for this question and the example. I will look into this and get back to you over the next few weeks after I figure out whether we need to make a clarification in the docs here. Thank you!

**Comment by markingmyname** [comment]
@ZanderFick 

First, we apologize for the delayed response.

Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
@ZanderFick 

I was able to reproduce the error you received.

I have reached out to the appropriate parties to confirm our results.

thank you.

**Comment by markingmyname** [comment]
@ZanderFick 

After further investigation, we have determined there might be some inconsistencies between creating a trigger on a system-versioned temporal table and converting a regular base table that has triggers into a system-versioned temporal table.

We appreciate you bringing this information to our attention.

We will move forward closing this Issue, but we will not close the fact we will revisit this Issue from the Microsoft side and make the appropriate updates.

Thank you.

@WilliamDAssafMSFT for awareness.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site.

**Comment by WilliamDAssafMSFT** [comment]
@ZanderFick Following up having just figured this out. The issue here is your use of INSTEAD OF triggers, instead of AFTER triggers. This is [documented](https://docs.microsoft.com/sql/relational-databases/tables/temporal-table-considerations-and-limitations): "INSTEAD OF triggers are not permitted on either the current or the history table to avoid invalidating the DML logic. AFTER triggers are permitted only on the current table. They are blocked on the history table to avoid invalidating the DML logic." Change your sample to use `FOR INSERT` or `AFTER INSERT` and it works fine.

CC @markingmyname
