### ISSUE TITLE
Error in Unit Test Walkthrough

### ISSUE THREAD

**Issue by philhege** [MicrosoftDocs/sql-docs#6651]
(transferred here per @rootsmusic)

Link to article:
(https://docs.microsoft.com/en-us/sql/ssdt/walkthrough-creating-and-running-a-sql-server-unit-test?view=sql-server-ver15 (Test for uspShowOrderDetails)

Problem:
The setup script that creates the sample database assigns two constraints to the order table's order date. The upper bound of the value is 01/01/2020, but the procedures use getdate() to assign order date, which is obviously out-of-bounds. I suggest extending the end date to 2025:
USE [SimpleUnitTestDB]
GO

ALTER TABLE [Sales].[Orders] DROP CONSTRAINT [CK_Orders_OrderDate]
GO

ALTER TABLE [Sales].[Orders] WITH CHECK ADD CONSTRAINT [CK_Orders_OrderDate] CHECK (([OrderDate]>'01/01/2005' AND [OrderDate]<'01/01/2025'))
GO

ALTER TABLE [Sales].[Orders] CHECK CONSTRAINT [CK_Orders_OrderDate]

USE [SimpleUnitTestDB]
GO

ALTER TABLE [Sales].[Orders] DROP CONSTRAINT [CK_Orders_FilledDate]
GO

ALTER TABLE [Sales].[Orders] WITH CHECK ADD CONSTRAINT [CK_Orders_FilledDate] CHECK (([FilledDate]>=[OrderDate] AND [FilledDate]<'01/01/2025'))
GO

ALTER TABLE [Sales].[Orders] CHECK CONSTRAINT [CK_Orders_FilledDate]

**Comment by dzsquared** [comment]
#assign:dzsquared

**Comment by dzsquared** [comment]
It looks like in the meantime the docs were corrected.
#please-close

**Comment by philhege** [comment]
Gracias.
