### ISSUE TITLE
Please provide an example of the step 7 "In the Command box, enter powershell.exe with parameters specifying the PowerShell script to be run."

### ISSUE THREAD

**Issue by JamieL22** [MicrosoftDocs/sql-docs#6652]
What might this imply:
"In the Command box, enter powershell.exe with parameters specifying the PowerShell script to be run."

Please iterate the correct parameters.  Are the parameters 

- " set-executionpolicy"
- " -file"
- " must the file include a path?"
- " is the file a .ps1, or psmx?"
- " somthing else"

The error received for the situation I am looking at is:

- Unexpected token, which is this case appears to be a legitimate PowerShell character "{"

It would be far more helpful if this documentation has a simple example included or step 7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db6f2a8a-7b0a-b5b6-7095-b7569d2c23bb
* Version Independent ID: 26d6594a-6d7d-7091-0f4b-382bb4a38ebe
* Content: [Run Windows PowerShell Steps in SQL Server Agent - SQL Server](https://docs.microsoft.com/en-us/sql/powershell/run-windows-powershell-steps-in-sql-server-agent?view=sql-server-ver15)
* Content Source: [docs/powershell/run-windows-powershell-steps-in-sql-server-agent.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/run-windows-powershell-steps-in-sql-server-agent.md)
* Product: **sql**
* Technology: **sql-server-powershell**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@Matteo-T 

do you have a recommendation?

**Comment by JamieL22** [comment]
Mark,

Sort of… One of the items I deal with in a military operation is the presence of security rules that require all extended stored procedures be disabled.

The command line is the one option that allows me the use of sqlcmd to briefly enable and subsequently disable to ability to run Powershell commands.  I’m not sure that is what you are looking for here though.   Unfortunately this was quite some time ago and I cannot recall the context.

Seems the TLS 1.2 is almost always an issue – add the line.  The other issue had to do with the xp_cmdshell being disabled as I recall.   Still fuzzy on the context though.   I believe what I did to get around the command shell being disabled has something to do with the questions I asked you about.

Jamie
==============Begin===============

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]:Tls12

# Create a batch file to enable xp_cmdShell
@batch1=@”
Exec sp_configure ‘show advanced options’ ,1
RECONFIGURE
“@

# Enable xp_cmdshell
@batch2=@”
Exec sp_configure ‘xp_cmdshell’ ,1
RECONFIGURE
“@

# Disable xp_cmdshell
@batch3=@”
Exec sp_configure ‘xp_cmdshell’ ,0
RECONFIGURE
“@

# Turn Off Advanced Options
@batch1=@”
Exec sp_configure ‘show advanced options’ ,0
RECONFIGURE
“@

# enable xp_cmdshell temporarily to launch powershell
Invoke-sqlcmd -query $batch1
Invoke-sqlcmd -query $batch2

# launch powershell scripts
Set-Location “X:\myfolder\myPSfiles”

Invoke-Expression “X:\myfolder\myPSfiles\myPS1.ps1”
Invoke-Expression “X:\myfolder\myPSfiles\myPS2.ps1”

# disable xp_cmdshell for security reasons
Invoke-sqlcmd -query $batch3
Invoke-sqlcmd -query $batch4

============== End ===============

**Comment by Matteo-T** [comment]
@JamieL22 / @markingmyname - I've sent out a PR to, hopefully, address the original questions asked in this issue. I am not sure how to read the follow-up post from @JamieL22, so please feel free to let me know if there are other things that are worth a little clarification. The gist is that you can pass pretty much what you can do if you do "PowerShell.exe -?" (with the usual caveats about escaping and such).

**Comment by markingmyname** [comment]
Thank you, @Matteo-T.

@JamieL22,

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site.
