### ISSUE TITLE
Typo: RDMBS

### ISSUE THREAD

**Issue by frajasn** [MicrosoftDocs/sql-docs#6653]
There is what looks to me like a typo in the 1st paragraph under "Row mode execution".  The paragraph says "RDMBS tables", but shouldn't it be "RDBMS" (Relational Database Management System)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45a7c96a-9d41-83e8-0ae8-b73fff390f48
* Version Independent ID: 1a880308-6a3b-6944-6428-1331801b327a
* Content: [Query Processing Architecture Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/query-processing-architecture-guide?view=sql-server-ver15)
* Content Source: [docs/relational-databases/query-processing-architecture-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/query-processing-architecture-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by WilliamAntonRohm** [comment]
@frajasn -- thank you for bringing this to our attention.  I am updating the article.
