### ISSUE TITLE
WSFC cluster mention requirement for CoreNet-ICMP6-* firewall rules to be enabled

### ISSUE THREAD

**Issue by janis-veinbergs** [MicrosoftDocs/sql-docs#6659]
One of those pages where I can find a button to comment something about WSFC network requirements.
Nowhere at docs.microsoft.com I find a clue that WSFC Network requirements must have `CoreNet-ICMP6-*` Rules enabled. (`Get-NetFirewallRule -ID "CoreNet-ICMP6-*"`) and it should be mentioned somwhere.

Failover Cluster firewall rules also include some sort of ICMPv6 communication requirements, however they apparently are not enought. (`FailoverClusterManager-ICMPv6*`).

What happens if `CoreNet-ICMP6-*` is disabled - the cluster constantly looses network routing information and nodes get quarantined. For more information: https://serverfault.com/questions/976162/windows-server-2016-guests-in-wsfc-cluster-randomly-quarantined-due-dropping-hea

Default Windows configuration HAS these rules enabled, however for those environments that try to lock down and only allow bare necessary things, not having this information available is troublesome.

Some additional pages about WSFC network requirements, not mentioning this stuff:
- https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements#cluster-service
- https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/windows-fireware-rule-block-udp-communication

Yes, I technically understand that Cluster Service does not kind of need that traffic, however Neighbor Discovery Protocol must be functioning for hidden WSFC IPv6 adapter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30225758-8196-5216-31fc-8380133d577e
* Version Independent ID: 4718f672-8fd8-9956-45dc-4329bfcc0b7b
* Content: [Before Installing Failover Clustering - SQL Server Always On](https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/install/before-installing-failover-clustering?view=sql-server-ver15)
* Content Source: [docs/sql-server/failover-clusters/install/before-installing-failover-clustering.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/failover-clusters/install/before-installing-failover-clustering.md)
* Product: **sql**
* Technology: **failover-cluster-instance**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@janis-veinbergs -- Jānis, thank you for your detailed feedback.

@cawrites -- Cheryl, please look into this issue.

**Comment by cawrites** [comment]
@janis-veinbergs thank you for contacting us with your question. We will review the content links you have shared and provide an update when it is available. We appreciate your patience as we may solicit another review from someone from our product team.

**Comment by cawrites** [comment]
@Kevin-Farlee can you provide a comment on this issue.

**Comment by Kevin-Farlee** [comment]
To me it looks like the defect is complaining about WSFC documentation, and one of the docs the defect points to does mention the need to let ICMP6 traffic through.
I'll run this by a contact in the cluster team to see what he has to say about it.

Kevin

**Comment by cawrites** [comment]
@JannikBausager we are still following up on this issue. We appreciate your patience.

**Comment by cawrites** [comment]
@janis-veinbergs based on your reply it appears you have gotten the information that you needed. Thank you for contacting Microsoft and please do not hesitate to contact us again.
