### ISSUE TITLE
Inconsistent casing in script example

### ISSUE THREAD

**Issue by rcverbeek** [MicrosoftDocs/sql-docs#6660]
The script for detecting orphaned users uses wrong casing for sid (SID), producing a warning on a case sensitive db. Furthermore I would prefer to add the dp alias on authentication_type_desc:

SELECT dp.type_desc, dp.**sid**, dp.name AS user_name
FROM sys.database_principals AS dp  
LEFT JOIN sys.server_principals AS sp  
    ON dp.**sid** = sp.**sid**  
WHERE sp.sid IS NULL  
    AND **dp**.authentication_type_desc = 'INSTANCE';

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc238707-5878-9a71-04f4-b8fd05f60c12
* Version Independent ID: 881acab6-0949-5f85-66fd-b308e85f7bf0
* Content: [Restore a Database to a New Location (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/restore-a-database-to-a-new-location-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/backup-restore/restore-a-database-to-a-new-location-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/restore-a-database-to-a-new-location-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@rcverbeek -- thank you for your detailed feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@rcverbeek -- I found this example in a different article, [Troubleshoot orphaned users (SQL Server)](https://docs.microsoft.com/sql/sql-server/failover-clusters/troubleshoot-orphaned-users-sql-server) and am updating it there.
