### ISSUE TITLE
Minor Typo in docs nav bar

### ISSUE THREAD

**Issue by StrikeNP** [MicrosoftDocs/sql-docs#6664]
There is an unnecessary `)` in the nav menu for 
`Docs/ SQL Tools SQL / Server Management Studio (SSMS)/ Concepts SQL Server Agent / Job Properties / General Page)`
https://docs.microsoft.com/en-us/sql/ssms/agent/job-properties-new-job-general-page?view=sql-server-ver15

![image](https://user-images.githubusercontent.com/2577059/128412619-efddaad0-e662-4f7b-8639-c8f63b9b8587.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c944409d-c9f8-5068-4f21-c24b2f2d4fcd
* Version Independent ID: 0af6d1ea-e2f1-2647-7944-7f27f0d593fe
* Content: [Job Properties - New Job (General Page) - SQL Server Agent](https://docs.microsoft.com/en-us/sql/ssms/agent/job-properties-new-job-general-page?view=sql-server-ver15)
* Content Source: [docs/ssms/agent/job-properties-new-job-general-page.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/job-properties-new-job-general-page.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@StrikeNP -- Nicolas, thank you for bringing this to our attention.  I am updating the nav text.
