### ISSUE TITLE
TLS support level contradicted by other article

### ISSUE THREAD

**Issue by 1Dimitri** [MicrosoftDocs/sql-docs#6669]
This page indicates SQL Server supports SSL 3.0 and TLS 1.0 which is contradicted by
[KB 3135244](https://support.microsoft.com/en-us/topic/kb3135244-tls-1-2-support-for-microsoft-sql-server-e4472ef8-90a9-13c1-e4d8-44aad198cdbe)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fbb99b-b42b-0558-7270-e9a3c8b34828
* Version Independent ID: 30f9a223-3dc9-9e21-0f1a-5238f0b939d0
* Content: [Connect to the Database Engine Using Extended Protection - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/connect-to-the-database-engine-using-extended-protection?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/connect-to-the-database-engine-using-extended-protection.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/connect-to-the-database-engine-using-extended-protection.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@1Dimitri -- thank you for your feedback.

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
Hi @1Dimitri - Can you please clarify where you see a contradiction? All supported versions of SQL Server still supports SSL 3.0 and TLS 1.0

**Comment by VanMSFT** [comment]
Hi @1Dimitri - Thanks for the clarification. I don't think there's any contradiction in the warning message, as it is true if you don't have a fully updated SQL Server 2012 or 2014. However, some clarification is needed to that message to update SQL Server to the latest build.

**Comment by 1Dimitri** [comment]
Indeed @VanMSFT  there are limitations for unpatched SQL Server 2012 and 2014. Unfortunately, these are here the limits of docs.microsoft.com where the listed versions of SQL Server are 2019, 2017, 2016 only. So you cannot know if the user is reading that page specifically for the specific version appended as a query in the URL or if he landed using some search engine to find resources for previous versions not officially available in docs.
Alternatively you may want to add the KB article link as part of the "recommended content"./further reading section.

**Comment by VanMSFT** [comment]
Thanks, @1Dimitri. I'm making a change to the doc and it should be updated later today.
