### ISSUE TITLE
Telnet alternative

### ISSUE THREAD

**Issue by aaronsentell-dba** [MicrosoftDocs/sql-docs#6676]
[Enter feedback here]
If telnet isn't installed, you can use the Test-netconnection PowerShell Cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6deae12a-182e-7a71-3c9f-ba2aad84dec7
* Version Independent ID: d25d90c8-26b2-c5a9-71a3-bc03d6eb9161
* Content: [Common issues & resolutions with availability groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/troubleshoot-always-on-availability-groups-configuration-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/troubleshoot-always-on-availability-groups-configuration-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/troubleshoot-always-on-availability-groups-configuration-sql-server.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@aaronsentell-dba -- thank you for your suggestion!

@cawrites -- please look into this issue.

**Comment by cawrites** [comment]
@aaronsentell-dba thank you for providing this additional alternative. We do try to provide several options for troubleshooting but we are well aware it's not possible to cover all of them. I will discuss this with my team and update this issue when an answer if available.

**Comment by cawrites** [comment]
@aaronsentell-dba thank you for making this suggestion. At this time we have decided not to include it in our content. I understand it is an option, but we prefer to use the option defined in the content as it is well established in the technical community. Thank you for contacting Microsoft.
