### ISSUE TITLE
remote query timeout incorrect default in docs

### ISSUE THREAD

**Issue by mcquary** [MicrosoftDocs/sql-docs#6680]
The default value in this doc is incorrect. The default appears to be 600, not 0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e25fe07f-aad6-ad1d-8645-5a15b55c4a0a
* Version Independent ID: 3cf2c9b2-8a73-cea6-4da2-3677d5076725
* Content: [Configure the remote query timeout Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-remote-query-timeout-server-configuration-option?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-the-remote-query-timeout-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-remote-query-timeout-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@mcquary -- Kevin, thank you for bringing this to our attention.  I am updating the article.
