### ISSUE TITLE
Missing quote in Azure notebook

### ISSUE THREAD

**Issue by CristianoGasparotto** [MicrosoftDocs/sql-docs#6681]
In ADS Notebook, TSQL syntax check fails because of a missing quote in line 62:
Now it is: select 'BACKUP LOG [' + @dbname + '] TO DISK = ''some_volume:\some_folder + @dbname + '_LOG.trn''' as BackupLogCommand

it should be: select 'BACKUP LOG [' + @dbname + '] TO DISK = ''some_volume:\some_folder' + @dbname + '_LOG.trn''' as BackupLogCommand

(missing quote after some_folder

**Comment by WilliamAntonRohm** [comment]
@CristianoGasparotto -- Cristiano, thank you for catching this.  Are you looking at a particular docs.microsoft.com article?

**Comment by CristianoGasparotto** [comment]
Yes, sorry. I was referring to notebook included here: https://docs.microsoft.com/en-us/sql/relational-databases/logs/troubleshoot-a-full-transaction-log-sql-server-error-9002?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@CristianoGasparotto -- Cristiano, thank you for your follow-up.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@CristianoGasparotto -- Christiano, when I look at this article it appears correctly.  Please let me know if it's fixed on your end as well.

**Comment by CristianoGasparotto** [comment]
@WilliamAntonRohm The code in the article is correct. The code in ADS Notebook is not 
![Image 1423](https://user-images.githubusercontent.com/46725217/130572943-e659a8e9-d27e-4f34-838c-ce78acf4790d.png)

**Comment by WilliamAntonRohm** [comment]
@CristianoGasparotto -- Cristiano, thank you for clarifying.  I am updating this code.

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- please review [PR 256](https://github.com/microsoft/tigertoolbox/pull/256).

**Comment by MashaMSFT** [comment]
Hi @CristianoGasparotto , thanks for contacting Microsoft! My apologies for the delay. The documentation has been updated and should be live later this week. I'll close out this Git Issue but please feel free to comment should you need anything further.

Thanks!
Masha from the SQL Docs team
#please-close
