### ISSUE TITLE
SINGLE_USER isn't supported on all databases

### ISSUE THREAD

**Issue by Gilesey** [MicrosoftDocs/sql-docs#6682]
Hi, just a quick one - this topic says this article applies to all versions, and it doesn't (won't work on SQL Managed Instance.)
Wouldn't it be great if there was a stored procedure or function can I call like with modenizr to say "DoesSupport('SET SINGLE_USER') or DoesSupport('AT TIME ZONE'), taking the guess work out of compatibility. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b67ab534-229d-f12a-6216-9550d790ea42
* Version Independent ID: 529e1ec2-00c5-9c13-1a75-dfc183765aff
* Content: [Set a Database to Single-user Mode - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/set-a-database-to-single-user-mode?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/set-a-database-to-single-user-mode.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/set-a-database-to-single-user-mode.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @Gilesey for taking the time to provide document feedback. In this case, this article's "Applies to" is correct. Though they share a Database Engine, the Azure SQL Database and SQL Managed Instance products are not a _version_ of SQL Server, but rather their own platforms. This is good feedback though that we could be more clear on the Applies To: line and we are discussing internally.

As for a proposed DoesSupport() function, that sounds like a great suggestion for [SQL Feedback](https://feedback.azure.com/forums/908035-sql-server). 

Thanks again for this feedback, your suggestions help improve our documentation.
