### ISSUE TITLE
TDE installation: Typo when referring to path between text and code

### ISSUE THREAD

**Issue by 1Dimitri** [MicrosoftDocs/sql-docs#6685]
Small typo:

The incipit says we assume the files are in C:\EKM.
The paths listed within the code are referring to C:\EKM_files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61685ee-fa58-d14a-b611-040c89372dcc
* Version Independent ID: dfbcf396-28e6-0fd2-e7cc-3178d3c7f4f2
* Content: [Enable TDE on SQL Server Using EKM - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/enable-tde-on-sql-server-using-ekm?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/enable-tde-on-sql-server-using-ekm.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/enable-tde-on-sql-server-using-ekm.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @shohamMSFT
* Microsoft Alias: **shohamd**

**Comment by WilliamAntonRohm** [comment]
@1Dimitri -- thank you for catching this.  I am updating the article.
