### ISSUE TITLE
Youtube Link Broken

### ISSUE THREAD

**Issue by Lickrob** [MicrosoftDocs/sql-docs#6686]
https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/in-memory-oltp-in-memory-optimization?view=sql-server-ver15 Video has been made private, all links broken.

**Comment by WilliamAntonRohm** [comment]
@Lickrob -- thank you for catching this.  I am looking into the video issue.

**Comment by WilliamAntonRohm** [comment]
@Lickrob  -- apologies for the delay in responding.  That video has been retired, and this page as well.  Please see [Overview and Usage Scenarios](https://docs.microsoft.com/sql/relational-databases/in-memory-oltp/overview-and-usage-scenarios) instead.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
