### ISSUE TITLE
Outdated reference to Azure classic portal

### ISSUE THREAD

**Issue by Greg-T8** [MicrosoftDocs/sql-docs#6693]
Under **How do I change my default Active Directory so my key vault is created in the same subscription and Active Directory as the service principal I created for the SQL Server Connector?**, this page has an outdated reference to the classic Azure portal, which is no longer accessible. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 248641a9-2364-dcbf-b071-6df585b05bba
* Version Independent ID: bd00d184-ff67-3b36-2d8f-22d05538a92f
* Content: [SQL Server Connector maintenance & troubleshooting - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/sql-server-connector-maintenance-troubleshooting?view=sql-server-ver15#upgrade-of--connector)
* Content Source: [docs/relational-databases/security/encryption/sql-server-connector-maintenance-troubleshooting.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/sql-server-connector-maintenance-troubleshooting.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@gregt8t -- Greg, thank you for your feedback.

@jaszymas -- please look into this issue.

**Comment by VanMSFT** [comment]
Thanks @Greg-T8! I'm updating the instructions. We appreciate your help!

**Comment by VanMSFT** [comment]
#reassign:VanMSFT
