### ISSUE TITLE
Connecting Issue solved by opening port 1431

### ISSUE THREAD

**Issue by Rhinostril** [MicrosoftDocs/sql-docs#6696]
[Enter feedback here]
This tutorial page specifies port 1433 to be open for connecting with Windows devices/clients.
When i follow the setup instructions and see which ports sqlserver is listening on, they are: 1433 AND 1431.
For a while i was having an issue where clients that are on the same local subnet could'nt connect, but clients that connected through vpn would be able to succesfully connect.
So I suggest that you maybe state the serverside firewall should open both ports instead of just 1433.
This may also be error on my side.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @Rhinostril, thank you for your feedback. By default, SQL Server listens on port 1433, and only 1433.
