### ISSUE TITLE
Wrong Command Posted on an SQL Database Properties MS Docs Site

### ISSUE THREAD

**Issue by StoyanChalakov** [MicrosoftDocs/sql-docs#6699]
**Is your feature request related to a problem? Please describe.**
This is a request to correct/update certain article, related to SQL Server Database Properties and in particular to Auto Update Statistics.
The article references a wrong command and article (CREATE STATISTICS (Transact-SQL)) when it comes to the Auto Update Statistics (should be Update STATISTICS (Transact-SQL))

**Describe the solution you'd like**
Under the section Auto Update Statitstics replace (CREATE STATISTICS (Transact-SQL)) with (UPDATE STATISTICS (Transact-SQL))

**Describe alternatives you've considered**
No alternatives, the procedure should be corrected/updated.

**Additional context**
Linkl to the article:
https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-properties-options-page?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ff5f89-39e8-2526-9f4c-fd03c8674fdc
* Version Independent ID: d27b5731-f02e-c33c-5a6e-86a0a7ea0522
* Content: [Database Properties (Options Page) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-properties-options-page?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/database-properties-options-page.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/database-properties-options-page.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @StoyanChalakov for contacting Microsoft with feedback about our product documentation. A doc update is in flight to correct this link and one like it for AUTO CREATE as well. Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by StoyanChalakov** [comment]
@WilliamDAssafMSFT  Glad to help, thanks for the update!
