### ISSUE TITLE
Can't install ODBC driver anymore

### ISSUE THREAD

**Issue by amihappy** [MicrosoftDocs/sql-docs#6700]
Hello,
Following instructions from the page, I cannot install odbc driver today, yesterday it was working fine.
I can see on https://packages.microsoft.com/debian/10/prod/dists/ that files has changed yesterday evening (16 aug 21:12) and building image stopped working on our CI/CD. Is there anything else that needs to be added to this instruction?

error:
 => [ 5/23] RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -                                     
 => [ 6/23] RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list 
 => [ 7/23] RUN apt-get update                                                                                               
 => ERROR [ 8/23] RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17                                                           
------
 > [ 8/23] RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17:
#12 0.358 Reading package lists...
#12 1.188 Building dependency tree...
#12 1.381 Reading state information...
#12 1.478 Some packages could not be installed. This may mean that you have
#12 1.478 requested an impossible situation or if you are using the unstable
#12 1.478 distribution that some required packages have not yet been created
#12 1.478 or been moved out of Incoming.
#12 1.478 The following information may help to resolve the situation:
#12 1.478
#12 1.478 The following packages have unmet dependencies:
#12 1.593  libodbc1 : PreDepends: multiarch-support but it is not installable
#12 1.594  odbcinst1debian2 : PreDepends: multiarch-support but it is not installable
#12 1.615 E: Unable to correct problems, you have held broken packages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by timnyborg** [comment]
I ran into the same problem, because the latest debian docker image (python:3.7-slim in my case) moved from buster to bullseye.  Specifying `FROM python:3.7-slim-buster` fixed the issue.  Bullseye doesn't seem to have a msodbcsql17 library yet.

**Comment by amihappy** [comment]
Correct, thanks, i've checked release on microsft package, and haven't checked my source image (pytohn3.7). Thanks for help

**Comment by WilliamAntonRohm** [comment]
@amihappy -- Jacek, thank you for your feedback.  Please let me know if you are able to resolve this difficulty. 

@timnyborg -- Tim, thank you for your suggestion.

cc @David-Engel for awareness

**Comment by andrewspiers** [comment]
Are there any plans in the works for packaging msodbcql17 for latest stable Debian?

**Comment by David-Engel** [comment]
> Are there any plans in the works for packaging msodbcql17 for latest stable Debian?

@andrewspiers 

We can't make any public promises about future releases, but if you look at the release notes for past releases, you can see that support for new Debian/Ubuntu/Red Hat/SUSE/Apple OS versions have historically been added to the ODBC driver GA release following the GA release of those OS versions. You can also see the historical 6-month ODBC GA release cadence of Jan/July.

**Comment by andrewspiers** [comment]
Thanks @David-Engel  !

**Comment by lochuynh** [comment]
Thanks @timnyborg

**Comment by David-Engel** [comment]
Closing this as it isn't a documentation issue.

#please-close

**Comment by mlocati** [comment]
What does that mean? "It isn't a documentation issue" doesn't tell me that much?

Also: why this issue has been closed? Not having msodbcsql for Debian 11 is still an issue...
