### ISSUE TITLE
[View the Definition of a Stored Procedure] sp_helptext is not supported in Azure Synapse SQL 

### ISSUE THREAD

**Issue by kawo123** [MicrosoftDocs/sql-docs#6713]
In our [documentation](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/view-the-definition-of-a-stored-procedure?view=sql-server-ver15#TsqlProcedure), it implies that `sp_helptext` can be used to see the definition of a view in T-SQL for Azure Synapse Analytics. 

In contrary, `sp_helptext` is not supported in both Synapse SQL Serverless and Dedicated Pool. 

![image](https://user-images.githubusercontent.com/14829553/130118065-f3e2dd13-591a-438f-986c-cdf43cc8dbce.png)

I may be missing something or the documentation should call out that `sp_helptext` doesn't work in Synapse. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c44500e4-1856-1a19-1488-35b7d21d0351
* Version Independent ID: 90b9a8ca-4a22-d4e9-6060-01f6576adc43
* Content: [View the Definition of a Stored Procedure - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/view-the-definition-of-a-stored-procedure?view=sql-server-ver15#TsqlProcedure)
* Content Source: [docs/relational-databases/stored-procedures/view-the-definition-of-a-stored-procedure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/stored-procedures/view-the-definition-of-a-stored-procedure.md)
* Product: **sql**
* Technology: **stored-procedures**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @kawo123 for the feedback. I've reached out to the product team and will update documentation. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. 
	
Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @kawo123 for the feedback. A document update is in flight to address this. Thanks again for this feedback, your suggestions help improve our documentation.
