### ISSUE TITLE
SQL Server 2016/2017 - Support for Windows Server 2022

### ISSUE THREAD

**Issue by micoolpaul** [MicrosoftDocs/sql-docs#6722]
Hi,

Could we also please have information on whether SQL Server 2016/2017 will be supported on Windows Server 2022.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b411a1-f282-d77e-a497-83d08a963549
* Version Independent ID: f896a7f4-f08a-4b67-6d98-c14a0e1a969e
* Content: [SQL Server 2016 & 2017: Hardware & software requirements - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server?view=sql-server-ver15)
* Content Source: [docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@micoolpaul -- thank you for your question.

@cawrites -- please look into this issue.

**Comment by cawrites** [comment]
@micoolpaul regarding your question: 

"We we only be supporting those releases in active support on the new OS: SQL17, SQL19, and eventually SQL22."

We encourage you continue to look at our content for future updates. Thank you for contacting Microsoft.
