### ISSUE TITLE
Missing semi-colon in Java example

### ISSUE THREAD

**Issue by gpigc** [MicrosoftDocs/sql-docs#6725]
Missing a semi-colon after storePassword in example:
String connectionUrl =
    "jdbc:sqlserver://localhost:1433;" +
     "databaseName=AdventureWorks;integratedSecurity=true;" +
     "encrypt=true; trustServerCertificate=false;" +
     "trustStore=storeName;trustStorePassword=storePassword" +
     "hostNameInCertificate=hostName";

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 056fe1ba-c2ab-8768-e30a-f3a8dcf1bc6c
* Version Independent ID: b0fd3afa-940f-c109-b29b-c6294c3e8a05
* Content: [Connecting with encryption - JDBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-with-ssl-encryption?view=sql-server-ver15)
* Content Source: [docs/connect/jdbc/connecting-with-ssl-encryption.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/connecting-with-ssl-encryption.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@gpigc -- thank you for catching this.  I am updating the article.
