### ISSUE TITLE
YouTube Video is "Private"?

### ISSUE THREAD

**Issue by domcote** [MicrosoftDocs/sql-docs#6727]
Hi, I'm trying to watch the SQL OLTP tuning video on YouTube https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/in-memory-oltp-in-memory-optimization?view=sql-server-ver15#anchorname-17minute-video, but it tells me the video is "private".

How can I watch it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 494b3bdc-5dc6-66a0-3c01-ab53f76539fc
* Version Independent ID: 22627b4b-4877-6aa5-933b-8010e07487a4
* Content: [In-Memory OLTP (In-Memory Optimization) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/in-memory-oltp-in-memory-optimization?view=sql-server-ver15#anchorname-17minute-video)
* Content Source: [docs/relational-databases/in-memory-oltp/in-memory-oltp-in-memory-optimization.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/in-memory-oltp-in-memory-optimization.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@domcote -- thank you for your feedback.  I am investigating this issue.

**Comment by WilliamAntonRohm** [comment]
@domcote -- apologies for the delay in responding.  That video has been retired, and this page as well.  Please see [Overview and Usage Scenarios](https://docs.microsoft.com/sql/relational-databases/in-memory-oltp/overview-and-usage-scenarios) instead.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
