### ISSUE TITLE
Mac M1 - pecl install of sqlsrv and pdo_sqlsrv needs an amendment

### ISSUE THREAD

**Issue by fozzedout** [MicrosoftDocs/sql-docs#6728]
the pecl install will fail on a Mac M1 - I needed these lines before it would compile:

sudo CXXFLAGS="-I/opt/homebrew/opt/unixodbc/include/" LDFLAGS="-L/opt/homebrew/lib/" pecl install sqlsrv
sudo CXXFLAGS="-I/opt/homebrew/opt/unixodbc/include/" LDFLAGS="-L/opt/homebrew/lib/" pecl install pdo_sqlsrv

I hope this helps!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f591be-6564-c959-7a92-6489bdd4f60b
* Version Independent ID: eec72536-eda0-1bc8-a41a-36ed4b9a8883
* Content: [Linux and macOS Installation for the Drivers for PHP - PHP drivers for SQL Server](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15)
* Content Source: [docs/connect/php/installation-tutorial-linux-mac.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/installation-tutorial-linux-mac.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@fozzedout Thanks for the feedback!

We haven't officially added support for the Mac M1 to the PHP drivers, yet, but it's good to know you were able to get it working with minimal changes.

@yitam - just FYI.

**Comment by David-Engel** [comment]
Since this is not a documentation issue and the PHP docs will be updated when we add official support for the Mac M1, I'm closing this issue.

#please-close
