### ISSUE TITLE
Release Name change suggestion

### ISSUE THREAD

**Issue by FHankFreeman2** [MicrosoftDocs/sql-docs#6729]
``
Please change the release name to include the Release Number, Build Number, and Release Date 
Use the format I create as shown in these two examples.

SSMS-Setup-ENU.exe (release file) 
SSMS-Setup-ENU_REL_18.9.1_Build_15.0.18384.0_20-APR-2021.exe
SSMS-Setup-ENU_REL_18.9.2_Build_15.0.18386.0_15-JLY-2021.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@FHankFreeman2 -- thank you for your suggestion.  Please add it here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
