### ISSUE TITLE
Confusing footnote marker

### ISSUE THREAD

**Issue by darksidemilk** [MicrosoftDocs/sql-docs#6734]
When looking at the calculations for worker threads on sql server 2017 on 64bit machines with more the 4 cpus, it looks like the calculation is saying 512^2 i.e. 512 squared. Took a minute to realize it was a footnote reference. Could easily cause someone to grossly misconfigure their worker threads. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90f494da-8888-13e8-0fcc-187242579039
* Version Independent ID: 01bd6647-777e-8c62-f865-6831469b4924
* Content: [Configure the max worker threads Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-max-worker-threads-server-configuration-option?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-the-max-worker-threads-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-max-worker-threads-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@darksidemilk -- JJ, thank you for your feedback, and I see your point of potential confusion.  I am looking into clarifications.

**Comment by WilliamAntonRohm** [comment]
@darksidemilk -- JJ, for consistency with other articles, we'll leave it as-is, trusting to the reader for disambiguation in the subsequent paragraphs.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
