### ISSUE TITLE
This documentation does not apply to Azure SQL!!

### ISSUE THREAD

**Issue by larsholm** [MicrosoftDocs/sql-docs#6742]
"In the Database Properties - database_name dialog box, under Select a page, select Filegroups."

There is no Filegroups page in SQL Management Studio when viewing an Azure SQL Database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4466c524-282b-adc0-d539-3eb85d956597
* Version Independent ID: 08052bb4-d7bb-02ab-6d37-e3fcce20846c
* Content: [Create Partitioned Tables and Indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/partitions/create-partitioned-tables-and-indexes?view=azuresqldb-current)
* Content Source: [docs/relational-databases/partitions/create-partitioned-tables-and-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/partitions/create-partitioned-tables-and-indexes.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by julieMSFT** [comment]
@lardholm I will go ahead with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
