### ISSUE TITLE
Port 464 UDP/TCP required to perform Kerberos Password Change 

### ISSUE THREAD

**Issue by lcanastreiro** [MicrosoftDocs/sql-docs#6744]
Hello All,

Would be possible to review the list of Ports (UDP/TCP) referred in the "Traffic and Ports" section of this page to include the need to consider the port 464 to allow the Kerberos/AD Password Change protocol to be performed:

https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/password-change-mechanisms
https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/config-firewall-for-ad-domains-and-trusts

Thanks for your attention,
Luís.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e93258-ada8-594a-c725-005e5cf94e7c
* Version Independent ID: 995e0663-2823-c258-193a-5904620f805d
* Content: [Deploy in Active Directory mode - SQL Server Big Data Cluster](https://docs.microsoft.com/en-us/sql/big-data-cluster/active-directory-deploy?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/active-directory-deploy.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/active-directory-deploy.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @cloudmelon
* Microsoft Alias: **melqin**

**Comment by WilliamDAssafMSFT** [comment]
Thanks again @lcanastreiro for taking the time to provide this feedback, your suggestions help improve our documentation. This has been updated and a doc update is in flight.
