### ISSUE TITLE
This article is some what confusing for SharePoint Admins

### ISSUE THREAD

**Issue by RVAHaver01** [MicrosoftDocs/sql-docs#6745]
If you are a SharePoint Admin and has little to no experience with C2WTS and Kerberos this article is confusing.  For example, is the Report View web part supported on SharePoint 2019? The article states:
---------------------------------------------------------------------------------------------------
This web part is available for SharePoint 2013 and SharePoint 2016. Both SharePoint 2013 and SharePoint 2016 make use of claims authentication. 
---------------------------------------------------------------------------------------------------

It is not clear about what needs to be done on the SharePoint server(s) vs. the SSRS servers.  In step 2 it states:
---------------------------------------------------------------------------------------------------
Right-click each service account and open the properties dialog. In the dialog click the Delegation tab.

The delegation tab is only visible if the object has a Service Principal Name (SPN) assigned to it. C2WTS does not require an SPN on the C2WTS Account, however, without an SPN, the Delegation tab will not be visible. An alternative way to configure constrained delegation is to use a utility such as ADSIEdit.
---------------------------------------------------------------------------------------------------

There are no steps or good examples on where you need to do this (which box(s)) or how to do it.  (i.e. what machine and account combinations that need to be done. (SharePoint vs. SSRS).  Up farther in the article there are links to how to create SPN's but those are very generic.

**Comment by maggiesMSFT** [comment]
Hi, @RVAHaver01 -- I'm checking on your question about whether the Report Viewer web part is supported on SharePoint 2019. I'll let you know what I find out. Cheers!

**Comment by maggiesMSFT** [comment]
Hi, @RVAHaver01 -- yes, the Report Viewer web part is supported on SharePoint 2019. I'll update the article. 
#please-close
