### ISSUE TITLE
Database Diagrams and Synapse Analytics

### ISSUE THREAD

**Issue by ngorur** [MicrosoftDocs/sql-docs#6747]
Are SSMS Database Diagrams supported with Azure Synapse Analytics / Analytics Platform System (PDW)? The Database Diagrams Folder does not appear in SSMS when connected to a dedicated SQL Pool. This needs to be verified and if its not supported, documentation should be updated to remove Azure Synapse Analytics and Analytics Platform System (PDW)

![image](https://user-images.githubusercontent.com/78385677/131138684-bf920eaf-e9be-43f7-98a4-20a92ea00518.png)

![image](https://user-images.githubusercontent.com/78385677/131139263-b2f4f890-1ffa-4f94-b35d-794b9f3ea8c7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8bc803d-3aee-0e1f-ab64-31c5af48e9f9
* Version Independent ID: 472fcb4b-39c3-72a3-d2af-4eba68b72f04
* Content: [Create a New Database Diagram - Visual Database Tools](https://docs.microsoft.com/en-us/sql/ssms/visual-db-tools/create-a-new-database-diagram-visual-database-tools?view=sql-server-ver15)
* Content Source: [docs/ssms/visual-db-tools/create-a-new-database-diagram-visual-database-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/visual-db-tools/create-a-new-database-diagram-visual-database-tools.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @ngorur for taking the time to provide this feedback, your suggestions help improve our documentation. You are correct that the visual database tools are not available for Azure Synapse Analytics. There is a doc update in flight for this section.
