### ISSUE TITLE
Incorrect Steps

### ISSUE THREAD

**Issue by haverland389** [MicrosoftDocs/sql-docs#6750]
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections?view=sql-server-ver15#Auto

In the steps for "Automatic SPN Registration" it appears that step 3 needs to be corrected. Instead of looking in ADUC for the service account that is running the SQL Server service, you should be looking for the computer object for the SQL server and then add the user object for the service account to the security of the computer object of the SQL server.

Suggested change...

Under Computers, locate SQL Server computer object, and then right-click and select Properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16136000-fc6d-9156-499a-c45bde264bc4
* Version Independent ID: ea9aacfc-8f27-563f-08c8-77ac4e941cff
* Content: [Register a Service Principal Name for Kerberos Connections - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by rothja** [comment]
@haverland389 Thanks, again for the suggestion. @VanMSFT Van, could you please review William's PR that addresses this issue and approve or suggest changes? #reassign:vanmsft
