### ISSUE TITLE
Solution is not really a solution

### ISSUE THREAD

**Issue by TRGibson** [MicrosoftDocs/sql-docs#6758]
[Enter feedback here]
It is great you have a page that talks about this error
but the solution does not tell you how to fix it, thus it is not a solution
This can be better

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 574f74cc-d66b-870e-0117-3efa88a526b1
* Version Independent ID: 34280deb-b64f-4e42-e7dc-814824e630a3
* Content: [Availability replicas not synchronizing data - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/some-availability-replicas-are-not-synchronizing-data?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/some-availability-replicas-are-not-synchronizing-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/some-availability-replicas-are-not-synchronizing-data.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by cawrites** [comment]
@TRGibson thank you for providing this feedback. I will follow-up and provide some additional insight on this topic.

**Comment by cawrites** [comment]
@TRGibson thank you for reaching out. I understand the need of wanting a resolution to a problem. I will check in with our internal resources to determine what we can provide for this issue. Thank you

**Comment by cawrites** [comment]
@Kevin-Farlee do you have any insights on this?

**Comment by cawrites** [comment]
@TRGibson  I am following up with some additional content that is available:  https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/data-synchronization-state-of-some-availability-database-is-not-healthy?view=sql-server-ver15

There is recommended content on the page you referenced that may be beneficial to review.
