### ISSUE TITLE
Command specific to Ubuntu 16.04, should note that users need to change to 18.04 or 20.04

### ISSUE THREAD

**Issue by alex-jitbit** [MicrosoftDocs/sql-docs#6765]
This command `curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list`

Should add a note that if user has a different version of Ubuntu, you may need to change `/ubuntu/16.04/` to reflect the applicable version number. For example `/ubuntu/18.04/` or `/ubuntu/20.04/`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@alex-jitbit -- Alexander, thank you for your feedback.  I am updating this article.

**Comment by VanMSFT** [comment]
@alex-jitbit @WilliamAntonRohm - This note is listed in the doc:

![image](https://user-images.githubusercontent.com/40007119/131709574-44c9c9ea-e28a-498a-94ef-f0561ce53580.png)

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, should I update that note with "18.04" as well?  It seems clear from the context.

**Comment by VanMSFT** [comment]
@WilliamAntonRohm - It's implied in the note that the path needs to be changed, but I guess for further clarification, a note update for 18.04 couldn't hurt. Thanks!

**Comment by alex-jitbit** [comment]
Sorry I missed, the note on the screenshot, false-alarm I guess. Maybe just move it closer to the CLI command.
