### ISSUE TITLE
Incorrect pre-requisites

### ISSUE THREAD

**Issue by lukos** [MicrosoftDocs/sql-docs#6766]
Despite what it says at the top of this article, you cannot setup SQL Server Web or Express editions as a publisher. 

This needs to be made clear because I have wasted a lot of time trying to setup replication only to get an error that I can't.

Standard is over 10x the cost of Web edition so it isn't an option for many people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5638a498-67b5-8e1f-e60d-77e80fb122f9
* Version Independent ID: 22171cdd-c1d9-29cc-a67d-9d5fcfb68d52
* Content: [Tutorial: Configure replication (T-SQL) - SQL Server on Linux](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-replication-tutorial-tsql?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-replication-tutorial-tsql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-replication-tutorial-tsql.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@lukos -- Luke, thank you for bringing this to our attention.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @lukos - Thanks again for this feedback, and sorry for the inconvenience. The editions and supported features are listed in the following doc: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-editions-and-components-2019
