### ISSUE TITLE
Not supported on web/express editions

### ISSUE THREAD

**Issue by lukos** [MicrosoftDocs/sql-docs#6767]
This is another DB article that has not invested the time to clarify which editions this applies to. AG are not available on express or web editions and since standard is 10x more expensive than web, this is not an option for many people.

It should make it clear at the top that it does not apply to all editions, only to Standard and Enterprise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a735a85f-b7c8-ff2e-5cf5-2cc0b45091c5
* Version Independent ID: 84c66851-4167-a286-ddac-e4e057450dab
* Content: [Availability groups for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-overview?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-availability-group-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-availability-group-overview.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@lukos -- Luke, thank you for your feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @lukos - Thanks for submitting this issue. The editions and features that are supported are listed in a specific article: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-editions-and-components-2019.

**Comment by lukos** [comment]
It was not clear that saying "all supported versions" means that someone has to go to the other article, which isn't linked in the page, and look for support. Why does it even say that, it doesn't really mean anything? It's like saying "supported everywhere it is supported". Why not instead say, pre-requisites: Supported SQL Version (see here....) or even pre-requisites: SQL Server Standard or Enterprise Edition?

It seems like a small change to make the docs more usable. Without trying to sound big-headed, I have developed SQL Server (amongst other things) for 20 years, so if I can make the mistake, I would respectfully suggest that others would.

**Comment by VanMSFT** [comment]
Thanks for the feedback, @lukos! We will take your feedback into considerations for doc updates in the future. Version is in reference to the SQL Server version (2017, 2019, etc.), and not the edition. Unfortunately, there are many features and specifying whether an edition for each feature is supported is not something we're specifying on every page at the moment. Since this is not a single page change, as we'll have to take into consideration the whole content set, you can see that it will get convoluted fast.
