### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by CanuckGamer** [MicrosoftDocs/sql-docs#6770]
This page has a grammatical error. The page in part reads, "This example the returns the names of the databases on the linked server."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac4dbeb2-b244-27af-7cfe-4f441ca26d2e
* Version Independent ID: ee282927-e7df-a8d9-da5c-755d0bc41b0f
* Content: [Create Linked Servers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/linked-servers/create-linked-servers-sql-server-database-engine?view=sql-server-ver15)
* Content Source: [docs/relational-databases/linked-servers/create-linked-servers-sql-server-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/linked-servers/create-linked-servers-sql-server-database-engine.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@CanuckGamer -- thank you for your feedback.  I am updating this article.
