### ISSUE TITLE
Add another item to the Restrictions list

### ISSUE THREAD

**Issue by zikato** [MicrosoftDocs/sql-docs#6776]
Query Store also cannot be enabled on tempdb.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37fab3b5-a2f3-5612-06e2-01e0406a615d
* Version Independent ID: 2daa00e0-8234-bf26-13c0-8d5200a1f4a5
* Content: [tempdb database - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/tempdb-database?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/tempdb-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/tempdb-database.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@zikato -- Tom, thank you for your feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @zikato for the feedback and taking the time to open this issue. This is true, we have this fact documented properly in the [Query Store overview article](https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-ver15#:~:text=query%20store%20cannot%20be%20enabled%20for%20the%20master%20or%20tempdb%20databases.)
