### ISSUE TITLE
Insert table data type with only pure JDBC interface (and no explicit cast)

### ISSUE THREAD

**Issue by lapo-luchini** [MicrosoftDocs/sql-docs#6785]
This example code in the page is fairly difficult to use in JBoss (due to multiple wrapping of statement, which breaks the explicit cast):

```Java
SQLServerPreparedStatement pStmt =
    (SQLServerPreparedStatement) connection.prepareStatement("INSERT INTO dbo.Categories SELECT * FROM ?");  
pStmt.setStructured(1, "dbo.CategoryTableType", sourceTVPObject);  
pStmt.execute(); 
```

after many tries and some reading of the sources, I managed to solve using the following, which is very simple and needs no cast at all:

```Java
PreparedStatement pStmt =
    connection.prepareStatement("INSERT INTO dbo.Categories SELECT * FROM ?");  
sourceTVPObject.setTvpName("dbo.CategoryTableType");
pStmt.setObject(1, sourceTVPObject);  
pStmt.execute(); 
```

It's true that this way cannot be used with `ResultSet` (which can't hold the `tvpName`), but works wonderfully (and is much easier / more portable) when using `SQLServerDataTable` type and I think it would be a nice alternative to suggest in the official documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02793fc-aa1a-d276-af3b-654f30f95b5e
* Version Independent ID: 258ace1b-fc45-bb24-d5c2-c117ad14e868
* Content: [Using table-valued parameters - JDBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-table-valued-parameters?view=sql-server-ver15#passing-a-table-valued-parameter-as-a-sqlserverdatatable-object)
* Content Source: [docs/connect/jdbc/using-table-valued-parameters.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/using-table-valued-parameters.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@lapo-luchini -- Lapo, thank you for your suggestion.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@lapo-luchini -- Lapo, my apologies for the delay here.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
I added a second example to the page using the suggested alternatives of setTvpName and setObject.

Thanks,
David

#please-close
