### ISSUE TITLE
Troubleshooting - Additional information about rpm preinstallation check failures. 

### ISSUE THREAD

**Issue by Awdball** [MicrosoftDocs/sql-docs#6787]
For RHEL and Oracle Linux installations:

The rpm preinstall scripts include a check for the driver via the following command:
	`"odbcinst -q -d -n "ODBC Driver $1 for SQL Server" &>/dev/null || exit_code=$?"`

And if the driver is present, installation fails with:
	`"Installation failed, ODBC Driver $1 for SQL Server detected!"`

From just the output alone, it's not necessarily clear how the preinstallation script came to that conclusion so the end-user can fix the condition.

I recommend adding the odbcinst preinstallation checks (at least for Redhat) to the troubleshooting steps in the article on the condition they receive the "Installation Failed" message.

Ideally, yum/rpm should prevent the condition from happening, but if it does, it would be nice for the end-user to know what's being checked and how to fix it without having to read the rpm scripts.

For reference, the rpm scripts for this package can be reviewed with:
`rpm -qp --scripts msodbcsql17-17.8.1.1-1.x86_64.rpm`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@Awdball -- thank you for your considered feedback.

@David-Engel -- please look into this issue.

**Comment by rwestMSFT** [comment]
@Awdball Please create a pull request with this change.

**Comment by David-Engel** [comment]
I added a paragraph to the troubleshooting section. It should appear in a few hours.

Thanks,
David

#please-close
