### ISSUE TITLE
Forums have moved...

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/sql-docs#6792]
In section

https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is-azure-data-studio?view=sql-server-ver15#-get-help-for-sql-tools

the link to the SQL Client Tools Forum 

https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqltools&filter=alltypes&sort=lastpostdesc

takes you to the forum, which says that it has migrated to Microsoft Q&A. This looks like the appropriate link that should be used instead:

https://docs.microsoft.com/en-us/answers/products/sql-server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 962f065e-a643-85e1-5e90-c80548681195
* Version Independent ID: aad000f8-a420-43fd-3031-c19427c38c0f
* Content: [What is Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is-azure-data-studio?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/what-is-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/what-is-azure-data-studio.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@GaTechThomas -- Thomas, thank you for catching this.  I am updating the article.
