### ISSUE TITLE
Documentation points to outdated link

### ISSUE THREAD

**Issue by jasonhorner** [MicrosoftDocs/sql-docs#6800]
this pages contains an outdated link (SQL 2012):
https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/ee210549(v=sql.110)

I think many of these restrictions have been fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d185ed-733f-2f63-2c28-e63670053b7d
* Version Independent ID: eebf764e-3c26-00f1-c627-03098efe1743
* Content: [Export a Data-tier Application - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/export-a-data-tier-application?view=sql-server-ver15)
* Content Source: [docs/relational-databases/data-tier-applications/export-a-data-tier-application.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/export-a-data-tier-application.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @JasonHorner. This is an article in the previous versions archive, not surprised it is out of date. It is linked though in current docs, we'll see about getting modern articles linked instead. Appreciate the time to point this out and create the issue.  We'll contact you if we need further information, and you'll receive an email message each time we mention you in a comment. 
	
Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by dzsquared** [comment]
#assign:dzsquared

**Comment by WilliamDAssafMSFT** [comment]
Another issue has been created to get this resolved. Thanks @jasonhorner for the heads up here.
