### ISSUE TITLE
update docs for ports clarity

### ISSUE THREAD

**Issue by pmpopovichjr** [MicrosoftDocs/sql-docs#6808]
Hi, 

following this link to setup a single node bdc:
https://github.com/microsoft/sql-server-samples/tree/master/samples/features/sql-big-data-cluster/deployment/kubeadm/ubuntu-single-node-vm

that worked which lead me to sample data here: 
https://github.com/microsoft/sql-server-samples/tree/master/samples/features/sql-big-data-cluster

which lead me to this docs page I am making the pull request on

https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-load-sample-data?view=sql-server-ver15

in following the setup guide for the single node and the docs page for the sample data load I ended up running this command

./bootstrap-sample-db.sh mssql-cluster 192.168.1.128 192.168.1.128 --install-extra-samples 31433 30443

when i used this block
Run the bootstrap script.

Bash
./bootstrap-sample-db.sh <CLUSTER_NAMESPACE> <SQL_MASTER_ENDPOINT> <KNOX_ENDPOINT>

notice how my string (ignore the --install extra samples) needed the ports to be thrown onto the script which isn't mentioned in the page. It took me a while to figure it out, might not be the worst thing to update to mention them to save some folks some trouble.

Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16adfeea-f75b-bd99-b9ae-44fe77e9c8d1
* Version Independent ID: 2c6e8c0d-4764-e6a1-e20c-8014a06264dd
* Content: [Load sample data - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-load-sample-data?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/tutorial-load-sample-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/tutorial-load-sample-data.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@pmpopovichjr -- Paul, thank you for your feedback and resolution.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by pmpopovichjr** [comment]
I'd also add adding to the docs page the basic auth example for a single VM non domain joined. That took me a hot minute to figure out too. I saw the ports listed in the script upon second review but there was some weirdness where a curl failed with a : error and only worked when I plopped them into the script itself.

**Comment by WilliamDAssafMSFT** [comment]
@pmpopovichjr After reviewing the [sample script](https://raw.githubusercontent.com/Microsoft/sql-server-samples/master/samples/features/sql-big-data-cluster/bootstrap-sample-db.sh), it appears the default ports are in use, and should not have been necessary to provide in the call ./bootstrap-sample-db.sh. Do you have any more information on the error raised when the default ports were not provided, or any other repro information? You may also want to consider opening a support ticket if you'd like more interactive troubleshooting.

**Comment by pmpopovichjr** [comment]
Morning, I just ran through this setup on a new build, didnt specify the
ports (but added the extra sample command) and it worked as expected. THe
first time, I didnt use extra sample, and needed the ports. Go ahead and
close this, as I can't repro it.

Thanks,
Paul
