### ISSUE TITLE
Unable to locate package msodbcsql17 and mssql-tools for Debian Bullseye

### ISSUE THREAD

**Issue by vmalakhin** [MicrosoftDocs/sql-docs#6817]
Hello,

I'm wondering if there's any plan to introduce support of recently released Debian Bullseye? It seems that packages msodbcsql17 and mssql-tools missing and there's no mention of Bullseye under https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md#debian17

I've tried following:

```
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
ACCEPT_EULA=Y apt-get -yqq install -y msodbcsql17
```

But no luck.

Thanks, Vasily

**Comment by WilliamAntonRohm** [comment]
@vmalakhin -- Vasily, thank you for your feedback.  Please see previous issue #6804.
