### ISSUE TITLE
Insufficient information provided on what specific SPNs need to be created.

### ISSUE THREAD

**Issue by RVAHaver01** [MicrosoftDocs/sql-docs#6849]
Under this section "Resolving Kerberos Authentication Errors When Connecting to a Report Server" please provide some examples on what specific SPNs need to be created. I had to open a MS Case just to find out I needed these specific ones:

```
SETSPN -S HTTP/<SSRS Server FDQN> <SSRS Service Account>
SETSPN -S HTTP/<host header for Report server web site> <SSRS Service Account>
SETSPN -S HTTP/<SharePoint Server FDQN> <SharePoint Application Pool Account>
SETSPN -S HTTP/<host header for SharePoint site>  <SharePoint Application Pool Account>
SETSPN -S HTTP/Dummy <Claims to Windows Taken Service Account>
```

**Comment by WilliamAntonRohm** [comment]
@RVAHaver01 -- thank you for your feedback regarding [this article](https://docs.microsoft.com/en-us/sql/reporting-services/security/configure-windows-authentication-on-the-report-server?view=sql-server-ver15#proxyfirewallRSWindowsNegotiate).

@maggiesMSFT -- please look into this issue.

**Comment by maggiesMSFT** [comment]
Thanks for the suggestion, @RVAHaver01! Article update should be live today, Sept 6, 23.

**Comment by maggiesMSFT** [comment]
#please-close
