### ISSUE TITLE
Script correction proposal - switched IDs

### ISSUE THREAD

**Issue by paulusvo** [MicrosoftDocs/sql-docs#6851]
Both JOIN statements currently contain switched targets:
(I indicated the switched parts in bold italic)

SELECT	roles.principal_id							AS RolePrincipalID
	,	roles.name									AS RolePrincipalName
	,	database_role_members.member_principal_id	AS MemberPrincipalID
	,	members.name								AS MemberPrincipalName
FROM sys.database_role_members AS database_role_members  
JOIN sys.database_principals AS roles  
    ON database_role_members.**_role_**_principal_id = roles.principal_id  
JOIN sys.database_principals AS members  
    ON database_role_members.**_member_**_principal_id = members.principal_id;  
GO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d95c4e-dfbb-ec5a-7df9-8a8d33be5b83
* Version Independent ID: a35a9368-4e76-6d55-7e90-34e925b34dd7
* Content: [Database-Level Roles - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/authentication-access/database-level-roles.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/database-level-roles.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@paulusvo -- thank you for finding this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please review [private PR 20301](https://github.com/MicrosoftDocs/sql-docs-pr/pull/20301).
