### ISSUE TITLE
Suggestion: Alternate Data Streams

### ISSUE THREAD

**Issue by grahamlower** [MicrosoftDocs/sql-docs#6857]
SQL Server should be updated to support alternate data streams, which allows alternate datasets to be returned if enabled, otherwise not sent.  The common use for alternate streams would be debugging, QA, and logging.  Developers could seed debugging queries directly into the code, enabling and disabling without the need to recompile or distribute. 

When enabled, query results also include metadata to indicate which stream the results belong to, where the stream is an INT.    Clients are responsible for interpreting results as appropriate.

A connection option should enable this feature, as well as a per-stream enabling.  e.g. ;USE ALTSREAM.  Specific streams also be enabled: e.g. USE ALTER STREAM:1,4,10.  Stream 0 would be permeated enabled. 

Within a session, data sent to streams other than 0 should be able to be suppressed.  e.g. SET ALTSTREAM OFF, or on a stream by stream basis: SET ALTSTREAM 2 OFF.  Metadata on the stream would still be included, but only data for stream 0 should be sent. The ability to toggle this state would be permissions-based.  By default, if the feature is enabled and the connecting user has permissions it would be to ON, otherwise OFF.

CRUD statements would be extended to support the selection of the stream, defaulting to 0 when not supplied.   The EXECUTE statement would also be extended to support the selection of the default stream during the execution of the procedure. One possible way may be through the use of a query hint/execute option: e.g. USE STREAM 2.   The ability to not execute a statement when alternate streams are not available should exist:  USE STREAM 2 ONLY WHEN AVAILABLE.  Any stream hints/options would be ignored when outputting to a table (of any sort).

**Comment by WilliamAntonRohm** [comment]
@grahamlower -- thank you for your considered and detailed feedback.  Please add these suggestions here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by grahamlower** [comment]
@WilliamAntonRohm I'd love to, but it seems there has been an update recently and it redirects to a generic Azure Feedback page (https://azure.microsoft.com/en-us/feedback/) with no obvious way to actually give feedback or suggestions.  Any pointers? 

As an aside: your comment suggests this is not the preferred place for feedback and suggestions, so I want to point out that  https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-ver15 links here to share "an idea, a suggestion, feedback, anything!"  It may be worth following up on that if there is such a preference.

**Comment by WilliamAntonRohm** [comment]
@grahamlower -- thank you for your follow-up & researches.  I'm looking into the current suggestion link.

**Comment by WilliamAntonRohm** [comment]
@grahamlower -- thank you for your patience.  There's a new place for SQL feedback:
- [SQL forum](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
