### ISSUE TITLE
AUTO_UPDATE_STATISTICS Option recompilation behavior

### ISSUE THREAD

**Issue by Ventilios** [MicrosoftDocs/sql-docs#6867]
I'm missing an explanation, or remark, related to the recompilation behavior when _AUTO_UPDATE_STATISTICS_ is turned _off_. Something that can be missed for example is manually updating statistics will not result into the recompilation of a query. 
Can an explanation or note be added, including any remark that can be made related to compatibility level behavior in combination with this setting? 

From my understanding (source: _page 728, SQL Internals 2012, Kalen Delaney_): "_If automatic updates of statistics defined on a table or indexed view are disabled - All plan optimality-related recompilations cause by those indexes or statistics will stop._". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e5062c-ab80-eace-5cbb-8868c17014c3
* Version Independent ID: 7bcb85b7-ee68-ae1c-5385-91f6db828c06
* Content: [Statistics - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/statistics/statistics?view=sql-server-ver15)
* Content Source: [docs/relational-databases/statistics/statistics.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/statistics/statistics.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
@Ventilios Thanks for taking the time to create this issue. I have an update in progress to elaborate more on the behavior of AUTO_UPDATE_STATISTICS = OFF on the Statistics page. I think you'll find more clarification on this condition in https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options?view=sql-server-ver15#auto_update_statistics, where OFF "specifies that Query Optimizer doesn't update statistics when they're used by a query. Query Optimizer also doesn't update statistics when they might be out-of-date. Setting this option to OFF can cause suboptimal query plans and degraded query performance."
