### ISSUE TITLE
Synapse Dedicated Pool behavior

### ISSUE THREAD

**Issue by balukes** [MicrosoftDocs/sql-docs#6871]
The TRIM command with 'FROM' does not work with Synapse Dedicated Pools. In the 'applies to' it mentions Synapse but does not clarify serverless vs dedicated. I have verified this works in serverless. 

Msg 103010, Level 16, State 1, Line 5
Parse error at line: 1, column: 21: Incorrect syntax near 'FROM'.

**Comment by WilliamAntonRohm** [comment]
@balukes -- thank you for your feedback.  Which docs.microsoft.com article are you following?

**Comment by balukes** [comment]
https://docs.microsoft.com/en-us/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@balukes -- thank you for your followup.

@julieMSFT -- please look into this issue.

**Comment by julieMSFT** [comment]
#reassign:mstehrani

**Comment by mstehrani** [comment]
Hi @balukes - TRIM is supported in Synapse Analytics but to a different extent (this is why it still is listed under 'Applies to'). For these differences in support, you'll see that the [syntax block](https://docs.microsoft.com/en-us/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver15#syntax) contains a definition for SQL Server syntax, and another block for the specific Synapse-supported syntax. Here we stats that only TRIM is supported and not TRIM ... FROM.

#close
