### ISSUE TITLE
SQL Server and 40-bit crypto

### ISSUE THREAD

**Issue by x509cert** [MicrosoftDocs/sql-docs#6883]
Can we remove all references to 40-bit crypto? I hope at this stage that SQL Server does not allow it!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa20275-e415-5531-3ef4-7472d859753b
* Version Independent ID: cc1346a6-9336-91ba-bcff-9fff79847c35
* Content: [Enable encrypted connections - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
@x509cert - Hi Michael, thanks for bringing this issue up. Let me check with the relevant Product Team member to get confirmation.

**Comment by pmasl** [comment]
SQL Server still ships with TLS1.0 support (not recommended) so, no, it can't be removed. Hence the warning.

**Comment by VanMSFT** [comment]
Thanks, @pmasl!

Discussed internally, and closing issue.
