### ISSUE TITLE
msodbcsql for Debian 11 (bullseye)

### ISSUE THREAD

**Issue by marhoy** [MicrosoftDocs/sql-docs#6884]
The `stable` release of Debian 11 has been out for a while, but there is still no `msodbcsql` package available?
Any ETA on that?

https://packages.microsoft.com/debian/11/prod/pool/main/m/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
We can't make any public promises about future releases, but if you look at the release notes for past releases, you can see that support for new Debian/Ubuntu/Red Hat/SUSE/Apple OS versions have historically been added to the ODBC driver GA release following the GA release of those OS versions. You can also see the historical 6-month ODBC GA release cadence of Jan/July.

Regards,
David

#please-close
