### ISSUE TITLE
MySQL version support

### ISSUE THREAD

**Issue by lionelpenuchot** [MicrosoftDocs/sql-docs#6885]
According to https://docs.microsoft.com/en-us/azure/azure-sql/migration-guides/database/mysql-to-sql-database-guide?source=docs#prerequisites only MySQL 5.6 and 5.7 are supported. This looks like a doc bug:
Verify that your source environment is supported. Currently, MySQL 5.6 and 5.7 are supported.

Shouldn't it be corrected to:
Verify that your source environment is supported. Currently, MySQL 5.6 and higher are supported.

**Comment by WilliamAntonRohm** [comment]
@lionelpenuchot -- Lionel, thank you for your feedback.

@cawrites -- Cheryl, please look into this issue.

**Comment by MikeRayMSFT** [comment]
@mokabiru  - please review.

**Comment by WilliamAntonRohm** [comment]
#reassign:rajpo

**Comment by rwestMSFT** [comment]
The article currently states:

> Verify that your source environment is supported. Currently, MySQL 4.1 and above is supported.

I am closing this issue is resolved.
