### ISSUE TITLE
select gives wrong result in case of comparing datetime with datetime2 column

### ISSUE THREAD

**Issue by mhandsteiner** [MicrosoftDocs/sql-docs#6896]
Steps to reproduce:
Table TEST with columns LOG_ID decimal(16), LOG_TIME1 datetime, LOG_TIME2 datetime2.

Insert a row with {LOG_ID=1, LOG_TIME1=2021-10-01 11:44:31.857, LOG_TIME2=2021-10-01 11:44:31.857}

Selecting this row again over jdbc or DBeaver delivers exact these data again.

But the following select does not deliver a row
select * from TEST where LOG_TIME1 = LOG_TIME2
[]

The problem is, that LOG_TIME1 is casted to datetime2, but not rounded to milliseconds...

To get the internal representation of the datetime columns, without getting an influence of the jdbc driver, I used the following select:

select LOG_ID, concat('', cast(LOG_TIME1 as datetime2)) CAST_LOG_TIME1, concat('', LOG_TIME2) CAST_LOG_TIME2 from TEST_UPDATE

The result is:
{LOG_ID=1, LOG_TIME1=2021-10-01 11:44:31.8566667, LOG_TIME2=2021-10-01 11:44:31.857}

This shows, that casting "2021-10-01 11:44:31.857" datetime to datetime2 results in: "2021-10-01 11:44:31.8566667".

So datetime is not able to store such an accuracy. It would be best to round the casted result to Milliseconds, to avoid rounding problems...
 

Microsoft JDBC Driver 9.2 for SQL Server [9.2.0.0]
Database: Microsoft SQL Server [15.00.2000
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64) 
	Sep 24 2019 13:48:23 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19042: ) (Hypervisor)
]

**Comment by WilliamAntonRohm** [comment]
@mhandsteiner -- thank you for your feedback.  I am looking into this issue.
