### ISSUE TITLE
Wrong reference to the service account instead of the machine account

### ISSUE THREAD

**Issue by ibawwad** [MicrosoftDocs/sql-docs#6910]
[Enter feedback here]
I tried to follow the steps below in order to automatically update the SPN, it turns out the security changes needs to be done on the Server/computer object not actually on the Sql Server service startup account as mentioned. The instructions were confusing, even the mentioned setting 'Read ServiceprincipalName' doesn't exist except for a computer object.
//
On the Domain Controller machine, start Active Directory Users and Computers.

1. Select View > Advanced.

2. Under Users, locate SQL Server startup account, and then right-click and select Properties.

3. Select the Security tab and click Advanced.

4. In the list, if SQL Server startup account is not listed, click Add to add it and once it is added do the following:

a. Select the account and click Edit.

b. Under Permissions select Validate Write servicePrincipalName.

d. Scroll down and under Properties select:

Read servicePrincipalName

Write servicePrincipalName

e. Click OK twice.

Close Active Directory Users and Computers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16136000-fc6d-9156-499a-c45bde264bc4
* Version Independent ID: ea9aacfc-8f27-563f-08c8-77ac4e941cff
* Content: [Register a Service Principal Name for Kerberos Connections - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@ibawwad -- Ibrahim, thank you for your considered feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@ibawwad,

Apologizes for the delayed response.

However, I assure you that we have already split the UI instructions based on " SQL" versions.

Depending on what version you select in the TOC, the set of steps d change with how to manage certs for SQL Server. 

![image](https://user-images.githubusercontent.com/22989000/141846865-9c058d68-d8d7-4b97-bdb4-b0000ff094a6.png)

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site.

**Comment by markingmyname** [comment]
#please-open

**Comment by ibawwad** [comment]
@markingmyname Hello Mark,
This was not actually related to any SQL server version, the instructions were about the AD account settings!

**Comment by markingmyname** [comment]
The SPN is only useful if you create it for the SQL Server Service Account.

If the admin happens to be using a computer account, such as a default without specifying the account they want to use for SQL Server, then the SPN needs to be registered under the computer account object.

However, that's not going to work if the service account is not under a computer account

To automatically have the SQL Server Service Account register/unregister an SPN, the account used will need read/write servicePrincipalName permissions

Which is usually only granted to Admin roles, but needs to be specified manually if the service account is not an admin.

**Comment by markingmyname** [comment]
However, I will add that I will review the content again in a few weeks if I feel there are any updates to make.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site.
