### ISSUE TITLE
The result not matched with the sql query.

### ISSUE THREAD

**Issue by Arnab-Developer** [MicrosoftDocs/sql-docs#6921]
I found that the result is not matching with the query given in the document.

https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-ver15#convert-json-collections-to-a-rowset

The query:

```sql
DECLARE @json NVARCHAR(MAX);
SET @json = N'[  
  {"id": 2, "info": {"name": "John", "surname": "Smith"}, "age": 25},
  {"id": 5, "info": {"name": "Jane", "surname": "Smith", "skills": ["SQL", "C#", "Azure"]}, "dob": "2005-11-04T12:00:00"}  
]';

SELECT *  
FROM OPENJSON(@json)  
  WITH (
    id INT 'strict $.id',
    firstName NVARCHAR(50) '$.info.name',
    lastName NVARCHAR(50) '$.info.surname',  
    age INT,
    dateOfBirth DATETIME2 '$.dob',
    skills NVARCHAR(MAX) '$.info.skills' AS JSON
  )
OUTER APPLY OPENJSON(skills)
  WITH (skill NVARCHAR(8) '$');
```

The result:

![image](https://user-images.githubusercontent.com/3396447/136768940-5900be30-b98c-41eb-aee9-81be0cadcf81.png)

**Comment by WilliamAntonRohm** [comment]
@jovanpop-msft -- Jovan, please review Arnab's PR https://github.com/MicrosoftDocs/sql-docs/pull/6922.
