### ISSUE TITLE
Wrong example command to 'GRANT SELECT ON Security.tvf_securitypredicate'

### ISSUE THREAD

**Issue by StefH** [MicrosoftDocs/sql-docs#6928]
For example `A`:

The example code:
```  sql
GRANT SELECT ON Security.tvf_securitypredicate TO SalesRep1;` is repeated twice.
```

It should be SalesRep1 and SalesRep2, so
``` sql
GRANT SELECT ON Security.tvf_securitypredicate TO SalesRep1;
GRANT SELECT ON Security.tvf_securitypredicate TO SalesRep2;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c96c3ee-5443-004f-d189-3701f8bef6c9
* Version Independent ID: efcc952b-eadb-4579-54c7-00da3bc107ae
* Content: [Row-Level Security - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/row-level-security?view=sql-server-ver15&viewFallbackFrom=sql-server-previousversions)
* Content Source: [docs/relational-databases/security/row-level-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/row-level-security.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please review [private PR 20496](https://github.com/MicrosoftDocs/sql-docs-pr/pull/20496).
