### ISSUE TITLE
How to use SSMS debugger with version > 18.4 ?

### ISSUE THREAD

**Issue by puschie286** [MicrosoftDocs/sql-docs#6931]
Hi, im looking for the SSMS debugger - the documentation doesnt mentionted that it was removed in 18.0

So whats the current state ? 
the newest stuff i found was from a 2019 stackoverflow question, this mentioned that is was removed in 18.0 with no replacement....
so with SSMS > 18.4 - how do i debug TSQL scripts / queries ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b6bda12-8647-257a-0cff-3e1753f24ef1
* Version Independent ID: 88cf6bd4-b860-e79e-50eb-6d7b6c5d0f45
* Content: [Transact-SQL debugger - T-SQL debugger](https://docs.microsoft.com/en-us/sql/ssms/scripting/transact-sql-debugger?view=sql-server-ver15)
* Content Source: [docs/ssms/scripting/transact-sql-debugger.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/transact-sql-debugger.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by abdi-1989** [comment]
Iiiytt
