### ISSUE TITLE
Release Notes for Report Viewer are very outdated

### ISSUE THREAD

**Issue by OronDF343** [MicrosoftDocs/sql-docs#6932]
https://docs.microsoft.com/en-us/sql/reporting-services/application-integration/release-notes-ssrs-application-integration?view=sql-server-ver15

The article has only up to 150.1427.0 from 2020-12-01

Missing info for the following:

| Version | Release Date |
|--------|-------|
| 150.1440.0 | 2021-02-18 |
| 150.1449.0 | 2021-03-25 |
| 150.1484.0 | 2021-09-27 |

Is there a better source of up to date info available?

**Comment by rwestMSFT** [comment]
It appears this page has been updated.

#please-close

**Comment by jaredthirsk** [comment]
@RhysSchmidtke there have been 3 new releases, but no update to the release notes:


<html>
<body>


150.1586.0 | 2,549 | 9 days ago 
-- | -- | -- 
150.1585.0 | 883 | 12 days ago |  
150.1576.0 | 14,321 | 2 months ago


</body>
</html>

**Comment by jaredthirsk** [comment]
> Please open a new issue.

@rwestMSFT 
If this is a recurring issue, shouldn't you guys change your process?  Surely, waiting for a rando to find his way to the gitlab issues page and open an issue isn't part of your process?

**Comment by rwestMSFT** [comment]
@jaredthirsk If you open a new issue, it will get processed by our reviewers, who will triage it, and then it will be seen by the owner of the article. That is our process.

**Comment by WilliamAntonRohm** [comment]
@jaredthirsk -- Jared, thank you for your follow-up.  I have created a new issue #9152 to restart the update process.

@rwestMSFT -- Randolph, thank you for your clarifications above.  Rhys is no longer assignable in GitHub, so I assigned the new issue to you.  If someone else is a more suitable author, please reassign it to them.

**Comment by jaredthirsk** [comment]
@WilliamAntonRohm  @rwestMSFT 

The release notes are again out of date.  They are missing 150.1620.0, released 3 months ago on 2024-01-18.

**Comment by rwestMSFT** [comment]
I am locking this thread.

> @jaredthirsk If you open a new issue, it will get processed by our reviewers, who will triage it, and then it will be seen by the owner of the article. That is our process.
