### ISSUE TITLE
Script task - Only supports standard .NET Framework APIs?

### ISSUE THREAD

**Issue by sqlgreen** [MicrosoftDocs/sql-docs#6933]
It says the Script task _Only supports standard .NET Framework APIs_, so clearly we are talking about ".NET Framework", and the _standard_ APIs are a subset, but what is that subset?

Are we by any chance talking about ".NET Standard", which I think shouldn't really be labelled as ".NET Framework"

I refer to the Microsoft .NET terms defined here https://dotnet.microsoft.com/learn/dotnet/what-is-dotnet-framework, but they may have changed after lunch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bab227c-0449-76f4-b232-96b9f0b658dd
* Version Independent ID: df73cb55-55e4-8e76-2943-44168d589624
* Content: [Limitations and known issues for SSIS on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-ssis-known-issues?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-ssis-known-issues.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-ssis-known-issues.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @lrtoyou1223
* Microsoft Alias: **lle**

**Comment by WilliamAntonRohm** [comment]
@sqlgreen -- Darren, thank you for your feedback.

@lrtoyou1223 -- Leo, please look into this issue.

**Comment by rwestMSFT** [comment]
Hi @sqlgreen. The article says "standard .NET Framework APIs", meaning the standard APIs that are included in .NET Framework.

#please-close
