### ISSUE TITLE
Does the SQL Agent service account really need to be sysadmin ?

### ISSUE THREAD

**Issue by pierrejeandev** [MicrosoftDocs/sql-docs#6935]
About the SQL Agent service account, the documentation says: 
_The account must be a member of the sysadmin fixed server role._

But when installing SQL Server with a domain service account instead of the default local account, the SQL agent service account is not given the sysadmin role. The account is not even added as a user to SQL Server.
The same thing also happen when changing the service account with the SQL Server Configuration tool.
Still every thing seem to work as expected.

So my question is : Does the SQL Agent service account really need to be sysadmin ?

Or is there some other magic trick that gives the SQL Agent service account sysadmin rights even if does not exists as a user in SQL Server ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b65d5830-880e-63d9-ea1a-3ce1439cbef1
* Version Independent ID: 0695525c-2778-e73e-b274-764127d1096c
* Content: [Select an Account for the SQL Server Agent Service - SQL Server Agent](https://docs.microsoft.com/en-us/sql/ssms/agent/select-an-account-for-the-sql-server-agent-service?view=sql-server-ver15)
* Content Source: [docs/ssms/agent/select-an-account-for-the-sql-server-agent-service.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/select-an-account-for-the-sql-server-agent-service.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@pierrejeandev

Thanks for this question.

I apologize for the confusion and the delayed response.

I am confirming that your findings are correct.

**Comment by markingmyname** [comment]
@pierrejeandev 

Apologizes for this info.

You're correct there is no reason to have the account be a sysadmin.

I will make that change.

thank you.

**Comment by markingmyname** [comment]
PR to address this - https://github.com/MicrosoftDocs/sql-docs-pr/pull/20652
