### ISSUE TITLE
Mysterious `sp_batch_params` is in the documentation (and SSMS IntelliSense), yet does not appear to be in SQL Server

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#6946]
The documentation page for `sp_batch_params` indicates that it exists in all supported versions, but I can't find it in any. 

**sp_batch_params (Transact-SQL)**
https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-batch-params-transact-sql

According to the documentation, the following should work:

```sql
DECLARE @Def NVARCHAR(MAX);
SET @Def = OBJECT_DEFINITION(OBJECT_ID(N'sp_configure'));

PRINT @Def;

EXEC sp_batch_params @Def;
```

Yet the `EXEC` merely returns the following error:

> Msg 2812, Level 16, State 62, Line XXXXX  
> Could not find stored procedure 'sp_batch_params'.

This proc does not show up where it should (based on the documentation):

```sql
SELECT *
FROM sys.all_objects
WHERE [name] LIKE N'%batch%' COLLATE Latin1_General_100_CI_AS_SC
-- 12 rows (SQL Server 2012); 13 rows (SQL Server 2017 & 2019)
```

```sql
SELECT *
FROM sys.all_objects
WHERE [name] LIKE N'%params%' COLLATE Latin1_General_100_CI_AS_SC
-- 8 rows (SQL Server 2012, 2017 & 2019)
```

I can't find any trace of this, even when starting SQL Server in single user admin mode (i.e. `-m` command-line switch) and looking in the Resource DB:

```sql
USE [mssqlsystemresource];

SELECT *
FROM  sys.all_sql_modules asm
WHERE asm.[definition] LIKE N'%batch[_]params%' COLLATE Latin1_General_100_CI_AS_SC
```

In the Resource DB, the two queries above from `sys.all_objects` return 15 rows each (SQL Server 2017), but still none of them are for `sp_batch_params`.

The history shows that it has been updated several times since 2017-03-16, but only for general documentation formatting / meta-data updates (as far as I can tell):

https://github.com/MicrosoftDocs/sql-docs/commits/live/docs/relational-databases/system-stored-procedures/sp-batch-params-transact-sql.md

Is this something that has been removed and should likewise be removed from SSMS IntelliSense and the documentation?

**Comment by WilliamAntonRohm** [comment]
@srutzky -- Hi Solomon!  Thank you again for your contributions to keeping our documentation accurate.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@srutzky 

Thank you for this suggestion.

However, I have no issues with these queries.

I am running them on a SQL Server 2019 version in SSMS.

May I ask why the version of SQL Server you are running it on, please?

**Comment by srutzky** [comment]
Hi @markingmyname . I tried on SQL Server 2012, 2017, and 2019 (just now; not sure if I tried additional versions when I first posted this). Only the first query above will return an error, but it will also produce output. Comment out the `PRINT` statement to make it clearer between error and success.

**Comment by markingmyname** [comment]
@srutzky 

so to be clear, you are still getting the error which each of these versions even after commenting out the "print" command?

**Comment by srutzky** [comment]
@markingmyname 

> so to be clear, you are still getting the error which each of these versions even after commenting out the "print" command?

Yes, I get the error on each version. The error is:

> Could not find stored procedure 'sp_batch_params'.

**Comment by markingmyname** [comment]
@srutzky,

It seems we have deprecated this SPROC.

I am investigating further for more details.

thank you for your patience.

**Comment by srutzky** [comment]
@markingmyname Not deprecated; removed entirely. I tested more versions and it's in 2005, 2008, and 2008 R2. It was removed in 2012 and has not been seen since. It _should_ have been added to the following page but never was (clearly):

[Discontinued Database Engine Functionality in SQL Server 2012](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/ms144262(v=sql.110))

And, the doc page itself should have been removed at that time as well (when 2012 was released).

I did not test 7.0 or 2000. I figure at this point, whatever version it was deprecated in (no later than 2008 R2) is a moot point now.

**Comment by markingmyname** [comment]
@srutzky,

Apologizes again.

I got more info to clarify why the SPROC (SP) is not working.

That SPROC is provided for backward compatibility only. So it wasn't necessarily deprecated just not used directly.

All the new [SQL Server drivers use sp_describe_undeclared_parameters](https://docs.microsoft.com/sql/relational-databases/system-stored-procedures/sp-describe-undeclared-parameters-transact-sql).
 
Generally, applications or customers don't invoke this SPROC directly.

We haven't deprecated this SPROC specifically since older drivers are using it.

As such, I am going to update the sp_batch_params article to reflect this new info.

The article should be updated by the end of the week.

Thank you for your patience.

**Comment by srutzky** [comment]
@markingmyname Ok, so can we agree that `sp_batch_params` does not exist anymore? It is no longer anywhere in SQL Server, deprecated or not, used for backwards-compatibility or not.

The live documentation appears to not concern any version prior to SQL Server 2016. Since this proc was removed as of SQL Server 2012, wouldn't it make sense to update the "Features discontinued in SQL Server 2012" page and then remove the `sp_batch_params` page (but only from the live stuff; should still be accessible under "previous versions")? I'm not sure of the point of having a page for a proc that nobody would ever be able to find no matter how hard they tried.

**Comment by markingmyname** [comment]
I created this PR - https://github.com/MicrosoftDocs/sql-docs-pr/pull/20677/files - to remove the batch_params article not to cause any more confusion.

I must say I appreciate very much you bringing this to our attention.  

We apologize for not catching this earlier and adding it to the deprecated list.

**Comment by srutzky** [comment]
@markingmyname Yer welcome. And I'm not able to see the internal PR stuff, but sounds good. Will the "Features discontinued in SQL Server 2012" page also be updated? I know it's obsolete doc, but it would answer the question if anyone ever does go looking for it. Thanks for taking care of this.

**Comment by markingmyname** [comment]
@srutzky 

I realized that about the internal PR.  That's why I edited that comment to remove it. :)

Unfortunately, no.  All docs describing SQL server version 2014 and older are no longer updated.

However, if someone has bookmarked or saved the link to the sp_batch_params article, it will auto direct them to the updated SPROC article.

Thank you again for helping us improve and keep our content current.

**Comment by srutzky** [comment]
Ok, I started my comment before the edit. Sad that the older doc won't be made correct, but I suppose that the redirect should answer the question well-enough. Thanks.

**Comment by markingmyname** [comment]
@srutzky 

The changes are live now.

thank you, again.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site.
