### ISSUE TITLE
Certificate Management (SQL Server Configuration Manager) - only applies to SQL 2019 

### ISSUE THREAD

**Issue by sqlworldwide** [MicrosoftDocs/sql-docs#6948]
At the top of this document, it is mentioned "SQL Server (all supported versions) - Windows only". Is that misleading? Since the instructions only work for SQL Server 2019.

In one of the notes it is mentioned:
_You can use certificate management in SQL Server Configuration Manager with lower versions of SQL Server, starting with SQL Server 2008._

I do not see any import button in lower versions of SQL Server.
![2021-10-18_14-18-27](https://user-images.githubusercontent.com/26484126/137785676-39995d9e-f1ae-4174-8a37-ba783c01e0bd.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be811156-078f-e4d9-406a-7e63e06603b5
* Version Independent ID: e7ab123c-1f76-14ac-2d55-296e7845a50c
* Content: [Certificate Management (SQL Server Configuration Manager) - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/manage-certificates?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/manage-certificates.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/manage-certificates.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@sqlwideworld

Thank you for submitting this.

However, I am a bit confused about what the ask is now for this issue.

Do you want us to update the article that shows a different UI for SQL Server 2019 vs. lower versions, or are you asking about uploading a cert for SQL Server?

Please let me know.

Thank you.

@srutzky,

Thank you for your input on this topic as well.

Also, I replied to another [issue](https://github.com/MicrosoftDocs/sql-docs/issues/6946) you submitted earlier.

**Comment by srutzky** [comment]
@markingmyname and @WilliamAntonRohm : With Configuration Manager _not_ being able to connect to remote instances, as well as there being no easy way to get Configuration Manager 2019 on a server where SQL Server 2019 has not been installed, I have to agree with @sqlworldwide that this documentation is misleading and should be improved. It is _technically_ true that Configuration Manager 2019 does work with lower versions, BUT _only if_ those lower versions just happen to be installed on the same physical server (which is the case for me as they are all for testing, but not a common setup out in the real world). It would be great if Configuration Manager could connect to remote instances, but if it can't (and it really looks like it can't), then some additional wording is needed to qualify that working with previous versions means "previous versions installed on the same server that SQL Server 2019 is installed on". Something to that effect.

**Comment by sqlworldwide** [comment]
@srutzky thank you. That is exactly my point. Please see my initial comment at the top and I still believe the document can be improved.

**Comment by markingmyname** [comment]
@srutzky and @sqlworldwide,

thank you both for clarifying.

I agree with your sentiments.

I will work on clarifying this article, so it's more direct and less confusing.

 Thank you for bringing this to our attention.

**Comment by markingmyname** [comment]
@sqlworldwide ,

Apologizes for the delayed response.

However, I assure you that we have already split the UI instructions based on " SQL" versions.

Depending on what version you select in the TOC, the set of steps d change with how to manage certs for SQL Server. 

![image](https://user-images.githubusercontent.com/22989000/141846865-9c058d68-d8d7-4b97-bdb4-b0000ff094a6.png)

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site.
