### ISSUE TITLE
this doods accent ruins the video - i cant understand anything. sad

### ISSUE THREAD

**Issue by Rekt-Dev** [MicrosoftDocs/sql-docs#6951]
this doods accent ruins the video - i cant understand anything. sad
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 991167bc-4e0e-1fc8-d0bb-f282b51b3321
* Version Independent ID: 0b5cf834-d452-dd57-d51d-268083011e33
* Content: [Work with JSON data - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/json/json-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/json-data-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@Rekt-Dev -- thank you for your feedback.  I will pass it along to that team.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
