### ISSUE TITLE
Use Statefulset rather than Deployment

### ISSUE THREAD

**Issue by kinzleb** [MicrosoftDocs/sql-docs#6953]
It seems like this example should be using a Statefulset rather than a Deployment resource for deploying SQL Server -- the example even seems to switch from a Pod that was clearly created using a Deployment to one created from a Statefulset with a "-0" suffix on the Pod name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04922c04-a2da-186c-5946-1cc4d9a7447b
* Version Independent ID: 6e490885-cdd7-079a-0b3a-4688616b0954
* Content: [Deploy a SQL Server container with Azure Kubernetes Services (AKS) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-ver15#create-storage)
* Content Source: [docs/linux/tutorial-sql-server-containers-kubernetes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-sql-server-containers-kubernetes.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
We don't see an issue with using Deployment, but if there are arguments otherwise, please feel free to clarify and we will take it under consideration. For now, closing this issue.
