### ISSUE TITLE
The "This Product" link at the bottom of the page leads no where.

### ISSUE THREAD

**Issue by cale-sweeney** [MicrosoftDocs/sql-docs#6955]
[The "This Product" link at the bottom of the page leads no where.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d89ecc7f-4705-dabe-9f70-2070d4aa19c9
* Version Independent ID: 9c991bd5-535c-03b5-d810-c1b2ca7e7cb4
* Content: [Import Flat File to SQL - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/import-flat-file-wizard?view=sql-server-ver15#troubleshooting)
* Content Source: [docs/relational-databases/import-export/import-flat-file-wizard.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/import-flat-file-wizard.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
@cale-sweeney -- Cale, thank you for bringing this to our attention.  The feedback process is changing and the new implementation is in progress.  You are welcome to add any product-related feedback in this issue.

**Comment by WilliamAntonRohm** [comment]
@cale-sweeney -- Cale, the new feedback page is here: 
- [SQL feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
