### ISSUE TITLE
Clarification on the new extent allocation criteria

### ISSUE THREAD

**Issue by tmasternak** [MicrosoftDocs/sql-docs#6959]
The following sentence suggests that there are some threshold criteria for allocating new extents for a table:
 
> The SQL Server Database Engine allocates a new extent to an allocation unit only when it cannot quickly find a page in an existing extent with sufficient space to hold the row being inserted.

What are the exact criteria and what are some scenarios in which this can happen? Does this mean that a new extent can be allocated even if there are pages available with enough free space?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2881d6-51e3-3eee-a6df-911463517b54
* Version Independent ID: 9295888e-8884-7d3f-7bd4-2bdeccae6962
* Content: [Pages and Extents Architecture Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/pages-and-extents-architecture-guide?view=sql-server-ver15#IAM)
* Content Source: [docs/relational-databases/pages-and-extents-architecture-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/pages-and-extents-architecture-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by tmasternak** [comment]
@rothja just checking. Were you able to find any additional information on this behavior? Thank you!

**Comment by rothja** [comment]
@tmasternak  Tomasz, sorry for the delay. @pmasl Pedro, do you have any insight onto whether this could happen (the [doc](https://docs.microsoft.com/en-us/sql/relational-databases/pages-and-extents-architecture-guide?view=sql-server-ver15#IAM) suggests that a new extent might be created even if an existing one has free space under *unspecified circumstances*) and what those conditions are? Thanks! 

![image](https://user-images.githubusercontent.com/1580454/145438593-cd80bfee-3dea-4c74-a70f-57521359732f.png)

**Comment by rothja** [comment]
#assign:pmasl

**Comment by rothja** [comment]
I apologize, but we haven't been able to find a firm answer on this in order to update the docs. At this time, I am going to close the issue, but if we get a firm answer in the future, we will add it at that time. Thanks, and sorry that we don't have a more definitive resolution at this time!
