### ISSUE TITLE
Remote user: Use the remote user to map users not defined in Local login?

### ISSUE THREAD

**Issue by nachiketrss** [MicrosoftDocs/sql-docs#6966]
Hi

Can you review your documentation on `remote user`. It says: "Remote User
Use the remote user to map users **not** defined in Local login. The Remote User must be a SQL Server Authentication login on the remote server."

Should it have been as follows?: Use the remote user to map users defined in Local login. 

Please can this be reviewed.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac4dbeb2-b244-27af-7cfe-4f441ca26d2e
* Version Independent ID: ee282927-e7df-a8d9-da5c-755d0bc41b0f
* Content: [Create Linked Servers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/linked-servers/create-linked-servers-sql-server-database-engine?view=sql-server-ver15#to-create-a-linked-server-to-another-instance-of-sql-server-using-sql-server-management-studio)
* Content Source: [docs/relational-databases/linked-servers/create-linked-servers-sql-server-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/linked-servers/create-linked-servers-sql-server-database-engine.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hi @nachiketrss, in this case I believe the documentation is correct. The Remote Login parameter or field in SSMS is only used for local logins not already mapped to a remote user. If the local login has specific instructions to use a remote user, it will use that remote user. All other local users, it will use the remote login specified. In TSQL, the difference is in the sp_addlinkedsrvlogin command. When a @locallogin parameter is provided, it will use the @rmtuser. When no @locallogin is provided, the @rmtuser is attempted by any other local logins.

**Comment by nachiketrss** [comment]
@WilliamDAssafMSFT - You may have misunderstood the issue so I will attempt to reiterate.

I agree that `The Remote Login parameter or field in SSMS is only used for local logins not already mapped to a remote user.`. But this issue is nothing to do with Remote Login. As mentioned in my original issue description, it is to do with the definition of **Remote User**.

The documentation reads: Use the remote user to map users **not** defined in Local login.

Is this correct? Shouldn't it be: **Use the remote user to map users defined in Local login.**

cc: @WilliamAntonRohm

**Comment by WilliamDAssafMSFT** [comment]
@nachiketrss Thanks for the time spent on this explanation, I DO now see how this is confusing and I appreciate calling this out. We can make the edit to "Use the remote user to map users defined in Local login." Would you like to open the PR, make the change yourself, and get credit as a contributor to the article? I'll await your reply.
If so, go to https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/linked-servers/create-linked-servers-sql-server-database-engine.md, log into GitHub, and click the "pencil' button to get started.

**Comment by nachiketrss** [comment]
Thanks I have raised the PR now. But instead of your recommendation of "Use the remote user to map **users** defined in Local login.", I have updated it to "Use the remote user to map **user** defined in Local login."

I hope it makes sense because each row refers to a single login (user).

**Comment by WilliamDAssafMSFT** [comment]
Makes sense, and well done! Thanks again!
