### ISSUE TITLE
Documentation about Windows AD group based SQL logins with and without Kerberos

### ISSUE THREAD

**Issue by nachiketrss** [MicrosoftDocs/sql-docs#6967]
The existing documentation doesn't mention anything about **Windows AD group based SQL logins** on the source server. What I mean is - assuming the source user is member of a Windows AD group based SQL logins, then what are the linked server limitations with and without Kerberos configured?

For example:
1. Without Kerberos, whether the "Local server login to remote server login mappings" section supports "Local Login" value of type Windows AD group based SQL login?
2. With Kerberos, whether the "Local server login to remote server login mappings" supports "Local Login" value of type Windows AD group based SQL login?
3. Without Kerberos, and for each of the options in "For a login not defined in the list above, connections will:" section, whether it supports Windows AD group based SQL login making the query?
4. With Kerberos, and for each of the options in "For a login not defined in the list above, connections will:" section, whether it supports Windows AD group based SQL login making the query?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac4dbeb2-b244-27af-7cfe-4f441ca26d2e
* Version Independent ID: ee282927-e7df-a8d9-da5c-755d0bc41b0f
* Content: [Create Linked Servers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/linked-servers/create-linked-servers-sql-server-database-engine?view=sql-server-ver15#to-create-a-linked-server-to-another-instance-of-sql-server-using-sql-server-management-studio)
* Content Source: [docs/relational-databases/linked-servers/create-linked-servers-sql-server-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/linked-servers/create-linked-servers-sql-server-database-engine.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by nachiketrss** [comment]
@WilliamDAssafMSFT - For example - it will be nice to mention in the documentation that Window AD group based SQL login is not supported as `Local Login`.

**Comment by WilliamDAssafMSFT** [comment]
thanks @nachiketrss. Will add this note to the documentation, this is potentially useful that only SQL Authentication or a Windows Authentication login can be used.
