### ISSUE TITLE
mssql account not part of mssql group

### ISSUE THREAD

**Issue by Ziomal004** [MicrosoftDocs/sql-docs#6968]
While trying to execute  `/opt/mssql/bin/mssql-conf set sqlagent.enabled true ` as user mssql
on latest docker release for 2019 SQL on linux it throws the following exception:

```
This program must be run as superuser or as a user with membership in the mssql
group.
```
Lacks an info here why mssql user is not by default part of mssql group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c0b1027-3982-e114-0230-c6bd9bd81346
* Version Independent ID: 244740de-8817-1671-387d-970f8ee8dfcb
* Content: [Configure SQL Server settings on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-configure-mssql-conf.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-mssql-conf.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
@amvin87 - Following up

**Comment by amvin87** [comment]
Yes, we are aware on this issue and for now working on fixing this. Meanwhile, you can make the changes required to mssql-conf file as documented here: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-ver15#mssql-conf-format and then mount that when deploying the containers or edit the mssql-conf file manually if you want to do this inside the container.

**Comment by VanMSFT** [comment]
> Yes, we are aware on this issue and for now working on fixing this. Meanwhile, you can make the changes required to mssql-conf file as documented here: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-ver15#mssql-conf-format and then mount that when deploying the containers or edit the mssql-conf file manually if you want to do this inside the container.

Thanks, @amvin87 - What doc changes are needed in the meantime? We do list that the command needs to run with sudo, but is there a need to clarify further?

**Comment by amvin87** [comment]
I think until we fix this issue, we can update this doc https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment?view=sql-server-ver15&pivots=cs1-bash with a section that how customers can work with the mssql.conf file in containers as guidance. I will share a draft with you offline.

**Comment by VanMSFT** [comment]
Following up with Amit offline.
