### ISSUE TITLE
RDBMS high availability in Korean Language totally wrong

### ISSUE THREAD

**Issue by Park-minkyu** [MicrosoftDocs/sql-docs#6972]
Hello there,
for version of 2016~2017
Table of feature that supports per SQL server edition in RDBMS high availability section are wrong
ex)  
                                                          Enterprise Standatd
------------------------------------------------
온라인 인덱스 만들기 및 다시 작성 | 예            |     예

means that standard edition supports online index rebuilding which is not true.

and other features that supports only in enterprise edition are also wrong.
this will give confusion to korean engineers.

con you check it? 
thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 453dc1e2-0c9c-fe95-c6fc-90be886432ad
* Version Independent ID: cd472bc0-26b9-a4a6-4089-31b79be787cb
* Content: [Editions and supported features - SQL Server 2017](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2017?view=sql-server-ver15)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-2017.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-2017.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@Park-minkyu -- we've created an internal localization ticket for this issue.  I'll let you know when that is completed.

**Comment by Park-minkyu** [comment]
Sound great! I'll wait on your call. Thank you.

**Comment by WilliamAntonRohm** [comment]
@Park-minkyu -- Minkyu, this has been fixed and should be live.

**Comment by Park-minkyu** [comment]
> @Park-minkyu -- Minkyu, this has been fixed and should be live.

Confirmed that document has been fixed. Thank you.
