### ISSUE TITLE
AttributeError: 'SparkContext' object has no attribute 'install_packages'

### ISSUE THREAD

**Issue by yetanotherlogonfail** [MicrosoftDocs/sql-docs#6977]
[Enter feedback here]
sc.install_packages("numpy==1.11.0")
import numpy as np

result:
Traceback (most recent call last):
  File "/script.py", line 14, in <module>
    sc.install_packages("numpy==1.11.0")
AttributeError: 'SparkContext' object has no attribute 'install_packages'

so is this incorrect or have you not been precise enough?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95966e39-532d-fcb7-7f2a-d7386dc53862
* Version Independent ID: da6bc455-2357-046a-63d8-145335f2945d
* Content: [Spark Library Management - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/spark-install-packages?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/spark-install-packages.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/spark-install-packages.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Cannot reproduce. @yetanotherlogonfail do you have any more scenario/setup information to provide?
CC @DaniBunny
