### ISSUE TITLE
New location access permission setup for SQL server when moving user databases

### ISSUE THREAD

**Issue by kamelija-kauzlaric** [MicrosoftDocs/sql-docs#6987]
Hi,

I think it would be a good idea to add a link to [this part of the page](https://docs.microsoft.com/en-us/sql/relational-databases/databases/move-user-databases?view=sql-server-ver15#planned-relocation-procedure) which would lead to the article on [granting file system permissions to the per-service SID](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-file-system-permissions-for-database-engine-access?view=sql-server-ver15#to-grant-file-system-permission-to-the-per-service-sid), to make sure the new location can be accessed by SQL Server. 

This might be useful for people just learning how to use SQL (like myself).

Sorry if this is the wrong place for this feedback!
K.K.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378754cc-abd5-2c11-4662-3da9af6094f9
* Version Independent ID: b6ae6f68-11b3-adb2-5ed2-c882bae020f3
* Content: [Move User Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/move-user-databases?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/move-user-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/move-user-databases.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hi @kamelija-kauzlaric, this is a great suggestion and this is the right place for this feedback! Will get a doc update in flight to add shortly. Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by kamelija-kauzlaric** [comment]
Hello, that's great! Thanks for letting me know and have a great day.
