### ISSUE TITLE
Please state explicitly whether the memory optimised filegroup can be on an SMB file share

### ISSUE THREAD

**Issue by RP634** [MicrosoftDocs/sql-docs#6990]
Can the memory optimised filegroup be on an SMB file share?  This page does not say.  It says explicitly that "The memory-optimized filegroup is based on filestream filegroup".  Maybe that implies that the memory optimised filegroup cannot be on an SMB file share.  An explicit statement would be so much clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0438f047-5f9a-e2bd-c026-6deb62e4c121
* Version Independent ID: 23bd86fc-3c86-9623-4d9e-057ce9f5302a
* Content: [The Memory Optimized Filegroup - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/the-memory-optimized-filegroup?view=sql-server-ver15)
* Content Source: [docs/relational-databases/in-memory-oltp/the-memory-optimized-filegroup.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/the-memory-optimized-filegroup.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@RP634 -- thank you for your feedback.

@markingmyname -- please look into this issue.

Related to #6989

**Comment by markingmyname** [comment]
@cawrites for awareness

**Comment by markingmyname** [comment]
@RP634

Thank you for your feedback! We will investigate and get back to you with the relevant info.

However, please add your experience in [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) to find if you see more people experience the same situation.

**Comment by markingmyname** [comment]
@RP634 

Database files need to be local only in general. Azure Blob Storage is possible. On Linux, you can use NFS, which is a different protocol. SMB protocol-based files are supported only for read-only purposes/databases.

FILENAME { 'os_file_name' | 'filestream_path' } Specifies the operating system (physical) file name.' os_file_name ' Is the path and file name used by the operating system when you create the file. The file must reside on one of the following devices:

- The local server on which SQL Server is installed
- Storage Area Network [SAN]
- iSCSI-based network

The specified path must exist before executing the CREATE DATABASE statement.

For more information, see "Database Files and Filegroups" in the Remarks section.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site.
