### ISSUE TITLE
ODBC 13.1 driver broken on Mac?

### ISSUE THREAD

**Issue by jmorrey** [MicrosoftDocs/sql-docs#6991]
I followed the instructions on this page to install the 13.1 driver, including symlinking the odbcinst.ini and odbc.ini files into /etc.  However, I still get the following error when trying to use the driver from a Python script:

```
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/usr/local/lib/libmsodbcsql.13.dylib' : file not found (0) (SQLDriverConnect)")
```

Here is my odbcinst.ini file:

```
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/usr/local/lib/libmsodbcsql.13.dylib
UsageCount=1
```

The dylib file itself is there.  However, most of the dependencies seem to be broken:

```
% otool -L /usr/local/lib/libmsodbcsql.13.dylib
/usr/local/lib/libmsodbcsql.13.dylib:
	/usr/local/opt/msodbcsql/lib/libmsodbcsql.dylib (compatibility version 1.5.0, current version 1.9.2)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1259.11.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/local/lib/libodbcinst.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)

% ls -alh /usr/local/opt/msodbcsql/lib/libmsodbcsql.dylib
ls: /usr/local/opt/msodbcsql/lib/libmsodbcsql.dylib: No such file or directory
% ls -alh /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
ls: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation: No such file or directory
% ls -alh /usr/lib/libSystem.B.dylib
ls: /usr/lib/libSystem.B.dylib: No such file or directory
% ls -alh /usr/local/lib/libodbcinst.2.dylib 
lrwxr-xr-x  1 craven  admin    50B Nov  1 08:51 /usr/local/lib/libodbcinst.2.dylib -> ../Cellar/unixodbc/2.3.9_1/lib/libodbcinst.2.dylib
% ls -alh /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
ls: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib: No such file or directory
% ls -alh /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
ls: /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos: No such file or directory
% ls -alh /usr/lib/libcurl.4.dylib
ls: /usr/lib/libcurl.4.dylib: No such file or directory
% ls -alh /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
ls: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib: No such file or directory
% ls -alh /usr/lib/libiconv.2.dylib
ls: /usr/lib/libiconv.2.dylib: No such file or directory
% ls -alh /usr/lib/libc++.1.dylib
ls: /usr/lib/libc++.1.dylib: No such file or directory

```

Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c0de6fb-19ae-ff6f-8e73-ce66fa94bd64
* Version Independent ID: 34edd099-f4fe-4ac3-cdd4-abc87b35270b
* Content: [Install the Microsoft ODBC driver for SQL Server (macOS) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@jmorrey - Thank you for your question. I would ask over in the GitHub repo for the Homebrew install formula for the driver:

https://github.com/Microsoft/homebrew-mssql-release

Someone there should be able to help you troubleshoot.

Regards,
David

**Comment by WilliamAntonRohm** [comment]
@jmorrey -- Jon, thank you for your question.

@David-Engel -- David, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
