### ISSUE TITLE
.NET 4.7.2 is not relevant on this document.

### ISSUE THREAD

**Issue by sivan-koren** [MicrosoftDocs/sql-docs#6992]
[Enter feedback here]
I just ran the 18.10 setup for SSMS and discovered that .NET Framework 4.7.2 was not installed with this installation file.

Document lists that .NET Framework 4.7.2 remains as a shared component when uninstalling SSSMS.

Why would the document list an unrelated shared component as remaining installed if the setup file never installs it to begin with?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
#assign:dzsquared

**Comment by dzsquared** [comment]
Hi @sivan-koren  - the list of shared components are potentially installed by SSMS, but may already exist within your operating system.  To be clear, is SSMS functioning normally for you?  I'm updating the docs now to be more clear, here's a sneak peak at the content:




> SSMS may install shared components if it is determined that they are missing during SSMS installation. SSMS will not automatically uninstall these components when you uninstall SSMS.

> The shared components are:
> 
> - Azure Data Studio
> - Microsoft .NET Framework 4.7.2
> - Microsoft OLE DB Driver for SQL Server
> - Microsoft ODBC Driver 17 for SQL Server
> - Microsoft Visual C++ 2013 Redistributable (x86)
> - Microsoft Visual C++ 2017 Redistributable (x86)
> - Microsoft Visual C++ 2017 Redistributable (x64)
> - Microsoft Visual Studio Tools for Applications 2017
> 
> These components aren't uninstalled because they can be shared with other products. If uninstalled, you may run the risk of disabling other products.

**Comment by sivan-koren** [comment]
SSMS currently working, no .NET 4.7.2 is installed.

Another .NET version, namely 4.5, is installed, but did not originate from
the SSMS installer, it is pre-existing.

**Comment by dzsquared** [comment]
#please-close
