### ISSUE TITLE
SQL Server documentation is mostly unusable

### ISSUE THREAD

**Issue by lukos** [MicrosoftDocs/sql-docs#6995]
I was trying to follow this to setup a workgroup cluster for failover and very quickly got overcome by the volume and complexity of instructions. This page doesn't look too bad but as soon as you follow the links to setting up the cluster and enabling the aoag features, you are immediately amongst extremely long instructions that don't always match what I can see in SQL Server 2019 setup.

* "Install MSDTC" but that isn't in the SQL Server setup so not sure
* Enable clustering but that feature is not available on the setup menu (you can install a new installation as a cluster but is that what I want?)
* Even the explanation of "what you used to do in previous versions" takes up a lot of the article, which is irrelevant if you simply want to know how to set it up.
* The prerequisites in the linked document say "must be using server 2016" since it is a lazily reused document. Why not separate it into the various flavours of SQL Server and the types of failover groups you are creating?
* "All servers must have the Failover Clustering feature installed" no link. Thanks.
* `new-itemproperty -path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -Name LocalAccountTokenFilterPolicy -Value 1` Really? I need to add things to the registry with Powershell to setup a high-level function like clustering?

At this stage with the millions of dollars you have made, these things should be applications that you download and run and it can tell you to "install missing package X from here" or "clustering is not enabled, press here to enable it" etc. I wouldn't need any of the documentation and I wouldn't have given up on the whole exercise.

All really nasty unfortunately.

(By the way, I have 20+ years with MS and SQL Server so I am not a noob and I am also not a DBA)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df2d6260-37b5-78f2-e558-7129b58ca9c5
* Version Independent ID: 247cde67-5d7a-c844-f2e7-292277348c60
* Content: [Create a domain-independent availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/domain-independent-availability-groups?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/domain-independent-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/domain-independent-availability-groups.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@lukos -- Luke, thank you for your well-considered feedback. As you know, these are highly complex products, as is the documentation, and so there will always be room for further clarification.
- You are welcome to submit issues related to the overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback). 

@cawrites -- Cheryl, please look into this issue.


cc @rothja for awareness

**Comment by lukos** [comment]
Thanks @WilliamAntonRohm I appreciate it is a bit of a vague issue to raise but I would expect a dedicated team for such an important product who are not constantly reviewing the documents but also adding lots of these very complicated steps to the main installer so I don't have to know whether the change will break something or whether it is still relevant on Server 2019/SQL Enterprise or whatever.

Unfortunately, I don't know enough about setting up failover groups to provide much useful specific feedback, that is why I wanted to use the docs. I have passed this work to my colleague so hopefully he can manage otherwise we simply won't be able to set this up without taking a massive risk on our production DB.

**Comment by cawrites** [comment]
@kfarlee can you some insights on this topic

**Comment by rwestMSFT** [comment]
@lukos Thank you for your concern. We will look into rewriting this article to use more current examples and clearer explanations.

#please-close
