### ISSUE TITLE
text Free Extended Security Updates eligible for improvement

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/sql-docs#7002]
Hi sql-docs team,
 
In https://docs.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-end-of-life-overview?view=sql-server-ver15#benefits-2 for Azure Virtual Machine some text may be eligible for improvement. 
Current text: 
**Free Extended Security Updates:** If you choose to keep your SQL Server as-is using SQL Server 2008 or SQL Server 2008 R2, you can get free Extended Security Updates for three years past the end of support date, even without having Software Assurance.
 
On top of SQL Server 2008 and 2008 R2, Extended Security Updates will also be available for SQL Server 2012. Also, a fourth year of ESU was added for 2008 and 2008 R2 (Azure only).
 
Please review.
Kind regards, inge
 
 https://docs.microsoft.com/en-us/lifecycle/products/microsoft-sql-server-2008
![image](https://user-images.githubusercontent.com/40343254/140058416-3dcfce8f-fc59-4ead-a97d-ba927517fdb4.png)
https://docs.microsoft.com/en-us/lifecycle/products/microsoft-sql-server-2008-r2
![image](https://user-images.githubusercontent.com/40343254/140058581-fae00143-2acd-44a4-8d12-407f3b81f7e0.png)
https://docs.microsoft.com/en-us/lifecycle/products/microsoft-sql-server-2012
![image](https://user-images.githubusercontent.com/40343254/140058653-e3b4a898-1c9e-448c-aebd-dc8cda5d81e6.png)

 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b469329f-fda9-1f3a-8527-75b1b1bd21ac
* Version Independent ID: c7c4d8dd-2402-c86a-81b0-6acf0ea1a762
* Content: [End of support options - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-end-of-life-overview?view=sql-server-ver15)
* Content Source: [docs/sql-server/end-of-support/sql-server-end-of-life-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/end-of-support/sql-server-end-of-life-overview.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@ingebeumer -- Inge, thank you for your thorough feedback.

@cawrites -- Cheryl, please look into this issue.

**Comment by cawrites** [comment]
@ingebeumer thank you for providing this information we will looking into and update this issue when the information is available.

**Comment by cawrites** [comment]
@pmasl can you provide some feedback on this issue?

**Comment by MashaMSFT** [comment]
Hi @ingebeumer , thanks for contacting Microsoft! @rwestMSFT would you be able to help with this Git Issue?

#reassign:rwestMSFT

**Comment by rwestMSFT** [comment]
Hi @ingebeumer, this article was already updated earlier this year. If you would like to make additional changes, please reply here.

#please-close
