### ISSUE TITLE
Installation not applicable to Managed Instance

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/sql-docs#7009]
Hi team,
 
The Applies to section of some articles in Installation mention Azure SQL Managed Instance. As customers don't install SQL Server themselves in Azure SQL Managed Instance, I think there's some articles that don't apply to Managed Instance. Observed in multiple articles in the Installation documentation. See some examples in screenshot.
 
Please review the Applies to section for articles in Installation documentation.

Kind regards, Inge
 
![image](https://user-images.githubusercontent.com/40343254/140715697-7e76ce74-2e18-401e-afba-d8a9c30e74e5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2001e929-cac9-395c-224e-d03489a46007
* Version Independent ID: f7979c9a-282b-50d5-d074-17ca941c43cf
* Content: [What's New in SQL Server Installation - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/what-s-new-in-sql-server-installation?view=sql-server-ver15)
* Content Source: [docs/sql-server/install/what-s-new-in-sql-server-installation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/what-s-new-in-sql-server-installation.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment]
@ingebeumer -- Inge, thank you for bringing this to our attention.

@cawrites -- Cheryl, please look into this issue.

**Comment by rothja** [comment]
@MikeRayMSFT Could you take a look at this? Thank you!
