### ISSUE TITLE
page is too large

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/sql-docs#7010]
the info in this page is great, but the page itself is too large.  should be split up into sub pages that cross link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dae81d65-f7b9-7a97-7fe7-30775f815e5b
* Version Independent ID: d4d339e7-48d7-d159-eb59-13bdedc25b4c
* Content: [Transaction Locking and Row Versioning Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-ver15)
* Content Source: [docs/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@drdamour -- thank you for your positive feedback.

@rothja -- please look into this issue.

**Comment by rothja** [comment]
@drdamour Thank you, and I completely agree with you! We migrated this white paper from older content back in the days when White Papers were the norm. Due to limited time constraints, we kept the same format, but breaking it up would be more modern and more usable. At this time, we do not have the bandwidth to perform the task of splitting it up, but I will keep this in mind as a possible future improvement for the article. Thanks, again, for the feedback and idea.

**Comment by drdamour** [comment]
Y close the issue then?

**Comment by rothja** [comment]
@drdamour Yes, I closed it for now. But I'll keep your suggestion in mind. Let me know if you have any other questions or concerns. Thanks!

**Comment by drdamour** [comment]
Same question, y close the issue then? You agree it should be done, it should remain open till addressed then i would think

**Comment by rothja** [comment]
@drdamour Oh, so sorry. I read that as "Yes" or "You" and not "Why". My bad. So, for feedback that is a good idea but we don't have bandwidth to implement, we track for the future but close the issue as there is no immediate work planned. That way we don't have hundreds of pending issues open that obscure the issues we are still researching actively to respond to.
