### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by larrystavinoha** [MicrosoftDocs/sql-docs#7015]
[Enter feedback here]
 Peer-to-Psafaseer replication, is in the text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d481270-9da8-1af1-b010-2bcf9807a0a8
* Version Independent ID: 146f72dc-f0cf-6699-b055-83c5e0f07f94
* Content: [Transactional Replication - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/transactional/transactional-replication?view=sql-server-ver15)
* Content Source: [docs/relational-databases/replication/transactional/transactional-replication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/transactional/transactional-replication.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@larrystavinoha -- thank you for bringing this to our attention.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
