### ISSUE TITLE
Need to add steps to change server collation for SQL Server on Linux

### ISSUE THREAD

**Issue by krishnamsft20** [MicrosoftDocs/sql-docs#7016]
We need to update this document with steps needed to change collation in Linux /Containers.
mssql-conf set-collation
There have been few customers that have asked about this.
[Enter feedback here]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca70403-237f-0160-7d1f-5817e40b5d25
* Version Independent ID: 9993116a-bcec-e054-1cbe-82c3ad603ef6
* Content: [Set or Change the Server Collation - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-server-collation?view=sql-server-ver15)
* Content Source: [docs/relational-databases/collations/set-or-change-the-server-collation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/set-or-change-the-server-collation.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by VanMSFT** [comment]
Hey @krishnamsft20 - The mssql-conf settings for collation is listed in our Linux section: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-ver15#collation
