### ISSUE TITLE
Invalid link on "Release Notes for the Microsoft Drivers for PHP for SQL Server" page

### ISSUE THREAD

**Issue by luisdev** [MicrosoftDocs/sql-docs#7017]
The "Release Notes for the Microsoft Drivers for PHP for SQL Server" page on https://docs.microsoft.com/en-za/sql/connect/php/release-notes-php-sql-driver?view=sql-server-2017 contains a broken link to the 5.9 version of the driver. That link is pointing to:

https://go.microsoft.com/fwlink/?linkid=?????

That ?linkid is clearly invalid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a683dc3-b573-0ed0-22df-ed028017e776
* Version Independent ID: b7dd1223-79e2-ccd4-cac5-06370a6051b2
* Content: [Release Notes for the Microsoft Drivers for PHP - PHP drivers for SQL Server](https://docs.microsoft.com/en-za/sql/connect/php/release-notes-php-sql-driver?view=sql-server-2017#59)
* Content Source: [docs/connect/php/release-notes-php-sql-driver.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/release-notes-php-sql-driver.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@luisdev -- Luis, thank you for your feedback.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@luisdev -- Luis, this issue has been fixed and should be live.

**Comment by luisdev** [comment]
Tested and it is working now.
Thank you.
