### ISSUE TITLE
List of new T-SQL language elements for 2016?

### ISSUE THREAD

**Issue by Prof-hu** [MicrosoftDocs/sql-docs#7027]
I was looking for a comprehensive list of new T-SQL language elements, exactly like this one, but for 2016.
https://docs.microsoft.com/en-us/previous-versions/sql/2014/database-engine/whats-new-in-sql-server-2016?view=sql-server-2014#TSQL
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92039d2f-79be-5b42-a880-d2992ce8a151
* Version Independent ID: ef7c0d04-a65f-28e0-3935-3dac80fb13c2
* Content: [What's New in SQL Server 2016 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-2016?view=sql-server-2016)
* Content Source: [docs/sql-server/what-s-new-in-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/what-s-new-in-sql-server-2016.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by Prof-hu** [comment]
Can't say that I'm not very confused by having "previous-versions/sql/**_2014_**" in the URL first, then a final node of "whats-new-in-sql-server-_**2016**_" and then again a parameter "?view=sql-server-**_2014_**"
To add to the confusion, if I visit https://docs.microsoft.com/en-us/previous-versions/sql/2014/?view=sql-server-2014 and try to open the "Transact-SQL Reference +" item in the TOC (pointing to https://docs.microsoft.com/en-us/sql/t-sql/?view=sql-server-2014) I get redirected to this page...

**Comment by WilliamAntonRohm** [comment]
@Prof-hu -- thank you for your feedback.  I see the appropriate What's New page with this URL:
- https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-2016?view=sql-server-2016

There doesn't appear to be a list of specifically new T-SQL elements for SQL Server 2016:
- https://docs.microsoft.com/en-us/sql/t-sql/language-reference?view=sql-server-2016

Please check the version that is selected:
![image](https://user-images.githubusercontent.com/27738025/141870558-43b6e15b-5011-429a-9727-34094a74c26a.png)

cc @MikeRayMSFT for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
