### ISSUE TITLE
Is AAD MFA supported in the code sample?

### ISSUE THREAD

**Issue by ElectricLlama** [MicrosoftDocs/sql-docs#7028]
Please refer to this SO question and answer

https://stackoverflow.com/questions/69980859/authenticate-to-sql-server-through-powershell-with-mfa-active-directory-interac

Could you add a note to this doc that AAD MFA is not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75078545-ecc6-24d3-1f2b-3827e60dc1a2
* Version Independent ID: 4f6f6369-6c88-fb74-5229-c2ec698d11a9
* Content: [Configure Always Encrypted using PowerShell - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/configure-always-encrypted-using-powershell?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/configure-always-encrypted-using-powershell.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/configure-always-encrypted-using-powershell.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@ElectricLlama -- Nick, thank you for your question and research.

@jaszymas -- Jakub, please look into this issue.

**Comment by FinneVirta** [comment]
Any update on this?

**Comment by VanMSFT** [comment]
Thanks, @ElectricLlama for submitting this. I will make the update for now that it's not supported with MFA

@jaszymas @shohamMSFT - FYI

@GithubMirek - Hey Mirek, can you help clarify this? Specifically, Azure AD MFA is not supported using system.data.sqlclient in PowerShell, but I could also not find a way to use Microsoft.Data.SqlClient (MSAL).

**Comment by VanMSFT** [comment]
https://sqlrider.net/2020/08/connecting-to-azure-sql-database-with-aad-authentication-using-powershell-and-c/
