### ISSUE TITLE
SQL Server 2014 offline content instructions do not work

### ISSUE THREAD

**Issue by sqlsauce** [MicrosoftDocs/sql-docs#7030]
The SQL Server 2014 offline content section (anchored at #sql-server-2014-offline-content) instructs to download a self-extracting executable from https://www.microsoft.com/en-us/download/details.aspx?id=42557. The instructions say the executable will extract HelpContentSetup.msha, but running that executable, SQLSERVER2014DOCUMENTATION_AUGUST2014_EN.exe, results only in the following .cab files, without HelpContentSetup.msha:

sql_server_2014_books_online_b4164_sql_120_en-us_1(0b10b277-ad40-ef9d-0d66-22173fb3e568).cab
sql_server_2014_developer_reference_b4171_sql_120_en-us_1(414c518c-73ee-006d-2aad-f9eb3f12eb55).cab
sql_server_2014_developer_reference_b4171_sql_120_en-us_2(078924e0-b382-e658-77d1-065e3c9a4c0f).cab
sql_server_2014_developer_reference_b4171_sql_120_en-us_3(e19cb1f9-e72c-003f-0e8d-2fc198fab0c5).cab
sql_server_2014_developer_reference_b4171_sql_120_en-us_4(ec69ae08-4336-bf87-59a8-d7f5bb6b3e41).cab
sql_server_2014_developer_reference_b4171_sql_120_en-us_5(92f61087-0ccb-f17e-48a7-88ea3a57c5b3).cab
sql_server_2014_developer_reference_b4171_sql_120_en-us_6(43a8e617-7971-1ad0-4f65-550cec66847b).cab
sql_server_2014_developer_reference_b4171_sql_120_en-us_7(1c45f605-f120-5a25-601a-c655996706a1).cab
sql_server_2014_developer_reference_b4171_sql_120_en-us_8(e29e6550-3127-71c2-424c-b9603d907d17).cab
sql_server_2014_installation_b4170_sql_120_en-us_1(b0791de4-5768-173b-6840-80b3f61093ac).cab
sql_server_2014_microsoft_sql_server_language_reference_b4246_sql_120_en-us_1(5c1ad741-d0e3-a4a8-d9c0-057e2ddfa6e1).cab
sql_server_2014_microsoft_sql_server_language_reference_b4246_sql_120_en-us_2(24815f90-9e36-db87-887b-cf20727e5e73).cab

Each of those .cab files has an .mshc file and an .mshi file, but no .msha.

Either the instructions are wrong (both here and at https://www.microsoft.com/en-us/download/details.aspx?id=42557), or SQLSERVER2014DOCUMENTATION_AUGUST2014_EN.exe is wrong or incomplete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521c034-95f5-47b2-e8ed-6113d3a385d2
* Version Independent ID: 5bf9d9e5-a0e1-7467-4764-944d8f67542b
* Content: [Install SQL Server documentation to view offline - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-offline-documentation?view=sql-server-ver15#sql-server-2014-offline-content)
* Content Source: [docs/sql-server/sql-server-offline-documentation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/sql-server-offline-documentation.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@sqlsauce -- Jonathan, thank you for your feedback.  SQL Server 2014 documentation is no longer being updated:
- [SQL Server 2014 documentation](https://docs.microsoft.com/en-us/previous-versions/sql/2014/?view=sql-server-2014)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

cc @markingmyname for awareness
