### ISSUE TITLE
Why is it that stuff never works out of the box with Linux?

### ISSUE THREAD

**Issue by ngluva** [MicrosoftDocs/sql-docs#7037]
It's like we're stuck in 1990 and still compiling Linux from floppies.

W: GPG error: https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019 focal InRelease: The following signatures couldn't be  verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019 focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@ngluva -- Malcolm, thank you for your feedback.  This repo is solely for documentation issues, and this seems to be product-related.  Please add this issue here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)


I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
