### ISSUE TITLE
Übersetzungsfehler beseitigen, der den Inhalt unverständlich macht

### ISSUE THREAD

**Issue by klacol** [MicrosoftDocs/sql-docs#7038]
Das sollte getauscht werden:

> Wenn Sie die Befehle im vorherigen Beispiel rückgängig gemacht haben, wird der Container heruntergefahren, wenn das Skript „do-my-sql-commands.sh“ abgeschlossen wird.

gegen:

> Wenn Sie die Befehle im vorherigen Beispiel vertauschen, wird der Container heruntergefahren, wenn das Skript „do-my-sql-commands.sh“ abgeschlossen wird.

Danke

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 19f77423-91bb-21e4-5e1b-a956a7161ca2
* Version Independent ID: b2d30183-00b8-302d-ab1e-4f9882a2eed0
* Content: [Konfigurieren und Anpassen von SQL Server Docker-Containern - SQL Server](https://docs.microsoft.com/de-de/sql/linux/sql-server-linux-docker-container-configure?view=sql-server-ver15&pivots=cs1-bash#feedback)
* Content Source: [docs/linux/sql-server-linux-docker-container-configure.md](https://github.com/MicrosoftDocs/sql-docs-pr.de-de/blob/live/docs/linux/sql-server-linux-docker-container-configure.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@klacol -- vielen Dank, dass Sie uns darauf aufmerksam gemacht haben.  Ich aktualisiere diesen Artikel.

**Comment by WilliamAntonRohm** [comment]
@amvin87 -- Amit, please review this change in [private PR 20775](https://github.com/MicrosoftDocs/sql-docs-pr/pull/20775).

**Comment by WilliamAntonRohm** [comment]
This issue is being tracked in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/535300.
