### ISSUE TITLE
Typo in the product name

### ISSUE THREAD

**Issue by ackh** [MicrosoftDocs/sql-docs#7039]
The sentence
> SQL Server Management Objects (SMO) are objects designed for programmatic management of MicrosoftSQL Server

at the beginning contains a typo. It should be "Microsoft SQL" instead of "MicrosoftSQL".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92818bf8-a90c-250d-5b92-7c1883deab6e
* Version Independent ID: abfe86cb-a3ac-13d9-1447-2009537a9e2e
* Content: [Overview (SMO) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/overview-smo?view=sql-server-ver15)
* Content Source: [docs/relational-databases/server-management-objects-smo/overview-smo.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/server-management-objects-smo/overview-smo.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@ackh -- thank you for catching this!  I am updating the article.
