### ISSUE TITLE
EmployeeID

### ISSUE THREAD

**Issue by brentd2021** [MicrosoftDocs/sql-docs#7049]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85ee3f3-9c1b-f58f-57e7-47b3ac56014d
* Version Independent ID: 563123f2-41a3-ef47-ce0a-75ca0373da08
* Content: [Use the Visual Studio Code mssql extension - SQL Server](https://docs.microsoft.com/en-us/sql/tools/visual-studio-code/sql-server-develop-use-vscode?view=sql-server-ver15)
* Content Source: [docs/tools/visual-studio-code/sql-server-develop-use-vscode.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/visual-studio-code/sql-server-develop-use-vscode.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@brentd2021 -- thank you for your feedback.  Please clarify.
