### ISSUE TITLE
No difference in example 2 and 3 in 'Get started using SQL Assessment cmdlets'

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/sql-docs#7051]
Hi team,
 
I don't see any difference in option 2 and 3 in [Get started using SQL Assessment cmdlets](https://docs.microsoft.com/en-us/sql/tools/sql-assessment-api/sql-assessment-api-overview?view=sql-server-ver15#get-started-using-sql-assessment-cmdlets). Was the item copied and not yet modified to provide a different example?
 
The section seems eligible for improvement. 
 
Kind regards, inge

![image](https://user-images.githubusercontent.com/40343254/143245594-f6b7ec87-9c8d-42c7-87cf-a85262d3d213.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40121b29-38a7-4942-aafb-0238da8e93e7
* Version Independent ID: 13d2b590-ad3c-98cc-85e0-c1b014247665
* Content: [SQL Server Assessment API - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sql-assessment-api/sql-assessment-api-overview?view=sql-server-ver15)
* Content Source: [docs/tools/sql-assessment-api/sql-assessment-api-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sql-assessment-api/sql-assessment-api-overview.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@ingebeumer -- Inge, thank you for bringing this to our attention.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
PR - https://github.com/MicrosoftDocs/sql-docs-pr/pull/20922 - to remove the duplicate step.

Thank you for bringing this to our attention.
