### ISSUE TITLE
Maintenance Plans Enable Your Disabled Indexes

### ISSUE THREAD

**Issue by johannwe** [MicrosoftDocs/sql-docs#7052]
To whom it may concern,

while figuring out a custom solution to disable unneeded indexes in a DB, I came across the issue, that a maintenance plan may silently enable your disabled index again. This issue (including steps to repro) was already described by Brent Ozar 3 years ago in this blog: https://www.brentozar.com/archive/2017/12/maintenance-plans-enable-disabled-indexes

Can you please exclude disabled indexes from all maintenance plans?
A far worse solution would be to document this odd behavior.

Many thanks in advance,
Johann Weskandt
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78f16a34-9ad5-2f36-847a-a44040b88ecc
* Version Independent ID: 3bb9b9b7-c22c-90bd-09c1-cad555611e33
* Content: [Rebuild Index Task (Maintenance Plan) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/maintenance-plans/rebuild-index-task-maintenance-plan?view=sql-server-ver15)
* Content Source: [docs/relational-databases/maintenance-plans/rebuild-index-task-maintenance-plan.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/maintenance-plans/rebuild-index-task-maintenance-plan.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@johannwe Thank you for pointing this out. It sounds like a bug in SQL Server. Would you be willing to enter this in our Product Feedback site for SQL Server here: (https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0)(https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0)? 

But, if this is the behavior, we should add a warning to the user in the article until it is fixed. Let me research this and see if we should add it. Thanks, and sorry for this impacting you!

**Comment by johannwe** [comment]
@rothja Thanks for your feedback, but unfortunately your links do not work! I only get a page showing this msg:
We're sorry, but something went wrong. Please try again, and if this persists, contact the website administrator.
Error ID # [75d704f1-3871-46b6-b950-8dc10ebfd8ee]
We've been notified about this issue and we'll take a look at it shortly. Thank you for your patience.
12/9/2021 10:30:41 AM UTC
NAM 3084a93d-fcb2-44be-8ef3-67cb7edbf6d7

**Comment by rothja** [comment]
@johannwe So sorry that the link did not work! Maybe try accessing it at the bottom of the docs page here:

![image](https://user-images.githubusercontent.com/1580454/145434547-b8475fb0-9009-4b67-ad15-44f20cb3f0c7.png)

This "Product feedback" is meant to take new entries (and votes for already reported problems) and make the product team aware for triaging and future fixes. Let me know if that button works for you? Thank you!

**Comment by johannwe** [comment]
Hi Jason,

finally I managed to file this behaviour as a product bug under my corporate account:
https://feedback.azure.com/d365community/idea/dc06bf39-3b5c-ec11-a819-0022484bf651
Hopefully the product group can straighten out the flaws around disabled indexes.

Many thanks, Johann
________________________________

**Comment by rothja** [comment]
Awesome, thank you! I will look at it a little further if we could provide some doc guidance.

**Comment by rothja** [comment]
At this time, I think the product feedback to the SQL Server product team that was filed is the best course of action for this issue. If we get more information on this from the product team or from other tests/sources, we will consider updating the doc in the future. Thank you!
