### ISSUE TITLE
Incorrect grammar

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#7053]
**With extense new research** on modern workloads and actual business data reveal that predicate filters from different tables usually do not correlate with each other. In the following query, the CE assumes there is no correlation between s.type and r.date. Therefore the CE makes a lower estimate of the number of rows returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d712c8-87f2-7203-6dd9-5f23a60cdfc2
* Version Independent ID: 536de496-f292-b661-7da7-350d59ec331f
* Content: [Cardinality Estimation (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/cardinality-estimation-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/cardinality-estimation-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/cardinality-estimation-sql-server.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@brettshearer -- Brett, thank you for catching that.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
