### ISSUE TITLE
Step 4.10 "Create a database encryption key by using the ASYMMETRIC KEY (EKMSampleASYKey)."

### ISSUE THREAD

**Issue by Kevin-S-Lewis** [MicrosoftDocs/sql-docs#7056]
Is Step 4.10 "Create a database encryption key by using the ASYMMETRIC KEY (EKMSampleASYKey)." missing USE <DB_Name> in the example?

i.e. in line with: https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-encryption-key-transact-sql?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4997f245-c966-51a3-34c7-705c3cfbd4b0
* Version Independent ID: 129fbe40-3b02-f2c1-ef13-b42d86ffdb77
* Content: [Set up Transparent Data Encryption (TDE) Extensible Key Management with Azure Key Vault - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-ver15&tabs=portal)
* Content Source: [docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @Rupp29
* Microsoft Alias: **arupp**

**Comment by Rupp29** [comment]
I added <USE DB> for clarity.
Thanks for the feedback.

**Comment by Rupp29** [comment]
#sign-off

**Comment by VanMSFT** [comment]
Doc has been updated by Adrian in https://github.com/MicrosoftDocs/sql-docs-pr/pull/20787. Closing this issue.
