### ISSUE TITLE
Wrong DATEADD algorythm 

### ISSUE THREAD

**Issue by kibbage** [MicrosoftDocs/sql-docs#7058]
In the sample code there are the following lines:
/*Add offset of the local time zone to current time*/
DECLARE @asOf DATETIMEOFFSET = GETDATE() AT TIME ZONE 'Pacific Standard Time'
/*Convert AS OF filter to UTC*/
SET @asOf = DATEADD (MONTH, -9, @asOf) AT TIME ZONE 'UTC';

In the last line shouldn't "MONTH" be "HOUR"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16923b34-9fbb-86a2-071d-c4fa47e639ff
* Version Independent ID: 83127f7a-a6cd-0b63-a723-ee72f7511a6a
* Content: [Temporal Table Usage Scenarios - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-table-usage-scenarios?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/temporal-table-usage-scenarios.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/temporal-table-usage-scenarios.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@kibbage -- Ken, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
