### ISSUE TITLE
MSSQL for debian 11

### ISSUE THREAD

**Issue by shivaramabhat** [MicrosoftDocs/sql-docs#7059]
[Enter feedback here]

Hello,

We are planning to move to Debian 11. When can we expect support for ODBC driver compatible with  Debian 11 ?
Is it planned in the roadmap?

Best regards
Shivarama Bhat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36a1d7f-a410-b597-0eb7-98212934fb0e
* Version Independent ID: e706f2bd-e051-fcff-7c3d-2ef3d9f80e87
* Content: [Download ODBC Driver for SQL Server - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-linux-2017)
* Content Source: [docs/connect/odbc/download-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/download-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
Look for it in the next release. While that date isn't public, sometime in Q1 2022 is a safe assumption. Subscribe to the SQLServerDrivers blog for driver release announcements.
https://techcommunity.microsoft.com/t5/sql-server-blog/bg-p/SQLServer/label-name/SQLServerDrivers

Regards,
David

#please-close
