### ISSUE TITLE
Reverse lookup (PTR record) is required when configuring the host address in the first step.

### ISSUE THREAD

**Issue by limershein** [MicrosoftDocs/sql-docs#7064]
This example will not work if the PTR record box is not checked when the host DNS record is created in AD.  The adutil process requires reverse lookups!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84e4ebac-6e2e-f188-e382-4e8d9940f8fb
* Version Independent ID: c256593c-499f-1cf9-9f6b-eba3516de73a
* Content: [Configure Active Directory authentication with SQL Server on Linux using adutil - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-ad-auth-adutil-tutorial?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-ad-auth-adutil-tutorial.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-ad-auth-adutil-tutorial.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@limershein -- Louis, thank you for your succinct feedback.

@amvin87 -- Amit, please look into this issue.

**Comment by amvin87** [comment]
Thank you Louis, that is correct, we need to edit the picture with the PTR record checked for RDNS to work. @WilliamAntonRohm  I can give you the correct picture could you please update the doc with the correct picture.

**Comment by WilliamAntonRohm** [comment]
@amvin87 -- please send me that picture and I will update this article.

**Comment by amvin87** [comment]
![image](https://user-images.githubusercontent.com/63835878/144647204-47c4f483-f934-4d3b-a3a3-a33206148cc0.png)

**Comment by WilliamAntonRohm** [comment]
@limershein -- Louis, I have updated the documentation and it should be live by tomorrow.

@amvin87 -- Amit, thank you for the image.
