### ISSUE TITLE
Document known issue: SQL Server Profiler user interface incorrectly rendering decimals in TextData column

### ISSUE THREAD

**Issue by jzabroski** [MicrosoftDocs/sql-docs#7065]
From  https://github.com/MicrosoftDocs/sql-docs/pull/6978#issuecomment-981907477

Suggest we add a note like such somewhere in the SQL Server profiler article CC @MikeRayMSFT :

```
> [!NOTE]
> If you are using the deprecated SQL Server Profiler, you may see decimal values represented incorrectly in the user interface.  For example, 0.00159 may be represented in the TextData field as 159.  This behavior is a display bug that occurs when the TextData value is reconstructed from other profiler fields.  This is a good reason to use SQL Server Profiler's replacement API, SQL Server Extended Events.  If you try to copy-paste the 159 literal into a SQL Server Management Studio query window and execute it, you will get an error.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8779ddb-0c8c-cdab-eea6-a0b4f7412628
* Version Independent ID: 64ac7286-50d2-0a1b-6950-3df303e73fae
* Content: [SQL Server Profiler - SQL Server Profiler](https://docs.microsoft.com/en-us/sql/tools/sql-server-profiler/sql-server-profiler?view=sql-server-2016)
* Content Source: [docs/tools/sql-server-profiler/sql-server-profiler.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sql-server-profiler/sql-server-profiler.md)
* Product: **sql**
* Technology: **profiler**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@jzabroski -- John, thank you for bringing this up.

@markingmyname, @MikeRayMSFT -- Mark, Mike, please look into this issue.

**Comment by markingmyname** [comment]
@jzabroski 

May I ask for you to offer this feedback to the product group - https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0.

I will discuss with the parties in charge on how to illustrate this change.

thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site.

**Comment by jzabroski** [comment]
I am confused. What is the outcome here? You want to ignore the issue until people vote for it to be fixed... in an obsolete product?

**Comment by jzabroski** [comment]
This is literally a documentation issue. It is not a big. Please fix the docs and reopen this.
