### ISSUE TITLE
SSMS F1 help doesn't work for sys.dm_exec_query_plan_stats

### ISSUE THREAD

**Issue by zikato** [MicrosoftDocs/sql-docs#7068]
I open SSMS, highlight sys.dm_exec_query_plan_stats in my query and press F1

I would expect it to open this page
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-query-plan-stats-transact-sql?view=sql-server-ver15

but it goes to "SQL Server Management Studio (SSMS) Query Editor page" instead

**Comment by WilliamAntonRohm** [comment]
@zikato -- Tom, thank you for finding this.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

**Comment by WilliamDAssafMSFT** [comment]
Thanks @zikato for raising this issue! Can confirm and repro, Investigation is underway.

**Comment by Matteo-T** [comment]
I looked into this issue and it appears to be a problem in the F1/Help backend side (as per internal e/mail thread with @WilliamDAssafMSFT). If this cannot be resolved there, I believe I have a workaround which we can include in the next release of SSMS (18.11 and 19.0 Preview 2).

**Comment by WilliamDAssafMSFT** [comment]
Thanks @Zikato for bringing this to our attention. A fix is in flight to address this problem with F1 redirection for SSMS on some DMVs. Much appreciated!

**Comment by zikato** [comment]
Hi @WilliamDAssafMSFT, I've noticed that sys.dm_exec_query_plan_stats works for me on the newest SSMS version (18.10 - 15.0.18390.0). But I found another function where F1 help doesn't work (even though F1 metadata is correct). Should I wait for a new version/fix or report it?

**Comment by WilliamDAssafMSFT** [comment]
@Zikato You can paste in the article links here and I'll investigate based on what we found last time was the issue.

**Comment by zikato** [comment]
Sure, it's this one
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/current-transaction-id-transact-sql.md

**Comment by WilliamDAssafMSFT** [comment]
Same issue as last time. Thanks for raising. Will address.
