### ISSUE TITLE
Typo correction

### ISSUE THREAD

**Issue by amon09** [MicrosoftDocs/sql-docs#7072]
There is a small typo, ACCESS_METHODS_HBOT_VIRTUAL_ROOT should be ACCESS_METHODS_HOBT_VIRTUAL_ROOT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fe4ffaf-23d3-98b8-f8be-f27c63ead017
* Version Independent ID: 6d31099f-0505-f296-b3c5-61e11b1a8085
* Content: [Whitepaper: Diagnose & resolve latch contention - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/diagnose-resolve-latch-contention?view=sql-server-ver15)
* Content Source: [docs/relational-databases/diagnose-resolve-latch-contention.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/diagnose-resolve-latch-contention.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @bluefooted
* Microsoft Alias: **pamela**

**Comment by WilliamAntonRohm** [comment]
@amon09 -- Arun, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@bluefooted -- Pam, please review this change in [private PR 20828](https://github.com/MicrosoftDocs/sql-docs-pr/pull/20828).

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
