### ISSUE TITLE
sys-dm-pdw-dms-external-work-transact-sql.md / column "estimated_bytes_processed"

### ISSUE THREAD

**Issue by ozanabuse** [MicrosoftDocs/sql-docs#7075]
In the doc for sys.dm_pdw_dms_external_work for Synapse Analytics, it's mentioned that column "estimated_bytes_processed" shows the "Number of bytes processed by this worker."
Running the following query on a SQL dedicated pool "select estimated_bytes_processed from sys.dm_pdw_dms_external_work", returns the error "Msg 207, Level 16, State 1, Line 22 Invalid column name 'estimated_bytes_processed'."

![image](https://user-images.githubusercontent.com/18326258/144268455-e8fb101f-953a-4f24-9763-58d6cc071b55.png)

Running select bytes_processed from sys.dm_pdw_dms_external_work, works without an issue.
Should there be bytes_processed, instead of estimated_bytes_processed?

**Comment by WilliamAntonRohm** [comment]
@ozanabuse -- Ozana, thank you for your feedback.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@ronortloff -- Ron, please review this update in [private PR 20831](https://github.com/MicrosoftDocs/sql-docs-pr/pull/20831).

**Comment by WilliamAntonRohm** [comment]
@ozanabuse -- Ozana, thank you again for catching this.  I have updated the documentation and it should be live by tomorrow.
