### ISSUE TITLE
ancient terms in bcp docs

### ISSUE THREAD

**Issue by josef-marec** [MicrosoftDocs/sql-docs#7076]
"Arguments" section of bcp docs mention term "owner", while in syntax is used correct term "schema"

IIRC this changed back in version 2008

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86bd520a-7468-fd55-c357-b0f645a917ef
* Version Independent ID: 3dc9dee5-afcb-8287-4441-e84ff717186a
* Content: [bcp Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver15)
* Content Source: [docs/tools/bcp-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/bcp-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@josef-marec -- thank you for your feedback.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review [private PR 20898](https://github.com/MicrosoftDocs/sql-docs-pr/pull/20898).
