### ISSUE TITLE
Rename column sample has the incorrect field names based on the description of the sample. 

### ISSUE THREAD

**Issue by zitzerd** [MicrosoftDocs/sql-docs#7078]
[Enter feedback here]

The sample code talks about table ErrorLog and column ErrorMessage but the description says
> The following example renames the column TerritoryID in the table Sales.SalesTerritory to TerrID in the AdventureWorksLT database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c410eaa8-c421-adaf-6688-578b129c4dbe
* Version Independent ID: 365697b5-dfac-0bc8-9105-f53580fa27bb
* Content: [Rename Columns (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/rename-columns-database-engine?view=sql-server-ver15&source=docs)
* Content Source: [docs/relational-databases/tables/rename-columns-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/rename-columns-database-engine.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Nice catch! Thanks @zitzerd for taking the time to provide this feedback, your suggestions help improve our documentation.  A doc update is in flight.
