### ISSUE TITLE
SPECIFICATION misspelled for DATABASE AUDIT events

### ISSUE THREAD

**Issue by bowermea** [MicrosoftDocs/sql-docs#7082]
The create, alter, and deny database audit specification name has specification misspelled, also deny is supposed to be drop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a14d613f-8491-824f-38a8-552f6086a12b
* Version Independent ID: 1e8bd781-30f0-60b2-5b6e-44cc0e1b1630
* Content: [DDL Events - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/triggers/ddl-events?view=sql-server-2017)
* Content Source: [docs/relational-databases/triggers/ddl-events.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/triggers/ddl-events.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@bowermea -- thank you for catching these.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@rothja -- Jason, please review this update in [private PR 20833](https://github.com/MicrosoftDocs/sql-docs-pr/pull/20833).

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
