### ISSUE TITLE
bad SQL in PredictTipSciKitPy

### ISSUE THREAD

**Issue by wvaughn409** [MicrosoftDocs/sql-docs#7084]
Msg 512, Level 16, State 1, Procedure dbo.PredictTipSciKitPy, Line 5 [Batch Start Line 0]
Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.
Msg 39004, Level 16, State 20, Line 2
A 'Python' script error occurred during execution of 'sp_execute_external_script' with HRESULT 0x80004004.
Msg 39019, Level 16, State 2, Line 2
An external script error occurred: 

Error in execution.  Check the output for more information.
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "D:\ProgramData\MSSQLDEVSERVER\Temp-PY\Appcontainer1\01A307C0-EF9E-4752-B979-B1480B68445F\sqlindb_0.py", line 43, in transform
    mod = pickle.loads(lmodel2)
TypeError: a bytes-like object is required, not 'NoneType'

SqlSatelliteCall error: Error in execution.  Check the output for more information.
STDOUT message(s) from external script: 
SqlSatelliteCall function failed. Please see the console output for more information.
Traceback (most recent call last):
  File "D:\MSSQL15.MSSQLDEVSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 605, in rx_sql_satellite_call
    rx_native_call("SqlSatelliteCall", params)
  File "D:\MSSQL15.MSSQLDEVSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\RxSerializable.py", line 375, in rx_native_call
    ret = px_call(functionname, params)
RuntimeError: revoscalepy function failed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3289a4-d387-44cc-3e1e-4eadebf26472
* Version Independent ID: 292e69a9-c3b0-833e-138b-4522b00430f2
* Content: [Python tutorial: Run predictions in SQL stored procedures - SQL machine learning](https://docs.microsoft.com/en-us/sql/machine-learning/tutorials/python-taxi-classification-deploy-model?view=sql-server-ver15#feedback)
* Content Source: [docs/machine-learning/tutorials/python-taxi-classification-deploy-model.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/tutorials/python-taxi-classification-deploy-model.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by dphansen** [comment]
@WilliamDAssafMSFT Would you be able to have a look at this? Thank you.

**Comment by WilliamDAssafMSFT** [comment]
@wvaughn409 We will need to investigate with engineers. Please provide SQL Server version/edition information, OS, as well as the tools you are using to execute. The more information you can provide the better.

**Comment by WilliamDAssafMSFT** [comment]
@wvaughn409 Can you follow up with environmental information?
