### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by MarkHammondDPR** [MicrosoftDocs/sql-docs#7086]
The instructions do not tell you how to display Registered Servers. I suggest adding the following step at the top of the instructions, like so:

1. If the Registered Servers pane is not visible, select View -> Registered Servers in the menu.
2. In Registered Servers, right-click a server, point to Connect, and then click Object Explorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8720cf5-689a-372e-80aa-8cb3b7ef6c52
* Version Independent ID: e278bc40-9397-2baa-5490-2115bb386988
* Content: [Connect to a Registered Server - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/register-servers/connect-to-a-registered-server-sql-server-management-studio?view=sql-server-ver15)
* Content Source: [docs/ssms/register-servers/connect-to-a-registered-server-sql-server-management-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/register-servers/connect-to-a-registered-server-sql-server-management-studio.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@MarkHammondDPR -- Mark, thank you for your feedback.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review this update in [private PR 20899](https://github.com/MicrosoftDocs/sql-docs-pr/pull/20899).

**Comment by MarkHammondDPR** [comment]
Hi William. That link takes me to a 404 page.

**Comment by WilliamAntonRohm** [comment]
@MarkHammondDPR -- that link is to a PR in the private staging docs repo.  Your issue is now fixed & should be live by tomorrow.
