### ISSUE TITLE
This page is not c++

### ISSUE THREAD

**Issue by MartinKosicky** [MicrosoftDocs/sql-docs#7089]
The name of the page is called C++. Its misleading since it looka like som C winapi. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac828919-7780-c626-d071-724e0cbc5d56
* Version Independent ID: 47d85824-56f3-9fa1-4348-30c864bc756b
* Content: [C++ ODBC app accessing a SQL database - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/cpp-code-example-app-connect-access-sql-db?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/cpp-code-example-app-connect-access-sql-db.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/cpp-code-example-app-connect-access-sql-db.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@MartinKosicky -- thank you for your feedback.  Please clarify your concern.  The code appears to be C++ to me.

cc @David-Engel for awareness

**Comment by MartinKosicky** [comment]
Hmm, well you are using stdio.h instead of iostream. Using goto instead if RAII objects. Code doesnt have c++ wrappers at all. You are using macros instead of lambdas. Struct defines look like in C.   The SQL code is pure C style API. I suggeat you either provide c++ wrappers and write it as C++ code or rename the documentation to C

**Comment by WilliamAntonRohm** [comment]
@MartinKosicky -- thank you for clarifying.  Is the code as-is functioning for you?

@David-Engel -- please look into this issue.

**Comment by MartinKosicky** [comment]
yes it is functioning but,  it's not C++. You can also write it in python and it will work but it wont be C++

**Comment by David-Engel** [comment]
It compiles as C++, which is sufficient to label it as such.

Regards,
David

#please-close

**Comment by David-Engel** [comment]
The article has been renamed to "C / C++".

Regards,
David
