### ISSUE TITLE
Minor correction on the path to the examples directory

### ISSUE THREAD

**Issue by emil-prager** [MicrosoftDocs/sql-docs#7091]
Hi there!

Just a minor correction on the path to the `examples` directory: the name of the PowerShell extension directory is `microsoft.powershell-<version>` instead of `ms-vscode.PowerShell-<version>`.
E.g.: `microsoft.powershell-2021.8.2`.

**Installation details:**
Azure Data Studio version: 1.33.1 (from 2021-11-04):
```
Version: 1.33.1 (user setup)
Commit: 0b9ef714c823d662815f441aec4a94eaa21940f8
Date: 2021-11-04T17:45:15.872Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```
PowerShell extension version: 2021.8.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abda6b59-7b6a-af05-5551-06375473fdc3
* Version Independent ID: 0bba3dc2-9bce-5df1-fa8a-be933632e733
* Content: [PowerShell extension - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/powershell-extension?view=sql-server-ver15&source=docs)
* Content Source: [docs/azure-data-studio/extensions/powershell-extension.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/extensions/powershell-extension.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @SQLvariant
* Microsoft Alias: **aanelson**

**Comment by WilliamAntonRohm** [comment]
@emil-prager -- Emil, thank you for bringing this to our attention.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@SQLvariant -- Aaron, please review this update in [private PR 20835](https://github.com/MicrosoftDocs/sql-docs-pr/pull/20835).

**Comment by WilliamAntonRohm** [comment]
@emil-prager -- Emil, thank you again for your feedback.  I have updated the documentation and it should be live by tomorrow.
