### ISSUE TITLE
Modernize Forced Parameterization Documentation

### ISSUE THREAD

**Issue by erikdarlingdata** [MicrosoftDocs/sql-docs#7093]
This page is quite old, and even has no alternative at the "recommended version" link:

https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms175037(v=sql.105)

These pages are difficult for people to find and sometimes make it seem like a feature is outdated.

**Comment by WilliamAntonRohm** [comment]
@erikdarlingdata -- Erik, thank you for your feedback.  9 years is indeed very old for a technology article.  That page indicates that it is retired.  Which feature are you looking for?

**Comment by erikdarlingdata** [comment]
Hi there! I'm not really sure how to answer that one. The feature I'm looking for is documented there (forced parameterization). I guess what I'm looking for is for it to be moved/migrated to docs that aren't archived? It seems to be complete, just... old. Thanks!

**Comment by WilliamAntonRohm** [comment]
@erikdarlingdata -- Erik, apologies for the delay in responding.  Please see these articles:
- [Specify Query Parameterization Behavior by Using Plan Guides](https://docs.microsoft.com/en-us/sql/relational-databases/performance/specify-query-parameterization-behavior-by-using-plan-guides)
- [Forced Parameterization](https://docs.microsoft.com/en-us/sql/relational-databases/query-processing-architecture-guide#ForcedParam)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by rwestMSFT** [comment]
@erikdarlingdata Thanks for the suggestion.

This page should be unarchived, like we just did with Service Broker. I'm going to look into this.
