### ISSUE TITLE
Canonize Parallel Query Placement Logic

### ISSUE THREAD

**Issue by erikdarlingdata** [MicrosoftDocs/sql-docs#7095]
This post has a lot of valuable information on it that would be good to canonize and modernize on an official docs page: https://techcommunity.microsoft.com/t5/sql-server-support-blog/sql-server-parallel-query-placement-decision-logic/ba-p/318696

**Comment by WilliamAntonRohm** [comment]
@erikdarlingdata -- Erik, thank you for your feedback.  Do you have a suggestion for a docs.microsoft.com location for this proposed article?

**Comment by erikdarlingdata** [comment]
@WilliamAntonRohm this seems a natural location for it: https://docs.microsoft.com/en-us/sql/relational-databases/query-processing-architecture-guide?view=sql-server-ver15#parallel-query-processing

**Comment by MikeRayMSFT** [comment]
@erikdarlingdata  - thanks for this (very well aged) submission. I've logged [User Story 64009](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64009): Add new: SQL Server parallel query architecture content. Will track to publishing internally.

**Comment by erikdarlingdata** [comment]
Thanks @MikeRayMSFT -- looking forward to it.
