### ISSUE TITLE
Missing info on source installation, and general linux instructions

### ISSUE THREAD

**Issue by NiKiZe** [MicrosoftDocs/sql-docs#7101]
This page is missing information on how to compile from source.

General steps to install on linux machines is `untar`, `./configure`, `make`, `make install` is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f591be-6564-c959-7a92-6489bdd4f60b
* Version Independent ID: eec72536-eda0-1bc8-a41a-36ed4b9a8883
* Content: [Linux and macOS Installation for the Drivers for PHP - PHP drivers for SQL Server](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15)
* Content Source: [docs/connect/php/installation-tutorial-linux-mac.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/installation-tutorial-linux-mac.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@NiKiZe -- Christian, thank you for your feedback.

@David-Engel -- David, please look into this potential documentation issue.

**Comment by NiKiZe** [comment]
Seems there is no source, only binary blobs, bu instructions for general Linux distros would be good so we don't have to reverse engineer the instructions for any of the ones that is listed, to then apply to distro of choice.

**Comment by David-Engel** [comment]
The PHP drivers are open source. If you want to learn how to build from source (and even modify it), the GitHub project has build instructions: https://github.com/Microsoft/msphpsql#building-and-installing-the-drivers-on-windows

Those instructions are not need for this user documentation, which tells how to install the driver in supported scenarios.

Regards,
David

#please-close

**Comment by NiKiZe** [comment]
So you claim that the driver is OSS, you also claim that it works on Linux.
but it requires closed source, and you refuse to provide any information at all on how to use it, or even download it on anything other than your selected sets of bloated distributions - that is not Linux, and is not helpful in any way.

But hey, thanks for making it clear, makes it easy to not waste more time on it. Thanks!
