### ISSUE TITLE
Driver not available?

### ISSUE THREAD

**Issue by kcoburndnr** [MicrosoftDocs/sql-docs#7103]
[Enter feedback here]
Hi! I went to install the driver at the link below but it kept giving us an 404 error. :( 

Web page
https://docs.microsoft.com/en-us/sql/odbc/microsoft/importing-visual-foxpro-data-into-microsoft-access?view=sql-server-ver15
Link to download here
https://docs.microsoft.com/en-us/previous-versions/visualstudio/foxpro/mt490121(v=msdn.10)
The main source we need no longer exists. 
https://support.microsoft.com/en-US/help/277772

We just need to read the Foxpro files and keep getting errors when access the dbf without a odbc driver. 

THANKS! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0db48ae-6190-c9a4-41dd-17bb38ab25e6
* Version Independent ID: 44b68238-6935-4909-a42b-793d523e7554
* Content: [Visual FoxPro ODBC Driver - Open Database Connectivity (ODBC)](https://docs.microsoft.com/en-us/sql/odbc/microsoft/visual-foxpro-odbc-driver?view=sql-server-ver15)
* Content Source: [docs/odbc/microsoft/visual-foxpro-odbc-driver.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/microsoft/visual-foxpro-odbc-driver.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
@kcoburndnr 

I was able to do a little digging and found that the content of that support article is duplicated here:
https://www.betaarchive.com/wiki/index.php?title=Microsoft_KB_Archive/277772

The Visual FoxPro driver is long out of support and [that doc](https://docs.microsoft.com/en-us/previous-versions/visualstudio/foxpro/mt490121(v=msdn.10)) is no longer maintained, but hopefully this helps you.

Regards,
David

#please-close

**Comment by kcoburndnr** [comment]
Thank you so much @David-Engel !!! I really appreciate the link you sent!
