### ISSUE TITLE
Unsafe Assembly Error SSIS

### ISSUE THREAD

**Issue by bernaljo** [MicrosoftDocs/sql-docs#7104]
Hello,
Please mention that this impacts integration services and provide an example of the error message. Having this error message will enable users to perform a web search and understand why this error occurs.

Example 
"Unsafe assembly 'microsoft.sqlserver.integrationservices.server, version=15.0.0.0, culture=neutral, publickeytoken=89845dcd8080cc91, processorarchitecture=msil' loaded into appdomain 2 (SSISDB.dbo[runtime].1)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96693d4a-9460-9e08-8f14-836b6257e449
* Version Independent ID: 47f19aec-1f62-97c4-fca4-609496fc2139
* Content: [CLR strict security - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/clr-strict-security?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/configure-windows/clr-strict-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/clr-strict-security.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@bernaljo -- thank you for your feedback.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
Thank you, @bernaljo, for bringing this to our attention.

I reached out to the parties involved to get a more in-depth idea of this information.

**Comment by markingmyname** [comment]
#assign @chugugrace

**Comment by WilliamAntonRohm** [comment]
@rwestMSFT -- Randolph, please look into this issue.

**Comment by rwestMSFT** [comment]
Thank you for your contribution, @bernaljo. We already note that `UNSAFE` is required on this page: https://docs.microsoft.com/sql/integration-services/catalog/ssis-catalog#to-restore-the-ssis-database

I will add a reference to this page in an upcoming refresh.
