### ISSUE TITLE
SQL Service Accounts and GPO Settings

### ISSUE THREAD

**Issue by bernaljo** [MicrosoftDocs/sql-docs#7105]
Hello,
Please provide more information regarding group policy settings for SSIS service accounts. As well as the error of packages getting stuck in "Pending Execution" when permissions are not set for the service account. 

GPO requirements:
Impersonate a client after authentication
Replace a process level token
Adjust memory quotas for a process

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b3831a3-6c86-243c-4b07-8960e4d06d7b
* Version Independent ID: dfd7599d-88eb-99f2-c227-0c9dc82bfd87
* Content: [Configure Windows service accounts and permissions - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@bernaljo -- thank you again for writing to us.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
#assign @chugugrace

**Comment by markingmyname** [comment]
@bernaljo 

Have you had a chance to visit this page as well - https://docs.microsoft.com/en-us/sql/integration-services/service/integration-services-service-ssis-service?

**Comment by VanMSFT** [comment]
Closing this as it's been a while since there's no response.
