### ISSUE TITLE
ATTACH Database documentation

### ISSUE THREAD

**Issue by Mendolis** [MicrosoftDocs/sql-docs#7109]
Document completely ignores FILESTREAM - which requires a completely syntax to attach.  If you're going to create a completely separate document from CREATE DATABASE, please provide an example if nothing else

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f754e5a-c07f-943b-5184-6a8eb8a24c26
* Version Independent ID: cedc9b77-16de-ae53-9cec-d10b3dfb1ff1
* Content: [Attach a Database - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/attach-a-database?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/attach-a-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/attach-a-database.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@Mendolis -- thank you for your feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Hi @Mendolis! Thanks for taking the time to provide this feedback.
You can should add all files, including FILESTREAM files, to your CREATE DATABASE FOR ATTACH statement. For an example with a FILESTREAM file, see https://docs.microsoft.com/sql/relational-databases/blob/move-a-filestream-enabled-database. We will consider adding more context to the example on this page however!

**Comment by WilliamDAssafMSFT** [comment]
Hi @Mendolis! Thanks again for taking the time to provide this feedback. Doc updates are in flight to improve this and adjacent pages, to make more clear the files and potential for FILESTREAM to complicate an attach. Thanks again for this feedback, your suggestions help improve our documentation.
