### ISSUE TITLE
Listeners and Kerberos part

### ISSUE THREAD

**Issue by deffinity** [MicrosoftDocs/sql-docs#7111]
For example to configure an SPN for an availability group named AG1listener.Adventure-Works.com hosted...

should be

For example to configure an SPN for an availability group **listener** named AG1listener.Adventure-Works.com hosted...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c76c2d8c-17da-8982-8a91-dd9968efa26e
* Version Independent ID: 2ecd127b-9f05-1f89-bcea-a93e8ded60eb
* Content: [Connect to an availability group listener - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover?view=sql-server-ver15#SSLcertificates)
* Content Source: [docs/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@deffinity -- thank you for catching this.  I am updating the article.
