### ISSUE TITLE
Good page, but SEO not great

### ISSUE THREAD

**Issue by iampeterdaniels** [MicrosoftDocs/sql-docs#7112]
I found this page, but it took a bit of nav.  Just searching for "SQL Server Audit" in google does not get me here on the first results  page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2a1a3a-cffa-ec4b-dedc-c1c23d547abb
* Version Independent ID: b0e62617-2dc3-8762-e359-a78af1fe3191
* Content: [SQL Server Audit (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-database-engine?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/auditing/sql-server-audit-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/auditing/sql-server-audit-database-engine.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @DavidTrigano
* Microsoft Alias: **datrigan**

**Comment by WilliamAntonRohm** [comment]
@iampeterdaniels -- Peter, thank you for your feedback.  I am looking into this article's SEO terms.

**Comment by WilliamAntonRohm** [comment]
@iampeterdaniels -- Peter, apologies for the delayed response.  According to our guidelines, it has the necessary SEO terms:
```
keywords: 
  - "SQL Server Audit"
  - "audits [SQL Server], SQL Server Audit"
```

I passed your comment on to our docs team.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
