### ISSUE TITLE
Create a foreign key relationship in Table Designer Use SQL Server Management Studio confusing

### ISSUE THREAD

**Issue by DougAtClir** [MicrosoftDocs/sql-docs#7124]
In Step 3:

In the Foreign-key Relationships dialog box, select Add.

The relationship appears in the Selected Relationship list with a system-provided name in the format FK_<tablename>_<tablename>, where tablename is the name of the foreign key table.

The "where tablename is the name of the foreign key table" seems to say that all foreign keys are names have the same tablename twice.  Is this intended and correct?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5cd392a-eda6-eaf1-1a15-617d405d6add
* Version Independent ID: b29cc815-8e35-c1ac-cc50-5f7c8ac58778
* Content: [Create Foreign Key Relationships - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/create-foreign-key-relationships?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/create-foreign-key-relationships.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/create-foreign-key-relationships.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @DougAtClir for taking the time to provide this feedback, your suggestions help improve our documentation. This does seem a bit confusing, a doc update is in flight to remediate and should be live later today.
