### ISSUE TITLE
Wrong character in wget options

### ISSUE THREAD

**Issue by MrSpaceWZRD** [MicrosoftDocs/sql-docs#7127]
Places where wget -q0- are mentioned need to be changed to wget -qo- , the correct character for the option is o the letter not 0 the number.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@MrSpaceWZRD -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@MrSpaceWZRD -- as it turns out, those are capital O's, not zeroes.  Thank you for for bringing up this potential point of confusion.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
