### ISSUE TITLE
Vague command Fails, Works when specifying certificate

### ISSUE THREAD

**Issue by MrSpaceWZRD** [MicrosoftDocs/sql-docs#7128]
Issue:
The Command: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

Results in:  gpg: no valid OpenPGP data found.

Suggested Correction: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add microsoft.asc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@MrSpaceWZRD -- that is a good suggestion.  I'll add it to this article.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please review this update in [private PR 20931](https://github.com/MicrosoftDocs/sql-docs-pr/pull/20931).

**Comment by VanMSFT** [comment]
Approved the PR.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
