### ISSUE TITLE
Option incorrectly marked as deprecated

### ISSUE THREAD

**Issue by chinhang** [MicrosoftDocs/sql-docs#7135]
I don't think this option is deprecated, it is still required for linked servers.  If we turn it off, linked servers stop working with the following error: 

Msg 7201, Level 17, State 4, Procedure GetCustomer, Line 1
Could not execute procedure on remote server '' because SQL Server is not configured for remote access. Ask your system administrator to reconfigure SQL Server to allow remote access.

https://stackoverflow.com/questions/54334202/how-to-execute-a-stored-procedure-against-linked-server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebe2b119-5871-7bea-9c04-9bf9a79e653f
* Version Independent ID: 5256973a-9b6b-91b1-92f8-cef735e58e7f
* Content: [Configure the remote access Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-remote-access-server-configuration-option?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-the-remote-access-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-remote-access-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@chinhang -- Ben, thank you for your feedback and research.

@markingmyname -- Mark, please look into this issue.

**Comment by rwestMSFT** [comment]
#reassign:rwestMSFT

**Comment by rwestMSFT** [comment]
The refreshed article will be available in the next few days with more explicit wording about linked servers.

**Comment by rwestMSFT** [comment]
#please-close
