### ISSUE TITLE
There is an example that does not run.

### ISSUE THREAD

**Issue by sangeun-jo** [MicrosoftDocs/sql-docs#7142]
[Enter feedback here]

This example has not been executed in SQL SERVER 2019.
```
USE AdventureWorks2019;  
GO  
SELECT ProductModelID, Name,  
   Instructions.query('  
declare namespace MI="https://schemas.microsoft.com/sqlserver/2004/07/adventure-works/ProductModelManuInstructions"  
   /MI:root/MI:Location[1]/MI:step  
')   
FROM Production.ProductModel  
FOR XML RAW ('ProductModelData')  
GO
```
You have to fix it like this to run it.

```
USE AdventureWorks2019;  
GO
SELECT ProductModelID, 
Name, 
	Instructions.query(
		'declare namespace MI="http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/ProductModelManuInstructions";
	/MI:root/MI:Location[1]/MI:step  
	')
FROM Production.ProductModel
FOR XML RAW ('ProductModelData')
GO
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc7b8512-cd03-75f8-221c-068516cde6bd
* Version Independent ID: 6696e8e0-a494-1de6-5125-a223b5332474
* Content: [Example: Querying XMLType Columns - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/xml/example-querying-xmltype-columns?view=sql-server-ver15)
* Content Source: [docs/relational-databases/xml/example-querying-xmltype-columns.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/xml/example-querying-xmltype-columns.md)
* Product: **sql**
* Technology: **xml**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@sangeun-jo -- Sangeun, thank you for your feedback.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review this change in [private PR 20962](https://github.com/MicrosoftDocs/sql-docs-pr/pull/20962).

**Comment by WilliamAntonRohm** [comment]
#reassign @MikeRayMSFT

**Comment by MikeRayMSFT** [comment]
Fixing in a few places #please-close
