### ISSUE TITLE
Instructions to enable SSDT projects in VS 2022 is invalid

### ISSUE THREAD

**Issue by siakc** [MicrosoftDocs/sql-docs#7146]
In this [article](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssdt/download-sql-server-data-tools-ssdt.md?plain=1) instructions to enable SSDT projects in VS 2022 is invalid, it seems that the functionality is not supported in VS 2022 at all.
https://developercommunity.visualstudio.com/t/microsoft-analysis-services-projects-extension-is/1487317
https://docs.microsoft.com/en-us/answers/questions/620487/problem-with-analysis-services-in-visual-studio-20.html

**Comment by WilliamAntonRohm** [comment]
@siakc -- Siavosh, thank you for your feedback.  Are you following a particular docs.microsoft.com article?

**Comment by siakc** [comment]
Oh sorry I did not mention it in the first places.
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssdt/download-sql-server-data-tools-ssdt.md?plain=1

**Comment by dzsquared** [comment]
@siakc - It seems the links you have added are not for installing SSDT, but for installing the SSAS extension. The SSAS extension is not yet available for VS 2022. 
Info on the SSAS extension:
- https://docs.microsoft.com/en-us/analysis-services/tools-and-applications-used-in-analysis-services?view=asallproducts-allversions
- https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftAnalysisServicesModelingProjects

SSDT projects are SQL database projects, which are available in VS 2022.
![image](https://user-images.githubusercontent.com/12227241/147964386-d4aea270-bad2-4551-9390-b37e81bcb228.png)


#please-close

**Comment by sambathraj** [comment]
Using the URl https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftAnalysisServicesModelingProjects2022 I was able to install the SSAS extension now.
