### ISSUE TITLE
SQL Managed - Algorithm used to define default Max Worker Threads?

### ISSUE THREAD

**Issue by BennyHarding** [MicrosoftDocs/sql-docs#7148]
SQL Managed Instance uses a different algorithm to define the default value for Max Worker Threads (well it did in 2020..).
If this is still the case, can we update this article to include this info?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90f494da-8888-13e8-0fcc-187242579039
* Version Independent ID: 01bd6647-777e-8c62-f865-6831469b4924
* Content: [Configure the max worker threads Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-max-worker-threads-server-configuration-option?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-the-max-worker-threads-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-max-worker-threads-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@BennyHarding -- Ben, thank you for your feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@MashaMSFT for awareness

**Comment by WilliamDAssafMSFT** [comment]
Hi @BennyHarding, is this what you're looking for? [Max concurrent workers (requests)](https://docs.microsoft.com/azure/azure-sql/managed-instance/resource-limits#service-tier-characteristics).

**Comment by BennyHarding** [comment]
Yes, yes it is. Thank you for pointing it out. :)
Will close this item.
