### ISSUE TITLE
B+ Tree

### ISSUE THREAD

**Issue by vikramvgupta** [MicrosoftDocs/sql-docs#7154]
I believe SQL Server uses B+ Tree to store Keys rather than B-Tree. Can this be corrected on the page please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afee5ff1-15c2-257b-a70d-ab71e375273d
* Version Independent ID: e54b50e5-99f6-77a6-9ca1-e9ed6e7c7b64
* Content: [Clustered and nonclustered indexes described - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/clustered-and-nonclustered-indexes-described?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/indexes/clustered-and-nonclustered-indexes-described.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/clustered-and-nonclustered-indexes-described.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@vikramvgupta -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please confirm this documentation update in [private PR 20986](https://github.com/MicrosoftDocs/sql-docs-pr/pull/20986).

**Comment by WilliamAntonRohm** [comment]
#re-assign @MikeRayMSFT

**Comment by MikeRayMSFT** [comment]
SQL Documentation does not identify specific types of binary tree indexes. I'm reviewing this internally before we determine whether or not we will take the private PR.
