### ISSUE TITLE
Update Package Versions To Match Current Situation

### ISSUE THREAD

**Issue by tyler555g** [MicrosoftDocs/sql-docs#7158]
Currently is listed:

<html>
<body>

Connector | Maven Coordinate
-- | --
Spark 2.4.x compatible connector | com.microsoft.azure:spark-mssql-connector:1.0.2
Spark 3.0.x compatible connector | com.microsoft.azure:spark-mssql-connector_2.12:1.1.0

</body>
</html>

Suggested for accuracy:

<html>
<body>

Connector | Maven Coordinate
-- | --
Spark 2.4.x compatible connector | com.microsoft.azure:spark-mssql-connector:1.0.2
Spark 3.0.x compatible connector | com.microsoft.azure:spark-mssql-connector_2.12:1.1.0
Spark 3.1.x compatible connector | com.microsoft.azure:spark-mssql-connector_2.12:1.2.0

</body>
</html>

This is based on https://github.com/microsoft/sql-spark-connector#apache-spark-connector-for-sql-server-and-azure-sql and https://github.com/microsoft/sql-spark-connector/pull/134.

I also recommend a warning to explicitly call out 2.12:1.1.0 vs 2.12:1.2.0. Due to how slight the version change is and the lack of semantic versioning within the connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b01f2068-8e50-ce91-ef4b-c99c61b63b1b
* Version Independent ID: a596f7df-c80e-5b97-21c0-a1eeed1829f0
* Content: [Apache Spark connector for SQL Server - Spark connector for SQL Server](https://docs.microsoft.com/en-us/sql/connect/spark/connector?view=sql-server-ver15)
* Content Source: [docs/connect/spark/connector.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/spark/connector.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@tyler555g -- Tyler, thank you for your thorough feedback.  I am updating the article.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @tyler555g for contacting Microsoft with feedback about our product documentation. It could take from a few business days to a few weeks to look further into this with the product team and decide on how to address. We'll contact you if we need further information, and you'll receive an email message each time we mention you in a comment. 
Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by tyler555g** [comment]
It's a pretty simple and straightforward issue... Shouldn't need to take
weeks.

**Comment by tyler555g** [comment]
@WilliamDAssafMSFT 
Please take a moment to actually read and familiarize yourself with the request and replies.

@WilliamAntonRohm  is updating. This a pretty straightforward and simple issue that should not take weeks.

**Comment by WilliamDAssafMSFT** [comment]
@tyler555g I'd like to discuss with the program manager for a couple important reasons, and they are currently out of the country for that duration. @WilliamAntonRohm please hold off.

**Comment by WilliamAntonRohm** [comment]
@WilliamDAssafMSFT -- noted!

**Comment by WilliamDAssafMSFT** [comment]
Thanks @tyler555g, a doc update is in flight to note support for Spark 3.1.x. Thanks for taking the time to provide this feedback!
