### ISSUE TITLE
Inconsistent/missing information within "Step 2: Create a key vault" when compared between Portal and PowerShell version

### ISSUE THREAD

**Issue by Kevin-S-Lewis** [MicrosoftDocs/sql-docs#7159]
The following links show both Azure Portal and PowerShell methods, however the information presented is technically different.

https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-ver15&tabs=portal#step-2-create-a-key-vault

https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-ver15&tabs=powershell#step-2-create-a-key-vault

Some of this may be down to how the Azure Portal may not allow certain activity with the GUI being more restrictive. Some should apply either way:

![image](https://user-images.githubusercontent.com/79272305/148083774-a2b43364-64ea-4e9d-a56a-14b0b066a315.png)

However the PowerShell tab has further information on Best Practices and Types of keys that the Portal version does not. The portal version says to use a RSA key size of 2048, whereas the PowerShell tab explains either a key size of 2048 or 3072 can be used:

![image](https://user-images.githubusercontent.com/79272305/148084551-f067715e-eae7-4709-8a1d-4c843c146ab4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4997f245-c966-51a3-34c7-705c3cfbd4b0
* Version Independent ID: 129fbe40-3b02-f2c1-ef13-b42d86ffdb77
* Content: [Set up Transparent Data Encryption (TDE) Extensible Key Management with Azure Key Vault - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-ver15&tabs=portal)
* Content Source: [docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @Rupp29
* Microsoft Alias: **arupp**

**Comment by Rupp29** [comment]
Thanks for the detail write up. You are correct, the PowerShell and Portal content is slightly different. This documentation is step-by-step for an Example (not all possible options). There are a few more "options" one could select RSA, HSM, 2048, 3072, etc... This documentation was not intended to provide explanation for every possible option, rather a sample of a way to configure EKM.

**Comment by Kevin-S-Lewis** [comment]
@Rupp29, I do get that, that the portal tab is an example, as is the PowerShell method an example. However would it be an idea that the "Important" notes, "Best Practices" and "Types of key" to be shown within the overall section of Step 2 rather than only in one tab view?

**Comment by Rupp29** [comment]
I added the Best Practices content to the Portal Tab. Thanks for the suggestion.

**Comment by Rupp29** [comment]
I just checked to online docs and verified the Best Practices content is now visible on both PS and Portal tabs. 
Thanks

**Comment by Kevin-S-Lewis** [comment]
Thank you!
