### ISSUE TITLE
add brew tap from msft github tip to troubleshooting section

### ISSUE THREAD

**Issue by petersmagnusson** [MicrosoftDocs/sql-docs#7161]
Suggestion - in the troubleshooting page, add (this if for MacOS m1 Catalina install) something like this:

"If your brew is having trouble finding the formulas, you could try brew tap Microsoft/homebrew-mssql-release".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c0de6fb-19ae-ff6f-8e73-ce66fa94bd64
* Version Independent ID: 34edd099-f4fe-4ac3-cdd4-abc87b35270b
* Content: [Install the Microsoft ODBC driver for SQL Server (macOS) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@petersmagnusson -- Peter, thank you for your suggestion.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
I added a sentence to the troubleshooting section about verifying that the the brew tap command has been run if brew can't find the formulas. The change should show up tomorrow.

Thanks,
David

#please-close
