### ISSUE TITLE
Disable an index : "Disable" menu item always greyed out when table opened in Design

### ISSUE THREAD

**Issue by goozak** [MicrosoftDocs/sql-docs#7168]
For the "Using SQL Server Management Studio / To disable an index" section, it should be mentioned that if the table is opened in Design mode, the "Disable" context-menu item will be greyed out even if the index is enabled.

SQL Server Management Studio v15.0.18390.0
Windows 10 Pro v10.0.19043

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2bb45cd-9675-aa90-9ca2-c27774d85e3f
* Version Independent ID: 7ca9be50-df61-4fa3-9254-7879c3b6d120
* Content: [Disable Indexes and Constraints - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/disable-indexes-and-constraints?view=sql-server-ver15)
* Content Source: [docs/relational-databases/indexes/disable-indexes-and-constraints.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/disable-indexes-and-constraints.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@goozak -- Bruno, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by MikeRayMSFT** [comment]
Fixing in https://github.dev/MikeRayMSFT/sql-docs-pr/tree/20230214-issue-7168

#please-close
