### ISSUE TITLE
SQL Server Profiler - Duration units of measurement (milliseconds vs microseconds)

### ISSUE THREAD

**Issue by match-gabeflores** [MicrosoftDocs/sql-docs#7170]
This text says:

`The server reports the duration of an event in microseconds (10^-6 seconds) and the amount of CPU time used by the event in milliseconds (10^-3 seconds). The SQL Server Profiler graphical user interface displays the Duration column in milliseconds by default, but when a trace is saved to either a file or a database table, the Duration column value is written in microseconds.
`

That's not what I'm seeing when I run a trace on my Azure Analysis Services instance and then save to a table. I see _both_ results are shown in milliseconds. None are in microseconds. 
When I repeat the steps for tracing a t-sql query, I do see the above behavior (milliseconds in trace window, microseconds in saved table results). Is the text above specific to t-sql queries and not SSAS queries? That should be specified.

The trace results
![image](https://user-images.githubusercontent.com/286903/148418295-249e64e0-f2ef-4197-962a-7c3c4e1b40de.png)

Results after saving to table
![image](https://user-images.githubusercontent.com/286903/148418473-edce62a3-1970-4aef-b23f-af504b75bb01.png)

Using SSMS v18.9. Profiler Options below
![image](https://user-images.githubusercontent.com/286903/148418569-1be8f045-3a0f-4709-afeb-248136b207f8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c368ea-c7dd-2697-229b-ff5e2d1c81ab
* Version Independent ID: 0e824da3-240c-a6fa-85de-c85734cfdc24
* Content: [View and Analyze Traces - SQL Server Profiler](https://docs.microsoft.com/en-us/sql/tools/sql-server-profiler/view-and-analyze-traces-with-sql-server-profiler?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/tools/sql-server-profiler/view-and-analyze-traces-with-sql-server-profiler.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sql-server-profiler/view-and-analyze-traces-with-sql-server-profiler.md)
* Product: **sql**
* Technology: **profiler**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@match-gabeflores -- Gabe, thank you for your well-researched feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@match-gabeflores

Yes, it is a reference to t-sql queries.

**Comment by markingmyname** [comment]
@match-gabeflores 

Thanks for bringing this to our attention.

The article will be updated either later today or on Monday.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site or the [Q & A](https://docs.microsoft.com/en-us/answers/products/sql-server) site.
