### ISSUE TITLE
Green code in example (Commented out code in example / Dead Code in example)

### ISSUE THREAD

**Issue by DsanchezPerez** [MicrosoftDocs/sql-docs#7180]
Having commented out code (Green Code / Dead Code) is not a good practice.  Please remove any commented out code from example to present clean best practice implementations to public audience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb5c17b-c567-303f-00b8-0c8a0ad15fb5
* Version Independent ID: a4ccc766-4a61-5b7a-e5dd-692e3cebb503
* Content: [Format Query Results as JSON with FOR JSON - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@DsanchezPerez -- David, thank you for your feedback.  I'm not sure about the first two commented-out lines:

```
   --where
   --   c.ClassName LIKE '%Math%'
```

The third commented-out line is described in the preceding paragraph:
- The absence of the null value from the returned JSON is also illustrated. However, you can override this default behavior by use of the INCLUDE_NULL_VALUES keyword on the FOR clause.

```
   FOR
      JSON AUTO
      --, INCLUDE_NULL_VALUES
```

@jovanpop-msft -- Jovan, please look into this issue.

**Comment by jovanpop-msft** [comment]
@MightyPen added this example. I believe that the following part might be removed:
```
--where
--   c.ClassName LIKE '%Math%'
```
Because I don't see any value for this.
For the second example, I would recommend adding inline comment before INCLUDE_NULL_VALUES to make it clear why this line is here:

```
   FOR
      JSON AUTO
      -- To include NULL values in the output, uncomment the following line:
      --, INCLUDE_NULL_VALUES
```

**Comment by WilliamAntonRohm** [comment]
@DsanchezPerez -- thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
