### ISSUE TITLE
Make sure SSMS settings allow for the change, see this response

### ISSUE THREAD

**Issue by mjathecpa** [MicrosoftDocs/sql-docs#7183]
https://stackoverflow.com/a/28982768/9224187

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76507156-d85c-e9f0-a214-3a9f1eb0f1fc
* Version Independent ID: 045c9c15-fbf9-abf9-c48a-904733e7ab42
* Content: [Change Column Order in a Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/change-column-order-in-a-table?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/change-column-order-in-a-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/change-column-order-in-a-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@mjathecpa -- Michael, thank you for your research and feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @mjathecpa for taking the time to provide this feedback, your suggestions help improve our documentation. A doc update to add more context to this page is in flight!
