### ISSUE TITLE
This does not apply to standard edition

### ISSUE THREAD

**Issue by waltheed** [MicrosoftDocs/sql-docs#7184]
We tried to set this up on our test servers using sql server 2019 standard edition. But it appears that this is not possible with standard edition. This should be made clear at the start of the article. 

In many docs articles by the way there is no mention of the functionalitity being available in enterprise or standard. That would be an important improvement. 

Thanks - Edgar Walther

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f5553d-c78b-8266-66ec-df027f55d47a
* Version Independent ID: 4ffbdaed-d28a-2d1a-c3df-55fe77a39469
* Content: [Offload workload to secondary availability group replica - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/active-secondaries-readable-secondary-replicas-always-on-availability-groups?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/active-secondaries-readable-secondary-replicas-always-on-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/active-secondaries-readable-secondary-replicas-always-on-availability-groups.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@waltheed -- Edgar, thank you for your feedback.

@MashaMSFT -- Masha, please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @waltheed , thanks for contacting Microsoft and my apologies for the delay as we work through a large backlog of Issues. While your suggestion has merit, it is out of scope for a Git Issue engagement so we're going to start tracking it internally ([61471](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61471)) and address it as resourcing allows. I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
