### ISSUE TITLE
SQL Native Client Deprecated

### ISSUE THREAD

**Issue by bernaljo** [MicrosoftDocs/sql-docs#7187]
Please mention deprecation of SQL Native Client and it's replacement linked service Microsoft OLE DB Driver for SQL Server as mentioned below.
https://docs.microsoft.com/en-us/SQL/relational-databases/native-client/SQL-server-native-client?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fd36271-def0-10d0-4fd4-bb8740149433
* Version Independent ID: 100621f6-da29-759e-4ac9-704c3b48fd97
* Content: [Deprecated database engine features in SQL Server 2019 - SQL Server 2019](https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-version-15?view=sql-server-ver15)
* Content Source: [docs/database-engine/deprecated-database-engine-features-in-sql-server-version-15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/deprecated-database-engine-features-in-sql-server-version-15.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@bernaljo -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
After reviewing, we determined that SQL NCLI removal is not a database engine feature. In addition the deprecation announcement was announce many years ago. The requested information is not in the scope of this article. Thank you.
