### ISSUE TITLE
wrong commend in apt-key add: it shall be `wget -qO- https://packages.microsoft.com/keys/microsoft.asc |  sudo apt-key add -`

### ISSUE THREAD

**Issue by philjoseph** [MicrosoftDocs/sql-docs#7191]
[Enter feedback here]

It shall be `wget -qO- https://packages.microsoft.com/keys/microsoft.asc |  sudo apt-key add -` and not as written right now
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@philjoseph -- Phillipe, thank you for catching this.  I am updating the article.
