### ISSUE TITLE
response payload: {"code":400,"reason":"Failed with invalid JSON for Big Data Cluster","internalStatus":"INVALID_JSON","details":["1. Path spec.resources.gateway.spec.settings['gateway-site.gateway.httpserver.requestHeaderBuffer'],line 1, position 449"]

### ISSUE THREAD

**Issue by macarv-ms** [MicrosoftDocs/sql-docs#7195]
The following code snippet in **Provide security and endpoint parameters** section is wrong. I have had few customer complaining about this when trying to implement the following code, copying and pasting from the article. 

{
    ...
    "spec": {
        "resources": {
            ...
            "gateway": {
                "spec": {
                    "replicas": 1,
                    "endpoints": [{...}],
                    "settings": {
                        "gateway-site.gateway.httpserver.requestHeaderBuffer": "65536"
                    }
                }
            },
            ...
        },
        "services": {
            ...
            "hdfs": {
                "resources": [...],
                "settings": {
                  "core-site.hadoop.security.group.mapping.ldap.search.group.hierarchy.levels": "4"
                }
            },
            ...
        }
    }
}

Note that I have tested it myself and, with this setting in config files, we always hit this error during deployment:

2022-01-07 13:37:15.0329 UTC | DEBUG | response payload: urllib3.connectionpool : https://10.140.85.23:30081 "POST /api/v1/bdc HTTP/1.1" 400 314
2022-01-07 13:37:15.0345 UTC | DEBUG | response payload: {"code":400,"reason":"Failed with invalid JSON for Big Data Cluster","internalStatus":"INVALID_JSON","details":["1. Path spec.resources.gateway.spec.settings['gateway-site.gateway.httpserver.requestHeaderBuffer'],line 1, position 449"],"help":"https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help"}
2022-01-07 13:37:15.0345 UTC | ERROR | ERROR: Failed with invalid JSON for Big Data Cluster Details:  1. Path spec.resources.gateway.spec.settings['gateway-site.gateway.httpserver.requestHeaderBuffer'], line 1, position 449 For more help, go to this link: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help azdata_command_data_logger : exit code: 1
2022-01-07 13:37:15.0361 UTC | INFO | command ran in 349.188 seconds.

**SOLUTION**

Correct way in the json should be to put the settings under a "gateway" node. This is different from how settings are provided for services as this is a resource.

"spec": {
        "resources": {
…
          "gateway": {
                "spec": {
                    "replicas": 1,
                    "endpoints": [
                        {
…
                        }
                    ] ,
                    "settings": {
                        "gateway": {
                            "gateway-site.gateway.httpclient.socketTimeout": "95s",
                            "gateway-site.gateway.httpserver.requestHeaderBuffer": "65536"
                        }
                    }
                }
            }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e93258-ada8-594a-c725-005e5cf94e7c
* Version Independent ID: 995e0663-2823-c258-193a-5904620f805d
* Content: [Deploy in Active Directory mode - SQL Server Big Data Cluster](https://docs.microsoft.com/en-us/sql/big-data-cluster/active-directory-deploy?view=sql-server-ver15#provide-security-and-endpoint-parameters)
* Content Source: [docs/big-data-cluster/active-directory-deploy.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/active-directory-deploy.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @cloudmelon
* Microsoft Alias: **melqin**

**Comment by WilliamAntonRohm** [comment]
@macarv-ms -- thank you for your well-researched feedback.

@cloudmelon -- please look into this issue.

**Comment by rwestMSFT** [comment]
@macarv-ms Please create a pull request with this change, so that we can get it merged more quickly.

**Comment by rwestMSFT** [comment]
@macarv-ms Since we haven't heard from you, I'm closing this issue.
