### ISSUE TITLE
-h Docker Flag Shorthand Deprecated

### ISSUE THREAD

**Issue by fennar01** [MicrosoftDocs/sql-docs#7198]
Flag shorthand -h in Docker as mentioned on this page has been deprecated. 

Docker rename [container_name] [new_container_name] is now more relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@fennar01 -- thank you for your feedback.

@amvin87 -- please look into this issue.

**Comment by amvin87** [comment]
Thank you @fennar01  I thought the -h shorthand for --help was deprecated as documented here https://docs.docker.com/engine/deprecated/#-h-shorthand-for---help, but the context for which it is used in our documentation is for --hostname. but I agree to avoid confusion we should update our documentation and replace -h with --hostname. 

@WilliamAntonRohm  could you please help update our documentation and replace -h with --hostname in the command examples in the documentation.

**Comment by WilliamAntonRohm** [comment]
@amvin87 -- thank you for clarifying.  I will make this update.

#reassign @WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
