### ISSUE TITLE
The aside panel is hiding the content of th main page 

### ISSUE THREAD

**Issue by alaindebecker** [MicrosoftDocs/sql-docs#7201]
The **in this article** aside panel is usefull. 

It would be much more usefull if it wasn't covering the main article, preventing to read it.
... Or if one could reduce it, or make it disapear.

AlainD
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dbecbff-a7d6-ec1f-86e6-75c29f1d1850
* Version Independent ID: ad74b783-407c-b0ce-1d01-9384b232c162
* Content: [SQLGetInfo Function - ODBC API Reference](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetinfo-function?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/odbc/reference/syntax/sqlgetinfo-function.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/syntax/sqlgetinfo-function.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@alaindebecker -- Alain, thank you for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
