### ISSUE TITLE
Release notes for azdata cli missing ?

### ISSUE THREAD

**Issue by nojetlag** [MicrosoftDocs/sql-docs#7205]
I would have expected a link to the azdata cli release notes on this page: docs/azdata/install/deploy-install-azdata.md
However can't find anything where I can see what did change between the releases.

**Comment by WilliamAntonRohm** [comment]
@nojetlag -- thank you for your feedback.

- [Install Azure Data CLI (azdata)](https://docs.microsoft.com/en-us/sql/azdata/install/deploy-install-azdata)

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
Thank you for the feedback. At this time Azure Data CLI (azdata) is not receiving additional updates.
