### ISSUE TITLE
Issue on First Instruction

### ISSUE THREAD

**Issue by rishabhack** [MicrosoftDocs/sql-docs#7208]
Your First Instruction "wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add microsoft.asc" Does not work.
Give Error "wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add microsoft.asc"

Solution : curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
Above line solved my problum.

And After that no issue with remaining instructions.

You can Give Some description an Comment type or Mouser Over Instruction if this issue is because of lack in linux technical issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@rishabhack -- Rishabh, thank you for your feedback and solution.  I am updating this article.
