### ISSUE TITLE
Running the command `wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add microsoft.asc` gives out `gpg: can't open 'microsoft.asc': No such file or directory`

### ISSUE THREAD

**Issue by ReportDataCode** [MicrosoftDocs/sql-docs#7209]
[Enter feedback here]
I launched an Ubuntu 20.04 LTS VM on Windows using the Multipass CLI.

I run the following command in a Windows Terminal to import the public repository GPG keys:

`wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add microsoft.asc`

however, it outputs this.
`gpg: can't open 'microsoft.asc': No such file or directory`.

Upon researching, the following commands work instead.
`wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@ReportDataCode -- Prince, thank you for your clear feedback.  I am updating this article.

Related to #7208 and #7191.
