### ISSUE TITLE
Need a link to connection string with TLS encryption

### ISSUE THREAD

**Issue by taleleuma** [MicrosoftDocs/sql-docs#7214]
Following link needs to be added:
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-string-syntax#using-trustservercertificate

That way, developers will know the connection-string-syntax when encryption is configured

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa20275-e415-5531-3ef4-7472d859753b
* Version Independent ID: cc1346a6-9336-91ba-bcff-9fff79847c35
* Content: [Enable encrypted connections - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@taleleuma -- Taleleuma, thank you for your suggestion.  I am updating the article.
