### ISSUE TITLE
Suggestion regarding "Update lock"

### ISSUE THREAD

**Issue by jekic** [MicrosoftDocs/sql-docs#7216]
Hello everybody, 
  In section "Update Lock" you explain that (U) lock is used internally to avoid deadlock when we have SELECT + UPDATE statements, in case when we have REPEATABLE READ or SERIAZABLE transaction isolation level. That is true, but you didn't mention READ COMMITTED isolation level. It is confusing because, as you know,  (U) lock is also used internally during each UPDATE statement during READ COMMITTED isolation level.

Best regards,
  Bojan Jekic
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dae81d65-f7b9-7a97-7fe7-30775f815e5b
* Version Independent ID: d4d339e7-48d7-d159-eb59-13bdedc25b4c
* Content: [Transaction Locking and Row Versioning Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-ver15#Lock_Basics)
* Content Source: [docs/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @LitKnd
* Microsoft Alias: **kendralittle**

**Comment by WilliamAntonRohm** [comment]
@jekic -- Bojan, thank you for your thoughtful feedback.

@LitKnd -- Kendra, please look into this issue.

**Comment by LitKnd** [comment]
Hi @jekic,

Thank you for this feedback. 

This section of the document is short enough that I'm going to go ahead and copy it in here, putting the confusing wording in bold:

> ### Update Locks
> Update (U) locks prevent a common form of deadlock. In a **repeatable read or serializable transaction**, the transaction reads data, acquiring a shared (S) lock on the resource (page or row), and then modifies the data, which requires lock conversion to an exclusive (X) lock. If two transactions acquire shared-mode locks on a resource and then attempt to update data concurrently, one transaction attempts the lock conversion to an exclusive (X) lock. The shared-mode-to-exclusive lock conversion must wait because the exclusive lock for one transaction is not compatible with the shared-mode lock of the other transaction; a lock wait occurs. The second transaction attempts to acquire an exclusive (X) lock for its update. Because both transactions are converting to exclusive (X) locks, and they are each waiting for the other transaction to release its shared-mode lock, a deadlock occurs.

> To avoid this potential deadlock problem, update (U) locks are used. Only one transaction can obtain an update (U) lock to a resource at a time. If a transaction modifies a resource, the update (U) lock is converted to an exclusive (X) lock.

I can't recall how this works regarding in-memory OLTP tables-- I think we might possibly need some wording like "In a transaction against a rowstore table" there. Other folks definitely know, so we will look into this.

Thanks again,
Kendra

Content Developer on the SQL Docs team

**Comment by LitKnd** [comment]
Hello,

Thanks for your patience, and apologies that I have not been able to resolve this issue. I am reassigning this issue within the team as we continue to investigate.

Cheers,
Kendra 

#reassign: rothja

**Comment by rothja** [comment]
@jekic Apologies, again, for the delay in response. @rwestMSFT Randolph, when you get a chance, could you take a look at this issue and see if any doc changes are needed? Thank you! #reassign:rwestMSFT

**Comment by rwestMSFT** [comment]
I have re-opened investigation into this, and I am tracking the issue internally. I will update this issue once we have news, but am closing it in the meantime.

#please-close

**Comment by WilliamDAssafMSFT** [comment]
@jekic We've reviewed the Update Locks section and have update the description including the behavior in multiple isolation levels. Thanks for the feedback. Despite the delay, your feedback has helped improve Microsoft Docs for everyone. A doc update is in flight, look for an update soon.
