### ISSUE TITLE
Misleading info

### ISSUE THREAD

**Issue by madev2020** [MicrosoftDocs/sql-docs#7220]
the following statement is misleading. "Before a capture instance can be created for individual tables, a member of the sysadmin fixed server role (only in SQL Server / Azure SQL Managed Instance) or db_owner must first enable the database for change data capture."

Only Login with Sysadmin rights can enable CDC on database. not db_owner. I tested it with a login which is not sysadmin but has db_owner role on the database. The command "EXEC sys.sp_cdc_enable_db" on that database failed and gave the following error.
"Caller is not authorized to initiate the requested action. Sysadmin privileges are required."

I had to fight with my client about this permission. He is not ready to give sysadmin rights.

Please correct this info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd2adf6-0543-7ca3-3bd5-dd51d0499d7c
* Version Independent ID: 7fdb189c-e1f2-5a99-e2f8-2f683467e016
* Content: [Enable and Disable change data capture - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/enable-and-disable-change-data-capture-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/track-changes/enable-and-disable-change-data-capture-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/enable-and-disable-change-data-capture-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@madev2020 -- thank you for your well-researched feedback.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
Checking with engineering. Thank you.
