### ISSUE TITLE
How to output entire JSON result without losing any at the end

### ISSUE THREAD

**Issue by kuhlaid** [MicrosoftDocs/sql-docs#7222]
The document mentions 'A large result set splits the long JSON string across multiple rows' but does not explain HOW to obtain all the rows in output within SSMS. I keep getting JSON output that is incomplete and need to know how to get ALL of resulting output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb5c17b-c567-303f-00b8-0c8a0ad15fb5
* Version Independent ID: a4ccc766-4a61-5b7a-e5dd-692e3cebb503
* Content: [Format Query Results as JSON with FOR JSON - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by jovanpop-msft** [comment]
Depends on a data access framework that you are using. You will get an ordered result set that you need to concatenate.

There is a docs link to the example with SqlClient:

Other client applications may require code to recombine lengthy results into a single, valid JSON string by concatenating the contents of multiple rows. For an example of this code in a C# application, see [Use FOR JSON output in a C# client app](https://docs.microsoft.com/en-us/sql/relational-databases/json/use-for-json-output-in-sql-server-and-in-client-apps-sql-server?view=sql-server-ver15#use-for-json-output-in-a-c-client-app).

You can find other example in [.Net/NodeJS](https://github.com/microsoft/sql-server-samples/tree/master/samples/features/json/product-catalog) or Dapper: https://github.com/microsoft/sql-server-samples/blob/master/samples/features/json/Dapper-Orm/Controllers/ProductController.cs] on the SQL Server github reporsitory.

**Comment by WilliamAntonRohm** [comment]
@kuhlaid -- thank you for your feedback.

@jovanpop-msft -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
