### ISSUE TITLE
Azure Data Studio should be highlighted in bold

### ISSUE THREAD

**Issue by kuhlaid** [MicrosoftDocs/sql-docs#7223]
The page should mention that **Azure Data Studio** is **WAY** better than SSMS for query results handling, such as getting results saved in JSON formatted to a file (without using 'FOR JSON' query conditions). Now that I know ADS exists, SSMS will be my secondary SQL tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb5c17b-c567-303f-00b8-0c8a0ad15fb5
* Version Independent ID: a4ccc766-4a61-5b7a-e5dd-692e3cebb503
* Content: [Format Query Results as JSON with FOR JSON - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@kuhlaid -- thank you for your positive feedback.

@jovanpop-msft -- please look into this issue.

**Comment by jovanpop-msft** [comment]
@kuhlaid thanks for the feedback, but this is generic tsql language page. Here we are not recommending/favorizing any tool, programming language, or library. Even if handling json is easier in in one language like C# compared to another like Ruby, or in Dapper vs Entity Framework,  we will not make any comparison or recommendation on this page. 
Please propose someone in ADS documentation to explain the benefits and we will add a link here @WilliamAntonRohm does it make sense?

**Comment by jovanpop-msft** [comment]
#assign @WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
#reassign @WilliamAntonRohm

**Comment by dzsquared** [comment]
@jovanpop-msft. @WilliamAntonRohm  the page already mentions in the opening paragraph "Azure Data Studio is the recommended query editor for JSON queries because it auto-formats the JSON results (as seen in this article) instead of displaying a flat string."  I read the request as an ask to bold this sentence so its not as easy to skip.

**Comment by jovanpop-msft** [comment]
I changed this. It will be public today.

**Comment by WilliamAntonRohm** [comment]
@jovanpop-msft -- Jovan, thank you for that update.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
