### ISSUE TITLE
Get-SqlDatabase: Keyword not supported: 'authentication'.

### ISSUE THREAD

**Issue by sartoris** [MicrosoftDocs/sql-docs#7225]
In the PowerShell script, the following line is used to create the connection string:
$connStr = "Server = " + $serverName + "; Database = " + $databaseName + "; Authentication = Active Directory Integrated"

But the following line gives an error message:
$database = Get-SqlDatabase -ConnectionString $connStr

Error message: Get-SqlDatabase: Keyword not supported: 'authentication'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75078545-ecc6-24d3-1f2b-3827e60dc1a2
* Version Independent ID: 4f6f6369-6c88-fb74-5229-c2ec698d11a9
* Content: [Configure Always Encrypted using PowerShell - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/configure-always-encrypted-using-powershell?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/configure-always-encrypted-using-powershell.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/configure-always-encrypted-using-powershell.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by jaszymas** [comment]
Which version of the SqlServer PowerShell module are you using? You can determine the version of the imported/installed module by running the below cmdlets:

Get-Module "SqlServer"
Get-InstalledModule "SqlServer"

**Comment by sartoris** [comment]
21.1.18256

**Comment by Matteo-T** [comment]
Hi @sartoris, could you confirm you are seeing this on PS7 and not PS5.1?

What's the output of $psVersionTable? 

I do see it in PS7, so I can take a look and see what is going on there...

**Comment by sartoris** [comment]
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by Matteo-T** [comment]
Yes, that's what I suspected.

From a conversation with the owners of System.Data.SqlClient on netcore/netstandard, it is by design that that is not supported.

You'd have to wait for the upcoming version 22.x of the module which is supposed to adopt Microsoft.Data.SqlClient: once that happen your scenario should light up automagically.

**Comment by sartoris** [comment]
I suspected as much. .Net Core will get there eventually.

**Comment by Matteo-T** [comment]
@ericfran - I hope I can push a v22-preview out in a couple of weeks. I'm in the final round of validation on waiting on some partner teams to give me the green light.

**Comment by ericfran** [comment]
will it also support the encryption column ?

**Comment by Matteo-T** [comment]
> will it also support the encryption column ?

Kindly elaborate on that question :-)

**Comment by ericfran** [comment]
seems same need on the lib with another option
Issue : for encrypted field in table in Azure SQL + Always encrypted , the POwershell Module SQlServer can't support in connectionsctring  "
 Column Encryption Setting=enabled;"
SetValueInvocationException: Exception setting "ConnectionString": "Keyword not supported: 'column encryption setting'."

**Comment by Matteo-T** [comment]
Yes, same thing.

This is what I have on my machine *right now*:

![image](https://user-images.githubusercontent.com/19174408/163998162-092a58c6-4692-4158-801a-724dedc6802d.png)

which is a lot more exciting than the old one:

![image](https://user-images.githubusercontent.com/19174408/163998344-7df52010-492a-491f-9c93-acc96edf6062.png)

**Comment by ericfran** [comment]
That is great 

Any idea when we could have this on our ‘pc’ ? 😉
Thanks ( no preview possible )

**Comment by Matteo-T** [comment]
I'm pretty much locked and loaded with the "v22 super-alpha preview"...

I do not have an ETA to get out of the preview... it may be a bit (or a lot) down the road, depending on how the preview goes (I expect to make additional breaking changes to modernize the codebase a bit and bring it to a state where I could ideally push it to github.com.

**Comment by ericfran** [comment]
also trying from Azure cloud Shell it doesn't work
