### ISSUE TITLE
Command line error in webpage

### ISSUE THREAD

**Issue by Tcoton** [MicrosoftDocs/sql-docs#7227]
[Enter feedback here]

The section "Install SQL Server" step 1 is written: 
"wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add microsoft.asc" 
and should be 
"wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@Tcoton -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@Tcoton -- this has been updated in #7191.  Thank you again for your feedback.
