### ISSUE TITLE
incorrect docker run quotation postion

### ISSUE THREAD

**Issue by ronking-zhu** [MicrosoftDocs/sql-docs#7231]
[Enter feedback here]
If we are trying to configure collation for a container, it will fail with error 17750.
Msg 17750, Level 16, State 1, Server 454c95bffafdc49, Procedure msdb.dbo.sp_executesql, Line 1
Could not load the DLL (server internal), or one of the DLLs it references. Reason: 126(The specified module could not be found.).

We have already verified this error in RFC 14206077.
1. To set the collation we need to use -e MSSQL_COLLATION="Latin1_General_BIN2" 
2. We may need to restart the container after we change the container. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-bash#pullandrun2019)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@ronking-zhu -- Rozms, thank you for your feedback.

@amvin87 -- Amit, please look into this issue.

**Comment by amvin87** [comment]
Ack, let me take a look into this

**Comment by VanMSFT** [comment]
Following up with @amvin87

**Comment by rwestMSFT** [comment]
I'm tracking this internally. I'll prepare an internal PR shortly and ask @amvin87 for review.

#please-close
