### ISSUE TITLE
note about homebrew installing mac arch-compatible odbc version appears to be false

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [MicrosoftDocs/sql-docs#7235]
This page contains the following "Note" highlighted in Purple:

> The Microsoft ODBC driver for SQL Server on macOS is only supported on the x64 architecture through version 17.7. The Apple M1 (ARM64) is supported starting with version 17.8. The architecture will be detected and the correct package will be automatically installed by the Homebrew formula...

However, I'm on MacOS x64 arch, installed Microsoft ODBC 17 per the instructions below that note on the same page (reproduced below):

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
brew update
HOMEBREW_NO_ENV_FILTERING=1 ACCEPT_EULA=Y brew install msodbcsql17 mssql-tools
```

...and still ended up with  MS ODBC Version 17.8:
 ```
~/maxdev  ls /usr/local/Cellar/msodbcsql17                               | devenv py | 19:33:00
17.8.1.1
```

I'm thinking this "unsupported version" might be why I continue to get the following error when I attempt to make a connection to a MS SQL Server using pyodbc:
```
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'driver' : file not found (0) (SQLDriverConnect)")
```

I've also followed the troubleshooting steps advised in the light-blue "Important" box and the "troubleshooting" sub-section on the same page.

I'm not asking anyone here to troubleshoot my ODBC issues, but wanted to register that based on my experience, it seems that the note up top about homebrew installing version <=17.7 if on MacOS arch64 for compatibility appears to be false. Unless I'm even more lost/confused than I think I am with these odbc errors, which is possible. 

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c0de6fb-19ae-ff6f-8e73-ce66fa94bd64
* Version Independent ID: 34edd099-f4fe-4ac3-cdd4-abc87b35270b
* Content: [Install the Microsoft ODBC driver for SQL Server (macOS) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@MaxPowerWasTaken -- Max, thank you for your well-researched feedback.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
I think the note is confusing. It is meant to say that driver versions up to 17.7 only support x64. Apple M1 (arm64) support was **_added_** starting with version 17.8. I'll update the article.

**Comment by David-Engel** [comment]
The article has been updated and the change will be reflected tomorrow.

BTW, your ODBC error indicates a problem with the connection string you are giving pyODBC. It thinks you are trying to use a driver named "driver". Make sure you are using a connection string similar to: `DRIVER={ODBC Driver 17 for SQL Server};SERVER=test;DATABASE=test;UID=user;PWD=password`

Regards,
David

#please-close
