### ISSUE TITLE
Separate sections for tempdb / model / msdb

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/sql-docs#7238]
Hi, 
  
When you're looking to move model, msdb, and tempdb databases you can easily miss sentence 'This procedure applies to all system databases except the master and Resource databases' in [Planned Relocation and Scheduled Disk Maintenance Procedure](https://docs.microsoft.com/en-us/sql/relational-databases/databases/move-system-databases?view=sql-server-ver15#Planned) and oversee they're included in this article.
Please consider giving model, msdb, and tempdb their own section like master and Resource Database. There are subtle differences for each and by giving them each a section you better see what's included in this article and you have more clear steps per database. It would introduce some repetition, but it would make the article more inclusive, also for people that have less experience as a database administrator. Remember? It was a bit exciting, moving system databases in a critical production environment for the first time.
 
'Stop the instance of SQL Server or shut down the system to perform maintenance. '
If I recall correctly, this is not necessary to move model and msdb. We don't need to introduce downtime if not strictly necessary. For msdb restarting SQL Server Agent comes into play, but not the SQL Server service. 
![image](https://user-images.githubusercontent.com/40343254/151009469-ea303943-d98d-4b35-87c9-68722c578946.png)
 
The word model is not mentioned in this article, [model Database](https://docs.microsoft.com/en-us/sql/relational-databases/databases/model-database?view=sql-server-ver15) does refer to this article. Seeing a section would make it clearer where I need to be. 
![image](https://user-images.githubusercontent.com/40343254/151003142-0954f1fa-4eda-41b7-ac92-e10034b9012a.png)
 
Some for msdb is mentioned in this article but giving it its own section would make the article better readable and oversee what and what not to do in moving msdb (e.g. stop/start SQL Server Agent). [msdb Database](https://docs.microsoft.com/en-us/sql/relational-databases/databases/msdb-database?view=sql-server-ver15) refers to this article. 
![image](https://user-images.githubusercontent.com/40343254/151003577-67ff2619-64fd-4f7c-b307-d21a049fe0b9.png)
 
Tempdb is included in Examples but giving it its own section would make the article better readable.
![image](https://user-images.githubusercontent.com/40343254/151002523-d6933c4a-1c2f-4744-bffb-0c1e6026a59f.png)
 
Thank you for reviewing. 
Kind regards, inge 
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9423e4-0573-7564-3f58-2a8df9a11d9f
* Version Independent ID: 5b88aa32-b6f7-e8eb-806f-fd331ed43133
* Content: [Move System Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/move-system-databases?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/move-system-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/move-system-databases.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@ingebeumer -- Inge, thank you for your thoughtful feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @ingebeumer for this feedback. I agree this article can be improved and have a doc update in flight along these lines. Look for some improvements here soon.
