### ISSUE TITLE
link 'Disk and performance best practices for temporary disk for SQL Server in Azure Virtual Machines'

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/sql-docs#7240]
Hello,
 
Link in 'TempDB configuration options' for 'Disk and performance best practices for temporary disk for SQL Server in Azure Virtual Machines' leads to https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices. Did you really mean to guide towards ASP.NET documentation, or is https://docs.microsoft.com/en-us/azure/azure-sql/virtual-machines/windows/performance-guidelines-best-practices-storage in SQL Server on Azure VM documentation more applicable?
 
Thx for reviewing.
Kind regards, inge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3adb3e3c-6398-7df7-ff9f-472ccf9f0f9e
* Version Independent ID: 616ee859-3bf5-ac5f-3a30-b7559762e9fd
* Content: [Performance Center - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/performance-center-for-sql-server-database-engine-and-azure-sql-database?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/performance-center-for-sql-server-database-engine-and-azure-sql-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/performance-center-for-sql-server-database-engine-and-azure-sql-database.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
