### ISSUE TITLE
Remove confusing note about money data type

### ISSUE THREAD

**Issue by sommarskog** [MicrosoftDocs/sql-docs#7241]
In this topic, https://docs.microsoft.com/en-us/sql/t-sql/data-types/constants-transact-sql?view=sql-server-ver15, there is a note which says that comma are ignored on money literals. This note is incorrect. If you say
```
SELECT $123,12
```
You get two columns, not a single money value. That is, you cannot have commas in money literals at all. You can have commas in a string that you convert to money, and they can be all over the place: 
```
SELECT convert(money, '$1,2,2,3,43')
```
This is issue was raised in this Q&A thread: https://docs.microsoft.com/en-us/answers/questions/707043/sql-server-money-constant-syntax.html.

**Comment by WilliamAntonRohm** [comment]
@sommarskog -- thank you for your thorough feedback.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
@sommarskog  - thank you. Investigating.

**Comment by rwestMSFT** [comment]
@sommarskog I'm putting together a PR to refresh the article and update that note. Would you be happy with this wording?

> Commas are ignored anywhere in a string literal that is cast to the **money** data type.
