### ISSUE TITLE
Please add a step to check/reconfigure SQL Servername

### ISSUE THREAD

**Issue by Tcoton** [MicrosoftDocs/sql-docs#7242]
[Enter feedback here]
I have been struggling for hours not understanding why the aggregation was not working or even did not want to be created in the first place with a message telling me that I was not connected to any of the instances (I was connected to all of them via azure data studio...).
For my lab I am using cloned virtual machines with SQL Server already installed to go a bit faster when everything goes wrong. After the first boot of each machine, you must indeed change the hostname and the /etc/hosts information but you must also change each server name recorded inside SQL Server. The solution is here: https://blog.sqlauthority.com/2015/07/13/sql-server-how-to-change-server-name/

If you don't change the SQL Server names, you will end up with no sync or no aggregation group creation.

Also, there is no root enabled with Ubuntu, you have to do a lot of tricks in order to copy the certificates across servers. What I did without breaking the system security was:

$ sudo bash  #to get a root access to /var/opt/mssql/data from my user folder
cp dbm_* ./ 
chown <username>:root dbm_* #to be able to scp to the replicas (without the chown, a normal user cannot send the file)
scp dbm_* nodex:/home/<username>
exit #to go back to my normal user

on the replicas, you also have to get a root bash so:
$ sudo bash #to get a root access to /var/opt/mssql/data from my user folder
mv dbm_* /var/opt/mssql/data
chown mssql:mssql /var/opt/mssql/data/dbm_*
exit #to go back to my normal user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76df1cf-a234-3768-3c94-b7270d249829
* Version Independent ID: 1235d9a1-8c44-2a11-a213-a1ced144616a
* Content: [Configure availability group for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-configure-ha?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-availability-group-configure-ha.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-availability-group-configure-ha.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @Tcoton - Thanks for the suggestion. I'm adding the following note to the article to clarify it further.

> [!IMPORTANT]
> In the current implementation of the SQL Server resource agent, the node name must match the `ServerName` property from your instance. For example, if your node name is *node1*, make sure SERVERPROPERTY('ServerName') returns *node1* in your SQL Server instance. If there is a mismatch, your replicas will go into a resolving state after the pacemaker resource is created.
>
> A scenario where this rule is important is when using fully qualified domain names. For example, if you use *node1.yourdomain.com* as the node name during cluster setup, make sure SERVERPROPERTY('ServerName') returns *node1.yourdomain.com*, and not just *node1*. The possible workarounds for this problem are:
> - Rename your host name to the FQDN and use `sp_dropserver` and `sp_addserver` store procedures to ensure the metadata in SQL Server matches the change. 
> - Use the `addr` option in the `pcs cluster auth` command to match the node name to the SERVERPROPERTY('ServerName') value and use a static IP as the node address.
