### ISSUE TITLE
Disabling nonclustered indexes on tables

### ISSUE THREAD

**Issue by agg06** [MicrosoftDocs/sql-docs#7244]
To avoid any confusion,  I believe "effect of disabling a nonclustered index on a table" should be explicitly expressed in the section copied below.
 
Regards,

Disabling a nonclustered or clustered index on a **view** physically deletes the index data. Disabling a clustered index on a table prevents access to the data; the data still remains in the table, but is unavailable for data manipulation language (DML) operations until the index is dropped or rebuilt. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2bb45cd-9675-aa90-9ca2-c27774d85e3f
* Version Independent ID: 7ca9be50-df61-4fa3-9254-7879c3b6d120
* Content: [Disable Indexes and Constraints - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/disable-indexes-and-constraints?view=sql-server-ver15)
* Content Source: [docs/relational-databases/indexes/disable-indexes-and-constraints.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/disable-indexes-and-constraints.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@agg06 -- thank you for your suggestion.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
@agg06 - 

The [Limitations and Restrictions](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/disable-indexes-and-constraints?view=sql-server-ver15#Restrictions) section of the article describes the effects of disabling a nonlcustered index.

If you feel free that it is missing some explicit information, please propose an edit to the document. We will review and include it if appropriate.

**Comment by agg06** [comment]
This is my proposal for the section I have mentioned:

Disabling **a clustered index on a view or a nonclustered index** physically deletes the index data. Disabling a clustered index on a table prevents access to the data; the data still remains in the table, but is unavailable for data manipulation language (DML) operations until the index is dropped or rebuilt.

**Comment by agg06** [comment]
I propose a slight modification for the first sentence to make it clear
that disabling a nonclustered index on a table also deletes the index data.
Because recently I witnessed a confusion that the sentence referenced only
indexes on a view.



Disabling a clustered index on a view or a nonclustered index physically
deletes the index data. Disabling a clustered index on a table prevents
access to the data; the data still remains in the table, but is unavailable
for data manipulation language (DML) operations until the index is dropped
or rebuilt.



Mike Ray ***@***.***>, 9 Mar 2022 Çar, 01:24 tarihinde şunu
yazdı:
