### ISSUE TITLE
Overlocalization in the Italian version

### ISSUE THREAD

**Issue by aldonetti** [MicrosoftDocs/sql-docs#7247]
in the localized (Italian) version of this article, the first occurrence of the command "ALTER TABLE" is translated into "MODIFICA TABELLA" while it should NOT be, as it is a SQL Command. thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f23902a4-9a7c-8484-b14b-05be93093e41
* Version Independent ID: 74d1ce47-7ff9-b4e1-767f-e9d1bdb6eab9
* Content: [Replicate Schema Changes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/publish/replicate-schema-changes?view=sql-server-ver15&source=docs)
* Content Source: [docs/relational-databases/replication/publish/replicate-schema-changes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/publish/replicate-schema-changes.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@aldonetti -- Aldo, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
This issue is being tracked by the [localization team](https://ceapex.visualstudio.com/CEINTL/_workitems/edit/581329).
