### ISSUE TITLE
mssql-server-2019-gdr repo metadata not found / HTTP 404

### ISSUE THREAD

**Issue by es-fabricemarie** [MicrosoftDocs/sql-docs#7250]
Hi,

```
# dnf install mssql-server
packages-microsoft-com-mssql-server-2019-gdr                 1.3 kB/s | 162  B     00:00    
Errors during downloading metadata for repository 'packages-microsoft-com-mssql-server-2019-gdr':
  - Status code: 404 for https://packages.microsoft.com/rhel/8/mssql-server-2019-gdr/repodata/repomd.xml (IP: 52.163.211.218)
Error: Failed to download metadata for repo 'packages-microsoft-com-mssql-server-2019-gdr': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

Hope this helps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0f184b8-7d7c-9376-06bf-a08f10ccf30f
* Version Independent ID: 5c233e69-31e2-51ec-7820-2b5326a7a64c
* Content: [Configure Linux repositories for SQL Server 2017 and 2019 - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-change-repo?view=sql-server-ver15&pivots=ld2-rhel#configure-new-repository)
* Content Source: [docs/linux/sql-server-linux-change-repo.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-change-repo.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@es-fabricemarie, @VanMSFT -- Fabrice, Van, please see [my comment](https://github.com/MicrosoftDocs/sql-docs/issues/7249#issuecomment-1023609783) in issue #7249.

**Comment by VanMSFT** [comment]
Hi @es-fabricemarie - Thanks again! This has been updated as well in the doc, and now points to RHEL 7, as there are no GDRs for RHEL 8 and SQL Server 2019 packages

https://github.com/MicrosoftDocs/sql-docs-pr/pull/21096
