### ISSUE TITLE
Screenshot is unreadable

### ISSUE THREAD

**Issue by dewitweb** [MicrosoftDocs/sql-docs#7253]
Hi, 

The screenshot here: https://docs.microsoft.com/en-us/sql/relational-databases/import-export/use-a-format-file-to-skip-a-table-column-sql-server?view=sql-server-ver15#step-1---create-a-default-non-xml-format-file

is not readable. 

please fix this. 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3d260a6-975c-b738-9907-7480f1a9f79e
* Version Independent ID: 28939f55-94c8-e305-95ff-1f023eb33a23
* Content: [Use a Format File to Skip a Table Column (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/use-a-format-file-to-skip-a-table-column-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/import-export/use-a-format-file-to-skip-a-table-column-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/use-a-format-file-to-skip-a-table-column-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@dewitweb -- thank you for catching this.  I am updating this image.  Here is the table in Light theme:

![image](https://user-images.githubusercontent.com/27738025/151606807-950797ed-ceab-485b-aaba-cb78048a553e.png)

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
