### ISSUE TITLE
INSERT INTO: incorrect documentation, missing single-statement TVF as insert target

### ISSUE THREAD

**Issue by OleksiiKovalov** [MicrosoftDocs/sql-docs#7258]
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/insert-transact-sql.md
states:
![image](https://user-images.githubusercontent.com/26844170/151585560-3530ce32-816b-4bc5-b416-92c7a365890c.png)

while it is possible to use Single Statement Table Valued Function (with or without parameters) as target for insert statement
`create table OOPS(id int)
go

create or alter function Buzz(@id int)
returns table
as return(select * from oops where id = @id)
go

insert into dbo.Buzz(1) values(1)
go

select * from oops
go

select * from dbo.buzz(1)
go

`

select @@version
Microsoft SQL Server 2019 (RTM-CU14) (KB5007182) - 15.0.4188.2 (X64)

**Comment by WilliamAntonRohm** [comment]
@OleksiiKovalov -- Oleksii, thank you for your well-researched feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Hi @OleksiiKovalov Thanks for your feedback. While possible, is not a documented pattern for inserts. I'll raise this with the product group to see if this is something we want to fully document and recommend.

**Comment by WilliamDAssafMSFT** [comment]
Hi @OleksiiKovalov Thanks for your feedback. Just an FYI that the product team agrees that while this edge case may be possible, it is not a documented or supported method for inserting data into a table. It was interesting though!
