### ISSUE TITLE
Availability Group Listener creation missing

### ISSUE THREAD

**Issue by Tcoton** [MicrosoftDocs/sql-docs#7263]
[Enter feedback here]
The steps to create an availability group listener are missing and if the listener is missing, the database will be lost at the first failure with no way to recover it other than creating a listener with the virtualIP of the availability group. 

It took me 2 days and lots of research to figure it out why my database was being lost and never coming back as soon as I tried to simulate a failure or manually perform a failover.

A very easy way to test a node failure is to shutdown the interface connection of at least 1 host.

check which interface is linked to the network on a node:
~$ ip address show

shut the interface down:

~$ sudo ip link set <interface> down

and then check what is happening within the cluster and SQL Server.

to reconnect the interface:
~$ sudo ip link set <interface> up

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7de1f2c-d879-9ce4-09fd-251fc3dacc05
* Version Independent ID: 4de58f31-0b21-f4da-2a43-1eb4e8151f00
* Content: [Configure Ubuntu cluster for availability group - SQL Server on Linux](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-cluster-ubuntu?view=sql-server-ver15#create-a-sql-server-login-for-pacemaker)
* Content Source: [docs/linux/sql-server-linux-availability-group-cluster-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-availability-group-cluster-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @Tcoton - Thanks for the feedback! To better clarify the documentation noted, what would you propose we add? The functionality and optional use of a Listener is documented here: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-overview?view=sql-server-ver15#the-listener-under-linux

**Comment by Tcoton** [comment]
Without a  listener, the high availability does work at all so, I don't think it is an option, it is required. I tried it and without a listener, you loose the database as soon as the master is offline or as soon as you initiate a failover with no way to retrieve it. The database becomes unavailable which defeats the purpose of HA! The easiest way would maybe to add a link to the listener webpage as the next step at the end of the source page.

**Comment by rwestMSFT** [comment]
@Tcoton Revisiting this. We will add the referenced link to the top of the page where we mention the listener, and restate that "Note" as a regular paragraph. Thanks for your contribution. Look out for the updated page in the next few days.

**Comment by rwestMSFT** [comment]
#please-close
