### ISSUE TITLE
CREATE FUNCTION: Missed INDEX as table_constraint

### ISSUE THREAD

**Issue by OleksiiKovalov** [MicrosoftDocs/sql-docs#7264]
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-function-transact-sql?view=sql-server-ver15
states that
![image](https://user-images.githubusercontent.com/26844170/151769767-ccaf8b73-d8c5-47f4-affb-04ac8db94b68.png)

no INDEX option defined while SQL Server allows it
`
create or alter  function Test()
returns @result table(id int not null, **index idx (id)**)
as begin
 return 
end
go

`

Alow please note that CLUSTERED/NONCLUSTERED is described - the issue may relate to https://github.com/MicrosoftDocs/sql-docs/issues/7256
@LitKnd

**Comment by WilliamAntonRohm** [comment]
@OleksiiKovalov -- Oleksii, thank you again for your careful feedback.

@LitKnd -- Kendra, please look into this issue, related to #7256.

**Comment by LitKnd** [comment]
Hello,

Apologies for the delay in getting back to you.

The `table_constraint` portion of the syntax map is specific to constraints. the index example that you've given isn't a constraint, so it wouldn't make sense for it to be a part of the constraint syntax.

I will look into whether there is a desire to document this functionality in another part of the syntax map.

Thanks,
Kendra from the Database Docs Team

**Comment by LitKnd** [comment]
Hello,

Apologies for the delay in getting back to you on this-- we have a large volume of Git issues. We appreciate your feedback and your patience! I am reassigning this issue to my most excellent teammate, Randolph.

Kendra from the Database Docs Team

#reassign: @rwestMSFT

**Comment by rwestMSFT** [comment]
@OleksiiKovalov I'm tracking this issue, as well as your related issue, internally. Thank you for raising it.

#please-close.
