### ISSUE TITLE
Central Management Server can be a registered server in CMS

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/sql-docs#7266]
Hi,
 
Please review as guidance here is eligible for improvement.
Articles states 'Note that the Central Management Server cannot be a member of a group that it maintains'. However, registering the Central Management Server itself is possible if you register it including port number: **server\instance,1433**. That way the Central Management Server can be a registered server in CMS.
 
![image](https://user-images.githubusercontent.com/40343254/151827608-e17059a6-67af-46dc-a15e-31db871be200.png)
 
Thank you and kind regards,
Inge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c329f3d-5dc2-c3da-50ff-6a00ab81d1fd
* Version Independent ID: 9996b272-54b9-fcf1-4fdf-50ec43bac5c5
* Content: [Administer multiple servers using Central Management Servers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/administer-multiple-servers-using-central-management-servers?view=sql-server-ver15)
* Content Source: [docs/relational-databases/administer-multiple-servers-using-central-management-servers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/administer-multiple-servers-using-central-management-servers.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@ingebeumer -- Inge, thank you again for your feedback.

@MashaMSFT -- Masha, please look into this issue.

**Comment by ingebeumer** [comment]
close, replace by [contribution #8413(https://github.com/MicrosoftDocs/sql-docs/pull/8413)
