### ISSUE TITLE
CAST/CONVERT: incorrect description of [Length]

### ISSUE THREAD

**Issue by OleksiiKovalov** [MicrosoftDocs/sql-docs#7267]
https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver15
states
![image](https://user-images.githubusercontent.com/26844170/151843161-8eefc200-46dd-4c69-8c28-a54937ff7d5a.png)

but sql server allows this conversion
`
select cast(null as real(26)),convert(real(128),null)
`
pay attention to **real(128)**
https://docs.microsoft.com/en-us/sql/t-sql/data-types/float-and-real-transact-sql?view=sql-server-ver15
states that there is no length for REAL data type

also, 
`
declare @r real(26)
`
produces error
`
Msg 2716, Level 16, State 1, Line 1
Column, parameter, or variable #1: Cannot specify a column width on data type real.
`

SQL version:
Microsoft SQL Server 2019 (RTM-CU14) (KB5007182) - 15.0.4188.2 (X64)

**Comment by WilliamAntonRohm** [comment]
@OleksiiKovalov -- Oleksii, we appreciate your keen attention to the details in our documentation.

@MikeRayMSFT, @markingmyname -- Mike, Mark, please look into this issue.

**Comment by bobbybeard** [comment]
https://www.youtube.com/watch?v=tsGE8DCUm2c

**Comment by MikeRayMSFT** [comment]
@OleksiiKovalov -- 

I agree with @WilliamAntonRohm - thank you for the attention to the details. 

This appears to be a bug in the CAST/CONVERT code. It is likely legacy behavior inherited from older versions of SQL Server. You are welcome to file [feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) to record your experience with the issue and how it impacts you. 

If this causes specific problems for an implementation of the problem, you may [Contact Microsoft Support](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-ver15#contact-microsoft-support).
