### ISSUE TITLE
Column segment image is very blurry.

### ISSUE THREAD

**Issue by Vaccano** [MicrosoftDocs/sql-docs#7268]
The image that has the tool tip "Column segment" is really blurry.  It has text on it that I am not able to read because of how blurry it is.

I would recommend uploading a higher resolution of that image.  Here is screenshot of it for reference:

![image](https://user-images.githubusercontent.com/206109/151885847-8e168de4-62fa-4ed2-bc00-714f440e5dde.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 571bf244-1472-286b-d1a8-7db2e54f40a2
* Version Independent ID: bccbd120-47f3-78b7-0cd6-7d4198ea3604
* Content: [Columnstore indexes: Overview - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-overview?view=sql-server-ver15)
* Content Source: [docs/relational-databases/indexes/columnstore-indexes-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/columnstore-indexes-overview.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@Vaccano -- thank you for your feedback.  I am updating this image.
