### ISSUE TITLE
Link url shown instead of being a link

### ISSUE THREAD

**Issue by rjk** [MicrosoftDocs/sql-docs#7269]
It looks like the text "OPTION ([EXPAND VIEWS](/t-sql/queries/hints-transact-sql-query.md#expand-views))" is intended to be a link to a different page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a452207-5ac2-1a41-c5b1-3baf085a79b4
* Version Independent ID: a590e66c-ed9f-4d80-1511-1864128d2e8e
* Content: [Create Indexed Views - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/views/create-indexed-views?view=sql-server-ver15)
* Content Source: [docs/relational-databases/views/create-indexed-views.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/views/create-indexed-views.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@rjk -- Rory, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
