### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by StuartBV** [MicrosoftDocs/sql-docs#7278]
under "Bytes per index key for memory-optimized tables"
"For indexes on memory-optimized tables, there is no concept of included columns, since all indexes inherently cover of all columns."

last "of" is redundant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 780e3e16-ac52-1343-fe0a-a706c71ddb92
* Version Independent ID: 6f09b278-faa0-6f0d-1013-c1ae62ca006c
* Content: [Maximum capacity specifications for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/sql-server/maximum-capacity-specifications-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/maximum-capacity-specifications-for-sql-server.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@StuartBV -- Stuart, thank you for catching that.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
