### ISSUE TITLE
Misspelling in one of the headings

### ISSUE THREAD

**Issue by Hermholtz** [MicrosoftDocs/sql-docs#7282]
Existing text:

> Follow Up: After you configure the recovery inter**n**al option

Proper text:

> Follow Up: After you configure the recovery inter**v**al option

The entire page is about `recovery interval` option, and there's no user-facing "recovery inter**n**al" stuff in SQL Server.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8da8755-3783-0ca0-d1d0-ce289f1e785f
* Version Independent ID: 53fe9f1e-4eef-9207-ec68-62fa01c8f81c
* Content: [Configure the recovery interval Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-recovery-interval-server-configuration-option?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-the-recovery-interval-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-recovery-interval-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@Hermholtz -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
