### ISSUE TITLE
stdev_physical_io_reads documented twice

### ISSUE THREAD

**Issue by clement911** [MicrosoftDocs/sql-docs#7284]
stdev_physical_io_reads  is listed twice on https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-query-store-runtime-stats-transact-sql?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@clement911 -- Clement, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
