### ISSUE TITLE
If SSMS provides the feature, why don't document it. If it is not provided on SSMS, then mention it.

### ISSUE THREAD

**Issue by Raymond-Zheng** [MicrosoftDocs/sql-docs#7291]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f266259-326d-b74c-2316-cbc37d52eccd
* Version Independent ID: 0f0e7543-fa98-d820-dc20-119160d4d25b
* Content: [Configure read-only routing for an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-read-only-routing-for-an-availability-group-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/configure-read-only-routing-for-an-availability-group-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/configure-read-only-routing-for-an-availability-group-sql-server.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @Raymond-Zheng , thanks for contacting Microsoft and my apologies for the delay as we work through a large backlog of Issues. While your suggestion has merit, it is out of scope for a Git Issue engagement so we're going to start tracking it internally ([61475](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61475)) and address it as resourcing allows. I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
