### ISSUE TITLE
GRANT/DENY/REVOKE: missing UNMASK permission

### ISSUE THREAD

**Issue by OleksiiKovalov** [MicrosoftDocs/sql-docs#7296]
https://docs.microsoft.com/en-us/sql/relational-databases/security/dynamic-data-masking?view=sql-server-ver15#permissions
https://docs.microsoft.com/en-us/sql/relational-databases/security/dynamic-data-masking?view=sql-server-ver15#granting-permissions-to-view-unmasked-data

states that there is **UNMASK** permission

but GRANT/REVOKE/DENY documentation missed it
https://docs.microsoft.com/en-us/sql/t-sql/statements/deny-transact-sql?view=sql-server-ver15
https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-transact-sql?view=sql-server-ver15
https://docs.microsoft.com/en-us/sql/t-sql/statements/revoke-transact-sql?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@OleksiiKovalov -- Oleksii, thank you again for your considered feedback!

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @OleksiiKovalov - Sorry for the delay. Mask permissions are listed in the [Database Permissions](https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-database-permissions-transact-sql?view=sql-server-ver15) articles. Please let us know if there are any concerns.
