### ISSUE TITLE
Format of the code example is not correct

### ISSUE THREAD

**Issue by boyukbas** [MicrosoftDocs/sql-docs#7300]
Format of the code example is not sql but json. If it can be changed, example will be more readable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7174a23f-dd6a-0e3f-22fb-53d6de8e65de
* Version Independent ID: 2f7be91e-000a-6e53-7508-49f0b6aaf996
* Content: [Create reusable code snippets - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/code-snippets?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/code-snippets.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/code-snippets.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@boyukbas -- Baris, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
