### ISSUE TITLE
Error in code example for uninstall

### ISSUE THREAD

**Issue by derek-rlb** [MicrosoftDocs/sql-docs#7307]
The code example `Uninstall-module -Name SQLServer -RequiredVersion "<version number>" -AllowClobber` should read `Uninstall-module -Name SQLServer -RequiredVersion "<version number>"` as the AllowClobber switch is not valid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdc5826c-d266-6f61-e1eb-b4f236d03dd9
* Version Independent ID: 4ab93d92-6a23-a0c0-2911-ce06e99dc5c5
* Content: [Download SQL Server PowerShell Module - SQL Server](https://docs.microsoft.com/en-us/sql/powershell/download-sql-server-ps-module?view=sql-server-ver15)
* Content Source: [docs/powershell/download-sql-server-ps-module.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/download-sql-server-ps-module.md)
* Product: **sql**
* Technology: **sql-server-powershell**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@derek-rlb -- Derek, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
