### ISSUE TITLE
in  doc sys.dm_exec_requests, scheduler_id column wrongly stated as not null

### ISSUE THREAD

**Issue by cllvb** [MicrosoftDocs/sql-docs#7308]
In the sys.dm_exec_requests doc, scheduler_id column's  description is as follows: _ID of the scheduler that is scheduling this request. Is not nullable._
However, for commands like AWAITING COMMAND and TASK MANAGER scheduler_id is null. Also in the view itself scheduler_id is defined as int and null.

![image](https://user-images.githubusercontent.com/99716453/154015563-38df1fb8-bb15-4c02-96ab-e0aa3bdfc10d.png)

![image](https://user-images.githubusercontent.com/99716453/154015607-4bc76aa5-2776-4b55-ba10-02ca4457b063.png)

https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@cllvb -- thank you for your feedback and research.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
