### ISSUE TITLE
v4.1 Support Lifecycle Clarification

### ISSUE THREAD

**Issue by bdschaap** [MicrosoftDocs/sql-docs#7311]
The page says that v4.1 was released on Jan 31, '22 and supported through Nov 19 '24.  However, the page also states that Current releases are only supported for 3 months after the subsequent Current or LTS release.  I'm assuming there will be additional Current or LTS releases prior to Nov 19 '24.  If that's the case then will the end of support for v4.1 change from what's listed?  Or does the page incorrectly state that it will be supported through Nov 19 '24?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f0525e3-c29b-739d-a527-e58ae895b03d
* Version Independent ID: 729065ed-ec43-6733-65bd-a630b7f03b22
* Content: [SqlClient driver support lifecycle - ADO.NET Provider for SQL Server](https://docs.microsoft.com/en-us/sql/connect/ado-net/sqlclient-driver-support-lifecycle?view=sql-server-ver15)
* Content Source: [docs/connect/ado-net/sqlclient-driver-support-lifecycle.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/ado-net/sqlclient-driver-support-lifecycle.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
@bdschaap Thanks for catching that. It was a copy-paste oversight. The end date should have been left blank. I've updated it and it should be reflected in a few hours.

Thanks,
David

#please-close
