### ISSUE TITLE
oracle data source

### ISSUE THREAD

**Issue by cheezewhizze** [MicrosoftDocs/sql-docs#7313]
Really need more information about how to configure an oracle data source.  Eg--where does plugin look for oracle tnsnames.ora file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad5899cc-4757-b131-c36e-a0243b5bad95
* Version Independent ID: 8df879ca-e629-a313-6af9-8a6c3c04eefe
* Content: [Quickstart: Connect and explore Oracle databases - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/quickstart-oracle?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/quickstart-oracle.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/quickstart-oracle.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @nahk-ivanov
* Microsoft Alias: **alexiva**

**Comment by nahk-ivanov** [comment]
Hey,

As mentioned in the article

> please refer to the Oracle documentation on Data Source attribute of the ODP.NET connection string

[Oracle Client Configuration File Settings](https://docs.oracle.com/cd/E85694_01/ODPNT/InstallConfig.htm#ODPNT-GUID-FB680A9A-1182-4C06-874D-56E44B7857B5)

We included it in the README for the extension:

> In order to use _TNS Alias_ as a data source, make sure that `ORACLE_HOME` environment variable is set and _TNSNAMES.ORA_ file is located in the `<ORACLE_HOME>/network/admin` folder.

I suppose we need to duplicate it in the article as well.

Regards,
Alex.

**Comment by cheezewhizze** [comment]
Thanks!  This is very helpful.

From: Alexander Ivanov ***@***.***>
Sent: Tuesday, February 15, 2022 6:28 PM
To: MicrosoftDocs/sql-docs ***@***.***>
Cc: cheezewhizze ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/sql-docs] oracle data source (Issue #7313)

This message was sent from outside your organisation. Please do not click links or open attachments unless you recognize the source of this email and know the content is safe.

Hey,

As mentioned in the article

please refer to the Oracle documentation on Data Source attribute of the ODP.NET connection string

Oracle Client Configuration File Settings<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.oracle.com%2Fcd%2FE85694_01%2FODPNT%2FInstallConfig.htm%23ODPNT-GUID-FB680A9A-1182-4C06-874D-56E44B7857B5&data=04%7C01%7Cghp5h%40law.virginia.edu%7Cd56d66e4fef14216717108d9f0dacfa5%7Cb8a81d5c51694b0ca890c4ffc7cf0c85%7C0%7C0%7C637805644866109459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fL4%2BFp8p%2BCde3IIKpwHbyDLDNsG1Usxz%2BNXkhManVhA%3D&reserved=0>

We included it in the README for the extension:

In order to use TNS Alias as a data source, make sure that ORACLE_HOME environment variable is set and TNSNAMES.ORA file is located in the <ORACLE_HOME>/network/admin folder.

I suppose we need to duplicate it in the article as well.

Regards,
Alex.

-
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fsql-docs%2Fissues%2F7313%23issuecomment-1040901652&data=04%7C01%7Cghp5h%40law.virginia.edu%7Cd56d66e4fef14216717108d9f0dacfa5%7Cb8a81d5c51694b0ca890c4ffc7cf0c85%7C0%7C0%7C637805644866109459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wdbEJlTkPFcFnhW0zndDbp2SHCmIWZvGIXtQWCYSVkA%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAJVHOU5H2EH6EXC5NDVHF3U3LOQDANCNFSM5OP64O3Q&data=04%7C01%7Cghp5h%40law.virginia.edu%7Cd56d66e4fef14216717108d9f0dacfa5%7Cb8a81d5c51694b0ca890c4ffc7cf0c85%7C0%7C0%7C637805644866109459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Mdu6mYnKUYtlEKVRvotFU5yC5%2FIlMNhj8GFur99lsyU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cghp5h%40law.virginia.edu%7Cd56d66e4fef14216717108d9f0dacfa5%7Cb8a81d5c51694b0ca890c4ffc7cf0c85%7C0%7C0%7C637805644866109459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0odEUq5Ch3MTwyenAjWxvwvG5XyhsDjACSAEe1bjmLw%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cghp5h%40law.virginia.edu%7Cd56d66e4fef14216717108d9f0dacfa5%7Cb8a81d5c51694b0ca890c4ffc7cf0c85%7C0%7C0%7C637805644866109459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gPP%2FsFD7WmZAZrPtlI%2Bu4oWlRruWBoyblaW%2F2YMkHwU%3D&reserved=0>.

**Comment by WilliamAntonRohm** [comment]
@cheezewhizze -- thank you for your question.

@nahk-ivanov -- thank you for your clarification.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
