### ISSUE TITLE
Typo -> Get instance name from Configuration Manger

### ISSUE THREAD

**Issue by enemvi** [MicrosoftDocs/sql-docs#7316]
Typo -> Get instance name from Configuration **Manger**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6591785-4e97-b587-dc5f-4c03f8612789
* Version Independent ID: 5afdb02a-950d-b73d-2b02-5b1fc993279b
* Content: [Troubleshoot connecting to the SQL Server Database Engine - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/troubleshoot-connecting-to-the-sql-server-database-engine?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/troubleshoot-connecting-to-the-sql-server-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/troubleshoot-connecting-to-the-sql-server-database-engine.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@enemvi -- thank you for catching this.  I am updating the article.
