### ISSUE TITLE
Typo in "docker run" command

### ISSUE THREAD

**Issue by phooey** [MicrosoftDocs/sql-docs#7318]
There's a typo in the following command on the page:
```
sudo docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=<YourStrong@Passw0rd>" \
   -p 1433:1433 --name sql1 -hostname sql1 \
   -d mcr.microsoft.com/mssql/server:2019-latest
```

giving me the following error:
```
Unable to find image 'sql1:latest' locally
docker: Error response from daemon: pull access denied for sql1, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

Changing "-hostname" to "--hostname" or "-h" makes it work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-bash)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@phooey -- Mattias, thank you for reporting this issue.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
