### ISSUE TITLE
Use standard JSON terms to describe Transact-SQL output with FOR JSON

### ISSUE THREAD

**Issue by hekaplex** [MicrosoftDocs/sql-docs#7319]
It would be nice to use terms like JSON array and JSON object top make it easier for JSON devs to map different use cases of nested structure.  for example, having a three deep object/array hierarchy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6780fe4-5238-8607-8343-b8affadff8e2
* Version Independent ID: aa89f52b-328d-38b9-7b23-7f7de8ac8b25
* Content: [Use FOR JSON output in SQL Server and in client apps - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/use-for-json-output-in-sql-server-and-in-client-apps-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/json/use-for-json-output-in-sql-server-and-in-client-apps-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/use-for-json-output-in-sql-server-and-in-client-apps-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@hekaplex -- thank you for your considered feedback.

@jovanpop-msft -- please look into this issue.

**Comment by jovanpop-msft** [comment]
JSON array is used in most of the doc. 
"JSON output" is used when the output can be object or array.
"JSON text" is used when a text is placed in (N)VARCHAR columns. @hekaplex could you describe what exactly should be changed on this page?

**Comment by hekaplex** [comment]
You colleagues have a great example that actually uses words like array and structure to make it possible for non-SQL JSON devs to understand how to use the APIs here: https://docs.microsoft.com/en-us/azure/synapse-analytics/sql/query-parquet-nested-types

Not here to do y'all's job for free; even this article is still dropping the ball on exact code samples that can run without recoding as had been the gold standard when I was in SQL Support '00-'06

Good luck and a little fit and finish will go a long way for self service documentation.

**Comment by rwestMSFT** [comment]
I am closing this issue. We have a massive backlog, so this enhancement is unlikely to be done in the foreseeable future.

If you change your mind on helping the Database Docs team, we would welcome a pull request.
