### ISSUE TITLE
Data Definition Language Events and Event Groups image is unreadable

### ISSUE THREAD

**Issue by davidbaxterbrowne** [MicrosoftDocs/sql-docs#7320]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ceff698-5e6d-3209-ab90-ef3d1d5013a3
* Version Independent ID: e49ecab0-3f88-c5cf-bed4-7d5880a72d77
* Content: [WMI Provider for Server Events Classes and Properties - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/wmi-provider-server-events/wmi-provider-for-server-events-classes-and-properties?view=sql-server-ver15)
* Content Source: [docs/relational-databases/wmi-provider-server-events/wmi-provider-for-server-events-classes-and-properties.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/wmi-provider-server-events/wmi-provider-for-server-events-classes-and-properties.md)
* Product: **sql**
* Technology: **wmi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@davidbaxterbrowne -- David, thank you for bringing this to our attention.  I am updating the article.
