### ISSUE TITLE
Applies to should not include any Azure products

### ISSUE THREAD

**Issue by sqlgreen** [MicrosoftDocs/sql-docs#7327]
The "Applies to" lists several Azure products, none of which support OLE automation, this is only available in "SQL Server". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a877a1-3eb7-8504-23fe-6421955f5b9d
* Version Independent ID: c1d001c6-3267-2f34-4fe0-dd819c6505fb
* Content: [OLE Automation Sample Script - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/ole-automation-sample-script?view=sql-server-ver15)
* Content Source: [docs/relational-databases/stored-procedures/ole-automation-sample-script.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/stored-procedures/ole-automation-sample-script.md)
* Product: **sql**
* Technology: **stored-procedures**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@sqlgreen -- Darren, thank you for your feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @SQLGreen, you are correct that other platforms do not support OLE Automation and have been incorrectly applied to these samples. Will resolve with a doc update in flight. Thanks again for this feedback, your suggestions help improve our documentation.
