### ISSUE TITLE
Incorrect documentation: SELECT Clause - missing string literal aliases

### ISSUE THREAD

**Issue by OleksiiKovalov** [MicrosoftDocs/sql-docs#7329]
https://docs.microsoft.com/en-us/sql/t-sql/queries/select-clause-transact-sql
Documentation missing mentioning "string literal as column alias"
this feature is deprecated but still supported by SQL Server (at least) up to V2019
I think string literals as column alias should be described with their "deprecated" status

**Comment by WilliamAntonRohm** [comment]
@OleksiiKovalov -- Oleksii, thank you for your close reading of our documentation.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @OleksiiKovalov - Thanks for the feedback. We'll review this request and see if an update to the doc is needed.

**Comment by VanMSFT** [comment]
@OleksiiKovalov - Thanks again for the feedback. Upon review, not documenting a deprecated feature is intentional. Although users may use the functionality, it's not something we encourage, and have chosen to leave out. We appreciate your time submitting this issue. Feel free to let us know if there are concerns.

**Comment by OleksiiKovalov** [comment]
hi @VanMSFT 
as for now this syntax is legal and supported - with no notion that it is deprecated and will be removed in future versions and that users should rewrite/not use this syntax.
Deprecate notice can be found in many SQL articles (eg https://docs.microsoft.com/en-us/sql/t-sql/statements/set-fmtonly-transact-sql?view=sql-server-ver15 or https://docs.microsoft.com/en-us/sql/t-sql/statements/set-rowcount-transact-sql?view=sql-server-ver15)
Having this syntax not described by documentation is confusing - looks like (and technically it is true) the user uses some non-documented and therefore illegal feature - while it is not true.
I'm sure that documentation must have "deprecate notice" about this syntax.

**Comment by VanMSFT** [comment]
Hi @OleksiiKovalov - The deprecated notice is here: https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/bb510662(v=sql.110)?redirectedfrom=MSDN
