### ISSUE TITLE
systemctl

### ISSUE THREAD

**Issue by crashXJ** [MicrosoftDocs/sql-docs#7336]
Really should clarify this will not work on WSL when using systemctl.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a7eacd-7e91-3dac-8c5b-873d9dcdf89f
* Version Independent ID: 4fa4b92d-178b-7997-a095-3b2bef2ebabb
* Content: [Troubleshooting SQL Server Docker containers - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-troubleshooting?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-docker-container-troubleshooting.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-docker-container-troubleshooting.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@crashXJ -- thank you for your feedback.

@amvin87 -- please look into this issue.

**Comment by amvin87** [comment]
We do not support SQL Server containers on WSL. The supported platforms to host SQL Server container are same as the platforms that support SQL Server on Linux distros mentioned here: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup?view=sql-server-ver15#supportedplatforms

Thus, the documentation is only meant for SQL Server container images being run on RHEL, k8s, Ubuntu, SLES platforms and not for WSL.

**Comment by crashXJ** [comment]
This is about "systemctl" not working in WSL.  Instead I need to use
"service <something>" and that is what I am referring to.

**Comment by rwestMSFT** [comment]
@crashXJ Thank you for your comments. I am closing this issue because WSL is not a supported platform for running SQL Server on Linux.

#please-close
