### ISSUE TITLE
AlwaysEncrypted docs out of date and/or incomplete

### ISSUE THREAD

**Issue by joschmo80** [MicrosoftDocs/sql-docs#7338]
[Enter feedback here]
Docs out of date and/or incomplete

Per EFCore team recommendation [here](https://github.com/dotnet/efcore/issues/27499) from @roji, requesting doc updates:

- No instructions on how to configure AlwaysEncrypted directly from C# (SMO, EFCore, SqlClient, etc.).
- Instructions for configuring AlwaysEncrypted from PowerShell do not work with PowerShell 7+.
   -  Per [this](https://docs.microsoft.com/en-us/powershell/module/sqlserver/set-sqlcolumnencryption?view=sqlserver-ps), Set-SqlColumnEncryption is only supported in PowerShell 5.  As an aside, that page should ideally say what is the recommended alternative command to use with PowerShell 7+.
   - For this reason, calling the PowerShell code directly from .NET Core C# code leads to dll hell, as the former requires .NET Framework dll's loaded, and the latter .NET Core.
   - I was able to get this working by forking a separate PowerShell 5 process to run the powershell.  This allowed me to avoid the dll hell scenario.
- Instructions for configuring AlwaysEncrypted from SSMS is not always feasible.
  - For example, I develop medical device software.  Encryption of Patient Health Info (PHI) is critical, and deploying SSMS on every customer machine is not feasible. 
- I found an example [online](https://stackoverflow.com/questions/41027953/sql-server-always-encrypted-with-net-core-not-compatible) for AzureKeyValaultProvider, but this is not always feasible.
  - Going back to my example, hospital medical devices often do not have internet access, therefore the local (Win10) certificate manager must be used. 

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc717e21-1e3c-35b0-26ee-901c41deb303
* Version Independent ID: 33167cb3-1a89-f9df-c561-f1e474b249c7
* Content: [Create & store column master keys for Always Encrypted - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/create-and-store-column-master-keys-always-encrypted?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/encryption/create-and-store-column-master-keys-always-encrypted.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/create-and-store-column-master-keys-always-encrypted.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@joschmo80 -- thank you for your thorough feedback.

@jaszymas -- please look into this issue.

**Comment by VanMSFT** [comment]
@jaszymas @shohamMSFT - Can you please follow-up on this with feedback? Thanks!

**Comment by fepettersen** [comment]
Any movemet at all on this? The issue has been open for 8 months now!

**Comment by brian909** [comment]
Any updates?

**Comment by VanMSFT** [comment]
Sorry for the delay. @joschmo80 and @brian909 - If I'm not mistaken, our doc was updated with support for Always Encrypted using .NET Core. If these docs do not address your questions, please let us know what specifically is missing.

https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/tutorial-always-encrypted-enclaves-develop-net-apps?view=sql-server-ver16

https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/sqlclient-support-always-encrypted?view=sql-server-ver16

@Pietervanhove for any comments

**Comment by brian909** [comment]
I've seen the docs and it doesn't really seem to address entity framework core, there's some code in there for ADO.Net. I'm looking for documentation on the `AzureKeyVaultProvider` with ef.

**Comment by VanMSFT** [comment]
@brian909 - An example of using `AzureKeyVaultProvider` is shown here: https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-key-vault-example?view=sql-server-ver16. Unfortunately, we do not specifically target instructions for EF Core in SQL Documentation. If it is supported, we will notate that, but for any tutorials, that will need to be addressed with the EF Core Product Team.
