### ISSUE TITLE
Clarify ordering guarantees on OUTPUT clause (without INTO)

### ISSUE THREAD

**Issue by roji** [MicrosoftDocs/sql-docs#7339]
Hi, I'm an engineer on the Entity Framework team working on SQL Server performance improvements, and would like to be sure about an important point.

[The docs on the OUTPUT clause](https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?view=sql-server-ver15#remarks) contain this remark:

> There is no guarantee that the order in which the changes are applied to the table and the order in which the rows are inserted into the output table or table variable will correspond.

This note is quite clear; however, since "output table or table variable" are discussed, it seems to refer to the `OUTPUT INTO` clause. It isn't clear what the ordering guarantees are for a plain OUTPUT clause, without INTO.  For example, consider the following INSERT:

```sql
INSERT INTO Foo (Bar) OUTPUT INSERTED.Id (‘a’), (‘b’), (‘c’)
```

Assuming that Id is e.g. an IDENTITY column… is it guaranteed the resulting rows would contain increasing values (e.g. 1, 2, 3), and that those values would correspond to the provided ‘a’, ‘b’, ‘c’ values? This is very important for matching the generated IDs back to the correct data on the client, so that e.g. ID 1 is known to correspond to ‘a’, 2 to ‘b’ etc. AFAIK in most/all other databases this is the behavior, and it’s quite important.

If SQL Server doesn't make the above guarantees, it may be a good idea to amend the note to make that clear for OUTPUT without INTO.

**Comment by WilliamAntonRohm** [comment]
@roji -- Shay, thank you for your well-researched feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Looking into this issue

**Comment by rwestMSFT** [comment]
@roji I spoke with a PM in the SQL product group, and the order isn't guaranteed for `OUTPUT` at all, so you can think of the behaviour as the same, with or without `INTO`.

I'll make a note in the article.
