### ISSUE TITLE
Error in XML Format file examples leading to unexpected element "BCPFORMAT" error when used

### ISSUE THREAD

**Issue by petergoodrum** [MicrosoftDocs/sql-docs#7344]
XML Format files examples quoted on this page do not work.  Using example as is in SQL statement of the form: 

`BULK INSERT [TABLE_NAME] WITH (FORMATFILE = [FILENAME); `

results in:

```
Msg 4855, Level 16, State 1, Line 1
Line 2 in format file ...... unexpected element "BCPFORMAT"."
```
Root cause is the xmlns being https in the example.  Change from:

`<BCPFORMAT xmlns="https://schemas.microsoft.com/sqlserver/2004/bulkload/format" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`

to:

`<BCPFORMAT xmlns="http://schemas.microsoft.com/sqlserver/2004/bulkload/format" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`

and the BULK INSERT using the XML format file will then work.  

I expect it's because the XSD itself at https://schemas.microsoft.com/sqlserver/2004/bulkload/format/bulkloadschema.xsd specifies http, not https

`<xsd:schema xmlns:xsd="[http://www.w3.org/2001/XMLSchema]()" xmlns:bl="[http://schemas.microsoft.com/sqlserver/2004/bulkload/format]()" targetNamespace="[http://schemas.microsoft.com/sqlserver/2004/bulkload/format]()" elementFormDefault="[qualified]()" attributeFormDefault="[unqualified]()">`

Is it exceptionally unhelpful to have MS documentation providing examples that do not actually run successfully.  Issue has been raised by people on Stackoverflow https://stackoverflow.com/questions/54373618/why-does-format-file-cause-error-during-sql-server-bulk-insert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb0962c3-2d6a-9120-c5b7-70d2fb93cd23
* Version Independent ID: e1a70d77-ace8-1a16-bbc8-ccd7acde5880
* Content: [XML Format Files (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/xml-format-files-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/import-export/xml-format-files-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/xml-format-files-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@petergoodrum -- thank you for your well-researched feedback.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- Masha, please review this change in [private PR 21351](https://github.com/MicrosoftDocs/sql-docs-pr/pull/21351).
