### ISSUE TITLE
Link to Temporal Tables documentation under "See Also"

### ISSUE THREAD

**Issue by HarryDriscollTWE** [MicrosoftDocs/sql-docs#7346]
You should probably include a link to Temporal Tables under the "See Also" section.
https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 015ca28b-f0f3-c5b0-b2b6-b0a546fd4e17
* Version Independent ID: 1d340e3e-6e9e-1463-e9be-16e7d5a8062a
* Content: [What is change data capture (CDC)? - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/about-change-data-capture-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/track-changes/about-change-data-capture-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/about-change-data-capture-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@HarryDriscollTWE -- Harry, thank you for your suggestion.  I am updating this article.
