### ISSUE TITLE
Download links for SSMS 18.10 and 18.9.2 are targeting the same resource

### ISSUE THREAD

**Issue by hS6ZQZHwgT** [MicrosoftDocs/sql-docs#7347]
Download links for SSMS 18.10 and 18.9.2 are targeting the same resource (SSMS 18.9.2, build 15.0.18386.0)
Download SSMS 18.10 `https://go.microsoft.com/fwlink/?linkid=2168063`
Download SSMS 18.9.2 `https://go.microsoft.com/fwlink/?linkid=2168063`
source uri: [Release notes for (SSMS) - SQL Server Management Studio (SSMS) | Microsoft Docs](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver15)

**Comment by WilliamAntonRohm** [comment]
@hS6ZQZHwgT -- thank you for catching this.  I am updating the article.

**Comment by hS6ZQZHwgT** [comment]
Following up; it appears the correct uri for the download should be [https://go.microsoft.com/fwlink/?linkid=2174135](https://go.microsoft.com/fwlink/?linkid=2174135). I was able to successfully acquire the 18.10 installer with this uri.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
