### ISSUE TITLE
please add string_split to support empty string as separator

### ISSUE THREAD

**Issue by giacatluong** [MicrosoftDocs/sql-docs#7352]
Would like to add this feature..  
such as select string_plit('abc', '') 
would return
a
b
c

**Comment by WilliamAntonRohm** [comment]
@giacatluong -- thank you for your suggestion.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
