### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by BrianPainter88** [MicrosoftDocs/sql-docs#7355]
Under `Features added > Secure by default > details`, there is a typo in which it says `cliend-side` instead of `client-side` in the **BREAKING CHANGE** section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c317ca97-aeb0-47ad-32c1-96dac03228db
* Version Independent ID: 0a218c3e-da57-7e34-7bff-9c41fe5f4dc5
* Content: [Release notes for OLE DB Driver - OLE DB Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/oledb/release-notes-for-oledb-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/oledb/release-notes-for-oledb-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/oledb/release-notes-for-oledb-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
Thanks for catching that! It's been fixed and the change should be reflected on the website later this afternoon.

Regards,
David

#please-close
