### ISSUE TITLE
Statement about Borland Database Engine inaccurate and misleading

### ISSUE THREAD

**Issue by PaulenAndrew** [MicrosoftDocs/sql-docs#7356]
The statement about Borland Database Engine is inaccurate and mislead me. BDE was only ever required for dBASE and Paradox, and has not been required at all since around 2000 because of KB 263561.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08b5d2e2-4ca0-a8da-4478-055fdfd58aca
* Version Independent ID: 15d1c7b2-286f-a26d-26a5-0ac13deea86f
* Content: [Paradox Driver Programming Considerations - Open Database Connectivity (ODBC)](https://docs.microsoft.com/en-us/sql/odbc/microsoft/paradox-driver-programming-considerations?view=sql-server-ver15)
* Content Source: [docs/odbc/microsoft/paradox-driver-programming-considerations.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/microsoft/paradox-driver-programming-considerations.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
Thanks for reporting the inaccuracy. The note has been removed. The change should be reflected on the website later this afternoon (PST).

Thanks,
David

#please-close

**Comment by PaulenAndrew** [comment]
My feedback was based on a KB article that is no longer available:
https://web.archive.org/web/20070117151111/http://support.microsoft.com:80/kb/263561/en-us

During testing, I discovered that the Paradox driver _does_ appear to depend on the BDE.

Windows 10 Pro, 21H2, 19044.1586
msjet40.dll 4.0.9801.32
mspbde40.dll 4.0.9801.1

Similar to this article, I found that there is a "BDE" registry entry for the Paradox driver too:
https://web.archive.org/web/20070117031818/http://support.microsoft.com/kb/248841/EN-US/

If the BDE is installed, it works unless BDE is DWORD(2).

If the BDE is not installed:
1. If the value of BDE is (DWORD)2, presumably meaning never use the BDE, it fails to open an ADO connection that uses Jet/Paradox, "Invalid operation".
2. If the value of BDE is (DWORD)1, presumably meaning always use the BDE, it fails to open an ADO connection.
3. If the value of BDE is (DWORD)0, which is the default, presumably meaning use the BDE if installed, it fails to open an ADO connection, "Invalid operation".

If this is true, though, it would mean that Microsoft reversed their decision, apparently without documenting it, and reinstated a dependency on 90s era software. So I am skeptical. Does anyone actually have the correct information on this?

**Comment by David-Engel** [comment]
> If this is true, though, it would mean that Microsoft reversed their decision, apparently without documenting it, and reinstated a dependency on 90s era software. So I am skeptical. and apologies for my assumption. Does anyone actually have the correct information on this?

The Paradox driver and Jet engine technology is basically from the 90s.
https://docs.microsoft.com/en-us/sql/odbc/microsoft/history-of-the-desktop-database-drivers?view=sql-server-ver15
https://en.wikipedia.org/wiki/Access_Database_Engine#History

I'm not the authority, but I bet it's only in Windows to maintain backwards compatibility and probably falls under these legacy and/or deprecated components.
https://docs.microsoft.com/en-us/sql/connect/connect-history?view=sql-server-ver15#deprecated-mdacwdac-components

It seems you discovered the current behavior. I've added the previous note back to the doc page. If you truly require an answer from an authoritative owner, you will need to go through Microsoft Support, who can raise the question with the owners of the files in question.

Regards,
David

**Comment by PaulenAndrew** [comment]
That sounds like a good way to handle it, sorry for the wasted effort.

Yes, I gathered it's deprecated, and to get it to work at all there are a lot of caveats and limitations that are _mostly_ well documented.
