### ISSUE TITLE
Azure Data Studio 1.35 german release notes missing

### ISSUE THREAD

**Issue by kraiz** [MicrosoftDocs/sql-docs#7357]
Opened the fresh installed version 1.35 of Azure Data Studio. Notification pops up telling that the release notes are just a button click away. On the opened documentation page the 'latest' version is 1.34.

I always like to read about new features. Please update the release note page soon.

edit:
I just discovered that it's just the german version which is not update to date. Leaving the issue here. Feel free to close as it's not important for me. I prefer the english one.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f818cae2-8091-38c6-217c-328f5aa12b99
* Version Independent ID: 0a6efa72-49c2-12c4-4095-8fc094747b14
* Content: [Azure Data Studio-Versionshinweise - Azure Data Studio](https://docs.microsoft.com/de-de/sql/azure-data-studio/release-notes-azure-data-studio?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/release-notes-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs-pr.de-de/blob/live/docs/azure-data-studio/release-notes-azure-data-studio.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
@kraiz -- Lars, thank you for catching this.

@yualan -- Alan, please look into this issue.

**Comment by dzsquared** [comment]
Checking into this, it looks like both ADS and SSMS pages are stuck in localization.

**Comment by erinstellato-ms** [comment]
#reassign @SunnyDeng

**Comment by TimShererWithAquent** [comment]
@yualan Alan - Not sure how you got unassigned to this. There's an assigned to author tag. 

If this is in process for localization, we should close the issue.

**Comment by erinstellato-ms** [comment]
@TimShererWithAquent I had moved this to Sunny Deng (and away from @yualan) because it was my understanding that they could help address this.  I have opened a feedback item internally (Feedback 589785: Update Azure Data Release Notes for German Localization - Boards (visualstudio.com)) to address this localization issue.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [Azure Data Studio repo](https://github.com/microsoft/azuredatastudio).
