### ISSUE TITLE
SQL Managed Instance - CMK - EventName: MakeDatabaseInaccessible

### ISSUE THREAD

**Issue by felickz** [MicrosoftDocs/sql-docs#7360]
When DB loses access to key, this `MakeDatabaseInaccessible` event is no longer fired - it is now 30 minutes instead of 8 hours - please have documentation updated. Also please include how customer can monitor and alert on this critical event in real time ( seeing these similar critical events severely delayed).

```
EventName: MakeDatabaseInaccessible
Status: InProgress
Description: Database is waiting for Azure key vault key access to be reestablished by user within 8 hours. 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b6d066-9a0d-ebdb-7432-fb4ae7a82794
* Version Independent ID: 645e4ba4-7898-c2ec-bbb4-c39aecb7e21f
* Content: [Common errors with customer-managed keys in Azure Key Vault - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/troubleshoot-tde?view=azure-sqldw-latest#feedback)
* Content Source: [docs/relational-databases/security/encryption/troubleshoot-tde.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/troubleshoot-tde.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @shohamMSFT
* Microsoft Alias: **shohamd**

**Comment by shohamMSFT** [comment]
@felickz Thanks for the feedback! We are working on updating this document asap and I will revert back as soon as it is completed.

**Comment by shohamMSFT** [comment]
@felickz This document has now been updated with the events that appear in the Activity Log during Inaccessible Database scenario. Thanks!

**Comment by shohamMSFT** [comment]
#please-close
