### ISSUE TITLE
Synapse Analytics MERGE examples do not work due to unsupported OUTPUT clause

### ISSUE THREAD

**Issue by andrewMSFT** [MicrosoftDocs/sql-docs#7361]
Please remove the A, B and D examples from the MERGE doc for Synapse Analytics.  They all currently have OUTPUT clauses, which is not supported.   This is HIGHLY confusing to users.

[MERGE](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/merge-transact-sql.md)

**Comment by WilliamAntonRohm** [comment]
@andrewMSFT -- Andrew, thank you for bringing this up.

@XiaoyuMSFT -- Xiaoyu, please look into this issue.

**Comment by mstehrani** [comment]
This has been fixed in the Synapse MERGE doc and should be reflected within a day. #please-close
