### ISSUE TITLE
C# indexing should use square brackets

### ISSUE THREAD

**Issue by PumpkinVision** [MicrosoftDocs/sql-docs#7373]
[Enter feedback here]
The C# examples should use square brackets, not parentheses, for indexing.
Example:
srv.Databases("AdventureWorks2012").Tables("Person", "Person").Columns("LastName").Nullable = true;

should be

srv.Databases["AdventureWorks2012"].Tables["Person", "Person"].Columns["LastName"].Nullable = true;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e3f65c8-21f2-d580-2b1e-8977dc2820a2
* Version Independent ID: 403b1055-ba5a-b2cd-142a-8aa81bb55897
* Content: [Using Collections - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/create-program/using-collections?view=sql-server-ver15)
* Content Source: [docs/relational-databases/server-management-objects-smo/create-program/using-collections.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/server-management-objects-smo/create-program/using-collections.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@PumpkinVision -- thank you for catching this.  I am updating the article.
