### ISSUE TITLE
Synapse COPY INTO AUTO CREATE TABLE options

### ISSUE THREAD

**Issue by sdebruyn** [MicrosoftDocs/sql-docs#7376]
The option AUTO CREATE TABLE documented on https://docs.microsoft.com/en-us/sql/t-sql/statements/copy-into-transact-sql?view=azure-sqldw-latest uses some options to create the table but these are not documented. E.g. I want to have HEAP tables with distribution ROUND ROBIN, but apparently the option creates CCI tables.

**Comment by WilliamAntonRohm** [comment]
@sdebruyn -- Sam, thank you again for your feedback.

@MikeRayMSFT -- Mike, please look into this issue.
