### ISSUE TITLE
Synapse COPY INTO data type mapping

### ISSUE THREAD

**Issue by sdebruyn** [MicrosoftDocs/sql-docs#7377]
Regarding the COPY INTO option documented on https://docs.microsoft.com/en-us/sql/t-sql/statements/copy-into-transact-sql?view=azure-sqldw-latest

The statement expects a table with a certain schema so that the schema matches the files in the storage account. You need to create your table with that specific schema or you get unclear errors (or no errors at all, which is also not good because your table remains empty for an unknown reason...)

Please document for the supported file formats which data types map to which data types in Synapse SQL.

**Comment by WilliamAntonRohm** [comment]
@sdebruyn -- Sam, thank you for your close reading.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by MikeRayMSFT** [comment]
@sdebruyn  - thanks for this. Apologies for the slow response. I'm looking at options for an appropriate update. 

I think a link to https://learn.microsoft.com/en-us/sql/tools/synapse-pathway/data-type-mappings-microsoft-sql-server?view=azure-sqldw-latest may help.

But let me review and get back to you.

**Comment by WilliamDAssafMSFT** [comment]
@sdebruyn as you can imagine, the external storage/database platform can vary this answer. In general, ODBC data type mappings are a good place to start and could be helpful with whatever external storage and file format you're using. As well as Mike's link, Data Factory documentation covers a lot of ground here: 
https://learn.microsoft.com/azure/data-factory/connector-azure-sql-data-warehouse?tabs=data-factory
https://learn.microsoft.com/azure/data-factory/copy-activity-schema-and-type-mapping#data-type-mapping

This can be tricky, we'll keep this feedback in mind. If you have specific storage-to-Synapse troubleshooting, this may not be the best forum. I recommend [Microsoft Q & A (Azure Synapse Analytics)](https://docs.microsoft.com/en-us/answers/topics/azure-synapse-analytics.html), [Azure Synapse Analytics feedback](https://feedback.azure.com/d365community/forum/9b9ba8e4-0825-ec11-b6e6-000d3a4f07b8), Microsoft Support, or your support partners. Regardless, thanks again for this feedback, your suggestions help improve our documentation.
