### ISSUE TITLE
The topic for sys.fn_xe_file_target_read_file  could need some love

### ISSUE THREAD

**Issue by sommarskog** [MicrosoftDocs/sql-docs#7378]
I'm looking at https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/sys-fn-xe-file-target-read-file-transact-sql?view=sql-server-ver15, and I see some room for improvement.

It's says about the parameter path that there is no default. And that is true for the file-name part, but it seems that there is a default for the directory path. If I say 

FROM sys.fn_xe_file_target_read_file(N'system_health*.xel',DEFAULT, DEFAULT, DEFAULT)

it seems to find the file. So it looks as if the default folder might be the folder where the SQL Server errorlog, but this may require some investigation to certify.

It would also be good if the topic would point out that you almost always need to specify the wildcard star.

The warning on top should probably be dropped, and the text mdpath should be modified to say that this parameter only applies to SQL 2008. Oh, yes, there is already a Note to say this. But there's so many Notes in the Docs, that you tend to skip them. :-)

At a minimum the sole example in the topic could be modified to leave the second parameter NULL/DEFAULT.

But an example showing how to read the system_health session could be useful.

As could an example how to read it from Azure Blob Storage when you are on Azure SQL Database. (Assuming that you use this function for there as well, which I don't know for sure is the case.)

**Comment by WilliamAntonRohm** [comment]
@sommarskog -- thank you for your thorough feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @sommarskog for contacting Microsoft with feedback about our product documentation. I agree with some of these points and have a doc update in flight. I'll contact you if we need further information, and you'll receive an email message each time we mention you in a comment. 
	
Thanks again for this feedback, your suggestions help improve our documentation.
