### ISSUE TITLE
Information about driver used to connect to SQL Server

### ISSUE THREAD

**Issue by nojetlag** [MicrosoftDocs/sql-docs#7379]
It would be very helpful to find information in this page what driver is used when selecting connection type "Microsoft SQL Server".
ODBC / OLE DB ? What version ? Is the driver bundled with Azure Data Studio, if yes what is the update policy ? Tried to find information but unfortunately couldn't find it. If available please link to it, if not having the information would be much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df0319c-ec31-e09f-6f44-d71ed20544c3
* Version Independent ID: c52fabfa-5a3d-ea25-cbbf-8a988a8bc867
* Content: [Quickstart: Connect and query SQL Server - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/quickstart-sql-server?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/quickstart-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/quickstart-sql-server.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
@nojetlag -- thank you for your feedback and questions. 

@yualan -- please look into this issue.

**Comment by dzsquared** [comment]
@nojetlag - the connectivity to SQL Server in Azure Data Studio is managed through SQL Tools Service.  
As an open source tool, much of the architectural information about Azure Data Studio is available on its repository: https://github.com/microsoft/azuredatastudio/wiki/SQL-Tools-Service

**Comment by dzsquared** [comment]
#assign:dzsquared

**Comment by nojetlag** [comment]
> @nojetlag - the connectivity to SQL Server in Azure Data Studio is managed through SQL Tools Service.
> As an open source tool, much of the architectural information about Azure Data Studio is available on its repository: https://github.com/microsoft/azuredatastudio/wiki/SQL-Tools-Service

Thank you very much this information. I think it would be very helpful to have a reference to it in the Azure Data Studio documentation. If I did understand correctly SQL-Tools-Service is not using any driver for accessing SQL Server. I'm looking into this issue since starting Feb 2022 the drivers (OLEDB/ODBC/JDBC) have a breaking change where Encrypt=Mandatory and I was wondering when we will face this issue with ADS as well.
