### ISSUE TITLE
List breaking changes

### ISSUE THREAD

**Issue by nojetlag** [MicrosoftDocs/sql-docs#7380]
18.0.1.1 has breaking changes, however on this pages it is not mentioned. I feel this is even more important than having a list of bug fixes and features added (which both nicely are referred to on this page). Would be very much appreciated if breaking changes will be made visible on this page as well.

By coincidence I found the breaking information here, just before rolling out the driver in our organisation
https://techcommunity.microsoft.com/t5/sql-server-blog/odbc-driver-18-0-for-sql-server-released/ba-p/3169228

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23d75570-5304-556a-13b2-5e896528d0e6
* Version Independent ID: 6e5c7d39-798a-e369-f86f-53870182a975
* Content: [Release Notes for ODBC Driver for SQL Server on Windows - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/windows/release-notes-odbc-sql-server-windows?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/windows/release-notes-odbc-sql-server-windows.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/windows/release-notes-odbc-sql-server-windows.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @v-chojas
* Microsoft Alias: **v-chojas**

**Comment by v-chojas** [comment]
This is a major version change; 17.9 also exists as bugfixes with no breaking changes.

@David-Engel  for your thoughts on this.

**Comment by David-Engel** [comment]
I updated the page to include a line about the breaking changes introduced, which warranted the major version bump. The changes missed the past publish window for today but should show up Monday late-morning (PST).

Thanks,
David
