### ISSUE TITLE
Example of BULK INSERT UTF-8 files

### ISSUE THREAD

**Issue by mufukuha** [MicrosoftDocs/sql-docs#7385]
We need an example of BULK INSERT UTF-8 files in [BULK INSERT (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/statements/bulk-insert-transact-sql?view=sql-server-ver15).

Example:
BULK INSERT Sales.Invoices FROM '\\share\invoices\inv-2016-07-25.csv' WITH (FORMAT='CSV', DATAFILETYPE='char', CODEPAGE='65001', FIELDQUOTE='\\', ROWTERMINATOR='0x0A');

**Comment by WilliamAntonRohm** [comment]
@mufukuha -- Munenori, thank you for your suggestion.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by rwestMSFT** [comment]
@mufukuha Thanks for the suggestion. I will look into this for our next scheduled refresh.

**Comment by rwestMSFT** [comment]
A PR is in review, which refreshes this page and adds the example (under the same heading as the existing CSV example). You will see it within a day of the issue being closed.
