### ISSUE TITLE
Unable to locate package msodbcsql18

### ISSUE THREAD

**Issue by JannickB92** [MicrosoftDocs/sql-docs#7387]
Installing the msodbsql package can't be done in ubuntu 21.10:
"E: Unable to locate package msodbcsql18"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
The package appears to be there:
https://packages.microsoft.com/ubuntu/21.10/prod/pool/main/m/msodbcsql18/

Did you follow the installation steps to add the Microsoft packages repo as a source for your system?
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu18

Regards,
David

**Comment by JannickB92** [comment]
Followed the installation steps. It's Ubuntu Server by the way. I've solved my problem in a different way. Strange the package can't be reached.
