### ISSUE TITLE
Typo in /etc/network/interfaces

### ISSUE THREAD

**Issue by adrien-constant** [MicrosoftDocs/sql-docs#7390]
`auth eth0` should be `auto eth0` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29dd905c-43f7-9045-4eee-c087e27f48e0
* Version Independent ID: 0e52d919-2745-c8c5-eb12-77b564f5e3d1
* Content: [Connect your SQL Server instance using Windows authentication (Kerberos) - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-2017#join-your-os-to-the-active-directory-domain-controller)
* Content Source: [docs/azure-data-studio/enable-kerberos.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/enable-kerberos.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@adrien-constant -- Adrien, thank you for catching this.  I am updating the article.
