### ISSUE TITLE
Applies To list should not include Azure Synapse Analytics

### ISSUE THREAD

**Issue by bradleyschacht** [MicrosoftDocs/sql-docs#7397]
This documentation page states that it applies to Azure Synapse Analytics, however, filtered indexes are not available in Azure Synapse Analytics. I do not believe this applies to APS/PDW either, but I'd need to verify that. In the last version of the documentation for APS that I have it does not mention filtered indexes, so I assume it is also not supported there. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e578e8fc-b9da-8c8d-5a4a-64084f1204de
* Version Independent ID: 4adb8a19-ff61-5724-9f01-fb673efb7991
* Content: [Create filtered indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/create-filtered-indexes?view=sql-server-ver15)
* Content Source: [docs/relational-databases/indexes/create-filtered-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/create-filtered-indexes.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@bradleyschacht -- Bradley, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue.  If you wish, you can give me an updated Applies to list & I'll create a PR for it.

**Comment by rwestMSFT** [comment]
@WilliamDAssafMSFT Can you look into this please?

**Comment by WilliamDAssafMSFT** [comment]
Thanks @bradleyschacht, looks like the Applies to include file is incorrect. Will update. Thanks!
