### ISSUE TITLE
Missing AdventureWorks2016CTP3 db Samples

### ISSUE THREAD

**Issue by steebn** [MicrosoftDocs/sql-docs#7399]
In the section titled [Installing the In-Memory OLTP sample based on AdventureWorks](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/sample-database-for-in-memory-oltp?view=sql-server-ver15#InstallingtheIn-MemoryOLTPsamplebasedonAdventureWorks), step one states:
> Download AdventureWorks2016CTP3.bak and SQLServer2016CTP3Samples.zip from: https://github.com/microsoft/sql-server-samples/releases/tag/adventureworks to a local folder, for example 'c:\temp'.

When looking for those files to download from the provided link repo, I don't see them. How can get these files to follow the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc39f88d-19cf-8805-3f2e-9f5cc08aa361
* Version Independent ID: 32e86cee-fe98-064e-78f9-dd383204013f
* Content: [Sample Database for In-Memory OLTP - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/sample-database-for-in-memory-oltp?view=sql-server-ver15#InstallingtheIn-MemoryOLTPsamplebasedonAdventureWorks)
* Content Source: [docs/relational-databases/in-memory-oltp/sample-database-for-in-memory-oltp.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/sample-database-for-in-memory-oltp.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @LitKnd
* Microsoft Alias: **kendralittle**

**Comment by LitKnd** [comment]
Hi @steebn ,

Apologies on the confusion here. The files listed in the article should be:

* AdventureWorks2016.bak
* sql-server-2016-samples.zip

I will create a pull request to update the files in the documentation. This should go live today, so I'm going to go ahead and close out this issue. You will still be able to respond to the issue after it is closed.

Thank you for letting us know about this problem and for making the docs better!

Kendra from the Database Docs Team
#please-close
