### ISSUE TITLE
Rewrite the article with accurate details and screenshot

### ISSUE THREAD

**Issue by clouditspace** [MicrosoftDocs/sql-docs#7400]
The screenshot and explanation provided under the section3.4 is not accurate. 
Here is the section: https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016?view=sql-server-ver15#3---database-backup-to-url

SSMS is not allowing to enter SAS key and the following explanation is not relevant
**Open Object Explorer and connect to Azure storage using your storage account and account key.**

Attached the applicable screenshot as below:
![image](https://user-images.githubusercontent.com/47174734/158731118-14524a52-5905-4513-8814-17dd6ba73390.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e8e46c-01f3-a76a-761f-5206e6d878e9
* Version Independent ID: 3945290e-ef38-b04c-9ee6-d3889b4b94e4
* Content: [Tutorial: Use Azure Blob Storage with SQL Server 2016 - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@clouditspace -- Manu, thank you for bringing this to our attention.

@MashaMSFT -- Masha, please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @clouditspace , thanks for contacting Microsoft and my apologies for the delay as we work through a large backlog of Issues. While your suggestion has merit, it is out of scope for a Git Issue engagement so we're going to start tracking it internally ([61483](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61483)) and address it as resourcing allows. I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
