### ISSUE TITLE
Outdated - Tutorial: Use Azure Blob Storage with SQL Server 2016

### ISSUE THREAD

**Issue by alberto-morillo** [MicrosoftDocs/sql-docs#7401]
On Section #3 "Database backup to URL" step #4 is no longer available. You cannot connect to an Storage Account using an Account Key, the user needs to sign in to Azure instead starting SSMS 18.11.1.

You can read more about this recent change of behavior of SSMS on the following forum thread:

https://docs.microsoft.com/en-us/answers/questions/774987/connecting-to-azure-storage-account-from-ssms.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e8e46c-01f3-a76a-761f-5206e6d878e9
* Version Independent ID: 3945290e-ef38-b04c-9ee6-d3889b4b94e4
* Content: [Tutorial: Use Azure Blob Storage with SQL Server 2016 - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@alberto-morillo -- Alberto, thank you for your clear feedback.

@MashaMSFT -- Masha, please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @alberto-morillo , thanks for contacting Microsoft and my apologies for the delay as we work through a large backlog of Issues. While your suggestion has merit, it is out of scope for a Git Issue engagement so we're going to start tracking it internally ([61483](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61483)) and address it as resourcing allows. I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
