### ISSUE TITLE
Install-MLModels.ps1 fails

### ISSUE THREAD

**Issue by connerdk** [MicrosoftDocs/sql-docs#7405]
The description/script to install the pretrained models at
https://docs.microsoft.com/en-us/sql/machine-learning/install/sql-pretrained-models-install?view=sql-server-ver15
does not work.

Issue 1
It would be nice if the docs mention you need to give scripts permission to run with
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
and remove it again afterwards with
Set-ExecutionPolicy -ExecutionPolicy Undefined -Scope CurrentUser

Issue 2
Line 105 Loads an XML with
$doc.Load($assembly.GetManifestResourceStream("$dllName.$dllName.xml"))
in my case this contained the XML
&lt;?xml version="1.0" encoding="utf-8"?&gt;&lt;ConfigurationData&gt;&lt;mpo&gt;4.5.12.120&lt;/mpo&gt;&lt;mps&gt;9.4.7.25&lt;/mps&gt;&lt;/ConfigurationData&gt;
The variable $($language.ConfigNode) however contained the text "mpy".
I made a workaround like this $($language.ConfigNode).replace('mpy','mps') though not the proper solution

Issue 3
Line 291 I got an error "Error downloading models"
I tried running that from line 283 &$sqlInstance.RSetupPath "/checkurl $rsetupArgs" 2>&1 in shell directly and got error
Error making request: The request was aborted: Could not create SSL/TLS secure channel.
I disable my firewall and it didnt help, so i suspect this is because the web server expects TLS1.2 or newer while RSetup.exe maybe dont use that. Anyway i was able to download the file MLM_9.4.3.0_1033.cab in a browser. And my version 9.4.7.25 doesnt match that of the file, so i renamed it to MLM_9.4.7.0_1033.cab.
Since i already got the file now, i did following
Changed line 283 "/checkurl" to "/checkmedia /mediadir C:\Users\conner\Downloads" where i got the cab file and copied the cab file to the temp folder i suggested next time i ran the script and
Uncommented line 300-316 regarding "Download models, if not already cached"

Finally got it installed, just described my hacks and workaround, hope you find a better solution :)

**Comment by WilliamAntonRohm** [comment]
@connerdk -- thank you for your thorough feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @connerdk for contacting Microsoft with feedback about our product documentation. Glad you were able to find workarounds, thanks for documenting them. It could take from a few business days to a few weeks to look further into this with the product team and decide on how to address. We'll contact you if we need further information, and you'll receive an email message each time we mention you in a comment. 
	
Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
@connerdk if you can provide any more information the version where you encountered this, that would be helpful. If you can reproduce on the latest version that would also be valuable information. If you have more specific troubleshooting questions, please reach out to aka.ms/sqlfeedback, [Microsoft Q & A (SQL Server)](https://docs.microsoft.com/answers/products/sql-server), or contact Support.

Closing.
