### ISSUE TITLE
Wrong page

### ISSUE THREAD

**Issue by jekic** [MicrosoftDocs/sql-docs#7415]
Hi,

  just to inform you that when clicked on Always On Availability Group --> Concept --> Interoperability -->Failover Cluster Instance, it return wrong page "Analysis Services with Always On Availability Groups".

Best Regards,
  Bojan Jekic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b51d16a-4c42-977f-665e-b3211510f136
* Version Independent ID: 1962a422-949b-c2b3-3232-26718184605e
* Content: [Analysis Services with availability groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/analysis-services-with-always-on-availability-groups?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/analysis-services-with-always-on-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/analysis-services-with-always-on-availability-groups.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@jekic -- thank you for bringing this to our attention.  I am updating the table of contents.

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- Masha, I'm not sure whether the toc's name or href should be changed for this entry:
```
        - name: Failover cluster instances
          href: database-engine/availability-groups/windows/analysis-services-with-always-on-availability-groups.md
```

It seems to me the name should be updated to "Analysis Services with Always On Availability Groups".

**Comment by MashaMSFT** [comment]
Hi @jekic , thanks so much for contacting Microsoft and helping improve our docs! My apologies for the delay as we've been working through a large backlog of Issues. I've processed a change to update this that should be live later this week. I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks again and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
