### ISSUE TITLE
Login auditing on Linux 

### ISSUE THREAD

**Issue by CraigSQL** [MicrosoftDocs/sql-docs#7418]
Cannot configure successful login auditing on Linux
There is no Security tab for a Linux SQL Server, this page needs updating. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a5731fb-8c19-a127-e994-b4bb23835222
* Version Independent ID: f72b70a9-daa8-eac3-2399-8e52b6398786
* Content: [Configure Login Auditing (SQL Server Management Studio) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/configure-login-auditing-sql-server-management-studio?view=sql-server-ver15)
* Content Source: [docs/ssms/configure-login-auditing-sql-server-management-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/configure-login-auditing-sql-server-management-studio.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@CraigSQL -- Craig, thank you for your feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by erinstellato-ms** [comment]
#reassign @erinstellato-ms

**Comment by rwestMSFT** [comment]
@erinstellato-ms Following up. Is there any further action required, or can we close this issue?

**Comment by erinstellato** [comment]
@rwestMSFT I think I still need to update the docs here.

**Comment by rwestMSFT** [comment]
We have an internal PR staged for this change. Once it is merged, this issue will automatically close. Thank you again for your contribution, @CraigSQL.
