### ISSUE TITLE
Table DDL has errors

### ISSUE THREAD

**Issue by mcarr10** [MicrosoftDocs/sql-docs#7419]
[Enter feedback here]
The DDL for step 2 create HumanResources.DepartmentTest table is incorrect.  The data types are wrong for the name and group name columns.

DDL with errors:
CREATE TABLE [HumanResources].[DepartmentTest](
[DepartmentID] [smallint] NOT NULL,
[Name] [dbo].[Name] NOT NULL,
[GroupName] [dbo].[Name] NOT NULL
)
GO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75ef50ee-113c-d60b-d325-e0b2c8b3ff8c
* Version Independent ID: 22a0fe29-9168-fe54-c022-c03f6db7ac5c
* Content: [Insert Python dataframe into SQL table - SQL machine learning](https://docs.microsoft.com/en-us/sql/machine-learning/data-exploration/python-dataframe-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/machine-learning/data-exploration/python-dataframe-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/data-exploration/python-dataframe-sql-server.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@mcarr10 -- Merle, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Hi @mcarr10! Thanks for taking the time to submit this feedback. Need more info. What error do you receive, and in what step? The data types in the proposed `HumanResources.DepartmentTest` table match the data types in the actual `HumanResources.Department` table in the `AdventureWorks2019` database, using the same user-defined data type `dbo.Name` error. Make sure you are using the `AdventureWorks2019` sample database which has user-defined data type created: 'CREATE TYPE [dbo].[Name] FROM [nvarchar](50) NULL'.

**Comment by mcarr10** [comment]
I grabbed a fresh copy of AdventureWorks2019 and the DDL works fine.  Something must have changed in the copy I was working from.  Sorry for the false alarm.
