### ISSUE TITLE
Package names not valid for OS 

### ISSUE THREAD

**Issue by k7faq** [MicrosoftDocs/sql-docs#7422]
[Enter feedback here]

instructions for Ubuntu 20.04 are not valid.

apt-get install mssql-tools unixodbc-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mssql-tools
root@steven-diag:/# cat /etc/os-release |grep VERSION
VERSION="20.04.4 LTS (Focal Fossa)"
VERSION_ID="20.04"
VERSION_CODENAME=focal
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
> Is your environment x64 or arm?

Hey @dzsquared - Thanks! This issue has cropped up a couple of times. Can we be clearer in our docs about this, and do you think I should add it to our list of unsupported features?

We have this note, but is it just arm that is not supported?

![image](https://user-images.githubusercontent.com/40007119/159999831-03d437a2-9be2-451d-ad34-93ad6f08d097.png)

**Comment by k7faq** [comment]
I was trying to install this in a Docker Container on a Intel based Mac. I have since moved to using the image mcr.microsoft.com/mssql-tools for my needs.

**Comment by dzsquared** [comment]
> I was trying to install this in a Docker Container on a Intel based Mac. I have since moved to using the image mcr.microsoft.com/mssql-tools for my needs.

Ah, thank you for that info!  Was this an unattended install during container build?  It might have been the interactive EULA approval for sqltools that was hanging the install.
