### ISSUE TITLE
Image transparency causes text to be unreadable in a browser using a dark theme

### ISSUE THREAD

**Issue by drskev** [MicrosoftDocs/sql-docs#7426]
The image representing the DB recovery path:
https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/media/bnrr-rmfull1-db-failure-pt.gif?view=sql-server-ver15
Is a gif with a transparent background.

If you view this with the browser configured for a dark theme (as many developers do) then all the text that is not placed over a grey or white background in the image is rendered pretty much unreadable. 

If you choose to view the image in another tab then this displays fine (with a grey background).  However, when viewed within the page it renders with a black background. (Edge Version 99.0.1150.46).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3d152c1-49ed-9263-75c0-4cd738582f50
* Version Independent ID: d2ead26c-c016-a9f2-b6ad-bc4653f0bb7d
* Content: [Complete Database Restores (Full Recovery Model) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/complete-database-restores-full-recovery-model?view=sql-server-ver15)
* Content Source: [docs/relational-databases/backup-restore/complete-database-restores-full-recovery-model.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/complete-database-restores-full-recovery-model.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @LitKnd
* Microsoft Alias: **kendralittle**

**Comment by WilliamAntonRohm** [comment]
@drskev -- thank you for your feedback.  I am updating the image.
