### ISSUE TITLE
virtual account kerberos failure due to machine account password update

### ISSUE THREAD

**Issue by fdari** [MicrosoftDocs/sql-docs#7428]
hi! a sql server suddenly lost kerberos functionality, and the cause is almost certainly that the computer account changed its password while the service was running.

if this is correct, that possibility seems to merit mention in the guidance on virtual accounts

by default we exercise no control over when computer accounts update their passwords, so that means any sql server we configure using virtual accounts could lose kerberos functionality whenever, even if it happens rarely

if there is any guidance on how to mitigate or prevent this problem while continuing to use virtual accounts, could you please let me know, and also add it to the guidance on virtual accounts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b3831a3-6c86-243c-4b07-8960e4d06d7b
* Version Independent ID: dfd7599d-88eb-99f2-c227-0c9dc82bfd87
* Content: [Configure Windows service accounts and permissions - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
Hi @fdari, and thanks for your question. As I understand it, the passwords are refreshed every 30 days and should happen automatically even if the services are running. If not, you might be missing a hotfix (KB 2494158) depending on the version of Windows you're using.

That said, in the Virtual Account section we include the following paragraph:

> For more information on Managed Service Accounts and Virtual Accounts, see the Managed service account and virtual account concepts section of [Service Accounts Step-by-Step Guide](https://technet.microsoft.com/library/dd548356(WS.10).aspx) and [Managed Service Accounts Frequently Asked Questions (FAQ)](https://technet.microsoft.com/library/ff641729(WS.10).aspx).

That last URL contains a number of good Q&A, including the following guidance:

> **Can a managed service account password be reset manually if needed?**
>
> Yes. You can use the `Reset-ADServiceAccount` Windows PowerShell cmdlet to manually reset a managed service account password. You can also reset a managed service account password by using the Nltest.exe command-line tool. For more information about resetting managed service account passwords, see the [Service Accounts Step-by-Step Guide](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd548356(v=ws.10)).

I don't think the article warrants an update at this time, because this seems to be the scope of Windows documentation.

**Comment by WilliamAntonRohm** [comment]
@fdari -- thank you for your feedback.

@rwestMSFT -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by fdari** [comment]
@WilliamAntonRohm I think you got my request backwards:
Resetting the machine account password is not the goal.
The problem is not that the machine account password is not reset.
The password is reset. Automatically. Perhaps exactly every 30 days.

When the machine account password is reset, this effectively resets the password of the sql service account. If this happens when the sql service is already running, the sql service may become unable to perform kerberos authentication because it no longer qualifies for the spn associated with the machine account.

The requested guidance is not: how to make the machine reset its account password
It is:
How best to make sure sql retains or restores full functionality (kerberos authentication being the lost functionality) when the machine account password is reset?

**Comment by rwestMSFT** [comment]
Hi @fdari, I still believe that this is a Windows issue as it relates to Kerberos and virtual accounts, not SQL Server specifically. I'm sorry that this is not the answer you were hoping for.

**Comment by WilliamAntonRohm** [comment]
@fdari -- please consider these resources:

**Comment by fdari** [comment]
Thank you for your attention. I have solved my own problem, and sought only to recommend that:
... as the guidance on sql server suggests virtual service accounts ...
... and virtual service accounts are the default configuration of new sql servers ...
... the guidance ought to mention that this setup is not stable without further action.

Rephrased:
The virtual service account setup described on this page
As described
Has potential to fail in ways that can disrupt business as often as every 30 days
By design
It is my opinion that this, if correct, merits mention on a page providing guidance on how to configure the service identity for sql server.

I would expect you to either
a) say that I am mistaken about how the problem arose and explain that sql kerberos authentication with virtual accounts (not managed accounts) is unaffected by the automated password reset of computer accounts
b) say that you are unsure and need to investigate/see evidence before modifying documentation
c) make an update to note that the potential for a critical failure of services every 30 days exists in the default (virtual service account) setup, and perhaps describe methods of managing this risk

I am perplexed that you choose d) assert that a page intended to help make informed decisions about how to configure sql server should not include information about how one of the proposed setups might predictably fail (due to an event that occurs when Windows operates as design).

I can come up with my own solution, so I will back off, but I am really a little bit shocked at you.

**Comment by rwestMSFT** [comment]
Thank you for expressing your concerns. I would once again strongly encourage you to raise a support issue using the link I provided previously, so that if there is a bug with Windows and virtual accounts (which appears to be the case based on your feedback), it can be fixed.

**Comment by fdari** [comment]
I will raise a support issue (unless it is expensive and not covered by existing purchases), and report it as a bug. I'll let you know if neither Windows nor SQL see the behaviour as a bug, though I agree that potential failure every 30 days is obviously unintended behaviour.
