### ISSUE TITLE
Warning on this page is inaccurate and misleading

### ISSUE THREAD

**Issue by RobKraft** [MicrosoftDocs/sql-docs#7429]
The Warning on this page is not accurate.  "A CLR assembly created with PERMISSION_SET = SAFE may be able to access external system resources" is false.  If the PERMISSION_SET is SAFE, the assembly will NOT be able to access external system resources per my own testing and per Microsoft docs (https://docs.microsoft.com/en-us/sql/t-sql/statements/create-assembly-transact-sql).  An assembly marked SAFE or EXTERNAL_ACCESS does not require a certificate or an asymmetric key, but since CLR STRICT Security treats them all as UNSAFE, they are all required to have a certificate or an asymmetric key.

FYI - I documented this more thoroughly here: https://www.sqlserversecurity.com/blog/clrapps/ 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96693d4a-9460-9e08-8f14-836b6257e449
* Version Independent ID: 47f19aec-1f62-97c4-fca4-609496fc2139
* Content: [CLR strict security - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/clr-strict-security?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/clr-strict-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/clr-strict-security.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
#assign:rwestMSFT

**Comment by rwestMSFT** [comment]
@RobKraft You are correct in your assertion that if the setting is enabled, all assemblies marked as SAFE will be regarded as UNSAFE. However, this setting was only introduced in SQL Server 2017, and our documentation also covers SQL Server 2016.

For that reason, the wording "may be able" is still correct for SQL Server versions prior to 2017, and all versions when this setting is disabled.

**Comment by RobKraft** [comment]
I'll admit I have not tested on SQL 2016 yet.  But on SQL 2019, if I set 'clr strict security' to 0; and I set Trustworthy to ON for my database (pretty much turn off all the security constraints), and then I add my assembly with a PERMISSION_SET of SAFE, I can use the assembly to for stored procs that don't make service calls, but if I use the assembly to make a call out to the Internet I get an error.  And I'll repeat that for clarification; my assembly has one function that doesn't call the Internet (which works), and another function which does call the Internet (but fails) only when the PERMISSION_SET is SAFE.  Therefore, on SQL 2019, regardless of any other setting, if PERMISSION_SET is SAFE, that "blocks" calls to the Internet.  I assume that also blocks calls to other services because that is what the documentation for CREATE ASSEMBLY says it does.  Also, I am testing an assembly built using .Net 4.8, in case that makes a difference (as opposed to .Net 2.0 or a version that relied on CAS)

**Comment by rwestMSFT** [comment]
Your scenario makes sense, Rob, and it is correct for 2017+. I would appreciate it if you can test on SQL Server 2016, to help confirm the assertion in the warning.

**Comment by rwestMSFT** [comment]
@RobKraft Thank you again for looking into it further.

Where I'm coming from is that "external system resources" doesn't just refer a call to an Internet endpoint, which you've shown through your testing is correctly blocked. It could also refer to an internal (to the network) resource. Additionally, with .NET Framework 2.0 code still in production on SQL Server versions prior to 2016 and still supported, the landscape is unfortunately a lot more complicated, and so the wording "may be able to access" will stay for the time being.

I'm going to reach out to the product team and see what they say, and I'm going to refer to this discussion. I also want to expressly thank you for raising this concern, and I will get more folks to look into it in the medium term.

**Comment by RobKraft** [comment]
I think I understand now.  You are saying that even though SAFE blocked "my app" from calling the Internet, marking the assembly SAFE can't be relied upon to prevent it from making other "external access" calls.  Sorry to take your time. :)  I'm on the working group for the CIS benchmarks and am double-checking our guidance to make sure we understand the security implications correctly.

**Comment by rwestMSFT** [comment]
I appreciate the conversation, Rob. Information security is certainly an interesting field right now.
