### ISSUE TITLE
Link to video routes to a general page with no way to access specific video

### ISSUE THREAD

**Issue by leifjones** [MicrosoftDocs/sql-docs#7436]
The link to [JSON as a bridge between NoSQL and relational worlds](https://channel9.msdn.com/events/DataDriven/SQLServer2016/JSON-as-a-bridge-betwen-NoSQL-and-relational-worlds) at the bottom of this page routes to a general page with no way to access specific video. Please update and/or provide a direct link to the video. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dbf9b6d-ef9c-6a92-c4ac-a7ec404fc1a8
* Version Independent ID: 427b0fca-035c-f292-b6f2-6eacabf11099
* Content: [Validate, Query, and Change JSON Data with Built-in Functions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/validate-query-and-change-json-data-with-built-in-functions-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/json/validate-query-and-change-json-data-with-built-in-functions-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/validate-query-and-change-json-data-with-built-in-functions-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by rwestMSFT** [comment]
We have an update that removes the video link, which will publish in the next day or so. Thank you for your feedback.
