### ISSUE TITLE
Synapse Dedicated Pool:  sys.allocation_units;

### ISSUE THREAD

**Issue by pwehland** [MicrosoftDocs/sql-docs#7437]
select * from sys.allocation_units;

Msg 104385, Level 16, State 1, Line 1
Catalog view 'allocation_units' is not supported in this version.

Can anyone please suggest solution to this
i have searched, but cant able to find right solution

@WilliamAntonRohm 
@Vabby547 
@LuisGonzalezLT

_Originally posted by @ajithkumar-22 in https://github.com/MicrosoftDocs/sql-docs/issues/3749#issuecomment-1057664833_

We need this exposed so we can join to sys.dm_pdw_nodes_os_buffer_descriptors.allocation_unit_id for tuning our workloads.

**Comment by WilliamAntonRohm** [comment]
Duplicate of #3749.
