### ISSUE TITLE
Incorrect instruction for logger.ini file location

### ISSUE THREAD

**Issue by jmuis** [MicrosoftDocs/sql-docs#7445]
[Enter feedback here]
The location of the logger.ini file is not in /var/opt/mssql/log but in /var/opt/mssql. The output will be in the log subdir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41b9d2d4-b4a3-0885-765d-9360a9c62378
* Version Independent ID: 63494275-4c52-f2d9-2497-48c1d1cf5d63
* Content: [Troubleshooting Active Directory authentication for SQL Server on Linux and containers - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-ad-auth-troubleshooting?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-ad-auth-troubleshooting.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-ad-auth-troubleshooting.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by rwestMSFT** [comment]
@jmuis Thank you for raising this issue. We'll look into it next week.

**Comment by rwestMSFT** [comment]
#assign:rwestMSFT

**Comment by amvin87** [comment]
Thank you @Jmuis. @rwestMSFT, may I request your assistance in correcting the location of the logger.ini file from /var/opt/mssql/log to /var/opt/mssql please.

**Comment by rwestMSFT** [comment]
This has been addressed in a different pull request, which will go live shortly.

**Comment by rwestMSFT** [comment]
#please-close
