### ISSUE TITLE
Formatting issue in output-clause-transact-sql.md at Arguments/column_list/column_name

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/sql-docs#7448]
See https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/output-clause-transact-sql.md

Under *column_name*, it says:

> *column_name*  
> Is an explicit column reference. Any reference to the table being modified must be correctly qualified by either the INSERTED or the DELETED prefix as appropriate, for example: INSERTED**.**_column\_name_.  

There should not be “\*\*.\*\*”. It should just be “**.**”.

**Comment by WilliamAntonRohm** [comment]
@binki -- Nathan, thank you again for your feedback.  I am updating this article.
