### ISSUE TITLE
First example in RETURN article is pointless

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/sql-docs#7455]
In the RETURN article https://docs.microsoft.com/en-us/sql/t-sql/language-elements/return-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15 at the first example at https://docs.microsoft.com/en-us/sql/t-sql/language-elements/return-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15#a-returning-from-a-procedure , the following code is provided as an example:

```tsql
CREATE PROCEDURE findjobs @nm sysname = NULL
AS
IF @nm IS NULL
    BEGIN
        PRINT 'You must give a user name'
        RETURN
    END
ELSE
    BEGIN
        SELECT o.name, o.id, o.uid
        FROM sysobjects o INNER JOIN master..syslogins l
            ON o.uid = l.sid
        WHERE l.name = @nm
    END;
```

There are multiple issues with this code. For example, it contains one semicolon. But removing that semicolon has no effect and you could use a semicolon everywhere it is permissible instead like the following:

```tsql
CREATE PROCEDURE findjobs @nm sysname = NULL
AS
IF @nm IS NULL
    BEGIN;
        PRINT 'You must give a user name';
        RETURN;
    END;
ELSE
    BEGIN;
        SELECT o.name, o.id, o.uid
        FROM sysobjects o INNER JOIN master..syslogins l
            ON o.uid = l.sid
        WHERE l.name = @nm;
    END;
```

But, more importantly, this example is a bad example of the usage of the `RETURN` statement because removing `RETURN` from the example does not change its behavior. Consider the following which does not contain `RETURN` which has identical behavior:

```tsql
CREATE PROCEDURE findjobs @nm sysname = NULL
AS
IF @nm IS NULL
    BEGIN;
        PRINT 'You must give a user name';
    END;
ELSE
    BEGIN;
        SELECT o.name, o.id, o.uid
        FROM sysobjects o INNER JOIN master..syslogins l
            ON o.uid = l.sid
        WHERE l.name = @nm;
    END;
```

If you want to demonstrate how `RETURN` affects control flow, you should remove the `ELSE` from the example. Then, the `RETURN` statement would be significant:

```tsql
CREATE PROCEDURE findjobs @nm sysname = NULL
AS
IF @nm IS NULL
    BEGIN;
        PRINT 'You must give a user name';
        RETURN;
    END;
SELECT o.name, o.id, o.uid
FROM sysobjects o INNER JOIN master..syslogins l
    ON o.uid = l.sid
WHERE l.name = @nm;
```

**Comment by WilliamAntonRohm** [comment]
@binki -- Nathan, thank you again for your detailed feedback.  

@LitKnd -- Kendra, please look into this issue.

cc @pmasl for related issue #7456
