### ISSUE TITLE
Article about stored procedure return values and implicit default status values is missing

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/sql-docs#7456]
I would expect [`RETURN`](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/return-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15) to discuss the significance of `RETURN` without specifying a value. Or I would expect [`EXECUTE`](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/execute-transact-sql?view=sql-server-ver15) to discuss how the return value of a stored procedure is calculated during execution. Or I would expect [`CREATE PROCEDURE`](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-procedure-transact-sql?view=sql-server-ver15) to discuss the execution of stored procedures. Or I’d expect [Query Processing Architecture Guide / Stored Procedure and Trigger Execution](https://docs.microsoft.com/en-us/sql/relational-databases/query-processing-architecture-guide?view=sql-server-ver15#stored-procedure-and-trigger-execution) to talk about how the status code for a stored procedure is calculated and when it is updated.

Since I am young and new to SQL Server (compared to people who started using it in the late 1990s), I missed out on reading the documentation on earlier versions of SQL Server. [This SO answer](https://stackoverflow.com/a/2579781) links to [Erland Sommarskog’s paragraphs on `RETURN`](http://www.sommarskog.se/error-handling-I.html#returnvalue) which state:

> Books Online for earlier versions of SQL Server specified meanings for values -1 to -14. However, Books Online for SQL 2000 is silent on any such reservations, and does not explain what -1 to -14 would mean.

Could you restore the article from the older versions of SQL Server?

In particular, I am interested in clear documentation on what happens in a stored procedure when `RETURN;` (no value specified) is used and when the end of the stored procedure is reached without any `RETURN` statements being executed. I found the following surprising because I had not yet encountered [Erland Sommarskog’s article which documents this bheavior](http://www.sommarskog.se/error-handling-I.html#returnvalue). I expected everything to return 0, but many did not:

```tsql
CREATE PROCEDURE #empty AS
GO
DECLARE @ret INT;
EXEC @ret = #empty;
PRINT @ret; -- “0” (control group: the status value retains its initial value of 0)
DROP PROCEDURE #empty;
GO

CREATE PROCEDURE #raisesAndCatchesError AS
BEGIN TRY;
	RAISERROR(N'#raisesAndCathcesError', 11, 1);
END TRY BEGIN CATCH;
	_noop234234:;
END CATCH;
GO
DECLARE @ret INT;
EXEC @ret = #raisesAndCatchesError;
PRINT @ret; -- “-1” (raising an error changes value from 0)
GO

CREATE PROCEDURE #callsRaisesAndCatchesError AS
EXEC #raisesAndCatchesError;
GO
DECLARE @ret INT;
EXEC @ret = #callsRaisesAndCatchesError;
PRINT @ret; -- “0” (RAISERROR() only changes the status value of the procedure it is directly called in)
DROP PROCEDURE #raisesAndCatchesError;
DROP PROCEDURE #callsRaisesAndCatchesError;
GO

CREATE PROCEDURE #raisesError AS
RAISERROR(N'#raisesError', 11, 1);
GO
DECLARE @ret INT;
EXEC @ret = #raisesError;
PRINT @ret; -- “-1” (uncaught exception still changes status value from 0, the behavior is unrelated to TRY…CATCH)
GO

CREATE PROCEDURE #callsRaisesError AS
EXEC #raisesError;
GO
DECLARE @ret INT;
EXEC @ret = #callsRaisesError;
PRINT @ret; -- “0” (RAISERROR() only changes the status value of the procedure it is directly called in)
DROP PROCEDURE #raisesError;
DROP PROCEDURE #callsRaisesError;
GO

CREATE PROCEDURE #performsAndCatchesInvalidCast AS
BEGIN TRY;
	SELECT CAST('zero' AS INT) Value;
END TRY BEGIN CATCH;
	PRINT 'caught invalid cast';
END CATCH;
GO
DECLARE @ret INT;
EXEC @ret = #performsAndCatchesInvalidCast; -- “caught invalid cast”
PRINT @ret; -- “-6” (invalid cast gets a different status value than -1, it gets -6)
DROP PROCEDURE #performsAndCatchesInvalidCast;
GO

CREATE PROCEDURE #performsAndCatchesInvalidCastExplicitReturnValue AS
BEGIN TRY;
	DECLARE @i INT = CAST('zero' AS INT);
END TRY BEGIN CATCH;
	PRINT 'caught invalid cast';
END CATCH;
RETURN 0;
GO
DECLARE @ret INT;
EXEC @ret = #performsAndCatchesInvalidCastExplicitReturnValue; -- “caught invalid cast”
PRINT @ret; -- “0” -- (explicit value passed to RETURN ignores any existing status value)
DROP PROCEDURE #performsAndCatchesInvalidCastExplicitReturnValue;
GO

CREATE PROCEDURE #performsAndCatchesInvalidCast2 AS
BEGIN TRY;
	DECLARE @i INT = CAST('zero' AS INT);
END TRY BEGIN CATCH;
	PRINT 'caught invalid cast';
END CATCH;
GO
DECLARE @ret INT;
EXEC @ret = #performsAndCatchesInvalidCast2; -- “caught invalid cast”
PRINT @ret; -- “-6” (the value -6 is related to cast or expression evaluation failure rather than result set interruption)
DROP PROCEDURE #performsAndCatchesInvalidCast2;
GO

CREATE PROCEDURE #performsAndCatchesInvalidCastExplicitReturn AS
BEGIN TRY;
	DECLARE @i INT = CAST('zero' AS INT);
END TRY BEGIN CATCH;
	PRINT 'caught invalid cast';
END CATCH;
RETURN;
GO
DECLARE @ret INT;
EXEC @ret = #performsAndCatchesInvalidCastExplicitReturn; -- “caught invalid cast”
PRINT @ret; -- “-6” (RETURN without explicit value preserves any current status value)
DROP PROCEDURE #performsAndCatchesInvalidCastExplicitReturn;
GO
```

**Comment by WilliamAntonRohm** [comment]
@binki -- Nathan, your close reading is appreciated.

@pmasl -- Pedro, please look into this issue.

cc @LitKnd for related issue #7455

**Comment by rothja** [comment]
@rwestMSFT Randolph, could you take a look at this issue in Pedro's absence? #reassign:rwestmsft

**Comment by rwestMSFT** [comment]
@binki Thank you for your questions, which I've read through several times.

The database engine has undergone significant updates in the two decades since SQL Server 2000, so I'm not sure there's much value in restoring content prior to that time. In my opinion, it's academic whether a *user-defined* stored procedure returns an arbitrary value if RETURN is not used, or whether RETURN is used with no `integer_expression` value. Oftentimes, behaviour that is undocumented is also unsupported, meaning that the internals may change without notice. We do however guarantee that *system* stored procedures will return `0` if they are successful.

I would like to hear more about your specific use-case, so that I can best understand how to improve our documentation.

In the meantime, we have already flagged the architecture guide for a refresh some time in the near future, and you have also highlighted that the EXECUTE article is in need of a refresh. When we get to that in the backlog, I'll see if there's a way to incorporate the information you're asking where it adds value.

Thank you again for your thoughtful contribution. I will close this particular issue because we are tracking it internally, but please feel free to reply at your leisure.

#please-close
