### ISSUE TITLE
USE AdventureWorks2008R2;   then USE AdventureWorks2012;  

### ISSUE THREAD

**Issue by donhuvy** [MicrosoftDocs/sql-docs#7460]
Section 4

```
USE AdventureWorks2008R2;  
```
then, Section 5

```
USE AdventureWorks2012; 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfe9cad3-2e7d-a426-43ff-1347937dc291
* Version Independent ID: 6b04557f-6331-609e-5e80-6b3663495bd7
* Content: [View the Dependencies of a Stored Procedure - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/view-the-dependencies-of-a-stored-procedure?view=sql-server-2017)
* Content Source: [docs/relational-databases/stored-procedures/view-the-dependencies-of-a-stored-procedure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/stored-procedures/view-the-dependencies-of-a-stored-procedure.md)
* Product: **sql**
* Technology: **stored-procedures**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@donhuvy -- thank you for bringing this to our attention.

@WilliamDAssafMSFT -- William, please look into this issue.  If it can be solved by simply replacing AdventureWorks2008R2 with AdventureWorks2012, let me know and I'll create a PR for that fix.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @donhuvy. 
@WilliamAntonRohm Thanks for taking care of this one. It can actually be updated in each sample to `AdventureWorks2019`., I've verified. Please also include a reference to [https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure](https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure), for example:

```
This example uses the `AdventureWorks2019` database, available for download at [AdventureWorks sample databases](../../samples/adventureworks-install-configure.md).
```
