### ISSUE TITLE
Table definition query altenative non-functional

### ISSUE THREAD

**Issue by akisys** [MicrosoftDocs/sql-docs#7465]
Hi there,

in regards to getting table and column metadata information, the provided example query alternative to the stored procedure use-case was not working for me, here is an adjusted version which did work again:

```
SELECT s.name as schema_name, t.name as table_name, c.* FROM sys.columns AS c
INNER JOIN sys.tables AS t ON t.object_id = c.object_id
INNER JOIN sys.schemas AS s ON s.schema_id = t.schema_id
WHERE t.object_id = object_id('dbo.mytable') AND s.name = 'dbo';
```

Be aware that the schema name is used again within the `object_id` function call.

Hope this helps!
Cheers, Alex.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed157539-52dc-0dab-22ca-964143d7095d
* Version Independent ID: f8c8107c-8662-95e2-650b-1a1692a44db4
* Content: [View the Table Definition - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/view-the-table-definition?view=sql-server-2016)
* Content Source: [docs/relational-databases/tables/view-the-table-definition.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/view-the-table-definition.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@akisys -- Alexander, thank you for your feedback.  I am updating this article.

**Comment by WilliamDAssafMSFT** [comment]
@akisys Thanks for catching. The issue is with the `object_id` function not picking up other schemas. I will simplify the example. Appreciate your time to create this issue. Thanks again for this feedback, your suggestions help improve our documentation.
@WilliamAntonRohm I will handle, will refresh article as well.
