### ISSUE TITLE
About "You cannot Enable DTC on an existing Always On availability groups."

### ISSUE THREAD

**Issue by techert** [MicrosoftDocs/sql-docs#7470]
Concerns: https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/create-clustered-dtc-for-an-always-on-availability-group?view=sql-server-ver15#7----create-availability-group
Section 7.

Issue: the warning in the blue "Important section" is unclear.
It claims that USE master; ALTER AVAILABILITY GROUP <availability_group> SET (DTC_Support = Per_DB) won't work.
Presumably this applies only to SQL Server 2016SP1? Without reference to the version, it implies that it just doesn't work.
The article of Ryan Adams [here](https://ryanjadams.com/2018/07/msdtc-configuration-sql-support/) confirms that it is supported on SQL Server 2016SP2 and SQL Server 2017.

If this is correct, please add the version to that section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8bed28c-1e39-ff86-259c-dba50596680a
* Version Independent ID: 764033c7-0c9d-d42e-d6fb-a98afb164ce2
* Content: [Create Clustered DTC resource for an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/create-clustered-dtc-for-an-always-on-availability-group?view=sql-server-ver15)
* Content Source: [docs/database-engine/availability-groups/windows/create-clustered-dtc-for-an-always-on-availability-group.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/create-clustered-dtc-for-an-always-on-availability-group.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@techert -- thank you for your thorough research.

@MashaMSFT -- please look into this issue.

**Comment by tarynpratt** [comment]
hi @techert  , thanks so much for your feedback, our apologies for the long delay as we processed a large number of back Issues. I've processed the change you recommended and it should be live later this week. I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

thanks again, hope you have a good day
#please-close
