### ISSUE TITLE
example how to grant "ALTER ANY CREDENTIAL"

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/sql-docs#7476]
very important to execute: 

**_Assign the user account to the role of [db_backupoperator] and grant permissions._**

please add and example to the page: 

```tsql
use [master]
GO
GRANT ALTER ANY CREDENTIAL TO [MYDOM\MyUser4Backup]
GO
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e8e46c-01f3-a76a-761f-5206e6d878e9
* Version Independent ID: 3945290e-ef38-b04c-9ee6-d3889b4b94e4
* Content: [Tutorial: Use Azure Blob Storage with SQL Server 2016 - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@TiloGit -- thank you for your feedback and suggestion.

@MashaMSFT -- please look into this issue.

**Comment by rwestMSFT** [comment]
Hi @TiloGit. We already note in the *Prerequisites* section the following:

> Assign the user account to the role of [db_backupoperator](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles?view=sql-server-ver15) and grant [alter any credential](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-credential-transact-sql?view=sql-server-ver15) permissions.

We appreciate that you have submitted feedback. Please continue to do so.

#please-close

**Comment by TiloGit** [comment]
@rwestMSFT an simple example on that page (instead of link to SQL document) would have help me to complete this much faster but your call. Cheers.
