### ISSUE TITLE
Typo in 'Business continuity and database recovery - SQL Server'

### ISSUE THREAD

**Issue by connormoolman** [MicrosoftDocs/sql-docs#7477]
Typo, can't edit document as content isn't on github. 

Typo: "availability group as one of the instances hosing either a primary or secondary replica"
Fix: "availability group as one of the instances hosting either a primary or secondary replica"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76208061-3c5d-758a-6704-dd7f546d5545
* Version Independent ID: 6ea99630-2750-17b2-b64b-b6fa8464e1dc
* Content: [Business continuity and database recovery - SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/sql-server-business-continuity-dr?view=sql-server-ver15)
* Content Source: [docs/database-engine/sql-server-business-continuity-dr.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/sql-server-business-continuity-dr.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@connormoolman -- Connor, thank you for catching that.  I'm updating the article.

**Comment by connormoolman** [comment]
@WilliamAntonRohm -- Hi, it still seems like the Typo is there in case you have forgotten, cheers.

**Comment by rwestMSFT** [comment]
@connormoolman Thank you for your contribution. The typo in question was in a difficult-to-find file and it took several attempts to get a fix in. I ended up having to do it through an internal process. You should see the correct text in the next day or so.
