### ISSUE TITLE
untrusted constraints

### ISSUE THREAD

**Issue by duanerchuk** [MicrosoftDocs/sql-docs#7478]
This page should include some discussion of the 'with check check constraint' clause. As written, I believe it will leave the keys in question untrusted, which I am told means they will not be used by the query optimizer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d04ece6f-5b0e-1fbc-b083-c561025fcb87
* Version Independent ID: 633f8c59-bdf7-f33f-fab6-a3b9cd2ce111
* Content: [Disable Foreign Key Constraints in INSERT and UPDATE Statements - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/disable-foreign-key-constraints-with-insert-and-update-statements?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/disable-foreign-key-constraints-with-insert-and-update-statements.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/disable-foreign-key-constraints-with-insert-and-update-statements.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
This would be a great add @duanerchuk, thanks for raising awareness to it.  A doc update is in progress.
