### ISSUE TITLE
Default folder

### ISSUE THREAD

**Issue by YounggunKim** [MicrosoftDocs/sql-docs#7489]
Dear docs team,

Before SQL Server 2016, 
default folder for sqlmonitor.exe is "C:\Program Files (x86)\Microsoft SQL Server\nnn\Tools\Binn\"
(x86) is omitted.

From SQL Server 2016, SSMS installed separately.
I think adding default folder for new SSMS is needed.
It's "C:\Program Files (x86)\Microsoft SQL Server Management Studio nn\Common7"

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9734bc2f-7471-d79a-ec3f-4fa6b3e9c18d
* Version Independent ID: 83c66c18-59f2-2a66-3b87-797458e7c375
* Content: [Start the Replication Monitor - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/monitor/start-the-replication-monitor?view=sql-server-ver15)
* Content Source: [docs/relational-databases/replication/monitor/start-the-replication-monitor.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/monitor/start-the-replication-monitor.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@YounggunKim -- Younggun, please add this issue here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
