### ISSUE TITLE
Mention setting `loginTimeout` to 90 or 120 sec for Azure SQL database

### ISSUE THREAD

**Issue by philippw** [MicrosoftDocs/sql-docs#7501]
In [this comment](https://github.com/microsoft/mssql-jdbc/issues/1667#issuecomment-941293206), @lilgreenbird mentions their recommendation of setting `loginTimeout` to 90 or 120 sec for Azure SQL database when using the MS SQL JDBC driver.

We shoud add this crucial piece of information to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ae74cc-0d4c-2e44-af2b-50d6fba8c5a8
* Version Independent ID: 7c2c80c0-b2fb-3193-8e68-e5a891ca4061
* Content: [Connect to an Azure SQL database - JDBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-to-an-azure-sql-database?view=sql-server-ver15)
* Content Source: [docs/connect/jdbc/connecting-to-an-azure-sql-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/connecting-to-an-azure-sql-database.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@philippw -- Philipp, thank you for your suggestion.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
Done. The change should be reflected after tomorrow's site publish.

#please-close
