### ISSUE TITLE
Apparent conflicting rules in Special Roles

### ISSUE THREAD

**Issue by InteXX** [MicrosoftDocs/sql-docs#7502]
The general documentation for Special Roles, [here](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles?view=sql-server-ver15#special-roles-for--and-azure-synapse), indicates that "Logins cannot be added to these roles, but users can be created based on logins and then those users can be added to the roles."

The specific documentation for the `dbmanager` role, then, goes on to indicate that "A member of the dbmanager role that creates a database, becomes the owner of that database, which allows that user to connect to that database as the dbo user."

However, if we don't have a database we can't have a user. The only way that a member of the `dbmanager` role could create a database is for that member to be a login. But the rules have already laid out the notion that logins can't be added to the role.

Something is wrong here. I'm getting an error when I run this script:

```
CREATE LOGIN test WITH PASSWORD=N'Passw0rd'
GO

ALTER ROLE dbmanager ADD MEMBER test
GO
```
I've also tried:

```
ALTER SERVER ROLE dbmanager ADD MEMBER test
GO
```
The error returned is:

> Cannot add the server principal 'test', because it does not exist or you do not have permission.

This despite the fact that the login has indeed been added, as indicated by a corresponding TreeView node in SSMS. It's not a permissions issue, as the commands are issued under `sysadmin` credentials.

Some clarification is in order. Which rule takes precedence?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d95c4e-dfbb-ec5a-7df9-8a8d33be5b83
* Version Independent ID: a35a9368-4e76-6d55-7e90-34e925b34dd7
* Content: [Database-Level Roles - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles?view=sql-server-ver15#special-roles-for--and-azure-synapse)
* Content Source: [docs/relational-databases/security/authentication-access/database-level-roles.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/database-level-roles.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hey @InteXX - For clarification, these roles are special to Azure SQL Database.

![image](https://user-images.githubusercontent.com/40007119/164513924-58ea81a2-aa31-469e-9f67-93f3722f6974.png)


You're referencing `sysadmin`, which is a server level role and doesn't apply to Azure SQL Database. Can you please clarify?
