### ISSUE TITLE
Label change: Button was renamed to "Add connection"

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/sql-docs#7509]
The page states:

> For Connection type, select Azure Monitor Logs.

However, the button seems to have been renamed to "Add connection":

![grafik](https://user-images.githubusercontent.com/13981145/164888968-09a9e629-ee77-45c9-a4e5-b06d8ce2a281.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aecdd154-9637-879f-dee2-34c2aa258026
* Version Independent ID: ddf6aa52-ff98-ad96-8814-ead8c433a774
* Content: [Azure Monitor Logs extension for Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/azure-monitor-logs-extension?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/extensions/azure-monitor-logs-extension.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/extensions/azure-monitor-logs-extension.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@NenoLoje -- Neno, thank you for bringing this to our attention.  I am updating the article.
