### ISSUE TITLE
Trivial but...

### ISSUE THREAD

**Issue by irdublu** [MicrosoftDocs/sql-docs#7512]
In your example Lax mode and strict mode and in the table below it, you say Bristol is in the County of Avon.  Avon was disbanded in 1996.  Bristol is a city and county.  I suggest you choose another city for your example.

**Comment by WilliamAntonRohm** [comment]
@irdublu -- thank you for your feedback.  To which docs.microsoft.com article are you referring?

**Comment by irdublu** [comment]
Take a look at [](JSON_QUERY Transact-SQL https://docs.microsoft.com/en-us/sql/t-sql/functions/json-query-transact-sql?view=sql-server-ver15)

**Comment by WilliamAntonRohm** [comment]
@irdublu -- thank you for your follow-up.  I am updating this article.

**Comment by irdublu** [comment]
Great.  Choose Cheltenham in Gloucestershire or Exeter in Devon or wherever you choose so long as it is right.
