### ISSUE TITLE
sqlserver driver for ubuntu 22.04

### ISSUE THREAD

**Issue by bhaveshghadi-konsultera** [MicrosoftDocs/sql-docs#7514]
when can we expect SQL server driver for ubuntu 22.04

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @bhaveshghadi-konsultera - Unfortunately, we can't comment on any future releases, and this page is only for documentation issue. Sorry for the inconvenience.
