### ISSUE TITLE
"apache" instead of "azuredatastudio"

### ISSUE THREAD

**Issue by richardblaha** [MicrosoftDocs/sql-docs#7518]
In shell commands at the section "Uninstall Azure Data Studio from Linux" - "In Debian" there is "apache" instead of "azuredatastudio".

Also, the title of the section could be "In Ubuntu/Debian" because Ubuntu is the most widely used Debian derivate. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/download-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download-azure-data-studio.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @tdoshin
* Microsoft Alias: **timioshin**

**Comment by dzsquared** [comment]
#assign:tdoshin

**Comment by markingmyname** [comment]
@tdoshin can you help assist?

**Comment by tdoshin** [comment]
Please confirm @richardblaha
