### ISSUE TITLE
Please update example on RESTRICTED_USER usage

### ISSUE THREAD

**Issue by osapeliuk** [MicrosoftDocs/sql-docs#7523]
Hello, in example [RESTRICTED_USER/MULTI_USER](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options?redirectedfrom=MSDN&view=azuresqldb-current#a-set-the-database-to-read_only) should be **USE _[database_name];_** instead of _**USE master;**_. 
When running this query on master, 
```
USE master;
GO
ALTER DATABASE [database_name]
SET RESTRICTED_USER;
GO
```

error is thrown:
```
Msg 42008, Level 16, State 3, Line 1
ODBC error: State: 28000: Error: 18456 Message:'[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user '##MS_InstanceCertificate##'.'.
Msg 5069, Level 16, State 3, Line 1
ALTER DATABASE statement failed.
``` 
Please update example.

also, in case of running 
```
USE [database_name];
GO
ALTER DATABASE [database_name]
SET RESTRICTED_USER;
GO
```
it works and DB is in RESTRICTED_USER mode, but when checking database mode with:
`SELECT name, user_access_desc FROM sys.databases;`
it shows user_access_desc  as _MULTI_USER_

**Comment by WilliamAntonRohm** [comment]
@osapeliuk -- Oleksandr, thank you for your well-researched feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @osapeliuk for contacting Microsoft with feedback about our product documentation. Can you confirm that you are observing this behavior in Azure SQL Database? If so, I believe some doc updates are in order in the Azure SQL Database version, and a review of these examples are underway.
