### ISSUE TITLE
sqlpackage does not work on arch linux based distros with icu 71.1-1

### ISSUE THREAD

**Issue by sarvasana** [MicrosoftDocs/sql-docs#7526]
Running [`sqlpackage`](https://aur.archlinux.org/packages/sqlpackage) on arch linux based distros with [icu 71.1-1](https://archlinux.org/packages/core/x86_64/icu/) results in following error:

_"Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support."_

A work around is adding below export to `.bashrc` or `.zshrc`.
```bash 
export CLR_ICU_VERSION_OVERRIDE=71.1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3df6af-9ac8-bc57-93dc-29ff713c1d3b
* Version Independent ID: 7624e2cc-7aa9-40dd-4015-3371ea2ea0a2
* Content: [Download and install sqlpackage - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/sqlpackage/sqlpackage-download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage/sqlpackage-download.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@sarvasana -- Kris, thank you for your feedback and solution.

@dzsquared -- Drew, please look into this issue.

**Comment by dzsquared** [comment]
Thank you for the information on the difficulty you overcame to use SqlPackage on arch based linux.  At this time we're not ready to expand the support matrix for SqlPackage further from the set listed in the docs:
- Debian 9, 10, 11
- Red Hat Enterprise Linux 7+
- SUSE Linux Enterprise Server v12 SP2+
- Ubuntu 16.04, 18.04, 20.04

I do appreciate the feedback and we are working towards improved compatibility in the future.

#please-close
