### ISSUE TITLE
Does "execute as" is mandatory in natively compiled stored procedures?

### ISSUE THREAD

**Issue by tamirzas** [MicrosoftDocs/sql-docs#7530]
[see the full question in stackoverflow](https://stackoverflow.com/questions/72075883/does-execute-as-is-mandatory-in-natively-compiled-stored-procedures)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3753d78f-048a-dc22-a4f0-cef8eb9340e6
* Version Independent ID: 933e4f88-fe3b-5236-8e3c-aa12718c531a
* Content: [Native Compilation Advisor - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/native-compilation-advisor?view=sql-server-ver15#code-sample)
* Content Source: [docs/relational-databases/in-memory-oltp/native-compilation-advisor.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/native-compilation-advisor.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @LitKnd
* Microsoft Alias: **kendralittle**

**Comment by WilliamAntonRohm** [comment]
@tamirzas -- thank you for your question.  I'm glad you found a satisfactory answer on stackoverflow.  

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
