### ISSUE TITLE
Can't read text in the attached pictures

### ISSUE THREAD

**Issue by dplautjhmi** [MicrosoftDocs/sql-docs#7533]
The text in the screenshots is not legible. Please replace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b26df5c-92a8-91e4-3fd1-e90d28157778
* Version Independent ID: ee0fa626-9318-7cf6-e27d-66d512fc2ee3
* Content: [Work with Change Tracking - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/work-with-change-tracking-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/track-changes/work-with-change-tracking-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/work-with-change-tracking-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@dplautjhmi -- David, thank you for your feedback.  I am updating those images.

**Comment by rwestMSFT** [comment]
@WilliamAntonRohm Please assign this to me, and I'll replace them with Markdown tables instead.

**Comment by WilliamAntonRohm** [comment]
@rwestMSFT -- thank you Randolph.

#reassign @rwestMSFT

**Comment by rwestMSFT** [comment]
@dplautjhmi We are experiencing a delay in our approval of content updates, but as soon as the article has been approved, this issue will close automatically, and you will see an update in less than a day after that.
