### ISSUE TITLE
Typo in example the for Escaping values in the connection URL

### ISSUE THREAD

**Issue by dovigoldstein** [MicrosoftDocs/sql-docs#7534]
There seems to be a typo in the [Escaping values in the connection URL](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15#escaping-values-in-the-connection-url) section.

The connection string should be:
 `jdbc:sqlserver://localhost;username=MyUsername;password={pass";{}word};`

Instead of: 
`jdbc:sqlserver://localhost;username=MyUsername;password={pass";{}}word};`

Notice the extra `}` in the password

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53cbf1a-c62f-e9db-1e44-ee1f7004c0e4
* Version Independent ID: ff9a1e3c-3e36-fab8-e226-e2515fc3e8ba
* Content: [Building the connection URL - JDBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15#escaping-values-in-the-connection-url)
* Content Source: [docs/connect/jdbc/building-the-connection-url.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/building-the-connection-url.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
It's not a typo. That extra `}` is what is escaping the `}` in the password in JDBC driver versions 8.4+. Without the double `}}`, the single `}` would be seen by the driver as the end of the password.

Regards,
David

**Comment by dovigoldstein** [comment]
Wow @David-Engel , that was fast!

My bad, I missed this part : 

> **closing** braces must be escaped

Thanks again!
