### ISSUE TITLE
There is no documentation for batch started or batch completed groups

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#7537]
Was this an oversight?  There appears to be no documentation on what is captured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e423dd72-6012-f9f0-9bd1-6ab946399770
* Version Independent ID: f55d3328-111e-13d2-d8c2-78ba2b644b91
* Content: [SQL Server Audit Action Groups and Actions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @sravanisaluru
* Microsoft Alias: **srsaluru**

**Comment by sravanisaluru** [comment]
could you please elaborate more , audit action groups for server and database does cover these action groups 


BATCH_COMPLETED_GROUP | This event is raised whenever any batch text, stored procedure, or transaction management operation completes executing. It is raised after the batch completes and will audit the entire batch or stored procedure text, as sent from the client, including the result. Added in SQL Server 2019.
-- | --
BATCH_STARTED_GROUP | This event is raised whenever any batch text, stored procedure, or transaction management operation starts to execute. It is raised before execution and will audit the entire batch or stored procedure text, as sent from the client. Added in SQL Server 2019.

**Comment by PrometheusRising1** [comment]
To elaborate, other classes have more in-depth documentation linked - for example the backup restore group has a link with more in-depth information on the class and the columns returned in the audit message:
<html>
<body>


BACKUP_RESTORE_GROUP | This event is raised whenever a backup or restore command is issued. Equivalent to the Audit Backup and Restore Event Class.
-- | --



</body>
</html>BACKUP_RESTORE_GROUP	This event is raised whenever a backup or restore command is issued. Equivalent to the [Audit Backup and Restore Event Class](https://docs.microsoft.com/en-us/sql/relational-databases/event-classes/audit-backup-and-restore-event-class?view=sql-server-ver15).

**Comment by sravanisaluru** [comment]
Thank you for the clarification. I have updated the documentation with the required links 

https://learn.microsoft.com/en-us/sql/relational-databases/event-classes/sql-batchcompleted-event-class?view=sql-server-ver15

https://learn.microsoft.com/en-us/sql/relational-databases/event-classes/sql-batchstarting-event-class?view=sql-server-ver15

https://github.com/MicrosoftDocs/sql-docs-pr/pull/27530

pull request for reference.

**Comment by sravanisaluru** [comment]
#close

**Comment by WilliamAntonRohm** [comment]
#please-close
