### ISSUE TITLE
The page doesn't say that you need to have 'WITH SCHEMABINDING' for the function to be considered as "deterministic"

### ISSUE THREAD

**Issue by veljkoz** [MicrosoftDocs/sql-docs#7561]
Page describes (and briefly touches on topic of deterministic functions) but it fails to say that "WITH SCHEMABINDING" is required for the function to be considered deterministic (and afterwards used as a calculated index column)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea8a53d-e5c1-bd0e-34ca-c68cedb738c8
* Version Independent ID: 59238b70-ff8d-8feb-9d0a-be85d20960db
* Content: [User-Defined Functions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/user-defined-functions?view=sql-server-ver15)
* Content Source: [docs/relational-databases/user-defined-functions/user-defined-functions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/user-defined-functions/user-defined-functions.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@veljkoz -- thank you for your considered feedback.

@rothja -- please look into this issue.

**Comment by rwestMSFT** [comment]
@veljkoz Thank you for your contribution. I will look into this for our next refresh of this article.

**Comment by rwestMSFT** [comment]
@veljkoz Thank you once again. Your query prompted a refresh of all UDF articles. Once they are published in the next couple of days, you will see the following sentence added to the article in question:

> Deterministic functions must be schema-bound. Use the SCHEMABINDING clause when creating a deterministic function.

**Comment by veljkoz** [comment]
Thanks, I appreciate your responsiveness and how you didn't let this get forgotten 👍
