### ISSUE TITLE
Computed columns need QUOTED_IDENTIFIER to be on and this should be mentioned as a pre-requisite in the computed columns page

### ISSUE THREAD

**Issue by kanishkjaiswal2015** [MicrosoftDocs/sql-docs#7568]
We happen to learn this the hard way after many of our production databases running into issues after we added a computed column. Please update the doc page for computed columns

The pre-requisite for QUOTED_IDENTIFIER to be on for computed columns is listed in the QUOTED_IDENTIFIER doc page. 
https://docs.microsoft.com/en-us/sql/t-sql/statements/set-quoted-identifier-transact-sql?view=sql-server-ver15#:~:text=SET%20QUOTED_IDENTIFIER%20must%20be%20ON%20when%20you,when%20you%20use%20the%20SET%20statements.

**Comment by WilliamAntonRohm** [comment]
@kanishkjaiswal2015 -- thank you for your feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @kanishkjaiswal2015 for taking the time to provide this feedback, your suggestions help improve our documentation. This well-researched issue will be part of an upcoming Doc update to this area.
