### ISSUE TITLE
Duplicate text

### ISSUE THREAD

**Issue by tonyabbott** [MicrosoftDocs/sql-docs#7577]
The following paragraph contains duplicate text:

> The --hostname parameter as discussed above, **changes the internal name of the container to a custom value. This changes the internal name of the container to a custom value.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@tonyabbott -- Tony, thank you for catching this.  I am updating the article.

**Comment by TimShererWithAquent** [comment]
@WilliamAntonRohm If you haven't looked at this yet, I'll be fixing it in the dev edit workflow.

**Comment by TimShererWithAquent** [comment]
This will be fixed in MicrosoftDocs/sql-docs-pr/pull/22137 in a couple of days -

**Comment by rwestMSFT** [comment]
#please-close
