### ISSUE TITLE
SQL Agent Extension Upgrade issue

### ISSUE THREAD

**Issue by abhijeet-ubale** [MicrosoftDocs/sql-docs#7581]
**Problem:** 
Error while upgrading the SQL Server IaaS Agent - 

"New-AzSqlVM: Long running operation failed with status 'Failed'. Additional Info:'Error: 'Invalid data returned from get tempdb log path query;System.Exception: Invalid data returned from get tempdb log path query"

**Cause:**
In our case the TempDB was based on NDF files instead of LDF files, which caused the below Agent code to fail - 
![image](https://user-images.githubusercontent.com/105677414/168680224-5dcbdc49-ca0e-418b-99bc-48bd884cd4a9.png)

**Resolution:**
1. Provide a LDF file to the TempDB 
2. Restart "Microsoft SQL Server Iaas Query Service" and "Microsoft SQL Server IaaS Agent" within Windows Services
3. Remove the additional LDF file if you don't need it

**Comment by WilliamAntonRohm** [comment]
@abhijeet-ubale -- thank you for your well-researched feedback.  Are you following a particular docs.microsoft.com article?

**Comment by abhijeet-ubale** [comment]
> @abhijeet-ubale -- thank you for your well-researched feedback. Are you following a particular docs.microsoft.com article?

Thanks! 

I was following this article to upgrade the Agent (ref: https://docs.microsoft.com/en-us/azure/azure-sql/virtual-machines/windows/sql-agent-extension-manually-register-single-vm?view=azuresql&tabs=bash%2Cazure-cli)

**Comment by rwestMSFT** [comment]
@abhijeet-ubale I'm revisiting this issue because it has been open for some time. What action would you like us to take with the documentation?

**Comment by rwestMSFT** [comment]
#reassign:rwestMSFT

**Comment by rwestMSFT** [comment]
I'm closing this issue. If you have any feedback, please let me know.

I don't consider this a documentation issue. It seems more like a support issue with the cmdlet.

**Comment by rwestMSFT** [comment]
#please-close
