### ISSUE TITLE
 depricating basic authentication, Add warning and workaround for How to use database mail. 

### ISSUE THREAD

**Issue by HitenBhavsarMSFT** [MicrosoftDocs/sql-docs#7584]
Please add the warning, since basic authentication deprecating. 

An Alternative to db_mail would be to use Logic Apps: [https://docs.microsoft.com/en-us/azure/data-factory/how-to-send-email](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdata-factory%2Fhow-to-send-email&data=05%7C01%7Chibhavsa%40microsoftsupport.com%7Cfb220b327af24f4087fd08da34360529%7Cb4c546a47dac46a6a7dded822a11efd3%7C0%7C0%7C637879703869235974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pJjq6cuMBzgicOTj28R%2B1GUB6twdlw93eKSIO4TKhJg%3D&reserved=0) 
but there is on sample custom code to connect to SQL MI. 

> Note
> The deprecation of basic authentication will also prevent the use of app passwords with apps that don't support two-step verification.

https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online#re-enabling-and-opting-out-of-proactive-protection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c36343-c4f9-b55d-6d24-e0fb12ccde7e
* Version Independent ID: 984e7366-9f29-26e0-9a22-7b972eaec3fd
* Content: [Database Mail Configuration Objects - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/database-mail/database-mail-configuration-objects?view=sql-server-ver15)
* Content Source: [docs/relational-databases/database-mail/database-mail-configuration-objects.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/database-mail/database-mail-configuration-objects.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@HitenBhavsarMSFT -- Hiten, thank you for your feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @HitenBhavsarMSFT for taking the time to provide this feedback, your suggestions help improve our documentation. This will be included in a Doc update already in flight.
