### ISSUE TITLE
Docs don't mention that UAMI cannot be used to connect to AKV's that are not publicly accessible

### ISSUE THREAD

**Issue by Jaffacakes82** [MicrosoftDocs/sql-docs#7586]
It would be great if the documentation could include the fact that connectivity isn't currently possible if trying to connect to a network restricted Key Vault when enabling TD from a User Assigned Managed Identity attached to Azure SQL. System Assigned identity does work, but I spent a long time trying to work out why connectivity wasn't working for my UAMI!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b6d066-9a0d-ebdb-7432-fb4ae7a82794
* Version Independent ID: 645e4ba4-7898-c2ec-bbb4-c39aecb7e21f
* Content: [Common errors with customer-managed keys in Azure Key Vault - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/troubleshoot-tde?view=azure-sqldw-latest)
* Content Source: [docs/relational-databases/security/encryption/troubleshoot-tde.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/troubleshoot-tde.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @shohamMSFT
* Microsoft Alias: **shohamd**

**Comment by WilliamAntonRohm** [comment]
@Jaffacakes82 -- Joe, thank you for your well-researched feedback.

@shohamMSFT -- Shoham, please look into this issue.

**Comment by shohamMSFT** [comment]
@Jaffacakes82 thanks for the feedback! The current limitation that UAMI cannot be used with TDE when key vault is behind a Vnet or firewall is documented here - https://docs.microsoft.com/en-us/azure/azure-sql/database/transparent-data-encryption-byok-identity?view=azuresql#limitations-and-known-issues .
This is a limitation of the UAMI feature that is in preview currently and will be removed by GA.

**Comment by shohamMSFT** [comment]
#please-close
