### ISSUE TITLE
Installation Instructions Update Needed To Address RHEL 9

### ISSUE THREAD

**Issue by arazilsongweaver** [MicrosoftDocs/sql-docs#7588]
The SQL Server 2019 installation instructions need to be updated to address Red Hat Enterprise Linux (RHEL) release 9. RHEL 9 removes the python2 and compat-openssl10 packages that are currently required by SQL Server 2019. (https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/considerations_in_adopting_rhel_9/index#doc-wrapper)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b543b57-f397-779d-6fe4-1bc2ecd3bdca
* Version Independent ID: e274a0f3-ec74-e809-f4d3-515782b29a92
* Content: [RHEL: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-red-hat?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-red-hat.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-red-hat.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@arazilsongweaver -- Arazil, thank you for your clear feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by rwestMSFT** [comment]
@arazilsongweaver Thank you for raising this issue. SQL Server 2019 is only supported on Red Hat 7.x and 8.x right now. When RHEL 9 is released, we will do internal certification testing, and as with previous Cumulative Updates that adopt new distribution versions, if the new version is supported, we will update the documentation accordingly.

We appreciate that you took the time to submit this issue, and we'll be sure to add a note about package support when the time comes.

#please-close

**Comment by tsondergaard** [comment]
@rwestMSFT, RHEL 9 was released almost four months ago on 2022-05-17. Do you know when we can expect SQL Server 2019 for RHEL 9?

**Comment by rwestMSFT** [comment]
@tsondergaard Thank you for your question. My previous comment stands.

**Comment by troglobytor** [comment]
Centos 9 Stream and Ubuntu 22.04 have difficulties with mssql 2022 and 2019 for a variety of reasons, Some selinux  and polkit on Centos 9 andlibldap-2.4-2 baked into 2022 mssql

**Comment by rwestMSFT** [comment]
@troglobytor SQL Server is not supported on CentOS. You can read more about supported distributions for [SQL Server 2017](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2017#supported-platforms), [SQL Server 2019](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019#supported-platforms) and [SQL Server 2022](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2022#supported-platforms).

As with previous Cumulative Updates that adopt new distribution versions (for example Ubuntu 22.04 and Red Hat 9), if the new version is supported, we will update the documentation accordingly.

**Comment by Pancat007** [comment]
Hi Team,
What about SQL Server 2022? if it's supported Red Hat 9.0? based on the documentation, it's supported on Red Hat 8.0-8.6
https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2022?view=sql-server-ver16

**Comment by tsondergaard** [comment]
We are not supposed to ask such questions - I expect you will get a terse impatient silly-you reply that references https://github.com/MicrosoftDocs/sql-docs/issues/7588#issuecomment-1141457249

**Comment by troglobytor** [comment]
For now it seems docker and podman will work

**Comment by rwestMSFT** [comment]
@tsondergaard Thank you for your comment. We are not permitted to comment on future plans.

**Comment by limershein** [comment]
Please note that Microsoft and Red Hat announced full support for SQL Server 2022 CU10 on RHEL9, including support for using SQL Server with SELinux,  this week at the PASS Data Community Summit. See:  https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-red-hat?view=sql-server-ver16
