### ISSUE TITLE
The lists of bug fixes for ODBC Driver 17.9 & 18.0 for SQL Server are identical

### ISSUE THREAD

**Issue by scarson** [MicrosoftDocs/sql-docs#7590]
This looks suspiciously like a copy/paste error and should be clarified or corrected.
The page currently reads:

**Bug fixes in the Microsoft ODBC Driver 18.0 for SQL Server**

- Fix UI issues where text was cut off and position of items was off.
- Fix issue with Active Directory Interactive login where attempting to login after closing the window of the first failure would automatically succeed if cached credentials were available.
- Fixed use of XADTC with Azure SQL Managed Instance.
- Fixed loss of Azure Active Directory authentication mode when reconnecting an idle connection.
- Fix an issue with federated authentication when using PingFed.

**Bug fixes in the Microsoft ODBC Driver 17.9 for SQL Server**

- Fix UI issues where text was cut off and position of items was off.
- Fix issue with Active Directory Interactive login where attempting to login after closing the window of the first failure would automatically succeed if cached credentials were available.
- Fixed use of XADTC with Azure SQL Managed Instance.
- Fixed loss of Azure Active Directory authentication mode when reconnecting an idle connection.
- Fix an issue with federated authentication when using PingFed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7979ca60-7e38-17bf-53fa-c1b67361d510
* Version Independent ID: 119d65f3-c90b-1d17-a948-29746cc0579f
* Content: [List of bugs fixed - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/bug-fixes?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/bug-fixes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/bug-fixes.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @v-chojas
* Microsoft Alias: **v-chojas**

**Comment by David-Engel** [comment]
17.9 was released after 18.0 (2 weeks apart). The bugs were fixed in 18.0 and backported to the 17.x driver. Both major versions are under support.

**Comment by WilliamAntonRohm** [comment]
@scarson -- Sam, thank you for your interest and feedback.

@David-Engel -- David, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
