### ISSUE TITLE
Does Not Support Filestream?

### ISSUE THREAD

**Issue by keithnicholson** [MicrosoftDocs/sql-docs#7593]
"Filestream: RLS is incompatible with Filestream."

What does this mean?  If Filestream is on a database, 

> then RLS cannot be used on any table?
> Then RLS cannot be used on a table referencing the blob?
> Then RLS cannot be used with a predicate on the file?

Can you provide clarity in this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c96c3ee-5443-004f-d189-3701f8bef6c9
* Version Independent ID: efcc952b-eadb-4579-54c7-00da3bc107ae
* Content: [Row-Level Security - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/row-level-security?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/row-level-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/row-level-security.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @keithnicholson - Thanks for the question! It's not that RLS can't be used when FILESTREAM is enabled. FILESTREAM is secured by granting permissions at the table or column levels, and if a user has permissions to the FILESTREAM column, the user can open the associated files, and hence it's incompatible with RLS since it defeats the purpose.

**Comment by keithnicholson** [comment]
Thank you for the insight.  I'll think through this and consider how else my design could go.

Regarding this "issue", would it feasible to edit the line stating something similar with a reference to **https://docs.microsoft.com/en-us/sql/relational-databases/blob/filestream-sql-server?view=sql-server-ver15#integrated-security**  That might help others.

If not, just say so and feel free to close this comment out.


In my scenario, it is not so much that we are protecting anything specific or secret in the documents as much as mitigating what a user thinks they have access to without trusting the developer to filter on the client side.

I might play with the idea of using RLS for users accessing through a middle-tier app to a look up table (Scenarios C and D in this doc).  That table would then provide some identifier to access the document, The middle tier would not return this identifier to the client, but would rather permit the middle tier service account view/read-only access to the table with the FileStream column.

Peace!
