### ISSUE TITLE
404 page not found error

### ISSUE THREAD

**Issue by aruwo17** [MicrosoftDocs/sql-docs#7597]
[Enter feedback here]

1. Section: **Options** (https://docs.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-end-of-support-overview?view=sql-server-ver15#options)
2. Link in 2nd bullet point is broken, that is, Free Extended Security Updates (https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sql/virtual-machines-windows-sql-server-2008-eos-extend-support)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89223ae2-d21a-20df-90f1-75d6a7ef2600
* Version Independent ID: 89223ae2-d21a-20df-90f1-75d6a7ef2600
* Content: [End of support options - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-end-of-support-overview?view=sql-server-ver15)
* Content Source: [docs/sql-server/end-of-support/sql-server-end-of-support-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/end-of-support/sql-server-end-of-support-overview.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
We are aware of this issue and are waiting for a content freeze to lift.

**Comment by WilliamAntonRohm** [comment]
@aruwo17 -- thank you for your feedback.

@rwestMSFT -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by rwestMSFT** [comment]
@aruwo17, we were able to find other URLs that were not resolving correctly, after doing some digging.

Thank you again for raising this issue. You've helped us more than you could know.

**Comment by aruwo17** [comment]
That's great. Glad I could be of help.


Best regards,

________________________________
