### ISSUE TITLE
Code appears to be incorrect

### ISSUE THREAD

**Issue by dbuskirk** [MicrosoftDocs/sql-docs#7600]
A mean squared error of 3e-27 should have been a giveaway. It looks like this code does not remove the target column from the training set, thereby allowing a perfect linear model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37966482-bf2c-619a-1bff-5e3706d5a051
* Version Independent ID: 00869b9b-ea04-4110-6227-91039c979001
* Content: [Python tutorial: Train model - SQL machine learning](https://docs.microsoft.com/en-us/sql/machine-learning/tutorials/python-ski-rental-linear-regression-train-model?view=sql-server-ver15)
* Content Source: [docs/machine-learning/tutorials/python-ski-rental-linear-regression-train-model.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/tutorials/python-ski-rental-linear-regression-train-model.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@dbuskirk -- Dan, thank you for your clear feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @dbuskirk for contacting Microsoft with feedback about our product documentation. It could take from a few business days to a few weeks to look further into this with the product team and decide on how to address. We'll contact you if we need further information, and you'll receive an email message each time we mention you in a comment. 
	
Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
Great catch @dbuskirk and thanks for taking the time to create a GitHub issue and point this out. A doc update is in flight to address this in Step 2 of the tutorial.
