### ISSUE TITLE
Confirm SQL Server 2008/2008R2 ESU timelines

### ISSUE THREAD

**Issue by pablojavierf** [MicrosoftDocs/sql-docs#7611]
Hi Team! I've seen in the referenced doc that as part of subtitle "SQL Server on Azure VMs" for Benefits for Extended Security Updates it points out that you can have ESU free for three years past the end of support date. For that particular case we know it would be until July 2022.

However, there is also another documentation https://docs.microsoft.com/en-us/lifecycle/products/microsoft-sql-server-2008-r2
which points out a fourth year for ESU.

I believe that we need to update this information as from this referenced page, it seems to have only 3 years of ESU for SQL Server 2008/2008R2 and generates some confusions with the other url.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89223ae2-d21a-20df-90f1-75d6a7ef2600
* Version Independent ID: 89223ae2-d21a-20df-90f1-75d6a7ef2600
* Content: [End of support options - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-end-of-support-overview?view=sql-server-ver16#feedback)
* Content Source: [docs/sql-server/end-of-support/sql-server-end-of-support-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/end-of-support/sql-server-end-of-support-overview.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@pablojavierf -- thank you for your close reading.

@rwestMSFT -- please look into this issue.

**Comment by rwestMSFT** [comment]
Hi Pablo. Thanks for noting this. The page is already staged, and will be published sometime in June.

#please-close
