### ISSUE TITLE
Download link goes to version 18.11.1

### ISSUE THREAD

**Issue by lucascbaker** [MicrosoftDocs/sql-docs#7612]
As the title suggests, the download link on the preview release page goes to the current GA release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0bd2a7f-92e7-7ee4-7dec-84491d97a66f
* Version Independent ID: f0bd2a7f-92e7-7ee4-7dec-84491d97a66f
* Content: [Download SQL Server Management Studio (SSMS) 19 - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms-19?view=sql-server-ver16)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms-19.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms-19.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by WilliamAntonRohm** [comment]
@lucascbaker -- Lucas, thank you for bringing this to our attention.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@lucascbaker -- Lucas, when I click on the [Download SQL Server Management Studio (SSMS) 19 (Preview)](https://go.microsoft.com/fwlink/?linkid=2195969&clcid=0x409) link, I get the correct installer.  Please try again and attach a screenshot here of your own results.

![image](https://user-images.githubusercontent.com/27738025/170147176-dc1ed0d8-0987-45fd-b5f1-36ee84aa67b4.png)

**Comment by lucascbaker** [comment]
@WilliamAntonRohm The link appears to be working now.  It appears to have been updated.  Thanks.
