### ISSUE TITLE
SSMS-Setup-ENU.exe contains PUA (Potentially Unwanted Application)

### ISSUE THREAD

**Issue by SHAGGAR** [MicrosoftDocs/sql-docs#7622]
The SSMS installer forces you to install the potentially unwanted application "Azure Data Studio" by default.  Azure Data Studio is marketing software used to promote Microsoft's Azure cloud data products.  It is not useful for managing SQL server which is the purpose of SSMS.  

Stop shipping Azure Data Studio with SSMS entirely or make it an optional install that is disabled by default.  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by WilliamAntonRohm** [comment]
@SHAGGAR -- thank you for your feedback.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
