### ISSUE TITLE
Contained availability group VS what customers demand

### ISSUE THREAD

**Issue by xxflop** [MicrosoftDocs/sql-docs#7626]
Negatively surprised by the implementation of this feature. I think that 99% of our customers using AG expected a feature similar to the replicatedmaster in the Azure SQL Server Managed Instance. Did you ask the customers what they need? In my experience the typical response will be "we want it to work as it worked in a failover cluster instance".

I understand that one instance can be a replica of multiple AG and due to that this implementation will work better in this scenario but this is, in my experience, the edge scenario. The most common is to have 2-3 nodes for HA+distribute read only loads all that with only one AG and 0 to 1 listeners. Apart from that it is common that some read only applications connect directly to the master database of one of the replicas, maybe due to the physical location of the replica, maybe due to legacy apps not supporting adding the application intent in the connection string.

Which is the reason not offering (instead or additionally) the replicatedmaster alternative you already have implemented for Azure Sql Server Managed Instance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 269d8ec6-8675-a302-0a8a-e03222d04fa5
* Version Independent ID: 269d8ec6-8675-a302-0a8a-e03222d04fa5
* Content: [What is a contained availability group? - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/contained-availability-groups-overview?view=sql-server-ver16)
* Content Source: [docs/database-engine/availability-groups/windows/contained-availability-groups-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/contained-availability-groups-overview.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @kfarlee
* Microsoft Alias: **kfarlee**

**Comment by aldinabbe** [comment]
Hi,
 I'm new. 
Can someone help me create date function in SQL?
Back 7 days with datename, date, month and year. I hope you undarstand me.
Thank you!
