### ISSUE TITLE
SQL Graph SHORTEST_PATH Syntax error Example D, E and F

### ISSUE THREAD

**Issue by GLaDAP** [MicrosoftDocs/sql-docs#7629]
Hi!

When trying the examples from the SHORTEST_PATH (SQL Graph) page I encountered a problem when running example D, E and F. For example with D: _Find people 1-3 hops away from a given person_
```
SELECT
	Person1.name AS PersonName,
	STRING_AGG(Person2.name, '->') WITHIN GROUP (GRAPH PATH) AS Friends
FROM
	Person AS Person1,
	friendOf FOR PATH AS fo,
	Person FOR PATH  AS Person2
WHERE MATCH(SHORTEST_PATH(Person1(-(fo)->Person2){1,3}))
AND Person1.name = 'Jacob'
```
I get a syntax error when using the `{1,3}` notation (SqlState 42000, Syntax error, permission violation, or other nonspecific error). 
Examples not using this notation works fine (e.g. A, B, C and G)

I use the Docker version of SQL Server 2019 (tag:2019-CU15-ubuntu-20.04) and the sample data is from the SQL Graph sample page.

SQL Server Version:
Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64) 
        Jan 12 2022 22:30:08 
        Copyright (C) 2019 Microsoft Corporation
        Developer Edition (64-bit) on Linux (Ubuntu 20.04.3 LTS) <X64>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44d0352c-3838-e788-f99e-ba6171fe2acc
* Version Independent ID: 22c33c5e-8e6d-7bf8-cace-f59af7b5cc7f
* Content: [SHORTEST PATH (SQL Graph) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-shortest-path?view=sql-server-ver16)
* Content Source: [docs/relational-databases/graphs/sql-graph-shortest-path.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/graphs/sql-graph-shortest-path.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by GLaDAP** [comment]
@arvindshmicrosoft I use sqlcmd within the Docker container using the method described [here](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash#connect-to-sql-server)

Using `go-sqlcmd` did execute the example queries succesfully without problems

**Comment by arvindshmicrosoft** [comment]
OK thanks for the feedback. This may likely be another oddity specific to SQL Server on Linux. I will ask around and update this issue if I find anything. In the meantime, since go-sqlcmd is being actively worked upon and is open-source, I encourage you to consider using that.

**Comment by GLaDAP** [comment]
Thanks for the tip, I will use `go-sqlcmd` from now on

**Comment by WilliamAntonRohm** [comment]
@GLaDAP -- David, thank you for your feedback, and glad you have a solution.

@arvindshmicrosoft -- Arvind, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
