### ISSUE TITLE
How do we determine what windows account is associated with SQL Server agent?

### ISSUE THREAD

**Issue by cactushacker** [MicrosoftDocs/sql-docs#7640]
For Pull/Merge subscriptions we need to add access for the Windows Account used to run the agent. How do we determine what windows account is associated with SQL Server agent? We can see the Windows account used in services.msc, are those the accounts that need access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a6bafd8-1642-5536-d024-2d4c46e07cc3
* Version Independent ID: f28f3eaf-7ec6-8ff8-c56c-770096e9f44f
* Content: [Secure the Snapshot Folder - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/security/secure-the-snapshot-folder?redirectedfrom=MSDN&view=sql-server-ver16)
* Content Source: [docs/relational-databases/replication/security/secure-the-snapshot-folder.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/security/secure-the-snapshot-folder.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by OriShavit1** [comment]
Yes, the same ones seen in Services.msc are the ones who run the agent.
If needed to change the accounts, best practice is through the SQL Configuration Manager, and not Services.msc

**Comment by WilliamAntonRohm** [comment]
@OriShavit1 -- Ori, thank you for your contribution to this issue.

**Comment by WilliamAntonRohm** [comment]
@cactushacker -- I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
