### ISSUE TITLE
Missing link to SSMS

### ISSUE THREAD

**Issue by zaczekvol** [MicrosoftDocs/sql-docs#7646]
Since the page contains feature comparison to SSMS, it should also contain direct link to download SSMS at the end. Just in case SSMS turns out to be what the reader needs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 962f065e-a643-85e1-5e90-c80548681195
* Version Independent ID: aad000f8-a420-43fd-3031-c19427c38c0f
* Content: [What is Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is-azure-data-studio?view=sql-server-ver16)
* Content Source: [docs/azure-data-studio/what-is-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/what-is-azure-data-studio.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@zaczekvol -- Michał, thank you for your suggestion.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
