### ISSUE TITLE
datetime mssql

### ISSUE THREAD

**Issue by mrcetec168** [MicrosoftDocs/sql-docs#7648]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c56bf005-aaa1-2cd5-a78c-225e5d72f017
* Version Independent ID: fd7781ad-de66-ab66-3e32-29946bbb14c3
* Content: [About Code Examples in the Documentation - PHP drivers for SQL Server](https://docs.microsoft.com/en-us/sql/connect/php/about-code-examples-in-the-documentation?view=sql-server-2016)
* Content Source: [docs/connect/php/about-code-examples-in-the-documentation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/about-code-examples-in-the-documentation.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@mrcetec168 -- thank you for your feedback.  Please provide additional details and context for your intended task.
