### ISSUE TITLE
Missing Release Notes for previous versions of SSMS 2019

### ISSUE THREAD

**Issue by PedroC88** [MicrosoftDocs/sql-docs#7649]
Include a link for Release Notes for previous versions of SSMS 2019, in this site I can only see what's new on Preview 2 but I want to know what's new overall from 2018.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de5cf89b-941c-1365-de56-00bcdf130529
* Version Independent ID: de5cf89b-941c-1365-de56-00bcdf130529
* Content: [Release notes for (SSMS) 19 (Preview) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms-19?view=sql-server-ver16)
* Content Source: [docs/ssms/release-notes-ssms-19.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms-19.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by rwestMSFT** [comment]
@PedroC88  Did you check out the release notes page? https://docs.microsoft.com/sql/ssms/release-notes-ssms

**Comment by PedroC88** [comment]
@rwestMSFT Yes and that page doesn't have anything for v19, except a link to the page... unless I'm missing something.

**Comment by rwestMSFT** [comment]
There is no SSMS 2019. SSMS 19.x was only released recently for the SQL Server 2022 Preview. The current mainline version is SSMS 18.x, which was released for SQL Server 2019. I hope that helps.

**Comment by WilliamAntonRohm** [comment]
@PedroC88 -- Pedro, thank you for your feedback.

@rwestMSFT -- Randolph, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by PedroC88** [comment]
You are right, at all times I meant v18 and v19 instead of 2018 or 2019, I apologize. Having said that, where can I find the release notes for all 19 compared to 18, not just preview 2 (as described on the original question).

**Comment by rwestMSFT** [comment]
Once SSMS v19 is out of preview, you can expect to see the same kind of release notes as v18.

**Comment by erinstellato-ms** [comment]
@PedroC88 The release notes for SSMS 19 Preview 2 currently do list everything that is new since SSMS 18.11.1.  Obviously, since we are in preview, additional functionality will be added in future releases.  The release notes for SSMS 19 Preview follow the same pattern as those for SSMS 18 and below.  If you believe something is missing, or you are looking for something specific, let me know.
