### ISSUE TITLE
Duplicate sentence

### ISSUE THREAD

**Issue by Nutster67** [MicrosoftDocs/sql-docs#7650]
In the Remarks section of the documentation, the sentence, "This feature is a new additional option for DBCC SHRINKDATABASE and DBCC SHRINKFILE." appears twice in a row.  One of the duplicates should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67f0fd32-024f-734e-82c1-32b890ac591d
* Version Independent ID: bca0a8c1-05fe-91d5-37b5-0a4729c1237f
* Content: [Shrink a database - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/shrink-a-database?view=sql-server-ver16)
* Content Source: [docs/relational-databases/databases/shrink-a-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/shrink-a-database.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hi @Nutster67! Nice catch! Thanks for taking the time to fill out a GitHub issue. A doc update is in flight.
