### ISSUE TITLE
Documentation for Synapse dedicated pool is misleading or very wrong

### ISSUE THREAD

**Issue by lovalvob** [MicrosoftDocs/sql-docs#7656]
https://docs.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?toc=%2Fazure%2Fsynapse-analytics%2Fsql-data-warehouse%2Ftoc.json&bc=%2Fazure%2Fsynapse-analytics%2Fsql-data-warehouse%2Fbreadcrumb%2Ftoc.json&view=azure-sqldw-latest&preserve-view=true

The remarks section states that "But in [CHAR(n) and VARCHAR(n)](https://docs.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=azure-sqldw-latest) the n defines the string length in bytes (0-8,000). n never defines numbers of characters that can be stored".  This is in direct conflict with sql documentation and is demonstratably incorrect for normal single- and double-byte collations. VARCHAR(8000) refers to a varchar that holds 8,000 characters.  NVARCHAR(4000) refers to a NVARCHAR that holds 4,000 characters.  Attempts to create NVARCHAR(8000) result is overflow errors.

I suppose that the documentation could be referring _UTF* datatypes, but if so, it's very unclear.

**Comment by WilliamAntonRohm** [comment]
@lovalvob -- Barry, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by MikeRayMSFT** [comment]
@assign-reviewer: WilliamDAssafMSFT 

Please review.

**Comment by WilliamDAssafMSFT** [comment]
It appears that @rwestMSFT updated this article last year and aligned it more closely with the SQL Server language, bringing clarity here. Thanks for your feedback @lovalvob, I believe this has been resolved.
