### ISSUE TITLE
Documentation for sys.geo_replication_links missing Suspended replication state

### ISSUE THREAD

**Issue by mitwong-microsoft** [MicrosoftDocs/sql-docs#7659]
replication_state and replication_state_desc are missing the 4 and "SUSPENDED" states respectively.

Might be useful to include info on this also being a transitory state during post-geo failover reseed, but not sure if this is the correct place for that documentation.

**Comment by WilliamAntonRohm** [comment]
@mitwong-microsoft -- thank you for your feedback and suggestion.  Are you referring to this article?
- [sys.geo_replication_links (Azure SQL Database)](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-geo-replication-links-azure-sql-database?view=azuresqldb-current)

@rwestMSFT -- please look into this issue.

**Comment by rwestMSFT** [comment]
@mitwong-microsoft, thanks for your feedback. I'll make a note of this for the next refresh of this article.

#please-close

**Comment by rwestMSFT** [comment]
The article has been updated.
