### ISSUE TITLE
Incorrect information in information box

### ISSUE THREAD

**Issue by Dottn** [MicrosoftDocs/sql-docs#7660]
It looks like the information box in the top of the section
#column-level-encryption-by-using-an-asymmetric-key-from-the-key-vault
should state:

You cannot use the same asymmetric key for column level encryption if you've already used that key for TDE or backup encryption (the preceding examples).

Currently it does not mention column level encryption, but references backup encryption twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 561a78d9-5662-287c-2599-a36b2102b8d5
* Version Independent ID: 9820cfde-5caa-1a7f-cdb5-06df907b7395
* Content: [Use SQL Server Connector encryption with Azure Key Vault - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/use-sql-server-connector-with-sql-encryption-features?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/encryption/use-sql-server-connector-with-sql-encryption-features.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/use-sql-server-connector-with-sql-encryption-features.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@Dottn -- thank you for your thoughtful feedback.

@jaszymas -- please look into this issue.

**Comment by rwestMSFT** [comment]
Thanks for reporting this, @Dottn, and thank you for your patience. The section in question will be updated in the next day or so.
