### ISSUE TITLE
How about a link to the odbc schema views?

### ISSUE THREAD

**Issue by thomasapto** [MicrosoftDocs/sql-docs#7665]
[Enter feedback here]
It'd be nice to have a pointer to the docs on the actual schema views, i.e., what you seem to call the INFORMATION_SCHEMA views, i.e., the SQL-92 defined views.  I think there's a list here: https://flylib.com/books/en/1.193.1.77/1/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5620249d-7da8-3669-8157-53fc15281cbb
* Version Independent ID: 36b8a69a-29f3-2cf2-1690-50af6fac5f46
* Content: [Schema Views - ODBC API Reference](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/schema-views?view=sql-server-ver16)
* Content Source: [docs/odbc/reference/develop-app/schema-views.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/develop-app/schema-views.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@thomasapto -- Tom, thank you for your suggestion.

@David-Engel -- David, please look into this issue.  I haven't found a corresponding link in docs.microsoft.com.

**Comment by David-Engel** [comment]
There are some problems with adding the requested link:

1. These docs are about the ODBC API itself, not the SQL Server-specific ODBC implementation of it. ODBC is a standard. So the views available via each ODBC driver will be dependent on the target database's implementation of the SQL-92 standard. We can't link to every known database implementation here. I'm hesitant to link to only SQL Server's information schema info in the official ODBC API docs.
2. Unfortunately, copies of the SQL-92 standard itself are not freely available. You can purchase a copy from [iso.org](https://iso.org/) or [ansi.org](https://ansi.org/).

Regards,
David

**Comment by WilliamAntonRohm** [comment]
@David-Engel -- David, thank you for clarifying.

@thomasapto --Tom, I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
