### ISSUE TITLE
Does not specify file location for repair

### ISSUE THREAD

**Issue by obi-juan-quinobi** [MicrosoftDocs/sql-docs#7667]
Does not specify file location for repair

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0cfb9c7-c818-53fa-a361-056d59204f75
* Version Independent ID: dfa0bc23-03e5-c72b-3c13-566de93ca42e
* Content: [Uninstall SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/uninstall-sql-server?view=sql-server-ver16)
* Content Source: [docs/sql-server/install/uninstall-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/uninstall-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
Hi @obi-juan-quinobi, can you point out which specific section you're referring to? If I look at [this section](https://docs.microsoft.com/sql/database-engine/install-windows/repair-a-failed-sql-server-installation#repair-a-failed-installation-of--from-the-installation-center), which is linked from the page you noted, I see the following sentence:

> Launch the SQL Server Setup program (setup.exe) from SQL Server installation media.

**Comment by rwestMSFT** [comment]
@obi-juan-quinobi If you still wish to respond, please feel free to reply here. I am closing this as resolved in the meantime.

#please-close
