### ISSUE TITLE
SSMS download link points to previous version (18.11) instead of 18.12

### ISSUE THREAD

**Issue by anilpananghat** [MicrosoftDocs/sql-docs#7670]
[Enter feedback here]
SSMS download link points to previous version (18.11) instead of 18.12

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
These will be updated shortly

**Comment by erinstellato-ms** [comment]
link was updated and points to 18.12

**Comment by erinstellato-ms** [comment]
#please-close

**Comment by anilpananghat** [comment]
thanks for updating the link
