### ISSUE TITLE
clr strict security

### ISSUE THREAD

**Issue by Oleg26Dev** [MicrosoftDocs/sql-docs#7671]
[Enter feedback here]

clr strict security

Wrote:
0 | Disabled - Provided for backwards compatibility. Disabled value is not recommended.
1 | Enabled - Causes the Database Engine to ignore the PERMISSION_SET information on the assemblies, and always interpret them as UNSAFE. Enabled is the default value, starting with SQL Server 2017 (14.x).

It seems should be:
1 | Enabled - Provided for backwards compatibility. 
0 | Disabled - Causes the Database Engine to ignore the PERMISSION_SET information on the assemblies, and always interpret them as UNSAFE. Disabled is the default value, starting with SQL Server 2017 (14.x).
Disabled value is not recommended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96693d4a-9460-9e08-8f14-836b6257e449
* Version Independent ID: 47f19aec-1f62-97c4-fca4-609496fc2139
* Content: [CLR strict security - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/clr-strict-security?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/clr-strict-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/clr-strict-security.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
Hi @Oleg26Dev.

If CLR strict security is *enabled* (the default on SQL Server 2017 and later), it means it will apply a much stricter security posture, which includes ignoring PERMISSION_SET, and always assuming assemblies to be UNSAFE.

**Comment by WilliamAntonRohm** [comment]
@Oleg26Dev -- thank you for your feedback.

@rwestMSFT -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
