### ISSUE TITLE
Active Directory Managed Identity authentication requires Principal ID NOT Client ID

### ISSUE THREAD

**Issue by ssemyan** [MicrosoftDocs/sql-docs#7673]
In the section "Using Active Directory Managed Identity authentication" that describes using the Active Directory Managed Identity authentication, you should specify that the ID's Principal ID is required, not the Client ID. This is not clear from the docs. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 947b6a2f-66c5-821d-8c58-8798a48a9f3f
* Version Independent ID: 35874772-4b2c-7679-7fa3-57e77e02fbb0
* Content: [Using Azure Active Directory authentication with SqlClient - ADO.NET Provider for SQL Server](https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16)
* Content Source: [docs/connect/ado-net/sql/azure-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/ado-net/sql/azure-active-directory-authentication.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
The [docs](https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16#using-active-directory-managed-identity-authentication) are already pretty specific about it:

> For a user-assigned managed identity, the client id of the managed identity must be provided when using Microsoft.Data.SqlClient v3.0 or newer. If using Microsoft.Data.SqlClient v2.1, the object id of the managed identity must be provided.

And code examples are provided for both version ranges with appropriately named placeholders.

The Azure Portal even labels the ID when you look at the overview of the Managed Identity: "Object (principal) ID"

How could it be made more clear?

Thanks,
David

**Comment by WilliamAntonRohm** [comment]
@ssemyan -- Scott, thank you for your feedback.

@David-Engel -- David, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
