### ISSUE TITLE
Remove extra word "You"

### ISSUE THREAD

**Issue by evans911** [MicrosoftDocs/sql-docs#7682]
Sentence miss worded or extra word:  When you are restoring backups, you can use **you** the FILE option to specify which backups you want to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65c52297-6953-da02-108c-d06d42258d73
* Version Independent ID: 85115728-2ffe-2c0f-3a3f-d5864a67c74d
* Content: [Media sets, media families, & backup sets - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/media-sets-media-families-and-backup-sets-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/media-sets-media-families-and-backup-sets-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/media-sets-media-families-and-backup-sets-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@evans911 -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
