### ISSUE TITLE
wrong statement "the device mapper (DM) multipath target"

### ISSUE THREAD

**Issue by Pitterling** [MicrosoftDocs/sql-docs#7684]
[As multipath IO is often used for SQL Server deployments, **the device mapper (DM) multipath target** should also be configured to use the blk-mq infrastructure by enabling the dm_mod.use_blk_mq=y kernel boot option. The default value is n (disabled). This setting, when the underlying SCSI devices are using blk-mq, reduces locking overhead at the DM layer. Refer to the documentation of the Linux distribution in use for additional guidance on how to configure it.

This is not multi-pathing but multi-queuing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc91cc25-7d13-a975-76ee-6d97bdcf9416
* Version Independent ID: ae8d2f7e-0c69-1269-a438-d6d36594dd27
* Content: [Performance best practices for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-performance-best-practices?view=sql-server-ver16)
* Content Source: [docs/linux/sql-server-linux-performance-best-practices.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-performance-best-practices.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @tejasaks
* Microsoft Alias: **tejasaks**

**Comment by WilliamAntonRohm** [comment]
@Pitterling -- Pitt, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@tejasaks -- Tejas, please review this update in [private PR 22991](https://github.com/MicrosoftDocs/sql-docs-pr/pull/22991).
