### ISSUE TITLE
Incorrect param name for -h

### ISSUE THREAD

**Issue by polebridge** [MicrosoftDocs/sql-docs#7685]
This page says:

            -w column_width
            Specifies the screen width

But  "sqlcmd -?" says

            [-w screen width]

This page should also say:

            -w screen_width
            Specifies the screen width

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da1f57b-a8fd-cca7-4cf0-9d594d365062
* Version Independent ID: 60c46780-6a03-7958-c77a-e7c94e3b9e85
* Content: [sqlcmd Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver16)
* Content Source: [docs/tools/sqlcmd-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlcmd-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@polebridge -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review this update in [private PR 22992](https://github.com/MicrosoftDocs/sql-docs-pr/pull/22992).
