### ISSUE TITLE
Procedure for setting available memory fails in Docker Desktop

### ISSUE THREAD

**Issue by jsmarsch** [MicrosoftDocs/sql-docs#7690]
My setup:  Docker Desktop running docker via WSL2 on Windows 10 using Linux containers.
Image: mcr.microsoft.com/mssql/server:2019-latest

I start  docker terminal session (note sudo is not available in docker terminal, apparently because you are already running as root)

Command `/opt/mssql/bin/mssql-conf set memory.memorylimitmb 3328`

Error Returned is:
`Warning: could not create log file for mssql-conf at /var/opt/mssql/log/mssql-conf/mssql-conf.log.
This program must be run as superuser or as a user with membership in the mssql
group.`

Upon restarting the container, memory has not changed.

Also, i tried to check the config file as detailed in the instructions:
`cat /var/opt/mssql/mssql.conf`
Returns the error:
`cat: /var/opt/mssql/mssql.conf: No such file or directory`

So I tried listing the contents of the /var/opt/mssql directory.  The file isn't present:

```
$ ls /var/opt/mssql/
data  log  secrets

```

Is there something different I need to do in order to configure MSSQL in docker?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c0b1027-3982-e114-0230-c6bd9bd81346
* Version Independent ID: 244740de-8817-1671-387d-970f8ee8dfcb
* Content: [Configure SQL Server settings on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-linux-ver15)
* Content Source: [docs/linux/sql-server-linux-configure-mssql-conf.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-mssql-conf.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @jsmarsch - Thanks for submitting this question. Try this article as it gives reference to running the non-root container as the root user: https://docs.microsoft.com/sql/linux/sql-server-linux-docker-container-security?view=sql-server-linux-ver15#run-the-non-root-container-as-the-root-user

@amvin87 - Adding Amit in case he has any other suggestions.

**Comment by amvin87** [comment]
Running SQL Server containers on WSL2 platform is not supported, but for testing and development purpose, you could do this manually. You can create the mssql.conf file manually and then using a text editor you could manually add an entry here is reference to https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-ver16#mssql-conf-format for creating this manually

**Comment by jsmarsch** [comment]
Thank you. The only reason I was using WSL2 is because my understanding was
that WSL2 had become the preferred host for running containers on Windows
10 (this is for a dev machine, not for production). Was I wrong about that?

**Comment by rwestMSFT** [comment]
I understand your thinking, @jsmarsch. However, SQL Server in containers are only supported on Linux, which means there's some manual work you'll have to do if you want to get containers running elsewhere, including Windows and macOS.
