### ISSUE TITLE
'SQL Server 2012 end of support' link broken

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/sql-docs#7696]
link
[SQL Server 2012 end of support](https://www.microsoft.com/cloud-platform/windows-sql-server-2012)
broken

should be
https://docs.microsoft.com/en-us/lifecycle/products/microsoft-sql-server-2012

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89223ae2-d21a-20df-90f1-75d6a7ef2600
* Version Independent ID: 89223ae2-d21a-20df-90f1-75d6a7ef2600
* Content: [End of support options - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-end-of-support-overview?view=sql-server-ver16)
* Content Source: [docs/sql-server/end-of-support/sql-server-end-of-support-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/end-of-support/sql-server-end-of-support-overview.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@OzBob -- thank you for catching this.  I am updating the article.
