### ISSUE TITLE
Wrong step title

### ISSUE THREAD

**Issue by roabrey** [MicrosoftDocs/sql-docs#7700]
Under the section "To add a member to a user-defined database role
"
The step "6. Expand the Server Roles folder" ... should be ...
"6. Expand the **Database** Roles folder"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48e8faac-493d-c9f9-1656-393f95e51d25
* Version Independent ID: 023b79b9-ced9-9c30-0bdb-d013fca515cf
* Content: [Join a Role - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/join-a-role?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/authentication-access/join-a-role.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/join-a-role.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@roabrey -- thank you for catching this. I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
