### ISSUE TITLE
The "Try SQL Server!" link is 404

### ISSUE THREAD

**Issue by stuartpa** [MicrosoftDocs/sql-docs#7713]
From this page:

[Editions and supported features of SQL Server 2019 - SQL Server | Microsoft Docs](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2019?view=sql-server-ver15)

This link:
 
	[https://www.microsoft.com//evalcenter/evaluate-sql-server](https://www.microsoft.com/evalcenter/evaluate-sql-server)

Returns:

We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2657179a-7015-033c-e294-e1f29eddcd39
* Version Independent ID: 2657179a-7015-033c-e294-e1f29eddcd39
* Content: [Editions and supported features of SQL Server 2019 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2019?view=sql-server-ver15)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-2019.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-2019.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@stuartpa -- Stuart, thank you for catching this.  I am updating the article.
