### ISSUE TITLE
Error in Invoke-Sqlcmd - Example 13 broken

### ISSUE THREAD

**Issue by dvasdekis** [MicrosoftDocs/sql-docs#7715]
On page https://docs.microsoft.com/en-us/powershell/module/sqlserver/invoke-sqlcmd?view=sqlserver-ps#examples
Example 13 currently reads:
```
Import-Module SQLServer

# Note: the sample assumes that you or your DBA configured the server to accept connections using
#       that VM Identity you are running on and has granted it access to the database (in this 
#       example at least the SELECT permission).

### Obtain the Access Token from the machine
$response = Invoke-WebRequest `
     -Uri 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fdatabase.windows.net'`
     -Method GET`
     -Headers @{Metadata="true"}
$access_token = ($response.Content | ConvertFrom-Json).access_token

# Now that we have the token, we use it to connect to the database 'mydb' on server 'myserver'
Invoke-Sqlcmd -ServerInstance myserver.database.windows.net -Database mydb -AccessToken $access_token`
              -query 'select * from Table1'
```

But the Invoke-Webrequest line is broken as the resources have now changed. It should instead read:
```
Import-Module SQLServer

# Note: the sample assumes that you or your DBA configured the server to accept connections using
#       that VM Identity you are running on and has granted it access to the database (in this 
#       example at least the SELECT permission).

### Obtain the Access Token from the Azure provider for database resources (requires az cli)
$access_token = az account get-access-token --resource https://database.windows.net/ --query accessToken -o tsv

# Now that we have the token, we use it to connect to the database 'mydb' on server 'myserver'
Invoke-Sqlcmd -ServerInstance myserver.database.windows.net -Database mydb -AccessToken $access_token`
              -query 'select * from Table1'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 697650d3-bcd4-9e48-dc8f-8dea1e9d5928
* Version Independent ID: 4281a260-7400-eec9-1a40-7f9048f389a2
* Content: [SQL Server PowerShell - SQL Server](https://docs.microsoft.com/en-us/sql/powershell/sql-server-powershell?view=sql-server-ver16&viewFallbackFrom=sqlserver-ps)
* Content Source: [docs/powershell/sql-server-powershell.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/sql-server-powershell.md)
* Product: **sql**
* Technology: **sql-server-powershell**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review this update in [private PR 88](https://github.com/MicrosoftDocs/sql-docs-powershell/pull/88).

**Comment by Matteo-T** [comment]
Can we avoid taking a HUGE dependency on "az"?

**Comment by dvasdekis** [comment]
Sure, the endpoint mentioned (169.254.169.254) flat out doesn't work on most systems, as it's an azure internal IP, but the example is meant to be general purpose.

By all means you could try to find a non-AZ alternative, but you need base credentials before you can get issued a token, which would require some encryption and key exchange before the HTTP kethod. AWS's example python to do this independent of its boto library is 30 lines long, so go for it, but at least show a working example in the interim. 

Alternatively, keep the old example for Azure VMs with the Azure services and network stack enabled (which would have az installed by default anyway), but add this as a working example for other use cases (e.g. desktops, Azure DevOps, etc.)

**Comment by Matteo-T** [comment]
To be 100% honest with you, that example was indeed written with Azure machine in mind. My own Azure machines don't have "az" preinstalled, just to give you an example.

I do like the idea of providing both examples - or maybe we could just have the two options listed in the same example - with a little comment.

What do you think of something like this?

```powershell

## Obtain access token from the machine

if (Get-Command -All az -ErrorAction SilentlyContinue -CommandType Application) {
  # Obtain the Access Token from the Azure provider for database resources (using az az cli)
  az login
  $access_token = az account get-access-token --resource https://database.windows.net/ --query accessToken -o tsv
} else {
  # az cli not around: fall back and assume this is a VM in Azure
  $response = Invoke-WebRequest `
    -Uri 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fdatabase.windows.net'`
    -Method GET`
    -Headers @{Metadata="true"}
  $access_token = ($response.Content | ConvertFrom-Json).access_token
}

# Now that we have the token, we use it to connect to the database 'mydb' on server 'myserver'
Invoke-Sqlcmd -ServerInstance myserver.database.windows.net -Database mydb -AccessToken $access_token`
              -query 'select * from Table1'
              
```

**Comment by dvasdekis** [comment]
Fantastic, thanks!

**Comment by Matteo-T** [comment]
I've given a little more thought to this today.... and setup an environment to play with it, which is already useful :)

For the scenario where we want to use a (System) Managed Identity, we have these two options, as far as I can tell:

```powershell
   # The one that uses az
   # I was missing the 2 parameters...
   az login --identity --allow-no-subscriptions
   $access_token = az account get-access-token --resource https://database.windows.net/ --query accessToken -o tsv
   <# ... #>

  # The one that uses Az.Accounts and such
  # It's definitely more idiomatic and succint compared to the REST API call 
   Add-AzAccount -identity
   $access_token = (Get-AzAccessToken -ResourceUrl 'https://database.windows.net').Token
   <# ... #>
```

Ultimately the two solutions are not all that different. I suppose we can still keep them to just show how to get the token in different ways.... no harm there.

However, if I compare Example 11 and Example 13 after this change, I see that they are pretty similar: the only difference is the -Identity passed in. So, I wonder if we really need both examples. At a minimum, I think we should call out that they are really similar and maybe swap 12 and 13, so 11 and 13 end up being close being so similar.

I'll send out a PR with the above-mentioned cleanup shortly.

**Comment by dvasdekis** [comment]
Thanks for giving this some thought. These examples are used thousands of times across the planet for every one that gets written, and most people just give up instead of writing a lengthy github issue requesting clarification, so doing this proactively (as you've done) probably saves both thousands of people, and future members of your team, a bunch of time. Much appreciated!
