### ISSUE TITLE
how to update sql server license key in ubunthu

### ISSUE THREAD

**Issue by callranjithkani** [MicrosoftDocs/sql-docs#7720]
how to update sql server license key in ubunthu? I neve find any knowledge base to update license key in ubunthu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-linux-ver15&preserve-view=true)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @callranjithkani - You should be able to run `mssql-conf setup` and choose the edition of SQL Server, and then enter your product key at that time.

**Comment by callranjithkani** [comment]
But option 7 not accepting any key.

**Comment by VanMSFT** [comment]
@callranjithkani - The paid options, like option 7 does not require entering a product key. You are verifying that you have a volume license or purchased a license through an Enterprise Agreement. Option 8 is for retail purchases, and you can enter a product key.

**Comment by rwestMSFT** [comment]
@callranjithkani If you have any more questions, please feel free to reply here. In the meantime, I am closing this as resolved.

#please-close
