### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by lachaves** [MicrosoftDocs/sql-docs#7722]
The Microsoft.AzureArcData and Microsoft.HybridCompute resource providers (has) been registered.
The Microsoft.AzureArcData and Microsoft.HybridCompute resource providers have been registered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa2343e7-8920-d26c-e167-394ddb5a5878
* Version Independent ID: 159d34d5-1f2d-5028-88a6-4bf6d04f0ffd
* Content: [Connect to Azure Arc](https://docs.microsoft.com/en-us/sql/sql-server/azure-arc/connect?view=sql-server-ver16&tabs=azure%2Cwindows)
* Content Source: [docs/sql-server/azure-arc/connect.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/azure-arc/connect.md)
* Product: **sql**
* GitHub Login: @anosov1960
* Microsoft Alias: **sashan**

**Comment by WilliamAntonRohm** [comment]
@lachaves -- Luis, thank you for catching this.  I am updating the article.
