### ISSUE TITLE
 msodbcsql driver not supporting ubuntu 22.04

### ISSUE THREAD

**Issue by PradeepaB07** [MicrosoftDocs/sql-docs#7723]
Hi Team,
I have recently Installed Ubuntu 22.04.
when i tried to install the drivers msodbcsql  17 or 18, it was not supporting.
This package is not available in Ubuntu 22.04..
Will there be a  patch version released in Ubuntu to support msodbcsql .17 or 18? if so when?
Awaiting your reply.
Thank you.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08eeeaa9-2a32-4a81-149c-4c118db93bc9
* Version Independent ID: fccc0d58-6b4f-1e7c-f451-31e4ad7c0b84
* Content: [Microsoft Drivers for PHP Support Matrix - PHP drivers for SQL Server](https://docs.microsoft.com/en-us/sql/connect/php/microsoft-php-drivers-for-sql-server-support-matrix?view=sql-server-ver16#sql-server-version-certified-compatibility)
* Content Source: [docs/connect/php/microsoft-php-drivers-for-sql-server-support-matrix.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/microsoft-php-drivers-for-sql-server-support-matrix.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@PradeepaB07 -- thank you for writing.  Please see related issue #7721.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
