### ISSUE TITLE
Use of correct function name in JSON_MODIFY.

### ISSUE THREAD

**Issue by dambito** [MicrosoftDocs/sql-docs#7727]
Just a small issue, I think, that in paragraph 

```text
To avoid automatic escaping, provide newValue by using the JSON_QUERY function. JSON_MODIFY knows that the value returned by JSON_MODIFY is properly formatted JSON, so it doesn't escape the value.
```
There should be this instead: "...returned by JSON_`QUERY` is properly..." or am I wrong? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c673e1d-891c-8c83-4566-b8bc27ce139d
* Version Independent ID: 3cd2f484-3a26-5c7b-cacc-16990b0c2be0
* Content: [JSON_MODIFY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-modify-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/functions/json-modify-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/json-modify-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@dambito -- thank you for catching this.  I am updating the article.
