### ISSUE TITLE
Impovement: add note about schema name requirement

### ISSUE THREAD

**Issue by OleksiiKovalov** [MicrosoftDocs/sql-docs#7728]
Exec documentation does not contain a notion about the required schema name for a call to scalar function, it would be great to make a note here.

also, CREATE FUNCTION  (https://docs.microsoft.com/en-us/sql/t-sql/statements/create-function-transact-sql?view=sql-server-ver16) statement has such note - "Scalar functions must be invoked by using at least the two-part name of the function (<schema>.<function>)."

My suggestion:
1. Add note that the schema is required for invoking of scalar UDF
2. Add note that the schema is NOT required for invoking of table value UDF

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da647854-0134-18ae-4dfd-ad0db2aac00f
* Version Independent ID: 4c0b8962-de3c-012b-d3cc-5374014efb05
* Content: [Execute User-defined Functions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/execute-user-defined-functions?view=sql-server-ver16)
* Content Source: [docs/relational-databases/user-defined-functions/execute-user-defined-functions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/user-defined-functions/execute-user-defined-functions.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@OleksiiKovalov -- Oleksii, thank you for your close reading and suggestions.

@rwestMSFT -- Randolph, please look into this issue.

**Comment by rwestMSFT** [comment]
@OleksiiKovalov Thanks for the suggestion. We will take it into account for the next article refresh cycle. I will close this issue because I'm tracking it internally.

#please-close
