### ISSUE TITLE
Error in ALTER DATABASE syntax

### ISSUE THREAD

**Issue by DougBernhardt** [MicrosoftDocs/sql-docs#7731]
There is no "=" sign....should be 
SET SUSPEND_FOR_SNAPSHOT_BACKUP ON

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8840ba86-332c-33fc-509b-9e7e08671c7a
* Version Independent ID: 8840ba86-332c-33fc-509b-9e7e08671c7a
* Content: [Create a T-SQL Backup - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/create-a-transact-sql-snapshot-backup?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/create-a-transact-sql-snapshot-backup.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/create-a-transact-sql-snapshot-backup.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @perrysk-msft
* Microsoft Alias: **peskount**

**Comment by WilliamAntonRohm** [comment]
@DougBernhardt -- Doug, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@DougBernhardt -- Doug, I'm not finding a misplaced `=` in this article.  Please clarify your discovery.  This article may have been updated already.

**Comment by WilliamAntonRohm** [comment]
@DougBernhardt -- Doug, thank you for pointing that out for me.  I have updated the documentation and it should be live by tomorrow.
