### ISSUE TITLE
[Question] Microsoft Docs (SQL) - Regarding query for Example 1

### ISSUE THREAD

**Issue by yongshun950824** [MicrosoftDocs/sql-docs#7736]
From this [Example][1]

```SQL
SELECT FirstName, LastName,
 JSON_VALUE(jsonInfo,'$.info.address[0].town') AS Town
FROM Person.Person
WHERE JSON_VALUE(jsonInfo,'$.info.address[0].state') LIKE 'US%'
ORDER BY JSON_VALUE(jsonInfo,'$.info.address[0].town')
```

**Question: Is the `jsonInfo` value is based from [here][2]?**

```SQL
SET @jsonInfo=N'{  
     "info":{    
       "type":1,  
       "address":{    
         "town":"Bristol",  
         "county":"Avon",  
         "country":"England"  
       },  
       "tags":["Sport", "Water polo"]  
    },  
    "type":"Basic"  
 }'  
```

---

**If yes**, I think the above query was wrong as `info.address` is an object but not an array. So the query should be:

```SQL
SELECT FirstName, LastName,
 JSON_VALUE(jsonInfo,'$.info.address.town') AS Town
FROM Person.Person
WHERE JSON_VALUE(jsonInfo,'$.info.address.state') LIKE 'US%'
ORDER BY JSON_VALUE(jsonInfo,'$.info.address.town')
```

The provided sample in the table (Row 3) mentions that to retrieve the town value:

| Path | Return value in lax mode | Return value in strict mode |
|-|-|-|
| $.info.address.town | N'Bristol' | N'Bristol' |

And also

| Path | Return value in lax mode | Return value in strict mode | More info |
|-|-|-|-|
| $.info.type[0] | NULL | Error | Not an array. |

From here mentioned that access to an object with indexer will lead to error as it is not an array.

[1]: https://docs.microsoft.com/en-us/sql/t-sql/functions/json-value-transact-sql?view=sql-server-ver16#example-1
[2]: https://docs.microsoft.com/en-us/sql/t-sql/functions/json-value-transact-sql?view=sql-server-ver16#lax-mode-and-strict-mode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28e8713d-8b6e-7e43-04cc-e2720891b56c
* Version Independent ID: d09b9ed6-4e55-7d18-b17f-88e17839074d
* Content: [JSON_VALUE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-value-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/functions/json-value-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/json-value-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@yongshun950824 -- thank you for catching this.  I am updating the article.
