### ISSUE TITLE
there is typo in korean translated version.

### ISSUE THREAD

**Issue by Park-minkyu** [MicrosoftDocs/sql-docs#7739]
hello I found small typo which is really bothering some of us......
Please check the below..
below is just a single sample, there are lot more backslash typos in korean translated page.

as-is:
4\\\.1의 새로운 기능

to-is:
4.1의 새로운 기능

Thank You!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c88ed436-3315-c7c4-8536-62396c0a2525
* Version Independent ID: 1126c22e-62b7-da3a-fb31-b367dc7f3414
* Content: [Introduction to Microsoft.Data.SqlClient namespace - ADO.NET Provider for SQL Server](https://docs.microsoft.com/en-us/sql/connect/ado-net/introduction-microsoft-data-sqlclient-namespace?view=sql-server-ver16)
* Content Source: [docs/connect/ado-net/introduction-microsoft-data-sqlclient-namespace.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/ado-net/introduction-microsoft-data-sqlclient-namespace.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@Park-minkyu -- Minkyu, thank you for your feedback.  I will send this issue on to the localization team here.

**Comment by WilliamAntonRohm** [comment]
@Park-minkyu -- Minkyu, I have created a [new localization work item](https://ceapex.visualstudio.com/CEINTL/_workitems/edit/687507) for this issue.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
