### ISSUE TITLE
No useful content in this page

### ISSUE THREAD

**Issue by mrdenny** [MicrosoftDocs/sql-docs#7748]
It would appear that something went  wrong with this page, as there is no useful content here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ac2fe2-31da-7db6-2d5f-5091022f41d2
* Version Independent ID: bbf07c2c-7006-7b94-f12f-800fa7bc67e4
* Content: [CREATE EXTERNAL TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-table-transact-sql?view=azuresqldb-mi-current&tabs=dedicated)
* Content Source: [docs/t-sql/statements/create-external-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @mrdenny for pointing this out. [Data virtualization for SQL MI is still in preview](https://docs.microsoft.com/azure/azure-sql/managed-instance/data-virtualization-overview) and this doc is on the way. Thanks again for taking the time to create this GitHub issue, your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
@mrdenny Happy to announce that the data virtualization feature for SQL MI has been announced and this reference page has been updated for SQL MI-specific content.
