### ISSUE TITLE
Invalid examples for OPENROWSET

### ISSUE THREAD

**Issue by mrdenny** [MicrosoftDocs/sql-docs#7749]
Most of these examples are invalid as they point to local drive paths.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbec06eb-2341-9186-a24f-adc129642169
* Version Independent ID: d32aa975-1187-ede1-e775-a590c0dba458
* Content: [OPENROWSET (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/openrowset-transact-sql?view=azuresqldb-mi-current)
* Content Source: [docs/t-sql/functions/openrowset-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/openrowset-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rwestMSFT** [comment]
Hey Denny, do you mind providing a couple of examples for non-local paths? That'll help get this resolved.

**Comment by mrdenny** [comment]
Honestly I'd probably just pull out the examples that are using local paths. I'm not sure if you can pull in data from Access or Excel on an MI anyway.

Thank You,
Denny Cherry
Owner & Principal Consultant
Denny Cherry & Associates Consulting, an Inc. 5000 company
***@***.******@***.***>
(o) +1 (323) 686-1478<tel:3236861478> | (d) +1 (213) 973-3669<tel:2139733669>
Online Calendar ***@***.***/bookings/>
[Logo, company name  Description automatically generated]<http://www.dcac.co/>
***@***.***
[A picture containing text  Description automatically generated]
[A blue sign with white text  Description automatically generated with low confidence]

**Comment by rwestMSFT** [comment]
#assign:@MikeRayMSFT

**Comment by MikeRayMSFT** [comment]
Thanks @mrdenny - reviewing

**Comment by MikeRayMSFT** [comment]
Updated assignees (@nzagorac-ms, @WilliamDAssafMSFT).

**Comment by WilliamDAssafMSFT** [comment]
This issue has been addressed in an doc update in flight, and remains in discussion. Thanks for bringing attention to it, @mrdenny .
