### ISSUE TITLE
What are the dashes after SELECT clauses in the code samples?

### ISSUE THREAD

**Issue by BurstX** [MicrosoftDocs/sql-docs#7750]
For example, [here](https://docs.microsoft.com/en-us/sql/relational-databases/query-processing-architecture-guide?view=sql-server-ver15#parameters-and-execution-plan-reuse) I see:
```sql
SELECT - -- <<<==== this dash character is what I mean
FROM AdventureWorks2014.Production.Product 
WHERE ProductSubcategoryID = 1;
```
![image](https://user-images.githubusercontent.com/3790231/176623989-4ffe32d8-098a-4fe7-805b-10d570397625.png)

Why not `SELECT *` ? The code sample is not executable after simple copying it to the IDE. Is it intentional? Then what is the purpose? I could not find any explanation in the community resources and in MSdocs site itself, sorry.

The only reason coming across my mind is `SELECT *` can consume too much resources in some cases (depening on the query), but it seems to me that every single code sample has the dash kind (`SELECT - ...`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45a7c96a-9d41-83e8-0ae8-b73fff390f48
* Version Independent ID: 1a880308-6a3b-6944-6428-1331801b327a
* Content: [Query Processing Architecture Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/query-processing-architecture-guide?view=sql-server-ver15#caching-multiple-plans-for-the-same-query)
* Content Source: [docs/relational-databases/query-processing-architecture-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/query-processing-architecture-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @akatesmith
* Microsoft Alias: **katsmith**

**Comment by rwestMSFT** [comment]
An article refresh will be making its way out today or tomorrow with corrections. Thanks again, @BurstX.
