### ISSUE TITLE
Less than greater than syntax is rendering with escaped XML codes rather than characters in the 'Recommended Content'

### ISSUE THREAD

**Issue by drskev** [MicrosoftDocs/sql-docs#7752]
The Recommended content list contains a link for the 'traditional' not equal consisting of the lessthan greater than characters. However, the characters themselves are replaced instead with their escaped XML equivalents of `&lt;&gt;` in the title of the link. 

Looking at some of the other links to pages such as not less than, I see it is doing the same. Is this fixable or an unfortunate quirk of how the page content is transformed to HTML?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c47a45c5-bade-23ad-4eea-c9bba719ea83
* Version Independent ID: d31b0fce-bd6b-2413-ac0b-243e750cde19
* Content: [!= (Not Equal To) (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/not-equal-to-transact-sql-exclamation?view=sql-server-2017)
* Content Source: [docs/t-sql/language-elements/not-equal-to-transact-sql-exclamation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/not-equal-to-transact-sql-exclamation.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@drskev Recommended content is unfortunately out of the content team's control. I'm going to ping @WilliamAntonRohm to see if he can escalate to the engineering team.

**Comment by rwestMSFT** [comment]
#assign:@WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
@drskev -- thank you for catching these.

@rwestMSFT -- I am looking into this issue.

**Comment by rwestMSFT** [comment]
I'm marking this as closed because it isn't a Docs content issue. We are tracking it internally. Thanks again for the feedback, @drskev.

**Comment by rwestMSFT** [comment]
#please-close
