### ISSUE TITLE
SQL Server Import and Export Wizard hide controls when scroll mouse

### ISSUE THREAD

**Issue by rambmario** [MicrosoftDocs/sql-docs#7755]
In SQL Server 2019 Import and Export Wizard Data (64bit) lost controls when you fast scroll mouse in combo focused, also other options disappear too.

<img width="480" alt="sql01" src="https://user-images.githubusercontent.com/33069691/176870842-f2113b7f-970d-404b-a8ec-2073400f473b.PNG">

<img width="477" alt="sql02" src="https://user-images.githubusercontent.com/33069691/176870905-8871b26d-0ee9-4b2d-8cb4-167a2cd47d99.PNG">
<img width="477" alt="sql03" src="https://user-images.githubusercontent.com/33069691/176870917-fbf8cd3c-8027-4949-8210-70470b0856df.PNG">

**Comment by WilliamAntonRohm** [comment]
@rambmario -- Mario, thank you for your feedback.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
