### ISSUE TITLE
Add code fence for partial result set

### ISSUE THREAD

**Issue by jslatane** [MicrosoftDocs/sql-docs#7757]
Please add the markdown code fence for the partial result set under the Basic Syntax Example section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7788150-0996-387b-c565-b752b7609820
* Version Independent ID: 3790de35-d533-dc61-cd1c-66c22c3aefd0
* Content: [PERCENTILE_DISC (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/percentile-disc-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/functions/percentile-disc-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/percentile-disc-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@jslatane -- thank you for your contribution!
