### ISSUE TITLE
Need to update connect example

### ISSUE THREAD

**Issue by lbilodeau** [MicrosoftDocs/sql-docs#7761]
Someone needs to update the connect strings driver to the current version of the MS-SQL drivers, otherwise you might get this error on connection:

'(\'01000\', "[01000] [unixODBC][Driver Manager]Can\'t open lib \'ODBC Driver 17 for SQL Server\' : file not found (0) (SQLDriverConnect)")'

For my installation I ended up with MSSQL drivers for version 18.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95454cf7-3691-e4eb-d8c6-b7986fcd490b
* Version Independent ID: 84a42231-fc84-e831-a9a8-18cb86f3cfb9
* Content: [Step 1: Configure pyodbc Python environment - Python driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/python/pyodbc/step-1-configure-development-environment-for-pyodbc-python-development?view=sql-server-ver16)
* Content Source: [docs/connect/python/pyodbc/step-1-configure-development-environment-for-pyodbc-python-development.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/python/pyodbc/step-1-configure-development-environment-for-pyodbc-python-development.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@lbilodeau -- El Bilo, thank you for your feedback.

@David-Engel -- David, please look into this potential documentation issue.

**Comment by David-Engel** [comment]
Done. The change should be reflected after tomorrow's site publish.

#please-close

**Comment by wb2712** [comment]
Need to update connect example  
https://learn.microsoft.com/en-us/sql/connect/odbc/cpp-code-example-app-connect-access-sql-db?view=sql-server-ver16

ubuntu 22.04  
Using the same connection parameters, `freetds-dev` with `pyodbc` can successfully connect, but when using `unixODBC`, it continuously returns -2 without any error messages.
