### ISSUE TITLE
Typos in document

### ISSUE THREAD

**Issue by DavidKlempfner** [MicrosoftDocs/sql-docs#7762]
Feedback for:
https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server?view=sql-server-ver16

"specified by the flexible failover policyof the availability group." - A space needs to be inserted between "policy" and "of".

"you will need to create an availability group listener the availability group and update your applications to use the network name of the listener." - "availability group listener the availability group" doesn't make any sense, maybe "availability group listener **for** the availability group"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c5b4585-159a-6472-140f-8e9439222ab7
* Version Independent ID: 03a14cb4-5589-1156-5a4e-938665968ebb
* Content: [What is an Always On availability group? - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server?view=sql-server-ver16)
* Content Source: [docs/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by rwestMSFT** [comment]
Thanks @DavidKlempfner, I'll handle this.

**Comment by rwestMSFT** [comment]
The fixes have been merged, and will reflect later today or tomorrow morning. Thanks again for identifying this issue.
