### ISSUE TITLE
Domain Independent Availability Group - SQL Server

### ISSUE THREAD

**Issue by alpacino12** [MicrosoftDocs/sql-docs#7763]
I'm to trying create a Domain Independent Always on availability group using the documentation

https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/domain-independent-availability-groups?view=sql-server-ver15

The documentation says -Using the instructions at this link, deploy a Workgroup Cluster composed of all servers that will participate in the availability group-

I have followed the prerequisites in the documentation and created two vm's having sql installed with dns suffix .

While I try to create a Workgroup Cluster using PowerShell on one machine , it keeps giving

'Administrative privileges not present on other machine '

though I have created a user under administrative group on both machines

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1b8751e-c59a-edd0-9c6d-1fde427d1945
* Version Independent ID: 9e48f7cb-7a85-ee36-81c2-590bb01ddb79
* Content: [SQL Server help and feedback - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017)
* Content Source: [docs/sql-server/sql-server-get-help.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/sql-server-get-help.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rwestMSFT** [comment]
Hi @alpacino12, I would strongly encourage you to open a support call. If I were to hazard a guess, this is a DNS issue, but short of that, your best bet is talking to Microsoft Support.

**Comment by WilliamAntonRohm** [comment]
@alpacino12 -- thank you for your feedback.

@rwestMSFT -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
