### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by jrmclennan** [MicrosoftDocs/sql-docs#7773]
Dead links are in the Windows Permission section: https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server?view=sql-server-ver16#WinPermissions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b679be86-06b0-b425-cd4f-d7b3ea104693
* Version Independent ID: aec2cf5b-5bf9-647e-6b0f-9fab6fca3a79
* Content: [Configure availability group listener - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server?view=sql-server-ver16#feedback)
* Content Source: [docs/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@jrmclennan -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
