### ISSUE TITLE
DBCC STACKDUMP is missing from the list of DBCC commands

### ISSUE THREAD

**Issue by emad-almousa** [MicrosoftDocs/sql-docs#7778]
Hi,

DBCC STACKDUMP is missing from the list of DBCC commands. DBCC STACKDUMP was introduced in SQL Server 2019....referenced in another MSSQL DOC: https://docs.microsoft.com/en-us/troubleshoot/sql/tools/use-sqldumper-generate-dump-file#extended-dbcc-stackdump-functionality-introduced-in-sql-server-2019

Regards,
Emad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 369bcc0e-60fd-20b9-9468-d31d0567d98d
* Version Independent ID: ee7eddca-2195-7ca7-02a4-061164aca845
* Content: [DBCC (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/database-console-commands/dbcc-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/database-console-commands/dbcc-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **umajay**

**Comment by rwestMSFT** [comment]
Hi @emad-almousa, thank you for your feedback. There are several undocumented DBCC commands in SQL Server, including this one. Given that it relates specifically to troubleshooting with CSS, it is unlikely that this will be documented elsewhere. If that changes, I will update this issue. In the meantime, I am closing it.

#please-close
