### ISSUE TITLE
setspn -S instead of setspn -A

### ISSUE THREAD

**Issue by halinegv** [MicrosoftDocs/sql-docs#7780]
[Enter feedback here]

Hello, it would be possible to make a change on the section "Manual SPN Registration"
Suggested change:
From: SETSPN - A 
To: SETSPN -S
That would avoid to create duplicated SPNs

Thanks a lot,
Haline
Microsoft alias: havicente
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16136000-fc6d-9156-499a-c45bde264bc4
* Version Independent ID: ea9aacfc-8f27-563f-08c8-77ac4e941cff
* Content: [Register a Service Principal Name for Kerberos Connections - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections?view=sql-server-ver16#automatic-spn-registration)
* Content Source: [docs/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@halinegv -- Haline, thank you for your suggestion.  I am updating the article.

**Comment by halinegv** [comment]
Thanks a lot!!!
