### ISSUE TITLE
"All SQL" no longer available

### ISSUE THREAD

**Issue by Yanis77240** [MicrosoftDocs/sql-docs#7786]
Selecting **All SQL > Hide nothing** is no longer available in the version filter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 707f60c5-6dee-8cf3-4f1f-49ad87b9337b
* Version Independent ID: 9f4ce234-fe5b-03d0-3dd1-4a2790c09674
* Content: [SQL Server docs navigation tips - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/sql-docs-navigation-guide?view=sql-server-ver15)
* Content Source: [docs/sql-server/sql-docs-navigation-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/sql-docs-navigation-guide.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@Yanis77240 -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
