### ISSUE TITLE
UNMASK permission in not working at Schema, Table and Column level

### ISSUE THREAD

**Issue by mnagineni85** [MicrosoftDocs/sql-docs#7787]
Team,

As per the document/help under section **Grant different UNMASK permissions to users**, it is mentioned that we can provide **UNMASK** permissions at Column, Table, and Schema levels. But, none of them are working.

When I run the below query, it is giving error **Incorrect syntax near 'UNMASK'.**

GRANT UNMASK ON Data.Membership(FirstName) TO ServiceAttendant; 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9408bf-18b5-339f-cd25-6a3024be3243
* Version Independent ID: eea4b8dc-5598-b7e6-e01a-902d5ca1f96d
* Content: [Dynamic Data Masking - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/dynamic-data-masking?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/dynamic-data-masking.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/dynamic-data-masking.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @mnagineni85 - Are you using SQL Server 2022? This granularity was introduced in SQL Server 2022, so it will not work on any version below this.

https://docs.microsoft.com/en-us/sql/relational-databases/security/dynamic-data-masking?view=sql-server-ver15#granular

**Comment by rwestMSFT** [comment]
Since we haven't heard back from you, @mnagineni85, I'm closing this issue. Please feel free to respond in the comments if your circumstances change.
