### ISSUE TITLE
Error in C# code

### ISSUE THREAD

**Issue by ch0kai** [MicrosoftDocs/sql-docs#7791]
Line : 
`db = srv.Databases("AdventureWorks2012");  `

should be  :
`db = srv.Databases["AdventureWorks2012"];  `

Databases is collection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 014c3dc8-52ac-9c5e-4822-45e628174260
* Version Independent ID: 152141e7-00a7-93b0-b520-312e2eca1885
* Content: [Setting Properties - SMO - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/create-program/setting-properties-smo?view=sql-server-2017)
* Content Source: [docs/relational-databases/server-management-objects-smo/create-program/setting-properties-smo.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/server-management-objects-smo/create-program/setting-properties-smo.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
