### ISSUE TITLE
Free version - others link broken

### ISSUE THREAD

**Issue by byroniac** [MicrosoftDocs/sql-docs#7792]
The "Free version - others" link is broken which originally pointed to https://www.microsoft.com/evalcenter/evaluate-sql-server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae75dfb-2017-17a3-835b-9409fdb06427
* Version Independent ID: 8f22b559-823e-d719-7c5d-f76f89345c01
* Content: [SQL Server installation guide - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server?view=sql-server-ver16)
* Content Source: [docs/database-engine/install-windows/install-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/install-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@byroniac -- Byron, thank you for your feedback.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
