### ISSUE TITLE
Duplicate line of code

### ISSUE THREAD

**Issue by benny779** [MicrosoftDocs/sql-docs#7796]
There is duplication [here](https://docs.microsoft.com/en-us/sql/connect/ado-net/step-4-connect-resiliently-sql-ado-net?view=sql-server-ver16#:~:text=sqlConnectionSB.IntegratedSecurity%20%3D,IntegratedSecurity%20%3D%20false%3B). (open in a new tab to see highlight)

Line ```sqlConnectionSB.IntegratedSecurity = false;``` appears twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa5d294-2da9-2938-794d-207704e1625f
* Version Independent ID: ab9a3ba2-4b76-0311-5e89-5339991c5ec7
* Content: [Step 4: Connect resiliently to SQL with ADO.NET - ADO.NET Provider for SQL Server](https://docs.microsoft.com/en-us/sql/connect/ado-net/step-4-connect-resiliently-sql-ado-net?view=sql-server-ver16)
* Content Source: [docs/connect/ado-net/step-4-connect-resiliently-sql-ado-net.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/ado-net/step-4-connect-resiliently-sql-ado-net.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
