### ISSUE TITLE
Confusing or incorrect documentation for nchar, nvarchar and xml related to unicode compression.

### ISSUE THREAD

**Issue by justinharrell** [MicrosoftDocs/sql-docs#7800]
Documentation states: 

nchar | Yes | Trailing padding characters are removed. Note that the Database Engine inserts the same padding character regardless of the collation that is used.

nvarchar | No | No effect.

xml | No | No effect.

However the Unicode Compression Implementation documentation states it is enabled by row compression or page compression and effects the storage of nchar and nvarchar types. I also believe the xml type is compressed via unicode compression and that is not mentioned anywhere except the main data compression page when describing how no compression is applied to values larger than 8060 bytes.

Its seem strange to not mention unicode compression here and even inaccurate to say nvarchar has no compression when row compression is enabled. This was only true before SQL 2008 R2 I believe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92817093-2e91-eb90-6536-a64e4ece6562
* Version Independent ID: afc320b0-6709-6fe9-1d59-b446bee73675
* Content: [Row Compression Implementation - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-compression/row-compression-implementation?view=sql-server-ver16)
* Content Source: [docs/relational-databases/data-compression/row-compression-implementation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-compression/row-compression-implementation.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by rwestMSFT** [comment]
#reassign:@rwestMSFT

**Comment by rwestMSFT** [comment]
@justinharrell Thanks, we'll look into this.

**Comment by rwestMSFT** [comment]
@justinharrell I'm updating this thread to let you know I'm closing this issue because we're tracking it internally. Once we have an update, I'll leave a comment here.

Thanks again for your feedback.

#please-close

**Comment by rwestMSFT** [comment]
AB#70883

**Comment by rwestMSFT** [comment]
@justinharrell As promised, I'm adding footnotes to the three data types you queried, using content from the Unicode and general compression articles as you cited.

The reason I won't be changing the `No` to `Yes` for the Unicode types is that compression may not occur for non-Latin alphabets, and "maybe" isn't a good text value for that column.

Thank you for your patience. Hopefully, this change (which you should see live early next week) reduces the confusion.
