### ISSUE TITLE
Syntax for DATE_BUCKET: origin should be optional

### ISSUE THREAD

**Issue by rsocol** [MicrosoftDocs/sql-docs#7805]
The Syntax section should be updated to clarify that the origin parameter is optional. It already says so in the first paragraph of the article (and in the Arguments section), but the Syntax section should specify this parameter between square brackets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a3bf44-c67c-9cf0-ba4f-442ad6eb814e
* Version Independent ID: 44a3bf44-c67c-9cf0-ba4f-442ad6eb814e
* Content: [DATE_BUCKET (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/date-bucket-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/functions/date-bucket-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/date-bucket-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @kendalvandyke
* Microsoft Alias: **kendalv**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
