### ISSUE TITLE
Mistake in Result Set from Example A

### ISSUE THREAD

**Issue by JJWilber** [MicrosoftDocs/sql-docs#7806]
The code for example A says "Product Name" for the field header, but the result set shows "Company Name".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 854b2781-0175-536c-83ad-2a439f417134
* Version Independent ID: c84fee2c-902b-6f1f-6c8f-ea01bd993e6a
* Content: [SELECT @local_variable (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/select-local-variable-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/language-elements/select-local-variable-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/select-local-variable-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@JJWilber Good catch, thanks! I'll have this fixed shortly.
