### ISSUE TITLE
Code sample not working

### ISSUE THREAD

**Issue by brentleslie** [MicrosoftDocs/sql-docs#7809]
I attempted to run the code sample provided on the page and replicated below on an Azure SQL database:

DECLARE @array VARCHAR(MAX);
SET @array = '[{"month":"Jan", "temp":10},{"month":"Feb", "temp":12},{"month":"Mar", "temp":15},
               {"month":"Apr", "temp":17},{"month":"May", "temp":23},{"month":"Jun", "temp":27}
              ]';

SELECT * FROM OPENJSON(@array)
        WITH (  month VARCHAR(3),
                temp int,
                month_id tinyint '$.sql:identity()') as months

Received the following message:

Msg 13607, Level 16, State 4, Line 33
JSON path is not properly formatted. Unexpected character ':' is found at position 5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e25eda30-d6e4-600c-ed9d-4f0a53ee1058
* Version Independent ID: 9b53b7d7-b827-6f7f-c0c9-84645742d6a2
* Content: [OPENJSON (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/openjson-transact-sql?view=azuresqldb-current)
* Content Source: [docs/t-sql/functions/openjson-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/openjson-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by rwestMSFT** [comment]
Hi @brentleslie, thanks for your feedback.

As the article states:

> The identity is available only in the serverless SQL pool in Synapse Analytics.

In other words, you cannot use `sql.identity()` on SQL Server, Azure SQL Database, or Azure SQL Managed Instance. The query works as expected if you remove that directive.

If you have any other questions, please feel free to respond in the comments below. I'm closing this issue in the meantime.

#please-close
