### ISSUE TITLE
Line 91 selects @dbname rather than DbName

### ISSUE THREAD

**Issue by mdthuleen** [MicrosoftDocs/sql-docs#7810]
The select should be:
DECLARE no_truncate_db CURSOR FOR
    SELECT log_reuse_wait, log_reuse_wait_desc, DbName, database_id, recovery_model_desc FROM #CannotTruncateLog_Db;

rather than:
DECLARE no_truncate_db CURSOR FOR
    SELECT log_reuse_wait, log_reuse_wait_desc, @dbname, database_id, recovery_model_desc FROM #CannotTruncateLog_Db;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f3c1175-cf53-423b-b7b4-d68b58b5bf22
* Version Independent ID: 04c9e403-be61-9b41-b9af-dd88d0a31d40
* Content: [Troubleshoot full transaction log error 9002 - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/logs/troubleshoot-a-full-transaction-log-sql-server-error-9002?view=sql-server-ver16)
* Content Source: [docs/relational-databases/logs/troubleshoot-a-full-transaction-log-sql-server-error-9002.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/logs/troubleshoot-a-full-transaction-log-sql-server-error-9002.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@mdthuleen -- Mike, thank you for catching this. I am updating the article.
