### ISSUE TITLE
DBCC UPDATEUSAGE - best practices

### ISSUE THREAD

**Issue by LonnyNiederstadt** [MicrosoftDocs/sql-docs#7813]
[Enter feedback here]
In the second sentence of the following paragraph from "Best Practices", the bolded fragment can be made much more clear.

Do not run DBCC UPDATEUSAGE routinely. Because DBCC UPDATEUSAGE can take some time to run on large tables or databases, **it should not be used only unless you suspect incorrect values** are being returned by sp_spaceused.

For example:
Routine use of DBCC UPDATEUSAGE should not be necessary, as SQL Server will properly maintain the metadata under most circumstances. It is appropriate to use DBCC UPDATEUSAGE on an occasional basis, such as when you suspect incorrect values are being returned by sp_spaceused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fab3e01-f317-6e83-9081-73f69d2a8b50
* Version Independent ID: d9625c39-cacd-c36a-e545-edd5402950bf
* Content: [DBCC UPDATEUSAGE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-updateusage-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/database-console-commands/dbcc-updateusage-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/database-console-commands/dbcc-updateusage-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **umajay**

**Comment by WilliamAntonRohm** [comment]
@LonnyNiederstadt -- Lonny, thank you for your suggestion.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
