### ISSUE TITLE
Indirect checkpoints - Advantages lists a disadvantage

### ISSUE THREAD

**Issue by jpomfret** [MicrosoftDocs/sql-docs#7841]
This section of the docs are not very clear. It first states `Indirect checkpoints offer the following advantages:` and then lists `An online transactional workload on a database configured for indirect checkpoints can experience performance degradation`. 

> # Indirect checkpoints
> Indirect checkpoints, introduced in SQL Server 2012 (11.x), provide a configurable database-level alternative to automatic checkpoints. This can be configured by specifying the target recovery time database configuration option. For more information, see [Change the Target Recovery Time of a Database (SQL Server)](https://docs.microsoft.com/en-us/sql/relational-databases/logs/change-the-target-recovery-time-of-a-database-sql-server?view=sql-server-ver16). In the event of a system crash, indirect checkpoints provide potentially faster, more predictable recovery time than automatic checkpoints. Indirect checkpoints offer the following advantages:
> 
> An online transactional workload on a database configured for indirect checkpoints can experience performance degradation. Indirect checkpoints ensure that the number of dirty pages are below a certain threshold so the database recovery completes within the target recovery time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bca058-bde3-c76a-793a-dc344751d853
* Version Independent ID: 1f682f41-3a2d-66d6-47f1-bd5c2b4ca873
* Content: [Database Checkpoints (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/logs/database-checkpoints-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/logs/database-checkpoints-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/logs/database-checkpoints-sql-server.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by rwestMSFT** [comment]
#reassign:rwestMSFT

**Comment by rwestMSFT** [comment]
@jpomfret Thanks so much for your feedback. You'll see an updated version of this article in the next day or so.

**Comment by jpomfret** [comment]
Thanks @rwestMSFT! I had a feeling you might be the one to fix this 🙂 Appreciate it!
