### ISSUE TITLE
Please correct the options-for-encryption-and-compression sample

### ISSUE THREAD

**Issue by pradm** [MicrosoftDocs/sql-docs#7850]
https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url-s3-compatible-object-storage?view=sql-server-ver16#options-for-encryption-and-compression

The Syntax is incorrect in the sample it has an extra "," which is not needed and executing the statement fails.

-- Backup database
BACKUP DATABASE AdventureWorks2019
TO URL = 's3://10.171.188.41:9000/sqlcssbk1/AdventureWorks2019_Encrypt.bak',
WITH FORMAT, MAXTRANSFERSIZE = 20971520, COMPRESSION,
ENCRYPTION (ALGORITHM = AES_256, SERVER CERTIFICATE = AdventureWorks2019Cert)
GO

-- Backup database
BACKUP DATABASE AdventureWorks2019
TO URL = 's3://10.171.188.41:9000/sqlcssbk1/AdventureWorks2019_Encrypt.bak'
WITH FORMAT, MAXTRANSFERSIZE = 20971520, COMPRESSION,
ENCRYPTION (ALGORITHM = AES_256, SERVER CERTIFICATE = AdventureWorks2019Cert)
GO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb0792d-9a47-6a41-4e6b-700798775797
* Version Independent ID: 3cb0792d-9a47-6a41-4e6b-700798775797
* Content: [SQL Server backup to URL for S3-compatible object storage - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url-s3-compatible-object-storage?view=sql-server-ver16#part-numbers-and-file-size-limitations)
* Content Source: [docs/relational-databases/backup-restore/sql-server-backup-to-url-s3-compatible-object-storage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/sql-server-backup-to-url-s3-compatible-object-storage.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @pradm. Good catch. This doc update is in flight and should be live later today.
