### ISSUE TITLE
Connect to Localhost sample code no longer works due to SSL by default in JDBC 10.2 driver

### ISSUE THREAD

**Issue by alexanderankin** [MicrosoftDocs/sql-docs#7853]
This section - https://docs.microsoft.com/en-us/sql/connect/jdbc/using-the-jdbc-driver?view=sql-server-ver16#make-a-simple-connection-to-a-database - contains the following outdated sample code:

```java
String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=AdventureWorks;user=MyUserName;password=*****;";  
Connection con = DriverManager.getConnection(connectionUrl);
```

it should specify that the connection is not SSL encrypted, since this is now the default as of this breaking change - https://docs.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver16#changes-in-102 (released a couple months ago in may of this year)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a02a21f-988a-217b-6ca4-4771fc2da991
* Version Independent ID: bc164fc2-8268-13a5-d22a-872e1a79c03c
* Content: [Using the JDBC driver - JDBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-the-jdbc-driver?view=sql-server-ver16#make-a-simple-connection-to-a-database)
* Content Source: [docs/connect/jdbc/using-the-jdbc-driver.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/using-the-jdbc-driver.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by alexanderankin** [comment]
This string should have `encrypt=false;` somewhere in it (https://stackoverflow.com/a/73102825)

https://github.com/MicrosoftDocs/sql-docs/blob/b9bc98299500f3d3d1a28de0db3ce09b4cdcbd7b/docs/connect/jdbc/using-the-jdbc-driver.md?plain=1#L349-L352

**Comment by WilliamAntonRohm** [comment]
@alexanderankin -- David, thank you for your clear feedback.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@David-Engel -- David, please review this update in [private PR 23453](https://github.com/MicrosoftDocs/sql-docs-pr/pull/23453).

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
