### ISSUE TITLE
Korean Localization has critical typo problem

### ISSUE THREAD

**Issue by Park-minkyu** [MicrosoftDocs/sql-docs#7854]
[Enter feedback here]

Hello, There!

I Found critical type problem of this documents.
Please check the below,

English -
  You change the primary replica or the secondary replica to **_asynchronous-commit availability mode_**. 

Korean - 
  주 복제본 또는 보조 복제본을 **_동기-커밋 가용성 모드_**로 변경합니다. 

which means totally opposite way.
Can we check it to localization team?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92080b07-0409-3acc-3514-7c2ec49f720e
* Version Independent ID: a848a4fb-ea37-2caf-1e10-ab1fce32ecd7
* Content: [Availability modes for an availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/availability-modes-always-on-availability-groups?view=sql-server-ver16)
* Content Source: [docs/database-engine/availability-groups/windows/availability-modes-always-on-availability-groups.md] (https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/availability-modes-always-on-availability-groups.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@Park-minkyu -- Minkyu, thank you for catching this.  I am creating a translation update request.

**Comment by WilliamAntonRohm** [comment]
@Park-minkyu -- Minkyu, I have created a [new localization work item](https://ceapex.visualstudio.com/CEINTL/_workitems/edit/687509/) for this issue.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by Park-minkyu** [comment]
@WilliamAntonRohm 
I understood what new localization work item beginning as fixing is on-process and I don't have privileges for that link. I can wait!

Can I have any notice if fixing is finished?

**Comment by WilliamAntonRohm** [comment]
@Park-minkyu -- Minkyu, I will get a notification when the work item is complete, and will post that here.

**Comment by Park-minkyu** [comment]
@WilliamAntonRohm I found no modification at this point.

**Comment by Park-minkyu** [comment]
@WilliamAntonRohm 
Here is the typo I mentioned which has totally opposite meaning
asynchronous (ENG) --> 비-동기 (KOR)
synchronous (ENG) --> 동기 (KOR)

**Comment by WilliamAntonRohm** [comment]
@Park-minkyu -- Minkyu, thank you for your follow-up.  The translation has been revised and will be up on the live site in a few days.  Please let me know if you don't see it by then.

**Comment by Park-minkyu** [comment]
@WilliamAntonRohm I confirmed it and now everything is on site! Thank you!
