### ISSUE TITLE
Incorrect: column_alias = expression   

### ISSUE THREAD

**Issue by OleksiiKovalov** [MicrosoftDocs/sql-docs#7855]
Looks like "column_alias = expression   " part of "column_specifier" is incorrect  - sql server 2019 does not accept this syntax - and SSMS 18.11.1 shows syntax error
![image](https://user-images.githubusercontent.com/26844170/180732341-62de39bd-b53b-4750-9cb1-116aa85d95f9.png)

@@version Microsoft SQL Server 2019 (RTM-CU16) (KB5011644) - 15.0.4223.1 (X64) 

![image](https://user-images.githubusercontent.com/26844170/180731426-1138f9a6-c62c-47b9-b011-fae3c90f7bc3.png)

![image](https://user-images.githubusercontent.com/26844170/180735973-0ec43103-ea75-4e80-bd4c-2752cd46ed65.png)

`select @@version
go

drop queue ExpenseQueue
go

create queue ExpenseQueue;
go

RECEIVE column_alias = message_type_name
FROM ExpenseQueue ;  
go

RECEIVE  message_type_name as column_alias
FROM ExpenseQueue ;  
go

`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31ea70de-a80a-21db-12a0-6c502a2f4696
* Version Independent ID: 99a91d24-fb71-44b0-24d5-8b61fe9eebd3
* Content: [RECEIVE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/receive-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/receive-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/receive-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @OleksiiKovalov for contacting Microsoft with feedback about our product documentation. It could take from a few business days to a few weeks to confirm this with the product team and address. This is very well documented, and I appreciate the time it took. We'll contact you if we need further information, and you'll receive an email message each time we mention you in a comment. 
	
Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
Thanks again @OleksiiKovalov for contacting Microsoft with feedback about our product documentation. An update has been published. Good catch! Your suggestions help improve our documentation.
