### ISSUE TITLE
Improve examples A and B on STRING_AGG page

### ISSUE THREAD

**Issue by mjswart-d2l** [MicrosoftDocs/sql-docs#7859]
The examples A and B talk about the behavior of STRING_AGG when a value is NULL. 
It would be better to use another column other than FirstName in Person.Person in AdventureWorks since FirstName does not allow nulls and the behavior under discussion is not illustrated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8471b5d7-c6c9-c158-c57e-341683a0fc36
* Version Independent ID: 50e18725-91d2-21b7-864e-8b6432ad342b
* Content: [STRING_AGG (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/string-agg-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/functions/string-agg-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/string-agg-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@mjswart-d2l -- Michael, thank you for your suggestions.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by rwestMSFT** [comment]
@mjswart-d2l Would you be interested in creating a pull request to update the example section? As you can see, we have a backlog and haven't yet had a chance to look into this.

**Comment by MikeRayMSFT** [comment]
@mjswart-d2l  - thanks again for the suggestion. I've filed an internal item to fix this which we will prioritize and resolve as resources allow. 

[User Story 124333](https://dev.azure.com/msft-skilling/Content/_workitems/edit/124333): SQL Server | Improve  A & B example on STRING_AGG
