### ISSUE TITLE
No "Properties" on SSMS for SQL DB (maybe SQL MI as well)

### ISSUE THREAD

**Issue by doitnow420** [MicrosoftDocs/sql-docs#7865]
Docs says:

To add a member to a user-defined database role

1. In Object Explorer, expand the server in which you want to edit a user-defined database role.
2. Expand the Databases folder.
3. Expand the database in which you want to edit a user-defined database role.
4. Expand the Security folder.
5. Expand the Roles folder.
6. Expand the Database Roles folder.
7, Right-click the role you want to edit and select Properties.
8. In the Database Role Properties -database_role_name dialog box, in the General page, click Add.
9. In the Select Database User or Role dialog box, under Enter the object names to select (examples), enter the login or database role to add to this database role. Alternately, click Browse... and select any or all of the available objects in the Browse for Objects dialog box. Click OK to return to the Database Role Properties -database_role_name dialog box.
10. Click OK.

**7, Right-click the role you want to edit and select Properties.**

SSMS does not show "Properties" for SQL DB(probably the same for SQL MI).

So could you please remove "Azure SQL Database" (and Azure SQL Managed Instance) from "Applies to" on the top?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48e8faac-493d-c9f9-1656-393f95e51d25
* Version Independent ID: 023b79b9-ced9-9c30-0bdb-d013fca515cf
* Content: [Join a Role - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/join-a-role?view=sql-server-ver15#to-add-a-member-to-a-user-defined-database-role)
* Content Source: [docs/relational-databases/security/authentication-access/join-a-role.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/join-a-role.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@doitnow420 -- thank you for your feedback.

@VanMSFT -- if this conjecture regarding "Applies to" is correct, please let me know and I will update the article.

**Comment by VanMSFT** [comment]
@doitnow420 - Thanks for the feedback. You can add a role in Azure SQL, but you'll need to use T-SQL. The doc still applies to Azure SQL Database, but not the portion about using SSMS. The SSMS functionality differs for SQL Server and Azure SQL, and these scenarios generally cover for SQL Server.

@WilliamAntonRohm - Thanks, William. It would probably help to add a clarifying sentence that the SSMS steps are for SQL Server.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- Van, please review this update in [private PR 23602](https://github.com/MicrosoftDocs/sql-docs-pr/pull/23602).
