### ISSUE TITLE
FUNCTION OBJECT_SCHEMA_NAME not supported in Azure Synapse Serverless

### ISSUE THREAD

**Issue by lpargiter** [MicrosoftDocs/sql-docs#7872]
Maybe I'm missing something but I'm thinking this doc should have a caveat that it is not supported in Azure Synapse Serverless, since the "Applies to:" references "Azure Synapse Analytics".  Error: "FUNCTION 'OBJECT_SCHEMA_NAME' is not supported" is returned using it in Azure Synapse Serverless.

Thanks,
Luke

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0cee1d-1e90-2cd1-39c2-67404d0f2cc8
* Version Independent ID: 483fc29c-d706-dbf2-db99-513bc683298c
* Content: [OBJECT_SCHEMA_NAME (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/object-schema-name-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/functions/object-schema-name-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/object-schema-name-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@lpargiter -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue.

**Comment by jenpritchard** [comment]
Has there been any progress on this? I just wasted an afternoon working on something only to find out that it will work in our dedicated but not our serverless

**Comment by WilliamAntonRohm** [comment]
@jenpritchard -- Jen, thank you for your followup.

@rwestMSFT -- Randolph, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
#reassign:WilliamDAssafMSFT

**Comment by WilliamDAssafMSFT** [comment]
@lpargiter Thanks for taking the time to provide this feedback, your suggestions help improve our documentation. This article will be updated to clarify its applicability for Azure Synapse. You are correct, this syntax is not supported for serverless SQL pools.
