### ISSUE TITLE
LEFT and RIGHT behavior clarification

### ISSUE THREAD

**Issue by DreadLordMikey** [MicrosoftDocs/sql-docs#7876]
A useful clarification for these pages would be that if the length of the provided string is less than the provided length, the string is returned unmodified.

I don't know how many times I've seen SQL scripts with explicit and unnecessary checks against the length of a string before calling LEFT and RIGHT because developers didn't know this behavior was built into the functions.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1da09376-977d-cbd4-b92e-7150eee0d1f4
* Version Independent ID: d066fb72-7486-d982-b09c-4db5a7d71757
* Content: [LEFT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/left-transact-sql?f1url=%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LEFT_TSQL)%3Bk(sql13.swb.tsqlresults.f1)%3Bk(sql13.swb.tsqlquery.f1)%3Bk(MiscellaneousFilesProject)%3Bk(DevLang-TSQL)%26rd%3Dtrue&view=sql-server-ver16#feedback)
* Content Source: [docs/t-sql/functions/left-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/left-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@DreadLordMikey -- Michael, thank you for your feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@DreadLordMikey 

Thank you for your feedback! We will investigate and get back to you with the relevant info.

However, please add your experience in [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) to find if you see more people experience the same situation.

**Comment by WilliamDAssafMSFT** [comment]
@DreadLordMikey This is pretty self-evident from the documentation as is. Many unnecessary transformations like this may be more along the lines of a coding practice than a technical specification, as this document is. LEFT could also be a safety mechanism in some cases.
