### ISSUE TITLE
Information outdated

### ISSUE THREAD

**Issue by rhgoribeiro** [MicrosoftDocs/sql-docs#7878]
The information on this page is outdated and there for misleading.
SSMS 18 no longer uses this type of regex. instead it uses .NET regex

it took me several hours and trial & error to figure this out. 

Please update the info on this page

Best regards
rhgoribeiro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9027fbf7-358e-f42f-91e3-5dd316bd68a1
* Version Independent ID: 8751863c-1c8f-fe89-11be-e66ebc8416fa
* Content: [Search Text with Regular Expressions - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/scripting/search-text-with-regular-expressions?view=sql-server-ver16)
* Content Source: [docs/ssms/scripting/search-text-with-regular-expressions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/search-text-with-regular-expressions.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@rhgoribeiro -- thank you for your clear feedback.

@markingmyname -- please look into this issue.

**Comment by erinstellato** [comment]
@markingmyname Per @Matteo-T we can just link that page (for recent version of SSMS) to the VS2017 Find & Replace, as we rely on what VS does there.  I think it would be this: https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2017/ide/finding-and-replacing-text?view=vs-2017

**Comment by markingmyname** [comment]
@erinstellato, let me look into that.  thank you.

**Comment by markingmyname** [comment]
Hi, [rhgoribeiro](https://github.com/rhgoribeiro)

Sorry for the delay.

**Comment by markingmyname** [comment]
Changes made.  the article is replaced with the VS article.

Should be live by the end of the week.
