### ISSUE TITLE
LAST_VALUE syntax: rows_range_clause is optional

### ISSUE THREAD

**Issue by peterbud** [MicrosoftDocs/sql-docs#7880]
The syntax is incorrect, as rows_range_clause should be optional and therefore in square brackets:

```
LAST_VALUE ( [ scalar_expression ] )  [ IGNORE NULLS | RESPECT NULLS ]
    OVER ( [ partition_by_clause ] order_by_clause rows_range_clause )
```

should be 
```
LAST_VALUE ( [ scalar_expression ] )  [ IGNORE NULLS | RESPECT NULLS ]
    OVER ( [ partition_by_clause ] order_by_clause [ rows_range_clause ] )
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ffda42-ab8a-74df-0b14-92cc12cf39df
* Version Independent ID: 1fd3836e-52fa-014c-67de-b73e0fd810ed
* Content: [LAST_VALUE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/last-value-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/functions/last-value-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/last-value-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@peterbud -- Peter, thank you for catching that.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@peterbud -- Peter, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
