### ISSUE TITLE
As of 8/1/2022 JSON_OBJECT does not appear to yet be available in Azure SQL Database.

### ISSUE THREAD

**Issue by LuisGonzalezLT** [MicrosoftDocs/sql-docs#7884]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82439ce5-53ba-e7a5-cd8a-d8d8d60f9d02
* Version Independent ID: 82439ce5-53ba-e7a5-cd8a-d8d8d60f9d02
* Content: [JSON_OBJECT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-object-transact-sql?view=azuresqldb-current)
* Content Source: [docs/t-sql/functions/json-object-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/json-object-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @uc-msft
* Microsoft Alias: **umajay**

**Comment by TimShererWithAquent** [comment]
@LuisGonzalezLT  Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please provide more context around the general task .
