### ISSUE TITLE
Confusion about SCHEMA_NAME, OBJECT_NAME and DISTRIBUTION

### ISSUE THREAD

**Issue by sommarskog** [MicrosoftDocs/sql-docs#7885]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ac2fe2-31da-7db6-2d5f-5091022f41d2
* Version Independent ID: bbf07c2c-7006-7b94-f12f-800fa7bc67e4
* Content: [CREATE EXTERNAL TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-table-transact-sql?view=sql-server-ver16&tabs=dedicated)
* Content Source: [docs/t-sql/statements/create-external-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by sommarskog** [comment]
Sorry, did not see where I was supposed to type.

On this page, SCHEMA_NAME, OBJECT_NAME and DISTRIBUTION are explained in the text, and they also appear in at least one example(G). But they don't appear in the initial syntax graph. Also, when I try Example G on SQL 2022 CTP 2.1, I get a syntax error. I believe this these three arguments are only valid in Azure SQL Database.

Also, the syntax graph suggests that FILE_FORMAT is mandatory, but that is reasonably not the case when the external data source is a relational data source.

It appears that this topic is in need of some review. Or being split in separate topics, given the differences between platforms.

**Comment by TimShererWithAquent** [comment]
@sommarskog Thanks for your input. We'll look at the issues you found.

**Comment by WilliamDAssafMSFT** [comment]
Appears to be correct on all accounts, thanks @sommarskog. It looks like some of this content belongs in the Azure SQL DB version of the article, thanks for taking the time to point this out.  A doc update is in flight. Thanks again for taking the time to provide this feedback, your suggestions help improve our documentation.
