### ISSUE TITLE
Increase the password length?

### ISSUE THREAD

**Issue by nhoxchipZ1** [MicrosoftDocs/sql-docs#7887]
[Enter feedback here]
password is a maximum of 128 characters
-> How about increase the password length to 1024 characters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 170326d4-4dd1-32cf-f96b-2d161cfc7cfb
* Version Independent ID: 1fa164f7-1987-70cb-4290-6a97b1717b19
* Content: [CREATE ASYMMETRIC KEY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-asymmetric-key-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/statements/create-asymmetric-key-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-asymmetric-key-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by TimShererWithAquent** [comment]
@nhoxchipZ1 Thanks for your suggestion - I'm looking into the right place to direct your input -

**Comment by VanMSFT** [comment]
Hi @nhoxchipZ1 - You can submit product feedback here: https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0, or use the product feedback button at the end of each article:

![image](https://user-images.githubusercontent.com/40007119/182674822-32651b23-3f69-46db-b6eb-8a683d17190c.png)

Thanks!
