### ISSUE TITLE
windows related configuration types are not supported in Azure SSIS IR

### ISSUE THREAD

**Issue by SamarendraPanda** [MicrosoftDocs/sql-docs#7888]
The document shows that, all the 5 package configuration types are supported by the Azure SDF SSIS IR. However, below 2 are not supported by SSIS IR. 

Environment variable | An environment variable contains the configuration.
Registry entry | A Registry entry contains the configuration.

Document should have a note mentioning this. 

https://docs.microsoft.com/en-us/sql/integration-services/packages/legacy-package-deployment-ssis?view=sql-server-ver16&source=docs#package-configuration-types

**Comment by TimShererWithAquent** [comment]
@SamarendraPanda Thanks for your input!

**Comment by rwestMSFT** [comment]
@SamarendraPanda Please create a pull request with this change, which will increase the likelihood of it being made.

**Comment by rwestMSFT** [comment]
@SamarendraPanda We are closing this public issue and tracking it internally.

AB#214733
