### ISSUE TITLE
Just missing <>, according the the Microsoft Syntax Conventions

### ISSUE THREAD

**Issue by henriquebg88** [MicrosoftDocs/sql-docs#7896]
At:
```
-- Transact-SQL Syntax for Natively Compiled Stored Procedures

CREATE [ OR ALTER ] { PROC | PROCEDURE } [schema_name.] procedure_name
    [ { @parameter data_type } [ NULL | NOT NULL ] [ = default ]
        [ OUT | OUTPUT ] [READONLY]
    ] [ ,... n ]
  WITH NATIVE_COMPILATION, SCHEMABINDING [ , EXECUTE AS clause ]
AS
{
  BEGIN ATOMIC WITH (set_option [ ,... n ] )
sql_statement [;] [ ... n ]
 [ END ]
}
 [;]

<set_option> ::=
    LANGUAGE = [ N ] 'language'
  | TRANSACTION ISOLATION LEVEL = { SNAPSHOT | REPEATABLE READ | SERIALIZABLE }
  | [ DATEFIRST = number ]
  | [ DATEFORMAT = format ]
  | [ DELAYED_DURABILITY = { OFF | ON } ]
```

set_option is missing the <>. Should be <set_option>, as explained on the [Microsoft syntax conventions](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql?view=sql-server-ver16)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e804135e-b9e9-3d0c-4bc8-9f522a6d8178
* Version Independent ID: 117bdc3d-c3d0-4363-e625-a41ef559d488
* Content: [CREATE PROCEDURE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-procedure-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/statements/create-procedure-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-procedure-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by rwestMSFT** [comment]
@henriquebg88 Thank you for your feedback! I'll look into this.

#reassign:@rwestMSFT

**Comment by rwestMSFT** [comment]
@henriquebg88 This issue will close automatically when the article is approved, and you can expect to see the refreshed content in the next day or so.
