### ISSUE TITLE
Syntax Error in table_or_view_name

### ISSUE THREAD

**Issue by Timothy-Liu** [MicrosoftDocs/sql-docs#7897]
The syntax of ```table_or_view_name [ FOR SYSTEM_TIME <system_time> ] [ AS ] table_alias ] ``` has an error - a open bracket '[' is missing from ```[ AS ] table_alias ]```.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3553153e-f6bf-2bc7-288c-ee03a3ba0781
* Version Independent ID: b4e3cfdf-aad7-e8a6-ffd7-acba7571de5c
* Content: [FROM clause plus JOIN, APPLY, PIVOT (T-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/from-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/queries/from-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/from-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@Timothy-Liu -- Timothy, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
