### ISSUE TITLE
DEADLOCK_PRIORITY should not be marked supported for Azure Synapse Analytics and PDW

### ISSUE THREAD

**Issue by cheenamalhotra** [MicrosoftDocs/sql-docs#7898]
It seems the documentation incorrectly marks DEADLOCK_PRIORITY to be supported for Azure Synapse Analytics and Analytics Platform System (PDW), can you please confirm that's valid?

Below behavior is seen however when connecting to a DW database:

![image](https://user-images.githubusercontent.com/13396919/182961189-2ef625bb-fd26-468e-8789-a602fd7c4fd3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c086835-072b-d846-753c-c4f4fe09d260
* Version Independent ID: 3c09f21e-db70-f781-baff-f3199efd2fa2
* Content: [SET DEADLOCK_PRIORITY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-deadlock-priority-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/statements/set-deadlock-priority-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-deadlock-priority-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@cheenamalhotra -- Cheena, thank you for raising this.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
@cheenamalhotra Great catch, thanks for taking the time to provide this helpful feedback on Microsoft Docs. A doc update to resolve this and refresh this Doc is in flight. Your suggestions help improve our documentation.
