### ISSUE TITLE
Minor inconsistency's in FORMAT docs

### ISSUE THREAD

**Issue by casparz** [MicrosoftDocs/sql-docs#7900]
The code block in A is not consistantly naming culture 'zh-cn'.
The result block in C does not correspond the code block, the column names do not match.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f019407-5787-6f54-1027-084e817b6b8e
* Version Independent ID: a92541d0-b63a-9603-2a1f-18e210be89e4
* Content: [FORMAT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/format-transact-sql?redirectedfrom=MSDN&view=sql-server-ver16)
* Content Source: [docs/t-sql/functions/format-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/format-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@casparz -- thank you for catching that.  I am updating the article.
