### ISSUE TITLE
Issue with the instructions for installing Microsoft ODBC for SQL Server (Linux) ubuntu commands

### ISSUE THREAD

**Issue by TrevorMay** [MicrosoftDocs/sql-docs#7909]
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16
currently the instructions say to run this command
curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list > /etc/apt/sources.list.d/mssql-release.list
it seems that url is dead so it adds the html code for the 404 not found page to /etc/apt/sources.list.d/mssql-release.list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#17)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
@TrevorMay What version of Ubuntu are you trying to install on? I.e., what is the output of `lsb_release -rs`?

**Comment by TrevorMay** [comment]
@David-Engel 10, this is on an Azure App Service that I'm trying to get to be able to connect a sql server database through python and pyodbc.

**Comment by David-Engel** [comment]
@TrevorMay 

10?

That doesn't align with Ubuntu versions I'm familiar with. Did you mean 21.10? If you are running the full install script, you should have been stopped by the first command that verifies you are running a supported version:

```
if ! [[ "16.04 18.04 20.04 21.04 21.10" == *"$(lsb_release -rs)"* ]];
then
    echo "Ubuntu $(lsb_release -rs) is not currently supported.";
    exit;
fi
```

**Comment by TrevorMay** [comment]
![image](https://user-images.githubusercontent.com/57117008/183509565-9070acf6-b760-4a3c-a5af-7398a7a748d1.png)
I'm not sure, I'm really new to Cloud development and Linux in general. You are correct I apologize I unfortunately assumed that whatever version of Ubuntu the Web App was grabbing to deploy would be new enough that the first check at the top of that script didn't relate to my situation and went ahead with the below commands.

**Comment by David-Engel** [comment]
It looks like Debian underpins App Service on Linux. You can probably check with either of these commands:

```
uname -a

cat /etc/os-release
```

You can try the Debian installation instructions and see if that works for you.

Regards,
David

**Comment by TrevorMay** [comment]
It seems like following the Debian installation instructions worked, thank you so much! I will close this issue now.
