### ISSUE TITLE
"Learn more about go-sqlcmd on Github" links to GO driver instead of go-sqlcmd

### ISSUE THREAD

**Issue by zijchen** [MicrosoftDocs/sql-docs#7910]
Not sure if the "Learn more about go-sqlcmd on Github" link under Next Steps is supposed to say "Learn more about the GO driver" or supposed to link to the go-sqlcmd page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 094da575-8e25-b22b-9db0-4355c446109a
* Version Independent ID: 094da575-8e25-b22b-9db0-4355c446109a
* Content: [go-sqlcmd utility (preview) - SQL Server](https://docs.microsoft.com/en-us/sql/tools/go-sqlcmd-utility?view=sql-server-ver16#feedback)
* Content Source: [docs/tools/go-sqlcmd-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/go-sqlcmd-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@zijchen -- Z, thank you for catching this.  I am updating the article.  Here is the correct link:
- https://github.com/microsoft/go-sqlcmd

**Comment by WilliamAntonRohm** [comment]
@zijchen, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
