### ISSUE TITLE
Potential Syntax Error Near [ [ AS ] column_alias ] 

### ISSUE THREAD

**Issue by Timothy-Liu** [MicrosoftDocs/sql-docs#7911]
To the syntax:
```
...
        {  
          [ { table_name | view_name | table_alias }. ]  
               { column_name | $IDENTITY | $ROWGUID }   
          | udt_column_name [ { . | :: } { { property_name | field_name }   
            | method_name ( argument [ ,...n] ) } ]  
          | expression  
          [ [ AS ] column_alias ]   
         }  
...
```
the ``` [ [ AS ] column_alias ]  ``` should be out of the curly brace. or it will only belongs to the ```expression```.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fdbcbae-052c-a473-2c78-9523eb08153a
* Version Independent ID: 8b710871-2e83-0512-4702-9ba7a8657137
* Content: [SELECT Clause (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-clause-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/queries/select-clause-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/select-clause-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@Timothy-Liu -- Timothy, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@VanMSFT -- please review this change in [private PR 23907](https://github.com/MicrosoftDocs/sql-docs-pr/pull/23907).
