### ISSUE TITLE
Is RAISERROR () WITH LOG option still valid in Azure SQL databases?

### ISSUE THREAD

**Issue by jurw2201** [MicrosoftDocs/sql-docs#7914]
Hi, I'm tasked with porting an on-prem Microsoft SQL database and its routines to an Azure SQL database. I'm trying to create a stored procedure which includes the RAISERROR() WITH LOG option statement. When executing the script, it's returning error "Only System Administrator can specify WITH LOG option for RAISERROR command." The Azure SQL server has been setup to accept only Azure Active Directory authentication. An Azure security group was configured as admin which I am part of and have had no issues connecting or creating objects.

Anyways, all this to ask, as my feedback, since Azure SQL database uses Azure Monitor, is the "WITH LOG" option still valid in Azure SQL databases? Where is it logging the error? This information should be reflected in the "WITH LOG" option table, if still valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472beb1c-1682-d2db-c2b1-3083c174b0cc
* Version Independent ID: 099a81a1-42cb-bd91-9147-bc761d4be177
* Content: [RAISERROR (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/raiserror-transact-sql?view=azuresqldb-current)
* Content Source: [docs/t-sql/language-elements/raiserror-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/raiserror-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
Hi @jurw2201. You are correct that this is a permissions issue. To work around it, you'll need to use a BEGIN TRY block, and log the errors to a database table.

**Comment by rwestMSFT** [comment]
@jurw2201 An article update will remove "SQL Database" from the supported platforms for `WITH LOG` in the next day or so. Thank you again for your feedback.

**Comment by rwestMSFT** [comment]
#assign:@rwestMSFT
