### ISSUE TITLE
Failed to install msodbcsql18_18.1.1.1-1_amd64.apk and mssql-tools18_18.1.1.1-1_amd64.apk on Alpine:python3.7

### ISSUE THREAD

**Issue by rodelrebs** [MicrosoftDocs/sql-docs#7915]
Curl result is only 2KB size and throws an IO error  when installing as a local package with  `apk add --allow-untrusted <package>`.

  curl -O https://download.microsoft.com/download/b/9/f/b9f3cce4-3925-46d4-9f46-da08869c6486/msodbcsql18_18.1.1.1-1_amd64.apk
  curl -O https://download.microsoft.com/download/b/9/f/b9f3cce4-3925-46d4-9f46-da08869c6486/mssql-tools18_18.1.1.1-1_amd64.apk

**Comment by rwestMSFT** [comment]
@rodelrebs I can confirm that the URL gives a 404 error. Can you please let us know which Docs article you were referencing, to download this file?

**Comment by jayph88** [comment]
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15

**Comment by rwestMSFT** [comment]
@David-Engel, can you please look into this?

**Comment by rwestMSFT** [comment]
#assign:@David-Engel

**Comment by David-Engel** [comment]
Please try the download again. There was a hiccup in publishing the Alpine files. They should be available now.

**Comment by rodelrebs** [comment]
> Please try the download again. There was a hiccup in publishing the Alpine files. They should be available now.

I can confirm that it's working now. I was able to download and install it. Thanks.
