### ISSUE TITLE
Example 2 description incorrect

### ISSUE THREAD

**Issue by chargerback-ron** [MicrosoftDocs/sql-docs#7917]
[Enter feedback here]

Example 2
The following example returns 0 since the input JSON string contains the specified SQL/JSON path.

Shouldn't that read "... since the input JSON string does not contain the specified SQL/JSON path"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd30f6a4-5cc7-e614-c58d-623191ceaa7a
* Version Independent ID: dd30f6a4-5cc7-e614-c58d-623191ceaa7a
* Content: [JSON_PATH_EXISTS (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-path-exists-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/functions/json-path-exists-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/json-path-exists-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @uc-msft
* Microsoft Alias: **umajay**

**Comment by rwestMSFT** [comment]
@chargerback-ron Thanks for the feedback. You're absolutely right. I'll get this sorted.

#assign:@rwestMSFT

**Comment by rwestMSFT** [comment]
@chargerback-ron Thanks to some fortuitous timing, the refreshed article will be published some time tomorrow. Thanks again for your feedback.
