### ISSUE TITLE
It does not work on Azure SQL Server

### ISSUE THREAD

**Issue by tund3010** [MicrosoftDocs/sql-docs#7918]
[Nhập phản hồi vào đây]
It does not work on Azure SQL Server due to they don't support USE command

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: f6cb23e7-dfcf-8e7e-9042-aa4ce18fdfe3
* Version Independent ID: 71341cc5-767d-74d1-d0d9-81c1c87540ad
* Content: [Delete a Database - SQL Server](https://docs.microsoft.com/vi-vn/sql/relational-databases/databases/delete-a-database?view=azuresqldb-current)
* Content Source: [docs/relational-databases/databases/delete-a-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/delete-a-database.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @tund3010 for taking the time to provide this feedback, your suggestions help improve our documentation. You are of course correct, we have added applicability to many existing legacy articles. We have an ongoing effort in place to address issues like this and doc updates are in flight, and this will be resolved. Will close this ticket.
