### ISSUE TITLE
SQL Engine virtual account

### ISSUE THREAD

**Issue by JozefBk** [MicrosoftDocs/sql-docs#7919]
There is an incorrect specification for SQL Engine Virtual account format near:

"(All rights are granted to the per-service SID. Default instance: NT SERVICE\MSSQLSERVER. Named instance: NT Service\MSSQLServer$InstanceName.)"

Should instead read as

"(All rights are granted to the per-service SID. Default instance: NT SERVICE\MSSQLSERVER. Named instance: NT Service\MSSQL$InstanceName.)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b3831a3-6c86-243c-4b07-8960e4d06d7b
* Version Independent ID: dfd7599d-88eb-99f2-c227-0c9dc82bfd87
* Content: [Configure Windows service accounts and permissions - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
Thank you for your feedback @JozefBk! I will look into this.

#assign:@rwestMSFT
