### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by Lemilton** [MicrosoftDocs/sql-docs#7920]
Under point 1. it says:

> Local workstations must have the same Python package versions as those on SQL Server, including the base Anaconda 4.2.0 with Python 3.5.2 distribution, and Microsoft-specific packages.

But when installing SQL Server Management Services, it installs Python 3.7.1 with revoscalepy 9.4.7.
Would it be possible to add the updated information for which Anaconda and Python versions are needed and add an installer for the newer revoscalepy version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2175e183-b508-c7e4-1caa-65b2adbb3b54
* Version Independent ID: e2ee7575-2be6-6ec7-4b2e-be278da1f2ff
* Content: [Set up a Python data science client - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/python/setup-python-client-tools-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-ver16)
* Content Source: [docs/machine-learning/python/setup-python-client-tools-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/python/setup-python-client-tools-sql.md)
* Product: **sql**
* Technology: **machine-learning-services**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @Lemilton for contacting Microsoft with feedback about our product documentation. It could take from a few business days to a few weeks to look further into this with the product team and decide on how to address.

**Comment by WilliamDAssafMSFT** [comment]
@Lemilton - Some info for you.
SSMS does not install revoscalepy. With SQL Server 2022, all runtimes are user-installed and not shipped with SQL Server. Here is the version info per version: https://docs.microsoft.com/en-us/sql/machine-learning/sql-server-machine-learning-services?view=sql-server-ver15#python-and-r-versions 
The recommendation stands to install the same runtimes on both the server and on workstations in all versions of SQL Server, keeping in mind that different versions of SSMS and versions of SQL Server prior to 2022 may not install the same runtimes by default.

Thanks again for taking the time to create this issue, your feedback improve the Microsoft Docs experience for everyone.

**Comment by Lemilton** [comment]
@WilliamDAssafMSFT Thank you very much for the fast answer. I have the same runtimes on all SQL Servers I use but I am not sure how to get the same runtime onto my workstation (no SQL Server) as the installer from the Docs page only ships with Python 3.5.2 and revoscalepy 9.3 while the SQL Servers I use have 3.7.1 and 9.4.7. Is there a way to update the versions on my workstation to match those of the SQL Servers?
Maybe there is an obvious solution to this problem but I sadly can't figure it out and would be very thankful for some help.

**Comment by Lemilton** [comment]
I guess I found the up-to-date installer [here](https://docs.microsoft.com/en-us/previous-versions/machine-learning-server/install/machine-learning-server-windows-offline#file-list-94). Would it be possible to add the new one to the [SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/python/setup-python-client-tools-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-ver16) Docs under the page for setting up a python client?

**Comment by WilliamDAssafMSFT** [comment]
> I guess I found the up-to-date installer [here](https://docs.microsoft.com/en-us/previous-versions/machine-learning-server/install/machine-learning-server-windows-offline#file-list-94). Would it be possible to add the new one to the [SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/python/setup-python-client-tools-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-ver16) Docs under the page for setting up a python client?

That's a good idea @Lemilton, look for that soon.
