### ISSUE TITLE
The download link labeled "Free Download for SQL Server Management Studio (SSMS) 18.12.1" is downloading version 19, preview 3

### ISSUE THREAD

**Issue by AlanWaiss** [MicrosoftDocs/sql-docs#7933]
I've tried 3 different times to make sure I was clicking the correct thing. I switched the Version drop down to "SQL Server 2019". It links to https://aka.ms/ssmsfullsetup, but when I click to run, the installer says Version 19, Preview 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
@AlanWaiss Thank you for reporting this issue, there was an error on our end which should now be resolved, and selecting "Free Download for SQL Server Management Studio SSMS (18.12.1)" should now download 18.12.1 (and not SSMS 19 Preview 3).

**Comment by erinstellato-ms** [comment]
#please-close
