### ISSUE TITLE
Update need to providers table for NetApp

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/sql-docs#7934]
Please update NetApp table entry in section https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-and-restore-with-s3-compatible-object-storage?view=sql-server-ver16#providers-of-s3-compatible-object-storage to:

Left column:
[NetApp](https://www.netapp.com/)
Right column:
[StorageGrid](https://docs.netapp.com/us-en/storagegrid-116/s3/index.html)
[ONTAP ](https://docs.netapp.com/us-en/ontap/s3-config/s3-support-concept.html)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fa91b14-0a07-8fd0-a9b0-8deb950354c0
* Version Independent ID: 7fa91b14-0a07-8fd0-a9b0-8deb950354c0
* Content: [Backup & restore with S3-compatible object storage - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-and-restore-with-s3-compatible-object-storage?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/sql-server-backup-and-restore-with-s3-compatible-object-storage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/sql-server-backup-and-restore-with-s3-compatible-object-storage.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @gvanteylingen for contacting Microsoft with feedback about our product documentation. We'll look further into this with the product team and decide on how to address. 
	
Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
Thanks again @gvanteylingen for contacting Microsoft with this feedback. A doc update is in flight.
