### ISSUE TITLE
add section/note related to MSDB database regarding TRUSTWORHTY

### ISSUE THREAD

**Issue by emad-almousa** [MicrosoftDocs/sql-docs#7937]
Hi,

it will be very good addition to state that MSDB database which is a system database by default has TRUSTWORTHY setting set to "true" by design and this shouldn't be changed.

Regards,
Emad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f50f342e-6257-8000-1d57-d58e7050507a
* Version Independent ID: c5c39a8f-bbea-d31d-0440-fc4212b23fa0
* Content: [TRUSTWORTHY Database Property - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/trustworthy-database-property?view=sql-server-ver16&source=docs)
* Content Source: [docs/relational-databases/security/trustworthy-database-property.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/trustworthy-database-property.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@emad-almousa -- Emad, thank you for your considered suggestion.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @emad-almousa - Thanks for the feedback! Can you please expand on why the documentation should include references to msdb being trustworthy by default, and what's a use case of this?

**Comment by emad-almousa** [comment]
Hi, 
Thanks for your message, as I said its a "suggestion"....TRUSTWORTHY property is a very dangerous settings and inexperienced IT analyst can think that changing it in MSDB is not harmful. so, it needs to be explicitly mentioned as disclaimer that MSDB has this property set to TRUE by design and should be kept as is. its the only database by **_default_** has this setting enabled.
