### ISSUE TITLE
Missing space

### ISSUE THREAD

**Issue by codykonior** [MicrosoftDocs/sql-docs#7939]
There's a space missing between the link and the Transact-SQL word:

> the [CREATE SECURITY POLICY](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-security-policy-transact-sql?view=sql-server-2017)Transact-SQL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c96c3ee-5443-004f-d189-3701f8bef6c9
* Version Independent ID: efcc952b-eadb-4579-54c7-00da3bc107ae
* Content: [Row-Level Security - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/row-level-security?view=sql-server-2017)
* Content Source: [docs/relational-databases/security/row-level-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/row-level-security.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@codykonior -- Cody, thank you for catching this.  I am updating the article.
