### ISSUE TITLE
Incorrect update to NetApp S3 compatible products 

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/sql-docs#7940]
Hi,

I recently requested an update (https://github.com/MicrosoftDocs/sql-docs/issues/7934) to the products under 'NetApp' but they were not incorporated correctly unfortunately.

The NetApp products supporting S3 are distinctly different product lines, as such the request was to update to:
Left-hand column:

> [NetApp](https://www.netapp.com/)

Right-hand column:

> [StorageGrid](https://docs.netapp.com/us-en/storagegrid-116/s3/index.html)
> [ONTAP](https://docs.netapp.com/us-en/ontap/s3-config/s3-support-concept.html)

If this is not possible, please update to:
Left-hand column:

> [NetApp](https://www.netapp.com/)

Right-hand column: 

> StorageGrid, ONTAP

(note the comma between the StorageGrid and ONTAP)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fa91b14-0a07-8fd0-a9b0-8deb950354c0
* Version Independent ID: 7fa91b14-0a07-8fd0-a9b0-8deb950354c0
* Content: [Backup & restore with S3-compatible object storage - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-and-restore-with-s3-compatible-object-storage?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/sql-server-backup-and-restore-with-s3-compatible-object-storage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/sql-server-backup-and-restore-with-s3-compatible-object-storage.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hi @gvanteylingen, thanks again for the time and attention to this detail. A doc update is underway.
