### ISSUE TITLE
No binaries for ARM or whatnot ?

### ISSUE THREAD

**Issue by mckenzm** [MicrosoftDocs/sql-docs#7956]
May wish to mention supported instruction sets might be restricted to AMD64......    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@mckenzm -- Matthew, thank you for your suggestion.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @mckenzm - Thanks for the feedback. The system requirements for SQL Server on Linux are listed in the [prerequisites](https://docs.microsoft.com/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16#prerequisites-2) in the doc referenced, and points to here: https://docs.microsoft.com/sql/linux/sql-server-linux-setup#system

#please-close
