### ISSUE TITLE
GDR program information

### ISSUE THREAD

**Issue by kegotms** [MicrosoftDocs/sql-docs#7958]
[Enter feedback here]
Users don't know which cab file will be needed when we try to applying GDR patch such as KB4583458 (SQL Server 2019 GDR-RTM) and KB4583457 (SQL Server 2017 RTM-GDR).
Can you add the GDR patch imformation in this document?

Example
|**[SQL Server 2019 RTM GDR](https://support.microsoft.com/help/4583458)** |  |  |  |
| | Microsoft R Open      | [SRO_3.5.2.125_1033.cab](https://go.microsoft.com/fwlink/?linkid=2085686)  |  |
| | R Server              | [SRS_9.4.7.25_1033.cab](https://go.microsoft.com/fwlink/?linkid=2085792)  |  |
| | Microsoft Python Open | [SPO_4.5.12.120_1033.cab](https://go.microsoft.com/fwlink/?linkid=2085793) |  |
| | Python Server         | [SPS_9.4.7.25_1033.cab](https://go.microsoft.com/fwlink/?linkid=2085685)  |  |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9ff3c86-865f-9cbb-1d0a-2248149f4c87
* Version Independent ID: 12963cad-1c8a-d3f4-7b44-3fcd56206393
* Content: [CAB download updates for offline install - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/install/sql-ml-cab-downloads?view=sql-server-2017#sql-server-2017-cabs)
* Content Source: [docs/machine-learning/install/sql-ml-cab-downloads.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/install/sql-ml-cab-downloads.md)
* Product: **sql**
* Technology: **machine-learning-services**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @kegotms for taking the time to file this issue. I've reviewed with the PG and a doc update is in flight. In general, GDR releases do not get new .cab files, and so use the .cab file from the most recent non-GDR release, such as a CU.
