### ISSUE TITLE
ExcludedObject Types misisng

### ISSUE THREAD

**Issue by czb182** [MicrosoftDocs/sql-docs#7962]
following types missing from current documentation

AssemblyFiles;DatabaseEncryptionKeys;DatabaseOptions;DatabaseWorkloadGroups;ExternalLanguages;ExternalLibraries;ExternalStreamingJobs;ExternalStreams;MasterKeys;WorkloadClassifiers

current documentation checked against list here 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.objecttype?view=sql-dacfx-160
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2042e58f-bf1e-fe60-e270-293906bb48be
* Version Independent ID: 02a48c1c-5401-e4dd-8935-51a715925395
* Content: [SqlPackage Script - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-script?view=sql-server-ver16)
* Content Source: [docs/tools/sqlpackage/sqlpackage-script.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage/sqlpackage-script.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by czb182** [comment]
for values to use in DoNotDropObjectTypes

**Comment by WilliamAntonRohm** [comment]
@czb182 -- Christopher, thank you for your feedback.

@dzsquared -- Drew, please look into this issue.

**Comment by dzsquared** [comment]
#please-close
