### ISSUE TITLE
JSON_ARRAY error in Azure SQL Managed Instance

### ISSUE THREAD

**Issue by chargerback-ron** [MicrosoftDocs/sql-docs#7963]
[Enter feedback here]
Copy and paste Example 1 into SSMS 18.12.1 connected to Azure SQL Managed Instance, run with F5, and I receive the following message:

Msg 195, Level 15, State 10, Line 1
'JSON_ARRAY' is not a recognized built-in function name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb550ea1-2f4d-9213-ef4e-0da7967349e3
* Version Independent ID: eb550ea1-2f4d-9213-ef4e-0da7967349e3
* Content: [JSON_ARRAY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-array-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/functions/json-array-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/json-array-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @uc-msft
* Microsoft Alias: **umajay**

**Comment by WilliamAntonRohm** [comment]
@chargerback-ron -- Ron, thank you for your feedback.

@uc-msft -- Umachandar, please look into this issue.

**Comment by rwestMSFT** [comment]
I am reviewing old issues and noticed this was still open. Can you please confirm whether the issue persists?

**Comment by rwestMSFT** [comment]
@chargerback-ron I notice that the article was changed in May 2023, to remove "Azure SQL Managed Instance" from the "Applies to" section, so I'm going to close this as resolved.

**Comment by chargerback-ron** [comment]
@rwestMSFT Thank you!

**Comment by rwestMSFT** [comment]
Thanks for raising the issue originally, and for your patience as we close stale issues.
