### ISSUE TITLE
JSON_ARRAY is not working with the current build of Azure SQL DB. 

### ISSUE THREAD

**Issue by ralphke** [MicrosoftDocs/sql-docs#7964]
The expression JSON_ARRAY is not working with the current build of Azure SQL DB. 
I get the following error message:
SELECT JSON_ARRAY('a', 1, 'b', 2)
select @@VERSION
Error:
Msg 195, Level 15, State 10, Line 1
'JSON_ARRAY' is not a recognized built-in function name.

Select @@version
Microsoft SQL Azure (RTM) - 12.0.2000.8   May 12 2022 23:11:24   Copyright (C) 2022 Microsoft Corporation 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb550ea1-2f4d-9213-ef4e-0da7967349e3
* Version Independent ID: eb550ea1-2f4d-9213-ef4e-0da7967349e3
* Content: [JSON_ARRAY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-array-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/functions/json-array-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/json-array-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @uc-msft
* Microsoft Alias: **umajay**

**Comment by WilliamAntonRohm** [comment]
@ralphke -- Ralph, thank you for writing to us.  This issue is a duplicate of #7963.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by rwestMSFT** [comment]
I am reviewing old issues and noticed the related issue was still open. Can you please confirm whether the issue persists?
