### ISSUE TITLE
Slight Grammar Correction

### ISSUE THREAD

**Issue by dwneder** [MicrosoftDocs/sql-docs#7969]
Might want to fix this line toward the top of the page:

Features for OLTP (Online Transactional Processing)
Systems **_which_** ("that") must **_processes_** ("process") large numbers of SQL INSERTs concurrently are excellent candidates for the OLTP features.

The nits have been picked.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c7055d-861f-fe71-bde6-63decf873bfe
* Version Independent ID: 4dc3b379-862b-54d3-f04f-c29e95353527
* Content: [In-memory OLTP for faster T-SQL Performance - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/survey-of-initial-areas-in-in-memory-oltp?view=sql-server-ver16)
* Content Source: [docs/relational-databases/in-memory-oltp/survey-of-initial-areas-in-in-memory-oltp.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/survey-of-initial-areas-in-in-memory-oltp.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Nice catch @dwneder, thanks! A doc update is in flight.
