### ISSUE TITLE
Azure Arc Enabled instance - missing argument in documentation?

### ISSUE THREAD

**Issue by johlju** [MicrosoftDocs/sql-docs#7970]
In the example for Deploy to Azure Arc the argument `/ONBOARDSQLTOARC` is present, but it is not mentioned in the list of arguments for the setup action `Install`. Is the example wrong or is the argument list documentation missing the argument?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff01c71-f3bf-2c3a-5e90-b11952aee4f8
* Version Independent ID: 99ebd80b-9465-6929-c84f-187525ee3284
* Content: [SQL Server installation - Command Prompt parameters - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-ver16)
* Content Source: [docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
Hi @johlju, this is likely just an oversight because we're still in prerelease for SQL Server 2022.

**Comment by rwestMSFT** [comment]
This will be addressed in an internal PR.

#please-close
