### ISSUE TITLE
datetime  lost precision

### ISSUE THREAD

**Issue by minesunny** [MicrosoftDocs/sql-docs#7980]
Microsoft SQL Server 2019 (RTM-CU12) (KB5004524) - 15.0.4153.1 (X64) 
	Jul 19 2021 15:37:34 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 20.04.2 LTS) <X64>
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/98507458/185945853-f9d14211-4baf-4289-aee6-905056593cc5.png">

**Comment by WilliamAntonRohm** [comment]
@minesunny -- thank you for your feedback and example.  This looks like a product issue rather than a documentation issue; please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)
