### ISSUE TITLE
Problem with example 2

### ISSUE THREAD

**Issue by xerxel** [MicrosoftDocs/sql-docs#7983]
Why does example 2 have a "!" in it? Is that a mistake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfc6a4cd-b57c-8df6-221d-85aead960a91
* Version Independent ID: d0acb956-b718-d5d4-f422-52110f7a1242
* Content: [TRIM (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/functions/trim-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/trim-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by rwestMSFT** [comment]
Hi @xerxel, thanks for your question.

Here's the query being executed in SSMS 19 preview, against SQL Server 2022 (Preview) CTP 2.0.

![image](https://user-images.githubusercontent.com/97149825/186196359-2397fd7b-d919-4d9e-9a8e-7d82768e6c66.png)

In a real-world environment, you might have a common list of characters that you want to remove. In this example, you can see how the `'.,! '` portion is being used as a list of characters that should be removed from the string `'     #     test    .'` if they exist. However, only the space and period characters are being removed.

#please-close

**Comment by xerxel** [comment]
Well what you said makes sense but the description on the page is misleading:

> B. Remove specified characters from both sides of string
> The following example removes a trailing period and spaces from before # and after the word test.

The description seems to imply that in order to remove a trailing period and spaces you should include a ",!". Would be easier tfor users to understand if you either included your comments from above or removed the ",!" from the command.

**Comment by rwestMSFT** [comment]
An upcoming refresh will include clarifying language. Thanks again for your feedback.
