### ISSUE TITLE
The "S" within inputString is highlighted

### ISSUE THREAD

**Issue by renjieliu** [MicrosoftDocs/sql-docs#7987]
Not sure why the middle S is highlighted.

![image](https://user-images.githubusercontent.com/19803974/186237196-afc8c044-0216-4975-9654-e0c33e2d4ca7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e60cc3d-fd45-2a73-aa40-536051e9f54d
* Version Independent ID: ddf2d9c5-6855-66e7-06c6-b4036dea1276
* Content: [TRANSLATE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/translate-transact-sql?view=sql-server-ver16#feedback)
* Content Source: [docs/t-sql/functions/translate-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/translate-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rwestMSFT** [comment]
Hi @renjieliu. Thanks for your feedback. There's not much we can do about this unfortunately, so I'm going to report it internally and close this issue. We appreciate your help to make Docs better!

#please-close
