### ISSUE TITLE
Parentheses is not documented for filter_predicate section

### ISSUE THREAD

**Issue by OleksiiKovalov** [MicrosoftDocs/sql-docs#7988]
there is no mention of the usage of parentheses in the filter_predicate section but the SQL server supports parentheses here

```
drop table if exists dbo.DemoTable;
go
create table dbo.DemoTable(Id int);
go
create index IX on dbo.DemoTable(id) where (Id is not null) and (Id != 0);
go
create index IX2 on dbo.DemoTable(id) where ((Id is not null) and (Id != 0));
go
create index IX3 on dbo.DemoTable(id) where (((((Id is not null) and (Id != 0)))));
go
create index IX4 on dbo.DemoTable(id) where (((((Id is not null) and (Id in (0))))));
go

```

Microsoft SQL Server 2019 (RTM-CU16) (KB5011644) - 15.0.4223.1 (X64) 
	Apr 11 2022 16:24:07 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19044: ) (Hypervisor)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13793c61-629f-f379-fcb7-e9178e4f5dce
* Version Independent ID: ced6efc1-1e34-f452-f995-b597e812c2f2
* Content: [CREATE INDEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/statements/create-index-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-index-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@OleksiiKovalov -- Oleksii, thank you for your continued interest.

@rwestMSFT -- Randolph, please look into this issue.

**Comment by rwestMSFT** [comment]
Hi @OleksiiKovalov. In all your examples you're using the `AND` keyword, which makes the use of parentheses redundant. Is there a particular scenario in which you would consider that the use of parentheses would alter the filtered index definition?

**Comment by OleksiiKovalov** [comment]
hi @rwestMSFT , 
of course, parentheses are redundant here - but they are allowed here - so I or someone else can put them in the filter definition;  and are not documented, so I do not expect it here. this is not good.
basically, I found this situation while writing the "Redundant parentheses" code analyzer rule.
if parentheses are allowed in filter definition (and redundant parentheses - too) - I need to analyze this section of code - and as long as it does not fall under the general "condition" grammar rule - I need to take special care about it.
anyway, documentation must strictly match the actual implementation, regardless of how meaningless is code or behavior.

**Comment by rwestMSFT** [comment]
It's not that I'm not wanting to update the article. I just wonder what the correct approach is. Do we just add a note to say "parentheses are supported", or something more?

**Comment by OleksiiKovalov** [comment]
@rwestMSFT , sure, you should document it.
anyway, parentheses can be redundant - but they can (and sometimes - will) increase readability

**Comment by OleksiiKovalov** [comment]
hi @rwestMSFT , could you please also look at CREATE STATISTICS statement? 
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-statistics-transact-sql?view=sql-server-ver16
the same situation here

or a separate issue needed to be created?

**Comment by rwestMSFT** [comment]
That will have to be a separate issue. Thanks.

Also, please feel free to submit your own pull request, even if you aren't sure about things like formatting and layout.

**Comment by WilliamDAssafMSFT** [comment]
Hi @OleksiiKovalov! In this case, parenthesis would be treated like other logical operators, and are not documented on ANY of our TSQL syntax articles unless specifically required or made an example of, such as, "[Enclose each result_sets_definition in parentheses, separated by commas.](https://docs.microsoft.com/sql/t-sql/language-elements/execute-transact-sql?view=sql-server-ver16#:~:text=enclose%20each%20result_sets_definition%20in%20parentheses%2C%20separated%20by%20commas.%20)". Refer to our [TSQL Syntax conventions](https://docs.microsoft.com/sql/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql?view=sql-server-ver16) which make no specific mentions of when parentheses or other logical operators are supported, because they are supported in the vast majority of cases. We won't be updating these articles but I wish you the best of luck on your code analyzer project!

**Comment by OleksiiKovalov** [comment]
hi @WilliamDAssafMSFT , 
documentation for Expressions (https://docs.microsoft.com/en-us/sql/t-sql/language-elements/expressions-transact-sql?view=sql-server-ver16 ) and search_condition (https://docs.microsoft.com/en-us/sql/t-sql/queries/search-condition-transact-sql?view=sql-server-ver16) (used in where/having/join clauses of DML)  contains direct notes about parentheses - both in grammar and in remarks/article body
but for CREATE INDEX/STATEMENT filter, which is a simplified/limited form of search_condition - has no notion regarding parentheses.

I think documentation must be as clear and relevant as it is possible.
If the statement supports parentheses - it should be explicitly described, not implied.
