### ISSUE TITLE
Parentheses is not documented for filter_predicate section

### ISSUE THREAD

**Issue by OleksiiKovalov** [MicrosoftDocs/sql-docs#7989]
there is no mention of the usage of parentheses in the filter_predicate section but the SQL server supports parentheses here
```
CREATE STATISTICS ContactPromotion2
    ON Person.Person (BusinessEntityID, LastName, EmailPromotion)  
WHERE ((EmailPromotion = 2))
go

```
Microsoft SQL Server 2019 (RTM-CU16) (KB5011644) - 15.0.4223.1 (X64) 
	Apr 11 2022 16:24:07 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19044: ) (Hypervisor)

discussion about necessity of parentheses can be found here [#7988 ](https://github.com/MicrosoftDocs/sql-docs/issues/7988#issuecomment-1224871798)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fbe6561-d42f-d0a8-d119-72ae0f2b6796
* Version Independent ID: 26915af8-95c6-cf10-9d1f-616d5624e9f0
* Content: [CREATE STATISTICS (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-statistics-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/statements/create-statistics-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-statistics-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@OleksiiKovalov -- Oleksii, thank you for creating this issue as well.

@WilliamDAssafMSFT -- William, please see the discussion in #7988.

**Comment by WilliamDAssafMSFT** [comment]
See https://github.com/MicrosoftDocs/sql-docs/issues/7988#issuecomment-1224945266
