### ISSUE TITLE
[System stored procedures] sp_refreshview or sp_refreshsqlmodule are not supported in Azure Synapse SQL Serverless Pool

### ISSUE THREAD

**Issue by nstijepovic** [MicrosoftDocs/sql-docs#7991]
In our [documentation1](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-refreshview-transact-sql?view=sql-server-ver15), and  [documentation2](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-refreshsqlmodule-transact-sql?view=sql-server-ver15) it looks like that sp_refreshview and sp_refreshsqlmodule can both be used in Azure Synapse Analytics.

In contrary, sp_refreshview nor sp_refreshsqlmodule are supported in Synapse SQL Serverless Pool.

![image](https://user-images.githubusercontent.com/96438735/186389651-3b0a7324-d66d-448a-b935-bcb093681b3f.png)

![image](https://user-images.githubusercontent.com/96438735/186389059-de215309-2bd3-4bd1-8517-b81629baa837.png)

**Comment by WilliamAntonRohm** [comment]
@nstijepovic -- thank you for clear feedback.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
#reassign @WilliamDAssafMSFT

**Comment by markingmyname** [comment]
Assigned to William based on Synapse info.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @nstijepovic for taking the time to provide this feedback, your suggestions help improve our documentation. This looks like a good opportunity to update the applicability of this article to dedicated SQL pools only. This doc update is in flight. Thanks again!
