### ISSUE TITLE
Article Needs More on Linked Server Between Managed Instance and SQL Server

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#7992]
Needs more information on Managed Instance linked to SQL Server (on-prem and/or VM) - no ability to add to a Trust Group, it would appear for the SQL Server side, so how to use trustservercertificate=false for your connection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7695b6a-e69f-7ee8-6493-d6276d5ea167
* Version Independent ID: 71d085f6-643b-4223-54d7-be831a9b0bf3
* Content: [Linked Servers (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/linked-servers/linked-servers-database-engine?view=sql-server-ver16#azure-sql-managed-instance-linked-server-authentication)
* Content Source: [docs/relational-databases/linked-servers/linked-servers-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/linked-servers/linked-servers-database-engine.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by MashaMSFT** [comment]
Hi @PrometheusRising1 , thanks for contacting Microsoft! My apologies for the delay in response - would you mind clarifying your topology? Are you creating a linked server between Azure SQL Managed Instance and SQL Server? Or are you using the [Managed Instance link feature](https://learn.microsoft.com/azure/azure-sql/managed-instance/managed-instance-link-feature-overview?view=azuresql).

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @PrometheusRising1 , thanks for contacting Microsoft! Since it's been some time since we've heard from you, we're going to assume that your issue was addressed and close out this Git Issue. However, if you still need assistance, please feel free to comment. 

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
