### ISSUE TITLE
CREATE TABLE - column-level PRIMARY KEY and UNIQUE - incorrect documentation

### ISSUE THREAD

**Issue by OleksiiKovalov** [MicrosoftDocs/sql-docs#7996]
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver16&source=docs

documentation for column level PK/UQ states that there is no column that can be specified 
![image](https://user-images.githubusercontent.com/26844170/186716074-26443635-7085-465e-a94a-75fc01ba53c4.png)
However, I can specify columns - both the same and even another column from the table - as shown in the example
and of course, this column name is checked for existence in the table.
Several columns also can be specified
the same is for column-level unique constraint

**UPDATED** actually created PK/UQ contains all specified columns and looks just like table-level PK/UQ

```
drop table if exists dbo.DemoTable
go
create table dbo.DemoTable
(
	id int not null primary key clustered(OtherColumn,id)
	,OtherColumn int
)
go

select sc.name
from sys.indexes i inner join sys.key_constraints kc on i.index_id = kc.unique_index_id and i.object_id = kc.parent_object_id
		inner join sys.index_columns ic on i.object_id = ic.object_id 
				inner join sys.columns sc on i.object_id = sc.object_id and sc.column_id = ic.column_id
where kc.parent_object_id = object_id('dbo.Demotable'); 
```
![image](https://user-images.githubusercontent.com/26844170/186717166-8d39b73d-6de7-499c-ace1-152bf119e0ec.png)

```
drop table if exists dbo.DemoTable
go
create table dbo.DemoTable
(
	id int not null unique clustered(OtherColumn,id)
	,OtherColumn int
)
go

select kc.name, sc.name
from sys.indexes i inner join sys.key_constraints kc on i.index_id = kc.unique_index_id and i.object_id = kc.parent_object_id
		inner join sys.index_columns ic on i.object_id = ic.object_id 
				inner join sys.columns sc on i.object_id = sc.object_id and sc.column_id = ic.column_id
where kc.parent_object_id = object_id('dbo.Demotable'); 
```
![image](https://user-images.githubusercontent.com/26844170/186717073-2200d60c-1b99-4f6c-9cee-9826c0a15526.png)

Microsoft SQL Server 2019 (RTM-CU16) (KB5011644) - 15.0.4223.1 (X64) 
	Apr 11 2022 16:24:07 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19044: ) (Hypervisor)

**Comment by WilliamAntonRohm** [comment]
@OleksiiKovalov -- Oleksii, thank you again for your thorough feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by rwestMSFT** [comment]
@OleksiiKovalov May I suggest that you submit PRs, as opposed to opening issues? It would make our lives a little easier in approving changes.

**Comment by WilliamDAssafMSFT** [comment]
Agreed @oleksiiKovalov. Easier to show than tell sometimes. After reviewing this I believe you are correct, the syntax is missing the non-partitioned column syntax. In the future, might be easier for you to [create a Pull Request](https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute) and get the ball rolling on a change yourself, instead of trying to describe it. By opening a pull request, you're collaborating with the author to add changes directly to the documentation. After your PR is merged, GitHub lists you as an article contributor. 

Either way, thanks for your feedback! Closing this issue and will resolve in a future docs update.

**Comment by OleksiiKovalov** [comment]
hi @WilliamDAssafMSFT @rwestMSFT 
English is not the thing in which I'm strong enough but I'll do my best

**Comment by WilliamDAssafMSFT** [comment]
No worries. Someone from the Database Docs team will always review and potentially co-author commits.

**Comment by rwestMSFT** [comment]
I'll second this, @OleksiiKovalov. We prefer PRs because we can refine what you've written, plus you get credit for your contributions.

**Comment by rwestMSFT** [comment]
#reassign:rwestMSFT
