### ISSUE TITLE
Recovery with sp_query_store_consistency_check in an Azure SQL Database

### ISSUE THREAD

**Issue by kimjamia** [MicrosoftDocs/sql-docs#8000]
The page says:
> Starting with SQL Server 2017 (14.x), Query Store can be recovered by executing the sys.sp_query_store_consistency_check stored procedure within the affected database. Query Store must be disabled before you attempt the recovery operation.

However, the following is also mentioned (and this statement is true, I tried):
> Query Store cannot be disabled in Azure SQL Database single database and Elastic Pool.

There's no guidance (even with Azure SQL Database selected from the version dropdown) how to recover the Query Store in an Azure SQL Database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155bfbc5-9c63-32c6-9d06-a9b3cdb4c60e
* Version Independent ID: c854b2de-e509-e320-8151-67d690d486ed
* Content: [Best practices with Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/best-practice-with-the-query-store?view=azuresqldb-current#Verify)
* Content Source: [docs/relational-databases/performance/best-practice-with-the-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/best-practice-with-the-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hi @kimjamia! Thanks for taking the time to file an issue with Microsoft Docs. I believe you have your answer. This is not possible in Azure SQL DB, and should not be necessary. If you are experiencing a corruption or recovery scenario with Azure SQL DB and Query Store, please contact Microsoft Support. Is that the case?

**Comment by kimjamia** [comment]
Thanks for the answer. Yes, a Query Store is reporting readonly_reason 131072 but even after clearing the QS it won't let me change it back to read-write.

**Comment by kimjamia** [comment]
Support instructed me to scale up/down and that seemed to do the trick. After I scaled up, all databases in the Elastic Pool switched to READ_WRITE and remained so after scaling back down. I didn't even have to explicitly try to switch the QS, scaling was all that was needed.

Perhaps it's useful to add this to the documentation?

**Comment by WilliamDAssafMSFT** [comment]
@Kimjamia This has been discussed internally, there are other considerations. Closing this issue now. Glad you were unblocked on this issue and thanks again for creating the issue and providing the info.
