### ISSUE TITLE
property for dropping specific table in sqlpackage.exe

### ISSUE THREAD

**Issue by abhi421** [MicrosoftDocs/sql-docs#8008]
Is there any property  for dropping specific table in sqlpackage.exe 

I have add following properties in my publish report 
/p:DropObjectsNotInSource=True
/p:DoNotDropTables=True

and I want to drop a specific table, is there any way I pass table name and the table get drop from target ?

**Comment by dzsquared** [comment]
There isn't a way to do this with SqlPackage currently without the use of deployment contributors.

You can make feature requests for DacFx/Sqlpackage here: https://github.com/microsoft/dacfx

You can learn more about deployment contributors here: https://github.com/microsoft/dacextensions

#please-close
