### ISSUE TITLE
still using python27

### ISSUE THREAD

**Issue by xmseraph** [MicrosoftDocs/sql-docs#8011]
please change it to python3, can't believe the documents still reference python2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95454cf7-3691-e4eb-d8c6-b7986fcd490b
* Version Independent ID: 84a42231-fc84-e831-a9a8-18cb86f3cfb9
* Content: [Step 1: Configure pyodbc Python environment - Python driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/python/pyodbc/step-1-configure-development-environment-for-pyodbc-python-development?source=recommendations&view=sql-server-ver16)
* Content Source: [docs/connect/python/pyodbc/step-1-configure-development-environment-for-pyodbc-python-development.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/python/pyodbc/step-1-configure-development-environment-for-pyodbc-python-development.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@xmseraph -- thank you for your suggestion.

@David-Engel -- please look into this issue.

**Comment by David-Engel** [comment]
Done. The change will be reflected tomorrow around 10:30 AM PST.

#please-close
