### ISSUE TITLE
Tip is incorrect

### ISSUE THREAD

**Issue by xxx** [MicrosoftDocs/sql-docs#8012]
On the page it mentions

> Tip

> You can omit the password on the command-line to be prompted to enter it.

This does not work.

```
mssql@sql1:/$ /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P
Sqlcmd: '-P': Missing argument. Enter '-?' for help.
mssql@sql1:/$
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by amvin87** [comment]
Sorry for the confusion, but what that statement meant is that you run the command like this
mssql@sql1:/$ /opt/mssql-tools/bin/sqlcmd -S localhost -U SA 

then you should be prompted to enter the password for 'SA' . Let me know if, you see any issues.
