### ISSUE TITLE
Re: F. Importing fixed-length or fixed-width fields

### ISSUE THREAD

**Issue by DutchHarry** [MicrosoftDocs/sql-docs#8013]
Re: F. Importing fixed-length or fixed-width fields
https://docs.microsoft.com/en-us/sql/relational-databases/import-export/xml-format-files-sql-server?view=sql-server-ver16#ImportFixedFields

The example format file will work when the data is padded out to the correct length, that is each line has the correct length plus \r\n

The following should also work if the length of the last column isn't padded.

```
<?xml version="1.0"?>  
<BCPFORMAT  
       xmlns="http://schemas.microsoft.com/sqlserver/2004/bulkload/format"  
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">  
  <RECORD>  
    <FIELD ID="1" xsi:type="CharFixed" LENGTH="10"/>  
    <FIELD ID="2" xsi:type="CharTerm" TERMINATOR="\r\n"/>  
  </RECORD>  
  <ROW>  
    <COLUMN SOURCE="1" NAME="C1" xsi:type="SQLINT" />  
    <COLUMN SOURCE="2" NAME="C2" xsi:type="SQLINT" />  
  </ROW>  
</BCPFORMAT>  
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb0962c3-2d6a-9120-c5b7-70d2fb93cd23
* Version Independent ID: e1a70d77-ace8-1a16-bbc8-ccd7acde5880
* Content: [XML Format Files (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/xml-format-files-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/import-export/xml-format-files-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/xml-format-files-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@DutchHarry -- thank you for your feedback.

@rwestMSFT -- please look into this issue.

**Comment by rwestMSFT** [comment]
@DutchHarry Thanks for your contribution.

Is the example in the article wrong? It's not clear from your comment what wording needs to change.

If you're suggesting an alternative solution to the same example, then it is unlikely that it will be added, because we have a really big backlog.

I look forward to hearing from you.

**Comment by rwestMSFT** [comment]
@DutchHarry I'm closing this issue for now. You are still welcome to provide clarification when you get a chance. Thanks!

**Comment by rwestMSFT** [comment]
#please-close
