### ISSUE TITLE
Incorrect parameter in Examples

### ISSUE THREAD

**Issue by ri-ka-tang** [MicrosoftDocs/sql-docs#8022]
I think an incorrect property is used in the `# example publish using short form parameter names, skips schema validation` example, the property ` /p:VerifyExtraction=False` should be ` /p:VerifyDeployment=False`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c457408b-20fb-a617-0bb0-0e73d4f703c5
* Version Independent ID: 9a420183-7d44-3d71-1eba-f66bb757bb65
* Content: [SqlPackage Publish - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-publish?view=sql-server-ver15)
* Content Source: [docs/tools/sqlpackage/sqlpackage-publish.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage/sqlpackage-publish.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
#assign:dzsquared
