### ISSUE TITLE
Unclear points in article

### ISSUE THREAD

**Issue by enevoj** [MicrosoftDocs/sql-docs#8028]
There are several points which are unclear to me.

> At this point SQL Server should run normally. However Microsoft recommends also adjusting the registry entry at HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\instance_ID\Setup, where instance_ID is like MSSQL13.MSSQLSERVER. In that hive, change the SQLDataRoot value to the new path.

The default value for SQLDataRoot is **C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER**. The master db is in a sub-folder, **DATA**, which is also the default DATA directory. So the value does not directly point to the location of the master db, but rather the parent directory. The Microsoft article covers moving the master db to a new example path, **E:\SQLData**. It mentions to change the SQLDataRoot registry value to the new path. This suggests changing SQLDataRoot to **E:\SQLData**, as that is the new path. However it doesn't make sense, shouldn't it be set to **E:**, which is the parent directory to the directory containing the master db?
I've read several alternative blog posts.
1. https://itech-blog.com/how-to-move-master-database-files-in-sql-server/
2. https://www.mssqltips.com/sqlservertip/6883/sql-server-move-database-files-for-master/

In (1) the author moves master db to **F:\MSSQL\DATA** and sets SQLDataRoot to **F:\MSSQL**.
In (2) the author moves master db to **C:\MSSQL\SystemDatabases** and sets SQLDataRoot to **C:\MSSQL\SystemDatabases**.
In (2) there are several readers posting responses to the article requesting clarification on this.

From this it seems there is some misunderstanding in the community and it would be great if the article could be updated to make this very clear.

> Change the SQL Server Agent log path. If you do not update this path, SQL Server Agent will fail to start.

Why would it fail to start? The only thing that has changed is that the system db files have been moved. The existing log path still exists, with the same permissions, nothing has changed in that respect. In fact after moving the system db files to another drive, in my experience, SQL Agent starts perfectly fine, no errors shown in the agent log. Could this be clarified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9423e4-0573-7564-3f58-2a8df9a11d9f
* Version Independent ID: 5b88aa32-b6f7-e8eb-806f-fd331ed43133
* Content: [Move System Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/move-system-databases?view=sql-server-ver16&source=docs)
* Content Source: [docs/relational-databases/databases/move-system-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/move-system-databases.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @enevoj for contacting Microsoft with feedback about our product documentation and taking the time to put these questions together. 

1) Re: the registry key, let me confirm with the product group but I believe this is only necessary in some scenarios and not all situations in which the `master` database is changed. I also agree this part of the doc could be clearer and provide a distinct example. 
2) "Why would it fail to start?" This answer is made clear in the section in which those instructions exist, in the scenario: "If you have moved all of the system databases to a new drive or volume or to another server with a different drive letter, make the following updates..." It only applies in that scenario. The Agent log must exist at the time of startup.

It could take from a few business days to a few weeks to look further into this with the product team and decide on how to address. We'll contact you if we need further information, and you'll receive an email message each time we mention you in a comment.

**Comment by enevoj** [comment]
Thanks @WilliamDAssafMSFT for your quick response. 

Regarding question 2, hmm let me see...
I'll provide further context to my question as it's still not falling into place for me.  

Considering that the scenario specifically is, if all of the system databases (master, model, msdb, tempdb) have been moved to a new location (i.e. a non-default location), how _specifically_ does that result in SQL Agent failing to start? What is it about this procedure that ultimately causes the SQL Agent to fail to start?
Given that;
1. The agent log is a separate file altogether from the databases. 
2. The agent log resides in its own location accessible to SQL Server. 
3. The location exists. 
4. SQL Server still has permissions to the location.

_What is it about this situation that would stop SQL Agent from starting?_ 

It's like saying, for example, if you paint your car green then you must only enter via the passenger side otherwise the car will no longer start. And I ask why would the car no longer start without entering via the passenger side? And you seem to be saying, the reason is clearly explained; the reason is because you painted your car green. But it's not really explaining it.

In my experience, having just moved all of the system databases to non-default locations (different drives) on 4 servers, I've not needed to alter the location of the SQL Agent log, as SQL Agent has started successfully each time, with no errors. But I would like to understand more about this.

**Comment by PiJoCoder** [comment]
I agree that SQL Agent path has no bearing on the moved database file location.

**Comment by WilliamDAssafMSFT** [comment]
Thanks for your patience @enevoj. I've confirmed with the product engineer group that this doc is correct. We will add more clarification to specifically verify the paths of **SQLDataRoot** and **SQLAGENT.OUT** files are still valid. If you have moved all of the system databases to a new volume or have migrated to another server with a different drive letter, and the path does not exist in either case, we recommend changing it. Whether or not the files exist in a default or non-default path is not really the concern. Some of the ways these invalid paths could cause problems are in future patching where paths in the registry or configuration settings are assumed to be valid.
