### ISSUE TITLE
Typo in title in dropdown menu

### ISSUE THREAD

**Issue by acmds** [MicrosoftDocs/sql-docs#8034]
Hi Team,

I am from the Azure CXP team and just spotted an issue with the title of this article that shows in the dropdown menu on the left. I believe it should say "Explore Azure SQL Resources" instead of "Explorer Azure SQL Resources".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4f0e47-7264-41fa-bf83-55240e6a0e79
* Version Independent ID: a933d5da-0579-cd95-1051-95398e605563
* Content: [Explore Azure SQL resources with Azure Resource Explorer - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/azure-resource-explorer?view=sql-server-ver16)
* Content Source: [docs/azure-data-studio/azure-resource-explorer.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/azure-resource-explorer.md)
* Product: **azure-data-studio**
* GitHub Login: @yanancai
* Microsoft Alias: **yanacai**

**Comment by WilliamAntonRohm** [comment]
@acmds -- thank you for spotting this.  I am updating the table of contents.
