### ISSUE TITLE
The SSDT Release Notes article is incorrectly replaced by article on SSIS

### ISSUE THREAD

**Issue by daiplusplus** [MicrosoftDocs/sql-docs#8036]
1. I was looking for the current release notes for SSDT in VS2019 to see if there's an update that adds support for SQL Server 2022 with Compatibility Level 160.
   * Because my current SSDT install doesn't support `IS DISTINCT FROM` which is added in SQL Server 2022, y'see.
1. Searching for "ssdt 2019 release notes" in Google returns this page ( https://docs.microsoft.com/en-us/sql/ssdt/release-notes-ssdt ) which has a disclaimer saying the page is for VS2017/SSDT2017 and links to another page for VS2019/SSDT2019 Release Notes.
   * The broken link is where it says "Release notes updates for SSDT 2019 and later are now listed under [Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/whats-new-visual-studio-docs)."
   - [ ] **Problem 1**: This link goes to the "What's new in Visual Studio **docs**" page, not the "What's new in Visual Studio" page.
1. With some guesswork I surmised the VS2019/SSDT2019 release notes would be located at this URI: https://docs.microsoft.com/en-us/sql/ssdt/release-notes-ssdt-2019
   - [ ] **Problem 2**: The page at https://docs.microsoft.com/en-us/sql/ssdt/release-notes-ssdt-2019 _is completely different_: despite the URI name "release-notes-ssdt-2019" the page is about SSIS Extensions, not SSDT.
1. ...and I still can't find the actual SSDT 2019 release notes.
- [ ] **Problem 3**: So, where are the current SSDT 2019 release notes?

(Also, most documentation links and Help buttons within VS/SSDT are broken, for example the prominent "Learn more about Azure SQL Database versions" link under Project Properties just takes you through this redirect chain:

1. "Learn more about Azure SQL Database versions"
1. to `https://go.microsoft.com/fwlink/?LinkId=519360`
1. to `https://azure.microsoft.com/documentation/services/sql-database`
1. to `https://azure.microsoft.com/en-us/documentation/services/sql-database/`
1. to `https://docs.microsoft.com/en-us/azure/azure-sql/?view=azuresql` ... which is just the Azure SQL documentation homepage, so this just wastes the user's time).

**Comment by WilliamAntonRohm** [comment]
@Jehoel -- Dai, thank you for your thorough feedback.

@chugugrace -- Grace, please look into this issue.

**Comment by dzsquared** [comment]
I apologize for the broken link to the Visual Studio release notes - https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes?view=vs-2022

To answer your specific question about SQL 2022 support in Visual Studio - it hasn't landed just yet.  The SQL projects support for SQL 2022 should land between now and when SQL 2022 GAs.



I would expect this page to be more clearly labeled as the SSIS release notes for SSDT.

**Comment by rwestMSFT** [comment]
@dzsquared Is there anything else we need to do with this issue, or can it be closed?

**Comment by rwestMSFT** [comment]
We have updated the articles in question, and the new content will be available in the next day or so.
