### ISSUE TITLE
SSDT data comparison reports wrong results

### ISSUE THREAD

**Issue by umbersar** [MicrosoftDocs/sql-docs#8038]
If I try to compare to 2 databases using SSDT, I get incorrect results. The same 2 databases when compared with Red Gate's 'SQL Data Compare' tool shows correct results. Please see attached snapshots, diff1.png and diff2.png. 

1. diff1.png shows SSDT comparison and it incorrectly reports that there are 108 updated rows in Archive_samples table. That is wrong as these are new rows.
2. diff2.png shows Red Gate's 'SQL Data Compare' tool and it correctly reports 108 rows in Archive_samples table as new additions.

It seems like a bug in SSDT data comparison tool.

SSDT data comparison:
![diff1](https://user-images.githubusercontent.com/11863217/188372827-f7f834de-6082-4ba9-ab5a-477a242989c7.PNG)

Red Gate 'SQL Data Compare':
![diff2](https://user-images.githubusercontent.com/11863217/188373208-e8c57b16-c63d-4208-9e97-b0bcca03d5de.PNG)

**Comment by WilliamAntonRohm** [comment]
@umbersar -- Ramneek, thank you for your research and feedback.  Please add this here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
