### ISSUE TITLE
;l

### ISSUE THREAD

**Issue by hoanganh13032k03** [MicrosoftDocs/sql-docs#8043]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34db833-bfe2-2c31-303c-7da4200e1e94
* Version Independent ID: f34db833-bfe2-2c31-303c-7da4200e1e94
* Content: [SQL Server 2019 Release Notes - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-2019-release-notes?source=recommendations&view=sql-server-ver15)
* Content Source: [docs/sql-server/sql-server-2019-release-notes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/sql-server-2019-release-notes.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
