### ISSUE TITLE
SQL Server NUMA related document missing for SQL Server 2022

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [MicrosoftDocs/sql-docs#8049]
There are some really good SQL Server NUMA related documents for older versions of SQL Server:
https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms178144(v=sql.105)?redirectedfrom=MSDN

But I can't find them for SQL Server 2022. Is this intentional or just an omission?

**Comment by WilliamAntonRohm** [comment]
@0x7FFFFFFFFFFFFFFF -- thank you for your feedback and question.  Please see this article:
- [Understand non-uniform memory access](https://docs.microsoft.com/en-us/sql/relational-databases/memory-management-architecture-guide#understand-non-uniform-memory-access)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
