### ISSUE TITLE
SSMS data-tier features missing but mentioned in documentation

### ISSUE THREAD

**Issue by czb182** [MicrosoftDocs/sql-docs#8050]
I have SSMS 18.12.1

I dont see Object Explorer -> Management\Data-tier Applications
-OR-
Utility Explorer

Are these just removed features, and documentation hasn't been updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63ddb5d-2b77-bdeb-e764-ad84d18fe76c
* Version Independent ID: 01786943-f591-d8f9-f1db-3867a787198c
* Content: [Monitor Data-tier Applications - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/monitor-data-tier-applications?view=sql-server-ver16)
* Content Source: [docs/relational-databases/data-tier-applications/monitor-data-tier-applications.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/monitor-data-tier-applications.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by dzsquared** [comment]
#assign:erinstellato-ms

**Comment by rwestMSFT** [comment]
Related to https://github.com/MicrosoftDocs/sql-docs/issues/8255.

**Comment by rwestMSFT** [comment]
@czb182 These features were removed from SSMS in version 17, if memory serves. I am closing this issue as resolved.
