### ISSUE TITLE
HOMEBREW_NO_ENV_FILTERING is deprecated and has been removed

### ISSUE THREAD

**Issue by dbartz** [MicrosoftDocs/sql-docs#8052]
The HOMEBREW_NO_ENV_FILTERING has been removed and the commands using this flag no longer work.

Reference:
https://brew.sh/2022/09/07/homebrew-3.6.0/

From the link:
Environment variables needed in formulae or casks need to have a HOMEBREW_ prefix to be passed through and then reassigned e.g. ENV["FOO"] = ENV["HOMEBREW_FOO"].

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c0de6fb-19ae-ff6f-8e73-ce66fa94bd64
* Version Independent ID: 34edd099-f4fe-4ac3-cdd4-abc87b35270b
* Content: [Install the Microsoft ODBC driver for SQL Server (macOS) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver16)
* Content Source: [docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@dbartz -- Daniel, thank you for this update.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
The brew formulas and the instructions have been updated.

Thanks,
David

#please-close
