### ISSUE TITLE
Available GDR for SQL 2016SP3 is missing from the Latest updates table

### ISSUE THREAD

**Issue by Kentix** [MicrosoftDocs/sql-docs#8055]
In the "Latest updates" table, the row for SQL Server 2016 SP3 should indicate that a GDR is applicable. The GDR which is valid is KB5014355 and was derived from https://support.microsoft.com/en-us/topic/kb5016394-cumulative-update-17-for-sql-server-2019-3033f654-b09d-41aa-8e49-e9d0c353c5f7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1353d4d-3899-d6cf-e44f-8536c7828335
* Version Independent ID: de0210cf-386a-f8c8-1157-40cea207ed4b
* Content: [Latest updates for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/latest-updates-for-microsoft-sql-server?view=sql-server-ver16)
* Content Source: [docs/database-engine/install-windows/latest-updates-for-microsoft-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/latest-updates-for-microsoft-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @SrinivasSQLMS
* Microsoft Alias: **skandi**

**Comment by WilliamAntonRohm** [comment]
@Kentix -- thank you for bringing this to our attention.

@SrinivasSQLMS -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
@kentix,

when I look at https://docs.microsoft.com/sql/database-engine/install-windows/latest-updates-for-microsoft-sql-server I see that SQL Server 2016 SP3 includes the GDR. 

CC: @harveymorams  - is there an updated needed here? 

![image](https://user-images.githubusercontent.com/15928587/189724729-64500389-18d6-4142-9200-1075de9219bd.png)

**Comment by Kentix** [comment]
@***@***.***

On second look, I think it’s fine. I think I was looking for “GDR” within the table and fixated on its existence in the CU column as with some of the other line items. Somehow I missed the the entire GDR column. This issue can be closed out, apologies for the noise!

On Sep 12, 2022, at 2:04 PM, Mike Ray ***@***.***> wrote:

﻿

@Kentix<https://github.com/Kentix>,

when I look at https://docs.microsoft.com/sql/database-engine/install-windows/latest-updates-for-microsoft-sql-server I see that SQL Server 2016 SP3 includes the GDR.

CC: @harveymorams<https://github.com/harveymorams> - is there an updated needed here?

[image]<https://user-images.githubusercontent.com/15928587/189724729-64500389-18d6-4142-9200-1075de9219bd.png>

**Comment by WilliamAntonRohm** [comment]
#please-close
