### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by abde115** [MicrosoftDocs/sql-docs#8064]
[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des défis GitHub.*

* ID: 3f0bcec3-7063-e556-e089-f6df587e2f03
* Version Independent ID: 801bc1d0-3453-9fba-2d82-d913ca90fdc8
* Content: [Installation guidance for SQL Server on Linux - SQL Server](https://docs.microsoft.com/fr-fr/sql/linux/sql-server-linux-setup?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-setup.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
