### ISSUE TITLE
Documenation improvement, clarifying a few things for customers setting up DAG 

### ISSUE THREAD

**Issue by krishnamsft20** [MicrosoftDocs/sql-docs#8069]
I recently worked on a case where customer was setting up Distributed AG between Azure and On-Prem environment. On Azure side AG there were two replicas VM1 and VM2. On the On-Prem AG there was only one replica VM1.

Here are the things I think we need to clarify for customers. 
1. If you are setting up firewall rules for network connectivity. You need to have allow rules for following
Besides 5022 and 1433, you need to allow (dynamic) for traffic initiating from other side. Traffic coming in from other side will have source port as dynamic port destination port as 5022 or 1433. Need to account for that while setting up port rule on devices like Palo alto. if customer only allow 5022 to 5022 and 1433 to 1433, DAG will not work. Need more like this:

any:5022 // 5022:any
and
any:1433 // 1433:any

2. If you are using automatic seeding for DAG, you need to have matching drive paths between Global primary and Forwarder replica
We have separate documentations for automatic seeding (saying you need to have identical paths) and DAG (saying you do not need identical paths). But for automatic seeding with DAG, we need identical paths. This needs to be clarified in this document.

3. You will need grant create any database for secondary ag on forwarder replica
- We have documentation saying, on the secondary AG, you only need to run "Alter Availability group AG2 grant create any database" on the secondary replica. But for one replica AG on the secondary AG for DAG, we need to run this on the primary or automatic seeding would fail with error 20/error 3.
If we can clarify these, customers would run into less troubles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab92d64a-bdc3-67a0-60f8-c551b85ead4b
* Version Independent ID: e8ed4dfb-c487-e663-e77f-f205415319e4
* Content: [Configure a distributed availability group - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-distributed-availability-groups?view=sql-server-ver16&tabs=automatic)
* Content Source: [docs/database-engine/availability-groups/windows/configure-distributed-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/configure-distributed-availability-groups.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@krishnamsft20 -- thank you for your thorough feedback.

@MashaMSFT -- please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @krishnamsft20 , thanks for contacting Microsoft! The documentation that you're referring to is intended for on-premises environments. Please review the distributed ag documentation for SQL VM, starting here: https://learn.microsoft.com/azure/azure-sql/migration-guides/virtual-machines/sql-server-distributed-availability-group-migrate-prerequisites?view=azuresql

I'll update the existing article to make it clear that this is not intended for availability groups with Azure. During this time, Git Issues have been deprecated as we've transitioned to a new feedback system. I've added your suggestion to our internal backlog (#250004) that we will continue addressing as priorities and resources allow.

We use your feedback to improve our documentation, so we are grateful for your input, and your time. I apologize for any inconvenience, and thank you for your patience and understanding. 

Masha from the SQL Docs team
#please-close
