### ISSUE TITLE
Issue with !INCLUDE in Recommended content

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/sql-docs#8080]
Hello Docs team,
 
This article has an issue with **[!INCLUDE[sssql22-md](../includes/sssql22-md.md)]** in the Recommended content. As I made some mistakes with includes in another contribution, I need to investigate how to properly contribute to those. 
Other than that, I'm not sure if this is something that I can contribute to as the GitHub page ends with Next steps section, and I don't see the Recommended content in there.
 
Thx for reviewing, and please feel free to educate me as I like to do some more contributions starting this FY. 
 
Kind regards, inge
 
![image](https://user-images.githubusercontent.com/40343254/190262392-8a5c7dd2-b5cc-456d-a8a7-c5b588fe11c0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7a9f405-e1e5-280d-d902-71d5061f08e7
* Version Independent ID: f7a9f405-e1e5-280d-d902-71d5061f08e7
* Content: [SQL Server 2022 Release Notes - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-2022-release-notes?view=sql-server-ver16)
* Content Source: [docs/sql-server/sql-server-2022-release-notes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/sql-server-2022-release-notes.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@ingebeumer -- Inge, thank you for catching this.  I am also unsure where "Recommended content" is brought into an article, and am investigating.

**Comment by ingebeumer** [comment]
Hi @WilliamAntonRohm,
Just came across [SQL Assessment API](https://learn.microsoft.com/en-us/sql/tools/sql-assessment-api/sql-assessment-api-overview?view=sql-server-ver16) article and this one also has an issue with some !INCLUDEs in the Recommended content.

![image](https://user-images.githubusercontent.com/40343254/199968265-10a3a64e-ac52-46f6-913c-9ea24ad0ec06.png)

**Comment by WilliamAntonRohm** [comment]
Hi @ingebeumer -- thank you for adding that!

**Comment by ingebeumer** [comment]
Hi @WilliamAntonRohm,
Do you want to keep this issue open for your investigation where the 'Recommended content' is brought into an article? I see that both articles I mentioned don't have the issue anymore.

**Comment by WilliamAntonRohm** [comment]
@ingebeumer -- Inge, thank you for following up!
