### ISSUE TITLE
Proposed Revision for SQL ML Doc - Apply CU updates on existing instance.

### ISSUE THREAD

**Issue by ronking-zhu** [MicrosoftDocs/sql-docs#8086]
[Enter feedback here]
The statement of the "This may result in unexpected behavior or errors." in the "Apply updates" -> "Existing installation" is not very accurate and it's not very effcient to get to this noticing when searching the Machine Learning installation errors.  And this part has already causing multiple CSS cases from high influence customer. 
https://docs.microsoft.com/en-us/sql/machine-learning/install/sql-machine-learning-services-windows-install?view=sql-server-2017#apply-updates 

We proposal to change the 2 parts for the same page:
**---part 1---**
If you have added Machine Learning Services to an existing SQL Server instance and have previously applied a Cumulative Update (CU), the versions of your database engine and the Machine Learning Services feature might be different. This may result in unexpected behavior or errors. 
**To**
If you have added Machine Learning Services to an existing SQL Server instance and have previously applied a Cumulative Update (CU), the versions of your database engine and the Machine Learning Services feature might be different. This may result in unexpected behavior or errors because the launchpad.exe and the sqlservr.exe might have different versions. The behavior like unable to start the launchpad service and launchpad might report error 0xc0000409 in the Event Viewer. For more details, check the Windows Event Viewer log. 

**---part 2---**
3. Run the installation of the Cumulative Update (CU) and follow the instructions to install the CU for Machine Learning Services.
**To**
3. Run the installation of the Cumulative Update (CU) and follow the instructions to install the CU for Machine Learning Services again.   Select the existing instance that have the ML services. The upgrade status will show **Incompletely Installed** from the landing page of the patch. Click Next and follow the instructions to install the CU for Machine Learning Services.

---- from Rodel Nagales findings . 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10a1a190-9335-9d2d-c664-9b91c9be8cf0
* Version Independent ID: c9e23f38-b817-bf96-453a-3c7171501dd3
* Content: [Install on Windows - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/machine-learning/install/sql-machine-learning-services-windows-install?view=sql-server-2017#apply-updates)
* Content Source: [docs/machine-learning/install/sql-machine-learning-services-windows-install.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/install/sql-machine-learning-services-windows-install.md)
* Product: **sql**
* Technology: **machine-learning-services**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@ronking-zhu -- Rozms, thank you for your thorough feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Hi @ronking-zhu, thanks for taking the time to create this feedback. Looks like a good add. Would you like to submit a pull request to our open source docs and be credited with adding this content? http://aka.ms/editsqldocs By opening a pull request, you're collaborating with the author to add changes directly to the documentation. I'll review the content before merging. After the updated article is published, GitHub lists you as an article contributor. If you're prefer not, we can implement the changes. Either way, thanks for your feedback!

**Comment by ronking-zhu** [comment]
Thank you William. Created the pull request. Kindly review.

**Comment by WilliamDAssafMSFT** [comment]
I see https://github.com/MicrosoftDocs/sql-docs/pull/8100/. Will review
