### ISSUE TITLE
DateTime data-masking not working with SQL Server SSDT?

### ISSUE THREAD

**Issue by Thorium** [MicrosoftDocs/sql-docs#8087]
A database column
```sql
[DateOfBirth] DATE MASKED WITH (FUNCTION = 'datetime("D")') NOT NULL,
```
fails SQLPROJ (SSDT) compilation for:
`SQL70630: The data masking function provided for column DateOfBirth is invalid. `

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9408bf-18b5-339f-cd25-6a3024be3243
* Version Independent ID: eea4b8dc-5598-b7e6-e01a-902d5ca1f96d
* Content: [Dynamic Data Masking - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/dynamic-data-masking?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/dynamic-data-masking.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/dynamic-data-masking.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@Thorium -- Tuomas, thank you for your example and feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

cc @vanmsft for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
