### ISSUE TITLE
reference links for "Database Engine Performance in an Azure Virtual Machine" are broken

### ISSUE THREAD

**Issue by CarlosGzz-SQL** [MicrosoftDocs/sql-docs#8090]
[Enter feedback here]
while checking the link for each one of the "database engine performance in an azure VM" all of them lead you to an asp.net reference page. 
https://learn.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-6.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3adb3e3c-6398-7df7-ff9f-472ccf9f0f9e
* Version Independent ID: 616ee859-3bf5-ac5f-3a30-b7559762e9fd
* Content: [Performance Center - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/performance/performance-center-for-sql-server-database-engine-and-azure-sql-database?view=sql-server-ver15)
* Content Source: [docs/relational-databases/performance/performance-center-for-sql-server-database-engine-and-azure-sql-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/performance-center-for-sql-server-database-engine-and-azure-sql-database.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
You're absolutely correct, @carlosgzz-SQL, thanks for taking the time to provide this feedback, your suggestions help improve our documentation. A doc update is in flight to correct these links.
