### ISSUE TITLE
Please check the missing in T-SQL Statement

### ISSUE THREAD

**Issue by huyvhd293** [MicrosoftDocs/sql-docs#8093]
Please replace this T-SQL
`
-- creates a WMI event alert that retrieves all event properties for any ALTER_TABLE event that occurs on table AdventureWorks2012.Sales.SalesOrderDetail  
-- This example assumes that the message 54001 already exists.  
USE msdb ;  
GO  

EXEC dbo.sp_add_alert  
    @name = N'Test Alert 2',  
    @message_id = 54001  
    @notification_message = N'Error 54001 has occurred on the Sales.SalesOrderDetail table on the AdventureWorks2012 database.',  
    @wmi_namespace = '\\.\root\Microsoft\SqlServer\ServerEvents\,  
    @wmi_query = N'SELECT * FROM ALTER_TABLE   
WHERE DatabaseName = 'AdventureWorks2012' AND SchemaName = 'Sales'   
    AND ObjectType='Table' AND ObjectName = 'SalesOrderDetail'';  
GO`

by

`-- creates a WMI event alert that retrieves all event properties for any ALTER_TABLE event that occurs on table AdventureWorks2012.Sales.SalesOrderDetail  
-- This example assumes that the message 54001 already exists.  
USE msdb ;  
GO  

EXEC dbo.sp_add_alert  
    @name = N'Test Alert 2',  
    @message_id = 54001, 
    @notification_message = N'Error 54001 has occurred on the Sales.SalesOrderDetail table on the AdventureWorks2012 database.',  
    @wmi_namespace = '\\.\root\Microsoft\SqlServer\ServerEvents\',  
    @wmi_query = N'SELECT * FROM ALTER_TABLE   
WHERE DatabaseName = ''AdventureWorks2012'' AND SchemaName = ''Sales''   
    AND ObjectType=''Table'' AND ObjectName = ''SalesOrderDetail''';  
GO `

Because missing the comma
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6278957-5256-5796-d248-707f4619c08d
* Version Independent ID: b711b2b3-b20f-d307-10fb-7cd4c75c32b1
* Content: [Create a WMI Event Alert - SQL Server Agent](https://learn.microsoft.com/en-us/sql/ssms/agent/create-a-wmi-event-alert?view=sql-server-ver16)
* Content Source: [docs/ssms/agent/create-a-wmi-event-alert.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/create-a-wmi-event-alert.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by rwestMSFT** [comment]
@huyvhd293 Thank you for your feedback. The article will be refreshed and published in the next day or so, and this issue will automatically close when the article is merged.

#reassign:rwestMSFT
