### ISSUE TITLE
Index JSON data available on Azure SQL?

### ISSUE THREAD

**Issue by ioemat** [MicrosoftDocs/sql-docs#8115]
The page says "Applies to: SQL Server 2016 (13.x) and later"  - does this mean that the functionality is not available on Azure SQL?
If so, is there a roadmap to make it avaiable?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 647be77d-8f01-6d16-7c7f-9a539199abc1
* Version Independent ID: 0ea0cc4f-b66e-e1ad-5a08-01a8b50aab41
* Content: [Index JSON data - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/json/index-json-data?view=sql-server-ver16)
* Content Source: [docs/relational-databases/json/index-json-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/index-json-data.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by jovanpop-msft** [comment]
It is applicable to Azure SQL DB. This is an error in the docs.

@MikeRayMSFT why the file /MicrosoftDocs/sql-docs/live/docs/includes/applies-to-version/sqlserver2016-asdb.md contains just:

      [!INCLUDE [Applies to](../../includes/applies-md.md)] [!INCLUDE [SQL Server 2016](_ss2016.md)] and later 

and doesn't contain the text that is mentioning Azure SQL Database? The error is in included text.

**Comment by MikeRayMSFT** [comment]
This has been fixed. Thanks.
