### ISSUE TITLE
SQL Bug in examples

### ISSUE THREAD

**Issue by SQLeap** [MicrosoftDocs/sql-docs#8118]
Section 5

The SQL example contains an extra ) that causes the statement to fail. 

Please correct

Thanks in Advance
Eric

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9408bf-18b5-339f-cd25-6a3024be3243
* Version Independent ID: eea4b8dc-5598-b7e6-e01a-902d5ca1f96d
* Content: [Dynamic Data Masking - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/dynamic-data-masking?view=sql-server-ver16#granular)
* Content Source: [docs/relational-databases/security/dynamic-data-masking.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/dynamic-data-masking.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Thanks for catching this, @SQLeap! I'm updating the doc and it should go live later today. We really appreciate your help!
