### ISSUE TITLE
Indicate that Parameter Sensitive Plan Optimization is available in Azure SQL?

### ISSUE THREAD

**Issue by tmenier** [MicrosoftDocs/sql-docs#8120]
According to [this matrix](https://learn.microsoft.com/en-us/sql/relational-databases/performance/intelligent-query-processing?source=recommendations&view=sql-server-ver16#sql2022), Parameter Sensitive Plan Optimization is available in Azure SQL starting with compatibility level 150. Assuming that's correct, shouldn't this be indicated on the top of the page describing the feature? Currently that just says:

> **Applies to**: SQL Server (Starting with SQL Server 2022 (16.x) Preview)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d912455d-8d09-0b74-0f8e-9de4d8777b26
* Version Independent ID: d912455d-8d09-0b74-0f8e-9de4d8777b26
* Content: [Parameter Sensitive Plan optimization - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/performance/parameter-sensitivity-plan-optimization?view=sql-server-ver16#feedback)
* Content Source: [docs/relational-databases/performance/parameter-sensitivity-plan-optimization.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/parameter-sensitivity-plan-optimization.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @thesqlsith
* Microsoft Alias: **derekw**

**Comment by thesqlsith** [comment]
Thank you for the comment.  The matrix that you are referring to only applies to SQL Server, which is how we delineate between the Azure SQL Database products (which would include SQL DB, MI, Synapse, etc.) and the on premises or VM based product in our documentation.  PSP will be available in public preview form for Azure SQL DB and MI soon.

We will update the matrix and the documentation for PSP to reflect that database compatibility level 160 is required, however.  Thanks again for bringing this to our attention.

**Comment by tmenier** [comment]
Thanks for the quick reply. Maybe it's the 2nd column header of that matrix that's either confusing or just wrong?

**Supported in Azure SQL Database and Azure SQL Managed Instance**

Sounds like you're saying PSP isn't available in Azure SQL DB at compat level 150 as indicated. But it appears I can go to 160 there, are you saying even at 160 PSP isn't actually available in Azure SQL DB?

**Comment by thesqlsith** [comment]
"Sounds like you're saying PSP isn't available in Azure SQL DB at compat level 150 as indicated. But it appears I can go to 160 there, are you saying even at 160 PSP isn't actually available in Azure SQL DB?"

Correct.  PSP is not yet available in public preview form in Azure yet (it is coming however).  Also, the page did have another error that I have just corrected.  PSP will only be available with db compat 160, not 150.  

We do apologize for the confusion that this has caused.  The documentation updates should be reflected later today or tomorrow at the latest.

**Comment by tmenier** [comment]
Thanks...very impressed with your response time! :)

**Comment by thesqlsith** [comment]
No problem.  As an F.Y.I., as you are aware, we are constantly deploying things into Azure.  At the moment, we are currently rolling out some newer bits to Azure, so depending on where you are in the world, you may start to see some of the newer IQP features light up before we can officially announce them :-).  The team is trying to get the timing right, however.

**Comment by tmenier** [comment]
Great, really looking forward to this feature. Thanks again!

**Comment by thesqlsith** [comment]
#please-close

**Comment by thesqlsith** [comment]
Thanks @tmenier for the follow up question regarding the status of the PSPO feature in Azure. We do not have any updates that we can share at the moment regarding when the feature will be in Public Preview in Azure. We are still working on narrowing down a better timeline, however. 

We realize that it has been several months since the last update and do sincerely apologize for that. 

Please stay tuned.

**Comment by tmenier** [comment]
Thanks, I really appreciate your responsiveness here! Good enough, I'll just stay tuned for any updates. Thanks again.
