### ISSUE TITLE
Incorrect example in topic on Collation precedence

### ISSUE THREAD

**Issue by sommarskog** [MicrosoftDocs/sql-docs#8123]
This concerncs: https://learn.microsoft.com/en-us/sql/t-sql/statements/collation-precedence-transact-sql

More precisely this passage: 

> You cannot have multiple COLLATE clauses on an expression that is already an explicit expression. For example, the following WHERE clause is not valid because a COLLATE clause is specified for an expression that is already an explicit expression:
>
> WHERE ColumnA = ( 'abc' COLLATE French_CI_AS) COLLATE French_CS_AS

I don't want to edit this, because the text may actually want to say something. However the WHERE clause _is_ valid, you can cast collations twice in an expression. (And it can sometimes be useful if you want to convert between code pages.)

**Comment by WilliamAntonRohm** [comment]
@sommarskog -- thank you for your clear feedback.

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
Hi @sommarskog ,

Sorry for the delay in our response. 

This is good info for us to know we have this out there.

Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
@sommarskog 

I apologize I have not offered an update in about a month.

It's good to hear from you.

Let me take some time on this week and get back to you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site or the [Q & A](https://docs.microsoft.com/en-us/answers/products/sql-server) site.
