### ISSUE TITLE
SSISBuild: Issue with Cached Connection Manager (File not found)

### ISSUE THREAD

**Issue by brain246** [MicrosoftDocs/sql-docs#8130]
Hi there!

Stumbled upon an error in SSISBuild.exe today. Well not sure if it classifies as an error, but at least the behaviour of SSISBuild.exe differs from Visual Studio Data Tools in this regard.

Scenario: Project with various SSIS packages and connection managers. One of the connection managers is a "cached connection manager" (without file). Now the name of the connection manager (file) in the VS-Solution was different than the name defined inside the connection manager itself.

Filename was "Variants.conmgr". The name defined in the GUI of the connection manager was different however:

```
<?xml version="1.0"?>
<DTS:ConnectionManager xmlns:DTS="www.microsoft.com/SqlServer/Dts"
  DTS:ObjectName="AllowedVariants"
```
Visual Studio Data Tools 2019 builds that project without any problem (no warnings etc.). When building the same project with SSISBuild.exe i get the following error message and the build fails:
```
An error has occurred when updating files in 'BudgetTransferFromSubbudget\BudgetTransferFromSubbudget\obj\Development': Could not find file 'BudgetTransferFromSubbudget\BudgetTransferFromSubbudget\AllowedVariants.conmgr'.. 
```

The workaround/fix i found for that specific issue was to align the names. In my case i renamed the connection manager in the solution to "AllowedVariants" (Filename: AllowedVariants.conmgr). That solved the issue in SSISBuild.exe.

Edit: Sorry just realized that this is the general docs Github and not the one for the DevOps tools. I will re-post the issue in Q&A @Marketplace.

**Comment by WilliamAntonRohm** [comment]
@brain246 -- Thomas, thank you for your feedback.  Are you following a particular learn.microsoft.com article?  Meanwhile, please consider adding this issue here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

**Comment by brain246** [comment]
> @brain246 -- Thomas, thank you for your feedback. Are you following a particular learn.microsoft.com article? Meanwhile, please consider adding this issue here:
> 
> * [SQL Server feedback](http://aka.ms/sqlfeedback)

Well one could argue my issue is related to the following docs-page: https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/integration-services/devops/ssis-devops-standalone.md

However, i am quite aware that this isn't a documentation issue. So please feel free to close this issue here, i reposted my findings already at:  https://marketplace.visualstudio.com/items?itemName=SSIS.ssis-devops-tools&ssr=false#qna

Will checkout the link you provided tomorrow as well and maybe post it here too. 

Thanks for the fast response!

**Comment by WilliamAntonRohm** [comment]
@brain246 -- Thomas, thank you for your prompt followup and clarification.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

cc @chugugrace for awareness
