### ISSUE TITLE
Ole Automation Procedures not  present in Editions and supported features of SQL Server on Linux

### ISSUE THREAD

**Issue by Mnior** [MicrosoftDocs/sql-docs#8136]
https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-editions-and-components-2017

There is no mention of the operability of Ole Automation Procedures on the Linux platform.

Although the procedure is present, but it is impossible to achieve a result.
https://stackoverflow.com/questions/54780833/

Therefore, it is not clear whether these procedures should be removed or an example of application should be provided.

**Comment by WilliamAntonRohm** [comment]
@Mnior -- thank you for your feedback.  Please consider these resources as well:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
Hey @Mnior - OLE Automation Procedures is included in systems extended stored procedures, and that is listed:

https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-editions-and-components-2017?view=sql-server-ver15#Unsupported

![image](https://user-images.githubusercontent.com/40007119/193363321-0bbae379-d253-450c-b8fc-5dad1099ece2.png)

@rwestMSFT FYI
