### ISSUE TITLE
Unit for throughput?

### ISSUE THREAD

**Issue by pmasl** [MicrosoftDocs/sql-docs#8147]
What's the unit of _Backup/Restore Throughput/sec_ counter? Is it bytes like _Bulk Copy throughput/sec_?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7cde069-435c-ea89-efb5-bae00fffb0c0
* Version Independent ID: 3e51125f-3a9c-4653-78f0-3e76050ee094
* Content: [SQL Server, Databases object - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-databases-object?view=sql-server-ver16)
* Content Source: [docs/relational-databases/performance-monitor/sql-server-databases-object.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance-monitor/sql-server-databases-object.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@pmasl -- Pedro, good question!

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Hi @pmasl! The units are bytes/second. 
A doc update is in flight to make this more clear. Thanks for the feedback!
