### ISSUE TITLE
Mismatch between doc description and sample code - format files for blob storage access

### ISSUE THREAD

**Issue by tarockey** [MicrosoftDocs/sql-docs#8152]
- In the top of the document, it states that format files will not be used in the examples on the page, however all of the sample queries specify a format file:

Said description:
>The BULK INSERT and OPENROWSET statements can directly access a file in Azure blob storage. The following examples use data from a CSV (comma separated value) file (named inv-2017-01-19.csv), stored in a container (named Week3), stored in a storage account (named newinvoices). **The path to format file can be used, but is not included in these examples.**

Code snippet:
```SQL
SELECT * FROM OPENROWSET(
   BULK 'week3/inv-2017-01-19.csv',
   DATA_SOURCE = 'MyAzureInvoices',
   FORMAT = 'CSV',
   FORMATFILE='invoices.fmt',
   FORMATFILE_DATA_SOURCE = 'MyAzureInvoices'
   ) AS DataFile;
```

There are also no examples where a format file is not included.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b7a6124-86bc-bd57-88c6-7c4334c49cd5
* Version Independent ID: 1598c673-fb85-3cf7-4ff9-8fdc0e384c68
* Content: [Bulk access to data in Azure Blob storage - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage?source=recommendations&view=sql-server-ver16#accessing-data-in-a-csv-file-referencing-a-container-in-an-azure-blob-storage-location)
* Content Source: [docs/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@tarockey Thank you for your feedback. We will look into this when we refresh the article.

**Comment by rwestMSFT** [comment]
The article will be refreshed in the next few days. This issue will automatically close before then.
