### ISSUE TITLE
SSMS Utility does not support argument for "Active Directory - Universal with MFA"

### ISSUE THREAD

**Issue by zhfk930129** [MicrosoftDocs/sql-docs#8162]
We are a team under Microsoft C+AI org. Our team enforces us to use AAD account of another tenant (PME tenant) with 2-factor authentication to access customer's SQL Server database. It's very inconvenient without the argument support for "Active Directory - Universal with MFA".

Here are the detailed steps of our daily life which explain why the current process is so inconvenient:
Our portal will generate the SSMS command scripts with prepopulated server name, database name, username, etc. We simply copy it for execution then it will initialize the SSMS. Without the argument for "Active Directory - Universal with MFA" it cannot connect to the database for sure. **Now we have to manually switch the authentication type to "Active Directory - Universal with MFA". Then the crazier thing will happen: after switching the authentication type, the "database name" that our script prepopulated will be cleared so we have to click "options" tab, find the "database name" somewhere and manually type or paste there.**

Our org has thousands of engineers and most of us are required to be on-call and access customer's database. With your support, it will not only save MSFT's COGS, but also increase satisfaction on the on-call experience, which will eventually be reflected in our service attitude to customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 179d9df0-cfc8-d9f2-babc-e9b7d0732d87
* Version Independent ID: c458bccb-8bba-f94c-658c-5d35eab7cdc7
* Content: [SSMS Utility - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/ssms-utility?view=azuresqldb-current)
* Content Source: [docs/ssms/ssms-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/ssms-utility.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@zhfk930129 -- Frank, thank you for your detailed feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.


cc @markingmyname for awareness
