### ISSUE TITLE
SSMS 2012

### ISSUE THREAD

**Issue by ades-zeneb1** [MicrosoftDocs/sql-docs#8165]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
@ades-zeneb1 Hi - can you please help me understand the issue?  There is no stand alone download for SSMS 2012.  You can download the latest SSMS (18.12.1) which you can use against SQL Server 2012.

**Comment by rwestMSFT** [comment]
We haven't heard back in over three weeks, so I am closing this.

#please-close
