### ISSUE TITLE
Have SQLParamData/SQLPutData code example handling SQL_NO_DATA

### ISSUE THREAD

**Issue by sebflaesch** [MicrosoftDocs/sql-docs#8168]
Hello!

The ODBC page describing SQLPutData() code example should also show an UPDATE or DELETE statement usage, where the LOB parameter is used in the WHERE clause, with potential SQL_NO_DATA returned by SQLParamData(), if no row matches.

Or at least, add a comment near if() statements checking the return code

   // Make final SQLParamData call.  
   retcode = SQLParamData(hstmt1, &pParmID);
   **// Note: SQLParamData() can return SQL_NO_DATA with UPDATE/DELETE**   
   if ( (retcode != SQL_SUCCESS) && (retcode != SQL_SUCCESS_WITH_INFO) ) {  
      printf("Final SQLParamData Failed\n\n");  
      Cleanup();  
      return(9);  
   } 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d040eb38-371a-cacd-177a-addbdd2a78d8
* Version Independent ID: 18f56fb6-b16c-1a39-e47f-c15de5a82343
* Content: [SQLParamData Function - ODBC API Reference](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlparamdata-function?view=sql-server-ver16)
* Content Source: [docs/odbc/reference/syntax/sqlparamdata-function.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/syntax/sqlparamdata-function.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@sebflaesch -- Sebastien, thank you for your feedback and proposed update.

@David-Engel -- David, please look into this issue.

**Comment by rwestMSFT** [comment]
@sebflaesch Would you mind creating a pull request with your suggestion?

**Comment by rwestMSFT** [comment]
@sebflaesch We haven't heard back from you for a long time, and documentation enhancements like these often fall to the bottom of our backlog. I'm closing this issue, and hope that you will find it in your heart to open a pull request with the suggested change in order to get it published sooner.
