### ISSUE TITLE
Backup option not available in SSMS 17.9.1,18.12.1, 19.x for Azure SQL Databases

### ISSUE THREAD

**Issue by skyfox46311** [MicrosoftDocs/sql-docs#8176]
![image](https://user-images.githubusercontent.com/39566167/195352212-d0096b84-646f-481d-8f8a-6d1c231ed0f7.png)

Using SQL Authentication and AD Authentication seems to make no difference.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b39a6f87-ff17-e358-4a7c-ea7c2a037cde
* Version Independent ID: a8691d00-99a1-ec0d-346b-fee8f78202dd
* Content: [Quickstart: Backup & restore to Azure Blob Storage - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tutorial-sql-server-backup-and-restore-to-azure-blob-storage-service?view=sql-server-ver16&tabs=SSMS)
* Content Source: [docs/relational-databases/tutorial-sql-server-backup-and-restore-to-azure-blob-storage-service.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tutorial-sql-server-backup-and-restore-to-azure-blob-storage-service.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@skyfox46311 It's not clear from your screenshot which version of SQL Server you're using. If you can let us know, we might be able to direct you to the right resource. Backup to Azure Blob Storage is not supported on Azure SQL Database.

**Comment by rwestMSFT** [comment]
@skyfox46311 I'm closing this issue for now, but if you have any comments or feedback, please feel free to reply here.

#please-close
