### ISSUE TITLE
Are the .net core requirements accurate?

### ISSUE THREAD

**Issue by wapayne69** [MicrosoftDocs/sql-docs#8178]
I just installed .net core 3.1.424 only to then get errors about .net framework v4.6 not being installed?

stdout: C:\Program Files\dotnet\sdk\3.1.424\Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.6 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at...

I have to jump through a lot of infosec hoops at my customer to get software installed and it wastes a lot of time when the software requirements aren't correctly documented up front.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d25be772-12d5-6a8e-1eb5-9982ae0bfcac
* Version Independent ID: c4652a23-abc2-63ed-11fa-334b0f46698a
* Content: [SQL Database Projects extension - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension?view=sql-server-ver16)
* Content Source: [docs/azure-data-studio/extensions/sql-database-project-extension.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/extensions/sql-database-project-extension.md)
* Product: **azure-data-studio**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@wapayne69 -- Waylon, thank you for your feedback.  I see under [.NET Core SDK](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension?view=sql-server-ver16#net-core-sdk): 
> To force the SQL Database Projects extension to use the v3.1.x version of the .NET Core SDK when multiple versions are installed, add a [package.json](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x) file to the folder that contains the SQL project.

@dzsquared -- Drew, is this still the case, or should I update the current references from v3.1.x to v4.6.x?  Please advise.

**Comment by dzsquared** [comment]
No - when a project created in SSDT is opened for the first time in Azure Data Studio or VS Code it should get targets added for .NET Core automatically - it appears for @wapayne69 something went wrong.  If you raise this over at https://github.com/microsoft/azuredatastudio @wapayne69 the team can help uncover what went wrong and get you unblocked.

**Comment by wapayne69** [comment]
Only .net core 3.1 is installed. No other .net frameworks. I have logged a bug for the extension. It seems that it only happens when my project is in a folder that is git connected.

**Comment by WilliamAntonRohm** [comment]
@dzsquared -- Drew, thank you for clarifying.

@wapayne69 -- Waylon, thank you for your follow-up, and for logging that bug.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
