### ISSUE TITLE
Not supported in Synapse

### ISSUE THREAD

**Issue by ElectricLlama** [MicrosoftDocs/sql-docs#8187]
Please add some information to this page indicating this is _not_ supported in Synpase. i.e. the green checkboxes at the top.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f9c244b-870b-737f-6f6d-db9675179427
* Version Independent ID: 3dde09ff-88b5-f6f3-1120-3bf8a90a395e
* Content: [Temporal Tables - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-ver16)
* Content Source: [docs/relational-databases/tables/temporal-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/temporal-tables.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@ElectricLlama -- Nick, thank you for your feedback.  I am updating the article.

**Comment by rwestMSFT** [comment]
Thanks William.

For reference, we are moving away from putting in explicitly excluded versions in the article header. You'll find articles associated with Synapse will explicitly state support.

**Comment by WilliamAntonRohm** [comment]
@rwestMSFT -- Randolph, thank you for that clarification.

@ElectricLlama -- Nick, I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
