### ISSUE TITLE
The code snippet is misleading and inaccurate

### ISSUE THREAD

**Issue by nvingoe** [MicrosoftDocs/sql-docs#8190]
The code snippet is misleading and inaccurate. There is no need to specify a Database in a `Use` statement to query `sys.databases`. Furthermore, for those unfamiliar with TSQL, the reference to a Database called "AdventureWorks2012" is likely to confuse; especially if their SQL Server instance does not contain a Database by that name.

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ef0bcf2-f4b6-0bc0-a568-36f425aa4c24
* Version Independent ID: faec9433-5f72-8ddc-28bf-d0821701a634
* Content: [View list of databases on SQL Server - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/databases/view-a-list-of-databases-on-an-instance-of-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/databases/view-a-list-of-databases-on-an-instance-of-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/view-a-list-of-databases-on-an-instance-of-sql-server.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@nvingoe -- Neil, thank you for your clear feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Agreed, @nvingoe! Thanks for taking the time to provide this feedback, this improves documentation for everyone. A doc update is in flight to remove the confusingly-placed USE statement.
