### ISSUE TITLE
typo on Oracle Connection Manager 'If you wanna'

### ISSUE THREAD

**Issue by mcgolledge** [MicrosoftDocs/sql-docs#8192]
Should be 'If you want to'

**Comment by WilliamAntonRohm** [comment]
@mcgolledge -- thank you for catching this.  Which learn.microsoft.com article is this in?

**Comment by mcgolledge** [comment]
@WilliamAntonRohm The title is "Oracle Connection Manager"  SQL  SSIS  Microsoft connector for Oracle

**Comment by WilliamAntonRohm** [comment]
@mcgolledge -- thanks for clarifying!  I am updating this article.
