### ISSUE TITLE
In the article descibes how to unpack a DACPAC, but don't say which program must be installed to do it.

### ISSUE THREAD

**Issue by CSolervicens** [MicrosoftDocs/sql-docs#8193]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba7594c0-a72e-9dcc-9c02-29f7814d5bd5
* Version Independent ID: 4c7e2b0e-6caa-cb44-9920-018966e9bf1b
* Content: [Unpack a DAC Package - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/data-tier-applications/unpack-a-dac-package?view=sql-server-ver16)
* Content Source: [docs/relational-databases/data-tier-applications/unpack-a-dac-package.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/unpack-a-dac-package.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@CSolervicens -- Cristian, thank you for your feedback.  My understanding is that the unpacking capability is built into SQL Server.  Are you unable to unpack your DACPAC?

**Comment by dzsquared** [comment]
#assign:dzsquared

**Comment by dzsquared** [comment]
@CSolervicens  - frankly that article looks terribly out of date and incorrect.


I'll keep this open while I work towards updating the article, but if you have a dacpac you'd like to see inside of you have a few options:
1. In Visual Studio (Community is fine) with the Data Platform workload installed, you can import a dacpac to a new SQL project.  This will show all of the object scripts in the project explorer.
2. If you have a development or isolated instance of SQL (such as a container, localdb, etc), you can use SSMS or Azure Data Studio to publish the dacpac to the server.  *Only do this if you trust the author of the dacpac or can isolate it from other databases*
3. For a very quick glimpse at the contents of a dacpac, you can convert the file extension to .zip and extract it to the folder with xml files.  While they're not .sql files that are easy to read, you may be able to tell what you're looking for from this view.

**Comment by dzsquared** [comment]
#please-close
