### ISSUE TITLE
Regarding the Function GetNewValues()

### ISSUE THREAD

**Issue by PP-Papa** [MicrosoftDocs/sql-docs#8195]
Dear authors,
How are you today?

Thank you so much for this wonderful documentation "Binding Arrays of Parameters" at https://learn.microsoft.com/en-us/sql/odbc/reference/develop-app/binding-arrays-of-parameters?redirectedfrom=MSDN&view=sql-server-ver16. 

As I'm trying to follow the operations described in this page to solve my problem, my compiler reports error that the function "GetNewValues" was not declared. I cannot find any information about it, could you specify the usage of this function, please? Or at lease, could you specify which library that this function shall be referred to? Thank you!

Sincerely,
Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4722e09-0c77-3db9-5896-6fb4dec6886d
* Version Independent ID: f7c74a36-d709-d998-7168-119248853bb0
* Content: [Binding Arrays of Parameters - ODBC API Reference](https://learn.microsoft.com/en-us/sql/odbc/reference/develop-app/binding-arrays-of-parameters?redirectedfrom=MSDN&view=sql-server-ver16)
* Content Source: [docs/odbc/reference/develop-app/binding-arrays-of-parameters.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/develop-app/binding-arrays-of-parameters.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
`GetNewValues` is just a generic function you implement to provide data to the loop in the code sample. The sample was probably written that way to keep the code concise. You can implement `GetNewValues` however you need. For one example, see https://stackoverflow.com/questions/62148064/how-to-store-varbinarymax-and-varcharmax-data-in-sql-server-when-length-is-n.

Regards,
David

**Comment by WilliamAntonRohm** [comment]
@PP-Papa -- thank you for your kind words, and for your questions.

@David-Engel -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
