### ISSUE TITLE
Documentation not working for Ubuntu 22.10

### ISSUE THREAD

**Issue by mrunal77** [MicrosoftDocs/sql-docs#8200]
[The MSSQL is not available for Ubuntu 22.10. Is there any timeline for when the MS SQL Server will be available for Ubuntu 22.10?]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16&source=docs)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@mrunal77 -- Mrunal, thank you for your feedback.  For the latest information, please subscribe to:
- [SQL Server Blog](https://techcommunity.microsoft.com/t5/sql-server-blog/bg-p/SQLServer/label-name/SQLReleases)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
