### ISSUE TITLE
Clarify support for auditing for Synapse SQL pools

### ISSUE THREAD

**Issue by goventur** [MicrosoftDocs/sql-docs#8204]
In the article [Auditing for Azure SQL Database and Azure Synapse Analytics](https://learn.microsoft.com/en-us/azure/azure-sql/database/auditing-overview?view=azuresql)

It mentions Synapse Analytics is supported, but it doesn't clarify that it applies only to Dedicated SQL pools, it doesn't apply to Serverless SQL pools.

Suggesting some options to fix it:
- Add a note at the top mentioning it only applies to Dedicated SQL pools.
- Add a note under the section [Auditing limitations](https://learn.microsoft.com/en-us/azure/azure-sql/database/auditing-overview?view=azuresql#auditing-limitations).

Thanks!

**Comment by WilliamAntonRohm** [comment]
@goventur -- thank you for your feedback and suggestions.

@sravanisaluru -- please look into this issue.

**Comment by sravanisaluru** [comment]
@goventur could you please review the latest document and let me know if you still see any information is missing .

**Comment by goventur** [comment]
@sravanisaluru thank you, everything looks good!
