### ISSUE TITLE
Would suggest to adapt the query to check current size and growth to have growth in MB, like size is in MB for consistency reasons

### ISSUE THREAD

**Issue by brunogonzalez** [MicrosoftDocs/sql-docs#8210]
The size and growth check query in chapter: https://learn.microsoft.com/en-us/sql/relational-databases/databases/tempdb-database?view=sql-server-ver16#optimizing-tempdb-performance-in-sql-server, is referring to the growth value in a different unit than the size value, which is mega-bytes. I think for consistency reasons, it would be better to have growth in MB as well like:

```
SELECT name AS FileName,
    size*1.0/128 AS FileSizeInMB,
    CASE max_size
        WHEN 0 THEN 'Autogrowth is off.'
        WHEN -1 THEN 'Autogrowth is on.'
        ELSE 'Log file grows to a maximum size of 2 TB.'
    END,
    **growth*1.0/128 AS 'GrowthValueInMB',**
    'GrowthIncrement' =
        CASE
            WHEN growth = 0 THEN 'Size is fixed.'
            WHEN growth > 0 AND is_percent_growth = 0
                THEN 'Growth value is in 8-KB pages.'
            ELSE 'Growth value is a percentage.'
        END
FROM tempdb.sys.database_files;
GO
```

It's just a suggestion.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37fab3b5-a2f3-5612-06e2-01e0406a615d
* Version Independent ID: 2daa00e0-8234-bf26-13c0-8d5200a1f4a5
* Content: [tempdb database - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/databases/tempdb-database?view=sql-server-ver16#feedback)
* Content Source: [docs/relational-databases/databases/tempdb-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/tempdb-database.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@brunogonzalez -- Bruno, thank you for your suggestion.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Hi @brunogonzalez! Thanks for your feedback. I agree this query could be more consistent in the units and I like your edit.

To give you credit as a contributor to the article, would you like to [create a Pull Request](https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute) and get the ball rolling on a change yourself? By opening a pull request, you're collaborating with the author to add changes directly to the documentation. After the updated article is published, GitHub lists you as an article contributor.  Select the "Edit" pencil at the top of the article to begin a pull request on our open sources docs. You can reference this issue and my GitHub in your pull request, and I'll personally review and carry it across the finish line.

Either way, thanks for your feedback!

Closing this issue for now. If you'd rather not create a pull request, we can handle the update.

**Comment by brunogonzalez** [comment]
Hi @WilliamDAssafMSFT ,
thank you. I just did. I proposed something better though that could adapt to all situations.

**Comment by WilliamDAssafMSFT** [comment]
Got it!
