### ISSUE TITLE
Change data capture support

### ISSUE THREAD

**Issue by sidesw1pe** [MicrosoftDocs/sql-docs#8211]
This article mentions:

> Change data capture is only supported in SQL Server and Azure SQL Managed Instance.

However CDC has been in GA for Azure SQL Database for a while now.
https://devblogs.microsoft.com/azure-sql/announcing-general-availability-of-change-data-capture-cdc-on-azure-sql-database/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5064f6a-f469-4b7c-101c-e62038f1efb6
* Version Independent ID: 4e830181-4699-703f-cf74-5c468628c082
* Content: [Track Data Changes - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/track-changes/track-data-changes-sql-server?view=sql-server-ver16&source=docs)
* Content Source: [docs/relational-databases/track-changes/track-data-changes-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/track-data-changes-sql-server.md)
* Product: **sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@sidesw1pe -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review this update in [private PR 24828](https://github.com/MicrosoftDocs/sql-docs-pr/pull/24828).
