### ISSUE TITLE
Changing the scale and precision in the NUMERIC datatype in ODBC

### ISSUE THREAD

**Issue by edwig** [MicrosoftDocs/sql-docs#8229]
To get things really working a lot more is  needed to change the scale and precision of a NUMERIC datatype.
1) A row-descriptor must be gotten
2) The SQL_DESC_TYPE of the descriptor must be set
3) Then the SQL_DESC_PRECISION and SQL_DESC_SCALE can be set on the row-descriptor
4) And lastly, the missing step on this page is the re-setting of the SQL_DESC_DATA_PTR. If the data pointer is not set, most ODBC drivers wil not react to the new settings of scale and precision

Here  is a working example from the [SQLComponents](https://github.com/edwig/sqlcomponents) project

```
void
SQLQuery::BindColumnNumeric(SQLSMALLINT p_column,SQLVariant* p_var,int p_type)
{
  // Row descriptor for RESULT rows or PARAMeter rows
  SQLHDESC rowdesc = NULL;

  // Is it for a result set, or for a binded parameter?
  SQLINTEGER attribute = (p_type == SQL_RESULT_COL) ? SQL_ATTR_APP_ROW_DESC : SQL_ATTR_APP_PARAM_DESC;

  // Getting the ROW descriptor and set the precision/scale fields
  m_retCode = SqlGetStmtAttr(m_hstmt,attribute,&rowdesc,SQL_IS_POINTER,nullptr);
  if(SQL_SUCCEEDED(m_retCode))
  {
    SQLULEN precision = (SQLULEN)     p_var->GetNumericPrecision();
    SQLSMALLINT scale = (SQLSMALLINT) p_var->GetNumericScale();

    if(m_database)
    {
      m_database->GetSQLInfoDB()->GetRDBMSNumericPrecisionScale(precision,scale);
   }

    RETCODE retCode1  = SqlSetDescField(rowdesc,p_column,SQL_DESC_TYPE,     (SQLPOINTER)(DWORD_PTR)SQL_C_NUMERIC,SQL_IS_INTEGER);
    RETCODE retCode2  = SqlSetDescField(rowdesc,p_column,SQL_DESC_PRECISION,(SQLPOINTER)(DWORD_PTR)precision,    SQL_IS_UINTEGER);
    RETCODE retCode3  = SqlSetDescField(rowdesc,p_column,SQL_DESC_SCALE,    (SQLPOINTER)(DWORD_PTR)scale,        SQL_IS_SMALLINT);

    if(SQL_SUCCEEDED(retCode1) && SQL_SUCCEEDED(retCode2) && SQL_SUCCEEDED(retCode3))
    {
      // Now trigger the reset and check of the descriptor record, by re-supplying the data pointer again.
      // Very covertly described in the ODBC documentation. But if you do not do this one last step
      // results will be very different - and faulty - depending on your RDBMS
      SQLPOINTER pointer = p_var->GetDataPointer();
      m_retCode = SqlSetDescField(rowdesc,p_column,SQL_DESC_DATA_PTR,pointer,SQL_IS_POINTER);
      if(SQL_SUCCEEDED(m_retCode))
      {
        // All went well, we are done
        return;
      }
    }
  }
  XString error;
  error.Format("Cannot bind NUMERIC attributes PRECISION/SCALE for column: %d",p_column);
  throw StdException(error);
}
```

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51016543-850f-04d4-f605-827433fd14e1
* Version Independent ID: 6d24d370-d991-b517-a1da-d91e981445b8
* Content: [Overriding Default Precision and Scale for Numeric Data Types - ODBC API Reference](https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/overriding-default-precision-and-scale-for-numeric-data-types?view=sql-server-ver16)
* Content Source: [docs/odbc/reference/appendixes/overriding-default-precision-and-scale-for-numeric-data-types.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/appendixes/overriding-default-precision-and-scale-for-numeric-data-types.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@edwig -- Edwig, thank you for your thorough feedback.

@David-Engel -- David, please look into this issue.

**Comment by rwestMSFT** [comment]
@edwig We haven't heard back from you for almost a year, and documentation enhancements like these often fall to the bottom of our backlog. I'm closing this issue, and hope that you open a pull request with the suggested change in order to get it published sooner.
