### ISSUE TITLE
UPDATE (Transact-SQL) table_alias documentation seems wrong

### ISSUE THREAD

**Issue by nmschulte-aviture** [MicrosoftDocs/sql-docs#8232]
https://learn.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-ver16

It's not clear, though I suspect this is incorrect: the _table_alias_ documentation says "in the FROM clause," where I think it should read "in the UPDATE clause":
> ...
> ![image](https://user-images.githubusercontent.com/5199745/199619501-6b6a672f-dbde-4293-9faa-14c87c9b097d.png)
> ...
> _table_alias_
> The alias specified in the FROM clause representing the table or view from which the rows are to be updated.

**Comment by WilliamAntonRohm** [comment]
@nmschulte-aviture -- thank you for your feedback.

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
Thanks @nmschulte-aviture! I'm updating the documentation.
