### ISSUE TITLE
TutorialDB.bak

### ISSUE THREAD

**Issue by pgh000** [MicrosoftDocs/sql-docs#8241]
THe database TurorialDB.bak is not available from the link. Instead an error is given "Public access is not permitted on this storage account."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b02d11f-8002-4de2-22bd-8b9fae018dc2
* Version Independent ID: 9156a821-0f92-1c48-6892-59a6f59a781b
* Content: [Python tutorial: Ski rentals - SQL machine learning](https://learn.microsoft.com/en-us/sql/machine-learning/tutorials/python-ski-rental-linear-regression?view=sql-server-ver15)
* Content Source: [docs/machine-learning/tutorials/python-ski-rental-linear-regression.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/tutorials/python-ski-rental-linear-regression.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @pgh000, acknowledged the problem is on our side. These links are in the process of being moved and re-housed, the docs should be updated with new links shortly.
