### ISSUE TITLE
Hope there are some examples for Azure Storage

### ISSUE THREAD

**Issue by vinixwu** [MicrosoftDocs/sql-docs#8243]
I'm trying to get info about how to know contents of backup files on Azure Storage, but all examples in this docuument are about backups on local disk.

Please Add information about how to view contents of backup files on Azure Storage.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7777705d-c967-84ea-0ab2-2fcb1cda1c11
* Version Independent ID: d1256d3d-a292-c855-c918-ae7607a74c3f
* Content: [View backup contents (file or tape) - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/view-the-contents-of-a-backup-tape-or-file-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/view-the-contents-of-a-backup-tape-or-file-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/view-the-contents-of-a-backup-tape-or-file-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@vinixwu -- thank you for your feedback.  Please consider this section for a starting point.
- [What can I back up?](https://learn.microsoft.com/azure/backup/backup-overview#what-can-i-back-up)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
