### ISSUE TITLE
SQL function GEN_NORM_TABLES is not documented

### ISSUE THREAD

**Issue by renjieliu** [MicrosoftDocs/sql-docs#8246]
Hello, 

Can anyone look into this issue? 

This built in function GEN_NORM_TABLES is not documented, and I am not able to find any information online.

Thank you.

![image](https://user-images.githubusercontent.com/19803974/200685417-111ce519-bbad-4965-b47c-4119a0fb1f33.png)

**Comment by WilliamAntonRohm** [comment]
@renjieliu -- thank you for your feedback.  This is an internal-only function, and so it is not in the public documentation.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
