### ISSUE TITLE
Invalid Param RSSVCPASSWORD

### ISSUE THREAD

**Issue by Dwayne75** [MicrosoftDocs/sql-docs#8250]
/RSSVCPASSWORD="************"

This param doesnt exist for sql 2022 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33aa7982-7edb-b858-7811-037a1d6d5bcc
* Version Independent ID: 683dcf24-4cb8-6eb7-f9bb-c916f3e85044
* Content: [Install SQL Server Using a Configuration File - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-using-a-configuration-file?view=sql-server-ver16)
* Content Source: [docs/database-engine/install-windows/install-sql-server-using-a-configuration-file.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/install-sql-server-using-a-configuration-file.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@Dwayne75 -- Dwayne, thank you for your feedback.  You are correct, as per the Note following the *SQL Server Database Engine component* table:
- [Service account parameters](https://learn.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-ver16#Accounts)

I am updating this article.

**Comment by rwestMSFT** [comment]
@WilliamAntonRohm Please re-verify against the latest version of the article from today’s release branch merge.

I will be back next week to review, if this still needs attention.

**Comment by WilliamAntonRohm** [comment]
@rwestMSFT -- Randolph, I'll check tomorrow's version, as today's merge doesn't seem to be propagated yet.

**Comment by rwestMSFT** [comment]
@Dwayne75 @WilliamAntonRohm I have a new internal PR that will refresh this article and resolve this issue in the next day or so. Thanks for reporting it!
