### ISSUE TITLE
Typo in example script

### ISSUE THREAD

**Issue by sidesw1pe** [MicrosoftDocs/sql-docs#8251]
The example script in the "Create database-mirroring endpoints on all replicas" section seems to have a typo, instead of "FOR DATA_MIRRORING" it should be "FOR DATABASE_MIRRORING".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e357702e-ddfb-eb9c-d6a5-a5274d87b320
* Version Independent ID: a809b6ec-7bf2-4cce-b4af-c06fdd1b00bd
* Content: [Configure read-scale for an availability group - SQL Server Always On](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-read-scale-availability-groups?source=recommendations&view=sql-server-ver16)
* Content Source: [docs/database-engine/availability-groups/windows/configure-read-scale-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/configure-read-scale-availability-groups.md)
* Product: **sql**
* Technology: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@sidesw1pe -- thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@sidesw1pe -- it seems the article is correct as written.  For example, see [Create an endpoint to listen to all IP addresses](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-distributed-availability-groups?view=sql-server-ver16&tabs=automatic#create-an-endpoint-to-listen-to-all-ip-addresses).

cc @MashaMSFT for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by sidesw1pe** [comment]
@WilliamAntonRohm, @MashaMSFT 
The documentation for [CREATE ENDPOINT](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-endpoint-transact-sql?view=sql-server-ver16) lists only 3 payload types: 

> FOR { TSQL | SERVICE_BROKER | DATABASE_MIRRORING }
> Specifies the payload type.

I copy/pasted the example and it failed to parse and gave an error when I tried to run it. I needed to change "FOR DATA_MIRRORING" to "FOR_DATABASE_MIRRORING" to get it to run.

**Comment by WilliamAntonRohm** [comment]
@sidesw1pe -- thank you for your followup.

@MashaMSFT -- please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @sidesw1pe , thanks so much for contacting Microsoft and helping improve our docs! My apologies for the delay as we've been working through a large backlog of Issues. I've processed a change to update this that should be live later this week. I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks again and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
