### ISSUE TITLE
No information what's the optimal way to obtain final results if the number of results is dynamic.   

### ISSUE THREAD

**Issue by amikot** [MicrosoftDocs/sql-docs#8254]
If  certain situations like when executed stored procedure has loops it may happen that number of returned results is unexpected.
This may happen when you processing table with dynamic size iterating each row in loop copying over some data to temp tables etc. 
Every select into temp table or update, or insert generates "empty" results. 
Unfortunately there is no php function to automatically skip these "empty" results and jump to final one which contains all returned data.

Somewhere on the internet I've found suggestion to use php loop with sqlsrv_next_result which would be stopped if valid results would be detected. I would say it make sense, but without giving reason this answer was scored negatively by many people. 

The MS docs are not giving any example, while IMHO there should be information about that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d993eeba-bf05-5a06-dc25-e941526cbf60
* Version Independent ID: 0f517adc-583f-ddb5-1f5b-4799f5bc3b60
* Content: [sqlsrv_next_result - PHP drivers for SQL Server](https://learn.microsoft.com/en-us/sql/connect/php/sqlsrv-next-result?view=sql-server-ver16)
* Content Source: [docs/connect/php/sqlsrv-next-result.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/sqlsrv-next-result.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
@amikot 
Thanks for submitting an issue.

The possible results returned by a stored procedure are virtually limitless. We cannot possibly provide code examples for every scenario you might need to handle. That is up to you and the queries submitted via your application. The example on the page already provides the scaffold for looping through all results and all columns of each result. It's up to you to implement application-specific logic to analyze the results and act on them accordingly.

That said, if you are the writer of the stored procedures and you don't need to check the results of every insert/update/delete performed by the stored procedure, consider using `SET NOCOUNT OFF` in the procedure to avoid sending those results to the client. For more information, see [SET NOCOUNT (Transact-SQL)](https://learn.microsoft.com/en-us/sql/t-sql/statements/set-nocount-transact-sql?view=sql-server-ver16).

Regards,
David

**Comment by WilliamAntonRohm** [comment]
@amikot -- thank you for your feedback.

@David-Engel -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
