### ISSUE TITLE
Missing steps under Install on single server section

### ISSUE THREAD

**Issue by jwarner777** [MicrosoftDocs/sql-docs#8257]
[Enter feedback here]
At Step 8:
8: In the Certificates snap-in, expand Certificates, expand Personal, and then right-click Certificates, point to All Tasks, and then select Import.

The "Welcome to the Certificate Import Wizard" will display the Store location will be filled in as Local Machine, click Next.

File to Import, find the certificate file to import then click Next. <blah blah blah> finish the wizard...

Now the certificate has been imported...

XX: Right-click the imported certificate, point to All Tasks, and then select Manage Private Keys. In the Security dialog box, add read permission **(or full based on https://learn.microsoft.com/en-us/troubleshoot/sql/admin/event-id-33565-start-sql-server)** for the user account used by the SQL Server service account.   

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dfa20275-e415-5531-3ef4-7472d859753b
* Version Independent ID: cc1346a6-9336-91ba-bcff-9fff79847c35
* Content: [Enable encrypted connections - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@jwarner777 -- thank you for your feedback.  I have edited your comment to bold what I think is the addition you're requesting.

@VanMSFT -- please look into this issue.

**Comment by rwestMSFT** [comment]
@jwarner777 It has been some time since you submitted this issue, and the article in question has changed since then. Can you please confirm whether the issue persists?

**Comment by rwestMSFT** [comment]
Closing this, as it appears to be resolved.
