### ISSUE TITLE
Documentation typo: missing verb. 

### ISSUE THREAD

**Issue by JerryNixon** [MicrosoftDocs/sql-docs#8258]
It reads: 
> If LEFT or RIGHT not specified, LEFT range is the default.

It should read: 
> If LEFT or RIGHT **_is_** not specified, LEFT range is the default.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7b22d6-0ccb-bda0-7ea6-dc4a7e4817c5
* Version Independent ID: 9039d0ef-8830-a67d-6cd0-b17ef2a78081
* Content: [Partitioned tables and indexes - SQL Server, Azure SQL Database, Azure SQL Managed Instance](https://learn.microsoft.com/en-us/sql/relational-databases/partitions/partitioned-tables-and-indexes?view=sql-server-ver16#aligned-index)
* Content Source: [docs/relational-databases/partitions/partitioned-tables-and-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/partitions/partitioned-tables-and-indexes.md)
* Product: **sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@JerryNixon -- Jerry, thank you for catching this.  I am updating the article.
