### ISSUE TITLE
Not working in SSMS 19

### ISSUE THREAD

**Issue by FullThrottle** [MicrosoftDocs/sql-docs#8259]
Tried this in SSMS 19 and found that the steps do not work. The path for data and logs reset back to the original values, even after stopping / restarting sql service.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8bf2db49-3c57-2e1c-7cb2-66c54438ce5e
* Version Independent ID: 39879f1e-3301-49aa-f507-a7a970829e90
* Content: [View or Change the Default Locations for Data and Log Files - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/view-or-change-the-default-locations-for-data-and-log-files?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/view-or-change-the-default-locations-for-data-and-log-files.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/view-or-change-the-default-locations-for-data-and-log-files.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by erinstellato-ms** [comment]
Hi @FullThrottle, can you please confirm which version of SSMS 19 you used, and what version of SQL?  Also, did you restart the instance through Configuration Manager, or from within SSMS?  Thanks.

**Comment by rwestMSFT** [comment]
@FullThrottle I am closing this because we haven't heard from you. If you do want to provide more information for us, please feel free to comment.

**Comment by rwestMSFT** [comment]
#please-close
