### ISSUE TITLE
Can I download example file "call_center.csv" used in this sample? 

### ISSUE THREAD

**Issue by Aldermore-RajChidipudi** [MicrosoftDocs/sql-docs#8262]
Hello there,

Can I download example file "call_center.csv" used in this sample please?  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1918e8f-e4fd-597c-fc36-6912948d3119
* Version Independent ID: f1918e8f-e4fd-597c-fc36-6912948d3119
* Content: [Virtualize a CSV file with PolyBase - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/polybase/virtualize-csv?view=sql-server-ver16)
* Content Source: [docs/relational-databases/polybase/virtualize-csv.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/virtualize-csv.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @HugoMSFT
* Microsoft Alias: **hudequei**

**Comment by WilliamAntonRohm** [comment]
@Aldermore-RajChidipudi -- thank you for your question.  This file is just an example (placeholder), and doesn't really exist.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
