### ISSUE TITLE
Add entry for SQL 2017 introducing NVARCHAR(MAX) in clustered columnstore

### ISSUE THREAD

**Issue by codykonior** [MicrosoftDocs/sql-docs#8264]
This article is about differences in columnstore between each version.

SQL 2017 introduced NVARCHAR(MAX) in clustered columnstore (mentioned here: https://learn.microsoft.com/en-us/sql/t-sql/statements/create-columnstore-index-transact-sql?view=sql-server-ver16)

It would be good to add this to the differences list.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f005780-e6f8-10e5-a891-00a20254a64b
* Version Independent ID: 5d875140-6fb9-d85b-3e15-fa440bc49096
* Content: [What's new in columnstore indexes - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-what-s-new?view=sql-server-ver16)
* Content Source: [docs/relational-databases/indexes/columnstore-indexes-what-s-new.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/columnstore-indexes-what-s-new.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@codykonior -- Cody, thank you for your suggestion.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by MikeRayMSFT** [comment]
Staging update at https://github.com/MicrosoftDocs/sql-docs-pr/pull/27677

**Comment by MikeRayMSFT** [comment]
@codykonior - complete. Thanks
