### ISSUE TITLE
Create a Publication - RMO property name is incorrect

### ISSUE THREAD

**Issue by jpomfret** [MicrosoftDocs/sql-docs#8265]
Under this section: 
[to-create-a-snapshot-or-transactional-publication](https://learn.microsoft.com/en-us/sql/relational-databases/replication/publish/create-a-publication?view=sql-server-ver16#to-create-a-snapshot-or-transactional-publication-1)

It specifies `PublicationType` but that fails, and looking at the object it is named just `Type`
![image](https://user-images.githubusercontent.com/981370/201970256-6f3061ca-be71-4e6e-b43b-b1bd37def754.png)

That also makes me think this page is wrong: https://learn.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.replication.publicationtype?view=sqlserver-2016

![image](https://user-images.githubusercontent.com/981370/201970524-21f470f6-6780-4490-9c7d-49fd439a7354.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f4babe3-56f1-a6d9-e725-39abe290a54e
* Version Independent ID: a4440d47-1ae5-7295-6f2f-fae7ee741886
* Content: [Create a Publication - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/replication/publish/create-a-publication?view=sql-server-ver16)
* Content Source: [docs/relational-databases/replication/publish/create-a-publication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/publish/create-a-publication.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@jpomfret -- Jess, thank you for your feedback.

@MashaMSFT -- Masha, please look into this issue.

**Comment by rwestMSFT** [comment]
@jpomfret which DLL are you looking at? I see `PublicationType` in my SSMS v19 `Microsoft.SqlServer.Replication.dll`, as well as the SMO DLL distributed with dbatools v1.1.143.

**Comment by rwestMSFT** [comment]
@jpomfret Well will you look at that... I went into `TransPublication` class and had a look there: the property is called Type, but it's a `PublicationType` type.

@MashaMSFT I think we'll have to edit that article. I'll do a PR.

**Comment by jpomfret** [comment]
Thanks @rwestMSFT!
