### ISSUE TITLE
docker command specifying do not work

### ISSUE THREAD

**Issue by relcodedev** [MicrosoftDocs/sql-docs#8267]
1 issues with docker command on the page:

#1 docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=MyStrongPassword" --cap-add SYS_PTRACE -u (id -u myusername):(id -g myusername) -v /path/to/mssql:/var/opt/mssql -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest

It is missing the **$**(id -u myusername):**$**(id -g myusername) 

tested on ubuntu 20.04.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d971388-f1db-b134-7809-3e1fe84352a1
* Version Independent ID: 1ae396d0-78fb-4501-4992-44e4623e854a
* Content: [Secure SQL Server Linux containers - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-security?view=sql-server-ver15&viewFallbackFrom=sql-server-2019)
* Content Source: [docs/linux/sql-server-linux-docker-container-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-docker-container-security.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@relcodedev -- Edgar, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@amvin87 -- please review this change in [private PR 24959](https://github.com/MicrosoftDocs/sql-docs-pr/pull/24959).
