### ISSUE TITLE
Change Tracking - Unreadable Images in Dark Mode/High Contrast themes

### ISSUE THREAD

**Issue by A-Matt** [MicrosoftDocs/sql-docs#8273]
The images which are provided in this document seem to have been had the White Background on them removed but this hasn't been done effectively and causes the text to be made Extremely hard to read.
![image](https://user-images.githubusercontent.com/47449129/202421478-66cf2a05-fceb-4e3c-a50f-25e51d9b3d16.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9003737-0cf4-d790-2e55-b91bdba216aa
* Version Independent ID: 1b86829b-5158-1540-47a2-cdfeda1263e6
* Content: [About Change Tracking - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/track-changes/about-change-tracking-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/track-changes/about-change-tracking-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/about-change-tracking-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @JetterMcTedder
* Microsoft Alias: **bspendolini**

**Comment by WilliamAntonRohm** [comment]
@A-Matt -- thank you for your feedback.  I am updating these images.
