### ISSUE TITLE
This article does NOT say how to enter into T-SQL debug mode?

### ISSUE THREAD

**Issue by RobinAinscough** [MicrosoftDocs/sql-docs#8274]
Don't you think it might be important to actually provide information on HOW to get T-SQL into debug mode?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b6bda12-8647-257a-0cff-3e1753f24ef1
* Version Independent ID: 88cf6bd4-b860-e79e-50eb-6d7b6c5d0f45
* Content: [Transact-SQL debugger - T-SQL debugger](https://learn.microsoft.com/en-us/sql/ssms/scripting/transact-sql-debugger?view=sql-server-ver16)
* Content Source: [docs/ssms/scripting/transact-sql-debugger.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/transact-sql-debugger.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@RobinAinscough,

May I ask if you are using an older version of SSMS?

**Comment by markingmyname** [comment]
Not enough info:

Hello, [RobinAinscough](https://github.com/RobinAinscough) Thank you for your comment. I can't tell by the title and the lack of supporting detail what exactly is the "issue" with this article.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community wants, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site or the [Q & A](https://docs.microsoft.com/en-us/answers/products/sql-server) site.
