### ISSUE TITLE
Case Typo

### ISSUE THREAD

**Issue by calebTree** [MicrosoftDocs/sql-docs#8283]
It appears to me there is a casing typo in the first code sample:
```
var Shipcity; // intended to be pascal casing?
ShipCity = Request.form ("ShipCity");  
var sql = "select * from OrdersTable where ShipCity = '" + ShipCity + "'";
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75b0c5a5-dadb-192a-c466-23275c8409d3
* Version Independent ID: 179ebcda-6d12-2e9c-3df3-902fc038388c
* Content: [SQL Injection - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/sql-injection?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/sql-injection.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/sql-injection.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@calebTree -- Caleb, thank you for catching this.  I am updating the article.
