### ISSUE TITLE
sp_configure: ADR cleaner retry timeout (min) and ADR Preallocation Factor

### ISSUE THREAD

**Issue by JCNavarroG** [MicrosoftDocs/sql-docs#8289]
This value in Microsoft (https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/server-configuration-options-sql-server?view=sql-server-ver15) 

1. ADR cleaner retry timeout (min): has a default value of 15. 
2. ADR Preallocation Factor: has a default value of 4. 

In the page "https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/adr-cleaner-retry-timeout-configuration-option?view=sql-server-ver15" said:

Occasionally the cleaner runs into issues while acquiring object level locks due to conflicts with user workload during its sweep. It tracks such pages in a separate list. The ADR cleaner retry timeout **_(default value of 15_**) controls the amount of time the cleaner would spend exclusively retrying object lock acquisition and cleanup of page before abandoning the sweep. Completion of a sweep with 100% success is essential to keep the growth of aborted transactions in the aborted transactions map. If the separate list cannot be cleaned up in the prescribed timeout, then the current sweep will be abandoned and the next sweep will start.

In the page:  https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/adr-preallocation-factor-server-configuration-option?view=sql-server-ver15 said: 
 
.......
The number of pages the background thread pre-allocates is based on various workload heuristics, but largely allocates pages in chunks of 512 pages. The ADR preallocation factor is a multiple of the chunk. **By default, the factor is 4.** This means it preallocates 2048 pages at once when required.
......

 However during the process of install  the value of "ADR cleaner retry timeout (min) " is "0", and the same for "ADR Preallocation Factor"
When I use the next code the default value is o.

![image](https://user-images.githubusercontent.com/118738050/203063445-e41ec87c-3ab4-4d2c-aa33-0f234db8990d.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32e9c4f8-ec32-ff5f-93a4-8f07b664db5f
* Version Independent ID: 2111d777-a999-dc99-a3e5-cc7e7877c9b8
* Content: [Server Configuration Options (SQL Server) - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/server-configuration-options-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/server-configuration-options-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/server-configuration-options-sql-server.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
As noted in #8290, we are looking into this. Thank you for your contribution.

**Comment by rwestMSFT** [comment]
@JCNavarroG We are tracking this item internally (AB#70883), so this issue is being closed. Thanks again for your feedback. When we have an update to share, we will let you know here. In the meanwhile, please feel free to leave additional feedback.

**Comment by rwestMSFT** [comment]
@JCNavarroG Thank you for your patience. I wanted to let you know we updated this article some time ago, and neglected to update this issue to say so. Depending on which SQL Server you pick from the top left menu (2019 or 2022), the information relevant to 2019 is displayed.

Additionally, we are going to be addressing #8290 in the next few days.

Once again we appreciate your feedback!
