### ISSUE TITLE
sp_configure in 2022: missing options 

### ISSUE THREAD

**Issue by JCNavarroG** [MicrosoftDocs/sql-docs#8290]
The option "**ADR Cleaner Thread Count**'" is missing in 2022 page.
However in the process of setup exist with the default value of 1

![image](https://user-images.githubusercontent.com/118738050/203070169-3f8b156b-8faa-4a0d-8fbd-611a09237245.png)

Others options misssing:

1. **Data processed daily limit in TB** with default value 2147483647
2. **Data processed monthly limit in TB**  with default value 2147483647
3. **Data processed weekly limit in TB**  with default value   2147483647
4. **hardware offload config** with default value  0
5. **hardware offload mode** with default value  0
6. **openrowset auto_create_statistics** witb default value 1
7. **suppress recovery model errors** with default value 0. This option is avalaible also in SQL Managed instances
8. **version high part of SQL Server** with default valuer 1048576
10. **version low part of SQL Server** with default value 65536006
11. And **min server memory** in SQL Server 2019 and 2022 the defatult value is 16 instead of 0
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32e9c4f8-ec32-ff5f-93a4-8f07b664db5f
* Version Independent ID: 2111d777-a999-dc99-a3e5-cc7e7877c9b8
* Content: [Server Configuration Options (SQL Server) - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/server-configuration-options-sql-server?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/server-configuration-options-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/server-configuration-options-sql-server.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@JCNavarroG -- Juan, thank you for your clear feedback.

@rwestMSFT -- Randolph, please look into this issue.

**Comment by rwestMSFT** [comment]
@JCNavarroG We are looking into this, as well as #8289. Thank you for your contribution.

**Comment by rwestMSFT** [comment]
@JCNavarroG An update to this article was created recently, though not with all settings. That will be coming out in the next month or so.
