### ISSUE TITLE
Applicability to Azure SQL Database Managed Instance

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/sql-docs#8299]
This issue relates to https://github.com/MicrosoftDocs/sql-docs/issues/4076

Some file group features apply to Azure SQL MI in addition to SQL Server. For example, see https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-file-and-filegroup-options?view=azuresqldb-mi-current&preserve-view=true. 

I think this page should be updated to:

1) List Azure SQL MI as one of the applicable platforms
2) Enumerate any differences in support between SQL Server and Azure SQL MI

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1faba5-e9b8-a343-308b-509a70d08db0
* Version Independent ID: c5156c9e-8e82-0c25-a8f5-4d1c37ee6720
* Content: [Database Files and Filegroups - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/databases/database-files-and-filegroups?view=sql-server-ver16)
* Content Source: [docs/relational-databases/databases/database-files-and-filegroups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/database-files-and-filegroups.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@VitalyMCT -- Vitaly, thank you for your clear feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @VitalyMCT, it appears the program group made this exact change to the **Database Files and Filegroups** article in mid-December.
