### ISSUE TITLE
Web page refers to example code which is not present

### ISSUE THREAD

**Issue by BusterRaid** [MicrosoftDocs/sql-docs#8300]
The documentation makes multiple references to some example Visual Basic code that should be available on the web page, including how to compile it.
There is no Visual Basic code on the web page.
It is a "getting started" web page, so it's particularly disappointing the simple example referred to is not present.

Dell Precision 490.
Windows 10 Pro x64 OEM 2H22
Exhibited behaviour on:
Firefox 107.0
MSEdge Version 107.0.1418.56 (Official build) (64-bit)

Page:
https://learn.microsoft.com/en-us/sql/relational-databases/clr-integration/database-objects/getting-started-with-clr-integration?view=sql-server-ver16

Note: The example code seems missing for 2022, 2019, 2017, 2016

Looking at the Markdown code:
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/clr-integration/database-objects/getting-started-with-clr-integration.md

... it seems the VB code is present (as at 20221124-1030 UTC).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de8bd484-b3db-2b2f-7448-0a5445d9f29e
* Version Independent ID: 6d0f33a2-f9ae-58e4-2032-90efb2a49d09
* Content: [Getting Started with CLR Integration - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/clr-integration/database-objects/getting-started-with-clr-integration?view=sql-server-ver16)
* Content Source: [docs/relational-databases/clr-integration/database-objects/getting-started-with-clr-integration.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/clr-integration/database-objects/getting-started-with-clr-integration.md)
* Service: **sql**
* Sub-service: **clr**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@BusterRaid Thanks for your feedback. It looks like a small bug in the way the article is being rendered, because as you noted, the VB code is there, just not visible. I'll look into bringing it back.

**Comment by rwestMSFT** [comment]
This article will be refreshed in the next day or so. Thanks again for the feedback.
