### ISSUE TITLE
Update docs to use newer version

### ISSUE THREAD

**Issue by rgl** [MicrosoftDocs/sql-docs#8319]
The referenced documentation page should use the newer https://github.com/microsoft/mssql-jdbc/releases/tag/v11.2.1 version. Its currently still referring to 11.2.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3cded3d0-9d0a-ce94-1c91-21de62e3ddaf
* Version Independent ID: c14c4066-056b-faea-0a28-5eba2c544a43
* Content: [Download - JDBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver16)
* Content Source: [docs/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@rgl -- Rui, thank you for your feedback.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
I've pushed an update to the docs. It should be reflected within the next couple of hours.

Thanks,
David

#please-close
