### ISSUE TITLE
The zip file is broken

### ISSUE THREAD

**Issue by rgl** [MicrosoftDocs/sql-docs#8320]
The referred zip file is broken. Please see https://github.com/dgalbraith/chocolatey-packages/issues/448.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3cded3d0-9d0a-ce94-1c91-21de62e3ddaf
* Version Independent ID: c14c4066-056b-faea-0a28-5eba2c544a43
* Content: [Download - JDBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver16)
* Content Source: [docs/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@rgl -- Rui, thank you again.

@David-Engel -- David, please look into this issue as well.

**Comment by David-Engel** [comment]
Strange. It appears and extracts correctly using Windows built-in Compressed Folder Tools. We'll have to look and see what is causing it to appear that way in 7-zip.

**Comment by David-Engel** [comment]
I filed an issue in the source repo since this repo is just for doc issues.
Ref: https://github.com/microsoft/mssql-jdbc/issues/1978

Thanks,
David

#please-close
