### ISSUE TITLE
 Operating system support list is very misleading

### ISSUE THREAD

**Issue by paranoidloyd** [MicrosoftDocs/sql-docs#8324]
The Operating system support list is very misleading and potentially costing small business thousands of dollars that they don't need to spend on a standard license. There needs to be an asterisk next to the Windows Server 2022 Standard explaining that this also covers the OEM Essentials version, most people (including the sales team at Dell) don't understand that the essentials version is no longer a separate version from the standard version. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5dbbe35-6dd7-6ca7-3966-ee9416304d99
* Version Independent ID: c5dbbe35-6dd7-6ca7-3966-ee9416304d99
* Content: [SQL Server 2019: Hardware & software requirements - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-2019?view=sql-server-ver15)
* Content Source: [docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-2019.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-2019.md)
* Service: **sql**
* Sub-service: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@paranoidloyd -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
@paranoidloyd - note that we added essentials to this table in the noted PR. 

Thank you for submitting the request.
