### ISSUE TITLE
Download SSMS Preview link doesn't take you anywhere and doesn't download anything

### ISSUE THREAD

**Issue by MeatRocket** [MicrosoftDocs/sql-docs#8338]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
@MeatRocket Can you please clarify the issue?  When I go to https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16#feedback and select the text that says "Download SSMS 19":

![image](https://user-images.githubusercontent.com/98599126/205345074-beb9c41e-a521-4c41-937d-30ce8f4c7c13.png)

I then get take to this page:

https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms-19?view=sql-server-ver16

From this page, if I select "Download SQL Server Management Studio (SSMS) 19 (Preview) then the download starts for me.  

![image](https://user-images.githubusercontent.com/98599126/205345371-0a839d11-2106-4d35-8587-0e54ed5c8e0d.png)

Here is the direct download link:

https://go.microsoft.com/fwlink/?linkid=2203303&clcid=0x409

If this does not work for you, can please provide more details on what does occur?
