### ISSUE TITLE
Properties cannot be seen in Management Studio for Azure SQL

### ISSUE THREAD

**Issue by leftpeg01** [MicrosoftDocs/sql-docs#8341]
It should probably be noted that the section entitled **View the properties of a full-text index with Management Studio** is not supported for Azure SQL in the latest released version (and previous versions) of SQL Server Management Studio.

Regards,
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5332b85c-c67f-2dfe-3fec-d4bc978822de
* Version Independent ID: 6239c2b0-c81e-f22c-bdff-1393cd372aab
* Content: [Create and Manage Full-Text Indexes - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/search/create-and-manage-full-text-indexes?view=sql-server-ver16)
* Content Source: [docs/relational-databases/search/create-and-manage-full-text-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/search/create-and-manage-full-text-indexes.md)
* Service: **sql**
* Sub-service: **search**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@leftpeg01 -- thank you for your feedback.

@rwestMSFT -- please look into this issue.

**Comment by rwestMSFT** [comment]
Thanks @leftpeg01. To clarify, are you able to view the properties using Transact-SQL commands at least?

**Comment by leftpeg01** [comment]
That is correct. You can get the properties with Transact-SQL, but not via
the menu item.

If you try and access them visually via the table context menu (Full-Text
Index -> Properties) you get a dialog that says:
Cannot load Full-Text General Catalog Properties form.
Object of type 'SearchPropertyList' is not supported on Microsoft Azure SQL
Database. (Microsoft.SqlServer.Smo)

I see that SSMS 19 is coming out soon, so perhaps they have integrated some
of these features that are available for stand alone installations of SQL
Server, but not currently available for Azure SQL in SSMS 18.

**Comment by rwestMSFT** [comment]
@leftpeg01 Thank you for confirming. I have discussed this issue with the product team, and we can confirm that the feature is not supported in SSMS 19 either. I will be updating the article to note the support for Azure SQL, for this particular feature, is limited to Transact-SQL.

Once that change is merged, this issue will automatically close, and the updated article will be published in the next few days.
