### ISSUE TITLE
Incomplete/Wrong documentation for Import from Azure Blob Storage

### ISSUE THREAD

**Issue by manuel284** [MicrosoftDocs/sql-docs#8345]
Content: https://learn.microsoft.com/en-us/sql/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage?view=sql-server-ver16
Content source: https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage.md

The documentation says:
> The external data source must be created with a database scoped credential that uses the SHARED ACCESS SIGNATURE identity.

This is not true and also doesn't work if we try to import data from a Blob Storage that's only available through a private endpoint.
If we try this, we always get the following error:
> Cannot bulk load because the file "filename" could not be opened. Operating system error code 5(Access is denied.).

See [this question](https://learn.microsoft.com/en-us/answers/questions/967040/bulk-insert-from-blob-storage-in-private-network.html):
> I changed firewall setting 'Disabled' to 'Enabled from selected virtual network and IP addresses' and use managed Id of Azure SQL Database, then I could call bulk insert.

Also, there is [this blog](https://www.cloudshift.nl/blog/2021/12/sql-bulk-insert-from-a-private-azure-storage-account) post explaining in detail how to use Managed Identity.

**Comment by rwestMSFT** [comment]
Thanks @manuel284, we'll look into this as part of our article refresh cycle.

**Comment by rwestMSFT** [comment]
@manuel284 We are tracking this item internally (AB#70883), so this issue is being closed. Thanks again for your feedback. When we have an update to share, we will let you know here. In the meanwhile, please feel free to leave additional feedback.
