### ISSUE TITLE
Add troubleshooting steps for registering Subscription to Resource Provider 

### ISSUE THREAD

**Issue by charmainewkchan** [MicrosoftDocs/sql-docs#8348]
We found that this step (registering a subscription for the Microsoft.azurearcdata resource provider) is often missed and we are trying to improve documentation to prevent users from running into this issue. 

If users don't register their subscription and install the extension, they will see the following success message, but will not see their SQL server instances on Azure:

> Installing SQL Server - Azure Arc extension. This may take 5+ minutes.
> SQL Server - Azure Arc extension is successfully installed. If one or more SQL Server instances are up and running on the server, Arc
> -enabled SQL Server instance resource(s) will be visible within a minute on the portal.
> Newly installed instances or instances started now will show up within an hour.

Would it be possible to add a troubleshooting section asking customer to register their subscription if the run into the following issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa2343e7-8920-d26c-e167-394ddb5a5878
* Version Independent ID: 159d34d5-1f2d-5028-88a6-4bf6d04f0ffd
* Content: [Connect to Azure Arc - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/connect?view=sql-server-ver16&tabs=azure%2Cwindows#feedback)
* Content Source: [docs/sql-server/azure-arc/connect.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/azure-arc/connect.md)
* Service: **sql**
* GitHub Login: @anosov1960
* Microsoft Alias: **sashan**

**Comment by WilliamAntonRohm** [comment]
@charmainewkchan -- Charmaine, thank you for your feedback and suggestion.

@anosov1960 -- Sasha, please look into this issue.

**Comment by twright-msft** [comment]
@MikeRayMSFT  - @MikeRay - can you please add this to your to do list?  We can put something on the troubleshooting docs for Arc SQL Server onboarding. https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/connect-at-scale?view=sql-server-ver15&tabs=azure%2Cwindows#troubleshoot-azure-extension-for-sql-server  
Also - we should have this troubleshooting section be a snippet that is included in both that article linked above and in this article: https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/connect?view=sql-server-ver15&tabs=azure%2Cwindows#validate-your-arc-enabled-sql-server-resources

**Comment by MikeRayMSFT** [comment]
I think that changes in the deployment experience, and updates to documentation may have resolved this issue. 

See:
- [Automatically connect your SQL Server to Azure Arc](https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/automatically-connect?view=sql-server-ver16)
- [Connect SQL Server instances to Azure Arc](https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/connect?view=sql-server-ver16&tabs=windows#connect-sql-server-instances-to-azure-arc)

**Comment by MikeRayMSFT** [comment]
Closing - discussing internally with PG.
