### ISSUE TITLE
Link to Andreas's blog post is broken

### ISSUE THREAD

**Issue by Bysza** [MicrosoftDocs/sql-docs#8366]
The link to Andreas's blog post is broken - the page does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81b47032-2e86-a8fd-cdab-c362ccad8f7b
* Version Independent ID: d19b09f6-06a6-67f6-5284-0bad0f1d53c9
* Content: [Server-level roles - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/server-level-roles?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/authentication-access/server-level-roles.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/server-level-roles.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@Bysza -- thank you for your feedback.  Currently Andreas' entire site is down.  I will check again on Monday.

**Comment by rwestMSFT** [comment]
I spoke to Andreas and I'm going to point it to an archive of the site in the meantime, and refresh the article a little.

**Comment by rwestMSFT** [comment]
#reassign:rwestMSFT
