### ISSUE TITLE
Reference Variable (For SQL Server)

### ISSUE THREAD

**Issue by michelmaxas** [MicrosoftDocs/sql-docs#8371]
I have a suggestion for MS SQL Server, it would be great if MS could give more power to data type SYSNAME (or another), where you could use a string to reference a table or column name, avoiding making the developers create a whole Dynamic-SQL just to select a specific table or column, for example:
`DECLARE @tableName AS SYSNAME;
SET @tableName = 'Person.Person';
SELECT * FROM @tableName;`

What I'm talking about is something akin to C# "ref" prefix, after all Dynamic-SQL increases the LOG File, and if it only for getting a specific Column or Table, you shouldn't need a whole Dynamic-SQL.

**Comment by WilliamAntonRohm** [comment]
@michelmaxas -- thank you for your suggestion!  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)
