### ISSUE TITLE
Powershell code sample has error 

### ISSUE THREAD

**Issue by propellor** [MicrosoftDocs/sql-docs#8375]
[Enter feedback here]

Code sample should be as below, removing the 'ClusterParameter' after Set-ClusterParameter. 

Get-ClusterResource $nameResource | Set-ClusterParameter HostRecordTTL 300 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5dab67c-0b02-71a8-bba0-416be62e5d52
* Version Independent ID: c0f9db5f-668e-aac1-f789-cd7e34bdf316
* Content: [Availability group: Prerequisites, restrictions, & recommendations - SQL Server Always On](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability?view=sql-server-ver16)
* Content Source: [docs/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability.md)
* Service: **sql**
* Sub-service: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by TimShererWithAquent** [comment]
Thanks @propellor - we're fixing now.
