### ISSUE TITLE
SET Single User does not work for SQL Serverless

### ISSUE THREAD

**Issue by dbszepesi** [MicrosoftDocs/sql-docs#8377]
Trying to run the script from this article against a SQL Serverless DB and I get all these errors:

Msg 15869, Level 16, State 11, Line 34
SINGLE_USER is not supported for ALTER DATABASE.
Msg 15869, Level 16, State 11, Line 37
READ_ONLY is not supported for ALTER DATABASE.
Msg 15869, Level 16, State 11, Line 40
MULTI_USER is not supported for ALTER DATABASE.

Is there a SQL Serverless version of this? I am trying to run the following:

alter database current collate Latin1_General_100_BIN2_UTF8

And get the error:

Msg 5030, Level 16, State 5, Line 5
The database [DBNAME] could not be exclusively locked to perform the operation.
Msg 5072, Level 16, State 1, Line 5
ALTER DATABASE failed. The default collation of database '[DBNAME]' cannot be set to Latin1_General_100_BIN2_UTF8.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b67ab534-229d-f12a-6216-9550d790ea42
* Version Independent ID: 529e1ec2-00c5-9c13-1a75-dfc183765aff
* Content: [Set a database to single-user mode - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/databases/set-a-database-to-single-user-mode?view=sql-server-ver16)
* Content Source: [docs/relational-databases/databases/set-a-database-to-single-user-mode.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/set-a-database-to-single-user-mode.md)
* Service: **sql**
* Sub-service: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hi @dbszepesi! This article applies to SQL Server, which does not include pools in Azure Synapse. The available `ALTER DATABASE` syntax options for Azure Synapse are provided here: https://learn.microsoft.com/sql/t-sql/statements/alter-database-transact-sql?view=azure-sqldw-latest&preserve-view=true&tabs=sqlpool

**Comment by dbszepesi** [comment]
Thanks for the quick response. The article is tagged as for all SQL versions, I guess that does not explicitly mean Synapse?

Applies to:  SQL Server (all supported versions)
