### ISSUE TITLE
Update required to include how to export large database bacpac files

### ISSUE THREAD

**Issue by Frankd4** [MicrosoftDocs/sql-docs#8394]
Hi Team,

Please update the Export & Import page to include examples for syntax while exporting 
large databases for example 500 GB, 1 TB or greater databases. Many customers try to Export & Import very large databases and get stuck.

The examples do not currently mention how to do this and what type of issues you could face, example out of memory, temp location etc...
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35acf4f8-a716-20bb-b08b-5fe3541e988b
* Version Independent ID: aaabdf4f-3f99-3e06-a5f2-772e4539acd5
* Content: [SqlPackage Export - SQL Server](https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-export?view=sql-server-ver15)
* Content Source: [docs/tools/sqlpackage/sqlpackage-export.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage/sqlpackage-export.md)
* Service: **sql**
* Sub-service: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
@Frankd4 - there's a troubleshooting page for this specific info https://learn.microsoft.com/en-us/sql/tools/sqlpackage/troubleshooting-issues-and-performance-with-sqlpackage?view=sql-server-ver15

There's no magic wand for databases of that size, but sizing the client running SqlPackage appropriately is helpful: https://learn.microsoft.com/en-us/sql/tools/sqlpackage/troubleshooting-issues-and-performance-with-sqlpackage?view=sql-server-ver15#client-resource-consumption

**Comment by dzsquared** [comment]
#assign:dzsquared

**Comment by Frankd4** [comment]
Thank Drew. Based on my experience adding more examples for this specific large database export would definitely help.

**Comment by dzsquared** [comment]
#please-close
