### ISSUE TITLE
Typo mistake in username on the page content

### ISSUE THREAD

**Issue by chinteshsoni** [MicrosoftDocs/sql-docs#8399]
Hi,
It seems there is a typo mistake on the page. Please find link below;
https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions?view=sql-server-ver16#Agent
Underneath "Description of Service Account" title , third line it says "a member if sysamin - instead of sysadmin.
Thank you.

Chintesh
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9b3831a3-6c86-243c-4b07-8960e4d06d7b
* Version Independent ID: dfd7599d-88eb-99f2-c227-0c9dc82bfd87
* Content: [Configure Windows service accounts and permissions - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@chinteshsoni -- Chintesh, thank you for catching that.  I am updating the article.

**Comment by rwestMSFT** [comment]
@chinteshsoni @WilliamAntonRohm I can't seem to find the typo, and the edit history on the article doesn't reflect any changes to that line for several months.

#please-close
