### ISSUE TITLE
Contradiction in documentation

### ISSUE THREAD

**Issue by DanielKeogh** [MicrosoftDocs/sql-docs#8405]
This documentation indicates that "sysobjects" is a view.

https://learn.microsoft.com/en-us/previous-versions/sql/sql-server-2005/ms187376(v=sql.90)

This documentation indicates that "sysobjects" is a table.
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/mapping-system-tables-to-system-views-transact-sql.md

**Comment by WilliamAntonRohm** [comment]
@DanielKeogh -- Daniel, thank you for your feedback.  The older documentation is retired and no longer authoritative.
