### ISSUE TITLE
Wrong link of `Column Level Encryption (CLE)`

### ISSUE THREAD

**Issue by nomba** [MicrosoftDocs/sql-docs#8408]
There is a paragraph:

> SQL Server provides several types of encryption that help protect sensitive data, including [Transparent Data Encryption (TDE)](https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption?view=sql-server-ver16), [Column Level Encryption](https://learn.microsoft.com/en-us/sql/t-sql/functions/cryptographic-functions-transact-sql?view=sql-server-ver16) (CLE), and [Backup Encryption](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/backup-encryption?view=sql-server-ver16).

The link of `Column Level Encryption  (CLE)` points to Cryptographic functions article. I guess, it's a typo and you meant another article, it might be this: [Encrypt a Column of Data](https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/encrypt-a-column-of-data)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8a49313-385a-3f77-5468-f6b5c631adcb
* Version Independent ID: 913fde38-b0c6-6abc-1a7f-69ae976a9c30
* Content: [Extensible Key Management using Azure Key Vault - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/extensible-key-management-using-azure-key-vault-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/encryption/extensible-key-management-using-azure-key-vault-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/extensible-key-management-using-azure-key-vault-sql-server.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@nomba -- Sergey, thank you for catching this.  I am updating the article.
