### ISSUE TITLE
Incorrect name

### ISSUE THREAD

**Issue by SQLSteinar** [MicrosoftDocs/sql-docs#8410]
In SQL Server 2022 (and perhaps earlier versions to?) this option is named "recovery interval (min)" in sys.configurations. It should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8da8755-3783-0ca0-d1d0-ce289f1e785f
* Version Independent ID: 53fe9f1e-4eef-9207-ec68-62fa01c8f81c
* Content: [Configure the recovery interval Server Configuration Option - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-recovery-interval-server-configuration-option?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/configure-the-recovery-interval-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-recovery-interval-server-configuration-option.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@SQLSteinar Thanks for your feedback. If you don't mind, please create a pull request with this modification, using the pencil icon on the top right of the article.

**Comment by SQLSteinar** [comment]
In SQL Server 2022 (and perhaps earlier versions to?) this option is named "recovery interval (min)" in sys.configurations. It should be updated.

**Comment by SQLSteinar** [comment]
Done. I think I managed to do correctly...

**Comment by rwestMSFT** [comment]
@SQLSteinar The pencil icon I'm referring to is on the Docs article itself. Once you click it, you can then click the next pencil icon that appears on GitHub. 
![image](https://user-images.githubusercontent.com/97149825/209201910-fc9cace9-8a7b-4991-afb3-52cd716cd355.png)

**Comment by rwestMSFT** [comment]
@SQLSteinar I had some time today to look at doing this change. The refreshed article will be published in the near future. Thanks again for raising this.
