### ISSUE TITLE
DatabaseWaitStatistcsEvent miss an "i" in the OperationName column name in AzureDiagnostics 

### ISSUE THREAD

**Issue by erincon01** [MicrosoftDocs/sql-docs#8416]
Hi.

an "i" is missing in the OperationName column.
Run this KQL in Log Analytics to see the result.

// Wait stats 
// Wait stats over the last hour, by Logical Server and Database. 
AzureDiagnostics
| where ResourceProvider == "MICROSOFT.SQL" and OperationName  == "**DatabaseWaitStatistcsEvent**"
| parse _ResourceId with * "/microsoft.sql/servers/" LogicalServerName "/databases/" DatabaseName
| project TimeGenerated, Category, ResourceGroup, LogicalServerName_s, DatabaseName_s, wait_type_s, delta_wait_time_ms_d, delta_waiting_tasks_count_d

**Comment by erincon01** [comment]
Hello William.

in SQL Azure Databases you can configure the database to log diagnosis and performance issues to Log Analytics.
https://learn.microsoft.com/en-us/azure/azure-monitor/insights/azure-sql

If you setup that login, then the KQL query shared earlier will return rows.
In the query ..> OperationName == "DatabaseWaitStatistcsEvent"
see data the data should be:
DatabaseWaitStatist**I**csEvent
instead of
DatabaseWaitStatistcsEvent.

There is a gramma error.
however, if you add the i, existing queries will fail, so I will have to concatenate this for when you fix it:
(OperationName == "DatabaseWaitStatistcsEvent" or OperationName == "DatabaseWaitStatisticsEvent" )

**Comment by WilliamAntonRohm** [comment]
@erincon01 -- thank you for clarifying!  I'll fix it.

**Comment by WilliamAntonRohm** [comment]
@erincon01 -- apologies for the delayed reply.  I don't see "DatabaseWaitStatistcsEvent" or "KQL" in the referenced article.  Please let me know where you found the typo.

**Comment by erincon01** [comment]
Hi William.
 If I am correct you refer to documentation issues, not to product related, correct? If that is the case, I should have opened the issue to the product team, not to this team. Btw, what is the forum to inform the issue to the product team? Thanks.

**Comment by WilliamAntonRohm** [comment]
@erincon01 -- thank you for your followup and you are correct.  Please add your feedback here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)
