### ISSUE TITLE
PYODBC has not worked since 2015

### ISSUE THREAD

**Issue by Shelby86** [MicrosoftDocs/sql-docs#8417]
[Enter feedback here]
PYODBC has not worked since 2015 and still no one has fixed it

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81d157a2-8c94-ad05-47ed-8baebb156948
* Version Independent ID: 37dd4c6b-a214-7a72-fe59-89a42b9d05a2
* Content: [Python SQL Driver - pyodbc - Python driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/python/pyodbc/python-sql-driver-pyodbc?source=recommendations&view=sql-server-ver16)
* Content Source: [docs/connect/python/pyodbc/python-sql-driver-pyodbc.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/python/pyodbc/python-sql-driver-pyodbc.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@Shelby86 -- thank you for your feedback.  Please add this as a product issue here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)
