### ISSUE TITLE
Ambiguity in document (as one of the instances)

### ISSUE THREAD

**Issue by Shanga1** [MicrosoftDocs/sql-docs#8418]
Link: https://learn.microsoft.com/en-us/sql/database-engine/sql-server-business-continuity-dr?view=sql-server-ver16#always-on-failover-cluster-instances

`An FCI can participate in an availability group as one of the instances hosting either a primary or secondary replica.`

Does this mean that only 1 side of the AG can be an FCI and the other side must be a standalone instance? Please can you clarify?

The term `as one of the` is confusing me.

**Comment by WilliamAntonRohm** [comment]
Related to #8419
