### ISSUE TITLE
About suppprt for FCIs in distributed AG

### ISSUE THREAD

**Issue by Shanga1** [MicrosoftDocs/sql-docs#8420]
Link: https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/distributed-availability-groups?view=sql-server-ver16

Microsoft, please can you confirm that - in a distributed availability group,

1. Can one of the replicas in one of the AGs can be an FCI?
2. Can one of the replicas in both the AGs be an FCI?
3. Can both the replicas in one of the AGs be an FCI?
4. Can both the replicas in both the AGs be an FCI?

Please can you clarify since the documentation isn't giving this information?

**Comment by kfarlee** [comment]
Any or all of the replicas in either of the AGs that belong to a Distributed AG may be FCI instances.  The only caveat is that the Distributed AG will not make use of the cluster infrastructure for managing the distributed AG itself.

**Comment by rwestMSFT** [comment]
I am closing this issue, as it appears it was answered.
