### ISSUE TITLE
Query is not accurate in the documentation

### ISSUE THREAD

**Issue by emad-almousa** [MicrosoftDocs/sql-docs#8421]
Hi Team,

For the following query, two observations for your consideration:

SELECT
 t.[commit_time] AS [CommitTime] 
 , t.[principal_name] AS [UserName]
 , l.[EmployeeID]
 , l.[AccessOperationDescription]
 , l.[Timestamp]
 , l.[ledger_operation_type_desc] AS Operation
 FROM [AccessControl].[KeyCardEvents_Ledger] l
 JOIN sys.database_ledger_transactions t
 ON t.transaction_id = l.ledger_transaction_id
 ORDER BY t.commit_time DESC;

1. correct predicate should be:
t.transaction_id = l.ledger_start_transaction_id
instead of
t.transaction_id = l.ledger_transaction_id

2. Also, there is No column with the name ledger_operation_type_desc associated with the table [AccessControl].[KeyCardEvents_Ledger] I think it should be removed from the query.

Thanks,
Emad

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff26ae33-7433-7e49-4cce-b6021c72a53c
* Version Independent ID: ff26ae33-7433-7e49-4cce-b6021c72a53c
* Content: [Create and use append-only ledger tables - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/ledger/ledger-how-to-append-only-ledger-tables?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/ledger/ledger-how-to-append-only-ledger-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/ledger/ledger-how-to-append-only-ledger-tables.md)
* Service: **sql-database**
* Sub-service: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@emad-almousa -- Emad, thank you for your detailed feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @emad-almousa, thanks for submitting this.

@Pietervanhove - Pieter, do you mind checking on this?

**Comment by VanMSFT** [comment]
Tied to https://github.com/MicrosoftDocs/sql-docs/pull/8424

**Comment by Pietervanhove** [comment]
Hi @emad-almousa,

You're mixing up the ledger table and the ledger view.
The query in the documentation is based on the ledger view.
The field l.ledger_start_transaction_id doesn't exist in the view and should be l.ledger_transaction_id, like in the example.
The same applies for the field ledger_operation_type_desc which does exist in the ledger view.

Best regards
Pieter

**Comment by MashaMSFT** [comment]
Hi @emad-almousa , thanks for contacting Microsoft! Since Pieter was able to clarify the issue, I'll go ahead and close out this request. Please feel free to comment should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of  your day!
Masha from the SQL Docs team
#please-close
