### ISSUE TITLE
Pre-requisite ALLOW_SNAPSHOT_ISOLATION is required to run sp_verify_database_ledger

### ISSUE THREAD

**Issue by emad-almousa** [MicrosoftDocs/sql-docs#8422]
Hi Team,

when I ran sp_verify_database_ledger the following error was thrown:

**Msg 37498, Level 16, State 2, Procedure sp_verify_database_ledger, Line 1 [Batch Start Line 0]
Snapshot isolation must be enabled on the database when sp_verify_database_ledger is executed.**

This was executed  in SQL Server 2022 Developer Edition:
Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)   Oct  8 2022 05:58:25   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Home 10.0 <X64> (Build 19044: ) 

So, I think you need to add a pre-requisite remark that ledger database should have SNAPSHOT ISOLATION ON:

USE [master]
GO

GO
ALTER DATABASE [XXXXXXX] SET ALLOW_SNAPSHOT_ISOLATION ON
GO

Regards,
Emad

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e908d0d1-d694-4247-cdec-fa6f4aad0389
* Version Independent ID: e908d0d1-d694-4247-cdec-fa6f4aad0389
* Content: [Verify a ledger table to detect tampering - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/ledger/ledger-verify-database?view=sql-server-ver16&tabs=t-sql-automatic)
* Content Source: [docs/relational-databases/security/ledger/ledger-verify-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/ledger/ledger-verify-database.md)
* Service: **sql-database**
* Sub-service: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@emad-almousa -- Emad, thank you for your clear feedback.


@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Tied to https://github.com/MicrosoftDocs/sql-docs/pull/8423

**Comment by VanMSFT** [comment]
FYI @Pietervanhove

**Comment by MashaMSFT** [comment]
Hi @emad-almousa , thanks so much for reaching out! The PR has been merged so this issue seems resolved. I'll go ahead and close it out but please feel free to comment should you need anything further.

Thanks again for contacting Microsoft and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
