### ISSUE TITLE
no details on connecting SQL server using domain account

### ISSUE THREAD

**Issue by Rajan23** [MicrosoftDocs/sql-docs#8426]
It would be great if there is some info on how to use domain authentication (instead of windows and sql) to connect to the sql server. Domain authentication comes under windows authentication? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b51309c7-1370-863d-4a44-eefe2d381161
* Version Independent ID: e56a7f00-aa5a-c0e7-3862-77b3e85f3a65
* Content: [Connecting to an Instance of SQL Server - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/create-program/connecting-to-an-instance-of-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/server-management-objects-smo/create-program/connecting-to-an-instance-of-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/server-management-objects-smo/create-program/connecting-to-an-instance-of-sql-server.md)
* Service: **sql**
* Sub-service: ****
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by rwestMSFT** [comment]
Active Directory authentication is the same thing as Windows authentication, yes. Note that the example assumes that the account your code is running under, has access to the database server.

#please-close
