### ISSUE TITLE
Polybase for SQL Server 2022 on Linux

### ISSUE THREAD

**Issue by kentmaxwell** [MicrosoftDocs/sql-docs#8428]
[Enter feedback here]
This documentation suggests that Polybase running on SQL Server 2022 on Linux has the same capabilities as Polybase running on SQL Server 2022 on Windows.  This is NOT the case.  Polybase on Linux is the same as SQL Server 2022 and SQL Server 2019.  

Please update the documentation to reflect this reality.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7ebefef-f8c5-e429-269e-1ef7a96264fd
* Version Independent ID: a8009495-9bb9-87f4-85af-0ac0074749e7
* Content: [Introducing data virtualization with PolyBase - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/polybase/polybase-guide?view=sql-server-ver16)
* Content Source: [docs/relational-databases/polybase/polybase-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-guide.md)
* Service: **sql**
* Sub-service: **polybase**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@kentmaxwell -- Kent, thank you again for your feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @kentmaxwell for taking the time to provide this feedback, your suggestions help improve our documentation. Will review internally with the product group. If you have any specific examples, code samples to demonstrate, etc., this would be helpful.

**Comment by WilliamDAssafMSFT** [comment]
Hi @Kentmaxwell I understand you're already talking to @HugoMSFT to clear up the confusion. PolyBase for SQL Server 2022 on Linux is indeed SQL Server 2022. Sounds like the product group is engaging on that, great! I'll close this issue.
