### ISSUE TITLE
Trace Flag 460 doesn't include SQL 2016 information

### ISSUE THREAD

**Issue by josh-simar** [MicrosoftDocs/sql-docs#8430]
on the Trace Flag documentation trace flag 460 doesn't include information that it works on SQL 2016 but according to the KB article it does.
https://support.microsoft.com/en-us/topic/kb4468101-improvement-optional-replacement-for-string-or-binary-data-would-be-truncated-message-with-extended-information-in-sql-server-2016-and-2017-a4279ad6-1d3b-3960-77ef-c82a909f4b89

**Comment by josh-simar** [comment]
#8431 is PR. Don't know how to do the tie proper.

**Comment by WilliamAntonRohm** [comment]
@josh-simar -- thank you for that PR.  It has been merged into our live documentation.

For future reference, just add a commit comment starting with `Fixes` to link a PR to an issue:
```
Fixes MicrosoftDocs/sql-docs/issues/8430
```
