### ISSUE TITLE
Type-O in page

### ISSUE THREAD

**Issue by ElvisVangDBA** [MicrosoftDocs/sql-docs#8433]
[Enter feedback here]
The section that talks about SQLCHECK has a type-o, actually spelled SCLCHECK in the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e38f9b5-1664-79f1-9647-1c49f201dbca
* Version Independent ID: 4e38f9b5-1664-79f1-9647-1c49f201dbca
* Content: [Certificate requirements for SQL Server - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/certificate-requirements?view=sql-server-ver16#certificate-requirements-for-sql-server-encryption)
* Content Source: [docs/database-engine/configure-windows/certificate-requirements.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/certificate-requirements.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @sevend2
* Microsoft Alias: **v-sidong**

**Comment by rwestMSFT** [comment]
#assign:rwestMSFT

**Comment by rwestMSFT** [comment]
@ElvisVangDBA Thanks, this should be fixed as part of the next publication cycle.

**Comment by rwestMSFT** [comment]
#please-close
