### ISSUE TITLE
Incomplete Description of BULK INSERT FORMAT

### ISSUE THREAD

**Issue by ClarkFrazier** [MicrosoftDocs/sql-docs#8435]
[Enter feedback here]

Incomplete Description of BULK INSERT FORMAT. Does not enumerate available file formats and the earliest supporting SQL Server version.
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe073190-9591-00f0-0d07-8f1fcf16bbc0
* Version Independent ID: 769fb224-8abc-29b4-355d-bab3417be8c1
* Content: [Use a format file to bulk import data - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/import-export/use-a-format-file-to-bulk-import-data-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/import-export/use-a-format-file-to-bulk-import-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/use-a-format-file-to-bulk-import-data-sql-server.md)
* Service: **sql**
* Sub-service: **data-movement**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@ClarkFrazier thanks for your feedback. SQL Server versions would be 2016 and higher. Documentation relating to SQL Server 2005 - 2014 is available in the [previous versions](https://learn.microsoft.com/en-us/previous-versions/sql/) archive.

As for available file formats, the data formats are covered in [Data formats for bulk import or bulk export (SQL Server)](https://learn.microsoft.com/en-us/sql/relational-databases/import-export/data-formats-for-bulk-import-or-bulk-export-sql-server).

If you have any more questions, please let us know.

**Comment by WilliamAntonRohm** [comment]
@ClarkFrazier -- thank you for your considered feedback.

@rwestMSFT -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
