### ISSUE TITLE
Typo in your install command

### ISSUE THREAD

**Issue by Aarav568** [MicrosoftDocs/sql-docs#8448]
[Enter feedback here]
One of the commands on your page has a typo in Step 4 of "Install SQL Server"  instructions.
Thank you.

<h3>Quickstart: Install SQL Server and create a database on Ubuntu</h3>
<h4>Step 4: </h4>

```diff
sudo apt-get update
- sudo apt-get install -y mssql-server
+ sudo apt-get install -y mysql-server
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@Aarav568 -- thank you for catching this.  I am updating the article.

**Comment by rwestMSFT** [comment]
There's no typo here. SQL Server is `mssql-server`. If you're looking for MySQL documentation, please reference https://learn.microsoft.com/en-us/azure/mysql/.

**Comment by rwestMSFT** [comment]
#please-close
