### ISSUE TITLE
The back up and restore tutorial needs updating

### ISSUE THREAD

**Issue by craigs100** [MicrosoftDocs/sql-docs#8458]
[Enter feedback here]
The tutorial needs updating. the "Manage" screen shown looks nothing like ADS now in 2023. I'm using 1.40.2 on Linux.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44eeec53-091c-6666-1d84-dd900496d291
* Version Independent ID: 3fbbb1cc-ea77-4b3a-ad96-dd0d561c6908
* Content: [Back up and restore a database - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/tutorial-backup-restore-sql-server?view=sql-server-ver16)
* Content Source: [docs/azure-data-studio/tutorial-backup-restore-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/tutorial-backup-restore-sql-server.md)
* Service: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
Hi, @[craigs100](https://github.com/craigs100)

First, we apologize for the delayed response.

Thank you for your feedback! 

The images should be updated by the end of the week.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site or the [Q & A](https://docs.microsoft.com/en-us/answers/products/sql-server) site.
