### ISSUE TITLE
SQL Server 2022

### ISSUE THREAD

**Issue by Rajini09** [MicrosoftDocs/sql-docs#8459]
[Enter feedback here]
Hi, Can you confirm if this is applicable for upgrade to SQL Server 2022.  The very first line states only SQL Server 2019(does not mentions SQL 2022). Here it is from the doc "In this guide, you learn how to upgrade your user databases from previous versions of SQL Server to SQL Server 2019 by using the Data Migration Assistant (DMA)."

Please confirm.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1ab40d-6585-03f3-bec9-f8c14eefe453
* Version Independent ID: 3617b434-412c-9694-c3d5-dbce2825ebe4
* Content: [Upgrade SQL Server to SQL Server 2019 - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/migrate/guides/sql-server-to-sql-server-upgrade-guide?view=sql-server-ver16)
* Content Source: [docs/sql-server/migrate/guides/sql-server-to-sql-server-upgrade-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/migrate/guides/sql-server-to-sql-server-upgrade-guide.md)
* Service: **sql**
* Sub-service: **migration-guide**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by rwestMSFT** [comment]
@Rajini09 We've discussed this internally and the article is due for a refresh.

SQL Server 2022 is definitely supported as an upgrade target.

#please-close
