### ISSUE TITLE
Driver won't install on Windows 10 Enterprise

### ISSUE THREAD

**Issue by joshprittse** [MicrosoftDocs/sql-docs#8462]
Used the download driver link at the top of this page and when trying to install it on a Windows 10 Enterprise machine it says it is not supported on this operating system.  Do you have a version of this driver that works on Windows 10 Enterprise?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e928f81-9ba4-f42f-9718-fc1ce9e2aa92
* Version Independent ID: 7bc576d6-100a-fc69-36a9-2c69a2b67bc5
* Content: [Installing OLE DB Driver for SQL Server - OLE DB Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/oledb/applications/installing-oledb-driver-for-sql-server?view=sql-server-ver16)
* Content Source: [docs/connect/oledb/applications/installing-oledb-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/oledb/applications/installing-oledb-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
@joshprittse 

Windows 10 is supported by the Microsoft OLE DB Driver for SQL Server.
https://learn.microsoft.com/en-us/sql/connect/oledb/applications/support-policies-for-oledb-driver-for-sql-server?view=sql-server-ver16#supported-operating-system-versions

Did you download the correct installer for your platform type? If you are running Windows 10 **x64 / 64-bit**, you need the x64 installer. If you are running Windows 10 **x86 / 32-bit**, you need the x86 installer.

Regards,
David

**Comment by WilliamAntonRohm** [comment]
@joshprittse - Josh, I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
