### ISSUE TITLE
UniversalAuthentication sample does not work

### ISSUE THREAD

**Issue by HitenBhavsarMSFT** [MicrosoftDocs/sql-docs#8465]
Below sample did not work with the new SQLPackage, Please update with working sample. 

**failed sample:**
# example export connecting using Azure Active Directory universal authentication
SqlPackage /Action:Export /TargetFile:"C:\AdventureWorksLT.bacpac" /UniversalAuthentication=True \
    /SourceConnectionString:"Server=tcp:{yourserver}.database.windows.net,1433;Initial Catalog=AdventureWorksLT;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
    
   
**Working Sample:**
sqlpackage.exe /a:Export /tf:"C:\Scripts\sample.bacpac" /scs:"Data Source=dbap01.database.windows.net;Initial Catalog=sample;" /ua:True

![image](https://user-images.githubusercontent.com/72768193/211077271-f19c4210-e754-4f53-8d2f-50356cf0697b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35acf4f8-a716-20bb-b08b-5fe3541e988b
* Version Independent ID: aaabdf4f-3f99-3e06-a5f2-772e4539acd5
* Content: [SqlPackage Export - SQL Server](https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-export?view=sql-server-ver16)
* Content Source: [docs/tools/sqlpackage/sqlpackage-export.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage/sqlpackage-export.md)
* Service: **sql**
* Sub-service: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by HitenBhavsarMSFT** [comment]
SR2301060050001262

**Comment by WilliamAntonRohm** [comment]
@HitenBhavsarMSFT -- Hiten, thank you for your feedback and solution.

@dzsquared -- Drew, please look into this issue.

**Comment by rwestMSFT** [comment]
@HitenBhavsarMSFT We are closing this issue because we are tracking it internally.

You can also engage with the engineering team directly at https://github.com/microsoft/dacfx.

AB#203362
