### ISSUE TITLE
Image issue on page

### ISSUE THREAD

**Issue by jpomfret** [MicrosoftDocs/sql-docs#8467]
One of the images on this page isn't good

![image](https://user-images.githubusercontent.com/981370/211200522-c5e4717b-af8f-4c74-a4d3-43d959419bea.png)

[Affected section](https://learn.microsoft.com/en-us/sql/database-engine/install-windows/choose-a-database-engine-upgrade-method?view=sql-server-ver16#upgrade-in-place)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 916e128d-19fd-1f7d-8285-6313c4419710
* Version Independent ID: 8402af42-fdd1-2f3b-7c6a-8759e90e115f
* Content: [Choose a database engine upgrade method - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/install-windows/choose-a-database-engine-upgrade-method?view=sql-server-ver16)
* Content Source: [docs/database-engine/install-windows/choose-a-database-engine-upgrade-method.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/choose-a-database-engine-upgrade-method.md)
* Service: **sql**
* Sub-service: **install**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@jpomfret -- Jess, thank you for reporting this.  I am updating the image.

**Comment by rwestMSFT** [comment]
@jpomfret @WilliamAntonRohm Turns out the images were updated, but the old ones are being cached. I've submitted a PR that hopefully fixes the problem.

**Comment by rwestMSFT** [comment]
Looks like it's fixed now. Thanks again for reporting this, Jess.
