### ISSUE TITLE
This feature is not available with SSMS version from 17.0 onwards. This should be made explicit. Simply saying 'all supported versions' may be misleading.

### ISSUE THREAD

**Issue by TimGJ2409** [MicrosoftDocs/sql-docs#8468]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7578255e-e9ff-9501-0f8c-0670e77149ea
* Version Independent ID: 8410398f-d7f6-c5ac-7a2f-be3e0ac29cb4
* Content: [SQL Server Utility Features and Tasks - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/manage/sql-server-utility-features-and-tasks?view=sql-server-ver16)
* Content Source: [docs/relational-databases/manage/sql-server-utility-features-and-tasks.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/manage/sql-server-utility-features-and-tasks.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@TimGJ2409 -- Tim, thank you for your clear feedback.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by MikeRayMSFT** [comment]
@TimGJ2409 - thank for submitting this issue. 

Utility control point is no longer available in versions 17.X and newer. We are updating the documentation.
