### ISSUE TITLE
Missing alternative for disallowed single quote

### ISSUE THREAD

**Issue by LeszekKalibrate** [MicrosoftDocs/sql-docs#8472]
Disallow the following input characters
' Character data string delimiter
[Enter feedback here]
What is the proper alternative to disallow it, but still allow Mc'Donalds (surname) to include single quote in user's name?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 971e2142-ecc0-357f-2c9f-2f9697a79d3f
* Version Independent ID: 971e2142-ecc0-357f-2c9f-2f9697a79d3f
* Content: [SQL Server security best practices - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/sql-server-security-best-practices?view=sql-server-ver16#common-sql-threats)
* Content Source: [docs/relational-databases/security/sql-server-security-best-practices.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/sql-server-security-best-practices.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @dplessMSFT
* Microsoft Alias: **dpless**

**Comment by WilliamAntonRohm** [comment]
@LeszekKalibrate -- Leszek, thank you for your feedback.  Please see related issue #8473.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
