### ISSUE TITLE
Refine the security best practices

### ISSUE THREAD

**Issue by Hermholtz** [MicrosoftDocs/sql-docs#8473]
In the [SQL injection risks](https://learn.microsoft.com/en-us/sql/relational-databases/security/sql-server-security-best-practices#sql-injection-risks) section you recommend to "Disallow the following input characters ... `'` Character data string delimiter"

This character is crucial to entering most of Irish surnames, such as O'Brian, or O'Reilly (e.g. from the famous O'Reilly Media publishing tech books you should be aware of). Nobody will listen to unrealistic requirement.

Instead of disallowing certain characters, a **concrete** server-side **quoting** and validating mechanisms should be recommended. It should be noted that SQL Server uses duplication for the apostrophe character to make it a safe(r) value. Validation would be easier if you finally implemented a replacement for broken `ISNUMERIC` under a different name, and/or regular expressions in SQL Server, because now there's no easy way of validating numbers, as `LIKE` is incapable of expressing "repeat the previous [0-9] range one or more times".

Also, from my experience, almost no developer is aware of the `QUOTENAME` function. Or how to create a safe parameterized `EXEC sp_executesql` calls.

The section notes that "The injection process works by terminating a text string and appending a new command. "
It's so vague, you don't give a concrete information that it's the exact process of constructing query string by concatenating it from parts, including user-supplied values, that creates this risk. You should blatantly point that out, maybe even add annotated example of code that constitutes this malpractice.

Also, you should clearly recommend constructing queries with the use of parameters, along with the information that it's available in all popular programming languages, and at best with a link to concrete example on how to do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 971e2142-ecc0-357f-2c9f-2f9697a79d3f
* Version Independent ID: 971e2142-ecc0-357f-2c9f-2f9697a79d3f
* Content: [SQL Server security best practices - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/sql-server-security-best-practices?view=sql-server-ver16#common-sql-threats)
* Content Source: [docs/relational-databases/security/sql-server-security-best-practices.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/sql-server-security-best-practices.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @dplessMSFT
* Microsoft Alias: **dpless**

**Comment by WilliamAntonRohm** [comment]
@Hermholtz -- thank you for your thorough feedback.

@dplessMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
Reviewing
