### ISSUE TITLE
Instant File Initialization not showing correct value

### ISSUE THREAD

**Issue by polygonuk0036** [MicrosoftDocs/sql-docs#8477]
While installing SQL Server 2019 Standard, I ticked 'Grant Perform Volume Maintenance Task Privilege...'. This is confirmed as enabled both in the log at startup and the flag in sys.dm_server_services, but still shows as 'No' in SQL Server Configuration Manager service properties:

![image](https://user-images.githubusercontent.com/48650765/211617258-dfc8250d-206d-42d4-8e01-fa5c325b3fe3.png)

Current version is CU18.

Kind regards
Paul Egan
DBA

**Comment by WilliamAntonRohm** [comment]
@polygonuk0036 -- Paul, thank you for your feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
