### ISSUE TITLE
dm_operation_status states are incorrect for state 4 and are missing for state 5

### ISSUE THREAD

**Issue by mitwong-microsoft** [MicrosoftDocs/sql-docs#8479]
For [sys-dm-operation-status-azure-sql-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-operation-status-azure-sql-database.md), the documentation shows that state 4 is "Cancelled" when in testing we have seen state 4 as "CancelInProgress" and state 5 as "Cancelled."

**Comment by WilliamAntonRohm** [comment]
@mitwong-microsoft -- thank you for catching this.  I am updating the article.
