### ISSUE TITLE
Wrong article for installing Python on SQL 2022.

### ISSUE THREAD

**Issue by sommarskog** [MicrosoftDocs/sql-docs#8480]
If you go to https://learn.microsoft.com/en-us/sql/machine-learning/install/custom-runtime-python?view=sql-server-ver16&pivots=platform-windows, you quickly see that this topic is for SQL 2019.

Since SQL 2022 no longer ships with Python, this article is in the wrong place. I know that there is an article for installing Python on SQL 2022, because I successfully followed the instructions during the CTP of SQL 2022.

As I am about to sign off for the day, I don't have the time to research if that article is elsewhere. But this article I've linked to should not be under SQL 2022.

**Comment by WilliamAntonRohm** [comment]
@sommarskog -- thank you for bringing this to our attention.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks for the note @sommarskog. https://learn.microsoft.com/en-us/sql/machine-learning/install/sql-machine-learning-services-windows-install-sql-2022?view=sql-server-ver16 is the correct article for SQL 2022. You're right, these <2022 articles should be hidden from the SQL 2022 TOC. Will put this in queue.
