### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by devcon5devcon5** [MicrosoftDocs/sql-docs#8482]
Hi
Where is the sample database used in the article?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 751e374d-cd64-1de5-c1d2-5c426c9534c9
* Version Independent ID: 2c62a70f-cd2e-bf40-5974-dde1b5a10efe
* Content: [Querying Data in a System-Versioned Temporal Table - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/querying-data-in-a-system-versioned-temporal-table?view=sql-server-ver16)
* Content Source: [docs/relational-databases/tables/querying-data-in-a-system-versioned-temporal-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/querying-data-in-a-system-versioned-temporal-table.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
The sample database is created and modified in the earlier [Create](https://learn.microsoft.com/en-us/sql/relational-databases/tables/creating-a-system-versioned-temporal-table) and [Modify](https://learn.microsoft.com/en-us/sql/relational-databases/tables/modifying-data-in-a-system-versioned-temporal-table) articles in this section.

**Comment by rwestMSFT** [comment]
#please-close
