### ISSUE TITLE
Improve phrasing of ODBC Driver installation instructions

### ISSUE THREAD

**Issue by Punchyou** [MicrosoftDocs/sql-docs#8485]
Change the phrasing of the following line to avoid misleading users:

_The Microsoft ODBC Driver 18 for SQL Server will install side by side with Microsoft ODBC Driver 17 for SQL Server._

To something that explains that those versions will not be installed together with the version 18 installation or version 18 will not override version 17.

Maybe something like: _The Microsoft ODBC Driver 18 for SQL Server **can be installed** side by side with Microsoft ODBC Driver 17 for SQL Server._

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a36a1d7f-a410-b597-0eb7-98212934fb0e
* Version Independent ID: e706f2bd-e051-fcff-7c3d-2ef3d9f80e87
* Content: [Download ODBC Driver for SQL Server - ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16)
* Content Source: [docs/connect/odbc/download-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/download-odbc-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@Punchyou -- Maria, thank you for your feedback and suggestion.  I am updating the article.
