### ISSUE TITLE
Coding style of sample CREATE TABLE statement

### ISSUE THREAD

**Issue by DanielCarmingham** [MicrosoftDocs/sql-docs#8488]
The CREATE TABLE example deviates from the style of most other SQL samples in the documentation where the commas are on the right.  For consistency's sake, sample SQL should probably follow the same coding style throughout the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0554218-0eab-3107-526d-4db740530128
* Version Independent ID: 3f5da473-f58d-791e-008b-0cf865693e37
* Content: [Create Tables (Database Engine) - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/create-tables-database-engine?source=recommendations&view=sql-server-ver16)
* Content Source: [docs/relational-databases/tables/create-tables-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/create-tables-database-engine.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@DanielCarmingham -- Daniel, thank you for your keen eye.  I am updating this article.

**Comment by rwestMSFT** [comment]
Further to note: we have over 15,000 articles in this repository managed by a team of 8. It is not practical to make the formatting consistent across all articles. However, we are trying.

**Comment by DanielCarmingham** [comment]
@rwestMSFT Apologies, I didn't realize I could PR the fix myself.  Hope this helps.  Please let me know if I can be of any further assistance.  Thanks!

**Comment by DanielCarmingham** [comment]
> @DanielCarmingham -- Daniel, thank you for your keen eye. I am updating this article.

@WilliamAntonRohm Just saw this...hope you hadn't gotten to it yet.  I just put in a PR with proposed update.  Thank you.

**Comment by WilliamAntonRohm** [comment]
@DanielCarmingham -- Daniel, thank you for beating me to this PR -- much appreciated!

**Comment by rwestMSFT** [comment]
Closing this because of the PR.

#please-close
