### ISSUE TITLE
'\n' is implementation dependent, ODBC driver may not resolve.

### ISSUE THREAD

**Issue by swellhunter** [MicrosoftDocs/sql-docs#8492]
[Enter feedback here]

When installed on Linux and using pyodbc to perform BULK INSERT, "\n" is expected as "0x0A" and a truncation error occurs if the column is the same size as the capacity of  a Varchar(n) column.

UN/RSD|UNKNOWN ROADSIDE MAIL DELIVERY|UNKNOWN ROADSIDE MAIL DELIVERY

inserted into 

create table XYZ.dbo.GNAF_ADDRESS_TYPE_AUT (
  code varchar(8) not null,
  name varchar(50) not null,
  description varchar(30)
);

results in 

'[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Bulk load data conversion error (truncation) for row 36, column 3 (description). (4863) (SQLExecDirectW)'

so the value of '\n' is local to the OS. It may not be correct to assume CRLF.

(Can use dos2unix to convert text files - just an issue with the '\n' assumption). 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5a5757e-e1f9-5064-8e10-5dbab37d2055
* Version Independent ID: 9ff5c29d-79ec-1ee1-1c9d-bbcb1bfe5ef9
* Content: [Specify Field and Row Terminators (SQL Server) - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/import-export/specify-field-and-row-terminators-sql-server?view=sql-server-ver16#specifying-n-as-a-row-terminator-for-bulk-import)
* Content Source: [docs/relational-databases/import-export/specify-field-and-row-terminators-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/specify-field-and-row-terminators-sql-server.md)
* Service: **sql**
* Sub-service: **data-movement**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@swellhunter -- Matthew, thank you for your thorough feedback.

@rwestMSFT -- Randolph, please look into this issue.

**Comment by rwestMSFT** [comment]
@swellhunter This article hasn't been updated for a while, so I'll refresh it and look into clarifying the information around `\n`. Thanks for your feedback.

**Comment by rwestMSFT** [comment]
@swellhunter We are tracking this item internally (AB#70883), so this issue is being closed. Thanks again for your feedback. When we have an update to share, we will let you know here. In the meanwhile, please feel free to leave additional feedback.
