### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by GabiRepare** [MicrosoftDocs/sql-docs#8493]
> "The data will be slower for query performance, which is acceptable if the partition is **queries** infrequently."

Should read

> "The data will be slower for query performance, which is acceptable if the partition is **queried** infrequently."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b8faf5d-ad57-f652-0970-2cdcdda2929c
* Version Independent ID: af4c93c4-9959-fe9e-984d-876eddf06ff5
* Content: [Columnstore indexes - Design guidance - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-design-guidance?view=sql-server-ver16)
* Content Source: [docs/relational-databases/indexes/columnstore-indexes-design-guidance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/columnstore-indexes-design-guidance.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@GabiRepare -- Gabriel, thank you for catching this.  I am updating the article.
