### ISSUE TITLE
The first two result set / cursor types are duplicated

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/sql-docs#8498]
In the Remarks section (https://learn.microsoft.com/en-us/sql/connect/jdbc/understanding-cursor-types?view=sql-server-ver16#remarks), the first two cursor types are duplicated ... aren't they?

Also, there is an "Integer value" specified for some cursor types, not for all. Is it the constant value? Hard to understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 189dfd79-d0ab-791c-a66a-392996f74bd1
* Version Independent ID: 9d2a1e6e-f01f-5443-9335-1d04fe6ce3f0
* Content: [Understanding cursor types - JDBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/jdbc/understanding-cursor-types?view=sql-server-ver16)
* Content Source: [docs/connect/jdbc/understanding-cursor-types.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/understanding-cursor-types.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@ciufudean -- thank you for your feedback.  I am updating this article.
