### ISSUE TITLE
What about Windows 11 ARM

### ISSUE THREAD

**Issue by PascalUK** [MicrosoftDocs/sql-docs#8502]
Hi, in the "Operating system support" table Windows 11 ARM is not mentionned, and SQL Server 2022 doesn't seem to work on this OS. Pleqse lety us know... 
Regards,
Pascal 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5dbbe35-6dd7-6ca7-3966-ee9416304d99
* Version Independent ID: c5dbbe35-6dd7-6ca7-3966-ee9416304d99
* Content: [SQL Server 2019: Hardware & software requirements - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-2019?view=sql-server-ver15#operating-system-support)
* Content Source: [docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-2019.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-2019.md)
* Service: **sql**
* Sub-service: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rwestMSFT** [comment]
SQL Server is not supported on any ARM platforms. Only Azure SQL Edge can be installed as a container on ARM-based platforms running Linux. I hope that helps.

**Comment by rwestMSFT** [comment]
#please-close

**Comment by PascalUK** [comment]
Thank you for your quick answer, but the purpose of my query was to ask you to update the page, so by looking at it people will know if SQL Server is supported on ARM platforms, as I assume it will one day...

**Comment by rwestMSFT** [comment]
Unfortunately, Microsoft does not comment on future plans. If it should happen that ARM is a supported platform for SQL Server, the documentation will reflect that.

A list of unsupported platforms for SQL Server would be out of date almost immediately, and is not practical for our small team to maintain.

Thank you for your understanding.
