### ISSUE TITLE
The DMK for Contained Availability Groups and TDE

### ISSUE THREAD

**Issue by Dottn** [MicrosoftDocs/sql-docs#8505]
In the document, you have the following paragraph:

> To transfer the DMK from the master database of the instance, to the contained master database, see [Move a TDE Protected Database to Another SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/move-a-tde-protected-database-to-another-sql-server?view=sql-server-ver16), primarily focusing on the portions where the DMK is transferred from the old server to the new one.

From what I can gather, _Move a TDE Protected Database to Another SQL Server_ does not transfer the DMK.
What is transferred is the _certificate_, which is protected by the DMK.

Which gives that [master] and [_mycontainedag_\_master] can both have unique DMKs, as long as the certificate is loaded into, at minimum, [_mycontainedag_\_master].

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 269d8ec6-8675-a302-0a8a-e03222d04fa5
* Version Independent ID: 269d8ec6-8675-a302-0a8a-e03222d04fa5
* Content: [What is a contained availability group? - SQL Server Always On](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/contained-availability-groups-overview?view=sql-server-ver16)
* Content Source: [docs/database-engine/availability-groups/windows/contained-availability-groups-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/contained-availability-groups-overview.md)
* Service: **sql**
* Sub-service: **high-availability**
* GitHub Login: @kfarlee
* Microsoft Alias: **kfarlee**

**Comment by WilliamAntonRohm** [comment]
@Dottn -- thank you for your feedback and conclusions.

@kfarlee -- please look into this issue.

**Comment by rwestMSFT** [comment]
@Dottn The article was recently refreshed. Can you please let us know if it describes the issue better?

**Comment by rwestMSFT** [comment]
Since we haven't heard from you for some time, I am closing this issue. Please feel free to comment below if you would like to continue discussing this issue.
