### ISSUE TITLE
Choose install location

### ISSUE THREAD

**Issue by tiago-aguiar-moreira** [MicrosoftDocs/sql-docs#8508]
In older versions it was possible to choose the installation location. Would it be possible to have that option again?

![image](https://user-images.githubusercontent.com/26027121/213474146-544f60fd-ca8d-4753-9413-24e042b33c1d.png)

**Comment by WilliamAntonRohm** [comment]
@tiago-aguiar-moreira -- Tiago, thank you for your suggestion.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
