### ISSUE TITLE
My happiness using Microsoft SQL

### ISSUE THREAD

**Issue by samsorrahman** [MicrosoftDocs/sql-docs#8510]
[Enter feedback here]

it is a great pleasure for my that I am using Microsoft SQL Server to boost up my Data base Skill
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9261422-8fd0-f534-8503-b3f144853958
* Version Independent ID: 0c05cc4f-8260-a264-e724-2f3801f82862
* Content: [Tutorials for SQL Server - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/tutorials-for-sql-server-2016?view=sql-server-ver16)
* Content Source: [docs/sql-server/tutorials-for-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/tutorials-for-sql-server-2016.md)
* Service: **sql**
* Sub-service: ****
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@samsorrahman -- Samsor, thank you for sharing such positive feedback!  Best wishes in your pursuit of learning and advancement!

cc @MikeRayMSFT & @rothja

**Comment by rothja** [comment]
Completely agree! Thank you @samsorrahman for your feedback. I'm the manager of the Database Docs team. Let me know if you have any feedback on how we can improve.
