### ISSUE TITLE
Clarification on SQL Ledger storage

### ISSUE THREAD

**Issue by DougBernhardtData** [MicrosoftDocs/sql-docs#8512]
Please clarify if SQL Ledger is supported on any WORM storage or just Azure and if so, how the database needs to be created. Do only data files reside on WORM storage and logs on standard storage?  

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2c95399-0656-08b2-6daf-bea16906ff5b
* Version Independent ID: c2c95399-0656-08b2-6daf-bea16906ff5b
* Content: [Configure a ledger database - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/ledger/ledger-how-to-configure-ledger-database?view=sql-server-ver16&preserve-view=true&tabs=Portal)
* Content Source: [docs/relational-databases/security/ledger/ledger-how-to-configure-ledger-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/ledger/ledger-how-to-configure-ledger-database.md)
* Service: **sql-database**
* Sub-service: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @DougBernhardtData - This is discussed here: https://learn.microsoft.com/en-us/sql/relational-databases/security/ledger/ledger-overview?view=sql-server-ver16#how-it-works

**Comment by DougBernhardtData** [comment]
https://learn.microsoft.com/en-us/sql/relational-databases/security/ledger/ledger-overview?view=sql-server-ver16#how-it-works is a high level explanation.  There is no detailed explanation on exactly how to do it. The following excerpt which is the only mention of on-premises WORM simply contains a link to a wikipedia article " on-premises [Write Once Read Many (WORM) storage devices](https://en.wikipedia.org/wiki/Write_once_read_many)"

**Comment by VanMSFT** [comment]
Thanks for the feedback, @DougBernhardtData.

@Pietervanhove - Pieter, do you mind reviewing this and see if we can add some clarity into our docs, or comment on the feedback.

#assign:Pietervanhove

**Comment by Pietervanhove** [comment]
Hi @DougBernhardtData

The WORM device can be used to store the database digest files.  In Azure SQL DB you can choose between Azure Storage or Azure Confidential Ledger for automatic digest storage. In SQL Server, we currently only support Azure Storage for automatic digest storage. If you want to use a local WORM device to store the database digests, you will have to generate the digests manually. I wrote a blog post about it a few months ago. See [https://techcommunity.microsoft.com/t5/sql-server-blog/ledger-automatic-digest-upload-for-sql-server-without-azure/ba-p/3630992](url)

A database that contains a ledger table should be created on normal storage.

Regards
Pieter

**Comment by MashaMSFT** [comment]
Hi @DougBernhardtData , thanks for contacting Microsoft! It seems your question was addressed so I'm going to close out this Git Issue but please feel free to comment should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
