### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by EGOproject** [MicrosoftDocs/sql-docs#8515]
[Enter feedback here]
helpful
[EGO WPF ~ EGO SOFT EULA.txt](https://github.com/MicrosoftDocs/sql-docs/files/10470749/EGO.WPF.EGO.SOFT.EULA.txt)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9261422-8fd0-f534-8503-b3f144853958
* Version Independent ID: 0c05cc4f-8260-a264-e724-2f3801f82862
* Content: [Tutorials for SQL Server - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/tutorials-for-sql-server-2016?view=sql-server-ver16)
* Content Source: [docs/sql-server/tutorials-for-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/tutorials-for-sql-server-2016.md)
* Service: **sql**
* Sub-service: ****
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@EGOproject -- Enock, thank you for your feedback.  Please clarify your intended task or purpose.
