### ISSUE TITLE
Potential bug with DATEDIFF(hour...) function 

### ISSUE THREAD

**Issue by SameerSawla** [MicrosoftDocs/sql-docs#8531]
DATEDIFF hour shows a value of 3 & 4 for similar difference of 191 minutes. 
Attaching the relevant snapshot 
![image](https://user-images.githubusercontent.com/7716847/214762713-b8a6aef1-3a9e-4f77-8357-3af079fed3cf.png)

Here's the query 

```
select *,
datediff(minute, jobstarttime, jobendtime) as duration_minute,
datediff(minute, jobstarttime, jobendtime)/60 as duration_minute_by_60,
datediff(hour, jobstarttime, jobendtime) as duration_hour
from sam_temp

```

Please find the CreateTable and Insert query below 

```
CREATE TABLE [sdfconfig].[sam_temp](
	[id] [bigint] NOT NULL,
	[jobStartTime] [datetime2](0) NULL,
	[jobEndTime] [datetime2](0) NULL,
 CONSTRAINT [PK_sam_temp] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```

```
insert into sam_temp
values 
(1,'2022-10-15 01:14:52','2022-10-15 04:25:32'),
(2,'2022-10-08 01:08:14','2022-10-08 04:22:55'),
(3,'2022-10-07 09:50:39','2022-10-07 13:01:32'),
(4,'2022-10-01 01:10:15','2022-10-01 04:24:14')
```

**Comment by WilliamAntonRohm** [comment]
@SameerSawla -- Sameer, thank you for uncovering this apparent discrepancy.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
