### ISSUE TITLE
Edge constraints are not available in SQL Server 2017

### ISSUE THREAD

**Issue by siggemannen** [MicrosoftDocs/sql-docs#8544]
Hello, it seems that this page incorrectly states that edge constraints can be created in SQL Server 2017: 
https://learn.microsoft.com/en-us/sql/relational-databases/tables/graph-edge-constraints?view=sql-server-2017
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/graph-edge-constraints.md

But i think it's only available starting from SQL Server 2019. Could you update the documentation?

**Comment by WilliamAntonRohm** [comment]
@siggemannen -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue.

**Comment by ZedZipDev** [comment]
Yes, it is and I have spent a time with it using SQL2017.

**Comment by siggemannen** [comment]
@ZedZipDev, I didn't mean edge tables, but edge constraints specifically, are you sure?
