### ISSUE TITLE
Persian Language Support in SSMS

### ISSUE THREAD

**Issue by alikiaee** [MicrosoftDocs/sql-docs#8545]
Hi, Why don't you add Persian language support for SSMS?

**Comment by WilliamAntonRohm** [comment]
@alikiaee -- Alireza, thank you for your question from Tehran.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by alikiaee** [comment]
Ok, Thanks.
