### ISSUE TITLE
placement 'Create assessment' in left menu

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/sql-docs#8547]
Hi Docs team,
 
Article [Perform a SQL Server migration assessment with Data Migration Assistant](https://learn.microsoft.com/en-us/sql/dma/dma-assesssqlonprem?view=sql-server-ver16) is in the left menu placed under **Assess Azure SQL DB Readiness** while the **Create assessment** article is more general in how to create and perform an assessment for any of the supported targets. 
Would it be better to place this article in between **What's new** and **Assess SQL Server Integration Services (SSIS)**? 
 
[Use DMA GUI](https://learn.microsoft.com/en-us/sql/dma/dma-assess-sql-data-estate-to-sqldb?view=sql-server-ver16) is Azure SQL Database specific. [Use DMA command-line](https://learn.microsoft.com/en-us/sql/dma/dma-assess-sql-data-estate-to-sqldb-commandline?view=sql-server-ver16) targets anything Azure SQL.
Is it best to rename the group from **Assess Azure SQL DB Readiness** to **Assess Azure SQL Readiness**?
 
I don't think I can contribute to anything regarding the menu.

![image](https://user-images.githubusercontent.com/40343254/215555007-2c7ca396-5b9c-47b4-acfc-5af7174a6e51.png)

**Comment by WilliamAntonRohm** [comment]
@ingebeumer -- Inge, thank you again for contributing these suggestions.

@rajeshsetlem -- please consider this for future updates.

**Comment by rwestMSFT** [comment]
@ingebeumer We can discuss this internally and I can demonstrate how to make changes to the table of contents.

**Comment by rwestMSFT** [comment]
@ingebeumer Please confirm whether this has been resolved - I think it has.
