### ISSUE TITLE
Change stripe size limit units from MB to GB

### ISSUE THREAD

**Issue by nanoDBA** [MicrosoftDocs/sql-docs#8550]
100,000 MB references can be changed to 100 GB to arguably increase readability without doing a quick conversion.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9b99dc-4e63-75a7-a6ed-ea635159c01e
* Version Independent ID: 6e9b99dc-4e63-75a7-a6ed-ea635159c01e
* Content: [Back up to URL best practices & troubleshooting for S3-compatible object storage - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url-s3-compatible-object-storage-best-practices-and-troubleshooting?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/sql-server-backup-to-url-s3-compatible-object-storage-best-practices-and-troubleshooting.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/sql-server-backup-to-url-s3-compatible-object-storage-best-practices-and-troubleshooting.md)
* Service: **sql**
* Sub-service: **backup-restore**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@nanoDBA -- thank you for your suggestion.  I'll update the article.
