### ISSUE TITLE
IGNORE NULLS | RESPECT NULLS clauses not documented for LAG/LEAD functions

### ISSUE THREAD

**Issue by clement911** [MicrosoftDocs/sql-docs#8552]
The clause for `IGNORE NULLS | RESPECT NULLS` was recently added to FIRST_VALUE and LAST_VALUE, however it is still not documented on LAG/LEAD, even though it is supported (I believe for both SQL SERVER 2022 and AZURE SQL)

Documented:
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/first-value-transact-sql.md
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/last-value-transact-sql.md

Not documented:
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/lead-transact-sql.md
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/lag-transact-sql.md

**Comment by WilliamAntonRohm** [comment]
@clement911 -- Clement, thank you for your well-researched feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by clement911** [comment]
@markingmyname  to prove that LAG() OVER() is supported in SQL SERVER 2022 and SQL AZURE, you can simply run the following query

```sql
SELECT LAG(value) IGNORE NULLS OVER(ORDER BY id)
FROM (VALUES (1, 'Yes'), (2, NULL), (3, 'No')) t(id, value)
```

**Comment by clement911** [comment]
It would great to add this.
This is a great new feature in sql server 2022. Unfortunately, people won't use it unless it's documented...

**Comment by clement911** [comment]
any updates?

**Comment by clement911** [comment]
@markingmyname

**Comment by WilliamDAssafMSFT** [comment]
@clement911 This use of IGNORE NULLS | RESPECT NULLS is not documented for LAG/LEAD functions for a reason, for now. Currently, this is not supported. This is on our radar.  Thanks for bringing this up and taking the time to create this issue though, this feedback is valuable.

**Comment by clement911** [comment]
@WilliamDAssafMSFT What is the reason?

I'm not sure what you mean exactly by 'not supported'.
We have been using IGNORE NULLS with LAG/LEAD in both Sql server 2022 and Sql Azure for several months now.

In addition, it is mentioned in this post: https://sqlperformance.com/2022/05/t-sql-queries/windowing-improvements-sql-server-2022#:~:text=As%20mentioned%2C%20the%20NULL%20treatment%20clause%20is%20available%20to%20all%20offset%20window%20functions%20(FIRST_VALUE%2C%20LAST_VALUE%2C%20LAG%2C%20and%20LEAD).%20Here%E2%80%99s%20an%20example%20using%20LAG%20to%20return%20the%20previous%20known%20value%3A

![image](https://user-images.githubusercontent.com/3426504/225778666-a0083bb5-383e-4c9f-8e4a-28cb8dcbd553.png)

**Comment by WilliamDAssafMSFT** [comment]
I'm sorry I can't offer you any more information at this time, but it is on our radar. Will update.

**Comment by WilliamDAssafMSFT** [comment]
@Clement911 Yes, there was an issue with IGNORE NULLS in LAG/LEAD and this has been resolved in CU4 for SQL Server 2022. https://learn.microsoft.com/troubleshoot/sql/releases/sqlserver-2022/cumulativeupdate4#2278800

**Comment by clement911** [comment]
I see. I guess that the documentation can be updated now it is fixed?

However, how do we track the status of this fixes in Sql Azure? Does Sql Azure have this cumulative fixes already applied?

**Comment by WilliamDAssafMSFT** [comment]
You are correct that a doc update is in flight! 
Azure SQL Database always running on the latest stable version of the SQL Server database engine and patched OS, yes. You can verify the version of your logical server via the same methods as on a SQL Server, [for example](https://learn.microsoft.com/en-us/troubleshoot/sql/releases/find-my-sql-version#:~:text=select%20serverproperty('productversion')%2C%20serverproperty%20('productlevel')%2C%20serverproperty%20('edition')).

**Comment by clement911** [comment]
This is what I'm seeing when querying sql azure:

![image](https://github.com/MicrosoftDocs/sql-docs/assets/3426504/f7be26aa-b38a-47c6-bd11-5933d6c77bfa)

If sql azure is using a Mar 30 version, are you positive that it contains the latest cumulative update which was released on May 11th?

That is completely different from we see in the docs for the [cumulative update 4](https://learn.microsoft.com/en-au/troubleshoot/sql/releases/sqlserver-2022/cumulativeupdate4#2278800):

![image](https://github.com/MicrosoftDocs/sql-docs/assets/3426504/3201f4ff-241f-47bc-b975-4398865d716c)

I'm even more confused.
