### ISSUE TITLE
The 11.2.0 download link on this page is incorrectly 10.2.0.0

### ISSUE THREAD

**Issue by RikaEndo0** [MicrosoftDocs/sql-docs#8553]
I want to get sqljdbc_11.2.0.0_jpn.zip, but the file I get from the download link is sqljdbc_10.2.0.0_jpn.zip. The tar file seems to be wrong as well.

https://learn.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver16#112-releases

**Comment by WilliamAntonRohm** [comment]
@RikaEndo0 -- Rika, thank you for catching this.  I am updating the article.

**Comment by RikaEndo0** [comment]
@WilliamAntonRohm   I made sure the link was fixed. Thank you for your prompt response !!
