### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by gdipersio** [MicrosoftDocs/sql-docs#8555]
SOS_SCHEDULER_YEILD should be SOS_SCHEDULER_YIELD.  Affects search engines.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: afbb87df-5f49-cbe1-b2ff-53102d1d07df
* Version Independent ID: 6bc18849-20fb-bbc8-ca47-9dde06bfb393
* Content: [Whitepaper: Diagnose & resolve spinlock contention - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/diagnose-resolve-spinlock-contention?view=sql-server-ver16)
* Content Source: [docs/relational-databases/diagnose-resolve-spinlock-contention.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/diagnose-resolve-spinlock-contention.md)
* Service: **sql**
* Sub-service: **performance**
* GitHub Login: @bluefooted
* Microsoft Alias: **pamela**

**Comment by WilliamAntonRohm** [comment]
@gdipersio -- Glen, thank you for catching this.  I am updating the article.
