### ISSUE TITLE
A member of the role db_owner can execute sp_updatestats for Azure SQL Database.

### ISSUE THREAD

**Issue by LifeRyuto** [MicrosoftDocs/sql-docs#8557]
The document below says,
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-updatestats-transact-sql.md#permissions
> To run sp_updatestats, the user must be the owner of the database (the dbo, not just member of the role db_owner) or to be member of the sysadmin fixed server role.

However, a member of the role db_owner could execute sp_updatestats for Azure SQL Database. Could you please fix the document for Azure SQL Database?

```
exec sp_helptext sp_updatestats;

 -- Check the user sysadmin, dbo or member of db_owner when the engineedition is 5 which is the edition for SQL Azure  
 if not is_srvrolemember('sysadmin') = 1 and suser_sid() <> @dbsid and not (is_rolemember('db_owner') = 1 and SERVERPROPERTY('engineedition') = 5)  
...
```

**Comment by WilliamAntonRohm** [comment]
@LifeRyuto -- Ryuto, thank you for your detailed feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by N-Kannan** [comment]
@WilliamAntonRohm can you assisn me this I can work on it. I have good experience in sql.

**Comment by sshen-pcr** [comment]
so it has been confirmed that a member of db_owner role can indeed execute this procedure, right?
How do I get the ddl of this procedure?

**Comment by WilliamAntonRohm** [comment]
@N-Kannan -- Kannan, thank you again for your offer.  Please see this comment:  https://github.com/MicrosoftDocs/sql-docs/issues/8830#issuecomment-1513620328.

**Comment by N-Kannan** [comment]
Thanks @WilliamAntonRohm I will create a pull request once I update all

**Comment by WilliamDAssafMSFT** [comment]
> Thanks @WilliamAntonRohm I will create a pull request once I update all

@N-Kannan please issue one pull request per fix.

**Comment by N-Kannan** [comment]
@WilliamDAssafMSFT i am working it due to my work schedule little delay I will in 4 days

**Comment by N-Kannan** [comment]
@WilliamAntonRohm can you check my pr and close the issue

**Comment by WilliamAntonRohm** [comment]
@N-Kannan -- Kannan, thank you for your contributions.

@markingmyname, @WilliamDAssafMSFT -- Mark or William, please review these changes.

**Comment by WilliamDAssafMSFT** [comment]
Closing as this Issue has been addressed in another PR.
