### ISSUE TITLE
misleading info about maintenance plan script

### ISSUE THREAD

**Issue by gewoonptr** [MicrosoftDocs/sql-docs#8564]
https://learn.microsoft.com/en-us/sql/relational-databases/maintenance-plans/create-a-maintenance-plan?view=sql-server-ver16#to-create-a-maintenance-plan

This title is misleading. The T-SQL is not creating a maintenance plan. It's creating an agent-job... 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15f7a03d-8031-2a8a-11f4-a261db7843e9
* Version Independent ID: 7067b556-f353-ea26-8c4a-64b616c24cf3
* Content: [Create a Maintenance Plan - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/maintenance-plans/create-a-maintenance-plan?view=sql-server-ver16)
* Content Source: [docs/relational-databases/maintenance-plans/create-a-maintenance-plan.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/maintenance-plans/create-a-maintenance-plan.md)
* Service: **sql**
* Sub-service: **supportability**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@gewoonptr -- thank you for your feedback.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@gewoonptr -- Zevenvoorelf, I find that this is outside my expertise.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by rwestMSFT** [comment]
I'm on it while Mike is away.
