### ISSUE TITLE
Managed Instance preview status

### ISSUE THREAD

**Issue by mshelt** [MicrosoftDocs/sql-docs#8565]
This page states that Managed Instance is in Preview. This page states it is GA. 

https://techcommunity.microsoft.com/t5/azure-sql-blog/data-virtualization-now-generally-available-in-azure-sql-managed/ba-p/3624292#:~:text=We%20are%20excited%20to%20announce%20the%20general%20availability,new%20supported%20option%20for%20authenticating%20to%20storage%20accounts. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7ebefef-f8c5-e429-269e-1ef7a96264fd
* Version Independent ID: a8009495-9bb9-87f4-85af-0ac0074749e7
* Content: [Introducing data virtualization with PolyBase - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/polybase/polybase-guide?view=sql-server-ver16)
* Content Source: [docs/relational-databases/polybase/polybase-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-guide.md)
* Service: **sql**
* Sub-service: **polybase**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@mshelt -- Mike, thank you for catching this.  I am updating the article.
