### ISSUE TITLE
Add Mac OS support

### ISSUE THREAD

**Issue by JJVanhoof** [MicrosoftDocs/sql-docs#8566]
Please add a section for Mac OS dev, by copying the linux section and referring to the ODBC driver for mac:
https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver16

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95454cf7-3691-e4eb-d8c6-b7986fcd490b
* Version Independent ID: 84a42231-fc84-e831-a9a8-18cb86f3cfb9
* Content: [Step 1: Configure pyodbc Python environment - Python driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/python/pyodbc/step-1-configure-development-environment-for-pyodbc-python-development?view=sql-server-ver16)
* Content Source: [docs/connect/python/pyodbc/step-1-configure-development-environment-for-pyodbc-python-development.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/python/pyodbc/step-1-configure-development-environment-for-pyodbc-python-development.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@JJVanhoof -- thank you for your suggestion.

@David-Engel -- please look into this issue.

**Comment by David-Engel** [comment]
A new section for macOS has been added to the page. It should appear on the website within a few hours.

Thanks,
David

#please-close
