### ISSUE TITLE
Column name is not is_encrypted but encrypt_option

### ISSUE THREAD

**Issue by kegoly** [MicrosoftDocs/sql-docs#8567]
The document refer to the following statement.

Execute the following T-SQL command to check the value of is_encrypted column. For encrypted connections the value will be 1.
SELECT * FROM sys.dm_exec_connections

This is not is_encrypted but encrypt_option. Could you please fix it?

sys.dm_exec_connections (Transact-SQL)
https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-connections-transact-sql?view=sql-server-ver16

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d932a41-5533-8809-e9fa-e6f48cd4eec5
* Version Independent ID: 9d932a41-5533-8809-e9fa-e6f48cd4eec5
* Content: [SQL Server and client encryption summary - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-and-client-encryption-summary?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/sql-server-and-client-encryption-summary.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/sql-server-and-client-encryption-summary.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @padmajayaraman
* Microsoft Alias: **v-jayaramanp**

**Comment by WilliamAntonRohm** [comment]
@kegoly -- thank you for your well-researched feedback.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@kegoly -- this has been corrected and is now live.
