### ISSUE TITLE
Fix this issue and remove this page

### ISSUE THREAD

**Issue by IT-CASADO** [MicrosoftDocs/sql-docs#8568]
This issue is very annoying and happens for years now. Why do you not fix this issue and remove this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7fd1b3-32a6-dcbd-738f-40c46e9d55bf
* Version Independent ID: 21d55bbf-4586-1957-6b76-10b0eea64a5d
* Content: [Enable copying from find and replace window - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/troubleshoot/enable-copying-find-replace-window?view=sql-server-ver16)
* Content Source: [docs/ssms/troubleshoot/enable-copying-find-replace-window.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/troubleshoot/enable-copying-find-replace-window.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
The page documents the setting required to enable copying into the find/replace window and these GitHub issues track problems with the documentation.  Your feedback on both documentation and the products is appreciated - SSMS feedback is filed at https://aka.ms/sqlfeedback
#please-close
