### ISSUE TITLE
Incorrect use of GetHostByName($env:computerName) as New-SelfSignedCertificate input

### ISSUE THREAD

**Issue by mloskot** [MicrosoftDocs/sql-docs#8569]
```
"[System.Net.Dns]::GetHostByName($env:computerName)"
```

This does not yield FQDN of host:

```
"[System.Net.Dns]::GetHostByName($env:computerName)"
```

because `GetHostByName` returns a collection of values, so this is the correct way:

```
("{0}" -f [System.Net.Dns]::GetHostByName($env:computerName).HostName)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf384fb2-ea82-4956-5199-bf8d1c305a20
* Version Independent ID: cf384fb2-ea82-4956-5199-bf8d1c305a20
* Content: [Configure SQL Server Database Engine for encryption - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/configure-sql-server-encryption?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/configure-sql-server-encryption.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-sql-server-encryption.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @sevend2
* Microsoft Alias: **v-sidong**

**Comment by WilliamAntonRohm** [comment]
@mloskot - Mateusz, thank you for your correction here.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@sevend2 -- please review this change in [private PR 26999](https://github.com/MicrosoftDocs/sql-docs-pr/pull/26999).
