### ISSUE TITLE
SQL Server ODBC Driver 18 64bit installs in system32

### ISSUE THREAD

**Issue by nojetlag** [MicrosoftDocs/sql-docs#8580]
Hi there I noticed that the the ODBC Driver 18.1.2.1 64bit version installs the msodbcsql18.dll  into c:\Windows\system32. Is this a bug or did I misunderstand something behind the concept how MSFT installs 32bit vs 64bit software on Windows ?

**Comment by WilliamAntonRohm** [comment]
@nojetlag -- thank you for your feedback and question.  If you feel this is a product issue, please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
