### ISSUE TITLE
Option "Check for open transactions before closing T-SQL query windows" not visible

### ISSUE THREAD

**Issue by Ikaer** [MicrosoftDocs/sql-docs#8587]
[Enter feedback here]
Hi, on this version of SSMS
![image](https://user-images.githubusercontent.com/7936075/217855203-6eaf775d-993e-4238-aa64-8895945de67e.png)

I don't have this option "Check for open transactions before closing T-SQL query windows".
![image](https://user-images.githubusercontent.com/7936075/217855146-10a10f30-8949-4a6e-a1f2-4e11ad7f2c4c.png)

I have this dialog to close every time I close a query editor. I would like to remove this check, is there a way to make the checkbox appears or to change this configuration otherwise ?
![image](https://user-images.githubusercontent.com/7936075/217854762-eb64959e-6983-4318-9ff9-1c6ad9256dcc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c114af5b-31b0-b14e-e6c8-fc166e476d79
* Version Independent ID: f5e0e46e-768f-8232-553f-416180c4bb69
* Content: [SSMS Options page - Query Execution - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/menu-help/options-query-execution?view=sql-server-ver16)
* Content Source: [docs/ssms/menu-help/options-query-execution.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/menu-help/options-query-execution.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
Hi @Ikaer - that option is only available in SSMS 19.0, you will need to upgrade to SSMS 19.0 or higher in order for that option.  Thanks.
