### ISSUE TITLE
This page didn't say how to modify password policy

### ISSUE THREAD

**Issue by kind03** [MicrosoftDocs/sql-docs#8593]
This page didn't say how to modify password policy, for example, how to modify the expiration time of the password policy, and how to create a new password policy and apply to certain account.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58afcd81-a8da-a2bc-5ed0-1a28cf242781
* Version Independent ID: 05c003a1-7f84-67b9-d82e-150aff74faed
* Content: [Password Policy - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/password-policy.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/password-policy.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @kind03, password policies like password expiration time/date cannot be modified in SQL Server. To enforce password policies, you do this with ALTER LOGIN or CREATE LOGIN when creating a new login.
