### ISSUE TITLE
sys.sp_cdc_generate_wrapper_function formatting problems

### ISSUE THREAD

**Issue by EitanBlumin** [MicrosoftDocs/sql-docs#8595]
There are a few formatting mistakes in this document:

https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sys-sp-cdc-generate-wrapper-function-transact-sql

MD:
https://github.com/MicrosoftDocs/sql-docs/blob/b7782a6ae8760ba8e16e65f6c6f4393c6a331c15/docs/relational-databases/system-stored-procedures/sys-sp-cdc-generate-wrapper-function-transact-sql.md

The formatting mistakes are:

- The syntax block is improperly wrapped. It seems to be mistakenly split into two blocks.
- The argument headings don't seem to fit the formatting done in most other documents.
- The example code uses a cursor with `#` in its name, and overall uses abnormal syntax and formatting.

**Comment by WilliamAntonRohm** [comment]
@EitanBlumin -- Eitan, thank you for your clear feedback.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@EitanBlumin -- Eitan, I updated the syntax formatting, and the headings are good as-is.

@markingmyname -- Mark, is an octothorpe `#` needed in that example?
