### ISSUE TITLE
 [Error] Error: spawn virtualenv ENOENT 

### ISSUE THREAD

**Issue by JamieL22** [MicrosoftDocs/sql-docs#8598]
If possible, this error could use more informative feedback.   
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: badc8fa0-55a6-8c5e-1dd7-ff03ad335208
* Version Independent ID: 0e214c94-6b42-3bc9-c1e1-5ee58a6844d3
* Content: [Run jobs: Spark & Hive Tools for VS Code - SQL Server Big Data Clusters](https://learn.microsoft.com/en-us/sql/big-data-cluster/spark-hive-tools-vscode?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/spark-hive-tools-vscode.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/spark-hive-tools-vscode.md)
* Service: **sql**
* Sub-service: **big-data-cluster**
* GitHub Login: @HugoMSFT
* Microsoft Alias: **hudequei**

**Comment by WilliamAntonRohm** [comment]
@JamieL22 -- Jamie, thank you for your feedback.  This seems more product-related than documentation-related.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

cc @HugoMSFT for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
