### ISSUE TITLE
Pate lacks a credible example.

### ISSUE THREAD

**Issue by ClarkFrazier** [MicrosoftDocs/sql-docs#8603]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc238707-5878-9a71-04f4-b8fd05f60c12
* Version Independent ID: 881acab6-0949-5f85-66fd-b308e85f7bf0
* Content: [Restore a Database to a New Location (SQL Server) - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/restore-a-database-to-a-new-location-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/restore-a-database-to-a-new-location-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/restore-a-database-to-a-new-location-sql-server.md)
* Service: **sql**
* Sub-service: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @ClarkFrazier , thanks for contacting Microsoft! My apologies, would you mind expanding on your request? What are you hoping to see from the example that isn't there?

Thanks!
Masha from the SQL Docs team

**Comment by rwestMSFT** [comment]
I am closing this issue. Please feel free to leave a comment once you have more information to share.
