### ISSUE TITLE
Correction request

### ISSUE THREAD

**Issue by romil-gupta** [MicrosoftDocs/sql-docs#8604]
At step : Join the database on the secondary of the second availability group

In case of manual seeding when we are configuring a Distributed AG from SQL 2017 to SQL 2019, then we have to restore the db with NO RECOVERY option on both forwarder and its secondary instance.

At present in the article its not mentioned that we have to create the db on both nodes of the forwarder

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab92d64a-bdc3-67a0-60f8-c551b85ead4b
* Version Independent ID: e8ed4dfb-c487-e663-e77f-f205415319e4
* Content: [Configure a distributed availability group - SQL Server Always On](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-distributed-availability-groups?view=sql-server-ver16&tabs=automatic)
* Content Source: [docs/database-engine/availability-groups/windows/configure-distributed-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/configure-distributed-availability-groups.md)
* Service: **sql**
* Sub-service: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@romil-gupta -- thank you for your clear feedback.

@tarynpratt -- please look into this issue.

**Comment by tarynpratt** [comment]
Hi @romil-gupta, thanks so much for your feedback, our apologies for the long delay as we processed a large number of back Issues. I've processed a change and it should be live later this week. I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

thanks again, hope you have a good day, bye 
#reassign:tarynpratt  
#please-close
