### ISSUE TITLE
Incorrect Applies To in cdc.ddl_history

### ISSUE THREAD

**Issue by EitanBlumin** [MicrosoftDocs/sql-docs#8607]
The documentation says that the `cdc.ddl_history` table applies to "SQL Server" only (on-prem, SQL on VM's, etc.).

However, the table `cdc.ddl_history` also exists in Azure SQL Databases (and I think in Azure SQL Managed Instance as well).
This may have been a relatively recent change, and this page got missed somehow while the documentation was updated.

URL:
https://learn.microsoft.com/en-us/sql/relational-databases/system-tables/cdc-ddl-history-transact-sql

MD:
https://github.com/MicrosoftDocs/sql-docs/blob/23ba057c8967a2e1f12102e0c7fc4a444aba5dd3/docs/relational-databases/system-tables/cdc-ddl-history-transact-sql.md?plain=1#L20

**Comment by WilliamAntonRohm** [comment]
@EitanBlumin -- Eitan, thank you again for your well-researched feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Thanks @EitanBlumin! Verified and making the updates now.
