### ISSUE TITLE
Product Suggestion (Not Issue): Auto Correct Syntax and SQL Formatting

### ISSUE THREAD

**Issue by cgers** [MicrosoftDocs/sql-docs#8609]
# SSMS is a great product however I believe that the two following additions would go a long way to making it much better.

1. When typing a query, how often instead of typing the `FROM `keyword, does the user type `FORM`  by mistake. SSMS should have the ability to detect these and automatically change them.
2. Secondly is the formatting of SQL Statements. How many times do users copy their code into a CODE beautifier to make it look neater? A code beautifier/formatting is essential in a tool like SSMS - I should not have to purchase a REDGATE product to do this for me.

I have used SSMS for a decade and know that these improvements will help many users.

**Comment by WilliamAntonRohm** [comment]
@cgers -- Craig, thank you for your thoughtful suggestions.  Please add them here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
