### ISSUE TITLE
SQL Server versions that support PAYG

### ISSUE THREAD

**Issue by MasayukiOzawa** [MicrosoftDocs/sql-docs#8614]
This document describes the following
>  Pay-as-you-go, billed through Azure, is now available for all versions of SQL Server from 2014 to 2022.

However, the following document states that SQL Server 2012 or later is supported.
https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/release-notes?view=sql-server-ver16#azure-extension-for-sql-server-1
>Pay-as-you-go (PAYG) licensing option is now extended to SQL Server 2012 and above

I believe PAYG is supported by SQL Server 2012 or later.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b9f51bd-1ce7-dcbb-6d42-3ec6e51e0e23
* Version Independent ID: 299a7dc8-b9b2-503d-6a24-0da0e2b48dd8
* Content: [Azure Arc-enabled SQL Server - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/overview?view=sql-server-ver16)
* Content Source: [docs/sql-server/azure-arc/overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/azure-arc/overview.md)
* Service: **sql**
* GitHub Login: @anosov1960
* Microsoft Alias: **sashan**

**Comment by WilliamAntonRohm** [comment]
@MasayukiOzawa -- Masayuki, thank you for bringing this to our attention.  I am updating the article.
