### ISSUE TITLE
SSMS: Generate Scripts: Search option to filter objects 

### ISSUE THREAD

**Issue by SuryamaniR** [MicrosoftDocs/sql-docs#8616]
![image](https://user-images.githubusercontent.com/125864881/220052310-822a47b2-d4b5-4a90-8e0f-6fcdfa454eeb.png)

Search option will help to choose objects having common word in their name

**Comment by WilliamAntonRohm** [comment]
@SuryamaniR -- Suryamani, thank you for your suggestion.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
