### ISSUE TITLE
Update SubQuery Gets hangs in Windows Server 2019 and SQL Server 2019

### ISSUE THREAD

**Issue by sanjaymicrobrain** [MicrosoftDocs/sql-docs#8617]
While Executing Following Query machine gets hanged. It works in all version but hangs Windows Server 2019 and SQL Server 2019.

UPDATE FaAccountBalanceMaster SET 
FaAccountBalanceMaster.Month1Total = 
ROUND(FaAccountBalanceMaster.Month1Total + Summary.Amount * 1, 2), 
FaAccountBalanceMaster.CurrentBalance = Round(FaAccountBalanceMaster.CurrentBalance + Summary.Amount * 1, 2), 
FaAccountBalanceMaster.Used = 'True', 
FaAccountBalanceMaster.CurrencyCurrentBalance = Round(FaAccountBalanceMaster.CurrencyCurrentBalance + CASE WHEN FaAccountBalanceMaster.CurrencyCode <> '' THEN Summary.CurrencyAmount * 1 ELSE 0 END, 2) 
FROM 
(
SELECT 
AccountCode, 
AccountBranchCode AS BranchCode, 
ROUND(SUM(Amount), 2) AS Amount, 
ROUND(SUM(CurrencyAmount), 2) AS CurrencyAmount 
FROM FaAccountLedger 
WHERE 
FaAccountLedger.DocumentDate >= ('04/01/2021') AND 
FaAccountLedger.DocumentDate <= ('04/30/2021') AND 
FaAccountLedger.Passed = 'True' 
GROUP BY 
AccountCode, 
AccountBranchCode ) AS Summary INNER JOIN 
FaAccountBalanceMaster ON 
Summary.AccountCode = FaAccountBalanceMaster.AccountCode AND 
Summary.BranchCode = FaAccountBalanceMaster.BranchCode 

Please do needful.

Sanjay Shah

![SQL_SubQuery_Update_Hang_2023_02_20](https://user-images.githubusercontent.com/125877004/220086139-8ac587bd-7db1-46a5-aec2-2ef3fe9ac29d.jpg)

**Comment by WilliamAntonRohm** [comment]
@sanjaymicrobrain -- Sanjay, thank you for your feedback.  Are you following a particular learn.microsoft.com article?

**Comment by sanjaymicrobrain** [comment]
Yes I have also post this query to earn.microsoft.com article.

**Comment by WilliamAntonRohm** [comment]
@sanjaymicrobrain -- thank you for your follow-up.  Which article?
