### ISSUE TITLE
Error in  https://packages.microsoft.com/config/rhel/8/prod.repo

### ISSUE THREAD

**Issue by fmercier** [MicrosoftDocs/sql-docs#8618]
Hello,
the content of the file 
 https://packages.microsoft.com/config/rhel/8/prod.repo

miss the section and the name e.g 

```
[]
name=
baseurl=https://packages.microsoft.com/rhel/9.0/mssql-server-2022/
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b543b57-f397-779d-6fe4-1bc2ecd3bdca
* Version Independent ID: e274a0f3-ec74-e809-f4d3-515782b29a92
* Content: [RHEL: Install SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-red-hat?view=sql-server-ver16)
* Content Source: [docs/linux/quickstart-install-connect-red-hat.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-red-hat.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @fmercier - Can you please elaborate? RHEL 9.0 is not supported for SQL Server 2022 at the moment.

**Comment by fmercier** [comment]
Hello,
I've made a error in my description, sorry.
The wrong file is :
https://packages.microsoft.com/config/rhel/8/mssql-server-2022.repo
and it's current content is :
> 
[]
name=
baseurl=https://packages.microsoft.com/rhel/8/mssql-server-2022/
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc

So it miss the section and the name

**Comment by VanMSFT** [comment]
Hi @fmercier, can you please clarify what you mean by wrong file? What section of the document are you following, and what's wrong? The [Install SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-red-hat?view=sql-server-ver16#install) portion of this doc has the correct file listed, and the [base URL](https://packages.microsoft.com/rhel/8/mssql-server-2022/) points to the rpm installation of SQL Server 2022.

**Comment by fmercier** [comment]
Hello,
The documentation is correct but the content of the file referenced is wrong

**Comment by VanMSFT** [comment]
@fmercier - Thanks for the clarity! This is what I see when I download the file:

```
[packages-microsoft-com-mssql-server-2022]
name=packages-microsoft-com-mssql-server-2022
baseurl=https://packages.microsoft.com/rhel/8/mssql-server-2022/
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
```

**Comment by fmercier** [comment]
Your content is correct; but not mine !

> curl https://packages.microsoft.com/config/rhel/8/mssql-server-2022.repo
[]
name=
baseurl=https://packages.microsoft.com/rhel/8/mssql-server-2022/
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc

Is it a replication problem ? This is how the dns translate at my location

> nslookup packages.microsoft.com
packages.microsoft.com  canonical name = apt-geofence-parent.trafficmanager.net.
apt-geofence-parent.trafficmanager.net  canonical name = csd-apt-weu-d-1.westeurope.cloudapp.azure.com.
Name:   csd-apt-weu-d-1.westeurope.cloudapp.azure.com
Address: 13.80.99.124

**Comment by VanMSFT** [comment]
Thanks for the details, @fmercier! Let me inform the Product Group and see if they can replicate that.

@rwestMSFT @amitkh-msft

**Comment by rwestMSFT** [comment]
I don't think this qualifies as a Docs issue, so I'm closing this issue for now, and we'll track it internally. Thanks again @fmercier
