### ISSUE TITLE
Always Encrypted: There are vital steps missing in the process 

### ISSUE THREAD

**Issue by geluvac** [MicrosoftDocs/sql-docs#8628]
Coming from a tech guy frustrated with MS support center, I took time to pull up an article showing the full experince of using Always Encrypted with keys stored in AKV: https://www.codeproject.com/Articles/5355073/Full-Tutorial-on-using-Always-Encrypted-with-Azure

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 034a5408-3f72-4141-6814-548b71f21b04
* Version Independent ID: 6956f5a2-3608-fb9e-641b-da72384168e2
* Content: [Tutorial: Develop a .NET application using Always Encrypted with secure enclaves - ADO.NET Provider for SQL Server](https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/tutorial-always-encrypted-enclaves-develop-net-apps?view=sql-server-ver16)
* Content Source: [docs/connect/ado-net/sql/tutorial-always-encrypted-enclaves-develop-net-apps.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/ado-net/sql/tutorial-always-encrypted-enclaves-develop-net-apps.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@geluvac -- thank you for your feedback.

@David-Engel -- please look into this issue.

**Comment by Pietervanhove** [comment]
Hi @geluvac 

Thank you for the great article. Would it be possible to open a PR for this so that we can include your valuable contribution in our documentation?

Thanks,
Pieter

**Comment by rwestMSFT** [comment]
I'm closing this for now. We look forward to seeing your PR, @geluvac.
