### ISSUE TITLE
No wildcard option in REPLACE dialogue box in SSMS

### ISSUE THREAD

**Issue by rferreiradba** [MicrosoftDocs/sql-docs#8631]
Here: https://learn.microsoft.com/en-us/sql/ssms/scripting/search-text-with-wildcards?view=sql-server-ver16

It reads: "To search using wildcards
To enable the use of wildcards in the Find what field during Quick Find, Find in Files, Quick Replace, or Replace in Files operations, ### select the Use option under Find Options and then choose Wildcards."

Well, there is no such option to select. The only options are Match case, Match whole word, and Use Regular Expressions.

![1](https://user-images.githubusercontent.com/38080557/220741954-fbf46a52-cdfe-4ea0-bce9-4624e66817d8.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0ee7374-8987-ed14-b4b4-06fa957d35d7
* Version Independent ID: c57a30e5-e3fe-4353-c162-1248575d2d64
* Content: [Search Text with Wildcards - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/scripting/search-text-with-wildcards?view=sql-server-ver16)
* Content Source: [docs/ssms/scripting/search-text-with-wildcards.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/search-text-with-wildcards.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@rferreiradba -- Raphael, thank your for your clear feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by rwestMSFT** [comment]
@rferreiradba Since SSMS 17 and later uses the regular expression search that is built into Visual Studio, we are updating the article to reflect that. Thank you for your contribution. This issue will automatically close when the updated article is merged, and you'll see it published in the next few days.
