### ISSUE TITLE
Bad docker hub page link

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/sql-docs#8632]
[Enter feedback here]

The following link on this page leads to a 404 error:

https://hub.docker.com/_/microsoft-mssql-server

The above link is in this section of the page:

https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment?view=sql-server-ver16&pivots=cs1-bash#tags

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3dc2ec36-4915-f7ab-3104-282acc9321e6
* Version Independent ID: fc98af17-f3c5-adff-69ca-593f985e7882
* Content: [Deploy and connect to SQL Server Linux containers - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment?view=sql-server-ver16)
* Content Source: [docs/linux/sql-server-linux-docker-container-deployment.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-docker-container-deployment.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @amitkh-msft
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@GaTechThomas -- Thomas, thank you again for your close reading.  I am updating this article.

**Comment by rwestMSFT** [comment]
This was an internal issue that was resolved on the same day.
