### ISSUE TITLE
Bug found in newest preview: Object Microsoft.SqlServer.Management.Common.ServerConnection not working?

### ISSUE THREAD

**Issue by acul99** [MicrosoftDocs/sql-docs#8634]
Hello,
 I found a potential Bug, in the Preview Version 22.0.49 of the SQLServer.

We updated our SQLServer-Module Version, so we can automatically deploy SQL2022 Instances, after that our Script to add newly created instances to our CMS suddenly  didnt work anymore.

It seems like there is a Problem with Object:
Microsoft.SqlServer.Management.Common.ServerConnection
OR
Microsoft.SqlServer.Management.RegisteredServers.RegisteredServersStore.

When I try to create the RegisteredServersStore-Object I get an Error Message, that the connection failed to server "System.Data.SqlClient.SqlConnection"
The reason for this, is the Object Microsoft.SqlServer.Management.Common.ServerConnection which i gave as parameter to the constructor.

When using the old SQLServer Module 21.1.18256 the script runs without a Problem!

I attached 2 Txt-Files that shows the code we ran and the output of Microsoft.SqlServer.Management.Common.ServerConnection Object (called in $cnn in the Script). In the preview Version its pretty empty, while in the current stable version the Parameters are filled with information.
Bellow the output you see the results of trying to create the registeredServers-Object. In the preview it fails, in the stable version it works without a problem.

[Using_SQLServer_Preview.txt](https://github.com/MicrosoftDocs/sql-docs/files/10812887/Using_SQLServer_Preview.txt)
[Using SQLServer21.1.18256.txt](https://github.com/MicrosoftDocs/sql-docs/files/10812895/Using.SQLServer21.1.18256.txt)

**Comment by WilliamAntonRohm** [comment]
@acul99 -- thank you for your well-researched feedback.  Please add this here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
