### ISSUE TITLE
For Json Auto is not supporting in Dedicated  SQL pool

### ISSUE THREAD

**Issue by Aswinsb** [MicrosoftDocs/sql-docs#8638]
`For JSON Auto` is supported in Azure Synapse analytics serverless SQL pool , But It is **not supporting in Dedicated SQL pool**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ffb5c17b-c567-303f-00b8-0c8a0ad15fb5
* Version Independent ID: a4ccc766-4a61-5b7a-e5dd-692e3cebb503
* Content: [Format Query Results as JSON with FOR JSON - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md)
* Service: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@Aswinsb -- Aswin, thank you for your feedback.

@jovanpop-msft -- Jovan, please look into this issue.

**Comment by rwestMSFT** [comment]
@Aswinsb Thank you for your feedback. We will update the article in the next few days.
