### ISSUE TITLE
SYNONYMs Fail to Honor Pass Through Authentication for References to Linked Servers with just Current Security Context

### ISSUE THREAD

**Issue by viclindsey** [MicrosoftDocs/sql-docs#8643]
Once again, SYNONYMs are "second class" objects that fails to behave like the object it refers to in specific circumstances. In this case if you define a 4-part object reference for a SYNONYM (i.e., use a linked server), AND that linked server is setup for pass-through authentication using just the "Be made using the login's current security context", you will get an error similar to
 
```
Msg 7416, Level 16, State 2, Procedure dbo.MySynonym, Line 1 [Batch Start Line 16]
Access to the remote server is denied because no login-mapping exists.
```
 
Using the 4-part object instead of the SYNONYM in your script has no such problem. One of the primary reasons for using pass-through authentication, is elimination of such workaround as a fixed security context and/or the impersonation of specific users, and the privileged administration that such management entails.

**Comment by WilliamAntonRohm** [comment]
@viclindsey -- thank you for your clear feedback.  Are you following a particular learn.microsoft.com article?

**Comment by viclindsey** [comment]
No, not really.

I don't know how Microsoft labels deficiencies such as this. To me, this is a bug; to others it might be a feature (because SQL never has had this capability, that I am aware of). But in this case, the level of abstraction that a SYNONYM affords is wasted, because it doesn't behave like the object it refers to.

**Comment by WilliamAntonRohm** [comment]
@viclindsey -- thank you for your followup.  As this is not a documentation issue, please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
