### ISSUE TITLE
New Resource Type for Optimized Locking

### ISSUE THREAD

**Issue by albertoRamon** [MicrosoftDocs/sql-docs#8648]
[This page](https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-tran-locks-transact-sql?view=azuresqldb-current)

Need be updated with this new feature: [Optimized locking](https://learn.microsoft.com/en-us/sql/relational-databases/performance/optimized-locking?view=azuresqldb-current) (Released Feb 2023)
(Resource Type XACT doesn't exist in the manual)
![image](https://user-images.githubusercontent.com/15262462/221446627-154449a2-804b-4b47-bb6c-5b38a71f4464.png)

**Comment by WilliamAntonRohm** [comment]
@albertoRamon -- Alberto, thank you for your clear and actionable feedback.

@rwestMSFT -- Randoplh, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @albertoRamon, nice catch and sharp eye. We have a doc flight in progress to provide much more detail on OL include the XACT lock type. Look for more info soon.

**Comment by WilliamDAssafMSFT** [comment]
@AlbertoRamon look for more info on XACT lock resource here: https://learn.microsoft.com/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide#lock-granularity-and-hierarchies

**Comment by albertoRamon** [comment]
nice
