### ISSUE TITLE
Swap end_date_time/start_date_time

### ISSUE THREAD

**Issue by igor-tkachev** [MicrosoftDocs/sql-docs#8653]
Please, check the following condition

ValidFrom < end_date_time AND ValidTo > start_date_time

it looks like end_date_time/start_date_time should be swaped.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f9c244b-870b-737f-6f6d-db9675179427
* Version Independent ID: 3dde09ff-88b5-f6f3-1120-3bf8a90a395e
* Content: [Temporal Tables - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-ver16)
* Content Source: [docs/relational-databases/tables/temporal-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/temporal-tables.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@igor-tkachev -- Igor, thank you for catching this.  I am updating the article.

**Comment by rwestMSFT** [comment]
It is correct. Please don't change anything, @WilliamAntonRohm.

**Comment by rwestMSFT** [comment]
@igor-tkachev The query demonstrates a set of rows that fall *between* `ValidFrom`, which necessarily has to be lower than the end date, and `ValidTo`, which has to be higher than the start date.

#please-close
