### ISSUE TITLE
Using Microsoft ODBC driver for SQL Server in apple M2

### ISSUE THREAD

**Issue by yellowlotus** [MicrosoftDocs/sql-docs#8659]
Hello,

I would please want to know if Microsoft ODBC driver is compatible with apple M2.

Thanks in advance.

Cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c0de6fb-19ae-ff6f-8e73-ce66fa94bd64
* Version Independent ID: 34edd099-f4fe-4ac3-cdd4-abc87b35270b
* Content: [Install the Microsoft ODBC driver for SQL Server (macOS) - ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@yellowlotus -- thank you for your question.  My research so far indicates that M2 is not currently supported.


@David-Engel -- please look into this potential documentation issue.

**Comment by David-Engel** [comment]
> Hello,
> 
> I would please want to know if Microsoft ODBC driver is compatible with apple M2.
> 
> Thanks in advance.
> 
> Cheers!

@yellowlotus 

The ODBC driver is compatible with the Apple M2. The docs should really focus on Apple "ARM64" instead of being "M1" specific. But when that statement was written, we didn't know Apple would change to "M2". I'll update the page.

Regards,
David

**Comment by David-Engel** [comment]
Page updated. Changes should be visible later today.

Thanks,
David

#please-close
