### ISSUE TITLE
Azure SQL Transactional Replication & sp_adddistpublisher

### ISSUE THREAD

**Issue by kenjmartinii** [MicrosoftDocs/sql-docs#8660]
Affects the following pages and in the context of using SQL MI within a transactional replication:

https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-adddistpublisher-transact-sql?view=sql-server-ver16

sp_adddistpublisher has the parameter @storage_connection_string that is needed when setting up SQL MI as a transactional replication publisher. When setting up SQL MI as a subscriber from an on-prem transactional replication publication, however, @storage_connection_string should be omitted entirely.

The main documentation for sp_adddistpublisher only states that parameter @storage_connection_string is "...required for SQL Database" but it does not elaborate further and state that it is NOT needed when SQL MI is a subscriber for an on-prem publication. This ambiguous wording somewhat spills over into the description for parameter @working_directory as well.

The possibility that @storage_connection_string is not needed when there is an on-prem publisher and SQL MI subscriber was brought to light by this code block comment [here](https://github.com/MicrosoftDocs/sql-docs/blob/live/azure-sql/managed-instance/replication-between-two-instances-configure-tutorial.md?plain=1#L164). This code block comment should probably be removed if/when the main sp_adddispublisher doc is updated as this linked example is SQL MI to SQL MI pub/sub and introducing comments in the examples for on-prem stuff might be confusing for some folks.

To address this ambiguity, I suggest enhancing the wording within documentation for sp_adddistpublisher to state that @storage_connection_string is completely not needed when Azure SQL is a subscriber to an on-prem publication and that the value for @working_directory should be a local path/SMB share when publishing from on-prem OR use a storage account location when Azure SQL is a publisher.

**Comment by WilliamAntonRohm** [comment]
@kenjmartinii -- Ken, thank you for your thorough feedback.

@MashaMSFT -- Masha, please look into this issue.

**Comment by MashaMSFT** [comment]
Awesome, thanks for bringing this to our attention @kenjmartinii ! @sasapopo , would you mind taking a look? #reassign:sasapopo

**Comment by MashaMSFT** [comment]
Hi @kenjmartinii , Thank you for your submission! My sincere apologies for the delay it's taken to address your concern, we've been working through a very large backlog.

During this time, Git Issues have been deprecated as we've transitioned to a new feedback system. I've added your suggestion to our internal backlog (#250019) that we will continue addressing as priorities and resources allow.

We use your feedback to improve our documentation, so we are grateful for your input, and your time. I apologize for any inconvenience, and thank you for your patience and understanding. 

Masha from the SQL Docs team
#please-close
