### ISSUE TITLE
2019 statement fails on 2022

### ISSUE THREAD

**Issue by PhilM-IT** [MicrosoftDocs/sql-docs#8661]
Running this as docs state, fails on server 2022 (it did on Enterprise edition). Maybe remove the detail if this isn't relevant to 2022.

exec sp_configure @configname = 'hadoop connectivity', @configvalue = 7;
RECONFIGURE;

Msg 46934, Level 16, State 1, Procedure sp_configure, Line 177 [Batch Start Line 4]
The option 'hadoop connectivity' cannot be enabled in this edition of SQL Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94ab99ca-282b-6ace-6354-09a0d3ad97ad
* Version Independent ID: 7448fdc3-2a74-1811-38c5-aafcef2630e7
* Content: [Access external data: Azure Blob Storage - PolyBase - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/polybase/polybase-configure-azure-blob-storage?view=sql-server-ver16)
* Content Source: [docs/relational-databases/polybase/polybase-configure-azure-blob-storage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-azure-blob-storage.md)
* Service: **sql**
* Sub-service: **polybase**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @PhilM-IT, you're correct, this doc isn't clear in stating that Hadoop support was removed in SQL Server 2022. Will update, thanks for bringing attention to this!
