### ISSUE TITLE
docker run mssql 2022 permission_check script error 

### ISSUE THREAD

**Issue by developeer** [MicrosoftDocs/sql-docs#8666]
When the /var/opt/mssql/permissions_check.sh script is run for mssql 2022 contiainer, you get an error on line 4 and 59

/opt/mssql/bin/permissions_check.sh: line 4: [: : integer expression expected

It seems that in line 4 the $CONFIG_EDGE_BUILD variable is not set.

 if [ "$CONFIG_EDGE_BUILD" -eq 1 ] ; then

As a workaround I added the -e "CONFIG_EDGE_BUILD=0" to the docker run.

I know the error can be ignored but wanted to bring to your attention as it could confuse users.

This error does not occur on mssql 2019 docker image.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d971388-f1db-b134-7809-3e1fe84352a1
* Version Independent ID: 1ae396d0-78fb-4501-4992-44e4623e854a
* Content: [Secure SQL Server Linux containers - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-security?view=sql-server-ver16)
* Content Source: [docs/linux/sql-server-linux-docker-container-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-docker-container-security.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @amitkh-msft
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@developeer -- Edgardo, thank you for your close attention.

@amitkh-msft -- Amit, please look into this issue.

**Comment by amitkh-msft** [comment]
Thank you @developeer! we are aware of this issue and we are working on fixing this in upcoming CUs, hopefully by end of April/May, this should be fixed and then you should not see this logging in the container logs anymore. But thank you for your feedback, we appreciate it!

**Comment by rwestMSFT** [comment]
I'm closing this issue, because it will be addressed in an upcoming release and is unrelated to Docs.
