### ISSUE TITLE
Missing download link for 18.12?

### ISSUE THREAD

**Issue by sacrophyte** [MicrosoftDocs/sql-docs#8668]
I don't see a download link for 18.12 - is it missing? Or hidden?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver16#previous-ssms-releases)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
Hi @sacrophyte - In the release notes page we only list the last release for any previous build, so that was 18.12.1.  Thanks!

**Comment by WilliamAntonRohm** [comment]
@erinstellato-ms -- Erin, thank you for clarifying.  I've assigned this issue to you so you'll get that credit.
