### ISSUE TITLE
No instructions on how to install the extension

### ISSUE THREAD

**Issue by darla-walker** [MicrosoftDocs/sql-docs#8672]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12bf49db-fd24-7f4d-6792-6825f4e08faa
* Version Independent ID: 5f524d58-816a-812f-e43f-1916f1b4f199
* Content: [Add extensions - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/add-extensions?view=sql-server-ver16)
* Content Source: [docs/azure-data-studio/extensions/add-extensions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/extensions/add-extensions.md)
* Service: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by darla-walker** [comment]
The document says install the extension. When I click install, it takes me to GIT Hub. This document does not have any further instructions on what to do next.

**Comment by WilliamAntonRohm** [comment]
@darla-walker -- Darla, thank you for your feedback.  Please see this section of that article:
- [Install from a VSIX](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/add-extensions?view=sql-server-ver16#install-from-a-vsix).


cc @markingmyname for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by darla-walker** [comment]
@WilliamAntonRohm -  I figured out what I needed to do from someone's blog post where they said that to install an extension, click install and that some extensions must be installed from a VSIX. It's pretty obvious now but it wasn't from the initial quick read of the document. Thank you for answering my question.
