### ISSUE TITLE
Clarify what "legacy certificate" means on SQL Server Certificate Requirements

### ISSUE THREAD

**Issue by atombravo** [MicrosoftDocs/sql-docs#8674]
For the uninitiated, this requirement is not particularly clear as to what a "legacy certificate" actually is:

> The certificate must be created using the KeySpec option of AT_KEYEXCHANGE. This requires a legacy certificate. Usually, the certificate's key usage property (KEY_USAGE) will also include key encipherment (CERT_KEY_ENCIPHERMENT_KEY_USAGE) and a digital signature (CERT_DIGITAL_SIGNATURE_KEY_USAGE).

It would be really helpful to edit this to explain what "legacy certificate" means in this context (since it could be interpreted as requiring a v1 template, for instance).  Something like:

This requires a certificate which uses a legacy (https://learn.microsoft.com/en-us/windows/win32/seccertenroll/cryptoapi-cryptographic-service-providers) Cryptographic Storage Provider to store the private key.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e38f9b5-1664-79f1-9647-1c49f201dbca
* Version Independent ID: 4e38f9b5-1664-79f1-9647-1c49f201dbca
* Content: [Certificate requirements for SQL Server - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/certificate-requirements?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/certificate-requirements.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/certificate-requirements.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @sevend2
* Microsoft Alias: **v-sidong**

**Comment by WilliamAntonRohm** [comment]
@atombravo -- Adam, thank you for your feedback and proposed re-wording.

@sevend2 -- please look into this issue.

**Comment by jwarner777** [comment]
Yes, Please update this documentation, I was looking for what a Legacy Certificate is and ran across this post.  I was going to open a developer ticket with Microsoft just so I could figure out what a Legacy Certificate is as I cannot find anything that explains this in simple terms.
