### ISSUE TITLE
Incorrect steps

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/sql-docs#8675]
Install and configure Pacemaker on each cluster node under this sections, you have the following command:
sudo apt-get install -y pacemaker pacemaker-cli-utils crmsh resource-agents fence-agents corosync python3-azure

Then you have the following section: Enable and start pcsd service and Pacemaker with these: 
sudo systemctl enable pcsd
sudo systemctl start pcsd
sudo systemctl enable pacemaker

Your installing crmsh in the first section command, but after that your telling us to start and enable pcsd, crmsh and has different command structure to pcsd. 

You either need to change the command and remove crmsh and replace with pcs or you need to show the correct syntax to start crmsh and enable it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e89d1f9-5679-ffd4-8069-0d53756a41e6
* Version Independent ID: 230ea633-ca5a-ab4d-f3b6-a6654afcd714
* Content: [Configure a Pacemaker cluster for SQL Server availability groups - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-cluster-pacemaker?tabs=ubuntu&view=sql-server-ver16#create-availability-group-resource)
* Content Source: [docs/linux/sql-server-linux-availability-group-cluster-pacemaker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-availability-group-cluster-pacemaker.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
Thank you for your well-considered, positive, and thoughtful comments. You're absolutely right. We failed you. You're welcome to open a pull request to make this change yourself, or I'll get to it when I've worked through my backlog.

Once again, we appreciate constructive feedback like this. It makes us much better at documenting our products.

**Comment by amitkh-msft** [comment]
copying @aravindmahadevan-ms for further action and FYI

Thank you for the feedback. @rwestMSFT could you please help remove the entire "enable and start pcsd service section". I am creating a PR with the required changes that needs to go in.

**Comment by rwestMSFT** [comment]
An internal PR has been created. Once it is merged, this issue will automatically close. Thanks again for your submission.
