### ISSUE TITLE
Grammar in section: Digital certificate overview

### ISSUE THREAD

**Issue by ripvlan** [MicrosoftDocs/sql-docs#8678]
[Enter feedback here]
Hello, 
The end of this sentence (fragment below) doesn't read correctly.  Both the 2019 and 2022 documentation contain the same sentence.

"vouches for the identity of the certificate holder and enables the parties to communicate securely manner by using encryption."

https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/certificate-overview?view=sql-server-ver15#digital-certificate-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6869e780-7460-2ff3-1a77-e9021c1cc4e0
* Version Independent ID: 6869e780-7460-2ff3-1a77-e9021c1cc4e0
* Content: [Transport Layer Security and digital certificates - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/certificate-overview?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/certificate-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/certificate-overview.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @sevend2
* Microsoft Alias: **v-sidong**

**Comment by WilliamAntonRohm** [comment]
@ripvlan -- thank you for your close reading.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@ripvlan -- I've edited this article and the revised version should be live by tomorrow.
