### ISSUE TITLE
why I use `-e 'MSSQL_RPC_PORT=135' -e 'MSSQL_DTC_TCP_PORT=51000' `  and the DTC service is not start?

### ISSUE THREAD

**Issue by John0King** [MicrosoftDocs/sql-docs#8683]
I use docker desktop and  the latest sqlserver docker image    plus the `-e 'MSSQL_RPC_PORT=135' -e 'MSSQL_DTC_TCP_PORT=51000' `   environment variables ,  and I find that  .net framework web app fail on   communicate to the DTC  service

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c998e1ee-e33d-1e74-291b-565239adf112
* Version Independent ID: 0318ca75-d26e-243b-b322-6412b9521916
* Content: [How to use distributed transactions with SQL Server Linux containers - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-msdtc-docker?view=sql-server-ver16)
* Content Source: [docs/linux/sql-server-linux-configure-msdtc-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-msdtc-docker.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Docker desktop for Windows (on a Windows host) is not a supported scenario. There's a limitation on port 135 binding in this scenario and no workaround.

**Comment by John0King** [comment]
@VanMSFT   May I ask what happend  on the linux container on windows?   why  I can't connect to DTC in the container ?
can you explain more specific ?

**Comment by VanMSFT** [comment]
Hi @John0King - You can read more about the discussion on this here: https://github.com/MicrosoftDocs/sql-docs/issues/5690
