### ISSUE TITLE
Sql connection pool disposal of idle connections

### ISSUE THREAD

**Issue by tzographos** [MicrosoftDocs/sql-docs#8685]
Hello,
Regarding the sentence "_The connection pooler removes a connection from the pool after it has been idle for approximately 4-8 minutes_",

is it still the case or has this functionality been superseded by LoadBalanceTimeout?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a11806a5-c6e7-87fd-2aa6-7bf0254b0c61
* Version Independent ID: 053a5dfd-b9f3-a561-7c00-8bdc0c7895e4
* Content: [SQL Server connection pooling - ADO.NET Provider for SQL Server](https://learn.microsoft.com/en-us/sql/connect/ado-net/sql-server-connection-pooling?view=sql-server-ver16)
* Content Source: [docs/connect/ado-net/sql-server-connection-pooling.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/ado-net/sql-server-connection-pooling.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by tzographos** [comment]
Hello @WilliamAntonRohm  and thanks for reaching out,

So far, what I know is the following (gathered from various sources, including the ones you specify):

If `LoadBalanceTimeout` (or `Connection Lifetime`) is set, then, when a connection is returned to the pool, its creation time is compared with the current time, and the connection is destroyed if that time span (in seconds) exceeds the value specified by Load Balance timeout.

If `LoadBalanceTimeout` (or `Connection Lifetime`) is NOT set (default value = 0), then the connection pool removes the connection after it has been idle for approximately 4-8 minutes (in a random two-pass fashion). 

I would like a confirmation on the above.

**Comment by David-Engel** [comment]
> So far, what I know is the following (gathered from various sources, including the ones you specify):
> 
> If `LoadBalanceTimeout` (or `Connection Lifetime`) is set, then, when a connection is returned to the pool, its creation time is compared with the current time, and the connection is destroyed if that time span (in seconds) exceeds the value specified by Load Balance timeout.
> 
> If `LoadBalanceTimeout` (or `Connection Lifetime`) is NOT set (default value = 0), then the connection pool removes the connection after it has been idle for approximately 4-8 minutes (in a random two-pass fashion).
> 
> I would like a confirmation on the above.

Exactly. LoadBalanceTimeout overrides the default connection pool pruning logic.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder.loadbalancetimeout?view=sqlclient-dotnet-standard-5.1

Regards,
David

**Comment by David-Engel** [comment]
I updated the doc page to clarify the behavior of LoadBalanceTimeout. The changes should be reflected sometime tomorrow.

Thanks,
David

#please-close
