### ISSUE TITLE
Limitations and Restrictions section is incomplete and misleading

### ISSUE THREAD

**Issue by pevans360** [MicrosoftDocs/sql-docs#8691]
[Enter feedback here]
After reading the Limitations and Restrictions section, I attempted to rename a table.  Got the following message:
"Object '[tableName]' cannot be renamed because the object participates in enforced dependencies."

Text should be added to the Limitations and Restrictions section to cover this.  Current text leads you to believe that if you rename all references, things will work.  Obviously, certain dependencies have to be dropped and re-created.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 845be038-be75-4933-d9c1-8969edbb8cc4
* Version Independent ID: 9cf68546-15b0-f8af-2f0d-bf154237f0f8
* Content: [Rename Tables (Database Engine) - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/rename-tables-database-engine?view=sql-server-ver16)
* Content Source: [docs/relational-databases/tables/rename-tables-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/rename-tables-database-engine.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@pevans360 -- thank you for your feedback.

@WilliamDAssafMSFT - William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @ for taking the time to provide this feedback, your suggestions help improve our documentation.  Foreign keys are among the databases objects that could block the renaming of objects for sure. There are a number of scenarios that could block renaming, and the error messages usually explain why. We'll consider this feedback in future updates to this introductory tutorial. 

Thanks again for this feedback, your suggestions like this help improve our documentation.
