### ISSUE TITLE
Azure Data Studio Database Extension Options Changed?

### ISSUE THREAD

**Issue by bgdszepesi** [MicrosoftDocs/sql-docs#8694]
My screen only has two options, Create New or Open Existing. Has the import from existing been removed? I am using the newest version of Azure Data Studio.
![Screenshot 2023-03-08 114524](https://user-images.githubusercontent.com/56093667/223790785-76bb7042-f7f7-4938-84de-b63ea170f43f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59647183-7992-fa79-c600-e8e965275512
* Version Independent ID: 81c2cc4d-aa17-be21-7099-2cc9a74b6ed6
* Content: [Getting started with the SQL Database Projects extension - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension-getting-started?view=sql-server-ver16)
* Content Source: [docs/azure-data-studio/extensions/sql-database-project-extension-getting-started.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/extensions/sql-database-project-extension-getting-started.md)
* Service: **azure-data-studio**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**
![Screenshot 2023-03-08 114524](https://user-images.githubusercontent.com/56093667/223790850-65d9ec9c-73f0-451c-9ec8-d07304efacf6.png)

**Comment by dzsquared** [comment]
Sorry for the confusion, the option is now under the menu as "Create Project from Database":
![image](https://user-images.githubusercontent.com/12227241/223791592-efffeaca-43b6-4072-95b9-21af96e555d9.png)
