### ISSUE TITLE
Error: could not find query file at any of the following paths

### ISSUE THREAD

**Issue by mbourgon** [MicrosoftDocs/sql-docs#8696]
[Enter feedback here]
Busted. Seems like it's ADS that's busted.  All I get is "Error: could not find query file at any of the following paths c:\Program Files\Azure Data studio\resources\app\extensions\insights-default\c:\Program Files\Azure Data studio\resources\app\extensions\insights-default\sql\tablespace.". Same with the slow queries wiedget.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aea4ccb9-1337-4701-4d1b-ebbf251d508c
* Version Independent ID: c31b65be-3267-0130-26bf-1d9cafd13686
* Content: [Enable the table space usage sample insight widget - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/tutorial-table-space-sql-server?view=sql-server-ver16)
* Content Source: [docs/azure-data-studio/tutorial-table-space-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/tutorial-table-space-sql-server.md)
* Service: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mbourgon** [comment]
Looking at other similar errors, You need to specifically mention needing to restart  ADS after changing the setting.

**Comment by WilliamAntonRohm** [comment]
@mbourgon -- thank you for your feedback and followup.

@markingmyname -- please look into this issue.

**Comment by mbourgon** [comment]
@erinstellato-ms Naturally, it looks like it's been fixed sometime between me opening the ticket and now. I just opened it and it's working. My best guess is that it was a combination of a version change and because, on my laptop, I have to use "Run as a Different User". (laptop logs into a different domain than my servers are on). 

To test, I RDP'd to a box running an ancient version of ADS (below, over a year old) did the demo from scratch, and it worked. 

Version: 1.35.1 (system setup)
Commit: fab63efd307e54c063c8af03474bbb5d77f5fd11
Date: 2022-03-15T18:03:38.261Z
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 6.3.9600

**Comment by erinstellato-ms** [comment]
@mbourgon thanks for the udpate, glad it's resolved...and would love to see you update that 1.35 release to the latest when you're ready :)
