### ISSUE TITLE
Known Issues bug was fixed a looooong time ago

### ISSUE THREAD

**Issue by LastThird** [MicrosoftDocs/sql-docs#8699]
Heads up, the bug listed in [Known Issues](https://learn.microsoft.com/en-us/sql/azure-data-studio/notebooks/notebooks-kusto-kernel?view=sql-server-ver16#known-issues) was apparently fixed ~2.5 years ago: https://github.com/microsoft/azuredatastudio/issues/12565#issuecomment-700987555

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b17ce301-da42-49a9-2f23-fcd1e05e9cb3
* Version Independent ID: 851122ea-e078-5d77-bdee-1c0c0955d47b
* Content: [Notebooks with Kusto Kernel in Azure Data Studio - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/notebooks/notebooks-kusto-kernel?view=sql-server-ver16&source=docs)
* Content Source: [docs/azure-data-studio/notebooks/notebooks-kusto-kernel.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/notebooks/notebooks-kusto-kernel.md)
* Service: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@LastThird -- thank you bringing this to our attention.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@LastThird -- thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
