### ISSUE TITLE
Change the default to always be a replace for current document only

### ISSUE THREAD

**Issue by DeWittRagsdale** [MicrosoftDocs/sql-docs#8702]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c20e3408-243a-9581-fddc-38656b156fd0
* Version Independent ID: c20e3408-243a-9581-fddc-38656b156fd0
* Content: [Find and Replace - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/scripting/find-and-replace?view=sql-server-ver16)
* Content Source: [docs/ssms/scripting/find-and-replace.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/find-and-replace.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@DeWittRagsdale -- thank you for your request.  This repo is solely for documentation, and this seems product-related.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)
