### ISSUE TITLE
SQLPackage using AD MFA Authentication

### ISSUE THREAD

**Issue by lpargiter** [MicrosoftDocs/sql-docs#8703]
Don't know if this would be useful addition for someone else reading this document but I got this working for Synapse Serverless using AD MFA Authentication using "Authentication=Active Directory Interactive;" in the connection string: and the on-demand endpoint. 

```
/SourceConnectionString:"Server=tcp:{SynapseInstance}-ondemand.database.windows.net,1433;Initial Catalog={DatabaseName};Authentication=Active Directory Interactive;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
```

Thanks,
Luke
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e7c27cb-6f5e-4732-7258-766afb93b26e
* Version Independent ID: a9ffa884-9fa5-3cff-a5bb-c4e1f5aca197
* Content: [SqlPackage Extract - SQL Server](https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-extract?view=sql-server-ver16)
* Content Source: [docs/tools/sqlpackage/sqlpackage-extract.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage/sqlpackage-extract.md)
* Service: **sql**
* Sub-service: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
#assign:dzsquared

**Comment by rwestMSFT** [comment]
@lpargiter We are closing this issue because we are tracking it internally.

You can also engage with the engineering team directly at https://github.com/microsoft/dacfx.

AB#203362
