### ISSUE TITLE
Incorrect Documentation: DMS does not support online migration to Azure SQL DB

### ISSUE THREAD

**Issue by parableai** [MicrosoftDocs/sql-docs#8711]
In the document sql-docs/tree/live/azure-sql/migration-guides/database)/sql-server-to-sql-database-overview.md
Section [Compare migration options](https://github.com/MicrosoftDocs/sql-docs/blob/live/azure-sql/migration-guides/database/sql-server-to-sql-database-overview.md#compare-migration-options)
The documentation that Azure SQL Migration extension for Azure Data Studio supports both online and offline migrations is incorrect and causing a lot of confusion.
Verbatim line: "- Can run in both online and offline modes."

DMS does not support online migration from SQL Server to Azure SQL Database. Document should be fixed.

**Comment by WilliamAntonRohm** [comment]
@parableai -- ParableAI, thank you for your feedback.

@croblesm -- Carlos, please look into this issue.

**Comment by croblesm** [comment]
@parableai, thanks for your contribution! The documentation issue was solved, the change will be reflected later today.
