### ISSUE TITLE
trying to follow this instruction set i get error with ldap version 

### ISSUE THREAD

**Issue by mofateh86** [MicrosoftDocs/sql-docs#8713]
sudo apt-get install -y mssql-server
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mssql-server : Depends: libldap-2.4-2 but it is not installable
E: Unable to correct problems, you have held broken packages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @mofateh86, what version of Ubuntu are you running? Please note that SQL Server 2022 is only supported for Ubuntu 20.04, and this is a common error with greater versions than 20.04. This is also not a documentation issue.

https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2022

**Comment by rwestMSFT** [comment]
I am closing this issue, as it appears to be related to Ubuntu 22.04, which is currently not supported.
