### ISSUE TITLE
Is SQL Server Profiler extension available on VSCode marketplace?

### ISSUE THREAD

**Issue by OfirD1** [MicrosoftDocs/sql-docs#8728]
From the [docs here](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-server-profiler-extension?view=sql-server-ver15#install-the-sql-server-profiler-extension) it seems that SQL Server Profiler extension available on VSCode marketplace is available on the marketplace, but when searching it - it doesn't show up:

![image](https://user-images.githubusercontent.com/30159171/224976112-1551bbf2-9732-4f87-b327-8b7eb851f674.png)

**Comment by dzsquared** [comment]
#assign:dzsquared

**Comment by OfirD1** [comment]
@dzsquared oops 🙈 haven't used it before, and on that tutorial it looks so much alike. Thanks!

**Comment by dzsquared** [comment]
all good! They're closely related, but Azure Data Studio has a number of additional interface components that are helpful when working with databases.
