### ISSUE TITLE
Does not address the topic stated in the title

### ISSUE THREAD

**Issue by sderose** [MicrosoftDocs/sql-docs#8731]
[Enter feedback here]
This page is titled "Retrieve and query XML data", but has nothing on those subjects. It's all about what non-information-bearing XML syntax details may be lost on loading. There's not even a *link* to a page that's on the topic it claims to address (unless it's buried way down in "see more"). 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a8f8d06-b0b7-e92f-f3a7-86ead89fe387
* Version Independent ID: 52c88374-7487-f6de-f0f1-e55b7c98a90e
* Content: [Retrieve and query XML data - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/xml/retrieve-and-query-xml-data?view=sql-server-ver16)
* Content Source: [docs/relational-databases/xml/retrieve-and-query-xml-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/xml/retrieve-and-query-xml-data.md)
* Service: **sql**
* Sub-service: **xml**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MikeRayMSFT** [comment]
@sderose - Thank you. Staging an update
