### ISSUE TITLE
Download link for 18.12.1 is missing

### ISSUE THREAD

**Issue by MikeSpike666** [MicrosoftDocs/sql-docs#8740]
The download link for 18.12.1 is missing. Need that version due to Redgate tools not working on version 19 yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver16#18121)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by dzsquared** [comment]
download links:
![image](https://user-images.githubusercontent.com/12227241/225651520-904d84e5-891f-4a1f-a858-57a925394e46.png)

**Comment by MikeSpike666** [comment]
HAHA thanks! Too obvious :) I was looking for a link like this:
![image](https://user-images.githubusercontent.com/29395853/225895273-1c8546a1-8be4-4cb0-a48e-90f34ef65342.png)
