### ISSUE TITLE
Can we repack the unpacked DACPAC after schema changes?

### ISSUE THREAD

**Issue by karlarr** [MicrosoftDocs/sql-docs#8741]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba7594c0-a72e-9dcc-9c02-29f7814d5bd5
* Version Independent ID: 4c7e2b0e-6caa-cb44-9920-018966e9bf1b
* Content: [Unpack a DAC Package - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/data-tier-applications/unpack-a-dac-package?view=sql-server-ver15)
* Content Source: [docs/relational-databases/data-tier-applications/unpack-a-dac-package.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/unpack-a-dac-package.md)
* Service: **sql**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
hi @karlarr - a few options to get a new dacpac:
1. if you unpack a dac package to a SQL project in Visual Studio - you can build a new dacpac by running the SQL project build.
2. if you deploy the dac package to a test instance - you can make the schema changes and then extract a new dacpac.  In Azure Data Studio, the same extension used to deploy the dacpac can be used to extract a dacpac (https://learn.microsoft.com/en-us/sql/relational-databases/data-tier-applications/unpack-a-dac-package?view=sql-server-ver15#deploy-the-dacpac-using-azure-data-studio)

**Comment by WilliamAntonRohm** [comment]
@karlarr -- thank you for your question.

@dzsquared -- thank you for your answers.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
