### ISSUE TITLE
Typos etc in How-to > Backup to Azure > Backup to URL for Blob

### ISSUE THREAD

**Issue by apjanke** [MicrosoftDocs/sql-docs#8742]
In [this "SQL Server backup to URL for Microsoft Azure Blob Storage" (SQL Server 2022 version) page](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-ver16) - you've got a couple typos.

In graf 1, says "This article introduces the concepts, requirements and components necessary" - missing an Oxford comma. I think, based on previous interaction with y'all, and my reading of other docs, that Oxford commas are Microsoft house style for documents.

In Overview, graf 2, says "objects created with the storage account" - Maybe that should be "within the storage account"? My understanding is that storage accounts are containers which hold blob container and file share things, not so much a role or user account which performs actions.

Overview, graf 2, says "For more information on Azure Storage Accounts, see [About Azure Storage Accounts](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create) and for more information about Shared Access Signatures, see...". Think you need a comma before the "and for more information..."?

In "Azure Storage and S3-compatible storage", graf 1, says "shared-access signature (SAS) keys, a secure and simple way to authenticate certificates to Azure Storage" - I didn't think SAS keys used certificates. (In the X.509/cryptographic/SSL sense of "certificate".) Instead, they're an alternative to certificate-based authentication? I think saying "certificates" might be wrong here; what you're authenticating is a... well, I'm not sure, a "user" or "service" that SQL Server is acting as?

In "Backup to Azure Storage block blob vs. page blog":

Graf 2 says "If the storage key is used" - I think the correct term is "access key", or more specifically "access key for a storage account". I've never heard the term "storage key" before. And maybe "a <x> key" is better than "the <x>" key. Same for "if the Shared Access Signature is used": maybe should be "if a Shared...".

Graf 3: "in SQL Server 2016 or later version for" - "<X> or later version" sounds ungrammatical. Maybe "<x> or a later version" or "<x> or later versions"?

Graf 3: "Backup to block blob instead of page blob if you are running SQL Server 2016 or later." - I think the two word "back up" is more commonly used when you're using a verb? This sentence sounds like an imperative one, telling the reader to "back up to <somewhere>", as opposed to talking about "backup to <x>" as a noun that identifies a feature, as in "Backup to Azure Storage".

Under "The main reasons":

"and support larger database backup." - Maybe should be a plural "larger database backups"? Not sure about your house style here.

Item 4: "Customers that need to back up to page blobs via a proxy server will need to use backuptourl.exe." - I don't think that's a reason for backing up to block blobs, which I think is the topic of this bullet list. That's just another piece of info about block blob vs. page blog. As such, I think it should be a paragraph following this bullet list, rather than a bullet item in the list.

Right after that list, it says: "Taking a backup of a large database to Azure Blob Storage is subject to the limitations listed in [Azure SQL Managed Instance T-SQL differences, limitations, and known issues](https://learn.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-transact-sql-information#backup)." That's a little surprising reference to me: the doc it points to is specifically about Azure SQL Managed Instance limitations, and this here page is not talking about Azure SQL or its Managed Instances specifically. Do those limitations actually apply here to all use of Backup to URL for Microsoft Azure Blob Storage? Like, even if you're doing that backup to Azure Blob from a SQL on IaaS VM, or a regular on-prem SQL Server?

Next graf:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/2618447/226085706-c1f07a03-35ae-4fd6-9047-7af73c2e2153.png">

The two items in this bullet list are imperative complete sentences, or rather one imperative complete sentence split across two bullet items. As such, I think you need a full stop. And I think a comma would make things read better. How about styling it like:

If the database is too large, either:
* Use backup compression, or
* Back up to multiple block blobs.

(And maybe with an ellipsis, like ", or...".)

Under "Support on Linux, containers, ...":

Graf 3 says "The only supported backup to URL for Azure Blob Storage is to block blobs, using the Shared Access Signature.". I think the "backup" in "backup to URL for Azure..." should be capitalized as "Backup to..." because it is a proper noun, part of the name of this feature. In the last couple sections, "block blob", when talking about a type of storage, is singular, not plural "block blobs"; maybe it should be singular "block blob" here too. Maybe should be "a [SAS]" instead of "the [SAS]". And sounds like there's a word missing after "...for Azure Blob Storage". Maybe it should be "...for Azure Blob Storage target is to..." or "...Storage storage type is to...".

Under ["Microsoft Azure Blob Storage"](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-ver16#Blob):

Graf 3: "Blob: A file of any type and size." - I think Microsoft standard practices is to not refer to blobs as "files". In other doco on Azure Blob Storage I've read, they seem to spend effort to _differentiate_ blobs from files - like, files are the old thing, and blobs are the new cloudy modern scalable thing - and I think also avoid using the term "file" to avoid confusion with the File share feature of Azure Storage accounts, which is a different thing from Blobs. I think in this page, you're using the term "backup file" to talk about the byte sequence data written by SQL Server's backup facility, and indeed those "files" are stored in blobs when using this Backup to URL feature, but this sentence here seems to be talking generically about Azure blobs and not the SQL Server backup file format etc, and as such I'm not sure calling a blob a file like this is correct.

"There are two types of blobs..." - this [Blob storage document](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction#blobs) says there are three types of blobs, not two: block blobs, page blobs, and also append blobs.

Under "SQL Server Components":

Graf 2: "Here is a sample URL value: http[s]://ACCOUNTNAME.blob.core.windows.net/<CONTAINER>/FILENAME.bak." I think ACCOUNTNAME and FILENAME should be in angle brackets like "<CONTAINER>" is, to indicate that they're placeholders or metasyntactic variables, and not literal text. (Though I really haven't seen Azure documentation use that "<...>" placeholder notation much; is that something your house style actually uses?)

Graf 2: "Here is a sample URL value: http[s]://[...]. HTTPS is not required, but is recommended." - If your Azure Storage account has "Secure transfer required" enabled - and I believe that is the default - then HTTPS is indeed required. Might be worth noting that here, because I think that means that https _is_ required for most users, and whether it is required depends on your Azure resource configuration; it's not just an option that you can independently choose when writing your backup T-SQL here.

BTW, over in the Azure Portal's Storage Account page, the tooltip for "Secure transfer required" styles "HTTPs" with a lower-case "s". Don't think that's standard. You know how to contact those web devs about that?

<img width="536" alt="image" src="https://user-images.githubusercontent.com/2618447/226087120-85447574-2a97-4084-ad93-ac3484d7a8f9.png">

Graf 3: "Here, SQL Server backup and restore processes use credential to authenticate..." - Think that should be "use a credential" or "use the credential" or "use credentials". Sentence 3 says "The Credential stores...", but "credential" is not capitalized in any of the other sentences in this graf, though it looks like it's being used the same way here.

Graf 4: "For an example about how to create a Shared Access Signature, see [Create a Shared Access Signature](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-ver16#SAS) examples later" - Agreement issue; should be plural "For examples about..."? And maybe "examples of" is more standard usage than "examples about"?

Graf 4: "...later in this article and to create..." - Think that's a run-on, and should be "...this article, and to...", with a comma.

Graf 5: "For general information about credentials, see [Credentials](https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/credentials-database-engine?view=sql-server-ver16)" - Missing a period at the end of the sentence?

Graf 6 - "For information on other examples where credentials are used, see [Create a SQL Server Agent Proxy](https://learn.microsoft.com/en-us/sql/ssms/agent/create-a-sql-server-agent-proxy?view=sql-server-ver16)." - The thing it's linking to is not information on examples of credentials, I think; it's just information on credentials. Maybe "information on other cases where..."?

Under "Security for Azure Blob Storage":

"When creating a container for Azure Blob Storage, we recommend that you set the access to private. " - Maybe "strongly recommend", with "strongly" being bolded? If you don't use private access, you're granting anonymous read access to your blobs, which I think is something most users really don't want to do with their database backups.

"Blobs are addressable using the following URL format: https://<storage account>.blob.core.windows.net/<container>/<blob>." - Maybe that URL should be styled in fixed-width text? Other URLs in this document are, including when talking about URL naming/construction patterns.

"should be in the db_backup operator database role..." - I think it's "db_backupoperator" with no space.

"...role with Alter any credential permissions" - Wait, you need _alter_ _any_ credential permissions to perform a backup to URL? I would think you only need permission to read/use that credential?

Under "Limitations of backup/restore to Azure Blob Storage":

Bullet 1: "...using a page blob... using block blobs..." - Maybe they should both be singular or both plurarl, for consistency?

Bullet 2: "...using TSQL, SMO, ..." - I think it's styled "T-SQL"?

Bullet 2: "...cmdlets, SQL Server Management Studio Backup or Restore wizard." I think you're missing an "and" or "or" after the comma here? And maybe "wizard" should be plural? And a "the"? I'd think it'd be like "...cmdlets, or the SQL Server Management Studio Backup or Restore wizards."

Bullet 3: "So adding URL as a backup device..." - Maybe "...adding a URL..."?

Bullet 4: "...is not permitted to avoid leaving..." - Think it should be "...not permitted, to avoid...", because it's talking about the reason that WITH FORMAT is not permitted, not saying that WITH FORMAT is not permitted to do this thing.

"Specifying backupset options - RETAINDAYS and EXPIREDATE are not supported." - Don't think that dash should be there.

"that can be used (for example, User Delegation Key tokens are not supported)." - I think that "(for example..." is a separate sentence, so this should be "...that can be used. (For example, ...".

Under "Support for backup/restore statements in Azure Blob Storage":

The first table is inconsistent about whether it uses a full stop at the end of the items in the Comments column.

Under "Support for backup arguments in Azure Blob Storage":

There's a blank row of some sort between the "LOG" and "TO (URL)" items. Dunno if that's intentional.

The "CREDENTIAL" item does not have a full stop at the end of its Comments item. That's a complete sentence, so I think it should end in a full stop.

In the "NOINIT | INIT" item, the comment says "...the WITH FORMAT argument is not permitted to avoid leaving...", which I think has the missing-comma issue noted above.

The "NOFORMAT | FORMAT" item's comment says "...the FORMAT argument is not permitted to avoid leaving orphaned...", ditto. Same for the next sentence.

Under "Support for restore arguments in Azure Blob Storage":

The "CREDENTIAL" item's comment says: "WITH CREDENTIAL is only supported when using RESTORE FROM URL option to restore from Microsoft Azure Blob Storage." I don't know what that means. Does it mean that it's not supported for AWS S3 storage? Might want to clarify that, since this whole page is talking about Microsoft Azure Blob Storage.

The "FILESTREAM" item says "Not supported for snapshot backup". Elsewhere in this page, I think you're usually calling it "file-snapshot" instead of just "snapshot"? Or is this item talking about something different?

Under "Back up with SSMS":

The purple "Note" box says "...Transact-SQL, Powershell or C# rather..." - Missing Oxford comma.

"The following steps describe the changes made to the Back Up Database task" - this list isn't really talking about changes from a previous version of SSMS; it's just describing the steps to do something in the current version, or whatever versions support this operation.

"On the General page in the Destination section the URL option..." - missing comma at "...section, the URL option...", I think. And I think you might want one at "...General page, in the Destination section...", because it's not that the General page is in the Destination section; you're talking about the Destination section in the General page.

"Azure storage container: The name of the Microsoft Azure storage container" - Should "storage" be capitalized, because it's a proper noun or brand name? Or maybe not, because I see in the SSMS GUI that it says "Azure storage container" with a lower-case "s", so maybe consistency is more important here, if this is referring specifically to an item in the SSMS GUI. If that's the case, then "d. New Container" should maybe be lower-c "New container", since that's how it appears in SSMS? (SSMS v18.12.1 for me here.)

"Shared Access Policy" - I think you mean "Shared Access Signature" here?

Under "Back up with maintenance plan":

Should it be capitalized "Back up with Maintenance Plan", since Maintenance Plan is a proper noun/named thing in SSMS/SQL Server?

Says "...back up to Azure storage like the SQL Credential." Think you need a comma, like "...back up to Azure storage, like the SQL Credential." And "credential" is not capitalized in most of the rest of this page.

Says "It has the same For more information". Looks like it's missing the end of the sentence after "the same".

Purple "Note" box: Says "To create a striped backup set, a SQL Server file-snapshot backup, or a SQL credential using Shared Access token...". This isn't talking about how to create a SQL credential using SAS; it's talking about how to do a backup _using_ a credential using SAS. Maybe this should be reworded. Also I think it's "Shared Access Signature token", not just "Shared Access token".

Under "Restore with SSMS":

Says "Select the browse (...) button" - Maybe that should be styled as '("...")', to indicate that it's talking about a thing that's a literal three-dot ellipsis, and this isn't just an aside that's saying nothing?

Says "The fully qualified name..." - Should it be "fully-qualified", since that is a compound-word adjective modifying "name"? Not sure here.

Says "Add: Used to register an existing container that you do not have a shared access signature for." - Capitalize "Shared Access Signature"?

"OK": Capitalizes "Credential", inconsistent with most of the rest of this page.

Under "Code Examples":

Says "This section contains the following examples." - Maybe should be a colon (":") instead of a period (".")?

Purple Note box: "For a tutorial on using SQL Server 2016 with Azure Blob Storage, see" - The linked tutorial looks like it's for SQL Server 2016 or later (that is, any version supporting this Azure Blob thing); to me the wording here sounds like it's talking specifically about version 2016, which is a little odd for the version 2022 doc page. Maybe "2016 or later" or just omit the "2016"?

Under "Create a Shared Access Signature":

Graf 1: "Credential" - Again, inconsistent capitalization of this term.

Purple Note box: "...requires Microsoft Azure Powershell." - I think it's styled "PowerShell" with a capital internal "S"?

"to a query tool, connect to an instance of SQL Server and run the command" - Missing comma at "...Server, and run...". That's not even an Oxford comma; it's just grammar.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc04e819-4cfd-5b23-404b-8d4ed41afd21
* Version Independent ID: d254a232-e05d-0d52-0e25-7e83866f12e6
* Content: [SQL Server Backup to URL for Microsoft Azure Blob Storage - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/sql-server-backup-to-url.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/sql-server-backup-to-url.md)
* Service: **sql**
* Sub-service: **backup-restore**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@apjanke -- Andrew, thank you for your very thorough feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by rwestMSFT** [comment]
@apjanke Your feedback is appreciated. Since this is your first issue on this repo, I'd encourage you to submit that same feedback in a **pull request**. As written, there is little to no chance that every single thing you raised will be addressed. We just don't have enough time. However, if you create a pull request, we are more likely to review the requested changes.

Thank you again for your close reading.

**Comment by apjanke** [comment]
Oh, no problem! I'll make a PR; I love giving copy-editing feedback. Didn't realize that was your preferred format for suggestions.
