### ISSUE TITLE
Outdated "Feedback" tool screenshot in CONTRIBUTING.md

### ISSUE THREAD

**Issue by apjanke** [MicrosoftDocs/sql-docs#8745]
Hi, SQL Server doco folks,

In your [CONTRIBUTING.md](https://github.com/MicrosoftDocs/sql-docs/blob/b39ae98544245c008481e70eaf3bb3008a943245/CONTRIBUTING.md) guide, in the ["Reporting Bugs and Suggesting Enhancements" section](Reporting Bugs and Suggesting Enhancements), it shows this for me:

<img width="757" alt="image" src="https://user-images.githubusercontent.com/2618447/226089342-23b34141-883d-4c8a-9f4b-675b43c07bfe.png">

I think the Microsoft SQL Server docs web site has changed, and this is out of date. When I go there (today in Google Chrome on macOS), the Feedback section looks like this for me:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/2618447/226089360-183c9650-f563-48fa-839c-2d3ad38b1431.png">

That seems like a substantial difference. Maybe the Contributing guide should be updated?

**Comment by WilliamAntonRohm** [comment]
@apjanke -- Andrew, thank you for your close reading.  I am updating the article.
