### ISSUE TITLE
Troubleshoot a Full Transaction Log (SQL Server Error 9002) - Missing Parameter

### ISSUE THREAD

**Issue by JohnKNess** [MicrosoftDocs/sql-docs#8747]
Documentation: https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/logs/troubleshoot-a-full-transaction-log-sql-server-error-9002.md

The command in the script to modify the TARGET_RECOVERY_TIME is missing either the MINUTES or SECONDS parameter.

Current code snippet:

`    else if (@log_reuse_wait = 13)
    BEGIN
        select 'The oldest page on the database might be older than the checkpoint log sequence number (LSN). In this case, the oldest page can delay log truncation.' as Finding
        select 'This state should be short-lived, but if you find it is taking a long time, you can consider disabling Indirect Checkpoint temporarily' as Recommendation
        select 'ALTER DATABASE [' +@dbname+ '] SET TARGET_RECOVERY_TIME = 0' as DisableIndirectCheckpointTemporarily
    END   `

This should possibly be (e.g. SECONDS): 

`
    else if (@log_reuse_wait = 13)
    BEGIN
        select 'The oldest page on the database might be older than the checkpoint log sequence number (LSN). In this case, the oldest page can delay log truncation.' as Finding
        select 'This state should be short-lived, but if you find it is taking a long time, you can consider disabling Indirect Checkpoint temporarily' as Recommendation
        select 'ALTER DATABASE [' +@dbname+ '] SET TARGET_RECOVERY_TIME = 0 SECONDS' as DisableIndirectCheckpointTemporarily
    END   
`

Thanks for taking a look.

**Comment by WilliamAntonRohm** [comment]
@JohnKNess -- John, thank you for your feedback and suggestion.

@MashaMSFT -- Masha, please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @JohnKNess , thanks so much for your feedback! You are correct, there should be a time qualifier for TARGET_RECOVERY_TIME. I can process a change for this later in the week but also wanted you to know that you are able to make the change yourself, if you'd like to be listed as a contributor to the article. You can find more info here: [https://aka.ms/editsqldocs](https://aka.ms/editsqldocs).

I'll go ahead and close out this Git Issue for the time being but please feel free to comment should you need anything further.

Thanks again for contacting Microsoft and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
