### ISSUE TITLE
olapR  still not available for R  v.4 - 

### ISSUE THREAD

**Issue by Edouard-Legoupil** [MicrosoftDocs/sql-docs#8752]
Hello 

```

  | olapR | Applies only to SQL Server 2016, SQL Server 2017, and SQL Server 2019. R functions used for MDX queries against a SQL Server Analysis Services OLAP cube.
-- | -- | --


[olapR](https://learn.microsoft.com/en-us/sql/machine-learning/r/ref-r-olapr?view=sql-server-ver16) 	Applies only to SQL Server 2016, SQL Server 2017, and SQL Server 2019. R functions used for MDX queries against a SQL Server Analysis Services OLAP cube.
```

The version of R used there is R 3.5 - which means at least 3 years old...
Would it be possible to publish olapR on regular CRAN or tu update it so that it can work at least with R 4...?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3da02ee-698a-3851-51d0-9a6cc0ba51d4
* Version Independent ID: cb0be659-b1f7-0733-7d17-ab5a96abc0c5
* Content: [What is SQL Server Machine Learning Services (Python and R)? - SQL Server Machine Learning Services](https://learn.microsoft.com/en-us/sql/machine-learning/sql-server-machine-learning-services?view=sql-server-ver16)
* Content Source: [docs/machine-learning/sql-server-machine-learning-services.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/sql-server-machine-learning-services.md)
* Service: **sql**
* Sub-service: **machine-learning-services**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hi @Edouard-Legoupil, this isn't the forum for these type of product requests, valid as this may be. I recommend [SQL Server Feedback](https://feedback.azure.com/forums/908035-sql-server). Specifically, take a look at similar feedback here: https://feedback.azure.com/d365community/idea/84e0ef91-a34c-ec11-a819-0022484e8090 and add your vote. This feedback is viewed and managed directly by the product team. Regardless, thanks again for this feedback, your suggestions help improve our documentation.

**Comment by eldonprince** [comment]
@Edouard-Legoupil were you able to learn anything on this issue? The lack of support for olapR is an issue for us as well, particularly due to SQL Server 2022 not including olapR. Where can we find this package moving forward?
