### ISSUE TITLE
sys.dm_exec_requests.status incomplete enumeration

### ISSUE THREAD

**Issue by clement911** [MicrosoftDocs/sql-docs#8775]
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql.md doesn't mention that the status column can also have a value of 'rollback'.

**Comment by rwestMSFT** [comment]
@clement911 Thanks for your feedback. Once I've confirmed this with a PM, we'll get the article refreshed and updated.

**Comment by clement911** [comment]
Thanks. 
By the way, I believe the statuses should also all be lowercasw
