### ISSUE TITLE
Steps for installing mssql for ubuntu 22.04

### ISSUE THREAD

**Issue by rajesh78** [MicrosoftDocs/sql-docs#8776]
[Enter feedback here]

Hi,
This page has direction for installing mssql in Ubuntu 20.04. But there is no example for installing mssql in Ubuntu 20.04.

Would you please update it with the steps to install mssql in Ubuntu 22.04
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by rwestMSFT** [comment]
Thank you for your feedback. SQL Server is not supported in Ubuntu 22.04. When this changes, we will update the documentation.
