### ISSUE TITLE
SQL Server 2022 Installation Issue - Setup Account Preivileges

### ISSUE THREAD

**Issue by shankarmohannamakkal** [MicrosoftDocs/sql-docs#8778]
I am keep getting this issue, even i have full adminstration access for the system.
Also provided the access for right of backup files, right to manage auditing and the security logs, right to debug programs.
But still issue is not resolving, can one please help to fix this issue.

**Comment by rwestMSFT** [comment]
We need more information to help identify whether this is a documentation issue, or a support issue. Which article were you referencing, and what error message are you seeing?

**Comment by shankarmohannamakkal** [comment]
This issue is resolved for me. I used the below command, its installed successfully.
`C:\Temp\SQLEXPR_x64_ENU>Setup.exe /ACTION=Install /SkipRules=HasSecurityBackupAndDebugPrivilegesCheck`

**Comment by rwestMSFT** [comment]
Thanks for following up.
