### ISSUE TITLE
ubuntu section very outdated

### ISSUE THREAD

**Issue by RyanSwan0** [MicrosoftDocs/sql-docs#8789]
in 22.04 server
this does not exist:
python-software-properties

network interfaces are no longer here:
/etc/network/interfaces

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29dd905c-43f7-9045-4eee-c087e27f48e0
* Version Independent ID: 0e52d919-2745-c8c5-eb12-77b564f5e3d1
* Content: [Connect your SQL Server instance using Windows authentication (Kerberos) - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-2017#join-your-os-to-the-active-directory-domain-controller&preserve-view=true)
* Content Source: [docs/azure-data-studio/enable-kerberos.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/enable-kerberos.md)
* Service: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@RyanSwan0 -- Ryan, thank you for your feedback. SQL Server is not supported in Ubuntu 22.04. When this changes, we will update the documentation.
