### ISSUE TITLE
Azure Data Studio DEB download link inconsistent on download page 

### ISSUE THREAD

**Issue by jaapie** [MicrosoftDocs/sql-docs#8802]
As I reported last month (#8680), the download link is inconsistent again. At the top of the page the link to download the x64 DEB points to the new version, but the link in the Ubuntu-specific section is the old version.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install Azure Data Studio - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver16&tabs=redhat-install%2Credhat-uninstall)
* Content Source: [docs/azure-data-studio/download-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download-azure-data-studio.md)
* Service: **azure-data-studio**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
@jaapie That you did report, and it looks like we messed up somewhere along the way.  Two things... 1) working on fixing it.  2) figuring out why it happened and how to resolve it permanently.  Thank you for your diligence and for reporting it.  I'll follow up when we get it sorted.

**Comment by erinstellato-ms** [comment]
Hi @jaapie Thanks for your patience.  We've updated the docs and that change should get pushed out tomorrow so you should see it reflected then.  Further, it should not occur in the future.  If you find a problem, please let us know.
