### ISSUE TITLE
Grammar improvement for index design tip

### ISSUE THREAD

**Issue by gdipersio** [MicrosoftDocs/sql-docs#8804]
This suggestion refers to the "Tip" at the bottom of the document.  I just wish to improve the grammar slightly.

The tip calls out _nonclustered_ indexes - I believe it also applies to clustered indexes because the problem relates to B-tree changes common to both.  Could be worth asking R&D whether to remove the word "nonclustered" from this tip.  They might add that this tip will intentionally cause skip-scan operations, which is valuable information to intermediate readers.  Maybe consider my cosmetic changes up front and backlog a task for R&D to improve/expand on this tip?

OLD:
"When a column in a nonclustered index key columns have many duplicate values, performance can degrade for updates, inserts, and deletes. One way to improve performance in this situation is to add another column to the nonclustered index."

NEW:
"When any key column in a nonclustered index has many duplicate values, performance can degrade for updates, inserts, and deletes. One way to improve performance in this situation is to place a column that has greater distinctness in the index key, before the problematic column."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20a94499-0b07-2deb-46d6-102e6f1dedac
* Version Independent ID: 324ed645-ed52-6104-9ffd-2907ff315565
* Content: [SQL Server and Azure SQL index architecture and design guide - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/sql-server-index-design-guide?view=sql-server-ver16)
* Content Source: [docs/relational-databases/sql-server-index-design-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/sql-server-index-design-guide.md)
* Service: **sql**
* Sub-service: **supportability**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@gdipersio Thanks - we've been wanting to refresh this article for a while now, so I've modified your wording and will incorporate it into the refresh. You can expect to see the updated article in the next day or so.
