### ISSUE TITLE
Need to clarify ESU for SQL Server 2008/2008 R2

### ISSUE THREAD

**Issue by pablojavierf** [MicrosoftDocs/sql-docs#8808]
There should be a note or clarification that ESU is not available for SQL Server 2008 and 2008 R2 through Azure Arc as those versions are [not supported](https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/prerequisites?view=sql-server-ver16&tabs=azure#supported-sql-server-versions-and-operating-systems) by Azure Arc.

At the beginning of this docs, it gives the wrong idea that customers could get ESU for 2008 via Arc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd3e29e8-6559-58d3-27a5-3c443bd76c94
* Version Independent ID: 37b33566-6d93-ca52-7f54-4101ddb3a332
* Content: [What are Extended Security Updates? - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-extended-security-updates?view=sql-server-ver16)
* Content Source: [docs/sql-server/end-of-support/sql-server-extended-security-updates.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/end-of-support/sql-server-extended-security-updates.md)
* Service: **sql**
* Sub-service: **install**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@pablojavierf -- Pablo, thank you for your research and feedback.

@rwestMSFT -- Randolph, please look into this issue.

**Comment by rwestMSFT** [comment]
@pablojavierf SQL Server 2008 and 2008 R2 support for ESUs was extended to July 2023, per the note on the ESU page.

> Customers on SQL Server 2008 (10.0.x) and SQL Server 2008 R2 (10.50.x) can migrate to Azure services if they wish to continue receiving Extended Security Updates, until [July 12, 2023](https://www.microsoft.com/windows-server/extended-security-updates). See the [Overview](https://learn.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-extended-security-updates?view=sql-server-ver16#overview) for more information.

#please-close

**Comment by pablojavierf** [comment]
Hi Randolph!

Thanks for your support. The observation was for Azure Arc particularly.

***@***.***

Arc does not support 2008 as documented<https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/prerequisites?view=sql-server-ver16&tabs=azure#supported-sql-server-versions-and-operating-systems>.

Regards!

***@***.***
Pablo Javier Fernández
Cloud Solution Architect - Data & AI
LATAM SQL Advanced Cloud Expert
***@***.******@***.***>
"Data is the way"
P Please consider the environment before printing this email.
