### ISSUE TITLE
How to use Transfer Accelerated endpoint

### ISSUE THREAD

**Issue by ivanlewis** [MicrosoftDocs/sql-docs#8811]
[Enter feedback here]

How to use Transfer Accelerated S3 endpoint for creating the backups?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9b99dc-4e63-75a7-a6ed-ea635159c01e
* Version Independent ID: 6e9b99dc-4e63-75a7-a6ed-ea635159c01e
* Content: [Back up to URL best practices & troubleshooting for S3-compatible object storage - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url-s3-compatible-object-storage-best-practices-and-troubleshooting?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/sql-server-backup-to-url-s3-compatible-object-storage-best-practices-and-troubleshooting.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/sql-server-backup-to-url-s3-compatible-object-storage-best-practices-and-troubleshooting.md)
* Service: **sql**
* Sub-service: **backup-restore**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hi @Ivanlewis, this may not be the best forum for this type of discussion. I recommend [Microsoft Q&A (SQL Server)](https://docs.microsoft.com/answers/products/sql-server), [SQL Server Feedback](https://feedback.azure.com/forums/908035-sql-server), Microsoft Support, or your support partners. 

The AWS Transfer Accelerated S3 endpoint it is not specifically listed in our documentation and is not supported. The S3-compatible storage features of SQL Server 2022 work with any S3-compatible storage vendor's platform, and we do not test for every vendor's complete feature set. However, if the Transfer Accelerated S3 endpoint uses the same APIs, it will likely work fine.
