### ISSUE TITLE
BULK Error handling options on Azure

### ISSUE THREAD

**Issue by albertoRamon** [MicrosoftDocs/sql-docs#8813]
Could be possible that [this feature ](https://learn.microsoft.com/en-us/sql/t-sql/functions/openrowset-transact-sql?view=sql-server-ver16#bulk-error-handling-options)has not been integrated on Azure Databases, and is not mentioned in the manual ?

Basically this work perfectly
CREATE VIEW [hubspot].[V_LZ_contacts]
	AS
	SELECT *
		FROM OPENROWSET(
			BULK							'2023/04/05/contacts.csv'
			, DATA_SOURCE					= 'HSDataSource'
			, FORMATFILE					= 'FormatFile/contacts.fmt'
			, FORMATFILE_DATA_SOURCE		= 'HSDataSource'
			, MAXERRORS						= 100
		) AS x;
GO

This (+2 lines) even doesn't compile, thus . . .
CREATE VIEW [hubspot].[V_LZ_contacts]
	AS
	SELECT *
		FROM OPENROWSET(
			BULK							'2023/04/05/contacts.csv'
			, DATA_SOURCE					= 'HSDataSource'
			, FORMATFILE					= 'FormatFile/contacts.fmt'
			, FORMATFILE_DATA_SOURCE		= 'HSDataSource'
			, MAXERRORS						= 100
			**, ERRORFILE						= 'FormatFile/errorsOpenRowSet/contacts.txt'
			, ERRORFILE_DATA_SOURCE_NAME	= 'HSDataSource'**
		) AS x;
GO

ERROR: _Incorrect syntax near 'ERRORFILE_DATA_SOURCE_NAME'._

**Comment by WilliamAntonRohm** [comment]
@albertoRamon -- Alberto, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by albertoRamon** [comment]
" Applies to: SQL Server 2017 (14.x) CTP 1.1. Beginning with SQL Server 2017 (14.x), the error_file_path can be in Azure Blob Storage."

this means that 
* this parameter is ONLY for SQL on-site? doesn't have a lot of sense . . 
* if you are on-site you need v2017 ?

**Comment by MikeRayMSFT** [comment]
> " Applies to: SQL Server 2017 (14.x) CTP 1.1. Beginning with SQL Server 2017 (14.x), the error_file_path can be in Azure Blob Storage."
> 
> What this means?
> 
> * this parameter is ONLY for SQL on-site? doesn't have a lot of sense . .
> * if you are on-site you will need SQL v2017 ?

Hello, @albertoRamon  - thank you for the discussion.

The features are available in SQL Server 2017 and later.

CTP n.n represent a preview release. We're updating the article to clarify. Will also review applicability for Azure SQL Database.
