### ISSUE TITLE
For APT based Linux distros, apt-key add is deprecating

### ISSUE THREAD

**Issue by jduke-halls** [MicrosoftDocs/sql-docs#8821]
In both the Debian and Ubuntu sections, the documentation states to add the signing key to APT using the ```apt-key add -``` command.  The [apt-key man page](https://manpages.debian.org/testing/apt/apt-key.8.en.html#DEPRECATION) shows how to download the armored key for use with apt using the ```wget``` command. Using ```curl``` to match the rest of the documentation, it would look like the below:

```
sudo su 
curl https://packages.microsoft.com/keys/microsoft.asc -o /etc/apt/trusted.gpg.d/microsoft.asc
```

This deprecation warning comes up on all supported Ubuntu 20.04 LTS and 22.04 LTS, Debian 11, and the current versions of Kali , Pop_OS, and Mint in my tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=alpine18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@jduke-halls -- thank you for your well-researched feedback.

@David-Engel -- please look into this issue.

**Comment by timw5** [comment]
I ran into this problem last week, I updated the example from the docs to show what worked for me. 
@David-Engel Hopefully this helps! 

```BASH

sudo apt-get update && sudo apt-get install -y gnupg2 curl 

if ! [[ "18.04 20.04 22.04" == *"$(lsb_release -rs)"* ]];
then
    echo "Ubuntu $(lsb_release -rs) is not currently supported.";
    exit;
fi

sudo su
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/microsoft-archive-keyring.gpg
#Alternatively, you can put the key in /etc/apt/keyrings/

# The .list file at https://packages.microsoft.com/config/ubuntu/22.04/prod.list needs to be changed to include the "signed-by" piece you will see below.
# I Currently hard coded to 22.04 as thats what I'm using, just make sure that the signed-by piece references the location that you saved the key in from the previous step.
echo "deb [arch=amd64,armhf,arm64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" > /etc/apt/sources.list.d/mssql-release.list

exit
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

# optional: for bcp and sqlcmd
sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18
echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
source ~/.bashrc

# optional: for unixODBC development headers
sudo apt-get install -y unixodbc-dev

```

**Comment by David-Engel** [comment]
This has been addressed on the doc page.

Thanks,
David

#please-close
