### ISSUE TITLE
Oracle Extension non functional or partaly functional

### ISSUE THREAD

**Issue by Thadir** [MicrosoftDocs/sql-docs#8826]
[Enter feedback here]

Currently this plugin (oracle) does not support querying a core functionality I think this should be mentioned in the plugin page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad5899cc-4757-b131-c36e-a0243b5bad95
* Version Independent ID: 8df879ca-e629-a313-6af9-8a6c3c04eefe
* Content: [Quickstart: Connect and explore Oracle databases - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/quickstart-oracle?view=sql-server-2016)
* Content Source: [docs/azure-data-studio/quickstart-oracle.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/quickstart-oracle.md)
* Service: **azure-data-studio**
* GitHub Login: @tdoshin
* Microsoft Alias: **timioshin**

**Comment by TimShererWithAquent** [comment]
Thanks @Thadir - we'll look into updating the article.

**Comment by rwestMSFT** [comment]
I am closing this because it appears the issue was resolved.
