### ISSUE TITLE
Incomplete instruction on enabling TCP IP 

### ISSUE THREAD

**Issue by mdesai639** [MicrosoftDocs/sql-docs#8827]
[Enter feedback here]
The instruction on this page for enabling TCP IP protocol is incomplete. It says that after enabling the protocol through SQL Sever Configuration Manager, you need to restart the instance service. What is missing here is the need to restart the SQL Browser service.
On SQL Server 2019 Express, **I found that if you install it with default parameters it doesn't enable TCP IP protocol of the instance. It also doesn't enable SQL Browser service. So you also need to start the Browser service (after enabling it - setting it startup type to Automatic). If you don't start the Browser service you can't connect to the SQL Instance remotely. So this page need to have the instruction to restart Browser service if it is not running.**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3e350b6-b39b-0a14-6637-06fbec7b171a
* Version Independent ID: f92e2065-c2d4-3e93-c136-de4da69d7586
* Content: [Enable or Disable a Server Network Protocol - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/enable-or-disable-a-server-network-protocol?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/enable-or-disable-a-server-network-protocol.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/enable-or-disable-a-server-network-protocol.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by TimShererWithAquent** [comment]
@mdesai639 Thanks for finding this -

**Comment by rwestMSFT** [comment]
@mdesai639 Thanks for the feedback. We will refresh the article and include a note at the end to remind customers to restart the Browser service. You should see the updated article in the next day or so.
