### ISSUE TITLE
Please indicate that MI needs at least 10 characters long.

### ISSUE THREAD

**Issue by LifeRyuto** [MicrosoftDocs/sql-docs#8836]
The document says below. Azure SQL Managed Instance needs at least 10 characters long. Please indicate it as a note.

> Password Complexity
> Password complexity policies are designed to deter brute force attacks by increasing the number of possible passwords. When password complexity policy is enforced, new passwords must meet the following guidelines:
> 
> The password doesn't contain the account name of the user.
> 
> The password is at least **eight** characters long.
> 
> The password contains characters from three of the following four categories:
> 
> Latin uppercase letters (A through Z)
> 
> Latin lowercase letters (a through z)
> 
> Base 10 digits (0 through 9)
> 
> Non-alphanumeric characters such as: exclamation point (!), dollar sign ($), number sign (#), or percent (%).
> 
> Passwords can be up to 128 characters long. Use passwords that are as long and complex as possible.

Also, the document says below. Please indicate whether this information is applied to Azure SQL Managed Instance or not.
> Azure SQL Database enforces [password complexity](https://learn.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-ver16#password-complexity). The password expiration and policy enforcement sections do not apply to Azure SQL Database.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58afcd81-a8da-a2bc-5ed0-1a28cf242781
* Version Independent ID: 05c003a1-7f84-67b9-d82e-150aff74faed
* Content: [Password Policy - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-ver16#password-complexity)
* Content Source: [docs/relational-databases/security/password-policy.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/password-policy.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @LifeRyuto - Thanks for your feedback on our docs! The password policy for Azure SQL Managed Instance is referenced here: https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/frequently-asked-questions-faq?view=azuresql#password-policy-

That being said, I realize that our document here could use a link for clarity. I will update the doc. Thanks!
