### ISSUE TITLE
"No documentation" warning for version 16.x (2022)

### ISSUE THREAD

**Issue by jovton** [MicrosoftDocs/sql-docs#8842]
On this page https://learn.microsoft.com/en-us/sql/relational-databases/security/ledger/ledger-overview?source=recommendations&view=sql-server-ver16#database-digests, there is a note with a link taking us to "Automatic digest management". It opens on the correct documentation, BUT... there is a message on top of that page telling us that the version requested was not found, and it automatically redirected us to the "latest" version. The target for the link is https://learn.microsoft.com/en-us/sql/relational-databases/security/ledger/ledger-how-to-enable-automatic-digest-storage?view=sql-server-ver16

According to the documentation, SQL Server 2022 (16.x) is supported.

![referrer](https://user-images.githubusercontent.com/5833599/231516632-b1d3f19b-c8d5-496e-9583-3187bab00ea6.png)
![target](https://user-images.githubusercontent.com/5833599/231517286-4f2e8a28-d609-40c2-93f3-23c9b256811c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c29298a-7abc-7d20-e18f-96df1f9d432f
* Version Independent ID: 0c29298a-7abc-7d20-e18f-96df1f9d432f
* Content: [Ledger overview - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/ledger/ledger-overview?source=recommendations&view=sql-server-ver16#database-digests)
* Content Source: [docs/relational-databases/security/ledger/ledger-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/ledger/ledger-overview.md)
* Service: **sql-database**
* Sub-service: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@jovton -- thank you for your feedback.

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
Hi @jovton - Thanks for letting us know! We appreciate it. I'm fixing the page.
