### ISSUE TITLE
After Installing SSMS 19.01/19.02 getting error during login (provider: SSL Provider, error: 0 - The received certificate has expired)

### ISSUE THREAD

**Issue by ssharma222** [MicrosoftDocs/sql-docs#8845]
TITLE: Connect to Server
------------------------------

Cannot connect to server\abc.

------------------------------
ADDITIONAL INFORMATION:

A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The received certificate has expired.) (Microsoft SQL Server, Error: -2146893016)
[Enter feedback here]
Request you to redirect us to fix this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver16)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by ssharma222** [comment]
I am connecting to SQL server 2019 and no certificate is used for SQL
installation. No additional options selected. Connectivity working with all
versions of SSMS 18.xx.

**Comment by erinstellato-ms** [comment]
Can you try enabling 'Trust server certificate' on the Connection Properties tab to see if that resolves it?

**Comment by ssharma222** [comment]
Yes, it is working after enabling 'Trust server certificate'. This was not
the case in SSMS18.xx or older version. How can I have it checked along
with installation by default? Or do we have any other option?

**Comment by erinstellato-ms** [comment]
You cannot have the option checked by default.  If you need to enable the option, then you either have Force Encryption set to Yes for the instance, or you do have a certificate installed and it is expired.  I recommend you check SQL Server Configuration Manager.  Within there, expand SQL Server Network Configuration, and right-click on the Protocols entry for the instance.  On the Flags tab, see if Force Encryption is set to Yes.  On the Certificate tab, see if there is Certificate selected and if so, is it expired.

**Comment by ssharma222** [comment]
You are right,  Force Encryption is set to Yes. This is the reason it was throwing the error for the instance. Thank you a bunch for your quick help.  Please close this case.

**Comment by erinstellato-ms** [comment]
#please-close
