### ISSUE TITLE
Confusing phrasing

### ISSUE THREAD

**Issue by leorb** [MicrosoftDocs/sql-docs#8846]
Document states: "the dataworkspace.*excluded*Projects array within settings lists all the SQL projects *included* in the Projects pane."
Confusion is because *excluded* is the opposite of *included* 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d25be772-12d5-6a8e-1eb5-9982ae0bfcac
* Version Independent ID: c4652a23-abc2-63ed-11fa-334b0f46698a
* Content: [SQL Database Projects extension - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension?view=sql-server-ver16)
* Content Source: [docs/azure-data-studio/extensions/sql-database-project-extension.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/extensions/sql-database-project-extension.md)
* Service: **azure-data-studio**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
Hi @leorb - thanks for pointing that out, it's an error in the docs.  


It should be:
```
the dataworkspace.excludedProjects array within settings lists all the SQL projects excluded from the Projects pane.
```
I'll get it updated shortly

#assign:dzsquared

**Comment by dzsquared** [comment]
#please-close
