### ISSUE TITLE
SSMS System Requirements not listing Windows Server 2019

### ISSUE THREAD

**Issue by CathySpears** [MicrosoftDocs/sql-docs#8849]
[Enter feedback here] The "SSMS System Requirements" section of this page
https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16
does not include Windows Server 2019 & 2022 as Supported Operating Systems.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by WilliamAntonRohm** [comment]
@CathySpears -- Cathy, thank you for catching these.

@erinstellato-ms -- Erin, please look into this issue.

**Comment by erinstellato-ms** [comment]
@CathySpears To confirm, you are looking at the Download SSMS page, correct?  I see this:

![image](https://user-images.githubusercontent.com/98599126/231872588-4d9f6246-ebb6-45df-8a6c-5e273f1a16c7.png)

**Comment by CathySpears** [comment]
Hi Erin - Yes. Thanks

**Comment by erinstellato-ms** [comment]
close
