### ISSUE TITLE
Missing step about Microsoft SQL Server repository

### ISSUE THREAD

**Issue by tjlee** [MicrosoftDocs/sql-docs#8851]
To install `mssql-server-fts` one needs to add Microsoft SQL Server repository
```
sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2022.list)"
```
add public GPG Key
```
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
```
invoke update
```
sudo apt update
```
and only then install `mssql-server-fts`
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a804984c-ad78-db28-3865-d34a71806770
* Version Independent ID: aa5ccdc1-8b7b-da83-4e50-b8afe7f76135
* Content: [Install SQL Server Full-Text Search on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-setup-full-text-search?view=sql-server-ver16)
* Content Source: [docs/linux/sql-server-linux-setup-full-text-search.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-full-text-search.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@tjlee -- Vasilii, thank you for your feedback and solution.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @tjlee - Thanks for your feedback on this document. The steps you outlined are a prerequisite for installing FTS, and are highlighted in our first note on the page:

![image](https://user-images.githubusercontent.com/40007119/232730923-aa48f923-2065-4b38-b038-a68588fa69ee.png)

SQL Server is a requirement before installing FTS, so we want the customer to follow the steps of our SQL Server install first. It would be redundant to list the same steps in this document.

https://learn.microsoft.com/sql/linux/quickstart-install-connect-ubuntu#install

We appreciate the feedback, but will leave the current page as is for now. Thanks for your time!

FYI @rwestMSFT
