### ISSUE TITLE
Link does not work 

### ISSUE THREAD

**Issue by robertplata** [MicrosoftDocs/sql-docs#8852]
This link does not work on this page:
https://msdn.microsoft.com/library/dd578580(SQL.100).aspx

Is it obsolete?  Or, is there an updated page for this topic?

Thanks!
Rob
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7b22d6-0ccb-bda0-7ea6-dc4a7e4817c5
* Version Independent ID: 9039d0ef-8830-a67d-6cd0-b17ef2a78081
* Content: [Partitioned tables and indexes - SQL Server, Azure SQL Database, Azure SQL Managed Instance](https://learn.microsoft.com/en-us/sql/relational-databases/partitions/partitioned-tables-and-indexes?view=sql-server-ver16)
* Content Source: [docs/relational-databases/partitions/partitioned-tables-and-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/partitions/partitioned-tables-and-indexes.md)
* Service: **sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@robertplata -- Rob, please see this document:
- [Partitioned Table and Index Strategies Using SQL Server 2008](https://download.microsoft.com/download/d/b/d/dbde7972-1eb9-470a-ba18-58849db3eb3b/parttableandindexstrat.docx)

This article shows the current support for SQL Server 2008:
- [Microsoft SQL Server 2008](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-sql-server-2008)

**Comment by VanMSFT** [comment]
Thanks @WilliamAntonRohm and @robertplata - I'm fixing the link.

#assign:VanMSFT
