### ISSUE TITLE
"monitoring-with-dmvs" uses a DMV that is not available in Managed Instance

### ISSUE THREAD

**Issue by brain246** [MicrosoftDocs/sql-docs#8854]
Hello there,

I just wanted to use this query on a managed instance (tried in master as well as in a database):
```
SELECT TOP 10 *
FROM sys.resource_stats
WHERE database_name = 'resource1'
ORDER BY start_time DESC;
```
as described here:
https://learn.microsoft.com/en-us/azure/azure-sql/database/monitoring-with-dmvs?view=azuresql-mi

However, in doing so i am getting this error message: `Invalid object name 'sys.resource_stats'.`

**Comment by WilliamAntonRohm** [comment]
@brain246 -- Thomas, thank you for your feedback.  I see in the Azure SQL Managed Instance view of this article that `sys.resource_stats` is not mentioned:
- [Monitor resource use](https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/monitoring-with-dmvs?view=azuresql-mi#monitor-resource-use)

![image](https://user-images.githubusercontent.com/27738025/232915607-3ee1e1fd-be2c-4b74-a892-1fb6b2d9eb49.png)

However, there is a reference to `sys.resource_stats` under [Maximum sessions](https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/monitoring-with-dmvs?view=azuresql-mi#maximum-sessions) that may be incorrect:
> You can get historical statistics on sessions by querying the [sys.resource_stats](https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-resource-stats-azure-sql-database) view and reviewing the active_session_count column.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @brain246 , thanks for contacting Microsoft and bringing this to our attention! I've removed the sentence for now while we investigate if there's an alternative way to find that information for Azure SQL Managed Instance and updated the applies to.  This change will be live either this week or next. 

I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks again for reaching out to improve our docs, and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
