### ISSUE TITLE
Update link to point to Microsoft Command Line Utilities Version 16

### ISSUE THREAD

**Issue by mggrand** [MicrosoftDocs/sql-docs#8855]
Hi Guys!

The docs of SQL Server Version 16 are pointing to the Microsoft Command Line Utilities Version 15. 
After installing those the version of the sqlcmd.exe is 2019.x.
When installing the SQL Server 2022 we got the sqlcmd.exe with Version 2022.x.

Can you please update the link to point to the Microsoft Command Line Utilities Version 16?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8da1f57b-a8fd-cca7-4cf0-9d594d365062
* Version Independent ID: 60c46780-6a03-7958-c77a-e7c94e3b9e85
* Content: [sqlcmd Utility - SQL Server](https://learn.microsoft.com/en-us/sql/tools/sqlcmd/sqlcmd-utility?view=sql-server-ver16)
* Content Source: [docs/tools/sqlcmd/sqlcmd-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlcmd/sqlcmd-utility.md)
* Service: **sql**
* Sub-service: **tools-other**
* GitHub Login: @grrlgeek
* Microsoft Alias: **jeschult**

**Comment by WilliamAntonRohm** [comment]
@mggrand -- Goman, thank you for your feedback and request.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@grrlgeek -- Jes, please look into this issue.  I'm not sure where to find the Version 16 release and build numbers.

**Comment by Matteo-T** [comment]
Technically, there is no "Microsoft Command Line Utilities Version 16" (yet).

So, no, that cannot happen. :)

What can (and should) happen is that the "Microsoft Command Line Utilities Version 15" that one would download from that page should have the binaries that are versioned something like 16.x.x.x, i.e. "aligned" with SQL 2022 CUs.

I'm waiting for some issue with the EULAs for the standalone MSIs to be addressed before I can make that happen. But, as I said, they would be branded `15` and, more importantly, they would just install (by default) under the same folder (`C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn`). In the Windows Installer lingo, the new MSIs would be an in-place upgrade of the old MSIs. You would, however, see `sqlcmd.exe -?` and `bcp.exe -?` banners showing a "reassuring" 16.x.x.x.

As usual, never get too emotionally attached to "version numbers"... they don't mean a whole lot at the end of the day. Just know that whatever is in the currently available version (15.x.x.x) and the upcoming version (16.x.x.x) are functionally identical.

**Comment by grrlgeek** [comment]
[like]  Jes Schultz reacted to your message:
________________________________

**Comment by mggrand** [comment]
@Matteo-T Thank you for your feedback. It does not matter if the two versions are the same. But we should be able to install the "Microsoft Command Line Utilities Version 16", because if we install SQL Server 2022 we also get the Utilities in Version 16. So, i think the tools are around somewhere and just need to be published as standalone download.

**Comment by Matteo-T** [comment]
> @Matteo-T Thank you for your feedback. It does not matter if the two versions are the same. But we should be able to install the "Microsoft Command Line Utilities Version 16", because if we install SQL Server 2022 we also get the Utilities in Version 16. So, i think the tools are around somewhere and just need to be published as standalone download.

Are implying that I would not know if they are? Based on what?

**Comment by rwestMSFT** [comment]
I am closing this issue, because the original question has been answered.
