### ISSUE TITLE
Clarify headings of topics on this page

### ISSUE THREAD

**Issue by tastyeggs** [MicrosoftDocs/sql-docs#8860]
This title here threw us off: "Requirements for a Service in an Availability Group to Receive Remote Messages". 

Our use case with Service Broker and Availability Groups is quite basic - there is a producer and a consumer, all operating on the same cluster. The above heading should clarify as "Receive Remote Messages from Other Service Broker Instances". 

We mistakenly assumed "remote" here meant our client application, and went on a wild-goose chase to try and understand why these extra endpoints, grants and routes were required, and started blindly following instructions, until it clicked after 2-3 days of research.

Please make the page very clear - people are landing here by googling "SQL Server Service Broker Availability Groups", and multiple members on the team assumed the first section needed to be done for our basic use case. Most of us don't even realize that multiple service broker clusters can be connected together.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fddd2356-d321-4a6f-0858-9da13b80e296
* Version Independent ID: ff377e0c-a700-0d80-c267-ca2ab60bfe60
* Content: [Service Broker with availability groups - SQL Server Always On](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/service-broker-with-always-on-availability-groups-sql-server?view=sql-server-ver16)
* Content Source: [docs/database-engine/availability-groups/windows/service-broker-with-always-on-availability-groups-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/service-broker-with-always-on-availability-groups-sql-server.md)
* Service: **sql**
* Sub-service: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- please review this update in [private PR 26859](https://github.com/MicrosoftDocs/sql-docs-pr/pull/26859).

**Comment by WilliamAntonRohm** [comment]
@tastyeggs -- thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
