### ISSUE TITLE
SA_PASSWORD not MSSQL_SA_PASSWORD

### ISSUE THREAD

**Issue by jmgomez77** [MicrosoftDocs/sql-docs#8874]
Please review the post or the docker image, because SA_PASSWORD is the right variable name.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28a7eacd-7e91-3dac-8c5b-873d9dcdf89f
* Version Independent ID: 4fa4b92d-178b-7997-a095-3b2bef2ebabb
* Content: [Troubleshooting SQL Server Docker containers - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-troubleshooting?view=sql-server-ver16)
* Content Source: [docs/linux/sql-server-linux-docker-container-troubleshooting.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-docker-container-troubleshooting.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @amitkh-msft
* Microsoft Alias: **amitkh**

**Comment by rwestMSFT** [comment]
@jmgomez77 This is not correct. SA_PASSWORD was changed to MSSQL_SA_PASSWORD to follow the naming convention for other environment variables.

Thanks for your feedback.
