### ISSUE TITLE
Missing notice about required %TEMP% space for exporting Data-tier application

### ISSUE THREAD

**Issue by chriswue** [MicrosoftDocs/sql-docs#8894]
This page ais missing a big notice about the fact that SSMS writes all data to %TEMP% first before writing the actual output.

I tried to perform the "Export Data-tier application" for a large (550GB) Azure SQL Database to a VM running in Azure. I attached a 4 TB data disk and configured it to store the BACPAC file there. After several hours the export ended up failing with Out of Diskspace which seemed nonsensical. After trying again I caught it in state where it was pulling loads of data from SQL sever but no disk activity was happening at all for long period of time, likewise RAM usage didn't go. Since all this data has to end up somewhere I checked the various disk drives and found C: drive to be completely filled up.

After some searching I found that the only way to fix this is to configure your system %TEMP% folder to be located on the extra data disk.

Since that isn't really mentioned anywhere and the official Microsoft recommendation for taking backups of large databases is SSMS Export Data-tier application this was not all that easy to figure since the error messages weren't helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9d185ed-733f-2f63-2c28-e63670053b7d
* Version Independent ID: eebf764e-3c26-00f1-c627-03098efe1743
* Content: [Export a Data-tier Application - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/data-tier-applications/export-a-data-tier-application?view=sql-server-ver16)
* Content Source: [docs/relational-databases/data-tier-applications/export-a-data-tier-application.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/export-a-data-tier-application.md)
* Service: **sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by N-Kannan** [comment]
Hi @chriswue 
As per my understanding you need to add small steps in the documentation. Can you please check this doc i add. Once you give confirmation i will make the change and do pull request.

It's recommended to configure the system %TEMP% folder to be located on a separate data disk. This will ensure that there is enough space for the export process to complete successfully without running into disk space issues.

To configure the system %TEMP% folder, you can follow these steps:

Open the System Properties window by pressing the Windows key + Pause/Break or by right-clicking on This PC and selecting Properties.

Click on the Advanced system settings link on the left-hand side.

In the System Properties window that appears, click on the Environment Variables button at the bottom.

Under System Variables, locate the TEMP and TMP variables, and click the Edit button.

Change the value of both variables to a path on the separate data disk you have set up. For example, if your data disk is mounted on D:, you can set the values to D:\Temp.

Click OK to save the changes and close all windows.

After completing these steps, the system %TEMP% folder will be located on the separate data disk and will have enough space to accommodate large data exports from SSMS without causing disk space issues.

**Comment by chriswue** [comment]
Sounds good to me, thanks

**Comment by N-Kannan** [comment]
If it's good I will add and make a pull request. If there any thing want to update in my content @chriswue

**Comment by N-Kannan** [comment]
@WilliamAntonRohm can I work on this issue. Please check the above steps. Is is OK to add are anything want to update more detail. Review and let me know 😊

**Comment by chriswue** [comment]
Unfortunately moving %TEMP% isn't sufficient - the export still fails with a full C drive at the end. The culprit is "IsolatedStorage" which is located in the users' App Data directory. Don't know how to point this to another drive

**Comment by WilliamAntonRohm** [comment]
@N-Kannan -- Kannan, you are welcome to work on this.  Your changes will be reviewed before including them in the live documentation.

@chriswue -- thank you for your contributions to this discussion.

**Comment by markingmyname** [comment]
@chriswue - thank you for your contribution.  We will make those edits.

@N-Kannan - thank you for your additional contribution.

The article should be updated by the end of te week.

thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site or the [Q & A](https://docs.microsoft.com/en-us/answers/products/sql-server) site.
