### ISSUE TITLE
SQL Database Project does not work with Azure Analytics Syntax (OPENROWSET)

### ISSUE THREAD

**Issue by FullStackSteve** [MicrosoftDocs/sql-docs#8897]
**Problem**
When we try to use the SQL Database Project VSCode / Azure Data Studio extension, the syntax parsing/building is inconsistent with Azure Synapse Analytics Studio, particuarly with `OPENROWSET` syntax for connecting to CosmosDB via Azure Synapse Link.

The queries work on Azure Synapse Analytics Studio, but we would prefer local development rather than through a web GUI.

**How to replicate**
1. Install [SQL Database Project Extension](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension?view=sql-server-ver16) on VSCode / Azure Data Studio
2. Either
    a. Import an existing [Azure Synapse Analytics Serverless SQL](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension-getting-started?view=sql-server-ver16#create-a-database-project-from-an-existing-database) pool with `OPENROWSET` derived views from CosmosDB using the SQL Database Project Extension OR
    b. Copy the quickstart code [here](https://learn.microsoft.com/en-us/azure/synapse-analytics/sql/create-use-views#cosmosdb-view):
    ```
    CREATE DATABASE SCOPED CREDENTIAL MyCosmosDbAccountCredential
    WITH IDENTITY = 'SHARED ACCESS SIGNATURE', SECRET = 's5zarR2pT0JWH9k8roipnWxUYBegOuFGjJpSjGlR36y86cW0GQ6RaaG8kGjsRAQoWMw1QKTkkX8HQtFpJjC8Hg==';
    GO
    CREATE OR ALTER VIEW Ecdc
    AS SELECT *
    FROM OPENROWSET(
          PROVIDER = 'CosmosDB',
          CONNECTION = 'Account=synapselink-cosmosdb-sqlsample;Database=covid',
          OBJECT = 'Ecdc',
          CREDENTIAL = 'MyCosmosDbAccountCredential'
        ) with ( date_rep varchar(20), cases bigint, geo_id varchar(6) ) as rows
    ```
3. See error `Incorrect syntax: 'CREATE VIEW' must be the only statement in the batch.` in IDE:
<img width="776" alt="image" src="https://user-images.githubusercontent.com/19396027/235730290-f248049a-27c7-439b-a95d-413e9f7214f7.png">

**Expected result**
That we can use the SDK example code in VSCode / Azure Data Studio as well as on Azure Synapse Analytics

**Comment by FullStackSteve** [comment]
Note that the quickstart code needs to be changed to the following to work in Azure Synapse Analytics Studio:

```
CREATE DATABASE SCOPED CREDENTIAL MyCosmosDbAccountCredential
WITH IDENTITY = 'SHARED ACCESS SIGNATURE', SECRET = 's5zarR2pT0JWH9k8roipnWxUYBegOuFGjJpSjGlR36y86cW0GQ6RaaG8kGjsRAQoWMw1QKTkkX8HQtFpJjC8Hg==';
GO
CREATE VIEW Ecdc
AS SELECT *
FROM OPENROWSET(
      PROVIDER = 'CosmosDB',
      CONNECTION = 'Account=synapselink-cosmosdb-sqlsample;Database=covid',
      OBJECT = 'Ecdc',
      SERVER_CREDENTIAL = 'MyCosmosDbAccountCredential'
    ) with ( date_rep varchar(20), cases bigint, geo_id varchar(6) ) as rows
```

**Comment by dzsquared** [comment]
Hi @FullStackSteve - I apologize but I can't "move" this issue directly, it would be best over in https://github.com/microsoft/azuredatastudio - which doesn't yet support serverless SQL pools for SQL projects.  (soon! but not yet.)

**Comment by WilliamAntonRohm** [comment]
@dzsquared -- Drew, thank you for those pointers.

@FullStackSteve -- Steve, please add this issue to https://github.com/microsoft/azuredatastudio, as Drew suggested.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
