### ISSUE TITLE
Please include how to disable this 'feature'

### ISSUE THREAD

**Issue by ken747747** [MicrosoftDocs/sql-docs#8915]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24d3ba88-bb53-d484-ee90-d3d531befe5d
* Version Independent ID: 5382dd32-b21d-2e3a-2c6b-ed2cb7c18863
* Content: [Code Outlining - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/scripting/code-outlining?view=sql-server-ver16)
* Content Source: [docs/ssms/scripting/code-outlining.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/code-outlining.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by rwestMSFT** [comment]
Hi @ken747747. What is it that you are asking?

Code outlining lets you collapse code blocks by manually selecting the `[-]` button in the margin of SQL Server Management Studio. If you don't select the `[-]`, the feature doesn't engage. If you accidentally collapse a code area, you can select the `[+]` option in the same margin to disable it.

We look forward to hearing from you.

**Comment by ken747747** [comment]
I occasionally expand the region by accident and would prefer to be able to enable / disable them entirely.  No worries if it’s not an option just wanted to be sure I hadn’t missed it somewhere.

Thank you for the very prompt response,

Ken Jett | Senior Software Developer | Stratagen Systems, Inc. | DDS Wireless | ***@***.******@***.***> | O: 425.821.8454

**Comment by rwestMSFT** [comment]
Understood. Thanks for getting back to us. SSMS is based on the Visual Studio shell, and therefore inherits a lot of features, including that one.
