### ISSUE TITLE
Missing entry for error SameKeyMaterialNotFoundOnRemoteServer

### ISSUE THREAD

**Issue by nachoalonsoportillo** [MicrosoftDocs/sql-docs#8919]
I think it should be nice to have an entry added for the SameKeyMaterialNotFoundOnRemoteServer error in this article. Let me know if you find it appropriate and I can add it myself (ialonso@microsoft.com)

Details about the error can be found here https://techcommunity.microsoft.com/t5/azure-database-support-blog/error-samekeymaterialnotfoundonremoteserver-while-coping-azure/ba-p/3630398

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83b6d066-9a0d-ebdb-7432-fb4ae7a82794
* Version Independent ID: 645e4ba4-7898-c2ec-bbb4-c39aecb7e21f
* Content: [Common errors with customer-managed keys in Azure Key Vault - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/troubleshoot-tde?view=azure-sqldw-latest)
* Content Source: [docs/relational-databases/security/encryption/troubleshoot-tde.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/troubleshoot-tde.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
Nacho, if you want to create a PR for this, feel free.

**Comment by rwestMSFT** [comment]
@nachoalonsoportillo We haven't heard from you for a long time. Feel free to add a PR. In the meantime, I'm closing this.
