### ISSUE TITLE
document is not up to date with authentication options 

### ISSUE THREAD

**Issue by mc-mc** [MicrosoftDocs/sql-docs#8920]
Quoting from the page:
When the bcp utility is connecting to SQL Database or Azure Synapse Analytics, using Windows authentication or Azure Active Directory authentication is not supported. Use the -U and -P options.

This is no longer true, the latest version of bcp allows connection to the cloud based services without using the -U and -P options.
We can connect just fine using these flags only:  -G -q -c
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86bd520a-7468-fd55-c357-b0f645a917ef
* Version Independent ID: 3dc9dee5-afcb-8287-4441-e84ff717186a
* Content: [bcp Utility - SQL Server](https://learn.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver16)
* Content Source: [docs/tools/bcp-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/bcp-utility.md)
* Service: **sql**
* Sub-service: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@mc-mc -- Michael, thank you for your clear feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by rwestMSFT** [comment]
I believe this issue has been resolved, as the article was recently updated.
