### ISSUE TITLE
Incorrect statements about joins...

### ISSUE THREAD

**Issue by Davi-Gray** [MicrosoftDocs/sql-docs#8926]
In one paragraph, the text states:

> The SELECT list for a join can reference all the columns in the joined tables, or any subset of the columns. The SELECT list is not required to contain columns from every table in the join. For example, in a three-table join, only one table can be used to bridge from one of the other tables to the third table, and none of the columns from the middle table have to be referenced in the select list. **This is also called an anti semi join.**

This is not in fact called an anti semi join, which is a join operation that returns columns from the left (or right) side of a join that do not have a match on the other side. Nothing (necessarily) to do with a three-table join, so this could confuse some readers.

A couple paragraphs later, the text says:

> When SQL Server processes joins, the Query Optimizer chooses the most efficient method (out of several possibilities) of processing the join. This includes choosing the most efficient type of physical join, the order in which the tables will be joined, and even using **types of logical join operations that cannot be directly expressed with Transact-SQL syntax, such as semi joins and anti semi joins.**

Sort of true, in the limited sense that there are no SEMIJOIN or ANTISEMIJOIN operators, but it's easy (and fairly common) to perform these operations in T-SQL using e.g. subqueries.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f3f4741-a003-e127-ce4d-2bc2ded98886
* Version Independent ID: 576a3826-5b7a-15ab-6405-7cd445b6b7c0
* Content: [Joins (SQL Server) - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/performance/joins?view=sql-server-ver16)
* Content Source: [docs/relational-databases/performance/joins.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/joins.md)
* Service: **sql**
* Sub-service: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @Davi-Gray for taking the time to provide this feedback.  We'll review and consider updates on this subject in a future update to the article.
