### ISSUE TITLE
Wrong information CAB download for offline installation

### ISSUE THREAD

**Issue by moematsuo** [MicrosoftDocs/sql-docs#8928]
I tried to apply KB5021127 to SQL Server 2017 offline. I downloaded CAB files for CU31 (SRO_3.5.2.777_1033.cab, SRS_9.4.7.1162_1033.cab..). However I failed to apply KB5021127 due to wrong CAB files.
I retried with old CAB files(SRO_3.3.3.1400_1033.cab, SRS_9.2.0.1400_1033.cab...) and succeed.

I followed the instruction. If the instruction is correct, CAB files for KB5021127 were same with CU31. I think this is wrong.
https://learn.microsoft.com/en-us/sql/machine-learning/install/sql-ml-cab-downloads?view=sql-server-2017#sql-server-2017-cabs
-------
GDR releases of SQL Server will require the same component .cab file versions as the next earlier non-GDR release, such as a CU. For example, for the SQL Server 2019 CU16 GDR, use the same .cab download versions as SQL Server 2019 CU16.
-------

**Comment by WilliamDAssafMSFT** [comment]
Thanks @moematsuo for taking the time to provide this feedback. Apologize for the delay in response - Microsoft Build was a busy time for us.

Keeping in mind this isn't a support platform, this is a platform to improve docs, can you clarify what version you were patching from and to? "I tried to apply KB5021127 to SQL Server 2017 offline" what was the version of SQL Server 2017 before applying KB5021127?
It appears to have worked when you applied the cabs for SQL 2017 CU14-18, did you try the cabs for later versions of SQL 2017?

**Comment by moematsuo** [comment]
Hi @WilliamDAssafMSFT Thank you for checking.
The version was Microsoft SQL Server 2017 (RTM-GDR) (KB5014354) - 14.0.2042.3 (X64) .

**Comment by WilliamDAssafMSFT** [comment]
@moematsuo We appreciate you bringing this to our attention. **A doc update for this article is in flight.** Thanks again for taking the time and effort to document this feedback, your suggestions help improve our documentation.
