### ISSUE TITLE
Hhh

### ISSUE THREAD

**Issue by Andyblack301** [MicrosoftDocs/sql-docs#8933]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c85ee3f3-9c1b-f58f-57e7-47b3ac56014d
* Version Independent ID: 563123f2-41a3-ef47-ce0a-75ca0373da08
* Content: [Use the Visual Studio Code mssql extension - SQL Server](https://learn.microsoft.com/en-us/sql/tools/visual-studio-code/sql-server-develop-use-vscode?view=sql-server-ver16)
* Content Source: [docs/tools/visual-studio-code/sql-server-develop-use-vscode.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/visual-studio-code/sql-server-develop-use-vscode.md)
* Service: **sql**
* Sub-service: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
@Andyblack301 - did you have any details to share?

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
