### ISSUE TITLE
This statement is abjectly false.

### ISSUE THREAD

**Issue by LJ9999** [MicrosoftDocs/sql-docs#8941]
The following statement is not true:

"When Windows is configured with IPv6 SQL Server, components automatically recognize the existence of IPv6."

Right now I'm looking at a SQL Server instance that does not have IPv6 in its list of settings for TCP/IP while a second instance does.

Fix this doc. It's wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 294ff50f-8b6f-bacd-79cf-5bb6573a92f2
* Version Independent ID: 7f3ffff1-f165-25dd-8863-0d788e16f10c
* Content: [Connecting Using IPv6 - SQL Server](https://learn.microsoft.com/en-us/sql/tools/configuration-manager/connecting-using-ipv6?view=sql-server-ver16)
* Content Source: [docs/tools/configuration-manager/connecting-using-ipv6.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/configuration-manager/connecting-using-ipv6.md)
* Service: **sql**
* Sub-service: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@LJ9999 -- thank you for your direct feedback.

@markingmyname -- please look into this issue.

**Comment by rwestMSFT** [comment]
@LJ9999 Can you please provide some information about your configuration, so that we can establish what exactly is false to the absolute worst degree about our documentation.

> Right now I'm looking at a SQL Server instance that does not have IPv6 in its list of settings for TCP/IP while a second instance does.

As currently written, this sounds very much like a support issue, and I'd highly recommend reaching out to Microsoft Support.

**Comment by rwestMSFT** [comment]
Hi @LJ9999. Since we haven't heard from you, I am closing this issue. If you can provide the information we requested, then please feel free to comment below.
