### ISSUE TITLE
Error on https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/azure-ad-authentication-sql-server-setup-tutorial re result of Set Admin action

### ISSUE THREAD

**Issue by martinbherbener** [MicrosoftDocs/sql-docs#8946]
Just after the heading https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/azure-ad-authentication-sql-server-setup-tutorial?view=sql-server-ver16#create-logins-and-users there is this statement:

"After the Azure Arc agent on the SQL Server host has completed its operation, the admin account selected in the Azure Active Directory pane in the portal will be a sysadmin on the SQL Server instance."

However, from my experience, and also from the text a littler earlier in the page ("The Azure AD admin login is listed in sys.server_principals, but is not part of the sysadmin role. To grant the Azure AD admin the sysadmin role, use the [sp_addsrvrolemember](https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-addsrvrolemember-transact-sql?view=sql-server-ver16) stored procedure.") this is not actually true, and further action by an administrator is needed to make the newly added AAD account a sysadmin.

thanks

Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d7c8f586-e5f8-794c-26b6-6319fef9103a
* Version Independent ID: d7c8f586-e5f8-794c-26b6-6319fef9103a
* Content: [Set up Azure Active Directory authentication for SQL Server - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/azure-ad-authentication-sql-server-setup-tutorial?view=sql-server-ver16#configure-azure-ad-authentication-for-sql-server-through-azure-portal)
* Content Source: [docs/relational-databases/security/authentication-access/azure-ad-authentication-sql-server-setup-tutorial.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/azure-ad-authentication-sql-server-setup-tutorial.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @GithubMirek
* Microsoft Alias: **mireks**

**Comment by WilliamAntonRohm** [comment]
@martinbherbener -- Martin, thank you for your feedback.

@GithubMirek -- Mirek, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @martinbherbener - Sorry for the delay! We are looking into this issue and confirming with the Product Team.

**Comment by VanMSFT** [comment]
Hi @martinbherbener - Thanks again for your feedback. I checked with the Product Team, and setting the Azure AD admin now grants `sysadmin` privileges to that principal. There was a bug in the RTM release of SQL Server 2022 where the workaround listed in the documentation was needed, but has since been addressed in later CUs. I'll edit the article for clarification.
