### ISSUE TITLE
No document for `sys.dm_os_enumerate_filesystem`

### ISSUE THREAD

**Issue by hochun836** [MicrosoftDocs/sql-docs#8948]
I can find the [document](https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-enumerate-fixed-drives) for `sys.dm_os_enumerate_fixed_drives`, but I cannot find the document for `sys.dm_os_enumerate_filesystem`

ref: [sql-doc github](https://github.com/MicrosoftDocs/sql-docs/tree/live/docs/relational-databases/system-dynamic-management-views)

**Comment by WilliamAntonRohm** [comment]
@hochun836 -- Ho, thank you for your feedback.  I am investigating.

**Comment by rwestMSFT** [comment]
This is correct. It is not documented.

**Comment by WilliamAntonRohm** [comment]
@rwestMSFT -- Randolph, thank you for commenting.  Is `sys.dm_os_enumerate_filesystem` purposely undocumented?

**Comment by rwestMSFT** [comment]
No, it was not intentional. I've added it to my backlog. It may take weeks or months to get it documented.

**Comment by rwestMSFT** [comment]
AB#90630

Closing because we're tracking this internally. Thanks again, @hochun836, and to @WilliamAntonRohm for following up.

**Comment by rwestMSFT** [comment]
Update: we will not be documenting this stored procedure for the foreseeable future, because it is for internal use, and is not supported.
