### ISSUE TITLE
Temporal tables - Needs to mention that versions are logged even if data doesn't change

### ISSUE THREAD

**Issue by chadbaldwin** [MicrosoftDocs/sql-docs#8950]
Referencing:

* https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables
* https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/temporal-tables.md

A question came up for me today that I had to build a test case for, which was...if you have a table using a system-versioned temporal table and you "update" a record in the current table, but you do not change the value, is a record still logged in the temporal table?

The answer to that question is "yes", and after thinking about it, this makes sense to me. For example, if you write an update statement to update a million records, just because the data matches for all of your updates doesn't mean it does zero work, it's up to the developer to ensure they're not doing useless work.

Example:

```sql
GO
CREATE TABLE dbo.TestTemporal (
    ID int NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED
  , ColumnA varchar(50) NOT NULL
  , ValidFrom datetime2 GENERATED ALWAYS AS ROW START NOT NULL
  , ValidTo datetime2 GENERATED ALWAYS AS ROW END NOT NULL
  , PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
)
WITH (SYSTEM_VERSIONING = ON);
GO
INSERT INTO dbo.TestTemporal (ColumnA) VALUES ('SomeVal')
GO
UPDATE dbo.TestTemporal SET ColumnA = 'SomeVal';
GO
SELECT * FROM dbo.TestTemporal FOR SYSTEM_TIME ALL;
```

This will end up with 1 record in the temporal table and 1 record in the current table.

I think it's worth considering whether parts of this documentation should be re-worded to indicate that it's not "data changes" or "row is modified" that is logged, but instead DELETE and UPDATE operations (essentially the "deleted" table records). Or, maybe just have a quick snippet somewhere that clarifies that it does not check whether data was actually changed.

This might be obvious to experienced SQL devs, but I think it's worth having it in the documentation.

**Comment by WilliamAntonRohm** [comment]
@chadbaldwin -- Chad, thank you for your thorough feedback.

@rwestMSFT -- Randolph, please look into this issue.

**Comment by rwestMSFT** [comment]
@chadbaldwin Thanks for your feedback.

This is outside of the scope of temporal tables, because any data modification like this to a table will be carried out by the Database Engine, whether or not temporal tables are enabled. Using your same example on a non-temporal table, you'll be able to see transaction log entries updating the row or rows even if the values haven't "changed".

Because of that, while I agree this might be useful information in relation to temporal tables, I will need to speak to a few people internally to figure out the best way to document this, or direct our readers to a related article that possibly contains this information already. That might take some time.

**Comment by chadbaldwin** [comment]
@rwestMSFT That's fair, it's not a result of how temporal tables works, but more so how the database engine works. The same goes for change tracking, triggers (`deleted` table) and, like you said, logs. I didn't really think of it that way.

I think it would be useful to indicate that you can't build a temporal table and expect to use it as a perfect history of "data changes", but I'm also not sure how I would improve the documentation to reflect that while also not including out-of-scope information...but I guess that's why I don't work on the docs team 😂

**Comment by rwestMSFT** [comment]
Definitely not an easy one to do in a simple way 😄.

**Comment by rwestMSFT** [comment]
@chadbaldwin I'm closing this issue for now, but we are tracking it internally. However, there's no promise as to when we'll address it.

AB#70883

**Comment by rwestMSFT** [comment]
@chadbaldwin We are performing a minor refresh on this article, including a new NOTE that will call out your requested change. The changes will publish in the next day or so.

> When you run any data modification queries on a temporal table, the Database Engine adds a row to the history table even if no column values change.

Thank you again for your feedback, and for helping improve the Database Docs.
