### ISSUE TITLE
Enabling of Optimized locking & availability is unclear

### ISSUE THREAD

**Issue by lukeskinner** [MicrosoftDocs/sql-docs#8957]
> Where is optimized locking currently available?
> Currently, optimized locking is available in Azure SQL Database.
> 
> Optimized locking is available in the following service tiers:
> 
> - all DTU service tiers
> - all vCore service tiers, including provisioned and serverless
>
> Optimized locking is not currently available in:
> - Azure SQL Managed Instance
> - SQL Server 2022 (16.x)

I'm very interested in this feature and when it becomes available but I feel there's some information missing about availability or how to enable this.

I have around 800 databases hosted in Azure (UK South, UK West, West Europe) on a mixture of standalone DTU databases and some in elastic pools (also DTU based).

Not a single one of these has optimised locking enabled when I check using this:

> SELECT IsOptimizedLockingOn = DATABASEPROPERTYEX('testdb', 'IsOptimizedLockingOn');

I understand this github is to talk about the documentation so I would like to see this area expanded to either include:
- The regions in which this available (or a link to where you can find this)
- How to enable optimized locking (even if it says you have to wait for Microsoft to enable it for you)

I've scoured through all the documentation I can find online and it says how to check it's enabled, how to to turn it off (by making a support ticket in Azure) but nothing for how to turn it on!

I'm happy to wait to get this but I've spent ages trying to figure it out and maybe someone else will in the future go down this path.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51ad0ed6-1729-2e9d-f975-ff28d3649362
* Version Independent ID: 51ad0ed6-1729-2e9d-f975-ff28d3649362
* Content: [Optimized locking - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/performance/optimized-locking?view=azuresqldb-current&viewFallbackFrom=sql-server-ver16#where-is-optimized-locking-currently-available)
* Content Source: [docs/relational-databases/performance/optimized-locking.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/optimized-locking.md)
* Service: **sql**
* Sub-service: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
@lukeskinner Thanks for taking the time to create this issue. Can you provide a screenshot of one of the DATABASEPROPERTYEX commands, and the region it is in? You can obfuscate the actual database name from the command.

**Comment by WilliamDAssafMSFT** [comment]
Hi @lukeskinner following up on this. Can you confirm the results of the DATABASEPROPERTYEX command and the region?

**Comment by WilliamDAssafMSFT** [comment]
Hi @lukeskinner following up on this. Can you confirm the results of the DATABASEPROPERTYEX command for one of your user databases, and the region?

**Comment by WilliamDAssafMSFT** [comment]
Closing this issue. Happy to followup.
