### ISSUE TITLE
max. concurrent login limits at Azure SQL Databases not listed for General Purpose G5 Standard

### ISSUE THREAD

**Issue by fslearn** [MicrosoftDocs/sql-docs#8960]
I have found in our documentation that with General Purpose G5 Standard is no max concurrent logins listed -->  [Single database vCore resource limits - Azure SQL Database | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-sql/database/resource-limits-vcore-single-databases?view=azuresql#general-purpose---provisioned-compute---gen5).

But with Business Critical Stadard Series as well with the DTU Standard it is listed -->[Single database vCore resource limits - Azure SQL Database | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-sql/database/resource-limits-vcore-single-databases?view=azuresql#gen5-hardware-part-1-4)

It would be helpful to have this information also handy for General Purpose G5 Standard.

**Comment by WilliamAntonRohm** [comment]
@fslearn -- thank you for raising this.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @fslearn for taking the time to provide this feedback. A doc update is in flight. In general, "Max concurrent workers" and "Max concurrent logins" are the same. The documentation has some gaps to make this more clear and address gaps and discrepancies.
