### ISSUE TITLE
SSMS Maintenance Plan Wizard - overlapping screen elements makes screen unreadable

### ISSUE THREAD

**Issue by silentk62** [MicrosoftDocs/sql-docs#8963]
Related to #4530 - which is closed, but the problem persists even in Copy Database

Overlapping screen elements makes the screen unreadable.
![image](https://github.com/MicrosoftDocs/sql-docs/assets/37136154/367d2f55-c0ab-411f-8b7c-969748ef74d6)

SSMS vsn 19.0.2
Using RDP from Dell laptop full resolution

See problem in some Options screens too
![image](https://github.com/MicrosoftDocs/sql-docs/assets/37136154/7df9447a-92d4-40b5-b3c7-246a8bbb2d53)

**Comment by WilliamAntonRohm** [comment]
@silentk62 -- thank you for your followup.  This is a product issue, rather than a documentation issue.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)
