### ISSUE TITLE
Docs page for sys.server_principals now shows information only relevant to Azure-based offerings for all versions of SQL Server

### ISSUE THREAD

**Issue by RobAshton-IM** [MicrosoftDocs/sql-docs#8964]
This bug relates to this page:
Published link: https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-server-principals-transact-sql?view=sql-server-ver16
Live branch file: https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-server-principals-transact-sql.md

Commit a50595b incorrectly changed the contents of this page so that the information relevant only to Azure-based offerings, such as Azure SQL Database, is now the only version of text provided for _all_ versions of SQL Server.

This has lost information regarding logins of types U (Windows Users), G (Windows Groups), C (Certificate-mapped), and K (Asymmetric Key-mapped) for the SQL Server 2016, 2017, 2019 and 2022 versions.

Please update this page to separate the different versions of text for the versions that they apply to and reintroduce the lost information.

**Comment by WilliamAntonRohm** [comment]
@RobAshton-IM -- Rob, thank you for your clear feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Thanks, Rob.

Hi @AndreasWolter - Do you mind commenting on this GitHub Issue and see if we need to revert some changes? Thanks!

#assign:AndreasWolter

**Comment by rwestMSFT** [comment]
It appears this issue was resolved.
