### ISSUE TITLE
Request document update

### ISSUE THREAD

**Issue by wzcgh2019** [MicrosoftDocs/sql-docs#8969]
[Enter feedback here]
Would appreciate updating to latest Ubuntu 20.04 and RHEL8

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12171705-e172-ae55-c93a-7c9c707a6fc8
* Version Independent ID: 918d86e4-98bc-1465-243d-e0cc308f859a
* Content: [Join SQL Server on Linux to Active Directory - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-join-domain?source=recommendations&view=sql-server-ver16)
* Content Source: [docs/linux/sql-server-linux-active-directory-join-domain.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-join-domain.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @tejasaks
* Microsoft Alias: **tejasaks**

**Comment by rwestMSFT** [comment]
This is already on our roadmap. Thanks for your feedback!

**Comment by rwestMSFT** [comment]
AB#70883
