### ISSUE TITLE
Should this still say preview?

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/sql-docs#8976]
Should [this](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension?view=sql-server-ver16#visual-studio-code-preview) still say preview?

![image](https://github.com/MicrosoftDocs/sql-docs/assets/1784452/c7b45581-73e9-4c41-a306-a28fe095b3a5)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d25be772-12d5-6a8e-1eb5-9982ae0bfcac
* Version Independent ID: c4652a23-abc2-63ed-11fa-334b0f46698a
* Content: [SQL Database Projects extension - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension?view=sql-server-ver16)
* Content Source: [docs/azure-data-studio/extensions/sql-database-project-extension.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/extensions/sql-database-project-extension.md)
* Service: **azure-data-studio**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
A timely question :)
As of 8am Pacific today the VS Code extension for SQL Database Projects is still in preview - but we're about to release the v1 (GA) version very soon.
