### ISSUE TITLE
sys.query_store_plan_feedback wrong value in state_desc column

### ISSUE THREAD

**Issue by sqlworldwide** [MicrosoftDocs/sql-docs#8993]
[sys.query_store_plan_feedback (Transact-SQL)](https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-query-store-plan-feedback?view=sql-server-ver16) state_desc has wrong values. In my SQL 2022 CU4 version test column state = 7 shows state_desc  = 'FEEDBACK_VALID' but learn website has 7 'FEEDBACK_INVALID'

**Comment by WilliamAntonRohm** [comment]
@sqlworldwide -- thank you for your well-researched feedback.  I am updating this article.

**Comment by rwestMSFT** [comment]
@sqlworldwide Great catch. Especially with these articles in the process of updating, I really appreciate your attention detail.
