### ISSUE TITLE
Missing attribute 'Yes: Percentile Adjusting'

### ISSUE THREAD

**Issue by sqlworldwide** [MicrosoftDocs/sql-docs#8994]
The new query attribute for MermoryGrintInfo -->IsMemoryGrantFeedbackAdjusted is missing. This was added in SQL 2022 as a new IQP feature.
Yes: Percentile Adjusting

This is also documented in the new showplan .xsd file.

`
<xsd:simpleType name="MemoryGrantFeedbackInfoType">
            <xsd:restriction base="xsd:string">
			<xsd:enumeration value="Yes: Adjusting" />
			<xsd:enumeration value="Yes: Stable" />
			<xsd:enumeration value="No: First Execution" />
			<xsd:enumeration value="No: Accurate Grant" />
			<xsd:enumeration value="No: Feedback Disabled" />
			<xsd:enumeration value="Yes: Percentile Adjusting" />
		</xsd:restriction>
 </xsd:simpleType>
`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b770595-1ea3-2dc5-cfd9-85719e527434
* Version Independent ID: 5b770595-1ea3-2dc5-cfd9-85719e527434
* Content: [Query processing feedback features - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/performance/intelligent-query-processing-feedback?view=sql-server-ver15#batch-mode-memory-grant-feedback)
* Content Source: [docs/relational-databases/performance/intelligent-query-processing-feedback.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/intelligent-query-processing-feedback.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@sqlworldwide -- thank you for bringing this to our attention.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Hi Taiob @sqlworldwide! Would you like to create a pull request to contribute the change and get contributor credit on the article? You can author the suggestion by making an edit to our open-source docs here on GitHub. To add a commit and receive credit as a contributor to the article, [create a Pull Request](https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute). By opening a pull request, you're collaborating with the author(s), like myself, to add changes directly to the documentation. After the updated article is reviewed and published, GitHub will list you as an article contributor. Select the "Edit" pencil at the top of most articles in Microsoft Docs to begin a pull request.

**Comment by WilliamDAssafMSFT** [comment]
Ok, noted. I'll handle any PR.

@sqlworldwide are you referring to the XML sample after `You can see this property in the root operator of the graphical showplan or in the showplan XML output:`? Not every `MemoryGrantInfo` node will have an `IsMemoryGrantFeedbackAdjusted` element. Is your feedback that we should have a sample `MemoryGrantInfo` node with a value for `IsMemoryGrantFeedbackAdjusted`?

**Comment by sqlworldwide** [comment]
Thank you. We should add another item in the table below. Value = "Yes: Percentile Adjusting." I do not know the description, so I did not submit a PR.
Or should we change the current value ="Yes:Adjusting" to Value = "Yes: Percentile Adjusting"?


![Screenshot 2023-06-04 191406](https://github.com/MicrosoftDocs/sql-docs/assets/26484126/b2e21434-0df8-4319-83e3-8f20bd332c02)

**Comment by WilliamDAssafMSFT** [comment]
Thanks @sqlworldwide. Will discuss with the PG and update. I have created an internal work item to track this.

**Comment by WilliamDAssafMSFT** [comment]
Thanks again @sqlworldwide. The description of "Yes: Percentile Adjusting" is "MFG is being applied using the percentile grant algorithm, which looks at more history than only the most recent execution."

A doc update is in flight.

**Comment by Bryant4044** [comment]
@sqlworldwide is there any progress on this? I am running into the error regularly.
