### ISSUE TITLE
Event Name MakeManagedDatabaseInaccessible incorrect

### ISSUE THREAD

**Issue by chrisnelmes** [MicrosoftDocs/sql-docs#9004]
In this documentation it is stated the event name for databases in SQL Managed Incidents should be MakeManagedDatabaseInaccessible

However the event is MakeManagedDbInaccessible (DB not Database)

Please find redacted event log for evidence

{
    "channels": "Operation",
    "correlationId": "REDACTED",
    "description": "",
    "eventDataId": "REDACTED",
    "eventName": {
        "value": "",
        "localizedValue": ""
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "REDACTED",
    "id": "REDACTED",
    "level": "Informational",
    "operationId": "",
    "operationName": {
        "value": "Microsoft.Sql/managedServers/databases/write",
        "localizedValue": "Microsoft.Sql/managedServers/databases/write"
    },
    "resourceGroupName": "REDACTED",
    "resourceProviderName": {
        "value": "MICROSOFT.SQL",
        "localizedValue": "Microsoft SQL"
    },
    "resourceType": {
        "value": "MICROSOFT.SQL/managedinstances/databases",
        "localizedValue": "MICROSOFT.SQL/managedinstances/databases"
    },
    "resourceId": "/REDACTED",
    "status": {
        "value": "Succeeded",
        "localizedValue": "Succeeded"
    },
    "subStatus": {
        "value": "",
        "localizedValue": ""
    },
    "submissionTimestamp": "REDACTED",
    "subscriptionId": "REDACTED",
    "tenantId": "",
    "properties": {
        "originalEventTimestamp": "REDACTED",
        "CorrelationId": "REDACTED",
        "EventId": "REDACTED",
        "EventName": "MakeManagedDbInaccessible",
        "OperationName": "Microsoft.Sql/managedServers/databases/write",
        "Status": "Succeeded",
        "Description_scrubbed": "MakeManagedDbInaccessible: Database REDACTED on managed server REDACTED is inaccessible and requires user to re-establish access to Azure Key Vault Key. https://go.microsoft.com/fwlink/?linkid=2095036",
        "Caller": "Unavailable",
        "CallerCredentialType": "NotSpecified",
        "EventChannel": "OperationLogStore",
        "IpAddress": "",
        "EventSource": "SQL Databases Event Supplier",
        "EventProperties": "REDACTED"
    },
    "relatedEvents": []
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83b6d066-9a0d-ebdb-7432-fb4ae7a82794
* Version Independent ID: 645e4ba4-7898-c2ec-bbb4-c39aecb7e21f
* Content: [Common errors with customer-managed keys in Azure Key Vault - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/troubleshoot-tde?view=azure-sqldw-latest)
* Content Source: [docs/relational-databases/security/encryption/troubleshoot-tde.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/troubleshoot-tde.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
I have updated the documentation and it should be live by tomorrow.
