### ISSUE TITLE
SQL Server Import and Export Wizard not showing database

### ISSUE THREAD

**Issue by genifycom** [MicrosoftDocs/sql-docs#9017]
On the final page of the SQL Server Import and Export Wizard (i.e. the Complete the Wizard page), the source location (server name only), Source Provider and Destination Location (server name only) and Destination Provider are shown.

However, on that page there is no mention of the source database name and destination database name.

```
Click Finish to perform the following actions: 

Source Location : prod.myhost1.com
Source Provider : SQLNCLI11
Destination Location : reporting.myhost2.com
Destination Provider : SQLNCLI11

⦁	Copy rows from [Query] to [dbo].[inventory]
The new rows will be appended to the existing table.

⦁	The package will not be saved. 
⦁	The package will be run immediately. 
```

This means that on the final step, we cannot determine that all of the selected parameters are correct.

Please append the database names to either the top section or the copy section e.g. Copy rows from [database1].[Query] to [database2].[dbo].[inventory]

Thanks

**Comment by rwestMSFT** [comment]
Hi @genifycom, this is a product request, and falls outside of the scope of Database Docs.

Please use the following link: [Have suggestions for improving SQL Server?](https://feedback.azure.com/forums/908035-sql-server).
