### ISSUE TITLE
SQL Server Import and Export Wizard showing wrong data type

### ISSUE THREAD

**Issue by genifycom** [MicrosoftDocs/sql-docs#9018]
I have a source table with a field called created_date of type datetime.

On the Column mappings page of the wizard it correctly shows as datetime.

On the next page "Review Data Type Mapping", it shows this same column as datetime2 and indicates that a conversion to datetime is required (because the destination field is datetime).

The source in this case is a query, but the query only uses select created_date (i.e. there is no conversion involved).

Why is the source field showing as datetime2 on the review page?

**Comment by rwestMSFT** [comment]
@genifycom I have asked a PM to take a look at this question, but it falls outside of the scope of Database Docs. I suspect it's going to be a product feature request.

**Comment by erinstellato-ms** [comment]
Hi @genifycom - can you please share the version of SQL that you're using, and the SSMS build?  Thanks.

**Comment by rwestMSFT** [comment]
@genifycom We haven't heard from you for some time, so I am closing this issue. If you decide to share the information we requested, please feel free to do so below.
