### ISSUE TITLE
Great stuff

### ISSUE THREAD

**Issue by Darmo22** [MicrosoftDocs/sql-docs#9022]
Great pathway to gain tuning skils
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6cda79e-e9d8-631f-9ce6-5fb8fda8bee4
* Version Independent ID: 9343baf7-af9f-00f2-9b4b-7437037f39ee
* Content: [Monitor and Tune for Performance - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/performance/monitor-and-tune-for-performance?view=sql-server-ver16)
* Content Source: [docs/relational-databases/performance/monitor-and-tune-for-performance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/monitor-and-tune-for-performance.md)
* Service: **sql**
* Sub-service: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks for the feedback, @Darmo22!
