### ISSUE TITLE
Naming convention for IQP features

### ISSUE THREAD

**Issue by sqlworldwide** [MicrosoftDocs/sql-docs#9023]
On this page, most IQP features are preceded by "Intelligent Database:" whereas some are not. Why?

Example with "Intelligent Database:"

- Intelligent Database: approximate count distinct
- Intelligent Database: approximate percentile

Example without "Intelligent Database:"

- Batch mode adaptive joins
- Batch mode memory grant feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da229e25-1614-845e-244e-c679dcbc0594
* Version Independent ID: da229e25-1614-845e-244e-c679dcbc0594
* Content: [Editions and supported features of SQL Server 2022 - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2022?view=sql-server-ver16)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-2022.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-2022.md)
* Service: **sql**
* Sub-service: **release-landing**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
Hi @sqlworldwide, if I were to guess, it's a legacy thing. Some features were introduced in earlier products before given the umbrella term, and aren't referred to as such in those older products.

**Comment by sqlworldwide** [comment]
> Hi @sqlworldwide, if I were to guess, it's a legacy thing. Some features were introduced in earlier products before given the umbrella term, and aren't referred to as such in those older products.

I know the two in the example are SQL 2017, but I see other 2017 featured are preceded by `Intelligent Database.` My suggestion will be to add this to all features of IQP to avoid confusion. I can submit a PR if that helps.

**Comment by WilliamAntonRohm** [comment]
@sqlworldwide -- thank you for your follow-up.  You are welcome to create a PR.

**Comment by sqlworldwide** [comment]
> @sqlworldwide -- thank you for your follow-up. You are welcome to create a PR.

done. Sumbitted a PR.

**Comment by rwestMSFT** [comment]
#please-close
