### ISSUE TITLE
Adding the winget option to install Azure Data Studio to description

### ISSUE THREAD

**Issue by SmartInteractiveGroup** [MicrosoftDocs/sql-docs#9024]
please add winget option to install Azure Data Studio

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install Azure Data Studio - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver16&culture=pl-pl&country=pl&tabs=redhat-install%2Credhat-uninstall)
* Content Source: [docs/azure-data-studio/download-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download-azure-data-studio.md)
* Service: **azure-data-studio**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by WilliamAntonRohm** [comment]
@SmartInteractiveGroup -- Marcin, thank you for your feedback.  Are you referring to adding an existing winget option into the documentation, or to adding a new winget feature to the product?

**Comment by erinstellato-ms** [comment]
@SmartInteractiveGroup Azure Data Studio is available via winget.

![image](https://github.com/MicrosoftDocs/sql-docs/assets/98599126/8b66f838-c672-4ddc-92ac-c344dc821f34)

**Comment by SmartInteractiveGroup** [comment]
@WilliamAntonRohm deeply sorry for the delay in my response. I was referring to adding an existing winget option into the documentation, as the winget option is just great and everybody should know it can be used! 

dw @erinstellato-ms

**Comment by erinstellato-ms** [comment]
@dlevy-msft Something to add to the download page for ADS?

**Comment by WilliamAntonRohm** [comment]
#reassign:dlevy-msft

**Comment by SmartInteractiveGroup** [comment]
This option was added. Work perfect! Congrats to the whole team!! I will promote that on my Linkedin. 

You can close this issue. 

![image](https://github.com/MicrosoftDocs/sql-docs/assets/16972436/e8e77b96-d86c-41ea-bed3-5a6394282e89)

**Comment by SmartInteractiveGroup** [comment]
This option was added. Work perfect! Congrats to the whole team!! I will promote that on my Linkedin. 

You can close this issue. 

![image](https://github.com/MicrosoftDocs/sql-docs/assets/16972436/e8e77b96-d86c-41ea-bed3-5a6394282e89)
