### ISSUE TITLE
Does the database limit per instance on SQL 2022 include the new hidden system databases?

### ISSUE THREAD

**Issue by MelK-HH** [MicrosoftDocs/sql-docs#9029]
I was looking for the maximum database_id a database on a SQL 2022 on Linux may have. This article states a limit of 32,767 databases per instance for SQL Server 2022 in Windows.

However, in the  DMV sys.dm_io_virtual_file_stats I found two system databases having an id less than 32,767:
- 32761: model_msdb
- 32762: model_replicatedmaster

If I were to create 32,767 databases on this instance including the regular system databases master, msdb, model, and tempdb, I actually would have a total of 32,769 databases including the two hidden ones. This may lead to errors on the DMV "sys.dm_io_virtual_file_stats" which returns a smallint field for database_id.

Can you, please, confirm that this limit of 32,767 database per instance is still valid for SQL 2022 and if yes, if this includes the two new hidden system databases?
Also, it would be nice to have this article available for SQL Server on Linux as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 780e3e16-ac52-1343-fe0a-a706c71ddb92
* Version Independent ID: 6f09b278-faa0-6f0d-1013-c1ae62ca006c
* Content: [Maximum capacity specifications for SQL Server - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server?view=sql-server-ver16&viewFallbackFrom=sql-server-linux-2017)
* Content Source: [docs/sql-server/maximum-capacity-specifications-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/maximum-capacity-specifications-for-sql-server.md)
* Service: **sql**
* Sub-service: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rwestMSFT** [comment]
The 32,767 is a hard limit (I know because I've hit that limit in a test environment). Any databases, hidden or not, on both Windows and Linux, will count.

I hope that answers your question.

#please-close
