### ISSUE TITLE
why we use Open 

### ISSUE THREAD

**Issue by Rajkiran-125** [MicrosoftDocs/sql-docs#9030]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e930ec1b-7042-77a9-afd4-1ff11edf2a00
* Version Independent ID: a54607a9-f4c0-922f-d2ec-52597188e245
* Content: [Parse and Transform JSON Data with OPENJSON - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/json/convert-json-data-to-rows-and-columns-with-openjson-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/json/convert-json-data-to-rows-and-columns-with-openjson-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/convert-json-data-to-rows-and-columns-with-openjson-sql-server.md)
* Service: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by Rajkiran-125** [comment]
Why we use OpenJson

**Comment by rwestMSFT** [comment]
@Rajkiran-125 It's not clear what you're asking. Can you please provide more context so that we can answer your question?

**Comment by rwestMSFT** [comment]
I'm closing this issue, because we haven't heard back from you. If you wish to provide us more information, please respond in the comments below.
