### ISSUE TITLE
Bug in sample code

### ISSUE THREAD

**Issue by candritzky** [MicrosoftDocs/sql-docs#9032]
There is a bug in the following part of the sample code:

```
string someData = "EKG data.";
Encoding unicode = Encoding.GetEncoding(0);

sqlFileStream.Write(unicode.GetBytes(someData.ToCharArray()),
        0,
        someData.Length);

```

Passing `someData.Length` looks wrong. This is the length of the string (in characters), but after encoding, the length of the encoded byte array might be different (usually a couple of bytes longer). The length of the array returned by `Encoding.GetBytes()` should be used instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a91e62db-afa7-c1d5-3d70-b409d5e52b50
* Version Independent ID: aaf413ee-2550-ab7a-83e1-155f16fb0602
* Content: [Access FILESTREAM Data with OpenSqlFilestream - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/blob/access-filestream-data-with-opensqlfilestream?view=sql-server-ver15)
* Content Source: [docs/relational-databases/blob/access-filestream-data-with-opensqlfilestream.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/blob/access-filestream-data-with-opensqlfilestream.md)
* Service: **sql**
* Sub-service: **filestream**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@candritzky -- Chris, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- Mike, please review this update in [private PR 27415](https://github.com/MicrosoftDocs/sql-docs-pr/pull/27415).
