### ISSUE TITLE
sql agent service not started

### ISSUE THREAD

**Issue by cletocs** [MicrosoftDocs/sql-docs#9047]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 652c3fee-c6a9-f163-a281-6e2ae73da6f5
* Version Independent ID: 8b88a92e-0d8d-d2b2-2a37-e96565a71045
* Content: [Quickstart: Deploy a SQL Server container cluster on Azure - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-sql-server-containers-azure?view=sql-server-ver16&tabs=kubectl)
* Content Source: [docs/linux/quickstart-sql-server-containers-azure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-sql-server-containers-azure.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@cletocs Please provide more information about the issue you're experiencing, and what steps you took so we can recreate it.

**Comment by rwestMSFT** [comment]
@cletocs As we have not heard from you, I am closing this issue. If you decide to provide some information, please do so in the comments below.
