### ISSUE TITLE
Footnote 4 - missing a NOT???

### ISSUE THREAD

**Issue by dannysantee** [MicrosoftDocs/sql-docs#9048]
Should this include NOT in this footnote???
4 Standard Edition and SQL Server + CAL-based licensing can restrict how many processors SQL Server Standard can use, but SQL Server Standard is **not** NUMA aware.

See related question asked but not fully answered:
https://dba.stackexchange.com/questions/318017/whether-sql-standard-edition-has-numa-support

No such footnote exists for SQL 2019 via:
https://learn.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2019?view=sql-server-2017#RDBMSSP
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 468d4b7b-8880-a867-de2c-75e6099474f9
* Version Independent ID: e57139bf-0bd8-eb5c-4896-71488873c1f0
* Content: [Editions and supported features - SQL Server 2016](https://learn.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2016?view=sql-server-2017#RDBMSSP)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-2016.md)
* Service: **sql**
* Sub-service: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rwestMSFT** [comment]
I've reviewed the article. The grammar is correct. SQL Server Standard edition limits the number of CPU cores, but it is still NUMA aware. However, it will not apply an equal distribution across multiple cores if the hardware contains more than the limit Standard edition supports.
