### ISSUE TITLE
The information on he page is wrong

### ISSUE THREAD

**Issue by sjs1959** [MicrosoftDocs/sql-docs#9054]
I have visited this page to get help on how to set up credentials on my Azure Database.

This page says click on the Credentials node in the Security node.

I did this and on my system ...
**Microsoft SQL Azure (RTM) - 12.0.2000.8   Jun  2 2023 14:53:48   Copyright (C) 2022 Microsoft Corporation** 

There is no such Credentials node.

So this help page rates a 0/10 from me.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e2a381d-1520-b4b4-18c3-b23f638a0605
* Version Independent ID: 8bc3d24f-79ee-07bd-7177-4b4a7bc2c6c5
* Content: [Create a Credential - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/create-a-credential?view=azuresqldb-current)
* Content Source: [docs/relational-databases/security/authentication-access/create-a-credential.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/create-a-credential.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by rwestMSFT** [comment]
Thanks @erinstellato-ms!

Hopefully this answers your question, @sjs1959. I'm closing this issue as resolved. If you have any further thoughts, please feel free to comment below.
