### ISSUE TITLE
Incorrect syntax for enable/disable Memory Grant Feedback Percentile

### ISSUE THREAD

**Issue by transmokopter** [MicrosoftDocs/sql-docs#9061]
[Enter feedback here]

Documentation says to run ALTER DATABASE SCOPED CONFIGURATION SET MEMORY_GRANT_FEEDBACK_PERCENTILE = ON|OFF
This yields an "INCORRECT SYNTAX NEAR 'MEMORY_GRANT_FEEDBACK_PERCENTILE' error.
Looking into sys.database_scoped_configurations I see it's named MEMORY_GRANT_FEEDBACK_PERCENTILE_GRANT.
This is Sql Server 2022 CU4 container from mcr.microsoft.com/mssql/server

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b770595-1ea3-2dc5-cfd9-85719e527434
* Version Independent ID: 5b770595-1ea3-2dc5-cfd9-85719e527434
* Content: [Query processing feedback features - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/performance/intelligent-query-processing-feedback?view=sql-server-ver16#degree-of-parallelism-dop-feedback)
* Content Source: [docs/relational-databases/performance/intelligent-query-processing-feedback.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/intelligent-query-processing-feedback.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Nice catch @transmokopter! A doc update is in flight to fix this typo. Thanks very much for taking the time to provide this feedback!

**Comment by transmokopter** [comment]
@WilliamDAssafMSFT the same applies to ALTER DATABASE SCOPED CONFIGURATION page here: https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql?view=sql-server-ver16
