### ISSUE TITLE
Incorrect syntax for enable/disable Memory Grant Feedback Percentile

### ISSUE THREAD

**Issue by transmokopter** [MicrosoftDocs/sql-docs#9062]
Referring to #9061 - the same typo made it to the ALTER DATABASE SCOPED CONFIGURATION page. [](https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql?view=sql-server-ver16)

MEMORY_GRANT_FEEDBACK_PERCENTILE should be MEMORY_GRANT_FEEDBACK_PERCENTILE_GRANT

**Comment by transmokopter** [comment]
[https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql?view=sql-server-ver16](https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql?view=sql-server-ver16)

**Comment by rwestMSFT** [comment]
Thanks, Magnus. On it.

**Comment by rwestMSFT** [comment]
@WilliamDAssafMSFT was so good, he already fixed it in the previous PR, so it'll reflect when we publish. Closing this as completed.
