### ISSUE TITLE
US only S3 Providers listed as examples

### ISSUE THREAD

**Issue by 1Dimitri** [MicrosoftDocs/sql-docs#9068]
[Enter feedback here]

In the list of S3 compatible storage  providers, article is US oriented and does not reflect the need for companies to use storage in their region for latency or regulatory purposes

You may want to add for example
| scaleway |  https://www.scaleway.com/en/object-storage/ |
| clevercloud | https://www.clever-cloud.com/doc/deploy/addon/cellar/ |

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7fa91b14-0a07-8fd0-a9b0-8deb950354c0
* Version Independent ID: 7fa91b14-0a07-8fd0-a9b0-8deb950354c0
* Content: [Backup & restore with S3-compatible object storage - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-and-restore-with-s3-compatible-object-storage?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/sql-server-backup-and-restore-with-s3-compatible-object-storage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/sql-server-backup-and-restore-with-s3-compatible-object-storage.md)
* Service: **sql**
* Sub-service: **backup-restore**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@1Dimitri -- Dimitri, thank you for your feedback.

@WilliamDAssafMSFT -- William, please look into this issue.
