### ISSUE TITLE
Test the queries on this page

### ISSUE THREAD

**Issue by lucidqdreams** [MicrosoftDocs/sql-docs#9079]
Some feedback regarding documentation here. 

[View SQL Server databases - SQL Server | Microsoft Learn](https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/view-databases?view=sql-server-ver16)

I wanted to take this query to the Graph
 
![image](https://github.com/MicrosoftDocs/sql-docs/assets/6086602/83dc9bf8-6e34-485a-9a0d-4bb786e6f0e9)

Paste, run.

![image](https://github.com/MicrosoftDocs/sql-docs/assets/6086602/4f5b9907-e8b6-4e75-af90-7baac97c2fab)

Comments
resources is technically lowercase by autocorrect, add some spaces after the pipes
 
![image](https://github.com/MicrosoftDocs/sql-docs/assets/6086602/4dc0daad-578d-4ac7-b97c-cca32699dafc)

![image](https://github.com/MicrosoftDocs/sql-docs/assets/6086602/5c03e6db-c7de-4b5c-8087-dffe3aa2f056)

 Hmm “lincensetype” is an issue.

 
![image](https://github.com/MicrosoftDocs/sql-docs/assets/6086602/c379e852-9dc1-4aa0-9cbb-576758f14ea5)

But lincentype work
![image](https://github.com/MicrosoftDocs/sql-docs/assets/6086602/1387ff2c-d4f1-4245-97fa-ef02b7acd75e)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38bd60d9-ac77-b45b-8d21-68519ba20328
* Version Independent ID: 38bd60d9-ac77-b45b-8d21-68519ba20328
* Content: [View SQL Server databases - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/view-databases?view=sql-server-ver16)
* Content Source: [docs/sql-server/azure-arc/view-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/azure-arc/view-databases.md)
* Service: **sql**
* GitHub Login: @ntakru
* Microsoft Alias: **nikitatakru**

**Comment by WilliamAntonRohm** [comment]
@lucidqdreams -- Lucid, thank you for your well-researched feedback.  I am updating the article.

**Comment by rwestMSFT** [comment]
@WilliamAntonRohm I'll take this one, if you don't mind.

**Comment by ntakru** [comment]
This is great feedback. Let's update the docs article to reflect the changes in terms of the lower case for resources and license type spelling so that the query can be copy and pasted directly in Azure Resource Graph from there.

**Comment by rwestMSFT** [comment]
@lucidqdreams @ntakru @WilliamAntonRohm This issue will automatically close when the internal PR is merged, and the updated article will be published in the next day or so.
