### ISSUE TITLE
Typo mistake

### ISSUE THREAD

**Issue by gb5757870** [MicrosoftDocs/sql-docs#9080]
The word "delete" is misspelt in the section called "Disconnect and unregister individual SQL Server instances from Azure Arc"

See the last line "Confirm that you want to _detele_ the resource(s) when prompted"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4646c89b-b0b8-0f72-4274-4b73730d58d7
* Version Independent ID: 4646c89b-b0b8-0f72-4274-4b73730d58d7
* Content: [Disconnect your SQL Server from Azure Arc - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/delete-from-azure-arc?view=sql-server-ver16&tabs=azure)
* Content Source: [docs/sql-server/azure-arc/delete-from-azure-arc.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/azure-arc/delete-from-azure-arc.md)
* Service: **sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rwestMSFT** [comment]
Thanks, @gb5757870, this will be fixed in the next day.
