### ISSUE TITLE
Restart requirements

### ISSUE THREAD

**Issue by JoeBrunsTR** [MicrosoftDocs/sql-docs#9083]
Please try to indicate if any server or windows service restarts are required to reload the drivers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a36a1d7f-a410-b597-0eb7-98212934fb0e
* Version Independent ID: e706f2bd-e051-fcff-7c3d-2ef3d9f80e87
* Content: [Download ODBC Driver for SQL Server - ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16#version-17)
* Content Source: [docs/connect/odbc/download-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/download-odbc-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
Noted.

As with any shared library installation, restarts may be required if files are locked by processes not owned by the installer. For files owned by the installer, it will prompt the user to close programs/stop processes that are locking files to avoid a reboot. But only during a GUI install. Silent install behavior is controlled by standard msiexec command line options.

The ODBC driver also ships with a module from the VCRuntime that itself might require a reboot if its shared files are in use. Unfortunately, we can't always predict when that module will signal that a reboot is required.

Regards,
David

#please-close
