### ISSUE TITLE
Several Connection Attributes data type incorrect for 64-bit

### ISSUE THREAD

**Issue by rbancroft** [MicrosoftDocs/sql-docs#9084]
Hello,

SQL_ATTR_CONNECTION_TIMEOUT, SQL_ATTR_LOGIN_TIMEOUT and SQL_ATTR_PACKET_SIZE  are described as SQLUINTEGER values however it seems as though they behave as SQLULEN values.

I'm not sure if this is also a software bug, however passing an SQLUINTEGER to this API for these 3 attributes leads to a buffer overrun in 64-bit.

e.g.
SQLUINTEGER loginTimeout{0};
SQLINTEGER length{0};
// 8 bytes get written to loginTimeout on 64-bit, but the size is only 4 bytes.
SQLGetConnectAttr(hdbc, SQL_ATTR_LOGIN_TIMEOUT, &loginTimeout, sizeof(loginTimeout), &length);
// stack buffer overrun

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da688271-2074-259b-3249-4b915da2712c
* Version Independent ID: f748db20-7142-ca0b-f873-6b5932e20917
* Content: [SQLSetConnectAttr Function - ODBC API Reference](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetconnectattr-function?view=sql-server-ver16)
* Content Source: [docs/odbc/reference/syntax/sqlsetconnectattr-function.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/syntax/sqlsetconnectattr-function.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@rbancroft -- Ryan, thank you for your thorough feedback.  If you feel this is a product issue, please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

@David-Engel -- David, please look into this issue.

**Comment by rbancroft** [comment]
I apologize, this is probably not an issue after all. I was using SQLGetConnectAttr incorrectly. The docs say to always use an SQLULEN buffer even for 16 or 32-bit values. In this case it happens to write out 64 bits for a 32-bit value, however if I attempt to set a value > 32-bits for these values, the upper 32-bits is ignored.

I think you can close/ignore this report. My apologies.

**Comment by WilliamAntonRohm** [comment]
@rbancroft -- Ryan, thank you for your follow-up.  No apology needed; happy to help!
