### ISSUE TITLE
Version numbers don't match ODBC Data Source Administrator versions

### ISSUE THREAD

**Issue by 69baud** [MicrosoftDocs/sql-docs#9091]
[Enter feedback here]
How are we supposed to know what version we have installed?  The version numbers on here don't correspond to the version numbers shown in the ODBC Data Source Administrator (32-bit or 64-bit) applet (odbcad32.exe)

For example, in ODBC DSA, I see

2017.172.00.01
2018.182.01.01

No match with 17.10.4.1 or 18.2.2.1

Why can't you show the correct version numbers as the user sees them in odbcad32.exe?  Or is there somewhere else to see them?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a36a1d7f-a410-b597-0eb7-98212934fb0e
* Version Independent ID: e706f2bd-e051-fcff-7c3d-2ef3d9f80e87
* Content: [Download ODBC Driver for SQL Server - ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16#version-17)
* Content Source: [docs/connect/odbc/download-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/download-odbc-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
@69baud 

I agree it's probably confusing. You can see the Product Version in Add or remove programs (Microsoft ODBC Driver XX for SQL Server). The ODBC Data Source Administrator is showing File Version.

But you can easily translate File Version to Product Version. Ignoring the major version field, the minor version field is the combination of major and minor. So:

2017.172.00.01 == [17.2].00.01 (17.2.0.1)
2018.182.01.01 == [18.2].01.01 (18.2.1.1)

Regards,
David

**Comment by WilliamAntonRohm** [comment]
@69baud -- thank you for your questions.

@David-Engel -- thank you for clarifying.
