### ISSUE TITLE
"Table Valued Parameters" function bindings does not work as documented.

### ISSUE THREAD

**Issue by RayWhitmer** [MicrosoftDocs/sql-docs#9093]
The code given at
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/native-client-odbc-how-to/use-table-valued-parameters-odbc.md

has a function called demo_variable_TVP_binding.

On line 795:
SQLPutData(hstmt, &Qty, sizeof(SQLINTEGER));

This does not capture the return value, but the next line apparently wants to test the return value.

Thus guarantees that the function will always fail without accomplishing its intended function because r is guaranteed to be SQL_NEED_DATA by the surrounding while loop.

If we fix this line by adding "r = " to be beginning of this line, the function still doesn't work, because despite the calls to tell the driver no more rows ( r = SQLPutData(hstmt, SQLPOINTER(1), 0); on line 782, the SQLParamData function on line 804 keeps returning SQL_NEED_DATA and asking for another row with the code as written here, which seems like it has not been tested. I can't make the function work.

This is the same result I got in my own coding attempts from the reference, it keeps asking for more rows despite there being no more rows. I really need an example program that works with specification of minimum driver versions that make it work (if that might be the second problem).

I have tried it with the latest drivers even though these were created long after this document was written.

There has been no success getting anyone at Microsoft support to even look at the issue or even identifying the right support team that would look at it. They take my money and give me the URL of the incorrect documentation. Everyone is content to keep publishing false documentation. But someone should be responsible for this documentation being wrong and how to make the functionality work.

Or give me a document certifying the obvious to my managers, that **Microsoft is an unsupported OS and database** and give me a refund of the support incident that you encouraged me to open.

**Comment by MikeRayMSFT** [comment]
@RayWhitmer - thank you for resubmitting this issue. I'm tracking down appropriate and authoritative responses.

CC: @rwestMSFT , @rothja

**Comment by v-chojas** [comment]
@RayWhitmer  please look at the docs again; we believe the page you refer to has been corrected.

**Comment by RayWhitmer** [comment]
The correction does seem to solve the problem of the infinite loop (I would characterize this as the most significant issue with an erroneous API call, which resembles a nearly-magic incantation gone wrong).

You should also fix the problem on line 795 that I mentioned first in the report (add "r =") or the example fails out without even reaching the previous infinite loop now fixed to terminate correctly, because r continues to hold SQL_NEED_DATA which got it to this point in the logic, which causes it to exit as an error because it was not updated with the (successful in this case) result of the call.

**Comment by RayWhitmer** [comment]
"Closed again" but not complete without the fix on line 795.

**Comment by RayWhitmer** [comment]
I failed to say, v-chojas, thanks for the fix. It completely unblocks me.

Fixing line 795 would give your documentation a code snippet that works, which seems like a win for you.

**Comment by WilliamAntonRohm** [comment]
@RayWhitmer -- Ray, thank you for your follow-up.  I am updating line 795.

**Comment by WilliamAntonRohm** [comment]
@RayWhitmer -- Ray, this update is already in the live article:  https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/native-client-odbc-how-to/use-table-valued-parameters-odbc.md

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
