### ISSUE TITLE
sys.fn_MSxe_read_event_stream is missing parameter information

### ISSUE THREAD

**Issue by erikdarlingdata** [MicrosoftDocs/sql-docs#9098]
The documentation currently only has the session name input listed, but Microsoft uses the following query to read from files.

It would be nice to know what different source options are, and how they can be used.

```
EXEC sp_executesql N'
SELECT
    type,
    data
FROM sys.fn_MSxe_read_event_stream (@source, @sourceopt)',
N'@source nvarchar(256),@sourceopt int',
@source=N'system_health_*.xel',@sourceopt=1
```

**Comment by rwestMSFT** [comment]
Hi Erik. Thanks for your feedback.

We won't be able to provide further information. Quoting the sentence in the article, with my emphasis added:

> Extended Events provides a table valued function (TVF) for **internal use** by the Extended Events user interface (UI). **The table does not provide customer usable data.**

**Comment by erikdarlingdata** [comment]
😭😭😭
