### ISSUE TITLE
Incomplete Sentence

### ISSUE THREAD

**Issue by RadicalErin** [MicrosoftDocs/sql-docs#9100]
[Enter feedback here]
```
When you need to enable system-versioning using an existing table, such as when you wish to migrate a custom temporal solution to built-in support. For example, you may have a set of tables where versioning is implemented with triggers.
```

Incomplete phrase. When <x>, such as <y>, then ... what? It's not clear what the rest of this sentence was intended to say. I do not know enough on the subject, myself, to suggest what might go there, either.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 349eae51-5e73-47db-ee0d-8cae824f5c45
* Version Independent ID: 98d04967-6eb4-4d4d-e4a4-8e77a0f1fba0
* Content: [Create a system-versioned temporal table - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/creating-a-system-versioned-temporal-table?view=sql-server-ver16)
* Content Source: [docs/relational-databases/tables/creating-a-system-versioned-temporal-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/creating-a-system-versioned-temporal-table.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@RadicalErin Agreed, this is not grammatically correct. The context (which I will fix in an upcoming update to the article) should read as follows (bold contains the proposed new text):

> ### Alter non-temporal table to be a system-versioned temporal table

> **You can enable system-versioning on an existing non-temporal table**, such as when you wish to migrate a custom temporal solution to built-in support. For example, you may have a set of tables where versioning is implemented with triggers.

Does this make sense?

**Comment by RadicalErin** [comment]
Ah. Yeah, if it was never meant to have a finishing phrase, that sounds like the right fix.

**Comment by rwestMSFT** [comment]
Great, and thank you for your close reading. The updated article will be published in the next day or so.
