### ISSUE TITLE
Installer download link is missing for SSMS version 18.x

### ISSUE THREAD

**Issue by sb3strand** [MicrosoftDocs/sql-docs#9116]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver16#18121)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by rwestMSFT** [comment]
Hi @sb3strand, the 18.x downloads are available on that article. While I suspect you're looking directly for a link that says "Download", all available language downloads are listed.

https://learn.microsoft.com/sql/ssms/release-notes-ssms#18121

#please-close
