### ISSUE TITLE
repair Sql server master database

### ISSUE THREAD

**Issue by XE0123** [MicrosoftDocs/sql-docs#9117]
How do you repair a Master.mdb if SSMS cannnot connect to the database, probably because of an error in the master.mdf file.
The instructions on the webpage 'https://learn.microsoft.com/en-us/sql/relational-databases/databases/rebuild-system-databases?view=sql-server-ver16' are based that there IS an connection with the database so 'SELECT * FROM sys.configurations; ' does not work and the page does not give an alternative solution.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4305ba00-bb98-1076-118f-9133acc496c6
* Version Independent ID: 6ea8ec5a-7f33-45b5-68fa-ccc18dcc4d81
* Content: [master Database - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/databases/master-database?view=sql-server-ver16)
* Content Source: [docs/relational-databases/databases/master-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/master-database.md)
* Service: **sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hi @XE0123
Sorry to hear you're in the situation of having a corrupted master database. This is not an easy solution. Consider this blog post: https://techcommunity.microsoft.com/t5/sql-server-blog/the-easiest-way-to-rebuild-the-master-database/ba-p/383742
It involves creating another SQL Server with the same version and drive letters, restore the master database there, then replace the .mdf and .ldf files from the restored master database over the corrupted master database.

If you have any further questions, this is not the best forum for technical support. I recommend [Microsoft Q&A (SQL Server)](https://docs.microsoft.com/answers/products/sql-server), [SQL Server Feedback](https://feedback.azure.com/forums/908035-sql-server), Microsoft Support, or your support partners. Regardless, thanks again for this feedback, your suggestions help improve our documentation.
