### ISSUE TITLE
https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/manage-license-type?view=sql-server-ver16&tabs=azure

### ISSUE THREAD

**Issue by sommarskog** [MicrosoftDocs/sql-docs#9130]
This passage:

Azure Active Directory authentication. You can manage access to your SQL Server databases using Azure Active Directory credentials. This feature requires that your instance is upgraded to SQL Server 2022. For more information, see [Azure Active Directory authentication for SQL Server 2022](https://cloudblogs.microsoft.com/sqlserver/2022/07/28/azure-active-directory-authentication-for-sql-server-2022/).

Contradicts what is said earlier on the page that Azure AD Authentication is in fact available with LicenseOnly, which I also believe to be the correct state of affairs. I did not want to edit the page and delete the bullet point, since you may still want to have the text about SQL 2022 somewhere in the article.

**Comment by WilliamAntonRohm** [comment]
@sommarskog -- thank you for your clear feedback.

@anosov1960 -- please look into this issue.

**Comment by shilpimitra** [comment]
@MikeRayMSFT So the document you cited seems to be outdated. Here is the correct feature availability matrix wrt license type. https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/overview?view=sql-server-ver16#feature-availability-depending-on-license-type AAD is available for all license types of Arc enabled SQL Server. 
Also AAD feature has a dependency on SQL Server version as well and is only available for SQL 2022.  ref: https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/overview?view=sql-server-ver16#feature-availability-by-version

**Comment by sommarskog** [comment]
It appears that the page has been updated since I filed this issue. I cannot find the text that I cite above. So let's close this.

**Comment by sommarskog** [comment]
Closing this in
