### ISSUE TITLE
Clarify use of "the server"

### ISSUE THREAD

**Issue by cnc-bdibene** [MicrosoftDocs/sql-docs#9131]
There are a couple references to "the server"
e.g. <FQDN> is the fully qualified domain name of the server.

Please clarify if you're referring to the source/client/web server, the destination/DB server, the Active Directory server, or other.

**Comment by WilliamAntonRohm** [comment]
@cnc-bdibene -- Brian, thank you for your feedback.  Which learn.microsoft.com article are you following?
