### ISSUE TITLE
go-sqlcmd and install impacts

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#9133]
The documentation appears to assume that no prior installations of [sqlcmd] are present.  I would like to see a section added to the documentation at [https://learn.microsoft.com/en-us/sql/tools/sqlcmd/go-sqlcmd-utility?view=sql-server-ver16&tabs=windows] to include reference to how the install deals with prior installations of [sqlcmd] since the command to install doesn't have a different name. 
- Do I need to remove prior installations of [sqlcmd]?
- Will this overlay the existing installations of [sqlcmd]?
- Can earlier editions co-exist side-by-side?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 094da575-8e25-b22b-9db0-4355c446109a
* Version Independent ID: 094da575-8e25-b22b-9db0-4355c446109a
* Content: [go-sqlcmd utility - SQL Server](https://learn.microsoft.com/en-us/sql/tools/sqlcmd/go-sqlcmd-utility?view=sql-server-ver16&tabs=windows)
* Content Source: [docs/tools/sqlcmd/go-sqlcmd-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlcmd/go-sqlcmd-utility.md)
* Service: **sql**
* Sub-service: **tools-other**
* GitHub Login: @grrlgeek
* Microsoft Alias: **jeschult**

**Comment by rwestMSFT** [comment]
Thanks for the suggestion, @LindaLF. We will take this feedback into account when we review the documentation for **go-sqlcmd**. Stay tuned!

**Comment by dlevy-msft** [comment]
We have updated the article. The changes should be up in the next day or so.

#please-close
