### ISSUE TITLE
Instant File Initialization & Azure SQL DB

### ISSUE THREAD

**Issue by kenjmartinii** [MicrosoftDocs/sql-docs#9144]
With the release of SQL Server 2022, instant file initialization was enabled for Azure SQL DB as documented on the last row in the 'Performance' table [here](https://learn.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-2022?view=sql-server-ver16#performance).

![image](https://github.com/MicrosoftDocs/sql-docs/assets/49922510/6896d2f2-d8b7-4f7c-af69-4cc669360fff)

The main doc [here](https://learn.microsoft.com/en-us/sql/relational-databases/databases/database-instant-file-initialization?view=sql-server-ver16) for instant file initialization makes no mention of Azure SQL DB and should be updated to reflect that IFI is also now applicable to Azure SQL DB tlog files for autogrowth increments up to 64 MB

**Comment by WilliamAntonRohm** [comment]
@kenjmartinii -- Ken, thank you for your thorough feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @kenjmartinii for taking the time to provide this feedback. We're going to bring clarity to this issue with a Doc update soon.  Thanks for drawing attention to this disparity, your suggestions help improve our documentation. Closing, as this doc update is in flight and tracked by an internal initiative.

**Comment by WilliamDAssafMSFT** [comment]
Thanks again @kenjmartinii, https://learn.microsoft.com/sql/relational-databases/databases/database-instant-file-initialization has been updated to bring more clarity.
