### ISSUE TITLE
Default PW expiration ? or none? 

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/sql-docs#9147]
What is the default PW expiration on Linux? 90 days or none? see also this Q: https://learn.microsoft.com/en-us/answers/questions/1079552/mssql-2019-on-linux-login-expiry-default

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69eacb7b-72f2-9a64-6238-8112f40e8e4f
* Version Independent ID: bc7b778e-c403-894d-883a-862840a1e2b7
* Content: [Security limitations for SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-security-overview?view=sql-server-ver16)
* Content Source: [docs/linux/sql-server-linux-security-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-security-overview.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@TiloGit I chatted with the product group, and they confirmed with me that the 90 day expiration is hard-coded for Linux, if you're not using integrated authentication.

I've responded on that Q&A article, and we'll update the Security Limitations article.

Thanks for your feedback, and helping make Docs even better.
