### ISSUE TITLE
[Feature request] Add support for multiple cascading foreign keys

### ISSUE THREAD

**Issue by MarvinKlein1508** [MicrosoftDocs/sql-docs#9150]
I have two columns in my table which are both the same foreign key of another table.

These are my two tables:
```sql
CREATE TABLE users 
(
	user_id integer IDENTITY(1,1) NOT NULL,
	username varchar(50) NOT NULL,
	PRIMARY KEY(user_id)
);

CREATE TABLE notizen_aktionen 
(
    notiz_aktion_id INTEGER IDENTITY(1,1),
    notiz_id INTEGER NOT NULL,
    aktion_id INTEGER NOT NULL,
    creation_user_id INTEGER DEFAULT NULL,
    description TEXT NOT NULL DEFAULT '',
    status_id INTEGER NOT NULL,
    last_user_id INTEGER DEFAULT NULL,
    PRIMARY KEY(notiz_aktion_id),
    FOREIGN KEY (creation_user_id) 
         REFERENCES users(user_id) ON DELETE SET NULL,
    FOREIGN KEY (last_user_id) 
         REFERENCES users(user_id) ON DELETE SET NULL,
);
```

One value contains the `user_id` of the user who created the record and the other one holds the information who has made the last change to this record.

What I want to achieve now is when the user will be deleted, both of these columns should be set to null.

So I thought of using a foreign key for this. But SQL server won't let me create this table. In MySQL, & Firebird this works just fine. 

It would be great if SQL Server could support this as well so we do not need to write endless triggers for this simple task.

I get this error:

> Introducing FOREIGN KEY constraint '%.*ls' on table '%.*ls' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.

**Comment by rwestMSFT** [comment]
Hi @MarvinKlein1508, please submit your request at this Azure Feedback page: [SQL community](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0).

**Comment by MarvinKlein1508** [comment]
Hi @rwestMSFT 
I was doing it here since the docs said this repository is for requests as well.

But I see the docs have already been updated to the new link :)

Have a nice day.
