### ISSUE TITLE
Release Notes for Report Viewer are outdated 

### ISSUE THREAD

**Issue by WilliamAntonRohm** [MicrosoftDocs/sql-docs#9152]
Regarding [Release Notes for Report Viewer controls for WebForms and WinForms of SSRS](https://docs.microsoft.com/en-us/sql/reporting-services/application-integration/release-notes-ssrs-application-integration?view=sql-server-ver15)

Please update the release information per issue #6932.

**Comment by rwestMSFT** [comment]
This looks like it was resolved.
