### ISSUE TITLE
Out of Date information?

### ISSUE THREAD

**Issue by h27kim** [MicrosoftDocs/sql-docs#9165]
[Enter feedback here]
The information provided here does not seem to be up to date, at least not for the current version of Excel.  There seems to be no option in the current version (Office 365, I guess?) for importing Foxpro files.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a794b1ae-03a3-690e-eb11-8253e07bbc6a
* Version Independent ID: 714fd887-0044-21c5-ba02-6ea4b1a90acd
* Content: [Importing Data into Microsoft Excel from a Visual FoxPro Database - Open Database Connectivity (ODBC)](https://learn.microsoft.com/en-us/sql/odbc/microsoft/importing-data-into-microsoft-excel-from-a-visual-foxpro-database?view=sql-server-ver16)
* Content Source: [docs/odbc/microsoft/importing-data-into-microsoft-excel-from-a-visual-foxpro-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/microsoft/importing-data-into-microsoft-excel-from-a-visual-foxpro-database.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
The only thing I see wrong in this article is the Excel menus have changed in step 2. Microsoft Query is now located under Get Data > From Other Sources > From Microsoft Query. You can also find it by simply typing `Microsoft Query` in the new, central Search bar of Excel:
![image](https://github.com/MicrosoftDocs/sql-docs/assets/26262303/57dfc4b2-c42d-4766-bbc6-755e6c9ea905)

I can update the article to reflect the new menu layout.

Make sure you have downloaded and installed the FoxPro driver from previous pages in the section.
https://learn.microsoft.com/en-us/sql/odbc/microsoft/installing-and-configuring?view=sql-server-ver16

Regards,
David

**Comment by h27kim** [comment]
Thanks!  That information is kinda important (since the only options that
showed up are dbase, IIRC, on my end.)

Now, the drivers are the other problem:  there seems to be no driver
associated with FoxPro database on any microsoft web site now (some/many of
hte documentation is still there, but none of the actual drivers.)

**Comment by David-Engel** [comment]
Hmm. Looks like a lot of content has been removed since FoxPro has been out of support for so long. I'm guessing these pages are relics, too, and should be "cleaned up". I know, unfortunate for those still running legacy apps. A little searching came up with this blog: http://woody-prolib.blogspot.com/2018/12/how-to.html
and this GitHub repo, which you might find useful: https://github.com/VFPX/VFP9SP2Hotfix3

Regards,
David

**Comment by h27kim** [comment]
Thanks!  I'll check these out.

**Comment by David-Engel** [comment]
#please-close
