### ISSUE TITLE
Missing index inconsistent documentation

### ISSUE THREAD

**Issue by mkassow** [MicrosoftDocs/sql-docs#9166]
This page [Tune nonclustered indexes with missing index suggestions](https://learn.microsoft.com/en-us/sql/relational-databases/indexes/tune-nonclustered-missing-index-suggestions#limitations-of-the-missing-index-feature) states in limitations:
"Suggestions are gathered for a maximum of 500 missing index groups. After this threshold is reached, no more missing index group data is gathered."

The page [sys. dm_db_missing_index_groups (Transact-SQL)](https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-missing-index-groups-transact-sql#remarks) states in remarks:
"The result set for this DMV is limited to 600 rows. Each row contains one missing index. If you have more than 600 missing indexes, you should address the existing missing indexes so you can then view the newer ones."

In practice we have seen a maximum 600 rows. Is a clarification or correction needed?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9b87a42-d40c-e064-838f-301da2dc3fc2
* Version Independent ID: f9b87a42-d40c-e064-838f-301da2dc3fc2
* Content: [Tune nonclustered indexes with missing index suggestions - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/indexes/tune-nonclustered-missing-index-suggestions?view=sql-server-2016#limitations-of-the-missing-index-feature)
* Content Source: [docs/relational-databases/indexes/tune-nonclustered-missing-index-suggestions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/tune-nonclustered-missing-index-suggestions.md)
* Service: **sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@mkassow -- thank you for your detailed feedback.

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
@mkassow - thank you for the note. I'm reviewing the issue with the product group.
