### ISSUE TITLE
Why the website

### ISSUE THREAD

**Issue by TheOnlyDasBoot** [MicrosoftDocs/sql-docs#9169]
Why do you make me have to select the download?  You already KNOW what version I am running and on what machine type so why make by go through all the hassle?  I should be able to click DOWNLOAD and not be taken you your website but instead the download should start.  You already know everything about the PC and the SSMS version I am running.  I clicked download which means I want it.  Do you make your users do this with Windows updates?  How about Office or Visual Studios?  Get my point.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by WilliamAntonRohm** [comment]
@TheOnlyDasBoot -- David, thank you for your considered feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

**Comment by erinstellato-ms** [comment]
@TheOnlyDasBoot can you clarify what you are clicking that is taking you to another website?  When I click on the "Free Download for SQL Server Management Studio (SSMS) 19.1 link, it starts to download the installer.  When I click on any of the languages under the Available Languages heading, the installers immediately start to download.
