### ISSUE TITLE
Steps to take SQL MI Copy only backups is missing

### ISSUE THREAD

**Issue by Frankd4** [MicrosoftDocs/sql-docs#9174]
[Enter feedback here]

Steps to take SQL MI Copy only backups is missing, there is only t-sql for SQL server, please update the doc

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2325bc0e-ffd7-0f37-eb0e-e01540892936
* Version Independent ID: 401d5bbd-e07d-8379-5705-039c0f5b6ce8
* Content: [Copy-Only Backups - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/copy-only-backups-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/copy-only-backups-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/copy-only-backups-sql-server.md)
* Service: **sql**
* Sub-service: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @Frankd4 , thanks for bringing this to our attention! @Stralle , would you be able to help with this Git Issue?

Thanks!
Masha from the SQL Docs team
#assign:Stralle

**Comment by Frankd4** [comment]
Thank you @MashaMSFT

**Comment by Stralle** [comment]
@Frankd4 what would be your proposal/idea here? I'm not sure I understand, because T-SQL template is applicable for Azure SQL Managed Instance as well, it shall just be exported to Azure storage. Do we really need to update this example?

**Comment by Frankd4** [comment]
Hi @Stralle 

Thank you. Please take a look at the examples in the article, these are not applicable to Azure SQL MI. 
We need specific examples for SQL MI. I will ping you over MS teams

**Comment by Stralle** [comment]
Hi, @Frankd4 I added example to our docs. Please let me know if you think we need to add more detailed example(s) and feel free to contribute!

**Comment by Frankd4** [comment]
Thanks a lot @Stralle :)
