### ISSUE TITLE
Node.js Driver for SQL Server,

### ISSUE THREAD

**Issue by ajpogue** [MicrosoftDocs/sql-docs#9178]
Are we still recommending Tedious for  Node.js driver for SQL Serve?

Node.js Driver for SQL Server, we list Tedious. https://learn.microsoft.com/en-us/sql/connect/node-js/node-js-driver-for-sql-server?view=sql-server-ver16

The tedious site says  - Note: **tediousjs/mssql is no longer being actively maintained**
https://tediousjs.github.io/tedious/frequently-encountered-problems.html

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ccbd2d2-5e40-d08e-9b05-d410eda2b891
* Version Independent ID: 83cb4507-b12a-cafe-8bab-4121984b0ce4
* Content: [Node.js Driver for SQL Server - Node.js driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/node-js/node-js-driver-for-sql-server?view=sql-server-ver16)
* Content Source: [docs/connect/node-js/node-js-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/node-js/node-js-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
Yes. The note only refers to the `tediousjs/node-mssql` (looks like there is a typo in that tedious doc) project, not the `tediousjs/tedious` project. The `tediousjs/tedious` project is different and is definitely still actively maintained.

Regards,
David

#please-close
