### ISSUE TITLE
Unix package names are case sensitive

### ISSUE THREAD

**Issue by infa-presales** [MicrosoftDocs/sql-docs#9183]
In this document the spelling of the unix package names is incorrect. 
Package names in RH Linux are case sensitive, so the references to unixODBC-devel must noch be spelled as unixodbc-devel!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?tabs=redhat-install&view=sql-server-ver16#RHEL)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@infa-presales -- thank you for catching this.  I am updating the article.

**Comment by rwestMSFT** [comment]
@infa-presales You are correct: package names are case-sensitive.

The casing of `unixODBC-devel` is deliberate. You will see as much on this site: https://pkgs.org/download/unixODBC-devel
