### ISSUE TITLE
Vulnerability Assessment removed from SSMS 19.1

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/sql-docs#9187]
Hi,
 
[Vulnerability assessment for SQL Server - SQL Server | Microsoft Learn](https://learn.microsoft.com/en-us/sql/relational-databases/security/sql-vulnerability-assessment?view=sql-server-ver16) was removed from SSMS 19.1. What would you like to do with this article? Add a note on the removal as people may still be using older versions now?

![image](https://github.com/MicrosoftDocs/sql-docs/assets/40343254/218c38e2-2f32-474e-836a-334729efbfef)

See [Release notes for (SSMS) - SQL Server Management Studio (SSMS) | Microsoft Learn](https://learn.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver16) 

![image](https://github.com/MicrosoftDocs/sql-docs/assets/40343254/28305d27-427f-4887-aecc-ab31996b4db2)

PS. [PowerShell cmdlets for managing SQL Vulnerability Assessments | Microsoft Learn](https://learn.microsoft.com/en-us/archive/blogs/sqlsecurity/powershell-cmdlets-for-managing-sql-vulnerability-assessments) seem to be still available with [PowerShell Gallery | SqlServer 22.1.1](https://www.powershellgallery.com/packages/SqlServer/22.1.1)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2d785ce-ee98-7cbf-a016-b88f6947dd8e
* Version Independent ID: 2ecb2905-5c58-f768-3487-5af00d983102
* Content: [Vulnerability assessment for SQL Server - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/sql-vulnerability-assessment?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/sql-vulnerability-assessment.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/sql-vulnerability-assessment.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @DavidTrigano
* Microsoft Alias: **datrigan**

**Comment by WilliamAntonRohm** [comment]
@ingebeumer -- Inge, thank you again for your feedback.

@DavidTrigano -- David, please look into this issue.

**Comment by rwestMSFT** [comment]
@ingebeumer Discussing this with @erinstellato-ms and we'll close this when we've created an internal PR. Thanks!

**Comment by rwestMSFT** [comment]
Replaced by https://github.com/MicrosoftDocs/sql-docs-pr/pull/27935.
