### ISSUE TITLE
ODBC 18 not compatible

### ISSUE THREAD

**Issue by halinegv** [MicrosoftDocs/sql-docs#9188]
Hello team,
On the "System requirements" section, this documentation says "This component requires both Windows Installer 4.5 and the latest Microsoft ODBC Driver for SQL Server", kindly consider to change it to Microsoft ODBC 17 instead of latest, as the latest version is 18 and the this BCP version doesn't support the ODBC 18.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86bd520a-7468-fd55-c357-b0f645a917ef
* Version Independent ID: 3dc9dee5-afcb-8287-4441-e84ff717186a
* Content: [bcp utility - SQL Server](https://learn.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver16#system-requirements)
* Content Source: [docs/tools/bcp-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/bcp-utility.md)
* Service: **sql**
* Sub-service: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@halinegv -- Haline, thank you for your suggestion.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@halinegv -- Haline, the article has been updated.

**Comment by halinegv** [comment]
It looks great, thanks @WilliamAntonRohm!
