### ISSUE TITLE
Link to SQL 2005 documentation brings up 404 page not found error

### ISSUE THREAD

**Issue by byroniac** [MicrosoftDocs/sql-docs#9193]
The link to the SQL 2005 documentation is broken on the next page after clicking the link.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 444e750b-2eb3-722c-bd43-16963e35248a
* Version Independent ID: b4351b94-6403-4efa-9e8f-3738211ce849
* Content: [Previous versions of SQL Server documentation - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/previous-versions-sql-server?view=sql-server-ver16)
* Content Source: [docs/sql-server/previous-versions-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/previous-versions-sql-server.md)
* Service: **sql**
* Sub-service: **install**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by rwestMSFT** [comment]
Confirmed that the 2005, 2008, 2008 R2, and 2012 pages don't load.

**Comment by byroniac** [comment]
Certain links on that next page do load, like "[SQL Server 2005 Administrator Guide](https://learn.microsoft.com/en-us/previous-versions/sql/sql-server-2005/administrator/)"

**Comment by rwestMSFT** [comment]
Yeah, we're on it.

**Comment by MikeRayMSFT** [comment]
Thanks @byroniac (Byron).

Internally, I'm tracking this at [User Story 144181](https://dev.azure.com/msft-skilling/Content/_workitems/edit/144181): Databases | Fix links to archived content.

I think the resolution will publish within two weeks. Just based on current load.

**Comment by byroniac** [comment]
Much appreciated.

**Comment by MikeRayMSFT** [comment]
@byroniac,

Currently you can access the content from these links:

[SQL Server 2012](https://msdn.microsoft.com/en-US/library/ms130214(v=sql.110))
[SQL Server 2008 R2](https://msdn.microsoft.com/en-US/library/ms130214(v=sql.105))
[SQL Server 2008](https://msdn.microsoft.com/en-US/library/ms130214(v=sql.100))
[SQL Server 2005](https://msdn.microsoft.com/en-US/library/ms130214(v=sql.90))

We're working to update the landing page. Thanks.

**Comment by MikeRayMSFT** [comment]
Internal incident: [413125629](https://portal.microsofticm.com/imp/v3/incidents/details/413125629/home)

**Comment by rwestMSFT** [comment]
This issue has been resolved.
