### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by PhilemonPhilippin** [MicrosoftDocs/sql-docs#9196]
Hello,
In the "Connect to SQL Server" section, step 2.

I tried this but with the provided path, the "No such file or directory" error message shows.

Then, I tried the path /opt/mssql-tools/bin/sqlcmd -S localhost -U SA 
(Without the 18 after "mssql-tools")
And it worked!

I hope it may help you, or others.

I wish you a good day

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-cmd)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @amitkh-msft
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@PhilemonPhilippin -- Phil, thank you for bringing this to our attention.  I am updating the article.

**Comment by rwestMSFT** [comment]
Related to #9209

**Comment by rwestMSFT** [comment]
This has been resolved.
