### ISSUE TITLE
Database diagram for azure sql database

### ISSUE THREAD

**Issue by ramyadba** [MicrosoftDocs/sql-docs#9198]
How to get ERD for azure sql database am using SSMS 18.6.. getting table diagrams but not relationships

**Comment by ramyadba** [comment]
am following these but couldn't find anywhere.. all docs are showing for previous SSMS version.. but want to get ER diagram with relationship from SSMS 18.6 for Azure database

**Comment by rwestMSFT** [comment]
This is a support issue, and is outside of the scope of this repository. Please redirect your question to the SQL Server on Microsoft Q&A link posted previously.
