### ISSUE TITLE
Download Links

### ISSUE THREAD

**Issue by kmcrawford99** [MicrosoftDocs/sql-docs#9199]
The download links on this page do not work.  I'm unable to apply the latest SQL 2019 CU.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9ff3c86-865f-9cbb-1d0a-2248149f4c87
* Version Independent ID: 12963cad-1c8a-d3f4-7b44-3fcd56206393
* Content: [CAB download updates for offline install - SQL Server Machine Learning Services](https://learn.microsoft.com/en-us/sql/machine-learning/install/sql-ml-cab-downloads?view=sql-server-ver15)
* Content Source: [docs/machine-learning/install/sql-ml-cab-downloads.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/install/sql-ml-cab-downloads.md)
* Service: **sql**
* Sub-service: **machine-learning-services**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
@kmcrawford99 Acknowledged, thanks. We are aware and resolving this soon. Will update.

**Comment by WilliamDAssafMSFT** [comment]
@kmcrawford99 The latest 2019 CAB links have been repaired. Please refresh and try now.
