### ISSUE TITLE
SQL Managed Instance dot not support some ALTER DATABASE commands

### ISSUE THREAD

**Issue by raphaelquati** [MicrosoftDocs/sql-docs#9205]
SQL Managed Instance do not support these commands:

```
ALTER DATABASE <dbname>
SET RESTRICTED_USER
WITH ROLLBACK IMMEDIATE;

ALTER DATABASE <dbname>
SET MULTI_USER;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 537e197c-adac-94b7-1a8e-9f5ca34a29fc
* Version Independent ID: 99f9866c-b728-219a-c49d-8f7d52f59ea0
* Content: [Contained user access to contained databases - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/contained-database-users-making-your-database-portable?view=sql-server-ver16&source=docs)
* Content Source: [docs/relational-databases/security/contained-database-users-making-your-database-portable.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/contained-database-users-making-your-database-portable.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by raphaelquati** [comment]
Documentation: https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/transact-sql-tsql-differences-sql-server?view=azuresql#alter-database-statement

**Comment by WilliamAntonRohm** [comment]
@raphaelquati -- Raphael, thank you for your well-researched feedback.

@VanMSFT -- Van, please look into this issue.

**Comment by VanMSFT** [comment]
Still following up internally on the best approach.

**Comment by VanMSFT** [comment]
After speaking with the Product Team, the best way to alter the database for containment is to kill connections to the database, as no other options currently exist. However, this comes with a heavy warning to understand the consequences of killing connections to the database. I've added the changes in the article.
