### ISSUE TITLE
MSSQL Express Edition production license for versions 2019/2022 links to 2017 license

### ISSUE THREAD

**Issue by davidemaggi** [MicrosoftDocs/sql-docs#9208]
Hello all,
I'm working on a project that includes a MSSQL 2019 Express instance deployed in a container, I looked in the container's license and then in the 2019 Linux license at his page.

![image](https://github.com/MicrosoftDocs/sql-docs/assets/6232921/4de2538f-4804-4ce6-9adb-94e8aa5564c0)

The link for express license is valid but points to the 2017 version, is this license still applicable or a different license is enforced?

Reference: [LINK to RTF](https://go.microsoft.com/fwlink/?linkid=857693) | [Zipped RTF](https://github.com/MicrosoftDocs/sql-docs/files/12248843/license_Expr.zip)

This issue is valid also for 2022 version.

Thanks and best regards

Dave

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3dc2ec36-4915-f7ab-3104-282acc9321e6
* Version Independent ID: fc98af17-f3c5-adff-69ca-593f985e7882
* Content: [Deploy and connect to SQL Server Linux containers - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment?view=sql-server-linux-ver15&pivots=cs1-bash#production)
* Content Source: [docs/linux/sql-server-linux-docker-container-deployment.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-docker-container-deployment.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @amitkh-msft
* Microsoft Alias: **amitkh**

**Comment by rwestMSFT** [comment]
It's effectively the same license, just the version number is bumped.

**Comment by davidemaggi** [comment]
Thanks to You Randolph
