### ISSUE TITLE
Typo in filepath

### ISSUE THREAD

**Issue by MintTree117** [MicrosoftDocs/sql-docs#9209]
[Enter feedback here]
/opt/mssql-tools18/bin/sqlcmd

should be

/opt/mssql-tools/bin/sqlcmd

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-bash)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @amitkh-msft
* Microsoft Alias: **amitkh**

**Comment by rwestMSFT** [comment]
Confirmed, thank you! We'll publish an update shortly.

**Comment by MintTree117** [comment]
I'm very glad Microsoft is so responsive with your docs and issues. Fantastic!
