### ISSUE TITLE
FullTextIndex missing ExcludeObjectTypes list?

### ISSUE THREAD

**Issue by MikeMcWilliams** [MicrosoftDocs/sql-docs#9212]
Hello!  Thank you for building such a great tool!
Both `FullTextCatalogs` and `FullTextStoplists` are in the ExcludeObjectTypes list; however it appears that FullTextIndexes are not:

`*** Argument 'ExcludeObjectTypes' has an invalid value: 'FullTextIndexes'.`

Is there something I overlooked or missing?

**Comment by rwestMSFT** [comment]
Hi @MikeMcWilliams, do you mind referencing the article in question?

**Comment by rwestMSFT** [comment]
Hi @MikeMcWilliams, I'm closing this issue because we haven't heard from you. If that changes, please feel free to respond below.
