### ISSUE TITLE
Install fails for Ubuntu 22.04

### ISSUE THREAD

**Issue by gordthompson** [MicrosoftDocs/sql-docs#9213]
Current instructions for Ubuntu fail on Ubuntu 22.04 for both msodbcsql18 and msodbcsql17. With a freshly-provisioned VM running Xubuntu 22.04, fully patched as of 2023-08-04:

```
$ sudo curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list > /etc/apt/sources.list.d/mssql-release.list
bash: /etc/apt/sources.list.d/mssql-release.list: Permission denied
```

Using `sudo -s` and running the same command succeeds …

```
$ sudo -s
root@xubu-22-04:/home/gord# curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list > /etc/apt/sources.list.d/mssql-release.list
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    88  100    88    0     0    158      0 --:--:-- --:--:-- --:--:--   159
```

… but then if I try to continue with the installation I get the following errors

```
root@xubu-22-04:/home/gord# exit
exit
gord@xubu-22-04:~$ sudo apt update
Hit:1 http://ca.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://ca.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]    
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]      
Get:4 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3,611 B]
Get:5 http://ca.archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]   
Err:4 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
Reading package lists... Done
W: GPG error: https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
gord@xubu-22-04:~$ sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package msodbcsql18
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15&tabs=alpine18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by TimShererWithAquent** [comment]
Thanks @gordthompson - we'll look at the procedure -

**Comment by David-Engel** [comment]
I've updated the article with fixed commands that shouldn't result in an error. For Ubuntu:

```
if ! [[ "18.04 20.04 22.04 23.04" == *"$(lsb_release -rs)"* ]];
then
    echo "Ubuntu $(lsb_release -rs) is not currently supported.";
    exit;
fi

curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc

curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list

sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
# optional: for bcp and sqlcmd
sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18
echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
source ~/.bashrc
# optional: for unixODBC development headers
sudo apt-get install -y unixodbc-dev
```

The changes should be visible in a few hours.

Thanks,
David

#please-close

**Comment by gordthompson** [comment]
@jsoques - I just tried the script on a fresh Ubuntu 22.04 VM (fully patched) and it worked fine for me. What version of unixODBC in on the machine? (You can use `odbcinst -j` to check.)

**Comment by jsoques** [comment]
@gordthompson 
unixODBC 2.3.9
DRIVERS............: /usr/local/etc/odbcinst.ini
SYSTEM DATA SOURCES: /usr/local/etc/odbc.ini
FILE DATA SOURCES..: /usr/local/etc/ODBCDataSources

Anyways, instead of running the script I downloaded the .deb file from https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/msodbcsql18/ and installed and it worked for me.

Thanks.
