### ISSUE TITLE
The list of fulltext semantic languages is too short

### ISSUE THREAD

**Issue by phaselden** [MicrosoftDocs/sql-docs#9215]
When I run `SELECT * FROM sys.fulltext_semantic_languages` it brings back more languages than documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3509c9a1-76c1-8f9d-ea32-92fd884f9f94
* Version Independent ID: 3edee952-aafd-1528-73c7-fe460e5d67a8
* Content: [Enable Semantic Search on Tables and Columns - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/search/enable-semantic-search-on-tables-and-columns?view=sql-server-2017)
* Content Source: [docs/relational-databases/search/enable-semantic-search-on-tables-and-columns.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/search/enable-semantic-search-on-tables-and-columns.md)
* Service: **sql**
* Sub-service: **search**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
Thanks for the feedback - this article is quite out of date (last updated in 2017). I'll resolve this later this week.

**Comment by rwestMSFT** [comment]
An update to this article will publish in the next day or so. When the internal PR merges, this issue will automatically close.

Thank you again for your feedback, @phaselden.
