### ISSUE TITLE
Can't find checkbox `Use as a default template for selected server type `

### ISSUE THREAD

**Issue by Anderman** [MicrosoftDocs/sql-docs#9216]
[Enter feedback here]
Can't find the checkbox `Use as a default template for selected server type `
![image](https://github.com/MicrosoftDocs/sql-docs/assets/1858745/b00b7048-af53-4de0-941f-4cb70dd93ab8)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 226e5bd7-32a6-20d8-534b-702c61b59b22
* Version Independent ID: fb3f474b-3e6f-9d7f-7a02-7b8238717666
* Content: [Templates - SQl Server Profiler](https://learn.microsoft.com/en-us/sql/tools/sql-server-profiler/sql-server-profiler-templates?view=sql-server-ver16)
* Content Source: [docs/tools/sql-server-profiler/sql-server-profiler-templates.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sql-server-profiler/sql-server-profiler-templates.md)
* Service: **sql**
* Sub-service: **profiler**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by TimShererWithAquent** [comment]
Thanks @Anderman - I don't see it on that page either. We'll take a look.

**Comment by erinstellato-ms** [comment]
@Anderman You need to edit the template to make it the default.  Within Profiler, select File -> Templates -> Edit Template, then select the template you want to make the default.  Screenshot below:

![image](https://github.com/MicrosoftDocs/sql-docs/assets/98599126/0f555695-40b0-4bd2-90fa-af65ae8d317a)

**Comment by erinstellato-ms** [comment]
#please-close

**Comment by rwestMSFT** [comment]
Thanks, @erinstellato-ms!
