### ISSUE TITLE
install action is invalid

### ISSUE THREAD

**Issue by NewRay99** [MicrosoftDocs/sql-docs#9217]
https://github.com/MicrosoftDocs/sql-docs/blame/f4a803f2e41409b779d2525974a6adf8a0cc448d/azure-sql/database/azure-sql-python-quickstart.md#L75C5-L75C13

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
