### ISSUE TITLE
Installation fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by RichardJECooke** [MicrosoftDocs/sql-docs#9220]
`sudo /opt/mssql/bin/mssql-conf setup; `

gives error

`liblber-2.4.so.2 No such file or directory`

on Ubuntu 22.04 (LXC container)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by amitkh-msft** [comment]
hi @RichardJECooke ! SQL Server is not yet supported for Ubuntu 22.04, we are going to release this support soon, hopefully within this quarter. Once that is released you should not be seeing this issue.

**Comment by TimShererWithAquent** [comment]
@RichardJECooke Thanks for your question! It looks like @amitkh-msft has addressed your issue. I'll close this to keep the queue clear -

**Comment by BPowell76** [comment]
Any update on getting official support? Ubuntu 22.04 LTS is over a year and a half old now.

**Comment by RichardJECooke** [comment]
An easy workaround I found is just to use an older version of Ubuntu in LXC or Docker.

**Comment by NoExceptions** [comment]
On Rocky Linux (RHEL) is just installing: **openldap-compat**

`sudo yum install openldap-compat`

**Comment by mlachman** [comment]
On Ubuntu 22.04 LTS:

```
sudo wget http://http.us.debian.org/debian/pool/main/o/openldap/libldap-2.4-2_2.4.47+dfsg-3+deb10u7_amd64.deb 
sudo apt install ./libldap-2.4-2_2.4.47+dfsg-3+deb10u7_amd64.deb

wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
```

Worked for me.

**Comment by BPowell76** [comment]
I ended up giving up and just using MariaDB and then later PostgreSQL. This was just for home use anyways.

Brian Powell Jr, EI

**Comment by mlachman** [comment]
I came here because I was following Microsoft's guidelines to install the MSSQL server. However, I discovered that there's now compatibility with Ubuntu 22.04. All that's required is to utilize an alternative repository.

`curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc`

`curl -fsSL https://packages.microsoft.com/config/ubuntu/22.04/mssql-server-2022.list | sudo tee /etc/apt/sources.list.d/mssql-server-2022.list`

After this, you can simply run the installation commands:

```bash
sudo apt-get update
sudo apt-get install -y mssql-server
```
