### ISSUE TITLE
Network requirements for mssql-server-linux

### ISSUE THREAD

**Issue by lorenzodeveloper** [MicrosoftDocs/sql-docs#9221]
Hi,
I'm thinking of installing MSSQL 2019 deployed in a container and I'm wondering about network requirements for license checks and I cannot find any section in the docs talking about network requirements for the deployment.
I need to know them as in a production environment I'd like to restrict every communication to the minimum necessary.

If I decide to opt out for a Standard license and I specify the key in the deployment command, are there network requirements that the container shall follow in order to contact the license verification server, if any?
What are the endpoints that the container shall always able to reach?

Thank you.

Best regards,

Lorenzo 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3dc2ec36-4915-f7ab-3104-282acc9321e6
* Version Independent ID: fc98af17-f3c5-adff-69ca-593f985e7882
* Content: [Deploy and connect to SQL Server Linux containers - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment?view=sql-server-linux-ver15&pivots=cs1-bash#production)
* Content Source: [docs/linux/sql-server-linux-docker-container-deployment.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-docker-container-deployment.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @amitkh-msft
* Microsoft Alias: **amitkh**

**Comment by amitkh-msft** [comment]
Hi @lorenzodeveloper there are no network requirements for License checks needed, like in Windows or Linux even on containers you can specify the key during the configuration and it does not have any network requirement for licensing verification. Any reason why you are using SQL 2019 and not the latest SQL 2022 ?

**Comment by lorenzodeveloper** [comment]
Hi,
Thanks for your prompt answer. 
No particular reason, that's the version I used to work with, so I searched for it first.

So the only way to check the validity of license key is through audit or offline logics in the container?

However, I have another doubt on the network requirements:
Reading the license for Express version in the first pages I read that it can collect performance and other data related to how one uses SQL Server. That data would be sent somewhere in the internet? 

Thank you again.

Lorenzo

**Comment by rwestMSFT** [comment]
The performance collection process will run, but if your machine isn't connected to the Internet, it won't send that data. That's not an issue.

I'm closing this issue, as it is outside the scope of our documentation.

Thanks for your questions. If you have anything else, please feel free to comment below, or open a new issue.
