### ISSUE TITLE
Documentation for -k[1|2] is incorrect

### ISSUE THREAD

**Issue by shueybubbles** [MicrosoftDocs/sql-docs#9224]
Using Sqlcmd from SQL Server 2019, we can see that `-k` is not the same as `-k1`

`-k` removes control characters 
`-k1` replaces each control character with a space
`-k2` replaces consecutive control characters with a single space

```
>sqlcmd -k 2
1> select '1
2~
3~
4~ 3'
5> go

--------
1 3

(1 rows affected)
1> quit

>sqlcmd -k
1> select '1
2~
3~
4~ 3'
5> go

--------
13

(1 rows affected)
1> quit

>sqlcmd -k1
1> select '1
2~
3~
4~ 3'
5> go

--------
1      3
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8da1f57b-a8fd-cca7-4cf0-9d594d365062
* Version Independent ID: 60c46780-6a03-7958-c77a-e7c94e3b9e85
* Content: [sqlcmd utility - SQL Server](https://learn.microsoft.com/en-us/sql/tools/sqlcmd/sqlcmd-utility?view=sql-server-ver15&source=docs)
* Content Source: [docs/tools/sqlcmd/sqlcmd-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlcmd/sqlcmd-utility.md)
* Service: **sql**
* Sub-service: **tools-other**
* GitHub Login: @grrlgeek
* Microsoft Alias: **jeschult**

**Comment by rwestMSFT** [comment]
Thanks, @shueybubbles. Mind doing a PR in the private repo?
