### ISSUE TITLE
Add Information About tempdb performance improvements in SQL Server 2022

### ISSUE THREAD

**Issue by GlennAlanBerry1961** [MicrosoftDocs/sql-docs#9225]
I think it would be very helpful to add some info (or have a link) to the [tempdb improvements in SQL Server 2022](https://cloudblogs.microsoft.com/sqlserver/2022/07/21/improve-scalability-with-system-page-latch-concurrency-enhancements-in-sql-server-2022/) under the “Performance improvements in tempdb for SQL Server” section in the page linked below.
              [tempdb database - SQL Server | Microsoft Learn](https://learn.microsoft.com/en-us/sql/relational-databases/databases/tempdb-database?view=sql-server-ver16#optimizing-tempdb-performance-in-sql-server)

The idea here is to educate and remind more people about useful improvements in SQL Server 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37fab3b5-a2f3-5612-06e2-01e0406a615d
* Version Independent ID: 2daa00e0-8234-bf26-13c0-8d5200a1f4a5
* Content: [tempdb database - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/databases/tempdb-database?view=sql-server-ver16#optimizing-tempdb-performance-in-sql-server)
* Content Source: [docs/relational-databases/databases/tempdb-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/tempdb-database.md)
* Service: **sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by rwestMSFT** [comment]
I have an internal ticket for this already.

**Comment by rwestMSFT** [comment]
Closing this. The tempdb article was already updated before the blog post went live.
