### ISSUE TITLE
Download SSMS not working

### ISSUE THREAD

**Issue by Saulnocap** [MicrosoftDocs/sql-docs#9232]
Download page for SSMS is not working properly, please review

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
@Saulnocap Can you please provide more information about what "not working properly means"?  What link are you selecting - the "Free Download for SQL Server Management Studio (SSMS) 19.1", or one under the Available Languages section (https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16#available-languages).  I've tested the download for both and did not have an issue.  If you are receiving an error message, please include that.  Thank you.

**Comment by Saulnocap** [comment]
For sure, when clicked the "Download SSMS" link, the page is not available

**Comment by Saulnocap** [comment]
[image: image.png]Is rejecting the connection, "Cannot access this website"

**Comment by erinstellato-ms** [comment]
@Saulnocap are you stating that you cannot get to the actual download PAGE?  Or once on the page, you cannot click a link?

If it's the first one, how are you finding the link to the page?  From a search engine, or from another page?  I am able to access the page.  Thanks.

**Comment by Saulnocap** [comment]
I'm trying to get in there through this link "
https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16#available-languages"
by clicking the "  Free Download for SQL Server Management Studio (SSMS)
19.1 <https://aka.ms/ssmsfullsetup>  " hypertext, in Google Chrome. seems
like an error on my connection, my apologies.

**Comment by erinstellato-ms** [comment]
Ok, hopefully it's resolved for you - I am able to access all of the links that you included above.  And for reference, I am not in the Redmond area, so I am not on the corporate network or anything like that.

**Comment by kumarmageshr** [comment]
SSMS Download link is not working 
https://download.microsoft.com/download/a/c/a/aca4e29f-6925-4d50-a06b-5576c6ea629f/SSMS-Setup-ENU.exe

**Comment by erinstellato-ms** [comment]
@kumarmageshr Can you share the error that you're getting?  I am able to download just fine (outside the MS network) and I've confirmed the files are available.  Could this be a connectivity issue on your side?

**Comment by kumarmageshr** [comment]
![Capture](https://github.com/MicrosoftDocs/sql-docs/assets/9978620/d7caf90e-6c4d-49ea-9966-2a5cf5f9c4d7)
FYI 
Other applications are working fine. Even Microsoft-related website links are working fine. 
![Uploading 12.PNG…]()

**Comment by erinstellato-ms** [comment]
@kumarmageshr Have you downloaded from the site previously?  Have you checked with other folks in your organization to confirm they have the same issue?
