### ISSUE TITLE
Broken link (pymssql module)

### ISSUE THREAD

**Issue by shoff** [MicrosoftDocs/sql-docs#9234]
The link to the pymssql module is no longer valid. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32e25473-d2fe-fa98-586b-2a1129cdf165
* Version Independent ID: 4cdbf46d-09e2-8065-ffa4-8722ec3bc114
* Content: [Step 1: Configure pymssql environment - Python driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/python/pymssql/step-1-configure-development-environment-for-pymssql-python-development?view=sql-server-2017)
* Content Source: [docs/connect/python/pymssql/step-1-configure-development-environment-for-pymssql-python-development.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/python/pymssql/step-1-configure-development-environment-for-pymssql-python-development.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@shoff -- Steve, thank you for bringing this to our attention.  I am updating the article.
