### ISSUE TITLE
New-AzStorageContainerSASToken - leading question mark

### ISSUE THREAD

**Issue by alansingfieldcvn** [MicrosoftDocs/sql-docs#9236]
The PowerShell script for creating the SAS Token needs to take into account that the question mark may no longer be returned in a future version.

Suggest replacing $sas.Substring(1) with $sas.TrimStart('?')

```
WARNING: Upcoming breaking changes in the cmdlet 'New-AzStorageContainerSASToken' :
The leading question mark '?' of the created SAS token will be removed in a future release.
- The change is expected to take effect from Az version : '11.0.0'
- The change is expected to take effect from version : '6.0.0'
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc04e819-4cfd-5b23-404b-8d4ed41afd21
* Version Independent ID: d254a232-e05d-0d52-0e25-7e83866f12e6
* Content: [SQL Server Backup to URL for Microsoft Azure Blob Storage - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/sql-server-backup-to-url.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/sql-server-backup-to-url.md)
* Service: **sql**
* Sub-service: **backup-restore**
* GitHub Login: @dplessMSFT
* Microsoft Alias: **dpless**

**Comment by WilliamAntonRohm** [comment]
@alansingfieldcvn -- thank you for your suggestion.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@dplessMSFT -- David, please confirm these code changes in [private PR 28091](https://github.com/MicrosoftDocs/sql-docs-pr/pull/28091).

**Comment by rwestMSFT** [comment]
@alansingfieldcvn Please can you direct me to your assertion that the SAS token won't have a `?` character in future versions? Our documentation doesn't comment on future releases for obvious reasons. I understand your suggestion and why you'd want the code to take it into account, but do you have a source?

**Comment by alansingfieldcvn** [comment]
Hello Randolph,

Yes of course, it is in:
https://learn.microsoft.com/en-us/powershell/azure/upcoming-breaking-changes?view=azps-10.1.0&viewFallbackFrom=azps-8.3.0#new-azstoragecontainersastoken

New-AzStorageContainerSASToken
*       Cmdlet breaking-change will happen to all parameter set
o   The leading question mark '?' of the created SAS token will be removed in a future release.
o   This change is expected to take effect from Az.Storage version: 6.0.0 and Az version: 11.0.0

You also get an "upcoming breaking change" warning when using the command.

Thanks,

Alan.


Alan Singfield BSc (Hons)
IT Director, Central Valuation Network Services

M:  07811 942003
E: ***@***.******@***.***>

1 King House, 55 Victoria Street, St Albans, Hertfordshire AL1 3ER
