### ISSUE TITLE
More details on the server string to connecton

### ISSUE THREAD

**Issue by UchiTesting** [MicrosoftDocs/sql-docs#9255]
Hello,

This page tells about how to Connect SQL Server. I think it is not detailed enough.
With a special focus to the syntax to be used to actually connect to SQL Server.

## A bit of context.

I started a SQL Server course pathway a few days back which introduced me to Azure Data Studio.
Because I do not have administrative rights on my corporate PC but an installation of Docker I could just spin a container and connect using the sample server line from placeholder (`tcp:localhost,1433`)
Now I also have an instance installed on my personal PC. I tried the syntax and other things and could not connect.

It told about handshake issue. I started checking TCP is enabled and other setup (trust cert, encrypt and more). 
Then I looked up for the error and people seem to face such situation (for many reasons).

Until eventually I just removed everything and just input my machine name.

If there is something such as `tcp:` protocol, **what are the other options possible to connect?**

**Where could I find this piece of information?**

## Suggestions

- If it is already exhaustively described on any page, just **add a link** to there on this page.
- Else, it is a good candidate to **describe the information on the page**.

Kind Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7df0319c-ec31-e09f-6f44-d71ed20544c3
* Version Independent ID: c52fabfa-5a3d-ea25-cbbf-8a988a8bc867
* Content: [Quickstart: Connect and query SQL Server - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/quickstart-sql-server?view=sql-server-ver16)
* Content Source: [docs/azure-data-studio/quickstart-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/quickstart-sql-server.md)
* Service: **azure-data-studio**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
@UchiTesting Can you share the SQL Server course pathway that you used for this exercise?  To be clear, the confusion isn't from the Connect & query SQL Server doc (there is no reference to (tcp:localhost,1433)) but it's from this dialog: 

![image](https://github.com/MicrosoftDocs/sql-docs/assets/98599126/e2750b20-6436-4175-8f9e-f396d734fefb)

The screenshot in the Connect & query SQL Server doc has just the text localhost for the server.

For SQL, localhost is another way of saying "the SQL default instance installed on my machine".  If putting in your machine name for servername worked, then using localhost should also work.  If you use localhost,1433 then you're appending the default port number (1433) for SQL on to the servername.

I can update the docs to use a machine name for the servername, and either provide additional information for that field, or link to the appropriate doc.  Tagging @rwestMSFT for any suggestions on a doc with details about servername.

**Comment by rwestMSFT** [comment]
@UchiTesting If we don't hear back from you in the next while, we will close this issue, since we are waiting for some further information from you. We will still go forward with updating the article in question, but your feedback will go a long way to helping us get the wording right.

**Comment by UchiTesting** [comment]
> @UchiTesting Can you share the SQL Server course pathway that you used for this exercise? To be clear, the confusion isn't from the Connect & query SQL Server doc (there is no reference to (tcp:localhost,1433)) but it's from this dialog:
> 
> ![image](https://user-images.githubusercontent.com/98599126/261730472-e2750b20-6436-4175-8f9e-f396d734fefb.png)
> 
> The screenshot in the Connect & query SQL Server doc has just the text localhost for the server.
> 
> For SQL, localhost is another way of saying "the SQL default instance installed on my machine". If putting in your machine name for servername worked, then using localhost should also work. If you use localhost,1433 then you're appending the default port number (1433) for SQL on to the servername.
> 
> I can update the docs to use a machine name for the servername, and either provide additional information for that field, or link to the appropriate doc. Tagging @rwestMSFT for any suggestions on a doc with details about servername.

Hi,

The course in particular is bellow. There is 3mn demo telling how to connect to a database.

https://www.pluralsight.com/courses/sqlserver-tables-view-designing-implementing

I don't know how it is important. Especially because it is not a course about ADS and does not cover it extensively.

What I am really asking for is information about the syntax accepted in that field.

The placeholder gives an example from which we could make assumptions. They can be wrong.

When I see `tcp:localhost,1433` I assume there may be other protocols than tcp or other possible parameters that could be added to specify even more how to connect to the database.

## Example

This is an example I just made up to explain what it is about.

Synopsis

`protocol:hostname,port|AnyParam/SomethingElse%Furthersettings`

| Data | Possible values | Description |
|-|-|-|
| protocol | tcp, udp, np | Defines the protocol to be used. Can be tcp, usp, np for respectively TCP, UDP or Named Pipes (default value) |
| Hostname | - | URL, domain name or IP to SQL Server |
| Port | | Port to be used when applicable. This data is not needed when using named pipes |
| AnyParam | Any value description | Any description |
| | | ... you name it...|

I hope this makes my point clearer.

Kind Regards

**Comment by rwestMSFT** [comment]
Thanks @UchiTesting, this confirms what I understood from your original feedback, and will go towards improving our documentation. We appreciate it!

**Comment by rwestMSFT** [comment]
@UchiTesting We have an article for [ODBC client connectivity](https://learn.microsoft.com/en-us/sql/connect/oledb/applications/using-connection-string-keywords-with-oledb-driver-for-sql-server), which contains some of this information, but we're going to use this GitHub issue to kick off the creation of a new article that summarizes the key points.

**Comment by rwestMSFT** [comment]
@UchiTesting @erinstellato-ms 

I am closing this. We have since added a new article titled [Connect to the Database Engine](https://learn.microsoft.com/sql/sql-server/connect-to-database-engine), which should answer your questions.

Once again, thank you for the feedback. Without this issue, we would not have considered adding this new article.
