### ISSUE TITLE
Customer wants clarification around X86 and X64 installer

### ISSUE THREAD

**Issue by krishnamsft20** [MicrosoftDocs/sql-docs#9256]
One of the customers had issue where they were trying to 32 bit installer on 64 bit windows machine. Their believe is that they were able to do that for years. But our testing and consultation with SIMBA team revealed that we could not use 32 bit installer on 64 bit machine. We needed to use 64 bit msi to install both 64 bit and 32 bit driver on 64 bit machine. Can we clarify something around this on this page? Something like, use X86 installer for 32 bit machines, and X64 installer to install both 64 bit and 32 bit driver on 64 bit machine. 

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a36a1d7f-a410-b597-0eb7-98212934fb0e
* Version Independent ID: e706f2bd-e051-fcff-7c3d-2ef3d9f80e87
* Content: [Download ODBC Driver for SQL Server - ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16)
* Content Source: [docs/connect/odbc/download-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/download-odbc-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@krishnamsft20 -- thank you for your clear feedback.  I am updating the article.
