### ISSUE TITLE
Debian 12 link

### ISSUE THREAD

**Issue by jonkolbeinsen** [MicrosoftDocs/sql-docs#9258]
The link to Debian 12 on this page needs to be added - looks like it works: https://packages.microsoft.com/config/debian/12/prod.list

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=alpine18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
Links to Debian 12 will be added when we finish validating that scenario and add it to the support matrix. That isn't complete, yet.

Regards,
David

#please-close
