### ISSUE TITLE
Certificate for AG nodes 

### ISSUE THREAD

**Issue by pshore73** [MicrosoftDocs/sql-docs#9262]
To me at least, the certificate documentation for AG nodes is a little ambiguous. The document is very clear when it comes to defining what needs to be a part of the certificate for any given node. However, I find it incomplete in that it does not give equal clarity as to the N+1 node certificate. Does it need to be the same certificate on all nodes or a certificate per node overlapping the listener name(s)?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c76c2d8c-17da-8982-8a91-dd9968efa26e
* Version Independent ID: 2ecd127b-9f05-1f89-bcea-a93e8ded60eb
* Content: [Connect to an availability group listener - SQL Server Always On](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover?view=sql-server-ver16#SSLcertificates)
* Content Source: [docs/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover.md)
* Service: **sql**
* Sub-service: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @pshore73 , Thank you for your submission! My sincere apologies for the delay it's taken to address your concern, we've been working through a very large backlog.

During this time, Git Issues have been deprecated as we've transitioned to a new feedback system. I've added your suggestion to our internal backlog (#250055) that we will continue addressing as priorities and resources allow.

We use your feedback to improve our documentation, so we are grateful for your input, and your time. I apologize for any inconvenience, and thank you for your patience and understanding. 

Masha from the SQL Docs team
#please-close
