### ISSUE TITLE
Create user-defined functions: Document side-effecting functions restricted from direct use

### ISSUE THREAD

**Issue by erikdarlingdata** [MicrosoftDocs/sql-docs#9266]
The section on limitations and restrictions does not mention not being able to directly call side-effecting functions, e.g.

```
CREATE OR ALTER FUNCTION
    dbo.r()
RETURNS float
AS
BEGIN
    RETURN RAND();
END;
GO 

CREATE OR ALTER FUNCTION
    dbo.n()
RETURNS uniqueidentifier
AS
BEGIN
    RETURN NEWID()
END;
GO
```
Will both return errors:

> Msg 443, Level 16, State 1, Procedure r, Line 6 [Batch Start Line 0]
> Invalid use of a side-effecting operator 'rand' within a function.
> 
> Msg 443, Level 16, State 1, Procedure n, Line 8 [Batch Start Line 8]
> Invalid use of a side-effecting operator 'newid' within a function.

Of course you can wrap either in a view and call the view from within a function, but you don't need to mention that 😉

It would be helpful to have the full current list documented here.

Thank you for your prompt attention to my highly performant ask.

**Comment by WilliamAntonRohm** [comment]
@erikdarlingdata -- Erik, thank you again for your close reading.  Which learn.microsoft.com article are you following?

**Comment by erikdarlingdata** [comment]
@WilliamAntonRohm oops, right here: https://learn.microsoft.com/en-us/sql/relational-databases/user-defined-functions/create-user-defined-functions-database-engine?view=sql-server-ver16

**Comment by rwestMSFT** [comment]
Thanks, Eric. I'll take a look at this.

**Comment by rwestMSFT** [comment]
@erikdarlingdata Still chatting with the product group about this.

**Comment by erikdarlingdata** [comment]
@rwestMSFT 💯

**Comment by rwestMSFT** [comment]
@erikdarlingdata We're closing this issue because we're tracking it internally.

AB#70883
