### ISSUE TITLE
Documentation error on the "Manage accelerated database recovery" document

### ISSUE THREAD

**Issue by bjrazumich** [MicrosoftDocs/sql-docs#9267]
There is a documentation error on the page. The page refers to the system view sys.dm_persistent_version_store_stats but that view does not exist. A bit of searching on a 2019 database indicates the actual name of the view is sys.dm_tran_persistent_version_store_stats. Thanks for considering this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98d6d147-a7a7-cd75-13fb-4f4f72a16a15
* Version Independent ID: bb4f71b0-3103-06af-0560-e28860c752bc
* Content: [Manage accelerated database recovery - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/accelerated-database-recovery-management?view=sql-server-ver15)
* Content Source: [docs/relational-databases/accelerated-database-recovery-management.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/accelerated-database-recovery-management.md)
* Service: **sql**
* Sub-service: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@bjrazumich -- Robert, thank you for catching this.  I am updating the article.

**Comment by rwestMSFT** [comment]
Updated article should publish today. Thanks again for your feedback, @bjrazumich.
