### ISSUE TITLE
Topic should discuss that BUILTIN\ADMINISTRATORS get added as sysadmin in a contained AG

### ISSUE THREAD

**Issue by sommarskog** [MicrosoftDocs/sql-docs#9268]
[Enter feedback here]

I ran this, when connected to my contained AG:

  SELECT name
   FROM   sys.server_principals  
   WHERE  is_srvrolemember('sysadmin', name) = 1

And I saw this:

    sa
    BUILTIN\Administrators
    NT SERVICE\SQLWriter
    NT SERVICE\Winmgmt
    NT SERVICE\SQLSERVERAGENT

This means that the Windows administrator has access as sysadmin to the contained AG. And to the instance, since the AG is not a security boundary.

I can understand why this happens. When I run Setup to install SQL Server,I am asked to supply a Windows user that will be sysadmin. But there is no option to specify a sysadmin for the AG, so BUILTIN\Administrators comes in handy.

I think the topic should call out that this happens and recommend readers to add a real sysadmin and then drop BUILTIN\Administrators.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 269d8ec6-8675-a302-0a8a-e03222d04fa5
* Version Independent ID: 269d8ec6-8675-a302-0a8a-e03222d04fa5
* Content: [What is a contained availability group? - SQL Server Always On](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/contained-availability-groups-overview?view=sql-server-ver16)
* Content Source: [docs/database-engine/availability-groups/windows/contained-availability-groups-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/contained-availability-groups-overview.md)
* Service: **sql**
* Sub-service: **high-availability**
* GitHub Login: @kfarlee
* Microsoft Alias: **kfarlee**

**Comment by WilliamAntonRohm** [comment]
@sommarskog -- thank you for investigating this behavior.

@kfarlee -- please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @sommarskog , Thank you for your submission! My sincere apologies for the delay it's taken to address your concern, we've been working through a very large backlog.

During this time, Git Issues have been deprecated as we've transitioned to a new feedback system. I've added your suggestion to our internal backlog (#250055) that we will continue addressing as priorities and resources allow.

We use your feedback to improve our documentation, so we are grateful for your input, and your time. I apologize for any inconvenience, and thank you for your patience and understanding. 

Masha from the SQL Docs team
#please-close
