### ISSUE TITLE
Tools.NewDataComparison content is being truncated

### ISSUE THREAD

**Issue by reZach** [MicrosoftDocs/sql-docs#9269]
This is not an issue with the documentation, but with the _assumed_ tool **Tools.NewDataComparison** that is run when using the new data comparison window in Tools -> SQL Server -> New Data Comparison in Visual Studio. I did not know or could not find where I might log such a bug - and so I was hoping someone could direct me to where I might communicate the issue I have found.

The short summary of the bug is the Generate Script functionality of the New Data Comparison window in Visual Studio truncates content that is > 4000 characters. The issue has been hard to reproduce, but I have found content that replicates this issue and wanted to report this so it may be investigated.

**Comment by WilliamAntonRohm** [comment]
@reZach -- thank you for your detailed feedback.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
