### ISSUE TITLE
References are outdated

### ISSUE THREAD

**Issue by kdmishraISU** [MicrosoftDocs/sql-docs#9271]
This entire page needs a warding that it is no longer valid and where to go if they are looking for this solution (as many books refer to minicran being a best practice). 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf66e4a9-acd0-2ea7-fb78-2813645530e4
* Version Independent ID: 52f2bdba-ba6b-e3ce-3797-a98bd840dca8
* Content: [Create a repository with miniCRAN - SQL machine learning](https://learn.microsoft.com/en-us/sql/machine-learning/package-management/create-a-local-package-repository-using-minicran?view=sql-server-2017)
* Content Source: [docs/machine-learning/package-management/create-a-local-package-repository-using-minicran.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/package-management/create-a-local-package-repository-using-minicran.md)
* Service: **sql**
* Sub-service: **machine-learning**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
@kdmishraISU Thanks for taking the time to provide this feedback. We've started an internal review and doc updates are expected. We'll be providing more clarity and wider message given the [Microsoft R Application Network retirement](https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-r-application-network-retirement/ba-p/3707161).

Meanwhile, if you have any specific suggestions or replacements to improve these docs, we welcome them of course. I suggest you [create a Pull Request](https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute) and get the ball rolling on a specific change. By opening a pull request, you're collaborating with the author to add changes directly to the documentation. After your PR is merged, GitHub lists you as an article contributor. 

Either way, thanks for your feedback!
