### ISSUE TITLE
Out of data information

### ISSUE THREAD

**Issue by kdmishraISU** [MicrosoftDocs/sql-docs#9272]
Several references that are out of date. Please update. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce36aa85-fd24-74a6-1e01-20c892f92a9f
* Version Independent ID: 08b9fb79-7117-98fc-5d2c-7a42a6c49a04
* Content: [Install R packages with sqlmlutils - SQL Server Machine Learning Services](https://learn.microsoft.com/en-us/sql/machine-learning/package-management/install-additional-r-packages-on-sql-server?view=sql-server-ver15)
* Content Source: [docs/machine-learning/package-management/install-additional-r-packages-on-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/package-management/install-additional-r-packages-on-sql-server.md)
* Service: **sql**
* Sub-service: **machine-learning**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
@kdmishraISU Thanks for taking the time to provide this feedback. We've started an internal review and doc updates are expected. We'll be providing more clarity and wider message given the [Microsoft R Application Network retirement](https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-r-application-network-retirement/ba-p/3707161).

Meanwhile, if you have any specific suggestions or replacements to improve these docs, we welcome them of course. I suggest you [create a Pull Request](https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute) and get the ball rolling on a specific change. By opening a pull request, you're collaborating with the author to add changes directly to the documentation. After your PR is merged, GitHub lists you as an article contributor. 

Either way, thanks for your feedback!
