### ISSUE TITLE
Beter code

### ISSUE THREAD

**Issue by hoganlong** [MicrosoftDocs/sql-docs#9274]
This code has a pattern of checking for null and providing a default value in WHERE like this:

        AND   (pc.ProductCategoryID = @ProductCategoryID or @ProductCategoryID IS NULL)

Better code would look like this:

        AND pc.ProductCategoryID = COALESCE(@ProductCategoryID,pc.ProductCategoryID)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1f2710f-b5a5-bb12-f204-3d332ef0356e
* Version Independent ID: e838c337-fabe-5a2c-f605-ee389b321227
* Content: [Specify parameters - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/stored-procedures/specify-parameters?view=sql-server-ver16)
* Content Source: [docs/relational-databases/stored-procedures/specify-parameters.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/stored-procedures/specify-parameters.md)
* Service: **sql**
* Sub-service: **stored-procedures**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @hoganlong for taking the time to great this issue. This code change would complicate the content by introducing the `COALESCE` syntax. We feel it brings more clarity to learners of all levels of experience to use the OR.
