### ISSUE TITLE
Error 3725 if a FK depends on it

### ISSUE THREAD

**Issue by haagensen** [MicrosoftDocs/sql-docs#9280]
While it may work in this database, it's not that simple -- if the PK being removed is referenced by a FK somewhere, error 3725 is throw: `The constraint '<PK name>' is being referenced by table '<referenced table>', foreign key constraint '<FK name>'.` 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f0c0857-1a99-d09d-157d-04edf8edda01
* Version Independent ID: bf4b680f-7849-a05f-a567-c084875ab790
* Content: [Delete Primary Keys - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/delete-primary-keys?view=sql-server-ver16)
* Content Source: [docs/relational-databases/tables/delete-primary-keys.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/delete-primary-keys.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@haagensen -- Christian, thank you for your clear feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Makes sense, @haagensen. We'll add that detail to this page. Thanks for taking the time to provide this feedback!
