### ISSUE TITLE
Mistake in "Read committed" description

### ISSUE THREAD

**Issue by Aleksey-Kudryavtsev** [MicrosoftDocs/sql-docs#9281]
Section: Database Engine isolation levels
Read committed - Allows a transaction to _read_ data previously read (not modified) by another transaction without waiting for the first transaction to complete. 

I think it should be - Allows a transaction to _write_ data previously read (not modified) by another transaction without waiting for the first transaction to complete. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dae81d65-f7b9-7a97-7fe7-30775f815e5b
* Version Independent ID: d4d339e7-48d7-d159-eb59-13bdedc25b4c
* Content: [Transaction locking and row versioning guide - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-ver16)
* Content Source: [docs/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md)
* Service: **sql**
* Sub-service: **performance**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hello @Aleksey-Kudryavtsev, thanks for taking the time to provide this feedback. 

However, this would be incorrect. A read committed transaction would be blocked from reading a row by an in-progress transaction updating the row. Similarly, a read committed transaction would be blocked from writing by another read committed transaction that holds a read lock. Two Read Committed transactions that do not modify data can read the same data without waiting for the other to finish.  

If you have further technical questions, this may not be the best forum. I recommend [Microsoft Q&A (SQL Server)](https://docs.microsoft.com/answers/products/sql-server), [Microsoft Q & A (Azure SQL)](https://docs.microsoft.com/answers/products/azure?product=databases), [SQL Server Feedback](https://feedback.azure.com/forums/908035-sql-server), Microsoft Support, or your support partners.  Regardless, thanks again for this feedback, your suggestions help improve our documentation.

**Comment by Aleksey-Kudryavtsev** [comment]
@WilliamDAssafMSFT , sorry, you're right. But still the statement "Allows a transaction to read data previously read (not modified) by another transaction without waiting for the first transaction to complete." is confusing, because it's true for all isolation levels (correct me if I'm wrong).

**Comment by WilliamDAssafMSFT** [comment]
@Aleksey-Kudryavtsev it's a good contrast to the previous row - because READ UNCOMMITTED _does_ allow you to read uncommitted data from another transaction. Thus the danger!

**Comment by Aleksey-Kudryavtsev** [comment]
@WilliamDAssafMSFT , I see now, the emphasis is on _(not modified)_. IMHO confusing and would be better to invert it by saying that it does not read modified data until it's committed. Any way, thank you for your time!
