### ISSUE TITLE
Incorrect audit action group for SQL Server Auditing

### ISSUE THREAD

**Issue by Micheldongelo** [MicrosoftDocs/sql-docs#9282]
The tip that is provided for what audit action group to use is incorrect. It should be DATABASE_OBJECT_CHANGE_GROUP not DATABASE_CHANGE_GROUP.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20953c9f-c769-7849-420a-dac77f917d4a
* Version Independent ID: dfd9ad27-844c-c3c8-58a3-5d4a0c92fbba
* Content: [Transparent data encryption (TDE) - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/encryption/transparent-data-encryption.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/transparent-data-encryption.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
Good catch, @Micheldongelo. We'll update the article.

**Comment by rwestMSFT** [comment]
An article update has been staged. When that merges, this issue will automatically close. The updated article will be published in the next day or so.
