### ISSUE TITLE
No start menu for SQL MI

### ISSUE THREAD

**Issue by mfernee** [MicrosoftDocs/sql-docs#9283]
[Enter feedback here]
Hi, the document mentions logging in to Windows and navigating to the start menu. This is not possible for SQL MI.

Can you explain how to configure the SQL Agent for SQL MI, or remove the 'applies to Azure SQL Managed Instance'?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f4169a35-ff35-53ad-f184-85ea95075817
* Version Independent ID: 32157654-f726-53d8-59aa-5199e44b1625
* Content: [Configure SQL Server Agent - SQL Server Agent](https://learn.microsoft.com/en-us/sql/ssms/agent/configure-sql-server-agent?view=sql-server-ver16)
* Content Source: [docs/ssms/agent/configure-sql-server-agent.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/configure-sql-server-agent.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by rwestMSFT** [comment]
Hi @mfernee. Thanks for your feedback.

I would like to draw your attention to the alert box, just below the **Applies to** section, which states the following. I have bolded the relevant phrases:

> On [Azure SQL Managed Instance](https://learn.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance), most, **but not all** SQL Server Agent features are currently supported. Enabling and disabling SQL Server Agent is currently **not supported** in SQL Managed Instance. **SQL Agent is always running.** See [SQL Managed Instance T-SQL differences from SQL Server](https://learn.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-transact-sql-information#sql-server-agent) for details.

Since this addresses your concern, I am closing this issue. Thank you for your attention.
