### ISSUE TITLE
The page is missing a description of the Trust server certificate option

### ISSUE THREAD

**Issue by charltonbook** [MicrosoftDocs/sql-docs#9284]
The page is missing a description of the Trust server certificate option

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc7d6865-0adc-7ca9-4211-dcb7cbf6c655
* Version Independent ID: 44249c31-c58f-1b6e-8787-9941f6e06ab4
* Content: [Connect to Server (Connection Properties Page) Database Engine - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/f1-help/connect-to-server-connection-properties-page-database-engine?view=sql-server-ver16&f1url=%3FappId%3DDev15IDEF1%26l%3Den-US%26k%3Dk(sql13.swb.connecttosqlserver.connectionproperties.f1))
* Content Source: [docs/ssms/f1-help/connect-to-server-connection-properties-page-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/f1-help/connect-to-server-connection-properties-page-database-engine.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by rwestMSFT** [comment]
@charltonbook Thanks for your feedback. We do have an internal PR in progress, but I can't say when it will be published. When that happens, we'll update this issue with a comment.
