### ISSUE TITLE
Dead Links for Code Examples

### ISSUE THREAD

**Issue by suyashbansal** [MicrosoftDocs/sql-docs#9292]
When I click on the Code Example links for specific OS, it takes me to a new page that says "_We are sorry, the page you requested cannot be found. The URL may be misspelled or the page you're looking for is no longer available._"

<img width="1497" alt="Screenshot 2023-08-31 at 2 32 28 PM" src="https://github.com/MicrosoftDocs/sql-docs/assets/5832436/f2d9c07d-1080-409b-8412-32a8ea9b7bb2">

<img width="1497" alt="image" src="https://github.com/MicrosoftDocs/sql-docs/assets/5832436/50f281bd-2a0c-4b1e-9c18-3b7a75efc655">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ccbd2d2-5e40-d08e-9b05-d410eda2b891
* Version Independent ID: 83cb4507-b12a-cafe-8bab-4121984b0ce4
* Content: [Node.js Driver for SQL Server - Node.js driver for SQL Server](https://learn.microsoft.com/en-gb/sql/connect/node-js/node-js-driver-for-sql-server?view=sql-server-ver16)
* Content Source: [docs/connect/node-js/node-js-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/node-js/node-js-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by rwestMSFT** [comment]
I believe this has been resolved.
