### ISSUE TITLE
Drivers linked to dead link

### ISSUE THREAD

**Issue by azdave2020** [MicrosoftDocs/sql-docs#9295]
You cant download the drivers. The links just take you to the microsoft home page
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3cded3d0-9d0a-ce94-1c91-21de62e3ddaf
* Version Independent ID: c14c4066-056b-faea-0a28-5eba2c544a43
* Content: [Download - JDBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver16)
* Content Source: [docs/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
Thanks for the heads up! This is fixed now.

Regards,
David

#please-close
