### ISSUE TITLE
Provided script seems to resolve links to incorrect address

### ISSUE THREAD

**Issue by AndersUP** [MicrosoftDocs/sql-docs#9299]
It appears that the at least some of the links in the installer PowerShell Script are incorrect. If I run the script as the docs specify, I get:

[2023-09-04 23:45:20Z] Downloading https://go.microsoft.com/fwlink/?LinkId=852726&clcid=1033 to C:\Users\######\AppData\Local\Temp\SPS_9.2.1.0_1033.cab
Invoke-WebRequest : The remote name could not be resolved: 'rserverdistribution.azureedge.net'
At C:\Temp\Untitled1.ps1:99 char:9
\+         Invoke-WebRequest -Uri $cabUrl -OutFile $cabFile
\+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    \+ CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

I get the same for the link https://go.microsoft.com/fwlink/?LinkId=852723&clcid=1033

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2175e183-b508-c7e4-1caa-65b2adbb3b54
* Version Independent ID: e2ee7575-2be6-6ec7-4b2e-be278da1f2ff
* Content: [Set up a Python data science client - SQL Server Machine Learning Services](https://learn.microsoft.com/en-us/sql/machine-learning/python/setup-python-client-tools-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-ver16)
* Content Source: [docs/machine-learning/python/setup-python-client-tools-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/python/setup-python-client-tools-sql.md)
* Service: **sql**
* Sub-service: **machine-learning-services**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
@AndersUP We have resolved a temporary outage with the fwlinks as they were in need of redirection. Should be resolved now. Thanks very much for bringing this to our attention.
