### ISSUE TITLE
Out of date link

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/sql-docs#9301]
The link to key security concepts should probably point here https://learn.microsoft.com/en-us/dotnet/standard/security/key-security-concepts. Also I don't think MSDN is a thing any more.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a88c18b4-3662-e2d3-0599-e48719e104b1
* Version Independent ID: 8d5b4739-29a6-ce32-7f8b-84c2796f54a9
* Content: [Choose an Encryption Algorithm - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/choose-an-encryption-algorithm?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/encryption/choose-an-encryption-algorithm.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/choose-an-encryption-algorithm.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by WilliamAntonRohm** [comment]
@martingbrown -- Martin, thank you for catching these.  I am updating the article.

**Comment by rwestMSFT** [comment]
I'll take this.

#reassign:rwestMSFT

**Comment by rwestMSFT** [comment]
We have an internal PR that refreshes this article, which will be published in the next few days. Thank you for your feedback, @martingbrown.
