### ISSUE TITLE
User-Assigned Managed Identity and Azure SQL Database

### ISSUE THREAD

**Issue by squarerigger** [MicrosoftDocs/sql-docs#9303]
The article is almost right (Using Active Directory Managed Identity authentication).  However, using the recommended code 'as is' in an environment slightly different than the author's and using two AD entities instead of one in an Azure function app (one for the first step involving a Service Bus, another for more restrictive Azure SQL database access) leads to an inner error and task cancellation when trying to perform the second step (Azure SQL authentication). I have tried six close alternatives using Microsoft docs, with the same inner error exception.

The recommended code fails (each a small variation)
conn = new SqlConnection("Server=<db server goes here>.database.windows.net; Database=<db goes here>; Authentication=Active Directory Default; Encrypt=True; User Id=<User-Assigned Managed Identity Client Id here>"); 
conn = new SqlConnection("Server=<db server goes here>.database.windows.net,1433; Database=<db goes here>; Authentication=Active Directory Default; Encrypt=True; User Id=<User-Assigned Managed Identity Client Id here>"); 
conn = new SqlConnection("Server=tcp:<db server goes here>.database.windows.net; Database=<db goes here>; Authentication=Active Directory Default; Encrypt=True; User Id=<User-Assigned Managed Identity Client Id here>"); 
conn = new SqlConnection("Server=tcp:<db server goes here>.database.windows.net,1433; Database=<db goes here>; Authentication=Active Directory Default; Encrypt=True; User Id=<User-Assigned Managed Identity Client Id here>"); 
conn = new SqlConnection("Server=tcp:<db server goes here>.database.windows.net,1433; Database=<db goes here>; Authentication=Active Directory Default; Encrypt=True; User Id=<User-Assigned Managed Identity Client Id here>; TrustServerCertificate=True"); 

**Bottom line --- the Azure Default credential is failing to switch over to the new Client ID that is provided in the connection string.  Perhaps the ID of the first AD user has been cached and is being used instead of the newly provided id.**

My environment:  a non-domain-connected network (a standalone workstation) using Visual Studio with one Active Directory account logged in, using an Azure function app, succeeding in accessing the Service Bus with the initial AD account, then trying to open Azure SQL database using a different, User-Assigned managed identity.  (Both AD accounts have the required setup in Azure - as evidenced by success when I forced the AD ClientID to be used in the code that follows.)
     Azure.Identity 1.9.0
     Microsoft.Data.SqlClient 5.1.1
     Azure.Core 1.32.0
     Microsoft.Identity.Client 4.49.1
     Microsoft.Identity.Client.Extensions.Msai 2.25.3
     Microsoft.IdentityModel.Abstractions 6.24.0
     Microsoft.IdentityModel.Protocols 6.24.0
     Microsoft.IdentityModel.Protocols.Openidconnect 6.24.0
     Microsoft.IdentityModel.Tokens 6.24.0
     System.IdentityModel.Tokens.Jwt 6.24.0

This article provided code that works:
https://techcommunity.microsoft.com/t5/apps-on-azure-blog/connect-app-service-with-azure-sql-database-with-managed/ba-p/3288300

```
string userAssignedClientId = ""; //Give Client ID of User Managed Identity
var conn = new SqlConnection(connectionString);
var credential = new Azure.Identity.DefaultAzureCredential(new DefaultAzureCredentialOptions { ManagedIdentityClientId = userAssignedClientId });
var token = credential.GetToken(new Azure.Core.TokenRequestContext(new[] { "https://database.windows.net/.default"}));
conn.AccessToken = token.Token;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 947b6a2f-66c5-821d-8c58-8798a48a9f3f
* Version Independent ID: 35874772-4b2c-7679-7fa3-57e77e02fbb0
* Content: [Connect to Azure SQL with Azure AD authentication and SqlClient - ADO.NET Provider for SQL Server](https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16)
* Content Source: [docs/connect/ado-net/sql/azure-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/ado-net/sql/azure-active-directory-authentication.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@squarerigger -- thank you for your well-researched feedback.

@David-Engel -- please look into this issue.

**Comment by David-Engel** [comment]
@squarerigger Please submit this issue over at the [dotnet/SqlClient repo](https://github.com/dotnet/SqlClient/issues). This repo is specifically for documentation issues. They should be able to help you troubleshoot over there and identify any possible issues in the SqlClient library.

Thanks,
David

**Comment by David-Engel** [comment]
Copied this issue to the dotnet/SqlClient repo for further investigation. Closing this one.

#please-close
