### ISSUE TITLE
Correct documentation command | sqlagent.errorfile -> sqlagent.errorlogfile

### ISSUE THREAD

**Issue by tbrucezzi-qontigo** [MicrosoftDocs/sql-docs#9304]
SQL Agent error logs
https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-ver16#agenterrorlog

Wrong command to verify:

- sudo /opt/mssql/bin/mssql-conf set sqlagent.**errorfile** <path> -> **errorlogfile**

Thanks have a nice day!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c0b1027-3982-e114-0230-c6bd9bd81346
* Version Independent ID: 244740de-8817-1671-387d-970f8ee8dfcb
* Content: [Configure SQL Server settings on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-ver16)
* Content Source: [docs/linux/sql-server-linux-configure-mssql-conf.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-mssql-conf.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@tbrucezzi-qontigo -- Thiago, thank you for catching this.  I am updating the article.

**Comment by tbrucezzi-qontigo** [comment]
thanks @WilliamAntonRohm -- I ve just see your updating. lastly, check to update the example of the Bash command, which also has the wrong command.

From:
Bash
`sudo /opt/mssql/bin/mssql-conf set sqlagent.errorfile <path>`

To:
Bash
`sudo /opt/mssql/bin/mssql-conf set sqlagent.errorlogfile <path>`

**Comment by rwestMSFT** [comment]
Hi @tbrucezzi-qontigo, thanks for catching this. I was curious what you meant by "also" in your second comment, because I only see in one place in the file where errorlogfile was mistyped.

**Comment by rwestMSFT** [comment]
We have refreshed the article and it will be published in the next day or so.
