### ISSUE TITLE
Deprecated (???)

### ISSUE THREAD

**Issue by criverar99** [MicrosoftDocs/sql-docs#9305]
[Enter feedback here]
I am trying to install the packages as mentioned in the tutorial for R, but I always get an error about the CRAN mirrors

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62f422c9-ff16-97ad-75ae-9ae9c5a39bcd
* Version Independent ID: 62f422c9-ff16-97ad-75ae-9ae9c5a39bcd
* Content: [Install SQL Server 2022 Machine Learning Services on Windows - SQL Server Machine Learning Services](https://learn.microsoft.com/en-us/sql/machine-learning/install/sql-machine-learning-services-windows-install-sql-2022?view=sql-server-ver16&viewFallbackFrom=sql-server-ver15)
* Content Source: [docs/machine-learning/install/sql-machine-learning-services-windows-install-sql-2022.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/install/sql-machine-learning-services-windows-install-sql-2022.md)
* Service: **sql**
* Sub-service: **machine-learning-services**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hi @criverar99! Can you provide more details and information on the links, and any error messages?

**Comment by rwestMSFT** [comment]
@criverar99 We haven't heard from you for some time, so we are closing this issue. If you have any feedback to share, please feel free to do so in the comment section below. Thank you.
