### ISSUE TITLE
Wrong doc for creating new user using SSMS

### ISSUE THREAD

**Issue by chenwang07** [MicrosoftDocs/sql-docs#9308]
[Enter feedback here]

Right-click the Security folder, point to New, and select **User**....

There is no **User** after you right-click
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4397e125-a658-36a3-f982-a8b29176b738
* Version Independent ID: efef2baf-67e5-4e8e-9164-799c1c234386
* Content: [Create a database user - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/create-a-database-user?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/authentication-access/create-a-database-user.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/create-a-database-user.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @chenwang07 - You'll need to expand a database first, as noted in the instructions. I am closing this issue as it is not a documentation issue.

![image](https://github.com/MicrosoftDocs/sql-docs/assets/40007119/ac897feb-00e1-4b77-afd1-90cad7612468)

**Comment by chenwang07** [comment]
Thanks for your reply!
