### ISSUE TITLE
Database Migration Assistant (DMA) SQL Assessment Console page states minimum req of .NET Core 3.1 but .NET 6.0 is required for SqlAssessment.exe v1.4.0.0 (2023-08-14 build)

### ISSUE THREAD

**Issue by scarson** [MicrosoftDocs/sql-docs#9310]
https://learn.microsoft.com/en-us/sql/dma/dma-sku-recommend-sql-db?view=sql-server-ver16

States:

> **Prerequisites**
> 
> - Download and install the latest version of [DMA](https://aka.ms/get-dma). If you have already an earlier version of the tool, open it, and you'll be prompted to upgrade DMA.
> - Install the minimum version [.NET Core 3.1](https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0) on the tools machine where the SKU recommendations console application is running.
> - Ensure the account used to connect to your SQL Server on-premises source has sysadmin permission.

However, attempting to run the DMA SqlAssessment.exe console application with only .NET Core 3.1 Runtime installed returns the following error:

> It was not possible to find any compatible framework version
> The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
>   - The following frameworks were found:
>       3.1.32 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> 
> You can resolve the problem by installing the specified framework and/or SDK.
> 
> The specified framework can be found at:
>   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=win10-x64

Please update the docs to correctly reference and link to .NET 6 instead.
https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime

Tagging @ajithkr-ms as page owner.

------------------

Edit: It appears it must be exactly .NET 6. Having only .NET 7 Runtime installed returns the following error:

> 
> You must install or update .NET to run this application.
> 
> App: C:\Program Files\Microsoft Data Migration Assistant\SqlAssessmentConsole\SqlAssessment.exe
> Architecture: x64
> Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
> .NET location: C:\Program Files\dotnet\
> 
> The following frameworks were found:
>   7.0.10 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> 
> Learn about framework resolution:
> https://aka.ms/dotnet/app-launch-failed
> 
> To install missing framework, download:
> https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=win10-x64

**Comment by rwestMSFT** [comment]
Thanks, @scarson. We'll have a refreshed article published in the next day or so.
