### ISSUE TITLE
Download SQL Server Management Studio (SSMS)

### ISSUE THREAD

**Issue by kumarmageshr** [MicrosoftDocs/sql-docs#9314]
The Download SQL SSMS link is not working. 
FYI
https://download.microsoft.com/download/a/c/a/aca4e29f-6925-4d50-a06b-5576c6ea629f/SSMS-Setup-ENU.exe

**Comment by WilliamAntonRohm** [comment]
@kumarmageshr -- Mahesh, thank you for your feedback.  That link is working for me.
