### ISSUE TITLE
Missing word in the text

### ISSUE THREAD

**Issue by DWalker07** [MicrosoftDocs/sql-docs#9316]
[Enter feedback here]
The page says "If the batch size is >= 102400, the rows are directly into the compressed rowgroups. "  I think this should say "the rows are _inserted_ directly into..."  Right?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40178a54-5c50-6667-f605-f6c0d75f8741
* Version Independent ID: 9a0b755c-40a0-563a-b945-c0216ae71f7b
* Content: [Columnstore indexes - Data loading guidance - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-data-loading-guidance?view=sql-server-ver16&source=recommendations)
* Content Source: [docs/relational-databases/indexes/columnstore-indexes-data-loading-guidance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/columnstore-indexes-data-loading-guidance.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@DWalker07 -- thank you for catching this.  I am updating the article.

**Comment by rwestMSFT** [comment]
I'll take this. The article needs a refresh. We'll put "loaded" instead of "inserted" to follow earlier use of the term in the article.

Thanks for the feedback!

**Comment by DWalker07** [comment]
Thanks.
