### ISSUE TITLE
Put User is Quotes: "SA" not SA in the bash commands.

### ISSUE THREAD

**Issue by Adrianjewell91** [MicrosoftDocs/sql-docs#9318]
[Enter feedback here]
Put User is Quotes: "SA" not SA in the bash commands.

like so: 
/opt/mssql-tools/bin/sqlcmd -S localhost -U "SA" 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @amitkh-msft
* Microsoft Alias: **amitkh**

**Comment by rwestMSFT** [comment]
Hi @Adrianjewell91, quotation marks are not required for the username for sqlcmd. Please refer to the [sqlcmd article](https://learn.microsoft.com/en-us/sql/tools/sqlcmd/sqlcmd-utility?view=sql-server-ver16&tabs=odbc%2Cwindows#-u-login_id).
