### ISSUE TITLE
Add Edition Required Information for each IQP Feature

### ISSUE THREAD

**Issue by GlennAlanBerry1961** [MicrosoftDocs/sql-docs#9324]
It would be very useful if there was an easy way to tell the required edition for each IQP feature (whether it was Enterprise Edition-only or not). The current breakdown by major version and whether Query Store must be enabled is a good start, but having an easy indication about edition support would improve this page tremendously.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16d91022-0ff5-2a0e-4711-217fd9568018
* Version Independent ID: cd30c087-06e7-f947-cf6a-262001d574a3
* Content: [Intelligent query processing - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/performance/intelligent-query-processing?view=sql-server-ver16)
* Content Source: [docs/relational-databases/performance/intelligent-query-processing.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/intelligent-query-processing.md)
* Service: **sql**
* Sub-service: **performance**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@GlennAlanBerry1961 -- Glenn, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by rwestMSFT** [comment]
@GlennAlanBerry1961 We like this idea, but we have a lot of other things to get to before we can nail this one down. I'm going to close it, but we'll track the issue internally.

AB#70883
