### ISSUE TITLE
Wait Stats Applies to for CX waits

### ISSUE THREAD

**Issue by erikdarlingdata** [MicrosoftDocs/sql-docs#9327]
Hello and thank you for joining my podcast.

On this page: https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-wait-stats-transact-sql?view=sql-server-ver16

The waits `CXSYNC_PORT` and `CXROWSET_SYNC` both have "Applies to: Azure SQL Database, Azure SQL Managed Instance"

However, this episode's sponsor, SQL Server 2022, has both of those wait types in the `dm_os_wait_stats` DMV, and are generated by parallel queries executing.

I believe the "Applies to" section requires an update to reflect this, because it would be weird even for Microsoft to have wait stats mean different things between cloud and box products.

Like and subscribe,
Erik

**Comment by WilliamAntonRohm** [comment]
@erikdarlingdata -- Erik, thank you for your fun and actionable feedback.

@rwestMSFT -- Randolph, please look into this issue.

**Comment by rwestMSFT** [comment]
Thanks for the feedback. We'll have a refreshed article published in the next day or so.

**Comment by erikdarlingdata** [comment]
I look forward to refreshments.
