### ISSUE TITLE
Not sure what to do 

### ISSUE THREAD

**Issue by OCDCyclist** [MicrosoftDocs/sql-docs#9334]
I am directed to this page after clicking a link in Sql Server Mgt Studio to update my local copy.  I have no idea what to do and do not want to read a long document and ponder what is the right thing to do.

So as usual I don't update.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
@OCDCyclist What information would help you determine what is the right thing to do?

**Comment by rwestMSFT** [comment]
@OCDCyclist You have two options:

- If the version you already have installed, has a major version of v19.x, then you can download the latest version and run the installer (make sure SSMS is closed when you do this).

- If the version you already have installed, has an older major version (v18 or earlier), you must uninstall that version from your computer first.

This information is noted in the article, under the **[Download SSMS](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16#download-ssms)** heading:

> The SSMS 19.x installation doesn't upgrade or replace SSMS versions 18.x or earlier. SSMS 19.x installs alongside previous versions, so both versions are available for use. However, if you have an earlier preview version of SSMS 19 installed, you must uninstall it before installing SSMS 19.1. You can see if you have a preview version by going to the Help > About window.

![CleanShot 2023-09-21 at 18 39 00@2x](https://github.com/MicrosoftDocs/sql-docs/assets/97149825/f617c57e-8a16-48aa-ad91-fc0b2b758135)

I hope that helps!
