### ISSUE TITLE
Known issue for ODBC driver

### ISSUE THREAD

**Issue by juresaht2** [MicrosoftDocs/sql-docs#9336]
https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/known-issues-in-this-version-of-the-driver

The Microsoft ODBC driver uses glibc gconv to convert character sets. However there is no dependency on the package and the driver simply fails with the error "`[Microsoft][ODBC Driver 17 for SQL Server]Unicode conversion failed`", if the necessary gconv modules are not installed!

On some operating systems, the `glibc` package already contains all the necessary gconv modules to convert from the typical character sets, however on other operating systems only ANSI C UTF-8 support is built-in and the other gconv modules are provided by the `glibc-gconv-extra package`.

This could be considered a bug in the Microsoft ODBC driver because of the missing dependency, however it's true that change in the packages is relatively recent.

Maybe add this to your known issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ffb43d90-0ed6-d1f0-9351-b8693c5a92d8
* Version Independent ID: f3a3141d-7a59-192a-6a09-e81143612f65
* Content: [Known issues for the ODBC driver on Linux and macOS - ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/known-issues-in-this-version-of-the-driver?view=sql-server-ver16)
* Content Source: [docs/connect/odbc/linux-mac/known-issues-in-this-version-of-the-driver.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/known-issues-in-this-version-of-the-driver.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
> ... on other operating systems only ANSI C UTF-8 support is built-in and the other gconv modules are provided by the `glibc-gconv-extra package`.

@juresaht2 Which operating systems is this an issue on? Any of the ones from the list of [supported operating systems](https://learn.microsoft.com/sql/connect/odbc/linux-mac/system-requirements#operating-system-support)?

Thanks,
David

**Comment by juresaht2** [comment]
Different RHEL8 and RHEL9 compatible systems, which are on your list.

**Comment by David-Engel** [comment]
> Different RHEL8 and RHEL9 compatible systems, which are on your list.

@juresaht2 

"RHEL8 and RHEL9 compatible" but NOT actually RHEL8 or RHEL9? Are there actual RHEL8 or RHEL9 systems where this is an issue? There are a lot of Linux distributions that are "compatibile" with major distros, but they may contain subtle differences like this. We can't test or certify them all. We would only add a known issue for a system that is on the list of supported operating systems.

Regards,
David

**Comment by juresaht2** [comment]
Suit yourself.

**Comment by WilliamAntonRohm** [comment]
@juresaht2 -- Jure, thank you for your followup.  I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
