### ISSUE TITLE
Should the page be updated to cover SQL 2019 CU22 now it has been released?

### ISSUE THREAD

**Issue by LorraineBigmore** [MicrosoftDocs/sql-docs#9337]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9ff3c86-865f-9cbb-1d0a-2248149f4c87
* Version Independent ID: 12963cad-1c8a-d3f4-7b44-3fcd56206393
* Content: [CAB download updates for offline install - SQL Server Machine Learning Services](https://learn.microsoft.com/en-us/sql/machine-learning/install/sql-ml-cab-downloads?view=sql-server-ver15)
* Content Source: [docs/machine-learning/install/sql-ml-cab-downloads.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/install/sql-ml-cab-downloads.md)
* Service: **sql**
* Sub-service: **machine-learning-services**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@LorraineBigmore -- Lorraine, thank for your question.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @LorraineBigmore, nice catch. The CABs are unchanged since CU16, we've updated this page to reflect that. Appreciate you taking the time to bring this to our attention. A doc update is in flight.
