### ISSUE TITLE
SEMANTICSIMILARITYTABLE  results are limited to 10 records?

### ISSUE THREAD

**Issue by mg8811** [MicrosoftDocs/sql-docs#9338]
Seems that SEMANTICSIMILARITYTABLE returns max of 10 records.
I've loaded over 600K documents (pdf,doc,docx)  response is very quick .. but always <=10 records.
I've found a single comment on stackoverflow.com regarding this being an issue in SQL 2012.

**Comment by WilliamAntonRohm** [comment]
@mg8811 -- thank you for your feedback.  Are you following a particular learn.microsoft.com article?  Meanwhile, please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)

**Comment by rwestMSFT** [comment]
@mg8811 We haven't heard from you in over a week. Please will you respond with the article you're referencing, so we can investigate further.

**Comment by mg8811** [comment]
Apologies evidently, I stopped getting notification :<

Managed to piece together a test system from various articles.
Even the simplest example

```
Declare @hids  AS hierarchyid
select @hids=path_locator from docsFS where name='401386.446feb4d-cedb-440d-b26e-5d9b2c445696.pdf'

SELECT TOP(100) *
FROM SEMANTICSIMILARITYTABLE(Docsfs, file_stream, @hids)
go

returns a max of 10 records 
I've deliverately loaded duplicates and still only get 10 rows back  score .9999  down to .24



```returns 10 records max

**Comment by WilliamAntonRohm** [comment]
@mg8811 -- please specify which articles.

**Comment by mg8811** [comment]
mainly 
https://www.mssqltips.com/sqlservertip/2769/sql-server-semantic-search-to-find-text-in-external-files/
and
https://codingsight.com/store-and-analyse-documents-on-windows-file-system-with-sql-server-semantic-search-part-1/

Loaded 600K  PDF files (after correctly installing PDF ifilter for SQL (hints from
https://dba-presents.com/databases/sql-server/48-full-text-search-with-pdf-documents-in-sql-server-2014
and
 https://social.msdn.microsoft.com/Forums/sqlserver/en-US/69535dbc-c7ef-402d-a347-d3d3e4860d72/sql-server-2008-64bit-fulltext-indexing-pdf-not-working-cant-find-ifilter?forum=sqldatabaseengine 

Full text Search works so does  SEMANTICSIMILARITYTABLE  (but with 10 result limit )

I've implemented a solution using https://lucenenet.apache.org/   years ago, so am familiar with the topic.

**Comment by rwestMSFT** [comment]
@mg8811 This is the Database Docs repository. @WilliamAntonRohm was asking which articles in the Database Docs repo (under `https://learn.microsoft.com/sql`) you were referencing.

That being said, this sounds like a bug in the product, and I would like to encourage you to open a support ticket with the product team. Without referencing a specific article in our repository, this issue isn't going to be escalated, and is likely to be closed.

Thank you for your understanding.

**Comment by mg8811** [comment]
issue seems be a bug going back to SQL 2012 /2014
https://stackoverflow.com/questions/32392738/how-many-rows-does-semanticsimilaritytable-produce
Thank you.

**Comment by mg8811** [comment]
issue seems be a bug going back to SQL 2012 /2014
https://stackoverflow.com/questions/32392738/how-many-rows-does-semanticsimilaritytable-produce
Chances of it being fixed is near 0 so I'll abandon any plans to switch from Lucene to SQL
Thanks out.

**Comment by rwestMSFT** [comment]
@mg8811 If you open a bug report, you would be doing everyone a favour. I'd encourage you to consider it.
