### ISSUE TITLE
Requirements for VC redistributable may be confusing.

### ISSUE THREAD

**Issue by krasoluta** [MicrosoftDocs/sql-docs#9341]
In a note, a requirement states: 
"You must install both the x86 and x64 versions of the C++ redistributable package to use the OLE DB driver with 32-bit programs."

This could be understood to mean that if you don't install the x86 version of the VC redistributable, you won't be able to use OLEDB with 32-bit programs.  The implication is that if you don't intend on using 32-bit programs + OLEDB then you don't need to download the x86 VC redistributable.

This is false.  I had to install both versions of the VC redistributable in order for the OLEDB driver to install at all.

I would suggest an edit to the following:

"You must install both the x86 and x64 versions of the C++ redistributable package to install and use the OLE DB driver."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5f6f81a-974a-c224-8331-1633c8e39b7e
* Version Independent ID: fcca32ef-3cbe-ad6d-688b-96f7726d62af
* Content: [Download Microsoft OLE DB Driver for SQL Server - OLE DB Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/oledb/download-oledb-driver-for-sql-server?view=sql-server-2017)
* Content Source: [docs/connect/oledb/download-oledb-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/oledb/download-oledb-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
Thanks for the suggestion. I adjusted the wording of the note to: "You must install both the x86 and x64 versions of the C++ redistributable package to install the x64 OLE DB driver package." The change should be reflected in a few hours.

Thanks,
David

#please-close
