### ISSUE TITLE
2022 document uses 2016 illustrations

### ISSUE THREAD

**Issue by stacker60** [MicrosoftDocs/sql-docs#9343]
[Enter feedback here]
All pictures on this page refer to Sql Server 2016. They should show Sql Server 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 916e128d-19fd-1f7d-8285-6313c4419710
* Version Independent ID: 8402af42-fdd1-2f3b-7c6a-8759e90e115f
* Content: [Choose a database engine upgrade method - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/install-windows/choose-a-database-engine-upgrade-method?view=sql-server-ver16)
* Content Source: [docs/database-engine/install-windows/choose-a-database-engine-upgrade-method.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/choose-a-database-engine-upgrade-method.md)
* Service: **sql**
* Sub-service: **install**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@stacker60 -- thank you for your feedback.

@rwestMSFT -- please look into this issue.

**Comment by rwestMSFT** [comment]
Thanks for the feedback. In the text we say "2016 and later versions", and the images just show 2016 as an example. We'll look at this when we have time.

**Comment by rwestMSFT** [comment]
AB#70883

**Comment by rwestMSFT** [comment]
@stacker60 We have an internal PR that will publish in the next day or so with updated images, and a refreshed article. Once again, we appreciate your feedback!
