### ISSUE TITLE
Confusing example for token syntax

### ISSUE THREAD

**Issue by shnja** [MicrosoftDocs/sql-docs#9344]
The example in section [C. Using tokens with the ESCAPE_NONE macro](https://learn.microsoft.com/en-us/sql/ssms/agent/use-tokens-in-job-steps?view=sql-server-ver16#c-using-tokens-with-the-escape_none-macro) has issues.

![image](https://github.com/MicrosoftDocs/sql-docs/assets/32129682/6e07fd8d-14a4-434a-96af-7a32d0495716)

You don't need to retrieve the `job_id` from the `sysjobs` table because you have `JOBID`, so just SET it.

```sql
SET @JobID = CONVERT(uniqueidentifier, $(ESCAPE_NONE(JOBID)))
```

`@JobID` won't be populated anyway in the `WHERE` and the `SELECT` will either return no rows because `@JobID` has not been set or all `sysjobs` if it equals `JOBID`.

Also why declare `@JobID` as a binary type and cause an implicit conversion if you know you're going to convert to uniqueidentifier.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3c73e6a-0759-dbb7-c244-efd613675e72
* Version Independent ID: 36c8ba73-85f3-3150-f7c0-69c6287766ea
* Content: [Use Tokens in Job Steps - SQL Server Agent](https://learn.microsoft.com/en-us/sql/ssms/agent/use-tokens-in-job-steps?view=sql-server-ver16)
* Content Source: [docs/ssms/agent/use-tokens-in-job-steps.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/use-tokens-in-job-steps.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@shnja -- thank you for your thorough feedback.

@markingmyname -- please look into this issue.
