### ISSUE TITLE
How to authenticate through Azure Cli Credentials

### ISSUE THREAD

**Issue by serge-portima** [MicrosoftDocs/sql-docs#9345]
The documentation doesn't make it clear how to authenticate with Azure Cli Credentials.

Is it a variation of the "Active Directory Service Principal"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 947b6a2f-66c5-821d-8c58-8798a48a9f3f
* Version Independent ID: 35874772-4b2c-7679-7fa3-57e77e02fbb0
* Content: [Connect to Azure SQL with Azure AD authentication and SqlClient - ADO.NET Provider for SQL Server](https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver15)
* Content Source: [docs/connect/ado-net/sql/azure-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/ado-net/sql/azure-active-directory-authentication.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
@serge-portima Azure Active Directory authentication can be confusing. To start, you need to understand that there are many ways applications can authenticate to Azure AD. On top of that, some applications offer a way for other apps to use their Azure AD authentication token. This is what Azure CLI does. Azure CLI authenticates to Azure AD and saves that authentication in a way that other apps can take advantage of it, so those apps don't have to authenticate directly to Azure AD themselves. Most of the SqlClient Authentication options are for direct authentication to Azure AD, not via another app's token. The exception is `Authentication = Active Directory Default`. That one currently offers a way to take advantage of Azure CLI's auth token via a simple SqlClient connection option. For details, it's in this section of the page you referenced (search for Azure CLI): [Using Active Directory Default authentication](https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver15#using-active-directory-default-authentication)

Perhaps an unstated assumption in the doc is that you first need to be authenticated via Azure CLI (or any of the chained token acquisition methods) before trying to make a connection using Active Directory Default. https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli

Regards,
David

**Comment by serge-portima** [comment]
The issue with `Authentication = Active Directory Default` is, Azure CLI credential will come last in chain and attempts to use Managed identity will cause an Exception in some environments (eg: Azure Devops pipeline w/o MSI support).

Now, I rely on getting the token within the code and set it to the SQL Connection, but knowing it could be achieved through 'Authentication = xxx' make clear it should not be mandatory anymore.

**Comment by David-Engel** [comment]
> The issue with `Authentication = Active Directory Default` is, Azure CLI credential will come last in chain and attempts to use Managed identity will cause an Exception in some environments (eg: Azure Devops pipeline w/o MSI support).
> 
> Now, I rely on getting the token within the code and set it to the SQL Connection, but knowing it could be achieved through 'Authentication = xxx' make clear it should not be the only way anymore.

As an alternative, you can define and register your own authentication provider and override one of the built-in authentication options. For example, you could override the `Authentication=Active Directory Default` option to use a provider you register. Your provider can use the Azure Identity library's [AzureCLICredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.azureclicredential?view=azure-dotnet) and simply pass that to SqlClient. Details on how to create a custom provider are here:
https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16#support-for-a-custom-sql-authentication-provider

Finally, in Microsoft.Data.SqlClient 5.2 preview 3, there is a new SqlConnection.AccessTokenCallback property that is simpler to set up than a custom provider. Here's an example:

```cs
using Azure.Core;
using Azure.Identity;
using Microsoft.Data.SqlClient;
...

            string s_defaultScopeSuffix = "/.default";
            var cred = new AzureCliCredential();
            Func<SqlAuthenticationParameters, CancellationToken, Task<SqlAuthenticationToken>> myTokenCallback = async (ctx, cancellationToken) =>
            {
                string scope = ctx.Resource.EndsWith(s_defaultScopeSuffix) ? ctx.Resource : ctx.Resource + s_defaultScopeSuffix;
                AccessToken token = await cred.GetTokenAsync(new TokenRequestContext(new[] { scope }), cancellationToken);
                return new SqlAuthenticationToken(token.Token, token.ExpiresOn);
            };

            using (SqlConnection sqlConnection = new SqlConnection("Server=name.database.windows.net;Database=db;"))
            {
                sqlConnection.AccessTokenCallback = myTokenCallback;
                sqlConnection.Open();
                Console.WriteLine("Connected successfully!");
            }
```

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by serge-portima** [comment]
> > The issue with `Authentication = Active Directory Default` is, Azure CLI credential will come last in chain and attempts to use Managed identity will cause an Exception in some environments (eg: Azure Devops pipeline w/o MSI support).
> > Now, I rely on getting the token within the code and set it to the SQL Connection, but knowing it could be achieved through 'Authentication = xxx' make clear it should not be the only way anymore.
> 
> As an alternative, you can define and register your own authentication provider and override one of the built-in authentication options. For example, you could override the `Authentication=Active Directory Default` option to use a provider you register. Your provider can use the Azure Identity library's [AzureCLICredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.azureclicredential?view=azure-dotnet) and simply pass that to SqlClient. Details on how to create a custom provider are here: https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16#support-for-a-custom-sql-authentication-provider
> 
> Finally, in Microsoft.Data.SqlClient 5.2 preview 3, there is a new SqlConnection.AccessTokenCallback property that is simpler to set up than a custom provider. Here's an example:
> 
> ```cs
> using Azure.Core;
> using Azure.Identity;
> using Microsoft.Data.SqlClient;
> ...
> 
>             string s_defaultScopeSuffix = "/.default";
>             var cred = new AzureCliCredential();
>             Func<SqlAuthenticationParameters, CancellationToken, Task<SqlAuthenticationToken>> myTokenCallback = async (ctx, cancellationToken) =>
>             {
>                 string scope = ctx.Resource.EndsWith(s_defaultScopeSuffix) ? ctx.Resource : ctx.Resource + s_defaultScopeSuffix;
>                 AccessToken token = await cred.GetTokenAsync(new TokenRequestContext(new[] { scope }), cancellationToken);
>                 return new SqlAuthenticationToken(token.Token, token.ExpiresOn);
>             };
> 
>             using (SqlConnection sqlConnection = new SqlConnection("Server=name.database.windows.net;Database=db;"))
>             {
>                 sqlConnection.AccessTokenCallback = myTokenCallback;
>                 sqlConnection.Open();
>                 Console.WriteLine("Connected successfully!");
>             }
> ```

Thank you, I had something similar at SqlConnection creation.

I guess this method will only be called when a new token is needed (not when one is cached and still valid).

I'll try it as soon as 5.2 gets released :)
