### ISSUE TITLE
Update the Doc from Azure AD to Entra ID

### ISSUE THREAD

**Issue by NandanHegde15** [MicrosoftDocs/sql-docs#9350]
https://learn.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-configure?view=azuresql&tabs=azure-powershell

Still old :
<img width="451" alt="image" src="https://github.com/MicrosoftDocs/sql-docs/assets/67547199/d8483823-365e-496f-a9b1-8934d30bebbf">

latest : 
<img width="744" alt="image" src="https://github.com/MicrosoftDocs/sql-docs/assets/67547199/d1035e31-8188-49f8-b4d3-c6c22f896f3f">

**Comment by rwestMSFT** [comment]
Hi @NandanHegde15, we have an internal project going on right now to resolve this. I am closing this issue, but we definitely appreciate your submission.
