### ISSUE TITLE
Missing SQL 2022 on table for section Using SQL Server Side-By-Side with Previous Versions of SQL Server

### ISSUE THREAD

**Issue by iggonzalezMS** [MicrosoftDocs/sql-docs#9352]
[Enter feedback here]
On this section Using SQL Server Side-By-Side with Previous Versions of SQL Server, all SQL server are detailed but not SQL Server 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c5b2d5d-0a6b-46e2-cb87-be75e37c538f
* Version Independent ID: 66e80689-5e06-fd53-bfdd-75058533df10
* Content: [Work with multiple versions and instances - SQL Server](https://learn.microsoft.com/en-gb/sql/sql-server/install/work-with-multiple-versions-and-instances-of-sql-server?view=sql-server-ver16)
* Content Source: [docs/sql-server/install/work-with-multiple-versions-and-instances-of-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/work-with-multiple-versions-and-instances-of-sql-server.md)
* Service: **sql**
* Sub-service: **install**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@iggonzalezMS Thanks, we'll have a refreshed article published in the next day or so.
