### ISSUE TITLE
Database identifiers doc does not mention how to escape delimiters

### ISSUE THREAD

**Issue by nathan-at-delphix** [MicrosoftDocs/sql-docs#9363]
The Database identifiers document could benefit from showing how to escape delimiter characters that are part of a delimited identifier.

For example:

`SELECT KeyCol FROM [dbo].[table_with_[]]_brackets];` for an object named `table with [] brackets` using brackets as a delimiter
`SELECT KeyCol FROM "dbo"."""table with lots of "" quotes""";` for an object named `"table with lots of " quotes"` using quotes as a delimiter

While I would hope that nobody ever has to deal with an object where that's needed, I can't find this clearly referenced elsewhere in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76dc89ee-79b3-9175-fcbd-0115d0b8d00d
* Version Independent ID: 402a20bb-727f-5681-f288-471aa9cb6b50
* Content: [Database identifiers - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers?view=sql-server-ver16)
* Content Source: [docs/relational-databases/databases/database-identifiers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/database-identifiers.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@nathan-at-delphix -- Nathan, thank you for your clear feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Thanks for taking the time to provide this feedback, @nathan-at-delphix. We'll consider this type of content on edge case naming in future updates to this article.
