### ISSUE TITLE
Explain how uniqueidentifier comparison works

### ISSUE THREAD

**Issue by Socolin** [MicrosoftDocs/sql-docs#9369]
Hello,

in this page of documentation: https://learn.microsoft.com/en-us/sql/t-sql/data-types/uniqueidentifier-transact-sql?view=sql-server-ver16

It says:
> However, ordering is not implemented by comparing the bit patterns of the two values

How ordering is working ? Can you detail this.

I'm trying to iterate over a large database with UUID as PK and I would like to iterate over them like `WHERE Id LIKE '0000%'` but if the PK is not ordered this way it may not be the most effective way of doing things.

**Comment by rwestMSFT** [comment]
@Socolin Thanks for your question.

I'll check with the product team in the meantime, but there's a chance we may not be able to document the internal implementation detail.

**Comment by rwestMSFT** [comment]
@Socolin Unfortunately we aren't able to document the internal implementation details. Hopefully in the time since you asked, you were able to build a suitable testing process that helped you resolve your question.

**Comment by rwestMSFT** [comment]
Ordering shouldn't be affected by version, because GUIDs have always been ordered on the final segment (which used to be based on the MAC address before v4 of the GUID format was adopted). As far as I am aware, the ordering implementation hasn't changed, but it might in future versions.
