### ISSUE TITLE
Needs clarity on Azure VMware Service (AVS) approach.

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/sql-docs#9371]
This doc needs clarity on Azure VMware Service (AVS) approach.
It doesn't make sense that these would have Arc installed but then need to take a disconnected approach.
This documentation should walk through a dedicated approach for SQL VMs on AVS

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd3e29e8-6559-58d3-27a5-3c443bd76c94
* Version Independent ID: 37b33566-6d93-ca52-7f54-4101ddb3a332
* Content: [What are Extended Security Updates? - SQL Server](https://review.learn.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-extended-security-updates?view=sql-server-ver16&tabs=portal)
* Content Source: [docs/sql-server/end-of-support/sql-server-extended-security-updates.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/end-of-support/sql-server-extended-security-updates.md)
* Service: **sql**
* Sub-service: **install**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@thommck I believe your request is being addressed internally. I'm closing this for now.
