### ISSUE TITLE
Left menu for article

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/sql-docs#9372]
Hi,
 
The left menu for [Disconnect your SQL Server from Azure Arc - SQL Server | Microsoft Learn](https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/delete-from-azure-arc?view=sql-server-ver16&tabs=azure) shows **Delete from or restore to Azure Arc**. The article has no mention of restore. Would **Disconnect from Azure Arc** or **Disconnect and unregister from Azure Arc** better convey the article's content in the left menu?
 
Cannot contribute to left menu myself.
 
Thank you, inge
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4646c89b-b0b8-0f72-4274-4b73730d58d7
* Version Independent ID: 4646c89b-b0b8-0f72-4274-4b73730d58d7
* Content: [Disconnect your SQL Server from Azure Arc - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/delete-from-azure-arc?view=sql-server-ver16&tabs=azure)
* Content Source: [docs/sql-server/azure-arc/delete-from-azure-arc.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/azure-arc/delete-from-azure-arc.md)
* Service: **sql**
* Sub-service: **azure-arc-sql-server**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rwestMSFT** [comment]
Yes, please do an internal PR to edit the table of contents.
