### ISSUE TITLE
Some changes take effect immediately - without services restart

### ISSUE THREAD

**Issue by gregsohl** [MicrosoftDocs/sql-docs#9387]
Was changing from a Dynamic Port to a specific port in the IPAll section today. The existing values were:
TCP Dynamic Ports: 61643
TCP Port: <blank>

I changed to 
TCP Dynamic Ports: <blank>
TCP Port: 1433

I did not restart the SQL Service, planning to do that later tonight on a announced and planned schedule.

However connectivity broke for some connections immediately. 

1. Used a Test.UDL file to test connection from a client computer - that would not connect
2. Some connections using a connection string with "Provider=SQLOLEDB;......" would not connect.

I changed the values back - again without restarting the SQL Service and all client connectivity worked again.

This seems contrary to both the documentation and what the SQL Server Configuration Manager says on screen when pressing OK or Apply, that the changes only take effect when restarting the SQL Service.

Greg

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f87e4050-237e-5627-ef13-d6e1fdd5b5f9
* Version Independent ID: 9830edce-9e1d-1ce2-2e5c-a393215e35b6
* Content: [Configure SQL Server to listen on a specific TCP port - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@gregsohl Thanks for your feedback.

This behaviour is documented, in a yellow alert box titled **Warning**. My highlighting is added in italics.

> The Database Engine begins listening on a new port when restarted. *However the SQL Server Browser service monitors the registry and reports the new port number as soon as the configuration is changed, even though the Database Engine might not be using it.* Restart the Database Engine to ensure consistency and avoid connection failures.

I am closing this issue.

**Comment by gregsohl** [comment]
Thanks very much!
