### ISSUE TITLE
Please update this page and include some screenshots

### ISSUE THREAD

**Issue by Frankd4** [MicrosoftDocs/sql-docs#9389]
[Enter feedback here]

Hi Team

This is a very common question for Azure SQL Database from CX, please include some screenshots to show the export & import to .bacpac.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9d185ed-733f-2f63-2c28-e63670053b7d
* Version Independent ID: eebf764e-3c26-00f1-c627-03098efe1743
* Content: [Export a Data-tier Application - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/data-tier-applications/export-a-data-tier-application?view=sql-server-ver16)
* Content Source: [docs/relational-databases/data-tier-applications/export-a-data-tier-application.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/data-tier-applications/export-a-data-tier-application.md)
* Service: **sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @Frankd4 for taking the time to provide this feedback, your suggestions help improve our documentation. We'll consider this for a future refresh to this article.

Is there a specific step or set of steps that are most confusing without a visual aid? Is there a specific part of the interface that is confusing?

**Comment by Frankd4** [comment]
Hi @WilliamDAssafMSFT

Thank you. Yes, the UI screenshots makes it easier and quicker to understand than the steps here
- Use the Export Data-tier Application Wizard. CX's ask this type of questions many times, but there are not screenshots so need to explain in more detail the options to select and perform the import/export.

**Comment by WilliamDAssafMSFT** [comment]
#reassign:markingmyname

**Comment by markingmyname** [comment]
@Frankd4

This is an acceptable request.

We are planning on adding some images for the wizard to the article.  ETA early next week.

Also, it is on the roadmap to update this article further in het future.

**Comment by Frankd4** [comment]
Thank you @markingmyname
