### ISSUE TITLE
sql-server 2019 latest doesn't define mssql group

### ISSUE THREAD

**Issue by andreas-ibm** [MicrosoftDocs/sql-docs#9403]
This is kinda related to Issue #6575, answered by @WilliamAntonRohm ...

The quickstart tutorial at https://learn.microsoft.com/en-us/sql/linux/quickstart-sql-server-containers-azure?view=sql-server-ver16&tabs=kubectl mentions:

> securityContext: Defines privilege and access control settings for a pod or container. In this case, it's specified at the pod level, so all containers adhere to that security context. In the security context, we define the fsGroup with the value 10001, which is the Group ID (GID) for the mssql group. This value means that all processes of the container are also part of the supplementary GID 10001 (mssql). The owner for volume /var/opt/mssql and any files created in that volume will be GID 10001 (the mssql group).

Which work nicely if it were true! ;-p

Looking at `/etc/group` on the system:
```
mssql@mssqlinst:/$ cat /etc/group
root:x:0:
daemon:x:1:
bin:x:2:
sys:x:3:
adm:x:4:
tty:x:5:
disk:x:6:
lp:x:7:
mail:x:8:
news:x:9:
uucp:x:10:
man:x:12:
proxy:x:13:
kmem:x:15:
dialout:x:20:
fax:x:21:
voice:x:22:
cdrom:x:24:
floppy:x:25:
tape:x:26:
sudo:x:27:
audio:x:29:
dip:x:30:
www-data:x:33:
backup:x:34:
operator:x:37:
list:x:38:
irc:x:39:
src:x:40:
gnats:x:41:
shadow:x:42:
utmp:x:43:
video:x:44:
sasl:x:45:
plugdev:x:46:
staff:x:50:
games:x:60:
users:x:100:
nogroup:x:65534:
```
whilst the `mssql` user is defined as:
```
mssql:x:10001:0::/home/mssql:/bin/bash
```
So it's defining the `uid` to 10001 but `gid` to `0` (root).

So now I can't run things like:
```
$ /opt/mssql/bin/mssql-conf get network.tlscert
Warning: could not create log file for mssql-conf at /var/opt/mssql/log/mssql-conf/mssql-conf.log.
This program must be run as superuser or as a user with membership in the mssql
group.
```

This might indeed be a product issue rather than documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 652c3fee-c6a9-f163-a281-6e2ae73da6f5
* Version Independent ID: 8b88a92e-0d8d-d2b2-2a37-e96565a71045
* Content: [Quickstart: Deploy a SQL Server container cluster on Azure - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-sql-server-containers-azure?view=sql-server-ver16&tabs=kubectl)
* Content Source: [docs/linux/quickstart-sql-server-containers-azure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-sql-server-containers-azure.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by amitkh-msft** [comment]
thanks @andreas-ibm for the feedback and raising the issue, let me take a look at this and update you on the same

**Comment by rwestMSFT** [comment]
Correct, this is not a documentation issue. I'll echo @amitkh-msft and thank you for raising the issue. I'm closing this, as it isn't a documentation issue, but we are tracking it internally.

AB#70883

**Comment by andreas-ibm** [comment]
Thanks,
As a final comment, to get further with the current image, you can define a custom configmap adding the missing line to /etc/group and add it as a volume mount to the pod and hey presto you can run the mssql-conf command again!
