### ISSUE TITLE
SSMS 19.1 requires .NET Framework 4.7.2 but this is not documented

### ISSUE THREAD

**Issue by ofortun** [MicrosoftDocs/sql-docs#9404]
[SQL Server Management Studio 19.1](https://www.catalog.update.microsoft.com/Search.aspx?q=SQL%20Server%20Management%20Studio%2019.1) is being deployed via Configuration Manager to update SSMS 19 installations to this latest version. The SSMS 19.1 update fails to install on Windows Server 2016 if the original .NET Framework is still installed (2016 comes with version 4.6.2).

SSMS documentation says that Server 2016 is compatible, but there is no documentation for a minimum .NET Framework.

From the setup logs under %temp%\SsmsSetup:
Condition 'NETFRAMEWORK45 >= "461808"' evaluates to false.
.NET Framework 4.7.2 (or greater) is not detected on this machine. Please install it and run this installer again.
Error 0x81f40001: Bundle condition evaluated to false: NETFRAMEWORK45 >= "461808"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16&tabs=command-line)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
@ofortun can you confirm what you mean by "deployed via Configuration Manager".  I think of SQL Server Configuration Manager, and there is no capability to deploy SSMS from there.  Can you provide a screenshot maybe?  Thanks.

**Comment by cuellartech** [comment]
@erinstellato-ms 

By Configuration Manager, he means the updates are deployed from ConfiMgr/WSUS, this specific KB is [KB5027595](https://www.catalog.update.microsoft.com/Search.aspx?q=kb5027595)

![image](https://github.com/MicrosoftDocs/sql-docs/assets/60406960/a98804a5-66e3-49e8-af41-b23b5238f07e)

**Comment by rwestMSFT** [comment]
I will add a note to the system requirement section, to state that .NET Framework 4.7.2 is required on Windows Server 2016.

Thanks for your feedback.
