### ISSUE TITLE
Give your rule a name so you can identify it quickly.

### ISSUE THREAD

**Issue by ngluva** [MicrosoftDocs/sql-docs#9405]
[Give your rule a name so you can identify it quickly. is not part of the "add new app" so from this point on the docs are wrong.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24e49fc4-1101-0d6f-e16a-52242616287b
* Version Independent ID: df5e0042-2137-3309-a957-de5f556f5c84
* Content: [Lesson 2: Connecting from Another Computer - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/lesson-2-connecting-from-another-computer?view=sql-server-ver16)
* Content Source: [docs/relational-databases/lesson-2-connecting-from-another-computer.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/lesson-2-connecting-from-another-computer.md)
* Service: **sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@ngluva -- Malcolm, thank you for your feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by rwestMSFT** [comment]
I've reviewed this issue several times, and I don't understand what you're saying.

The article says that if you need to add an app through the firewall, select the app, or create a new rule if it doesn't exist. The instructions are correct for adding a custom rule. If you need to add an application, and it's in the list, that's where you stop in the process.

Can you help me understand where your confusion is?

**Comment by rwestMSFT** [comment]
We're making a small change to the article. It will say "skip to step 12" if you don't need to add a custom rule.

When this internal PR is merged, the issue will automatically close, and the updated article will be published in the next day or so.
