### ISSUE TITLE
Updating backup storage redundancy on existing instance

### ISSUE THREAD

**Issue by akikawa1123** [MicrosoftDocs/sql-docs#9407]
Updating backup storage redundancy on existing instance can be supported now. This sentence is confusing. 

<img width="331" alt="quickstart" src="https://github.com/MicrosoftDocs/sql-docs/assets/87466397/51a1fc41-7bf2-46eb-bc96-891b39cf8e1a">

https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/instance-create-quickstart?view=azuresql-mi

**Comment by MashaMSFT** [comment]
Hi @akikawa1123 , thanks for bringing this to our attention! I've processed a change to get this fixed and it'll be live later this week :) I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks!
Masha from the SQL Docs team
#please-close
