### ISSUE TITLE
The image shows 5 nodes, while there is description only for 4

### ISSUE THREAD

**Issue by jmadhanraj** [MicrosoftDocs/sql-docs#9408]
The key diagram shows nodes in the availability group, there are 5. But in the tabular column below and subsequent description there is only 4 nodes discussed

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47fd1979-b6af-5ffc-fc7e-31e2b34fe207
* Version Independent ID: 33956f4f-e50c-94d3-b996-187bf71c1ec4
* Content: [What is an Always On availability group? - SQL Server Always On](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server?view=sql-server-ver16)
* Content Source: [docs/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server.md)
* Service: **sql**
* Sub-service: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by rwestMSFT** [comment]
@jmadhanraj The diagram and content both refer to a single primary replica, and four secondary replicas. Does that help your understanding better?

**Comment by rwestMSFT** [comment]
I am closing this issue, as I don't believe there is a problem with the article in question. You are welcome to continue the discussion below if you have additional comments.
