### ISSUE TITLE
sqlpackage parameter VerifyExtraction

### ISSUE THREAD

**Issue by stephenkeogh** [MicrosoftDocs/sql-docs#9411]
To obtain the database schema and data while skipping the schema validation, perform an [Export](https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-export?view=sql-server-ver16) with the property /p:VerifyExtraction=True
should read
To obtain the database schema and data while skipping the schema validation, perform an [Export](https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-export?view=sql-server-ver16) with the property /p:VerifyExtraction=False

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d81bc053-0d2a-b2c7-d60d-d275bfcda033
* Version Independent ID: d81bc053-0d2a-b2c7-d60d-d275bfcda033
* Content: [Troubleshooting issues and performance with SqlPackage - SQL Server](https://learn.microsoft.com/en-us/sql/tools/sqlpackage/troubleshooting-issues-and-performance-with-sqlpackage?view=sql-server-ver16)
* Content Source: [docs/tools/sqlpackage/troubleshooting-issues-and-performance-with-sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage/troubleshooting-issues-and-performance-with-sqlpackage.md)
* Service: **sql**
* Sub-service: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@stephenkeogh -- Stephen, thank you for catching that.  I am updating the article.
