### ISSUE TITLE
$(ESCAPE_SQUOTE(TIME)) returns HMMSS, not HHMMSS

### ISSUE THREAD

**Issue by AudunWangen** [MicrosoftDocs/sql-docs#9412]
`$(ESCAPE_SQUOTE(TIME))` seems to return HMMSS, not HHMMSS, or in other words 24 hour clock without leading zeroes. At least that seems to be the case in SQL Server 2022.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3c73e6a-0759-dbb7-c244-efd613675e72
* Version Independent ID: 36c8ba73-85f3-3150-f7c0-69c6287766ea
* Content: [Use Tokens in Job Steps - SQL Server Agent](https://learn.microsoft.com/en-us/sql/ssms/agent/use-tokens-in-job-steps?view=sql-server-ver16)
* Content Source: [docs/ssms/agent/use-tokens-in-job-steps.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/use-tokens-in-job-steps.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by AudunWangen** [comment]
I think this is worse than I thought, and not just a problem with the documentation. It seems to truncate zeros from the start, so if the time is 12:30AM, TIME will be se to '3000', instead of '03000' or '003000'.

**Comment by rwestMSFT** [comment]
@AudunWangen If this is a product issue, please open a support case.

**Comment by WilliamAntonRohm** [comment]
@AudunWangen -- Audun, thank you for your feedback.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

@rwestMSFT -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
