### ISSUE TITLE
Incorrect information for Synapse analytics

### ISSUE THREAD

**Issue by cameron-interactive** [MicrosoftDocs/sql-docs#9418]
The SSMS section of this article does NOT apply to Synapse Analytics

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7f1c141-dea3-1a2c-ba2f-86163be24aa6
* Version Independent ID: 5d4a7221-2821-feb8-c74d-509c0c6e3889
* Content: [Add Columns to a Table (Database Engine) - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/add-columns-to-a-table-database-engine?view=sql-server-ver16)
* Content Source: [docs/relational-databases/tables/add-columns-to-a-table-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/add-columns-to-a-table-database-engine.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
You are correct, @cameron-interactive, not all Object Explorer and table designer features of SSMS work in Synapse SQL pools. Looks like we can be more clear about this in some of the docs. Thanks for the time and attention here.
