### ISSUE TITLE
export table data via table update trigger

### ISSUE THREAD

**Issue by vrc153** [MicrosoftDocs/sql-docs#9419]
Is following, not completed, example really the best way to match "export table data via table update trigger"

![image](https://github.com/MicrosoftDocs/sql-docs/assets/147373754/bea8ce2c-9646-4455-9c47-e10838ca9804)

**Comment by rwestMSFT** [comment]
@vrc153 Which article in Database Docs are you referencing? What feedback are you providing for that article? What would you like to see changed? Your embedded image did not include alt-text, and it's not clear what you're asking.

**Comment by vrc153** [comment]
Thanks for your question. I try to explain it with more detail.

My more general request is to provide a SQL independent solution for backup. Which is based on export file and store that file in a repository.

I want to do the same as "Tasks/Generate Scripts.../export Table Data to sql file".

But I want this integrated in a table update trigger. A Trigger has its environment. Which solution is the best in that environment?

I checked the Internet for solutions but even the best solution seems to be very unhandy.

I would expect a "oneliner" for that.

**Comment by rwestMSFT** [comment]
@vrc153 I still need to know which article and code sample you're referencing. I can't find the code sample from your screenshot in the Database Docs content.

This sounds more like a support or feature request, as opposed to a problem with the existing documentation, so I'm not sure this is the correct repository to be making this request.

**Comment by vrc153** [comment]
Issue moved to:

[https://feedback.azure.com/d365community/idea/ac5990c5-586e-ee11-a81c-6045bdb7ea56](https://feedback.azure.com/d365community/idea/ac5990c5-586e-ee11-a81c-6045bdb7ea56) 

Thx to rwestMSFT for his hints/ideas/support.
