### ISSUE TITLE
Historic recurrence - SSMS - EXCEL - "conditional formating"

### ISSUE THREAD

**Issue by vrc153** [MicrosoftDocs/sql-docs#9420]
History of Excel with focus on "conditional formating"
1987    first version without "conditional formating"
1997    first version of "conditional formating"
2010    improved "conditional formating"
2023    "conditional formating" still available and loved, because very useful

History of SSMS with focus on "conditional formating"
2005    first version without "conditional formating"
2023    users still asking for "conditional formating"

If "conditional formating" is available 2028 in SSMS, it took approximately the same time for users, like they were waiting for that feature in Excel.

the good prevails.

**Comment by rwestMSFT** [comment]
@vrc153 Can you please explain clearly what your question or issue is, and to which article you're referring? Thanks.

**Comment by vrc153** [comment]
Thanks for your hint. I'm sorry. I still have not a good detail knowledge, I'm working hard on understanding anything better. But its really challanging. I checked feedback.azure.com and tried to find SSMS at "https://feedback.azure.com/d365community/post/" but I didn't.
I'm still confused with which is the correct receiver for my issue.

**Comment by vrc153** [comment]
https://stackoverflow.com/questions/2833164/format-results-in-sql-management-studio

viewed 3k times.

https://stackoverflow.com/questions/7605597/how-to-have-colors-in-the-output-of-sql-result

viewed 37k times.

**Comment by vrc153** [comment]
Issue moved to:

[https://feedback.azure.com/d365community/idea/516520a9-556e-ee11-a81c-6045bdb7ea56](https://feedback.azure.com/d365community/idea/516520a9-556e-ee11-a81c-6045bdb7ea56) 

Thx to rwestMSFT for his hints/ideas/support.
