### ISSUE TITLE
A paragraph is not clear to me

### ISSUE THREAD

**Issue by AttilaAts** [MicrosoftDocs/sql-docs#9426]
Probably just because English is not my mother tongue, this paragraph is not clear to me:

Once you understand the permissions, apply server level permissions to logins or server roles and database level permissions users or database roles with the GRANT, REVOKE, and DENY statements.

I guess a 'to' is missing before 'users or database' but I may be wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6141aa-bfd7-1ce4-aecd-820036f4a60e
* Version Independent ID: fd41bd15-b6f6-0a67-eee8-4bae68e9838e
* Content: [Permissions (Database Engine) - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/permissions-database-engine?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/permissions-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/permissions-database-engine.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @AndreasWolter
* Microsoft Alias: **anwolter**

**Comment by AndreasWolter** [comment]
You are right. A "to" is missing. My bad.
Slightly adjusted:
Once you understand the permissions, apply server level permissions to logins or server roles and database level permissions to users or database roles by using the GRANT, REVOKE, and DENY statements.
is that easier to understand?

**Comment by AttilaAts** [comment]
It absolutely is. Thank you for the correction.

Regards,

Attila

**Comment by rwestMSFT** [comment]
We are updating the paragraph in question, and the updated article will be published in the next day or so. When that happens, this issue will automatically close.

Thank you for your feedback, @AttilaAts.
