### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by alankwyu** [MicrosoftDocs/sql-docs#9428]
Clicking the link in
For more information on implementing subscription streams, see [Navigating SQL replication subscriptionStream setting](https://blogs.msdn.microsoft.com/repltalk/2010/03/01/navigating-sql-replication-subscriptionstreams-setting).

returns

The request is blocked.
20231018T150014Z-13wkf20c3h03f8fh1310730p3c0000000dag000000001swn

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79643e9a-1ed5-bc2c-fe57-9f46f4430d86
* Version Independent ID: d8847636-ef0e-fe0f-e7eb-b0ccfcbe2626
* Content: [Enhance Transactional Replication Performance - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/replication/administration/enhance-transactional-replication-performance?view=sql-server-ver16)
* Content Source: [docs/relational-databases/replication/administration/enhance-transactional-replication-performance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/administration/enhance-transactional-replication-performance.md)
* Service: **sql**
* Sub-service: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @alankwyu , thanks for bringing this to our attention! I tested the link, and had a few other people in different locations test is as well, and it seems to be working for us. Could there be some kind of security setting on your end that is blocking the target? 

Thanks!
Masha from the SQL Docs team

**Comment by rwestMSFT** [comment]
I'll update the link in the original article to point to [the redirected link](https://repltalk.com/2010/03/01/navigating-sql-replication-subscriptionstreams-setting/) in the next day or so. Thanks @MashaMSFT.

Thanks for your feedback, @alankwyu.
