### ISSUE TITLE
Documentation for sys.sp_configure_automatic_tuning

### ISSUE THREAD

**Issue by erikdarlingdata** [MicrosoftDocs/sql-docs#9432]
This stored procedure was dormant in SQL Server 2019, but appears to be functional in SQL Server 2022, and Managed Instance. 

It would be nice to have it documented, since it's an internal procedure

```
EXECUTE sys.sp_configure_automatic_tuning
    @option = N'???',
    @type = N'???',
    @type_value = ???,
    @option_value = N'???';
```

One working configuration to disable automatic plan forcing is like so:

```
EXECUTE sys.sp_configure_automatic_tuning
    @option = N'FORCE_LAST_GOOD_PLAN', /*Option*/
    @type = N'QUERY', /*Target*/
    @type_value = 1, /*query_id from Query Store*/
    @option_value = N'OFF'; /*Disable*/
```

Thanks!

**Comment by WilliamAntonRohm** [comment]
@erikdarlingdata -- Erik, thank you for your continued interest in our documentation!  Which learn.microsoft.com article are you following?

**Comment by erikdarlingdata** [comment]
@WilliamAntonRohm thank you for your continued interest in my feedback. There is no docs page for this stored procedure at all, which is what I hope can be addressed.

**Comment by WilliamAntonRohm** [comment]
I see!  My expertise, such as it is, does not go this deep.  Please send me a couple names of related procedures, so I can find a suitable author.

**Comment by erikdarlingdata** [comment]
@WilliamAntonRohm there is one related stored procedure, the name of which is in the title and body of this issue.

**Comment by JohnKNess** [comment]
I guess the documentation for [sp_configure](https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-configure-transact-sql?view=sql-server-ver16#:~:text=sp_configure%20(Transact%2DSQL)) could serve a possible template for the non-existent sys.sp_configure_automatic_tuning documentation.

**Comment by rwestMSFT** [comment]
@erikdarlingdata After some internal discussion, we won't be able to document `sys.sp_configure_automatic_tuning` at this time.

Thank you for your continued feedback.
