### ISSUE TITLE
Typo in example code

### ISSUE THREAD

**Issue by cbirt-capgemini** [MicrosoftDocs/sql-docs#9434]
Text copied below reads 'Desciption' rather than 'Description'

```
EXECUTE msdb.dbo.sysmail_add_profile_sp
  @profile_name = 'Profile Name'  
, @description = 'Desciption';
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2207e5-7268-5a38-829d-09f2c3beb384
* Version Independent ID: 6398807e-6c2b-a4d2-462e-ef159b4afb14
* Content: [Create a Database Mail Profile - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/database-mail/create-a-database-mail-profile?view=sql-server-ver16)
* Content Source: [docs/relational-databases/database-mail/create-a-database-mail-profile.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/database-mail/create-a-database-mail-profile.md)
* Service: **sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@cbirt-capgemini -- thank you for catching this.  I am updating the article.
