### ISSUE TITLE
Topic for sys.dm_os_enumerate_fixed_drives is in the wrong place

### ISSUE THREAD

**Issue by sommarskog** [MicrosoftDocs/sql-docs#9449]
The topic https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-
views/sys-dm-os-enumerate-fixed-drives?view=azuresqldb-current is sorted under Azure SQL Database, when I run it in my SQL Database, I get Invalid object name 'sys.dm_os_enumerate_fixed_drives'. Which is not surprising at all, since the DMV makes no sense on Azure SQL Database.

The topic should be under SQL Server 2022 etc.

**Comment by WilliamAntonRohm** [comment]
@sommarskog -- thank you for your feedback.

@rwestMSFT -- please look into this issue.
