### ISSUE TITLE
Non-Microsoft download site is given for downloading Windows Installer 4.5

### ISSUE THREAD

**Issue by russ960** [MicrosoftDocs/sql-docs#9454]
When on this page there is a link for Windows Installer 4.5 that directs to a 3rd party download site https://windows-installer.soft32.com/ that looks super sketchy.  I know that there is a download site on MS site for this: https://support.microsoft.com/en-us/topic/windows-installer-4-5-is-available-bf06be18-3e0a-d5eb-4549-b482f67e1c46 

I have seen this on another connected page for downloading the installer.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86bd520a-7468-fd55-c357-b0f645a917ef
* Version Independent ID: 3dc9dee5-afcb-8287-4441-e84ff717186a
* Content: [bcp utility - SQL Server](https://learn.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver16)
* Content Source: [docs/tools/bcp-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/bcp-utility.md)
* Service: **sql**
* Sub-service: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@russ960 -- Russ, thank you for catching that. Windows Installer 4.5 is no longer available.

@markingmyname -- Mark, it appears this section is behind the times:
- [System requirements](https://learn.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver16#system-requirements)

**Comment by rwestMSFT** [comment]
Thanks for this, @russ960. I will stage an update for supported operating systems.
