### ISSUE TITLE
E: Unable to locate package mssql-server-is

### ISSUE THREAD

**Issue by ShadowOfPhantom** [MicrosoftDocs/sql-docs#9460]
Hello! I'm trying to fight the issue "Unable to locate package"
Do you have any idea how to deal with this?

![image](https://github.com/MicrosoftDocs/sql-docs/assets/41395390/01043225-94a2-4432-9ae3-d71ecad58a04)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41654ae8-cbd1-c5dd-f15a-69466a765fda
* Version Independent ID: 94311dce-80f0-b8ce-7296-b595ff50d640
* Content: [Install SQL Server Integration Services on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-setup-ssis?view=sql-server-linux-ver15&tabs=rhel)
* Content Source: [docs/linux/sql-server-linux-setup-ssis.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-ssis.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @lrtoyou1223
* Microsoft Alias: **lle**

**Comment by rwestMSFT** [comment]
Hi @ShadowOfPhantom I'm not sure why you're unable to install. The packages for SSIS on SQL Server 2017, 2019, and 2022, are live on the packages.microsoft.com site, for Ubuntu 18.04 and 20.04 respectively.

For example, you can see this at https://packages.microsoft.com/ubuntu/20.04/mssql-server-2022/pool/main/m/mssql-server-is/ for the SQL Server 2022 Integration Services package.

Perhaps you can download the package and install it manually?

**Comment by ShadowOfPhantom** [comment]
> Hi @ShadowOfPhantom I'm not sure why you're unable to install. The packages for SSIS on SQL Server 2019, and 2022, are live on the packages.microsoft.com site, for Ubuntu 18.04 and 20.04 respectively.
> 
> For example, you can see this at https://packages.microsoft.com/ubuntu/20.04/mssql-server-2022/pool/main/m/mssql-server-is/ for the SQL Server 2022 Integration Services package.
> 
> Perhaps you can download the package and install it manually?

Take a look, this is from the [instruction](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-setup-ssis?view=sql-server-linux-ver15&tabs=ubuntu):

curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc

sudo add-apt-repository "$(curl https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list)"

sudo apt-get update
sudo apt-get install -y mssql-server-is

https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019/dists/focal/main/binary-amd64/ it actually **doesn't contain** mssql-server-is package

**Comment by rwestMSFT** [comment]
Ah thanks. As documented here, there is no 20.04 release for SSIS on Ubuntu: https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019

I'm updating the instructions to point to 18.04.

**Comment by ShadowOfPhantom** [comment]
> Ah thanks. As documented here, there is no 20.04 release for SSIS on Ubuntu: https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019
> 
> I'm updating the instructions to point to 18.04.

Thank you. Looks like I've successfully installed it with SQL SERVER 2022 on Ubuntu 20.04 but I couldn't do for what I have installed ssis. I was trying to use Copy Wizard to migrate database from Windows to Linux sql server instance but it always say "The action you attempted to perform on a remote SQL Server instance failed because the action requires a SQL Server component that is not installed on the remote computer. To proceed, install SQL Server Integration Services on the remote computer and try again."

I'm desperate, do you have any ideas how to fix that?

**Comment by rwestMSFT** [comment]
Unfortunately I can't provide technical support. Please consider the resources available at [SQL Server help and feedback](https://learn.microsoft.com/en-us/sql/sql-server/sql-server-get-help).

**Comment by rwestMSFT** [comment]
@ShadowOfPhantom This issue was closed by an automation process. The updated article will be published later today.
