### ISSUE TITLE
HOW DO I DOWNLOAD JUST BCP - it should not be this tough

### ISSUE THREAD

**Issue by mbourgon** [MicrosoftDocs/sql-docs#9469]
The page says that BCP is being shipped with SQL Server. So in order to run it on my jumpbox, which I cannot connect to directly, I have to download the SQL Server installer, then go through the installer, just in order to discover I can't install it for reasons having to do with it being a jumpbox. I just need BCP.

And it turns out, 15 minutes later, that there's a download page for it that didn't come up when I searched for it initially

PLEASE ADD THE FOLLOWING LINK TO "HOW TO DOWNLOAD"
https://www.microsoft.com/en-us/download/details.aspx?id=36433
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86bd520a-7468-fd55-c357-b0f645a917ef
* Version Independent ID: 3dc9dee5-afcb-8287-4441-e84ff717186a
* Content: [bcp utility - SQL Server](https://learn.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver16)
* Content Source: [docs/tools/bcp-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/bcp-utility.md)
* Service: **sql**
* Sub-service: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mbourgon** [comment]
And that version of BCP is 10 years old. So it's probably unusable for what I need anyhow. HOW DO I JUST GET BCP

**Comment by mbourgon** [comment]
stackoverflow: 
https://dba.stackexchange.com/questions/318662/where-to-download-bcp-command-line-package-for-sql-server-2019

Old but not as old, and actually acquirable.

BCP comes with "Command Line Utilities" package. You need to install "ODBC driver" first. Sending you the links for download

[Microsoft ODBC Driver 17 for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16#version-17) - [Direct Download Link](https://download.microsoft.com/download/6/f/f/6ffefc73-39ab-4cc0-bb7c-4093d64c2669/en-US/17.10.3.1/x64/msodbcsql.msi)

[Microsoft Command Line Utilities 15 for SQL Server (x64)](https://learn.microsoft.com/en-us/sql/tools/sqlcmd/sqlcmd-utility?view=sql-server-ver16#download-and-install-sqlcmd) - [Direct Download Link](https://download.microsoft.com/download/a/a/4/aa47b3b0-9f67-441d-8b00-e74cd845ea9f/EN/x64/MsSqlCmdLnUtils.msi)

**Comment by WilliamAntonRohm** [comment]
@mbourgon -- thank you for your detailed feedback.  

@markingmyname -- please look into this issue.

**Comment by rwestMSFT** [comment]
We have an update to the **bcp** article, which should publish in the next day or so, with links to download the tool on Windows, Linux, and macOS.

When that update is merged, this issue will automatically close.

Thank you for your feedback.
