### ISSUE TITLE
How to exclude some column from history table in temporal table

### ISSUE THREAD

**Issue by soroshsabz** [MicrosoftDocs/sql-docs#9471]
I have temporal table like below

```sql
-- Create a Temporal Table
CREATE TABLE dbo.Sample
(
  SampleId int identity(1,1) PRIMARY KEY CLUSTERED
  , SampleDate date NOT NULL
  , Data1 varchar(50)
  , Data2 varchar(50)
  -- Other fields...
  , SysStartTime datetime2 GENERATED ALWAYS AS ROW START
  , SysEndTime datetime2 GENERATED ALWAYS AS ROW END
  , PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime)
 )
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.SampleHistory));
```

I want to say all of changes in Data2 does not store in `HISTORY_TABLE`. In another word, in very large and big tables I just need few columns for auditing so I want to exclude other columns to reduce DB size and improve performance (in some cases most frequent changes in table occur on non-auditable column)

**Please add example for this scenario in this page**

I have the same question into the https://stackoverflow.com/q/76943485/1539100

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f9c244b-870b-737f-6f6d-db9675179427
* Version Independent ID: 3dde09ff-88b5-f6f3-1120-3bf8a90a395e
* Content: [Temporal Tables - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-ver16&source=docs)
* Content Source: [docs/relational-databases/tables/temporal-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/temporal-tables.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
Hi @soroshsabz. This is not how temporal tables work. You cannot select which columns are maintained in the history table.

If you'd like to make a feature request, please visit the SQL section on https://feedback.azure.com.

#please-close

**Comment by soroshsabz** [comment]
So please upvote

https://feedback.azure.com/d365community/idea/56566e8b-0440-ee11-a81c-000d3ae37d1e

and

https://feedback.azure.com/d365community/idea/f251229b-6b79-ee11-a81c-6045bdb7ea56
