### ISSUE TITLE
Still a crock!

### ISSUE THREAD

**Issue by GeorgeBR** [MicrosoftDocs/sql-docs#9472]
Unfortunately, despite being an ENTERPRISE product, and on version 19, this is still a crock!
Trying to script a database, and the apps it loads (that look like they've been unchanged since Windows 95, and sometimes just don't load at all) crash SSMS every time.
Honestly, if this is what you think Enterprise software is, then you should all pack up and go home!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-gb/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by rwestMSFT** [comment]
@GeorgeBR Since we haven't heard from you for two weeks, I'm closing this issue as resolved.
