### ISSUE TITLE
Great job guys- Thanks

### ISSUE THREAD

**Issue by Ed2353** [MicrosoftDocs/sql-docs#9481]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86b1a74a-487c-8b7a-894c-454d5986ed1b
* Version Independent ID: 001c4d17-589b-ccd5-9887-52bead593258
* Content: [SQL Server Management Studio keyboard shortcuts - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/sql-server-management-studio-keyboard-shortcuts?view=sql-server-ver16)
* Content Source: [docs/ssms/sql-server-management-studio-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/sql-server-management-studio-keyboard-shortcuts.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@Ed2353 -- you're welcome!
