### ISSUE TITLE
Remove bad practices from the PowerShell sample commands

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/sql-docs#9489]
The "Create a CmdExec job step" contains two problematic PowerShell examples:

> `PowerShell.exe -Command "& { Get-Date }"`

There's no reason to use `"& { ... }"` in order to invoke code passed to PowerShell's CLI via the `-Command` (`-c`) parameter - just use `"..."` directly. Older versions of the [CLI documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh) erroneously suggested that `& { ... }` is required, but this has since been corrected.

Therefore:

```powershell
PowerShell.exe -Command "Get-Date"
```

---

> `PowerShell.exe -Command "& {&SQLCmd.exe -S $(ESCAPE_NONE(SRVR)) -Q 'select @@version'}"`

Aside from the unnecessary `& { ... }` enclosure (and the fact that you don't need PowerShell to simply invoke an executable):

* Use of `&` isn't strictly necessary here (the executable name is a literal name/path that is neither quoted nor contains variable references)

* If you do want to use it (which may make sense, given that it is safe to _always_ use it), it's best to put a _space_ between the `&` and the executable name (`& SQLCmd.exe ...`); while not using a space technically works, using one helps readability in general, and, more importantly, is better for symmetry with the related [dot-sourcing operator](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators#dot-sourcing-operator-), `. `, which _requires_ a space.

Therefore:

* Either:

```powershell
PowerShell.exe -Command  "SQLCmd.exe -S $(ESCAPE_NONE(SRVR)) -Q 'select @@version'"
```

* Or:

```powershell
PowerShell.exe -Command  "& SQLCmd.exe -S $(ESCAPE_NONE(SRVR)) -Q 'select @@version'"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db6f2a8a-7b0a-b5b6-7095-b7569d2c23bb
* Version Independent ID: 26d6594a-6d7d-7091-0f4b-382bb4a38ebe
* Content: [Run Windows PowerShell Steps in SQL Server Agent - SQL Server](https://learn.microsoft.com/en-us/sql/powershell/run-windows-powershell-steps-in-sql-server-agent?view=sql-server-ver16#create-a-powershell-job-step)
* Content Source: [docs/powershell/run-windows-powershell-steps-in-sql-server-agent.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/run-windows-powershell-steps-in-sql-server-agent.md)
* Service: **sql**
* Sub-service: **sql-server-powershell**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@mklement0 -- Michael, thank you for your clear feedback.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@markingmyname -- Mark, please review this change in [private PR 29297](https://github.com/MicrosoftDocs/sql-docs-pr/pull/29297).
