### ISSUE TITLE
avg_memory_usage_percent may not be supported on SQL Managed Instance

### ISSUE THREAD

**Issue by akikawa1123** [MicrosoftDocs/sql-docs#9493]
avg_memory_usage_percent may not be supported on SQL Managed Instance. I think the document should note this limitation.

SELECT end_time,avg_memory_usage_percent,avg_instance_memory_percent FROM sys.dm_db_resource_stats;
<img width="573" alt="image" src="https://github.com/MicrosoftDocs/sql-docs/assets/87466397/43cebf81-8d77-4dcf-883a-0bd16db49332">

https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-resource-stats-azure-sql-database?view=azuresqldb-current

**Comment by WilliamAntonRohm** [comment]
@akikawa1123 -- Akikawa, thank you for your feedback.

@rwestMSFT -- Randolph, please look into this issue.

**Comment by rwestMSFT** [comment]
We're investigating, thanks.

**Comment by rwestMSFT** [comment]
We will be removing MI as a supported option from the "Applies to" section at the top. Thanks for raising this issue, @akikawa1123. When the internal PR is merged, this issue will automatically close.
