### ISSUE TITLE
Probe port in examples are in the dynamic port range

### ISSUE THREAD

**Issue by lbergnehr** [MicrosoftDocs/sql-docs#9494]
In the sql tutorial https://github.com/MicrosoftDocs/sql-docs/blob/live/azure-sql/virtual-machines/windows/availability-group-manually-configure-tutorial-single-subnet.md the probe port for the load balancer (search for `probe`) is exemplified with `59999`. This, however, is in the dynamic port range and according to [RFC 6335](https://www.rfc-editor.org/rfc/rfc6335) you must not assume that a port in this range is available:
> ... application software MUST NOT
      assume that a specific port number in the Dynamic Ports range will
      always be available for communication at all times, and a port
      number in that range hence MUST NOT be used as a service
      identifier.
https://www.rfc-editor.org/rfc/rfc6335#section-8.1.2

I think a port below 49152 should be used in the example.

**Comment by rwestMSFT** [comment]
@lbergnehr Thank you for your feedback. Perhaps you would like to create a pull request to make this change yourself. It is more likely to be triaged, and you will get appropriate credit as an article contributor.

**Comment by tarynpratt** [comment]
@lbergnehr Thanks for the feedback on this item. We'll consider making this change in the future, as we're just using the port number as an example and include additional details to exclude the port from being used elsewhere. 

#please-close
