### ISSUE TITLE
Resolving conflicts between SQLPS and SqlServer modules

### ISSUE THREAD

**Issue by renbud** [MicrosoftDocs/sql-docs#9499]
Some command names exist in both SQLPS and SqlServer modules. 

This means that if you have one module already installed an error is raised which can be prevented by using the -AllowClobber parameter when installing or updating the other module.
Also, when importing one module you need to remove the other module first or use the -DisableNameChecking parameter to prevent an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cdc5826c-d266-6f61-e1eb-b4f236d03dd9
* Version Independent ID: 4ab93d92-6a23-a0c0-2911-ce06e99dc5c5
* Content: [Download SQL Server PowerShell Module - SQL Server](https://learn.microsoft.com/en-us/sql/powershell/download-sql-server-ps-module?view=sql-server-ver16)
* Content Source: [docs/powershell/download-sql-server-ps-module.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/download-sql-server-ps-module.md)
* Service: **sql**
* Sub-service: **sql-server-powershell**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@renbud -- Renato, thank you for your clear feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment]
@renbud 

Thank you for bringing this to our attention.

That is a valid point.

We will work on adding some sort of context to help others avoid this in the future.

**Comment by markingmyname** [comment]
Updates to the article should be live early next week.  

Thank you.
