### ISSUE TITLE
Error popup

### ISSUE THREAD

**Issue by ginger-schooling** [MicrosoftDocs/sql-docs#9516]
When I download and install the new version of SSMS, I get a popup that has 3 buttons: Repair, Uninstall, Close. None of those buttons seem relevant and the doc here doesn't say what to do when that popup happens.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
@ginger-schooling It sounds like you already have SSMS 19.2 installed.  If you try to install the same version that's already on the machine, it prompts with the dialog you've mentioned.  If you open SSMS and go to Help > About, what version are you running?

**Comment by ginger-schooling** [comment]
I just clicked Uninstall and reinstalled it and it’s fine. I was running 19.2 already prior to that.

***@***.***

Ginger Schooling
Pricing Analyst
Ferguson | Price Management
(530) 292-6381
***@***.***

**Comment by erinstellato-ms** [comment]
@ginger-schooling Right, so if you already had 19.2 installed, then if you try to install it again, it will assume you want to uninstall, repair, or do nothing (close).

**Comment by erinstellato-ms** [comment]
#please-close
