### ISSUE TITLE
Contained databases - Add note that certificate for the encrypted backup should be stored in the server master database

### ISSUE THREAD

**Issue by Nova-Logic** [MicrosoftDocs/sql-docs#9520]
Sql docs does not have information that certificate for the encrypted backup should be stored in the master DB of Server DB instead of master db of contained DB. That's important when you're using sql always on with contained DB.

**Comment by WilliamAntonRohm** [comment]
@Nova-Logic -- thank you for your feedback.  Are you following a particular learn.microsoft.com article?

**Comment by rwestMSFT** [comment]
@Nova-Logic Would this be an appropriate place to clarify your request? https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/contained-availability-groups-overview?view=sql-server-ver16#transparent-data-encryption-tde

That section already describes where TDE will look for the certificates. Perhaps we can add an additional note there?

**Comment by Nova-Logic** [comment]
Or mat be it would be better to update contained db article that will describe this limitation, and then links to that article from backup and TDE articles

**Comment by Nova-Logic** [comment]
Thanks!

**Comment by rwestMSFT** [comment]
We're still working on testing the scenario to confirm the changes to the staged articles.
