### ISSUE TITLE
Collation is wrongly defined

### ISSUE THREAD

**Issue by mcgolledge** [MicrosoftDocs/sql-docs#9522]
This text "A collation specifies the bit patterns that represent each character in a dataset." is wrong. An encoding is the bit pattern that represents a character. A collation is the ordering of characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bda69849-66d9-0b69-1041-c526a406c04f
* Version Independent ID: 7a8927c6-95b4-47bf-d866-3c5585cf9383
* Content: [Collation and Unicode support - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver16)
* Content Source: [docs/relational-databases/collations/collation-and-unicode-support.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/collation-and-unicode-support.md)
* Service: **sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by rwestMSFT** [comment]
@mcgolledge thank you for your feedback.

If "collation" refers to the "ordering of characters" in general terms, in the context of SQL Server, it also includes how we *encode* those characters, on account of ASCII vs Unicode support (specifically UCS-2, UTF-16, and UTF-8) in SQL Server collations.

Thus, with the way we define collation in the product, the sentence is correct.

#please-close

**Comment by mcgolledge** [comment]
The rest of the world understands collation to mean how text is sorted and compared and encoding to mean the bit patterns used to represent code points. Effectively, you are changing the definition to meet your implementation.For instance, let's take the Unicode character set. Each character has a code point. 'A' is U+0041. That code point is encoded in UTF-8 as 0100 0001; in UTF-16, it is 0000 0000 0100 0001. The encoding does not change the equality of 'A' and 'A'.Some languages share the same characters, which have the same code point and are encoded using the same bit pattern, but order them differently in their alphabet. Thus, the same character may have different encodings or different ordering and comparison results, collation. Two strings encoded in UTF-8 may sort differently dependent on the collation of the current language. Encoding and collation are independent.Take a look at the COLLATE option in WHERE clauses. That affects comparisons without changing the original encoding.On Nov 28, 2023 6:21 PM, Randolph West MSFT ***@***.***> wrote:
@mcgolledge thank you for your feedback.
If "collation" refers to the "ordering of characters" in general terms, in the context of SQL Server, it also includes how we encode those characters, on account of ASCII vs Unicode support (specifically UCS-2, UTF-16, and UTF-8) in SQL Server collations.
Thus, with the way we define collation in the product, the sentence is correct.
#please-close
