### ISSUE TITLE
missed indent in RU localisation

### ISSUE THREAD

**Issue by baslo2** [MicrosoftDocs/sql-docs#9526]
![Снимок экрана от 2023-11-30 11-41-51](https://github.com/MicrosoftDocs/sql-docs/assets/84476539/d6b66742-67c0-41e1-b95b-6428582e8d67)
between "ntext" and "и" have to space

https://learn.microsoft.com/ru-ru/sql/relational-databases/indexes/guidelines-for-online-index-operations?view=sql-server-ver16

**Comment by baslo2** [comment]
@WilliamAntonRohm you are welcome, glad to help

**Comment by WilliamAntonRohm** [comment]
@baslo2 -- Shamsutdinov, sorry for the delay.  I've created a new [localization work item 940497](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/940497) for this issue.

@rwestMSFT -- Randolph, fyi and thank you.
