### ISSUE TITLE
TURKISH CHARACTER ISSUE 

### ISSUE THREAD

**Issue by sinancinar** [MicrosoftDocs/sql-docs#9532]
When I import flat file (csv file) all the Turkish characters changed 
on Excel: ![image](https://github.com/MicrosoftDocs/sql-docs/assets/10000282/c58470fa-a1b0-475b-9ca9-6ed117cd1269)
on SSMS: ![image](https://github.com/MicrosoftDocs/sql-docs/assets/10000282/4bc58185-71db-46c9-b82b-1f514ba5a17f)

to sole problem i tried to different variations 
![image](https://github.com/MicrosoftDocs/sql-docs/assets/10000282/135bdb72-4942-4da3-bb27-98a4f7fb5d81)

i imported all different ways but result same
tools>web properties uTF-8 and the others but didn't worked
![image](https://github.com/MicrosoftDocs/sql-docs/assets/10000282/f40a2ec8-eeae-4172-be39-1957d261fb09)

I tried to import from task > import data .xlsx (and all acceped extensions) but this time i got this error 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine (System.Data)

I installed Microsoft Access Database Engine 2010 and 2016 64 bit version didn't solve problem

I read the Microsoft import and export page didn't find a solution 
Maybe you will find a solutions thanks for even read this.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d89ecc7f-4705-dabe-9f70-2070d4aa19c9
* Version Independent ID: 9c991bd5-535c-03b5-d810-c1b2ca7e7cb4
* Content: [Import Flat File to SQL - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/import-export/import-flat-file-wizard?view=sql-server-ver16&f1url=%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(sql13.swb.importflatfile.f1)%26rd%3Dtrue)
* Content Source: [docs/relational-databases/import-export/import-flat-file-wizard.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/import-flat-file-wizard.md)
* Service: **sql**
* Sub-service: **data-movement**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
Hi @sinancinar - can you please share the version of SSMS you are using (from **Help > About**)?  If you are right-clicking on the database and selecting **Tasks > Import Flat File...** then this should not be an issue with SSMS 19.2 (latest release, you can download [here](https://learn.microsoft.com/sql/ssms/download-sql-server-management-studio-ssms).

When you right-click on the database and select **Tasks -> Import Data**, this option uses Integration Services.  If you don't have Integration Services installed, then this will not work (documentation [here](https://learn.microsoft.com/sql/integration-services/import-export-data/start-the-sql-server-import-and-export-wizard).  If it you can select a flat file, on the **Choose a Destination* page, select SQL Server Native Client and connect to your server, assuming you're importing this to a local server:

![image](https://github.com/MicrosoftDocs/sql-docs/assets/98599126/8de4437b-3e52-4b8e-b5c3-8b8e391d07c1)

You can then review the mapping, etc. for the import.

**Comment by erinstellato-ms** [comment]
Hey @sinancinar - following up to see if you had a chance to test with the information I provided above.  If you could provide an update that would be great.  Thanks!

**Comment by rwestMSFT** [comment]
@sinancinar I am closing this, because we haven't heard back from you. If that changes, feel free to respond below.
