### ISSUE TITLE
No provider of 'msodbcsql18' found

### ISSUE THREAD

**Issue by TAMASOOD** [MicrosoftDocs/sql-docs#9533]
I am not able to install Microsoft ODBC 18 with the provided documentation from Microsoft. The information is: 

Refreshing service 'Basesystem_Module_15_SP3_ppc64le'.
Refreshing service 'Desktop_Applications_Module_15_SP3_ppc64le'.
Refreshing service 'IBM_POWER_Advance_Toolchain_for_SLE_15_ppc64le'.
Refreshing service 'IBM_POWER_Tools_for_SLE_15_ppc64le'.
Refreshing service 'Legacy_Module_15_SP3_ppc64le'.
Refreshing service 'SAP_Applications_Module_15_SP3_ppc64le'.
Refreshing service 'SUSE_Linux_Enterprise_High_Availability_Extension_15_SP3_ppc64le'.
Refreshing service 'SUSE_Linux_Enterprise_Server_for_SAP_Applications_15_SP3_ppc64le'.
Refreshing service 'Server_Applications_Module_15_SP3_ppc64le'.
Building repository 'packages-microsoft-com-prod' cache ............................................................................................................[done]
Loading repository data...
Reading installed packages...
'msodbcsql18' not found in package names. Trying capabilities.
No provider of 'msodbcsql18' found.

Any hint what is going wrong?

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=suse18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
The ppc64 architecture isn't supported.

**Comment by WilliamAntonRohm** [comment]
@TAMASOOD -- thank you for your question.

@David-Engel -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by TAMASOOD** [comment]
Hello Guys

Thanks a lot for the answer and clarification.

Just curious, @WilliamAntonRohm is there any ODBC driver for PPC64 to retrieve data from SQL Server to SAP HANA DB?

Regards

TAMASOOD.
