### ISSUE TITLE
Database Mail: article missing referenced troubleshooting link

### ISSUE THREAD

**Issue by iamshiao** [MicrosoftDocs/sql-docs#9537]
In the Troubleshoot sub section it says "Opens this Docs article."
But there is nothing to open.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f9782de-2b30-b2da-bf2c-2613e7bd92ce
* Version Independent ID: df40dd9e-036f-d491-f4e9-144da46387c4
* Content: [Configure Database Mail - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/database-mail/configure-database-mail?view=sql-server-ver16&f1url=%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(sql13.swb.dbmail.sendtestemail.test.f1)%26rd%3Dtrue)
* Content Source: [docs/relational-databases/database-mail/configure-database-mail.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/database-mail/configure-database-mail.md)
* Service: **sql**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Thanks @iamshiao, a doc update is in flight. It'll be more clear that by "this document", it means the **Troubleshoot** button on that wizard brings you to [this document, the current document you're reading](https://learn.microsoft.com/en-us/sql/relational-databases/database-mail/configure-database-mail). From the time of Books Online. Should be more clear once published, soon. 

Thanks again for the time and attention here, your suggestions help improve our documentation.
