### ISSUE TITLE
DATETIME Data Types page insinuates num_prec_radix

### ISSUE THREAD

**Issue by terakilobyte** [MicrosoftDocs/sql-docs#9541]
On this page specifically, it implies that these types should have a `num_prec_radix` given
> ... The NUM_PREC_RADIX column (in the result set returned by SQLColumns, SQLGetTypeInfo, and SQLProcedureColumns) contains a value of 2. If SQL_ATTR_ODBC_VERSION is set to SQL_OV_ODBC2, then the functions return SQL_DATE, SQL_TIME, and SQL_TIMESTAMP in the DATA_TYPE field, the COLUMN_SIZE column contains the decimal precision for the approximate numeric type, and the NUM_PREC_RADIX column contains a value of 10.

However, in the page for [example resulset metadata](https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/example-sqlgettypeinfo-result-set?view=sql-server-ver16), it clearly shows that this should be null.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d93083eb-3a7c-dff1-9615-4b99731fafe7
* Version Independent ID: cd7db5ac-3b16-8db6-905f-10b2effb46f0
* Content: [Datetime Data Type Changes - ODBC API Reference](https://learn.microsoft.com/en-us/sql/odbc/reference/develop-app/datetime-data-type-changes?view=sql-server-ver16)
* Content Source: [docs/odbc/reference/develop-app/datetime-data-type-changes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/develop-app/datetime-data-type-changes.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by rwestMSFT** [comment]
@terakilobyte Thank you for your contribution. It's not clear where the implication is being made, or what the consequences of it are. If you have some more detail to share, please feel free. Until then, I am closing this issue.

**Comment by terakilobyte** [comment]
On the page for [Datetime Data Type Changes](https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/datetime-data-types?view=sql-server-ver16), the content ...

> The NUM_PREC_RADIX column (in the result set returned by SQLColumns, SQLGetTypeInfo, and SQLProcedureColumns) contains a value of 2. If SQL_ATTR_ODBC_VERSION is set to SQL_OV_ODBC2, then the functions return SQL_DATE, SQL_TIME, and SQL_TIMESTAMP in the DATA_TYPE field, the COLUMN_SIZE column contains the decimal precision for the approximate numeric type, and the NUM_PREC_RADIX column contains a value of 10.

implies that these should have a `NUM_PREC_RADIX`. However, in the Example [SQLGetTypeInfo Result Set](https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/example-sqlgettypeinfo-result-set?view=sql-server-ver16), the value is clearly displayed as `<null>`.

So, what should it be?

**Comment by David-Engel** [comment]
The NUM_PREC_RADIX column should only apply to numeric types, not date/time types. It also seems like any values are database specific. The example table looks correct to me (`<null>`). I'm not sure why that changes page lists any values at all for the NUM_PREC_RADIX column for date/time types.

I can remove those sentences.

Regards,
David

**Comment by terakilobyte** [comment]
Thanks, that's what thought as well but it caused some needless discussion internally. Hoping to help future devs!
