### ISSUE TITLE
PBScaleout Groups

### ISSUE THREAD

**Issue by maroliict** [MicrosoftDocs/sql-docs#9543]
[Enter feedback here]
As listed on this page https://learn.microsoft.com/en-us/sql/relational-databases/polybase/configure-scale-out-groups-windows?view=sql-server-ver16 this setting is retired in the favour of a Scale Up scenario.

Should this page be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0f602a-88ea-16cc-a28f-d306de15d22b
* Version Independent ID: 81ed5850-ffbb-b1f8-4bd6-fede5eb5769b
* Content: [Install PolyBase on Windows - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/polybase/polybase-installation?view=sql-server-ver16)
* Content Source: [docs/relational-databases/polybase/polybase-installation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-installation.md)
* Service: **sql**
* Sub-service: **polybase**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@maroliict -- thank you for your feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
@maroliict Thanks for taking the time to provide this feedback. Both pages indicate that Scale-out group functionality is retired and removed from the product in SQL Server 2022 (16.x). What further updates did you have in mind?

**Comment by maroliict** [comment]
Retired is Ok. But the commandline switch does not work anymore when installing SQL2022. So I would expect that you remove this option from the page.




[My Logo]

Met vriendelijke groet,

Rob Litjens

T. 0651117831

***@***.***‑ict.nl



[Facebook]<https://cloud.letsignit.com/collect/bc/61f3c9d3493d5b4d02e22bbf?p=LNMVKNft1VOW-tTmCg1GDI4busryP2HbGzfxzEfVXCjocQfmp4ttSX8Htnz-I4jX0XRxH3nlrjAg8595z8uA0ohQgm0XhpC9XlquztfkJ6iPg5grwK54r7mOew4q12-dcXOpXqVkRZNycy0bfe1ASA==>

[Twitter]<https://cloud.letsignit.com/collect/bc/61f3c9d3493d5b4d02e22bbf?p=LNMVKNft1VOW-tTmCg1GDI4busryP2HbGzfxzEfVXCjocQfmp4ttSX8Htnz-I4jX0XRxH3nlrjAg8595z8uA0i0YJc9fGQ34NR0fUiP80UiQ3F4zuMdJ97TqhfZY6BzQ-qRkggsquhNE4RxALb0mgw==>

[LinkedIn]<https://cloud.letsignit.com/collect/bc/61f3c9d3493d5b4d02e22bbf?p=LNMVKNft1VOW-tTmCg1GDI4busryP2HbGzfxzEfVXCjocQfmp4ttSX8Htnz-I4jX0XRxH3nlrjAg8595z8uA0nu1AODnO2i0v1bsq9G4ivqGBC-jXXJVigRj8jIzxC0Gmrs1s0Sv3wxo9d5R2kPbdQ==>



Van: William Assaf MSFT ***@***.***>
Verzonden: maandag 11 december 2023 20:38
Aan: MicrosoftDocs/sql-docs ***@***.***>
CC: Rob Litjens ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [MicrosoftDocs/sql-docs] PBScaleout Groups (Issue #9543)


@maroliict<https://github.com/maroliict> Thanks for taking the time to provide this feedback. Both pages indicate that Scale-out group functionality is retired and removed from the product in SQL Server 2022 (16.x). What further updates did you have in mind?

**Comment by WilliamDAssafMSFT** [comment]
Ah, I understand. Our Docs serve multiple versions, so the scale-out is still supported for some earlier versions of SQL Server, and must remain documented for them while they're in support.

**Comment by maroliict** [comment]
Yea, but should that option not disappear when 2022 is selected?

Met vriendelijke groet,
Maroli-ICT

Rob Litjens
+31 6 51117831

(Mobiel verstuurd)
________________________________
Van: William Assaf MSFT ***@***.***>
Verzonden: Tuesday, December 12, 2023 6:04:02 PM
Aan: MicrosoftDocs/sql-docs ***@***.***>
CC: Rob Litjens ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [MicrosoftDocs/sql-docs] PBScaleout Groups (Issue #9543)


Ah, I understand. Our Docs serve multiple versions, so the scale-out is still supported for some earlier versions of SQL Server, and must remain documented for them while they're in support.

**Comment by WilliamDAssafMSFT** [comment]
We have different tools to handle versioned content in various docs. The NOTE box is how we decided to implement this caveat, which is more informative than simply hiding the content. Thanks for asking, @maroliict !
