### ISSUE TITLE
How to backup and restore with older versions SQL server 2016+ to AWS S3 bucket

### ISSUE THREAD

**Issue by momchilok** [MicrosoftDocs/sql-docs#9550]
Is there a way to backup directly to S3 aws bucket from on premise SQL server 2016, 2019 without first to create local backup and then upload it.
This article says only SQL 2022 can do it [https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url-s3-compatible-object-storage?view=sql-server-ver16](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url-s3-compatible-object-storage?view=sql-server-ver16)

**Comment by rwestMSFT** [comment]
The article is correct. Only SQL Server 2022 is supported at this time.

Thank you for your question.
