### ISSUE TITLE
Functions of vsfoxpro 

### ISSUE THREAD

**Issue by Gahadue** [MicrosoftDocs/sql-docs#9552]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d146a133-1a17-c410-9d1c-4aff2708199c
* Version Independent ID: 90303173-9018-7d9f-5f72-b89dce325ac0
* Content: [String Functions (Visual FoxPro ODBC Driver) - Open Database Connectivity (ODBC)](https://learn.microsoft.com/en-us/sql/odbc/microsoft/string-functions-visual-foxpro-odbc-driver?view=sql-server-ver16)
* Content Source: [docs/odbc/microsoft/string-functions-visual-foxpro-odbc-driver.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/microsoft/string-functions-visual-foxpro-odbc-driver.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by rwestMSFT** [comment]
@Gahadue Do you have a question or feedback for us?

**Comment by rwestMSFT** [comment]
Closing this as non-actionable.
