### ISSUE TITLE
Incorrect information about IFI and TDE

### ISSUE THREAD

**Issue by scorellis** [MicrosoftDocs/sql-docs#9554]
here at this [link](https://learn.microsoft.com/en-us/sql/relational-databases/databases/database-instant-file-initialization?view=sql-server-ver16#:~:text=This%20use%20of%20instant%20file%20initialization%20is%20allowed%20for%20transaction%20log%20growth%20for%20databases%20which%20have%20Transparent%20Data%20Encryption%20(TDE)%20due%20to%20the%20nature%20of%20how%20the%20transaction%20log%20file%20is%20expanded%20and%20the%20fact%20that%20the%20transaction%20log%20is%20written%20into%20in%20a%20serial%20fashion.) 

"This use of instant file **initialization is allowed** for transaction log growth for databases which have Transparent Data Encryption (TDE) due to the nature of how the transaction log file is expanded and the fact that the transaction log is written into in a serial fashion."

I'm pretty sure it should be "is NOT allowed" especially because this [link](https://learn.microsoft.com/en-us/sql/relational-databases/databases/database-instant-file-initialization?view=sql-server-ver16#:~:text=Some%20feature%20usage%2C%20such%20as%20Transparent%20Data%20Encryption%20(TDE)%2C%20can%20prevent%20instant%20file%20initialization.) says the exact opposite. 

"Some feature usage, **such as [Transparent Data Encryption** (TDE)](https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption?view=sql-server-ver16), can prevent instant file initialization."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66ff457d-65be-2e16-7460-8dc5c77286a7
* Version Independent ID: 69640716-d7da-dafa-3028-0534181f4645
* Content: [Database instant file initialization - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/databases/database-instant-file-initialization?view=sql-server-ver16)
* Content Source: [docs/relational-databases/databases/database-instant-file-initialization.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/database-instant-file-initialization.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by rwestMSFT** [comment]
Investigating. Thank you for your feedback.

**Comment by rwestMSFT** [comment]
@scorellis IFI is supported on SQL Server 2022 and Azure SQL Database, for the transaction log, if TDE is enabled on the database. I will clarify the note you reference, but the article is correct.

The refreshed article will publish in the next few days.
