### ISSUE TITLE
[Azure SQL] ETA for Hyperscale Serverless Elasticpool GA?

### ISSUE THREAD

**Issue by KenADev** [MicrosoftDocs/sql-docs#9561]
Hello,

the Hyperscale Serverless Tier for Azure SQL Elasticpools has been in Public Preview since February 2023
https://azure.microsoft.com/de-de/updates/public-preview-serverless-hyperscale-in-azure-sql-database/

Is there an expected date for the General Availability yet?

Best,

KenADev

**Comment by rwestMSFT** [comment]
This is the documentation repository. We cannot comment on future plans by the product group. Thanks for stopping by.
