### ISSUE TITLE
Inquiry and Assistance Request Regarding prose.codeaccelerator Usage

### ISSUE THREAD

**Issue by weissye** [MicrosoftDocs/sql-docs#9565]
[Enter feedback here]

Dear Microsoft Azure Support Team,

My name is Yeshayahu, and I am a Ph.D. student specializing in Computer Science at Ben-Gurion University. I'm reaching out to ask for help with using the 'prose.codeaccelerator' service in the context of my research.

In my research, I am leveraging the capabilities of prose.codeaccelerator to enhance my work in Python, using Azure Data Studio Notebook as my primary platform. Given that prose.codeaccelerator is no longer supported through the 'pip' tool, I have explored alternative methods to integrate it into my workflow.

After visiting 'https://prose-python-packages.azurewebsites.net/', I successfully downloaded and installed the 'azureml-codeaccelerator' Python wheel. However, I am facing challenges in understanding the list of attributes and APIs available within the 'azureml-codeaccelerator' package.

Additionally, I attempted to download 'prose-codeaccelerator,' but encountered an error message during the installation process. Gaining access to the proper documentation or guidance on the attributes and APIs associated with these packages would greatly benefit my research.

I am eager to learn more about the functionalities and capabilities of prose.codeaccelerator and would appreciate any help you could give me with this. Specifically, I would like information on the APIs and attributes that can be used within the 'azureml-codeaccelerator' package.

Furthermore, I would like to inquire about the error message I encountered while attempting to install 'prose-codeaccelerator' and seek guidance on resolving this issue.

I understand that your team's expertise and support are invaluable. I hope you could share insights, documentation, or any relevant resources that would aid me in effectively using prose.codeaccelerator for my research.

I kindly request that the response be sent to my email address at weissye@post.bgu.ac.il, and I would be grateful for any assistance you can provide.

Thank you very much for your time and consideration. I look forward to hearing from you about this.

Best regards,

Yeshayahu Weiss
Ben-Gurion University in Israel
weissye@post.bgu.ac.il

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51fde3a2-6da5-a1ef-1f39-39fc9cec1f94
* Version Independent ID: 2ac1cb67-1f32-cf14-b65a-4d7cf2a77e36
* Content: [Generate code for data wrangling tasks - Azure Data Studio](https://learn.microsoft.com/en-us/sql/big-data-cluster/use-prose-for-big-data-automation?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/use-prose-for-big-data-automation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/use-prose-for-big-data-automation.md)
* Service: **sql**
* Sub-service: **machine-learning-bdc**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hi Yeshayahu Weiss-
This avenue of communication is for documentation feedback. This may not be the best forum for your question. I suggest you visit the repo for the PROSE code accelerator here: https://github.com/Microsoft/prose-codeaccelerator. 

If you have further technical questions, I recommend [Microsoft Q&A (SQL Server)](https://docs.microsoft.com/answers/products/sql-server), [Microsoft Q & A (Azure SQL)](https://docs.microsoft.com/answers/products/azure?product=databases), [SQL Server Feedback](https://feedback.azure.com/forums/908035-sql-server).
