### ISSUE TITLE
在表结构设计的时候浏览器时候增加说明一列，不用每次都点字段才知道

### ISSUE THREAD

**Issue by gallop1** [MicrosoftDocs/sql-docs#9566]
不方便，感觉每次去掉，没有PL/SQL那些查看数据库表结构方便，用起来很麻烦。请立刻更新打补丁或者告诉我相关解决方案。请及时在客户端更新啊。

**Comment by rwestMSFT** [comment]
This is not the correct place to request product features. Please visit feedback.azure.com and provide your feedback in the "SQL" section.
