### ISSUE TITLE
在新建查询之后的界面查询分析器里面外面增加一个格式化SQL语句的按钮

### ISSUE THREAD

**Issue by gallop1** [MicrosoftDocs/sql-docs#9567]
直接格式化排版SQL语句，不用再麻烦去Notepad++里面排版。这样既可以节省时间，也可以对自己眼睛舒服很多了。请尽快完成，谢谢。

**Comment by rwestMSFT** [comment]
This is not the correct place to request product features. Please visit feedback.azure.com and provide your feedback in the "SQL" section.

**Comment by gallop1** [comment]
@rwestMSFT But they didn't have an official developer reply to me.Why？I have already provided feedback on the website you mentioned, but no one paid attention to me.

**Comment by rwestMSFT** [comment]
I have no insight into the feedback site. I am a content developer, and this is the documentation repository. Thank you for stopping by.
