### ISSUE TITLE
Correction in TSQL Code

### ISSUE THREAD

**Issue by Santro2511** [MicrosoftDocs/sql-docs#9572]
1. Key name used in EncryptByKey is wrong in 1st TSQL code. It should be key_ReplDataShare instead of key_DataShare

**Updated Code -** 

-- Execute at the Publisher on the publication database.
USE AdventureWorks2022;
GO

-- Create the database master key if it doesn't exist.
IF NOT EXISTS (SELECT * FROM sys.symmetric_keys 
    WHERE [name] LIKE '%DatabaseMasterKey%')
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'Pub$p@55w0Rd';

-- Create the cert_keyProtection certificate if it doesn't exist.
IF NOT EXISTS (SELECT * FROM sys.certificates 
    WHERE [name] = 'cert_keyPublisher')
CREATE CERTIFICATE [cert_keyPublisher] 
    WITH SUBJECT = 'Publisher Key Protection';

-- Create the key_ReplDataShare symmetric key if it doesn't exist.
IF NOT EXISTS (SELECT * FROM sys.symmetric_keys 
    WHERE [name] = 'key_ReplDataShare')
CREATE SYMMETRIC KEY [key_ReplDataShare] WITH
    KEY_SOURCE = 'My key generation bits. This is a shared secret!',
    ALGORITHM = AES_256, 
    IDENTITY_VALUE = 'Key Identity generation bits. Also a shared secret'
    ENCRYPTION BY CERTIFICATE [cert_keyPublisher];
GO 

-- Open the encryption key.
OPEN SYMMETRIC KEY [key_ReplDataShare]
    DECRYPTION BY CERTIFICATE [cert_keyPublisher];
GO

-- Create a new CreditCardApprovalCode column in the SalesOrderHeader table.
ALTER TABLE Sales.SalesOrderHeader 
    ADD EncryptedCreditCardApprovalCode VARBINARY(256) NULL;
GO

-- Insert encrypted data from the CreditCardApprovalCode column.
UPDATE Sales.SalesOrderHeader
SET EncryptedCreditCardApprovalCode
    = EncryptByKey(Key_GUID('key_ReplDataShare'), CreditCardApprovalCode);
GO

CLOSE SYMMETRIC KEY [key_ReplDataShare];
GO

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44af891d-6aa8-9422-5048-80bed7d36035
* Version Independent ID: 7898b8ef-2b39-4ac4-828c-48bf242a66a9
* Content: [Replicate encrypted columns (SSMS) - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/replication/security/replicate-data-in-encrypted-columns-sql-server-management-studio?view=sql-server-ver16)
* Content Source: [docs/relational-databases/replication/security/replicate-data-in-encrypted-columns-sql-server-management-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/security/replicate-data-in-encrypted-columns-sql-server-management-studio.md)
* Service: **sql**
* Sub-service: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by rwestMSFT** [comment]
Thanks @Santro2511, we have an internal PR that will correct this issue, which will publish in the next day or so.
