### ISSUE TITLE
Disabling all nonsemantic indexes of all the tables of a customer database (improvment)

### ISSUE THREAD

**Issue by SQL-pro** [MicrosoftDocs/sql-docs#9573]
[Enter feedback here]

-- TSQL script to do that stuff:

```
DECLARE @SQL NVARCHAR(max) = N'';
SELECT @SQL = @SQL 
            + N'ALTER INDEX ' + QUOTENAME(i.name) + N' ON '
            + QUOTENAME(s.name) + N'.'
            + QUOTENAME(o.name) + N' DISABLE;'
FROM   sys.indexes AS i
       JOIN sys.objects AS o 
          ON i.object_id = o.object_id
       JOIN sys.schemas AS s 
          ON o.schema_id = s.schema_id
WHERE  o.is_ms_shipped = 0
  AND  o.type IN ('U', -- user tables
                  'V'  -- indexed views
                 )
  AND  i.index_id > 0  
  AND  i.is_primary_key = 0
  AND  i.is_unique = 0
  AND  i.is_unique_constraint = 0
  AND  i.is_hypothetical = 0
  AND  i.is_disabled = 0
  AND  i.type IN (1, 2, -- BTree (aka rowstore)
                  5, 6  -- Columnar (aka columnstore)
                  );
EXEC (@SQL);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2bb45cd-9675-aa90-9ca2-c27774d85e3f
* Version Independent ID: 7ca9be50-df61-4fa3-9254-7879c3b6d120
* Content: [Disable Indexes and Constraints - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/indexes/disable-indexes-and-constraints?view=sql-server-ver16)
* Content Source: [docs/relational-databases/indexes/disable-indexes-and-constraints.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/disable-indexes-and-constraints.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rwestMSFT** [comment]
@SQL-pro It's not clear from this issue what it is you're trying to do. Can you please create a pull request to make the change instead? You can edit the article in question using the pencil icon in the top right.

**Comment by SQL-pro** [comment]
It is not an issue it is a complement to the page about disabling indexes and this is a script to disable all indexes of the user’s table in a database

 

De : Randolph West MSFT ***@***.***> 
Envoyé : jeudi 28 décembre 2023 19:52
À : MicrosoftDocs/sql-docs ***@***.***>
Cc : SQL-pro ***@***.***>; Mention ***@***.***>
Objet : Re: [MicrosoftDocs/sql-docs] Disabling all nonsemantic indexes of all the tables of a customer database (improvment) (Issue #9573)

 

@SQL-pro <https://github.com/SQL-pro>  It's not clear from this issue what it is you're trying to do. Can you please create a pull request to make the change instead? You can edit the article in question using the pencil icon in the top right.

**Comment by rwestMSFT** [comment]
Then, please create a pull request. Thank you.

**Comment by WilliamAntonRohm** [comment]
@SQL-pro -- thank you for your followup.

@rwestMSFT -- thank you for your suggestion.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
