### ISSUE TITLE
Error in setup - liblber-2.4.so.2 missing - Server 22.04

### ISSUE THREAD

**Issue by NJ-Brad** [MicrosoftDocs/sql-docs#9575]
Running Ubuntu 22.04.3 (Server)
Get through step 3 no problem (thanks to the updated key instructions)
When I run
`sudo /opt/mssql/bin/mssql-conf setup`
I end up with this error
`/opt/mssql/bin/sqlservr: error while loading shared libraries: liblber-2.4.so.2: cannot open shared object file: No such file or directory`

I saw previous issues with this error message (they were closed stating that 22.04 wasn't supported at the time)
Currently this page show installation instructions for 22.04, which leads me to believe that it is supported now.  Could this be a difference between workstation and server versions of Ubuntu?

**Comment by NJ-Brad** [comment]
This is the page I am referring to : [Quickstart: Install SQL Server and create a database on Ubuntu](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16&tabs=ubuntu2204)  Dated 12/20/2023

**Comment by NJ-Brad** [comment]
I have installed Ubuntu 22.04 workstation without error.  It appears that the issue is related to the server version only.

**Comment by rwestMSFT** [comment]
Thanks for the feedback and further investigation. Unfortunately this falls outside of the realm of documentation, so I'll be closing the issue.

I will let the product group know and we'll continue to monitor internally.

**Comment by amitkh-msft** [comment]
![image](https://github.com/MicrosoftDocs/sql-docs/assets/119350246/218735ca-71b0-4190-9feb-105d24f1f8e5)
It does work for me, I am not sure what is different but could you open a issue here https://github.com/microsoft/mssql-docker/issues and give further details please.

**Comment by NJ-Brad** [comment]
I concur with closing this ticket.  I have completed the installation multiple times on server 2204, without issue.

**Comment by juniorbuba** [comment]
Hi @NJ-Brad , I'm currently facing this error on Ubuntu 22.04, can you share pointers on how you were able to complete the installation of mssql-server?

**Comment by NJ-Brad** [comment]
I believe the biggest issue was following the wrong instructions initially.

I followed the instructions at https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16

One thing that I did not notice was that the wrong Ubuntu version was selected in the Install SQL Server section.  You have to select the 22.04 version.  The direct link for this is https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16&tabs=ubuntu2204

Good Luck
