### ISSUE TITLE
Winget installation instructions for SSMS

### ISSUE THREAD

**Issue by tbeest** [MicrosoftDocs/sql-docs#9581]
The SSMS page lacks winget instructions, unlike the [.NET installation page](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net80#install-with-windows-package-manager-winget)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-gb/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by rwestMSFT** [comment]
I spoke to a PM, and apparently you can install SSMS using `winget install ssms`.

The SQL Server product group is distinct from the .NET product group, and our content is managed differently.

I would need to find out if winget is a supported way of installing and managing SSMS. My main concern is that preview versions of SSMS need to be removed before installing supported versions, which adds significant complexity when dealing with a command-line silent installer like winget or Chocolatey.

**Comment by rwestMSFT** [comment]
Upon further investigation, there appears to be a known issue with selecting a localized version of SSMS with winget. For this reason, don't think it would be prudent to offer this on the download page at this time.

https://github.com/microsoft/winget-pkgs/issues/102724

Thank you for your feedback. I am closing this issue.
