### ISSUE TITLE
Add the option to Disable the promt of saving the queries. 

### ISSUE THREAD

**Issue by ksexasa** [MicrosoftDocs/sql-docs#9582]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1813bf-093a-3fd6-19de-a6b1fced00c8
* Version Independent ID: 4eb5a42a-4d69-cf96-55bd-01f3e40042af
* Content: [Save Changes - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/menu-help/save-changes?view=sql-server-ver16&f1url=%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.SaveChangesDlg)%3Bk(DevLang-TSQL)%26rd%3Dtrue)
* Content Source: [docs/ssms/menu-help/save-changes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/menu-help/save-changes.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by rwestMSFT** [comment]
Hi @ksexasa.

As it currently stands, this issue is not clear, and will be closed shortly.

- If this is a product feature request, please direct your query to https://feedback.azure.com, under the "SQL" section.

- If this is a documentation enhancement request, please provide more information.

**Comment by rwestMSFT** [comment]
@ksexasa I am closing this issue because we haven't heard from you.
