### ISSUE TITLE
SYSTEM_USER - Returns guids in format of<ClientId>@<TenantId> for managed identity logins - Seeking a friendly name

### ISSUE THREAD

**Issue by b-mcbride** [MicrosoftDocs/sql-docs#9584]
My organization is leveraging managed identity from Azure App Services when connecting to SQL Server.  Is it possible to get the principal name, the name found in `sys.database_principals` or `sys.server_principals`, rather than a format of two guids separated by @ like this <ClientId>@<TenantId>?  

My organization logs the value returned by SYSTEM_USER to audit tables and two guids in the format of <ClientId>@<TenantId> is not friendly or readable.

Is there another SQL keyword I should be using?

**Comment by rwestMSFT** [comment]
@b-mcbride Unfortunately this is the documentation repository, and your question sounds like a support request, which we can't answer.

I suggest you either open a feedback item on feedback.azure.com, if this is a feature you'd like added to the Database Engine. Alternatively, you can look for support through Microsoft Support if you have an account manager, or third-party resources like StackOverflow.

**Comment by b-mcbride** [comment]
My apologies @rwestMSFT . Perhaps, in the future, the documentation at [SYSTEM_USER (Transact-SQL)](https://learn.microsoft.com/en-us/sql/t-sql/functions/system-user-transact-sql?view=sql-server-ver16) can be enhanced to include the behavior I am seeing with external logins from managed identities. It would benefit others.

**Comment by rwestMSFT** [comment]
@b-mcbride

No need to apologize, Brian. I'm making a note here to speak to my colleague who owns this article, and we'll add it to the team backlog. It may take several months to get to it, but we do keep track of documentation enhancement requests.

Thanks for stopping by. We appreciate it.
