### ISSUE TITLE
Please update: SQL Server 2022 doc refers to 2019 version.

### ISSUE THREAD

**Issue by rsilvabcib** [MicrosoftDocs/sql-docs#9594]
Hello,

the 1st line of this document for SQL Server 2022 is not updated: 

"In this guide, you learn how to upgrade your user databases from previous versions of SQL Server to SQL Server **_2019_** by using the Data Migration Assistant (DMA)."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1ab40d-6585-03f3-bec9-f8c14eefe453
* Version Independent ID: 3617b434-412c-9694-c3d5-dbce2825ebe4
* Content: [Upgrade SQL Server to SQL Server 2019 - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/migrate/guides/sql-server-to-sql-server-upgrade-guide?view=sql-server-ver16)
* Content Source: [docs/sql-server/migrate/guides/sql-server-to-sql-server-upgrade-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/migrate/guides/sql-server-to-sql-server-upgrade-guide.md)
* Service: **sql**
* Sub-service: **migration-guide**
* GitHub Login: @ajithkr-ms
* Microsoft Alias: **ajithkr**

**Comment by WilliamAntonRohm** [comment]
@rsilvabcib -- thank you for your feedback.

@ajithkr-ms -- please look into this issue.

**Comment by rwestMSFT** [comment]
@rsilvabcib Thank you for your feedback.

We have staged an update to this article, which will publish in the next day or so.
