### ISSUE TITLE
Documentation unclear about Preview

### ISSUE THREAD

**Issue by BillMedland** [MicrosoftDocs/sql-docs#9601]
[Enter feedback here]
The page makes clear that if one has "an earlier _preview_ version of SSMS 19 installed" then one must uninstall it. It then goes on to note that "You can see if you have a preview version by going to the **Help > About**", but fails to note what hint on that window will indicate a _preview_ version (versus a non-preview version which presumably does not need to be uninstalled).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-ca/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
@BillMedland The version of SSMS 19 would include the text "Preview", for example, SSMS 19 Preview 3.

**Comment by WilliamAntonRohm** [comment]
@BillMedland -- Bill, thank you for your feedback.

@erinstellato-ms -- Erin, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
