### ISSUE TITLE
Sql server on wsl works

### ISSUE THREAD

**Issue by ahlstro** [MicrosoftDocs/sql-docs#9604]
The [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/about) isn't supported as an installation target for SQL Server.

This is not true, I got it working on wsl2 following the document instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16&tabs=ubuntu2204)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
Hi @ahlstro. We don't support WSL as a production environment. That's what "isn't supported" means. A lot of things work on a lot of platforms, but we can't support every scenario.

Thank you for your understanding.

**Comment by rwestMSFT** [comment]
@ahlstro Thank you for your feedback. Unfortunately our policy is that we don't document unsupported scenarios. Because there are countless ways to get SQL Server to run on multiple platforms, we'd be opening ourselves up to support issues by doing so. We appreciate your suggestion, though.
