### ISSUE TITLE
Incorrect C# code sample syntax

### ISSUE THREAD

**Issue by Hardrada** [MicrosoftDocs/sql-docs#9610]
The c# line
db = srv.Databases("AdventureWorks2022");  
is incorrect and should read db = srv.Databases["AdventureWorks2022"];  as it is a collection

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 304a74b7-d74a-e64d-f0e7-7759b758e5ab
* Version Independent ID: 4d1dc0fd-76c1-e78c-ecb7-9e478ebbdea2
* Content: [Handling SMO Events - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/create-program/handling-smo-events?view=sql-server-ver16)
* Content Source: [docs/relational-databases/server-management-objects-smo/create-program/handling-smo-events.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/server-management-objects-smo/create-program/handling-smo-events.md)
* Service: **sql**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by rwestMSFT** [comment]
Thanks for your feedback, @Hardrada. I'll confirm with the product group, and make sure this change is included in other articles.

**Comment by rwestMSFT** [comment]
We have staged an update, which will publish in the next day or so. Thanks again for your contribution.
