### ISSUE TITLE
Error on this page

### ISSUE THREAD

**Issue by jjpinsky** [MicrosoftDocs/sql-docs#9615]
In the examples provided for returning data from a stored procedure using output parameters, I think the following paragraph is in error:

_The following example calls the procedure created in the first example and saves the output value returned from the called procedure in the **@SalesYTD** variable, which is local to the calling program._

The calling program saves the output parameter to @SalesYTDBySalesPerson, not to @SalesYTD.  Note that @SalesYTD is actually a parameter to the sp, not the local variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 56f56caa-8938-8891-571e-170235af43ad
* Version Independent ID: 85e82726-114f-93e9-b5bc-c49b47229ea2
* Content: [Return data from a stored procedure - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/stored-procedures/return-data-from-a-stored-procedure?view=sql-server-ver16)
* Content Source: [docs/relational-databases/stored-procedures/return-data-from-a-stored-procedure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/stored-procedures/return-data-from-a-stored-procedure.md)
* Service: **sql**
* Sub-service: **stored-procedures**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Nice catch, @jjpinsky. A correction for this doc is in flight. Thanks for the time and attention to report that sentence.
