### ISSUE TITLE
Overly Permissive RBAC Suggestion for Log Replay Service (LRS)

### ISSUE THREAD

**Issue by blakedeckard** [MicrosoftDocs/sql-docs#9617]
https://github.com/MicrosoftDocs/sql-docs/blob/live/azure-sql/managed-instance/log-replay-service-migrate.md

Under the section Azure RBAC Permissions, it states that a user requires one of:
1) Subscription Owner role, 
2) [SQL Managed Instance Contributor](https://github.com/MicrosoftDocs/sql-docs/blob/live/azure/role-based-access-control/built-in-roles#sql-managed-instance-contributor) role, or 
3) a "Custom role with the following permission: Microsoft.Sql/managedInstances/databases/*".

This violates the principle of least privilege.

Subscription owner has the permission: Microsoft.Sql/managedInstances/databases/*

So, I suggest we reduce this to:
1) [SQL Managed Instance Contributor](https://github.com/MicrosoftDocs/sql-docs/blob/live/azure/role-based-access-control/built-in-roles#sql-managed-instance-contributor) role, or 
2) a role with the following permission: Microsoft.Sql/managedInstances/databases/*

in order to prevent suggesting Subscription Owner, but still being explicit about the needed permissions

**Comment by blakedeckard** [comment]
See: https://github.com/MicrosoftDocs/sql-docs/pull/9618

**Comment by WilliamAntonRohm** [comment]
@blakedeckard -- thank you for your feedback and contribution.

@danimir -- please review [PR 9618](https://github.com/MicrosoftDocs/sql-docs/pull/9618).
