### ISSUE TITLE
sqlpackage export

### ISSUE THREAD

**Issue by rangosheriff** [MicrosoftDocs/sql-docs#9620]
Is it possible to export data only of all the tables in the DB using sqlpackage export action? Schema is not to be included in the .bacpac file.

**Comment by dzsquared** [comment]
This isn't possible with the current functionality - a .bacpac file is defined as being able to be imported to a new database to create the objects and import the data.
What would be the next step for the data export you're looking for?  That would help in suggesting an alternative approach.
#assign:dzsquared

**Comment by rwestMSFT** [comment]
@rangosheriff I'm closing this issue because we haven't heard back from you. If you decide to respond, please feel free to comment below.
