### ISSUE TITLE
Excellent resource for compatibility checking

### ISSUE THREAD

**Issue by NottmTony** [MicrosoftDocs/sql-docs#9624]
I found this page very useful while trying to determine an upgrade path for SQL Server and a Java application using Java 7,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 428f1edd-45d8-d0e1-5c77-970b18c877d8
* Version Independent ID: fe980aa0-299d-c16f-1b3e-8b5300cb70c1
* Content: [Support matrix - JDBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-ver16#sql-version-compatibility)
* Content Source: [docs/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by rwestMSFT** [comment]
@NottmTony Thank you for your feedback. It is very much appreciated.
