### ISSUE TITLE
Azure Active Directory authentication doc miss WorkloadIdentityCredential

### ISSUE THREAD

**Issue by sbebrys** [MicrosoftDocs/sql-docs#9629]
Azure Active Directory authentication doc miss WorkloadIdentityCredential in [docs/connect/ado-net/sql/azure-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/ado-net/sql/azure-active-directory-authentication.md) which is part of DefaultAzureCredential

**Comment by David-Engel** [comment]
You are correct that WorkloadIdentityCredential was indirectly added to the DefaultAzureCredential chain in Microsoft.Data.SqlClient 5.1.4 with the Azure.Identity dependency version bump from 1.7 to 1.10. I'll update the doc page.

Thanks,
David

**Comment by David-Engel** [comment]
I've pushed updates to this article adding WorkloadIdentityCredential (and AzureDeveloperCliCredential - another missing one) to the list. They should appear later today.

Thanks,
David

#please-close
