### ISSUE TITLE
Wrong microsoft.asc signed-by path in Debian 12 source list when installing ODBC driver

### ISSUE THREAD

**Issue by guangyu-he** [MicrosoftDocs/sql-docs#9633]
Hello, I am trying to install ODBC driver in a Debian 12 server.

Accroding to the documentation page, the signed microsoft asc file is stored in `/etc/apt/trusted.gpg.d/microsoft.asc`, while `curl https://packages.microsoft.com/config/debian/12/prod.list` is giving me 

deb [arch=amd64,arm64,armhf signed-by=**/usr/share/keyrings/microsoft-prod.gpg**] https://packages.microsoft.com/debian/12/prod bookworm main, 

in which the `signed_by` field leads to a nonexistent path (I suppose it should be `/etc/apt/trusted.gpg.d/microsoft.asc`).
User may need to manually change it to the correct key path to proceed with `apt update`.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15&tabs=debian18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@guangyu-he -- Guangyu, thank you for your thorough feedback.

@David-Engel -- David, please look into this issue.

**Comment by rwestMSFT** [comment]
@guangyu-he Thank you for raising this. We will be closing this issue and monitoring internally.

AB#241035.
