### ISSUE TITLE
This feature works with SSMS version 17.9.1 and earlier

### ISSUE THREAD

**Issue by JulioQc** [MicrosoftDocs/sql-docs#9634]
Considering "This feature works with SSMS version 17.9.1 and earlier." why is this whole page still displayed for SQL 2022? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9b244fe7-aff6-2d79-31f0-c6cc82ab2f5e
* Version Independent ID: 63bf372c-1166-646a-a1e4-3b22af12a1c2
* Content: [Run the Transact-SQL Debugger - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/scripting/run-the-transact-sql-debugger?view=sql-server-ver16)
* Content Source: [docs/ssms/scripting/run-the-transact-sql-debugger.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/run-the-transact-sql-debugger.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@JulioQc -- Julien, thank you for your question.

@markingmyname -- Mark, please look into this issue.

**Comment by rwestMSFT** [comment]
This is a great question, and it's because we want customers using SQL Server 2022 to see that if they want to use this feature, it's only available in an older version of SSMS.

#please-close
