### ISSUE TITLE
incorrect sample code

### ISSUE THREAD

**Issue by hamishinglis** [MicrosoftDocs/sql-docs#9638]
[Enter feedback here]

It seems there might be an error or typo in your code. In the provided code snippet, you're using the variable name "test" for the training set, but you might have intended to use the variable name "df"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6126902-bcdc-3d8e-5977-ed58b8bf00f1
* Version Independent ID: 9dc69621-c9ce-840a-1dac-5da135f50515
* Content: [Python tutorial: Prepare data - SQL machine learning](https://learn.microsoft.com/en-us/sql/machine-learning/tutorials/python-ski-rental-linear-regression-prepare-data?view=sql-server-ver16)
* Content Source: [docs/machine-learning/tutorials/python-ski-rental-linear-regression-prepare-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/tutorials/python-ski-rental-linear-regression-prepare-data.md)
* Service: **sql**
* Sub-service: **machine-learning**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@hamishinglis -- thank you for catching this.  I am updating the article.
