### ISSUE TITLE
Adding new columns not automated to update Change Tables

### ISSUE THREAD

**Issue by datageekcb** [MicrosoftDocs/sql-docs#9640]
[Enter feedback here]
you should also mention that adding new columns does not update the change table to add new columns. I don't see that specifically documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa8712c4-728a-4ef7-69ad-e1f28119feff
* Version Independent ID: aa8712c4-728a-4ef7-69ad-e1f28119feff
* Content: [Known issues and errors with CDC - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/track-changes/known-issues-and-errors-change-data-capture?view=sql-server-ver16)
* Content Source: [docs/relational-databases/track-changes/known-issues-and-errors-change-data-capture.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/track-changes/known-issues-and-errors-change-data-capture.md)
* Service: **sql**
* GitHub Login: @croblesm
* Microsoft Alias: **roblescarlos**

**Comment by rwestMSFT** [comment]
@datageekcb Thank you for your feedback. I am closing this issue because we are tracking it internally.

AB#205784
