### ISSUE TITLE
Typo issue in xml

### ISSUE THREAD

**Issue by QuickyBooster** [MicrosoftDocs/sql-docs#9645]
I was reading this article: [Configure multiple-subnet Always On Availability Groups and failover cluster instances](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-multiple-subnet?view=sql-server-ver16#update-the-cib).

I followed the instructions, but until [Update the CIB, section2] :
```
<instance attributes id="<NameForAttribute>">
    <nvpair id="<NameForIP>" name="ip" value="<IPAddress>"/>
</instance attributes>
```
It doesn't work beacause missing "_" in ```<instance attributes ...>```. The correct one should be ```<instance_attributes ...>```, I corrected on my machine and it worked.

Please take a look at this!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13f1751a-84fd-682c-4263-07f026cb857b
* Version Independent ID: d40a6ed5-a98c-f9af-eb21-7f2696818844
* Content: [Configure multiple-subnet availability group & FCI (Linux) - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-multiple-subnet?view=sql-server-ver16#configuration-with-pacemaker)
* Content Source: [docs/linux/sql-server-linux-configure-multiple-subnet.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-multiple-subnet.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rwestMSFT** [comment]
Great find! We'll get on this in the next day or so. We are planning on refreshing FCI content in the coming months as well, so stay tuned.

#assign:rwestMSFT

**Comment by QuickyBooster** [comment]
@rwestMSFT I updated the link, sorry for my mistake. Have a nice day!
