### ISSUE TITLE
A better example for the S3 Location format

### ISSUE THREAD

**Issue by renbud** [MicrosoftDocs/sql-docs#9649]
I had difficulty finding an example LOCATION format to connect to a simple S3 bucket.

Here is what finally worked after many attempts

`CREATE EXTERNAL DATA SOURCE s3_ds
WITH (
    LOCATION = 's3://mypolybucket.s3.amazonaws.com:443',
    CREDENTIAL = s3_dc
);`

Where mypolybucket is the name of my S3 bucket.
I think its important to point out that the port 443 is required as well as the s3:// prefix an the url in the form mybucket.s3.amazonaws.com.  This works for the vanilla case for folks that have not mapped alternate names.

The generic server:port in the documentation left me guessing for ages. I was also led astray by a lot of misleading information about the old 2019 versions of poly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44b5f703-7faa-2e18-334b-0f95ba959516
* Version Independent ID: 44b5f703-7faa-2e18-334b-0f95ba959516
* Content: [Access external data: S3-compatible object storage - PolyBase - SQL Server](https://learn.microsoft.com/en-au/sql/relational-databases/polybase/polybase-configure-s3-compatible?view=sql-server-ver16)
* Content Source: [docs/relational-databases/polybase/polybase-configure-s3-compatible.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-s3-compatible.md)
* Service: **sql**
* Sub-service: **polybase**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hi @renbud, thanks for taking time. We welcome this feedback and look forward to improving our docs. We're reviewing internally.

**Comment by WilliamDAssafMSFT** [comment]
Hi @renbud, thanks again for providing this feedback. It seems that the S3-compatible standard has not changed, but Amazon's S3 has. We have a doc update in flight. I'm glad you are no longer blocked, and very much appreciate the time.

**Comment by WilliamDAssafMSFT** [comment]
Hi @renbud, thanks again for providing this feedback. We've added more specific syntax reference for AWS's multiple supported URL formats. For example, https://learn.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql?branch=main&branchFallbackFrom=pr-en-us-29745&view=sql-server-ver16&tabs=dedicated#location--prefixpathport-3

Hopefully, that would unblock customers in the same spot. Thanks again for drawing attention to this.
