### ISSUE TITLE
coding

### ISSUE THREAD

**Issue by Nishanthrr** [MicrosoftDocs/sql-docs#9650]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5fca52fb-b9a8-1de7-0dde-f95cf4983ee5
* Version Independent ID: 72dfda95-c5b2-ce83-8ebe-8eb686b371e6
* Content: [Microsoft Open Database Connectivity (ODBC) - Open Database Connectivity (ODBC)](https://learn.microsoft.com/en-us/sql/odbc/microsoft-open-database-connectivity-odbc?view=sql-server-ver16)
* Content Source: [docs/odbc/microsoft-open-database-connectivity-odbc.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/microsoft-open-database-connectivity-odbc.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
#please-close
