### ISSUE TITLE
Light weight pooling can't be enabled for Express Edition

### ISSUE THREAD

**Issue by moematsuo** [MicrosoftDocs/sql-docs#9653]
I discovered that SQL Server Express does not support light weight pooling. 
This document should mention this limitation for Express Edition. 
https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/lightweight-pooling-server-configuration-option?view=sql-server-ver16

Also, another point is that if we try to enable light weight pooling on Express, we will get Error 5836 like the below.

Error: 5836, Severity: 16, State: 1.  Lightweight pooling is not supported on this platform or in this edition of SQL Server. 

I failed to apply a CU due to the error. I wish there was some documentation about this issue.

(Repro steps)
1. Set  'lightweight pooling', 1 on Express Edition.
********
exec sp_configure 'show advanced options',1
go
reconfigure
go
exec sp_configure 'lightweight pooling'
go
exec sp_configure 'lightweight pooling', 1
go
********
These queries can change the "config_value"=1. "run_value"=0

2. Apply a CU on the environment.
3. Fail with error 5836. (I guess CU must execute "RECONFIGURE" inside the script)

**Comment by WilliamAntonRohm** [comment]
@moematsuo -- thank you for your feedback.  Are you following a particular learn.microsoft.com article?

**Comment by moematsuo** [comment]
@WilliamAntonRohm
Thank you for checking. I referred this article
https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/lightweight-pooling-server-configuration-option?view=sql-server-ver16
