### ISSUE TITLE
Please add a note regarding required compatibility_level = 130

### ISSUE THREAD

**Issue by bkrifp** [MicrosoftDocs/sql-docs#9657]
Please add a note regarding required compatibility_level = 130 for OPENJSON() along with the SQL Server version.
(I spent an inordinate amount of time tracking down why the examples were not working for me because of this. (One of my databases was set to compatibility_level = 110.)

Thanks.
--BKR

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 991167bc-4e0e-1fc8-d0bb-f282b51b3321
* Version Independent ID: 0b5cf834-d452-dd57-d51d-268083011e33
* Content: [Work with JSON data in SQL Server - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/json/json-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/json-data-sql-server.md)
* Service: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by rwestMSFT** [comment]
In the Applies to section at the top of this article, we explicitly state that this applies to SQL Server 2016 (13.x) and later versions. I have reviewed the article and agree that a compatibility level note would also be useful.
