### ISSUE TITLE
Add a note about what happened when the compatibility level from some database is changed inside an Always On AG

### ISSUE THREAD

**Issue by andrecrms** [MicrosoftDocs/sql-docs#9658]
I had a customer that raised the question:

What happened if I change the compatibility level of some database in the primary replica??? 
- This will break Always On AG? 
- This will propagate to the secondaries or do I need to change in all replicas manually?

We discovered trough some labs that the change don't break the Always On and is propagated from the primary to the secondaries.

It will be very useful have a note in the documentation about it.

Thanks!
André Rodrigues

**Comment by MashaMSFT** [comment]
Hi @andrecrms , thanks for contacting Microsoft! Changes and operations that are logged on the primary database are replicated to the secondary replicas. Changing the database compatibility level is a logged operation, therefore that change will be replicated to the database on the secondary replica. Changing the compatibility level changes how queries are processed, it does not change the functionality of the database within the server, so it would have no impact on the availability group mechanism.  This behavior is explained in multiple places in our documentation. 

I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further. 

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team

**Comment by andrecrms** [comment]
Hello Masha! Thks for your answer.
