### ISSUE TITLE
this is WRONG , it does not work for Tables .....

### ISSUE THREAD

**Issue by berndesj** [MicrosoftDocs/sql-docs#9663]
when a try this it does not give you the result like in SSMS for the tables relation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1d9a706-27a6-b00f-6e5b-3f7f548a2f4a
* Version Independent ID: d99fd464-baea-24b8-30d7-2cbdb36981a8
* Content: [View the Dependencies of a Table - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/view-the-dependencies-of-a-table?view=sql-server-2016)
* Content Source: [docs/relational-databases/tables/view-the-dependencies-of-a-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/view-the-dependencies-of-a-table.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@berndesj -- thank you for your feedback.  Please provide more details and context for your intended task.

**Comment by rwestMSFT** [comment]
I am closing this, because the function works as documented.
