### ISSUE TITLE
sys.query_store_plan is missing two "applies to" entries

### ISSUE THREAD

**Issue by erikdarlingdata** [MicrosoftDocs/sql-docs#9666]
The columns `plan_forcing_type` and `plan_forcing_type_desc` should have a note that they only apply to SQL Server 2017+, e.g. 

> Applies to: SQL Server (Starting with SQL Server 2017 (14.x))

Thank you for your basic human decency and kindness to mammals large and small in this matter.

**Comment by rwestMSFT** [comment]
Thanks @erikdarlingdata. The underlying article needed a refresh too, so when that is merged, this issue will automatically close.
