### ISSUE TITLE
Header/text mismatch

### ISSUE THREAD

**Issue by miksh7** [MicrosoftDocs/sql-docs#9667]
Mismatch in a number of rows returned

Example B: Searching for **the top ten matches**
The following example uses CONTAINSTABLE to return the description of **the top 5 products** where the Description column contains the word "aluminum" near either the word "light" or the word "lightweight".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ede1b9ce-001a-ab85-6ced-a93148c1f3fe
* Version Independent ID: a5405da9-0640-d348-8911-9b2ce41772ec
* Content: [Limit Search Results with RANK - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/search/limit-search-results-with-rank?view=sql-server-ver16)
* Content Source: [docs/relational-databases/search/limit-search-results-with-rank.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/search/limit-search-results-with-rank.md)
* Service: **sql**
* Sub-service: **search**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@miksh7 Thanks for your feedback. We will refresh the article and include your suggestion in the next publish cycle.
