### ISSUE TITLE
SQL Server document in learn

### ISSUE THREAD

**Issue by dmachanick** [MicrosoftDocs/sql-docs#9672]
This is garbage. I am looking for recommended RAM based on activity and number of users.
If anyone used the RAM shown in the article, the SQL Server would croak.
Please republish this with realistic guidelines.
Use your SQL Server tech evangelist (Don Ward) to provide figures instead of the marketing department.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5dbbe35-6dd7-6ca7-3966-ee9416304d99
* Version Independent ID: c5dbbe35-6dd7-6ca7-3966-ee9416304d99
* Content: [SQL Server 2019: Hardware & software requirements - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-2019?view=sql-server-ver16)
* Content Source: [docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-2019.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-2019.md)
* Service: **sql**
* Sub-service: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by rwestMSFT** [comment]
Closing this as unproductive. Thanks for stopping by.
