### ISSUE TITLE
Typo: "ONLNE"

### ISSUE THREAD

**Issue by rsocol** [MicrosoftDocs/sql-docs#9674]
There is a typo in the "Resumable operations" section: "ONLNE" instead of "ONLINE"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6521b5c9-9bbd-37be-aae8-67921643e222
* Version Independent ID: 6521b5c9-9bbd-37be-aae8-67921643e222
* Content: [Resumable add table constraints - SQL Server & Azure SQL](https://learn.microsoft.com/en-us/sql/relational-databases/security/resumable-add-table-constraints?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/resumable-add-table-constraints.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/resumable-add-table-constraints.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Thanks @rsocol! We appreciate you catching this. I'm fixing this, and the doc will be updated shortly.
