### ISSUE TITLE
Great To Learn

### ISSUE THREAD

**Issue by 324-Joshi-kamal** [MicrosoftDocs/sql-docs#9675]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 983d1291-c218-d6f7-4a01-14dff4bc3d18
* Version Independent ID: 863cb0aa-794e-6546-309e-e526b5cf2bac
* Content: [Tutorial: Getting Started with the Database Engine - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tutorial-getting-started-with-the-database-engine?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tutorial-getting-started-with-the-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tutorial-getting-started-with-the-database-engine.md)
* Service: **sql**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@324-Joshi-kamal -- Kamal, thank you for your kind words.  We appreciate them!

cc @rwestMSFT
