### ISSUE TITLE
GPG key has to be made world-readable for _apt system account to read it (Ubuntu 22.04)

### ISSUE THREAD

**Issue by JmbFountain** [MicrosoftDocs/sql-docs#9678]
in step 1 of "Installing SQL Server on Linux", the Key is written to /usr/share/keyrings/microsoft-prod.gpg, however, it isn't readable by _apt by default. It is necessary to run `chmod a+r /usr/share/keyrings/microsoft-prod.gpg`in order for Apt to be able to read the keyring. Additionally, it is necessary to change the repository list entry to the following:
`deb [arch=amd64,armhf,arm64 signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/ubuntu/22.04/m ssql-server-2022 jammy main`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16&tabs=ubuntu2004)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@JmbFountain -- thank you for your feedback.

@rwestMSFT -- please look into this issue.

**Comment by rwestMSFT** [comment]
I am closing this issue, as we are tracking it internally.
