### ISSUE TITLE
ODBC

### ISSUE THREAD

**Issue by jahernandezp28** [MicrosoftDocs/sql-docs#9691]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de039d46-b6f1-576e-9e8c-d99506ffb16b
* Version Independent ID: 5a6ba40d-657d-d44f-ab94-f6badcc49b5e
* Content: [ODBC Overview - ODBC API Reference](https://learn.microsoft.com/en-us/sql/odbc/reference/odbc-overview?view=sql-server-ver16)
* Content Source: [docs/odbc/reference/odbc-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/odbc-overview.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by rwestMSFT** [comment]
@jahernandezp28 What exactly is the issue you'd like to report?
