### ISSUE TITLE
sys.tables - schema docs missing data_retention_period* columns

### ISSUE THREAD

**Issue by chadbaldwin** [MicrosoftDocs/sql-docs#9709]
I'm not entirely sure what these columns are for, otherwise I would submit a PR. I just came across the discrepancy by happenstance so figured I would submit the issue.

`sys.tables` columns missing from the docs page:

- `data_retention_period`
- `data_retention_period_unit`
- `data_retention_period_unit_desc`

Appears they were introduced with SQL Server 2022 (along with the ledger columns) as I don't see them on any of my 2019 instances.

<https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-tables-transact-sql?view=sql-server-ver16>

<https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-tables-transact-sql.md>

**Comment by rwestMSFT** [comment]
Thanks, @chadbaldwin. I'll add these to the documentation, but they're going to say "internal use only" for the time being.

**Comment by rwestMSFT** [comment]
@chadbaldwin The updated article will be published in the next day or so. I tracked down a PM to explain what the columns are for. This issue will close automatically when our internal PR is merged.
