### ISSUE TITLE
Update SQL Server enabled by Azure Arc branding

### ISSUE THREAD

**Issue by Datachick** [MicrosoftDocs/sql-docs#9712]
The page needs to have text and images updated with the new name _SQL Serve enabled by Azure Arc_, with a priority for graphics since we tend to use them and can't easily update them.

https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/overview?view=sql-server-ver16

I know it's recent. :).

**Comment by MikeRayMSFT** [comment]
@Datachick - thank you!

We've got an initial update submitted: https://github.com/MicrosoftDocs/sql-docs/commit/506ff572981dc1fb656d139282b94a0da8c6424d

More to follow.
