### ISSUE TITLE
Wrong translation from English to Japanese

### ISSUE THREAD

**Issue by marshal115** [MicrosoftDocs/sql-docs#9727]
https://learn.microsoft.com/ja-jp/azure/azure-sql/copilot/copilot-azure-sql-overview?view=azuresql-db#natural-language-to-sql-query
The translation for this title is totally wrong. 

"Natural language to SQL qury" should be translated to "自然言語からSQLへの変換", not "自然言語をDAXクエリに".
DAX is the native language for Power BI and it's absolutely wrong to mention it here. Thanks!

<img width="511" alt="Eng" src="https://github.com/MicrosoftDocs/sql-docs/assets/63047810/0e090c91-facd-4abd-a006-c8f6e4ed2f27">
<img width="524" alt="JP" src="https://github.com/MicrosoftDocs/sql-docs/assets/63047810/306f90b8-2707-4e64-aa9e-08fb9eea79ed">

**Comment by rwestMSFT** [comment]
Please direct your request to https://aka.ms/provide-feedback. We are unable to resolve this from here.
