### ISSUE TITLE
install-sql-server-using-a-configuration (version 2022)

### ISSUE THREAD

**Issue by ZAJDAN** [MicrosoftDocs/sql-docs#9728]
The documentation describes **ConfigurationFile.ini** , but in version 2022 it does not exists any more. 
In version 2022 is generated **Settings.xml**

**Comment by rwestMSFT** [comment]
@ZAJDAN Can you please provide a screenshot demonstrating this? When I installed SQL Server 2022 recently, I was able to use an INI file.

**Comment by rwestMSFT** [comment]
I have just attempted a fresh install using SQL Server 2022, and confirm that the file used is still `ConfigurationFile.ini`.

![image](https://github.com/MicrosoftDocs/sql-docs/assets/97149825/3880fadc-9df0-421e-94a3-dc19535fd0ea)

If you have further information, please feel free to comment below. However, I am closing this issue.

**Comment by ZAJDAN** [comment]
@rwestMSFT 
I forgot to say I install SQL 2022 EXPRESS
There is not **Section Ready to install** and anyway it creates just Settings.xml

**Comment by rwestMSFT** [comment]
@ZAJDAN Can you demonstrate that this is different to earlier versions of SQL Server Express edition?
