### ISSUE TITLE
OptimizedLocking not enabled by default

### ISSUE THREAD

**Issue by PhilM-IT** [MicrosoftDocs/sql-docs#9736]
Duplicate of unresolved closed issue

https://github.com/MicrosoftDocs/sql-docs/issues/8957

If we create a new DB in US East 2 and place that directly in our existing elastic pool, optimized locking is not enabled.

If we create a new db in the same region using serverless compute the property is on as expected.

Opened a ticket late last year or so on this which MS support closed after we had a workaround...

Here I am 6 months later and it's still a problem.

**Comment by PhilM-IT** [comment]
My previous writeup for support. This seemed to be tied at the time to VBS (https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-enclaves?view=sql-server-ver16#supported-enclave-technologies) enabling by default. 

During our recent deploys that isn't happening. (creating the DBs via the Azure UI, VBS is not enabled so isn't part of the problem here).

A few updates. We were able to work around this issue.

1)	VBS seems to be enabling on the newly deploy DBs when deploy via the Az Portal as a serverless DB.
2)	If we deploy directly to the pool via the Az portal or bicep, the resulting DB has OptimizedLocking disabled (which again, should not be the case)
a.	This happens on our xxxxx which is a business critical tier pool
b.	If we try our dev server using a GP pool OptimizedLocking is enabled as it should be (xxxxx)
3)	When we manually deploy using bicep
a.	Serverless – the resulting DB does NOT have VBS enabled
b.	Pool – the resulting DB still has OptimizedLocking disabled (as explain above in #2.a)

Our full workaround for both issues was to deploy via Bicep to serverless (to ensure the OptimizedLocking was enabled). After this we are able to successfully move that DB into the pool without errors (because bicep was able to create the DB without VBS enabled).

**Comment by rwestMSFT** [comment]
We closed that issue because the person who opened it never responded.

**Comment by WilliamDAssafMSFT** [comment]
@PhilM-IT You should follow up with Microsoft support. Any documentation updates as the result of a known issue or incident notes would flow from the product group.
