### ISSUE TITLE
Prerequisites - SQL Server enabled by Azure Arc - Endpoint URL doesn't exist

### ISSUE THREAD

**Issue by RayMaAU** [MicrosoftDocs/sql-docs#9738]
Hi team,

Should we update the endpoint for DPS in the prerequisite doc: [Prerequisites - SQL Server enabled by Azure Arc | Microsoft Learn](https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/prerequisites?view=sql-server-ver16&tabs=azure#connect-to-azure-arc-data-processing-service)

The endpoint URL is in a wrong format and the requirements has been updated, now only require to whitelist specific subdomains, described here: https://learn.microsoft.com/en-us/sql/sql-server/azure-arc/troubleshoot-telemetry-endpoint?view=sql-server-ver16#endpoint-reference

Thanks.

**Comment by RayMaAU** [comment]
The endpoint URLs have been fixed. However, I think we still need to mention the new endpoint reference used by the new SQL extension.

**Comment by rwestMSFT** [comment]
@RayMaAU Since GitHub Issues is being disabled for this repo shortly, please can you use internal comms to discuss any outstanding issues.
