### ISSUE TITLE
Translation mistake in chinese doc

### ISSUE THREAD

**Issue by arkonzz** [MicrosoftDocs/sql-docs#9766]
I just found a Translation mistake in chinese doc
![f110e225031d22bb186380f1077563b](https://github.com/MicrosoftDocs/sql-docs/assets/130046092/63f210a3-aaf8-4262-a95f-6ae772bd3113)
the word 'select' and 'insert' need to change their position
here is the link https://learn.microsoft.com/zh-cn/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-ver16#Lock_Basics

but it's correct in English doc
![IV{F2Y5MN0LC_FD2DC%AZXT](https://github.com/MicrosoftDocs/sql-docs/assets/130046092/b0fd55a9-8426-43ed-8953-d07d31f179ae)
english doc link:https://learn.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-ver16#Lock_Basics

i can't edit chinese doc.so i submit an issue.
sorry for my bad english,hope you can understand.

**Comment by rwestMSFT** [comment]
Please submit this correction on https://aka.ms/provide-feedback. There's nothing we can do from our side (we fill in the same form).
