### ISSUE TITLE
Possible typos in documentation?

### ISSUE THREAD

**Issue by gilesp-pageup** [MicrosoftDocs/sql-docs#9771]
On docs/linux/sql-server-linux-create-availability-group.md and docs/linux/sql-server-linux-availability-group-cluster-pacemaker.md there are references to a 'failover-timeout' meta parameter, but I can't identify whether this is actually a valid setting.

On [docs/linux/sql-server-linux-availability-group-cluster-pacemaker.md](https://github.com/MicrosoftDocs/sql-docs/blob/afec4836198e877d40dfd0603cb287945a3489f9/docs/linux/sql-server-linux-availability-group-cluster-pacemaker.md?plain=1#L149) immediately below on line 157 the documentation instead refers to the more expected 'failure-timeout' meta parameter for Pacemaker.

With regards to ocf:mssql:ag there doesn't appear to be any use of a parameter named failover-timeout either, despite the documentation suggesting otherwise.

Happy to put in a pull request with corrections, but thought I'd open an issue first to verify, as nobody seems to really know for sure.

**Comment by rwestMSFT** [comment]
@gilesp-pageup We are no longer tracking Docs issues here. Please provide feedback using the **Feedback** option on the article in question. We will be able to triage and address it then.

![Screenshot 2024-04-29 at 14 27 46](https://github.com/MicrosoftDocs/sql-docs/assets/97149825/70e14d30-807a-4c8f-9f0f-dd09600d96ad)

**Comment by gilesp-pageup** [comment]
Feedback has been submitted. Happy to make the PR myself, if it is confirmed to be a mistake in the documentation.

**Comment by rwestMSFT** [comment]
Thanks, @gilesp-pageup. We appreciate your feedback.
