### ISSUE TITLE
Release notes for Report Viewer controls are outdated

### ISSUE THREAD

**Issue by OronDF343** [MicrosoftDocs/sql-docs#9772]
Hi,

Once again the release notes for Report Viewer controls [here](https://learn.microsoft.com/en-us/sql/reporting-services/application-integration/release-notes-ssrs-application-integration?view=sql-server-ver15) are outdated.

Of the versions listed for the [NuGet package](https://www.nuget.org/packages/Microsoft.ReportingServices.ReportViewerControl.WebForms#versions-body-tab), the following versions on the 150 branch do not have corresponding release notes:

|Version      |Release Date|
|------------|-------------|
|150.1440.0|2/18/2021|
|150.1449.0|3/25/2021|
|150.1576.0|5/8/2023|
|150.1585.0|6/23/2023|
|150.1620.0|3 months ago|

**Comment by rwestMSFT** [comment]
Please submit your feedback using the Feedback option on the article itself. We are not monitoring GitHub issues any longer.

![Screenshot 2024-04-30 at 11 43 31](https://github.com/MicrosoftDocs/sql-docs/assets/97149825/4d881146-5479-4741-9a43-70eb00e406be)
